var searchData=
[
  ['udictionary',['UDictionary',['../classFoam_1_1UDictionary.html',1,'Foam']]],
  ['uiliststream',['uiliststream',['../classFoam_1_1uiliststream.html',1,'uiliststream'],['../classFoam_1_1UIListStream.html',1,'UIListStream']]],
  ['uiliststreamallocator',['UIListStreamAllocator',['../classFoam_1_1Detail_1_1UIListStreamAllocator.html',1,'Foam::Detail']]],
  ['uillist',['UILList',['../classFoam_1_1UILList.html',1,'Foam']]],
  ['uindirectlist',['UIndirectList',['../classFoam_1_1UIndirectList.html',1,'Foam']]],
  ['uipstream',['UIPstream',['../classFoam_1_1UIPstream.html',1,'Foam']]],
  ['ulist',['UList',['../classFoam_1_1UList.html',1,'Foam']]],
  ['ulist_3c_20datatype_20_3e',['UList&lt; DataType &gt;',['../classFoam_1_1UList.html',1,'Foam']]],
  ['ulist_3c_20face_20_3e',['UList&lt; Face &gt;',['../classFoam_1_1UList.html',1,'UList&lt; Face &gt;'],['../classFoam_1_1UList.html',1,'UList&lt; face &gt;']]],
  ['ulist_3c_20foam_3a_3asurfzone_20_3e',['UList&lt; Foam::surfZone &gt;',['../classFoam_1_1UList.html',1,'Foam']]],
  ['ulist_3c_20foam_3a_3avector_20_3e',['UList&lt; Foam::Vector &gt;',['../classFoam_1_1UList.html',1,'Foam']]],
  ['ulist_3c_20foam_3a_3awordre_20_3e',['UList&lt; Foam::wordRe &gt;',['../classFoam_1_1UList.html',1,'Foam']]],
  ['ulist_3c_20label_20_3e',['UList&lt; label &gt;',['../classFoam_1_1UList.html',1,'Foam']]],
  ['ulist_3c_20stringtype_20_3e',['UList&lt; StringType &gt;',['../classFoam_1_1UList.html',1,'Foam']]],
  ['ulist_3c_20type_20_3e',['UList&lt; Type &gt;',['../classFoam_1_1UList.html',1,'Foam']]],
  ['umistlimiter',['UMISTLimiter',['../classFoam_1_1UMISTLimiter.html',1,'Foam']]],
  ['unavailablefunctionobject',['unavailableFunctionObject',['../classFoam_1_1functionObject_1_1unavailableFunctionObject.html',1,'Foam::functionObject']]],
  ['uncollatedfileoperation',['uncollatedFileOperation',['../classFoam_1_1fileOperations_1_1uncollatedFileOperation.html',1,'Foam::fileOperations']]],
  ['uncorrectedsngrad',['uncorrectedSnGrad',['../classFoam_1_1fv_1_1uncorrectedSnGrad.html',1,'Foam::fv']]],
  ['uncoupledsixdofrigidbodydisplacementpointpatchvectorfield',['uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField',['../classFoam_1_1uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField.html',1,'Foam']]],
  ['undoablemeshcutter',['undoableMeshCutter',['../classFoam_1_1undoableMeshCutter.html',1,'Foam']]],
  ['uniform',['uniform',['../classFoam_1_1distributionModels_1_1uniform.html',1,'Foam::distributionModels']]],
  ['uniform',['Uniform',['../classFoam_1_1Function1Types_1_1Uniform.html',1,'Foam::Function1Types']]],
  ['uniform',['uniform',['../classFoam_1_1uniform.html',1,'Foam']]],
  ['uniform',['uniform',['../classFoam_1_1windowModels_1_1uniform.html',1,'Foam::windowModels']]],
  ['uniformbinary',['uniformBinary',['../classFoam_1_1diameterModels_1_1daughterSizeDistributionModels_1_1uniformBinary.html',1,'Foam::diameterModels::daughterSizeDistributionModels']]],
  ['uniformdensityhydrostaticpressurefvpatchscalarfield',['uniformDensityHydrostaticPressureFvPatchScalarField',['../classFoam_1_1uniformDensityHydrostaticPressureFvPatchScalarField.html',1,'Foam']]],
  ['uniformdiffusivity',['uniformDiffusivity',['../classFoam_1_1uniformDiffusivity.html',1,'Foam']]],
  ['uniformdimensionedfield',['UniformDimensionedField',['../classFoam_1_1UniformDimensionedField.html',1,'Foam']]],
  ['uniformdimensionedfield_3c_20scalar_20_3e',['UniformDimensionedField&lt; scalar &gt;',['../classFoam_1_1UniformDimensionedField.html',1,'Foam']]],
  ['uniformdimensionedfield_3c_20vector_20_3e',['UniformDimensionedField&lt; vector &gt;',['../classFoam_1_1UniformDimensionedField.html',1,'Foam']]],
  ['uniformdistance',['uniformDistance',['../classFoam_1_1uniformDistance.html',1,'Foam']]],
  ['uniformfield',['UniformField',['../classFoam_1_1UniformField.html',1,'Foam']]],
  ['uniformfixedgradientfvpatchfield',['uniformFixedGradientFvPatchField',['../classFoam_1_1uniformFixedGradientFvPatchField.html',1,'Foam']]],
  ['uniformfixedvaluefvpatchfield',['uniformFixedValueFvPatchField',['../classFoam_1_1uniformFixedValueFvPatchField.html',1,'Foam']]],
  ['uniformfixedvaluepointpatchfield',['uniformFixedValuePointPatchField',['../classFoam_1_1uniformFixedValuePointPatchField.html',1,'Foam']]],
  ['uniformgeneratorop',['uniformGeneratorOp',['../classFoam_1_1Random_1_1uniformGeneratorOp.html',1,'Foam::Random']]],
  ['uniformgrid',['uniformGrid',['../classFoam_1_1uniformGrid.html',1,'Foam']]],
  ['uniforminletoutletfvpatchfield',['uniformInletOutletFvPatchField',['../classFoam_1_1uniformInletOutletFvPatchField.html',1,'Foam']]],
  ['uniforminterpolateddisplacementpointpatchvectorfield',['uniformInterpolatedDisplacementPointPatchVectorField',['../classFoam_1_1uniformInterpolatedDisplacementPointPatchVectorField.html',1,'Foam']]],
  ['uniforminterpolationtable',['uniformInterpolationTable',['../classFoam_1_1uniformInterpolationTable.html',1,'Foam']]],
  ['uniforminterpolationtable_3c_20scalar_20_3e',['uniformInterpolationTable&lt; scalar &gt;',['../classFoam_1_1uniformInterpolationTable.html',1,'Foam']]],
  ['uniformjumpamifvpatchfield',['uniformJumpAMIFvPatchField',['../classFoam_1_1uniformJumpAMIFvPatchField.html',1,'Foam']]],
  ['uniformjumpfvpatchfield',['uniformJumpFvPatchField',['../classFoam_1_1uniformJumpFvPatchField.html',1,'Foam']]],
  ['uniformnormalfixedvaluefvpatchvectorfield',['uniformNormalFixedValueFvPatchVectorField',['../classFoam_1_1uniformNormalFixedValueFvPatchVectorField.html',1,'Foam']]],
  ['uniformop',['uniformOp',['../classFoam_1_1cut_1_1uniformOp.html',1,'Foam::cut']]],
  ['uniformop_3c_20container_20_26_20_3e',['uniformOp&lt; Container &amp; &gt;',['../classFoam_1_1cut_1_1uniformOp.html',1,'Foam::cut']]],
  ['uniformop_3c_20zero_3a_3anull_20_3e',['uniformOp&lt; zero::null &gt;',['../classFoam_1_1cut_1_1uniformOp.html',1,'Foam::cut']]],
  ['uniformset',['uniformSet',['../classFoam_1_1uniformSet.html',1,'Foam']]],
  ['uniformtotalpressurefvpatchscalarfield',['uniformTotalPressureFvPatchScalarField',['../classFoam_1_1uniformTotalPressureFvPatchScalarField.html',1,'Foam']]],
  ['uniformvalue',['uniformValue',['../classFoam_1_1uniformValue.html',1,'Foam']]],
  ['uniformvaluefield',['UniformValueField',['../classFoam_1_1PatchFunction1Types_1_1UniformValueField.html',1,'Foam::PatchFunction1Types']]],
  ['unioneqop',['unionEqOp',['../classFoam_1_1cellToFaceStencil_1_1unionEqOp.html',1,'Foam::cellToFaceStencil']]],
  ['unioneqop',['unionEqOp',['../classFoam_1_1cellToCellStencil_1_1unionEqOp.html',1,'Foam::cellToCellStencil']]],
  ['uniqueeqop',['uniqueEqOp',['../structFoam_1_1ListOps_1_1uniqueEqOp.html',1,'Foam::ListOps']]],
  ['unmappedpassivepositionparticlecloud',['unmappedPassivePositionParticleCloud',['../classFoam_1_1unmappedPassivePositionParticleCloud.html',1,'Foam']]],
  ['unsortedmeshedsurface',['UnsortedMeshedSurface',['../classFoam_1_1UnsortedMeshedSurface.html',1,'Foam']]],
  ['unthreadedinitialise',['unthreadedInitialise',['../classFoam_1_1unthreadedInitialise.html',1,'Foam']]],
  ['unthreadedinitialise',['unthreadedInitialise',['../classFoam_1_1fileOperations_1_1unthreadedInitialise.html',1,'Foam::fileOperations']]],
  ['unwatchediodictionary',['unwatchedIOdictionary',['../classFoam_1_1unwatchedIOdictionary.html',1,'Foam']]],
  ['uoliststream',['UOListStream',['../classFoam_1_1UOListStream.html',1,'Foam']]],
  ['uoliststreamallocator',['UOListStreamAllocator',['../classFoam_1_1Detail_1_1UOListStreamAllocator.html',1,'Foam::Detail']]],
  ['uoprocess',['UOprocess',['../classFoam_1_1UOprocess.html',1,'Foam']]],
  ['uopstream',['UOPstream',['../classFoam_1_1UOPstream.html',1,'Foam']]],
  ['updateablemeshobject',['UpdateableMeshObject',['../classFoam_1_1UpdateableMeshObject.html',1,'Foam']]],
  ['updateablemeshobject_3c_20fvmesh_20_3e',['UpdateableMeshObject&lt; fvMesh &gt;',['../classFoam_1_1UpdateableMeshObject.html',1,'Foam']]],
  ['updateablemeshobject_3c_20pointmesh_20_3e',['UpdateableMeshObject&lt; pointMesh &gt;',['../classFoam_1_1UpdateableMeshObject.html',1,'Foam']]],
  ['updateablemeshobject_3c_20polymesh_20_3e',['UpdateableMeshObject&lt; polyMesh &gt;',['../classFoam_1_1UpdateableMeshObject.html',1,'Foam']]],
  ['updatemethod',['updateMethod',['../classFoam_1_1updateMethod.html',1,'Foam']]],
  ['updateop',['updateOp',['../classFoam_1_1updateOp.html',1,'Foam']]],
  ['upstream',['UPstream',['../classFoam_1_1UPstream.html',1,'Foam']]],
  ['uptrdictionary',['UPtrDictionary',['../classFoam_1_1UPtrDictionary.html',1,'Foam']]],
  ['uptrlist',['UPtrList',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20const_20lduinterface_20_3e',['UPtrList&lt; const lduInterface &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20const_20lduinterfacefield_20_3e',['UPtrList&lt; const lduInterfaceField &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20const_20lduinterfacefield_3c_20type_20_3e_20_3e',['UPtrList&lt; const LduInterfaceField&lt; Type &gt; &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20foam_3a_3adiametermodels_3a_3asizegroup_20_3e',['UPtrList&lt; Foam::diameterModels::sizeGroup &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20foam_3a_3adiametermodels_3a_3avelocitygroup_20_3e',['UPtrList&lt; Foam::diameterModels::velocityGroup &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20foam_3a_3afield_3c_20type_20_3e_20_3e',['UPtrList&lt; Foam::Field&lt; Type &gt; &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20foam_3a_3ageometricfield_20_3e',['UPtrList&lt; Foam::GeometricField &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20foam_3a_3aphasemodel_20_3e',['UPtrList&lt; Foam::phaseModel &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20foam_3a_3aradiation_3a_3areflectionmodel_20_3e',['UPtrList&lt; Foam::radiation::reflectionModel &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20foam_3a_3asearchablesurface_20_3e',['UPtrList&lt; Foam::searchableSurface &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['uptrlist_3c_20phasemodel_20_3e',['UPtrList&lt; phaseModel &gt;',['../classFoam_1_1UPtrList.html',1,'Foam']]],
  ['upwind',['upwind',['../classFoam_1_1upwind.html',1,'Foam']]],
  ['upwindceccelltofacestencilobject',['upwindCECCellToFaceStencilObject',['../classFoam_1_1upwindCECCellToFaceStencilObject.html',1,'Foam']]],
  ['upwindcfccelltofacestencilobject',['upwindCFCCellToFaceStencilObject',['../classFoam_1_1upwindCFCCellToFaceStencilObject.html',1,'Foam']]],
  ['upwindcpccelltofacestencilobject',['upwindCPCCellToFaceStencilObject',['../classFoam_1_1upwindCPCCellToFaceStencilObject.html',1,'Foam']]],
  ['upwindedgeinterpolation',['upwindEdgeInterpolation',['../classFoam_1_1upwindEdgeInterpolation.html',1,'Foam']]],
  ['upwindfeccelltofacestencilobject',['upwindFECCellToFaceStencilObject',['../classFoam_1_1upwindFECCellToFaceStencilObject.html',1,'Foam']]],
  ['upwindfitdata',['UpwindFitData',['../classFoam_1_1UpwindFitData.html',1,'Foam']]],
  ['upwindfitscheme',['UpwindFitScheme',['../classFoam_1_1UpwindFitScheme.html',1,'Foam']]]
];
