OpenFOAM: integrationScheme Class Reference
integrationScheme Class Reference abstract
Base for a set of schemes which integrate simple ODEs which arise from semi-implcit rate expressions.
Public Member Functions
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, integrationScheme, word,(),())
Declare runtime constructor selection table.
integrationScheme ()
Construct.
virtual autoPtr
< integrationScheme > clone () const =0
Construct and return clone.
virtual ~integrationScheme ()
Destructor.
template<class Type >
Type delta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta) const
Perform the integration.
template<class Type >
Type partialDelta (const Type &phi, const scalar dt, const Type &Alpha, const scalar Beta, const Type &alphai, const scalar betai) const
Perform a part of the integration.
virtual scalar dtEff (const scalar dt, const scalar Beta) const =0
Return the integration effective time step.
virtual scalar sumDtEff (const scalar dt, const scalar Beta) const =0
Return the integral of the effective time step.
Static Public Member Functions
static autoPtr< integrationScheme > New (const word &phiName, const dictionary &dict)
Select an integration scheme.
template<class Type >
static Type explicitDelta (const Type &phi, const scalar dtEff, const Type &Alpha, const scalar Beta)
Perform the integration explicitly.
Detailed Description
Base for a set of schemes which integrate simple ODEs which arise from semi-implcit rate expressions.
The methods are defined in terms of the effective time-step by which the explicit rate is multipled. The effective time-step is a function of the actual time step and the implicit coefficient, which must be implemented in each derived scheme.
This class also facilitates integration in stages. If the explicit and implicit coefficients, and , are a summation of differing contributions, and , then the integration can be split up to detemine the effect of each contribution.
These partial calculations are defined in terms of the integral of the effective time-step, , which is also implemented in every derivation.
Source files
integrationScheme.H
integrationScheme.C
Definition at line 86 of file integrationScheme.H.
Constructor & Destructor Documentation
integrationScheme ()
Construct.
Definition at line 33 of file integrationScheme.C.
References Foam::defineRunTimeSelectionTable(), and Foam::defineTypeNameAndDebug().
~integrationScheme () virtual
Destructor.
Definition at line 39 of file integrationScheme.C.
Member Function Documentation
TypeName ("integrationScheme")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , integrationScheme , word , () , ())
Declare runtime constructor selection table.
virtual autoPtr<integrationScheme> clone () const pure virtual
Construct and return clone.
Implemented in analytical, and Euler.
Foam::autoPtr< Foam::integrationScheme > New (const word & phiName, const dictionary & dict) static
Select an integration scheme.
Definition at line 28 of file integrationSchemeNew.C.
References Foam::abort(), Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Type explicitDelta (const Type & phi, const scalar dtEff, const Type & Alpha, const scalar Beta) inline static
Perform the integration explicitly.
Definition at line 27 of file integrationSchemeTemplates.C.
Type delta (const Type & phi, const scalar dt, const Type & Alpha, const scalar Beta) const inline
Perform the integration.
Definition at line 40 of file integrationSchemeTemplates.C.
References integrationScheme::dtEff().
Type partialDelta (const Type & phi, const scalar dt, const Type & Alpha, const scalar Beta, const Type & alphai, const scalar betai) const inline
Perform a part of the integration.
Definition at line 53 of file integrationSchemeTemplates.C.
virtual scalar dtEff (const scalar dt, const scalar Beta) const pure virtual
Return the integration effective time step.
Implemented in analytical, and Euler.
Referenced by integrationScheme::delta().
virtual scalar sumDtEff (const scalar dt, const scalar Beta) const pure virtual
Return the integral of the effective time step.
Implemented in Euler, and analytical.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationScheme.H
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationScheme.C
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationSchemeNew.C
src/lagrangian/intermediate/integrationScheme/integrationScheme/integrationSchemeTemplates.C