OpenFOAM: indirect Class Reference
indirect Class Reference
A coordinate system forward to a global coordinate system that is normally provided by the constant/coordinateSystems file.
Public Member Functions
TypeName ("indirect")
Runtime type information.
indirect (const indirect &csys)
Copy construct.
indirect (indirect &&csys)
Move construct.
indirect (const objectRegistry &obr, const word &name)
Construct from global lookup.
indirect (const objectRegistry &obr, const dictionary &dict)
Construct from global lookup.
virtual autoPtr< coordinateSystem > clone () const
Return clone.
virtual ~indirect ()=default
Destructor.
virtual const coordinateSystem & cs () const
Reference to the underlying coordinate system.
virtual bool valid () const
Is the coordinate system valid?
virtual bool uniform () const
True if the rotation tensor is uniform for all positions.
virtual const coordinateRotation & rotation () const
The rotation specification.
virtual const word & name () const
Return the name.
virtual const string & note () const
Return the optional note.
virtual const point & origin () const
Return origin.
virtual const tensor & R () const
Return const reference to the rotation tensor.
virtual const vector e1 () const
The local Cartesian x-axis in global coordinates.
virtual const vector e2 () const
The local Cartesian y-axis in global coordinates.
virtual const vector e3 () const
The local Cartesian z-axis in global coordinates.
void rename (const word &newName)
Rename (ignored)
string & note ()
Provide non-constant access to the optional note.
virtual point & origin ()
Edit access to origin (disallowed)
virtual void clear ()
Clear (ignored)
virtual void rotation (autoPtr< coordinateRotation > &&crot)
Change the rotation (disallowed)
virtual void write (Ostream &os) const
Write.
virtual void writeEntry (const word &keyword, Ostream &os) const
Write dictionary entry.
void operator= (const coordinateSystem &csys)=delete
No copy assignment.
void operator= (coordinateSystem &&csys)=delete
No move assignment.
virtual tensor R (const point &global) const
Position-dependent rotation tensor at a single point.
virtual tmp< tensorField > R (const UList< point > &global) const
Position-dependent rotation tensors at multiple points.
virtual tmp< tensorField > R (const pointUIndList &global) const
Position-dependent rotation tensors at multiple points.
Public Member Functions inherited from coordinateSystem
TypeName ("coordinateSystem")
Runtime type information.
coordinateSystem ()
Construct null. This is an identity coordinateSystem.
coordinateSystem (const coordinateRotation &crot)
Copy construct from rotation with origin=0.
coordinateSystem (coordinateRotation &&crot)
Move construct from rotation with origin=0.
coordinateSystem (const coordinateSystem &csys)
Copy construct.
coordinateSystem (coordinateSystem &&csys)
Move construct.
coordinateSystem (autoPtr< coordinateSystem > &&csys)
Move construct from autoPtr.
coordinateSystem (const word &name, const coordinateSystem &csys)
Copy construct with a different name.
coordinateSystem (const point &origin, const coordinateRotation &crot)
Construct from origin and rotation.
coordinateSystem (const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const point &origin, const coordinateRotation &crot)
Construct from origin and rotation.
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const dictionary &dict)
Construct from dictionary with a given name.
coordinateSystem (const dictionary &dict)
Construct from dictionary without a name.
coordinateSystem (const dictionary &dict, const word &dictName)
Construct from dictionary with optional subDict lookup.
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, coordinateSystem, registry,(const objectRegistry &obr, const dictionary &dict),(obr, dict))
virtual ~coordinateSystem ()=default
Destructor.
void operator= (const coordinateSystem &csys)
Copy assignment.
void operator= (coordinateSystem &&csys)
Move assignment.
void operator= (const autoPtr< coordinateSystem > &csys)
Copy assignment from autoPtr.
void operator= (autoPtr< coordinateSystem > &&csys)
Move assignment from autoPtr.
point transformPoint (const point &localCart) const
Transform point and add origin offset.
tmp< pointField > transformPoint (const UList< point > &localCart) const
Transform points and add origin offset.
tmp< pointField > transformPoint (const pointUIndList &localCart) const
Transform points and add origin offset.
point invTransformPoint (const point &global) const
Remove origin offset and inverse transform point.
tmp< pointField > invTransformPoint (const UList< point > &global) const
Remove origin offset and inverse transform points.
tmp< pointField > invTransformPoint (const pointUIndList &global) const
Remove origin offset and inverse transform points.
point globalPosition (const point &local) const
From local coordinate position to global (cartesian) position.
tmp< pointField > globalPosition (const pointField &local) const
From local coordinate position to global (cartesian) position.
point localPosition (const point &global) const
From global (cartesian) position to local coordinate position.
tmp< pointField > localPosition (const pointField &global) const
From global (cartesian) position to local coordinate position.
vector globalVector (const vector &local) const
From local to global (cartesian) vector components.
tmp< vectorField > globalVector (const vectorField &local) const
From local to global (cartesian) vector components.
vector localVector (const vector &global) const
From global (cartesian) to local vector components.
tmp< vectorField > localVector (const vectorField &global) const
From global (cartesian) to local vector components.
virtual symmTensor transformPrincipal (const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< vector > &input) const
virtual symmTensor transformPrincipal (const point &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const UList< vector > &input) const
virtual scalar transform (const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< scalar > &input) const
virtual scalar transform (const point &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< point > &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< point > &global, const UList< scalar > &input) const
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const UList< scalar > &input) const
virtual vector transform (const vector &input) const
virtual tmp< Field< vector > > transform (const UList< vector > &input) const
virtual vector transform (const point &global, const vector &input) const
virtual tmp< Field< vector > > transform (const UList< point > &global, const vector &input) const
virtual tmp< Field< vector > > transform (const pointUIndList &global, const vector &input) const
virtual tmp< Field< vector > > transform (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< vector > > transform (const pointUIndList &global, const UList< vector > &input) const
virtual sphericalTensor transform (const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< sphericalTensor > &input) const
virtual sphericalTensor transform (const point &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< point > &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const pointUIndList &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< point > &global, const UList< sphericalTensor > &input) const
virtual tmp< Field
< sphericalTensor > > transform (const pointUIndList &global, const UList< sphericalTensor > &input) const
virtual symmTensor transform (const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< symmTensor > &input) const
virtual symmTensor transform (const point &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const UList< symmTensor > &input) const
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const UList< symmTensor > &input) const
virtual tensor transform (const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< tensor > &input) const
virtual tensor transform (const point &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< point > &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< point > &global, const UList< tensor > &input) const
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const UList< tensor > &input) const
virtual scalar invTransform (const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< scalar > &input) const
virtual scalar invTransform (const point &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const UList< scalar > &input) const
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const UList< scalar > &input) const
virtual vector invTransform (const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< vector > &input) const
virtual vector invTransform (const point &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const UList< vector > &input) const
virtual sphericalTensor invTransform (const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< sphericalTensor > &input) const
virtual sphericalTensor invTransform (const point &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< point > &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const pointUIndList &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< point > &global, const UList< sphericalTensor > &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const pointUIndList &global, const UList< sphericalTensor > &input) const
virtual symmTensor invTransform (const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< symmTensor > &input) const
virtual symmTensor invTransform (const point &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const UList< symmTensor > &input) const
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const UList< symmTensor > &input) const
virtual tensor invTransform (const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< tensor > &input) const
virtual tensor invTransform (const point &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const UList< tensor > &input) const
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const UList< tensor > &input) const
template<class PointField >
Foam::tmp< Foam::tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
Foam::tmp< Foam::pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
Foam::tmp< Foam::pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Protected Member Functions
virtual vector localToGlobal (const vector &local, bool translate) const
Convert from local coordinate system to the global Cartesian system with optional translation for the origin.
virtual tmp< vectorField > localToGlobal (const vectorField &local, bool translate) const
Convert from local coordinate system to the global Cartesian system with optional translation for the origin.
virtual vector globalToLocal (const vector &global, bool translate) const
Convert from global Cartesian system to the local coordinate system with optional translation for the origin.
virtual tmp< vectorField > globalToLocal (const vectorField &global, bool translate) const
Convert from global Cartesian system to the local coordinate system with optional translation for the origin.
Protected Member Functions inherited from coordinateSystem
template<class PointField >
tmp< tensorField > rotationsImpl (const PointField &global) const
Implementation for R() methods.
template<class PointField >
tmp< pointField > transformPointImpl (const PointField &localCart) const
Implementation for transformPoint() methods.
template<class PointField >
tmp< pointField > invTransformPointImpl (const PointField &global) const
Implementation for transformPosition() methods.
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
Use position-dependent transform tensors for multiple inputs.
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Use position-dependent transform tensors for single input.
void assign (const dictionary &dict)
Assign from dictionary content.
coordinateSystem (std::nullptr_t)
Construct null, without allocating a coordinateRotation specification.
Additional Inherited Members
Static Public Member Functions inherited from coordinateSystem
static autoPtr< coordinateSystem > New (word modelType, const objectRegistry &obr, const dictionary &dict)
Select construct the specified coordinate system type with reference to objectRegistry for indirect entries.
static autoPtr< coordinateSystem > New (word modelType, const dictionary &dict)
Select construct the specified coordinate system type.
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict, const word &dictName="")
Select construct from dictionary with reference to objectRegistry for indirect entries.
static autoPtr< coordinateSystem > New (const dictionary &dict, const word &dictName="")
Select constructed from dictionary.
static autoPtr< coordinateSystem > New (Istream &is)
Select constructed from Istream.
Static Protected Member Functions inherited from coordinateSystem
template<class RetType , class Type , class BinaryOp >
static tmp< Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
Apply single transform tensor for multiple inputs.
Protected Attributes inherited from coordinateSystem
autoPtr< coordinateRotation > spec_
User specification of the coordinate rotation.
point origin_
The coordinate system origin.
tensor rot_
The rotation tensor.
word name_
The name of the coordinate system (optional)
string note_
An optional note describing the coordinate system.
Static Protected Attributes inherited from coordinateSystem
static coordinateSystem dummy_
Dummy coordinate system for suppressed manipulation.
Detailed Description
A coordinate system forward to a global coordinate system that is normally provided by the constant/coordinateSystems file.
Dictionary entries
Property Description Required Default
type Type name: indirect yes
name Name of the referenced system yes
Source files
indirectCS.H
indirectCS.C
Definition at line 71 of file indirectCS.H.
Constructor & Destructor Documentation
indirect (const indirect & csys)
Copy construct.
Definition at line 39 of file indirectCS.C.
indirect (indirect && csys)
Move construct.
Definition at line 46 of file indirectCS.C.
indirect (const objectRegistry & obr, const word & name)
Construct from global lookup.
Definition at line 55 of file indirectCS.C.
indirect (const objectRegistry & obr, const dictionary & dict)
Construct from global lookup.
Definition at line 66 of file indirectCS.C.
virtual ~indirect () virtual default
Destructor.
Member Function Documentation
virtual vector localToGlobal (const vector & local, bool translate) const inline protected virtual
Convert from local coordinate system to the global Cartesian system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 100 of file indirectCS.H.
virtual tmp<vectorField> localToGlobal (const vectorField & local, bool translate) const inline protected virtual
Convert from local coordinate system to the global Cartesian system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 113 of file indirectCS.H.
References coordinateSystem::globalToLocal().
virtual vector globalToLocal (const vector & global, bool translate) const inline protected virtual
Convert from global Cartesian system to the local coordinate system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 126 of file indirectCS.H.
virtual tmp<vectorField> globalToLocal (const vectorField & global, bool translate) const inline protected virtual
Convert from global Cartesian system to the local coordinate system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 139 of file indirectCS.H.
TypeName ("indirect")
Runtime type information.
virtual autoPtr<coordinateSystem> clone () const inline virtual
Return clone.
Reimplemented from coordinateSystem.
Definition at line 181 of file indirectCS.H.
References coordinateSystem::rotation().
virtual const coordinateSystem& cs () const inline virtual
Reference to the underlying coordinate system.
Definition at line 200 of file indirectCS.H.
virtual bool valid () const inline virtual
Is the coordinate system valid?
Reimplemented from coordinateSystem.
Definition at line 208 of file indirectCS.H.
References coordinateSystem::e1().
virtual bool uniform () const inline virtual
True if the rotation tensor is uniform for all positions.
Reimplemented from coordinateSystem.
Definition at line 216 of file indirectCS.H.
References coordinateSystem::e2().
virtual const coordinateRotation& rotation () const inline virtual
The rotation specification.
Reimplemented from coordinateSystem.
Definition at line 224 of file indirectCS.H.
virtual const word& name () const inline virtual
Return the name.
Reimplemented from coordinateSystem.
Definition at line 232 of file indirectCS.H.
References coordinateSystem::dummy_, coordinateSystem::note(), and NotImplemented.
virtual const string& note () const inline virtual
Return the optional note.
Reimplemented from coordinateSystem.
Definition at line 240 of file indirectCS.H.
References coordinateSystem::dummy_, NotImplemented, and coordinateSystem::origin().
virtual const point& origin () const inline virtual
Return origin.
Reimplemented from coordinateSystem.
Definition at line 248 of file indirectCS.H.
virtual const tensor& R () const inline virtual
Return const reference to the rotation tensor.
Reimplemented from coordinateSystem.
Definition at line 256 of file indirectCS.H.
virtual const vector e1 () const inline virtual
The local Cartesian x-axis in global coordinates.
Reimplemented from coordinateSystem.
Definition at line 264 of file indirectCS.H.
virtual const vector e2 () const inline virtual
The local Cartesian y-axis in global coordinates.
Reimplemented from coordinateSystem.
Definition at line 272 of file indirectCS.H.
virtual const vector e3 () const inline virtual
The local Cartesian z-axis in global coordinates.
Reimplemented from coordinateSystem.
Definition at line 280 of file indirectCS.H.
void rename (const word & newName) inline virtual
Rename (ignored)
Reimplemented from coordinateSystem.
Definition at line 291 of file indirectCS.H.
References coordinateSystem::R().
string& note () inline virtual
Provide non-constant access to the optional note.
Reimplemented from coordinateSystem.
Definition at line 296 of file indirectCS.H.
virtual point& origin () inline virtual
Edit access to origin (disallowed)
Reimplemented from coordinateSystem.
Definition at line 305 of file indirectCS.H.
virtual void clear () inline virtual
Clear (ignored)
Reimplemented from coordinateSystem.
Definition at line 314 of file indirectCS.H.
virtual void rotation (autoPtr< coordinateRotation > && crot) inline virtual
Change the rotation (disallowed)
Reimplemented from coordinateSystem.
Definition at line 319 of file indirectCS.H.
void write (Ostream & os) const virtual
Write.
Reimplemented from coordinateSystem.
Definition at line 77 of file indirectCS.C.
void writeEntry (const word & keyword, Ostream & os) const virtual
Write dictionary entry.
Reimplemented from coordinateSystem.
Definition at line 84 of file indirectCS.C.
void operator= (const coordinateSystem & csys) delete
No copy assignment.
void operator= (coordinateSystem && csys) delete
No move assignment.
virtual tensor R (const point & global) const inline virtual
Position-dependent rotation tensor at a single point.
Reimplemented from coordinateSystem.
Definition at line 356 of file indirectCS.H.
virtual tmp<tensorField> R (const UList< point > & global) const inline virtual
Position-dependent rotation tensors at multiple points.
Reimplemented from coordinateSystem.
Definition at line 364 of file indirectCS.H.
virtual tmp<tensorField> R (const pointUIndList & global) const inline virtual
Position-dependent rotation tensors at multiple points.
Reimplemented from coordinateSystem.
Definition at line 372 of file indirectCS.H.
The documentation for this class was generated from the following files:
src/meshTools/coordinate/systems/indirectCS.H
src/meshTools/coordinate/systems/indirectCS.C