OpenFOAM: PairCollisionRecord< Type > Class Template Reference
PairCollisionRecord< Type > Class Template Reference
Record of a collision between the particle holding the record and the particle with the stored id.
Public Member Functions
PairCollisionRecord ()
Construct null.
PairCollisionRecord (bool accessed, label origProcOfOther, label origIdOfOther, const Type &data=Type(Zero))
Construct from components.
PairCollisionRecord (Istream &)
Construct from Istream.
PairCollisionRecord (const PairCollisionRecord &)
Construct as copy.
~PairCollisionRecord ()
Destructor.
label origProcOfOther () const
Return the origProcOfOther data.
label origIdOfOther () const
Return the origIdOfOther data.
const Type & collisionData () const
Return access to the collision data.
Type & collisionData ()
Return access to the collision data.
bool match (label queryOrigProcOfOther, label queryOrigIdOfOther) const
bool accessed () const
Return the accessed status of the record.
void setAccessed ()
Set the accessed property of the record to accessed.
void setUnaccessed ()
Set the accessed property of the record to unaccessed.
void operator= (const PairCollisionRecord &)
Friends
bool operator== (const PairCollisionRecord< Type > &, const PairCollisionRecord< Type > &)
bool operator!= (const PairCollisionRecord< Type > &, const PairCollisionRecord< Type > &)
Istream & operator>> (Istream &, PairCollisionRecord< Type > &)
Ostream & operator (Ostream &, const PairCollisionRecord< Type > &)
Detailed Description
template<class Type>
class Foam::PairCollisionRecord< Type >
Record of a collision between the particle holding the record and the particle with the stored id.
The access status of the record is to be coded in the origProcOfOther data member. The actual processor is offset by +1. A negative value means that the record has not been accessed, positive means that it has.
Source files
PairCollisionRecord.H
PairCollisionRecordI.H
PairCollisionRecord.C
PairCollisionRecordIO.C
Definition at line 54 of file PairCollisionRecord.H.
Constructor & Destructor Documentation
PairCollisionRecord ()
Construct null.
Definition at line 27 of file PairCollisionRecord.C.
PairCollisionRecord (bool accessed, label origProcOfOther, label origIdOfOther, const Type & data = Type(Zero))
Construct from components.
Definition at line 37 of file PairCollisionRecord.C.
PairCollisionRecord (Istream & is)
Construct from Istream.
Definition at line 27 of file PairCollisionRecordIO.C.
References IOstream::check(), and FUNCTION_NAME.
PairCollisionRecord (const PairCollisionRecord< Type > &)
Construct as copy.
~PairCollisionRecord ()
Destructor.
Definition at line 72 of file PairCollisionRecord.C.
Member Function Documentation
Foam::label origProcOfOther () const inline
Return the origProcOfOther data.
Definition at line 39 of file PairCollisionRecordI.H.
Foam::label origIdOfOther () const inline
Return the origIdOfOther data.
Definition at line 46 of file PairCollisionRecordI.H.
References Foam::mag().
const Type & collisionData () const inline
Return access to the collision data.
Definition at line 54 of file PairCollisionRecordI.H.
Type & collisionData () inline
Return access to the collision data.
Definition at line 61 of file PairCollisionRecordI.H.
bool match (label queryOrigProcOfOther, label queryOrigIdOfOther) const inline
Definition at line 25 of file PairCollisionRecordI.H.
bool accessed () const inline
Return the accessed status of the record.
Definition at line 68 of file PairCollisionRecordI.H.
void setAccessed () inline
Set the accessed property of the record to accessed.
Definition at line 75 of file PairCollisionRecordI.H.
References Foam::pos0().
void setUnaccessed () inline
Set the accessed property of the record to unaccessed.
Definition at line 82 of file PairCollisionRecordI.H.
void operator= (const PairCollisionRecord< Type > &)
Definition at line 80 of file PairCollisionRecord.C.
Friends And Related Function Documentation
bool operator== (const PairCollisionRecord< Type > & , const PairCollisionRecord< Type > &) friend
bool operator!= (const PairCollisionRecord< Type > & , const PairCollisionRecord< Type > &) friend
Istream& operator>> (Istream & , PairCollisionRecord< Type > &) friend
Ostream& operator (Ostream & , const PairCollisionRecord< Type > &) friend
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecord.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecord.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecordI.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/PairCollisionRecord/PairCollisionRecordIO.C