OpenFOAM: globalIndex Class Reference
globalIndex Class Reference
Calculates a unique integer (label so might not have enough room - 2G max) for processor + local index. E.g.
Public Member Functions
globalIndex ()=default
Construct null.
globalIndex (const label localSize)
Construct from local max size.
globalIndex (const label localSize, const int tag, const label comm, const bool parallel)
Construct from local max size.
globalIndex (const labelUList &offsets)
Copy construct from list of labels.
globalIndex (labelList &&offsets)
Move construct from list of labels.
globalIndex (Istream &is)
Construct from Istream.
bool empty () const
Check for null constructed or global sum == 0.
const labelList & offsets () const
Const-access to the offsets.
label size () const
Global sum of localSizes.
labelList sizes () const
The local sizes.
labelList & offsets ()
Write-access to the offsets, for changing after construction.
void reset (const label localSize)
Reset from local size.
void reset (const label localSize, const int tag, const label comm, const bool parallel)
Reset from local size.
label localStart () const
My local start.
label localSize () const
My local size.
labelRange range () const
Return start/size range of local processor data.
bool isLocal (const label i) const
Is on local processor.
label toGlobal (const label i) const
From local to global index.
labelList toGlobal (const labelUList &labels) const
From local to global index.
void inplaceToGlobal (labelList &labels) const
From local to global index (inplace)
label toLocal (const label i) const
From global to local on current processor.
label offset (const label proci) const
Start of proci data.
label localStart (const label proci) const
Start of proci data.
label localSize (const label proci) const
Size of proci data.
labelRange range (const label proci) const
Return start/size range of proci data.
bool isLocal (const label proci, const label i) const
Is on processor proci.
label toGlobal (const label proci, const label i) const
From local to global on proci.
labelList toGlobal (const label proci, const labelUList &labels) const
From local to global on proci.
void inplaceToGlobal (const label proci, labelList &labels) const
From local to global index on proci (inplace)
label toLocal (const label proci, const label i) const
From global to local on proci.
label whichProcID (const label i) const
Which processor does global come from? Binary search.
template<class Container , class Type >
void gather (const label comm, const Container &procIDs, const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking) const
Collect data in processor order on master (== procIDs[0]).
template<class Type >
void gather (const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking) const
Collect data in processor order on master.
template<class Container , class Type >
void gather (const label comm, const Container &procIDs, List< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking) const
Inplace collect in processor order on master (== procIDs[0]). Needs offsets only on master.
template<class Type >
void gather (List< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking) const
Inplace collect data in processor order on master.
template<class Container , class Type >
void scatter (const label comm, const Container &procIDs, const UList< Type > &allFld, UList< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking) const
Distribute data in processor order. Requires fld to be sized!
template<class Type >
void scatter (const UList< Type > &allFld, UList< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking) const
Distribute data in processor order. Requires fld to be sized!
template<class Type , class CombineOp >
void get (List< Type > &allFld, const labelUList &globalIds, const CombineOp &cop, const label comm=Pstream::worldComm, const int tag=UPstream::msgType()) const
Get (potentially remote) data. Elements required given as.
Static Public Member Functions
template<class Container , class Type >
static void gather (const labelUList &offsets, const label comm, const Container &procIDs, const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking)
Collect data in processor order on master (== procIDs[0]).
template<class Type >
static void gatherOp (const UList< Type > &fld, List< Type > &allFld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking)
Collect data in processor order on master.
template<class Container , class Type >
static void gather (const labelUList &offsets, const label comm, const Container &procIDs, List< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking)
Inplace collect in processor order on master (== procIDs[0]). Needs offsets only on master.
template<class Type >
static void gatherOp (List< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking)
Inplace collect data in processor order on master.
template<class Container , class Type >
static void scatter (const labelUList &offsets, const label comm, const Container &procIDs, const UList< Type > &allFld, UList< Type > &fld, const int tag=UPstream::msgType(), const Pstream::commsTypes commsType=Pstream::commsTypes::nonBlocking)
Distribute data in processor order. Requires fld to be sized!
Friends
Istream & operator>> (Istream &is, globalIndex &gi)
Ostream & operator<< (Ostream &os, const globalIndex &gi)
Detailed Description
Calculates a unique integer (label so might not have enough room - 2G max) for processor + local index. E.g.
globalIndex globalFaces(mesh.nFaces()); label globalFacei = globalFaces.toGlobal(facei);
Source files
globalIndex.H
globalIndexI.H
globalIndex.C
globalIndexTemplates.C
Definition at line 64 of file globalIndex.H.
Constructor & Destructor Documentation
globalIndex () default
Construct null.
globalIndex (const label localSize) inline explicit
Construct from local max size.
Does communication with default communicator and message tag.
Definition at line 27 of file globalIndexI.H.
globalIndex (const label localSize, const int tag, const label comm, const bool parallel) inline
Construct from local max size.
Does communication with given communicator and message tag
Parameters
tag message tag
comm communicator
parallel use parallel comms
Definition at line 36 of file globalIndexI.H.
References reset().
globalIndex (const labelUList & offsets) inline explicit
Copy construct from list of labels.
Definition at line 49 of file globalIndexI.H.
References reset().
globalIndex (labelList && offsets) inline explicit
Move construct from list of labels.
Definition at line 55 of file globalIndexI.H.
globalIndex (Istream & is) explicit
Construct from Istream.
Definition at line 26 of file globalIndex.C.
Member Function Documentation
bool empty () const inline
Check for null constructed or global sum == 0.
Definition at line 63 of file globalIndexI.H.
const Foam::labelList & offsets () const inline
Const-access to the offsets.
Definition at line 69 of file globalIndexI.H.
Foam::label size () const inline
Global sum of localSizes.
Definition at line 81 of file globalIndexI.H.
Foam::labelList sizes () const
The local sizes.
Definition at line 133 of file globalIndex.C.
Foam::labelList & offsets () inline
Write-access to the offsets, for changing after construction.
Definition at line 75 of file globalIndexI.H.
void reset (const label localSize) inline
Reset from local size.
Does communication with default communicator and message tag.
Definition at line 87 of file globalIndexI.H.
Referenced by distributedTriSurfaceMesh::globalTris().
void reset (const label localSize, const int tag, const label comm, const bool parallel)
Reset from local size.
Does communication with given communicator and message tag
Parameters
tag message tag
comm communicator
parallel use parallel comms
Definition at line 95 of file globalIndex.C.
Foam::label localStart () const inline
My local start.
Definition at line 105 of file globalIndexI.H.
Foam::label localSize () const inline
My local size.
Definition at line 117 of file globalIndexI.H.
Foam::labelRange range () const inline
Return start/size range of local processor data.
Definition at line 129 of file globalIndexI.H.
bool isLocal (const label i) const inline
Is on local processor.
Definition at line 141 of file globalIndexI.H.
Referenced by regionSplit::reduceRegions().
Foam::label toGlobal (const label i) const inline
From local to global index.
Definition at line 157 of file globalIndexI.H.
Referenced by regionSplit::reduceRegions(), regionSplit2D::regionSplit2D(), and cellVolumeWeight::update().
Foam::labelList toGlobal (const labelUList & labels) const inline
From local to global index.
Definition at line 177 of file globalIndexI.H.
void inplaceToGlobal (labelList & labels) const inline
From local to global index (inplace)
Definition at line 200 of file globalIndexI.H.
References Foam::val.
Foam::label toLocal (const label i) const inline
From global to local on current processor.
FatalError if not on local processor.
Definition at line 222 of file globalIndexI.H.
Referenced by distributedTriSurfaceMesh::localQueries().
Foam::label offset (const label proci) const inline
Start of proci data.
Definition at line 93 of file globalIndexI.H.
References UPstream::msgType(), and reset().
Foam::label localStart (const label proci) const inline
Start of proci data.
Definition at line 99 of file globalIndexI.H.
Foam::label localSize (const label proci) const inline
Size of proci data.
Definition at line 111 of file globalIndexI.H.
References UPstream::myProcNo().
Foam::labelRange range (const label proci) const inline
Return start/size range of proci data.
Definition at line 123 of file globalIndexI.H.
References UPstream::myProcNo().
bool isLocal (const label proci, const label i) const inline
Is on processor proci.
Definition at line 135 of file globalIndexI.H.
References UPstream::myProcNo(), and range.
Foam::label toGlobal (const label proci, const label i) const inline
From local to global on proci.
Definition at line 148 of file globalIndexI.H.
References UPstream::myProcNo().
Foam::labelList toGlobal (const label proci, const labelUList & labels) const inline
From local to global on proci.
Definition at line 164 of file globalIndexI.H.
References UPstream::myProcNo().
void inplaceToGlobal (const label proci, labelList & labels) const inline
From local to global index on proci (inplace)
Definition at line 186 of file globalIndexI.H.
References UPstream::myProcNo().
Foam::label toLocal (const label proci, const label i) const inline
From global to local on proci.
Definition at line 207 of file globalIndexI.H.
References UPstream::myProcNo().
Foam::label whichProcID (const label i) const inline
Which processor does global come from? Binary search.
Definition at line 228 of file globalIndexI.H.
References UPstream::myProcNo().
Referenced by distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::localQueries(), and regionSplit::reduceRegions().
void gather (const labelUList & offsets, const label comm, const Container & procIDs, const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) static
Collect data in processor order on master (== procIDs[0]).
Needs offsets only on master.
Definition at line 28 of file globalIndexTemplates.C.
References UList< T >::begin(), UPstream::blocking, UList< T >::byteSize(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld, i, UList< T >::last(), UPstream::myProcNo(), UPstream::nRequests(), UIPstream::read(), UPstream::scheduled, List< T >::setSize(), UList< T >::size(), UPstream::waitRequests(), and UOPstream::write().
Referenced by PatchTools::gatherAndMerge().
void gather (const label comm, const Container & procIDs, const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) const inline
Collect data in processor order on master (== procIDs[0]).
Needs offsets only on master.
Definition at line 319 of file globalIndex.H.
void gather (const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) const
Collect data in processor order on master.
Does communication with default communicator and message tag.
Definition at line 180 of file globalIndexTemplates.C.
void gatherOp (const UList< Type > & fld, List< Type > & allFld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) static
Collect data in processor order on master.
Does communication with default communicator and message tag.
Definition at line 201 of file globalIndexTemplates.C.
void gather (const labelUList & offsets, const label comm, const Container & procIDs, List< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) static
Inplace collect in processor order on master (== procIDs[0]). Needs offsets only on master.
Definition at line 214 of file globalIndexTemplates.C.
References UList< T >::size().
void gather (const label comm, const Container & procIDs, List< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) const inline
Inplace collect in processor order on master (== procIDs[0]). Needs offsets only on master.
Definition at line 385 of file globalIndex.H.
void gather (List< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) const
Inplace collect data in processor order on master.
Does communication with default communicator and message tag. After the gather, the field is zero-sized on the slaves.
Definition at line 236 of file globalIndexTemplates.C.
void gatherOp (List< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) static
Inplace collect data in processor order on master.
Does communication with default communicator and message tag. After the gather, the field is zero-sized on the slaves.
Definition at line 267 of file globalIndexTemplates.C.
void scatter (const labelUList & offsets, const label comm, const Container & procIDs, const UList< Type > & allFld, UList< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) static
Distribute data in processor order. Requires fld to be sized!
Definition at line 279 of file globalIndexTemplates.C.
void scatter (const label comm, const Container & procIDs, const UList< Type > & allFld, UList< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) const inline
Distribute data in processor order. Requires fld to be sized!
Definition at line 449 of file globalIndex.H.
void scatter (const UList< Type > & allFld, UList< Type > & fld, const int tag = UPstream::msgType(), const Pstream::commsTypes commsType = Pstream::commsTypes::nonBlocking) const
Distribute data in processor order. Requires fld to be sized!
Does communication with default communicator and message tag.
Definition at line 438 of file globalIndexTemplates.C.
void get (List< Type > & allFld, const labelUList & globalIds, const CombineOp & cop, const label comm = Pstream::worldComm, const int tag = UPstream::msgType()) const
Get (potentially remote) data. Elements required given as.
global indices
Definition at line 460 of file globalIndexTemplates.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, globalIndex & gi) friend
Ostream& operator<< (Ostream & os, const globalIndex & gi) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndex.H
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndex.C
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndexI.H
src/OpenFOAM/meshes/polyMesh/globalMeshData/globalIndexTemplates.C