OpenFOAM: STARCDCore Class Reference
STARCDCore Class Reference
Core routines used when reading/writing PROSTAR vrt/cel/bnd files.
Public Types
enum fileHeader { HEADER_CEL, HEADER_VRT, HEADER_BND }
Enumeration defining the file headers.
enum fileExt { CEL_FILE, VRT_FILE, BND_FILE, INP_FILE }
Enumeration defining the file extensions.
enum matlType {
starcdFluidType = 1, starcdSolidType = 2, starcdBaffleType = 3, starcdShellType = 4,
starcdLineType = 5, starcdPointType = 6
}
Basic material type for STARCD/PROSTAR files.
enum shapeType {
starcdPoint = 1, starcdLine = 2, starcdShell = 3, starcdHex = 11,
starcdPrism = 12, starcdTet = 13, starcdPyr = 14, starcdPoly = 255
}
Shape-Type for STARCD/PROSTAR files.
Static Public Member Functions
static fileName starFileName (const fileName &baseName, const enum fileExt ext)
Resolve base file-name for the given file-type.
static void removeFiles (const fileName &baseName)
Remove existing PROSTAR files for the given base file-name.
static label readPoints (IFstream &is, List< point > &points, List< label > &ids)
Read points from a (.vrt) file, return the max prostar id used.
static void writePoints (Ostream &os, const UList< point > &points, const scalar scaleFactor=1.0)
Write header and points to (.vrt) file, optionally with scaling.
Static Public Attributes
static const char *const defaultBoundaryName
The name for default (unassigned) boundaries.
static const char *const defaultSolidBoundaryName
The name we have chosen for default (unassigned) solid boundaries.
Protected Member Functions
STARCDCore ()=default
Construct null.
Static Protected Member Functions
static bool readHeader (IFstream &is, const enum fileHeader header)
Read header and check signature PROSTAR_(CELL|VERTEX|BOUNDARY)
static void writeHeader (Ostream &os, const enum fileHeader header)
Write header for fileType (CELL|VERTEX|BOUNDARY)
Static Protected Attributes
static const Map< FixedList
< int, 6 > > starToFoamFaceAddr
Face addressing from PROSTAR faces to OpenFOAM faces.
static const Map< FixedList
< int, 6 > > foamToStarFaceAddr
Face addressing from OpenFOAM faces to PROSTAR faces.
Detailed Description
Core routines used when reading/writing PROSTAR vrt/cel/bnd files.
Source files
STARCDCore.H
STARCDCore.C
Definition at line 55 of file STARCDCore.H.
Member Enumeration Documentation
enum fileHeader
Enumeration defining the file headers.
Enumerator
HEADER_CEL
HEADER_VRT
HEADER_BND
Definition at line 64 of file STARCDCore.H.
enum fileExt
Enumeration defining the file extensions.
Enumerator
CEL_FILE
VRT_FILE
BND_FILE
INP_FILE
Definition at line 74 of file STARCDCore.H.
enum matlType
Basic material type for STARCD/PROSTAR files.
Enumerator
starcdFluidType
starcdSolidType
starcdBaffleType
starcdShellType
starcdLineType
starcdPointType
Definition at line 85 of file STARCDCore.H.
enum shapeType
Shape-Type for STARCD/PROSTAR files.
Enumerator
starcdPoint
starcdLine
starcdShell
starcdHex
starcdPrism
starcdTet
starcdPyr
starcdPoly
Definition at line 98 of file STARCDCore.H.
Constructor & Destructor Documentation
STARCDCore () protected default
Construct null.
Member Function Documentation
bool readHeader (IFstream & is, const enum fileHeader header) static protected
Read header and check signature PROSTAR_(CELL|VERTEX|BOUNDARY)
Definition at line 115 of file STARCDCore.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, IOstream::good(), Foam::Info, ISstream::name(), Foam::nl, and Foam::readToNewline().
void writeHeader (Ostream & os, const enum fileHeader header) static protected
Write header for fileType (CELL|VERTEX|BOUNDARY)
Definition at line 149 of file STARCDCore.C.
Foam::fileName starFileName (const fileName & baseName, const enum fileExt ext) static
Resolve base file-name for the given file-type.
Definition at line 170 of file STARCDCore.C.
void removeFiles (const fileName & baseName) static
Remove existing PROSTAR files for the given base file-name.
Definition at line 179 of file STARCDCore.C.
References ext().
Foam::label readPoints (IFstream & is, List< point > & points, List< label > & ids) static
Read points from a (.vrt) file, return the max prostar id used.
The file format is as follows:
* Line 1:
* PROSTAR_VERTEX  newline
*
* Line 2:
* {version} 0 0 0 0 0 0 0  newline
*
* Body:
* {vertexId}  {x}  {y}  {z}  newline
*
Definition at line 189 of file STARCDCore.C.
void writePoints (Ostream & os, const UList< point > & points, const scalar scaleFactor = 1.0) static
Write header and points to (.vrt) file, optionally with scaling.
Definition at line 238 of file STARCDCore.C.
Member Data Documentation
const char *const defaultBoundaryName static
Initial value:
=
    "Default_Boundary_Region"
The name for default (unassigned) boundaries.
Definition at line 114 of file STARCDCore.H.
const char *const defaultSolidBoundaryName static
Initial value:
=
    "Default_Boundary_Solid"
The name we have chosen for default (unassigned) solid boundaries.
Slightly distinguished from the regular default name.
Definition at line 121 of file STARCDCore.H.
const Foam::Map< Foam::FixedList< int, 6 > > starToFoamFaceAddr static protected
Initial value:
=
{
    { starcdHex,   { 4, 5, 2, 3, 0, 1 } },
    { starcdPrism, { 0, 1, 4, -1, 2, 3 } },
    { starcdTet,   { 3, -1, 2, -1, 1, 0 } },
    { starcdPyr,   { 0, -1, 4, 2, 1, 3 } }
}
Face addressing from PROSTAR faces to OpenFOAM faces.
For hex, prism, tet, pyr primitive shapes.
Definition at line 141 of file STARCDCore.H.
Referenced by STARCDMeshReader::readBoundary().
const Foam::Map< Foam::FixedList< int, 6 > > foamToStarFaceAddr static protected
Initial value:
=
{
    { starcdHex,   { 4, 5, 2, 3, 0, 1 } },
    { starcdPrism, { 0, 1, 4, 5, 2, -1 } },
    { starcdTet,   { 5, 4, 2, 0, -1, -1 } },
    { starcdPyr,   { 0, 4, 3, 5, 2, -1 } }
}
Face addressing from OpenFOAM faces to PROSTAR faces.
For hex, prism, tet, pyr primitive shapes.
Definition at line 148 of file STARCDCore.H.
The documentation for this class was generated from the following files:
src/fileFormats/starcd/STARCDCore.H
src/fileFormats/starcd/STARCDCore.C