OpenFOAM: fieldAverageItem Class Reference
fieldAverageItem Class Reference
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
Public Types
enum baseType { ITER, TIME }
Enumeration defining the averaging base type.
enum windowType { NONE, APPROXIMATE, EXACT }
Enumeration defining the averaging window type.
Public Member Functions
fieldAverageItem ()
Construct null.
fieldAverageItem (Istream &)
Construct from Istream.
fieldAverageItem (const fieldAverageItem &)
Construct as copy.
~fieldAverageItem ()
Destructor.
bool active () const
Return const access to the active flag.
bool & active ()
Return non-const access to the active flag.
const word & fieldName () const
Return const access to the field name.
bool mean () const
Return const access to the mean flag.
bool & mean ()
Return non-const access to the mean flag.
const word & meanFieldName () const
Return const access to the mean field name.
bool prime2Mean () const
Return const access to the prime-squared mean flag.
bool & prime2Mean ()
Return non-const access to the prime-squared mean flag.
const word & prime2MeanFieldName () const
Return const access to the prime-squared mean field name.
const word & base () const
Return averaging base type name.
label totalIter () const
Return the total number of iterations item has been evolved.
scalar totalTime () const
Return the total time item has been evolved.
scalar window () const
Return the window length (iterations or seconds)
const word & windowName () const
Return the (optional) window name.
const FIFOStack< scalar > & windowTimes () const
Return the list of window times (windowType = EXACT)
const FIFOStack< word > & windowFieldNames () const
Return the list of window field names (windowType = EXACT)
bool allowRestart () const
Return the allow restart flag.
scalar dt (const scalar deltaT) const
Return the current time interval.
scalar Dt () const
Return the total time interval.
word windowFieldName (const word &prefix) const
Helper function to construct a window field name.
bool inWindow (const scalar t) const
Return true if time is inside window (including boundaries)
bool storeWindowFields () const
Return true if we wish to store window fields.
bool writeWindowFields () const
Return true if we wish to write window fields.
void addToWindow (const word &fieldName, const scalar deltaT)
Add field to window.
void evolve (const objectRegistry &obr)
Evolve and update.
void clear (const objectRegistry &obr, const bool fullClean)
Clear out all mean fields and (optionally) supporting data.
bool readState (const dictionary &dict)
Read state and re-initialise values.
void writeState (dictionary &dict) const
Write state for restart.
template<class Type >
bool calculateMeanField (const objectRegistry &obr) const
Calculate the mean field value.
template<class Type1 , class Type2 >
bool calculatePrime2MeanField (const objectRegistry &obr) const
Calculate prime-squared average fields.
void operator= (const fieldAverageItem &)
Static Public Attributes
static const word EXT_MEAN
Mean average.
static const word EXT_PRIME2MEAN
Prime-squared average.
Friends
bool operator== (const fieldAverageItem &a, const fieldAverageItem &b)
bool operator!= (const fieldAverageItem &a, const fieldAverageItem &b)
Istream & operator>> (Istream &, fieldAverageItem &)
Ostream & operator<< (Ostream &, const fieldAverageItem &)
Detailed Description
Helper class to describe what form of averaging to apply. A set will be applied to each base field in Foam::fieldAverage, of the form:
{
    mean            on;
    prime2Mean      on;
    base            time; // iteration
    window          200;  // optional averaging window
    windowName      w1;   // optional window name (default = "")
    windowType      approximate; // window type
    allowRestart    yes;  // optional, used for windowType 'exact'
}
The averaging window corresponds to the averaging interval (iters or time) If not specified, the averaging is over 'all iters/time'
Available window types:
none : no windowing
exact : exact windowing - additional files will be stored and written
approximate : approximate variant that does not store/write additional fields
Source files
fieldAverageItem.H
fieldAverageItem.C
fieldAverageItemIO.C
Definition at line 86 of file fieldAverageItem.H.
Member Enumeration Documentation
enum baseType strong
Enumeration defining the averaging base type.
Enumerator
ITER
TIME
Definition at line 108 of file fieldAverageItem.H.
enum windowType strong
Enumeration defining the averaging window type.
Enumerator
NONE
APPROXIMATE
EXACT
Definition at line 117 of file fieldAverageItem.H.
Constructor & Destructor Documentation
fieldAverageItem ()
Construct null.
Definition at line 63 of file fieldAverageItem.C.
fieldAverageItem (Istream & is)
Construct from Istream.
Definition at line 28 of file fieldAverageItemIO.C.
fieldAverageItem (const fieldAverageItem & faItem)
Construct as copy.
Definition at line 85 of file fieldAverageItem.C.
~fieldAverageItem ()
Destructor.
Definition at line 110 of file fieldAverageItem.C.
Member Function Documentation
bool active () const inline
Return const access to the active flag.
Definition at line 23 of file fieldAverageItemI.H.
Referenced by fieldAverage::addMeanFieldType().
bool & active () inline
Return non-const access to the active flag.
Definition at line 29 of file fieldAverageItemI.H.
const Foam::word & fieldName () const inline
Return const access to the field name.
Definition at line 35 of file fieldAverageItemI.H.
Referenced by fieldAverage::addMeanFieldType(), and fieldAverageItem::calculateMeanField().
bool mean () const inline
Return const access to the mean flag.
Definition at line 41 of file fieldAverageItemI.H.
Referenced by fieldAverage::addMeanFieldType().
bool & mean () inline
Return non-const access to the mean flag.
Definition at line 47 of file fieldAverageItemI.H.
const Foam::word & meanFieldName () const inline
Return const access to the mean field name.
Definition at line 54 of file fieldAverageItemI.H.
Referenced by fieldAverage::addMeanFieldType().
bool prime2Mean () const inline
Return const access to the prime-squared mean flag.
Definition at line 60 of file fieldAverageItemI.H.
bool & prime2Mean () inline
Return non-const access to the prime-squared mean flag.
Definition at line 66 of file fieldAverageItemI.H.
const Foam::word & prime2MeanFieldName () const inline
Return const access to the prime-squared mean field name.
Definition at line 72 of file fieldAverageItemI.H.
const Foam::word & base () const inline
Return averaging base type name.
Definition at line 78 of file fieldAverageItemI.H.
Foam::label totalIter () const inline
Return the total number of iterations item has been evolved.
Definition at line 84 of file fieldAverageItemI.H.
Foam::scalar totalTime () const inline
Return the total time item has been evolved.
Definition at line 90 of file fieldAverageItemI.H.
Foam::scalar window () const inline
Return the window length (iterations or seconds)
Definition at line 96 of file fieldAverageItemI.H.
const Foam::word & windowName () const inline
Return the (optional) window name.
Definition at line 102 of file fieldAverageItemI.H.
const Foam::FIFOStack< Foam::scalar > & windowTimes () const inline
Return the list of window times (windowType = EXACT)
Definition at line 109 of file fieldAverageItemI.H.
const Foam::FIFOStack< Foam::word > & windowFieldNames () const inline
Return the list of window field names (windowType = EXACT)
Definition at line 116 of file fieldAverageItemI.H.
bool allowRestart () const inline
Return the allow restart flag.
Definition at line 122 of file fieldAverageItemI.H.
Foam::scalar dt (const scalar deltaT) const inline
Return the current time interval.
Definition at line 129 of file fieldAverageItemI.H.
Referenced by fieldAverageItem::calculateMeanField().
Foam::scalar Dt () const inline
Return the total time interval.
Definition at line 155 of file fieldAverageItemI.H.
Referenced by fieldAverageItem::calculateMeanField().
Foam::word windowFieldName (const word & prefix) const inline
Helper function to construct a window field name.
Definition at line 180 of file fieldAverageItemI.H.
bool inWindow (const scalar t) const inline
Return true if time is inside window (including boundaries)
Definition at line 188 of file fieldAverageItemI.H.
References Foam::name().
bool storeWindowFields () const inline
Return true if we wish to store window fields.
Definition at line 213 of file fieldAverageItemI.H.
bool writeWindowFields () const inline
Return true if we wish to write window fields.
Definition at line 219 of file fieldAverageItemI.H.
void addToWindow (const word & fieldName, const scalar deltaT)
Add field to window.
Definition at line 117 of file fieldAverageItem.C.
void evolve (const objectRegistry & obr)
Evolve and update.
Definition at line 127 of file fieldAverageItem.C.
void clear (const objectRegistry & obr, const bool fullClean)
Clear out all mean fields and (optionally) supporting data.
Definition at line 156 of file fieldAverageItem.C.
bool readState (const dictionary & dict)
Read state and re-initialise values.
Definition at line 186 of file fieldAverageItem.C.
void writeState (dictionary & dict) const
Write state for restart.
Definition at line 202 of file fieldAverageItem.C.
bool calculateMeanField (const objectRegistry & obr) const
Calculate the mean field value.
Definition at line 26 of file fieldAverageItemTemplates.C.
References Foam::abort(), fieldAverageItem::APPROXIMATE, beta(), LList< LListBase, T >::cbegin(), TimeState::deltaTValue(), fieldAverageItem::dt(), fieldAverageItem::Dt(), fieldAverageItem::EXACT, Foam::FatalError, FatalErrorInFunction, fieldAverageItem::fieldName(), objectRegistry::findObject(), LList< LListBase, T >::first(), fieldAverageItem::ITER, objectRegistry::lookupObject(), objectRegistry::lookupObjectRef(), n, fieldAverageItem::NONE, fieldAverageItem::TIME, and objectRegistry::time().
bool calculatePrime2MeanField (const objectRegistry & obr) const
Calculate prime-squared average fields.
Definition at line 161 of file fieldAverageItemTemplates.C.
void operator= (const fieldAverageItem & rhs)
Definition at line 220 of file fieldAverageItem.C.
Friends And Related Function Documentation
bool operator== (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 406 of file fieldAverageItem.H.
bool operator!= (const fieldAverageItem & a, const fieldAverageItem & b) friend
Definition at line 428 of file fieldAverageItem.H.
Istream& operator>> (Istream & , fieldAverageItem &) friend
Ostream& operator<< (Ostream & , const fieldAverageItem &) friend
Member Data Documentation
const Foam::word EXT_MEAN static
Mean average.
Definition at line 97 of file fieldAverageItem.H.
const Foam::word EXT_PRIME2MEAN static
Prime-squared average.
Definition at line 102 of file fieldAverageItem.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.H
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItem.C
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemI.H
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemIO.C
src/functionObjects/field/fieldAverage/fieldAverageItem/fieldAverageItemTemplates.C