OpenFOAM: solverControl Class Reference
solverControl Class Reference
Base class for solver control classes.
Public Member Functions
TypeName ("solverControl")
Run-time type information.
solverControl (const solver &solver)
Construct from solver.
virtual ~solverControl ()=default
Destructor.
virtual const dictionary solverDict () const
Read controls from optimisationDict.
virtual const dictionary solutionDict () const
Return the solutionControls dictionary.
bool printMaxMags () const
Print max mags of solver fields.
bool storeInitValues () const
Re-initialize.
label iter () const
Return iteration index.
label & averageIter ()
Return average iteration index reference.
label averageIter () const
Return const average iteration index reference.
label averageStartIter () const
Return iteration index.
bool doAverageIter () const
Whether or not to add fields of the current iteration to the average fields.
bool useAveragedFields () const
Use averaged fields? For solving the adjoint equations or computing sensitivities based on averaged fields.
bool average () const
Whether averaging is enabled or not.
Protected Member Functions
virtual bool read ()
Read controls from optimisationDict.
Protected Attributes
const solver & solver_
Reference to the underlaying solver.
bool printMaxMags_
Whether to print the max magnitude during each solver iteration.
label iter_
Current iteration index.
label averageIter_
Current averaging iteration index.
label averageStartIter_
Averaging start index.
bool storeInitValues_
Whether to re-initialize the solution based on the initial time step. Makes sense only for optimisation or FD runs.
bool average_
Do averaging.
Detailed Description
Base class for solver control classes.
Definition at line 45 of file solverControl.H.
Constructor & Destructor Documentation
solverControl (const solver & solver)
Construct from solver.
Definition at line 49 of file solverControl.C.
virtual ~solverControl () virtual default
Destructor.
Member Function Documentation
bool read () protected virtual
Read controls from optimisationDict.
Reimplemented in SIMPLEControl, SIMPLEControlOpt, and SIMPLEControlSingleRun.
Definition at line 34 of file solverControl.C.
References Foam::defineTypeNameAndDebug().
TypeName ("solverControl")
Run-time type information.
const Foam::dictionary solverDict () const inline virtual
Read controls from optimisationDict.
Return the solver dictionary
Definition at line 26 of file solverControlI.H.
const Foam::dictionary solutionDict () const inline virtual
Return the solutionControls dictionary.
Definition at line 32 of file solverControlI.H.
References solver::dict(), and solverControl::solver_.
Referenced by SIMPLEControl::pRefCell().
bool printMaxMags () const inline
Print max mags of solver fields.
Definition at line 38 of file solverControlI.H.
References dictionary::subDict().
bool storeInitValues () const inline
Re-initialize.
Definition at line 44 of file solverControlI.H.
Referenced by incompressibleVars::computeMeanFields().
Foam::label iter () const inline
Return iteration index.
Definition at line 50 of file solverControlI.H.
Foam::label & averageIter () inline
Return average iteration index reference.
Definition at line 56 of file solverControlI.H.
Foam::label averageIter () const inline
Return const average iteration index reference.
Definition at line 62 of file solverControlI.H.
Foam::label averageStartIter () const inline
Return iteration index.
Definition at line 68 of file solverControlI.H.
bool doAverageIter () const inline
Whether or not to add fields of the current iteration to the average fields.
Definition at line 74 of file solverControlI.H.
bool useAveragedFields () const inline
Use averaged fields? For solving the adjoint equations or computing sensitivities based on averaged fields.
Definition at line 87 of file solverControlI.H.
bool average () const inline
Whether averaging is enabled or not.
Definition at line 100 of file solverControlI.H.
Referenced by incompressibleAdjointMeanFlowVars::getSolverControl(), and incompressibleVars::transfer().
Member Data Documentation
const solver& solver_ protected
Reference to the underlaying solver.
Definition at line 54 of file solverControl.H.
Referenced by solverControl::solutionDict().
bool printMaxMags_ protected
Whether to print the max magnitude during each solver iteration.
Useful for adjoint solvers
Definition at line 63 of file solverControl.H.
label iter_ protected
Current iteration index.
Definition at line 71 of file solverControl.H.
label averageIter_ protected
Current averaging iteration index.
Definition at line 76 of file solverControl.H.
label averageStartIter_ protected
Averaging start index.
Definition at line 81 of file solverControl.H.
bool storeInitValues_ protected
Whether to re-initialize the solution based on the initial time step. Makes sense only for optimisation or FD runs.
Definition at line 89 of file solverControl.H.
bool average_ protected
Do averaging.
Definition at line 94 of file solverControl.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/solverControl/solverControl.H
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/solverControl/solverControl.C
src/optimisation/adjointOptimisation/adjoint/solvers/solverControl/solverControl/solverControlI.H