OpenFOAM: adjointOutletFluxFvPatchScalarField Class Reference
adjointOutletFluxFvPatchScalarField Class Reference
Public Member Functions
TypeName ("adjointOutletFlux")
Runtime type information.
adjointOutletFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
adjointOutletFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
adjointOutletFluxFvPatchScalarField (const adjointOutletFluxFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given adjointOutletFluxFvPatchScalarField onto a new patch.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
adjointOutletFluxFvPatchScalarField (const adjointOutletFluxFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the evaluation of the value of this patchField with given weights.
virtual tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the evaluation of the value of this patchField with given weights.
virtual tmp< Field< scalar > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the evaluation of the gradient of this patchField.
virtual tmp< Field< scalar > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the evaluation of the gradient of this patchField.
virtual void write (Ostream &) const
Write.
Detailed Description
Source files
adjointOutletFluxFvPatchScalarField.H
adjointOutletFluxFvPatchScalarField.C
Definition at line 49 of file adjointOutletFluxFvPatchScalarField.H.
Constructor & Destructor Documentation
adjointOutletFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 35 of file adjointOutletFluxFvPatchScalarField.C.
References p.
adjointOutletFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 57 of file adjointOutletFluxFvPatchScalarField.C.
adjointOutletFluxFvPatchScalarField (const adjointOutletFluxFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given adjointOutletFluxFvPatchScalarField onto a new patch.
Definition at line 45 of file adjointOutletFluxFvPatchScalarField.C.
adjointOutletFluxFvPatchScalarField (const adjointOutletFluxFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 73 of file adjointOutletFluxFvPatchScalarField.C.
Member Function Documentation
TypeName ("adjointOutletFlux")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 97 of file adjointOutletFluxFvPatchScalarField.H.
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 118 of file adjointOutletFluxFvPatchScalarField.H.
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 84 of file adjointOutletFluxFvPatchScalarField.C.
tmp< Field< scalar > > valueInternalCoeffs (const tmp< scalarField > &) const virtual
Return the matrix diagonal coefficients corresponding to the evaluation of the value of this patchField with given weights.
Definition at line 98 of file adjointOutletFluxFvPatchScalarField.C.
tmp< Field< scalar > > valueBoundaryCoeffs (const tmp< scalarField > &) const virtual
Return the matrix source coefficients corresponding to the evaluation of the value of this patchField with given weights.
Definition at line 107 of file adjointOutletFluxFvPatchScalarField.C.
References Foam::New(), and Foam::Zero.
tmp< Field< scalar > > gradientBoundaryCoeffs () const virtual
Return the matrix source coefficients corresponding to the evaluation of the gradient of this patchField.
Definition at line 116 of file adjointOutletFluxFvPatchScalarField.C.
References Foam::New(), and Foam::Zero.
tmp< Field< scalar > > gradientInternalCoeffs () const virtual
Return the matrix diagonal coefficients corresponding to the evaluation of the gradient of this patchField.
Definition at line 123 of file adjointOutletFluxFvPatchScalarField.C.
References Foam::New(), and Foam::Zero.
void write (Ostream & os) const virtual
Write.
Definition at line 129 of file adjointOutletFluxFvPatchScalarField.C.
References Foam::New(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointRAS/derivedFvPatchFields/adjointOutletFlux/adjointOutletFluxFvPatchScalarField.H
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointRAS/derivedFvPatchFields/adjointOutletFlux/adjointOutletFluxFvPatchScalarField.C