OpenFOAM: patchIdentifier Class Reference
patchIdentifier Class Reference
Identifies a patch by name, patch index and physical type.
Public Member Functions
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &p, const label index)
Copy construct, resetting the index.
virtual ~patchIdentifier ()=default
Destructor.
const word & name () const
Return the patch name.
word & name ()
Modifiable patch name.
const word & physicalType () const
The optional physical type of the patch.
word & physicalType ()
Modifiable optional physical type of the patch.
label index () const
The index of this patch in the boundaryMesh.
label & index ()
Modifiable the index of this patch in the boundaryMesh.
const wordList & inGroups () const
The optional groups that the patch belongs to.
wordList & inGroups ()
Modifiable optional groups that the patch belongs to.
bool inGroup (const word &name) const
Check if the patch is in named group.
void write (Ostream &os) const
Write patchIdentifier as a dictionary.
Friends
Ostream & operator<< (Ostream &os, const patchIdentifier &p)
Detailed Description
Identifies a patch by name, patch index and physical type.
Source files
patchIdentifier.H
patchIdentifier.C
Definition at line 53 of file patchIdentifier.H.
Constructor & Destructor Documentation
patchIdentifier (const word & name, const label index, const word & physicalType = word::null, const wordList & inGroups = wordList())
Construct from components.
Definition at line 28 of file patchIdentifier.C.
patchIdentifier (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 43 of file patchIdentifier.C.
patchIdentifier (const patchIdentifier & p, const label index)
Copy construct, resetting the index.
Definition at line 58 of file patchIdentifier.C.
References dictionary::readIfPresent().
virtual ~patchIdentifier () virtual default
Destructor.
Member Function Documentation
const word& name () const inline
Return the patch name.
Definition at line 123 of file patchIdentifier.H.
Referenced by fvMeshTools::addPatch(), emptyFaPatch::clone(), symmetryFaPatch::clone(), cyclicPolyPatch::clone(), ConstantField< Type >::ConstantField(), snappyLayerDriver::doLayers(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), genericFaPatchField< Type >::genericFaPatchField(), faPatch::New(), waveModel::New(), and polyPatch::New().
word& name () inline
Modifiable patch name.
Definition at line 131 of file patchIdentifier.H.
const word& physicalType () const inline
The optional physical type of the patch.
Definition at line 139 of file patchIdentifier.H.
word& physicalType () inline
Modifiable optional physical type of the patch.
Definition at line 147 of file patchIdentifier.H.
label index () const inline
The index of this patch in the boundaryMesh.
Definition at line 155 of file patchIdentifier.H.
Referenced by faPatch::New(), polyPatch::New(), and fvPatch::start().
label& index () inline
Modifiable the index of this patch in the boundaryMesh.
Definition at line 163 of file patchIdentifier.H.
const wordList& inGroups () const inline
The optional groups that the patch belongs to.
Definition at line 171 of file patchIdentifier.H.
Referenced by mappedPolyPatch::mappedPolyPatch(), mappedWallPolyPatch::mappedWallPolyPatch(), oversetPolyPatch::oversetPolyPatch(), polyPatch::polyPatch(), and wallPolyPatch::wallPolyPatch().
wordList& inGroups () inline
Modifiable optional groups that the patch belongs to.
Definition at line 179 of file patchIdentifier.H.
bool inGroup (const word & name) const
Check if the patch is in named group.
Definition at line 72 of file patchIdentifier.C.
void write (Ostream & os) const
Write patchIdentifier as a dictionary.
Definition at line 78 of file patchIdentifier.C.
References UList< T >::found().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const patchIdentifier & p) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/Identifiers/patch/patchIdentifier.H
src/OpenFOAM/meshes/Identifiers/patch/patchIdentifier.C