OpenFOAM: csvTableReader< Type > Class Template Reference
csvTableReader< Type > Class Template Reference
Reads an interpolation table from a file - CSV-format.
Public Member Functions
TypeName ("csv")
Runtime type information.
csvTableReader (const dictionary &dict)
Construct from dictionary.
virtual autoPtr< tableReader
< Type > > clone () const
Construct and return a copy.
virtual ~csvTableReader ()
Destructor.
virtual void operator() (const fileName &, List< Tuple2< scalar, Type >> &)
Read the table.
virtual void operator() (const fileName &, List< Tuple2< scalar, List< Tuple2< scalar, Type >>>> &)
Read 2D table.
virtual void write (Ostream &os) const
Write the remaining parameters.
Public Member Functions inherited from tableReader< Type >
TypeName ("tableReader")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, tableReader, dictionary,(const dictionary &dict),(dict))
tableReader (const dictionary &dict)
Construct from dictionary.
virtual ~tableReader ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from tableReader< Type >
static autoPtr< tableReader > New (const dictionary &spec)
Return a reference to the selected tableReader.
Detailed Description
template<class Type>
class Foam::csvTableReader< Type >
Reads an interpolation table from a file - CSV-format.
Source files
csvTableReader.H
tableReader.C
Definition at line 48 of file csvTableReader.H.
Constructor & Destructor Documentation
csvTableReader (const dictionary & dict)
Construct from dictionary.
Definition at line 28 of file csvTableReader.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
~csvTableReader () virtual
Destructor.
Definition at line 49 of file csvTableReader.C.
Member Function Documentation
TypeName ("csv")
Runtime type information.
virtual autoPtr<tableReader<Type> > clone () const inline virtual
Construct and return a copy.
Implements tableReader< Type >.
Definition at line 98 of file csvTableReader.H.
void operator() (const fileName & fName, List< Tuple2< scalar, Type >> & data) virtual
Read the table.
Implements tableReader< Type >.
Definition at line 98 of file csvTableReader.C.
void operator() (const fileName & fName, List< Tuple2< scalar, List< Tuple2< scalar, Type >>>> & data) virtual
Read 2D table.
Implements tableReader< Type >.
Definition at line 157 of file csvTableReader.C.
void write (Ostream & os) const virtual
Write the remaining parameters.
Reimplemented from tableReader< Type >.
Definition at line 167 of file csvTableReader.C.
References NotImplemented.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationTable/tableReaders/csv/csvTableReader.H
src/OpenFOAM/interpolations/interpolationTable/tableReaders/csv/csvTableReader.C