OpenFOAM: chemistryReader< ThermoType > Class Template Reference
chemistryReader< ThermoType > Class Template Reference abstract
Chemistry readers
Abstract class for reading chemistry.
Public Types
typedef ThermoType thermoType
The type of thermo package the reader was instantiated for.
Public Member Functions
TypeName ("chemistryReader")
Runtime type information.
chemistryReader ()
Construct null.
declareRunTimeSelectionTable (autoPtr, chemistryReader, dictionary,(const dictionary &thermoDict, speciesTable &species),(thermoDict, species))
virtual ~chemistryReader ()=default
Destructor.
virtual const speciesTable & species () const =0
Return access to the list of species.
virtual const
speciesCompositionTable & specieComposition () const =0
Table of species composition.
virtual const HashPtrTable
< ThermoType > & speciesThermo () const =0
Return access to the thermo packages.
virtual const ReactionList
< ThermoType > & reactions () const =0
Return access to the list of reactions.
Static Public Member Functions
static autoPtr< chemistryReader > New (const dictionary &thermoDict, speciesTable &species)
Select constructed from dictionary.
Detailed Description
template<class ThermoType>
class Foam::chemistryReader< ThermoType >
Abstract class for reading chemistry.
Source files
chemistryReader.H
chemistryReader.C
Definition at line 57 of file chemistryReader.H.
Member Typedef Documentation
typedef ThermoType thermoType
The type of thermo package the reader was instantiated for.
Definition at line 69 of file chemistryReader.H.
Constructor & Destructor Documentation
chemistryReader () inline
Construct null.
Definition at line 77 of file chemistryReader.H.
virtual ~chemistryReader () virtual default
Destructor.
Member Function Documentation
TypeName ("chemistryReader< ThermoType >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , chemistryReader< ThermoType > , dictionary , (const dictionary &thermoDict, speciesTable &species) , (thermoDict, species))
Foam::autoPtr< Foam::chemistryReader< ThermoType > > New (const dictionary & thermoDict, speciesTable & species) static
Select constructed from dictionary.
Definition at line 29 of file chemistryReader.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, dictionary::lookupOrDefault(), and thermoDict.
virtual const speciesTable& species () const pure virtual
Return access to the list of species.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
virtual const speciesCompositionTable& specieComposition () const pure virtual
Table of species composition.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
virtual const HashPtrTable<ThermoType>& speciesThermo () const pure virtual
Return access to the thermo packages.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
virtual const ReactionList<ThermoType>& reactions () const pure virtual
Return access to the list of reactions.
Implemented in chemkinReader, and foamChemistryReader< ThermoType >.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/chemistryReaders/chemistryReader/chemistryReader.H
src/thermophysicalModels/reactionThermo/chemistryReaders/chemistryReader/chemistryReader.C