OpenFOAM: mapDistributePolyMesh Class Reference
mapDistributePolyMesh Class Reference
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
Public Member Functions
mapDistributePolyMesh ()
Construct null.
mapDistributePolyMesh (mapDistributePolyMesh &&map)
Move construct.
mapDistributePolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList &&oldPatchStarts, labelList &&oldPatchNMeshPoints, labelListList &&subPointMap, labelListList &&subFaceMap, labelListList &&subCellMap, labelListList &&subPatchMap, labelListList &&constructPointMap, labelListList &&constructFaceMap, labelListList &&constructCellMap, labelListList &&constructPatchMap, const bool subFaceHasFlip=false, const bool constructFaceHasFlip=false)
Construct from components. Note that mesh has to be changed already.
mapDistributePolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, labelList &&oldPatchStarts, labelList &&oldPatchNMeshPoints, mapDistribute &&pointMap, mapDistribute &&faceMap, mapDistribute &&cellMap, mapDistribute &&patchMap)
Move construct from components.
mapDistributePolyMesh (Istream &is)
Construct from Istream.
label nOldPoints () const
Number of points in mesh before distribution.
label nOldFaces () const
Number of faces in mesh before distribution.
label nOldCells () const
Number of cells in mesh before distribution.
const labelList & oldPatchSizes () const
List of the old patch sizes.
const labelList & oldPatchStarts () const
List of the old patch start labels.
const labelList & oldPatchNMeshPoints () const
List of numbers of mesh points per old patch.
const mapDistribute & pointMap () const
Point distribute map.
const mapDistribute & faceMap () const
Face distribute map.
const mapDistribute & cellMap () const
Cell distribute map.
const mapDistribute & patchMap () const
Patch distribute map.
void transfer (mapDistributePolyMesh &map)
Transfer the contents of the argument and annul the argument.
template<class T >
void distributePointData (List< T > &lst) const
Distribute list of point data.
template<class T >
void distributeFaceData (List< T > &lst) const
Distribute list of face data.
template<class T >
void distributeCellData (List< T > &lst) const
Distribute list of cell data.
template<class T >
void distributePatchData (List< T > &lst) const
Distribute list of patch data.
void distributePointIndices (labelList &pointIDs) const
Distribute list of point/face/cell/patch indices.
void distributeFaceIndices (labelList &faceIDs) const
void distributeCellIndices (labelList &cellIDs) const
void distributePatchIndices (labelList &patchIDs) const
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistributePolyMesh &map)
Copy assignment.
void operator= (mapDistributePolyMesh &&map)
Move assignment.
Friends
Istream & operator>> (Istream &, mapDistributePolyMesh &)
Read dictionary from Istream.
Ostream & operator<< (Ostream &, const mapDistributePolyMesh &)
Write dictionary to Ostream.
Detailed Description
Class containing mesh-to-mesh mapping information after a mesh distribution where we send parts of meshes (using subsetting) to other processors and receive and reconstruct mesh.
We store mapping from the bits-to-send to the complete starting mesh (subXXXMap) and from the received bits to their location in the new mesh (constructXXXMap).
Source files
mapDistributePolyMesh.H
mapDistributePolyMesh.C
Definition at line 62 of file mapDistributePolyMesh.H.
Constructor & Destructor Documentation
mapDistributePolyMesh ()
Construct null.
Definition at line 57 of file mapDistributePolyMesh.C.
mapDistributePolyMesh (mapDistributePolyMesh && map)
Move construct.
Definition at line 73 of file mapDistributePolyMesh.C.
mapDistributePolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList && oldPatchStarts, labelList && oldPatchNMeshPoints, labelListList && subPointMap, labelListList && subFaceMap, labelListList && subCellMap, labelListList && subPatchMap, labelListList && constructPointMap, labelListList && constructFaceMap, labelListList && constructCellMap, labelListList && constructPatchMap, const bool subFaceHasFlip = false, const bool constructFaceHasFlip = false)
Construct from components. Note that mesh has to be changed already.
since uses mesh.nPoints etc as the new size.
Definition at line 84 of file mapDistributePolyMesh.C.
References transfer().
mapDistributePolyMesh (const label nOldPoints, const label nOldFaces, const label nOldCells, labelList && oldPatchStarts, labelList && oldPatchNMeshPoints, mapDistribute && pointMap, mapDistribute && faceMap, mapDistribute && cellMap, mapDistribute && patchMap)
Move construct from components.
Definition at line 148 of file mapDistributePolyMesh.C.
mapDistributePolyMesh (Istream & is)
Construct from Istream.
Definition at line 178 of file mapDistributePolyMesh.C.
Member Function Documentation
label nOldPoints () const inline
Number of points in mesh before distribution.
Definition at line 206 of file mapDistributePolyMesh.H.
label nOldFaces () const inline
Number of faces in mesh before distribution.
Definition at line 214 of file mapDistributePolyMesh.H.
label nOldCells () const inline
Number of cells in mesh before distribution.
Definition at line 222 of file mapDistributePolyMesh.H.
const labelList& oldPatchSizes () const inline
List of the old patch sizes.
Definition at line 230 of file mapDistributePolyMesh.H.
const labelList& oldPatchStarts () const inline
List of the old patch start labels.
Definition at line 238 of file mapDistributePolyMesh.H.
const labelList& oldPatchNMeshPoints () const inline
List of numbers of mesh points per old patch.
Definition at line 246 of file mapDistributePolyMesh.H.
const mapDistribute& pointMap () const inline
Point distribute map.
Definition at line 254 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
const mapDistribute& faceMap () const inline
Face distribute map.
Definition at line 262 of file mapDistributePolyMesh.H.
References mapDistribute::distribute().
const mapDistribute& cellMap () const inline
Cell distribute map.
Definition at line 270 of file mapDistributePolyMesh.H.
const mapDistribute& patchMap () const inline
Patch distribute map.
Definition at line 278 of file mapDistributePolyMesh.H.
References NotImplemented.
void transfer (mapDistributePolyMesh & map)
Transfer the contents of the argument and annul the argument.
Definition at line 186 of file mapDistributePolyMesh.C.
void distributePointData (List< T > & lst) const inline
Distribute list of point data.
Definition at line 295 of file mapDistributePolyMesh.H.
void distributeFaceData (List< T > & lst) const inline
Distribute list of face data.
Definition at line 304 of file mapDistributePolyMesh.H.
Referenced by faceBoolSet::writeDebug().
void distributeCellData (List< T > & lst) const inline
Distribute list of cell data.
Definition at line 313 of file mapDistributePolyMesh.H.
void distributePatchData (List< T > & lst) const inline
Distribute list of patch data.
Definition at line 322 of file mapDistributePolyMesh.H.
void distributePointIndices (labelList & pointIDs) const
Distribute list of point/face/cell/patch indices.
(Converts to boolList, distributes boolList and reconstructs)
Definition at line 205 of file mapDistributePolyMesh.C.
void distributeFaceIndices (labelList & faceIDs) const
Definition at line 221 of file mapDistributePolyMesh.C.
void distributeCellIndices (labelList & cellIDs) const
Definition at line 237 of file mapDistributePolyMesh.C.
void distributePatchIndices (labelList & patchIDs) const
Definition at line 253 of file mapDistributePolyMesh.C.
void updateMesh (const mapPolyMesh &) inline
Correct for topo change.
Definition at line 343 of file mapDistributePolyMesh.H.
void operator= (const mapDistributePolyMesh & map)
Copy assignment.
Definition at line 277 of file mapDistributePolyMesh.C.
Referenced by IOmapDistributePolyMesh::IOmapDistributePolyMesh().
void operator= (mapDistributePolyMesh && map)
Move assignment.
Definition at line 292 of file mapDistributePolyMesh.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , mapDistributePolyMesh &) friend
Read dictionary from Istream.
Ostream& operator<< (Ostream & , const mapDistributePolyMesh &) friend
Write dictionary to Ostream.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributePolyMesh.C