OpenFOAM: lineSearch Class Reference
lineSearch Class Reference abstract
Abstract base class for line search methods.
Public Member Functions
TypeName ("lineSearch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, lineSearch, dictionary,(const dictionary &dict, const Time &time),(dict, time))
lineSearch (const dictionary &dict, const Time &time)
Construct from components.
virtual ~lineSearch ()=default
Destructor.
virtual void setDeriv (const scalar deriv)
Set objective derivative.
void setDirection (const scalarField &direction)
Set direction.
void setNewMeritValue (const scalar value)
Set new objective value.
void setOldMeritValue (const scalar value)
Set old objective value.
virtual void reset ()
Reset step to initial value.
label maxIters () const
Get max number of iterations.
scalar step () const
Get current step.
virtual bool converged ()=0
Return the correction of the design variables.
virtual void updateStep ()=0
Update the line search step based on the specific line search strategy, e.g. bisection, quadratic fit, etc.
virtual void updateStep (const scalar newStep)
Update the step using the supplied value.
virtual lineSearch & operator++ ()
Increment iteration number and store merit value corresponding to the previous optimisation cycle.
virtual lineSearch & operator++ (int)
Postfix increment. Necessary for compilation.
Static Public Member Functions
static autoPtr< lineSearch > New (const dictionary &dict, const Time &time)
Return a reference to the selected turbulence model.
Protected Member Functions
const dictionary & coeffsDict ()
Optional coeffs dict.
Protected Attributes
const dictionary dict_
Subdict within updateMethod.
IOdictionary lineSearchDict_
IOdictionary under time/uniform for continuation.
scalar directionalDeriv_
Directional derivative of the merit function.
scalarField direction_
Update direction.
scalar oldMeritValue_
Old merit value from this opt cycle.
scalar newMeritValue_
New merit value from this opt cycle.
scalar prevMeritDeriv_
Merit directional deriv from the previous opt cycle.
scalar initialStep_
Correction multiplier at the first step of line search.
scalar minStep_
Minimum allowed correction multiplier.
scalar step_
Correction multiplier.
label iter_
Inner line search iteration.
label maxIters_
Maximum line search iterations.
bool extrapolateInitialStep_
Whether to extrapolate the correction multiplier for this optimisation cycle based on the previous ones.
autoPtr< stepUpdate > stepUpdate_
Mechanism to update method if line search conditions are not set.
Detailed Description
Abstract base class for line search methods.
Source files
lineSearch.H
lineSearch.C
Definition at line 52 of file lineSearch.H.
Constructor & Destructor Documentation
lineSearch (const dictionary & dict, const Time & time)
Construct from components.
Definition at line 45 of file lineSearch.C.
References lineSearch::dict_, dictionary::optionalSubDict(), and Foam::type().
virtual ~lineSearch () virtual default
Destructor.
Member Function Documentation
const Foam::dictionary & coeffsDict () protected
Optional coeffs dict.
Definition at line 37 of file lineSearch.C.
TypeName ("lineSearch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , lineSearch , dictionary , (const dictionary &dict, const Time &time) , (dict, time))
Foam::autoPtr< Foam::lineSearch > New (const dictionary & dict, const Time & time) static
Return a reference to the selected turbulence model.
Definition at line 89 of file lineSearch.C.
void setDeriv (const scalar deriv) virtual
Set objective derivative.
Definition at line 129 of file lineSearch.C.
void setDirection (const scalarField & direction)
Set direction.
Definition at line 136 of file lineSearch.C.
void setNewMeritValue (const scalar value)
Set new objective value.
Definition at line 142 of file lineSearch.C.
void setOldMeritValue (const scalar value)
Set old objective value.
Definition at line 149 of file lineSearch.C.
References value().
void reset () virtual
Reset step to initial value.
Definition at line 156 of file lineSearch.C.
References value().
Foam::label maxIters () const
Get max number of iterations.
Definition at line 176 of file lineSearch.C.
Foam::scalar step () const
Get current step.
Definition at line 182 of file lineSearch.C.
virtual bool converged () pure virtual
Return the correction of the design variables.
Implemented in ArmijoConditions.
virtual void updateStep () pure virtual
Update the line search step based on the specific line search strategy, e.g. bisection, quadratic fit, etc.
Implemented in ArmijoConditions.
void updateStep (const scalar newStep) virtual
Update the step using the supplied value.
Definition at line 188 of file lineSearch.C.
Foam::lineSearch & operator++ () virtual
Increment iteration number and store merit value corresponding to the previous optimisation cycle.
Definition at line 194 of file lineSearch.C.
Foam::lineSearch & operator++ (int) virtual
Postfix increment. Necessary for compilation.
Definition at line 212 of file lineSearch.C.
Member Data Documentation
const dictionary dict_ protected
Subdict within updateMethod.
Definition at line 61 of file lineSearch.H.
Referenced by lineSearch::lineSearch().
IOdictionary lineSearchDict_ protected
IOdictionary under time/uniform for continuation.
Definition at line 66 of file lineSearch.H.
scalar directionalDeriv_ protected
Directional derivative of the merit function.
Definition at line 71 of file lineSearch.H.
scalarField direction_ protected
Update direction.
Definition at line 76 of file lineSearch.H.
scalar oldMeritValue_ protected
Old merit value from this opt cycle.
Definition at line 81 of file lineSearch.H.
scalar newMeritValue_ protected
New merit value from this opt cycle.
Definition at line 86 of file lineSearch.H.
scalar prevMeritDeriv_ protected
Merit directional deriv from the previous opt cycle.
Definition at line 91 of file lineSearch.H.
scalar initialStep_ protected
Correction multiplier at the first step of line search.
Definition at line 96 of file lineSearch.H.
scalar minStep_ protected
Minimum allowed correction multiplier.
Definition at line 101 of file lineSearch.H.
scalar step_ protected
Correction multiplier.
Definition at line 106 of file lineSearch.H.
label iter_ protected
Inner line search iteration.
Definition at line 111 of file lineSearch.H.
label maxIters_ protected
Maximum line search iterations.
Definition at line 116 of file lineSearch.H.
bool extrapolateInitialStep_ protected
Whether to extrapolate the correction multiplier for this optimisation cycle based on the previous ones.
Usefull for non-quasi Newton methods
Definition at line 124 of file lineSearch.H.
autoPtr<stepUpdate> stepUpdate_ protected
Mechanism to update method if line search conditions are not set.
Definition at line 129 of file lineSearch.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/lineSearch/lineSearch/lineSearch.H
src/optimisation/adjointOptimisation/adjoint/optimisation/lineSearch/lineSearch/lineSearch.C