OpenFOAM: OSstream Class Reference
OSstream Class Reference
Generic output stream.
Public Member Functions
OSstream (std::ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct as wrapper around std::ostream and set stream status.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual bool write (const token &tok)
Write token to stream or otherwise handle it.
virtual Ostream & write (const char c)
Write character.
virtual Ostream & write (const char *str)
Write character string.
virtual Ostream & write (const word &str)
Write word.
virtual Ostream & write (const string &str)
Write string (quoted)
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t val)
Write int32_t.
virtual Ostream & write (const int64_t val)
Write int64_t.
virtual Ostream & write (const floatScalar val)
Write floatScalar.
virtual Ostream & write (const doubleScalar val)
Write doubleScalar.
virtual Ostream & write (const char *data, std::streamsize count)
Write binary block.
virtual Ostream & writeRaw (const char *data, std::streamsize count)
Low-level raw binary output.
virtual bool beginRawWrite (std::streamsize count)
Begin marker for low-level raw binary output.
virtual bool endRawWrite ()
End marker for low-level raw binary output.
virtual void indent ()
Add indentation characters.
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)
Set stream flags.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual char fill () const
Get the current padding character.
virtual char fill (const char fillch)
Set padding character for formatted field up to field width.
virtual int width () const
Get width of output field.
virtual int width (const int w)
Set width of output field.
virtual int precision () const
Get precision of output field.
virtual int precision (const int p)
Set precision of output field.
virtual std::ostream & stdStream ()
Access to underlying std::ostream.
virtual const std::ostream & stdStream () const
Const access to underlying std::ostream.
virtual void print (Ostream &os) const
Print description of IOstream to Ostream.
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct and set stream status.
virtual ~Ostream ()=default
Destructor.
virtual Ostream & write (const keyType &kw)
Write keyType.
unsigned short indentSize () const
Return indent level.
unsigned short & indentSize ()
Access to indent size.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Increment the indent level.
void decrIndent ()
Decrement the indent level.
virtual Ostream & writeKeyword (const keyType &kw)
Write the keyword followed by an appropriate indentation.
virtual Ostream & beginBlock (const keyType &kw)
Write begin block group with the given name.
virtual Ostream & beginBlock ()
Write begin block group without a name.
virtual Ostream & endBlock ()
Write end block group.
virtual Ostream & endEntry ()
Write end entry (';') followed by newline.
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
Write a keyword/value entry.
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Write a keyword/value entry only when the two values differ.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (const IOstreamOption option)
Construct with specified stream option.
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct with format, version.
virtual ~IOstream ()=default
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
unsigned labelByteSize () const
The label byte-size associated with the stream.
unsigned scalarByteSize () const
The scalar byte-size associated with the stream.
void setLabelByteSize (unsigned nbytes)
Set the label byte-size associated with the stream.
void setScalarByteSize (unsigned nbytes)
Set the scalar byte-size associated with the stream.
template<class T = label>
std::enable_if
< std::is_integral< T >::value,
bool >::type checkLabelSize () const
Check if the label byte-size associated with the stream is the same as the given type.
template<class T = scalar>
std::enable_if
< std::is_floating_point< T >
::value, bool >::type checkScalarSize () const
Check if the scalar byte-size associated with the stream is the same as the given type.
label lineNumber () const
Const access to the current stream line number.
label & lineNumber ()
Non-const access to the current stream line number.
label lineNumber (const label num)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
void print (Ostream &os, const int streamState) const
Print information about the stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from IOstreamOption
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
Enumeration for stream open/closed state.
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision.
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Static Public Attributes inherited from IOstream
static unsigned int precision_
Default precision.
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
Number of spaces per indent level.
unsigned short indentLevel_ = 0
Current indent level.
Protected Attributes inherited from IOstream
streamAccess openClosed_
ios_base::iostate ioState_
unsigned short labelByteSize_
The label byte-size (could also be stored as byte)
unsigned short scalarByteSize_
The scalar byte-size (could also be stored as byte)
label lineNumber_
The file line.
Static Protected Attributes inherited from Ostream
static constexpr const
unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Static Protected Attributes inherited from IOstream
static fileName staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
Generic output stream.
Source files
OSstream.H
OSstreamI.H
OSstream.C
Definition at line 50 of file OSstream.H.
Constructor & Destructor Documentation
OSstream (std::ostream & os, const string & name, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED) inline
Construct as wrapper around std::ostream and set stream status.
Definition at line 26 of file OSstreamI.H.
References IOstream::precision_, IOstream::setGood(), IOstream::setOpened(), and IOstream::setState().
Member Function Documentation
virtual const fileName& name () const inline virtual
Return the name of the stream.
Useful for Fstream to return the filename
Reimplemented from IOstream.
Definition at line 94 of file OSstream.H.
Referenced by mappedPatchBase::calcMapping(), meshObject::clearUpto(), distributedTriSurfaceMesh::distribute(), MeshObject< Mesh, MeshObjectType, Type >::New(), oldCyclicPolyPatch::order(), fvMeshDistribute::printFieldInfo(), regionSplit::reduceRegions(), and surfaceFeatures::writeObj().
virtual fileName& name () inline virtual
Return non-const access to the name of the stream.
Useful to alter the stream name
Reimplemented from IOstream.
Definition at line 104 of file OSstream.H.
std::ios_base::fmtflags flags () const virtual
Return flags of output stream.
Implements IOstream.
Definition at line 266 of file OSstream.C.
References Foam::vtk::write().
bool write (const token & tok) virtual
Write token to stream or otherwise handle it.
Returns
false if the token type was not handled by this method
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 29 of file OSstream.C.
References token::BEGIN_BLOCK, token::END_BLOCK, token::HASH, token::stringToken(), token::type(), and OSstream::writeQuoted().
Referenced by prefixOSstream::indent(), prefixOSstream::write(), OBJstream::write(), and prefixOSstream::writeQuoted().
Foam::Ostream & write (const char c) virtual
Write character.
Implements Ostream.
Reimplemented in OBJstream, and prefixOSstream.
Definition at line 67 of file OSstream.C.
Foam::Ostream & write (const char * str) virtual
Write character string.
Implements Ostream.
Reimplemented in ensightFile, OBJstream, and prefixOSstream.
Definition at line 79 of file OSstream.C.
Foam::Ostream & write (const word & str) virtual
Write word.
Implements Ostream.
Reimplemented in OBJstream, and prefixOSstream.
Definition at line 88 of file OSstream.C.
Foam::Ostream & write (const string & str) virtual
Write string (quoted)
In the rare case that the string contains a final trailing backslash, it will be dropped to the appearance of an escaped double-quote.
Implements Ostream.
Reimplemented in OSHA1stream, ensightFile, OBJstream, and prefixOSstream.
Definition at line 155 of file OSstream.C.
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implements Ostream.
Reimplemented in OBJstream, and prefixOSstream.
Definition at line 97 of file OSstream.C.
Referenced by OSstream::write(), and prefixOSstream::write().
Foam::Ostream & write (const int32_t val) virtual
Write int32_t.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 161 of file OSstream.C.
Foam::Ostream & write (const int64_t val) virtual
Write int64_t.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 169 of file OSstream.C.
References Foam::val.
Foam::Ostream & write (const floatScalar val) virtual
Write floatScalar.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 177 of file OSstream.C.
References Foam::val.
Foam::Ostream & write (const doubleScalar val) virtual
Write doubleScalar.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 185 of file OSstream.C.
References Foam::val.
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Write binary block.
Implements Ostream.
Reimplemented in ensightFile, and prefixOSstream.
Definition at line 193 of file OSstream.C.
References Foam::val.
Foam::Ostream & writeRaw (const char * data, std::streamsize count) virtual
Low-level raw binary output.
Implements Ostream.
Definition at line 229 of file OSstream.C.
bool beginRawWrite (std::streamsize count) virtual
Begin marker for low-level raw binary output.
The count indicates the number of bytes for subsequent writeRaw calls.
Implements Ostream.
Definition at line 203 of file OSstream.C.
bool endRawWrite () virtual
End marker for low-level raw binary output.
Implements Ostream.
Definition at line 219 of file OSstream.C.
void indent () virtual
Add indentation characters.
Implements Ostream.
Reimplemented in prefixOSstream.
Definition at line 244 of file OSstream.C.
std::ios_base::fmtflags flags (const ios_base::fmtflags f) virtual
Set stream flags.
Implements IOstream.
Definition at line 272 of file OSstream.C.
void flush () virtual
Flush stream.
Implements Ostream.
Definition at line 253 of file OSstream.C.
void endl () virtual
Add newline and flush stream.
Implements Ostream.
Definition at line 259 of file OSstream.C.
char fill () const virtual
Get the current padding character.
Implements Ostream.
Definition at line 280 of file OSstream.C.
char fill (const char fillch) virtual
Set padding character for formatted field up to field width.
Returns
previous padding character
Implements Ostream.
Definition at line 286 of file OSstream.C.
int width () const virtual
Get width of output field.
Implements Ostream.
Definition at line 292 of file OSstream.C.
int width (const int w) virtual
Set width of output field.
Returns
previous width
Implements Ostream.
Definition at line 298 of file OSstream.C.
int precision () const virtual
Get precision of output field.
Implements Ostream.
Definition at line 304 of file OSstream.C.
Referenced by FLMAsurfaceFormat< Face >::write().
int precision (const int p) virtual
Set precision of output field.
Returns
old precision
Implements Ostream.
Definition at line 310 of file OSstream.C.
virtual std::ostream& stdStream () inline virtual
Access to underlying std::ostream.
Reimplemented in OFstream.
Definition at line 271 of file OSstream.H.
virtual const std::ostream& stdStream () const inline virtual
Const access to underlying std::ostream.
Reimplemented in OFstream.
Definition at line 279 of file OSstream.H.
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Reimplemented in OListStream, UOListStream, OCountStream, OStringStream, prefixOSstream, and OFstream.
Definition at line 39 of file SstreamsPrint.C.
Referenced by prefixOSstream::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Sstreams/OSstream.H
src/OpenFOAM/db/IOstreams/Sstreams/OSstream.C
src/OpenFOAM/db/IOstreams/Sstreams/OSstreamI.H
src/OpenFOAM/db/IOstreams/Sstreams/SstreamsPrint.C