OpenFOAM: KinematicParcel< ParcelType >::trackingData Class Reference
KinematicParcel< ParcelType >::trackingData Class Reference
Public Types
enum trackPart { tpVelocityHalfStep, tpLinearTrack, tpRotationalTrack }
Public Member Functions
template<class TrackCloudType >
trackingData (const TrackCloudType &cloud, trackPart part=tpLinearTrack)
Construct from components.
const interpolation< scalar > & rhoInterp () const
Return const access to the interpolator for continuous phase density field.
const interpolation< vector > & UInterp () const
Return const access to the interpolator for continuous phase velocity field.
const interpolation< scalar > & muInterp () const
Return const access to the interpolator for continuous phase dynamic viscosity field.
scalar rhoc () const
Return the continuous phase density.
scalar & rhoc ()
Access the continuous phase density.
const vector & Uc () const
Return the continuous phase velocity.
vector & Uc ()
Access the continuous phase velocity.
scalar muc () const
Return the continuous phase viscosity.
scalar & muc ()
Access the continuous phase viscosity.
const vector & g () const
trackPart part () const
Return the part of the tracking operation taking place.
trackPart & part ()
Return access to the part of the tracking operation taking place.
Detailed Description
template<class ParcelType>
class Foam::KinematicParcel< ParcelType >::trackingData
Definition at line 187 of file KinematicParcel.H.
Member Enumeration Documentation
enum trackPart
Enumerator
tpVelocityHalfStep
tpLinearTrack
tpRotationalTrack
Definition at line 193 of file KinematicParcel.H.
Constructor & Destructor Documentation
trackingData (const TrackCloudType & cloud, trackPart part = tpLinearTrack) inline
Construct from components.
Definition at line 24 of file KinematicParcelTrackingDataI.H.
Member Function Documentation
const Foam::interpolation< Foam::scalar > & rhoInterp () const inline
Return const access to the interpolator for continuous phase density field.
Definition at line 64 of file KinematicParcelTrackingDataI.H.
Referenced by KinematicParcel< ParcelType >::setCellValues().
const Foam::interpolation< Foam::vector > & UInterp () const inline
Return const access to the interpolator for continuous phase velocity field.
Definition at line 72 of file KinematicParcelTrackingDataI.H.
Referenced by KinematicParcel< ParcelType >::setCellValues().
const Foam::interpolation< Foam::scalar > & muInterp () const inline
Return const access to the interpolator for continuous phase dynamic viscosity field.
Definition at line 80 of file KinematicParcelTrackingDataI.H.
Foam::scalar rhoc () const inline
Return the continuous phase density.
Definition at line 96 of file KinematicParcelTrackingDataI.H.
Referenced by KinematicParcel< ParcelType >::setCellValues().
Foam::scalar & rhoc () inline
Access the continuous phase density.
Definition at line 103 of file KinematicParcelTrackingDataI.H.
const Foam::vector & Uc () const inline
Return the continuous phase velocity.
Definition at line 111 of file KinematicParcelTrackingDataI.H.
Referenced by KinematicParcel< ParcelType >::setCellValues().
Foam::vector & Uc () inline
Access the continuous phase velocity.
Definition at line 118 of file KinematicParcelTrackingDataI.H.
Foam::scalar muc () const inline
Return the continuous phase viscosity.
Definition at line 125 of file KinematicParcelTrackingDataI.H.
Foam::scalar & muc () inline
Access the continuous phase viscosity.
Definition at line 132 of file KinematicParcelTrackingDataI.H.
const Foam::vector & g () const inline
Definition at line 88 of file KinematicParcelTrackingDataI.H.
Foam::KinematicParcel< ParcelType >::trackingData::trackPart part () const inline
Return the part of the tracking operation taking place.
Definition at line 140 of file KinematicParcelTrackingDataI.H.
Foam::KinematicParcel< ParcelType >::trackingData::trackPart & part () inline
Return access to the part of the tracking operation taking place.
Definition at line 148 of file KinematicParcelTrackingDataI.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelTrackingDataI.H