OpenFOAM: LehrMilliesMewesCoalescence Class Reference
LehrMilliesMewesCoalescence Class Reference
Model of Lehr et al. (2002). The coalescence rate is calculated by.
Public Member Functions
TypeName ("LehrMilliesMewes")
Runtime type information.
LehrMilliesMewesCoalescence (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~LehrMilliesMewesCoalescence ()=default
Destructor.
virtual void addToCoalescenceRate (volScalarField &coalescenceRate, const label i, const label j)
Add to coalescenceRate.
Public Member Functions inherited from coalescenceModel
TypeName ("coalescenceModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coalescenceModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
coalescenceModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< coalescenceModel > clone () const
virtual ~coalescenceModel ()=default
Destructor.
virtual void correct ()
Correct diameter independent expressions.
Additional Inherited Members
Static Public Member Functions inherited from coalescenceModel
static autoPtr< coalescenceModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from coalescenceModel
const populationBalanceModel & popBal_
Reference to the populationBalanceModel.
Detailed Description
Model of Lehr et al. (2002). The coalescence rate is calculated by.
where
is the characteristic velocity for coalescence. Note that a velocity difference between bubble i and j is only present if the corresponding size groups are assigned to different velocity groups.
= Diameter of bubble i [m]
= Diameter of bubble j [m]
= Turbulent dissipation rate of continuous phase [m2/s3]
= Total void fraction of the bubbles [-]
= Maximum packing density of the bubbles [-]
= Critical velocity for coalescence [m/s]
= Velocity vector of bubble i [m/s]
= Velocity vector of bubble j [m/s]
Reference:
        Lehr, F., Millies, M., & Mewes, D. (2002).
        Bubble‐size distributions and flow fields in bubble columns.
        AIChE Journal, 48(11), 2426-2443.
Usage
Property Description Required Default value
uCrit Crit. coalescence velocity no 0.08
alphaMax Maximum packing density no 0.6
Source files
LehrMilliesMewesCoalescence.H
LehrMilliesMewesCoalescence.C
Definition at line 146 of file LehrMilliesMewesCoalescence.H.
Constructor & Destructor Documentation
LehrMilliesMewesCoalescence (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 51 of file LehrMilliesMewesCoalescence.C.
virtual ~LehrMilliesMewesCoalescence () virtual default
Destructor.
Member Function Documentation
TypeName ("LehrMilliesMewes")
Runtime type information.
void addToCoalescenceRate (volScalarField & coalescenceRate, const label i, const label j) virtual
Add to coalescenceRate.
Implements coalescenceModel.
Definition at line 73 of file LehrMilliesMewesCoalescence.C.
References Foam::cbrt(), sizeGroup::d(), Foam::exp(), i, j, Foam::mag(), Foam::max(), Foam::min(), sizeGroup::phase(), Foam::constant::mathematical::pi(), phaseModel::residualAlpha(), Foam::sqr(), Foam::sqrt(), and phaseModel::U().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/populationBalanceModel/coalescenceModels/LehrMilliesMewesCoalescence/LehrMilliesMewesCoalescence.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/populationBalanceModel/coalescenceModels/LehrMilliesMewesCoalescence/LehrMilliesMewesCoalescence.C