OpenFOAM: polyTopoChange Class Reference
polyTopoChange Class Reference
Direct mesh changes based on v1.3 polyTopoChange syntax.
Public Member Functions
ClassName ("polyTopoChange")
Runtime type information.
polyTopoChange (const label nPatches, const bool strict=true)
Construct without mesh. Either specify nPatches or use.
polyTopoChange (const polyMesh &mesh, const bool strict=true)
Construct from mesh. Adds all points/face/cells from mesh.
const DynamicList< point > & points () const
Points. Shrunk after constructing mesh (or calling of compact())
const DynamicList< face > & faces () const
const DynamicList< label > & region () const
const DynamicList< label > & faceOwner () const
const DynamicList< label > & faceNeighbour () const
bool pointRemoved (const label pointi) const
Is point removed?
bool faceRemoved (const label facei) const
Is face removed?
bool cellRemoved (const label celli) const
Is cell removed?
void clear ()
Clear all storage.
void addMesh (const polyMesh &mesh, const labelUList &patchMap, const labelUList &pointZoneMap, const labelUList &faceZoneMap, const labelUList &cellZoneMap)
Add all points/faces/cells of mesh. Additional offset for patch.
void setCapacity (const label nPoints, const label nFaces, const label nCells)
Explicitly pre-size the dynamic storage for expected mesh.
void movePoints (const pointField &newPoints)
Move all points. Incompatible with other topology changes.
label setAction (const topoAction &action)
For compatibility with polyTopoChange: set topological action.
label addPoint (const point &pt, const label masterPointID, const label zoneID, const bool inCell)
Add point. Return new point label.
void modifyPoint (const label pointi, const point &pt, const label zoneID, const bool inCell)
Modify coordinate.
void removePoint (const label pointi, const label mergePointi)
Remove/merge point.
label addFace (const face &f, const label own, const label nei, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Add face to cells. Return new face label.
void modifyFace (const face &f, const label facei, const label own, const label nei, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Modify vertices or cell of face.
void removeFace (const label facei, const label mergeFacei)
Remove/merge face.
label addCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
Add cell. Return new cell label.
void modifyCell (const label celli, const label zoneID)
Modify zone of cell.
void removeCell (const label celli, const label mergeCelli)
Remove/merge cell.
void setNumPatches (const label nPatches)
Explicitly set the number of patches if construct-without-mesh.
autoPtr< mapPolyMesh > changeMesh (polyMesh &mesh, const bool inflate, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
Inplace changes mesh without change of patches.
autoPtr< mapPolyMesh > makeMesh (autoPtr< fvMesh > &newMesh, const IOobject &io, const polyMesh &mesh, const bool syncParallel=true, const bool orderCells=false, const bool orderPoints=false)
Create new mesh with old mesh patches.
Detailed Description
Direct mesh changes based on v1.3 polyTopoChange syntax.
Instead of recording changes and executing them all in one go (as did v1.3 polyTopoChange) this class actually holds the current points/faces/cells and does the change immediately. It can be asked to compress out all unused points/faces/cells and renumber everything to be consistent.
Note:
polyTopoChange can be copied.
adding a face using non-existing cells causes all intermediate cells to be added. So always first add cells/points and then faces. (or set strict checking)
strict checking:
any added/modified face can only use already existing vertices
any added face can only use already existing cells
no item can be removed more than once.
removed cell: cell set to 0 faces.
removed face: face set to 0 vertices.
removed point: coordinate set to vector::max (VGREAT,VGREAT,VGREAT). Note that this might give problems if this value is used already. To see if point is equal to above value we don't use == (which might give problems with roundoff error) but instead compare the individual component with >.
coupled patches: the reorderCoupledFaces routine (borrowed from the couplePatches utility) reorders coupled patch faces and uses the cyclicPolyPatch,processorPolyPatch functionality.
Source files
polyTopoChange.H
polyTopoChange.C
polyTopoChangeI.H
polyTopoChangeTemplates.C
Definition at line 96 of file polyTopoChange.H.
Constructor & Destructor Documentation
polyTopoChange (const label nPatches, const bool strict = true)
Construct without mesh. Either specify nPatches or use.
setNumPatches before trying to make a mesh (makeMesh, changeMesh)
Definition at line 2107 of file polyTopoChange.C.
polyTopoChange (const polyMesh & mesh, const bool strict = true)
Construct from mesh. Adds all points/face/cells from mesh.
Definition at line 2139 of file polyTopoChange.C.
Member Function Documentation
ClassName ("polyTopoChange")
Runtime type information.
const DynamicList<point>& points () const inline
Points. Shrunk after constructing mesh (or calling of compact())
Definition at line 551 of file polyTopoChange.H.
const DynamicList<face>& faces () const inline
Definition at line 556 of file polyTopoChange.H.
const DynamicList<label>& region () const inline
Definition at line 561 of file polyTopoChange.H.
const DynamicList<label>& faceOwner () const inline
Definition at line 566 of file polyTopoChange.H.
const DynamicList<label>& faceNeighbour () const inline
Definition at line 571 of file polyTopoChange.H.
bool pointRemoved (const label pointi) const inline
Is point removed?
Considered removed if point is GREAT.
Definition at line 25 of file polyTopoChangeI.H.
bool faceRemoved (const label facei) const inline
Is face removed?
Considered removed if face is empty
Definition at line 36 of file polyTopoChangeI.H.
bool cellRemoved (const label celli) const inline
Is cell removed?
Considered removed if the cellMap is -2
Definition at line 42 of file polyTopoChangeI.H.
void clear ()
Clear all storage.
Definition at line 2183 of file polyTopoChange.C.
void addMesh (const polyMesh & mesh, const labelUList & patchMap, const labelUList & pointZoneMap, const labelUList & faceZoneMap, const labelUList & cellZoneMap)
Add all points/faces/cells of mesh. Additional offset for patch.
or zone ids.
Definition at line 2214 of file polyTopoChange.C.
void setCapacity (const label nPoints, const label nFaces, const label nCells)
Explicitly pre-size the dynamic storage for expected mesh.
size for if construct-without-mesh
Definition at line 2419 of file polyTopoChange.C.
void movePoints (const pointField & newPoints)
Move all points. Incompatible with other topology changes.
Definition at line 2650 of file polyTopoChange.C.
Foam::label setAction (const topoAction & action)
For compatibility with polyTopoChange: set topological action.
Definition at line 2451 of file polyTopoChange.C.
Referenced by combineFaces::setUnrefinement().
Foam::label addPoint (const point & pt, const label masterPointID, const label zoneID, const bool inCell)
Add point. Return new point label.
Notes:
masterPointID can be < 0 (appended points)
inCell = false: add retired point (to end of point list)
Definition at line 2580 of file polyTopoChange.C.
void modifyPoint (const label pointi, const point & pt, const label zoneID, const bool inCell)
Modify coordinate.
Notes:
zoneID = +ve (add to zoneID), -ve (remove from zones)
inCell = false: add retired point (to end of point list)
Definition at line 2608 of file polyTopoChange.C.
void removePoint (const label pointi, const label mergePointi)
Remove/merge point.
Definition at line 2669 of file polyTopoChange.C.
Foam::label addFace (const face & f, const label own, const label nei, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Add face to cells. Return new face label.
own,nei<0, zoneID>=0 : add inactive face (to end of face list)
Definition at line 2717 of file polyTopoChange.C.
void modifyFace (const face & f, const label facei, const label own, const label nei, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Modify vertices or cell of face.
Definition at line 2781 of file polyTopoChange.C.
void removeFace (const label facei, const label mergeFacei)
Remove/merge face.
Definition at line 2818 of file polyTopoChange.C.
Foam::label addCell (const label masterPointID, const label masterEdgeID, const label masterFaceID, const label masterCellID, const label zoneID)
Add cell. Return new cell label.
Definition at line 2865 of file polyTopoChange.C.
void modifyCell (const label celli, const label zoneID)
Modify zone of cell.
Definition at line 2902 of file polyTopoChange.C.
void removeCell (const label celli, const label mergeCelli)
Remove/merge cell.
Definition at line 2912 of file polyTopoChange.C.
References zoneID.
void setNumPatches (const label nPatches) inline
Explicitly set the number of patches if construct-without-mesh.
used.
Definition at line 48 of file polyTopoChangeI.H.
Foam::autoPtr< Foam::mapPolyMesh > changeMesh (polyMesh & mesh, const bool inflate, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Inplace changes mesh without change of patches.
Adapts patch start/end and by default does parallel matching. Clears all data. Returns map. inflate = true : keep old mesh points. Put new points into the returned map (preMotionPoints) so we can use inflation. Any points out of nothing (appended points) are vector::zero. inflate = false: set mesh points directly. Empty preMotionPoints in the map. orderCells : whether to order the cells (see bandCompression.H) orderPoints : whether to order the points into internal first followed by boundary points. This is not fully consistent with upper-triangular ordering of points and edges so is only done when explicitly asked for.
Definition at line 2950 of file polyTopoChange.C.
Referenced by meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), and meshRefinement::zonify().
Foam::autoPtr< Foam::mapPolyMesh > makeMesh (autoPtr< fvMesh > & newMesh, const IOobject & io, const polyMesh & mesh, const bool syncParallel = true, const bool orderCells = false, const bool orderPoints = false)
Create new mesh with old mesh patches.
Definition at line 3213 of file polyTopoChange.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChange.H
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChange.C
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChangeI.H
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChangeTemplates.C