OpenFOAM: regExpCxx Class Reference
regExpCxx Class Reference
Wrapper around C++11 regular expressions.
Public Types
typedef std::smatch results_type
Type for matches.
Public Member Functions
regExpCxx ()
Construct null.
regExpCxx (const regExpCxx &rgx)
Copy construct.
regExpCxx (regExpCxx &&rgx)
Move construct.
regExpCxx (const char *pattern)
Construct from character array.
regExpCxx (const std::string &pattern)
Construct from string.
regExpCxx (const char *pattern, bool ignoreCase)
Construct from character array, optionally ignore case.
regExpCxx (const std::string &pattern, bool ignoreCase)
Construct from string, optionally ignore case.
~regExpCxx ()=default
Destructor.
bool empty () const noexcept
Return true if expression is empty.
bool exists () const noexcept
Return true if expression is non-empty.
unsigned ngroups () const
The number of capture groups for a non-empty expression.
bool nocase () const
bool clear ()
Clear expression.
void swap (regExpCxx &rgx)
Swap contents.
bool set (const char *pattern, bool ignoreCase=false)
Compile pattern into a regular expression, optionally ignore case.
bool set (const std::string &pattern, bool ignoreCase=false)
Compile pattern into a regular expression, optionally ignore case.
std::string::size_type find (const std::string &text) const
Find position within the text.
bool match (const std::string &text) const
True if the regex matches the entire text.
bool match (const std::string &text, results_type &matches) const
True if the regex matches the text, set the matches.
bool search (const std::string &text) const
Return true if the regex was found within the text.
bool operator() (const std::string &text) const
Perform match on text.
void operator= (const regExpCxx &rgx)
Copy assignment.
void operator= (regExpCxx &&rgx)
Move assignment.
void operator= (const char *pattern)
Assign and compile pattern from a character array.
void operator= (const std::string &pattern)
Assign and compile pattern from string.
Static Public Member Functions
static bool meta (const char c)
Test if character appears to be a regular expression meta-character.
Static Public Attributes
static int grammar
The default grammar (extended | ECMAScript).
Detailed Description
Wrapper around C++11 regular expressions.
Using either POSIX extended regular expressions or modified ECMAScript regular expression grammar
Since ECMAScript grammar may not work correctly on all installations, the current default is to use extended regular expressions.
The JAVA/PCRE '(?i)' extension is supported as a prefix to compile the regular expression as being case-insensitive.
Note
The C++11 regular expressions may be broken on some compilers. For example, gcc 4.8 is known to fail. For these systems the POSIX implementation or alternative must be used.
Warning
This class should not be used directly. Use the Foam::regExp typedef instead.
Source files
regExpCxx.H
regExpCxxI.H
regExpCxx.C
Definition at line 68 of file regExpCxx.H.
Member Typedef Documentation
typedef std::smatch results_type
Type for matches.
Definition at line 98 of file regExpCxx.H.
Constructor & Destructor Documentation
regExpCxx () inline
Construct null.
Definition at line 49 of file regExpCxxI.H.
regExpCxx (const regExpCxx & rgx) inline
Copy construct.
Definition at line 56 of file regExpCxxI.H.
regExpCxx (regExpCxx && rgx) inline
Move construct.
Definition at line 63 of file regExpCxxI.H.
regExpCxx (const char * pattern) inline explicit
Construct from character array.
Definition at line 72 of file regExpCxxI.H.
regExpCxx (const std::string & pattern) inline explicit
Construct from string.
Definition at line 81 of file regExpCxxI.H.
References set().
regExpCxx (const char * pattern, bool ignoreCase) inline
Construct from character array, optionally ignore case.
Definition at line 90 of file regExpCxxI.H.
References set().
regExpCxx (const std::string & pattern, bool ignoreCase) inline
Construct from string, optionally ignore case.
Definition at line 99 of file regExpCxxI.H.
References set().
~regExpCxx () default
Destructor.
Member Function Documentation
bool meta (const char c) inline static
Test if character appears to be a regular expression meta-character.
Returns
true if character is one of the following:
any character: '.'
quantifiers: '*', '+', '?'
grouping: '(', '|', ')'
range: '[', ']'
Note
The presence of '{', '}' regex bounds is not considered
Definition at line 35 of file regExpCxxI.H.
bool empty () const inline noexcept
Return true if expression is empty.
Definition at line 110 of file regExpCxxI.H.
References set().
bool exists () const inline noexcept
Return true if expression is non-empty.
Definition at line 116 of file regExpCxxI.H.
unsigned ngroups () const inline
The number of capture groups for a non-empty expression.
Definition at line 122 of file regExpCxxI.H.
bool nocase () const inline
Definition at line 128 of file regExpCxxI.H.
bool clear () inline
Clear expression.
Returns
True if expression had existed prior to the clear.
Definition at line 134 of file regExpCxxI.H.
void swap (regExpCxx & rgx) inline
Swap contents.
Definition at line 148 of file regExpCxxI.H.
bool set (const char * pattern, bool ignoreCase = false)
Compile pattern into a regular expression, optionally ignore case.
Returns
True if the pattern was compiled
Definition at line 104 of file regExpCxx.C.
bool set (const std::string & pattern, bool ignoreCase = false)
Compile pattern into a regular expression, optionally ignore case.
Returns
True if the pattern was compiled
Definition at line 153 of file regExpCxx.C.
std::string::size_type find (const std::string & text) const inline
Find position within the text.
Returns
The index where it begins or string::npos if not found
Definition at line 160 of file regExpCxxI.H.
bool match (const std::string & text) const inline
True if the regex matches the entire text.
The begin-of-line (^) and end-of-line ($) anchors are implicit
Definition at line 178 of file regExpCxxI.H.
bool match (const std::string & text, results_type & matches) const inline
True if the regex matches the text, set the matches.
The first group starts at index 1 (0 is the entire match). The begin-of-line (^) and end-of-line ($) anchors are implicit
Definition at line 185 of file regExpCxxI.H.
bool search (const std::string & text) const inline
Return true if the regex was found within the text.
Definition at line 172 of file regExpCxxI.H.
bool operator() (const std::string & text) const inline
Perform match on text.
Definition at line 196 of file regExpCxxI.H.
void operator= (const regExpCxx & rgx) inline
Copy assignment.
Definition at line 202 of file regExpCxxI.H.
References Foam::stringOps::match().
void operator= (regExpCxx && rgx) inline
Move assignment.
Definition at line 209 of file regExpCxxI.H.
void operator= (const char * pattern) inline
Assign and compile pattern from a character array.
Matching is case sensitive.
Definition at line 216 of file regExpCxxI.H.
References clear().
void operator= (const std::string & pattern) inline
Assign and compile pattern from string.
Matching is case sensitive.
Definition at line 222 of file regExpCxxI.H.
References set().
Member Data Documentation
int grammar static
The default grammar (extended | ECMAScript).
Definition at line 106 of file regExpCxx.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/regex/regExpCxx.H
src/OpenFOAM/primitives/strings/regex/regExpCxx.C
src/OpenFOAM/primitives/strings/regex/regExpCxxI.H