OpenFOAM: OBJstream Class Reference
OBJstream Class Reference
OFstream that keeps track of vertices.
Public Member Functions
ClassName ("OBJstream")
OBJstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct from pathname.
~OBJstream ()=default
Destructor.
label nVertices () const
Return the number of vertices written.
virtual Ostream & write (const char c)
Write character.
virtual Ostream & write (const char *str)
Write character string.
virtual Ostream & write (const word &str)
Write word.
virtual Ostream & write (const string &str)
Write string.
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
Write std::string surrounded by quotes.
Ostream & write (const point &pt)
Write point.
Ostream & write (const point &pt, const vector &n)
Write point and vector normal ('vn')
Ostream & write (const edge &e, const UList< point > &points)
Write edge as points and line.
Ostream & write (const linePointRef &ln)
Write line.
Ostream & write (const linePointRef &ln, const vector &n0, const vector &n1)
Write line with points and vector normals ('vn')
Ostream & write (const triPointRef &f, const bool lines=true)
Write triangle as points and lines/filled-polygon.
Ostream & write (const face &f, const UList< point > &points, const bool lines=true)
Write face as points and lines/filled-polygon.
Ostream & write (const UList< face > &faces, const pointField &points, const bool lines=true)
Write patch faces as points and lines/filled-polygon.
Ostream & write (const UList< edge > &edges, const UList< point > &points, const bool compact=false)
Write edges as points and lines.
Ostream & write (const treeBoundBox &bb, const bool lines=true)
Write tree-bounding box as lines/filled-polygons.
Public Member Functions inherited from OFstream
ClassName ("OFstream")
OFstream (const fileName &pathname, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED, const bool append=false)
Construct from pathname.
~OFstream ()=default
Destructor.
virtual std::ostream & stdStream ()
Access to underlying std::ostream.
virtual const std::ostream & stdStream () const
Const access to underlying std::ostream.
void print (Ostream &os) const
Print description of IOstream to Ostream.
Public Member Functions inherited from OSstream
OSstream (std::ostream &os, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct as wrapper around std::ostream and set stream status.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual bool write (const token &tok)
Write token to stream or otherwise handle it.
virtual Ostream & write (const int32_t val)
Write int32_t.
virtual Ostream & write (const int64_t val)
Write int64_t.
virtual Ostream & write (const floatScalar val)
Write floatScalar.
virtual Ostream & write (const doubleScalar val)
Write doubleScalar.
virtual Ostream & write (const char *data, std::streamsize count)
Write binary block.
virtual Ostream & writeRaw (const char *data, std::streamsize count)
Low-level raw binary output.
virtual bool beginRawWrite (std::streamsize count)
Begin marker for low-level raw binary output.
virtual bool endRawWrite ()
End marker for low-level raw binary output.
virtual void indent ()
Add indentation characters.
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)
Set stream flags.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual char fill () const
Get the current padding character.
virtual char fill (const char fillch)
Set padding character for formatted field up to field width.
virtual int width () const
Get width of output field.
virtual int width (const int w)
Set width of output field.
virtual int precision () const
Get precision of output field.
virtual int precision (const int p)
Set precision of output field.
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct and set stream status.
virtual ~Ostream ()=default
Destructor.
virtual Ostream & write (const keyType &kw)
Write keyType.
unsigned short indentSize () const
Return indent level.
unsigned short & indentSize ()
Access to indent size.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Increment the indent level.
void decrIndent ()
Decrement the indent level.
virtual Ostream & writeKeyword (const keyType &kw)
Write the keyword followed by an appropriate indentation.
virtual Ostream & beginBlock (const keyType &kw)
Write begin block group with the given name.
virtual Ostream & beginBlock ()
Write begin block group without a name.
virtual Ostream & endBlock ()
Write end block group.
virtual Ostream & endEntry ()
Write end entry (';') followed by newline.
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
Write a keyword/value entry.
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Write a keyword/value entry only when the two values differ.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (const IOstreamOption option)
Construct with specified stream option.
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct with format, version.
virtual ~IOstream ()=default
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
unsigned labelByteSize () const
The label byte-size associated with the stream.
unsigned scalarByteSize () const
The scalar byte-size associated with the stream.
void setLabelByteSize (unsigned nbytes)
Set the label byte-size associated with the stream.
void setScalarByteSize (unsigned nbytes)
Set the scalar byte-size associated with the stream.
template<class T = label>
std::enable_if
< std::is_integral< T >::value,
bool >::type checkLabelSize () const
Check if the label byte-size associated with the stream is the same as the given type.
template<class T = scalar>
std::enable_if
< std::is_floating_point< T >
::value, bool >::type checkScalarSize () const
Check if the scalar byte-size associated with the stream is the same as the given type.
label lineNumber () const
Const access to the current stream line number.
label & lineNumber ()
Non-const access to the current stream line number.
label lineNumber (const label num)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
void print (Ostream &os, const int streamState) const
Print information about the stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from IOstreamOption
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
Enumeration for stream open/closed state.
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision.
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Static Public Attributes inherited from IOstream
static unsigned int precision_
Default precision.
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Protected Member Functions inherited from OFstreamAllocator
OFstreamAllocator (const fileName &pathname, IOstream::compressionType compression=IOstream::UNCOMPRESSED, const bool append=false)
Construct from pathname.
~OFstreamAllocator ()
Destructor.
void deallocate ()
Delete the stream pointer.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from OFstreamAllocator
std::ostream * allocatedPtr_
The allocated stream pointer (ofstream or ogzstream).
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
Number of spaces per indent level.
unsigned short indentLevel_ = 0
Current indent level.
Protected Attributes inherited from IOstream
streamAccess openClosed_
ios_base::iostate ioState_
unsigned short labelByteSize_
The label byte-size (could also be stored as byte)
unsigned short scalarByteSize_
The scalar byte-size (could also be stored as byte)
label lineNumber_
The file line.
Static Protected Attributes inherited from Ostream
static constexpr const
unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Static Protected Attributes inherited from IOstream
static fileName staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
OFstream that keeps track of vertices.
Source files
OBJstream.H
OBJstream.C
Definition at line 52 of file OBJstream.H.
Constructor & Destructor Documentation
OBJstream (const fileName & pathname, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED)
Construct from pathname.
Definition at line 57 of file OBJstream.C.
~OBJstream () default
Destructor.
Member Function Documentation
ClassName ("OBJstream")
label nVertices () const inline
Return the number of vertices written.
Definition at line 100 of file OBJstream.H.
Foam::Ostream & write (const char c) virtual
Write character.
Reimplemented from OSstream.
Definition at line 72 of file OBJstream.C.
Referenced by distributedTriSurfaceMesh::distribute(), and meshRefinement::zonify().
Foam::Ostream & write (const char * str) virtual
Write character string.
Reimplemented from OSstream.
Definition at line 79 of file OBJstream.C.
Foam::Ostream & write (const word & str) virtual
Write word.
Reimplemented from OSstream.
Definition at line 89 of file OBJstream.C.
References iter.
Foam::Ostream & write (const string & str) virtual
Write string.
Reimplemented from OSstream.
Definition at line 95 of file OBJstream.C.
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Reimplemented from OSstream.
Definition at line 102 of file OBJstream.C.
Foam::Ostream & write (const point & pt)
Write point.
Definition at line 158 of file OBJstream.C.
Foam::Ostream & write (const point & pt, const vector & n)
Write point and vector normal ('vn')
Definition at line 165 of file OBJstream.C.
References Foam::nl, Foam::vtk::write(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Foam::Ostream & write (const edge & e, const UList< point > & points)
Write edge as points and line.
Definition at line 173 of file OBJstream.C.
References Foam::nl, Foam::vtk::write(), OSstream::write(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Foam::Ostream & write (const linePointRef & ln)
Write line.
Definition at line 182 of file OBJstream.C.
Foam::Ostream & write (const linePointRef & ln, const vector & n0, const vector & n1)
Write line with points and vector normals ('vn')
Definition at line 192 of file OBJstream.C.
Foam::Ostream & write (const triPointRef & f, const bool lines = true)
Write triangle as points and lines/filled-polygon.
Definition at line 206 of file OBJstream.C.
Foam::Ostream & write (const face & f, const UList< point > & points, const bool lines = true)
Write face as points and lines/filled-polygon.
Definition at line 238 of file OBJstream.C.
Foam::Ostream & write (const UList< face > & faces, const pointField & points, const bool lines = true)
Write patch faces as points and lines/filled-polygon.
Definition at line 272 of file OBJstream.C.
Foam::Ostream & write (const UList< edge > & edges, const UList< point > & points, const bool compact = false)
Write edges as points and lines.
Optionally eliminate unused points.
Definition at line 320 of file OBJstream.C.
Foam::Ostream & write (const treeBoundBox & bb, const bool lines = true)
Write tree-bounding box as lines/filled-polygons.
Definition at line 382 of file OBJstream.C.
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/obj/OBJstream.H
src/surfMesh/surfaceFormats/obj/OBJstream.C