OpenFOAM: nutWallFunctionFvPatchScalarField Class Reference
nutWallFunctionFvPatchScalarField Class Reference abstract
Wall functions
The class nutWallFunction is a base class that parents the derived boundary conditions which provide a wall constraint on various fields, such as turbulence kinematic viscosity, i.e. nut, for low- and high-Reynolds number turbulence models.
Public Member Functions
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given nutWallFunctionFvPatchScalarField onto a new patch.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar Cmu () const
Return Cmu.
scalar kappa () const
Return kappa.
scalar E () const
Return E.
scalar yPlusLam () const
Return the y+ at the edge of the viscous sublayer.
virtual tmp< scalarField > yPlus () const =0
Calculate and return the yPlus at the boundary.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Static Public Member Functions
static const
nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Return the nut patchField for the given wall patch.
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the y+ at the edge of the viscous sublayer.
Protected Member Functions
virtual const volVectorField & U (const turbulenceModel &turb) const
Helper to return the velocity field either from the turbulence model (default) or the mesh database.
virtual void checkType ()
Check the type of the patch.
virtual tmp< scalarField > calcNut () const =0
Calculate the turbulence viscosity.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
word UName_
Name of velocity field.
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Estimated y+ value at the edge of the viscous sublayer.
Detailed Description
The class nutWallFunction is a base class that parents the derived boundary conditions which provide a wall constraint on various fields, such as turbulence kinematic viscosity, i.e. nut, for low- and high-Reynolds number turbulence models.
Reference:
    Default model coefficients:
        Versteeg, H. K., & Malalasekera, W. (2011).
        An introduction to computational fluid dynamics: the finite
        volume method. Harlow: Pearson Education.
        Subsection "3.5.2 k-epsilon model".
Usage
Property Description Required Default value
Cmu Cmu coefficient no 0.09
kappa Von Karman constant no 0.41
E E coefficient no 9.8
Examples of the boundary condition specification:
    <patchName>
    {
        // Mandatory entries
        type            nutWallFunction;
        // Optional entries
    }
See Also
Foam::fixedValueFvPatchField
Source files
nutWallFunctionFvPatchScalarField.H
nutWallFunctionFvPatchScalarField.C
Definition at line 106 of file nutWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 87 of file nutWallFunctionFvPatchScalarField.C.
nutWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 123 of file nutWallFunctionFvPatchScalarField.C.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given nutWallFunctionFvPatchScalarField onto a new patch.
Definition at line 104 of file nutWallFunctionFvPatchScalarField.C.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 141 of file nutWallFunctionFvPatchScalarField.C.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 157 of file nutWallFunctionFvPatchScalarField.C.
Member Function Documentation
const Foam::volVectorField & U (const turbulenceModel & turb) const protected virtual
Helper to return the velocity field either from the turbulence model (default) or the mesh database.
Definition at line 53 of file nutWallFunctionFvPatchScalarField.C.
Referenced by nutUWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUBlendedWallFunctionFvPatchScalarField::calcNut(), and nutUSpaldingWallFunctionFvPatchScalarField::calcNut().
void checkType () protected virtual
Check the type of the patch.
Definition at line 38 of file nutWallFunctionFvPatchScalarField.C.
References Foam::defineTypeNameAndDebug().
virtual tmp<scalarField> calcNut () const protected pure virtual
Calculate the turbulence viscosity.
Implemented in nutUSpaldingWallFunctionFvPatchScalarField, nutUBlendedWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, nutkAtmRoughWallFunctionFvPatchScalarField, nutUWallFunctionFvPatchScalarField, nutkWallFunctionFvPatchScalarField, nutLowReWallFunctionFvPatchScalarField, and nutkFilmWallFunctionFvPatchScalarField.
void writeLocalEntries (Ostream & os) const protected virtual
Write local wall function variables.
Reimplemented in nutUSpaldingWallFunctionFvPatchScalarField.
Definition at line 69 of file nutWallFunctionFvPatchScalarField.C.
TypeName ("nutWallFunction")
Runtime type information.
scalar Cmu () const inline
Return Cmu.
Definition at line 232 of file nutWallFunctionFvPatchScalarField.H.
scalar kappa () const inline
Return kappa.
Definition at line 240 of file nutWallFunctionFvPatchScalarField.H.
scalar E () const inline
Return E.
Definition at line 248 of file nutWallFunctionFvPatchScalarField.H.
const Foam::nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel & turbModel, const label patchi) static
Return the nut patchField for the given wall patch.
Definition at line 177 of file nutWallFunctionFvPatchScalarField.C.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), and nutUSpaldingWallFunctionFvPatchScalarField::calcNut().
Foam::scalar yPlusLam (const scalar kappa, const scalar E) static
Calculate the y+ at the edge of the viscous sublayer.
Definition at line 192 of file nutWallFunctionFvPatchScalarField.C.
Foam::scalar yPlusLam () const
Return the y+ at the edge of the viscous sublayer.
Definition at line 208 of file nutWallFunctionFvPatchScalarField.C.
virtual tmp<scalarField> yPlus () const pure virtual
Calculate and return the yPlus at the boundary.
Implemented in nutURoughWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutUBlendedWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, nutUWallFunctionFvPatchScalarField, nutkFilmWallFunctionFvPatchScalarField, nutkWallFunctionFvPatchScalarField, and nutLowReWallFunctionFvPatchScalarField.
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 214 of file nutWallFunctionFvPatchScalarField.C.
void write (Ostream & os) const virtual
Write.
Reimplemented in nutURoughWallFunctionFvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarField, nutkRoughWallFunctionFvPatchScalarField, nutUBlendedWallFunctionFvPatchScalarField, nutkAtmRoughWallFunctionFvPatchScalarField, nutUTabulatedWallFunctionFvPatchScalarField, nutUWallFunctionFvPatchScalarField, and nutkFilmWallFunctionFvPatchScalarField.
Definition at line 228 of file nutWallFunctionFvPatchScalarField.C.
Member Data Documentation
word UName_ protected
Name of velocity field.
Defult is null (not specified) in which case the velocity is retrieved from the turbulence model
Definition at line 120 of file nutWallFunctionFvPatchScalarField.H.
scalar Cmu_ protected
Cmu coefficient.
Definition at line 125 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), and nutkFilmWallFunctionFvPatchScalarField::calcUTau().
scalar kappa_ protected
Von Karman constant.
Definition at line 130 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), and nutkFilmWallFunctionFvPatchScalarField::calcUTau().
scalar E_ protected
E coefficient.
Definition at line 135 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), and nutUWallFunctionFvPatchScalarField::calcNut().
scalar yPlusLam_ protected
Estimated y+ value at the edge of the viscous sublayer.
Definition at line 140 of file nutWallFunctionFvPatchScalarField.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), and nutUWallFunctionFvPatchScalarField::calcNut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutWallFunction/nutWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutWallFunction/nutWallFunctionFvPatchScalarField.C