OpenFOAM: MPPICParcel< ParcelType > Class Template Reference
MPPICParcel< ParcelType > Class Template Reference
Parcels
Wrapper around kinematic parcel types to add MPPIC modelling.
Classes
class iNew
Factory class to read-construct particles used for.
class trackingData
Public Member Functions
TypeName ("MPPICParcel")
Runtime type information.
AddToPropertyList (ParcelType," (UCorrectx UCorrecty UCorrectz)")
String representation of properties.
MPPICParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from mesh, coordinates and topology.
MPPICParcel (const polyMesh &mesh, const vector &position, const label celli)
Construct from a position and a cell, searching for the rest of the.
MPPICParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &UCorrect0, const typename ParcelType::constantProperties &constProps)
Construct from components.
MPPICParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
MPPICParcel (const MPPICParcel &p)
Construct as a copy.
MPPICParcel (const MPPICParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
const vector & UCorrect () const
Return const access to correction velocity.
vector & UCorrect ()
Return access to correction velocity.
template<class TrackCloudType >
bool move (TrackCloudType &cloud, trackingData &td, const scalar trackTime)
Move the parcel.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
Write individual parcel properties to stream.
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
Read.
template<class CloudType >
static void writeFields (const CloudType &c)
Write.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields
Size in bytes of the fields.
Protected Attributes
vector UCorrect_
Velocity correction due to collisions [m/s].
Friends
Ostream & operator (Ostream &, const MPPICParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::MPPICParcel< ParcelType >
Wrapper around kinematic parcel types to add MPPIC modelling.
Source files
MPPICParcel.H
MPPICParcelI.H
MPPICParcelTrackingDataI.H
MPPICParcel.C
MPPICParcelIO.C
Definition at line 54 of file MPPICParcel.H.
Constructor & Destructor Documentation
MPPICParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Construct from mesh, coordinates and topology.
Other properties initialised as null
Definition at line 25 of file MPPICParcelI.H.
MPPICParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Construct from a position and a cell, searching for the rest of the.
required topology. Other properties are initialised as null.
Definition at line 40 of file MPPICParcelI.H.
MPPICParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & UCorrect0, const typename ParcelType::constantProperties & constProps) inline
Construct from components.
Definition at line 53 of file MPPICParcelI.H.
MPPICParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 44 of file MPPICParcelIO.C.
MPPICParcel (const MPPICParcel< ParcelType > & p)
Construct as a copy.
MPPICParcel (const MPPICParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
TypeName ("MPPICParcel< ParcelType >")
Runtime type information.
AddToPropertyList (ParcelType , " (UCorrectx UCorrecty UCorrectz)")
String representation of properties.
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 289 of file MPPICParcel.H.
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 297 of file MPPICParcel.H.
const Foam::vector & UCorrect () const inline
Return const access to correction velocity.
Definition at line 89 of file MPPICParcelI.H.
Foam::vector & UCorrect () inline
Return access to correction velocity.
Definition at line 96 of file MPPICParcelI.H.
bool move (TrackCloudType & cloud, trackingData & td, const scalar trackTime)
Move the parcel.
Definition at line 53 of file MPPICParcel.C.
References f(), p, MPPICParcel< ParcelType >::trackingData::part(), KinematicParcel< ParcelType >::trackingData::tpLinearTrack, and KinematicParcel< ParcelType >::U().
void readFields (CloudType & c) static
Read.
Definition at line 82 of file MPPICParcelIO.C.
void writeFields (const CloudType & c) static
Write.
Definition at line 107 of file MPPICParcelIO.C.
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Write individual parcel properties to stream.
Definition at line 131 of file MPPICParcelIO.C.
void readObjects (CloudType & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 153 of file MPPICParcelIO.C.
void writeObjects (const CloudType & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Definition at line 177 of file MPPICParcelIO.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const MPPICParcel< ParcelType > &) friend
Member Data Documentation
const std::size_t sizeofFields static
Size in bytes of the fields.
Definition at line 82 of file MPPICParcel.H.
vector UCorrect_ protected
Velocity correction due to collisions [m/s].
Definition at line 196 of file MPPICParcel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcel.C
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelI.H
src/lagrangian/intermediate/parcels/Templates/MPPICParcel/MPPICParcelIO.C