OpenFOAM: Tuple2< T1, T2 > Class Template Reference
Tuple2< T1, T2 > Class Template Reference
A 2-tuple for storing two objects of dissimilar types. The container is similar in purpose to std::pair, but does not expose its members directly.
Public Types
typedef T1 first_type
Type of member first, the first template parameter (T1)
typedef T2 second_type
Type of member second, the second template parameter (T2)
Public Member Functions
Tuple2 ()=default
Construct null.
Tuple2 (const T1 &f, const T2 &s)
Copy construct from components.
Tuple2 (T1 &&f, T2 &&s)
Move construct from components.
Tuple2 (const std::pair< T1, T2 > &vals)
Copy construct from std::pair.
Tuple2 (std::pair< T1, T2 > &&vals)
Move construct from std::pair.
Tuple2 (Istream &is)
Construct from Istream.
const T1 & first () const noexcept
Return first.
T1 & first () noexcept
Return first.
const T2 & second () const noexcept
Return second.
T2 & second () noexcept
Return second.
Detailed Description
template<class T1, class T2>
class Foam::Tuple2< T1, T2 >
A 2-tuple for storing two objects of dissimilar types. The container is similar in purpose to std::pair, but does not expose its members directly.
See Also
Foam::Pair for storing two objects of identical types.
Definition at line 51 of file Tuple2.H.
Member Typedef Documentation
typedef T1 first_type
Type of member first, the first template parameter (T1)
Definition at line 65 of file Tuple2.H.
typedef T2 second_type
Type of member second, the second template parameter (T2)
Definition at line 70 of file Tuple2.H.
Constructor & Destructor Documentation
Tuple2 () inline default
Construct null.
Tuple2 (const T1 & f, const T2 & s) inline
Copy construct from components.
Definition at line 83 of file Tuple2.H.
Tuple2 (T1 && f, T2 && s) inline
Move construct from components.
Definition at line 92 of file Tuple2.H.
Tuple2 (const std::pair< T1, T2 > & vals) inline
Copy construct from std::pair.
Definition at line 101 of file Tuple2.H.
Tuple2 (std::pair< T1, T2 > && vals) inline
Move construct from std::pair.
Definition at line 110 of file Tuple2.H.
Tuple2 (Istream & is) inline explicit
Construct from Istream.
Definition at line 119 of file Tuple2.H.
Member Function Documentation
const T1& first () const inline noexcept
Return first.
Definition at line 130 of file Tuple2.H.
Referenced by distributedTriSurfaceMesh::findNearest(), scalars::operation(), nearestEqOp::operator()(), mappedPatchBase::nearestEqOp::operator()(), mappedPatchBase::maxProcEqOp::operator()(), minFirstOp< T1 >::operator()(), minFirstEqOp< T1 >::operator()(), maxFirstOp< T1 >::operator()(), forceSuSp::operator+=(), forceSuSp::operator-=(), Foam::operator>=(), and Tuple2< scalar, Foam::Vector >::second().
T1& first () inline noexcept
Return first.
Definition at line 138 of file Tuple2.H.
const T2& second () const inline noexcept
Return second.
Definition at line 146 of file Tuple2.H.
Referenced by distributedTriSurfaceMesh::findNearest(), scalars::operation(), nearestEqOp::operator()(), mappedPatchBase::nearestEqOp::operator()(), mappedPatchBase::maxProcEqOp::operator()(), maxFirstOp< T1 >::operator()(), forceSuSp::operator+=(), forceSuSp::operator-=(), and Tuple2< scalar, Foam::Vector >::second().
T2& second () inline noexcept
Return second.
Definition at line 154 of file Tuple2.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/primitives/Tuple2/Tuple2.H