OpenFOAM: VectorSpace< Form, Cmpt, Ncmpts > Class Template Reference
VectorSpace< Form, Cmpt, Ncmpts > Class Template Reference
Templated vector space.
Classes
class ConstBlock
Const sub-block type.
Public Types
typedef VectorSpace< Form,
Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
typedef Cmpt magType
Magnitude type.
typedef Cmpt * iterator
Random access iterator for traversing VectorSpace.
typedef const Cmpt * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > &vs)
Copy construct.
template<class Form2 , class Cmpt2 >
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Return const pointer to the first data element.
Cmpt * data () noexcept
Return pointer to the first data element.
template<class SubVector , direction BStart>
const ConstBlock< SubVector,
BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
template<class SubVector , Foam::direction BStart>
const Foam::VectorSpace< Form,
Cmpt, Ncmpts >::template
ConstBlock< SubVector, BStart > block () const
Static Public Member Functions
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Form uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes
Cmpt v_ [Ncmpts]
The components of this vector space.
Static Public Attributes
static constexpr direction dim = 3
Dimensionality of space.
static constexpr direction nComponents = Ncmpts
Number of components in this vector space.
static constexpr direction mRows = Ncmpts
static constexpr direction nCols = 1
static const char *const typeName = "diagTensor"
static const char *const componentNames []
static const Form zero
static const Form one
static const Form max
static const Form min
static const Form rootMax
static const Form rootMin
Friends
Istream & operator>> (Istream &, VectorSpace< Form, Cmpt, Ncmpts > &)
Ostream & operator (Ostream &, const VectorSpace< Form, Cmpt, Ncmpts > &)
Detailed Description
template<class Form, class Cmpt, direction Ncmpts>
class Foam::VectorSpace< Form, Cmpt, Ncmpts >
Templated vector space.
Template arguments are the Form the vector space will be used to create, the type of the elements and the number of elements.
Source files
VectorSpace.H
VectorSpaceI.H
VectorSpace.C
Definition at line 52 of file VectorSpace.H.
Member Typedef Documentation
typedef VectorSpace<Form, Cmpt, Ncmpts> vsType
VectorSpace type.
Definition at line 86 of file VectorSpace.H.
typedef Cmpt cmptType
Component type.
Definition at line 91 of file VectorSpace.H.
typedef Cmpt magType
Magnitude type.
Definition at line 96 of file VectorSpace.H.
typedef Cmpt* iterator
Random access iterator for traversing VectorSpace.
Definition at line 249 of file VectorSpace.H.
typedef const Cmpt* const_iterator
Random access iterator for traversing VectorSpace.
Definition at line 254 of file VectorSpace.H.
Constructor & Destructor Documentation
VectorSpace () inline
Construct null.
Definition at line 32 of file VectorSpaceI.H.
VectorSpace (const Foam::zero) inline
Construct initialized to zero.
Definition at line 37 of file VectorSpaceI.H.
VectorSpace (Istream & is)
Construct from Istream.
Definition at line 30 of file VectorSpace.C.
References IOstream::check(), FUNCTION_NAME, i, Istream::readBegin(), and Istream::readEnd().
VectorSpace (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Copy construct.
Definition at line 45 of file VectorSpaceI.H.
References Foam::Zero.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > & vs) inline explicit
Copy construct of a VectorSpace with the same size.
Definition at line 56 of file VectorSpaceI.H.
Member Function Documentation
constexpr Foam::direction size () inline static
Return the number of elements in the VectorSpace = Ncmpts.
Definition at line 85 of file VectorSpaceI.H.
Referenced by Foam::zip().
const Cmpt & component (const direction d) const inline
Definition at line 93 of file VectorSpaceI.H.
Referenced by Foam::component(), and cellMDLimitedGrad< Type >::limitFace().
Cmpt & component (const direction d) inline
Definition at line 112 of file VectorSpaceI.H.
void component (Cmpt & c, const direction d) const inline
Definition at line 131 of file VectorSpaceI.H.
void replace (const direction d, const Cmpt & c) inline
Definition at line 151 of file VectorSpaceI.H.
const Cmpt * cdata () const inline noexcept
Return const pointer to the first data element.
Definition at line 198 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_.
Cmpt * data () inline noexcept
Return pointer to the first data element.
Definition at line 191 of file VectorSpaceI.H.
Form uniform (const Cmpt & s) inline static
Return a VectorSpace with all elements = s.
Definition at line 170 of file VectorSpaceI.H.
const ConstBlock<SubVector, BStart> block () const inline
const Cmpt & operator[] (const direction d) const inline
Definition at line 250 of file VectorSpaceI.H.
Cmpt & operator[] (const direction d) inline
Definition at line 269 of file VectorSpaceI.H.
void operator= (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Definition at line 340 of file VectorSpaceI.H.
void operator+= (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Definition at line 350 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp().
void operator-= (const VectorSpace< Form, Cmpt, Ncmpts > & vs) inline
Definition at line 360 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp().
void operator= (const Foam::zero) inline
Definition at line 369 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOp().
void operator*= (const scalar s) inline
Definition at line 377 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOpS().
void operator/= (const scalar s) inline
Definition at line 387 of file VectorSpaceI.H.
References VectorSpaceOps< N, I >::eqOpS(), and s.
Cmpt * begin () inline
Return an iterator to begin of VectorSpace.
Definition at line 205 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_.
Cmpt * end () inline
Return an iterator to end of VectorSpace.
Definition at line 212 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_.
const Cmpt * cbegin () const inline
Return const_iterator to begin of VectorSpace.
Definition at line 219 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_.
const Cmpt * cend () const inline
Return const_iterator to end of VectorSpace.
Definition at line 226 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_.
const Cmpt * begin () const inline
Return const_iterator to begin of VectorSpace.
Definition at line 233 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_.
const Cmpt * end () const inline
Return const_iterator to end of VectorSpace.
Definition at line 240 of file VectorSpaceI.H.
References VectorSpace< Form, Cmpt, Ncmpts >::v_.
const Foam::VectorSpace<Form, Cmpt, Ncmpts>::template ConstBlock<SubVector, BStart> block () const inline
Definition at line 182 of file VectorSpaceI.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & , VectorSpace< Form, Cmpt, Ncmpts > &) friend
Ostream& operator (Ostream & , const VectorSpace< Form, Cmpt, Ncmpts > &) friend
Member Data Documentation
Cmpt v_[Ncmpts]
The components of this vector space.
Definition at line 81 of file VectorSpace.H.
Referenced by VectorSpace< Form, Cmpt, Ncmpts >::begin(), VectorSpace< Form, Cmpt, Ncmpts >::cbegin(), VectorSpace< Form, Cmpt, Ncmpts >::cdata(), VectorSpace< Form, Cmpt, Ncmpts >::cend(), and VectorSpace< Form, Cmpt, Ncmpts >::end().
constexpr direction dim = 3 static
Dimensionality of space.
Definition at line 104 of file VectorSpace.H.
constexpr direction nComponents = Ncmpts static
Number of components in this vector space.
Definition at line 109 of file VectorSpace.H.
constexpr direction mRows = Ncmpts static
Definition at line 115 of file VectorSpace.H.
constexpr direction nCols = 1 static
Definition at line 116 of file VectorSpace.H.
const char *const typeName = "diagTensor" static
Definition at line 121 of file VectorSpace.H.
const char *const componentNames static
Initial value:
=
{
    "xx", "yy", "zz"
}
Definition at line 122 of file VectorSpace.H.
const Foam::vector2D zero static
Definition at line 123 of file VectorSpace.H.
const Foam::vector2D one static
Definition at line 124 of file VectorSpace.H.
const Foam::vector2D max static
Definition at line 125 of file VectorSpace.H.
Referenced by distributedTriSurfaceMesh::overlappingSurface(), sampledTriSurfaceMesh::update(), and discreteSurface::update().
const Foam::vector2D min static
Definition at line 126 of file VectorSpace.H.
Referenced by distributedTriSurfaceMesh::overlappingSurface(), sampledTriSurfaceMesh::update(), and discreteSurface::update().
const Foam::vector2D rootMax static
Definition at line 127 of file VectorSpace.H.
const Foam::vector2D rootMin static
Definition at line 128 of file VectorSpace.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/VectorSpace/VectorSpace.H
src/OpenFOAM/primitives/DiagTensor/diagTensor/diagTensor.C
src/OpenFOAM/primitives/spatialVectorAlgebra/CompactSpatialTensor/compactSpatialTensor/compactSpatialTensor.C
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialTensor/spatialTensor/spatialTensor.C
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialVector/spatialVector/spatialVector.C
src/OpenFOAM/primitives/SphericalTensor/labelSphericalTensor/labelSphericalTensor.C
src/OpenFOAM/primitives/SphericalTensor/sphericalTensor/sphericalTensor.C
src/OpenFOAM/primitives/SphericalTensor2D/sphericalTensor2D/sphericalTensor2D.C
src/OpenFOAM/primitives/SymmTensor/labelSymmTensor/labelSymmTensor.C
src/OpenFOAM/primitives/SymmTensor/symmTensor/symmTensor.C
src/OpenFOAM/primitives/SymmTensor2D/symmTensor2D/symmTensor2D.C
src/OpenFOAM/primitives/Tensor/doubleTensor/doubleTensor.C
src/OpenFOAM/primitives/Tensor/floatTensor/floatTensor.C
src/OpenFOAM/primitives/Tensor/labelTensor/labelTensor.C
src/OpenFOAM/primitives/Tensor/tensor/tensor.C
src/OpenFOAM/primitives/Tensor2D/tensor2D/tensor2D.C
src/OpenFOAM/primitives/triad/triad.C
src/OpenFOAM/primitives/Vector/complexVector/complexVector.C
src/OpenFOAM/primitives/Vector/doubleVector/doubleVector.C
src/OpenFOAM/primitives/Vector/floatVector/floatVector.C
src/OpenFOAM/primitives/Vector/labelVector/labelVector.C
src/OpenFOAM/primitives/Vector/vector/vector.C
src/OpenFOAM/primitives/Vector2D/labelVector2D/labelVector2D.C
src/OpenFOAM/primitives/Vector2D/vector2D/vector2D.C
src/OpenFOAM/primitives/VectorSpace/VectorSpace.C
src/OpenFOAM/primitives/VectorSpace/VectorSpaceI.H