OpenFOAM: fvExprDriver Class Reference
fvExprDriver Class Reference abstract
Base driver for parsing value expressions associated with an fvMesh.
Public Member Functions
TypeName ("fvExprDriver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvExprDriver, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
declareRunTimeSelectionTable (autoPtr, fvExprDriver, idName,(const word &ident, const fvMesh &mesh),(ident, mesh))
fvExprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
fvExprDriver (const fvExprDriver &)
Copy construct.
fvExprDriver (const dictionary &dict)
Construct from a dictionary.
virtual autoPtr< fvExprDriver > clone () const =0
Clone.
virtual ~fvExprDriver ()
Destructor.
virtual label size () const =0
The underlying field size for the expression.
virtual label pointSize () const =0
The underlying point field size for the expression.
const Time & runTime () const
The Time associated with the mesh.
virtual word timeName () const
The current time name.
virtual scalar timeValue () const
The current time value.
bool cacheSets () const
Status of cache-sets (static variable)
virtual void clearVariables ()
Clear temporary variables and resets from expression strings.
virtual bool hasVariable (const word &name) const
True if named variable exists.
virtual const exprResult & variable (const word &name) const
Return const-access to the named variable.
template<class Type >
bool isVariableOrField (const word &name, bool isPointVal=false, label expectSize=-1) const
Test for existence of a local/global variable or a field.
template<class Type >
tmp< Field< Type > > getVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
word getFieldClassName (const word &name) const
Lookup the field class name (memory or read from disk)
topoSetSource::sourceType topoSetType (const word &name) const
Return cell/face/point set type or unknown.
topoSetSource::sourceType topoZoneType (const word &name) const
Return cell/face/point zone type or unknown.
topoSetSource::sourceType topoSourceType (const word &name) const
Return cell/face/point zone/set type or unknown.
labelList getTopoSetLabels (const word &name, enum topoSetSource::sourceType setType) const
Read and return labels associated with the topo set.
bool isCellZone (const word &name) const
Test if name is a known cellZone.
bool isFaceZone (const word &name) const
Test if name is a known faceZone.
bool isPointZone (const word &name) const
Test if name is a known pointZone.
bool isCellSet (const word &name) const
Test if name is a known cellSet.
bool isFaceSet (const word &name) const
Test if name is a known faceSet.
bool isPointSet (const word &name) const
Test if name is a known pointSet.
virtual void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
Evaluate an expression on a remote and save as the specified named variable.
template<class Type >
bool isVariable (const word &name, bool isPointVal=false, label expectSize=-1) const
Test existence of a local/global variable.
template<class Type >
bool foundField (const word &name) const
Test if specified field can be found in memory or disk.
word getTypeOfField (const word &fieldName) const
Read the IOobject for fieldName and return its headerClassName.
virtual bool readDict (const dictionary &dict)
Read variables, tables etc.
Ostream & writeCommon (Ostream &os, bool debug=false) const
Write "variables", "storedVariables", "delayedVariables", "globalScopes" if they are present.
void createWriterAndRead (const word &name)
Create a writer for this object.
void tryWrite () const
Write data if apropriate Should enable exact restarts.
template<class GeomField >
Foam::tmp< GeomField > getOrReadField (const word &name, bool mandatory, bool getOldTime)
template<class GeomField >
Foam::tmp< GeomField > getOrReadPointField (const word &name, bool mandatory, bool getOldTime)
template<class GeomField , class Mesh >
Foam::tmp< GeomField > readAndRegister (const word &name, const Mesh &meshRef)
template<class Type >
Foam::tmp< Foam::Field< Type > > getVariable (const word &name, label expectedSize, const bool mandatory) const
template<class GeomField , class Mesh >
Foam::tmp< GeomField > getOrReadFieldImpl (const word &name, const Mesh &meshRef, bool mandatory, bool getOldTime)
template<class T >
Foam::autoPtr< T > getTopoSet (const fvMesh &mesh, const word &name, SetOrigin &origin) const
Public Member Functions inherited from exprDriver
TypeName ("exprDriver")
Runtime type information.
exprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
exprDriver (const exprDriver &)
Copy construct.
exprDriver (const dictionary &dict)
Construct from a dictionary.
virtual ~exprDriver ()=default
Destructor.
const dictionary & dict () const
The dictionary with all input data/specification.
virtual const exprResult & result () const
Const access to expression result.
virtual exprResult & result ()
Non-const access to expression result.
void clearResult ()
Clear the result.
template<class Type >
tmp< Field< Type > > getResult (bool isPointVal=false)
Return the expression result as a tmp field.
virtual word getResultType () const
The result type as word - same as result().valueType()
int stashedTokenId () const
Get "look-behind" parsing context (internal bookkeeping)
int resetStashedTokenId (int tokenId=0) const
Reset "look-behind" parsing context (mutable operation)
void setDebugging (bool scannerDebug, bool parserDebug)
Set the scanner/parser debug.
void setDebugging (const exprDriver &rhs)
Set the scanner/parser debug to match the input.
void setSearchBehaviour (bool cacheReadFields, bool searchInMemory, bool searchFiles)
Set search behaviour.
void setSearchBehaviour (const exprDriver &rhs)
Set search behaviour to be identical to rhs.
bool debugScanner () const
Read access to scanner debug.
bool debugParser () const
Read access to parser debug.
bool cacheReadFields () const
bool searchInMemory () const
bool searchFiles () const
bool prevIterIsOldTime () const
void addVariables (const expressions::exprString &expr, bool clear=true)
Add/set string expressions for variables.
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
Add/set string expressions for variables.
template<class T >
void addUniformVariable (const word &name, const T &val)
Add a uniform variable from an outside caller.
template<class T >
bool isLocalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a local variable.
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)=0
Execute the parser.
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return the field.
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return a single value.
void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
Return a new field with the size()
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
Return a new field with the pointSize()
expressions::exprString readExpression (const word &name)
Read an expression string (with the current dictionary) and do substitutions.
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Read "variables" and assigns to the list of expression strings.
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
Write "variables".
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Static Public Member Functions
static const fvMesh & defaultMesh ()
Get the default mesh, if one is defined.
static const fvMesh * resetDefaultMesh (const fvMesh &mesh, const bool force=false)
Set the default mesh (if not already set)
static autoPtr< fvExprDriver > New (const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected value driver.
static autoPtr< fvExprDriver > New (const dictionary &dict)
Return a reference to the selected value driver.
static autoPtr< fvExprDriver > New (const word &type, const word &id, const fvMesh &mesh)
Return a reference to the selected value driver.
Static Public Member Functions inherited from exprDriver
static expressions::exprString readExpression (const word &name, const dictionary &dict)
Read an expression string and do substitutions.
static List
< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Read the list of variable strings.
Protected Types
enum SetOrigin {
INVALID = 0, NEW, FILE, MEMORY,
CACHE
}
The origin of the topoSet.
Protected Member Functions
virtual const fvMesh & mesh () const =0
The mesh we are attached to.
void setGlobalScopes (const wordUList &scopes)
Define scopes for global variables.
virtual exprResult & variable (const word &name)
Non-const access to the named variable (sub-classes only)
template<class T >
bool isGlobalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a global variable.
const exprResult & lookupGlobal (const word &name) const
Return the global variable if available or a null result.
template<class Type >
bool isField (const word &name, bool isPointVal=false, label expectSize=-1) const
Test for the existence of a mesh field.
template<class GeomField >
tmp< GeomField > getOrReadField (const word &name, bool mandatory=true, bool getOldTime=false)
Retrieve field from memory or disk.
template<class GeomField >
tmp< GeomField > getOrReadPointField (const word &name, bool mandatory=true, bool getOldTime=false)
Retrieve point field from memory or disk.
template<class GeomField , class MeshRef >
tmp< GeomField > getOrReadFieldImpl (const word &name, const MeshRef &meshRef, bool mandatory=true, bool getOldTime=false)
Retrieve field from memory or disk (implementation)
template<class GeomField , class MeshRef >
tmp< GeomField > readAndRegister (const word &name, const MeshRef &meshRef)
Helper function for getOrReadField.
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Create a random field.
template<class T >
autoPtr< T > getTopoSet (const fvMesh &mesh, const word &setName, SetOrigin &origin) const
Get topoSet.
template<class T >
bool updateSet (autoPtr< T > &setPtr, const word &setName, SetOrigin origin) const
Update topoSet.
virtual void updateSpecialVariables (bool force=false)
Examine current variable values and update stored variables.
virtual bool hasDataToWrite () const
Do we need a data file to be written.
virtual void prepareData (dictionary &dict) const
Prepare/update special variables and add to dictionary, normally via the reader/writer.
virtual void getData (const dictionary &dict)
Read data from dictionary, normally via the reader/writer.
Protected Member Functions inherited from exprDriver
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Fill a random field.
virtual bool update ()
Update things.
virtual exprResult getRemoteResult (const exprDriver &other) const
Get the result from another driver.
void operator= (const exprDriver &)=delete
No copy assignment.
Static Protected Member Functions
static const fvMesh & regionMesh (const dictionary &dict, const fvMesh &mesh, bool readIfNecessary)
Determine mesh or region mesh as specified in the dictionary with the keyword "region".
template<class T >
static word defaultBoundaryType (const T &)
Default boundary type is calculated.
template<class Type >
static word defaultBoundaryType (const GeometricField< Type, fvPatchField, volMesh > &)
Default boundary type for volume fields is zeroGradient.
template<class T >
static void correctField (T &)
Apply correctBoundaryConditions (volume fields only)
template<class Type >
static void correctField (GeometricField< Type, fvPatchField, volMesh > &fld)
Static Protected Member Functions inherited from exprDriver
template<typename TableType >
static bool readTable (const word &name, const dictionary &dict, HashTable< TableType > &tbl, bool clear=true)
Read an interpolation table.
template<class TableType >
static void writeTable (Ostream &os, const word &name, const HashTable< TableType > &tbl)
Write an interpolation table.
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
The (global) weighted average of a field, with stabilisation.
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
The (global) weighted sum (integral) of a field.
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
Return the location of the min value.
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Return the location of the max value.
Friends
class exprDriverWriter
Additional Inherited Members
Protected Attributes inherited from exprDriver
const dictionary & dict_
The dictionary with all input data/specification.
exprResult result_
The result.
List< expressions::exprString > variableStrings_
Variable definitions, as read from a dictionary.
HashTable< exprResult > variables_
The variables table.
int stashedTokenId_
Internal bookkeeping as "look-behind" parsing context.
bool debugScanner_
Request debugging for scanner.
bool debugParser_
Request debugging for parser.
bool allowShadowing_
Allow variable names to mask field names.
bool prevIterIsOldTime_
Use value of previous iteration when oldTime is requested.
bool cacheReadFields_
Keep fields read from disc in memory.
bool searchInMemory_
Search in registry before looking on disk.
bool searchFiles_
Search on disk (eg, for a standalone application)
Detailed Description
Base driver for parsing value expressions associated with an fvMesh.
Largely based on code and ideas from swak4foam
Properties
Property Description Required Default
variables List of variables for expressions no ()
delayedVariables List of delayed variables no ()
storedVariables List of stored variables no ()
globalScopes Scopes for global variables no ()
allowShadowing Allow variables to shadow field names no false
Debug Properties
Property Description Required Default
debugBaseDriver Debug level (int) for base driver no
debugScanner Add debug for scanner no false
debugParser Add debug for parser no false
Source files
fvExprDriver.H
fvExprDriverI.H
fvExprDriver.C
fvExprDriverFields.C
fvExprDriverIO.C
fvExprDriverNew.C
fvExprDriverTemplates.C
Definition at line 134 of file fvExprDriver.H.
Member Enumeration Documentation
enum SetOrigin protected
The origin of the topoSet.
Enumerator
INVALID
NEW
FILE
MEMORY
CACHE
Definition at line 393 of file fvExprDriver.H.
Constructor & Destructor Documentation
fvExprDriver (bool cacheReadFields = false, bool searchInMemory = true, bool searchFiles = false, const dictionary & dict = dictionary::null) explicit
Null constructor, and null construct with search preferences.
Definition at line 89 of file fvExprDriver.C.
fvExprDriver (const fvExprDriver & rhs)
Copy construct.
Definition at line 114 of file fvExprDriver.C.
fvExprDriver (const dictionary & dict) explicit
Construct from a dictionary.
Definition at line 130 of file fvExprDriver.C.
~fvExprDriver () virtual
Destructor.
Definition at line 148 of file fvExprDriver.C.
Member Function Documentation
const Foam::fvMesh & regionMesh (const dictionary & dict, const fvMesh & mesh, bool readIfNecessary) static protected
Determine mesh or region mesh as specified in the dictionary with the keyword "region".
Definition at line 526 of file fvExprDriver.C.
static word defaultBoundaryType (const T &) inline static protected
Default boundary type is calculated.
Definition at line 237 of file fvExprDriver.H.
static word defaultBoundaryType (const GeometricField< Type, fvPatchField, volMesh > &) inline static protected
Default boundary type for volume fields is zeroGradient.
Definition at line 247 of file fvExprDriver.H.
static void correctField (T &) inline static protected
Apply correctBoundaryConditions (volume fields only)
Definition at line 259 of file fvExprDriver.H.
static void correctField (GeometricField< Type, fvPatchField, volMesh > & fld) inline static protected
Definition at line 263 of file fvExprDriver.H.
virtual const fvMesh& mesh () const protected pure virtual
The mesh we are attached to.
Implemented in parseDriver, and parseDriver.
Referenced by fvExprDriver::getTopoSetLabels().
void setGlobalScopes (const wordUList & scopes) inline protected
Define scopes for global variables.
Definition at line 286 of file fvExprDriver.H.
References fvExprDriver::CACHE, fvExprDriver::FILE, fvExprDriver::INVALID, fvExprDriver::MEMORY, and fvExprDriver::NEW.
Foam::expressions::exprResult & variable (const word & name) inline protected virtual
Non-const access to the named variable (sub-classes only)
Reimplemented from exprDriver.
Definition at line 52 of file fvExprDriverI.H.
Referenced by parseDriver::getVariableIfAvailable().
bool isGlobalVariable (const word & name, bool isPointVal, label expectedSize = -1) const protected
Test existence of a global variable.
Definition at line 30 of file fvExprDriverTemplates.C.
References Foam::expressions::patchExpr::debug, DebugInfo, Foam::endl(), Foam::Info, fvExprDriver::lookupGlobal(), Foam::reduce(), and exprDriver::result().
const Foam::expressions::exprResult & lookupGlobal (const word & name) const protected
Return the global variable if available or a null result.
Definition at line 717 of file fvExprDriver.C.
References mesh.
Referenced by parseDriver::getVariableIfAvailable(), and fvExprDriver::isGlobalVariable().
bool isField (const word & name, bool isPointVal = false, label expectSize = -1) const protected
Test for the existence of a mesh field.
Parameters
expectSize ignored
Definition at line 191 of file fvExprDriverTemplates.C.
tmp<GeomField> getOrReadField (const word & name, bool mandatory = true, bool getOldTime = false) inline protected
Retrieve field from memory or disk.
tmp<GeomField> getOrReadPointField (const word & name, bool mandatory = true, bool getOldTime = false) inline protected
Retrieve point field from memory or disk.
tmp<GeomField> getOrReadFieldImpl (const word & name, const MeshRef & meshRef, bool mandatory = true, bool getOldTime = false) protected
Retrieve field from memory or disk (implementation)
tmp<GeomField> readAndRegister (const word & name, const MeshRef & meshRef) inline protected
Helper function for getOrReadField.
void fill_random (scalarField & field, label seed = 0, const bool gaussian = false) const protected
Create a random field.
Parameters
field the field to populate
seed the seed value. If zero or negative, use as an offset to the current timeIndex
gaussian generate a Gaussian distribution
Definition at line 28 of file fvExprDriverFields.C.
References exprDriver::fill_random(), fvExprDriver::runTime(), and timeIndex.
autoPtr<T> getTopoSet (const fvMesh & mesh, const word & setName, SetOrigin & origin) const protected
Get topoSet.
bool updateSet (autoPtr< T > & setPtr, const word & setName, SetOrigin origin) const inline protected
Update topoSet.
Definition at line 511 of file fvExprDriverTemplates.C.
void updateSpecialVariables (bool force = false) protected virtual
Examine current variable values and update stored variables.
Reimplemented from exprDriver.
Definition at line 257 of file fvExprDriver.C.
References runTime.
bool hasDataToWrite () const protected virtual
Do we need a data file to be written.
Definition at line 725 of file fvExprDriver.C.
References exprResultGlobals::get(), mesh, and exprResultGlobals::New().
void prepareData (dictionary & dict) const protected virtual
Prepare/update special variables and add to dictionary, normally via the reader/writer.
Definition at line 741 of file fvExprDriver.C.
References dictionary::readIfPresent().
void getData (const dictionary & dict) protected virtual
Read data from dictionary, normally via the reader/writer.
Definition at line 732 of file fvExprDriver.C.
const Foam::fvMesh & defaultMesh () static
Get the default mesh, if one is defined.
Definition at line 54 of file fvExprDriver.C.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, and Foam::nl.
const Foam::fvMesh * resetDefaultMesh (const fvMesh & mesh, const bool force = false) static
Set the default mesh (if not already set)
Parameters
force Force reset, even if already set
Definition at line 70 of file fvExprDriver.C.
TypeName ("fvExprDriver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , fvExprDriver , dictionary , (const dictionary &dict, const fvMesh &mesh) , (dict, mesh))
declareRunTimeSelectionTable (autoPtr , fvExprDriver , idName , (const word &ident, const fvMesh &mesh) , (ident, mesh))
Foam::autoPtr< Foam::expressions::fvExprDriver > New (const dictionary & dict, const fvMesh & mesh) static
Return a reference to the selected value driver.
Definition at line 42 of file fvExprDriverNew.C.
Referenced by parseDriver::getVariableIfAvailable(), and fvExprDriver::New().
Foam::autoPtr< Foam::expressions::fvExprDriver > New (const dictionary & dict) static
Return a reference to the selected value driver.
Definition at line 28 of file fvExprDriverNew.C.
References fvExprDriver::New().
Foam::autoPtr< Foam::expressions::fvExprDriver > New (const word & type, const word & id, const fvMesh & mesh) static
Return a reference to the selected value driver.
Definition at line 72 of file fvExprDriverNew.C.
virtual autoPtr<fvExprDriver> clone () const pure virtual
Clone.
Implemented in parseDriver, and parseDriver.
virtual label size () const pure virtual
The underlying field size for the expression.
Reimplemented from exprDriver.
Implemented in parseDriver, and parseDriver.
virtual label pointSize () const pure virtual
The underlying point field size for the expression.
Reimplemented from exprDriver.
Implemented in parseDriver, and parseDriver.
const Foam::Time & runTime () const
The Time associated with the mesh.
Definition at line 239 of file fvExprDriver.C.
Referenced by fvExprDriver::fill_random().
Foam::word timeName () const virtual
The current time name.
Definition at line 245 of file fvExprDriver.C.
References mesh.
Foam::scalar timeValue () const virtual
The current time value.
Definition at line 251 of file fvExprDriver.C.
References runTime.
bool cacheSets () const inline
Status of cache-sets (static variable)
Definition at line 597 of file fvExprDriver.H.
void clearVariables () virtual
Clear temporary variables and resets from expression strings.
Reimplemented from exprDriver.
Definition at line 348 of file fvExprDriver.C.
bool hasVariable (const word & name) const inline virtual
True if named variable exists.
Reimplemented from exprDriver.
Definition at line 27 of file fvExprDriverI.H.
Referenced by parseDriver::getVariableIfAvailable().
const Foam::expressions::exprResult & variable (const word & name) const inline virtual
Return const-access to the named variable.
Reimplemented from exprDriver.
Definition at line 37 of file fvExprDriverI.H.
References exprDriver::variables_.
bool isVariableOrField (const word & name, bool isPointVal = false, label expectSize = -1) const inline
Test for existence of a local/global variable or a field.
Definition at line 83 of file fvExprDriverI.H.
tmp<Field<Type> > getVariable (const word & name, label expectSize, const bool mandatory = true) const
Retrieve local/global variable as a tmp field.
Parameters
name The name of the local/global field
expectSize The size check on the variable, -1 to ignore
mandatory A missing variable is Fatal, or return an invalid tmp
Foam::word getFieldClassName (const word & name) const
Lookup the field class name (memory or read from disk)
Return empty if the name cannot be resolved.
Definition at line 585 of file fvExprDriver.C.
References mesh.
Foam::topoSetSource::sourceType topoSetType (const word & name) const
Return cell/face/point set type or unknown.
Definition at line 609 of file fvExprDriver.C.
Foam::topoSetSource::sourceType topoZoneType (const word & name) const
Return cell/face/point zone type or unknown.
Definition at line 631 of file fvExprDriver.C.
Foam::topoSetSource::sourceType topoSourceType (const word & name) const
Return cell/face/point zone/set type or unknown.
Definition at line 653 of file fvExprDriver.C.
Foam::labelList getTopoSetLabels (const word & name, enum topoSetSource::sourceType setType) const
Read and return labels associated with the topo set.
Definition at line 31 of file fvExprDriverIO.C.
References polyMesh::cellZones(), Foam::endl(), Foam::exit(), polyMesh::faceZones(), Foam::FatalError, FatalErrorInFunction, topoSet::findIOobject(), IOobject::headerClassName(), fvExprDriver::mesh(), Foam::nl, List< label >::null(), polyMesh::pointZones(), set(), and zoneID.
Referenced by parseDriver::field_cellSelection().
bool isCellZone (const word & name) const
Test if name is a known cellZone.
Definition at line 697 of file fvExprDriver.C.
bool isFaceZone (const word & name) const
Test if name is a known faceZone.
Definition at line 703 of file fvExprDriver.C.
References mesh.
bool isPointZone (const word & name) const
Test if name is a known pointZone.
Definition at line 709 of file fvExprDriver.C.
References mesh.
bool isCellSet (const word & name) const
Test if name is a known cellSet.
Definition at line 667 of file fvExprDriver.C.
bool isFaceSet (const word & name) const
Test if name is a known faceSet.
Definition at line 677 of file fvExprDriver.C.
bool isPointSet (const word & name) const
Test if name is a known pointSet.
Definition at line 687 of file fvExprDriver.C.
void evaluateVariable (const word & varName, const expressions::exprString & expr) virtual
Evaluate the expression and save as the specified named variable.
Definition at line 374 of file fvExprDriver.C.
References iter.
void evaluateVariableRemote (string remote, const word & varName, const expressions::exprString & expr) virtual
Evaluate an expression on a remote and save as the specified named variable.
The fully qualified form of the remote is given as follows
*     type'name/region
*
If not specified, the default type is "patch", which means the following are equivalent
*     patch'name/region
*     name/region
*
If region is identical to the current region, it can be omitted:
*     patch'name
*     name   (default is patch)
*
Reimplemented from exprDriver.
Definition at line 422 of file fvExprDriver.C.
bool isVariable (const word & name, bool isPointVal = false, label expectSize = -1) const inline
Test existence of a local/global variable.
Definition at line 67 of file fvExprDriverI.H.
bool foundField (const word & name) const
Test if specified field can be found in memory or disk.
Definition at line 128 of file fvExprDriverTemplates.C.
Foam::word getTypeOfField (const word & fieldName) const
Read the IOobject for fieldName and return its headerClassName.
Empty if the field could not be found.
Definition at line 576 of file fvExprDriver.C.
bool readDict (const dictionary & dict) virtual
Read variables, tables etc.
Also usable for objects not constructed from a dictionary.
Reimplemented from exprDriver.
Reimplemented in parseDriver.
Definition at line 155 of file fvExprDriver.C.
Foam::Ostream & writeCommon (Ostream & os, bool debug = false) const
Write "variables", "storedVariables", "delayedVariables", "globalScopes" if they are present.
Definition at line 201 of file fvExprDriverIO.C.
void createWriterAndRead (const word & name)
Create a writer for this object.
Definition at line 255 of file fvExprDriverIO.C.
void tryWrite () const
Write data if apropriate Should enable exact restarts.
Definition at line 264 of file fvExprDriverIO.C.
References Foam::type(), and writer_().
Foam::tmp<GeomField> getOrReadField (const word & name, bool mandatory, bool getOldTime) inline
Definition at line 101 of file fvExprDriverI.H.
Foam::tmp<GeomField> getOrReadPointField (const word & name, bool mandatory, bool getOldTime) inline
Definition at line 120 of file fvExprDriverI.H.
Foam::tmp<GeomField> readAndRegister (const word & name, const Mesh & meshRef) inline
Definition at line 139 of file fvExprDriverI.H.
Foam::tmp<Foam::Field<Type> > getVariable (const word & name, label expectedSize, const bool mandatory) const
Definition at line 69 of file fvExprDriverTemplates.C.
Foam::tmp<GeomField> getOrReadFieldImpl (const word & name, const Mesh & meshRef, bool mandatory, bool getOldTime)
Definition at line 221 of file fvExprDriverTemplates.C.
Foam::autoPtr<T> getTopoSet (const fvMesh & mesh, const word & name, SetOrigin & origin) const
Definition at line 420 of file fvExprDriverTemplates.C.
Friends And Related Function Documentation
friend class exprDriverWriter friend
Definition at line 445 of file fvExprDriver.H.
The documentation for this class was generated from the following files:
src/finiteVolume/expressions/base/fvExprDriver.H
src/finiteVolume/expressions/base/fvExprDriver.C
src/finiteVolume/expressions/base/fvExprDriverFields.C
src/finiteVolume/expressions/base/fvExprDriverI.H
src/finiteVolume/expressions/base/fvExprDriverIO.C
src/finiteVolume/expressions/base/fvExprDriverNew.C
src/finiteVolume/expressions/base/fvExprDriverTemplates.C