OpenFOAM: treeBoundBox Class Reference
treeBoundBox Class Reference
Standard boundBox with extra functionality for use in octree.
Public Types
enum octantBit : direction { RIGHTHALF = 0x1, TOPHALF = 0x2, FRONTHALF = 0x4 }
Bits used for octant/point encoding.
enum faceId {
LEFT = 0, RIGHT = 1, BOTTOM = 2, TOP = 3,
BACK = 4, FRONT = 5
}
Face codes. Identical order and meaning as per hex cellmodel and boundBox, but have a different point ordering.
enum faceBit : direction {
NOFACE = 0, LEFTBIT = 0x1 << LEFT, RIGHTBIT = 0x1 << RIGHT, BOTTOMBIT = 0x1 << BOTTOM,
TOPBIT = 0x1 << TOP, BACKBIT = 0x1 << BACK, FRONTBIT = 0x1 << FRONT
}
Bits used for face encoding.
enum edgeId {
E01 = 0, E13 = 1, E23 = 2, E02 = 3,
E45 = 4, E57 = 5, E67 = 6, E46 = 7,
E04 = 8, E15 = 9, E37 = 10, E26 = 11
}
Edges codes.
Public Types inherited from boundBox
enum directionBit : direction { XDIR = 0x1, YDIR = 0x2, ZDIR = 0x4 }
Bits used for (x/y/z) direction encoding.
Public Member Functions
treeBoundBox ()
Construct without any points - an inverted bounding box.
treeBoundBox (const boundBox &bb)
Construct from a boundBox.
treeBoundBox (const point &pt)
Construct a bounding box containing a single initial point.
treeBoundBox (const point &min, const point &max)
Construct from components.
treeBoundBox (const UList< point > &points)
Construct as the bounding box of the given pointField.
treeBoundBox (const UList< point > &points, const labelUList &indices)
Construct as subset of points.
template<unsigned N>
treeBoundBox (const UList< point > &points, const FixedList< label, N > &indices)
Construct as subset of points.
treeBoundBox (Istream &is)
Construct from Istream.
scalar typDim () const
Typical dimension length,height,width.
tmp< pointField > points () const
Vertex coordinates. In octant coding.
point corner (const direction octant) const
Corner point of given octant.
treeBoundBox subBbox (const direction octant) const
Sub-box of given octant. Midpoint calculated.
treeBoundBox subBbox (const point &mid, const direction) const
Sub-box given by octant number. Midpoint provided.
direction subOctant (const point &pt) const
Returns octant number given point and the calculated midpoint.
direction subOctant (const point &pt, bool &onEdge) const
Returns octant number given point and the calculated midpoint.
void searchOrder (const point &pt, FixedList< direction, 8 > &octantOrder) const
Calculates optimal order to look for nearest to point.
bool intersects (const point &overallStart, const vector &overallVec, const point &start, const point &end, point &pt, direction &ptBits) const
Intersects segment; set point to intersection position and face,.
bool intersects (const point &start, const point &end, point &pt) const
Like above but does not return faces point is on.
bool contains (const vector &dir, const point &) const
Contains point (inside or on edge) and moving in direction.
direction faceBits (const point &pt) const
Code position of point on bounding box faces.
direction posBits (const point &pt) const
Position of point relative to bounding box.
void calcExtremities (const point &pt, point &nearest, point &furthest) const
Calculate nearest and furthest (to point) vertex coords of.
scalar maxDist (const point &pt) const
Returns distance point to furthest away corner.
label distanceCmp (const point &pt, const treeBoundBox &other) const
Compare distance to point with other bounding box.
treeBoundBox extend (Random &rndGen, const scalar s) const
Return slightly wider bounding box.
Public Member Functions inherited from boundBox
boundBox ()
Construct without any points - an inverted bounding box.
boundBox (const point &pt)
Construct a bounding box containing a single initial point.
boundBox (const point &min, const point &max)
Construct from components.
boundBox (const UList< point > &points, bool doReduce=true)
Construct as the bounding box of the given points.
boundBox (const tmp< pointField > &tpoints, bool doReduce=true)
Construct as the bounding box of the given temporary pointField.
boundBox (const UList< point > &points, const labelUList &indices, bool doReduce=true)
Construct bounding box as an indirect subset of the points.
template<unsigned N>
boundBox (const UList< point > &points, const FixedList< label, N > &indices, bool doReduce=true)
Construct bounding box as an indirect subset of the points.
boundBox (Istream &is)
Construct from Istream.
bool empty () const
Bounding box is inverted, contains no points.
bool valid () const
Bounding box is non-inverted.
const point & min () const
Minimum describing the bounding box.
const point & max () const
Maximum describing the bounding box.
point & min ()
Minimum describing the bounding box, non-const access.
point & max ()
Maximum describing the bounding box, non-const access.
point centre () const
The centre (midpoint) of the bounding box.
point midpoint () const
The midpoint (centre) of the bounding box. Identical to centre()
vector span () const
The bounding box span (from minimum to maximum)
scalar mag () const
The magnitude of the bounding box span.
scalar volume () const
The volume of the bound box.
scalar minDim () const
Smallest length/height/width dimension.
scalar maxDim () const
Largest length/height/width dimension.
scalar avgDim () const
Average length/height/width dimension.
label nDim () const
Count the number of positive, non-zero dimensions.
tmp< pointField > points () const
Corner points in an order corresponding to a 'hex' cell.
tmp< pointField > faceCentres () const
Face midpoints.
point faceCentre (const direction facei) const
Face centre of given face index.
void clear ()
Clear bounding box and make it an inverted box.
void add (const boundBox &bb)
Extend to include the second box.
void add (const point &pt)
Extend to include the point.
void add (const UList< point > &points)
Extend to include the points.
void add (const tmp< pointField > &tpoints)
Extend to include the points from the temporary point field.
template<unsigned N>
void add (const FixedList< point, N > &points)
Extend to include the points.
template<unsigned N>
void add (const UList< point > &points, const FixedList< label, N > &indices)
Extend to include a (subsetted) point field.
template<class IntContainer >
void add (const UList< point > &points, const IntContainer &indices)
Extend to include a (subsetted) point field.
void inflate (const scalar s)
Inflate box by factor*mag(span) in all dimensions.
void reduce ()
Parallel reduction of min/max values.
bool intersect (const boundBox &bb)
Intersection (union) with the second box.
bool intersects (const plane &pln) const
Does plane intersect this bounding box.
bool overlaps (const boundBox &bb) const
Overlaps/touches boundingBox?
bool overlaps (const point &centre, const scalar radiusSqr) const
Overlaps boundingSphere (centre + sqr(radius))?
bool contains (const point &pt) const
Contains point? (inside or on edge)
bool contains (const boundBox &bb) const
Fully contains other boundingBox?
bool containsInside (const point &pt) const
Contains point? (inside only)
bool contains (const UList< point > &points) const
Contains all points? (inside or on edge)
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
Contains all of the (subsetted) points? (inside or on edge)
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
Contains all of the (subsetted) points? (inside or on edge)
bool containsAny (const UList< point > &points) const
Contains any of the points? (inside or on edge)
template<unsigned N>
bool containsAny (const UList< point > &points, const FixedList< label, N > &indices) const
Contains any of the (subsetted) points? (inside or on edge)
template<class IntContainer >
bool containsAny (const UList< point > &points, const IntContainer &indices) const
Contains any of the (subsetted) points? (inside or on edge)
point nearest (const point &pt) const
Return the nearest point on the boundBox to the supplied point.
void operator+= (const boundBox &bb)
Extend box to include the second box, as per the add() method.
Static Public Member Functions
static direction subOctant (const point &mid, const point &pt)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const point &pt, bool &onEdge)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const vector &dir, const point &pt, bool &onEdge)
Returns octant number given intersection and midpoint.
Static Public Attributes
static const faceList faces
Face to point addressing.
static const edgeList edges
Edge to point addressing.
Static Public Attributes inherited from boundBox
static const boundBox greatBox
A large boundBox: min/max == -/+ ROOTVGREAT.
static const boundBox invertedBox
A large inverted boundBox: min/max == +/- ROOTVGREAT.
static const faceList faces
Faces to point addressing, as per a 'hex' cell.
static const FixedList< vector, 6 > faceNormals
The unit normal per face.
Friends
Istream & operator>> (Istream &is, treeBoundBox &bb)
Ostream & operator<< (Ostream &os, const treeBoundBox &bb)
Detailed Description
Standard boundBox with extra functionality for use in octree.
Numbering of corner points is according to octant numbering.
On the back plane (z=0):
    Y
    ^
    |
    +--------+
    |2      3|
    |        |
    |        |
    |        |
    |0      1|
    +--------+->X
For the front plane add 4 to the point labels.
Note
When a bounding box is created without any points, it creates an inverted bounding box. Points can be added later and the bounding box will grow to include them.
Source files
treeBoundBox.H
treeBoundBoxI.H
treeBoundBox.C
treeBoundBoxTemplates.C
Definition at line 83 of file treeBoundBox.H.
Member Enumeration Documentation
enum octantBit : direction
Bits used for octant/point encoding.
Every octant/corner point is the combination of three faces.
Enumerator
RIGHTHALF
TOPHALF
FRONTHALF
Definition at line 97 of file treeBoundBox.H.
enum faceId
Face codes. Identical order and meaning as per hex cellmodel and boundBox, but have a different point ordering.
Enumerator
LEFT
0: x-min, left
RIGHT
1: x-max, right
BOTTOM
2: y-min, bottom
TOP
3: y-max, top
BACK
4: z-min, back
FRONT
5: z-max, front
Definition at line 108 of file treeBoundBox.H.
enum faceBit : direction
Bits used for face encoding.
Enumerator
NOFACE
LEFTBIT
1: x-min, left
RIGHTBIT
2: x-max, right
BOTTOMBIT
4: y-min, bottom
TOPBIT
8: y-max, top
BACKBIT
16: z-min, back
FRONTBIT
32: z-max, front
Definition at line 121 of file treeBoundBox.H.
enum edgeId
Edges codes.
E01 = edge between 0 and 1.
Enumerator
E01
E13
E23
E02
E45
E57
E67
E46
E04
E15
E37
E26
Definition at line 137 of file treeBoundBox.H.
Constructor & Destructor Documentation
treeBoundBox () inline
Construct without any points - an inverted bounding box.
Definition at line 27 of file treeBoundBoxI.H.
treeBoundBox (const boundBox & bb) inline explicit
Construct from a boundBox.
Definition at line 33 of file treeBoundBoxI.H.
treeBoundBox (const point & pt) inline explicit
Construct a bounding box containing a single initial point.
Definition at line 39 of file treeBoundBoxI.H.
treeBoundBox (const point & min, const point & max) inline
Construct from components.
Definition at line 45 of file treeBoundBoxI.H.
treeBoundBox (const UList< point > & points) explicit
Construct as the bounding box of the given pointField.
Local processor domain only (no reduce as in boundBox)
Definition at line 55 of file treeBoundBox.C.
treeBoundBox (const UList< point > & points, const labelUList & indices)
Construct as subset of points.
Local processor domain only (no reduce as in boundBox)
Definition at line 68 of file treeBoundBox.C.
treeBoundBox (const UList< point > & points, const FixedList< label, N > & indices)
Construct as subset of points.
The indices could be from edge/triFace etc. Local processor domain only (no reduce as in boundBox)
Definition at line 28 of file treeBoundBoxTemplates.C.
References UList< T >::empty(), Foam::nl, and WarningInFunction.
treeBoundBox (Istream & is) inline
Construct from Istream.
Definition at line 51 of file treeBoundBoxI.H.
Member Function Documentation
Foam::scalar typDim () const inline
Typical dimension length,height,width.
Definition at line 59 of file treeBoundBoxI.H.
Foam::tmp< Foam::pointField > points () const
Vertex coordinates. In octant coding.
Definition at line 85 of file treeBoundBox.C.
Referenced by searchableBox::findNearest(), and AABBTree< Type >::writeOBJ().
Foam::point corner (const direction octant) const inline
Corner point of given octant.
Definition at line 65 of file treeBoundBoxI.H.
Foam::treeBoundBox subBbox (const direction octant) const
Sub-box of given octant. Midpoint calculated.
Definition at line 99 of file treeBoundBox.C.
Referenced by dynamicIndexedOctree< Type >::insertIndex(), dynamicIndexedOctree< Type >::print(), indexedOctree< Type >::print(), and dynamicIndexedOctree< Type >::removeIndex().
Foam::treeBoundBox subBbox (const point & mid, const direction octant) const
Sub-box given by octant number. Midpoint provided.
Definition at line 106 of file treeBoundBox.C.
Foam::direction subOctant (const point & pt) const inline
Returns octant number given point and the calculated midpoint.
Definition at line 77 of file treeBoundBoxI.H.
Referenced by dynamicIndexedOctree< Type >::findNode(), and indexedOctree< Type >::findNode().
Foam::direction subOctant (const point & mid, const point & pt) inline static
Returns octant number given point and midpoint.
Definition at line 86 of file treeBoundBoxI.H.
Foam::direction subOctant (const point & pt, bool & onEdge) const inline
Returns octant number given point and the calculated midpoint.
onEdge set if the point is on edge of subOctant
Definition at line 115 of file treeBoundBoxI.H.
Foam::direction subOctant (const point & mid, const point & pt, bool & onEdge) inline static
Returns octant number given point and midpoint.
onEdge set if the point is on edge of subOctant
Definition at line 127 of file treeBoundBoxI.H.
Foam::direction subOctant (const point & mid, const vector & dir, const point & pt, bool & onEdge) inline static
Returns octant number given intersection and midpoint.
onEdge set if the point is on edge of subOctant If onEdge, the direction vector determines which octant to use (acc. to which octant the point would be if it were moved along dir)
Definition at line 172 of file treeBoundBoxI.H.
References treeBoundBox::FRONTHALF, treeBoundBox::RIGHTHALF, treeBoundBox::TOPHALF, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
void searchOrder (const point & pt, FixedList< direction, 8 > & octantOrder) const inline
Calculates optimal order to look for nearest to point.
First will be the octant containing the point, second the octant with boundary nearest to the point etc.
Definition at line 228 of file treeBoundBoxI.H.
Referenced by dynamicIndexedOctree< Type >::findNearest(), and indexedOctree< Type >::findNearest().
bool intersects (const point & overallStart, const vector & overallVec, const point & start, const point & end, point & pt, direction & ptBits) const
Intersects segment; set point to intersection position and face,.
return true if intersection found. (pt argument used during calculation even if not intersecting). Calculates intersections from outside supplied vector (overallStart, overallVec). This is so when e.g. tracking through lots of consecutive boxes (typical octree) we're not accumulating truncation errors. Set to start, (end-start) if not used.
Definition at line 155 of file treeBoundBox.C.
Referenced by indexedOctree< Type >::findLine().
bool intersects (const point & start, const point & end, point & pt) const
Like above but does not return faces point is on.
Definition at line 302 of file treeBoundBox.C.
bool contains (const vector & dir, const point & pt) const
Contains point (inside or on edge) and moving in direction.
dir would cause it to go inside.
Definition at line 313 of file treeBoundBox.C.
Referenced by dynamicIndexedOctree< Type >::findNode().
Foam::direction faceBits (const point & pt) const
Code position of point on bounding box faces.
Definition at line 351 of file treeBoundBox.C.
Referenced by indexedOctree< Type >::findLine().
Foam::direction posBits (const point & pt) const
Position of point relative to bounding box.
Definition at line 384 of file treeBoundBox.C.
Referenced by indexedOctree< Type >::findLine().
void calcExtremities (const point & pt, point & nearest, point & furthest) const
Calculate nearest and furthest (to point) vertex coords of.
bounding box
Definition at line 419 of file treeBoundBox.C.
Foam::scalar maxDist (const point & pt) const
Returns distance point to furthest away corner.
Definition at line 466 of file treeBoundBox.C.
Foam::label distanceCmp (const point & pt, const treeBoundBox & other) const
Compare distance to point with other bounding box.
return: -1 : all vertices of my bounding box are nearer than any of other +1 : all vertices of my bounding box are further away than any of other 0 : none of the above.
Definition at line 476 of file treeBoundBox.C.
Foam::treeBoundBox extend (Random & rndGen, const scalar s) const inline
Return slightly wider bounding box.
Extends all dimensions with s*span*Random::sample01<scalar>() and guarantees in any direction s*mag(span) minimum width
Definition at line 318 of file treeBoundBoxI.H.
Referenced by meshSearch::boundaryTree(), and meshSearch::cellTree().
Friends And Related Function Documentation
Istream& operator>> (Istream & is, treeBoundBox & bb) friend
Ostream& operator<< (Ostream & os, const treeBoundBox & bb) friend
Member Data Documentation
const Foam::faceList faces static
Face to point addressing.
Definition at line 158 of file treeBoundBox.H.
Referenced by AABBTree< Type >::writeOBJ().
const Foam::edgeList edges static
Edge to point addressing.
Definition at line 163 of file treeBoundBox.H.
Referenced by distributedTriSurfaceMesh::distribute(), and AABBTree< Type >::writeOBJ().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/treeBoundBox/treeBoundBox.H
src/OpenFOAM/meshes/treeBoundBox/treeBoundBox.C
src/OpenFOAM/meshes/treeBoundBox/treeBoundBoxI.H
src/OpenFOAM/meshes/treeBoundBox/treeBoundBoxTemplates.C