OpenFOAM: ReactingHeterogeneousParcel< ParcelType >::constantProperties Class Reference
ReactingHeterogeneousParcel< ParcelType >::constantProperties Class Reference
Class to hold reacting particle constant properties.
Public Member Functions
constantProperties ()
Null constructor.
constantProperties (const constantProperties &cp)
Copy constructor.
constantProperties (const dictionary &parentDict)
Construct from dictionary.
scalar hRetentionCoeff () const
Return const access to the fraction of enthalpy retained by.
Detailed Description
template<class ParcelType>
class Foam::ReactingHeterogeneousParcel< ParcelType >::constantProperties
Class to hold reacting particle constant properties.
Definition at line 76 of file ReactingHeterogeneousParcel.H.
Constructor & Destructor Documentation
constantProperties () inline
Null constructor.
Definition at line 25 of file ReactingHeterogeneousParcelI.H.
constantProperties (const constantProperties & cp) inline
Copy constructor.
Definition at line 35 of file ReactingHeterogeneousParcelI.H.
constantProperties (const dictionary & parentDict) inline
Construct from dictionary.
Definition at line 47 of file ReactingHeterogeneousParcelI.H.
Member Function Documentation
Foam::scalar hRetentionCoeff () const inline
Return const access to the fraction of enthalpy retained by.
parcel due to surface reactions
Definition at line 136 of file ReactingHeterogeneousParcelI.H.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and value().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcelI.H