OpenFOAM: ISstream Class Reference
ISstream Class Reference
Generic input stream using standard (STL) streams.
Public Member Functions
ISstream (std::istream &is, const string &name, streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct as wrapper around std::istream.
virtual ~ISstream ()=default
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
ISstream & get (char &c)
Raw, low-level get character function.
int peek ()
Raw, low-level peek function.
ISstream & getLine (std::string &str, char delim= '\n')
Raw, low-level getline into a string function.
ISstream & putback (const char c)
Raw, low-level putback character function.
virtual Istream & read (token &t)
Return next token from stream.
virtual Istream & read (char &c)
Read a character.
virtual Istream & read (word &str)
Read a word.
virtual Istream & read (string &str)
Read a string (including enclosing double-quotes).
virtual Istream & read (label &val)
Read a label.
virtual Istream & read (floatScalar &val)
Read a floatScalar.
virtual Istream & read (doubleScalar &val)
Read a doubleScalar.
virtual Istream & read (char *buf, std::streamsize count)
Read binary block.
virtual Istream & readRaw (char *data, std::streamsize count)
Low-level raw binary read.
virtual bool beginRawRead ()
Start of low-level raw binary read.
virtual bool endRawRead ()
End of low-level raw binary read.
virtual void rewind ()
Rewind the stream so that it may be read again.
virtual ios_base::fmtflags flags (const ios_base::fmtflags flags)
Set stream flags.
virtual std::istream & stdStream ()
Access to underlying std::istream.
virtual const std::istream & stdStream () const
Const access to underlying std::istream.
virtual void print (Ostream &os) const
Print description of IOstream to Ostream.
Public Member Functions inherited from Istream
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct and set stream status.
virtual ~Istream ()=default
Destructor.
void putBack (const token &tok)
Put back token.
bool getBack (token &tok)
Get the put back token if there is one and return true.
bool peekBack (token &tok)
Peek at the put back token without removing it.
bool readBegin (const char *funcName)
Begin read of data chunk, starts with '('.
bool readEnd (const char *funcName)
End read of data chunk, ends with ')'.
char readBeginList (const char *funcName)
Begin read of list data, starts with '(' or '{'.
char readEndList (const char *funcName)
End read of list data, ends with ')' or '}'.
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (const IOstreamOption option)
Construct with specified stream option.
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct with format, version.
virtual ~IOstream ()=default
Destructor.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
unsigned labelByteSize () const
The label byte-size associated with the stream.
unsigned scalarByteSize () const
The scalar byte-size associated with the stream.
void setLabelByteSize (unsigned nbytes)
Set the label byte-size associated with the stream.
void setScalarByteSize (unsigned nbytes)
Set the scalar byte-size associated with the stream.
template<class T = label>
std::enable_if
< std::is_integral< T >::value,
bool >::type checkLabelSize () const
Check if the label byte-size associated with the stream is the same as the given type.
template<class T = scalar>
std::enable_if
< std::is_floating_point< T >
::value, bool >::type checkScalarSize () const
Check if the scalar byte-size associated with the stream is the same as the given type.
label lineNumber () const
Const access to the current stream line number.
label & lineNumber ()
Non-const access to the current stream line number.
label lineNumber (const label num)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
void print (Ostream &os, const int streamState) const
Print information about the stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from IOstreamOption
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
Enumeration for stream open/closed state.
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision.
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Static Public Attributes inherited from IOstream
static unsigned int precision_
Default precision.
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from IOstream
streamAccess openClosed_
ios_base::iostate ioState_
unsigned short labelByteSize_
The label byte-size (could also be stored as byte)
unsigned short scalarByteSize_
The scalar byte-size (could also be stored as byte)
label lineNumber_
The file line.
Static Protected Attributes inherited from IOstream
static fileName staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
Generic input stream using standard (STL) streams.
Source files
ISstream.H
ISstreamI.H
ISstream.C
Definition at line 50 of file ISstream.H.
Constructor & Destructor Documentation
ISstream (std::istream & is, const string & name, streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED) inline
Construct as wrapper around std::istream.
Definition at line 25 of file ISstreamI.H.
References IOstream::setGood(), and IOstream::setOpened().
virtual ~ISstream () virtual default
Destructor.
Member Function Documentation
virtual const fileName& name () const inline virtual
Return the name of the stream.
Useful for Fstream to return the filename
Reimplemented from IOstream.
Definition at line 126 of file ISstream.H.
Referenced by IStringStream::print(), ISstream::print(), and STARCDCore::readHeader().
virtual fileName& name () inline virtual
Return non-const access to the name of the stream.
Useful to alter the stream name
Reimplemented from IOstream.
Definition at line 136 of file ISstream.H.
std::ios_base::fmtflags flags () const virtual
Return flags of output stream.
Implements IOstream.
Reimplemented in dummyISstream.
Definition at line 859 of file ISstream.C.
Foam::ISstream & get (char & c) inline
Raw, low-level get character function.
Definition at line 51 of file ISstreamI.H.
Referenced by Foam::ReadHex(), and Foam::readToNewline().
int peek () inline
Raw, low-level peek function.
Does not remove the character from the stream. Returns the next character in the stream or EOF if the end of file is read.
Definition at line 65 of file ISstreamI.H.
Foam::ISstream & getLine (std::string & str, char delim = '\n') inline
Raw, low-level getline into a string function.
Definition at line 71 of file ISstreamI.H.
Referenced by STARCDsurfaceFormatCore::readInpCellTable().
Foam::ISstream & putback (const char c) inline
Raw, low-level putback character function.
Definition at line 85 of file ISstreamI.H.
Foam::Istream & read (token & t) virtual
Return next token from stream.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 151 of file ISstream.C.
Referenced by Foam::getToken(), STARCDMeshReader::readBoundary(), STARCDMeshReader::readCells(), and STARCDMeshReader::readPoints().
Foam::Istream & read (char & c) virtual
Read a character.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 391 of file ISstream.C.
Foam::Istream & read (word & str) virtual
Read a word.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 398 of file ISstream.C.
Foam::Istream & read (string & str) virtual
Read a string (including enclosing double-quotes).
Backslashes are retained, except when escaping double-quotes and an embedded newline character.
Implements Istream.
Reimplemented in dummyISstream, and ensightReadFile.
Definition at line 479 of file ISstream.C.
Foam::Istream & read (label & val) virtual
Read a label.
Implements Istream.
Reimplemented in dummyISstream, and ensightReadFile.
Definition at line 777 of file ISstream.C.
Foam::Istream & read (floatScalar & val) virtual
Read a floatScalar.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 785 of file ISstream.C.
References Foam::val.
Foam::Istream & read (doubleScalar & val) virtual
Read a doubleScalar.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 793 of file ISstream.C.
References Foam::val.
Foam::Istream & read (char * buf, std::streamsize count) virtual
Read binary block.
Implements Istream.
Reimplemented in dummyISstream, and ensightReadFile.
Definition at line 801 of file ISstream.C.
References Foam::val.
Foam::Istream & readRaw (char * data, std::streamsize count) virtual
Low-level raw binary read.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 811 of file ISstream.C.
bool beginRawRead () virtual
Start of low-level raw binary read.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 820 of file ISstream.C.
bool endRawRead () virtual
End of low-level raw binary read.
Implements Istream.
Reimplemented in dummyISstream.
Definition at line 836 of file ISstream.C.
void rewind () virtual
Rewind the stream so that it may be read again.
Implements Istream.
Reimplemented in UIListStream, IListStream, dummyISstream, and IFstream.
Definition at line 845 of file ISstream.C.
Referenced by IFstream::print(), and simpleObjectRegistry::setValues().
std::ios_base::fmtflags flags (const ios_base::fmtflags flags) virtual
Set stream flags.
Implements IOstream.
Reimplemented in dummyISstream.
Definition at line 865 of file ISstream.C.
virtual std::istream& stdStream () inline virtual
Access to underlying std::istream.
Reimplemented in IFstream.
Definition at line 250 of file ISstream.H.
Referenced by Foam::tellg().
virtual const std::istream& stdStream () const inline virtual
Const access to underlying std::istream.
Reimplemented in IFstream.
Definition at line 258 of file ISstream.H.
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Reimplemented in UIListStream, IListStream, IStringStream, and IFstream.
Definition at line 30 of file SstreamsPrint.C.
References ISstream::name().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Sstreams/ISstream.H
src/OpenFOAM/db/IOstreams/Sstreams/ISstream.C
src/OpenFOAM/db/IOstreams/Sstreams/ISstreamI.H
src/OpenFOAM/db/IOstreams/Sstreams/SstreamsPrint.C