OpenFOAM: PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData > Class Template Reference
PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData > Class Template Reference
Wave propagation of information along patch. Every iteration information goes through one layer of faces. Templated on information that is transferred.
Public Member Functions
PatchEdgeFaceWave (const polyMesh &mesh, const PrimitivePatchType &patch, const labelList &initialEdges, const List< Type > &initialEdgesInfo, UList< Type > &allEdgeInfo, UList< Type > &allFaceInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from patch, list of changed edges with the Type.
PatchEdgeFaceWave (const polyMesh &mesh, const PrimitivePatchType &patch, UList< Type > &allEdgeInfo, UList< Type > &allFaceInfo, TrackingData &td=dummyTrackData_)
Construct from patch. Use setEdgeInfo and iterate() to do.
UList< Type > & allEdgeInfo () const
Access allEdgeInfo.
UList< Type > & allFaceInfo () const
Access allFaceInfo.
const TrackingData & data () const
Additional data to be passed into container.
label nUnvisitedFaces () const
Number of unvisited faces, i.e. faces that were not (yet)
label nUnvisitedEdges () const
void setEdgeInfo (const labelList &changedEdges, const List< Type > &changedEdgesInfo)
Copy initial data into allEdgeInfo_.
label edgeToFace ()
Propagate from edge to face. Returns total number of faces.
label faceToEdge ()
Propagate from face to edge. Returns total number of edges.
label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
Static Public Member Functions
static scalar propagationTol ()
Access to tolerance.
static void setPropagationTol (const scalar tol)
Change tolerance.
Detailed Description
template<class PrimitivePatchType, class Type, class TrackingData = label>
class Foam::PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >
Wave propagation of information along patch. Every iteration information goes through one layer of faces. Templated on information that is transferred.
Source files
PatchEdgeFaceWave.H
PatchEdgeFaceWave.C
Definition at line 67 of file PatchEdgeFaceWave.H.
Constructor & Destructor Documentation
PatchEdgeFaceWave (const polyMesh & mesh, const PrimitivePatchType & patch, const labelList & initialEdges, const List< Type > & initialEdgesInfo, UList< Type > & allEdgeInfo, UList< Type > & allFaceInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from patch, list of changed edges with the Type.
for these edges. Gets work arrays to operate on, one of size number of patch edges, the other number of patch faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 286 of file PatchEdgeFaceWave.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, iter, PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::iterate(), PatchTools::matchEdges(), Foam::Pout, PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::setEdgeInfo(), and UList< T >::size().
PatchEdgeFaceWave (const polyMesh & mesh, const PrimitivePatchType & patch, UList< Type > & allEdgeInfo, UList< Type > & allFaceInfo, TrackingData & td = dummyTrackData_)
Construct from patch. Use setEdgeInfo and iterate() to do.
actual calculation
Definition at line 376 of file PatchEdgeFaceWave.C.
References PatchTools::matchEdges().
Member Function Documentation
static scalar propagationTol () inline static
Access to tolerance.
Definition at line 205 of file PatchEdgeFaceWave.H.
static void setPropagationTol (const scalar tol) inline static
Change tolerance.
Definition at line 213 of file PatchEdgeFaceWave.H.
UList<Type>& allEdgeInfo () const inline
Access allEdgeInfo.
Definition at line 261 of file PatchEdgeFaceWave.H.
UList<Type>& allFaceInfo () const inline
Access allFaceInfo.
Definition at line 269 of file PatchEdgeFaceWave.H.
const TrackingData& data () const inline
Additional data to be passed into container.
Definition at line 277 of file PatchEdgeFaceWave.H.
Foam::label nUnvisitedFaces () const
Number of unvisited faces, i.e. faces that were not (yet)
reached from walking across patch. This can happen from
not enough iterations done
a disconnected patch
a patch without walls in it
Definition at line 433 of file PatchEdgeFaceWave.C.
Foam::label nUnvisitedEdges () const
Definition at line 420 of file PatchEdgeFaceWave.C.
void setEdgeInfo (const labelList & changedEdges, const List< Type > & changedEdgesInfo)
Copy initial data into allEdgeInfo_.
Definition at line 448 of file PatchEdgeFaceWave.C.
References forAll, and List< T >::set().
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave().
Foam::label edgeToFace ()
Propagate from edge to face. Returns total number of faces.
(over all processors) changed.
Definition at line 550 of file PatchEdgeFaceWave.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::Pout, and Foam::returnReduce().
Foam::label faceToEdge ()
Propagate from face to edge. Returns total number of edges.
(over all processors) changed.
Definition at line 487 of file PatchEdgeFaceWave.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::nl, Foam::Pout, and Foam::returnReduce().
Foam::label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
number of iterations.
Definition at line 612 of file PatchEdgeFaceWave.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), iter, Foam::nl, and Foam::Pout.
Referenced by PatchEdgeFaceWave< PrimitivePatchType, Type, TrackingData >::PatchEdgeFaceWave().
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/PatchEdgeFaceWave.H
src/meshTools/algorithms/PatchEdgeFaceWave/PatchEdgeFaceWave.C