OpenFOAM: runTimeCondition Class Reference
runTimeCondition Class Reference abstract
Base class for run time conditions.
Public Member Functions
TypeName ("runTimeCondition")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, runTimeCondition, dictionary,(const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state),(name, obr, dict, state))
Declare runtime constructor selection table.
runTimeCondition (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
Constructor.
virtual ~runTimeCondition ()=default
Destructor.
virtual const word & name () const
Return the condition name.
virtual bool active () const
Return the active flag.
virtual label groupID () const
Return the group index.
virtual bool apply ()=0
Apply the condition.
virtual void write ()=0
Write.
Static Public Member Functions
static autoPtr< runTimeCondition > New (const word &conditionName, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state)
Selector.
Public Attributes
Switch log
Switch to send output to Info.
Protected Member Functions
dictionary & setConditionDict ()
Set the condition dictionary (create if necessary)
const dictionary & conditionDict () const
Return const access to the conditions dictionary.
dictionary & conditionDict ()
Return non-const access to the conditions dictionary.
Protected Attributes
word name_
Condition name.
const objectRegistry & obr_
Reference to the object registry.
stateFunctionObject & state_
State.
bool active_
On/off switch.
dictionary & conditionDict_
Reference to the condition dictionary.
label groupID_
Group index - if applied, all conditions in a group must be.
Detailed Description
Base class for run time conditions.
Source files
runTimeCondition.H
runTimeCondition.C
runTimeConditionNew.C
runTimeCondition.H
Definition at line 57 of file runTimeCondition.H.
Constructor & Destructor Documentation
runTimeCondition (const word & name, const objectRegistry & obr, const dictionary & dict, stateFunctionObject & state)
Constructor.
Definition at line 71 of file runTimeCondition.C.
virtual ~runTimeCondition () virtual default
Destructor.
Member Function Documentation
Foam::dictionary & setConditionDict () protected
Set the condition dictionary (create if necessary)
Definition at line 41 of file runTimeCondition.C.
const Foam::dictionary & conditionDict () const protected
Return const access to the conditions dictionary.
Definition at line 55 of file runTimeCondition.C.
Referenced by averageCondition::calc().
Foam::dictionary & conditionDict () protected
Return non-const access to the conditions dictionary.
Definition at line 62 of file runTimeCondition.C.
TypeName ("runTimeCondition")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , runTimeCondition , dictionary , (const word &name, const objectRegistry &obr, const dictionary &dict, stateFunctionObject &state) , (name, obr, dict, state))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::functionObjects::runTimeControls::runTimeCondition > New (const word & conditionName, const objectRegistry & obr, const dictionary & dict, stateFunctionObject & state) static
Selector.
Definition at line 28 of file runTimeConditionNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
const Foam::word & name () const virtual
Return the condition name.
Definition at line 91 of file runTimeCondition.C.
bool active () const virtual
Return the active flag.
Definition at line 97 of file runTimeCondition.C.
Foam::label groupID () const virtual
Return the group index.
Definition at line 104 of file runTimeCondition.C.
virtual bool apply () pure virtual
Apply the condition.
Implemented in averageCondition, equationInitialResidualCondition, minMaxCondition, maxDurationCondition, equationMaxIterCondition, and minTimeStepCondition.
virtual void write () pure virtual
Write.
Implemented in averageCondition, equationInitialResidualCondition, minMaxCondition, maxDurationCondition, equationMaxIterCondition, and minTimeStepCondition.
Member Data Documentation
word name_ protected
Condition name.
Definition at line 67 of file runTimeCondition.H.
const objectRegistry& obr_ protected
Reference to the object registry.
Definition at line 72 of file runTimeCondition.H.
Referenced by averageCondition::calc().
stateFunctionObject& state_ protected
State.
Definition at line 77 of file runTimeCondition.H.
Referenced by averageCondition::calc(), and minMaxCondition::setValue().
bool active_ protected
On/off switch.
Definition at line 82 of file runTimeCondition.H.
dictionary& conditionDict_ protected
Reference to the condition dictionary.
Definition at line 87 of file runTimeCondition.H.
label groupID_ protected
Group index - if applied, all conditions in a group must be.
satisfied before condition is met
Definition at line 94 of file runTimeCondition.H.
Switch log
Switch to send output to Info.
Definition at line 172 of file runTimeCondition.H.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/runTimeControl/runTimeCondition/runTimeCondition/runTimeCondition.H
src/functionObjects/utilities/runTimeControl/runTimeCondition/runTimeCondition/runTimeCondition.C
src/functionObjects/utilities/runTimeControl/runTimeCondition/runTimeCondition/runTimeConditionNew.C