OpenFOAM: patchWriter Class Reference
patchWriter Class Reference
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
Public Member Functions
patchWriter (const fvMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64, const bool useNearCellValue=false)
Construct from components (default format INLINE_BASE64)
patchWriter (const fvMesh &mesh, const labelList &patchIDs, const fileName &file, bool parallel=Pstream::parRun())
Construct from components (default format INLINE_BASE64), and open the file for writing.
patchWriter (const fvMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Construct from components (default format INLINE_BASE64), Construct from components and open the file for writing.
patchWriter (const fvMesh &mesh, const labelList &patchIDs, const vtk::outputOptions opts, const bool useNearCellValue, const fileName &file, bool parallel=Pstream::parRun())
Construct from components and open the file for writing.
virtual ~patchWriter ()=default
Destructor.
const labelList & patchIDs () const
The patch IDs.
virtual bool beginFile (std::string title="")
Write file header (non-collective)
virtual bool writeGeometry ()
Write patch topology.
virtual bool beginCellData (label nFields=0)
Begin CellData output section for specified number of fields.
virtual bool beginPointData (label nFields=0)
Begin PointData for specified number of fields.
void writePatchIDs ()
Write patch ids as CellData.
bool writeProcIDs ()
Write processor ids as CellData. This is no-op in serial.
bool writeNeighIDs ()
Write processor neighbour ids as CellData. This is no-op in serial.
template<class Type >
void writeUniform (const word &fieldName, const Type &val)
Write a uniform field of Cell (Face) or Point values.
template<class Type , template< class > class PatchField>
void write (const GeometricField< Type, PatchField, pointMesh > &field)
Write point field.
template<class Type , template< class > class PatchField>
void write (const GeometricField< Type, PatchField, volMesh > &field)
Write volume field.
template<class Type >
void write (const GeometricField< Type, fvPatchField, volMesh > &field, const PrimitivePatchInterpolation< primitivePatch > &pInterp)
Write volume field with point interpolation.
template<class Type >
void write (const GeometricField< Type, fvPatchField, volMesh > &field, const PrimitivePatchInterpolation< primitivePatch > *pInterp)
Write volume field with point interpolation.
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
Construct from components.
virtual ~fileWriter ()
Destructor.
vtk::fileTag contentType () const
The content type.
vtk::outputOptions opts () const
The output options in use.
word ext () const
File extension for current format type.
bool legacy () const
Commonly used query.
bool parallel () const
Parallel output requested?
const word & state () const
The output state in printable format.
const fileName & output () const
The current output file name.
bool open (const fileName &file, bool parallel=Pstream::parRun())
Open file for writing (creates parent directory).
void close ()
End the file contents and close the file after writing.
bool beginFieldData (label nFields=0)
Begin FieldData output section for specified number of fields.
label nCellData () const
Return the number of CellData written for the Piece thus far.
label nPointData () const
Return the number of PointData written for the Piece thus far.
bool endFieldData ()
Explicitly end FieldData output and switch to DECLARED state.
bool endCellData ()
Explicitly end CellData output and switch to PIECE state.
bool endPointData ()
Explicitly end PointData output and switch to PIECE state.
void writeTimeValue (scalar timeValue)
Write "TimeValue" FieldData (name as per Catalyst output)
Static Public Member Functions
static word ext (vtk::outputOptions opts)
File extension for given output type.
Additional Inherited Members
Protected Types inherited from fileWriter
enum outputState {
CLOSED = 0, OPENED, DECLARED, FIELD_DATA,
PIECE, CELL_DATA, POINT_DATA
}
Internal tracking of the output state.
Protected Member Functions inherited from fileWriter
std::ofstream & os ()
The backend ostream in use.
vtk::formatter & format ()
The VTK formatter in use.
bool isState (outputState test) const
True if the output state corresponds to the test state.
bool notState (outputState test) const
True if the output state does not correspond to the test state.
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
Write uniform field content.
bool enter_Piece ()
Trigger change state to Piece. Resets nCellData_, nPointData_.
bool endPiece ()
Explicitly end Piece output and switch to DECLARED state.
bool enter_CellData (label nEntries, label nFields)
Trigger change state to CellData.
bool enter_PointData (label nEntries, label nFields)
Trigger change state to PointData.
bool exit_File ()
Emit file footer (end data, end piece, end file)
fileWriter (const fileWriter &)=delete
No copy construct.
void operator= (const fileWriter &)=delete
No copy assignment.
Protected Attributes inherited from fileWriter
vtk::fileTag contentType_
The content type.
outputOptions opts_
The requested output options.
bool parallel_
Writing in parallel (via master)
outputState state_
The output state.
label nCellData_
The number of CellData written for the Piece thus far.
label nPointData_
The number of PointData written for the Piece thus far.
fileName outputFile_
The output file name.
autoPtr< vtk::formatter > format_
The VTK formatter in use (master process)
std::ofstream os_
The backend ostream in use (master process)
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Names for the output state (for messages, not for file output).
Detailed Description
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
The file output states are managed by the Foam::vtk::fileWriter class. FieldData (eg, TimeValue) must appear before any geometry pieces.
Note
Parallel output is combined into a single Piece without point merging, which is similar to using multi-piece data sets, but allows more convenient creation as a streaming process. In the future, the duplicate points at processor connections may be addressed using ghost points.
Source files
foamVtkPatchWriter.H
foamVtkPatchWriter.C
foamVtkPatchWriterTemplates.C
Definition at line 62 of file foamVtkPatchWriter.H.
Constructor & Destructor Documentation
patchWriter (const fvMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64, const bool useNearCellValue = false)
Construct from components (default format INLINE_BASE64)
Parameters
useNearCellValue to use cell instead of patch values
Definition at line 384 of file foamVtkPatchWriter.C.
patchWriter (const fvMesh & mesh, const labelList & patchIDs, const fileName & file, bool parallel = Pstream::parRun())
Construct from components (default format INLINE_BASE64), and open the file for writing.
The file name is with/without an extension.
Definition at line 407 of file foamVtkPatchWriter.C.
patchWriter (const fvMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Construct from components (default format INLINE_BASE64), Construct from components and open the file for writing.
The file name is with/without an extension.
Definition at line 421 of file foamVtkPatchWriter.C.
patchWriter (const fvMesh & mesh, const labelList & patchIDs, const vtk::outputOptions opts, const bool useNearCellValue, const fileName & file, bool parallel = Pstream::parRun())
Construct from components and open the file for writing.
The file name is with/without an extension.
Parameters
useNearCellValue to use cell instead of patch values
Definition at line 436 of file foamVtkPatchWriter.C.
virtual ~patchWriter () virtual default
Destructor.
Member Function Documentation
static word ext (vtk::outputOptions opts) inline static
File extension for given output type.
Definition at line 227 of file foamVtkPatchWriter.H.
const labelList& patchIDs () const inline
The patch IDs.
Definition at line 235 of file foamVtkPatchWriter.H.
bool beginFile (std::string title = "") virtual
Write file header (non-collective)
Note
Expected calling states: (OPENED).
Reimplemented from fileWriter.
Definition at line 453 of file foamVtkPatchWriter.C.
bool writeGeometry () virtual
Write patch topology.
Also writes the file header if not previously written.
Note
Must be called prior to writing CellData or PointData
Implements fileWriter.
Definition at line 503 of file foamVtkPatchWriter.C.
bool beginCellData (label nFields = 0) virtual
Begin CellData output section for specified number of fields.
Must be called prior to writing any cell data fields.
Parameters
nFields is for legacy format only. When nFields=0, this a no-op for legacy format.
Note
Expected calling states: (PIECE | POINT_DATA).
Returns
True if the state changed
Implements fileWriter.
Definition at line 529 of file foamVtkPatchWriter.C.
bool beginPointData (label nFields = 0) virtual
Begin PointData for specified number of fields.
Must be called prior to writing any point data fields.
Parameters
nFields is for legacy format only. When nFields=0, this a no-op for legacy format.
Note
Expected calling states: (PIECE | CELL_DATA).
Returns
True if the state changed
Implements fileWriter.
Definition at line 535 of file foamVtkPatchWriter.C.
void writePatchIDs ()
Write patch ids as CellData.
Must be called within the CELL_DATA state.
Definition at line 541 of file foamVtkPatchWriter.C.
bool writeProcIDs ()
Write processor ids as CellData. This is no-op in serial.
Must be called within the CELL_DATA state.
Definition at line 652 of file foamVtkPatchWriter.C.
References format().
bool writeNeighIDs ()
Write processor neighbour ids as CellData. This is no-op in serial.
Must be called within the CELL_DATA state.
Definition at line 736 of file foamVtkPatchWriter.C.
void writeUniform (const word & fieldName, const Type & val)
Write a uniform field of Cell (Face) or Point values.
Definition at line 28 of file foamVtkPatchWriterTemplates.C.
References Foam::vtk::CELL_DATA, Foam::endl(), fileWriter::isState(), fileWriter::nCellData_, Foam::nl, fileWriter::nPointData_, Foam::vtk::POINT_DATA, fileWriter::state_, fileWriter::stateNames, Foam::val, and WarningInFunction.
void write (const GeometricField< Type, PatchField, pointMesh > & field)
Write point field.
Definition at line 55 of file foamVtkPatchWriterTemplates.C.
void write (const GeometricField< Type, PatchField, volMesh > & field)
Write volume field.
Definition at line 166 of file foamVtkPatchWriterTemplates.C.
void write (const GeometricField< Type, fvPatchField, volMesh > & field, const PrimitivePatchInterpolation< primitivePatch > & pInterp)
Write volume field with point interpolation.
Definition at line 290 of file foamVtkPatchWriterTemplates.C.
void write (const GeometricField< Type, fvPatchField, volMesh > & field, const PrimitivePatchInterpolation< primitivePatch > * pInterp)
Write volume field with point interpolation.
The documentation for this class was generated from the following files:
src/conversion/vtk/output/foamVtkPatchWriter.H
src/conversion/vtk/output/foamVtkPatchWriter.C
src/conversion/vtk/output/foamVtkPatchWriterTemplates.C