OpenFOAM: fileOperation Class Reference
fileOperation Class Reference abstract
An encapsulation of filesystem-related operations.
Public Types
enum pathType {
NOTFOUND, ABSOLUTE, OBJECT, WRITEOBJECT,
PROCUNCOLLATED, PROCBASEOBJECT, PROCOBJECT, PARENTOBJECT,
FINDINSTANCE, PROCUNCOLLATEDINSTANCE, PROCBASEINSTANCE, PROCINSTANCE
}
Enumeration for the location of an IOobject.
typedef Tuple2< fileName,
Tuple2< pathType, label > > dirIndex
typedef List< dirIndex > dirIndexList
Public Member Functions
TypeName ("fileOperation")
Runtime type information.
fileOperation (const label comm)
Construct from communicator.
declareRunTimeSelectionTable (autoPtr, fileOperation, word,(bool verbose),(verbose))
virtual ~fileOperation ()=default
Destructor.
virtual bool mkDir (const fileName &, mode_t=0777) const =0
Make directory.
virtual bool chMod (const fileName &, const mode_t) const =0
Set the file mode.
virtual mode_t mode (const fileName &, const bool followLink=true) const =0
Return the file mode.
virtual fileName::Type type (const fileName &, const bool followLink=true) const =0
Return the file type: DIRECTORY, FILE or LINK.
virtual bool exists (const fileName &, const bool checkGzip=true, const bool followLink=true) const =0
Does the name exist (as DIRECTORY or FILE) in the file system?
virtual bool isDir (const fileName &, const bool followLink=true) const =0
Does the name exist as a DIRECTORY in the file system?
virtual bool isFile (const fileName &, const bool checkGzip=true, const bool followLink=true) const =0
Does the name exist as a FILE in the file system?
virtual off_t fileSize (const fileName &, const bool followLink=true) const =0
Return size of file.
virtual time_t lastModified (const fileName &, const bool followLink=true) const =0
Return time of last file modification.
virtual double highResLastModified (const fileName &, const bool followLink=true) const =0
Return time of last file modification.
virtual fileNameList readDir (const fileName &, const fileName::Type=fileName::FILE, const bool filtergz=true, const bool followLink=true) const =0
Read a directory and return the entries as a string list.
virtual bool cp (const fileName &src, const fileName &dst, const bool followLink=true) const =0
Copy, recursively if necessary, the source to the destination.
virtual bool ln (const fileName &src, const fileName &dst) const =0
Create a softlink. dst should not exist. Returns true if.
virtual bool mv (const fileName &src, const fileName &dst, const bool followLink=false) const =0
Rename src to dst.
virtual bool mvBak (const fileName &, const std::string &ext="bak") const =0
Rename to a corresponding backup file.
virtual bool rm (const fileName &) const =0
Remove a file, returning true if successful otherwise false.
virtual bool rmDir (const fileName &dir, const bool silent=false) const =0
Remove a directory and its contents.
virtual fileName objectPath (const IOobject &io, const word &typeName) const
Generate disk file name for object. Opposite of filePath.
virtual fileName filePath (const bool checkGlobal, const IOobject &, const word &typeName, const bool search=true) const =0
Search for an object. checkGlobal : also check undecomposed case.
virtual fileName dirPath (const bool checkGlobal, const IOobject &io, const bool search=true) const =0
Search for a directory. checkGlobal : also check undecomposed.
virtual fileNameList readObjects (const objectRegistry &db, const fileName &instance, const fileName &local, word &newInstance) const
Search directory for objects. Used in IOobjectList.
virtual bool readHeader (IOobject &, const fileName &, const word &typeName) const =0
Read object header from supplied file.
virtual autoPtr< ISstream > readStream (regIOobject &, const fileName &, const word &typeName, const bool valid=true) const =0
Reads header for regIOobject and returns an ISstream.
virtual bool read (regIOobject &, const bool masterOnly, const IOstream::streamFormat format, const word &typeName) const =0
Top-level read.
virtual bool writeObject (const regIOobject &, IOstream::streamFormat format=IOstream::ASCII, IOstream::versionNumber version=IOstream::currentVersion, IOstream::compressionType compression=IOstream::UNCOMPRESSED, const bool valid=true) const
Writes a regIOobject (so header, contents and divider).
virtual fileName filePath (const fileName &) const
Search for a file or directory. Use IOobject version in.
virtual autoPtr< ISstream > NewIFstream (const fileName &) const =0
Generate an ISstream that reads a file.
virtual autoPtr< Ostream > NewOFstream (const fileName &pathname, IOstream::streamFormat format=IOstream::ASCII, IOstream::versionNumber version=IOstream::currentVersion, IOstream::compressionType compression=IOstream::UNCOMPRESSED, const bool valid=true) const =0
Generate an Ostream that writes a file.
virtual label addWatch (const fileName &) const
Add watching of a file. Returns handle.
virtual bool removeWatch (const label) const
Remove watch on a file (using handle)
virtual label findWatch (const labelList &watchIndices, const fileName &) const
Find index (or -1) of file in list of handles.
virtual void addWatches (regIOobject &, const fileNameList &) const
Helper: add watches for list of regIOobjects.
virtual fileName getFile (const label) const
Get name of file being watched (using handle)
virtual void updateStates (const bool masterOnly, const bool syncPar) const
Update state of all files.
virtual fileMonitor::fileState getState (const label) const
Get current state of file (using handle)
virtual void setUnmodified (const label) const
Set current state of file (using handle) to unmodified.
virtual word processorsDir (const IOobject &io) const
Actual name of processors dir (for use in mode PROCOBJECT,.
virtual word processorsDir (const fileName &) const
Actual name of processors dir (for use in mode PROCOBJECT,.
virtual void setNProcs (const label nProcs)
Set number of processor directories/results. Only used in.
virtual label nProcs (const fileName &dir, const fileName &local="") const
Get number of processor directories/results. Used for e.g.
virtual instantList findTimes (const fileName &, const word &) const
Get sorted list of times.
virtual IOobject findInstance (const IOobject &io, const scalar startValue, const word &stopInstance) const
Find instance where IOobject is. Fails if cannot be found.
virtual void setTime (const Time &) const
Callback for time change.
virtual void flush () const
Forcibly wait until all output done. Flush any cached data.
fileName processorsCasePath (const IOobject &, const word &procDir) const
Generate path (like io.path) from root+casename with any.
fileName processorsPath (const IOobject &, const word &instance, const word &procDir) const
Generate path (like io.path) with provided instance and any.
fileName processorsPath (const fileName &, const word &procDir) const
Operating on fileName: replace processorXXX with procDir.
Static Public Member Functions
static autoPtr< fileOperation > New (const word &handlerType, bool verbose=false)
Select fileHandler-type.
static label splitProcessorPath (const fileName &, fileName &path, fileName &procDir, fileName &local, label &groupStart, label &groupSize, label &nProcs)
Split fileName into part before 'processor' and part after.
static label detectProcessorPath (const fileName &)
Detect processor number from '/aa/bb/processorDDD/cc'.
Static Public Attributes
static const Enum< pathType > pathTypeNames_
static word processorsBaseDir = "processors"
Return the processors directory name (usually "processors")
static word defaultFileHandler
Default fileHandler.
static autoPtr< fileOperation > fileHandlerPtr_
Static fileOperation.
Protected Member Functions
fileMonitor & monitor () const
tmpNrc< dirIndexList > lookupAndCacheProcessorsPath (const fileName &, const bool syncPar) const
Lookup name of processorsDDD using cache. Return empty fileName.
virtual tmpNrc< dirIndexList > lookupProcessorsPath (const fileName &) const
Lookup name of processorsDDD using cache. Return empty fileName.
bool exists (IOobject &io) const
Does ioobject exist. Is either a directory (empty name()) or.
Static Protected Member Functions
static instantList sortTimes (const fileNameList &, const word &)
Sort directory entries according to time value.
static void mergeTimes (const instantList &extraTimes, const word &constantName, instantList &times)
Merge two times.
static bool isFileOrDir (const bool isFile, const fileName &)
Helper: check for file (isFile) or directory (!isFile)
Protected Attributes
const label comm_
Communicator to use.
HashTable< dirIndexList > procsDirs_
Detected processors directories.
autoPtr< fileMonitor > monitorPtr_
file-change monitor for all registered files
Detailed Description
An encapsulation of filesystem-related operations.
Definition at line 70 of file fileOperation.H.
Member Typedef Documentation
typedef Tuple2<fileName, Tuple2<pathType, label> > dirIndex
Definition at line 96 of file fileOperation.H.
typedef List<dirIndex> dirIndexList
Definition at line 97 of file fileOperation.H.
Member Enumeration Documentation
enum pathType
Enumeration for the location of an IOobject.
Enumerator
NOTFOUND
ABSOLUTE
OBJECT
WRITEOBJECT
PROCUNCOLLATED
PROCBASEOBJECT
PROCOBJECT
PARENTOBJECT
FINDINSTANCE
PROCUNCOLLATEDINSTANCE
PROCBASEINSTANCE
PROCINSTANCE
Definition at line 77 of file fileOperation.H.
Constructor & Destructor Documentation
fileOperation (const label comm) explicit
Construct from communicator.
Definition at line 414 of file fileOperation.C.
virtual ~fileOperation () virtual default
Destructor.
Member Function Documentation
Foam::fileMonitor & monitor () const protected
Definition at line 77 of file fileOperation.C.
Foam::instantList sortTimes (const fileNameList & dirEntries, const word & constantName) static protected
Sort directory entries according to time value.
Definition at line 95 of file fileOperation.C.
void mergeTimes (const instantList & extraTimes, const word & constantName, instantList & times) static protected
Merge two times.
Definition at line 150 of file fileOperation.C.
bool isFileOrDir (const bool isFile, const fileName & f) static protected
Helper: check for file (isFile) or directory (!isFile)
Definition at line 223 of file fileOperation.C.
Foam::tmpNrc< Foam::fileOperation::dirIndexList > lookupAndCacheProcessorsPath (const fileName & fName, const bool syncPar) const protected
Lookup name of processorsDDD using cache. Return empty fileName.
if not found.
Definition at line 231 of file fileOperation.C.
References Foam::isDir(), and Foam::isFile().
Foam::tmpNrc< Foam::fileOperation::dirIndexList > lookupProcessorsPath (const fileName & fName) const protected virtual
Lookup name of processorsDDD using cache. Return empty fileName.
if not found. To be called on all processors
Reimplemented in uncollatedFileOperation.
Definition at line 362 of file fileOperation.C.
bool exists (IOobject & io) const protected
Does ioobject exist. Is either a directory (empty name()) or.
a file
Definition at line 369 of file fileOperation.C.
TypeName ("fileOperation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , fileOperation , word , (bool verbose) , (verbose))
Foam::autoPtr< Foam::fileOperation > New (const word & handlerType, bool verbose = false) static
Select fileHandler-type.
Definition at line 421 of file fileOperation.C.
virtual bool mkDir (const fileName & , mode_t = 0777) const pure virtual
Make directory.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool chMod (const fileName & , const mode_t) const pure virtual
Set the file mode.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual mode_t mode (const fileName & , const bool followLink = true) const pure virtual
Return the file mode.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual fileName::Type type (const fileName & , const bool followLink = true) const pure virtual
Return the file type: DIRECTORY, FILE or LINK.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool exists (const fileName & , const bool checkGzip = true, const bool followLink = true) const pure virtual
Does the name exist (as DIRECTORY or FILE) in the file system?
Optionally enable/disable check for gzip file.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool isDir (const fileName & , const bool followLink = true) const pure virtual
Does the name exist as a DIRECTORY in the file system?
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool isFile (const fileName & , const bool checkGzip = true, const bool followLink = true) const pure virtual
Does the name exist as a FILE in the file system?
Optionally enable/disable check for gzip file.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual off_t fileSize (const fileName & , const bool followLink = true) const pure virtual
Return size of file.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual time_t lastModified (const fileName & , const bool followLink = true) const pure virtual
Return time of last file modification.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual double highResLastModified (const fileName & , const bool followLink = true) const pure virtual
Return time of last file modification.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual fileNameList readDir (const fileName & , const fileName::Type = fileName::FILE, const bool filtergz = true, const bool followLink = true) const pure virtual
Read a directory and return the entries as a string list.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool cp (const fileName & src, const fileName & dst, const bool followLink = true) const pure virtual
Copy, recursively if necessary, the source to the destination.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool ln (const fileName & src, const fileName & dst) const pure virtual
Create a softlink. dst should not exist. Returns true if.
successful.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool mv (const fileName & src, const fileName & dst, const bool followLink = false) const pure virtual
Rename src to dst.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool mvBak (const fileName & , const std::string & ext = "bak") const pure virtual
Rename to a corresponding backup file.
If the backup file already exists, attempt with "01" .. "99" suffix
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool rm (const fileName &) const pure virtual
Remove a file, returning true if successful otherwise false.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool rmDir (const fileName & dir, const bool silent = false) const pure virtual
Remove a directory and its contents.
Parameters
silent do not report missing directory
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
Foam::fileName objectPath (const IOobject & io, const word & typeName) const virtual
Generate disk file name for object. Opposite of filePath.
Optional wanted typeName.
Reimplemented in collatedFileOperation.
Definition at line 448 of file fileOperation.C.
virtual fileName filePath (const bool checkGlobal, const IOobject & , const word & typeName, const bool search = true) const pure virtual
Search for an object. checkGlobal : also check undecomposed case.
Optional wanted typeName.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
Referenced by IOobject::globalFilePath(), and IOobject::setBad().
virtual fileName dirPath (const bool checkGlobal, const IOobject & io, const bool search = true) const pure virtual
Search for a directory. checkGlobal : also check undecomposed.
case
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
Foam::fileNameList readObjects (const objectRegistry & db, const fileName & instance, const fileName & local, word & newInstance) const virtual
Search directory for objects. Used in IOobjectList.
Reimplemented in masterUncollatedFileOperation, and uncollatedFileOperation.
Definition at line 875 of file fileOperation.C.
virtual bool readHeader (IOobject & , const fileName & , const word & typeName) const pure virtual
Read object header from supplied file.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
Referenced by IOobject::typeHeaderOk().
virtual autoPtr<ISstream> readStream (regIOobject & , const fileName & , const word & typeName, const bool valid = true) const pure virtual
Reads header for regIOobject and returns an ISstream.
to read the contents.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual bool read (regIOobject & , const bool masterOnly, const IOstream::streamFormat format, const word & typeName) const pure virtual
Top-level read.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
Referenced by regIOobject::readHeaderOk().
bool writeObject (const regIOobject & io, IOstream::streamFormat format = IOstream::ASCII, IOstream::versionNumber version = IOstream::currentVersion, IOstream::compressionType compression = IOstream::UNCOMPRESSED, const bool valid = true) const virtual
Writes a regIOobject (so header, contents and divider).
Returns success state. Default action is to write to the objectPath using writeData. If !valid the file does not need to be written (this is used e.g. to suppress empty local lagrangian data)
Reimplemented in masterUncollatedFileOperation, and collatedFileOperation.
Definition at line 458 of file fileOperation.C.
References IOobject::objectPath().
Referenced by regIOobject::writeObject().
Foam::fileName filePath (const fileName & fName) const virtual
Search for a file or directory. Use IOobject version in.
preference
Definition at line 513 of file fileOperation.C.
virtual autoPtr<ISstream> NewIFstream (const fileName &) const pure virtual
Generate an ISstream that reads a file.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
virtual autoPtr<Ostream> NewOFstream (const fileName & pathname, IOstream::streamFormat format = IOstream::ASCII, IOstream::versionNumber version = IOstream::currentVersion, IOstream::compressionType compression = IOstream::UNCOMPRESSED, const bool valid = true) const pure virtual
Generate an Ostream that writes a file.
Implemented in masterUncollatedFileOperation, and uncollatedFileOperation.
Foam::label addWatch (const fileName & fName) const virtual
Add watching of a file. Returns handle.
Reimplemented in masterUncollatedFileOperation.
Definition at line 572 of file fileOperation.C.
References Foam::endl(), and Foam::Pout.
bool removeWatch (const label watchIndex) const virtual
Remove watch on a file (using handle)
Reimplemented in masterUncollatedFileOperation.
Definition at line 578 of file fileOperation.C.
Foam::label findWatch (const labelList & watchIndices, const fileName & fName) const virtual
Find index (or -1) of file in list of handles.
Reimplemented in masterUncollatedFileOperation.
Definition at line 585 of file fileOperation.C.
void addWatches (regIOobject & rio, const fileNameList & files) const virtual
Helper: add watches for list of regIOobjects.
Reimplemented in masterUncollatedFileOperation.
Definition at line 602 of file fileOperation.C.
Foam::fileName getFile (const label watchIndex) const virtual
Get name of file being watched (using handle)
Reimplemented in masterUncollatedFileOperation.
Definition at line 638 of file fileOperation.C.
void updateStates (const bool masterOnly, const bool syncPar) const virtual
Update state of all files.
Reimplemented in masterUncollatedFileOperation.
Definition at line 645 of file fileOperation.C.
Foam::fileMonitor::fileState getState (const label watchFd) const virtual
Get current state of file (using handle)
Reimplemented in masterUncollatedFileOperation.
Definition at line 655 of file fileOperation.C.
References UPstream::parRun().
void setUnmodified (const label watchFd) const virtual
Set current state of file (using handle) to unmodified.
Reimplemented in masterUncollatedFileOperation.
Definition at line 663 of file fileOperation.C.
Referenced by regIOobject::writeObject().
virtual word processorsDir (const IOobject & io) const inline virtual
Actual name of processors dir (for use in mode PROCOBJECT,.
PROCINSTANCE)
Reimplemented in collatedFileOperation.
Definition at line 595 of file fileOperation.H.
virtual word processorsDir (const fileName &) const inline virtual
Actual name of processors dir (for use in mode PROCOBJECT,.
PROCINSTANCE)
Reimplemented in collatedFileOperation.
Definition at line 605 of file fileOperation.H.
void setNProcs (const label nProcs) virtual
Set number of processor directories/results. Only used in.
decomposePar
Reimplemented in collatedFileOperation.
Definition at line 914 of file fileOperation.C.
Foam::label nProcs (const fileName & dir, const fileName & local = "") const virtual
Get number of processor directories/results. Used for e.g.
reconstructPar, argList checking
Definition at line 919 of file fileOperation.C.
Foam::instantList findTimes (const fileName & directory, const word & constantName) const virtual
Get sorted list of times.
Reimplemented in masterUncollatedFileOperation.
Definition at line 670 of file fileOperation.C.
Referenced by TimePaths::times().
Foam::IOobject findInstance (const IOobject & io, const scalar startValue, const word & stopInstance) const virtual
Find instance where IOobject is. Fails if cannot be found.
and readOpt() is MUST_READ/MUST_READ_IF_MODIFIED. Otherwise returns stopInstance.
Reimplemented in masterUncollatedFileOperation.
Definition at line 728 of file fileOperation.C.
virtual void setTime (const Time &) const inline virtual
Callback for time change.
Reimplemented in masterUncollatedFileOperation.
Definition at line 649 of file fileOperation.H.
void flush () const virtual
Forcibly wait until all output done. Flush any cached data.
Reimplemented in masterUncollatedFileOperation, and collatedFileOperation.
Definition at line 981 of file fileOperation.C.
Foam::fileName processorsCasePath (const IOobject & io, const word & procDir) const
Generate path (like io.path) from root+casename with any.
'processorXXX' replaced by procDir (usually 'processsors')
Definition at line 993 of file fileOperation.C.
Foam::fileName processorsPath (const IOobject & io, const word & instance, const word & procDir) const
Generate path (like io.path) with provided instance and any.
'processorXXX' replaced by procDir (usually 'processsors')
Definition at line 1003 of file fileOperation.C.
Foam::fileName processorsPath (const fileName & dir, const word & procDir) const
Operating on fileName: replace processorXXX with procDir.
Definition at line 1018 of file fileOperation.C.
Foam::label splitProcessorPath (const fileName & objectPath, fileName & path, fileName & procDir, fileName & local, label & groupStart, label & groupSize, label & nProcs) static
Split fileName into part before 'processor' and part after.
Returns -1 or processor number and optionally number of processors. Use with care.
path/"processor"+Foam::name(proci)/local reconstructs input
path/"processors"+Foam::name(nProcs)/local reconstructs collated processors equivalence
Definition at line 1043 of file fileOperation.C.
Foam::label detectProcessorPath (const fileName & fName) static
Detect processor number from '/aa/bb/processorDDD/cc'.
Definition at line 1164 of file fileOperation.C.
Member Data Documentation
const Foam::Enum< Foam::fileOperation::pathType > pathTypeNames_ static
Definition at line 94 of file fileOperation.H.
const label comm_ protected
Communicator to use.
Definition at line 107 of file fileOperation.H.
HashTable<dirIndexList> procsDirs_ mutable protected
Detected processors directories.
Definition at line 112 of file fileOperation.H.
autoPtr<fileMonitor> monitorPtr_ mutable protected
file-change monitor for all registered files
Definition at line 117 of file fileOperation.H.
Foam::word processorsBaseDir = "processors" static
Return the processors directory name (usually "processors")
Definition at line 180 of file fileOperation.H.
word defaultFileHandler static
Default fileHandler.
Definition at line 185 of file fileOperation.H.
autoPtr< fileOperation > fileHandlerPtr_ static
Static fileOperation.
Definition at line 199 of file fileOperation.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/fileOperations/fileOperation/fileOperation.H
src/OpenFOAM/global/fileOperations/fileOperation/fileOperation.C