OpenFOAM: icoPolynomial< Specie, PolySize > Class Template Reference
icoPolynomial< Specie, PolySize > Class Template Reference
Equation of state
Incompressible, polynomial form of equation of state, using a polynomial function for density.
Public Member Functions
icoPolynomial (const Specie &sp, const Polynomial< PolySize > &rhoPoly)
Construct from components.
icoPolynomial (const dictionary &dict)
Construct from dictionary.
icoPolynomial (const word &name, const icoPolynomial &)
Construct as named copy.
autoPtr< icoPolynomial > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar H (const scalar p, const scalar T) const
Return enthalpy departure [J/kg].
scalar Cp (scalar p, scalar T) const
Return Cp departure [J/(kg K].
scalar E (const scalar p, const scalar T) const
Return internal energy departure [J/kg].
scalar Cv (scalar p, scalar T) const
Return Cv departure [J/(kg K].
scalar S (const scalar p, const scalar T) const
Return entropy [J/(kg K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar CpMCv (scalar p, scalar T) const
Return (Cp - Cv) [J/(kg K].
void write (Ostream &os) const
Write to Ostream.
void operator= (const icoPolynomial &)
void operator+= (const icoPolynomial &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< icoPolynomial > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = true
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
icoPolynomial operator+ (const icoPolynomial &, const icoPolynomial &)
icoPolynomial operator* (const scalar s, const icoPolynomial &)
icoPolynomial operator== (const icoPolynomial &, const icoPolynomial &)
Ostream & operator (Ostream &, const icoPolynomial &)
Detailed Description
template<class Specie, int PolySize>
class Foam::icoPolynomial< Specie, PolySize >
Incompressible, polynomial form of equation of state, using a polynomial function for density.
Usage
Property Description
rhoCoeffs<8> Density polynomial coefficients
Example of the specification of the equation of state:
    equationOfState
    {
        rhoCoeffs<8>    ( 1000 -0.05 0.003 0 0 0 0 0 );
    }
The polynomial expression is evaluated as so:
Note
Input in [kg/m3], but internally uses [kg/m3/kmol].
Source files
icoPolynomial.H
icoPolynomialI.H
icoPolynomial.C
See Also
Foam::Polynomial
Definition at line 83 of file icoPolynomial.H.
Constructor & Destructor Documentation
icoPolynomial (const Specie & sp, const Polynomial< PolySize > & rhoPoly) inline
Construct from components.
Definition at line 27 of file icoPolynomialI.H.
Referenced by icoPolynomial< Specie, PolySize >::icoPolynomial().
icoPolynomial (const dictionary & dict)
Construct from dictionary.
Definition at line 32 of file icoPolynomial.C.
References dict, and icoPolynomial< Specie, PolySize >::icoPolynomial().
icoPolynomial (const word & name, const icoPolynomial< Specie, PolySize > &) inline
Construct as named copy.
Member Function Documentation
Foam::autoPtr< Foam::icoPolynomial< Specie, PolySize > > clone () const inline
Construct and return a clone.
Definition at line 53 of file icoPolynomialI.H.
Foam::autoPtr< Foam::icoPolynomial< Specie, PolySize > > New (const dictionary & dict) inline static
Definition at line 61 of file icoPolynomialI.H.
References Foam::New().
static word typeName () inline static
Return the instantiated type name.
Definition at line 179 of file icoPolynomial.H.
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 71 of file icoPolynomialI.H.
Foam::scalar H (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kg].
Definition at line 82 of file icoPolynomialI.H.
Foam::scalar Cp (scalar p, scalar T) const inline
Return Cp departure [J/(kg K].
Definition at line 93 of file icoPolynomialI.H.
Foam::scalar E (const scalar p, const scalar T) const inline
Return internal energy departure [J/kg].
Definition at line 104 of file icoPolynomialI.H.
Foam::scalar Cv (scalar p, scalar T) const inline
Return Cv departure [J/(kg K].
Definition at line 115 of file icoPolynomialI.H.
Foam::scalar S (const scalar p, const scalar T) const inline
Return entropy [J/(kg K)].
Definition at line 126 of file icoPolynomialI.H.
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 137 of file icoPolynomialI.H.
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 148 of file icoPolynomialI.H.
Foam::scalar CpMCv (scalar p, scalar T) const inline
Return (Cp - Cv) [J/(kg K].
Definition at line 159 of file icoPolynomialI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 42 of file icoPolynomial.C.
void operator= (const icoPolynomial< Specie, PolySize > &) inline
Definition at line 172 of file icoPolynomialI.H.
void operator+= (const icoPolynomial< Specie, PolySize > &) inline
Definition at line 184 of file icoPolynomialI.H.
void operator*= (const scalar s) inline
Definition at line 202 of file icoPolynomialI.H.
Friends And Related Function Documentation
icoPolynomial operator+ (const icoPolynomial< Specie, PolySize > & , const icoPolynomial< Specie, PolySize > &) friend
icoPolynomial operator* (const scalar s, const icoPolynomial< Specie, PolySize > &) friend
icoPolynomial operator== (const icoPolynomial< Specie, PolySize > & , const icoPolynomial< Specie, PolySize > &) friend
Ostream& operator (Ostream & , const icoPolynomial< Specie, PolySize > &) friend
Member Data Documentation
const bool incompressible = true static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 190 of file icoPolynomial.H.
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 195 of file icoPolynomial.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomial.H
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomial.C
src/thermophysicalModels/specie/equationOfState/icoPolynomial/icoPolynomialI.H