OpenFOAM: keyType Class Reference
keyType Class Reference
A class for handling keywords in dictionaries.
Public Types
enum option : unsigned char {
LITERAL = 0, REGEX = 1, RECURSIVE = 0x80, LITERAL_RECURSIVE = (LITERAL | RECURSIVE),
REGEX_RECURSIVE = (REGEX | RECURSIVE)
}
Enumeration for the data type and search/match modes (bitmask)
Public Member Functions
keyType ()
Construct null.
keyType (const keyType &s)
Copy construct, retaining type (literal or regex)
keyType (const word &s)
Copy construct from word, treat as literal.
keyType (const string &s)
Copy construct from string, treat as regular expression.
keyType (const char *s)
Construct as copy of character array, treat as literal.
keyType (const std::string &s, option opt)
Copy construct from std::string with specified treatment.
keyType (keyType &&s)
Move construct, retaining type (literal or regex)
keyType (word &&s)
Move construct from word, treat as literal.
keyType (string &&s)
Move construct from string, treat as regular expression.
keyType (std::string &&s, option opt)
Move construct from std::string with specified treatment.
keyType (Istream &is)
Construct from Istream.
bool isLiteral () const
The keyType is treated as literal, not as pattern.
bool isPattern () const
The keyType is treated as a pattern, not as literal string.
void setType (option opt, bool adjust=false)
Change the representation.
bool compile ()
Mark as regular expression.
void uncompile (bool adjust=false)
Mark as literal, instead of a regular expression.
void clear ()
Clear string and set as literal.
void swap (keyType &s)
Swap contents. Self-swapping is a no-op.
bool match (const std::string &text, bool literal=false) const
Smart match as regular expression or as a string.
bool operator() (const std::string &text) const
Perform smart match on text, as per match()
void operator= (const keyType &s)
Copy assignment, retaining type (literal or regex)
void operator= (keyType &&s)
Move assignment, retaining type (literal or regex)
void operator= (const word &s)
Assign as word, treat as literal.
void operator= (const string &s)
Assign from Foam::string, treat as regular expression.
void operator= (const char *s)
Assign as word, treat as literal.
keyType (const std::string &s, bool isPattern)
Deprecated(2019-08) construct as literal/regex.
Public Member Functions inherited from word
word ()=default
Construct null.
word (const word &)=default
Copy construct.
word (word &&w)=default
Move construct.
word (const string &s, bool doStrip=true)
Copy construct from Foam::string.
word (string &&s, bool doStrip=true)
Move construct from Foam::string.
word (const std::string &s, bool doStrip=true)
Copy construct from std::string.
word (std::string &&s, bool doStrip=true)
Move construct from std::string.
word (const char *s, bool doStrip=true)
Copy from character array.
word (const char *s, size_type len, bool doStrip)
Copy from buffer for a maximum number of characters.
word (Istream &is)
Construct from Istream.
void stripInvalid ()
Strip invalid characters from this word.
word lessExt () const
Return word without extension (part before last .)
word ext () const
Return file name extension (part after last .)
word & ext (const word &ending)
Append a '.' and the ending, and return the object.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
word & operator= (const word &s)
Copy assignment, no character validation required.
word & operator= (word &&s)
Move assignment, no character validation required.
word & operator= (const string &s)
Copy assignment from Foam::string, stripping invalid characters.
word & operator= (string &&s)
Move assignment from Foam::string, stripping invalid characters.
word & operator= (const std::string &s)
Copy assignment from std::string, stripping invalid characters.
word & operator= (std::string &&s)
Move assignment from std::string, stripping invalid characters.
word & operator= (const char *s)
Copy, stripping invalid characters.
template<class PrimitiveType >
Foam::word printf (const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
Foam::word printf (const std::string &fmt, const PrimitiveType &val)
Public Member Functions inherited from string
string ()=default
Construct null.
string (const std::string &str)
Copy construct from std::string.
string (std::string &&str)
Move construct from std::string.
string (const char *str)
Construct as copy of character array.
string (const char *str, const size_type len)
Construct as copy with a maximum number of characters.
string (const char c)
Construct from a single character.
string (const size_type len, const char c)
Construct fill copies of a single character.
string (Istream &is)
Construct from Istream.
bool match (const std::string &text) const
Test for equality.
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
Replace first occurrence of sub-string s1 with s2, beginning at pos.
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
Replace all occurrences of sub-string s1 with s2, beginning at pos in the string.
string & expand (const bool allowEmpty=false)
Inplace expand initial tags, tildes, and all occurrences of environment variables as per stringOps::expand.
bool removeRepeated (const char character)
Remove repeated characters.
bool removeStart (const std::string &text)
Remove the given text from the start of the string.
bool removeStart (const char c)
Remove leading character, unless string is a single character.
bool removeEnd (const std::string &text)
Remove the given text from the end of the string.
bool removeEnd (const char c)
Remove trailing character, unless string is a single character.
void swap (std::string &str)
Swap contents. Self-swapping is a no-op.
bool operator() (const std::string &text) const
Test for equality. Allows use as a predicate.
bool starts_with (const std::string &s) const
True if string starts with the given prefix (cf. C++20)
bool starts_with (const char c) const
True if string starts with the given character (cf. C++20)
bool ends_with (const std::string &s) const
True if string ends with the given suffix (cf. C++20)
bool ends_with (const char c) const
True if string ends with the given character (cf. C++20)
size_type count (const char c) const
Count the number of occurrences of the specified character in the string.
bool startsWith (const std::string &s) const
Deprecated(2019-11)
bool endsWith (const std::string &s) const
Deprecated(2019-11)
bool removeTrailing (const char c)
Deprecated(2019-11)
template<class String >
Foam::string quotemeta (const std::string &str, const char quote)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Static Public Member Functions
static bool valid (char c)
Is this character valid for a keyType?
Static Public Member Functions inherited from word
template<class PrimitiveType >
static word printf (const char *fmt, const PrimitiveType &val)
Use a printf-style formatter for a primitive.
template<class PrimitiveType >
static word printf (const std::string &fmt, const PrimitiveType &val)
Use a printf-style formatter for a primitive.
static bool valid (char c)
Is this character valid for a word?
static word validate (const std::string &s, const bool prefix=false)
Construct validated word (no invalid characters).
static word validate (const char *first, const char *last, const bool prefix=false)
Construct validated word (no invalid characters) from a sequence of characters in the range [first,last),.
Static Public Member Functions inherited from string
template<class String >
static bool valid (const std::string &str)
Does the string contain valid characters only?
template<class String >
static bool meta (const std::string &str, const char quote='\\')
Does this string contain meta-characters?
template<class String >
static bool stripInvalid (std::string &str)
Strip invalid characters from the given string.
template<class String >
static String validate (const std::string &str)
Return a valid String from the given string.
template<class String >
static string quotemeta (const std::string &str, const char quote= '\\')
Return a String with quoted meta-characters from the given string.
Static Public Attributes
static const keyType null
An empty keyType.
Static Public Attributes inherited from word
static const char *const typeName = "word"
The typeName.
static int debug
Debugging.
static const word null
An empty word.
Static Public Attributes inherited from string
static const char *const typeName = "string"
The type name "string".
static int debug
The debug flag.
static const string null
An empty string.
Additional Inherited Members
Protected Member Functions inherited from string
std::string::size_type find_ext () const
Find position of a file extension dot, return npos on failure.
word ext () const
Return file name extension (part after last .)
bool ext (const word &ending)
Append a '.' and the ending.
bool hasPath () const
Return true if it contains a '/' character.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
bool removePath ()
Remove leading path, returning true if string changed.
Static Protected Member Functions inherited from string
static std::string::size_type find_ext (const std::string &str)
Find position of a file extension dot, return npos on failure.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
Detailed Description
A class for handling keywords in dictionaries.
A keyType is the keyword of a dictionary. It differs from word in that it also accepts patterns (regular expressions). It is very similar to wordRe, but doesn't store a regular expression.
Source files
keyType.H
keyType.C
Definition at line 56 of file keyType.H.
Member Enumeration Documentation
enum option : unsigned char
Enumeration for the data type and search/match modes (bitmask)
eg, (keyType::REGEX | keyType::RECURSIVE)
Enumerator
LITERAL
String literal.
REGEX
Regular expression.
RECURSIVE
Recursive search (eg, in dictionary)
LITERAL_RECURSIVE
REGEX_RECURSIVE
Definition at line 69 of file keyType.H.
Constructor & Destructor Documentation
keyType () inline
Construct null.
Definition at line 41 of file keyTypeI.H.
keyType (const keyType & s) inline
Copy construct, retaining type (literal or regex)
Definition at line 48 of file keyTypeI.H.
keyType (const word & s) inline
Copy construct from word, treat as literal.
Definition at line 55 of file keyTypeI.H.
keyType (const string & s) inline
Copy construct from string, treat as regular expression.
Definition at line 62 of file keyTypeI.H.
keyType (const char * s) inline
Construct as copy of character array, treat as literal.
Definition at line 69 of file keyTypeI.H.
keyType (const std::string & s, option opt) inline
Copy construct from std::string with specified treatment.
Definition at line 76 of file keyTypeI.H.
keyType (keyType && s) inline
Move construct, retaining type (literal or regex)
Definition at line 83 of file keyTypeI.H.
keyType (word && s) inline
Move construct from word, treat as literal.
Definition at line 92 of file keyTypeI.H.
References s.
keyType (string && s) inline
Move construct from string, treat as regular expression.
Definition at line 99 of file keyTypeI.H.
keyType (std::string && s, option opt) inline
Move construct from std::string with specified treatment.
Definition at line 106 of file keyTypeI.H.
keyType (Istream & is) explicit
Construct from Istream.
Treat as regular expression if surrounded by quotation marks.
Definition at line 33 of file keyType.C.
keyType (const std::string & s, bool isPattern) inline
Deprecated(2019-08) construct as literal/regex.
Deprecated:
(2019-08) - use Construct with option
Definition at line 287 of file keyType.H.
Member Function Documentation
bool valid (char c) inline static
Is this character valid for a keyType?
This is largely identical with what word accepts, but also permit brace-brackets, which are valid for some regexs.
Definition at line 26 of file keyTypeI.H.
References Foam::isspace().
Referenced by wordRe::isPattern().
bool isLiteral () const inline
The keyType is treated as literal, not as pattern.
Definition at line 115 of file keyTypeI.H.
Referenced by GeometricField< Type, PatchField, GeoMesh >::Boundary::readField().
bool isPattern () const inline
The keyType is treated as a pattern, not as literal string.
Definition at line 121 of file keyTypeI.H.
Referenced by Ostream::writeKeyword().
void setType (option opt, bool adjust = false) inline
Change the representation.
Definition at line 127 of file keyTypeI.H.
bool compile () inline
Mark as regular expression.
Definition at line 144 of file keyTypeI.H.
void uncompile (bool adjust = false) inline
Mark as literal, instead of a regular expression.
Optionally strip invalid word characters.
Definition at line 151 of file keyTypeI.H.
void clear () inline
Clear string and set as literal.
Definition at line 157 of file keyTypeI.H.
void swap (keyType & s) inline
Swap contents. Self-swapping is a no-op.
Definition at line 164 of file keyTypeI.H.
References clear().
bool match (const std::string & text, bool literal = false) const
Smart match as regular expression or as a string.
Optionally force a literal match only
Definition at line 44 of file keyType.C.
bool operator() (const std::string & text) const inline
Perform smart match on text, as per match()
Allows use as a predicate.
Definition at line 178 of file keyTypeI.H.
void operator= (const keyType & s) inline
Copy assignment, retaining type (literal or regex)
Self-assignment is a no-op.
Definition at line 184 of file keyTypeI.H.
References Foam::stringOps::match().
void operator= (keyType && s) inline
Move assignment, retaining type (literal or regex)
Self-assignment is a no-op.
Definition at line 196 of file keyTypeI.H.
void operator= (const word & s) inline
Assign as word, treat as literal.
Definition at line 208 of file keyTypeI.H.
void operator= (const string & s) inline
Assign from Foam::string, treat as regular expression.
Definition at line 215 of file keyTypeI.H.
References Foam::FieldOps::assign().
void operator= (const char * s) inline
Assign as word, treat as literal.
Definition at line 222 of file keyTypeI.H.
References Foam::FieldOps::assign().
Member Data Documentation
const Foam::keyType null static
An empty keyType.
Definition at line 109 of file keyType.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/keyType/keyType.H
src/OpenFOAM/primitives/strings/keyType/keyType.C
src/OpenFOAM/primitives/strings/keyType/keyTypeI.H