OpenFOAM: LduMatrix< Type, DType, LUType >::smoother Class Reference
LduMatrix< Type, DType, LUType >::smoother Class Reference abstract
Abstract base-class for LduMatrix smoothers.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, smoother, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
declareRunTimeSelectionTable (autoPtr, smoother, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix),(fieldName, matrix))
smoother (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix)
virtual ~smoother ()=default
const word & fieldName () const
const LduMatrix< Type, DType,
LUType > & matrix () const
virtual void smooth (Field< Type > &psi, const label nSweeps) const =0
Smooth the solution for a given number of sweeps.
Static Public Member Functions
static autoPtr< smoother > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &smootherDict)
Return a new smoother.
Protected Attributes
word fieldName_
const LduMatrix< Type, DType,
LUType > & matrix_
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >::smoother
Abstract base-class for LduMatrix smoothers.
Definition at line 300 of file LduMatrix.H.
Constructor & Destructor Documentation
smoother (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix)
Definition at line 98 of file LduMatrixSmoother.C.
virtual ~smoother () virtual default
Member Function Documentation
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (autoPtr , smoother , symMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix) , (fieldName, matrix))
declareRunTimeSelectionTable (autoPtr , smoother , asymMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix) , (fieldName, matrix))
Foam::autoPtr< typename Foam::LduMatrix< Type, DType, LUType >::smoother > New (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & smootherDict) static
Return a new smoother.
Definition at line 29 of file LduMatrixSmoother.C.
References LduMatrix< Type, DType, LUType >::asymmetric(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, LduMatrix< Type, DType, LUType >::smoother::fieldName(), dictionary::get(), LduMatrix< Type, DType, LUType >::smoother::matrix(), and LduMatrix< Type, DType, LUType >::symmetric().
const word& fieldName () const inline
Definition at line 382 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::smoother::New().
const LduMatrix<Type, DType, LUType>& matrix () const inline
Definition at line 387 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::smoother::New().
virtual void smooth (Field< Type > & psi, const label nSweeps) const pure virtual
Smooth the solution for a given number of sweeps.
Implemented in TGaussSeidelSmoother< Type, DType, LUType >.
Member Data Documentation
word fieldName_ protected
Definition at line 306 of file LduMatrix.H.
const LduMatrix<Type, DType, LUType>& matrix_ protected
Definition at line 307 of file LduMatrix.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixSmoother.C