OpenFOAM: DictionaryBase< IDLListType, T > Class Template Reference
DictionaryBase< IDLListType, T > Class Template Reference
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
Public Member Functions
DictionaryBase (const label size=128)
Construct with given or default (128) table capacity.
DictionaryBase (const DictionaryBase &dict)
Copy construct.
template<class INew >
DictionaryBase (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
DictionaryBase (Istream &is)
Construct from Istream using default Istream constructor class.
bool found (const word &keyword) const
Search for given keyword.
const T * lookupPtr (const word &keyword) const
Find and return an entry if present, otherwise return nullptr.
T * lookupPtr (const word &keyword)
Find and return an entry if present, otherwise return nullptr.
const T * lookup (const word &keyword) const
Find and return entry.
T * lookup (const word &keyword)
Find and return entry.
wordList toc () const
Return the table of contents (as a sorted list)
wordList sortedToc () const
Return the table of contents as a sorted list.
template<class Compare >
wordList sortedToc (const Compare &comp) const
Return table of contents sorted using the specified comparator.
void insert (const word &keyword, T *)
Add at head of dictionary.
void append (const word &keyword, T *)
Add at tail of dictionary.
T * remove (const word &keyword)
Remove and return entry specified by keyword.
void clear ()
Clear the dictionary.
void transfer (DictionaryBase< IDLListType, T > &dict)
Transfer the contents of the argument into this DictionaryBase.
void operator= (const DictionaryBase &)
Copy assigment.
const T * operator[] (const word &key) const
Find and return entry.
T * operator[] (const word &key)
Find and return entry.
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
Protected Member Functions
void addEntries ()
Protected Attributes
HashTable< T * > hashedTs_
HashTable of the entries held on the IDLListType for quick lookup.
Friends
Ostream & operator (Ostream &, const DictionaryBase< IDLListType, T > &)
Detailed Description
template<class IDLListType, class T>
class Foam::DictionaryBase< IDLListType, T >
Base dictionary class templated on both the form of doubly-linked list it uses as well as the type it holds.
The double templating allows for the instantiation of forms with or without storage management.
Note
The IDLListType parameter should itself be a template but this confused gcc 2.95.2 so it has to be instantiated for T when an instantiation of DictionaryBase is requested
See Also
Dictionary and UDictionary
Source files
DictionaryBase.H
DictionaryBase.C
DictionaryBaseIO.C
Definition at line 59 of file DictionaryBase.H.
Constructor & Destructor Documentation
DictionaryBase (const label size = 128) explicit
Construct with given or default (128) table capacity.
Definition at line 39 of file DictionaryBase.C.
DictionaryBase (const DictionaryBase< IDLListType, T > & dict)
Copy construct.
Definition at line 47 of file DictionaryBase.C.
DictionaryBase (Istream & is, const INew & inew)
Construct from Istream using given Istream constructor class.
Definition at line 60 of file DictionaryBase.C.
DictionaryBase (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 72 of file DictionaryBase.C.
Member Function Documentation
void addEntries () protected
Definition at line 27 of file DictionaryBase.C.
References stdFoam::begin(), end(), and iter.
bool found (const word & keyword) const
Search for given keyword.
Definition at line 83 of file DictionaryBase.C.
const T * lookupPtr (const word & keyword) const
Find and return an entry if present, otherwise return nullptr.
Definition at line 91 of file DictionaryBase.C.
Referenced by Foam::appendNamedEntry().
T * lookupPtr (const word & keyword)
Find and return an entry if present, otherwise return nullptr.
Definition at line 107 of file DictionaryBase.C.
const T * lookup (const word & keyword) const
Find and return entry.
Definition at line 121 of file DictionaryBase.C.
T * lookup (const word & keyword)
Find and return entry.
Definition at line 137 of file DictionaryBase.C.
Foam::wordList toc () const
Return the table of contents (as a sorted list)
Definition at line 153 of file DictionaryBase.C.
Foam::wordList sortedToc () const
Return the table of contents as a sorted list.
Definition at line 163 of file DictionaryBase.C.
wordList sortedToc (const Compare & comp) const
Return table of contents sorted using the specified comparator.
void insert (const word & keyword, T * tPtr)
Add at head of dictionary.
Definition at line 181 of file DictionaryBase.C.
void append (const word & keyword, T * tPtr)
Add at tail of dictionary.
Definition at line 190 of file DictionaryBase.C.
Referenced by Foam::appendNamedEntry().
T * remove (const word & keyword)
Remove and return entry specified by keyword.
Return nullptr if the keyword was not found.
Definition at line 199 of file DictionaryBase.C.
void clear ()
Clear the dictionary.
Definition at line 215 of file DictionaryBase.C.
void transfer (DictionaryBase< IDLListType, T > & dict)
Transfer the contents of the argument into this DictionaryBase.
and annul the argument.
Definition at line 224 of file DictionaryBase.C.
void operator= (const DictionaryBase< IDLListType, T > &)
Copy assigment.
Definition at line 242 of file DictionaryBase.C.
const T* operator[] (const word & key) const inline
Find and return entry.
Definition at line 204 of file DictionaryBase.H.
T* operator[] (const word & key) inline
Find and return entry.
Definition at line 212 of file DictionaryBase.H.
Foam::wordList sortedToc (const Compare & comp) const
Definition at line 172 of file DictionaryBase.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const DictionaryBase< IDLListType, T > &) friend
Member Data Documentation
HashTable<T*> hashedTs_ protected
HashTable of the entries held on the IDLListType for quick lookup.
Definition at line 81 of file DictionaryBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.H
src/OpenFOAM/containers/Dictionaries/DictionaryBase/DictionaryBase.C