OpenFOAM: thermophysicalProperties Class Reference
thermophysicalProperties Class Reference abstract
Base-class for thermophysical properties of solids, liquids and gases providing an interface compatible with the templated thermodynamics packages.
Public Member Functions
TypeName ("thermophysicalProperties")
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties,,(),())
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties, dictionary,(const dictionary &dict),(dict))
thermophysicalProperties (scalar W)
Construct from molecular weight.
thermophysicalProperties (const dictionary &dict)
Construct from dictionary.
virtual ~thermophysicalProperties ()=default
Destructor.
scalar W () const
Molecular weight [kg/kmol].
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
virtual scalar rho (scalar p, scalar T) const =0
Liquid density [kg/m^3].
virtual scalar psi (scalar p, scalar T) const =0
Liquid compressibility rho/p [s^2/m^2].
virtual scalar CpMCv (scalar p, scalar T) const =0
Return (Cp - Cv) [J/(kg K].
virtual scalar Cp (const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Hs (const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar Hc () const =0
Chemical enthalpy [J/kg].
virtual scalar Ha (const scalar p, const scalar T) const =0
Absolute Enthalpy [J/kg].
virtual scalar S (const scalar p, const scalar T) const =0
virtual scalar mu (scalar p, scalar T) const =0
Liquid viscosity [Pa s].
virtual scalar kappa (scalar p, scalar T) const =0
Liquid thermal conductivity [W/(m K)].
virtual scalar alphah (const scalar p, const scalar T) const =0
Liquid thermal diffusivity of enthalpy [kg/ms].
void readIfPresent (const dictionary &dict)
Read and set the properties present it the given dictionary.
virtual void writeData (Ostream &os) const =0
Write the function coefficients.
Static Public Member Functions
static autoPtr
< thermophysicalProperties > New (const word &name)
Return a pointer to a new thermophysicalProperties created from name.
static autoPtr
< thermophysicalProperties > New (const dictionary &dict)
Return a pointer to a new thermophysicalProperties.
Friends
Ostream & operator<< (Ostream &os, const thermophysicalProperties &l)
Ostream Operator.
Detailed Description
Base-class for thermophysical properties of solids, liquids and gases providing an interface compatible with the templated thermodynamics packages.
Source files
thermophysicalProperties.H
thermophysicalPropertiesI.H
thermophysicalProperties.C
Definition at line 51 of file thermophysicalProperties.H.
Constructor & Destructor Documentation
thermophysicalProperties (scalar W)
Construct from molecular weight.
Definition at line 35 of file thermophysicalProperties.C.
thermophysicalProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 41 of file thermophysicalProperties.C.
virtual ~thermophysicalProperties () virtual default
Destructor.
Member Function Documentation
TypeName ("thermophysicalProperties")
declareRunTimeSelectionTable (autoPtr , thermophysicalProperties , () , ())
declareRunTimeSelectionTable (autoPtr , thermophysicalProperties , dictionary , (const dictionary &dict) , (dict))
Foam::autoPtr< Foam::thermophysicalProperties > New (const word & name) static
Return a pointer to a new thermophysicalProperties created from name.
Definition at line 51 of file thermophysicalProperties.C.
Foam::autoPtr< Foam::thermophysicalProperties > New (const dictionary & dict) static
Return a pointer to a new thermophysicalProperties.
created from dictionary
Definition at line 75 of file thermophysicalProperties.C.
Foam::scalar W () const inline
Molecular weight [kg/kmol].
Definition at line 29 of file thermophysicalPropertiesI.H.
References Foam::T().
Referenced by liquidFilmThermo::Tb().
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 23 of file thermophysicalPropertiesI.H.
virtual scalar rho (scalar p, scalar T) const pure virtual
Liquid density [kg/m^3].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::mu().
virtual scalar psi (scalar p, scalar T) const pure virtual
Liquid compressibility rho/p [s^2/m^2].
Note: currently it is assumed the liquid is incompressible
Implemented in liquidProperties.
virtual scalar CpMCv (scalar p, scalar T) const pure virtual
Return (Cp - Cv) [J/(kg K].
Note: currently it is assumed the liquid is incompressible so CpMCv 0
Implemented in liquidProperties.
virtual scalar Cp (const scalar p, const scalar T) const pure virtual
Heat capacity at constant pressure [J/(kg K)].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::kappa().
virtual scalar Hs (const scalar p, const scalar T) const pure virtual
Sensible enthalpy [J/kg].
Implemented in liquidProperties.
virtual scalar Hc () const pure virtual
Chemical enthalpy [J/kg].
Implemented in liquidProperties.
virtual scalar Ha (const scalar p, const scalar T) const pure virtual
Absolute Enthalpy [J/kg].
Implemented in liquidProperties.
virtual scalar S (const scalar p, const scalar T) const pure virtual
Implemented in liquidProperties.
virtual scalar mu (scalar p, scalar T) const pure virtual
Liquid viscosity [Pa s].
Implemented in liquidProperties, IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
virtual scalar kappa (scalar p, scalar T) const pure virtual
Liquid thermal conductivity [W/(m K)].
Implemented in liquidProperties, IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
virtual scalar alphah (const scalar p, const scalar T) const pure virtual
Liquid thermal diffusivity of enthalpy [kg/ms].
Implemented in liquidProperties.
void readIfPresent (const dictionary & dict)
Read and set the properties present it the given dictionary.
Definition at line 102 of file thermophysicalProperties.C.
void writeData (Ostream & os) const pure virtual
Write the function coefficients.
Implemented in liquidProperties, IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, iC3H8O, IC8H18, MB, N2, nC3H8O, H2O, and C8H10.
Definition at line 108 of file thermophysicalProperties.C.
References dictionary::readIfPresent().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const thermophysicalProperties & l) friend
Ostream Operator.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalProperties/thermophysicalProperties.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalProperties/thermophysicalProperties.C
src/thermophysicalModels/thermophysicalProperties/thermophysicalProperties/thermophysicalPropertiesI.H