OpenFOAM: searchableBox Class Reference
searchableBox Class Reference
Searching on bounding box.
Public Member Functions
TypeName ("searchableBox")
Runtime type information.
searchableBox (const IOobject &io, const treeBoundBox &bb)
Construct from components.
searchableBox (const IOobject &io, const dictionary &dict)
Construct from dictionary (used by searchableSurface)
virtual ~searchableBox ()=default
Destructor.
virtual const wordList & regions () const
Names of regions.
virtual bool hasVolumeType () const
Whether surface supports volume type (below)
virtual volumeType outsideVolumeType () const
What is type of points outside bounds.
virtual label size () const
Range of local indices that can be returned.
virtual tmp< pointField > coordinates () const
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
Get bounding spheres (centre and radius squared), one per element.
virtual tmp< pointField > points () const
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const
Does any part of the surface overlap the supplied bound box?
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
Calculate nearest point on surface.
pointIndexHit findNearestOnEdge (const point &sample, const scalar nearestDistSqr) const
Calculate nearest point on edge.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to segment.
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &) const
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &) const
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &, labelList &region) const
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &, vectorField &normal) const
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &points, List< volumeType > &volType) const
Determine type (inside/outside) for points.
bool writeData (Ostream &) const
Pure virtual writeData function.
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr
< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()=default
Destructor.
virtual bool global () const
Is object global.
virtual fileName filePath () const
Return complete path + object name if the file exists.
virtual const boundBox & bounds () const
Return const reference to boundBox.
virtual boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual label globalSize () const
Range of global indices that can be returned.
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest locations for the supplied points to a.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
virtual void setField (const labelList &values)
WIP. Store element-wise field.
virtual void getField (const List< pointIndexHit > &, labelList &values) const
WIP. From a set of hits (points and.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Public Member Functions inherited from treeBoundBox
treeBoundBox ()
Construct without any points - an inverted bounding box.
treeBoundBox (const boundBox &bb)
Construct from a boundBox.
treeBoundBox (const point &pt)
Construct a bounding box containing a single initial point.
treeBoundBox (const point &min, const point &max)
Construct from components.
treeBoundBox (const UList< point > &points)
Construct as the bounding box of the given pointField.
treeBoundBox (const UList< point > &points, const labelUList &indices)
Construct as subset of points.
template<unsigned N>
treeBoundBox (const UList< point > &points, const FixedList< label, N > &indices)
Construct as subset of points.
treeBoundBox (Istream &is)
Construct from Istream.
scalar typDim () const
Typical dimension length,height,width.
tmp< pointField > points () const
Vertex coordinates. In octant coding.
point corner (const direction octant) const
Corner point of given octant.
treeBoundBox subBbox (const direction octant) const
Sub-box of given octant. Midpoint calculated.
treeBoundBox subBbox (const point &mid, const direction) const
Sub-box given by octant number. Midpoint provided.
direction subOctant (const point &pt) const
Returns octant number given point and the calculated midpoint.
direction subOctant (const point &pt, bool &onEdge) const
Returns octant number given point and the calculated midpoint.
void searchOrder (const point &pt, FixedList< direction, 8 > &octantOrder) const
Calculates optimal order to look for nearest to point.
bool intersects (const point &overallStart, const vector &overallVec, const point &start, const point &end, point &pt, direction &ptBits) const
Intersects segment; set point to intersection position and face,.
bool intersects (const point &start, const point &end, point &pt) const
Like above but does not return faces point is on.
bool contains (const vector &dir, const point &) const
Contains point (inside or on edge) and moving in direction.
direction faceBits (const point &pt) const
Code position of point on bounding box faces.
direction posBits (const point &pt) const
Position of point relative to bounding box.
void calcExtremities (const point &pt, point &nearest, point &furthest) const
Calculate nearest and furthest (to point) vertex coords of.
scalar maxDist (const point &pt) const
Returns distance point to furthest away corner.
label distanceCmp (const point &pt, const treeBoundBox &other) const
Compare distance to point with other bounding box.
treeBoundBox extend (Random &rndGen, const scalar s) const
Return slightly wider bounding box.
Public Member Functions inherited from boundBox
boundBox ()
Construct without any points - an inverted bounding box.
boundBox (const point &pt)
Construct a bounding box containing a single initial point.
boundBox (const point &min, const point &max)
Construct from components.
boundBox (const UList< point > &points, bool doReduce=true)
Construct as the bounding box of the given points.
boundBox (const tmp< pointField > &tpoints, bool doReduce=true)
Construct as the bounding box of the given temporary pointField.
boundBox (const UList< point > &points, const labelUList &indices, bool doReduce=true)
Construct bounding box as an indirect subset of the points.
template<unsigned N>
boundBox (const UList< point > &points, const FixedList< label, N > &indices, bool doReduce=true)
Construct bounding box as an indirect subset of the points.
boundBox (Istream &is)
Construct from Istream.
bool empty () const
Bounding box is inverted, contains no points.
bool valid () const
Bounding box is non-inverted.
const point & min () const
Minimum describing the bounding box.
const point & max () const
Maximum describing the bounding box.
point & min ()
Minimum describing the bounding box, non-const access.
point & max ()
Maximum describing the bounding box, non-const access.
point centre () const
The centre (midpoint) of the bounding box.
point midpoint () const
The midpoint (centre) of the bounding box. Identical to centre()
vector span () const
The bounding box span (from minimum to maximum)
scalar mag () const
The magnitude of the bounding box span.
scalar volume () const
The volume of the bound box.
scalar minDim () const
Smallest length/height/width dimension.
scalar maxDim () const
Largest length/height/width dimension.
scalar avgDim () const
Average length/height/width dimension.
label nDim () const
Count the number of positive, non-zero dimensions.
tmp< pointField > points () const
Corner points in an order corresponding to a 'hex' cell.
tmp< pointField > faceCentres () const
Face midpoints.
point faceCentre (const direction facei) const
Face centre of given face index.
void clear ()
Clear bounding box and make it an inverted box.
void add (const boundBox &bb)
Extend to include the second box.
void add (const point &pt)
Extend to include the point.
void add (const UList< point > &points)
Extend to include the points.
void add (const tmp< pointField > &tpoints)
Extend to include the points from the temporary point field.
template<unsigned N>
void add (const FixedList< point, N > &points)
Extend to include the points.
template<unsigned N>
void add (const UList< point > &points, const FixedList< label, N > &indices)
Extend to include a (subsetted) point field.
template<class IntContainer >
void add (const UList< point > &points, const IntContainer &indices)
Extend to include a (subsetted) point field.
void inflate (const scalar s)
Inflate box by factor*mag(span) in all dimensions.
void reduce ()
Parallel reduction of min/max values.
bool intersect (const boundBox &bb)
Intersection (union) with the second box.
bool intersects (const plane &pln) const
Does plane intersect this bounding box.
bool overlaps (const boundBox &bb) const
Overlaps/touches boundingBox?
bool overlaps (const point &centre, const scalar radiusSqr) const
Overlaps boundingSphere (centre + sqr(radius))?
bool contains (const point &pt) const
Contains point? (inside or on edge)
bool contains (const boundBox &bb) const
Fully contains other boundingBox?
bool containsInside (const point &pt) const
Contains point? (inside only)
bool contains (const UList< point > &points) const
Contains all points? (inside or on edge)
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
Contains all of the (subsetted) points? (inside or on edge)
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
Contains all of the (subsetted) points? (inside or on edge)
bool containsAny (const UList< point > &points) const
Contains any of the points? (inside or on edge)
template<unsigned N>
bool containsAny (const UList< point > &points, const FixedList< label, N > &indices) const
Contains any of the (subsetted) points? (inside or on edge)
template<class IntContainer >
bool containsAny (const UList< point > &points, const IntContainer &indices) const
Contains any of the (subsetted) points? (inside or on edge)
point nearest (const point &pt) const
Return the nearest point on the boundBox to the supplied point.
void operator+= (const boundBox &bb)
Extend box to include the second box, as per the add() method.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Public Types inherited from treeBoundBox
enum octantBit : direction { RIGHTHALF = 0x1, TOPHALF = 0x2, FRONTHALF = 0x4 }
Bits used for octant/point encoding.
enum faceId {
LEFT = 0, RIGHT = 1, BOTTOM = 2, TOP = 3,
BACK = 4, FRONT = 5
}
Face codes. Identical order and meaning as per hex cellmodel and boundBox, but have a different point ordering.
enum faceBit : direction {
NOFACE = 0, LEFTBIT = 0x1 << LEFT, RIGHTBIT = 0x1 << RIGHT, BOTTOMBIT = 0x1 << BOTTOM,
TOPBIT = 0x1 << TOP, BACKBIT = 0x1 << BACK, FRONTBIT = 0x1 << FRONT
}
Bits used for face encoding.
enum edgeId {
E01 = 0, E13 = 1, E23 = 2, E02 = 3,
E45 = 4, E57 = 5, E67 = 6, E46 = 7,
E04 = 8, E15 = 9, E37 = 10, E26 = 11
}
Edges codes.
Public Types inherited from boundBox
enum directionBit : direction { XDIR = 0x1, YDIR = 0x2, ZDIR = 0x4 }
Bits used for (x/y/z) direction encoding.
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Member Functions inherited from treeBoundBox
static direction subOctant (const point &mid, const point &pt)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const point &pt, bool &onEdge)
Returns octant number given point and midpoint.
static direction subOctant (const point &mid, const vector &dir, const point &pt, bool &onEdge)
Returns octant number given intersection and midpoint.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Public Attributes inherited from treeBoundBox
static const faceList faces
Face to point addressing.
static const edgeList edges
Edge to point addressing.
Static Public Attributes inherited from boundBox
static const boundBox greatBox
A large boundBox: min/max == -/+ ROOTVGREAT.
static const boundBox invertedBox
A large inverted boundBox: min/max == +/- ROOTVGREAT.
static const faceList faces
Faces to point addressing, as per a 'hex' cell.
static const FixedList< vector, 6 > faceNormals
The unit normal per face.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Searching on bounding box.
Dictionary parameters
Property Description Required Default
type box / searchableBox selector
min minimum point for bounding box yes
max maximum point for bounding box yes
Source files
searchableBox.H
searchableBox.C
Definition at line 76 of file searchableBox.H.
Constructor & Destructor Documentation
searchableBox (const IOobject & io, const treeBoundBox & bb)
Construct from components.
Definition at line 174 of file searchableBox.C.
searchableBox (const IOobject & io, const dictionary & dict)
Construct from dictionary (used by searchableSurface)
Definition at line 195 of file searchableBox.C.
virtual ~searchableBox () virtual default
Destructor.
Member Function Documentation
TypeName ("searchableBox")
Runtime type information.
const Foam::wordList & regions () const virtual
Names of regions.
Implements searchableSurface.
Definition at line 217 of file searchableBox.C.
Referenced by searchableRotatedBox::coordinates().
virtual bool hasVolumeType () const inline virtual
Whether surface supports volume type (below)
Reimplemented from searchableSurface.
Definition at line 165 of file searchableBox.H.
virtual volumeType outsideVolumeType () const inline virtual
What is type of points outside bounds.
Implements searchableSurface.
Definition at line 172 of file searchableBox.H.
virtual label size () const inline virtual
Range of local indices that can be returned.
Implements searchableSurface.
Definition at line 180 of file searchableBox.H.
Foam::tmp< Foam::pointField > coordinates () const virtual
Get representative set of element coordinates.
Usually the element centres (should be of length size()).
Implements searchableSurface.
Definition at line 228 of file searchableBox.C.
void boundingSpheres (pointField & centres, scalarField & radiusSqr) const virtual
Get bounding spheres (centre and radius squared), one per element.
Any point on element is guaranteed to be inside.
Implements searchableSurface.
Definition at line 246 of file searchableBox.C.
Foam::tmp< Foam::pointField > points () const virtual
Get the points that define the surface.
Implements searchableSurface.
Definition at line 280 of file searchableBox.C.
virtual bool overlaps (const boundBox & bb) const inline virtual
Does any part of the surface overlap the supplied bound box?
Implements searchableSurface.
Definition at line 209 of file searchableBox.H.
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Calculate nearest point on surface.
Returns
bool : any point found nearer than nearestDistSqr
label: relevant index in surface (=face 0..5)
point: actual nearest point found
Definition at line 287 of file searchableBox.C.
References treeBoundBox::points().
Foam::pointIndexHit findNearestOnEdge (const point & sample, const scalar nearestDistSqr) const
Calculate nearest point on edge.
Returns
bool : any point found nearer than nearestDistSqr
label: relevant index in surface(=?)
point: actual nearest point found
Definition at line 297 of file searchableBox.C.
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to segment.
Returns
bool : any point found?
label: relevant index in shapes (=face 0..5)
point: actual nearest point found sets:
tightest : bounding box
linePoint : corresponding nearest point on line
Definition at line 367 of file searchableBox.C.
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 379 of file searchableBox.C.
References NotImplemented.
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 442 of file searchableBox.C.
void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const virtual
Implements searchableSurface.
Definition at line 452 of file searchableBox.C.
References findLine().
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Implements searchableSurface.
Definition at line 470 of file searchableBox.C.
References i.
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Return any intersection on segment from start to end.
Implements searchableSurface.
Definition at line 486 of file searchableBox.C.
References findLine(), and i.
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit >> & info) const virtual
Get all intersections in order from start to end.
Implements searchableSurface.
Definition at line 502 of file searchableBox.C.
References i.
void getRegion (const List< pointIndexHit > & info, labelList & region) const virtual
From a set of points and indices get the region.
Implements searchableSurface.
Definition at line 570 of file searchableBox.C.
void getNormal (const List< pointIndexHit > & info, vectorField & normal) const virtual
From a set of points and indices get the normal.
Implements searchableSurface.
Definition at line 581 of file searchableBox.C.
void getVolumeType (const pointField & points, List< volumeType > & volType) const virtual
Determine type (inside/outside) for points.
Implements searchableSurface.
Definition at line 604 of file searchableBox.C.
bool writeData (Ostream &) const inline virtual
Pure virtual writeData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 344 of file searchableBox.H.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchableBox/searchableBox.H
src/meshTools/searchableSurfaces/searchableBox/searchableBox.C