OpenFOAM: ReactingParcel< ParcelType > Class Template Reference
ReactingParcel< ParcelType > Class Template Reference
Parcels
Reacting parcel class with one/two-way coupling with the continuous phase.
Classes
class constantProperties
Class to hold reacting parcel constant properties.
class iNew
Factory class to read-construct particles used for.
class trackingData
Public Member Functions
TypeName ("ReactingParcel")
Runtime type information.
AddToPropertyList (ParcelType," mass0"+" nPhases(Y1..YN)")
String representation of properties.
ReactingParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from mesh, coordinates and topology.
ReactingParcel (const polyMesh &mesh, const vector &position, const label celli)
Construct from a position and a cell, searching for the rest of the.
ReactingParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const constantProperties &constProps)
Construct from components.
ReactingParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
ReactingParcel (const ReactingParcel &p, const polyMesh &mesh)
Construct as a copy.
ReactingParcel (const ReactingParcel &p)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
scalar mass0 () const
Return const access to initial mass [kg].
const scalarField & Y () const
Return const access to mass fractions of mixture [].
scalar & mass0 ()
Return access to initial mass [kg].
scalarField & Y ()
Return access to mass fractions of mixture [].
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
Set cell values.
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
Correct cell values using latest transfer information.
template<class TrackCloudType >
void correctSurfaceValues (TrackCloudType &cloud, trackingData &td, const scalar T, const scalarField &Cs, scalar &rhos, scalar &mus, scalar &Prs, scalar &kappas)
Correct surface values due to emitted species.
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
Update parcel properties over the time interval.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
Write individual parcel properties to stream.
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
Read - composition supplied.
template<class CloudType >
static void readFields (CloudType &c)
Read - no composition.
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
Write - composition supplied.
template<class CloudType >
static void writeFields (const CloudType &c)
Write - no composition.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType , class CompositionType >
static void readObjects (CloudType &c, const CompositionType &compModel, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
template<class CloudType , class CompositionType >
static void writeObjects (const CloudType &c, const CompositionType &compModel, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields
Size in bytes of the fields.
Protected Member Functions
template<class TrackCloudType >
void calcPhaseChange (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar Pr, const scalar Ts, const scalar nus, const scalar d, const scalar T, const scalar mass, const label idPhase, const scalar YPhase, const scalarField &YComponents, scalarField &dMassPC, scalar &Sh, scalar &N, scalar &NCpW, scalarField &Cs)
Calculate Phase change.
scalar updateMassFraction (const scalar mass0, const scalarField &dMass, scalarField &Y) const
Update mass fraction.
Protected Attributes
scalar mass0_
Initial mass [kg].
scalarField Y_
Mass fractions of mixture [].
Friends
Ostream & operator (Ostream &, const ReactingParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingParcel< ParcelType >
Reacting parcel class with one/two-way coupling with the continuous phase.
Source files
ReactingParcel.H
ReactingParcelI.H
ReactingParcel.C
ReactingParcelIO.C
Definition at line 52 of file ReactingParcel.H.
Constructor & Destructor Documentation
ReactingParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Construct from mesh, coordinates and topology.
Other properties initialised as null
Definition at line 59 of file ReactingParcelI.H.
ReactingParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Construct from a position and a cell, searching for the rest of the.
required topology. Other properties are initialised as null.
Definition at line 75 of file ReactingParcelI.H.
ReactingParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const constantProperties & constProps) inline
Construct from components.
Definition at line 89 of file ReactingParcelI.H.
ReactingParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 43 of file ReactingParcelIO.C.
ReactingParcel (const ReactingParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
ReactingParcel (const ReactingParcel< ParcelType > & p)
Construct as a copy.
Member Function Documentation
void calcPhaseChange (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar Pr, const scalar Ts, const scalar nus, const scalar d, const scalar T, const scalar mass, const label idPhase, const scalar YPhase, const scalarField & YComponents, scalarField & dMassPC, scalar & Sh, scalar & N, scalar & NCpW, scalarField & Cs) protected
Calculate Phase change.
Definition at line 34 of file ReactingParcel.C.
References composition, Cp, forAll, i, Foam::min(), ReactingParcel< ParcelType >::trackingData::pc(), Foam::constant::thermodynamic::RR, and Foam::sum().
Foam::scalar updateMassFraction (const scalar mass0, const scalarField & dMass, scalarField & Y) const protected
Update mass fraction.
Definition at line 142 of file ReactingParcel.C.
TypeName ("ReactingParcel< ParcelType >")
Runtime type information.
AddToPropertyList (ParcelType , " mass0"+" nPhases(Y1..YN)")
String representation of properties.
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 349 of file ReactingParcel.H.
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 357 of file ReactingParcel.H.
Foam::scalar mass0 () const inline
Return const access to initial mass [kg].
Definition at line 153 of file ReactingParcelI.H.
const Foam::scalarField & Y () const inline
Return const access to mass fractions of mixture [].
Definition at line 160 of file ReactingParcelI.H.
Foam::scalar & mass0 () inline
Return access to initial mass [kg].
Definition at line 167 of file ReactingParcelI.H.
Foam::scalarField & Y () inline
Return access to mass fractions of mixture [].
Definition at line 174 of file ReactingParcelI.H.
void setCellValues (TrackCloudType & cloud, trackingData & td)
Set cell values.
Definition at line 195 of file ReactingParcel.C.
References coordinates(), Foam::expressions::patchExpr::debug, Foam::endl(), interpolation< class >::interpolate(), Foam::nl, ReactingParcel< ParcelType >::trackingData::pc(), ReactingParcel< ParcelType >::trackingData::pInterp(), and WarningInFunction.
void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Correct cell values using latest transfer information.
Definition at line 225 of file ReactingParcel.C.
void correctSurfaceValues (TrackCloudType & cloud, trackingData & td, const scalar T, const scalarField & Cs, scalar & rhos, scalar & mus, scalar & Prs, scalar & kappas)
Correct surface values due to emitted species.
Definition at line 281 of file ReactingParcel.C.
void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Update parcel properties over the time interval.
Definition at line 373 of file ReactingParcel.C.
void readFields (CloudType & c, const CompositionType & compModel) static
Read - composition supplied.
Definition at line 97 of file ReactingParcelIO.C.
void readFields (CloudType & c) static
Read - no composition.
Definition at line 88 of file ReactingParcelIO.C.
void writeFields (const CloudType & c, const CompositionType & compModel) static
Write - composition supplied.
Definition at line 172 of file ReactingParcelIO.C.
void writeFields (const CloudType & c) static
Write - no composition.
Definition at line 163 of file ReactingParcelIO.C.
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Write individual parcel properties to stream.
Definition at line 229 of file ReactingParcelIO.C.
void readObjects (CloudType & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
no composition
Definition at line 252 of file ReactingParcelIO.C.
void readObjects (CloudType & c, const CompositionType & compModel, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 276 of file ReactingParcelIO.C.
void writeObjects (const CloudType & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
no composition
Definition at line 264 of file ReactingParcelIO.C.
void writeObjects (const CloudType & c, const CompositionType & compModel, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Definition at line 324 of file ReactingParcelIO.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const ReactingParcel< ParcelType > &) friend
Member Data Documentation
const std::size_t sizeofFields static
Size in bytes of the fields.
Definition at line 76 of file ReactingParcel.H.
scalar mass0_ protected
Initial mass [kg].
Definition at line 204 of file ReactingParcel.H.
scalarField Y_ protected
Mass fractions of mixture [].
Definition at line 209 of file ReactingParcel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelIO.C