OpenFOAM: multivariateIndependentScheme< Type > Class Template Reference
multivariateIndependentScheme< Type > Class Template Reference
Generic multi-variate discretisation scheme class for which any of the NVD, CNVD or NVDV schemes may be selected for each variable and applied independently.
Public Member Functions
TypeName ("multivariateIndependent")
Runtime type information.
multivariateIndependentScheme (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct for field, faceFlux and Istream.
tmp
< surfaceInterpolationScheme
< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > &field) const
Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, multivariateSurfaceInterpolationScheme, Istream,(const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is),(mesh, fields, faceFlux, is))
multivariateSurfaceInterpolationScheme (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct for interpolating given field.
virtual ~multivariateSurfaceInterpolationScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
const fieldTable & fields () const
Return fields to be interpolated.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
static tmp
< multivariateSurfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type>
class Foam::multivariateIndependentScheme< Type >
Generic multi-variate discretisation scheme class for which any of the NVD, CNVD or NVDV schemes may be selected for each variable and applied independently.
This is equivalent to using separate "div" terms and schemes for each variable/equation.
Source files
multivariateIndependentScheme.H
multivariateIndependentScheme.C
Definition at line 54 of file multivariateIndependentScheme.H.
Constructor & Destructor Documentation
multivariateIndependentScheme (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData)
Construct for field, faceFlux and Istream.
Definition at line 32 of file multivariateIndependentScheme.C.
Member Function Documentation
TypeName ("multivariateIndependent")
Runtime type information.
tmp<surfaceInterpolationScheme<Type> > operator() (const GeometricField< Type, fvPatchField, volMesh > & field) const inline virtual
Implements multivariateSurfaceInterpolationScheme< Type >.
Definition at line 106 of file multivariateIndependentScheme.H.
References field(), dictionary::lookup(), DimensionedField< Type, GeoMesh >::mesh(), and surfaceInterpolationScheme< Type >::New().
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateIndependentScheme/multivariateIndependentScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateIndependentScheme/multivariateIndependentScheme.C