OpenFOAM: exprResult Class Reference
exprResult Class Reference
A polymorphic field/result from evaluating an expression.
Public Member Functions
TypeName ("exprResult")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, exprResult, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, exprResult, empty,(),())
exprResult ()
Construct null.
exprResult (const exprResult &expr)
Copy construct.
exprResult (exprResult &&expr)
Move construct.
exprResult (const dictionary &dict, const bool uniform=false, const bool needsValue=false)
Construct from a dictionary.
template<class Type >
exprResult (const Field< Type > &f)
Construct by copying a field.
template<class Type >
exprResult (Field< Type > &&f)
Construct by moving a field.
template<class Type >
exprResult (autoPtr< Type > &ap)
Construct for an IOobject.
template<class Type >
exprResult (autoPtr< Type > &&ap)
Construct for an IOobject.
template<class Type >
exprResult (const dimensioned< Type > &f)
Construct from a dimensioned value.
exprResult (const bool &val)
exprResult (const scalar &val)
exprResult (const vector &val)
exprResult (const tensor &val)
exprResult (const symmTensor &val)
exprResult (const sphericalTensor &val)
virtual autoPtr< exprResult > clone () const
Clone.
virtual ~exprResult ()
Destructor.
bool hasValue () const
Has a value?
const word & valueType () const
Basic type for the field or single value.
bool isPointValue (const bool isPointVal=true) const
True if representing point values, or test if same as isPointVal.
bool isUniform () const
True if single, uniform value.
template<class Type >
bool isType () const
True if valueType corresponds to the given Type.
bool isBool () const
True if valueType is a bool.
bool isObject () const
True if the object pointer is being used.
label size () const
The field or object size.
const void * dataAddress () const
The address of the field data content.
void clear ()
Clear (zero) the result.
void noReset ()
Change reset behaviour.
void allowReset ()
Change reset behaviour.
void testIfSingleValue (const bool parRun=Pstream::parRun())
Test if field corresponds to a single-value and thus uniform.
template<class Type >
void setResult (Field< Type > *, bool isPointVal=false)
Set result field, taking ownership of the pointer.
template<class Type >
void setResult (const Field< Type > &fld, bool isPointVal=false)
Set result field, taking copy of the field contents.
template<class Type >
void setResult (Field< Type > &&, bool isPointVal=false)
Set result field, moving field contents.
template<class Type >
void setResult (const Type &val, const label size)
Set uniform result field of given size.
template<class Type >
void setSingleValue (const Type &val)
Set single-value uniform result.
template<class Type >
void setObjectResult (autoPtr< Type > &o)
template<class Type >
void setObjectResult (autoPtr< Type > &&o)
template<class Type >
const Field< Type > & cref () const
Return const reference to the field.
template<class Type >
Field< Type > & ref ()
Return non-const reference to the field.
template<class Type >
Field< Type > & getRef () const
Return non-const reference to the field, casting away constness.
template<class Type >
tmp< Field< Type > > getResult (bool cacheCopy=false)
Return tmp field of the contents, optionally keeping a copy in cache.
template<class Type >
tmp< Type > getObjectResult (bool cacheCopy=false)
Get object result (Caution - potentially fragile) optionally keeping a copy in cache.
exprResult getUniform (const label size, const bool noWarn, const bool parRun=Pstream::parRun()) const
Construct a uniform field from the current results.
template<template< class > class BinaryOp, class Type >
Type getReduced (const BinaryOp< Type > &bop, const Type &initial=pTraits< Type >::zero)
Get a reduced result.
void writeEntry (const word &keyword, Ostream &os) const
Forwarding to Field::writeEntry.
void writeDict (Ostream &os, const bool subDict=true) const
Write entry as dictionary contents.
void writeValue (Ostream &os) const
Write the single value, or the first value from field.
virtual void operator= (const exprResult &rhs)
Copy assignment.
virtual void operator= (exprResult &&rhs)
Move assignment.
exprResult & operator*= (const scalar &b)
Scalar multiplication.
exprResult & operator+= (const exprResult &b)
Addition of results.
template<class T >
void setObjectResultImpl (T *ptr)
template<class T >
void setObjectResultImpl (autoPtr< T > &o)
template<class T >
void setObjectResultImpl (autoPtr< T > &&o)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool cacheCopy)
template<class Type >
const Foam::Field< Type > & cref () const
template<class Type >
Foam::Field< Type > & ref ()
template<class Type >
Foam::Field< Type > & getRef () const
template<class Type >
Foam::tmp< Type > getObjectResult (bool cacheCopy)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static autoPtr< exprResult > New (const dictionary &dict)
Return a reference to the selected value driver.
Static Public Attributes
static const exprResult null
An empty result.
Protected Member Functions
virtual exprResult & target ()
Simulate virtual templated methods.
virtual void resetImpl ()
Reset at new timestep according to the derived class type.
bool reset (bool force=false)
Reset at new timestep according to type.
void needsReset (bool val)
Adjusts the internal needsReset value.
Friends
class exprResultGlobals
Friendship with globals.
Detailed Description
A polymorphic field/result from evaluating an expression.
Dictionary parameters
Property Description Required Default
resultType The type of result no exprResult
unsetValue Create without reading the dictionary no false
noReset Suppress reset on time no false
When creating with values
Property Description Required Default
valueType Result value type (scalar, vector,..) yes
isSingleValue A single field value no false
isPointValue Interpret values as point values no false
value The field values yes
fieldSize The size of the field (when not single-value) no
Source files
exprResult.H
exprResult.C
exprResultI.H
Definition at line 124 of file exprResult.H.
Constructor & Destructor Documentation
exprResult ()
Construct null.
Definition at line 198 of file exprResult.C.
exprResult (const exprResult & expr)
Copy construct.
Definition at line 215 of file exprResult.C.
References clear().
exprResult (exprResult && expr)
Move construct.
Definition at line 223 of file exprResult.C.
exprResult (const dictionary & dict, const bool uniform = false, const bool needsValue = false) explicit
Construct from a dictionary.
Definition at line 232 of file exprResult.C.
exprResult (const Field< Type > & f)
Construct by copying a field.
Definition at line 186 of file exprResultI.H.
exprResult (Field< Type > && f)
Construct by moving a field.
Definition at line 197 of file exprResultI.H.
exprResult (autoPtr< Type > & ap)
Construct for an IOobject.
Definition at line 208 of file exprResultI.H.
exprResult (autoPtr< Type > && ap)
Construct for an IOobject.
Definition at line 217 of file exprResultI.H.
exprResult (const dimensioned< Type > & f)
Construct from a dimensioned value.
Definition at line 226 of file exprResultI.H.
exprResult (const bool & val) inline explicit
Construct from single value of bool
Definition at line 503 of file exprResult.H.
exprResult (const scalar & val) inline explicit
Construct from single value of scalar
Definition at line 504 of file exprResult.H.
exprResult (const vector & val) inline explicit
Construct from single value of vector
Definition at line 505 of file exprResult.H.
exprResult (const tensor & val) inline explicit
Construct from single value of tensor
Definition at line 506 of file exprResult.H.
exprResult (const symmTensor & val) inline explicit
Construct from single value of symmTensor
Definition at line 507 of file exprResult.H.
exprResult (const sphericalTensor & val) inline explicit
Construct from single value of sphericalTensor
Definition at line 508 of file exprResult.H.
~exprResult () virtual
Destructor.
Definition at line 348 of file exprResult.C.
Member Function Documentation
virtual exprResult& target () inline protected virtual
Simulate virtual templated methods.
Reimplemented in exprResultDelayed.
Definition at line 380 of file exprResult.H.
void resetImpl () protected virtual
Reset at new timestep according to the derived class type.
Reimplemented in exprResultStored, and exprResultStoredStack.
Definition at line 358 of file exprResult.C.
bool reset (bool force = false) protected
Reset at new timestep according to type.
Returns
true if it was actually reset
Definition at line 364 of file exprResult.C.
References clear().
void needsReset (bool val) inline protected
Adjusts the internal needsReset value.
Definition at line 397 of file exprResult.H.
TypeName ("exprResult")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , exprResult , dictionary , (const dictionary &dict) , (dict))
declareRunTimeSelectionTable (autoPtr , exprResult , empty , () , ())
Foam::autoPtr< Foam::expressions::exprResult > New (const dictionary & dict) static
Return a reference to the selected value driver.
Definition at line 297 of file exprResult.C.
virtual autoPtr<exprResult> clone () const inline virtual
Clone.
Reimplemented in exprResultDelayed, exprResultStored, exprResultStack, and exprResultStoredStack.
Definition at line 523 of file exprResult.H.
bool hasValue () const inline
Has a value?
Definition at line 237 of file exprResultI.H.
Referenced by Foam::stringOps::evaluate().
const Foam::word & valueType () const inline
Basic type for the field or single value.
Definition at line 243 of file exprResultI.H.
bool isPointValue (const bool isPointVal = true) const inline
True if representing point values, or test if same as isPointVal.
Definition at line 250 of file exprResultI.H.
Referenced by parseDriver::getField(), and parseDriver::getVariableIfAvailable().
bool isUniform () const inline
True if single, uniform value.
Definition at line 258 of file exprResultI.H.
Referenced by parseDriver::getField(), and parseDriver::getVariableIfAvailable().
bool isType () const inline
True if valueType corresponds to the given Type.
Definition at line 265 of file exprResultI.H.
bool isBool () const inline
True if valueType is a bool.
Definition at line 271 of file exprResultI.H.
bool isObject () const inline
True if the object pointer is being used.
Definition at line 277 of file exprResultI.H.
Foam::label size () const inline
The field or object size.
Definition at line 283 of file exprResultI.H.
Referenced by Foam::stringOps::evaluate().
const void * dataAddress () const
The address of the field data content.
Fatal for unknown types. Used, for example, for python integration
Definition at line 818 of file exprResult.C.
void clear ()
Clear (zero) the result.
Definition at line 376 of file exprResult.C.
void noReset () inline
Change reset behaviour.
Definition at line 599 of file exprResult.H.
void allowReset () inline
Change reset behaviour.
Definition at line 604 of file exprResult.H.
void testIfSingleValue (const bool parRun = Pstream::parRun())
Test if field corresponds to a single-value and thus uniform.
Uses field min/max to establish uniformity. Test afterwards with isUniform()
Definition at line 452 of file exprResult.C.
void setResult (Field< Type > * fldPtr, bool isPointVal = false) inline
Set result field, taking ownership of the pointer.
Definition at line 403 of file exprResultI.H.
Referenced by parseDriver::pointSize(), and parseDriver::setInternalFieldResult().
void setResult (const Field< Type > & fld, bool isPointVal = false) inline
Set result field, taking copy of the field contents.
Definition at line 291 of file exprResultI.H.
void setResult (Field< Type > && val, bool isPointVal = false) inline
Set result field, moving field contents.
Definition at line 304 of file exprResultI.H.
void setResult (const Type & val, const label size) inline
Set uniform result field of given size.
Definition at line 434 of file exprResultI.H.
void setSingleValue (const Type & val) inline
Set single-value uniform result.
Definition at line 466 of file exprResultI.H.
void setObjectResult (autoPtr< Type > & o) inline
Definition at line 360 of file exprResultI.H.
void setObjectResult (autoPtr< Type > && o) inline
Definition at line 367 of file exprResultI.H.
References autoPtr< T >::ptr().
const Field<Type>& cref () const inline
Return const reference to the field.
Referenced by parseDriver::getField(), and parseDriver::getVariableIfAvailable().
Field<Type>& ref () inline
Return non-const reference to the field.
Field<Type>& getRef () const inline
Return non-const reference to the field, casting away constness.
tmp<Field<Type> > getResult (bool cacheCopy = false) inline
Return tmp field of the contents, optionally keeping a copy in cache.
tmp<Type> getObjectResult (bool cacheCopy = false) inline
Get object result (Caution - potentially fragile) optionally keeping a copy in cache.
Foam::expressions::exprResult getUniform (const label size, const bool noWarn, const bool parRun = Pstream::parRun()) const
Construct a uniform field from the current results.
Uses the field average. Optionally warning if the min/max deviation is larger than SMALL.
Definition at line 417 of file exprResult.C.
Referenced by exprDriver::addVariables().
Type getReduced (const BinaryOp< Type > & bop, const Type & initial = pTraits<Type>::zero) inline
Get a reduced result.
Definition at line 787 of file exprResultI.H.
void writeEntry (const word & keyword, Ostream & os) const
Forwarding to Field::writeEntry.
Definition at line 550 of file exprResult.C.
void writeDict (Ostream & os, const bool subDict = true) const
Write entry as dictionary contents.
Definition at line 574 of file exprResult.C.
void writeValue (Ostream & os) const
Write the single value, or the first value from field.
Definition at line 632 of file exprResult.C.
Referenced by Foam::stringOps::evaluate().
void operator= (const exprResult & rhs) virtual
Copy assignment.
Reimplemented in exprResultDelayed, exprResultStored, and exprResultStack.
Definition at line 479 of file exprResult.C.
References Foam::endl(), and WarningInFunction.
Referenced by exprResultDelayed::storeValue().
void operator= (exprResult && rhs) virtual
Move assignment.
Reimplemented in exprResultDelayed.
Definition at line 523 of file exprResult.C.
Foam::expressions::exprResult & operator*= (const scalar & b)
Scalar multiplication.
Definition at line 666 of file exprResult.C.
Foam::expressions::exprResult & operator+= (const exprResult & b)
Addition of results.
Definition at line 707 of file exprResult.C.
void setObjectResultImpl (T * ptr)
Definition at line 374 of file exprResultI.H.
void setObjectResultImpl (autoPtr< T > & o)
Definition at line 388 of file exprResultI.H.
void setObjectResultImpl (autoPtr< T > && o)
Definition at line 395 of file exprResultI.H.
References autoPtr< T >::ptr().
Foam::tmp<Foam::Field<Type> > getResult (bool cacheCopy) inline
Definition at line 662 of file exprResultI.H.
const Foam::Field<Type>& cref () const inline
Definition at line 704 of file exprResultI.H.
Foam::Field<Type>& ref () inline
Definition at line 731 of file exprResultI.H.
Foam::Field<Type>& getRef () const inline
Definition at line 739 of file exprResultI.H.
Foam::tmp<Type> getObjectResult (bool cacheCopy) inline
Definition at line 747 of file exprResultI.H.
Friends And Related Function Documentation
friend class exprResultGlobals friend
Friendship with globals.
Definition at line 410 of file exprResult.H.
Member Data Documentation
const Foam::expressions::exprResult null static
An empty result.
Definition at line 405 of file exprResult.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprResult/exprResult.H
src/OpenFOAM/expressions/exprResult/exprResult.C
src/OpenFOAM/expressions/exprResult/exprResultI.H