OpenFOAM: phaseTransferModel Class Reference
phaseTransferModel Class Reference abstract
Public Member Functions
TypeName ("phaseTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, phaseTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
phaseTransferModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~phaseTransferModel ()
Destructor.
virtual tmp< volScalarField > dmdt () const =0
The mass transfer rate.
Static Public Member Functions
static autoPtr
< phaseTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimDmdt
Mass transfer rate dimensions.
Protected Attributes
const phasePair & pair_
Phase pair.
Detailed Description
Source files
phaseTransferModel.H
phaseTransferModel.C
Definition at line 49 of file phaseTransferModel.H.
Constructor & Destructor Documentation
phaseTransferModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
Definition at line 41 of file phaseTransferModel.C.
~phaseTransferModel () virtual
Destructor.
Definition at line 52 of file phaseTransferModel.C.
Member Function Documentation
TypeName ("phaseTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , phaseTransferModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::phaseTransferModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 28 of file newPhaseTransferModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volScalarField> dmdt () const pure virtual
The mass transfer rate.
Implemented in deposition.
Member Data Documentation
const phasePair& pair_ protected
Phase pair.
Definition at line 58 of file phaseTransferModel.H.
const Foam::dimensionSet dimDmdt static
Initial value:
=
    Foam::dimDensity/Foam::dimTime
Mass transfer rate dimensions.
Definition at line 89 of file phaseTransferModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialModels/phaseTransferModels/phaseTransferModel/phaseTransferModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialModels/phaseTransferModels/phaseTransferModel/newPhaseTransferModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialModels/phaseTransferModels/phaseTransferModel/phaseTransferModel.C