OpenFOAM: slidingInterface Class Reference
slidingInterface Class Reference
Sliding interface mesh modifier. Given two face zones, couple the master and slave side using a cutting procedure.
Public Types
enum typeOfMatch { INTEGRAL, PARTIAL }
Type of match.
Public Member Functions
TypeName ("slidingInterface")
Runtime type information.
slidingInterface (const word &name, const label index, const polyTopoChanger &mme, const word &masterFaceZoneName, const word &slaveFaceZoneName, const word &cutPointZoneName, const word &cutFaceZoneName, const word &masterPatchName, const word &slavePatchName, const typeOfMatch tom, const bool coupleDecouple=false, const intersection::algorithm algo=intersection::VISIBLE)
Construct from components.
slidingInterface (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Construct from dictionary.
virtual ~slidingInterface ()
Destructor.
const faceZoneID & masterFaceZoneID () const
Return master face zone ID.
const faceZoneID & slaveFaceZoneID () const
Return slave face zone ID.
bool attached () const
Return true if attached.
virtual bool changeTopology () const
Check for topology change.
virtual void setRefinement (polyTopoChange &) const
Insert the layer addition/removal instructions.
virtual void modifyMotionPoints (pointField &motionPoints) const
Modify motion points to comply with the topological change.
virtual void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
const pointField & pointProjection () const
Return projected points for a slave patch.
void setTolerances (const dictionary &, bool report=false)
Set the tolerances from the values in a dictionary.
virtual void write (Ostream &) const
Write.
virtual void writeDict (Ostream &) const
Write dictionary.
Public Member Functions inherited from polyMeshModifier
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
Construct from components.
virtual ~polyMeshModifier ()
Destructor.
const word & name () const
Return name of this modifier.
label index () const
Return the index of this modifier.
const polyTopoChanger & topoChanger () const
Return reference to morph engine.
const Switch & active () const
void enable () const
Activate mesh modifier.
void disable () const
Activate mesh modifier.
Static Public Attributes
static const Enum< typeOfMatch > typeOfMatchNames
Names for the types of matches.
Additional Inherited Members
Static Public Member Functions inherited from polyMeshModifier
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Select constructed from dictionary.
Detailed Description
Sliding interface mesh modifier. Given two face zones, couple the master and slave side using a cutting procedure.
The coupled faces are collected into the "coupled" zone and can become either internal or placed into a master and slave coupled zone. The remaining faces (uncovered master or slave) are placed into the master and slave patch.
The definition of the sliding interface can be either integral or partial. Integral interface implies that the slave side completely covers the master (i.e. no faces are uncovered); partial interface implies that the uncovered part of master/slave face zone should become boundary faces.
Source files
slidingInterface.H
slidingInterface.C
coupleSlidingInterface.C
decoupleSlidingInterface.C
slidingInterfaceProjectPoints.C
slidingInterfaceAttachedAddressing.C
slidingInterfaceClearCouple.C
Definition at line 69 of file slidingInterface.H.
Member Enumeration Documentation
enum typeOfMatch
Type of match.
Enumerator
INTEGRAL
PARTIAL
Definition at line 80 of file slidingInterface.H.
Constructor & Destructor Documentation
slidingInterface (const word & name, const label index, const polyTopoChanger & mme, const word & masterFaceZoneName, const word & slaveFaceZoneName, const word & cutPointZoneName, const word & cutFaceZoneName, const word & masterPatchName, const word & slavePatchName, const typeOfMatch tom, const bool coupleDecouple = false, const intersection::algorithm algo = intersection::VISIBLE)
Construct from components.
Definition at line 111 of file slidingInterface.C.
slidingInterface (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme)
Construct from dictionary.
Definition at line 201 of file slidingInterface.C.
~slidingInterface () virtual
Destructor.
Definition at line 300 of file slidingInterface.C.
Member Function Documentation
TypeName ("slidingInterface")
Runtime type information.
const Foam::faceZoneID & masterFaceZoneID () const
Return master face zone ID.
Definition at line 315 of file slidingInterface.C.
const Foam::faceZoneID & slaveFaceZoneID () const
Return slave face zone ID.
Definition at line 321 of file slidingInterface.C.
bool attached () const inline
Return true if attached.
Definition at line 498 of file slidingInterface.H.
bool changeTopology () const virtual
Check for topology change.
Implements polyMeshModifier.
Definition at line 327 of file slidingInterface.C.
void setRefinement (polyTopoChange & ref) const virtual
Insert the layer addition/removal instructions.
into the topological change
Implements polyMeshModifier.
Definition at line 368 of file slidingInterface.C.
void modifyMotionPoints (pointField & motionPoints) const virtual
Modify motion points to comply with the topological change.
Implements polyMeshModifier.
Definition at line 401 of file slidingInterface.C.
void updateMesh (const mapPolyMesh & m) virtual
Force recalculation of locally stored data on topological change.
Implements polyMeshModifier.
Definition at line 632 of file slidingInterface.C.
References Foam::endl(), and Foam::Pout.
const Foam::pointField & pointProjection () const
Return projected points for a slave patch.
Definition at line 664 of file slidingInterface.C.
void setTolerances (const dictionary & dict, bool report = false)
Set the tolerances from the values in a dictionary.
Definition at line 674 of file slidingInterface.C.
void write (Ostream & os) const virtual
Write.
Implements polyMeshModifier.
Definition at line 732 of file slidingInterface.C.
void writeDict (Ostream & os) const virtual
Write dictionary.
Implements polyMeshModifier.
Definition at line 756 of file slidingInterface.C.
References intersection::algorithmNames_, Ostream::beginBlock(), Ostream::endBlock(), Foam::name(), Foam::nl, Foam::type(), WRITE_NON_DEFAULT, and Ostream::writeEntry().
Member Data Documentation
const Foam::Enum< Foam::slidingInterface::typeOfMatch > typeOfMatchNames static
Names for the types of matches.
Definition at line 89 of file slidingInterface.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/slidingInterface/slidingInterface.H
src/dynamicMesh/slidingInterface/coupleSlidingInterface.C
src/dynamicMesh/slidingInterface/decoupleSlidingInterface.C
src/dynamicMesh/slidingInterface/slidingInterface.C
src/dynamicMesh/slidingInterface/slidingInterfaceAttachedAddressing.C
src/dynamicMesh/slidingInterface/slidingInterfaceClearCouple.C
src/dynamicMesh/slidingInterface/slidingInterfaceProjectPoints.C