OpenFOAM: removeFaces Class Reference
removeFaces Class Reference
Given list of faces to remove insert all the topology changes. Contains helper function to get consistent set of faces to remove.
Public Member Functions
ClassName ("removeFaces")
Runtime type information.
removeFaces (const polyMesh &, const scalar minCos)
Construct from mesh and min cos of angle for boundary faces.
label compatibleRemoves (const labelList &inPiercedFaces, labelList &cellRegion, labelList &cellRegionMaster, labelList &outPiercedFaces) const
Find faces including those with cells which have the same mastercell.
void setRefinement (const labelList &piercedFaces, const labelList &cellRegion, const labelList &cellRegionMaster, polyTopoChange &) const
Play commands into polyTopoChange to remove faces.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
void distribute (const mapDistributePolyMesh &)
Force recalculation of locally stored data for mesh distribution.
Detailed Description
Given list of faces to remove insert all the topology changes. Contains helper function to get consistent set of faces to remove.
Not very well tested in parallel.
Source files
removeFaces.H
removeFaces.C
Definition at line 60 of file removeFaces.H.
Constructor & Destructor Documentation
removeFaces (const polyMesh & mesh, const scalar minCos)
Construct from mesh and min cos of angle for boundary faces.
to be considered aligned. Set to >= 1 to disable checking and always merge (if on same patch)
Definition at line 556 of file removeFaces.C.
Member Function Documentation
ClassName ("removeFaces")
Runtime type information.
Foam::label compatibleRemoves (const labelList & inPiercedFaces, labelList & cellRegion, labelList & cellRegionMaster, labelList & outPiercedFaces) const
Find faces including those with cells which have the same mastercell.
Given set of faces to pierce calculates:
region for connected cells
mastercell for each region. This is the lowest numbered cell of all cells that get merged.
new set of faces which contains input set + additional ones where cells on both sides would have same mastercell. Returns number of regions.
Definition at line 575 of file removeFaces.C.
References Foam::abort(), List< T >::append(), Foam::FatalError, FatalErrorInFunction, forAll, i, Foam::min(), List< T >::setSize(), UList< T >::size(), and Foam::Zero.
void setRefinement (const labelList & piercedFaces, const labelList & cellRegion, const labelList & cellRegionMaster, polyTopoChange & meshMod) const
Play commands into polyTopoChange to remove faces.
Definition at line 756 of file removeFaces.C.
void updateMesh (const mapPolyMesh &) inline
Force recalculation of locally stored data on topological change.
Definition at line 243 of file removeFaces.H.
void distribute (const mapDistributePolyMesh &) inline
Force recalculation of locally stored data for mesh distribution.
Definition at line 249 of file removeFaces.H.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/removeFaces.H
src/dynamicMesh/polyTopoChange/polyTopoChange/removeFaces.C