OpenFOAM: exprString Class Reference
exprString Class Reference
Public Member Functions
exprString ()=default
Construct null.
exprString (const exprString &rhs)=default
Copy construct.
exprString (exprString &&rhs)=default
Move construct.
exprString (const std::string &s, bool doValidate=true)
Copy construct from std::string.
exprString (std::string &&s, bool doValidate=true)
Move construct from std::string.
exprString (const char *s, bool doValidate=true)
Construct as copy of character array.
exprString (const std::string &str, const dictionary &dict, const bool stripComments=true)
Copy construct and expand with dictionary variables, and strip C/C++ comments from the input.
exprString (std::string &&str, const dictionary &dict, const bool stripComments=true)
Move construct and expand with dictionary variables, and strip C/C++ comments from the input.
exprString (Istream &is, const dictionary &dict, const bool stripComments=true)
Construct from Istream and expand with dictionary variables, and strip C/C++ comments from the input.
~exprString ()=default
Destructor.
exprString & expand (const dictionary &dict, const bool stripComments=true)
Inplace expansion with dictionary variables, and strip C/C++ comments from the input.
bool valid () const
Check for unexpanded '$' entries. Fatal if any exist.
exprString & operator= (const exprString &str)=default
Copy assign.
exprString & operator= (exprString &&str)=default
Move assign.
exprString & operator= (const char *str)
Copy assign from c-string. No expansions, no comment stripping.
exprString & operator= (const std::string &str)
Copy assign from string. No expansions, no comment stripping.
exprString & operator= (std::string &&str)
Move assign from string. No expansions, no comment stripping.
Public Member Functions inherited from string
string ()=default
Construct null.
string (const std::string &str)
Copy construct from std::string.
string (std::string &&str)
Move construct from std::string.
string (const char *str)
Construct as copy of character array.
string (const char *str, const size_type len)
Construct as copy with a maximum number of characters.
string (const char c)
Construct from a single character.
string (const size_type len, const char c)
Construct fill copies of a single character.
string (Istream &is)
Construct from Istream.
bool match (const std::string &text) const
Test for equality.
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
Replace first occurrence of sub-string s1 with s2, beginning at pos.
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
Replace all occurrences of sub-string s1 with s2, beginning at pos in the string.
string & expand (const bool allowEmpty=false)
Inplace expand initial tags, tildes, and all occurrences of environment variables as per stringOps::expand.
bool removeRepeated (const char character)
Remove repeated characters.
bool removeStart (const std::string &text)
Remove the given text from the start of the string.
bool removeStart (const char c)
Remove leading character, unless string is a single character.
bool removeEnd (const std::string &text)
Remove the given text from the end of the string.
bool removeEnd (const char c)
Remove trailing character, unless string is a single character.
void swap (std::string &str)
Swap contents. Self-swapping is a no-op.
bool operator() (const std::string &text) const
Test for equality. Allows use as a predicate.
bool starts_with (const std::string &s) const
True if string starts with the given prefix (cf. C++20)
bool starts_with (const char c) const
True if string starts with the given character (cf. C++20)
bool ends_with (const std::string &s) const
True if string ends with the given suffix (cf. C++20)
bool ends_with (const char c) const
True if string ends with the given character (cf. C++20)
size_type count (const char c) const
Count the number of occurrences of the specified character in the string.
bool startsWith (const std::string &s) const
Deprecated(2019-11)
bool endsWith (const std::string &s) const
Deprecated(2019-11)
bool removeTrailing (const char c)
Deprecated(2019-11)
template<class String >
Foam::string quotemeta (const std::string &str, const char quote)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Static Public Member Functions
static void inplaceExpand (std::string &str, const dictionary &dict, const bool stripComments=true)
Inplace expansion with dictionary variables, and strip C/C++ comments from the input.
static exprString getExpression (const word &name, const dictionary &dict, const bool stripComments=false)
Get and expand expression with dictionary entries, optionally strip C/C++ comments from the input.
static exprString toExpr (const std::string &str)
Copy convert string to exprString.
static exprString toExpr (std::string &&str)
Move convert string to exprString.
Static Public Member Functions inherited from string
template<class String >
static bool valid (const std::string &str)
Does the string contain valid characters only?
template<class String >
static bool meta (const std::string &str, const char quote='\\')
Does this string contain meta-characters?
template<class String >
static bool stripInvalid (std::string &str)
Strip invalid characters from the given string.
template<class String >
static String validate (const std::string &str)
Return a valid String from the given string.
template<class String >
static string quotemeta (const std::string &str, const char quote= '\\')
Return a String with quoted meta-characters from the given string.
Additional Inherited Members
Static Public Attributes inherited from string
static const char *const typeName = "string"
The type name "string".
static int debug
The debug flag.
static const string null
An empty string.
Protected Member Functions inherited from string
std::string::size_type find_ext () const
Find position of a file extension dot, return npos on failure.
word ext () const
Return file name extension (part after last .)
bool ext (const word &ending)
Append a '.' and the ending.
bool hasPath () const
Return true if it contains a '/' character.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
bool removePath ()
Remove leading path, returning true if string changed.
Static Protected Member Functions inherited from string
static std::string::size_type find_ext (const std::string &str)
Find position of a file extension dot, return npos on failure.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
Detailed Description
Definition at line 56 of file exprString.H.
Constructor & Destructor Documentation
exprString () default
Construct null.
exprString (const exprString & rhs) default
Copy construct.
exprString (exprString && rhs) default
Move construct.
exprString (const std::string & s, bool doValidate = true) inline explicit
Copy construct from std::string.
Definition at line 27 of file exprStringI.H.
exprString (std::string && s, bool doValidate = true) inline explicit
Move construct from std::string.
Definition at line 44 of file exprStringI.H.
exprString (const char * s, bool doValidate = true) inline explicit
Construct as copy of character array.
Definition at line 61 of file exprStringI.H.
exprString (const std::string & str, const dictionary & dict, const bool stripComments = true) inline
Copy construct and expand with dictionary variables, and strip C/C++ comments from the input.
Definition at line 78 of file exprStringI.H.
exprString (std::string && str, const dictionary & dict, const bool stripComments = true) inline
Move construct and expand with dictionary variables, and strip C/C++ comments from the input.
Definition at line 91 of file exprStringI.H.
References Foam::stringOps::expand().
exprString (Istream & is, const dictionary & dict, const bool stripComments = true) inline
Construct from Istream and expand with dictionary variables, and strip C/C++ comments from the input.
Definition at line 104 of file exprStringI.H.
References Foam::stringOps::expand().
~exprString () default
Destructor.
Member Function Documentation
void inplaceExpand (std::string & str, const dictionary & dict, const bool stripComments = true) static
Inplace expansion with dictionary variables, and strip C/C++ comments from the input.
Expansion behaviour
alternatives = True
environment = True
allow empty = True
subDict = False
Definition at line 28 of file exprString.C.
References Foam::stringOps::inplaceRemoveComments().
Foam::expressions::exprString getExpression (const word & name, const dictionary & dict, const bool stripComments = false) static
Get and expand expression with dictionary entries, optionally strip C/C++ comments from the input.
Expansion behaviour as per inplaceExpand
Definition at line 45 of file exprString.C.
Foam::expressions::exprString toExpr (const std::string & str) inline static
Copy convert string to exprString.
No expansions, know what you are doing.
Definition at line 136 of file exprStringI.H.
Foam::expressions::exprString toExpr (std::string && str) inline static
Move convert string to exprString.
No expansions, know what you are doing.
Definition at line 147 of file exprStringI.H.
Foam::expressions::exprString & expand (const dictionary & dict, const bool stripComments = true)
Inplace expansion with dictionary variables, and strip C/C++ comments from the input.
Definition at line 67 of file exprString.C.
bool valid () const inline
Check for unexpanded '$' entries. Fatal if any exist.
Definition at line 118 of file exprStringI.H.
References Foam::stringOps::expand().
exprString& operator= (const exprString & str) default
Copy assign.
exprString& operator= (exprString && str) default
Move assign.
Foam::expressions::exprString & operator= (const char * str) inline
Copy assign from c-string. No expansions, no comment stripping.
Definition at line 160 of file exprStringI.H.
Foam::expressions::exprString & operator= (const std::string & str) inline
Copy assign from string. No expansions, no comment stripping.
Definition at line 173 of file exprStringI.H.
Foam::expressions::exprString & operator= (std::string && str) inline
Move assign from string. No expansions, no comment stripping.
Definition at line 186 of file exprStringI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprString/exprString.H
src/OpenFOAM/expressions/exprString/exprString.C
src/OpenFOAM/expressions/exprString/exprStringI.H