OpenFOAM: externalFileCoupler Class Reference
externalFileCoupler Class Reference
Encapsulates the logic for coordinating between OpenFOAM and an external application.
Public Types
enum runState { NONE, MASTER, SLAVE, DONE }
The run state (ie, who is currently in charge)
Public Member Functions
TypeName ("externalFileCoupler")
Runtime type information.
externalFileCoupler ()
Construct using standard defaults.
externalFileCoupler (const fileName &commsDir)
Construct with specified communications directory.
externalFileCoupler (const dictionary &dict)
Construct from dictionary.
virtual ~externalFileCoupler ()
Destructor.
bool initialized () const
True if state has been initialized.
bool slaveFirst () const
External application provides initial values.
const fileName & commDirectory () const
Return the file path to the base communications directory.
fileName resolveFile (const word &file) const
Return the file path in the communications directory.
fileName lockFile () const
Return the file path to the lock file.
bool readDict (const dictionary &dict)
Read communication settings from dictionary.
enum Time::stopAtControls useMaster (const bool wait=false) const
Create lock file to indicate that OpenFOAM is in charge.
enum Time::stopAtControls useSlave (const bool wait=false) const
Remove lock file to indicate that the external program is in charge.
enum Time::stopAtControls waitForMaster () const
Wait for master to complete.
enum Time::stopAtControls waitForSlave () const
Wait for slave to complete.
virtual void readDataMaster ()
Read data files on master (OpenFOAM).
virtual void readDataSlave ()
Read data files on slave (external program).
virtual void writeDataMaster () const
Write data files from master (OpenFOAM)
virtual void writeDataSlave () const
Write data files from slave (external program)
virtual void removeDataMaster () const
Remove data files written by master (OpenFOAM)
virtual void removeDataSlave () const
Remove data files written by slave (external program)
void shutdown () const
Generate status=done in lock (only when run-state = master)
void removeDirectory () const
Remove files written by OpenFOAM.
Static Public Attributes
static word lockName = "OpenFOAM"
Name of the lock file.
Detailed Description
Encapsulates the logic for coordinating between OpenFOAM and an external application.
This class provides a simple interface for explicit coupling with an external application using plain text files located in the user-specified communications directory. These files are to be read/written on the master processor only.
The explicit coupling follows a master/slave model in which OpenFOAM is the 'master' and the external application is the 'slave'. The readiness to exchange information in either direction is handled by a lock file (ie, OpenFOAM.lock). If the lock file is present, the slave (external application) should wait for the master (OpenFOAM) to complete.
When the master is finished its tasks and has prepared data for the slave, the lock file is removed, instructing the external source to take control of the program execution.
When the slave has completed its tasks, it will reinstate the lock file.
Example of the communication specification:
communication
{
    commsDir        "<case>/comms";
    waitInterval    1;
    timeOut         100;
    initByExternal  no;
    statusDone      done;
}
A typical coupling loop would look like this (on the master-side):
    initialize - master takes control
    writeDataMaster() - write data for slave
    useSlave()
    waitForSlave()
    removeDataMaster() - cleanup old data from master [optional?]
    readDataMaster() - read data from slave
    useMaster()
On the slave-side:
    waitForMaster()
    readDataSlave()  - read data from master
    writeDataSlave() - write data for master
    useMaster()
Note that since the waitForSlave() method not only waits for the lock file to be reinstated but also does a simple check of its contents, it can also serve to communicate some control from the slave to the master.
Source files
externalFileCoupler.H
externalFileCoupler.C
externalFileCouplerI.H
Definition at line 103 of file externalFileCoupler.H.
Member Enumeration Documentation
enum runState
The run state (ie, who is currently in charge)
Enumerator
NONE
Not initialized.
MASTER
The master (OpenFOAM) is in charge.
SLAVE
The slave (external program) is in charge.
DONE
Finished.
Definition at line 112 of file externalFileCoupler.H.
Constructor & Destructor Documentation
externalFileCoupler ()
Construct using standard defaults.
Does not create communications directory.
Definition at line 88 of file externalFileCoupler.C.
externalFileCoupler (const fileName & commsDir)
Construct with specified communications directory.
Creates the communications directory upon construction.
Definition at line 103 of file externalFileCoupler.C.
externalFileCoupler (const dictionary & dict)
Construct from dictionary.
Creates the communications directory upon construction.
Definition at line 123 of file externalFileCoupler.C.
References Foam::mkDir().
~externalFileCoupler () virtual
Destructor.
Definition at line 138 of file externalFileCoupler.C.
Member Function Documentation
TypeName ("externalFileCoupler")
Runtime type information.
bool initialized () const inline
True if state has been initialized.
Definition at line 23 of file externalFileCouplerI.H.
bool slaveFirst () const inline
External application provides initial values.
Definition at line 29 of file externalFileCouplerI.H.
References externalFileCoupler::NONE.
Referenced by externalCoupled::externalCoupled().
const Foam::fileName & commDirectory () const inline
Return the file path to the base communications directory.
Definition at line 35 of file externalFileCouplerI.H.
Foam::fileName resolveFile (const word & file) const inline
Return the file path in the communications directory.
Definition at line 42 of file externalFileCouplerI.H.
Foam::fileName lockFile () const inline
Return the file path to the lock file.
Definition at line 50 of file externalFileCouplerI.H.
bool readDict (const dictionary & dict)
Read communication settings from dictionary.
Definition at line 146 of file externalFileCoupler.C.
enum Foam::Time::stopAtControls useMaster (const bool wait = false) const
Create lock file to indicate that OpenFOAM is in charge.
Parameters
wait - wait for master to complete.
Returns
Time::stopAtControls::saUnknown if not waiting, otherwise as per the waitForMaster() description.
Definition at line 179 of file externalFileCoupler.C.
Referenced by externalCoupled::externalCoupled().
enum Foam::Time::stopAtControls useSlave (const bool wait = false) const
Remove lock file to indicate that the external program is in charge.
Parameters
wait - wait for slave to complete.
Returns
Time::stopAtControls::saUnknown if not waiting, otherwise as per the waitForSlave() description.
Definition at line 215 of file externalFileCoupler.C.
enum Foam::Time::stopAtControls waitForMaster () const
Wait for master to complete.
This is when the lock file disappears, or exists but has status=done content.
Returns
Time::stopAtControls::saUnknown or if lock file contained status=done it returns Time::stopAtControls::saEndTime
Definition at line 243 of file externalFileCoupler.C.
enum Foam::Time::stopAtControls waitForSlave () const
Wait for slave to complete.
This is when the lock file appears.
When the lock file appears, it is checked for the following content which corresponds to particular return values:
status=done
Returns
Foam::Time::saEndTime
action=noWriteNow
Returns
Foam::Time::saNoWriteNow
action=writeNow
Returns
Foam::Time::saWriteNow
action=nextWrite
Returns
Foam::Time::saNextWrite
Anything else (empty file, no action= or status=, etc)
Returns
Foam::Time::saUnknown
Definition at line 287 of file externalFileCoupler.C.
void readDataMaster () virtual
Read data files on master (OpenFOAM).
These data files are normally created by the slave.
Reimplemented in externalCoupled.
Definition at line 330 of file externalFileCoupler.C.
void readDataSlave () virtual
Read data files on slave (external program).
These data files are normally created by the master.
Definition at line 334 of file externalFileCoupler.C.
void writeDataMaster () const virtual
Write data files from master (OpenFOAM)
Reimplemented in externalCoupled.
Definition at line 338 of file externalFileCoupler.C.
void writeDataSlave () const virtual
Write data files from slave (external program)
Definition at line 342 of file externalFileCoupler.C.
void removeDataMaster () const virtual
Remove data files written by master (OpenFOAM)
Reimplemented in externalCoupled.
Definition at line 346 of file externalFileCoupler.C.
void removeDataSlave () const virtual
Remove data files written by slave (external program)
Reimplemented in externalCoupled.
Definition at line 350 of file externalFileCoupler.C.
void shutdown () const
Generate status=done in lock (only when run-state = master)
The exact text can be specified via the statusDone keyword
Definition at line 354 of file externalFileCoupler.C.
void removeDirectory () const
Remove files written by OpenFOAM.
Member Data Documentation
Foam::word lockName = "OpenFOAM" static
Name of the lock file.
Definition at line 186 of file externalFileCoupler.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/coupling/externalFileCoupler.H
src/finiteVolume/cfdTools/general/coupling/externalFileCoupler.C
src/finiteVolume/cfdTools/general/coupling/externalFileCouplerI.H