OpenFOAM: TimePaths Class Reference
TimePaths Class Reference
Address the time paths without using the Time class.
Public Member Functions
TimePaths (const argList &args, const word &systemName="system", const word &constantName="constant")
Construct using characteristics given by the argList.
TimePaths (const fileName &rootPath, const fileName &caseName, const word &systemName="system", const word &constantName="constant")
Construct given database name, rootPath and casePath.
TimePaths (const bool processorCase, const fileName &rootPath, const bool distributed, const fileName &globalCaseName, const fileName &caseName, const word &systemName="system", const word &constantName="constant")
Construct given database name, rootPath and casePath.
bool distributed () const
True if case running with parallel distributed directories (ie. not NFS mounted)
bool processorCase () const
Return true if this is a processor case.
const fileName & rootPath () const
Return root path.
const fileName & globalCaseName () const
Return global case name.
const fileName & caseName () const
Return case name.
fileName & caseName ()
The case name for modification (use with caution)
fileName path () const
Return path for the case.
fileName globalPath () const
Return global path for the case.
fileName relativePath (const fileName &input, const bool caseTag=false) const
Return the input relative to the globalPath by stripping off a leading value of the globalPath.
const word & constant () const
Return constant name.
const word & system () const
Return system name.
fileName caseConstant () const
Return the constant name for the case, which is ../constant() for parallel runs.
fileName caseSystem () const
Return the system name for the case, which is ../system() for parallel runs.
fileName constantPath () const
Return constant path.
fileName systemPath () const
Return system path.
instantList times () const
Search the case for valid time directories.
instant findClosestTime (const scalar t) const
Search the case for the time closest to the given time.
Static Public Member Functions
static instantList findTimes (const fileName &directory, const word &constantName="constant")
Search a given directory for valid time directories.
static label findClosestTimeIndex (const instantList &timeDirs, const scalar t, const word &constantName="constant")
Search instantList for the time index closest to the specified time.
Detailed Description
Address the time paths without using the Time class.
Source files
TimePaths.H
TimePaths.C
Definition at line 52 of file TimePaths.H.
Constructor & Destructor Documentation
TimePaths (const argList & args, const word & systemName = "system", const word & constantName = "constant")
Construct using characteristics given by the argList.
Definition at line 62 of file TimePaths.C.
TimePaths (const fileName & rootPath, const fileName & caseName, const word & systemName = "system", const word & constantName = "constant")
Construct given database name, rootPath and casePath.
Definition at line 84 of file TimePaths.C.
TimePaths (const bool processorCase, const fileName & rootPath, const bool distributed, const fileName & globalCaseName, const fileName & caseName, const word & systemName = "system", const word & constantName = "constant")
Construct given database name, rootPath and casePath.
Definition at line 105 of file TimePaths.C.
Member Function Documentation
bool distributed () const inline
True if case running with parallel distributed directories (ie. not NFS mounted)
Definition at line 23 of file TimePathsI.H.
bool processorCase () const inline
Return true if this is a processor case.
Definition at line 29 of file TimePathsI.H.
const Foam::fileName & rootPath () const inline
Return root path.
Definition at line 35 of file TimePathsI.H.
Referenced by engineTime::New().
const Foam::fileName & globalCaseName () const inline
Return global case name.
Definition at line 41 of file TimePathsI.H.
const Foam::fileName & caseName () const inline
Return case name.
Definition at line 47 of file TimePathsI.H.
Referenced by engineTime::New().
Foam::fileName & caseName () inline
The case name for modification (use with caution)
Definition at line 53 of file TimePathsI.H.
Foam::fileName path () const inline
Return path for the case.
Definition at line 59 of file TimePathsI.H.
Foam::fileName globalPath () const inline
Return global path for the case.
Definition at line 65 of file TimePathsI.H.
Referenced by meshRefinement::findRegions().
Foam::fileName relativePath (const fileName & input, const bool caseTag = false) const inline
Return the input relative to the globalPath by stripping off a leading value of the globalPath.
Parameters
input the directory or filename to make case-relative
caseTag replace globalPath with <case> for later use with expand(), or prefix <case> if the file name was not an absolute location
Definition at line 72 of file TimePathsI.H.
const Foam::word & constant () const inline
Return constant name.
Definition at line 81 of file TimePathsI.H.
References fileName::relative().
Referenced by coalCloudList::coalCloudList(), surfaceFilmModel::New(), engineMesh::New(), basicSolidChemistryModel::New(), laminarFlameSpeed::New(), twoPhaseSystem::New(), coordinateSystems::New(), laminarModel< BasicTurbulenceModel >::New(), SRFModel::New(), RASModel< BasicTurbulenceModel >::New(), dynamicFvMesh::New(), multiphaseSystem::New(), LESModel< BasicTurbulenceModel >::New(), thermalBaffleModel::New(), pyrolysisModel::New(), radiationModel::New(), waveModel::New(), pyrolysisModelCollection::pyrolysisModelCollection(), and mappedPatchBase::surfPtr().
const Foam::word & system () const inline
Return system name.
Definition at line 87 of file TimePathsI.H.
Foam::fileName caseConstant () const inline
Return the constant name for the case, which is ../constant() for parallel runs.
Definition at line 93 of file TimePathsI.H.
Foam::fileName caseSystem () const inline
Return the system name for the case, which is ../system() for parallel runs.
Definition at line 104 of file TimePathsI.H.
Foam::fileName constantPath () const inline
Return constant path.
Definition at line 115 of file TimePathsI.H.
Foam::fileName systemPath () const inline
Return system path.
Definition at line 121 of file TimePathsI.H.
References path().
Foam::instantList findTimes (const fileName & directory, const word & constantName = "constant") static
Search a given directory for valid time directories.
Forwards to the current fileHandler
Definition at line 133 of file TimePaths.C.
Foam::label findClosestTimeIndex (const instantList & timeDirs, const scalar t, const word & constantName = "constant") static
Search instantList for the time index closest to the specified time.
Definition at line 149 of file TimePaths.C.
References path().
Foam::instantList times () const
Search the case for valid time directories.
Definition at line 142 of file TimePaths.C.
References Foam::fileHandler(), and fileOperation::findTimes().
Foam::instant findClosestTime (const scalar t) const
Search the case for the time closest to the given time.
Definition at line 176 of file TimePaths.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/TimePaths.H
src/OpenFOAM/db/Time/TimePaths.C
src/OpenFOAM/db/Time/TimePathsI.H