OpenFOAM: stateFunctionObject Class Reference
stateFunctionObject Class Reference
Base class for function objects, adding functionality to read/write state information (data required for smooth restart behaviour) and results to/from the state dictionary.
Public Member Functions
stateFunctionObject (const word &name, const Time &runTime)
Construct from components.
virtual ~stateFunctionObject ()=default
Destructor.
dictionary & propertyDict ()
Return access to the property dictionary.
bool foundProperty (const word &entryName) const
Return true if the property exists.
label getTrigger () const
Get the current trigger index.
bool setTrigger (const label triggeri)
Set the current trigger index.
bool getDict (const word &entryName, dictionary &dict) const
Set dictionary, return true if set.
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
Set dictionary from named object, return true if set.
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property.
template<class Type >
bool getProperty (const word &entryName, Type &value) const
Set generic property, return true if set.
template<class Type >
void setProperty (const word &entryName, const Type &value)
Add generic property.
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from named object.
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
Set generic property from named object, return true if set.
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
Add generic property from named object.
template<class Type >
void setResult (const word &entryName, const Type &value)
Add result.
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
Add result from named object.
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result.
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result from named object.
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
Set result from named object, return true if set.
word resultType (const word &entryName) const
Retrieve the result type.
word objectResultType (const word &objectName, const word &entryName) const
Return the type of result.
List< word > objectResultEntries () const
Retrieve the result entries.
List< word > objectResultEntries (const word &objectName) const
Return result entries for named object.
void writeResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
void writeResultEntries (const word &objectName, Ostream &os) const
Write the results entries for named object to stream.
void writeAllResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
Construct from Time.
virtual ~timeFunctionObject ()=default
Destructor.
const Time & time () const
Return time database.
objectRegistry & storedObjects ()
Write access to the output objects ("functionObjectObjects") registered on Time.
const objectRegistry & storedObjects () const
Const access to the output objects ("functionObjectObjects") registered on Time.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()=default
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool read (const dictionary &dict)
Read and set the function object if its data have changed.
virtual bool execute ()=0
Called at each ++ or += of the time-loop.
virtual bool execute (const label subIndex)
Execute using the specified subIndex.
virtual bool write ()=0
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool filesModified () const
Did any file get changed during execution?
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
const IOdictionary & stateDict () const
Return a const reference to the state dictionary.
IOdictionary & stateDict ()
Return non-const access to the state dictionary.
stateFunctionObject (const stateFunctionObject &)=delete
No copy construct.
void operator= (const stateFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
Remove specified items from "functionObjectObjects".
timeFunctionObject (const timeFunctionObject &)=delete
No copy construct.
void operator= (const timeFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Return a scoped name, e.g. used to construct local field names.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
bool log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
static word outputPrefix
Directory prefix.
Protected Attributes inherited from timeFunctionObject
const Time & time_
Reference to the time database.
Detailed Description
Base class for function objects, adding functionality to read/write state information (data required for smooth restart behaviour) and results to/from the state dictionary.
Note: cannot access the state dictionary until after construction of the function objects, since the owner container functionObjectList is owned by time, and time owns the state dictionary. I.e. need to wait for time to be fully constructed.
See Also
Foam::functionObject
Source files
stateFunctionObject.H
stateFunctionObject.C
stateFunctionObjectTemplates.C
Definition at line 63 of file stateFunctionObject.H.
Constructor & Destructor Documentation
stateFunctionObject (const stateFunctionObject &) protected delete
No copy construct.
stateFunctionObject (const word & name, const Time & runTime)
Construct from components.
Definition at line 49 of file stateFunctionObject.C.
virtual ~stateFunctionObject () virtual default
Destructor.
Member Function Documentation
const Foam::IOdictionary & stateDict () const protected
Return a const reference to the state dictionary.
Definition at line 34 of file stateFunctionObject.C.
Foam::IOdictionary & stateDict () protected
Return non-const access to the state dictionary.
Definition at line 40 of file stateFunctionObject.C.
References Time::functionObjects(), functionObjectList::stateDict(), and timeFunctionObject::time_.
void operator= (const stateFunctionObject &) protected delete
No copy assignment.
Foam::dictionary & propertyDict ()
Return access to the property dictionary.
Definition at line 60 of file stateFunctionObject.C.
bool foundProperty (const word & entryName) const
Return true if the property exists.
Definition at line 102 of file stateFunctionObject.C.
Foam::label getTrigger () const
Get the current trigger index.
Definition at line 93 of file stateFunctionObject.C.
bool setTrigger (const label triggeri)
Set the current trigger index.
Definition at line 74 of file stateFunctionObject.C.
bool getDict (const word & entryName, dictionary & dict) const
Set dictionary, return true if set.
Definition at line 119 of file stateFunctionObject.C.
bool getObjectDict (const word & objectName, const word & entryName, dictionary & dict) const
Set dictionary from named object, return true if set.
Definition at line 129 of file stateFunctionObject.C.
References dict, and Foam::name().
Referenced by functionObjectBase::getFileName().
Type getProperty (const word & entryName, const Type & defaultValue = Type(Zero)) const
Retrieve generic property.
Definition at line 28 of file stateFunctionObjectTemplates.C.
bool getProperty (const word & entryName, Type & value) const
Set generic property, return true if set.
Definition at line 41 of file stateFunctionObjectTemplates.C.
void setProperty (const word & entryName, const Type & value)
Add generic property.
Definition at line 52 of file stateFunctionObjectTemplates.C.
References Foam::name().
Type getObjectProperty (const word & objectName, const word & entryName, const Type & defaultValue = Type(Zero)) const
Retrieve generic property from named object.
Definition at line 63 of file stateFunctionObjectTemplates.C.
References Foam::name().
bool getObjectProperty (const word & objectName, const word & entryName, Type & value) const
Set generic property from named object, return true if set.
Definition at line 77 of file stateFunctionObjectTemplates.C.
void setObjectProperty (const word & objectName, const word & entryName, const Type & value)
Add generic property from named object.
Definition at line 97 of file stateFunctionObjectTemplates.C.
void setResult (const word & entryName, const Type & value)
Add result.
Definition at line 117 of file stateFunctionObjectTemplates.C.
Referenced by averageCondition::calc(), valueAverage::calc(), and fieldMinMax::output().
void setObjectResult (const word & objectName, const word & entryName, const Type & value)
Add result from named object.
Definition at line 128 of file stateFunctionObjectTemplates.C.
References Foam::name().
Type getResult (const word & entryName, const Type & defaultValue = Type(Zero)) const
Retrieve result.
Definition at line 165 of file stateFunctionObjectTemplates.C.
Referenced by averageCondition::calc().
Type getObjectResult (const word & objectName, const word & entryName, const Type & defaultValue = Type(Zero)) const
Retrieve result from named object.
Definition at line 176 of file stateFunctionObjectTemplates.C.
References Foam::name().
Referenced by averageCondition::calc(), and minMaxCondition::setValue().
bool getObjectResult (const word & objectName, const word & entryName, Type & value) const
Set result from named object, return true if set.
Definition at line 190 of file stateFunctionObjectTemplates.C.
Foam::word resultType (const word & entryName) const
Retrieve the result type.
Definition at line 152 of file stateFunctionObject.C.
Foam::word objectResultType (const word & objectName, const word & entryName) const
Return the type of result.
Definition at line 161 of file stateFunctionObject.C.
References Foam::name().
Referenced by averageCondition::calc(), and valueAverage::calc().
Foam::List< Foam::word > objectResultEntries () const
Retrieve the result entries.
Definition at line 194 of file stateFunctionObject.C.
Foam::List< Foam::word > objectResultEntries (const word & objectName) const
Return result entries for named object.
Definition at line 202 of file stateFunctionObject.C.
References Foam::name().
void writeResultEntries (Ostream & os) const
Write the results entries for all objects to stream.
Definition at line 234 of file stateFunctionObject.C.
void writeResultEntries (const word & objectName, Ostream & os) const
Write the results entries for named object to stream.
Definition at line 243 of file stateFunctionObject.C.
References Foam::name().
void writeAllResultEntries (Ostream & os) const
Write the results entries for all objects to stream.
Definition at line 275 of file stateFunctionObject.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/stateFunctionObject/stateFunctionObject.H
src/OpenFOAM/db/functionObjects/stateFunctionObject/stateFunctionObject.C
src/OpenFOAM/db/functionObjects/stateFunctionObject/stateFunctionObjectTemplates.C