OpenFOAM: vectorTensorTransform Class Reference
vectorTensorTransform Class Reference
Vector-tensor class used to perform translations and rotations in 3D space.
Public Member Functions
vectorTensorTransform ()
Construct null.
vectorTensorTransform (const vector &t, const tensor &R, bool hasR=true)
Construct given a translation vector, rotation tensor and.
vectorTensorTransform (const vector &t)
Construct a pure translation vectorTensorTransform given a.
vectorTensorTransform (const tensor &R)
Construct a pure rotation vectorTensorTransform given a.
vectorTensorTransform (Istream &)
Construct from Istream.
const vector & t () const
const tensor & R () const
bool hasR () const
vector & t ()
tensor & R ()
vector transformPosition (const vector &v) const
Transform the given position.
pointField transformPosition (const pointField &pts) const
Transform the given pointField.
vector invTransformPosition (const vector &v) const
Inverse transform the given position.
pointField invTransformPosition (const pointField &pts) const
Inverse transform the given pointField.
template<class Type >
tmp< Field< Type > > transform (const Field< Type > &) const
Transform the given field.
void operator= (const vectorTensorTransform &)
void operator&= (const vectorTensorTransform &)
void operator= (const vector &)
void operator+= (const vector &)
void operator-= (const vector &)
void operator= (const tensor &)
void operator&= (const tensor &)
template<>
Foam::tmp< Foam::Field< bool > > transform (const Field< bool > &fld) const
template<>
Foam::tmp< Foam::Field
< Foam::label > > transform (const Field< label > &fld) const
template<>
Foam::tmp< Foam::Field
< Foam::scalar > > transform (const Field< scalar > &fld) const
template<>
tmp< Field< bool > > transform (const Field< bool > &) const
Template specialisations.
template<>
tmp< Field< label > > transform (const Field< label > &) const
template<>
tmp< Field< scalar > > transform (const Field< scalar > &) const
template<class Type >
Foam::tmp< Foam::Field< Type > > transform (const Field< Type > &fld) const
Static Public Attributes
static const char *const typeName
static const vectorTensorTransform zero
static const vectorTensorTransform I
Friends
Istream & operator>> (Istream &is, vectorTensorTransform &)
Ostream & operator<< (Ostream &os, const vectorTensorTransform &)
Detailed Description
Vector-tensor class used to perform translations and rotations in 3D space.
Source files
vectorTensorTransform.H
vectorTensorTransformI.H
vectorTensorTransform.C
vectorTensorTransformTemplates.C
Definition at line 59 of file vectorTensorTransform.H.
Constructor & Destructor Documentation
vectorTensorTransform () inline
Construct null.
Definition at line 23 of file vectorTensorTransformI.H.
vectorTensorTransform (const vector & t, const tensor & R, bool hasR = true) inline
Construct given a translation vector, rotation tensor and.
hasR bool
Definition at line 32 of file vectorTensorTransformI.H.
vectorTensorTransform (const vector & t) inline explicit
Construct a pure translation vectorTensorTransform given a.
translation vector
Definition at line 44 of file vectorTensorTransformI.H.
vectorTensorTransform (const tensor & R) inline explicit
Construct a pure rotation vectorTensorTransform given a.
rotation tensor
Definition at line 52 of file vectorTensorTransformI.H.
vectorTensorTransform (Istream & is)
Construct from Istream.
Definition at line 48 of file vectorTensorTransform.C.
Member Function Documentation
const Foam::vector & t () const inline
Definition at line 62 of file vectorTensorTransformI.H.
const Foam::tensor & R () const inline
Definition at line 68 of file vectorTensorTransformI.H.
Referenced by particle< Type >::correctAfterInteractionListReferral(), and vectorTensorTransform::transform().
bool hasR () const inline
Definition at line 74 of file vectorTensorTransformI.H.
References R_().
Foam::vector & t () inline
Definition at line 80 of file vectorTensorTransformI.H.
Foam::tensor & R () inline
Definition at line 86 of file vectorTensorTransformI.H.
Foam::vector transformPosition (const vector & v) const inline
Transform the given position.
Definition at line 98 of file vectorTensorTransformI.H.
Foam::pointField transformPosition (const pointField & pts) const inline
Transform the given pointField.
Definition at line 114 of file vectorTensorTransformI.H.
Foam::vector invTransformPosition (const vector & v) const inline
Inverse transform the given position.
Definition at line 133 of file vectorTensorTransformI.H.
Foam::pointField invTransformPosition (const pointField & pts) const inline
Inverse transform the given pointField.
Definition at line 149 of file vectorTensorTransformI.H.
tmp<Field<Type> > transform (const Field< Type > &) const
Transform the given field.
void operator= (const vectorTensorTransform & tr) inline
Definition at line 170 of file vectorTensorTransformI.H.
void operator&= (const vectorTensorTransform & tr) inline
Definition at line 181 of file vectorTensorTransformI.H.
void operator= (const vector & t) inline
Definition at line 194 of file vectorTensorTransformI.H.
void operator+= (const vector & t) inline
Definition at line 200 of file vectorTensorTransformI.H.
void operator-= (const vector & t) inline
Definition at line 206 of file vectorTensorTransformI.H.
void operator= (const tensor & R) inline
Definition at line 212 of file vectorTensorTransformI.H.
void operator&= (const tensor & R) inline
Definition at line 220 of file vectorTensorTransformI.H.
References R, and R_().
Foam::tmp<Foam::Field<bool> > transform (const Field< bool > & fld) const
Definition at line 68 of file vectorTensorTransform.C.
Foam::tmp<Foam::Field<Foam::label> > transform (const Field< label > & fld) const
Definition at line 76 of file vectorTensorTransform.C.
References fld.
Foam::tmp<Foam::Field<Foam::scalar> > transform (const Field< scalar > & fld) const
Definition at line 84 of file vectorTensorTransform.C.
References fld.
tmp<Field<bool> > transform (const Field< bool > &) const
Template specialisations.
tmp<Field<label> > transform (const Field< label > &) const
tmp<Field<scalar> > transform (const Field< scalar > &) const
Foam::tmp<Foam::Field<Type> > transform (const Field< Type > & fld) const
Definition at line 25 of file vectorTensorTransformTemplates.C.
References fld, and vectorTensorTransform::R().
Friends And Related Function Documentation
Istream& operator>> (Istream & is, vectorTensorTransform &) friend
Ostream& operator<< (Ostream & os, const vectorTensorTransform &) friend
Member Data Documentation
const char *const typeName static
Initial value:
=
    "vectorTensorTransform"
Definition at line 86 of file vectorTensorTransform.H.
const Foam::vectorTensorTransform zero static
Definition at line 88 of file vectorTensorTransform.H.
const Foam::vectorTensorTransform I static
Definition at line 90 of file vectorTensorTransform.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransform.H
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransform.C
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransformI.H
src/OpenFOAM/primitives/globalIndexAndTransform/vectorTensorTransform/vectorTensorTransformTemplates.C