OpenFOAM: addstopAtWriteNowSignalToOpt Class Reference
addstopAtWriteNowSignalToOpt Class Reference
Public Member Functions
addstopAtWriteNowSignalToOpt (const addstopAtWriteNowSignalToOpt &)=delete
void operator= (const addstopAtWriteNowSignalToOpt &)=delete
addstopAtWriteNowSignalToOpt (const char *name)
virtual ~addstopAtWriteNowSignalToOpt ()=default
virtual void readData (Foam::Istream &is)
Read.
virtual void writeData (Foam::Ostream &os) const
Write.
Public Member Functions inherited from simpleRegIOobject
simpleRegIOobject (void(*fn)(const char *name, simpleRegIOobject *), const char *name)
Construct from objectregistry inserter and name.
virtual ~simpleRegIOobject ()=default
Destructor.
Detailed Description
Definition at line 50 of file sigStopAtWriteNow.C.
Constructor & Destructor Documentation
addstopAtWriteNowSignalToOpt (const addstopAtWriteNowSignalToOpt &) delete
Referenced by addstopAtWriteNowSignalToOpt::addstopAtWriteNowSignalToOpt().
addstopAtWriteNowSignalToOpt (const char * name) inline explicit
Definition at line 60 of file sigStopAtWriteNow.C.
References addstopAtWriteNowSignalToOpt::addstopAtWriteNowSignalToOpt(), and addstopAtWriteNowSignalToOpt::operator=().
virtual ~addstopAtWriteNowSignalToOpt () virtual default
Member Function Documentation
void operator= (const addstopAtWriteNowSignalToOpt &) delete
Referenced by addstopAtWriteNowSignalToOpt::addstopAtWriteNowSignalToOpt().
virtual void readData (Foam::Istream & is) inline virtual
Read.
Implements simpleRegIOobject.
Definition at line 67 of file sigStopAtWriteNow.C.
virtual void writeData (Foam::Ostream & os) const inline virtual
Write.
Implements simpleRegIOobject.
Definition at line 73 of file sigStopAtWriteNow.C.
References sigStopAtWriteNow::set().
The documentation for this class was generated from the following file:
src/OSspecific/POSIX/signals/sigStopAtWriteNow.C