OpenFOAM: isoCutFace Class Reference
isoCutFace Class Reference
Class for cutting a face, faceI, of an fvMesh, mesh_, at its intersection with an isosurface defined by the mesh point values f_ and the isovalue, isoValue_.
Public Member Functions
isoCutFace (const fvMesh &mesh, scalarField &f)
Construct from fvMesh and a scalarField.
label calcSubFace (const label faceI, const scalar isoValue)
Calculate cut points along edges of faceI.
label calcSubFace (const pointField &points, const scalarField &f, const scalar isoValue)
Calculate cut points along edges of face with values f.
const point & subFaceCentre ()
const vector & subFaceArea ()
const DynamicList< point > & subFacePoints () const
const DynamicList< point > & surfacePoints () const
void clearStorage ()
scalar timeIntegratedFaceFlux (const label facei, const vector &x0, const vector &n0, const scalar Un0, const scalar f0, const scalar dt, const scalar phi, const scalar magSf)
Calculate volumetric face transport during dt given the isoFace.
scalar timeIntegratedArea (const pointField &fPts, const scalarField &pTimes, const scalar dt, const scalar magSf, const scalar Un0)
Calculate time integrated area for a face.
void cutPoints (const pointField &pts, const scalarField &f, const scalar f0, DynamicList< point > &cutPoints)
void quadAreaCoeffs (const DynamicList< point > &pf0, const DynamicList< point > &pf1, scalar &alpha, scalar &beta) const
Static Public Attributes
static int debug = 0
Detailed Description
Class for cutting a face, faceI, of an fvMesh, mesh_, at its intersection with an isosurface defined by the mesh point values f_ and the isovalue, isoValue_.
Reference:
        Roenby, J., Bredmose, H. and Jasak, H. (2016).
        A computational method for sharp interface advection
        Royal Society Open Science, 3
        doi 10.1098/rsos.160405
Original code supplied by Johan Roenby, DHI (2016)
Source files
isoCutFace.H
isoCutFace.C
Definition at line 60 of file isoCutFace.H.
Constructor & Destructor Documentation
isoCutFace (const fvMesh & mesh, scalarField & f)
Construct from fvMesh and a scalarField.
Length of scalarField should equal number of mesh points
Definition at line 32 of file isoCutFace.C.
References isoCutFace::clearStorage().
Member Function Documentation
Foam::label calcSubFace (const label faceI, const scalar isoValue)
Calculate cut points along edges of faceI.
Definition at line 262 of file isoCutFace.C.
Foam::label calcSubFace (const pointField & points, const scalarField & f, const scalar isoValue)
Calculate cut points along edges of face with values f.
Definition at line 275 of file isoCutFace.C.
const Foam::point & subFaceCentre ()
Definition at line 287 of file isoCutFace.C.
References Foam::identity(), and UList< T >::size().
const Foam::vector & subFaceArea ()
Definition at line 297 of file isoCutFace.C.
const Foam::DynamicList< Foam::point > & subFacePoints () const
Definition at line 307 of file isoCutFace.C.
const Foam::DynamicList< Foam::point > & surfacePoints () const
Definition at line 313 of file isoCutFace.C.
void clearStorage ()
Definition at line 319 of file isoCutFace.C.
Referenced by isoCutFace::isoCutFace().
Foam::scalar timeIntegratedFaceFlux (const label facei, const vector & x0, const vector & n0, const scalar Un0, const scalar f0, const scalar dt, const scalar phi, const scalar magSf)
Calculate volumetric face transport during dt given the isoFace.
data provided as input for face facei
Definition at line 334 of file isoCutFace.C.
Foam::scalar timeIntegratedArea (const pointField & fPts, const scalarField & pTimes, const scalar dt, const scalar magSf, const scalar Un0)
Calculate time integrated area for a face.
Definition at line 480 of file isoCutFace.C.
void cutPoints (const pointField & pts, const scalarField & f, const scalar f0, DynamicList< point > & cutPoints)
Definition at line 618 of file isoCutFace.C.
void quadAreaCoeffs (const DynamicList< point > & pf0, const DynamicList< point > & pf1, scalar & alpha, scalar & beta) const
Definition at line 666 of file isoCutFace.C.
Member Data Documentation
int debug = 0 static
Definition at line 164 of file isoCutFace.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMatrices/solvers/isoAdvection/isoCutFace/isoCutFace.H
src/finiteVolume/fvMatrices/solvers/isoAdvection/isoCutFace/isoCutFace.C