OpenFOAM: treeDataPrimitivePatch< PatchType > Class Template Reference
treeDataPrimitivePatch< PatchType > Class Template Reference
Encapsulation of data needed to search on PrimitivePatches.
Classes
class findAllIntersectOp
class findIntersectOp
class findNearestOp
class findSelfIntersectOp
Public Member Functions
treeDataPrimitivePatch (const bool cacheBb, const PatchType &, const scalar planarTol)
Construct from patch.
label size () const
pointField shapePoints () const
Representative point cloud for all shapes inside (one point per shape)
const PatchType & patch () const
Return access to the underlying patch.
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< PatchType >> &, const point &) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does shape at index overlap bb.
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
Does shape at index overlap sphere.
template<>
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> &oc, const point &sample) const
template<>
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> &oc, const point &sample) const
Static Public Member Functions
static bool findIntersection (const indexedOctree< treeDataPrimitivePatch< PatchType >> &tree, const label index, const point &start, const point &end, point &intersectionPoint)
Helper: find intersection of line with shapes.
Detailed Description
template<class PatchType>
class Foam::treeDataPrimitivePatch< PatchType >
Encapsulation of data needed to search on PrimitivePatches.
Source files
treeDataPrimitivePatch.H
treeDataPrimitivePatch.C
Definition at line 59 of file treeDataPrimitivePatch.H.
Constructor & Destructor Documentation
treeDataPrimitivePatch (const bool cacheBb, const PatchType & patch, const scalar planarTol)
Construct from patch.
Definition at line 50 of file treeDataPrimitivePatch.C.
Member Function Documentation
label size () const inline
Definition at line 231 of file treeDataPrimitivePatch.H.
Foam::pointField shapePoints () const
Representative point cloud for all shapes inside (one point per shape)
Definition at line 112 of file treeDataPrimitivePatch.C.
const PatchType& patch () const inline
Return access to the underlying patch.
Definition at line 245 of file treeDataPrimitivePatch.H.
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< PatchType >> & oc, const point & sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 127 of file treeDataPrimitivePatch.C.
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does shape at index overlap bb.
Definition at line 356 of file treeDataPrimitivePatch.C.
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Does shape at index overlap sphere.
Definition at line 423 of file treeDataPrimitivePatch.C.
bool findIntersection (const indexedOctree< treeDataPrimitivePatch< PatchType >> & tree, const label index, const point & start, const point & end, point & intersectionPoint) static
Helper: find intersection of line with shapes.
Definition at line 570 of file treeDataPrimitivePatch.C.
Foam::volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> & oc, const point & sample) const
Definition at line 29 of file treeDataTriSurface.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, PointIndexHit< Point >::index(), and Foam::sqr().
volumeType getVolumeType (const indexedOctree< treeDataPrimitivePatch< triSurface >> & oc, const point & sample) const
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPrimitivePatch.H
src/meshTools/indexedOctree/treeDataPrimitivePatch.C