OpenFOAM: primitiveMeshTools Class Reference
primitiveMeshTools Class Reference
Static Public Member Functions
static tmp< scalarField > faceOrthogonality (const primitiveMesh &mesh, const vectorField &fAreas, const vectorField &cellCtrs)
Generate non-orthogonality field (internal faces only)
static void facePyramidVolume (const primitiveMesh &mesh, const pointField &points, const vectorField &cellCtrs, scalarField &ownPyrVol, scalarField &neiPyrVol)
Generate face pyramid volume fields.
static tmp< scalarField > faceSkewness (const primitiveMesh &mesh, const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs)
Generate skewness field.
static void cellClosedness (const primitiveMesh &mesh, const Vector< label > &meshD, const vectorField &areas, const scalarField &vols, scalarField &openness, scalarField &aratio)
Generate cell openness and cell ascpect ratio field.
static tmp< scalarField > faceConcavity (const scalar maxSin, const primitiveMesh &mesh, const pointField &p, const vectorField &faceAreas)
Generate face concavity field. Returns per face the (sin of the)
static tmp< scalarField > faceFlatness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &faceAreas)
Generate face flatness field. Compares the individual triangles'.
static tmp< scalarField > edgeAlignment (const primitiveMesh &mesh, const Vector< label > &directions, const pointField &p)
Generate edge alignment field. Is per face the minimum aligned edge.
static tmp< scalarField > cellDeterminant (const primitiveMesh &mesh, const Vector< label > &directions, const vectorField &faceAreas, const bitSet &internalOrCoupledFace)
Generate cell determinant field. Normalised to 1 for an internal cube.
static scalar faceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc, const point &neiCc)
Skewness of single face.
static scalar boundaryFaceSkewness (const primitiveMesh &mesh, const pointField &p, const vectorField &fCtrs, const vectorField &fAreas, const label facei, const point &ownCc)
Skewness of single boundary face.
static scalar faceOrthogonality (const point &ownCc, const point &neiCc, const vector &s)
Orthogonality of single face.
Detailed Description
Definition at line 48 of file primitiveMeshTools.H.
Member Function Documentation
Foam::tmp< Foam::scalarField > faceOrthogonality (const primitiveMesh & mesh, const vectorField & fAreas, const vectorField & cellCtrs) static
Generate non-orthogonality field (internal faces only)
Definition at line 118 of file primitiveMeshTools.C.
Referenced by polyMeshTools::faceOrthogonality().
void facePyramidVolume (const primitiveMesh & mesh, const pointField & points, const vectorField & cellCtrs, scalarField & ownPyrVol, scalarField & neiPyrVol) static
Generate face pyramid volume fields.
Definition at line 197 of file primitiveMeshTools.C.
Foam::tmp< Foam::scalarField > faceSkewness (const primitiveMesh & mesh, const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs) static
Generate skewness field.
Definition at line 146 of file primitiveMeshTools.C.
void cellClosedness (const primitiveMesh & mesh, const Vector< label > & meshD, const vectorField & areas, const scalarField & vols, scalarField & openness, scalarField & aratio) static
Generate cell openness and cell ascpect ratio field.
Definition at line 236 of file primitiveMeshTools.C.
Foam::tmp< Foam::scalarField > faceConcavity (const scalar maxSin, const primitiveMesh & mesh, const pointField & p, const vectorField & faceAreas) static
Generate face concavity field. Returns per face the (sin of the)
most concave angle between two consecutive edges
Definition at line 330 of file primitiveMeshTools.C.
Foam::tmp< Foam::scalarField > faceFlatness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & faceAreas) static
Generate face flatness field. Compares the individual triangles'.
normals against the face average normal. Between 0 (fully warped) and 1 (fully flat)
Definition at line 400 of file primitiveMeshTools.C.
static tmp<scalarField> edgeAlignment (const primitiveMesh & mesh, const Vector< label > & directions, const pointField & p) static
Generate edge alignment field. Is per face the minimum aligned edge.
(does not use edge addressing)
Foam::tmp< Foam::scalarField > cellDeterminant (const primitiveMesh & mesh, const Vector< label > & directions, const vectorField & faceAreas, const bitSet & internalOrCoupledFace) static
Generate cell determinant field. Normalised to 1 for an internal cube.
Definition at line 450 of file primitiveMeshTools.C.
Foam::scalar faceSkewness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc, const point & neiCc) static
Skewness of single face.
Definition at line 29 of file primitiveMeshTools.C.
References d, f(), primitiveMesh::faces(), forAll, Foam::mag(), Foam::max(), and Foam::constant::mathematical::pi().
Foam::scalar boundaryFaceSkewness (const primitiveMesh & mesh, const pointField & p, const vectorField & fCtrs, const vectorField & fAreas, const label facei, const point & ownCc) static
Skewness of single boundary face.
Definition at line 65 of file primitiveMeshTools.C.
Foam::scalar faceOrthogonality (const point & ownCc, const point & neiCc, const vector & s) static
Orthogonality of single face.
Definition at line 103 of file primitiveMeshTools.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshTools.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshTools.C