OpenFOAM: enrichedPatch Class Reference
enrichedPatch Class Reference
The enriched patch contains a double set of faces from the two sides of the sliding interface before the cutting.
Public Member Functions
ClassName ("enrichedPatch")
enrichedPatch (const primitiveFacePatch &masterPatch, const primitiveFacePatch &slavePatch, const labelUList &slavePointPointHits, const labelUList &slavePointEdgeHits, const UList< objectHit > &slavePointFaceHits)
Construct from components.
~enrichedPatch ()
Destructor.
const Map< point > & pointMap () const
Return map of points.
Map< point > & pointMap ()
Return non-const access to point map to add points.
const Map< label > & pointMergeMap () const
Return map of point merges.
Map< label > & pointMergeMap ()
Return map of point merges.
void calcEnrichedFaces (const labelListList &pointsIntoMasterEdges, const labelListList &pointsIntoSlaveEdges, const pointField &projectedSlavePoints)
Calculate enriched faces.
const faceList & enrichedFaces () const
Return enriched faces.
const labelList & meshPoints () const
Return mesh points.
const faceList & localFaces () const
Return local faces.
const pointField & localPoints () const
Return local points.
const labelListList & pointPoints () const
Return point-point addressing.
const Map< labelList > & masterPointFaces () const
Master point face addressing.
const faceList & cutFaces () const
Return list of cut faces.
const labelList & cutFaceMaster () const
Return cut face master list.
const labelList & cutFaceSlave () const
Return cut face slave list.
bool checkSupport () const
Check if the patch is fully supported.
void writeOBJ (const fileName &fName) const
Debugging: dump graphical representation to obj format file.
Detailed Description
The enriched patch contains a double set of faces from the two sides of the sliding interface before the cutting.
The patch basically consists of two over-lapping sets of faces sitting on a common point support, where every edge may be shared by more than 2 faces. The patch points are collected in a map. Additional information needed for cutting is the point insertion into every edge of master and slave.
Note: If new points are created during master-slave edge cutting, they should be registered with the pointMap.
Source files
enrichedPatch.H
enrichedPatch.C
enrichedPatchCutFaces.C
enrichedPatchFaces.C
enrichedPatchPointMap.C
enrichedPatchPointMergeMap.C
enrichedPatchPointPoints.C
Definition at line 64 of file enrichedPatch.H.
Constructor & Destructor Documentation
enrichedPatch (const primitiveFacePatch & masterPatch, const primitiveFacePatch & slavePatch, const labelUList & slavePointPointHits, const labelUList & slavePointEdgeHits, const UList< objectHit > & slavePointFaceHits)
Construct from components.
Definition at line 131 of file enrichedPatch.C.
~enrichedPatch ()
Destructor.
Definition at line 165 of file enrichedPatch.C.
Member Function Documentation
ClassName ("enrichedPatch")
const Foam::Map< Foam::point > & pointMap () const inline
Return map of points.
Definition at line 23 of file enrichedPatchI.H.
Referenced by enrichedPatch::calcEnrichedFaces().
Foam::Map< Foam::point > & pointMap () inline
Return non-const access to point map to add points.
Definition at line 34 of file enrichedPatchI.H.
const Foam::Map< Foam::label > & pointMergeMap () const inline
Return map of point merges.
Definition at line 45 of file enrichedPatchI.H.
Referenced by enrichedPatch::calcEnrichedFaces().
Foam::Map< Foam::label > & pointMergeMap () inline
Return map of point merges.
Definition at line 51 of file enrichedPatchI.H.
void calcEnrichedFaces (const labelListList & pointsIntoMasterEdges, const labelListList & pointsIntoSlaveEdges, const pointField & projectedSlavePoints)
Calculate enriched faces.
Definition at line 33 of file enrichedPatchFaces.C.
References Foam::abort(), enrichedPatch::checkSupport(), Foam::expressions::patchExpr::debug, Foam::constant::electromagnetic::e, Foam::endl(), enrichedPatch::enrichedFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceEdges(), Foam::FatalError, FatalErrorInFunction, forAll, i, Foam::Info, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), HashTable< T, Key, Hash >::lookup(), Foam::magSqr(), Foam::max(), Foam::min(), Foam::nl, enrichedPatch::pointMap(), enrichedPatch::pointMergeMap(), and UList< T >::size().
const Foam::faceList & enrichedFaces () const
Return enriched faces.
Definition at line 377 of file enrichedPatchFaces.C.
Referenced by enrichedPatch::calcEnrichedFaces().
const Foam::labelList & meshPoints () const
Return mesh points.
Definition at line 173 of file enrichedPatch.C.
const Foam::faceList & localFaces () const
Return local faces.
Definition at line 184 of file enrichedPatch.C.
const Foam::pointField & localPoints () const
Return local points.
Definition at line 195 of file enrichedPatch.C.
const Foam::labelListList & pointPoints () const
Return point-point addressing.
Definition at line 206 of file enrichedPatch.C.
const Foam::Map< Foam::labelList > & masterPointFaces () const
Master point face addressing.
Definition at line 97 of file enrichedPatchMasterPoints.C.
const Foam::faceList & cutFaces () const
Return list of cut faces.
Definition at line 652 of file enrichedPatchCutFaces.C.
const Foam::labelList & cutFaceMaster () const
Return cut face master list.
Definition at line 663 of file enrichedPatchCutFaces.C.
const Foam::labelList & cutFaceSlave () const
Return cut face slave list.
Definition at line 674 of file enrichedPatchCutFaces.C.
bool checkSupport () const
Check if the patch is fully supported.
Definition at line 217 of file enrichedPatch.C.
Referenced by enrichedPatch::calcEnrichedFaces().
void writeOBJ (const fileName & fName) const
Debugging: dump graphical representation to obj format file.
Definition at line 246 of file enrichedPatch.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatch.H
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatch.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchCutFaces.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchFaces.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchI.H
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchMasterPoints.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchPointMap.C
src/dynamicMesh/slidingInterface/enrichedPatch/enrichedPatchPointPoints.C