OpenFOAM: kOmegaSSTBase< BasicEddyViscosityModel > Class Template Reference
kOmegaSSTBase< BasicEddyViscosityModel > Class Template Reference
Base class implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
Public Types
typedef
BasicEddyViscosityModel::alphaField alphaField
typedef
BasicEddyViscosityModel::rhoField rhoField
typedef
BasicEddyViscosityModel::transportModel transportModel
Public Member Functions
kOmegaSSTBase (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~kOmegaSSTBase ()=default
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
tmp< volScalarField > DkEff (const volScalarField &F1) const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > omega () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Protected Member Functions
void setDecayControl (const dictionary &dict)
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
virtual void correctNut (const volScalarField &S2)
virtual void correctNut ()
virtual tmp
< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Return k production rate.
virtual tmp
< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
Return epsilon/k which for standard RAS is betaStar*omega.
virtual tmp
< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
Return G/nu.
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Attributes
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
Flag to include the F3 term.
const volScalarField & y_
Wall distance.
volScalarField k_
volScalarField omega_
Switch decayControl_
Flag to include the decay control.
dimensionedScalar kInf_
dimensionedScalar omegaInf_
Detailed Description
template<class BasicEddyViscosityModel>
class Foam::kOmegaSSTBase< BasicEddyViscosityModel >
Base class implementation of the k-omega-SST turbulence model for incompressible and compressible flows.
Turbulence model described in:
    Menter, F. R. & Esch, T. (2001).
    Elements of Industrial Heat Transfer Prediction.
    16th Brazilian Congress of Mechanical Engineering (COBEM).
with updated coefficients from
    Menter, F. R., Kuntz, M., and Langtry, R. (2003).
    Ten Years of Industrial Experience with the SST Turbulence Model.
    Turbulence, Heat and Mass Transfer 4, ed: K. Hanjalic, Y. Nagano,
    & M. Tummers, Begell House, Inc., 625 - 632.
but with the consistent production terms from the 2001 paper as form in the 2003 paper is a typo, see
    http://turbmodels.larc.nasa.gov/sst.html
and the addition of the optional F3 term for rough walls from
    Hellsten, A. (1998).
    Some Improvements in Menter's k-omega-SST turbulence model
    29th AIAA Fluid Dynamics Conference, AIAA-98-2554.
and the optional decay control from:
    Spalart, P. R. and Rumsey, C. L. (2007).
    Effective Inflow Conditions for Turbulence Models in Aerodynamic
    Calculations
    AIAA Journal, 45(10), 2544 - 2553.
Note that this implementation is written in terms of alpha diffusion coefficients rather than the more traditional sigma (alpha = 1/sigma) so that the blending can be applied to all coefficients in a consistent manner. The paper suggests that sigma is blended but this would not be consistent with the blending of the k-epsilon and k-omega models.
Also note that the error in the last term of equation (2) relating to sigma has been corrected.
Wall-functions are applied in this implementation by using equations (14) to specify the near-wall omega as appropriate.
The blending functions (15) and (16) are not currently used because of the uncertainty in their origin, range of applicability and that if y+ becomes sufficiently small blending u_tau in this manner clearly becomes nonsense.
The default model coefficients are
    kOmegaSSTBaseCoeffs
    {
        alphaK1         0.85;
        alphaK2         1.0;
        alphaOmega1     0.5;
        alphaOmega2     0.856;
        beta1           0.075;
        beta2           0.0828;
        betaStar        0.09;
        gamma1          5/9;
        gamma2          0.44;
        a1              0.31;
        b1              1.0;
        c1              10.0;
        F3              no;
        // Optional decay control
        decayControl    yes;
        kInf            \<far-field k value\>;
        omegaInf        \<far-field omega value\>;
    }
Source files
kOmegaSSTBase.H
kOmegaSSTBase.C
Definition at line 124 of file kOmegaSSTBase.H.
Member Typedef Documentation
typedef BasicEddyViscosityModel::alphaField alphaField
Definition at line 295 of file kOmegaSSTBase.H.
typedef BasicEddyViscosityModel::rhoField rhoField
Definition at line 296 of file kOmegaSSTBase.H.
typedef BasicEddyViscosityModel::transportModel transportModel
Definition at line 297 of file kOmegaSSTBase.H.
Constructor & Destructor Documentation
kOmegaSSTBase (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName)
Construct from components.
Definition at line 217 of file kOmegaSSTBase.C.
virtual ~kOmegaSSTBase () virtual default
Destructor.
Member Function Documentation
void setDecayControl (const dictionary & dict) protected
Definition at line 425 of file kOmegaSSTBase.C.
tmp< volScalarField > F1 (const volScalarField & CDkOmega) const protected virtual
Reimplemented in kOmegaSSTLM< BasicTurbulenceModel >.
Definition at line 35 of file kOmegaSSTBase.C.
References Foam::dimless, Foam::dimTime, Foam::constant::electromagnetic::e, Foam::max(), Foam::min(), Foam::constant::physicoChemical::mu, Foam::sqr(), and Foam::sqrt().
tmp< volScalarField > F2 () const protected virtual
Definition at line 64 of file kOmegaSSTBase.C.
tmp< volScalarField > F3 () const protected virtual
Definition at line 81 of file kOmegaSSTBase.C.
tmp< volScalarField > F23 () const protected virtual
Definition at line 94 of file kOmegaSSTBase.C.
tmp<volScalarField> blend (const volScalarField & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 205 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::alphaK(), kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::alphaOmega(), and kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::beta().
tmp<volScalarField::Internal> blend (const volScalarField::Internal & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 215 of file kOmegaSSTBase.H.
tmp<volScalarField> alphaK (const volScalarField & F1) const inline protected
Definition at line 224 of file kOmegaSSTBase.H.
tmp<volScalarField> alphaOmega (const volScalarField & F1) const inline protected
Definition at line 229 of file kOmegaSSTBase.H.
tmp<volScalarField::Internal> beta (const volScalarField::Internal & F1) const inline protected
Definition at line 235 of file kOmegaSSTBase.H.
tmp<volScalarField::Internal> gamma (const volScalarField::Internal & F1) const inline protected
Definition at line 243 of file kOmegaSSTBase.H.
void correctNut (const volScalarField & S2) protected virtual
Reimplemented in kOmegaSSTSato< BasicTurbulenceModel >, kOmegaSST< BasicTurbulenceModel >, and kOmegaSSTDES< BasicTurbulenceModel >.
Definition at line 109 of file kOmegaSSTBase.C.
void correctNut () protected virtual
Reimplemented in kOmegaSST< BasicTurbulenceModel >, and kOmegaSSTDES< BasicTurbulenceModel >.
Definition at line 121 of file kOmegaSSTBase.C.
tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected virtual
Return k production rate.
Reimplemented in kOmegaSSTLM< BasicTurbulenceModel >.
Definition at line 129 of file kOmegaSSTBase.C.
References Foam::fvc::grad(), Foam::magSqr(), and Foam::symm().
tmp< volScalarField::Internal > epsilonByk (const volScalarField & F1, const volTensorField & gradU) const protected virtual
Return epsilon/k which for standard RAS is betaStar*omega.
Reimplemented in kOmegaSSTLM< BasicTurbulenceModel >, and kOmegaSSTDES< BasicTurbulenceModel >.
Definition at line 140 of file kOmegaSSTBase.C.
tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal & GbyNu0, const volScalarField::Internal & F2, const volScalarField::Internal & S2) const protected virtual
Return G/nu.
Reimplemented in kOmegaSSTDES< BasicTurbulenceModel >.
Definition at line 151 of file kOmegaSSTBase.C.
tmp< fvScalarMatrix > kSource () const protected virtual
Definition at line 167 of file kOmegaSSTBase.C.
tmp< fvScalarMatrix > omegaSource () const protected virtual
Definition at line 181 of file kOmegaSSTBase.C.
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected virtual
Reimplemented in kOmegaSSTSAS< BasicTurbulenceModel >.
Definition at line 196 of file kOmegaSSTBase.C.
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented in kOmegaSSTLM< BasicTurbulenceModel >, kOmegaSSTSato< BasicTurbulenceModel >, kOmegaSSTSAS< BasicTurbulenceModel >, kOmegaSSTDES< BasicTurbulenceModel >, kOmegaSSTIDDES< BasicTurbulenceModel >, and kOmegaSSTDDES< BasicTurbulenceModel >.
Definition at line 448 of file kOmegaSSTBase.C.
tmp<volScalarField> DkEff (const volScalarField & F1) const inline
Return the effective diffusivity for k.
Definition at line 334 of file kOmegaSSTBase.H.
tmp<volScalarField> DomegaEff (const volScalarField & F1) const inline
Return the effective diffusivity for omega.
Definition at line 345 of file kOmegaSSTBase.H.
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Definition at line 360 of file kOmegaSSTBase.H.
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 368 of file kOmegaSSTBase.H.
virtual tmp<volScalarField> omega () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 389 of file kOmegaSSTBase.H.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented in kOmegaSSTLM< BasicTurbulenceModel >, and kOmegaSSTSato< BasicTurbulenceModel >.
Definition at line 476 of file kOmegaSSTBase.C.
Member Data Documentation
dimensionedScalar alphaK1_ protected
Definition at line 147 of file kOmegaSSTBase.H.
dimensionedScalar alphaK2_ protected
Definition at line 148 of file kOmegaSSTBase.H.
dimensionedScalar alphaOmega1_ protected
Definition at line 150 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::alphaK().
dimensionedScalar alphaOmega2_ protected
Definition at line 151 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::alphaK().
dimensionedScalar gamma1_ protected
Definition at line 153 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::beta().
dimensionedScalar gamma2_ protected
Definition at line 154 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::beta().
dimensionedScalar beta1_ protected
Definition at line 156 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::alphaOmega().
dimensionedScalar beta2_ protected
Definition at line 157 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::alphaOmega().
dimensionedScalar betaStar_ protected
Definition at line 159 of file kOmegaSSTBase.H.
dimensionedScalar a1_ protected
Definition at line 161 of file kOmegaSSTBase.H.
dimensionedScalar b1_ protected
Definition at line 162 of file kOmegaSSTBase.H.
dimensionedScalar c1_ protected
Definition at line 163 of file kOmegaSSTBase.H.
Switch F3_ protected
Flag to include the F3 term.
Definition at line 168 of file kOmegaSSTBase.H.
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 179 of file kOmegaSSTBase.H.
volScalarField k_ protected
Definition at line 181 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::DkEff().
volScalarField omega_ protected
Definition at line 182 of file kOmegaSSTBase.H.
Referenced by kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::k().
Switch decayControl_ protected
Flag to include the decay control.
Definition at line 190 of file kOmegaSSTBase.H.
dimensionedScalar kInf_ protected
Definition at line 191 of file kOmegaSSTBase.H.
dimensionedScalar omegaInf_ protected
Definition at line 192 of file kOmegaSSTBase.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/Base/kOmegaSST/kOmegaSSTBase.H
src/TurbulenceModels/turbulenceModels/Base/kOmegaSST/kOmegaSSTBase.C