OpenFOAM: meshRefinement Class Reference
meshRefinement Class Reference
Helper class which maintains intersections of (changing) mesh with (static) surfaces.
Public Types
enum debugType {
MESH = (1 << 0), OBJINTERSECTIONS = (1 << 1), FEATURESEEDS = (1 << 2), ATTRACTION = (1 << 3),
LAYERINFO = (1 << 4)
}
Enumeration for what to debug. Used as a bit-pattern.
enum writeType {
WRITEMESH = (1 << 0), NOWRITEREFINEMENT = (1 << 1), WRITELEVELS = (1 << 2), WRITELAYERSETS = (1 << 3),
WRITELAYERFIELDS = (1 << 4)
}
Enumeration for what to write. Used as a bit-pattern.
enum mapType { MASTERONLY = 1, KEEPALL = 2, REMOVE = 4 }
Enumeration for how userdata is to be mapped upon refinement.
enum FaceMergeType { NONE, GEOMETRIC, IGNOREPATCH }
Enumeration for what to do with co-planar patch faces on a single.
Public Member Functions
ClassName ("meshRefinement")
Runtime type information.
meshRefinement (fvMesh &mesh, const scalar mergeDistance, const bool overwrite, const refinementSurfaces &, const refinementFeatures &, const shellSurfaces &, const shellSurfaces &, const labelUList &checkFaces, const bool dryRun)
Construct from components.
const fvMesh & mesh () const
Reference to mesh.
fvMesh & mesh ()
scalar mergeDistance () const
bool overwrite () const
Overwrite the mesh?
const word & oldInstance () const
(points)instance of mesh upon construction
const refinementSurfaces & surfaces () const
Reference to surface search engines.
const refinementFeatures & features () const
Reference to feature edge mesh.
const shellSurfaces & shells () const
Reference to refinement shells (regions)
const shellSurfaces & limitShells () const
Reference to limit shells (regions)
const hexRef8 & meshCutter () const
Reference to meshcutting engine.
const labelList & surfaceIndex () const
Per start-end edge the index of the surface hit.
labelList & surfaceIndex ()
const Map< label > & faceToCoupledPatch () const
For faces originating from processor faces store the original.
const List< Tuple2< mapType,
labelList > > & userFaceData () const
Additional face data that is maintained across.
List< Tuple2< mapType,
labelList > > & userFaceData ()
label countHits () const
Count number of intersections (local)
autoPtr< mapDistributePolyMesh > balance (const bool keepZoneFaces, const bool keepBaffles, const scalarField &cellWeights, decompositionMethod &decomposer, fvMeshDistribute &distributor)
Redecompose according to cell count.
labelList intersectedFaces () const
Get faces with intersection.
labelList intersectedPoints () const
Get points on surfaces with intersection and boundary faces.
bool isGap (const scalar, const vector &, const vector &, const vector &, const vector &) const
Is local topology a small gap?
bool isNormalGap (const scalar planarCos, const label level0, const vector &point0, const vector &normal0, const label level1, const vector &point1, const vector &normal1) const
Is local topology a small gap normal to the test vector.
labelList refineCandidates (const pointField &keepPoints, const scalar curvature, const scalar planarAngle, const bool featureRefinement, const bool featureDistanceRefinement, const bool internalRefinement, const bool surfaceRefinement, const bool curvatureRefinement, const bool smallFeatureRefinement, const bool gapRefinement, const bool bigGapRefinement, const bool spreadGapSize, const label maxGlobalCells, const label maxLocalCells) const
Calculate list of cells to refine.
void markOutsideFaces (const labelList &cellLevel, const labelList &neiLevel, const labelList &refineCell, bitSet &isOutsideFace) const
Mark faces on interface between set and rest.
label countFaceDirs (const bitSet &isOutsideFace, const label celli) const
Count number of faces on cell that are in set.
void growSet (const labelList &neiLevel, const bitSet &isOutsideFace, labelList &refineCell, label &nRefine) const
Add one layer of cells to set.
autoPtr< mapPolyMesh > removeGapCells (const scalar planarAngle, const labelList &minSurfaceLevel, const labelList &globalToMasterPatch, const label growIter)
Detect gapRefinement cells and remove them.
autoPtr< mapPolyMesh > refine (const labelList &cellsToRefine)
Refine some cells.
autoPtr< mapDistributePolyMesh > refineAndBalance (const string &msg, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &cellsToRefine, const scalar maxLoadUnbalance)
Refine some cells and rebalance.
autoPtr< mapDistributePolyMesh > balanceAndRefine (const string &msg, decompositionMethod &decomposer, fvMeshDistribute &distributor, const labelList &cellsToRefine, const scalar maxLoadUnbalance)
Balance before refining some cells.
labelList directionalRefineCandidates (const label maxGlobalCells, const label maxLocalCells, const labelList &currentLevel, const direction dir) const
Calculate list of cells to directionally refine.
autoPtr< mapPolyMesh > directionalRefine (const string &msg, const direction cmpt, const labelList &cellsToRefine)
Directionally refine in direction cmpt.
void baffleAndSplitMesh (const bool handleSnapProblems, const snapParameters &snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField &perpendicularAngle, const label nErodeCellZones, const dictionary &motionDict, Time &runTime, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const wordList &regionsInMesh, const pointField &locationsOutsideMesh, const writer< scalar > &leakPathFormatter)
Split off unreachable areas of mesh.
void mergeFreeStandingBaffles (const snapParameters &snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField &perpendicularAngle, const scalar planarAngle, const dictionary &motionDict, Time &runTime, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const pointField &locationsOutsideMesh, const writer< scalar > &leakPathFormatter)
Merge free-standing baffles.
autoPtr< mapPolyMesh > splitMesh (const label nBufferLayers, const label nErodeCellZones, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const wordList &regionsInMesh, const pointField &locationsOutsideMesh, const writer< scalar > &leakPathFormatter)
Split off (with optional buffer layers) unreachable areas.
autoPtr< mapPolyMesh > removeLimitShells (const label nBufferLayers, const label nErodeCellZones, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const wordList &regionsInMesh)
Remove cells from limitRegions if level -1.
autoPtr< mapPolyMesh > dupNonManifoldPoints (const localPointRegion &)
Find boundary points that connect to more than one cell.
autoPtr< mapPolyMesh > dupNonManifoldPoints ()
Find boundary points that connect to more than one cell.
autoPtr< mapPolyMesh > dupNonManifoldBoundaryPoints ()
Find boundary points that are on faceZones of type boundary.
autoPtr< mapPolyMesh > mergePoints (const labelList &pointToDuplicate)
Merge duplicate points.
autoPtr< mapPolyMesh > createBaffles (const labelList &ownPatch, const labelList &neiPatch)
Create baffle for every internal face where ownPatch != -1.
labelList getZones (const List< surfaceZonesInfo::faceZoneType > &fzTypes) const
Get zones of given type.
autoPtr< mapPolyMesh > createZoneBaffles (const labelList &zoneIDs, List< labelPair > &baffles, labelList &originatingFaceZone)
Create baffles for faces on faceZones. Return created baffles.
autoPtr< mapPolyMesh > mergeBaffles (const List< labelPair > &, const Map< label > &faceToPatch)
Merge baffles. Gets pairs of faces and boundary faces to move.
autoPtr< mapPolyMesh > mergeZoneBaffles (const bool doInternalZones, const bool doBaffleZones)
Merge all baffles on faceZones.
autoPtr< mapPolyMesh > zonify (const bool allowFreeStandingZoneFaces, const label nErodeCellZones, const pointField &locationsInMesh, const wordList &regionsInMesh, wordPairHashTable &zonesToFaceZone)
Put faces/cells into zones according to surface specification.
label addMeshedPatch (const word &name, const dictionary &)
Add patch originating from meshing. Update meshedPatches_.
labelList meshedPatches () const
Get patchIDs for patches added in addMeshedPatch.
label addFaceZone (const word &fzName, const word &masterPatch, const word &slavePatch, const surfaceZonesInfo::faceZoneType &fzType)
Add/lookup faceZone and update information. Return index of.
bool getFaceZoneInfo (const word &fzName, label &masterPatchID, label &slavePatchID, surfaceZonesInfo::faceZoneType &fzType) const
Lookup faceZone information. Return false if no information.
void selectSeparatedCoupledFaces (boolList &) const
Select coupled faces that are not collocated.
void updateIntersections (const labelList &changedFaces)
Find any intersection of surface. Store in surfaceIndex_.
autoPtr< mapPolyMesh > splitMeshRegions (const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const pointField &locationsInMesh, const pointField &locationsOutsideMesh, const writer< scalar > &leakPathFormatter)
Split mesh. Keep part containing point. Return empty map if.
void doSplitFaces (const labelList &splitFaces, const labelPairList &splits, polyTopoChange &meshMod) const
Split faces into two.
label splitFacesUndo (const labelList &splitFaces, const labelPairList &splits, const dictionary &motionDict, labelList &duplicateFace, List< labelPair > &baffles)
Split faces along diagonal. Maintain mesh quality. Return.
void distribute (const mapDistributePolyMesh &)
Update local numbering for mesh redistribution.
void updateMesh (const mapPolyMesh &, const labelList &changedFaces)
Update for external change to mesh. changedFaces are in new mesh.
void storeData (const labelList &pointsToStore, const labelList &facesToStore, const labelList &cellsToStore)
Signal points/face/cells for which to store data.
void updateMesh (const mapPolyMesh &, const labelList &changedFaces, const Map< label > &pointsToRestore, const Map< label > &facesToRestore, const Map< label > &cellsToRestore)
Update local numbering + undo.
label mergePatchFaces (const scalar minCos, const scalar concaveCos, const label mergeSize, const labelList &patchIDs, const meshRefinement::FaceMergeType mergeType)
Merge coplanar faces if sets are of size mergeSize.
label mergePatchFacesUndo (const scalar minCos, const scalar concaveCos, const labelList &patchIDs, const dictionary &motionDict, const labelList &preserveFaces, const meshRefinement::FaceMergeType mergeType)
Merge coplanar faces. preserveFaces is != -1 for faces.
autoPtr< mapPolyMesh > doRemovePoints (removePoints &pointRemover, const boolList &pointCanBeDeleted)
autoPtr< mapPolyMesh > doRestorePoints (removePoints &pointRemover, const labelList &facesToRestore)
labelList collectFaces (const labelList &candidateFaces, const labelHashSet &set) const
labelList growFaceCellFace (const labelUList &set) const
labelList growFaceCellFace (const labelHashSet &set) const
label mergeEdgesUndo (const scalar minCos, const dictionary &motionDict)
Merge edges, maintain mesh quality. Return global number.
void checkData ()
Debugging: check that all faces still obey start()>end()
template<class T >
void testSyncBoundaryFaceList (const scalar mergeDistance, const string &, const UList< T > &, const UList< T > &) const
Compare two lists over all boundary faces.
void printMeshInfo (const bool, const string &) const
Print some mesh stats.
word timeName () const
Replacement for Time::timeName() that returns oldInstance (if overwrite_)
void setInstance (const fileName &)
Set instance of all local IOobjects.
bool write () const
Write mesh and all data.
void dumpRefinementLevel () const
Write refinement level as volScalarFields for postprocessing.
void dumpIntersections (const fileName &prefix) const
Debug: Write intersection information to OBJ format.
void write (const debugType debugFlags, const writeType writeFlags, const fileName &) const
Do any one of above IO functions.
Static Public Member Functions
static autoPtr
< indirectPrimitivePatch > makePatch (const polyMesh &, const labelList &)
Create patch from set of patches.
static tmp< pointVectorField > makeDisplacementField (const pointMesh &pMesh, const labelList &adaptPatchIDs)
Helper function to make a pointVectorField with correct.
static void checkCoupledFaceZones (const polyMesh &)
Helper function: check that face zones are synced.
static void calculateEdgeWeights (const polyMesh &mesh, const bitSet &isMasterEdge, const labelList &meshPoints, const edgeList &edges, scalarField &edgeWeights, scalarField &invSumWeight)
Helper: calculate edge weights (1/length)
template<class Type >
static void weightedSum (const polyMesh &mesh, const bitSet &isMasterEdge, const labelList &meshPoints, const edgeList &edges, const scalarField &edgeWeights, const Field< Type > &data, Field< Type > &sum)
Helper: weighted sum (over all subset of mesh points) by.
static List< labelPair > subsetBaffles (const polyMesh &mesh, const labelList &zoneIDs, const List< labelPair > &baffles)
Subset baffles according to zones.
static label appendPatch (fvMesh &, const label insertPatchi, const word &, const dictionary &)
Helper:append patch to end of mesh.
static label addPatch (fvMesh &, const word &name, const dictionary &)
Helper:add patch to mesh. Update all registered fields.
static label findRegion (const polyMesh &, const labelList &cellRegion, const vector &perturbVec, const point &p)
Find region point is in. Uses optional perturbation to re-test.
static label findRegions (const polyMesh &, const vector &perturbVec, const pointField &locationsInMesh, const pointField &locationsOutsideMesh, const writer< scalar > &leakPathFormatter, const label nRegions, labelList &cellRegion, const boolList &blockedFace)
Find regions points are in.
template<class T >
static void updateList (const labelList &newToOld, const T &nullValue, List< T > &elems)
Helper: reorder list according to map.
static void testSyncPointList (const string &msg, const polyMesh &mesh, const List< scalar > &fld)
static void testSyncPointList (const string &msg, const polyMesh &mesh, const List< point > &fld)
template<class T >
static void collectAndPrint (const UList< point > &points, const UList< T > &data)
Print list according to (collected and) sorted coordinate.
static bitSet getMasterPoints (const polyMesh &mesh, const labelList &meshPoints)
Determine master point for subset of points. If coupled.
static bitSet getMasterEdges (const polyMesh &mesh, const labelList &meshEdges)
Determine master edge for subset of edges. If coupled.
static void removeFiles (const polyMesh &)
Helper: remove all relevant files from mesh instance.
template<class T >
static T gAverage (const bitSet &isMasterElem, const UList< T > &values)
Helper: calculate average.
static writeType writeLevel ()
Get/set write level.
static void writeLevel (const writeType)
template<class EnumContainer >
static int readFlags (const EnumContainer &namedEnum, const wordList &words)
Helper: convert wordList into bit pattern using provided Enum.
template<class Type >
static Type get (const dictionary &dict, const word &keyword, const bool noExit, enum keyType::option matchOpt=keyType::REGEX, const Type &defaultValue=Zero)
Wrapper around dictionary::get which does not exit.
static const dictionary & subDict (const dictionary &dict, const word &keyword, const bool noExit)
Wrapper around dictionary::subDict which does not exit.
static ITstream & lookup (const dictionary &dict, const word &keyword, const bool noExit)
Wrapper around dictionary::lookup which does not exit.
Static Public Attributes
static const Enum< debugType > debugTypeNames
static const Enum< writeType > writeTypeNames
Detailed Description
Helper class which maintains intersections of (changing) mesh with (static) surfaces.
Maintains
per face any intersections of the cc-cc segment with any of the surfaces
Source files
meshRefinement.H
meshRefinement.C
meshRefinementBaffles.C
meshRefinementGapRefine.C
meshRefinementMerge.C
meshRefinementProblemCells.C
meshRefinementRefine.C
Definition at line 82 of file meshRefinement.H.
Member Enumeration Documentation
enum debugType
Enumeration for what to debug. Used as a bit-pattern.
Enumerator
MESH
OBJINTERSECTIONS
FEATURESEEDS
ATTRACTION
LAYERINFO
Definition at line 91 of file meshRefinement.H.
enum writeType
Enumeration for what to write. Used as a bit-pattern.
Enumerator
WRITEMESH
NOWRITEREFINEMENT
WRITELEVELS
WRITELAYERSETS
WRITELAYERFIELDS
Definition at line 113 of file meshRefinement.H.
enum mapType
Enumeration for how userdata is to be mapped upon refinement.
Enumerator
MASTERONLY
maintain master only
KEEPALL
have slaves (upon refinement) from master
REMOVE
set value to -1 any face that was refined
Definition at line 127 of file meshRefinement.H.
enum FaceMergeType
Enumeration for what to do with co-planar patch faces on a single.
cell
Enumerator
NONE
GEOMETRIC
IGNOREPATCH
Definition at line 139 of file meshRefinement.H.
Constructor & Destructor Documentation
meshRefinement (fvMesh & mesh, const scalar mergeDistance, const bool overwrite, const refinementSurfaces & surfaces, const refinementFeatures & features, const shellSurfaces & shells, const shellSurfaces & limitShells, const labelUList & checkFaces, const bool dryRun)
Construct from components.
Definition at line 1425 of file meshRefinement.C.
Member Function Documentation
ClassName ("meshRefinement")
Runtime type information.
const fvMesh& mesh () const inline
Reference to mesh.
Definition at line 1135 of file meshRefinement.H.
fvMesh& mesh () inline
Definition at line 1139 of file meshRefinement.H.
scalar mergeDistance () const inline
Definition at line 1144 of file meshRefinement.H.
bool overwrite () const inline
Overwrite the mesh?
Definition at line 1152 of file meshRefinement.H.
const word& oldInstance () const inline
(points)instance of mesh upon construction
Definition at line 1160 of file meshRefinement.H.
const refinementSurfaces& surfaces () const inline
Reference to surface search engines.
Definition at line 1168 of file meshRefinement.H.
const refinementFeatures& features () const inline
Reference to feature edge mesh.
Definition at line 1176 of file meshRefinement.H.
const shellSurfaces& shells () const inline
Reference to refinement shells (regions)
Definition at line 1184 of file meshRefinement.H.
const shellSurfaces& limitShells () const inline
Reference to limit shells (regions)
Definition at line 1192 of file meshRefinement.H.
const hexRef8& meshCutter () const inline
Reference to meshcutting engine.
Definition at line 1200 of file meshRefinement.H.
const Foam::labelList & surfaceIndex () const
Per start-end edge the index of the surface hit.
Definition at line 1474 of file meshRefinement.C.
Foam::labelList & surfaceIndex ()
Definition at line 1487 of file meshRefinement.C.
const Map<label>& faceToCoupledPatch () const inline
For faces originating from processor faces store the original.
patch
Definition at line 1217 of file meshRefinement.H.
const List<Tuple2<mapType, labelList> >& userFaceData () const inline
Additional face data that is maintained across.
topo changes. Every entry is a list over all faces. Bit of a hack. Additional flag to say whether to maintain master only (false) or increase set to account for face-from-face.
Definition at line 1229 of file meshRefinement.H.
List<Tuple2<mapType, labelList> >& userFaceData () inline
Definition at line 1234 of file meshRefinement.H.
Foam::label countHits () const
Count number of intersections (local)
Definition at line 1497 of file meshRefinement.C.
References Foam::identity().
Foam::autoPtr< Foam::mapDistributePolyMesh > balance (const bool keepZoneFaces, const bool keepBaffles, const scalarField & cellWeights, decompositionMethod & decomposer, fvMeshDistribute & distributor)
Redecompose according to cell count.
keepZoneFaces : find all faceZones from zoned surfaces and keep owner and neighbour together keepBaffles : find all baffles and keep them together
Definition at line 1518 of file meshRefinement.C.
Foam::labelList intersectedFaces () const
Get faces with intersection.
Definition at line 1768 of file meshRefinement.C.
Foam::labelList intersectedPoints () const
Get points on surfaces with intersection and boundary faces.
Definition at line 1796 of file meshRefinement.C.
Foam::autoPtr< Foam::indirectPrimitivePatch > makePatch (const polyMesh & mesh, const labelList & patchIDs) static
Create patch from set of patches.
Definition at line 1869 of file meshRefinement.C.
Referenced by snappySnapDriver::repatchToSurface().
Foam::tmp< Foam::pointVectorField > makeDisplacementField (const pointMesh & pMesh, const labelList & adaptPatchIDs) static
Helper function to make a pointVectorField with correct.
bcs for mesh movement:
adaptPatchIDs : fixedValue
processor : calculated (so free to move)
cyclic/wedge/symmetry : slip
other : slip
Definition at line 1911 of file meshRefinement.C.
void checkCoupledFaceZones (const polyMesh & mesh) static
Helper function: check that face zones are synced.
Definition at line 1964 of file meshRefinement.C.
void calculateEdgeWeights (const polyMesh & mesh, const bitSet & isMasterEdge, const labelList & meshPoints, const edgeList & edges, scalarField & edgeWeights, scalarField & invSumWeight) static
Helper: calculate edge weights (1/length)
Definition at line 2052 of file meshRefinement.C.
Referenced by fieldSmoother::minSmoothField().
void weightedSum (const polyMesh & mesh, const bitSet & isMasterEdge, const labelList & meshPoints, const edgeList & edges, const scalarField & edgeWeights, const Field< Type > & data, Field< Type > & sum) static
Helper: weighted sum (over all subset of mesh points) by.
summing contribution from (master) edges
Definition at line 264 of file meshRefinementTemplates.C.
Referenced by fieldSmoother::minSmoothField().
bool isGap (const scalar planarCos, const vector & point0, const vector & normal0, const vector & point1, const vector & normal1) const
Is local topology a small gap?
Hits differ and angles are oppositeish and
hits have a normal distance
Definition at line 1533 of file meshRefinementRefine.C.
References d, Foam::mag(), VectorSpace< Vector< scalar >, scalar, 3 >::zero, and Foam::Zero.
bool isNormalGap (const scalar planarCos, const label level0, const vector & point0, const vector & normal0, const label level1, const vector & point1, const vector & normal1) const
Is local topology a small gap normal to the test vector.
Hits differ and angles are oppositeish and
hits have a normal distance
Definition at line 1583 of file meshRefinementRefine.C.
References Foam::cos(), d, Foam::degToRad(), Foam::mag(), VectorSpace< Vector< scalar >, scalar, 3 >::zero, and Foam::Zero.
Foam::labelList refineCandidates (const pointField & keepPoints, const scalar curvature, const scalar planarAngle, const bool featureRefinement, const bool featureDistanceRefinement, const bool internalRefinement, const bool surfaceRefinement, const bool curvatureRefinement, const bool smallFeatureRefinement, const bool gapRefinement, const bool bigGapRefinement, const bool spreadGapSize, const label maxGlobalCells, const label maxLocalCells) const
Calculate list of cells to refine.
Disable refinement shortcut. nAllowRefine is per processor limit.
Definition at line 2043 of file meshRefinementRefine.C.
References Foam::cos(), Foam::degToRad(), Foam::endl(), forAll, Foam::Info, Foam::labelMax, Foam::max(), UPstream::nProcs(), List< T >::setSize(), and UList< T >::size().
void markOutsideFaces (const labelList & cellLevel, const labelList & neiLevel, const labelList & refineCell, bitSet & isOutsideFace) const
Mark faces on interface between set and rest.
(and same cell level)
Definition at line 157 of file meshRefinementBlock.C.
References polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), bitSet::set(), PackedList< Width >::setSize(), syncTools::swapBoundaryCellList(), and Foam::Zero.
Foam::label countFaceDirs (const bitSet & isOutsideFace, const label celli) const
Count number of faces on cell that are in set.
Definition at line 215 of file meshRefinementBlock.C.
void growSet (const labelList & neiLevel, const bitSet & isOutsideFace, labelList & refineCell, label & nRefine) const
Add one layer of cells to set.
Definition at line 266 of file meshRefinementBlock.C.
Foam::autoPtr< Foam::mapPolyMesh > removeGapCells (const scalar planarAngle, const labelList & minSurfaceLevel, const labelList & globalToMasterPatch, const label growIter)
Detect gapRefinement cells and remove them.
Definition at line 921 of file meshRefinementBlock.C.
Foam::autoPtr< Foam::mapPolyMesh > refine (const labelList & cellsToRefine)
Refine some cells.
Definition at line 2353 of file meshRefinementRefine.C.
References mapPolyMesh::preMotionPoints().
Foam::autoPtr< Foam::mapDistributePolyMesh > refineAndBalance (const string & msg, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & cellsToRefine, const scalar maxLoadUnbalance)
Refine some cells and rebalance.
Definition at line 2395 of file meshRefinementRefine.C.
Foam::autoPtr< Foam::mapDistributePolyMesh > balanceAndRefine (const string & msg, decompositionMethod & decomposer, fvMeshDistribute & distributor, const labelList & cellsToRefine, const scalar maxLoadUnbalance)
Balance before refining some cells.
Definition at line 2496 of file meshRefinementRefine.C.
References Foam::checkData(), Foam::expressions::patchExpr::debug, Foam::endl(), forAll, i, Foam::Info, Foam::mag(), UPstream::nProcs(), Foam::Pout, Foam::returnReduce(), timeName, and Foam::vtk::write().
Foam::labelList directionalRefineCandidates (const label maxGlobalCells, const label maxLocalCells, const labelList & currentLevel, const direction dir) const
Calculate list of cells to directionally refine.
Definition at line 2656 of file meshRefinementRefine.C.
References Foam::endl(), and Foam::Info.
Foam::autoPtr< Foam::mapPolyMesh > directionalRefine (const string & msg, const direction cmpt, const labelList & cellsToRefine)
Directionally refine in direction cmpt.
Definition at line 2756 of file meshRefinementRefine.C.
void baffleAndSplitMesh (const bool handleSnapProblems, const snapParameters & snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField & perpendicularAngle, const label nErodeCellZones, const dictionary & motionDict, Time & runTime, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const wordList & regionsInMesh, const pointField & locationsOutsideMesh, const writer< scalar > & leakPathFormatter)
Split off unreachable areas of mesh.
Definition at line 3549 of file meshRefinementBaffles.C.
References Foam::checkData(), cpuTimePosix::cpuTimeIncrement(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::Info, Foam::nl, Time::path(), Foam::Pout, Foam::returnReduce(), runTime, timeName, and Foam::vtk::write().
void mergeFreeStandingBaffles (const snapParameters & snapParams, const bool useTopologicalSnapDetection, const bool removeEdgeConnectedCells, const scalarField & perpendicularAngle, const scalar planarAngle, const dictionary & motionDict, Time & runTime, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const pointField & locationsOutsideMesh, const writer< scalar > & leakPathFormatter)
Merge free-standing baffles.
Definition at line 3730 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > splitMesh (const label nBufferLayers, const label nErodeCellZones, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const wordList & regionsInMesh, const pointField & locationsOutsideMesh, const writer< scalar > & leakPathFormatter)
Split off (with optional buffer layers) unreachable areas.
of mesh. Does not introduce baffles.
Definition at line 3825 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > removeLimitShells (const label nBufferLayers, const label nErodeCellZones, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const wordList & regionsInMesh)
Remove cells from limitRegions if level -1.
Definition at line 4128 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldPoints (const localPointRegion & regionSide)
Find boundary points that connect to more than one cell.
region and split them.
Definition at line 4212 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldPoints ()
Find boundary points that connect to more than one cell.
region and split them.
Definition at line 4271 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > dupNonManifoldBoundaryPoints ()
Find boundary points that are on faceZones of type boundary.
and duplicate them
Definition at line 4350 of file meshRefinementBaffles.C.
References surfaceZonesInfo::BAFFLE, surfaceZonesInfo::BOUNDARY, Foam::endl(), surfaceZonesInfo::faceZoneTypeNames, forAll, i, Foam::Info, surfaceZonesInfo::INTERNAL, j, Foam::max(), n, Foam::returnReduce(), and syncTools::syncPointList().
Foam::autoPtr< Foam::mapPolyMesh > mergePoints (const labelList & pointToDuplicate)
Merge duplicate points.
Definition at line 4281 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > createBaffles (const labelList & ownPatch, const labelList & neiPatch)
Create baffle for every internal face where ownPatch != -1.
External faces get repatched according to ownPatch (neiPatch should be -1 for these)
Redo the intersections on the newly create baffle faces. Note that
this changes also the cell centre positions.
Definition at line 474 of file meshRefinementBaffles.C.
Foam::labelList getZones (const List< surfaceZonesInfo::faceZoneType > & fzTypes) const
Get zones of given type.
Definition at line 652 of file meshRefinementBaffles.C.
Foam::List< Foam::labelPair > subsetBaffles (const polyMesh & mesh, const labelList & zoneIDs, const List< labelPair > & baffles) static
Subset baffles according to zones.
Definition at line 679 of file meshRefinementBaffles.C.
References List< T >::append(), polyMesh::faceZones(), forAll, i, primitiveMesh::nFaces(), p, UList< T >::size(), and zoneID.
Foam::autoPtr< Foam::mapPolyMesh > createZoneBaffles (const labelList & zoneIDs, List< labelPair > & baffles, labelList & originatingFaceZone)
Create baffles for faces on faceZones. Return created baffles.
(= pairs of faces) and corresponding faceZone
Definition at line 712 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > mergeBaffles (const List< labelPair > & couples, const Map< label > & faceToPatch)
Merge baffles. Gets pairs of faces and boundary faces to move.
onto (coupled) patches
Definition at line 1146 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > mergeZoneBaffles (const bool doInternalZones, const bool doBaffleZones)
Merge all baffles on faceZones.
Definition at line 1326 of file meshRefinementBaffles.C.
Foam::autoPtr< Foam::mapPolyMesh > zonify (const bool allowFreeStandingZoneFaces, const label nErodeCellZones, const pointField & locationsInMesh, const wordList & regionsInMesh, wordPairHashTable & zonesToFaceZone)
Put faces/cells into zones according to surface specification.
Returns null if no zone surfaces present. Regions containing locationsInMesh/regionsInMesh will be put in corresponding cellZone. keepPoints is for backwards compatibility and sets all yet unassigned cells to be non-zoned (zone = -1)
Per face index of faceZone or -1
Definition at line 4449 of file meshRefinementBaffles.C.
References Foam::abort(), surfaceZonesInfo::addCellZonesToMesh(), surfaceZonesInfo::addFaceZone(), surfaceZonesInfo::addFaceZonesToMesh(), polyTopoChange::changeMesh(), polyPatch::coupled(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, HashTable< T, Key, Hash >::find(), Pair< T >::flip(), forAll, syncTools::getMasterFaces(), surfaceZonesInfo::getNamedSurfaces(), i, Foam::indent(), Foam::Info, HashTable< T, Key, Hash >::insert(), Pstream::mapCombineGather(), Pstream::mapCombineScatter(), n, zone::name(), Foam::nl, nZones, Foam::foamVersion::patch, Foam::returnReduce(), UList< T >::size(), HashTable< T, Key, Hash >::size(), HashTable< T, Key, Hash >::sortedToc(), polyPatch::start(), syncTools::swapBoundaryCellList(), bitSet::test(), timeName, and OBJstream::write().
Foam::label appendPatch (fvMesh & mesh, const label insertPatchi, const word & patchName, const dictionary & patchDict) static
Helper:append patch to end of mesh.
Definition at line 2108 of file meshRefinement.C.
Foam::label addPatch (fvMesh & mesh, const word & name, const dictionary & patchInfo) static
Helper:add patch to mesh. Update all registered fields.
Used by addMeshedPatch to add patches originating from surfaces.
Definition at line 2206 of file meshRefinement.C.
Foam::label addMeshedPatch (const word & name, const dictionary & patchInfo)
Add patch originating from meshing. Update meshedPatches_.
Definition at line 2284 of file meshRefinement.C.
Foam::labelList meshedPatches () const
Get patchIDs for patches added in addMeshedPatch.
Definition at line 2334 of file meshRefinement.C.
Foam::label addFaceZone (const word & fzName, const word & masterPatch, const word & slavePatch, const surfaceZonesInfo::faceZoneType & fzType)
Add/lookup faceZone and update information. Return index of.
faceZone
Definition at line 2361 of file meshRefinement.C.
bool getFaceZoneInfo (const word & fzName, label & masterPatchID, label & slavePatchID, surfaceZonesInfo::faceZoneType & fzType) const
Lookup faceZone information. Return false if no information.
for faceZone
Definition at line 2385 of file meshRefinement.C.
void selectSeparatedCoupledFaces (boolList & selected) const
Select coupled faces that are not collocated.
Definition at line 2413 of file meshRefinement.C.
void updateIntersections (const labelList & changedFaces)
Find any intersection of surface. Store in surfaceIndex_.
Definition at line 267 of file meshRefinement.C.
Foam::label findRegion (const polyMesh & mesh, const labelList & cellRegion, const vector & perturbVec, const point & p) static
Find region point is in. Uses optional perturbation to re-test.
Definition at line 2440 of file meshRefinement.C.
Foam::label findRegions (const polyMesh & mesh, const vector & perturbVec, const pointField & locationsInMesh, const pointField & locationsOutsideMesh, const writer< scalar > & leakPathFormatter, const label nRegions, labelList & cellRegion, const boolList & blockedFace) static
Find regions points are in.
Returns
number of cells to be removed
Definition at line 2477 of file meshRefinement.C.
References polyMesh::boundaryMesh(), fileName::clean(), coordSet::coordFormatNames, coordSet::DISTANCE, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Pstream::gatherList(), writer< Type >::getFileName(), TimePaths::globalPath(), polyBoundaryMesh::groupPatchIDs(), i, UPstream::master(), Foam::max(), Foam::mkDir(), UPstream::myProcNo(), n, primitiveMesh::nCells(), Foam::nl, UPstream::nProcs(), IOstream::opened(), functionObject::outputPrefix, points, polyMesh::pointsInstance(), Foam::reduce(), Pstream::scatter(), List< T >::setSize(), UList< T >::size(), Foam::sortedOrder(), objectRegistry::time(), writer< Type >::write(), and Foam::Zero.
Foam::autoPtr< Foam::mapPolyMesh > splitMeshRegions (const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const pointField & locationsInMesh, const pointField & locationsOutsideMesh, const writer< scalar > & leakPathFormatter)
Split mesh. Keep part containing point. Return empty map if.
no cells removed.
Definition at line 2726 of file meshRefinement.C.
void doSplitFaces (const labelList & splitFaces, const labelPairList & splits, polyTopoChange & meshMod) const
Split faces into two.
Definition at line 938 of file meshRefinement.C.
Foam::label splitFacesUndo (const labelList & splitFaces, const labelPairList & splits, const dictionary & motionDict, labelList & duplicateFace, List< labelPair > & baffles)
Split faces along diagonal. Maintain mesh quality. Return.
total number of faces split.
Definition at line 1057 of file meshRefinement.C.
void distribute (const mapDistributePolyMesh & map)
Update local numbering for mesh redistribution.
Definition at line 2831 of file meshRefinement.C.
void updateMesh (const mapPolyMesh & map, const labelList & changedFaces)
Update for external change to mesh. changedFaces are in new mesh.
face labels.
Definition at line 2893 of file meshRefinement.C.
Referenced by meshRefinement::mergePatchFaces().
void updateList (const labelList & newToOld, const T & nullValue, List< T > & elems) static
Helper: reorder list according to map.
Definition at line 31 of file meshRefinementTemplates.C.
References forAll, i, and UList< T >::size().
void storeData (const labelList & pointsToStore, const labelList & facesToStore, const labelList & cellsToStore)
Signal points/face/cells for which to store data.
Definition at line 2905 of file meshRefinement.C.
void updateMesh (const mapPolyMesh & map, const labelList & changedFaces, const Map< label > & pointsToRestore, const Map< label > & facesToRestore, const Map< label > & cellsToRestore)
Update local numbering + undo.
Data to restore given as new pointlabel + stored pointlabel (i.e. what was in pointsToStore)
Definition at line 2922 of file meshRefinement.C.
Foam::label mergePatchFaces (const scalar minCos, const scalar concaveCos, const label mergeSize, const labelList & patchIDs, const meshRefinement::FaceMergeType mergeType)
Merge coplanar faces if sets are of size mergeSize.
(usually 4)
Definition at line 35 of file meshRefinementMerge.C.
References polyMesh::boundaryMesh(), polyTopoChange::changeMesh(), fvMesh::clearOut(), polyPatch::coupled(), Foam::endl(), polyMesh::faceOwner(), forAll, combineFaces::getMergeSets(), meshRefinement::growFaceCellFace(), mapPolyMesh::hasMotionPoints(), i, Foam::Info, fvMesh::movePoints(), primitiveMesh::nBoundaryFaces(), Foam::nl, Foam::foamVersion::patch, patches, mapPolyMesh::preMotionPoints(), Foam::returnReduce(), mapPolyMesh::reverseFaceMap(), polyMesh::setInstance(), combineFaces::setRefinement(), polyPatch::start(), meshRefinement::timeName(), combineFaces::updateMesh(), fvMesh::updateMesh(), and meshRefinement::updateMesh().
Foam::label mergePatchFacesUndo (const scalar minCos, const scalar concaveCos, const labelList & patchIDs, const dictionary & motionDict, const labelList & preserveFaces, const meshRefinement::FaceMergeType mergeType)
Merge coplanar faces. preserveFaces is != -1 for faces.
to be preserved
Definition at line 243 of file meshRefinementMerge.C.
References polyTopoChange::changeMesh(), Foam::checkData(), motionSmootherAlgo::checkMesh(), polyPatch::coupled(), Foam::expressions::patchExpr::debug, Foam::endl(), forAll, forAllConstIters, combineFaces::getMergeSets(), i, Foam::Info, Foam::inplaceMapKey(), IOobject::instance(), iter, j, combineFaces::masterFace(), meshRefinement::MESH, Foam::nl, IOobject::objectPath(), Foam::foamVersion::patch, patches, Foam::Pout, Foam::returnReduce(), combineFaces::savedPointLabels(), set(), combineFaces::setRefinement(), combineFaces::setUnrefinement(), HashTable< T, Key, Hash >::size(), polyPatch::start(), timeName, combineFaces::updateMesh(), Ostream::write(), Foam::vtk::write(), and regIOobject::write().
Foam::autoPtr< Foam::mapPolyMesh > doRemovePoints (removePoints & pointRemover, const boolList & pointCanBeDeleted)
Definition at line 615 of file meshRefinementMerge.C.
Foam::autoPtr< Foam::mapPolyMesh > doRestorePoints (removePoints & pointRemover, const labelList & facesToRestore)
Definition at line 673 of file meshRefinementMerge.C.
Foam::labelList collectFaces (const labelList & candidateFaces, const labelHashSet & set) const
Definition at line 747 of file meshRefinementMerge.C.
Foam::labelList growFaceCellFace (const labelUList & set) const
Definition at line 810 of file meshRefinementMerge.C.
Referenced by meshRefinement::mergePatchFaces().
Foam::labelList growFaceCellFace (const labelHashSet & set) const
Definition at line 833 of file meshRefinementMerge.C.
Foam::label mergeEdgesUndo (const scalar minCos, const dictionary & motionDict)
Merge edges, maintain mesh quality. Return global number.
of edges merged
Definition at line 857 of file meshRefinementMerge.C.
void checkData ()
Debugging: check that all faces still obey start()>end()
Definition at line 663 of file meshRefinement.C.
void testSyncPointList (const string & msg, const polyMesh & mesh, const List< scalar > & fld) static
Definition at line 570 of file meshRefinement.C.
void testSyncPointList (const string & msg, const polyMesh & mesh, const List< point > & fld) static
Definition at line 617 of file meshRefinement.C.
void testSyncBoundaryFaceList (const scalar mergeDistance, const string & msg, const UList< T > & faceData, const UList< T > & syncedFaceData) const
Compare two lists over all boundary faces.
Definition at line 98 of file meshRefinementTemplates.C.
void collectAndPrint (const UList< point > & points, const UList< T > & data) static
Print list according to (collected and) sorted coordinate.
Definition at line 155 of file meshRefinementTemplates.C.
Foam::bitSet getMasterPoints (const polyMesh & mesh, const labelList & meshPoints) static
Determine master point for subset of points. If coupled.
chooses only one
Definition at line 3068 of file meshRefinement.C.
Referenced by snappySnapDriver::detectNearSurfaces(), and medialAxisMeshMover::~medialAxisMeshMover().
Foam::bitSet getMasterEdges (const polyMesh & mesh, const labelList & meshEdges) static
Determine master edge for subset of edges. If coupled.
chooses only one
Definition at line 3104 of file meshRefinement.C.
Referenced by medialAxisMeshMover::~medialAxisMeshMover().
void printMeshInfo (const bool debug, const string & msg) const
Print some mesh stats.
Definition at line 3139 of file meshRefinement.C.
Foam::word timeName () const
Replacement for Time::timeName() that returns oldInstance (if overwrite_)
Definition at line 3192 of file meshRefinement.C.
Referenced by meshRefinement::mergePatchFaces().
void setInstance (const fileName & inst)
Set instance of all local IOobjects.
Definition at line 870 of file meshRefinement.C.
bool write () const
Write mesh and all data.
Definition at line 3032 of file meshRefinement.C.
void dumpRefinementLevel () const
Write refinement level as volScalarFields for postprocessing.
Definition at line 3203 of file meshRefinement.C.
void dumpIntersections (const fileName & prefix) const
Debug: Write intersection information to OBJ format.
Definition at line 3265 of file meshRefinement.C.
void write (const debugType debugFlags, const writeType writeFlags, const fileName & prefix) const
Do any one of above IO functions.
Definition at line 3334 of file meshRefinement.C.
void removeFiles (const polyMesh & mesh) static
Helper: remove all relevant files from mesh instance.
Definition at line 3366 of file meshRefinement.C.
T gAverage (const bitSet & isMasterElem, const UList< T > & values) static
Helper: calculate average.
Definition at line 55 of file meshRefinementTemplates.C.
Referenced by fieldSmoother::minSmoothField().
Foam::meshRefinement::writeType writeLevel () static
Get/set write level.
Definition at line 3390 of file meshRefinement.C.
void writeLevel (const writeType flags) static
Definition at line 3396 of file meshRefinement.C.
int readFlags (const EnumContainer & namedEnum, const wordList & words) static
Helper: convert wordList into bit pattern using provided Enum.
Definition at line 246 of file meshRefinementTemplates.C.
Type get (const dictionary & dict, const word & keyword, const bool noExit, enum keyType::option matchOpt = keyType::REGEX, const Type & defaultValue = Zero) static
Wrapper around dictionary::get which does not exit.
Definition at line 323 of file meshRefinementTemplates.C.
const Foam::dictionary & subDict (const dictionary & dict, const word & keyword, const bool noExit) static
Wrapper around dictionary::subDict which does not exit.
Definition at line 3415 of file meshRefinement.C.
References dictionary::csearch(), FatalIOErrorInFunction, dictionary::name(), dictionary::null, and keyType::REGEX.
Foam::ITstream & lookup (const dictionary & dict, const word & keyword, const bool noExit) static
Wrapper around dictionary::lookup which does not exit.
Definition at line 3451 of file meshRefinement.C.
Member Data Documentation
const Foam::Enum< Foam::meshRefinement::debugType > debugTypeNames static
Definition at line 100 of file meshRefinement.H.
const Foam::Enum< Foam::meshRefinement::writeType > writeTypeNames static
Definition at line 122 of file meshRefinement.H.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/meshRefinement/meshRefinement.H
src/mesh/snappyHexMesh/meshRefinement/meshRefinement.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementBaffles.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementBlock.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementGapRefine.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementMerge.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementProblemCells.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementRefine.C
src/mesh/snappyHexMesh/meshRefinement/meshRefinementTemplates.C