OpenFOAM: lduPrimitiveProcessorInterface Class Reference
lduPrimitiveProcessorInterface Class Reference
Concrete implementation of processor interface. Used to temporarily store settings.
Public Member Functions
TypeName ("calculatedProcessor")
Runtime type information.
lduPrimitiveProcessorInterface (const labelUList &faceCells, const label myProcNo, const label neighbProcNo, const tensorField &forwardT, const int tag, const label comm=UPstream::worldComm)
Construct from components.
virtual ~lduPrimitiveProcessorInterface ()=default
Destructor.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise neighbour field transfer.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Transfer and return internal field adjacent to the interface.
virtual label comm () const
Return communicator used for sending.
virtual int myProcNo () const
Return processor number (rank in communicator)
virtual int neighbProcNo () const
Return neighbour processor number (rank in communicator)
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual int tag () const
Return message tag used for sending.
int & tag ()
Return message tag used for sending.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()=default
Construct null.
virtual ~lduInterface ()=default
Destructor.
Public Member Functions inherited from processorLduInterface
TypeName ("processorLduInterface")
Runtime type information.
processorLduInterface ()=default
Construct null.
virtual ~processorLduInterface ()=default
Destructor.
template<class Type >
void send (const Pstream::commsTypes commsType, const UList< Type > &f) const
Raw send function.
template<class Type >
void receive (const Pstream::commsTypes commsType, UList< Type > &f) const
Raw receive function.
template<class Type >
tmp< Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
Raw receive function returning field.
template<class Type >
void compressedSend (const Pstream::commsTypes commsType, const UList< Type > &f) const
Raw send function with data compression.
template<class Type >
void compressedReceive (const Pstream::commsTypes commsType, UList< Type > &f) const
Raw receive function with data compression.
template<class Type >
tmp< Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Raw receive function with data compression returning field.
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Detailed Description
Concrete implementation of processor interface. Used to temporarily store settings.
Source files
lduPrimitiveProcessorInterface.H
lduPrimitiveProcessorInterface.C
Definition at line 49 of file lduPrimitiveProcessorInterface.H.
Constructor & Destructor Documentation
lduPrimitiveProcessorInterface (const labelUList & faceCells, const label myProcNo, const label neighbProcNo, const tensorField & forwardT, const int tag, const label comm = UPstream::worldComm)
Construct from components.
Definition at line 35 of file lduPrimitiveProcessorInterface.C.
virtual ~lduPrimitiveProcessorInterface () virtual default
Destructor.
Member Function Documentation
TypeName ("calculatedProcessor")
Runtime type information.
virtual const labelUList& faceCells () const inline virtual
Return faceCell addressing.
Implements lduInterface.
Definition at line 137 of file lduPrimitiveProcessorInterface.H.
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements lduInterface.
Definition at line 57 of file lduPrimitiveProcessorInterface.C.
void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Initialise neighbour field transfer.
Reimplemented from lduInterface.
Definition at line 72 of file lduPrimitiveProcessorInterface.C.
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const virtual
Transfer and return internal field adjacent to the interface.
Implements lduInterface.
Definition at line 83 of file lduPrimitiveProcessorInterface.C.
References processorLduInterface::send().
virtual label comm () const inline virtual
Return communicator used for sending.
Implements processorLduInterface.
Definition at line 179 of file lduPrimitiveProcessorInterface.H.
Referenced by calculatedProcessorFvPatchField< Type >::clone().
virtual int myProcNo () const inline virtual
Return processor number (rank in communicator)
Implements processorLduInterface.
Definition at line 187 of file lduPrimitiveProcessorInterface.H.
virtual int neighbProcNo () const inline virtual
Return neighbour processor number (rank in communicator)
Implements processorLduInterface.
Definition at line 195 of file lduPrimitiveProcessorInterface.H.
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements processorLduInterface.
Definition at line 203 of file lduPrimitiveProcessorInterface.H.
Referenced by calculatedProcessorFvPatchField< Type >::comm().
virtual int tag () const inline virtual
Return message tag used for sending.
Implements processorLduInterface.
Definition at line 211 of file lduPrimitiveProcessorInterface.H.
int& tag () inline
Return message tag used for sending.
Definition at line 222 of file lduPrimitiveProcessorInterface.H.
The documentation for this class was generated from the following files:
src/overset/lduPrimitiveProcessorInterface/lduPrimitiveProcessorInterface.H
src/overset/lduPrimitiveProcessorInterface/lduPrimitiveProcessorInterface.C