OpenFOAM: Istream Class Reference
Istream Class Reference abstract
An Istream is an abstract base class for all input systems (streams, files, token lists etc). The basic operations are construct, close, read token, read primitive and read binary block.
Public Member Functions
Istream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct and set stream status.
virtual ~Istream ()=default
Destructor.
void putBack (const token &tok)
Put back token.
bool getBack (token &tok)
Get the put back token if there is one and return true.
bool peekBack (token &tok)
Peek at the put back token without removing it.
virtual Istream & read (token &)=0
Return next token from stream.
virtual Istream & read (char &)=0
Read a character.
virtual Istream & read (word &)=0
Read a word.
virtual Istream & read (string &)=0
Read a string (including enclosing double-quotes)
virtual Istream & read (label &)=0
Read a label.
virtual Istream & read (floatScalar &)=0
Read a floatScalar.
virtual Istream & read (doubleScalar &)=0
Read a doubleScalar.
virtual Istream & read (char *, std::streamsize)=0
Read binary block.
virtual bool beginRawRead ()=0
Start of low-level raw binary read.
virtual bool endRawRead ()=0
End of low-level raw binary read.
virtual Istream & readRaw (char *, std::streamsize)=0
Low-level raw binary read.
virtual void rewind ()=0
Rewind the stream so that it may be read again.
bool readBegin (const char *funcName)
Begin read of data chunk, starts with '('.
bool readEnd (const char *funcName)
End read of data chunk, ends with ')'.
char readBeginList (const char *funcName)
Begin read of list data, starts with '(' or '{'.
char readEndList (const char *funcName)
End read of list data, ends with ')' or '}'.
Istream & operator() () const
Return a non-const reference to const Istream.
Public Member Functions inherited from IOstream
IOstream (const IOstreamOption option)
Construct with specified stream option.
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct with format, version.
virtual ~IOstream ()=default
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
unsigned labelByteSize () const
The label byte-size associated with the stream.
unsigned scalarByteSize () const
The scalar byte-size associated with the stream.
void setLabelByteSize (unsigned nbytes)
Set the label byte-size associated with the stream.
void setScalarByteSize (unsigned nbytes)
Set the scalar byte-size associated with the stream.
template<class T = label>
std::enable_if
< std::is_integral< T >::value,
bool >::type checkLabelSize () const
Check if the label byte-size associated with the stream is the same as the given type.
template<class T = scalar>
std::enable_if
< std::is_floating_point< T >
::value, bool >::type checkScalarSize () const
Check if the scalar byte-size associated with the stream is the same as the given type.
label lineNumber () const
Const access to the current stream line number.
label & lineNumber ()
Non-const access to the current stream line number.
label lineNumber (const label num)
Set the stream line number.
virtual ios_base::fmtflags flags () const =0
Return flags of stream.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)=0
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
virtual void print (Ostream &os) const
Print description of IOstream to Ostream.
void print (Ostream &os, const int streamState) const
Print information about the stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from IOstreamOption
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
Enumeration for stream open/closed state.
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision.
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Static Public Attributes inherited from IOstream
static unsigned int precision_
Default precision.
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from IOstream
streamAccess openClosed_
ios_base::iostate ioState_
unsigned short labelByteSize_
The label byte-size (could also be stored as byte)
unsigned short scalarByteSize_
The scalar byte-size (could also be stored as byte)
label lineNumber_
The file line.
Static Protected Attributes inherited from IOstream
static fileName staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
An Istream is an abstract base class for all input systems (streams, files, token lists etc). The basic operations are construct, close, read token, read primitive and read binary block.
In addition, version control and line number counting is incorporated. Usually one would use the read primitive member functions, but if one were reading a stream on unknown data sequence one can read token by token, and then analyse.
Source files
Istream.H
Istream.C
Definition at line 57 of file Istream.H.
Constructor & Destructor Documentation
Istream (streamFormat format = ASCII, versionNumber version = currentVersion, compressionType compression = UNCOMPRESSED) inline
Construct and set stream status.
Definition at line 82 of file Istream.H.
virtual ~Istream () virtual default
Destructor.
Member Function Documentation
void putBack (const token & tok)
Put back token.
Only a single put back is permitted
Definition at line 46 of file Istream.C.
Referenced by Function1< Type >::New(), PatchFunction1< Type >::New(), Foam::blockMeshTools::read(), PtrList< T >::readIstream(), mappedPatchBase::readListOrField(), and functionEntry::readStringList().
bool getBack (token & tok)
Get the put back token if there is one and return true.
Return false if no put back token is available.
Definition at line 68 of file Istream.C.
bool peekBack (token & tok)
Peek at the put back token without removing it.
Returns false if no put back token is available and set the token to undefined.
Definition at line 87 of file Istream.C.
virtual Istream& read (token &) pure virtual
Return next token from stream.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
Referenced by Foam::operator<<(), Foam::operator>>(), and Foam::readHexDigit().
virtual Istream& read (char &) pure virtual
Read a character.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
virtual Istream& read (word &) pure virtual
Read a word.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
virtual Istream& read (string &) pure virtual
Read a string (including enclosing double-quotes)
Implemented in ITstream, ISstream, UIPstream, dummyISstream, dummyIstream, and ensightReadFile.
virtual Istream& read (label &) pure virtual
Read a label.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, dummyIstream, and ensightReadFile.
virtual Istream& read (floatScalar &) pure virtual
Read a floatScalar.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
virtual Istream& read (doubleScalar &) pure virtual
Read a doubleScalar.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
virtual Istream& read (char * , std::streamsize) pure virtual
Read binary block.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, dummyIstream, and ensightReadFile.
virtual bool beginRawRead () pure virtual
Start of low-level raw binary read.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
virtual bool endRawRead () pure virtual
End of low-level raw binary read.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
virtual Istream& readRaw (char * , std::streamsize) pure virtual
Low-level raw binary read.
Implemented in ITstream, ISstream, UIPstream, dummyISstream, and dummyIstream.
virtual void rewind () pure virtual
Rewind the stream so that it may be read again.
Implemented in ITstream, UIListStream, ISstream, UIPstream, IListStream, dummyISstream, dummyIstream, and IFstream.
bool readBegin (const char * funcName)
Begin read of data chunk, starts with '('.
Returns
true or FatalIOError
Definition at line 102 of file Istream.C.
Referenced by maxFirstOp< T1 >::operator()(), maxFirstEqOp< T1 >::operator()(), magnet::orientation(), and VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace().
bool readEnd (const char * funcName)
End read of data chunk, ends with ')'.
Returns
true or FatalIOError
Definition at line 120 of file Istream.C.
Referenced by maxFirstOp< T1 >::operator()(), maxFirstEqOp< T1 >::operator()(), magnet::orientation(), and VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace().
char readBeginList (const char * funcName)
Begin read of list data, starts with '(' or '{'.
Returns
starting delimiter or FatalIOError
Definition at line 139 of file Istream.C.
Referenced by Foam::blockMeshTools::read(), and PtrList< T >::readIstream().
char readEndList (const char * funcName)
End read of list data, ends with ')' or '}'.
Returns
closing delimiter or FatalIOError
Definition at line 160 of file Istream.C.
Referenced by Foam::blockMeshTools::read(), and PtrList< T >::readIstream().
Foam::Istream & operator() () const
Return a non-const reference to const Istream.
Needed for read-constructors where the stream argument is temporary: e.g. thing thisThing(IFstream("thingFileName")());
Definition at line 182 of file Istream.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/Istream.H
src/OpenFOAM/db/IOstreams/IOstreams/Istream.C