OpenFOAM: surfaceMeshWriter Class Reference
surfaceMeshWriter Class Reference
Write faces (eg face-zones or face-sets) with fields.
Public Member Functions
surfaceMeshWriter (const indirectPrimitivePatch &pp, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
Construct from patch (default format INLINE_BASE64)
surfaceMeshWriter (const indirectPrimitivePatch &pp, const fileName &file, bool parallel=Pstream::parRun())
Construct from patch (default format INLINE_BASE64), and open the file for writing.
surfaceMeshWriter (const indirectPrimitivePatch &pp, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Construct from patch and open the file for writing.
virtual ~surfaceMeshWriter ()=default
Destructor.
template<class Type >
void write (const GeometricField< Type, fvsPatchField, surfaceMesh > &field)
Write surface field (CellData)
template<class Type >
void write (const GeometricField< Type, faPatchField, areaMesh > &field)
Write surface field (CellData)
template<class Type >
Foam::tmp< Foam::Field< Type > > getFaceField (const GeometricField< Type, fvsPatchField, surfaceMesh > &sfld) const
Public Member Functions inherited from indirectPatchWriter
indirectPatchWriter (const indirectPrimitivePatch &pp, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
Construct from patch (default output INLINE_BASE64)
indirectPatchWriter (const indirectPrimitivePatch &pp, const fileName &file, bool parallel=Pstream::parRun())
Construct from components (default output INLINE_BASE64),.
indirectPatchWriter (const indirectPrimitivePatch &pp, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Construct from components and open the file for writing.
virtual ~indirectPatchWriter ()=default
Destructor.
const indirectPrimitivePatch & patch () const
Reference to the indirect patch.
virtual bool beginFile (std::string title="")
Write file header (non-collective)
virtual bool writeGeometry ()
Write patch topology.
virtual bool beginCellData (label nFields=0)
Begin CellData output section for specified number of fields.
virtual bool beginPointData (label nFields=0)
Begin PointData for specified number of fields.
template<class Type >
void writeUniform (const word &fieldName, const Type &val)
Write a uniform field of Cell (Face) or Point values.
template<class Type >
void write (const word &fieldName, const UList< Type > &field)
Write a list of Cell (Face) or Point values.
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
Construct from components.
virtual ~fileWriter ()
Destructor.
vtk::fileTag contentType () const
The content type.
vtk::outputOptions opts () const
The output options in use.
word ext () const
File extension for current format type.
bool legacy () const
Commonly used query.
bool parallel () const
Parallel output requested?
const word & state () const
The output state in printable format.
const fileName & output () const
The current output file name.
bool open (const fileName &file, bool parallel=Pstream::parRun())
Open file for writing (creates parent directory).
void close ()
End the file contents and close the file after writing.
bool beginFieldData (label nFields=0)
Begin FieldData output section for specified number of fields.
label nCellData () const
Return the number of CellData written for the Piece thus far.
label nPointData () const
Return the number of PointData written for the Piece thus far.
bool endFieldData ()
Explicitly end FieldData output and switch to DECLARED state.
bool endCellData ()
Explicitly end CellData output and switch to PIECE state.
bool endPointData ()
Explicitly end PointData output and switch to PIECE state.
void writeTimeValue (scalar timeValue)
Write "TimeValue" FieldData (name as per Catalyst output)
Additional Inherited Members
Static Public Member Functions inherited from indirectPatchWriter
static word ext (vtk::outputOptions opts)
File extension for given output type.
Protected Types inherited from fileWriter
enum outputState {
CLOSED = 0, OPENED, DECLARED, FIELD_DATA,
PIECE, CELL_DATA, POINT_DATA
}
Internal tracking of the output state.
Protected Member Functions inherited from fileWriter
std::ofstream & os ()
The backend ostream in use.
vtk::formatter & format ()
The VTK formatter in use.
bool isState (outputState test) const
True if the output state corresponds to the test state.
bool notState (outputState test) const
True if the output state does not correspond to the test state.
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
Write uniform field content.
bool enter_Piece ()
Trigger change state to Piece. Resets nCellData_, nPointData_.
bool endPiece ()
Explicitly end Piece output and switch to DECLARED state.
bool enter_CellData (label nEntries, label nFields)
Trigger change state to CellData.
bool enter_PointData (label nEntries, label nFields)
Trigger change state to PointData.
bool exit_File ()
Emit file footer (end data, end piece, end file)
fileWriter (const fileWriter &)=delete
No copy construct.
void operator= (const fileWriter &)=delete
No copy assignment.
Protected Attributes inherited from fileWriter
vtk::fileTag contentType_
The content type.
outputOptions opts_
The requested output options.
bool parallel_
Writing in parallel (via master)
outputState state_
The output state.
label nCellData_
The number of CellData written for the Piece thus far.
label nPointData_
The number of PointData written for the Piece thus far.
fileName outputFile_
The output file name.
autoPtr< vtk::formatter > format_
The VTK formatter in use (master process)
std::ofstream os_
The backend ostream in use (master process)
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Names for the output state (for messages, not for file output).
Detailed Description
Write faces (eg face-zones or face-sets) with fields.
The file output states are managed by the Foam::vtk::fileWriter class. FieldData (eg, TimeValue) must appear before any geometry pieces.
Note
Parallel output is combined into a single Piece without point merging, which is similar to using multi-piece data sets, but allows more convenient creation as a streaming process. In the future, the duplicate points at processor connections may be addressed using ghost points.
Source files
foamVtkSurfaceMeshWriter.H
foamVtkSurfaceMeshWriterTemplates.C
Definition at line 62 of file foamVtkSurfaceMeshWriter.H.
Constructor & Destructor Documentation
surfaceMeshWriter (const indirectPrimitivePatch & pp, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64) inline
Construct from patch (default format INLINE_BASE64)
Definition at line 97 of file foamVtkSurfaceMeshWriter.H.
surfaceMeshWriter (const indirectPrimitivePatch & pp, const fileName & file, bool parallel = Pstream::parRun()) inline
Construct from patch (default format INLINE_BASE64), and open the file for writing.
The file name is with/without an extension.
Definition at line 112 of file foamVtkSurfaceMeshWriter.H.
surfaceMeshWriter (const indirectPrimitivePatch & pp, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun()) inline
Construct from patch and open the file for writing.
The file name is with/without an extension.
Definition at line 127 of file foamVtkSurfaceMeshWriter.H.
virtual ~surfaceMeshWriter () virtual default
Destructor.
Member Function Documentation
void write (const GeometricField< Type, fvsPatchField, surfaceMesh > & field)
Write surface field (CellData)
Definition at line 63 of file foamVtkSurfaceMeshWriterTemplates.C.
Referenced by Foam::writeAreaField().
void write (const GeometricField< Type, faPatchField, areaMesh > & field)
Write surface field (CellData)
Definition at line 82 of file foamVtkSurfaceMeshWriterTemplates.C.
Foam::tmp<Foam::Field<Type> > getFaceField (const GeometricField< Type, fvsPatchField, surfaceMesh > & sfld) const
Definition at line 27 of file foamVtkSurfaceMeshWriterTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), iter, DimensionedField< Type, GeoMesh >::mesh(), Foam::New(), indirectPatchWriter::patch(), patches, UList< T >::size(), polyBoundaryMesh::start(), and polyBoundaryMesh::whichPatch().
The documentation for this class was generated from the following files:
src/conversion/vtk/output/foamVtkSurfaceMeshWriter.H
src/conversion/vtk/output/foamVtkSurfaceMeshWriterTemplates.C