OpenFOAM: SphericalTensor< Cmpt > Class Template Reference
SphericalTensor< Cmpt > Class Template Reference
Templated 3D SphericalTensor derived from VectorSpace adding construction from 1 component, element access using th ii() member function and the inner-product (dot-product) and outer-product operators.
Public Types
enum components { II }
Component labeling enumeration.
typedef SphericalTensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
typedef VectorSpace
< SphericalTensor< Cmpt >
, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
typedef Cmpt magType
Magnitude type.
typedef Cmpt * iterator
Random access iterator for traversing VectorSpace.
typedef const Cmpt * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
SphericalTensor ()
Construct null.
SphericalTensor (const Foam::zero)
Construct initialized to zero.
template<class Cmpt2 >
SphericalTensor (const VectorSpace< SphericalTensor< Cmpt2 >, Cmpt2, 1 > &)
Construct given VectorSpace.
SphericalTensor (const Cmpt &tii)
Construct given the component.
SphericalTensor (Istream &)
Construct from Istream.
const Cmpt & ii () const
Cmpt & ii ()
const SphericalTensor< Cmpt > & T () const
Transpose.
Public Member Functions inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Return const pointer to the first data element.
Cmpt * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SphericalTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Static Public Attributes
static constexpr direction rank = 2
Rank of SphericalTensor is 2.
static const SphericalTensor I
static const SphericalTensor oneThirdI
static const SphericalTensor twoThirdsI
Static Public Attributes inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const SphericalTensor
< Cmpt > zero
static const SphericalTensor
< Cmpt > one
static const SphericalTensor
< Cmpt > max
static const SphericalTensor
< Cmpt > min
static const SphericalTensor
< Cmpt > rootMax
static const SphericalTensor
< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static SphericalTensor< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< SphericalTensor< Cmpt >, Cmpt, 1 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SphericalTensor< Cmpt >
Templated 3D SphericalTensor derived from VectorSpace adding construction from 1 component, element access using th ii() member function and the inner-product (dot-product) and outer-product operators.
Source files
SphericalTensor.H
SphericalTensorI.H
Definition at line 51 of file SphericalTensor.H.
Member Typedef Documentation
typedef SphericalTensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 61 of file SphericalTensor.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
II
Definition at line 82 of file SphericalTensor.H.
Constructor & Destructor Documentation
SphericalTensor () inline
Construct null.
Definition at line 26 of file SphericalTensorI.H.
SphericalTensor (const Foam::zero) inline
Construct initialized to zero.
Definition at line 31 of file SphericalTensorI.H.
SphericalTensor (const VectorSpace< SphericalTensor< Cmpt2 >, Cmpt2, 1 > & vs) inline
Construct given VectorSpace.
Definition at line 40 of file SphericalTensorI.H.
SphericalTensor (const Cmpt & tii) inline
Construct given the component.
Definition at line 49 of file SphericalTensorI.H.
SphericalTensor (Istream & is) inline
Construct from Istream.
Definition at line 56 of file SphericalTensorI.H.
Member Function Documentation
const Cmpt & ii () const inline
Definition at line 65 of file SphericalTensorI.H.
Referenced by Foam::invariantI(), Foam::invariantII(), Foam::invariantIII(), Foam::operator&(), Foam::operator+(), Foam::operator-(), and Foam::sph().
Cmpt & ii () inline
Definition at line 72 of file SphericalTensorI.H.
const Foam::SphericalTensor< Cmpt > & T () const inline
Transpose.
Definition at line 80 of file SphericalTensorI.H.
Member Data Documentation
constexpr direction rank = 2 static
Rank of SphericalTensor is 2.
Definition at line 69 of file SphericalTensor.H.
const Foam::labelSphericalTensor I static
Definition at line 74 of file SphericalTensor.H.
const SphericalTensor oneThirdI static
Definition at line 75 of file SphericalTensor.H.
const SphericalTensor twoThirdsI static
Definition at line 76 of file SphericalTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SphericalTensor/SphericalTensor.H
src/OpenFOAM/primitives/SphericalTensor/labelSphericalTensor/labelSphericalTensor.C
src/OpenFOAM/primitives/SphericalTensor/SphericalTensorI.H