OpenFOAM: sampledIsoSurface Class Reference
sampledIsoSurface Class Reference
A sampledSurface defined by a surface of iso value. Always triangulated. To be used in sampleSurfaces / functionObjects. Recalculates iso surface only if time changes.
Public Member Functions
TypeName ("sampledIsoSurface")
Runtime type information.
sampledIsoSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
virtual ~sampledIsoSurface ()
Destructor.
const isoSurface & surface () const
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
virtual const labelList & zoneIds () const
Per-face zone/region information.
virtual const vectorField & Sf () const
Face area magnitudes.
virtual const scalarField & magSf () const
Face area magnitudes.
virtual const vectorField & Cf () const
Face centres.
void getIsoField ()
Lookup or read isoField.
virtual tmp< scalarField > sample (const interpolation< scalar > &sampler) const
Sample volume field onto surface faces.
virtual tmp< vectorField > sample (const interpolation< vector > &sampler) const
Sample volume field onto surface faces.
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > &sampler) const
Sample volume field onto surface faces.
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > &sampler) const
Sample volume field onto surface faces.
virtual tmp< tensorField > sample (const interpolation< tensor > &sampler) const
Sample volume field onto surface faces.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< vectorField > interpolate (const interpolation< vector > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &interpolator) const
Interpolate volume field onto surface points.
virtual void print (Ostream &) const
Write.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &mesh, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor - calls clearGeom()
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool enabled () const
Surface is enabled.
bool invariant () const
Surface is invariant with geometry change (caution)
bool interpolate () const
Interpolation to nodes requested for surface.
scalar area () const
The total surface area.
virtual bool hasFaceIds () const
If element ids/order of the original surface are available.
virtual const labelList & originalIds () const
List of element ids/order of the original surface, when hasFaceIds is true.
polySurface * getRegistrySurface (const objectRegistry &obr, word lookupName="") const
Get surface from registry if available.
polySurface * storeRegistrySurface (objectRegistry &obr, word lookupName="") const
Copy surface into registry.
bool removeRegistrySurface (objectRegistry &obr, word lookupName="") const
Remove surface from registry.
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
Copy/store sampled field onto registered surface (if it exists)
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
Move/store sampled field onto registered surface (if it exists)
surfMesh * getSurfMesh (word lookupName="") const
Get surface from registry if available.
surfMesh * storeSurfMesh (word lookupName="") const
Copy surface into registry.
bool removeSurfMesh (word lookupName="") const
Remove surface from registry.
template<class Type , class GeoMeshType >
bool storeSurfMeshField (const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
Copy/store sampled Face field onto surfMesh (if it exists)
template<class Type , class GeoMeshType >
bool storeSurfMeshField (const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
Move/store sampled Face field onto surfMesh (if it exists)
virtual bool withSurfaceFields () const
Can it sample surface-fields?
virtual tmp< scalarField > sample (const surfaceScalarField &sField) const
Sample surface field onto surface.
virtual tmp< vectorField > sample (const surfaceVectorField &sField) const
Sample surface field onto surface.
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &sField) const
Sample surface field onto surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &sField) const
Sample surface field onto surface.
virtual tmp< tensorField > sample (const surfaceTensorField &sField) const
Sample surface field onto surface.
virtual void rename (const word &newName)
Rename.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld)
Public Member Functions inherited from meshedSurf
meshedSurf ()=default
Construct null.
virtual ~meshedSurf ()=default
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected surface.
Static Public Attributes inherited from sampledSurface
static const wordList surfaceFieldTypes
Class names for surface field types.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Additional cleanup when clearing the geometry.
sampledSurface (const word &name, std::nullptr_t)
Construct null.
Static Protected Member Functions inherited from sampledSurface
template<class Type >
static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts)
General loop for sampling elements to faces.
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld)
Create cell values by averaging the point values.
Detailed Description
A sampledSurface defined by a surface of iso value. Always triangulated. To be used in sampleSurfaces / functionObjects. Recalculates iso surface only if time changes.
This is often embedded as part of a sampled surfaces function object.
Usage
Example of function object partial specification:
surfaces
(
    surface1
    {
        type    sampledIsoSurface;
        cell    false;
    }
);
Where the sub-entries comprise:
Property Description Required Default
type sampledIsoSurface yes
isoField field name for obtaining iso-surface yes
isoValue value of iso-surface yes
mergeTol tolerance for merging points no 1e-6
regularise point snapping (bool or enum) no true
average cell values from averaged point values no false
bounds limit with bounding box no
zone limit to cell zone (name or regex) no
zones limit to cell zones (names, regexs) no
exposedPatchName name for zone subset partly
Source files
sampledIsoSurface.H
sampledIsoSurface.C
Definition at line 136 of file sampledIsoSurface.H.
Constructor & Destructor Documentation
sampledIsoSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 410 of file sampledIsoSurface.C.
~sampledIsoSurface () virtual
Destructor.
Definition at line 475 of file sampledIsoSurface.C.
Member Function Documentation
TypeName ("sampledIsoSurface")
Runtime type information.
const isoSurface& surface () const inline
Definition at line 284 of file sampledIsoSurface.H.
Referenced by sampledIsoSurface::sampleOnFaces().
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 481 of file sampledIsoSurface.C.
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 489 of file sampledIsoSurface.C.
References mesh, fvMesh::time(), and TimeState::timeIndex().
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 509 of file sampledIsoSurface.C.
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 313 of file sampledIsoSurface.H.
Referenced by sampledIsoSurface::sampleOnFaces().
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 321 of file sampledIsoSurface.H.
virtual const labelList& zoneIds () const inline virtual
Per-face zone/region information.
Reimplemented from meshedSurf.
Definition at line 329 of file sampledIsoSurface.H.
virtual const vectorField& Sf () const inline virtual
Face area magnitudes.
Implements sampledSurface.
Definition at line 337 of file sampledIsoSurface.H.
virtual const scalarField& magSf () const inline virtual
Face area magnitudes.
Implements sampledSurface.
Definition at line 345 of file sampledIsoSurface.H.
virtual const vectorField& Cf () const inline virtual
Face centres.
Implements sampledSurface.
Definition at line 353 of file sampledIsoSurface.H.
void getIsoField ()
Lookup or read isoField.
Sets volFieldPtr_ and pointFieldPtr_.
Foam::tmp< Foam::scalarField > sample (const interpolation< scalar > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 516 of file sampledIsoSurface.C.
Foam::tmp< Foam::vectorField > sample (const interpolation< vector > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 525 of file sampledIsoSurface.C.
Foam::tmp< Foam::sphericalTensorField > sample (const interpolation< sphericalTensor > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 534 of file sampledIsoSurface.C.
Foam::tmp< Foam::symmTensorField > sample (const interpolation< symmTensor > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 543 of file sampledIsoSurface.C.
Foam::tmp< Foam::tensorField > sample (const interpolation< tensor > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 552 of file sampledIsoSurface.C.
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 561 of file sampledIsoSurface.C.
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 570 of file sampledIsoSurface.C.
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 578 of file sampledIsoSurface.C.
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 587 of file sampledIsoSurface.C.
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 596 of file sampledIsoSurface.C.
void print (Ostream & os) const virtual
Write.
Reimplemented from sampledSurface.
Definition at line 604 of file sampledIsoSurface.C.
Foam::tmp<Foam::Field<Type> > sampleOnFaces (const interpolation< Type > & sampler) const
Definition at line 32 of file sampledIsoSurfaceTemplates.C.
References sampledIsoSurface::points(), sampledSurface::sampleOnFaces(), and sampledIsoSurface::surface().
Foam::tmp<Foam::Field<Type> > sampleOnPoints (const interpolation< Type > & interpolator) const
Definition at line 51 of file sampledIsoSurfaceTemplates.C.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/isoSurface/sampledIsoSurface.H
src/sampling/sampledSurface/isoSurface/sampledIsoSurface.C
src/sampling/sampledSurface/isoSurface/sampledIsoSurfaceTemplates.C