OpenFOAM: hConstThermo< EquationOfState > Class Template Reference
hConstThermo< EquationOfState > Class Template Reference
Thermodynamics
Constant properties thermodynamics package templated into the EquationOfState.
Public Member Functions
hConstThermo (const dictionary &dict)
Construct from dictionary.
hConstThermo (const word &, const hConstThermo &)
Construct as named copy.
autoPtr< hConstThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar Cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar Ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kg].
scalar Hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar dGdT (const scalar p, const scalar T) const
Derivative of Gibbs free energy w.r.t. temperature.
scalar dCpdT (const scalar p, const scalar T) const
Temperature derivative of heat capacity at constant pressure.
void write (Ostream &os) const
Write to Ostream.
void operator+= (const hConstThermo &)
Static Public Member Functions
static autoPtr< hConstThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hConstThermo operator+ (const hConstThermo &, const hConstThermo &)
hConstThermo operator* (const scalar, const hConstThermo &)
hConstThermo operator== (const hConstThermo &, const hConstThermo &)
Ostream & operator (Ostream &, const hConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hConstThermo< EquationOfState >
Constant properties thermodynamics package templated into the EquationOfState.
Source files
hConstThermo.H
hConstThermoI.H
hConstThermo.C
Definition at line 47 of file hConstThermo.H.
Constructor & Destructor Documentation
hConstThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 27 of file hConstThermo.C.
hConstThermo (const word & name, const hConstThermo< EquationOfState > & ct) inline
Construct as named copy.
Definition at line 41 of file hConstThermoI.H.
Member Function Documentation
Foam::autoPtr< Foam::hConstThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 54 of file hConstThermoI.H.
Foam::autoPtr< Foam::hConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 62 of file hConstThermoI.H.
References Foam::New().
static word typeName () inline static
Return the instantiated type name.
Definition at line 136 of file hConstThermo.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 72 of file hConstThermoI.H.
Foam::scalar Cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 82 of file hConstThermoI.H.
References T.
Foam::scalar Ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kg].
Definition at line 93 of file hConstThermoI.H.
References Cp.
Foam::scalar Hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 103 of file hConstThermoI.H.
References Hs().
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 112 of file hConstThermoI.H.
References H(), and T.
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 120 of file hConstThermoI.H.
References Hf_().
Foam::scalar dGdT (const scalar p, const scalar T) const inline
Derivative of Gibbs free energy w.r.t. temperature.
Definition at line 130 of file hConstThermoI.H.
References Foam::log(), and Foam::constant::standard::Tstd.
Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Temperature derivative of heat capacity at constant pressure.
Definition at line 140 of file hConstThermoI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 38 of file hConstThermo.C.
void operator+= (const hConstThermo< EquationOfState > &) inline
Definition at line 151 of file hConstThermoI.H.
Friends And Related Function Documentation
hConstThermo operator+ (const hConstThermo< EquationOfState > & , const hConstThermo< EquationOfState > &) friend
hConstThermo operator* (const scalar , const hConstThermo< EquationOfState > &) friend
hConstThermo operator== (const hConstThermo< EquationOfState > & , const hConstThermo< EquationOfState > &) friend
Ostream& operator (Ostream & , const hConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hConst/hConstThermo.H
src/thermophysicalModels/specie/thermo/hConst/hConstThermo.C
src/thermophysicalModels/specie/thermo/hConst/hConstThermoI.H