OpenFOAM: injectedParticle Class Reference
injectedParticle Class Reference
Primarly stores particle properties so that it can be injected at a later time. Note that this stores its own local position as opposed to the base particle class barycentric coordinates since the particle is not (usually) attached to a mesh, and instead used for post-processing.
Classes
class iNew
Factory class to read-construct particles used for.
Public Member Functions
TypeName ("injectedParticle")
Runtime type information.
AddToPropertyList (particle," tag"+" soi"+" d"+" (Ux Uy Uz)";)
String representation of properties.
injectedParticle (const polyMesh &mesh, const vector &position, const label celli=-1)
Construct from a position and a cell.
injectedParticle (const polyMesh &mesh, const vector &position, const label tag, const scalar soi, const scalar d, const vector &U, const bool doLocate=true)
Construct from components.
injectedParticle (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
injectedParticle (const injectedParticle &p)
Construct as a copy.
injectedParticle (const injectedParticle &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
label tag () const
Return const access to the tag.
scalar soi () const
Return const access to the start of injection.
scalar d () const
Return const access to diameter.
const vector & U () const
Return const access to velocity.
label & tag ()
Return the tag.
scalar & soi ()
Return the start of injection.
scalar & d ()
Return access to diameter.
vector & U ()
Return access to velocity.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
Write individual parcel properties to stream.
virtual void writePosition (Ostream &) const
Write the particle position and cell.
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label celli=-1)
Construct from a position and a cell.
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const bool doLocate=true)
Construct from position components.
particle (const polyMesh &mesh, Istream &, bool readFields=true, bool newFormat=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with reference to a new mesh.
virtual ~particle ()=default
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const barycentric & coordinates () const
Return current particle coordinates.
label cell () const
Return current cell particle is in.
label & cell ()
Return current cell particle is in for manipulation.
label tetFace () const
Return current tet face particle is in.
label & tetFace ()
Return current tet face particle is in for manipulation.
label tetPt () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in for manipulation.
label face () const
Return current face particle is on otherwise -1.
label & face ()
Return current face particle is on for manipulation.
scalar stepFraction () const
Return the fraction of time-step completed.
scalar & stepFraction ()
Return the fraction of time-step completed.
label origProc () const
Return the originating processor ID.
label & origProc ()
Return the originating processor ID.
label origId () const
Return the particle ID on the originating processor.
label & origId ()
Return the particle ID on the originating processor.
Pair< scalar > stepFractionSpan () const
Return the step fraction change within the overall time-step.
scalar currentTimeFraction () const
Return the current fraction within the timestep. This differs.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
barycentricTensor currentTetTransform () const
Return the current tet transformation tensor.
vector normal () const
The (unit) normal of the tri on tetFacei_ for the current tet.
bool onFace () const
Is the particle on a face?
bool onInternalFace () const
Is the particle on an internal face?
bool onBoundaryFace () const
Is the particle on a boundary face?
label patch () const
Return the index of patch that the particle is on.
vector position () const
Return current particle position.
scalar track (const vector &displacement, const scalar fraction)
Track along the displacement for a given fraction of the overall.
scalar trackToFace (const vector &displacement, const scalar fraction)
As particle::track, but also stops on internal faces.
scalar trackToTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToFace, but also stops on tet triangles. On.
scalar trackToStationaryTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for stationary meshes.
scalar trackToMovingTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for moving meshes.
template<class TrackCloudType >
void hitFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
Hit the current face. If the current face is internal than this.
template<class TrackCloudType >
void trackToAndHitFace (const vector &direction, const scalar fraction, TrackCloudType &cloud, trackingData &td)
Convenience function. Combines trackToFace and hitFace.
vector deviationFromMeshCentre () const
Get the displacement from the mesh centre. Used to correct the.
void patchData (vector &n, vector &U) const
Get the normal and velocity of the current patch location.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
void prepareForParallelTransfer ()
Convert global addressing to the processor patch local equivalents.
void correctAfterParallelTransfer (const label patchi, trackingData &td)
Convert processor patch addressing to the global equivalents.
void prepareForInteractionListReferral (const vectorTensorTransform &transform)
Break the topology and store the particle position so that the.
void correctAfterInteractionListReferral (const label celli)
Correct the topology after referral. The particle may still be.
label procTetPt (const polyMesh &procMesh, const label procCell, const label procTetFace) const
Return the tet point appropriate for decomposition or reconstruction.
void autoMap (const vector &position, const mapPolyMesh &mapper)
Map after a topology change.
void relocate (const point &position, const label celli=-1)
Set the addressing based on the provided position.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
Write individual particle properties to stream.
void writeCoordinates (Ostream &os) const
Write the particle barycentric coordinates and cell info.
Static Public Member Functions
static void readFields (Cloud< injectedParticle > &c)
Read fields.
static void writeFields (const Cloud< injectedParticle > &c)
Write fields.
static void readObjects (Cloud< injectedParticle > &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
static void writeObjects (const Cloud< injectedParticle > &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class Type >
static void writePropertyName (Ostream &os, const word &name, const word &delim)
Write the name representation to stream.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Type &value, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property to stream, optionally filtered based on its name.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Field< Type > &values, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property list to stream, optionally filtered based on its name.
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
Read the fields associated with the owner cloud.
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
Write the fields associated with the owner cloud.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields
Size in bytes of the fields.
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provide unique ID.
static bool writeLagrangianCoordinates = true
Write particle coordinates file (v1712 and later) Default is true.
static bool writeLagrangianPositions
Write particle positions file (v1706 format and earlier) Default is true (disable in etc/controlDict)
Protected Attributes
point position_
Position.
label tag_
Tag.
scalar soi_
Start of injection [s].
scalar d_
Diameter [m].
vector U_
Velocity [m/s].
Friends
Ostream & operator<< (Ostream &, const injectedParticle &)
Additional Inherited Members
Protected Member Functions inherited from particle< Type >
template<class TrackCloudType >
bool hitPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a patch.
template<class TrackCloudType >
void hitWedgePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackCloudType >
void hitSymmetryPlanePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitSymmetryPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a symmetryPatch.
template<class TrackCloudType >
void hitCyclicPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackCloudType >
void hitCyclicAMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackCloudType >
void hitCyclicACMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a processorPatch.
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wallPatch.
Detailed Description
Primarly stores particle properties so that it can be injected at a later time. Note that this stores its own local position as opposed to the base particle class barycentric coordinates since the particle is not (usually) attached to a mesh, and instead used for post-processing.
Source files
injectedParticle.H
injectedParticle.C
injectedParticleIO.C
See Also
Foam::functionObjects::extractEulerianParticles
Definition at line 59 of file injectedParticle.H.
Constructor & Destructor Documentation
injectedParticle (const polyMesh & mesh, const vector & position, const label celli = -1) inline
Construct from a position and a cell.
Searches for the rest of the required topology. Other properties are zero initialised.
Definition at line 25 of file injectedParticleI.H.
Referenced by injectedParticle::clone().
injectedParticle (const polyMesh & mesh, const vector & position, const label tag, const scalar soi, const scalar d, const vector & U, const bool doLocate = true) inline
Construct from components.
Definition at line 41 of file injectedParticleI.H.
injectedParticle (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 42 of file injectedParticleIO.C.
injectedParticle (const injectedParticle & p)
Construct as a copy.
Definition at line 33 of file injectedParticle.C.
References Foam::defineTypeNameAndDebug().
injectedParticle (const injectedParticle & p, const polyMesh & mesh)
Construct as a copy.
Definition at line 45 of file injectedParticle.C.
Member Function Documentation
TypeName ("injectedParticle")
Runtime type information.
AddToPropertyList (particle , " tag"+" soi"+" d"+" (Ux Uy Uz)";)
String representation of properties.
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Reimplemented from particle< Type >.
Definition at line 175 of file injectedParticle.H.
References injectedParticle::injectedParticle().
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 183 of file injectedParticle.H.
Foam::label tag () const inline
Return const access to the tag.
Definition at line 60 of file injectedParticleI.H.
Foam::scalar soi () const inline
Return const access to the start of injection.
Definition at line 66 of file injectedParticleI.H.
References injectedParticle::tag_.
Foam::scalar d () const inline
Return const access to diameter.
Definition at line 72 of file injectedParticleI.H.
const Foam::vector & U () const inline
Return const access to velocity.
Definition at line 78 of file injectedParticleI.H.
Foam::label & tag () inline
Return the tag.
Definition at line 84 of file injectedParticleI.H.
Foam::scalar & soi () inline
Return the start of injection.
Definition at line 90 of file injectedParticleI.H.
Foam::scalar & d () inline
Return access to diameter.
Definition at line 96 of file injectedParticleI.H.
Foam::vector & U () inline
Return access to velocity.
Definition at line 102 of file injectedParticleI.H.
void readFields (Cloud< injectedParticle > & c) static
Read fields.
Definition at line 89 of file injectedParticleIO.C.
Referenced by injectedParticleCloud::injectedParticleCloud().
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly) const
Write individual parcel properties to stream.
Definition at line 169 of file injectedParticleIO.C.
void writeFields (const Cloud< injectedParticle > & c) static
Write fields.
Definition at line 125 of file injectedParticleIO.C.
void readObjects (Cloud< injectedParticle > & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 192 of file injectedParticleIO.C.
Referenced by injectedParticleCloud::writeObjects().
void writeObjects (const Cloud< injectedParticle > & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Definition at line 221 of file injectedParticleIO.C.
void writePosition (Ostream & os) const virtual
Write the particle position and cell.
Note: This uses the local particle position, and bypasses the barycentric description
Reimplemented from particle< Type >.
Definition at line 250 of file injectedParticleIO.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const injectedParticle &) friend
Member Data Documentation
point position_ protected
Position.
Definition at line 72 of file injectedParticle.H.
label tag_ protected
Tag.
Definition at line 77 of file injectedParticle.H.
Referenced by injectedParticle::soi().
scalar soi_ protected
Start of injection [s].
Definition at line 82 of file injectedParticle.H.
scalar d_ protected
Diameter [m].
Definition at line 87 of file injectedParticle.H.
vector U_ protected
Velocity [m/s].
Definition at line 92 of file injectedParticle.H.
const std::size_t sizeofFields static
Size in bytes of the fields.
Definition at line 102 of file injectedParticle.H.
The documentation for this class was generated from the following files:
src/lagrangian/basic/injectedParticle/injectedParticle.H
src/lagrangian/basic/injectedParticle/injectedParticle.C
src/lagrangian/basic/injectedParticle/injectedParticleI.H
src/lagrangian/basic/injectedParticle/injectedParticleIO.C