OpenFOAM: wedgePolyPatch Class Reference
wedgePolyPatch Class Reference
Wedge front and back plane patch.
Public Member Functions
TypeName ("wedge")
Runtime type information.
wedgePolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
wedgePolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
wedgePolyPatch (const wedgePolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
wedgePolyPatch (const wedgePolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
wedgePolyPatch (const wedgePolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
const vector & axis () const
Return axis of the wedge.
const vector & centreNormal () const
Return plane normal between the wedge boundaries.
const vector & n () const
Return the normal to the patch.
scalar cosAngle () const
Return the cosine of the wedge angle.
const tensor & faceT () const
Return face transformation tensor.
const tensor & cellT () const
Return neighbour-cell transformation tensor.
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label offset () const
The offset where this patch starts in the boundary face list.
label start () const
Return start label of this patch in the polyMesh face list.
labelRange range () const
Return start/size range of this patch.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch is geometrically coupled (i.e. faces and.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
tmp< scalarField > areaFraction () const
Return the area fraction as the ratio of the stored face area and the area given by the face points.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &p, const label index)
Copy construct, resetting the index.
virtual ~patchIdentifier ()=default
Destructor.
const word & name () const
Return the patch name.
word & name ()
Modifiable patch name.
const word & physicalType () const
The optional physical type of the patch.
word & physicalType ()
Modifiable optional physical type of the patch.
label index () const
The index of this patch in the boundaryMesh.
label & index ()
Modifiable the index of this patch in the boundaryMesh.
const wordList & inGroups () const
The optional groups that the patch belongs to.
wordList & inGroups ()
Modifiable optional groups that the patch belongs to.
bool inGroup (const word &name) const
Check if the patch is in named group.
void write (Ostream &os) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &&faces, const Field< PointType > &points)
Construct from components, transferring faces.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< PointType > & faceNormals () const
Return face unit normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Protected Member Functions
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
Protected Member Functions inherited from polyPatch
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &p)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
virtual void clearGeom ()
Clear geometry.
Additional Inherited Members
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Detailed Description
Wedge front and back plane patch.
Source files
wedgePolyPatch.H
wedgePolyPatch.C
Definition at line 46 of file wedgePolyPatch.H.
Constructor & Destructor Documentation
wedgePolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from components.
Definition at line 128 of file wedgePolyPatch.C.
Referenced by wedgePolyPatch::clone().
wedgePolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 148 of file wedgePolyPatch.C.
wedgePolyPatch (const wedgePolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 167 of file wedgePolyPatch.C.
wedgePolyPatch (const wedgePolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 183 of file wedgePolyPatch.C.
wedgePolyPatch (const wedgePolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 202 of file wedgePolyPatch.C.
Member Function Documentation
void calcGeometry (PstreamBuffers &) protected virtual
Calculate the patch geometry.
Reimplemented from polyPatch.
Definition at line 39 of file wedgePolyPatch.C.
TypeName ("wedge")
Runtime type information.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from polyPatch.
Definition at line 162 of file wedgePolyPatch.H.
References wedgePolyPatch::wedgePolyPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Definition at line 173 of file wedgePolyPatch.H.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from polyPatch.
Definition at line 192 of file wedgePolyPatch.H.
const vector& axis () const inline
Return axis of the wedge.
Definition at line 213 of file wedgePolyPatch.H.
const vector& centreNormal () const inline
Return plane normal between the wedge boundaries.
Definition at line 221 of file wedgePolyPatch.H.
const vector& n () const inline
Return the normal to the patch.
Definition at line 229 of file wedgePolyPatch.H.
scalar cosAngle () const inline
Return the cosine of the wedge angle.
Definition at line 237 of file wedgePolyPatch.H.
const tensor& faceT () const inline
Return face transformation tensor.
Definition at line 245 of file wedgePolyPatch.H.
Referenced by wedgeFvPatch::faceT().
const tensor& cellT () const inline
Return neighbour-cell transformation tensor.
Definition at line 253 of file wedgePolyPatch.H.
Referenced by wedgeFaPatch::centreNormal().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/wedge/wedgePolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/wedge/wedgePolyPatch.C