OpenFOAM: ODESolver Class Reference
ODESolver Class Reference abstract
Ordinary Differential Equation (ODE) solvers
Abstract base-class for ODE system solvers.
Classes
class stepState
Public Member Functions
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, ODESolver, dictionary,(const ODESystem &ode, const dictionary &dict),(ode, dict))
ODESolver (const ODESystem &ode, const dictionary &dict)
Construct for given ODESystem.
ODESolver (const ODESystem &ode, const scalarField &absTol, const scalarField &relTol)
Construct for given ODESystem specifying tolerances.
virtual ~ODESolver ()=default
Destructor.
label nEqns () const
Return the number of equations to solve.
scalarField & absTol ()
Return access to the absolute tolerance field.
scalarField & relTol ()
Return access to the relative tolerance field.
virtual bool resize ()=0
Resize the ODE solver.
template<class Type >
void resizeField (UList< Type > &f) const
void resizeMatrix (scalarSquareMatrix &m) const
virtual void solve (scalar &x, scalarField &y, scalar &dxTry) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (scalar &x, scalarField &y, stepState &step) const
Solve the ODE system as far as possible upto dxTry.
virtual void solve (const scalar xStart, const scalar xEnd, scalarField &y, scalar &dxEst) const
Solve the ODE system from xStart to xEnd, update the state.
Static Public Member Functions
static autoPtr< ODESolver > New (const ODESystem &ode, const dictionary &dict)
Select null constructed.
template<class Type >
static void resizeField (UList< Type > &f, const label n)
Protected Member Functions
scalar normalizeError (const scalarField &y0, const scalarField &y, const scalarField &err) const
Return the nomalized scalar error.
ODESolver (const ODESolver &)=delete
No copy construct.
void operator= (const ODESolver &)=delete
No copy assignment.
Protected Attributes
const ODESystem & odes_
Reference to ODESystem.
const label maxN_
Maximum size of the ODESystem.
label n_
Size of the ODESystem (adjustable)
scalarField absTol_
Absolute convergence tolerance per step.
scalarField relTol_
Relative convergence tolerance per step.
label maxSteps_
The maximum number of sub-steps allowed for the integration step.
Friends
class ODESystem
Detailed Description
Abstract base-class for ODE system solvers.
Source files
ODESolver.H
ODESolver.C
Definition at line 52 of file ODESolver.H.
Constructor & Destructor Documentation
ODESolver (const ODESolver &) protected delete
No copy construct.
ODESolver (const ODESystem & ode, const dictionary & dict)
Construct for given ODESystem.
Definition at line 56 of file ODESolver.C.
ODESolver (const ODESystem & ode, const scalarField & absTol, const scalarField & relTol)
Construct for given ODESystem specifying tolerances.
Definition at line 68 of file ODESolver.C.
virtual ~ODESolver () virtual default
Destructor.
Member Function Documentation
Foam::scalar normalizeError (const scalarField & y0, const scalarField & y, const scalarField & err) const protected
Return the nomalized scalar error.
Definition at line 36 of file ODESolver.C.
void operator= (const ODESolver &) protected delete
No copy assignment.
TypeName ("ODESolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , ODESolver , dictionary , (const ODESystem &ode, const dictionary &dict) , (ode, dict))
Foam::autoPtr< Foam::ODESolver > New (const ODESystem & ode, const dictionary & dict) static
Select null constructed.
Definition at line 27 of file ODESolverNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Foam::label nEqns () const inline
Return the number of equations to solve.
Definition at line 24 of file ODESolverI.H.
Foam::scalarField & absTol () inline
Return access to the absolute tolerance field.
Definition at line 30 of file ODESolverI.H.
References ODESolver::n_.
Foam::scalarField & relTol () inline
Return access to the relative tolerance field.
Definition at line 36 of file ODESolverI.H.
bool resize () pure virtual
Resize the ODE solver.
Implemented in seulex, SIBS, RKF45, RKDP45, Rosenbrock34, RKCK45, rodas34, rodas23, Rosenbrock23, Rosenbrock12, EulerSI, Euler, and Trapezoid.
Definition at line 85 of file ODESolver.C.
void resizeField (UList< Type > & f, const label n) inline static
Definition at line 43 of file ODESolverI.H.
void resizeField (UList< Type > & f) const inline
Definition at line 50 of file ODESolverI.H.
References UList< T >::begin(), n, and UList< T >::shallowCopy().
void resizeMatrix (scalarSquareMatrix & m) const inline
Definition at line 56 of file ODESolverI.H.
void solve (scalar & x, scalarField & y, scalar & dxTry) const virtual
Solve the ODE system as far as possible upto dxTry.
adjusting the step as necessary to provide a solution within the specified tolerance. Update the state and return an estimate for the next step in dxTry
Reimplemented in RKF45, RKDP45, Rosenbrock34, RKCK45, SIBS, rodas34, rodas23, Rosenbrock23, Rosenbrock12, EulerSI, Euler, and Trapezoid.
Definition at line 110 of file ODESolver.C.
void solve (scalar & x, scalarField & y, stepState & step) const virtual
Solve the ODE system as far as possible upto dxTry.
adjusting the step as necessary to provide a solution within the specified tolerance. Update the state and return an estimate for the next step in dxTry
Reimplemented in seulex.
Definition at line 123 of file ODESolver.C.
void solve (const scalar xStart, const scalar xEnd, scalarField & y, scalar & dxEst) const virtual
Solve the ODE system from xStart to xEnd, update the state.
and return an estimate for the next step in dxTry
Definition at line 136 of file ODESolver.C.
Friends And Related Function Documentation
friend class ODESystem friend
Definition at line 115 of file ODESolver.H.
Member Data Documentation
const ODESystem& odes_ protected
Reference to ODESystem.
Definition at line 62 of file ODESolver.H.
const label maxN_ protected
Maximum size of the ODESystem.
Definition at line 67 of file ODESolver.H.
label n_ mutable protected
Size of the ODESystem (adjustable)
Definition at line 72 of file ODESolver.H.
Referenced by ODESolver::absTol().
scalarField absTol_ protected
Absolute convergence tolerance per step.
Definition at line 77 of file ODESolver.H.
scalarField relTol_ protected
Relative convergence tolerance per step.
Definition at line 82 of file ODESolver.H.
label maxSteps_ protected
The maximum number of sub-steps allowed for the integration step.
Definition at line 87 of file ODESolver.H.
The documentation for this class was generated from the following files:
src/ODE/ODESolvers/ODESolver/ODESolver.H
src/ODE/ODESolvers/ODESolver/ODESolver.C
src/ODE/ODESolvers/ODESolver/ODESolverI.H
src/ODE/ODESolvers/ODESolver/ODESolverNew.C