OpenFOAM: demandDrivenEntry< Type > Class Template Reference
demandDrivenEntry< Type > Class Template Reference
Class for demand-driven dictionary entries.
Public Member Functions
demandDrivenEntry (const dictionary &dict, const Type &value)
Constructors.
demandDrivenEntry (const dictionary &dict, const word &keyword)
Construct from dictionary and keyword.
demandDrivenEntry (const dictionary &dict, const word &keyword, const Type &defaultValue, const bool readIfPresent=true)
Construct from dictionary, keyword and default value.
demandDrivenEntry (const demandDrivenEntry &dde)
Copy constructor.
void initialise () const
Initialise.
const Type & value () const
Return the value.
void setValue (const Type &value)
Set the value.
void reset ()
Reset the demand-driven entry.
Detailed Description
template<class Type>
class Foam::demandDrivenEntry< Type >
Class for demand-driven dictionary entries.
Holds a reference to a dictionary, which is then queried if the value is requested and has not already been cached
Source files
demandDrivenEntry.H
demandDrivenEntry.C
demandDrivenEntryI.H
Definition at line 51 of file demandDrivenEntry.H.
Constructor & Destructor Documentation
demandDrivenEntry (const dictionary & dict, const Type & value)
Constructors.
Construct from dictionary and value - cannot be re-read
Definition at line 27 of file demandDrivenEntry.C.
demandDrivenEntry (const dictionary & dict, const word & keyword)
Construct from dictionary and keyword.
Definition at line 41 of file demandDrivenEntry.C.
demandDrivenEntry (const dictionary & dict, const word & keyword, const Type & defaultValue, const bool readIfPresent = true)
Construct from dictionary, keyword and default value.
Definition at line 55 of file demandDrivenEntry.C.
demandDrivenEntry (const demandDrivenEntry< Type > & dde)
Copy constructor.
Definition at line 75 of file demandDrivenEntry.C.
References dictionary::readIfPresent().
Member Function Documentation
void initialise () const inline
Initialise.
Definition at line 26 of file demandDrivenEntryI.H.
const Type & value () const inline
Return the value.
Definition at line 37 of file demandDrivenEntryI.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::constantProperties::LDevol(), SprayParcel< ParcelType >::constantProperties::mu0(), CollidingParcel< ParcelType >::constantProperties::poissonsRatio(), and ThermoParcel< ParcelType >::constantProperties::TMin().
void setValue (const Type & value) inline
Set the value.
Definition at line 46 of file demandDrivenEntryI.H.
void reset () inline
Reset the demand-driven entry.
Definition at line 55 of file demandDrivenEntryI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/demandDrivenEntry/demandDrivenEntry.H
src/OpenFOAM/primitives/demandDrivenEntry/demandDrivenEntry.C
src/OpenFOAM/primitives/demandDrivenEntry/demandDrivenEntryI.H