OpenFOAM: optionAdjointList Class Reference
optionAdjointList Class Reference
Public Member Functions
TypeName ("optionAdjointList")
Runtime type information.
optionAdjointList (const fvMesh &mesh)
Construct null.
optionAdjointList (const fvMesh &mesh, const dictionary &dict)
Construct from mesh and dictionary.
virtual ~optionAdjointList ()=default
Destructor.
void reset (const dictionary &dict)
Reset the source list.
template<class Type >
void correct (GeometricField< Type, fvPatchField, volMesh > &fld)
Correct.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Return source for equation with specified name.
template<class Type >
void constrain (fvMatrix< Type > &eqn)
Apply constraints to equation.
virtual bool read (const dictionary &dict)
Read dictionary.
virtual bool writeData (Ostream &os) const
Write data to Ostream.
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &fld, const word &fieldName)
Public Member Functions inherited from PtrList< optionAdjoint >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< optionAdjoint > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< optionAdjoint > &&list)
Move construct.
PtrList (UList< optionAdjoint * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
PtrList (const PtrList< optionAdjoint > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< optionAdjoint > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< optionAdjoint > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
PtrList< optionAdjoint > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (optionAdjoint *ptr)
Append an element to the end of the list.
void append (autoPtr< optionAdjoint > &aptr)
Move append an element to the end of the list.
void append (autoPtr< optionAdjoint > &&aptr)
Move append an element to the end of the list.
void append (const tmp< optionAdjoint > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< optionAdjoint > &list)
Transfer into this list and annul the argument list.
const optionAdjoint * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< optionAdjoint > set (const label i, optionAdjoint *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< optionAdjoint > set (const label i, autoPtr< optionAdjoint > &aptr)
Set element to given autoPtr and return old element.
autoPtr< optionAdjoint > set (const label i, autoPtr< optionAdjoint > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< optionAdjoint > set (const label i, const tmp< optionAdjoint > &tptr)
Set element to given tmp and return old element.
autoPtr< optionAdjoint > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< optionAdjoint > &list)
Copy assignment.
void operator= (PtrList< optionAdjoint > &&list)
Move assignment.
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
const dictionary & optionAdjointsDict (const dictionary &dict) const
Return the "optionAdjoints" sub-dictionary if present otherwise return dict.
bool readOptionAdjoints (const dictionary &dict)
Read optionAdjoints dictionary.
void checkApplied () const
Check that all sources have been applied.
Protected Member Functions inherited from PtrList< optionAdjoint >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
label checkTimeIndex_
Time index to check that all defined sources have been applied.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Friends
Ostream & operator<< (Ostream &os, const optionAdjointList &optionAdjoints)
Ostream operator.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Detailed Description
DescriptionAdjoint List of finite volume optionAdjoints
SourceFile optionAdjointList.C
Definition at line 52 of file fvOptionAdjointList.H.
Constructor & Destructor Documentation
optionAdjointList (const fvMesh & mesh)
Construct null.
Definition at line 99 of file fvOptionAdjointList.C.
References reset().
optionAdjointList (const fvMesh & mesh, const dictionary & dict)
Construct from mesh and dictionary.
Definition at line 86 of file fvOptionAdjointList.C.
virtual ~optionAdjointList () virtual default
Destructor.
Member Function Documentation
const Foam::dictionary & optionAdjointsDict (const dictionary & dict) const protected
Return the "optionAdjoints" sub-dictionary if present otherwise return dict.
Definition at line 40 of file fvOptionAdjointList.C.
bool readOptionAdjoints (const dictionary & dict) protected
Read optionAdjoints dictionary.
Definition at line 55 of file fvOptionAdjointList.C.
References dict.
void checkApplied () const protected
Check that all sources have been applied.
Definition at line 70 of file fvOptionAdjointList.C.
TypeName ("optionAdjointList")
Runtime type information.
void reset (const dictionary & dict)
Reset the source list.
Definition at line 109 of file fvOptionAdjointList.C.
void correct (GeometricField< Type, fvPatchField, volMesh > & fld)
Correct.
Definition at line 27 of file fvOptionAdjointListTemplates.C.
References option::applyToField(), option::correct(), Foam::expressions::patchExpr::debug, Foam::endl(), forAll, i, Foam::Info, option::isActive(), option::name(), IOobject::name(), UPtrList< T >::operator[](), and option::setApplied().
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld)
Return source for equation.
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Return source for equation with specified name.
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Return source for equation.
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Return source for equation with specified name.
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Return source for equation.
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Return source for equation with specified name.
void constrain (fvMatrix< Type > & eqn)
Apply constraints to equation.
Definition at line 219 of file fvOptionAdjointListTemplates.C.
bool read (const dictionary & dict) virtual
Read dictionary.
Definition at line 140 of file fvOptionAdjointList.C.
bool writeData (Ostream & os) const virtual
Write data to Ostream.
Definition at line 146 of file fvOptionAdjointList.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld)
Definition at line 60 of file fvOptionAdjointListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Definition at line 70 of file fvOptionAdjointListTemplates.C.
References fld.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Definition at line 111 of file fvOptionAdjointListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Definition at line 122 of file fvOptionAdjointListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld)
Definition at line 164 of file fvOptionAdjointListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & fld, const word & fieldName)
Definition at line 176 of file fvOptionAdjointListTemplates.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const optionAdjointList & optionAdjoints) friend
Ostream operator.
Definition at line 165 of file fvOptionAdjointList.C.
Member Data Documentation
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 78 of file fvOptionAdjointList.H.
label checkTimeIndex_ protected
Time index to check that all defined sources have been applied.
Definition at line 83 of file fvOptionAdjointList.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/fvOptionsAdjoint/fvOptions/fvOptionAdjointList.H
src/optimisation/adjointOptimisation/adjoint/fvOptionsAdjoint/fvOptions/fvOptionAdjointList.C
src/optimisation/adjointOptimisation/adjoint/fvOptionsAdjoint/fvOptions/fvOptionAdjointListTemplates.C