OpenFOAM: TimeState Class Reference
TimeState Class Reference
The time value with time-stepping information, user-defined remapping, etc.
Public Member Functions
TimeState ()
Construct a zero time state, using the current time formatting.
virtual ~TimeState ()=default
Destructor.
virtual scalar userTimeToTime (const scalar theta) const
Convert the user-time (e.g. CA deg) to real-time (s).
virtual scalar timeToUserTime (const scalar t) const
Convert the real-time (s) into user-time (e.g. CA deg)
scalar timeOutputValue () const
Return current time value.
label timeIndex () const
Return current time index.
scalar deltaTValue () const
Return time step value.
scalar deltaT0Value () const
Return old time step value.
dimensionedScalar deltaT () const
Return time step.
dimensionedScalar deltaT0 () const
Return old time step.
bool writeTime () const
Return true if this is a write time.
bool outputTime () const
Deprecated(2016-05) return true if this is a write time.
Public Member Functions inherited from dimensioned< scalar >
dimensioned ()
A dimensionless Zero, named "0".
dimensioned (const dimensionSet &dims)
A dimensioned Zero, named "0".
dimensioned (const dimensionSet &dims, const zero)
A dimensioned Zero, named "0".
dimensioned (const scalar &val)
Implicit construct dimensionless from given value.
dimensioned (const word &name, const dimensioned< scalar > &dt)
Copy construct dimensioned Type with a new name.
dimensioned (const word &name, const dimensionSet &dims, const scalar &val)
Construct from components (name, dimensions, value).
dimensioned (const primitiveEntry &e)
Construct from primitive entry with given name.
dimensioned (const primitiveEntry &e, const dimensionSet &dims)
Construct from primitive entry with given name and dimensions.
dimensioned (const word &name, const dictionary &dict)
Construct from dictionary lookup with a given name.
dimensioned (const word &name, const dimensionSet &dims, const dictionary &dict)
Construct from dictionary lookup with a given name and dimensions.
dimensioned (const word &name, const dimensionSet &dims, const dictionary &dict, const word &entryName)
Construct from dictionary lookup with a given name and dimensions.
dimensioned (const word &name, const dimensionSet &dims, const scalar &val, const dictionary &dict)
Construct from components (name, dimensions, value) with optional dictionary override.
dimensioned (Istream &is) FOAM_DEPRECATED(2018-11)
Deprecated(2018-11) Construct from Istream (expects name, dimensions, value)
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const scalar & value () const
Return const reference to value.
scalar & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction d) const
Return a component as a dimensioned<cmptType>
void replace (const direction d, const dimensioned< cmptType > &dc)
Return a component with a dimensioned<cmptType>
dimensioned< scalar > T () const
Return transpose.
bool read (const dictionary &dict)
Update the value of dimensioned<Type>, lookup in dictionary with the name().
bool read (const word &entryName, const dictionary &dict)
Update the value of dimensioned<Type>, using an alternative entry name.
Istream & read (Istream &is, const bool readName=true)
Read (name, dimensions, value) from stream, using units from system table.
Istream & read (Istream &is, const dictionary &readSet)
Read (name, dimensions, value) from stream, using units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &readSet)
Read (name, dimensions, value) from stream, using units from table.
bool readIfPresent (const dictionary &dict)
Update the value of dimensioned<Type> if found in the dictionary, lookup in dictionary with the name().
bool readIfPresent (const word &entryName, const dictionary &dict)
Update the value of dimensioned<Type> if found in the dictionary, using an alternative entry name.
void writeEntry (const word &keyword, Ostream &os) const
Write as a dictionary entry with keyword.
dimensioned< cmptType > operator[] (const direction d) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< scalar > &dt)
void operator-= (const dimensioned< scalar > &dt)
void operator*= (const scalar s)
void operator/= (const scalar s)
FOAM_DEPRECATED (2018-11)
Deprecated(2018-11) Construct from Istream with given name (expects dimensions, value)
FOAM_DEPRECATED (2018-11)
Deprecated(2018-11) Construct from Istream with given name and expected dimensions.
Protected Attributes
label timeIndex_
label writeTimeIndex_
scalar deltaT_
scalar deltaT0_
scalar deltaTSave_
bool deltaTchanged_
bool writeTime_
Additional Inherited Members
Public Types inherited from dimensioned< scalar >
typedef scalar value_type
The underlying data type.
typedef pTraits< scalar >::cmptType cmptType
Component type.
Static Public Member Functions inherited from dimensioned< scalar >
static dimensioned< scalar > getOrDefault (const word &name, const dictionary &dict, const dimensionSet &dims=dimless, const scalar &deflt=scalar(Zero))
Construct dimensioned from dictionary, with default value. FatalIOError if there are excess tokens.
static dimensioned< scalar > getOrDefault (const word &name, const dictionary &dict, const scalar &deflt=scalar(Zero))
Construct dimensionless from dictionary, with default value.
static dimensioned< scalar > getOrAddToDict (const word &name, dictionary &dict, const dimensionSet &dims=dimless, const scalar &deflt=scalar(Zero))
Construct dimensioned from dictionary, with default value.
static dimensioned< scalar > getOrAddToDict (const word &name, dictionary &dict, const scalar &deflt=scalar(Zero))
Construct dimensionless from dictionary, with default value.
static dimensioned< scalar > lookupOrDefault (const word &name, const dictionary &dict, const dimensionSet &dims=dimless, const scalar &deflt=scalar(Zero))
Construct dimensioned from dictionary, with default value. FatalIOError if there are excess tokens.
static dimensioned< scalar > lookupOrDefault (const word &name, const dictionary &dict, const scalar &deflt=scalar(Zero))
Construct dimensionless from dictionary, with default value.
static dimensioned< scalar > lookupOrAddToDict (const word &name, dictionary &dict, const dimensionSet &dims=dimless, const scalar &deflt=scalar(Zero))
Construct dimensioned from dictionary, with default value.
static dimensioned< scalar > lookupOrAddToDict (const word &name, dictionary &dict, const scalar &deflt=scalar(Zero))
Construct dimensionless from dictionary, with default value.
Detailed Description
The time value with time-stepping information, user-defined remapping, etc.
Source files
TimeState.H
TimeState.C
Definition at line 47 of file TimeState.H.
Constructor & Destructor Documentation
TimeState ()
Construct a zero time state, using the current time formatting.
Definition at line 27 of file TimeState.C.
virtual ~TimeState () virtual default
Destructor.
Member Function Documentation
Foam::scalar userTimeToTime (const scalar theta) const virtual
Convert the user-time (e.g. CA deg) to real-time (s).
Reimplemented in crankConRod.
Definition at line 42 of file TimeState.C.
Referenced by ConeInjection< CloudType >::ConeInjection(), InflationInjection< CloudType >::InflationInjection(), KinematicLookupTableInjection< CloudType >::KinematicLookupTableInjection(), PatchFlowRateInjection< CloudType >::PatchFlowRateInjection(), PatchInjection< CloudType >::PatchInjection(), ReactingLookupTableInjection< CloudType >::ReactingLookupTableInjection(), ReactingMultiphaseLookupTableInjection< CloudType >::ReactingMultiphaseLookupTableInjection(), and ThermoLookupTableInjection< CloudType >::ThermoLookupTableInjection().
Foam::scalar timeToUserTime (const scalar t) const virtual
Convert the real-time (s) into user-time (e.g. CA deg)
Reimplemented in crankConRod.
Definition at line 48 of file TimeState.C.
Referenced by TimeState::timeIndex().
Foam::scalar timeOutputValue () const inline
Return current time value.
Definition at line 23 of file TimeStateI.H.
Foam::label timeIndex () const inline
Return current time index.
Definition at line 29 of file TimeStateI.H.
References TimeState::timeToUserTime(), and dimensioned< scalar >::value().
Referenced by sampledThresholdCellFaces::expire(), sampledIsoSurface::expire(), sampledIsoSurfaceCell::needsUpdate(), and data::setSolverPerformance().
Foam::scalar deltaTValue () const inline
Return time step value.
Definition at line 35 of file TimeStateI.H.
Referenced by averageCondition::calc(), fieldAverageItem::calculateMeanField(), Foam::MULES::correct(), and Foam::MULES::explicitSolve().
Foam::scalar deltaT0Value () const inline
Return old time step value.
Definition at line 41 of file TimeStateI.H.
Foam::dimensionedScalar deltaT () const inline
Return time step.
Definition at line 47 of file TimeStateI.H.
Referenced by kinematicSingleLayer::gNorm().
Foam::dimensionedScalar deltaT0 () const inline
Return old time step.
Definition at line 53 of file TimeStateI.H.
References Foam::dimTime.
bool writeTime () const inline
Return true if this is a write time.
Definition at line 59 of file TimeStateI.H.
References Foam::dimTime.
bool outputTime () const inline
Deprecated(2016-05) return true if this is a write time.
Deprecated:
(2016-05) - use writeTime() method
Definition at line 137 of file TimeState.H.
Member Data Documentation
label timeIndex_ protected
Definition at line 53 of file TimeState.H.
label writeTimeIndex_ protected
Definition at line 54 of file TimeState.H.
scalar deltaT_ protected
Definition at line 56 of file TimeState.H.
scalar deltaT0_ protected
Definition at line 57 of file TimeState.H.
scalar deltaTSave_ protected
Definition at line 58 of file TimeState.H.
bool deltaTchanged_ protected
Definition at line 60 of file TimeState.H.
bool writeTime_ protected
Definition at line 61 of file TimeState.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/TimeState.H
src/OpenFOAM/db/Time/TimeState.C
src/OpenFOAM/db/Time/TimeStateI.H