OpenFOAM: token::compound Class Reference
token::compound Class Reference abstract
Abstract base class for complex tokens.
Public Member Functions
TypeName ("compound")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, compound, Istream,(Istream &is),(is))
Declare run-time constructor selection table.
compound ()
Construct null.
virtual ~compound ()=default
Destructor.
bool empty () const
bool & empty ()
virtual label size () const =0
virtual void write (Ostream &os) const =0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static autoPtr< compound > New (const word &type, Istream &is)
Select null constructed.
static bool isCompound (const word &name)
Return true if name is a known (registered) compound type.
Friends
Ostream & operator<< (Ostream &os, const compound &ct)
Output operator.
Detailed Description
Abstract base class for complex tokens.
Definition at line 148 of file token.H.
Constructor & Destructor Documentation
compound () inline
Construct null.
Definition at line 189 of file token.H.
virtual ~compound () virtual default
Destructor.
Member Function Documentation
TypeName ("compound")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , compound , Istream , (Istream &is) , (is))
Declare run-time constructor selection table.
Foam::autoPtr< Foam::token::compound > New (const word & type, Istream & is) static
Select null constructed.
Definition at line 49 of file token.C.
bool isCompound (const word & name) static
Return true if name is a known (registered) compound type.
Definition at line 73 of file token.C.
bool empty () const inline
Definition at line 216 of file token.H.
Referenced by Foam::printTokenInfo().
bool& empty () inline
Definition at line 221 of file token.H.
References token::Compound< T >::Compound(), token::Compound< T >::size(), Foam::T(), token::Compound< T >::TypeName(), and token::Compound< T >::write().
virtual label size () const pure virtual
Implemented in token::Compound< T >.
virtual void write (Ostream & os) const pure virtual
Implemented in token::Compound< T >.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const compound & ct) friend
Output operator.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/token/token.H
src/OpenFOAM/db/IOstreams/token/token.C