OpenFOAM: adjointSpalartAllmaras Class Reference
adjointSpalartAllmaras Class Reference
Continuous adjoint to the Spalart-Allmaras one-eqn mixing-length model for incompressible flows.
Public Member Functions
TypeName ("adjointSpalartAllmaras")
Runtime type information.
adjointSpalartAllmaras (incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName=adjointTurbulenceModel::typeName, const word &modelName=typeName)
Construct from components.
virtual ~adjointSpalartAllmaras ()=default
Destructor.
virtual tmp< volSymmTensorField > devReff () const
Return the effective stress tensor including the laminar stress.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const
Return the diffusion term for the momentum equation.
virtual tmp< volVectorField > adjointMeanFlowSource ()
Source terms to the adjoint momentum equation due to the differentiation of the turbulence model.
virtual tmp< volScalarField > nutJacobianTMVar1 () const
Jacobian of nut wrt the first turbulence model variable.
virtual tmp< scalarField > diffusionCoeffVar1 (label patchI) const
Diffusion coefficient of the first primal and adjoint turbulence model equation. Needed for some adjoint BCs. Defaults to zero.
virtual const boundaryVectorField & adjointMomentumBCSource () const
Source for the outlet adjoint momentum BC coming from differentiating the turbulence model.
virtual const boundaryVectorField & wallShapeSensitivities ()
Sensitivity terms for shape optimisation, emerging from.
virtual const boundaryVectorField & wallFloCoSensitivities ()
Sensitivity terms for flow control, emerging from the.
virtual tmp< volScalarField > distanceSensitivities ()
Sensitivity terms resulting from the differentiation of the distance field. Misses dxdb, to be added by the classes assembling the sensitivities.
virtual tmp< volTensorField > FISensitivityTerm ()
Term contributing to the computation of FI-based sensitivities.
virtual void nullify ()
Nullify all adjoint turbulence model fields and their old times.
virtual void correct ()
Solve the adjoint turbulence equations.
virtual bool read ()
Read adjointRASProperties dictionary.
Public Member Functions inherited from adjointRASModel
TypeName ("adjointRASModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, adjointRASModel, dictionary,(incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName),(primalVars, adjointVars, objManager, adjointTurbulenceModelName))
adjointRASModel (const word &type, incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName=adjointTurbulenceModel::typeName)
Construct from components.
virtual ~adjointRASModel ()=default
Destructor.
const nearWallDist & y () const
Return the near wall distances.
const dictionary & coeffDict () const
Const access to the coefficients dictionary.
volScalarField & getAdjointTMVariable1Inst ()
Return non-constant reference to adjoint turbulence model variable 1.
volScalarField & getAdjointTMVariable2Inst ()
Return non-constant reference to adjoint turbulence model variable 2.
volScalarField & getAdjointTMVariable1 ()
Return non-constant reference to adjoint turbulence model variable 1.
volScalarField & getAdjointTMVariable2 ()
Return non-constant reference to adjoint turbulence model variable 2.
autoPtr< volScalarField > & getAdjointTMVariable1InstPtr ()
Return non-constant autoPtr to adjoint turbulence model variable 1.
autoPtr< volScalarField > & getAdjointTMVariable2InstPtr ()
Return non-constant autoPtr to adjoint turbulence model variable 2.
virtual tmp< volScalarField > nutJacobianTMVar2 () const
Jacobian of nut wrt the second turbulence model variable.
virtual tmp< scalarField > diffusionCoeffVar2 (label patchI) const
Diffusion coefficient of the second primal and adjoint turbulence model equation. Needed for some adjoint BCs. Defaults to zero.
void setChangedPrimalSolution ()
Set flag of changed primal solution to true.
void resetMeanFields ()
Reset mean fields to zero.
void computeMeanFields ()
Average adjoint fields on the fly.
bool includeDistance () const
Should the adjoint to the eikonal equation be computed.
Public Member Functions inherited from adjointTurbulenceModel
TypeName ("adjointTurbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable (autoPtr, adjointTurbulenceModel, adjointTurbulenceModel,(incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName),(primalVars, adjointVars, objManager, adjointTurbulenceModelName))
adjointTurbulenceModel (incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName=typeName)
Construct from components.
virtual ~adjointTurbulenceModel ()=default
Destructor.
tmp< volScalarField > nu () const
Return the laminar viscosity.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual bool writeData (Ostream &) const
Default dummy write function.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Public Member Functions inherited from IOdictionary
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
virtual bool global () const
Is object global.
virtual fileName filePath () const
Return complete path + object name if the file exists.
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const IOobject &)
Construct given an IOobject.
baseIOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
baseIOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~baseIOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
virtual bool readData (Istream &)
ReadData function required for regIOobject read operation.
virtual bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const baseIOdictionary &)
Assignment of other baseIOdictionary's entries to this.
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
Construct given the entry name, parent dictionary and Istream, reading entries until EOF, optionally keeping the header.
dictionary (Istream &is)
Construct top-level dictionary from Istream, reading entries until EOF. Discards the header.
dictionary (Istream &is, bool keepHeader)
Construct top-level dictionary from Istream, reading entries until EOF, optionally keeping the header.
dictionary (const dictionary &parentDict, const dictionary &dict)
Copy construct given the parent dictionary.
dictionary (const dictionary &dict)
Copy construct top-level dictionary.
dictionary (const dictionary *dict)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, dictionary &&dict)
Move construct for given parent dictionary.
dictionary (dictionary &&dict)
Move construct top-level dictionary.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const fileName & name () const
The dictionary name.
fileName & name ()
The dictionary name for modification (use with caution).
word dictName () const
The local dictionary name (final part of scoped name)
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Search for an entry (const access) with the given keyword.
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find for an entry (non-const access) with the given keyword.
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry (const access) with the given keyword.
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Search for a scoped entry (const access) with the given keyword.
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary pointer if present.
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary pointer if present.
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
Search for an entry (const access) with the given keyword.
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return an entry data stream. FatalIOError if not found, or if the number of tokens is incorrect.
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T. FatalIOError if not found, or if the number of tokens is incorrect.
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T with additional checking FatalIOError if not found, or if the number of tokens is incorrect.
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Check if entry is found and is a sub-dictionary.
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary.
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary for manipulation.
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
Find and return a sub-dictionary as a copy, otherwise return an empty dictionary.
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary, otherwise return this dictionary.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
template<class Compare >
wordList sortedToc (const Compare &comp) const
Return table of contents sorted using the specified comparator.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
Substitute the given keyword (which is prefixed by '$')
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
Substitute the given scoped keyword (which is prefixed by '$')
entry * add (entry *entryPtr, bool mergeEntry=false)
Add a new entry.
entry * add (const entry &e, bool mergeEntry=false)
Add an entry.
entry * add (const keyType &k, const word &v, bool overwrite=false)
Add a word entry.
entry * add (const keyType &k, const string &v, bool overwrite=false)
Add a string entry.
entry * add (const keyType &k, const label v, bool overwrite=false)
Add a label entry.
entry * add (const keyType &k, const scalar v, bool overwrite=false)
Add a scalar entry.
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
Add a T entry.
entry * set (entry *entryPtr)
Assign a new entry, overwriting any existing entry.
entry * set (const entry &e)
Assign a new entry, overwriting any existing entry.
entry * set (const keyType &k, const dictionary &v)
Assign a dictionary entry, overwriting any existing entry.
template<class T >
entry * set (const keyType &k, const T &v)
Assign a T entry, overwriting any existing entry.
bool remove (const word &keyword)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &dict)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &dict)
Transfer the contents of the argument and annul the argument.
void checkITstream (const ITstream &is, const word &keyword) const
Check after reading if the input token stream has unconsumed tokens remaining or if there were no tokens in the first place.
bool read (Istream &is)
Read dictionary from Istream.
bool read (Istream &is, bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void writeEntry (const keyType &keyword, Ostream &os) const
Write sub-dictionary with the keyword as its header.
void writeEntries (Ostream &os, const bool extraNewLine=false) const
Write dictionary entries.
void write (Ostream &os, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
const_searcher csearch (const word &keyword, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword.
const_searcher search (const word &keyword, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword.
searcher search (const word &keyword, enum keyType::option=keyType::REGEX)
Search dictionary for given keyword.
const_searcher csearchScoped (const word &keyword, enum keyType::option) const
Search using scoping.
const_searcher searchScoped (const word &keyword, enum keyType::option) const
Search using dot or slash scoping.
searcher searchScoped (const word &keyword, enum keyType::option)
Search using dot or slash scoping.
const dictionary * cfindScopedDict (const fileName &dictPath) const
Locate a sub-dictionary using slash-scoping.
const dictionary * findScopedDict (const fileName &dictPath) const
Locate a sub-dictionary using slash-scoping.
dictionary * findScopedDict (const fileName &dictPath)
Locate a sub-dictionary using slash-scoping.
dictionary * makeScopedDict (const fileName &dictPath)
Locate existing or create sub-dictionary using slash-scoping.
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option) const
Find and return an entry pointer if present, or return a nullptr, using any compatibility names if needed.
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option) const
Find and return an entry if present, otherwise FatalIOError, using any compatibility names if needed.
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Find and return an entry data stream, using any compatibility names if needed.
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Find and return a T using any compatibility names if needed. FatalIOError if not found, or if there are excess tokens.
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, const T &deflt, enum keyType::option=keyType::REGEX) const
Find and return a T, or return the given default value using any compatibility names if needed.
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, T &val, enum keyType::option=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val using any compatibility names if needed. FatalIOError if there are excess tokens.
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, T &val, enum keyType::option=keyType::REGEX) const
Find an entry if present, and assign to T val using any compatibility names if needed. FatalIOError if it is found and there are excess tokens.
void operator= (const dictionary &rhs)
Copy assignment.
void operator+= (const dictionary &rhs)
Include entries from the given dictionary.
void operator|= (const dictionary &rhs)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &rhs)
Unconditionally include entries from the given dictionary.
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T lookupOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value using any compatibility names if needed.
ITstream & FOAM_DEPRECATED_FOR (2018-07,"lookup() method") operator[](const word &keyword) const
Deprecated(2018-07) find and return an entry data stream.
template<class T >
T FOAM_DEPRECATED_FOR (2018-10,"get() method") lookupType(const word &keyword
Deprecated(2018-10) find and return a T.
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
Null construct.
ILList (T *item)
Construct and insert the initial T item pointer.
ILList (Istream &is)
Construct from Istream.
ILList (const ILList< LListBase, T > &lst)
Copy construct using the 'clone()' method for each element.
ILList (ILList< LListBase, T > &&lst)
Move construct.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone 'clone()'.
template<class INew >
ILList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *item)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &lst)
Transfer the contents of the argument into this List and annul the argument list.
void operator= (const ILList< LListBase, T > &lst)
Copy assignment using the 'clone()' method for each element.
void operator= (ILList< LListBase, T > &&lst)
Move assignment.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
Null construct.
UILList (T *item)
Construct and insert the initial T item.
UILList (const UILList< LListBase, T > &lst)
Construct as copy.
T * first ()
The first entry in the list.
const T * first () const
The first entry in the list (const access)
T * last ()
The last entry in the list.
const T * last () const
The last entry in the list (const access)
T * removeHead ()
Remove and return head.
T * remove (T *item)
Remove and return element.
T * remove (iterator &iter)
Remove and return item specified by iterator.
void operator= (const UILList< LListBase, T > &lst)
Copy assignment.
bool operator== (const UILList< LListBase, T > &lst) const
Equality. True both lists are element-wise equal.
bool operator!= (const UILList< LListBase, T > &lst) const
The opposite of the equality operation. Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write UILList with line-breaks when length exceeds shortLen.
iterator begin ()
Iterator to first item in list with non-const access.
const_iterator cbegin () const
Iterator to first item in list with const access.
reverse_iterator rbegin ()
Iterator to last item in list with non-const access.
const_reverse_iterator crbegin () const
Iterator to last item in list with const access.
const_iterator begin () const
Iterator to first item in list with const access.
const_reverse_iterator rbegin () const
Iterator to last item in list with const access.
const iterator & end ()
End of list for forward iterators.
const const_iterator & cend () const
End of list for forward iterators.
const reverse_iterator & rend ()
End of list for reverse iterators.
const const_reverse_iterator & crend () const
End of list for reverse iterators.
const const_iterator & end () const
End of list for forward iterators.
const const_reverse_iterator & rend () const
End of list for reverse iterators.
Protected Member Functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > r (const volScalarField &Stilda) const
tmp< volScalarField > fw (const volScalarField &Stilda) const
tmp< volScalarField > DnuTildaEff () const
const volScalarField & nuTilda () const
References to the primal turbulence model variables.
const volScalarField & nut () const
Return the turbulence viscosity.
tmp< volScalarField > dFv1_dChi (const volScalarField &chi) const
tmp< volScalarField > dFv2_dChi (const volScalarField &chi, const volScalarField &fv1, const volScalarField &dFv1dChi) const
tmp< volScalarField > dStilda_dOmega (const volScalarField &Omega, const volScalarField &fv2) const
tmp< volScalarField > dStilda_dNuTilda (const volScalarField &Omega, const volScalarField &fv2, const volScalarField &dFv2dChi) const
tmp< volScalarField > dStilda_dDelta (const volScalarField &Omega, const volScalarField &fv2) const
tmp< volScalarField > dr_dNuTilda (const volScalarField &Stilda) const
tmp< volScalarField > dr_dStilda (const volScalarField &Stilda) const
tmp< volScalarField > dr_dDelta (const volScalarField &Stilda) const
tmp< volScalarField > dfw_dr (const volScalarField &Stilda) const
tmp< volScalarField > dfw_dNuTilda (const volScalarField &Stilda, const volScalarField &dfwdr, const volScalarField &dStildadNuTilda) const
tmp< volScalarField > dfw_dOmega (const volScalarField &Stilda, const volScalarField &dfwdr, const volScalarField &dStildadOmega) const
tmp< volScalarField > dfw_dDelta (const volScalarField &Stilda, const volScalarField &dfwdr, const volScalarField &dStildadDelta) const
tmp< volScalarField > dD_dNuTilda (const volScalarField &fw, const volScalarField &dfwdNuTilda) const
tmp< volScalarField > dP_dNuTilda (const volScalarField &dStildadNuTilda) const
tmp< volScalarField > dnut_dNuTilda (const volScalarField &fv1, const volScalarField &dFv1dChi) const
tmp< volVectorField > conservativeMomentumSource ()
Conservative source term for the adjoint momentum equations.
volScalarField & nuaTilda ()
Access to the adjoint Spalart - Allmaras field.
void updatePrimalRelatedFields ()
Update the constant primal-related fields.
tmp< volScalarField > allocateMask ()
Allocate the mask field.
Protected Member Functions inherited from adjointRASModel
virtual void printCoeffs ()
Print model coefficients.
void setMeanFields ()
Set mean fields.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Protected Attributes
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cs_
bool limitAdjointProduction_
Whether to limit the adjoint production term to enhance stability.
const volScalarField & y_
Wall distance.
volScalarField mask_
Field for masking (convergence enhancement)
volSymmTensorField symmAdjointProductionU_
volScalarField productionDestructionSource_
volScalarField Stilda_
volScalarField r_
volScalarField fw_
volScalarField Cdnut_
volTensorField momentumSourceMult_
volTensorField gradU_
volVectorField gradNuTilda_
dimensionedScalar minStilda_
Protected Attributes inherited from adjointRASModel
objectiveManager & objectiveManager_
Reference to the objectiveManager.
Switch adjointTurbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
nearWallDist y_
Near wall distance boundary field.
autoPtr< volScalarField > adjointTMVariable1Ptr_
Adjoint turbulence model variable 1.
autoPtr< volScalarField > adjointTMVariable2Ptr_
Adjoint turbulence model variable 2.
autoPtr< volScalarField > adjointTMVariable1MeanPtr_
Adjoint turbulence model variable 1, mean value.
autoPtr< volScalarField > adjointTMVariable2MeanPtr_
Adjoint turbulence model variable 2, mean value.
autoPtr< boundaryVectorField > adjMomentumBCSourcePtr_
Source to the adjoint momentum BC emerging from differentiating the turbulence model.
autoPtr< boundaryVectorField > wallShapeSensitivitiesPtr_
Wall sensitivity term for shape optimisation.
autoPtr< boundaryVectorField > wallFloCoSensitivitiesPtr_
Wall sensitivity term for flow control optimisation.
bool includeDistance_
Does the turbulence model include distances and should the adjoint to the distance field be computed.
bool changedPrimalSolution_
Has the primal solution changed?
Protected Attributes inherited from adjointTurbulenceModel
incompressibleVars & primalVars_
incompressibleAdjointMeanFlowVars & adjointVars_
const Time & runTime_
const fvMesh & mesh_
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
Searcher with const access.
typedef Searcher< false > searcher
Searcher with non-const access.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values stored.
typedef T * pointer
Pointer for value_type.
typedef const T * const_pointer
Const pointer for value_type.
typedef T & reference
Reference for value_type.
typedef const T & const_reference
Const reference for value_type.
typedef label size_type
The type that can represent the container size.
typedef label difference_type
The difference between iterator objects.
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Static Public Member Functions inherited from adjointRASModel
static autoPtr< adjointRASModel > New (incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName=adjointTurbulenceModel::typeName)
Return a reference to the selected adjointRAS model.
Static Public Member Functions inherited from adjointTurbulenceModel
static autoPtr
< adjointTurbulenceModel > New (incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName=typeName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &is)
Construct top-level dictionary on freestore from Istream.
Public Attributes inherited from dictionary
friend const_searcher
Declare friendship with the searcher classes.
friend searcher
T bool recursive = false
T bool bool patternMatch
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
Report optional keywords and values if not present in dictionary.
static const dictionary null
An empty dictionary, which is also the parent for all dictionaries.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Continuous adjoint to the Spalart-Allmaras one-eqn mixing-length model for incompressible flows.
Reference:
    For the adjoint to the Spalart-Allmaras PDE
        Zymaris, A., Papadimitriou, D., Giannakoglou, K., &
        Othmer, C. (2009).
        Continuous adjoint approach to the Spalart-Allmaras turbulence
        model for incompressible flows.
        Computers & Fluids, 38(8), 1528-538.
        http://doi.org/10.1016/j.compfluid.2008.12.006
    For the FI sensitivity terms
        Papoutsis-Kiachagias, E. M., Asouti, V. G., Giannakoglou, K. C.,
        Gkagkas, K., Shimokawa, S., & Itakura, E. (2018).
        Multi-point aerodynamic shape optimization of cars based on
        continuous adjoint.
        Structural and Multidisciplinary Optimization, 59(2), 675-694.
        http://doi.org/10.1007/s00158-018-2091-3
Both of the above-mentioned papers develop the adjoint to the Spalart-Allmaras PDE that includes the fv3 term. The current implementation corresponds to the Spalart-Allmaras PDE as programmed within OpenFOAM and is, thus, slightly different than the one developed in the cited papers
Source files
adjointSpalartAllmaras.H
adjointSpalartAllmaras.C
Definition at line 83 of file adjointSpalartAllmaras.H.
Constructor & Destructor Documentation
adjointSpalartAllmaras (incompressibleVars & primalVars, incompressibleAdjointMeanFlowVars & adjointVars, objectiveManager & objManager, const word & adjointTurbulenceModelName = adjointTurbulenceModel::typeName, const word & modelName = typeName)
Construct from components.
Definition at line 468 of file adjointSpalartAllmaras.C.
virtual ~adjointSpalartAllmaras () virtual default
Destructor.
Member Function Documentation
tmp< volScalarField > chi () const protected
Definition at line 56 of file adjointSpalartAllmaras.C.
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 62 of file adjointSpalartAllmaras.C.
References adjointTurbulenceModel::nu(), and adjointSpalartAllmaras::nuTilda().
Referenced by adjointSpalartAllmaras::conservativeMomentumSource(), and adjointSpalartAllmaras::Stilda().
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 70 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::Cv1_, and Foam::pow3().
tmp< volScalarField > Stilda (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 80 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::fv1().
tmp< volScalarField > r (const volScalarField & Stilda) const protected
Definition at line 100 of file adjointSpalartAllmaras.C.
tmp< volScalarField > fw (const volScalarField & Stilda) const protected
Definition at line 122 of file adjointSpalartAllmaras.C.
Referenced by adjointSpalartAllmaras::dP_dNuTilda().
tmp< volScalarField > DnuTildaEff () const protected
Definition at line 132 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::Cw2_, adjointSpalartAllmaras::Cw3_, g, Foam::pow(), Foam::pow6(), and adjointSpalartAllmaras::r_.
const volScalarField & nuTilda () const protected
References to the primal turbulence model variables.
Definition at line 141 of file adjointSpalartAllmaras.C.
Referenced by adjointSpalartAllmaras::conservativeMomentumSource(), adjointSpalartAllmaras::dP_dNuTilda(), and adjointSpalartAllmaras::fv1().
const volScalarField & nut () const protected virtual
Return the turbulence viscosity.
Reimplemented from adjointTurbulenceModel.
Definition at line 147 of file adjointSpalartAllmaras.C.
References adjointTurbulenceModel::primalVars_, and incompressibleVars::RASModelVariables().
tmp< volScalarField > dFv1_dChi (const volScalarField & chi) const protected
Definition at line 156 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dFv2_dChi (const volScalarField & chi, const volScalarField & fv1, const volScalarField & dFv1dChi) const protected
Definition at line 167 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dStilda_dOmega (const volScalarField & Omega, const volScalarField & fv2) const protected
Definition at line 178 of file adjointSpalartAllmaras.C.
References Foam::sqr().
tmp< volScalarField > dStilda_dNuTilda (const volScalarField & Omega, const volScalarField & fv2, const volScalarField & dFv2dChi) const protected
Definition at line 193 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dStilda_dDelta (const volScalarField & Omega, const volScalarField & fv2) const protected
Definition at line 207 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dr_dNuTilda (const volScalarField & Stilda) const protected
Definition at line 220 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dr_dStilda (const volScalarField & Stilda) const protected
Definition at line 236 of file adjointSpalartAllmaras.C.
Referenced by adjointSpalartAllmaras::dD_dNuTilda(), and adjointSpalartAllmaras::dfw_dDelta().
tmp< volScalarField > dr_dDelta (const volScalarField & Stilda) const protected
Definition at line 252 of file adjointSpalartAllmaras.C.
Referenced by adjointSpalartAllmaras::dD_dNuTilda().
tmp< volScalarField > dfw_dr (const volScalarField & Stilda) const protected
Definition at line 268 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dfw_dNuTilda (const volScalarField & Stilda, const volScalarField & dfwdr, const volScalarField & dStildadNuTilda) const protected
Definition at line 284 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dfw_dOmega (const volScalarField & Stilda, const volScalarField & dfwdr, const volScalarField & dStildadOmega) const protected
Definition at line 298 of file adjointSpalartAllmaras.C.
tmp< volScalarField > dfw_dDelta (const volScalarField & Stilda, const volScalarField & dfwdr, const volScalarField & dStildadDelta) const protected
Definition at line 309 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::dr_dStilda().
tmp< volScalarField > dD_dNuTilda (const volScalarField & fw, const volScalarField & dfwdNuTilda) const protected
Definition at line 320 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::dr_dDelta(), and adjointSpalartAllmaras::dr_dStilda().
tmp< volScalarField > dP_dNuTilda (const volScalarField & dStildadNuTilda) const protected
Definition at line 330 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::Cw1_, adjointSpalartAllmaras::fw(), adjointSpalartAllmaras::nuTilda(), and Foam::sqr().
tmp< volScalarField > dnut_dNuTilda (const volScalarField & fv1, const volScalarField & dFv1dChi) const protected
Definition at line 339 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::Cb1_.
tmp< volVectorField > conservativeMomentumSource () protected
Conservative source term for the adjoint momentum equations.
Sets also the adjointMomentumBCSource
Definition at line 348 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::fv1(), adjointTurbulenceModel::nu(), and adjointSpalartAllmaras::nuTilda().
volScalarField& nuaTilda () inline protected
Access to the adjoint Spalart - Allmaras field.
Definition at line 293 of file adjointSpalartAllmaras.H.
Referenced by adjointSpalartAllmaras::correct().
void updatePrimalRelatedFields () protected
Update the constant primal-related fields.
Definition at line 368 of file adjointSpalartAllmaras.C.
tmp< volScalarField > allocateMask () protected
Allocate the mask field.
Definition at line 434 of file adjointSpalartAllmaras.C.
TypeName ("adjointSpalartAllmaras")
Runtime type information.
tmp< volSymmTensorField > devReff () const virtual
Return the effective stress tensor including the laminar stress.
Implements adjointRASModel.
Definition at line 696 of file adjointSpalartAllmaras.C.
tmp< fvVectorMatrix > divDevReff (volVectorField & U) const virtual
Return the diffusion term for the momentum equation.
Implements adjointRASModel.
Definition at line 714 of file adjointSpalartAllmaras.C.
tmp< volVectorField > adjointMeanFlowSource () virtual
Source terms to the adjoint momentum equation due to the differentiation of the turbulence model.
Implements adjointRASModel.
Definition at line 727 of file adjointSpalartAllmaras.C.
tmp< volScalarField > nutJacobianTMVar1 () const virtual
Jacobian of nut wrt the first turbulence model variable.
Needed for objective functions that depend on nut. Defaults to zero
Reimplemented from adjointRASModel.
Definition at line 737 of file adjointSpalartAllmaras.C.
tmp< scalarField > diffusionCoeffVar1 (label patchI) const virtual
Diffusion coefficient of the first primal and adjoint turbulence model equation. Needed for some adjoint BCs. Defaults to zero.
Reimplemented from adjointRASModel.
Definition at line 747 of file adjointSpalartAllmaras.C.
const boundaryVectorField & adjointMomentumBCSource () const virtual
Source for the outlet adjoint momentum BC coming from differentiating the turbulence model.
Implements adjointRASModel.
Definition at line 765 of file adjointSpalartAllmaras.C.
const boundaryVectorField & wallShapeSensitivities () virtual
Sensitivity terms for shape optimisation, emerging from.
the turbulence model differentiation. Misses dxdb, to be added by the classes assembling the sensitivities
Implements adjointRASModel.
Definition at line 772 of file adjointSpalartAllmaras.C.
References adjointRASModel::adjMomentumBCSourcePtr_.
const boundaryVectorField & wallFloCoSensitivities () virtual
Sensitivity terms for flow control, emerging from the.
turbulence model differentiation
Implements adjointRASModel.
Definition at line 795 of file adjointSpalartAllmaras.C.
tmp< volScalarField > distanceSensitivities () virtual
Sensitivity terms resulting from the differentiation of the distance field. Misses dxdb, to be added by the classes assembling the sensitivities.
Implements adjointRASModel.
Definition at line 813 of file adjointSpalartAllmaras.C.
tmp< volTensorField > FISensitivityTerm () virtual
Term contributing to the computation of FI-based sensitivities.
Misses grad(dxdb), to be added by the assembling the sensitivities
Implements adjointRASModel.
Definition at line 932 of file adjointSpalartAllmaras.C.
void nullify () virtual
Nullify all adjoint turbulence model fields and their old times.
Implements adjointRASModel.
Definition at line 1007 of file adjointSpalartAllmaras.C.
void correct () virtual
Solve the adjoint turbulence equations.
Reimplemented from adjointRASModel.
Definition at line 1013 of file adjointSpalartAllmaras.C.
References adjointSpalartAllmaras::nuaTilda(), and variablesSet::nullifyField().
bool read () virtual
Read adjointRASProperties dictionary.
Reimplemented from adjointRASModel.
Definition at line 1073 of file adjointSpalartAllmaras.C.
Member Data Documentation
dimensionedScalar sigmaNut_ protected
Definition at line 106 of file adjointSpalartAllmaras.H.
dimensionedScalar kappa_ protected
Definition at line 107 of file adjointSpalartAllmaras.H.
dimensionedScalar Cb1_ protected
Definition at line 109 of file adjointSpalartAllmaras.H.
Referenced by adjointSpalartAllmaras::dnut_dNuTilda().
dimensionedScalar Cb2_ protected
Definition at line 110 of file adjointSpalartAllmaras.H.
dimensionedScalar Cw1_ protected
Definition at line 111 of file adjointSpalartAllmaras.H.
Referenced by adjointSpalartAllmaras::dP_dNuTilda().
dimensionedScalar Cw2_ protected
Definition at line 112 of file adjointSpalartAllmaras.H.
Referenced by adjointSpalartAllmaras::DnuTildaEff().
dimensionedScalar Cw3_ protected
Definition at line 113 of file adjointSpalartAllmaras.H.
Referenced by adjointSpalartAllmaras::DnuTildaEff().
dimensionedScalar Cv1_ protected
Definition at line 114 of file adjointSpalartAllmaras.H.
Referenced by adjointSpalartAllmaras::fv2().
dimensionedScalar Cs_ protected
Definition at line 115 of file adjointSpalartAllmaras.H.
bool limitAdjointProduction_ protected
Whether to limit the adjoint production term to enhance stability.
Definition at line 121 of file adjointSpalartAllmaras.H.
const volScalarField& y_ protected
Wall distance.
Note: reference to the distance known by the primal model
Definition at line 131 of file adjointSpalartAllmaras.H.
volScalarField mask_ protected
Field for masking (convergence enhancement)
Definition at line 136 of file adjointSpalartAllmaras.H.
volSymmTensorField symmAdjointProductionU_ protected
Definition at line 141 of file adjointSpalartAllmaras.H.
volScalarField productionDestructionSource_ protected
Definition at line 142 of file adjointSpalartAllmaras.H.
volScalarField Stilda_ protected
Definition at line 143 of file adjointSpalartAllmaras.H.
volScalarField r_ protected
Definition at line 144 of file adjointSpalartAllmaras.H.
Referenced by adjointSpalartAllmaras::DnuTildaEff().
volScalarField fw_ protected
Definition at line 145 of file adjointSpalartAllmaras.H.
volScalarField Cdnut_ protected
Definition at line 146 of file adjointSpalartAllmaras.H.
volTensorField momentumSourceMult_ protected
Definition at line 147 of file adjointSpalartAllmaras.H.
volTensorField gradU_ protected
Definition at line 148 of file adjointSpalartAllmaras.H.
volVectorField gradNuTilda_ protected
Definition at line 149 of file adjointSpalartAllmaras.H.
dimensionedScalar minStilda_ protected
Definition at line 152 of file adjointSpalartAllmaras.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointRAS/adjointSpalartAllmaras/adjointSpalartAllmaras.H
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointRAS/adjointSpalartAllmaras/adjointSpalartAllmaras.C