OpenFOAM: distributionModel Class Reference
distributionModel Class Reference abstract
A library of runtime-selectable distribution models.
Public Member Functions
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, distributionModel, dictionary,(const dictionary &dict, Random &rndGen),(dict, rndGen))
Declare runtime constructor selection table.
distributionModel (const word &name, const dictionary &dict, Random &rndGen)
Construct from dictionary.
distributionModel (const distributionModel &p)
Construct copy.
virtual autoPtr
< distributionModel > clone () const =0
Construct and return a clone.
virtual ~distributionModel ()
Destructor.
virtual scalar sample () const =0
Sample the distributionModel.
virtual scalar minValue () const =0
Return the minimum value.
virtual scalar maxValue () const =0
Return the maximum value.
virtual scalar meanValue () const =0
Return the maximum value.
Static Public Member Functions
static autoPtr< distributionModel > New (const dictionary &dict, Random &rndGen)
Selector.
Protected Member Functions
virtual void check () const
Check that the distribution model is valid.
Protected Attributes
const dictionary distributionModelDict_
Coefficients dictionary.
Random & rndGen_
Reference to the random number generator.
Detailed Description
A library of runtime-selectable distribution models.
Returns a sampled value given the expectation (nu) and variance (sigma^2)
Current distribution models include:
exponential
fixedValue
general
multi-normal
normal
Rosin-Rammler
Mass-based Rosin-Rammler
uniform
The distributionModel is tabulated in equidistant nPoints, in an interval. These values are integrated to obtain the cumulated distribution model, which is then used to change the distribution from unifrom to the actual distributionModel.
Source files
distributionModel.H
distributionModel.C
distributionModelNew.C
Definition at line 66 of file distributionModel.H.
Constructor & Destructor Documentation
distributionModel (const word & name, const dictionary & dict, Random & rndGen)
Construct from dictionary.
Definition at line 58 of file distributionModel.C.
distributionModel (const distributionModel & p)
Construct copy.
Definition at line 70 of file distributionModel.C.
~distributionModel () virtual
Destructor.
Definition at line 81 of file distributionModel.C.
Member Function Documentation
void check () const protected virtual
Check that the distribution model is valid.
Definition at line 34 of file distributionModel.C.
TypeName ("distributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , distributionModel , dictionary , (const dictionary &dict, Random &rndGen) , (dict, rndGen))
Declare runtime constructor selection table.
virtual autoPtr<distributionModel> clone () const pure virtual
Construct and return a clone.
Implemented in binned, general, massRosinRammler, multiNormal, normal, RosinRammler, exponential, uniform, and fixedValue.
Foam::autoPtr< Foam::distributionModel > New (const dictionary & dict, Random & rndGen) static
Selector.
Definition at line 27 of file distributionModelNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, rndGen, and dictionary::subOrEmptyDict().
virtual scalar sample () const pure virtual
Sample the distributionModel.
Implemented in general, binned, massRosinRammler, multiNormal, normal, RosinRammler, exponential, uniform, and fixedValue.
virtual scalar minValue () const pure virtual
Return the minimum value.
Implemented in general, binned, massRosinRammler, multiNormal, normal, RosinRammler, exponential, uniform, and fixedValue.
virtual scalar maxValue () const pure virtual
Return the maximum value.
Implemented in general, binned, massRosinRammler, multiNormal, normal, RosinRammler, exponential, uniform, and fixedValue.
virtual scalar meanValue () const pure virtual
Return the maximum value.
Implemented in general, binned, massRosinRammler, multiNormal, normal, RosinRammler, exponential, uniform, and fixedValue.
Member Data Documentation
const dictionary distributionModelDict_ protected
Coefficients dictionary.
Definition at line 76 of file distributionModel.H.
Random& rndGen_ protected
Reference to the random number generator.
Definition at line 81 of file distributionModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/distributionModels/distributionModel/distributionModel.H
src/lagrangian/distributionModels/distributionModel/distributionModel.C
src/lagrangian/distributionModels/distributionModel/distributionModelNew.C