OpenFOAM: SolverPerformance< Type > Class Template Reference
SolverPerformance< Type > Class Template Reference
SolverPerformance is the class returned by the LduMatrix solver containing performance statistics.
Public Member Functions
ClassName ("SolverPerformance")
SolverPerformance ()
SolverPerformance (const word &solverName, const word &fieldName, const Type &iRes=pTraits< Type >::zero, const Type &fRes=pTraits< Type >::zero, const labelType &nIter=pTraits< labelType >::zero, const bool converged=false, const bool singular=false)
const word & solverName () const
Return solver name.
word & solverName ()
Return solver name.
const word & fieldName () const
Return field name.
const Type & initialResidual () const
Return initial residual.
Type & initialResidual ()
Return initial residual.
const Type & finalResidual () const
Return final residual.
Type & finalResidual ()
Return final residual.
const labelType & nIterations () const
Return number of iterations.
labelType & nIterations ()
Return number of iterations.
bool converged () const
Has the solver converged?
bool singular () const
Is the matrix singular?
bool checkConvergence (const Type &tolerance, const Type &relTolerance)
Check, store and return convergence.
bool checkSingularity (const Type &residual)
Singularity test.
void print (Ostream &os) const
Print summary of solver performance to the given stream.
void replace (const label cmpt, const SolverPerformance< typename pTraits< Type >::cmptType > &sp)
Replace component based on the minimal SolverPerformance.
SolverPerformance< typename
pTraits< Type >::cmptType > max ()
Return the summary maximum of SolverPerformance<Type>
bool operator!= (const SolverPerformance< Type > &) const
template<>
Foam::SolverPerformance
< Foam::scalar > max ()
template<>
SolverPerformance< scalar > max ()
Static Public Attributes
static const scalar great_
Large Type for the use in solvers.
static const scalar small_
Small Type for the use in solvers.
static const scalar vsmall_
Very small Type for the use in solvers.
Friends
SolverPerformance< Type > Foam::max (const SolverPerformance< Type > &, const SolverPerformance< Type > &)
Return the element-wise maximum of two SolverPerformance<Type>s.
Istream & operator>> (Istream &, SolverPerformance< Type > &)
Ostream & operator (Ostream &, const SolverPerformance< Type > &)
Detailed Description
template<class Type>
class Foam::SolverPerformance< Type >
SolverPerformance is the class returned by the LduMatrix solver containing performance statistics.
Source files
SolverPerformance.H
SolverPerformance.C
Definition at line 47 of file SolverPerformance.H.
Constructor & Destructor Documentation
SolverPerformance () inline
Definition at line 117 of file SolverPerformance.H.
SolverPerformance (const word & solverName, const word & fieldName, const Type & iRes = pTraits<Type>::zero, const Type & fRes = pTraits<Type>::zero, const labelType & nIter = pTraits<labelType>::zero, const bool converged = false, const bool singular = false) inline
Definition at line 128 of file SolverPerformance.H.
Member Function Documentation
ClassName ("SolverPerformance< Type >")
const word& solverName () const inline
Return solver name.
Definition at line 153 of file SolverPerformance.H.
word& solverName () inline
Return solver name.
Definition at line 161 of file SolverPerformance.H.
const word& fieldName () const inline
Return field name.
Definition at line 170 of file SolverPerformance.H.
const Type& initialResidual () const inline
Return initial residual.
Definition at line 179 of file SolverPerformance.H.
Referenced by GAMGSolver::solve().
Type& initialResidual () inline
Return initial residual.
Definition at line 187 of file SolverPerformance.H.
const Type& finalResidual () const inline
Return final residual.
Definition at line 196 of file SolverPerformance.H.
Referenced by GAMGSolver::solve().
Type& finalResidual () inline
Return final residual.
Definition at line 204 of file SolverPerformance.H.
const labelType& nIterations () const inline
Return number of iterations.
Definition at line 213 of file SolverPerformance.H.
Referenced by GAMGSolver::solve().
labelType& nIterations () inline
Return number of iterations.
Definition at line 221 of file SolverPerformance.H.
bool converged () const inline
Has the solver converged?
Definition at line 230 of file SolverPerformance.H.
bool singular () const
Is the matrix singular?
Definition at line 43 of file SolverPerformance.C.
bool checkConvergence (const Type & tolerance, const Type & relTolerance)
Check, store and return convergence.
Definition at line 56 of file SolverPerformance.C.
Referenced by GAMGSolver::solve().
bool checkSingularity (const Type & residual)
Singularity test.
Definition at line 28 of file SolverPerformance.C.
References Foam::component().
void print (Ostream & os) const
Print summary of solver performance to the given stream.
Definition at line 92 of file SolverPerformance.C.
Referenced by GAMGSolver::solve().
void replace (const label cmpt, const SolverPerformance< typename pTraits< Type >::cmptType > & sp)
Replace component based on the minimal SolverPerformance.
Definition at line 126 of file SolverPerformance.C.
Foam::SolverPerformance< typename Foam::pTraits< Type >::cmptType > max ()
Return the summary maximum of SolverPerformance<Type>
Effectively it will mostly return solverPerformanceScalar
Definition at line 140 of file SolverPerformance.C.
bool operator!= (const SolverPerformance< Type > & sp) const
Definition at line 157 of file SolverPerformance.C.
Foam::SolverPerformance< Foam::scalar > max ()
Definition at line 36 of file solverPerformance.C.
SolverPerformance< scalar > max ()
Friends And Related Function Documentation
SolverPerformance<Type> Foam::max (const SolverPerformance< Type > & , const SolverPerformance< Type > &) friend
Return the element-wise maximum of two SolverPerformance<Type>s.
Istream& operator>> (Istream & , SolverPerformance< Type > &) friend
Ostream& operator (Ostream & , const SolverPerformance< Type > &) friend
Member Data Documentation
const scalar great_ static
Large Type for the use in solvers.
Definition at line 102 of file SolverPerformance.H.
const scalar small_ static
Small Type for the use in solvers.
Definition at line 107 of file SolverPerformance.H.
const scalar vsmall_ static
Very small Type for the use in solvers.
Definition at line 112 of file SolverPerformance.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/SolverPerformance.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/SolverPerformance.C
src/OpenFOAM/matrices/LduMatrix/LduMatrix/solverPerformance.C