OpenFOAM: cellFeatures Class Reference
cellFeatures Class Reference
Cell analysis class.
Public Member Functions
cellFeatures (const primitiveMesh &, const scalar minCos, const label celli)
Construct from cell in mesh.
~cellFeatures ()
Destructor.
const labelHashSet & featureEdge () const
const faceList & faces () const
const List< DynamicList< label > > & faceMap () const
New to old faceMap. Guaranteed to be shrunk.
bool isFeatureEdge (const label edgeI) const
Is edge a feature edge (uniquely determined since on cell.
bool isFeaturePoint (const label edge0, const label edge1) const
Are two edges connected at feature point?
bool isFeatureVertex (const label facei, const label vertI) const
Is vertexI on facei used by two edges that form feature.
Detailed Description
Cell analysis class.
Constructs feature edges and feature points, which are edges/points with and angle > given specification. Can be asked for 'superFaces' which can be used to see if a cell is a 'splitHex'.
Source files
cellFeatures.H
cellFeatures.C
Definition at line 59 of file cellFeatures.H.
Constructor & Destructor Documentation
cellFeatures (const primitiveMesh & mesh, const scalar minCos, const label celli)
Construct from cell in mesh.
Definition at line 366 of file cellFeatures.C.
~cellFeatures ()
Destructor.
Definition at line 396 of file cellFeatures.C.
Member Function Documentation
const labelHashSet& featureEdge () const inline
Definition at line 149 of file cellFeatures.H.
Referenced by cellFeatures::faceMap().
const faceList& faces () const inline
Definition at line 154 of file cellFeatures.H.
const List<DynamicList<label> >& faceMap () const inline
New to old faceMap. Guaranteed to be shrunk.
Definition at line 166 of file cellFeatures.H.
References cellFeatures::featureEdge(), and HashTable< T, Key, Hash >::found().
bool isFeatureEdge (const label edgeI) const inline
Is edge a feature edge (uniquely determined since on cell.
only two faces sharing edge)
Definition at line 183 of file cellFeatures.H.
bool isFeaturePoint (const label edge0, const label edge1) const
Are two edges connected at feature point?
Is local to face since point might be seen as feature point from one face but not from another.
Definition at line 404 of file cellFeatures.C.
References Foam::deleteDemandDrivenData().
bool isFeatureVertex (const label facei, const label vertI) const
Is vertexI on facei used by two edges that form feature.
point
Definition at line 468 of file cellFeatures.C.
The documentation for this class was generated from the following files:
src/meshTools/cellFeatures/cellFeatures.H
src/meshTools/cellFeatures/cellFeatures.C