OpenFOAM: AMIMethod< SourcePatch, TargetPatch > Class Template Reference
AMIMethod< SourcePatch, TargetPatch > Class Template Reference abstract
Base class for Arbitrary Mesh Interface (AMI) methods.
Public Member Functions
TypeName ("AMIMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, AMIMethod, components,(const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch),(srcPatch, tgtPatch, triMode, reverseTarget, requireMatch))
Declare runtime constructor selection table.
AMIMethod (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Construct from components.
virtual ~AMIMethod ()=default
Destructor.
const labelList & srcNonOverlap () const
Labels of faces that are not overlapped by any target faces.
virtual bool conformal () const
Flag to indicate that interpolation patches are conformal.
const List< scalar > & srcMagSf () const
Return const access to source patch face areas.
List< scalar > & srcMagSf ()
Return access to source patch face areas.
const List< scalar > & tgtMagSf () const
Return const access to target patch face areas.
List< scalar > & tgtMagSf ()
Return access to target patch face areas.
virtual void calculate (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label srcFacei=-1, label tgtFacei=-1)=0
Update addressing and weights.
virtual void setMagSf (const TargetPatch &tgtPatch, const mapDistribute &map, scalarList &srcMagSf, scalarList &tgtMagSf) const =0
Set the face areas for parallel runs.
virtual void normaliseWeights (const bool verbose, AMIInterpolation< SourcePatch, TargetPatch > &inter)=0
Normalise the weight. Can optionally subset addressing (e.g. for mapNearest)
Static Public Member Functions
static autoPtr< AMIMethod > New (const word &methodName, const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch)
Selector.
Protected Types
typedef treeDataPrimitivePatch
< TargetPatch > treeType
Local typedef to octree tree-type.
Protected Member Functions
void checkPatches () const
Check AMI patch coupling.
bool initialise (labelListList &srcAddress, scalarListList &srcWeights, labelListList &tgtAddress, scalarListList &tgtWeights, label &srcFacei, label &tgtFacei)
Initialise and return true if all ok.
void writeIntersectionOBJ (const scalar area, const face &f1, const face &f2, const pointField &f1Points, const pointField &f2Points) const
Write triangle intersection to OBJ file.
void resetTree ()
Reset the octree for the target patch face search.
label findTargetFace (const label srcFacei) const
Find face on target patch that overlaps source face.
void appendNbrFaces (const label facei, const TargetPatch &patch, const DynamicList< label > &visitedFaces, DynamicList< label > &faceIDs) const
Add faces neighbouring facei to the ID list.
template<class PatchType >
void triangulatePatch (const PatchType &patch, List< DynamicList< face >> &tris, List< scalar > &magSf) const
Helper function to decompose a patch.
Protected Attributes
const SourcePatch & srcPatch_
Reference to source patch.
const TargetPatch & tgtPatch_
Reference to target patch.
const bool reverseTarget_
Flag to indicate that the two patches are co-directional and that the orientation of the target patch should be reversed.
const bool requireMatch_
Flag to indicate that the two patches must be matched/an overlap exists between them.
List< scalar > srcMagSf_
Source face areas.
List< scalar > tgtMagSf_
Target face areas.
labelList srcNonOverlap_
Labels of faces that are not overlapped by any target faces (should be empty for correct functioning)
autoPtr< indexedOctree
< treeType > > treePtr_
Octree used to find face seeds.
const
faceAreaIntersect::triangulationMode triMode_
Face triangulation mode.
Detailed Description
template<class SourcePatch, class TargetPatch>
class Foam::AMIMethod< SourcePatch, TargetPatch >
Base class for Arbitrary Mesh Interface (AMI) methods.
Source files
AMIMethod.H
AMIMethod.C
Definition at line 56 of file AMIMethod.H.
Member Typedef Documentation
typedef treeDataPrimitivePatch<TargetPatch> treeType protected
Local typedef to octree tree-type.
Definition at line 79 of file AMIMethod.H.
Constructor & Destructor Documentation
AMIMethod (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const faceAreaIntersect::triangulationMode & triMode, const bool reverseTarget, const bool requireMatch)
Construct from components.
Definition at line 360 of file AMIMethod.C.
virtual ~AMIMethod () virtual default
Destructor.
Member Function Documentation
void checkPatches () const protected
Check AMI patch coupling.
Definition at line 30 of file AMIMethod.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::nl, Foam::Pout, and WarningInFunction.
bool initialise (labelListList & srcAddress, scalarListList & srcWeights, labelListList & tgtAddress, scalarListList & tgtWeights, label & srcFacei, label & tgtFacei) protected
Initialise and return true if all ok.
Definition at line 68 of file AMIMethod.C.
void writeIntersectionOBJ (const scalar area, const face & f1, const face & f2, const pointField & f1Points, const pointField & f2Points) const protected
Write triangle intersection to OBJ file.
Definition at line 143 of file AMIMethod.C.
void resetTree () protected
Reset the octree for the target patch face search.
Definition at line 194 of file AMIMethod.C.
Foam::label findTargetFace (const label srcFacei) const protected
Find face on target patch that overlaps source face.
Definition at line 226 of file AMIMethod.C.
void appendNbrFaces (const label facei, const TargetPatch & patch, const DynamicList< label > & visitedFaces, DynamicList< label > & faceIDs) const protected
Add faces neighbouring facei to the ID list.
Definition at line 257 of file AMIMethod.C.
void triangulatePatch (const PatchType & patch, List< DynamicList< face >> & tris, List< scalar > & magSf) const protected
Helper function to decompose a patch.
Definition at line 313 of file AMIMethod.C.
TypeName ("AMIMethod< SourcePatch, TargetPatch >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , AMIMethod< SourcePatch, TargetPatch > , components , (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool reverseTarget, const bool requireMatch) , (srcPatch, tgtPatch, triMode, reverseTarget, requireMatch))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::AMIMethod< SourcePatch, TargetPatch > > New (const word & methodName, const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const faceAreaIntersect::triangulationMode & triMode, const bool reverseTarget, const bool requireMatch) static
Selector.
Definition at line 27 of file AMIMethodNew.C.
References DebugInfo, Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
const Foam::labelList & srcNonOverlap () const inline
Labels of faces that are not overlapped by any target faces.
Note: this should be empty for correct functioning
Definition at line 55 of file AMIMethodI.H.
bool conformal () const virtual
Flag to indicate that interpolation patches are conformal.
Reimplemented in partialFaceAreaWeightAMI< SourcePatch, TargetPatch >.
Definition at line 385 of file AMIMethod.C.
const Foam::List< Foam::scalar > & srcMagSf () const inline
Return const access to source patch face areas.
Definition at line 23 of file AMIMethodI.H.
Foam::List< Foam::scalar > & srcMagSf () inline
Return access to source patch face areas.
Definition at line 31 of file AMIMethodI.H.
const Foam::List< Foam::scalar > & tgtMagSf () const inline
Return const access to target patch face areas.
Definition at line 39 of file AMIMethodI.H.
Foam::List< Foam::scalar > & tgtMagSf () inline
Return access to target patch face areas.
Definition at line 47 of file AMIMethodI.H.
virtual void calculate (labelListList & srcAddress, scalarListList & srcWeights, labelListList & tgtAddress, scalarListList & tgtWeights, label srcFacei = -1, label tgtFacei = -1) pure virtual
Update addressing and weights.
Implemented in faceAreaWeightAMI< SourcePatch, TargetPatch >, mapNearestAMI< SourcePatch, TargetPatch >, directAMI< SourcePatch, TargetPatch >, and partialFaceAreaWeightAMI< SourcePatch, TargetPatch >.
virtual void setMagSf (const TargetPatch & tgtPatch, const mapDistribute & map, scalarList & srcMagSf, scalarList & tgtMagSf) const pure virtual
Set the face areas for parallel runs.
Implemented in faceAreaWeightAMI< SourcePatch, TargetPatch >, mapNearestAMI< SourcePatch, TargetPatch >, directAMI< SourcePatch, TargetPatch >, and partialFaceAreaWeightAMI< SourcePatch, TargetPatch >.
virtual void normaliseWeights (const bool verbose, AMIInterpolation< SourcePatch, TargetPatch > & inter) pure virtual
Normalise the weight. Can optionally subset addressing (e.g. for mapNearest)
Implemented in faceAreaWeightAMI< SourcePatch, TargetPatch >, mapNearestAMI< SourcePatch, TargetPatch >, and directAMI< SourcePatch, TargetPatch >.
Member Data Documentation
const SourcePatch& srcPatch_ protected
Reference to source patch.
Definition at line 87 of file AMIMethod.H.
const TargetPatch& tgtPatch_ protected
Reference to target patch.
Definition at line 92 of file AMIMethod.H.
const bool reverseTarget_ protected
Flag to indicate that the two patches are co-directional and that the orientation of the target patch should be reversed.
Definition at line 98 of file AMIMethod.H.
const bool requireMatch_ protected
Flag to indicate that the two patches must be matched/an overlap exists between them.
Definition at line 104 of file AMIMethod.H.
List<scalar> srcMagSf_ protected
Source face areas.
Definition at line 109 of file AMIMethod.H.
List<scalar> tgtMagSf_ protected
Target face areas.
Definition at line 114 of file AMIMethod.H.
labelList srcNonOverlap_ protected
Labels of faces that are not overlapped by any target faces (should be empty for correct functioning)
Definition at line 120 of file AMIMethod.H.
autoPtr<indexedOctree<treeType> > treePtr_ protected
Octree used to find face seeds.
Definition at line 125 of file AMIMethod.H.
const faceAreaIntersect::triangulationMode triMode_ protected
Face triangulation mode.
Definition at line 130 of file AMIMethod.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethod.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethod.C
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethodI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIMethod/AMIMethod/AMIMethodNew.C