OpenFOAM: HerschelBulkley Class Reference
HerschelBulkley Class Reference
Herschel-Bulkley non-Newtonian viscosity model.
Public Member Functions
TypeName ("HerschelBulkley")
Runtime type information.
HerschelBulkley (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~HerschelBulkley ()=default
Destructor.
virtual tmp< volScalarField > nu () const
Return the laminar viscosity.
virtual tmp< scalarField > nu (const label patchi) const
Return the laminar viscosity for patch.
virtual void correct ()
Correct the laminar viscosity.
virtual bool read (const dictionary &viscosityProperties)
Read transportProperties dictionary.
Public Member Functions inherited from viscosityModel
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
viscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~viscosityModel ()=default
Destructor.
const dictionary & viscosityProperties () const
Return the phase transport properties dictionary.
tmp< volScalarField > strainRate () const
Return the strain rate.
Protected Member Functions
tmp< volScalarField > calcNu () const
Calculate and return the laminar viscosity.
Protected Member Functions inherited from viscosityModel
viscosityModel (const viscosityModel &)=delete
No copy construct.
void operator= (const viscosityModel &)=delete
No copy assignment.
Protected Attributes
volScalarField nu_
Protected Attributes inherited from viscosityModel
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Additional Inherited Members
Static Public Member Functions inherited from viscosityModel
static autoPtr< viscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Return a reference to the selected viscosity model.
Detailed Description
Herschel-Bulkley non-Newtonian viscosity model.
Source files
HerschelBulkley.H
HerschelBulkley.C
Definition at line 51 of file HerschelBulkley.H.
Constructor & Destructor Documentation
HerschelBulkley (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Construct from components.
Definition at line 69 of file HerschelBulkley.C.
virtual ~HerschelBulkley () virtual default
Destructor.
Member Function Documentation
Foam::tmp< Foam::volScalarField > calcNu () const protected
Calculate and return the laminar viscosity.
Definition at line 47 of file HerschelBulkley.C.
Referenced by HerschelBulkley::nu().
TypeName ("HerschelBulkley")
Runtime type information.
virtual tmp<volScalarField> nu () const inline virtual
Return the laminar viscosity.
Implements viscosityModel.
Definition at line 113 of file HerschelBulkley.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), and HerschelBulkley::nu_.
virtual tmp<scalarField> nu (const label patchi) const inline virtual
Return the laminar viscosity for patch.
Implements viscosityModel.
Definition at line 121 of file HerschelBulkley.H.
References HerschelBulkley::calcNu(), and HerschelBulkley::nu_.
virtual void correct () inline virtual
Correct the laminar viscosity.
Implements viscosityModel.
Definition at line 129 of file HerschelBulkley.H.
bool read (const dictionary & viscosityProperties) virtual
Read transportProperties dictionary.
Implements viscosityModel.
Definition at line 103 of file HerschelBulkley.C.
Member Data Documentation
volScalarField nu_ protected
Definition at line 69 of file HerschelBulkley.H.
Referenced by HerschelBulkley::nu().
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/HerschelBulkley/HerschelBulkley.H
src/transportModels/incompressible/viscosityModels/HerschelBulkley/HerschelBulkley.C