OpenFOAM: ddtScheme< Type > Class Template Reference
ddtScheme< Type > Class Template Reference abstract
Time schemes
Abstract base class for ddt schemes.
Public Types
typedef GeometricField
< typename flux< Type >::type,
fvsPatchField, surfaceMesh > fluxFieldType
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, ddtScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
ddtScheme (const fvMesh &mesh)
Construct from mesh.
ddtScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~ddtScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcDdt (const dimensioned< Type > &)=0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > &)
virtual tmp< fvMatrix< Type > > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmDdt (const volScalarField &alpha, const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &vf)=0
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeffExperimental (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi, const fluxFieldType &phiCorr, const volScalarField &rho)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > &rhoU, const fluxFieldType &phi, const volScalarField &rho)
virtual tmp< fluxFieldType > fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)=0
virtual tmp< fluxFieldType > fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)=0
virtual tmp< fluxFieldType > fvcDdtUfCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const GeometricField< Type, fvsPatchField, surfaceMesh > &Uf)=0
virtual tmp< fluxFieldType > fvcDdtPhiCorr (const volScalarField &rho, const GeometricField< Type, fvPatchField, volMesh > &U, const fluxFieldType &phi)=0
virtual tmp< surfaceScalarField > meshPhi (const GeometricField< Type, fvPatchField, volMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from ddtSchemeBase
ddtSchemeBase ()
ddtSchemeBase ()
Static Public Member Functions
static tmp< ddtScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new ddtScheme created on freestore.
Protected Member Functions
ddtScheme (const ddtScheme &)=delete
No copy construct.
void operator= (const ddtScheme &)=delete
No copy assignment.
Protected Attributes
const fvMesh & mesh_
scalar ddtPhiCoeff_
Input for fvcDdtPhiCoeff.
Additional Inherited Members
Static Public Attributes inherited from ddtSchemeBase
static bool experimentalDdtCorr
Flag to use experimental ddtCorr from org version Default is off for backwards compatibility.
Detailed Description
template<class Type>
class Foam::fv::ddtScheme< Type >
Abstract base class for ddt schemes.
Source files
ddtScheme.H
ddtScheme.C
Definition at line 81 of file ddtScheme.H.
Member Typedef Documentation
typedef GeometricField< typename flux<Type>::type, fvsPatchField, surfaceMesh > fluxFieldType
Definition at line 247 of file ddtScheme.H.
Constructor & Destructor Documentation
ddtScheme (const ddtScheme< Type > &) protected delete
No copy construct.
ddtScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 140 of file ddtScheme.H.
ddtScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 149 of file ddtScheme.H.
virtual ~ddtScheme () virtual default
Destructor.
Member Function Documentation
void operator= (const ddtScheme< Type > &) protected delete
No copy assignment.
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , ddtScheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< ddtScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new ddtScheme created on freestore.
Definition at line 43 of file ddtScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by Foam::fvc::ddt(), and Foam::fvm::ddt().
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 179 of file ddtScheme.H.
Referenced by EulerDdtScheme< Type >::EulerDdtScheme(), and steadyStateDdtScheme< Type >::steadyStateDdtScheme().
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const dimensioned< Type > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDdt (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Definition at line 85 of file ddtScheme.C.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > fvcDdt (const GeometricField< Type, fvsPatchField, surfaceMesh > & sf) virtual
Reimplemented in localEulerDdtScheme< Type >, and EulerDdtScheme< Type >.
Definition at line 121 of file ddtScheme.C.
virtual tmp<fvMatrix<Type> > fvmDdt (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<fvMatrix<Type> > fvmDdt (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<fvMatrix<Type> > fvmDdt (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
tmp< fvMatrix< Type > > fvmDdt (const volScalarField & alpha, const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Definition at line 102 of file ddtScheme.C.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi, const fluxFieldType & phiCorr)
Definition at line 137 of file ddtScheme.C.
tmp< surfaceScalarField > fvcDdtPhiCoeffExperimental (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi, const fluxFieldType & phiCorr)
Definition at line 211 of file ddtScheme.C.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi, const fluxFieldType & phiCorr, const volScalarField & rho)
Definition at line 292 of file ddtScheme.C.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi)
Definition at line 318 of file ddtScheme.C.
tmp< surfaceScalarField > fvcDdtPhiCoeff (const GeometricField< Type, fvPatchField, volMesh > & rhoU, const fluxFieldType & phi, const volScalarField & rho)
Definition at line 348 of file ddtScheme.C.
virtual tmp<fluxFieldType> fvcDdtUfCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<fluxFieldType> fvcDdtPhiCorr (const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<fluxFieldType> fvcDdtUfCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const GeometricField< Type, fvsPatchField, surfaceMesh > & Uf) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<fluxFieldType> fvcDdtPhiCorr (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & U, const fluxFieldType & phi) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
virtual tmp<surfaceScalarField> meshPhi (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in CrankNicolsonDdtScheme< Type >, localEulerDdtScheme< Type >, SLTSDdtScheme< Type >, backwardDdtScheme< Type >, CoEulerDdtScheme< Type >, boundedDdtScheme< Type >, EulerDdtScheme< Type >, and steadyStateDdtScheme< Type >.
Member Data Documentation
const fvMesh& mesh_ protected
Definition at line 91 of file ddtScheme.H.
scalar ddtPhiCoeff_ protected
Input for fvcDdtPhiCoeff.
If set to -1 (default) the code will calculate the coefficient If > 0 the coupling coeff is set to this value
Definition at line 99 of file ddtScheme.H.
Referenced by backwardDdtScheme< Type >::backwardDdtScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/ddtSchemes/ddtScheme/ddtScheme.H
src/finiteVolume/finiteVolume/ddtSchemes/ddtScheme/ddtScheme.C