OpenFOAM: exprDriver Class Reference
exprDriver Class Reference abstract
Base driver for parsing (field) values.
Public Member Functions
TypeName ("exprDriver")
Runtime type information.
exprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
exprDriver (const exprDriver &)
Copy construct.
exprDriver (const dictionary &dict)
Construct from a dictionary.
virtual ~exprDriver ()=default
Destructor.
virtual label size () const
The underlying field size for the expression.
virtual label pointSize () const
The underlying point field size for the expression.
const dictionary & dict () const
The dictionary with all input data/specification.
virtual const exprResult & result () const
Const access to expression result.
virtual exprResult & result ()
Non-const access to expression result.
void clearResult ()
Clear the result.
template<class Type >
tmp< Field< Type > > getResult (bool isPointVal=false)
Return the expression result as a tmp field.
virtual word getResultType () const
The result type as word - same as result().valueType()
int stashedTokenId () const
Get "look-behind" parsing context (internal bookkeeping)
int resetStashedTokenId (int tokenId=0) const
Reset "look-behind" parsing context (mutable operation)
void setDebugging (bool scannerDebug, bool parserDebug)
Set the scanner/parser debug.
void setDebugging (const exprDriver &rhs)
Set the scanner/parser debug to match the input.
void setSearchBehaviour (bool cacheReadFields, bool searchInMemory, bool searchFiles)
Set search behaviour.
void setSearchBehaviour (const exprDriver &rhs)
Set search behaviour to be identical to rhs.
bool debugScanner () const
Read access to scanner debug.
bool debugParser () const
Read access to parser debug.
bool cacheReadFields () const
bool searchInMemory () const
bool searchFiles () const
bool prevIterIsOldTime () const
virtual void clearVariables ()
Clear temporary variables and resets from expression strings.
virtual bool hasVariable (const word &name) const
True if named variable exists.
virtual const exprResult & variable (const word &name) const
Return const-access to the named variable.
void addVariables (const expressions::exprString &expr, bool clear=true)
Add/set string expressions for variables.
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
Add/set string expressions for variables.
template<class T >
void addUniformVariable (const word &name, const T &val)
Add a uniform variable from an outside caller.
template<class T >
bool isLocalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a local variable.
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)=0
Execute the parser.
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return the field.
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return a single value.
void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
Evaluate an expression on a remote and save as the specified named variable.
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
Return a new field with the size()
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
Return a new field with the pointSize()
expressions::exprString readExpression (const word &name)
Read an expression string (with the current dictionary) and do substitutions.
virtual bool readDict (const dictionary &dict)
Read variables, tables etc.
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Read "variables" and assigns to the list of expression strings.
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
Write "variables".
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Static Public Member Functions
static expressions::exprString readExpression (const word &name, const dictionary &dict)
Read an expression string and do substitutions.
static List
< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Read the list of variable strings.
Protected Member Functions
virtual exprResult & variable (const word &name)
Non-const access to the named variable (sub-classes only)
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Fill a random field.
virtual bool update ()
Update things.
virtual void updateSpecialVariables (bool force=false)
Examine current variable values and update stored variables.
virtual exprResult getRemoteResult (const exprDriver &other) const
Get the result from another driver.
void operator= (const exprDriver &)=delete
No copy assignment.
Static Protected Member Functions
template<typename TableType >
static bool readTable (const word &name, const dictionary &dict, HashTable< TableType > &tbl, bool clear=true)
Read an interpolation table.
template<class TableType >
static void writeTable (Ostream &os, const word &name, const HashTable< TableType > &tbl)
Write an interpolation table.
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
The (global) weighted average of a field, with stabilisation.
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
The (global) weighted sum (integral) of a field.
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
Return the location of the min value.
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Return the location of the max value.
Protected Attributes
const dictionary & dict_
The dictionary with all input data/specification.
exprResult result_
The result.
List< expressions::exprString > variableStrings_
Variable definitions, as read from a dictionary.
HashTable< exprResult > variables_
The variables table.
int stashedTokenId_
Internal bookkeeping as "look-behind" parsing context.
bool debugScanner_
Request debugging for scanner.
bool debugParser_
Request debugging for parser.
bool allowShadowing_
Allow variable names to mask field names.
bool prevIterIsOldTime_
Use value of previous iteration when oldTime is requested.
bool cacheReadFields_
Keep fields read from disc in memory.
bool searchInMemory_
Search in registry before looking on disk.
bool searchFiles_
Search on disk (eg, for a standalone application)
Detailed Description
Base driver for parsing (field) values.
Largely based on code and ideas from swak4foam
Properties
Property Description Required Default
variables List of variables for expressions no ()
allowShadowing Allow variables to shadow field names no false
Debug Properties
Property Description Required Default
debugBaseDriver Debug level (int) for base driver no
debugScanner Add debug for scanner no false
debugParser Add debug for parser no false
Source files
exprDriver.H
exprDriverI.H
exprDriver.C
exprDriverFields.C
exprDriverIO.C
exprDriverTemplates.C
Definition at line 108 of file exprDriver.H.
Constructor & Destructor Documentation
exprDriver (bool cacheReadFields = false, bool searchInMemory = true, bool searchFiles = false, const dictionary & dict = dictionary::null) explicit
Null constructor, and null construct with search preferences.
Definition at line 77 of file exprDriver.C.
exprDriver (const exprDriver & rhs)
Copy construct.
Definition at line 108 of file exprDriver.C.
exprDriver (const dictionary & dict) explicit
Construct from a dictionary.
Definition at line 130 of file exprDriver.C.
virtual ~exprDriver () virtual default
Destructor.
Member Function Documentation
bool readTable (const word & name, const dictionary & dict, HashTable< TableType > & tbl, bool clear = true) static protected
Read an interpolation table.
Definition at line 26 of file exprDriverTemplates.C.
References HashTable< T, Key, Hash >::clear(), d, dictionary::found(), dictionary::get(), HashTable< T, Key, Hash >::insert(), and dictionary::lookup().
void writeTable (Ostream & os, const word & name, const HashTable< TableType > & tbl) static protected
Write an interpolation table.
Definition at line 57 of file exprDriverTemplates.C.
Foam::expressions::exprResult & variable (const word & name) inline protected virtual
Non-const access to the named variable (sub-classes only)
Reimplemented in fvExprDriver.
Definition at line 45 of file exprDriverI.H.
References Foam::name().
Referenced by parseDriver::getField().
void fill_random (scalarField & field, label seed = 0, const bool gaussian = false) const protected
Fill a random field.
Parameters
field the field to populate
seed the seed value.
gaussian generate a Gaussian distribution
Definition at line 28 of file exprDriverFields.C.
References Foam::FieldOps::assign().
Referenced by parseDriver::field_rand(), and fvExprDriver::fill_random().
static Type weightedAverage (const scalarField & weights, const Field< Type > & fld) static protected
The (global) weighted average of a field, with stabilisation.
Referenced by parseDriver::pointSize().
static Type weightedSum (const scalarField & weights, const Field< Type > & fld) static protected
The (global) weighted sum (integral) of a field.
Referenced by parseDriver::resultType().
Foam::point getPositionOfMinimum (const scalarField & vals, const pointField & locs) static protected
Return the location of the min value.
Definition at line 48 of file exprDriverFields.C.
Foam::point getPositionOfMaximum (const scalarField & vals, const pointField & locs) static protected
Return the location of the max value.
Definition at line 58 of file exprDriverFields.C.
References Foam::FieldOps::findMinData().
bool update () protected virtual
Update things.
Definition at line 173 of file exprDriver.C.
void updateSpecialVariables (bool force = false) protected virtual
Examine current variable values and update stored variables.
Reimplemented in fvExprDriver.
Definition at line 179 of file exprDriver.C.
Foam::expressions::exprResult getRemoteResult (const exprDriver & other) const protected virtual
Get the result from another driver.
Override to allow mapping
Definition at line 221 of file exprDriver.C.
References NotImplemented.
void operator= (const exprDriver &) protected delete
No copy assignment.
TypeName ("exprDriver")
Runtime type information.
virtual label size () const inline virtual
The underlying field size for the expression.
Reimplemented in fvExprDriver, parseDriver, parseDriver, and parseDriver.
Definition at line 344 of file exprDriver.H.
virtual label pointSize () const inline virtual
The underlying point field size for the expression.
Reimplemented in fvExprDriver, parseDriver, parseDriver, and parseDriver.
Definition at line 352 of file exprDriver.H.
const dictionary& dict () const inline
The dictionary with all input data/specification.
Definition at line 360 of file exprDriver.H.
virtual const exprResult& result () const inline virtual
Const access to expression result.
Definition at line 368 of file exprDriver.H.
Referenced by exprDriver::addVariables(), Foam::stringOps::evaluate(), fvExprDriver::isGlobalVariable(), parseDriver::pointSize(), and parseDriver::setInternalFieldResult().
virtual exprResult& result () inline virtual
Non-const access to expression result.
Definition at line 376 of file exprDriver.H.
void clearResult ()
Clear the result.
Definition at line 167 of file exprDriver.C.
tmp<Field<Type> > getResult (bool isPointVal = false)
Return the expression result as a tmp field.
virtual word getResultType () const inline virtual
The result type as word - same as result().valueType()
Definition at line 395 of file exprDriver.H.
int stashedTokenId () const inline
Get "look-behind" parsing context (internal bookkeeping)
Definition at line 97 of file exprDriverI.H.
int resetStashedTokenId (int tokenId = 0) const inline
Reset "look-behind" parsing context (mutable operation)
Returns
the previous value
Definition at line 104 of file exprDriverI.H.
void setDebugging (bool scannerDebug, bool parserDebug)
Set the scanner/parser debug.
Definition at line 345 of file exprDriver.C.
void setDebugging (const exprDriver & rhs)
Set the scanner/parser debug to match the input.
Definition at line 356 of file exprDriver.C.
void setSearchBehaviour (bool cacheReadFields, bool searchInMemory, bool searchFiles)
Set search behaviour.
Definition at line 366 of file exprDriver.C.
References exprDriver::debugParser_, and exprDriver::debugScanner_.
void setSearchBehaviour (const exprDriver & rhs)
Set search behaviour to be identical to rhs.
Definition at line 384 of file exprDriver.C.
bool debugScanner () const inline
Read access to scanner debug.
Definition at line 444 of file exprDriver.H.
bool debugParser () const inline
Read access to parser debug.
Definition at line 449 of file exprDriver.H.
bool cacheReadFields () const inline
Definition at line 451 of file exprDriver.H.
bool searchInMemory () const inline
Definition at line 452 of file exprDriver.H.
bool searchFiles () const inline
Definition at line 453 of file exprDriver.H.
bool prevIterIsOldTime () const inline
Definition at line 454 of file exprDriver.H.
void clearVariables () virtual
Clear temporary variables and resets from expression strings.
Reimplemented in fvExprDriver.
Definition at line 183 of file exprDriver.C.
bool hasVariable (const word & name) const inline virtual
True if named variable exists.
Reimplemented in fvExprDriver.
Definition at line 25 of file exprDriverI.H.
Referenced by parseDriver::getField().
const Foam::expressions::exprResult & variable (const word & name) const inline virtual
Return const-access to the named variable.
Reimplemented in fvExprDriver.
Definition at line 35 of file exprDriverI.H.
References exprDriver::variables_.
void addVariables (const expressions::exprString & expr, bool clear = true)
Add/set string expressions for variables.
Can include multiple definitions inline
Parameters
clear Remove previously defined variables
Definition at line 231 of file exprDriver.C.
References exprResult::getUniform(), and exprDriver::result().
void addVariables (const UList< expressions::exprString > & list, bool clear = true)
Add/set string expressions for variables.
Can include multiple definitions inline
Parameters
clear Remove previously defined variables
Definition at line 327 of file exprDriver.C.
void addUniformVariable (const word & name, const T & val) inline
Add a uniform variable from an outside caller.
bool isLocalVariable (const word & name, bool isPointVal, label expectedSize = -1) const
Test existence of a local variable.
Definition at line 160 of file exprDriverTemplates.C.
tmp<Field<Type> > getLocalVariable (const word & name, label expectSize, const bool mandatory = true) const
Retrieve local/global variable as a tmp field.
Parameters
name The name of the local/global field
expectSize The size check on the variable, -1 to ignore
mandatory A missing variable is Fatal, or return an invalid tmp
virtual unsigned parse (const std::string & expr, size_t pos = 0, size_t len = std::string::npos) pure virtual
Execute the parser.
The return value currently has no meaning.
Implemented in parseDriver, parseDriver, and parseDriver.
tmp<Field<Type> > evaluate (const expressions::exprString & expr, bool isPointVal = false) inline
Evaluate the expression and return the field.
Type evaluateUniform (const expressions::exprString & expr, bool isPointVal = false) inline
Evaluate the expression and return a single value.
Definition at line 83 of file exprDriverI.H.
void evaluateVariable (const word & varName, const expressions::exprString & expr)
Evaluate the expression and save as the specified named variable.
Definition at line 191 of file exprDriver.C.
void evaluateVariableRemote (string remote, const word & varName, const expressions::exprString & expr) virtual
Evaluate an expression on a remote and save as the specified named variable.
Reimplemented in fvExprDriver.
Definition at line 209 of file exprDriver.C.
tmp<Field<Type> > newField (const Type & val = pTraits< Type >::zero) const
Return a new field with the size()
tmp<Field<Type> > newPointField (const Type & val = pTraits< Type >::zero) const
Return a new field with the pointSize()
Foam::expressions::exprString readExpression (const word & name, const dictionary & dict) static
Read an expression string and do substitutions.
Definition at line 68 of file exprDriverIO.C.
Foam::List< Foam::expressions::exprString > readVariableStrings (const dictionary & dict, const word & name = "variables", bool mandatory = false) static
Read the list of variable strings.
(or initialize with a single string)
Definition at line 89 of file exprDriverIO.C.
References dict.
Foam::expressions::exprString readExpression (const word & name)
Read an expression string (with the current dictionary) and do substitutions.
Definition at line 79 of file exprDriverIO.C.
References dictionary::get().
bool readDict (const dictionary & dict) virtual
Read variables, tables etc.
Also usable for objects not constructed from a dictionary.
Reimplemented in fvExprDriver, and parseDriver.
Definition at line 149 of file exprDriver.C.
Foam::label setVariableStrings (const dictionary & dict, bool mandatory = false)
Read "variables" and assigns to the list of expression strings.
Returns
the number variable strings read.
Definition at line 100 of file exprDriverIO.C.
References Foam::exprTools::getList().
Foam::Ostream & writeVariableStrings (Ostream & os, const word & keyword = "") const
Write "variables".
Definition at line 112 of file exprDriverIO.C.
void addUniformVariable (const word & name, const Type & val) inline
Definition at line 55 of file exprDriverI.H.
References Foam::name().
Foam::tmp<Foam::Field<Type> > evaluate (const expressions::exprString & expr, bool isPointVal)
Definition at line 69 of file exprDriverI.H.
Foam::tmp<Foam::Field<Type> > getResult (bool isPointVal)
Definition at line 141 of file exprDriverTemplates.C.
Foam::tmp<Foam::Field<Type> > newField (const Type & val) const
Definition at line 205 of file exprDriverTemplates.C.
Foam::tmp<Foam::Field<Type> > newPointField (const Type & val) const
Definition at line 216 of file exprDriverTemplates.C.
Member Data Documentation
const dictionary& dict_ protected
The dictionary with all input data/specification.
Definition at line 119 of file exprDriver.H.
exprResult result_ protected
The result.
Definition at line 124 of file exprDriver.H.
List<expressions::exprString> variableStrings_ protected
Variable definitions, as read from a dictionary.
Definition at line 129 of file exprDriver.H.
HashTable<exprResult> variables_ protected
The variables table.
Definition at line 134 of file exprDriver.H.
Referenced by exprDriver::variable(), and fvExprDriver::variable().
int stashedTokenId_ mutable protected
Internal bookkeeping as "look-behind" parsing context.
Definition at line 142 of file exprDriver.H.
bool debugScanner_ protected
Request debugging for scanner.
Definition at line 147 of file exprDriver.H.
Referenced by exprDriver::setSearchBehaviour().
bool debugParser_ protected
Request debugging for parser.
Definition at line 152 of file exprDriver.H.
Referenced by exprDriver::setSearchBehaviour().
bool allowShadowing_ protected
Allow variable names to mask field names.
Definition at line 157 of file exprDriver.H.
bool prevIterIsOldTime_ protected
Use value of previous iteration when oldTime is requested.
Definition at line 162 of file exprDriver.H.
bool cacheReadFields_ protected
Keep fields read from disc in memory.
Definition at line 167 of file exprDriver.H.
bool searchInMemory_ protected
Search in registry before looking on disk.
Definition at line 172 of file exprDriver.H.
bool searchFiles_ protected
Search on disk (eg, for a standalone application)
Definition at line 177 of file exprDriver.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/exprDriver/exprDriver.H
src/OpenFOAM/expressions/exprDriver/exprDriver.C
src/OpenFOAM/expressions/exprDriver/exprDriverFields.C
src/OpenFOAM/expressions/exprDriver/exprDriverI.H
src/OpenFOAM/expressions/exprDriver/exprDriverIO.C
src/OpenFOAM/expressions/exprDriver/exprDriverTemplates.C