OpenFOAM: entry Class Reference
entry Class Reference abstract
A keyword and a list of tokens is an 'entry'.
Public Types
enum inputMode {
MERGE, OVERWRITE, PROTECT, WARN,
ERROR, GLOBAL
}
The input mode options.
Public Member Functions
entry (const keyType &keyword)
Construct from keyword.
entry (const entry &e)
Construct as copy.
virtual autoPtr< entry > clone (const dictionary &parentDict) const =0
Construct on freestore as copy with reference to the.
virtual autoPtr< entry > clone () const
Construct on freestore as copy.
virtual ~entry ()=default
Destructor.
const keyType & keyword () const
Return keyword.
keyType & keyword ()
Return non-const access to keyword.
virtual const fileName & name () const =0
Return the dictionary name.
virtual fileName & name ()=0
Return the dictionary name.
virtual label startLineNumber () const =0
Return line number of first token in dictionary.
virtual label endLineNumber () const =0
Return line number of last token in dictionary.
virtual bool isStream () const
Return true if this entry is a stream.
virtual ITstream & stream () const =0
Return token stream, if entry is a primitive entry.
virtual bool isDict () const
Return true if this entry is a dictionary.
virtual const dictionary * dictPtr () const
Return pointer to dictionary, if entry is a dictionary.
virtual dictionary * dictPtr ()
Return non-const pointer to dictionary, if entry is a dictionary.
virtual const dictionary & dict () const =0
Return dictionary, if entry is a dictionary.
virtual dictionary & dict ()=0
Return non-const access to dictionary, if entry is a dictionary.
void checkITstream (const ITstream &is) const
Check after reading if the input token stream has unconsumed tokens remaining or if there were no tokens in the first place.
template<class T >
T get () const
Get a T from the stream, FatalIOError if the number of tokens is incorrect.
template<class T >
void readEntry (T &val) const
Assign to T val, FatalIOError if the number of tokens is incorrect.
template<class T , class Predicate >
T getCheck (const Predicate &pred) const
Get a T from the stream, FatalIOError if the number of tokens is incorrect.
template<class T , class Predicate >
void readCheck (T &val, const Predicate &pred) const
Assign to T val, FatalIOError if the number of tokens is incorrect.
virtual void write (Ostream &os) const =0
Write.
void operator= (const entry &e)
bool operator== (const entry &e) const
bool operator!= (const entry &e) const
Static Public Member Functions
static bool New (dictionary &parentDict, Istream &is, const inputMode inpMode=inputMode::GLOBAL, const int endChar=0)
Construct from an Istream and insert into the dictionary.
static autoPtr< entry > New (Istream &is)
Construct an entry from Istream.
static void resetInputMode ()
Reset the globalInputMode to merge.
Static Public Attributes
static int disableFunctionEntries
Enable or disable use of function entries and variable expansions.
static inputMode globalInputMode = inputMode::MERGE
The current global input-mode.
Friends
Ostream & operator<< (Ostream &os, const entry &e)
Detailed Description
A keyword and a list of tokens is an 'entry'.
An entry can be read, written and printed, and the types and values of its tokens analysed. An entry is a high-level building block for data description. It is a front-end for the token parser. A list of entries can be used as a set of keyword syntax elements, for example.
Source files
entry.H
entry.C
entryIO.C
Definition at line 63 of file entry.H.
Member Enumeration Documentation
enum inputMode strong
The input mode options.
Enumerator
MERGE
Merge sub-dictionaries when possible.
OVERWRITE
Keep last entry. Silently remove previous ones.
PROTECT
Keep initial entry. Silently ignore subsequent ones.
WARN
Keep initial entry. Warn about subsequent ones.
ERROR
FatalError for duplicate entries.
GLOBAL
Use global value from globalInputMode variable.
Definition at line 74 of file entry.H.
Constructor & Destructor Documentation
entry (const keyType & keyword)
Construct from keyword.
Definition at line 48 of file entry.C.
References entry::globalInputMode, and entry::MERGE.
entry (const entry & e)
Construct as copy.
Definition at line 55 of file entry.C.
virtual ~entry () virtual default
Destructor.
Member Function Documentation
virtual autoPtr<entry> clone (const dictionary & parentDict) const pure virtual
Construct on freestore as copy with reference to the.
dictionary the copy belongs to
Implemented in primitiveEntry, dictionaryEntry, and dictionaryListEntry.
Referenced by dictionary::add(), dictionary::operator+=(), dictionary::operator<<=(), dictionary::operator|=(), and dictionary::set().
Foam::autoPtr< Foam::entry > clone () const virtual
Construct on freestore as copy.
Note: the parent directory is set to dictionary::null
Definition at line 62 of file entry.C.
bool New (dictionary & parentDict, Istream & is, const inputMode inpMode = inputMode::GLOBAL, const int endChar = 0) static
Construct from an Istream and insert into the dictionary.
Parameters
parentDict dictionary to insert into
is the input stream
inpMode the input mode. The default is to use the currently active globalInputMode
endChar the expected end character (eg, a closing brace). The endChar is 0 if no expectations are asserted.
Definition at line 97 of file entryIO.C.
Referenced by inputModeMerge::execute(), inputModeOverwrite::execute(), inputModeWarn::execute(), and inputModeError::execute().
Foam::autoPtr< Foam::entry > New (Istream & is) static
Construct an entry from Istream.
The expected input comprises a keyword followed by a dictionaryEntry or a primitiveEntry.
The dictionaryEntry starts with a '{' left brace and ends with a '}' right brace.
The primitiveEntry ends with a ';' semi-colon.
Example input
*    key1 { ... }   // dictionary input
*    key2 ... ;     // primitive input
*
Returns
The entry read, or nullptr on error.
Definition at line 459 of file entryIO.C.
void resetInputMode () static
Reset the globalInputMode to merge.
Definition at line 40 of file entry.C.
const keyType& keyword () const inline
Return keyword.
Definition at line 221 of file entry.H.
References entry::dictPtr().
Referenced by cellModel::cellModel(), solutionControl::maxTypeResidual(), Foam::operator<<(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::readField().
keyType& keyword () inline
Return non-const access to keyword.
Definition at line 229 of file entry.H.
virtual const fileName& name () const pure virtual
Return the dictionary name.
Implemented in primitiveEntry, and dictionaryEntry.
virtual fileName& name () pure virtual
Return the dictionary name.
Implemented in primitiveEntry, and dictionaryEntry.
virtual label startLineNumber () const pure virtual
Return line number of first token in dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by CodedSource< Type >::read().
virtual label endLineNumber () const pure virtual
Return line number of last token in dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
virtual bool isStream () const inline virtual
Return true if this entry is a stream.
Reimplemented in primitiveEntry.
Definition at line 258 of file entry.H.
References Foam::T(), and Foam::val.
virtual ITstream& stream () const pure virtual
Return token stream, if entry is a primitive entry.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by entry::dictPtr(), dimensionSet::dimensionSet(), entry::isDict(), solutionControl::maxTypeResidual(), Function1< Type >::New(), PatchFunction1< Type >::New(), Foam::blockMeshTools::read(), and expressionEntry::toExprStr().
virtual bool isDict () const inline virtual
Return true if this entry is a dictionary.
Definition at line 272 of file entry.H.
References entry::checkITstream(), entry::stream(), and Foam::val.
Referenced by Foam::getVariableOrDie(), Function1< Type >::New(), PatchFunction1< Type >::New(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::readField().
virtual const dictionary* dictPtr () const inline virtual
Return pointer to dictionary, if entry is a dictionary.
Return nullptr if the entry is not a dictionary.
Reimplemented in dictionaryEntry.
Definition at line 282 of file entry.H.
References Foam::T(), and Foam::val.
Referenced by entry::keyword().
virtual dictionary* dictPtr () inline virtual
Return non-const pointer to dictionary, if entry is a dictionary.
Return nullptr if the entry is not a dictionary.
Reimplemented in dictionaryEntry.
Definition at line 292 of file entry.H.
References entry::checkITstream(), entry::stream(), and Foam::val.
virtual const dictionary& dict () const pure virtual
Return dictionary, if entry is a dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
Referenced by Function1< Type >::New(), PatchFunction1< Type >::New(), and GeometricField< Type, PatchField, GeoMesh >::Boundary::readField().
virtual dictionary& dict () pure virtual
Return non-const access to dictionary, if entry is a dictionary.
Implemented in primitiveEntry, and dictionaryEntry.
void checkITstream (const ITstream & is) const
Check after reading if the input token stream has unconsumed tokens remaining or if there were no tokens in the first place.
Emits FatalIOError
Definition at line 89 of file entry.C.
Referenced by entry::dictPtr(), and entry::isDict().
T get () const inline
Get a T from the stream, FatalIOError if the number of tokens is incorrect.
Definition at line 323 of file entry.H.
Referenced by stringEntry::evaluate(), and Foam::getOrAdd().
void readEntry (T & val) const inline
Assign to T val, FatalIOError if the number of tokens is incorrect.
Parameters
val the value to read into
Definition at line 338 of file entry.H.
Referenced by CodedSource< Type >::read().
T getCheck (const Predicate & pred) const inline
Get a T from the stream, FatalIOError if the number of tokens is incorrect.
Parameters
pred the value check predicate
Definition at line 354 of file entry.H.
void readCheck (T & val, const Predicate & pred) const inline
Assign to T val, FatalIOError if the number of tokens is incorrect.
Parameters
val the value to read into
pred the value check predicate
Definition at line 370 of file entry.H.
virtual void write (Ostream & os) const pure virtual
Write.
Implemented in primitiveEntry, dictionaryEntry, functionEntry, and dictionaryListEntry.
void operator= (const entry & e)
Definition at line 173 of file entry.C.
bool operator== (const entry & e) const
Definition at line 184 of file entry.C.
bool operator!= (const entry & e) const
Definition at line 207 of file entry.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const entry & e) friend
Member Data Documentation
int disableFunctionEntries static
Enable or disable use of function entries and variable expansions.
Definition at line 129 of file entry.H.
Foam::entry::inputMode globalInputMode = inputMode::MERGE static
The current global input-mode.
Definition at line 134 of file entry.H.
Referenced by entry::entry().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/entry/entry.H
src/OpenFOAM/db/dictionary/entry/entry.C
src/OpenFOAM/db/dictionary/entry/entryIO.C