OpenFOAM: string Class Reference
string Class Reference
A class for handling character strings derived from std::string.
Classes
struct hash
Hashing function for string and derived string classes.
Public Member Functions
string ()=default
Construct null.
string (const std::string &str)
Copy construct from std::string.
string (std::string &&str)
Move construct from std::string.
string (const char *str)
Construct as copy of character array.
string (const char *str, const size_type len)
Construct as copy with a maximum number of characters.
string (const char c)
Construct from a single character.
string (const size_type len, const char c)
Construct fill copies of a single character.
string (Istream &is)
Construct from Istream.
bool match (const std::string &text) const
Test for equality.
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
Replace first occurrence of sub-string s1 with s2, beginning at pos.
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
Replace all occurrences of sub-string s1 with s2, beginning at pos in the string.
string & expand (const bool allowEmpty=false)
Inplace expand initial tags, tildes, and all occurrences of environment variables as per stringOps::expand.
bool removeRepeated (const char character)
Remove repeated characters.
bool removeStart (const std::string &text)
Remove the given text from the start of the string.
bool removeStart (const char c)
Remove leading character, unless string is a single character.
bool removeEnd (const std::string &text)
Remove the given text from the end of the string.
bool removeEnd (const char c)
Remove trailing character, unless string is a single character.
void swap (std::string &str)
Swap contents. Self-swapping is a no-op.
bool operator() (const std::string &text) const
Test for equality. Allows use as a predicate.
bool starts_with (const std::string &s) const
True if string starts with the given prefix (cf. C++20)
bool starts_with (const char c) const
True if string starts with the given character (cf. C++20)
bool ends_with (const std::string &s) const
True if string ends with the given suffix (cf. C++20)
bool ends_with (const char c) const
True if string ends with the given character (cf. C++20)
size_type count (const char c) const
Count the number of occurrences of the specified character in the string.
bool startsWith (const std::string &s) const
Deprecated(2019-11)
bool endsWith (const std::string &s) const
Deprecated(2019-11)
bool removeTrailing (const char c)
Deprecated(2019-11)
template<class String >
Foam::string quotemeta (const std::string &str, const char quote)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Static Public Member Functions
template<class String >
static bool valid (const std::string &str)
Does the string contain valid characters only?
template<class String >
static bool meta (const std::string &str, const char quote='\\')
Does this string contain meta-characters?
template<class String >
static bool stripInvalid (std::string &str)
Strip invalid characters from the given string.
template<class String >
static String validate (const std::string &str)
Return a valid String from the given string.
template<class String >
static string quotemeta (const std::string &str, const char quote= '\\')
Return a String with quoted meta-characters from the given string.
Static Public Attributes
static const char *const typeName = "string"
The type name "string".
static int debug
The debug flag.
static const string null
An empty string.
Protected Member Functions
std::string::size_type find_ext () const
Find position of a file extension dot, return npos on failure.
word ext () const
Return file name extension (part after last .)
bool ext (const word &ending)
Append a '.' and the ending.
bool hasPath () const
Return true if it contains a '/' character.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
bool removePath ()
Remove leading path, returning true if string changed.
Static Protected Member Functions
static std::string::size_type find_ext (const std::string &str)
Find position of a file extension dot, return npos on failure.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
Detailed Description
A class for handling character strings derived from std::string.
Strings may contain any characters and therefore are delimited by quotes for IO : "any list of characters".
Used as a base class for word and fileName.
See Also
Foam::findEtcFile() for information about the site/user OpenFOAM configuration directory
Source files
string.H
stringI.H
string.C
stringIO.C
stringTemplates.C
Definition at line 69 of file string.H.
Constructor & Destructor Documentation
string () default
Construct null.
string (const std::string & str) inline
Copy construct from std::string.
Definition at line 86 of file stringI.H.
string (std::string && str) inline
Move construct from std::string.
Definition at line 92 of file stringI.H.
string (const char * str) inline
Construct as copy of character array.
Definition at line 98 of file stringI.H.
string (const char * str, const size_type len) inline
Construct as copy with a maximum number of characters.
Definition at line 104 of file stringI.H.
string (const char c) inline explicit
Construct from a single character.
Definition at line 110 of file stringI.H.
string (const size_type len, const char c) inline
Construct fill copies of a single character.
Definition at line 116 of file stringI.H.
string (Istream & is) explicit
Construct from Istream.
Definition at line 27 of file stringIO.C.
Member Function Documentation
std::string::size_type find_ext (const std::string & str) inline static protected
Find position of a file extension dot, return npos on failure.
A wrapped version of find_last_of("./") with additional logic.
Definition at line 24 of file stringI.H.
References i.
std::string::size_type find_ext () const inline protected
Find position of a file extension dot, return npos on failure.
A wrapped version of find_last_of("./") with additional logic.
Definition at line 37 of file stringI.H.
static std::string::size_type string_printf (std::string & output, const char * fmt, const PrimitiveType & val) static protected
A printf-style formatter for a primitive.
static std::string::size_type string_printf (std::string & output, const std::string & fmt, const PrimitiveType & val) static protected
A printf-style formatter for a primitive.
Foam::word ext () const protected
Return file name extension (part after last .)
Definition at line 38 of file string.C.
Referenced by word::ext(), word::hasExt(), and fileName::nameLessExt().
bool ext (const word & ending) protected
Append a '.' and the ending.
The '.' and ending will not be added when the ending is empty, or when the object was or ended with a '/'.
Returns
True if append occurred.
Definition at line 51 of file string.C.
bool hasPath () const inline protected
Return true if it contains a '/' character.
Definition at line 43 of file stringI.H.
Referenced by fileName::hasExt().
bool hasExt () const inline protected
Return true if it has an extension or simply ends with a '.'.
Definition at line 49 of file stringI.H.
References Foam::ListOps::find().
Referenced by fileName::components(), word::hasExt(), fileName::hasExt(), Foam::operator&(), fileName::path(), and word::removeExt().
bool hasExt (const word & ending) const protected
Return true if the extension is the same as the given ending.
Definition at line 74 of file string.C.
bool hasExt (const wordRe & ending) const protected
Return true if the extension matches the given ending.
Definition at line 92 of file string.C.
bool removeExt () inline protected
Remove extension, returning true if string changed.
Definition at line 69 of file stringI.H.
Referenced by fileName::ext(), and word::operator=().
bool removePath () inline protected
Remove leading path, returning true if string changed.
Definition at line 55 of file stringI.H.
Referenced by fileName::removeExt().
bool valid (const std::string & str) inline static
Does the string contain valid characters only?
Definition at line 125 of file stringI.H.
bool meta (const std::string & str, const char quote = '\\') inline static
Does this string contain meta-characters?
The meta characters can be optionally quoted.
Definition at line 169 of file stringI.H.
bool stripInvalid (std::string & str) inline static
Strip invalid characters from the given string.
Definition at line 140 of file stringI.H.
String validate (const std::string & str) inline static
Return a valid String from the given string.
Definition at line 231 of file stringI.H.
static string quotemeta (const std::string & str, const char quote = '\\') inline static
Return a String with quoted meta-characters from the given string.
bool match (const std::string & text) const inline
Test for equality.
Returns
True when strings match literally.
Definition at line 253 of file stringI.H.
Foam::string & replace (const std::string & s1, const std::string & s2, size_type pos = 0)
Replace first occurrence of sub-string s1 with s2, beginning at pos.
Definition at line 114 of file string.C.
References Foam::stringOps::count().
Referenced by objectRegistry::found(), and parseDriver::setInternalFieldResult().
Foam::string & replaceAll (const std::string & s1, const std::string & s2, size_type pos = 0)
Replace all occurrences of sub-string s1 with s2, beginning at pos in the string.
This is a no-op if s1 is empty.
Definition at line 130 of file string.C.
Foam::string & expand (const bool allowEmpty = false)
Inplace expand initial tags, tildes, and all occurrences of environment variables as per stringOps::expand.
Any unknown entries are removed silently if allowEmpty is true
See Also
Foam::findEtcFile
Definition at line 152 of file string.C.
Referenced by functionObjectBase::getFileName(), and TableFile< Type >::TableFile().
bool removeRepeated (const char character)
Remove repeated characters.
Returns
True if string changed
Definition at line 159 of file string.C.
References Foam::stringOps::inplaceExpand().
bool removeStart (const std::string & text)
Remove the given text from the start of the string.
Returns
True if the removal occurred
Definition at line 193 of file string.C.
bool removeStart (const char c)
Remove leading character, unless string is a single character.
Returns
True if the removal occurred
Definition at line 223 of file string.C.
bool removeEnd (const std::string & text)
Remove the given text from the end of the string.
Returns
True if the removal occurred
Definition at line 208 of file string.C.
bool removeEnd (const char c)
Remove trailing character, unless string is a single character.
Returns
True if the removal occurred
Definition at line 235 of file string.C.
void swap (std::string & str) inline
Swap contents. Self-swapping is a no-op.
Definition at line 259 of file stringI.H.
bool operator() (const std::string & text) const inline
Test for equality. Allows use as a predicate.
Returns
True when strings match literally.
Definition at line 271 of file stringI.H.
bool starts_with (const std::string & s) const inline
True if string starts with the given prefix (cf. C++20)
Definition at line 382 of file string.H.
bool starts_with (const char c) const inline
True if string starts with the given character (cf. C++20)
Definition at line 390 of file string.H.
bool ends_with (const std::string & s) const inline
True if string ends with the given suffix (cf. C++20)
Definition at line 398 of file string.H.
Referenced by IOobjectList::allNames().
bool ends_with (const char c) const inline
True if string ends with the given character (cf. C++20)
Definition at line 406 of file string.H.
Foam::string::size_type count (const char c) const
Count the number of occurrences of the specified character in the string.
Partially deprecated (NOV-2017) in favour of stringOps::count
Definition at line 107 of file string.C.
bool startsWith (const std::string & s) const inline
Deprecated(2019-11)
Deprecated:
(2019-11) use starts_with instead
Definition at line 424 of file string.H.
bool endsWith (const std::string & s) const inline
Deprecated(2019-11)
Deprecated:
(2019-11) use ends_with instead
Definition at line 431 of file string.H.
bool removeTrailing (const char c) inline
Deprecated(2019-11)
Deprecated:
(2019-11) use removeEnd instead
Definition at line 438 of file string.H.
Foam::string quotemeta (const std::string & str, const char quote) inline
Definition at line 194 of file stringI.H.
std::string::size_type string_printf (std::string & output, const char * fmt, const PrimitiveType & val)
Definition at line 29 of file stringTemplates.C.
References n.
std::string::size_type string_printf (std::string & output, const std::string & fmt, const PrimitiveType & val)
Definition at line 57 of file stringTemplates.C.
Member Data Documentation
const char *const typeName = "string" static
The type name "string".
Definition at line 166 of file string.H.
int debug static
The debug flag.
Definition at line 171 of file string.H.
const Foam::string null static
An empty string.
Definition at line 176 of file string.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/string/string.H
src/OpenFOAM/primitives/strings/string/string.C
src/OpenFOAM/primitives/strings/string/stringI.H
src/OpenFOAM/primitives/strings/string/stringIO.C
src/OpenFOAM/primitives/strings/string/stringTemplates.C