OpenFOAM: SRFWallVelocityFvPatchVectorField Class Reference
SRFWallVelocityFvPatchVectorField Class Reference
Wall
Wall-velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: FOAM::SRFModel)
Public Member Functions
TypeName ("SRFWallVelocity")
Runtime type information.
SRFWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
SRFWallVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given SRFWallVelocityFvPatchVectorField.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &)
Construct as copy.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchVectorField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Wall-velocity condition to be used in conjunction with the single rotating frame (SRF) model (see: FOAM::SRFModel)
The condition applies the appropriate rotation transformation in time and space to determine the local SRF velocity of the wall.
where
=
=
The normal component of is removed to ensure 0 wall-flux even if the wall patch faces are irregular.
Usage
Example of the boundary condition specification:
<patchName>
{
    type            SRFWallVelocity;
    value           uniform (0 0 0);    // Initial value
}
See Also
Foam::SRFModel Foam::SRFVelocityFvPatchVectorField Foam::fixedValueFvPatchField
Source files
SRFWallVelocityFvPatchVectorField.H
SRFWallVelocityFvPatchVectorField.C
Definition at line 89 of file SRFWallVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
SRFWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 30 of file SRFWallVelocityFvPatchVectorField.C.
Referenced by SRFWallVelocityFvPatchVectorField::clone().
SRFWallVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 52 of file SRFWallVelocityFvPatchVectorField.C.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given SRFWallVelocityFvPatchVectorField.
onto a new patch
Definition at line 40 of file SRFWallVelocityFvPatchVectorField.C.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & srfvpvf)
Construct as copy.
Definition at line 63 of file SRFWallVelocityFvPatchVectorField.C.
SRFWallVelocityFvPatchVectorField (const SRFWallVelocityFvPatchVectorField & srfvpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 72 of file SRFWallVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName ("SRFWallVelocity")
Runtime type information.
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 147 of file SRFWallVelocityFvPatchVectorField.H.
References SRFWallVelocityFvPatchVectorField::SRFWallVelocityFvPatchVectorField().
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 168 of file SRFWallVelocityFvPatchVectorField.H.
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 84 of file SRFWallVelocityFvPatchVectorField.C.
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 93 of file SRFWallVelocityFvPatchVectorField.C.
References Field< vector >::autoMap().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 102 of file SRFWallVelocityFvPatchVectorField.C.
void write (Ostream & os) const virtual
Write.
Definition at line 125 of file SRFWallVelocityFvPatchVectorField.C.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFWallVelocityFvPatchVectorField/SRFWallVelocityFvPatchVectorField.H
src/finiteVolume/cfdTools/general/SRF/derivedFvPatchFields/SRFWallVelocityFvPatchVectorField/SRFWallVelocityFvPatchVectorField.C