OpenFOAM: veryInhomogeneousMixture< ThermoType > Class Template Reference
veryInhomogeneousMixture< ThermoType > Class Template Reference
Mixtures
The very inhomogeneous mixture contains species ("ft", "fu", "b").
Public Types
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Public Types inherited from basicCombustionMixture
typedef basicCombustionMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
The base class of the mixture.
Public Member Functions
veryInhomogeneousMixture (const dictionary &thermoDict, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, mesh and phase name.
virtual ~veryInhomogeneousMixture ()=default
Destructor.
const dimensionedScalar & stoicRatio () const
const ThermoType & mixture (const scalar, const scalar) const
const ThermoType & cellMixture (const label celli) const
const ThermoType & patchFaceMixture (const label patchi, const label facei) const
const ThermoType & cellReactants (const label celli) const
const ThermoType & patchFaceReactants (const label patchi, const label facei) const
const ThermoType & cellProducts (const label celli) const
const ThermoType & patchFaceProducts (const label patchi, const label facei) const
void read (const dictionary &)
Read dictionary.
const ThermoType & getLocalThermo (const label speciei) const
Return thermo based on index.
Public Member Functions inherited from basicCombustionMixture
TypeName ("basicCombustionMixture")
Run time type information.
basicCombustionMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, specie names, mesh and phase name.
virtual ~basicCombustionMixture ()=default
Destructor.
scalar fres (const scalar ft, const scalar stoicRatio) const
tmp< volScalarField > fres (const volScalarField &ft, const dimensionedScalar &stoicRatio) const
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()=default
Destructor.
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar HE (const label speciei, const scalar p, const scalar T) const =0
Enthalpy/Internal energy [J/kg].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()=default
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
template<class ThermoType>
class Foam::veryInhomogeneousMixture< ThermoType >
The very inhomogeneous mixture contains species ("ft", "fu", "b").
Source files
veryInhomogeneousMixture.H
veryInhomogeneousMixture.C
Definition at line 50 of file veryInhomogeneousMixture.H.
Member Typedef Documentation
typedef ThermoType thermoType
The type of thermodynamics this mixture is instantiated for.
Definition at line 93 of file veryInhomogeneousMixture.H.
Constructor & Destructor Documentation
veryInhomogeneousMixture (const dictionary & thermoDict, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, mesh and phase name.
Definition at line 28 of file veryInhomogeneousMixture.C.
virtual ~veryInhomogeneousMixture () virtual default
Destructor.
Member Function Documentation
static word typeName () inline static
Return the instantiated type name.
Definition at line 120 of file veryInhomogeneousMixture.H.
References veryInhomogeneousMixture< ThermoType >::mixture().
const dimensionedScalar& stoicRatio () const inline
Definition at line 125 of file veryInhomogeneousMixture.H.
Referenced by veryInhomogeneousMixture< ThermoType >::cellProducts(), and veryInhomogeneousMixture< ThermoType >::patchFaceReactants().
const ThermoType& mixture (const scalar , const scalar) const
Referenced by veryInhomogeneousMixture< ThermoType >::cellProducts(), veryInhomogeneousMixture< ThermoType >::patchFaceMixture(), veryInhomogeneousMixture< ThermoType >::patchFaceReactants(), and veryInhomogeneousMixture< ThermoType >::typeName().
const ThermoType& cellMixture (const label celli) const inline
Definition at line 132 of file veryInhomogeneousMixture.H.
const ThermoType& patchFaceMixture (const label patchi, const label facei) const inline
Definition at line 138 of file veryInhomogeneousMixture.H.
References veryInhomogeneousMixture< ThermoType >::mixture().
const ThermoType& cellReactants (const label celli) const inline
Definition at line 150 of file veryInhomogeneousMixture.H.
const ThermoType& patchFaceReactants (const label patchi, const label facei) const inline
Definition at line 156 of file veryInhomogeneousMixture.H.
References basicCombustionMixture::fres(), veryInhomogeneousMixture< ThermoType >::mixture(), veryInhomogeneousMixture< ThermoType >::stoicRatio(), and value().
const ThermoType& cellProducts (const label celli) const inline
Definition at line 168 of file veryInhomogeneousMixture.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), basicCombustionMixture::fres(), veryInhomogeneousMixture< ThermoType >::mixture(), veryInhomogeneousMixture< ThermoType >::stoicRatio(), and value().
const ThermoType& patchFaceProducts (const label patchi, const label facei) const inline
Definition at line 175 of file veryInhomogeneousMixture.H.
void read (const dictionary &)
Read dictionary.
const ThermoType& getLocalThermo (const label speciei) const
Return thermo based on index.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/veryInhomogeneousMixture/veryInhomogeneousMixture.H
src/thermophysicalModels/reactionThermo/mixtures/veryInhomogeneousMixture/veryInhomogeneousMixture.C