OpenFOAM: CompactListList< T, Container > Class Template Reference
CompactListList< T, Container > Class Template Reference
A packed storage unstructured matrix of objects of type <T> using an offset table for access.
Public Member Functions
CompactListList ()
Null constructor.
CompactListList (const List< Container > &)
Construct by converting given List<List<T>>
CompactListList (const label mRows, const label nData)
Construct given size of offset table (number of rows)
CompactListList (const label mRows, const label nData, const T &)
Construct given size of offset table (number of rows),.
CompactListList (const labelUList &rowSizes)
Construct given list of row-sizes.
CompactListList (const labelUList &rowSizes, const T &)
Construct given list of row-sizes.
CompactListList (const CompactListList< T, Container > &lst)
Copy construct.
CompactListList (CompactListList< T, Container > &&lst)
Move construct.
CompactListList (CompactListList< T, Container > &lst, bool reuse)
Construct as copy or re-use as specified.
CompactListList (Istream &)
Construct from Istream.
autoPtr< CompactListList< T,
Container > > clone () const
Clone.
label size () const noexcept
The primary size (the number of rows)
bool empty () const noexcept
True if the number of rows is zero.
const List< label > & offsets () const
Return the offset table (= size()+1)
List< label > & offsets ()
Return non-const access to the offset table.
const List< T > & m () const
Return the packed matrix of data.
List< T > & m ()
Return non-const access to the packed matrix of data.
void setSize (const label mRows)
Reset size of CompactListList.
void setSize (const label mRows, const label nData)
Reset size of CompactListList.
void setSize (const label mRows, const label nData, const T &)
Reset sizes of CompactListList and value for new elements.
void setSize (const labelUList &rowSizes)
Reset size of CompactListList.
void resize (const label mRows)
Reset size of CompactListList.
void resize (const label mRows, const label nData)
Reset size of CompactListList.
void resize (const label mRows, const label nData, const T &)
Reset sizes of CompactListList and value for new elements.
void resize (const labelUList &rowSizes)
Reset size of CompactListList.
void clear ()
Clear the CompactListList, i.e. set sizes to zero.
labelList sizes () const
Return sizes (to be used e.g. for construction)
void swap (CompactListList< T, Container > &lst)
Swap contents.
void transfer (CompactListList< T, Container > &lst)
Transfer the contents of the argument CompactListList.
label index (const label row, const label col) const
Return index into m.
label whichRow (const label index) const
Get row for index into m.
label whichColumn (const label row, const label index) const
Get column index (j) given above row.
UList< T > operator[] (const label i)
Return subscript-checked row as UList.
const UList< T > operator[] (const label i) const
Return const subscript-checked row as UList.
T & operator() (const label i, const label j)
Return subscript-checked element.
const T & operator() (const label i, const label j) const
Return const subscript-checked element.
List< Container > operator() () const
Return as List<Container>
void operator= (const T &val)
Assignment of all entries to the given value.
void operator= (const CompactListList< T, Container > &lst)
Copy assignment.
void operator= (CompactListList< T, Container > &&lst)
Move assignment.
Static Public Member Functions
static const CompactListList
< T, Container > & null ()
Return a null CompactListList.
Friends
Istream & operator>> (Istream &, CompactListList< T, Container > &)
Read CompactListList from Istream, discarding contents.
Ostream & operator (Ostream &, const CompactListList< T, Container > &)
Detailed Description
template<class T, class Container>
class Foam::CompactListList< T, Container >
A packed storage unstructured matrix of objects of type <T> using an offset table for access.
The offset table is the size of the number of rows+1 whose elements are the accumulated sizes of the rows, i.e.
offset[i] gives the index of first element of row i
offset[i+1] - offset[i] is the number of elements in row i
Storage is allocated on free-store during construction.
As a special case a null-constructed CompactListList has an empty offsets_ (instead of size 1).
Source files
CompactListList.H
CompactListList.C
CompactListListI.H
CompactListListIO.C
Definition at line 90 of file polyTopoChange.H.
Constructor & Destructor Documentation
CompactListList () inline
Null constructor.
Definition at line 28 of file CompactListListI.H.
CompactListList (const List< Container > & ll) explicit
Construct by converting given List<List<T>>
Definition at line 27 of file CompactListList.C.
References forAll, i, j, k, and UList< T >::size().
CompactListList (const label mRows, const label nData) inline
Construct given size of offset table (number of rows)
and number of data.
Definition at line 36 of file CompactListListI.H.
CompactListList (const label mRows, const label nData, const T & val) inline
Construct given size of offset table (number of rows),.
the number of data and a value for all elements.
Definition at line 49 of file CompactListListI.H.
CompactListList (const labelUList & rowSizes) explicit
Construct given list of row-sizes.
Definition at line 57 of file CompactListList.C.
CompactListList (const labelUList & rowSizes, const T & val)
Construct given list of row-sizes.
Definition at line 78 of file CompactListList.C.
CompactListList (const CompactListList< T, Container > & lst) inline
Copy construct.
Definition at line 63 of file CompactListListI.H.
CompactListList (CompactListList< T, Container > && lst) inline
Move construct.
Definition at line 75 of file CompactListListI.H.
CompactListList (CompactListList< T, Container > & lst, bool reuse) inline
Construct as copy or re-use as specified.
Definition at line 85 of file CompactListListI.H.
References transfer().
CompactListList (Istream & is)
Construct from Istream.
Definition at line 27 of file CompactListListIO.C.
References Foam::operator>>().
Member Function Documentation
const Foam::CompactListList< T, Container > & null () inline static
Return a null CompactListList.
Definition at line 108 of file CompactListListI.H.
Foam::autoPtr< Foam::CompactListList< T, Container > > clone () const inline
Clone.
Definition at line 98 of file CompactListListI.H.
Foam::label size () const inline noexcept
The primary size (the number of rows)
Definition at line 115 of file CompactListListI.H.
bool empty () const inline noexcept
True if the number of rows is zero.
Definition at line 122 of file CompactListListI.H.
const Foam::List< Foam::label > & offsets () const inline
Return the offset table (= size()+1)
Definition at line 130 of file CompactListListI.H.
Referenced by decompositionInformation::clear().
Foam::List< Foam::label > & offsets () inline
Return non-const access to the offset table.
Definition at line 137 of file CompactListListI.H.
const Foam::List< T > & m () const inline
Return the packed matrix of data.
Definition at line 144 of file CompactListListI.H.
Referenced by decompositionInformation::clear().
Foam::List< T > & m () inline
Return non-const access to the packed matrix of data.
Definition at line 152 of file CompactListListI.H.
void setSize (const label mRows)
Reset size of CompactListList.
This form only allows contraction of the CompactListList.
Definition at line 101 of file CompactListList.C.
void setSize (const label mRows, const label nData)
Reset size of CompactListList.
Definition at line 126 of file CompactListList.C.
void setSize (const label mRows, const label nData, const T & t)
Reset sizes of CompactListList and value for new elements.
Definition at line 139 of file CompactListList.C.
void setSize (const labelUList & rowSizes)
Reset size of CompactListList.
Definition at line 152 of file CompactListList.C.
void resize (const label mRows) inline
Reset size of CompactListList.
This form only allows contraction of the CompactListList.
Definition at line 196 of file CompactListListI.H.
void resize (const label mRows, const label nData) inline
Reset size of CompactListList.
Definition at line 204 of file CompactListListI.H.
References setSize().
void resize (const label mRows, const label nData, const T & t) inline
Reset sizes of CompactListList and value for new elements.
Definition at line 215 of file CompactListListI.H.
References setSize().
void resize (const labelUList & rowSizes) inline
Reset size of CompactListList.
Definition at line 227 of file CompactListListI.H.
References setSize().
void clear ()
Clear the CompactListList, i.e. set sizes to zero.
Definition at line 186 of file CompactListList.C.
Foam::labelList sizes () const
Return sizes (to be used e.g. for construction)
Definition at line 170 of file CompactListList.C.
void swap (CompactListList< T, Container > & lst)
Swap contents.
Definition at line 196 of file CompactListList.C.
void transfer (CompactListList< T, Container > & lst)
Transfer the contents of the argument CompactListList.
into this CompactListList and annul the argument list.
Definition at line 213 of file CompactListList.C.
Foam::label index (const label row, const label col) const inline
Return index into m.
Definition at line 160 of file CompactListListI.H.
Foam::label whichRow (const label index) const inline
Get row for index into m.
Definition at line 170 of file CompactListListI.H.
References i, and j.
Foam::label whichColumn (const label row, const label index) const inline
Get column index (j) given above row.
Definition at line 186 of file CompactListListI.H.
Foam::UList< T > operator[] (const label i) inline
Return subscript-checked row as UList.
Definition at line 239 of file CompactListListI.H.
const Foam::UList< T > operator[] (const label i) const inline
Return const subscript-checked row as UList.
Definition at line 251 of file CompactListListI.H.
T & operator() (const label i, const label j) inline
Return subscript-checked element.
Definition at line 266 of file CompactListListI.H.
const T & operator() (const label i, const label j) const inline
Return const subscript-checked element.
Definition at line 277 of file CompactListListI.H.
References j.
Foam::List< Container > operator() () const
Return as List<Container>
Definition at line 231 of file CompactListList.C.
void operator= (const T & val) inline
Assignment of all entries to the given value.
Definition at line 287 of file CompactListListI.H.
References j.
void operator= (const CompactListList< T, Container > & lst) inline
Copy assignment.
Definition at line 295 of file CompactListListI.H.
References Foam::val.
void operator= (CompactListList< T, Container > && lst) inline
Move assignment.
Definition at line 312 of file CompactListListI.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & , CompactListList< T, Container > &) friend
Read CompactListList from Istream, discarding contents.
of existing CompactListList.
Ostream& operator (Ostream & , const CompactListList< T, Container > &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/polyTopoChange.H
src/OpenFOAM/containers/Lists/CompactListList/CompactListList.H
src/OpenFOAM/containers/Lists/CompactListList/CompactListList.C
src/OpenFOAM/containers/Lists/CompactListList/CompactListListI.H
src/OpenFOAM/containers/Lists/CompactListList/CompactListListIO.C