OpenFOAM: wallBoundedStreamLineParticle Class Reference
wallBoundedStreamLineParticle Class Reference
Particle class that samples fields as it passes through. Used in streamline calculation.
Classes
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass tracking data to the trackToEdge function.
Public Member Functions
wallBoundedStreamLineParticle (const polyMesh &c, const point &position, const label celli, const label tetFacei, const label tetPti, const label meshEdgeStart, const label diagEdge, const bool trackForward, const label lifeTime)
Construct from components.
wallBoundedStreamLineParticle (const polyMesh &c, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
wallBoundedStreamLineParticle (const wallBoundedStreamLineParticle &p)
Construct copy.
autoPtr< particle > clone () const
Construct and return a clone.
template<class TrackCloudType >
bool move (TrackCloudType &cloud, trackingData &td, const scalar trackTime)
Track all particles to their end point.
Public Member Functions inherited from wallBoundedParticle
wallBoundedParticle (const polyMesh &c, const point &position, const label celli, const label tetFacei, const label tetPti, const label meshEdgeStart, const label diagEdge)
Construct from components.
wallBoundedParticle (const polyMesh &c, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
wallBoundedParticle (const wallBoundedParticle &p)
Construct copy.
label meshEdgeStart () const
-1 or label of mesh edge
label diagEdge () const
-1 or diagonal edge
template<class TrackCloudType >
scalar trackToEdge (TrackCloudType &cloud, trackingData &td, const vector &endPosition)
Equivalent of trackToFace.
template<class TrackCloudType >
void patchInteraction (TrackCloudType &cloud, trackingData &td, const scalar trackFraction)
Do all patch interaction.
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &cloud, trackingData &td)
Overridable function to handle the particle hitting a processorPatch.
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &cloud, trackingData &td)
Overridable function to handle the particle hitting a wallPatch.
InfoProxy< wallBoundedParticle > info () const
Return info proxy.
template<class TrackCloudType >
Foam::scalar trackToEdge (TrackCloudType &cloud, trackingData &td, const vector &endPosition)
template<class TrackCloudType >
void readFields (TrackCloudType &c)
template<class TrackCloudType >
void writeFields (const TrackCloudType &c)
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label celli=-1)
Construct from a position and a cell.
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const bool doLocate=true)
Construct from position components.
particle (const polyMesh &mesh, Istream &, bool readFields=true, bool newFormat=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with reference to a new mesh.
virtual ~particle ()=default
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const barycentric & coordinates () const
Return current particle coordinates.
label cell () const
Return current cell particle is in.
label & cell ()
Return current cell particle is in for manipulation.
label tetFace () const
Return current tet face particle is in.
label & tetFace ()
Return current tet face particle is in for manipulation.
label tetPt () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in for manipulation.
label face () const
Return current face particle is on otherwise -1.
label & face ()
Return current face particle is on for manipulation.
scalar stepFraction () const
Return the fraction of time-step completed.
scalar & stepFraction ()
Return the fraction of time-step completed.
label origProc () const
Return the originating processor ID.
label & origProc ()
Return the originating processor ID.
label origId () const
Return the particle ID on the originating processor.
label & origId ()
Return the particle ID on the originating processor.
Pair< scalar > stepFractionSpan () const
Return the step fraction change within the overall time-step.
scalar currentTimeFraction () const
Return the current fraction within the timestep. This differs.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
barycentricTensor currentTetTransform () const
Return the current tet transformation tensor.
vector normal () const
The (unit) normal of the tri on tetFacei_ for the current tet.
bool onFace () const
Is the particle on a face?
bool onInternalFace () const
Is the particle on an internal face?
bool onBoundaryFace () const
Is the particle on a boundary face?
label patch () const
Return the index of patch that the particle is on.
vector position () const
Return current particle position.
scalar track (const vector &displacement, const scalar fraction)
Track along the displacement for a given fraction of the overall.
scalar trackToFace (const vector &displacement, const scalar fraction)
As particle::track, but also stops on internal faces.
scalar trackToTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToFace, but also stops on tet triangles. On.
scalar trackToStationaryTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for stationary meshes.
scalar trackToMovingTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for moving meshes.
template<class TrackCloudType >
void hitFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
Hit the current face. If the current face is internal than this.
template<class TrackCloudType >
void trackToAndHitFace (const vector &direction, const scalar fraction, TrackCloudType &cloud, trackingData &td)
Convenience function. Combines trackToFace and hitFace.
vector deviationFromMeshCentre () const
Get the displacement from the mesh centre. Used to correct the.
void patchData (vector &n, vector &U) const
Get the normal and velocity of the current patch location.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
void prepareForParallelTransfer ()
Convert global addressing to the processor patch local equivalents.
void correctAfterParallelTransfer (const label patchi, trackingData &td)
Convert processor patch addressing to the global equivalents.
void prepareForInteractionListReferral (const vectorTensorTransform &transform)
Break the topology and store the particle position so that the.
void correctAfterInteractionListReferral (const label celli)
Correct the topology after referral. The particle may still be.
label procTetPt (const polyMesh &procMesh, const label procCell, const label procTetFace) const
Return the tet point appropriate for decomposition or reconstruction.
void autoMap (const vector &position, const mapPolyMesh &mapper)
Map after a topology change.
void relocate (const point &position, const label celli=-1)
Set the addressing based on the provided position.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
Write individual particle properties to stream.
void writeCoordinates (Ostream &os) const
Write the particle barycentric coordinates and cell info.
virtual void writePosition (Ostream &os) const
Write the particle position and cell id.
Static Public Member Functions
static void readFields (Cloud< wallBoundedStreamLineParticle > &)
Read.
static void writeFields (const Cloud< wallBoundedStreamLineParticle > &)
Write.
Static Public Member Functions inherited from wallBoundedParticle
template<class CloudType >
static void readFields (CloudType &)
Read.
template<class CloudType >
static void writeFields (const CloudType &)
Write.
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class Type >
static void writePropertyName (Ostream &os, const word &name, const word &delim)
Write the name representation to stream.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Type &value, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property to stream, optionally filtered based on its name.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Field< Type > &values, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property list to stream, optionally filtered based on its name.
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
Read the fields associated with the owner cloud.
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
Write the fields associated with the owner cloud.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Protected Member Functions
vector interpolateFields (const trackingData &td, const point &position, const label celli, const label facei)
vector sample (trackingData &td)
Protected Member Functions inherited from wallBoundedParticle
edge currentEdge () const
Construct current edge.
void crossEdgeConnectedFace (const label &celli, label &tetFacei, label &tetPti, const edge &e)
Replacement for particle::crossEdgeConnectedFace that avoids bombing.
void crossEdgeConnectedFace (const edge &meshEdge)
Cross mesh edge into different face on same cell.
void crossDiagonalEdge ()
Cross diagonal edge into different triangle on same face,cell.
scalar trackFaceTri (const vector &n, const vector &endPosition, label &)
Track through single triangle.
bool isTriAlongTrack (const vector &n, const point &endPosition) const
Is current triangle in the track direction.
Protected Member Functions inherited from particle< Type >
template<class TrackCloudType >
bool hitPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a patch.
template<class TrackCloudType >
void hitWedgePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackCloudType >
void hitSymmetryPlanePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitSymmetryPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a symmetryPatch.
template<class TrackCloudType >
void hitCyclicPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackCloudType >
void hitCyclicAMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackCloudType >
void hitCyclicACMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a processorPatch.
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wallPatch.
Protected Attributes
bool trackForward_
Track with +U or -U.
label lifeTime_
Lifetime of particle. Particle dies when reaches 0.
DynamicList< point > sampledPositions_
Sampled positions.
List< DynamicList< scalar > > sampledScalars_
Sampled scalars.
List< DynamicList< vector > > sampledVectors_
Sampled vectors.
Protected Attributes inherited from wallBoundedParticle
point localPosition_
Particle position is updated locally as opposed to via track.
label meshEdgeStart_
Particle is on mesh edge:
label diagEdge_
Particle is on diagonal edge:
Friends
Ostream & operator<< (Ostream &, const wallBoundedStreamLineParticle &)
Additional Inherited Members
Static Public Attributes inherited from wallBoundedParticle
static const std::size_t sizeofFields_
Size in bytes of the fields.
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provide unique ID.
static bool writeLagrangianCoordinates = true
Write particle coordinates file (v1712 and later) Default is true.
static bool writeLagrangianPositions
Write particle positions file (v1706 format and earlier) Default is true (disable in etc/controlDict)
Detailed Description
Particle class that samples fields as it passes through. Used in streamline calculation.
Source files
wallBoundedStreamLineParticle.H
wallBoundedStreamLineParticle.C
Definition at line 62 of file wallBoundedStreamLineParticle.H.
Constructor & Destructor Documentation
wallBoundedStreamLineParticle (const polyMesh & c, const point & position, const label celli, const label tetFacei, const label tetPti, const label meshEdgeStart, const label diagEdge, const bool trackForward, const label lifeTime)
Construct from components.
Definition at line 116 of file wallBoundedStreamLineParticle.C.
wallBoundedStreamLineParticle (const polyMesh & c, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 144 of file wallBoundedStreamLineParticle.C.
wallBoundedStreamLineParticle (const wallBoundedStreamLineParticle & p)
Construct copy.
Definition at line 178 of file wallBoundedStreamLineParticle.C.
Member Function Documentation
Foam::vector interpolateFields (const trackingData & td, const point & position, const label celli, const label facei) protected
Definition at line 28 of file wallBoundedStreamLineParticle.C.
References Foam::abort(), DynamicList< T, SizeMin >::append(), Foam::FatalError, FatalErrorInFunction, forAll, UList< T >::last(), Foam::magSqr(), particle< Type >::position(), wallBoundedStreamLineParticle::sampledPositions_, wallBoundedStreamLineParticle::sampledScalars_, wallBoundedStreamLineParticle::sampledVectors_, UList< T >::size(), Foam::sqr(), U, wallBoundedStreamLineParticle::trackingData::UIndex_, wallBoundedStreamLineParticle::trackingData::vsInterp_, and wallBoundedStreamLineParticle::trackingData::vvInterp_.
Foam::vector sample (trackingData & td) protected
Definition at line 87 of file wallBoundedStreamLineParticle.C.
Referenced by wallBoundedStreamLineParticle::move().
autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from wallBoundedParticle.
Definition at line 208 of file wallBoundedStreamLineParticle.H.
bool move (TrackCloudType & cloud, trackingData & td, const scalar trackTime)
Track all particles to their end point.
Definition at line 26 of file wallBoundedStreamLineParticleTemplates.C.
References wallBoundedStreamLineParticle::trackingData::allPositions_, wallBoundedStreamLineParticle::trackingData::allScalars_, wallBoundedStreamLineParticle::trackingData::allVectors_, polyMesh::bounds(), Foam::expressions::patchExpr::debug, Foam::endl(), forAll, i, particle< Type >::trackingData::keepParticle, wallBoundedStreamLineParticle::lifeTime_, wallBoundedParticle::localPosition_, boundBox::mag(), particle< Type >::mesh(), p, Foam::Pout, wallBoundedStreamLineParticle::sample(), wallBoundedStreamLineParticle::sampledPositions_, wallBoundedStreamLineParticle::sampledScalars_, wallBoundedStreamLineParticle::sampledVectors_, UList< T >::size(), particle< Type >::stepFraction(), particle< Type >::trackingData::switchProcessor, wallBoundedStreamLineParticle::trackingData::trackLength_, wallBoundedParticle::trackToEdge(), List< T >::transfer(), and U.
void readFields (Cloud< wallBoundedStreamLineParticle > & c) static
Read.
Definition at line 194 of file wallBoundedStreamLineParticle.C.
Referenced by wallBoundedStreamLineParticleCloud::wallBoundedStreamLineParticleCloud().
void writeFields (const Cloud< wallBoundedStreamLineParticle > & c) static
Write.
Definition at line 228 of file wallBoundedStreamLineParticle.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const wallBoundedStreamLineParticle &) friend
Member Data Documentation
bool trackForward_ protected
Track with +U or -U.
Definition at line 133 of file wallBoundedStreamLineParticle.H.
label lifeTime_ protected
Lifetime of particle. Particle dies when reaches 0.
Definition at line 138 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::move().
DynamicList<point> sampledPositions_ protected
Sampled positions.
Definition at line 143 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::interpolateFields(), and wallBoundedStreamLineParticle::move().
List<DynamicList<scalar> > sampledScalars_ protected
Sampled scalars.
Definition at line 148 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::interpolateFields(), and wallBoundedStreamLineParticle::move().
List<DynamicList<vector> > sampledVectors_ protected
Sampled vectors.
Definition at line 153 of file wallBoundedStreamLineParticle.H.
Referenced by wallBoundedStreamLineParticle::interpolateFields(), and wallBoundedStreamLineParticle::move().
The documentation for this class was generated from the following files:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLineParticle.H
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLineParticle.C
src/functionObjects/field/wallBoundedStreamLine/wallBoundedStreamLineParticleTemplates.C