OpenFOAM: hexRef8 Class Reference
hexRef8 Class Reference
Refinement of (split) hexes using polyTopoChange.
Public Member Functions
ClassName ("hexRef8")
Runtime type information.
hexRef8 (const polyMesh &mesh, const bool readHistory=true)
Construct from mesh, read_if_present refinement data.
hexRef8 (const polyMesh &mesh, const labelList &cellLevel, const labelList &pointLevel, const refinementHistory &history, const scalar level0Edge=-GREAT)
Construct from mesh and un/refinement data and optional size of.
hexRef8 (const polyMesh &mesh, const labelList &cellLevel, const labelList &pointLevel, const scalar level0Edge=-GREAT)
Construct from mesh and refinement data and optional size of.
const polyMesh & mesh () const
const labelIOList & cellLevel () const
const labelIOList & pointLevel () const
const refinementHistory & history () const
scalar level0EdgeLength () const
Typical edge length between unrefined points.
label faceLevel (const label facei) const
Gets level such that the face has four points <= level.
labelList consistentRefinement (const labelUList &cellLevel, const labelList &cellsToRefine, const bool maxSet) const
Given valid mesh and current cell level and proposed.
labelList consistentRefinement (const labelList &cellsToRefine, const bool maxSet) const
Given valid mesh and current cell level and proposed.
labelList consistentSlowRefinement (const label maxFaceDiff, const labelList &cellsToRefine, const labelList &facesToCheck, const label maxPointDiff, const labelList &pointsToCheck) const
Like consistentRefinement but slower:
labelList consistentSlowRefinement2 (const label maxFaceDiff, const labelList &cellsToRefine, const labelList &facesToCheck) const
Like consistentSlowRefinement but uses different meshWave.
labelListList setRefinement (const labelList &cells, polyTopoChange &)
Insert refinement. All selected cells will be split into 8.
void updateMesh (const mapPolyMesh &)
Update local numbering for changed mesh.
void storeData (const labelList &pointsToStore, const labelList &facesToStore, const labelList &cellsToStore)
Signal points/face/cells for which to store data.
void updateMesh (const mapPolyMesh &, const Map< label > &pointsToRestore, const Map< label > &facesToRestore, const Map< label > &cellsToRestore)
Update local numbering + undo.
void subset (const labelList &pointMap, const labelList &faceMap, const labelList &cellMap)
Update local numbering for subsetted mesh.
void distribute (const mapDistributePolyMesh &)
Update local numbering for mesh redistribution.
void checkMesh () const
Debug: Check coupled mesh for correctness.
void checkRefinementLevels (const label maxPointDiff, const labelList &pointsToCheck) const
Debug: Check 2:1 consistency across faces.
const cellShapeList & cellShapes () const
Utility: get hexes as cell shapes.
labelList getSplitPoints () const
Return the points at the centre of top-level split cells.
labelList consistentUnrefinement (const labelList &pointsToUnrefine, const bool maxSet) const
Given proposed.
void setUnrefinement (const labelList &splitPointLabels, polyTopoChange &)
Remove some refinement. Needs to be supplied output of.
void setInstance (const fileName &inst)
bool write (const bool valid=true) const
Force writing refinement+history to polyMesh directory.
Static Public Member Functions
static void removeFiles (const polyMesh &)
Helper: remove all relevant files from mesh instance.
Detailed Description
Refinement of (split) hexes using polyTopoChange.
Source files
hexRef8.H
hexRef8.C
Definition at line 63 of file hexRef8.H.
Constructor & Destructor Documentation
hexRef8 (const polyMesh & mesh, const bool readHistory = true)
Construct from mesh, read_if_present refinement data.
(from write below). If readHistory is true does read_if_present of refinement history. If false clears all history
Definition at line 1925 of file hexRef8.C.
References Foam::abort(), refinementHistory::active(), hexRef8::checkMesh(), hexRef8::checkRefinementLevels(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::nCells(), primitiveMesh::nPoints(), IOobject::objectPath(), refinementHistory::read(), IOobject::READ_IF_PRESENT, IOobject::readOpt(), UList< T >::size(), IOobject::typeHeaderOk(), and refinementHistory::visibleCells().
hexRef8 (const polyMesh & mesh, const labelList & cellLevel, const labelList & pointLevel, const refinementHistory & history, const scalar level0Edge = -GREAT)
Construct from mesh and un/refinement data and optional size of.
starting cells
Definition at line 2040 of file hexRef8.C.
hexRef8 (const polyMesh & mesh, const labelList & cellLevel, const labelList & pointLevel, const scalar level0Edge = -GREAT)
Construct from mesh and refinement data and optional size of.
starting cells
Definition at line 2150 of file hexRef8.C.
Member Function Documentation
ClassName ("hexRef8")
Runtime type information.
const polyMesh& mesh () const inline
Definition at line 477 of file hexRef8.H.
const labelIOList& cellLevel () const inline
Definition at line 482 of file hexRef8.H.
const labelIOList& pointLevel () const inline
Definition at line 487 of file hexRef8.H.
const refinementHistory& history () const inline
Definition at line 492 of file hexRef8.H.
scalar level0EdgeLength () const inline
Typical edge length between unrefined points.
Definition at line 500 of file hexRef8.H.
Foam::label faceLevel (const label facei) const
Gets level such that the face has four points <= level.
Definition at line 794 of file hexRef8.C.
Foam::labelList consistentRefinement (const labelUList & cellLevel, const labelList & cellsToRefine, const bool maxSet) const
Given valid mesh and current cell level and proposed.
cells to refine calculate any clashes (due to 2:1) and return ok list of cells to refine. Either adds cells to refine to set (maxSet = true) or removes cells to refine (maxSet = false)
Definition at line 2252 of file hexRef8.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::Pout, and Foam::reduce().
labelList consistentRefinement (const labelList & cellsToRefine, const bool maxSet) const inline
Given valid mesh and current cell level and proposed.
cells to refine calculate any clashes (due to 2:1) and return ok list of cells to refine. Either adds cells to refine to set (maxSet = true) or removes cells to refine (maxSet = false)
Definition at line 536 of file hexRef8.H.
Foam::labelList consistentSlowRefinement (const label maxFaceDiff, const labelList & cellsToRefine, const labelList & facesToCheck, const label maxPointDiff, const labelList & pointsToCheck) const
Like consistentRefinement but slower:
specify number of cells between consecutive refinement levels (consistentRefinement equivalent to 1)
specify max level difference between point-connected cells. (-1 to disable) Note that with normal 2:1 limitation (maxFaceDiff=1) there can be 8:1 size difference across point connected cells so maxPointDiff allows you to make that less. cellsToRefine : cells we're thinking about refining. It will extend this set. All refinement levels will be at least maxFaceDiff layers thick. facesToCheck : additional faces where to implement the maxFaceDiff thickness (usually only boundary faces)
Definition at line 2308 of file hexRef8.C.
References Foam::abort(), List< T >::append(), Foam::BitOps::count(), refinementData::count(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, i, refinementData::isRefined(), iter, FaceCellWave< Type, TrackingData >::iterate(), Foam::labelMin, Foam::mag(), Foam::max(), Foam::nl, Foam::Pout, Foam::reduce(), refinementData::refinementCount(), FaceCellWave< Type, TrackingData >::setFaceInfo(), UList< T >::size(), syncTools::swapBoundaryFaceList(), syncTools::syncPointList(), refinementData::updateFace(), and Foam::Zero.
Foam::labelList consistentSlowRefinement2 (const label maxFaceDiff, const labelList & cellsToRefine, const labelList & facesToCheck) const
Like consistentSlowRefinement but uses different meshWave.
(proper distance instead of toplogical count). No point checks yet.
Definition at line 2792 of file hexRef8.C.
Foam::labelListList setRefinement (const labelList & cells, polyTopoChange & meshMod)
Insert refinement. All selected cells will be split into 8.
Returns per element in cells the 8 cells they were split into. Guarantees that the 0th element is the original cell label. Mapping: -split cells: 7 new ones get added from original -split faces: original gets modified; 3 new ones get added from original -added internal faces: added from original cell face(if that was internal) or created out-of-nothing (so will not get mapped!). Note: could make this inflate from point but that will allocate interpolation. -points added to split edge: added from edge start() -midpoints added: added from cellPoints[0].
Definition at line 3192 of file hexRef8.C.
void updateMesh (const mapPolyMesh & map)
Update local numbering for changed mesh.
Definition at line 4233 of file hexRef8.C.
void storeData (const labelList & pointsToStore, const labelList & facesToStore, const labelList & cellsToStore)
Signal points/face/cells for which to store data.
Definition at line 4206 of file hexRef8.C.
void updateMesh (const mapPolyMesh & map, const Map< label > & pointsToRestore, const Map< label > & facesToRestore, const Map< label > & cellsToRestore)
Update local numbering + undo.
Data to restore given as new pointlabel + stored pointlabel (i.e. what was in pointsToStore)
Definition at line 4245 of file hexRef8.C.
References Foam::abort(), mapPolyMesh::cellMap(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, iter, newPointi, mapPolyMesh::nOldCells(), mapPolyMesh::nOldPoints(), mapPolyMesh::pointMap(), Foam::Pout, Foam::reorder(), mapPolyMesh::reverseCellMap(), mapPolyMesh::reversePointMap(), UList< T >::size(), and List< T >::transfer().
void subset (const labelList & pointMap, const labelList & faceMap, const labelList & cellMap)
Update local numbering for subsetted mesh.
Gets new-to-old maps. Not compatible with unrefinement.
Definition at line 4435 of file hexRef8.C.
void distribute (const mapDistributePolyMesh & map)
Update local numbering for mesh redistribution.
Definition at line 4518 of file hexRef8.C.
void checkMesh () const
Debug: Check coupled mesh for correctness.
Definition at line 4546 of file hexRef8.C.
Referenced by hexRef8::hexRef8().
void checkRefinementLevels (const label maxPointDiff, const labelList & pointsToCheck) const
Debug: Check 2:1 consistency across faces.
maxPointDiff==-1 : only check 2:1 across faces maxPointDiff!=-1 : check point-connected cells.
Gives problems after first splitting off inside mesher.
// Hanging points { // Any patches with points having only two edges.
boolList isHangingPoint(mesh_.nPoints(), false);
const polyBoundaryMesh& patches = mesh_.boundaryMesh();
forAll(patches, patchi) { const polyPatch& pp = patches[patchi];
const labelList& meshPoints = pp.meshPoints();
forAll(meshPoints, i) { label pointi = meshPoints[i];
const labelList& pEdges = mesh_.pointEdges()[pointi];
if (pEdges.size() == 2) { isHangingPoint[pointi] = true; } } }
syncTools::syncPointList (mesh_, isHangingPoint, andEqOp<bool>(), // only if all decide it is hanging point true, // null false // no separation);
//OFstream str(mesh_.time().path()/"hangingPoints.obj");
label nHanging = 0;
forAll(isHangingPoint, pointi) { if (isHangingPoint[pointi]) { nHanging++;
Pout<< "Hanging boundary point " << pointi << " at " << mesh_.points()[pointi] << endl; //meshTools::writeOBJ(str, mesh_.points()[pointi]); } }
if (returnReduce(nHanging, sumOp<label>()) > 0) { FatalErrorInFunction << "Detected a point used by two edges only (hanging point)" << nl << "This is not allowed" << abort(FatalError); } }
Definition at line 4755 of file hexRef8.C.
Referenced by hexRef8::hexRef8().
const Foam::cellShapeList & cellShapes () const
Utility: get hexes as cell shapes.
Definition at line 5010 of file hexRef8.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), forAll, Foam::nl, and Foam::Pout.
Foam::labelList getSplitPoints () const
Return the points at the centre of top-level split cells.
that can be unsplit.
Definition at line 5070 of file hexRef8.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, i, Foam::Pout, UList< T >::size(), and Foam::Zero.
Foam::labelList consistentUnrefinement (const labelList & pointsToUnrefine, const bool maxSet) const
Given proposed.
splitPoints to unrefine according to calculate any clashes (due to 2:1) and return ok list of points to unrefine. Either adds points to refine to set (maxSet = true) or removes points to refine (maxSet = false)
Definition at line 5274 of file hexRef8.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, i, j, Foam::Pout, Foam::reduce(), List< T >::set(), and syncTools::swapBoundaryFaceList().
void setUnrefinement (const labelList & splitPointLabels, polyTopoChange & meshMod)
Remove some refinement. Needs to be supplied output of.
consistentUnrefinement. Only call if undoable set. All 8 pointCells of a split point will be combined into the lowest numbered cell of those 8.
Definition at line 5497 of file hexRef8.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, i, j, Foam::min(), Foam::nl, IOobject::objectPath(), Foam::Pout, UList< T >::size(), HashTable< T, Key, Hash >::size(), and regIOobject::write().
void setInstance (const fileName & inst)
Definition at line 1729 of file hexRef8.C.
bool write (const bool valid = true) const
Force writing refinement+history to polyMesh directory.
Definition at line 5698 of file hexRef8.C.
References refinementHistory::removeFiles().
void removeFiles (const polyMesh & mesh) static
Helper: remove all relevant files from mesh instance.
Definition at line 5718 of file hexRef8.C.
References Foam::expressions::patchExpr::debug, DebugVar, Foam::exists(), polyMesh::facesInstance(), mesh, polyMesh::meshSubDir, refinementHistory::removeFiles(), and Foam::rm().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8.H
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8.C