OpenFOAM: boundBox Class Reference
boundBox Class Reference
A bounding box defined in terms of min/max extrema points.
Public Types
enum directionBit : direction { XDIR = 0x1, YDIR = 0x2, ZDIR = 0x4 }
Bits used for (x/y/z) direction encoding.
Public Member Functions
boundBox ()
Construct without any points - an inverted bounding box.
boundBox (const point &pt)
Construct a bounding box containing a single initial point.
boundBox (const point &min, const point &max)
Construct from components.
boundBox (const UList< point > &points, bool doReduce=true)
Construct as the bounding box of the given points.
boundBox (const tmp< pointField > &tpoints, bool doReduce=true)
Construct as the bounding box of the given temporary pointField.
boundBox (const UList< point > &points, const labelUList &indices, bool doReduce=true)
Construct bounding box as an indirect subset of the points.
template<unsigned N>
boundBox (const UList< point > &points, const FixedList< label, N > &indices, bool doReduce=true)
Construct bounding box as an indirect subset of the points.
boundBox (Istream &is)
Construct from Istream.
bool empty () const
Bounding box is inverted, contains no points.
bool valid () const
Bounding box is non-inverted.
const point & min () const
Minimum describing the bounding box.
const point & max () const
Maximum describing the bounding box.
point & min ()
Minimum describing the bounding box, non-const access.
point & max ()
Maximum describing the bounding box, non-const access.
point centre () const
The centre (midpoint) of the bounding box.
point midpoint () const
The midpoint (centre) of the bounding box. Identical to centre()
vector span () const
The bounding box span (from minimum to maximum)
scalar mag () const
The magnitude of the bounding box span.
scalar volume () const
The volume of the bound box.
scalar minDim () const
Smallest length/height/width dimension.
scalar maxDim () const
Largest length/height/width dimension.
scalar avgDim () const
Average length/height/width dimension.
label nDim () const
Count the number of positive, non-zero dimensions.
tmp< pointField > points () const
Corner points in an order corresponding to a 'hex' cell.
tmp< pointField > faceCentres () const
Face midpoints.
point faceCentre (const direction facei) const
Face centre of given face index.
void clear ()
Clear bounding box and make it an inverted box.
void add (const boundBox &bb)
Extend to include the second box.
void add (const point &pt)
Extend to include the point.
void add (const UList< point > &points)
Extend to include the points.
void add (const tmp< pointField > &tpoints)
Extend to include the points from the temporary point field.
template<unsigned N>
void add (const FixedList< point, N > &points)
Extend to include the points.
template<unsigned N>
void add (const UList< point > &points, const FixedList< label, N > &indices)
Extend to include a (subsetted) point field.
template<class IntContainer >
void add (const UList< point > &points, const IntContainer &indices)
Extend to include a (subsetted) point field.
void inflate (const scalar s)
Inflate box by factor*mag(span) in all dimensions.
void reduce ()
Parallel reduction of min/max values.
bool intersect (const boundBox &bb)
Intersection (union) with the second box.
bool intersects (const plane &pln) const
Does plane intersect this bounding box.
bool overlaps (const boundBox &bb) const
Overlaps/touches boundingBox?
bool overlaps (const point &centre, const scalar radiusSqr) const
Overlaps boundingSphere (centre + sqr(radius))?
bool contains (const point &pt) const
Contains point? (inside or on edge)
bool contains (const boundBox &bb) const
Fully contains other boundingBox?
bool containsInside (const point &pt) const
Contains point? (inside only)
bool contains (const UList< point > &points) const
Contains all points? (inside or on edge)
template<unsigned N>
bool contains (const UList< point > &points, const FixedList< label, N > &indices) const
Contains all of the (subsetted) points? (inside or on edge)
template<class IntContainer >
bool contains (const UList< point > &points, const IntContainer &indices) const
Contains all of the (subsetted) points? (inside or on edge)
bool containsAny (const UList< point > &points) const
Contains any of the points? (inside or on edge)
template<unsigned N>
bool containsAny (const UList< point > &points, const FixedList< label, N > &indices) const
Contains any of the (subsetted) points? (inside or on edge)
template<class IntContainer >
bool containsAny (const UList< point > &points, const IntContainer &indices) const
Contains any of the (subsetted) points? (inside or on edge)
point nearest (const point &pt) const
Return the nearest point on the boundBox to the supplied point.
void operator+= (const boundBox &bb)
Extend box to include the second box, as per the add() method.
Static Public Attributes
static const boundBox greatBox
A large boundBox: min/max == -/+ ROOTVGREAT.
static const boundBox invertedBox
A large inverted boundBox: min/max == +/- ROOTVGREAT.
static const faceList faces
Faces to point addressing, as per a 'hex' cell.
static const FixedList< vector, 6 > faceNormals
The unit normal per face.
Friends
Istream & operator>> (Istream &is, boundBox &bb)
Ostream & operator<< (Ostream &os, const boundBox &bb)
Detailed Description
A bounding box defined in terms of min/max extrema points.
Note
When a bounding box is created without any points, it creates an inverted bounding box. Points can be added later and the bounding box will grow to include them.
Definition at line 57 of file boundBox.H.
Member Enumeration Documentation
enum directionBit : direction
Bits used for (x/y/z) direction encoding.
Enumerator
XDIR
1: x-direction (vector component 0)
YDIR
2: y-direction (vector component 1)
ZDIR
4: z-direction (vector component 2)
Definition at line 73 of file boundBox.H.
Constructor & Destructor Documentation
boundBox () inline
Construct without any points - an inverted bounding box.
Definition at line 26 of file boundBoxI.H.
boundBox (const point & pt) inline explicit
Construct a bounding box containing a single initial point.
Definition at line 33 of file boundBoxI.H.
boundBox (const point & min, const point & max) inline
Construct from components.
Definition at line 40 of file boundBoxI.H.
boundBox (const UList< point > & points, bool doReduce = true) explicit
Construct as the bounding box of the given points.
Does parallel communication (doReduce = true)
Definition at line 65 of file boundBox.C.
boundBox (const tmp< pointField > & tpoints, bool doReduce = true) explicit
Construct as the bounding box of the given temporary pointField.
Does parallel communication (doReduce = true)
Definition at line 78 of file boundBox.C.
References boundBox::reduce().
boundBox (const UList< point > & points, const labelUList & indices, bool doReduce = true)
Construct bounding box as an indirect subset of the points.
The indices could be from cell/face etc. Does parallel communication (doReduce = true)
Definition at line 92 of file boundBox.C.
References boundBox::reduce().
boundBox (const UList< point > & points, const FixedList< label, N > & indices, bool doReduce = true)
Construct bounding box as an indirect subset of the points.
The indices could be from edge/triFace etc. Does parallel communication (doReduce = true)
Definition at line 29 of file boundBoxTemplates.C.
References boundBox::add(), and boundBox::reduce().
boundBox (Istream & is) inline
Construct from Istream.
Definition at line 47 of file boundBoxI.H.
Member Function Documentation
bool empty () const inline
Bounding box is inverted, contains no points.
Definition at line 55 of file boundBoxI.H.
References Foam::operator>>().
bool valid () const inline
Bounding box is non-inverted.
Definition at line 69 of file boundBoxI.H.
Referenced by cuttingPlane::checkOverlap(), and cuttingSurfaceBase::checkOverlap().
const Foam::point & min () const inline
Minimum describing the bounding box.
Definition at line 84 of file boundBoxI.H.
Referenced by meshSearch::boundaryTree(), meshSearch::cellTree(), boundBox::containsInside(), voxelMeshSearch::fill(), dynamicIndexedOctree< Type >::findNearest(), indexedOctree< Type >::findNearest(), meshSearch::findNearestBoundaryFace(), boundaryMesh::getNearest(), Foam::operator!=(), and discreteSurface::update().
const Foam::point & max () const inline
Maximum describing the bounding box.
Definition at line 90 of file boundBoxI.H.
Referenced by meshSearch::boundaryTree(), meshSearch::cellTree(), boundBox::containsInside(), voxelMeshSearch::fill(), dynamicIndexedOctree< Type >::findNearest(), indexedOctree< Type >::findNearest(), meshSearch::findNearestBoundaryFace(), boundaryMesh::getNearest(), Foam::operator!=(), and discreteSurface::update().
Foam::point & min () inline
Minimum describing the bounding box, non-const access.
Definition at line 96 of file boundBoxI.H.
Foam::point & max () inline
Maximum describing the bounding box, non-const access.
Definition at line 102 of file boundBoxI.H.
Foam::point centre () const inline
The centre (midpoint) of the bounding box.
Definition at line 108 of file boundBoxI.H.
Foam::point midpoint () const inline
The midpoint (centre) of the bounding box. Identical to centre()
Definition at line 114 of file boundBoxI.H.
Foam::vector span () const inline
The bounding box span (from minimum to maximum)
Definition at line 120 of file boundBoxI.H.
Foam::scalar mag () const inline
The magnitude of the bounding box span.
Definition at line 126 of file boundBoxI.H.
Referenced by refinementFeatures::checkSizes(), and wallBoundedStreamLineParticle::move().
Foam::scalar volume () const inline
The volume of the bound box.
Definition at line 132 of file boundBoxI.H.
References Foam::mag().
Foam::scalar minDim () const inline
Smallest length/height/width dimension.
Definition at line 138 of file boundBoxI.H.
References Foam::cmptProduct().
Foam::scalar maxDim () const inline
Largest length/height/width dimension.
Definition at line 144 of file boundBoxI.H.
References Foam::cmptMin().
Foam::scalar avgDim () const inline
Average length/height/width dimension.
Definition at line 150 of file boundBoxI.H.
References Foam::cmptMax().
Referenced by boundaryMesh::getNearest().
Foam::label nDim () const inline
Count the number of positive, non-zero dimensions.
Returns
-1 if any dimensions are negative, 0 = 0D (point), 1 = 1D (line aligned with an axis), 2 = 2D (plane aligned with an axis), 3 = 3D (box)
Definition at line 156 of file boundBoxI.H.
References Foam::cmptAv().
Foam::tmp< Foam::pointField > points () const
Corner points in an order corresponding to a 'hex' cell.
Definition at line 111 of file boundBox.C.
Foam::tmp< Foam::pointField > faceCentres () const
Face midpoints.
Definition at line 129 of file boundBox.C.
Foam::point faceCentre (const direction facei) const
Face centre of given face index.
Definition at line 143 of file boundBox.C.
void clear () inline
Clear bounding box and make it an inverted box.
Definition at line 177 of file boundBoxI.H.
void add (const boundBox & bb) inline
Extend to include the second box.
Definition at line 184 of file boundBoxI.H.
Referenced by boundBox::boundBox(), triPoints::bounds(), and PatchTools::calcBounds().
void add (const point & pt) inline
Extend to include the point.
Definition at line 191 of file boundBoxI.H.
References Foam::max(), and Foam::min().
void add (const UList< point > & points) inline
Extend to include the points.
Definition at line 198 of file boundBoxI.H.
References Foam::max(), and Foam::min().
void add (const tmp< pointField > & tpoints) inline
Extend to include the points from the temporary point field.
Definition at line 207 of file boundBoxI.H.
References Foam::add(), and p.
void add (const FixedList< point, N > & points)
Extend to include the points.
Definition at line 50 of file boundBoxTemplates.C.
void add (const UList< point > & points, const FixedList< label, N > & indices)
Extend to include a (subsetted) point field.
The indices could be from edge/triFace etc.
Definition at line 63 of file boundBoxTemplates.C.
void add (const UList< point > & points, const IntContainer & indices)
Extend to include a (subsetted) point field.
Template Parameters
IntContainer A container with an iterator that dereferences to an label
Definition at line 88 of file boundBoxTemplates.C.
void inflate (const scalar s)
Inflate box by factor*mag(span) in all dimensions.
Definition at line 168 of file boundBox.C.
Referenced by surfaceFeatures::nearestSurfEdge().
void reduce ()
Parallel reduction of min/max values.
Definition at line 177 of file boundBox.C.
Referenced by boundBox::boundBox(), and distributedTriSurfaceMesh::distributedTriSurfaceMesh().
bool intersect (const boundBox & bb)
Intersection (union) with the second box.
The return value is true if the intersection is non-empty.
Definition at line 184 of file boundBox.C.
References Foam::reduce().
Referenced by sampledTriSurfaceMesh::update().
bool intersects (const plane & pln) const
Does plane intersect this bounding box.
There is an intersection if the plane segments the corner points
Note
the results are unreliable when plane coincides almost exactly with a box face
Definition at line 193 of file boundBox.C.
Referenced by cuttingPlane::checkOverlap().
bool overlaps (const boundBox & bb) const inline
Overlaps/touches boundingBox?
Definition at line 214 of file boundBoxI.H.
References Foam::add(), and tmp< T >::clear().
Referenced by cuttingSurfaceBase::checkOverlap(), indexedOctree< Type >::overlaps(), and searchableSphere::regions().
bool overlaps (const point & centre, const scalar radiusSqr) const inline
Overlaps boundingSphere (centre + sqr(radius))?
Definition at line 226 of file boundBoxI.H.
bool contains (const point & pt) const inline
Contains point? (inside or on edge)
Definition at line 264 of file boundBoxI.H.
Referenced by refinementFeatures::checkSizes().
bool contains (const boundBox & bb) const inline
Fully contains other boundingBox?
Definition at line 275 of file boundBoxI.H.
bool containsInside (const point & pt) const inline
Contains point? (inside only)
Definition at line 281 of file boundBoxI.H.
References boundBox::max(), and boundBox::min().
bool contains (const UList< point > & points) const
Contains all points? (inside or on edge)
Definition at line 223 of file boundBox.C.
bool contains (const UList< point > & points, const FixedList< label, N > & indices) const inline
Contains all of the (subsetted) points? (inside or on edge)
Definition at line 113 of file boundBoxTemplates.C.
bool contains (const UList< point > & points, const IntContainer & indices) const inline
Contains all of the (subsetted) points? (inside or on edge)
Template Parameters
IntContainer A container with an iterator that dereferences to an label
Definition at line 142 of file boundBoxTemplates.C.
bool containsAny (const UList< point > & points) const
Contains any of the points? (inside or on edge)
Definition at line 242 of file boundBox.C.
bool containsAny (const UList< point > & points, const FixedList< label, N > & indices) const inline
Contains any of the (subsetted) points? (inside or on edge)
Definition at line 171 of file boundBoxTemplates.C.
bool containsAny (const UList< point > & points, const IntContainer & indices) const inline
Contains any of the (subsetted) points? (inside or on edge)
Template Parameters
IntContainer A container with an iterator that dereferences to an label
Definition at line 204 of file boundBoxTemplates.C.
Foam::point nearest (const point & pt) const
Return the nearest point on the boundBox to the supplied point.
If point is inside the boundBox then the point is returned unchanged.
Definition at line 261 of file boundBox.C.
void operator+= (const boundBox & bb) inline
Extend box to include the second box, as per the add() method.
Definition at line 294 of file boundBoxI.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, boundBox & bb) friend
Ostream& operator<< (Ostream & os, const boundBox & bb) friend
Member Data Documentation
const Foam::boundBox greatBox static
A large boundBox: min/max == -/+ ROOTVGREAT.
Definition at line 83 of file boundBox.H.
const Foam::boundBox invertedBox static
A large inverted boundBox: min/max == +/- ROOTVGREAT.
Definition at line 88 of file boundBox.H.
Referenced by PatchTools::calcBounds(), and lumpedPointMovement::setBoundBox().
const Foam::faceList faces static
Faces to point addressing, as per a 'hex' cell.
Definition at line 93 of file boundBox.H.
const Foam::FixedList< Foam::vector, 6 > faceNormals static
The unit normal per face.
Definition at line 98 of file boundBox.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/boundBox/boundBox.H
src/OpenFOAM/meshes/boundBox/boundBox.C
src/OpenFOAM/meshes/boundBox/boundBoxI.H
src/OpenFOAM/meshes/boundBox/boundBoxTemplates.C