OpenFOAM: boundaryAdjointContribution Class Reference
boundaryAdjointContribution Class Reference abstract
Abstract base class for computing contributions of the objective functions to the adjoint boundary conditions.
Public Member Functions
TypeName ("boundaryAdjointContribution")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, boundaryAdjointContribution, dictionary,(const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch),(managerName, adjointSolverName, simulationType, patch))
boundaryAdjointContribution (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch)
Construct from components.
virtual ~boundaryAdjointContribution ()=default
Destructor.
virtual tmp< scalarField > pressureSource ()=0
virtual tmp< vectorField > velocitySource ()=0
virtual tmp< vectorField > tangentVelocitySource ()=0
virtual tmp< vectorField > normalVelocitySource ()=0
virtual tmp< scalarField > adjointTMVariable1Source ()
virtual tmp< scalarField > adjointTMVariable2Source ()
virtual tmp< scalarField > energySource ()=0
virtual tmp< scalarField > momentumDiffusion ()=0
virtual tmp< scalarField > laminarDiffusivity ()=0
virtual tmp< scalarField > thermalDiffusion ()=0
virtual tmp< scalarField > wallDistance ()=0
virtual tmp< scalarField > TMVariable1Diffusion ()
virtual tmp< scalarField > TMVariable2Diffusion ()
virtual tmp< scalarField > TMVariable1 ()
virtual tmp< scalarField > TMVariable2 ()
virtual const fvPatchVectorField & Ub () const =0
virtual const fvPatchScalarField & pb () const =0
virtual const fvsPatchScalarField & phib () const =0
virtual const fvPatchScalarField & turbulentDiffusivity () const =0
virtual const fvPatchVectorField & Uab () const =0
virtual const fvPatchScalarField & pab () const =0
virtual const fvsPatchScalarField & phiab () const =0
virtual const word primalSolverName () const =0
virtual const word adjointSolverName () const =0
Static Public Member Functions
static autoPtr
< boundaryAdjointContribution > New (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch)
Return a reference to the selected turbulence model.
Protected Attributes
const fvPatch & patch_
Detailed Description
Abstract base class for computing contributions of the objective functions to the adjoint boundary conditions.
Source files
boundaryAdjointContribution.H
boundaryAdjointContribution.C
Definition at line 54 of file boundaryAdjointContribution.H.
Constructor & Destructor Documentation
boundaryAdjointContribution (const word & managerName, const word & adjointSolverName, const word & simulationType, const fvPatch & patch)
Construct from components.
Definition at line 38 of file boundaryAdjointContribution.C.
virtual ~boundaryAdjointContribution () virtual default
Destructor.
Member Function Documentation
TypeName ("boundaryAdjointContribution")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , boundaryAdjointContribution , dictionary , (const word &managerName, const word &adjointSolverName, const word &simulationType, const fvPatch &patch) , (managerName, adjointSolverName, simulationType, patch))
autoPtr< boundaryAdjointContribution > New (const word & managerName, const word & adjointSolverName, const word & simulationType, const fvPatch & patch) static
Return a reference to the selected turbulence model.
Definition at line 52 of file boundaryAdjointContribution.C.
Referenced by boundaryAdjointContributionIncompressible::sumContributions().
virtual tmp<scalarField> pressureSource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual tmp<vectorField> velocitySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual tmp<vectorField> tangentVelocitySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual tmp<vectorField> normalVelocitySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
tmp< scalarField > adjointTMVariable1Source () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 87 of file boundaryAdjointContribution.C.
tmp< scalarField > adjointTMVariable2Source () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 93 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, fvPatch::size(), and Foam::Zero.
virtual tmp<scalarField> energySource () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual tmp<scalarField> momentumDiffusion () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual tmp<scalarField> laminarDiffusivity () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual tmp<scalarField> thermalDiffusion () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual tmp<scalarField> wallDistance () pure virtual
Implemented in boundaryAdjointContributionIncompressible.
tmp< scalarField > TMVariable1Diffusion () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 99 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, fvPatch::size(), and Foam::Zero.
tmp< scalarField > TMVariable2Diffusion () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 105 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, fvPatch::size(), and Foam::Zero.
tmp< scalarField > TMVariable1 () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 111 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, fvPatch::size(), and Foam::Zero.
tmp< scalarField > TMVariable2 () virtual
Reimplemented in boundaryAdjointContributionIncompressible.
Definition at line 117 of file boundaryAdjointContribution.C.
References tmp< T >::New(), boundaryAdjointContribution::patch_, fvPatch::size(), and Foam::Zero.
virtual const fvPatchVectorField& Ub () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const fvPatchScalarField& pb () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const fvsPatchScalarField& phib () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const fvPatchScalarField& turbulentDiffusivity () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const fvPatchVectorField& Uab () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const fvPatchScalarField& pab () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const fvsPatchScalarField& phiab () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const word primalSolverName () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
virtual const word adjointSolverName () const pure virtual
Implemented in boundaryAdjointContributionIncompressible.
Member Data Documentation
const fvPatch& patch_ protected
Definition at line 78 of file boundaryAdjointContribution.H.
Referenced by boundaryAdjointContribution::adjointTMVariable2Source(), boundaryAdjointContributionIncompressible::pab(), boundaryAdjointContributionIncompressible::pb(), boundaryAdjointContributionIncompressible::phiab(), boundaryAdjointContributionIncompressible::phib(), boundaryAdjointContributionIncompressible::primalSolverName(), boundaryAdjointContributionIncompressible::sumContributions(), boundaryAdjointContribution::TMVariable1(), boundaryAdjointContribution::TMVariable1Diffusion(), boundaryAdjointContribution::TMVariable2(), boundaryAdjointContribution::TMVariable2Diffusion(), and boundaryAdjointContributionIncompressible::turbulentDiffusivity().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/boundaryAdjointContributions/boundaryAdjointContribution/boundaryAdjointContribution.H
src/optimisation/adjointOptimisation/adjoint/boundaryAdjointContributions/boundaryAdjointContribution/boundaryAdjointContribution.C