OpenFOAM: MinMax< T > Class Template Reference
MinMax< T > Class Template Reference
A min/max value pair with additional methods. In addition to conveniently storing values, it can be used for logic operations or to modify data. A few global functions and functors are also provided.
Public Types
typedef T value_type
The value type the MinMax represents.
typedef pTraits< T >::cmptType cmptType
Component type.
Public Types inherited from Tuple2< T, T >
typedef T first_type
Type of member first, the first template parameter (T1)
typedef T second_type
Type of member second, the second template parameter (T2)
Public Member Functions
MinMax ()
Construct inverted range.
MinMax (const T &minVal, const T &maxVal)
Copy construct from components.
MinMax (const std::pair< T, T > &range)
Copy construct from components.
MinMax (const Pair< T > &range)
Copy construct from components.
MinMax (const zero)
Construct with a single zero value.
MinMax (const T &val)
Construct with a single initial value.
MinMax (const UList< T > &vals)
Construct from list of values.
const T & min () const noexcept
The min value (first)
T & min () noexcept
The min value (first)
const T & max () const noexcept
The max value (second)
T & max () noexcept
The max value (second)
T centre () const
The min/max average value.
T span () const
The min to max span. Zero if the range is invalid.
scalar mag () const
The magnitude of the min to max span. Zero if the range is invalid.
bool empty () const
Range is empty if it is inverted.
bool valid () const
Range is valid if it is not inverted.
void clear ()
Reset to an invalid, inverted range.
bool intersect (const MinMax< T > &b)
Intersect (union) with the second range.
bool overlaps (const MinMax< T > &b) const
Test if the ranges overlap.
int compare (const T &val) const
Compares the min/max range with the specified value.
bool contains (const T &val) const
True if the value is within the range.
const T & clip (const T &val) const
If out of range, return the respective min/max limits, otherwise return the value itself.
bool inplaceClip (T &val) const
Inplace clip value by the min/max limits.
MinMax< T > & add (const MinMax &other)
Extend the range to include the other min/max range.
MinMax< T > & add (const T &val)
Include the value into the range.
MinMax< T > & add (const UList< T > &vals)
Include the values into the range.
bool operator() (const T &val) const
Identical to contains(), for use as a predicate.
MinMax< T > & operator+= (const MinMax< T > &b)
Extend min/max range to include other range.
MinMax< T > & operator+= (const T &val)
Extend min/max range to include value.
MinMax< T > & operator+= (const UList< T > &vals)
Extend min/max range to include all values.
MinMax< T > & operator*= (const scalar &s)
Multiply range by scalar factor.
MinMax< T > & operator/= (const scalar &s)
Divide range by scalar factor.
Public Member Functions inherited from Tuple2< T, T >
Tuple2 ()=default
Construct null.
Tuple2 (const T &f, const T &s)
Copy construct from components.
Tuple2 (T &&f, T &&s)
Move construct from components.
Tuple2 (const std::pair< T, T > &vals)
Copy construct from std::pair.
Tuple2 (std::pair< T, T > &&vals)
Move construct from std::pair.
Tuple2 (Istream &is)
Construct from Istream.
const T & first () const noexcept
Return first.
T & first () noexcept
Return first.
const T & second () const noexcept
Return second.
T & second () noexcept
Return second.
Static Public Member Functions
static MinMax< T > ge (const T &minVal)
A semi-infinite range from minVal to the type max.
static MinMax< T > le (const T &maxVal)
A semi-infinite range from type min to maxVal.
static MinMax< T > zero_one ()
A 0-1 range corresponding to the pTraits zero, one.
Detailed Description
template<class T>
class Foam::MinMax< T >
A min/max value pair with additional methods. In addition to conveniently storing values, it can be used for logic operations or to modify data. A few global functions and functors are also provided.
Examples of use.
Determine min/max limits from a List of values:
List<scalar> values = ...;
// on construction
MinMax<scalar> range(values);
range.clear();
range += val;
// global minMax() function
Info<< minMax(values) << nl;
General comparsion operations
scalar val;
if (val < range) ... value is below range min
if (range.contains(val)) ... value within range
if (range.compare(val) > 0) ... value is above range max
if (range(val)) ... value within range - as predicate
Since the range has a predicate form, it can be used as a filter method. For example,
Info<< "values in range: " << subsetList(values, range) << nl;
boolList mask = ListOps::create<bool>(values, range);
Info<< "values values in range " << mask << nl;
One particular advantage offered by MinMax is to clip or limit values to a particular range. For example,
scalarMinMax range(lower, upper);
scalar val;
val = range.clip(val)    .. return clip values
// vs.
val = min(max(value, lower, upper))
Or when working on lists, the values can be limited in a single pass of the data without intermediate memory allocation.
scalarField values = ...;
for (scalar& val : values)
{
    range.inplaceClip(val);
}
// vs.
values = min(max(values, lower, upper))
Definition at line 72 of file HashSet.H.
Member Typedef Documentation
typedef T value_type
The value type the MinMax represents.
Definition at line 130 of file MinMax.H.
typedef pTraits<T>::cmptType cmptType
Component type.
Definition at line 135 of file MinMax.H.
Constructor & Destructor Documentation
MinMax () inline
Construct inverted range.
Definition at line 47 of file MinMaxI.H.
MinMax (const T & minVal, const T & maxVal) inline
Copy construct from components.
Definition at line 54 of file MinMaxI.H.
MinMax (const std::pair< T, T > & range) inline
Copy construct from components.
Definition at line 61 of file MinMaxI.H.
MinMax (const Pair< T > & range) inline
Copy construct from components.
Definition at line 68 of file MinMaxI.H.
MinMax (const zero) inline explicit
Construct with a single zero value.
Definition at line 75 of file MinMaxI.H.
MinMax (const T & val) inline explicit
Construct with a single initial value.
Definition at line 82 of file MinMaxI.H.
MinMax (const UList< T > & vals) inline explicit
Construct from list of values.
Definition at line 89 of file MinMaxI.H.
Member Function Documentation
Foam::MinMax< T > ge (const T & minVal) inline static
A semi-infinite range from minVal to the type max.
Definition at line 24 of file MinMaxI.H.
Foam::MinMax< T > le (const T & maxVal) inline static
A semi-infinite range from type min to maxVal.
Definition at line 31 of file MinMaxI.H.
Foam::MinMax< T > zero_one () inline static
A 0-1 range corresponding to the pTraits zero, one.
Definition at line 38 of file MinMaxI.H.
const T & min () const inline noexcept
The min value (first)
Definition at line 100 of file MinMaxI.H.
Referenced by MinMax< T >::compare(), Foam::minMaxMag(), minMaxMagEqOp< T >::operator()(), and Foam::rangex().
T & min () inline noexcept
The min value (first)
Definition at line 107 of file MinMaxI.H.
const T & max () const inline noexcept
The max value (second)
Definition at line 114 of file MinMaxI.H.
Referenced by MinMax< T >::compare(), Foam::minMaxMag(), minMaxMagEqOp< T >::operator()(), and Foam::rangex().
T & max () inline noexcept
The max value (second)
Definition at line 121 of file MinMaxI.H.
T centre () const inline
The min/max average value.
Definition at line 128 of file MinMaxI.H.
T span () const inline
The min to max span. Zero if the range is invalid.
Definition at line 136 of file MinMaxI.H.
References Foam::max(), and Foam::min().
Foam::scalar mag () const inline
The magnitude of the min to max span. Zero if the range is invalid.
Definition at line 143 of file MinMaxI.H.
References Foam::max(), Foam::min(), and Foam::Zero.
Referenced by Foam::mag().
bool empty () const inline
Range is empty if it is inverted.
Definition at line 150 of file MinMaxI.H.
References Foam::mag().
bool valid () const inline
Range is valid if it is not inverted.
Definition at line 157 of file MinMaxI.H.
References Foam::max(), and Foam::min().
Referenced by x3dWriter::writeTemplate(), and x3dWriter::x3dWriter().
void clear () inline
Reset to an invalid, inverted range.
Definition at line 164 of file MinMaxI.H.
References Foam::max(), and Foam::min().
bool intersect (const MinMax< T > & b) inline
Intersect (union) with the second range.
Returns
True if the resulting intersection is non-empty.
Definition at line 172 of file MinMaxI.H.
References Foam::max(), and Foam::min().
bool overlaps (const MinMax< T > & b) const inline
Test if the ranges overlap.
Definition at line 182 of file MinMaxI.H.
int compare (const T & val) const inline
Compares the min/max range with the specified value.
Returns
0: value is within the range, or range is invalid
-1: range (max) is less than the value
+1: range (min) is greater than value
Definition at line 190 of file MinMaxI.H.
References MinMax< T >::max(), and MinMax< T >::min().
Referenced by Foam::operator<=(), and Foam::operator>().
bool contains (const T & val) const inline
True if the value is within the range.
Definition at line 209 of file MinMaxI.H.
const T & clip (const T & val) const inline
If out of range, return the respective min/max limits, otherwise return the value itself.
If the range is invalid, always return the value.
Definition at line 216 of file MinMaxI.H.
Referenced by Foam::clip(), and clipOp< T >::operator()().
bool inplaceClip (T & val) const inline
Inplace clip value by the min/max limits.
Returns
True if clipping was applied.
Definition at line 235 of file MinMaxI.H.
Foam::MinMax< T > & add (const MinMax< T > & other) inline
Extend the range to include the other min/max range.
Definition at line 256 of file MinMaxI.H.
Referenced by Foam::minMaxMag(), minMaxOp< T >::operator()(), and minMaxMagOp< T >::operator()().
Foam::MinMax< T > & add (const T & val) inline
Include the value into the range.
Definition at line 265 of file MinMaxI.H.
Foam::MinMax< T > & add (const UList< T > & vals) inline
Include the values into the range.
Definition at line 274 of file MinMaxI.H.
bool operator() (const T & val) const inline
Identical to contains(), for use as a predicate.
Definition at line 287 of file MinMaxI.H.
Foam::MinMax< T > & operator+= (const MinMax< T > & b) inline
Extend min/max range to include other range.
Can be used in a reduction operation.
Definition at line 325 of file MinMaxI.H.
Foam::MinMax< T > & operator+= (const T & val) inline
Extend min/max range to include value.
Definition at line 332 of file MinMaxI.H.
References Foam::add().
Foam::MinMax< T > & operator+= (const UList< T > & vals) inline
Extend min/max range to include all values.
Definition at line 339 of file MinMaxI.H.
References Foam::add().
Foam::MinMax< T > & operator*= (const scalar & s) inline
Multiply range by scalar factor.
Definition at line 346 of file MinMaxI.H.
References Foam::add().
Foam::MinMax< T > & operator/= (const scalar & s) inline
Divide range by scalar factor.
Definition at line 355 of file MinMaxI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashSet/HashSet.H
src/OpenFOAM/primitives/ranges/MinMax/MinMax.H
src/OpenFOAM/primitives/ranges/MinMax/MinMaxI.H