OpenFOAM: extendedFaceToCellStencil Class Reference
extendedFaceToCellStencil Class Reference
Note: transformations on coupled patches not supported. Problem is the positions of cells reachable through these patches.
Public Member Functions
extendedFaceToCellStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, List< List< Type >> &stencilFld)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar >> &stencilWeights)
Static Public Member Functions
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvsPatchField, surfaceMesh > &fld, List< List< T >> &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar >> &stencilWeights)
Sum surface field contributions to create cell values.
Protected Attributes
const polyMesh & mesh_
Detailed Description
Note: transformations on coupled patches not supported. Problem is the positions of cells reachable through these patches.
Source files
extendedFaceToCellStencil.H
extendedFaceToCellStencil.C
extendedFaceToCellStencilTemplates.C
Definition at line 52 of file extendedFaceToCellStencil.H.
Constructor & Destructor Documentation
extendedFaceToCellStencil (const polyMesh & mesh) explicit
Construct from mesh.
Definition at line 27 of file extendedFaceToCellStencil.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, patchIdentifier::name(), coupledPolyPatch::parallel(), patches, and coupledPolyPatch::separated().
Member Function Documentation
static void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< T, fvsPatchField, surfaceMesh > & fld, List< List< T >> & stencilFld) static
Use map to get the data into stencil order.
Referenced by extendedCentredFaceToCellStencil::stencil().
static tmp<GeometricField<Type, fvPatchField, volMesh> > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, const List< List< scalar >> & stencilWeights) static
Sum surface field contributions to create cell values.
Referenced by extendedCentredFaceToCellStencil::collectData().
void collectData (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, List< List< Type >> & stencilFld)
Definition at line 27 of file extendedFaceToCellStencilTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), mapDistributeBase::constructSize(), mapDistribute::distribute(), forAll, i, fvsPatchField< Type >::patch(), List< T >::setSize(), UList< T >::size(), and Foam::Zero.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, const List< List< scalar >> & stencilWeights)
Definition at line 78 of file extendedFaceToCellStencilTemplates.C.
Member Data Documentation
const polyMesh& mesh_ protected
Definition at line 58 of file extendedFaceToCellStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedFaceToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedFaceToCellStencil.C
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedFaceToCellStencilTemplates.C