OpenFOAM: aspectRatioModel Class Reference
aspectRatioModel Class Reference abstract
Public Member Functions
TypeName ("aspectRatioModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, aspectRatioModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
aspectRatioModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and an ordered phase pair.
virtual ~aspectRatioModel ()
Destructor.
virtual tmp< volScalarField > E () const =0
Aspect ratio.
TypeName ("aspectRatioModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, aspectRatioModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
aspectRatioModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and an ordered phase pair.
virtual ~aspectRatioModel ()
Destructor.
virtual tmp< volScalarField > E () const =0
Aspect ratio.
Static Public Member Functions
static autoPtr< aspectRatioModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< aspectRatioModel > New (const dictionary &dict, const phasePair &pair)
Protected Attributes
const phasePair & pair_
Phase pair.
Detailed Description
Source files
aspectRatioModel.H
aspectRatioModel.C
newAspectRatioModel.C
Source files
aspectRatioModel.H
aspectRatioModel.C
newAspectRatioModel.C
Definition at line 50 of file aspectRatioModel.H.
Constructor & Destructor Documentation
aspectRatioModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and an ordered phase pair.
Definition at line 36 of file aspectRatioModel.C.
~aspectRatioModel () virtual
Destructor.
Definition at line 47 of file aspectRatioModel.C.
aspectRatioModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and an ordered phase pair.
virtual ~aspectRatioModel () virtual
Destructor.
Member Function Documentation
TypeName ("aspectRatioModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , aspectRatioModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::aspectRatioModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 29 of file newAspectRatioModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volScalarField> E () const pure virtual
Aspect ratio.
Implemented in Wellek, Wellek, TomiyamaAspectRatio, TomiyamaAspectRatio, VakhrushevEfremov, constantAspectRatio, VakhrushevEfremov, and constantAspectRatio.
TypeName ("aspectRatioModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , aspectRatioModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
static autoPtr<aspectRatioModel> New (const dictionary & dict, const phasePair & pair) static
virtual tmp<volScalarField> E () const pure virtual
Aspect ratio.
Implemented in Wellek, Wellek, TomiyamaAspectRatio, TomiyamaAspectRatio, VakhrushevEfremov, constantAspectRatio, VakhrushevEfremov, and constantAspectRatio.
Member Data Documentation
const phasePair & pair_ protected
Phase pair.
Definition at line 59 of file aspectRatioModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialModels/aspectRatioModels/aspectRatioModel/aspectRatioModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/interfacialModels/aspectRatioModels/aspectRatioModel/aspectRatioModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialModels/aspectRatioModels/aspectRatioModel/aspectRatioModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialModels/aspectRatioModels/aspectRatioModel/newAspectRatioModel.C