OpenFOAM: updateMethod Class Reference
updateMethod Class Reference abstract
Abstract base class for optimisation methods.
Public Member Functions
TypeName ("updateMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, updateMethod, dictionary,(const fvMesh &mesh, const dictionary &dict),(mesh, dict))
updateMethod (const fvMesh &mesh, const dictionary &dict)
Construct from components.
virtual ~updateMethod ()=default
Destructor.
void setObjectiveDeriv (const scalarField &derivs)
Set objective derivative.
void setConstraintDeriv (const PtrList< scalarField > &derivs)
Set constraints derivative.
void setObjectiveValue (const scalar value)
Set constraints derivative.
void setConstraintValues (const scalarField &values)
Set constraints derivative.
void setStep (const scalar eta)
Set step for optimisation methods.
void setGlobalSum (const bool useGlobalSum)
Set globalSum variable.
virtual void computeCorrection ()=0
Return the correction of the design variables.
scalarField & returnCorrection ()
Return the correction of the design variables.
void writeCorrection ()
virtual scalar computeMeritFunction ()
Compute merit function. Could be different than the objective in the presence of constraints.
virtual scalar meritFunctionDirectionalDerivative ()
Directional derivative of the merit function, in the direction of the correction. Could be different than the objective directional derivative in the presence of constraints.
bool & initialEtaSet ()
Return whether initial eta was set.
virtual void updateOldCorrection (const scalarField &oldCorrection)
Update old correction. useful for quasi-newton methods coupled with line search.
virtual void write ()
Write usefull quantities to files.
Static Public Member Functions
static autoPtr< updateMethod > New (const fvMesh &mesh, const dictionary &dict)
Return a reference to the selected turbulence model.
Protected Member Functions
const scalarField leftMult (const scalarField &, const SquareMatrix< scalar > &)
const scalarField rightMult (const SquareMatrix< scalar > &, const scalarField &)
SquareMatrix< scalar > outerProd (const scalarField &, const scalarField &)
SquareMatrix< scalar > inv (SquareMatrix< scalar > A)
scalar globalSum (const scalarField &field)
Compute either global or local sum, based on globalSum flag.
scalar globalSum (tmp< scalarField > &tfield)
Compute either global or local sum, based on globalSum flag.
dictionary coeffsDict ()
Return optional dictionary with parameters specific to each method.
Protected Attributes
const fvMesh & mesh_
const dictionary dict_
IOdictionary optMethodIODict_
Used to output values useful for continuation runs.
scalarField objectiveDerivatives_
Derivatives of the objective functions.
PtrList< scalarField > constraintDerivatives_
Derivatives of the constraints.
scalar objectiveValue_
Objective value.
scalarField cValues_
Constraint values.
scalarField correction_
Design variables correction.
scalarField cumulativeCorrection_
Cumulative design variables correction throughout the optimisation loop.
scalar eta_
Step multiplying the correction.
bool initialEtaSet_
Is initially set?
word correctionFolder_
Folder storing the corrections to file.
bool globalSum_
Whether to use gSum or sum in the inner products.
Detailed Description
Abstract base class for optimisation methods.
Source files
updateMethod.H
updateMethod.C
Definition at line 50 of file updateMethod.H.
Constructor & Destructor Documentation
updateMethod (const fvMesh & mesh, const dictionary & dict)
Construct from components.
Definition at line 196 of file updateMethod.C.
References updateMethod::correctionFolder_, updateMethod::eta_, updateMethod::initialEtaSet_, UPstream::master(), Foam::mkDir(), updateMethod::optMethodIODict_, and dictionary::readIfPresent().
virtual ~updateMethod () virtual default
Destructor.
Member Function Documentation
const Foam::scalarField leftMult (const scalarField & s, const SquareMatrix< scalar > & m) protected
Definition at line 38 of file updateMethod.C.
const Foam::scalarField rightMult (const SquareMatrix< scalar > & m, const scalarField & s) protected
Definition at line 65 of file updateMethod.C.
Foam::SquareMatrix< Foam::scalar > outerProd (const scalarField & a, const scalarField & b) protected
Definition at line 92 of file updateMethod.C.
Foam::SquareMatrix< Foam::scalar > inv (SquareMatrix< scalar > A) protected
LU decomposition of A
Definition at line 118 of file updateMethod.C.
Foam::scalar globalSum (const scalarField & field) protected
Compute either global or local sum, based on globalSum flag.
Definition at line 170 of file updateMethod.C.
Foam::scalar globalSum (tmp< scalarField > & tfield) protected
Compute either global or local sum, based on globalSum flag.
Definition at line 185 of file updateMethod.C.
Foam::dictionary coeffsDict () protected
Return optional dictionary with parameters specific to each method.
Definition at line 249 of file updateMethod.C.
TypeName ("updateMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , updateMethod , dictionary , (const fvMesh &mesh, const dictionary &dict) , (mesh, dict))
Foam::autoPtr< Foam::updateMethod > New (const fvMesh & mesh, const dictionary & dict) static
Return a reference to the selected turbulence model.
Definition at line 258 of file updateMethod.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, and mesh.
void setObjectiveDeriv (const scalarField & derivs)
Set objective derivative.
Definition at line 286 of file updateMethod.C.
void setConstraintDeriv (const PtrList< scalarField > & derivs)
Set constraints derivative.
Definition at line 293 of file updateMethod.C.
void setObjectiveValue (const scalar value)
Set constraints derivative.
Definition at line 301 of file updateMethod.C.
void setConstraintValues (const scalarField & values)
Set constraints derivative.
Definition at line 307 of file updateMethod.C.
References value().
void setStep (const scalar eta)
Set step for optimisation methods.
Definition at line 313 of file updateMethod.C.
References Foam::HashTableOps::values().
void setGlobalSum (const bool useGlobalSum)
Set globalSum variable.
Should be set by the optimisationType owining the updateMethod
Definition at line 319 of file updateMethod.C.
virtual void computeCorrection () pure virtual
Return the correction of the design variables.
Implemented in SQP, LBFGS, DBFGS, BFGS, SR1, conjugateGradient, constrainedOptimisationMethod, constraintProjection, and steepestDescent.
Foam::scalarField & returnCorrection ()
Return the correction of the design variables.
const scalarField& returnCorrection() const;
Return the correction of the design variables
Definition at line 325 of file updateMethod.C.
void writeCorrection ()
Definition at line 332 of file updateMethod.C.
Foam::scalar computeMeritFunction () virtual
Compute merit function. Could be different than the objective in the presence of constraints.
Reimplemented in SQP.
Definition at line 366 of file updateMethod.C.
Foam::scalar meritFunctionDirectionalDerivative () virtual
Directional derivative of the merit function, in the direction of the correction. Could be different than the objective directional derivative in the presence of constraints.
Reimplemented in SQP.
Definition at line 372 of file updateMethod.C.
bool & initialEtaSet ()
Return whether initial eta was set.
Definition at line 378 of file updateMethod.C.
References Foam::sum().
void updateOldCorrection (const scalarField & oldCorrection) virtual
Update old correction. useful for quasi-newton methods coupled with line search.
Reimplemented in SQP, LBFGS, DBFGS, BFGS, SR1, and conjugateGradient.
Definition at line 385 of file updateMethod.C.
Referenced by SR1::write(), BFGS::write(), DBFGS::write(), LBFGS::write(), and SQP::write().
void write () virtual
Write usefull quantities to files.
Reimplemented in SQP, LBFGS, DBFGS, BFGS, SR1, and conjugateGradient.
Definition at line 393 of file updateMethod.C.
Member Data Documentation
const fvMesh& mesh_ protected
Definition at line 56 of file updateMethod.H.
const dictionary dict_ protected
Definition at line 58 of file updateMethod.H.
IOdictionary optMethodIODict_ protected
Used to output values useful for continuation runs.
Definition at line 63 of file updateMethod.H.
Referenced by updateMethod::updateMethod().
scalarField objectiveDerivatives_ protected
Derivatives of the objective functions.
Definition at line 68 of file updateMethod.H.
PtrList<scalarField> constraintDerivatives_ protected
Derivatives of the constraints.
Definition at line 73 of file updateMethod.H.
scalar objectiveValue_ protected
Objective value.
Definition at line 78 of file updateMethod.H.
scalarField cValues_ protected
Constraint values.
Definition at line 83 of file updateMethod.H.
scalarField correction_ protected
Design variables correction.
Definition at line 88 of file updateMethod.H.
scalarField cumulativeCorrection_ protected
Cumulative design variables correction throughout the optimisation loop.
Definition at line 94 of file updateMethod.H.
scalar eta_ protected
Step multiplying the correction.
Definition at line 99 of file updateMethod.H.
Referenced by updateMethod::updateMethod().
bool initialEtaSet_ protected
Is initially set?
Definition at line 104 of file updateMethod.H.
Referenced by updateMethod::updateMethod().
word correctionFolder_ protected
Folder storing the corrections to file.
For some optimisation methods with a very high number of design variables (e.g. topology), it doesn't make much sense to write all updates in the updateMethodDict. Hence, a separate file is used to write the corrections, in case they are needed for post-processing
Definition at line 115 of file updateMethod.H.
Referenced by updateMethod::updateMethod().
bool globalSum_ protected
Whether to use gSum or sum in the inner products.
Definition at line 120 of file updateMethod.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/optimisation/updateMethod/updateMethod/updateMethod.H
src/optimisation/adjointOptimisation/adjoint/optimisation/updateMethod/updateMethod/updateMethod.C