OpenFOAM: UOPstream Class Reference
UOPstream Class Reference
Output inter-processor communications stream operating on external buffer.
Public Member Functions
UOPstream (const commsTypes commsType, const int toProcNo, DynamicList< char > &sendBuf, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool sendAtDestruct=true, streamFormat format=BINARY, versionNumber version=currentVersion)
Construct given process index to send to and optional buffer size,.
UOPstream (const int toProcNo, PstreamBuffers &buffers)
Construct given buffers.
~UOPstream ()
Destructor.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
virtual bool write (const token &tok)
Write token to stream or otherwise handle it.
virtual Ostream & write (const char c)
Write single character. Whitespace is suppressed.
virtual Ostream & write (const char *str)
Write the word-characters of a character string.
virtual Ostream & write (const word &str)
Write word.
virtual Ostream & write (const string &str)
Write string.
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t val)
Write int32_t as a label.
virtual Ostream & write (const int64_t val)
Write int64_t as a label.
virtual Ostream & write (const floatScalar val)
Write floatScalar.
virtual Ostream & write (const doubleScalar val)
Write doubleScalar.
virtual Ostream & write (const char *data, std::streamsize count)
Write binary block with 8-byte alignment.
virtual Ostream & writeRaw (const char *data, std::streamsize count)
Low-level raw binary output.
virtual bool beginRawWrite (std::streamsize count)
Begin marker for low-level raw binary output.
virtual bool endRawWrite ()
End marker for low-level raw binary output.
virtual void indent ()
Add indentation characters.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual char fill () const
Get the current padding character.
virtual char fill (const char)
Set padding character for formatted field up to field width.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field.
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field.
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
void print (Ostream &os) const
Print description of IOstream to Ostream.
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct and set stream status.
virtual ~Ostream ()=default
Destructor.
virtual Ostream & write (const keyType &kw)
Write keyType.
unsigned short indentSize () const
Return indent level.
unsigned short & indentSize ()
Access to indent size.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Increment the indent level.
void decrIndent ()
Decrement the indent level.
virtual Ostream & writeKeyword (const keyType &kw)
Write the keyword followed by an appropriate indentation.
virtual Ostream & beginBlock (const keyType &kw)
Write begin block group with the given name.
virtual Ostream & beginBlock ()
Write begin block group without a name.
virtual Ostream & endBlock ()
Write end block group.
virtual Ostream & endEntry ()
Write end entry (';') followed by newline.
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
Write a keyword/value entry.
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Write a keyword/value entry only when the two values differ.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (const IOstreamOption option)
Construct with specified stream option.
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct with format, version.
virtual ~IOstream ()=default
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
unsigned labelByteSize () const
The label byte-size associated with the stream.
unsigned scalarByteSize () const
The scalar byte-size associated with the stream.
void setLabelByteSize (unsigned nbytes)
Set the label byte-size associated with the stream.
void setScalarByteSize (unsigned nbytes)
Set the scalar byte-size associated with the stream.
template<class T = label>
std::enable_if
< std::is_integral< T >::value,
bool >::type checkLabelSize () const
Check if the label byte-size associated with the stream is the same as the given type.
template<class T = scalar>
std::enable_if
< std::is_floating_point< T >
::value, bool >::type checkScalarSize () const
Check if the scalar byte-size associated with the stream is the same as the given type.
label lineNumber () const
Const access to the current stream line number.
label & lineNumber ()
Non-const access to the current stream line number.
label lineNumber (const label num)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
void print (Ostream &os, const int streamState) const
Print information about the stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from IOstreamOption
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Static Public Member Functions
static bool write (const commsTypes commsType, const int toProcNo, const char *buf, const std::streamsize bufSize, const int tag=UPstream::msgType(), const label communicator=0)
Write given buffer to given processor.
Static Public Member Functions inherited from UPstream
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in worldComm) given communicator and procssor.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor number) (= reverse of baseProcNo)
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number and communicator)
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library adds/requires on the command line.
static bool init (int &argc, char **&argv, const bool needsThread)
Initialisation function called from main.
static bool initNull ()
Special purpose initialisation function.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static bool haveThreads ()
Have support for threads.
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static constexpr int masterNo () noexcept
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (label communicator)
Process ID of given process index.
static constexpr int firstSlave () noexcept
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
static void allToAll (const labelUList &sendData, labelUList &recvData, const label communicator=0)
Exchange label with all processors (in the communicator).
static void allToAll (const char *sendData, const UList< int > &sendSizes, const UList< int > &sendOffsets, char *recvData, const UList< int > &recvSizes, const UList< int > &recvOffsets, const label communicator=0)
Exchange data with all processors (in the communicator)
static void gather (const char *sendData, int sendSize, char *recvData, const UList< int > &recvSizes, const UList< int > &recvOffsets, const label communicator=0)
Receive data from all processors on the master.
static void scatter (const char *sendData, const UList< int > &sendSizes, const UList< int > &sendOffsets, char *recvData, int recvSize, const label communicator=0)
Send data to all processors from the root of the communicator.
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision.
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Additional Inherited Members
Public Types inherited from UPstream
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
Enumeration for stream open/closed state.
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Static Public Attributes inherited from UPstream
static const Enum< commsTypes > commsTypeNames
Names of the communication types.
static bool floatTransfer
Should compact transfer be used in which floats replace doubles reducing the bandwidth requirement at the expense of some loss in accuracy.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear to tree.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static int maxCommsSize
Optional maximum message size (bytes)
static const int mpiBufferSize
MPI buffer-size (bytes)
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Static Public Attributes inherited from IOstream
static unsigned int precision_
Default precision.
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes inherited from UPstream
commsTypes commsType_
Communications type of this stream.
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
Number of spaces per indent level.
unsigned short indentLevel_ = 0
Current indent level.
Protected Attributes inherited from IOstream
streamAccess openClosed_
ios_base::iostate ioState_
unsigned short labelByteSize_
The label byte-size (could also be stored as byte)
unsigned short scalarByteSize_
The scalar byte-size (could also be stored as byte)
label lineNumber_
The file line.
Static Protected Attributes inherited from Ostream
static constexpr const
unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Static Protected Attributes inherited from IOstream
static fileName staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
Output inter-processor communications stream operating on external buffer.
Source files
UOPstream.H
UOPstream.C
Definition at line 53 of file UOPstream.H.
Constructor & Destructor Documentation
UOPstream (const commsTypes commsType, const int toProcNo, DynamicList< char > & sendBuf, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool sendAtDestruct = true, streamFormat format = BINARY, versionNumber version = currentVersion)
Construct given process index to send to and optional buffer size,.
write format and IO version
Definition at line 115 of file UOPstream.C.
UOPstream (const int toProcNo, PstreamBuffers & buffers)
Construct given buffers.
Definition at line 139 of file UOPstream.C.
~UOPstream ()
Destructor.
Definition at line 156 of file UOPstream.C.
Member Function Documentation
virtual ios_base::fmtflags flags () const inline virtual
Return flags of output stream.
Implements IOstream.
Definition at line 149 of file UOPstream.H.
bool write (const commsTypes commsType, const int toProcNo, const char * buf, const std::streamsize bufSize, const int tag = UPstream::msgType(), const label communicator = 0) static
Write given buffer to given processor.
Definition at line 30 of file UOPwrite.C.
References NotImplemented.
Referenced by Pstream::combineGather(), Pstream::gather(), globalIndex::gather(), Pstream::gatherList(), processorLduInterface::send(), and LUscalarMatrix::solve().
bool write (const token & tok) virtual
Write token to stream or otherwise handle it.
Returns
false if the token type was not handled by this method
Implements Ostream.
Definition at line 184 of file UOPstream.C.
Foam::Ostream & write (const char c) virtual
Write single character. Whitespace is suppressed.
Implements Ostream.
Definition at line 222 of file UOPstream.C.
Foam::Ostream & write (const char * str) virtual
Write the word-characters of a character string.
Sends as a single char, or as word.
Implements Ostream.
Definition at line 233 of file UOPstream.C.
Foam::Ostream & write (const word & str) virtual
Write word.
Implements Ostream.
Definition at line 250 of file UOPstream.C.
Foam::Ostream & write (const string & str) virtual
Write string.
Implements Ostream.
Definition at line 259 of file UOPstream.C.
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implements Ostream.
Definition at line 269 of file UOPstream.C.
Foam::Ostream & write (const int32_t val) virtual
Write int32_t as a label.
Implements Ostream.
Definition at line 288 of file UOPstream.C.
Foam::Ostream & write (const int64_t val) virtual
Write int64_t as a label.
Implements Ostream.
Definition at line 296 of file UOPstream.C.
Foam::Ostream & write (const floatScalar val) virtual
Write floatScalar.
Implements Ostream.
Definition at line 304 of file UOPstream.C.
Foam::Ostream & write (const doubleScalar val) virtual
Write doubleScalar.
Implements Ostream.
Definition at line 312 of file UOPstream.C.
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Write binary block with 8-byte alignment.
Implements Ostream.
Definition at line 320 of file UOPstream.C.
Foam::Ostream & writeRaw (const char * data, std::streamsize count) virtual
Low-level raw binary output.
Implements Ostream.
Definition at line 336 of file UOPstream.C.
bool beginRawWrite (std::streamsize count) virtual
Begin marker for low-level raw binary output.
The count indicates the number of bytes for subsequent writeRaw calls.
Implements Ostream.
Definition at line 351 of file UOPstream.C.
virtual bool endRawWrite () inline virtual
End marker for low-level raw binary output.
Implements Ostream.
Definition at line 251 of file UOPstream.H.
virtual void indent () inline virtual
Add indentation characters.
Implements Ostream.
Definition at line 259 of file UOPstream.H.
virtual void flush () inline virtual
Flush stream.
Implements Ostream.
Definition at line 268 of file UOPstream.H.
virtual void endl () inline virtual
Add newline and flush stream.
Implements Ostream.
Definition at line 274 of file UOPstream.H.
virtual char fill () const inline virtual
Get the current padding character.
Returns
previous padding character
Implements Ostream.
Definition at line 282 of file UOPstream.H.
virtual char fill (const char) inline virtual
Set padding character for formatted field up to field width.
Implements Ostream.
Definition at line 290 of file UOPstream.H.
virtual int width () const inline virtual
Get width of output field.
Implements Ostream.
Definition at line 298 of file UOPstream.H.
virtual int width (const int) inline virtual
Set width of output field.
Returns
previous width
Implements Ostream.
Definition at line 308 of file UOPstream.H.
virtual int precision () const inline virtual
Get precision of output field.
Implements Ostream.
Definition at line 316 of file UOPstream.H.
virtual int precision (const int) inline virtual
Set precision of output field.
Returns
old precision
Implements Ostream.
Definition at line 326 of file UOPstream.H.
ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Set flags of stream.
Implements IOstream.
Definition at line 337 of file UOPstream.H.
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Definition at line 367 of file UOPstream.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UOPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UOPstream.C
src/Pstream/dummy/UOPwrite.C
src/Pstream/mpi/UOPwrite.C