OpenFOAM: threePhaseInterfaceProperties Class Reference
threePhaseInterfaceProperties Class Reference
Properties to aid interFoam : 1. Correct the alpha boundary condition for dynamic contact angle. 2. Calculate interface curvature.
Public Member Functions
threePhaseInterfaceProperties (const incompressibleThreePhaseMixture &mixture)
Construct from volume fraction field alpha and IOdictionary.
scalar cAlpha () const
const dimensionedScalar & deltaN () const
const surfaceScalarField & nHatf () const
const volScalarField & K () const
tmp< volScalarField > sigma () const
tmp< volScalarField > sigmaK () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
Indicator of the proximity of the interface.
void correct ()
Detailed Description
Properties to aid interFoam : 1. Correct the alpha boundary condition for dynamic contact angle. 2. Calculate interface curvature.
Source files
threePhaseInterfaceProperties.H
threePhaseInterfaceProperties.C
Definition at line 49 of file threePhaseInterfaceProperties.H.
Constructor & Destructor Documentation
threePhaseInterfaceProperties (const incompressibleThreePhaseMixture & mixture)
Construct from volume fraction field alpha and IOdictionary.
Member Function Documentation
scalar cAlpha () const inline
Definition at line 127 of file threePhaseInterfaceProperties.H.
const dimensionedScalar& deltaN () const inline
Definition at line 132 of file threePhaseInterfaceProperties.H.
References incompressibleThreePhaseMixture::alpha2(), incompressibleThreePhaseMixture::alpha3(), and Foam::max().
const surfaceScalarField& nHatf () const inline
Definition at line 137 of file threePhaseInterfaceProperties.H.
const volScalarField& K () const inline
Definition at line 142 of file threePhaseInterfaceProperties.H.
References threePhaseInterfaceProperties::sigma().
tmp<volScalarField> sigma () const inline
Definition at line 147 of file threePhaseInterfaceProperties.H.
Referenced by threePhaseInterfaceProperties::K().
tmp<volScalarField> sigmaK () const inline
Definition at line 157 of file threePhaseInterfaceProperties.H.
tmp<surfaceScalarField> surfaceTensionForce () const
tmp<volScalarField> nearInterface () const
Indicator of the proximity of the interface.
Field values are 1 near and 0 away for the interface.
void correct () inline
Definition at line 171 of file threePhaseInterfaceProperties.H.
Referenced by immiscibleIncompressibleThreePhaseMixture::correct().
The documentation for this class was generated from the following file:
applications/solvers/multiphase/interFoam/interMixingFoam/threePhaseInterfaceProperties/threePhaseInterfaceProperties.H