OpenFOAM: MRFZoneList Class Reference
MRFZoneList Class Reference
List container for MRF zomes.
Public Member Functions
MRFZoneList (const fvMesh &mesh, const dictionary &dict)
Constructor.
~MRFZoneList ()
Destructor.
bool active (const bool warn=false) const
Return active status.
void reset (const dictionary &dict)
Reset the source list.
void addAcceleration (const volVectorField &U, volVectorField &ddtU) const
Add the frame acceleration.
void addAcceleration (fvVectorMatrix &UEqn) const
Add the frame acceleration contribution to the momentum equation.
void addAcceleration (const volScalarField &rho, fvVectorMatrix &UEqn) const
Add the frame acceleration contribution to the momentum equation.
tmp< volVectorField > DDt (const volVectorField &U) const
Return the frame acceleration.
tmp< volVectorField > DDt (const volScalarField &rho, const volVectorField &U) const
Return the frame acceleration.
void makeRelative (volVectorField &U) const
Make the given absolute velocity relative within the MRF region.
void makeRelative (surfaceScalarField &phi) const
Make the given absolute flux relative within the MRF region.
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &phi) const
Return the given absolute flux relative within the MRF region.
tmp< FieldField< fvsPatchField,
scalar > > relative (const tmp< FieldField< fvsPatchField, scalar >> &tphi) const
Return the given absolute boundary flux relative within.
tmp< Field< scalar > > relative (const tmp< Field< scalar >> &tphi, const label patchi) const
Return the given absolute patch flux relative within.
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given absolute mass-flux relative within the MRF region.
void makeAbsolute (volVectorField &U) const
Make the given relative velocity absolute within the MRF region.
void makeAbsolute (surfaceScalarField &phi) const
Make the given relative flux absolute within the MRF region.
tmp< surfaceScalarField > absolute (const tmp< surfaceScalarField > &phi) const
Return the given relative flux absolute within the MRF region.
void makeAbsolute (const surfaceScalarField &rho, surfaceScalarField &phi) const
Make the given relative mass-flux absolute within the MRF region.
void correctBoundaryVelocity (volVectorField &U) const
Correct the boundary velocity for the rotation of the MRF region.
void correctBoundaryFlux (const volVectorField &U, surfaceScalarField &phi) const
Correct the boundary flux for the rotation of the MRF region.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tphi) const
Filter-out the MRF region contribution from the given field.
void update ()
Update MRFZone faces if the mesh topology changes.
bool read (const dictionary &dict)
Read dictionary.
bool writeData (Ostream &os) const
Write data to Ostream.
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> &tphi) const
Public Member Functions inherited from PtrList< MRFZone >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< MRFZone > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< MRFZone > &&list)
Move construct.
PtrList (UList< MRFZone * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
PtrList (const PtrList< MRFZone > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< MRFZone > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< MRFZone > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
PtrList< MRFZone > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (MRFZone *ptr)
Append an element to the end of the list.
void append (autoPtr< MRFZone > &aptr)
Move append an element to the end of the list.
void append (autoPtr< MRFZone > &&aptr)
Move append an element to the end of the list.
void append (const tmp< MRFZone > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< MRFZone > &list)
Transfer into this list and annul the argument list.
const MRFZone * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< MRFZone > set (const label i, MRFZone *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< MRFZone > set (const label i, autoPtr< MRFZone > &aptr)
Set element to given autoPtr and return old element.
autoPtr< MRFZone > set (const label i, autoPtr< MRFZone > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< MRFZone > set (const label i, const tmp< MRFZone > &tptr)
Set element to given tmp and return old element.
autoPtr< MRFZone > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< MRFZone > &list)
Copy assignment.
void operator= (PtrList< MRFZone > &&list)
Move assignment.
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Friends
Ostream & operator<< (Ostream &os, const MRFZoneList &models)
Ostream operator.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Protected Member Functions inherited from PtrList< MRFZone >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Detailed Description
List container for MRF zomes.
Source files
MRFZoneList.H
MRFZoneList.C
Definition at line 53 of file MRFZoneList.H.
Constructor & Destructor Documentation
MRFZoneList (const fvMesh & mesh, const dictionary & dict)
Constructor.
Definition at line 28 of file MRFZoneList.C.
References MRFZoneList::reset().
~MRFZoneList ()
Destructor.
Definition at line 44 of file MRFZoneList.C.
Member Function Documentation
bool active (const bool warn = false) const
Return active status.
Definition at line 50 of file MRFZoneList.C.
void reset (const dictionary & dict)
Reset the source list.
Definition at line 67 of file MRFZoneList.C.
Referenced by MRFZoneList::MRFZoneList().
void addAcceleration (const volVectorField & U, volVectorField & ddtU) const
Add the frame acceleration.
Definition at line 126 of file MRFZoneList.C.
void addAcceleration (fvVectorMatrix & UEqn) const
Add the frame acceleration contribution to the momentum equation.
Definition at line 138 of file MRFZoneList.C.
References i.
void addAcceleration (const volScalarField & rho, fvVectorMatrix & UEqn) const
Add the frame acceleration contribution to the momentum equation.
Definition at line 148 of file MRFZoneList.C.
References i.
Foam::tmp< Foam::volVectorField > DDt (const volVectorField & U) const
Return the frame acceleration.
Definition at line 161 of file MRFZoneList.C.
References i.
Foam::tmp< Foam::volVectorField > DDt (const volScalarField & rho, const volVectorField & U) const
Return the frame acceleration.
Definition at line 191 of file MRFZoneList.C.
void makeRelative (volVectorField & U) const
Make the given absolute velocity relative within the MRF region.
Definition at line 200 of file MRFZoneList.C.
References Foam::fvc::DDt().
void makeRelative (surfaceScalarField & phi) const
Make the given absolute flux relative within the MRF region.
Definition at line 209 of file MRFZoneList.C.
References i.
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & phi) const
Return the given absolute flux relative within the MRF region.
Definition at line 219 of file MRFZoneList.C.
References i.
Foam::tmp< Foam::FieldField< Foam::fvsPatchField, Foam::scalar > > relative (const tmp< FieldField< fvsPatchField, scalar >> & tphi) const
Return the given absolute boundary flux relative within.
the MRF region
Definition at line 251 of file MRFZoneList.C.
Foam::tmp< Foam::Field< Foam::scalar > > relative (const tmp< Field< scalar >> & tphi, const label patchi) const
Return the given absolute patch flux relative within.
the MRF region
Definition at line 277 of file MRFZoneList.C.
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given absolute mass-flux relative within the MRF region.
Definition at line 303 of file MRFZoneList.C.
void makeAbsolute (volVectorField & U) const
Make the given relative velocity absolute within the MRF region.
Definition at line 315 of file MRFZoneList.C.
References i.
void makeAbsolute (surfaceScalarField & phi) const
Make the given relative flux absolute within the MRF region.
Definition at line 324 of file MRFZoneList.C.
References i.
Foam::tmp< Foam::surfaceScalarField > absolute (const tmp< surfaceScalarField > & phi) const
Return the given relative flux absolute within the MRF region.
Definition at line 334 of file MRFZoneList.C.
References i.
void makeAbsolute (const surfaceScalarField & rho, surfaceScalarField & phi) const
Make the given relative mass-flux absolute within the MRF region.
Definition at line 365 of file MRFZoneList.C.
void correctBoundaryVelocity (volVectorField & U) const
Correct the boundary velocity for the rotation of the MRF region.
Definition at line 377 of file MRFZoneList.C.
References i.
void correctBoundaryFlux (const volVectorField & U, surfaceScalarField & phi) const
Correct the boundary flux for the rotation of the MRF region.
Definition at line 387 of file MRFZoneList.C.
References i.
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tphi) const
Filter-out the MRF region contribution from the given field.
setting the corresponding values to zero
void update ()
Update MRFZone faces if the mesh topology changes.
Definition at line 413 of file MRFZoneList.C.
References Uf.
bool read (const dictionary & dict)
Read dictionary.
Definition at line 100 of file MRFZoneList.C.
bool writeData (Ostream & os) const
Write data to Ostream.
Definition at line 113 of file MRFZoneList.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > zeroFilter (const tmp< GeometricField< Type, fvsPatchField, surfaceMesh >> & tphi) const
Definition at line 28 of file MRFZoneListTemplates.C.
References forAll, i, Foam::name(), Foam::New(), UPtrList< T >::operator[](), tmp< T >::ref(), and UPtrList< T >::size().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const MRFZoneList & models) friend
Ostream operator.
Member Data Documentation
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 77 of file MRFZoneList.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.H
src/finiteVolume/cfdTools/general/MRF/MRFZoneList.C
src/finiteVolume/cfdTools/general/MRF/MRFZoneListTemplates.C