OpenFOAM: extendedCentredCellToFaceStencil Class Reference
extendedCentredCellToFaceStencil Class Reference
Public Member Functions
extendedCentredCellToFaceStencil (const cellToFaceStencil &)
Construct from uncompacted face stencil.
const mapDistribute & map () const
Return reference to the parallel distribution map.
const labelListList & stencil () const
Return reference to the stencil.
void compact ()
After removing elements from the stencil adapt the schedule (map).
template<class T >
void collectData (const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T >> &stencilFld) const
Use map to get the data into stencil order.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > weightedSum (const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights) const
Sum vol field contributions to create face values.
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type >> &stencilFld)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T >> &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Source files
extendedCentredCellToFaceStencil.H
extendedCentredCellToFaceStencil.C
Definition at line 47 of file extendedCentredCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedCentredCellToFaceStencil (const cellToFaceStencil & stencil) explicit
Construct from uncompacted face stencil.
Definition at line 28 of file extendedCentredCellToFaceStencil.C.
References cellToFaceStencil::globalNumbering(), and UPstream::nProcs().
Member Function Documentation
const mapDistribute& map () const inline
Return reference to the parallel distribution map.
Definition at line 95 of file extendedCentredCellToFaceStencil.H.
Referenced by centredCECCellToFaceStencilObject::centredCECCellToFaceStencilObject(), centredCFCCellToFaceStencilObject::centredCFCCellToFaceStencilObject(), centredCPCCellToFaceStencilObject::centredCPCCellToFaceStencilObject(), centredFECCellToFaceStencilObject::centredFECCellToFaceStencilObject(), extendedCentredCellToFaceStencil::collectData(), and extendedCentredCellToFaceStencil::stencil().
const labelListList& stencil () const inline
Return reference to the stencil.
Definition at line 103 of file extendedCentredCellToFaceStencil.H.
References extendedCellToFaceStencil::collectData(), and extendedCentredCellToFaceStencil::map().
Referenced by centredCECCellToFaceStencilObject::centredCECCellToFaceStencilObject(), centredCFCCellToFaceStencilObject::centredCFCCellToFaceStencilObject(), centredCPCCellToFaceStencilObject::centredCPCCellToFaceStencilObject(), centredFECCellToFaceStencilObject::centredFECCellToFaceStencilObject(), and extendedCentredCellToFaceStencil::collectData().
void compact ()
After removing elements from the stencil adapt the schedule (map).
Definition at line 51 of file extendedCentredCellToFaceStencil.C.
void collectData (const GeometricField< T, fvPatchField, volMesh > & fld, List< List< T >> & stencilFld) const inline
Use map to get the data into stencil order.
Definition at line 118 of file extendedCentredCellToFaceStencil.H.
References extendedCentredCellToFaceStencil::map(), extendedCentredCellToFaceStencil::stencil(), and extendedCellToFaceStencil::weightedSum().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > weightedSum (const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar >> & stencilWeights) const inline
Sum vol field contributions to create face values.
Definition at line 137 of file extendedCentredCellToFaceStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCentredCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedCentredCellToFaceStencil.C