OpenFOAM: edgeVertex Class Reference
edgeVertex Class Reference
Combines edge or vertex in single label. Used to specify cuts across cell circumference.
Public Member Functions
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Static Public Member Functions
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointi to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Detailed Description
Combines edge or vertex in single label. Used to specify cuts across cell circumference.
Source files
edgeVertex.H
Definition at line 50 of file edgeVertex.H.
Constructor & Destructor Documentation
edgeVertex (const polyMesh & mesh) inline
Construct from mesh.
Definition at line 106 of file edgeVertex.H.
References primitiveMesh::nEdges(), and primitiveMesh::nPoints().
Member Function Documentation
void updateLabels (const labelList & map, List< refineCell > & refCells) static
Update refine list from map. Used to update cell/face labels.
after morphing
Definition at line 31 of file edgeVertex.C.
References refineCell::cellNo(), refineCell::direction(), and forAll.
void updateLabels (const labelList & map, Map< label > & cellPairs) static
Update map from map. Used to update cell/face labels.
after morphing
Definition at line 58 of file edgeVertex.C.
void updateLabels (const labelList & map, labelHashSet & cells) static
Update map from map. Used to update cell/face labels.
after morphing
Definition at line 121 of file edgeVertex.C.
const polyMesh& mesh () const inline
Definition at line 114 of file edgeVertex.H.
static bool isEdge (const primitiveMesh & mesh, const label eVert) inline static
Is eVert an edge?
Definition at line 125 of file edgeVertex.H.
Referenced by edgeVertex::getEdge().
bool isEdge (const label eVert) const inline
Definition at line 138 of file edgeVertex.H.
static label getEdge (const primitiveMesh & mesh, const label eVert) inline static
Convert eVert to edge label.
Definition at line 146 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and edgeVertex::isEdge().
label getEdge (const label eVert) const inline
Definition at line 156 of file edgeVertex.H.
References edgeVertex::getVertex().
static label getVertex (const primitiveMesh & mesh, const label eVert) inline static
Convert eVert to vertex label.
Definition at line 164 of file edgeVertex.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by edgeVertex::getEdge().
label getVertex (const label eVert) const inline
Definition at line 174 of file edgeVertex.H.
static label vertToEVert (const primitiveMesh & mesh, const label vertI) inline static
Convert pointi to eVert.
Definition at line 182 of file edgeVertex.H.
label vertToEVert (const label vertI) const inline
Definition at line 192 of file edgeVertex.H.
static label edgeToEVert (const primitiveMesh & mesh, const label edgeI) inline static
Convert edgeI to eVert.
Definition at line 200 of file edgeVertex.H.
References edgeVertex::coord().
label edgeToEVert (const label edgeI) const inline
Definition at line 210 of file edgeVertex.H.
Foam::point coord (const primitiveMesh & mesh, const label cut, const scalar weight) static
Return coordinate of cut (uses weight if edgeCut)
Definition at line 164 of file edgeVertex.C.
Referenced by edgeVertex::edgeToEVert().
point coord (const label cut, const scalar weight) const inline
Definition at line 224 of file edgeVertex.H.
Foam::label cutPairToEdge (const primitiveMesh & mesh, const label cut0, const label cut1) static
Find mesh edge (or -1) between two cuts.
Definition at line 186 of file edgeVertex.C.
label cutPairToEdge (const label cut0, const label cut1) const inline
Definition at line 238 of file edgeVertex.H.
Foam::Ostream & writeCut (Ostream & os, const label cut, const scalar weight) const
Write cut description to Ostream.
Definition at line 209 of file edgeVertex.C.
Foam::Ostream & writeCuts (Ostream & os, const labelList & cuts, const scalarField & weights) const
Write cut descriptions to Ostream.
Definition at line 234 of file edgeVertex.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/edgeVertex/edgeVertex.H
src/dynamicMesh/meshCut/edgeVertex/edgeVertex.C