OpenFOAM: sampledSurface Class Reference
sampledSurface Class Reference abstract
Utility function objects
An abstract class for surfaces with sampling.
Classes
class iNew
PtrList read-construction helper.
class iNewCapture
PtrList read-construction helper that captures dictionaries used during creation.
Public Member Functions
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &mesh, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor - calls clearGeom()
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool enabled () const
Surface is enabled.
bool invariant () const
Surface is invariant with geometry change (caution)
bool interpolate () const
Interpolation to nodes requested for surface.
virtual bool needsUpdate () const =0
Does the surface need an update?
virtual bool expire ()=0
Mark the surface as needing an update.
virtual bool update ()=0
Update the surface as required.
virtual const pointField & points () const =0
Points of surface.
virtual const faceList & faces () const =0
Faces of surface.
virtual const vectorField & Sf () const =0
Face area vectors.
virtual const scalarField & magSf () const =0
Face area magnitudes.
virtual const vectorField & Cf () const =0
Face centres.
scalar area () const
The total surface area.
virtual bool hasFaceIds () const
If element ids/order of the original surface are available.
virtual const labelList & originalIds () const
List of element ids/order of the original surface, when hasFaceIds is true.
polySurface * getRegistrySurface (const objectRegistry &obr, word lookupName="") const
Get surface from registry if available.
polySurface * storeRegistrySurface (objectRegistry &obr, word lookupName="") const
Copy surface into registry.
bool removeRegistrySurface (objectRegistry &obr, word lookupName="") const
Remove surface from registry.
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
Copy/store sampled field onto registered surface (if it exists)
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
Move/store sampled field onto registered surface (if it exists)
surfMesh * getSurfMesh (word lookupName="") const
Get surface from registry if available.
surfMesh * storeSurfMesh (word lookupName="") const
Copy surface into registry.
bool removeSurfMesh (word lookupName="") const
Remove surface from registry.
template<class Type , class GeoMeshType >
bool storeSurfMeshField (const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
Copy/store sampled Face field onto surfMesh (if it exists)
template<class Type , class GeoMeshType >
bool storeSurfMeshField (const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
Move/store sampled Face field onto surfMesh (if it exists)
virtual tmp< scalarField > sample (const interpolation< scalar > &sampler) const =0
Sample volume field onto surface faces.
virtual tmp< vectorField > sample (const interpolation< vector > &sampler) const =0
Sample volume field onto surface faces.
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > &sampler) const =0
Sample volume field onto surface faces.
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > &sampler) const =0
Sample volume field onto surface faces.
virtual tmp< tensorField > sample (const interpolation< tensor > &sampler) const =0
Sample volume field onto surface faces.
virtual bool withSurfaceFields () const
Can it sample surface-fields?
virtual tmp< scalarField > sample (const surfaceScalarField &sField) const
Sample surface field onto surface.
virtual tmp< vectorField > sample (const surfaceVectorField &sField) const
Sample surface field onto surface.
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &sField) const
Sample surface field onto surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &sField) const
Sample surface field onto surface.
virtual tmp< tensorField > sample (const surfaceTensorField &sField) const
Sample surface field onto surface.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &interpolator) const =0
Interpolate volume field onto surface points.
virtual tmp< vectorField > interpolate (const interpolation< vector > &interpolator) const =0
Interpolate volume field onto surface points.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &interpolator) const =0
Interpolate volume field onto surface points.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &interpolator) const =0
Interpolate volume field onto surface points.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &interpolator) const =0
Interpolate volume field onto surface points.
virtual void rename (const word &newName)
Rename.
virtual void print (Ostream &os) const
Print information.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld)
Public Member Functions inherited from meshedSurf
meshedSurf ()=default
Construct null.
virtual ~meshedSurf ()=default
Destructor.
virtual const labelList & zoneIds () const
Per-face zone/region information.
Static Public Member Functions
static autoPtr< sampledSurface > New (const word &name, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected surface.
Static Public Attributes
static const wordList surfaceFieldTypes
Class names for surface field types.
Protected Member Functions
virtual void clearGeom () const
Additional cleanup when clearing the geometry.
sampledSurface (const word &name, std::nullptr_t)
Construct null.
Static Protected Member Functions
template<class Type >
static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts)
General loop for sampling elements to faces.
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld)
Create cell values by averaging the point values.
Detailed Description
An abstract class for surfaces with sampling.
The constructors for the derived classes should generally start in a 'expired' condition (ie, needsUpdate() == true) and rely on a subsequent call to the update() method to complete the initialization. Delaying the final construction as late as possible allows the construction of surfaces that may depend on intermediate calculation results (eg, iso-surfaces) and also avoids the unnecessary reconstruction of surfaces between sampling intervals.
It is the responsibility of the caller to ensure that the surface update() is called before the surface is used. The update() method implementation should do nothing when the surface is already up-to-date.
Any sampler is assumed to work for the standard volume field types. Some may also support surface fields.
Dictionary entries:
Property Description Required Default
name Alternative name no
enabled Enable/disable the surface? no yes
interpolate Sample to nodes instead of faces no false
invariant Invariant with geometry change (use with caution!) no false
Note
The invariant switch is an advanced feature to declare that the surface is unaffected by changes in the general mesh geometry. For example, if sampling on a static patch while some other motion occurs elsewhere. If used improperly, there is a significant possibility for problems (caveat emptor).
Source files
sampledSurface.H
sampledSurface.C
sampledSurfaceTemplates.C
Definition at line 116 of file sampledSurface.H.
Constructor & Destructor Documentation
sampledSurface (const word & name, std::nullptr_t) explicit protected
Construct null.
Definition at line 87 of file sampledSurface.C.
sampledSurface (const word & name, const polyMesh & mesh, const bool interpolate = false)
Construct from name, mesh.
Definition at line 99 of file sampledSurface.C.
sampledSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 115 of file sampledSurface.C.
~sampledSurface () virtual
Destructor - calls clearGeom()
Definition at line 132 of file sampledSurface.C.
Member Function Documentation
static tmp<Field<Type> > sampleOnFaces (const interpolation< Type > & sampler, const labelUList & elements, const faceList & fcs, const pointField & pts) static protected
General loop for sampling elements to faces.
Referenced by sampledCuttingSurface::sampleOnFaces(), sampledTriSurfaceMesh::sampleOnFaces(), sampledPlane::sampleOnFaces(), sampledIsoSurface::sampleOnFaces(), sampledCuttingPlane::sampleOnFaces(), sampledDistanceSurface::sampleOnFaces(), sampledIsoSurfaceTopo::sampleOnFaces(), and sampledIsoSurfaceCell::sampleOnFaces().
static tmp<GeometricField<Type, fvPatchField, volMesh> > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > & pfld) static protected
Create cell values by averaging the point values.
void clearGeom () const protected virtual
Additional cleanup when clearing the geometry.
Definition at line 48 of file sampledSurface.C.
Referenced by sampledTriSurfaceMesh::expire().
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , sampledSurface , word , (const word &name, const polyMesh &mesh, const dictionary &dict) , (name, mesh, dict))
Declare run-time constructor selection table.
autoPtr<sampledSurface> clone () const inline
Clone.
Definition at line 313 of file sampledSurface.H.
Foam::autoPtr< Foam::sampledSurface > New (const word & name, const polyMesh & mesh, const dictionary & dict) static
Return a reference to the selected surface.
Definition at line 57 of file sampledSurface.C.
Referenced by sampledPatch::sampleOnFaces(), sampledTriSurfaceMesh::sampleOnFaces(), sampledSurface::sampleOnFaces(), sampledPatchInternalField::sampleOnFaces(), and sampledThresholdCellFaces::sampleOnFaces().
const polyMesh& mesh () const inline
Access to the underlying mesh.
Definition at line 346 of file sampledSurface.H.
References List< label >::null().
Referenced by sampledPatch::needsUpdate(), and sampledTriSurfaceMesh::sampleOnFaces().
const word& name () const inline
Name of surface.
Definition at line 354 of file sampledSurface.H.
Referenced by sampledSurface::getRegistrySurface().
bool enabled () const inline
Surface is enabled.
Definition at line 362 of file sampledSurface.H.
bool invariant () const inline
Surface is invariant with geometry change (caution)
Definition at line 370 of file sampledSurface.H.
bool interpolate () const inline
Interpolation to nodes requested for surface.
Definition at line 378 of file sampledSurface.H.
virtual bool needsUpdate () const pure virtual
Does the surface need an update?
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, sampledIsoSurfaceTopo, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
virtual bool expire () pure virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, sampledIsoSurfaceTopo, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
virtual bool update () pure virtual
Update the surface as required.
Do nothing (and return false) if no update was required
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, sampledIsoSurfaceTopo, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
virtual const pointField& points () const pure virtual
Points of surface.
Implements meshedSurf.
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
virtual const faceList& faces () const pure virtual
Faces of surface.
Implements meshedSurf.
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
virtual const vectorField& Sf () const pure virtual
Face area vectors.
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
virtual const scalarField& magSf () const pure virtual
Face area magnitudes.
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
virtual const vectorField& Cf () const pure virtual
Face centres.
Implemented in sampledTriSurfaceMesh, sampledCuttingPlane, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, and sampledNone.
Foam::scalar area () const
The total surface area.
Definition at line 140 of file sampledSurface.C.
virtual bool hasFaceIds () const inline virtual
If element ids/order of the original surface are available.
Reimplemented in sampledTriSurfaceMesh, and sampledDiscreteSurface.
Definition at line 436 of file sampledSurface.H.
virtual const labelList& originalIds () const inline virtual
List of element ids/order of the original surface, when hasFaceIds is true.
Reimplemented in sampledTriSurfaceMesh, and sampledDiscreteSurface.
Definition at line 445 of file sampledSurface.H.
Foam::polySurface * getRegistrySurface (const objectRegistry & obr, word lookupName = "") const
Get surface from registry if available.
Parameters
obr The objectRegistry to use
lookupName Optional lookup name, use surface name if empty
Returns
surface or nullptr
Definition at line 29 of file sampledSurfaceRegister.C.
References sampledSurface::name().
Foam::polySurface * storeRegistrySurface (objectRegistry & obr, word lookupName = "") const
Copy surface into registry.
Parameters
obr The objectRegistry to use
lookupName Optional lookup name, use surface name if empty
Returns
surface or nullptr it surface should not be stored
Definition at line 44 of file sampledSurfaceRegister.C.
bool removeRegistrySurface (objectRegistry & obr, word lookupName = "") const
Remove surface from registry.
Parameters
obr The objectRegistry to use
lookupName Optional lookup name, use surface name if empty
Returns
True if surface existed and was removed
Definition at line 69 of file sampledSurfaceRegister.C.
bool storeRegistryField (const objectRegistry & obr, const word & fieldName, const dimensionSet & dims, const Field< Type > & values, word lookupName = "") const
Copy/store sampled field onto registered surface (if it exists)
Definition at line 117 of file sampledSurfaceTemplates.C.
bool storeRegistryField (const objectRegistry & obr, const word & fieldName, const dimensionSet & dims, Field< Type > && values, word lookupName = "") const
Move/store sampled field onto registered surface (if it exists)
Definition at line 141 of file sampledSurfaceTemplates.C.
Foam::surfMesh * getSurfMesh (word lookupName = "") const
Get surface from registry if available.
Parameters
lookupName Optional lookup name, use surface name if empty
Returns
surface or nullptr
Definition at line 79 of file sampledSurfaceRegister.C.
References objectRegistry::checkOut().
Foam::surfMesh * storeSurfMesh (word lookupName = "") const
Copy surface into registry.
Parameters
lookupName Optional lookup name, use surface name if empty
Returns
surface or nullptr it surface should not be stored
Definition at line 90 of file sampledSurfaceRegister.C.
bool removeSurfMesh (word lookupName = "") const
Remove surface from registry.
Parameters
lookupName Optional lookup name, use surface name if empty
Returns
True if surface existed and was removed
Definition at line 113 of file sampledSurfaceRegister.C.
bool storeSurfMeshField (const word & fieldName, const dimensionSet & dims, const Field< Type > & values, word lookupName = "") const
Copy/store sampled Face field onto surfMesh (if it exists)
Definition at line 165 of file sampledSurfaceTemplates.C.
bool storeSurfMeshField (const word & fieldName, const dimensionSet & dims, Field< Type > && values, word lookupName = "") const
Move/store sampled Face field onto surfMesh (if it exists)
Definition at line 188 of file sampledSurfaceTemplates.C.
virtual tmp<scalarField> sample (const interpolation< scalar > & sampler) const pure virtual
Sample volume field onto surface faces.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledPatchInternalField, sampledNone, and sampledTriSurfaceMeshNormal.
virtual tmp<vectorField> sample (const interpolation< vector > & sampler) const pure virtual
Sample volume field onto surface faces.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledPatchInternalField, sampledNone, and sampledTriSurfaceMeshNormal.
virtual tmp<sphericalTensorField> sample (const interpolation< sphericalTensor > & sampler) const pure virtual
Sample volume field onto surface faces.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledPatchInternalField, sampledNone, and sampledTriSurfaceMeshNormal.
virtual tmp<symmTensorField> sample (const interpolation< symmTensor > & sampler) const pure virtual
Sample volume field onto surface faces.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledPatchInternalField, sampledNone, and sampledTriSurfaceMeshNormal.
virtual tmp<tensorField> sample (const interpolation< tensor > & sampler) const pure virtual
Sample volume field onto surface faces.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledPatchInternalField, sampledNone, and sampledTriSurfaceMeshNormal.
bool withSurfaceFields () const virtual
Can it sample surface-fields?
Reimplemented in sampledPatch.
Definition at line 151 of file sampledSurface.C.
Foam::tmp< Foam::scalarField > sample (const surfaceScalarField & sField) const virtual
Sample surface field onto surface.
Reimplemented in sampledPatch.
Definition at line 158 of file sampledSurface.C.
Foam::tmp< Foam::vectorField > sample (const surfaceVectorField & sField) const virtual
Sample surface field onto surface.
Reimplemented in sampledPatch.
Definition at line 168 of file sampledSurface.C.
References NotImplemented.
Foam::tmp< Foam::sphericalTensorField > sample (const surfaceSphericalTensorField & sField) const virtual
Sample surface field onto surface.
Reimplemented in sampledPatch.
Definition at line 178 of file sampledSurface.C.
References NotImplemented.
Foam::tmp< Foam::symmTensorField > sample (const surfaceSymmTensorField & sField) const virtual
Sample surface field onto surface.
Reimplemented in sampledPatch.
Definition at line 188 of file sampledSurface.C.
References NotImplemented.
Foam::tmp< Foam::tensorField > sample (const surfaceTensorField & sField) const virtual
Sample surface field onto surface.
Reimplemented in sampledPatch.
Definition at line 198 of file sampledSurface.C.
References NotImplemented.
virtual tmp<scalarField> interpolate (const interpolation< scalar > & interpolator) const pure virtual
Interpolate volume field onto surface points.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledPatchInternalField, sampledTriSurfaceMeshNormal, and sampledNone.
virtual tmp<vectorField> interpolate (const interpolation< vector > & interpolator) const pure virtual
Interpolate volume field onto surface points.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledTriSurfaceMeshNormal, sampledPatchInternalField, and sampledNone.
virtual tmp<sphericalTensorField> interpolate (const interpolation< sphericalTensor > & interpolator) const pure virtual
Interpolate volume field onto surface points.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledTriSurfaceMeshNormal, sampledPatchInternalField, and sampledNone.
virtual tmp<symmTensorField> interpolate (const interpolation< symmTensor > & interpolator) const pure virtual
Interpolate volume field onto surface points.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledTriSurfaceMeshNormal, sampledPatchInternalField, and sampledNone.
virtual tmp<tensorField> interpolate (const interpolation< tensor > & interpolator) const pure virtual
Interpolate volume field onto surface points.
Implemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledIsoSurfaceTopo, sampledThresholdCellFaces, sampledCuttingSurface, sampledDistanceSurface, sampledDiscreteSurface, sampledTriSurfaceMeshNormal, sampledPatchInternalField, and sampledNone.
virtual void rename (const word & newName) inline virtual
Rename.
Definition at line 708 of file sampledSurface.H.
void print (Ostream & os) const virtual
Print information.
Reimplemented in sampledCuttingPlane, sampledTriSurfaceMesh, sampledIsoSurface, sampledPatch, sampledPlane, sampledIsoSurfaceCell, sampledThresholdCellFaces, sampledIsoSurfaceTopo, sampledDistanceSurface, sampledDiscreteSurface, and sampledPatchInternalField.
Definition at line 207 of file sampledSurface.C.
References NotImplemented.
Foam::tmp<Foam::Field<Type> > sampleOnFaces (const interpolation< Type > & sampler, const labelUList & elements, const faceList & fcs, const pointField & pts)
Definition at line 29 of file sampledSurfaceTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, i, interpolation< class >::interpolate(), sampledSurface::New(), UList< T >::size(), and Foam::HashTableOps::values().
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > & pfld)
Definition at line 65 of file sampledSurfaceTemplates.C.
Member Data Documentation
const Foam::wordList surfaceFieldTypes static
Class names for surface field types.
Definition at line 127 of file sampledSurface.H.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/sampledSurface/sampledSurface.H
src/sampling/sampledSurface/sampledSurface/sampledSurface.C
src/sampling/sampledSurface/sampledSurface/sampledSurfaceRegister.C
src/sampling/sampledSurface/sampledSurface/sampledSurfaceTemplates.C