OpenFOAM: regionFunctionObject Class Reference
regionFunctionObject Class Reference
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
Public Member Functions
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()=default
Destructor.
virtual bool read (const dictionary &dict)
Read optional controls.
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
Deprecated(2018-10)
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Deprecated(2018-10)
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
Construct from components.
virtual ~stateFunctionObject ()=default
Destructor.
dictionary & propertyDict ()
Return access to the property dictionary.
bool foundProperty (const word &entryName) const
Return true if the property exists.
label getTrigger () const
Get the current trigger index.
bool setTrigger (const label triggeri)
Set the current trigger index.
bool getDict (const word &entryName, dictionary &dict) const
Set dictionary, return true if set.
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
Set dictionary from named object, return true if set.
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property.
template<class Type >
bool getProperty (const word &entryName, Type &value) const
Set generic property, return true if set.
template<class Type >
void setProperty (const word &entryName, const Type &value)
Add generic property.
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from named object.
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
Set generic property from named object, return true if set.
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
Add generic property from named object.
template<class Type >
void setResult (const word &entryName, const Type &value)
Add result.
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
Add result from named object.
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result.
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result from named object.
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
Set result from named object, return true if set.
word resultType (const word &entryName) const
Retrieve the result type.
word objectResultType (const word &objectName, const word &entryName) const
Return the type of result.
List< word > objectResultEntries () const
Retrieve the result entries.
List< word > objectResultEntries (const word &objectName) const
Return result entries for named object.
void writeResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
void writeResultEntries (const word &objectName, Ostream &os) const
Write the results entries for named object to stream.
void writeAllResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
Construct from Time.
virtual ~timeFunctionObject ()=default
Destructor.
const Time & time () const
Return time database.
objectRegistry & storedObjects ()
Write access to the output objects ("functionObjectObjects") registered on Time.
const objectRegistry & storedObjects () const
Const access to the output objects ("functionObjectObjects") registered on Time.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()=default
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool execute ()=0
Called at each ++ or += of the time-loop.
virtual bool execute (const label subIndex)
Execute using the specified subIndex.
virtual bool write ()=0
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool filesModified () const
Did any file get changed during execution?
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
virtual const objectRegistry & obr () const
The region or sub-region registry being used.
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
Return non-const pointer to the object of the given Type, (sub) objectRegistry.
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
Return non-const pointer to the object of the given Type, using a const-cast to have it behave like a mutable.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup and return object (eg, a field) from the (sub) objectRegistry.
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
Lookup and return object (eg, a field) from the (sub) objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the field in the (sub) objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in the (sub) objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the (sub) objectRegistry if present.
void clearObjects (const wordList &objNames)
Clear fields from the (sub) objectRegistry if present.
regionFunctionObject (const regionFunctionObject &)=delete
No copy construct.
void operator= (const regionFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from stateFunctionObject
const IOdictionary & stateDict () const
Return a const reference to the state dictionary.
IOdictionary & stateDict ()
Return non-const access to the state dictionary.
stateFunctionObject (const stateFunctionObject &)=delete
No copy construct.
void operator= (const stateFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
Remove specified items from "functionObjectObjects".
timeFunctionObject (const timeFunctionObject &)=delete
No copy construct.
void operator= (const timeFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Return a scoped name, e.g. used to construct local field names.
Protected Attributes
word subRegistryName_
Name for alternative object registry.
const objectRegistry & obr_
Reference to the region objectRegistry.
const objectRegistry * obrPtr_
Pointer to alternative (eg, sub-region) objectRegistry.
Protected Attributes inherited from timeFunctionObject
const Time & time_
Reference to the time database.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
bool log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
static word outputPrefix
Directory prefix.
Detailed Description
Specialization of Foam::functionObject for a region and providing a reference to the region Foam::objectRegistry.
Also provides support for referencing an alternative objectRegistry that can hold fields. This may be used, for example, to access stored surfaces and fields.
Dictionary controls
Property Description Required Default
region Name of the mesh region no region0
subRegion Name for alternative objectRegistry no ""
See Also
Foam::functionObjects::stateFunctionObject
Source files
regionFunctionObject.H
regionFunctionObject.C
Definition at line 83 of file regionFunctionObject.H.
Constructor & Destructor Documentation
regionFunctionObject (const regionFunctionObject &) protected delete
No copy construct.
regionFunctionObject (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
The region objectRegistry is looked-up runTime with the name looked-up from the dictionary (defaults to polyMesh::defaultRegion)
Definition at line 124 of file regionFunctionObject.C.
regionFunctionObject (const word & name, const objectRegistry & obr, const dictionary & dict)
Construct from the region objectRegistry and dictionary.
Definition at line 144 of file regionFunctionObject.C.
virtual ~regionFunctionObject () virtual default
Destructor.
Member Function Documentation
const Foam::objectRegistry & obr () const protected virtual
The region or sub-region registry being used.
Reimplemented in surfaceFieldValue.
Definition at line 40 of file regionFunctionObject.C.
Referenced by fieldAverage::addMeanFieldType(), regionFunctionObject::cfindObject(), and fieldValue::New().
bool foundObject (const word & fieldName) const protected
Find object (eg, a field) in the (sub) objectRegistry.
Definition at line 29 of file regionFunctionObjectTemplates.C.
const ObjectType * cfindObject (const word & fieldName) const protected
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
Returns
nullptr if the object was not found or had incorrect type.
Definition at line 39 of file regionFunctionObjectTemplates.C.
References objectRegistry::foundObject(), and regionFunctionObject::obr().
const ObjectType * findObject (const word & fieldName) const protected
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
Returns
nullptr if the object was not found or had incorrect type.
Definition at line 49 of file regionFunctionObjectTemplates.C.
ObjectType * findObject (const word & fieldName) protected
Return non-const pointer to the object of the given Type, (sub) objectRegistry.
Returns
nullptr if the object was not found or had incorrect type.
Definition at line 59 of file regionFunctionObjectTemplates.C.
ObjectType * getObjectPtr (const word & fieldName) const protected
Return non-const pointer to the object of the given Type, using a const-cast to have it behave like a mutable.
Exercise caution when using.
Returns
nullptr if the object was not found or had incorrect type.
Definition at line 70 of file regionFunctionObjectTemplates.C.
const ObjectType & lookupObject (const word & fieldName) const protected
Lookup and return object (eg, a field) from the (sub) objectRegistry.
Definition at line 80 of file regionFunctionObjectTemplates.C.
ObjectType & lookupObjectRef (const word & fieldName) const protected
Lookup and return object (eg, a field) from the (sub) objectRegistry.
Definition at line 90 of file regionFunctionObjectTemplates.C.
bool store (word & fieldName, const tmp< ObjectType > & tfield, bool cacheable = false) protected
Store the field in the (sub) objectRegistry under the given name.
Note: sets the fieldName to tfield().name() if not already set
Definition at line 100 of file regionFunctionObjectTemplates.C.
Referenced by fieldsExpression::calcFieldTypes(), surfaceInterpolate::interpolateFields(), and fieldCoordinateSystemTransform::transformField().
bool writeObject (const word & fieldName) protected
Write field if present in the (sub) objectRegistry.
Definition at line 60 of file regionFunctionObject.C.
bool clearObject (const word & fieldName) protected
Clear field from the (sub) objectRegistry if present.
Definition at line 81 of file regionFunctionObject.C.
void clearObjects (const wordList & objNames) protected
Clear fields from the (sub) objectRegistry if present.
Definition at line 105 of file regionFunctionObject.C.
void operator= (const regionFunctionObject &) protected delete
No copy assignment.
TypeName ("regionFunctionObject")
Runtime type information.
bool read (const dictionary & dict) virtual
Read optional controls.
Reimplemented from functionObject.
Reimplemented in surfaceFieldValue, stabilityBlendingFactor, forces, sampledSurfaces, regionSizeDistribution, pressure, volFieldValue, energyTransport, forceCoeffs, fieldAverage, ensightWrite, extractEulerianParticles, fluxSummary, scalarTransport, sizeDistribution, momentum, sampledSets, vtkCloud, turbulenceFields, streamLineBase, runTimePostProcessing, dataCloud, areaWrite, wallBoundedStreamLine, nearWallFields, fieldMinMax, streamLine, fieldExtents, reference, hydrostaticPressure, setFlow, fieldValueDelta, ddt2, limitFields, Curle, blendingFactor, valueAverage, solverInfo, fieldCoordinateSystemTransform, mapFields, particleDistribution, histogram, wallShearStress, zeroGradient, reactionsSensitivityAnalysis< chemistryType >, icoUncoupledKinematicCloud, fieldValue, proudmanAcousticPower, derivedFields, heatTransferCoeff, energySpectrum, wallHeatFlux, surfaceInterpolate, surfaceDistance, continuityError, columnAverage, AMIWeights, readFields, cloudInfo, phaseForces, CourantNo, runTimeControl, sixDoFRigidBodyState, DESModelRegions, PecletNo, yPlus, fieldsExpression, processorField, removeRegisteredObject, dsmcFields, writeDictionary, moleFractions< ThermoType >, writeCellCentres, XiReactionRate, writeCellVolumes, fieldExpression, specieReactionRates< ChemistryModelType >, and randomise.
Definition at line 159 of file regionFunctionObject.C.
Referenced by writeCellVolumes::execute(), XiReactionRate::execute(), writeCellCentres::execute(), processorField::execute(), and icoUncoupledKinematicCloud::execute().
const ObjectType* lookupObjectPtr (const word & fieldName) const inline
Deprecated(2018-10)
Deprecated:
(2018-10) - use findObject() method
Definition at line 273 of file regionFunctionObject.H.
ObjectType* lookupObjectRefPtr (const word & fieldName) const inline
Deprecated(2018-10)
Deprecated:
(2018-10) - use getObjectPtr() method
Definition at line 284 of file regionFunctionObject.H.
Member Data Documentation
word subRegistryName_ protected
Name for alternative object registry.
Definition at line 95 of file regionFunctionObject.H.
const objectRegistry& obr_ protected
Reference to the region objectRegistry.
Definition at line 100 of file regionFunctionObject.H.
Referenced by turbulenceFields::compressible(), nearWallFields::createFields(), surfaceInterpolate::interpolateFields(), turbulenceFields::processField(), and volFieldValue::validField().
const objectRegistry* obrPtr_ mutable protected
Pointer to alternative (eg, sub-region) objectRegistry.
If a sub-region is not in effect, this is a nullptr
Definition at line 107 of file regionFunctionObject.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObject.H
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObject.C
src/OpenFOAM/db/functionObjects/regionFunctionObject/regionFunctionObjectTemplates.C