OpenFOAM: laminarFlameSpeed Class Reference
laminarFlameSpeed Class Reference abstract
Abstract class for laminar flame speed.
Public Member Functions
TypeName ("laminarFlameSpeed")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarFlameSpeed, dictionary,(const dictionary &dict, const psiuReactionThermo &ct),(dict, ct))
laminarFlameSpeed (const dictionary &, const psiuReactionThermo &)
Construct from dictionary and psiuReactionThermo.
virtual ~laminarFlameSpeed ()
Destructor.
virtual tmp< volScalarField > operator() () const =0
Return the laminar flame speed [m/s].
Static Public Member Functions
static autoPtr< laminarFlameSpeed > New (const psiuReactionThermo &)
Protected Attributes
const psiuReactionThermo & psiuReactionThermo_
word fuel_
Fuel.
scalar equivalenceRatio_
Equivalence ratio of a homogeneous mixture.
Detailed Description
Abstract class for laminar flame speed.
Source files
laminarFlameSpeed.H
laminarFlameSpeed.C
laminarFlameSpeedNew.C
Definition at line 57 of file laminarFlameSpeed.H.
Constructor & Destructor Documentation
laminarFlameSpeed (const dictionary & dict, const psiuReactionThermo & ct)
Construct from dictionary and psiuReactionThermo.
Definition at line 36 of file laminarFlameSpeed.C.
~laminarFlameSpeed () virtual
Destructor.
Definition at line 55 of file laminarFlameSpeed.C.
Member Function Documentation
TypeName ("laminarFlameSpeed")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , laminarFlameSpeed , dictionary , (const dictionary &dict, const psiuReactionThermo &ct) , (dict, ct))
Foam::autoPtr< Foam::laminarFlameSpeed > New (const psiuReactionThermo & ct) static
Definition at line 27 of file laminarFlameSpeedNew.C.
References TimePaths::constant(), IOobject::db(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, basicThermo::T(), and IOobject::time().
virtual tmp<volScalarField> operator() () const pure virtual
Return the laminar flame speed [m/s].
Implemented in SCOPE, RaviPetersen, GuldersEGR, Gulders, and constant.
Member Data Documentation
const psiuReactionThermo& psiuReactionThermo_ protected
Definition at line 64 of file laminarFlameSpeed.H.
word fuel_ protected
Fuel.
Definition at line 69 of file laminarFlameSpeed.H.
scalar equivalenceRatio_ protected
Equivalence ratio of a homogeneous mixture.
Definition at line 74 of file laminarFlameSpeed.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/laminarFlameSpeed/laminarFlameSpeed/laminarFlameSpeed.H
src/thermophysicalModels/laminarFlameSpeed/laminarFlameSpeed/laminarFlameSpeed.C
src/thermophysicalModels/laminarFlameSpeed/laminarFlameSpeed/laminarFlameSpeedNew.C