OpenFOAM: interpolationCellPointWallModified< Type > Class Template Reference
interpolationCellPointWallModified< Type > Class Template Reference
Same as interpolationCellPoint, but if interpolating a wall face, uses cell centre value instead.
Public Member Functions
TypeName ("cellPointWallModified")
Runtime type information.
interpolationCellPointWallModified (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
Type interpolate (const cellPointWeightWallModified &cpw) const
Interpolate field for the given cellPointWeight.
Type interpolate (const vector &position, const label celli, const label facei=-1) const
Interpolate field to the given point in the given cell.
Type interpolate (const barycentric &coordinates, const tetIndices &tetIs, const label facei=-1) const
Interpolate field to the given coordinates in the tetrahedron.
Public Member Functions inherited from interpolationCellPoint< Type >
TypeName ("cellPoint")
Runtime type information.
interpolationCellPoint (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
Type interpolate (const cellPointWeight &cpw) const
Interpolate field for the given cellPointWeight.
Public Member Functions inherited from interpolation< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolation, dictionary,(const GeometricField< Type, fvPatchField, volMesh > &psi),(psi))
interpolation (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
virtual ~interpolation ()=default
Destructor.
const GeometricField< Type,
fvPatchField, volMesh > & psi () const
Return the field to be interpolated.
Additional Inherited Members
Static Public Member Functions inherited from interpolation< Type >
static autoPtr< interpolation
< Type > > New (const word &interpolationType, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the specified interpolation scheme.
static autoPtr< interpolation
< Type > > New (const dictionary &interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the selected interpolation scheme.
Protected Attributes inherited from interpolationCellPoint< Type >
const GeometricField< Type,
pointPatchField, pointMesh > psip_
Interpolated volfield.
Protected Attributes inherited from interpolation< Type >
const GeometricField< Type,
fvPatchField, volMesh > & psi_
const polyMesh & pMesh_
const vectorField & pMeshPoints_
const faceList & pMeshFaces_
const vectorField & pMeshFaceCentres_
const vectorField & pMeshFaceAreas_
Detailed Description
template<class Type>
class Foam::interpolationCellPointWallModified< Type >
Same as interpolationCellPoint, but if interpolating a wall face, uses cell centre value instead.
Definition at line 44 of file interpolationCellPointWallModified.H.
Constructor & Destructor Documentation
interpolationCellPointWallModified (const GeometricField< Type, fvPatchField, volMesh > & psi)
Construct from components.
Definition at line 28 of file interpolationCellPointWallModified.C.
Member Function Documentation
TypeName ("cellPointWallModified")
Runtime type information.
Type interpolate (const cellPointWeightWallModified & cpw) const inline
Interpolate field for the given cellPointWeight.
Definition at line 25 of file interpolationCellPointWallModifiedI.H.
References cellPointWeight::cell(), cellPointWeight::faceVertices(), and cellPointWeight::weights().
Type interpolate (const vector & position, const label celli, const label facei = -1) const inline virtual
Interpolate field to the given point in the given cell.
Reimplemented from interpolationCellPoint< Type >.
Definition at line 43 of file interpolationCellPointWallModifiedI.H.
Type interpolate (const barycentric & coordinates, const tetIndices & tetIs, const label facei = -1) const inline virtual
Interpolate field to the given coordinates in the tetrahedron.
defined by the given indices.
Reimplemented from interpolationCellPoint< Type >.
Definition at line 64 of file interpolationCellPointWallModifiedI.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationCellPointWallModified/interpolationCellPointWallModified.H
src/finiteVolume/interpolation/interpolation/interpolationCellPointWallModified/interpolationCellPointWallModified.C
src/finiteVolume/interpolation/interpolation/interpolationCellPointWallModified/interpolationCellPointWallModifiedI.H