OpenFOAM: partitioningModel Class Reference
partitioningModel Class Reference abstract
Base class for wall heat flux partitioning models.
Public Member Functions
TypeName ("partitioningModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, partitioningModel, dictionary,(const dictionary &dict),(dict))
Declare runtime construction.
partitioningModel ()
Construct null.
virtual ~partitioningModel ()
Destructor.
virtual tmp< scalarField > fLiquid (const scalarField &alphaLiquid) const =0
Calculate and return the wall heat-flux partitioning.
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< partitioningModel > New (const dictionary &dict)
Select null constructed.
Detailed Description
Base class for wall heat flux partitioning models.
Source files
partitioningModel.H
partitioningModel.C
newpartitioningModel.C
Definition at line 51 of file partitioningModel.H.
Constructor & Destructor Documentation
partitioningModel ()
Construct null.
Definition at line 37 of file partitioningModel.C.
~partitioningModel () virtual
Destructor.
Definition at line 43 of file partitioningModel.C.
Member Function Documentation
TypeName ("partitioningModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , partitioningModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime construction.
Foam::autoPtr< Foam::wallBoilingModels::partitioningModel > New (const dictionary & dict) static
Select null constructed.
Definition at line 28 of file newPartitioningModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<scalarField> fLiquid (const scalarField & alphaLiquid) const pure virtual
Calculate and return the wall heat-flux partitioning.
Implemented in linear, cosine, Lavieville, and phaseFraction.
void write (Ostream & os) const virtual
Reimplemented in linear, cosine, and Lavieville.
Definition at line 49 of file partitioningModel.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/partitioningModel/partitioningModel.H
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/partitioningModel/newPartitioningModel.C
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/partitioningModel/partitioningModel.C