OpenFOAM: backwardFaDdtScheme< Type > Class Template Reference
backwardFaDdtScheme< Type > Class Template Reference
Second-order backward-differencing implicit ddt using the current and two previous time-step values.
Public Member Functions
TypeName ("backward")
Runtime type information.
backwardFaDdtScheme (const faMesh &mesh)
Construct from mesh.
backwardFaDdtScheme (const faMesh &mesh, Istream &is)
Construct from mesh and Istream.
const faMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt (const dimensioned< Type >)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt0 (const dimensioned< Type >)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt0 (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt0 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facDdt0 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famDdt (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famDdt (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< faMatrix< Type > > famDdt (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
Public Member Functions inherited from faDdtScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, faDdtScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
faDdtScheme (const faMesh &mesh)
Construct from mesh.
faDdtScheme (const faMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~faDdtScheme ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from faDdtScheme< Type >
static tmp< faDdtScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Return a pointer to a new faDdtScheme created on freestore.
Protected Member Functions inherited from faDdtScheme< Type >
faDdtScheme (const faDdtScheme &)=delete
No copy construct.
void operator= (const faDdtScheme &)=delete
No copy assignment.
Protected Attributes inherited from faDdtScheme< Type >
const faMesh & mesh_
Detailed Description
template<class Type>
class Foam::fa::backwardFaDdtScheme< Type >
Second-order backward-differencing implicit ddt using the current and two previous time-step values.
Source files
backwardFaDdtScheme.H
backwardFaDdtScheme.C
Definition at line 53 of file backwardFaDdtScheme.H.
Constructor & Destructor Documentation
backwardFaDdtScheme (const faMesh & mesh) inline
Construct from mesh.
Definition at line 101 of file backwardFaDdtScheme.H.
References faDdtScheme< Type >::mesh().
backwardFaDdtScheme (const faMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 109 of file backwardFaDdtScheme.H.
Member Function Documentation
TypeName ("backward")
Runtime type information.
const faMesh& mesh () const inline
Return mesh reference.
Definition at line 120 of file backwardFaDdtScheme.H.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensioned< Type > dt) virtual
Implements faDdtScheme< Type >.
Definition at line 71 of file backwardFaDdtScheme.C.
References dimensioned< Type >::dimensions(), Foam::dimTime, mesh, dimensioned< Type >::name(), Foam::New(), IOobject::NO_READ, IOobject::NO_WRITE, tmp< T >::ref(), dimensioned< Type >::value(), and Foam::Zero.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensioned< Type > dt) virtual
Implements faDdtScheme< Type >.
Definition at line 126 of file backwardFaDdtScheme.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 173 of file backwardFaDdtScheme.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 246 of file backwardFaDdtScheme.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 316 of file backwardFaDdtScheme.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 389 of file backwardFaDdtScheme.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 460 of file backwardFaDdtScheme.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > facDdt0 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 537 of file backwardFaDdtScheme.C.
tmp< faMatrix< Type > > famDdt (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 611 of file backwardFaDdtScheme.C.
tmp< faMatrix< Type > > famDdt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 662 of file backwardFaDdtScheme.C.
tmp< faMatrix< Type > > famDdt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements faDdtScheme< Type >.
Definition at line 713 of file backwardFaDdtScheme.C.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/ddtSchemes/backwardFaDdtScheme/backwardFaDdtScheme.H
src/finiteArea/finiteArea/ddtSchemes/backwardFaDdtScheme/backwardFaDdtScheme.C