OpenFOAM: Tensor< Cmpt > Class Template Reference
Tensor< Cmpt > Class Template Reference
Templated 3D tensor derived from MatrixSpace adding construction from 9 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum components {
XX, XY, XZ, YX,
YY, YZ, ZX, ZY,
ZZ
}
Component labeling enumeration.
typedef Tensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
typedef MatrixSpace< Tensor
< Cmpt >, Cmpt, Mrows, Ncols > msType
MatrixSpace type.
Public Types inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
typedef VectorSpace< Tensor
< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
typedef Cmpt magType
Magnitude type.
typedef Cmpt * iterator
Random access iterator for traversing VectorSpace.
typedef const Cmpt * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
Tensor ()
Construct null.
Tensor (const Foam::zero)
Construct initialized to zero.
template<class Cmpt2 >
Tensor (const MatrixSpace< Tensor< Cmpt2 >, Cmpt2, 3, 3 > &vs)
Construct given MatrixSpace of the same rank.
template<class Cmpt2 >
Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > &vs)
Construct given VectorSpace of the same rank.
Tensor (const SphericalTensor< Cmpt > &st)
Construct given SphericalTensor.
Tensor (const SymmTensor< Cmpt > &st)
Construct given SymmTensor.
Tensor (const Vector< Vector< Cmpt >> &vecs, const bool transposed=false)
Construct given triad of row vectors, optionally treated as transposed (ie, column vectors)
Tensor (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z, const bool transposed=false)
Construct given the three row vectors, optionally treated as transposed (ie, column vectors)
Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz)
Construct given the nine components.
template<template< class, direction, direction > class Block2, direction BRowStart, direction BColStart>
Tensor (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
Construct from a block of another matrix space.
Tensor (Istream &is)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & xz () const
const Cmpt & yx () const
const Cmpt & yy () const
const Cmpt & yz () const
const Cmpt & zx () const
const Cmpt & zy () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & xz ()
Cmpt & yx ()
Cmpt & yy ()
Cmpt & yz ()
Cmpt & zx ()
Cmpt & zy ()
Cmpt & zz ()
Vector< Cmpt > cx () const
Extract vector for column 0.
Vector< Cmpt > cy () const
Extract vector for column 1.
Vector< Cmpt > cz () const
Extract vector for column 2.
template<direction Col>
Vector< Cmpt > col () const
Extract vector for given column.
Vector< Cmpt > col (const direction c) const
Extract vector for given column (0,1,2).
template<direction Col>
void col (const Vector< Cmpt > &v)
Set values of given column.
void col (const direction c, const Vector< Cmpt > &v)
Set values of given column (0,1,2)
void cols (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Set column values.
Vector< Cmpt > x () const
Extract vector for row 0.
Vector< Cmpt > y () const
Extract vector for row 1.
Vector< Cmpt > z () const
Extract vector for row 2.
template<direction Row>
Vector< Cmpt > row () const
Extract vector for given row.
Vector< Cmpt > row (const direction r) const
Extract vector for given row (0,1,2)
template<direction Row>
void row (const Vector< Cmpt > &v)
Set values of given row.
void row (const direction r, const Vector< Cmpt > &v)
Set values of given row (0,1,2)
void rows (const Vector< Cmpt > &x, const Vector< Cmpt > &y, const Vector< Cmpt > &z)
Set row values.
Vector< Cmpt > diag () const
Extract the diagonal as a vector.
void diag (const Vector< Cmpt > &v)
Set values of the diagonal.
Tensor< Cmpt > T () const
Return transpose.
Tensor< Cmpt > inv () const
Return inverse.
Tensor< Cmpt > inner (const Tensor< Cmpt > &t2) const
Inner-product of this with another Tensor.
Tensor< Cmpt > schur (const Tensor< Cmpt > &t2) const
Schur-product of this with another Tensor.
void operator&= (const Tensor< Cmpt > &t)
Assign inner-product of this with another Tensor.
template<class Cmpt2 >
void operator= (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > &)
Assign to an equivalent vector space.
void operator= (const SphericalTensor< Cmpt > &)
Assign to a SphericalTensor.
void operator= (const SymmTensor< Cmpt > &)
Assign to a SymmTensor.
void operator= (const Vector< Vector< Cmpt >> &)
Assign to a triad of row vectors.
Vector< Cmpt > vectorComponent (const direction cmpt) const
Deprecated(2018-12) Return vector for given row (0,1)
template<Foam::direction Col>
Foam::Vector< Cmpt > col () const
template<Foam::direction Row>
Foam::Vector< Cmpt > row () const
Public Member Functions inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
MatrixSpace ()
Construct null.
MatrixSpace (const Foam::zero)
Construct initialized to zero.
MatrixSpace (const VectorSpace< Form2, Cmpt2, Mrows *Ncols > &)
Construct as copy of a VectorSpace with the same size.
MatrixSpace (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
Construct from a block of another matrix space.
MatrixSpace (Istream &)
Construct from Istream.
const Cmpt & elmt () const
Fast const element access using compile-time addressing.
Cmpt & elmt ()
Fast element access using compile-time addressing.
const Cmpt & xx () const
Cmpt & xx ()
const Cmpt & xy () const
Cmpt & xy ()
const Cmpt & xz () const
Cmpt & xz ()
const Cmpt & yx () const
Cmpt & yx ()
const Cmpt & yy () const
Cmpt & yy ()
const Cmpt & yz () const
Cmpt & yz ()
const Cmpt & zx () const
Cmpt & zx ()
const Cmpt & zy () const
Cmpt & zy ()
const Cmpt & zz () const
Cmpt & zz ()
typeOfTranspose< Cmpt, Tensor
< Cmpt > >::type T () const
Return the transpose of the matrix.
ConstBlock< SubTensor,
BRowStart, BColStart > block () const
Return a const sub-block corresponding to the specified type.
Block< SubTensor, BRowStart,
BColStart > block ()
Return a sub-block corresponding to the specified type.
const Cmpt & operator() (const direction &i, const direction &j) const
(i, j) const element access operator
Cmpt & operator() (const direction &i, const direction &j)
(i, j) element access operator
void operator= (const Foam::zero)
Assignment to zero.
void operator= (const Block2< Tensor< Cmpt >, BRowStart, BColStart > &block)
Assignment to a block of another matrix space.
void operator&= (const MatrixSpace< Tensor< Cmpt >, Cmpt, Ncols, Ncols > &matrix)
Inner product with a compatible square matrix.
Public Member Functions inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Return const pointer to the first data element.
Cmpt * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Tensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Static Public Attributes
static constexpr direction rank = 2
Rank of Tensor is 2.
static const Tensor I
Static Public Attributes inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
static constexpr direction mRows
static constexpr direction nCols
Static Public Attributes inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Tensor< Cmpt > zero
static const Tensor< Cmpt > one
static const Tensor< Cmpt > max
static const Tensor< Cmpt > min
static const Tensor< Cmpt > rootMax
static const Tensor< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from MatrixSpace< Tensor< Cmpt >, Cmpt, 3, 3 >
static direction m () noexcept
Return the number of rows.
static direction n () noexcept
Return the number of columns.
static msType identity ()
Return the identity matrix for square matrix spaces.
Static Public Member Functions inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Tensor< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< Tensor< Cmpt >, Cmpt, Mrows *Ncols >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Tensor< Cmpt >
Templated 3D tensor derived from MatrixSpace adding construction from 9 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
Tensor.H
TensorI.H
See Also
Foam::MatrixSpace Foam::Vector
Definition at line 275 of file complexI.H.
Member Typedef Documentation
typedef Tensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 71 of file Tensor.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
XX
XY
XZ
YX
YY
YZ
ZX
ZY
ZZ
Definition at line 90 of file Tensor.H.
Constructor & Destructor Documentation
Tensor () inline
Construct null.
Definition at line 27 of file TensorI.H.
Tensor (const Foam::zero) inline
Construct initialized to zero.
Definition at line 32 of file TensorI.H.
Tensor (const MatrixSpace< Tensor< Cmpt2 >, Cmpt2, 3, 3 > & vs) inline
Construct given MatrixSpace of the same rank.
Definition at line 41 of file TensorI.H.
Tensor (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 52 of file TensorI.H.
Tensor (const SphericalTensor< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 61 of file TensorI.H.
Tensor (const SymmTensor< Cmpt > & st) inline
Construct given SymmTensor.
Definition at line 72 of file TensorI.H.
Tensor (const Vector< Vector< Cmpt >> & vecs, const bool transposed = false) inline
Construct given triad of row vectors, optionally treated as transposed (ie, column vectors)
Definition at line 82 of file TensorI.H.
Tensor (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z, const bool transposed = false) inline
Construct given the three row vectors, optionally treated as transposed (ie, column vectors)
Definition at line 93 of file TensorI.H.
Tensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyx, const Cmpt tyy, const Cmpt tyz, const Cmpt tzx, const Cmpt tzy, const Cmpt tzz) inline
Construct given the nine components.
Definition at line 113 of file TensorI.H.
Tensor (const Block2< Tensor< Cmpt >, BRowStart, BColStart > & block) inline
Construct from a block of another matrix space.
Definition at line 133 of file TensorI.H.
Tensor (Istream & is) inline
Construct from Istream.
Definition at line 142 of file TensorI.H.
Member Function Documentation
const Cmpt & xx () const inline
Definition at line 151 of file TensorI.H.
Referenced by Foam::det(), Foam::inv(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::tr(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & xy () const inline
Definition at line 158 of file TensorI.H.
Referenced by Foam::det(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & xz () const inline
Definition at line 165 of file TensorI.H.
Referenced by Foam::det(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & yx () const inline
Definition at line 172 of file TensorI.H.
Referenced by Foam::det(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & yy () const inline
Definition at line 179 of file TensorI.H.
Referenced by Foam::det(), Foam::inv(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::tr(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & yz () const inline
Definition at line 186 of file TensorI.H.
Referenced by Foam::det(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & zx () const inline
Definition at line 193 of file TensorI.H.
Referenced by Foam::det(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & zy () const inline
Definition at line 200 of file TensorI.H.
Referenced by Foam::det(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::transform(), and Foam::transformPrincipal_vector().
const Cmpt & zz () const inline
Definition at line 207 of file TensorI.H.
Referenced by Foam::det(), Foam::inv(), Foam::invariantII(), Foam::invariantIII(), momentOfInertia::massPropertiesSolid(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::symm(), Foam::tr(), Foam::transform(), and Foam::transformPrincipal_vector().
Cmpt & xx () inline
Definition at line 214 of file TensorI.H.
Cmpt & xy () inline
Definition at line 221 of file TensorI.H.
Cmpt & xz () inline
Definition at line 228 of file TensorI.H.
Cmpt & yx () inline
Definition at line 235 of file TensorI.H.
Cmpt & yy () inline
Definition at line 242 of file TensorI.H.
Cmpt & yz () inline
Definition at line 249 of file TensorI.H.
Cmpt & zx () inline
Definition at line 256 of file TensorI.H.
Cmpt & zy () inline
Definition at line 263 of file TensorI.H.
Cmpt & zz () inline
Definition at line 270 of file TensorI.H.
Foam::Vector< Cmpt > cx () const inline
Extract vector for column 0.
Definition at line 298 of file TensorI.H.
Foam::Vector< Cmpt > cy () const inline
Extract vector for column 1.
Definition at line 305 of file TensorI.H.
Foam::Vector< Cmpt > cz () const inline
Extract vector for column 2.
Definition at line 312 of file TensorI.H.
Vector<Cmpt> col () const inline
Extract vector for given column.
Compile-time check of column index.
Referenced by cylindrical::R().
Foam::Vector< Cmpt > col (const direction c) const inline
Extract vector for given column (0,1,2).
Runtime check of column index.
Definition at line 332 of file TensorI.H.
void col (const Vector< Cmpt > & v) inline
Set values of given column.
Compile-time check of column index.
Definition at line 380 of file TensorI.H.
void col (const direction c, const Vector< Cmpt > & v) inline
Set values of given column (0,1,2)
Runtime check of column index.
Definition at line 455 of file TensorI.H.
void cols (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Set column values.
Definition at line 428 of file TensorI.H.
Foam::Vector< Cmpt > x () const inline
Extract vector for row 0.
Definition at line 277 of file TensorI.H.
Foam::Vector< Cmpt > y () const inline
Extract vector for row 1.
Definition at line 284 of file TensorI.H.
Foam::Vector< Cmpt > z () const inline
Extract vector for row 2.
Definition at line 291 of file TensorI.H.
Vector<Cmpt> row () const inline
Extract vector for given row.
Compile-time check of row index.
Foam::Vector< Cmpt > row (const direction r) const inline
Extract vector for given row (0,1,2)
Runtime check of row index.
Definition at line 362 of file TensorI.H.
void row (const Vector< Cmpt > & v) inline
Set values of given row.
Compile-time check of row index.
Definition at line 407 of file TensorI.H.
void row (const direction r, const Vector< Cmpt > & v) inline
Set values of given row (0,1,2)
Runtime check of row index.
Definition at line 471 of file TensorI.H.
void rows (const Vector< Cmpt > & x, const Vector< Cmpt > & y, const Vector< Cmpt > & z) inline
Set row values.
Definition at line 442 of file TensorI.H.
Foam::Vector< Cmpt > diag () const inline
Extract the diagonal as a vector.
Definition at line 487 of file TensorI.H.
void diag (const Vector< Cmpt > & v) inline
Set values of the diagonal.
Definition at line 494 of file TensorI.H.
Foam::Tensor< Cmpt > T () const inline
Return transpose.
Definition at line 503 of file TensorI.H.
Referenced by particle< Type >::correctAfterInteractionListReferral(), edgeInterpolationScheme< Type >::interpolate(), spatialTransform::operator*(), Foam::RBD::transform(), and triad::triad().
Tensor< Cmpt > inv () const inline
Return inverse.
Definition at line 857 of file TensorI.H.
Foam::Tensor< Cmpt > inner (const Tensor< Cmpt > & t2) const inline
Inner-product of this with another Tensor.
Definition at line 516 of file TensorI.H.
Foam::Tensor< Cmpt > schur (const Tensor< Cmpt > & t2) const inline
Schur-product of this with another Tensor.
Definition at line 539 of file TensorI.H.
void operator&= (const Tensor< Cmpt > & t) inline
Assign inner-product of this with another Tensor.
Definition at line 555 of file TensorI.H.
void operator= (const VectorSpace< Tensor< Cmpt2 >, Cmpt2, 9 > & vs) inline
Assign to an equivalent vector space.
Definition at line 564 of file TensorI.H.
void operator= (const SphericalTensor< Cmpt > & st) inline
Assign to a SphericalTensor.
Definition at line 573 of file TensorI.H.
void operator= (const SymmTensor< Cmpt > & st) inline
Assign to a SymmTensor.
Definition at line 582 of file TensorI.H.
void operator= (const Vector< Vector< Cmpt >> & tr) inline
Assign to a triad of row vectors.
Definition at line 591 of file TensorI.H.
Vector<Cmpt> vectorComponent (const direction cmpt) const inline
Deprecated(2018-12) Return vector for given row (0,1)
Deprecated:
(2018-12) use row() method
Definition at line 397 of file Tensor.H.
Foam::Vector<Cmpt> col () const inline
Definition at line 320 of file TensorI.H.
Foam::Vector<Cmpt> row () const inline
Definition at line 350 of file TensorI.H.
Member Data Documentation
constexpr direction rank = 2 static
Rank of Tensor is 2.
Definition at line 79 of file Tensor.H.
const Foam::floatTensor I static
Definition at line 84 of file Tensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/complex/complexI.H
src/OpenFOAM/primitives/Tensor/Tensor.H
src/OpenFOAM/primitives/Tensor/doubleTensor/doubleTensor.C
src/OpenFOAM/primitives/Tensor/floatTensor/floatTensor.C
src/OpenFOAM/primitives/Tensor/TensorI.H