OpenFOAM: treeDataPoint Class Reference
treeDataPoint Class Reference
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassName ("treeDataPoint")
treeDataPoint (const pointField &points)
Construct from pointField.
treeDataPoint (const pointField &points, const labelUList &pointLabels, const bool useSubsetPoints=true)
Construct from subset of pointField, copies point ids.
treeDataPoint (const pointField &points, labelList &&pointLabels, const bool useSubsetPoints=true)
Construct from subset of pointField, moves point ids.
bool empty () const
An empty effective point field?
label size () const
The effective point field size.
const pointField & points () const
The original point field.
const labelList & pointLabels () const
The original point ids.
bool useSubset () const
Use a subset of points.
label pointLabel (const label index) const
The original (non-subset) point label.
const point & shapePoint (const label index) const
Point at specified index.
pointField shapePoints () const
Representative point cloud for all shapes inside (one point per shape)
volumeType getVolumeType (const indexedOctree< treeDataPoint > &os, const point &sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does (bb of) shape at index overlap bb.
bool overlaps (const label index, const point &centre, const scalar radiusSqr) const
Does shape at index overlap the sphere.
const point & operator[] (const label index) const
The point at the specified index.
Detailed Description
Holds (reference to) pointField. Encapsulation of data needed for octree searches. Used for searching for nearest point. No bounding boxes around points. Only overlaps and calcNearest are implemented, rest makes little sense.
Optionally works on subset of points.
Source files
treeDataPoint.H
treeDataPoint.C
Definition at line 58 of file treeDataPoint.H.
Constructor & Destructor Documentation
treeDataPoint (const pointField & points) explicit
Construct from pointField.
Note
Holds reference to the points!
Definition at line 37 of file treeDataPoint.C.
References Foam::defineTypeNameAndDebug().
treeDataPoint (const pointField & points, const labelUList & pointLabels, const bool useSubsetPoints = true)
Construct from subset of pointField, copies point ids.
Note
Holds reference to the points!
Definition at line 45 of file treeDataPoint.C.
treeDataPoint (const pointField & points, labelList && pointLabels, const bool useSubsetPoints = true)
Construct from subset of pointField, moves point ids.
Note
Holds reference to the points!
Definition at line 58 of file treeDataPoint.C.
Member Function Documentation
ClassName ("treeDataPoint")
bool empty () const inline
An empty effective point field?
Definition at line 171 of file treeDataPoint.H.
References UList< T >::size().
label size () const inline
The effective point field size.
Definition at line 184 of file treeDataPoint.H.
const pointField& points () const inline
The original point field.
Definition at line 197 of file treeDataPoint.H.
const labelList& pointLabels () const inline
The original point ids.
Definition at line 205 of file treeDataPoint.H.
Referenced by refinementFeatures::findNearestPoint().
bool useSubset () const inline
Use a subset of points.
Definition at line 213 of file treeDataPoint.H.
label pointLabel (const label index) const inline
The original (non-subset) point label.
Definition at line 221 of file treeDataPoint.H.
const point& shapePoint (const label index) const inline
Point at specified index.
Definition at line 234 of file treeDataPoint.H.
Referenced by treeDataPoint::findNearestOp::operator()(), and treeDataPoint::overlaps().
Foam::pointField shapePoints () const
Representative point cloud for all shapes inside (one point per shape)
Definition at line 88 of file treeDataPoint.C.
Foam::volumeType getVolumeType (const indexedOctree< treeDataPoint > & os, const point & sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 100 of file treeDataPoint.C.
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does (bb of) shape at index overlap bb.
Definition at line 110 of file treeDataPoint.C.
References volumeType::UNKNOWN.
bool overlaps (const label index, const point & centre, const scalar radiusSqr) const
Does shape at index overlap the sphere.
Definition at line 120 of file treeDataPoint.C.
References treeDataPoint::shapePoint().
const point& operator[] (const label index) const inline
The point at the specified index.
Definition at line 289 of file treeDataPoint.H.
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataPoint.H
src/meshTools/indexedOctree/treeDataPoint.C