OpenFOAM: pointMVCWeight Class Reference
pointMVCWeight Class Reference
Container to calculate weights for interpolating directly from vertices of cell using Mean Value Coordinates.
Public Member Functions
pointMVCWeight (const polyMesh &mesh, const vector &position, const label celli, const label facei=-1)
Construct from components.
label cell () const
Cell index.
const scalarField & weights () const
Interpolation weights (in order of cellPoints)
template<class Type >
Type interpolate (const GeometricField< Type, pointPatchField, pointMesh > &psip) const
Interpolate field.
Static Public Attributes
static int debug
Debug switch.
static scalar tol
Tolerance used in calculating barycentric coordinates.
Protected Member Functions
void calcWeights (const Map< label > &toLocal, const face &f, const DynamicList< point > &u, const scalarField &dist, scalarField &weights) const
Calculate weights from single face's vertices only.
void calcWeights (const polyMesh &mesh, const labelList &toGlobal, const Map< label > &toLocal, const vector &position, const vectorField &uVec, const scalarField &dist, scalarField &weights) const
Calculate weights from all cell's vertices.
Protected Attributes
const label cellIndex_
Cell index.
scalarField weights_
Weights applied to cell vertices.
Detailed Description
Container to calculate weights for interpolating directly from vertices of cell using Mean Value Coordinates.
Based on (VTK's vtkMeanValueCoordinatesInterpolator's) implementation of "Spherical Barycentric Coordinates" 2006 paper Eurographics Symposium on Geometry Processing by Torsten Langer, Alexander Belyaev and Hans-Peter Seide
Source files
pointMVCWeight.H
pointMVCWeight.C
Definition at line 65 of file pointMVCWeight.H.
Constructor & Destructor Documentation
pointMVCWeight (const polyMesh & mesh, const vector & position, const label celli, const label facei = -1)
Construct from components.
Definition at line 239 of file pointMVCWeight.C.
Member Function Documentation
void calcWeights (const Map< label > & toLocal, const face & f, const DynamicList< point > & u, const scalarField & dist, scalarField & weights) const protected
Calculate weights from single face's vertices only.
Definition at line 37 of file pointMVCWeight.C.
void calcWeights (const polyMesh & mesh, const labelList & toGlobal, const Map< label > & toLocal, const vector & position, const vectorField & uVec, const scalarField & dist, scalarField & weights) const protected
Calculate weights from all cell's vertices.
Definition at line 78 of file pointMVCWeight.C.
label cell () const inline
Cell index.
Definition at line 144 of file pointMVCWeight.H.
const scalarField& weights () const inline
Interpolation weights (in order of cellPoints)
Definition at line 152 of file pointMVCWeight.H.
Type interpolate (const GeometricField< Type, pointPatchField, pointMesh > & psip) const inline
Interpolate field.
Definition at line 27 of file pointMVCWeightI.H.
References pointMVCWeight::cellIndex_, forAll, i, DimensionedField< Type, GeoMesh >::mesh(), Foam::vertices(), pointMVCWeight::weights_, and Foam::Zero.
Referenced by interpolationPointMVC< Type >::interpolate().
Member Data Documentation
const label cellIndex_ protected
Cell index.
Definition at line 74 of file pointMVCWeight.H.
Referenced by pointMVCWeight::interpolate().
scalarField weights_ protected
Weights applied to cell vertices.
Definition at line 79 of file pointMVCWeight.H.
Referenced by pointMVCWeight::interpolate().
int debug static
Debug switch.
Definition at line 115 of file pointMVCWeight.H.
Foam::scalar tol static
Tolerance used in calculating barycentric coordinates.
(applied to normalised values)
Definition at line 122 of file pointMVCWeight.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.H
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.C
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeightI.H