OpenFOAM: CompositionModel< CloudType > Class Template Reference
CompositionModel< CloudType > Class Template Reference abstract
Composition
Templated reacting parcel composition model class Consists of carrier species (via thermo package), and additional liquids and solids.
Public Member Functions
TypeName ("compositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CompositionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
CompositionModel (CloudType &owner)
Construct null from owner.
CompositionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
CompositionModel (const CompositionModel< CloudType > &cm)
Construct copy.
virtual autoPtr
< CompositionModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~CompositionModel ()
Destructor.
const SLGThermo & thermo () const
Return the thermo database.
const basicSpecieMixture & carrier () const
Return the carrier components (wrapper function)
const liquidMixtureProperties & liquids () const
Return the global (additional) liquids.
const solidMixtureProperties & solids () const
Return the global (additional) solids.
const phasePropertiesList & phaseProps () const
Return the list of phase properties.
label nPhase () const
Return the number of phases.
const wordList & phaseTypes () const
Return the list of phase type names.
const wordList & stateLabels () const
Return the list of state labels (s), (l), (g) etc.
const wordList & componentNames (const label phaseI) const
Return the list of component names for phaseI.
label carrierId (const word &cmptName, const bool allowNotFound=false) const
Return global id of component cmptName in carrier thermo.
label localId (const label phaseI, const word &cmptName, const bool allowNotFound=false) const
Return local id of component cmptName in phase phaseI.
label localToCarrierId (const label phaseI, const label id, const bool allowNotFound=false) const
Return carrier id of component given local id.
const scalarField & Y0 (const label phaseI) const
Return the list of phase phaseI mass fractions.
tmp< scalarField > X (const label phaseI, const scalarField &Y) const
Return the list of phase phaseI volume fractions fractions.
virtual const scalarField & YMixture0 () const =0
Return the list of mixture mass fractions.
virtual label idGas () const =0
Gas id.
virtual label idLiquid () const =0
Liquid id.
virtual label idSolid () const =0
Solid id.
virtual scalar H (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return total enthalpy for the phase phaseI.
virtual scalar Hs (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return sensible enthalpy for the phase phaseI.
virtual scalar Hc (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return chemical enthalpy for the phase phaseI.
virtual scalar Cp (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return specific heat capacity for the phase phaseI.
virtual scalar L (const label phaseI, const scalarField &Y, const scalar p, const scalar T) const
Return latent heat for the phase phaseI.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
virtual fileName localPath () const
Output directory.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
bool getModelDict (const word &entryName, dictionary &dict) const
Retrieve dictionary, return true if set.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr
< CompositionModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::CompositionModel< CloudType >
Templated reacting parcel composition model class Consists of carrier species (via thermo package), and additional liquids and solids.
Source files
CompositionModel.H
CompositionModel.C
CompositionModelNew.C
Definition at line 54 of file ReactingCloud.H.
Constructor & Destructor Documentation
CompositionModel (CloudType & owner)
Construct null from owner.
Definition at line 26 of file CompositionModel.C.
CompositionModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from dictionary.
Definition at line 36 of file CompositionModel.C.
CompositionModel (const CompositionModel< CloudType > & cm)
Construct copy.
Definition at line 56 of file CompositionModel.C.
~CompositionModel () virtual
Destructor.
Definition at line 69 of file CompositionModel.C.
Member Function Documentation
TypeName ("compositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , CompositionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<CompositionModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in SingleMixtureFraction< CloudType >, SinglePhaseMixture< CloudType >, and NoComposition< CloudType >.
Foam::autoPtr< Foam::CompositionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 29 of file CompositionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
const Foam::SLGThermo & thermo () const
Return the thermo database.
Definition at line 76 of file CompositionModel.C.
const Foam::basicSpecieMixture & carrier () const
Return the carrier components (wrapper function)
Definition at line 84 of file CompositionModel.C.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc(), and ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation().
const Foam::liquidMixtureProperties & liquids () const
Return the global (additional) liquids.
Definition at line 92 of file CompositionModel.C.
const Foam::solidMixtureProperties & solids () const
Return the global (additional) solids.
Definition at line 100 of file CompositionModel.C.
const Foam::phasePropertiesList & phaseProps () const
Return the list of phase properties.
Definition at line 108 of file CompositionModel.C.
Foam::label nPhase () const
Return the number of phases.
Definition at line 115 of file CompositionModel.C.
const Foam::wordList & phaseTypes () const
Return the list of phase type names.
If only 1 phase, return the component names of that phase
Definition at line 122 of file CompositionModel.C.
const Foam::wordList & stateLabels () const
Return the list of state labels (s), (l), (g) etc.
Definition at line 137 of file CompositionModel.C.
const Foam::wordList & componentNames (const label phaseI) const
Return the list of component names for phaseI.
Definition at line 145 of file CompositionModel.C.
Foam::label carrierId (const word & cmptName, const bool allowNotFound = false) const
Return global id of component cmptName in carrier thermo.
Definition at line 153 of file CompositionModel.C.
References phasei.
Foam::label localId (const label phaseI, const word & cmptName, const bool allowNotFound = false) const
Return local id of component cmptName in phase phaseI.
Definition at line 175 of file CompositionModel.C.
Foam::label localToCarrierId (const label phaseI, const label id, const bool allowNotFound = false) const
Return carrier id of component given local id.
Definition at line 196 of file CompositionModel.C.
Referenced by ReactingMultiphaseParcel< ParcelType >::calcDevolatilisation().
const Foam::scalarField & Y0 (const label phaseI) const
Return the list of phase phaseI mass fractions.
Definition at line 218 of file CompositionModel.C.
Foam::tmp< Foam::scalarField > X (const label phaseI, const scalarField & Y) const
Return the list of phase phaseI volume fractions fractions.
based on supplied mass fractions Y
Definition at line 228 of file CompositionModel.C.
References phasei.
virtual const scalarField& YMixture0 () const pure virtual
Return the list of mixture mass fractions.
If only 1 phase, return component fractions of that phase
Implemented in SingleMixtureFraction< CloudType >, SinglePhaseMixture< CloudType >, and NoComposition< CloudType >.
virtual label idGas () const pure virtual
Gas id.
Implemented in SingleMixtureFraction< CloudType >, SinglePhaseMixture< CloudType >, and NoComposition< CloudType >.
virtual label idLiquid () const pure virtual
Liquid id.
Implemented in SingleMixtureFraction< CloudType >, SinglePhaseMixture< CloudType >, and NoComposition< CloudType >.
virtual label idSolid () const pure virtual
Solid id.
Implemented in SingleMixtureFraction< CloudType >, SinglePhaseMixture< CloudType >, and NoComposition< CloudType >.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc().
Foam::scalar H (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return total enthalpy for the phase phaseI.
Definition at line 272 of file CompositionModel.C.
Foam::scalar Hs (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return sensible enthalpy for the phase phaseI.
Definition at line 326 of file CompositionModel.C.
Foam::scalar Hc (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return chemical enthalpy for the phase phaseI.
Definition at line 381 of file CompositionModel.C.
Foam::scalar Cp (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return specific heat capacity for the phase phaseI.
Definition at line 432 of file CompositionModel.C.
Foam::scalar L (const label phaseI, const scalarField & Y, const scalar p, const scalar T) const virtual
Return latent heat for the phase phaseI.
Definition at line 482 of file CompositionModel.C.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ReactingCloud/ReactingCloud.H
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/CompositionModel/CompositionModel.H
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/CompositionModel/CompositionModel.C
src/lagrangian/intermediate/submodels/Reacting/CompositionModel/CompositionModel/CompositionModelNew.C