OpenFOAM: sixDoFRigidBodyMotionConstraint Class Reference
sixDoFRigidBodyMotionConstraint Class Reference abstract
Base class for defining constraints for sixDoF motions.
Public Member Functions
TypeName ("sixDoFRigidBodyMotionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFRigidBodyMotionConstraint, dictionary,(const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion),(name, sDoFRBMCDict, motion))
sixDoFRigidBodyMotionConstraint (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Construct from the sDoFRBMCDict dictionary and Time.
virtual autoPtr
< sixDoFRigidBodyMotionConstraint > clone () const =0
Construct and return a clone.
virtual ~sixDoFRigidBodyMotionConstraint ()
Destructor.
const word & name () const
Return the name.
virtual void setCentreOfRotation (point &) const
Set the centre of rotation if not the centre of mass.
virtual void constrainTranslation (pointConstraint &) const =0
Apply and accumulate translational constraints.
virtual void constrainRotation (pointConstraint &) const =0
Apply and accumulate rotational constraints.
virtual bool read (const dictionary &sDoFRBMCDict)
Update properties from given dictionary.
const dictionary & coeffDict () const
virtual void write (Ostream &) const
Write.
Static Public Member Functions
static autoPtr
< sixDoFRigidBodyMotionConstraint > New (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion)
Select constructed from the sDoFRBMCDict dictionary and Time.
Protected Attributes
word name_
Name of the constraint.
dictionary sDoFRBMCCoeffs_
Constraint model specific coefficient dictionary.
const sixDoFRigidBodyMotion & motion_
Reference to the body motion.
Detailed Description
Base class for defining constraints for sixDoF motions.
Source files
sixDoFRigidBodyMotionConstraint.H
sixDoFRigidBodyMotionConstraint.C
sixDoFRigidBodyMotionConstraintNew.C
Definition at line 64 of file sixDoFRigidBodyMotionConstraint.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotionConstraint (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion)
Construct from the sDoFRBMCDict dictionary and Time.
Definition at line 35 of file sixDoFRigidBodyMotionConstraint.C.
~sixDoFRigidBodyMotionConstraint () virtual
Destructor.
Definition at line 49 of file sixDoFRigidBodyMotionConstraint.C.
Member Function Documentation
TypeName ("sixDoFRigidBodyMotionConstraint")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , sixDoFRigidBodyMotionConstraint , dictionary , (const word &name, const dictionary &sDoFRBMCDict, const sixDoFRigidBodyMotion &motion) , (name, sDoFRBMCDict, motion))
virtual autoPtr<sixDoFRigidBodyMotionConstraint> clone () const pure virtual
Construct and return a clone.
Implemented in line, plane, point, axis, and orientation.
Foam::autoPtr< Foam::sixDoFRigidBodyMotionConstraint > New (const word & name, const dictionary & sDoFRBMCDict, const sixDoFRigidBodyMotion & motion) static
Select constructed from the sDoFRBMCDict dictionary and Time.
Definition at line 28 of file sixDoFRigidBodyMotionConstraintNew.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and sixDoFRigidBodyMotionConstraint::name().
const word& name () const inline
Return the name.
Definition at line 153 of file sixDoFRigidBodyMotionConstraint.H.
Referenced by sixDoFRigidBodyMotionConstraint::New().
virtual void setCentreOfRotation (point &) const inline virtual
Set the centre of rotation if not the centre of mass.
Reimplemented in point.
Definition at line 161 of file sixDoFRigidBodyMotionConstraint.H.
References sixDoFRigidBodyMotionConstraint::sDoFRBMCCoeffs_.
virtual void constrainTranslation (pointConstraint &) const pure virtual
Apply and accumulate translational constraints.
Implemented in line, plane, point, axis, and orientation.
virtual void constrainRotation (pointConstraint &) const pure virtual
Apply and accumulate rotational constraints.
Implemented in line, plane, point, axis, and orientation.
bool read (const dictionary & sDoFRBMCDict) virtual
Update properties from given dictionary.
Reimplemented in line, plane, point, axis, and orientation.
Definition at line 56 of file sixDoFRigidBodyMotionConstraint.C.
const dictionary& coeffDict () const inline
Definition at line 182 of file sixDoFRigidBodyMotionConstraint.H.
void write (Ostream & os) const virtual
Write.
Reimplemented in line, plane, point, axis, and orientation.
Definition at line 66 of file sixDoFRigidBodyMotionConstraint.C.
Member Data Documentation
word name_ protected
Name of the constraint.
Definition at line 74 of file sixDoFRigidBodyMotionConstraint.H.
dictionary sDoFRBMCCoeffs_ protected
Constraint model specific coefficient dictionary.
Definition at line 79 of file sixDoFRigidBodyMotionConstraint.H.
Referenced by sixDoFRigidBodyMotionConstraint::setCentreOfRotation().
const sixDoFRigidBodyMotion& motion_ protected
Reference to the body motion.
Definition at line 84 of file sixDoFRigidBodyMotionConstraint.H.
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/sixDoFRigidBodyMotionConstraint/sixDoFRigidBodyMotionConstraint.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/sixDoFRigidBodyMotionConstraint/sixDoFRigidBodyMotionConstraint.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/constraints/sixDoFRigidBodyMotionConstraint/sixDoFRigidBodyMotionConstraintNew.C