OpenFOAM: sootModel Class Reference
sootModel Class Reference abstract
Base class for soor models.
Public Member Functions
TypeName ("sootModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sootModel, dictionary,(const dictionary &dict, const fvMesh &mesh, const word &modelType),(dict, mesh, modelType))
Declare runtime constructor selection table.
sootModel (const dictionary &dict, const fvMesh &mesh, const word &modelType)
Construct from components.
virtual ~sootModel ()
Destructor.
const fvMesh & mesh () const
Reference to the mesh.
const dictionary & dict () const
Reference to the dictionary.
virtual void correct ()=0
Main update/correction routine.
virtual const volScalarField & soot () const =0
Return const reference to soot.
Static Public Member Functions
static autoPtr< sootModel > New (const dictionary &dict, const fvMesh &mesh)
Selector.
Protected Attributes
const dictionary dict_
Radiation model dictionary.
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
Base class for soor models.
Definition at line 49 of file sootModel.H.
Constructor & Destructor Documentation
sootModel (const dictionary & dict, const fvMesh & mesh, const word & modelType)
Construct from components.
Definition at line 37 of file sootModel.C.
~sootModel () virtual
Destructor.
Definition at line 50 of file sootModel.C.
Member Function Documentation
TypeName ("sootModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , sootModel , dictionary , (const dictionary &dict, const fvMesh &mesh, const word &modelType) , (dict, mesh, modelType))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::radiation::sootModel > New (const dictionary & dict, const fvMesh & mesh) static
Selector.
Definition at line 29 of file sootModelNew.C.
References sootModel::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, sootModel::mesh(), and dictionary::readIfPresent().
const fvMesh& mesh () const inline
Reference to the mesh.
Definition at line 128 of file sootModel.H.
Referenced by sootModel::New().
const dictionary& dict () const inline
Reference to the dictionary.
Definition at line 136 of file sootModel.H.
Referenced by sootModel::New().
virtual void correct () pure virtual
Main update/correction routine.
Implemented in mixtureFractionSoot< ThermoType >, and noSoot.
virtual const volScalarField& soot () const pure virtual
Return const reference to soot.
Implemented in mixtureFractionSoot< ThermoType >, and noSoot.
Member Data Documentation
const dictionary dict_ protected
Radiation model dictionary.
Definition at line 59 of file sootModel.H.
const fvMesh& mesh_ protected
Reference to the fvMesh.
Definition at line 64 of file sootModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/sootModel/sootModel/sootModel.H
src/thermophysicalModels/radiation/submodels/sootModel/sootModel/sootModel.C
src/thermophysicalModels/radiation/submodels/sootModel/sootModel/sootModelNew.C