OpenFOAM: Instant< T > Class Template Reference
Instant< T > Class Template Reference
A tuple of value and key. The value often corresponds to a time value, thus the naming of the class. The key will usually be a time name or a file name etc.
Classes
struct less
Less function for sorting.
Public Member Functions
Instant ()
Construct null, with value = 0.
Instant (scalar val, const T &key)
Copy construct from components.
Instant (scalar val, T &&key)
Move construct from components.
Instant (const Instant &)=default
Copy construct.
Instant (Instant &&)=default
Move construct.
scalar value () const
The value (const access)
scalar & value ()
The value (non-const access)
const T & name () const
The name/key (const access)
T & name ()
The name/key (non-const access)
bool equal (scalar val) const
True if values are equal (includes SMALL for rounding)
template<class T2 >
bool equal (const Instant< T2 > &other) const
True if values are equal (includes SMALL for rounding)
Instant & operator= (const Instant &)=default
Copy assignment.
Instant & operator= (Instant &&)=default
Move assignment.
Detailed Description
template<class T>
class Foam::Instant< T >
A tuple of value and key. The value often corresponds to a time value, thus the naming of the class. The key will usually be a time name or a file name etc.
Source files
Instant.H
Instant.C
Definition at line 49 of file Instant.H.
Constructor & Destructor Documentation
Instant ()
Construct null, with value = 0.
Definition at line 26 of file Instant.C.
Instant (scalar val, const T & key)
Copy construct from components.
Instant (scalar val, T && key)
Move construct from components.
Instant (const Instant< T > &) default
Copy construct.
Instant (Instant< T > &&) default
Move construct.
Member Function Documentation
scalar value () const inline
The value (const access)
Definition at line 113 of file Instant.H.
Referenced by seriesWriter::append(), Foam::operator!=(), seriesLess::operator()(), Instant< T >::less::operator()(), Foam::operator<(), timeSelector::selected(), ensightCase::setTime(), and ensightCase::write().
scalar& value () inline
The value (non-const access)
Definition at line 121 of file Instant.H.
const T& name () const inline
The name/key (const access)
Definition at line 129 of file Instant.H.
Referenced by seriesWriter::append(), and seriesLess::operator()().
T& name () inline
The name/key (non-const access)
Definition at line 137 of file Instant.H.
bool equal (scalar val) const
True if values are equal (includes SMALL for rounding)
Definition at line 52 of file Instant.C.
Referenced by Foam::operator!=(), and Foam::operator<().
bool equal (const Instant< T2 > & other) const
True if values are equal (includes SMALL for rounding)
Definition at line 60 of file Instant.C.
Instant& operator= (const Instant< T > &) default
Copy assignment.
Instant& operator= (Instant< T > &&) default
Move assignment.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/instant/Instant.H
src/OpenFOAM/db/Time/instant/Instant.C