OpenFOAM: basicCombustionMixture Class Reference
basicCombustionMixture Class Reference
Mixtures
Specialization of the basicSpecieMixture for combustion.
Public Types
typedef basicCombustionMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicSpecieMixture
typedef basicSpecieMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMultiComponentMixture
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
The base class of the mixture.
Public Member Functions
TypeName ("basicCombustionMixture")
Run time type information.
basicCombustionMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, specie names, mesh and phase name.
virtual ~basicCombustionMixture ()=default
Destructor.
scalar fres (const scalar ft, const scalar stoicRatio) const
tmp< volScalarField > fres (const volScalarField &ft, const dimensionedScalar &stoicRatio) const
Public Member Functions inherited from basicSpecieMixture
TypeName ("basicSpecieMixture")
Run time type information.
basicSpecieMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicSpecieMixture ()=default
Destructor.
virtual scalar W (const label speciei) const =0
Molecular weight of the given specie [kg/kmol].
virtual scalar Hc (const label speciei) const =0
Chemical enthalpy [J/kg].
virtual scalar Cp (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
virtual scalar Cv (const label speciei, const scalar p, const scalar T) const =0
Heat capacity at constant volume [J/(kg K)].
virtual scalar HE (const label speciei, const scalar p, const scalar T) const =0
Enthalpy/Internal energy [J/kg].
virtual scalar Ha (const label speciei, const scalar p, const scalar T) const =0
Absolute enthalpy [J/kg].
virtual scalar Hs (const label speciei, const scalar p, const scalar T) const =0
Sensible enthalpy [J/kg].
virtual scalar S (const label speciei, const scalar p, const scalar T) const =0
Entropy [J/(kg K)].
virtual scalar Es (const label speciei, const scalar p, const scalar T) const =0
Sensible internal energy [J/kg].
virtual scalar G (const label speciei, const scalar p, const scalar T) const =0
Gibbs free energy [J/kg].
virtual scalar A (const label speciei, const scalar p, const scalar T) const =0
Helmholtz free energy [J/kg].
virtual scalar mu (const label speciei, const scalar p, const scalar T) const =0
Dynamic viscosity [kg/m/s].
virtual scalar kappa (const label speciei, const scalar p, const scalar T) const =0
Thermal conductivity [W/m/K].
virtual scalar alphah (const label speciei, const scalar p, const scalar T) const =0
Thermal diffusivity of enthalpy [kg/m/s].
virtual scalar rho (const label speciei, const scalar p, const scalar T) const =0
Density [kg/m3].
Public Member Functions inherited from basicMultiComponentMixture
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()=default
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
Additional Inherited Members
Protected Attributes inherited from basicMultiComponentMixture
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
Specialization of the basicSpecieMixture for combustion.
Source files
basicCombustionMixture.H
basicCombustionMixture.C
Definition at line 49 of file basicCombustionMixture.H.
Member Typedef Documentation
typedef basicCombustionMixture basicMixtureType
The base class of the mixture.
Definition at line 65 of file basicCombustionMixture.H.
Constructor & Destructor Documentation
basicCombustionMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, specie names, mesh and phase name.
Definition at line 34 of file basicCombustionMixture.C.
virtual ~basicCombustionMixture () virtual default
Destructor.
Member Function Documentation
TypeName ("basicCombustionMixture")
Run time type information.
Foam::scalar fres (const scalar ft, const scalar stoicRatio) const inline
Definition at line 22 of file basicCombustionMixtureI.H.
Referenced by veryInhomogeneousMixture< ThermoType >::cellProducts(), and veryInhomogeneousMixture< ThermoType >::patchFaceReactants().
Foam::tmp< Foam::volScalarField > fres (const volScalarField & ft, const dimensionedScalar & stoicRatio) const inline
Definition at line 32 of file basicCombustionMixtureI.H.
References Foam::max().
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicCombustionMixture/basicCombustionMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicCombustionMixture/basicCombustionMixture.C
src/thermophysicalModels/reactionThermo/mixtures/basicCombustionMixture/basicCombustionMixtureI.H