OpenFOAM: base64Layer Class Reference
base64Layer Class Reference
An output filter layer to write base-64 encoded content.
Public Member Functions
base64Layer (std::ostream &os)
Construct and attach to an output stream.
~base64Layer ()
Destructor.
void write (const char *s, std::streamsize n)
Encode the character sequence, writing when possible.
void reset ()
Restart a new encoding sequence.
bool close ()
End the encoding sequence, padding the final characters with '='.
Static Public Member Functions
static std::size_t encodedLength (std::size_t n)
The encoded length has 4 bytes out for every 3 bytes in.
Protected Member Functions
void add (char c)
Add a character to the group, outputting when the group is full.
Detailed Description
An output filter layer to write base-64 encoded content.
Base64 encoding accoding to RFC 4648 specification (https://tools.ietf.org/html/rfc4648#page-5). It is the obligation of the caller to avoid using normal output while the base-64 encoding layer is actively used.
Source files
base64Layer.H
base64Layer.C
Definition at line 51 of file base64Layer.H.
Constructor & Destructor Documentation
base64Layer (std::ostream & os)
Construct and attach to an output stream.
Definition at line 100 of file base64Layer.C.
~base64Layer ()
Destructor.
Definition at line 111 of file base64Layer.C.
Member Function Documentation
void add (char c) protected
Add a character to the group, outputting when the group is full.
Definition at line 78 of file base64Layer.C.
Referenced by foamVtkBase64Layer::write().
std::size_t encodedLength (std::size_t n) static
The encoded length has 4 bytes out for every 3 bytes in.
Definition at line 45 of file base64Layer.C.
void write (const char * s, std::streamsize n)
Encode the character sequence, writing when possible.
Definition at line 119 of file base64Layer.C.
Referenced by foamVtkBase64Layer::foamVtkBase64Layer().
void reset ()
Restart a new encoding sequence.
Definition at line 128 of file base64Layer.C.
bool close ()
End the encoding sequence, padding the final characters with '='.
Return false if no encoding was actually performed.
Definition at line 135 of file base64Layer.C.
Referenced by foamVtkBase64Layer::encodedLength(), and foamVtkBase64Layer::encoding().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/hashes/base64Layer.H
src/OpenFOAM/db/IOstreams/hashes/base64Layer.C