OpenFOAM: wallPoints Class Reference
wallPoints Class Reference
For use with FaceCellWave. Determines topological distance to starting faces.
Public Member Functions
wallPoints ()
Construct null.
wallPoints (const UList< point > &origin, const UList< scalar > &distSqr, const UList< FixedList< label, 3 >> &surface)
Construct from count.
const List< point > & origin () const
const List< scalar > & distSqr () const
const List< FixedList< label, 3 > > & surface () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallPoints &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const wallPoints &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const wallPoints &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const wallPoints &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const wallPoints &, TrackingData &) const
Same (like operator==)
bool operator== (const wallPoints &) const
bool operator!= (const wallPoints &) const
Protected Member Functions
template<class TrackingData >
bool update (const point &pt, const label index1, const wallPoints &w2, const label index2, const scalar tol, TrackingData &td)
Originating normal.
Protected Attributes
DynamicList< point > origin_
Starting points.
DynamicList< scalar > distSqr_
Distance (squared) from cellcenter to origin.
DynamicList< FixedList< label, 3 > > surface_
Originating surface,region and topological region.
Friends
Ostream & operator<< (Ostream &, const wallPoints &)
Istream & operator>> (Istream &, wallPoints &)
Detailed Description
For use with FaceCellWave. Determines topological distance to starting faces.
Source files
wallPoints.H
wallPointsI.H
wallPoints.C
Definition at line 61 of file wallPoints.H.
Constructor & Destructor Documentation
wallPoints () inline
Construct null.
Definition at line 83 of file wallPointsI.H.
wallPoints (const UList< point > & origin, const UList< scalar > & distSqr, const UList< FixedList< label, 3 >> & surface) inline
Construct from count.
Definition at line 93 of file wallPointsI.H.
Member Function Documentation
bool update (const point & pt, const label index1, const wallPoints & w2, const label index2, const scalar tol, TrackingData & td) inline protected
Originating normal.
DynamicList<vector> normal_;
Evaluate distance to point. Update distSqr, origin from whomever
is nearer pt. Return true if w2 is closer to point, false otherwise.
Definition at line 28 of file wallPointsI.H.
References Foam::diff(), wallPoints::distSqr_, Foam::magSqr(), wallPoints::origin_, wallPoints::surface_, and wallPoints::valid().
const List<point>& origin () const inline
Definition at line 135 of file wallPoints.H.
const List<scalar>& distSqr () const inline
Definition at line 139 of file wallPoints.H.
const List<FixedList<label, 3> >& surface () const inline
Definition at line 144 of file wallPoints.H.
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 110 of file wallPointsI.H.
Referenced by wallPoints::update().
bool sameGeometry (const polyMesh & , const wallPoints & , const scalar , TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 119 of file wallPointsI.H.
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 133 of file wallPointsI.H.
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 167 of file wallPointsI.H.
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 151 of file wallPointsI.H.
bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const wallPoints & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 186 of file wallPointsI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const wallPoints & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 228 of file wallPointsI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const wallPoints & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 271 of file wallPointsI.H.
bool equal (const wallPoints & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 312 of file wallPointsI.H.
bool operator== (const wallPoints & rhs) const inline
Definition at line 324 of file wallPointsI.H.
bool operator!= (const wallPoints & rhs) const inline
Definition at line 337 of file wallPointsI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const wallPoints &) friend
Istream& operator>> (Istream & , wallPoints &) friend
Member Data Documentation
DynamicList<point> origin_ protected
Starting points.
Definition at line 70 of file wallPoints.H.
Referenced by wallPoints::update().
DynamicList<scalar> distSqr_ protected
Distance (squared) from cellcenter to origin.
Definition at line 75 of file wallPoints.H.
Referenced by wallPoints::update().
DynamicList<FixedList<label, 3> > surface_ protected
Originating surface,region and topological region.
Definition at line 80 of file wallPoints.H.
Referenced by wallPoints::update().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/meshRefinement/wallPoints.H
src/mesh/snappyHexMesh/meshRefinement/wallPointsI.H