OpenFOAM: STLAsciiParse Class Reference
STLAsciiParse Class Reference
Internal class used when parsing STL ASCII format.
Public Member Functions
STLAsciiParse (const label approxNpoints)
From input stream and the approximate number of vertices in the STL.
void clear ()
Reset stored values.
bool sorted () const
Do all the solid groups appear in order?
DynamicList< STLpoint > & points ()
A list of unstitched triangle points.
DynamicList< label > & facets ()
A list of facet IDs (group IDs) corresponds to the number of triangles.
DynamicList< word > & names ()
Solid names in the order of their appearance.
DynamicList< label > & sizes ()
Solid sizes in the order of their appearance.
Protected Member Functions
void beginSolid (word solidName)
Action when entering 'solid'.
void beginFacet ()
Action when entering 'facet'.
void resetVertex ()
Reset vertex component to zero.
bool addVertexComponent (float val)
Add next vertex component. On each third call, adds the point.
bool addVertexComponent (const char *text)
Add next vertex component. On each third call, adds the point.
void endFacet ()
Action on 'endfacet'.
STLAsciiParse (const STLAsciiParse &)=delete
No copy construct.
void operator= (const STLAsciiParse &)=delete
No copy assignment.
Protected Attributes
bool sorted_
label groupId_
label lineNum_
int nFacetPoints_
The number of local points on the current facet.
int nVertexCmpt_
Current vertex component when reading 'vertex'.
STLpoint currVertex_
Scratch space for reading 'vertex'.
DynamicList< STLpoint > points_
DynamicList< label > facets_
DynamicList< word > names_
DynamicList< label > sizes_
HashTable< label > nameLookup_
Detailed Description
Internal class used when parsing STL ASCII format.
Source files
STLAsciiParse.H
STLAsciiParse.C
Definition at line 50 of file STLAsciiParse.H.
Constructor & Destructor Documentation
STLAsciiParse (const STLAsciiParse &) protected delete
No copy construct.
STLAsciiParse (const label approxNpoints) inline
From input stream and the approximate number of vertices in the STL.
Definition at line 128 of file STLAsciiParseI.H.
Member Function Documentation
void beginSolid (word solidName) inline protected
Action when entering 'solid'.
Definition at line 23 of file STLAsciiParseI.H.
References DynamicList< T, SizeMin >::append(), HashTable< T, Key, Hash >::cfind(), STLAsciiParse::groupId_, HashTable< T, Key, Hash >::insert(), iter, STLAsciiParse::nameLookup_, STLAsciiParse::names_, UList< T >::size(), STLAsciiParse::sizes_, and STLAsciiParse::sorted_.
void beginFacet () inline protected
Action when entering 'facet'.
Definition at line 56 of file STLAsciiParseI.H.
void resetVertex () inline protected
Reset vertex component to zero.
Definition at line 63 of file STLAsciiParseI.H.
bool addVertexComponent (float val) inline protected
Add next vertex component. On each third call, adds the point.
Returns
true when point has been added (on the last component)
Definition at line 69 of file STLAsciiParseI.H.
bool addVertexComponent (const char * text) inline protected
Add next vertex component. On each third call, adds the point.
Returns
true when point has been added (on the last component)
> safer, but slower: readFloat(text, currVertex_[nVertexCmpt_]);
Definition at line 84 of file STLAsciiParseI.H.
void endFacet () inline protected
Action on 'endfacet'.
Definition at line 102 of file STLAsciiParseI.H.
void operator= (const STLAsciiParse &) protected delete
No copy assignment.
void clear () inline
Reset stored values.
Definition at line 142 of file STLAsciiParseI.H.
bool sorted () const inline
Do all the solid groups appear in order?
Definition at line 159 of file STLAsciiParseI.H.
Foam::DynamicList< Foam::STLpoint > & points () inline
A list of unstitched triangle points.
Definition at line 165 of file STLAsciiParseI.H.
Foam::DynamicList< Foam::label > & facets () inline
A list of facet IDs (group IDs) corresponds to the number of triangles.
Definition at line 171 of file STLAsciiParseI.H.
Foam::DynamicList< Foam::word > & names () inline
Solid names in the order of their appearance.
Definition at line 177 of file STLAsciiParseI.H.
Foam::DynamicList< Foam::label > & sizes () inline
Solid sizes in the order of their appearance.
Definition at line 183 of file STLAsciiParseI.H.
Member Data Documentation
bool sorted_ protected
Definition at line 56 of file STLAsciiParse.H.
Referenced by STLAsciiParse::beginSolid().
label groupId_ protected
Definition at line 57 of file STLAsciiParse.H.
Referenced by STLAsciiParse::beginSolid().
label lineNum_ protected
Definition at line 58 of file STLAsciiParse.H.
int nFacetPoints_ protected
The number of local points on the current facet.
Definition at line 63 of file STLAsciiParse.H.
int nVertexCmpt_ protected
Current vertex component when reading 'vertex'.
Definition at line 68 of file STLAsciiParse.H.
STLpoint currVertex_ protected
Scratch space for reading 'vertex'.
Definition at line 73 of file STLAsciiParse.H.
DynamicList<STLpoint> points_ protected
Definition at line 75 of file STLAsciiParse.H.
DynamicList<label> facets_ protected
Definition at line 76 of file STLAsciiParse.H.
DynamicList<word> names_ protected
Definition at line 77 of file STLAsciiParse.H.
Referenced by STLAsciiParse::beginSolid().
DynamicList<label> sizes_ protected
Definition at line 78 of file STLAsciiParse.H.
Referenced by STLAsciiParse::beginSolid().
HashTable<label> nameLookup_ protected
Definition at line 79 of file STLAsciiParse.H.
Referenced by STLAsciiParse::beginSolid().
The documentation for this class was generated from the following files:
src/fileFormats/stl/STLAsciiParse.H
src/fileFormats/stl/STLAsciiParseI.H