OpenFOAM: uncollatedFileOperation Class Reference
uncollatedFileOperation Class Reference
fileOperation that assumes file operations are local.
Public Member Functions
TypeName ("uncollated")
Runtime type information.
uncollatedFileOperation (bool verbose)
Construct null.
virtual ~uncollatedFileOperation ()=default
Destructor.
virtual bool mkDir (const fileName &, mode_t=0777) const
Make directory.
virtual bool chMod (const fileName &, const mode_t) const
Set the file mode.
virtual mode_t mode (const fileName &, const bool followLink=true) const
Return the file mode.
virtual fileName::Type type (const fileName &, const bool followLink=true) const
Return the file type: DIRECTORY, FILE or LINK.
virtual bool exists (const fileName &, const bool checkGzip=true, const bool followLink=true) const
Does the name exist (as DIRECTORY or FILE) in the file system?
virtual bool isDir (const fileName &, const bool followLink=true) const
Does the name exist as a DIRECTORY in the file system?
virtual bool isFile (const fileName &, const bool checkGzip=true, const bool followLink=true) const
Does the name exist as a FILE in the file system?
virtual off_t fileSize (const fileName &, const bool followLink=true) const
Return size of file.
virtual time_t lastModified (const fileName &, const bool followLink=true) const
Return time of last file modification.
virtual double highResLastModified (const fileName &, const bool followLink=true) const
Return time of last file modification.
virtual fileNameList readDir (const fileName &, const fileName::Type=fileName::FILE, const bool filtergz=true, const bool followLink=true) const
Read a directory and return the entries as a string list.
virtual bool cp (const fileName &src, const fileName &dst, const bool followLink=true) const
Copy, recursively if necessary, the source to the destination.
virtual bool ln (const fileName &src, const fileName &dst) const
Create a softlink. dst should not exist. Returns true if.
virtual bool mv (const fileName &src, const fileName &dst, const bool followLink=false) const
Rename src to dst.
virtual bool mvBak (const fileName &, const std::string &ext="bak") const
Rename to a corresponding backup file.
virtual bool rm (const fileName &) const
Remove a file, returning true if successful otherwise false.
virtual bool rmDir (const fileName &dir, const bool silent=false) const
Remove a directory and its contents.
virtual fileName filePath (const bool checkGlobal, const IOobject &io, const word &typeName, const bool search) const
Search for an object. checkGlobal : also check undecomposed case.
virtual fileName dirPath (const bool checkGlobal, const IOobject &io, const bool search) const
Search for a directory. checkGlobal : also check undecomposed.
virtual fileNameList readObjects (const objectRegistry &db, const fileName &instance, const fileName &local, word &newInstance) const
Search directory for objects. Used in IOobjectList.
virtual bool readHeader (IOobject &, const fileName &, const word &typeName) const
Read object header from supplied file.
virtual autoPtr< ISstream > readStream (regIOobject &, const fileName &, const word &typeName, const bool procValid=true) const
Reads header for regIOobject and returns an ISstream.
virtual bool read (regIOobject &, const bool masterOnly, const IOstream::streamFormat format, const word &typeName) const
Top-level read.
virtual autoPtr< ISstream > NewIFstream (const fileName &) const
Generate an ISstream that reads a file.
virtual autoPtr< Ostream > NewOFstream (const fileName &pathname, IOstream::streamFormat format=IOstream::ASCII, IOstream::versionNumber version=IOstream::currentVersion, IOstream::compressionType compression=IOstream::UNCOMPRESSED, const bool valid=true) const
Generate an Ostream that writes a file.
Public Member Functions inherited from fileOperation
TypeName ("fileOperation")
Runtime type information.
fileOperation (const label comm)
Construct from communicator.
declareRunTimeSelectionTable (autoPtr, fileOperation, word,(bool verbose),(verbose))
virtual ~fileOperation ()=default
Destructor.
virtual fileName objectPath (const IOobject &io, const word &typeName) const
Generate disk file name for object. Opposite of filePath.
virtual bool writeObject (const regIOobject &, IOstream::streamFormat format=IOstream::ASCII, IOstream::versionNumber version=IOstream::currentVersion, IOstream::compressionType compression=IOstream::UNCOMPRESSED, const bool valid=true) const
Writes a regIOobject (so header, contents and divider).
virtual fileName filePath (const fileName &) const
Search for a file or directory. Use IOobject version in.
virtual label addWatch (const fileName &) const
Add watching of a file. Returns handle.
virtual bool removeWatch (const label) const
Remove watch on a file (using handle)
virtual label findWatch (const labelList &watchIndices, const fileName &) const
Find index (or -1) of file in list of handles.
virtual void addWatches (regIOobject &, const fileNameList &) const
Helper: add watches for list of regIOobjects.
virtual fileName getFile (const label) const
Get name of file being watched (using handle)
virtual void updateStates (const bool masterOnly, const bool syncPar) const
Update state of all files.
virtual fileMonitor::fileState getState (const label) const
Get current state of file (using handle)
virtual void setUnmodified (const label) const
Set current state of file (using handle) to unmodified.
virtual word processorsDir (const IOobject &io) const
Actual name of processors dir (for use in mode PROCOBJECT,.
virtual word processorsDir (const fileName &) const
Actual name of processors dir (for use in mode PROCOBJECT,.
virtual void setNProcs (const label nProcs)
Set number of processor directories/results. Only used in.
virtual label nProcs (const fileName &dir, const fileName &local="") const
Get number of processor directories/results. Used for e.g.
virtual instantList findTimes (const fileName &, const word &) const
Get sorted list of times.
virtual IOobject findInstance (const IOobject &io, const scalar startValue, const word &stopInstance) const
Find instance where IOobject is. Fails if cannot be found.
virtual void setTime (const Time &) const
Callback for time change.
virtual void flush () const
Forcibly wait until all output done. Flush any cached data.
fileName processorsCasePath (const IOobject &, const word &procDir) const
Generate path (like io.path) from root+casename with any.
fileName processorsPath (const IOobject &, const word &instance, const word &procDir) const
Generate path (like io.path) with provided instance and any.
fileName processorsPath (const fileName &, const word &procDir) const
Operating on fileName: replace processorXXX with procDir.
Protected Member Functions
fileName filePathInfo (const bool checkGlobal, const bool isFile, const IOobject &io, const bool search) const
Search for an object.
virtual tmpNrc< dirIndexList > lookupProcessorsPath (const fileName &) const
Lookup name of processorsDDD using cache. Return empty fileName.
Protected Member Functions inherited from fileOperation
fileMonitor & monitor () const
tmpNrc< dirIndexList > lookupAndCacheProcessorsPath (const fileName &, const bool syncPar) const
Lookup name of processorsDDD using cache. Return empty fileName.
bool exists (IOobject &io) const
Does ioobject exist. Is either a directory (empty name()) or.
Additional Inherited Members
Public Types inherited from fileOperation
enum pathType {
NOTFOUND, ABSOLUTE, OBJECT, WRITEOBJECT,
PROCUNCOLLATED, PROCBASEOBJECT, PROCOBJECT, PARENTOBJECT,
FINDINSTANCE, PROCUNCOLLATEDINSTANCE, PROCBASEINSTANCE, PROCINSTANCE
}
Enumeration for the location of an IOobject.
typedef Tuple2< fileName,
Tuple2< pathType, label > > dirIndex
typedef List< dirIndex > dirIndexList
Static Public Member Functions inherited from fileOperation
static autoPtr< fileOperation > New (const word &handlerType, bool verbose=false)
Select fileHandler-type.
static label splitProcessorPath (const fileName &, fileName &path, fileName &procDir, fileName &local, label &groupStart, label &groupSize, label &nProcs)
Split fileName into part before 'processor' and part after.
static label detectProcessorPath (const fileName &)
Detect processor number from '/aa/bb/processorDDD/cc'.
Static Public Attributes inherited from fileOperation
static const Enum< pathType > pathTypeNames_
static word processorsBaseDir = "processors"
Return the processors directory name (usually "processors")
static word defaultFileHandler
Default fileHandler.
static autoPtr< fileOperation > fileHandlerPtr_
Static fileOperation.
Static Protected Member Functions inherited from fileOperation
static instantList sortTimes (const fileNameList &, const word &)
Sort directory entries according to time value.
static void mergeTimes (const instantList &extraTimes, const word &constantName, instantList &times)
Merge two times.
static bool isFileOrDir (const bool isFile, const fileName &)
Helper: check for file (isFile) or directory (!isFile)
Protected Attributes inherited from fileOperation
const label comm_
Communicator to use.
HashTable< dirIndexList > procsDirs_
Detected processors directories.
autoPtr< fileMonitor > monitorPtr_
file-change monitor for all registered files
Detailed Description
fileOperation that assumes file operations are local.
Definition at line 44 of file uncollatedFileOperation.H.
Constructor & Destructor Documentation
uncollatedFileOperation (bool verbose)
Construct null.
Definition at line 175 of file uncollatedFileOperation.C.
virtual ~uncollatedFileOperation () virtual default
Destructor.
Member Function Documentation
Foam::fileName filePathInfo (const bool checkGlobal, const bool isFile, const IOobject & io, const bool search) const protected
Search for an object.
checkGlobal : also check undecomposed case isFile : true:check for file false:check for directory
Definition at line 53 of file uncollatedFileOperation.C.
Foam::tmpNrc< Foam::fileOperation::dirIndexList > lookupProcessorsPath (const fileName & fName) const protected virtual
Lookup name of processorsDDD using cache. Return empty fileName.
if not found. Do not use any parallel synchronisation
Reimplemented from fileOperation.
Definition at line 163 of file uncollatedFileOperation.C.
TypeName ("uncollated")
Runtime type information.
bool mkDir (const fileName & dir, mode_t mode = 0777) const virtual
Make directory.
Implements fileOperation.
Definition at line 192 of file uncollatedFileOperation.C.
bool chMod (const fileName & fName, const mode_t mode) const virtual
Set the file mode.
Implements fileOperation.
Definition at line 202 of file uncollatedFileOperation.C.
References Foam::mkDir(), and Foam::mode().
mode_t mode (const fileName & fName, const bool followLink = true) const virtual
Return the file mode.
Implements fileOperation.
Definition at line 212 of file uncollatedFileOperation.C.
References Foam::chMod(), and Foam::mode().
Foam::fileName::Type type (const fileName & fName, const bool followLink = true) const virtual
Return the file type: DIRECTORY, FILE or LINK.
Implements fileOperation.
Definition at line 222 of file uncollatedFileOperation.C.
References Foam::mode().
bool exists (const fileName & fName, const bool checkGzip = true, const bool followLink = true) const virtual
Does the name exist (as DIRECTORY or FILE) in the file system?
Optionally enable/disable check for gzip file.
Implements fileOperation.
Definition at line 232 of file uncollatedFileOperation.C.
References Foam::type().
bool isDir (const fileName & fName, const bool followLink = true) const virtual
Does the name exist as a DIRECTORY in the file system?
Implements fileOperation.
Definition at line 243 of file uncollatedFileOperation.C.
References Foam::exists().
bool isFile (const fileName & fName, const bool checkGzip = true, const bool followLink = true) const virtual
Does the name exist as a FILE in the file system?
Optionally enable/disable check for gzip file.
Implements fileOperation.
Definition at line 253 of file uncollatedFileOperation.C.
References Foam::isDir().
off_t fileSize (const fileName & fName, const bool followLink = true) const virtual
Return size of file.
Implements fileOperation.
Definition at line 264 of file uncollatedFileOperation.C.
References Foam::isFile().
time_t lastModified (const fileName & fName, const bool followLink = true) const virtual
Return time of last file modification.
Implements fileOperation.
Definition at line 274 of file uncollatedFileOperation.C.
References Foam::fileSize().
double highResLastModified (const fileName & fName, const bool followLink = true) const virtual
Return time of last file modification.
Implements fileOperation.
Definition at line 284 of file uncollatedFileOperation.C.
References Foam::lastModified().
Foam::fileNameList readDir (const fileName & dir, const fileName::Type type = fileName::FILE, const bool filtergz = true, const bool followLink = true) const virtual
Read a directory and return the entries as a string list.
Implements fileOperation.
Definition at line 323 of file uncollatedFileOperation.C.
References Foam::rmDir().
bool cp (const fileName & src, const fileName & dst, const bool followLink = true) const virtual
Copy, recursively if necessary, the source to the destination.
Implements fileOperation.
Definition at line 335 of file uncollatedFileOperation.C.
References Foam::readDir().
bool ln (const fileName & src, const fileName & dst) const virtual
Create a softlink. dst should not exist. Returns true if.
successful.
Implements fileOperation.
Definition at line 346 of file uncollatedFileOperation.C.
References Foam::cp().
bool mv (const fileName & src, const fileName & dst, const bool followLink = false) const virtual
Rename src to dst.
Implements fileOperation.
Definition at line 356 of file uncollatedFileOperation.C.
References Foam::ln().
bool mvBak (const fileName & fName, const std::string & ext = "bak") const virtual
Rename to a corresponding backup file.
If the backup file already exists, attempt with "01" .. "99" suffix
Implements fileOperation.
Definition at line 294 of file uncollatedFileOperation.C.
References Foam::highResLastModified().
bool rm (const fileName & fName) const virtual
Remove a file, returning true if successful otherwise false.
Implements fileOperation.
Definition at line 304 of file uncollatedFileOperation.C.
References ext(), and Foam::mvBak().
bool rmDir (const fileName & dir, const bool silent = false) const virtual
Remove a directory and its contents.
Implements fileOperation.
Definition at line 313 of file uncollatedFileOperation.C.
References Foam::rm().
Foam::fileName filePath (const bool checkGlobal, const IOobject & io, const word & typeName, const bool search) const virtual
Search for an object. checkGlobal : also check undecomposed case.
Implements fileOperation.
Definition at line 367 of file uncollatedFileOperation.C.
References Foam::mv().
Foam::fileName dirPath (const bool checkGlobal, const IOobject & io, const bool search) const virtual
Search for a directory. checkGlobal : also check undecomposed.
case
Implements fileOperation.
Definition at line 395 of file uncollatedFileOperation.C.
Foam::fileNameList readObjects (const objectRegistry & db, const fileName & instance, const fileName & local, word & newInstance) const virtual
Search directory for objects. Used in IOobjectList.
Use non-time searching version
Reimplemented from fileOperation.
Definition at line 422 of file uncollatedFileOperation.C.
bool readHeader (IOobject & io, const fileName & fName, const word & typeName) const virtual
Read object header from supplied file.
Implements fileOperation.
Definition at line 473 of file uncollatedFileOperation.C.
Foam::autoPtr< Foam::ISstream > readStream (regIOobject & io, const fileName & fName, const word & typeName, const bool procValid = true) const virtual
Reads header for regIOobject and returns an ISstream.
to read the contents.
Implements fileOperation.
Definition at line 526 of file uncollatedFileOperation.C.
bool read (regIOobject & io, const bool masterOnly, const IOstream::streamFormat format, const word & typeName) const virtual
Top-level read.
Implements fileOperation.
Definition at line 615 of file uncollatedFileOperation.C.
Foam::autoPtr< Foam::ISstream > NewIFstream (const fileName & filePath) const virtual
Generate an ISstream that reads a file.
Implements fileOperation.
Definition at line 709 of file uncollatedFileOperation.C.
Foam::autoPtr< Foam::Ostream > NewOFstream (const fileName & pathname, IOstream::streamFormat format = IOstream::ASCII, IOstream::versionNumber version = IOstream::currentVersion, IOstream::compressionType compression = IOstream::UNCOMPRESSED, const bool valid = true) const virtual
Generate an Ostream that writes a file.
Implements fileOperation.
Definition at line 719 of file uncollatedFileOperation.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/fileOperations/uncollatedFileOperation/uncollatedFileOperation.H
src/OpenFOAM/global/fileOperations/uncollatedFileOperation/uncollatedFileOperation.C