OpenFOAM: lumpedPointState Class Reference
lumpedPointState Class Reference
The state of lumped points corresponds to positions and rotations.
Public Types
enum inputFormatType { PLAIN, DICTIONARY }
Input format types.
Public Member Functions
lumpedPointState ()
Construct null.
lumpedPointState (const lumpedPointState &rhs)
Copy constructor.
lumpedPointState (const pointField &pts)
Construct from points with zero-rotation.
lumpedPointState (tmp< pointField > &pts)
Construct from points with zero-rotation.
lumpedPointState (const dictionary &dict)
Construct from dictionary.
virtual ~lumpedPointState ()
Destructor.
bool valid () const
Has positions and consistent number of rotations?
bool empty () const
If no points were specified.
label size () const
The number of points.
const pointField & points () const
The points corresponding to mass centres.
const vectorField & angles () const
The orientation of the points (mass centres)
const tensorField & rotations () const
The local-to-global transformation for each point.
void scalePoints (const scalar scaleFactor)
Scale points by given factor.
void relax (const scalar alpha, const lumpedPointState &prev)
Relax the state.
bool readData (Istream &is)
Read input as dictionary content.
bool writeData (Ostream &os) const
Output as dictionary content.
void writeDict (Ostream &os) const
Output as dictionary content.
bool readPlain (Istream &is)
Read input as plain content.
void writePlain (Ostream &os) const
Output as plain content.
bool readData (const inputFormatType &fmt, const fileName &file)
Read input from file (master process only) using specified format.
void writeVTP (const fileName &outputFile, const vector &axis) const
Output as VTK file for debugging/visualization.
void operator= (const lumpedPointState &rhs)
Assignment operator.
Static Public Attributes
static const Enum
< inputFormatType > formatNames
Names for the input format types.
Detailed Description
The state of lumped points corresponds to positions and rotations.
This class encapsulates the response from the external application and serves as the entry point for applying relaxation, sub-stepping etc.
Dictionary input format
Property Description Required Default
points List of points yes
angles List of Euler rotation angles yes
order The Euler-angle rotation order no zxz
degrees Rotation angles in degrees no false
Plain input format. Blank and comment lines starting with a '#' character are ignored. The angles are always in radians.
    NumPoints
    x0 y0 z0 eulerz0 eulerx'0 eulerz''0
    x1 y1 z1 eulerz1 eulerx'1 eulerz''1
    ...
See Also
Foam::coordinateRotations::euler, Foam::quaternion
Source files
lumpedPointState.H
lumpedPointState.C
lumpedPointStateI.H
Definition at line 107 of file lumpedPointState.H.
Member Enumeration Documentation
enum inputFormatType strong
Input format types.
Enumerator
PLAIN
"plain" is a simple ASCII format
DICTIONARY
"dictionary" is the OpenFOAM dictionary format
Definition at line 114 of file lumpedPointState.H.
Constructor & Destructor Documentation
lumpedPointState ()
Construct null.
Definition at line 98 of file lumpedPointState.C.
lumpedPointState (const lumpedPointState & rhs)
Copy constructor.
Definition at line 108 of file lumpedPointState.C.
lumpedPointState (const pointField & pts)
Construct from points with zero-rotation.
Definition at line 118 of file lumpedPointState.C.
lumpedPointState (tmp< pointField > & pts)
Construct from points with zero-rotation.
Definition at line 128 of file lumpedPointState.C.
lumpedPointState (const dictionary & dict)
Construct from dictionary.
Definition at line 138 of file lumpedPointState.C.
~lumpedPointState () virtual
Destructor.
Definition at line 152 of file lumpedPointState.C.
Member Function Documentation
bool valid () const inline
Has positions and consistent number of rotations?
Definition at line 21 of file lumpedPointStateI.H.
bool empty () const inline
If no points were specified.
Definition at line 27 of file lumpedPointStateI.H.
References UList< T >::size().
Foam::label size () const inline
The number of points.
Definition at line 33 of file lumpedPointStateI.H.
const Foam::pointField & points () const inline
The points corresponding to mass centres.
Definition at line 39 of file lumpedPointStateI.H.
Referenced by lumpedPointMovement::displacePoints().
const Foam::vectorField & angles () const inline
The orientation of the points (mass centres)
Definition at line 45 of file lumpedPointStateI.H.
const Foam::tensorField & rotations () const inline
The local-to-global transformation for each point.
Definition at line 51 of file lumpedPointStateI.H.
Referenced by lumpedPointMovement::displacePoints().
void scalePoints (const scalar scaleFactor)
Scale points by given factor.
Zero and negative values are ignored.
Definition at line 171 of file lumpedPointState.C.
void relax (const scalar alpha, const lumpedPointState & prev)
Relax the state.
alpha = 1 : no relaxation alpha < 1 : relaxation alpha = 0 : do nothing
Definition at line 181 of file lumpedPointState.C.
bool readData (Istream & is)
Read input as dictionary content.
Definition at line 249 of file lumpedPointState.C.
Referenced by lumpedPointMovement::readState().
bool writeData (Ostream & os) const
Output as dictionary content.
Definition at line 258 of file lumpedPointState.C.
void writeDict (Ostream & os) const
Output as dictionary content.
Definition at line 265 of file lumpedPointState.C.
bool readPlain (Istream & is)
Read input as plain content.
Definition at line 209 of file lumpedPointState.C.
void writePlain (Ostream & os) const
Output as plain content.
Definition at line 280 of file lumpedPointState.C.
References Ostream::writeEntry().
bool readData (const inputFormatType & fmt, const fileName & file)
Read input from file (master process only) using specified format.
Definition at line 307 of file lumpedPointState.C.
void writeVTP (const fileName & outputFile, const vector & axis) const
Output as VTK file for debugging/visualization.
The points are joined as lines, the rotation is visualized by planes, write as VTK PolyData format.
Definition at line 43 of file lumpedPointStateWriter.C.
Referenced by lumpedPointMovement::writeForcesAndMomentsVTP().
void operator= (const lumpedPointState & rhs)
Assignment operator.
Definition at line 160 of file lumpedPointState.C.
References Foam::deleteDemandDrivenData().
Member Data Documentation
const Foam::Enum< Foam::lumpedPointState::inputFormatType > formatNames static
Names for the input format types.
Definition at line 125 of file lumpedPointState.H.
Referenced by lumpedPointMovement::readDict().
The documentation for this class was generated from the following files:
src/lumpedPointMotion/state/lumpedPointState.H
src/lumpedPointMotion/state/lumpedPointState.C
src/lumpedPointMotion/state/lumpedPointStateI.H
src/lumpedPointMotion/state/lumpedPointStateWriter.C