OpenFOAM: Pstream Class Reference
Pstream Class Reference
Inter-processor communications stream.
Public Member Functions
ClassName ("Pstream")
Pstream (const commsTypes commsType, const label bufSize=0)
Construct given optional buffer size.
Public Member Functions inherited from UPstream
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Static Public Member Functions
template<class T , class BinaryOp >
static void gather (const List< commsStruct > &comms, T &Value, const BinaryOp &bop, const int tag, const label comm)
Gather data. Apply bop to combine Value.
template<class T , class BinaryOp >
static void gather (T &Value, const BinaryOp &bop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void scatter (const List< commsStruct > &comms, T &Value, const int tag, const label comm)
Scatter data. Distribute without modification. Reverse of gather.
template<class T >
static void scatter (T &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T , class CombineOp >
static void combineGather (const List< commsStruct > &comms, T &Value, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void combineGather (T &Value, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void combineScatter (const List< commsStruct > &comms, T &Value, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class T >
static void combineScatter (T &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T , class CombineOp >
static void listCombineGather (const List< commsStruct > &comms, List< T > &Value, const CombineOp &cop, const int tag, const label comm)
template<class T , class CombineOp >
static void listCombineGather (List< T > &Value, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void listCombineScatter (const List< commsStruct > &comms, List< T > &Value, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class T >
static void listCombineScatter (List< T > &Value, const int tag=Pstream::msgType(), const label comm=Pstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container , class CombineOp >
static void mapCombineGather (const List< commsStruct > &comms, Container &Values, const CombineOp &cop, const int tag, const label comm)
template<class Container , class CombineOp >
static void mapCombineGather (Container &Values, const CombineOp &cop, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container >
static void mapCombineScatter (const List< commsStruct > &comms, Container &Values, const int tag, const label comm)
Scatter data. Reverse of combineGather.
template<class Container >
static void mapCombineScatter (Container &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void gatherList (const List< commsStruct > &comms, List< T > &Values, const int tag, const label comm)
Gather data but keep individual values separate.
template<class T >
static void gatherList (List< T > &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class T >
static void scatterList (const List< commsStruct > &comms, List< T > &Values, const int tag, const label comm)
Scatter data. Reverse of gatherList.
template<class T >
static void scatterList (List< T > &Values, const int tag=Pstream::msgType(), const label comm=UPstream::worldComm)
Like above but switches between linear/tree communication.
template<class Container , class T >
static void exchange (const UList< Container > &sendData, const labelUList &recvSizes, List< Container > &recvData, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool block=true)
Helper: exchange contiguous data. Sends sendData, receives into.
template<class Container >
static void exchangeSizes (const Container &sendData, labelList &sizes, const label comm=UPstream::worldComm)
Helper: exchange sizes of sendData. sendData is the data per.
template<class Container , class T >
static void exchange (const UList< Container > &sendData, List< Container > &recvData, const int tag=UPstream::msgType(), const label comm=UPstream::worldComm, const bool block=true)
Exchange contiguous data. Sends sendData, receives into.
Static Public Member Functions inherited from UPstream
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in worldComm) given communicator and procssor.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor number) (= reverse of baseProcNo)
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number and communicator)
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library adds/requires on the command line.
static bool init (int &argc, char **&argv, const bool needsThread)
Initialisation function called from main.
static bool initNull ()
Special purpose initialisation function.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static bool haveThreads ()
Have support for threads.
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static constexpr int masterNo () noexcept
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (label communicator)
Process ID of given process index.
static constexpr int firstSlave () noexcept
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
static void allToAll (const labelUList &sendData, labelUList &recvData, const label communicator=0)
Exchange label with all processors (in the communicator).
static void allToAll (const char *sendData, const UList< int > &sendSizes, const UList< int > &sendOffsets, char *recvData, const UList< int > &recvSizes, const UList< int > &recvOffsets, const label communicator=0)
Exchange data with all processors (in the communicator)
static void gather (const char *sendData, int sendSize, char *recvData, const UList< int > &recvSizes, const UList< int > &recvOffsets, const label communicator=0)
Receive data from all processors on the master.
static void scatter (const char *sendData, const UList< int > &sendSizes, const UList< int > &sendOffsets, char *recvData, int recvSize, const label communicator=0)
Send data to all processors from the root of the communicator.
Protected Attributes
DynamicList< char > buf_
Transfer buffer.
Protected Attributes inherited from UPstream
commsTypes commsType_
Communications type of this stream.
Additional Inherited Members
Public Types inherited from UPstream
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Static Public Attributes inherited from UPstream
static const Enum< commsTypes > commsTypeNames
Names of the communication types.
static bool floatTransfer
Should compact transfer be used in which floats replace doubles reducing the bandwidth requirement at the expense of some loss in accuracy.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear to tree.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static int maxCommsSize
Optional maximum message size (bytes)
static const int mpiBufferSize
MPI buffer-size (bytes)
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Detailed Description
Inter-processor communications stream.
Source files
Pstream.H
Pstream.C
gatherScatter.C
combineGatherScatter.C
gatherScatterList.C
exchange.C
Definition at line 52 of file Pstream.H.
Constructor & Destructor Documentation
Pstream (const commsTypes commsType, const label bufSize = 0) inline
Construct given optional buffer size.
Definition at line 116 of file Pstream.H.
References Pstream::buf_, and DynamicList< T, SizeMin >::setCapacity().
Member Function Documentation
ClassName ("Pstream")
void gather (const List< commsStruct > & comms, T & Value, const BinaryOp & bop, const int tag, const label comm) static
Gather data. Apply bop to combine Value.
from different processors
Definition at line 44 of file gatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), forAll, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), UIPstream::read(), UPstream::scheduled, Foam::T(), value(), and UOPstream::write().
Referenced by Foam::reduce().
void gather (T & Value, const BinaryOp & bop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 124 of file gatherScatter.C.
void scatter (const List< commsStruct > & comms, T & Value, const int tag, const label comm) static
Scatter data. Distribute without modification. Reverse of gather.
Definition at line 144 of file gatherScatter.C.
Referenced by meshRefinement::findRegions(), regIOobject::readHeaderOk(), Foam::reduce(), IOobject::typeHeaderOk(), and fileMonitor::updateStates().
void scatter (T & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 220 of file gatherScatter.C.
void combineGather (const List< commsStruct > & comms, T & Value, const CombineOp & cop, const int tag, const label comm) static
Definition at line 42 of file combineGatherScatter.C.
References UPstream::commsStruct::above(), UPstream::commsStruct::below(), Foam::expressions::patchExpr::debug, Foam::endl(), forAll, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), Foam::Pout, UIPstream::read(), UPstream::scheduled, Foam::T(), value(), and UOPstream::write().
Referenced by Foam::combineReduce(), and vtkCloud::writeFields().
void combineGather (T & Value, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 143 of file combineGatherScatter.C.
void combineScatter (const List< commsStruct > & comms, T & Value, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 177 of file combineGatherScatter.C.
Referenced by vtkCloud::writeFields().
void combineScatter (T & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 265 of file combineGatherScatter.C.
void listCombineGather (const List< commsStruct > & comms, List< T > & Value, const CombineOp & cop, const int tag, const label comm) static
Definition at line 284 of file combineGatherScatter.C.
Referenced by inverseDistance::findHoles(), lumpedPointMovement::forcesAndMoments(), patchProbes::sample(), cellVolumeWeight::update(), and fileMonitor::updateStates().
void listCombineGather (List< T > & Value, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 392 of file combineGatherScatter.C.
void listCombineScatter (const List< commsStruct > & comms, List< T > & Value, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 426 of file combineGatherScatter.C.
Referenced by inverseDistance::findHoles(), lumpedPointMovement::forcesAndMoments(), patchProbes::sample(), cellVolumeWeight::update(), and fileMonitor::updateStates().
void listCombineScatter (List< T > & Value, const int tag = Pstream::msgType(), const label comm = Pstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 514 of file combineGatherScatter.C.
void mapCombineGather (const List< commsStruct > & comms, Container & Values, const CombineOp & cop, const int tag, const label comm) static
Definition at line 545 of file combineGatherScatter.C.
Referenced by regionSplit2D::regionSplit2D(), regionSizeDistribution::regionSum(), and meshRefinement::zonify().
void mapCombineGather (Container & Values, const CombineOp & cop, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 626 of file combineGatherScatter.C.
void mapCombineScatter (const List< commsStruct > & comms, Container & Values, const int tag, const label comm) static
Scatter data. Reverse of combineGather.
Definition at line 660 of file combineGatherScatter.C.
Referenced by regionSplit2D::regionSplit2D(), regionSizeDistribution::regionSum(), and meshRefinement::zonify().
void mapCombineScatter (Container & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 718 of file combineGatherScatter.C.
void gatherList (const List< commsStruct > & comms, List< T > & Values, const int tag, const label comm) static
Gather data but keep individual values separate.
Definition at line 46 of file gatherScatterList.C.
References Foam::abort(), UPstream::commsStruct::above(), UPstream::commsStruct::allBelow(), UList< T >::begin(), UPstream::commsStruct::below(), UList< T >::byteSize(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, UPstream::myProcNo(), UPstream::nProcs(), UPstream::parRun(), Foam::Pout, UIPstream::read(), UPstream::scheduled, UList< T >::size(), and UOPstream::write().
Referenced by fieldValue::combineFields(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), meshRefinement::findRegions(), PatchTools::gatherAndMerge(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), and distributedTriSurfaceMesh::localQueries().
void gatherList (List< T > & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 194 of file gatherScatterList.C.
void scatterList (const List< commsStruct > & comms, List< T > & Values, const int tag, const label comm) static
Scatter data. Reverse of gatherList.
Definition at line 209 of file gatherScatterList.C.
Referenced by fieldValue::combineFields(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), and distributedTriSurfaceMesh::localQueries().
void scatterList (List< T > & Values, const int tag = Pstream::msgType(), const label comm = UPstream::worldComm) static
Like above but switches between linear/tree communication.
Definition at line 336 of file gatherScatterList.C.
void exchange (const UList< Container > & sendData, const labelUList & recvSizes, List< Container > & recvData, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool block = true) static
Helper: exchange contiguous data. Sends sendData, receives into.
recvData. If block=true will wait for all transfers to finish.
Definition at line 181 of file exchange.C.
void exchangeSizes (const Container & sendData, labelList & sizes, const label comm = UPstream::worldComm) static
Helper: exchange sizes of sendData. sendData is the data per.
processor (in the communicator). Returns sizes of sendData on the sending processor.
Definition at line 343 of file exchange.C.
Referenced by distributedTriSurfaceMesh::distribute().
void exchange (const UList< Container > & sendData, List< Container > & recvData, const int tag = UPstream::msgType(), const label comm = UPstream::worldComm, const bool block = true) static
Exchange contiguous data. Sends sendData, receives into.
recvData. Determines sizes to receive. If block=true will wait for all transfers to finish.
Definition at line 370 of file exchange.C.
Member Data Documentation
DynamicList<char> buf_ protected
Transfer buffer.
Definition at line 101 of file Pstream.H.
Referenced by Pstream::Pstream().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/Pstream.H
src/OpenFOAM/db/IOstreams/Pstreams/combineGatherScatter.C
src/OpenFOAM/db/IOstreams/Pstreams/exchange.C
src/OpenFOAM/db/IOstreams/Pstreams/gatherScatter.C
src/OpenFOAM/db/IOstreams/Pstreams/gatherScatterList.C