OpenFOAM: geometryCloud Class Reference
geometryCloud Class Reference
Visualisation of cloud data from function object output (file-based only).
Public Member Functions
TypeNameNoDebug ("geometryCloud")
Run-time type information.
geometryCloud (const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~geometryCloud ()
Destructor.
bool addGeometry (const scalar position, vtkRenderer *renderer)
Add cloud to scene (from simulation)
virtual void addGeometryToScene (const scalar position, vtkRenderer *renderer)
Add cloud to scene.
virtual void updateActors (const scalar position)
Update actors.
virtual bool clear ()
No-op.
Public Member Functions inherited from pointData
TypeNameNoDebug ("pointData")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, pointData, dictionary,(const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours),(parent, dict, colours))
pointData (const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~pointData ()
Destructor.
Public Member Functions inherited from geometryBase
geometryBase (const runTimePostProcessing &parent_, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~geometryBase ()
Destructor.
const runTimePostProcessing & parent () const
Return the reference to the parent function object.
bool needsCollective () const
May need to gather geometry parts to render on single-processor.
const word & name () const
Return the name.
bool visible () const
Return the visible flag.
bool parallel () const
Allow parallel rendering.
scalar opacity (const scalar position) const
Return the opacity.
const HashPtrTable< Function1
< vector > > & colours () const
Return reference to the colours.
Public Member Functions inherited from fieldVisualisationBase
fieldVisualisationBase (const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~fieldVisualisationBase ()
Destructor.
const HashPtrTable< Function1
< vector > > & colours () const
Return the colours.
const word & fieldName () const
Return the field name.
Protected Member Functions
vtkSmartPointer
< vtkMultiPieceDataSet > gatherCloud (const objectRegistry &obrTmp) const
Gather and convert cloud positions with vtkPolyData for the leaves.
template<class Type >
bool addField (vtkDataSet *piece, const Field< Type > &fld, const word &fieldName) const
Add field.
template<class Type >
bool addCloudField (vtkMultiPieceDataSet *multiPiece, const IOField< Type > *fldptr, const word &fieldName) const
Add field.
template<class Type >
bool addCloudField (vtkMultiPieceDataSet *multiPiece, const regIOobject *fieldPtr, const word &fieldName) const
Add field.
bool addCloudField (vtkMultiPieceDataSet *multiPiece, const objectRegistry &obrTmp, const word &fieldName) const
Add field.
geometryCloud (const geometryCloud &)=delete
No copy construct.
void operator= (const geometryCloud &)=delete
No copy assignment.
Protected Member Functions inherited from pointData
void addPoints (const label framei, vtkActor *actor, vtkPolyDataMapper *mapper, vtkPolyData *data) const
Add the point data to the renderer.
pointData (const pointData &)=delete
No copy construct.
void operator= (const pointData &)=delete
No copy assignment.
Protected Member Functions inherited from geometryBase
void initialiseActor (vtkActor *actor) const
Initialise actor.
geometryBase (const geometryBase &)=delete
No copy construct.
void operator= (const geometryBase &)=delete
No copy assignment.
Protected Member Functions inherited from fieldVisualisationBase
void setColourMap (vtkLookupTable *lut) const
Set the colour map.
void addScalarBar (const scalar position, vtkRenderer *renderer, vtkLookupTable *lut) const
Add scalar bar (if visible) to renderer.
void setField (const scalar position, const word &colourFieldName, const FieldAssociation fieldAssociation, vtkMapper *mapper, vtkRenderer *renderer) const
Set field/configure mapper, add scalar bar.
void addGlyphs (const scalar position, const word &scaleFieldName, const fieldSummary &scaleFieldInfo, const word &colourFieldName, const fieldSummary &colourFieldInfo, const scalar maxGlyphLength, vtkPolyData *data, vtkActor *actor, vtkRenderer *renderer) const
Add glyphs.
fieldVisualisationBase (const fieldVisualisationBase &)=delete
No copy construct.
void operator= (const fieldVisualisationBase &)=delete
No copy assignment.
Protected Attributes
word cloudName_
Name of geometryCloud.
word colourFieldName_
Name of field to colour by.
vtkSmartPointer< vtkActor > actor_
Actor.
Protected Attributes inherited from pointData
representationType representation_
Representation type.
scalar maxGlyphLength_
Max glyph length.
autoPtr< Function1< vector > > pointColour_
Point colour.
Protected Attributes inherited from geometryBase
const runTimePostProcessing & parent_
Reference to the parent function object.
word name_
The surface name.
bool visible_
Visible flag.
bool parallel_
Allow parallel rendering.
renderModeType renderMode_
Render mode.
autoPtr< Function1< scalar > > opacity_
Opacity.
const HashPtrTable< Function1
< vector > > & colours_
Reference to the colours.
Protected Attributes inherited from fieldVisualisationBase
const HashPtrTable< Function1
< vector > > & colours_
Colours.
word fieldName_
Field name.
bool smooth_
Requested smoother fields (eg, interpolate cell -> point values)
colourByType colourBy_
Colour by type.
colourMapType colourMap_
Colour map type.
Tuple2< scalar, scalar > range_
Range of values.
scalarBar scalarBar_
Scalar bar characteristics.
Additional Inherited Members
Public Types inherited from pointData
enum representationType { rtSphere, rtVector }
Point representation types.
Public Types inherited from geometryBase
enum renderModeType { rmFlat, rmGouraud, rmPhong }
Surface shading types.
Public Types inherited from fieldVisualisationBase
enum colourByType { cbColour, cbField }
Colouring type.
enum colourMapType {
cmCoolToWarm, cmBlueWhiteRed = cmCoolToWarm, cmColdAndHot, cmFire,
cmRainbow, cmGreyscale, cmXray
}
Colour map enumerations.
enum FieldAssociation { NO_DATA = 0, CELL_DATA = 0x1, POINT_DATA = 0x2, CELL_POINT_DATA = 0x3 }
Enumeration of the data field associations.
Static Public Member Functions inherited from pointData
static autoPtr< pointData > New (const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours, const word &pointDataName)
Return selected pointData.
Static Public Attributes inherited from pointData
static const Enum
< representationType > representationTypeNames
Names for point representation types.
Static Public Attributes inherited from geometryBase
static const Enum< renderModeType > renderModeTypeNames
Names for surface shading types.
static int debug
Debug switch.
Static Public Attributes inherited from fieldVisualisationBase
static const Enum< colourByType > colourByTypeNames
Enumeration names for colourByType.
static const Enum< colourMapType > colourMapTypeNames
Enumeration names for colourMapType.
Static Protected Member Functions inherited from fieldVisualisationBase
static fieldSummary queryFieldSummary (const word &fieldName, vtkDataSet *dataset)
Query DataSet for field name and its field association.
static fieldSummary queryFieldSummary (const word &fieldName, vtkCompositeDataSet *data)
Query composite DataSet for field name and its FieldAssociation.
static FieldAssociation queryFieldAssociation (const word &fieldName, vtkDataSet *dataset)
Query DataSet for field name and its field association.
static FieldAssociation queryFieldAssociation (const word &fieldName, vtkCompositeDataSet *data)
Query composite DataSet for field name and its FieldAssociation.
static void addMagField (const word &fieldName, vtkFieldData *fieldData)
Add "mag(..)" field for filters that only accept scalars.
static void addMagField (const word &fieldName, vtkDataSet *dataset)
Add "mag(..)" field for filters that only accept scalars.
static void addMagField (const word &fieldName, vtkCompositeDataSet *data)
Add "mag(..)" field for filters that only accept scalars.
Detailed Description
Visualisation of cloud data from function object output (file-based only).
Dictionary controls
Property Description Required Default
type The point type: geometryCloud yes
cloud The cloud name no
field The field for glyphs scaling no
colourField The field to display no
Source files
geometryCloud.H
geometryCloud.C
Definition at line 89 of file geometryCloud.H.
Constructor & Destructor Documentation
geometryCloud (const geometryCloud &) protected delete
No copy construct.
geometryCloud (const runTimePostProcessing & parent, const dictionary & dict, const HashPtrTable< Function1< vector >> & colours)
Construct from dictionary.
Definition at line 98 of file geometryCloud.C.
~geometryCloud () virtual
Destructor.
Definition at line 115 of file geometryCloud.C.
Member Function Documentation
vtkSmartPointer< vtkMultiPieceDataSet > gatherCloud (const objectRegistry & obrTmp) const protected
Gather and convert cloud positions with vtkPolyData for the leaves.
If VTK is also running in parallel, each cloud is left as a processor-local piece. Otherwise all processor-local parts are gathered onto the master in their correponding slots.
Definition at line 37 of file geometryCloudGather.C.
References List< T >::clear(), cloud::findIOPosition(), UPstream::firstSlave(), UPstream::lastSlave(), UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), geometryBase::needsCollective(), Foam::New(), UPstream::nProcs(), points, UPstream::scheduled, and Foam::vtk::Tools::Vertices().
bool addField (vtkDataSet * piece, const Field< Type > & fld, const word & fieldName) const protected
Add field.
Definition at line 27 of file geometryCloudTemplates.C.
References fieldVisualisationBase::fieldName(), and fld.
bool addCloudField (vtkMultiPieceDataSet * multiPiece, const IOField< Type > * fldptr, const word & fieldName) const protected
Add field.
Definition at line 46 of file geometryCloudTemplates.C.
bool addCloudField (vtkMultiPieceDataSet * multiPiece, const regIOobject * fieldPtr, const word & fieldName) const protected
Add field.
Definition at line 148 of file geometryCloudTemplates.C.
bool addCloudField (vtkMultiPieceDataSet * multiPiece, const objectRegistry & obrTmp, const word & fieldName) const protected
Add field.
Definition at line 57 of file geometryCloud.C.
void operator= (const geometryCloud &) protected delete
No copy assignment.
TypeNameNoDebug ("geometryCloud")
Run-time type information.
bool addGeometry (const scalar position, vtkRenderer * renderer)
Add cloud to scene (from simulation)
dataset->Print(std::cout);
Definition at line 123 of file geometryCloud.C.
void addGeometryToScene (const scalar position, vtkRenderer * renderer) virtual
Add cloud to scene.
Implements geometryBase.
Definition at line 227 of file geometryCloud.C.
void updateActors (const scalar position) virtual
Update actors.
Implements geometryBase.
Definition at line 238 of file geometryCloud.C.
bool clear () virtual
No-op.
Implements geometryBase.
Definition at line 255 of file geometryCloud.C.
Member Data Documentation
word cloudName_ protected
Name of geometryCloud.
Definition at line 101 of file geometryCloud.H.
word colourFieldName_ protected
Name of field to colour by.
Definition at line 106 of file geometryCloud.H.
vtkSmartPointer<vtkActor> actor_ protected
Actor.
Definition at line 111 of file geometryCloud.H.
The documentation for this class was generated from the following files:
src/functionObjects/graphics/runTimePostProcessing/geometryCloud.H
src/functionObjects/graphics/runTimePostProcessing/geometryCloud.C
src/functionObjects/graphics/runTimePostProcessing/geometryCloudGather.C
src/functionObjects/graphics/runTimePostProcessing/geometryCloudTemplates.C