OpenFOAM: lduMesh Class Reference
lduMesh Class Reference abstract
Abstract base class for meshes which provide LDU addressing for the construction of lduMatrix and LDU-solvers.
Public Member Functions
TypeName ("lduMesh")
Runtime type information.
virtual ~lduMesh ()=default
Destructor.
virtual bool hasDb () const =0
Return true if thisDb() is a valid DB.
virtual const objectRegistry & thisDb () const
Return the object registry.
virtual const lduAddressing & lduAddr () const =0
Return ldu addressing.
virtual lduInterfacePtrsList interfaces () const =0
Return a list of pointers for each patch.
virtual label comm () const =0
Return communicator used for parallel communication.
template<class T , class BinaryOp >
void reduce (T &Value, const BinaryOp &bop) const
Helper: reduce with current communicator.
InfoProxy< lduMesh > info () const
Return info proxy.
Friends
Ostream & operator<< (Ostream &, const InfoProxy< lduMesh > &)
Detailed Description
Abstract base class for meshes which provide LDU addressing for the construction of lduMatrix and LDU-solvers.
Definition at line 56 of file lduMesh.H.
Constructor & Destructor Documentation
virtual ~lduMesh () virtual default
Destructor.
Member Function Documentation
TypeName ("lduMesh")
Runtime type information.
virtual bool hasDb () const pure virtual
Return true if thisDb() is a valid DB.
Implemented in faMesh, fvMesh, and lduPrimitiveMesh.
const Foam::objectRegistry & thisDb () const virtual
Return the object registry.
Reimplemented in faMesh, and fvMesh.
Definition at line 35 of file lduMesh.C.
References Foam::defineTypeNameAndDebug().
virtual const lduAddressing& lduAddr () const pure virtual
Return ldu addressing.
Implemented in faMesh, fvMesh, dynamicOversetFvMesh, and lduPrimitiveMesh.
Referenced by GAMGAgglomeration::agglomerateLduAddressing().
virtual lduInterfacePtrsList interfaces () const pure virtual
Return a list of pointers for each patch.
with only those pointing to interfaces being set
Implemented in faMesh, fvMesh, dynamicOversetFvMesh, and lduPrimitiveMesh.
virtual label comm () const pure virtual
Return communicator used for parallel communication.
Implemented in faMesh, fvMesh, and lduPrimitiveMesh.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), and lduMesh::reduce().
void reduce (T & Value, const BinaryOp & bop) const
Helper: reduce with current communicator.
Definition at line 27 of file lduMeshTemplates.C.
References lduMesh::comm(), UPstream::msgType(), and Foam::reduce().
InfoProxy<lduMesh> info () const inline
Return info proxy.
Used to print mesh information to a stream
Definition at line 124 of file lduMesh.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const InfoProxy< lduMesh > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/lduMesh/lduMesh.H
src/OpenFOAM/meshes/lduMesh/lduMesh.C
src/OpenFOAM/meshes/lduMesh/lduMeshTemplates.C