OpenFOAM: CHFSubCoolModel Class Reference
CHFSubCoolModel Class Reference abstract
Public Member Functions
TypeName ("CHFSubCoolModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CHFSubCoolModel, dictionary,(const dictionary &dict),(dict))
Declare runtime construction.
CHFSubCoolModel ()
Construct null.
virtual ~CHFSubCoolModel ()
Destructor.
virtual tmp< scalarField > CHFSubCool (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
Calculate temperature.
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< CHFSubCoolModel > New (const dictionary &dict)
Select null constructed.
Detailed Description
Definition at line 53 of file CHFSubCoolModel.H.
Constructor & Destructor Documentation
CHFSubCoolModel ()
Construct null.
Definition at line 37 of file CHFSubCoolModel.C.
~CHFSubCoolModel () virtual
Destructor.
Definition at line 43 of file CHFSubCoolModel.C.
Member Function Documentation
TypeName ("CHFSubCoolModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , CHFSubCoolModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime construction.
Foam::autoPtr< Foam::wallBoilingModels::CHFSubCoolModel > New (const dictionary & dict) static
Select null constructed.
Definition at line 27 of file newCHFSubCoolModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<scalarField> CHFSubCool (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Calculate temperature.
Implemented in HuaXu.
void write (Ostream & os) const virtual
Reimplemented in HuaXu.
Definition at line 50 of file CHFSubCoolModel.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/CHFSubCoolModel/CHFSubCoolModel.H
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/CHFSubCoolModel/CHFSubCoolModel.C
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/CHFSubCoolModels/CHFSubCoolModel/newCHFSubCoolModel.C