OpenFOAM: fieldSmoother Class Reference
fieldSmoother Class Reference
Utility functions for mesh motion solvers.
Public Member Functions
TypeName ("fieldSmoother")
fieldSmoother (const polyMesh &)
Construct from a polyMesh.
virtual ~fieldSmoother ()
Destructor.
void smoothNormals (const label nIter, const bitSet &isMeshMasterPoint, const bitSet &isMeshMasterEdge, const labelList &fixedPoints, pointVectorField &normals) const
Smooth interior normals.
void smoothPatchNormals (const label nIter, const bitSet &isPatchMasterPoint, const bitSet &isPatchMasterEdge, const indirectPrimitivePatch &adaptPatch, pointField &normals) const
Smooth patch normals.
template<class Type >
void minSmoothField (const label nIter, const bitSet &isPatchMasterPoint, const bitSet &isPatchMasterEdge, const indirectPrimitivePatch &adaptPatch, const scalarField &fieldMin, Field< Type > &field) const
Smooth a scalar field towards, but not beyond, a minimum value.
void smoothLambdaMuDisplacement (const label nIter, const bitSet &isMeshMasterPoint, const bitSet &isMeshMasterEdge, const bitSet &isSmoothable, vectorField &displacement) const
Smooth and then un-smooth a displacement.
Detailed Description
Utility functions for mesh motion solvers.
Source files
fieldSmoother.H
fieldSmoother.C
Definition at line 46 of file fieldSmoother.H.
Constructor & Destructor Documentation
fieldSmoother (const polyMesh & mesh)
Construct from a polyMesh.
Definition at line 33 of file fieldSmoother.C.
References Foam::defineTypeNameAndDebug().
~fieldSmoother () virtual
Destructor.
Definition at line 41 of file fieldSmoother.C.
Member Function Documentation
TypeName ("fieldSmoother")
void smoothNormals (const label nIter, const bitSet & isMeshMasterPoint, const bitSet & isMeshMasterEdge, const labelList & fixedPoints, pointVectorField & normals) const
Smooth interior normals.
Definition at line 48 of file fieldSmoother.C.
void smoothPatchNormals (const label nIter, const bitSet & isPatchMasterPoint, const bitSet & isPatchMasterEdge, const indirectPrimitivePatch & adaptPatch, pointField & normals) const
Smooth patch normals.
Definition at line 135 of file fieldSmoother.C.
void minSmoothField (const label nIter, const bitSet & isPatchMasterPoint, const bitSet & isPatchMasterEdge, const indirectPrimitivePatch & adaptPatch, const scalarField & fieldMin, Field< Type > & field) const
Smooth a scalar field towards, but not beyond, a minimum value.
Definition at line 25 of file fieldSmootherTemplates.C.
References Foam::average(), meshRefinement::calculateEdgeWeights(), PrimitivePatch< Face, FaceList, PointField, PointType >::edges(), Foam::endl(), forAll, meshRefinement::gAverage(), Foam::Info, iter, Foam::mag(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), UList< T >::size(), and meshRefinement::weightedSum().
void smoothLambdaMuDisplacement (const label nIter, const bitSet & isMeshMasterPoint, const bitSet & isMeshMasterEdge, const bitSet & isSmoothable, vectorField & displacement) const
Smooth and then un-smooth a displacement.
Definition at line 200 of file fieldSmoother.C.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/externalDisplacementMeshMover/fieldSmoother/fieldSmoother.H
src/mesh/snappyHexMesh/externalDisplacementMeshMover/fieldSmoother/fieldSmoother.C
src/mesh/snappyHexMesh/externalDisplacementMeshMover/fieldSmoother/fieldSmootherTemplates.C