OpenFOAM: quaternion Class Reference
quaternion Class Reference
Quaternion class used to perform rotations in 3D space.
Public Types
enum eulerOrder : unsigned char {
XZX, XYX, YXY, YZY,
ZYZ, ZXZ, XZY, XYZ,
YXZ, YZX, ZYX, ZXY
}
Euler-angle rotation order.
typedef scalar cmptType
Component type.
typedef scalar magType
Magnitude type.
Public Member Functions
quaternion ()
Construct null.
quaternion (const Foam::zero)
Construct zero initialized.
quaternion (const scalar w, const vector &v)
Construct given scalar and vector parts.
quaternion (const vector &d, const scalar theta)
Construct rotation quaternion given direction d and angle theta.
quaternion (const vector &d, const scalar cosTheta, const bool normalized)
Construct a rotation quaternion given direction d and cosine angle cosTheta and flag if d is normalized.
quaternion (const scalar w)
Construct a real quaternion from the given scalar part, the vector part = zero.
quaternion (const vector &v)
Construct a pure imaginary quaternion given the vector part, the scalar part = 0.
quaternion (const eulerOrder order, const vector &angles)
Construct from three Euler rotation angles.
quaternion (const tensor &rotationTensor)
Construct from a rotation tensor.
quaternion (Istream &is)
Construct from Istream.
scalar w () const
Scalar part of the quaternion (= cos(theta/2) for rotation)
const vector & v () const
Vector part of the quaternion (= axis of rotation)
tensor R () const
The rotation tensor corresponding to the quaternion.
vector eulerAngles (const eulerOrder order) const
Return the Euler rotation angles corresponding to the specified rotation order.
quaternion normalized () const
Return the quaternion normalized by its magnitude.
scalar & w ()
Scalar part of the quaternion (= cos(theta/2) for rotation)
vector & v ()
Vector part of the quaternion (= axis of rotation)
void normalize ()
Normalize the quaternion by its magnitude.
vector transform (const vector &v) const
Rotate the given vector.
vector invTransform (const vector &v) const
Rotate the given vector anti-clockwise.
quaternion transform (const quaternion &q) const
Rotate the given quaternion (and normalize)
quaternion invTransform (const quaternion &q) const
Rotate the given quaternion anti-clockwise (and normalize)
void operator= (const quaternion &q)
void operator+= (const quaternion &q)
void operator-= (const quaternion &q)
void operator*= (const quaternion &q)
void operator/= (const quaternion &q)
void operator= (const scalar s)
Change scalar portion.
void operator= (const vector &v)
Change vector portion.
void operator*= (const scalar s)
void operator/= (const scalar s)
Static Public Member Functions
static quaternion unit (const vector &v)
Return the unit quaternion (versor) from the given vector (w = sqrt(1 - |sqr(v)|))
Static Public Attributes
static const Enum< eulerOrder > eulerOrderNames
The names for Euler-angle rotation order.
static constexpr direction rank = 1
Rank of quaternion is 1.
static constexpr const char *const typeName = "quaternion"
static const quaternion zero
static const quaternion I
Detailed Description
Quaternion class used to perform rotations in 3D space.
Source files
quaternion.H
quaternionI.H
quaternion.C
Definition at line 52 of file quaternion.H.
Member Typedef Documentation
typedef scalar cmptType
Component type.
Definition at line 104 of file quaternion.H.
typedef scalar magType
Magnitude type.
Definition at line 109 of file quaternion.H.
Member Enumeration Documentation
enum eulerOrder : unsigned char
Euler-angle rotation order.
Enumerator
XZX
XYX
YXY
YZY
ZYZ
ZXZ
XZY
XYZ
YXZ
YZX
ZYX
ZXY
Definition at line 114 of file quaternion.H.
Constructor & Destructor Documentation
quaternion () inline
Construct null.
Definition at line 24 of file quaternionI.H.
quaternion (const Foam::zero) inline
Construct zero initialized.
Definition at line 28 of file quaternionI.H.
quaternion (const scalar w, const vector & v) inline
Construct given scalar and vector parts.
Definition at line 35 of file quaternionI.H.
quaternion (const vector & d, const scalar theta) inline
Construct rotation quaternion given direction d and angle theta.
Definition at line 42 of file quaternionI.H.
quaternion (const vector & d, const scalar cosTheta, const bool normalized) inline
Construct a rotation quaternion given direction d and cosine angle cosTheta and flag if d is normalized.
Definition at line 50 of file quaternionI.H.
quaternion (const scalar w) inline explicit
Construct a real quaternion from the given scalar part, the vector part = zero.
Definition at line 70 of file quaternionI.H.
References Foam::mag(), and Foam::sqrt().
quaternion (const vector & v) inline explicit
Construct a pure imaginary quaternion given the vector part, the scalar part = 0.
Definition at line 77 of file quaternionI.H.
quaternion (const eulerOrder order, const vector & angles) inline
Construct from three Euler rotation angles.
Definition at line 91 of file quaternionI.H.
References Foam::magSqr(), and Foam::sqrt().
quaternion (const tensor & rotationTensor) inline explicit
Construct from a rotation tensor.
Definition at line 204 of file quaternionI.H.
quaternion (Istream & is) explicit
Construct from Istream.
Definition at line 54 of file quaternion.C.
Member Function Documentation
Foam::quaternion unit (const vector & v) inline static
Return the unit quaternion (versor) from the given vector (w = sqrt(1 - |sqr(v)|))
Definition at line 84 of file quaternionI.H.
Foam::scalar w () const inline
Scalar part of the quaternion (= cos(theta/2) for rotation)
Definition at line 282 of file quaternionI.H.
Referenced by Foam::inv(), Foam::mag(), Foam::normalize(), Foam::operator!=(), Foam::operator*(), Foam::operator-(), Foam::operator/(), and quaternion::operator/=().
const Foam::vector & v () const inline
Vector part of the quaternion (= axis of rotation)
Definition at line 288 of file quaternionI.H.
Referenced by Foam::inv(), Foam::mag(), Foam::normalize(), Foam::operator!=(), Foam::operator*(), Foam::operator-(), Foam::operator/(), and quaternion::operator/=().
Foam::tensor R () const inline
The rotation tensor corresponding to the quaternion.
Definition at line 351 of file quaternionI.H.
References Foam::conjugate(), and Foam::normalize().
Referenced by Foam::transform(), and triad::triad().
Foam::vector eulerAngles (const eulerOrder order) const inline
Return the Euler rotation angles corresponding to the specified rotation order.
Definition at line 401 of file quaternionI.H.
References Foam::asin(), and Foam::atan2().
Foam::quaternion normalized () const inline
Return the quaternion normalized by its magnitude.
Definition at line 306 of file quaternionI.H.
Foam::scalar & w () inline
Scalar part of the quaternion (= cos(theta/2) for rotation)
Definition at line 294 of file quaternionI.H.
Foam::vector & v () inline
Vector part of the quaternion (= axis of rotation)
Definition at line 300 of file quaternionI.H.
void normalize () inline
Normalize the quaternion by its magnitude.
Definition at line 312 of file quaternionI.H.
References Foam::mag().
Foam::vector transform (const vector & v) const inline
Rotate the given vector.
Definition at line 324 of file quaternionI.H.
Referenced by septernion::operator*=().
Foam::vector invTransform (const vector & v) const inline
Rotate the given vector anti-clockwise.
Definition at line 330 of file quaternionI.H.
References Foam::conjugate().
Referenced by septernion::operator/=(), and septernion::operator=().
Foam::quaternion transform (const quaternion & q) const inline
Rotate the given quaternion (and normalize)
Definition at line 336 of file quaternionI.H.
References Foam::conjugate().
Foam::quaternion invTransform (const quaternion & q) const inline
Rotate the given quaternion anti-clockwise (and normalize)
Definition at line 343 of file quaternionI.H.
References Foam::normalize().
void operator= (const quaternion & q) inline
Definition at line 581 of file quaternionI.H.
void operator+= (const quaternion & q) inline
Definition at line 587 of file quaternionI.H.
void operator-= (const quaternion & q) inline
Definition at line 593 of file quaternionI.H.
void operator*= (const quaternion & q) inline
Definition at line 599 of file quaternionI.H.
void operator/= (const quaternion & q) inline
Definition at line 606 of file quaternionI.H.
References quaternion::v(), quaternion::w(), and w0.
void operator= (const scalar s) inline
Change scalar portion.
Definition at line 612 of file quaternionI.H.
References Foam::inv().
void operator= (const vector & v) inline
Change vector portion.
Definition at line 618 of file quaternionI.H.
References s.
void operator*= (const scalar s) inline
Definition at line 624 of file quaternionI.H.
void operator/= (const scalar s) inline
Definition at line 630 of file quaternionI.H.
References s.
Member Data Documentation
const Foam::Enum< Foam::quaternion::eulerOrder > eulerOrderNames static
The names for Euler-angle rotation order.
Definition at line 126 of file quaternion.H.
constexpr direction rank = 1 static
Rank of quaternion is 1.
Definition at line 134 of file quaternion.H.
constexpr const char* const typeName = "quaternion" static
Definition at line 139 of file quaternion.H.
const Foam::quaternion zero static
Definition at line 141 of file quaternion.H.
const Foam::quaternion I static
Definition at line 142 of file quaternion.H.
Referenced by septernion::operator+=().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/quaternion/quaternion.H
src/OpenFOAM/primitives/quaternion/quaternion.C
src/OpenFOAM/primitives/quaternion/quaternionI.H