OpenFOAM: frictionalStressModel Class Reference
frictionalStressModel Class Reference abstract
Public Member Functions
TypeName ("frictionalStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
Construct from components.
virtual ~frictionalStressModel ()
Destructor.
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const =0
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const =0
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const =0
virtual bool read ()=0
TypeName ("frictionalStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
Construct from components.
virtual ~frictionalStressModel ()
Destructor.
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const =0
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const =0
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const =0
virtual bool read ()=0
Static Public Member Functions
static autoPtr
< frictionalStressModel > New (const dictionary &dict)
static autoPtr
< frictionalStressModel > New (const dictionary &dict)
Protected Attributes
const dictionary & dict_
Reference to higher-level dictionary for re-read.
Detailed Description
Source files
frictionalStressModel.H
frictionalStressModel.C
Source files
frictionalStressModel.H
frictionalStressModel.C
Definition at line 48 of file frictionalStressModel.H.
Constructor & Destructor Documentation
frictionalStressModel (const dictionary & dict)
Construct from components.
Definition at line 39 of file frictionalStressModel.C.
~frictionalStressModel () virtual
Destructor.
Definition at line 49 of file frictionalStressModel.C.
frictionalStressModel (const dictionary & dict)
Construct from components.
virtual ~frictionalStressModel () virtual
Destructor.
Member Function Documentation
TypeName ("frictionalStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , frictionalStressModel , dictionary , (const dictionary &dict) , (dict))
Foam::autoPtr< Foam::kineticTheoryModels::frictionalStressModel > New (const dictionary & dict) static
Definition at line 28 of file newFrictionalStressModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volScalarField> frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
virtual tmp<volScalarField> frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
virtual tmp<volScalarField> nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
virtual bool read () pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
TypeName ("frictionalStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , frictionalStressModel , dictionary , (const dictionary &dict) , (dict))
static autoPtr<frictionalStressModel> New (const dictionary & dict) static
virtual tmp<volScalarField> frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
virtual tmp<volScalarField> frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
virtual tmp<volScalarField> nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
virtual bool read () pure virtual
Implemented in JohnsonJackson, JohnsonJacksonSchaeffer, JohnsonJackson, JohnsonJacksonSchaeffer, Schaeffer, and Schaeffer.
Member Data Documentation
const dictionary & dict_ protected
Reference to higher-level dictionary for re-read.
Definition at line 70 of file frictionalStressModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/frictionalStressModel/frictionalStressModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/phaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/frictionalStressModel/frictionalStressModel.H
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/frictionalStressModel/frictionalStressModel.C
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/frictionalStressModel/newFrictionalStressModel.C