OpenFOAM: triangleFuncs Class Reference
triangleFuncs Class Reference
Various triangle functions.
Public Types
enum proxType { NONE, POINT, EDGE }
Enumeration defining nearness classification.
Static Public Member Functions
static bool intersectAxesBundle (const point &V0, const point &V10, const point &V20, const label i0, const pointField &origin, const scalar maxLength, point &pInter)
Intersect triangle with parallel edges aligned with axis i0.
static bool intersectBb (const point &p0, const point &p1, const point &p2, const treeBoundBox &cubeBb)
Does triangle intersect bounding box.
static bool intersect (const point &va0, const point &va10, const point &va20, const point &basePoint, const vector &normal, point &pInter0, point &pInter1)
Does triangle intersect plane. Return bool and set intersection segment.
static bool intersect (const point &va0, const point &va10, const point &va20, const point &vb0, const point &vb10, const point &vb20, point &pInter0, point &pInter1)
Do triangles intersect. Return bool and set intersection segment.
Detailed Description
Various triangle functions.
Source files
triangleFuncs.H
triangleFuncs.C
Definition at line 52 of file triangleFuncs.H.
Member Enumeration Documentation
enum proxType
Enumeration defining nearness classification.
Enumerator
NONE
POINT
EDGE
Definition at line 62 of file triangleFuncs.H.
Member Function Documentation
bool intersectAxesBundle (const point & V0, const point & V10, const point & V20, const label i0, const pointField & origin, const scalar maxLength, point & pInter) static
Intersect triangle with parallel edges aligned with axis i0.
Returns true (and intersection in pInter) if any of them intersects triangle. Used in intersectBb.
Definition at line 82 of file triangleFuncs.C.
References Foam::constant::atomic::alpha, beta(), Foam::det(), forAll, Foam::mag(), s, and u0.
bool intersectBb (const point & p0, const point & p1, const point & p2, const treeBoundBox & cubeBb) static
Does triangle intersect bounding box.
Definition at line 169 of file triangleFuncs.C.
bool intersect (const point & va0, const point & va10, const point & va20, const point & basePoint, const vector & normal, point & pInter0, point & pInter1) static
Does triangle intersect plane. Return bool and set intersection segment.
Definition at line 226 of file triangleFuncs.C.
bool intersect (const point & va0, const point & va10, const point & va20, const point & vb0, const point & vb10, const point & vb20, point & pInter0, point & pInter1) static
Do triangles intersect. Return bool and set intersection segment.
Definition at line 344 of file triangleFuncs.C.
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triangleFuncs/triangleFuncs.H
src/meshTools/triSurface/triangleFuncs/triangleFuncs.C