OpenFOAM: reactionRateFlameArea Class Reference
reactionRateFlameArea Class Reference abstract
Abstract class for reaction rate per flame area unit.
Public Member Functions
TypeName ("reactionRateFlameArea")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, reactionRateFlameArea, dictionary,(const word modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel),(modelType, dict, mesh, combModel))
reactionRateFlameArea (const word &modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Construct from components.
virtual ~reactionRateFlameArea ()
const volScalarField & omega () const
Access functions.
virtual void correct (const volScalarField &sigma)=0
Correct omega.
virtual bool read (const dictionary &dictProperties)
Update from dictionary.
Static Public Member Functions
static autoPtr
< reactionRateFlameArea > New (const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel)
Protected Attributes
dictionary coeffDict_
Dictionary.
const fvMesh & mesh_
Mesh reference.
const combustionModel & combModel_
Combustion model owner.
word fuel_
Fuel name.
volScalarField omega_
Fuel consumption rate per unit of flame area.
Detailed Description
Abstract class for reaction rate per flame area unit.
Source files
reactionRateFlameArea.H
reactionRateFlameArea.C
reactionRateFlameAreaNew.C
Definition at line 52 of file reactionRateFlameArea.H.
Constructor & Destructor Documentation
reactionRateFlameArea (const word & modelType, const dictionary & dict, const fvMesh & mesh, const combustionModel & combModel)
Construct from components.
Definition at line 35 of file reactionRateFlameArea.C.
~reactionRateFlameArea () virtual
Definition at line 63 of file reactionRateFlameArea.C.
Member Function Documentation
TypeName ("reactionRateFlameArea")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , reactionRateFlameArea , dictionary , (const word modelType, const dictionary &dict, const fvMesh &mesh, const combustionModel &combModel) , (modelType, dict, mesh, combModel))
Foam::autoPtr< Foam::reactionRateFlameArea > New (const dictionary & dict, const fvMesh & mesh, const combustionModel & combModel) static
Definition at line 27 of file reactionRateFlameAreaNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, Foam::Info, dictionary::lookup(), and mesh.
Referenced by FSD< ReactionThermo, ThermoType >::FSD().
const volScalarField& omega () const inline
Access functions.
Return omega
Definition at line 163 of file reactionRateFlameArea.H.
virtual void correct (const volScalarField & sigma) pure virtual
Correct omega.
Implemented in relaxation.
bool read (const dictionary & dictProperties) virtual
Update from dictionary.
Reimplemented in relaxation.
Definition at line 69 of file reactionRateFlameArea.C.
Member Data Documentation
dictionary coeffDict_ protected
Dictionary.
Definition at line 62 of file reactionRateFlameArea.H.
const fvMesh& mesh_ protected
Mesh reference.
Definition at line 67 of file reactionRateFlameArea.H.
const combustionModel& combModel_ protected
Combustion model owner.
Definition at line 72 of file reactionRateFlameArea.H.
word fuel_ protected
Fuel name.
Definition at line 77 of file reactionRateFlameArea.H.
volScalarField omega_ protected
Fuel consumption rate per unit of flame area.
Definition at line 82 of file reactionRateFlameArea.H.
The documentation for this class was generated from the following files:
src/combustionModels/FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameArea.H
src/combustionModels/FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameArea.C
src/combustionModels/FSD/reactionRateFlameAreaModels/reactionRateFlameArea/reactionRateFlameAreaNew.C