OpenFOAM: fvFieldReconstructor Class Reference
fvFieldReconstructor Class Reference
Finite volume reconstructor for volume and surface fields.
Classes
class fvPatchFieldReconstructor
Mapper for sizing only - does not do any actual mapping.
Public Member Functions
fvFieldReconstructor (fvMesh &mesh, const PtrList< fvMesh > &procMeshes, const PtrList< labelIOList > &faceProcAddressing, const PtrList< labelIOList > &cellProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
Construct from components.
label nReconstructed () const
Return number of fields reconstructed.
template<class Type >
tmp< DimensionedField< Type,
volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> &procFields) const
Reconstruct volume internal field.
template<class Type >
tmp< DimensionedField< Type,
volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject) const
Read and reconstruct volume internal field.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> &) const
Reconstruct volume field.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject) const
Read and reconstruct volume field.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Reconstruct surface field.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject) const
Read and reconstruct surface field.
template<class Type >
label reconstructFvVolumeInternalFields (const IOobjectList &objects, const UList< word > &fieldNames)
Read, reconstruct and write specified volume internal fields.
template<class Type >
label reconstructFvVolumeFields (const IOobjectList &objects, const UList< word > &fieldNames)
Read, reconstruct and write specified volume fields.
template<class Type >
label reconstructFvSurfaceFields (const IOobjectList &objects, const UList< word > &fieldNames)
Read, reconstruct and write specified surface fields.
template<class Type >
label reconstructFvVolumeInternalFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
Read, reconstruct and write all/selected volume internal fields.
template<class Type >
label reconstructFvVolumeFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
Read, reconstruct and write all/selected volume fields.
template<class Type >
label reconstructFvSurfaceFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
Read, reconstruct and write all/selected surface fields.
template<class Type >
label reconstructFvVolumeInternalFields (const IOobjectList &objects, const wordHashSet &selectedFields)
Read, reconstruct and write all/selected volume internal fields.
template<class Type >
label reconstructFvVolumeFields (const IOobjectList &objects, const wordHashSet &selectedFields)
Read, reconstruct and write all/selected volume fields.
template<class Type >
label reconstructFvSurfaceFields (const IOobjectList &objects, const wordHashSet &selectedFields)
Read, reconstruct and write all/selected surface fields.
template<class Type >
Foam::tmp
< Foam::DimensionedField< Type,
Foam::volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> &procFields) const
template<class Type >
Foam::tmp
< Foam::DimensionedField< Type,
Foam::volMesh > > reconstructFvVolumeInternalField (const IOobject &fieldIoObject) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> &procFields) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > reconstructFvVolumeField (const IOobject &fieldIoObject) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &procFields) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > reconstructFvSurfaceField (const IOobject &fieldIoObject) const
template<class Type >
Foam::label reconstructFvVolumeInternalFields (const IOobjectList &objects, const UList< word > &fieldNames)
template<class Type >
Foam::label reconstructFvVolumeFields (const IOobjectList &objects, const UList< word > &fieldNames)
template<class Type >
Foam::label reconstructFvSurfaceFields (const IOobjectList &objects, const UList< word > &fieldNames)
template<class Type >
Foam::label reconstructFvVolumeInternalFields (const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructFvVolumeFields (const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructFvSurfaceFields (const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructFvVolumeInternalFields (const IOobjectList &objects, const wordHashSet &selectedFields)
template<class Type >
Foam::label reconstructFvVolumeFields (const IOobjectList &objects, const wordHashSet &selectedFields)
template<class Type >
Foam::label reconstructFvSurfaceFields (const IOobjectList &objects, const wordHashSet &selectedFields)
Detailed Description
Finite volume reconstructor for volume and surface fields.
Source files
fvFieldReconstructor.H
fvFieldReconstructor.C
fvFieldReconstructorFields.C
Definition at line 52 of file fvFieldReconstructor.H.
Constructor & Destructor Documentation
fvFieldReconstructor (fvMesh & mesh, const PtrList< fvMesh > & procMeshes, const PtrList< labelIOList > & faceProcAddressing, const PtrList< labelIOList > & cellProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Construct from components.
Definition at line 26 of file fvFieldReconstructor.C.
References fvMesh::boundary(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, primitiveMesh::nCells(), primitiveMesh::nFaces(), and UPtrList< T >::size().
Member Function Documentation
label nReconstructed () const inline
Return number of fields reconstructed.
Definition at line 168 of file fvFieldReconstructor.H.
tmp<DimensionedField<Type, volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> & procFields) const
Reconstruct volume internal field.
tmp<DimensionedField<Type, volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject) const
Read and reconstruct volume internal field.
tmp<GeometricField<Type, fvPatchField, volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> &) const
Reconstruct volume field.
tmp<GeometricField<Type, fvPatchField, volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject) const
Read and reconstruct volume field.
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> &) const
Reconstruct surface field.
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject) const
Read and reconstruct surface field.
label reconstructFvVolumeInternalFields (const IOobjectList & objects, const UList< word > & fieldNames)
Read, reconstruct and write specified volume internal fields.
label reconstructFvVolumeFields (const IOobjectList & objects, const UList< word > & fieldNames)
Read, reconstruct and write specified volume fields.
label reconstructFvSurfaceFields (const IOobjectList & objects, const UList< word > & fieldNames)
Read, reconstruct and write specified surface fields.
label reconstructFvVolumeInternalFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Read, reconstruct and write all/selected volume internal fields.
An empty wordRes corresponds to select ALL.
label reconstructFvVolumeFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Read, reconstruct and write all/selected volume fields.
An empty wordRes corresponds to select ALL.
label reconstructFvSurfaceFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Read, reconstruct and write all/selected surface fields.
An empty wordRes corresponds to select ALL.
label reconstructFvVolumeInternalFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Read, reconstruct and write all/selected volume internal fields.
An empty wordHashSet corresponds to select ALL.
Note
this may be removed in the future (2018-11)
label reconstructFvVolumeFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Read, reconstruct and write all/selected volume fields.
An empty wordHashSet corresponds to select ALL.
Note
this may be removed in the future (2018-11)
label reconstructFvSurfaceFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Read, reconstruct and write all/selected surface fields.
An empty wordHashSet corresponds to select ALL.
Note
this may be removed in the future (2018-11)
Foam::tmp<Foam::DimensionedField<Type, Foam::volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject, const PtrList< DimensionedField< Type, volMesh >> & procFields) const
Definition at line 35 of file fvFieldReconstructorFields.C.
References DimensionedField< Type, GeoMesh >::field(), forAll, primitiveMesh::nCells(), Foam::New(), and Field< Type >::rmap().
Foam::tmp<Foam::DimensionedField<Type, Foam::volMesh> > reconstructFvVolumeInternalField (const IOobject & fieldIoObject) const
Definition at line 72 of file fvFieldReconstructorFields.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvPatchField, volMesh >> & procFields) const
Definition at line 120 of file fvFieldReconstructorFields.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > reconstructFvVolumeField (const IOobject & fieldIoObject) const
Definition at line 299 of file fvFieldReconstructorFields.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject, const PtrList< GeometricField< Type, fvsPatchField, surfaceMesh >> & procFields) const
Definition at line 347 of file fvFieldReconstructorFields.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > reconstructFvSurfaceField (const IOobject & fieldIoObject) const
Definition at line 541 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvVolumeInternalFields (const IOobjectList & objects, const UList< word > & fieldNames)
Definition at line 588 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvVolumeFields (const IOobjectList & objects, const UList< word > & fieldNames)
Definition at line 620 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvSurfaceFields (const IOobjectList & objects, const UList< word > & fieldNames)
Definition at line 652 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvVolumeInternalFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 684 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvVolumeFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 704 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvSurfaceFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 724 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvVolumeInternalFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Definition at line 744 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvVolumeFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Definition at line 764 of file fvFieldReconstructorFields.C.
Foam::label reconstructFvSurfaceFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Definition at line 784 of file fvFieldReconstructorFields.C.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.H
src/parallel/reconstruct/reconstruct/fvFieldReconstructor.C
src/parallel/reconstruct/reconstruct/fvFieldReconstructorFields.C