OpenFOAM: meshReader Class Reference
meshReader Class Reference abstract
This class supports creating polyMeshes with baffles.
Classes
class cellFaceIdentifier
Identify cell faces in terms of cell Id and face Id.
Public Member Functions
meshReader (const fileName &, const scalar scaling=1.0)
Construct from fileName.
virtual ~meshReader ()
Destructor.
virtual autoPtr< polyMesh > mesh (const objectRegistry &)
Create and return polyMesh.
void writeAux (const objectRegistry &) const
Write auxiliary information.
void writeMesh (const polyMesh &, IOstream::streamFormat fmt=IOstream::BINARY) const
Write mesh.
Static Public Member Functions
static void warnDuplicates (const word &context, const wordList &)
Warn about repeated names.
Protected Member Functions
virtual bool readGeometry (const scalar scaleFactor=1.0)=0
Subclasses are required to supply this information.
Protected Attributes
fileName geometryFile_
Referenced filename.
scalar scaleFactor_
Geometry scaling.
pointField points_
Points supporting the mesh.
labelList origCellId_
Lookup original Cell number for a given cell.
List< List< cellFaceIdentifier > > boundaryIds_
Identify boundary faces by cells and their faces.
wordList patchTypes_
Boundary patch types.
wordList patchNames_
Boundary patch names.
wordList patchPhysicalTypes_
Boundary patch physical types.
labelList patchStarts_
Polyhedral mesh boundary patch start indices and dimensions.
labelList patchSizes_
label nInternalFaces_
Number of internal faces for polyMesh.
faceList meshFaces_
Global face list for polyMesh.
faceListList cellFaces_
List of faces for every cell.
faceList baffleFaces_
List of each baffle face.
labelList cellTableId_
Cell table id for each cell.
cellTable cellTable_
Cell table persistent data saved as a dictionary.
Detailed Description
This class supports creating polyMeshes with baffles.
The derived classes are responsible for providing the protected data. This implementation is somewhat messy, but could/should be restructured to provide a more generalized reader (at the moment it has been written for converting PROSTAR data).
The meshReader supports cellTable information (see new user's guide entry).
Note
The boundary definitions are given as cell/face.
Source files
meshReader.H
calcPointCells.C
createPolyBoundary.C
createPolyCells.C
meshReader.C
meshReaderAux.C
Definition at line 64 of file meshReader.H.
Constructor & Destructor Documentation
meshReader (const fileName & fileOrPrefix, const scalar scaling = 1.0)
Construct from fileName.
Definition at line 152 of file meshReader.C.
~meshReader () virtual
Destructor.
Definition at line 190 of file meshReader.C.
Member Function Documentation
virtual bool readGeometry (const scalar scaleFactor = 1.0) protected pure virtual
Subclasses are required to supply this information.
Implemented in STARCDMeshReader, and FIREMeshReader.
void warnDuplicates (const word & context, const wordList & list) static
Warn about repeated names.
Definition at line 30 of file meshReaderAux.C.
References Foam::endl(), forAllConstIters, Foam::Info, HashTable< T, Key, Hash >::insert(), iter, Foam::nl, and UList< T >::size().
Foam::autoPtr< Foam::polyMesh > mesh (const objectRegistry & registry) virtual
Create and return polyMesh.
Reimplemented in FIREMeshReader.
Definition at line 76 of file meshReader.C.
void writeAux (const objectRegistry & registry) const
Write auxiliary information.
Definition at line 144 of file meshReaderAux.C.
void writeMesh (const polyMesh & mesh, IOstream::streamFormat fmt = IOstream::BINARY) const
Write mesh.
Definition at line 119 of file meshReader.C.
Member Data Documentation
fileName geometryFile_ protected
Referenced filename.
Definition at line 261 of file meshReader.H.
scalar scaleFactor_ protected
Geometry scaling.
Definition at line 266 of file meshReader.H.
pointField points_ protected
Points supporting the mesh.
Definition at line 271 of file meshReader.H.
Referenced by FIREMeshReader::readFaces(), and FIREMeshReader::readPoints().
labelList origCellId_ protected
Lookup original Cell number for a given cell.
Definition at line 276 of file meshReader.H.
List<List<cellFaceIdentifier> > boundaryIds_ protected
Identify boundary faces by cells and their faces.
for each patch
Definition at line 283 of file meshReader.H.
wordList patchTypes_ protected
Boundary patch types.
Definition at line 288 of file meshReader.H.
wordList patchNames_ protected
Boundary patch names.
Definition at line 293 of file meshReader.H.
wordList patchPhysicalTypes_ protected
Boundary patch physical types.
Definition at line 298 of file meshReader.H.
labelList patchStarts_ protected
Polyhedral mesh boundary patch start indices and dimensions.
Definition at line 303 of file meshReader.H.
labelList patchSizes_ protected
Definition at line 304 of file meshReader.H.
label nInternalFaces_ protected
Number of internal faces for polyMesh.
Definition at line 309 of file meshReader.H.
faceList meshFaces_ protected
Global face list for polyMesh.
Definition at line 314 of file meshReader.H.
faceListList cellFaces_ protected
List of faces for every cell.
Definition at line 319 of file meshReader.H.
faceList baffleFaces_ protected
List of each baffle face.
Definition at line 324 of file meshReader.H.
labelList cellTableId_ protected
Cell table id for each cell.
Definition at line 329 of file meshReader.H.
cellTable cellTable_ protected
Cell table persistent data saved as a dictionary.
Definition at line 334 of file meshReader.H.
The documentation for this class was generated from the following files:
src/conversion/common/reader/meshReader.H
src/conversion/common/reader/calcPointCells.C
src/conversion/common/reader/createPolyBoundary.C
src/conversion/common/reader/createPolyCells.C
src/conversion/common/reader/meshReader.C
src/conversion/common/reader/meshReaderAux.C