OpenFOAM: surfaceFeatures Class Reference
surfaceFeatures Class Reference
Holds feature edges/points of surface.
Public Types
enum edgeStatus { NONE, REGION, EXTERNAL, INTERNAL }
Edge status.
Public Member Functions
ClassName ("surfaceFeatures")
surfaceFeatures (const triSurface &surf)
Construct from surface.
surfaceFeatures (const triSurface &surf, const labelList &featurePoints, const labelList &featureEdges, const label externalStart, const label internalStart)
Construct from components.
surfaceFeatures (const triSurface &surf, const scalar includedAngle, const scalar minLen=0, const label minElems=0, const bool geometricTestOnly=false)
Construct from surface, angle and min cumulative length and/or.
surfaceFeatures (const triSurface &surf, const dictionary &dict)
Construct from dictionary.
surfaceFeatures (const triSurface &surf, const fileName &fName)
Construct from file.
surfaceFeatures (const triSurface &surf, const pointField &points, const edgeList &edges, const scalar mergeTol=1e-6, const bool geometricTestOnly=false)
Construct from pointField and edgeList (edgeMesh)
surfaceFeatures (const surfaceFeatures &sf)
Construct as copy.
const triSurface & surface () const
const labelList & featurePoints () const
Return feature point list.
const labelList & featureEdges () const
Return feature edge list.
label externalStart () const
Start of external edges.
label internalStart () const
Start of internal edges.
label nRegionEdges () const
Return number of region edges.
label nExternalEdges () const
Return number of external edges.
label nInternalEdges () const
Return number of internal edges.
labelList selectFeatureEdges (const bool regionEdges, const bool externalEdges, const bool internalEdges) const
Helper function: select a subset of featureEdges_.
void findFeatures (const scalar includedAngle, const bool geometricTestOnly)
Find feature edges using provided included angle.
labelList trimFeatures (const scalar minLen, const label minElems, const scalar includedAngle)
Delete small sets of edges. Edges are stringed up and any.
void excludeBox (List< edgeStatus > &edgeStat, const treeBoundBox &bb) const
Mark edge status inside box as 'NONE'.
void subsetBox (List< edgeStatus > &edgeStat, const treeBoundBox &bb) const
Mark edge status outside box as 'NONE'.
void deleteBox (List< edgeStatus > &edgeStat, const treeBoundBox &bb, const bool removeInside) const
Mark edge status as 'NONE' for edges inside/outside box.
void subsetPlane (List< edgeStatus > &edgeStat, const plane &cutPlane) const
If edge does not intersect the plane, mark as 'NONE'.
void excludeOpen (List< edgeStatus > &edgeStat) const
Mark edges with a single connected face as 'NONE'.
void checkFlatRegionEdge (List< edgeStatus > &edgeStat, const scalar tol, const scalar includedAngle) const
Divide into multiple normal bins.
List< edgeStatus > toStatus () const
From member feature edges to status per edge.
void setFromStatus (const List< edgeStatus > &edgeStat, const scalar includedAngle)
Set from status per edge.
Map< label > nearestSamples (const labelList &selectedPoints, const pointField &samples, const scalarField &maxDistSqr) const
Find nearest sample for selected surface points.
Map< label > nearestSamples (const labelList &selectedEdges, const pointField &samples, const scalarField &sampleDist, const scalarField &maxDistSqr, const scalar minSampleDist=0.1) const
Find nearest sample for regularly sampled points along.
Map< pointIndexHit > nearestEdges (const labelList &selectedEdges, const edgeList &sampleEdges, const labelList &selectedSampleEdges, const pointField &samplePoints, const scalarField &sampleDist, const scalarField &maxDistSqr, const scalar minSampleDist=0.1) const
Like nearestSamples but now gets nearest point on.
void nearestSurfEdge (const labelList &selectedEdges, const pointField &samples, scalar searchSpanSqr, labelList &edgeLabel, labelList &edgeEndPoint, pointField &edgePoint) const
Find nearest surface edge (out of selectedEdges) for.
void nearestSurfEdge (const labelList &selectedEdges, const edgeList &sampleEdges, const labelList &selectedSampleEdges, const pointField &samplePoints, const vector &searchSpan, labelList &edgeLabel, pointField &pointOnEdge, pointField &pointOnFeature) const
Find nearest surface edge (out of selectedEdges) for each.
void nearestFeatEdge (const edgeList &edges, const pointField &points, scalar searchSpanSqr, labelList &edgeLabel) const
Find nearest feature edge to each surface edge. Uses the.
void writeDict (Ostream &os) const
Write as dictionary.
void write (const fileName &fName) const
Write as dictionary to file.
void writeObj (const fileName &prefix) const
Write to separate OBJ files (region, external, internal edges,.
void writeStats (Ostream &os) const
Write some information.
void operator= (const surfaceFeatures &rhs)
Detailed Description
Holds feature edges/points of surface.
Feature edges are stored in one list and sorted: 0 .. externalStart_-1 : region edges externalStart_ .. internalStart_-1 : external edges internalStart_ .. size-1 : internal edges
NOTE: angle is included angle, not feature angle and is in degrees. The included angle is the smallest angle between two planes. For coplanar faces it is 180, for straight angles it is 90. To pick up straight edges only use included angle of 91 degrees
Source files
surfaceFeatures.H
surfaceFeatures.C
Definition at line 69 of file surfaceFeatures.H.
Member Enumeration Documentation
enum edgeStatus
Edge status.
Enumerator
NONE
Not a classified feature edge.
REGION
EXTERNAL
"Convex" edge
INTERNAL
"Concave" edge
Definition at line 76 of file surfaceFeatures.H.
Constructor & Destructor Documentation
surfaceFeatures (const triSurface & surf)
Construct from surface.
Definition at line 647 of file surfaceFeatures.C.
surfaceFeatures (const triSurface & surf, const labelList & featurePoints, const labelList & featureEdges, const label externalStart, const label internalStart)
Construct from components.
Definition at line 659 of file surfaceFeatures.C.
surfaceFeatures (const triSurface & surf, const scalar includedAngle, const scalar minLen = 0, const label minElems = 0, const bool geometricTestOnly = false)
Construct from surface, angle and min cumulative length and/or.
number of elements. If geometric test only is true, then region information is ignored and features are only assigned based on the geometric criteria
Definition at line 677 of file surfaceFeatures.C.
References surfaceFeatures::findFeatures(), and surfaceFeatures::trimFeatures().
surfaceFeatures (const triSurface & surf, const dictionary & dict)
Construct from dictionary.
Definition at line 701 of file surfaceFeatures.C.
surfaceFeatures (const triSurface & surf, const fileName & fName)
Construct from file.
Definition at line 715 of file surfaceFeatures.C.
surfaceFeatures (const triSurface & surf, const pointField & points, const edgeList & edges, const scalar mergeTol = 1e-6, const bool geometricTestOnly = false)
Construct from pointField and edgeList (edgeMesh)
Definition at line 738 of file surfaceFeatures.C.
surfaceFeatures (const surfaceFeatures & sf)
Construct as copy.
Definition at line 818 of file surfaceFeatures.C.
Member Function Documentation
ClassName ("surfaceFeatures")
const triSurface& surface () const inline
Definition at line 285 of file surfaceFeatures.H.
References UList< T >::size().
Referenced by surfaceFeatures::operator=().
const labelList& featurePoints () const inline
Return feature point list.
Definition at line 293 of file surfaceFeatures.H.
Referenced by surfaceFeatures::operator=().
const labelList& featureEdges () const inline
Return feature edge list.
Definition at line 301 of file surfaceFeatures.H.
Referenced by surfaceFeatures::operator=().
label externalStart () const inline
Start of external edges.
Definition at line 309 of file surfaceFeatures.H.
Referenced by surfaceFeatures::operator=().
label internalStart () const inline
Start of internal edges.
Definition at line 317 of file surfaceFeatures.H.
Referenced by surfaceFeatures::operator=().
label nRegionEdges () const inline
Return number of region edges.
Definition at line 325 of file surfaceFeatures.H.
label nExternalEdges () const inline
Return number of external edges.
Definition at line 333 of file surfaceFeatures.H.
label nInternalEdges () const inline
Return number of internal edges.
Definition at line 341 of file surfaceFeatures.H.
Foam::labelList selectFeatureEdges (const bool regionEdges, const bool externalEdges, const bool internalEdges) const
Helper function: select a subset of featureEdges_.
Definition at line 831 of file surfaceFeatures.C.
References DynamicList< T, SizeMin >::append(), i, DynamicList< T, SizeMin >::setCapacity(), DynamicList< T, SizeMin >::shrink(), and UList< T >::size().
void findFeatures (const scalar includedAngle, const bool geometricTestOnly)
Find feature edges using provided included angle.
Definition at line 874 of file surfaceFeatures.C.
Referenced by surfaceFeatures::surfaceFeatures().
Foam::labelList trimFeatures (const scalar minLen, const label minElems, const scalar includedAngle)
Delete small sets of edges. Edges are stringed up and any.
string of length < minLen (or nElems < minElems) is deleted.
Definition at line 899 of file surfaceFeatures.C.
References forAll, i, edge::mag(), and UList< T >::size().
Referenced by surfaceFeatures::surfaceFeatures().
void excludeBox (List< edgeStatus > & edgeStat, const treeBoundBox & bb) const
Mark edge status inside box as 'NONE'.
Definition at line 1033 of file surfaceFeatures.C.
void subsetBox (List< edgeStatus > & edgeStat, const treeBoundBox & bb) const
Mark edge status outside box as 'NONE'.
Definition at line 1043 of file surfaceFeatures.C.
void deleteBox (List< edgeStatus > & edgeStat, const treeBoundBox & bb, const bool removeInside) const
Mark edge status as 'NONE' for edges inside/outside box.
Definition at line 1053 of file surfaceFeatures.C.
void subsetPlane (List< edgeStatus > & edgeStat, const plane & cutPlane) const
If edge does not intersect the plane, mark as 'NONE'.
Definition at line 1075 of file surfaceFeatures.C.
void excludeOpen (List< edgeStatus > & edgeStat) const
Mark edges with a single connected face as 'NONE'.
Definition at line 1106 of file surfaceFeatures.C.
void checkFlatRegionEdge (List< edgeStatus > & edgeStat, const scalar tol, const scalar includedAngle) const
Divide into multiple normal bins.
set REGION if != 2 normals
set REGION if 2 normals that make feature angle
otherwise set NONE and set normals,bins
return REGION if != 2 normals
return REGION if 2 normals that make feature angle
otherwise return NONE and set normals,bins
Definition at line 1128 of file surfaceFeatures.C.
References forAll, surfaceFeatures::REGION, and UList< T >::size().
Foam::List< Foam::surfaceFeatures::edgeStatus > toStatus () const
From member feature edges to status per edge.
Definition at line 110 of file surfaceFeatures.C.
void setFromStatus (const List< edgeStatus > & edgeStat, const scalar includedAngle)
Set from status per edge.
Definition at line 139 of file surfaceFeatures.C.
Foam::Map< Foam::label > nearestSamples (const labelList & selectedPoints, const pointField & samples, const scalarField & maxDistSqr) const
Find nearest sample for selected surface points.
(usually the set of featurePoints). Return map from index in samples to surface point. Do not include points that are further than maxDist away (separate maxDist for every sample). Supply maxDistSqr.
Definition at line 1239 of file surfaceFeatures.C.
References Foam::abort(), indexedOctree< Type >::bb(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, forAllConstIters, PointIndexHit< Point >::hit(), i, PointIndexHit< Point >::index(), iter, Foam::magSqr(), Foam::Pout, UList< T >::size(), and Foam::meshTools::writeOBJ().
Foam::Map< Foam::label > nearestSamples (const labelList & selectedEdges, const pointField & samples, const scalarField & sampleDist, const scalarField & maxDistSqr, const scalar minSampleDist = 0.1) const
Find nearest sample for regularly sampled points along.
the selected (surface) edges. Return map from sample to edge. maxDistSqr is distance squared below which gets snapped. Edge gets sampled at points sampleDist[sampleI] apart. (with a maximum of 10 samples per edge)
Definition at line 1320 of file surfaceFeatures.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::exit(), forAll, forAllConstIters, i, iter, edge::line(), Foam::mag(), Foam::magSqr(), Foam::max(), line< Point, PointRef >::nearestDist(), Foam::Pout, s, UList< T >::size(), edge::start(), edge::vec(), and Foam::meshTools::writeOBJ().
Foam::Map< Foam::pointIndexHit > nearestEdges (const labelList & selectedEdges, const edgeList & sampleEdges, const labelList & selectedSampleEdges, const pointField & samplePoints, const scalarField & sampleDist, const scalarField & maxDistSqr, const scalar minSampleDist = 0.1) const
Like nearestSamples but now gets nearest point on.
sample-edge instead of nearest sample-point itself. Return map from sample edge to feature edge.
Definition at line 1456 of file surfaceFeatures.C.
References edge::centre(), Foam::expressions::patchExpr::debug, treeDataEdge::edgeLabels(), Foam::endl(), Foam::exit(), forAll, forAllConstIters, i, iter, Foam::mag(), Foam::magSqr(), Foam::max(), Foam::Pout, s, indexedOctree< Type >::shapes(), UList< T >::size(), edge::start(), edge::vec(), and Foam::meshTools::writeOBJ().
void nearestSurfEdge (const labelList & selectedEdges, const pointField & samples, scalar searchSpanSqr, labelList & edgeLabel, labelList & edgeEndPoint, pointField & edgePoint) const
Find nearest surface edge (out of selectedEdges) for.
each sample point. Sets:
edgeLabel : label of surface edge.
edgePoint : exact position of nearest point on edge.
edgeEndPoint : -1, 0, 1 depending on whether edgePoint is on inside/start/end of edge
Definition at line 1607 of file surfaceFeatures.C.
References edge::end(), forAll, PointIndexHit< Point >::hit(), i, PointIndexHit< Point >::index(), boundBox::inflate(), PointIndexHit< Point >::rawPoint(), List< T >::setSize(), UList< T >::size(), and edge::start().
void nearestSurfEdge (const labelList & selectedEdges, const edgeList & sampleEdges, const labelList & selectedSampleEdges, const pointField & samplePoints, const vector & searchSpan, labelList & edgeLabel, pointField & pointOnEdge, pointField & pointOnFeature) const
Find nearest surface edge (out of selectedEdges) for each.
sample edge. Sets:
edgeLabel : label of surface edge.
pointOnEdge : exact position of nearest point on edge.
pointOnFeature : exact position on sample edge.
Definition at line 1677 of file surfaceFeatures.C.
References line< Point, PointRef >::centre(), forAll, PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), i, PointIndexHit< Point >::index(), edge::line(), List< T >::setSize(), and UList< T >::size().
void nearestFeatEdge (const edgeList & edges, const pointField & points, scalar searchSpanSqr, labelList & edgeLabel) const
Find nearest feature edge to each surface edge. Uses the.
mid-point of the surface edges.
Definition at line 1743 of file surfaceFeatures.C.
References edge::centre(), forAll, PointIndexHit< Point >::hit(), Foam::identity(), PointIndexHit< Point >::index(), Foam::mag(), UList< T >::size(), edge::start(), and edge::vec().
void writeDict (Ostream & os) const
Write as dictionary.
Definition at line 1154 of file surfaceFeatures.C.
References dictionary::add(), and dictionary::write().
void write (const fileName & fName) const
Write as dictionary to file.
Definition at line 1166 of file surfaceFeatures.C.
void writeObj (const fileName & prefix) const
Write to separate OBJ files (region, external, internal edges,.
feature points) for visualization
Definition at line 1173 of file surfaceFeatures.C.
References Foam::endl(), i, OSstream::name(), Foam::Pout, and Foam::meshTools::writeOBJ().
void writeStats (Ostream & os) const
Write some information.
Definition at line 1225 of file surfaceFeatures.C.
References Foam::endl(), and Foam::nl.
void operator= (const surfaceFeatures & rhs)
Definition at line 1805 of file surfaceFeatures.C.
References Foam::abort(), surfaceFeatures::externalStart(), Foam::FatalError, FatalErrorInFunction, surfaceFeatures::featureEdges(), surfaceFeatures::featurePoints(), surfaceFeatures::internalStart(), and surfaceFeatures::surface().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/surfaceFeatures/surfaceFeatures.H
src/meshTools/triSurface/surfaceFeatures/surfaceFeatures.C