OpenFOAM: LienCubicKE Class Reference
LienCubicKE Class Reference
Lien cubic non-linear low-Reynolds k-epsilon turbulence models for incompressible flows.
Public Member Functions
TypeName ("LienCubicKE")
Runtime type information.
LienCubicKE (const geometricOneField &alpha, const geometricOneField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~LienCubicKE ()=default
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
tmp< volScalarField > DkEff () const
Return the effective diffusivity for k.
tmp< volScalarField > DepsilonEff () const
Return the effective diffusivity for epsilon.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from nonlinearEddyViscosity< incompressible::RASModel >
nonlinearEddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~nonlinearEddyViscosity ()=default
Destructor.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from eddyViscosity< incompressible::RASModel >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()=default
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< incompressible::RASModel >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()=default
Destructor.
Protected Member Functions
tmp< volScalarField > fMu () const
tmp< volScalarField > f2 () const
tmp< volScalarField > E (const volScalarField &f2) const
virtual void correctNut ()
virtual void correctNonlinearStress (const volTensorField &gradU)
Protected Attributes
dimensionedScalar Ceps1_
dimensionedScalar Ceps2_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
dimensionedScalar Cmu1_
dimensionedScalar Cmu2_
dimensionedScalar Cbeta_
dimensionedScalar Cbeta1_
dimensionedScalar Cbeta2_
dimensionedScalar Cbeta3_
dimensionedScalar Cgamma1_
dimensionedScalar Cgamma2_
dimensionedScalar Cgamma4_
dimensionedScalar Cmu_
dimensionedScalar kappa_
dimensionedScalar Anu_
dimensionedScalar AE_
volScalarField k_
volScalarField epsilon_
const volScalarField & y_
Wall distance.
Protected Attributes inherited from nonlinearEddyViscosity< incompressible::RASModel >
volSymmTensorField nonlinearStress_
Protected Attributes inherited from eddyViscosity< incompressible::RASModel >
volScalarField nut_
Additional Inherited Members
Public Types inherited from nonlinearEddyViscosity< incompressible::RASModel >
typedef
incompressible::RASModel::alphaField alphaField
typedef
incompressible::RASModel::rhoField rhoField
typedef
incompressible::RASModel::transportModel transportModel
Public Types inherited from eddyViscosity< incompressible::RASModel >
typedef
incompressible::RASModel::alphaField alphaField
typedef
incompressible::RASModel::rhoField rhoField
typedef
incompressible::RASModel::transportModel transportModel
Public Types inherited from linearViscousStress< incompressible::RASModel >
typedef
incompressible::RASModel::alphaField alphaField
typedef
incompressible::RASModel::rhoField rhoField
typedef
incompressible::RASModel::transportModel transportModel
Detailed Description
Lien cubic non-linear low-Reynolds k-epsilon turbulence models for incompressible flows.
This turbulence model is described in:
    Lien, F.S., Chen, W.L. & Leschziner, M.A. (1996).
    Low-Reynolds-number eddy-viscosity modeling based on non-linear
    stress-strain/vorticity relations.
    Engineering Turbulence Modelling and Experiments 3, 91-100.
Implemented according to the specification in: Apsley: Turbulence Models 2002
In addition to the low-Reynolds number damping functions support for wall-functions is also included to allow for low- and high-Reynolds number operation.
See Also
Foam::incompressible::RASModels::ShihQuadraticKE
Source files
LienCubicKE.H
LienCubicKE.C
Definition at line 76 of file LienCubicKE.H.
Constructor & Destructor Documentation
LienCubicKE (const geometricOneField & alpha, const geometricOneField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 119 of file LienCubicKE.C.
virtual ~LienCubicKE () virtual default
Destructor.
Member Function Documentation
tmp< volScalarField > fMu () const protected
Definition at line 43 of file LienCubicKE.C.
tmp< volScalarField > f2 () const protected
Definition at line 53 of file LienCubicKE.C.
tmp< volScalarField > E (const volScalarField & f2) const protected
Definition at line 61 of file LienCubicKE.C.
References LienCubicKE::epsilon_, Foam::exp(), LienCubicKE::k_, nu, and Foam::sqr().
void correctNut () protected virtual
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 75 of file LienCubicKE.C.
void correctNonlinearStress (const volTensorField & gradU) protected virtual
Implements nonlinearEddyViscosity< incompressible::RASModel >.
Definition at line 81 of file LienCubicKE.C.
References Foam::fvc::grad().
TypeName ("LienCubicKE")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 336 of file LienCubicKE.C.
tmp<volScalarField> DkEff () const inline
Return the effective diffusivity for k.
Definition at line 173 of file LienCubicKE.H.
References nu, eddyViscosity< incompressible::RASModel >::nut_, and LienCubicKE::sigmaEps_.
tmp<volScalarField> DepsilonEff () const inline
Return the effective diffusivity for epsilon.
Definition at line 184 of file LienCubicKE.H.
References LienCubicKE::k_.
virtual tmp<volScalarField> k () const inline virtual
Return the turbulence kinetic energy.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 195 of file LienCubicKE.H.
virtual tmp<volScalarField> epsilon () const inline virtual
Return the turbulence kinetic energy dissipation rate.
Definition at line 203 of file LienCubicKE.H.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Implements eddyViscosity< incompressible::RASModel >.
Definition at line 365 of file LienCubicKE.C.
Member Data Documentation
dimensionedScalar Ceps1_ protected
Definition at line 87 of file LienCubicKE.H.
dimensionedScalar Ceps2_ protected
Definition at line 88 of file LienCubicKE.H.
dimensionedScalar sigmak_ protected
Definition at line 89 of file LienCubicKE.H.
dimensionedScalar sigmaEps_ protected
Definition at line 90 of file LienCubicKE.H.
Referenced by LienCubicKE::DkEff().
dimensionedScalar Cmu1_ protected
Definition at line 91 of file LienCubicKE.H.
dimensionedScalar Cmu2_ protected
Definition at line 92 of file LienCubicKE.H.
dimensionedScalar Cbeta_ protected
Definition at line 93 of file LienCubicKE.H.
dimensionedScalar Cbeta1_ protected
Definition at line 94 of file LienCubicKE.H.
dimensionedScalar Cbeta2_ protected
Definition at line 95 of file LienCubicKE.H.
dimensionedScalar Cbeta3_ protected
Definition at line 96 of file LienCubicKE.H.
dimensionedScalar Cgamma1_ protected
Definition at line 97 of file LienCubicKE.H.
dimensionedScalar Cgamma2_ protected
Definition at line 98 of file LienCubicKE.H.
dimensionedScalar Cgamma4_ protected
Definition at line 99 of file LienCubicKE.H.
dimensionedScalar Cmu_ protected
Definition at line 101 of file LienCubicKE.H.
dimensionedScalar kappa_ protected
Definition at line 102 of file LienCubicKE.H.
dimensionedScalar Anu_ protected
Definition at line 104 of file LienCubicKE.H.
dimensionedScalar AE_ protected
Definition at line 105 of file LienCubicKE.H.
volScalarField k_ protected
Definition at line 110 of file LienCubicKE.H.
Referenced by LienCubicKE::DepsilonEff(), and LienCubicKE::E().
volScalarField epsilon_ protected
Definition at line 111 of file LienCubicKE.H.
Referenced by LienCubicKE::E().
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 119 of file LienCubicKE.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LienCubicKE/LienCubicKE.H
src/TurbulenceModels/incompressible/turbulentTransportModels/RAS/LienCubicKE/LienCubicKE.C