OpenFOAM: JohnsonJackson Class Reference
JohnsonJackson Class Reference
Public Member Functions
TypeName ("JohnsonJackson")
Runtime type information.
JohnsonJackson (const dictionary &dict)
Construct from components.
virtual ~JohnsonJackson ()
Destructor.
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const
virtual bool read ()
TypeName ("JohnsonJackson")
Runtime type information.
JohnsonJackson (const dictionary &dict)
Construct from components.
virtual ~JohnsonJackson ()
Destructor.
virtual tmp< volScalarField > frictionalPressure (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > frictionalPressurePrime (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax) const
virtual tmp< volScalarField > nu (const phaseModel &phase, const dimensionedScalar &alphaMinFriction, const dimensionedScalar &alphaMax, const volScalarField &pf, const volSymmTensorField &D) const
virtual bool read ()
Public Member Functions inherited from frictionalStressModel
TypeName ("frictionalStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
Construct from components.
virtual ~frictionalStressModel ()
Destructor.
TypeName ("frictionalStressModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, frictionalStressModel, dictionary,(const dictionary &dict),(dict))
frictionalStressModel (const dictionary &dict)
Construct from components.
virtual ~frictionalStressModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from frictionalStressModel
static autoPtr
< frictionalStressModel > New (const dictionary &dict)
static autoPtr
< frictionalStressModel > New (const dictionary &dict)
Protected Attributes inherited from frictionalStressModel
const dictionary & dict_
Reference to higher-level dictionary for re-read.
Detailed Description
Source files
JohnsonJacksonFrictionalStress.H
JohnsonJacksonFrictionalStress.C
Source files
JohnsonJacksonFrictionalStress.H
JohnsonJacksonFrictionalStress.C
Definition at line 49 of file JohnsonJacksonFrictionalStress.H.
Constructor & Destructor Documentation
JohnsonJackson (const dictionary & dict)
Construct from components.
Definition at line 51 of file JohnsonJacksonFrictionalStress.C.
~JohnsonJackson () virtual
Destructor.
Definition at line 70 of file JohnsonJacksonFrictionalStress.C.
JohnsonJackson (const dictionary & dict)
Construct from components.
virtual ~JohnsonJackson () virtual
Destructor.
Member Function Documentation
TypeName ("JohnsonJackson")
Runtime type information.
Foam::tmp< Foam::volScalarField > frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
Definition at line 79 of file JohnsonJacksonFrictionalStress.C.
References Foam::constant::atomic::alpha, Foam::max(), and Foam::pow().
Foam::tmp< Foam::volScalarField > frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
Definition at line 96 of file JohnsonJacksonFrictionalStress.C.
Foam::tmp< Foam::volScalarField > nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const virtual
Implements frictionalStressModel.
Definition at line 115 of file JohnsonJacksonFrictionalStress.C.
bool read () virtual
Implements frictionalStressModel.
Definition at line 127 of file JohnsonJacksonFrictionalStress.C.
References Foam::dimTime, and Foam::sin().
TypeName ("JohnsonJackson")
Runtime type information.
virtual tmp<volScalarField> frictionalPressure (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
virtual tmp<volScalarField> frictionalPressurePrime (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax) const virtual
Implements frictionalStressModel.
virtual tmp<volScalarField> nu (const phaseModel & phase, const dimensionedScalar & alphaMinFriction, const dimensionedScalar & alphaMax, const volScalarField & pf, const volSymmTensorField & D) const virtual
Implements frictionalStressModel.
virtual bool read () virtual
Implements frictionalStressModel.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJackson/JohnsonJacksonFrictionalStress.H
applications/solvers/multiphase/twoPhaseEulerFoam/phaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJackson/JohnsonJacksonFrictionalStress.H
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/frictionalStressModel/JohnsonJackson/JohnsonJacksonFrictionalStress.C