OpenFOAM: ThermalPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
ThermalPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
Class to provide interfacial heat and mass transfer between a number of phases according the interfacial temperature approximated by the saturation temperature.
Public Member Functions
ThermalPhaseChangePhaseSystem (const fvMesh &)
Construct from fvMesh.
virtual ~ThermalPhaseChangePhaseSystem ()
Destructor.
const saturationModel & saturation () const
Return the saturationModel.
virtual tmp< volScalarField > dmdt (const phasePairKey &key) const
Return the mass transfer rate for a pair.
virtual PtrList< volScalarField > dmdts () const
Return the mass transfer rates for each phase.
virtual autoPtr
< phaseSystem::heatTransferTable > heatTransfer () const
Return the heat transfer matrices.
virtual autoPtr
< phaseSystem::massTransferTable > massTransfer () const
Return the mass transfer matrices.
virtual void correctInterfaceThermo ()
Correct the interface thermodynamics.
virtual bool read ()
Read base phaseProperties dictionary.
Protected Types
typedef HashPtrTable
< volScalarField, phasePairKey,
phasePairKey::hash > iDmdtTable
typedef HashPtrTable
< volScalarField, phasePairKey,
phasePairKey::hash > wDmdtTable
typedef HashPtrTable
< volScalarField, phasePairKey,
phasePairKey::hash > wMDotLTable
Protected Member Functions
tmp< volScalarField > iDmdt (const phasePairKey &key) const
Return the interfacial mass transfer rate for a pair.
tmp< volScalarField > wDmdt (const phasePairKey &key) const
Return the boundary mass transfer rate for a pair.
Protected Attributes
word volatile_
Name of the volatile specie.
autoPtr< saturationModel > saturationModel_
The saturation model used to evaluate Tsat = Tf.
Switch phaseChange_
iDmdtTable iDmdt_
Interfacial Mass transfer rate.
wDmdtTable wDmdt_
Boundary Mass transfer rate.
wMDotLTable wMDotL_
Boundary thermal energy transfer rate.
Detailed Description
template<class BasePhaseSystem>
class Foam::ThermalPhaseChangePhaseSystem< BasePhaseSystem >
Class to provide interfacial heat and mass transfer between a number of phases according the interfacial temperature approximated by the saturation temperature.
Source files
ThermalPhaseChangePhaseSystem.H
ThermalPhaseChangePhaseSystem.C
Definition at line 51 of file ThermalPhaseChangePhaseSystem.H.
Member Typedef Documentation
typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> iDmdtTable protected
Definition at line 61 of file ThermalPhaseChangePhaseSystem.H.
typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> wDmdtTable protected
Definition at line 64 of file ThermalPhaseChangePhaseSystem.H.
typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> wMDotLTable protected
Definition at line 67 of file ThermalPhaseChangePhaseSystem.H.
Constructor & Destructor Documentation
ThermalPhaseChangePhaseSystem (const fvMesh & mesh)
Construct from fvMesh.
Definition at line 69 of file ThermalPhaseChangePhaseSystem.C.
References IOobject::AUTO_WRITE, Foam::dimDensity, Foam::dimEnergy, Foam::dimTime, Foam::dimVolume, forAllConstIter, IOobject::groupName(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt_, mesh, phasePair::name(), phasePairKey::ordered(), IOobject::READ_IF_PRESENT, HashPtrTable< T, Key, Hash >::set(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::wDmdt_, and ThermalPhaseChangePhaseSystem< BasePhaseSystem >::wMDotL_.
~ThermalPhaseChangePhaseSystem () virtual
Destructor.
Definition at line 160 of file ThermalPhaseChangePhaseSystem.C.
Member Function Documentation
Foam::tmp< Foam::volScalarField > iDmdt (const phasePairKey & key) const protected
Return the interfacial mass transfer rate for a pair.
Definition at line 31 of file ThermalPhaseChangePhaseSystem.C.
Foam::tmp< Foam::volScalarField > wDmdt (const phasePairKey & key) const protected
Return the boundary mass transfer rate for a pair.
Definition at line 49 of file ThermalPhaseChangePhaseSystem.C.
const Foam::saturationModel & saturation () const
Return the saturationModel.
Definition at line 168 of file ThermalPhaseChangePhaseSystem.C.
Foam::tmp< Foam::volScalarField > dmdt (const phasePairKey & key) const virtual
Return the mass transfer rate for a pair.
Definition at line 177 of file ThermalPhaseChangePhaseSystem.C.
Foam::PtrList< Foam::volScalarField > dmdts () const virtual
Return the mass transfer rates for each phase.
Definition at line 187 of file ThermalPhaseChangePhaseSystem.C.
Foam::autoPtr< Foam::phaseSystem::heatTransferTable > heatTransfer () const virtual
Return the heat transfer matrices.
Definition at line 215 of file ThermalPhaseChangePhaseSystem.C.
Foam::autoPtr< Foam::phaseSystem::massTransferTable > massTransfer () const virtual
Return the mass transfer matrices.
Definition at line 277 of file ThermalPhaseChangePhaseSystem.C.
void correctInterfaceThermo () virtual
Correct the interface thermodynamics.
Definition at line 336 of file ThermalPhaseChangePhaseSystem.C.
bool read () virtual
Read base phaseProperties dictionary.
Definition at line 532 of file ThermalPhaseChangePhaseSystem.C.
Member Data Documentation
word volatile_ protected
Name of the volatile specie.
Definition at line 75 of file ThermalPhaseChangePhaseSystem.H.
autoPtr<saturationModel> saturationModel_ protected
The saturation model used to evaluate Tsat = Tf.
Definition at line 80 of file ThermalPhaseChangePhaseSystem.H.
Switch phaseChange_ protected
Definition at line 83 of file ThermalPhaseChangePhaseSystem.H.
iDmdtTable iDmdt_ protected
Interfacial Mass transfer rate.
Definition at line 88 of file ThermalPhaseChangePhaseSystem.H.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem().
wDmdtTable wDmdt_ protected
Boundary Mass transfer rate.
Definition at line 93 of file ThermalPhaseChangePhaseSystem.H.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem().
wMDotLTable wMDotL_ protected
Boundary thermal energy transfer rate.
Definition at line 98 of file ThermalPhaseChangePhaseSystem.H.
Referenced by ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/PhaseSystems/ThermalPhaseChangePhaseSystem/ThermalPhaseChangePhaseSystem.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/PhaseSystems/ThermalPhaseChangePhaseSystem/ThermalPhaseChangePhaseSystem.C