OpenFOAM: formatter Class Reference
formatter Class Reference abstract
Abstract class for a VTK output stream formatter.
Public Types
enum quoteChar : char { DOUBLE_QUOTE = '\"', SINGLE_QUOTE = '\'' }
Quoting for XML attributes.
typedef uint64_t headerType
The header data is vtk UInt64.
Public Member Functions
virtual ~formatter ()=default
Destructor.
std::ostream & os ()
Access to the underlying output stream.
virtual const outputOptions & opts () const =0
The format-type / output options.
virtual const char * name () const =0
Name for the XML output type or the legacy output type.
virtual const char * encoding () const =0
Name for the XML append encoding.
void quoting (const quoteChar quote)
Change quoting char for XML attributes (default: SINGLE_QUOTE)
virtual uint64_t offset (const uint64_t numbytes)
Increase the append data offset by numbytes and sizeof(uint64_t).
virtual std::size_t encodedLength (std::size_t n) const
The encoded length for binary output is pass-through.
virtual bool writeSize (const uint64_t numbytes)=0
Write leading size for binary output.
virtual void write (const uint8_t val)=0
virtual void write (const label val)=0
virtual void write (const float val)=0
virtual void write (const double val)=0
virtual void flush ()=0
Flush encoding, write newline etc.
void indent ()
Add indenting according to the current XML tag depth.
void indent (label n)
Add indenting of n spaces.
formatter & xmlHeader ()
Write XML header.
template<class... Args>
formatter & xmlComment (const std::string &text, Args &&...args)
Write XML comment (at the current indentation level)
template<class... Args>
formatter & openTag (const word &tagName, Args &&...args)
Start an XML tag, optionally with attributes.
template<class... Args>
formatter & openTag (vtk::fileTag t, Args &&...args)
Start an XML tag, optionally with attributes.
formatter & closeTag (const bool isEmpty=false)
Finish an XML tag, optional as an empty container.
formatter & endTag (const word &tagName=word::null)
An end XML tag, optional with sanity check.
virtual formatter & endTag (vtk::fileTag t)
An end XML tag with sanity check.
template<class... Args>
formatter & tag (const word &t, Args &&...args)
Write XML tag without any attributes. Combines openTag/closeTag.
template<class... Args>
formatter & tag (vtk::fileTag t, Args &&...args)
Write XML tag without any attributes. Combines openTag/closeTag.
formatter & beginVTKFile (const word &contentType, const word &contentVersion, const bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
formatter & beginVTKFile (vtk::fileTag contentType, const word &contentVersion, const bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
formatter & beginVTKFile (vtk::fileTag contentType, const bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
template<vtk::fileTag ContentType>
formatter & beginVTKFile (bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
formatter & beginAppendedData ()
Add a "AppendedData" XML tag with the current encoding and output the requisite '_' prefix.
formatter & beginBlock (label index, std::string name="")
Begin "Block" XML section.
formatter & endBlock ()
End "Block" XML section.
formatter & beginPiece (label index, std::string name="")
Begin "Piece" XML section.
virtual formatter & endPiece ()
End "Piece" XML section.
formatter & DataSet (label index, std::string file="", bool autoName=true)
Insert a single "DataSet" XML entry tag.
formatter & DataSet (label index, std::string file, std::string name)
Insert a single "DataSet" XML entry tag.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & beginDataArray (const word &dataName, uint64_t payLoad=npos, bool leaveOpen=false)
Begin "DataArray" XML section.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & beginDataArray (const vtk::dataArrayAttr &dataName, uint64_t payLoad=npos, bool leaveOpen=false)
Begin "DataArray" XML section.
virtual formatter & endDataArray ()
End "DataArray" XML section.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & PDataArray (const word &dataName)
Insert a single "PDataArray" XML entry tag.
formatter & beginFieldData ()
Begin "FieldData" XML section.
formatter & beginCellData ()
Begin "CellData" XML section.
formatter & beginPointData ()
Begin "PointData" XML section.
virtual formatter & endFieldData ()
End "FieldData" XML section.
virtual formatter & endCellData ()
End "CellData" XML section.
virtual formatter & endPointData ()
End "PointData" XML section.
formatter & endAppendedData ()
End "AppendedData" XML section.
virtual formatter & endVTKFile ()
End "VTKFile" XML section.
formatter & writeTimeValue (scalar timeValue)
Emit "TimeValue" for FieldData (name as per Catalyst output)
template<class... Args>
formatter & xmlAttr (const word &k, const std::string &v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const int32_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const int64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const uint64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const scalar v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const std::string &v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const int32_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const int64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const uint64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const scalar v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & openDataArray (const word &dataName)
Open "DataArray" XML tag and leave open (requires a closeTag).
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & openDataArray (const vtk::dataArrayAttr &dataName)
Open "DataArray" XML tag and leave open (requires a closeTag).
template<class... Args>
Foam::vtk::formatter & xmlComment (const std::string &text, Args &&...args)
template<class... Args>
Foam::vtk::formatter & openTag (const word &tagName, Args &&...args)
template<class... Args>
Foam::vtk::formatter & openTag (vtk::fileTag t, Args &&...args)
template<class... Args>
Foam::vtk::formatter & tag (const word &t, Args &&...args)
template<class... Args>
Foam::vtk::formatter & tag (vtk::fileTag t, Args &&...args)
template<Foam::vtk::fileTag ContentType>
Foam::vtk::formatter & beginVTKFile (bool leaveOpen)
template<class Type , Foam::direction nComp, int nTuple>
Foam::vtk::formatter & beginDataArray (const vtk::dataArrayAttr &dataName, uint64_t payLoad, bool leaveOpen)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const std::string &v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const int32_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const int64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const uint64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const scalar v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const std::string &v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const int32_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const int64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const uint64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const scalar v, Args &&...args)
template<class Type , Foam::direction nComp, int nTuple>
Foam::vtk::formatter & beginDataArray (const word &dataName, uint64_t payLoad, bool leaveOpen)
template<class Type , Foam::direction nComp, int nTuple>
Foam::vtk::formatter & PDataArray (const word &dataName)
Static Public Attributes
static constexpr uint64_t npos = uint64_t(-1)
Out of range position or size.
Protected Member Functions
bool canWriteAttr (const word &k) const
Can write XML key/value attribute pair when inside a tag. Emit warning and return false if this condition is not met.
bool canWriteToplevel (const char *what) const
Can write tag-like top-level content (eg, comment, ...) when not already inside a tag. Emit warning and return false if this condition is not met.
template<class Type >
void writeAttr (const word &k, const Type &v)
Write XML key/value attribute pair (implementation).
formatter & xmlAttr ()
No-op write XML attribute (for templating code).
void xmlCommentLoop ()
No-op XML comment loop (for templating code).
template<class... Args>
void xmlCommentLoop (const std::string &text, Args &&...args)
Loop/output XML comments.
bool openTagImpl (const word &tagName)
Open XML tag (implementation), checking if not already inside another tag. Emit warning and return false if this condition is not met.
formatter (std::ostream &os)
Construct and attach to an output stream.
Protected Attributes
std::ostream & os_
The output stream for the formatter.
DynamicList< word > xmlTags_
LIFO stack of current XML tags.
bool inTag_
Tag open/closed/ended state.
char quote_
Quoting character for XML attributes.
Detailed Description
Abstract class for a VTK output stream formatter.
Includes simple support for writing XML elements. By default uses single-quoting for XML attributes.
Source files
foamVtkFormatter.H
foamVtkFormatter.C
foamVtkFormatterTemplates.C
Definition at line 64 of file foamVtkFormatter.H.
Member Typedef Documentation
typedef uint64_t headerType
The header data is vtk UInt64.
Definition at line 167 of file foamVtkFormatter.H.
Member Enumeration Documentation
enum quoteChar : char
Quoting for XML attributes.
Enumerator
DOUBLE_QUOTE
Double-quote XML attributes.
SINGLE_QUOTE
Single-quote XML attributes.
Definition at line 71 of file foamVtkFormatter.H.
Constructor & Destructor Documentation
formatter (std::ostream & os) inline protected
Construct and attach to an output stream.
Definition at line 52 of file foamVtkFormatterI.H.
virtual ~formatter () virtual default
Destructor.
Member Function Documentation
bool canWriteAttr (const word & k) const protected
Can write XML key/value attribute pair when inside a tag. Emit warning and return false if this condition is not met.
Definition at line 24 of file foamVtkFormatter.C.
References formatter::inTag_, and WarningInFunction.
bool canWriteToplevel (const char * what) const protected
Can write tag-like top-level content (eg, comment, ...) when not already inside a tag. Emit warning and return false if this condition is not met.
Definition at line 36 of file foamVtkFormatter.C.
void writeAttr (const word & k, const Type & v) inline protected
Write XML key/value attribute pair (implementation).
Definition at line 314 of file foamVtkFormatterI.H.
Foam::vtk::formatter & xmlAttr () inline protected
No-op write XML attribute (for templating code).
Returns
formatter for chaining
Definition at line 23 of file foamVtkFormatterI.H.
Referenced by formatter::beginDataArray().
void xmlCommentLoop () inline protected
No-op XML comment loop (for templating code).
Definition at line 29 of file foamVtkFormatterI.H.
void xmlCommentLoop (const std::string & text, Args &&... args) inline protected
Loop/output XML comments.
Definition at line 35 of file foamVtkFormatterI.H.
bool openTagImpl (const word & tagName) protected
Open XML tag (implementation), checking if not already inside another tag. Emit warning and return false if this condition is not met.
Definition at line 69 of file foamVtkFormatter.C.
References n.
std::ostream & os () inline
Access to the underlying output stream.
Definition at line 63 of file foamVtkFormatterI.H.
Referenced by appendRawFormatter::appendRawFormatter(), Foam::vtk::legacy::beginCellData(), Foam::vtk::legacy::beginPointData(), Foam::vtk::legacy::doubleField(), Foam::vtk::legacy::fieldData(), Foam::vtk::legacy::floatField(), and Foam::vtk::legacy::intField().
virtual const outputOptions& opts () const pure virtual
The format-type / output options.
Implemented in asciiFormatter, appendRawFormatter, legacyRawFormatter, appendBase64Formatter, legacyAsciiFormatter, and base64Formatter.
virtual const char* name () const pure virtual
Name for the XML output type or the legacy output type.
Implemented in asciiFormatter, appendRawFormatter, legacyRawFormatter, appendBase64Formatter, legacyAsciiFormatter, and base64Formatter.
Referenced by formatter::beginDataArray().
virtual const char* encoding () const pure virtual
Name for the XML append encoding.
Implemented in asciiFormatter, appendRawFormatter, legacyRawFormatter, legacyAsciiFormatter, and foamVtkBase64Layer.
void quoting (const quoteChar quote)
Change quoting char for XML attributes (default: SINGLE_QUOTE)
Definition at line 51 of file foamVtkFormatter.C.
uint64_t offset (const uint64_t numbytes) virtual
Increase the append data offset by numbytes and sizeof(uint64_t).
The additional (uint64_t) size information is consistent with writeSize()
Returns
The previous data offset or formatter::npos for formats that do not support appending data.
Reimplemented in appendRawFormatter, and appendBase64Formatter.
Definition at line 57 of file foamVtkFormatter.C.
Referenced by formatter::beginDataArray().
std::size_t encodedLength (std::size_t n) const virtual
The encoded length for binary output is pass-through.
Reimplemented in asciiFormatter, and foamVtkBase64Layer.
Definition at line 63 of file foamVtkFormatter.C.
References formatter::npos.
virtual bool writeSize (const uint64_t numbytes) pure virtual
Write leading size for binary output.
Returns
True if used by the formatter.
Implemented in appendRawFormatter, asciiFormatter, legacyRawFormatter, and foamVtkBase64Layer.
Referenced by lagrangianWriter::write(), and fileWriter::writeUniform().
virtual void write (const uint8_t val) pure virtual
Implemented in appendRawFormatter, asciiFormatter, legacyRawFormatter, and foamVtkBase64Layer.
Referenced by Foam::vtk::write().
virtual void write (const label val) pure virtual
Implemented in appendRawFormatter, asciiFormatter, legacyRawFormatter, and foamVtkBase64Layer.
virtual void write (const float val) pure virtual
Implemented in appendRawFormatter, asciiFormatter, legacyRawFormatter, and foamVtkBase64Layer.
virtual void write (const double val) pure virtual
Implemented in appendRawFormatter, asciiFormatter, legacyRawFormatter, and foamVtkBase64Layer.
virtual void flush () pure virtual
Flush encoding, write newline etc.
Implemented in appendRawFormatter, asciiFormatter, legacyRawFormatter, foamVtkBase64Layer, and base64Formatter.
Referenced by lagrangianWriter::write(), and fileWriter::writeUniform().
void indent () inline
Add indenting according to the current XML tag depth.
Two spaces per depth.
Definition at line 69 of file foamVtkFormatterI.H.
void indent (label n) inline
Add indenting of n spaces.
Definition at line 75 of file foamVtkFormatterI.H.
References Foam::indent().
Foam::vtk::formatter & xmlHeader () inline
Write XML header.
Returns
formatter for chaining
Definition at line 84 of file foamVtkFormatterI.H.
formatter& xmlComment (const std::string & text, Args &&... args) inline
Write XML comment (at the current indentation level)
Returns
formatter for chaining
formatter& openTag (const word & tagName, Args &&... args) inline
Start an XML tag, optionally with attributes.
Returns
formatter for chaining
Referenced by formatter::beginDataArray().
formatter& openTag (vtk::fileTag t, Args &&... args) inline
Start an XML tag, optionally with attributes.
Returns
formatter for chaining
Foam::vtk::formatter & closeTag (const bool isEmpty = false)
Finish an XML tag, optional as an empty container.
Always adds a trailing newline.
Returns
formatter for chaining
Definition at line 92 of file foamVtkFormatter.C.
Referenced by formatter::beginDataArray().
Foam::vtk::formatter & endTag (const word & tagName = word::null)
An end XML tag, optional with sanity check.
Always adds a trailing newline.
Returns
formatter for chaining
Definition at line 118 of file foamVtkFormatter.C.
Foam::vtk::formatter & endTag (vtk::fileTag t) inline virtual
An end XML tag with sanity check.
Always adds a trailing newline.
Returns
formatter for chaining
Reimplemented in legacyRawFormatter, and legacyAsciiFormatter.
Definition at line 263 of file foamVtkFormatterI.H.
References Foam::vtk::FIELD_DATA.
formatter& tag (const word & t, Args &&... args) inline
Write XML tag without any attributes. Combines openTag/closeTag.
Returns
formatter for chaining
formatter& tag (vtk::fileTag t, Args &&... args) inline
Write XML tag without any attributes. Combines openTag/closeTag.
Returns
formatter for chaining
Foam::vtk::formatter & beginVTKFile (const word & contentType, const word & contentVersion, const bool leaveOpen = false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
Parameters
leaveOpen Leave tag open for additional attributes.
Returns
formatter for chaining
Definition at line 151 of file foamVtkFormatter.C.
Foam::vtk::formatter & beginVTKFile (vtk::fileTag contentType, const word & contentVersion, const bool leaveOpen = false) inline
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
Parameters
leaveOpen Leave tag open for additional attributes.
Returns
formatter for chaining
Definition at line 183 of file foamVtkFormatterI.H.
Foam::vtk::formatter & beginVTKFile (vtk::fileTag contentType, const bool leaveOpen = false) inline
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
Parameters
leaveOpen Leave tag open for additional attributes.
Returns
formatter for chaining
Definition at line 199 of file foamVtkFormatterI.H.
formatter& beginVTKFile (bool leaveOpen = false) inline
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
Parameters
leaveOpen Leave tag open for additional attributes.
Returns
formatter for chaining
Foam::vtk::formatter & beginAppendedData ()
Add a "AppendedData" XML tag with the current encoding and output the requisite '_' prefix.
Returns
formatter for chaining
Definition at line 174 of file foamVtkFormatter.C.
Foam::vtk::formatter & beginBlock (label index, std::string name = "")
Begin "Block" XML section.
Parameters
index The index of the block
name The name of the block (ignored if empty)
Returns
formatter for chaining
Definition at line 194 of file foamVtkFormatter.C.
Foam::vtk::formatter & endBlock () inline
End "Block" XML section.
Returns
formatter for chaining
Definition at line 293 of file foamVtkFormatterI.H.
References Foam::vtk::DATA_ARRAY.
Foam::vtk::formatter & beginPiece (label index, std::string name = "")
Begin "Piece" XML section.
Parameters
index The index of the piece
name The name of the piece (ignored if empty)
Returns
formatter for chaining
Definition at line 215 of file foamVtkFormatter.C.
Foam::vtk::formatter & endPiece () inline virtual
End "Piece" XML section.
Returns
formatter for chaining
Reimplemented in legacyRawFormatter, and legacyAsciiFormatter.
Definition at line 299 of file foamVtkFormatterI.H.
References Foam::vtk::BLOCK.
Foam::vtk::formatter & DataSet (label index, std::string file = "", bool autoName = true)
Insert a single "DataSet" XML entry tag.
Parameters
index The index of the DataSet
file The file name for the data (ignored if empty)
autoName The name for the data extracted from the file name (without extension)
Returns
formatter for chaining
Definition at line 236 of file foamVtkFormatter.C.
Foam::vtk::formatter & DataSet (label index, std::string file, std::string name)
Insert a single "DataSet" XML entry tag.
Parameters
index The index of the DataSet
file The file name for the data (ignored if empty)
name The name for the dataset
Returns
formatter for chaining
Definition at line 263 of file foamVtkFormatter.C.
formatter& beginDataArray (const word & dataName, uint64_t payLoad = npos, bool leaveOpen = false)
Begin "DataArray" XML section.
Parameters
dataName The name of the DataArray
payLoad Additional payLoad information to increment the offset for an append formatter and add the "offset" attribute accordingly.
leaveOpen Leave tag open for additional attributes.
Returns
formatter for chaining
Referenced by lagrangianWriter::write(), and fileWriter::writeUniform().
formatter& beginDataArray (const vtk::dataArrayAttr & dataName, uint64_t payLoad = npos, bool leaveOpen = false) inline
Begin "DataArray" XML section.
Parameters
dataName The name of the DataArray as an enumeration
payLoad Additional payLoad information to increment the offset for an append formatter and add the "offset" attribute accordingly.
leaveOpen Leave tag open for additional attributes.
Returns
formatter for chaining
Foam::vtk::formatter & endDataArray () inline virtual
End "DataArray" XML section.
Returns
formatter for chaining
Reimplemented in legacyRawFormatter, and legacyAsciiFormatter.
Definition at line 287 of file foamVtkFormatterI.H.
References Foam::vtk::FIELD_DATA.
Referenced by fileWriter::writeUniform().
formatter& PDataArray (const word & dataName)
Insert a single "PDataArray" XML entry tag.
For some entries, the name is optional.
Returns
formatter for chaining
Foam::vtk::formatter & beginFieldData () inline
Begin "FieldData" XML section.
Definition at line 255 of file foamVtkFormatterI.H.
References Foam::vtk::POINT_DATA.
Foam::vtk::formatter & beginCellData () inline
Begin "CellData" XML section.
Definition at line 243 of file foamVtkFormatterI.H.
Foam::vtk::formatter & beginPointData () inline
Begin "PointData" XML section.
Definition at line 249 of file foamVtkFormatterI.H.
References Foam::vtk::CELL_DATA.
Foam::vtk::formatter & endFieldData () inline virtual
End "FieldData" XML section.
Reimplemented in legacyRawFormatter, and legacyAsciiFormatter.
Definition at line 281 of file foamVtkFormatterI.H.
References Foam::vtk::POINT_DATA.
Foam::vtk::formatter & endCellData () inline virtual
End "CellData" XML section.
Reimplemented in legacyRawFormatter, and legacyAsciiFormatter.
Definition at line 269 of file foamVtkFormatterI.H.
References Foam::vtk::fileTagNames.
Foam::vtk::formatter & endPointData () inline virtual
End "PointData" XML section.
Reimplemented in legacyRawFormatter, and legacyAsciiFormatter.
Definition at line 275 of file foamVtkFormatterI.H.
References Foam::vtk::CELL_DATA.
Foam::vtk::formatter & endAppendedData ()
End "AppendedData" XML section.
Returns
formatter for chaining
Definition at line 185 of file foamVtkFormatter.C.
Foam::vtk::formatter & endVTKFile () inline virtual
End "VTKFile" XML section.
Returns
formatter for chaining
Reimplemented in legacyRawFormatter, and legacyAsciiFormatter.
Definition at line 305 of file foamVtkFormatterI.H.
References Foam::vtk::PIECE.
Foam::vtk::formatter & writeTimeValue (scalar timeValue)
Emit "TimeValue" for FieldData (name as per Catalyst output)
Definition at line 289 of file foamVtkFormatter.C.
formatter& xmlAttr (const word & k, const std::string & v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const word & k, const int32_t v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const word & k, const int64_t v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const word & k, const uint64_t v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const word & k, const scalar v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const vtk::fileAttr & k, const std::string & v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const vtk::fileAttr & k, const int32_t v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const vtk::fileAttr & k, const int64_t v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const vtk::fileAttr & k, const uint64_t v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& xmlAttr (const vtk::fileAttr & k, const scalar v, Args &&... args) inline
Pair-wise write of XML key/value attributes.
Returns
formatter for chaining
formatter& openDataArray (const word & dataName) inline
Open "DataArray" XML tag and leave open (requires a closeTag).
Deprecated:
Use beginDataArray instead (SEPT-2018)
Definition at line 703 of file foamVtkFormatter.H.
formatter& openDataArray (const vtk::dataArrayAttr & dataName) inline
Open "DataArray" XML tag and leave open (requires a closeTag).
Deprecated:
Use beginDataArray instead (SEPT-2018)
Definition at line 717 of file foamVtkFormatter.H.
Foam::vtk::formatter& xmlComment (const std::string & text, Args &&... args) inline
Definition at line 97 of file foamVtkFormatterI.H.
Foam::vtk::formatter& openTag (const word & tagName, Args &&... args) inline
Definition at line 129 of file foamVtkFormatterI.H.
Foam::vtk::formatter& openTag (vtk::fileTag t, Args &&... args) inline
Definition at line 145 of file foamVtkFormatterI.H.
Foam::vtk::formatter& tag (const word & t, Args &&... args) inline
Definition at line 156 of file foamVtkFormatterI.H.
References args, and Foam::vtk::fileTagNames.
Foam::vtk::formatter& tag (vtk::fileTag t, Args &&... args) inline
Definition at line 171 of file foamVtkFormatterI.H.
Foam::vtk::formatter& beginVTKFile (bool leaveOpen) inline
Definition at line 214 of file foamVtkFormatterI.H.
Foam::vtk::formatter& beginDataArray (const vtk::dataArrayAttr & dataName, uint64_t payLoad, bool leaveOpen) inline
Definition at line 227 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const word & k, const std::string & v, Args &&... args) inline
Definition at line 322 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const word & k, const int32_t v, Args &&... args) inline
Definition at line 337 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const word & k, const int64_t v, Args &&... args) inline
Definition at line 352 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const word & k, const uint64_t v, Args &&... args) inline
Definition at line 367 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const word & k, const scalar v, Args &&... args) inline
Definition at line 382 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const vtk::fileAttr & k, const std::string & v, Args &&... args) inline
Definition at line 397 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const vtk::fileAttr & k, const int32_t v, Args &&... args) inline
Definition at line 412 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const vtk::fileAttr & k, const int64_t v, Args &&... args) inline
Definition at line 427 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const vtk::fileAttr & k, const uint64_t v, Args &&... args) inline
Definition at line 442 of file foamVtkFormatterI.H.
Foam::vtk::formatter& xmlAttr (const vtk::fileAttr & k, const scalar v, Args &&... args) inline
Definition at line 457 of file foamVtkFormatterI.H.
Foam::vtk::formatter& beginDataArray (const word & dataName, uint64_t payLoad, bool leaveOpen)
Definition at line 26 of file foamVtkFormatterTemplates.C.
References formatter::closeTag(), Foam::vtk::DATA_ARRAY, formatter::name(), formatter::npos, Foam::vtk::NUMBER_OF_COMPONENTS, Foam::vtk::NUMBER_OF_TUPLES, formatter::offset(), formatter::openTag(), and formatter::xmlAttr().
Foam::vtk::formatter& PDataArray (const word & dataName)
Definition at line 66 of file foamVtkFormatterTemplates.C.
Member Data Documentation
std::ostream& os_ protected
The output stream for the formatter.
Definition at line 85 of file foamVtkFormatter.H.
DynamicList<word> xmlTags_ protected
LIFO stack of current XML tags.
Definition at line 90 of file foamVtkFormatter.H.
bool inTag_ mutable protected
Tag open/closed/ended state.
Definition at line 95 of file foamVtkFormatter.H.
Referenced by formatter::canWriteAttr().
char quote_ protected
Quoting character for XML attributes.
Definition at line 100 of file foamVtkFormatter.H.
constexpr uint64_t npos = uint64_t(-1) static
Out of range position or size.
Definition at line 172 of file foamVtkFormatter.H.
Referenced by formatter::beginDataArray(), and formatter::encodedLength().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/format/foamVtkFormatter.H
src/fileFormats/vtk/format/foamVtkFormatter.C
src/fileFormats/vtk/format/foamVtkFormatterI.H
src/fileFormats/vtk/format/foamVtkFormatterTemplates.C