OpenFOAM: InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem > Class Template Reference
Class to provide interfacial heat and mass transfer between a number of phases according to a interface composition model.
Public Member Functions
InterfaceCompositionPhaseChangePhaseSystem (const fvMesh &)
Construct from fvMesh.
virtual ~InterfaceCompositionPhaseChangePhaseSystem ()
Destructor.
virtual tmp< volScalarField > dmdt (const phasePairKey &key) const
Return the mass transfer rate for a pair.
virtual PtrList< volScalarField > dmdts () const
Return the mass transfer rates for each phase.
virtual autoPtr
< phaseSystem::massTransferTable > massTransfer () const
Return the mass transfer matrices.
virtual void correctInterfaceThermo ()
Correct the interface temperatures.
virtual bool read ()
Read base phaseProperties dictionary.
Protected Types
typedef HashTable< autoPtr
< interfaceCompositionModel >
, phasePairKey,
phasePairKey::hash > interfaceCompositionModelTable
typedef HashTable< Pair
< autoPtr
< BlendedInterfacialModel
< massTransferModel >
> >, phasePairKey,
phasePairKey::hash > massTransferModelTable
typedef HashPtrTable
< HashPtrTable< volScalarField >
, phasePairKey,
phasePairKey::hash > iDmdtSuSpTable
typedef HashPtrTable
< volScalarField, phasePairKey,
phasePairKey::hash > iDmdtTable
Protected Member Functions
virtual tmp< volScalarField > iDmdt (const phasePairKey &key) const
Return the interfacial mass transfer rate for a pair for a pair.
Protected Attributes
const label nInterfaceCorrectors_
The number of interface correctors.
massTransferModelTable massTransferModels_
Mass transfer models.
interfaceCompositionModelTable interfaceCompositionModels_
Interface composition models.
iDmdtSuSpTable iDmdtSu_
The explicit part of the interfacial mass transfer rates.
iDmdtSuSpTable iDmdtSp_
The implicit part of the interfacial mass transfer rates.
Detailed Description
template<class BasePhaseSystem>
class Foam::InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >
Class to provide interfacial heat and mass transfer between a number of phases according to a interface composition model.
The interface temperature is calculated such that the net rate at which the heat is transferred to the interface is equal to the latent heat consumed by the mass transfer.
Source files
InterfaceCompositionPhaseChangePhaseSystem.H
InterfaceCompositionPhaseChangePhaseSystem.C
Definition at line 55 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Member Typedef Documentation
typedef HashTable< autoPtr<interfaceCompositionModel>, phasePairKey, phasePairKey::hash > interfaceCompositionModelTable protected
Definition at line 68 of file InterfaceCompositionPhaseChangePhaseSystem.H.
typedef HashTable< Pair<autoPtr<BlendedInterfacialModel<massTransferModel> > >, phasePairKey, phasePairKey::hash > massTransferModelTable protected
Definition at line 75 of file InterfaceCompositionPhaseChangePhaseSystem.H.
typedef HashPtrTable< HashPtrTable<volScalarField>, phasePairKey, phasePairKey::hash > iDmdtSuSpTable protected
Definition at line 83 of file InterfaceCompositionPhaseChangePhaseSystem.H.
typedef HashPtrTable<volScalarField, phasePairKey, phasePairKey::hash> iDmdtTable protected
Definition at line 86 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Constructor & Destructor Documentation
InterfaceCompositionPhaseChangePhaseSystem (const fvMesh & mesh)
Construct from fvMesh.
Definition at line 88 of file InterfaceCompositionPhaseChangePhaseSystem.C.
References Foam::dimDensity, Foam::dimTime, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAllConstIter, IOobject::groupName(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdtSp_, InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdtSu_, phasePair::index(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::interfaceCompositionModels_, InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::massTransferModels_, mesh, phasePair::name(), phaseModel::name(), phasePairKey::ordered(), phasePair::phase1(), phasePair::phase2(), HashPtrTable< T, Key, Hash >::set(), and interfaceCompositionModel::species().
~InterfaceCompositionPhaseChangePhaseSystem () virtual
Destructor.
Definition at line 241 of file InterfaceCompositionPhaseChangePhaseSystem.C.
Member Function Documentation
Foam::tmp< Foam::volScalarField > iDmdt (const phasePairKey & key) const protected virtual
Return the interfacial mass transfer rate for a pair for a pair.
Definition at line 31 of file InterfaceCompositionPhaseChangePhaseSystem.C.
References FixedList< T, N >::first(), forAllConstIter, iter, phaseModel::name(), Foam::name(), phases, tmp< T >::ref(), Pair< T >::second(), and phaseModel::Y().
Foam::tmp< Foam::volScalarField > dmdt (const phasePairKey & key) const virtual
Return the mass transfer rate for a pair.
Definition at line 250 of file InterfaceCompositionPhaseChangePhaseSystem.C.
Foam::PtrList< Foam::volScalarField > dmdts () const virtual
Return the mass transfer rates for each phase.
Definition at line 260 of file InterfaceCompositionPhaseChangePhaseSystem.C.
Foam::autoPtr< Foam::phaseSystem::massTransferTable > massTransfer () const virtual
Return the mass transfer matrices.
Definition at line 307 of file InterfaceCompositionPhaseChangePhaseSystem.C.
void correctInterfaceThermo () virtual
Correct the interface temperatures.
Definition at line 385 of file InterfaceCompositionPhaseChangePhaseSystem.C.
bool read () virtual
Read base phaseProperties dictionary.
Definition at line 500 of file InterfaceCompositionPhaseChangePhaseSystem.C.
Member Data Documentation
const label nInterfaceCorrectors_ protected
The number of interface correctors.
Definition at line 96 of file InterfaceCompositionPhaseChangePhaseSystem.H.
massTransferModelTable massTransferModels_ protected
Mass transfer models.
Definition at line 101 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
interfaceCompositionModelTable interfaceCompositionModels_ protected
Interface composition models.
Definition at line 106 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
iDmdtSuSpTable iDmdtSu_ mutable protected
The explicit part of the interfacial mass transfer rates.
Definition at line 111 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
iDmdtSuSpTable iDmdtSp_ mutable protected
The implicit part of the interfacial mass transfer rates.
Definition at line 116 of file InterfaceCompositionPhaseChangePhaseSystem.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/PhaseSystems/InterfaceCompositionPhaseChangePhaseSystem/InterfaceCompositionPhaseChangePhaseSystem.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/PhaseSystems/InterfaceCompositionPhaseChangePhaseSystem/InterfaceCompositionPhaseChangePhaseSystem.C