OpenFOAM: Cole Class Reference
Cole Class Reference
Cole correlation for bubble departure frequency.
Public Member Functions
TypeName ("Cole")
Runtime type information.
Cole (const dictionary &dict)
Construct from a dictionary.
virtual ~Cole ()
Destructor.
virtual tmp< scalarField > fDeparture (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &dDep) const
Calculate and return the bubble departure frequency.
Public Member Functions inherited from departureFrequencyModel
TypeName ("departureFrequencyModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, departureFrequencyModel, dictionary,(const dictionary &dict),(dict))
Declare runtime construction.
departureFrequencyModel ()
Construct null.
virtual ~departureFrequencyModel ()
Destructor.
virtual void write (Ostream &os) const
Additional Inherited Members
Static Public Member Functions inherited from departureFrequencyModel
static autoPtr
< departureFrequencyModel > New (const dictionary &dict)
Select null constructed.
Detailed Description
Cole correlation for bubble departure frequency.
Reference:
    Cole, R. (1960).
    A photographic study of pool boiling in the region of the critical heat
    flux.
    AIChE Journal, 6(4), 533-538.
Source files
Cole.H
Cole.C
Definition at line 58 of file Cole.H.
Constructor & Destructor Documentation
Cole (const dictionary & dict)
Construct from a dictionary.
Definition at line 52 of file Cole.C.
~Cole () virtual
Destructor.
Definition at line 61 of file Cole.C.
Member Function Documentation
TypeName ("Cole")
Runtime type information.
Foam::tmp< Foam::scalarField > fDeparture (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & dDep) const virtual
Calculate and return the bubble departure frequency.
Implements departureFrequencyModel.
Definition at line 70 of file Cole.C.
References g, Foam::mag(), Foam::max(), DimensionedField< Type, GeoMesh >::mesh(), rhoThermo::rho(), Foam::sqrt(), phaseModel::thermo(), and value().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/departureFrequencyModels/Cole/Cole.H
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/departureFrequencyModels/Cole/Cole.C