OpenFOAM: Matrix< Form, Type > Class Template Reference
Matrix< Form, Type > Class Template Reference
A templated (m x n) matrix of objects of <T>. The layout is (mRows x nCols) - row-major order:
Public Types
typedef Matrix< Form, Type > mType
Matrix type.
typedef Type cmptType
Component type.
typedef Type * iterator
Random access iterator for traversing a Matrix.
typedef const Type * const_iterator
Random access iterator for traversing a Matrix.
Public Member Functions
Matrix ()
Construct null.
Matrix (const label m, const label n)
Construct given number of rows/columns.
Matrix (const label m, const label n, const zero)
Construct with given number of rows/columns initializing all elements to zero.
Matrix (const label m, const label n, const Type &val)
Construct with given number of rows/columns initializing all elements to the given value.
Matrix (const labelPair &dims)
Construct given number of rows/columns.
Matrix (const labelPair &dims, const zero)
Construct given number of rows/columns initializing all elements to zero.
Matrix (const labelPair &dims, const Type &val)
Construct with given number of rows/columns initializing all elements to the given value.
Matrix (const Matrix< Form, Type > &mat)
Copy construct.
Matrix (Matrix< Form, Type > &&mat)
Move construct.
template<class Form2 >
Matrix (const Matrix< Form2, Type > &mat)
Copy constructor from Matrix of a different form.
template<class MatrixType >
Matrix (const ConstMatrixBlock< MatrixType > &Mb)
Construct from a block of another Matrix.
template<class MatrixType >
Matrix (const MatrixBlock< MatrixType > &Mb)
Construct from a block of another Matrix.
Matrix (Istream &is)
Construct from Istream.
autoPtr< mType > clone () const
Clone.
~Matrix ()
Destructor.
label m () const noexcept
The number of rows.
label n () const noexcept
The number of columns.
label size () const
The number of elements in Matrix (m*n)
labelPair sizes () const
Return row/column sizes.
bool empty () const noexcept
Return true if Matrix is empty (i.e., size() is zero)
const Type * cdata () const noexcept
Return const pointer to the first data element, which can also be used to address into Matrix contents.
Type * data () noexcept
Return pointer to the first data element, which can also be used to address into Matrix contents.
const Type * rowData (const label irow) const
Return const pointer to data in the specified row.
Type * rowData (const label irow)
Return pointer to data in the specified row.
const Type & at (const label idx) const
Linear addressing const element access.
Type & at (const label idx)
Linear addressing element access.
ConstMatrixBlock< mType > subColumn (const label colIndex, const label rowIndex=0, label len=-1) const
Return const column or column's subset of Matrix.
ConstMatrixBlock< mType > subRow (const label rowIndex, const label colIndex=0, label len=-1) const
Return const row or const row's subset of Matrix.
ConstMatrixBlock< mType > subMatrix (const label rowIndex, const label colIndex, label szRows=-1, label szCols=-1) const
Return const sub-block of Matrix.
template<class VectorSpace >
ConstMatrixBlock< mType > block (const label rowIndex, const label colIndex) const
Access Field as a ConstMatrixBlock.
MatrixBlock< mType > subColumn (const label colIndex, const label rowIndex=0, label len=-1)
Return column or column's subset of Matrix.
MatrixBlock< mType > subRow (const label rowIndex, const label colIndex=0, label len=-1)
Return row or row's subset of Matrix.
MatrixBlock< mType > subMatrix (const label rowIndex, const label colIndex, label szRows=-1, label szCols=-1)
Return sub-block of Matrix.
template<class VectorSpace >
MatrixBlock< mType > block (const label rowIndex, const label colIndex)
Access Field as a MatrixBlock.
void checki (const label irow) const
Check index i is within valid range [0, m)
void checkj (const label jcol) const
Check index j is within valid range [0, n)
void checkSize () const
Check that dimensions are positive, non-zero.
bool uniform () const
True if all entries have identical values, and Matrix is non-empty.
void clear ()
Clear Matrix, i.e. set sizes to zero.
List< Type > release ()
Release storage management of Matrix contents by transferring management to a List.
void swap (Matrix< Form, Type > &mat)
Swap contents.
void transfer (Matrix< Form, Type > &mat)
Transfer the contents of the argument Matrix into this Matrix and annul the argument Matrix.
void resize (const label m, const label n)
Change Matrix dimensions, preserving the elements.
void setSize (const label m, const label n)
Change Matrix dimensions, preserving the elements.
void shallowResize (const label m, const label n)
Resize Matrix without reallocating storage (unsafe)
void round (const scalar tol=SMALL)
Round to zero elements with magnitude smaller than tol (SMALL)
Form T () const
Return (conjugate) transpose of Matrix.
tmp< Field< Type > > Amul (const UList< Type > &x) const
Right-multiply Matrix by a column vector (A * x)
template<class Addr >
tmp< Field< Type > > Amul (const IndirectListBase< Type, Addr > &x) const
Right-multiply Matrix by a column vector (A * x)
tmp< Field< Type > > Tmul (const UList< Type > &x) const
Left-multiply Matrix by a row vector (x * A)
template<class Addr >
tmp< Field< Type > > Tmul (const IndirectListBase< Type, Addr > &x) const
Left-multiply Matrix by a row vector (x * A)
List< Type > diag () const
Extract the diagonal elements. Method may change in the future.
void diag (const UList< Type > &list)
Assign diagonal of Matrix.
Type trace () const
Return the trace.
scalar columnNorm (const label colIndex, const bool noSqrt=false) const
Return L2-Norm of chosen column.
scalar norm (const bool noSqrt=false) const
Return Frobenius norm of Matrix.
const Type * operator[] (const label irow) const
Return const pointer to data in the specified row - rowData().
Type * operator[] (const label irow)
Return pointer to data in the specified row - rowData().
const Type & operator() (const label irow, const label jcol) const
(i, j) const element access operator
Type & operator() (const label irow, const label jcol)
(i, j) element access operator
void operator= (const Matrix< Form, Type > &mat)
Copy assignment. Takes linear time.
void operator= (Matrix< Form, Type > &&mat)
Move assignment.
template<class MatrixType >
void operator= (const ConstMatrixBlock< MatrixType > &Mb)
Assignment to a block of another Matrix.
template<class MatrixType >
void operator= (const MatrixBlock< MatrixType > &Mb)
Assignment to a block of another Matrix.
void operator= (const zero)
Assignment of all elements to zero.
void operator= (const Type &val)
Assignment of all elements to the given value.
void operator+= (const Matrix< Form, Type > &other)
Matrix addition.
void operator-= (const Matrix< Form, Type > &other)
Matrix subtraction.
void operator+= (const Type &s)
Matrix scalar addition.
void operator-= (const Type &s)
Matrix scalar subtraction.
void operator*= (const Type &s)
Matrix scalar multiplication.
void operator/= (const Type &s)
Matrix scalar division.
iterator begin ()
Return an iterator to begin traversing a Matrix.
iterator end ()
Return an iterator to end traversing a Matrix.
const_iterator cbegin () const
Return const_iterator to begin traversing a constant Matrix.
const_iterator cend () const
Return const_iterator to end traversing a constant Matrix.
const_iterator begin () const
Return const_iterator to begin traversing a constant Matrix.
const_iterator end () const
Return const_iterator to end traversing a constant Matrix.
bool readMatrix (Istream &is)
Read Matrix from Istream, discarding existing contents.
Ostream & writeMatrix (Ostream &os, const label shortLen=0) const
Write Matrix, with line-breaks in ASCII when length exceeds shortLen.
label mRows () const noexcept
The number of rows - same as m()
label nRows () const noexcept
The number of rows - same as m()
label nCols () const noexcept
The number of columns - same as n()
const Type * FOAM_DEPRECATED_FOR (2019-04,"cdata() method") v() const
Deprecated(2019-04) raw data pointer, const access.
Type * FOAM_DEPRECATED_FOR (2019-04,"data() method") v()
Deprecated(2019-04) raw data pointer, non-const access.
ConstMatrixBlock< mType > FOAM_DEPRECATED_FOR (2019-04,"subMatrix() method") block(const label m
Deprecated(2019-04) - use subMatrix()
MatrixBlock< mType > FOAM_DEPRECATED_FOR (2019-04,"subMatrix() method") block(const label m
Deprecated(2019-04) - use subMatrix()
ConstMatrixBlock< mType > FOAM_DEPRECATED_FOR (2019-04,"subColumn() method") col(const label m
Deprecated(2019-04) - use subColumn()
MatrixBlock< mType > FOAM_DEPRECATED_FOR (2019-04,"subColumn() method") col(const label m
Deprecated(2019-04) - use subColumn()
void col (const label m, const label rowStart) const =delete
Deleted(2019-04) - use subColumn()
void col (const label m, const label rowStart)=delete
Deleted(2019-04) - use subColumn()
template<class ListType >
Foam::tmp< Foam::Field< Type > > AmulImpl (const ListType &x) const
template<class ListType >
Foam::tmp< Foam::Field< Type > > TmulImpl (const ListType &x) const
template<class VectorSpace >
Foam::ConstMatrixBlock
< Foam::Matrix< Form, Type > > block (const label rowIndex, const label colIndex) const
template<class VectorSpace >
Foam::MatrixBlock
< Foam::Matrix< Form, Type > > block (const label rowIndex, const label colIndex)
template<class Addr >
Foam::tmp< Foam::Field< Type > > Amul (const IndirectListBase< Type, Addr > &x) const
template<class Addr >
Foam::tmp< Foam::Field< Type > > Tmul (const IndirectListBase< Type, Addr > &x) const
Static Public Member Functions
static const Matrix< Form, Type > & null ()
Return a null Matrix.
Public Attributes
ConstMatrixBlock< mType >
const label n
ConstMatrixBlock< mType >
const label const label mStart
ConstMatrixBlock< mType >
const label const label const
label nStart const
MatrixBlock< mType > const label n
MatrixBlock< mType > const
label const label mStart
MatrixBlock< mType > const
label const label const label nStart
ConstMatrixBlock< mType >
const label mStart
ConstMatrixBlock< mType >
const label const label
nStart const
MatrixBlock< mType > const label mStart
MatrixBlock< mType > const
label const label nStart
Detailed Description
template<class Form, class Type>
class Foam::Matrix< Form, Type >
A templated (m x n) matrix of objects of <T>. The layout is (mRows x nCols) - row-major order:
    (0,0)
      +---> j [nCols]
      |
      |
      v
      i [mRows]
Source files
Matrix.H
Matrix.C
MatrixI.H
MatrixIO.C
Definition at line 44 of file DiagonalMatrix.H.
Member Typedef Documentation
typedef Matrix<Form, Type> mType
Matrix type.
Definition at line 110 of file Matrix.H.
typedef Type cmptType
Component type.
Definition at line 115 of file Matrix.H.
typedef Type* iterator
Random access iterator for traversing a Matrix.
Definition at line 131 of file Matrix.H.
typedef const Type* const_iterator
Random access iterator for traversing a Matrix.
Definition at line 136 of file Matrix.H.
Constructor & Destructor Documentation
Matrix () inline
Construct null.
Definition at line 41 of file MatrixI.H.
Matrix (const label m, const label n)
Construct given number of rows/columns.
Definition at line 102 of file Matrix.C.
Matrix (const label m, const label n, const zero)
Construct with given number of rows/columns initializing all elements to zero.
Definition at line 115 of file Matrix.C.
Matrix (const label m, const label n, const Type & val)
Construct with given number of rows/columns initializing all elements to the given value.
Definition at line 130 of file Matrix.C.
Matrix (const labelPair & dims) inline explicit
Construct given number of rows/columns.
Definition at line 50 of file MatrixI.H.
Matrix (const labelPair & dims, const zero) inline
Construct given number of rows/columns initializing all elements to zero.
Definition at line 57 of file MatrixI.H.
Matrix (const labelPair & dims, const Type & val) inline
Construct with given number of rows/columns initializing all elements to the given value.
Definition at line 64 of file MatrixI.H.
Matrix (const Matrix< Form, Type > & mat)
Copy construct.
Definition at line 145 of file Matrix.C.
Matrix (Matrix< Form, Type > && mat)
Move construct.
Definition at line 161 of file Matrix.C.
Matrix (const Matrix< Form2, Type > & mat) explicit
Copy constructor from Matrix of a different form.
Definition at line 175 of file Matrix.C.
Matrix (const ConstMatrixBlock< MatrixType > & Mb) inline
Construct from a block of another Matrix.
Definition at line 193 of file Matrix.C.
Matrix (const MatrixBlock< MatrixType > & Mb) inline
Construct from a block of another Matrix.
Definition at line 215 of file Matrix.C.
Matrix (Istream & is) explicit
Construct from Istream.
Definition at line 33 of file MatrixIO.C.
~Matrix ()
Destructor.
Definition at line 237 of file Matrix.C.
Member Function Documentation
const Foam::Matrix< Form, Type > & null () inline static
Return a null Matrix.
Definition at line 81 of file MatrixI.H.
Foam::autoPtr< Foam::Matrix< Form, Type > > clone () const inline
Clone.
Definition at line 72 of file MatrixI.H.
Foam::label m () const inline noexcept
The number of rows.
Definition at line 88 of file MatrixI.H.
Referenced by Matrix< Form, Type >::AmulImpl(), Foam::solve(), and SVD::SVD().
label n () const inline noexcept
The number of columns.
Foam::label size () const inline
The number of elements in Matrix (m*n)
Definition at line 102 of file MatrixI.H.
Referenced by Foam::MatrixTools::equal().
Foam::labelPair sizes () const inline
Return row/column sizes.
Definition at line 109 of file MatrixI.H.
bool empty () const inline noexcept
Return true if Matrix is empty (i.e., size() is zero)
Definition at line 116 of file MatrixI.H.
const Type * cdata () const inline noexcept
Return const pointer to the first data element, which can also be used to address into Matrix contents.
Definition at line 194 of file MatrixI.H.
Type * data () inline noexcept
Return pointer to the first data element, which can also be used to address into Matrix contents.
Definition at line 201 of file MatrixI.H.
const Type * rowData (const label irow) const inline
Return const pointer to data in the specified row.
Subscript checking only with FULLDEBUG
Definition at line 208 of file MatrixI.H.
Type * rowData (const label irow) inline
Return pointer to data in the specified row.
Subscript checking only with FULLDEBUG
Definition at line 218 of file MatrixI.H.
const Type & at (const label idx) const inline
Linear addressing const element access.
Subscript checking only with FULLDEBUG
Definition at line 228 of file MatrixI.H.
Type & at (const label idx) inline
Linear addressing element access.
Subscript checking only with FULLDEBUG
Definition at line 243 of file MatrixI.H.
Foam::ConstMatrixBlock< Foam::Matrix< Form, Type > > subColumn (const label colIndex, const label rowIndex = 0, label len = -1) const inline
Return const column or column's subset of Matrix.
Return entire column by its index: M.subColumn(a); Return subset of a column starting from rowIndex: M.subColumn(a, b); Return subset of a column starting from rowIndex with szRows elems: M.subColumn(a, b, c);
Definition at line 260 of file MatrixI.H.
Foam::ConstMatrixBlock< Foam::Matrix< Form, Type > > subRow (const label rowIndex, const label colIndex = 0, label len = -1) const inline
Return const row or const row's subset of Matrix.
Return entire row by its index: M.subRow(a); Return subset of a row starting from columnIndex: M.subRow(a,b); Return subset of a row starting from columnIndex with szCols elems: M.subRow(a, b, c);
Definition at line 285 of file MatrixI.H.
Foam::ConstMatrixBlock< Foam::Matrix< Form, Type > > subMatrix (const label rowIndex, const label colIndex, label szRows = -1, label szCols = -1) const inline
Return const sub-block of Matrix.
Sub-block starting at columnIndex & rowIndex indices
Definition at line 310 of file MatrixI.H.
ConstMatrixBlock<mType> block (const label rowIndex, const label colIndex) const inline
Access Field as a ConstMatrixBlock.
Foam::MatrixBlock< Foam::Matrix< Form, Type > > subColumn (const label colIndex, const label rowIndex = 0, label len = -1) inline
Return column or column's subset of Matrix.
Definition at line 354 of file MatrixI.H.
Foam::MatrixBlock< Foam::Matrix< Form, Type > > subRow (const label rowIndex, const label colIndex = 0, label len = -1) inline
Return row or row's subset of Matrix.
Definition at line 379 of file MatrixI.H.
Foam::MatrixBlock< Foam::Matrix< Form, Type > > subMatrix (const label rowIndex, const label colIndex, label szRows = -1, label szCols = -1) inline
Return sub-block of Matrix.
Definition at line 404 of file MatrixI.H.
MatrixBlock<mType> block (const label rowIndex, const label colIndex) inline
Access Field as a MatrixBlock.
void checki (const label irow) const inline
Check index i is within valid range [0, m)
Definition at line 123 of file MatrixI.H.
void checkj (const label jcol) const inline
Check index j is within valid range [0, n)
Definition at line 141 of file MatrixI.H.
void checkSize () const inline
Check that dimensions are positive, non-zero.
Definition at line 159 of file MatrixI.H.
bool uniform () const inline
True if all entries have identical values, and Matrix is non-empty.
Definition at line 172 of file MatrixI.H.
void clear ()
Clear Matrix, i.e. set sizes to zero.
Definition at line 249 of file Matrix.C.
Foam::List< Type > release ()
Release storage management of Matrix contents by transferring management to a List.
Definition at line 263 of file Matrix.C.
void swap (Matrix< Form, Type > & mat)
Swap contents.
Definition at line 283 of file Matrix.C.
void transfer (Matrix< Form, Type > & mat)
Transfer the contents of the argument Matrix into this Matrix and annul the argument Matrix.
Definition at line 297 of file Matrix.C.
void resize (const label m, const label n)
Change Matrix dimensions, preserving the elements.
Definition at line 317 of file Matrix.C.
void setSize (const label m, const label n) inline
Change Matrix dimensions, preserving the elements.
Definition at line 446 of file MatrixI.H.
void shallowResize (const label m, const label n) inline
Resize Matrix without reallocating storage (unsafe)
Definition at line 453 of file MatrixI.H.
References resize().
void round (const scalar tol = SMALL)
Round to zero elements with magnitude smaller than tol (SMALL)
Definition at line 342 of file Matrix.C.
Form T () const
Return (conjugate) transpose of Matrix.
Definition at line 355 of file Matrix.C.
Foam::tmp< Foam::Field< Type > > Amul (const UList< Type > & x) const inline
Right-multiply Matrix by a column vector (A * x)
Definition at line 462 of file MatrixI.H.
tmp<Field<Type> > Amul (const IndirectListBase< Type, Addr > & x) const inline
Right-multiply Matrix by a column vector (A * x)
Foam::tmp< Foam::Field< Type > > Tmul (const UList< Type > & x) const inline
Left-multiply Matrix by a row vector (x * A)
Definition at line 483 of file MatrixI.H.
tmp<Field<Type> > Tmul (const IndirectListBase< Type, Addr > & x) const inline
Left-multiply Matrix by a row vector (x * A)
Foam::List< Type > diag () const
Extract the diagonal elements. Method may change in the future.
Definition at line 372 of file Matrix.C.
void diag (const UList< Type > & list)
Assign diagonal of Matrix.
Definition at line 388 of file Matrix.C.
Type trace () const
Return the trace.
Definition at line 409 of file Matrix.C.
References i.
Foam::scalar columnNorm (const label colIndex, const bool noSqrt = false) const
Return L2-Norm of chosen column.
Optional without sqrt for parallel usage.
Definition at line 426 of file Matrix.C.
Foam::scalar norm (const bool noSqrt = false) const
Return Frobenius norm of Matrix.
Optional without sqrt for parallel usage. https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm
Definition at line 443 of file Matrix.C.
const Type * operator[] (const label irow) const inline
Return const pointer to data in the specified row - rowData().
Subscript checking only with FULLDEBUG
Definition at line 585 of file MatrixI.H.
Type * operator[] (const label irow) inline
Return pointer to data in the specified row - rowData().
Subscript checking only with FULLDEBUG
Definition at line 595 of file MatrixI.H.
const Type & operator() (const label irow, const label jcol) const inline
(i, j) const element access operator
Subscript checking only with FULLDEBUG
Definition at line 556 of file MatrixI.H.
Type & operator() (const label irow, const label jcol) inline
(i, j) element access operator
Subscript checking only with FULLDEBUG
Definition at line 571 of file MatrixI.H.
void operator= (const Matrix< Form, Type > & mat)
Copy assignment. Takes linear time.
Definition at line 459 of file Matrix.C.
void operator= (Matrix< Form, Type > && mat)
Move assignment.
Definition at line 482 of file Matrix.C.
References Matrix< Form, Type >::cbegin(), and Matrix< Form, Type >::cend().
void operator= (const ConstMatrixBlock< MatrixType > & Mb)
Assignment to a block of another Matrix.
Definition at line 495 of file Matrix.C.
void operator= (const MatrixBlock< MatrixType > & Mb)
Assignment to a block of another Matrix.
Definition at line 512 of file Matrix.C.
void operator= (const zero)
Assignment of all elements to zero.
Definition at line 534 of file Matrix.C.
References stdFoam::begin(), and end().
void operator= (const Type & val)
Assignment of all elements to the given value.
Definition at line 527 of file Matrix.C.
void operator+= (const Matrix< Form, Type > & other)
Matrix addition.
Definition at line 541 of file Matrix.C.
References stdFoam::begin(), end(), and Foam::Zero.
void operator-= (const Matrix< Form, Type > & other)
Matrix subtraction.
Definition at line 571 of file Matrix.C.
void operator+= (const Type & s)
Matrix scalar addition.
Definition at line 601 of file Matrix.C.
void operator-= (const Type & s)
Matrix scalar subtraction.
Definition at line 611 of file Matrix.C.
References s.
void operator*= (const Type & s)
Matrix scalar multiplication.
Definition at line 621 of file Matrix.C.
References s.
void operator/= (const Type & s)
Matrix scalar division.
Definition at line 631 of file Matrix.C.
References s.
Foam::Matrix< Form, Type >::iterator begin () inline
Return an iterator to begin traversing a Matrix.
Definition at line 506 of file MatrixI.H.
Foam::Matrix< Form, Type >::iterator end () inline
Return an iterator to end traversing a Matrix.
Definition at line 514 of file MatrixI.H.
Foam::Matrix< Form, Type >::const_iterator cbegin () const inline
Return const_iterator to begin traversing a constant Matrix.
Definition at line 522 of file MatrixI.H.
Referenced by Foam::MatrixTools::equal(), and Matrix< Form, Type >::operator=().
Foam::Matrix< Form, Type >::const_iterator cend () const inline
Return const_iterator to end traversing a constant Matrix.
Definition at line 530 of file MatrixI.H.
Referenced by Matrix< Form, Type >::operator=().
Foam::Matrix< Form, Type >::const_iterator begin () const inline
Return const_iterator to begin traversing a constant Matrix.
Definition at line 538 of file MatrixI.H.
Foam::Matrix< Form, Type >::const_iterator end () const inline
Return const_iterator to end traversing a constant Matrix.
Definition at line 546 of file MatrixI.H.
bool readMatrix (Istream & is)
Read Matrix from Istream, discarding existing contents.
Definition at line 44 of file MatrixIO.C.
References Foam::operator>>().
Foam::Ostream & writeMatrix (Ostream & os, const label shortLen = 0) const
Write Matrix, with line-breaks in ASCII when length exceeds shortLen.
Using '0' suppresses line-breaks entirely.
Definition at line 135 of file MatrixIO.C.
label mRows () const inline noexcept
The number of rows - same as m()
Definition at line 679 of file Matrix.H.
label nRows () const inline noexcept
The number of rows - same as m()
Definition at line 687 of file Matrix.H.
label nCols () const inline noexcept
The number of columns - same as n()
Definition at line 695 of file Matrix.H.
const Type* FOAM_DEPRECATED_FOR (2019- 04, "cdata() method") const inline
Deprecated(2019-04) raw data pointer, const access.
Deprecated:
(2019-04) - use cdata() method
Definition at line 706 of file Matrix.H.
Type* FOAM_DEPRECATED_FOR (2019- 04, "data() method") inline
Deprecated(2019-04) raw data pointer, non-const access.
Deprecated:
(2019-04) - use data() method
Definition at line 716 of file Matrix.H.
ConstMatrixBlock<mType> FOAM_DEPRECATED_FOR (2019- 04, "subMatrix< Form, Type >() method") const
Deprecated(2019-04) - use subMatrix()
Deprecated:
(2019-04) - use subMatrix()
MatrixBlock<mType> FOAM_DEPRECATED_FOR (2019- 04, "subMatrix< Form, Type >() method") const
Deprecated(2019-04) - use subMatrix()
Deprecated:
(2019-04) - use subMatrix()
ConstMatrixBlock<mType> FOAM_DEPRECATED_FOR (2019- 04, "subColumn() method") const
Deprecated(2019-04) - use subColumn()
Deprecated:
(2019-04) - use subColumn()
MatrixBlock<mType> FOAM_DEPRECATED_FOR (2019- 04, "subColumn() method") const
Deprecated(2019-04) - use subColumn()
Deprecated:
(2019-04) - use subColumn()
void col (const label m, const label rowStart) const delete
Deleted(2019-04) - use subColumn()
Deprecated:
(2019-04) - use subColumn()
void col (const label m, const label rowStart) delete
Deleted(2019-04) - use subColumn()
Deprecated:
(2019-04) - use subColumn()
Foam::tmp<Foam::Field<Type> > AmulImpl (const ListType & x) const
Definition at line 31 of file Matrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, i, j, Matrix< Form, Type >::m(), Matrix< Form, Type >::n, Foam::New(), Foam::nl, and Foam::Zero.
Foam::tmp<Foam::Field<Type> > TmulImpl (const ListType & x) const
Definition at line 66 of file Matrix.C.
Foam::ConstMatrixBlock<Foam::Matrix<Form, Type> > block (const label rowIndex, const label colIndex) const inline
Definition at line 335 of file MatrixI.H.
Foam::MatrixBlock<Foam::Matrix<Form, Type> > block (const label rowIndex, const label colIndex) inline
Definition at line 429 of file MatrixI.H.
Foam::tmp<Foam::Field<Type> > Amul (const IndirectListBase< Type, Addr > & x) const inline
Definition at line 473 of file MatrixI.H.
Foam::tmp<Foam::Field<Type> > Tmul (const IndirectListBase< Type, Addr > & x) const inline
Definition at line 494 of file MatrixI.H.
Member Data Documentation
Foam::label n inline noexcept
Definition at line 730 of file Matrix.H.
Referenced by Matrix< Form, Type >::AmulImpl(), and SVD::SVD().
ConstMatrixBlock<mType> const label const label mStart
Definition at line 730 of file Matrix.H.
ConstMatrixBlock<mType> const label const label const label nStart const
Initial value:
{
            return this->subMatrix(mStart, nStart, m, n)
Definition at line 734 of file Matrix.H.
MatrixBlock<mType> const label n
Definition at line 747 of file Matrix.H.
MatrixBlock<mType> const label const label mStart
Definition at line 747 of file Matrix.H.
MatrixBlock<mType> const label const label const label nStart
Initial value:
{
            return this->subMatrix(mStart, nStart, m, n)
Definition at line 751 of file Matrix.H.
ConstMatrixBlock<mType> const label mStart
Definition at line 765 of file Matrix.H.
ConstMatrixBlock<mType> const label const label nStart const
Initial value:
{
            return this->subColumn(nStart, mStart, m)
Definition at line 768 of file Matrix.H.
MatrixBlock<mType> const label mStart
Definition at line 781 of file Matrix.H.
MatrixBlock<mType> const label const label nStart
Initial value:
{
            return this->subColumn(nStart, mStart, m)
Definition at line 784 of file Matrix.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/DiagonalMatrix/DiagonalMatrix.H
src/OpenFOAM/matrices/Matrix/Matrix.H
src/OpenFOAM/matrices/Matrix/Matrix.C
src/OpenFOAM/matrices/Matrix/MatrixI.H
src/OpenFOAM/matrices/Matrix/MatrixIO.C