OpenFOAM: FixedList< T, N > Class Template Reference
FixedList< T, N > Class Template Reference
A 1D vector of objects of type <T> with a fixed length <N>.
Classes
struct Hash
Hashing function class for FixedList.
Public Types
typedef T value_type
The value type the FixedList contains.
typedef T * pointer
The pointer type for non-const access to value_type items.
typedef const T * const_pointer
The pointer type for const access to value_type items.
typedef T & reference
The type used for storing into value_type objects.
typedef const T & const_reference
The type used for reading from constant value_type objects.
typedef T * iterator
Random access iterator for traversing FixedList.
typedef const T * const_iterator
Random access iterator for traversing FixedList.
typedef label size_type
The type to represent the size of a FixedList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Public Member Functions
FixedList ()=default
Null constructor.
FixedList (const T &val)
Construct and initialize all entries to given value.
FixedList (const zero)
Construct and initialize all entries to zero.
FixedList (const T list[N])
Copy construct from C-array.
FixedList (const FixedList< T, N > &list)
Copy constructor.
FixedList (FixedList< T, N > &&list)
Move construct by using move assignment for the individual list elements.
template<class InputIterator >
FixedList (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
FixedList (std::initializer_list< T > list)
Construct from an initializer list.
FixedList (const UList< T > &list)
Construct from UList.
FixedList (const SLList< T > &list)
Construct from SLList.
FixedList (Istream &is)
Construct from Istream.
autoPtr< FixedList< T, N > > clone () const
Clone.
const T * cdata () const noexcept
Return a const pointer to the first data element.
T * data () noexcept
Return a pointer to the first data element.
T & first () noexcept
The first element of the list, position [0].
const T & first () const noexcept
The first element of the list, position [0].
T & last () noexcept
The last element of the list, position [N-1].
const T & last () const noexcept
The last element of the list, position [N-1].
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const T & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
T & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const T & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
T & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is identical to template parameter N.
void checkIndex (const label i) const
Check index is within valid range [0,N)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const T &val, const label start=0) const
Find index of the first occurence of the value.
bool found (const T &val, const label start=0) const
True if the value if found in the list. Linear search.
void resize (const label n)
Dummy resize function, to make FixedList consistent with List.
void setSize (const label n)
Dummy setSize function, to make FixedList consistent with List.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element.
void swapLast (const label i)
Swap element with the last element.
void transfer (FixedList< T, N > &list)
Transfer by swapping using a move assignment for the content of the individual list elements.
T & operator[] (const label i)
Return element of FixedList.
const T & operator[] (const label i) const
Return element of constant FixedList.
void operator= (const T list[N])
Assignment to array operator. Takes linear time.
void operator= (const UList< T > &list)
Assignment to UList operator. Takes linear time.
void operator= (const SLList< T > &list)
Assignment to SLList operator. Takes linear time.
void operator= (std::initializer_list< T > list)
Assignment to an initializer list. Takes linear time.
void operator= (const T &val)
Assignment of all entries to the given value.
void operator= (const FixedList< T, N > &list)
Copy assignment.
void operator= (FixedList< T, N > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
void swap (FixedList< T, N > &list)
Swap lists by swapping the content of the individual list elements.
bool operator== (const FixedList< T, N > &list) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< T, N > &list) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< T, N > &list) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< T, N > &list) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< T, N > &list) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< T, N > &list) const
Return true if !(a < b). Takes linear time.
void writeEntry (const word &keyword, Ostream &os) const
Write the list as a dictionary entry with keyword.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
Static Public Member Functions
static const FixedList< T, N > & null ()
Return a null FixedList.
static constexpr bool empty () noexcept
Always false since zero-sized FixedList is compile-time disabled.
static constexpr label size () noexcept
Return the number of elements in the FixedList.
static constexpr unsigned max_size () noexcept
The dimensioned size (template parameter N) of the FixedList.
Protected Member Functions
void writeEntry (Ostream &os) const
Write the FixedList with its compound type.
Friends
Istream & operator>> (Istream &is, FixedList< T, N > &list)
Read from Istream, discarding contents of existing List.
Detailed Description
template<class T, unsigned N>
class Foam::FixedList< T, N >
A 1D vector of objects of type <T> with a fixed length <N>.
Source files
FixedList.H
FixedList.C
FixedListI.H
FixedListIO.C
Definition at line 100 of file HashTable.H.
Member Typedef Documentation
typedef T value_type
The value type the FixedList contains.
Definition at line 106 of file FixedList.H.
typedef T* pointer
The pointer type for non-const access to value_type items.
Definition at line 111 of file FixedList.H.
typedef const T* const_pointer
The pointer type for const access to value_type items.
Definition at line 116 of file FixedList.H.
typedef T& reference
The type used for storing into value_type objects.
Definition at line 121 of file FixedList.H.
typedef const T& const_reference
The type used for reading from constant value_type objects.
Definition at line 126 of file FixedList.H.
typedef T* iterator
Random access iterator for traversing FixedList.
Definition at line 131 of file FixedList.H.
typedef const T* const_iterator
Random access iterator for traversing FixedList.
Definition at line 136 of file FixedList.H.
typedef label size_type
The type to represent the size of a FixedList.
Definition at line 141 of file FixedList.H.
typedef label difference_type
The difference between iterator objects.
Definition at line 146 of file FixedList.H.
typedef std::reverse_iterator<iterator> reverse_iterator
Reverse iterator (non-const access)
Definition at line 151 of file FixedList.H.
typedef std::reverse_iterator<const_iterator> const_reverse_iterator
Reverse iterator (const access)
Definition at line 156 of file FixedList.H.
Constructor & Destructor Documentation
FixedList () inline default
Null constructor.
FixedList (const T & val) inline explicit
Construct and initialize all entries to given value.
Definition at line 39 of file FixedListI.H.
FixedList (const zero) inline explicit
Construct and initialize all entries to zero.
Definition at line 49 of file FixedListI.H.
References i, and Foam::val.
FixedList (const T list[N]) inline explicit
Copy construct from C-array.
Definition at line 59 of file FixedListI.H.
References i, and Foam::Zero.
FixedList (const FixedList< T, N > & list) inline
Copy constructor.
Definition at line 69 of file FixedListI.H.
References i.
FixedList (FixedList< T, N > && list) inline
Move construct by using move assignment for the individual list elements.
Definition at line 79 of file FixedListI.H.
References i.
FixedList (InputIterator begIter, InputIterator endIter) inline
Construct given begin/end iterators.
Uses std::distance when verifying the size.
Definition at line 91 of file FixedListI.H.
FixedList (std::initializer_list< T > list) inline
Construct from an initializer list.
Definition at line 107 of file FixedListI.H.
FixedList (const UList< T > & list) inline explicit
Construct from UList.
Definition at line 121 of file FixedListI.H.
FixedList (const SLList< T > & list) inline explicit
Construct from SLList.
Definition at line 133 of file FixedListI.H.
References i.
FixedList (Istream & is) explicit
Construct from Istream.
Definition at line 134 of file FixedListIO.C.
Member Function Documentation
void writeEntry (Ostream & os) const protected
Write the FixedList with its compound type.
Definition at line 30 of file FixedListIO.C.
const Foam::FixedList< T, N > & null () inline static
Return a null FixedList.
Definition at line 30 of file FixedListI.H.
Foam::autoPtr< Foam::FixedList< T, N > > clone () const inline
Clone.
Definition at line 148 of file FixedListI.H.
const T * cdata () const inline noexcept
Return a const pointer to the first data element.
Similar to the STL front() method and the string::data() method This can be used (with caution) when interfacing with C code
Definition at line 158 of file FixedListI.H.
T * data () inline noexcept
Return a pointer to the first data element.
Similar to the STL front() method and the string::data() method This can be used (with caution) when interfacing with C code
Definition at line 166 of file FixedListI.H.
T & first () inline noexcept
The first element of the list, position [0].
Definition at line 173 of file FixedListI.H.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt(), solutionControl::maxTypeResidual(), statsEqOp::operator()(), multiphaseMixtureThermo::interfacePair::hash::operator()(), multiphaseMixture::interfacePair::hash::operator()(), PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem(), and SquareMatrix< Type >::SquareMatrix().
const T & first () const inline noexcept
The first element of the list, position [0].
Definition at line 180 of file FixedListI.H.
T & last () inline noexcept
The last element of the list, position [N-1].
Definition at line 187 of file FixedListI.H.
Referenced by solutionControl::maxTypeResidual().
const T & last () const inline noexcept
The last element of the list, position [N-1].
Definition at line 194 of file FixedListI.H.
Foam::label fcIndex (const label i) const inline
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
Definition at line 201 of file FixedListI.H.
Referenced by triSurfaceTools::vertexNormalWeight().
const T & fcValue (const label i) const inline
Return forward circular value (ie, next value in the list)
Definition at line 208 of file FixedListI.H.
T & fcValue (const label i) inline
Return forward circular value (ie, next value in the list)
Definition at line 215 of file FixedListI.H.
Foam::label rcIndex (const label i) const inline
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
Definition at line 222 of file FixedListI.H.
const T & rcValue (const label i) const inline
Return reverse circular value (ie, previous value in the list)
Definition at line 229 of file FixedListI.H.
T & rcValue (const label i) inline
Return reverse circular value (ie, previous value in the list)
Definition at line 236 of file FixedListI.H.
void checkStart (const label start) const inline
Check start is within valid range [0,size)
Definition at line 243 of file FixedListI.H.
void checkSize (const label size) const inline
Check size is identical to template parameter N.
Definition at line 256 of file FixedListI.H.
void checkIndex (const label i) const inline
Check index is within valid range [0,N)
Definition at line 268 of file FixedListI.H.
bool uniform () const inline
True if all entries have identical values, and list is non-empty.
Definition at line 280 of file FixedListI.H.
Foam::label find (const T & val, const label start = 0) const
Find index of the first occurence of the value.
Linear search.
Returns
-1 if not found.
Definition at line 29 of file FixedList.C.
References i, List_CONST_ACCESS, N(), and T.
Referenced by triFace::sweptVol(), and triSurfaceTools::vertexNormalWeight().
bool found (const T & val, const label start = 0) const inline
True if the value if found in the list. Linear search.
Definition at line 298 of file FixedListI.H.
Referenced by triFace::which().
void resize (const label n) inline
Dummy resize function, to make FixedList consistent with List.
Definition at line 308 of file FixedListI.H.
References Foam::ListOps::find().
void setSize (const label n) inline
Dummy setSize function, to make FixedList consistent with List.
Definition at line 316 of file FixedListI.H.
void moveFirst (const label i)
Move element to the first position.
Definition at line 52 of file FixedList.C.
void moveLast (const label i)
Move element to the last position.
Definition at line 64 of file FixedList.C.
References Foam::stringOps::lower(), and Foam::Swap().
void swapFirst (const label i)
Swap element with the first element.
Definition at line 76 of file FixedList.C.
References Foam::Swap(), and Foam::stringOps::upper().
void swapLast (const label i)
Swap element with the last element.
Definition at line 88 of file FixedList.C.
References Foam::Swap().
void transfer (FixedList< T, N > & list) inline
Transfer by swapping using a move assignment for the content of the individual list elements.
Definition at line 340 of file FixedListI.H.
References Foam::Swap().
T & operator[] (const label i) inline
Return element of FixedList.
Definition at line 357 of file FixedListI.H.
const T & operator[] (const label i) const inline
Return element of constant FixedList.
Definition at line 367 of file FixedListI.H.
void operator= (const T list[N]) inline
Assignment to array operator. Takes linear time.
Definition at line 377 of file FixedListI.H.
void operator= (const UList< T > & list) inline
Assignment to UList operator. Takes linear time.
Definition at line 386 of file FixedListI.H.
References i.
void operator= (const SLList< T > & list) inline
Assignment to SLList operator. Takes linear time.
Definition at line 397 of file FixedListI.H.
References i.
void operator= (std::initializer_list< T > list) inline
Assignment to an initializer list. Takes linear time.
Definition at line 410 of file FixedListI.H.
References i, and iter.
void operator= (const T & val) inline
Assignment of all entries to the given value.
Definition at line 423 of file FixedListI.H.
References i, and iter.
void operator= (const FixedList< T, N > & list) inline
Copy assignment.
Definition at line 432 of file FixedListI.H.
References i, and Foam::val.
void operator= (FixedList< T, N > && list) inline
Move assignment.
Definition at line 446 of file FixedListI.H.
References i.
Foam::FixedList< T, N >::iterator begin () inline
Return an iterator to begin traversing the FixedList.
Definition at line 466 of file FixedListI.H.
Referenced by bitSet::bitSet(), edge::erase(), HashSet< Key, Hash >::insert(), edge::insert(), HashSet< Key, Hash >::operator=(), bitSet::unset(), and HashSet< Key, Hash >::unset().
Foam::FixedList< T, N >::iterator end () inline
Return an iterator to end traversing the FixedList.
Definition at line 490 of file FixedListI.H.
Referenced by bitSet::bitSet(), edge::erase(), HashSet< Key, Hash >::insert(), edge::insert(), HashSet< Key, Hash >::operator=(), bitSet::unset(), and HashSet< Key, Hash >::unset().
Foam::FixedList< T, N >::const_iterator cbegin () const inline
Return const_iterator to begin traversing the constant FixedList.
Definition at line 482 of file FixedListI.H.
Referenced by HashTable< T, Key, Hash >::erase().
Foam::FixedList< T, N >::const_iterator cend () const inline
Return const_iterator to end traversing the constant FixedList.
Definition at line 506 of file FixedListI.H.
Referenced by HashTable< T, Key, Hash >::erase().
Foam::FixedList< T, N >::const_iterator begin () const inline
Return const_iterator to begin traversing the constant FixedList.
Definition at line 474 of file FixedListI.H.
Foam::FixedList< T, N >::const_iterator end () const inline
Return const_iterator to end traversing the constant FixedList.
Definition at line 498 of file FixedListI.H.
Foam::FixedList< T, N >::reverse_iterator rbegin () inline
Return reverse_iterator to begin reverse traversing the FixedList.
Definition at line 514 of file FixedListI.H.
Foam::FixedList< T, N >::reverse_iterator rend () inline
Return reverse_iterator to end reverse traversing the FixedList.
Definition at line 538 of file FixedListI.H.
References end().
Foam::FixedList< T, N >::const_reverse_iterator crbegin () const inline
Return const_reverse_iterator to begin reverse traversing FixedList.
Definition at line 530 of file FixedListI.H.
References end().
Foam::FixedList< T, N >::const_reverse_iterator crend () const inline
Return const_reverse_iterator to end reverse traversing FixedList.
Definition at line 554 of file FixedListI.H.
References stdFoam::begin().
Foam::FixedList< T, N >::const_reverse_iterator rbegin () const inline
Return const_reverse_iterator to begin reverse traversing FixedList.
Definition at line 522 of file FixedListI.H.
References end().
Foam::FixedList< T, N >::const_reverse_iterator rend () const inline
Return const_reverse_iterator to end reverse traversing FixedList.
Definition at line 546 of file FixedListI.H.
References stdFoam::begin().
static constexpr bool empty () inline static noexcept
Always false since zero-sized FixedList is compile-time disabled.
Definition at line 511 of file FixedList.H.
static constexpr label size () inline static noexcept
Return the number of elements in the FixedList.
Definition at line 516 of file FixedList.H.
Referenced by HashSet< Key, Hash >::operator=().
static constexpr unsigned max_size () inline static noexcept
The dimensioned size (template parameter N) of the FixedList.
Definition at line 521 of file FixedList.H.
void swap (FixedList< T, N > & list) inline
Swap lists by swapping the content of the individual list elements.
Definition at line 325 of file FixedListI.H.
bool operator== (const FixedList< T, N > & list) const
Equality operation on FixedLists of the same type.
Returns true when the FixedLists are element-wise equal (using FixedList::value_type::operator==). Takes linear time
Definition at line 104 of file FixedList.C.
bool operator!= (const FixedList< T, N > & list) const
The opposite of the equality operation. Takes linear time.
Definition at line 148 of file FixedList.C.
bool operator< (const FixedList< T, N > & list) const
Compare two FixedLists lexicographically. Takes linear time.
Definition at line 124 of file FixedList.C.
bool operator> (const FixedList< T, N > & list) const
Compare two FixedLists lexicographically. Takes linear time.
Definition at line 155 of file FixedList.C.
References Foam::operator==().
bool operator<= (const FixedList< T, N > & list) const
Return true if !(a > b). Takes linear time.
Definition at line 162 of file FixedList.C.
bool operator>= (const FixedList< T, N > & list) const
Return true if !(a < b). Takes linear time.
Definition at line 169 of file FixedList.C.
void writeEntry (const word & keyword, Ostream & os) const
Write the list as a dictionary entry with keyword.
Definition at line 45 of file FixedListIO.C.
Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
Using '0' suppresses line-breaks entirely.
Definition at line 61 of file FixedListIO.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, FixedList< T, N > & list) friend
Read from Istream, discarding contents of existing List.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/Lists/FixedList/FixedList.H
src/OpenFOAM/containers/Lists/FixedList/FixedList.C
src/OpenFOAM/containers/Lists/FixedList/FixedListI.H
src/OpenFOAM/containers/Lists/FixedList/FixedListIO.C