OpenFOAM: solidMixtureProperties Class Reference
solidMixtureProperties Class Reference
A mixture of solids.
Public Member Functions
solidMixtureProperties (const dictionary &)
Construct from dictionary.
solidMixtureProperties (const solidMixtureProperties &lm)
Construct copy.
virtual autoPtr
< solidMixtureProperties > clone () const
Construct and return a clone.
virtual ~solidMixtureProperties ()=default
Destructor.
const List< word > & components () const
Return the solidProperties names.
const PtrList< solidProperties > & properties () const
Return the solidProperties properties.
label size () const
Return the number of solids in the mixture.
scalar rho (const scalarField &Y) const
Calculate the mixture density [kg/m^3] as a function of.
scalar Cp (const scalarField &Y) const
Calculate the mixture heat capacity [J/(kg K)] as a function of.
Static Public Member Functions
static autoPtr
< solidMixtureProperties > New (const dictionary &)
Select construct from dictionary.
Detailed Description
A mixture of solids.
An example of a two component solid mixture:
    <parentDictionary>
    {
        C;
        ash
        {
            //... user defined properties for ash
        }
    }
Source files
solidMixtureProperties.H
solidMixtureProperties.C
See Also
Foam::solidProperties
Definition at line 65 of file solidMixtureProperties.H.
Constructor & Destructor Documentation
solidMixtureProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 25 of file solidMixtureProperties.C.
References forAll, i, dictionary::isDict(), solidProperties::New(), UList< T >::size(), dictionary::subDict(), and dictionary::toc().
solidMixtureProperties (const solidMixtureProperties & lm)
Construct copy.
Definition at line 56 of file solidMixtureProperties.C.
virtual ~solidMixtureProperties () virtual default
Destructor.
Member Function Documentation
virtual autoPtr<solidMixtureProperties> clone () const inline virtual
Construct and return a clone.
Definition at line 97 of file solidMixtureProperties.H.
Foam::autoPtr< Foam::solidMixtureProperties > New (const dictionary & thermophysicalProperties) static
Select construct from dictionary.
Definition at line 73 of file solidMixtureProperties.C.
const List<word>& components () const inline
Return the solidProperties names.
Definition at line 122 of file solidMixtureProperties.H.
References UList< T >::size().
const PtrList<solidProperties>& properties () const inline
Return the solidProperties properties.
Definition at line 130 of file solidMixtureProperties.H.
label size () const inline
Return the number of solids in the mixture.
Definition at line 138 of file solidMixtureProperties.H.
Foam::scalar rho (const scalarField & Y) const
Calculate the mixture density [kg/m^3] as a function of.
mass fractions
Definition at line 83 of file solidMixtureProperties.C.
References autoPtr< T >::New().
Foam::scalar Cp (const scalarField & Y) const
Calculate the mixture heat capacity [J/(kg K)] as a function of.
mass fractions
Definition at line 96 of file solidMixtureProperties.C.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidMixtureProperties/solidMixtureProperties.H
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidMixtureProperties/solidMixtureProperties.C