OpenFOAM: FIRECore Class Reference
FIRECore Class Reference
Core routines used when reading/writing AVL/FIRE files.
Public Types
enum selectionType { cellSelection = 2, faceSelection = 3 }
Selection Types.
enum shapeType {
fireLine = 1, fireTri = 2, fireQuad = 3, fireTet = 4,
fireHex = 5, firePyr = 6, firePrism = 8
}
Shape-Type for FIRE (FLMA) files.
enum fileExt3d { POLY_ASCII, POLY_BINARY, POLY_ASCII_Z, POLY_BINARY_Z }
Enumeration defining the file extensions for 3D types.
typedef int32_t fireInt_t
Integer type (binary format)
typedef double fireReal_t
Float type (binary format)
Static Public Member Functions
static fileName fireFileName (const fileName &baseName, const enum fileExt3d)
Resolve base file-name for the given file-type.
static label getFireLabel (ISstream &)
Get an integer (ascii or binary)
static point getFirePoint (ISstream &)
Get an point x/y/z (ascii or binary)
static std::string getFireString (ISstream &)
Extract a string (ascii or binary)
static void putFireLabel (OSstream &, const label)
Write an integer (ascii or binary)
static void putFireLabels (OSstream &, const labelUList &)
Write multiple integers (ascii or binary)
static void putFireLabels (OSstream &, const label count, const label start)
Write an on-the-fly list of integers (ascii or binary)
static void putFirePoint (OSstream &, const point &)
Write a point x/y/z (ascii or binary)
static void putFireString (OSstream &, const std::string &)
Write a string (ascii or binary)
Protected Member Functions
FIRECore ()=default
Construct null.
Static Protected Member Functions
static label readPoints (ISstream &, pointField &)
Read points.
Static Protected Attributes
static const Enum< fileExt3d > file3dExtensions
Detailed Description
Core routines used when reading/writing AVL/FIRE files.
Source files
FIRECore.H
FIRECore.C
Definition at line 56 of file FIRECore.H.
Member Typedef Documentation
typedef int32_t fireInt_t
Integer type (binary format)
Definition at line 100 of file FIRECore.H.
typedef double fireReal_t
Float type (binary format)
Definition at line 105 of file FIRECore.H.
Member Enumeration Documentation
enum selectionType
Selection Types.
Enumerator
cellSelection
faceSelection
Definition at line 65 of file FIRECore.H.
enum shapeType
Shape-Type for FIRE (FLMA) files.
Enumerator
fireLine
fireTri
fireQuad
fireTet
fireHex
firePyr
firePrism
Definition at line 74 of file FIRECore.H.
enum fileExt3d
Enumeration defining the file extensions for 3D types.
Enumerator
POLY_ASCII
POLY_BINARY
POLY_ASCII_Z
POLY_BINARY_Z
Definition at line 88 of file FIRECore.H.
Constructor & Destructor Documentation
FIRECore () protected default
Construct null.
Member Function Documentation
Foam::label readPoints (ISstream & is, pointField & points) static protected
Read points.
This is the first thing to do when reading FPMA,FPMB,FLMA files. Return the number of points read.
The file format is as follows:
* NUMBER_OF_VERTICES
* x0 y0 z0 x1 y1 z1 ... xN-1 yN-1 zN-1
*
Definition at line 41 of file FIRECore.C.
Referenced by FIREMeshReader::readPoints().
Foam::fileName fireFileName (const fileName & baseName, const enum fileExt3d ext) static
Resolve base file-name for the given file-type.
Definition at line 72 of file FIRECore.C.
Foam::label getFireLabel (ISstream & is) static
Get an integer (ascii or binary)
Definition at line 81 of file FIRECore.C.
References ext().
Foam::point getFirePoint (ISstream & is) static
Get an point x/y/z (ascii or binary)
Definition at line 102 of file FIRECore.C.
References Foam::readLabel().
std::string getFireString (ISstream & is) static
Extract a string (ascii or binary)
Definition at line 131 of file FIRECore.C.
void putFireLabel (OSstream & os, const label value) static
Write an integer (ascii or binary)
Definition at line 195 of file FIRECore.C.
void putFireLabels (OSstream & os, const labelUList & lst) static
Write multiple integers (ascii or binary)
Definition at line 218 of file FIRECore.C.
References value().
void putFireLabels (OSstream & os, const label count, const label start) static
Write an on-the-fly list of integers (ascii or binary)
Definition at line 257 of file FIRECore.C.
void putFirePoint (OSstream & os, const point & value) static
Write a point x/y/z (ascii or binary)
Definition at line 298 of file FIRECore.C.
void putFireString (OSstream & os, const std::string & value) static
Write a string (ascii or binary)
Definition at line 327 of file FIRECore.C.
Member Data Documentation
const Foam::Enum< Foam::fileFormats::FIRECore::fileExt3d > file3dExtensions static protected
Definition at line 112 of file FIRECore.H.
The documentation for this class was generated from the following files:
src/fileFormats/fire/FIRECore.H
src/fileFormats/fire/FIRECore.C