OpenFOAM: AMIInterpolation< SourcePatch, TargetPatch > Class Template Reference
AMIInterpolation< SourcePatch, TargetPatch > Class Template Reference
Interpolation class dealing with transfer of data between two primitive patches with an arbitrary mesh interface (AMI).
Public Types
enum interpolationMethod { imDirect, imMapNearest, imFaceAreaWeight, imPartialFaceAreaWeight }
Enumeration specifying interpolation method.
typedef SourcePatch sourcePatchType
typedef TargetPatch targetPatchType
Public Member Functions
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const interpolationMethod &method=imFaceAreaWeight, const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components.
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const word &methodName=interpolationMethodNames_[imFaceAreaWeight], const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components.
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const autoPtr< searchableSurface > &surf, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const interpolationMethod &method=imFaceAreaWeight, const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components, with projection surface.
AMIInterpolation (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const autoPtr< searchableSurface > &surf, const faceAreaIntersect::triangulationMode &triMode, const bool requireMatch=true, const word &methodName=interpolationMethodNames_[imFaceAreaWeight], const scalar lowWeightCorrection=-1, const bool reverseTarget=false)
Construct from components, with projection surface.
AMIInterpolation (const AMIInterpolation< SourcePatch, TargetPatch > &fineAMI, const labelList &sourceRestrictAddressing, const labelList &neighbourRestrictAddressing)
Construct from agglomeration of AMIInterpolation. Agglomeration.
~AMIInterpolation ()
Destructor.
label singlePatchProc () const
Set to -1, or the processor holding all faces (both sides) of the AMI.
scalar lowWeightCorrection () const
Threshold weight below which interpolation is deactivated.
bool applyLowWeightCorrection () const
Return true if employing a 'lowWeightCorrection'.
const List< scalar > & srcMagSf () const
Return const access to source patch face areas.
List< scalar > & srcMagSf ()
Return access to source patch face areas.
const labelListList & srcAddress () const
Return const access to source patch addressing.
labelListList & srcAddress ()
Return access to source patch addressing.
const scalarListList & srcWeights () const
Return const access to source patch weights.
scalarListList & srcWeights ()
Return access to source patch weights.
const scalarField & srcWeightsSum () const
Return const access to normalisation factor of source patch weights (i.e. the sum before normalisation)
scalarField & srcWeightsSum ()
Return access to normalisation factor of source patch weights (i.e. the sum before normalisation)
const mapDistribute & srcMap () const
Source map pointer - valid only if singlePatchProc = -1 This gets source data into a form to be consumed by tgtAddress, tgtWeights.
const List< scalar > & tgtMagSf () const
Return const access to target patch face areas.
List< scalar > & tgtMagSf ()
Return access to target patch face areas.
const labelListList & tgtAddress () const
Return const access to target patch addressing.
labelListList & tgtAddress ()
Return access to target patch addressing.
const scalarListList & tgtWeights () const
Return const access to target patch weights.
scalarListList & tgtWeights ()
Return access to target patch weights.
const scalarField & tgtWeightsSum () const
Return const access to normalisation factor of target patch weights (i.e. the sum before normalisation)
scalarField & tgtWeightsSum ()
Return access to normalisation factor of target patch weights (i.e. the sum before normalisation)
const mapDistribute & tgtMap () const
Target map pointer - valid only if singlePatchProc=-1. This gets target data into a form to be consumed by srcAddress, srcWeights.
void update (const SourcePatch &srcPatch, const TargetPatch &tgtPatch)
Update addressing and weights.
void append (const SourcePatch &srcPatch, const TargetPatch &tgtPatch)
Append additional addressing and weights.
void normaliseWeights (const bool conformal, const bool output)
Normalise the weights.
template<class Type , class CombineOp >
void interpolateToSource (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target to source with supplied op to combine existing value with remote value and weight.
template<class Type , class CombineOp >
void interpolateToTarget (const UList< Type > &fld, const CombineOp &cop, List< Type > &result, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source to target with supplied op to combine existing value with remote value and weight.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target to source with supplied op.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target tmp field to source with supplied op.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source to target with supplied op.
template<class Type , class CombineOp >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source tmp field to target with supplied op.
template<class Type >
tmp< Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target to source.
template<class Type >
tmp< Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from target tmp field.
template<class Type >
tmp< Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source to target.
template<class Type >
tmp< Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues=UList< Type >::null()) const
Interpolate from source tmp field.
label srcPointFace (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const vector &n, const label tgtFacei, point &tgtPoint) const
Return source patch face index of point on target patch face.
label tgtPointFace (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const vector &n, const label srcFacei, point &srcPoint) const
Return target patch face index of point on source patch face.
void writeFaceConnectivity (const SourcePatch &srcPatch, const TargetPatch &tgtPatch, const labelListList &srcAddress) const
Write face connectivity as OBJ file.
template<class Patch >
Foam::tmp< Foam::scalarField > patchMagSf (const Patch &patch, const faceAreaIntersect::triangulationMode triMode)
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type , class CombineOp >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const CombineOp &cop, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToSource (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const Field< Type > &fld, const UList< Type > &defaultValues) const
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolateToTarget (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues) const
Static Public Member Functions
template<class Patch >
static tmp< scalarField > patchMagSf (const Patch &patch, const faceAreaIntersect::triangulationMode triMode)
Calculate the patch face magnitudes for the given tri-mode.
Static Public Attributes
static const Enum
< interpolationMethod > interpolationMethodNames_
static bool cacheIntersections_
Detailed Description
template<class SourcePatch, class TargetPatch>
class Foam::AMIInterpolation< SourcePatch, TargetPatch >
Interpolation class dealing with transfer of data between two primitive patches with an arbitrary mesh interface (AMI).
Based on the algorithm given in:
Conservative interpolation between volume meshes by local Galerkin projection, Farrell PE and Maddison JR, 2011, Comput. Methods Appl. Mech Engrg, Volume 200, Issues 1-4, pp 89-100
Interpolation requires that the two patches should have opposite orientations (opposite normals). The 'reverseTarget' flag can be used to reverse the orientation of the target patch.
Source files
AMIInterpolation.H
AMIInterpolation.C
AMIInterpolationName.C
AMIInterpolationParallelOps.C
Definition at line 77 of file AMIInterpolation.H.
Member Typedef Documentation
typedef SourcePatch sourcePatchType
Definition at line 408 of file AMIInterpolation.H.
typedef TargetPatch targetPatchType
Definition at line 411 of file AMIInterpolation.H.
Member Enumeration Documentation
enum interpolationMethod
Enumeration specifying interpolation method.
Enumerator
imDirect
imMapNearest
imFaceAreaWeight
imPartialFaceAreaWeight
Definition at line 88 of file AMIInterpolation.H.
Constructor & Destructor Documentation
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const interpolationMethod & method = imFaceAreaWeight, const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components.
Definition at line 593 of file AMIInterpolation.C.
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const word & methodName = interpolationMethodNames_[imFaceAreaWeight], const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components.
Definition at line 626 of file AMIInterpolation.C.
References update().
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const autoPtr< searchableSurface > & surf, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const interpolationMethod & method = imFaceAreaWeight, const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components, with projection surface.
Definition at line 659 of file AMIInterpolation.C.
References update().
AMIInterpolation (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const autoPtr< searchableSurface > & surf, const faceAreaIntersect::triangulationMode & triMode, const bool requireMatch = true, const word & methodName = interpolationMethodNames_[imFaceAreaWeight], const scalar lowWeightCorrection = -1, const bool reverseTarget = false)
Construct from components, with projection surface.
Definition at line 693 of file AMIInterpolation.C.
AMIInterpolation (const AMIInterpolation< SourcePatch, TargetPatch > & fineAMI, const labelList & sourceRestrictAddressing, const labelList & neighbourRestrictAddressing)
Construct from agglomeration of AMIInterpolation. Agglomeration.
passed in as new coarse size and addressing from fine from coarse
Definition at line 727 of file AMIInterpolation.C.
~AMIInterpolation ()
Destructor.
Definition at line 833 of file AMIInterpolation.C.
Member Function Documentation
static tmp<scalarField> patchMagSf (const Patch & patch, const faceAreaIntersect::triangulationMode triMode) static
Calculate the patch face magnitudes for the given tri-mode.
Foam::label singlePatchProc () const inline
Set to -1, or the processor holding all faces (both sides) of the AMI.
Definition at line 24 of file AMIInterpolationI.H.
Foam::scalar lowWeightCorrection () const inline
Threshold weight below which interpolation is deactivated.
Definition at line 32 of file AMIInterpolationI.H.
bool applyLowWeightCorrection () const inline
Return true if employing a 'lowWeightCorrection'.
Definition at line 41 of file AMIInterpolationI.H.
const Foam::List< Foam::scalar > & srcMagSf () const inline
Return const access to source patch face areas.
Definition at line 49 of file AMIInterpolationI.H.
Foam::List< Foam::scalar > & srcMagSf () inline
Return access to source patch face areas.
Definition at line 57 of file AMIInterpolationI.H.
const Foam::labelListList & srcAddress () const inline
Return const access to source patch addressing.
Definition at line 65 of file AMIInterpolationI.H.
Foam::labelListList & srcAddress () inline
Return access to source patch addressing.
Definition at line 73 of file AMIInterpolationI.H.
const Foam::scalarListList & srcWeights () const inline
Return const access to source patch weights.
Definition at line 81 of file AMIInterpolationI.H.
Foam::scalarListList & srcWeights () inline
Return access to source patch weights.
Definition at line 89 of file AMIInterpolationI.H.
const Foam::scalarField & srcWeightsSum () const inline
Return const access to normalisation factor of source patch weights (i.e. the sum before normalisation)
Definition at line 97 of file AMIInterpolationI.H.
Foam::scalarField & srcWeightsSum () inline
Return access to normalisation factor of source patch weights (i.e. the sum before normalisation)
Definition at line 105 of file AMIInterpolationI.H.
const Foam::mapDistribute & srcMap () const inline
Source map pointer - valid only if singlePatchProc = -1 This gets source data into a form to be consumed by tgtAddress, tgtWeights.
Definition at line 113 of file AMIInterpolationI.H.
const Foam::List< Foam::scalar > & tgtMagSf () const inline
Return const access to target patch face areas.
Definition at line 121 of file AMIInterpolationI.H.
Foam::List< Foam::scalar > & tgtMagSf () inline
Return access to target patch face areas.
Definition at line 129 of file AMIInterpolationI.H.
const Foam::labelListList & tgtAddress () const inline
Return const access to target patch addressing.
Definition at line 137 of file AMIInterpolationI.H.
Foam::labelListList & tgtAddress () inline
Return access to target patch addressing.
Definition at line 145 of file AMIInterpolationI.H.
const Foam::scalarListList & tgtWeights () const inline
Return const access to target patch weights.
Definition at line 153 of file AMIInterpolationI.H.
Foam::scalarListList & tgtWeights () inline
Return access to target patch weights.
Definition at line 161 of file AMIInterpolationI.H.
const Foam::scalarField & tgtWeightsSum () const inline
Return const access to normalisation factor of target patch weights (i.e. the sum before normalisation)
Definition at line 169 of file AMIInterpolationI.H.
Foam::scalarField & tgtWeightsSum () inline
Return access to normalisation factor of target patch weights (i.e. the sum before normalisation)
Definition at line 177 of file AMIInterpolationI.H.
const Foam::mapDistribute & tgtMap () const inline
Target map pointer - valid only if singlePatchProc=-1. This gets target data into a form to be consumed by srcAddress, srcWeights.
Definition at line 185 of file AMIInterpolationI.H.
void update (const SourcePatch & srcPatch, const TargetPatch & tgtPatch)
Update addressing and weights.
Definition at line 841 of file AMIInterpolation.C.
void append (const SourcePatch & srcPatch, const TargetPatch & tgtPatch)
Append additional addressing and weights.
Definition at line 1054 of file AMIInterpolation.C.
void normaliseWeights (const bool conformal, const bool output)
Normalise the weights.
Definition at line 1246 of file AMIInterpolation.C.
void interpolateToSource (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>::null()) const
Interpolate from target to source with supplied op to combine existing value with remote value and weight.
Definition at line 1367 of file AMIInterpolation.C.
Referenced by mappedPatchBase::distribute(), cyclicAMIPolyPatch::interpolate(), and regionModel::mapRegionPatchField().
void interpolateToTarget (const UList< Type > & fld, const CombineOp & cop, List< Type > & result, const UList< Type > & defaultValues = UList<Type>::null()) const
Interpolate from source to target with supplied op to combine existing value with remote value and weight.
Definition at line 1280 of file AMIInterpolation.C.
tmp<Field<Type> > interpolateToSource (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target to source with supplied op.
tmp<Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target tmp field to source with supplied op.
tmp<Field<Type> > interpolateToTarget (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source to target with supplied op.
tmp<Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source tmp field to target with supplied op.
tmp<Field<Type> > interpolateToSource (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target to source.
tmp<Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from target tmp field.
tmp<Field<Type> > interpolateToTarget (const Field< Type > & fld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source to target.
tmp<Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues = UList< Type >::null()) const
Interpolate from source tmp field.
Foam::label srcPointFace (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const vector & n, const label tgtFacei, point & tgtPoint) const
Return source patch face index of point on target patch face.
Definition at line 1595 of file AMIInterpolation.C.
Foam::label tgtPointFace (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const vector & n, const label srcFacei, point & srcPoint) const
Return target patch face index of point on source patch face.
Definition at line 1643 of file AMIInterpolation.C.
void writeFaceConnectivity (const SourcePatch & srcPatch, const TargetPatch & tgtPatch, const labelListList & srcAddress) const
Write face connectivity as OBJ file.
Definition at line 1691 of file AMIInterpolation.C.
Foam::tmp<Foam::scalarField> patchMagSf (const Patch & patch, const faceAreaIntersect::triangulationMode triMode)
Definition at line 53 of file AMIInterpolation.C.
References forAll, i, tmp< T >::ref(), and Foam::Zero.
Foam::tmp<Foam::Field<Type> > interpolateToSource (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1455 of file AMIInterpolation.C.
Foam::tmp<Foam::Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1486 of file AMIInterpolation.C.
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const Field< Type > & fld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1500 of file AMIInterpolation.C.
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const CombineOp & cop, const UList< Type > & defaultValues) const
Definition at line 1531 of file AMIInterpolation.C.
Foam::tmp<Foam::Field<Type> > interpolateToSource (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 1545 of file AMIInterpolation.C.
Foam::tmp<Foam::Field<Type> > interpolateToSource (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues) const
Definition at line 1558 of file AMIInterpolation.C.
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const Field< Type > & fld, const UList< Type > & defaultValues) const
Definition at line 1571 of file AMIInterpolation.C.
Foam::tmp<Foam::Field<Type> > interpolateToTarget (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues) const
Definition at line 1584 of file AMIInterpolation.C.
Member Data Documentation
const Foam::Enum< typename Foam::AMIInterpolation< SourcePatch, TargetPatch >::interpolationMethod > interpolationMethodNames_ static
Definition at line 96 of file AMIInterpolation.H.
bool cacheIntersections_ static
Initial value:
=
    false
Definition at line 98 of file AMIInterpolation.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolation.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolation.C
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolationI.H
src/meshTools/AMIInterpolation/AMIInterpolation/AMIInterpolationParallelOps.C