OpenFOAM: OneResistanceHeatTransferPhaseSystem< BasePhaseSystem > Class Template Reference
OneResistanceHeatTransferPhaseSystem< BasePhaseSystem > Class Template Reference
Class which models interfacial heat transfer between a number of phases. A single heat transfer model is used for each interface.
Public Member Functions
OneResistanceHeatTransferPhaseSystem (const fvMesh &)
Construct from fvMesh.
virtual ~OneResistanceHeatTransferPhaseSystem ()
Destructor.
virtual autoPtr
< phaseSystem::heatTransferTable > heatTransfer () const
Return the heat transfer matrices.
virtual bool read ()
Read base phaseProperties dictionary.
Protected Types
typedef HashTable< autoPtr
< BlendedInterfacialModel
< heatTransferModel >
>, phasePairKey,
phasePairKey::hash > heatTransferModelTable
Protected Attributes
heatTransferModelTable heatTransferModels_
Heat transfer models.
Detailed Description
template<class BasePhaseSystem>
class Foam::OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >
Class which models interfacial heat transfer between a number of phases. A single heat transfer model is used for each interface.
See Also
TwoResistanceHeatTransferPhaseSystem
Source files
OneResistanceHeatTransferPhaseSystem.H
OneResistanceHeatTransferPhaseSystem.C
Definition at line 55 of file OneResistanceHeatTransferPhaseSystem.H.
Member Typedef Documentation
typedef HashTable< autoPtr<BlendedInterfacialModel<heatTransferModel> >, phasePairKey, phasePairKey::hash > heatTransferModelTable protected
Definition at line 68 of file OneResistanceHeatTransferPhaseSystem.H.
Constructor & Destructor Documentation
OneResistanceHeatTransferPhaseSystem (const fvMesh & mesh)
Construct from fvMesh.
Definition at line 29 of file OneResistanceHeatTransferPhaseSystem.C.
References OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::heatTransferModels_.
~OneResistanceHeatTransferPhaseSystem () virtual
Destructor.
Definition at line 48 of file OneResistanceHeatTransferPhaseSystem.C.
Member Function Documentation
Foam::autoPtr< Foam::phaseSystem::heatTransferTable > heatTransfer () const virtual
Return the heat transfer matrices.
Definition at line 57 of file OneResistanceHeatTransferPhaseSystem.C.
References basicThermo::Cpv(), Foam::dimEnergy, Foam::dimTime, dmdt12, dmdt21, forAll, forAllConstIter, he, basicThermo::he(), he2, iter, phaseModel::K(), K1, K2, phaseModel::name(), Foam::negPart(), phasePairKey::ordered(), phase1, phasePair::phase1(), phase2, phasePair::phase2(), phasei, Foam::posPart(), HashPtrTable< T, Key, Hash >::set(), Foam::fvm::Sp(), basicThermo::T(), and phaseModel::thermo().
bool read () virtual
Read base phaseProperties dictionary.
Definition at line 147 of file OneResistanceHeatTransferPhaseSystem.C.
Member Data Documentation
heatTransferModelTable heatTransferModels_ protected
Heat transfer models.
Definition at line 78 of file OneResistanceHeatTransferPhaseSystem.H.
Referenced by OneResistanceHeatTransferPhaseSystem< BasePhaseSystem >::OneResistanceHeatTransferPhaseSystem().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/PhaseSystems/OneResistanceHeatTransferPhaseSystem/OneResistanceHeatTransferPhaseSystem.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/PhaseSystems/OneResistanceHeatTransferPhaseSystem/OneResistanceHeatTransferPhaseSystem.C