OpenFOAM: MappedFile< Type > Class Template Reference
MappedFile< Type > Class Template Reference
Public Member Functions
TypeName ("mappedFile")
MappedFile (const polyPatch &pp, const word &type, const word &entryName, const dictionary &dict, const bool faceValues=true)
Construct from entry name and dictionary.
MappedFile (const polyPatch &pp, const word &entryName, const dictionary &dict, const word &fieldTableName, const bool faceValues)
Construct from entry name and dictionary.
MappedFile (const MappedFile< Type > &ut)
Copy constructor.
MappedFile (const MappedFile< Type > &ut, const polyPatch &pp)
Copy constructor setting patch.
virtual tmp< PatchFunction1
< Type > > clone () const
Construct and return a clone.
virtual tmp< PatchFunction1
< Type > > clone (const polyPatch &pp) const
Construct and return a clone setting patch.
virtual ~MappedFile ()=default
Destructor.
virtual tmp< Field< Type > > value (const scalar) const
Return MappedFile value.
virtual bool constant () const
Is value constant (i.e. independent of x)
virtual bool uniform () const
Is value uniform (i.e. independent of coordinate)
virtual tmp< Field< Type > > integrate (const scalar x1, const scalar x2) const
Integrate between two values.
virtual void autoMap (const FieldMapper &mapper)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const PatchFunction1< Type > &pf1, const labelList &addr)
Reverse map the given PatchFunction1 onto this PatchFunction1.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from PatchFunction1< Type >
declareRunTimeSelectionTable (autoPtr, PatchFunction1, dictionary,(const polyPatch &pp, const word &type, const word &entryName, const dictionary &dict, const bool faceValues),(pp, type, entryName, dict, faceValues))
Runtime type information.
PatchFunction1 (const polyPatch &pp, const word &entryName, const bool faceValues=true)
Construct from polyPatch and entry name.
PatchFunction1 (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
Construct from polyPatch, dictionary and entry name.
PatchFunction1 (const PatchFunction1< Type > &pf1)
Copy constructor.
PatchFunction1 (const PatchFunction1< Type > &pf1, const polyPatch &pp)
Copy constructor setting patch.
virtual ~PatchFunction1 ()=default
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual tmp< pointField > localPosition (const pointField &globalPos) const
Helper: optionally convert coordinates to local coordinates.
virtual tmp< Field< Type > > transform (const Field< Type > &fld) const
Apply optional transformation.
virtual tmp< Field< Type > > transform (const tmp< Field< Type >> &tfld) const
Apply optional transformation.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Public Types inherited from PatchFunction1< Type >
typedef Field< Type > returnType
Static Public Member Functions inherited from PatchFunction1< Type >
static autoPtr< PatchFunction1
< Type > > New (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
Selector.
Protected Attributes inherited from PatchFunction1< Type >
const word name_
Name of entry.
const polyPatch & patch_
Reference to the patch.
const bool faceValues_
Whether to generate face or point values on patch.
coordinateScaling< Type > coordSys_
Optional local co-ordinate system and scaling.
Detailed Description
template<class Type>
class Foam::PatchFunction1Types::MappedFile< Type >
Source files
MappedFile.H
MappedFile.C
Definition at line 50 of file MappedFile.H.
Constructor & Destructor Documentation
MappedFile (const polyPatch & pp, const word & type, const word & entryName, const dictionary & dict, const bool faceValues = true)
Construct from entry name and dictionary.
Definition at line 29 of file MappedFile.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), and Function1< Type >::New().
MappedFile (const polyPatch & pp, const word & entryName, const dictionary & dict, const word & fieldTableName, const bool faceValues)
Construct from entry name and dictionary.
Definition at line 83 of file MappedFile.C.
MappedFile (const MappedFile< Type > & ut) explicit
Copy constructor.
Definition at line 135 of file MappedFile.C.
MappedFile (const MappedFile< Type > & ut, const polyPatch & pp) explicit
Copy constructor setting patch.
Definition at line 160 of file MappedFile.C.
virtual ~MappedFile () virtual default
Destructor.
Member Function Documentation
TypeName ("mappedFile")
virtual tmp<PatchFunction1<Type> > clone () const inline virtual
Construct and return a clone.
Implements PatchFunction1< Type >.
Definition at line 191 of file MappedFile.H.
References PatchFunction1< Type >::uniform().
virtual tmp<PatchFunction1<Type> > clone (const polyPatch & pp) const inline virtual
Construct and return a clone setting patch.
Implements PatchFunction1< Type >.
Definition at line 202 of file MappedFile.H.
Foam::tmp< Foam::Field< Type > > value (const scalar x) const virtual
Return MappedFile value.
Reimplemented from PatchFunction1< Type >.
Definition at line 468 of file MappedFile.C.
virtual bool constant () const inline virtual
Is value constant (i.e. independent of x)
Implements PatchFunction1< Type >.
Definition at line 229 of file MappedFile.H.
virtual bool uniform () const inline virtual
Is value uniform (i.e. independent of coordinate)
Implements PatchFunction1< Type >.
Definition at line 237 of file MappedFile.H.
Foam::tmp< Foam::Field< Type > > integrate (const scalar x1, const scalar x2) const virtual
Integrate between two values.
Reimplemented from PatchFunction1< Type >.
Definition at line 578 of file MappedFile.C.
void autoMap (const FieldMapper & mapper) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented from PatchFunction1< Type >.
Definition at line 188 of file MappedFile.C.
void rmap (const PatchFunction1< Type > & pf1, const labelList & addr) virtual
Reverse map the given PatchFunction1 onto this PatchFunction1.
Reimplemented from PatchFunction1< Type >.
Definition at line 208 of file MappedFile.C.
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented from PatchFunction1< Type >.
Definition at line 590 of file MappedFile.C.
The documentation for this class was generated from the following files:
src/meshTools/PatchFunction1/MappedFile/MappedFile.H
src/meshTools/PatchFunction1/MappedFile/MappedFile.C