OpenFOAM: PrimitivePatch< Face, FaceList, PointField, PointType > Class Template Reference
PrimitivePatch< Face, FaceList, PointField, PointType > Class Template Reference
A list of faces which address into the list of points.
Public Types
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Public Member Functions
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &&faces, const Field< PointType > &points)
Construct from components, transferring faces.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< PointType > & faceNormals () const
Return face unit normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Detailed Description
template<class Face, template< class > class FaceList, class PointField, class PointType = point>
class Foam::PrimitivePatch< Face, FaceList, PointField, PointType >
A list of faces which address into the list of points.
The class is templated on the face type (e.g. triangle, polygon etc.) and on the list type of faces and points so that it can refer to existing lists using UList and const pointField& or hold the storage using List and pointField.
Source files
PrimitivePatch.H
PrimitivePatchAddressing.C
PrimitivePatchBdryPoints.C
PrimitivePatch.C
PrimitivePatchCheck.C
PrimitivePatchClear.C
PrimitivePatchEdgeLoops.C
PrimitivePatchLocalPointOrder.C
PrimitivePatchMeshData.C
PrimitivePatchMeshEdges.C
PrimitivePatchName.C
PrimitivePatchPointAddressing.C
PrimitivePatchProjectPoints.C
Definition at line 86 of file PrimitivePatch.H.
Member Typedef Documentation
typedef Face FaceType
Definition at line 96 of file PrimitivePatch.H.
typedef FaceList<Face> FaceListType
Definition at line 97 of file PrimitivePatch.H.
typedef PointField PointFieldType
Definition at line 98 of file PrimitivePatch.H.
Member Enumeration Documentation
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
Enumerator
MANIFOLD
OPEN
ILLEGAL
Definition at line 106 of file PrimitivePatch.H.
Constructor & Destructor Documentation
PrimitivePatch (const FaceList< Face > & faces, const Field< PointType > & points)
Construct from components.
Definition at line 34 of file PrimitivePatch.C.
PrimitivePatch (FaceList< Face > && faces, const Field< PointType > & points)
Construct from components, transferring faces.
Definition at line 72 of file PrimitivePatch.C.
PrimitivePatch (FaceList< Face > & faces, Field< PointType > & points, const bool reuse)
Construct from components, reuse storage.
Definition at line 110 of file PrimitivePatch.C.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > & pp)
Construct as copy.
Definition at line 149 of file PrimitivePatch.C.
~PrimitivePatch () virtual
Destructor.
Definition at line 188 of file PrimitivePatch.C.
Member Function Documentation
void clearOut ()
Definition at line 123 of file PrimitivePatchClear.C.
void clearGeom ()
Definition at line 36 of file PrimitivePatchClear.C.
References Foam::expressions::patchExpr::debug, Foam::deleteDemandDrivenData(), Foam::endl(), and InfoInFunction.
Referenced by polyPatch::clearGeom().
void clearTopology ()
Definition at line 61 of file PrimitivePatchClear.C.
References Foam::expressions::patchExpr::debug, Foam::deleteDemandDrivenData(), Foam::endl(), and InfoInFunction.
void clearPatchMeshAddr ()
Definition at line 101 of file PrimitivePatchClear.C.
References Foam::expressions::patchExpr::debug, Foam::deleteDemandDrivenData(), Foam::endl(), and InfoInFunction.
void swap (PrimitivePatch< Face, FaceList, PointField, PointType > &) delete
Suppress direct swapping, since storage containers may be const.
const Field<PointType>& points () const inline
Return reference to global points.
Definition at line 386 of file PrimitivePatch.H.
Referenced by PatchTools::calcBounds(), PatchTools::checkOrientation(), triSurfaceTools::classify(), distributedTriSurfaceMesh::distribute(), Foam::drawHitProblem(), PatchTools::gatherAndMerge(), distributedTriSurfaceMesh::getNormal(), oldCyclicPolyPatch::order(), distributedTriSurfaceMesh::overlappingSurface(), and triSurfacePointGeoMesh::size().
label nPoints () const inline
Return number of points supporting patch faces.
Definition at line 399 of file PrimitivePatch.H.
Referenced by ConstantField< Type >::ConstantField(), snappySnapDriver::detectNearSurfaces(), snappySnapDriver::getFacePoints(), PatchTools::matchPoints(), fieldSmoother::minSmoothField(), PatchFunction1< Type >::New(), PatchTools::pointNormals(), parseDriver::size(), PatchTools::subsetMap(), and Foam::writeZone().
label nEdges () const inline
Return number of edges in patch.
Definition at line 407 of file PrimitivePatch.H.
Referenced by PatchTools::checkOrientation(), PatchTools::edgeNormals(), PatchTools::matchEdges(), regionSplit2D::regionSplit2D(), and faMesh::updateMesh().
const Foam::edgeList & edges () const
Return list of edges, address into LOCAL point list.
Definition at line 231 of file PrimitivePatch.C.
Referenced by PatchTools::checkOrientation(), PatchTools::edgeOwner(), triSurfaceTools::getVertexTriangles(), PatchTools::matchEdges(), triSurfaceTools::minEdge(), fieldSmoother::minSmoothField(), PatchTools::sortedEdgeFaces(), and PatchTools::sortedPointEdges().
Foam::label nInternalEdges () const
Number of internal edges.
Definition at line 251 of file PrimitivePatch.C.
Referenced by faMesh::updateMesh().
bool isInternalEdge (const label edgei) const inline
Is internal edge?
Definition at line 425 of file PrimitivePatch.H.
const Foam::labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
Definition at line 271 of file PrimitivePatch.C.
const Foam::labelListList & faceFaces () const
Return face-face addressing.
Definition at line 291 of file PrimitivePatch.C.
const Foam::labelListList & edgeFaces () const
Return edge-face addressing.
Definition at line 311 of file PrimitivePatch.C.
Referenced by PatchTools::checkOrientation(), PatchTools::edgeNormals(), PatchTools::edgeOwner(), triSurfaceTools::getVertexTriangles(), PatchTools::markZone(), surfaceLocation::normal(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), and faMesh::updateMesh().
const Foam::labelListList & faceEdges () const
Return face-edge addressing.
Definition at line 331 of file PrimitivePatch.C.
Referenced by enrichedPatch::calcEnrichedFaces(), PatchTools::checkOrientation(), triSurfaceTools::classify(), PatchTools::markZone(), regionSplit2D::regionSplit2D(), and PatchTools::sortedPointEdges().
const Foam::labelListList & pointEdges () const
Return point-edge addressing.
Definition at line 351 of file PrimitivePatch.C.
Referenced by PatchTools::sortedPointEdges().
const Foam::labelListList & pointFaces () const
Return point-face addressing.
Definition at line 371 of file PrimitivePatch.C.
Referenced by triSurfaceTools::getVertexTriangles(), oldCyclicPolyPatch::order(), and PatchTools::pointNormals().
const Foam::List< Face > & localFaces () const
Return patch faces addressing into local point list.
Definition at line 391 of file PrimitivePatch.C.
Referenced by mappedPatchBase::calcAMI(), enrichedPatch::calcEnrichedFaces(), PatchTools::checkOrientation(), triSurfaceTools::classify(), PatchTools::edgeOwner(), geometryPatches::gatherPatchPieces(), oldCyclicPolyPatch::order(), PatchTools::pointNormals(), snappySnapDriver::repatchToSurface(), PatchTools::sortedEdgeFaces(), PatchTools::subsetMap(), and Foam::writeZone().
const Foam::labelList & meshPoints () const
Return labelList of mesh points in patch.
They are constructed by walking through the faces in incremental order and not sorted anymore.
Definition at line 411 of file PrimitivePatch.C.
Referenced by snappySnapDriver::detectNearSurfaces(), PatchTools::matchEdges(), PatchTools::matchPoints(), fieldSmoother::minSmoothField(), facePointPatch::name(), PatchTools::pointNormals(), pointConstraints::syncUntransformedData(), and medialAxisMeshMover::~medialAxisMeshMover().
const Foam::Map< Foam::label > & meshPointMap () const
Mesh point map.
Given the global point index find its location in the patch
Definition at line 431 of file PrimitivePatch.C.
Referenced by snappySnapDriver::getFacePoints(), PatchTools::matchPoints(), and PatchTools::pointNormals().
const Foam::Field< PointType > & localPoints () const
Return pointField of points in patch.
Definition at line 451 of file PrimitivePatch.C.
Referenced by mappedPatchBase::calcAMI(), enrichedPatch::calcEnrichedFaces(), PatchTools::checkOrientation(), snappySnapDriver::detectNearSurfaces(), geometryPatches::gatherPatchPieces(), triSurfaceTools::minEdge(), PatchTools::sortedEdgeFaces(), and Foam::writeZone().
const Foam::labelList & localPointOrder () const
Return orders the local points for most efficient search.
Definition at line 471 of file PrimitivePatch.C.
Foam::label whichPoint (const label gp) const
Given a global point index, return the local point index.
If the point is not found, return -1
Definition at line 492 of file PrimitivePatch.C.
Foam::label whichEdge (const edge & e) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
Definition at line 170 of file PrimitivePatchMeshEdges.C.
References forAll, nPoints, and edge::start().
Foam::labelList meshEdges (const edgeList & allEdges, const labelListList & cellEdges, const labelList & faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
Definition at line 36 of file PrimitivePatchMeshEdges.C.
References Foam::expressions::patchExpr::debug, end(), Foam::endl(), forAll, found, Foam::Info, UList< T >::size(), and Foam::start.
Referenced by medialAxisMeshMover::~medialAxisMeshMover().
Foam::labelList meshEdges (const edgeList & allEdges, const labelListList & pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
Definition at line 113 of file PrimitivePatchMeshEdges.C.
References Foam::expressions::patchExpr::debug, end(), Foam::endl(), forAll, i, Foam::Info, and UList< T >::size().
const Foam::Field< PointType > & faceCentres () const
Return face centres for patch.
Definition at line 510 of file PrimitivePatch.C.
Referenced by patchEdgeFaceInfo::equal().
const Foam::Field< PointType > & faceAreas () const
Return face area vectors for patch.
Definition at line 530 of file PrimitivePatch.C.
const Foam::Field< Foam::scalar > & magFaceAreas () const
Return face area magnitudes for patch.
Definition at line 550 of file PrimitivePatch.C.
const Foam::Field< PointType > & faceNormals () const
Return face unit normals for patch.
Definition at line 570 of file PrimitivePatch.C.
Referenced by PatchTools::checkOrientation(), PatchTools::edgeNormals(), surfaceLocation::normal(), and PatchTools::pointNormals().
const Foam::Field< PointType > & pointNormals () const
Return point normals for patch.
Definition at line 590 of file PrimitivePatch.C.
bool hasFaceAreas () const inline
Definition at line 555 of file PrimitivePatch.H.
bool hasFaceCentres () const inline
Definition at line 556 of file PrimitivePatch.H.
bool hasFaceNormals () const inline
Definition at line 557 of file PrimitivePatch.H.
bool hasPointNormals () const inline
Definition at line 558 of file PrimitivePatch.H.
List<objectHit> projectPoints (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm = intersection::FULL_RAY, const intersection::direction = intersection::VECTOR) const
Project vertices of patch onto another patch.
List<objectHit> projectFaceCentres (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm = intersection::FULL_RAY, const intersection::direction = intersection::VECTOR) const
Project vertices of patch onto another patch.
const Foam::labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
Edge loops are given as ordered lists of vertices in local addressing
Definition at line 162 of file PrimitivePatchEdgeLoops.C.
Foam::PrimitivePatch< Face, FaceList, PointField, PointType >::surfaceTopo surfaceType () const
Calculate surface type formed by patch.
Types:
all edges have two neighbours (manifold)
some edges have more than two neighbours (illegal)
other (open)
Definition at line 116 of file PrimitivePatchCheck.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), forAll, Foam::Info, InfoInFunction, and UList< T >::size().
bool checkTopology (const bool report = false, labelHashSet * setPtr = nullptr) const
Check surface formed by patch for manifoldness (see above).
Return true if any incorrect edges are found. Insert vertices of incorrect edges into set.
Definition at line 164 of file PrimitivePatchCheck.C.
References Foam::expressions::patchExpr::debug, edge::end(), Foam::endl(), forAll, Foam::Info, InfoInFunction, HashSet< Key, Hash >::insert(), UList< T >::size(), and edge::start().
bool checkPointManifold (const bool report = false, labelHashSet * setPtr = nullptr) const
Checks primitivePatch for faces sharing point but not edge.
This denotes a surface that is pinched at a single point (test for pinched at single edge is already in PrimitivePatch) Returns true if this situation found and puts conflicting (mesh)point in set. Based on all the checking routines in primitiveMesh.
Definition at line 224 of file PrimitivePatchCheck.C.
References Foam::endl(), forAll, i, Foam::Info, HashSet< Key, Hash >::insert(), Foam::constant::atomic::mp, Foam::nl, and UList< T >::size().
void movePoints (const Field< PointType > &) virtual
Correct patch after moving points.
Definition at line 206 of file PrimitivePatch.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), and Foam::Pout.
Referenced by polyPatch::updateMesh().
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > & pp)
Assignment.
Definition at line 613 of file PrimitivePatch.C.
Foam::List<Foam::objectHit> projectPoints (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Definition at line 44 of file PrimitivePatchProjectPoints.C.
References Foam::abort(), Foam::fac::average(), Foam::expressions::patchExpr::debug, PointHit< Point >::distance(), PointHit< Point >::eligibleMiss(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PointHit< Point >::hit(), Foam::Info, Foam::mag(), Foam::magSqr(), PointHit< Point >::missPoint(), Foam::nl, nPoints, points, and UList< T >::size().
Foam::List<Foam::objectHit> projectFaceCentres (const ToPatch & targetPatch, const Field< PointType > & projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Definition at line 287 of file PrimitivePatchProjectPoints.C.
References Foam::abort(), Foam::bandCompression(), Foam::expressions::patchExpr::debug, PointHit< Point >::distance(), PointHit< Point >::eligibleMiss(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, PointHit< Point >::hit(), Foam::Info, Foam::mag(), Foam::magSqr(), PointHit< Point >::missPoint(), Foam::nl, points, and UList< T >::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatch.H
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatch.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchAddressing.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchBdryPoints.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchCheck.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchClear.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchEdgeLoops.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchLocalPointOrder.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchMeshData.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchMeshEdges.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchPointAddressing.C
src/OpenFOAM/meshes/primitiveMesh/PrimitivePatch/PrimitivePatchProjectPoints.C