OpenFOAM: meshSearch Class Reference
meshSearch Class Reference
Various (local, not parallel) searches on polyMesh; uses (demand driven) octree to search.
Public Member Functions
ClassName ("meshSearch")
meshSearch (const polyMesh &mesh, const polyMesh::cellDecomposition=polyMesh::CELL_TETS)
Construct from components. Constructs bb slightly bigger than.
meshSearch (const polyMesh &mesh, const treeBoundBox &bb, const polyMesh::cellDecomposition=polyMesh::CELL_TETS)
Construct with a custom bounding box. Any mesh element outside.
~meshSearch ()
Destructor.
const polyMesh & mesh () const
polyMesh::cellDecomposition decompMode () const
const indexedOctree
< treeDataFace > & boundaryTree () const
Get (demand driven) reference to octree holding all.
const indexedOctree
< treeDataCell > & cellTree () const
Get (demand driven) reference to octree holding all cells.
label findNearestCell (const point &location, const label seedCelli=-1, const bool useTreeSearch=true) const
Find nearest cell in terms of cell centre.
label findNearestFace (const point &location, const label seedFacei=-1, const bool useTreeSearch=true) const
label findCell (const point &location, const label seedCelli=-1, const bool useTreeSearch=true) const
Find cell containing location.
label findNearestBoundaryFace (const point &location, const label seedFacei=-1, const bool useTreeSearch=true) const
Find nearest boundary face.
pointIndexHit intersection (const point &pStart, const point &pEnd) const
Find first intersection of boundary in segment [pStart, pEnd].
List< pointIndexHit > intersections (const point &pStart, const point &pEnd) const
Find all intersections of boundary within segment pStart .. pEnd.
bool isInside (const point &) const
Determine inside/outside status.
void clearOut ()
Delete all storage.
void correct ()
Correct for mesh geom/topo changes.
Static Public Attributes
static scalar tol_ = 1e-3
Tolerance on linear dimensions.
Detailed Description
Various (local, not parallel) searches on polyMesh; uses (demand driven) octree to search.
Source files
meshSearch.H
meshSearch.C
Definition at line 56 of file meshSearch.H.
Constructor & Destructor Documentation
meshSearch (const polyMesh & mesh, const polyMesh::cellDecomposition cellDecompMode = polyMesh::CELL_TETS)
Construct from components. Constructs bb slightly bigger than.
mesh points bb.
Definition at line 550 of file meshSearch.C.
References polyMesh::CELL_TETS, polyMesh::FACE_DIAG_TRIS, and polyMesh::tetBasePtIs().
meshSearch (const polyMesh & mesh, const treeBoundBox & bb, const polyMesh::cellDecomposition cellDecompMode = polyMesh::CELL_TETS)
Construct with a custom bounding box. Any mesh element outside.
bb will not be found. Up to user to make sure bb extends slightly beyond wanted elements.
Definition at line 571 of file meshSearch.C.
References polyMesh::CELL_TETS, polyMesh::FACE_DIAG_TRIS, and polyMesh::tetBasePtIs().
~meshSearch ()
Destructor.
Definition at line 596 of file meshSearch.C.
Member Function Documentation
ClassName ("meshSearch")
const polyMesh& mesh () const inline
Definition at line 225 of file meshSearch.H.
polyMesh::cellDecomposition decompMode () const inline
Definition at line 230 of file meshSearch.H.
const Foam::indexedOctree< Foam::treeDataFace > & boundaryTree () const
Get (demand driven) reference to octree holding all.
boundary faces
Definition at line 605 of file meshSearch.C.
References Foam::constant::electromagnetic::e, treeBoundBox::extend(), Foam::identity(), boundBox::max(), boundBox::min(), and rndGen.
const Foam::indexedOctree< Foam::treeDataCell > & cellTree () const
Get (demand driven) reference to octree holding all cells.
Definition at line 657 of file meshSearch.C.
References Foam::constant::electromagnetic::e, treeBoundBox::extend(), boundBox::max(), boundBox::min(), and rndGen.
Foam::label findNearestCell (const point & location, const label seedCelli = -1, const bool useTreeSearch = true) const
Find nearest cell in terms of cell centre.
Options:
use octree
use linear search
if seed is provided walk. (uses findNearestCellWalk; does not handle holes in domain)
Definition at line 703 of file meshSearch.C.
Foam::label findNearestFace (const point & location, const label seedFacei = -1, const bool useTreeSearch = true) const
Definition at line 726 of file meshSearch.C.
Foam::label findCell (const point & location, const label seedCelli = -1, const bool useTreeSearch = true) const
Find cell containing location.
If seed provided walks and falls back to linear/tree search. (so handles holes correctly)s Returns -1 if not in domain.
Definition at line 749 of file meshSearch.C.
Foam::label findNearestBoundaryFace (const point & location, const label seedFacei = -1, const bool useTreeSearch = true) const
Find nearest boundary face.
If seed provided walks but then does not pass local minima in distance. Also does not jump from one connected region to the next.
Definition at line 773 of file meshSearch.C.
References indexedOctree< Type >::bb(), PointHit< Point >::distance(), treeDataFace::faceLabels(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), Foam::magSqr(), boundBox::max(), boundBox::min(), face::nearestPoint(), indexedOctree< Type >::shapes(), and Foam::sqr().
Foam::pointIndexHit intersection (const point & pStart, const point & pEnd) const
Find first intersection of boundary in segment [pStart, pEnd].
(so inclusive of endpoints). Always octree for now
Definition at line 839 of file meshSearch.C.
References PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), and PointIndexHit< Point >::setIndex().
Foam::List< Foam::pointIndexHit > intersections (const point & pStart, const point & pEnd) const
Find all intersections of boundary within segment pStart .. pEnd.
Always octree for now
Definition at line 856 of file meshSearch.C.
References DynamicList< T, SizeMin >::append(), PointIndexHit< Point >::hit(), PointIndexHit< Point >::index(), PointIndexHit< Point >::setIndex(), and DynamicList< T, SizeMin >::shrink().
bool isInside (const point & p) const
Determine inside/outside status.
Definition at line 882 of file meshSearch.C.
References volumeType::INSIDE.
void clearOut ()
Delete all storage.
Definition at line 888 of file meshSearch.C.
void correct ()
Correct for mesh geom/topo changes.
Definition at line 896 of file meshSearch.C.
Member Data Documentation
scalar tol_ = 1e-3 static
Tolerance on linear dimensions.
Definition at line 186 of file meshSearch.H.
The documentation for this class was generated from the following files:
src/meshTools/meshSearch/meshSearch.H
src/meshTools/meshSearch/meshSearch.C