OpenFOAM: PrimitivePatchInterpolation< Patch > Class Template Reference
PrimitivePatchInterpolation< Patch > Class Template Reference
Interpolation class within a primitive patch. Allows interpolation from points to faces and vice versa.
Public Member Functions
PrimitivePatchInterpolation (const Patch &p)
Construct from PrimitivePatch.
~PrimitivePatchInterpolation ()
Destructor.
template<class Type >
tmp< Field< Type > > faceToPointInterpolate (const Field< Type > &ff) const
Interpolate from faces to points.
template<class Type >
tmp< Field< Type > > faceToPointInterpolate (const tmp< Field< Type >> &tff) const
template<class Type >
tmp< Field< Type > > pointToFaceInterpolate (const Field< Type > &pf) const
Interpolate from points to faces.
template<class Type >
tmp< Field< Type > > pointToFaceInterpolate (const tmp< Field< Type >> &tpf) const
template<class Type >
tmp< Field< Type > > faceToEdgeInterpolate (const Field< Type > &ff) const
Interpolate from faces to edges.
template<class Type >
tmp< Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type >> &tff) const
bool movePoints ()
Do what is necessary if the mesh has moved.
Detailed Description
template<class Patch>
class Foam::PrimitivePatchInterpolation< Patch >
Interpolation class within a primitive patch. Allows interpolation from points to faces and vice versa.
Source files
PrimitivePatchInterpolation.H
PrimitivePatchInterpolation.C
Definition at line 49 of file PrimitivePatchInterpolation.H.
Constructor & Destructor Documentation
PrimitivePatchInterpolation (const Patch & p)
Construct from PrimitivePatch.
Definition at line 147 of file PrimitivePatchInterpolation.C.
~PrimitivePatchInterpolation ()
Destructor.
Definition at line 158 of file PrimitivePatchInterpolation.C.
Member Function Documentation
tmp< Field< Type > > faceToPointInterpolate (const Field< Type > & ff) const
Interpolate from faces to points.
Definition at line 169 of file PrimitivePatchInterpolation.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, tmp< T >::ref(), UList< Type >::size(), and Foam::Zero.
tmp< Field< Type > > faceToPointInterpolate (const tmp< Field< Type >> & tff) const
Definition at line 213 of file PrimitivePatchInterpolation.C.
tmp< Field< Type > > pointToFaceInterpolate (const Field< Type > & pf) const
Interpolate from points to faces.
Definition at line 226 of file PrimitivePatchInterpolation.C.
tmp< Field< Type > > pointToFaceInterpolate (const tmp< Field< Type >> & tpf) const
Definition at line 270 of file PrimitivePatchInterpolation.C.
tmp< Field< Type > > faceToEdgeInterpolate (const Field< Type > & ff) const
Interpolate from faces to edges.
Definition at line 283 of file PrimitivePatchInterpolation.C.
tmp< Field< Type > > faceToEdgeInterpolate (const tmp< Field< Type >> & tff) const
Definition at line 327 of file PrimitivePatchInterpolation.C.
bool movePoints ()
Do what is necessary if the mesh has moved.
Definition at line 338 of file PrimitivePatchInterpolation.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/primitivePatchInterpolation/PrimitivePatchInterpolation.H
src/OpenFOAM/interpolations/primitivePatchInterpolation/PrimitivePatchInterpolation.C