OpenFOAM: granularPressureModel Class Reference
granularPressureModel Class Reference abstract
Public Member Functions
TypeName ("granularPressureModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, granularPressureModel, dictionary,(const dictionary &dict),(dict))
granularPressureModel (const dictionary &dict)
Construct from components.
virtual ~granularPressureModel ()
Destructor.
virtual tmp< volScalarField > granularPressureCoeff (const volScalarField &alpha1, const volScalarField &g0, const volScalarField &rho1, const dimensionedScalar &e) const =0
Granular pressure coefficient.
virtual tmp< volScalarField > granularPressureCoeffPrime (const volScalarField &alpha1, const volScalarField &g0, const volScalarField &g0prime, const volScalarField &rho1, const dimensionedScalar &e) const =0
Derivative of the granular pressure coefficient.
virtual bool read ()
TypeName ("granularPressureModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, granularPressureModel, dictionary,(const dictionary &dict),(dict))
granularPressureModel (const dictionary &dict)
Construct from components.
virtual ~granularPressureModel ()
Destructor.
virtual tmp< volScalarField > granularPressureCoeff (const volScalarField &alpha1, const volScalarField &g0, const volScalarField &rho1, const dimensionedScalar &e) const =0
Granular pressure coefficient.
virtual tmp< volScalarField > granularPressureCoeffPrime (const volScalarField &alpha1, const volScalarField &g0, const volScalarField &g0prime, const volScalarField &rho1, const dimensionedScalar &e) const =0
Derivative of the granular pressure coefficient.
virtual bool read ()
Static Public Member Functions
static autoPtr
< granularPressureModel > New (const dictionary &dict)
static autoPtr
< granularPressureModel > New (const dictionary &dict)
Protected Attributes
const dictionary & dict_
Detailed Description
Source files
granularPressureModel.H
granularPressureModel.C
Source files
granularPressureModel.H
granularPressureModel.C
Definition at line 47 of file granularPressureModel.H.
Constructor & Destructor Documentation
granularPressureModel (const dictionary & dict)
Construct from components.
Definition at line 39 of file granularPressureModel.C.
~granularPressureModel () virtual
Destructor.
Definition at line 49 of file granularPressureModel.C.
granularPressureModel (const dictionary & dict)
Construct from components.
virtual ~granularPressureModel () virtual
Destructor.
Member Function Documentation
TypeName ("granularPressureModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , granularPressureModel , dictionary , (const dictionary &dict) , (dict))
Foam::autoPtr< Foam::kineticTheoryModels::granularPressureModel > New (const dictionary & dict) static
Definition at line 28 of file newGranularPressureModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volScalarField> granularPressureCoeff (const volScalarField & alpha1, const volScalarField & g0, const volScalarField & rho1, const dimensionedScalar & e) const pure virtual
Granular pressure coefficient.
Implemented in Lun, SyamlalRogersOBrien, Lun, and SyamlalRogersOBrien.
virtual tmp<volScalarField> granularPressureCoeffPrime (const volScalarField & alpha1, const volScalarField & g0, const volScalarField & g0prime, const volScalarField & rho1, const dimensionedScalar & e) const pure virtual
Derivative of the granular pressure coefficient.
Implemented in Lun, SyamlalRogersOBrien, Lun, and SyamlalRogersOBrien.
virtual bool read () inline virtual
Definition at line 136 of file granularPressureModel.H.
TypeName ("granularPressureModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , granularPressureModel , dictionary , (const dictionary &dict) , (dict))
static autoPtr<granularPressureModel> New (const dictionary & dict) static
virtual tmp<volScalarField> granularPressureCoeff (const volScalarField & alpha1, const volScalarField & g0, const volScalarField & rho1, const dimensionedScalar & e) const pure virtual
Granular pressure coefficient.
Implemented in Lun, SyamlalRogersOBrien, Lun, and SyamlalRogersOBrien.
virtual tmp<volScalarField> granularPressureCoeffPrime (const volScalarField & alpha1, const volScalarField & g0, const volScalarField & g0prime, const volScalarField & rho1, const dimensionedScalar & e) const pure virtual
Derivative of the granular pressure coefficient.
Implemented in Lun, SyamlalRogersOBrien, Lun, and SyamlalRogersOBrien.
virtual bool read () inline virtual
Definition at line 136 of file granularPressureModel.H.
Member Data Documentation
const dictionary & dict_ protected
Definition at line 66 of file granularPressureModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/granularPressureModel/granularPressureModel/granularPressureModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/phaseCompressibleTurbulenceModels/kineticTheoryModels/granularPressureModel/granularPressureModel/granularPressureModel.H
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/granularPressureModel/granularPressureModel/granularPressureModel.C
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/granularPressureModel/granularPressureModel/newGranularPressureModel.C