OpenFOAM: LaakkonenAlopaeusAittamaaDsd Class Reference
LaakkonenAlopaeusAittamaaDsd Class Reference
Daughter size distribution model used by Laakkonen et al. (2006). Note that it must be multiplied by the number of daughter particles (2). Also, the coefficient C4 needs to be set to the value of 2 as to ensure number and mass conservation following Kumar and Ramkrishna (1996). Also the internal coordinate was changed to particle volume, which gives.
Public Member Functions
TypeName ("LaakkonenAlopaeusAittamaa")
Runtime type information.
LaakkonenAlopaeusAittamaaDsd (const breakupModel &breakup, const dictionary &dict)
virtual ~LaakkonenAlopaeusAittamaaDsd ()
Destructor.
virtual dimensionedScalar calcNik (const label i, const label k) const
Return total number of particles assigned to class i when a particle.
Public Member Functions inherited from daughterSizeDistributionModel
TypeName ("daughterSizeDistributionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, daughterSizeDistributionModel, dictionary,(const breakupModel &breakup, const dictionary &dict),(breakup, dict))
daughterSizeDistributionModel (const breakupModel &breakup, const dictionary &dict)
virtual ~daughterSizeDistributionModel ()
Destructor.
const dimensionedScalar & nik (const label i, const label k) const
Return total number of particles assigned to class i when a particle.
void correct ()
Correct field independent expressions.
Additional Inherited Members
Static Public Member Functions inherited from daughterSizeDistributionModel
static autoPtr
< daughterSizeDistributionModel > New (const breakupModel &breakup, const dictionary &dict)
Protected Attributes inherited from daughterSizeDistributionModel
const breakupModel & breakup_
Reference to the breakupModel.
PtrList< PtrList
< dimensionedScalar > > nik_
nik
Detailed Description
Daughter size distribution model used by Laakkonen et al. (2006). Note that it must be multiplied by the number of daughter particles (2). Also, the coefficient C4 needs to be set to the value of 2 as to ensure number and mass conservation following Kumar and Ramkrishna (1996). Also the internal coordinate was changed to particle volume, which gives.
where
= Volume of daughter bubble i [m]
= Volume of mother bubble j [m]
References:
        Laakkonen, M., Alopaeus, V., & Aittamaa, J. (2006).
        Validation of bubble breakage, coalescence and mass transfer models for
        gas-liquid dispersion in agitated vessel.
        Chemical engineering science, 61(1), 218-228.
        Eq. 3, p. 220.
        Kumar, S., & Ramkrishna, D. (1996).
        On the solution of population balance equations by discretization-I.
        A fixed pivot technique.
        Chemical Engineering Science, 51(8), 1311-1332.
        Eq. 33, p. 1318.
Usage
Property Description Required Default value
C1 Coefficient C1 no 6.0
C2 Coefficient C2 no 0.04
C3 Coefficient C3 no 0.01
Source files
LaakkonenAlopaeusAittamaaDsd.H
LaakkonenAlopaeusAittamaaBinaryBreakup.C
Definition at line 119 of file LaakkonenAlopaeusAittamaaDsd.H.
Constructor & Destructor Documentation
LaakkonenAlopaeusAittamaaDsd (const breakupModel & breakup, const dictionary & dict)
Definition at line 49 of file LaakkonenAlopaeusAittamaaDsd.C.
~LaakkonenAlopaeusAittamaaDsd () virtual
Destructor.
Definition at line 61 of file LaakkonenAlopaeusAittamaaDsd.C.
Member Function Documentation
TypeName ("LaakkonenAlopaeusAittamaa")
Runtime type information.
Foam::dimensionedScalar calcNik (const label i, const label k) const virtual
Return total number of particles assigned to class i when a particle.
of class k breaks
Implements daughterSizeDistributionModel.
Definition at line 70 of file LaakkonenAlopaeusAittamaaDsd.C.
References i, k, Foam::pow3(), Foam::pow4(), Foam::pow5(), Foam::pow6(), Foam::sqr(), and x.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/populationBalanceModel/daughterSizeDistributionModels/LaakkonenAlopaeusAittamaaDsd/LaakkonenAlopaeusAittamaaDsd.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/populationBalanceModel/daughterSizeDistributionModels/LaakkonenAlopaeusAittamaaDsd/LaakkonenAlopaeusAittamaaDsd.C