OpenFOAM: viscosityModel Class Reference
viscosityModel Class Reference abstract
An abstract base class for incompressible viscosityModels.
Public Member Functions
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi),(name, viscosityProperties, U, phi))
viscosityModel (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Construct from components.
virtual ~viscosityModel ()=default
Destructor.
const dictionary & viscosityProperties () const
Return the phase transport properties dictionary.
tmp< volScalarField > strainRate () const
Return the strain rate.
virtual tmp< volScalarField > nu () const =0
Return the laminar viscosity.
virtual tmp< scalarField > nu (const label patchi) const =0
Return the laminar viscosity for patch.
virtual void correct ()=0
Correct the laminar viscosity.
virtual bool read (const dictionary &viscosityProperties)=0
Read transportProperties dictionary.
Static Public Member Functions
static autoPtr< viscosityModel > New (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi)
Return a reference to the selected viscosity model.
Protected Member Functions
viscosityModel (const viscosityModel &)=delete
No copy construct.
void operator= (const viscosityModel &)=delete
No copy assignment.
Protected Attributes
word name_
dictionary viscosityProperties_
const volVectorField & U_
const surfaceScalarField & phi_
Detailed Description
An abstract base class for incompressible viscosityModels.
The strain rate is defined by:
mag(symm(grad(U)))
Source files
viscosityModel.H
viscosityModel.C
viscosityModelNew.C
Source files
viscosityModel.H
viscosityModel.C
Definition at line 64 of file viscosityModel.H.
Constructor & Destructor Documentation
viscosityModel (const viscosityModel &) protected delete
No copy construct.
viscosityModel (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi)
Construct from components.
Definition at line 37 of file viscosityModel.C.
virtual ~viscosityModel () virtual default
Destructor.
Member Function Documentation
void operator= (const viscosityModel &) protected delete
No copy assignment.
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , viscosityModel , dictionary , (const word &name, const dictionary &viscosityProperties, const volVectorField &U, const surfaceScalarField &phi) , (name, viscosityProperties, U, phi))
Foam::autoPtr< Foam::viscosityModel > New (const word & name, const dictionary & viscosityProperties, const volVectorField & U, const surfaceScalarField & phi) static
Return a reference to the selected viscosity model.
Definition at line 29 of file viscosityModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, Foam::name(), phi, and U.
const dictionary& viscosityProperties () const inline
Return the phase transport properties dictionary.
Definition at line 155 of file viscosityModel.H.
Foam::tmp< Foam::volScalarField > strainRate () const
Return the strain rate.
Definition at line 53 of file viscosityModel.C.
virtual tmp<volScalarField> nu () const pure virtual
Return the laminar viscosity.
Implemented in Casson, strainRateFunction, BirdCarreau, CrossPowerLaw, HerschelBulkley, powerLaw, and Newtonian.
virtual tmp<scalarField> nu (const label patchi) const pure virtual
Return the laminar viscosity for patch.
Implemented in Casson, strainRateFunction, BirdCarreau, CrossPowerLaw, HerschelBulkley, powerLaw, and Newtonian.
virtual void correct () pure virtual
Correct the laminar viscosity.
Implemented in Casson, BirdCarreau, strainRateFunction, CrossPowerLaw, HerschelBulkley, powerLaw, and Newtonian.
bool read (const dictionary & viscosityProperties) pure virtual
Read transportProperties dictionary.
Implemented in Casson, BirdCarreau, CrossPowerLaw, HerschelBulkley, powerLaw, strainRateFunction, and Newtonian.
Definition at line 59 of file viscosityModel.C.
References Foam::fvc::grad(), Foam::mag(), Foam::sqrt(), Foam::symm(), and viscosityModel::U_.
Member Data Documentation
word name_ protected
Definition at line 71 of file viscosityModel.H.
dictionary viscosityProperties_ protected
Definition at line 72 of file viscosityModel.H.
const volVectorField& U_ protected
Definition at line 74 of file viscosityModel.H.
Referenced by viscosityModel::read().
const surfaceScalarField& phi_ protected
Definition at line 75 of file viscosityModel.H.
The documentation for this class was generated from the following files:
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModel.H
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModel.C
src/transportModels/incompressible/viscosityModels/viscosityModel/viscosityModelNew.C