OpenFOAM: timeSelector Class Reference
timeSelector Class Reference
A List of scalarRange for selecting times.
Public Member Functions
timeSelector ()
Construct null.
timeSelector (const std::string &str)
Construct by parsing string for time ranges.
bool selected (const instant &value) const
Return true if the given instant is within the ranges.
List< bool > selected (const instantList &times) const
Return the set of selected instants in the given list that are within the ranges.
instantList select (const instantList &times) const
Select a list of Time values that are within the ranges.
void inplaceSelect (instantList &times) const
Select a list of Time values that are within the ranges.
Static Public Member Functions
static void addOptions (const bool constant=true, const bool withZero=false)
Add timeSelector options to argList::validOptions.
static instantList select (const instantList &times, const argList &args, const word &constantName="constant")
Return the set of times selected based on the argList options.
static instantList select0 (Time &runTime, const argList &args)
Return the set of times selected based on the argList options and also set the runTime to the first instance or the constant/ directory if no instances are specified or available.
static instantList selectIfPresent (Time &runTime, const argList &args)
If any time option provided return the set of times (as select0) otherwise return just the current time.
Detailed Description
A List of scalarRange for selecting times.
The timeSelector provides a convenient means of selecting multiple times. A typical use would be the following:
timeSelector::addOptions();
// add other options
#include "setRootCase.H"
#include "createTime.H"
instantList timeDirs = timeSelector::select0(runTime, args);
...
forAll(timeDirs, timei)
{
    ...
}
The result program would receive -time, -latestTime, -constant and -noZero options. The -constant option explicitly includes the constant/ directory in the time list and the -noZero option explicitly excludes the 0/ directory from the time list.
There may however also be many cases in which neither the constant/ directory nor the 0/ directory contain particularly relevant information. This might occur, for example, when post-processing results. In this case, addOptions is called with optional boolean arguments.
timeSelector::addOptions(false, true);
The first argument avoids adding the -constant option. The second argument adds an additional -withZero option and also prevents the 0/ directory from being included in the default time range and in the -latestTime selection.
Source files
timeSelector.H
timeSelector.C
Definition at line 88 of file timeSelector.H.
Constructor & Destructor Documentation
timeSelector ()
Construct null.
Definition at line 29 of file timeSelector.C.
timeSelector (const std::string & str)
Construct by parsing string for time ranges.
Definition at line 35 of file timeSelector.C.
Member Function Documentation
bool selected (const instant & value) const
Return true if the given instant is within the ranges.
Definition at line 43 of file timeSelector.C.
Foam::List< bool > selected (const instantList & times) const
Return the set of selected instants in the given list that are within the ranges.
Definition at line 49 of file timeSelector.C.
References scalarRanges::operator()(), and Instant< T >::value().
Foam::instantList select (const instantList & times) const
Select a list of Time values that are within the ranges.
Definition at line 88 of file timeSelector.C.
void inplaceSelect (instantList & times) const
Select a list of Time values that are within the ranges.
Definition at line 94 of file timeSelector.C.
References Foam::subset().
void addOptions (const bool constant = true, const bool withZero = false) static
Add timeSelector options to argList::validOptions.
Parameters
constant Add the -constant option to include the constant/ directory
withZero Enable the -withZero option and alter the normal time selection behaviour (and -latestTime behaviour) to exclude the 0/ directory. The 0/ directory will only be included when -withZero is specified. The -noZero option has precedence over the -withZero option.
Definition at line 101 of file timeSelector.C.
References Foam::inplaceSubset().
Foam::instantList select (const instantList & times, const argList & args, const word & constantName = "constant") static
Return the set of times selected based on the argList options.
Definition at line 147 of file timeSelector.C.
Foam::instantList select0 (Time & runTime, const argList & args) static
Return the set of times selected based on the argList options and also set the runTime to the first instance or the constant/ directory if no instances are specified or available.
Definition at line 234 of file timeSelector.C.
Foam::instantList selectIfPresent (Time & runTime, const argList & args) static
If any time option provided return the set of times (as select0) otherwise return just the current time.
Also set the runTime to the first instance
Definition at line 265 of file timeSelector.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/Time/timeSelector.H
src/OpenFOAM/db/Time/timeSelector.C