OpenFOAM: dynamicCodeContext Class Reference
dynamicCodeContext Class Reference
Encapsulation of dynamic code dictionaries.
Public Member Functions
dynamicCodeContext ()
Construct null.
dynamicCodeContext (const dictionary &dict)
Construct from a dictionary.
bool valid () const
Considered valid if not using dictionary::null as the context.
void setCodeContext (const dictionary &dict)
Set code context from a dictionary.
const dictionary & dict () const
Return the parent dictionary context.
const string & include () const
Return the code-includes.
const string & options () const
Return the code-options.
const string & libs () const
Return the code-libs.
const string & code () const
Return the code.
const string & localCode () const
Return the local (file-scope) code.
const SHA1 & sha1 () const
Return SHA1 calculated from options, libs, include, code.
void append (const std::string &str)
Add content to SHA1 hashing.
operator const dictionary & () const
Cast to dictionary.
Static Public Member Functions
static void inplaceExpand (string &code, const dictionary &dict)
Cleanup string and expand with dictionary parameters.
static unsigned addLineDirective (string &code, label lineNum, const fileName &file)
Prefix a #line directive to code.
static unsigned addLineDirective (string &code, label lineNum, const dictionary &dict)
Prefix a #line directive to code.
Detailed Description
Encapsulation of dynamic code dictionaries.
Source files
dynamicCodeContext.H
dynamicCodeContext.C
Definition at line 49 of file dynamicCodeContext.H.
Constructor & Destructor Documentation
dynamicCodeContext ()
Construct null.
Definition at line 74 of file dynamicCodeContext.C.
dynamicCodeContext (const dictionary & dict) explicit
Construct from a dictionary.
Definition at line 80 of file dynamicCodeContext.C.
Member Function Documentation
void inplaceExpand (string & code, const dictionary & dict) static
Cleanup string and expand with dictionary parameters.
Definition at line 29 of file dynamicCodeContext.C.
unsigned addLineDirective (string & code, label lineNum, const fileName & file) static
Prefix a #line directive to code.
The input lineNum is 0-based. Is a no-op if any of the arguments are invalid (lineNum is negative, code or file are empty)
Returns
The change in string length caused by the directive. This can potentially be used to recover the substring portions.
Definition at line 40 of file dynamicCodeContext.C.
References Foam::stringOps::inplaceExpand(), and Foam::stringOps::inplaceTrim().
unsigned addLineDirective (string & code, label lineNum, const dictionary & dict) static
Prefix a #line directive to code.
The name of the dictionary is used for the 'file' name.
Definition at line 62 of file dynamicCodeContext.C.
bool valid () const
Considered valid if not using dictionary::null as the context.
Definition at line 90 of file dynamicCodeContext.C.
void setCodeContext (const dictionary & dict)
Set code context from a dictionary.
Definition at line 96 of file dynamicCodeContext.C.
References dictionary::null.
const dictionary& dict () const inline
Return the parent dictionary context.
Definition at line 156 of file dynamicCodeContext.H.
const string& include () const inline
Return the code-includes.
Definition at line 164 of file dynamicCodeContext.H.
const string& options () const inline
Return the code-options.
Definition at line 172 of file dynamicCodeContext.H.
References SHA1::append().
Referenced by CodedSource< Type >::prepare().
const string& libs () const inline
Return the code-libs.
Definition at line 180 of file dynamicCodeContext.H.
const string& code () const inline
Return the code.
Definition at line 188 of file dynamicCodeContext.H.
const string& localCode () const inline
Return the local (file-scope) code.
Definition at line 196 of file dynamicCodeContext.H.
const SHA1& sha1 () const inline
Return SHA1 calculated from options, libs, include, code.
Definition at line 204 of file dynamicCodeContext.H.
void append (const std::string & str) inline
Add content to SHA1 hashing.
Definition at line 212 of file dynamicCodeContext.H.
operator const dictionary & () const inline
Cast to dictionary.
Definition at line 223 of file dynamicCodeContext.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCodeContext.H
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCodeContext.C