OpenFOAM: primitiveMeshGeometry Class Reference
primitiveMeshGeometry Class Reference
Updateable mesh geometry + checking routines.
Public Member Functions
ClassName ("primitiveMeshGeometry")
primitiveMeshGeometry (const primitiveMesh &)
Construct from mesh.
const primitiveMesh & mesh () const
const vectorField & faceAreas () const
const vectorField & faceCentres () const
const vectorField & cellCentres () const
const scalarField & cellVolumes () const
void correct ()
Take over properties from mesh.
void correct (const pointField &p, const labelList &changedFaces)
Recalculate on selected faces. Recalculates cell properties.
labelList affectedCells (const labelList &changedFaces) const
Helper function: get affected cells from faces.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceArea (const bool report, const scalar minArea, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr) const
Static Public Member Functions
static bool checkFaceDotProduct (const bool report, const scalar orthWarn, const primitiveMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFacePyramids (const bool report, const scalar minPyrVol, const primitiveMesh &, const vectorField &cellCentres, const pointField &p, const labelList &checkFaces, labelHashSet *)
static bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const primitiveMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceWeights (const bool report, const scalar warnWeight, const primitiveMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceAngles (const bool report, const scalar maxDeg, const primitiveMesh &mesh, const vectorField &faceAreas, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceTwist (const bool report, const scalar minTwist, const primitiveMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkFaceArea (const bool report, const scalar minArea, const primitiveMesh &, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
static bool checkCellDeterminant (const bool report, const scalar minDet, const primitiveMesh &, const vectorField &faceAreas, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr)
Detailed Description
Updateable mesh geometry + checking routines.
Source files
primitiveMeshGeometry.H
primitiveMeshGeometry.C
Definition at line 47 of file primitiveMeshGeometry.H.
Constructor & Destructor Documentation
primitiveMeshGeometry (const primitiveMesh & mesh)
Construct from mesh.
Definition at line 214 of file primitiveMeshGeometry.C.
References primitiveMeshGeometry::correct().
Member Function Documentation
ClassName ("primitiveMeshGeometry")
const primitiveMesh& mesh () const inline
Definition at line 113 of file primitiveMeshGeometry.H.
const vectorField& faceAreas () const inline
Definition at line 118 of file primitiveMeshGeometry.H.
const vectorField& faceCentres () const inline
Definition at line 122 of file primitiveMeshGeometry.H.
const vectorField& cellCentres () const inline
Definition at line 126 of file primitiveMeshGeometry.H.
const scalarField& cellVolumes () const inline
Definition at line 130 of file primitiveMeshGeometry.H.
void correct ()
Take over properties from mesh.
Definition at line 229 of file primitiveMeshGeometry.C.
Referenced by primitiveMeshGeometry::primitiveMeshGeometry().
void correct (const pointField & p, const labelList & changedFaces)
Recalculate on selected faces. Recalculates cell properties.
on owner and neighbour of these cells.
Definition at line 239 of file primitiveMeshGeometry.C.
Foam::labelList affectedCells (const labelList & changedFaces) const
Helper function: get affected cells from faces.
Definition at line 185 of file primitiveMeshGeometry.C.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 252 of file primitiveMeshGeometry.C.
bool checkFacePyramids (const bool report, const scalar minPyrVol, const primitiveMesh & mesh, const vectorField & cellCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 393 of file primitiveMeshGeometry.C.
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 503 of file primitiveMeshGeometry.C.
bool checkFaceWeights (const bool report, const scalar warnWeight, const primitiveMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 640 of file primitiveMeshGeometry.C.
bool checkFaceAngles (const bool report, const scalar maxDeg, const primitiveMesh & mesh, const vectorField & faceAreas, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 724 of file primitiveMeshGeometry.C.
References Foam::abort(), Foam::asin(), Foam::degToRad(), Foam::endl(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), UList< T >::first(), forAll, i, Foam::Info, HashSet< Key, Hash >::insert(), UList< T >::last(), Foam::mag(), Foam::max(), Foam::min(), Foam::normalised(), Foam::radToDeg(), Foam::reduce(), Foam::sin(), and WarningInFunction.
bool checkFaceTwist (const bool report, const scalar minTwist, const primitiveMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 982 of file primitiveMeshGeometry.C.
References Foam::abort(), Foam::endl(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::mag(), face::nextLabel(), nf(), Foam::nl, Foam::reduce(), UList< T >::size(), and WarningInFunction.
bool checkFaceArea (const bool report, const scalar minArea, const primitiveMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Definition at line 1086 of file primitiveMeshGeometry.C.
bool checkCellDeterminant (const bool report, const scalar minDet, const primitiveMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) static
Definition at line 1145 of file primitiveMeshGeometry.C.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1244 of file primitiveMeshGeometry.C.
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1265 of file primitiveMeshGeometry.C.
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1287 of file primitiveMeshGeometry.C.
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1311 of file primitiveMeshGeometry.C.
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1333 of file primitiveMeshGeometry.C.
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1378 of file primitiveMeshGeometry.C.
bool checkFaceArea (const bool report, const scalar minArea, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 1401 of file primitiveMeshGeometry.C.
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) const
Definition at line 1421 of file primitiveMeshGeometry.C.
The documentation for this class was generated from the following files:
src/meshTools/primitiveMeshGeometry/primitiveMeshGeometry.H
src/meshTools/primitiveMeshGeometry/primitiveMeshGeometry.C