OpenFOAM: vtuCells Class Reference
vtuCells Class Reference
A deep-copy description of an OpenFOAM volume mesh in data structures suitable for VTK UnstructuredGrid, including the possibility of decomposing polyhedral cells into primitive cell types.
Public Member Functions
vtuCells (const enum contentType output=contentType::XML, const bool decompose=false)
Construct from components.
vtuCells (const polyMesh &mesh, const enum contentType output=contentType::XML, const bool decompose=false)
Construct from components and create the output information immediately.
vtuCells (const vtk::outputOptions opts, const bool decompose=false)
Construct from components.
vtuCells (const polyMesh &mesh, const vtk::outputOptions opts, const bool decompose=false)
Construct from components, and create the output information immediately.
~vtuCells ()=default
Destructor.
enum contentType content () const
The output content type.
bool decomposeRequested () const
Query the polyhedral decompose requested flag.
bool empty () const noexcept
True if no cellTypes are populated.
label size () const noexcept
The size of populated cellTypes.
void clear ()
Reset all sizes to zero.
void reset (const polyMesh &mesh)
Create the geometry using the previously requested output and decomposition types.
void reset (const polyMesh &mesh, const enum contentType output, const bool decompose)
Respecify requested output and decomposition type prior to creating the geometry.
void renumberCells (const labelUList &mapping)
Renumber cell ids to account for subset meshes.
void renumberPoints (const labelUList &mapping)
Renumber point ids to account for subset meshes.
const List< uint8_t > & cellTypes () const
Values for "types" (XML) and "CELL_TYPES" (legacy)
const labelList & vertLabels () const
Values for "connectivity" (XML) or "CELLS" (legacy)
const labelList & vertOffsets () const
Values for "offsets" (XML only)
const labelList & faceLabels () const
Values for "faces" (XML only)
const labelList & faceOffsets () const
Values for "faceoffset" (XML only)
const labelList & addPointCellLabels () const
Additional point addressing (from added point to original cell)
const labelList & cellMap () const
Original cell ids for all cells (regular and decomposed).
Public Member Functions inherited from vtuSizing
vtuSizing ()
Construct null.
vtuSizing (const polyMesh &mesh)
Construct sizing by analyzing the mesh.
vtuSizing (const polyMesh &mesh, const bool decompose)
Construct sizing by analyzing the mesh.
~vtuSizing ()=default
Destructor.
void reset (const polyMesh &mesh, const bool decompose=false)
Reset sizing by analyzing the mesh.
void clear ()
Reset all sizes to zero.
bool decompose () const
Query the decompose flag (normally off)
label nCells () const
Number of cells for the mesh.
label nPoints () const
Number of points for the mesh.
label nVertLabels () const
Number of vertex labels for the mesh.
label nFaceLabels () const
Number of polyhedral face labels for the mesh.
label nCellsPoly () const
Number of polyhedral cells for the mesh.
label nVertPoly () const
Number of vertex labels for polyhedral cells of the mesh.
label nAddCells () const
Number of additional (decomposed) cells for the mesh.
label nAddPoints () const
Number of additional (decomposed) points for the mesh.
label nAddVerts () const
Number of additional (decomposed) vertices for the mesh.
label nFieldCells () const
Number of field cells = nCells + nAddCells.
label nFieldPoints () const
Number of field points = nPoints + nAddPoints.
label sizeOf (const enum contentType output, const enum slotType slot) const
Return the required size for the storage slot.
label sizeLegacy () const
The calculated size for legacy storage.
label sizeLegacy (const enum slotType slot) const
The calculated size for legacy storage of the specified slot.
label sizeXml (const enum slotType slot) const
The calculated size for xml storage of the specified slot.
label sizeInternal (const enum slotType slot) const
The calculated size for vtk-internal storage of the specified slot.
void populateLegacy (const polyMesh &mesh, UList< uint8_t > &cellTypes, labelUList &connectivity, foamVtkMeshMaps &maps) const
Populate lists for Legacy output.
void populateXml (const polyMesh &mesh, UList< uint8_t > &cellTypes, labelUList &connectivity, labelUList &offsets, labelUList &faces, labelUList &facesOffsets, foamVtkMeshMaps &maps) const
Populate lists for XML output.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< int > &connectivity, UList< int > &offsets, UList< int > &faces, UList< int > &facesOffsets, foamVtkMeshMaps &maps) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long > &connectivity, UList< long > &offsets, UList< long > &faces, UList< long > &facesOffsets, foamVtkMeshMaps &maps) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long long > &connectivity, UList< long long > &offsets, UList< long long > &faces, UList< long long > &facesOffsets, foamVtkMeshMaps &maps) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< int > &connectivity, UList< int > &offsets, UList< int > &faces, UList< int > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long > &connectivity, UList< long > &offsets, UList< long > &faces, UList< long > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds) const
Populate lists for Internal VTK format.
void populateInternal (const polyMesh &mesh, UList< uint8_t > &cellTypes, UList< long long > &connectivity, UList< long long > &offsets, UList< long long > &faces, UList< long long > &facesOffsets, labelUList &cellMap, labelUList &addPointsIds) const
Populate lists for Internal VTK format.
void info (Ostream &os) const
Report some information.
bool operator== (const vtuSizing &rhs) const
Test equality.
bool operator!= (const vtuSizing &rhs) const
Test inequality.
Additional Inherited Members
Public Types inherited from vtuSizing
enum contentType { LEGACY, XML, INTERNAL }
Types of content that the storage may represent.
enum slotType { CELLS, CELLS_OFFSETS, FACES, FACES_OFFSETS }
The possible storage 'slots' that can be used.
Static Public Member Functions inherited from vtuSizing
static labelList copyVertLabelsLegacy (const labelUList &connectivity, const label globalPointOffset)
Copy vertex labels with a global point offset - legacy format.
static labelList copyVertLabelsXml (const labelUList &connectivity, const label globalPointOffset)
Copy vertex labels with a global point offset - XML format.
static labelList copyFaceLabelsXml (const labelUList &faceLabels, const label globalPointOffset)
Copy faces stream labels with a global point offset - XML format.
static labelList copyFaceOffsetsXml (const labelUList &faceOffsets, const label prevOffset)
Copy face offsets with an offset from previous - XML format.
static void renumberVertLabelsLegacy (labelUList &connectivity, const label globalPointOffset)
Renumber vertex labels by global point offset - legacy format.
static void renumberVertLabelsXml (labelUList &connectivity, const label globalPointOffset)
Renumber vertex labels by global point offset - XML format.
static void renumberFaceLabelsXml (labelUList &faceLabels, const label globalPointOffset)
Renumber faces stream labels by global point offset - XML format.
static void renumberFaceOffsetsXml (labelUList &faceOffsets, const label prevOffset)
Renumber face offsets with an offset from previous - XML format.
Detailed Description
A deep-copy description of an OpenFOAM volume mesh in data structures suitable for VTK UnstructuredGrid, including the possibility of decomposing polyhedral cells into primitive cell types.
Knowledge of the vtkUnstructuredGrid and the corresponding .vtu xml file-format aids in understanding this class. The class can be used for the VTK xml format, legacy format, as well as a VTK internal representation. The internal representation is somewhat related to the xml format, but not entirely.
See Also
Foam::vtk::vtuSizing
Source files
foamVtuCells.H
foamVtuCells.C
foamVtuCellsI.H
Definition at line 70 of file foamVtuCells.H.
Constructor & Destructor Documentation
vtuCells (const enum contentType output = contentType::XML, const bool decompose = false)
Construct from components.
Optionally with polyhedral decomposition.
Definition at line 28 of file foamVtuCells.C.
vtuCells (const polyMesh & mesh, const enum contentType output = contentType::XML, const bool decompose = false)
Construct from components and create the output information immediately.
Definition at line 46 of file foamVtuCells.C.
vtuCells (const vtk::outputOptions opts, const bool decompose = false)
Construct from components.
Optionally with polyhedral decomposition.
Definition at line 59 of file foamVtuCells.C.
References reset().
vtuCells (const polyMesh & mesh, const vtk::outputOptions opts, const bool decompose = false)
Construct from components, and create the output information immediately.
Definition at line 73 of file foamVtuCells.C.
~vtuCells () default
Destructor.
Member Function Documentation
enum Foam::vtk::vtuCells::contentType content () const inline
The output content type.
Definition at line 27 of file foamVtuCellsI.H.
bool decomposeRequested () const inline
Query the polyhedral decompose requested flag.
Definition at line 33 of file foamVtuCellsI.H.
bool empty () const inline noexcept
True if no cellTypes are populated.
Definition at line 39 of file foamVtuCellsI.H.
Foam::label size () const inline noexcept
The size of populated cellTypes.
Definition at line 45 of file foamVtuCellsI.H.
void clear ()
Reset all sizes to zero.
Definition at line 87 of file foamVtuCells.C.
References reset().
void reset (const polyMesh & mesh)
Create the geometry using the previously requested output and decomposition types.
Definition at line 149 of file foamVtuCells.C.
void reset (const polyMesh & mesh, const enum contentType output, const bool decompose)
Respecify requested output and decomposition type prior to creating the geometry.
Definition at line 157 of file foamVtuCells.C.
References vtuSizing::reset().
void renumberCells (const labelUList & mapping)
Renumber cell ids to account for subset meshes.
Definition at line 170 of file foamVtuCells.C.
void renumberPoints (const labelUList & mapping)
Renumber point ids to account for subset meshes.
Definition at line 176 of file foamVtuCells.C.
const Foam::List< uint8_t > & cellTypes () const inline
Values for "types" (XML) and "CELL_TYPES" (legacy)
Definition at line 52 of file foamVtuCellsI.H.
const Foam::labelList & vertLabels () const inline
Values for "connectivity" (XML) or "CELLS" (legacy)
Definition at line 59 of file foamVtuCellsI.H.
const Foam::labelList & vertOffsets () const inline
Values for "offsets" (XML only)
Definition at line 66 of file foamVtuCellsI.H.
const Foam::labelList & faceLabels () const inline
Values for "faces" (XML only)
Definition at line 73 of file foamVtuCellsI.H.
const Foam::labelList & faceOffsets () const inline
Values for "faceoffset" (XML only)
Definition at line 80 of file foamVtuCellsI.H.
const Foam::labelList & addPointCellLabels () const inline
Additional point addressing (from added point to original cell)
Definition at line 87 of file foamVtuCellsI.H.
const Foam::labelList & cellMap () const inline
Original cell ids for all cells (regular and decomposed).
Definition at line 94 of file foamVtuCellsI.H.
The documentation for this class was generated from the following files:
src/fileFormats/vtk/part/foamVtuCells.H
src/fileFormats/vtk/part/foamVtuCells.C
src/fileFormats/vtk/part/foamVtuCellsI.H