OpenFOAM: cellDistFuncs Class Reference
cellDistFuncs Class Reference
Collection of functions used in wall distance calculation.
Public Member Functions
ClassName ("cellDistFuncs")
cellDistFuncs (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
Access mesh.
labelHashSet getPatchIDs (const UList< wordRe > &patchNames) const
Return the set of patch IDs corresponding to the given names.
template<class Type >
labelHashSet getPatchIDs () const
Get patchIDs of/derived off certain type (e.g. 'processorPolyPatch')
scalar smallestDist (const point &p, const polyPatch &patch, const label nWallFaces, const labelList &wallFaces, label &meshFacei) const
Calculate smallest true distance (and face index)
label getPointNeighbours (const primitivePatch &, const label patchFacei, labelList &) const
Get faces sharing point with face on patch.
label maxPatchSize (const labelHashSet &patchIDs) const
Size of largest patch (out of supplied subset of patches)
label sumPatchSize (const labelHashSet &patchIDs) const
Sum of patch sizes (out of supplied subset of patches).
void correctBoundaryFaceCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
Correct all cells connected to boundary (via face). Sets values in.
void correctBoundaryPointCells (const labelHashSet &patchIDs, scalarField &wallDistCorrected, Map< label > &nearestFace) const
Correct all cells connected to wall (via point). Sets values in.
template<class Type >
Foam::labelHashSet getPatchIDs () const
Detailed Description
Collection of functions used in wall distance calculation.
Source files
cellDistFuncs.H
cellDistFuncs.C
cellDistFuncsTemplates.C
Definition at line 58 of file cellDistFuncs.H.
Constructor & Destructor Documentation
cellDistFuncs (const polyMesh & mesh)
Construct from mesh.
Definition at line 57 of file cellDistFuncs.C.
Member Function Documentation
ClassName ("cellDistFuncs")
const polyMesh& mesh () const inline
Access mesh.
Definition at line 105 of file cellDistFuncs.H.
Referenced by cellDistFuncs::getPatchIDs().
Foam::labelHashSet getPatchIDs (const UList< wordRe > & patchNames) const
Return the set of patch IDs corresponding to the given names.
Definition at line 66 of file cellDistFuncs.C.
labelHashSet getPatchIDs () const
Get patchIDs of/derived off certain type (e.g. 'processorPolyPatch')
Uses isA, not isType
Foam::scalar smallestDist (const point & p, const polyPatch & patch, const label nWallFaces, const labelList & wallFaces, label & meshFacei) const
Calculate smallest true distance (and face index)
from pt to faces wallFaces. For efficiency reasons we still pass in patch instead of extracting it from mesh_
Definition at line 78 of file cellDistFuncs.C.
Foam::label getPointNeighbours (const primitivePatch & patch, const label patchFacei, labelList & neighbours) const
Get faces sharing point with face on patch.
Definition at line 112 of file cellDistFuncs.C.
Foam::label maxPatchSize (const labelHashSet & patchIDs) const
Size of largest patch (out of supplied subset of patches)
Definition at line 220 of file cellDistFuncs.C.
Foam::label sumPatchSize (const labelHashSet & patchIDs) const
Sum of patch sizes (out of supplied subset of patches).
Used in sizing arrays.
Definition at line 241 of file cellDistFuncs.C.
void correctBoundaryFaceCells (const labelHashSet & patchIDs, scalarField & wallDistCorrected, Map< label > & nearestFace) const
Correct all cells connected to boundary (via face). Sets values in.
wallDistCorrected. Sets nearest wallface in nearestFace.
Definition at line 263 of file cellDistFuncs.C.
void correctBoundaryPointCells (const labelHashSet & patchIDs, scalarField & wallDistCorrected, Map< label > & nearestFace) const
Correct all cells connected to wall (via point). Sets values in.
wallDistCorrected. Uses/sets nearest wallFace in nearestFace.
Definition at line 319 of file cellDistFuncs.C.
Foam::labelHashSet getPatchIDs () const
Definition at line 29 of file cellDistFuncsTemplates.C.
References polyMesh::boundaryMesh(), forAll, cellDistFuncs::mesh(), and UPtrList< T >::size().
The documentation for this class was generated from the following files:
src/meshTools/cellDist/cellDistFuncs.H
src/meshTools/cellDist/cellDistFuncs.C
src/meshTools/cellDist/cellDistFuncsTemplates.C