OpenFOAM: combineFaces Class Reference
combineFaces Class Reference
Combines boundary faces into single face. The faces get the patch of the first face ('the master')
Public Member Functions
ClassName ("combineFaces")
Runtime type information.
combineFaces (const polyMesh &mesh, const bool undoable=false)
Construct from mesh.
const labelList & masterFace () const
If undoable: masterface for every set.
const labelList & savedPointLabels () const
If undoable: set of original point labels of stored points.
labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const labelHashSet &boundaryCells, const bool mergeAcrossPatches=false) const
Extract lists of all (non-coupled) boundary faces on selected.
labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const bool mergeAcrossPatches=false) const
Extract lists of all (non-coupled) boundary faces that can.
void setRefinement (const labelListList &, polyTopoChange &)
Play commands into polyTopoChange to combine faces. Gets.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
void setUnrefinement (const labelList &masterFaces, polyTopoChange &meshMod, Map< label > &restoredPoints, Map< label > &restoredFaces, Map< label > &restoredCells)
Play commands into polyTopoChange to reinsert original faces.
Static Public Member Functions
static face getOutsideFace (const indirectPrimitivePatch &)
Gets outside of patch as a face (in mesh point labels)
Detailed Description
Combines boundary faces into single face. The faces get the patch of the first face ('the master')
Source files
combineFaces.H
combineFaces.C
Definition at line 54 of file combineFaces.H.
Constructor & Destructor Documentation
combineFaces (const polyMesh & mesh, const bool undoable = false)
Construct from mesh.
Definition at line 284 of file combineFaces.C.
Member Function Documentation
ClassName ("combineFaces")
Runtime type information.
const labelList& masterFace () const inline
If undoable: masterface for every set.
Definition at line 173 of file combineFaces.H.
Referenced by meshRefinement::mergePatchFacesUndo().
const labelList& savedPointLabels () const inline
If undoable: set of original point labels of stored points.
Definition at line 181 of file combineFaces.H.
Referenced by meshRefinement::mergePatchFacesUndo().
Foam::labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const labelHashSet & boundaryCells, const bool mergeAcrossPatches = false) const
Extract lists of all (non-coupled) boundary faces on selected.
cells that can be merged. Uses getFaceRegions. Optionally allow faces-on-different-patches to be merged (into the largest area face - could be improved). Note: causes a problem in undoing - all restored faces get the patch/zone from the master face.
Definition at line 301 of file combineFaces.C.
Referenced by meshRefinement::mergePatchFaces(), and meshRefinement::mergePatchFacesUndo().
Foam::labelListList getMergeSets (const scalar featureCos, const scalar minConcaveCos, const bool mergeAcrossPatches = false) const
Extract lists of all (non-coupled) boundary faces that can.
be merged. Uses getFaceRegions. See note above about mergeAcrossPatches.
Definition at line 418 of file combineFaces.C.
Foam::face getOutsideFace (const indirectPrimitivePatch & fp) static
Gets outside of patch as a face (in mesh point labels)
Definition at line 456 of file combineFaces.C.
void setRefinement (const labelListList & faceSets, polyTopoChange & meshMod)
Play commands into polyTopoChange to combine faces. Gets.
labelListList of sets of faces to combine. Does no check for whether resulting face is legal.
Definition at line 584 of file combineFaces.C.
Referenced by meshRefinement::mergePatchFaces(), and meshRefinement::mergePatchFacesUndo().
void updateMesh (const mapPolyMesh & map)
Force recalculation of locally stored data on topological change.
Definition at line 809 of file combineFaces.C.
Referenced by meshRefinement::mergePatchFaces(), and meshRefinement::mergePatchFacesUndo().
void setUnrefinement (const labelList & masterFaces, polyTopoChange & meshMod, Map< label > & restoredPoints, Map< label > & restoredFaces, Map< label > & restoredCells)
Play commands into polyTopoChange to reinsert original faces.
No other topo changes can be done inbetween setRefinement and setUnrefinement. Can be called multiple times to undo parts of the last setRefinement call. Gets the master face labels whose sets need to be restored. Returns maps from added restored point to original point label (i.e. content of savedPointLabels_). (only restoredPoints are actually set; rest are just for generalness). See note above about restoring faces from different patches (mergeAcrossPatches)
Definition at line 858 of file combineFaces.C.
References Foam::abort(), UList< T >::empty(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, faceZone::flipMap(), forAll, i, HashTable< T, Key, Hash >::insert(), iter, polyTopoChange::setAction(), UList< T >::size(), faceZone::whichFace(), and zoneID.
Referenced by meshRefinement::mergePatchFacesUndo().
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/combineFaces.H
src/dynamicMesh/polyTopoChange/polyTopoChange/combineFaces.C