OpenFOAM: vtuAdaptor Class Reference
vtuAdaptor Class Reference
Bookkeeping for vtkUnstructuredGrid.
Public Member Functions
vtkSmartPointer< vtkPoints > points (const fvMesh &mesh) const
The vtk points for the mesh (and decomposition)
vtkSmartPointer< vtkPoints > points (const fvMesh &mesh, const labelUList &pointMap) const
The vtk points for the mesh (and decomposition) using the provided pointMap.
vtkSmartPointer
< vtkUnstructuredGrid > internal (const fvMesh &mesh, const bool decompPoly=false)
Internal mesh as vtkUnstructuredGrid.
template<class Type >
vtkSmartPointer< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > &fld) const
Convert internal volume field (CellData)
template<class Type >
vtkSmartPointer< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > &fld) const
Convert internal volume field (CellData)
Public Member Functions inherited from Caching< vtkUnstructuredGrid >
uint64_t nPoints () const
Number of points associated with the geometry.
void clearGeom ()
Clear geometry and dataset.
vtkSmartPointer< dataType > getCopy () const
Return a shallow copy of vtkgeom for manipulation.
void reuse ()
Make a shallow copy of vtkgeom into dataset.
void set (vtkSmartPointer< dataType > geom)
Set the geometry and make a shallow copy to dataset.
void PrintSelf (std::ostream &os) const
Report basic information to output.
Public Member Functions inherited from foamVtkMeshMaps
foamVtkMeshMaps (const label size=0)
Construct null.
~foamVtkMeshMaps ()=default
Destructor.
const labelList & cellMap () const
Original cell ids for all cells (regular and decomposed).
const labelList & pointMap () const
Point labels for subsetted meshes.
const labelList & additionalIds () const
Any additional (user) labels.
void clear ()
Clear.
void renumberCells (const labelUList &mapping)
Renumber cell ids (cellMap and additionalIds) to account for.
void renumberPoints (const labelUList &mapping)
Renumber point ids (pointMap) to account for subset meshes.
DynamicList< label > & cellMap ()
Original cell ids for all cells (regular and decomposed).
DynamicList< label > & pointMap ()
Point labels for subsetted meshes.
DynamicList< label > & additionalIds ()
Any additional (user) labels.
Static Public Member Functions
template<class Type >
static vtkSmartPointer
< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > &fld, const vtuAdaptor &vtuData)
Convert internal volume field (CellData)
template<class Type >
static vtkSmartPointer
< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > &fld, const vtuAdaptor &vtuData)
Convert internal volume field (CellData)
Additional Inherited Members
Public Types inherited from Caching< vtkUnstructuredGrid >
typedef vtkUnstructuredGrid dataType
Public Attributes inherited from Caching< vtkUnstructuredGrid >
vtkSmartPointer< dataType > vtkgeom
The geometry, without any cell/point data.
vtkSmartPointer< dataType > dataset
The shallow-copy of geometry, plus additional data.
Detailed Description
Bookkeeping for vtkUnstructuredGrid.
A low-level backend adaptor for converting OpenFOAM volume meshes/fields to VTK internal representation. The output is a single piece vtkUnstructuredGrid dataset. Multiblock composition is done by the caller.
Note
This was originally part of the catalystFvMesh function object backend, which was prototyped in the ParaView reader module. This adaptor unifies many common elements of both.
Source files
foamVtkVtuAdaptor.H
foamVtkVtuAdaptorI.H
foamVtkVtuAdaptorTemplates.C
Definition at line 76 of file foamVtkVtuAdaptor.H.
Member Function Documentation
vtkSmartPointer< vtkPoints > points (const fvMesh & mesh) const inline
The vtk points for the mesh (and decomposition)
Definition at line 25 of file foamVtkVtuAdaptorI.H.
References foamVtkMeshMaps::additionalIds(), primitiveMesh::cellCentres(), Foam::New(), p, polyMesh::points(), and UList< T >::size().
vtkSmartPointer< vtkPoints > points (const fvMesh & mesh, const labelUList & pointMap) const inline
The vtk points for the mesh (and decomposition) using the provided pointMap.
Definition at line 59 of file foamVtkVtuAdaptorI.H.
vtkSmartPointer< vtkUnstructuredGrid > internal (const fvMesh & mesh, const bool decompPoly = false) inline
Internal mesh as vtkUnstructuredGrid.
Calling this automatically populates the sizing and vtk::Caching
Definition at line 94 of file foamVtkVtuAdaptorI.H.
vtkSmartPointer< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > & fld, const vtuAdaptor & vtuData) static
Convert internal volume field (CellData)
Definition at line 32 of file foamVtkVtuAdaptorTemplates.C.
References foamVtkMeshMaps::cellMap(), Foam::vtk::Tools::foamToVtkTuple(), IOobject::name(), Foam::New(), and UList< T >::size().
vtkSmartPointer< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > & fld, const vtuAdaptor & vtuData) static
Convert internal volume field (CellData)
Definition at line 69 of file foamVtkVtuAdaptorTemplates.C.
vtkSmartPointer< vtkFloatArray > convertField (const DimensionedField< Type, volMesh > & fld) const
Convert internal volume field (CellData)
Definition at line 81 of file foamVtkVtuAdaptorTemplates.C.
vtkSmartPointer< vtkFloatArray > convertField (const GeometricField< Type, fvPatchField, volMesh > & fld) const
Convert internal volume field (CellData)
Definition at line 92 of file foamVtkVtuAdaptorTemplates.C.
The documentation for this class was generated from the following files:
src/conversion/vtk/adaptor/foamVtkVtuAdaptor.H
src/conversion/vtk/adaptor/foamVtkVtuAdaptorI.H
src/conversion/vtk/adaptor/foamVtkVtuAdaptorTemplates.C