OpenFOAM: correctedLnGrad< Type > Class Template Reference
correctedLnGrad< Type > Class Template Reference
Simple central-difference lnGrad scheme with non-orthogonal correction.
Public Member Functions
TypeName ("corrected")
Runtime type information.
correctedLnGrad (const faMesh &mesh)
Construct from mesh.
correctedLnGrad (const faMesh &mesh, Istream &)
Construct from mesh and data stream.
virtual ~correctedLnGrad ()
Destructor.
virtual tmp< edgeScalarField > deltaCoeffs (const GeometricField< Type, faPatchField, areaMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField
< Type, faePatchField,
edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > &) const
Return the explicit correction to the correctedLnGrad.
Public Member Functions inherited from lnGradScheme< Type >
declareRunTimeSelectionTable (tmp, lnGradScheme, Mesh,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
lnGradScheme (const faMesh &mesh)
Construct from mesh.
virtual ~lnGradScheme ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, faePatchField,
edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &) const
Return the lnGrad of the given cell field.
tmp< GeometricField< Type,
faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &) const
Return the lnGrad of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from lnGradScheme< Type >
static tmp< lnGradScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &, const tmp< edgeScalarField > &, const word &snGradName="lnGrad")
Return the lnGrad of the given cell field.
Detailed Description
template<class Type>
class Foam::fa::correctedLnGrad< Type >
Simple central-difference lnGrad scheme with non-orthogonal correction.
Source files
correctedLnGrad.H
correctedLnGrad.C
Definition at line 52 of file correctedLnGrad.H.
Constructor & Destructor Documentation
correctedLnGrad (const faMesh & mesh) inline
Construct from mesh.
Definition at line 77 of file correctedLnGrad.H.
correctedLnGrad (const faMesh & mesh, Istream &) inline
Construct from mesh and data stream.
Definition at line 86 of file correctedLnGrad.H.
~correctedLnGrad () virtual
Destructor.
Definition at line 40 of file correctedLnGrad.C.
Member Function Documentation
TypeName ("corrected")
Runtime type information.
virtual tmp<edgeScalarField> deltaCoeffs (const GeometricField< Type, faPatchField, areaMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements lnGradScheme< Type >.
Definition at line 104 of file correctedLnGrad.H.
References lnGradScheme< Type >::mesh(), and edgeInterpolation::orthogonal().
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from lnGradScheme< Type >.
Definition at line 114 of file correctedLnGrad.H.
tmp< GeometricField< Type, faePatchField, edgeMesh > > correction (const GeometricField< Type, faPatchField, areaMesh > & vf) const virtual
Return the explicit correction to the correctedLnGrad.
for the given field
Reimplemented from lnGradScheme< Type >.
Definition at line 49 of file correctedLnGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::component(), edgeInterpolation::correctionVectors(), IOobject::db(), edgeInterpolation::deltaCoeffs(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fac::grad(), faSchemes::gradScheme(), IOobject::instance(), Foam::interpolate(), mesh, IOobject::name(), Foam::New(), tmp< T >::ref(), GeometricField< Type, PatchField, GeoMesh >::replace(), and Foam::type().
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/lnGradSchemes/correctedLnGrad/correctedLnGrad.H
src/finiteArea/finiteArea/lnGradSchemes/correctedLnGrad/correctedLnGrad.C