OpenFOAM: dynamicCode Class Reference
dynamicCode Class Reference
Tools for handling dynamic code compilation.
Public Types
typedef Tuple2< fileName, string > fileAndContent
Public Member Functions
dynamicCode (const word &codeName, const word &codeDirName="")
Construct for a specified code name and code directory name.
const word & codeName () const
Return the code-name.
const word & codeDirName () const
Return the code-dirname.
const fileName & codeRoot () const
Root for dynamic code compilation.
fileName libSubDir () const
Subdirectory name for loading libraries.
fileName codePath () const
Path for specified code name.
fileName codeRelPath () const
Path for specified code name relative to <case>
fileName libPath () const
Library path for specified code name.
fileName libRelPath () const
Library path for specified code name relative to <case>
fileName digestFile () const
Path for SHA1Digest.
void clear ()
Clear files and variables.
void reset (const dynamicCodeContext &)
Clear files and reset variables to specified context.
void addCompileFile (const fileName &name)
Add a file template name, which will be found and filtered.
void addCopyFile (const fileName &name)
Add a file template name, which will be found and filtered.
void addCreateFile (const fileName &name, const string &contents)
Add a file to create with its contents. Will not be filtered.
void setFilterContext (const dynamicCodeContext &)
Define filter variables for code, codeInclude, SHA1sum.
void setFilterVariable (const word &key, const std::string &value)
Define a filter variable.
void setMakeOptions (const std::string &content)
Define contents for Make/options.
bool upToDate (const dynamicCodeContext &context) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
bool upToDate (const SHA1Digest &sha1) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
bool copyOrCreateFiles (const bool verbose=false) const
Copy/create files prior to compilation.
bool wmakeLibso () const
Compile a libso.
template<class Type >
void setFieldTemplates ()
Define a filter variables TemplateType and FieldType.
Static Public Member Functions
static void checkSecurity (const char *title, const dictionary &)
Check security for creating dynamic code.
static word libraryBaseName (const fileName &libPath)
Return the library basename without leading 'lib' or trailing '.so'.
Static Public Attributes
static const word codeTemplateEnvName = "FOAM_CODE_TEMPLATES"
Name of the code template environment variable.
static const fileName codeTemplateDirName = "codeTemplates/dynamicCode"
Name of the code template sub-directory.
static int allowSystemOperations
Flag if system operations are allowed.
Protected Member Functions
bool writeCommentSHA1 (Ostream &) const
Write SHA1 value as C-comment.
bool createMakeFiles () const
Copy/create Make/files prior to compilation.
bool createMakeOptions () const
Copy/create Make/options prior to compilation.
bool writeDigest (const SHA1Digest &) const
Write digest to Make/SHA1Digest.
bool writeDigest (const std::string &) const
Write digest to Make/SHA1Digest.
Static Protected Member Functions
static void copyAndFilter (ISstream &, OSstream &, const HashTable< string > &mapping)
Copy lines while expanding variables.
static bool resolveTemplates (const UList< fileName > &templateNames, DynamicList< fileName > &resolvedFiles, DynamicList< fileName > &badFiles)
Resolve code-templates via the codeTemplateEnvName.
Static Protected Attributes
static const char *const libTargetRoot
Root of the LIB target for Make/files.
static const char *const topDirName = "dynamicCode"
Top-level directory name for copy/compiling.
Detailed Description
Tools for handling dynamic code compilation.
Source files
dynamicCode.H
dynamicCode.C
Definition at line 55 of file dynamicCode.H.
Member Typedef Documentation
typedef Tuple2<fileName, string> fileAndContent
Definition at line 58 of file dynamicCode.H.
Constructor & Destructor Documentation
dynamicCode (const word & codeName, const word & codeDirName = "")
Construct for a specified code name and code directory name.
Defaults to using the code name for the code directory name
Definition at line 298 of file dynamicCode.C.
Member Function Documentation
void copyAndFilter (ISstream & is, OSstream & os, const HashTable< string > & mapping) static protected
Copy lines while expanding variables.
Definition at line 110 of file dynamicCode.C.
bool resolveTemplates (const UList< fileName > & templateNames, DynamicList< fileName > & resolvedFiles, DynamicList< fileName > & badFiles) static protected
Resolve code-templates via the codeTemplateEnvName.
alternatively in the codeTemplateDirName via Foam::findEtcFile
Definition at line 147 of file dynamicCode.C.
bool writeCommentSHA1 (Ostream & os) const protected
Write SHA1 value as C-comment.
Definition at line 190 of file dynamicCode.C.
bool createMakeFiles () const protected
Copy/create Make/files prior to compilation.
Definition at line 205 of file dynamicCode.C.
bool createMakeOptions () const protected
Copy/create Make/options prior to compilation.
Definition at line 242 of file dynamicCode.C.
bool writeDigest (const SHA1Digest & sha1) const protected
Write digest to Make/SHA1Digest.
Definition at line 271 of file dynamicCode.C.
bool writeDigest (const std::string & sha1) const protected
Write digest to Make/SHA1Digest.
Definition at line 283 of file dynamicCode.C.
void checkSecurity (const char * title, const dictionary & dict) static
Check security for creating dynamic code.
Definition at line 65 of file dynamicCode.C.
References dynamicCode::allowSystemOperations, Foam::foamVersion::api, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, Foam::isAdministrator(), and Foam::nl.
Referenced by codeStream::evaluate().
Foam::word libraryBaseName (const fileName & libPath) static
Return the library basename without leading 'lib' or trailing '.so'.
Definition at line 99 of file dynamicCode.C.
const word& codeName () const inline
Return the code-name.
Definition at line 244 of file dynamicCode.H.
const word& codeDirName () const inline
Return the code-dirname.
Definition at line 252 of file dynamicCode.H.
const fileName& codeRoot () const inline
Root for dynamic code compilation.
Expanded from <case>/dynamicCode
Definition at line 262 of file dynamicCode.H.
fileName libSubDir () const inline
Subdirectory name for loading libraries.
Expanded from platforms/$WM_OPTIONS/lib
Definition at line 272 of file dynamicCode.H.
fileName codePath () const inline
Path for specified code name.
Corresponds to codeRoot()/codeDirName()
Definition at line 282 of file dynamicCode.H.
References dynamicCode::setFilterVariable(), and Foam::val.
Foam::fileName codeRelPath () const
Path for specified code name relative to <case>
Corresponds to topDirName/codeDirName()
Definition at line 316 of file dynamicCode.C.
Foam::fileName libPath () const
Library path for specified code name.
Corresponds to codeRoot()/libSubDir()/lib<codeName>.so
Definition at line 322 of file dynamicCode.C.
Foam::fileName libRelPath () const
Library path for specified code name relative to <case>
Corresponds to dynamicCode/codeDirName()/libSubDir()/lib<codeName>.so
Definition at line 328 of file dynamicCode.C.
References EXT_SO.
fileName digestFile () const inline
Path for SHA1Digest.
Corresponds to codePath()/Make/SHA1Digest
Definition at line 315 of file dynamicCode.H.
void clear ()
Clear files and variables.
Definition at line 334 of file dynamicCode.C.
References EXT_SO.
void reset (const dynamicCodeContext & context)
Clear files and reset variables to specified context.
Definition at line 351 of file dynamicCode.C.
void addCompileFile (const fileName & name)
Add a file template name, which will be found and filtered.
Definition at line 360 of file dynamicCode.C.
References clear().
Referenced by CodedSource< Type >::prepare().
void addCopyFile (const fileName & name)
Add a file template name, which will be found and filtered.
Definition at line 366 of file dynamicCode.C.
Referenced by CodedSource< Type >::prepare().
void addCreateFile (const fileName & name, const string & contents)
Add a file to create with its contents. Will not be filtered.
Definition at line 373 of file dynamicCode.C.
void setFilterContext (const dynamicCodeContext & context)
Define filter variables for code, codeInclude, SHA1sum.
Definition at line 383 of file dynamicCode.C.
void setFilterVariable (const word & key, const std::string & value)
Define a filter variable.
Definition at line 395 of file dynamicCode.C.
Referenced by dynamicCode::codePath(), and CodedSource< Type >::prepare().
void setMakeOptions (const std::string & content)
Define contents for Make/options.
Definition at line 404 of file dynamicCode.C.
Referenced by CodedSource< Type >::prepare().
bool upToDate (const dynamicCodeContext & context) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
Definition at line 543 of file dynamicCode.C.
bool upToDate (const SHA1Digest & sha1) const
Verify if the copied code is up-to-date, based on Make/SHA1Digest.
Definition at line 530 of file dynamicCode.C.
bool copyOrCreateFiles (const bool verbose = false) const
Copy/create files prior to compilation.
Definition at line 410 of file dynamicCode.C.
bool wmakeLibso () const
Compile a libso.
Definition at line 502 of file dynamicCode.C.
void setFieldTemplates () inline
Define a filter variables TemplateType and FieldType.
Definition at line 390 of file dynamicCode.H.
Member Data Documentation
const char *const libTargetRoot static protected
Initial value:
=
    "LIB = $(PWD)/../platforms/$(WM_OPTIONS)/lib/lib"
Root of the LIB target for Make/files.
Definition at line 129 of file dynamicCode.H.
const char *const topDirName = "dynamicCode" static protected
Top-level directory name for copy/compiling.
Definition at line 134 of file dynamicCode.H.
const Foam::word codeTemplateEnvName = "FOAM_CODE_TEMPLATES" static
Name of the code template environment variable.
Used to located the codeTemplateName
Definition at line 197 of file dynamicCode.H.
const Foam::fileName codeTemplateDirName = "codeTemplates/dynamicCode" static
Name of the code template sub-directory.
Used when locating the codeTemplateName via Foam::findEtcFile
Definition at line 204 of file dynamicCode.H.
int allowSystemOperations static
Flag if system operations are allowed.
Definition at line 209 of file dynamicCode.H.
Referenced by dynamicCode::checkSecurity().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCode.H
src/OpenFOAM/db/dynamicLibrary/dynamicCode/dynamicCode.C