OpenFOAM: WallInteractionModel< CloudType > Class Template Reference
WallInteractionModel< CloudType > Class Template Reference abstract
Templated wall interaction model class.
Public Member Functions
TypeName ("WallInteractionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, WallInteractionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
WallInteractionModel (CloudType &owner)
Construct null from owner.
WallInteractionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~WallInteractionModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
virtual void correct (typename CloudType::parcelType &p)=0
Apply wall correction.
Static Public Member Functions
static autoPtr
< WallInteractionModel
< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::WallInteractionModel< CloudType >
Templated wall interaction model class.
Source files
WallInteractionModel.H
WallInteractionModel.C
WallInteractionModelNew.C
Definition at line 57 of file DSMCCloud.H.
Constructor & Destructor Documentation
WallInteractionModel (CloudType & owner)
Construct null from owner.
Definition at line 26 of file WallInteractionModel.C.
WallInteractionModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 36 of file WallInteractionModel.C.
~WallInteractionModel () virtual
Destructor.
Definition at line 51 of file WallInteractionModel.C.
Member Function Documentation
TypeName ("WallInteractionModel< CloudType >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , WallInteractionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::WallInteractionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 29 of file WallInteractionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
const CloudType & owner () const
Return the owner cloud object.
Definition at line 58 of file WallInteractionModel.C.
CloudType & owner ()
Return non-const access to the owner cloud object.
Definition at line 65 of file WallInteractionModel.C.
const Foam::dictionary & dict () const
Return the dictionary.
Definition at line 72 of file WallInteractionModel.C.
const Foam::dictionary & coeffDict () const
Return the coefficients dictionary.
Definition at line 80 of file WallInteractionModel.C.
virtual void correct (typename CloudType::parcelType & p) pure virtual
Apply wall correction.
Implemented in MixedDiffuseSpecular< CloudType >, MaxwellianThermal< CloudType >, and SpecularReflection< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/clouds/Templates/DSMCCloud/DSMCCloud.H
src/lagrangian/DSMC/submodels/WallInteractionModel/WallInteractionModel/WallInteractionModel.H
src/lagrangian/DSMC/submodels/WallInteractionModel/WallInteractionModel/WallInteractionModel.C
src/lagrangian/DSMC/submodels/WallInteractionModel/WallInteractionModel/WallInteractionModelNew.C