OpenFOAM: GAMGInterface Class Reference
GAMGInterface Class Reference abstract
Abstract base class for GAMG agglomerated interfaces.
Public Member Functions
TypeName ("GAMGInterface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, GAMGInterface, lduInterface,(const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm),(index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr, GAMGInterface, Istream,(const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is),(index, coarseInterfaces, is))
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces)
Construct from interfaces, restrict addressing set later on.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, const labelUList &faceCells, const labelUList &faceRestrictAddressing)
Construct from interfaces and restrict addressing.
GAMGInterface (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Construct from Istream.
virtual label size () const
Return size.
virtual label index () const
virtual const
lduInterfacePtrsList & coarseInterfaces () const
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual const labelList & faceRestrictAddressing () const
Return (local)face restrict addressing.
virtual labelList & faceRestrictAddressing ()
Return non-const access to face restrict addressing.
template<class Type >
tmp< Field< Type > > interfaceInternalField (const UList< Type > &internalData) const
Return the interface internal field of the given field.
template<class Type >
void interfaceInternalField (const UList< Type > &internalData, List< Type > &) const
Get the interface internal field of the given field.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
void combine (const GAMGInterface &)
Merge the next level with this level.
virtual tmp< scalarField > agglomerateCoeffs (const scalarField &fineCoeffs) const
Agglomerating the given fine-level coefficients and return.
virtual void write (Ostream &) const =0
Write to stream.
template<class Type >
Foam::tmp< Foam::Field< Type > > interfaceInternalField (const UList< Type > &iF) const
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()=default
Construct null.
virtual ~lduInterface ()=default
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const =0
Transfer and return internal field adjacent to the interface.
Static Public Member Functions
static autoPtr< GAMGInterface > New (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm)
Return a pointer to a new interface created on freestore given.
static autoPtr< GAMGInterface > New (const word &coupleType, const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is)
Return a pointer to a new interface created on freestore given.
Protected Attributes
const label index_
My index in coarseInterfaces.
const lduInterfacePtrsList & coarseInterfaces_
All interfaces.
labelList faceCells_
Face-cell addressing.
labelList faceRestrictAddressing_
Face restrict addressing.
Detailed Description
Abstract base class for GAMG agglomerated interfaces.
Source files
GAMGInterface.H
GAMGInterface.C
newAmgInterface.C
Definition at line 49 of file GAMGInterface.H.
Constructor & Destructor Documentation
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces) inline
Construct from interfaces, restrict addressing set later on.
Definition at line 185 of file GAMGInterface.H.
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, const labelUList & faceCells, const labelUList & faceRestrictAddressing) inline
Construct from interfaces and restrict addressing.
Definition at line 199 of file GAMGInterface.H.
GAMGInterface (const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is)
Construct from Istream.
Definition at line 36 of file GAMGInterface.C.
Member Function Documentation
TypeName ("GAMGInterface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , GAMGInterface , lduInterface , (const label index, const lduInterfacePtrsList &coarseInterfaces, const lduInterface &fineInterface, const labelField &localRestrictAddressing, const labelField &neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm) , (index, coarseInterfaces, fineInterface, localRestrictAddressing, neighbourRestrictAddressing, fineLevelIndex, coarseComm))
declareRunTimeSelectionTable (autoPtr , GAMGInterface , Istream , (const label index, const lduInterfacePtrsList &coarseInterfaces, Istream &is) , (index, coarseInterfaces, is))
Foam::autoPtr< Foam::GAMGInterface > New (const label index, const lduInterfacePtrsList & coarseInterfaces, const lduInterface & fineInterface, const labelField & localRestrictAddressing, const labelField & neighbourRestrictAddressing, const label fineLevelIndex, const label coarseComm) static
Return a pointer to a new interface created on freestore given.
the fine interface
Definition at line 30 of file GAMGInterfaceNew.C.
References GAMGInterface::coarseInterfaces(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, and GAMGInterface::index().
Referenced by GAMGAgglomeration::agglomerateLduAddressing().
Foam::autoPtr< Foam::GAMGInterface > New (const word & coupleType, const label index, const lduInterfacePtrsList & coarseInterfaces, Istream & is) static
Return a pointer to a new interface created on freestore given.
the fine interface
Definition at line 71 of file GAMGInterfaceNew.C.
virtual label size () const inline virtual
Return size.
Definition at line 231 of file GAMGInterface.H.
References GAMGInterface::faceRestrictAddressing_.
Referenced by GAMGInterface::interfaceInternalField().
virtual label index () const inline virtual
Definition at line 236 of file GAMGInterface.H.
References GAMGInterface::faceRestrictAddressing_.
Referenced by GAMGInterface::New().
virtual const lduInterfacePtrsList& coarseInterfaces () const inline virtual
Definition at line 241 of file GAMGInterface.H.
Referenced by GAMGInterface::New().
virtual const labelUList& faceCells () const inline virtual
Return faceCell addressing.
Implements lduInterface.
Definition at line 249 of file GAMGInterface.H.
virtual const labelList& faceRestrictAddressing () const inline virtual
Return (local)face restrict addressing.
Definition at line 257 of file GAMGInterface.H.
virtual labelList& faceRestrictAddressing () inline virtual
Return non-const access to face restrict addressing.
Definition at line 265 of file GAMGInterface.H.
tmp<Field<Type> > interfaceInternalField (const UList< Type > & internalData) const
Return the interface internal field of the given field.
void interfaceInternalField (const UList< Type > & internalData, List< Type > & result) const
Get the interface internal field of the given field.
Definition at line 39 of file GAMGInterfaceTemplates.C.
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements lduInterface.
Definition at line 65 of file GAMGInterface.C.
void combine (const GAMGInterface & coarseGi)
Merge the next level with this level.
combining the face-restrict addressing and copying the face-cell addressing
Definition at line 51 of file GAMGInterface.C.
Foam::tmp< Foam::scalarField > agglomerateCoeffs (const scalarField & fineCoeffs) const virtual
Agglomerating the given fine-level coefficients and return.
Definition at line 74 of file GAMGInterface.C.
void write (Ostream & os) const pure virtual
Write to stream.
Implemented in calculatedProcessorGAMGInterface, processorGAMGInterface, cyclicGAMGInterface, cyclicACMIGAMGInterface, and cyclicAMIGAMGInterface.
Definition at line 107 of file GAMGInterface.C.
Foam::tmp<Foam::Field<Type> > interfaceInternalField (const UList< Type > & iF) const
Definition at line 27 of file GAMGInterfaceTemplates.C.
References GAMGInterface::size().
Member Data Documentation
const label index_ protected
My index in coarseInterfaces.
Definition at line 61 of file GAMGInterface.H.
const lduInterfacePtrsList& coarseInterfaces_ protected
All interfaces.
Definition at line 66 of file GAMGInterface.H.
labelList faceCells_ protected
Face-cell addressing.
Definition at line 71 of file GAMGInterface.H.
labelList faceRestrictAddressing_ protected
Face restrict addressing.
Definition at line 76 of file GAMGInterface.H.
Referenced by GAMGInterface::index(), and GAMGInterface::size().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterface.H
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterface.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterfaceNew.C
src/OpenFOAM/matrices/lduMatrix/solvers/GAMG/interfaces/GAMGInterface/GAMGInterfaceTemplates.C