OpenFOAM: UIListStreamAllocator Class Reference
UIListStreamAllocator Class Reference
An stream/stream-buffer input allocator for a externally allocated list.
Public Member Functions
const UList< char > list () const
Const UList access to the input characters (shallow copy).
UList< char > list ()
Non-const UList access to the input characters (shallow copy).
label size () const
The list size.
std::streampos tellg () const
Position of the get buffer.
void rewind ()
Move to buffer start, clear errors.
Protected Types
typedef std::istream stream_type
Protected Member Functions
UIListStreamAllocator (char *buffer, size_t nbytes)
Construct for character array and number of bytes.
void reset (char *buffer, size_t nbytes)
Reset buffer pointers.
void printBufInfo (Ostream &os) const
Protected Attributes
memorybuf::in buf_
The stream buffer.
stream_type stream_
The stream.
Detailed Description
An stream/stream-buffer input allocator for a externally allocated list.
Definition at line 126 of file UIListStream.H.
Member Typedef Documentation
typedef std::istream stream_type protected
Definition at line 132 of file UIListStream.H.
Constructor & Destructor Documentation
UIListStreamAllocator (char * buffer, size_t nbytes) inline protected
Construct for character array and number of bytes.
Definition at line 150 of file UIListStream.H.
References UIListStreamAllocator::buf_, and memorybuf::in::resetg().
Member Function Documentation
void reset (char * buffer, size_t nbytes) inline protected
Reset buffer pointers.
Definition at line 162 of file UIListStream.H.
void printBufInfo (Ostream & os) const inline protected
Definition at line 167 of file UIListStream.H.
Referenced by UIListStream::print().
const UList<char> list () const inline
Const UList access to the input characters (shallow copy).
Definition at line 179 of file UIListStream.H.
UList<char> list () inline
Non-const UList access to the input characters (shallow copy).
Definition at line 187 of file UIListStream.H.
References UIListStreamAllocator::buf_, and UIListStreamAllocator::stream_.
label size () const inline
The list size.
Definition at line 195 of file UIListStream.H.
std::streampos tellg () const inline
Position of the get buffer.
Definition at line 203 of file UIListStream.H.
Referenced by IListStream::IListStream(), and UIListStream::UIListStream().
void rewind () inline
Move to buffer start, clear errors.
Definition at line 211 of file UIListStream.H.
Member Data Documentation
memorybuf::in buf_ protected
The stream buffer.
Definition at line 137 of file UIListStream.H.
Referenced by UIListStreamAllocator::list(), and UIListStreamAllocator::UIListStreamAllocator().
stream_type stream_ protected
The stream.
Definition at line 142 of file UIListStream.H.
Referenced by UIListStreamAllocator::list().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/UIListStream.H