OpenFOAM: convectionScheme< Type > Class Template Reference
convectionScheme< Type > Class Template Reference abstract
Convection schemes
Abstract base class for convection schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp, convectionScheme, Multivariate,(const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, fields, faceFlux, schemeData))
convectionScheme (const convectionScheme &)
Copy construct.
convectionScheme (const fvMesh &mesh, const surfaceScalarField &)
Construct from mesh, flux and Istream.
virtual ~convectionScheme ()
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > flux (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< fvMatrix< Type > > fvmDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcDiv (const surfaceScalarField &, const GeometricField< Type, fvPatchField, volMesh > &) const =0
void operator= (const convectionScheme< Type > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< convectionScheme
< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new convectionScheme created on freestore.
static tmp< convectionScheme
< Type > > New (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new multivariate convectionScheme.
Detailed Description
template<class Type>
class Foam::fv::convectionScheme< Type >
Abstract base class for convection schemes.
Source files
convectionScheme.H
convectionScheme.C
Definition at line 65 of file convectionScheme.H.
Constructor & Destructor Documentation
convectionScheme (const convectionScheme< Type > & cs)
Copy construct.
Definition at line 44 of file convectionScheme.C.
convectionScheme (const fvMesh & mesh, const surfaceScalarField &) inline
Construct from mesh, flux and Istream.
Definition at line 124 of file convectionScheme.H.
~convectionScheme () virtual
Destructor.
Definition at line 145 of file convectionScheme.C.
Member Function Documentation
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Istream , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Multivariate , (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, fields, faceFlux, schemeData))
tmp< convectionScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return a pointer to a new convectionScheme created on freestore.
Definition at line 55 of file convectionScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, and InfoInFunction.
Referenced by Foam::fvm::div(), and Foam::fvc::flux().
tmp< convectionScheme< Type > > New (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return a pointer to a new multivariate convectionScheme.
created on freestore
Definition at line 101 of file convectionScheme.C.
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 172 of file convectionScheme.H.
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > interpolate (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > flux (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
virtual tmp<fvMatrix<Type> > fvmDiv (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
Referenced by forAll().
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcDiv (const surfaceScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >, boundedConvectionScheme< Type >, and multivariateGaussConvectionScheme< Type >.
void operator= (const convectionScheme< Type > & cs)
Definition at line 152 of file convectionScheme.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/convectionSchemes/convectionScheme/convectionScheme.H
src/finiteVolume/finiteVolume/convectionSchemes/convectionScheme/convectionScheme.C