OpenFOAM: extendedEdgeMesh Class Reference
extendedEdgeMesh Class Reference
Description of feature edges and points.
Public Types
enum pointStatus { CONVEX, CONCAVE, MIXED, NONFEATURE }
enum edgeStatus {
EXTERNAL, INTERNAL, FLAT, OPEN,
MULTIPLE, NONE
}
enum sideVolumeType { INSIDE = 0, OUTSIDE = 1, BOTH = 2, NEITHER = 3 }
Normals point to the outside.
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef faMesh::BoundaryMesh BoundaryMesh
Public Member Functions
TypeName ("extendedEdgeMesh")
Runtime type information.
extendedEdgeMesh ()
Construct null.
extendedEdgeMesh (const extendedEdgeMesh &fem)
Construct as copy.
extendedEdgeMesh (const fileName &)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (const fileName &, const word &ext)
Construct from file name (uses extension to determine type)
extendedEdgeMesh (Istream &is)
Construct from Istream.
extendedEdgeMesh (const pointField &points, const edgeList &edges)
Copy construct from components.
extendedEdgeMesh (pointField &&points, edgeList &&edges)
Move construct from components.
extendedEdgeMesh (const surfaceFeatures &sFeat, const boolList &surfBaffleRegions)
Construct given a surface with selected edges,points.
extendedEdgeMesh (const PrimitivePatch< face, List, pointField, point > &surf, const labelUList &featureEdges, const labelUList &regionFeatureEdges, const labelUList &featurePoints)
Construct from PrimitivePatch.
extendedEdgeMesh (const pointField &pts, const edgeList &eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField &normals, const List< sideVolumeType > &normalVolumeTypes, const vectorField &edgeDirections, const labelListList &normalDirections, const labelListList &edgeNormals, const labelListList &featurePointNormals, const labelListList &featurePointEdges, const labelList &regionEdges)
Construct from all components.
declareRunTimeSelectionTable (autoPtr, extendedEdgeMesh, fileExtension,(const fileName &name),(name))
~extendedEdgeMesh ()
Destructor.
void nearestFeaturePoint (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const point &sample, scalar searchDistSqr, pointIndexHit &info) const
Find nearest surface edge for the sample point.
void nearestFeatureEdge (const pointField &samples, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find nearest surface edge for each sample point.
void nearestFeatureEdgeByType (const point &sample, const scalarField &searchDistSqr, List< pointIndexHit > &info) const
Find the nearest point on each type of feature edge.
void allNearestFeaturePoints (const point &sample, scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature points within searchDistSqr of sample.
void allNearestFeatureEdges (const point &sample, const scalar searchRadiusSqr, List< pointIndexHit > &info) const
Find all the feature edges within searchDistSqr of sample.
label convexStart () const
Return the index of the start of the convex feature points.
label concaveStart () const
Return the index of the start of the concave feature points.
label mixedStart () const
Return the index of the start of the mixed type feature points.
label nonFeatureStart () const
Return the index of the start of the non-feature points.
label externalStart () const
Return the index of the start of the external feature edges.
label internalStart () const
Return the index of the start of the internal feature edges.
label flatStart () const
Return the index of the start of the flat feature edges.
label openStart () const
Return the index of the start of the open feature edges.
label multipleStart () const
Return the index of the start of the multiply-connected feature.
bool featurePoint (label ptI) const
Return whether or not the point index is a feature point.
const vectorField & normals () const
Return the normals of the surfaces adjacent to the feature edges.
const List< sideVolumeType > & normalVolumeTypes () const
Return.
const vectorField & edgeDirections () const
Return the edgeDirection vectors.
const labelListList & normalDirections () const
vector edgeDirection (label edgeI, label ptI) const
Return the direction of edgeI, pointing away from ptI.
const labelListList & edgeNormals () const
Return the indices of the normals that are adjacent to the.
vectorField edgeNormals (const labelList &edgeNormIs) const
Return the normal vectors for a given set of normal indices.
vectorField edgeNormals (label edgeI) const
Return the normal vectors for a given edge.
const labelListList & featurePointNormals () const
Return the indices of the normals that are adjacent to the.
vectorField featurePointNormals (label ptI) const
Return the normal vectors for a given feature point.
const labelListList & featurePointEdges () const
Return the edge labels for a given feature point. Edges are.
const labelList & regionEdges () const
Return the feature edges which are on the boundary between.
pointStatus getPointStatus (label ptI) const
Return the pointStatus of a specified point.
edgeStatus getEdgeStatus (label edgeI) const
Return the edgeStatus of a specified edge.
PackedList< 2 > edgeBaffles (label edgeI) const
Return the baffle faces of a specified edge.
const indexedOctree
< treeDataPoint > & pointTree () const
Demand driven construction of octree for feature points.
const indexedOctree
< treeDataEdge > & edgeTree () const
Demand driven construction of octree for boundary edges.
const PtrList< indexedOctree
< treeDataEdge > > & edgeTreesByType () const
Demand driven construction of octree for boundary edges by type.
void transfer (extendedEdgeMesh &mesh)
Transfer the contents of the argument and annul the argument.
virtual void clear ()
Clear all storage.
void add (const extendedEdgeMesh &fem)
Add extendedEdgeMesh. No filtering of duplicates.
void flipNormals ()
Flip normals. All concave become convex, all internal external.
void autoMap (const pointField &subPoints, const edgeList &subEdges, const labelList &pointMap, const labelList &edgeMap)
Update with derived geometry.
void trim (const searchableSurface &surf, const volumeType volType, labelList &pointMap, labelList &edgeMap)
Trim to surface. Keep volType side. Return map from current back.
void setFromStatus (const List< extendedEdgeMesh::pointStatus > &pointStat, const List< extendedEdgeMesh::edgeStatus > &edgeStat, labelList &sortedToOriginalPoint, labelList &sortedToOriginalEdge)
Order according to point and edge status.
bool mergePointsAndSort (const scalar mergeDist, labelList &pointMap, labelList &edgeMap)
Geometric merge points. Returns true if any points merged.
bool read (const fileName &name, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &name)
Read from file. Chooses reader based on detected extension.
void writeObj (const fileName &prefix) const
Write all components of the extendedEdgeMesh as obj files.
virtual void writeStats (Ostream &os) const
Dump some information.
Public Member Functions inherited from edgeMesh
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C ()
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const edgeMesh &em)
Copy construct.
edgeMesh (edgeMesh &&em)
Move construct.
edgeMesh (const pointField &points, const edgeList &edges)
Copy construct from components.
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
Move construct from components.
edgeMesh (const fileName &name)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &name, const word &ext)
Construct from file name (uses extension to determine type)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &mesh)
Transfer the contents of the argument and annul the argument.
bool read (const fileName &name, const word &ext)
Read from file. Chooses reader based on explicit extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void scalePoints (const scalar scaleFactor)
Scale points. A non-positive factor is ignored.
virtual void mergePoints (const scalar mergeDist)
Geometric merge points (points within mergeDist) prior to.
virtual void mergeEdges ()
Merge duplicate edges and eliminate unused points.
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &rhs)
Copy assignment.
void operator= (edgeMesh &&rhs)
Move assignment.
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
Construct null.
virtual ~edgeMeshFormatsCore ()=default
Destructor.
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
Construct from MESH.
bool hasDb () const
Return true if thisDb() is a valid DB - here = false.
const objectRegistry & thisDb () const
Return the object registry.
const faMesh & operator() () const
Return reference to polyMesh.
Static Public Member Functions
static bool canRead (const fileName &name, bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< extendedEdgeMesh > New (const fileName &name, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< extendedEdgeMesh > New (const fileName &name)
Select constructed from filename (implicit extension)
static edgeStatus classifyEdge (const List< vector > &norms, const labelList &edNorms, const vector &fC0tofC1)
Classify the type of feature edge. Requires face centre 0 to face.
static void sortedOrder (const List< extendedEdgeMesh::pointStatus > &pointStat, const List< extendedEdgeMesh::edgeStatus > &edgeStat, labelList &sortedToOriginalPoint, labelList &sortedToOriginalEdge, label &pointConcaveStart, label &pointMixedStart, label &pointNonFeatStart, label &edgeInternalStart, label &edgeFlatStart, label &edgeOpenStart, label &edgeMultipleStart)
Determine the ordering.
Static Public Member Functions inherited from edgeMesh
static label size (const Mesh &mesh)
static bool canRead (const fileName &name, bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &name, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &name)
Select constructed from filename (implicit extension)
static void write (const fileName &name, const edgeMesh &mesh)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Attributes
static const Enum< pointStatus > pointStatusNames_
static const Enum< edgeStatus > edgeStatusNames_
static const Enum< sideVolumeType > sideVolumeTypeNames_
static scalar cosNormalAngleTol_
Angular closeness tolerance for treating normals as the same.
static label nPointTypes = 4
Number of possible point types (i.e. number of slices)
static label nEdgeTypes = 5
Number of possible feature edge types (i.e. number of slices)
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions
extendedEdgeMesh (class one::minus)
Construct null, initializing start indices with -1.
pointStatus classifyFeaturePoint (label ptI) const
Classify the type of feature point. Requires valid stored member.
void cut (const searchableSurface &, labelList &pMap, labelList &eMap, labelList &pointsFromEdge, labelList &oldEdge, labelList &surfTri)
Cut edges with surface. Return map from cut points&edges back.
void select (const searchableSurface &surf, const volumeType volType, labelList &pMap, labelList &eMap)
Remove outside/inside edges. volType denotes which side to keep.
template<class Patch >
void sortPointsAndEdges (const Patch &, const labelUList &featureEdges, const labelUList &regionFeatureEdges, const labelUList &feaurePoints)
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Protected Attributes
label concaveStart_
Index of the start of the concave feature points.
label mixedStart_
Index of the start of the mixed type feature points.
label nonFeatureStart_
Index of the start of the non-feature points.
label internalStart_
Index of the start of the internal feature edges.
label flatStart_
Index of the start of the flat feature edges.
label openStart_
Index of the start of the open feature edges.
label multipleStart_
Index of the start of the multiply-connected feature edges.
vectorField normals_
Normals of the features, to be referred to by index by both feature.
List< sideVolumeType > normalVolumeTypes_
Type per normal: which side of normal to mesh.
vectorField edgeDirections_
Flat and open edges require the direction of the edge.
labelListList normalDirections_
Starting directions for the edges.
labelListList edgeNormals_
Indices of the normals that are adjacent to the feature edges.
labelListList featurePointNormals_
Indices of the normals that are adjacent to the feature points.
labelListList featurePointEdges_
Indices of feature edges attached to feature points. The edges are.
labelList regionEdges_
Feature edges which are on the boundary between regions.
autoPtr< indexedOctree
< treeDataPoint > > pointTree_
Search tree for all feature points.
autoPtr< indexedOctree
< treeDataEdge > > edgeTree_
Search tree for all edges.
PtrList< indexedOctree
< treeDataEdge > > edgeTreesByType_
Individual search trees for each type of edge.
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Reference to Mesh.
Static Protected Attributes
static label convexStart_ = 0
Index of the start of the convex feature points - static as 0.
static label externalStart_ = 0
Index of the start of the external feature edges - static as 0.
Friends
Istream & operator>> (Istream &is, sideVolumeType &vt)
Ostream & operator<< (Ostream &os, const sideVolumeType &vt)
Ostream & operator<< (Ostream &, const extendedEdgeMesh &)
Istream & operator>> (Istream &, extendedEdgeMesh &)
Additional Inherited Members
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Read non-comment line.
Detailed Description
Description of feature edges and points.
Feature points are a sorted subset at the start of the overall points list: 0 .. concaveStart_-1 : convex points (w.r.t normals) concaveStart_ .. mixedStart_-1 : concave points mixedStart_ .. nonFeatureStart_-1 : mixed internal/external points nonFeatureStart_ .. size-1 : non-feature points
Feature edges are the edgeList of the edgeMesh and are sorted: 0 .. internalStart_-1 : external edges (convex w.r.t normals) internalStart_ .. flatStart_-1 : internal edges (concave) flatStart_ .. openStart_-1 : flat edges (neither concave or convex) can arise from region interfaces on flat surfaces openStart_ .. multipleStart_-1 : open edges (e.g. from baffle surfaces) multipleStart_ .. size-1 : multiply connected edges
The edge direction and feature edge and feature point adjacent normals are stored.
Source files
extendedEdgeMesh.H
extendedEdgeMeshI.H
extendedEdgeMesh.C
extendedEdgeMeshNew.C
Definition at line 82 of file extendedEdgeMesh.H.
Member Enumeration Documentation
enum pointStatus
Enumerator
CONVEX
Fully convex point (w.r.t normals)
CONCAVE
Fully concave point.
MIXED
A point surrounded by both convex and concave edges.
NONFEATURE
Not a feature point.
Definition at line 93 of file extendedEdgeMesh.H.
enum edgeStatus
Enumerator
EXTERNAL
"Convex" edge
INTERNAL
"Concave" edge
FLAT
Neither concave or convex, on a flat surface.
OPEN
Only connected to a single face.
MULTIPLE
Multiply connected (connected to more than two faces)
NONE
Unclassified (consistency with surfaceFeatures)
Definition at line 103 of file extendedEdgeMesh.H.
enum sideVolumeType
Normals point to the outside.
Enumerator
INSIDE
mesh inside
OUTSIDE
mesh outside
BOTH
e.g. a baffle
NEITHER
not sure when this may be used
Definition at line 118 of file extendedEdgeMesh.H.
Constructor & Destructor Documentation
extendedEdgeMesh (class one::minus) explicit protected
Construct null, initializing start indices with -1.
Definition at line 398 of file extendedEdgeMesh.C.
extendedEdgeMesh ()
Construct null.
Definition at line 374 of file extendedEdgeMesh.C.
extendedEdgeMesh (const extendedEdgeMesh & fem) explicit
Construct as copy.
Definition at line 422 of file extendedEdgeMesh.C.
extendedEdgeMesh (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 614 of file extendedEdgeMesh.C.
References Foam::read().
extendedEdgeMesh (const fileName & name, const word & ext)
Construct from file name (uses extension to determine type)
Definition at line 603 of file extendedEdgeMesh.C.
extendedEdgeMesh (Istream & is)
Construct from Istream.
Definition at line 446 of file extendedEdgeMesh.C.
extendedEdgeMesh (const pointField & points, const edgeList & edges)
Copy construct from components.
Definition at line 453 of file extendedEdgeMesh.C.
extendedEdgeMesh (pointField && points, edgeList && edges)
Move construct from components.
Definition at line 466 of file extendedEdgeMesh.C.
References points.
extendedEdgeMesh (const surfaceFeatures & sFeat, const boolList & surfBaffleRegions)
Construct given a surface with selected edges,points.
(surfaceFeatures) Extracts, classifies and reorders the data from surfaceFeatures.
Definition at line 479 of file extendedEdgeMesh.C.
References extendedEdgeMesh::transfer().
extendedEdgeMesh (const PrimitivePatch< face, List, pointField, point > & surf, const labelUList & featureEdges, const labelUList & regionFeatureEdges, const labelUList & featurePoints)
Construct from PrimitivePatch.
Definition at line 540 of file extendedEdgeMesh.C.
extendedEdgeMesh (const pointField & pts, const edgeList & eds, label concaveStart, label mixedStart, label nonFeatureStart, label internalStart, label flatStart, label openStart, label multipleStart, const vectorField & normals, const List< sideVolumeType > & normalVolumeTypes, const vectorField & edgeDirections, const labelListList & normalDirections, const labelListList & edgeNormals, const labelListList & featurePointNormals, const labelListList & featurePointEdges, const labelList & regionEdges)
Construct from all components.
Definition at line 560 of file extendedEdgeMesh.C.
~extendedEdgeMesh ()
Destructor.
Definition at line 624 of file extendedEdgeMesh.C.
References Foam::read().
Member Function Documentation
TypeName ("extendedEdgeMesh")
Runtime type information.
Foam::extendedEdgeMesh::pointStatus classifyFeaturePoint (label ptI) const protected
Classify the type of feature point. Requires valid stored member.
data for edges and normals.
Definition at line 149 of file extendedEdgeMesh.C.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
void cut (const searchableSurface & surf, labelList & pMap, labelList & eMap, labelList & pointsFromEdge, labelList & oldEdge, labelList & surfTri) protected
Cut edges with surface. Return map from cut points&edges back.
to original
Definition at line 193 of file extendedEdgeMesh.C.
void select (const searchableSurface & surf, const volumeType volType, labelList & pMap, labelList & eMap) protected
Remove outside/inside edges. volType denotes which side to keep.
Definition at line 295 of file extendedEdgeMesh.C.
void sortPointsAndEdges (const Patch & surf, const labelUList & featureEdges, const labelUList & regionFeatureEdges, const labelUList & feaurePoints) protected
Definition at line 33 of file extendedEdgeMeshTemplates.C.
References Foam::abort(), DynamicList< T, SizeMin >::append(), Vector< Cmpt >::centre(), extendedEdgeMesh::classifyEdge(), extendedEdgeMesh::classifyFeaturePoint(), extendedEdgeMesh::CONCAVE, extendedEdgeMesh::concaveStart_, extendedEdgeMesh::CONVEX, extendedEdgeMesh::cosNormalAngleTol_, Foam::cross(), extendedEdgeMesh::edgeDirections(), extendedEdgeMesh::edgeDirections_, edgeMesh::edgeMesh(), extendedEdgeMesh::edgeNormals(), extendedEdgeMesh::edgeNormals_, edge::end(), UList< T >::end(), extendedEdgeMesh::EXTERNAL, Foam::faceMap(), faceNormals(), Foam::FatalError, FatalErrorInFunction, extendedEdgeMesh::featurePointEdges_, extendedEdgeMesh::featurePointNormals(), extendedEdgeMesh::featurePointNormals_, extendedEdgeMesh::FLAT, extendedEdgeMesh::flatStart_, forAll, UList< T >::found(), i, Foam::identity(), Foam::inplaceRenumber(), Foam::inplaceReorder(), extendedEdgeMesh::INTERNAL, extendedEdgeMesh::internalStart_, Foam::invert(), j, k, Foam::mag(), extendedEdgeMesh::MIXED, extendedEdgeMesh::mixedStart_, extendedEdgeMesh::MULTIPLE, extendedEdgeMesh::multipleStart_, extendedEdgeMesh::nEdgeTypes, Foam::nl, extendedEdgeMesh::NONE, extendedEdgeMesh::NONFEATURE, extendedEdgeMesh::nonFeatureStart_, extendedEdgeMesh::normalDirections(), extendedEdgeMesh::normalDirections_, extendedEdgeMesh::normals_, extendedEdgeMesh::OPEN, extendedEdgeMesh::openStart_, edgeMesh::operator=(), edgeMesh::pointEdges(), edgeMesh::points(), extendedEdgeMesh::regionEdges(), extendedEdgeMesh::regionEdges_, DynamicList< T, SizeMin >::setCapacity(), List< T >::setSize(), UList< T >::size(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), edge::start(), bitSet::test(), edgeMesh::transfer(), List< T >::transfer(), edge::vec(), and Foam::Zero.
bool canRead (const fileName & name, bool verbose = false) static
Can we read this file format?
Definition at line 134 of file extendedEdgeMesh.C.
bool canReadType (const word & ext, bool verbose = false) static
Can we read this file format?
Definition at line 110 of file extendedEdgeMesh.C.
bool canWriteType (const word & ext, bool verbose = false) static
Can we write this file format type?
Definition at line 122 of file extendedEdgeMesh.C.
Foam::wordHashSet readTypes () static
Definition at line 96 of file extendedEdgeMesh.C.
Foam::wordHashSet writeTypes () static
Definition at line 102 of file extendedEdgeMesh.C.
declareRunTimeSelectionTable (autoPtr , extendedEdgeMesh , fileExtension , (const fileName &name) , (name))
Foam::autoPtr< Foam::extendedEdgeMesh > New (const fileName & name, const word & ext) static
Select constructed from filename (explicit extension)
Definition at line 35 of file extendedEdgeMeshNew.C.
Foam::autoPtr< Foam::extendedEdgeMesh > New (const fileName & name) static
Select constructed from filename (implicit extension)
Definition at line 57 of file extendedEdgeMeshNew.C.
void nearestFeaturePoint (const point & sample, scalar searchDistSqr, pointIndexHit & info) const
Find nearest surface edge for the sample point.
Definition at line 657 of file extendedEdgeMesh.C.
void nearestFeatureEdge (const point & sample, scalar searchDistSqr, pointIndexHit & info) const
Find nearest surface edge for the sample point.
Definition at line 672 of file extendedEdgeMesh.C.
void nearestFeatureEdge (const pointField & samples, const scalarField & searchDistSqr, List< pointIndexHit > & info) const
Find nearest surface edge for each sample point.
Definition at line 687 of file extendedEdgeMesh.C.
void nearestFeatureEdgeByType (const point & sample, const scalarField & searchDistSqr, List< pointIndexHit > & info) const
Find the nearest point on each type of feature edge.
Definition at line 708 of file extendedEdgeMesh.C.
void allNearestFeaturePoints (const point & sample, scalar searchRadiusSqr, List< pointIndexHit > & info) const
Find all the feature points within searchDistSqr of sample.
Definition at line 744 of file extendedEdgeMesh.C.
void allNearestFeatureEdges (const point & sample, const scalar searchRadiusSqr, List< pointIndexHit > & info) const
Find all the feature edges within searchDistSqr of sample.
Definition at line 775 of file extendedEdgeMesh.C.
Foam::label convexStart () const inline
Return the index of the start of the convex feature points.
Definition at line 23 of file extendedEdgeMeshI.H.
Foam::label concaveStart () const inline
Return the index of the start of the concave feature points.
Definition at line 29 of file extendedEdgeMeshI.H.
References extendedEdgeMesh::convexStart_.
Referenced by Foam::edgeMeshTools::writeStats().
Foam::label mixedStart () const inline
Return the index of the start of the mixed type feature points.
Definition at line 35 of file extendedEdgeMeshI.H.
Referenced by Foam::edgeMeshTools::writeStats().
Foam::label nonFeatureStart () const inline
Return the index of the start of the non-feature points.
Definition at line 41 of file extendedEdgeMeshI.H.
Referenced by Foam::edgeMeshTools::writeStats().
Foam::label externalStart () const inline
Return the index of the start of the external feature edges.
Definition at line 47 of file extendedEdgeMeshI.H.
Foam::label internalStart () const inline
Return the index of the start of the internal feature edges.
Definition at line 53 of file extendedEdgeMeshI.H.
Referenced by Foam::edgeMeshTools::writeStats().
Foam::label flatStart () const inline
Return the index of the start of the flat feature edges.
Definition at line 59 of file extendedEdgeMeshI.H.
Referenced by Foam::edgeMeshTools::writeStats().
Foam::label openStart () const inline
Return the index of the start of the open feature edges.
Definition at line 65 of file extendedEdgeMeshI.H.
Referenced by Foam::edgeMeshTools::writeStats().
Foam::label multipleStart () const inline
Return the index of the start of the multiply-connected feature.
edges
Definition at line 71 of file extendedEdgeMeshI.H.
Referenced by Foam::edgeMeshTools::writeStats().
bool featurePoint (label ptI) const inline
Return whether or not the point index is a feature point.
Definition at line 77 of file extendedEdgeMeshI.H.
const Foam::vectorField & normals () const inline
Return the normals of the surfaces adjacent to the feature edges.
and points
Definition at line 83 of file extendedEdgeMeshI.H.
const Foam::List< Foam::extendedEdgeMesh::sideVolumeType > & normalVolumeTypes () const inline
Return.
Definition at line 90 of file extendedEdgeMeshI.H.
const Foam::vectorField & edgeDirections () const inline
Return the edgeDirection vectors.
Definition at line 96 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
const Foam::labelListList & normalDirections () const inline
Definition at line 104 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
Foam::vector edgeDirection (label edgeI, label ptI) const inline
Return the direction of edgeI, pointing away from ptI.
Definition at line 111 of file extendedEdgeMeshI.H.
const Foam::labelListList & edgeNormals () const inline
Return the indices of the normals that are adjacent to the.
feature edges
Definition at line 139 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
Foam::vectorField edgeNormals (const labelList & edgeNormIs) const inline
Return the normal vectors for a given set of normal indices.
Definition at line 147 of file extendedEdgeMeshI.H.
Foam::vectorField edgeNormals (label edgeI) const inline
Return the normal vectors for a given edge.
Definition at line 162 of file extendedEdgeMeshI.H.
const Foam::labelListList & featurePointNormals () const inline
Return the indices of the normals that are adjacent to the.
feature points
Definition at line 170 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
Foam::vectorField featurePointNormals (label ptI) const inline
Return the normal vectors for a given feature point.
Definition at line 177 of file extendedEdgeMeshI.H.
const Foam::labelListList & featurePointEdges () const inline
Return the edge labels for a given feature point. Edges are.
ordered by the faces that they share. The edge labels correspond to the entry in edges().
Definition at line 205 of file extendedEdgeMeshI.H.
const Foam::labelList & regionEdges () const inline
Return the feature edges which are on the boundary between.
regions
Definition at line 211 of file extendedEdgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
Foam::extendedEdgeMesh::pointStatus getPointStatus (label ptI) const inline
Return the pointStatus of a specified point.
Definition at line 218 of file extendedEdgeMeshI.H.
Foam::extendedEdgeMesh::edgeStatus getEdgeStatus (label edgeI) const inline
Return the edgeStatus of a specified edge.
Definition at line 238 of file extendedEdgeMeshI.H.
Foam::PackedList< 2 > edgeBaffles (label edgeI) const inline
Return the baffle faces of a specified edge.
Definition at line 262 of file extendedEdgeMeshI.H.
const Foam::indexedOctree< Foam::treeDataPoint > & pointTree () const
Demand driven construction of octree for feature points.
Definition at line 831 of file extendedEdgeMesh.C.
const Foam::indexedOctree< Foam::treeDataEdge > & edgeTree () const
Demand driven construction of octree for boundary edges.
Definition at line 871 of file extendedEdgeMesh.C.
const Foam::PtrList< Foam::indexedOctree< Foam::treeDataEdge > > & edgeTreesByType () const
Demand driven construction of octree for boundary edges by type.
Definition at line 913 of file extendedEdgeMesh.C.
void transfer (extendedEdgeMesh & mesh)
Transfer the contents of the argument and annul the argument.
Definition at line 977 of file extendedEdgeMesh.C.
Referenced by extendedEdgeMesh::extendedEdgeMesh().
void clear () virtual
Clear all storage.
Reimplemented from edgeMesh.
Definition at line 1004 of file extendedEdgeMesh.C.
void add (const extendedEdgeMesh & fem)
Add extendedEdgeMesh. No filtering of duplicates.
Definition at line 1028 of file extendedEdgeMesh.C.
void flipNormals ()
Flip normals. All concave become convex, all internal external.
etc.
Definition at line 1298 of file extendedEdgeMesh.C.
void autoMap (const pointField & subPoints, const edgeList & subEdges, const labelList & pointMap, const labelList & edgeMap)
Update with derived geometry.
Definition at line 1410 of file extendedEdgeMesh.C.
void trim (const searchableSurface & surf, const volumeType volType, labelList & pointMap, labelList & edgeMap)
Trim to surface. Keep volType side. Return map from current back.
to original points (-1 for newly introduced points), edges
Definition at line 1650 of file extendedEdgeMesh.C.
void setFromStatus (const List< extendedEdgeMesh::pointStatus > & pointStat, const List< extendedEdgeMesh::edgeStatus > & edgeStat, labelList & sortedToOriginalPoint, labelList & sortedToOriginalEdge)
Order according to point and edge status.
Definition at line 1733 of file extendedEdgeMesh.C.
bool mergePointsAndSort (const scalar mergeDist, labelList & pointMap, labelList & edgeMap)
Geometric merge points. Returns true if any points merged.
Return maps from new back to original points/edges.
Definition at line 1801 of file extendedEdgeMesh.C.
bool read (const fileName & name, const word & ext)
Read from file. Chooses reader based on explicit extension.
Definition at line 645 of file extendedEdgeMesh.C.
bool read (const fileName & name) virtual
Read from file. Chooses reader based on detected extension.
Reimplemented from edgeMesh.
Reimplemented in extendedEdgeMeshFormat.
Definition at line 630 of file extendedEdgeMesh.C.
void writeObj (const fileName & prefix) const
Write all components of the extendedEdgeMesh as obj files.
Definition at line 1889 of file extendedEdgeMesh.C.
void writeStats (Ostream & os) const virtual
Dump some information.
Reimplemented from edgeMesh.
Definition at line 2044 of file extendedEdgeMesh.C.
Foam::extendedEdgeMesh::edgeStatus classifyEdge (const List< vector > & norms, const labelList & edNorms, const vector & fC0tofC1) static
Classify the type of feature edge. Requires face centre 0 to face.
centre 1 vector to distinguish internal from external
Definition at line 2096 of file extendedEdgeMesh.C.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
void sortedOrder (const List< extendedEdgeMesh::pointStatus > & pointStat, const List< extendedEdgeMesh::edgeStatus > & edgeStat, labelList & sortedToOriginalPoint, labelList & sortedToOriginalEdge, label & pointConcaveStart, label & pointMixedStart, label & pointNonFeatStart, label & edgeInternalStart, label & edgeFlatStart, label & edgeOpenStart, label & edgeMultipleStart) static
Determine the ordering.
Definition at line 2137 of file extendedEdgeMesh.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, sideVolumeType & vt) friend
Ostream& operator<< (Ostream & os, const sideVolumeType & vt) friend
Ostream& operator<< (Ostream & , const extendedEdgeMesh &) friend
Istream& operator>> (Istream & , extendedEdgeMesh &) friend
Member Data Documentation
const Foam::Enum< Foam::extendedEdgeMesh::pointStatus > pointStatusNames_ static
Definition at line 101 of file extendedEdgeMesh.H.
const Foam::Enum< Foam::extendedEdgeMesh::edgeStatus > edgeStatusNames_ static
Definition at line 113 of file extendedEdgeMesh.H.
const Foam::Enum< Foam::extendedEdgeMesh::sideVolumeType > sideVolumeTypeNames_ static
Definition at line 126 of file extendedEdgeMesh.H.
Foam::scalar cosNormalAngleTol_ static
Initial value:
=
    Foam::cos(degToRad(0.1))
Angular closeness tolerance for treating normals as the same.
Definition at line 131 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
Foam::label convexStart_ = 0 static protected
Index of the start of the convex feature points - static as 0.
Definition at line 141 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::concaveStart().
Foam::label externalStart_ = 0 static protected
Index of the start of the external feature edges - static as 0.
Definition at line 146 of file extendedEdgeMesh.H.
label concaveStart_ protected
Index of the start of the concave feature points.
Definition at line 154 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
label mixedStart_ protected
Index of the start of the mixed type feature points.
Definition at line 159 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
label nonFeatureStart_ protected
Index of the start of the non-feature points.
Definition at line 164 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
label internalStart_ protected
Index of the start of the internal feature edges.
Definition at line 169 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
label flatStart_ protected
Index of the start of the flat feature edges.
Definition at line 174 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
label openStart_ protected
Index of the start of the open feature edges.
Definition at line 179 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
label multipleStart_ protected
Index of the start of the multiply-connected feature edges.
Definition at line 184 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
vectorField normals_ protected
Normals of the features, to be referred to by index by both feature.
points and edges, unsorted
Definition at line 191 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
List<sideVolumeType> normalVolumeTypes_ protected
Type per normal: which side of normal to mesh.
Definition at line 196 of file extendedEdgeMesh.H.
vectorField edgeDirections_ protected
Flat and open edges require the direction of the edge.
Definition at line 201 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
labelListList normalDirections_ protected
Starting directions for the edges.
This vector points to the half of the plane defined by the first edge normal.
Definition at line 209 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
labelListList edgeNormals_ protected
Indices of the normals that are adjacent to the feature edges.
Definition at line 214 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
labelListList featurePointNormals_ protected
Indices of the normals that are adjacent to the feature points.
(only valid for 0..nonFeatureStart_-1)
Definition at line 221 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
labelListList featurePointEdges_ protected
Indices of feature edges attached to feature points. The edges are.
ordered so that they can be circulated.
Definition at line 228 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
labelList regionEdges_ protected
Feature edges which are on the boundary between regions.
Definition at line 233 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
autoPtr<indexedOctree<treeDataPoint> > pointTree_ mutable protected
Search tree for all feature points.
Definition at line 238 of file extendedEdgeMesh.H.
autoPtr<indexedOctree<treeDataEdge> > edgeTree_ mutable protected
Search tree for all edges.
Definition at line 243 of file extendedEdgeMesh.H.
PtrList<indexedOctree<treeDataEdge> > edgeTreesByType_ mutable protected
Individual search trees for each type of edge.
Definition at line 248 of file extendedEdgeMesh.H.
Foam::label nPointTypes = 4 static
Number of possible point types (i.e. number of slices)
Definition at line 310 of file extendedEdgeMesh.H.
Foam::label nEdgeTypes = 5 static
Number of possible feature edge types (i.e. number of slices)
Definition at line 315 of file extendedEdgeMesh.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
The documentation for this class was generated from the following files:
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMesh.H
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMesh.C
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshI.H
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshNew.C
src/meshTools/edgeMesh/extendedEdgeMesh/extendedEdgeMeshTemplates.C