OpenFOAM: processorPointPatch Class Reference
processorPointPatch Class Reference
Processor patch boundary needs to be such that the ordering of points in the patch is the same on both sides.
Public Member Functions
TypeName (processorPolyPatch::typeName_())
Runtime type information.
processorPointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~processorPointPatch ()
Destructor.
virtual int tag () const
Return message tag to use for communication.
virtual label comm () const
Return communicator used for communication.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
int myProcNo () const
Return processor number.
int neighbProcNo () const
Return neighbour processor number.
bool isMaster () const
Is this a master patch.
bool isSlave () const
Is this a slave patch.
const processorPolyPatch & procPolyPatch () const
Return the underlying processorPolyPatch.
const labelList & reverseMeshPoints () const
Return mesh points in the correct order for the receiving side.
Public Member Functions inherited from coupledFacePointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFacePointPatch (const polyPatch &patch, const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledFacePointPatch ()
Destructor.
Public Member Functions inherited from facePointPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &p, const pointBoundaryMesh &pm)
Construct from polyPatch and boundary mesh.
virtual ~facePointPatch ()=default
Destructor.
virtual const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label size () const
Return size.
virtual label index () const
Return the index of this patch in the pointBoundaryMesh.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const
Return mesh points.
virtual const pointField & localPoints () const
Return pointField of points in patch.
virtual const vectorField & pointNormals () const
Return point unit normals.
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
Construct from boundary mesh.
virtual ~pointPatch ()=default
Destructor.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Public Member Functions inherited from coupledPointPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledPointPatch (const pointBoundaryMesh &bm)
Construct from components.
virtual ~coupledPointPatch ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from facePointPatch
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
Protected Member Functions inherited from facePointPatch
facePointPatch (const facePointPatch &)=delete
No copy construct.
void operator= (const facePointPatch &)=delete
No copy assignment.
Protected Member Functions inherited from pointPatch
pointPatch (const pointPatch &)=delete
No copy construct.
void operator= (const pointPatch &)=delete
No copy assignment.
Protected Attributes inherited from facePointPatch
const polyPatch & polyPatch_
Reference to the underlying polyPatch.
Detailed Description
Processor patch boundary needs to be such that the ordering of points in the patch is the same on both sides.
Looking at the creation of the faces on both sides of the processor patch they need to be identical on both sides with the normals pointing in opposite directions. This is achieved by calling the reverseFace function in the decomposition. It is therefore possible to re-create the ordering of patch points on the slave side by reversing all the patch faces of the owner.
Source files
processorPointPatch.H
processorPointPatch.C
Definition at line 55 of file processorPointPatch.H.
Constructor & Destructor Documentation
processorPointPatch (const polyPatch & patch, const pointBoundaryMesh & bm)
Construct from components.
Definition at line 103 of file processorPointPatch.C.
~processorPointPatch () virtual
Destructor.
Definition at line 115 of file processorPointPatch.C.
Member Function Documentation
TypeName (processorPolyPatch:: typeName_())
Runtime type information.
virtual int tag () const inline virtual
Return message tag to use for communication.
Reimplemented in processorCyclicPointPatch.
Definition at line 140 of file processorPointPatch.H.
References processorPolyPatch::myProcNo().
virtual label comm () const inline virtual
Return communicator used for communication.
Definition at line 148 of file processorPointPatch.H.
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatch implements.
Reimplemented from pointPatch.
Definition at line 156 of file processorPointPatch.H.
References processorPointPatch::isMaster().
int myProcNo () const inline
Return processor number.
Definition at line 164 of file processorPointPatch.H.
int neighbProcNo () const inline
Return neighbour processor number.
Definition at line 172 of file processorPointPatch.H.
bool isMaster () const inline
Is this a master patch.
Definition at line 180 of file processorPointPatch.H.
Referenced by processorPointPatch::constraintType().
bool isSlave () const inline
Is this a slave patch.
Definition at line 188 of file processorPointPatch.H.
const processorPolyPatch& procPolyPatch () const inline
Return the underlying processorPolyPatch.
Definition at line 196 of file processorPointPatch.H.
const Foam::labelList & reverseMeshPoints () const
Return mesh points in the correct order for the receiving side.
Definition at line 121 of file processorPointPatch.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/processor/processorPointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/constraint/processor/processorPointPatch.C