OpenFOAM: bitSet Class Reference
bitSet Class Reference
A bitSet stores bits (elements with only two states) in packed internal format and supports a variety of bit-set operations. Its behaviour is largely list-like, with some HashSet features.
Classes
class const_iterator
A const_iterator for iterating across on values.
class reference
A reference supporting read/write access to an entry.
Public Types
typedef unsigned int const_reference
Public Types inherited from PackedList< 1 >
typedef unsigned int block_type
The storage block type for bit elements.
typedef unsigned int const_reference
Public Member Functions
ClassName ("bitSet")
Define class name and debug.
bitSet () noexcept
Construct an empty, zero-sized set.
bitSet (Istream &is)
Construct from Istream.
bitSet (const label n)
Construct with given size, with all bits set to 0.
bitSet (const label n, const bool val)
Construct with given size and value for all elements.
bitSet (const bitSet &bitset)
Copy construct.
bitSet (bitSet &&bitset)
Move construct.
bitSet (const bitSet &bitset, const labelUList &addr)
Copy construct a subset.
template<class Addr >
bitSet (const bitSet &bitset, const IndirectListBase< label, Addr > &addr)
Copy construct a subset.
bitSet (const bitSet &bitset, const labelRange &range)
Copy construct a subset range.
bitSet (const UList< bool > &bools)
Construct from a list of bools.
bitSet (const label n, const labelUList &locations)
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
template<class Addr >
bitSet (const label n, const IndirectListBase< label, Addr > &locations)
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
template<unsigned N>
bitSet (const label n, const FixedList< label, N > &locations)
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
bitSet (const label n, std::initializer_list< label > locations)
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
bitSet (const labelUList &locations)
Construct with automatic sizing (filled with 0), and populate with specified locations as 1.
template<class Addr >
bitSet (const IndirectListBase< label, Addr > &locations)
Construct with automatic sizing (filled with 0), and populate with specified locations as 1.
template<unsigned N>
bitSet (const FixedList< label, N > &locations)
Construct with automatic sizing (filled with 0), and populate with specified locations as 1.
autoPtr< bitSet > clone () const
Clone.
bool all () const
True if all bits in this bitset are set or if the set is empty.
bool any () const
True if any bits in this bitset are set.
bool none () const
True if no bits in this bitset are set.
bool uniform () const
True if all entries have identical values, and the set is non-empty.
unsigned int count (const bool on=true) const
Count number of bits set.
bool intersects (const bitSet &other) const
True if any bits in the other bitset intersect (are the same).
bool test (const label pos) const
Test value at specified position, never auto-vivify entries.
label find_first () const
Locate the first bit that is set.
label find_first_not () const
Locate the first bit that is unset.
label find_last () const
Locate the last bit set.
label find_next (label pos) const
Locate the next bit set, starting one beyond the specified position.
labelList toc () const
The indices of the on bits as a sorted labelList.
labelList sortedToc () const
The indices of the on bits as a sorted labelList.
List< bool > values () const
Return the bitset values as a boolList.
void assign (const bool val)
Assign all entries to the given value.
void assign (const UList< bool > &bools)
Copy assign all entries from a list of bools.
void set (const bitSet &bitset)
Set specified bits from another bitset.
void set (const labelRange &range)
Set the specified range of bits specified.
bitSet & unset (const bitSet &other)
Unset (subtract) the bits specified in the other bitset, which is a set difference corresponds to the logical operation.
void unset (const labelRange &range)
Unset the specified range of bits specified, never auto-vivifies.
void flip ()
Invert all bits in the addressable region.
void flip (const label pos)
Invert bits at the specified position.
void swap (bitSet &bitset)
Swap contents.
void transfer (bitSet &bitset)
Transfer the contents of the argument list into this list and annul the argument list.
bitSet & bound (const label maxSize)
Ensure the addressable range does not exceed maxSize.
bitSet & bound (const bitSet &other)
Ensure the addressable range does not exceed that of other.
bitSet & extend (const label minSize)
Ensure that minSize is covered by the bitSet.
bitSet & extend (const bitSet &other)
Ensure the bitset is addressable throughout the range of other.
template<class InputIter >
label setMany (InputIter first, InputIter last)
Set the locations listed by the iterator range,.
label set (const labelUList &locations)
Set the listed locations to true.
template<class Addr >
label set (const IndirectListBase< label, Addr > &locations)
Set the listed locations to true.
template<unsigned N>
label set (const FixedList< label, N > &locations)
Set the listed locations to true.
template<class InputIter >
label unset (InputIter first, InputIter last)
Unset the locations listed by the iterator range, never auto-vivify entries.
label unset (const labelUList &locations)
Unset the listed locations, never auto-vivifies.
template<class Addr >
label unset (const IndirectListBase< label, Addr > &locations)
Unset the listed locations, never auto-vivifies.
template<unsigned N>
label unset (const FixedList< label, N > &locations)
Unset the listed locations, never auto-vivifies.
const_iterator begin () const
Iterator set to the position of the first on bit.
const_iterator cbegin () const
Iterator set to the position of the first on bit.
const_iterator begin (label pos) const
Iterator set to the position of the first on bit that occurs at or beyond the given position.
const_iterator cbegin (label pos) const
Iterator set to the position of the first on bit that occurs at or beyond the given position.
const_iterator end () const noexcept
Iterator beyond the end of the bitSet.
const_iterator cend () const noexcept
Iterator beyond the end of the bitSet.
bool operator() (const label pos) const
Test value at specified position, same as test()
unsigned int operator[] (const label i) const
Identical to get() - get value at index.
reference operator[] (const label i)
Non-const access to value at index.
bitSet & operator= (const bool val)
Assignment of all entries to the given value.
bitSet & operator= (const bitSet &bitset)
Copy assignment.
bitSet & operator= (bitSet &&bitset)
Move assignment.
bitSet & operator&= (const bitSet &other)
Bitwise-AND all the bits in other with the bits in this bitset.
bitSet & operator|= (const bitSet &other)
Bitwise-OR operator - similar to the set() method.
bitSet & operator^= (const bitSet &other)
Bitwise-XOR operator - retains unique entries.
bitSet & operator-= (const bitSet &other)
Remove entries from this list - identical to the unset() method.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write bitSet, with line-breaks (ASCII) when length exceeds shortLen.
void writeEntry (const word &keyword, Ostream &os) const
Write as a dictionary entry with keyword.
InfoProxy< bitSet > info () const
Return info proxy.
template<class Addr>
Foam::label set (const IndirectListBase< label, Addr > &locations)
template<class Addr>
Foam::label unset (const IndirectListBase< label, Addr > &locations)
template<class InputIter >
Foam::label setMany (InputIter first, InputIter last)
template<class InputIter>
Foam::label unset (InputIter first, InputIter last)
template<unsigned N>
Foam::label set (const FixedList< label, N > &locations)
template<unsigned N>
Foam::label unset (const FixedList< label, N > &locations)
Public Member Functions inherited from PackedList< 1 >
void writeEntry (const word &keyword, Ostream &os) const
Write as a dictionary entry with keyword.
constexpr PackedList () noexcept
Null constructor.
PackedList (const label numElem)
Construct for given number of elements, initializes values to 0.
PackedList (const label numElem, const unsigned int val)
Construct for given number of elements, and the specified value for each element.
PackedList (Istream &is)
Construct from Istream.
PackedList (const PackedList< Width > &list)
Copy construct.
PackedList (PackedList< Width > &&list)
Move construct.
PackedList (const PackedList< Width > &list, const labelUList &addr)
Copy construct a subset.
PackedList (const PackedList< Width > &list, const IndirectListBase< label, Addr > &addr)
Copy construct a subset.
PackedList (const PackedList< Width > &list, const labelRange &range)
Copy construct a subset range.
PackedList (const labelUList &values)
Construct from a list of values.
PackedList (const IndirectListBase< label, Addr > &values)
Construct from a indirect list of values.
autoPtr< PackedList< Width > > clone () const
Clone.
void checkIndex (const label i) const
Check index is within valid range [0,size)
label size () const noexcept
Number of entries.
bool empty () const noexcept
True if the list is empty (ie, size() is zero).
label capacity () const
The number of elements that can be stored with reallocating.
bool uniform () const
True if all entries have identical values, and list is non-empty.
bool equal (const PackedList< Width > &other) const
Test for equality of sizes and the bits set.
unsigned int get (const label i) const
Get value at index i or 0 for out-of-range.
bool set (const label i, unsigned int val=~0u)
Set value at index i, default value set is the max_value.
bool unset (const label i)
Unset the entry at index i.
labelList values () const
Return the values as a list of labels.
List< IntType > unpack () const
Return the values as a list of integral type.
List< IntType > unpack (const labelRange &range) const
Return the range of values as a list of integral type.
List< IntType > unpack (const labelUList &locations) const
Extract the values for the specified locations as a list of integral type.
void assign (const unsigned int val)
Assign all entries to the given value. Takes linear time.
void assign (const PackedList< Width > &rhs)
Copy assignment.
bool trim (label minpos=-1)
Trim any trailing zero elements, optionally specifying a a minimum position, below which trimming will not occur.
void reset ()
Clear all bits but do not adjust the addressable size.
void setCapacity (const label nElem)
Alter the size of the underlying storage.
void resize (const label nElem, const unsigned int val=0u)
Reset addressable list size, does not shrink the allocated size.
void setSize (const label nElem, const unsigned int val=0u)
Alias for resize()
void reserve (const label nElem)
Reserve allocation space for at least this size.
void clear ()
Clear the list, i.e. set addressable size to zero.
void clearStorage ()
Clear the list and delete storage.
void shrink ()
Shrink the allocated space to what is actually used.
void swap (PackedList< Width > &rhs)
Swap contents with argument.
void transfer (PackedList< Width > &rhs)
Transfer the contents of the argument list into this list.
std::streamsize byteSize () const
The number of bytes used in the underlying storage including any unused padding.
label nBlocks () const
The number of internal storage blocks.
const List< unsigned int > & storage () const
Return the underlying storage blocks.
List< unsigned int > & storage ()
Return the underlying storage blocks.
Ostream & printBits (Ostream &os, bool debugOutput=false) const
Print bit patterns, optionally with extra debug.
Istream & read (Istream &is)
Clear list and read from stream.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
PackedList< Width > & append (const unsigned int val)
Append a value at the end of the list.
unsigned int remove ()
Remove and return the last element.
unsigned int operator[] (const label i) const
Identical to get() - get value at index.
reference operator[] (const label i)
Non-const access to value at index.
void operator= (const unsigned int val)
Assignment of all entries to the given value. Takes linear time.
void operator= (const PackedList< Width > &lst)
Copy assignment.
void operator= (PackedList< Width > &&lst)
Move assignment.
InfoProxy< PackedList< Width > > info () const
Return info proxy.
Public Member Functions inherited from PackedListCore
ClassNameNoDebug ("PackedList")
Define template name.
Protected Member Functions
void writeEntry (Ostream &os) const
Write as a dictionary entry.
bitSet & minusEq (const bitSet &other)
The set difference.
bitSet & andEq (const bitSet &other)
The set logical AND.
bitSet & orEq (const bitSet &other, const bool strict=true)
The set logical OR.
bitSet & xorEq (const bitSet &other, const bool strict=true)
The set logical XOR.
Protected Member Functions inherited from PackedList< 1 >
void setPair (Istream &is)
Read an index/value pair and set accordingly.
void writeEntry (Ostream &os) const
Write as a dictionary entry.
void clear_trailing_bits ()
Clear any partial rubbish in the last addressable block.
Additional Inherited Members
Static Public Member Functions inherited from PackedList< 1 >
static constexpr label num_blocks (label numElem)
Calculate the number of blocks required to _address_ the requested number of elements.
static constexpr block_type mask_lower (unsigned elementOffset)
Masking for all bits below the element offset.
Static Public Attributes inherited from PackedList< 1 >
static constexpr unsigned bits_per_block
The number of bits in a single block.
static constexpr unsigned element_width
The width of an individual element (in bits).
static constexpr unsigned elem_per_block
The number of elements stored per data block.
static constexpr block_type max_value
The max value for an element which is also the bit-mask of the individual element.
Protected Types inherited from PackedList< 1 >
typedef List< block_type > block_container
The internal container for storing the blocks.
Static Protected Member Functions inherited from PackedList< 1 >
static unsigned int repeated_value (unsigned val)
Enforce non-zero Width to fit within the block storage and require at least 2 items per storage block for general efficiency.
static unsigned int readValue (Istream &is)
Read a list entry (allows for specialization)
Protected Attributes inherited from PackedList< 1 >
block_container blocks_
The blocks of raw data.
label size_
Number of entries used.
Detailed Description
A bitSet stores bits (elements with only two states) in packed internal format and supports a variety of bit-set operations. Its behaviour is largely list-like, with some HashSet features.
Source files
bitSet.H
bitSetI.H
bitSet.C
bitSetIO.C
bitSetTemplates.C
See Also
Foam::BitOps Foam::PackedList
Definition at line 60 of file bitSet.H.
Member Typedef Documentation
typedef unsigned int const_reference
Definition at line 143 of file bitSet.H.
Constructor & Destructor Documentation
bitSet () inline noexcept
Construct an empty, zero-sized set.
Definition at line 70 of file bitSetI.H.
bitSet (Istream & is) explicit
Construct from Istream.
Definition at line 283 of file bitSet.C.
bitSet (const label n) inline explicit
Construct with given size, with all bits set to 0.
Definition at line 76 of file bitSetI.H.
bitSet (const label n, const bool val) inline
Construct with given size and value for all elements.
Definition at line 82 of file bitSetI.H.
bitSet (const bitSet & bitset) inline
Copy construct.
Definition at line 90 of file bitSetI.H.
References Foam::FieldOps::assign().
bitSet (bitSet && bitset) inline
Move construct.
Definition at line 96 of file bitSetI.H.
bitSet (const bitSet & bitset, const labelUList & addr)
Copy construct a subset.
Definition at line 291 of file bitSet.C.
bitSet (const bitSet & bitset, const IndirectListBase< label, Addr > & addr)
Copy construct a subset.
Definition at line 48 of file bitSetTemplates.C.
bitSet (const bitSet & bitset, const labelRange & range)
Copy construct a subset range.
Definition at line 304 of file bitSet.C.
References PackedList< Width >::get(), i, and bitSet::set().
bitSet (const UList< bool > & bools) inline explicit
Construct from a list of bools.
Definition at line 102 of file bitSetI.H.
bitSet (const label n, const labelUList & locations) inline
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
Definition at line 110 of file bitSetI.H.
References Foam::FieldOps::assign().
bitSet (const label n, const IndirectListBase< label, Addr > & locations) inline
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
Definition at line 120 of file bitSetI.H.
References UList< T >::begin(), and UList< T >::end().
bitSet (const label n, const FixedList< label, N > & locations)
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
Definition at line 27 of file bitSetTemplates.C.
bitSet (const label n, std::initializer_list< label > locations) inline
Construct with given size with all bits set to 0, subsequently add specified locations as 1.
Definition at line 132 of file bitSetI.H.
References IndirectListBase< T, Addr >::begin(), and IndirectListBase< T, Addr >::end().
bitSet (const labelUList & locations) inline explicit
Construct with automatic sizing (filled with 0), and populate with specified locations as 1.
Definition at line 143 of file bitSetI.H.
bitSet (const IndirectListBase< label, Addr > & locations) inline explicit
Construct with automatic sizing (filled with 0), and populate with specified locations as 1.
Definition at line 153 of file bitSetI.H.
References UList< T >::begin(), and UList< T >::end().
bitSet (const FixedList< label, N > & locations) explicit
Construct with automatic sizing (filled with 0), and populate with specified locations as 1.
Definition at line 37 of file bitSetTemplates.C.
References FixedList< T, N >::begin(), and FixedList< T, N >::end().
Member Function Documentation
void writeEntry (Ostream & os) const protected
Write as a dictionary entry.
Definition at line 26 of file bitSetIO.C.
Foam::bitSet & minusEq (const bitSet & other) protected
The set difference.
*     A = (A - B)
*     A = (A & !B)
*     A = (A & ~B)
*
A and B can have different sizes. Does not change the original set size.
Definition at line 35 of file bitSet.C.
References Foam::defineTypeNameAndDebug().
Referenced by bitSet::flip(), and Foam::operator~().
Foam::bitSet & andEq (const bitSet & other) protected
The set logical AND.
*     A = (A & B)
*
*
A and B can have different sizes.. Does not change the original set size.
Definition at line 70 of file bitSet.C.
Referenced by bitSet::operator|=().
Foam::bitSet & orEq (const bitSet & other, const bool strict = true) protected
The set logical OR.
*     A = (A | B)
*
A and B can have different sizes
Note
The default (strict=true) ignores additional length from B, whereas (strict=false) permits the set to automatically grow to accommodate additional elements arising from B.
Definition at line 111 of file bitSet.C.
Referenced by bitSet::operator^=(), and bitSet::set().
Foam::bitSet & xorEq (const bitSet & other, const bool strict = true) protected
The set logical XOR.
*     A = (A ^ B)
*
A and B can have different sizes. Sizing behaviour as per orEq.
Definition at line 198 of file bitSet.C.
Referenced by bitSet::operator-=().
ClassName ("bitSet")
Define class name and debug.
Foam::autoPtr< Foam::bitSet > clone () const inline
Clone.
Definition at line 163 of file bitSetI.H.
References IndirectListBase< T, Addr >::begin(), and IndirectListBase< T, Addr >::end().
bool all () const inline
True if all bits in this bitset are set or if the set is empty.
Definition at line 447 of file bitSetI.H.
Referenced by bitSet::count().
bool any () const inline
True if any bits in this bitset are set.
Definition at line 453 of file bitSetI.H.
Referenced by bitSet::uniform(), and Foam::HashSetOps::used().
bool none () const inline
True if no bits in this bitset are set.
Definition at line 472 of file bitSetI.H.
Referenced by bitSet::count().
bool uniform () const inline
True if all entries have identical values, and the set is non-empty.
Definition at line 478 of file bitSetI.H.
References bitSet::any().
unsigned int count (const bool on = true) const inline
Count number of bits set.
Parameters
on can be set to false to count the number of unset bits instead.
Definition at line 484 of file bitSetI.H.
References bitSet::all(), bitSet::none(), PackedList< 1 >::size(), and bitSet::test().
Referenced by Foam::HashSetOps::used(), and cuttingSurfaceBase::walkCellCuts().
bool intersects (const bitSet & other) const
True if any bits in the other bitset intersect (are the same).
Note
Method name compatibility with boost::dynamic_bitset
Definition at line 341 of file bitSet.C.
References set().
bool test (const label pos) const inline
Test value at specified position, never auto-vivify entries.
Note
Method name compatibility with std::bitset
Definition at line 505 of file bitSetI.H.
Referenced by bitSet::count(), snappyLayerDriver::doLayers(), bitSet::operator[](), extendedEdgeMesh::sortPointsAndEdges(), and meshRefinement::zonify().
Foam::label find_first () const inline
Locate the first bit that is set.
Returns
the location or -1 if there are no bits set.
Note
Method name compatibility with boost::dynamic_bitset
Definition at line 307 of file bitSetI.H.
Referenced by Foam::HashSetOps::used().
Foam::label find_first_not () const inline
Locate the first bit that is unset.
Returns
the location or -1 if the set is empty or all bits are on.
Note
Provided for symmetry with find_first()
Definition at line 335 of file bitSetI.H.
Foam::label find_last () const inline
Locate the last bit set.
Returns
the location or -1 if there are no bits set.
Note
Provided for symmetry with find_first()
Definition at line 367 of file bitSetI.H.
Referenced by topoBitSet::updateLabels().
Foam::label find_next (label pos) const inline
Locate the next bit set, starting one beyond the specified position.
Returns
the location or -1 if there are no further bits set.
Note
Method name compatibility with boost::dynamic_bitset
Definition at line 393 of file bitSetI.H.
Referenced by Foam::HashSetOps::used().
Foam::labelList toc () const
The indices of the on bits as a sorted labelList.
Note
Method name compatibility with HashSet
Definition at line 520 of file bitSet.C.
Referenced by bitSet::swap().
Foam::labelList sortedToc () const inline
The indices of the on bits as a sorted labelList.
This is identical to toc(), which is always sorted.
Note
Method name compatibility with HashSet
Definition at line 511 of file bitSetI.H.
References Foam::pos().
Foam::List< bool > values () const
Return the bitset values as a boolList.
When the output is a bool, this is more efficient than unpack()
Definition at line 559 of file bitSet.C.
void assign (const bool val) inline
Assign all entries to the given value.
Definition at line 529 of file bitSetI.H.
References PackedList< Width >::transfer().
void assign (const UList< bool > & bools)
Copy assign all entries from a list of bools.
Definition at line 321 of file bitSet.C.
void set (const bitSet & bitset) inline
Set specified bits from another bitset.
The current set size may grow to accommodate any new bits (auto-vivifies).
Definition at line 556 of file bitSetI.H.
References PackedList< 1 >::blocks_.
Referenced by Foam::apply(), bitSet::bitSet(), Foam::BitSetOps::create(), meshRefinement::markOutsideFaces(), PatchTools::matchEdges(), bitSet::reference::operator unsigned int(), and bitSet::reference::operator=().
void set (const labelRange & range)
Set the specified range of bits specified.
The current set size may grow to accommodate any new bits (auto-vivifies).
Note
this operation is generally more efficient than calling set(pos) on individual bits.
Definition at line 361 of file bitSet.C.
Foam::bitSet & unset (const bitSet & other) inline
Unset (subtract) the bits specified in the other bitset, which is a set difference corresponds to the logical operation.
*     A = (A & !B)
*
The result is comparable to 'operator-='
A and B can have different sizes. Does not change the original set size.
Definition at line 594 of file bitSetI.H.
References IndirectListBase< T, Addr >::begin(), and IndirectListBase< T, Addr >::end().
Referenced by Foam::apply(), and bitSet::unset().
void unset (const labelRange & range)
Unset the specified range of bits specified, never auto-vivifies.
Note
this operation can be more efficient than calling unset(pos) on individual bits.
Definition at line 439 of file bitSet.C.
void flip () inline
Invert all bits in the addressable region.
Definition at line 600 of file bitSetI.H.
References bitSet::minusEq().
Referenced by Foam::operator&().
void flip (const label pos) inline
Invert bits at the specified position.
A no-op if the position is out-of-range
Definition at line 615 of file bitSetI.H.
void swap (bitSet & bitset) inline
Swap contents.
Definition at line 517 of file bitSetI.H.
References bitSet::toc().
void transfer (bitSet & bitset) inline
Transfer the contents of the argument list into this list and annul the argument list.
Definition at line 523 of file bitSetI.H.
References PackedList< Width >::swap().
Referenced by bitSet::operator&=().
Foam::bitSet & bound (const label maxSize) inline
Ensure the addressable range does not exceed maxSize.
Either decreases the size of the bitSet or is a no-op.
*     pointField& pts = mesh.points();
*     bitset.bound(pts.size());
*
*     for (const label pointi : bitset)
*     {
*         pts[pointi]  ...
*     }
*
Definition at line 624 of file bitSetI.H.
References bitSet::reference::flip().
Referenced by bitSet::extend().
Foam::bitSet & bound (const bitSet & other) inline
Ensure the addressable range does not exceed that of other.
Either decreases the size of the bitSet or is a no-op.
Definition at line 635 of file bitSetI.H.
Foam::bitSet & extend (const label minSize) inline
Ensure that minSize is covered by the bitSet.
Either increases the size of the bitSet or is a no-op.
Definition at line 641 of file bitSetI.H.
References bitSet::bound(), and PackedList< Width >::size().
Referenced by bitSet::operator()().
Foam::bitSet & extend (const bitSet & other) inline
Ensure the bitset is addressable throughout the range of other.
Either increases the size of the bitSet or is a no-op.
Definition at line 652 of file bitSetI.H.
label setMany (InputIter first, InputIter last)
Set the locations listed by the iterator range,.
auto-vivify entries if needed.
Returns
number of locations changed
Referenced by bitSet::set(), and bitSet::unset().
Foam::label set (const labelUList & locations) inline
Set the listed locations to true.
Does auto-vivify for non-existent entries.
Returns
number of locations changed
Definition at line 562 of file bitSetI.H.
References bitSet::orEq().
label set (const IndirectListBase< label, Addr > & locations) inline
Set the listed locations to true.
Does auto-vivify for non-existent entries.
Returns
number of locations changed
label set (const FixedList< label, N > & locations)
Set the listed locations to true.
Does auto-vivify for non-existent entries.
Returns
number of locations changed
label unset (InputIter first, InputIter last)
Unset the locations listed by the iterator range, never auto-vivify entries.
Returns
number of locations changed
Foam::label unset (const labelUList & locations) inline
Unset the listed locations, never auto-vivifies.
Returns
number of locations changed
Definition at line 578 of file bitSetI.H.
References IndirectListBase< T, Addr >::begin(), IndirectListBase< T, Addr >::end(), and bitSet::setMany().
label unset (const IndirectListBase< label, Addr > & locations) inline
Unset the listed locations, never auto-vivifies.
Returns
number of locations changed
label unset (const FixedList< label, N > & locations)
Unset the listed locations, never auto-vivifies.
Returns
number of locations changed
Foam::bitSet::const_iterator begin () const inline
Iterator set to the position of the first on bit.
Definition at line 271 of file bitSetI.H.
References iter.
Foam::bitSet::const_iterator cbegin () const inline
Iterator set to the position of the first on bit.
Definition at line 277 of file bitSetI.H.
Foam::bitSet::const_iterator begin (label pos) const inline
Iterator set to the position of the first on bit that occurs at or beyond the given position.
Definition at line 283 of file bitSetI.H.
Foam::bitSet::const_iterator cbegin (label pos) const inline
Iterator set to the position of the first on bit that occurs at or beyond the given position.
Definition at line 289 of file bitSetI.H.
Foam::bitSet::const_iterator end () const inline noexcept
Iterator beyond the end of the bitSet.
Definition at line 295 of file bitSetI.H.
Foam::bitSet::const_iterator cend () const inline noexcept
Iterator beyond the end of the bitSet.
Definition at line 301 of file bitSetI.H.
bool operator() (const label pos) const inline
Test value at specified position, same as test()
Enables use as a predicate
Definition at line 660 of file bitSetI.H.
References bitSet::extend().
unsigned int operator[] (const label i) const inline
Identical to get() - get value at index.
Never auto-vivify entries.
Definition at line 666 of file bitSetI.H.
References bitSet::test().
Foam::bitSet::reference operator[] (const label i) inline
Non-const access to value at index.
Fatal for out-of-range indices
Definition at line 672 of file bitSetI.H.
References i.
Foam::bitSet & operator= (const bool val) inline
Assignment of all entries to the given value.
Definition at line 681 of file bitSetI.H.
Foam::bitSet & operator= (const bitSet & bitset) inline
Copy assignment.
Definition at line 688 of file bitSetI.H.
References PackedList< Width >::operator=().
Foam::bitSet & operator= (bitSet && bitset) inline
Move assignment.
Definition at line 695 of file bitSetI.H.
References PackedList< Width >::operator=().
Foam::bitSet & operator&= (const bitSet & other) inline
Bitwise-AND all the bits in other with the bits in this bitset.
The operands may have dissimilar sizes without affecting the size of the set.
Definition at line 702 of file bitSetI.H.
References Foam::HashSetOps::bitset(), and bitSet::transfer().
Foam::bitSet & operator|= (const bitSet & other) inline
Bitwise-OR operator - similar to the set() method.
The operands may have dissimilar sizes without affecting the size of the set.
Definition at line 708 of file bitSetI.H.
References bitSet::andEq().
Foam::bitSet & operator^= (const bitSet & other) inline
Bitwise-XOR operator - retains unique entries.
The operands may have dissimilar sizes without affecting the size of the set.
Definition at line 714 of file bitSetI.H.
References bitSet::orEq().
Foam::bitSet & operator-= (const bitSet & other) inline
Remove entries from this list - identical to the unset() method.
The operands may have dissimilar sizes without affecting the size of the set.
Definition at line 720 of file bitSetI.H.
References bitSet::xorEq().
Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Write bitSet, with line-breaks (ASCII) when length exceeds shortLen.
Using '0' suppresses line-breaks entirely.
Definition at line 35 of file bitSetIO.C.
Referenced by Foam::operator<<().
void writeEntry (const word & keyword, Ostream & os) const
Write as a dictionary entry with keyword.
Definition at line 94 of file bitSetIO.C.
InfoProxy<bitSet> info () const inline
Return info proxy.
Definition at line 804 of file bitSet.H.
Foam::label set (const IndirectListBase< label, Addr > & locations) inline
Definition at line 570 of file bitSetI.H.
References UList< T >::begin(), UList< T >::end(), and bitSet::setMany().
Foam::label unset (const IndirectListBase< label, Addr > & locations) inline
Definition at line 586 of file bitSetI.H.
References UList< T >::begin(), UList< T >::end(), and bitSet::unset().
Foam::label setMany (InputIter first, InputIter last)
Definition at line 68 of file bitSetTemplates.C.
Foam::label unset (InputIter first, InputIter last)
Definition at line 94 of file bitSetTemplates.C.
Foam::label set (const FixedList< label, N > & locations)
Definition at line 111 of file bitSetTemplates.C.
Foam::label unset (const FixedList< label, N > & locations)
Definition at line 118 of file bitSetTemplates.C.
References FixedList< T, N >::begin(), and FixedList< T, N >::end().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Bits/bitSet/bitSet.H
src/OpenFOAM/containers/Bits/bitSet/bitSet.C
src/OpenFOAM/containers/Bits/bitSet/bitSetI.H
src/OpenFOAM/containers/Bits/bitSet/bitSetIO.C
src/OpenFOAM/containers/Bits/bitSet/bitSetTemplates.C