OpenFOAM: outputOptions Class Reference
outputOptions Class Reference
Encapsulated combinations of output format options. This is primarily useful when defining the output type based on some command-line arguments or dictionary contents. However, it can also be a useful alternative to using the underlying enumeration directly, since this class provides additional methods not possible with an enum.
Public Member Functions
outputOptions ()
Construct null - XML insitu ASCII format with default precision.
outputOptions (enum formatType fmtType)
Construct with specified format and default (ASCII) precision.
outputOptions (enum formatType fmtType, unsigned prec)
Construct with specified format and (ASCII) write precision.
autoPtr< formatter > newFormatter (std::ostream &os) const
Return new formatter based on the selected output options.
formatType fmt () const
The output format type.
word ext (vtk::fileTag contentType) const
The file extension (legacy or xml) for the given content-type.
bool legacy () const
True if writer uses legacy file format.
bool xml () const
True if writer uses XML file format (non-legacy)
bool append () const
True if output format uses an append mode.
bool insitu () const
True if output format does not use an append mode.
bool ascii () const
True if output format is ASCII.
unsigned precision () const
Return the ASCII write precision.
outputOptions & ascii (bool on)
Toggle ASCII mode on/off.
outputOptions & append (bool on)
Toggle append mode on/off.
outputOptions & legacy (bool on)
Toggle legacy mode on/off.
outputOptions & precision (unsigned prec)
Set the write precision to be used for new ASCII formatters.
string description () const
A text description about the output option selected.
Detailed Description
Encapsulated combinations of output format options. This is primarily useful when defining the output type based on some command-line arguments or dictionary contents. However, it can also be a useful alternative to using the underlying enumeration directly, since this class provides additional methods not possible with an enum.
Source files
foamVtkOutputOptions.H
foamVtkOutputOptions.C
foamVtkOutputOptionsI.H
Definition at line 55 of file foamVtkOutputOptions.H.
Constructor & Destructor Documentation
outputOptions () inline
Construct null - XML insitu ASCII format with default precision.
Definition at line 25 of file foamVtkOutputOptionsI.H.
outputOptions (enum formatType fmtType) inline
Construct with specified format and default (ASCII) precision.
Note
This constructor should remain non-explicit.
Definition at line 33 of file foamVtkOutputOptionsI.H.
References Foam::vtk::INLINE_ASCII.
outputOptions (enum formatType fmtType, unsigned prec) inline
Construct with specified format and (ASCII) write precision.
Definition at line 43 of file foamVtkOutputOptionsI.H.
Member Function Documentation
Foam::autoPtr< Foam::vtk::formatter > newFormatter (std::ostream & os) const inline
Return new formatter based on the selected output options.
Definition at line 56 of file foamVtkOutputOptionsI.H.
Referenced by Foam::vtk::writePointSet().
Foam::vtk::formatType fmt () const inline
The output format type.
Definition at line 64 of file foamVtkOutputOptionsI.H.
References Foam::vtk::newFormatter().
Foam::word ext (vtk::fileTag contentType) const inline
The file extension (legacy or xml) for the given content-type.
Definition at line 70 of file foamVtkOutputOptionsI.H.
bool legacy () const inline
True if writer uses legacy file format.
Definition at line 81 of file foamVtkOutputOptionsI.H.
Referenced by VTKsurfaceFormatCore::formatOptions(), VTPsurfaceFormatCore::formatOptions(), and Foam::vtk::writePointSet().
bool xml () const inline
True if writer uses XML file format (non-legacy)
Definition at line 91 of file foamVtkOutputOptionsI.H.
bool append () const inline
True if output format uses an append mode.
Definition at line 97 of file foamVtkOutputOptionsI.H.
Referenced by VTKsurfaceFormatCore::formatOptions(), VTPsurfaceFormatCore::formatOptions(), and Foam::vtk::writePointSet().
bool insitu () const inline
True if output format does not use an append mode.
Definition at line 107 of file foamVtkOutputOptionsI.H.
bool ascii () const inline
True if output format is ASCII.
Definition at line 113 of file foamVtkOutputOptionsI.H.
References append().
Referenced by VTKsurfaceFormatCore::formatOptions(), and VTPsurfaceFormatCore::formatOptions().
unsigned precision () const inline
Return the ASCII write precision.
Definition at line 119 of file foamVtkOutputOptionsI.H.
Referenced by VTKsurfaceFormatCore::formatOptions(), and VTPsurfaceFormatCore::formatOptions().
Foam::vtk::outputOptions & ascii (bool on)
Toggle ASCII mode on/off.
In XML append mode, this switches between base64 and raw binary. In XML inline mode, this switches between ASCII and base64. In legacy mode, this switches between ASCII and binary.
Returns
outputOptions for chaining
Definition at line 26 of file foamVtkOutputOptions.C.
References Foam::vtk::APPEND_BASE64, Foam::vtk::APPEND_BINARY, Foam::vtk::INLINE_ASCII, Foam::vtk::INLINE_BASE64, Foam::vtk::LEGACY_ASCII, and Foam::vtk::LEGACY_BINARY.
Foam::vtk::outputOptions & append (bool on)
Toggle append mode on/off.
Returns
outputOptions for chaining
Definition at line 74 of file foamVtkOutputOptions.C.
Foam::vtk::outputOptions & legacy (bool on)
Toggle legacy mode on/off.
Returns
outputOptions for chaining
Definition at line 116 of file foamVtkOutputOptions.C.
Foam::vtk::outputOptions & precision (unsigned prec)
Set the write precision to be used for new ASCII formatters.
Returns
outputOptions for chaining
Definition at line 158 of file foamVtkOutputOptions.C.
Foam::string description () const
A text description about the output option selected.
Definition at line 165 of file foamVtkOutputOptions.C.
The documentation for this class was generated from the following files:
src/fileFormats/vtk/output/foamVtkOutputOptions.H
src/fileFormats/vtk/output/foamVtkOutputOptions.C
src/fileFormats/vtk/output/foamVtkOutputOptionsI.H