OpenFOAM: refinementSurfaces Class Reference
refinementSurfaces Class Reference
Container for data on surfaces used for surface-driven refinement. Contains all the data about the level of refinement needed per surface.
Public Member Functions
refinementSurfaces (const searchableSurfaces &allGeometry, const dictionary &, const label gapLevelIncrement, const bool dryRun)
Construct from surfaces and dictionary.
refinementSurfaces (const searchableSurfaces &allGeometry, const labelList &surfaces, const wordList &names, const PtrList< surfaceZonesInfo > &surfZones, const labelList &regionOffset, const labelList &minLevel, const labelList &maxLevel, const labelList &gapLevel, const scalarField &perpendicularAngle, PtrList< dictionary > &patchInfo, const bool dryRun)
Construct from components.
const searchableSurfaces & geometry () const
const labelList & surfaces () const
const wordList & names () const
Names of surfaces.
const PtrList< surfaceZonesInfo > & surfZones () const
const labelList & regionOffset () const
From local region number to global region number.
const labelList & minLevel () const
From global region number to refinement level.
const labelList & maxLevel () const
From global region number to refinement level.
const labelList & gapLevel () const
From global region number to small gap refinement level.
const labelList & blockLevel () const
From global region number to cell level at which blockage detection is applied.
const List< FixedList< label, 3 > > & extendedGapLevel () const
From global region number to specification of gap and its.
const List< volumeType > & extendedGapMode () const
From global region number to side of surface to detect.
const scalarField & perpendicularAngle () const
From global region number to perpendicular angle.
const PtrList< dictionary > & patchInfo () const
From global region number to patch type.
label globalRegion (const label surfI, const label regionI) const
From surface and region on surface to global region.
label minLevel (const label surfI, const label regionI) const
Min level for surface and region on surface.
label maxLevel (const label surfI, const label regionI) const
Max level for surface and region on surface.
label nRegions () const
labelList maxGapLevel () const
Per surface the maximum extendedGapLevel over all its regions.
void setMinLevelFields (const shellSurfaces &shells)
Calculate minLevelFields.
void findHigherIntersection (const shellSurfaces &shells, const pointField &start, const pointField &end, const labelList &currentLevel, labelList &surfaces, labelList &surfaceLevel) const
Find intersection of edge. Return -1 or first surface.
void findAllIntersections (const pointField &start, const pointField &end, const labelList &currentLevel, const labelList &globalMinLevel, const labelList &globalMaxLevel, List< vectorList > &surfaceNormal, labelListList &surfaceLevel) const
Find all intersections of edge with any surface with applicable.
void findAllIntersections (const pointField &start, const pointField &end, const labelList &currentLevel, const labelList &globalMinLevel, const labelList &globalMaxLevel, List< pointList > &surfaceLocation, List< vectorList > &surfaceNormal, labelListList &surfaceLevel) const
Find all intersections of edge with any surface with applicable.
void findNearestIntersection (const labelList &surfacesToTest, const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &region1, labelList &surface2, List< pointIndexHit > &hit2, labelList &region2) const
Find intersection nearest to the endpoints. surface1,2 are.
void findNearestIntersection (const labelList &surfacesToTest, const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &region1, vectorField &normal1, labelList &surface2, List< pointIndexHit > &hit2, labelList &region2, vectorField &normal2) const
findNearestIntersection but also get normals
void findNearestIntersection (const pointField &start, const pointField &end, labelList &surfaces, vectorField &normal) const
Find nearest (to start only) intersection of edge.
void findNearestIntersection (const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &, vectorField &normal) const
Find nearest (to start only) intersection of edge.
void findAnyIntersection (const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &) const
Used for debugging only: find intersection of edge.
void findNearest (const labelList &surfacesToTest, const pointField &samples, const scalarField &nearestDistSqr, labelList &surfaces, List< pointIndexHit > &) const
Find nearest point on surfaces.
void findNearestRegion (const labelList &surfacesToTest, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, labelList &hitRegion) const
Find nearest point on surfaces. Return surface and region on.
void findNearestRegion (const labelList &surfacesToTest, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, List< pointIndexHit > &hitInfo, labelList &hitRegion, vectorField &hitNormal) const
Find nearest point on surfaces. Return surface, region and.
void findInside (const labelList &surfacesToTest, const pointField &pt, labelList &insideSurfaces) const
Detect if a point is 'inside' (closed) surfaces.
void findNearest (const labelList &surfacesToTest, const labelListList &regions, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, List< pointIndexHit > &hitInfo) const
Find nearest point on selected regions of surfaces.
void findNearestRegion (const labelList &surfacesToTest, const labelListList &regions, const pointField &samples, const scalarField &nearestDistSqr, labelList &hitSurface, List< pointIndexHit > &hitInfo, labelList &hitRegion, vectorField &hitNormal) const
Find nearest point on selected regions of surfaces.
Detailed Description
Container for data on surfaces used for surface-driven refinement. Contains all the data about the level of refinement needed per surface.
Source files
refinementSurfaces.H
refinementSurfaces.C
Definition at line 59 of file refinementSurfaces.H.
Constructor & Destructor Documentation
refinementSurfaces (const searchableSurfaces & allGeometry, const dictionary & surfacesDict, const label gapLevelIncrement, const bool dryRun)
Construct from surfaces and dictionary.
Definition at line 122 of file refinementSurfaces.C.
refinementSurfaces (const searchableSurfaces & allGeometry, const labelList & surfaces, const wordList & names, const PtrList< surfaceZonesInfo > & surfZones, const labelList & regionOffset, const labelList & minLevel, const labelList & maxLevel, const labelList & gapLevel, const scalarField & perpendicularAngle, PtrList< dictionary > & patchInfo, const bool dryRun)
Construct from components.
Definition at line 516 of file refinementSurfaces.C.
Member Function Documentation
const searchableSurfaces& geometry () const inline
Definition at line 200 of file refinementSurfaces.H.
const labelList& surfaces () const inline
Definition at line 205 of file refinementSurfaces.H.
Referenced by snappySnapDriver::detectNearSurfaces(), and snappySnapDriver::repatchToSurface().
const wordList& names () const inline
Names of surfaces.
Definition at line 213 of file refinementSurfaces.H.
const PtrList<surfaceZonesInfo>& surfZones () const inline
Definition at line 218 of file refinementSurfaces.H.
Referenced by snappySnapDriver::detectNearSurfaces(), and snappySnapDriver::repatchToSurface().
const labelList& regionOffset () const inline
From local region number to global region number.
Definition at line 226 of file refinementSurfaces.H.
const labelList& minLevel () const inline
From global region number to refinement level.
Definition at line 234 of file refinementSurfaces.H.
const labelList& maxLevel () const inline
From global region number to refinement level.
Definition at line 242 of file refinementSurfaces.H.
const labelList& gapLevel () const inline
From global region number to small gap refinement level.
Definition at line 250 of file refinementSurfaces.H.
const labelList& blockLevel () const inline
From global region number to cell level at which blockage detection is applied.
Definition at line 259 of file refinementSurfaces.H.
const List<FixedList<label, 3> >& extendedGapLevel () const inline
From global region number to specification of gap and its.
refinement: 3 labels specifying
minimum wanted number of cells in the gap
minimum cell level when to start trying to detect gaps
maximum cell level to refine to (so do not detect gaps if cell >= maximum level)
Definition at line 273 of file refinementSurfaces.H.
const List<volumeType>& extendedGapMode () const inline
From global region number to side of surface to detect.
Definition at line 281 of file refinementSurfaces.H.
const scalarField& perpendicularAngle () const inline
From global region number to perpendicular angle.
Definition at line 289 of file refinementSurfaces.H.
const PtrList<dictionary>& patchInfo () const inline
From global region number to patch type.
Definition at line 297 of file refinementSurfaces.H.
label globalRegion (const label surfI, const label regionI) const inline
From surface and region on surface to global region.
Definition at line 308 of file refinementSurfaces.H.
Referenced by snappySnapDriver::repatchToSurface().
label minLevel (const label surfI, const label regionI) const inline
Min level for surface and region on surface.
Definition at line 316 of file refinementSurfaces.H.
label maxLevel (const label surfI, const label regionI) const inline
Max level for surface and region on surface.
Definition at line 324 of file refinementSurfaces.H.
label nRegions () const inline
Definition at line 329 of file refinementSurfaces.H.
Foam::labelList maxGapLevel () const
Per surface the maximum extendedGapLevel over all its regions.
Definition at line 609 of file refinementSurfaces.C.
References forAll, Foam::max(), and Foam::Zero.
void setMinLevelFields (const shellSurfaces & shells)
Calculate minLevelFields.
Definition at line 630 of file refinementSurfaces.C.
void findHigherIntersection (const shellSurfaces & shells, const pointField & start, const pointField & end, const labelList & currentLevel, labelList & surfaces, labelList & surfaceLevel) const
Find intersection of edge. Return -1 or first surface.
with higher (than currentLevel) minlevel. Return surface number and level.
Definition at line 763 of file refinementSurfaces.C.
void findAllIntersections (const pointField & start, const pointField & end, const labelList & currentLevel, const labelList & globalMinLevel, const labelList & globalMaxLevel, List< vectorList > & surfaceNormal, labelListList & surfaceLevel) const
Find all intersections of edge with any surface with applicable.
min/max refinement level. Unsorted order.
Definition at line 925 of file refinementSurfaces.C.
void findAllIntersections (const pointField & start, const pointField & end, const labelList & currentLevel, const labelList & globalMinLevel, const labelList & globalMaxLevel, List< pointList > & surfaceLocation, List< vectorList > & surfaceNormal, labelListList & surfaceLevel) const
Find all intersections of edge with any surface with applicable.
min/max refinement level. Unsorted order.
Definition at line 1018 of file refinementSurfaces.C.
void findNearestIntersection (const labelList & surfacesToTest, const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & region1, labelList & surface2, List< pointIndexHit > & hit2, labelList & region2) const
Find intersection nearest to the endpoints. surface1,2 are.
not indices into surfacesToTest but refinement surface indices. Returns surface, region on surface (so not global surface) and position on surface.
Definition at line 1115 of file refinementSurfaces.C.
Referenced by snappySnapDriver::detectNearSurfaces().
void findNearestIntersection (const labelList & surfacesToTest, const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & region1, vectorField & normal1, labelList & surface2, List< pointIndexHit > & hit2, labelList & region2, vectorField & normal2) const
findNearestIntersection but also get normals
Definition at line 1245 of file refinementSurfaces.C.
void findNearestIntersection (const pointField & start, const pointField & end, labelList & surfaces, vectorField & normal) const
Find nearest (to start only) intersection of edge.
Definition at line 1368 of file refinementSurfaces.C.
void findNearestIntersection (const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo1, vectorField & normal) const
Find nearest (to start only) intersection of edge.
Definition at line 1411 of file refinementSurfaces.C.
void findAnyIntersection (const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo) const
Used for debugging only: find intersection of edge.
Definition at line 1461 of file refinementSurfaces.C.
void findNearest (const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, labelList & surfaces, List< pointIndexHit > & hitInfo) const
Find nearest point on surfaces.
Definition at line 1482 of file refinementSurfaces.C.
void findNearestRegion (const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, labelList & hitRegion) const
Find nearest point on surfaces. Return surface and region on.
surface (so not global surface)
Definition at line 1515 of file refinementSurfaces.C.
Referenced by snappySnapDriver::repatchToSurface().
void findNearestRegion (const labelList & surfacesToTest, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, List< pointIndexHit > & hitInfo, labelList & hitRegion, vectorField & hitNormal) const
Find nearest point on surfaces. Return surface, region and.
normal on surface (so not global surface)
Definition at line 1578 of file refinementSurfaces.C.
void findInside (const labelList & surfacesToTest, const pointField & pt, labelList & insideSurfaces) const
Detect if a point is 'inside' (closed) surfaces.
Returns -1 if not, returns first surface it is.
Definition at line 1699 of file refinementSurfaces.C.
References surfaceZonesInfo::areaSelectionAlgoNames, Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, searchableSurface::getVolumeType(), searchableSurface::hasVolumeType(), i, surfaceZonesInfo::INSIDE, volumeType::INSIDE, IOobject::name(), surfaceZonesInfo::OUTSIDE, volumeType::OUTSIDE, List< T >::setSize(), and UList< T >::size().
void findNearest (const labelList & surfacesToTest, const labelListList & regions, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, List< pointIndexHit > & hitInfo) const
Find nearest point on selected regions of surfaces.
Definition at line 1762 of file refinementSurfaces.C.
void findNearestRegion (const labelList & surfacesToTest, const labelListList & regions, const pointField & samples, const scalarField & nearestDistSqr, labelList & hitSurface, List< pointIndexHit > & hitInfo, labelList & hitRegion, vectorField & hitNormal) const
Find nearest point on selected regions of surfaces.
Definition at line 1799 of file refinementSurfaces.C.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/refinementSurfaces/refinementSurfaces.H
src/mesh/snappyHexMesh/refinementSurfaces/refinementSurfaces.C