OpenFOAM: token Class Reference
token Class Reference
A token holds an item read from Istream.
Classes
class Compound
A templated class for holding compound tokens.
class compound
Abstract base class for complex tokens.
Public Types
enum tokenType {
UNDEFINED = 0, FLAG, PUNCTUATION, BOOL,
LABEL, FLOAT_SCALAR, DOUBLE_SCALAR, WORD,
STRING, VARIABLE, VERBATIMSTRING, COMPOUND,
ERROR
}
Enumeration defining the types of token.
enum flagType { NO_FLAG = 0, ASCII = 1, BINARY = 2 }
Stream or output control flags (1-byte width)
enum punctuationToken : char {
NULL_TOKEN = '\0', SPACE = ' ', TAB = '\t', NL = '\n',
END_STATEMENT = ';', BEGIN_LIST = '(', END_LIST = ')', BEGIN_SQR = '[',
END_SQR = ']', BEGIN_BLOCK = '{', END_BLOCK = '}', COLON = ':',
COMMA = ',', HASH = '#', DOLLAR = '$', ATSYM = '@',
SQUOTE = '\'', DQUOTE = '"', ASSIGN = '=', ADD = '+',
SUBTRACT = '-', MULTIPLY = '*', DIVIDE = '/', BEGIN_STRING = DQUOTE,
END_STRING = DQUOTE
}
Standard punctuation tokens (a character)
Public Member Functions
constexpr token () noexcept
Construct null, initialized to an UNDEFINED token.
token (const token &t)
Copy construct.
token (token &&t)
Move construct. The original token is left as UNDEFINED.
token (punctuationToken p, label lineNumber=0)
Construct punctuation character token.
token (const label val, label lineNumber=0)
Construct label token.
token (const floatScalar val, label lineNumber=0)
Construct float token.
token (const doubleScalar val, label lineNumber=0)
Construct double token.
token (const word &w, label lineNumber=0)
Copy construct word token.
token (const string &str, label lineNumber=0)
Copy construct string token.
token (word &&w, label lineNumber=0)
Move construct word token.
token (string &&str, label lineNumber=0)
Move construct string token.
token (Istream &is)
Construct from Istream.
~token ()
Destructor.
word name () const
Return the name of the token type.
tokenType type () const
Return the token type.
bool setType (const tokenType variant)
Change the token type, for similar types.
label lineNumber () const
The line number for the token.
label & lineNumber ()
The line number for the token.
bool good () const
True if token is not UNDEFINED or ERROR.
bool undefined () const
Token is UNDEFINED.
bool error () const
Token is ERROR.
bool isBool () const
Token is BOOL.
bool isFlag () const
Token is FLAG.
bool isPunctuation () const
Token is PUNCTUATION.
bool isSeparator () const
Token is PUNCTUATION and isseparator.
bool isLabel () const
Token is LABEL.
bool isFloatScalar () const
Token is FLOAT_SCALAR.
bool isDoubleScalar () const
Token is DOUBLE_SCALAR.
bool isScalar () const
Token is FLOAT_SCALAR or DOUBLE_SCALAR.
bool isNumber () const
Token is LABEL, FLOAT_SCALAR or DOUBLE_SCALAR.
bool isWord () const
Token is WORD.
bool isString () const
Token is STRING, VARIABLE or VERBATIM string.
bool isVariable () const
Token is VARIABLE.
bool isVerbatim () const
Token is VERBATIM string.
bool isStringType () const
Token is WORD, STRING, VARIABLE or VERBATIM.
bool isCompound () const
Token is COMPOUND.
bool boolToken () const
Return boolean token value.
int flagToken () const
Return flag bitmask value.
punctuationToken pToken () const
Return punctuation character.
label labelToken () const
Return label value.
floatScalar floatScalarToken () const
Return float value.
doubleScalar doubleScalarToken () const
Return double value.
scalar scalarToken () const
Return float or double value.
scalar number () const
Return label, float or double value.
const word & wordToken () const
Return const reference to the word contents.
const string & stringToken () const
Return const reference to the string contents.
const compound & compoundToken () const
Read access for compound token.
compound & transferCompoundToken (const Istream &is)
Return reference to compound token and decrease its internal refCound accordingly.
void reset ()
Reset token to UNDEFINED and clear any allocated storage.
void setBad ()
Clear token and set to be ERROR.
void swap (token &tok)
Swap token contents: type, data, line-number.
InfoProxy< token > info () const
Return info proxy for printing token information to a stream.
void operator= (const token &tok)
Copy assign.
void operator= (token &&tok)
Move assign.
void operator= (const punctuationToken p)
Copy assign from punctuation.
void operator= (const label val)
Copy assign from label.
void operator= (const floatScalar val)
Copy assign from float.
void operator= (const doubleScalar val)
Copy assign from double.
void operator= (const word &w)
Copy assign from word.
void operator= (const string &str)
Copy assign from string.
void operator= (word &&w)
Move assign from word.
void operator= (string &&str)
Move assign from string.
void operator= (compound *compoundPtr)
Assign compound with reference counting to token.
bool operator== (const token &tok) const
bool operator== (const punctuationToken p) const
bool operator== (const label val) const
bool operator== (const floatScalar val) const
bool operator== (const doubleScalar val) const
bool operator== (const std::string &s) const
bool operator!= (const token &tok) const
bool operator!= (const punctuationToken p) const
bool operator!= (const label val) const
bool operator!= (const floatScalar val) const
bool operator!= (const doubleScalar val) const
bool operator!= (const std::string &s) const
void operator= (word *)=delete
Deprecated(2017-11) transfer word pointer to the token.
void operator= (string *)=delete
Deprecated(2017-11) transfer string pointer to the token.
Static Public Member Functions
static token boolean (bool on)
Create a bool token.
static token flag (int bitmask)
Create a token with stream flags, no sanity check.
static bool isseparator (int c)
True if the character is a punctuation separator (eg, in ISstream).
Static Public Attributes
static const token undefinedToken
An undefined token.
static constexpr const char *const typeName = "token"
The type name is "token".
Friends
Ostream & operator<< (Ostream &os, const token &tok)
Ostream & operator<< (Ostream &os, const punctuationToken &pt)
ostream & operator<< (ostream &os, const punctuationToken &pt)
ostream & operator<< (ostream &os, const InfoProxy< token > &ct)
Detailed Description
A token holds an item read from Istream.
Source files
token.H
tokenI.H
token.C
tokenIO.C
Definition at line 65 of file token.H.
Member Enumeration Documentation
enum tokenType
Enumeration defining the types of token.
Since these values are also used to tag content in Pstream, the maximum number of types is limited to 30.
Enumerator
UNDEFINED
An undefined token-type.
FLAG
stream flag (1-byte bitmask)
PUNCTUATION
single character punctuation
BOOL
boolean type
LABEL
label (integer) type
FLOAT_SCALAR
float (single-precision) type
DOUBLE_SCALAR
double (double-precision) type
WORD
A Foam::word.
STRING
A string.
VARIABLE
A dictionary $variable (string variant)
VERBATIMSTRING
Verbatim string content.
COMPOUND
Compound type such as List<label> etc.
ERROR
A token error encountered.
Definition at line 75 of file token.H.
enum flagType
Stream or output control flags (1-byte width)
Enumerator
NO_FLAG
No flags.
ASCII
ASCII-mode stream.
BINARY
BINARY-mode stream.
Definition at line 101 of file token.H.
enum punctuationToken : char
Standard punctuation tokens (a character)
Enumerator
NULL_TOKEN
Nul character.
SPACE
Space [isspace].
TAB
Tab [isspace].
NL
Newline [isspace].
END_STATEMENT
End entry [isseparator].
BEGIN_LIST
Begin list [isseparator].
END_LIST
End list [isseparator].
BEGIN_SQR
Begin dimensions [isseparator].
END_SQR
End dimensions [isseparator].
BEGIN_BLOCK
Begin block [isseparator].
END_BLOCK
End block [isseparator].
COLON
Colon [isseparator].
COMMA
Comma [isseparator].
HASH
Hash - directive or verbatim string.
DOLLAR
Dollar - start variable.
ATSYM
At.
SQUOTE
Single quote.
DQUOTE
Double quote.
ASSIGN
Assignment/equals [isseparator].
ADD
Addition [isseparator].
SUBTRACT
Subtract or start of negative number.
MULTIPLY
Multiply [isseparator].
DIVIDE
Divide [isseparator].
BEGIN_STRING
Begin string with double quote.
END_STRING
End string with double quote.
Definition at line 112 of file token.H.
Constructor & Destructor Documentation
constexpr token () inline noexcept
Construct null, initialized to an UNDEFINED token.
Definition at line 88 of file tokenI.H.
token (const token & t) inline
Copy construct.
Definition at line 96 of file tokenI.H.
token (token && t) inline
Move construct. The original token is left as UNDEFINED.
Definition at line 135 of file tokenI.H.
token (punctuationToken p, label lineNumber = 0) inline explicit
Construct punctuation character token.
Definition at line 146 of file tokenI.H.
token (const label val, label lineNumber = 0) inline explicit
Construct label token.
Definition at line 156 of file tokenI.H.
References p.
token (const floatScalar val, label lineNumber = 0) inline explicit
Construct float token.
Definition at line 166 of file tokenI.H.
References Foam::val.
token (const doubleScalar val, label lineNumber = 0) inline explicit
Construct double token.
Definition at line 176 of file tokenI.H.
References Foam::val.
token (const word & w, label lineNumber = 0) inline explicit
Copy construct word token.
Definition at line 186 of file tokenI.H.
References Foam::val.
token (const string & str, label lineNumber = 0) inline explicit
Copy construct string token.
Definition at line 196 of file tokenI.H.
token (word && w, label lineNumber = 0) inline explicit
Move construct word token.
Definition at line 206 of file tokenI.H.
token (string && str, label lineNumber = 0) inline explicit
Move construct string token.
Definition at line 216 of file tokenI.H.
token (Istream & is) explicit
Construct from Istream.
Definition at line 109 of file tokenIO.C.
~token () inline
Destructor.
Definition at line 228 of file tokenI.H.
Member Function Documentation
Foam::token boolean (bool on) inline static
Create a bool token.
Definition at line 26 of file tokenI.H.
Foam::token flag (int bitmask) inline static
Create a token with stream flags, no sanity check.
Parameters
bitmask the flags to set
Definition at line 36 of file tokenI.H.
bool isseparator (int c) inline static
True if the character is a punctuation separator (eg, in ISstream).
Since it could also start a number, SUBTRACT is not included as a separator.
Parameters
c the character to test, passed as int for consistency with isdigit, isspace etc.
Definition at line 46 of file tokenI.H.
Foam::word name () const
Return the name of the token type.
Definition at line 119 of file tokenIO.C.
Foam::token::tokenType type () const inline
Return the token type.
Definition at line 288 of file tokenI.H.
Referenced by Foam::printTokenInfo(), and OSstream::write().
bool setType (const tokenType variant) inline
Change the token type, for similar types.
This can be used to change between string-like variants (eg, STRING, VARIABLE, etc) To change types entirely (eg, STRING to DOUBLE_SCALAR), use the corresponding assignment operator.
Returns
true if the change was successful or no change was required
Definition at line 294 of file tokenI.H.
Foam::label lineNumber () const inline
The line number for the token.
Definition at line 349 of file tokenI.H.
Referenced by Foam::printTokenInfo().
Foam::label & lineNumber () inline
The line number for the token.
Definition at line 355 of file tokenI.H.
bool good () const inline
True if token is not UNDEFINED or ERROR.
Definition at line 361 of file tokenI.H.
Referenced by Foam::getToken(), Foam::operator>>(), and OTstream::write().
bool undefined () const inline
Token is UNDEFINED.
Definition at line 367 of file tokenI.H.
bool error () const inline
Token is ERROR.
Definition at line 373 of file tokenI.H.
bool isBool () const inline
Token is BOOL.
Definition at line 379 of file tokenI.H.
bool isFlag () const inline
Token is FLAG.
Definition at line 397 of file tokenI.H.
bool isPunctuation () const inline
Token is PUNCTUATION.
Definition at line 415 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::blockMeshTools::read(), and PtrList< T >::readIstream().
bool isSeparator () const inline
Token is PUNCTUATION and isseparator.
Definition at line 433 of file tokenI.H.
bool isLabel () const inline
Token is LABEL.
Definition at line 443 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::blockMeshTools::read(), STARCDMeshReader::readBoundary(), STARCDMeshReader::readCells(), PtrList< T >::readIstream(), and STARCDMeshReader::readPoints().
bool isFloatScalar () const inline
Token is FLOAT_SCALAR.
Definition at line 461 of file tokenI.H.
bool isDoubleScalar () const inline
Token is DOUBLE_SCALAR.
Definition at line 479 of file tokenI.H.
bool isScalar () const inline
Token is FLOAT_SCALAR or DOUBLE_SCALAR.
Definition at line 497 of file tokenI.H.
bool isNumber () const inline
Token is LABEL, FLOAT_SCALAR or DOUBLE_SCALAR.
Definition at line 523 of file tokenI.H.
bool isWord () const inline
Token is WORD.
Definition at line 545 of file tokenI.H.
Referenced by Function1< Type >::New(), PatchFunction1< Type >::New(), Foam::operator>>(), Foam::blockMeshTools::read(), IOobject::readHeader(), and mappedPatchBase::readListOrField().
bool isString () const inline
Token is STRING, VARIABLE or VERBATIM string.
Definition at line 563 of file tokenI.H.
bool isVariable () const inline
Token is VARIABLE.
Definition at line 574 of file tokenI.H.
bool isVerbatim () const inline
Token is VERBATIM string.
Definition at line 580 of file tokenI.H.
bool isStringType () const inline
Token is WORD, STRING, VARIABLE or VERBATIM.
Definition at line 586 of file tokenI.H.
Referenced by functionEntry::readStringList().
bool isCompound () const inline
Token is COMPOUND.
Definition at line 614 of file tokenI.H.
bool boolToken () const inline
Return boolean token value.
Report FatalIOError and return false if token is not BOOL or LABEL
Definition at line 385 of file tokenI.H.
Referenced by Foam::printTokenInfo().
int flagToken () const inline
Return flag bitmask value.
Report FatalIOError and return NO_FLAG if token is not FLAG
Definition at line 403 of file tokenI.H.
Referenced by Foam::printTokenInfo().
Foam::token::punctuationToken pToken () const inline
Return punctuation character.
Report FatalIOError and return \0 if token is not PUNCTUATION
Definition at line 421 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::printTokenInfo(), Foam::blockMeshTools::read(), and PtrList< T >::readIstream().
Foam::label labelToken () const inline
Return label value.
Report FatalIOError and return 0 if token is not LABEL
Definition at line 449 of file tokenI.H.
Referenced by Foam::operator>>(), Foam::printTokenInfo(), Foam::blockMeshTools::read(), STARCDMeshReader::readCells(), PtrList< T >::readIstream(), and STARCDMeshReader::readPoints().
Foam::floatScalar floatScalarToken () const inline
Return float value.
Report FatalIOError and return 0 if token is not FLOAT_SCALAR
Definition at line 467 of file tokenI.H.
Referenced by Foam::printTokenInfo().
Foam::doubleScalar doubleScalarToken () const inline
Return double value.
Report FatalIOError and return 0 if token is not DOUBLE_SCALAR
Definition at line 485 of file tokenI.H.
Referenced by Foam::printTokenInfo().
Foam::scalar scalarToken () const inline
Return float or double value.
Report FatalIOError and return 0 if token is not a FLOAT_SCALAR or DOUBLE_SCALAR
Definition at line 507 of file tokenI.H.
Foam::scalar number () const inline
Return label, float or double value.
Report FatalIOError and return 0 if token is not a LABEL, FLOAT_SCALAR or DOUBLE_SCALAR
Definition at line 529 of file tokenI.H.
const Foam::word & wordToken () const inline
Return const reference to the word contents.
Report FatalIOError and return "" if token is not a WORD
Definition at line 551 of file tokenI.H.
Referenced by Function1< Type >::New(), PatchFunction1< Type >::New(), Foam::operator>>(), Foam::printTokenInfo(), Foam::blockMeshTools::read(), IOobject::readHeader(), and mappedPatchBase::readListOrField().
const Foam::string & stringToken () const inline
Return const reference to the string contents.
Report FatalIOError and return "" if token is not a STRING, VARIABLE, VERBATIM or an upcast WORD
Definition at line 592 of file tokenI.H.
Referenced by Foam::printTokenInfo(), and OSstream::write().
const Foam::token::compound & compoundToken () const inline
Read access for compound token.
Definition at line 620 of file tokenI.H.
Referenced by Foam::printTokenInfo().
Foam::token::compound & transferCompoundToken (const Istream & is)
Return reference to compound token and decrease its internal refCound accordingly.
The Istream is used for reference error messages only.
Definition at line 83 of file token.C.
void reset () inline
Reset token to UNDEFINED and clear any allocated storage.
Definition at line 236 of file tokenI.H.
References reset().
Referenced by Foam::operator<<().
void setBad () inline
Clear token and set to be ERROR.
Definition at line 632 of file tokenI.H.
void swap (token & tok) inline
Swap token contents: type, data, line-number.
Definition at line 275 of file tokenI.H.
InfoProxy<token> info () const inline
Return info proxy for printing token information to a stream.
Definition at line 679 of file token.H.
Referenced by Foam::operator>>(), Foam::blockMeshTools::read(), and PtrList< T >::readIstream().
void operator= (const token & tok) inline
Copy assign.
Definition at line 641 of file tokenI.H.
void operator= (token && tok) inline
Move assign.
Definition at line 687 of file tokenI.H.
void operator= (const punctuationToken p) inline
Copy assign from punctuation.
Definition at line 700 of file tokenI.H.
void operator= (const label val) inline
Copy assign from label.
Definition at line 708 of file tokenI.H.
References p, and reset().
void operator= (const floatScalar val) inline
Copy assign from float.
Definition at line 716 of file tokenI.H.
References reset(), and Foam::val.
void operator= (const doubleScalar val) inline
Copy assign from double.
Definition at line 724 of file tokenI.H.
References reset(), and Foam::val.
void operator= (const word & w) inline
Copy assign from word.
Definition at line 732 of file tokenI.H.
References reset(), and Foam::val.
void operator= (const string & str) inline
Copy assign from string.
Definition at line 740 of file tokenI.H.
References reset().
void operator= (word && w) inline
Move assign from word.
Definition at line 748 of file tokenI.H.
References reset().
void operator= (string && str) inline
Move assign from string.
Definition at line 756 of file tokenI.H.
References reset().
void operator= (compound * compoundPtr) inline
Assign compound with reference counting to token.
Definition at line 764 of file tokenI.H.
References reset(), and s.
bool operator== (const token & tok) const inline
Definition at line 772 of file tokenI.H.
References reset().
bool operator== (const punctuationToken p) const inline
Definition at line 821 of file tokenI.H.
bool operator== (const label val) const inline
Definition at line 838 of file tokenI.H.
bool operator== (const floatScalar val) const inline
Definition at line 848 of file tokenI.H.
bool operator== (const doubleScalar val) const inline
Definition at line 858 of file tokenI.H.
bool operator== (const std::string & s) const inline
Definition at line 827 of file tokenI.H.
bool operator!= (const token & tok) const inline
Definition at line 868 of file tokenI.H.
bool operator!= (const punctuationToken p) const inline
Definition at line 874 of file tokenI.H.
References Foam::operator==().
bool operator!= (const label val) const inline
Definition at line 880 of file tokenI.H.
References Foam::operator==().
bool operator!= (const floatScalar val) const inline
Definition at line 886 of file tokenI.H.
References Foam::operator==().
bool operator!= (const doubleScalar val) const inline
Definition at line 892 of file tokenI.H.
References Foam::operator==().
bool operator!= (const std::string & s) const inline
Definition at line 898 of file tokenI.H.
References Foam::operator==().
void operator= (word *) delete
Deprecated(2017-11) transfer word pointer to the token.
Deprecated:
(2017-11) - use move assign from word
void operator= (string *) delete
Deprecated(2017-11) transfer string pointer to the token.
Deprecated:
(2017-11) - use move assign from string
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const token & tok) friend
Ostream& operator<< (Ostream & os, const punctuationToken & pt) friend
ostream& operator<< (ostream & os, const punctuationToken & pt) friend
ostream& operator<< (ostream & os, const InfoProxy< token > & ct) friend
Member Data Documentation
const Foam::token undefinedToken static
An undefined token.
Definition at line 276 of file token.H.
constexpr const char* const typeName = "token" static
The type name is "token".
Definition at line 341 of file token.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/token/token.H
src/OpenFOAM/db/IOstreams/token/token.C
src/OpenFOAM/db/IOstreams/token/tokenI.H
src/OpenFOAM/db/IOstreams/token/tokenIO.C