OpenFOAM: surfacePatch Class Reference
surfacePatch Class Reference
'Patch' on surface as subset of triSurface.
Public Member Functions
ClassName ("surfacePatch")
Runtime type information.
surfacePatch ()
Construct null.
surfacePatch (const label index)
Construct null with specified index.
surfacePatch (const word &geometricType, const word &name, const label size, const label start, const label index)
Construct from components.
surfacePatch (Istream &is, const label index)
Construct from Istream.
surfacePatch (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
surfacePatch (const surfacePatch &)
Construct as copy.
label start () const
Return start label of this patch in the face list.
label & start ()
Return start label of this patch in the face list.
label size () const
Return size of this patch in the face list.
label & size ()
Return size of this patch in the face list.
void write (Ostream &) const
Write.
void writeDict (Ostream &) const
Write dictionary.
operator surfZone () const
Conversion to surfZone representation.
bool operator!= (const surfacePatch &) const
Compare.
bool operator== (const surfacePatch &) const
Compare.
Public Member Functions inherited from geometricSurfacePatch
ClassName ("geometricSurfacePatch")
Runtime type information.
geometricSurfacePatch ()
Construct null.
geometricSurfacePatch (const label index)
Construct null with specified index.
geometricSurfacePatch (const word &name, const label index, const word &geometricType=word::null)
Construct from components.
geometricSurfacePatch (const word &geometricType, const word &name, const label index)
Construct from components.
geometricSurfacePatch (const surfZoneIdentifier &ident)
Implicit conversion from surfZoneIdentifier, which has similar information but in a different order.
geometricSurfacePatch (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
geometricSurfacePatch (Istream &is, const label index)
Construct from Istream.
const word & name () const
Return name.
word & name ()
Return name.
const word & geometricType () const
Return the geometric type of the patch.
word & geometricType ()
Return the geometric type of the patch for modification.
label index () const
Return the index of this patch in the surface mesh.
label & index ()
Return the index of this patch in the surface mesh for modification.
void write (Ostream &os) const
Write.
void writeDict (Ostream &os) const
Write dictionary.
Friends
Ostream & operator<< (Ostream &, const surfacePatch &)
Additional Inherited Members
Static Public Attributes inherited from geometricSurfacePatch
static const word emptyType = "empty"
The name for an 'empty' type.
Detailed Description
'Patch' on surface as subset of triSurface.
Source files
surfacePatch.H
surfacePatch.C
Definition at line 56 of file surfacePatch.H.
Constructor & Destructor Documentation
surfacePatch ()
Construct null.
Definition at line 36 of file surfacePatch.C.
References Foam::defineTypeNameAndDebug().
surfacePatch (const label index) explicit
Construct null with specified index.
Definition at line 44 of file surfacePatch.C.
surfacePatch (const word & geometricType, const word & name, const label size, const label start, const label index)
Construct from components.
Definition at line 53 of file surfacePatch.C.
surfacePatch (Istream & is, const label index)
Construct from Istream.
Definition at line 67 of file surfacePatch.C.
surfacePatch (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 78 of file surfacePatch.C.
surfacePatch (const surfacePatch & sp)
Construct as copy.
Definition at line 90 of file surfacePatch.C.
Member Function Documentation
ClassName ("surfacePatch")
Runtime type information.
label start () const inline
Return start label of this patch in the face list.
Definition at line 130 of file surfacePatch.H.
Referenced by surfacePatch::writeDict().
label& start () inline
Return start label of this patch in the face list.
Definition at line 138 of file surfacePatch.H.
label size () const inline
Return size of this patch in the face list.
Definition at line 146 of file surfacePatch.H.
Referenced by surfacePatch::writeDict().
label& size () inline
Return size of this patch in the face list.
Definition at line 154 of file surfacePatch.H.
void write (Ostream & os) const
Write.
Definition at line 100 of file surfacePatch.C.
void writeDict (Ostream & os) const
Write dictionary.
Definition at line 107 of file surfacePatch.C.
References Foam::endl(), Foam::nl, surfacePatch::size(), surfacePatch::start(), and Foam::tab.
operator surfZone () const explicit
Conversion to surfZone representation.
bool operator!= (const surfacePatch & p) const
Compare.
Definition at line 134 of file surfacePatch.C.
bool operator== (const surfacePatch & p) const
Compare.
Definition at line 140 of file surfacePatch.C.
References p.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const surfacePatch &) friend
The documentation for this class was generated from the following files:
src/surfMesh/triSurface/patches/surfacePatch.H
src/surfMesh/triSurface/patches/surfacePatch.C