OpenFOAM: lduMatrix Class Reference
lduMatrix Class Reference
lduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
Classes
class preconditioner
Abstract base-class for lduMatrix preconditioners.
class smoother
Abstract base-class for lduMatrix smoothers.
class solver
Abstract base-class for lduMatrix solvers.
Public Member Functions
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
Construct given an LDU addressed mesh.
lduMatrix (const lduMatrix &)
Construct as copy.
lduMatrix (lduMatrix &, bool reuse)
Construct as copy or re-use as specified.
lduMatrix (const lduMesh &, Istream &)
Construct given an LDU addressed mesh and an Istream from which the coefficients are read.
~lduMatrix ()
Destructor.
const lduMesh & mesh () const
Return the LDU mesh from which the addressing is obtained.
const lduAddressing & lduAddr () const
Return the LDU addressing.
const lduSchedule & patchSchedule () const
Return the patch evaluation schedule.
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const
bool hasUpper () const
bool hasLower () const
bool diagonal () const
bool symmetric () const
bool asymmetric () const
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix multiplication with updated interfaces.
void Tmul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
void sumA (solveScalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
Sum the coefficients on each row of the matrix.
void residual (solveScalarField &rA, const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< solveScalarField > residual (const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
Initialise the update of interfaced interfaces for matrix operations.
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
void setResidualField (const scalarField &residual, const word &fieldName, const bool initial) const
Set the residual field using an IOField on the object registry if it exists.
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type >> &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type >> &) const
InfoProxy< lduMatrix > info () const
Return info proxy.
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type >> &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type >> &tpsi) const
Friends
Ostream & operator<< (Ostream &, const lduMatrix &)
Ostream & operator<< (Ostream &, const InfoProxy< lduMatrix > &)
Detailed Description
lduMatrix is a general matrix class in which the coefficients are stored as three arrays, one for the upper triangle, one for the lower triangle and a third for the diagonal.
Addressing arrays must be supplied for the upper and lower triangles.
It might be better if this class were organised as a hierachy starting from an empty matrix, then deriving diagonal, symmetric and asymmetric matrices.
Source files
lduMatrix.H
lduMatrixATmul.C
lduMatrix.C
lduMatrixTemplates.C
lduMatrixOperations.C
lduMatrixSolver.C
lduMatrixPreconditioner.C
lduMatrixTests.C
lduMatrixUpdateMatrixInterfaces.C
Definition at line 79 of file lduMatrix.H.
Constructor & Destructor Documentation
lduMatrix (const lduMesh & mesh)
Construct given an LDU addressed mesh.
The coefficients are initially empty for subsequent setting.
Definition at line 42 of file lduMatrix.C.
lduMatrix (const lduMatrix & A)
Construct as copy.
Definition at line 51 of file lduMatrix.C.
lduMatrix (lduMatrix & A, bool reuse)
Construct as copy or re-use as specified.
Definition at line 75 of file lduMatrix.C.
lduMatrix (const lduMesh & mesh, Istream & is)
Construct given an LDU addressed mesh and an Istream from which the coefficients are read.
Definition at line 122 of file lduMatrix.C.
~lduMatrix ()
Destructor.
Definition at line 148 of file lduMatrix.C.
Member Function Documentation
ClassName ("lduMatrix")
const lduMesh& mesh () const inline
Return the LDU mesh from which the addressing is obtained.
Definition at line 643 of file lduMatrix.H.
Referenced by faMatrix< Type >::residual().
const lduAddressing& lduAddr () const inline
Return the LDU addressing.
Definition at line 651 of file lduMatrix.H.
Referenced by lduMatrix::Amul(), lduMatrix::H(), and lduMatrix::sumDiag().
const lduSchedule& patchSchedule () const inline
Return the patch evaluation schedule.
Definition at line 659 of file lduMatrix.H.
Referenced by lduMatrix::initMatrixInterfaces().
Foam::scalarField & lower ()
Definition at line 167 of file lduMatrix.C.
Referenced by lduMatrix::Amul(), lduMatrix::H(), and lduMatrix::sumDiag().
Foam::scalarField & diag ()
Definition at line 185 of file lduMatrix.C.
Referenced by lduMatrix::Amul(), and lduMatrix::sumDiag().
Foam::scalarField & upper ()
Definition at line 196 of file lduMatrix.C.
Referenced by lduMatrix::Amul(), gaussLaplacianScheme< Type >::famLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), lduMatrix::H(), and lduMatrix::sumDiag().
Foam::scalarField & lower (const label size)
Definition at line 214 of file lduMatrix.C.
Foam::scalarField & diag (const label nCoeffs)
Definition at line 232 of file lduMatrix.C.
Foam::scalarField & upper (const label nCoeffs)
Definition at line 243 of file lduMatrix.C.
const Foam::scalarField & lower () const
Definition at line 261 of file lduMatrix.C.
const Foam::scalarField & diag () const
Definition at line 281 of file lduMatrix.C.
const Foam::scalarField & upper () const
Definition at line 294 of file lduMatrix.C.
bool hasDiag () const inline
Definition at line 683 of file lduMatrix.H.
bool hasUpper () const inline
Definition at line 688 of file lduMatrix.H.
bool hasLower () const inline
Definition at line 693 of file lduMatrix.H.
bool diagonal () const inline
Definition at line 698 of file lduMatrix.H.
bool symmetric () const inline
Definition at line 703 of file lduMatrix.H.
bool asymmetric () const inline
Definition at line 708 of file lduMatrix.H.
void sumDiag ()
Definition at line 30 of file lduMatrixOperations.C.
References lduMatrix::diag(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), UList< T >::size(), lduMatrix::upper(), and lduAddressing::upperAddr().
void negSumDiag ()
Definition at line 47 of file lduMatrixOperations.C.
Referenced by gaussLaplacianScheme< Type >::famLaplacian(), and gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected().
void sumMagOffDiag (scalarField & sumOff) const
Definition at line 65 of file lduMatrixOperations.C.
void Amul (solveScalarField & Apsi, const tmp< solveScalarField > & tpsi, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Matrix multiplication with updated interfaces.
Definition at line 32 of file lduMatrixATmul.C.
References UList< T >::begin(), lduMatrix::diag(), lduMatrix::initMatrixInterfaces(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), psi, UList< T >::size(), lduMatrix::updateMatrixInterfaces(), lduMatrix::upper(), and lduAddressing::upperAddr().
Referenced by GAMGSolver::solve().
void Tmul (solveScalarField & Tpsi, const tmp< solveScalarField > & tpsi, const FieldField< Field, scalar > & interfaceIntCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
Definition at line 95 of file lduMatrixATmul.C.
void sumA (solveScalarField & sumA, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces) const
Sum the coefficients on each row of the matrix.
Definition at line 156 of file lduMatrixATmul.C.
void residual (solveScalarField & rA, const solveScalarField & psi, const scalarField & source, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Definition at line 205 of file lduMatrixATmul.C.
Foam::tmp< Foam::Field< Foam::solveScalar > > residual (const solveScalarField & psi, const scalarField & source, const FieldField< Field, scalar > & interfaceBouCoeffs, const lduInterfaceFieldPtrsList & interfaces, const direction cmpt) const
Definition at line 277 of file lduMatrixATmul.C.
void initMatrixInterfaces (const bool add, const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces, const solveScalarField & psiif, solveScalarField & result, const direction cmpt) const
Initialise the update of interfaced interfaces for matrix operations.
Definition at line 27 of file lduMatrixUpdateMatrixInterfaces.C.
References UPstream::blocking, UPstream::defaultCommsType, FatalErrorInFunction, forAll, UPstream::nonBlocking, lduMatrix::patchSchedule(), UPstream::scheduled, UPtrList< T >::set(), UList< T >::size(), and UPtrList< T >::size().
Referenced by lduMatrix::Amul().
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > & interfaceCoeffs, const lduInterfaceFieldPtrsList & interfaces, const solveScalarField & psiif, solveScalarField & result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
Definition at line 96 of file lduMatrixUpdateMatrixInterfaces.C.
Referenced by lduMatrix::Amul().
void setResidualField (const scalarField & residual, const word & fieldName, const bool initial) const
Set the residual field using an IOField on the object registry if it exists.
Definition at line 315 of file lduMatrix.C.
Referenced by GAMGSolver::solve().
tmp<Field<Type> > H (const Field< Type > &) const
tmp<Field<Type> > H (const tmp< Field< Type >> &) const
Foam::tmp< Foam::scalarField > H1 () const
Definition at line 291 of file lduMatrixATmul.C.
tmp<Field<Type> > faceH (const Field< Type > &) const
tmp<Field<Type> > faceH (const tmp< Field< Type >> &) const
InfoProxy<lduMatrix> info () const inline
Return info proxy.
Used to print matrix information to a stream
Definition at line 837 of file lduMatrix.H.
void operator= (const lduMatrix & A)
Definition at line 85 of file lduMatrixOperations.C.
void negate ()
Definition at line 119 of file lduMatrixOperations.C.
References Foam::diag().
void operator+= (const lduMatrix & A)
Definition at line 138 of file lduMatrixOperations.C.
void operator-= (const lduMatrix & A)
Definition at line 217 of file lduMatrixOperations.C.
void operator*= (const scalarField & sf)
Definition at line 296 of file lduMatrixOperations.C.
void operator*= (scalar s)
Definition at line 326 of file lduMatrixOperations.C.
Foam::tmp<Foam::Field<Type> > H (const Field< Type > & psi) const
Definition at line 30 of file lduMatrixTemplates.C.
References UList< Type >::begin(), UList< T >::begin(), lduMatrix::lduAddr(), lduMatrix::lower(), lduAddressing::lowerAddr(), tmp< T >::ref(), UList< T >::size(), lduMatrix::upper(), lduAddressing::upperAddr(), and Foam::Zero.
Foam::tmp<Foam::Field<Type> > H (const tmp< Field< Type >> & tpsi) const
Definition at line 65 of file lduMatrixTemplates.C.
Foam::tmp<Foam::Field<Type> > faceH (const Field< Type > & psi) const
Definition at line 75 of file lduMatrixTemplates.C.
Foam::tmp<Foam::Field<Type> > faceH (const tmp< Field< Type >> & tpsi) const
Definition at line 109 of file lduMatrixTemplates.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const lduMatrix &) friend
Ostream& operator<< (Ostream & , const InfoProxy< lduMatrix > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrix.H
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrix.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixATmul.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixOperations.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixTemplates.C
src/OpenFOAM/matrices/lduMatrix/lduMatrix/lduMatrixUpdateMatrixInterfaces.C