OpenFOAM: cellShapeControlMesh Class Reference
cellShapeControlMesh Class Reference
Public Types
typedef
CellSizeDelaunay::Cell_handle Cell_handle
typedef
CellSizeDelaunay::Vertex_handle Vertex_handle
typedef CellSizeDelaunay::Point Point
Public Types inherited from DistributedDelaunayMesh< CellSizeDelaunay >
typedef
CellSizeDelaunay::Vertex_handle Vertex_handle
typedef
CellSizeDelaunay::Cell_handle Cell_handle
typedef CellSizeDelaunay::Point Point
typedef
CellSizeDelaunay::Finite_vertices_iterator Finite_vertices_iterator
typedef
CellSizeDelaunay::Finite_cells_iterator Finite_cells_iterator
typedef
CellSizeDelaunay::All_cells_iterator All_cells_iterator
Public Types inherited from DelaunayMesh< CellSizeDelaunay >
typedef
CellSizeDelaunay::Cell_handle Cell_handle
typedef
CellSizeDelaunay::Vertex_handle Vertex_handle
typedef CellSizeDelaunay::Edge Edge
typedef CellSizeDelaunay::Point Point
typedef CellSizeDelaunay::Facet Facet
typedef
CellSizeDelaunay::Finite_vertices_iterator Finite_vertices_iterator
typedef
CellSizeDelaunay::Finite_cells_iterator Finite_cells_iterator
typedef
CellSizeDelaunay::Finite_facets_iterator Finite_facets_iterator
Public Member Functions
ClassName ("cellShapeControlMesh")
Runtime type information.
cellShapeControlMesh (const Time &runTime)
~cellShapeControlMesh ()
Destructor.
const Time & time () const
void barycentricCoords (const Foam::point &pt, barycentric &bary, Cell_handle &ch) const
Calculate and return the barycentric coordinates for.
boundBox bounds () const
label removePoints ()
tmp< pointField > cellCentres () const
Get the centres of all the tets.
Vertex_handle insert (const Foam::point &pt, const scalar &size, const triad &alignment, const Foam::indexedVertexEnum::vertexType type=Vb::vtInternal)
Vertex_handle insertFar (const Foam::point &pt)
void distribute (const backgroundMeshDecomposition &decomposition)
tensorField dumpAlignments () const
void writeTriangulation ()
void write () const
label estimateCellCount (const autoPtr< backgroundMeshDecomposition > &decomposition) const
Public Member Functions inherited from DistributedDelaunayMesh< CellSizeDelaunay >
DistributedDelaunayMesh (const Time &runTime)
Construct from components.
DistributedDelaunayMesh (const Time &runTime, const word &meshName)
~DistributedDelaunayMesh ()=default
Destructor.
scalar calculateLoadUnbalance () const
bool distribute (const boundBox &bb)
autoPtr< mapDistribute > distribute (const backgroundMeshDecomposition &decomposition, List< Foam::point > &points)
void sync (const boundBox &bb)
Refer vertices so that the processor interfaces are consistent.
void sync (const boundBox &bb, PtrList< labelPairHashSet > &referralVertices, labelPairHashSet &receivedVertices, bool iterateReferral=true)
Refer vertices so that the processor interfaces are consistent.
labelPairHashSet rangeInsertReferredWithInfo (PointIterator begin, PointIterator end, bool printErrors=true)
Inserts points into the triangulation if the point is within.
Public Member Functions inherited from DelaunayMesh< CellSizeDelaunay >
DelaunayMesh (const Time &runTime)
Construct from components.
DelaunayMesh (const Time &runTime, const word &meshName)
~DelaunayMesh ()
Destructor.
const Time & time () const
Return a reference to the Time object.
void timeCheck (const string &description, const bool check=true) const
Write the cpuTime to screen.
label getNewCellIndex () const
Create a new unique cell index and return.
label getNewVertexIndex () const
Create a new unique vertex index and return.
label cellCount () const
Return the cell count (the next unique cell index)
label vertexCount () const
Return the vertex count (the next unique vertex index)
void resetCellCount ()
Set the cell count to zero.
void resetVertexCount ()
Set the vertex count to zero.
void reset ()
Clear the entire triangulation.
Map< label > insertPoints (const List< Vb > &vertices, const bool reIndex)
Insert the list of vertices (calls rangeInsertWithInfo)
Map< label > rangeInsertWithInfo (PointIterator begin, PointIterator end, bool printErrors=false, bool reIndex=true)
Function inserting points into a triangulation and setting the.
void printInfo (Ostream &os) const
Write mesh statistics to stream.
void printVertexInfo (Ostream &os) const
Write vertex statistics in the form of a table to stream.
autoPtr< polyMesh > createMesh (const fileName &name, labelPairLookup &vertexMap, labelList &cellMap, const bool writeDelaunayData=true) const
Create an fvMesh from the triangulation.
Static Public Attributes
static word meshSubDir
Return the mesh sub-directory name (usually "cellShapeControlMesh")
Additional Inherited Members
Static Public Member Functions inherited from DistributedDelaunayMesh< CellSizeDelaunay >
static autoPtr< mapDistribute > buildMap (const List< label > &toProc)
Build a mapDistribute for the supplied destination processor data.
Detailed Description
Source files
cellShapeControlMesh.H
cellShapeControlMeshI.H
cellShapeControlMesh.C
Definition at line 59 of file cellShapeControlMesh.H.
Member Typedef Documentation
typedef CellSizeDelaunay::Cell_handle Cell_handle
Definition at line 65 of file cellShapeControlMesh.H.
typedef CellSizeDelaunay::Vertex_handle Vertex_handle
Definition at line 66 of file cellShapeControlMesh.H.
typedef CellSizeDelaunay::Point Point
Definition at line 67 of file cellShapeControlMesh.H.
Constructor & Destructor Documentation
cellShapeControlMesh (const Time & runTime) explicit
~cellShapeControlMesh ()
Destructor.
Member Function Documentation
ClassName ("cellShapeControlMesh")
Runtime type information.
const Time& time () const inline
Definition at line 122 of file cellShapeControlMesh.H.
void barycentricCoords (const Foam::point & pt, barycentric & bary, Cell_handle & ch) const
Calculate and return the barycentric coordinates for.
interpolating quantities on the background mesh
boundBox bounds () const
label removePoints ()
tmp<pointField> cellCentres () const
Get the centres of all the tets.
Foam::cellShapeControlMesh::Vertex_handle insert (const Foam::point & pt, const scalar & size, const triad & alignment, const Foam::indexedVertexEnum::vertexType type = Vb::vtInternal) inline
Definition at line 24 of file cellShapeControlMeshI.H.
References DelaunayMesh< CellSizeDelaunay >::getNewVertexIndex(), insert(), UPstream::myProcNo(), Foam::type(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Foam::cellShapeControlMesh::Vertex_handle insertFar (const Foam::point & pt) inline
Definition at line 46 of file cellShapeControlMeshI.H.
void distribute (const backgroundMeshDecomposition & decomposition)
tensorField dumpAlignments () const
void writeTriangulation ()
void write () const
label estimateCellCount (const autoPtr< backgroundMeshDecomposition > & decomposition) const
Member Data Documentation
word meshSubDir static
Return the mesh sub-directory name (usually "cellShapeControlMesh")
Definition at line 104 of file cellShapeControlMesh.H.
The documentation for this class was generated from the following files:
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cellShapeControl/cellShapeControlMesh/cellShapeControlMesh.H
applications/utilities/mesh/generation/foamyMesh/conformalVoronoiMesh/cellShapeControl/cellShapeControlMesh/cellShapeControlMeshI.H