OpenFOAM: Function1< Type > Class Template Reference
Function1< Type > Class Template Reference abstract
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
Public Types
typedef Type returnType
Public Member Functions
declareRunTimeSelectionTable (autoPtr, Function1, dictionary,(const word &entryName, const dictionary &dict),(entryName, dict))
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &f1)
Copy constructor.
virtual tmp< Function1< Type > > clone () const =0
Construct and return a clone.
virtual ~Function1 ()=default
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType=word::null)
Selector.
Protected Attributes
const word name_
Name of entry.
Friends
Ostream & operator (Ostream &os, const Function1< Type > &func)
Ostream Operator.
Detailed Description
template<class Type>
class Foam::Function1< Type >
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or table, and provide functions to return the (interpolated) value, and integral between limits.
Source files
Function1.H
Function1.C
Function1New.C
Definition at line 52 of file Function1.H.
Member Typedef Documentation
typedef Type returnType
Definition at line 84 of file Function1.H.
Constructor & Destructor Documentation
Function1 (const word & entryName) explicit
Construct from entry name.
Definition at line 29 of file Function1.C.
Function1 (const Function1< Type > & f1) explicit
Copy constructor.
Definition at line 36 of file Function1.C.
virtual ~Function1 () virtual default
Destructor.
Member Function Documentation
declareRunTimeSelectionTable (autoPtr , Function1< Type > , dictionary , (const word &entryName, const dictionary &dict) , (entryName, dict))
Runtime type information.
Declare runtime constructor selection table
virtual tmp<Function1<Type> > clone () const pure virtual
Construct and return a clone.
Implemented in CSV< Type >, Constant< Type >, Table< Type >, and OneConstant< Type >.
Foam::autoPtr< Foam::Function1< Type > > New (const word & entryName, const dictionary & dict, const word & redirectType = word::null) static
Selector.
Definition at line 28 of file Function1New.C.
References entry::dict(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findEntry(), entry::isDict(), token::isWord(), Foam::nl, dictionary::optionalSubDict(), Istream::putBack(), dictionary::readEntry(), entry::stream(), and token::wordToken().
Referenced by MappedFile< Type >::MappedFile().
const Foam::word & name () const
Return the name of the entry.
Definition at line 46 of file Function1.C.
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented in TableBase< Type >, and Polynomial< Type >.
Definition at line 53 of file Function1.C.
Type value (const scalar x) const virtual
Return value as a function of (scalar) independent variable.
Reimplemented in Square< Type >, Sine< Type >, ramp, Scale< Type >, TableBase< Type >, Polynomial< Type >, Constant< Type >, OneConstant< Type >, halfCosineRamp, linearRamp, quadraticRamp, quarterCosineRamp, quarterSineRamp, and ZeroConstant< Type >.
Definition at line 58 of file Function1.C.
Foam::tmp< Foam::Field< Type > > value (const scalarField & x) const virtual
Return value as a function of (scalar) independent variable.
Reimplemented in Constant< Type >, and OneConstant< Type >.
Definition at line 67 of file Function1.C.
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented in TableBase< Type >, Polynomial< Type >, Constant< Type >, OneConstant< Type >, and ZeroConstant< Type >.
Definition at line 77 of file Function1.C.
References NotImplemented.
Foam::tmp< Foam::Field< Type > > integrate (const scalarField & x1, const scalarField & x2) const virtual
Integrate between two (scalar) values.
Reimplemented in Constant< Type >, Constant< Type >, OneConstant< Type >, and Constant< Type >.
Definition at line 87 of file Function1.C.
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented in Square< Type >, Sine< Type >, TableBase< Type >, CSV< Type >, ramp, Scale< Type >, Constant< Type >, Polynomial< Type >, OneConstant< Type >, TableFile< Type >, and ZeroConstant< Type >.
Definition at line 158 of file Function1.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const Function1< Type > & func) friend
Ostream Operator.
Member Data Documentation
const word name_ protected
Name of entry.
Definition at line 79 of file Function1.H.
Referenced by Polynomial< Type >::Polynomial().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.H
src/OpenFOAM/primitives/functions/Function1/Function1/Function1.C
src/OpenFOAM/primitives/functions/Function1/Function1/Function1New.C