OpenFOAM: pyrolysisChemistryModel< CompType, SolidThermo, GasThermo > Class Template Reference
pyrolysisChemistryModel< CompType, SolidThermo, GasThermo > Class Template Reference
Pyrolysis chemistry model. It includes gas phase in the solid reaction.
Public Member Functions
TypeName ("pyrolysis")
Runtime type information.
pyrolysisChemistryModel (typename CompType::reactionThermo &thermo)
Construct from thermo.
virtual ~pyrolysisChemistryModel ()
Destructor.
const PtrList< GasThermo > & gasThermo () const
Thermodynamic data of gases.
const speciesTable & gasTable () const
Gases table.
label nSpecie () const
The number of solids.
label nGases () const
The number of solids.
virtual scalarField omega (const scalarField &c, const scalar T, const scalar p, const bool updateC0=false) const
dc/dt = omega, rate of change in concentration, for each species
virtual scalar omega (const Reaction< SolidThermo > &r, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for reaction r.
virtual scalar omegaI (label iReaction, const scalarField &c, const scalar T, const scalar p, scalar &pf, scalar &cf, label &lRef, scalar &pr, scalar &cr, label &rRef) const
Return the reaction rate for iReaction.
virtual void calculate ()
Calculates the reaction rates.
const volScalarField::Internal & RRg (const label i) const
Return const access to the chemical source terms for gases.
tmp< volScalarField::Internal > RRg () const
Return total gas source term.
virtual tmp< volScalarField > gasHs (const volScalarField &p, const volScalarField &T, const label i) const
Return sensible enthalpy for gas i [J/Kg].
virtual scalar solve (const scalar deltaT)
Solve the reaction system for the given time step.
virtual label nEqns () const
Number of ODE's to solve.
virtual void derivatives (const scalar t, const scalarField &c, scalarField &dcdt) const
Calculate the derivatives in dydx.
virtual void jacobian (const scalar t, const scalarField &c, scalarField &dcdt, scalarSquareMatrix &dfdc) const
Calculate the Jacobian of the system.
virtual void solve (scalarField &c, scalar &T, scalar &p, scalar &deltaT, scalar &subDeltaT) const
Public Member Functions inherited from solidChemistryModel< CompType, SolidThermo >
TypeName ("solidChemistryModel")
Runtime type information.
solidChemistryModel (typename CompType::reactionThermo &thermo)
Construct from thermo.
virtual ~solidChemistryModel ()
Destructor.
const PtrList< Reaction
< SolidThermo > > & reactions () const
The reactions.
label nReaction () const
The number of reactions.
const volScalarField::Internal & RRs (const label i) const
Return const access to the chemical source terms for solids.
tmp< volScalarField::Internal > RRs () const
Return total solid source term.
tmp< DimensionedField< scalar,
volMesh > > RRsHs () const
Return net solid sensible enthalpy.
virtual scalar solve (const scalarField &deltaT)
Solve the reaction system for the given time step.
virtual tmp< volScalarField > tc () const
Return the chemical time scale.
virtual tmp< volScalarField > Qdot () const
Return the heat release rate [kg/m/s3].
Public Member Functions inherited from ODESystem
ODESystem ()
Construct null.
virtual ~ODESystem ()=default
Destructor.
Protected Member Functions
PtrList
< volScalarField::Internal > & RRg ()
Write access to source terms for gases.
Protected Member Functions inherited from solidChemistryModel< CompType, SolidThermo >
PtrList
< volScalarField::Internal > & RRs ()
Write access to source terms for solids.
void setCellReacting (const label celli, const bool active)
Set reacting status of cell, celli.
Protected Attributes
speciesTable pyrolisisGases_
List of gas species present in reaction system.
PtrList< GasThermo > gasThermo_
Thermodynamic data of gases.
label nGases_
Number of gas species.
label nSpecie_
Number of components being solved by ODE.
PtrList< volScalarField::Internal > RRg_
List of reaction rate per gas [kg/m3/s].
Protected Attributes inherited from solidChemistryModel< CompType, SolidThermo >
PtrList< volScalarField > & Ys_
Reference to solid mass fractions.
const PtrList< Reaction
< SolidThermo > > & reactions_
Reactions.
const PtrList< SolidThermo > & solidThermo_
Thermodynamic data of solids.
label nSolids_
Number of solid components.
label nReaction_
Number of solid reactions.
PtrList< volScalarField::Internal > RRs_
List of reaction rate per solid [kg/m3/s].
List< bool > reactingCells_
List of active reacting cells.
Detailed Description
template<class CompType, class SolidThermo, class GasThermo>
class Foam::pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >
Pyrolysis chemistry model. It includes gas phase in the solid reaction.
Source files
pyrolysisChemistryModel.H
pyrolysisChemistryModelI.H
pyrolysisChemistryModel.C
Definition at line 54 of file pyrolysisChemistryModel.H.
Constructor & Destructor Documentation
pyrolysisChemistryModel (typename CompType::reactionThermo & thermo)
Construct from thermo.
Definition at line 31 of file pyrolysisChemistryModel.C.
References IOobject::AUTO_WRITE, dictionary::dictName(), Foam::dimMass, Foam::dimTime, Foam::dimVolume, forAll, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::gasThermo_, i, Foam::indent(), Foam::Info, Foam::max(), mesh, IOobject::MUST_READ, Foam::name(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::nGases_, Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, solidChemistryModel< CompType, SolidThermo >::nSolids_, pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolisisGases_, solidChemistryModel< CompType, SolidThermo >::reactions_, solidThermo::rho(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::RRg_, solidChemistryModel< CompType, SolidThermo >::RRs_, PtrList< T >::set(), thermoDict, timeName, IOobject::typeHeaderOk(), solidChemistryModel< CompType, SolidThermo >::Ys_, and Foam::Zero.
~pyrolysisChemistryModel () virtual
Destructor.
Definition at line 167 of file pyrolysisChemistryModel.C.
Member Function Documentation
Foam::PtrList< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > & RRg () inline protected
Write access to source terms for gases.
Definition at line 28 of file pyrolysisChemistryModelI.H.
TypeName ("pyrolysis")
Runtime type information.
const Foam::PtrList< GasThermo > & gasThermo () const inline
Thermodynamic data of gases.
Definition at line 37 of file pyrolysisChemistryModelI.H.
const Foam::speciesTable & gasTable () const inline
Gases table.
Definition at line 46 of file pyrolysisChemistryModelI.H.
Foam::label nSpecie () const inline
The number of solids.
Definition at line 55 of file pyrolysisChemistryModelI.H.
label nGases () const inline
The number of solids.
Foam::scalarField omega (const scalarField & c, const scalar T, const scalar p, const bool updateC0 = false) const virtual
dc/dt = omega, rate of change in concentration, for each species
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 176 of file pyrolysisChemistryModel.C.
References forAll, g, Reaction< ReactionThermo >::grhs(), i, Reaction< ReactionThermo >::lhs(), om, R, Reaction< ReactionThermo >::rhs(), s, and Foam::Zero.
Foam::scalar omega (const Reaction< SolidThermo > & r, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Return the reaction rate for reaction r.
NOTE: Currently does not calculate reference specie and characteristic times (pf, cf,l Ref, etc.)
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 232 of file pyrolysisChemistryModel.C.
Foam::scalar omegaI (label iReaction, const scalarField & c, const scalar T, const scalar p, scalar & pf, scalar & cf, label & lRef, scalar & pr, scalar & cr, label & rRef) const virtual
Return the reaction rate for iReaction.
NOTE: Currently does not calculate reference specie and characteristic times (pf, cf,l Ref, etc.)
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 275 of file pyrolysisChemistryModel.C.
void calculate () virtual
Calculates the reaction rates.
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 445 of file pyrolysisChemistryModel.C.
const Foam::DimensionedField< Foam::scalar, Foam::volMesh > & RRg (const label i) const inline
Return const access to the chemical source terms for gases.
Definition at line 64 of file pyrolysisChemistryModelI.H.
Foam::tmp< Foam::DimensionedField< Foam::scalar, Foam::volMesh > > RRg () const inline
Return total gas source term.
Definition at line 75 of file pyrolysisChemistryModelI.H.
Foam::tmp< Foam::volScalarField > gasHs (const volScalarField & p, const volScalarField & T, const label i) const virtual
Return sensible enthalpy for gas i [J/Kg].
Definition at line 611 of file pyrolysisChemistryModel.C.
Foam::scalar solve (const scalar deltaT) virtual
Solve the reaction system for the given time step.
and return the characteristic time
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 513 of file pyrolysisChemistryModel.C.
Foam::label nEqns () const virtual
Number of ODE's to solve.
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 436 of file pyrolysisChemistryModel.C.
void derivatives (const scalar x, const scalarField & y, scalarField & dydx) const virtual
Calculate the derivatives in dydx.
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 298 of file pyrolysisChemistryModel.C.
void jacobian (const scalar x, const scalarField & y, scalarField & dfdx, scalarSquareMatrix & dfdy) const virtual
Calculate the Jacobian of the system.
Need by the stiff-system solvers
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 340 of file pyrolysisChemistryModel.C.
void solve (scalarField & c, scalar & T, scalar & p, scalar & deltaT, scalar & subDeltaT) const virtual
Implements solidChemistryModel< CompType, SolidThermo >.
Definition at line 650 of file pyrolysisChemistryModel.C.
Member Data Documentation
speciesTable pyrolisisGases_ protected
List of gas species present in reaction system.
Definition at line 71 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
PtrList<GasThermo> gasThermo_ protected
Thermodynamic data of gases.
Definition at line 76 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
label nGases_ protected
Number of gas species.
Definition at line 81 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
label nSpecie_ protected
Number of components being solved by ODE.
Definition at line 86 of file pyrolysisChemistryModel.H.
PtrList<volScalarField::Internal> RRg_ protected
List of reaction rate per gas [kg/m3/s].
Definition at line 91 of file pyrolysisChemistryModel.H.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
The documentation for this class was generated from the following files:
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModel.H
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModel.C
src/thermophysicalModels/solidChemistryModel/pyrolysisChemistryModel/pyrolysisChemistryModelI.H