OpenFOAM: opaqueDiffusive Class Reference
opaqueDiffusive Class Reference
Radiation boundary model for opaque diffusive walls. It requires to specify a wallAbsorptionEmissionModel in boundaryRadiationProperties file.
Public Member Functions
TypeName ("opaqueDiffusive")
Runtime type information.
opaqueDiffusive (const dictionary &dict, const polyPatch &pp)
Construct from components.
virtual ~opaqueDiffusive ()=default
Destructor.
virtual tmp< scalarField > e (const label bandI, vectorField *incomingDirection, scalarField *T) const
Return emissivity.
virtual scalar e (const label faceI, const label bandI, const vector &dir, const scalar T) const
Return emissivity on face.
virtual tmp< scalarField > a (const label bandI, vectorField *incomingDirection, scalarField *T) const
Return absorptivity on patch.
virtual scalar a (const label faceI, const label bandI, const vector &dir, const scalar T) const
Return absorptivity on face.
virtual tmp< scalarField > t (const label bandI, vectorField *incomingDirection, scalarField *T) const
Return transmissivity on patch.
virtual scalar t (const label faceI, const label bandI, const vector &dir, const scalar T) const
Return transmissivity on face.
virtual tmp< scalarField > rSpec (const label bandI, vectorField *incomingDirection, scalarField *T) const
Return specular reflectivity on patch.
virtual scalar rSpec (const label faceI, const label bandI, const vector &dir, const scalar T) const
Return specular reflectivity on face.
virtual tmp< scalarField > rDiff (const label bandI, vectorField *incomingDirection, scalarField *T) const
Return diffusive reflectivity on patch.
virtual scalar rDiff (const label faceI, const label bandI, const vector &dir, const scalar T) const
Return diffusive reflectivity on face.
virtual bool isGrey () const
Is Grey.
virtual label nBands () const
Number of bands.
Public Member Functions inherited from boundaryRadiationPropertiesPatch
TypeName ("boundaryRadiationPropertiesPatch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, boundaryRadiationPropertiesPatch, dictionary,(const dictionary &dict, const polyPatch &pp),(dict, pp))
boundaryRadiationPropertiesPatch (const dictionary &, const polyPatch &)
Construct from patch, internal field and dictionary.
virtual ~boundaryRadiationPropertiesPatch ()=default
Destructor.
const wallAbsorptionEmissionModel & absorptionEmission () const
Return absorptionEmissionModel.
const wallTransmissivityModel & transmissiveModel () const
Return transmissivityModel.
virtual void write (Ostream &) const
Write.
Protected Attributes
const polyPatch & pp_
Reference to the polyPatch.
Protected Attributes inherited from boundaryRadiationPropertiesPatch
autoPtr
< wallAbsorptionEmissionModel > absorptionEmission_
Absorption/emission model.
autoPtr< wallTransmissivityModel > transmissivity_
Transmissivity model.
Additional Inherited Members
Static Public Member Functions inherited from boundaryRadiationPropertiesPatch
static autoPtr
< boundaryRadiationPropertiesPatch > New (const dictionary &dict, const polyPatch &pp)
Selector.
Detailed Description
Radiation boundary model for opaque diffusive walls. It requires to specify a wallAbsorptionEmissionModel in boundaryRadiationProperties file.
Usage
    type       opaqueDiffusive;
    wallAbsorptionEmissionModel
    {
        type            multiBandAbsorption;
        absorptivity    (0.3 0.7);
        emissivity      (0.3 0.7);
    };
Definition at line 58 of file opaqueDiffusive.H.
Constructor & Destructor Documentation
opaqueDiffusive (const dictionary & dict, const polyPatch & pp)
Construct from components.
Definition at line 44 of file opaqueDiffusive.C.
virtual ~opaqueDiffusive () virtual default
Destructor.
Member Function Documentation
TypeName ("opaqueDiffusive")
Runtime type information.
Foam::tmp< Foam::scalarField > e (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Return emissivity.
Implements boundaryRadiationPropertiesPatch.
Definition at line 65 of file opaqueDiffusive.C.
Foam::scalar e (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Return emissivity on face.
Implements boundaryRadiationPropertiesPatch.
Definition at line 76 of file opaqueDiffusive.C.
References Foam::T().
Foam::tmp< Foam::scalarField > a (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Return absorptivity on patch.
Implements boundaryRadiationPropertiesPatch.
Definition at line 89 of file opaqueDiffusive.C.
Foam::scalar a (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Return absorptivity on face.
Implements boundaryRadiationPropertiesPatch.
Definition at line 100 of file opaqueDiffusive.C.
References Foam::T().
Foam::tmp< Foam::scalarField > t (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Return transmissivity on patch.
Implements boundaryRadiationPropertiesPatch.
Definition at line 112 of file opaqueDiffusive.C.
References Foam::T().
Foam::scalar t (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Return transmissivity on face.
Implements boundaryRadiationPropertiesPatch.
Definition at line 123 of file opaqueDiffusive.C.
References tmp< T >::New().
Foam::tmp< Foam::scalarField > rSpec (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Return specular reflectivity on patch.
Implements boundaryRadiationPropertiesPatch.
Definition at line 136 of file opaqueDiffusive.C.
Foam::scalar rSpec (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Return specular reflectivity on face.
Implements boundaryRadiationPropertiesPatch.
Definition at line 147 of file opaqueDiffusive.C.
References tmp< T >::New(), and Foam::Zero.
Foam::tmp< Foam::scalarField > rDiff (const label bandI, vectorField * incomingDirection, scalarField * T) const virtual
Return diffusive reflectivity on patch.
Implements boundaryRadiationPropertiesPatch.
Definition at line 159 of file opaqueDiffusive.C.
References Foam::Zero.
Foam::scalar rDiff (const label faceI, const label bandI, const vector & dir, const scalar T) const virtual
Return diffusive reflectivity on face.
Implements boundaryRadiationPropertiesPatch.
Definition at line 170 of file opaqueDiffusive.C.
References tmp< T >::New(), and Foam::Zero.
bool isGrey () const virtual
Is Grey.
Implements boundaryRadiationPropertiesPatch.
Definition at line 181 of file opaqueDiffusive.C.
References Foam::Zero.
Foam::label nBands () const virtual
Number of bands.
Implements boundaryRadiationPropertiesPatch.
Definition at line 187 of file opaqueDiffusive.C.
Member Data Documentation
const polyPatch& pp_ protected
Reference to the polyPatch.
Definition at line 70 of file opaqueDiffusive.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/boundaryRadiationProperties/opaqueDiffusive/opaqueDiffusive.H
src/thermophysicalModels/radiation/submodels/boundaryRadiationProperties/opaqueDiffusive/opaqueDiffusive.C