OpenFOAM: motionSmootherAlgo Class Reference
motionSmootherAlgo Class Reference
Given a displacement moves the mesh by scaling the displacement back until there are no more mesh errors.
Public Member Functions
ClassName ("motionSmootherAlgo")
motionSmootherAlgo (polyMesh &, pointMesh &, indirectPrimitivePatch &pp, pointVectorField &displacement, pointScalarField &scale, pointField &oldPoints, const labelList &adaptPatchIDs, const dictionary &paramDict, const bool dryRun=false)
Construct from mesh, patches to work on and smoothing parameters.
~motionSmootherAlgo ()
Destructor.
const polyMesh & mesh () const
Reference to mesh.
const pointMesh & pMesh () const
Reference to pointMesh.
const indirectPrimitivePatch & patch () const
Reference to patch.
const labelList & adaptPatchIDs () const
Patch labels that are being adapted.
const dictionary & paramDict () const
pointVectorField & pointDisplacement ()
Return reference to the point motion displacement field.
const pointVectorField & pointDisplacement () const
Return const reference to the point motion displacement field.
void correct ()
Take over existing mesh position.
void setDisplacementPatchFields ()
Set patch fields on displacement to be consistent with.
void setDisplacement (pointField &patchDisp)
void correctBoundaryConditions (pointVectorField &) const
Special correctBoundaryConditions which evaluates fixedValue.
void modifyMotionPoints (pointField &newPoints) const
Apply optional point constraint (2d correction)
tmp< pointField > curPoints () const
Get the current points (oldPoints+scale*displacement)
scalar setErrorReduction (const scalar)
Set the errorReduction (by how much to scale the displacement.
bool scaleMesh (labelList &checkFaces, const bool smoothMesh=true, const label nAllow=0)
Move mesh with given scale. Return true if mesh ok or has.
bool scaleMesh (labelList &checkFaces, const List< labelPair > &baffles, const bool smoothMesh=true, const label nAllow=0)
Move mesh (with baffles) with given scale.
bool scaleMesh (labelList &checkFaces, const List< labelPair > &baffles, const dictionary &paramDict, const dictionary &meshQualityDict, const bool smoothMesh=true, const label nAllow=0)
Move mesh with externally provided mesh constraints.
void movePoints ()
Update for new mesh geometry.
void updateMesh ()
Update for new mesh topology.
template<class Type >
void smooth (const GeometricField< Type, pointPatchField, pointMesh > &fld, const scalarField &edgeWeight, GeometricField< Type, pointPatchField, pointMesh > &newFld) const
Fully explicit smoothing of fields (not positions)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::pointPatchField,
Foam::pointMesh > > avg (const GeometricField< Type, pointPatchField, pointMesh > &fld, const scalarField &edgeWeight) const
Static Public Member Functions
static void setDisplacementPatchFields (const labelList &patchIDs, pointVectorField &pointDisplacement)
Set patch fields on patchIDs to be consistent with.
static void setDisplacement (const labelList &patchIDs, const indirectPrimitivePatch &pp, pointField &patchDisp, pointVectorField &displacement)
Set displacement field from displacement on patch points.
static bool checkMesh (const bool report, const polyMesh &mesh, const dictionary &dict, labelHashSet &wrongFaces, const bool dryRun=false)
Check mesh with mesh settings in dict. Collects incorrect faces.
static bool checkMesh (const bool report, const polyMesh &mesh, const dictionary &dict, const labelList &checkFaces, labelHashSet &wrongFaces, const bool dryRun=false)
Check (subset of mesh) with mesh settings in dict.
static bool checkMesh (const bool report, const polyMesh &mesh, const dictionary &dict, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet &wrongFaces, const bool dryRun=false)
Check (subset of mesh including baffles) with mesh settings.
static bool checkMesh (const bool report, const dictionary &dict, const polyMeshGeometry &, const pointField &, const labelList &checkFaces, labelHashSet &wrongFaces, const bool dryRun=false)
Check part of mesh with mesh settings in dict.
static bool checkMesh (const bool report, const dictionary &dict, const polyMeshGeometry &, const pointField &, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet &wrongFaces, const bool dryRun=false)
Check part of mesh including baffles with mesh settings in dict.
template<class Type >
static Type get (const dictionary &dict, const word &keyword, const bool noExit, enum keyType::option matchOpt, const Type &defaultValue=Zero)
Wrapper around dictionary::get which does not exit.
Detailed Description
Given a displacement moves the mesh by scaling the displacement back until there are no more mesh errors.
Holds displacement field (read upon construction since need boundary conditions) and scaling factor and optional patch number on which to scale back displacement.
E.g.
    // Construct iterative mesh mover.
    motionSmoother meshMover(mesh, labelList(1, patchi));
    // Set desired displacement:
    meshMover.displacement() = ..
    for (label iter = 0; iter < maxIter; iter++)
    {
        if (meshMover.scaleMesh(true))
        {
            Info<< "Successfully moved mesh" << endl;
            return true;
        }
    }
Note
Shared points (parallel): a processor can have points which are part of pp on another processor but have no pp itself (i.e. it has points and/or edges but no faces of pp). Hence we have to be careful when e.g. synchronising displacements that the value from the processor which has faces of pp get priority. This is currently handled in setDisplacement by resetting the internal displacement to zero on coupled points that are coupled to patch points before doing anything else. The combine operator used will give preference to non-zero values.
Various routines take baffles. These are sets of boundary faces that are treated as a single internal face. This is a hack used to apply movement to internal faces.
Mesh constraints are looked up from the supplied dictionary. (uses recursive lookup)
Source files
motionSmootherAlgo.H
motionSmootherAlgo.C
motionSmootherAlgoTemplates.C
Definition at line 96 of file motionSmootherAlgo.H.
Constructor & Destructor Documentation
motionSmootherAlgo (polyMesh & mesh, pointMesh & pMesh, indirectPrimitivePatch & pp, pointVectorField & displacement, pointScalarField & scale, pointField & oldPoints, const labelList & adaptPatchIDs, const dictionary & paramDict, const bool dryRun = false)
Construct from mesh, patches to work on and smoothing parameters.
Definition at line 319 of file motionSmootherAlgo.C.
~motionSmootherAlgo ()
Destructor.
Definition at line 348 of file motionSmootherAlgo.C.
Member Function Documentation
ClassName ("motionSmootherAlgo")
const Foam::polyMesh & mesh () const
Reference to mesh.
Definition at line 354 of file motionSmootherAlgo.C.
const Foam::pointMesh & pMesh () const
Reference to pointMesh.
Definition at line 360 of file motionSmootherAlgo.C.
const Foam::indirectPrimitivePatch & patch () const
Reference to patch.
Definition at line 366 of file motionSmootherAlgo.C.
const Foam::labelList & adaptPatchIDs () const
Patch labels that are being adapted.
Definition at line 372 of file motionSmootherAlgo.C.
const Foam::dictionary & paramDict () const
Definition at line 378 of file motionSmootherAlgo.C.
pointVectorField& pointDisplacement () inline
Return reference to the point motion displacement field.
Definition at line 411 of file motionSmootherAlgo.H.
const pointVectorField& pointDisplacement () const inline
Return const reference to the point motion displacement field.
Definition at line 419 of file motionSmootherAlgo.H.
void correct ()
Take over existing mesh position.
Definition at line 384 of file motionSmootherAlgo.C.
void setDisplacementPatchFields (const labelList & patchIDs, pointVectorField & pointDisplacement) static
Set patch fields on patchIDs to be consistent with.
all other boundary conditions
Definition at line 397 of file motionSmootherAlgo.C.
void setDisplacementPatchFields ()
Set patch fields on displacement to be consistent with.
internal values.
Definition at line 454 of file motionSmootherAlgo.C.
void setDisplacement (const labelList & patchIDs, const indirectPrimitivePatch & pp, pointField & patchDisp, pointVectorField & displacement) static
Set displacement field from displacement on patch points.
Modify provided displacement to be consistent with actual boundary conditions on displacement. Note: resets the displacement to be 0 on coupled patches beforehand to make sure shared points partially on pp (on some processors) and partially not (on other processors) get the value from pp.
Definition at line 461 of file motionSmootherAlgo.C.
void setDisplacement (pointField & patchDisp)
Definition at line 555 of file motionSmootherAlgo.C.
void correctBoundaryConditions (pointVectorField & displacement) const
Special correctBoundaryConditions which evaluates fixedValue.
patches first so they get overwritten with any constraint bc's.
Definition at line 563 of file motionSmootherAlgo.C.
void modifyMotionPoints (pointField & newPoints) const
Apply optional point constraint (2d correction)
Definition at line 630 of file motionSmootherAlgo.C.
Foam::tmp< Foam::pointField > curPoints () const
Get the current points (oldPoints+scale*displacement)
Definition at line 742 of file motionSmootherAlgo.C.
Foam::scalar setErrorReduction (const scalar errorReduction)
Set the errorReduction (by how much to scale the displacement.
at error locations) parameter. Returns the old value. Set to 0 (so revert to old mesh) grows out one cell layer from error faces.
Definition at line 691 of file motionSmootherAlgo.C.
bool scaleMesh (labelList & checkFaces, const bool smoothMesh = true, const label nAllow = 0)
Move mesh with given scale. Return true if mesh ok or has.
less than nAllow errors, false otherwise and locally update scale. Smoothmesh=false means only patch points get moved. Parallel ok (as long as displacement field is consistent across patches)
Definition at line 705 of file motionSmootherAlgo.C.
bool scaleMesh (labelList & checkFaces, const List< labelPair > & baffles, const bool smoothMesh = true, const label nAllow = 0)
Move mesh (with baffles) with given scale.
Definition at line 723 of file motionSmootherAlgo.C.
bool scaleMesh (labelList & checkFaces, const List< labelPair > & baffles, const dictionary & paramDict, const dictionary & meshQualityDict, const bool smoothMesh = true, const label nAllow = 0)
Move mesh with externally provided mesh constraints.
Definition at line 816 of file motionSmootherAlgo.C.
void movePoints ()
Update for new mesh geometry.
Definition at line 681 of file motionSmootherAlgo.C.
void updateMesh ()
Update for new mesh topology.
Definition at line 1026 of file motionSmootherAlgo.C.
bool checkMesh (const bool report, const polyMesh & mesh, const dictionary & dict, labelHashSet & wrongFaces, const bool dryRun = false) static
Check mesh with mesh settings in dict. Collects incorrect faces.
in set. Returns true if one or more faces in error. Parallel ok.
Definition at line 454 of file motionSmootherAlgoCheck.C.
Referenced by motionSmootherAlgo::checkMesh(), snappyLayerDriver::doLayers(), and meshRefinement::mergePatchFacesUndo().
bool checkMesh (const bool report, const polyMesh & mesh, const dictionary & dict, const labelList & checkFaces, labelHashSet & wrongFaces, const bool dryRun = false) static
Check (subset of mesh) with mesh settings in dict.
Collects incorrect faces in set. Returns true if one or more faces in error. Parallel ok.
Definition at line 28 of file motionSmootherAlgoCheck.C.
References motionSmootherAlgo::checkMesh().
bool checkMesh (const bool report, const polyMesh & mesh, const dictionary & dict, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet & wrongFaces, const bool dryRun = false) static
Check (subset of mesh including baffles) with mesh settings.
in dict. Collects incorrect faces in set. Returns true if one or more faces in error. Parallel ok.
Definition at line 51 of file motionSmootherAlgoCheck.C.
bool checkMesh (const bool report, const dictionary & dict, const polyMeshGeometry & meshGeom, const pointField & points, const labelList & checkFaces, labelHashSet & wrongFaces, const bool dryRun = false) static
Check part of mesh with mesh settings in dict.
Collects incorrect faces in set. Returns true if one or more faces in error. Parallel ok.
Definition at line 474 of file motionSmootherAlgoCheck.C.
bool checkMesh (const bool report, const dictionary & dict, const polyMeshGeometry & meshGeom, const pointField & points, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet & wrongFaces, const bool dryRun = false) static
Check part of mesh including baffles with mesh settings in dict.
Collects incorrect faces in set. Returns true if one or more faces in error. Parallel ok.
Definition at line 501 of file motionSmootherAlgoCheck.C.
void smooth (const GeometricField< Type, pointPatchField, pointMesh > & fld, const scalarField & edgeWeight, GeometricField< Type, pointPatchField, pointMesh > & newFld) const
Fully explicit smoothing of fields (not positions)
of internal points with varying diffusivity.
Definition at line 226 of file motionSmootherAlgoTemplates.C.
Type get (const dictionary & dict, const word & keyword, const bool noExit, enum keyType::option matchOpt, const Type & defaultValue = Zero) static
Wrapper around dictionary::get which does not exit.
Definition at line 288 of file motionSmootherAlgoTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::pointPatchField, Foam::pointMesh> > avg (const GeometricField< Type, pointPatchField, pointMesh > & fld, const scalarField & edgeWeight) const
Definition at line 135 of file motionSmootherAlgoTemplates.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSmoother/motionSmootherAlgo.H
src/dynamicMesh/motionSmoother/motionSmootherAlgo.C
src/dynamicMesh/motionSmoother/motionSmootherAlgoCheck.C
src/dynamicMesh/motionSmoother/motionSmootherAlgoTemplates.C