OpenFOAM: scatterModel Class Reference
scatterModel Class Reference abstract
Base class for radiation scattering.
Public Member Functions
TypeName ("scatterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, scatterModel, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
scatterModel (const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~scatterModel ()
Destructor.
virtual tmp< volScalarField > sigmaEff () const =0
Return scatter coefficient.
Static Public Member Functions
static autoPtr< scatterModel > New (const dictionary &dict, const fvMesh &mesh)
Protected Attributes
const fvMesh & mesh_
Reference to the fvMesh.
Detailed Description
Base class for radiation scattering.
Definition at line 46 of file scatterModel.H.
Constructor & Destructor Documentation
scatterModel (const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 39 of file scatterModel.C.
~scatterModel () virtual
Destructor.
Definition at line 50 of file scatterModel.C.
Member Function Documentation
TypeName ("scatterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , scatterModel , dictionary , (const dictionary &dict, const fvMesh &mesh) , (dict, mesh))
Foam::autoPtr< Foam::radiation::scatterModel > New (const dictionary & dict, const fvMesh & mesh) static
Definition at line 28 of file scatterModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, and mesh.
virtual tmp<volScalarField> sigmaEff () const pure virtual
Return scatter coefficient.
Implemented in constantScatter, cloudScatter, and noScatter.
Member Data Documentation
const fvMesh& mesh_ protected
Reference to the fvMesh.
Definition at line 56 of file scatterModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/radiation/submodels/scatterModel/scatterModel/scatterModel.H
src/thermophysicalModels/radiation/submodels/scatterModel/scatterModel/scatterModel.C
src/thermophysicalModels/radiation/submodels/scatterModel/scatterModel/scatterModelNew.C