OpenFOAM: snappySnapDriver Class Reference
snappySnapDriver Class Reference
All to do with snapping to surface.
Public Member Functions
ClassName ("snappySnapDriver")
Runtime type information.
snappySnapDriver (meshRefinement &meshRefiner, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const bool dryRun=false)
Construct from components.
autoPtr< mapPolyMesh > mergeZoneBaffles (const List< labelPair > &)
Merge baffles.
void detectNearSurfaces (const scalar planarCos, const indirectPrimitivePatch &, const pointField &nearestPoint, const vectorField &nearestNormal, vectorField &disp) const
Per patch point override displacement if in gap situation.
void smoothDisplacement (const snapParameters &snapParams, motionSmoother &) const
Smooth the displacement field to the internal.
bool scaleMesh (const snapParameters &snapParams, const label nInitErrors, const List< labelPair > &baffles, motionSmoother &)
Do the hard work: move the mesh according to displacement,.
autoPtr< mapPolyMesh > repatchToSurface (const snapParameters &snapParams, const labelList &adaptPatchIDs, const labelList &preserveFaces)
Repatch faces according to surface nearest the face centre.
void doSnap (const dictionary &snapDict, const dictionary &motionDict, const meshRefinement::FaceMergeType mergeType, const scalar featureCos, const scalar planarAngle, const snapParameters &snapParams)
template<class FaceList >
Foam::labelList getFacePoints (const indirectPrimitivePatch &pp, const FaceList &faces)
Static Public Member Functions
static scalarField calcSnapDistance (const fvMesh &mesh, const snapParameters &snapParams, const indirectPrimitivePatch &)
Calculate edge length per patch point.
static void preSmoothPatch (const meshRefinement &meshRefiner, const snapParameters &snapParams, const label nInitErrors, const List< labelPair > &baffles, motionSmoother &)
Smooth the mesh (patch and internal) to increase visibility.
static tmp< pointField > avgCellCentres (const fvMesh &mesh, const indirectPrimitivePatch &)
Helper: calculate average cell centre per point.
static vectorField calcNearestSurface (const bool strictRegionSnap, const meshRefinement &meshRefiner, const labelList &globalToMasterPatch, const labelList &globalToSlavePatch, const scalarField &snapDist, const indirectPrimitivePatch &, pointField &nearestPoint, vectorField &nearestNormal)
Per patch point calculate point on nearest surface. Set as.
Detailed Description
All to do with snapping to surface.
Source files
snappySnapDriver.H
snappySnapDriver.C
snappySnapDriverFeature.C
Definition at line 54 of file snappySnapDriver.H.
Constructor & Destructor Documentation
snappySnapDriver (meshRefinement & meshRefiner, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const bool dryRun = false)
Construct from components.
Definition at line 751 of file snappySnapDriver.C.
Member Function Documentation
ClassName ("snappySnapDriver")
Runtime type information.
autoPtr<mapPolyMesh> mergeZoneBaffles (const List< labelPair > &)
Merge baffles.
Foam::scalarField calcSnapDistance (const fvMesh & mesh, const snapParameters & snapParams, const indirectPrimitivePatch & pp) static
Calculate edge length per patch point.
Definition at line 768 of file snappySnapDriver.C.
void preSmoothPatch (const meshRefinement & meshRefiner, const snapParameters & snapParams, const label nInitErrors, const List< labelPair > & baffles, motionSmoother & meshMover) static
Smooth the mesh (patch and internal) to increase visibility.
of surface points (on castellated mesh) w.r.t. surface.
Definition at line 808 of file snappySnapDriver.C.
Foam::tmp< Foam::pointField > avgCellCentres (const fvMesh & mesh, const indirectPrimitivePatch & pp) static
Helper: calculate average cell centre per point.
Definition at line 972 of file snappySnapDriver.C.
void detectNearSurfaces (const scalar planarCos, const indirectPrimitivePatch & pp, const pointField & nearestPoint, const vectorField & nearestNormal, vectorField & disp) const
Per patch point override displacement if in gap situation.
Definition at line 1076 of file snappySnapDriver.C.
References meshRefinement::ATTRACTION, d, Foam::expressions::patchExpr::debug, end(), Foam::endl(), refinementSurfaces::findNearestIntersection(), forAll, meshRefinement::getMasterPoints(), surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), i, Foam::Info, PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), Time::path(), autoPtr< T >::reset(), Foam::returnReduce(), Foam::start, refinementSurfaces::surfaces(), refinementSurfaces::surfZones(), fvMesh::time(), and autoPtr< T >::valid().
Foam::vectorField calcNearestSurface (const bool strictRegionSnap, const meshRefinement & meshRefiner, const labelList & globalToMasterPatch, const labelList & globalToSlavePatch, const scalarField & snapDist, const indirectPrimitivePatch & pp, pointField & nearestPoint, vectorField & nearestNormal) static
Per patch point calculate point on nearest surface. Set as.
boundary conditions of motionSmoother displacement field. Return displacement of patch points.
Definition at line 1752 of file snappySnapDriver.C.
void smoothDisplacement (const snapParameters & snapParams, motionSmoother & meshMover) const
Smooth the displacement field to the internal.
Definition at line 2086 of file snappySnapDriver.C.
bool scaleMesh (const snapParameters & snapParams, const label nInitErrors, const List< labelPair > & baffles, motionSmoother & meshMover)
Do the hard work: move the mesh according to displacement,.
locally relax the displacement. Return true if ended up with correct mesh, false if not.
Definition at line 2160 of file snappySnapDriver.C.
Foam::autoPtr< Foam::mapPolyMesh > repatchToSurface (const snapParameters & snapParams, const labelList & adaptPatchIDs, const labelList & preserveFaces)
Repatch faces according to surface nearest the face centre.
calculate face-wise snap distance as max of point-wise
calculate face-wise nearest surface point
repatch face according to patch for surface point.
Definition at line 2227 of file snappySnapDriver.C.
References polyMesh::boundaryMesh(), cpuTimePosix::cpuTimeIncrement(), Foam::endl(), primitiveMesh::faceCentres(), polyMesh::faceZones(), refinementSurfaces::findNearestRegion(), forAll, surfaceZonesInfo::getNamedSurfaces(), surfaceZonesInfo::getUnnamedSurfaces(), refinementSurfaces::globalRegion(), i, Foam::Info, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), meshRefinement::makePatch(), Foam::max(), primitiveMesh::nFaces(), Foam::nl, Foam::returnReduce(), PtrList< T >::set(), Foam::sqr(), polyPatch::start(), refinementSurfaces::surfaces(), refinementSurfaces::surfZones(), and fvMesh::time().
void doSnap (const dictionary & snapDict, const dictionary & motionDict, const meshRefinement::FaceMergeType mergeType, const scalar featureCos, const scalar planarAngle, const snapParameters & snapParams)
Only if in feature attraction mode:
Nearest feature
Any faces to split
Indices in face to split across
Definition at line 2523 of file snappySnapDriver.C.
Foam::labelList getFacePoints (const indirectPrimitivePatch & pp, const FaceList & faces)
Definition at line 28 of file snappySnapDriverTemplates.C.
References HashTable< T, Key, Hash >::cfind(), f(), forAll, i, iter, PrimitivePatch< Face, FaceList, PointField, PointType >::meshPointMap(), and PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriver.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriver.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriverFeature.C
src/mesh/snappyHexMesh/snappyHexMeshDriver/snappySnapDriverTemplates.C