OpenFOAM: ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > Class Template Reference
ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > Class Template Reference
General class for handling chemically-activated bimolecular reactions.
Public Member Functions
ChemicallyActivatedReactionRate (const ReactionRate &k0, const ReactionRate &kInf, const ChemicallyActivationFunction &F, const thirdBodyEfficiencies &tbes)
Construct from components.
ChemicallyActivatedReactionRate (const speciesTable &species, const dictionary &dict)
Construct from dictionary.
scalar operator() (const scalar p, const scalar T, const scalarField &c) const
void write (Ostream &os) const
Write to stream.
Static Public Member Functions
static word type ()
Return the type name.
Friends
Ostream & operator (Ostream &, const ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > &)
Detailed Description
template<class ReactionRate, class ChemicallyActivationFunction>
class Foam::ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >
General class for handling chemically-activated bimolecular reactions.
Source files
ChemicallyActivatedReactionRate.H
ChemicallyActivatedReactionRateI.H
Definition at line 45 of file ChemicallyActivatedReactionRate.H.
Constructor & Destructor Documentation
ChemicallyActivatedReactionRate (const ReactionRate & k0, const ReactionRate & kInf, const ChemicallyActivationFunction & F, const thirdBodyEfficiencies & tbes) inline
Construct from components.
Definition at line 29 of file ChemicallyActivatedReactionRateI.H.
ChemicallyActivatedReactionRate (const speciesTable & species, const dictionary & dict) inline
Construct from dictionary.
Definition at line 49 of file ChemicallyActivatedReactionRateI.H.
Member Function Documentation
static word type () inline static
Return the type name.
Definition at line 101 of file ChemicallyActivatedReactionRate.H.
Foam::scalar operator() (const scalar p, const scalar T, const scalarField & c) const inline
Definition at line 69 of file ChemicallyActivatedReactionRateI.H.
References c(), p, Pr(), and Foam::T().
void write (Ostream & os) const inline
Write to stream.
Definition at line 89 of file ChemicallyActivatedReactionRateI.H.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/reactionRate/ChemicallyActivatedReactionRate/ChemicallyActivatedReactionRate.H
src/thermophysicalModels/specie/reaction/reactionRate/ChemicallyActivatedReactionRate/ChemicallyActivatedReactionRateI.H