OpenFOAM: surfaceZonesInfo Class Reference
surfaceZonesInfo Class Reference
Public Types
enum areaSelectionAlgo { INSIDE, OUTSIDE, INSIDEPOINT, NONE }
Types of selection of area.
enum faceZoneType { INTERNAL, BAFFLE, BOUNDARY }
What to do with faceZone faces.
Public Member Functions
surfaceZonesInfo (const searchableSurface &surface, const dictionary &surfacesDict)
Construct from surfaces and dictionary.
surfaceZonesInfo (const word &faceZoneNames, const word &cellZoneNames, const areaSelectionAlgo &zoneInside, const point &zoneInsidePoints, const faceZoneType &faceType)
Construct from components.
surfaceZonesInfo (const surfaceZonesInfo &)
Copy constructor.
autoPtr< surfaceZonesInfo > clone () const
Return clone.
const word & faceZoneName () const
Per 'interface' surface : empty or name of faceZone to put.
const word & cellZoneName () const
Per 'interface' surface : empty or name of cellZone to put.
const areaSelectionAlgo & zoneInside () const
const point & zoneInsidePoint () const
Get specified inside locations for surfaces with a cellZone.
const faceZoneType & faceType () const
How to handle face of surfaces with a faceZone.
Static Public Member Functions
static labelList getUnnamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
Get indices of unnamed surfaces (surfaces without faceZoneName)
static labelList getNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
Get indices of named surfaces (surfaces with faceZoneName)
static labelList getStandaloneNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
Get indices of named surfaces without a cellZone.
static labelList getClosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
Get indices of surfaces with a cellZone that are closed and.
static labelList getUnclosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
Get indices of surfaces with a cellZone that are unclosed.
static labelList getAllClosedNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList, const searchableSurfaces &allGeometry, const labelList &surfaces)
Get indices of surfaces with a cellZone that are closed.
static labelList getInsidePointNamedSurfaces (const PtrList< surfaceZonesInfo > &surfList)
Get indices of surfaces with a cellZone that have 'insidePoint'.
static label addCellZone (const word &name, const labelList &addressing, polyMesh &mesh)
static labelList addCellZonesToMesh (const PtrList< surfaceZonesInfo > &surfList, const labelList &namedSurfaces, polyMesh &mesh)
static label addFaceZone (const word &name, const labelList &addressing, const boolList &flipMap, polyMesh &mesh)
static labelList addFaceZonesToMesh (const PtrList< surfaceZonesInfo > &surfList, const labelList &namedSurfaces, polyMesh &mesh)
Static Public Attributes
static const Enum
< areaSelectionAlgo > areaSelectionAlgoNames
static const Enum< faceZoneType > faceZoneTypeNames
Detailed Description
Source files
surfaceZonesInfo.H
surfaceZonesInfo.C
Definition at line 56 of file surfaceZonesInfo.H.
Member Enumeration Documentation
enum areaSelectionAlgo
Types of selection of area.
Enumerator
INSIDE
OUTSIDE
INSIDEPOINT
NONE
Definition at line 63 of file surfaceZonesInfo.H.
enum faceZoneType
What to do with faceZone faces.
Enumerator
INTERNAL
BAFFLE
BOUNDARY
Definition at line 76 of file surfaceZonesInfo.H.
Constructor & Destructor Documentation
surfaceZonesInfo (const searchableSurface & surface, const dictionary & surfacesDict)
Construct from surfaces and dictionary.
Definition at line 58 of file surfaceZonesInfo.C.
surfaceZonesInfo (const word & faceZoneNames, const word & cellZoneNames, const areaSelectionAlgo & zoneInside, const point & zoneInsidePoints, const faceZoneType & faceType)
Construct from components.
Definition at line 137 of file surfaceZonesInfo.C.
surfaceZonesInfo (const surfaceZonesInfo & surfZone)
Copy constructor.
Definition at line 153 of file surfaceZonesInfo.C.
Member Function Documentation
autoPtr<surfaceZonesInfo> clone () const inline
Return clone.
Definition at line 162 of file surfaceZonesInfo.H.
const word& faceZoneName () const inline
Per 'interface' surface : empty or name of faceZone to put.
faces into
Definition at line 177 of file surfaceZonesInfo.H.
const word& cellZoneName () const inline
Per 'interface' surface : empty or name of cellZone to put.
cells into
Definition at line 187 of file surfaceZonesInfo.H.
const areaSelectionAlgo& zoneInside () const inline
Definition at line 192 of file surfaceZonesInfo.H.
const point& zoneInsidePoint () const inline
Get specified inside locations for surfaces with a cellZone.
Definition at line 200 of file surfaceZonesInfo.H.
const faceZoneType& faceType () const inline
How to handle face of surfaces with a faceZone.
Definition at line 208 of file surfaceZonesInfo.H.
Foam::labelList getUnnamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Get indices of unnamed surfaces (surfaces without faceZoneName)
Definition at line 164 of file surfaceZonesInfo.C.
Referenced by snappySnapDriver::detectNearSurfaces(), and snappySnapDriver::repatchToSurface().
Foam::labelList getNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Get indices of named surfaces (surfaces with faceZoneName)
Definition at line 185 of file surfaceZonesInfo.C.
Referenced by snappySnapDriver::detectNearSurfaces(), snappySnapDriver::repatchToSurface(), and meshRefinement::zonify().
Foam::labelList getStandaloneNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Get indices of named surfaces without a cellZone.
Definition at line 210 of file surfaceZonesInfo.C.
Foam::labelList getClosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Get indices of surfaces with a cellZone that are closed and.
have 'inside' or 'outside' selection.
Definition at line 236 of file surfaceZonesInfo.C.
Foam::labelList getUnclosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Get indices of surfaces with a cellZone that are unclosed.
Definition at line 268 of file surfaceZonesInfo.C.
Foam::labelList getAllClosedNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList, const searchableSurfaces & allGeometry, const labelList & surfaces) static
Get indices of surfaces with a cellZone that are closed.
Definition at line 295 of file surfaceZonesInfo.C.
Foam::labelList getInsidePointNamedSurfaces (const PtrList< surfaceZonesInfo > & surfList) static
Get indices of surfaces with a cellZone that have 'insidePoint'.
section.
Definition at line 323 of file surfaceZonesInfo.C.
Foam::label addCellZone (const word & name, const labelList & addressing, polyMesh & mesh) static
Definition at line 349 of file surfaceZonesInfo.C.
Foam::labelList addCellZonesToMesh (const PtrList< surfaceZonesInfo > & surfList, const labelList & namedSurfaces, polyMesh & mesh) static
Definition at line 380 of file surfaceZonesInfo.C.
Referenced by meshRefinement::zonify().
Foam::label addFaceZone (const word & name, const labelList & addressing, const boolList & flipMap, polyMesh & mesh) static
Definition at line 432 of file surfaceZonesInfo.C.
Referenced by meshRefinement::zonify().
Foam::labelList addFaceZonesToMesh (const PtrList< surfaceZonesInfo > & surfList, const labelList & namedSurfaces, polyMesh & mesh) static
Definition at line 465 of file surfaceZonesInfo.C.
Referenced by meshRefinement::zonify().
Member Data Documentation
const Foam::Enum< Foam::surfaceZonesInfo::areaSelectionAlgo > areaSelectionAlgoNames static
Definition at line 71 of file surfaceZonesInfo.H.
Referenced by refinementSurfaces::findInside().
const Foam::Enum< Foam::surfaceZonesInfo::faceZoneType > faceZoneTypeNames static
Definition at line 83 of file surfaceZonesInfo.H.
Referenced by meshRefinement::dupNonManifoldBoundaryPoints().
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/refinementSurfaces/surfaceZonesInfo.H
src/mesh/snappyHexMesh/refinementSurfaces/surfaceZonesInfo.C