OpenFOAM: PDRblock Class Reference
PDRblock Class Reference
A single block x-y-z rectilinear mesh addressable as i,j,k with simplified creation. Some of the input is similar to blockMeshDict, but since this specialization is for a single-block that is aligned with the x-y-z directions, it provides a different means of specifying the mesh.
Classes
class location
Grid locations in an axis direction.
Public Member Functions
PDRblock ()
Construct zero-size.
PDRblock (const UList< scalar > &xgrid, const UList< scalar > &ygrid, const UList< scalar > &zgrid)
Construct from components.
PDRblock (const dictionary &dict, bool verbose=false)
Construct from dictionary.
bool read (const dictionary &dict)
Read dictionary.
void reset (const UList< scalar > &xgrid, const UList< scalar > &ygrid, const UList< scalar > &zgrid)
Reset grid locations and mesh i-j-k sizing.
const Vector< location > & grid () const
The grid point locations in the i,j,k (x,y,z) directions.
const boundBox & bounds () const
The mesh bounding box.
const scalar & minEdgeLen () const
The min edge length.
scalar dx (const label i) const
Cell size in x-direction at i position.
scalar dx (const labelVector &ijk) const
Cell size in x-direction at i position.
scalar dy (const label j) const
Cell size in y-direction at j position.
scalar dy (const labelVector &ijk) const
Cell size in y-direction at j position.
scalar dz (const label k) const
Cell size in z-direction at k position.
scalar dz (const labelVector &ijk) const
Cell size in z-direction at k position.
vector span (const label i, const label j, const label k) const
Cell dimensions at i,j,k position.
vector span (const labelVector &ijk) const
Cell dimensions at i,j,k position.
point grid (const label i, const label j, const label k) const
Grid point at i,j,k position.
point grid (const labelVector &ijk) const
Grid point at i,j,k position.
point C (const label i, const label j, const label k) const
Cell centre at i,j,k position.
point C (const labelVector &ijk) const
Cell centre at i,j,k position.
scalar V (const label i, const label j, const label k) const
Cell volume at i,j,k position.
scalar V (const labelVector &ijk) const
Cell volume at i,j,k position.
scalar width (const label i, const label j, const label k) const
Characteristic cell size at i,j,k position.
scalar width (const labelVector &ijk) const
Characteristic cell size at i,j,k position.
labelVector findCell (const point &pt) const
Return i,j,k index for cell enclosing this location.
labelVector gridIndex (const point &pt, const scalar relTol=0.01) const
Obtain i,j,k grid index for point location within specified.
autoPtr< polyMesh > mesh (const IOobject &io) const
Create polyMesh for grid definition and patch information.
Public Member Functions inherited from ijkMesh
ijkMesh ()
Construct zero-sized.
ijkMesh (const labelVector &ijk)
Construct with addressing.
ijkMesh (const label nx, const label ny, const label nz)
Construct with addressing.
label nPoints () const
The number of mesh points (nx+1)*(ny+1)*(nz+1) in the i-j-k mesh.
label nCells () const
The number of mesh cells (nx*ny*nz) in the i-j-k mesh.
label nFaces () const
The total number of mesh faces in the i-j-k mesh.
label nInternalFaces () const
The number of internal faces in the i-j-k mesh.
label nBoundaryFaces () const
The number of boundary faces in the i-j-k mesh.
label nBoundaryFaces (const direction shapeFacei) const
The number of boundary faces on the box face.
label cellLabel (const label i, const label j, const label k) const
The linear cell index for an i-j-k position - same as index()
label cellLabel (const labelVector &ijk) const
The linear cell index for an i-j-k position - same as index()
label pointLabel (const label i, const label j, const label k) const
The linear point index for an i-j-k position.
label pointLabel (const labelVector &ijk) const
The linear point index for an i-j-k position.
Public Member Functions inherited from ijkAddressing
ijkAddressing ()
Construct zero-size addressing.
ijkAddressing (const labelVector &ijk)
Construct with addressing.
ijkAddressing (const label ni, const label nj, const label nk)
Construct with addressing components.
bool empty () const
Addressing is considered empty if any component is zero.
const labelVector & sizes () const
The (i,j,k) addressing dimensions.
labelVector & sizes ()
Return the (i,j,k) dimensions for modification.
label size () const
Return the total i*j*k size.
const label & size (const vector::components cmpt) const
The addressing dimension in the given direction.
void clear ()
Reset to (0,0,0) sizing.
void reset (const label ni, const label nj, const label nk)
Change the sizing parameters.
void reset (const labelVector &newSizes)
Change the sizing parameters.
label index (const label i, const label j, const label k) const
Linear addressing index (offset) for an (i,j,k) position.
label index (const labelVector &ijk) const
Linear addressing index (offset) for an (i,j,k) position.
labelVector index (const label idx) const
The (i,j,k) indexing from linear addressing.
void checkIndex (const label i, const label j, const label k, const bool allowExtra=false) const
Check indices are within ni,nj,nk range.
void checkIndex (const labelVector &ijk, const bool allowExtra=false) const
Check indices are within ni,nj,nk range.
void checkSizes () const
Check that all components of sizes() are non-negative.
void checkSizes (const labelVector &other) const
Check that all components of sizes() match.
void checkSizes (const label nTotal) const
Check that the total size matches.
Static Public Member Functions
static const PDRblock & null ()
Return a PDRblock reference to a nullObject.
Detailed Description
A single block x-y-z rectilinear mesh addressable as i,j,k with simplified creation. Some of the input is similar to blockMeshDict, but since this specialization is for a single-block that is aligned with the x-y-z directions, it provides a different means of specifying the mesh.
Dictionary controls
Property Description Required Default
x X-direction grid specification yes
y Y-direction grid specification yes
z Z-direction grid specification yes
scale Point scaling no 1.0
boundary Boundary patches yes
defaultPatch Default patch specification no
Grid coordinate controls
Property Description Required Default
points Locations defining the mesh segment yes
nCells Divisions per mesh segment yes
ratios Expansion ratio (end/start) per segment no uniform
The expansion ratios are defined as per blockMesh and represent the ratio of end-size / start-size for the section. A negative value is trapped and treated as its reciprocal.
Source files
PDRblock.H
PDRblockI.H
PDRblock.C
PDRblockCreate.C
Definition at line 137 of file PDRblock.H.
Constructor & Destructor Documentation
PDRblock () inline
Construct zero-size.
Definition at line 23 of file PDRblockI.H.
PDRblock (const UList< scalar > & xgrid, const UList< scalar > & ygrid, const UList< scalar > & zgrid)
Construct from components.
Definition at line 467 of file PDRblock.C.
References Foam::name(), PDRblock::reset(), PtrList< T >::resize(), and PtrList< T >::set().
PDRblock (const dictionary & dict, bool verbose = false) explicit
Construct from dictionary.
Definition at line 493 of file PDRblock.C.
Member Function Documentation
const Foam::PDRblock & null () static
Return a PDRblock reference to a nullObject.
Definition at line 72 of file PDRblock.C.
bool read (const dictionary & dict)
Read dictionary.
Definition at line 505 of file PDRblock.C.
References dictionary::lookupOrDefault(), and dictionary::subDict().
void reset (const UList< scalar > & xgrid, const UList< scalar > & ygrid, const UList< scalar > & zgrid)
Reset grid locations and mesh i-j-k sizing.
Definition at line 523 of file PDRblock.C.
References VectorSpace< Vector< scalar >, scalar, 3 >::nComponents.
Referenced by PDRblock::PDRblock().
const Foam::Vector< Foam::PDRblock::location > & grid () const inline
The grid point locations in the i,j,k (x,y,z) directions.
Definition at line 145 of file PDRblockI.H.
const Foam::boundBox & bounds () const inline
The mesh bounding box.
Definition at line 157 of file PDRblockI.H.
const Foam::scalar & minEdgeLen () const inline
The min edge length.
Definition at line 151 of file PDRblockI.H.
Foam::scalar dx (const label i) const inline
Cell size in x-direction at i position.
Definition at line 163 of file PDRblockI.H.
Referenced by PDRblock::grid(), PDRblock::span(), PDRblock::V(), and PDRblock::width().
Foam::scalar dx (const labelVector & ijk) const inline
Cell size in x-direction at i position.
Definition at line 169 of file PDRblockI.H.
Foam::scalar dy (const label j) const inline
Cell size in y-direction at j position.
Definition at line 175 of file PDRblockI.H.
References Vector< Cmpt >::x().
Referenced by PDRblock::grid(), PDRblock::span(), PDRblock::V(), and PDRblock::width().
Foam::scalar dy (const labelVector & ijk) const inline
Cell size in y-direction at j position.
Definition at line 181 of file PDRblockI.H.
Foam::scalar dz (const label k) const inline
Cell size in z-direction at k position.
Definition at line 187 of file PDRblockI.H.
References Vector< Cmpt >::y().
Referenced by PDRblock::grid(), PDRblock::span(), PDRblock::V(), and PDRblock::width().
Foam::scalar dz (const labelVector & ijk) const inline
Cell size in z-direction at k position.
Definition at line 193 of file PDRblockI.H.
Foam::vector span (const label i, const label j, const label k) const inline
Cell dimensions at i,j,k position.
Definition at line 200 of file PDRblockI.H.
References Vector< Cmpt >::z().
Foam::vector span (const labelVector & ijk) const inline
Cell dimensions at i,j,k position.
Definition at line 210 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), and PDRblock::dz().
Foam::point grid (const label i, const label j, const label k) const inline
Grid point at i,j,k position.
Definition at line 217 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), and PDRblock::dz().
Foam::point grid (const labelVector & ijk) const inline
Grid point at i,j,k position.
Definition at line 227 of file PDRblockI.H.
References i, j, and k.
Foam::point C (const label i, const label j, const label k) const inline
Cell centre at i,j,k position.
Definition at line 240 of file PDRblockI.H.
Foam::point C (const labelVector & ijk) const inline
Cell centre at i,j,k position.
Definition at line 250 of file PDRblockI.H.
Foam::scalar V (const label i, const label j, const label k) const inline
Cell volume at i,j,k position.
Definition at line 263 of file PDRblockI.H.
Referenced by PDRblock::width().
Foam::scalar V (const labelVector & ijk) const inline
Cell volume at i,j,k position.
Definition at line 273 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), and PDRblock::dz().
Foam::scalar width (const label i, const label j, const label k) const inline
Characteristic cell size at i,j,k position.
This is the cubic root of the volume
Definition at line 280 of file PDRblockI.H.
References PDRblock::dx(), PDRblock::dy(), PDRblock::dz(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
Foam::scalar width (const labelVector & ijk) const inline
Characteristic cell size at i,j,k position.
This is the cubic root of the volume
Definition at line 290 of file PDRblockI.H.
References Foam::cbrt(), and PDRblock::V().
Foam::labelVector findCell (const point & pt) const
Return i,j,k index for cell enclosing this location.
The value (-1,-1,-1) is returned for out-of-bounds (not found).
Definition at line 601 of file PDRblock.C.
Foam::labelVector gridIndex (const point & pt, const scalar relTol = 0.01) const
Obtain i,j,k grid index for point location within specified.
relative tolerance of the minEdgeLen. The value (-1,-1,-1) is returned for out-of-bounds (not found). and off-grid
Definition at line 615 of file PDRblock.C.
References Foam::pos().
Foam::autoPtr< Foam::polyMesh > mesh (const IOobject & io) const
Create polyMesh for grid definition and patch information.
Definition at line 296 of file PDRblockCreate.C.
The documentation for this class was generated from the following files:
src/mesh/blockMesh/PDRblockMesh/PDRblock.H
src/mesh/blockMesh/PDRblockMesh/PDRblock.C
src/mesh/blockMesh/PDRblockMesh/PDRblockCreate.C
src/mesh/blockMesh/PDRblockMesh/PDRblockI.H