OpenFOAM: thermalBaffleModel Class Reference
thermalBaffleModel Class Reference abstract
Public Member Functions
TypeName ("thermalBaffleModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermalBaffleModel, mesh,(const word &modelType, const fvMesh &mesh),(modelType, mesh))
declareRunTimeSelectionTable (autoPtr, thermalBaffleModel, dictionary,(const word &modelType, const fvMesh &mesh, const dictionary &dict),(modelType, mesh, dict))
thermalBaffleModel (const fvMesh &mesh)
Construct null from mesh.
thermalBaffleModel (const word &modelType, const fvMesh &mesh)
Construct from type name and mesh.
thermalBaffleModel (const word &modelType, const fvMesh &mesh, const dictionary &dict)
Construct from type name and mesh and dict.
virtual ~thermalBaffleModel ()
Destructor.
virtual const solidThermo & thermo () const =0
Return solid thermo.
const scalarField & thickness () const
Return thickness.
const dimensionedScalar & delta () const
Return geometrical thickness.
bool oneD () const
Return if region is one dimensional.
bool constantThickness () const
Return if region has constant thickness.
virtual const volScalarField & rho () const =0
Return density [kg/m3].
virtual const volScalarField & T () const =0
Return const temperature [K].
virtual const tmp< volScalarField > Cp () const =0
Return specific heat capacity [J/kg/K].
virtual const volScalarField & kappaRad () const =0
Return the region absorptivity [1/m].
virtual const volScalarField & kappa () const =0
Return the region thermal conductivity [W/m/k].
virtual void preEvolveRegion ()
Pre-evolve region.
Public Member Functions inherited from regionModel1D
TypeName ("regionModel1D")
Runtime type information.
regionModel1D (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel1D (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel1D (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh, region type and name and dict.
virtual ~regionModel1D ()
Destructor.
const labelListList & boundaryFaceFaces () const
Return the global face IDs.
const labelListList & boundaryFaceCells () const
Return the global cell IDs.
const labelList & boundaryFaceOppositeFace () const
Return the global boundary face IDs oppositte coupled patch.
const surfaceScalarField & nMagSf () const
Return the face area magnitudes / [m2].
label nLayers () const
Return the number of layers in the region.
Public Member Functions inherited from regionModel
TypeName ("regionModel")
Runtime type information.
regionModel (const fvMesh &mesh, const word &regionType)
Construct null.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, bool readFields=true)
Construct from mesh, region type and name.
regionModel (const fvMesh &mesh, const word &regionType, const word &modelName, const dictionary &dict, bool readFields=true)
Construct from mesh and name and dict.
virtual ~regionModel ()
Destructor.
const fvMesh & primaryMesh () const
Return the reference to the primary mesh database.
const Time & time () const
Return the reference to the time database.
const Switch & active () const
Return the active flag.
const Switch & infoOutput () const
Return the information flag.
const word & modelName () const
Return the model name.
const fvMesh & regionMesh () const
Return the region mesh database.
fvMesh & regionMesh ()
Return the region mesh database for manipulation.
const dictionary & coeffs () const
Return the model coefficients dictionary.
const dictionary & solution () const
Return the solution dictionary.
const IOdictionary & outputProperties () const
Return const access to the output properties dictionary.
IOdictionary & outputProperties ()
Return output properties dictionary.
bool isCoupledPatch (const label regionPatchi) const
Return true if patchi on the local region is a coupled.
bool isRegionPatch (const label primaryPatchi) const
Return true if patchi on the primary region is a coupled.
const labelList & primaryPatchIDs () const
Return the list of patch IDs on the primary region coupled.
const labelList & intCoupledPatchIDs () const
Return the list of patch IDs internally coupled with the.
label regionPatchID (const label primaryPatchID) const
Return region ID corresponding to primaryPatchID.
label nbrCoupledPatchID (const regionModel &nbrRegion, const label regionPatchi) const
Return the coupled patch ID paired with coupled patch.
template<class Type >
tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
Map patch field from another region model to local patch.
template<class Type >
tmp< Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip=false) const
Map patch internal field from another region model to local.
template<class Type >
void toPrimary (const label regionPatchi, List< Type > &regionField) const
Convert a local region field to the primary region.
template<class Type >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField) const
Convert a primary region field to the local region.
template<class Type , class CombineOp >
void toPrimary (const label regionPatchi, List< Type > &regionField, const CombineOp &cop) const
Convert a local region field to the primary region with op.
template<class Type , class CombineOp >
void toRegion (const label regionPatchi, List< Type > &primaryFieldField, const CombineOp &cop) const
Convert a primary region field to the local region with op.
virtual void evolve ()
Main driver routing to evolve the region - calls other evolves.
virtual void evolveRegion ()
Evolve the region.
virtual void postEvolveRegion ()
Post-evolve region.
virtual void info ()
Provide some feedback.
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const Field< Type > &nbrField, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
template<class Type >
Foam::tmp< Foam::Field< Type > > mapRegionPatchInternalField (const regionModel &nbrRegion, const word &fieldName, const label regionPatchi, const bool flip) const
Public Member Functions inherited from IOdictionary
IOdictionary (const IOobject &)
Construct given an IOobject.
IOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
IOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~IOdictionary ()
Destructor.
virtual bool global () const
Is object global.
virtual fileName filePath () const
Return complete path + object name if the file exists.
Public Member Functions inherited from baseIOdictionary
TypeName ("dictionary")
baseIOdictionary (const IOobject &)
Construct given an IOobject.
baseIOdictionary (const IOobject &, const dictionary &)
Construct given an IOobject and dictionary.
baseIOdictionary (const IOobject &, Istream &)
Construct given an IOobject and Istream.
virtual ~baseIOdictionary ()
Destructor.
const word & name () const
Name function is needed to disambiguate those inherited.
virtual bool readData (Istream &)
ReadData function required for regIOobject read operation.
virtual bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
void operator= (const baseIOdictionary &)
Assignment of other baseIOdictionary's entries to this.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Public Member Functions inherited from dictionary
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
Construct given the entry name, parent dictionary and Istream, reading entries until EOF, optionally keeping the header.
dictionary (Istream &is)
Construct top-level dictionary from Istream, reading entries until EOF. Discards the header.
dictionary (Istream &is, bool keepHeader)
Construct top-level dictionary from Istream, reading entries until EOF, optionally keeping the header.
dictionary (const dictionary &parentDict, const dictionary &dict)
Copy construct given the parent dictionary.
dictionary (const dictionary &dict)
Copy construct top-level dictionary.
dictionary (const dictionary *dict)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, dictionary &&dict)
Move construct for given parent dictionary.
dictionary (dictionary &&dict)
Move construct top-level dictionary.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const fileName & name () const
The dictionary name.
fileName & name ()
The dictionary name for modification (use with caution).
word dictName () const
The local dictionary name (final part of scoped name)
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Search for an entry (const access) with the given keyword.
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find for an entry (non-const access) with the given keyword.
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry (const access) with the given keyword.
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Search for a scoped entry (const access) with the given keyword.
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary pointer if present.
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary pointer if present.
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
Search for an entry (const access) with the given keyword.
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return an entry data stream. FatalIOError if not found, or if the number of tokens is incorrect.
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T. FatalIOError if not found, or if the number of tokens is incorrect.
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T with additional checking FatalIOError if not found, or if the number of tokens is incorrect.
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Check if entry is found and is a sub-dictionary.
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary.
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary for manipulation.
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
Find and return a sub-dictionary as a copy, otherwise return an empty dictionary.
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary, otherwise return this dictionary.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
template<class Compare >
wordList sortedToc (const Compare &comp) const
Return table of contents sorted using the specified comparator.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
Substitute the given keyword (which is prefixed by '$')
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
Substitute the given scoped keyword (which is prefixed by '$')
entry * add (entry *entryPtr, bool mergeEntry=false)
Add a new entry.
entry * add (const entry &e, bool mergeEntry=false)
Add an entry.
entry * add (const keyType &k, const word &v, bool overwrite=false)
Add a word entry.
entry * add (const keyType &k, const string &v, bool overwrite=false)
Add a string entry.
entry * add (const keyType &k, const label v, bool overwrite=false)
Add a label entry.
entry * add (const keyType &k, const scalar v, bool overwrite=false)
Add a scalar entry.
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
Add a T entry.
entry * set (entry *entryPtr)
Assign a new entry, overwriting any existing entry.
entry * set (const entry &e)
Assign a new entry, overwriting any existing entry.
entry * set (const keyType &k, const dictionary &v)
Assign a dictionary entry, overwriting any existing entry.
template<class T >
entry * set (const keyType &k, const T &v)
Assign a T entry, overwriting any existing entry.
bool remove (const word &keyword)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &dict)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &dict)
Transfer the contents of the argument and annul the argument.
void checkITstream (const ITstream &is, const word &keyword) const
Check after reading if the input token stream has unconsumed tokens remaining or if there were no tokens in the first place.
bool read (Istream &is)
Read dictionary from Istream.
bool read (Istream &is, bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void writeEntry (const keyType &keyword, Ostream &os) const
Write sub-dictionary with the keyword as its header.
void writeEntries (Ostream &os, const bool extraNewLine=false) const
Write dictionary entries.
void write (Ostream &os, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
const_searcher csearch (const word &keyword, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword.
const_searcher search (const word &keyword, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword.
searcher search (const word &keyword, enum keyType::option=keyType::REGEX)
Search dictionary for given keyword.
const_searcher csearchScoped (const word &keyword, enum keyType::option) const
Search using scoping.
const_searcher searchScoped (const word &keyword, enum keyType::option) const
Search using dot or slash scoping.
searcher searchScoped (const word &keyword, enum keyType::option)
Search using dot or slash scoping.
const dictionary * cfindScopedDict (const fileName &dictPath) const
Locate a sub-dictionary using slash-scoping.
const dictionary * findScopedDict (const fileName &dictPath) const
Locate a sub-dictionary using slash-scoping.
dictionary * findScopedDict (const fileName &dictPath)
Locate a sub-dictionary using slash-scoping.
dictionary * makeScopedDict (const fileName &dictPath)
Locate existing or create sub-dictionary using slash-scoping.
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option) const
Find and return an entry pointer if present, or return a nullptr, using any compatibility names if needed.
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option) const
Find and return an entry if present, otherwise FatalIOError, using any compatibility names if needed.
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Find and return an entry data stream, using any compatibility names if needed.
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Find and return a T using any compatibility names if needed. FatalIOError if not found, or if there are excess tokens.
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, const T &deflt, enum keyType::option=keyType::REGEX) const
Find and return a T, or return the given default value using any compatibility names if needed.
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, T &val, enum keyType::option=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val using any compatibility names if needed. FatalIOError if there are excess tokens.
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, T &val, enum keyType::option=keyType::REGEX) const
Find an entry if present, and assign to T val using any compatibility names if needed. FatalIOError if it is found and there are excess tokens.
void operator= (const dictionary &rhs)
Copy assignment.
void operator+= (const dictionary &rhs)
Include entries from the given dictionary.
void operator|= (const dictionary &rhs)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &rhs)
Unconditionally include entries from the given dictionary.
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T lookupOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value using any compatibility names if needed.
ITstream & FOAM_DEPRECATED_FOR (2018-07,"lookup() method") operator[](const word &keyword) const
Deprecated(2018-07) find and return an entry data stream.
template<class T >
T FOAM_DEPRECATED_FOR (2018-10,"get() method") lookupType(const word &keyword
Deprecated(2018-10) find and return a T.
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
Null construct.
ILList (T *item)
Construct and insert the initial T item pointer.
ILList (Istream &is)
Construct from Istream.
ILList (const ILList< LListBase, T > &lst)
Copy construct using the 'clone()' method for each element.
ILList (ILList< LListBase, T > &&lst)
Move construct.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone 'clone()'.
template<class INew >
ILList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *item)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &lst)
Transfer the contents of the argument into this List and annul the argument list.
void operator= (const ILList< LListBase, T > &lst)
Copy assignment using the 'clone()' method for each element.
void operator= (ILList< LListBase, T > &&lst)
Move assignment.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
Null construct.
UILList (T *item)
Construct and insert the initial T item.
UILList (const UILList< LListBase, T > &lst)
Construct as copy.
T * first ()
The first entry in the list.
const T * first () const
The first entry in the list (const access)
T * last ()
The last entry in the list.
const T * last () const
The last entry in the list (const access)
T * removeHead ()
Remove and return head.
T * remove (T *item)
Remove and return element.
T * remove (iterator &iter)
Remove and return item specified by iterator.
void operator= (const UILList< LListBase, T > &lst)
Copy assignment.
bool operator== (const UILList< LListBase, T > &lst) const
Equality. True both lists are element-wise equal.
bool operator!= (const UILList< LListBase, T > &lst) const
The opposite of the equality operation. Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write UILList with line-breaks when length exceeds shortLen.
iterator begin ()
Iterator to first item in list with non-const access.
const_iterator cbegin () const
Iterator to first item in list with const access.
reverse_iterator rbegin ()
Iterator to last item in list with non-const access.
const_reverse_iterator crbegin () const
Iterator to last item in list with const access.
const_iterator begin () const
Iterator to first item in list with const access.
const_reverse_iterator rbegin () const
Iterator to last item in list with const access.
const iterator & end ()
End of list for forward iterators.
const const_iterator & cend () const
End of list for forward iterators.
const reverse_iterator & rend ()
End of list for reverse iterators.
const const_reverse_iterator & crend () const
End of list for reverse iterators.
const const_iterator & end () const
End of list for forward iterators.
const const_reverse_iterator & rend () const
End of list for reverse iterators.
Static Public Member Functions
static autoPtr
< thermalBaffleModel > New (const fvMesh &mesh)
Return a reference to the selected model.
static autoPtr
< thermalBaffleModel > New (const fvMesh &mesh, const dictionary &dict)
Return a reference to the selected model using dictionary.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Member Functions inherited from dictionary
static autoPtr< dictionary > New (Istream &is)
Construct top-level dictionary on freestore from Istream.
Protected Member Functions
virtual bool read ()
Read control parameters from IO dictionary.
virtual bool read (const dictionary &)
Read control parameters from dictionary.
Protected Member Functions inherited from regionModel1D
tmp< labelField > moveMesh (const scalarList &deltaV, const scalar minDelta=0.0)
Move mesh points according to change in cell volumes.
Protected Member Functions inherited from regionModel
virtual const
AMIPatchToPatchInterpolation & interRegionAMI (const regionModel &nbrRegion, const label regionPatchi, const label nbrPatchi, const bool flip) const
Create or return a new inter-region AMI object.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Protected Attributes
scalarField thickness_
Baffle physical thickness.
dimensionedScalar delta_
Baffle mesh thickness.
bool oneD_
Is it one dimension.
bool constantThickness_
Is thickness constant.
Protected Attributes inherited from regionModel1D
labelListList boundaryFaceFaces_
Global face IDs.
labelListList boundaryFaceCells_
Global cell IDs.
labelList boundaryFaceOppositeFace_
Global boundary face IDs oppositte coupled patch.
label nLayers_
Number of layers in the region.
autoPtr< surfaceScalarField > nMagSfPtr_
Face area magnitude normal to patch.
Switch moveMesh_
Flag to allow mesh movement.
Protected Attributes inherited from regionModel
const fvMesh & primaryMesh_
Reference to the primary mesh database.
const Time & time_
Reference to the time database.
Switch active_
Active flag.
Switch infoOutput_
Active information output.
const word modelName_
Model name.
autoPtr< fvMesh > regionMeshPtr_
Pointer to the region mesh database.
dictionary coeffs_
Model coefficients dictionary.
autoPtr< IOdictionary > outputPropertiesPtr_
Dictionary of output properties.
labelList primaryPatchIDs_
List of patch IDs on the primary region coupled to this region.
labelList intCoupledPatchIDs_
List of patch IDs internally coupled with the primary region.
word regionName_
Region name.
regionModelFunctionObjectList functions_
Region model function objects.
wordList interRegionAMINames_
List of region names this region is coupled to.
PtrList< PtrList
< AMIPatchToPatchInterpolation > > interRegionAMI_
List of AMI objects per coupled region.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Public Types inherited from dictionary
typedef Searcher< true > const_searcher
Searcher with const access.
typedef Searcher< false > searcher
Searcher with non-const access.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values stored.
typedef T * pointer
Pointer for value_type.
typedef const T * const_pointer
Const pointer for value_type.
typedef T & reference
Reference for value_type.
typedef const T & const_reference
Const reference for value_type.
typedef label size_type
The type that can represent the container size.
typedef label difference_type
The difference between iterator objects.
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Attributes inherited from dictionary
friend const_searcher
Declare friendship with the searcher classes.
friend searcher
T bool recursive = false
T bool bool patternMatch
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Public Attributes inherited from dictionary
static int writeOptionalEntries
Report optional keywords and values if not present in dictionary.
static const dictionary null
An empty dictionary, which is also the parent for all dictionaries.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Source files
thermalBaffleModel.H
thermalBaffleModel.C
Definition at line 56 of file thermalBaffleModel.H.
Constructor & Destructor Documentation
thermalBaffleModel (const fvMesh & mesh)
Construct null from mesh.
Definition at line 177 of file thermalBaffleModel.C.
thermalBaffleModel (const word & modelType, const fvMesh & mesh)
Construct from type name and mesh.
Definition at line 206 of file thermalBaffleModel.C.
thermalBaffleModel (const word & modelType, const fvMesh & mesh, const dictionary & dict)
Construct from type name and mesh and dict.
Definition at line 188 of file thermalBaffleModel.C.
~thermalBaffleModel () virtual
Destructor.
Definition at line 223 of file thermalBaffleModel.C.
Member Function Documentation
bool read () protected virtual
Read control parameters from IO dictionary.
Reimplemented from regionModel1D.
Reimplemented in thermalBaffle, and noThermo.
Definition at line 44 of file thermalBaffleModel.C.
bool read (const dictionary & dict) protected virtual
Read control parameters from dictionary.
Reimplemented from regionModel1D.
Reimplemented in thermalBaffle.
Definition at line 51 of file thermalBaffleModel.C.
References regionModel1D::read().
TypeName ("thermalBaffleModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , thermalBaffleModel , mesh , (const word &modelType, const fvMesh &mesh) , (modelType, mesh))
declareRunTimeSelectionTable (autoPtr , thermalBaffleModel , dictionary , (const word &modelType, const fvMesh &mesh, const dictionary &dict) , (modelType, mesh, dict))
autoPtr< thermalBaffleModel > New (const fvMesh & mesh) static
Return a reference to the selected model.
Definition at line 35 of file thermalBaffleModelNew.C.
References TimePaths::constant(), dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::getOrDefault(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, and fvMesh::time().
autoPtr< thermalBaffleModel > New (const fvMesh & mesh, const dictionary & dict) static
Return a reference to the selected model using dictionary.
Definition at line 73 of file thermalBaffleModelNew.C.
virtual const solidThermo& thermo () const pure virtual
Return solid thermo.
Implemented in thermalBaffle, and noThermo.
const scalarField& thickness () const inline
Return thickness.
Definition at line 212 of file thermalBaffleModel.H.
const dimensionedScalar& delta () const inline
Return geometrical thickness.
Definition at line 220 of file thermalBaffleModel.H.
bool oneD () const inline
Return if region is one dimensional.
Definition at line 228 of file thermalBaffleModel.H.
bool constantThickness () const inline
Return if region has constant thickness.
Definition at line 236 of file thermalBaffleModel.H.
virtual const volScalarField& rho () const pure virtual
Return density [kg/m3].
Implemented in thermalBaffle, and noThermo.
virtual const volScalarField& T () const pure virtual
Return const temperature [K].
Implemented in thermalBaffle, and noThermo.
virtual const tmp<volScalarField> Cp () const pure virtual
Return specific heat capacity [J/kg/K].
Implemented in thermalBaffle, and noThermo.
virtual const volScalarField& kappaRad () const pure virtual
Return the region absorptivity [1/m].
Implemented in thermalBaffle, and noThermo.
virtual const volScalarField& kappa () const pure virtual
Return the region thermal conductivity [W/m/k].
Implemented in thermalBaffle, and noThermo.
void preEvolveRegion () virtual
Pre-evolve region.
Reimplemented from regionModel.
Reimplemented in thermalBaffle, and noThermo.
Definition at line 229 of file thermalBaffleModel.C.
Member Data Documentation
scalarField thickness_ protected
Baffle physical thickness.
Definition at line 87 of file thermalBaffleModel.H.
dimensionedScalar delta_ protected
Baffle mesh thickness.
Definition at line 92 of file thermalBaffleModel.H.
bool oneD_ protected
Is it one dimension.
Definition at line 97 of file thermalBaffleModel.H.
bool constantThickness_ protected
Is thickness constant.
Definition at line 102 of file thermalBaffleModel.H.
The documentation for this class was generated from the following files:
src/regionModels/thermalBaffleModels/thermalBaffleModel/thermalBaffleModel.H
src/regionModels/thermalBaffleModels/thermalBaffleModel/thermalBaffleModel.C
src/regionModels/thermalBaffleModels/thermalBaffleModel/thermalBaffleModelNew.C