OpenFOAM: extendedCentredFaceToCellStencil Class Reference
extendedCentredFaceToCellStencil Class Reference
Public Member Functions
extendedCentredFaceToCellStencil (const faceToCellStencil &)
Construct from uncompacted face stencil.
const mapDistribute & map () const
Return reference to the parallel distribution map.
const labelListList & stencil () const
Return reference to the stencil.
void compact ()
After removing elements from the stencil adapt the schedule (map).
template<class T >
void collectData (const GeometricField< T, fvsPatchField, surfaceMesh > &fld, List< List< T >> &stencilFld) const
Use map to get the data into stencil order.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > weightedSum (const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar >> &stencilWeights) const
Sum surface field contributions to create cell values.
Public Member Functions inherited from extendedFaceToCellStencil
extendedFaceToCellStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, List< List< Type >> &stencilFld)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar >> &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedFaceToCellStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvsPatchField, surfaceMesh > &fld, List< List< T >> &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvsPatchField, surfaceMesh > &fld, const List< List< scalar >> &stencilWeights)
Sum surface field contributions to create cell values.
Protected Attributes inherited from extendedFaceToCellStencil
const polyMesh & mesh_
Detailed Description
Source files
extendedCentredFaceToCellStencil.H
extendedCentredFaceToCellStencil.C
Definition at line 47 of file extendedCentredFaceToCellStencil.H.
Constructor & Destructor Documentation
extendedCentredFaceToCellStencil (const faceToCellStencil & stencil) explicit
Construct from uncompacted face stencil.
Definition at line 28 of file extendedCentredFaceToCellStencil.C.
References faceToCellStencil::globalNumbering(), and UPstream::nProcs().
Member Function Documentation
const mapDistribute& map () const inline
Return reference to the parallel distribution map.
Definition at line 95 of file extendedCentredFaceToCellStencil.H.
Referenced by extendedCentredFaceToCellStencil::collectData(), and extendedCentredFaceToCellStencil::stencil().
const labelListList& stencil () const inline
Return reference to the stencil.
Definition at line 103 of file extendedCentredFaceToCellStencil.H.
References extendedFaceToCellStencil::collectData(), and extendedCentredFaceToCellStencil::map().
Referenced by extendedCentredFaceToCellStencil::collectData().
void compact ()
After removing elements from the stencil adapt the schedule (map).
Definition at line 51 of file extendedCentredFaceToCellStencil.C.
void collectData (const GeometricField< T, fvsPatchField, surfaceMesh > & fld, List< List< T >> & stencilFld) const inline
Use map to get the data into stencil order.
Definition at line 118 of file extendedCentredFaceToCellStencil.H.
References extendedCentredFaceToCellStencil::map(), extendedCentredFaceToCellStencil::stencil(), and extendedFaceToCellStencil::weightedSum().
tmp<GeometricField<Type, fvPatchField, volMesh> > weightedSum (const GeometricField< Type, fvsPatchField, surfaceMesh > & fld, const List< List< scalar >> & stencilWeights) const inline
Sum surface field contributions to create cell values.
Definition at line 137 of file extendedCentredFaceToCellStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedCentredFaceToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/faceToCell/extendedCentredFaceToCellStencil.C