OpenFOAM: cyclicAMIFvPatch Class Reference
cyclicAMIFvPatch Class Reference
Cyclic patch for Arbitrary Mesh Interface (AMI)
Public Member Functions
TypeName (cyclicAMIPolyPatch::typeName_())
Runtime type information.
cyclicAMIFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
const cyclicAMIPolyPatch & cyclicAMIPatch () const
Return local reference cast into the cyclic patch.
virtual label neighbPatchID () const
Return neighbour.
virtual bool owner () const
virtual const cyclicAMIFvPatch & neighbPatch () const
Return processor number.
virtual const
AMIPatchToPatchInterpolation & AMI () const
Return a reference to the AMI interpolator.
virtual bool applyLowWeightCorrection () const
Return true if applying the low weight correction.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
const cyclicAMIFvPatch & neighbFvPatch () const
virtual bool coupled () const
Return true if this patch is coupled. This is equivalent.
virtual tmp< vectorField > delta () const
Return delta (P to N) vectors across coupled patch.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &fld, const UList< Type > &defaultValues=UList< Type >()) const
template<class Type >
tmp< Field< Type > > interpolate (const tmp< Field< Type >> &tFld, const UList< Type > &defaultValues=UList< Type >()) const
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Return neighbour field.
Public Member Functions inherited from coupledFvPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
virtual ~coupledFvPatch ()
Destructor.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
Initialise neighbour field transfer.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()=default
Construct null.
virtual ~lduInterface ()=default
Destructor.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise transfer of internal field adjacent to the interface.
Public Member Functions inherited from fvPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coefficient except for coupled patches for which the cell-centre to coupled-cell-centre distance coefficient is returned.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::Patch & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const Type *=nullptr) const
Lookup and return the patchField of the named field from the local objectRegistry.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Public Member Functions inherited from cyclicAMILduInterface
TypeName ("cyclicAMILduInterface")
Runtime type information.
cyclicAMILduInterface ()=default
Construct null.
virtual ~cyclicAMILduInterface ()=default
Destructor.
Protected Member Functions
void makeWeights (scalarField &) const
Make patch weighting factors.
Protected Member Functions inherited from fvPatch
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Detailed Description
Cyclic patch for Arbitrary Mesh Interface (AMI)
Source files
cyclicAMIFvPatch.H
cyclicAMIFvPatch.C
Definition at line 49 of file cyclicAMIFvPatch.H.
Constructor & Destructor Documentation
cyclicAMIFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Construct from polyPatch.
Definition at line 82 of file cyclicAMIFvPatch.H.
Member Function Documentation
void makeWeights (scalarField & w) const protected virtual
Make patch weighting factors.
Implements coupledFvPatch.
Definition at line 50 of file cyclicAMIFvPatch.C.
References cyclicAMIFvPatch::neighbFvPatch(), UPstream::parRun(), and fvPatch::size().
TypeName (cyclicAMIPolyPatch:: typeName_())
Runtime type information.
const cyclicAMIPolyPatch& cyclicAMIPatch () const inline
Return local reference cast into the cyclic patch.
Definition at line 97 of file cyclicAMIFvPatch.H.
virtual label neighbPatchID () const inline virtual
Return neighbour.
Implements cyclicAMILduInterface.
Definition at line 105 of file cyclicAMIFvPatch.H.
References cyclicAMIPolyPatch::owner().
virtual bool owner () const inline virtual
Implements cyclicAMILduInterface.
Definition at line 110 of file cyclicAMIFvPatch.H.
References fvPatch::boundaryMesh(), and cyclicAMIPolyPatch::neighbPatchID().
virtual const cyclicAMIFvPatch& neighbPatch () const inline virtual
Return processor number.
Implements cyclicAMILduInterface.
Definition at line 118 of file cyclicAMIFvPatch.H.
References cyclicAMIPolyPatch::AMI().
virtual const AMIPatchToPatchInterpolation& AMI () const inline virtual
Return a reference to the AMI interpolator.
Implements cyclicAMILduInterface.
Definition at line 129 of file cyclicAMIFvPatch.H.
virtual bool applyLowWeightCorrection () const inline virtual
Return true if applying the low weight correction.
Definition at line 137 of file cyclicAMIFvPatch.H.
References coupledPolyPatch::forwardT().
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Implements coupledFvPatch.
Definition at line 146 of file cyclicAMIFvPatch.H.
References coupledPolyPatch::reverseT().
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Implements coupledFvPatch.
Definition at line 154 of file cyclicAMIFvPatch.H.
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Implements coupledFvPatch.
Definition at line 162 of file cyclicAMIFvPatch.H.
const cyclicAMIFvPatch& neighbFvPatch () const inline
Definition at line 167 of file cyclicAMIFvPatch.H.
References cyclicAMIPolyPatch::interpolate().
Referenced by cyclicAMIFvPatch::makeWeights().
bool coupled () const virtual
Return true if this patch is coupled. This is equivalent.
to the coupledPolyPatch::coupled() if parallel running or both sides present, false otherwise
Reimplemented from coupledFvPatch.
Definition at line 44 of file cyclicAMIFvPatch.C.
Foam::tmp< Foam::vectorField > delta () const virtual
Return delta (P to N) vectors across coupled patch.
Implements coupledFvPatch.
Definition at line 92 of file cyclicAMIFvPatch.C.
References fvPatch::makeWeights().
tmp<Field<Type> > interpolate (const Field< Type > & fld, const UList< Type > & defaultValues = UList<Type>()) const inline
Definition at line 190 of file cyclicAMIFvPatch.H.
tmp<Field<Type> > interpolate (const tmp< Field< Type >> & tFld, const UList< Type > & defaultValues = UList<Type>()) const inline
Definition at line 200 of file cyclicAMIFvPatch.H.
Foam::tmp< Foam::labelField > interfaceInternalField (const labelUList & internalData) const virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements coupledFvPatch.
Definition at line 152 of file cyclicAMIFvPatch.C.
References coupledFvPatch::delta().
Foam::tmp< Foam::labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & internalData) const virtual
Return neighbour field.
Implements coupledFvPatch.
Definition at line 161 of file cyclicAMIFvPatch.C.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/constraint/cyclicAMI/cyclicAMIFvPatch.H
src/finiteVolume/fvMesh/fvPatches/constraint/cyclicAMI/cyclicAMIFvPatch.C