OpenFOAM: extrudeModel Class Reference
extrudeModel Class Reference abstract
Top level extrusion model class.
Public Member Functions
TypeName ("extrudeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, extrudeModel, dictionary,(const dictionary &dict),(dict))
Declare runtime constructor selection table.
extrudeModel (const word &modelType, const dictionary &dict)
Construct from dictionary for given model type.
virtual ~extrudeModel ()=default
Destructor.
label nLayers () const
Return the number of layers.
scalar expansionRatio () const
Return the expansion ratio.
scalar sumThickness (const label layer) const
Helper: calculate cumulative relative thickness for layer.
virtual point operator() (const point &surfacePoint, const vector &surfaceNormal, const label layer) const =0
Static Public Member Functions
static autoPtr< extrudeModel > New (const dictionary &dict)
Select null constructed.
Protected Member Functions
extrudeModel (const extrudeModel &)=delete
No copy construct.
void operator= (const extrudeModel &)=delete
No copy assignment.
Protected Attributes
label nLayers_
const scalar expansionRatio_
const dictionary & coeffDict_
Detailed Description
Top level extrusion model class.
Dictionary entries
Property Description Required Default
nLayer Number of extrusion layers no 1
expansionRatio Expansion ratio no 1
Source files
extrudeModel.H
extrudeModel.C
Definition at line 72 of file extrudeModel.H.
Constructor & Destructor Documentation
extrudeModel (const extrudeModel &) protected delete
No copy construct.
extrudeModel (const word & modelType, const dictionary & dict)
Construct from dictionary for given model type.
The corresponding model Coeffs dictionary must exist.
Definition at line 34 of file extrudeModel.C.
virtual ~extrudeModel () virtual default
Destructor.
Member Function Documentation
void operator= (const extrudeModel &) protected delete
No copy assignment.
TypeName ("extrudeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , extrudeModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::extrudeModel > New (const dictionary & dict) static
Select null constructed.
Definition at line 27 of file extrudeModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Foam::label nLayers () const
Return the number of layers.
Definition at line 51 of file extrudeModel.C.
Foam::scalar expansionRatio () const
Return the expansion ratio.
Definition at line 57 of file extrudeModel.C.
Foam::scalar sumThickness (const label layer) const
Helper: calculate cumulative relative thickness for layer.
(layer=0 -> 0; layer=nLayers -> 1)
Definition at line 63 of file extrudeModel.C.
virtual point operator() (const point & surfacePoint, const vector & surfaceNormal, const label layer) const pure virtual
Implemented in offsetSurface, sector, linearNormal, linearDirection, sigmaRadial, linearRadial, and radial.
Member Data Documentation
label nLayers_ protected
Definition at line 78 of file extrudeModel.H.
const scalar expansionRatio_ protected
Definition at line 80 of file extrudeModel.H.
const dictionary& coeffDict_ protected
Definition at line 82 of file extrudeModel.H.
The documentation for this class was generated from the following files:
src/mesh/extrudeModel/extrudeModel/extrudeModel.H
src/mesh/extrudeModel/extrudeModel/extrudeModel.C
src/mesh/extrudeModel/extrudeModel/extrudeModelNew.C