OpenFOAM: medialAxisMeshMover Class Reference
medialAxisMeshMover Class Reference
Mesh motion solver that uses a medial axis algorithm to work out a fraction between the (nearest point on a) moving surface and the (nearest point on a) fixed surface.
Public Member Functions
TypeName ("displacementMedialAxis")
Runtime type information.
medialAxisMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun)
Construct from dictionary and displacement field.
virtual ~medialAxisMeshMover ()
virtual bool move (const dictionary &, const label nAllowableErrors, labelList &checkFaces)
Move mesh using current pointDisplacement boundary values.
virtual void movePoints (const pointField &)
Update local data for geometry changes.
virtual void updateMesh (const mapPolyMesh &)
Update local data for topology changes.
Public Member Functions inherited from externalDisplacementMeshMover
TypeName ("externalDisplacementMeshMover")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, externalDisplacementMeshMover, dictionary,(const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun),(dict, baffles, pointDisplacement, dryRun))
externalDisplacementMeshMover (const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun)
Construct from dictionary and displacement field. Dictionary is.
virtual ~externalDisplacementMeshMover ()
Destructor.
pointVectorField & pointDisplacement ()
Return reference to the point motion displacement field.
const pointVectorField & pointDisplacement () const
Return const reference to the point motion displacement field.
const pointMesh & pMesh () const
const polyMesh & mesh () const
Additional Inherited Members
Static Public Member Functions inherited from externalDisplacementMeshMover
static autoPtr
< externalDisplacementMeshMover > New (const word &type, const dictionary &dict, const List< labelPair > &baffles, pointVectorField &pointDisplacement, const bool dryRun=false)
Return a reference to the selected meshMover model.
Static Protected Member Functions inherited from externalDisplacementMeshMover
static labelList getFixedValueBCs (const pointVectorField &)
Extract fixed-value patchfields.
static autoPtr
< indirectPrimitivePatch > getPatch (const polyMesh &, const labelList &)
Construct patch on selected patches.
Protected Attributes inherited from externalDisplacementMeshMover
List< labelPair > baffles_
Baffles in the mesh.
pointVectorField & pointDisplacement_
Reference to point motion field.
const bool dryRun_
In dry-run mode?
Detailed Description
Mesh motion solver that uses a medial axis algorithm to work out a fraction between the (nearest point on a) moving surface and the (nearest point on a) fixed surface.
This fraction is then used to scale the motion. Use
fixedValue on all moving patches
zeroFixedValue on stationary patches
slip on all slipping patches Note that the fixedValue boundary conditions might be changed by this solver to enforce consistency and a valid resulting mesh.
Source files
medialAxisMeshMover.H
medialAxisMeshMover.C
Definition at line 62 of file medialAxisMeshMover.H.
Constructor & Destructor Documentation
medialAxisMeshMover (const dictionary & dict, const List< labelPair > & baffles, pointVectorField & pointDisplacement, const bool dryRun)
Construct from dictionary and displacement field.
Definition at line 1273 of file medialAxisMeshMover.C.
References update().
~medialAxisMeshMover () virtual
Definition at line 1373 of file medialAxisMeshMover.C.
References Foam::cos(), UList< T >::data(), Foam::expressions::patchExpr::debug, Foam::degToRad(), Foam::endl(), forAll, UList< T >::get(), syncTools::getMasterEdges(), meshRefinement::getMasterEdges(), syncTools::getMasterPoints(), meshRefinement::getMasterPoints(), polyMesh::globalData(), Foam::Info, PointEdgeWave< Type, TrackingData >::iterate(), Foam::mag(), mesh, PrimitivePatch< Face, FaceList, PointField, PointType >::meshEdges(), PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), n, snappyLayerDriver::NOEXTRUDE, Foam::normalised(), nPoints, globalMeshData::nTotalPoints(), path(), points, polyMesh::points(), Foam::Pout, Foam::reduce(), autoPtr< T >::reset(), UList< T >::size(), timeName, autoPtr< T >::valid(), and Foam::Zero.
Member Function Documentation
TypeName ("displacementMedialAxis")
Runtime type information.
bool move (const dictionary & moveDict, const label nAllowableErrors, labelList & checkFaces) virtual
Move mesh using current pointDisplacement boundary values.
Return true if successful (errors on checkFaces less than allowable). Updates pointDisplacement.
Name of field specifying min thickness
Move mesh according to calculated displacement
Implements externalDisplacementMeshMover.
Definition at line 1814 of file medialAxisMeshMover.C.
References Foam::mag(), and snappyLayerDriver::NOEXTRUDE.
void movePoints (const pointField & p) virtual
Update local data for geometry changes.
Reimplemented from externalDisplacementMeshMover.
Definition at line 1880 of file medialAxisMeshMover.C.
virtual void updateMesh (const mapPolyMesh &) inline virtual
Update local data for topology changes.
Reimplemented from externalDisplacementMeshMover.
Definition at line 288 of file medialAxisMeshMover.H.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/externalDisplacementMeshMover/medialAxisMeshMover.H
src/mesh/snappyHexMesh/externalDisplacementMeshMover/medialAxisMeshMover.C