OpenFOAM: ReactingMultiphaseParcel< ParcelType > Class Template Reference
ReactingMultiphaseParcel< ParcelType > Class Template Reference
Parcels
Multiphase variant of the reacting parcel class with one/two-way coupling with the continuous phase.
Classes
class constantProperties
Class to hold reacting multiphase particle constant properties.
class iNew
Factory class to read-construct particles used for.
Public Types
typedef ParcelType::trackingData trackingData
Use base tracking data.
Public Member Functions
TypeName ("ReactingMultiphaseParcel")
Runtime type information.
AddToPropertyList (ParcelType," nGas(Y1..YN)"+" nLiquid(Y1..YN)"+" nSolid(Y1..YN)")
String representation of properties.
ReactingMultiphaseParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from mesh, position and topology.
ReactingMultiphaseParcel (const polyMesh &mesh, const vector &position, const label celli)
Construct from a position and a cell, searching for the rest of the.
ReactingMultiphaseParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y0, const scalarField &YGas0, const scalarField &YLiquid0, const scalarField &YSolid0, const constantProperties &constProps)
Construct from components.
ReactingMultiphaseParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
ReactingMultiphaseParcel (const ReactingMultiphaseParcel &p)
Construct as a copy.
ReactingMultiphaseParcel (const ReactingMultiphaseParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
const scalarField & YGas () const
Return const access to mass fractions of gases.
const scalarField & YLiquid () const
Return const access to mass fractions of liquids.
const scalarField & YSolid () const
Return const access to mass fractions of solids.
label canCombust () const
Return const access to the canCombust flag.
scalarField & YGas ()
Return access to mass fractions of gases.
scalarField & YLiquid ()
Return access to mass fractions of liquids.
scalarField & YSolid ()
Return access to mass fractions of solids.
label & canCombust ()
Return access to the canCombust flag.
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
Set cell values.
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
Correct cell values using latest transfer information.
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
Update parcel properties over the time interval.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
Write individual parcel properties to stream.
template<class TrackCloudType >
Foam::scalar CpEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
template<class TrackCloudType >
Foam::scalar HsEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
template<class TrackCloudType >
Foam::scalar LEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
Read - composition supplied.
template<class CloudType >
static void readFields (CloudType &c)
Read - no composition.
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
Write - composition supplied.
template<class CloudType >
static void writeFields (const CloudType &c)
Read - no composition.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType , class CompositionType >
static void readObjects (CloudType &c, const CompositionType &compModel, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
template<class CloudType , class CompositionType >
static void writeObjects (const CloudType &c, const CompositionType &compModel, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields
Size in bytes of the fields.
static const label GAS
static const label LIQ
static const label SLD
Protected Member Functions
template<class TrackCloudType >
void calcDevolatilisation (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar age, const scalar Ts, const scalar d, const scalar T, const scalar mass, const scalar mass0, const scalarField &YGasEff, const scalarField &YLiquidEff, const scalarField &YSolidEff, label &canCombust, scalarField &dMassDV, scalar &Sh, scalar &N, scalar &NCpW, scalarField &Cs) const
Calculate Devolatilisation.
template<class TrackCloudType >
void calcSurfaceReactions (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar d, const scalar Re, const scalar nu, const scalar T, const scalar mass, const label canCombust, const scalar N, const scalarField &YMix, const scalarField &YGas, const scalarField &YLiquid, const scalarField &YSolid, scalarField &dMassSRGas, scalarField &dMassSRLiquid, scalarField &dMassSRSolid, scalarField &dMassSRCarrier, scalar &Sh, scalar &dhsTrans) const
Calculate surface reactions.
Protected Attributes
scalarField YGas_
Mass fractions of gases [].
scalarField YLiquid_
Mass fractions of liquids [].
scalarField YSolid_
Mass fractions of solids [].
label canCombust_
Flag to identify if the particle can devolatilise and combust.
Friends
Ostream & operator (Ostream &, const ReactingMultiphaseParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingMultiphaseParcel< ParcelType >
Multiphase variant of the reacting parcel class with one/two-way coupling with the continuous phase.
Source files
ReactingMultiphaseParcel.H
ReactingMultiphaseParcelI.H
ReactingMultiphaseParcel.C
ReactingMultiphaseParcelIO.C
Definition at line 51 of file ReactingMultiphaseParcel.H.
Member Typedef Documentation
typedef ParcelType::trackingData trackingData
Use base tracking data.
Definition at line 151 of file ReactingMultiphaseParcel.H.
Constructor & Destructor Documentation
ReactingMultiphaseParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Construct from mesh, position and topology.
Other properties initialised as null
Definition at line 64 of file ReactingMultiphaseParcelI.H.
ReactingMultiphaseParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Construct from a position and a cell, searching for the rest of the.
required topology. Other properties are initialised as null.
Definition at line 82 of file ReactingMultiphaseParcelI.H.
ReactingMultiphaseParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y0, const scalarField & YGas0, const scalarField & YLiquid0, const scalarField & YSolid0, const constantProperties & constProps) inline
Construct from components.
Definition at line 98 of file ReactingMultiphaseParcelI.H.
ReactingMultiphaseParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 43 of file ReactingMultiphaseParcelIO.C.
ReactingMultiphaseParcel (const ReactingMultiphaseParcel< ParcelType > & p)
Construct as a copy.
ReactingMultiphaseParcel (const ReactingMultiphaseParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
void calcDevolatilisation (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar age, const scalar Ts, const scalar d, const scalar T, const scalar mass, const scalar mass0, const scalarField & YGasEff, const scalarField & YLiquidEff, const scalarField & YSolidEff, label & canCombust, scalarField & dMassDV, scalar & Sh, scalar & N, scalar & NCpW, scalarField & Cs) const protected
Calculate Devolatilisation.
Definition at line 500 of file ReactingMultiphaseParcel.C.
References beta(), CompositionModel< CloudType >::carrier(), Foam::cbrt(), Cp, forAll, i, CompositionModel< CloudType >::localToCarrierId(), Foam::max(), Foam::pow(), Foam::constant::thermodynamic::RR, Foam::sqr(), Foam::sqrt(), and Foam::sum().
void calcSurfaceReactions (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar d, const scalar Re, const scalar nu, const scalar T, const scalar mass, const label canCombust, const scalar N, const scalarField & YMix, const scalarField & YGas, const scalarField & YLiquid, const scalarField & YSolid, scalarField & dMassSRGas, scalarField & dMassSRLiquid, scalarField & dMassSRSolid, scalarField & dMassSRCarrier, scalar & Sh, scalar & dhsTrans) const protected
Calculate surface reactions.
Definition at line 601 of file ReactingMultiphaseParcel.C.
TypeName ("ReactingMultiphaseParcel< ParcelType >")
Runtime type information.
AddToPropertyList (ParcelType , " nGas(Y1..YN)"+" nLiquid(Y1..YN)"+" nSolid(Y1..YN)")
String representation of properties.
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 407 of file ReactingMultiphaseParcel.H.
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 415 of file ReactingMultiphaseParcel.H.
const Foam::scalarField & YGas () const inline
Return const access to mass fractions of gases.
Definition at line 184 of file ReactingMultiphaseParcelI.H.
const Foam::scalarField & YLiquid () const inline
Return const access to mass fractions of liquids.
Definition at line 192 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YGas_.
const Foam::scalarField & YSolid () const inline
Return const access to mass fractions of solids.
Definition at line 200 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YLiquid_.
Foam::label canCombust () const inline
Return const access to the canCombust flag.
Definition at line 208 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YSolid_.
Foam::scalarField & YGas () inline
Return access to mass fractions of gases.
Definition at line 215 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::canCombust_.
Foam::scalarField & YLiquid () inline
Return access to mass fractions of liquids.
Definition at line 222 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YGas_.
Foam::scalarField & YSolid () inline
Return access to mass fractions of solids.
Definition at line 229 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YLiquid_.
Foam::label & canCombust () inline
Return access to the canCombust flag.
Definition at line 236 of file ReactingMultiphaseParcelI.H.
References ReactingMultiphaseParcel< ParcelType >::YSolid_.
void setCellValues (TrackCloudType & cloud, trackingData & td)
Set cell values.
Definition at line 140 of file ReactingMultiphaseParcel.C.
void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Correct cell values using latest transfer information.
Definition at line 152 of file ReactingMultiphaseParcel.C.
void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Update parcel properties over the time interval.
Definition at line 166 of file ReactingMultiphaseParcel.C.
void readFields (CloudType & c, const CompositionType & compModel) static
Read - composition supplied.
Definition at line 90 of file ReactingMultiphaseParcelIO.C.
void readFields (CloudType & c) static
Read - no composition.
Definition at line 81 of file ReactingMultiphaseParcelIO.C.
void writeFields (const CloudType & c, const CompositionType & compModel) static
Write - composition supplied.
Definition at line 190 of file ReactingMultiphaseParcelIO.C.
void writeFields (const CloudType & c) static
Read - no composition.
Definition at line 181 of file ReactingMultiphaseParcelIO.C.
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Write individual parcel properties to stream.
Definition at line 280 of file ReactingMultiphaseParcelIO.C.
void readObjects (CloudType & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
no composition
Definition at line 305 of file ReactingMultiphaseParcelIO.C.
void readObjects (CloudType & c, const CompositionType & compModel, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 329 of file ReactingMultiphaseParcelIO.C.
void writeObjects (const CloudType & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
no composition
Definition at line 317 of file ReactingMultiphaseParcelIO.C.
void writeObjects (const CloudType & c, const CompositionType & compModel, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Definition at line 395 of file ReactingMultiphaseParcelIO.C.
Foam::scalar CpEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 44 of file ReactingMultiphaseParcel.C.
Foam::scalar HsEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 64 of file ReactingMultiphaseParcel.C.
Foam::scalar LEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idG, const label idL, const label idS) const
Definition at line 84 of file ReactingMultiphaseParcel.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const ReactingMultiphaseParcel< ParcelType > &) friend
Member Data Documentation
const std::size_t sizeofFields static
Size in bytes of the fields.
Definition at line 70 of file ReactingMultiphaseParcel.H.
const Foam::label GAS static
Definition at line 75 of file ReactingMultiphaseParcel.H.
const Foam::label LIQ static
Definition at line 76 of file ReactingMultiphaseParcel.H.
const Foam::label SLD static
Definition at line 77 of file ReactingMultiphaseParcel.H.
scalarField YGas_ protected
Mass fractions of gases [].
Definition at line 224 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::YLiquid().
scalarField YLiquid_ protected
Mass fractions of liquids [].
Definition at line 229 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::YSolid().
scalarField YSolid_ protected
Mass fractions of solids [].
Definition at line 234 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::canCombust().
label canCombust_ protected
Flag to identify if the particle can devolatilise and combust.
Combustion possible only after volatile content falls below threshold value. States include: 0 = can devolatilise, cannot combust but can change 1 = can devolatilise, can combust -1 = cannot devolatilise or combust, and cannot change
Definition at line 245 of file ReactingMultiphaseParcel.H.
Referenced by ReactingMultiphaseParcel< ParcelType >::YGas().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingMultiphaseParcel/ReactingMultiphaseParcelIO.C