OpenFOAM: adjointTurbulenceModel Class Reference
adjointTurbulenceModel Class Reference abstract
Abstract base class for incompressible adjoint turbulence models (RAS, LES and laminar).
Public Member Functions
TypeName ("adjointTurbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable (autoPtr, adjointTurbulenceModel, adjointTurbulenceModel,(incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName),(primalVars, adjointVars, objManager, adjointTurbulenceModelName))
adjointTurbulenceModel (incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName=typeName)
Construct from components.
virtual ~adjointTurbulenceModel ()=default
Destructor.
tmp< volScalarField > nu () const
Return the laminar viscosity.
virtual const volScalarField & nut () const
Return the turbulence viscosity.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< volSymmTensorField > devReff () const =0
Return the effective stress tensor including the laminar stress.
virtual tmp< fvVectorMatrix > divDevReff (volVectorField &U) const =0
Return the diffusion term for the momentum equation.
virtual tmp< volVectorField > adjointMeanFlowSource ()=0
Source term added to the adjoint mean flow due to the.
virtual void correct ()=0
Solve the adjoint turbulence equations.
virtual bool read ()=0
Read adjointLESProperties or adjointRASProperties dictionary.
virtual bool writeData (Ostream &) const
Default dummy write function.
virtual void nullify ()=0
Nullify all adjoint turbulence model fields and their old times.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Static Public Member Functions
static autoPtr
< adjointTurbulenceModel > New (incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName=typeName)
Return a reference to the selected turbulence model.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Protected Attributes
incompressibleVars & primalVars_
incompressibleAdjointMeanFlowVars & adjointVars_
const Time & runTime_
const fvMesh & mesh_
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Abstract base class for incompressible adjoint turbulence models (RAS, LES and laminar).
Source files
adjointTurbulenceModel.H
adjointTurbulenceModel.C
newTurbulenceModel.C
Definition at line 68 of file adjointTurbulenceModel.H.
Constructor & Destructor Documentation
adjointTurbulenceModel (incompressibleVars & primalVars, incompressibleAdjointMeanFlowVars & adjointVars, objectiveManager & objManager, const word & adjointTurbulenceModelName = typeName)
Construct from components.
Definition at line 42 of file adjointTurbulenceModel.C.
virtual ~adjointTurbulenceModel () virtual default
Destructor.
Member Function Documentation
TypeName ("adjointTurbulenceModel")
Runtime type information.
declareRunTimeNewSelectionTable (autoPtr , adjointTurbulenceModel , adjointTurbulenceModel , (incompressibleVars &primalVars, incompressibleAdjointMeanFlowVars &adjointVars, objectiveManager &objManager, const word &adjointTurbulenceModelName) , (primalVars, adjointVars, objManager, adjointTurbulenceModelName))
autoPtr< adjointTurbulenceModel > New (incompressibleVars & primalVars, incompressibleAdjointMeanFlowVars & adjointVars, objectiveManager & objManager, const word & adjointTurbulenceModelName = typeName) static
Return a reference to the selected turbulence model.
Definition at line 70 of file adjointTurbulenceModel.C.
tmp<volScalarField> nu () const inline
Return the laminar viscosity.
Definition at line 166 of file adjointTurbulenceModel.H.
References incompressibleVars::laminarTransport(), and adjointTurbulenceModel::primalVars_.
Referenced by adjointSpalartAllmaras::conservativeMomentumSource(), and adjointSpalartAllmaras::fv1().
virtual const volScalarField& nut () const inline virtual
Return the turbulence viscosity.
Reimplemented in adjointSpalartAllmaras.
Definition at line 174 of file adjointTurbulenceModel.H.
virtual tmp<volScalarField> nuEff () const inline virtual
Return the effective viscosity.
Definition at line 182 of file adjointTurbulenceModel.H.
virtual tmp<volSymmTensorField> devReff () const pure virtual
Return the effective stress tensor including the laminar stress.
Implemented in adjointSpalartAllmaras, adjointRASModel, and adjointLaminar.
virtual tmp<fvVectorMatrix> divDevReff (volVectorField & U) const pure virtual
Return the diffusion term for the momentum equation.
Implemented in adjointSpalartAllmaras, adjointRASModel, and adjointLaminar.
virtual tmp<volVectorField> adjointMeanFlowSource () pure virtual
Source term added to the adjoint mean flow due to the.
differentiation of the turbulence model
Implemented in adjointSpalartAllmaras, adjointRASModel, and adjointLaminar.
void correct () pure virtual
Solve the adjoint turbulence equations.
Implemented in adjointRASModel, adjointSpalartAllmaras, and adjointLaminar.
Definition at line 123 of file adjointTurbulenceModel.C.
virtual bool read () pure virtual
Read adjointLESProperties or adjointRASProperties dictionary.
Reimplemented from regIOobject.
Implemented in adjointRASModel, adjointSpalartAllmaras, and adjointLaminar.
virtual bool writeData (Ostream &) const inline virtual
Default dummy write function.
Implements regIOobject.
Definition at line 230 of file adjointTurbulenceModel.H.
virtual void nullify () pure virtual
Nullify all adjoint turbulence model fields and their old times.
Implemented in adjointRASModel, adjointSpalartAllmaras, and adjointLaminar.
Member Data Documentation
incompressibleVars& primalVars_ protected
Definition at line 91 of file adjointTurbulenceModel.H.
Referenced by adjointTurbulenceModel::nu(), and adjointSpalartAllmaras::nut().
incompressibleAdjointMeanFlowVars& adjointVars_ protected
Definition at line 92 of file adjointTurbulenceModel.H.
const Time& runTime_ protected
Definition at line 93 of file adjointTurbulenceModel.H.
const fvMesh& mesh_ protected
Definition at line 94 of file adjointTurbulenceModel.H.
Referenced by adjointRASModel::diffusionCoeffVar2(), and adjointRASModel::setChangedPrimalSolution().
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointTurbulenceModel/adjointTurbulenceModel.H
src/optimisation/adjointOptimisation/adjoint/turbulenceModels/incompressibleAdjoint/adjointTurbulenceModel/adjointTurbulenceModel.C