OpenFOAM: liquidMixtureProperties Class Reference
liquidMixtureProperties Class Reference
A mixture of liquids.
Public Member Functions
liquidMixtureProperties (const dictionary &dict)
Construct from dictionary.
liquidMixtureProperties (const liquidMixtureProperties &lm)
Construct copy.
virtual autoPtr
< liquidMixtureProperties > clone () const
Construct and return a clone.
virtual ~liquidMixtureProperties ()=default
Destructor.
const List< word > & components () const
Return the liquid names.
const PtrList< liquidProperties > & properties () const
Return the liquid properties.
label size () const
Return the number of liquids in the mixture.
scalar Tc (const scalarField &X) const
Calculate the critical temperature of mixture.
scalar pvInvert (const scalar p, const scalarField &X) const
Invert the vapour pressure relationship to retrieve the boiling.
scalar Tpc (const scalarField &X) const
Return pseudocritical temperature according to Kay's rule.
scalar Ppc (const scalarField &X) const
Return pseudocritical pressure (modified Prausnitz and Gunn)
scalar Tpt (const scalarField &X) const
Return pseudo triple point temperature (mole averaged formulation)
scalar omega (const scalarField &X) const
Return mixture accentric factor.
scalarField Xs (const scalar p, const scalar Tg, const scalar Tl, const scalarField &Xg, const scalarField &Xl) const
Return the surface molar fractions.
scalar W (const scalarField &X) const
Calculate the mean molecular weight [kg/kmol].
scalarField Y (const scalarField &X) const
Returns the mass fractions corresponding to the given mole fractions.
scalarField X (const scalarField &Y) const
Returns the mole fractions corresponding to the given mass fractions.
scalar rho (const scalar p, const scalar T, const scalarField &X) const
Calculate the mixture density [kg/m^3].
scalar pv (const scalar p, const scalar T, const scalarField &X) const
Calculate the mixture vapour pressure [Pa].
scalar hl (const scalar p, const scalar T, const scalarField &X) const
Calculate the mixture latent heat [J/kg].
scalar Cp (const scalar p, const scalar T, const scalarField &X) const
Calculate the mixture heat capacity [J/(kg K)].
scalar sigma (const scalar p, const scalar T, const scalarField &X) const
Estimate mixture surface tension [N/m].
scalar mu (const scalar p, const scalar T, const scalarField &X) const
Calculate the mixture viscosity [Pa s].
scalar kappa (const scalar p, const scalar T, const scalarField &X) const
Estimate thermal conductivity [W/(m K)].
scalar D (const scalar p, const scalar T, const scalarField &X) const
Vapour diffusivity [m2/s].
Static Public Member Functions
static autoPtr
< liquidMixtureProperties > New (const dictionary &)
Select construct from dictionary.
Detailed Description
A mixture of liquids.
An example of a two component liquid mixture:
    <parentDictionary>
    {
        H2O; // employ default coefficients
        C7H16
        {
            // ... user defined properties for C7H16
        }
    }
Source files
liquidMixtureProperties.H
liquidMixtureProperties.C
See Also
Foam::liquidProperties
Definition at line 64 of file liquidMixtureProperties.H.
Constructor & Destructor Documentation
liquidMixtureProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 33 of file liquidMixtureProperties.C.
References forAll, i, dictionary::isDict(), liquidProperties::New(), UList< T >::size(), dictionary::subDict(), and dictionary::toc().
liquidMixtureProperties (const liquidMixtureProperties & lm)
Construct copy.
Definition at line 66 of file liquidMixtureProperties.C.
virtual ~liquidMixtureProperties () virtual default
Destructor.
Member Function Documentation
virtual autoPtr<liquidMixtureProperties> clone () const inline virtual
Construct and return a clone.
Definition at line 101 of file liquidMixtureProperties.H.
Foam::autoPtr< Foam::liquidMixtureProperties > New (const dictionary & thermophysicalProperties) static
Select construct from dictionary.
Definition at line 84 of file liquidMixtureProperties.C.
const List<word>& components () const inline
Return the liquid names.
Definition at line 126 of file liquidMixtureProperties.H.
References UList< T >::size().
const PtrList<liquidProperties>& properties () const inline
Return the liquid properties.
Definition at line 134 of file liquidMixtureProperties.H.
label size () const inline
Return the number of liquids in the mixture.
Definition at line 142 of file liquidMixtureProperties.H.
Foam::scalar Tc (const scalarField & X) const
Calculate the critical temperature of mixture.
Definition at line 94 of file liquidMixtureProperties.C.
References autoPtr< T >::New().
Foam::scalar pvInvert (const scalar p, const scalarField & X) const
Invert the vapour pressure relationship to retrieve the boiling.
temperature of the mixture as a function of pressure
Definition at line 124 of file liquidMixtureProperties.C.
Foam::scalar Tpc (const scalarField & X) const
Return pseudocritical temperature according to Kay's rule.
Definition at line 167 of file liquidMixtureProperties.C.
Foam::scalar Ppc (const scalarField & X) const
Return pseudocritical pressure (modified Prausnitz and Gunn)
Definition at line 180 of file liquidMixtureProperties.C.
Foam::scalar Tpt (const scalarField & X) const
Return pseudo triple point temperature (mole averaged formulation)
Definition at line 110 of file liquidMixtureProperties.C.
Foam::scalar omega (const scalarField & X) const
Return mixture accentric factor.
Definition at line 195 of file liquidMixtureProperties.C.
Foam::scalarField Xs (const scalar p, const scalar Tg, const scalar Tl, const scalarField & Xg, const scalarField & Xl) const
Return the surface molar fractions.
Definition at line 209 of file liquidMixtureProperties.C.
Foam::scalar W (const scalarField & X) const
Calculate the mean molecular weight [kg/kmol].
from mole fractions
Definition at line 230 of file liquidMixtureProperties.C.
Foam::scalarField Y (const scalarField & X) const
Returns the mass fractions corresponding to the given mole fractions.
Definition at line 243 of file liquidMixtureProperties.C.
Foam::scalarField X (const scalarField & Y) const
Returns the mole fractions corresponding to the given mass fractions.
Definition at line 260 of file liquidMixtureProperties.C.
Foam::scalar rho (const scalar p, const scalar T, const scalarField & X) const
Calculate the mixture density [kg/m^3].
Definition at line 278 of file liquidMixtureProperties.C.
Foam::scalar pv (const scalar p, const scalar T, const scalarField & X) const
Calculate the mixture vapour pressure [Pa].
Definition at line 308 of file liquidMixtureProperties.C.
Foam::scalar hl (const scalar p, const scalar T, const scalarField & X) const
Calculate the mixture latent heat [J/kg].
Definition at line 334 of file liquidMixtureProperties.C.
Foam::scalar Cp (const scalar p, const scalar T, const scalarField & X) const
Calculate the mixture heat capacity [J/(kg K)].
Definition at line 360 of file liquidMixtureProperties.C.
Foam::scalar sigma (const scalar p, const scalar T, const scalarField & X) const
Estimate mixture surface tension [N/m].
Definition at line 386 of file liquidMixtureProperties.C.
Foam::scalar mu (const scalar p, const scalar T, const scalarField & X) const
Calculate the mixture viscosity [Pa s].
Definition at line 423 of file liquidMixtureProperties.C.
Foam::scalar kappa (const scalar p, const scalar T, const scalarField & X) const
Estimate thermal conductivity [W/(m K)].
Li's method, Eq. 10-12.27 - 10.12-19
Definition at line 445 of file liquidMixtureProperties.C.
Foam::scalar D (const scalar p, const scalar T, const scalarField & X) const
Vapour diffusivity [m2/s].
Definition at line 491 of file liquidMixtureProperties.C.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidMixtureProperties/liquidMixtureProperties.H
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidMixtureProperties/liquidMixtureProperties.C