OpenFOAM: interfaceCompositionModel Class Reference
interfaceCompositionModel Class Reference abstract
Generic base class for interface composition models. These models describe the composition in phase 1 of the supplied pair at the interface with phase 2.
Public Types
enum modelVariable { T, P, Y }
Enumeration for variable based mass transfer models.
Public Member Functions
TypeName ("interfaceCompositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interfaceCompositionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
interfaceCompositionModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~interfaceCompositionModel ()=default
Destructor.
virtual void update (const volScalarField &Tf)=0
Update the composition.
const hashedWordList & species () const
Return the transferring species names.
bool transports (word &speciesName) const
Returns whether the species is transported by the model and provides the name of the diffused species.
virtual tmp< volScalarField > Yf (const word &speciesName, const volScalarField &Tf) const =0
Interface mass fraction.
virtual tmp< volScalarField > YfPrime (const word &speciesName, const volScalarField &Tf) const =0
The interface mass fraction derivative w.r.t. temperature.
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const =0
Mass fraction difference between the interface and the field.
virtual tmp< volScalarField > D (const word &speciesName) const =0
Mass diffusivity.
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const =0
Latent heat.
virtual void addMDotL (const volScalarField &K, const volScalarField &Tf, volScalarField &mDotL, volScalarField &mDotLPrime) const =0
Add latent heat flow rate to total.
TypeName ("interfaceCompositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interfaceCompositionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
interfaceCompositionModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~interfaceCompositionModel ()=default
Destructor.
const word transferSpecie () const
Return the transferring species name.
const phasePair & pair () const
Return pair.
virtual tmp< volScalarField > Yf (const word &speciesName, const volScalarField &Tf) const =0
Interface mass fraction.
virtual tmp< volScalarField > dY (const word &speciesName, const volScalarField &Tf) const =0
Mass fraction difference between the interface and the field.
virtual tmp< volScalarField > D (const word &speciesName) const =0
Mass diffusivity.
virtual tmp< volScalarField > L (const word &speciesName, const volScalarField &Tf) const =0
Latent heat (delta Hc)
virtual tmp< volScalarField > Kexp (label modelVariable, const volScalarField &field)=0
Explicit mass transfer coefficient.
virtual const dimensionedScalar & Tactivate () const =0
Reference value.
const word variable () const
Returns the variable on which the model is based.
Static Public Member Functions
static autoPtr
< interfaceCompositionModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr
< interfaceCompositionModel > New (const dictionary &dict, const phasePair &pair)
Public Attributes
modelVariable modelVariable_
Enumeration for model variables.
Static Public Attributes
static const Enum< modelVariable > modelVariableNames
Protected Attributes
const phasePair & pair_
Phase pair.
const hashedWordList speciesNames_
Names of the transferring species.
word speciesName_
Names of the transferring specie.
const fvMesh & mesh_
Reference to mesh.
Detailed Description
Generic base class for interface composition models. These models describe the composition in phase 1 of the supplied pair at the interface with phase 2.
Generic base class for interface models. Mass transer models are interface models between two thermos. Abstract class for mass transfer functions.
Source files
interfaceCompositionModel.H
interfaceCompositionModel.C
Source files
interfaceCompositionModel.H
interfaceCompositionModel.C
Definition at line 54 of file interfaceCompositionModel.H.
Member Enumeration Documentation
enum modelVariable
Enumeration for variable based mass transfer models.
Enumerator
T
P
Y
Definition at line 63 of file interfaceCompositionModel.H.
Constructor & Destructor Documentation
interfaceCompositionModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
Definition at line 37 of file interfaceCompositionModel.C.
virtual ~interfaceCompositionModel () virtual default
Destructor.
interfaceCompositionModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
virtual ~interfaceCompositionModel () virtual default
Destructor.
Member Function Documentation
TypeName ("interfaceCompositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , interfaceCompositionModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::interfaceCompositionModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 30 of file newInterfaceCompositionModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, interfaceCompositionModel::pair(), phasePair::phase1(), phasePair::phase2(), and phaseModel::thermo().
Referenced by NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid(), and Raoult< Thermo, OtherThermo >::Raoult().
virtual void update (const volScalarField & Tf) pure virtual
Update the composition.
Implemented in NonRandomTwoLiquid< Thermo, OtherThermo >, Saturated< Thermo, OtherThermo >, Raoult< Thermo, OtherThermo >, and Henry< Thermo, OtherThermo >.
const Foam::hashedWordList & species () const
Return the transferring species names.
Definition at line 49 of file interfaceCompositionModel.C.
Referenced by InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem().
bool transports (word & speciesName) const
Returns whether the species is transported by the model and provides the name of the diffused species.
Definition at line 55 of file interfaceCompositionModel.C.
References interfaceCompositionModel::speciesNames_.
virtual tmp<volScalarField> Yf (const word & speciesName, const volScalarField & Tf) const pure virtual
Interface mass fraction.
Implemented in NonRandomTwoLiquid< Thermo, OtherThermo >, InterfaceCompositionModel< Thermo, OtherThermo >, Saturated< Thermo, OtherThermo >, Raoult< Thermo, OtherThermo >, and Henry< Thermo, OtherThermo >.
virtual tmp<volScalarField> YfPrime (const word & speciesName, const volScalarField & Tf) const pure virtual
The interface mass fraction derivative w.r.t. temperature.
Implemented in NonRandomTwoLiquid< Thermo, OtherThermo >, Saturated< Thermo, OtherThermo >, Raoult< Thermo, OtherThermo >, and Henry< Thermo, OtherThermo >.
virtual tmp<volScalarField> dY (const word & speciesName, const volScalarField & Tf) const pure virtual
Mass fraction difference between the interface and the field.
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
virtual tmp<volScalarField> D (const word & speciesName) const pure virtual
Mass diffusivity.
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
virtual tmp<volScalarField> L (const word & speciesName, const volScalarField & Tf) const pure virtual
Latent heat.
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
virtual void addMDotL (const volScalarField & K, const volScalarField & Tf, volScalarField & mDotL, volScalarField & mDotLPrime) const pure virtual
Add latent heat flow rate to total.
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >.
TypeName ("interfaceCompositionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , interfaceCompositionModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
static autoPtr<interfaceCompositionModel> New (const dictionary & dict, const phasePair & pair) static
const word transferSpecie () const
Return the transferring species name.
const phasePair& pair () const
Return pair.
Referenced by interfaceCompositionModel::New(), NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid(), and Raoult< Thermo, OtherThermo >::Raoult().
virtual tmp<volScalarField> Yf (const word & speciesName, const volScalarField & Tf) const pure virtual
Interface mass fraction.
Implemented in NonRandomTwoLiquid< Thermo, OtherThermo >, InterfaceCompositionModel< Thermo, OtherThermo >, Saturated< Thermo, OtherThermo >, Raoult< Thermo, OtherThermo >, and Henry< Thermo, OtherThermo >.
virtual tmp<volScalarField> dY (const word & speciesName, const volScalarField & Tf) const pure virtual
Mass fraction difference between the interface and the field.
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
virtual tmp<volScalarField> D (const word & speciesName) const pure virtual
Mass diffusivity.
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
virtual tmp<volScalarField> L (const word & speciesName, const volScalarField & Tf) const pure virtual
Latent heat (delta Hc)
Implemented in InterfaceCompositionModel< Thermo, OtherThermo >, and InterfaceCompositionModel< Thermo, OtherThermo >.
virtual tmp<volScalarField> Kexp (label modelVariable, const volScalarField & field) pure virtual
Explicit mass transfer coefficient.
Implemented in kineticGasEvaporation< Thermo, OtherThermo >, and Lee< Thermo, OtherThermo >.
virtual const dimensionedScalar& Tactivate () const pure virtual
Reference value.
Implemented in kineticGasEvaporation< Thermo, OtherThermo >, and Lee< Thermo, OtherThermo >.
const word variable () const
Returns the variable on which the model is based.
Member Data Documentation
const phasePair & pair_ protected
Phase pair.
Definition at line 63 of file interfaceCompositionModel.H.
const hashedWordList speciesNames_ protected
Names of the transferring species.
Definition at line 68 of file interfaceCompositionModel.H.
Referenced by Henry< Thermo, OtherThermo >::Henry(), NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid(), Raoult< Thermo, OtherThermo >::Raoult(), and interfaceCompositionModel::transports().
const Enum<modelVariable> modelVariableNames static
Definition at line 70 of file interfaceCompositionModel.H.
modelVariable modelVariable_
Enumeration for model variables.
Definition at line 75 of file interfaceCompositionModel.H.
word speciesName_ protected
Names of the transferring specie.
Definition at line 90 of file interfaceCompositionModel.H.
const fvMesh& mesh_ protected
Reference to mesh.
Definition at line 95 of file interfaceCompositionModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialCompositionModels/interfaceCompositionModels/interfaceCompositionModel/interfaceCompositionModel.H
applications/solvers/multiphase/icoReactingMultiphaseInterFoam/massTransferModels/interfaceCompositionModel/interfaceCompositionModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialCompositionModels/interfaceCompositionModels/interfaceCompositionModel/interfaceCompositionModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialCompositionModels/interfaceCompositionModels/interfaceCompositionModel/newInterfaceCompositionModel.C