OpenFOAM: extendedUpwindCellToFaceStencil Class Reference
extendedUpwindCellToFaceStencil Class Reference
Creates upwind stencil by shifting a centred stencil to upwind and downwind faces and optionally removing all non-(up/down)wind faces ('pureUpwind').
Public Member Functions
extendedUpwindCellToFaceStencil (const cellToFaceStencil &, const bool pureUpwind, const scalar minOpposedness)
Construct from mesh and uncompacted centred face stencil.
extendedUpwindCellToFaceStencil (const cellToFaceStencil &)
Construct from mesh and uncompacted centred face stencil. Splits.
bool pureUpwind () const
const mapDistribute & ownMap () const
Return reference to the parallel distribution map.
const mapDistribute & neiMap () const
Return reference to the parallel distribution map.
const labelListList & ownStencil () const
Return reference to the stencil.
const labelListList & neiStencil () const
Return reference to the stencil.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &ownWeights, const List< List< scalar >> &neiWeights) const
Sum vol field contributions to create face values.
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > weightedSum (const surfaceScalarField &phi, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &ownWeights, const List< List< scalar >> &neiWeights) const
Public Member Functions inherited from extendedCellToFaceStencil
ClassName ("extendedCellToFaceStencil")
extendedCellToFaceStencil (const polyMesh &)
Construct from mesh.
template<class Type >
void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, List< List< Type >> &stencilFld)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Additional Inherited Members
Static Public Member Functions inherited from extendedCellToFaceStencil
template<class T >
static void collectData (const mapDistribute &map, const labelListList &stencil, const GeometricField< T, fvPatchField, volMesh > &fld, List< List< T >> &stencilFld)
Use map to get the data into stencil order.
template<class Type >
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< scalar >> &stencilWeights)
Sum vol field contributions to create face values.
Static Protected Member Functions inherited from extendedCellToFaceStencil
static void writeStencilStats (Ostream &os, const labelListList &stencil, const mapDistribute &map)
Write some statistics about stencil.
Protected Attributes inherited from extendedCellToFaceStencil
const polyMesh & mesh_
Detailed Description
Creates upwind stencil by shifting a centred stencil to upwind and downwind faces and optionally removing all non-(up/down)wind faces ('pureUpwind').
Note: the minOpposedness parameter is to decide which upwind and downwind faces to combine the stencils from. If myArea is the local area and upwindArea the area of the possible upwind candidate it will be included if (upwindArea & myArea)/magSqr(myArea) > minOpposedness so this includes both cosine and area. WIP.
Source files
extendedUpwindCellToFaceStencil.H
extendedUpwindCellToFaceStencil.C
extendedUpwindCellToFaceStencilTemplates.C
Definition at line 57 of file extendedUpwindCellToFaceStencil.H.
Constructor & Destructor Documentation
extendedUpwindCellToFaceStencil (const cellToFaceStencil & stencil, const bool pureUpwind, const scalar minOpposedness)
Construct from mesh and uncompacted centred face stencil.
Transports facestencil to create owner and neighbour versions. pureUpwind to remove any remaining downwind cells.
Definition at line 376 of file extendedUpwindCellToFaceStencil.C.
extendedUpwindCellToFaceStencil (const cellToFaceStencil & stencil)
Construct from mesh and uncompacted centred face stencil. Splits.
stencil into owner and neighbour (so always pure upwind)
Definition at line 520 of file extendedUpwindCellToFaceStencil.C.
Member Function Documentation
bool pureUpwind () const inline
Definition at line 169 of file extendedUpwindCellToFaceStencil.H.
const mapDistribute& ownMap () const inline
Return reference to the parallel distribution map.
Definition at line 177 of file extendedUpwindCellToFaceStencil.H.
Referenced by pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject(), and extendedUpwindCellToFaceStencil::weightedSum().
const mapDistribute& neiMap () const inline
Return reference to the parallel distribution map.
Definition at line 185 of file extendedUpwindCellToFaceStencil.H.
Referenced by extendedUpwindCellToFaceStencil::weightedSum().
const labelListList& ownStencil () const inline
Return reference to the stencil.
Definition at line 193 of file extendedUpwindCellToFaceStencil.H.
Referenced by pureUpwindCFCCellToFaceStencilObject::pureUpwindCFCCellToFaceStencilObject(), upwindCECCellToFaceStencilObject::upwindCECCellToFaceStencilObject(), upwindCFCCellToFaceStencilObject::upwindCFCCellToFaceStencilObject(), upwindCPCCellToFaceStencilObject::upwindCPCCellToFaceStencilObject(), upwindFECCellToFaceStencilObject::upwindFECCellToFaceStencilObject(), and extendedUpwindCellToFaceStencil::weightedSum().
const labelListList& neiStencil () const inline
Return reference to the stencil.
Definition at line 201 of file extendedUpwindCellToFaceStencil.H.
Referenced by extendedUpwindCellToFaceStencil::weightedSum().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > weightedSum (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar >> & ownWeights, const List< List< scalar >> & neiWeights) const
Sum vol field contributions to create face values.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > weightedSum (const surfaceScalarField & phi, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< scalar >> & ownWeights, const List< List< scalar >> & neiWeights) const
Definition at line 28 of file extendedUpwindCellToFaceStencilTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), extendedCellToFaceStencil::collectData(), fvsPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, i, j, mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), extendedUpwindCellToFaceStencil::neiMap(), extendedUpwindCellToFaceStencil::neiStencil(), primitiveMesh::nInternalFaces(), IOobject::NO_READ, IOobject::NO_WRITE, extendedUpwindCellToFaceStencil::ownMap(), extendedUpwindCellToFaceStencil::ownStencil(), fvsPatchField< Type >::patch(), GeometricField< Type, PatchField, GeoMesh >::ref(), fvMesh::time(), Time::timeName(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencil.C
src/finiteVolume/fvMesh/extendedStencil/cellToFace/extendedUpwindCellToFaceStencilTemplates.C