OpenFOAM: sixDoFRigidBodyMotion Class Reference
sixDoFRigidBodyMotion Class Reference
Six degree of freedom motion for a rigid body.
Public Member Functions
sixDoFRigidBodyMotion (const Time &)
Construct null.
sixDoFRigidBodyMotion (const dictionary &dict, const dictionary &stateDict, const Time &time)
Construct from constant and state dictionaries.
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion &)
Construct as copy.
~sixDoFRigidBodyMotion ()
Destructor.
scalar mass () const
Return the mass.
const diagTensor & momentOfInertia () const
Return the inertia tensor.
const sixDoFRigidBodyMotionState & state () const
Return the motion state.
const point & centreOfRotation () const
Return the current centre of rotation.
const point & initialCentreOfMass () const
Return the initial centre of mass.
point centreOfMass () const
Return the current centre of mass.
const tensor & orientation () const
Return the orientation tensor, Q.
vector omega () const
Return the angular velocity in the global frame.
const vector & v () const
Return the current velocity.
vector & v ()
Return non-const access to vector.
vector momentArm () const
Return the current momentArm.
bool report () const
Return the report Switch.
const Time & time () const
Return time.
void newTime ()
Store the motion state at the beginning of the time-step.
point & centreOfRotation ()
Return non-const access to the centre of rotation.
void addRestraints (const dictionary &dict)
Add restraints to the motion, public to allow external.
void addConstraints (const dictionary &dict)
Add restraints to the motion, public to allow external.
void update (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)
Symplectic integration of velocities, orientation and position.
void status () const
Report the status of the motion.
point velocity (const point &pt) const
Return the velocity of a position.
point transform (const point &initialPoints) const
Transform the given initial state point by the current motion.
tmp< pointField > transform (const pointField &initialPoints) const
Transform the given initial state pointField by the current.
tmp< pointField > transform (const pointField &initialPoints, const scalarField &scale) const
Transform the given initial state pointField by the current.
void write (Ostream &) const
Write.
bool read (const dictionary &dict)
Read coefficients dictionary and update system parameters,.
Friends
class sixDoFSolver
Detailed Description
Six degree of freedom motion for a rigid body.
Angular momentum stored in body fixed reference frame. Reference orientation of the body (where Q = I) must align with the cartesian axes such that the Inertia tensor is in principle component form. Can add restraints (e.g. a spring) and constraints (e.g. motion may only be on a plane).
The time-integrator for the motion is run-time selectable with options for symplectic (explicit), Crank-Nicolson and Newmark schemes.
Source files
sixDoFRigidBodyMotion.H
sixDoFRigidBodyMotionI.H
sixDoFRigidBodyMotion.C
sixDoFRigidBodyMotionIO.C
Definition at line 65 of file sixDoFRigidBodyMotion.H.
Constructor & Destructor Documentation
sixDoFRigidBodyMotion (const Time & time)
Construct null.
Definition at line 69 of file sixDoFRigidBodyMotion.C.
sixDoFRigidBodyMotion (const dictionary & dict, const dictionary & stateDict, const Time & time)
Construct from constant and state dictionaries.
Definition at line 91 of file sixDoFRigidBodyMotion.C.
sixDoFRigidBodyMotion (const sixDoFRigidBodyMotion & sDoFRBM)
Construct as copy.
Definition at line 155 of file sixDoFRigidBodyMotion.C.
~sixDoFRigidBodyMotion ()
Destructor.
Definition at line 180 of file sixDoFRigidBodyMotion.C.
Member Function Documentation
Foam::scalar mass () const inline
Return the mass.
Definition at line 204 of file sixDoFRigidBodyMotionI.H.
const Foam::diagTensor & momentOfInertia () const inline
Return the inertia tensor.
Definition at line 211 of file sixDoFRigidBodyMotionI.H.
const Foam::sixDoFRigidBodyMotionState & state () const inline
Return the motion state.
Definition at line 218 of file sixDoFRigidBodyMotionI.H.
const Foam::point & centreOfRotation () const inline
Return the current centre of rotation.
Definition at line 224 of file sixDoFRigidBodyMotionI.H.
const Foam::point & initialCentreOfMass () const inline
Return the initial centre of mass.
Definition at line 231 of file sixDoFRigidBodyMotionI.H.
Foam::point centreOfMass () const inline
Return the current centre of mass.
Definition at line 237 of file sixDoFRigidBodyMotionI.H.
const Foam::tensor & orientation () const inline
Return the orientation tensor, Q.
globalVector = Q & bodyLocalVector bodyLocalVector = Q.T() & globalVector
Definition at line 250 of file sixDoFRigidBodyMotionI.H.
Foam::vector omega () const inline
Return the angular velocity in the global frame.
Definition at line 256 of file sixDoFRigidBodyMotionI.H.
const Foam::vector & v () const inline
Return the current velocity.
Definition at line 136 of file sixDoFRigidBodyMotionI.H.
Foam::vector & v () inline
Return non-const access to vector.
Definition at line 178 of file sixDoFRigidBodyMotionI.H.
Foam::vector momentArm () const inline
Return the current momentArm.
Definition at line 243 of file sixDoFRigidBodyMotionI.H.
References Foam::transform().
bool report () const inline
Return the report Switch.
Definition at line 266 of file sixDoFRigidBodyMotionI.H.
const Foam::Time & time () const inline
Return time.
Definition at line 261 of file sixDoFRigidBodyMotionI.H.
References Foam::inv(), and Foam::constant::mathematical::pi().
void newTime () inline
Store the motion state at the beginning of the time-step.
Definition at line 272 of file sixDoFRigidBodyMotionI.H.
Foam::point & centreOfRotation () inline
Return non-const access to the centre of rotation.
Definition at line 278 of file sixDoFRigidBodyMotionI.H.
void addRestraints (const dictionary & dict)
Add restraints to the motion, public to allow external.
addition of restraints after construction
Definition at line 187 of file sixDoFRigidBodyMotion.C.
Referenced by sixDoFRigidBodyMotion::read().
void addConstraints (const dictionary & dict)
Add restraints to the motion, public to allow external.
addition of restraints after construction
Definition at line 221 of file sixDoFRigidBodyMotion.C.
void update (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0)
Symplectic integration of velocities, orientation and position.
Changes to Crank-Nicolson integration for subsequent iterations.
Definition at line 301 of file sixDoFRigidBodyMotion.C.
void status () const
Report the status of the motion.
Definition at line 323 of file sixDoFRigidBodyMotion.C.
Foam::point velocity (const point & pt) const inline
Return the velocity of a position.
Definition at line 285 of file sixDoFRigidBodyMotionI.H.
Foam::point transform (const point & initialPoints) const inline
Transform the given initial state point by the current motion.
state
Definition at line 294 of file sixDoFRigidBodyMotionI.H.
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints) const
Transform the given initial state pointField by the current.
motion state
Definition at line 336 of file sixDoFRigidBodyMotion.C.
Foam::tmp< Foam::pointField > transform (const pointField & initialPoints, const scalarField & scale) const
Transform the given initial state pointField by the current.
motion state scaled by the given scale
Definition at line 349 of file sixDoFRigidBodyMotion.C.
void write (Ostream & os) const
Write.
Definition at line 45 of file sixDoFRigidBodyMotionIO.C.
bool read (const dictionary & dict)
Read coefficients dictionary and update system parameters,.
constraints and restraints but not the current state
Definition at line 27 of file sixDoFRigidBodyMotionIO.C.
References sixDoFRigidBodyMotion::addRestraints(), dictionary::lookupOrDefault(), and dictionary::readEntry().
Friends And Related Function Documentation
friend class sixDoFSolver friend
Definition at line 67 of file sixDoFRigidBodyMotion.H.
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion.C
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionI.H
src/sixDoFRigidBodyMotion/sixDoFRigidBodyMotion/sixDoFRigidBodyMotionIO.C