OpenFOAM: pairPotential Class Reference
pairPotential Class Reference abstract
Public Member Functions
TypeName ("pairPotential")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pairPotential, dictionary,(const word &name, const dictionary &pairPotentialProperties),(name, pairPotentialProperties))
pairPotential (const word &name, const dictionary &pairPotentialProperties)
Construct from components.
virtual ~pairPotential ()=default
Destructor.
void setLookupTables ()
scalar rMin () const
scalar dr () const
scalar rCut () const
scalar rCutSqr () const
scalar energy (const scalar r) const
scalar force (const scalar r) const
List< Pair< scalar > > energyTable () const
List< Pair< scalar > > forceTable () const
bool writeTables () const
virtual scalar unscaledEnergy (const scalar r) const =0
scalar scaledEnergy (const scalar r) const
scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative=true) const
const dictionary & pairPotentialProperties () const
bool writeEnergyAndForceTables (Ostream &os) const
virtual bool read (const dictionary &pairPotentialProperties)=0
Read pairPotential dictionary.
Static Public Member Functions
static autoPtr< pairPotential > New (const word &name, const dictionary &pairPotentialProperties)
Return a reference to the selected viscosity model.
Protected Member Functions
void scaleEnergy (scalar &e, const scalar r) const
pairPotential (const pairPotential &)=delete
No copy construct.
void operator= (const pairPotential &)=delete
No copy assignment.
Protected Attributes
word name_
dictionary pairPotentialProperties_
scalar rCut_
scalar rCutSqr_
scalar rMin_
scalar dr_
List< scalar > forceLookup_
List< scalar > energyLookup_
energyScalingFunction * esfPtr_
bool writeTables_
Detailed Description
Source files
pairPotential.H
pairPotential.C
pairPotentialNew.C
Definition at line 56 of file pairPotential.H.
Constructor & Destructor Documentation
pairPotential (const pairPotential &) protected delete
No copy construct.
pairPotential (const word & name, const dictionary & pairPotentialProperties)
Construct from components.
Definition at line 52 of file pairPotential.C.
virtual ~pairPotential () virtual default
Destructor.
Member Function Documentation
void scaleEnergy (scalar & e, const scalar r) const protected
Definition at line 35 of file pairPotential.C.
void operator= (const pairPotential &) protected delete
No copy assignment.
TypeName ("pairPotential")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , pairPotential , dictionary , (const word &name, const dictionary &pairPotentialProperties) , (name, pairPotentialProperties))
Foam::autoPtr< Foam::pairPotential > New (const word & name, const dictionary & pairPotentialProperties) static
Return a reference to the selected viscosity model.
Definition at line 28 of file pairPotentialNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, Foam::name(), and Foam::nl.
void setLookupTables ()
Definition at line 72 of file pairPotential.C.
Foam::scalar rMin () const inline
Definition at line 23 of file pairPotentialI.H.
Foam::scalar dr () const inline
Definition at line 29 of file pairPotentialI.H.
References pairPotential::rMin_.
Foam::scalar rCut () const inline
Definition at line 35 of file pairPotentialI.H.
Foam::scalar rCutSqr () const inline
Definition at line 41 of file pairPotentialI.H.
Foam::scalar energy (const scalar r) const
Definition at line 126 of file pairPotential.C.
Foam::scalar force (const scalar r) const
Definition at line 89 of file pairPotential.C.
Foam::List< Foam::Pair< Foam::scalar > > energyTable () const
Definition at line 148 of file pairPotential.C.
Referenced by pairPotential::writeEnergyAndForceTables().
Foam::List< Foam::Pair< Foam::scalar > > forceTable () const
Definition at line 111 of file pairPotential.C.
Referenced by pairPotential::writeEnergyAndForceTables().
bool writeTables () const inline
Definition at line 47 of file pairPotentialI.H.
virtual scalar unscaledEnergy (const scalar r) const pure virtual
Implemented in maitlandSmith, azizChen, dampedCoulomb, exponentialRepulsion, lennardJones, coulomb, and noInteraction.
Foam::scalar scaledEnergy (const scalar r) const
Definition at line 163 of file pairPotential.C.
Foam::scalar energyDerivative (const scalar r, const bool scaledEnergyDerivative = true) const
Definition at line 174 of file pairPotential.C.
const dictionary& pairPotentialProperties () const inline
Definition at line 180 of file pairPotential.H.
bool writeEnergyAndForceTables (Ostream & os) const
Definition at line 24 of file pairPotentialIO.C.
References Foam::constant::electromagnetic::e, Foam::endl(), pairPotential::energyTable(), UList< T >::first(), forAll, pairPotential::forceTable(), IOstream::good(), Foam::Info, pairPotential::name_, Foam::nl, and token::SPACE.
bool read (const dictionary & pairPotentialProperties) pure virtual
Read pairPotential dictionary.
Implemented in maitlandSmith, azizChen, dampedCoulomb, exponentialRepulsion, lennardJones, coulomb, and noInteraction.
Definition at line 217 of file pairPotential.C.
Member Data Documentation
word name_ protected
Definition at line 63 of file pairPotential.H.
Referenced by pairPotential::writeEnergyAndForceTables().
dictionary pairPotentialProperties_ protected
Definition at line 64 of file pairPotential.H.
scalar rCut_ protected
Definition at line 66 of file pairPotential.H.
scalar rCutSqr_ protected
Definition at line 67 of file pairPotential.H.
scalar rMin_ protected
Definition at line 69 of file pairPotential.H.
Referenced by pairPotential::dr().
scalar dr_ protected
Definition at line 70 of file pairPotential.H.
List<scalar> forceLookup_ protected
Definition at line 72 of file pairPotential.H.
List<scalar> energyLookup_ protected
Definition at line 73 of file pairPotential.H.
energyScalingFunction* esfPtr_ mutable protected
Definition at line 75 of file pairPotential.H.
bool writeTables_ protected
Definition at line 77 of file pairPotential.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotential.H
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotential.C
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotentialI.H
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotentialIO.C
src/lagrangian/molecularDynamics/potential/pairPotential/basic/pairPotentialNew.C