OpenFOAM: tmp< T > Class Template Reference
tmp< T > Class Template Reference
A class for managing temporary objects.
Public Types
typedef T element_type
Type of object being managed or referenced.
typedef T * pointer
Pointer to type of object being managed or referenced.
typedef Foam::refCount refCount
Reference counter class.
Public Member Functions
constexpr tmp () noexcept
Construct with no managed pointer.
constexpr tmp (std::nullptr_t) noexcept
Construct with no managed pointer.
tmp (T *p)
Construct, taking ownership of the pointer.
tmp (const T &obj) noexcept
Construct for a const reference to an object.
tmp (tmp< T > &&t) noexcept
Move construct, transferring ownership.
tmp (const tmp< T > &&t) noexcept
Move construct, transferring ownership.
tmp (const tmp< T > &t)
Copy construct, incrementing ref-count of managed pointer.
tmp (const tmp< T > &t, bool reuse)
Copy construct. Optionally reusing ref-counted pointer.
~tmp ()
Destructor: deletes managed pointer when the ref-count is 0.
bool isTmp () const noexcept
True if this is a managed pointer (not a const reference)
bool empty () const noexcept
True if this is a non-null managed pointer.
bool valid () const noexcept
True if this is a non-null managed pointer, or is a const object reference.
bool movable () const noexcept
True if this is a non-null managed pointer with a unique ref-count.
word typeName () const
Return type-name of the tmp, constructed from type-name of T.
T * get () noexcept
Return pointer without nullptr checking.
const T * get () const noexcept
Return const pointer without nullptr checking.
const T & cref () const
Return the const object reference or a const reference to the contents of a non-null managed pointer.
T & ref () const
Return non-const reference to the contents of a non-null managed pointer.
T & constCast () const
Non-const dereference, even if the object is const.
T * ptr () const
Return managed pointer for reuse, or clone() the const object reference.
void clear () const noexcept
If object pointer points to valid object: delete object and set pointer to nullptr.
void reset () noexcept
Release ownership of managed temporary object.
void reset (T *p) noexcept
Delete managed temporary object and set to new given pointer.
void reset (tmp< T > &&other) noexcept
Clear existing and transfer ownership.
void cref (const T &obj) noexcept
Delete managed temporary object and set to const reference.
void swap (tmp< T > &other) noexcept
Swaps the managed object with other.
const T & operator() () const
Return const reference to the object.
operator const T & () const
Cast to underlying data type, using the cref() method.
const T * operator-> () const
Dereferences (const) pointer to the managed object.
T * operator-> ()
Dereferences (non-const) pointer to the managed object.
operator bool () const noexcept
Is non-null managed pointer or const object reference : valid()
void operator= (T *p)
Take ownership of the pointer.
void operator= (const tmp< T > &t)
Transfer ownership of the managed pointer.
void operator= (tmp< T > &&other) noexcept
Clear existing and transfer ownership.
void operator= (std::nullptr_t)=delete
No assignment from literal nullptr.
template<class... Args>
Foam::tmp< T > New (Args &&...args)
template<class U , class... Args>
Foam::tmp< T > NewFrom (Args &&...args)
Static Public Member Functions
template<class... Args>
static tmp< T > New (Args &&...args)
Construct tmp of T with forwarding arguments.
template<class U , class... Args>
static tmp< T > NewFrom (Args &&...args)
Construct tmp from derived type with forwarding arguments.
Detailed Description
template<class T>
class Foam::tmp< T >
A class for managing temporary objects.
This is a combination of std::shared_ptr (with intrusive ref-counting) and a shared_ptr without ref-counting and null deleter. This allows the tmp to double as a pointer management and an indirect pointer to externally allocated objects.
Source files
tmp.H
tmpI.H
See Also
Foam::autoPtr Foam::refCount
Definition at line 55 of file PtrList.H.
Member Typedef Documentation
typedef T element_type
Type of object being managed or referenced.
Definition at line 98 of file tmp.H.
typedef T* pointer
Pointer to type of object being managed or referenced.
Definition at line 103 of file tmp.H.
typedef Foam::refCount refCount
Reference counter class.
Definition at line 109 of file tmp.H.
Constructor & Destructor Documentation
constexpr tmp () inline noexcept
Construct with no managed pointer.
Definition at line 63 of file tmpI.H.
constexpr tmp (std::nullptr_t) inline noexcept
Construct with no managed pointer.
Definition at line 71 of file tmpI.H.
tmp (T * p) inline explicit
Construct, taking ownership of the pointer.
Definition at line 79 of file tmpI.H.
tmp (const T & obj) inline noexcept
Construct for a const reference to an object.
Definition at line 95 of file tmpI.H.
tmp (tmp< T > && t) inline noexcept
Move construct, transferring ownership.
Does not affect ref-count
Definition at line 103 of file tmpI.H.
tmp (const tmp< T > && t) inline noexcept
Move construct, transferring ownership.
Does not affect ref-count
Note
Non-standard definition - should be non-const
Definition at line 114 of file tmpI.H.
tmp (const tmp< T > & t) inline
Copy construct, incrementing ref-count of managed pointer.
Note
Non-standard definition - should be non-const
Definition at line 125 of file tmpI.H.
tmp (const tmp< T > & t, bool reuse) inline
Copy construct. Optionally reusing ref-counted pointer.
Definition at line 147 of file tmpI.H.
~tmp () inline
Destructor: deletes managed pointer when the ref-count is 0.
Definition at line 176 of file tmpI.H.
Member Function Documentation
static tmp<T> New (Args &&... args) inline static
Construct tmp of T with forwarding arguments.
Parameters
args list of arguments with which an instance of T will be constructed.
Note
Similar to std::make_shared, but the overload for array types is not disabled.
Referenced by isoSurface::adaptPatchFields(), boundaryAdjointContribution::adjointTMVariable2Source(), searchablePlate::boundingSpheres(), searchableCylinder::boundingSpheres(), searchableCone::boundingSpheres(), nutLowReWallFunctionFvPatchScalarField::calcNut(), adjointRASModel::diffusionCoeffVar2(), wedgeFvPatchField< Type >::evaluate(), parseDriver::field_faceArea(), parseDriver::field_rand(), noiseFFT::frequencies(), Foam::getField(), Foam::getZeroGradField(), Foam::inv(), cylindrical::localToGlobal(), transparent::rDiff(), opaqueDiffusive::rDiff(), lookup::rDiff(), reader::readField(), coordinateSystem::rotationsImpl(), transparent::rSpec(), opaqueDiffusive::rSpec(), lookup::rSpec(), adjointRASModel::setChangedPrimalSolution(), displacementMeshMoverMotionSolver::solve(), constantTransmissivity::t(), multiBandTransmissivity::t(), opaqueDiffusive::t(), transparent::t(), opaqueReflective::t(), boundaryAdjointContribution::TMVariable1(), boundaryAdjointContribution::TMVariable1Diffusion(), boundaryAdjointContribution::TMVariable2(), boundaryAdjointContribution::TMVariable2Diffusion(), Foam::transformFieldMask< tensor >(), and constantAlphaContactAngleFvPatchScalarField::write().
static tmp<T> NewFrom (Args &&... args) inline static
Construct tmp from derived type with forwarding arguments.
Parameters
args list of arguments with which an instance of U will be constructed.
Note
Similar to New but for derived types
bool isTmp () const inline noexcept
True if this is a managed pointer (not a const reference)
Definition at line 185 of file tmpI.H.
Referenced by Foam::constrainHbyA().
bool empty () const inline noexcept
True if this is a non-null managed pointer.
Definition at line 192 of file tmpI.H.
bool valid () const inline noexcept
True if this is a non-null managed pointer, or is a const object reference.
Definition at line 199 of file tmpI.H.
Referenced by MovingPhaseModel< BasePhaseModel >::divU(), parseDriver::getField(), parseDriver::getVariableIfAvailable(), Foam::writeAreaField(), Foam::writeDimField(), Foam::writePointField(), and Foam::writeVolField().
bool movable () const inline noexcept
True if this is a non-null managed pointer with a unique ref-count.
Definition at line 206 of file tmpI.H.
Foam::word typeName () const inline
Return type-name of the tmp, constructed from type-name of T.
Definition at line 213 of file tmpI.H.
T * get () inline noexcept
Return pointer without nullptr checking.
Definition at line 220 of file tmpI.H.
References Foam::name(), and Foam::T().
const T * get () const inline noexcept
Return const pointer without nullptr checking.
Definition at line 227 of file tmpI.H.
const T & cref () const inline
Return the const object reference or a const reference to the contents of a non-null managed pointer.
Fatal for a null managed pointer
Definition at line 234 of file tmpI.H.
T & ref () const inline
Return non-const reference to the contents of a non-null managed pointer.
Fatal for a null managed pointer or if the object is const.
Definition at line 251 of file tmpI.H.
Referenced by Foam::fac::average(), Foam::fvc::average(), add::calcFieldType(), subtract::calcFieldType(), cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), Foam::constrainHbyA(), outletStabilised< Type >::corrected(), correctedLnGrad< Type >::correction(), fourthLnGrad< Type >::correction(), pointLinear< Type >::correction(), deferredCorrection< Type >::correction(), cellCellStencil::createField(), Foam::fvc::curl(), fvFieldDecomposer::decomposeField(), lumpedPointMovement::displacePoints(), Foam::fac::div(), PatchTools::edgeNormals(), EulerFaDdtScheme< Type >::facDdt(), backwardFaDdtScheme< Type >::facDdt(), PatchToPatchInterpolation< FromPatch, ToPatch >::faceInterpolate(), PrimitivePatchInterpolation< Patch >::faceToPointInterpolate(), gaussLaplacianScheme< Type >::famLaplacian(), skewCorrectedSnGrad< Type >::fullGradCorrection(), correctedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), cylindrical::globalToLocal(), Foam::fac::grad(), lduMatrix::H(), heheuPsiThermo< BasicPsiThermo, MixtureType >::heu(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::iDmdt(), isoSurfaceTopo::interpolate(), pointToPointPlanarInterpolation::interpolate(), edgeInterpolationScheme< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), Foam::levelSetFraction(), lnGradScheme< Type >::lnGrad(), Foam::fvc::magSqrGradGrad(), volSurfaceMapping::mapToSurface(), Foam::fac::ndiv(), faPatchField< Type >::New(), fvPatchField< Type >::New(), Foam::fac::ngrad(), faPatch::patchInternalField(), fvPatch::patchInternalField(), AMIInterpolation< SourcePatch, TargetPatch >::patchMagSf(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), PatchTools::pointNormals(), reader::readField(), mappedPatchBase::readListOrField(), patchProbes::sample(), mappedPatchBase::samplePoints(), skewCorrected< Type >::skewCorrection(), snGradScheme< Type >::snGrad(), optionList::source(), Foam::fam::Su(), coalCloudList::UTrans(), limitedSurfaceInterpolationScheme< Type >::weights(), and MRFZoneList::zeroFilter().
T & constCast () const inline
Non-const dereference, even if the object is const.
This is similar to ref(), but applies a const_cast to access const objects. Fatal for a null managed pointer.
Definition at line 275 of file tmpI.H.
T * ptr () const inline
Return managed pointer for reuse, or clone() the const object reference.
Definition at line 289 of file tmpI.H.
Referenced by PtrDynList< T, SizeMin >::append(), PtrList< T >::release(), and PtrList< T >::set().
void clear () const inline noexcept
If object pointer points to valid object: delete object and set pointer to nullptr.
Definition at line 318 of file tmpI.H.
Referenced by if(), edgeInterpolationScheme< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), boundBox::overlaps(), PatchToPatchInterpolation< FromPatch, ToPatch >::pointInterpolate(), realizableKE< BasicTurbulenceModel >::rCmu(), Foam::writeAreaField(), Foam::writeDimField(), Foam::writePointField(), and Foam::writeVolField().
void reset () inline noexcept
Release ownership of managed temporary object.
After this call no object is managed.
Definition at line 336 of file tmpI.H.
void reset (T * p) inline noexcept
Delete managed temporary object and set to new given pointer.
Definition at line 345 of file tmpI.H.
void reset (tmp< T > && other) inline noexcept
Clear existing and transfer ownership.
Definition at line 354 of file tmpI.H.
void cref (const T & obj) inline noexcept
Delete managed temporary object and set to const reference.
Definition at line 371 of file tmpI.H.
void swap (tmp< T > & other) inline noexcept
Swaps the managed object with other.
Definition at line 380 of file tmpI.H.
const T & operator() () const inline
Return const reference to the object.
Identical to cref() method.
Definition at line 401 of file tmpI.H.
operator const T & () const inline
Cast to underlying data type, using the cref() method.
Definition at line 408 of file tmpI.H.
const T * operator-> () const inline
Dereferences (const) pointer to the managed object.
Fatal for a null managed pointer.
Definition at line 415 of file tmpI.H.
T * operator-> () inline
Dereferences (non-const) pointer to the managed object.
Fatal for a null managed pointer or if the object is const.
Definition at line 429 of file tmpI.H.
operator bool () const inline explicit noexcept
Is non-null managed pointer or const object reference : valid()
Definition at line 452 of file tmpI.H.
void operator= (T * p) inline
Take ownership of the pointer.
Fatal for a null pointer, or when the pointer is non-unique.
Definition at line 459 of file tmpI.H.
void operator= (const tmp< T > & t) inline
Transfer ownership of the managed pointer.
Fatal for a null managed pointer or if the object is const.
Definition at line 483 of file tmpI.H.
void operator= (tmp< T > && other) inline noexcept
Clear existing and transfer ownership.
Definition at line 516 of file tmpI.H.
void operator= (std::nullptr_t) delete
No assignment from literal nullptr.
Consistent with run-time check for nullptr on assignment.
Foam::tmp<T> New (Args &&... args) inline
Definition at line 46 of file tmpI.H.
Foam::tmp<T> NewFrom (Args &&... args) inline
Definition at line 54 of file tmpI.H.
References args, and T.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/PtrLists/PtrList/PtrList.H
src/OpenFOAM/memory/tmp/tmp.H
src/OpenFOAM/memory/tmp/tmpI.H