OpenFOAM: parseDriver Class Reference
parseDriver Class Reference
Driver for patch expressions.
Public Member Functions
ClassName ("patchExpr::driver")
parseDriver (const fvPatch &p)
Construct for specified patch.
parseDriver (const fvPatch &p, const dictionary &dict)
Construct for specified patch with given dictionary.
parseDriver (const fvPatch &p, const parseDriver &driver_)
Construct for specified patch with copy of driver context.
parseDriver (const word &patchName, const fvMesh &mesh)
Construct with patchName for the given mesh.
parseDriver (const dictionary &dict, const fvMesh &mesh)
Construct with "patch" (mandatory) and "region" (optional) specified in dictionary.
virtual autoPtr
< expressions::fvExprDriver > clone () const
Clone.
virtual ~parseDriver ()=default
Destructor.
virtual const fvMesh & mesh () const
The mesh we are attached to.
virtual label size () const
The underlying field size for the expression.
virtual label pointSize () const
The underlying point field size for the expression.
label size (const FieldAssociation geoType) const
Field size associated with different geometric field types.
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)
Execute the parser.
template<class Type >
void setResult (Field< Type > *ptr, bool pointVal=false)
Set result.
template<class Type >
tmp< Field< Type > > getVariableIfAvailable (const word &fldName) const
Retrieve variable as field if possible.
template<class Type >
tmp< Field< Type > > getVolField (const word &fldName)
Retrieve field (vol field)
template<class Type >
tmp< Field< Type > > getSurfaceField (const word &fldName)
Retrieve field (surface field)
template<class Type >
tmp< Field< Type > > getPointField (const word &fldName)
Retrieve field (point field)
template<class Type >
tmp< Field< Type > > getField (const word &fldName)
Return named field.
template<class Type >
tmp< Field< Type > > faceToPoint (const Field< Type > &field) const
Interpolate face to point.
template<class Type >
tmp< Field< Type > > pointToFace (const Field< Type > &field) const
Interpolate point to face values.
template<class Type >
Type areaAverage (const Field< Type > &fld) const
The area-weighted average of a field.
template<class Type >
Type areaSum (const Field< Type > &fld) const
The area-weighted sum of a field.
tmp< scalarField > field_faceArea () const
The face area magnitudes [magSf] - (swak = area)
tmp< vectorField > field_faceCentre () const
The face centres - (swak = pos)
tmp< vectorField > field_areaNormal () const
The face areas with their vector direction [Sf] - (swak = face)
tmp< vectorField > field_pointField () const
The patch point locations - (swak = pts)
tmp< scalarField > field_rand (label seed=0, bool gaussian=false) const
A uniform random field.
tmp< scalarField > field_randGaussian (label seed=0) const
A Gaussian random field.
template<>
tmp< Field< bool > > getSurfaceField (const word &fldName)
Retrieve field (surface field: bool)
template<>
tmp< Field< bool > > getPointField (const word &fldName)
Retrieve field (point field: bool)
template<>
Foam::tmp< Foam::Field< bool > > getSurfaceField (const word &name)
template<>
Foam::tmp< Foam::Field< bool > > getPointField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getVariableIfAvailable (const word &name) const
template<class Type >
Foam::tmp< Foam::Field< Type > > getVolField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getSurfaceField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getPointField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > getField (const word &name)
template<class Type >
Foam::tmp< Foam::Field< Type > > faceToPoint (const Field< Type > &field) const
template<class Type >
Foam::tmp< Foam::Field< Type > > pointToFace (const Field< Type > &field) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > getVolField (const word &fldName, bool getOldTime)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > getSurfaceField (const word &fldName, bool getOldTime)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::pointPatchField,
Foam::pointMesh > > getPointField (const word &fldName, bool getOldTime)
template<class Type >
Foam::tmp< Foam::Field< Type > > getField (const word &name) const
Public Member Functions inherited from genericRagelLemonDriver
genericRagelLemonDriver ()
Construct null.
genericRagelLemonDriver (const genericRagelLemonDriver &rhs)=default
Copy construct.
genericRagelLemonDriver (genericRagelLemonDriver &&rhs)=default
Move construct.
virtual ~genericRagelLemonDriver ()=default
Destructor.
void clear ()
Reset references.
const std::string & content () const
Get reference to the input buffer content.
void content (const std::string &s, size_t pos=0, size_t len=std::string::npos)
Set reference to the input buffer content, which acts like a std::string_view.
std::string::const_iterator cbegin () const
Iterator to begin of content (sub)string.
std::string::const_iterator cend () const
Iterator to end of content (sub)string.
size_t parsePosition () const
The relative parse position with the content (sub)string.
size_t & parsePosition ()
The relative parse position with the content (sub)string.
Ostream & printBuffer (Ostream &os) const
Output the input buffer string content.
void reportFatal (const std::string &msg) const
Report FatalError.
void reportFatal (const std::string &msg, size_t pos) const
Report FatalError at parser position.
Public Member Functions inherited from fvExprDriver
TypeName ("fvExprDriver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvExprDriver, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
declareRunTimeSelectionTable (autoPtr, fvExprDriver, idName,(const word &ident, const fvMesh &mesh),(ident, mesh))
fvExprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
fvExprDriver (const fvExprDriver &)
Copy construct.
fvExprDriver (const dictionary &dict)
Construct from a dictionary.
virtual ~fvExprDriver ()
Destructor.
const Time & runTime () const
The Time associated with the mesh.
virtual word timeName () const
The current time name.
virtual scalar timeValue () const
The current time value.
bool cacheSets () const
Status of cache-sets (static variable)
virtual void clearVariables ()
Clear temporary variables and resets from expression strings.
virtual bool hasVariable (const word &name) const
True if named variable exists.
virtual const exprResult & variable (const word &name) const
Return const-access to the named variable.
template<class Type >
bool isVariableOrField (const word &name, bool isPointVal=false, label expectSize=-1) const
Test for existence of a local/global variable or a field.
template<class Type >
tmp< Field< Type > > getVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
word getFieldClassName (const word &name) const
Lookup the field class name (memory or read from disk)
topoSetSource::sourceType topoSetType (const word &name) const
Return cell/face/point set type or unknown.
topoSetSource::sourceType topoZoneType (const word &name) const
Return cell/face/point zone type or unknown.
topoSetSource::sourceType topoSourceType (const word &name) const
Return cell/face/point zone/set type or unknown.
labelList getTopoSetLabels (const word &name, enum topoSetSource::sourceType setType) const
Read and return labels associated with the topo set.
bool isCellZone (const word &name) const
Test if name is a known cellZone.
bool isFaceZone (const word &name) const
Test if name is a known faceZone.
bool isPointZone (const word &name) const
Test if name is a known pointZone.
bool isCellSet (const word &name) const
Test if name is a known cellSet.
bool isFaceSet (const word &name) const
Test if name is a known faceSet.
bool isPointSet (const word &name) const
Test if name is a known pointSet.
virtual void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
Evaluate an expression on a remote and save as the specified named variable.
template<class Type >
bool isVariable (const word &name, bool isPointVal=false, label expectSize=-1) const
Test existence of a local/global variable.
template<class Type >
bool foundField (const word &name) const
Test if specified field can be found in memory or disk.
word getTypeOfField (const word &fieldName) const
Read the IOobject for fieldName and return its headerClassName.
virtual bool readDict (const dictionary &dict)
Read variables, tables etc.
Ostream & writeCommon (Ostream &os, bool debug=false) const
Write "variables", "storedVariables", "delayedVariables", "globalScopes" if they are present.
void createWriterAndRead (const word &name)
Create a writer for this object.
void tryWrite () const
Write data if apropriate Should enable exact restarts.
template<class GeomField >
Foam::tmp< GeomField > getOrReadField (const word &name, bool mandatory, bool getOldTime)
template<class GeomField >
Foam::tmp< GeomField > getOrReadPointField (const word &name, bool mandatory, bool getOldTime)
template<class GeomField , class Mesh >
Foam::tmp< GeomField > readAndRegister (const word &name, const Mesh &meshRef)
template<class Type >
Foam::tmp< Foam::Field< Type > > getVariable (const word &name, label expectedSize, const bool mandatory) const
template<class GeomField , class Mesh >
Foam::tmp< GeomField > getOrReadFieldImpl (const word &name, const Mesh &meshRef, bool mandatory, bool getOldTime)
template<class T >
Foam::autoPtr< T > getTopoSet (const fvMesh &mesh, const word &name, SetOrigin &origin) const
Public Member Functions inherited from exprDriver
TypeName ("exprDriver")
Runtime type information.
exprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
exprDriver (const exprDriver &)
Copy construct.
exprDriver (const dictionary &dict)
Construct from a dictionary.
virtual ~exprDriver ()=default
Destructor.
const dictionary & dict () const
The dictionary with all input data/specification.
virtual const exprResult & result () const
Const access to expression result.
virtual exprResult & result ()
Non-const access to expression result.
void clearResult ()
Clear the result.
template<class Type >
tmp< Field< Type > > getResult (bool isPointVal=false)
Return the expression result as a tmp field.
virtual word getResultType () const
The result type as word - same as result().valueType()
int stashedTokenId () const
Get "look-behind" parsing context (internal bookkeeping)
int resetStashedTokenId (int tokenId=0) const
Reset "look-behind" parsing context (mutable operation)
void setDebugging (bool scannerDebug, bool parserDebug)
Set the scanner/parser debug.
void setDebugging (const exprDriver &rhs)
Set the scanner/parser debug to match the input.
void setSearchBehaviour (bool cacheReadFields, bool searchInMemory, bool searchFiles)
Set search behaviour.
void setSearchBehaviour (const exprDriver &rhs)
Set search behaviour to be identical to rhs.
bool debugScanner () const
Read access to scanner debug.
bool debugParser () const
Read access to parser debug.
bool cacheReadFields () const
bool searchInMemory () const
bool searchFiles () const
bool prevIterIsOldTime () const
void addVariables (const expressions::exprString &expr, bool clear=true)
Add/set string expressions for variables.
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
Add/set string expressions for variables.
template<class T >
void addUniformVariable (const word &name, const T &val)
Add a uniform variable from an outside caller.
template<class T >
bool isLocalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a local variable.
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return the field.
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return a single value.
void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
Return a new field with the size()
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
Return a new field with the pointSize()
expressions::exprString readExpression (const word &name)
Read an expression string (with the current dictionary) and do substitutions.
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Read "variables" and assigns to the list of expression strings.
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
Write "variables".
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Protected Member Functions
parseDriver (const parseDriver &)=delete
void operator= (const parseDriver &)=delete
Protected Member Functions inherited from fvExprDriver
void setGlobalScopes (const wordUList &scopes)
Define scopes for global variables.
virtual exprResult & variable (const word &name)
Non-const access to the named variable (sub-classes only)
template<class T >
bool isGlobalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a global variable.
const exprResult & lookupGlobal (const word &name) const
Return the global variable if available or a null result.
template<class Type >
bool isField (const word &name, bool isPointVal=false, label expectSize=-1) const
Test for the existence of a mesh field.
template<class GeomField >
tmp< GeomField > getOrReadField (const word &name, bool mandatory=true, bool getOldTime=false)
Retrieve field from memory or disk.
template<class GeomField >
tmp< GeomField > getOrReadPointField (const word &name, bool mandatory=true, bool getOldTime=false)
Retrieve point field from memory or disk.
template<class GeomField , class MeshRef >
tmp< GeomField > getOrReadFieldImpl (const word &name, const MeshRef &meshRef, bool mandatory=true, bool getOldTime=false)
Retrieve field from memory or disk (implementation)
template<class GeomField , class MeshRef >
tmp< GeomField > readAndRegister (const word &name, const MeshRef &meshRef)
Helper function for getOrReadField.
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Create a random field.
template<class T >
autoPtr< T > getTopoSet (const fvMesh &mesh, const word &setName, SetOrigin &origin) const
Get topoSet.
template<class T >
bool updateSet (autoPtr< T > &setPtr, const word &setName, SetOrigin origin) const
Update topoSet.
virtual void updateSpecialVariables (bool force=false)
Examine current variable values and update stored variables.
virtual bool hasDataToWrite () const
Do we need a data file to be written.
virtual void prepareData (dictionary &dict) const
Prepare/update special variables and add to dictionary, normally via the reader/writer.
virtual void getData (const dictionary &dict)
Read data from dictionary, normally via the reader/writer.
Protected Member Functions inherited from exprDriver
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Fill a random field.
virtual bool update ()
Update things.
virtual exprResult getRemoteResult (const exprDriver &other) const
Get the result from another driver.
void operator= (const exprDriver &)=delete
No copy assignment.
Protected Attributes
const fvPatch & patch_
The referenced patch.
Protected Attributes inherited from genericRagelLemonDriver
std::reference_wrapper< const
std::string > content_
Reference to the input string.
size_t start_
Start position within input string.
size_t length_
Length of input (sub)string.
size_t position_
The last known parser position.
Protected Attributes inherited from exprDriver
const dictionary & dict_
The dictionary with all input data/specification.
exprResult result_
The result.
List< expressions::exprString > variableStrings_
Variable definitions, as read from a dictionary.
HashTable< exprResult > variables_
The variables table.
int stashedTokenId_
Internal bookkeeping as "look-behind" parsing context.
bool debugScanner_
Request debugging for scanner.
bool debugParser_
Request debugging for parser.
bool allowShadowing_
Allow variable names to mask field names.
bool prevIterIsOldTime_
Use value of previous iteration when oldTime is requested.
bool cacheReadFields_
Keep fields read from disc in memory.
bool searchInMemory_
Search in registry before looking on disk.
bool searchFiles_
Search on disk (eg, for a standalone application)
Additional Inherited Members
Public Types inherited from genericRagelLemonDriver
typedef size_t location_type
Type for linear addressing within parse content.
Static Public Member Functions inherited from fvExprDriver
static const fvMesh & defaultMesh ()
Get the default mesh, if one is defined.
static const fvMesh * resetDefaultMesh (const fvMesh &mesh, const bool force=false)
Set the default mesh (if not already set)
static autoPtr< fvExprDriver > New (const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected value driver.
static autoPtr< fvExprDriver > New (const dictionary &dict)
Return a reference to the selected value driver.
static autoPtr< fvExprDriver > New (const word &type, const word &id, const fvMesh &mesh)
Return a reference to the selected value driver.
Static Public Member Functions inherited from exprDriver
static expressions::exprString readExpression (const word &name, const dictionary &dict)
Read an expression string and do substitutions.
static List
< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Read the list of variable strings.
Protected Types inherited from fvExprDriver
enum SetOrigin {
INVALID = 0, NEW, FILE, MEMORY,
CACHE
}
The origin of the topoSet.
Static Protected Member Functions inherited from fvExprDriver
static const fvMesh & regionMesh (const dictionary &dict, const fvMesh &mesh, bool readIfNecessary)
Determine mesh or region mesh as specified in the dictionary with the keyword "region".
template<class T >
static word defaultBoundaryType (const T &)
Default boundary type is calculated.
template<class Type >
static word defaultBoundaryType (const GeometricField< Type, fvPatchField, volMesh > &)
Default boundary type for volume fields is zeroGradient.
template<class T >
static void correctField (T &)
Apply correctBoundaryConditions (volume fields only)
template<class Type >
static void correctField (GeometricField< Type, fvPatchField, volMesh > &fld)
Static Protected Member Functions inherited from exprDriver
template<typename TableType >
static bool readTable (const word &name, const dictionary &dict, HashTable< TableType > &tbl, bool clear=true)
Read an interpolation table.
template<class TableType >
static void writeTable (Ostream &os, const word &name, const HashTable< TableType > &tbl)
Write an interpolation table.
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
The (global) weighted average of a field, with stabilisation.
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
The (global) weighted sum (integral) of a field.
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
Return the location of the min value.
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Return the location of the max value.
Detailed Description
Driver for patch expressions.
In addition to the standard mathematical functions, operations and logical and relational operations, the patch expressions support the following driver-specific functions:
Functions
Function Description Number of arguments
pos The face centres 0
pts The face points 0
area The face area magnitudes 0
weightAverage Area weighted average 1
weightSum Area weighted sum 1
face The face areaNormal vectors 0
point A point-field point value 1
faceToPoint Interpolate face values onto points 1
pointToFace Interpolate point values onto faces 1
rand Random field 0/1
Note
Use namespace debug switch patchExpr for scanner (2), parser (4) or dictionary controls as per Foam::expressions::exprDriver.
Source files
patchExprDriver.H
patchExprDriver.C
patchExprDriverFields.C
patchExprDriverTemplates.C
Definition at line 136 of file patchExprDriver.H.
Constructor & Destructor Documentation
parseDriver (const parseDriver &) protected delete
parseDriver (const fvPatch & p) explicit
Construct for specified patch.
Definition at line 112 of file patchExprDriver.C.
parseDriver (const fvPatch & p, const dictionary & dict)
Construct for specified patch with given dictionary.
Definition at line 121 of file patchExprDriver.C.
parseDriver (const fvPatch & p, const parseDriver & driver_)
Construct for specified patch with copy of driver context.
Definition at line 133 of file patchExprDriver.C.
parseDriver (const word & patchName, const fvMesh & mesh)
Construct with patchName for the given mesh.
Definition at line 145 of file patchExprDriver.C.
parseDriver (const dictionary & dict, const fvMesh & mesh)
Construct with "patch" (mandatory) and "region" (optional) specified in dictionary.
Definition at line 155 of file patchExprDriver.C.
virtual ~parseDriver () virtual default
Destructor.
Member Function Documentation
void operator= (const parseDriver &) protected delete
ClassName ("patchExpr::driver")
virtual autoPtr<expressions::fvExprDriver> clone () const inline virtual
Clone.
Implements fvExprDriver.
Definition at line 204 of file patchExprDriver.H.
Referenced by parseDriver::getVariableIfAvailable().
virtual const fvMesh& mesh () const inline virtual
The mesh we are attached to.
Implements fvExprDriver.
Definition at line 224 of file patchExprDriver.H.
virtual label size () const inline virtual
The underlying field size for the expression.
Implements fvExprDriver.
Definition at line 232 of file patchExprDriver.H.
Referenced by parseDriver::getVariableIfAvailable().
virtual label pointSize () const inline virtual
The underlying point field size for the expression.
Implements fvExprDriver.
Definition at line 240 of file patchExprDriver.H.
References fld, fvPatch::magSf(), parseDriver::patch_, and exprDriver::weightedAverage().
Referenced by parseDriver::getVariableIfAvailable().
Foam::label size (const FieldAssociation geoType) const inline
Field size associated with different geometric field types.
Definition at line 24 of file patchExprDriverI.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), fvPatch::patch(), parseDriver::patch_, Foam::expressions::patchExpr::POINT_DATA, and Foam::expressions::patchExpr::SURFACE_DATA.
unsigned parse (const std::string & expr, size_t pos = 0, size_t len = std::string::npos) virtual
Execute the parser.
The return value currently has no meaning.
Implements exprDriver.
Definition at line 167 of file patchExprDriver.C.
void setResult (Field< Type > * ptr, bool pointVal = false) inline
Set result.
Definition at line 279 of file patchExprDriver.H.
tmp<Field<Type> > getVariableIfAvailable (const word & fldName) const
Retrieve variable as field if possible.
Test tmp for validity to determine success of the operation.
tmp<Field<Type> > getVolField (const word & fldName)
Retrieve field (vol field)
tmp<Field<Type> > getSurfaceField (const word & fldName)
Retrieve field (surface field)
tmp<Field<Type> > getPointField (const word & fldName)
Retrieve field (point field)
tmp<Field<Type> > getField (const word & fldName)
Return named field.
tmp<Field<Type> > faceToPoint (const Field< Type > & field) const
Interpolate face to point.
tmp<Field<Type> > pointToFace (const Field< Type > & field) const
Interpolate point to face values.
Type areaAverage (const Field< Type > & fld) const inline
The area-weighted average of a field.
Definition at line 342 of file patchExprDriver.H.
Type areaSum (const Field< Type > & fld) const inline
The area-weighted sum of a field.
Definition at line 351 of file patchExprDriver.H.
Foam::tmp< Foam::scalarField > field_faceArea () const
The face area magnitudes [magSf] - (swak = area)
Definition at line 52 of file patchExprDriverFields.C.
Foam::tmp< Foam::vectorField > field_faceCentre () const
The face centres - (swak = pos)
Definition at line 59 of file patchExprDriverFields.C.
References fvPatch::magSf(), and parseDriver::patch_.
Foam::tmp< Foam::vectorField > field_areaNormal () const
The face areas with their vector direction [Sf] - (swak = face)
Definition at line 66 of file patchExprDriverFields.C.
Foam::tmp< Foam::vectorField > field_pointField () const
The patch point locations - (swak = pts)
Definition at line 73 of file patchExprDriverFields.C.
Foam::tmp< Foam::scalarField > field_rand (label seed = 0, bool gaussian = false) const
A uniform random field.
Definition at line 81 of file patchExprDriverFields.C.
tmp<scalarField> field_randGaussian (label seed = 0) const inline
A Gaussian random field.
Definition at line 384 of file patchExprDriver.H.
tmp<Field<bool> > getSurfaceField (const word & fldName)
Retrieve field (surface field: bool)
tmp<Field<bool> > getPointField (const word & fldName)
Retrieve field (point field: bool)
Foam::tmp<Foam::Field<bool> > getSurfaceField (const word & name)
Definition at line 30 of file patchExprDriverFields.C.
Foam::tmp<Foam::Field<bool> > getPointField (const word & name)
Definition at line 41 of file patchExprDriverFields.C.
Foam::tmp<Foam::Field<Type> > getVariableIfAvailable (const word & name) const
Definition at line 28 of file patchExprDriverTemplates.C.
References parseDriver::clone(), exprResult::cref(), Foam::endl(), Foam::gAverage(), fvExprDriver::hasVariable(), exprResult::isPointValue(), exprResult::isUniform(), fvExprDriver::lookupGlobal(), fvExprDriver::New(), Foam::nl, parseDriver::pointSize(), Foam::returnReduce(), parseDriver::size(), tmp< T >::valid(), fvExprDriver::variable(), and WarningInFunction.
Foam::tmp<Foam::Field<Type> > getVolField (const word & name)
Definition at line 82 of file patchExprDriverTemplates.C.
Foam::tmp<Foam::Field<Type> > getSurfaceField (const word & name)
Definition at line 90 of file patchExprDriverTemplates.C.
References Foam::name().
Foam::tmp<Foam::Field<Type> > getPointField (const word & name)
Definition at line 98 of file patchExprDriverTemplates.C.
References Foam::name().
Foam::tmp<Foam::Field<Type> > getField (const word & name)
Definition at line 106 of file patchExprDriverTemplates.C.
References Foam::name().
Foam::tmp<Foam::Field<Type> > faceToPoint (const Field< Type > & field) const
Definition at line 198 of file patchExprDriverTemplates.C.
Foam::tmp<Foam::Field<Type> > pointToFace (const Field< Type > & field) const
Definition at line 211 of file patchExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > getVolField (const word & fldName, bool getOldTime)
Definition at line 180 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > getSurfaceField (const word & fldName, bool getOldTime)
Definition at line 199 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::pointPatchField, Foam::pointMesh> > getPointField (const word & fldName, bool getOldTime)
Definition at line 218 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::Field<Type> > getField (const word & name) const
Definition at line 26 of file fieldExprDriverTemplates.C.
References exprResult::cref(), Foam::endl(), Foam::gAverage(), exprDriver::hasVariable(), exprResult::isPointValue(), exprResult::isUniform(), Foam::New(), Foam::nl, parseDriver::pointSize(), Foam::returnReduce(), parseDriver::size(), tmp< T >::valid(), exprDriver::variable(), and WarningInFunction.
Member Data Documentation
const fvPatch& patch_ protected
The referenced patch.
Definition at line 157 of file patchExprDriver.H.
Referenced by parseDriver::field_faceCentre(), parseDriver::pointSize(), and parseDriver::size().
The documentation for this class was generated from the following files:
src/finiteVolume/expressions/patch/patchExprDriver.H
src/finiteVolume/expressions/patch/patchExprDriver.C
src/finiteVolume/expressions/patch/patchExprDriverFields.C
src/finiteVolume/expressions/patch/patchExprDriverI.H
src/finiteVolume/expressions/patch/patchExprDriverTemplates.C
src/finiteVolume/expressions/volume/volumeExprDriverTemplates.C
src/OpenFOAM/expressions/fields/fieldExprDriverTemplates.C