OpenFOAM: IATEsource Class Reference
IATEsource Class Reference abstract
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
Classes
class iNew
Class used for the read-construction of.
Public Member Functions
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
virtual tmp< fvScalarMatrix > R (const volScalarField &alphai, volScalarField &kappai) const =0
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, IATEsource, dictionary,(const IATE &iate, const dictionary &dict),(iate, dict))
IATEsource (const IATE &iate)
autoPtr< IATEsource > clone () const
virtual ~IATEsource ()=default
Destructor.
const phaseModel & phase () const
const twoPhaseSystem & fluid () const
const phaseModel & otherPhase () const
scalar phi () const
tmp< volScalarField > Ur () const
Return the bubble relative velocity.
tmp< volScalarField > Ut () const
Return the bubble turbulent velocity.
tmp< volScalarField > Re () const
Return the bubble Reynolds number.
tmp< volScalarField > CD () const
Return the bubble drag coefficient.
tmp< volScalarField > Mo () const
Return the bubble Morton number.
tmp< volScalarField > Eo () const
Return the bubble Eotvos number.
tmp< volScalarField > We () const
Return the bubble Webber number.
virtual tmp< volScalarField > R () const =0
Static Public Member Functions
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
static autoPtr< IATEsource > New (const word &type, const IATE &iate, const dictionary &dict)
Protected Attributes
const IATE & iate_
Reference to the IATE this source applies to.
Detailed Description
IATE (Interfacial Area Transport Equation) bubble diameter model run-time selectable sources.
Source files
IATEsource.H
IATEsource.C
Source files
IATEsource.H
IATEsource.C
Definition at line 52 of file IATEsource.H.
Constructor & Destructor Documentation
IATEsource (const IATE & iate) inline
Definition at line 115 of file IATEsource.H.
virtual ~IATEsource () virtual default
Destructor.
IATEsource (const IATE & iate) inline
Definition at line 114 of file IATEsource.H.
virtual ~IATEsource () virtual default
Destructor.
Member Function Documentation
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , IATEsource , dictionary , (const IATE &iate, const dictionary &dict) , (iate, dict))
autoPtr<IATEsource> clone () const inline
Definition at line 120 of file IATEsource.H.
Foam::autoPtr< Foam::diameterModels::IATEsource > New (const word & type, const IATE & iate, const dictionary & dict) static
Definition at line 43 of file IATEsource.C.
const phaseModel& phase () const inline
Definition at line 145 of file IATEsource.H.
References phaseModel::fluid(), IATEsource::iate_, and diameterModel::phase().
Referenced by IATEsource::fluid().
const twoPhaseSystem& fluid () const inline
Definition at line 150 of file IATEsource.H.
References twoPhaseSystem::otherPhase(), and IATEsource::phase().
const phaseModel& otherPhase () const inline
Definition at line 155 of file IATEsource.H.
References Foam::constant::mathematical::pi().
scalar phi () const inline
Definition at line 160 of file IATEsource.H.
Foam::tmp< Foam::volScalarField > Ur () const
Return the bubble relative velocity.
Definition at line 68 of file IATEsource.C.
Foam::tmp< Foam::volScalarField > Ut () const
Return the bubble turbulent velocity.
Definition at line 84 of file IATEsource.C.
Foam::tmp< Foam::volScalarField > Re () const
Return the bubble Reynolds number.
Definition at line 89 of file IATEsource.C.
Foam::tmp< Foam::volScalarField > CD () const
Return the bubble drag coefficient.
Definition at line 94 of file IATEsource.C.
Foam::tmp< Foam::volScalarField > Mo () const
Return the bubble Morton number.
Definition at line 111 of file IATEsource.C.
Foam::tmp< Foam::volScalarField > Eo () const
Return the bubble Eotvos number.
Definition at line 122 of file IATEsource.C.
Foam::tmp< Foam::volScalarField > We () const
Return the bubble Webber number.
Definition at line 133 of file IATEsource.C.
virtual tmp<fvScalarMatrix> R (const volScalarField & alphai, volScalarField & kappai) const pure virtual
Implemented in randomCoalescence, phaseChange, turbulentBreakUp, wakeEntrainmentCoalescence, dummy, and wallBoiling.
TypeName ("IATEsource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , IATEsource , dictionary , (const IATE &iate, const dictionary &dict) , (iate, dict))
autoPtr<IATEsource> clone () const inline
Definition at line 119 of file IATEsource.H.
static autoPtr<IATEsource> New (const word & type, const IATE & iate, const dictionary & dict) static
const phaseModel& phase () const inline
Definition at line 144 of file IATEsource.H.
References phaseModel::fluid(), IATEsource::iate_, and diameterModel::phase().
const twoPhaseSystem& fluid () const inline
Definition at line 149 of file IATEsource.H.
References phaseModel::otherPhase(), and IATEsource::phase().
const phaseModel& otherPhase () const inline
Definition at line 154 of file IATEsource.H.
References Foam::constant::mathematical::pi().
scalar phi () const inline
Definition at line 159 of file IATEsource.H.
tmp<volScalarField> Ur () const
Return the bubble relative velocity.
tmp<volScalarField> Ut () const
Return the bubble turbulent velocity.
tmp<volScalarField> Re () const
Return the bubble Reynolds number.
tmp<volScalarField> CD () const
Return the bubble drag coefficient.
tmp<volScalarField> Mo () const
Return the bubble Morton number.
tmp<volScalarField> Eo () const
Return the bubble Eotvos number.
tmp<volScalarField> We () const
Return the bubble Webber number.
virtual tmp<volScalarField> R () const pure virtual
Implemented in randomCoalescence, turbulentBreakUp, wakeEntrainmentCoalescence, and dummy.
Member Data Documentation
const IATE & iate_ protected
Reference to the IATE this source applies to.
Definition at line 62 of file IATEsource.H.
Referenced by IATEsource::phase().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.H
applications/solvers/multiphase/twoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.H
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseSystem/diameterModels/IATE/IATEsources/IATEsource/IATEsource.C