OpenFOAM: faD2dt2Scheme< Type > Class Template Reference
faD2dt2Scheme< Type > Class Template Reference abstract
Abstract base class for d2dt2 schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, faD2dt2Scheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
faD2dt2Scheme (const faMesh &mesh)
Construct from mesh.
faD2dt2Scheme (const faMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~faD2dt2Scheme ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, faPatchField, areaMesh > > facD2dt2 (const dimensioned< Type >)=0
virtual tmp< GeometricField
< Type, faPatchField, areaMesh > > facD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField
< Type, faPatchField, areaMesh > > facD2dt2 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< GeometricField
< Type, faPatchField, areaMesh > > facD2dt2 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famD2dt2 (const dimensionedScalar &, const GeometricField< Type, faPatchField, areaMesh > &)=0
virtual tmp< faMatrix< Type > > famD2dt2 (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< faD2dt2Scheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Return a pointer to a new d2dt2Scheme created on freestore.
Protected Member Functions
faD2dt2Scheme (const faD2dt2Scheme &)=delete
No copy construct.
void operator= (const faD2dt2Scheme &)=delete
No copy assignment.
Protected Attributes
const faMesh & mesh_
Detailed Description
template<class Type>
class Foam::fa::faD2dt2Scheme< Type >
Abstract base class for d2dt2 schemes.
Source files
faD2dt2Scheme.H
faD2dt2Scheme.C
Definition at line 62 of file faD2dt2Scheme.H.
Constructor & Destructor Documentation
faD2dt2Scheme (const faD2dt2Scheme< Type > &) protected delete
No copy construct.
faD2dt2Scheme (const faMesh & mesh) inline
Construct from mesh.
Definition at line 112 of file faD2dt2Scheme.H.
faD2dt2Scheme (const faMesh & mesh, Istream &) inline
Construct from mesh and Istream.
Definition at line 120 of file faD2dt2Scheme.H.
~faD2dt2Scheme () virtual
Destructor.
Definition at line 85 of file faD2dt2Scheme.C.
Member Function Documentation
void operator= (const faD2dt2Scheme< Type > &) protected delete
No copy assignment.
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , faD2dt2Scheme< Type > , Istream , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< faD2dt2Scheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Return a pointer to a new d2dt2Scheme created on freestore.
Definition at line 43 of file faD2dt2Scheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fac::d2dt2(), and Foam::fam::d2dt2().
const faMesh& mesh () const inline
Return mesh reference.
Definition at line 149 of file faD2dt2Scheme.H.
Referenced by EulerFaD2dt2Scheme< Type >::EulerFaD2dt2Scheme().
virtual tmp<GeometricField<Type, faPatchField, areaMesh> > facD2dt2 (const dimensioned< Type >) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
virtual tmp<GeometricField<Type, faPatchField, areaMesh> > facD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
virtual tmp<GeometricField<Type, faPatchField, areaMesh> > facD2dt2 (const dimensionedScalar & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
virtual tmp<GeometricField<Type, faPatchField, areaMesh> > facD2dt2 (const areaScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
virtual tmp<faMatrix<Type> > famD2dt2 (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
virtual tmp<faMatrix<Type> > famD2dt2 (const dimensionedScalar & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
virtual tmp<faMatrix<Type> > famD2dt2 (const areaScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in EulerFaD2dt2Scheme< Type >.
Member Data Documentation
const faMesh& mesh_ protected
Definition at line 71 of file faD2dt2Scheme.H.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/d2dt2Schemes/faD2dt2Scheme/faD2dt2Scheme.H
src/finiteArea/finiteArea/d2dt2Schemes/faD2dt2Scheme/faD2dt2Scheme.C