OpenFOAM: IOerror Class Reference
IOerror Class Reference
Report an I/O error.
Public Member Functions
IOerror (const string &title)
Construct from title string.
IOerror (const dictionary &errDict)
Construct from dictionary.
virtual ~IOerror () throw ()
Destructor.
const string & ioFileName () const
label ioStartLineNumber () const
label ioEndLineNumber () const
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &ioStream)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &dict)
Convert to OSstream.
operator dictionary () const
Create and return a dictionary representation of the error.
void exit (const int errNo=1)
Exit : can be called for any error to exit program.
void abort ()
Abort : used to stop code for fatal errors.
void write (Ostream &os, const bool includeTitle=true) const
Print error message.
Public Member Functions inherited from error
error (const string &title)
Construct from title string.
error (const dictionary &errDict)
Construct from dictionary.
error (const error &err)
Construct as copy.
virtual ~error () throw ()
Destructor.
string message () const
void clear () const
Clear any messages.
const string & functionName () const
const string & sourceFileName () const
label sourceFileLineNumber () const
bool throwing () const
Return the current exception throwing (on or off)
bool throwExceptions (bool doThrow)
Activate/deactivate exception throwing.
bool throwExceptions ()
Activate exception throwing.
bool dontThrowExceptions ()
Deactivate exception throwing.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
operator dictionary () const
Create and return a dictionary representation of the error.
void exit (const int errNo=1)
Exit : can be called for any error to exit program.
void abort ()
Abort : used to stop code for fatal errors.
void write (Ostream &os, const bool includeTitle=true) const
Print error message.
Public Member Functions inherited from messageStream
messageStream (const string &title, const errorSeverity severity, const int maxErrors=0)
Construct from components.
messageStream (const dictionary &dict)
Construct as Fatal from dictionary, extracting the 'title'.
const string & title () const
Return the title of this error type.
int maxErrors () const
Return the maximum number of errors before program termination.
int & maxErrors ()
Return non-const access to the maximum number of errors before.
OSstream & masterStream (const label communicator)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream for << operations.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
Static Public Member Functions
static void SafeFatalIOError (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &ioStream, const string &msg)
Print basic message and exit.
Static Public Member Functions inherited from error
static void warnAboutAge (const char *what, const int version)
Emit warning on stderr about something being old.
static void safePrintStack (std::ostream &os)
Helper function to print a stack, used when OpenFOAM IO not yet initialised.
static void printStack (Ostream &os)
Helper function to print a stack.
Additional Inherited Members
Public Types inherited from messageStream
enum errorSeverity {
INFO = 1, WARNING, SERIOUS, FATAL,
INFO_STDERR = INFO | 0x10
}
Message type, or error severity flags.
Static Public Attributes inherited from messageStream
static int level
Controls the output verbosity of messageStream.
Protected Attributes inherited from error
string functionName_
string sourceFileName_
label sourceFileLineNumber_
bool throwExceptions_
OStringStream * messageStreamPtr_
Protected Attributes inherited from messageStream
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Detailed Description
Report an I/O error.
Definition at line 265 of file error.H.
Constructor & Destructor Documentation
IOerror (const string & title)
Construct from title string.
Definition at line 31 of file IOerror.C.
Referenced by error::operator()().
IOerror (const dictionary & errDict)
Construct from dictionary.
Definition at line 40 of file IOerror.C.
~IOerror () throw () virtual
Destructor.
Definition at line 51 of file IOerror.C.
Referenced by error::operator()().
Member Function Documentation
const string& ioFileName () const inline
Definition at line 299 of file error.H.
Referenced by error::operator()().
label ioStartLineNumber () const inline
Definition at line 304 of file error.H.
Referenced by error::operator()().
label ioEndLineNumber () const inline
Definition at line 309 of file error.H.
Referenced by error::operator()().
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const string & ioFileName, const label ioStartLineNumber = -1, const label ioEndLineNumber = -1)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 58 of file IOerror.C.
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 77 of file IOerror.C.
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const dictionary & dict)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 97 of file IOerror.C.
void SafeFatalIOError (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber, const IOstream & ioStream, const string & msg) static
Print basic message and exit.
Uses cerr if streams not yet constructed (at startup). Use in startup parsing instead of FatalError.
Definition at line 117 of file IOerror.C.
operator dictionary () const
Create and return a dictionary representation of the error.
void exit (const int errNo = 1)
Exit : can be called for any error to exit program.
Definition at line 168 of file IOerror.C.
Referenced by Foam::abort().
void abort ()
Abort : used to stop code for fatal errors.
Definition at line 205 of file IOerror.C.
void write (Ostream & os, const bool includeTitle = true) const
Print error message.
Definition at line 252 of file IOerror.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/error.H
src/OpenFOAM/db/error/IOerror.C