OpenFOAM: ReactingHeterogeneousParcel< ParcelType > Class Template Reference
ReactingHeterogeneousParcel< ParcelType > Class Template Reference
Parcels
Reacting heterogeneous Parcel.
Classes
class constantProperties
Class to hold reacting particle constant properties.
class iNew
Factory class to read-construct particles used for.
Public Types
typedef ParcelType::trackingData trackingData
Use base tracking data.
Public Member Functions
TypeName ("ReactingHeterogeneousParcel")
Runtime type information.
AddToPropertyList (ParcelType,+" nReactions(F1..FN)")
String representation of properties.
ReactingHeterogeneousParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from mesh, position and topology.
ReactingHeterogeneousParcel (const polyMesh &mesh, const vector &position, const label celli)
Construct from a position and a cell, searching for the rest of the.
ReactingHeterogeneousParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const scalarField &Y, const scalarField &F, const constantProperties &constProps)
Construct from components.
ReactingHeterogeneousParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel &p)
Construct as a copy.
ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
const scalarField & F () const
Return const access to F.
label canCombust () const
Return const access to the canCombust flag.
scalarField & F ()
Return access to F.
label & canCombust ()
Return access to the canCombust flag.
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
Update parcel properties over the time interval.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
Write individual parcel properties to stream.
template<class TrackCloudType >
Foam::scalar CpEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idS) const
template<class TrackCloudType >
Foam::scalar HsEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idS) const
template<class TrackCloudType >
Foam::scalar LEff (TrackCloudType &cloud, trackingData &td, const scalar p, const scalar T, const label idS) const
Static Public Member Functions
template<class CloudType , class CompositionType >
static void readFields (CloudType &c, const CompositionType &compModel)
Read - composition supplied.
template<class CloudType >
static void readFields (CloudType &c)
Read - no composition.
template<class CloudType , class CompositionType >
static void writeFields (const CloudType &c, const CompositionType &compModel)
Write - composition supplied.
template<class CloudType >
static void writeFields (const CloudType &c)
Read - no composition.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType , class CompositionType >
static void readObjects (CloudType &c, const CompositionType &compModel, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
template<class CloudType , class CompositionType >
static void writeObjects (const CloudType &c, const CompositionType &compModel, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields
Size in bytes of the fields.
Protected Member Functions
template<class TrackCloudType >
void calcHeterogeneousReactions (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Res, const scalar nu, const scalar d, const scalar T, const scalar mass, const label canCombust, const scalar N, scalar &NCpW, const scalarField &YSolid, scalarField &F, scalarField &dMassSRSolid, scalarField &dMassSRCarrier, scalar &Sh, scalar &dhsTrans) const
Calculate surface reactions.
Protected Attributes
scalarField F_
Progress variables for reactions.
label canCombust_
Flag to identify if the particle can devolatilise and combust.
Friends
Ostream & operator (Ostream &, const ReactingHeterogeneousParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ReactingHeterogeneousParcel< ParcelType >
Reacting heterogeneous Parcel.
Source files
ReactingHeterogeneousParcel.H
ReactingHeterogeneousParcelI.H
ReactingHeterogeneousParcel.C
ReactingHeterogeneousParcelIO.C
Definition at line 48 of file ReactingHeterogeneousParcel.H.
Member Typedef Documentation
typedef ParcelType::trackingData trackingData
Use base tracking data.
Definition at line 123 of file ReactingHeterogeneousParcel.H.
Constructor & Destructor Documentation
ReactingHeterogeneousParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Construct from mesh, position and topology.
Other properties initialised as null
Definition at line 58 of file ReactingHeterogeneousParcelI.H.
ReactingHeterogeneousParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Construct from a position and a cell, searching for the rest of the.
required topology. Other properties are initialised as null.
Definition at line 74 of file ReactingHeterogeneousParcelI.H.
ReactingHeterogeneousParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const scalarField & Y, const scalarField & F, const constantProperties & constProps) inline
Construct from components.
Definition at line 88 of file ReactingHeterogeneousParcelI.H.
ReactingHeterogeneousParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 43 of file ReactingHeterogeneousParcelIO.C.
ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel< ParcelType > & p)
Construct as a copy.
ReactingHeterogeneousParcel (const ReactingHeterogeneousParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
void calcHeterogeneousReactions (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Res, const scalar nu, const scalar d, const scalar T, const scalar mass, const label canCombust, const scalar N, scalar & NCpW, const scalarField & YSolid, scalarField & F, scalarField & dMassSRSolid, scalarField & dMassSRCarrier, scalar & Sh, scalar & dhsTrans) const protected
Calculate surface reactions.
Definition at line 289 of file ReactingHeterogeneousParcel.C.
References F(), Foam::min(), and Foam::sum().
TypeName ("ReactingHeterogeneousParcel< ParcelType >")
Runtime type information.
AddToPropertyList (ParcelType , +" nReactions(F1..FN)")
String representation of properties.
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 320 of file ReactingHeterogeneousParcel.H.
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 328 of file ReactingHeterogeneousParcel.H.
const Foam::scalarField & F () const inline
Return const access to F.
Definition at line 155 of file ReactingHeterogeneousParcelI.H.
Foam::label canCombust () const inline
Return const access to the canCombust flag.
Definition at line 171 of file ReactingHeterogeneousParcelI.H.
Foam::scalarField & F () inline
Return access to F.
Definition at line 163 of file ReactingHeterogeneousParcelI.H.
Foam::label & canCombust () inline
Return access to the canCombust flag.
Definition at line 178 of file ReactingHeterogeneousParcelI.H.
void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Update parcel properties over the time interval.
Definition at line 79 of file ReactingHeterogeneousParcel.C.
References CompositionModel< CloudType >::carrier(), Foam::cbrt(), composition, Cs, forAll, i, CompositionModel< CloudType >::idSolid(), Foam::constant::mathematical::pi(), Foam::pow4(), Foam::Re(), Su, Foam::sum(), T0, Foam::fieldTypes::volume, and Foam::Zero.
void readFields (CloudType & c, const CompositionType & compModel) static
Read - composition supplied.
Definition at line 78 of file ReactingHeterogeneousParcelIO.C.
void readFields (CloudType & c) static
Read - no composition.
Definition at line 69 of file ReactingHeterogeneousParcelIO.C.
void writeFields (const CloudType & c, const CompositionType & compModel) static
Write - composition supplied.
Definition at line 172 of file ReactingHeterogeneousParcelIO.C.
void writeFields (const CloudType & c) static
Read - no composition.
Definition at line 161 of file ReactingHeterogeneousParcelIO.C.
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly) const
Write individual parcel properties to stream.
Definition at line 249 of file ReactingHeterogeneousParcelIO.C.
void readObjects (CloudType & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
no composition
Definition at line 272 of file ReactingHeterogeneousParcelIO.C.
void readObjects (CloudType & c, const CompositionType & compModel, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 296 of file ReactingHeterogeneousParcelIO.C.
void writeObjects (const CloudType & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
no composition
Definition at line 284 of file ReactingHeterogeneousParcelIO.C.
void writeObjects (const CloudType & c, const CompositionType & compModel, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Definition at line 317 of file ReactingHeterogeneousParcelIO.C.
Foam::scalar CpEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idS) const
Definition at line 32 of file ReactingHeterogeneousParcel.C.
Foam::scalar HsEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idS) const
Definition at line 47 of file ReactingHeterogeneousParcel.C.
Foam::scalar LEff (TrackCloudType & cloud, trackingData & td, const scalar p, const scalar T, const label idS) const
Definition at line 62 of file ReactingHeterogeneousParcel.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const ReactingHeterogeneousParcel< ParcelType > &) friend
Member Data Documentation
const std::size_t sizeofFields static
Size in bytes of the fields.
Definition at line 71 of file ReactingHeterogeneousParcel.H.
scalarField F_ protected
Progress variables for reactions.
Definition at line 179 of file ReactingHeterogeneousParcel.H.
label canCombust_ protected
Flag to identify if the particle can devolatilise and combust.
Combustion possible only after volatile content falls below threshold value. States include: 0 = can combust but can change 1 = can devolatilise, can combust -1 = cannot devolatilise or combust, and cannot change
Definition at line 190 of file ReactingHeterogeneousParcel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcel.C
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcelI.H
src/lagrangian/intermediate/parcels/Templates/ReactingHeterogeneousParcel/ReactingHeterogeneousParcelIO.C