OpenFOAM: UnsortedMeshedSurface< Face > Class Template Reference
UnsortedMeshedSurface< Face > Class Template Reference
A surface geometry mesh, in which the surface zone information is conveyed by the 'zoneId' associated with each face.
Public Types
typedef Face FaceType
Face type used.
Public Types inherited from MeshedSurface< Face >
typedef Face FaceType
Face type used.
Public Types inherited from PrimitivePatch< Face,::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef ::Foam::List< Face > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< Face >
typedef SubList< Face > subList
Declare type of subList.
Public Types inherited from UList< Face >
typedef Face value_type
The value type the list contains.
typedef Face * pointer
The pointer type for non-const access to value_type items.
typedef const Face * const_pointer
The pointer type for const access to value_type items.
typedef Face & reference
The type used for storing into value_type objects.
typedef const Face & const_reference
The type used for reading from constant value_type objects.
typedef Face * iterator
Random access iterator for traversing a UList.
typedef const Face * const_iterator
Random access iterator for traversing a UList.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Public Member Functions
TypeName ("UnsortedMeshedSurface")
Runtime type information.
UnsortedMeshedSurface ()
Construct null.
UnsortedMeshedSurface (const UnsortedMeshedSurface< Face > &surf)
Construct as copy.
UnsortedMeshedSurface (const MeshedSurface< Face > &surf)
Construct from a MeshedSurface.
UnsortedMeshedSurface (UnsortedMeshedSurface< Face > &&surf)
Move construct from a UnsortedMeshedSurface.
UnsortedMeshedSurface (MeshedSurface< Face > &&surf)
Move construct from MeshedSurface.
UnsortedMeshedSurface (pointField &&pointLst, List< Face > &&faceLst, List< label > &&zoneIds, UList< surfZoneIdentifier > &tocInfo)
Move construct from components (points, faces, zone ids).
UnsortedMeshedSurface (const fileName &name)
Construct from file name (uses extension to determine type)
UnsortedMeshedSurface (const fileName &name, const word &ext)
Construct from file name (uses extension to determine type)
UnsortedMeshedSurface (Istream &is)
Construct from Istream.
UnsortedMeshedSurface (const Time &t, const word &surfName=word::null)
Construct from objectRegistry and a named surface.
declareRunTimeSelectionTable (autoPtr, UnsortedMeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~UnsortedMeshedSurface ()=default
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const UnsortedMeshedSurface< Face > &surf, const dictionary &options),(name, surf, options))
label size () const
The surface size is the number of faces.
void setSize (const label)
Reset size of face and zone list.
virtual const labelList & zoneIds () const
Return const access to the zone ids.
const List< surfZoneIdentifier > & zoneToc () const
Return const access to the zone table-of-contents.
surfZoneList sortedZones (labelList &faceMap) const
Sort faces according to zoneIds.
void setOneZone ()
Set zones to 0 and set a single zone.
void setZones (const surfZoneList &zoneLst)
Set zone ids and zones.
void setZones (const labelUList &sizes, const UList< word > &names)
Set zone ids and zones.
void setZones (const labelUList &sizes)
Set zone ids and zones with default names.
virtual void clear ()
Clear all storage.
template<class BoolListType >
UnsortedMeshedSurface subsetMesh (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
UnsortedMeshedSurface subsetMesh (const bitSet &include) const
Return new surface.
UnsortedMeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void swap (MeshedSurface< Face > &surf)=delete
Swap contents - disabled.
void swap (UnsortedMeshedSurface< Face > &surf)
Swap contents.
void transfer (UnsortedMeshedSurface< Face > &surf)
Transfer the contents of the argument and annul the argument.
void transfer (MeshedSurface< Face > &surf)
Transfer the contents of the argument and annul the argument.
autoPtr< labelList > releaseZoneIds ()
Release (clear) stored zoneIds and return for reuse.
bool read (const fileName &name, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &name)
Read from file. Chooses reader based on detected extension.
virtual void write (const fileName &name, const dictionary &options=dictionary::null) const
Generic write routine. Chooses writer based on its extension.
void write (const Time &t, const word &surfName=word::null) const
Write to database.
void operator= (const UnsortedMeshedSurface< Face > &surf)
Copy assignment.
void operator= (UnsortedMeshedSurface< Face > &&surf)
Move assignment.
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
template<class BoolListType >
Foam::UnsortedMeshedSurface< Face > subsetMesh (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
Public Member Functions inherited from MeshedSurface< Face >
ClassName ("MeshedSurface")
Runtime type information.
MeshedSurface ()
Construct null, an empty surface.
MeshedSurface (const MeshedSurface &surf)
Copy construct.
MeshedSurface (const UnsortedMeshedSurface< Face > &surf)
Copy construct from an UnsortedMeshedSurface.
MeshedSurface (MeshedSurface &&surf)
Move construct.
MeshedSurface (UnsortedMeshedSurface< Face > &&surf)
Move construct from an UnsortedMeshedSurface.
MeshedSurface (const pointField &pointLst, const UList< Face > &faceLst, const UList< surfZone > &zoneLst)
Copy construct from components (points, faces, zones).
MeshedSurface (pointField &&pointLst, List< Face > &&faceLst, const UList< surfZone > &zoneLst)
Move construct from components (points, faces).
MeshedSurface (const pointField &pointLst, const UList< Face > &faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Copy construct from components (points, faces).
MeshedSurface (pointField &&pointLst, List< Face > &&faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Move construct from components (points, faces).
MeshedSurface (const polyBoundaryMesh &bMesh, const bool globalPoints=false)
Construct from a boundary mesh with local points/faces.
MeshedSurface (const surfMesh &mesh)
Construct from a surfMesh.
MeshedSurface (const fileName &name)
Construct from file name (uses extension to determine type)
MeshedSurface (const fileName &name, const word &ext)
Construct from file name (uses extension to determine type)
MeshedSurface (Istream &is)
Construct from Istream.
MeshedSurface (const Time &runTime, const word &surfName=word::null)
Construct from database.
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< Face > &surf, const dictionary &options),(name, surf, options))
label size () const
The surface size is the number of faces.
const List< Face > & surfFaces () const
Return const access to the faces.
const surfZoneList & surfZones () const
Const access to the surface zones.
const vectorField & Sf () const
Face area vectors (normals)
const scalarField & magSf () const
Face area magnitudes.
const vectorField & Cf () const
Face centres.
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
Add surface zones.
bool addZonesToFaces ()
Propagate zone information on face regions.
virtual void removeZones ()
Remove surface zones.
virtual void movePoints (const pointField &newPoints)
Move points.
virtual void scalePoints (const scalar scaleFactor)
Scale points. A non-positive factor is ignored.
virtual void cleanup (const bool verbose)
Remove invalid faces.
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label nTriangles () const
Count number of triangles.
virtual label nTriangles (List< label > &faceMap) const
Count number of triangles, returning a face map of original ids.
virtual label triangulate ()
Triangulate in-place, returning the number of triangles added.
virtual label triangulate (List< label > &faceMap)
Triangulate in-place, returning the number of triangles added.
template<class BoolListType >
MeshedSurface subsetMesh (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
MeshedSurface subsetMesh (const bitSet &include) const
Return new surface.
MeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void swap (MeshedSurface< Face > &surf)
Swap contents.
void transfer (pointField &pointLst, List< Face > &faceLst)
Transfer the components.
void transfer (MeshedSurface< Face > &surf)
Transfer the contents of the argument and annul the argument.
void transfer (UnsortedMeshedSurface< Face > &surf)
Transfer the contents of the argument and annul the argument.
autoPtr< MeshedSurface< Face > > releaseGeom ()
Release (clear) geometry and return for reuse.
void swapFaces (List< Face > &faces)
Swap the stored faces.
void swapPoints (pointField &points)
Swap the stored points.
void swapZones (surfZoneList &zones)
Swap the stored zones.
bool read (const fileName &name, const word &ext)
Read from file. Chooses reader based on explicit extension.
void writeStats (Ostream &os) const
void write (const Time &t, const word &surfName=word::null) const
Write to database.
void operator= (const MeshedSurface< Face > &surf)
Copy assignment.
void operator= (MeshedSurface< Face > &&surf)
Move assignment.
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
template<class Face>
MeshedSurface (const MeshedSurface< Face > &surf)
template<class Face>
MeshedSurface (MeshedSurface< Face > &&surf)
template<class BoolListType >
Foam::MeshedSurface< Face > subsetMesh (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
template<>
bool addZonesToFaces ()
template<>
bool addZonesToFaces ()
Public Member Functions inherited from PrimitivePatch< Face,::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< Face > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (::Foam::List< Face > &&faces, const Field< point > &points)
Construct from components, transferring faces.
PrimitivePatch (::Foam::List< Face > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face,::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< point > & faceNormals () const
Return face unit normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face,::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< Face >
constexpr List () noexcept
Null constructor.
List (const label len)
Construct with given size.
List (const label len, const Face &val)
Construct with given size and value for all elements.
List (const label len, const zero)
Construct with given size initializing all elements to zero.
List (const one, const Face &val)
Construct with length=1, copying the value as the only content.
List (const one, Face &&val)
Construct with length=1, moving the value as the only content.
List (const one, const zero)
Construct with length=1, initializing content to zero.
List (const List< Face > &a)
Copy construct from list.
List (const UList< Face > &a)
Copy construct contents from list.
List (List< Face > &a, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Face > &list, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
List (const FixedList< Face, N > &list)
Construct as copy of FixedList<T, N>
List (const PtrList< Face > &list)
Construct as copy of PtrList<T>
List (const SLList< Face > &list)
Construct as copy of SLList<T>
List (const IndirectListBase< Face, Addr > &list)
Construct as copy of IndirectList contents.
List (std::initializer_list< Face > list)
Construct from an initializer list.
List (List< Face > &&list)
Move construct from List.
List (DynamicList< Face, SizeMin > &&list)
Move construct from DynamicList.
List (SortableList< Face > &&list)
Move construct from SortableList.
List (SLList< Face > &&list)
Move construct from SLList.
List (Istream &is)
Construct from Istream.
autoPtr< List< Face > > clone () const
Clone.
~List ()
Destructor.
void resize (const label newSize)
Adjust allocated size of list.
void resize (const label newSize, const Face &val)
Adjust allocated size of list and set val for new elements.
void setSize (const label newSize)
Alias for resize(const label)
void setSize (const label newSize, const Face &val)
Alias for resize(const label, const T&)
void clear ()
Clear the list, i.e. set size to zero.
void append (const Face &val)
Append an element at the end of the list.
void append (Face &&val)
Move append an element at the end of the list.
void append (const UList< Face > &list)
Append a List to the end of this list.
void append (const IndirectListBase< Face, Addr > &list)
Append IndirectList contents at the end of this list.
void transfer (List< Face > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (DynamicList< Face, SizeMin > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (SortableList< Face > &list)
Transfer the contents of the argument List into this list and annul the argument list.
Face & newElmt (const label i)
Return subscript-checked element of UList and resizing the list if required.
void operator= (const UList< Face > &a)
Assignment to UList operator. Takes linear time.
void operator= (const List< Face > &list)
Assignment operator. Takes linear time.
void operator= (const SLList< Face > &list)
Assignment to SLList operator. Takes linear time.
void operator= (const IndirectListBase< Face, Addr > &list)
Assignment from IndirectList. Takes linear time.
void operator= (std::initializer_list< Face > list)
Assignment to an initializer list.
void operator= (const Face &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (List< Face > &&list)
Move assignment. Takes constant time.
void operator= (DynamicList< Face, SizeMin > &&list)
Move assignment. Takes constant time.
void operator= (SortableList< Face > &&list)
Move assignment. Takes constant time.
void operator= (SLList< Face > &&list)
Move assignment. Takes constant time.
void shallowCopy (const UList< Face > &)=delete
No shallowCopy permitted.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type set (const label i, bool val=true)
A bitSet::set() method for a list of bool.
Public Member Functions inherited from UList< Face >
label size () const noexcept
The number of elements in the UList.
void writeEntry (const word &keyword, Ostream &os) const
Write the List as a dictionary entry with keyword.
void operator= (const Face &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
constexpr UList () noexcept
Null constructor.
UList (Face *__restrict__ v, label size) noexcept
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const Face & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
Face & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const Face & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
Face & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
std::streamsize byteSize () const
Return the binary size in number of characters of the UList if the element is a primitive type.
const Face * cdata () const
Return a const pointer to the first data element.
Face * data ()
Return a pointer to the first data element.
Face & first ()
Return the first element of the list.
const Face & first () const
Return first element of the list.
Face & last ()
Return the last element of the list.
const Face & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is within valid range [0,size].
void checkIndex (const label i) const
Check index is within valid range [0,size)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const Face &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const Face &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const Face &val, const label start=0) const
True if the value if found in the list.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element. Fatal on an empty list.
void swapLast (const label i)
Swap element with the last element. Fatal on an empty list.
void shallowCopy (const UList< Face > &list)
Copy the pointer held by the given UList.
void deepCopy (const UList< Face > &list)
Copy elements of the given UList.
Face & operator[] (const label i)
Return element of UList.
const Face & operator[] (const label i) const
Return element of constant UList.
UList< Face > operator[] (const labelRange &range)
Return (start,size) subset from UList with non-const access.
const UList< Face > operator[] (const labelRange &range) const
Return (start,size) subset from UList with const access.
operator const Foam::List< Face > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
bool empty () const noexcept
True if the UList is empty (ie, size() is zero)
void swap (UList< Face > &list)
Swap content with another UList of the same type in constant time.
bool operator== (const UList< Face > &a) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Face > &a) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Face > &list) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Face > &a) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Face > &a) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Face > &a) const
Return true if !(a < b). Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type test (const label i) const
A bitSet::test() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type get (const label i) const
A bitSet::get() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type unset (const label i)
A bitSet::unset() method for a list of bool.
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
Construct null.
virtual ~surfaceFormatsCore ()=default
Destructor.
Static Public Member Functions
static bool canReadType (const word &ext, bool verbose=false)
Can we read this file format type?
static bool canRead (const fileName &name, bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
Known readable file-types.
static wordHashSet writeTypes ()
Known writable file-types.
static autoPtr
< UnsortedMeshedSurface > New (const fileName &name, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr
< UnsortedMeshedSurface > New (const fileName &name)
Select constructed from filename (implicit extension)
static void write (const fileName &name, const UnsortedMeshedSurface< Face > &surf, const dictionary &options=dictionary::null)
Write to file, select based on its extension.
static void write (const fileName &name, const word &ext, const UnsortedMeshedSurface< Face > &surf, const dictionary &options)
Write to file, selected based on given extension.
Static Public Member Functions inherited from MeshedSurface< Face >
static bool canRead (const fileName &name, bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
Known readable file-types.
static wordHashSet writeTypes ()
Known writable file-types.
static autoPtr< MeshedSurface > New (const fileName &name, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< MeshedSurface > New (const fileName &name)
Select constructed from filename (implicit extension)
static void write (const fileName &name, const MeshedSurface< Face > &surf, const dictionary &options=dictionary::null)
Write to file, selecting writer based on its extension.
static void write (const fileName &name, const word &ext, const MeshedSurface< Face > &surf, const dictionary &options=dictionary::null)
Write to file, selecting writer based on the given extension.
Static Public Member Functions inherited from List< Face >
static const List< Face > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Face >
static const UList< Face > & null ()
Return a UList reference to a nullObject.
static constexpr label max_size () noexcept
The size of the largest possible UList.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Helper function when checking if a file extension is supported.
static fileName localMeshFileName (const word &surfName=word::null)
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName=word::null)
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName=word::null)
Find mesh file with surfName.
Protected Member Functions
labelList & storedZoneIds ()
Return non-const access to the zone Ids.
List< surfZoneIdentifier > & storedZoneToc ()
Return non-const access to the zone table-of-contents.
virtual void remapFaces (const labelUList &faceMap)
Set new zones from faceMap.
Protected Member Functions inherited from MeshedSurface< Face >
void transcribe (MeshedSurface< face > &surf)
Transfer points/zones from 'face' to other other shapes.
void checkZones ()
Basic sanity check on zones.
pointField & storedPoints ()
Non-const access to global points.
List< Face > & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
void sortFacesAndStore (DynamicList< Face > &unsortedFaces, DynamicList< label > &zoneIds, const bool sorted)
Sort faces by zones and store sorted faces.
template<>
void transcribe (MeshedSurface< face > &surf)
template<>
void transcribe (MeshedSurface< face > &surf)
template<>
void transcribe (MeshedSurface< face > &surf)
Protected Member Functions inherited from UList< Face >
void size (const label n) noexcept
Override size to be inconsistent with allocated storage.
void writeEntry (Ostream &os) const
Write the UList with its compound type.
labelRange validateRange (const labelRange &range) const
Return a validated (start,size) subset range, which means that it always addresses a valid section of the list.
UList< Face > & operator= (const UList< Face > &)=delete
No copy assignment (default: shallow copy)
Friends
template<class Face2 >
class MeshedSurface
template<class Face2 >
class UnsortedMeshedSurface
class surfMesh
Istream & operator>> (Istream &is, UnsortedMeshedSurface< Face > &surf)
Read UnsortedMeshedSurface from Istream.
Ostream & operator (Ostream &os, const UnsortedMeshedSurface< Face > &surf)
Write UnsortedMeshedSurface to Ostream.
Additional Inherited Members
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Read non-empty and non-comment line.
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a surfZone list with a single entry, the size of which corresponds to that of the container.
Detailed Description
template<class Face>
class Foam::UnsortedMeshedSurface< Face >
A surface geometry mesh, in which the surface zone information is conveyed by the 'zoneId' associated with each face.
This form of surface description is particularly useful for reading in surface meshes from third-party formats (eg, obj, stl, gts, etc.). It can also be particularly useful for situations in which the surface many be adjusted in an arbitrary manner without worrying about needed to adjust the zone information (eg, surface refinement).
See Also
The Foam::MeshedSurface - which is organized as a surface mesh, but with independent zone information.
Source files
UnsortedMeshedSurface.H
UnsortedMeshedSurface.C
Definition at line 75 of file MeshedSurface.H.
Member Typedef Documentation
typedef Face FaceType
Face type used.
Definition at line 170 of file UnsortedMeshedSurface.H.
Constructor & Destructor Documentation
UnsortedMeshedSurface ()
Construct null.
Definition at line 153 of file UnsortedMeshedSurface.C.
UnsortedMeshedSurface (const UnsortedMeshedSurface< Face > & surf)
Construct as copy.
Definition at line 161 of file UnsortedMeshedSurface.C.
UnsortedMeshedSurface (const MeshedSurface< Face > & surf)
Construct from a MeshedSurface.
Definition at line 173 of file UnsortedMeshedSurface.C.
UnsortedMeshedSurface (UnsortedMeshedSurface< Face > && surf)
Move construct from a UnsortedMeshedSurface.
Definition at line 187 of file UnsortedMeshedSurface.C.
References MeshedSurface< Face >::surfZones().
UnsortedMeshedSurface (MeshedSurface< Face > && surf)
Move construct from MeshedSurface.
Definition at line 199 of file UnsortedMeshedSurface.C.
References transfer().
UnsortedMeshedSurface (pointField && pointLst, List< Face > && faceLst, List< label > && zoneIds, UList< surfZoneIdentifier > & tocInfo)
Move construct from components (points, faces, zone ids).
Zone information is fairly lightweight and is copied.
Definition at line 211 of file UnsortedMeshedSurface.C.
References transfer().
UnsortedMeshedSurface (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 239 of file UnsortedMeshedSurface.C.
References Foam::blockMeshTools::read().
UnsortedMeshedSurface (const fileName & name, const word & ext)
Construct from file name (uses extension to determine type)
Definition at line 226 of file UnsortedMeshedSurface.C.
UnsortedMeshedSurface (Istream & is)
Construct from Istream.
Definition at line 251 of file UnsortedMeshedSurface.C.
References Foam::blockMeshTools::read().
UnsortedMeshedSurface (const Time & t, const word & surfName = word::null)
Construct from objectRegistry and a named surface.
Definition at line 263 of file UnsortedMeshedSurface.C.
References Foam::blockMeshTools::read().
virtual ~UnsortedMeshedSurface () virtual default
Destructor.
Member Function Documentation
labelList& storedZoneIds () inline protected
Return non-const access to the zone Ids.
Definition at line 144 of file UnsortedMeshedSurface.H.
List<surfZoneIdentifier>& storedZoneToc () inline protected
Return non-const access to the zone table-of-contents.
Definition at line 152 of file UnsortedMeshedSurface.H.
void remapFaces (const labelUList & faceMap) protected virtual
Set new zones from faceMap.
Reimplemented from MeshedSurface< Face >.
Definition at line 378 of file UnsortedMeshedSurface.C.
TypeName ("UnsortedMeshedSurface< Face >")
Runtime type information.
bool canReadType (const word & ext, bool verbose = false) static
Can we read this file format type?
Definition at line 49 of file UnsortedMeshedSurface.C.
bool canRead (const fileName & name, bool verbose = false) static
Can we read this file format?
Definition at line 83 of file UnsortedMeshedSurface.C.
bool canWriteType (const word & ext, bool verbose = false) static
Can we write this file format type?
Definition at line 66 of file UnsortedMeshedSurface.C.
Foam::wordHashSet readTypes () static
Known readable file-types.
Definition at line 34 of file UnsortedMeshedSurface.C.
Referenced by triSurface::readTypes().
Foam::wordHashSet writeTypes () static
Known writable file-types.
Definition at line 41 of file UnsortedMeshedSurface.C.
declareRunTimeSelectionTable (autoPtr , UnsortedMeshedSurface< Face > , fileExtension , (const fileName &name) , (name))
Foam::autoPtr< Foam::UnsortedMeshedSurface< Face > > New (const fileName & name, const word & ext) static
Select constructed from filename (explicit extension)
Definition at line 30 of file UnsortedMeshedSurfaceNew.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::flatOutput(), HashTable< T, Key, Hash >::found(), InfoInFunction, Foam::New(), and Foam::nl.
Foam::autoPtr< Foam::UnsortedMeshedSurface< Face > > New (const fileName & name) static
Select constructed from filename (implicit extension)
Definition at line 71 of file UnsortedMeshedSurfaceNew.C.
declareMemberFunctionSelectionTable (void , UnsortedMeshedSurface< Face > , write , fileExtension , (const fileName &name, const UnsortedMeshedSurface< Face > &surf, const dictionary &options) , (name, surf, options))
void write (const fileName & name, const UnsortedMeshedSurface< Face > & surf, const dictionary & options = dictionary::null) static
Write to file, select based on its extension.
Definition at line 99 of file UnsortedMeshedSurface.C.
void write (const fileName & name, const word & ext, const UnsortedMeshedSurface< Face > & surf, const dictionary & options) static
Write to file, selected based on given extension.
Definition at line 111 of file UnsortedMeshedSurface.C.
References Foam::vtk::write().
label size () const inline
The surface size is the number of faces.
Definition at line 353 of file UnsortedMeshedSurface.H.
void setSize (const label s)
Reset size of face and zone list.
Definition at line 436 of file UnsortedMeshedSurface.C.
virtual const labelList& zoneIds () const inline virtual
Return const access to the zone ids.
Definition at line 366 of file UnsortedMeshedSurface.H.
const List<surfZoneIdentifier>& zoneToc () const inline
Return const access to the zone table-of-contents.
Definition at line 374 of file UnsortedMeshedSurface.H.
Foam::surfZoneList sortedZones (labelList & faceMap) const
Sort faces according to zoneIds.
Returns a surfZoneList and sets faceMap to index within faces() (i.e. map from original,unsorted to sorted)
Definition at line 455 of file UnsortedMeshedSurface.C.
void setOneZone ()
Set zones to 0 and set a single zone.
Definition at line 278 of file UnsortedMeshedSurface.C.
void setZones (const surfZoneList & zoneLst)
Set zone ids and zones.
Definition at line 303 of file UnsortedMeshedSurface.C.
void setZones (const labelUList & sizes, const UList< word > & names)
Set zone ids and zones.
Definition at line 325 of file UnsortedMeshedSurface.C.
void setZones (const labelUList & sizes)
Set zone ids and zones with default names.
Definition at line 350 of file UnsortedMeshedSurface.C.
void clear () virtual
Clear all storage.
Reimplemented from MeshedSurface< Face >.
Definition at line 445 of file UnsortedMeshedSurface.C.
UnsortedMeshedSurface subsetMesh (const BoolListType & include, labelList & pointMap, labelList & faceMap) const
Return new surface.
Parameters
[in] include the faces to select
[out] pointMap from subsetMeshMap
[out] faceMap from subsetMeshMap
UnsortedMeshedSurface subsetMesh (const bitSet & include) const
Return new surface.
Foam::UnsortedMeshedSurface< Face > subsetMesh (const labelHashSet & include) const
Return new surface.
Definition at line 584 of file UnsortedMeshedSurface.C.
void swap (MeshedSurface< Face > & surf) delete
Swap contents - disabled.
void swap (UnsortedMeshedSurface< Face > & surf)
Swap contents.
Definition at line 595 of file UnsortedMeshedSurface.C.
void transfer (UnsortedMeshedSurface< Face > & surf)
Transfer the contents of the argument and annul the argument.
Definition at line 619 of file UnsortedMeshedSurface.C.
void transfer (MeshedSurface< Face > & surf)
Transfer the contents of the argument and annul the argument.
Definition at line 641 of file UnsortedMeshedSurface.C.
Foam::autoPtr< Foam::labelList > releaseZoneIds ()
Release (clear) stored zoneIds and return for reuse.
Definition at line 654 of file UnsortedMeshedSurface.C.
bool read (const fileName & name, const word & ext)
Read from file. Chooses reader based on explicit extension.
Definition at line 678 of file UnsortedMeshedSurface.C.
bool read (const fileName & name) virtual
Read from file. Chooses reader based on detected extension.
Reimplemented from MeshedSurface< Face >.
Reimplemented in GTSsurfaceFormat< Face >.
Definition at line 662 of file UnsortedMeshedSurface.C.
References autoPtr< T >::New().
virtual void write (const fileName & name, const dictionary & options = dictionary::null) const inline virtual
Generic write routine. Chooses writer based on its extension.
Reimplemented from MeshedSurface< Face >.
Reimplemented in GTSsurfaceFormat< Face >.
Definition at line 486 of file UnsortedMeshedSurface.H.
void write (const Time & t, const word & surfName = word::null) const
Write to database.
Definition at line 693 of file UnsortedMeshedSurface.C.
void operator= (const UnsortedMeshedSurface< Face > & surf)
Copy assignment.
Definition at line 706 of file UnsortedMeshedSurface.C.
void operator= (UnsortedMeshedSurface< Face > && surf)
Move assignment.
Definition at line 721 of file UnsortedMeshedSurface.C.
operator MeshedSurfaceProxy< Face > () const
Conversion operator to MeshedSurfaceProxy.
Foam::UnsortedMeshedSurface<Face> subsetMesh (const BoolListType & include, labelList & pointMap, labelList & faceMap) const
Definition at line 528 of file UnsortedMeshedSurface.C.
Friends And Related Function Documentation
friend class MeshedSurface friend
Definition at line 85 of file UnsortedMeshedSurface.H.
friend class UnsortedMeshedSurface friend
Definition at line 86 of file UnsortedMeshedSurface.H.
friend class surfMesh friend
Definition at line 89 of file UnsortedMeshedSurface.H.
Istream& operator>> (Istream & is, UnsortedMeshedSurface< Face > & surf) friend
Read UnsortedMeshedSurface from Istream.
Avoid using to read/write file content (fragile).
Ostream& operator (Ostream & os, const UnsortedMeshedSurface< Face > & surf) friend
Write UnsortedMeshedSurface to Ostream.
Avoid using to read/write file content (fragile).
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurface/MeshedSurface.H
src/surfMesh/UnsortedMeshedSurface/UnsortedMeshedSurface.H
src/surfMesh/UnsortedMeshedSurface/UnsortedMeshedSurface.C
src/surfMesh/UnsortedMeshedSurface/UnsortedMeshedSurfaceNew.C