OpenFOAM: NSRDSfunc5 Class Reference
NSRDSfunc5 Class Reference
NSRDS function number 105.
Public Member Functions
TypeName ("NSRDSfunc5")
Runtime type information.
NSRDSfunc5 (const scalar a, const scalar b, const scalar c, const scalar d)
Construct from components.
NSRDSfunc5 (const dictionary &dict)
Construct from dictionary.
scalar f (scalar, scalar T) const
Evaluate the function and return the result.
void writeData (Ostream &os) const
Write the function coefficients.
Public Member Functions inherited from thermophysicalFunction
TypeName ("thermophysicalFunction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, Istream,(Istream &is),(is))
declareRunTimeSelectionTable (autoPtr, thermophysicalFunction, dictionary,(const dictionary &dict),(dict))
thermophysicalFunction ()
Construct null.
virtual ~thermophysicalFunction ()=default
Destructor.
Friends
Ostream & operator<< (Ostream &os, const NSRDSfunc5 &f)
Additional Inherited Members
Static Public Member Functions inherited from thermophysicalFunction
static autoPtr
< thermophysicalFunction > New (Istream &is)
Return pointer to new thermophysicalFunction created from input.
static autoPtr
< thermophysicalFunction > New (const dictionary &dict)
Return pointer to new thermophysicalFunction created from dict.
Detailed Description
NSRDS function number 105.
Source:
                  NSRDS - AICHE
             Data Compilation Tables
                of Properties of
                 Pure Compounds
    Design Institute for Physical Property Data
      American Institute of Chemical Engineers
              345 East 47th Street
            New York, New York 10017
     National Standard Reference Data System
     American Institute of Chemical Engineers
      T.E. Daubert       -       R.P. Danner
        Department of Chemical Engineering
        The Pennsylvania State University
            University Park, PA 16802
Definition at line 63 of file NSRDSfunc5.H.
Constructor & Destructor Documentation
NSRDSfunc5 (const scalar a, const scalar b, const scalar c, const scalar d)
Construct from components.
Definition at line 35 of file NSRDSfunc5.C.
NSRDSfunc5 (const dictionary & dict)
Construct from dictionary.
Definition at line 49 of file NSRDSfunc5.C.
Member Function Documentation
TypeName ("NSRDSfunc5")
Runtime type information.
scalar f (scalar , scalar T) const inline virtual
Evaluate the function and return the result.
Implements thermophysicalFunction.
Definition at line 105 of file NSRDSfunc5.H.
References Foam::pow().
Referenced by C8H10::pv(), iC3H8O::pv(), nC3H8O::pv(), H2O::pv(), MB::pv(), IC8H18::pv(), C3H6O::pv(), C2H6O::pv(), CH3OH::pv(), C9H20::pv(), C8H18::pv(), C2H5OH::pv(), C7H8::pv(), C7H16::pv(), Ar::pv(), C6H14::pv(), C14H30::pv(), C3H8::pv(), C13H28::pv(), C12H26::pv(), C2H6::pv(), C10H22::pv(), C16H34::pv(), C4H10O::pv(), bC10H7CH3::pv(), aC10H7CH3::pv(), C6H6::pv(), N2::pv(), and IDEA::pv().
void writeData (Ostream & os) const inline virtual
Write the function coefficients.
Implements thermophysicalFunction.
Definition at line 113 of file NSRDSfunc5.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const NSRDSfunc5 & f) friend
Definition at line 124 of file NSRDSfunc5.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc5/NSRDSfunc5.H
src/thermophysicalModels/thermophysicalProperties/thermophysicalFunctions/NSRDSfunctions/NSRDSfunc5/NSRDSfunc5.C