OpenFOAM: geometryBase Class Reference
geometryBase Class Reference abstract
Base class for surface, text handling etc.
Public Types
enum renderModeType { rmFlat, rmGouraud, rmPhong }
Surface shading types.
Public Member Functions
geometryBase (const runTimePostProcessing &parent_, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~geometryBase ()
Destructor.
const runTimePostProcessing & parent () const
Return the reference to the parent function object.
bool needsCollective () const
May need to gather geometry parts to render on single-processor.
const word & name () const
Return the name.
bool visible () const
Return the visible flag.
bool parallel () const
Allow parallel rendering.
scalar opacity (const scalar position) const
Return the opacity.
const HashPtrTable< Function1
< vector > > & colours () const
Return reference to the colours.
virtual void addGeometryToScene (const scalar position, vtkRenderer *renderer)=0
Add geometry to scene.
virtual void updateActors (const scalar position)=0
Update the actors.
virtual bool clear ()=0
Clear any files used to create the object(s)
Static Public Attributes
static const Enum< renderModeType > renderModeTypeNames
Names for surface shading types.
static int debug
Debug switch.
Protected Member Functions
void initialiseActor (vtkActor *actor) const
Initialise actor.
geometryBase (const geometryBase &)=delete
No copy construct.
void operator= (const geometryBase &)=delete
No copy assignment.
Protected Attributes
const runTimePostProcessing & parent_
Reference to the parent function object.
word name_
The surface name.
bool visible_
Visible flag.
bool parallel_
Allow parallel rendering.
renderModeType renderMode_
Render mode.
autoPtr< Function1< scalar > > opacity_
Opacity.
const HashPtrTable< Function1
< vector > > & colours_
Reference to the colours.
Detailed Description
Base class for surface, text handling etc.
Dictionary controls
Property Description Required Default
visible Display the object no yes
renderMode Shading (flat/gouraud/phong) no gouraud
opacity Object opacity no 1.0
parallel Allow parallel rendering no true
Source files
geometryBase.H
geometryBase.C
Definition at line 97 of file geometryBase.H.
Member Enumeration Documentation
enum renderModeType
Surface shading types.
Enumerator
rmFlat
Flat shading.
rmGouraud
Gouraud shading.
rmPhong
Phong shading.
Definition at line 106 of file geometryBase.H.
Constructor & Destructor Documentation
geometryBase (const geometryBase &) protected delete
No copy construct.
geometryBase (const runTimePostProcessing & parent_, const dictionary & dict, const HashPtrTable< Function1< vector >> & colours)
Construct from dictionary.
Definition at line 88 of file geometryBase.C.
~geometryBase () virtual
Destructor.
Definition at line 127 of file geometryBase.C.
Member Function Documentation
void initialiseActor (vtkActor * actor) const protected
Initialise actor.
Definition at line 57 of file geometryBase.C.
void operator= (const geometryBase &) protected delete
No copy assignment.
const Foam::functionObjects::runTimePostProcessing & parent () const
Return the reference to the parent function object.
Definition at line 134 of file geometryBase.C.
Referenced by geometryPatches::gatherPatchPieces().
bool needsCollective () const
May need to gather geometry parts to render on single-processor.
True when OpenFOAM is running in parallel but VTK is not.
Definition at line 141 of file geometryBase.C.
Referenced by geometryPatches::addPatchField(), geometryCloud::gatherCloud(), geometryPatches::gatherPatchPieces(), and surface::gatherSurfacePieces().
const Foam::word & name () const
Return the name.
Definition at line 148 of file geometryBase.C.
References UPstream::parRun().
bool visible () const inline
Return the visible flag.
Definition at line 225 of file geometryBase.H.
bool parallel () const inline
Allow parallel rendering.
Definition at line 233 of file geometryBase.H.
Foam::scalar opacity (const scalar position) const
Return the opacity.
Definition at line 155 of file geometryBase.C.
const Foam::HashPtrTable< Foam::Function1< Foam::vector >, Foam::word > & colours () const
Return reference to the colours.
Definition at line 164 of file geometryBase.C.
virtual void addGeometryToScene (const scalar position, vtkRenderer * renderer) pure virtual
Add geometry to scene.
Implemented in text, geometryCloud, cuttingPlaneFilter, geometryPatches, functionObjectCloud, contourFilter, geometrySurface, functionObjectSurface, and functionObjectLine.
virtual void updateActors (const scalar position) pure virtual
Update the actors.
Implemented in surface, text, geometryCloud, geometryPatches, functionObjectCloud, geometrySurface, and functionObjectLine.
virtual bool clear () pure virtual
Clear any files used to create the object(s)
Implemented in text, geometryCloud, geometryPatches, functionObjectCloud, cuttingPlaneFilter, geometrySurface, contourFilter, functionObjectSurface, and functionObjectLine.
Member Data Documentation
const Foam::Enum< Foam::functionObjects::runTimePostPro::geometryBase::renderModeType > renderModeTypeNames static
Names for surface shading types.
Definition at line 116 of file geometryBase.H.
const runTimePostProcessing& parent_ protected
Reference to the parent function object.
Definition at line 126 of file geometryBase.H.
word name_ protected
The surface name.
Definition at line 131 of file geometryBase.H.
bool visible_ protected
Visible flag.
Definition at line 136 of file geometryBase.H.
bool parallel_ protected
Allow parallel rendering.
Definition at line 141 of file geometryBase.H.
renderModeType renderMode_ protected
Render mode.
Definition at line 146 of file geometryBase.H.
autoPtr<Function1<scalar> > opacity_ protected
Opacity.
Definition at line 151 of file geometryBase.H.
const HashPtrTable<Function1<vector> >& colours_ protected
Reference to the colours.
Definition at line 156 of file geometryBase.H.
int debug static
Debug switch.
Definition at line 182 of file geometryBase.H.
The documentation for this class was generated from the following files:
src/functionObjects/graphics/runTimePostProcessing/geometryBase.H
src/functionObjects/graphics/runTimePostProcessing/geometryBase.C