OpenFOAM: vtkWrite Class Reference
vtkWrite Class Reference
Utility function objects
Writes fields in VTK (xml or legacy) format. Writes cell-values or point-interpolated values for volFields.
Public Member Functions
TypeName ("vtkWrite")
Runtime type information.
vtkWrite (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~vtkWrite ()=default
Destructor.
virtual bool read (const dictionary &dict)
Read the vtkWrite specification.
virtual bool execute ()
Execute - does nothing.
virtual bool write ()
Write fields.
virtual bool end ()
On end - cleanup internal allocations.
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for mesh point-motion.
template<class GeoField >
Foam::label writeVolFields (autoPtr< vtk::internalWriter > &internalWriter, UPtrList< vtk::patchWriter > &patchWriters, const fvMeshSubset &proxy, const wordHashSet &acceptField) const
template<class GeoField >
Foam::label writeVolFields (autoPtr< vtk::internalWriter > &internalWriter, const autoPtr< volPointInterpolation > &pInterp, UPtrList< vtk::patchWriter > &patchWriters, const UPtrList< PrimitivePatchInterpolation< primitivePatch >> &patchInterps, const fvMeshSubset &proxy, const wordHashSet &acceptField) const
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
Construct from Time.
virtual ~timeFunctionObject ()=default
Destructor.
const Time & time () const
Return time database.
objectRegistry & storedObjects ()
Write access to the output objects ("functionObjectObjects") registered on Time.
const objectRegistry & storedObjects () const
Const access to the output objects ("functionObjectObjects") registered on Time.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()=default
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool execute (const label subIndex)
Execute using the specified subIndex.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool filesModified () const
Did any file get changed during execution?
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
bool log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
static word outputPrefix
Directory prefix.
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
Remove specified items from "functionObjectObjects".
timeFunctionObject (const timeFunctionObject &)=delete
No copy construct.
void operator= (const timeFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Return a scoped name, e.g. used to construct local field names.
Protected Attributes inherited from timeFunctionObject
const Time & time_
Reference to the time database.
Detailed Description
Writes fields in VTK (xml or legacy) format. Writes cell-values or point-interpolated values for volFields.
Example of function object specification:
vtkWrite1
{
    type            vtkWrite;
    libs            ("libutilityFunctionObjects.so");
    writeControl    writeTime;
    writeInterval   1;
    format          binary;
    legacy          false;
    decompose       false;
    ...
    fields          (U p);
    selection
    {
        box
        {
            action  use;
            source  box;
            box     (-0.1 -0.01 -0.1) (0.1 0.30 0.1);
        }
        dome
        {
            action  add;
            source  sphere;
            origin  (-0.1 -0.01 -0.1);
            radius  0.25;
        }
        centre
        {
            action  subtract;
            source  sphere;
            origin  (-0.1 -0.01 -0.1);
            radius  0.1;
        }
        blob
        {
            action  add;
            source  surface;
            surface triSurfaceMesh;
            name    blob.stl;
        }
    }
}
Basic Usage
Property Description Required Default
type Type name: vtkWrite yes
fields Fields to output (wordRe list) yes
boundary Convert boundary fields no true
internal Convert internal fields no true
single Combine patches into a single boundary no false
interpolate Interpolate for point values no false
Output Options
Property Description Required Default
format ascii or binary format no binary
legacy Legacy VTK output no false
precision Write precision in ascii no same as IOstream
directory The output directory name no postProcessing/NAME
width Padding width for file name no 8
decompose Decompose polyhedral cells no false
writeIds Write cell,patch,proc id fields no false
Output Selection
Property Description Required Default
region Name for a single region no region0
regions List of regions (wordRe list) no
patches Limit to listed patches (wordRe list) no
selection Cell selection (topoSet actions) no empty dict
Note
The region of interest is defined by the selection dictionary as a set of actions (use,add,subtract,subset,invert). Omitting the selection dictionary is the same as specifying the conversion of all cells (in the selected regions). Omitting the patches entry is the same as specifying the conversion of all patches.
See Also
Foam::functionObjects::ensightWrite Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::timeControl
Source files
vtkWrite.H
vtkWrite.C
vtkWriteTemplates.C
Definition at line 250 of file vtkWrite.H.
Constructor & Destructor Documentation
vtkWrite (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 114 of file vtkWrite.C.
virtual ~vtkWrite () virtual default
Destructor.
Member Function Documentation
TypeName ("vtkWrite")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the vtkWrite specification.
Reimplemented from functionObject.
Definition at line 157 of file vtkWrite.C.
bool execute () virtual
Execute - does nothing.
Implements functionObject.
Definition at line 245 of file vtkWrite.C.
bool write () virtual
Write fields.
Implements functionObject.
Definition at line 251 of file vtkWrite.C.
bool end () virtual
On end - cleanup internal allocations.
Reimplemented from functionObject.
Definition at line 757 of file vtkWrite.C.
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
Reimplemented from functionObject.
Definition at line 264 of file vtkWriteUpdate.C.
void movePoints (const polyMesh & mesh) virtual
Update for mesh point-motion.
Reimplemented from functionObject.
Definition at line 270 of file vtkWriteUpdate.C.
References polyMesh::TOPO_CHANGE.
Foam::label writeVolFields (autoPtr< vtk::internalWriter > & internalWriter, UPtrList< vtk::patchWriter > & patchWriters, const fvMeshSubset & proxy, const wordHashSet & acceptField) const
Definition at line 25 of file vtkWriteTemplates.C.
References fvMeshSubset::baseMesh(), Foam::BitOps::count(), Foam::endl(), field(), objectRegistry::findObject(), fvMeshSubsetProxy::interpolate(), Log, objectRegistry::sortedNames(), autoPtr< T >::valid(), and writer< Type >::write().
Foam::label writeVolFields (autoPtr< vtk::internalWriter > & internalWriter, const autoPtr< volPointInterpolation > & pInterp, UPtrList< vtk::patchWriter > & patchWriters, const UPtrList< PrimitivePatchInterpolation< primitivePatch >> & patchInterps, const fvMeshSubset & proxy, const wordHashSet & acceptField) const
Definition at line 95 of file vtkWriteTemplates.C.
The documentation for this class was generated from the following files:
src/functionObjects/utilities/vtkWrite/vtkWrite.H
src/functionObjects/utilities/vtkWrite/vtkWrite.C
src/functionObjects/utilities/vtkWrite/vtkWriteTemplates.C
src/functionObjects/utilities/vtkWrite/vtkWriteUpdate.C