OpenFOAM: pointPatchField< T > Class Template Reference
pointPatchField< T > Class Template Reference abstract
Abstract base class for point-mesh patch fields.
Public Types
typedef Type value_type
typedef pointPatch Patch
typedef
calculatedPointPatchField
< Type > Calculated
Public Member Functions
TypeName ("pointPatchField")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, pointPatchField, pointPatch,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF),(p, iF))
declareRunTimeSelectionTable (autoPtr, pointPatchField, patchMapper,(const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m),(dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr, pointPatchField, dictionary,(const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict),(p, iF, dict))
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &)
Construct from patch and internal field.
pointPatchField (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
pointPatchField (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
pointPatchField (const pointPatchField< Type > &)
Construct as copy.
virtual autoPtr
< pointPatchField< Type > > clone () const =0
Construct and return a clone.
pointPatchField (const pointPatchField< Type > &, const DimensionedField< Type, pointMesh > &)
Construct as copy setting internal field reference.
virtual autoPtr
< pointPatchField< Type > > clone (const DimensionedField< Type, pointMesh > &iF) const =0
Construct and return a clone setting internal field reference.
virtual ~pointPatchField ()=default
Destructor.
const objectRegistry & db () const
Return local objectRegistry.
label size () const
Return size.
const pointPatch & patch () const
Return patch.
const DimensionedField< Type,
pointMesh > & internalField () const
Return dimensioned internal field reference.
const Field< Type > & primitiveField () const
Return internal field reference.
const word & patchType () const
Optional patch type.
word & patchType ()
Optional patch type.
virtual bool fixesValue () const
Return true if this patch field fixes a value.
virtual bool coupled () const
Return true if this patch field is coupled.
bool updated () const
Return true if the boundary condition has already been updated.
tmp< Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Return field created from appropriate internal field values.
template<class Type1 >
tmp< Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
Return field created from selected internal field values.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
template<class Type1 >
void addToInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &points) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF, const labelList &meshPoints) const
Given the internal field and a patch field,.
template<class Type1 >
void setInInternalField (Field< Type1 > &iF, const Field< Type1 > &pF) const
Given the internal field and a patch field,.
virtual const word & constraintType () const
Return the constraint type this pointPatchField implements.
virtual void autoMap (const pointPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const pointPatchField< Type > &, const labelList &)
Reverse map the given pointPatchField onto this pointPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void initEvaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Initialise evaluation of the patch field (do nothing)
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Evaluate the patch field.
virtual void write (Ostream &) const
Write.
virtual void operator= (const pointPatchField< Type > &)
virtual void operator+= (const pointPatchField< Type > &)
virtual void operator-= (const pointPatchField< Type > &)
virtual void operator*= (const pointPatchField< scalar > &)
virtual void operator/= (const pointPatchField< scalar > &)
virtual void operator= (const Field< Type > &)
virtual void operator+= (const Field< Type > &)
virtual void operator-= (const Field< Type > &)
virtual void operator*= (const Field< scalar > &)
virtual void operator/= (const Field< scalar > &)
virtual void operator= (const Type &)
virtual void operator+= (const Type &)
virtual void operator-= (const Type &)
virtual void operator*= (const scalar)
virtual void operator/= (const scalar)
virtual void operator== (const pointPatchField< Type > &)
virtual void operator== (const Field< Type > &)
virtual void operator== (const Type &)
void negate ()
Negate the field inplace.
template<class Type2 >
Foam::autoPtr
< Foam::pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &pf)
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF, const labelList &meshPoints) const
template<class Type1 >
Foam::tmp< Foam::Field< Type1 > > patchInternalField (const Field< Type1 > &iF) const
Static Public Member Functions
static autoPtr
< pointPatchField< Type > > New (const word &, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr
< pointPatchField< Type > > New (const word &, const word &actualPatchType, const pointPatch &, const DimensionedField< Type, pointMesh > &)
Return a pointer to a new patchField created on freestore given.
static autoPtr
< pointPatchField< Type > > New (const pointPatchField< Type > &, const pointPatch &, const DimensionedField< Type, pointMesh > &, const pointPatchFieldMapper &)
Return a pointer to a new patchField created on freestore from.
static autoPtr
< pointPatchField< Type > > New (const pointPatch &, const DimensionedField< Type, pointMesh > &, const dictionary &)
Return a pointer to a new patchField created on freestore.
template<class Type2 >
static autoPtr
< pointPatchField< Type > > NewCalculatedType (const pointPatchField< Type2 > &)
Return a pointer to a new calculatedPointPatchField created on.
static const word & calculatedType ()
Return the type of the calculated form of pointPatchField.
Static Public Attributes
static int disallowGenericPointPatchField
Debug switch to disallow the use of genericPointPatchField.
Friends
Ostream & operator (Ostream &, const pointPatchField< Type > &)
Detailed Description
template<class T>
class Foam::pointPatchField< T >
Abstract base class for point-mesh patch fields.
The base-field does not store values as they are part of the "internal field". There are derived classes to store constraint values e.g. fixedValuePointPatchField derived from the generic valuePointPatchField which ensures the values in the "internal field" are reset to the fixed-values by applying the stored values.
Source files
pointPatchField.H
pointPatchField.C
pointPatchFieldNew.C
Definition at line 56 of file pointMVCWeight.H.
Member Typedef Documentation
typedef Type value_type
Definition at line 103 of file pointPatchField.H.
typedef pointPatch Patch
Definition at line 104 of file pointPatchField.H.
typedef calculatedPointPatchField<Type> Calculated
Definition at line 105 of file pointPatchField.H.
Constructor & Destructor Documentation
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF)
Construct from patch and internal field.
Definition at line 29 of file pointPatchField.C.
pointPatchField (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 43 of file pointPatchField.C.
pointPatchField (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper &)
Construct by mapping given patchField<Type> onto a new patch.
Definition at line 58 of file pointPatchField.C.
pointPatchField (const pointPatchField< Type > & ptf)
Construct as copy.
Definition at line 74 of file pointPatchField.C.
pointPatchField (const pointPatchField< Type > & ptf, const DimensionedField< Type, pointMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 87 of file pointPatchField.C.
virtual ~pointPatchField () virtual default
Destructor.
Member Function Documentation
TypeName ("pointPatchField< T >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , pointPatchField< T > , pointPatch , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF) , (p, iF))
declareRunTimeSelectionTable (autoPtr , pointPatchField< T > , patchMapper , (const pointPatchField< Type > &ptf, const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const pointPatchFieldMapper &m) , (dynamic_cast< const pointPatchFieldType & >(ptf), p, iF, m))
declareRunTimeSelectionTable (autoPtr , pointPatchField< T > , dictionary , (const pointPatch &p, const DimensionedField< Type, pointMesh > &iF, const dictionary &dict) , (p, iF, dict))
virtual autoPtr<pointPatchField<Type> > clone () const pure virtual
Construct and return a clone.
Implemented in waveMakerPointPatchVectorField, codedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, timeVaryingMappedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, exprValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, lumpedPointDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, zeroFixedValuePointPatchField< Type >, genericPointPatchField< Type >, processorCyclicPointPatchField< Type >, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, processorPointPatchField< Type >, oscillatingVelocityPointPatchVectorField, waveDisplacementPointPatchVectorField, oscillatingDisplacementPointPatchVectorField, coupledPointPatchField< Type >, fixedValuePointPatchField< Type >, valuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, fixedValuePointPatchField< vector >, valuePointPatchField< vector >, calculatedPointPatchField< Type >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, and basicSymmetryPointPatchField< Type >.
virtual autoPtr<pointPatchField<Type> > clone (const DimensionedField< Type, pointMesh > & iF) const pure virtual
Construct and return a clone setting internal field reference.
Implemented in codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, exprValuePointPatchField< Type >, uniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, zeroFixedValuePointPatchField< Type >, timeVaryingUniformFixedValuePointPatchField< Type >, genericPointPatchField< Type >, processorCyclicPointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, processorPointPatchField< Type >, calculatedPointPatchField< Type >, fixedValuePointPatchField< Type >, valuePointPatchField< Type >, cyclicSlipPointPatchField< Type >, emptyPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, symmetryPointPatchField< Type >, wedgePointPatchField< Type >, zeroGradientPointPatchField< Type >, slipPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values)
Definition at line 87 of file pointPatchFieldNew.C.
Foam::autoPtr< Foam::pointPatchField< Type > > New (const word & patchFieldType, const word & actualPatchType, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF) static
Return a pointer to a new patchField created on freestore given.
patch and internal field (does not set the patch field values). Allows override of constraint type
Definition at line 26 of file pointPatchFieldNew.C.
References pointPatch::constraintType(), DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, FatalErrorInLookup, and p.
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatchField< Type > & ptf, const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const pointPatchFieldMapper & pfMapper) static
Return a pointer to a new patchField created on freestore from.
a given pointPatchField mapped onto a new patch
Definition at line 168 of file pointPatchFieldNew.C.
Foam::autoPtr< Foam::pointPatchField< Type > > New (const pointPatch & p, const DimensionedField< Type, pointMesh > & iF, const dictionary & dict) static
Return a pointer to a new patchField created on freestore.
from dictionary
Definition at line 99 of file pointPatchFieldNew.C.
References Foam::New().
static autoPtr<pointPatchField<Type> > NewCalculatedType (const pointPatchField< Type2 > &) static
Return a pointer to a new calculatedPointPatchField created on.
freestore without setting patchField values
const Foam::objectRegistry & db () const
Return local objectRegistry.
Definition at line 102 of file pointPatchField.C.
label size () const inline
Return size.
Definition at line 307 of file pointPatchField.H.
const pointPatch& patch () const inline
Return patch.
Definition at line 315 of file pointPatchField.H.
const DimensionedField<Type, pointMesh>& internalField () const inline
Return dimensioned internal field reference.
Definition at line 324 of file pointPatchField.H.
const Field<Type>& primitiveField () const inline
Return internal field reference.
Definition at line 332 of file pointPatchField.H.
const word& patchType () const inline
Optional patch type.
Definition at line 340 of file pointPatchField.H.
word& patchType () inline
Optional patch type.
Definition at line 348 of file pointPatchField.H.
virtual bool fixesValue () const inline virtual
Return true if this patch field fixes a value.
Reimplemented in fixedValuePointPatchField< Type >, and fixedValuePointPatchField< vector >.
Definition at line 356 of file pointPatchField.H.
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in processorCyclicPointPatchField< Type >, processorPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 364 of file pointPatchField.H.
bool updated () const inline
Return true if the boundary condition has already been updated.
Definition at line 372 of file pointPatchField.H.
Foam::tmp< Foam::Field< Type > > patchInternalField () const
Return field created from appropriate internal field values.
Definition at line 122 of file pointPatchField.C.
tmp<Field<Type1> > patchInternalField (const Field< Type1 > & iF) const
Return field created from appropriate internal field values.
given internal field reference
tmp<Field<Type1> > patchInternalField (const Field< Type1 > & iF, const labelList & meshPoints) const
Return field created from selected internal field values.
given internal field reference
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
add the patch field to the internal field
Definition at line 166 of file pointPatchField.C.
void addToInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & points) const
Given the internal field and a patch field,.
add selected elements of the patch field to the internal field
Definition at line 203 of file pointPatchField.C.
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF, const labelList & meshPoints) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 242 of file pointPatchField.C.
void setInInternalField (Field< Type1 > & iF, const Field< Type1 > & pF) const
Given the internal field and a patch field,.
set the patch field in the internal field
Definition at line 277 of file pointPatchField.C.
const Foam::word & calculatedType () static
Return the type of the calculated form of pointPatchField.
Definition at line 26 of file calculatedPointPatchField.C.
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatchField implements.
Reimplemented in cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, processorPointPatchField< Type >, cyclicPointPatchField< Type >, symmetryPlanePointPatchField< Type >, emptyPointPatchField< Type >, symmetryPointPatchField< Type >, and wedgePointPatchField< Type >.
Definition at line 463 of file pointPatchField.H.
virtual void autoMap (const pointPatchFieldMapper &) inline virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, genericPointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, and oscillatingVelocityPointPatchVectorField.
Definition at line 475 of file pointPatchField.H.
virtual void rmap (const pointPatchField< Type > & , const labelList &) inline virtual
Reverse map the given pointPatchField onto this pointPatchField.
Reimplemented in timeVaryingMappedFixedValuePointPatchField< Type >, uniformFixedValuePointPatchField< Type >, genericPointPatchField< Type >, and valuePointPatchField< Type >.
Definition at line 484 of file pointPatchField.H.
virtual void updateCoeffs () inline virtual
Update the coefficients associated with the patch field.
Sets Updated to true
Reimplemented in waveMakerPointPatchVectorField, codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, lumpedPointDisplacementPointPatchVectorField, uniformInterpolatedDisplacementPointPatchVectorField, exprValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingUniformFixedValuePointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 498 of file pointPatchField.H.
virtual void initEvaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) inline virtual
Initialise evaluation of the patch field (do nothing)
Definition at line 507 of file pointPatchField.H.
void evaluate (const Pstream::commsTypes commsType = Pstream::commsTypes::blocking) virtual
Evaluate the patch field.
Reimplemented in codedFixedValuePointPatchField< Type >, cyclicACMIPointPatchField< Type >, cyclicAMIPointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, processorPointPatchField< Type >, processorCyclicPointPatchField< Type >, cyclicPointPatchField< Type >, valuePointPatchField< Type >, valuePointPatchField< vector >, fixedNormalSlipPointPatchField< Type >, symmetryPlanePointPatchField< Type >, wedgePointPatchField< Type >, cyclicSlipPointPatchField< Type >, nonuniformTransformCyclicPointPatchField< Type >, basicSymmetryPointPatchField< Type >, and coupledPointPatchField< Type >.
Definition at line 287 of file pointPatchField.C.
References Foam::foamVersion::patch.
void write (Ostream & os) const virtual
Write.
Reimplemented in waveMakerPointPatchVectorField, codedFixedValuePointPatchField< Type >, timeVaryingMappedFixedValuePointPatchField< Type >, surfaceSlipDisplacementPointPatchVectorField, sixDoFRigidBodyDisplacementPointPatchVectorField, uniformFixedValuePointPatchField< Type >, uniformInterpolatedDisplacementPointPatchVectorField, lumpedPointDisplacementPointPatchVectorField, valuePointPatchField< Type >, valuePointPatchField< vector >, exprValuePointPatchField< Type >, uncoupledSixDoFRigidBodyDisplacementPointPatchVectorField, genericPointPatchField< Type >, angularOscillatingDisplacementPointPatchVectorField, angularOscillatingVelocityPointPatchVectorField, oscillatingVelocityPointPatchVectorField, timeVaryingUniformFixedValuePointPatchField< Type >, fixedNormalSlipPointPatchField< Type >, waveDisplacementPointPatchVectorField, and oscillatingDisplacementPointPatchVectorField.
Definition at line 109 of file pointPatchField.C.
virtual void operator= (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >.
Definition at line 533 of file pointPatchField.H.
virtual void operator+= (const pointPatchField< Type > &) inline virtual
Definition at line 534 of file pointPatchField.H.
virtual void operator-= (const pointPatchField< Type > &) inline virtual
Definition at line 535 of file pointPatchField.H.
virtual void operator*= (const pointPatchField< scalar > &) inline virtual
Definition at line 536 of file pointPatchField.H.
virtual void operator/= (const pointPatchField< scalar > &) inline virtual
Definition at line 537 of file pointPatchField.H.
virtual void operator= (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >, and fixedValuePointPatchField< Type >.
Definition at line 539 of file pointPatchField.H.
virtual void operator+= (const Field< Type > &) inline virtual
Definition at line 540 of file pointPatchField.H.
virtual void operator-= (const Field< Type > &) inline virtual
Definition at line 541 of file pointPatchField.H.
virtual void operator*= (const Field< scalar > &) inline virtual
Definition at line 543 of file pointPatchField.H.
virtual void operator/= (const Field< scalar > &) inline virtual
Definition at line 544 of file pointPatchField.H.
virtual void operator= (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >, and fixedValuePointPatchField< Type >.
Definition at line 546 of file pointPatchField.H.
virtual void operator+= (const Type &) inline virtual
Definition at line 547 of file pointPatchField.H.
virtual void operator-= (const Type &) inline virtual
Definition at line 548 of file pointPatchField.H.
virtual void operator*= (const scalar) inline virtual
Definition at line 549 of file pointPatchField.H.
virtual void operator/= (const scalar) inline virtual
Definition at line 550 of file pointPatchField.H.
virtual void operator== (const pointPatchField< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >.
Definition at line 557 of file pointPatchField.H.
virtual void operator== (const Field< Type > &) inline virtual
Reimplemented in valuePointPatchField< Type >.
Definition at line 558 of file pointPatchField.H.
virtual void operator== (const Type &) inline virtual
Reimplemented in valuePointPatchField< Type >.
Definition at line 559 of file pointPatchField.H.
void negate () inline
Negate the field inplace.
[dummy placeholder for FieldField] (2019-11)
Definition at line 581 of file pointPatchField.H.
Foam::autoPtr<Foam::pointPatchField<Type> > NewCalculatedType (const pointPatchField< Type2 > & pf)
Definition at line 85 of file calculatedPointPatchField.C.
Foam::tmp<Foam::Field<Type1> > patchInternalField (const Field< Type1 > & iF, const labelList & meshPoints) const
Definition at line 132 of file pointPatchField.C.
Foam::tmp<Foam::Field<Type1> > patchInternalField (const Field< Type1 > & iF) const
Definition at line 155 of file pointPatchField.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const pointPatchField< Type > &) friend
Member Data Documentation
int disallowGenericPointPatchField static
Debug switch to disallow the use of genericPointPatchField.
Definition at line 116 of file pointPatchField.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/interpolation/interpolationPointMVC/pointMVCWeight.H
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.H
src/OpenFOAM/fields/pointPatchFields/basic/calculated/calculatedPointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchField.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFieldNew.C
src/OpenFOAM/fields/pointPatchFields/pointPatchField/pointPatchFields.C