OpenFOAM: wallBoundedParticle Class Reference
wallBoundedParticle Class Reference
Particle class that tracks on triangles of boundary faces. Use trackToEdge similar to trackToFace on particle.
Classes
class iNew
Factory class to read-construct particles used for.
class trackingData
Class used to pass tracking data to the trackToFace function.
Public Member Functions
wallBoundedParticle (const polyMesh &c, const point &position, const label celli, const label tetFacei, const label tetPti, const label meshEdgeStart, const label diagEdge)
Construct from components.
wallBoundedParticle (const polyMesh &c, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
wallBoundedParticle (const wallBoundedParticle &p)
Construct copy.
autoPtr< particle > clone () const
Construct and return a clone.
label meshEdgeStart () const
-1 or label of mesh edge
label diagEdge () const
-1 or diagonal edge
template<class TrackCloudType >
scalar trackToEdge (TrackCloudType &cloud, trackingData &td, const vector &endPosition)
Equivalent of trackToFace.
template<class TrackCloudType >
void patchInteraction (TrackCloudType &cloud, trackingData &td, const scalar trackFraction)
Do all patch interaction.
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &cloud, trackingData &td)
Overridable function to handle the particle hitting a processorPatch.
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &cloud, trackingData &td)
Overridable function to handle the particle hitting a wallPatch.
InfoProxy< wallBoundedParticle > info () const
Return info proxy.
template<class TrackCloudType >
Foam::scalar trackToEdge (TrackCloudType &cloud, trackingData &td, const vector &endPosition)
template<class TrackCloudType >
void readFields (TrackCloudType &c)
template<class TrackCloudType >
void writeFields (const TrackCloudType &c)
Public Member Functions inherited from particle< Type >
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label celli=-1)
Construct from a position and a cell.
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const bool doLocate=true)
Construct from position components.
particle (const polyMesh &mesh, Istream &, bool readFields=true, bool newFormat=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with reference to a new mesh.
virtual ~particle ()=default
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const barycentric & coordinates () const
Return current particle coordinates.
label cell () const
Return current cell particle is in.
label & cell ()
Return current cell particle is in for manipulation.
label tetFace () const
Return current tet face particle is in.
label & tetFace ()
Return current tet face particle is in for manipulation.
label tetPt () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in for manipulation.
label face () const
Return current face particle is on otherwise -1.
label & face ()
Return current face particle is on for manipulation.
scalar stepFraction () const
Return the fraction of time-step completed.
scalar & stepFraction ()
Return the fraction of time-step completed.
label origProc () const
Return the originating processor ID.
label & origProc ()
Return the originating processor ID.
label origId () const
Return the particle ID on the originating processor.
label & origId ()
Return the particle ID on the originating processor.
Pair< scalar > stepFractionSpan () const
Return the step fraction change within the overall time-step.
scalar currentTimeFraction () const
Return the current fraction within the timestep. This differs.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
barycentricTensor currentTetTransform () const
Return the current tet transformation tensor.
vector normal () const
The (unit) normal of the tri on tetFacei_ for the current tet.
bool onFace () const
Is the particle on a face?
bool onInternalFace () const
Is the particle on an internal face?
bool onBoundaryFace () const
Is the particle on a boundary face?
label patch () const
Return the index of patch that the particle is on.
vector position () const
Return current particle position.
scalar track (const vector &displacement, const scalar fraction)
Track along the displacement for a given fraction of the overall.
scalar trackToFace (const vector &displacement, const scalar fraction)
As particle::track, but also stops on internal faces.
scalar trackToTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToFace, but also stops on tet triangles. On.
scalar trackToStationaryTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for stationary meshes.
scalar trackToMovingTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for moving meshes.
template<class TrackCloudType >
void hitFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
Hit the current face. If the current face is internal than this.
template<class TrackCloudType >
void trackToAndHitFace (const vector &direction, const scalar fraction, TrackCloudType &cloud, trackingData &td)
Convenience function. Combines trackToFace and hitFace.
vector deviationFromMeshCentre () const
Get the displacement from the mesh centre. Used to correct the.
void patchData (vector &n, vector &U) const
Get the normal and velocity of the current patch location.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
void prepareForParallelTransfer ()
Convert global addressing to the processor patch local equivalents.
void correctAfterParallelTransfer (const label patchi, trackingData &td)
Convert processor patch addressing to the global equivalents.
void prepareForInteractionListReferral (const vectorTensorTransform &transform)
Break the topology and store the particle position so that the.
void correctAfterInteractionListReferral (const label celli)
Correct the topology after referral. The particle may still be.
label procTetPt (const polyMesh &procMesh, const label procCell, const label procTetFace) const
Return the tet point appropriate for decomposition or reconstruction.
void autoMap (const vector &position, const mapPolyMesh &mapper)
Map after a topology change.
void relocate (const point &position, const label celli=-1)
Set the addressing based on the provided position.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
Write individual particle properties to stream.
void writeCoordinates (Ostream &os) const
Write the particle barycentric coordinates and cell info.
virtual void writePosition (Ostream &os) const
Write the particle position and cell id.
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &)
Read.
template<class CloudType >
static void writeFields (const CloudType &)
Write.
Static Public Member Functions inherited from particle< Type >
static string propertyList ()
template<class Type >
static void writePropertyName (Ostream &os, const word &name, const word &delim)
Write the name representation to stream.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Type &value, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property to stream, optionally filtered based on its name.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Field< Type > &values, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property list to stream, optionally filtered based on its name.
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
Read the fields associated with the owner cloud.
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
Write the fields associated with the owner cloud.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields_
Size in bytes of the fields.
Static Public Attributes inherited from particle< Type >
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provide unique ID.
static bool writeLagrangianCoordinates = true
Write particle coordinates file (v1712 and later) Default is true.
static bool writeLagrangianPositions
Write particle positions file (v1706 format and earlier) Default is true (disable in etc/controlDict)
Protected Member Functions
edge currentEdge () const
Construct current edge.
void crossEdgeConnectedFace (const label &celli, label &tetFacei, label &tetPti, const edge &e)
Replacement for particle::crossEdgeConnectedFace that avoids bombing.
void crossEdgeConnectedFace (const edge &meshEdge)
Cross mesh edge into different face on same cell.
void crossDiagonalEdge ()
Cross diagonal edge into different triangle on same face,cell.
scalar trackFaceTri (const vector &n, const vector &endPosition, label &)
Track through single triangle.
bool isTriAlongTrack (const vector &n, const point &endPosition) const
Is current triangle in the track direction.
Protected Member Functions inherited from particle< Type >
template<class TrackCloudType >
bool hitPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a patch.
template<class TrackCloudType >
void hitWedgePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackCloudType >
void hitSymmetryPlanePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitSymmetryPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a symmetryPatch.
template<class TrackCloudType >
void hitCyclicPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackCloudType >
void hitCyclicAMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackCloudType >
void hitCyclicACMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a processorPatch.
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wallPatch.
Protected Attributes
point localPosition_
Particle position is updated locally as opposed to via track.
label meshEdgeStart_
Particle is on mesh edge:
label diagEdge_
Particle is on diagonal edge:
Friends
Ostream & operator<< (Ostream &, const wallBoundedParticle &)
Ostream & operator<< (Ostream &, const InfoProxy< wallBoundedParticle > &)
Detailed Description
Particle class that tracks on triangles of boundary faces. Use trackToEdge similar to trackToFace on particle.
Source files
wallBoundedParticle.H
wallBoundedParticle.C
wallBoundedParticleTemplates.C
Definition at line 59 of file wallBoundedParticle.H.
Constructor & Destructor Documentation
wallBoundedParticle (const polyMesh & c, const point & position, const label celli, const label tetFacei, const label tetPti, const label meshEdgeStart, const label diagEdge)
Construct from components.
Definition at line 405 of file wallBoundedParticle.C.
wallBoundedParticle (const polyMesh & c, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 423 of file wallBoundedParticle.C.
wallBoundedParticle (const wallBoundedParticle & p)
Construct copy.
Definition at line 461 of file wallBoundedParticle.C.
Member Function Documentation
Foam::edge currentEdge () const protected
Construct current edge.
Definition at line 34 of file wallBoundedParticle.C.
References Foam::abort(), wallBoundedParticle::diagEdge_, f(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, wallBoundedParticle::info(), particle< Type >::mesh(), wallBoundedParticle::meshEdgeStart_, face::nextLabel(), UList< T >::size(), polyMesh::tetBasePtIs(), and particle< Type >::tetFace().
void crossEdgeConnectedFace (const label & celli, label & tetFacei, label & tetPti, const edge & e) protected
Replacement for particle::crossEdgeConnectedFace that avoids bombing.
out on invalid tet decomposition (tetBasePtIs = -1)
Definition at line 76 of file wallBoundedParticle.C.
void crossEdgeConnectedFace (const edge & meshEdge) protected
Cross mesh edge into different face on same cell.
Definition at line 183 of file wallBoundedParticle.C.
void crossDiagonalEdge () protected
Cross diagonal edge into different triangle on same face,cell.
Definition at line 232 of file wallBoundedParticle.C.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Foam::scalar trackFaceTri (const vector & n, const vector & endPosition, label & minEdgei) protected
Track through single triangle.
Definition at line 279 of file wallBoundedParticle.C.
bool isTriAlongTrack (const vector & n, const point & endPosition) const protected
Is current triangle in the track direction.
Definition at line 358 of file wallBoundedParticle.C.
autoPtr<particle> clone () const inline virtual
Construct and return a clone.
Reimplemented from particle< Type >.
Reimplemented in wallBoundedStreamLineParticle.
Definition at line 211 of file wallBoundedParticle.H.
References wallBoundedParticle::meshEdgeStart_.
label meshEdgeStart () const inline
-1 or label of mesh edge
Definition at line 252 of file wallBoundedParticle.H.
label diagEdge () const inline
-1 or diagonal edge
Definition at line 260 of file wallBoundedParticle.H.
scalar trackToEdge (TrackCloudType & cloud, trackingData & td, const vector & endPosition)
Equivalent of trackToFace.
Referenced by wallBoundedStreamLineParticle::move().
void patchInteraction (TrackCloudType & cloud, trackingData & td, const scalar trackFraction)
Do all patch interaction.
Definition at line 28 of file wallBoundedParticleTemplates.C.
References polyMesh::boundaryMesh(), particle< Type >::face(), primitiveMesh::isInternalFace(), particle< Type >::trackingData::keepParticle, particle< Type >::mesh(), p, and particle< Type >::patch().
void hitProcessorPatch (TrackCloudType & cloud, trackingData & td)
Overridable function to handle the particle hitting a processorPatch.
Definition at line 375 of file wallBoundedParticleTemplates.C.
void hitWallPatch (TrackCloudType & cloud, trackingData & td)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 404 of file wallBoundedParticleTemplates.C.
InfoProxy<wallBoundedParticle> info () const inline
Return info proxy.
Used to print particle information to a stream
Definition at line 322 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::currentEdge().
static void readFields (CloudType &) static
Read.
static void writeFields (const CloudType &) static
Write.
Foam::scalar trackToEdge (TrackCloudType & cloud, trackingData & td, const vector & endPosition)
Definition at line 73 of file wallBoundedParticleTemplates.C.
void readFields (TrackCloudType & c)
Definition at line 412 of file wallBoundedParticleTemplates.C.
void writeFields (const TrackCloudType & c)
Definition at line 452 of file wallBoundedParticleTemplates.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const wallBoundedParticle &) friend
Ostream& operator<< (Ostream & , const InfoProxy< wallBoundedParticle > &) friend
Member Data Documentation
point localPosition_ protected
Particle position is updated locally as opposed to via track.
functions of the base Foam::particle class
Definition at line 101 of file wallBoundedParticle.H.
Referenced by wallBoundedStreamLineParticle::move().
label meshEdgeStart_ protected
Particle is on mesh edge:
const face& f = mesh.faces()[tetFace()] const edge e(f[meshEdgeStart_], f.nextLabel(meshEdgeStart_)); Note that this real edge is also one of the edges of the face-triangle (from tetFace()+tetPt()).
Definition at line 112 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::clone(), and wallBoundedParticle::currentEdge().
label diagEdge_ protected
Particle is on diagonal edge:
const face& f = mesh.faces()[tetFace()] label faceBasePti = mesh.tetBasePtIs()[facei]; label diagPti = (faceBasePti+diagEdge_)f.size(); const edge e(f[faceBasePti], f[diagPti]);
Definition at line 122 of file wallBoundedParticle.H.
Referenced by wallBoundedParticle::currentEdge().
const std::size_t sizeofFields_ static
Size in bytes of the fields.
Definition at line 173 of file wallBoundedParticle.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticle.H
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticle.C
src/functionObjects/field/wallBoundedStreamLine/wallBoundedParticleTemplates.C