OpenFOAM: fixedTrim Class Reference
fixedTrim Class Reference
Fixed trim coefficients.
Public Member Functions
TypeName ("fixedTrim")
Run-time type information.
fixedTrim (const fv::rotorDiskSource &rotor, const dictionary &dict)
Constructor.
virtual ~fixedTrim ()=default
Destructor.
void read (const dictionary &dict)
Read.
virtual tmp< scalarField > thetag () const
Return the geometric angle of attack [rad].
virtual void correct (const vectorField &U, vectorField &force)
Correct the model.
virtual void correct (const volScalarField rho, const vectorField &U, vectorField &force)
Correct the model for compressible flow.
Public Member Functions inherited from trimModel
TypeName ("trimModel")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, trimModel, dictionary,(const fv::rotorDiskSource &rotor, const dictionary &dict),(rotor, dict))
trimModel (const fv::rotorDiskSource &rotor, const dictionary &dict, const word &name)
Construct from components.
virtual ~trimModel ()=default
Destructor.
Protected Attributes
scalarField thetag_
Geometric angle of attack [rad].
Protected Attributes inherited from trimModel
const fv::rotorDiskSource & rotor_
Reference to the rotor source model.
const word name_
Name of model.
dictionary coeffs_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from trimModel
static autoPtr< trimModel > New (const fv::rotorDiskSource &rotor, const dictionary &dict)
Return a reference to the selected trim model.
Detailed Description
Fixed trim coefficients.
Source files
fixedTrim.H
fixedTrim.C
Definition at line 46 of file fixedTrim.H.
Constructor & Destructor Documentation
fixedTrim (const fv::rotorDiskSource & rotor, const dictionary & dict)
Constructor.
Definition at line 41 of file fixedTrim.C.
virtual ~fixedTrim () virtual default
Destructor.
Member Function Documentation
TypeName ("fixedTrim")
Run-time type information.
void read (const dictionary & dict) virtual
Read.
Reimplemented from trimModel.
Definition at line 55 of file fixedTrim.C.
References Foam::read().
Foam::tmp< Foam::scalarField > thetag () const virtual
Return the geometric angle of attack [rad].
Implements trimModel.
Definition at line 72 of file fixedTrim.C.
References Foam::cos(), i, psi, and Foam::sin().
void correct (const vectorField & U, vectorField & force) virtual
Correct the model.
Implements trimModel.
Definition at line 79 of file fixedTrim.C.
void correct (const volScalarField rho, const vectorField & U, vectorField & force) virtual
Correct the model for compressible flow.
Implements trimModel.
Definition at line 87 of file fixedTrim.C.
Member Data Documentation
scalarField thetag_ protected
Geometric angle of attack [rad].
Definition at line 57 of file fixedTrim.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/derived/rotorDiskSource/trimModel/fixed/fixedTrim.H
src/fvOptions/sources/derived/rotorDiskSource/trimModel/fixed/fixedTrim.C