OpenFOAM: Reaction< ReactionThermo > Class Template Reference
Reaction< ReactionThermo > Class Template Reference
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
Classes
struct specieCoeffs
Class to hold the specie index and its coefficients in the.
Public Member Functions
TypeName ("Reaction")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, Reaction, dictionary,(const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict),(species, thermoDatabase, dict))
Reaction (const speciesTable &species, const List< specieCoeffs > &lhs, const List< specieCoeffs > &rhs, const HashPtrTable< ReactionThermo > &thermoDatabase, bool initReactionThermo=true)
Construct from components.
Reaction (const Reaction< ReactionThermo > &, const speciesTable &species)
Construct as copy given new speciesTable.
Reaction (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict, bool initReactionThermo=true)
Construct from dictionary.
virtual autoPtr< Reaction
< ReactionThermo > > clone () const
Construct and return a clone.
virtual autoPtr< Reaction
< ReactionThermo > > clone (const speciesTable &species) const
Construct and return a clone with new speciesTable.
virtual ~Reaction ()=default
Destructor.
const word & name () const
const List< specieCoeffs > & lhs () const
const List< specieCoeffs > & rhs () const
virtual const List
< specieCoeffs > & grhs () const
virtual const List
< specieCoeffs > & glhs () const
const speciesTable & species () const
Access to specie list.
virtual const speciesTable & gasSpecies () const
Access to gas specie list.
void setLRhs (Istream &, const speciesTable &, List< specieCoeffs > &lhs, List< specieCoeffs > &rhs)
Construct the left- and right-hand-side reaction coefficients.
virtual scalar kf (const scalar p, const scalar T, const scalarField &c) const
Forward rate constant.
virtual scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant from the given forward rate constant.
virtual scalar kr (const scalar p, const scalar T, const scalarField &c) const
Reverse rate constant.
virtual void write (Ostream &) const
Write.
Static Public Member Functions
static autoPtr< Reaction
< ReactionThermo > > New (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict)
Return a pointer to new patchField created on freestore from dict.
Static Public Attributes
static label nUnNamedReactions = 0
Number of un-named reactions.
Protected Member Functions
void reactionStrLeft (OStringStream &reaction) const
Return string representation of the left of the reaction.
void reactionStrRight (OStringStream &reaction) const
Return string representation of the right of the reaction.
Friends
Ostream & operator (Ostream &, const Reaction< ReactionThermo > &)
Detailed Description
template<class ReactionThermo>
class Foam::Reaction< ReactionThermo >
Simple extension of ReactionThermo to handle reaction kinetics in addition to the equilibrium thermodynamics already handled.
Source files
Reaction.H
ReactionI.H
Reaction.C
Definition at line 52 of file Reaction.H.
Constructor & Destructor Documentation
Reaction (const speciesTable & species, const List< specieCoeffs > & lhs, const List< specieCoeffs > & rhs, const HashPtrTable< ReactionThermo > & thermoDatabase, bool initReactionThermo = true)
Construct from components.
Definition at line 150 of file Reaction.C.
Reaction (const Reaction< ReactionThermo > & r, const speciesTable & species)
Construct as copy given new speciesTable.
Definition at line 173 of file Reaction.C.
Reaction (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict, bool initReactionThermo = true)
Construct from dictionary.
NOTE: initReactionThermo is used by solidReaction where there is no need of setting a lhs - rhs thermo type for each reaction. This is needed for mechanism with reversible reactions
Definition at line 315 of file Reaction.C.
virtual ~Reaction () virtual default
Destructor.
Member Function Documentation
void reactionStrLeft (OStringStream & reaction) const protected
Return string representation of the left of the reaction.
Definition at line 34 of file Reaction.C.
References i, and Foam::mag().
void reactionStrRight (OStringStream & reaction) const protected
Return string representation of the right of the reaction.
Definition at line 59 of file Reaction.C.
TypeName ("Reaction< ReactionThermo >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , Reaction< ReactionThermo > , dictionary , (const speciesTable &species, const HashPtrTable< ReactionThermo > &thermoDatabase, const dictionary &dict) , (species, thermoDatabase, dict))
virtual autoPtr<Reaction<ReactionThermo> > clone () const inline virtual
Construct and return a clone.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 247 of file Reaction.H.
virtual autoPtr<Reaction<ReactionThermo> > clone (const speciesTable & species) const inline virtual
Construct and return a clone with new speciesTable.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 256 of file Reaction.H.
Foam::autoPtr< Foam::Reaction< ReactionThermo > > New (const speciesTable & species, const HashPtrTable< ReactionThermo > & thermoDatabase, const dictionary & dict) static
Return a pointer to new patchField created on freestore from dict.
Definition at line 346 of file Reaction.C.
References dict, Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, and dictionary::get().
const word & name () const inline
Definition at line 31 of file ReactionI.H.
const List< typename Reaction< ReactionThermo >::specieCoeffs > & lhs () const inline
Definition at line 39 of file ReactionI.H.
Referenced by singleStepReactingMixture< ThermoType >::calculateqFuel(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), DAC< CompType, ThermoType >::reduceMechanism(), and DRGEP< CompType, ThermoType >::reduceMechanism().
const List< typename Reaction< ReactionThermo >::specieCoeffs > & rhs () const inline
Definition at line 47 of file ReactionI.H.
Referenced by singleStepReactingMixture< ThermoType >::calculateqFuel(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), DAC< CompType, ThermoType >::reduceMechanism(), and DRGEP< CompType, ThermoType >::reduceMechanism().
const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & grhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 447 of file Reaction.C.
Referenced by pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega().
const Foam::List< typename Foam::Reaction< ReactionThermo >::specieCoeffs > & glhs () const virtual
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 438 of file Reaction.C.
const Foam::speciesTable & species () const
Access to specie list.
Definition at line 422 of file Reaction.C.
const Foam::speciesTable & gasSpecies () const virtual
Access to gas specie list.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 429 of file Reaction.C.
void setLRhs (Istream & is, const speciesTable & species, List< specieCoeffs > & lhs, List< specieCoeffs > & rhs)
Construct the left- and right-hand-side reaction coefficients.
Definition at line 232 of file Reaction.C.
Foam::scalar kf (const scalar p, const scalar T, const scalarField & c) const virtual
Forward rate constant.
Definition at line 386 of file Reaction.C.
Foam::scalar kr (const scalar kfwd, const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant from the given forward rate constant.
Definition at line 398 of file Reaction.C.
Foam::scalar kr (const scalar p, const scalar T, const scalarField & c) const virtual
Reverse rate constant.
Note this evaluates the forward rate constant and divides by the equilibrium constant
Definition at line 411 of file Reaction.C.
void write (Ostream & os) const virtual
Write.
Reimplemented in solidReaction< ReactionThermo >.
Definition at line 377 of file Reaction.C.
Referenced by ReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const Reaction< ReactionThermo > &) friend
Member Data Documentation
Foam::label nUnNamedReactions = 0 static
Number of un-named reactions.
Definition at line 89 of file Reaction.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.H
src/thermophysicalModels/specie/reaction/Reactions/Reaction/Reaction.C
src/thermophysicalModels/specie/reaction/Reactions/Reaction/ReactionI.H