OpenFOAM: ignition Class Reference
ignition Class Reference
Foam::ignition.
Public Member Functions
ignition (const dictionary &, const Time &, const fvMesh &)
Construct from Istream and database.
ignition (const dictionary &, const engineTime &, const fvMesh &)
Construct from Istream and engineTime.
const PtrList< ignitionSite > & sites ()
Return the set of ignition sites.
bool ignite () const
bool igniting () const
Are any of the ignition site currently igniting.
bool ignited () const
Has the mixture been ignited?
Detailed Description
Foam::ignition.
Source files
ignition.H
ignition.C
ignitionIO.C
Definition at line 50 of file ignition.H.
Constructor & Destructor Documentation
ignition (const dictionary & combustionProperties, const Time & db, const fvMesh & mesh)
Construct from Istream and database.
Definition at line 27 of file ignitionIO.C.
References Foam::endl(), and Foam::Info.
ignition (const dictionary & combustionProperties, const engineTime & edb, const fvMesh & mesh)
Construct from Istream and engineTime.
Definition at line 53 of file ignitionIO.C.
References Foam::endl(), and Foam::Info.
Member Function Documentation
const PtrList<ignitionSite>& sites () inline
Return the set of ignition sites.
Definition at line 94 of file ignition.H.
bool ignite () const inline
Definition at line 102 of file ignition.H.
Referenced by ignition::igniting().
bool igniting () const
Are any of the ignition site currently igniting.
Definition at line 27 of file ignition.C.
References forAll, i, and ignition::ignite().
bool ignited () const
Has the mixture been ignited?
Definition at line 48 of file ignition.C.
The documentation for this class was generated from the following files:
src/engine/ignition/ignition.H
src/engine/ignition/ignition.C
src/engine/ignition/ignitionIO.C