OpenFOAM: ThermoParcel< ParcelType >::trackingData Class Reference
ThermoParcel< ParcelType >::trackingData Class Reference
Public Types
typedef
ParcelType::trackingData::trackPart trackPart
Public Member Functions
template<class TrackCloudType >
trackingData (const TrackCloudType &cloud, trackPart part=ParcelType::trackingData::tpLinearTrack)
Construct from components.
const volScalarField & Cp () const
Return access to the locally stored carrier Cp field.
const volScalarField & kappa () const
Return access to the locally stored carrier kappa field.
const interpolation< scalar > & TInterp () const
Return const access to the interpolator for continuous.
const interpolation< scalar > & CpInterp () const
Return const access to the interpolator for continuous.
const interpolation< scalar > & kappaInterp () const
Return const access to the interpolator for continuous.
const interpolation< scalar > & GInterp () const
Return const access to the interpolator for continuous.
scalar Tc () const
Return the continuous phase temperature.
scalar & Tc ()
Access the continuous phase temperature.
scalar Cpc () const
Return the continuous phase specific heat capacity.
scalar & Cpc ()
Access the continuous phase specific heat capacity.
Detailed Description
template<class ParcelType>
class Foam::ThermoParcel< ParcelType >::trackingData
Definition at line 187 of file ThermoParcel.H.
Member Typedef Documentation
typedef ParcelType::trackingData::trackPart trackPart
Definition at line 248 of file ThermoParcel.H.
Constructor & Destructor Documentation
trackingData (const TrackCloudType & cloud, trackPart part = ParcelType::trackingData::tpLinearTrack) inline
Construct from components.
Definition at line 24 of file ThermoParcelTrackingDataI.H.
Member Function Documentation
const Foam::volScalarField & Cp () const inline
Return access to the locally stored carrier Cp field.
Definition at line 77 of file ThermoParcelTrackingDataI.H.
const Foam::volScalarField & kappa () const inline
Return access to the locally stored carrier kappa field.
Definition at line 85 of file ThermoParcelTrackingDataI.H.
References ThermoParcel< ParcelType >::Cp_.
const Foam::interpolation< Foam::scalar > & TInterp () const inline
Return const access to the interpolator for continuous.
phase temperature field
Definition at line 93 of file ThermoParcelTrackingDataI.H.
Referenced by ThermoParcel< ParcelType >::setCellValues().
const Foam::interpolation< Foam::scalar > & CpInterp () const inline
Return const access to the interpolator for continuous.
phase specific heat capacity field
Definition at line 101 of file ThermoParcelTrackingDataI.H.
Referenced by ThermoParcel< ParcelType >::setCellValues().
const Foam::interpolation< Foam::scalar > & kappaInterp () const inline
Return const access to the interpolator for continuous.
phase thermal conductivity field
Definition at line 109 of file ThermoParcelTrackingDataI.H.
const Foam::interpolation< Foam::scalar > & GInterp () const inline
Return const access to the interpolator for continuous.
radiation field
Definition at line 117 of file ThermoParcelTrackingDataI.H.
Foam::scalar Tc () const inline
Return the continuous phase temperature.
Definition at line 131 of file ThermoParcelTrackingDataI.H.
Referenced by ThermoParcel< ParcelType >::setCellValues().
Foam::scalar & Tc () inline
Access the continuous phase temperature.
Definition at line 138 of file ThermoParcelTrackingDataI.H.
Foam::scalar Cpc () const inline
Return the continuous phase specific heat capacity.
Definition at line 145 of file ThermoParcelTrackingDataI.H.
Referenced by ThermoParcel< ParcelType >::setCellValues().
Foam::scalar & Cpc () inline
Access the continuous phase specific heat capacity.
Definition at line 152 of file ThermoParcelTrackingDataI.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelTrackingDataI.H