OpenFOAM: gradScheme< Type > Class Template Reference
gradScheme< Type > Class Template Reference abstract
Abstract base class for gradient schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< typename outerProduct
< vector, Type >::type,
fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const =0
Calculate and return the grad of the given field.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type>
class Foam::fv::gradScheme< Type >
Abstract base class for gradient schemes.
Source files
gradScheme.H
gradScheme.C
Definition at line 58 of file gradScheme.H.
Constructor & Destructor Documentation
gradScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 105 of file gradScheme.H.
virtual ~gradScheme () virtual default
Destructor.
Member Function Documentation
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , gradScheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
Foam::tmp< Foam::fv::gradScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new gradScheme created on freestore.
Definition at line 30 of file gradScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by Foam::fvc::grad().
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 134 of file gradScheme.H.
Referenced by gaussGrad< Type >::gaussGrad().
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name) const pure virtual
Calculate and return the grad of the given field.
Used by grad either to recalculate the cached gradient when it is out of date with respect to the field or when it is not cached.
Implemented in cellLimitedGrad< Type, Limiter >, gaussGrad< Type >, LeastSquaresGrad< Type, Stencil >, faceLimitedGrad< Type >, faceMDLimitedGrad< Type >, cellMDLimitedGrad< Type >, leastSquaresGrad< Type >, and fourthGrad< Type >.
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > grad (const GeometricField< Type, fvPatchField, volMesh > & , const word & name) const
Calculate and return the grad of the given field.
which may have been cached
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
with the default name which may have been cached
tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
with the default name which may have been cached
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/gradSchemes/gradScheme/gradScheme.H
src/finiteVolume/finiteVolume/gradSchemes/gradScheme/gradScheme.C