OpenFOAM: FieldMapper Class Reference
FieldMapper Class Reference abstract
Abstract base class to hold the Field mapping addressing and weights.
Public Member Functions
FieldMapper ()
Null constructor.
virtual ~FieldMapper ()=default
Destructor.
virtual label size () const =0
virtual bool direct () const =0
virtual bool distributed () const
virtual const mapDistributeBase & distributeMap () const
virtual bool hasUnmapped () const =0
Are there unmapped values? I.e. do all size() elements get.
virtual const labelUList & directAddressing () const
virtual const labelListList & addressing () const
virtual const scalarListList & weights () const
template<class Type >
tmp< Field< Type > > operator() (const Field< Type > &f) const
Detailed Description
Abstract base class to hold the Field mapping addressing and weights.
Definition at line 43 of file FieldMapper.H.
Constructor & Destructor Documentation
FieldMapper () inline
Null constructor.
Definition at line 53 of file FieldMapper.H.
virtual ~FieldMapper () virtual default
Destructor.
Member Function Documentation
virtual label size () const pure virtual
Implemented in meshToMesh0::patchFieldInterpolator, faFieldDecomposer::processorEdgePatchFieldDecomposer, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, faAreaMapper, pointPatchMapper, faceMapper, cellMapper, pointMapper, fvPatchMapper, faPatchMapper, fvSurfaceMapper, faFieldDecomposer::processorAreaPatchFieldDecomposer, singleCellFvMesh::agglomPatchFieldMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, faEdgeMapper, faFieldReconstructor::faPatchFieldReconstructor, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, distributedWeightedFvPatchFieldMapper, faFieldDecomposer::patchFieldDecomposer, pointFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, distributedUnallocatedDirectFvPatchFieldMapper, distributedUnallocatedDirectFieldMapper, and directFieldMapper.
virtual bool direct () const pure virtual
Implemented in meshToMesh0::patchFieldInterpolator, faFieldDecomposer::processorEdgePatchFieldDecomposer, faAreaMapper, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, faceMapper, fvPatchMapper, cellMapper, faPatchMapper, fvSurfaceMapper, pointMapper, faFieldDecomposer::processorAreaPatchFieldDecomposer, faEdgeMapper, singleCellFvMesh::agglomPatchFieldMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, faFieldReconstructor::faPatchFieldReconstructor, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, distributedWeightedFvPatchFieldMapper, faFieldDecomposer::patchFieldDecomposer, pointFieldDecomposer::patchFieldDecomposer, distributedUnallocatedDirectFvPatchFieldMapper, fvFieldDecomposer::patchFieldDecomposer, distributedUnallocatedDirectFieldMapper, directFvPatchFieldMapper, directPointPatchFieldMapper, and directFieldMapper.
virtual bool distributed () const inline virtual
Reimplemented in distributedWeightedFvPatchFieldMapper, distributedUnallocatedDirectFvPatchFieldMapper, and distributedUnallocatedDirectFieldMapper.
Definition at line 69 of file FieldMapper.H.
virtual const mapDistributeBase& distributeMap () const inline virtual
Reimplemented in distributedWeightedFvPatchFieldMapper, distributedUnallocatedDirectFvPatchFieldMapper, and distributedUnallocatedDirectFieldMapper.
Definition at line 74 of file FieldMapper.H.
virtual bool hasUnmapped () const pure virtual
Are there unmapped values? I.e. do all size() elements get.
get value
Implemented in meshToMesh0::patchFieldInterpolator, faFieldDecomposer::processorEdgePatchFieldDecomposer, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, faAreaMapper, faceMapper, pointMapper, fvPatchMapper, fvSurfaceMapper, cellMapper, faPatchMapper, pointPatchMapper, faFieldDecomposer::processorAreaPatchFieldDecomposer, faEdgeMapper, singleCellFvMesh::agglomPatchFieldMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, faFieldReconstructor::faPatchFieldReconstructor, distributedWeightedFvPatchFieldMapper, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, distributedUnallocatedDirectFvPatchFieldMapper, faFieldDecomposer::patchFieldDecomposer, distributedUnallocatedDirectFieldMapper, pointFieldDecomposer::patchFieldDecomposer, fvFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, directPointPatchFieldMapper, and directFieldMapper.
virtual const labelUList& directAddressing () const inline virtual
Reimplemented in meshToMesh0::patchFieldInterpolator, faAreaMapper, pointPatchMapper, faceMapper, pointMapper, fvPatchMapper, fvSurfaceMapper, cellMapper, faPatchMapper, faEdgeMapper, fvFieldDecomposer::processorVolPatchFieldDecomposer, faFieldReconstructor::faPatchFieldReconstructor, fvFieldReconstructor::fvPatchFieldReconstructor, pointFieldReconstructor::pointPatchFieldReconstructor, distributedUnallocatedDirectFvPatchFieldMapper, faFieldDecomposer::patchFieldDecomposer, distributedUnallocatedDirectFieldMapper, pointFieldDecomposer::patchFieldDecomposer, directFvPatchFieldMapper, fvFieldDecomposer::patchFieldDecomposer, directPointPatchFieldMapper, and directFieldMapper.
Definition at line 90 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UList< label >::null().
virtual const labelListList& addressing () const inline virtual
Reimplemented in faFieldDecomposer::processorEdgePatchFieldDecomposer, faAreaMapper, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, faceMapper, pointMapper, fvPatchMapper, fvSurfaceMapper, cellMapper, faPatchMapper, faEdgeMapper, faFieldDecomposer::processorAreaPatchFieldDecomposer, singleCellFvMesh::agglomPatchFieldMapper, and distributedWeightedFvPatchFieldMapper.
Definition at line 99 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< labelList >::null().
virtual const scalarListList& weights () const inline virtual
Reimplemented in faFieldDecomposer::processorEdgePatchFieldDecomposer, faAreaMapper, fvFieldDecomposer::processorSurfacePatchFieldDecomposer, pointPatchMapper, faceMapper, pointMapper, fvPatchMapper, fvSurfaceMapper, cellMapper, faPatchMapper, faEdgeMapper, faFieldDecomposer::processorAreaPatchFieldDecomposer, singleCellFvMesh::agglomPatchFieldMapper, and distributedWeightedFvPatchFieldMapper.
Definition at line 108 of file FieldMapper.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and List< scalarList >::null().
tmp<Field<Type> > operator() (const Field< Type > & f) const inline
Definition at line 121 of file FieldMapper.H.
References Foam::New().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/Field/FieldMapper.H