OpenFOAM: primitiveMesh Class Reference
primitiveMesh Class Reference abstract
Cell-face mesh analysis engine.
Public Member Functions
ClassName ("primitiveMesh")
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
virtual ~primitiveMesh ()
Destructor.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList &cells)
Reset this primitiveMesh given the primitive array sizes and cells.
label nPoints () const
Number of mesh points.
label nEdges () const
Number of mesh edges.
label nFaces () const
Number of mesh faces.
label nCells () const
Number of mesh cells.
label nInternalFaces () const
Number of internal faces.
label nBoundaryFaces () const
Number of boundary faces (== nFaces - nInternalFaces)
label nInternalPoints () const
Points not on boundary.
label nInternal0Edges () const
Internal edges (i.e. not on boundary face) using no boundary point.
label nInternal1Edges () const
Internal edges using 0 or 1 boundary point.
label nInternalEdges () const
Internal edges using 0,1 or 2 boundary points.
virtual const pointField & points () const =0
Return mesh points.
virtual const faceList & faces () const =0
Return faces.
virtual const labelList & faceOwner () const =0
Face face-owner addressing.
virtual const labelList & faceNeighbour () const =0
Face face-neighbour addressing.
virtual const pointField & oldPoints () const =0
Return old points for mesh motion.
const cellShapeList & cellShapes () const
Return cell shapes.
const edgeList & edges () const
Return mesh edges. Uses calcEdges.
const labelListList & cellCells () const
const labelListList & edgeCells () const
const labelListList & pointCells () const
const cellList & cells () const
const labelListList & edgeFaces () const
const labelListList & pointFaces () const
const labelListList & cellEdges () const
const labelListList & faceEdges () const
const labelListList & pointEdges () const
const labelListList & pointPoints () const
const labelListList & cellPoints () const
const vectorField & cellCentres () const
const vectorField & faceCentres () const
const scalarField & cellVolumes () const
const vectorField & faceAreas () const
tmp< scalarField > movePoints (const pointField &p, const pointField &oldP)
Move points, returns volumes swept by faces in motion.
bool isInternalFace (const label faceIndex) const
Return true if given face label is internal to the mesh.
virtual bool checkUpperTriangular (const bool report=false, labelHashSet *setPtr=nullptr) const
Check face ordering.
virtual bool checkCellsZipUp (const bool report=false, labelHashSet *setPtr=nullptr) const
Check cell zip-up.
virtual bool checkFaceVertices (const bool report=false, labelHashSet *setPtr=nullptr) const
Check uniqueness of face vertices.
virtual bool checkPoints (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for unused points.
virtual bool checkFaceFaces (const bool report=false, labelHashSet *setPtr=nullptr) const
Check face-face connectivity.
virtual bool checkClosedBoundary (const bool report=false) const
Check boundary for closedness.
virtual bool checkClosedCells (const bool report=false, labelHashSet *setPtr=nullptr, labelHashSet *highAspectSetPtr=nullptr, const Vector< label > &solutionD=Vector< label >::one) const
Check cells for closedness.
virtual bool checkFaceAreas (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for negative face areas.
virtual bool checkCellVolumes (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for negative cell volumes.
virtual bool checkFaceOrthogonality (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for non-orthogonality.
virtual bool checkFacePyramids (const bool report=false, const scalar minPyrVol=-SMALL, labelHashSet *setPtr=nullptr) const
Check face pyramid volume.
virtual bool checkFaceSkewness (const bool report=false, labelHashSet *setPtr=nullptr) const
Check face skewness.
virtual bool checkFaceAngles (const bool report=false, const scalar maxSin=10, labelHashSet *setPtr=nullptr) const
Check face angles.
virtual bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage: decompose face and check ratio between.
virtual bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet *setPtr=nullptr) const
Check for point-point-nearness,.
virtual bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet *setPtr=nullptr) const
Check edge length.
virtual bool checkConcaveCells (const bool report=false, labelHashSet *setPtr=nullptr) const
Check for concave cells by the planes of faces.
virtual bool checkTopology (const bool report=false) const
Check mesh topology for correctness.
virtual bool checkGeometry (const bool report=false) const
Check mesh geometry (& implicitly topology) for correctness.
virtual bool checkMesh (const bool report=false) const
Check mesh for correctness. Returns false for no error.
bool pointInCellBB (const point &p, label celli, scalar inflationFraction=0) const
Return true if the point in the cell bounding box.
bool pointInCell (const point &p, label celli) const
Return true if the point is in the cell.
label findNearestCell (const point &location) const
Find the cell with the nearest cell centre to location.
label findCell (const point &location) const
Find cell enclosing this location (-1 if not in mesh)
void printAllocated () const
Print a list of all the currently allocated mesh data.
bool hasCellShapes () const
bool hasEdges () const
bool hasCellCells () const
bool hasEdgeCells () const
bool hasPointCells () const
bool hasCells () const
bool hasEdgeFaces () const
bool hasPointFaces () const
bool hasCellEdges () const
bool hasFaceEdges () const
bool hasPointEdges () const
bool hasPointPoints () const
bool hasCellPoints () const
bool hasCellCentres () const
bool hasFaceCentres () const
bool hasCellVolumes () const
bool hasFaceAreas () const
const labelList & cellCells (const label celli, DynamicList< label > &) const
cellCells using cells.
const labelList & cellCells (const label celli) const
const labelList & cellPoints (const label celli, labelHashSet &, DynamicList< label > &) const
cellPoints using cells
const labelList & cellPoints (const label celli) const
const labelList & pointCells (const label pointi, DynamicList< label > &) const
pointCells using pointFaces
const labelList & pointCells (const label pointi) const
const labelList & pointPoints (const label pointi, DynamicList< label > &) const
pointPoints using edges, pointEdges
const labelList & pointPoints (const label pointi) const
const labelList & faceEdges (const label facei, DynamicList< label > &) const
faceEdges using pointFaces, edges, pointEdges
const labelList & faceEdges (const label facei) const
const labelList & edgeFaces (const label edgeI, DynamicList< label > &) const
edgeFaces using pointFaces, edges, pointEdges
const labelList & edgeFaces (const label edgeI) const
const labelList & edgeCells (const label edgeI, DynamicList< label > &) const
edgeCells using pointFaces, edges, pointEdges
const labelList & edgeCells (const label edgeI) const
const labelList & cellEdges (const label celli, labelHashSet &, DynamicList< label > &) const
cellEdges using cells, pointFaces, edges, pointEdges
const labelList & cellEdges (const label celli) const
void clearGeom ()
Clear geometry.
void clearAddressing ()
Clear topological data.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Static Public Member Functions
static void calcCells (cellList &, const labelUList &own, const labelUList &nei, const label nCells=-1)
Helper function to calculate cell-face addressing from.
static bool calcPointOrder (label &nInternalPoints, labelList &pointMap, const faceList &, const label nInternalFaces, const label nPoints)
Helper function to calculate point ordering. Returns true.
static scalar setClosedThreshold (const scalar)
Set the closedness ratio warning threshold.
static scalar setAspectThreshold (const scalar)
Set the aspect ratio warning threshold.
static scalar setNonOrthThreshold (const scalar)
Set the non-orthogonality warning threshold in degrees.
static scalar setSkewThreshold (const scalar)
Set the skewness warning threshold as percentage.
Static Public Attributes
static const unsigned cellsPerEdge_ = 4
Estimated number of cells per edge.
static const unsigned cellsPerPoint_ = 8
Estimated number of cells per point.
static const unsigned facesPerCell_ = 6
Estimated number of faces per cell.
static const unsigned facesPerEdge_ = 4
Estimated number of faces per edge.
static const unsigned facesPerPoint_ = 12
Estimated number of faces per point.
static const unsigned edgesPerCell_ = 12
Estimated number of edges per cell.
static const unsigned edgesPerFace_ = 4
Estimated number of edges per cell.
static const unsigned edgesPerPoint_ = 6
Estimated number of edges per point.
static const unsigned pointsPerCell_ = 8
Estimated number of points per cell.
static const unsigned pointsPerFace_ = 4
Estimated number of points per face.
Protected Member Functions
void calcFaceCentresAndAreas () const
Calculate face centres and areas.
void makeFaceCentresAndAreas (const pointField &p, vectorField &fCtrs, vectorField &fAreas) const
void calcCellCentresAndVols () const
Calculate cell centres and volumes.
void makeCellCentresAndVols (const vectorField &fCtrs, const vectorField &fAreas, vectorField &cellCtrs, scalarField &cellVols) const
void calcEdgeVectors () const
Calculate edge vectors.
bool checkDuplicateFaces (const label, const Map< label > &, label &nBaffleFaces, labelHashSet *) const
Check if all points on face are shared with another face.
bool checkCommonOrder (const label, const Map< label > &, labelHashSet *) const
Check that shared points are in consecutive order.
bool checkClosedBoundary (const vectorField &areas, const bool report, const bitSet &internalOrCoupledFaces) const
Check boundary for closedness.
bool checkClosedCells (const vectorField &faceAreas, const scalarField &cellVolumes, const bool report, labelHashSet *setPtr, labelHashSet *aspectSetPtr, const Vector< label > &meshD) const
Check cells for closedness.
bool checkFaceAreas (const vectorField &faceAreas, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative face areas.
bool checkCellVolumes (const scalarField &vols, const bool report, const bool detailedReport, labelHashSet *setPtr) const
Check for negative cell volumes.
bool checkFaceOrthogonality (const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check for non-orthogonality.
bool checkFacePyramids (const pointField &points, const vectorField &ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet *setPtr) const
Check face pyramid volume.
bool checkFaceSkewness (const pointField &points, const vectorField &fCtrs, const vectorField &fAreas, const vectorField &cellCtrs, const bool report, labelHashSet *setPtr) const
Check face skewness.
bool checkFaceAngles (const pointField &points, const vectorField &faceAreas, const bool report, const scalar maxDeg, labelHashSet *setPtr) const
Check face angles.
bool checkFaceFlatness (const pointField &points, const vectorField &faceCentres, const vectorField &faceAreas, const bool report, const scalar warnFlatness, labelHashSet *setPtr) const
Check face warpage.
bool checkConcaveCells (const vectorField &fAreas, const pointField &fCentres, const bool report, labelHashSet *setPtr) const
Check for concave cells by the planes of faces.
primitiveMesh ()
Construct null.
Static Protected Attributes
static scalar closedThreshold_ = 1.0e-6
Static data to control mesh checking.
static scalar aspectThreshold_ = 1000
Aspect ratio warning threshold.
static scalar nonOrthThreshold_ = 70
Non-orthogonality warning threshold in deg.
static scalar skewThreshold_ = 4
Skewness warning threshold.
static scalar planarCosAngle_ = 1.0e-6
Threshold where faces are considered coplanar.
Detailed Description
Cell-face mesh analysis engine.
Source files
primitiveMesh.H
primitiveMeshI.H
primitiveMesh.C
primitiveMeshClear.C
primitiveMeshCellCells.C
primitiveMeshEdgeCells.C
primitiveMeshPointCells.C
primitiveMeshCells.C
primitiveMeshEdgeFaces.C
primitiveMeshPointFaces.C
primitiveMeshCellEdges.C
primitiveMeshPointEdges.C
primitiveMeshPointPoints.C
primitiveMeshEdges.C
primitiveMeshCellCentresAndVols.C
primitiveMeshFaceCentresAndAreas.C
primitiveMeshFindCell.C
Definition at line 74 of file primitiveMesh.H.
Constructor & Destructor Documentation
primitiveMesh () protected
Construct null.
Definition at line 34 of file primitiveMesh.C.
References Foam::defineTypeNameAndDebug().
primitiveMesh (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Construct from components.
Definition at line 72 of file primitiveMesh.C.
~primitiveMesh () virtual
Destructor.
Definition at line 113 of file primitiveMesh.C.
Member Function Documentation
void calcFaceCentresAndAreas () const protected
Calculate face centres and areas.
Definition at line 34 of file primitiveMeshFaceCentresAndAreas.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::makeFaceCentresAndAreas(), primitiveMesh::nFaces(), primitiveMesh::points(), and Foam::Pout.
void makeFaceCentresAndAreas (const pointField & p, vectorField & fCtrs, vectorField & fAreas) const protected
Definition at line 70 of file primitiveMeshFaceCentresAndAreas.C.
Referenced by primitiveMesh::calcFaceCentresAndAreas().
void calcCellCentresAndVols () const protected
Calculate cell centres and volumes.
Definition at line 31 of file primitiveMeshCellCentresAndVols.C.
References Foam::abort(), cellVols, Foam::expressions::patchExpr::debug, Foam::endl(), primitiveMesh::faceAreas(), primitiveMesh::faceCentres(), Foam::FatalError, FatalErrorInFunction, primitiveMesh::makeCellCentresAndVols(), primitiveMesh::nCells(), and Foam::Pout.
void makeCellCentresAndVols (const vectorField & fCtrs, const vectorField & fAreas, vectorField & cellCtrs, scalarField & cellVols) const protected
Definition at line 70 of file primitiveMeshCellCentresAndVols.C.
Referenced by primitiveMesh::calcCellCentresAndVols().
void calcEdgeVectors () const protected
Calculate edge vectors.
bool checkDuplicateFaces (const label facei, const Map< label > & nCommonPoints, label & nBaffleFaces, labelHashSet * setPtr) const protected
Check if all points on face are shared with another face.
Definition at line 1340 of file primitiveMeshCheck.C.
bool checkCommonOrder (const label facei, const Map< label > & nCommonPoints, labelHashSet * setPtr) const protected
Check that shared points are in consecutive order.
Definition at line 1381 of file primitiveMeshCheck.C.
bool checkClosedBoundary (const vectorField & areas, const bool report, const bitSet & internalOrCoupledFaces) const protected
Check boundary for closedness.
Definition at line 42 of file primitiveMeshCheck.C.
References primitiveMesh::closedThreshold_, Foam::cmptMag(), Foam::cmptMax(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::Info, InfoInFunction, Foam::mag(), primitiveMesh::nInternalFaces(), Foam::reduce(), UList< T >::size(), PackedList< Width >::size(), and Foam::Zero.
bool checkClosedCells (const vectorField & faceAreas, const scalarField & cellVolumes, const bool report, labelHashSet * setPtr, labelHashSet * aspectSetPtr, const Vector< label > & meshD) const protected
Check cells for closedness.
Definition at line 97 of file primitiveMeshCheck.C.
bool checkFaceAreas (const vectorField & faceAreas, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Check for negative face areas.
Definition at line 229 of file primitiveMeshCheck.C.
bool checkCellVolumes (const scalarField & vols, const bool report, const bool detailedReport, labelHashSet * setPtr) const protected
Check for negative cell volumes.
Definition at line 305 of file primitiveMeshCheck.C.
bool checkFaceOrthogonality (const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Check for non-orthogonality.
Definition at line 373 of file primitiveMeshCheck.C.
bool checkFacePyramids (const pointField & points, const vectorField & ctrs, const bool report, const bool detailedReport, const scalar minPyrVol, labelHashSet * setPtr) const protected
Check face pyramid volume.
Definition at line 481 of file primitiveMeshCheck.C.
bool checkFaceSkewness (const pointField & points, const vectorField & fCtrs, const vectorField & fAreas, const vectorField & cellCtrs, const bool report, labelHashSet * setPtr) const protected
Check face skewness.
Definition at line 581 of file primitiveMeshCheck.C.
bool checkFaceAngles (const pointField & points, const vectorField & faceAreas, const bool report, const scalar maxDeg, labelHashSet * setPtr) const protected
Check face angles.
Allows a slight non-convexity. E.g. maxDeg = 10 allows for angles < 190 (or 10 degrees concavity) (if truly concave and points not visible from face centre the face-pyramid check in checkMesh will fail)
Definition at line 652 of file primitiveMeshCheck.C.
bool checkFaceFlatness (const pointField & points, const vectorField & faceCentres, const vectorField & faceAreas, const bool report, const scalar warnFlatness, labelHashSet * setPtr) const protected
Check face warpage.
Definition at line 730 of file primitiveMeshCheck.C.
bool checkConcaveCells (const vectorField & fAreas, const pointField & fCentres, const bool report, labelHashSet * setPtr) const protected
Check for concave cells by the planes of faces.
Definition at line 833 of file primitiveMeshCheck.C.
ClassName ("primitiveMesh")
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells)
Reset this primitiveMesh given the primitive array sizes.
Definition at line 201 of file primitiveMesh.C.
void reset (const label nPoints, const label nInternalFaces, const label nFaces, const label nCells, cellList & cells)
Reset this primitiveMesh given the primitive array sizes and cells.
Definition at line 257 of file primitiveMesh.C.
Foam::label nPoints () const inline
Number of mesh points.
Definition at line 30 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), primitiveMesh::checkEdgeLength(), edgeVertex::edgeVertex(), hexRef8::hexRef8(), isoSurfaceTopo::interpolate(), PointEdgeWave< Type, TrackingData >::PointEdgeWave(), primitiveMesh::pointFaces(), pointSet::pointSet(), pointMesh::size(), parseDriver::size(), pointBitSet::updateMesh(), pointSet::updateMesh(), pointZoneSet::writeObject(), Foam::vtk::writePointSet(), and zoneMotion::zoneMotion().
Foam::label nEdges () const inline
Number of mesh edges.
Definition at line 60 of file primitiveMeshI.H.
Referenced by primitiveMesh::edgeCells(), primitiveMesh::edgeFaces(), edgeVertex::edgeVertex(), and PointEdgeWave< Type, TrackingData >::PointEdgeWave().
Foam::label nFaces () const inline
Number of mesh faces.
Definition at line 83 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), fvMeshTools::addPatch(), primitiveMesh::calcFaceCentresAndAreas(), decompositionMethod::decompose(), snappyLayerDriver::doLayers(), FaceCellWave< Type, TrackingData >::FaceCellWave(), polyMeshTools::faceOrthogonality(), faceSet::faceSet(), inverseDistance::findHoles(), fvFieldReconstructor::fvFieldReconstructor(), Foam::MULES::limit(), Foam::MULES::limitCorr(), dynamicRefineFvMesh::mapNewInternalFaces(), volSurfaceMapping::mapToSurface(), meshRefinement::markOutsideFaces(), snappyLayerDriver::mergePatchFacesUndo(), snappySnapDriver::repatchToSurface(), decompositionMethod::setConstraints(), lumpedPointMovement::setMapping(), Foam::fvc::smooth(), meshRefinement::subsetBaffles(), faceBoolSet::updateMesh(), faceBitSet::updateMesh(), faceSet::updateMesh(), cellVolumeWeight::walkFront(), and Foam::vtk::writeFaceSet().
Foam::label nCells () const inline
Number of mesh cells.
Definition at line 89 of file primitiveMeshI.H.
Referenced by polyMeshAdder::add(), primitiveMesh::calcCellCentresAndVols(), primitiveMesh::calcCells(), cellCuts::cellCuts(), primitiveMesh::cellPoints(), cellSet::cellSet(), randomDecomp::decompose(), decompositionMethod::decompose(), snappyLayerDriver::doLayers(), FaceCellWave< Type, TrackingData >::FaceCellWave(), meshRefinement::findRegions(), fvFieldReconstructor::fvFieldReconstructor(), hexRef8::hexRef8(), dynamicOversetFvMesh::interpolate(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), reactionsSensitivityAnalysis< chemistryType >::reactionsSensitivityAnalysis(), fvFieldReconstructor::reconstructFvVolumeInternalField(), regionSplit::reduceRegions(), zoltanRenumber::renumber(), polyGeoMesh::size(), volMesh::size(), parseDriver::size(), Foam::fvc::smooth(), syncTools::swapBoundaryCellPositions(), cellVolumeWeight::update(), cellSet::updateMesh(), Foam::vtk::writeCellSetFaces(), cellBitSet::writeDebug(), and cellZoneSet::writeObject().
Foam::label nInternalFaces () const inline
Number of internal faces.
Definition at line 71 of file primitiveMeshI.H.
Referenced by primitiveMesh::checkClosedBoundary(), decompositionMethod::decompose(), snappyLayerDriver::doLayers(), polyMeshTools::faceOrthogonality(), localPointRegion::findDuplicateFaces(), inverseDistance::findHoles(), boundaryMesh::getNearest(), dynamicRefineFvMesh::mapNewInternalFaces(), meshRefinement::markOutsideFaces(), Foam::oversetAdjustPhi(), regionSplit::reduceRegions(), sampledTriSurfaceMesh::sampleOnFaces(), lumpedPointMovement::setMapping(), parseDriver::size(), syncTools::swapBoundaryCellPositions(), cellVolumeWeight::walkFront(), extendedUpwindCellToFaceStencil::weightedSum(), and Foam::ensightOutput::Detail::writeVolField().
Foam::label nBoundaryFaces () const inline
Number of boundary faces (== nFaces - nInternalFaces)
Definition at line 77 of file primitiveMeshI.H.
Referenced by boundaryMesh::getNearest(), meshRefinement::mergePatchFaces(), sampledTriSurfaceMesh::sampleOnFaces(), syncTools::swapBoundaryCellPositions(), and Foam::ensightOutput::Detail::writeVolField().
Foam::label nInternalPoints () const inline
Points not on boundary.
Definition at line 24 of file primitiveMeshI.H.
Foam::label nInternal0Edges () const inline
Internal edges (i.e. not on boundary face) using no boundary point.
Definition at line 36 of file primitiveMeshI.H.
Foam::label nInternal1Edges () const inline
Internal edges using 0 or 1 boundary point.
Definition at line 44 of file primitiveMeshI.H.
Foam::label nInternalEdges () const inline
Internal edges using 0,1 or 2 boundary points.
Definition at line 52 of file primitiveMeshI.H.
virtual const pointField& points () const pure virtual
Return mesh points.
Implemented in polyMesh.
Referenced by primitiveMesh::calcFaceCentresAndAreas(), primitiveMesh::checkEdgeLength(), primitiveMesh::checkPointNearness(), localPointRegion::findDuplicateFaces(), boundaryMesh::getNearest(), primitiveMesh::pointInCellBB(), and cuttingSurfaceBase::walkCellCuts().
virtual const faceList& faces () const pure virtual
Return faces.
Implemented in polyMesh.
Referenced by primitiveMesh::checkEdgeLength(), primitiveMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceTwist(), primitiveMeshTools::faceSkewness(), localPointRegion::findDuplicateFaces(), boundaryMesh::getNearest(), Foam::interpolatePointToCell(), findUniqueIntersectOp::operator()(), primitiveMesh::pointFaces(), primitiveMesh::pointInCellBB(), and cuttingSurfaceBase::walkCellCuts().
virtual const labelList& faceOwner () const pure virtual
Face face-owner addressing.
Implemented in polyMesh.
virtual const labelList& faceNeighbour () const pure virtual
Face face-neighbour addressing.
Implemented in polyMesh.
virtual const pointField& oldPoints () const pure virtual
Return old points for mesh motion.
Implemented in polyMesh.
const Foam::cellShapeList & cellShapes () const
Return cell shapes.
Definition at line 309 of file primitiveMesh.C.
const Foam::edgeList & edges () const
Return mesh edges. Uses calcEdges.
Definition at line 498 of file primitiveMeshEdges.C.
void calcCells (cellList & cellFaceAddr, const labelUList & own, const labelUList & nei, const label nCells = -1) static
Helper function to calculate cell-face addressing from.
face-cell addressing. If nCells is not provided it will scan for the maximum.
Definition at line 26 of file primitiveMeshCells.C.
References forAll, Foam::max(), primitiveMesh::nCells(), List< T >::setSize(), UList< T >::size(), and Foam::Zero.
bool calcPointOrder (label & nInternalPoints, labelList & pointMap, const faceList & faces, const label nInternalFaces, const label nPoints) static
Helper function to calculate point ordering. Returns true.
if points already ordered, false and fills pointMap (old to new). Map splits points into those not used by any boundary face and those that are.
Definition at line 122 of file primitiveMesh.C.
const Foam::labelListList & cellCells () const
Definition at line 95 of file primitiveMeshCellCells.C.
const Foam::labelListList & edgeCells () const
Definition at line 27 of file primitiveMeshEdgeCells.C.
References Foam::abort(), primitiveMesh::cellEdges(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
const Foam::labelListList & pointCells () const
Definition at line 103 of file primitiveMeshPointCells.C.
Referenced by primitiveMesh::cellPoints().
const Foam::cellList & cells () const
Definition at line 131 of file primitiveMeshCells.C.
Referenced by Foam::interpolatePointToCell(), dynamicRefineFvMesh::mapNewInternalFaces(), Foam::markGrowFaceCellFace(), primitiveMesh::pointInCellBB(), Foam::polyMeshZipUpCells(), cuttingSurfaceBase::walkCellCuts(), cellVolumeWeight::walkFront(), Foam::vtk::writeCellSetFaces(), and zoneMotion::zoneMotion().
const Foam::labelListList & edgeFaces () const
Definition at line 26 of file primitiveMeshEdgeFaces.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), primitiveMesh::faceEdges(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nEdges(), and Foam::Pout.
const Foam::labelListList & pointFaces () const
Definition at line 27 of file primitiveMeshPointFaces.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), primitiveMesh::faces(), Foam::invertManyToMany(), primitiveMesh::nPoints(), and Foam::Pout.
Referenced by decompositionMethod::decompose(), and Foam::polyMeshZipUpCells().
const Foam::labelListList & cellEdges () const
Definition at line 113 of file primitiveMeshCellEdges.C.
Referenced by primitiveMesh::edgeCells().
const Foam::labelListList & faceEdges () const
Definition at line 521 of file primitiveMeshEdges.C.
Referenced by primitiveMesh::edgeFaces(), and Foam::meshTools::faceOnCell().
const Foam::labelListList & pointEdges () const
Definition at line 509 of file primitiveMeshEdges.C.
const Foam::labelListList & pointPoints () const
Definition at line 86 of file primitiveMeshPointPoints.C.
const Foam::labelListList & cellPoints () const
Definition at line 27 of file primitiveMeshCellPoints.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::invertManyToMany(), primitiveMesh::nCells(), primitiveMesh::pointCells(), and Foam::Pout.
const Foam::vectorField & cellCentres () const
Definition at line 170 of file primitiveMeshCellCentresAndVols.C.
Referenced by decompositionMethod::decompose(), mappedPatchBase::facePoint(), Foam::levelSetFraction(), vtuAdaptor::points(), and sweepData::updateFace().
const Foam::vectorField & faceCentres () const
Definition at line 139 of file primitiveMeshFaceCentresAndAreas.C.
Referenced by primitiveMesh::calcCellCentresAndVols(), decompositionMethod::decompose(), sweepData::equal(), mappedPatchBase::facePoint(), boundaryMesh::getNearest(), and snappySnapDriver::repatchToSurface().
const Foam::scalarField & cellVolumes () const
Definition at line 181 of file primitiveMeshCellCentresAndVols.C.
Referenced by InflationInjection< CloudType >::InflationInjection().
const Foam::vectorField & faceAreas () const
Definition at line 150 of file primitiveMeshFaceCentresAndAreas.C.
Referenced by primitiveMesh::calcCellCentresAndVols(), boundaryMesh::getNearest(), and findUniqueIntersectOp::operator()().
Foam::tmp< Foam::scalarField > movePoints (const pointField & p, const pointField & oldP)
Move points, returns volumes swept by faces in motion.
Definition at line 278 of file primitiveMesh.C.
bool isInternalFace (const label faceIndex) const inline
Return true if given face label is internal to the mesh.
Definition at line 95 of file primitiveMeshI.H.
Referenced by decompositionMethod::decompose(), extractEulerianParticles::faceValue(), Foam::markGrowFaceCellFace(), wallBoundedParticle::patchInteraction(), cellVolumeWeight::walkFront(), Foam::vtk::writeCellSetFaces(), and Foam::ensightOutput::Detail::writeVolField().
bool checkUpperTriangular (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check face ordering.
Definition at line 942 of file primitiveMeshCheck.C.
bool checkCellsZipUp (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check cell zip-up.
Definition at line 1103 of file primitiveMeshCheck.C.
bool checkFaceVertices (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check uniqueness of face vertices.
Definition at line 1199 of file primitiveMeshCheck.C.
bool checkPoints (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for unused points.
Definition at line 1270 of file primitiveMeshCheck.C.
bool checkFaceFaces (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check face-face connectivity.
Definition at line 1542 of file primitiveMeshCheck.C.
bool checkClosedBoundary (const bool report = false) const virtual
Check boundary for closedness.
Definition at line 1640 of file primitiveMeshCheck.C.
bool checkClosedCells (const bool report = false, labelHashSet * setPtr = nullptr, labelHashSet * highAspectSetPtr = nullptr, const Vector< label > & solutionD = Vector<label>::one) const virtual
Check cells for closedness.
Definition at line 1647 of file primitiveMeshCheck.C.
bool checkFaceAreas (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for negative face areas.
Definition at line 1667 of file primitiveMeshCheck.C.
bool checkCellVolumes (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for negative cell volumes.
Definition at line 1683 of file primitiveMeshCheck.C.
bool checkFaceOrthogonality (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for non-orthogonality.
Reimplemented in polyMesh.
Definition at line 1699 of file primitiveMeshCheck.C.
bool checkFacePyramids (const bool report = false, const scalar minPyrVol = -SMALL, labelHashSet * setPtr = nullptr) const virtual
Check face pyramid volume.
Definition at line 1715 of file primitiveMeshCheck.C.
bool checkFaceSkewness (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check face skewness.
Reimplemented in polyMesh.
Definition at line 1734 of file primitiveMeshCheck.C.
bool checkFaceAngles (const bool report = false, const scalar maxSin = 10, labelHashSet * setPtr = nullptr) const virtual
Check face angles.
Definition at line 1752 of file primitiveMeshCheck.C.
bool checkFaceFlatness (const bool report, const scalar warnFlatness, labelHashSet * setPtr) const virtual
Check face warpage: decompose face and check ratio between.
magnitude of sum of triangle areas and sum of magnitude of triangle areas.
Definition at line 1770 of file primitiveMeshCheck.C.
bool checkPointNearness (const bool report, const scalar reportDistSqr, labelHashSet * setPtr = nullptr) const virtual
Check for point-point-nearness,.
e.g. colocated points which may be part of baffles.
Definition at line 28 of file primitiveMeshCheckPointNearness.C.
References Foam::endl(), i, SortableList< T >::indices(), Foam::Info, HashSet< Key, Hash >::insert(), j, Foam::magSqr(), primitiveMesh::points(), Foam::reduce(), UList< T >::size(), and Foam::sqrt().
bool checkEdgeLength (const bool report, const scalar minLenSqr, labelHashSet * setPtr = nullptr) const virtual
Check edge length.
Definition at line 27 of file primitiveMeshCheckEdgeLength.C.
References Foam::endl(), f(), primitiveMesh::faces(), UList< T >::fcIndex(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), Foam::magSqr(), Foam::max(), Foam::min(), primitiveMesh::nPoints(), primitiveMesh::points(), Foam::reduce(), HashTable< T, Key, Hash >::size(), Foam::sqr(), Foam::sqrt(), and HashTable< T, Key, Hash >::transfer().
bool checkConcaveCells (const bool report = false, labelHashSet * setPtr = nullptr) const virtual
Check for concave cells by the planes of faces.
Definition at line 1789 of file primitiveMeshCheck.C.
bool checkTopology (const bool report = false) const virtual
Check mesh topology for correctness.
Returns false for no error.
Definition at line 1804 of file primitiveMeshCheck.C.
bool checkGeometry (const bool report = false) const virtual
Check mesh geometry (& implicitly topology) for correctness.
Returns false for no error.
Definition at line 1834 of file primitiveMeshCheck.C.
bool checkMesh (const bool report = false) const virtual
Check mesh for correctness. Returns false for no error.
Definition at line 1866 of file primitiveMeshCheck.C.
Foam::scalar setClosedThreshold (const scalar val) static
Set the closedness ratio warning threshold.
Definition at line 1895 of file primitiveMeshCheck.C.
Foam::scalar setAspectThreshold (const scalar val) static
Set the aspect ratio warning threshold.
Definition at line 1904 of file primitiveMeshCheck.C.
Foam::scalar setNonOrthThreshold (const scalar val) static
Set the non-orthogonality warning threshold in degrees.
Definition at line 1913 of file primitiveMeshCheck.C.
Foam::scalar setSkewThreshold (const scalar val) static
Set the skewness warning threshold as percentage.
of the face area vector
Definition at line 1922 of file primitiveMeshCheck.C.
bool pointInCellBB (const point & p, label celli, scalar inflationFraction = 0) const
Return true if the point in the cell bounding box.
The bounding box may be isotropically inflated by the fraction inflationFraction
Definition at line 29 of file primitiveMeshFindCell.C.
References primitiveMesh::cells(), primitiveMesh::faces(), and primitiveMesh::points().
bool pointInCell (const point & p, label celli) const
Return true if the point is in the cell.
Definition at line 54 of file primitiveMeshFindCell.C.
Foam::label findNearestCell (const point & location) const
Find the cell with the nearest cell centre to location.
Definition at line 81 of file primitiveMeshFindCell.C.
Foam::label findCell (const point & location) const
Find cell enclosing this location (-1 if not in mesh)
Definition at line 108 of file primitiveMeshFindCell.C.
void printAllocated () const
Print a list of all the currently allocated mesh data.
Definition at line 26 of file primitiveMeshClear.C.
References Foam::endl(), and Foam::Pout.
bool hasCellShapes () const inline
Definition at line 101 of file primitiveMeshI.H.
bool hasEdges () const inline
Definition at line 107 of file primitiveMeshI.H.
bool hasCellCells () const inline
Definition at line 113 of file primitiveMeshI.H.
bool hasEdgeCells () const inline
Definition at line 119 of file primitiveMeshI.H.
bool hasPointCells () const inline
Definition at line 125 of file primitiveMeshI.H.
bool hasCells () const inline
Definition at line 131 of file primitiveMeshI.H.
bool hasEdgeFaces () const inline
Definition at line 137 of file primitiveMeshI.H.
bool hasPointFaces () const inline
Definition at line 143 of file primitiveMeshI.H.
bool hasCellEdges () const inline
Definition at line 149 of file primitiveMeshI.H.
bool hasFaceEdges () const inline
Definition at line 155 of file primitiveMeshI.H.
bool hasPointEdges () const inline
Definition at line 161 of file primitiveMeshI.H.
bool hasPointPoints () const inline
Definition at line 167 of file primitiveMeshI.H.
bool hasCellPoints () const inline
Definition at line 173 of file primitiveMeshI.H.
bool hasCellCentres () const inline
Definition at line 179 of file primitiveMeshI.H.
bool hasFaceCentres () const inline
Definition at line 185 of file primitiveMeshI.H.
bool hasCellVolumes () const inline
Definition at line 191 of file primitiveMeshI.H.
bool hasFaceAreas () const inline
Definition at line 197 of file primitiveMeshI.H.
const Foam::labelList & cellCells (const label celli, DynamicList< label > & storage) const
cellCells using cells.
Definition at line 107 of file primitiveMeshCellCells.C.
const Foam::labelList & cellCells (const label celli) const
Definition at line 146 of file primitiveMeshCellCells.C.
const Foam::labelList & cellPoints (const label celli, labelHashSet & set, DynamicList< label > & storage) const
cellPoints using cells
Definition at line 55 of file primitiveMeshCellPoints.C.
const Foam::labelList & cellPoints (const label celli) const
Definition at line 91 of file primitiveMeshCellPoints.C.
const Foam::labelList & pointCells (const label pointi, DynamicList< label > & storage) const
pointCells using pointFaces
Definition at line 115 of file primitiveMeshPointCells.C.
const Foam::labelList & pointCells (const label pointi) const
Definition at line 169 of file primitiveMeshPointCells.C.
const Foam::labelList & pointPoints (const label pointi, DynamicList< label > & storage) const
pointPoints using edges, pointEdges
Definition at line 98 of file primitiveMeshPointPoints.C.
const Foam::labelList & pointPoints (const label pointi) const
Definition at line 130 of file primitiveMeshPointPoints.C.
const Foam::labelList & faceEdges (const label facei, DynamicList< label > & storage) const
faceEdges using pointFaces, edges, pointEdges
Definition at line 583 of file primitiveMeshEdges.C.
const Foam::labelList & faceEdges (const label facei) const
Definition at line 618 of file primitiveMeshEdges.C.
const Foam::labelList & edgeFaces (const label edgeI, DynamicList< label > & storage) const
edgeFaces using pointFaces, edges, pointEdges
Definition at line 53 of file primitiveMeshEdgeFaces.C.
const Foam::labelList & edgeFaces (const label edgeI) const
Definition at line 98 of file primitiveMeshEdgeFaces.C.
const Foam::labelList & edgeCells (const label edgeI, DynamicList< label > & storage) const
edgeCells using pointFaces, edges, pointEdges
Definition at line 53 of file primitiveMeshEdgeCells.C.
const Foam::labelList & edgeCells (const label edgeI) const
Definition at line 122 of file primitiveMeshEdgeCells.C.
const Foam::labelList & cellEdges (const label celli, labelHashSet & set, DynamicList< label > & storage) const
cellEdges using cells, pointFaces, edges, pointEdges
Definition at line 625 of file primitiveMeshEdges.C.
const Foam::labelList & cellEdges (const label celli) const
Definition at line 660 of file primitiveMeshEdges.C.
void clearGeom ()
Clear geometry.
Definition at line 120 of file primitiveMeshClear.C.
References Foam::endl(), and Foam::Pout.
void clearAddressing ()
Clear topological data.
Definition at line 136 of file primitiveMeshClear.C.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Definition at line 165 of file primitiveMeshClear.C.
Member Data Documentation
Foam::scalar closedThreshold_ = 1.0e-6 static protected
Static data to control mesh checking.
Cell closedness warning threshold
set as the fraction of un-closed area to closed area
Definition at line 318 of file primitiveMesh.H.
Referenced by primitiveMesh::checkClosedBoundary().
Foam::scalar aspectThreshold_ = 1000 static protected
Aspect ratio warning threshold.
Definition at line 323 of file primitiveMesh.H.
Foam::scalar nonOrthThreshold_ = 70 static protected
Non-orthogonality warning threshold in deg.
Definition at line 328 of file primitiveMesh.H.
Foam::scalar skewThreshold_ = 4 static protected
Skewness warning threshold.
Definition at line 333 of file primitiveMesh.H.
Foam::scalar planarCosAngle_ = 1.0e-6 static protected
Threshold where faces are considered coplanar.
Definition at line 338 of file primitiveMesh.H.
const unsigned cellsPerEdge_ = 4 static
Estimated number of cells per edge.
Definition at line 534 of file primitiveMesh.H.
const unsigned cellsPerPoint_ = 8 static
Estimated number of cells per point.
Definition at line 539 of file primitiveMesh.H.
const unsigned facesPerCell_ = 6 static
Estimated number of faces per cell.
Definition at line 544 of file primitiveMesh.H.
const unsigned facesPerEdge_ = 4 static
Estimated number of faces per edge.
Definition at line 549 of file primitiveMesh.H.
const unsigned facesPerPoint_ = 12 static
Estimated number of faces per point.
Definition at line 554 of file primitiveMesh.H.
const unsigned edgesPerCell_ = 12 static
Estimated number of edges per cell.
Definition at line 559 of file primitiveMesh.H.
const unsigned edgesPerFace_ = 4 static
Estimated number of edges per cell.
Definition at line 564 of file primitiveMesh.H.
const unsigned edgesPerPoint_ = 6 static
Estimated number of edges per point.
Definition at line 569 of file primitiveMesh.H.
const unsigned pointsPerCell_ = 8 static
Estimated number of points per cell.
Definition at line 574 of file primitiveMesh.H.
const unsigned pointsPerFace_ = 4 static
Estimated number of points per face.
Definition at line 579 of file primitiveMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMesh.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCalcCellShapes.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellCentresAndVols.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCellPoints.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheck.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckEdgeLength.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshCheck/primitiveMeshCheckPointNearness.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshClear.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdgeFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshEdges.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFaceCentresAndAreas.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshFindCell.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshI.H
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointCells.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointFaces.C
src/OpenFOAM/meshes/primitiveMesh/primitiveMeshPointPoints.C