OpenFOAM: UPstream Class Reference
UPstream Class Reference
Inter-processor communications stream.
Classes
class commsStruct
Structure for communicating between processors.
class communicator
Helper class for allocating/freeing communicators.
struct listEq
combineReduce operator for lists. Used for counting.
Public Types
enum commsTypes { blocking, scheduled, nonBlocking }
Types of communications.
Public Member Functions
ClassName ("UPstream")
UPstream (const commsTypes commsType)
Construct given optional buffer size.
commsTypes commsType () const
Get the communications type of the stream.
commsTypes commsType (const commsTypes ct)
Set the communications type of the stream.
Static Public Member Functions
static label allocateCommunicator (const label parent, const labelList &subRanks, const bool doPstream=true)
Allocate a new communicator.
static void freeCommunicator (const label communicator, const bool doPstream=true)
Free a previously allocated communicator.
static void freeCommunicators (const bool doPstream)
Free all communicators.
static int baseProcNo (const label myComm, const int procID)
Return physical processor number (i.e. processor number in worldComm) given communicator and procssor.
static label procNo (const label comm, const int baseProcID)
Return processor number in communicator (given physical processor number) (= reverse of baseProcNo)
static label procNo (const label myComm, const label currentComm, const int currentProcID)
Return processor number in communicator (given processor number and communicator)
static void addValidParOptions (HashTable< string > &validParOptions)
Add the valid option this type of communications library adds/requires on the command line.
static bool init (int &argc, char **&argv, const bool needsThread)
Initialisation function called from main.
static bool initNull ()
Special purpose initialisation function.
static label nRequests ()
Get number of outstanding requests.
static void resetRequests (const label sz)
Truncate number of outstanding requests.
static void waitRequests (const label start=0)
Wait until all requests (from start onwards) have finished.
static void waitRequest (const label i)
Wait until request i has finished.
static bool finishedRequest (const label i)
Non-blocking comms: has request i finished?
static int allocateTag (const char *)
static int allocateTag (const word &)
static void freeTag (const char *, const int tag)
static void freeTag (const word &, const int tag)
static bool & parRun ()
Is this a parallel run?
static bool haveThreads ()
Have support for threads.
static label nProcs (const label communicator=0)
Number of processes in parallel run.
static constexpr int masterNo () noexcept
Process index of the master.
static bool master (const label communicator=0)
Am I the master process.
static int myProcNo (const label communicator=0)
Number of this process (starting from masterNo() = 0)
static label parent (const label communicator)
static List< int > & procID (label communicator)
Process ID of given process index.
static constexpr int firstSlave () noexcept
Process index of first slave.
static int lastSlave (const label communicator=0)
Process index of last slave.
static const List< commsStruct > & linearCommunication (const label communicator=0)
Communication schedule for linear all-to-master (proc 0)
static const List< commsStruct > & treeCommunication (const label communicator=0)
Communication schedule for tree all-to-master (proc 0)
static int & msgType ()
Message tag of standard messages.
static void exit (int errnum=1)
Exit program.
static void abort ()
Abort program.
static void allToAll (const labelUList &sendData, labelUList &recvData, const label communicator=0)
Exchange label with all processors (in the communicator).
static void allToAll (const char *sendData, const UList< int > &sendSizes, const UList< int > &sendOffsets, char *recvData, const UList< int > &recvSizes, const UList< int > &recvOffsets, const label communicator=0)
Exchange data with all processors (in the communicator)
static void gather (const char *sendData, int sendSize, char *recvData, const UList< int > &recvSizes, const UList< int > &recvOffsets, const label communicator=0)
Receive data from all processors on the master.
static void scatter (const char *sendData, const UList< int > &sendSizes, const UList< int > &sendOffsets, char *recvData, int recvSize, const label communicator=0)
Send data to all processors from the root of the communicator.
Static Public Attributes
static const Enum< commsTypes > commsTypeNames
Names of the communication types.
static bool floatTransfer
Should compact transfer be used in which floats replace doubles reducing the bandwidth requirement at the expense of some loss in accuracy.
static int nProcsSimpleSum
Number of processors at which the sum algorithm changes from linear to tree.
static commsTypes defaultCommsType
Default commsType.
static int nPollProcInterfaces
Number of polling cycles in processor updates.
static int maxCommsSize
Optional maximum message size (bytes)
static const int mpiBufferSize
MPI buffer-size (bytes)
static label worldComm
Default communicator (all processors)
static label warnComm
Debugging: warn for use of any communicator differing from warnComm.
Protected Attributes
commsTypes commsType_
Communications type of this stream.
Detailed Description
Inter-processor communications stream.
Source files
UPstream.H
UPstream.C
UPstreamCommsStruct.C
gatherScatter.C
combineGatherScatter.C
gatherScatterList.C
Definition at line 57 of file UPstream.H.
Member Enumeration Documentation
enum commsTypes strong
Types of communications.
Enumerator
blocking
scheduled
nonBlocking
Definition at line 64 of file UPstream.H.
Constructor & Destructor Documentation
UPstream (const commsTypes commsType) inline
Construct given optional buffer size.
Definition at line 364 of file UPstream.H.
Member Function Documentation
ClassName ("UPstream")
Foam::label allocateCommunicator (const label parent, const labelList & subRanks, const bool doPstream = true) static
Allocate a new communicator.
Definition at line 93 of file UPstream.C.
void freeCommunicator (const label communicator, const bool doPstream = true) static
Free a previously allocated communicator.
Definition at line 159 of file UPstream.C.
void freeCommunicators (const bool doPstream) static
Free all communicators.
Definition at line 186 of file UPstream.C.
int baseProcNo (const label myComm, const int procID) static
Return physical processor number (i.e. processor number in worldComm) given communicator and procssor.
Definition at line 198 of file UPstream.C.
Foam::label procNo (const label comm, const int baseProcID) static
Return processor number in communicator (given physical processor number) (= reverse of baseProcNo)
Definition at line 214 of file UPstream.C.
Foam::label procNo (const label myComm, const label currentComm, const int currentProcID) static
Return processor number in communicator (given processor number and communicator)
Definition at line 232 of file UPstream.C.
void addValidParOptions (HashTable< string > & validParOptions) static
Add the valid option this type of communications library adds/requires on the command line.
Definition at line 27 of file UPstream.C.
bool init (int & argc, char **& argv, const bool needsThread) static
Initialisation function called from main.
Spawns slave processes and initialises inter-communication
Definition at line 41 of file UPstream.C.
Referenced by ParRunControl::runPar().
bool initNull () static
Special purpose initialisation function.
Performs a basic MPI_Init without any other setup. Only used for applications that need MPI communication when OpenFOAM is running in a non-parallel mode.
Note
Behaves as a no-op if MPI has already been initialized. Fatal if MPI has already been finalized.
Definition at line 31 of file UPstream.C.
Foam::label nRequests () static
Get number of outstanding requests.
Definition at line 145 of file UPstream.C.
Referenced by Foam::evaluateConstraintTypes(), and globalIndex::gather().
void resetRequests (const label sz) static
Truncate number of outstanding requests.
Definition at line 151 of file UPstream.C.
void waitRequests (const label start = 0) static
Wait until all requests (from start onwards) have finished.
Definition at line 155 of file UPstream.C.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), Foam::evaluateConstraintTypes(), and globalIndex::gather().
void waitRequest (const label i) static
Wait until request i has finished.
Definition at line 159 of file UPstream.C.
bool finishedRequest (const label i) static
Non-blocking comms: has request i finished?
Definition at line 163 of file UPstream.C.
int allocateTag (const char * s) static
Definition at line 990 of file UPstream.C.
int allocateTag (const word & s) static
Definition at line 1019 of file UPstream.C.
void freeTag (const char * s, const int tag) static
Definition at line 1048 of file UPstream.C.
void freeTag (const word & s, const int tag) static
Definition at line 1064 of file UPstream.C.
static bool& parRun () inline static
Is this a parallel run?
Definition at line 522 of file UPstream.H.
Referenced by GAMGAgglomeration::agglomerateLduAddressing(), mergedSurf::clear(), processorFvsPatchField< Type >::clone(), processorCyclicFvsPatchField< Type >::clone(), processorFaePatchField< Type >::clone(), processorFaPatchField< Type >::clone(), fieldValue::combineFields(), Pstream::combineGather(), decompositionMethod::decompose(), metisLikeDecomp::decomposeGeneral(), cyclicACMIFvPatch::delta(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), snappyLayerDriver::doLayers(), Foam::evaluateConstraintTypes(), distributedTriSurfaceMesh::findLine(), distributedTriSurfaceMesh::findLineAll(), distributedTriSurfaceMesh::findLineAny(), distributedTriSurfaceMesh::findNearest(), Pstream::gather(), Pstream::gatherList(), distributedTriSurfaceMesh::getField(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), fileOperation::getState(), distributedTriSurfaceMesh::getVolumeType(), InflationInjection< CloudType >::InflationInjection(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), PointEdgeWave< Type, TrackingData >::iterate(), cyclicAMIFvPatch::makeWeights(), geometryBase::name(), calculatedProcessorFvPatchField< Type >::neighbProcNo(), fieldMinMax::output(), LUscalarMatrix::solve(), faMesh::updateMesh(), and Foam::warnCompatDegrees().
static bool haveThreads () inline static
Have support for threads.
Definition at line 530 of file UPstream.H.
static label nProcs (const label communicator = 0) inline static
Number of processes in parallel run.
Definition at line 538 of file UPstream.H.
Referenced by meshRefinement::balanceAndRefine(), fieldValue::combineFields(), Pstream::combineGather(), fvMeshDistribute::countCells(), metisLikeDecomp::decomposeGeneral(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), extendedCentredCellToCellStencil::extendedCentredCellToCellStencil(), extendedCentredCellToFaceStencil::extendedCentredCellToFaceStencil(), extendedCentredFaceToCellStencil::extendedCentredFaceToCellStencil(), distributedTriSurfaceMesh::findNearest(), meshRefinement::findRegions(), Pstream::gather(), PatchTools::gatherAndMerge(), geometryCloud::gatherCloud(), Pstream::gatherList(), surface::gatherSurfacePieces(), distributedTriSurfaceMesh::getVolumeType(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), distributedTriSurfaceMesh::localQueries(), regionSplit::reduceRegions(), meshRefinement::refineCandidates(), regionSizeDistribution::regionSum(), and masterUncollatedFileOperation::scatterList().
static constexpr int masterNo () inline static noexcept
Process index of the master.
Definition at line 546 of file UPstream.H.
Referenced by geometryPatches::addPatchField(), metisLikeDecomp::decomposeGeneral(), geometryCloud::gatherCloud(), geometryPatches::gatherPatchPieces(), surface::gatherSurfacePieces(), masterUncollatedFileOperation::scatterList(), and LUscalarMatrix::solve().
static bool master (const label communicator = 0) inline static
Am I the master process.
Definition at line 554 of file UPstream.H.
Referenced by Foam::addGeometryToScene(), geometryPatches::addPatchField(), mappedPatchBase::calcMapping(), logFiles::createFiles(), metisLikeDecomp::decomposeGeneral(), meshRefinement::findRegions(), PatchTools::gatherAndMerge(), geometryCloud::gatherCloud(), geometryPatches::gatherPatchPieces(), surface::gatherSurfacePieces(), fileMonitor::getState(), ensightCase::newData(), baseIOdictionary::readData(), regIOobject::readHeaderOk(), patchProbes::sampleAndWrite(), thermoCoupleProbes::sampleAndWrite(), masterUncollatedFileOperation::scatterList(), LUscalarMatrix::solve(), IOobject::typeHeaderOk(), updateMethod::updateMethod(), fileMonitor::updateStates(), Foam::warnCompatDegrees(), x3dWriter::write(), lumpedPointMovement::writeData(), vtkCloud::writeFields(), regIOobject::writeObject(), and x3dWriter::writeTemplate().
static int myProcNo (const label communicator = 0) inline static
Number of this process (starting from masterNo() = 0)
Definition at line 562 of file UPstream.H.
Referenced by geometryPatches::addPatchField(), GAMGAgglomeration::calculateRegionMaster(), backgroundMeshDecomposition::cellLevel(), fieldValue::combineFields(), Pstream::combineGather(), noDecomp::decompose(), distributedTriSurfaceMesh::distribute(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), globalIndexAndTransform::encode(), distributedTriSurfaceMesh::findNearest(), meshRefinement::findRegions(), Pstream::gather(), globalIndex::gather(), PatchTools::gatherAndMerge(), geometryCloud::gatherCloud(), GAMGAgglomeration::gatherList(), Pstream::gatherList(), geometryPatches::gatherPatchPieces(), surface::gatherSurfacePieces(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), globalIndex::inplaceToGlobal(), cellShapeControlMesh::insert(), globalIndex::isLocal(), distributedTriSurfaceMesh::localQueries(), globalIndex::localSize(), noDecomp::parallelAware(), globalIndex::range(), regionSplit::reduceRegions(), masterUncollatedFileOperation::scatterList(), globalIndex::toGlobal(), globalIndex::toLocal(), and globalIndex::whichProcID().
static label parent (const label communicator) inline static
Definition at line 567 of file UPstream.H.
static List<int>& procID (label communicator) inline static
Process ID of given process index.
Definition at line 575 of file UPstream.H.
static constexpr int firstSlave () inline static noexcept
Process index of first slave.
Definition at line 583 of file UPstream.H.
Referenced by geometryPatches::addPatchField(), geometryCloud::gatherCloud(), geometryPatches::gatherPatchPieces(), surface::gatherSurfacePieces(), and LUscalarMatrix::solve().
static int lastSlave (const label communicator = 0) inline static
Process index of last slave.
Definition at line 591 of file UPstream.H.
Referenced by geometryPatches::addPatchField(), geometryCloud::gatherCloud(), geometryPatches::gatherPatchPieces(), surface::gatherSurfacePieces(), and LUscalarMatrix::solve().
static const List<commsStruct>& linearCommunication (const label communicator = 0) inline static
Communication schedule for linear all-to-master (proc 0)
Definition at line 600 of file UPstream.H.
static const List<commsStruct>& treeCommunication (const label communicator = 0) inline static
Communication schedule for tree all-to-master (proc 0)
Definition at line 611 of file UPstream.H.
static int& msgType () inline static
Message tag of standard messages.
Definition at line 621 of file UPstream.H.
Referenced by dynamicOversetFvMesh::interpolate(), processorFaPatch::makeNonGlobalPatchPoints(), regionModel::mapRegionPatchField(), processorFvPatch::neighbProcNo(), globalIndex::offset(), lduMesh::reduce(), and LUscalarMatrix::solve().
commsTypes commsType () const inline
Get the communications type of the stream.
Definition at line 630 of file UPstream.H.
commsTypes commsType (const commsTypes ct) inline
Set the communications type of the stream.
Definition at line 638 of file UPstream.H.
void exit (int errnum = 1) static
Exit program.
Definition at line 52 of file UPstream.C.
Referenced by ParRunControl::runPar().
void abort () static
Abort program.
Definition at line 59 of file UPstream.C.
References Foam::exit().
void allToAll (const labelUList & sendData, labelUList & recvData, const label communicator = 0) static
Exchange label with all processors (in the communicator).
sendData[proci] is the label to send to proci. After return recvData contains the data from the other processors.
Definition at line 93 of file UPstream.C.
void allToAll (const char * sendData, const UList< int > & sendSizes, const UList< int > & sendOffsets, char * recvData, const UList< int > & recvSizes, const UList< int > & recvOffsets, const label communicator = 0) static
Exchange data with all processors (in the communicator)
sendSizes, sendOffsets give (per processor) the slice of sendData to send, similarly recvSizes, recvOffsets give the slice of recvData to receive
Definition at line 529 of file UPstream.C.
void gather (const char * sendData, int sendSize, char * recvData, const UList< int > & recvSizes, const UList< int > & recvOffsets, const label communicator = 0) static
Receive data from all processors on the master.
Definition at line 104 of file UPstream.C.
References UList< T >::deepCopy().
void scatter (const char * sendData, const UList< int > & sendSizes, const UList< int > & sendOffsets, char * recvData, int recvSize, const label communicator = 0) static
Send data to all processors from the root of the communicator.
Definition at line 119 of file UPstream.C.
Member Data Documentation
const Foam::Enum< Foam::UPstream::commsTypes > commsTypeNames static
Names of the communication types.
Definition at line 74 of file UPstream.H.
Referenced by addcommsTypeToOpt::writeData().
commsTypes commsType_ protected
Communications type of this stream.
Definition at line 305 of file UPstream.H.
bool floatTransfer static
Should compact transfer be used in which floats replace doubles reducing the bandwidth requirement at the expense of some loss in accuracy.
Definition at line 320 of file UPstream.H.
int nProcsSimpleSum static
Number of processors at which the sum algorithm changes from linear to tree.
Definition at line 326 of file UPstream.H.
Foam::UPstream::commsTypes defaultCommsType static
Default commsType.
Definition at line 331 of file UPstream.H.
Referenced by mapDistributeBase::distribute(), distributedTriSurfaceMesh::distribute(), Foam::evaluateConstraintTypes(), lduMatrix::initMatrixInterfaces(), mapDistributeBase::reverseDistribute(), and addcommsTypeToOpt::writeData().
int nPollProcInterfaces static
Number of polling cycles in processor updates.
Definition at line 336 of file UPstream.H.
int maxCommsSize static
Optional maximum message size (bytes)
Definition at line 341 of file UPstream.H.
const int mpiBufferSize static
MPI buffer-size (bytes)
Definition at line 346 of file UPstream.H.
Referenced by attachOurBuffers().
Foam::label worldComm static
Default communicator (all processors)
Definition at line 351 of file UPstream.H.
Foam::label warnComm static
Debugging: warn for use of any communicator differing from warnComm.
Definition at line 356 of file UPstream.H.
Referenced by Foam::reduce().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.C
src/Pstream/dummy/UPstream.C
src/Pstream/mpi/UPstream.C