OpenFOAM: pointEdgePoint Class Reference
pointEdgePoint Class Reference
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Public Member Functions
pointEdgePoint ()
Construct null.
pointEdgePoint (const point &, const scalar)
Construct from origin, distance.
pointEdgePoint (const pointEdgePoint &)
Construct as copy.
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const pointEdgePoint &, const scalar tol, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const pointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const pointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const pointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const pointEdgePoint &, TrackingData &td) const
Same (like operator==)
bool operator== (const pointEdgePoint &) const
bool operator!= (const pointEdgePoint &) const
Friends
Ostream & operator<< (Ostream &, const pointEdgePoint &)
Istream & operator>> (Istream &, pointEdgePoint &)
Detailed Description
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Source files
pointEdgePoint.H
pointEdgePointI.H
pointEdgePoint.C
Definition at line 63 of file pointEdgePoint.H.
Constructor & Destructor Documentation
pointEdgePoint () inline
Construct null.
Definition at line 116 of file pointEdgePointI.H.
pointEdgePoint (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 125 of file pointEdgePointI.H.
pointEdgePoint (const pointEdgePoint & wpt) inline
Construct as copy.
Definition at line 136 of file pointEdgePointI.H.
Member Function Documentation
const Foam::point & origin () const inline
Definition at line 145 of file pointEdgePointI.H.
Referenced by pointEdgePoint::operator!=().
Foam::scalar distSqr () const inline
Definition at line 151 of file pointEdgePointI.H.
References origin_().
Referenced by pointEdgePoint::operator!=().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 158 of file pointEdgePointI.H.
bool sameGeometry (const pointEdgePoint & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 167 of file pointEdgePointI.H.
void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Convert origin to relative vector to leaving point.
(= point coordinate)
Definition at line 195 of file pointEdgePointI.H.
void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Convert relative origin to absolute by adding entering point.
Definition at line 221 of file pointEdgePointI.H.
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 208 of file pointEdgePointI.H.
References origin_().
bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const pointEdgePoint & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 236 of file pointEdgePointI.H.
bool updatePoint (const polyMesh & mesh, const label pointi, const pointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 252 of file pointEdgePointI.H.
bool updatePoint (const pointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 267 of file pointEdgePointI.H.
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const pointEdgePoint & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 280 of file pointEdgePointI.H.
bool equal (const pointEdgePoint & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 296 of file pointEdgePointI.H.
bool operator== (const pointEdgePoint & rhs) const inline
Definition at line 307 of file pointEdgePointI.H.
References Foam::operator==().
Referenced by PointData< DataType >::operator!=().
bool operator!= (const pointEdgePoint & rhs) const inline
Definition at line 314 of file pointEdgePointI.H.
References pointEdgePoint::distSqr(), and pointEdgePoint::origin().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const pointEdgePoint &) friend
Istream& operator>> (Istream & , pointEdgePoint &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PointEdgeWave/pointEdgePoint.H
src/meshTools/algorithms/PointEdgeWave/pointEdgePointI.H