OpenFOAM: eConstThermo< EquationOfState > Class Template Reference
eConstThermo< EquationOfState > Class Template Reference
Thermodynamics
Constant properties thermodynamics package templated on an equation of state.
Public Member Functions
eConstThermo (const dictionary &dict)
Construct from dictionary.
eConstThermo (const word &, const eConstThermo &)
Construct as named copy.
autoPtr< eConstThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar Cv (const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kg K)].
scalar Es (const scalar p, const scalar T) const
Sensible internal energy [J/kg].
scalar Ea (const scalar p, const scalar T) const
Absolute internal energy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar dGdT (const scalar p, const scalar T) const
Derivative of Gibbs free energy w.r.t. temperature.
scalar dCpdT (const scalar p, const scalar T) const
Temperature derivative of heat capacity at constant pressure.
void write (Ostream &os) const
Write to Ostream.
void operator+= (const eConstThermo &)
Static Public Member Functions
static autoPtr< eConstThermo > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Friends
eConstThermo operator+ (const eConstThermo &, const eConstThermo &)
eConstThermo operator* (const scalar, const eConstThermo &)
eConstThermo operator== (const eConstThermo &, const eConstThermo &)
Ostream & operator (Ostream &, const eConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::eConstThermo< EquationOfState >
Constant properties thermodynamics package templated on an equation of state.
Source files
eConstThermo.H
eConstThermoI.H
eConstThermo.C
Definition at line 49 of file eConstThermo.H.
Constructor & Destructor Documentation
eConstThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 27 of file eConstThermo.C.
eConstThermo (const word & , const eConstThermo< EquationOfState > &) inline
Construct as named copy.
Member Function Documentation
Foam::autoPtr< Foam::eConstThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 54 of file eConstThermoI.H.
Foam::autoPtr< Foam::eConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Definition at line 62 of file eConstThermoI.H.
References Foam::New().
static word typeName () inline static
Return the instantiated type name.
Definition at line 147 of file eConstThermo.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 72 of file eConstThermoI.H.
Foam::scalar Cv (const scalar p, const scalar T) const inline
Heat capacity at constant volume [J/(kg K)].
Definition at line 82 of file eConstThermoI.H.
References Foam::T().
Foam::scalar Es (const scalar p, const scalar T) const inline
Sensible internal energy [J/kg].
Definition at line 93 of file eConstThermoI.H.
References Cv.
Foam::scalar Ea (const scalar p, const scalar T) const inline
Absolute internal energy [J/kg].
Definition at line 104 of file eConstThermoI.H.
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 114 of file eConstThermoI.H.
References Es(), and Foam::T().
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 122 of file eConstThermoI.H.
References Hf_().
Foam::scalar dGdT (const scalar p, const scalar T) const inline
Derivative of Gibbs free energy w.r.t. temperature.
Definition at line 133 of file eConstThermoI.H.
References Cp, Foam::log(), and Foam::constant::standard::Tstd.
Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Temperature derivative of heat capacity at constant pressure.
Definition at line 144 of file eConstThermoI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 38 of file eConstThermo.C.
void operator+= (const eConstThermo< EquationOfState > &) inline
Definition at line 156 of file eConstThermoI.H.
Friends And Related Function Documentation
eConstThermo operator+ (const eConstThermo< EquationOfState > & , const eConstThermo< EquationOfState > &) friend
eConstThermo operator* (const scalar , const eConstThermo< EquationOfState > &) friend
eConstThermo operator== (const eConstThermo< EquationOfState > & , const eConstThermo< EquationOfState > &) friend
Ostream& operator (Ostream & , const eConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/eConst/eConstThermo.H
src/thermophysicalModels/specie/thermo/eConst/eConstThermo.C
src/thermophysicalModels/specie/thermo/eConst/eConstThermoI.H