OpenFOAM: IndirectListBase< T, Addr > Class Template Reference
IndirectListBase< T, Addr > Class Template Reference
Base for lists with indirect addressing, templated on the list contents type and the addressing type. Storage for both values and addressing is held outside of the class.
Classes
class const_iterator
A const iterator for an indirect list.
class iterator
A non-const iterator for an indirect list.
Public Types
typedef T value_type
Type of values the list contains.
typedef T * pointer
The pointer type for non-const access to value_type items.
typedef const T * const_pointer
The pointer type for const access to value_type items.
typedef T & reference
The type used for storing into value_type objects.
typedef const T & const_reference
The type used for reading from constant value_type objects.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef Addr addressing_type
The addressing type (non-stl definition)
Public Member Functions
IndirectListBase ()=delete
No null construct.
IndirectListBase (const UList< T > &values, const Addr &addr)
Store references to the values list and the addressing array.
label size () const
The number of elements in the list.
bool empty () const
True if the list is empty (ie, size() is zero).
bool uniform () const
True if all entries have identical values, and list is non-empty.
T & first ()
The first element of the list.
const T & first () const
The first element of the list.
T & last ()
The last element of the list.
const T & last () const
The last element of the list.
const UList< T > & values () const
The list of values (without addressing)
UList< T > & values ()
The list of values (without addressing)
const Addr & addressing () const
The addressing used for the list.
label find (const T &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const T &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const T &val, const label start=0) const
True if the value if found in the list. Linear search.
List< T > operator() () const
Return the addressed elements as a List.
T & operator[] (const label i)
Non-const access to an element in the list.
const T & operator[] (const label i) const
Const access to an element in the list.
void operator= (const T &val)
Assign all addressed elements to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (const UList< T > &rhs)
Deep copy values from a list of the addressed elements.
void operator= (const IndirectListBase< T, Addr > &rhs)
Deep copy values from a list of the addressed elements.
template<class AnyAddr >
void operator= (const IndirectListBase< T, AnyAddr > &rhs)
Deep copy values from a list of the addressed elements.
iterator begin ()
Return an iterator at begin of list.
iterator end ()
Return an iterator at end of list.
const_iterator cbegin () const
Return a const_iterator at begin of list.
const_iterator cend () const
Return a const_iterator at end of list.
const_iterator begin () const
Return a const_iterator at end of list.
const_iterator end () const
Return a const_iterator at end of list.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
Protected Member Functions
template<class ListType >
void copyList (const ListType &rhs)
Copy values The number of elements in the list.
Detailed Description
template<class T, class Addr>
class Foam::IndirectListBase< T, Addr >
Base for lists with indirect addressing, templated on the list contents type and the addressing type. Storage for both values and addressing is held outside of the class.
Source files
IndirectListBase.H
IndirectListBase.H
IndirectListBase.C
IndirectListBaseI.H
IndirectListBaseIO.C
Definition at line 53 of file IndirectListBase.H.
Member Typedef Documentation
typedef T value_type
Type of values the list contains.
Definition at line 86 of file IndirectListBase.H.
typedef T* pointer
The pointer type for non-const access to value_type items.
Definition at line 91 of file IndirectListBase.H.
typedef const T* const_pointer
The pointer type for const access to value_type items.
Definition at line 96 of file IndirectListBase.H.
typedef T& reference
The type used for storing into value_type objects.
Definition at line 101 of file IndirectListBase.H.
typedef const T& const_reference
The type used for reading from constant value_type objects.
Definition at line 106 of file IndirectListBase.H.
typedef label size_type
The type to represent the size of a UList.
Definition at line 111 of file IndirectListBase.H.
typedef label difference_type
The difference between iterator objects.
Definition at line 116 of file IndirectListBase.H.
typedef Addr addressing_type
The addressing type (non-stl definition)
Definition at line 126 of file IndirectListBase.H.
Constructor & Destructor Documentation
IndirectListBase () delete
No null construct.
IndirectListBase (const UList< T > & values, const Addr & addr) inline
Store references to the values list and the addressing array.
Definition at line 50 of file IndirectListBaseI.H.
Member Function Documentation
void copyList (const ListType & rhs) inline protected
Copy values The number of elements in the list.
Definition at line 26 of file IndirectListBaseI.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and i.
label size () const inline
The number of elements in the list.
Definition at line 154 of file IndirectListBase.H.
Referenced by IndirectListBase< T, Addr >::writeList().
bool empty () const inline
True if the list is empty (ie, size() is zero).
Definition at line 162 of file IndirectListBase.H.
bool uniform () const inline
True if all entries have identical values, and list is non-empty.
Definition at line 63 of file IndirectListBaseI.H.
Referenced by IndirectListBase< T, Addr >::writeList().
T& first () inline
The first element of the list.
Definition at line 175 of file IndirectListBase.H.
const T& first () const inline
The first element of the list.
Definition at line 183 of file IndirectListBase.H.
T& last () inline
The last element of the list.
Definition at line 191 of file IndirectListBase.H.
const T& last () const inline
The last element of the list.
Definition at line 199 of file IndirectListBase.H.
const UList<T>& values () const inline
The list of values (without addressing)
Definition at line 207 of file IndirectListBase.H.
UList<T>& values () inline
The list of values (without addressing)
Definition at line 215 of file IndirectListBase.H.
const Addr& addressing () const inline
The addressing used for the list.
Definition at line 223 of file IndirectListBase.H.
Foam::label find (const T & val, const label start = 0) const
Find index of the first occurrence of the value.
When start is specified, any occurences before start are ignored. Linear search.
Returns
-1 if not found.
Definition at line 25 of file IndirectListBase.C.
References i, List_CONST_ACCESS, and T.
Foam::label rfind (const T & val, const label pos = -1) const
Find index of the last occurrence of the value.
When pos is specified, any occurrences after pos are ignored. Linear search.
Returns
-1 if not found.
Definition at line 51 of file IndirectListBase.C.
bool found (const T & val, const label start = 0) const inline
True if the value if found in the list. Linear search.
Definition at line 88 of file IndirectListBaseI.H.
Foam::List< T > operator() () const inline
Return the addressed elements as a List.
Definition at line 101 of file IndirectListBaseI.H.
T & operator[] (const label i) inline
Non-const access to an element in the list.
Definition at line 118 of file IndirectListBaseI.H.
const T & operator[] (const label i) const inline
Const access to an element in the list.
Definition at line 126 of file IndirectListBaseI.H.
References i.
void operator= (const T & val) inline
Assign all addressed elements to the given value.
Definition at line 133 of file IndirectListBaseI.H.
References i.
void operator= (const zero) inline
Assignment of all entries to zero.
Definition at line 144 of file IndirectListBaseI.H.
References Foam::val.
void operator= (const UList< T > & rhs) inline
Deep copy values from a list of the addressed elements.
Fatal if list sizes are not identical
Definition at line 156 of file IndirectListBaseI.H.
void operator= (const IndirectListBase< T, Addr > & rhs) inline
Deep copy values from a list of the addressed elements.
Fatal if list sizes are not identical
Definition at line 166 of file IndirectListBaseI.H.
void operator= (const IndirectListBase< T, AnyAddr > & rhs) inline
Deep copy values from a list of the addressed elements.
Fatal if list sizes are not identical
Definition at line 177 of file IndirectListBaseI.H.
iterator begin () inline
Return an iterator at begin of list.
Definition at line 410 of file IndirectListBase.H.
Referenced by bitSet::bitSet(), bitSet::clone(), and bitSet::unset().
iterator end () inline
Return an iterator at end of list.
Definition at line 418 of file IndirectListBase.H.
Referenced by bitSet::bitSet(), bitSet::clone(), and bitSet::unset().
const_iterator cbegin () const inline
Return a const_iterator at begin of list.
Definition at line 429 of file IndirectListBase.H.
const_iterator cend () const inline
Return a const_iterator at end of list.
Definition at line 437 of file IndirectListBase.H.
const_iterator begin () const inline
Return a const_iterator at end of list.
Definition at line 445 of file IndirectListBase.H.
const_iterator end () const inline
Return a const_iterator at end of list.
Definition at line 453 of file IndirectListBase.H.
Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
Using '0' suppresses line-breaks entirely.
Definition at line 31 of file IndirectListBaseIO.C.
References Ostream::beginRawWrite(), IOstream::check(), Ostream::endRawWrite(), IOstreamOption::format(), FUNCTION_NAME, i, Foam::nl, IndirectListBase< T, Addr >::size(), T, IndirectListBase< T, Addr >::uniform(), and Ostream::writeRaw().
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBase.H
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBase.C
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBaseI.H
src/OpenFOAM/containers/IndirectLists/IndirectListBase/IndirectListBaseIO.C