OpenFOAM: facePointPatch Class Reference
facePointPatch Class Reference
A pointPatch based on a polyPatch.
Public Member Functions
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, facePointPatch, polyPatch,(const polyPatch &patch, const pointBoundaryMesh &bm),(patch, bm))
facePointPatch (const polyPatch &p, const pointBoundaryMesh &pm)
Construct from polyPatch and boundary mesh.
virtual ~facePointPatch ()=default
Destructor.
virtual const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label size () const
Return size.
virtual label index () const
Return the index of this patch in the pointBoundaryMesh.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const
Return mesh points.
virtual const pointField & localPoints () const
Return pointField of points in patch.
virtual const vectorField & pointNormals () const
Return point unit normals.
Public Member Functions inherited from pointPatch
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
Construct from boundary mesh.
virtual ~pointPatch ()=default
Destructor.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Static Public Member Functions
static autoPtr< facePointPatch > New (const polyPatch &, const pointBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
facePointPatch (const facePointPatch &)=delete
No copy construct.
void operator= (const facePointPatch &)=delete
No copy assignment.
Protected Member Functions inherited from pointPatch
pointPatch (const pointPatch &)=delete
No copy construct.
void operator= (const pointPatch &)=delete
No copy assignment.
Protected Attributes
const polyPatch & polyPatch_
Reference to the underlying polyPatch.
Friends
class processorPointPatch
class cyclicPointPatch
Detailed Description
A pointPatch based on a polyPatch.
Source files
facePointPatch.H
facePointPatch.C
newPointPatch.C
Definition at line 53 of file facePointPatch.H.
Constructor & Destructor Documentation
facePointPatch (const facePointPatch &) protected delete
No copy construct.
facePointPatch (const polyPatch & p, const pointBoundaryMesh & pm)
Construct from polyPatch and boundary mesh.
Definition at line 76 of file facePointPatch.C.
virtual ~facePointPatch () virtual default
Destructor.
Member Function Documentation
void initGeometry (PstreamBuffers &) protected virtual
Initialise the calculation of the patch geometry.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 47 of file facePointPatch.C.
Referenced by facePointPatch::updateMesh().
void calcGeometry (PstreamBuffers &) protected virtual
Calculate the patch geometry.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and coupledFacePointPatch.
Definition at line 51 of file facePointPatch.C.
void initMovePoints (PstreamBuffers & , const pointField &) protected virtual
Initialise the patches for moving points.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 55 of file facePointPatch.C.
void movePoints (PstreamBuffers & , const pointField &) protected virtual
Correct patches after moving points.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 59 of file facePointPatch.C.
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 63 of file facePointPatch.C.
Referenced by cyclicACMIPointPatch::updateMesh(), and cyclicAMIPointPatch::updateMesh().
void updateMesh (PstreamBuffers &) protected virtual
Update of the patch topology.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch, and cyclicAMIPointPatch.
Definition at line 69 of file facePointPatch.C.
References facePointPatch::initGeometry().
void operator= (const facePointPatch &) protected delete
No copy assignment.
TypeName (polyPatch:: typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr , facePointPatch , polyPatch , (const polyPatch &patch, const pointBoundaryMesh &bm) , (patch, bm))
Foam::autoPtr< Foam::facePointPatch > New (const polyPatch & patch, const pointBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from polyPatch.
Definition at line 27 of file facePointPatchNew.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, and facePointPatch::patch().
Referenced by pointBoundaryMesh::pointBoundaryMesh().
virtual const polyPatch& patch () const inline virtual
Return the polyPatch.
Definition at line 172 of file facePointPatch.H.
References polyPatch::coupled(), and facePointPatch::polyPatch_.
Referenced by facePointPatch::New().
virtual const word& name () const inline virtual
Return name.
Implements pointPatch.
Definition at line 180 of file facePointPatch.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::meshPoints(), and facePointPatch::polyPatch_.
virtual label size () const inline virtual
Return size.
Implements pointPatch.
Definition at line 188 of file facePointPatch.H.
virtual label index () const inline virtual
Return the index of this patch in the pointBoundaryMesh.
Implements pointPatch.
Definition at line 196 of file facePointPatch.H.
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented from pointPatch.
Reimplemented in cyclicACMIPointPatch.
Definition at line 204 of file facePointPatch.H.
virtual const labelList& meshPoints () const inline virtual
Return mesh points.
Implements pointPatch.
Definition at line 212 of file facePointPatch.H.
virtual const pointField& localPoints () const inline virtual
Return pointField of points in patch.
Implements pointPatch.
Definition at line 220 of file facePointPatch.H.
virtual const vectorField& pointNormals () const inline virtual
Return point unit normals.
Implements pointPatch.
Reimplemented in cyclicSlipPointPatch, and nonuniformTransformCyclicPointPatch.
Definition at line 228 of file facePointPatch.H.
Friends And Related Function Documentation
friend class processorPointPatch friend
Definition at line 115 of file facePointPatch.H.
friend class cyclicPointPatch friend
Definition at line 116 of file facePointPatch.H.
Member Data Documentation
const polyPatch& polyPatch_ protected
Reference to the underlying polyPatch.
Definition at line 64 of file facePointPatch.H.
Referenced by facePointPatch::name(), and facePointPatch::patch().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/pointMesh/pointPatches/facePointPatch/facePointPatch.H
src/OpenFOAM/meshes/pointMesh/pointPatches/facePointPatch/facePointPatch.C
src/OpenFOAM/meshes/pointMesh/pointPatches/facePointPatch/facePointPatchNew.C