OpenFOAM: rPolynomial< Specie > Class Template Reference
rPolynomial< Specie > Class Template Reference
Reciprocal polynomial equation of state for liquids and solids.
Public Member Functions
rPolynomial (const Specie &sp, const coeffList &coeffs)
Construct from components.
rPolynomial (const dictionary &dict)
Construct from dictionary.
rPolynomial (const word &name, const rPolynomial &)
Construct as named copy.
autoPtr< rPolynomial > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar H (const scalar p, const scalar T) const
Return enthalpy departure [J/kg].
scalar Cp (scalar p, scalar T) const
Return Cp departure [J/(kg K].
scalar E (const scalar p, const scalar T) const
Return internal energy departure [J/kg].
scalar Cv (scalar p, scalar T) const
Return Cv departure [J/(kg K].
scalar S (const scalar p, const scalar T) const
Return entropy [J/kg/K].
scalar psi (scalar p, scalar T) const
Return compressibility [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar CpMCv (scalar p, scalar T) const
Return (Cp - Cv) [J/(kg K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const rPolynomial &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< rPolynomial > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
rPolynomial operator+ (const rPolynomial &, const rPolynomial &)
rPolynomial operator* (const scalar s, const rPolynomial &)
rPolynomial operator== (const rPolynomial &, const rPolynomial &)
Ostream & operator (Ostream &, const rPolynomial &)
Detailed Description
template<class Specie>
class Foam::rPolynomial< Specie >
Reciprocal polynomial equation of state for liquids and solids.
This polynomial for the reciprocal of the density provides a much better fit than the equivalent polynomial for the density and has the advantage that it support coefficient mixing to support liquid and solid mixtures in an efficient manner.
Usage
Property Description
C Density polynomial coefficients
Example of the specification of the equation of state for pure water:
    equationOfState
    {
        C (0.001278 -2.1055e-06 3.9689e-09 4.3772e-13 -2.0225e-16);
    }
Note: This fit is based on the small amount of data which is freely available for the range 20-65degC and 1-100bar.
Source files
rPolynomial.H
rPolynomialI.H
rPolynomial.C
Definition at line 77 of file rPolynomial.H.
Constructor & Destructor Documentation
rPolynomial (const Specie & sp, const coeffList & coeffs) inline
Construct from components.
Definition at line 27 of file rPolynomialI.H.
rPolynomial (const dictionary & dict)
Construct from dictionary.
Definition at line 27 of file rPolynomial.C.
rPolynomial (const word & name, const rPolynomial< Specie > &) inline
Construct as named copy.
Member Function Documentation
Foam::autoPtr< Foam::rPolynomial< Specie > > clone () const inline
Construct and return a clone.
Definition at line 53 of file rPolynomialI.H.
Foam::autoPtr< Foam::rPolynomial< Specie > > New (const dictionary & dict) inline static
Definition at line 62 of file rPolynomialI.H.
static word typeName () inline static
Return the instantiated type name.
Definition at line 186 of file rPolynomial.H.
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 73 of file rPolynomialI.H.
Foam::scalar H (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kg].
Definition at line 80 of file rPolynomialI.H.
References p.
Foam::scalar Cp (scalar p, scalar T) const inline
Return Cp departure [J/(kg K].
Definition at line 87 of file rPolynomialI.H.
Foam::scalar E (const scalar p, const scalar T) const inline
Return internal energy departure [J/kg].
Definition at line 94 of file rPolynomialI.H.
Foam::scalar Cv (scalar p, scalar T) const inline
Return Cv departure [J/(kg K].
Definition at line 101 of file rPolynomialI.H.
Foam::scalar S (const scalar p, const scalar T) const inline
Return entropy [J/kg/K].
Definition at line 108 of file rPolynomialI.H.
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility [s^2/m^2].
Definition at line 115 of file rPolynomialI.H.
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 122 of file rPolynomialI.H.
References rho, Foam::sqr(), and Foam::T().
Foam::scalar CpMCv (scalar p, scalar T) const inline
Return (Cp - Cv) [J/(kg K].
Definition at line 129 of file rPolynomialI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 37 of file rPolynomial.C.
void operator+= (const rPolynomial< Specie > &) inline
Definition at line 139 of file rPolynomialI.H.
void operator*= (const scalar s) inline
Definition at line 154 of file rPolynomialI.H.
References rp(), and Y.
Friends And Related Function Documentation
rPolynomial operator+ (const rPolynomial< Specie > & , const rPolynomial< Specie > &) friend
rPolynomial operator* (const scalar s, const rPolynomial< Specie > &) friend
rPolynomial operator== (const rPolynomial< Specie > & , const rPolynomial< Specie > &) friend
Ostream& operator (Ostream & , const rPolynomial< Specie > &) friend
Member Data Documentation
const bool incompressible = false static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 197 of file rPolynomial.H.
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 202 of file rPolynomial.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/rPolynomial/rPolynomial.H
src/thermophysicalModels/specie/equationOfState/rPolynomial/rPolynomial.C
src/thermophysicalModels/specie/equationOfState/rPolynomial/rPolynomialI.H