OpenFOAM: mapPolyMesh Class Reference
mapPolyMesh Class Reference
Class containing mesh-to-mesh mapping information after a change in polyMesh topology.
Public Member Functions
mapPolyMesh (const polyMesh &mesh)
Construct from mesh.
mapPolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const labelList &pointMap, const List< objectMap > &pointsFromPoints, const labelList &faceMap, const List< objectMap > &facesFromPoints, const List< objectMap > &facesFromEdges, const List< objectMap > &facesFromFaces, const labelList &cellMap, const List< objectMap > &cellsFromPoints, const List< objectMap > &cellsFromEdges, const List< objectMap > &cellsFromFaces, const List< objectMap > &cellsFromCells, const labelList &reversePointMap, const labelList &reverseFaceMap, const labelList &reverseCellMap, const labelHashSet &flipFaceFlux, const labelListList &patchPointMap, const labelListList &pointZoneMap, const labelListList &faceZonePointMap, const labelListList &faceZoneFaceMap, const labelListList &cellZoneMap, const pointField &preMotionPoints, const labelList &oldPatchStarts, const labelList &oldPatchNMeshPoints, const autoPtr< scalarField > &oldCellVolumesPtr)
Construct from components. Copy (except for oldCellVolumes).
mapPolyMesh (const polyMesh &mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList &pointMap, List< objectMap > &pointsFromPoints, labelList &faceMap, List< objectMap > &facesFromPoints, List< objectMap > &facesFromEdges, List< objectMap > &facesFromFaces, labelList &cellMap, List< objectMap > &cellsFromPoints, List< objectMap > &cellsFromEdges, List< objectMap > &cellsFromFaces, List< objectMap > &cellsFromCells, labelList &reversePointMap, labelList &reverseFaceMap, labelList &reverseCellMap, labelHashSet &flipFaceFlux, labelListList &patchPointMap, labelListList &pointZoneMap, labelListList &faceZonePointMap, labelListList &faceZoneFaceMap, labelListList &cellZoneMap, pointField &preMotionPoints, labelList &oldPatchStarts, labelList &oldPatchNMeshPoints, autoPtr< scalarField > &oldCellVolumesPtr, const bool reuse)
Construct from components and optionally reuse storage.
const polyMesh & mesh () const
Return polyMesh.
label nOldPoints () const
Number of old points.
label nOldInternalFaces () const
Number of old internal faces.
label nOldFaces () const
Number of old faces.
label nOldCells () const
Number of old cells.
const labelList & pointMap () const
Old point map.
const List< objectMap > & pointsFromPointsMap () const
Points originating from points.
const labelList & faceMap () const
Old face map.
const List< objectMap > & facesFromPointsMap () const
Faces inflated from points.
const List< objectMap > & facesFromEdgesMap () const
Faces inflated from edges.
const List< objectMap > & facesFromFacesMap () const
Faces originating from faces.
const labelList & cellMap () const
Old cell map.
const List< objectMap > & cellsFromPointsMap () const
Cells inflated from points.
const List< objectMap > & cellsFromEdgesMap () const
Cells inflated from edges.
const List< objectMap > & cellsFromFacesMap () const
Cells inflated from faces.
const List< objectMap > & cellsFromCellsMap () const
Cells originating from cells.
const labelList & reversePointMap () const
Reverse point map.
label mergedPoint (const label oldPointi) const
If point is removed return point (on new mesh) it merged.
const labelList & reverseFaceMap () const
Reverse face map.
label mergedFace (const label oldFacei) const
If face is removed return face (on new mesh) it merged into.
const labelList & reverseCellMap () const
Reverse cell map.
label mergedCell (const label oldCelli) const
If cell is removed return cell (on new mesh) it merged into.
const labelHashSet & flipFaceFlux () const
Map of flipped face flux faces.
const labelListList & patchPointMap () const
Patch point renumbering.
const labelListList & pointZoneMap () const
Point zone renumbering.
const labelListList & faceZonePointMap () const
Face zone point renumbering.
const labelListList & faceZoneFaceMap () const
Face zone face renumbering.
const labelListList & cellZoneMap () const
Cell zone renumbering.
const pointField & preMotionPoints () const
Pre-motion point positions.
bool hasMotionPoints () const
Has valid preMotionPoints?
const labelList & oldPatchSizes () const
Return list of the old patch sizes.
const labelList & oldPatchStarts () const
Return list of the old patch start labels.
const labelList & oldPatchNMeshPoints () const
Return numbers of mesh points per old patch.
bool hasOldCellVolumes () const
const scalarField & oldCellVolumes () const
Detailed Description
Class containing mesh-to-mesh mapping information after a change in polyMesh topology.
General:
pointMap/faceMap/cellMap:
from current mesh back to previous mesh. (so to 'pull' the information onto the current mesh)
reversePointMap/faceMap/cellMap:
from previous mesh to current. (so to 'push' information)
In the topology change points/faces/cells
can be unchanged. (faces might be renumbered though)
can be removed (into nothing)
can be removed into/merged with existing same entity (so point merged with other point, face with other face, cell with other cell. Note that probably only cell with cell is relevant)
can be added from existing same 'master' entity (so point from point, face from face and cell from cell)
can be inflated: face out of edge or point, cell out of face, edge or point.
can be appended: added 'out of nothing'.
All this information is necessary to correctly map fields.
points
unchanged:
pointMap[pointi] contains old point label
reversePointMap[oldPointi] contains new point label
removed:
reversePointMap[oldPointi] contains -1
merged into point:
reversePointMap[oldPointi] contains <-1 : -newPointi-2
pointMap[pointi] contains the old master point label
pointsFromPoints gives for pointi all the old point labels (including the old master point!)
added-from-same:
pointMap[pointi] contains the old master point label
appended:
pointMap[pointi] contains -1
faces
unchanged:
faceMap[facei] contains old face label
reverseFaceMap[oldFacei] contains new face label
removed:
reverseFaceMap[oldFacei] contains -1
merged into face:
reverseFaceMap[oldFacei] contains <-1 : -newFacei-2
faceMap[facei] contains the old master face label
facesFromFaces gives for facei all the old face labels (including the old master face!)
added-from-same:
faceMap[facei] contains the old master face label
inflated-from-edge:
faceMap[facei] contains -1
facesFromEdges contains an entry with
facei
list of faces(*) on old mesh that connected to the old edge
inflated-from-point:
faceMap[facei] contains -1
facesFromPoints contains an entry with
facei
list of faces(*) on old mesh that connected to the old point
appended:
faceMap[facei] contains -1
Note (*)
if the newly inflated face is a boundary face the list of faces will only be boundary faces; if the new face is an internal face they will only be internal faces.
cells
unchanged:
cellMap[celli] contains old cell label
reverseCellMap[oldCelli] contains new cell label
removed:
reverseCellMap[oldCelli] contains -1
merged into cell:
reverseCellMap[oldCelli] contains <-1 : -newCelli-2
cellMap[celli] contains the old master cell label
cellsFromCells gives for celli all the old cell labels (including the old master cell!)
added-from-same:
cellMap[celli] contains the old master cell label
inflated-from-face:
cellMap[celli] contains -1
cellsFromFaces contains an entry with
celli
list of cells on old mesh that connected to the old face
inflated-from-edge:
cellMap[celli] contains -1
cellsFromEdges contains an entry with
celli
list of cells on old mesh that connected to the old edge
inflated-from-point:
cellMap[celli] contains -1
cellsFromPoints contains an entry with
celli
list of cells on old mesh that connected to the old point
appended:
cellMap[celli] contains -1
Source files
mapPolyMesh.H
mapPolyMesh.C
Definition at line 156 of file mapPolyMesh.H.
Constructor & Destructor Documentation
mapPolyMesh (const polyMesh & mesh)
Construct from mesh.
Definition at line 27 of file mapPolyMesh.C.
References polyMesh::boundaryMesh(), polyMesh::faceZones(), forAll, Foam::identity(), nPoints, polyMesh::pointZones(), and UPtrList< T >::size().
mapPolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, const labelList & pointMap, const List< objectMap > & pointsFromPoints, const labelList & faceMap, const List< objectMap > & facesFromPoints, const List< objectMap > & facesFromEdges, const List< objectMap > & facesFromFaces, const labelList & cellMap, const List< objectMap > & cellsFromPoints, const List< objectMap > & cellsFromEdges, const List< objectMap > & cellsFromFaces, const List< objectMap > & cellsFromCells, const labelList & reversePointMap, const labelList & reverseFaceMap, const labelList & reverseCellMap, const labelHashSet & flipFaceFlux, const labelListList & patchPointMap, const labelListList & pointZoneMap, const labelListList & faceZonePointMap, const labelListList & faceZoneFaceMap, const labelListList & cellZoneMap, const pointField & preMotionPoints, const labelList & oldPatchStarts, const labelList & oldPatchNMeshPoints, const autoPtr< scalarField > & oldCellVolumesPtr)
Construct from components. Copy (except for oldCellVolumes).
Definition at line 93 of file mapPolyMesh.C.
References polyMesh::cellZones(), Foam::identity(), and UPtrList< T >::size().
mapPolyMesh (const polyMesh & mesh, const label nOldPoints, const label nOldFaces, const label nOldCells, labelList & pointMap, List< objectMap > & pointsFromPoints, labelList & faceMap, List< objectMap > & facesFromPoints, List< objectMap > & facesFromEdges, List< objectMap > & facesFromFaces, labelList & cellMap, List< objectMap > & cellsFromPoints, List< objectMap > & cellsFromEdges, List< objectMap > & cellsFromFaces, List< objectMap > & cellsFromCells, labelList & reversePointMap, labelList & reverseFaceMap, labelList & reverseCellMap, labelHashSet & flipFaceFlux, labelListList & patchPointMap, labelListList & pointZoneMap, labelListList & faceZonePointMap, labelListList & faceZoneFaceMap, labelListList & cellZoneMap, pointField & preMotionPoints, labelList & oldPatchStarts, labelList & oldPatchNMeshPoints, autoPtr< scalarField > & oldCellVolumesPtr, const bool reuse)
Construct from components and optionally reuse storage.
Definition at line 181 of file mapPolyMesh.C.
Member Function Documentation
const polyMesh& mesh () const inline
Return polyMesh.
Definition at line 436 of file mapPolyMesh.H.
label nOldPoints () const inline
Number of old points.
Definition at line 444 of file mapPolyMesh.H.
Referenced by hexRef8::updateMesh().
label nOldInternalFaces () const inline
Number of old internal faces.
Definition at line 452 of file mapPolyMesh.H.
label nOldFaces () const inline
Number of old faces.
Definition at line 460 of file mapPolyMesh.H.
label nOldCells () const inline
Number of old cells.
Definition at line 468 of file mapPolyMesh.H.
Referenced by hexRef8::updateMesh().
const labelList& pointMap () const inline
Old point map.
Contains the old point label for all new points. For preserved points this is the old point label. For added points this is the master point ID
Definition at line 480 of file mapPolyMesh.H.
References i.
Referenced by hexRef8::updateMesh(), and polyMesh::updateMesh().
const List<objectMap>& pointsFromPointsMap () const inline
Points originating from points.
Definition at line 488 of file mapPolyMesh.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, and FatalErrorInFunction.
const labelList& faceMap () const inline
Old face map.
Contains a list of old face labels for every new face. Warning: this map contains invalid entries for new faces
Definition at line 499 of file mapPolyMesh.H.
const List<objectMap>& facesFromPointsMap () const inline
Faces inflated from points.
Definition at line 507 of file mapPolyMesh.H.
References i.
const List<objectMap>& facesFromEdgesMap () const inline
Faces inflated from edges.
Definition at line 515 of file mapPolyMesh.H.
const List<objectMap>& facesFromFacesMap () const inline
Faces originating from faces.
Definition at line 523 of file mapPolyMesh.H.
const labelList& cellMap () const inline
Old cell map.
Contains old cell label for all preserved cells.
Definition at line 533 of file mapPolyMesh.H.
Referenced by hexRef8::updateMesh().
const List<objectMap>& cellsFromPointsMap () const inline
Cells inflated from points.
Definition at line 541 of file mapPolyMesh.H.
References i.
const List<objectMap>& cellsFromEdgesMap () const inline
Cells inflated from edges.
Definition at line 549 of file mapPolyMesh.H.
const List<objectMap>& cellsFromFacesMap () const inline
Cells inflated from faces.
Definition at line 557 of file mapPolyMesh.H.
const List<objectMap>& cellsFromCellsMap () const inline
Cells originating from cells.
Definition at line 565 of file mapPolyMesh.H.
const labelList& reversePointMap () const inline
Reverse point map.
Contains new point label for all old and added points
Definition at line 578 of file mapPolyMesh.H.
Referenced by pointBitSet::distribute(), pointSet::distribute(), hexRef8::updateMesh(), and polyMesh::updateMesh().
label mergedPoint (const label oldPointi) const inline
If point is removed return point (on new mesh) it merged.
into
Definition at line 588 of file mapPolyMesh.H.
const labelList& reverseFaceMap () const inline
Reverse face map.
Contains new face label for all old and added faces
Definition at line 616 of file mapPolyMesh.H.
Referenced by faceBitSet::distribute(), faceBoolSet::distribute(), faceSet::distribute(), and meshRefinement::mergePatchFaces().
label mergedFace (const label oldFacei) const inline
If face is removed return face (on new mesh) it merged into.
Definition at line 624 of file mapPolyMesh.H.
const labelList& reverseCellMap () const inline
Reverse cell map.
Contains new cell label for all old and added cells
Definition at line 652 of file mapPolyMesh.H.
Referenced by cellSet::distribute(), and hexRef8::updateMesh().
label mergedCell (const label oldCelli) const inline
If cell is removed return cell (on new mesh) it merged into.
Definition at line 660 of file mapPolyMesh.H.
const labelHashSet& flipFaceFlux () const inline
Map of flipped face flux faces.
Definition at line 686 of file mapPolyMesh.H.
const labelListList& patchPointMap () const inline
Patch point renumbering.
For every preserved point on a patch give the old position. For added points, the index is set to -1
Definition at line 697 of file mapPolyMesh.H.
const labelListList& pointZoneMap () const inline
Point zone renumbering.
For every preserved point in zone give the old position. For added points, the index is set to -1
Definition at line 711 of file mapPolyMesh.H.
const labelListList& faceZonePointMap () const inline
Face zone point renumbering.
For every preserved point in zone give the old position. For added points, the index is set to -1
Definition at line 722 of file mapPolyMesh.H.
const labelListList& faceZoneFaceMap () const inline
Face zone face renumbering.
For every preserved face in zone give the old position. For added faces, the index is set to -1
Definition at line 733 of file mapPolyMesh.H.
const labelListList& cellZoneMap () const inline
Cell zone renumbering.
For every preserved cell in zone give the old position. For added cells, the index is set to -1
Definition at line 744 of file mapPolyMesh.H.
const pointField& preMotionPoints () const inline
Pre-motion point positions.
This specifies the correct way of blowing up zero-volume objects
Definition at line 755 of file mapPolyMesh.H.
Referenced by meshRefinement::mergePatchFaces(), and meshRefinement::refine().
bool hasMotionPoints () const inline
Has valid preMotionPoints?
Definition at line 763 of file mapPolyMesh.H.
Referenced by meshRefinement::mergePatchFaces(), and polyMesh::updateMesh().
const labelList& oldPatchSizes () const inline
Return list of the old patch sizes.
Definition at line 772 of file mapPolyMesh.H.
const labelList& oldPatchStarts () const inline
Return list of the old patch start labels.
Definition at line 780 of file mapPolyMesh.H.
const labelList& oldPatchNMeshPoints () const inline
Return numbers of mesh points per old patch.
Definition at line 788 of file mapPolyMesh.H.
bool hasOldCellVolumes () const inline
Definition at line 796 of file mapPolyMesh.H.
const scalarField& oldCellVolumes () const inline
Definition at line 801 of file mapPolyMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapPolyMesh.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapPolyMesh.C