OpenFOAM: adjointOutletVelocityFluxFvPatchVectorField Class Reference
adjointOutletVelocityFluxFvPatchVectorField Class Reference
An outlet boundary condition for patches in which the primal flow exhibits recirculation. Adds the contribution of the objective as an adjoint momentum flux directly to the PDEs, without the need to first compute an adjoint outlet velocity, circumventing thus the division with (almost) zero that manifests in case of primal flow recirculation.
Public Member Functions
TypeName ("adjointOutletVelocityFlux")
Runtime type information.
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
Construct from patch and internal field.
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given adjointOutletVelocityFluxFvPatchVectorField onto a new patch.
virtual tmp< fvPatchVectorField > clone () const
Construct and return a clone.
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual bool assignable () const
Return true: Allow adjoint solvers to obtain the outlet phia.
virtual void manipulateMatrix (fvMatrix< vector > &matrix)
add source term in the first cells off the wall due to adjoint WF
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual tmp< Field< vector > > valueInternalCoeffs (const tmp< scalarField > &) const
Return the matrix diagonal coefficients corresponding to the evaluation of the value of this patchField with given weights.
virtual tmp< Field< vector > > valueBoundaryCoeffs (const tmp< scalarField > &) const
Return the matrix source coefficients corresponding to the evaluation of the value of this patchField with given weights.
virtual tmp< Field< vector > > gradientBoundaryCoeffs () const
Return the matrix source coefficients corresponding to the evaluation of the gradient of this patchField.
virtual tmp< Field< vector > > gradientInternalCoeffs () const
Return the matrix diagonal coefficients corresponding to the evaluation of the gradient of this patchField.
virtual void write (Ostream &) const
Write.
virtual void operator= (const fvPatchField< vector > &pvf)
Public Member Functions inherited from adjointBoundaryCondition
TypeName ("adjointBoundaryCondition")
Run-time type information.
template<class Type >
adjointBoundaryCondition (const fvPatch &p, const DimensionedField< Type, volMesh > &iF, const word &solverName)
Construct from field and base name.
adjointBoundaryCondition (const adjointBoundaryCondition &)
Construct as copy.
virtual ~adjointBoundaryCondition ()=default
Destructor.
const word & objectiveManagerName () const
Return objectiveManager name.
const word & adjointSolverName () const
Return adjointSolverName.
const word & simulationType () const
Return the simulationType.
void setBoundaryContributionPtr ()
Set the ptr to the correct boundaryAdjointContribution.
boundaryAdjointContribution & getBoundaryAdjContribution ()
Get boundaryContribution.
const ATCModel & getATC () const
ATC type might be useful for a number of BCs. Return here.
Additional Inherited Members
Protected Member Functions inherited from adjointBoundaryCondition
template<class Type >
tmp< Field< typename
Foam::outerProduct
< Foam::vector, Type >::type > > computePatchGrad (word name)
Get gradient of field on a specific boundary.
bool addATCUaGradUTerm ()
Whether to add the extra term from the UaGradU formulation.
Protected Attributes inherited from adjointBoundaryCondition
const fvPatch & patch_
Reference to patch.
word managerName_
objectiveManager name corresponding to field
word adjointSolverName_
adjointSolver name corresponding to field
word simulationType_
simulationType corresponding to field.
autoPtr
< boundaryAdjointContribution > boundaryContrPtr_
Engine to manage contributions of the objective functions to the adjoint boundary conditions.
autoPtr< bool > addATCUaGradUTerm_
Whether to add the extra term from the UaGradU formulation.
Detailed Description
An outlet boundary condition for patches in which the primal flow exhibits recirculation. Adds the contribution of the objective as an adjoint momentum flux directly to the PDEs, without the need to first compute an adjoint outlet velocity, circumventing thus the division with (almost) zero that manifests in case of primal flow recirculation.
Source files
adjointOutletVelocityFluxFvPatchVectorField.H
adjointOutletVelocityFluxFvPatchVectorField.C
Definition at line 56 of file adjointOutletVelocityFluxFvPatchVectorField.H.
Constructor & Destructor Documentation
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Construct from patch and internal field.
Definition at line 32 of file adjointOutletVelocityFluxFvPatchVectorField.C.
adjointOutletVelocityFluxFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 58 of file adjointOutletVelocityFluxFvPatchVectorField.C.
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given adjointOutletVelocityFluxFvPatchVectorField onto a new patch.
Definition at line 44 of file adjointOutletVelocityFluxFvPatchVectorField.C.
adjointOutletVelocityFluxFvPatchVectorField (const adjointOutletVelocityFluxFvPatchVectorField & pivpvf, const DimensionedField< vector, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 76 of file adjointOutletVelocityFluxFvPatchVectorField.C.
Member Function Documentation
TypeName ("adjointOutletVelocityFlux")
Runtime type information.
virtual tmp<fvPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 111 of file adjointOutletVelocityFluxFvPatchVectorField.H.
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 132 of file adjointOutletVelocityFluxFvPatchVectorField.H.
virtual bool assignable () const inline virtual
Return true: Allow adjoint solvers to obtain the outlet phia.
value through HbyA
Definition at line 151 of file adjointOutletVelocityFluxFvPatchVectorField.H.
void manipulateMatrix (fvMatrix< vector > & matrix) virtual
add source term in the first cells off the wall due to adjoint WF
Definition at line 89 of file adjointOutletVelocityFluxFvPatchVectorField.C.
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 137 of file adjointOutletVelocityFluxFvPatchVectorField.C.
Foam::tmp< Foam::Field< Foam::vector > > valueInternalCoeffs (const tmp< scalarField > &) const virtual
Return the matrix diagonal coefficients corresponding to the evaluation of the value of this patchField with given weights.
Definition at line 159 of file adjointOutletVelocityFluxFvPatchVectorField.C.
Foam::tmp< Foam::Field< Foam::vector > > valueBoundaryCoeffs (const tmp< scalarField > &) const virtual
Return the matrix source coefficients corresponding to the evaluation of the value of this patchField with given weights.
Definition at line 169 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
Foam::tmp< Foam::Field< Foam::vector > > gradientBoundaryCoeffs () const virtual
Return the matrix source coefficients corresponding to the evaluation of the gradient of this patchField.
Definition at line 179 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
Foam::tmp< Foam::Field< Foam::vector > > gradientInternalCoeffs () const virtual
Return the matrix diagonal coefficients corresponding to the evaluation of the gradient of this patchField.
Definition at line 187 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
void write (Ostream & os) const virtual
Write.
Definition at line 194 of file adjointOutletVelocityFluxFvPatchVectorField.C.
References Foam::New(), and Foam::Zero.
void operator= (const fvPatchField< vector > & pvf) virtual
Definition at line 207 of file adjointOutletVelocityFluxFvPatchVectorField.C.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointOutletVelocityFlux/adjointOutletVelocityFluxFvPatchVectorField.H
src/optimisation/adjointOptimisation/adjoint/adjointBoundaryConditions/adjointOutletVelocityFlux/adjointOutletVelocityFluxFvPatchVectorField.C