OpenFOAM: tetrahedron< Point, PointRef > Class Template Reference
tetrahedron< Point, PointRef > Class Template Reference
A tetrahedron primitive.
Classes
class dummyOp
Dummy.
class storeOp
Store resulting tets.
class sumVolOp
Sum resulting volumes.
Public Types
enum { nVertices = 4, nEdges = 6 }
typedef FixedList< tetPoints, 200 > tetIntersectionList
Storage type for tets originating from intersecting tets.
Public Member Functions
tetrahedron (const Point &a, const Point &b, const Point &c, const Point &d)
Construct from points.
tetrahedron (const UList< Point > &, const FixedList< label, 4 > &indices)
Construct from four points in the list of points.
tetrahedron (Istream &)
Construct from Istream.
const Point & a () const
Return vertices.
const Point & b () const
const Point & c () const
const Point & d () const
triPointRef tri (const label facei) const
Return i-th face.
vector Sa () const
Face area normal for side a.
vector Sb () const
Face area normal for side b.
vector Sc () const
Face area normal for side c.
vector Sd () const
Face area normal for side d.
Point centre () const
Return centre (centroid)
scalar mag () const
Return volume.
Point circumCentre () const
Return circum-centre.
scalar circumRadius () const
Return circum-radius.
scalar quality () const
Return quality: Ratio of tetrahedron and circum-sphere.
Point randomPoint (Random &rndGen) const
Return a random point in the tetrahedron from a.
Point barycentricToPoint (const barycentric &bary) const
Calculate the point from the given barycentric coordinates.
barycentric pointToBarycentric (const point &pt) const
Calculate the barycentric coordinates from the given point.
scalar pointToBarycentric (const point &pt, barycentric &bary) const
Calculate the barycentric coordinates from the given point.
pointHit nearestPoint (const point &p) const
Return nearest point to p on tetrahedron. Is p itself.
bool inside (const point &pt) const
Return true if point is inside tetrahedron.
template<class AboveTetOp , class BelowTetOp >
void sliceWithPlane (const plane &pl, AboveTetOp &aboveOp, BelowTetOp &belowOp) const
Decompose tet into tets above and below plane.
void tetOverlap (const tetrahedron< Point, PointRef > &tetB, tetIntersectionList &insideTets, label &nInside, tetIntersectionList &outsideTets, label &nOutside) const
Decompose tet into tets inside and outside other tet.
pointHit containmentSphere (const scalar tol) const
Return (min)containment sphere, i.e. the smallest sphere with.
void gradNiSquared (scalarField &buffer) const
Fill buffer with shape function products.
void gradNiDotGradNj (scalarField &buffer) const
void gradNiGradNi (tensorField &buffer) const
void gradNiGradNj (tensorField &buffer) const
boundBox bounds () const
Calculate the bounding box.
Friends
Istream & operator>> (Istream &, tetrahedron &)
Ostream & operator (Ostream &, const tetrahedron &)
Detailed Description
template<class Point, class PointRef>
class Foam::tetrahedron< Point, PointRef >
A tetrahedron primitive.
Ordering of edges needs to be the same for a tetrahedron class, a tetrahedron cell shape model and a tetCell.
Source files
tetrahedron.H
tetrahedronI.H
tetrahedron.C
Definition at line 61 of file tetrahedron.H.
Member Typedef Documentation
typedef FixedList<tetPoints, 200> tetIntersectionList
Storage type for tets originating from intersecting tets.
(can possibly be smaller than 200)
Definition at line 95 of file tetrahedron.H.
Member Enumeration Documentation
anonymous enum
Enumerator
nVertices
nEdges
Definition at line 172 of file tetrahedron.H.
Constructor & Destructor Documentation
tetrahedron (const Point & a, const Point & b, const Point & c, const Point & d) inline
Construct from points.
Definition at line 31 of file tetrahedronI.H.
tetrahedron (const UList< Point > & points, const FixedList< label, 4 > & indices) inline
Construct from four points in the list of points.
Definition at line 47 of file tetrahedronI.H.
tetrahedron (Istream & is) inline
Construct from Istream.
Definition at line 60 of file tetrahedronI.H.
Member Function Documentation
const Point & a () const inline
Return vertices.
Definition at line 69 of file tetrahedronI.H.
const Point & b () const inline
Definition at line 76 of file tetrahedronI.H.
const Point & c () const inline
Definition at line 83 of file tetrahedronI.H.
References b_().
const Point & d () const inline
Definition at line 90 of file tetrahedronI.H.
Foam::triPointRef tri (const label facei) const inline
Return i-th face.
Definition at line 98 of file tetrahedronI.H.
Foam::vector Sa () const inline
Face area normal for side a.
Definition at line 130 of file tetrahedronI.H.
Foam::vector Sb () const inline
Face area normal for side b.
Definition at line 137 of file tetrahedronI.H.
References b_().
Foam::vector Sc () const inline
Face area normal for side c.
Definition at line 144 of file tetrahedronI.H.
Foam::vector Sd () const inline
Face area normal for side d.
Definition at line 151 of file tetrahedronI.H.
References b_().
Point centre () const inline
Return centre (centroid)
Definition at line 158 of file tetrahedronI.H.
References b_().
Foam::scalar mag () const inline
Return volume.
Definition at line 165 of file tetrahedronI.H.
References b_().
Referenced by Moment< Type >::Moment(), and tetrahedron< Point, PointRef >::storeOp::storeOp().
Point circumCentre () const inline
Return circum-centre.
Definition at line 172 of file tetrahedronI.H.
References b_().
Foam::scalar circumRadius () const inline
Return circum-radius.
Definition at line 199 of file tetrahedronI.H.
Foam::scalar quality () const inline
Return quality: Ratio of tetrahedron and circum-sphere.
volume, scaled so that a regular tetrahedron has a quality of 1
Definition at line 225 of file tetrahedronI.H.
Point randomPoint (Random & rndGen) const inline
Return a random point in the tetrahedron from a.
uniform distribution
Definition at line 239 of file tetrahedronI.H.
Point barycentricToPoint (const barycentric & bary) const inline
Calculate the point from the given barycentric coordinates.
Definition at line 249 of file tetrahedronI.H.
References barycentric01().
Referenced by interpolation< Foam::Vector >::psi().
Foam::barycentric pointToBarycentric (const point & pt) const inline
Calculate the barycentric coordinates from the given point.
Definition at line 259 of file tetrahedronI.H.
References b_().
Foam::scalar pointToBarycentric (const point & pt, barycentric & bary) const inline
Calculate the barycentric coordinates from the given point.
Returns the determinant.
Definition at line 271 of file tetrahedronI.H.
Foam::pointHit nearestPoint (const point & p) const inline
Return nearest point to p on tetrahedron. Is p itself.
if inside.
Definition at line 314 of file tetrahedronI.H.
bool inside (const point & pt) const inline
Return true if point is inside tetrahedron.
Definition at line 408 of file tetrahedronI.H.
void sliceWithPlane (const plane & pl, AboveTetOp & aboveOp, BelowTetOp & belowOp) const inline
Decompose tet into tets above and below plane.
Definition at line 1015 of file tetrahedronI.H.
void tetOverlap (const tetrahedron< Point, PointRef > & tetB, tetIntersectionList & insideTets, label & nInside, tetIntersectionList & outsideTets, label & nOutside) const inline
Decompose tet into tets inside and outside other tet.
Foam::pointHit containmentSphere (const scalar tol) const
Return (min)containment sphere, i.e. the smallest sphere with.
all points inside. Returns pointHit with:
hit : if sphere is equal to circumsphere (biggest sphere)
point : centre of sphere
distance : radius of sphere
eligiblemiss: false Tol (small compared to 1, e.g. 1e-9) is used to determine whether point is inside: mag(pt - ctr) < (1+tol)*radius.
Definition at line 29 of file tetrahedron.C.
References b_(), Foam::magSqr(), PointHit< Point >::rawPoint(), PointHit< Point >::setDistance(), PointHit< Point >::setHit(), PointHit< Point >::setMiss(), PointHit< Point >::setPoint(), and Foam::sqrt().
void gradNiSquared (scalarField & buffer) const
Fill buffer with shape function products.
Definition at line 241 of file tetrahedron.C.
void gradNiDotGradNj (scalarField & buffer) const
Definition at line 262 of file tetrahedron.C.
void gradNiGradNi (tensorField & buffer) const
Definition at line 292 of file tetrahedron.C.
void gradNiGradNj (tensorField & buffer) const
Definition at line 310 of file tetrahedron.C.
Foam::boundBox bounds () const
Calculate the bounding box.
Definition at line 335 of file tetrahedron.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , tetrahedron< Point, PointRef > &) friend
Ostream& operator (Ostream & , const tetrahedron< Point, PointRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedron.H
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedron.C
src/OpenFOAM/meshes/primitiveShapes/tetrahedron/tetrahedronI.H