OpenFOAM: masterUncollatedFileOperation Class Reference
masterUncollatedFileOperation Class Reference
fileOperations that performs all file operations on the master processor. Requires the calls to be parallel synchronised!
Classes
class chModOp
class cpOp
class existsOp
class fileOrNullOp
class fileSizeOp
class isDirOp
class isFileOp
class lastModifiedHROp
class lastModifiedOp
class lnOp
class mkDirOp
class modeOp
class mvBakOp
class mvOp
class readDirOp
class rmDirOp
class rmOp
class typeOp
Public Member Functions
TypeName ("masterUncollated")
Runtime type information.
masterUncollatedFileOperation (bool verbose)
Construct null.
masterUncollatedFileOperation (const label comm, bool verbose)
Construct from communicator.
virtual ~masterUncollatedFileOperation ()
Destructor.
virtual bool mkDir (const fileName &, mode_t=0777) const
Make directory.
virtual bool chMod (const fileName &, const mode_t) const
Set the file mode.
virtual mode_t mode (const fileName &, const bool followLink=true) const
Return the file mode.
virtual fileName::Type type (const fileName &, const bool followLink=true) const
Return the file type: DIRECTORY, FILE or LINK.
virtual bool exists (const fileName &, const bool checkGzip=true, const bool followLink=true) const
Does the name exist (as DIRECTORY or FILE) in the file system?
virtual bool isDir (const fileName &, const bool followLink=true) const
Does the name exist as a DIRECTORY in the file system?
virtual bool isFile (const fileName &, const bool checkGzip=true, const bool followLink=true) const
Does the name exist as a FILE in the file system?
virtual off_t fileSize (const fileName &, const bool followLink=true) const
Return size of file.
virtual time_t lastModified (const fileName &, const bool followLink=true) const
Return time of last file modification.
virtual double highResLastModified (const fileName &, const bool followLink=true) const
Return time of last file modification.
virtual fileNameList readDir (const fileName &, const fileName::Type=fileName::FILE, const bool filtergz=true, const bool followLink=true) const
Read a directory and return the entries as a string list.
virtual bool cp (const fileName &src, const fileName &dst, const bool followLink=true) const
Copy, recursively if necessary, the source to the destination.
virtual bool ln (const fileName &src, const fileName &dst) const
Create a softlink. dst should not exist. Returns true if.
virtual bool mv (const fileName &src, const fileName &dst, const bool followLink=false) const
Rename src to dst.
virtual bool mvBak (const fileName &, const std::string &ext="bak") const
Rename to a corresponding backup file.
virtual bool rm (const fileName &) const
Remove a file, returning true if successful otherwise false.
virtual bool rmDir (const fileName &dir, const bool silent=false) const
Remove a directory and its contents.
virtual fileName filePath (const bool checkGlobal, const IOobject &io, const word &typeName, const bool search) const
Search for an object. checkGlobal : also check undecomposed case.
virtual fileName dirPath (const bool checkGlobal, const IOobject &io, const bool search) const
Search for a directory. checkGlobal : also check undecomposed.
virtual fileNameList readObjects (const objectRegistry &db, const fileName &instance, const fileName &local, word &newInstance) const
Search directory for objects. Used in IOobjectList.
virtual bool readHeader (IOobject &, const fileName &, const word &typeName) const
Read object header from supplied file.
virtual autoPtr< ISstream > readStream (regIOobject &, const fileName &, const word &typeName, const bool valid=true) const
Reads header for regIOobject and returns an ISstream.
virtual bool read (regIOobject &, const bool masterOnly, const IOstream::streamFormat format, const word &typeName) const
Top-level read.
virtual bool writeObject (const regIOobject &, IOstream::streamFormat format=IOstream::ASCII, IOstream::versionNumber version=IOstream::currentVersion, IOstream::compressionType compression=IOstream::UNCOMPRESSED, const bool valid=true) const
Writes a regIOobject (so header, contents and divider).
virtual autoPtr< ISstream > NewIFstream (const fileName &) const
Generate an ISstream that reads a file.
virtual autoPtr< Ostream > NewOFstream (const fileName &pathname, IOstream::streamFormat format=IOstream::ASCII, IOstream::versionNumber version=IOstream::currentVersion, IOstream::compressionType compression=IOstream::UNCOMPRESSED, const bool valid=true) const
Generate an Ostream that writes a file.
virtual label addWatch (const fileName &) const
Add watching of a file. Returns handle.
virtual bool removeWatch (const label) const
Remove watch on a file (using handle)
virtual label findWatch (const labelList &watchIndices, const fileName &) const
Find index (or -1) of file in list of handles.
virtual void addWatches (regIOobject &, const fileNameList &) const
Helper: add watches for list of regIOobjects.
virtual fileName getFile (const label) const
Get name of file being watched (using handle)
virtual void updateStates (const bool masterOnly, const bool syncPar) const
Update state of all files.
virtual fileMonitor::fileState getState (const label) const
Get current state of file (using handle)
virtual void setUnmodified (const label) const
Set current state of file (using handle) to unmodified.
virtual instantList findTimes (const fileName &, const word &) const
Get sorted list of times.
virtual IOobject findInstance (const IOobject &io, const scalar startValue, const word &stopInstance) const
Find instance where IOobject is. Fails if cannot be found.
virtual void setTime (const Time &) const
Callback for time change.
virtual void flush () const
Forcibly wait until all output done. Flush any cached data.
const HashPtrTable< instantList > & times () const
Return cached times.
Public Member Functions inherited from fileOperation
TypeName ("fileOperation")
Runtime type information.
fileOperation (const label comm)
Construct from communicator.
declareRunTimeSelectionTable (autoPtr, fileOperation, word,(bool verbose),(verbose))
virtual ~fileOperation ()=default
Destructor.
virtual fileName objectPath (const IOobject &io, const word &typeName) const
Generate disk file name for object. Opposite of filePath.
virtual fileName filePath (const fileName &) const
Search for a file or directory. Use IOobject version in.
virtual word processorsDir (const IOobject &io) const
Actual name of processors dir (for use in mode PROCOBJECT,.
virtual word processorsDir (const fileName &) const
Actual name of processors dir (for use in mode PROCOBJECT,.
virtual void setNProcs (const label nProcs)
Set number of processor directories/results. Only used in.
virtual label nProcs (const fileName &dir, const fileName &local="") const
Get number of processor directories/results. Used for e.g.
fileName processorsCasePath (const IOobject &, const word &procDir) const
Generate path (like io.path) from root+casename with any.
fileName processorsPath (const IOobject &, const word &instance, const word &procDir) const
Generate path (like io.path) with provided instance and any.
fileName processorsPath (const fileName &, const word &procDir) const
Operating on fileName: replace processorXXX with procDir.
Static Public Member Functions
static bool uniformFile (const fileNameList &)
Same file?
Static Public Member Functions inherited from fileOperation
static autoPtr< fileOperation > New (const word &handlerType, bool verbose=false)
Select fileHandler-type.
static label splitProcessorPath (const fileName &, fileName &path, fileName &procDir, fileName &local, label &groupStart, label &groupSize, label &nProcs)
Split fileName into part before 'processor' and part after.
static label detectProcessorPath (const fileName &)
Detect processor number from '/aa/bb/processorDDD/cc'.
Static Public Attributes
static float maxMasterFileBufferSize
Max size of parallel communications. Switches from non-blocking.
Static Public Attributes inherited from fileOperation
static const Enum< pathType > pathTypeNames_
static word processorsBaseDir = "processors"
Return the processors directory name (usually "processors")
static word defaultFileHandler
Default fileHandler.
static autoPtr< fileOperation > fileHandlerPtr_
Static fileOperation.
Protected Member Functions
template<class Type >
Type scatterList (const UList< Type > &, const int, const label comm) const
template<class Type , class fileOp >
Type masterOp (const fileName &, const fileOp &fop, const int tag, const label comm) const
template<class Type , class fileOp >
Type masterOp (const fileName &, const fileName &, const fileOp &fop, const int tag, const label comm) const
virtual fileName filePathInfo (const bool checkGlobal, const bool isFile, const IOobject &, const bool search, pathType &searchType, word &processorsDir, word &instance) const
Search (locally!) for object; return info on how it was found.
fileName localObjectPath (const IOobject &, const pathType &searchType, const word &processorsDir, const word &instancePath) const
Construct filePath.
bool exists (const dirIndexList &, IOobject &io) const
Helper: check IO for local existence. Like filePathInfo but.
Protected Member Functions inherited from fileOperation
fileMonitor & monitor () const
tmpNrc< dirIndexList > lookupAndCacheProcessorsPath (const fileName &, const bool syncPar) const
Lookup name of processorsDDD using cache. Return empty fileName.
virtual tmpNrc< dirIndexList > lookupProcessorsPath (const fileName &) const
Lookup name of processorsDDD using cache. Return empty fileName.
bool exists (IOobject &io) const
Does ioobject exist. Is either a directory (empty name()) or.
Static Protected Member Functions
static labelList subRanks (const label n)
Get the list of processors that are part of this communicator.
static word findInstancePath (const instantList &timeDirs, const instant &t)
Equivalent of Time::findInstance.
static void readAndSend (const fileName &filePath, const IOstream::compressionType cmp, const labelUList &procs, PstreamBuffers &pBufs)
Read file contents and send to processors.
static void readAndSend (const fileName &fName, const labelUList &procs, PstreamBuffers &pBufs)
Detect file (possibly compressed), read file contents and send.
static autoPtr< ISstream > read (IOobject &io, const label comm, const bool uniform, const fileNameList &filePaths, const boolList &procValid)
Read files on comms master.
Static Protected Member Functions inherited from fileOperation
static instantList sortTimes (const fileNameList &, const word &)
Sort directory entries according to time value.
static void mergeTimes (const instantList &extraTimes, const word &constantName, instantList &times)
Merge two times.
static bool isFileOrDir (const bool isFile, const fileName &)
Helper: check for file (isFile) or directory (!isFile)
Protected Attributes
const label myComm_
Any communicator allocated by me.
HashPtrTable< instantList > times_
Cached times for a given directory.
Protected Attributes inherited from fileOperation
const label comm_
Communicator to use.
HashTable< dirIndexList > procsDirs_
Detected processors directories.
autoPtr< fileMonitor > monitorPtr_
file-change monitor for all registered files
Additional Inherited Members
Public Types inherited from fileOperation
enum pathType {
NOTFOUND, ABSOLUTE, OBJECT, WRITEOBJECT,
PROCUNCOLLATED, PROCBASEOBJECT, PROCOBJECT, PARENTOBJECT,
FINDINSTANCE, PROCUNCOLLATEDINSTANCE, PROCBASEINSTANCE, PROCINSTANCE
}
Enumeration for the location of an IOobject.
typedef Tuple2< fileName,
Tuple2< pathType, label > > dirIndex
typedef List< dirIndex > dirIndexList
Detailed Description
fileOperations that performs all file operations on the master processor. Requires the calls to be parallel synchronised!
Limitations
no /processor in filename
no /uniform/ in the filename
The main logic is in ::filePath which returns a
same path on all processors. This can either be a global file (system/controlDict, processorXXX/0/uniform/) or a collated file (processors/0/p)
same path on all processors of the local communicator (processors4_0-1/0/p)
different path on all processors (processor0/0/p)
system/controlDict: filePath worldmaster: <globalRoot>/system/controlDict localmaster: ,, slave : ,,
processor0/uniform/time filePath worldmaster: <globalRoot>/processorXXX/uniform/time localmaster: ,, slave : ,,
processors0/0/p processors10/0/p processors10_2-4/0/p
Definition at line 79 of file masterUncollatedFileOperation.H.
Constructor & Destructor Documentation
masterUncollatedFileOperation (bool verbose)
Construct null.
Definition at line 752 of file masterUncollatedFileOperation.C.
masterUncollatedFileOperation (const label comm, bool verbose)
Construct from communicator.
Definition at line 804 of file masterUncollatedFileOperation.C.
~masterUncollatedFileOperation () virtual
Destructor.
Definition at line 881 of file masterUncollatedFileOperation.C.
Member Function Documentation
Foam::labelList subRanks (const label n) static protected
Get the list of processors that are part of this communicator.
Definition at line 77 of file masterUncollatedFileOperation.C.
Type scatterList (const UList< Type > & masterLst, const int tag, const label comm) const protected
Definition at line 28 of file masterUncollatedFileOperationTemplates.C.
References PstreamBuffers::finishedSends(), UPstream::master(), UPstream::masterNo(), UPstream::myProcNo(), UPstream::nonBlocking, and UPstream::nProcs().
Type masterOp (const fileName & fName, const fileOp & fop, const int tag, const label comm) const protected
Definition at line 63 of file masterUncollatedFileOperationTemplates.C.
Type masterOp (const fileName & src, const fileName & dest, const fileOp & fop, const int tag, const label comm) const protected
Definition at line 106 of file masterUncollatedFileOperationTemplates.C.
Foam::word findInstancePath (const instantList & timeDirs, const instant & t) static protected
Equivalent of Time::findInstance.
Definition at line 128 of file masterUncollatedFileOperation.C.
Foam::fileName filePathInfo (const bool checkGlobal, const bool isFile, const IOobject & io, const bool search, pathType & searchType, word & processorsDir, word & instance) const protected virtual
Search (locally!) for object; return info on how it was found.
Does not do any parallel communication. checkGlobal : also check undecomposed case isFile : true:check for file false:check for directory searchType : how was found processorsDir : name of processor directory instance : instance
Definition at line 153 of file masterUncollatedFileOperation.C.
Foam::fileName localObjectPath (const IOobject & io, const pathType & searchType, const word & processorsDir, const word & instancePath) const protected
Construct filePath.
Definition at line 328 of file masterUncollatedFileOperation.C.
void readAndSend (const fileName & filePath, const IOstream::compressionType cmp, const labelUList & procs, PstreamBuffers & pBufs) static protected
Read file contents and send to processors.
Definition at line 488 of file masterUncollatedFileOperation.C.
void readAndSend (const fileName & fName, const labelUList & procs, PstreamBuffers & pBufs) static protected
Detect file (possibly compressed), read file contents and send.
to processors
Definition at line 552 of file masterUncollatedFileOperation.C.
Foam::autoPtr< Foam::ISstream > read (IOobject & io, const label comm, const bool uniform, const fileNameList & filePaths, const boolList & procValid) static protected
Read files on comms master.
Definition at line 583 of file masterUncollatedFileOperation.C.
bool exists (const dirIndexList & pDirs, IOobject & io) const protected
Helper: check IO for local existence. Like filePathInfo but.
without parent searchign and instance searching
Definition at line 1444 of file masterUncollatedFileOperation.C.
TypeName ("masterUncollated")
Runtime type information.
bool mkDir (const fileName & dir, mode_t mode = 0777) const virtual
Make directory.
Implements fileOperation.
Definition at line 893 of file masterUncollatedFileOperation.C.
bool chMod (const fileName & fName, const mode_t mode) const virtual
Set the file mode.
Implements fileOperation.
Definition at line 909 of file masterUncollatedFileOperation.C.
mode_t mode (const fileName & fName, const bool followLink = true) const virtual
Return the file mode.
Implements fileOperation.
Definition at line 925 of file masterUncollatedFileOperation.C.
Referenced by masterUncollatedFileOperation::chModOp::chModOp(), and masterUncollatedFileOperation::mkDirOp::mkDirOp().
Foam::fileName::Type type (const fileName & fName, const bool followLink = true) const virtual
Return the file type: DIRECTORY, FILE or LINK.
Implements fileOperation.
Definition at line 941 of file masterUncollatedFileOperation.C.
bool exists (const fileName & fName, const bool checkGzip = true, const bool followLink = true) const virtual
Does the name exist (as DIRECTORY or FILE) in the file system?
Optionally enable/disable check for gzip file.
Implements fileOperation.
Definition at line 960 of file masterUncollatedFileOperation.C.
bool isDir (const fileName & fName, const bool followLink = true) const virtual
Does the name exist as a DIRECTORY in the file system?
Implements fileOperation.
Definition at line 977 of file masterUncollatedFileOperation.C.
bool isFile (const fileName & fName, const bool checkGzip = true, const bool followLink = true) const virtual
Does the name exist as a FILE in the file system?
Optionally enable/disable check for gzip file.
Implements fileOperation.
Definition at line 993 of file masterUncollatedFileOperation.C.
Referenced by masterUncollatedFileOperation::fileOrNullOp::fileOrNullOp().
off_t fileSize (const fileName & fName, const bool followLink = true) const virtual
Return size of file.
Implements fileOperation.
Definition at line 1010 of file masterUncollatedFileOperation.C.
time_t lastModified (const fileName & fName, const bool followLink = true) const virtual
Return time of last file modification.
Implements fileOperation.
Definition at line 1026 of file masterUncollatedFileOperation.C.
double highResLastModified (const fileName & fName, const bool followLink = true) const virtual
Return time of last file modification.
Implements fileOperation.
Definition at line 1042 of file masterUncollatedFileOperation.C.
Foam::fileNameList readDir (const fileName & dir, const fileName::Type type = fileName::FILE, const bool filtergz = true, const bool followLink = true) const virtual
Read a directory and return the entries as a string list.
Implements fileOperation.
Definition at line 1105 of file masterUncollatedFileOperation.C.
bool cp (const fileName & src, const fileName & dst, const bool followLink = true) const virtual
Copy, recursively if necessary, the source to the destination.
Implements fileOperation.
Definition at line 1123 of file masterUncollatedFileOperation.C.
bool ln (const fileName & src, const fileName & dst) const virtual
Create a softlink. dst should not exist. Returns true if.
successful.
Implements fileOperation.
Definition at line 1141 of file masterUncollatedFileOperation.C.
bool mv (const fileName & src, const fileName & dst, const bool followLink = false) const virtual
Rename src to dst.
Implements fileOperation.
Definition at line 1158 of file masterUncollatedFileOperation.C.
bool mvBak (const fileName & fName, const std::string & ext = "bak") const virtual
Rename to a corresponding backup file.
If the backup file already exists, attempt with "01" .. "99" suffix
Implements fileOperation.
Definition at line 1058 of file masterUncollatedFileOperation.C.
bool rm (const fileName & fName) const virtual
Remove a file, returning true if successful otherwise false.
Implements fileOperation.
Definition at line 1074 of file masterUncollatedFileOperation.C.
bool rmDir (const fileName & dir, const bool silent = false) const virtual
Remove a directory and its contents.
Parameters
silent do not report missing directory
Implements fileOperation.
Definition at line 1089 of file masterUncollatedFileOperation.C.
Foam::fileName filePath (const bool checkGlobal, const IOobject & io, const word & typeName, const bool search) const virtual
Search for an object. checkGlobal : also check undecomposed case.
Implements fileOperation.
Definition at line 1176 of file masterUncollatedFileOperation.C.
Foam::fileName dirPath (const bool checkGlobal, const IOobject & io, const bool search) const virtual
Search for a directory. checkGlobal : also check undecomposed.
case
Implements fileOperation.
Definition at line 1321 of file masterUncollatedFileOperation.C.
Foam::fileNameList readObjects (const objectRegistry & db, const fileName & instance, const fileName & local, word & newInstance) const virtual
Search directory for objects. Used in IOobjectList.
Use non-time searching version
Reimplemented from fileOperation.
Definition at line 1693 of file masterUncollatedFileOperation.C.
bool readHeader (IOobject & io, const fileName & fName, const word & typeName) const virtual
Read object header from supplied file.
Implements fileOperation.
Definition at line 1782 of file masterUncollatedFileOperation.C.
Foam::autoPtr< Foam::ISstream > readStream (regIOobject & io, const fileName & fName, const word & typeName, const bool valid = true) const virtual
Reads header for regIOobject and returns an ISstream.
to read the contents.
Implements fileOperation.
Definition at line 1907 of file masterUncollatedFileOperation.C.
bool read (regIOobject & io, const bool masterOnly, const IOstream::streamFormat format, const word & typeName) const virtual
Top-level read.
Implements fileOperation.
Definition at line 2138 of file masterUncollatedFileOperation.C.
bool writeObject (const regIOobject & io, IOstream::streamFormat format = IOstream::ASCII, IOstream::versionNumber version = IOstream::currentVersion, IOstream::compressionType compression = IOstream::UNCOMPRESSED, const bool valid = true) const virtual
Writes a regIOobject (so header, contents and divider).
Returns success state.
Reimplemented from fileOperation.
Reimplemented in collatedFileOperation.
Definition at line 2240 of file masterUncollatedFileOperation.C.
Foam::autoPtr< Foam::ISstream > NewIFstream (const fileName & filePath) const virtual
Generate an ISstream that reads a file.
Implements fileOperation.
Definition at line 2409 of file masterUncollatedFileOperation.C.
Foam::autoPtr< Foam::Ostream > NewOFstream (const fileName & pathname, IOstream::streamFormat format = IOstream::ASCII, IOstream::versionNumber version = IOstream::currentVersion, IOstream::compressionType compression = IOstream::UNCOMPRESSED, const bool valid = true) const virtual
Generate an Ostream that writes a file.
Implements fileOperation.
Definition at line 2545 of file masterUncollatedFileOperation.C.
Foam::label addWatch (const fileName & fName) const virtual
Add watching of a file. Returns handle.
Reimplemented from fileOperation.
Definition at line 2576 of file masterUncollatedFileOperation.C.
bool removeWatch (const label watchIndex) const virtual
Remove watch on a file (using handle)
Reimplemented from fileOperation.
Definition at line 2591 of file masterUncollatedFileOperation.C.
Foam::label findWatch (const labelList & watchIndices, const fileName & fName) const virtual
Find index (or -1) of file in list of handles.
Reimplemented from fileOperation.
Definition at line 2606 of file masterUncollatedFileOperation.C.
void addWatches (regIOobject & rio, const fileNameList & files) const virtual
Helper: add watches for list of regIOobjects.
Reimplemented from fileOperation.
Definition at line 2630 of file masterUncollatedFileOperation.C.
Foam::fileName getFile (const label watchIndex) const virtual
Get name of file being watched (using handle)
Reimplemented from fileOperation.
Definition at line 2667 of file masterUncollatedFileOperation.C.
void updateStates (const bool masterOnly, const bool syncPar) const virtual
Update state of all files.
Reimplemented from fileOperation.
Definition at line 2682 of file masterUncollatedFileOperation.C.
Foam::fileMonitor::fileState getState (const label watchFd) const virtual
Get current state of file (using handle)
Reimplemented from fileOperation.
Definition at line 2696 of file masterUncollatedFileOperation.C.
void setUnmodified (const label watchFd) const virtual
Set current state of file (using handle) to unmodified.
Reimplemented from fileOperation.
Definition at line 2711 of file masterUncollatedFileOperation.C.
bool uniformFile (const fileNameList & filePaths) static
Same file?
Definition at line 470 of file masterUncollatedFileOperation.C.
Foam::instantList findTimes (const fileName & directory, const word & constantName) const virtual
Get sorted list of times.
Reimplemented from fileOperation.
Definition at line 2296 of file masterUncollatedFileOperation.C.
Foam::IOobject findInstance (const IOobject & io, const scalar startValue, const word & stopInstance) const virtual
Find instance where IOobject is. Fails if cannot be found.
and readOpt() is MUST_READ/MUST_READ_IF_MODIFIED. Otherwise returns stopInstance.
Reimplemented from fileOperation.
Definition at line 1493 of file masterUncollatedFileOperation.C.
void setTime (const Time & tm) const virtual
Callback for time change.
Reimplemented from fileOperation.
Definition at line 2343 of file masterUncollatedFileOperation.C.
void flush () const virtual
Forcibly wait until all output done. Flush any cached data.
Reimplemented from fileOperation.
Reimplemented in collatedFileOperation.
Definition at line 2568 of file masterUncollatedFileOperation.C.
const HashPtrTable<instantList>& times () const inline
Return cached times.
Definition at line 896 of file masterUncollatedFileOperation.H.
Member Data Documentation
const label myComm_ protected
Any communicator allocated by me.
Definition at line 90 of file masterUncollatedFileOperation.H.
HashPtrTable<instantList> times_ mutable protected
Cached times for a given directory.
Definition at line 95 of file masterUncollatedFileOperation.H.
float maxMasterFileBufferSize static
Max size of parallel communications. Switches from non-blocking.
to scheduled when reading/writing files. Read as float to enable easy specification of large sizes.
Definition at line 516 of file masterUncollatedFileOperation.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/fileOperations/masterUncollatedFileOperation/masterUncollatedFileOperation.H
src/OpenFOAM/global/fileOperations/masterUncollatedFileOperation/masterUncollatedFileOperation.C
src/OpenFOAM/global/fileOperations/masterUncollatedFileOperation/masterUncollatedFileOperationTemplates.C