OpenFOAM: fieldAverage Class Reference
fieldAverage Class Reference
Field function objects
Calculates average quantities for a user-specified selection of volumetric and surface fields. With the subRegion option, also supports fields on functionObject surface output (eg, sampledSurfaces).
Public Member Functions
TypeName ("fieldAverage")
Runtime type information.
fieldAverage (const word &name, const Time &runTime, const dictionary &)
Construct from Time and dictionary.
virtual ~fieldAverage ()=default
Destructor.
virtual bool read (const dictionary &)
Read the field average data.
virtual bool execute ()
Calculate the field averages.
virtual bool write ()
Write the field averages.
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()=default
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()=default
Destructor.
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
Deprecated(2018-10)
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Deprecated(2018-10)
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
Construct from components.
virtual ~stateFunctionObject ()=default
Destructor.
dictionary & propertyDict ()
Return access to the property dictionary.
bool foundProperty (const word &entryName) const
Return true if the property exists.
label getTrigger () const
Get the current trigger index.
bool setTrigger (const label triggeri)
Set the current trigger index.
bool getDict (const word &entryName, dictionary &dict) const
Set dictionary, return true if set.
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
Set dictionary from named object, return true if set.
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property.
template<class Type >
bool getProperty (const word &entryName, Type &value) const
Set generic property, return true if set.
template<class Type >
void setProperty (const word &entryName, const Type &value)
Add generic property.
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from named object.
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
Set generic property from named object, return true if set.
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
Add generic property from named object.
template<class Type >
void setResult (const word &entryName, const Type &value)
Add result.
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
Add result from named object.
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result.
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result from named object.
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
Set result from named object, return true if set.
word resultType (const word &entryName) const
Retrieve the result type.
word objectResultType (const word &objectName, const word &entryName) const
Return the type of result.
List< word > objectResultEntries () const
Retrieve the result entries.
List< word > objectResultEntries (const word &objectName) const
Return result entries for named object.
void writeResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
void writeResultEntries (const word &objectName, Ostream &os) const
Write the results entries for named object to stream.
void writeAllResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
Construct from Time.
virtual ~timeFunctionObject ()=default
Destructor.
const Time & time () const
Return time database.
objectRegistry & storedObjects ()
Write access to the output objects ("functionObjectObjects") registered on Time.
const objectRegistry & storedObjects () const
Const access to the output objects ("functionObjectObjects") registered on Time.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()=default
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool execute (const label subIndex)
Execute using the specified subIndex.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool filesModified () const
Did any file get changed during execution?
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Protected Member Functions
void initialize ()
Reset lists (clear existing values) and initialize averaging.
void restart ()
Restart averaging for restartOnOutput.
template<class Type >
void addMeanFieldType (fieldAverageItem &item)
Add mean average field to database.
template<class Type >
void addMeanField (fieldAverageItem &item)
Add mean average field to database.
template<class Type1 , class Type2 >
void addPrime2MeanFieldType (fieldAverageItem &item)
Add prime-squared average field to database.
template<class Type1 , class Type2 >
void addPrime2MeanField (fieldAverageItem &item)
Add prime-squared average field to database.
virtual void calcAverages ()
Main calculation routine.
template<class Type >
void calculateMeanFields () const
Calculate mean average fields.
template<class Type1 , class Type2 >
void calculatePrime2MeanFields () const
Calculate prime-squared average fields.
template<class Type1 , class Type2 >
void addMeanSqrToPrime2MeanType (const fieldAverageItem &item) const
Add mean-squared field value to prime-squared mean field.
template<class Type1 , class Type2 >
void addMeanSqrToPrime2Mean () const
Add mean-squared field value to prime-squared mean field.
template<class Type >
void storeWindowFieldType (fieldAverageItem &item)
template<class Type >
void storeWindowFields ()
template<class Type >
void restoreWindowFieldsType (const fieldAverageItem &item)
template<class Type >
void restoreWindowFields (const fieldAverageItem &item)
virtual void writeAverages () const
Write averages.
template<class Type >
void writeFieldType (const word &fieldName) const
Write fields.
template<class Type >
void writeFields () const
Write fields.
void writeAveragingProperties ()
Write averaging properties - steps and time.
void readAveragingProperties ()
Read averaging properties - steps and time.
fieldAverage (const fieldAverage &)=delete
No copy construct.
void operator= (const fieldAverage &)=delete
No copy assignment.
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
No copy construct.
void operator= (const fvMeshFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
The region or sub-region registry being used.
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
Return non-const pointer to the object of the given Type, (sub) objectRegistry.
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
Return non-const pointer to the object of the given Type, using a const-cast to have it behave like a mutable.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup and return object (eg, a field) from the (sub) objectRegistry.
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
Lookup and return object (eg, a field) from the (sub) objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the field in the (sub) objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in the (sub) objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the (sub) objectRegistry if present.
void clearObjects (const wordList &objNames)
Clear fields from the (sub) objectRegistry if present.
regionFunctionObject (const regionFunctionObject &)=delete
No copy construct.
void operator= (const regionFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from stateFunctionObject
const IOdictionary & stateDict () const
Return a const reference to the state dictionary.
IOdictionary & stateDict ()
Return non-const access to the state dictionary.
stateFunctionObject (const stateFunctionObject &)=delete
No copy construct.
void operator= (const stateFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
Remove specified items from "functionObjectObjects".
timeFunctionObject (const timeFunctionObject &)=delete
No copy construct.
void operator= (const timeFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Return a scoped name, e.g. used to construct local field names.
Protected Attributes
label prevTimeIndex_
Time at last call, prevents repeated averaging.
bool initialised_
Initialised flag.
Switch restartOnRestart_
Restart the averaging process on restart.
Switch restartOnOutput_
Restart the averaging process on output.
Switch periodicRestart_
Periodically restart the averaging process.
scalar restartPeriod_
Restart period.
scalar restartTime_
Specific restart time.
List< fieldAverageItem > faItems_
List of field average items, describing what averages to be.
List< label > totalIter_
Iteration steps counter.
List< scalar > totalTime_
Total time counter.
label periodIndex_
Index for periodic restart.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
Name for alternative object registry.
const objectRegistry & obr_
Reference to the region objectRegistry.
const objectRegistry * obrPtr_
Pointer to alternative (eg, sub-region) objectRegistry.
Protected Attributes inherited from timeFunctionObject
const Time & time_
Reference to the time database.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
bool log
Switch write log to Info.
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
static word outputPrefix
Directory prefix.
Detailed Description
Calculates average quantities for a user-specified selection of volumetric and surface fields. With the subRegion option, also supports fields on functionObject surface output (eg, sampledSurfaces).
Fields are entered as a list of sub-dictionaries, which indicate the type of averages to perform, and can be updated during the calculation. The current options include:
mean: arithmetic mean
prime2Mean: prime-squared mean
base: average over 'time', or 'iteration' (in the above)
window: optional averaging window, specified in 'base' units
Average field names are constructed by concatenating the base field with the averaging type, e.g. when averaging field 'U', the resultant fields are:
arithmetic mean field, UMean
prime-squared field, UPrime2Mean
Information regarding the number of averaging steps, and total averaging time are written on a per-field basis to the "<functionObject name>Properties" dictionary, located in <time>/uniform
When restarting form a previous calculation, the averaging is continuous or may be restarted using the restartOnRestart option.
The averaging process may be restarted after each calculation output time using the restartOnOutput option or restarted periodically using the periodicRestart option and setting restartPeriod to the required averaging period.
Usage
fieldAverage1
{
    type                fieldAverage;
    libs                ("libfieldFunctionObjects.so");
    writeControl        writeTime;
    restartOnRestart    false;
    restartOnOutput     false;
    periodicRestart     false;
    restartPeriod       0.002;
    fields
    (
        U
        {
            mean            on;
            prime2Mean      on;
            base            time;
            windowType      exact;
            window          10.0;
            windowName      w1;
        }
        p
        {
            mean            on;
            prime2Mean      on;
            base            time;
        }
    );
}
Where the entries comprise:
Property Description Required Default
type Type name: fieldAverage yes
restartOnRestart Restart the averaging on restart no no
restartOnOutput Restart the averaging on output no no
periodicRestart Periodically restart the averaging no no
restartPeriod Periodic restart period conditional
restartTime One-shot reset of the averaging no great
fields list of fields and averaging options yes
subRegion Name for alternative objectRegistry no ""
Note
To employ the prime2Mean option, the mean option must be selecetd.
See Also
Foam::functionObjects::fvMeshFunctionObject Foam::functionObject
Source files
fieldAverage.H
fieldAverage.C
fieldAverageTemplates.C
fieldAverageItem.C
Definition at line 196 of file fieldAverage.H.
Constructor & Destructor Documentation
fieldAverage (const fieldAverage &) protected delete
No copy construct.
fieldAverage (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 258 of file fieldAverage.C.
virtual ~fieldAverage () virtual default
Destructor.
Member Function Documentation
void initialize () protected
Reset lists (clear existing values) and initialize averaging.
Check requested field averages are valid, populate field lists
Definition at line 41 of file fieldAverage.C.
void restart () protected
Restart averaging for restartOnOutput.
Definition at line 97 of file fieldAverage.C.
void addMeanFieldType (fieldAverageItem & item) protected
Add mean average field to database.
Definition at line 32 of file fieldAverageTemplates.C.
References fieldAverageItem::active(), Foam::endl(), fieldAverageItem::fieldName(), found, Log, fieldAverageItem::mean(), fieldAverageItem::meanFieldName(), IOobject::NO_READ, IOobject::NO_WRITE, regionFunctionObject::obr(), IOobject::READ_IF_PRESENT, fieldAverage::restartOnOutput_, startTime, regIOobject::store(), timeFunctionObject::time(), timeName, and value().
void addMeanField (fieldAverageItem & item) protected
Add mean average field to database.
Definition at line 90 of file fieldAverageTemplates.C.
void addPrime2MeanFieldType (fieldAverageItem & item) protected
Add prime-squared average field to database.
Definition at line 179 of file fieldAverageTemplates.C.
void addPrime2MeanField (fieldAverageItem & item) protected
Add prime-squared average field to database.
Definition at line 234 of file fieldAverageTemplates.C.
void calcAverages () protected virtual
Main calculation routine.
Definition at line 112 of file fieldAverage.C.
void calculateMeanFields () const protected
Calculate mean average fields.
Definition at line 324 of file fieldAverageTemplates.C.
void calculatePrime2MeanFields () const protected
Calculate prime-squared average fields.
Definition at line 340 of file fieldAverageTemplates.C.
void addMeanSqrToPrime2MeanType (const fieldAverageItem & item) const protected
Add mean-squared field value to prime-squared mean field.
Definition at line 364 of file fieldAverageTemplates.C.
void addMeanSqrToPrime2Mean () const protected
Add mean-squared field value to prime-squared mean field.
Definition at line 384 of file fieldAverageTemplates.C.
void storeWindowFieldType (fieldAverageItem & item) protected
Definition at line 265 of file fieldAverageTemplates.C.
void storeWindowFields () protected
Definition at line 305 of file fieldAverageTemplates.C.
void restoreWindowFieldsType (const fieldAverageItem & item) protected
Definition at line 109 of file fieldAverageTemplates.C.
void restoreWindowFields (const fieldAverageItem & item) protected
Definition at line 160 of file fieldAverageTemplates.C.
void writeAverages () const protected virtual
Write averages.
Definition at line 179 of file fieldAverage.C.
void writeFieldType (const word & fieldName) const protected
Write fields.
Definition at line 411 of file fieldAverageTemplates.C.
void writeFields () const protected
Write fields.
Definition at line 424 of file fieldAverageTemplates.C.
void writeAveragingProperties () protected
Write averaging properties - steps and time.
Definition at line 193 of file fieldAverage.C.
void readAveragingProperties () protected
Read averaging properties - steps and time.
Definition at line 204 of file fieldAverage.C.
void operator= (const fieldAverage &) protected delete
No copy assignment.
TypeName ("fieldAverage")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the field average data.
Reimplemented from regionFunctionObject.
Definition at line 281 of file fieldAverage.C.
References Foam::read().
bool execute () virtual
Calculate the field averages.
Implements functionObject.
Definition at line 355 of file fieldAverage.C.
bool write () virtual
Write the field averages.
Implements functionObject.
Definition at line 363 of file fieldAverage.C.
Member Data Documentation
label prevTimeIndex_ protected
Time at last call, prevents repeated averaging.
Definition at line 207 of file fieldAverage.H.
bool initialised_ protected
Initialised flag.
Definition at line 212 of file fieldAverage.H.
Switch restartOnRestart_ protected
Restart the averaging process on restart.
Definition at line 217 of file fieldAverage.H.
Switch restartOnOutput_ protected
Restart the averaging process on output.
Definition at line 222 of file fieldAverage.H.
Referenced by fieldAverage::addMeanFieldType().
Switch periodicRestart_ protected
Periodically restart the averaging process.
Definition at line 227 of file fieldAverage.H.
scalar restartPeriod_ protected
Restart period.
Definition at line 232 of file fieldAverage.H.
scalar restartTime_ protected
Specific restart time.
Definition at line 237 of file fieldAverage.H.
List<fieldAverageItem> faItems_ protected
List of field average items, describing what averages to be.
calculated and output
Definition at line 244 of file fieldAverage.H.
List<label> totalIter_ protected
Iteration steps counter.
Definition at line 251 of file fieldAverage.H.
List<scalar> totalTime_ protected
Total time counter.
Definition at line 256 of file fieldAverage.H.
label periodIndex_ protected
Index for periodic restart.
Definition at line 261 of file fieldAverage.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/fieldAverage/fieldAverage.H
src/functionObjects/field/fieldAverage/fieldAverage.C
src/functionObjects/field/fieldAverage/fieldAverageTemplates.C