OpenFOAM: Roots< N > Class Template Reference
Roots< N > Class Template Reference
Templated storage for the roots of polynomial equations, plus flags to indicate the nature of the roots.
Public Member Functions
Roots ()
Construct null.
Roots (const roots::type t, const scalar x)
Construct with a uniform value.
Roots (const roots::type t, const scalar x, const Roots< N-1 > &xs)
Construct by concatenation.
Roots (const Roots< N-1 > &xs, const roots::type t, const scalar x)
Construct by concatenation.
template<direction M>
Roots (const Roots< M > &xs, const Roots< N-M > &ys)
Construct by concatenation.
void type (const direction i, const roots::type t)
Set the type of the i-th root.
roots::type type (const direction i) const
Return the type of the i-th root.
Public Member Functions inherited from VectorSpace< Roots< N >, scalar, N >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< Roots< N >, scalar, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const scalar & component (const direction) const
scalar & component (const direction)
void component (scalar &, const direction) const
void replace (const direction, const scalar &)
const scalar * cdata () const noexcept
Return const pointer to the first data element.
scalar * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const scalar & operator[] (const direction) const
scalar & operator[] (const direction)
void operator= (const VectorSpace< Roots< N >, scalar, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Roots< N >, scalar, Ncmpts > &)
void operator-= (const VectorSpace< Roots< N >, scalar, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Additional Inherited Members
Public Types inherited from VectorSpace< Roots< N >, scalar, N >
typedef VectorSpace< Roots< N >
, scalar, Ncmpts > vsType
VectorSpace type.
typedef scalar cmptType
Component type.
typedef scalar magType
Magnitude type.
typedef scalar * iterator
Random access iterator for traversing VectorSpace.
typedef const scalar * const_iterator
Random access iterator for traversing VectorSpace.
Static Public Member Functions inherited from VectorSpace< Roots< N >, scalar, N >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Roots< N > uniform (const scalar &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< Roots< N >, scalar, N >
scalar v_ [Ncmpts]
The components of this vector space.
Static Public Attributes inherited from VectorSpace< Roots< N >, scalar, N >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Roots< N > zero
static const Roots< N > one
static const Roots< N > max
static const Roots< N > min
static const Roots< N > rootMax
static const Roots< N > rootMin
Detailed Description
template<direction N>
class Foam::Roots< N >
Templated storage for the roots of polynomial equations, plus flags to indicate the nature of the roots.
Source files
Roots.H
RootsI.H
Roots.C
Definition at line 68 of file Roots.H.
Constructor & Destructor Documentation
Roots () inline
Construct null.
Definition at line 24 of file RootsI.H.
References forAll, and i.
Roots (const roots::type t, const scalar x) inline
Construct with a uniform value.
Definition at line 36 of file RootsI.H.
References i, Foam::roots::nan, and Roots< N >::type().
Roots (const roots::type t, const scalar x, const Roots< N-1 > & xs) inline
Construct by concatenation.
Definition at line 50 of file RootsI.H.
Roots (const Roots< N-1 > & xs, const roots::type t, const scalar x) inline
Construct by concatenation.
Definition at line 70 of file RootsI.H.
Roots (const Roots< M > & xs, const Roots< N-M > & ys) inline
Construct by concatenation.
Definition at line 91 of file RootsI.H.
Member Function Documentation
void type (const direction i, const roots::type t) inline
Set the type of the i-th root.
Definition at line 115 of file RootsI.H.
Referenced by Roots< N >::Roots(), and cubicEqn::roots().
Foam::roots::type type (const direction i) const inline
Return the type of the i-th root.
Definition at line 125 of file RootsI.H.
References Foam::type().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/polynomialEqns/Roots.H
src/OpenFOAM/primitives/polynomialEqns/RootsI.H