OpenFOAM: turbulenceFields Class Reference
turbulenceFields Class Reference
Field function objects
Stores turbulence fields on the mesh database for further manipulation.
Public Types
enum compressibleField {
cfK, cfEpsilon, cfOmega, cfNuTilda,
cfMut, cfMuEff, cfAlphat, cfAlphaEff,
cfR, cfDevRhoReff, cfL, cfI
}
enum incompressibleField {
ifK, ifEpsilon, ifOmega, ifNuTilda,
ifNut, ifNuEff, ifR, ifDevReff,
ifL, ifI
}
Public Member Functions
TypeName ("turbulenceFields")
Runtime type information.
turbulenceFields (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
virtual ~turbulenceFields ()
Destructor.
virtual bool read (const dictionary &)
Read the controls.
virtual bool execute ()
Calculate turbulence fields.
virtual bool write ()
Do nothing.
template<class Model >
Foam::tmp< Foam::volScalarField > omega (const Model &model) const
template<class Model >
Foam::tmp< Foam::volScalarField > nuTilda (const Model &model) const
template<class Model >
Foam::tmp< Foam::volScalarField > L (const Model &model) const
template<class Model >
Foam::tmp< Foam::volScalarField > I (const Model &model) const
Public Member Functions inherited from fvMeshFunctionObject
TypeName ("fvMeshFunctionObject")
Runtime type information.
fvMeshFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
fvMeshFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~fvMeshFunctionObject ()=default
Destructor.
Public Member Functions inherited from regionFunctionObject
TypeName ("regionFunctionObject")
Runtime type information.
regionFunctionObject (const word &name, const Time &runTime, const dictionary &dict)
Construct from Time and dictionary.
regionFunctionObject (const word &name, const objectRegistry &obr, const dictionary &dict)
Construct from the region objectRegistry and dictionary.
virtual ~regionFunctionObject ()=default
Destructor.
template<class ObjectType >
const ObjectType * lookupObjectPtr (const word &fieldName) const
Deprecated(2018-10)
template<class ObjectType >
ObjectType * lookupObjectRefPtr (const word &fieldName) const
Deprecated(2018-10)
Public Member Functions inherited from stateFunctionObject
stateFunctionObject (const word &name, const Time &runTime)
Construct from components.
virtual ~stateFunctionObject ()=default
Destructor.
dictionary & propertyDict ()
Return access to the property dictionary.
bool foundProperty (const word &entryName) const
Return true if the property exists.
label getTrigger () const
Get the current trigger index.
bool setTrigger (const label triggeri)
Set the current trigger index.
bool getDict (const word &entryName, dictionary &dict) const
Set dictionary, return true if set.
bool getObjectDict (const word &objectName, const word &entryName, dictionary &dict) const
Set dictionary from named object, return true if set.
template<class Type >
Type getProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property.
template<class Type >
bool getProperty (const word &entryName, Type &value) const
Set generic property, return true if set.
template<class Type >
void setProperty (const word &entryName, const Type &value)
Add generic property.
template<class Type >
Type getObjectProperty (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from named object.
template<class Type >
bool getObjectProperty (const word &objectName, const word &entryName, Type &value) const
Set generic property from named object, return true if set.
template<class Type >
void setObjectProperty (const word &objectName, const word &entryName, const Type &value)
Add generic property from named object.
template<class Type >
void setResult (const word &entryName, const Type &value)
Add result.
template<class Type >
void setObjectResult (const word &objectName, const word &entryName, const Type &value)
Add result from named object.
template<class Type >
Type getResult (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result.
template<class Type >
Type getObjectResult (const word &objectName, const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve result from named object.
template<class Type >
bool getObjectResult (const word &objectName, const word &entryName, Type &value) const
Set result from named object, return true if set.
word resultType (const word &entryName) const
Retrieve the result type.
word objectResultType (const word &objectName, const word &entryName) const
Return the type of result.
List< word > objectResultEntries () const
Retrieve the result entries.
List< word > objectResultEntries (const word &objectName) const
Return result entries for named object.
void writeResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
void writeResultEntries (const word &objectName, Ostream &os) const
Write the results entries for named object to stream.
void writeAllResultEntries (Ostream &os) const
Write the results entries for all objects to stream.
Public Member Functions inherited from timeFunctionObject
timeFunctionObject (const word &name, const Time &runTime)
Construct from Time.
virtual ~timeFunctionObject ()=default
Destructor.
const Time & time () const
Return time database.
objectRegistry & storedObjects ()
Write access to the output objects ("functionObjectObjects") registered on Time.
const objectRegistry & storedObjects () const
Const access to the output objects ("functionObjectObjects") registered on Time.
Public Member Functions inherited from functionObject
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()=default
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool execute (const label subIndex)
Execute using the specified subIndex.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool filesModified () const
Did any file get changed during execution?
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Attributes
static const Enum
< compressibleField > compressibleFieldNames_
static const Enum
< incompressibleField > incompressibleFieldNames_
static const word modelName
Static Public Attributes inherited from functionObject
static int debug
static bool postProcess
Global post-processing mode switch.
static word outputPrefix
Directory prefix.
Protected Member Functions
bool compressible ()
Return true if compressible turbulence model is identified.
template<class Type >
void processField (const word &fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh >> &tvalue)
Process the turbulence field.
template<class Model >
tmp< volScalarField > omega (const Model &model) const
Return omega calculated from k and epsilon.
template<class Model >
tmp< volScalarField > nuTilda (const Model &model) const
Return nuTilda calculated from k and omega.
template<class Model >
tmp< volScalarField > L (const Model &model) const
Return L calculated from k and epsilon.
template<class Model >
tmp< volScalarField > I (const Model &model) const
Return I calculated from k and U.
Protected Member Functions inherited from fvMeshFunctionObject
fvMeshFunctionObject (const fvMeshFunctionObject &)=delete
No copy construct.
void operator= (const fvMeshFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from regionFunctionObject
virtual const objectRegistry & obr () const
The region or sub-region registry being used.
template<class ObjectType >
bool foundObject (const word &fieldName) const
Find object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
const ObjectType * cfindObject (const word &fieldName) const
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
const ObjectType * findObject (const word &fieldName) const
Return const pointer to the object (eg, a field) in the (sub) objectRegistry.
template<class ObjectType >
ObjectType * findObject (const word &fieldName)
Return non-const pointer to the object of the given Type, (sub) objectRegistry.
template<class ObjectType >
ObjectType * getObjectPtr (const word &fieldName) const
Return non-const pointer to the object of the given Type, using a const-cast to have it behave like a mutable.
template<class ObjectType >
const ObjectType & lookupObject (const word &fieldName) const
Lookup and return object (eg, a field) from the (sub) objectRegistry.
template<class ObjectType >
ObjectType & lookupObjectRef (const word &fieldName) const
Lookup and return object (eg, a field) from the (sub) objectRegistry.
template<class ObjectType >
bool store (word &fieldName, const tmp< ObjectType > &tfield, bool cacheable=false)
Store the field in the (sub) objectRegistry under the given name.
bool writeObject (const word &fieldName)
Write field if present in the (sub) objectRegistry.
bool clearObject (const word &fieldName)
Clear field from the (sub) objectRegistry if present.
void clearObjects (const wordList &objNames)
Clear fields from the (sub) objectRegistry if present.
regionFunctionObject (const regionFunctionObject &)=delete
No copy construct.
void operator= (const regionFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from stateFunctionObject
const IOdictionary & stateDict () const
Return a const reference to the state dictionary.
IOdictionary & stateDict ()
Return non-const access to the state dictionary.
stateFunctionObject (const stateFunctionObject &)=delete
No copy construct.
void operator= (const stateFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from timeFunctionObject
void clearOutputObjects (const wordList &objNames)
Remove specified items from "functionObjectObjects".
timeFunctionObject (const timeFunctionObject &)=delete
No copy construct.
void operator= (const timeFunctionObject &)=delete
No copy assignment.
Protected Member Functions inherited from functionObject
word scopedName (const word &name) const
Return a scoped name, e.g. used to construct local field names.
Protected Attributes
wordHashSet fieldSet_
Fields to load.
Protected Attributes inherited from fvMeshFunctionObject
const fvMesh & mesh_
Reference to the fvMesh.
Protected Attributes inherited from regionFunctionObject
word subRegistryName_
Name for alternative object registry.
const objectRegistry & obr_
Reference to the region objectRegistry.
const objectRegistry * obrPtr_
Pointer to alternative (eg, sub-region) objectRegistry.
Protected Attributes inherited from timeFunctionObject
const Time & time_
Reference to the time database.
Additional Inherited Members
Static Public Member Functions inherited from functionObject
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Select from dictionary, based on its "type" entry.
Public Attributes inherited from functionObject
bool log
Switch write log to Info.
Detailed Description
Stores turbulence fields on the mesh database for further manipulation.
Fields are stored as copies of the original, with the prefix "tubulenceModel:", e.g.:
turbulenceModel:R
Usage
Example of function object specification:
turbulenceFields1
{
    type        turbulenceFields;
    libs        ("libfieldFunctionObjects.so");
    ...
    fields
    (
        R
        devRhoReff
    );
}
Where the entries comprise:
Property Description Required Default value
type type name: turbulenceFields yes
fields fields to store (see below) yes
Where fields can include:
k : turbulence kinetic energy
epsilon : turbulence kinetic energy dissipation rate
omega : turbulence specific dissipation rate
nuTilda : turbulence modified viscosity
nut : turbulence viscosity (incompressible)
nuEff : effective turbulence viscosity (incompressible)
mut : turbulence viscosity (compressible)
muEff : effective turbulence viscosity (compressible)
alphat : turbulence thermal diffusivity (compressible)
alphaEff : effective turbulence thermal diffusivity (compressible)
R : Reynolds stress tensor
devReff : Deviatoric part of the effective Reynolds stress
devRhoReff : Divergence of the Reynolds stress
L : turbulence length scale
I : turbulence intensity
See Also
Foam::functionObjects::fvMeshFunctionObject Foam::functionObjects::timeControl
Source files
turbulenceFields.H
turbulenceFields.C
Definition at line 184 of file turbulenceFields.H.
Member Enumeration Documentation
enum compressibleField
Enumerator
cfK
cfEpsilon
cfOmega
cfNuTilda
cfMut
cfMuEff
cfAlphat
cfAlphaEff
cfR
cfDevRhoReff
cfL
cfI
Definition at line 190 of file turbulenceFields.H.
enum incompressibleField
Enumerator
ifK
ifEpsilon
ifOmega
ifNuTilda
ifNut
ifNuEff
ifR
ifDevReff
ifL
ifI
Definition at line 207 of file turbulenceFields.H.
Constructor & Destructor Documentation
turbulenceFields (const word & name, const Time & runTime, const dictionary & dict)
Construct from Time and dictionary.
Definition at line 114 of file turbulenceFields.C.
~turbulenceFields () virtual
Destructor.
Definition at line 129 of file turbulenceFields.C.
References Foam::read().
Member Function Documentation
bool compressible () protected
Return true if compressible turbulence model is identified.
Definition at line 92 of file turbulenceFields.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, objectRegistry::foundObject(), turbulenceFields::modelName, and regionFunctionObject::obr_.
void processField (const word & fieldName, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvalue) protected
Process the turbulence field.
Definition at line 28 of file turbulenceFieldsTemplates.C.
References Foam::endl(), objectRegistry::found(), objectRegistry::getObjectPtr(), turbulenceFields::modelName, Foam::nl, IOobject::NO_WRITE, regionFunctionObject::obr_, IOobject::READ_IF_PRESENT, functionObject::scopedName(), regIOobject::store(), objectRegistry::time(), Time::timeName(), and WarningInFunction.
tmp<volScalarField> omega (const Model & model) const protected
Return omega calculated from k and epsilon.
tmp<volScalarField> nuTilda (const Model & model) const protected
Return nuTilda calculated from k and omega.
tmp<volScalarField> L (const Model & model) const protected
Return L calculated from k and epsilon.
tmp<volScalarField> I (const Model & model) const protected
Return I calculated from k and U.
TypeName ("turbulenceFields")
Runtime type information.
bool read (const dictionary & dict) virtual
Read the controls.
Reimplemented from regionFunctionObject.
Definition at line 135 of file turbulenceFields.C.
bool execute () virtual
Calculate turbulence fields.
Implements functionObject.
Definition at line 167 of file turbulenceFields.C.
bool write () virtual
Do nothing.
The turbulence fields are registered and written automatically
Implements functionObject.
Definition at line 320 of file turbulenceFields.C.
Foam::tmp<Foam::volScalarField> omega (const Model & model) const
Definition at line 74 of file turbulenceFieldsTemplates.C.
Foam::tmp<Foam::volScalarField> nuTilda (const Model & model) const
Definition at line 101 of file turbulenceFieldsTemplates.C.
Foam::tmp<Foam::volScalarField> L (const Model & model) const
Definition at line 116 of file turbulenceFieldsTemplates.C.
Foam::tmp<Foam::volScalarField> I (const Model & model) const
Definition at line 138 of file turbulenceFieldsTemplates.C.
Member Data Documentation
const Foam::Enum< Foam::functionObjects::turbulenceFields::compressibleField > compressibleFieldNames_ static
Definition at line 205 of file turbulenceFields.H.
const Foam::Enum< Foam::functionObjects::turbulenceFields::incompressibleField > incompressibleFieldNames_ static
Definition at line 220 of file turbulenceFields.H.
const Foam::word modelName static
Definition at line 222 of file turbulenceFields.H.
Referenced by turbulenceFields::compressible(), and turbulenceFields::processField().
wordHashSet fieldSet_ protected
Fields to load.
Definition at line 232 of file turbulenceFields.H.
The documentation for this class was generated from the following files:
src/functionObjects/field/turbulenceFields/turbulenceFields.H
src/functionObjects/field/turbulenceFields/turbulenceFields.C
src/functionObjects/field/turbulenceFields/turbulenceFieldsTemplates.C