OpenFOAM: MeshedSurfaceProxy< Face > Class Template Reference
MeshedSurfaceProxy< Face > Class Template Reference
A proxy for writing MeshedSurface, UnsortedMeshedSurface and surfMesh to various file formats.
Public Types
typedef Face FaceType
Face type used.
Public Member Functions
ClassName ("MeshedSurfaceProxy")
Runtime type information.
MeshedSurfaceProxy (const pointField &pointLst, const UList< Face > &faceLst, const UList< surfZone > &zoneLst=List< surfZone >(), const labelUList &faceMap=labelUList::null())
Construct from component references.
virtual ~MeshedSurfaceProxy ()=default
Destructor.
declareMemberFunctionSelectionTable (void, MeshedSurfaceProxy, write, fileExtension,(const fileName &name, const MeshedSurfaceProxy< Face > &surf, const dictionary &options),(name, surf, options))
label size () const
The surface size is the number of faces.
const pointField & points () const
Return const access to the points.
const UList< Face > & surfFaces () const
Return const access to the faces.
const UList< surfZone > & surfZones () const
Const access to the surface zones.
const labelUList & faceMap () const
Const access to the faceMap, zero-sized when unused.
bool useFaceMap () const
Use faceMap?
label nTriangles () const
Count number of triangles.
virtual void write (const fileName &name, const dictionary &options=dictionary::null) const
Generic write routine. Chooses writer based on its extension.
virtual void write (const fileName &name, const word &ext, const dictionary &options=dictionary::null) const
Generic write routine. Chooses writer based on extension.
virtual void write (const Time &t, const word &surfName=word::null) const
Write to database.
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
Construct null.
virtual ~surfaceFormatsCore ()=default
Destructor.
Static Public Member Functions
static wordHashSet writeTypes ()
The file format types that can be written via MeshedSurfaceProxy.
static bool canWriteType (const word &ext, const bool verbose=false)
Can this file format type be written via MeshedSurfaceProxy?
static void write (const fileName &name, const MeshedSurfaceProxy &surf, const dictionary &options)
Write to file, select based on its extension.
static void write (const fileName &name, const word &ext, const MeshedSurfaceProxy &surf, const dictionary &options)
Write to file, selected based on given extension.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Helper function when checking if a file extension is supported.
static fileName localMeshFileName (const word &surfName=word::null)
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName=word::null)
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName=word::null)
Find mesh file with surfName.
Additional Inherited Members
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Read non-empty and non-comment line.
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a surfZone list with a single entry, the size of which corresponds to that of the container.
Detailed Description
template<class Face>
class Foam::MeshedSurfaceProxy< Face >
A proxy for writing MeshedSurface, UnsortedMeshedSurface and surfMesh to various file formats.
Source files
MeshedSurfaceProxy.H
MeshedSurfaceProxy.C
MeshedSurfaceProxys.C
Definition at line 74 of file MeshedSurface.H.
Member Typedef Documentation
typedef Face FaceType
Face type used.
Definition at line 82 of file MeshedSurfaceProxy.H.
Constructor & Destructor Documentation
MeshedSurfaceProxy (const pointField & pointLst, const UList< Face > & faceLst, const UList< surfZone > & zoneLst = List<surfZone>(), const labelUList & faceMap = labelUList::null())
Construct from component references.
Definition at line 224 of file MeshedSurfaceProxy.C.
virtual ~MeshedSurfaceProxy () virtual default
Destructor.
Member Function Documentation
ClassName ("MeshedSurfaceProxy< Face >")
Runtime type information.
Foam::wordHashSet writeTypes () static
The file format types that can be written via MeshedSurfaceProxy.
Definition at line 33 of file MeshedSurfaceProxy.C.
bool canWriteType (const word & ext, const bool verbose = false) static
Can this file format type be written via MeshedSurfaceProxy?
Definition at line 41 of file MeshedSurfaceProxy.C.
declareMemberFunctionSelectionTable (void , MeshedSurfaceProxy< Face > , write , fileExtension , (const fileName &name, const MeshedSurfaceProxy< Face > &surf, const dictionary &options) , (name, surf, options))
void write (const fileName & name, const MeshedSurfaceProxy< Face > & surf, const dictionary & options) static
Write to file, select based on its extension.
Definition at line 55 of file MeshedSurfaceProxy.C.
Referenced by MeshedSurfaceProxy< Face >::faceMap(), and MeshedSurfaceProxy< Face >::useFaceMap().
void write (const fileName & name, const word & ext, const MeshedSurfaceProxy< Face > & surf, const dictionary & options) static
Write to file, selected based on given extension.
Definition at line 67 of file MeshedSurfaceProxy.C.
References fileName::ext(), and Foam::vtk::write().
label size () const inline
The surface size is the number of faces.
Definition at line 168 of file MeshedSurfaceProxy.H.
const pointField& points () const inline
Return const access to the points.
Definition at line 176 of file MeshedSurfaceProxy.H.
Referenced by FLMAsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), and SMESHsurfaceFormat< Face >::write().
const UList<Face>& surfFaces () const inline
Return const access to the faces.
Definition at line 184 of file MeshedSurfaceProxy.H.
Referenced by FLMAsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), and SMESHsurfaceFormat< Face >::write().
const UList<surfZone>& surfZones () const inline
Const access to the surface zones.
If zones are defined, they must be contiguous and cover the entire surface
Definition at line 195 of file MeshedSurfaceProxy.H.
Referenced by FLMAsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), and SMESHsurfaceFormat< Face >::write().
const labelUList& faceMap () const inline
Const access to the faceMap, zero-sized when unused.
Definition at line 203 of file MeshedSurfaceProxy.H.
References MeshedSurfaceProxy< Face >::write().
Referenced by FLMAsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), and SMESHsurfaceFormat< Face >::write().
bool useFaceMap () const inline
Use faceMap?
Definition at line 211 of file MeshedSurfaceProxy.H.
References MeshedSurfaceProxy< Face >::write().
Referenced by FLMAsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), and SMESHsurfaceFormat< Face >::write().
Foam::label nTriangles () const inline
Count number of triangles.
Definition at line 241 of file MeshedSurfaceProxy.C.
virtual void write (const fileName & name, const dictionary & options = dictionary::null) const inline virtual
Generic write routine. Chooses writer based on its extension.
Definition at line 228 of file MeshedSurfaceProxy.H.
virtual void write (const fileName & name, const word & ext, const dictionary & options = dictionary::null) const inline virtual
Generic write routine. Chooses writer based on extension.
Definition at line 240 of file MeshedSurfaceProxy.H.
void write (const Time & t, const word & surfName = word::null) const virtual
Write to database.
Definition at line 96 of file MeshedSurfaceProxy.C.
The documentation for this class was generated from the following files:
src/surfMesh/MeshedSurface/MeshedSurface.H
src/surfMesh/MeshedSurfaceProxy/MeshedSurfaceProxy.H
src/surfMesh/MeshedSurfaceProxy/MeshedSurfaceProxy.C