OpenFOAM: sweepData Class Reference
sweepData Class Reference
Helper class used by fvc::sweep function.
Public Member Functions
sweepData ()
Construct null.
sweepData (const scalar value, const point &origin)
Construct from component.
scalar value () const
Return value.
const point & origin () const
Return origin.
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const sweepData &, const scalar, TrackingData &td) const
Check for identical geometrical data.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const sweepData &svf, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const sweepData &, TrackingData &td) const
Same (like operator==)
void operator= (const scalar value)
bool operator== (const sweepData &) const
bool operator!= (const sweepData &) const
Friends
Ostream & operator<< (Ostream &os, const sweepData &svf)
Istream & operator>> (Istream &is, sweepData &svf)
Detailed Description
Helper class used by fvc::sweep function.
Source files
sweepData.H
sweepData.H
sweepDataI.H
Definition at line 46 of file sweepData.H.
Constructor & Destructor Documentation
sweepData () inline
Construct null.
Definition at line 69 of file sweepDataI.H.
sweepData (const scalar value, const point & origin) inline
Construct from component.
Definition at line 76 of file sweepDataI.H.
Member Function Documentation
scalar value () const inline
Return value.
Definition at line 90 of file sweepData.H.
const point& origin () const inline
Return origin.
Definition at line 98 of file sweepData.H.
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value
Definition at line 86 of file sweepDataI.H.
bool sameGeometry (const polyMesh & , const sweepData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data.
Used for cyclics checking
Definition at line 94 of file sweepDataI.H.
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to.
(patch)face centre
Definition at line 107 of file sweepDataI.H.
void enterDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 133 of file sweepDataI.H.
References origin_(), and Foam::transform().
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 121 of file sweepDataI.H.
References origin_().
bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 148 of file sweepDataI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 163 of file sweepDataI.H.
References primitiveMesh::cellCentres(), and update().
bool updateFace (const polyMesh & mesh, const label thisFacei, const sweepData & svf, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 179 of file sweepDataI.H.
bool equal (const sweepData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 193 of file sweepDataI.H.
References primitiveMesh::faceCentres(), and update().
void operator= (const scalar value) inline
Definition at line 205 of file sweepDataI.H.
bool operator== (const sweepData & rhs) const inline
Definition at line 214 of file sweepDataI.H.
References value().
bool operator!= (const sweepData & rhs) const inline
Definition at line 223 of file sweepDataI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const sweepData & svf) friend
Definition at line 228 of file sweepData.H.
Istream& operator>> (Istream & is, sweepData & svf) friend
Definition at line 236 of file sweepData.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepData.H
src/finiteVolume/finiteVolume/fvc/fvcSmooth/sweepDataI.H