OpenFOAM: gaussLaplacianScheme< Type > Class Template Reference
gaussLaplacianScheme< Type > Class Template Reference
Basic second-order laplacian using face-gradients and Gauss' theorem.
Public Member Functions
TypeName ("Gauss")
Runtime type information.
gaussLaplacianScheme (const faMesh &mesh)
Construct null.
gaussLaplacianScheme (const faMesh &mesh, Istream &is)
Construct from Istream.
tmp< faMatrix< Type > > famLaplacian (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facLaplacian (const GeometricField< Type, faPatchField, areaMesh > &)
tmp< GeometricField< Type,
faPatchField, areaMesh > > facLaplacian (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
Public Member Functions inherited from laplacianScheme< Type >
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const faMesh &mesh)
Construct from mesh.
laplacianScheme (const faMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~laplacianScheme ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
virtual tmp< faMatrix< Type > > famLaplacian (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
virtual tmp< GeometricField
< Type, faPatchField, areaMesh > > facLaplacian (const areaScalarField &, const GeometricField< Type, faPatchField, areaMesh > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from laplacianScheme< Type >
static tmp< laplacianScheme
< Type > > New (const faMesh &mesh, Istream &schemeData)
Return a pointer to a new laplacianScheme created on freestore.
Protected Member Functions inherited from laplacianScheme< Type >
laplacianScheme (const laplacianScheme &)=delete
No copy construct.
void operator= (const laplacianScheme &)=delete
No copy assignment.
Protected Attributes inherited from laplacianScheme< Type >
const faMesh & mesh_
tmp< edgeInterpolationScheme
< scalar > > tinterpGammaScheme_
tmp< lnGradScheme< Type > > tlnGradScheme_
Detailed Description
template<class Type>
class Foam::fa::gaussLaplacianScheme< Type >
Basic second-order laplacian using face-gradients and Gauss' theorem.
Source files
gaussFaLaplacianScheme.H
gaussFaLaplacianScheme.C
gaussFaLaplacianSchemes.C
Definition at line 53 of file gaussFaLaplacianScheme.H.
Constructor & Destructor Documentation
gaussLaplacianScheme (const faMesh & mesh) inline
Construct null.
Definition at line 83 of file gaussFaLaplacianScheme.H.
gaussLaplacianScheme (const faMesh & mesh, Istream & is) inline
Construct from Istream.
Definition at line 91 of file gaussFaLaplacianScheme.H.
Member Function Documentation
TypeName ("Gauss")
Runtime type information.
tmp< faMatrix< Type > > famLaplacian (const edgeScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements laplacianScheme< Type >.
Definition at line 40 of file gaussFaLaplacianScheme.C.
References faMatrix< Type >::boundaryCoeffs(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), Foam::correction(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fac::div(), faMatrix< Type >::faceFluxCorrectionPtr(), forAll, gamma, faPatchField< Type >::gradientBoundaryCoeffs(), faPatchField< Type >::gradientInternalCoeffs(), faMatrix< Type >::internalCoeffs(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, IOobject::name(), lduMatrix::negSumDiag(), faMatrix< Type >::psi(), tmp< T >::ref(), faMatrix< Type >::source(), and lduMatrix::upper().
tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements laplacianScheme< Type >.
Definition at line 109 of file gaussFaLaplacianScheme.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > facLaplacian (const edgeScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf) virtual
Implements laplacianScheme< Type >.
Definition at line 127 of file gaussFaLaplacianScheme.C.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/laplacianSchemes/gaussFaLaplacianScheme/gaussFaLaplacianScheme.H
src/finiteArea/finiteArea/laplacianSchemes/gaussFaLaplacianScheme/gaussFaLaplacianScheme.C