OpenFOAM: SymmTensor< Cmpt > Class Template Reference
SymmTensor< Cmpt > Class Template Reference
Templated 3D symmetric tensor derived from VectorSpace adding construction from 6 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Public Types
enum components {
XX, XY, XZ, YY,
YZ, ZZ
}
Component labeling enumeration.
typedef SymmTensor< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
typedef VectorSpace
< SymmTensor< Cmpt >, Cmpt,
Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
typedef Cmpt magType
Magnitude type.
typedef Cmpt * iterator
Random access iterator for traversing VectorSpace.
typedef const Cmpt * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
SymmTensor ()
Construct null.
SymmTensor (const Foam::zero)
Construct initialized to zero.
template<class Cmpt2 >
SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > &)
Construct given VectorSpace of the same rank.
SymmTensor (const SphericalTensor< Cmpt > &)
Construct given SphericalTensor.
SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz)
Construct given the six components.
SymmTensor (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & xz () const
const Cmpt & yy () const
const Cmpt & yz () const
const Cmpt & zz () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & xz ()
Cmpt & yy ()
Cmpt & yz ()
Cmpt & zz ()
Vector< Cmpt > diag () const
Extract the diagonal as a vector.
void diag (const Vector< Cmpt > &v)
Set values of the diagonal.
const SymmTensor< Cmpt > & T () const
Transpose.
void operator= (const SphericalTensor< Cmpt > &)
Assign to given SphericalTensor.
Public Member Functions inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Return const pointer to the first data element.
Cmpt * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SymmTensor< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Static Public Attributes
static constexpr direction rank = 2
Rank of SymmTensor is 2.
static const SymmTensor I
Static Public Attributes inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const SymmTensor< Cmpt > zero
static const SymmTensor< Cmpt > one
static const SymmTensor< Cmpt > max
static const SymmTensor< Cmpt > min
static const SymmTensor< Cmpt > rootMax
static const SymmTensor< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static SymmTensor< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< SymmTensor< Cmpt >, Cmpt, 6 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::SymmTensor< Cmpt >
Templated 3D symmetric tensor derived from VectorSpace adding construction from 6 components, element access using xx(), xy() etc. member functions and the inner-product (dot-product) and outer-product of two Vectors (tensor-product) operators.
Source files
SymmTensor.H
SymmTensorI.H
Definition at line 53 of file SymmTensor.H.
Member Typedef Documentation
typedef SymmTensor<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 63 of file SymmTensor.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
XX
XY
XZ
YY
YZ
ZZ
Definition at line 82 of file SymmTensor.H.
Constructor & Destructor Documentation
SymmTensor () inline
Construct null.
Definition at line 27 of file SymmTensorI.H.
SymmTensor (const Foam::zero) inline
Construct initialized to zero.
Definition at line 32 of file SymmTensorI.H.
SymmTensor (const VectorSpace< SymmTensor< Cmpt2 >, Cmpt2, 6 > & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 41 of file SymmTensorI.H.
SymmTensor (const SphericalTensor< Cmpt > & st) inline
Construct given SphericalTensor.
Definition at line 50 of file SymmTensorI.H.
SymmTensor (const Cmpt txx, const Cmpt txy, const Cmpt txz, const Cmpt tyy, const Cmpt tyz, const Cmpt tzz) inline
Construct given the six components.
Definition at line 60 of file SymmTensorI.H.
SymmTensor (Istream & is) inline
Construct from Istream.
Definition at line 73 of file SymmTensorI.H.
Member Function Documentation
const Cmpt & xx () const inline
Definition at line 82 of file SymmTensorI.H.
Referenced by Foam::det(), Foam::dev(), Foam::invariantI(), Foam::invariantII(), Foam::invariantIII(), Foam::operator&(), Foam::operator&&(), Foam::operator-(), and Foam::transform().
const Cmpt & xy () const inline
Definition at line 88 of file SymmTensorI.H.
Referenced by Foam::dev(), Foam::dev2(), Foam::invariantI(), Foam::invariantII(), Foam::invariantIII(), Foam::operator&(), Foam::operator&&(), Foam::operator*(), Foam::operator-(), and Foam::transform().
const Cmpt & xz () const inline
Definition at line 94 of file SymmTensorI.H.
Referenced by Foam::dev(), Foam::dev2(), Foam::invariantI(), Foam::invariantII(), Foam::invariantIII(), Foam::operator&(), Foam::operator&&(), Foam::operator*(), Foam::operator-(), and Foam::transform().
const Cmpt & yy () const inline
Definition at line 100 of file SymmTensorI.H.
Referenced by Foam::det(), Foam::dev(), Foam::dev2(), Foam::invariantI(), Foam::invariantII(), Foam::operator&(), Foam::operator&&(), Foam::operator-(), and Foam::transform().
const Cmpt & yz () const inline
Definition at line 106 of file SymmTensorI.H.
Referenced by Foam::dev(), Foam::dev2(), Foam::invariantI(), Foam::invariantII(), Foam::operator&(), Foam::operator&&(), Foam::operator*(), Foam::operator-(), and Foam::transform().
const Cmpt & zz () const inline
Definition at line 112 of file SymmTensorI.H.
Referenced by Foam::det(), Foam::dev(), Foam::dev2(), Foam::invariantI(), Foam::invariantII(), Foam::operator&(), Foam::operator&&(), Foam::operator-(), and Foam::transform().
Cmpt & xx () inline
Definition at line 119 of file SymmTensorI.H.
Cmpt & xy () inline
Definition at line 125 of file SymmTensorI.H.
Cmpt & xz () inline
Definition at line 131 of file SymmTensorI.H.
Cmpt & yy () inline
Definition at line 137 of file SymmTensorI.H.
Cmpt & yz () inline
Definition at line 143 of file SymmTensorI.H.
Cmpt & zz () inline
Definition at line 149 of file SymmTensorI.H.
Foam::Vector< Cmpt > diag () const inline
Extract the diagonal as a vector.
Definition at line 156 of file SymmTensorI.H.
void diag (const Vector< Cmpt > & v) inline
Set values of the diagonal.
Definition at line 163 of file SymmTensorI.H.
const Foam::SymmTensor< Cmpt > & T () const inline
Transpose.
Definition at line 170 of file SymmTensorI.H.
References Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
void operator= (const SphericalTensor< Cmpt > & st) inline
Assign to given SphericalTensor.
Definition at line 179 of file SymmTensorI.H.
Member Data Documentation
constexpr direction rank = 2 static
Rank of SymmTensor is 2.
Definition at line 71 of file SymmTensor.H.
const Foam::labelSymmTensor I static
Definition at line 76 of file SymmTensor.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/SymmTensor/SymmTensor.H
src/OpenFOAM/primitives/SymmTensor/labelSymmTensor/labelSymmTensor.C
src/OpenFOAM/primitives/SymmTensor/SymmTensorI.H