OpenFOAM: Tensor2D< Cmpt > Class Template Reference
Tensor2D< Cmpt > Class Template Reference
Templated 2D tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy(), yx() and yy() member functions and the iner-product (dot-product) and outer-product of two Vector2Ds (tensor-product) operators.
Public Types
enum components { XX, XY, YX, YY }
Component labeling enumeration.
typedef Tensor2D< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
typedef VectorSpace< Tensor2D
< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
typedef Cmpt magType
Magnitude type.
typedef Cmpt * iterator
Random access iterator for traversing VectorSpace.
typedef const Cmpt * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
Tensor2D ()=default
Construct null.
Tensor2D (const Foam::zero)
Construct initialized to zero.
Tensor2D (const VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 > &vs)
Construct given VectorSpace.
Tensor2D (const SymmTensor2D< Cmpt > &st)
Construct given SymmTensor2D.
Tensor2D (const SphericalTensor2D< Cmpt > &st)
Construct given SphericalTensor2D.
Tensor2D (const Vector2D< Cmpt > &x, const Vector2D< Cmpt > &y)
Construct given the two row vectors.
Tensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyx, const Cmpt tyy)
Construct given the four components.
Tensor2D (Istream &)
Construct from Istream.
const Cmpt & xx () const
const Cmpt & xy () const
const Cmpt & yx () const
const Cmpt & yy () const
Cmpt & xx ()
Cmpt & xy ()
Cmpt & yx ()
Cmpt & yy ()
Vector2D< Cmpt > cx () const
Extract vector for column 0.
Vector2D< Cmpt > cy () const
Extract vector for column 1.
template<direction Col>
Vector2D< Cmpt > col () const
Extract vector for given column.
Vector2D< Cmpt > col (const direction c) const
Extract vector for given column (0,1).
template<direction Col>
void col (const Vector2D< Cmpt > &v)
Set values of given column.
void col (const direction c, const Vector2D< Cmpt > &v)
Set values of given column (0,1)
void cols (const Vector2D< Cmpt > &x, const Vector2D< Cmpt > &y)
Set column values.
Vector2D< Cmpt > x () const
Extract vector for row 0.
Vector2D< Cmpt > y () const
Extract vector for row 1.
template<direction Row>
Vector2D< Cmpt > row () const
Extract vector for given row.
Vector2D< Cmpt > row (const direction r) const
Extract vector for given row (0,1)
template<direction Row>
void row (const Vector2D< Cmpt > &v)
Set values of given row.
void row (const direction r, const Vector2D< Cmpt > &v)
Set values of given row (0,1)
void rows (const Vector2D< Cmpt > &x, const Vector2D< Cmpt > &y)
Set row values.
Vector2D< Cmpt > diag () const
Extract the diagonal as a vector.
void diag (const Vector2D< Cmpt > &v)
Set values of the diagonal.
Tensor2D< Cmpt > T () const
Return transpose.
Tensor2D< Cmpt > inner (const Tensor2D< Cmpt > &t2) const
Inner-product of this with another Tensor2D.
Tensor2D< Cmpt > schur (const Tensor2D< Cmpt > &t2) const
Schur-product of this with another Tensor2D.
void operator= (const SymmTensor2D< Cmpt > &)
Copy assign from SymmTensor2D.
void operator= (const SphericalTensor2D< Cmpt > &)
Copy assign from SphericalTensor2D.
Vector2D< Cmpt > vectorComponent (const direction cmpt) const
Deprecated(2018-12) Return vector for given row (0,1)
template<Foam::direction Col>
Foam::Vector2D< Cmpt > col () const
template<Foam::direction Row>
Foam::Vector2D< Cmpt > row () const
Public Member Functions inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Return const pointer to the first data element.
Cmpt * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Tensor2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Static Public Attributes
static constexpr direction rank = 2
Rank of Tensor2D is 2.
static const Tensor2D I
Static Public Attributes inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Tensor2D< Cmpt > zero
static const Tensor2D< Cmpt > one
static const Tensor2D< Cmpt > max
static const Tensor2D< Cmpt > min
static const Tensor2D< Cmpt > rootMax
static const Tensor2D< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Tensor2D< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Tensor2D< Cmpt >
Templated 2D tensor derived from VectorSpace adding construction from 4 components, element access using xx(), xy(), yx() and yy() member functions and the iner-product (dot-product) and outer-product of two Vector2Ds (tensor-product) operators.
Source files
Tensor2D.H
Tensor2DI.H
Definition at line 55 of file Tensor2D.H.
Member Typedef Documentation
typedef Tensor2D<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 65 of file Tensor2D.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
XX
XY
YX
YY
Definition at line 84 of file Tensor2D.H.
Constructor & Destructor Documentation
Tensor2D () default
Construct null.
Tensor2D (const Foam::zero) inline
Construct initialized to zero.
Definition at line 25 of file Tensor2DI.H.
Tensor2D (const VectorSpace< Tensor2D< Cmpt >, Cmpt, 4 > & vs) inline
Construct given VectorSpace.
Definition at line 33 of file Tensor2DI.H.
Tensor2D (const SymmTensor2D< Cmpt > & st) inline
Construct given SymmTensor2D.
Definition at line 42 of file Tensor2DI.H.
Tensor2D (const SphericalTensor2D< Cmpt > & st) inline
Construct given SphericalTensor2D.
Definition at line 50 of file Tensor2DI.H.
References SymmTensor2D< Cmpt >::xx(), SymmTensor2D< Cmpt >::xy(), and SymmTensor2D< Cmpt >::yy().
Tensor2D (const Vector2D< Cmpt > & x, const Vector2D< Cmpt > & y) inline
Construct given the two row vectors.
Definition at line 61 of file Tensor2DI.H.
Tensor2D (const Cmpt txx, const Cmpt txy, const Cmpt tyx, const Cmpt tyy) inline
Construct given the four components.
Definition at line 73 of file Tensor2DI.H.
Tensor2D (Istream & is) inline
Construct from Istream.
Definition at line 84 of file Tensor2DI.H.
Member Function Documentation
const Cmpt & xx () const inline
Definition at line 93 of file Tensor2DI.H.
Referenced by Foam::dev(), Foam::dev2(), Foam::operator&(), Foam::operator+(), Foam::operator-(), and Foam::sph().
const Cmpt & xy () const inline
Definition at line 99 of file Tensor2DI.H.
Referenced by Foam::dev(), Foam::dev2(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::sph(), and Foam::twoSymm().
const Cmpt & yx () const inline
Definition at line 105 of file Tensor2DI.H.
Referenced by Foam::dev(), Foam::dev2(), Foam::operator&(), Foam::operator+(), Foam::operator-(), Foam::sph(), and Foam::twoSymm().
const Cmpt & yy () const inline
Definition at line 111 of file Tensor2DI.H.
Referenced by Foam::dev(), Foam::dev2(), Foam::operator&(), Foam::operator+(), Foam::operator-(), and Foam::sph().
Cmpt & xx () inline
Definition at line 118 of file Tensor2DI.H.
Cmpt & xy () inline
Definition at line 124 of file Tensor2DI.H.
Cmpt & yx () inline
Definition at line 130 of file Tensor2DI.H.
Cmpt & yy () inline
Definition at line 136 of file Tensor2DI.H.
Foam::Vector2D< Cmpt > cx () const inline
Extract vector for column 0.
Definition at line 156 of file Tensor2DI.H.
Foam::Vector2D< Cmpt > cy () const inline
Extract vector for column 1.
Definition at line 162 of file Tensor2DI.H.
Vector2D<Cmpt> col () const inline
Extract vector for given column.
Compile-time check of column index.
Foam::Vector2D< Cmpt > col (const direction c) const inline
Extract vector for given column (0,1).
Runtime check of column index.
Definition at line 181 of file Tensor2DI.H.
void col (const Vector2D< Cmpt > & v) inline
Set values of given column.
Compile-time check of column index.
Definition at line 226 of file Tensor2DI.H.
void col (const direction c, const Vector2D< Cmpt > & v) inline
Set values of given column (0,1)
Runtime check of column index.
Definition at line 286 of file Tensor2DI.H.
void cols (const Vector2D< Cmpt > & x, const Vector2D< Cmpt > & y) inline
Set column values.
Definition at line 262 of file Tensor2DI.H.
Foam::Vector2D< Cmpt > x () const inline
Extract vector for row 0.
Definition at line 143 of file Tensor2DI.H.
Foam::Vector2D< Cmpt > y () const inline
Extract vector for row 1.
Definition at line 149 of file Tensor2DI.H.
Vector2D<Cmpt> row () const inline
Extract vector for given row.
Compile-time check of row index.
Foam::Vector2D< Cmpt > row (const direction r) const inline
Extract vector for given row (0,1)
Runtime check of row index.
Definition at line 209 of file Tensor2DI.H.
void row (const Vector2D< Cmpt > & v) inline
Set values of given row.
Compile-time check of row index.
Definition at line 245 of file Tensor2DI.H.
void row (const direction r, const Vector2D< Cmpt > & v) inline
Set values of given row (0,1)
Runtime check of row index.
Definition at line 305 of file Tensor2DI.H.
void rows (const Vector2D< Cmpt > & x, const Vector2D< Cmpt > & y) inline
Set row values.
Definition at line 274 of file Tensor2DI.H.
Foam::Vector2D< Cmpt > diag () const inline
Extract the diagonal as a vector.
Definition at line 323 of file Tensor2DI.H.
void diag (const Vector2D< Cmpt > & v) inline
Set values of the diagonal.
Definition at line 330 of file Tensor2DI.H.
Foam::Tensor2D< Cmpt > T () const inline
Return transpose.
Definition at line 339 of file Tensor2DI.H.
Foam::Tensor2D< Cmpt > inner (const Tensor2D< Cmpt > & t2) const inline
Inner-product of this with another Tensor2D.
Definition at line 351 of file Tensor2DI.H.
Referenced by Foam::operator&().
Foam::Tensor2D< Cmpt > schur (const Tensor2D< Cmpt > & t2) const inline
Schur-product of this with another Tensor2D.
Definition at line 368 of file Tensor2DI.H.
void operator= (const SymmTensor2D< Cmpt > & st) inline
Copy assign from SymmTensor2D.
Definition at line 383 of file Tensor2DI.H.
void operator= (const SphericalTensor2D< Cmpt > & st) inline
Copy assign from SphericalTensor2D.
Definition at line 391 of file Tensor2DI.H.
References SymmTensor2D< Cmpt >::xx(), SymmTensor2D< Cmpt >::xy(), and SymmTensor2D< Cmpt >::yy().
Vector2D<Cmpt> vectorComponent (const direction cmpt) const inline
Deprecated(2018-12) Return vector for given row (0,1)
Deprecated:
(2018-12) use row() method
Definition at line 302 of file Tensor2D.H.
Foam::Vector2D<Cmpt> col () const inline
Definition at line 170 of file Tensor2DI.H.
Foam::Vector2D<Cmpt> row () const inline
Definition at line 198 of file Tensor2DI.H.
Member Data Documentation
constexpr direction rank = 2 static
Rank of Tensor2D is 2.
Definition at line 73 of file Tensor2D.H.
const Foam::tensor2D I static
Definition at line 78 of file Tensor2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Tensor2D/Tensor2D.H
src/OpenFOAM/primitives/Tensor2D/tensor2D/tensor2D.C
src/OpenFOAM/primitives/Tensor2D/Tensor2DI.H