OpenFOAM: PointEdgeWave< Type, TrackingData > Class Template Reference
PointEdgeWave< Type, TrackingData > Class Template Reference
Wave propagation of information through grid. Every iteration information goes through one layer of edges.
Public Member Functions
PointEdgeWave (const polyMesh &mesh, const labelList &initialPoints, const List< Type > &initialPointsInfo, UList< Type > &allPointInfo, UList< Type > &allEdgeInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh, list of changed points with the Type.
PointEdgeWave (const polyMesh &mesh, UList< Type > &allPointInfo, UList< Type > &allEdgeInfo, TrackingData &td=dummyTrackData_)
Construct from mesh. Use setPointInfo and iterate() to do.
~PointEdgeWave ()
Destructor.
UList< Type > & allPointInfo () const
Access allPointInfo.
UList< Type > & allEdgeInfo () const
Access allEdgeInfo.
const TrackingData & data () const
Additional data to be passed into container.
label nUnvisitedEdges () const
Number of unvisited edges, i.e. edges that were not (yet)
label nUnvisitedPoints () const
void setPointInfo (const labelList &changedPoints, const List< Type > &changedPointsInfo)
Copy initial data into allPointInfo_.
label pointToEdge ()
Propagate from point to edge. Returns total number of edges.
label edgeToPoint ()
Propagate from edge to point. Returns total number of points.
label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
template<class PatchType >
Foam::label countPatchType () const
Static Public Member Functions
static scalar propagationTol ()
Access to tolerance.
static void setPropagationTol (const scalar tol)
Change tolerance.
Detailed Description
template<class Type, class TrackingData = int>
class Foam::PointEdgeWave< Type, TrackingData >
Wave propagation of information through grid. Every iteration information goes through one layer of edges.
Templated on information that is transferred.
Handles parallel and cyclics. Only parallel reasonably tested. Cyclics hardly tested.
Note: whether to propagate depends on the return value of Type::update which returns true (i.e. propagate) if the value changes by more than a certain tolerance.
Note: parallel is done in two steps:
transfer patch points in offset notation, i.e. every patch point is denoted by a patchface label and an index in this face. Receiving end uses that fact that f[0] is shared and order is reversed.
do all non-local shared points by means of reduce of data on them.
Note: cyclics is with offset in patchface as well. Patch is divided into two sub patches and the point-point addressing is never explicitly calculated but instead use is made of the face-face correspondence. (it probably is more efficient to calculate a point-point correspondence at the start and then reuse this; task to be done)
Source files
PointEdgeWave.H
PointEdgeWave.C
Definition at line 83 of file PointEdgeWave.H.
Constructor & Destructor Documentation
PointEdgeWave (const polyMesh & mesh, const labelList & initialPoints, const List< Type > & initialPointsInfo, UList< Type > & allPointInfo, UList< Type > & allEdgeInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh, list of changed points with the Type.
for these points. Gets work arrays to operate on, one of size number of mesh points, the other number of mesh edges. Iterates until nothing changes or maxIter reached. (maxIter can be 0)
Definition at line 606 of file PointEdgeWave.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::Info, iter, PointEdgeWave< Type, TrackingData >::iterate(), primitiveMesh::nEdges(), primitiveMesh::nPoints(), Foam::returnReduce(), PointEdgeWave< Type, TrackingData >::setPointInfo(), and UList< T >::size().
PointEdgeWave (const polyMesh & mesh, UList< Type > & allPointInfo, UList< Type > & allEdgeInfo, TrackingData & td = dummyTrackData_)
Construct from mesh. Use setPointInfo and iterate() to do.
actual calculation
Definition at line 679 of file PointEdgeWave.C.
~PointEdgeWave ()
Destructor.
Definition at line 706 of file PointEdgeWave.C.
Member Function Documentation
static scalar propagationTol () inline static
Access to tolerance.
Definition at line 279 of file PointEdgeWave.H.
static void setPropagationTol (const scalar tol) inline static
Change tolerance.
Definition at line 287 of file PointEdgeWave.H.
UList<Type>& allPointInfo () const inline
Access allPointInfo.
Definition at line 339 of file PointEdgeWave.H.
UList<Type>& allEdgeInfo () const inline
Access allEdgeInfo.
Definition at line 347 of file PointEdgeWave.H.
References i.
const TrackingData& data () const inline
Additional data to be passed into container.
Definition at line 355 of file PointEdgeWave.H.
Foam::label nUnvisitedEdges () const
Number of unvisited edges, i.e. edges that were not (yet)
reached from walking across mesh. This can happen from
not enough iterations done
a disconnected mesh
a mesh without walls in it
Definition at line 721 of file PointEdgeWave.C.
Foam::label nUnvisitedPoints () const
Definition at line 714 of file PointEdgeWave.C.
void setPointInfo (const labelList & changedPoints, const List< Type > & changedPointsInfo)
Copy initial data into allPointInfo_.
Definition at line 730 of file PointEdgeWave.C.
References forAll.
Referenced by PointEdgeWave< Type, TrackingData >::PointEdgeWave().
Foam::label pointToEdge ()
Propagate from point to edge. Returns total number of edges.
(over all processors) changed.
Definition at line 842 of file PointEdgeWave.C.
Foam::label edgeToPoint ()
Propagate from edge to point. Returns total number of points.
(over all processors) changed.
Definition at line 766 of file PointEdgeWave.C.
Foam::label iterate (const label maxIter)
Iterate until no changes or maxIter reached. Returns actual.
number of iterations.
Definition at line 911 of file PointEdgeWave.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::Info, iter, Foam::nl, nPoints, UPstream::parRun(), and Foam::returnReduce().
Referenced by PointEdgeWave< Type, TrackingData >::PointEdgeWave(), and medialAxisMeshMover::~medialAxisMeshMover().
Foam::label countPatchType () const
Definition at line 290 of file PointEdgeWave.C.
References forAll, and nPatches.
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PointEdgeWave/PointEdgeWave.H
src/meshTools/algorithms/PointEdgeWave/PointEdgeWave.C