OpenFOAM: surfZone Class Reference
surfZone Class Reference
A surface zone on a MeshedSurface.
Public Member Functions
ClassName ("surfZone")
Runtime type information.
surfZone ()
Construct null with zero start, size, index.
surfZone (const word &name, const label size)
Construct with name, size. With zero start, index.
surfZone (const word &name, const label size, const label start, const label index, const word &geometricType=word::null)
Construct from components.
surfZone (Istream &is, const label index)
Construct from Istream.
surfZone (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
surfZone (const surfZone &)
Construct as copy.
surfZone (const surfZone &, const label index)
Construct from another zone, resetting the index.
autoPtr< surfZone > clone () const
Return clone.
label start () const
Return start label of this zone in the face list.
label & start ()
Return start label of this zone in the face list.
label size () const
Return size of this zone in the face list.
label & size ()
Return size of this zone in the face list.
labelRange range () const
Return start/size range of this zone.
void write (Ostream &) const
Write.
void writeDict (Ostream &) const
Write dictionary.
bool operator!= (const surfZone &) const
bool operator== (const surfZone &) const
compare.
Public Member Functions inherited from surfZoneIdentifier
surfZoneIdentifier ()
Construct null, with index zero.
surfZoneIdentifier (const label index)
Construct null with specified index.
surfZoneIdentifier (const word &name, const label index, const word &geometricType=word::null)
Construct from components.
surfZoneIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
surfZoneIdentifier (const surfZoneIdentifier &p, const label index)
Copy construct from another zone identifier, resetting the index.
virtual ~surfZoneIdentifier ()=default
Destructor.
const word & name () const
Return name.
word & name ()
Return name for modification.
const word & geometricType () const
Return the geometric type of the patch/zone.
word & geometricType ()
Return the geometric type of the patch/zone for modification.
label index () const
Return the index of this patch/zone in the surface mesh.
label & index ()
Return the index of this patch/zone for modification.
void write (Ostream &os) const
Write identifier as a dictionary.
Static Public Member Functions
static autoPtr< surfZone > New (Istream &is)
Friends
Istream & operator>> (Istream &, surfZone &)
Ostream & operator<< (Ostream &, const surfZone &)
Additional Inherited Members
Static Public Attributes inherited from surfZoneIdentifier
static const word emptyType = "empty"
The name for an 'empty' type.
Detailed Description
A surface zone on a MeshedSurface.
Similar in concept to a faceZone, but the face list is contiguous.
Source files
surfZone.H
surfZone.C
Definition at line 61 of file surfZone.H.
Constructor & Destructor Documentation
surfZone ()
Construct null with zero start, size, index.
Definition at line 36 of file surfZone.C.
References Foam::defineTypeNameAndDebug().
surfZone (const word & name, const label size)
Construct with name, size. With zero start, index.
Definition at line 44 of file surfZone.C.
surfZone (const word & name, const label size, const label start, const label index, const word & geometricType = word::null)
Construct from components.
Definition at line 53 of file surfZone.C.
surfZone (Istream & is, const label index)
Construct from Istream.
Definition at line 67 of file surfZone.C.
surfZone (const word & name, const dictionary & dict, const label index)
Construct from dictionary.
Definition at line 81 of file surfZone.C.
surfZone (const surfZone & zone)
Construct as copy.
Definition at line 93 of file surfZone.C.
surfZone (const surfZone & zone, const label index)
Construct from another zone, resetting the index.
Definition at line 101 of file surfZone.C.
Member Function Documentation
ClassName ("surfZone")
Runtime type information.
autoPtr<surfZone> clone () const inline
Return clone.
Definition at line 138 of file surfZone.H.
static autoPtr<surfZone> New (Istream & is) inline static
Definition at line 144 of file surfZone.H.
label start () const inline
Return start label of this zone in the face list.
Definition at line 158 of file surfZone.H.
Referenced by discreteSurface::setZoneMap(), and sampledTriSurfaceMesh::setZoneMap().
label& start () inline
Return start label of this zone in the face list.
Definition at line 166 of file surfZone.H.
label size () const inline
Return size of this zone in the face list.
Definition at line 174 of file surfZone.H.
Referenced by discreteSurface::setZoneMap(), and sampledTriSurfaceMesh::setZoneMap().
label& size () inline
Return size of this zone in the face list.
Definition at line 182 of file surfZone.H.
labelRange range () const inline
Return start/size range of this zone.
Definition at line 190 of file surfZone.H.
References surfZone::range().
Referenced by surfZone::range().
void write (Ostream & os) const
Write.
Definition at line 111 of file surfZone.C.
void writeDict (Ostream & os) const
Write dictionary.
Definition at line 117 of file surfZone.C.
bool operator!= (const surfZone & rhs) const
Definition at line 131 of file surfZone.C.
bool operator== (const surfZone & rhs) const
compare.
Definition at line 137 of file surfZone.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , surfZone &) friend
Ostream& operator<< (Ostream & , const surfZone &) friend
The documentation for this class was generated from the following files:
src/surfMesh/surfZone/surfZone.H
src/surfMesh/surfZone/surfZone.C