OpenFOAM: blendedSchemeBase< Type > Class Template Reference
blendedSchemeBase< Type > Class Template Reference abstract
Base class for blended schemes to provide access to the blending factor surface field.
Public Member Functions
blendedSchemeBase ()
Constructor.
virtual ~blendedSchemeBase ()=default
Destructor.
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const =0
Return the face-based blending factor.
Detailed Description
template<class Type>
class Foam::blendedSchemeBase< Type >
Base class for blended schemes to provide access to the blending factor surface field.
Definition at line 49 of file blendedSchemeBase.H.
Constructor & Destructor Documentation
blendedSchemeBase () inline
Constructor.
Definition at line 59 of file blendedSchemeBase.H.
References blendedSchemeBase< Type >::blendingFactor(), and blendedSchemeBase< Type >::~blendedSchemeBase().
virtual ~blendedSchemeBase () virtual default
Destructor.
Referenced by blendedSchemeBase< Type >::blendedSchemeBase().
Member Function Documentation
virtual tmp<surfaceScalarField> blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const pure virtual
Return the face-based blending factor.
Implemented in DEShybrid< Type >, cellCoBlended< Type >, CoBlended< Type >, localBlended< Type >, and blended< Type >.
Referenced by blendedSchemeBase< Type >::blendedSchemeBase().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/blendedSchemeBase/blendedSchemeBase.H