OpenFOAM: foamVtkMeshMaps Class Reference
foamVtkMeshMaps Class Reference
Bookkeeping for mesh subsetting and/or polyhedral cell decomposition. Although the main use case is for handling vtk meshes, it is not specific to VTK alone.
Public Member Functions
foamVtkMeshMaps (const label size=0)
Construct null.
~foamVtkMeshMaps ()=default
Destructor.
const labelList & cellMap () const
Original cell ids for all cells (regular and decomposed).
const labelList & pointMap () const
Point labels for subsetted meshes.
const labelList & additionalIds () const
Any additional (user) labels.
void clear ()
Clear.
void renumberCells (const labelUList &mapping)
Renumber cell ids (cellMap and additionalIds) to account for.
void renumberPoints (const labelUList &mapping)
Renumber point ids (pointMap) to account for subset meshes.
DynamicList< label > & cellMap ()
Original cell ids for all cells (regular and decomposed).
DynamicList< label > & pointMap ()
Point labels for subsetted meshes.
DynamicList< label > & additionalIds ()
Any additional (user) labels.
Detailed Description
Bookkeeping for mesh subsetting and/or polyhedral cell decomposition. Although the main use case is for handling vtk meshes, it is not specific to VTK alone.
The cellMap is a local-to-global lookup for normal and decomposed cells. The pointMap is an optional local-to-global lookup for point ids. The additional ids is typically used to store the cell-centre labels for additional points of decomposed cells
Source files
foamVtkMeshMaps.H
foamVtkMeshMapsI.H
Definition at line 53 of file foamVtkMeshMaps.H.
Constructor & Destructor Documentation
foamVtkMeshMaps (const label size = 0) inline explicit
Construct null.
Definition at line 25 of file foamVtkMeshMapsI.H.
~foamVtkMeshMaps () default
Destructor.
Member Function Documentation
const Foam::labelList & cellMap () const inline
Original cell ids for all cells (regular and decomposed).
A regular mesh comprising only primitive cell types, this will just be an identity list. However, for subsetted meshes and decomposed cells this becomes a useful means of mapping from the original mesh.
Definition at line 44 of file foamVtkMeshMapsI.H.
Referenced by vtuAdaptor::convertField().
const Foam::labelList & pointMap () const inline
Point labels for subsetted meshes.
Definition at line 58 of file foamVtkMeshMapsI.H.
const Foam::labelList & additionalIds () const inline
Any additional (user) labels.
Eg, cell-centre labels for additional points of decomposed cells
Definition at line 72 of file foamVtkMeshMapsI.H.
Referenced by vtuAdaptor::points().
void clear () inline
Clear.
Definition at line 35 of file foamVtkMeshMapsI.H.
void renumberCells (const labelUList & mapping)
Renumber cell ids (cellMap and additionalIds) to account for.
subset meshes
Definition at line 26 of file foamVtkMeshMaps.C.
void renumberPoints (const labelUList & mapping)
Renumber point ids (pointMap) to account for subset meshes.
Definition at line 33 of file foamVtkMeshMaps.C.
References Foam::inplaceRenumber().
Foam::DynamicList< Foam::label > & cellMap () inline
Original cell ids for all cells (regular and decomposed).
For a regular mesh comprising only primitive cell types, this will simply be an identity list. However, for subsetted meshes and decomposed cells this becomes a useful means of mapping from the original mesh.
Definition at line 51 of file foamVtkMeshMapsI.H.
Foam::DynamicList< Foam::label > & pointMap () inline
Point labels for subsetted meshes.
Definition at line 65 of file foamVtkMeshMapsI.H.
Foam::DynamicList< Foam::label > & additionalIds () inline
Any additional (user) labels.
Eg, cell-centre labels for additional points of decomposed cells
Definition at line 79 of file foamVtkMeshMapsI.H.
The documentation for this class was generated from the following files:
src/fileFormats/vtk/part/foamVtkMeshMaps.H
src/fileFormats/vtk/part/foamVtkMeshMaps.C
src/fileFormats/vtk/part/foamVtkMeshMapsI.H