OpenFOAM: gaussLaplacianScheme< Type, GType > Class Template Reference
gaussLaplacianScheme< Type, GType > Class Template Reference
Laplacian schemes
Basic second-order laplacian using face-gradients and Gauss' theorem.
Public Member Functions
TypeName ("Gauss")
Runtime type information.
gaussLaplacianScheme (const fvMesh &mesh)
Construct null.
gaussLaplacianScheme (const fvMesh &mesh, Istream &is)
Construct from Istream.
gaussLaplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType >> &igs, const tmp< snGradScheme< Type >> &sngs)
Construct from mesh, interpolation and snGradScheme schemes.
virtual ~gaussLaplacianScheme ()=default
Destructor.
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< scalar, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< scalar,
fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< scalar, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< vector, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< vector,
fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< vector, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
template<>
tmp< GeometricField
< sphericalTensor,
fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< symmTensor, fvPatchField, volMesh > &)
template<>
tmp< GeometricField
< symmTensor, fvPatchField,
volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< symmTensor, fvPatchField, volMesh > &)
template<>
tmp< fvMatrix< tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< tensor, fvPatchField, volMesh > &)
template<>
tmp< GeometricField< tensor,
fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &, const GeometricField< tensor, fvPatchField, volMesh > &)
template<>
Foam::tmp< Foam::fvMatrix
< Foam::scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< scalar, fvPatchField, volMesh > &vf)
template<>
Foam::tmp
< Foam::GeometricField
< Foam::scalar,
Foam::fvPatchField,
Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< scalar, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix
< Foam::vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< vector, fvPatchField, volMesh > &vf)
template<>
Foam::tmp
< Foam::GeometricField
< Foam::vector,
Foam::fvPatchField,
Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< vector, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix
< Foam::sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp
< Foam::GeometricField
< Foam::sphericalTensor,
Foam::fvPatchField,
Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix
< Foam::symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< symmTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp
< Foam::GeometricField
< Foam::symmTensor,
Foam::fvPatchField,
Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< symmTensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp< Foam::fvMatrix
< Foam::tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< tensor, fvPatchField, volMesh > &vf)
template<>
Foam::tmp
< Foam::GeometricField
< Foam::tensor,
Foam::fvPatchField,
Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > &gamma, const GeometricField< tensor, fvPatchField, volMesh > &vf)
Public Member Functions inherited from laplacianScheme< Type, GType >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const fvMesh &mesh)
Construct from mesh.
laplacianScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
laplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType >> &igs, const tmp< snGradScheme< Type >> &sngs)
Construct from mesh, interpolation and snGradScheme schemes.
virtual ~laplacianScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< fvMatrix< Type > > fvmLaplacianUncorrected (const surfaceScalarField &gammaMagSf, const surfaceScalarField &deltaCoeffs, const GeometricField< Type, fvPatchField, volMesh > &)
Static Public Member Functions inherited from laplacianScheme< Type, GType >
static tmp< laplacianScheme
< Type, GType > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new laplacianScheme created on freestore.
Additional Inherited Members
Protected Attributes inherited from laplacianScheme< Type, GType >
const fvMesh & mesh_
tmp
< surfaceInterpolationScheme
< GType > > tinterpGammaScheme_
tmp< snGradScheme< Type > > tsnGradScheme_
Detailed Description
template<class Type, class GType>
class Foam::fv::gaussLaplacianScheme< Type, GType >
Basic second-order laplacian using face-gradients and Gauss' theorem.
Source files
gaussLaplacianScheme.H
gaussLaplacianScheme.C
Definition at line 56 of file gaussLaplacianScheme.H.
Constructor & Destructor Documentation
gaussLaplacianScheme (const fvMesh & mesh) inline
Construct null.
Definition at line 92 of file gaussLaplacianScheme.H.
gaussLaplacianScheme (const fvMesh & mesh, Istream & is) inline
Construct from Istream.
Definition at line 100 of file gaussLaplacianScheme.H.
gaussLaplacianScheme (const fvMesh & mesh, const tmp< surfaceInterpolationScheme< GType >> & igs, const tmp< snGradScheme< Type >> & sngs) inline
Construct from mesh, interpolation and snGradScheme schemes.
Definition at line 109 of file gaussLaplacianScheme.H.
virtual ~gaussLaplacianScheme () virtual default
Destructor.
Member Function Documentation
TypeName ("Gauss")
Runtime type information.
tmp< fvMatrix< Type > > fvmLaplacianUncorrected (const surfaceScalarField & gammaMagSf, const surfaceScalarField & deltaCoeffs, const GeometricField< Type, fvPatchField, volMesh > & vf) static
Definition at line 42 of file gaussLaplacianScheme.C.
References fvMatrix< Type >::boundaryCoeffs(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::component(), fvPatchField< Type >::coupled(), surfaceInterpolation::deltaCoeffs(), DimensionedField< Type, GeoMesh >::dimensions(), Foam::fvc::dotInterpolate(), forAll, Foam::fvc::grad(), fvPatchField< Type >::gradientBoundaryCoeffs(), fvPatchField< Type >::gradientInternalCoeffs(), IOobject::instance(), fvMatrix< Type >::internalCoeffs(), mesh, IOobject::name(), lduMatrix::negSumDiag(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::oriented(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), tmp< T >::ref(), and lduMatrix::upper().
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements laplacianScheme< Type, GType >.
Definition at line 133 of file gaussLaplacianScheme.C.
References Foam::fvc::div(), fvMesh::magSf(), mesh, IOobject::name(), tmp< T >::ref(), and Foam::fvc::snGrad().
tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements laplacianScheme< Type, GType >.
Definition at line 153 of file gaussLaplacianScheme.C.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements laplacianScheme< Type, GType >.
Definition at line 200 of file gaussLaplacianScheme.C.
tmp< fvMatrix< scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< scalar, fvPatchField, volMesh > &)
tmp< GeometricField< scalar, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< scalar, fvPatchField, volMesh > &)
tmp< fvMatrix< vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< vector, fvPatchField, volMesh > &)
tmp< GeometricField< vector, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< vector, fvPatchField, volMesh > &)
tmp< fvMatrix< sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
tmp< GeometricField< sphericalTensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< sphericalTensor, fvPatchField, volMesh > &)
tmp< fvMatrix< symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< symmTensor, fvPatchField, volMesh > &)
tmp< GeometricField< symmTensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< symmTensor, fvPatchField, volMesh > &)
tmp< fvMatrix< tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< tensor, fvPatchField, volMesh > &)
tmp< GeometricField< tensor, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & , const GeometricField< tensor, fvPatchField, volMesh > &)
Foam::tmp< Foam::fvMatrix< Foam::scalar > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< scalar, fvPatchField, volMesh > & vf)
Definition at line 109 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::GeometricField< Foam::scalar, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< scalar, fvPatchField, volMesh > & vf)
Definition at line 109 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::fvMatrix< Foam::vector > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< vector, fvPatchField, volMesh > & vf)
Definition at line 110 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::GeometricField< Foam::vector, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< vector, fvPatchField, volMesh > & vf)
Definition at line 110 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::fvMatrix< Foam::sphericalTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > & vf)
Definition at line 111 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::GeometricField< Foam::sphericalTensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< sphericalTensor, fvPatchField, volMesh > & vf)
Definition at line 111 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::fvMatrix< Foam::symmTensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< symmTensor, fvPatchField, volMesh > & vf)
Definition at line 112 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::GeometricField< Foam::symmTensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< symmTensor, fvPatchField, volMesh > & vf)
Definition at line 112 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::fvMatrix< Foam::tensor > > fvmLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< tensor, fvPatchField, volMesh > & vf)
Definition at line 113 of file gaussLaplacianSchemes.C.
Foam::tmp< Foam::GeometricField< Foam::tensor, Foam::fvPatchField, Foam::volMesh > > fvcLaplacian (const GeometricField< scalar, fvsPatchField, surfaceMesh > & gamma, const GeometricField< tensor, fvPatchField, volMesh > & vf)
Definition at line 113 of file gaussLaplacianSchemes.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/laplacianSchemes/gaussLaplacianScheme/gaussLaplacianScheme.H
src/finiteVolume/finiteVolume/laplacianSchemes/gaussLaplacianScheme/gaussLaplacianScheme.C