OpenFOAM: RASModel< BasicTurbulenceModel > Class Template Reference
RASModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for RAS turbulence models.
Public Types
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()=default
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Static Public Member Functions
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Protected Member Functions
virtual void printCoeffs (const word &type)
Print model coefficients.
RASModel (const RASModel &)=delete
No copy construct.
void operator= (const RASModel &)=delete
No copy assignment.
Protected Attributes
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModel< BasicTurbulenceModel >
Templated abstract base class for RAS turbulence models.
Source files
RASModel.H
RASModel.C
Definition at line 47 of file RASModel.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 112 of file RASModel.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 113 of file RASModel.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 114 of file RASModel.H.
Constructor & Destructor Documentation
RASModel (const RASModel< BasicTurbulenceModel > &) protected delete
No copy construct.
RASModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 40 of file RASModel.C.
virtual ~RASModel () virtual default
Destructor.
Member Function Documentation
void printCoeffs (const word & type) protected virtual
Print model coefficients.
Definition at line 27 of file RASModel.C.
References Foam::endl(), and Foam::Info.
void operator= (const RASModel< BasicTurbulenceModel > &) protected delete
No copy assignment.
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , RASModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
Foam::autoPtr< Foam::RASModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected RAS model.
Definition at line 112 of file RASModel.C.
References Foam::constant::atomic::alpha, TimePaths::constant(), IOobject::db(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), IOobject::group(), IOobject::groupName(), Foam::Info, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, phi, rho, dictionary::subDict(), IOobject::time(), and U.
bool read () virtual
Read model coefficients if they have changed.
Reimplemented in kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, kOmegaSSTLM< BasicTurbulenceModel >, mixtureKEpsilon< BasicTurbulenceModel >, kEpsilonPhitF< BasicTurbulenceModel >, v2f< BasicTurbulenceModel >, kineticTheoryModel, kineticTheoryModel, kOmegaSSTSato< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, kEpsilonLopesdaCosta< BasicTurbulenceModel >, kOmegaSSTSAS< BasicTurbulenceModel >, SSG< BasicTurbulenceModel >, LaheyKEpsilon< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, kEpsilon< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, realizableKE< BasicTurbulenceModel >, phasePressureModel, continuousGasKEpsilon< BasicTurbulenceModel >, phasePressureModel, buoyantKEpsilon< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, PDRkEpsilon, ReynoldsStress< RASModel< BasicTurbulenceModel > >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, eddyViscosity< RASModel< BasicTurbulenceModel > >, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, and linearViscousStress< RASModel< BasicTurbulenceModel > >.
Definition at line 164 of file RASModel.C.
const dimensionedScalar& kMin () const inline
Return the lower allowable limit for k (default: SMALL)
Definition at line 197 of file RASModel.H.
const dimensionedScalar& epsilonMin () const inline
Return the lower allowable limit for epsilon (default: SMALL)
Definition at line 205 of file RASModel.H.
const dimensionedScalar& omegaMin () const inline
Return the lower allowable limit for omega (default: SMALL)
Definition at line 213 of file RASModel.H.
dimensionedScalar& kMin () inline
Allow kMin to be changed.
Definition at line 221 of file RASModel.H.
dimensionedScalar& epsilonMin () inline
Allow epsilonMin to be changed.
Definition at line 229 of file RASModel.H.
dimensionedScalar& omegaMin () inline
Allow omegaMin to be changed.
Definition at line 237 of file RASModel.H.
virtual const dictionary& coeffDict () const inline virtual
Const access to the coefficients dictionary.
Definition at line 245 of file RASModel.H.
virtual tmp<volScalarField> nuEff () const inline virtual
Return the effective viscosity.
Reimplemented in kineticTheoryModel, kineticTheoryModel, continuousGasKEpsilon< BasicTurbulenceModel >, phasePressureModel, and phasePressureModel.
Definition at line 254 of file RASModel.H.
virtual tmp<scalarField> nuEff (const label patchi) const inline virtual
Return the effective viscosity on patch.
Reimplemented in kineticTheoryModel, kineticTheoryModel, phasePressureModel, and phasePressureModel.
Definition at line 269 of file RASModel.H.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented in kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >, kOmegaSSTLM< BasicTurbulenceModel >, kEpsilonPhitF< BasicTurbulenceModel >, v2f< BasicTurbulenceModel >, kineticTheoryModel, kineticTheoryModel, mixtureKEpsilon< BasicTurbulenceModel >, kEpsilonLopesdaCosta< BasicTurbulenceModel >, LRR< BasicTurbulenceModel >, LaunderSharmaKE< BasicTurbulenceModel >, RNGkEpsilon< BasicTurbulenceModel >, phasePressureModel, kEpsilon< BasicTurbulenceModel >, SpalartAllmaras< BasicTurbulenceModel >, SSG< BasicTurbulenceModel >, kEpsilon< EddyDiffusivity< compressible::turbulenceModel > >, phasePressureModel, kOmegaSSTSato< BasicTurbulenceModel >, kOmega< BasicTurbulenceModel >, realizableKE< BasicTurbulenceModel >, ReynoldsStress< RASModel< BasicTurbulenceModel > >, LaheyKEpsilon< BasicTurbulenceModel >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, eddyViscosity< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, eddyViscosity< RASModel< BasicTurbulenceModel > >, PDRkEpsilon, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, linearViscousStress< RASModel< EddyDiffusivity< compressible::turbulenceModel > > >, and linearViscousStress< RASModel< BasicTurbulenceModel > >.
Definition at line 185 of file RASModel.C.
Member Data Documentation
dictionary RASDict_ protected
RAS coefficients dictionary.
Definition at line 59 of file RASModel.H.
Switch turbulence_ protected
Turbulence on/off flag.
Definition at line 64 of file RASModel.H.
Switch printCoeffs_ protected
Flag to print the model coeffs at run-time.
Definition at line 69 of file RASModel.H.
dictionary coeffDict_ protected
Model coefficients dictionary.
Definition at line 74 of file RASModel.H.
Referenced by RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >::epsilonMin().
dimensionedScalar kMin_ protected
Lower limit of k.
Definition at line 79 of file RASModel.H.
dimensionedScalar epsilonMin_ protected
Lower limit of epsilon.
Definition at line 84 of file RASModel.H.
dimensionedScalar omegaMin_ protected
Lower limit for omega.
Definition at line 89 of file RASModel.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/RASModel/RASModel.H
src/TurbulenceModels/turbulenceModels/RAS/RASModel/RASModel.C