OpenFOAM: lduInterfaceField Class Reference
lduInterfaceField Class Reference abstract
An abstract base class for implicitly-coupled interface fields e.g. processor and cyclic patch fields.
Public Member Functions
TypeName ("lduInterfaceField")
Runtime type information.
lduInterfaceField (const lduInterface &patch)
Construct given coupled patch.
virtual ~lduInterfaceField ()=default
Destructor.
const lduInterface & interface () const
Return the interface.
virtual const word & interfaceFieldType () const
Return the interface type.
bool updatedMatrix () const
Whether matrix has been updated.
bool & updatedMatrix ()
Whether matrix has been updated.
virtual bool ready () const
Is all data available.
virtual void initInterfaceMatrixUpdate (solveScalarField &result, const bool add, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const
Initialise neighbour matrix update. Add/subtract coupled contributions to matrix.
virtual void updateInterfaceMatrix (solveScalarField &result, const bool add, const solveScalarField &psiInternal, const scalarField &coeffs, const direction cmpt, const Pstream::commsTypes commsType) const =0
Update result field based on interface functionality. Add/subtract coupled contributions to matrix.
template<class Type >
void addToInternalField (Field< Type > &result, const bool add, const scalarField &coeffs, const Field< Type > &vals) const
Add/subtract weighted contributions to internal field.
Detailed Description
An abstract base class for implicitly-coupled interface fields e.g. processor and cyclic patch fields.
Source files
lduInterfaceField.H
lduInterfaceField.C
Definition at line 54 of file lduInterfaceField.H.
Constructor & Destructor Documentation
lduInterfaceField (const lduInterface & patch) inline explicit
Construct given coupled patch.
Definition at line 97 of file lduInterfaceField.H.
virtual ~lduInterfaceField () virtual default
Destructor.
Member Function Documentation
TypeName ("lduInterfaceField")
Runtime type information.
const lduInterface& interface () const inline
Return the interface.
Definition at line 117 of file lduInterfaceField.H.
Referenced by lduInterfaceField::addToInternalField(), and procLduInterface::procLduInterface().
virtual const word& interfaceFieldType () const inline virtual
Return the interface type.
Reimplemented in jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
Definition at line 125 of file lduInterfaceField.H.
Referenced by GAMGInterfaceField::New().
bool updatedMatrix () const inline
Whether matrix has been updated.
Definition at line 136 of file lduInterfaceField.H.
bool& updatedMatrix () inline
Whether matrix has been updated.
Definition at line 144 of file lduInterfaceField.H.
virtual bool ready () const inline virtual
Is all data available.
Reimplemented in calculatedProcessorFvPatchField< Type >, and processorFvPatchField< Type >.
Definition at line 152 of file lduInterfaceField.H.
virtual void initInterfaceMatrixUpdate (solveScalarField & result, const bool add, const solveScalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const inline virtual
Initialise neighbour matrix update. Add/subtract coupled contributions to matrix.
Reimplemented in calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, processorFaPatchField< Type >, processorGAMGInterfaceField, calculatedProcessorGAMGInterfaceField, processorFaPatchField< Type >, and processorFaPatchField< Type >.
Definition at line 162 of file lduInterfaceField.H.
virtual void updateInterfaceMatrix (solveScalarField & result, const bool add, const solveScalarField & psiInternal, const scalarField & coeffs, const direction cmpt, const Pstream::commsTypes commsType) const pure virtual
Update result field based on interface functionality. Add/subtract coupled contributions to matrix.
Implemented in calculatedProcessorFvPatchField< Type >, processorFvPatchField< Type >, coupledFvPatchField< Type >, cyclicACMIFvPatchField< Type >, processorFaPatchField< Type >, coupledFaPatchField< Type >, cyclicAMIFvPatchField< Type >, cyclicFvPatchField< Type >, cyclicFaPatchField< Type >, jumpCyclicFvPatchField< Type >, processorGAMGInterfaceField, calculatedProcessorGAMGInterfaceField, jumpCyclicAMIFvPatchField< Type >, cyclicGAMGInterfaceField, jumpCyclicFvPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, jumpCyclicFvPatchField< Type >, cyclicACMIGAMGInterfaceField, cyclicAMIGAMGInterfaceField, jumpCyclicFvPatchField< Type >, processorFaPatchField< Type >, processorFaPatchField< Type >, jumpCyclicAMIFvPatchField< Type >, and jumpCyclicFvPatchField< Type >.
void addToInternalField (Field< Type > & result, const bool add, const scalarField & coeffs, const Field< Type > & vals) const
Add/subtract weighted contributions to internal field.
Definition at line 25 of file lduInterfaceFieldTemplates.C.
References lduInterface::faceCells(), forAll, and lduInterfaceField::interface().
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/lduInterfaceField/lduInterfaceField.H
src/OpenFOAM/matrices/lduMatrix/lduAddressing/lduInterfaceFields/lduInterfaceField/lduInterfaceFieldTemplates.C