OpenFOAM: eddy Class Reference
eddy Class Reference
Class to describe eddies for the turbulentDFSEMInletFvPatchVectorField boundary condition.
Public Member Functions
eddy ()
Construct null.
eddy (Istream &is)
Construct from Istream.
eddy (const label patchFaceI, const point &position0, const scalar x, const scalar sigmaX, const symmTensor &R, Random &rndGen)
Construct from components.
eddy (const eddy &e)
Construct copy.
label patchFaceI () const
Return the patch face index that spawned the eddy.
const point & position0 () const
Return the reference position.
scalar x () const
Return the distance from the reference position.
const vector & sigma () const
Return the lLength scales in 3-D space.
const vector & alpha () const
Return the time-averaged intensity.
const tensor & Rpg () const
Return the coordinate system transformation from local.
scalar c1 () const
Return the model coefficient c1.
point position (const vector &n) const
Return the eddy position.
label dir1 () const
Return the index of the streamwise direction.
vector epsilon (Random &rndGen) const
Return random vector of -1 and 1's.
scalar volume () const
Volume.
void move (const scalar dx)
Move the eddy.
boundBox bounds (const bool global=true) const
Eddy bounds.
vector uDash (const point &xp, const vector &n) const
Return the fluctuating velocity contribution at local point xp.
void writeCentreOBJ (const vector &n, Ostream &os) const
Write the eddy centre in OBJ format.
label writeSurfaceOBJ (const label pointOffset, const vector &n, Ostream &os) const
Write the eddy surface in OBJ format.
void operator= (const eddy &e)
Static Public Attributes
static int debug = 0
Friends
bool operator== (const eddy &a, const eddy &b)
bool operator!= (const eddy &a, const eddy &b)
Istream & operator>> (Istream &is, eddy &e)
Ostream & operator<< (Ostream &os, const eddy &e)
Detailed Description
Class to describe eddies for the turbulentDFSEMInletFvPatchVectorField boundary condition.
Source files
eddy.H
eddy.C
eddyI.H
eddyIO.C
Definition at line 65 of file eddy.H.
Constructor & Destructor Documentation
eddy ()
Construct null.
Definition at line 108 of file eddy.C.
eddy (Istream & is)
Construct from Istream.
Definition at line 27 of file eddyIO.C.
eddy (const label patchFaceI, const point & position0, const scalar x, const scalar sigmaX, const symmTensor & R, Random & rndGen)
Construct from components.
Definition at line 122 of file eddy.C.
eddy (const eddy & e)
Construct copy.
Definition at line 207 of file eddy.C.
Member Function Documentation
Foam::label patchFaceI () const inline
Return the patch face index that spawned the eddy.
Definition at line 35 of file eddyI.H.
References Random::sample01().
const Foam::point & position0 () const inline
Return the reference position.
Definition at line 41 of file eddyI.H.
Foam::scalar x () const inline
Return the distance from the reference position.
Definition at line 47 of file eddyI.H.
const Foam::vector & sigma () const inline
Return the lLength scales in 3-D space.
Definition at line 53 of file eddyI.H.
const Foam::vector & alpha () const inline
Return the time-averaged intensity.
Definition at line 59 of file eddyI.H.
const Foam::tensor & Rpg () const inline
Return the coordinate system transformation from local.
principal to global axes
Definition at line 65 of file eddyI.H.
Foam::scalar c1 () const inline
Return the model coefficient c1.
Definition at line 77 of file eddyI.H.
Foam::point position (const vector & n) const inline
Return the eddy position.
Definition at line 71 of file eddyI.H.
label dir1 () const inline
Return the index of the streamwise direction.
Foam::vector epsilon (Random & rndGen) const inline
Return random vector of -1 and 1's.
Definition at line 83 of file eddyI.H.
Foam::scalar volume () const inline
Volume.
Definition at line 89 of file eddyI.H.
void move (const scalar dx) inline
Move the eddy.
Definition at line 95 of file eddyI.H.
References Foam::cmptProduct(), and Foam::constant::mathematical::pi().
Foam::boundBox bounds (const bool global = true) const inline
Eddy bounds.
Definition at line 101 of file eddyI.H.
Foam::vector uDash (const point & xp, const vector & n) const
Return the fluctuating velocity contribution at local point xp.
Definition at line 222 of file eddy.C.
void writeCentreOBJ (const vector & n, Ostream & os) const
Write the eddy centre in OBJ format.
Definition at line 247 of file eddy.C.
Foam::label writeSurfaceOBJ (const label pointOffset, const vector & n, Ostream & os) const
Write the eddy surface in OBJ format.
Returns the number of points used to describe the eddy surface
Definition at line 258 of file eddy.C.
References Foam::nl, p, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
void operator= (const eddy & e)
Definition at line 44 of file eddyIO.C.
References IOstream::check(), and FUNCTION_NAME.
Friends And Related Function Documentation
bool operator== (const eddy & a, const eddy & b) friend
Definition at line 281 of file eddy.H.
bool operator!= (const eddy & a, const eddy & b) friend
Definition at line 294 of file eddy.H.
Istream& operator>> (Istream & is, eddy & e) friend
Ostream& operator<< (Ostream & os, const eddy & e) friend
Member Data Documentation
int debug = 0 static
Definition at line 168 of file eddy.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddy.H
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddy.C
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddyI.H
src/finiteVolume/fields/fvPatchFields/derived/turbulentDFSEMInlet/eddy/eddyIO.C