OpenFOAM: layerParameters Class Reference
layerParameters Class Reference
Simple container to keep together layer specific information.
Public Types
enum layerSpecification {
ILLEGAL, FIRST_AND_TOTAL, FIRST_AND_EXPANSION, FINAL_AND_TOTAL,
FINAL_AND_EXPANSION, TOTAL_AND_EXPANSION
}
Enumeration defining the layer specification:
Public Member Functions
layerParameters (const dictionary &dict, const polyBoundaryMesh &, const bool dryRun=false)
Construct from dictionary.
const dictionary & dict () const
const labelList & numLayers () const
How many layers to add.
bool relativeSizes () const
Are size parameters relative to inner cell size or.
const scalarField & expansionRatio () const
const scalarField & finalLayerThickness () const
Wanted thickness of the layer furthest away.
const scalarField & firstLayerThickness () const
Wanted thickness of the layer nearest to the wall.
const scalarField & thickness () const
Wanted overall thickness of all layers.
const scalarField & minThickness () const
Minimum overall thickness of cell layer. If for any reason layer.
label nLayerIter () const
Number of overall layer addition iterations.
label nRelaxedIter () const
Number of iterations after which relaxed motion rules.
scalar featureAngle () const
scalar mergePatchFacesAngle () const
scalar concaveAngle () const
label nGrow () const
If points get not extruded do nGrow layers of connected faces.
scalar maxFaceThicknessRatio () const
Stop layer growth on highly warped cells.
label nBufferCellsNoExtrude () const
Create buffer region for new layer terminations.
const Switch & additionalReporting () const
const word & meshShrinker () const
Type of mesh shrinker.
scalar layerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine overall thickness. Uses two of the four parameters.
scalar layerExpansionRatio (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine expansion ratio. Uses two of the four parameters.
scalar firstLayerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine first layer (near-wall) thickness. Uses two of the.
scalar finalLayerThicknessRatio (const label nLayers, const scalar expansionRatio) const
Determine ratio of final layer thickness to.
Detailed Description
Simple container to keep together layer specific information.
Source files
layerParameters.H
layerParameters.C
Definition at line 53 of file layerParameters.H.
Member Enumeration Documentation
enum layerSpecification
Enumeration defining the layer specification:
first and total thickness specified
first and expansion ratio specified
final and total thickness specified
final and expansion ratio specified
total thickness and expansion ratio specified
Enumerator
ILLEGAL
FIRST_AND_TOTAL
FIRST_AND_EXPANSION
FINAL_AND_TOTAL
FINAL_AND_EXPANSION
TOTAL_AND_EXPANSION
Definition at line 68 of file layerParameters.H.
Constructor & Destructor Documentation
layerParameters (const dictionary & dict, const polyBoundaryMesh & boundaryMesh, const bool dryRun = false)
Construct from dictionary.
Definition at line 93 of file layerParameters.C.
Member Function Documentation
const dictionary& dict () const inline
Definition at line 192 of file layerParameters.H.
const labelList& numLayers () const inline
How many layers to add.
-1 : no specification. Assume 0 layers but allow sliding to make layers 0 : specified to have 0 layers. No sliding allowed. >0 : number of layers
Definition at line 208 of file layerParameters.H.
Referenced by snappyLayerDriver::doLayers().
bool relativeSizes () const inline
Are size parameters relative to inner cell size or.
absolute distances.
Definition at line 218 of file layerParameters.H.
const scalarField& expansionRatio () const inline
Definition at line 224 of file layerParameters.H.
const scalarField& finalLayerThickness () const inline
Wanted thickness of the layer furthest away.
from the wall (i.e. nearest the original mesh). If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 236 of file layerParameters.H.
const scalarField& firstLayerThickness () const inline
Wanted thickness of the layer nearest to the wall.
If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 247 of file layerParameters.H.
const scalarField& thickness () const inline
Wanted overall thickness of all layers.
If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 258 of file layerParameters.H.
const scalarField& minThickness () const inline
Minimum overall thickness of cell layer. If for any reason layer.
cannot be above minThickness do not add layer. If relativeSize() this number is relative to undistorted size of the cell outside layer.
Definition at line 270 of file layerParameters.H.
label nLayerIter () const inline
Number of overall layer addition iterations.
Definition at line 281 of file layerParameters.H.
label nRelaxedIter () const inline
Number of iterations after which relaxed motion rules.
are to be used.
Definition at line 291 of file layerParameters.H.
scalar featureAngle () const inline
Definition at line 299 of file layerParameters.H.
scalar mergePatchFacesAngle () const inline
Definition at line 304 of file layerParameters.H.
Referenced by snappyLayerDriver::mergePatchFacesUndo().
scalar concaveAngle () const inline
Definition at line 309 of file layerParameters.H.
Referenced by snappyLayerDriver::mergePatchFacesUndo().
label nGrow () const inline
If points get not extruded do nGrow layers of connected faces.
that are not grown. Is used to not do layers at all close to features.
Definition at line 320 of file layerParameters.H.
scalar maxFaceThicknessRatio () const inline
Stop layer growth on highly warped cells.
Definition at line 328 of file layerParameters.H.
label nBufferCellsNoExtrude () const inline
Create buffer region for new layer terminations.
Definition at line 336 of file layerParameters.H.
const Switch& additionalReporting () const inline
Definition at line 341 of file layerParameters.H.
const word& meshShrinker () const inline
Type of mesh shrinker.
Definition at line 349 of file layerParameters.H.
Foam::scalar layerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine overall thickness. Uses two of the four parameters.
according to the layerSpecification
Definition at line 377 of file layerParameters.C.
Foam::scalar layerExpansionRatio (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine expansion ratio. Uses two of the four parameters.
according to the layerSpecification
Definition at line 437 of file layerParameters.C.
Foam::scalar firstLayerThickness (const label nLayers, const scalar firstLayerThickess, const scalar finalLayerThickess, const scalar totalThickness, const scalar expansionRatio) const
Determine first layer (near-wall) thickness. Uses two of the.
four parameters according to the layerSpecification
Definition at line 488 of file layerParameters.C.
Foam::scalar finalLayerThicknessRatio (const label nLayers, const scalar expansionRatio) const
Determine ratio of final layer thickness to.
overall layer thickness
Definition at line 547 of file layerParameters.C.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/layerParameters/layerParameters.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/layerParameters/layerParameters.C