OpenFOAM: ZoneMesh< Zone, MeshType > Class Template Reference
ZoneMesh< Zone, MeshType > Class Template Reference
A list of mesh zones.
Public Member Functions
ZoneMesh (const IOobject &io, const MeshType &mesh)
Read constructor given IOobject and a MeshType reference.
ZoneMesh (const IOobject &io, const MeshType &mesh, const label size)
Construct given size.
ZoneMesh (const IOobject &io, const MeshType &mesh, const PtrList< ZoneType > &pzm)
Construct given a PtrList.
~ZoneMesh ()
Destructor.
const MeshType & mesh () const
Return the mesh reference.
const Map< label > & zoneMap () const
Map of zones containing zone index for all zoned elements.
label whichZone (const label objectIndex) const
Given a global object index, return the zone it is in.
wordList types () const
Return a list of zone types.
wordList names () const
A list of the zone names.
wordList names (const wordRe &matcher) const
A list of zone names satisfying the input matcher.
wordList names (const wordRes &matcher) const
A list of zone names satisfying the input matchers.
wordList sortedNames () const
Sorted list of the zone names.
wordList sortedNames (const wordRe &matcher) const
Sorted list of zone names satisfying the input matcher.
wordList sortedNames (const wordRes &matcher) const
Sorted list of zone names satisfying the input matchers.
labelList indices (const keyType &key) const
Return zone indices for all matches.
labelList indices (const wordRes &matcher) const
Return zone indices for all matches.
label findIndex (const keyType &key) const
Return zone index for the first match, return -1 if not found.
label findIndex (const wordRes &matcher) const
Return zone index for the first match, return -1 if not found.
label findZoneID (const word &zoneName) const
Find zone index given a name, return -1 if not found.
bitSet selection (const labelUList &zoneIds) const
Return all elements (cells, faces, points) contained in the listed zones.
bitSet selection (const keyType &key) const
Return all elements (cells, faces, points) that match the zone specification as a bitSet.
bitSet selection (const wordRes &matcher) const
Return all elements (cells, faces, points) that match the zone specification as a bitSet.
const ZoneType * zonePtr (const word &zoneName) const
Lookup zone by name and return const pointer, nullptr on error.
ZoneType * zonePtr (const word &zoneName)
Lookup zone by name and return pointer, nullptr on error.
void clearAddressing ()
Clear addressing.
void clear ()
Clear the zones.
bool checkDefinition (const bool report=false) const
Check zone definition. Return true if in error.
bool checkParallelSync (const bool report=false) const
Check whether all procs have all zones and in same order.
void movePoints (const pointField &pts)
Correct zone mesh after moving points.
bool writeData (Ostream &os) const
writeData member function required by regIOobject
const ZoneType & operator[] (const word &zoneName) const
Return const reference to zone by name.
ZoneType & operator[] (const word &zoneName)
Return reference to an existing zone by name.
ZoneType & operator() (const word &zoneName, const bool verbose=false)
Find an existing zone by name or create a new empty one if required.
labelList findIndices (const keyType &key) const
Identical to the indices() method (AUG-2018)
template<class UnaryMatchPredicate >
Foam::wordList namesImpl (const PtrList< ZoneType > &list, const UnaryMatchPredicate &matcher, const bool doSort)
template<class UnaryMatchPredicate >
Foam::labelList indicesImpl (const PtrList< ZoneType > &list, const UnaryMatchPredicate &matcher)
template<class UnaryMatchPredicate >
Foam::label findIndexImpl (const PtrList< ZoneType > &list, const UnaryMatchPredicate &matcher)
Public Member Functions inherited from PtrList< ZoneType >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< ZoneType > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< ZoneType > &&list)
Move construct.
PtrList (UList< ZoneType * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
PtrList (const PtrList< ZoneType > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< ZoneType > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< ZoneType > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
PtrList< ZoneType > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (ZoneType *ptr)
Append an element to the end of the list.
void append (autoPtr< ZoneType > &aptr)
Move append an element to the end of the list.
void append (autoPtr< ZoneType > &&aptr)
Move append an element to the end of the list.
void append (const tmp< ZoneType > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< ZoneType > &list)
Transfer into this list and annul the argument list.
const ZoneType * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< ZoneType > set (const label i, ZoneType *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< ZoneType > set (const label i, autoPtr< ZoneType > &aptr)
Set element to given autoPtr and return old element.
autoPtr< ZoneType > set (const label i, autoPtr< ZoneType > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< ZoneType > set (const label i, const tmp< ZoneType > &tptr)
Set element to given tmp and return old element.
autoPtr< ZoneType > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< ZoneType > &list)
Copy assignment.
void operator= (PtrList< ZoneType > &&list)
Move assignment.
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Static Public Attributes
static int disallowGenericZones
Debug switch to disallow the use of generic zones.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Friends
Ostream & operator (Ostream &os, const ZoneMesh< ZoneType, MeshType > &zones)
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Protected Member Functions inherited from PtrList< ZoneType >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Zone, class MeshType>
class Foam::ZoneMesh< Zone, MeshType >
A list of mesh zones.
Source files
ZoneMesh.H
ZoneMesh.C
Definition at line 38 of file cellZoneMeshFwd.H.
Constructor & Destructor Documentation
ZoneMesh (const IOobject & io, const MeshType & mesh)
Read constructor given IOobject and a MeshType reference.
Definition at line 223 of file ZoneMesh.C.
ZoneMesh (const IOobject & io, const MeshType & mesh, const label size)
Construct given size.
Definition at line 239 of file ZoneMesh.C.
References Foam::blockMeshTools::read().
ZoneMesh (const IOobject & io, const MeshType & mesh, const PtrList< ZoneType > & pzm)
Construct given a PtrList.
Definition at line 257 of file ZoneMesh.C.
~ZoneMesh ()
Destructor.
Definition at line 285 of file ZoneMesh.C.
Member Function Documentation
const MeshType& mesh () const inline
Return the mesh reference.
Definition at line 185 of file ZoneMesh.H.
const Foam::Map< Foam::label > & zoneMap () const
Map of zones containing zone index for all zoned elements.
Return -1 if the object is not in the zone
Definition at line 295 of file ZoneMesh.C.
Foam::label whichZone (const label objectIndex) const
Given a global object index, return the zone it is in.
If object does not belong to any zones, return -1
Definition at line 308 of file ZoneMesh.C.
Foam::wordList types () const
Return a list of zone types.
Definition at line 317 of file ZoneMesh.C.
Foam::wordList names () const
A list of the zone names.
Definition at line 333 of file ZoneMesh.C.
Referenced by reader::mesh(), and zoneMotion::zoneMotion().
Foam::wordList names (const wordRe & matcher) const
A list of zone names satisfying the input matcher.
Definition at line 350 of file ZoneMesh.C.
Foam::wordList names (const wordRes & matcher) const
A list of zone names satisfying the input matchers.
Definition at line 360 of file ZoneMesh.C.
References Foam::namesImpl().
Foam::wordList sortedNames () const
Sorted list of the zone names.
Definition at line 370 of file ZoneMesh.C.
References Foam::namesImpl().
Foam::wordList sortedNames (const wordRe & matcher) const
Sorted list of zone names satisfying the input matcher.
Definition at line 381 of file ZoneMesh.C.
Foam::wordList sortedNames (const wordRes & matcher) const
Sorted list of zone names satisfying the input matchers.
Definition at line 391 of file ZoneMesh.C.
References Foam::namesImpl().
Foam::labelList indices (const keyType & key) const
Return zone indices for all matches.
Definition at line 402 of file ZoneMesh.C.
References Foam::namesImpl().
Foam::labelList indices (const wordRes & matcher) const
Return zone indices for all matches.
Definition at line 427 of file ZoneMesh.C.
Foam::label findIndex (const keyType & key) const
Return zone index for the first match, return -1 if not found.
Definition at line 442 of file ZoneMesh.C.
Foam::label findIndex (const wordRes & matcher) const
Return zone index for the first match, return -1 if not found.
Definition at line 467 of file ZoneMesh.C.
Foam::label findZoneID (const word & zoneName) const
Find zone index given a name, return -1 if not found.
Definition at line 477 of file ZoneMesh.C.
References Foam::findIndexImpl().
Referenced by zoneMotion::zoneMotion().
Foam::bitSet selection (const labelUList & zoneIds) const
Return all elements (cells, faces, points) contained in the listed zones.
The bitSet is empty (zero-size) if there are no elements matched anywhere.
Definition at line 521 of file ZoneMesh.C.
Foam::bitSet selection (const keyType & key) const
Return all elements (cells, faces, points) that match the zone specification as a bitSet.
The bitSet is empty (zero-size) if there are no elements matched anywhere.
Definition at line 551 of file ZoneMesh.C.
Foam::bitSet selection (const wordRes & matcher) const
Return all elements (cells, faces, points) that match the zone specification as a bitSet.
The bitSet is empty (zero-size) if there are no elements matched anywhere.
Definition at line 561 of file ZoneMesh.C.
const ZoneType * zonePtr (const word & zoneName) const
Lookup zone by name and return const pointer, nullptr on error.
Definition at line 571 of file ZoneMesh.C.
ZoneType * zonePtr (const word & zoneName)
Lookup zone by name and return pointer, nullptr on error.
Definition at line 593 of file ZoneMesh.C.
void clearAddressing ()
Clear addressing.
Definition at line 614 of file ZoneMesh.C.
Referenced by Foam::polyMeshZipUpCells(), and polyMesh::updateMesh().
void clear ()
Clear the zones.
Definition at line 628 of file ZoneMesh.C.
bool checkDefinition (const bool report = false) const
Check zone definition. Return true if in error.
Definition at line 637 of file ZoneMesh.C.
bool checkParallelSync (const bool report = false) const
Check whether all procs have all zones and in same order.
Returns
True if any errors.
Definition at line 656 of file ZoneMesh.C.
void movePoints (const pointField & pts)
Correct zone mesh after moving points.
Definition at line 732 of file ZoneMesh.C.
bool writeData (Ostream & os) const virtual
writeData member function required by regIOobject
Implements regIOobject.
Definition at line 744 of file ZoneMesh.C.
const ZoneType & operator[] (const word & zoneName) const
Return const reference to zone by name.
Fatal if the zone does not exist.
Definition at line 755 of file ZoneMesh.C.
ZoneType & operator[] (const word & zoneName)
Return reference to an existing zone by name.
Fatal if the zone does not exist.
Definition at line 775 of file ZoneMesh.C.
ZoneType & operator() (const word & zoneName, const bool verbose = false)
Find an existing zone by name or create a new empty one if required.
To determine if the zone already existed or was newly created, it will be necessary to add additional logic in the caller. For example,
*     const label nOrig = zones.size();
*
*     ZoneType& zn = zones("zoneName");
*
*     if (nOrig == zones.size()) { existing... } else { new... }
*
Parameters
zoneName the name of the zone
verbose report if an existing zone was selected or a new zone was created.
Returns
non-const reference to the existing or new zone
Definition at line 795 of file ZoneMesh.C.
labelList findIndices (const keyType & key) const inline
Identical to the indices() method (AUG-2018)
Definition at line 398 of file ZoneMesh.H.
Foam::wordList namesImpl (const PtrList< ZoneType > & list, const UnaryMatchPredicate & matcher, const bool doSort)
Definition at line 138 of file ZoneMesh.C.
Foam::labelList indicesImpl (const PtrList< ZoneType > & list, const UnaryMatchPredicate & matcher)
Definition at line 173 of file ZoneMesh.C.
Foam::label findIndexImpl (const PtrList< ZoneType > & list, const UnaryMatchPredicate & matcher)
Definition at line 200 of file ZoneMesh.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const ZoneMesh< ZoneType, MeshType > & zones) friend
Member Data Documentation
int disallowGenericZones static
Debug switch to disallow the use of generic zones.
Definition at line 139 of file ZoneMesh.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/zones/ZoneMesh/cellZoneMeshFwd.H
src/OpenFOAM/meshes/polyMesh/zones/ZoneMesh/ZoneMesh.H
src/OpenFOAM/meshes/polyMesh/zones/ZoneMesh/ZoneMesh.C