OpenFOAM: surface Class Reference
surface Class Reference
Visualisation of surface data with additional routines for handling parallel distributed data.
Public Types
enum representationType {
rtNone, rtGlyph, rtWireframe, rtSurface,
rtSurfaceWithEdges
}
Surface representation types.
Public Types inherited from geometryBase
enum renderModeType { rmFlat, rmGouraud, rmPhong }
Surface shading types.
Public Member Functions
TypeNameNoDebug ("surface")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, surface, dictionary,(const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours),(parent, dict, colours))
surface (const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~surface ()
Destructor.
virtual void updateActors (const scalar position)
Update the actors.
Public Member Functions inherited from geometryBase
geometryBase (const runTimePostProcessing &parent_, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~geometryBase ()
Destructor.
const runTimePostProcessing & parent () const
Return the reference to the parent function object.
bool needsCollective () const
May need to gather geometry parts to render on single-processor.
const word & name () const
Return the name.
bool visible () const
Return the visible flag.
bool parallel () const
Allow parallel rendering.
scalar opacity (const scalar position) const
Return the opacity.
const HashPtrTable< Function1
< vector > > & colours () const
Return reference to the colours.
virtual void addGeometryToScene (const scalar position, vtkRenderer *renderer)=0
Add geometry to scene.
virtual bool clear ()=0
Clear any files used to create the object(s)
Static Public Member Functions
static autoPtr< surface > New (const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours, const word &surfaceName)
Return selected surface.
Static Public Attributes
static const Enum
< representationType > representationTypeNames
Names for surface representation types.
Static Public Attributes inherited from geometryBase
static const Enum< renderModeType > renderModeTypeNames
Names for surface shading types.
static int debug
Debug switch.
Protected Member Functions
void setRepresentation (vtkActor *actor) const
Set the representation.
void addFeatureEdges (vtkRenderer *renderer, vtkFeatureEdges *featureEdges) const
Add feature edges to scene.
void addFeatureEdges (vtkRenderer *renderer, vtkPolyData *data) const
Add feature edges to scene.
void addFeatureEdges (vtkRenderer *renderer, vtkCompositeDataGeometryFilter *input) const
Add feature edges to scene.
vtkSmartPointer
< vtkMultiPieceDataSet > gatherSurfacePieces (const polySurface *surf) const
Gather and convert polySurface to multi-piece dataset with vtkPolyData for the leaves.
vtkSmartPointer
< vtkMultiPieceDataSet > gatherFaceCentres (const polySurface *surf) const
Gather and convert polySurface to multi-piece dataset with vtkPolyData for the leaves.
template<class Type , class GeoMeshType >
bool addField (vtkDataSet *piece, const Field< Type > &fld, const word &fieldName) const
Add field of Type to piece as VTK field data in GeoMeshType slot.
template<class Type , class GeoMeshType >
bool addDimField (vtkDataSet *piece, const regIOobject *ioptr, const word &fieldName) const
Attempt cast of regIOobject to DimensionedField<Type> and add to piece as VTK field data in GeoMeshType slot.
template<class GeoMeshType >
bool addDimField (vtkDataSet *piece, const regIOobject *ioptr, const word &fieldName) const
Attempt cast of regIOobject to standard DimensionedField types and add to piece when possible.
template<class Type , class GeoMeshType >
bool addDimField (vtkMultiPieceDataSet *multiPiece, const DimensionedField< Type, GeoMeshType > *fldptr, const word &fieldName) const
Add DimensionedField of Type to multi-piece as VTK field data in GeoMeshType slot (CELL | POINT).
template<class Type , class GeoMeshType >
bool addDimField (vtkMultiPieceDataSet *multiPiece, const regIOobject *ioptr, const word &fieldName) const
Attempt cast of regIOobject to DimensionedField<Type> and add in multi-piece as VTK field data in GeoMeshType slot (CELL | POINT).
template<class GeoMeshType >
bool addDimField (vtkMultiPieceDataSet *multiPiece, const regIOobject *ioptr, const word &fieldName) const
Attempt cast of regIOobject to standard DimensionedField types and add when possible in GeoMeshType slot (CELL | POINT).
template<class GeoMeshType >
bool addDimField (vtkMultiPieceDataSet *multiPiece, const polySurface *surf, const word &fieldName) const
Add using regIOobject information obtained from surface.
surface (const surface &)=delete
No copy construct.
void operator= (const surface &)=delete
No copy assignment.
Protected Member Functions inherited from geometryBase
void initialiseActor (vtkActor *actor) const
Initialise actor.
geometryBase (const geometryBase &)=delete
No copy construct.
void operator= (const geometryBase &)=delete
No copy assignment.
Protected Attributes
representationType representation_
Representation type.
bool featureEdges_
Activate feature edges.
bool backFaceCulling_
Back face culling option; default = off.
bool frontFaceCulling_
Front face culling option; default = on.
autoPtr< Function1< vector > > surfaceColour_
Surface colour.
autoPtr< Function1< vector > > edgeColour_
Edge colour.
vtkSmartPointer< vtkActor > surfaceActor_
Surface actor.
vtkSmartPointer< vtkActor > edgeActor_
Edge actor.
scalar maxGlyphLength_
Max glyph length for representation type rtGlyph.
Protected Attributes inherited from geometryBase
const runTimePostProcessing & parent_
Reference to the parent function object.
word name_
The surface name.
bool visible_
Visible flag.
bool parallel_
Allow parallel rendering.
renderModeType renderMode_
Render mode.
autoPtr< Function1< scalar > > opacity_
Opacity.
const HashPtrTable< Function1
< vector > > & colours_
Reference to the colours.
Detailed Description
Visualisation of surface data with additional routines for handling parallel distributed data.
Dictionary controls
Property Description Required Default
representation none/glyph/wireframe/surface/surfaceWithEdges yes
surfaceColour Override surface colour no
edgeColour Override edge colour no
featureEdges Display surface feature edges no false
maxGlyphLength Limit for glyph representation yes 0
backFaceCulling Cull back face no false
frontFaceCulling Cull front face no true
Source files
surface.H
surface.C
surfaceGather.C
surfaceTemplates.C
Definition at line 184 of file surface.H.
Member Enumeration Documentation
enum representationType
Surface representation types.
Enumerator
rtNone
"none"
rtGlyph
"glyph"
rtWireframe
"wireframe"
rtSurface
"surface"
rtSurfaceWithEdges
"surfaceWithEdges"
Definition at line 195 of file surface.H.
Constructor & Destructor Documentation
surface (const surface &) protected delete
No copy construct.
surface (const runTimePostProcessing & parent, const dictionary & dict, const HashPtrTable< Function1< vector >> & colours)
Construct from dictionary.
Definition at line 195 of file surface.C.
~surface () virtual
Destructor.
Definition at line 275 of file surface.C.
Member Function Documentation
void setRepresentation (vtkActor * actor) const protected
Set the representation.
Definition at line 89 of file surface.C.
void addFeatureEdges (vtkRenderer * renderer, vtkFeatureEdges * featureEdges) const protected
Add feature edges to scene.
featureEdges->SetFeatureAngle(60);
Definition at line 129 of file surface.C.
void addFeatureEdges (vtkRenderer * renderer, vtkPolyData * data) const protected
Add feature edges to scene.
Definition at line 161 of file surface.C.
void addFeatureEdges (vtkRenderer * renderer, vtkCompositeDataGeometryFilter * input) const protected
Add feature edges to scene.
Definition at line 177 of file surface.C.
vtkSmartPointer< vtkMultiPieceDataSet > gatherSurfacePieces (const polySurface * surf) const protected
Gather and convert polySurface to multi-piece dataset with vtkPolyData for the leaves.
If VTK is also running in parallel, each surface is left as a processor-local piece. Otherwise all processor-local surfaces are gathered onto the master in their correponding slots.
Definition at line 37 of file surfaceGather.C.
References List< T >::clear(), polySurface::faces(), UPstream::firstSlave(), UPstream::lastSlave(), UPstream::master(), UPstream::masterNo(), Patch::mesh(), UPstream::myProcNo(), geometryBase::needsCollective(), Foam::New(), UPstream::nProcs(), points, polySurface::points(), UPstream::scheduled, and UList< T >::size().
vtkSmartPointer< vtkMultiPieceDataSet > gatherFaceCentres (const polySurface * surf) const protected
Gather and convert polySurface to multi-piece dataset with vtkPolyData for the leaves.
If VTK is also running in parallel, each surface is left as a processor-local piece. Otherwise all processor-local surfaces are gathered onto the master in their correponding slots.
Definition at line 128 of file surfaceGather.C.
bool addField (vtkDataSet * piece, const Field< Type > & fld, const word & fieldName) const protected
Add field of Type to piece as VTK field data in GeoMeshType slot.
GeoMeshType distinguishes between vtkCellData and vtkPointData
Parameters
piece The VTK piece (null protected)
fld The field values to add
fieldName The field name to use
Definition at line 29 of file surfaceTemplates.C.
References fld.
bool addDimField (vtkDataSet * piece, const regIOobject * ioptr, const word & fieldName) const protected
Attempt cast of regIOobject to DimensionedField<Type> and add to piece as VTK field data in GeoMeshType slot.
GeoMeshType distinguishes between vtkCellData and vtkPointData
Parameters
piece The VTK piece (null protected)
ioptr The field values to add
fieldName The field name to use
Definition at line 55 of file surfaceTemplates.C.
bool addDimField (vtkDataSet * piece, const regIOobject * ioptr, const word & fieldName) const protected
Attempt cast of regIOobject to standard DimensionedField types and add to piece when possible.
Parameters
piece The VTK piece (null protected)
ioptr The field values to add
fieldName The field name to use
Definition at line 80 of file surfaceTemplates.C.
bool addDimField (vtkMultiPieceDataSet * multiPiece, const DimensionedField< Type, GeoMeshType > * fldptr, const word & fieldName) const protected
Add DimensionedField of Type to multi-piece as VTK field data in GeoMeshType slot (CELL | POINT).
Definition at line 114 of file surfaceTemplates.C.
bool addDimField (vtkMultiPieceDataSet * multiPiece, const regIOobject * ioptr, const word & fieldName) const protected
Attempt cast of regIOobject to DimensionedField<Type> and add in multi-piece as VTK field data in GeoMeshType slot (CELL | POINT).
Parameters
multiPiece The VTK pieces
ioptr The field values to add
fieldName The field name to use
Definition at line 216 of file surfaceTemplates.C.
bool addDimField (vtkMultiPieceDataSet * multiPiece, const regIOobject * ioptr, const word & fieldName) const protected
Attempt cast of regIOobject to standard DimensionedField types and add when possible in GeoMeshType slot (CELL | POINT).
Parameters
multiPiece The VTK pieces
ioptr The field values to add
fieldName The field name to use
Definition at line 233 of file surfaceTemplates.C.
bool addDimField (vtkMultiPieceDataSet * multiPiece, const polySurface * surf, const word & fieldName) const protected
Add using regIOobject information obtained from surface.
Definition at line 267 of file surfaceTemplates.C.
void operator= (const surface &) protected delete
No copy assignment.
TypeNameNoDebug ("surface")
Run-time type information.
declareRunTimeSelectionTable (autoPtr , surface , dictionary , (const runTimePostProcessing &parent, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours) , (parent, dict, colours))
Foam::autoPtr< Foam::functionObjects::runTimePostPro::surface > New (const runTimePostProcessing & parent, const dictionary & dict, const HashPtrTable< Function1< vector >> & colours, const word & surfaceName) static
Return selected surface.
Definition at line 247 of file surface.C.
void updateActors (const scalar position) virtual
Update the actors.
Implements geometryBase.
Reimplemented in geometryPatches, and geometrySurface.
Definition at line 282 of file surface.C.
Member Data Documentation
const Foam::Enum< Foam::functionObjects::runTimePostPro::surface::representationType > representationTypeNames static
Names for surface representation types.
Definition at line 207 of file surface.H.
representationType representation_ protected
Representation type.
Definition at line 217 of file surface.H.
bool featureEdges_ protected
Activate feature edges.
Definition at line 222 of file surface.H.
bool backFaceCulling_ protected
Back face culling option; default = off.
Definition at line 227 of file surface.H.
bool frontFaceCulling_ protected
Front face culling option; default = on.
Definition at line 232 of file surface.H.
autoPtr<Function1<vector> > surfaceColour_ protected
Surface colour.
Definition at line 237 of file surface.H.
autoPtr<Function1<vector> > edgeColour_ protected
Edge colour.
Definition at line 242 of file surface.H.
vtkSmartPointer<vtkActor> surfaceActor_ protected
Surface actor.
Definition at line 247 of file surface.H.
vtkSmartPointer<vtkActor> edgeActor_ protected
Edge actor.
Definition at line 252 of file surface.H.
scalar maxGlyphLength_ protected
Max glyph length for representation type rtGlyph.
Definition at line 257 of file surface.H.
The documentation for this class was generated from the following files:
src/functionObjects/graphics/runTimePostProcessing/surface.H
src/functionObjects/graphics/runTimePostProcessing/surface.C
src/functionObjects/graphics/runTimePostProcessing/surfaceGather.C
src/functionObjects/graphics/runTimePostProcessing/surfaceTemplates.C