OpenFOAM: reducedUnits Class Reference
reducedUnits Class Reference
Public Member Functions
reducedUnits ()
Construct with no argument, uses default values:
reducedUnits (scalar refLength, scalar refTime, scalar refMass)
Construct from components.
reducedUnits (const IOdictionary &reducedUnitsDict)
Construct from dictionary.
~reducedUnits ()=default
Destructor.
void setRefValues (scalar refLength, scalar refTime, scalar refMass)
void setRefValues (const IOdictionary &reducedUnitsDict)
scalar refLength () const
scalar refTime () const
scalar refMass () const
scalar refTemp () const
scalar refEnergy () const
scalar refForce () const
scalar refVelocity () const
scalar refVolume () const
scalar refPressure () const
scalar refMassDensity () const
scalar refNumberDensity () const
Static Public Attributes
static const scalar kb = 1.3806504e-23
Static data someStaticData.
Friends
Ostream & operator<< (Ostream &, const reducedUnits &)
Detailed Description
Source files
reducedUnits.H
reducedUnitsI.H
reducedUnits.C
reducedUnitsIO.C
Definition at line 55 of file reducedUnits.H.
Constructor & Destructor Documentation
reducedUnits ()
Construct with no argument, uses default values:
length = 1nm mass = 1.660538782e-27kg (unified atomic mass unit) temperature = 1K (therefore, energy = 1*kb)
Definition at line 68 of file reducedUnits.C.
reducedUnits (scalar refLength, scalar refTime, scalar refMass)
Construct from components.
Definition at line 79 of file reducedUnits.C.
reducedUnits (const IOdictionary & reducedUnitsDict)
Construct from dictionary.
Definition at line 93 of file reducedUnits.C.
~reducedUnits () default
Destructor.
Member Function Documentation
void setRefValues (scalar refLength, scalar refTime, scalar refMass)
Definition at line 106 of file reducedUnits.C.
void setRefValues (const IOdictionary & reducedUnitsDict)
Definition at line 121 of file reducedUnits.C.
Foam::scalar refLength () const inline
Definition at line 23 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refTime () const inline
Definition at line 29 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refMass () const inline
Definition at line 35 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refTemp () const inline
Definition at line 41 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refEnergy () const inline
Definition at line 47 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refForce () const inline
Definition at line 53 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refVelocity () const inline
Definition at line 59 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refVolume () const inline
Definition at line 65 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refPressure () const inline
Definition at line 71 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refMassDensity () const inline
Definition at line 77 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Foam::scalar refNumberDensity () const inline
Definition at line 83 of file reducedUnitsI.H.
Referenced by Foam::operator<<().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const reducedUnits &) friend
Member Data Documentation
const Foam::scalar kb = 1.3806504e-23 static
Static data someStaticData.
Definition at line 98 of file reducedUnits.H.
The documentation for this class was generated from the following files:
src/lagrangian/molecularDynamics/molecule/reducedUnits/reducedUnits.H
src/lagrangian/molecularDynamics/molecule/reducedUnits/reducedUnits.C
src/lagrangian/molecularDynamics/molecule/reducedUnits/reducedUnitsI.H