OpenFOAM: decompositionMethod Class Reference
decompositionMethod Class Reference abstract
Abstract base class for domain decomposition.
Public Member Functions
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionary,(const dictionary &decompDict),(decompDict))
declareRunTimeSelectionTable (autoPtr, decompositionMethod, dictionaryRegion,(const dictionary &decompDict, const word &regionName),(decompDict, regionName))
decompositionMethod (const dictionary &decompDict)
Construct given the decomposition dictionary.
decompositionMethod (const dictionary &decompDict, const word &regionName)
Construct given the decomposition dictionary for specific region.
virtual ~decompositionMethod ()=default
Destructor.
label nDomains () const
Number of domains.
virtual bool parallelAware () const =0
Is method parallel aware?
virtual labelList decompose (const pointField &points, const scalarField &pointWeights) const
Return for every coordinate the wanted processor number.
virtual labelList decompose (const pointField &points) const
Decompose with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const pointField &points, const scalarField &pointWeights) const =0
Return for every coordinate the wanted processor number.
virtual labelList decompose (const polyMesh &mesh, const pointField &points) const
Decompose with uniform weights on the points.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints, const scalarField &regionWeights) const
Return for every coordinate the wanted processor number. Gets.
virtual labelList decompose (const polyMesh &mesh, const labelList &cellToRegion, const pointField &regionPoints) const
Like decompose but with uniform weights on the regions.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc, const scalarField &cWeights) const =0
Return for every coordinate the wanted processor number.
virtual labelList decompose (const labelListList &globalCellCells, const pointField &cc) const
Like decompose but with uniform weights on the cells.
void setConstraints (const polyMesh &mesh, boolList &blockedFace, PtrList< labelList > &specifiedProcessorFaces, labelList &specifiedProcessor, List< labelPair > &explicitConnections) const
Helper: extract constraints:
void applyConstraints (const polyMesh &mesh, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections, labelList &finalDecomp) const
Helper: apply constraints to a decomposition.
virtual labelList decompose (const polyMesh &mesh, const scalarField &cellWeights, const boolList &blockedFace, const PtrList< labelList > &specifiedProcessorFaces, const labelList &specifiedProcessor, const List< labelPair > &explicitConnections) const
labelList decompose (const polyMesh &mesh, const scalarField &cWeights) const
Decompose a mesh.
Static Public Member Functions
static label nDomains (const dictionary &decompDict)
Return the numberOfSubdomains entry from the dictionary.
static label nDomains (const dictionary &decompDict, const word &regionName)
Return the numberOfSubdomains from a region within the.
static const dictionary & optionalRegionDict (const dictionary &decompDict, const word &regionName)
Return an optional region dictionary from "regions" sub-dictionary.
static autoPtr
< decompositionMethod > New (const dictionary &decompDict)
Return a reference to the selected decomposition method.
static autoPtr
< decompositionMethod > New (const dictionary &decompDict, const word &regionName)
Return a reference to the selected decomposition method, with region specification.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool global, CompactListList< label > &cellCells)
Helper: determine (local or global) cellCells from mesh.
static void calcCellCells (const polyMesh &mesh, const labelList &agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > &cellCells, CompactListList< scalar > &cellCellWeights)
Helper: determine (local or global) cellCells and face weights.
Protected Types
enum selectionType { DEFAULT = 0, EXACT = 1, MANDATORY = 2, NULL_DICT = 4 }
Selection type when handling the coefficients dictionary.
Protected Member Functions
const dictionary & findCoeffsDict (const word &coeffsName, int select=selectionType::DEFAULT) const
Locate coeffsName dictionary or the fallback "coeffs" dictionary.
Static Protected Member Functions
static const dictionary & findCoeffsDict (const dictionary &dict, const word &coeffsName, int select=selectionType::DEFAULT)
Locate coeffsName dictionary or the fallback "coeffs" dictionary within an enclosing dictionary.
Protected Attributes
const dictionary & decompDict_
Top-level decomposition dictionary (eg, decomposeParDict)
const dictionary & decompRegionDict_
Region-specific decomposition dictionary information.
label nDomains_
Number of domains for the decomposition.
PtrList< decompositionConstraint > constraints_
Optional constraints.
Detailed Description
Abstract base class for domain decomposition.
Source files
decompositionMethod.H
decompositionMethod.C
Definition at line 47 of file decompositionMethod.H.
Member Enumeration Documentation
enum selectionType protected
Selection type when handling the coefficients dictionary.
To be used as a bit-mask for findCoeffsDict
Enumerator
DEFAULT
Default request.
EXACT
No fallback to "coeffs" if main name not found.
MANDATORY
Fatal if dictionary could not be found.
NULL_DICT
On failure, return dictionary::null instead of the top-level enclosing dictionary.
Definition at line 84 of file decompositionMethod.H.
Constructor & Destructor Documentation
decompositionMethod (const dictionary & decompDict)
Construct given the decomposition dictionary.
Definition at line 320 of file decompositionMethod.C.
decompositionMethod (const dictionary & decompDict, const word & regionName)
Construct given the decomposition dictionary for specific region.
Definition at line 333 of file decompositionMethod.C.
virtual ~decompositionMethod () virtual default
Destructor.
Member Function Documentation
const Foam::dictionary & findCoeffsDict (const dictionary & dict, const word & coeffsName, int select = selectionType::DEFAULT) static protected
Locate coeffsName dictionary or the fallback "coeffs" dictionary within an enclosing dictionary.
Parameters
select choose to include "coeffs" in the search, make failure a FatalError, return dictionary::null instead on failure.
Returns
the coefficients dictionary found. If nothing was found, return the enclosing dictionary or dictionary::null (depending on the select parameter).
Definition at line 222 of file decompositionMethod.C.
const Foam::dictionary & findCoeffsDict (const word & coeffsName, int select = selectionType::DEFAULT) const protected
Locate coeffsName dictionary or the fallback "coeffs" dictionary.
Searches both the region-specific decomposition dictionary and the top-level decomposition dictionary.
Parameters
select choose to include "coeffs" in the search, make failure a FatalError, return dictionary::null instead on failure.
Returns
the coefficients dictionary found. If nothing was found, return the top-level (non-region) dictionary or dictionary::null (depending on the select parameter).
Definition at line 262 of file decompositionMethod.C.
TypeName ("decompositionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , decompositionMethod , dictionary , (const dictionary &decompDict) , (decompDict))
declareRunTimeSelectionTable (autoPtr , decompositionMethod , dictionaryRegion , (const dictionary &decompDict, const word &regionName) , (decompDict, regionName))
Foam::label nDomains (const dictionary & decompDict) static
Return the numberOfSubdomains entry from the dictionary.
Definition at line 55 of file decompositionMethod.C.
Foam::label nDomains (const dictionary & decompDict, const word & regionName) static
Return the numberOfSubdomains from a region within the.
"regions" sub-dictionary
Definition at line 62 of file decompositionMethod.C.
References dictionary::get().
const Foam::dictionary & optionalRegionDict (const dictionary & decompDict, const word & regionName) static
Return an optional region dictionary from "regions" sub-dictionary.
or dictionary::null on failure.
Definition at line 91 of file decompositionMethod.C.
Foam::autoPtr< Foam::decompositionMethod > New (const dictionary & decompDict) static
Return a reference to the selected decomposition method.
Definition at line 352 of file decompositionMethod.C.
Foam::autoPtr< Foam::decompositionMethod > New (const dictionary & decompDict, const word & regionName) static
Return a reference to the selected decomposition method, with region specification.
Definition at line 382 of file decompositionMethod.C.
label nDomains () const inline
Number of domains.
Definition at line 274 of file decompositionMethod.H.
virtual bool parallelAware () const pure virtual
Is method parallel aware?
(i.e. does it synchronize domains across proc boundaries)
Implemented in scotchDecomp, hierarchGeomDecomp, kahipDecomp, multiLevelDecomp, ptscotchDecomp, metisDecomp, simpleGeomDecomp, manualDecomp, randomDecomp, noDecomp, and structuredDecomp.
virtual labelList decompose (const pointField & points, const scalarField & pointWeights) const inline virtual
Return for every coordinate the wanted processor number.
Reimplemented in hierarchGeomDecomp, simpleGeomDecomp, geomDecomp, and randomDecomp.
Definition at line 293 of file decompositionMethod.H.
virtual labelList decompose (const pointField & points) const inline virtual
Decompose with uniform weights on the points.
Reimplemented in hierarchGeomDecomp, geomDecomp, simpleGeomDecomp, and randomDecomp.
Definition at line 305 of file decompositionMethod.H.
virtual labelList decompose (const polyMesh & mesh, const pointField & points, const scalarField & pointWeights) const pure virtual
Return for every coordinate the wanted processor number.
Use the mesh connectivity (if needed)
Implemented in scotchDecomp, hierarchGeomDecomp, ptscotchDecomp, simpleGeomDecomp, multiLevelDecomp, metisLikeDecomp, manualDecomp, randomDecomp, noDecomp, and structuredDecomp.
Foam::labelList decompose (const polyMesh & mesh, const pointField & points) const virtual
Decompose with uniform weights on the points.
Reimplemented in hierarchGeomDecomp, and simpleGeomDecomp.
Definition at line 426 of file decompositionMethod.C.
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints, const scalarField & regionWeights) const virtual
Return for every coordinate the wanted processor number. Gets.
passed agglomeration map (from fine to coarse cells) and coarse cell location. Can be overridden by decomposers that provide this functionality natively. Coarse cells are local to the processor (if in parallel). If you want to have coarse cells spanning processors use the globalCellCells instead.
Reimplemented in scotchDecomp, ptscotchDecomp, and metisLikeDecomp.
Definition at line 438 of file decompositionMethod.C.
Foam::labelList decompose (const polyMesh & mesh, const labelList & cellToRegion, const pointField & regionPoints) const virtual
Like decompose but with uniform weights on the regions.
Definition at line 479 of file decompositionMethod.C.
virtual labelList decompose (const labelListList & globalCellCells, const pointField & cc, const scalarField & cWeights) const pure virtual
Return for every coordinate the wanted processor number.
The connectivity is equal to mesh.cellCells() except for
in parallel the cell numbers are global cell numbers (starting from 0 at processor0 and then incrementing all through the processors)
the connections are across coupled patches
Implemented in scotchDecomp, hierarchGeomDecomp, ptscotchDecomp, simpleGeomDecomp, metisLikeDecomp, multiLevelDecomp, manualDecomp, randomDecomp, noDecomp, and structuredDecomp.
Foam::labelList decompose (const labelListList & globalCellCells, const pointField & cc) const virtual
Like decompose but with uniform weights on the cells.
Reimplemented in hierarchGeomDecomp.
Definition at line 498 of file decompositionMethod.C.
void calcCellCells (const polyMesh & mesh, const labelList & agglom, const label nLocalCoarse, const bool global, CompactListList< label > & cellCells) static
Helper: determine (local or global) cellCells from mesh.
agglomeration. Agglomeration is local to the processor. local : connections are in local indices. Coupled across cyclics but not processor patches. global : connections are in global indices. Coupled across cyclics and processor patches.
Definition at line 510 of file decompositionMethod.C.
void calcCellCells (const polyMesh & mesh, const labelList & agglom, const label nLocalCoarse, const bool parallel, CompactListList< label > & cellCells, CompactListList< scalar > & cellCellWeights) static
Helper: determine (local or global) cellCells and face weights.
from mesh agglomeration. Uses mag of faceArea as weights
Definition at line 708 of file decompositionMethod.C.
void setConstraints (const polyMesh & mesh, boolList & blockedFace, PtrList< labelList > & specifiedProcessorFaces, labelList & specifiedProcessor, List< labelPair > & explicitConnections) const
Helper: extract constraints:
blockedface: existing faces where owner and neighbour on same proc explicitConnections: sets of boundary faces ,, ,, specifiedProcessorFaces: groups of faces with all cells on same processor.
Definition at line 1267 of file decompositionMethod.C.
References PtrList< T >::clear(), List< T >::clear(), primitiveMesh::nFaces(), and List< T >::setSize().
void applyConstraints (const polyMesh & mesh, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections, labelList & finalDecomp) const
Helper: apply constraints to a decomposition.
This gives constraints opportunity to modify decomposition in case the native decomposition method has not obeyed all constraints
Definition at line 1296 of file decompositionMethod.C.
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cellWeights, const boolList & blockedFace, const PtrList< labelList > & specifiedProcessorFaces, const labelList & specifiedProcessor, const List< labelPair > & explicitConnections) const virtual
Parameters
blockedFace Whether owner and neighbour should be on same processor
(takes priority over explicitConnections)
Parameters
specifiedProcessorFaces Whether whole sets of faces (and point neighbours) need to be kept
on single processor
Parameters
explicitConnections Additional connections between boundary faces
Definition at line 909 of file decompositionMethod.C.
References Foam::BitOps::all(), polyMesh::boundaryMesh(), primitiveMesh::cellCentres(), Foam::BitOps::count(), UList< T >::data(), Foam::expressions::patchExpr::debug, UList< T >::empty(), Foam::endl(), Foam::exit(), f(), primitiveMesh::faceCentres(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, polyMesh::globalData(), i, Foam::Info, primitiveMesh::isInternalFace(), VectorSpace< Vector< scalar >, scalar, 3 >::max, primitiveMesh::nCells(), primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, regionSplit::nLocalRegions(), globalMeshData::nTotalCells(), UPstream::parRun(), pFaces, primitiveMesh::pointFaces(), Foam::reduce(), Foam::returnReduce(), set(), UList< T >::size(), syncTools::swapBoundaryCellList(), and Foam::Zero.
Foam::labelList decompose (const polyMesh & mesh, const scalarField & cWeights) const
Decompose a mesh.
Apply all constraints from decomposeParDict ('preserveFaceZones' etc). Calls either
no constraints, empty weights: decompose(mesh, cellCentres())
no constraints, set weights: decompose(mesh, cellCentres(), cellWeights)
valid constraints: decompose(mesh, cellToRegion, regionPoints, regionWeights)
Definition at line 1321 of file decompositionMethod.C.
Member Data Documentation
const dictionary& decompDict_ protected
Top-level decomposition dictionary (eg, decomposeParDict)
Definition at line 99 of file decompositionMethod.H.
const dictionary& decompRegionDict_ protected
Region-specific decomposition dictionary information.
Definition at line 104 of file decompositionMethod.H.
label nDomains_ protected
Number of domains for the decomposition.
Definition at line 109 of file decompositionMethod.H.
PtrList<decompositionConstraint> constraints_ protected
Optional constraints.
Definition at line 114 of file decompositionMethod.H.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompositionMethods/decompositionMethod/decompositionMethod.H
src/parallel/decompose/decompositionMethods/decompositionMethod/decompositionMethod.C