OpenFOAM: Vector2D< Cmpt > Class Template Reference
Vector2D< Cmpt > Class Template Reference
Templated 2D Vector derived from VectorSpace adding construction from 2 components, element access using x() and y() member functions and the inner-product (dot-product).
Public Types
enum components { X, Y }
Component labeling enumeration.
typedef Vector2D< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
typedef VectorSpace< Vector2D
< Cmpt >, Cmpt, Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
typedef Cmpt magType
Magnitude type.
typedef Cmpt * iterator
Random access iterator for traversing VectorSpace.
typedef const Cmpt * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
Vector2D ()
Construct null.
Vector2D (const Foam::zero)
Construct initialized to zero.
Vector2D (const VectorSpace< Vector2D< Cmpt >, Cmpt, 2 > &vs)
Copy construct from VectorSpace of the same rank.
Vector2D (const Cmpt &vx, const Cmpt &vy)
Construct from two components.
Vector2D (Istream &is)
Construct from Istream.
const Cmpt & x () const
Access to the vector x component.
const Cmpt & y () const
Access to the vector y component.
Cmpt & x ()
Access to the vector x component.
Cmpt & y ()
Access to the vector y component.
Vector2D< Cmpt > & normalise ()
Normalise the vector by its magnitude.
scalar perp (const Vector2D< Cmpt > &b) const
Perp dot product (dot product with perpendicular vector)
Public Member Functions inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Return const pointer to the first data element.
Cmpt * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< Vector2D< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Static Public Attributes
static constexpr direction rank = 1
Rank of Vector2D is 1.
Static Public Attributes inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Vector2D< Cmpt > zero
static const Vector2D< Cmpt > one
static const Vector2D< Cmpt > max
static const Vector2D< Cmpt > min
static const Vector2D< Cmpt > rootMax
static const Vector2D< Cmpt > rootMin
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Vector2D< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< Vector2D< Cmpt >, Cmpt, 2 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Detailed Description
template<class Cmpt>
class Foam::Vector2D< Cmpt >
Templated 2D Vector derived from VectorSpace adding construction from 2 components, element access using x() and y() member functions and the inner-product (dot-product).
Source files
Vector2D.H
Vector2DI.H
Definition at line 51 of file Vector2D.H.
Member Typedef Documentation
typedef Vector2D<label> labelType
Equivalent type of labels used for valid component indexing.
Definition at line 61 of file Vector2D.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
X
Y
Definition at line 75 of file Vector2D.H.
Constructor & Destructor Documentation
Vector2D () inline
Construct null.
Definition at line 25 of file Vector2DI.H.
Vector2D (const Foam::zero) inline
Construct initialized to zero.
Definition at line 30 of file Vector2DI.H.
Vector2D (const VectorSpace< Vector2D< Cmpt >, Cmpt, 2 > & vs) inline
Copy construct from VectorSpace of the same rank.
Definition at line 38 of file Vector2DI.H.
Vector2D (const Cmpt & vx, const Cmpt & vy) inline
Construct from two components.
Definition at line 47 of file Vector2DI.H.
Vector2D (Istream & is) inline
Construct from Istream.
Definition at line 55 of file Vector2DI.H.
References Y.
Member Function Documentation
const Cmpt & x () const inline
Access to the vector x component.
Definition at line 64 of file Vector2DI.H.
Referenced by Foam::operator&(), Vector2D< Cmpt >::perp(), SymmTensor2D< Cmpt >::T(), and CV2D::toPoint3D().
const Cmpt & y () const inline
Access to the vector y component.
Definition at line 71 of file Vector2DI.H.
Referenced by Foam::operator&(), Vector2D< Cmpt >::perp(), SymmTensor2D< Cmpt >::T(), and CV2D::toPoint3D().
Cmpt & x () inline
Access to the vector x component.
Definition at line 78 of file Vector2DI.H.
References Y.
Cmpt & y () inline
Access to the vector y component.
Definition at line 85 of file Vector2DI.H.
Foam::Vector2D< Cmpt > & normalise () inline
Normalise the vector by its magnitude.
Definition at line 92 of file Vector2DI.H.
References Y.
scalar perp (const Vector2D< Cmpt > & b) const inline
Perp dot product (dot product with perpendicular vector)
Definition at line 125 of file Vector2DI.H.
References Vector2D< Cmpt >::x(), and Vector2D< Cmpt >::y().
Referenced by line< Point, PointRef >::nearestDist().
Member Data Documentation
constexpr direction rank = 1 static
Rank of Vector2D is 1.
Definition at line 69 of file Vector2D.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/Vector2D/Vector2D.H
src/OpenFOAM/primitives/Vector2D/Vector2DI.H