OpenFOAM: gradScheme< Type > Class Template Reference
gradScheme< Type > Class Template Reference abstract
Abstract base class for finite area calculus gradient schemes.
Public Member Functions
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const faMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< typename outerProduct
< vector, Type >::type,
faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &) const =0
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< gradScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type>
class Foam::fa::gradScheme< Type >
Abstract base class for finite area calculus gradient schemes.
Source files
faGradScheme.H
faGradScheme.C
faGradSchemes.C
Definition at line 59 of file faGradScheme.H.
Constructor & Destructor Documentation
gradScheme (const faMesh & mesh) inline
Construct from mesh.
Definition at line 100 of file faGradScheme.H.
~gradScheme () virtual
Destructor.
Definition at line 82 of file faGradScheme.C.
Member Function Documentation
declareRunTimeSelectionTable (tmp , gradScheme< Type > , Istream , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< gradScheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Return a pointer to a new gradScheme created on freestore.
Definition at line 39 of file faGradScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
Referenced by Foam::fac::grad(), and Foam::fac::ngrad().
const faMesh& mesh () const inline
Return mesh reference.
Definition at line 129 of file faGradScheme.H.
Referenced by gaussGrad< Type >::gaussGrad().
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > grad (const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Calculate and return the grad of the given field.
Implemented in gaussGrad< Type >, faceLimitedGrad< Type >, edgeLimitedGrad< Type >, and leastSquaresFaGrad< Type >.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/gradSchemes/faGradScheme/faGradScheme.H
src/finiteArea/finiteArea/gradSchemes/faGradScheme/faGradScheme.C