OpenFOAM: applications/utilities/postProcessing/miscellaneous/postChannel/collapse.H File Reference
collapse.H File Reference
Functions
fileName path (UMean.rootPath()/UMean.caseName()/"graphs"/UMean.instance())
mkDir (path)
scalarField UMeanXvalues (channelIndexing.collapse(UMean.component(vector::X)()))
scalarField UMeanYvalues (channelIndexing.collapse(UMean.component(vector::Y)()))
scalarField UMeanZvalues (channelIndexing.collapse(UMean.component(vector::Z)()))
scalarField RxxValues (channelIndexing.collapse(Rxx))
scalarField RyyValues (channelIndexing.collapse(Ryy))
scalarField RzzValues (channelIndexing.collapse(Rzz))
scalarField RxyValues (channelIndexing.collapse(Rxy, true))
scalarField pPrime2MeanValues (channelIndexing.collapse(pPrime2Mean))
scalarField urmsValues (sqrt(mag(RxxValues)))
scalarField vrmsValues (sqrt(mag(RyyValues)))
scalarField wrmsValues (sqrt(mag(RzzValues)))
scalarField kValues (0.5 *(sqr(urmsValues)+sqr(vrmsValues)+sqr(wrmsValues)))
makeGraph (y, UMeanXvalues,"Uf", path, gFormat)
makeGraph (y, urmsValues,"u", path, gFormat)
makeGraph (y, vrmsValues,"v", path, gFormat)
makeGraph (y, wrmsValues,"w", path, gFormat)
makeGraph (y, RxyValues,"uv", path, gFormat)
makeGraph (y, kValues,"k", path, gFormat)
makeGraph (y, pPrime2MeanValues,"pPrime2Mean", path, gFormat)
Variables
const scalarField & y = channelIndexing.y()
Function Documentation
fileName path (UMean. rootPath)/UMean.caseName()/"graphs"/UMean.instance()
Referenced by distributedTriSurfaceMesh::distribute(), TimePaths::findClosestTimeIndex(), IOobject::good(), Foam::home(), fileName::name(), oldCyclicPolyPatch::order(), Time::startTimeIndex(), TimePaths::systemPath(), Foam::writeCellGraph(), and medialAxisMeshMover::~medialAxisMeshMover().
mkDir (path)
scalarField UMeanXvalues (channelIndexing. collapseUMean.component(vector::X)())
scalarField UMeanYvalues (channelIndexing. collapseUMean.component(vector::Y)())
scalarField UMeanZvalues (channelIndexing. collapseUMean.component(vector::Z)())
scalarField RxxValues (channelIndexing. collapseRxx)
scalarField RyyValues (channelIndexing. collapseRyy)
scalarField RzzValues (channelIndexing. collapseRzz)
scalarField RxyValues (channelIndexing. collapseRxy, true)
scalarField pPrime2MeanValues (channelIndexing. collapsepPrime2Mean)
scalarField urmsValues (sqrt(mag(RxxValues)))
scalarField vrmsValues (sqrt(mag(RyyValues)))
scalarField wrmsValues (sqrt(mag(RzzValues)))
scalarField kValues (0.5 * sqr(urmsValues)+sqr(vrmsValues)+sqr(wrmsValues))
makeGraph (y , UMeanXvalues , "Uf" , path , gFormat)
makeGraph (y , urmsValues , "u" , path , gFormat)
makeGraph (y , vrmsValues , "v" , path , gFormat)
makeGraph (y , wrmsValues , "w" , path , gFormat)
makeGraph (y , RxyValues , "uv" , path , gFormat)
makeGraph (y , kValues , "k" , path , gFormat)
makeGraph (y , pPrime2MeanValues , "pPrime2Mean" , path , gFormat)
Variable Documentation
const scalarField& y = channelIndexing.y()
Definition at line 46 of file collapse.H.