OpenFOAM: applications/solvers/combustion/fireFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phig ("phig",-rhorAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA)+MRF.zeroFilter(rhorAUf *fvc::ddtCorr(rho, U, phi)))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
p_rghEqn solve (mesh.solver(p_rgh.select(pimple.finalInnerIter())))
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
rho = thermo.rho()
U = HbyA + rAU*fvc::reconstruct((p_rghEqn.flux() + phig)/rhorAUf)
p = p_rgh + rho*gh + pRef
K = 0.5*magSqr(U)
Function Documentation
volScalarField rAU (1.0/UEqn. A())
surfaceScalarField rhorAUf ("rhorAUf" , fvc:: interpolaterho *rAU)
Referenced by for(), and if().
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phig ("phig" , -rhorAUf *ghf *fvc:: snGradrho)*mesh.magSf()
Referenced by for(), and if().
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA)+MRF.zeroFilter(rhorAUf *fvc::ddtCorr(rho, U, phi)))+ phig)
MRF makeRelative (fvc:: interpolaterho, phiHbyA)
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
p_rghEqn solve (mesh. solverp_rgh.select(pimple.finalInnerIter()))
U correctBoundaryConditions ()
fvOptions correct (U)
Variable Documentation
rho = thermo.rho()
Definition at line 1 of file pEqn.H.
phase U = HbyA + rAU*fvc::reconstruct((p_rghEqn.flux() + phig)/rhorAUf)
Definition at line 44 of file pEqn.H.
Referenced by buoyantKEpsilon< BasicTurbulenceModel >::buoyantKEpsilon(), Foam::calc_rhoU(), continuousGasKEpsilon< BasicTurbulenceModel >::continuousGasKEpsilon(), continuousGasKEqn< BasicTurbulenceModel >::continuousGasKEqn(), DESModel< BasicTurbulenceModel >::DESModel(), for(), if(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), wallBoundedStreamLineParticle::interpolateFields(), DispersionRASModel< CloudType >::kModel(), kOmegaSSTSato< BasicTurbulenceModel >::kOmegaSSTSato(), LaheyKEpsilon< BasicTurbulenceModel >::LaheyKEpsilon(), LESeddyViscosity< BasicTurbulenceModel >::LESeddyViscosity(), Maxwell< BasicTurbulenceModel >::Maxwell(), mixtureKEpsilon< BasicTurbulenceModel >::mixtureKEpsilon(), wallBoundedStreamLineParticle::move(), Foam::compressible::New(), Foam::incompressible::New(), viscosityModel::New(), laminarModel< BasicTurbulenceModel >::New(), RASModel< BasicTurbulenceModel >::New(), LESModel< BasicTurbulenceModel >::New(), NicenoKEqn< BasicTurbulenceModel >::NicenoKEqn(), NullMRF::relative(), SmagorinskyZhang< BasicTurbulenceModel >::SmagorinskyZhang(), Stokes< BasicTurbulenceModel >::Stokes(), and phasePair::Ur().
p = p_rgh + rho*gh + pRef
Definition at line 50 of file pEqn.H.
K = 0.5*magSqr(U)
Definition at line 55 of file pEqn.H.