OpenFOAM: applications/solvers/compressible/rhoCentralFoam/setRDeltaT.H File Reference
setRDeltaT.H File Reference
Functions
scalar rDeltaTSmoothingCoeff (runTime.controlDict().lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02))
rDeltaT ref ()
rDeltaT correctBoundaryConditions ()
Function Documentation
scalar rDeltaTSmoothingCoeff (runTime. controlDict).lookupOrDefault< scalar >("rDeltaTSmoothingCoeff", 0.02)
pEqnComp2 ref ()
Initial value:
= max
        (
            rDeltaT(),
            fvc::surfaceSum(mag(phid))()()
            /((2*maxCo)*mesh.V()*psi())
        )
Referenced by Foam::fam::div(), Foam::fac::div(), Foam::fvc::div(), Foam::fac::grad(), Foam::fac::ndiv(), and Foam::fac::ngrad().
rDeltaT correctBoundaryConditions ()