OpenFOAM: applications/solvers/compressible/rhoSimpleFoam/rhoPorousSimpleFoam/UEqn.H File Reference
UEqn.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > tUEqn (fvm::div(phi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U)==)
UEqn relax ()
if (pressureImplicitPorosity)
fvOptions constrain (UEqn)
solve (UEqn==-fvc::grad(p))
fvOptions correct (U)
trAU ref ().rename("rAU")
Variables
fvVectorMatrix & UEqn = tUEqn.ref()
tmp< volScalarField > trAU = 1.0/UEqn.A()
tmp< volTensorField > trTU
else
Function Documentation
MRF correctBoundaryVelocity (U)
tmp<fvVectorMatrix> tUEqn (fvm:: divphi, U)+MRF.DDt(rho, U)+turbulence->divDevRhoReff(U = =)
UEqn relax ()
if (pressureImplicitPorosity)
Definition at line 24 of file UEqn.H.
References fvOptions, Foam::fac::grad(), Foam::I, Foam::inv(), nUCorr, p, pZones(), trTU, and U.
fvOptions constrain (UEqn)
solve (UEqn = =-fvc::grad(p))
fvOptions correct (U)
trAU ref ()
Variable Documentation
fvVectorMatrix& UEqn = tUEqn.ref()
Definition at line 13 of file UEqn.H.
trAU = 1.0/UEqn.A()
Definition at line 21 of file UEqn.H.
tmp<volTensorField> trTU
Definition at line 22 of file UEqn.H.
Referenced by if().
else
Initial value:
{
        pZones.addResistance(UEqn)
Definition at line 44 of file UEqn.H.