OpenFOAM: applications/utilities/preProcessing/createBoxTurb/createBlockMesh.H File Reference
createBlockMesh.H File Reference
Functions
block b (cellShape(hex, identity(8), false), pointField({point(0, 0, 0), point(L.x(), 0, 0), point(L.x(), L.y(), 0), point(0, L.y(), 0), point(0, 0, L.z()), point(L.x(), 0, L.z()), point(L.x(), L.y(), L.z()), point(0, L.y(), L.z())}), blockEdgeList(), blockFaceList(), N, List< gradingDescriptors >(12))
Info<< "Creating cells"<< endl;List
< FixedList< label, 8 > > bCells (b.cells())
cellShapes setSize (bCells.size())
forAll (cellShapes, celli)
forAll (boundaryDicts, patchi)
Variables
const cellModel & hex = cellModel::ref(cellModel::HEX)
cellShapeList cellShapes
faceListList boundary
pointField points
Info<< "Creating boundary
faces"<< endl;boundary.setSize(b.boundaryPatches().size());forAll(boundary,
patchi){faceList faces(b.boundaryPatches()[patchi].size());forAll(faces,
facei){faces[facei]=face(b.boundaryPatches()[patchi][facei]);}boundary[patchi].transfer(faces);}points.transfer(const_cast
< pointField & >b.points()));}Info
<< "Creating patch
dictionaries"<< endl;wordList
patchNames(boundary.size());forAll(patchNames,
patchi){patchNames[patchi]="patch"+Foam::name(patchi);}PtrList
< dictionary > boundaryDicts (boundary.size())
Function Documentation
block b (cellShape(hex, identity(8), false) , pointField({point(0, 0, 0), point(L.x(), 0, 0), point(L.x(), L.y(), 0), point(0, L.y(), 0), point(0, 0, L.z()), point(L.x(), 0, L.z()), point(L.x(), L.y(), L.z()), point(0, L.y(), L.z())}) , blockEdgeList() , blockFaceList() , N , List< gradingDescriptors > 12)
Info<< "Creating cells" << endl; List<FixedList<label, 8> > bCells (b. cells())
Referenced by forAll().
cellShapes setSize (bCells. size())
forAll (cellShapes , celli)
Definition at line 35 of file createBlockMesh.H.
References bCells(), cellShapes, hex, and labelList().
forAll (boundaryDicts , patchi)
Definition at line 65 of file createBlockMesh.H.
References boundaryDicts, and Foam::name().
Variable Documentation
const cellModel& hex = cellModel::ref(cellModel::HEX)
Definition at line 1 of file createBlockMesh.H.
Referenced by forAll().
cellShapeList cellShapes
Definition at line 3 of file createBlockMesh.H.
Referenced by forAll(), and if().
faceListList boundary
Definition at line 4 of file createBlockMesh.H.
Referenced by for(), and forAll().
pointField points
Definition at line 5 of file createBlockMesh.H.
Info<< "Creating boundary faces" << endl; boundary.setSize(b.boundaryPatches().size()); forAll(boundary, patchi) { faceList faces(b.boundaryPatches()[patchi].size()); forAll(faces, facei) { faces[facei] = face(b.boundaryPatches()[patchi][facei]); } boundary[patchi].transfer(faces); } points.transfer(const_cast<pointField&>b.points()));}Info<< "Creating patch dictionaries" << endl;wordList patchNames(boundary.size());forAll(patchNames, patchi){ patchNames[patchi] = "patch" + Foam::name(patchi);}PtrList<dictionary> boundaryDicts(boundary.size())
Definition at line 64 of file createBlockMesh.H.
Referenced by forAll().