OpenFOAM: applications/solvers/finiteArea/liquidFilmFoam/createFvFields.H File Reference
createFvFields.H File Reference
Functions
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
volScalarField H (IOobject("H", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
volSurfaceMapping vsm (aMesh)
Function Documentation
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
volScalarField H (IOobject("H", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
Referenced by hConstThermo< EquationOfState >::Hc(), hRefConstThermo< EquationOfState >::Hc(), and hPolynomialThermo< EquationOfState, PolySize >::Hs().
volSurfaceMapping vsm (aMesh)