OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/createMDFields.H File Reference
createMDFields.H File Reference
Functions
List< scalarField > allSpeciesN_RU (molecules.potential().nIds(),)
List< scalarField > allSpeciesM_RU (molecules.potential().nIds(),)
List< vectorField > allSpeciesVelocitySum_RU (molecules.potential().nIds(),)
List< scalarField > allSpeciesVelocityMagSquaredSum_RU (molecules.potential().nIds(),)
Info<< nl<< "Creating fields."
<< endl;PtrList
< volScalarField > allSpeciesRhoN (molecules.potential().nIds())
forAll (allSpeciesRhoN, rN)
Info<< " Creating total number
density field"<< endl;volScalarField
totalRhoN(IOobject("rhoN_total",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE), mesh,
dimless/dimVolume,"zeroGradient");totalRhoN.primitiveFieldRef()=0;totalRhoN.correctBoundaryConditions();PtrList
< volScalarField > allSpeciesRhoM (molecules.potential().nIds())
forAll (allSpeciesRhoM, rM)
Info<< " Creating total mass
density field"<< endl;volScalarField
totalRhoM(IOobject("rhoM_total",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE), mesh,
dimMass/dimVolume,"zeroGradient");totalRhoM.primitiveFieldRef()=0;totalRhoM.correctBoundaryConditions();PtrList
< volVectorField > allSpeciesVelocity (molecules.potential().nIds())
forAll (allSpeciesVelocity, v)
Info<< " Creating total
velocity field"<< endl;volVectorField
totalVelocity(IOobject("velocity_total",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE), mesh,);PtrList
< volScalarField > allSpeciesTemperature (molecules.potential().nIds())
forAll (allSpeciesTemperature, t)
Info<< " Creating total
temperature field"<< endl;volScalarField
totalTemperature(IOobject("temperature_total",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE), mesh,
dimTemperature,"zeroGradient");totalTemperature.primitiveFieldRef()=0;totalTemperature.correctBoundaryConditions();PtrList
< volScalarField > allSpeciesMeanKE (molecules.potential().nIds())
forAll (allSpeciesMeanKE, mKE)
Function Documentation
List<scalarField> allSpeciesN_RU (molecules. potential).nIds()
Referenced by forAll().
List<scalarField> allSpeciesM_RU (molecules. potential).nIds()
List<vectorField> allSpeciesVelocitySum_RU (molecules. potential).nIds()
List<scalarField> allSpeciesVelocityMagSquaredSum_RU (molecules. potential).nIds()
Info<< nl << "Creating fields." << endl;PtrList<volScalarField> allSpeciesRhoN (molecules. potential).nIds()
Referenced by forAll().
forAll (allSpeciesRhoN , rN)
Definition at line 40 of file createMDFields.H.
References allSpeciesRhoN(), Foam::dimless, Foam::dimVolume, Foam::endl(), Foam::Info, mesh, and runTime.
Info<< " Creating total number density field" << endl;volScalarField totalRhoN(IOobject ("rhoN_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimless/dimVolume, "zeroGradient");totalRhoN.primitiveFieldRef() = 0;totalRhoN.correctBoundaryConditions();PtrList<volScalarField> allSpeciesRhoM (molecules. potential).nIds()
Referenced by forAll().
forAll (allSpeciesRhoM , rM)
Definition at line 95 of file createMDFields.H.
References allSpeciesRhoM(), Foam::dimMass, Foam::dimVolume, Foam::endl(), Foam::Info, mesh, and runTime.
Info<< " Creating total mass density field" << endl;volScalarField totalRhoM(IOobject ("rhoM_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimMass/dimVolume, "zeroGradient");totalRhoM.primitiveFieldRef() = 0;totalRhoM.correctBoundaryConditions();PtrList<volVectorField> allSpeciesVelocity (molecules. potential).nIds()
Referenced by forAll().
forAll (allSpeciesVelocity , v)
Definition at line 150 of file createMDFields.H.
References allSpeciesVelocity(), Foam::dimVelocity, Foam::endl(), Foam::Info, mesh, runTime, and Foam::Zero.
Info<< " Creating total velocity field" << endl;volVectorField totalVelocity(IOobject ("velocity_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,);PtrList<volScalarField> allSpeciesTemperature (molecules. potential).nIds()
Referenced by forAll().
forAll (allSpeciesTemperature , t)
Definition at line 220 of file createMDFields.H.
References allSpeciesTemperature(), Foam::dimTemperature, Foam::endl(), Foam::Info, mesh, and runTime.
Info<< " Creating total temperature field" << endl;volScalarField totalTemperature(IOobject ("temperature_total", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh, dimTemperature, "zeroGradient");totalTemperature.primitiveFieldRef() = 0;totalTemperature.correctBoundaryConditions();PtrList<volScalarField> allSpeciesMeanKE (molecules. potential).nIds()
Referenced by forAll().
forAll (allSpeciesMeanKE , mKE)
Definition at line 276 of file createMDFields.H.
References allSpeciesMeanKE(), Foam::endl(), Foam::Info, mesh, and runTime.