OpenFOAM: applications/solvers/multiphase/driftFluxFoam/alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
if (MULESCorr)
for (int aCorr=0;aCorr< nAlphaCorr;aCorr++)
if (alphaApplyPrevCorr &&MULESCorr)
Variables
alpha2 = 1.0 - alpha1
Function Documentation
word alpharScheme ("div(phirb,alpha)")
Referenced by for().
if (MULESCorr)
Definition at line 5 of file alphaEqn.H.
References alpha1, alphaApplyPrevCorr(), alphaPhi(), correct, Foam::endl(), Foam::Info, Foam::max(), mesh, Foam::min(), mixture, phi, solve(), talphaPhiCorr0, value(), and Foam::vtk::Tools::zeroField().
for ()
Definition at line 50 of file alphaEqn.H.
References alpha1, alpha10(), alphaPhi(), alpharScheme(), correct, Foam::MULES::explicitSolve(), Foam::fvc::flux(), mixture, MULESCorr(), phi, phir(), and Foam::vtk::Tools::zeroField().
if (alphaApplyPrevCorr && MULESCorr)
Definition at line 110 of file alphaEqn.H.
References alphaPhi(), and talphaPhiCorr0.
Variable Documentation
alpha2 = 1.0 - alpha1
Definition at line 115 of file alphaEqn.H.