OpenFOAM: src/meshTools/triSurface/triSurfaceTools/geompack/geompack.C File Reference
geompack.C File Reference
Macros
#define LEVEL_MAX 25
#define INCX 5
#define INCX 10
#define TIME_SIZE 29
#define TIME_SIZE 29
#define DIM_NUM 2
#define DIM_NUM 2
Functions
double d_epsilon (void)
double d_max (double x, double y)
double d_min (double x, double y)
void d2vec_part_quick_a (int n, double a[], int *l, int *r)
void d2vec_permute (int n, double a[], int p[])
int * d2vec_sort_heap_index_a (int n, double a[])
void d2vec_sort_quick_a (int n, double a[])
int diaedg (double x0, double y0, double x1, double y1, double x2, double y2, double x3, double y3)
void dmat_transpose_print (int m, int n, double a[], const char *title)
void dmat_transpose_print_some (int m, int n, double a[], int ilo, int jlo, int ihi, int jhi, const char *title)
void dmat_uniform (int m, int n, double b, double c, int *seed, double r[])
int dtris2 (int point_num, double point_xy[], int *tri_num, int tri_vert[], int tri_nabe[])
bool dvec_eq (int n, double a1[], double a2[])
bool dvec_gt (int n, double a1[], double a2[])
bool dvec_lt (int n, double a1[], double a2[])
void dvec_print (int n, double a[], const char *title)
void dvec_swap (int n, double a1[], double a2[])
int i_max (int i1, int i2)
int i_min (int i1, int i2)
int i_modp (int i, int j)
int i_sign (int i)
int i_wrap (int ival, int ilo, int ihi)
void imat_transpose_print (int m, int n, int a[], const char *title)
void imat_transpose_print_some (int m, int n, int a[], int ilo, int jlo, int ihi, int jhi, const char *title)
void ivec_heap_d (int n, int a[])
int * ivec_indicator (int n)
void ivec_sort_heap_a (int n, int a[])
void ivec_sorted_unique (int n, int a[], int *nuniq)
int lrline (double xu, double yu, double xv1, double yv1, double xv2, double yv2, double dv)
bool perm_check (int n, int p[])
void perm_inv (int n, int p[])
int * points_delaunay_naive_2d (int n, double p[], int *ntri)
int s_len_trim (const char *s)
int swapec (int i, int *top, int *btri, int *bedg, int point_num, double point_xy[], int tri_num, int tri_vert[], int tri_nabe[], int stack[])
void timestamp (void)
char * timestring (void)
double * triangle_circumcenter_2d (double t[])
bool triangulation_plot_eps (const char *file_out_name, int g_num, double g_xy[], int tri_num, int nod_tri[])
void triangulation_print (int point_num, double xc[], int tri_num, int tri_vert[], int tri_nabe[])
void vbedg (double x, double y, int point_num, double point_xy[], int tri_num, int tri_vert[], int tri_nabe[], int *ltri, int *ledg, int *rtri, int *redg)
Macro Definition Documentation
#define LEVEL_MAX 25
Referenced by d2vec_sort_quick_a().
#define INCX 5
Referenced by dmat_transpose_print_some(), and imat_transpose_print_some().
#define INCX 10
#define TIME_SIZE 29
Referenced by timestamp(), and timestring().
#define TIME_SIZE 29
#define DIM_NUM 2
Referenced by triangle_circumcenter_2d(), and triangulation_print().
#define DIM_NUM 2
Function Documentation
double d_epsilon (void)
Definition at line 15 of file geompack.C.
Referenced by diaedg(), and dtris2().
double d_max (double x, double y)
Definition at line 57 of file geompack.C.
References x, and y.
Referenced by diaedg(), dtris2(), lrline(), and triangulation_plot_eps().
double d_min (double x, double y)
Definition at line 91 of file geompack.C.
References x, and y.
Referenced by triangulation_plot_eps().
void d2vec_part_quick_a (int n, double a[], int * l, int * r)
Definition at line 125 of file geompack.C.
References dvec_eq(), dvec_gt(), dvec_lt(), dvec_swap(), Foam::exit(), i, j, and n.
Referenced by d2vec_sort_quick_a().
void d2vec_permute (int n, double a[], int p[])
Definition at line 255 of file geompack.C.
References Foam::exit(), i, n, and perm_check().
Referenced by dtris2().
int* d2vec_sort_heap_index_a (int n, double a[])
Definition at line 380 of file geompack.C.
References i, ivec_indicator(), j, and n.
Referenced by dtris2().
void d2vec_sort_quick_a (int n, double a[])
Definition at line 510 of file geompack.C.
References d2vec_part_quick_a(), Foam::exit(), LEVEL_MAX, and n.
int diaedg (double x0, double y0, double x1, double y1, double x2, double y2, double x3, double y3)
Definition at line 628 of file geompack.C.
References d_epsilon(), d_max(), s, value(), and Foam::y0().
Referenced by swapec().
void dmat_transpose_print (int m, int n, double a[], const char * title)
Definition at line 745 of file geompack.C.
References dmat_transpose_print_some().
Referenced by triangulation_print().
void dmat_transpose_print_some (int m, int n, double a[], int ilo, int jlo, int ihi, int jhi, const char * title)
Definition at line 776 of file geompack.C.
References i, i_max(), i_min(), INCX, j, s_len_trim(), and Foam::setw().
Referenced by dmat_transpose_print().
void dmat_uniform (int m, int n, double b, double c, int * seed, double r[])
Definition at line 862 of file geompack.C.
References Foam::constant::physicoChemical::b, i, j, k, and n.
int dtris2 (int point_num, double point_xy[], int * tri_num, int tri_vert[], int tri_nabe[])
Definition at line 949 of file geompack.C.
References d2vec_permute(), d2vec_sort_heap_index_a(), d_epsilon(), d_max(), Foam::constant::electromagnetic::e, i, j, k, lrline(), n, perm_inv(), swapec(), and vbedg().
bool dvec_eq (int n, double a1[], double a2[])
Definition at line 1297 of file geompack.C.
References i, and n.
Referenced by d2vec_part_quick_a().
bool dvec_gt (int n, double a1[], double a2[])
Definition at line 1338 of file geompack.C.
References i, and n.
Referenced by d2vec_part_quick_a().
bool dvec_lt (int n, double a1[], double a2[])
Definition at line 1392 of file geompack.C.
References i, and n.
Referenced by d2vec_part_quick_a().
void dvec_print (int n, double a[], const char * title)
Definition at line 1445 of file geompack.C.
References i, s_len_trim(), and Foam::setw().
void dvec_swap (int n, double a1[], double a2[])
Definition at line 1490 of file geompack.C.
References i, and n.
Referenced by d2vec_part_quick_a().
int i_max (int i1, int i2)
Definition at line 1527 of file geompack.C.
Referenced by dmat_transpose_print_some(), i_wrap(), and imat_transpose_print_some().
int i_min (int i1, int i2)
Definition at line 1562 of file geompack.C.
Referenced by dmat_transpose_print_some(), i_wrap(), and imat_transpose_print_some().
int i_modp (int i, int j)
Definition at line 1597 of file geompack.C.
References Foam::exit(), j, and value().
Referenced by i_wrap().
int i_sign (int i)
Definition at line 1672 of file geompack.C.
Referenced by perm_inv().
int i_wrap (int ival, int ilo, int ihi)
Definition at line 1711 of file geompack.C.
References i_max(), i_min(), i_modp(), and value().
Referenced by swapec(), triangulation_plot_eps(), triangulation_print(), and vbedg().
void imat_transpose_print (int m, int n, int a[], const char * title)
Definition at line 1783 of file geompack.C.
References imat_transpose_print_some().
Referenced by triangulation_print().
void imat_transpose_print_some (int m, int n, int a[], int ilo, int jlo, int ihi, int jhi, const char * title)
Definition at line 1816 of file geompack.C.
References i, i_max(), i_min(), INCX, j, s_len_trim(), and Foam::setw().
Referenced by imat_transpose_print().
void ivec_heap_d (int n, int a[])
Definition at line 1913 of file geompack.C.
References i.
Referenced by ivec_sort_heap_a().
int* ivec_indicator (int n)
Definition at line 2037 of file geompack.C.
References i, and n.
Referenced by d2vec_sort_heap_index_a().
void ivec_sort_heap_a (int n, int a[])
Definition at line 2074 of file geompack.C.
References ivec_heap_d().
Referenced by triangulation_print().
void ivec_sorted_unique (int n, int a[], int * nuniq)
Definition at line 2148 of file geompack.C.
References i, and n.
Referenced by triangulation_print().
int lrline (double xu, double yu, double xv1, double yv1, double xv2, double yv2, double dv)
Definition at line 2199 of file geompack.C.
References d_max(), Foam::sqrt(), and value().
Referenced by dtris2(), and vbedg().
bool perm_check (int n, int p[])
Definition at line 2284 of file geompack.C.
References found, i, and n.
Referenced by d2vec_permute(), and perm_inv().
void perm_inv (int n, int p[])
Definition at line 2342 of file geompack.C.
References Foam::exit(), i, i_sign(), n, and perm_check().
Referenced by dtris2().
int* points_delaunay_naive_2d (int n, double p[], int * ntri)
Definition at line 2429 of file geompack.C.
References Foam::BitOps::count(), i, j, k, n, and Foam::yn().
int s_len_trim (const char * s)
Definition at line 2564 of file geompack.C.
References n, and s.
Referenced by dmat_transpose_print_some(), dvec_print(), and imat_transpose_print_some().
int swapec (int i, int * top, int * btri, int * bedg, int point_num, double point_xy[], int tri_num, int tri_vert[], int tri_nabe[], int stack[])
Definition at line 2608 of file geompack.C.
References Foam::constant::physicoChemical::b, c(), diaedg(), Foam::constant::electromagnetic::e, f(), i, i_wrap(), s, x, and y.
Referenced by dtris2().
void timestamp (void)
Definition at line 2886 of file geompack.C.
References TIME_SIZE.
char* timestring (void)
Definition at line 2933 of file geompack.C.
References s, and TIME_SIZE.
Referenced by triangulation_plot_eps().
double* triangle_circumcenter_2d (double t[])
Definition at line 2976 of file geompack.C.
References DIM_NUM.
bool triangulation_plot_eps (const char * file_out_name, int g_num, double g_xy[], int tri_num, int nod_tri[])
Definition at line 3049 of file geompack.C.
References d_max(), d_min(), Foam::constant::electromagnetic::e, g, i_wrap(), j, k, and timestring().
void triangulation_print (int point_num, double xc[], int tri_num, int tri_vert[], int tri_nabe[])
Definition at line 3276 of file geompack.C.
References DIM_NUM, dmat_transpose_print(), i, i_wrap(), imat_transpose_print(), ivec_sort_heap_a(), ivec_sorted_unique(), j, k, s, and Foam::setw().
void vbedg (double x, double y, int point_num, double point_xy[], int tri_num, int tri_vert[], int tri_nabe[], int * ltri, int * ledg, int * rtri, int * redg)
Definition at line 3446 of file geompack.C.
References Foam::constant::physicoChemical::b, Foam::constant::electromagnetic::e, i_wrap(), and lrline().
Referenced by dtris2().