OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputLagrangian.H File Reference
gmvOutputLagrangian.H File Reference
Functions
for (const scalar &val:fld)
forAll (fld, n)
Variables
gmvFile<< "tracers "
<< particles.size()<< nl;for(const
passiveParticle &p:particles){gmvFile
<< p.position().x()
<< ' ';}gmvFile<< nl;for(const
passiveParticle &p:particles){gmvFile
<< p.position().y()
<< ' ';}gmvFile<< nl;for(const
passiveParticle &p:particles){gmvFile
<< p.position().z()
<< ' ';}gmvFile<< nl;for(const
word
&name:lagrangianScalarNames){IOField
< scalar > fld (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Function Documentation
for (const scalar &val:fld)
Definition at line 39 of file gmvOutputLagrangian.H.
References Foam::val.
forAll (fld , n)
Definition at line 68 of file gmvOutputLagrangian.H.
References fld, and n.
Variable Documentation
gmvFile<< nl; }}for (const word& name : lagrangianVectorNames){ IOField<vector> fld(IOobject(name,runTime.timeName(),cloud::prefix,mesh,IOobject::MUST_READ,IOobject::NO_WRITE))
Definition at line 23 of file gmvOutputLagrangian.H.
Referenced by geometryCloud::addField(), surface::addField(), windowModel::apply(), PatchFunction1< Type >::autoMap(), cellCellStencil::createField(), nearWallFields::createFields(), mapDistributeBase::distribute(), mapDistribute::distribute(), Foam::evaluateConstraintTypes(), Field< Type >::Field(), parseDriver::field_cellSelection(), for(), forAll(), globalIndex::gather(), distributedTriSurfaceMesh::getField(), if(), isoSurfaceTopo::interpolate(), pointToPointPlanarInterpolation::interpolate(), surfaceInterpolate::interpolateFields(), cyclicACMIFvPatch::neighbFvPatch(), optionAdjointList::operator()(), mapDistribute::transform::operator()(), Foam::operator>>(), parseDriver::pointSize(), foamToVtkReportFields::print(), fvMeshDistribute::printFieldInfo(), mappedPatchBase::readListOrField(), mappedPatchBase::samplePoints(), solutionControl::storePrevIter(), vectorTensorTransform::transform(), updateOp< PrimitivePatchType, Type, TrackingData >::updateOp(), and coalCloudList::UTrans().