OpenFOAM: src/thermophysicalModels/specie/thermo/thermo/HtoEthermo.H File Reference
HtoEthermo.H File Reference
Functions
scalar Cv (const scalar p, const scalar T) const
scalar Es (const scalar p, const scalar T) const
scalar Ea (const scalar p, const scalar T) const
Function Documentation
scalar Cv (const scalar p, const scalar T) const inline
Definition at line 2 of file HtoEthermo.H.
References Cp, and cp.
scalar Es (const scalar p, const scalar T) const inline
Definition at line 17 of file HtoEthermo.H.
References Hs(), and rho.
Referenced by thermo< Thermo, Type >::ea(), eConstThermo< EquationOfState >::Hc(), Hs(), and eRefConstThermo< EquationOfState >::S().
scalar Ea (const scalar p, const scalar T) const inline
Definition at line 32 of file HtoEthermo.H.
References Ha(), and rho.
Referenced by thermo< Thermo, Type >::cp(), thermo< Thermo, Type >::g(), and Ha().