OpenFOAM: applications/solvers/multiphase/interPhaseChangeFoam/alphaEqnSubCycle.H File Reference
alphaEqnSubCycle.H File Reference
Functions
if (icAlpha > 0)
volScalarField divU (fvc::div(phi))
if (nAlphaSubCycles > 1)
Variables
else
Function Documentation
if (icAlpha , 0)
Definition at line 6 of file alphaEqnSubCycle.H.
References icAlpha(), interface(), Foam::fac::interpolate(), Foam::mag(), phic(), and U.
volScalarField divU (fvc:: divphi)
if (nAlphaSubCycles , 1)
Definition at line 14 of file alphaEqnSubCycle.H.
References alpha1, end(), nAlphaSubCycles(), rhoPhi, and runTime.
Variable Documentation
else
Definition at line 32 of file alphaEqnSubCycle.H.