OpenFOAM: applications/solvers/lagrangian/sprayFoam/YEqn.H File Reference
YEqn.H File Reference
Functions
tmp< fv::convectionScheme
< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,Yi_h)")))
volScalarField Yt (0.0 *Y[0])
forAll (Y, i)
Y[inertIndex] max (0.0)
Variables
Qdot = combustion->Qdot()
Y [inertIndex] = scalar(1) - Yt
Function Documentation
tmp<fv::convectionScheme<scalar> > mvConvection (fv::convectionScheme< scalar >:: Newmesh, fields, phi, mesh.divScheme("div(phi,Yi_h)"))
volScalarField Yt (0.0 * Y[0])
forAll (Y , i)
Definition at line 17 of file YEqn.H.
References combustion(), composition, Foam::fac::ddt(), convectionScheme< Type >::fvmDiv(), fvOptions, i, inertIndex, Foam::fac::laplacian(), mesh, mvConvection(), phi, rho, turbulence, Y, and Yt().
Y [inertIndex] max (0. 0)
Variable Documentation
Qdot = combustion->Qdot()
Definition at line 14 of file YEqn.H.
Y[inertIndex] = scalar(1) - Yt
Definition at line 47 of file YEqn.H.