OpenFOAM: applications/solvers/multiphase/twoPhaseEulerFoam/pU/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1)-alphaf1)
volScalarField rAU1 (IOobject::groupName("rAU", phase1.name()), 1.0/(U1Eqn.A()+max(phase1.residualAlpha()-alpha1, scalar(0))*rho1/runTime.deltaT()))
volScalarField rAU2 (IOobject::groupName("rAU", phase2.name()), 1.0/(U2Eqn.A()+max(phase2.residualAlpha()-alpha2, scalar(0))*rho2/runTime.deltaT()))
surfaceScalarField alpharAUf1 (fvc::interpolate(max(alpha1, phase1.residualAlpha())*rAU1))
surfaceScalarField alpharAUf2 (fvc::interpolate(max(alpha2, phase2.residualAlpha())*rAU2))
surfaceScalarField Df1 (fvc::interpolate(rAU1 *(D+phase1.turbulence().pPrime())))
surfaceScalarField Df2 (fvc::interpolate(rAU2 *(D+phase2.turbulence().pPrime())))
if (implicitPhasePressure)
volVectorField F (fluid.F())
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
MRF correctBoundaryFlux (U1, phi1)
MRF correctBoundaryFlux (U2, phi2)
volVectorField HbyA1 (IOobject::groupName("HbyA", phase1.name()), U1)
volVectorField HbyA2 (IOobject::groupName("HbyA", phase2.name()), U2)
surfaceScalarField ghSnGradRho ("ghSnGradRho", ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phig1 (alpharAUf1 *(ghSnGradRho-alphaf2 *fvc::interpolate(rho1-rho2)*(g &mesh.Sf())))
surfaceScalarField phig2 (alpharAUf2 *(ghSnGradRho-alphaf1 *fvc::interpolate(rho2-rho1)*(g &mesh.Sf())))
surfaceScalarField alphaf1Bar (fvc::interpolate(fvc::average(alphaf1)))
surfaceScalarField phiCorrCoeff1 (pos0(alphaf1Bar-0.99))
surfaceScalarField phiCorrCoeff2 (pos0(0.01-alphaf1Bar))
surfaceScalarField phiHbyA2 (IOobject::groupName("phiHbyA", phase2.name()), fvc::flux(HbyA2)+phiCorrCoeff2 *fvc::interpolate(alpha2.oldTime()*rho2.oldTime()*rAU2)*(MRF.absolute(phi2.oldTime())-fvc::flux(U2.oldTime()))/runTime.deltaT()-phiF2()-phig2)
surfaceScalarField rAUKd1 (fvc::interpolate(rAU1 *Kd))
surfaceScalarField rAUKd2 (fvc::interpolate(rAU2 *Kd))
surfaceScalarField phiHbyA ("phiHbyA", alphaf1 *(phiHbyA1+rAUKd1 *MRF.absolute(phi2))+alphaf2 *(phiHbyA2+rAUKd2 *MRF.absolute(phi1)))
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf ("rAUf",)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryFieldRef(),(phiHbyA.boundaryField()-(alphaf1.boundaryField()*phi1.boundaryField()+alphaf2.boundaryField()*phi2.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 (IOobject::groupName("phid", phase2.name()), fvc::interpolate(psi2)*phi2)
pEqnComp1 ref ().relax()
volScalarField p_rgh_0 (p_rgh)
solve (pEqnComp1()+pEqnComp2()+pEqnIncomp, mesh.solver(p_rgh.select(pimple.finalInnerIter())))
surfaceScalarField mSfGradp ("mSfGradp", pEqnIncomp.flux()/rAUf)
surfaceScalarField phi2s (phiHbyA2+alpharAUf2 *mSfGradp)
surfaceScalarField phir (((phi1s+rAUKd1 *phi2s)-(phi2s+rAUKd2 *phi1s))/(1-rAUKd1 *rAUKd2))
fluid dgdt ()
p_rgh relax ()
volVectorField Us2 (HbyA2+fvc::reconstruct(alpharAUf2 *mSfGradp-phiF2()-phig2))
volScalarField D1 (rAU1 *Kd)
volScalarField D2 (rAU2 *Kd)
volVectorField Ur (((1-D2)*Us1-(1-D1)*Us2)/(1-D1 *D2))
U1 correctBoundaryConditions ()
fvOptions correct (U1)
fvOptions correct (U2)
if (thermo1.dpdt()||thermo2.dpdt())
Variables
tmp< surfaceScalarField > phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
tmp< surfaceScalarField > phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
p_rgh = p - rho*gh
HbyA1
HbyA2
surfaceScalarField::Boundary & phiCorrCoeff2Bf
tmp< fvScalarMatrix > pEqnComp1
tmp< fvScalarMatrix > pEqnComp2
else
phi1 = phi + alphaf2*phir
phi2 = phi - alphaf1*phir
mSfGradp = pEqnIncomp.flux()/rAUf
U = alpha1*(Us1 + D1*U2) + alpha2*(Us2 + D2*U1)
U1 = U + alpha2*Ur
U2 = U - alpha1*Ur
p = max(p_rgh + rho*gh, pMin)
rho1 = psi1*(p_rgh - p_rgh_0)
rho2 = psi2*(p_rgh - p_rgh_0)
rho = fluid.rho()
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
surfaceScalarField alphaf1 ("alphaf1" , fvc:: interpolatealpha1)
surfaceScalarField alphaf2 ("alphaf2" , scalar(1)- alphaf1)
volScalarField rAU1 (IOobject:: groupName"rAU", phase1.name(), 1.0/ U1Eqn.A()+max(phase1.residualAlpha()-alpha1, scalar(0))*rho1/runTime.deltaT())
volScalarField rAU2 (IOobject:: groupName"rAU", phase2.name(), 1.0/ U2Eqn.A()+max(phase2.residualAlpha()-alpha2, scalar(0))*rho2/runTime.deltaT())
surfaceScalarField alpharAUf1 (fvc:: interpolatemax(alpha1, phase1.residualAlpha())*rAU1)
surfaceScalarField alpharAUf2 (fvc:: interpolatemax(alpha2, phase2.residualAlpha())*rAU2)
surfaceScalarField Df1 (fvc:: interpolaterAU1 *(D+phase1.turbulence().pPrime()))
Referenced by if().
surfaceScalarField Df2 (fvc:: interpolaterAU2 *(D+phase2.turbulence().pPrime()))
Referenced by if().
if (implicitPhasePressure)
Definition at line 61 of file pEqn.H.
References Df1(), Df2(), and fluid.
volVectorField F (fluid. F())
Referenced by ReactingHeterogeneousParcel< ParcelType >::calcHeterogeneousReactions(), noWallDamping::damp(), interpolated::damp(), and BlendedInterfacialModel< ModelType >::Ff().
surfaceScalarField snGradAlpha1 (fvc:: snGradalpha1)*mesh.magSf()
MRF correctBoundaryFlux (U1 , phi1)
MRF correctBoundaryFlux (U2 , phi2)
volVectorField HbyA1 (IOobject:: groupName"HbyA", phase1.name(), U1)
volVectorField HbyA2 (IOobject:: groupName"HbyA", phase2.name(), U2)
surfaceScalarField ghSnGradRho ("ghSnGradRho" , ghf *fvc:: snGradrho)*mesh.magSf()
surfaceScalarField phig1 (alpharAUf1 * ghSnGradRho-alphaf2 *fvc::interpolate(rho1-rho2)*(g &mesh.Sf()))
surfaceScalarField phig2 (alpharAUf2 * ghSnGradRho-alphaf1 *fvc::interpolate(rho2-rho1)*(g &mesh.Sf()))
surfaceScalarField alphaf1Bar (fvc:: interpolatefvc::average(alphaf1))
surfaceScalarField phiCorrCoeff1 (pos0(alphaf1Bar-0.99))
surfaceScalarField phiCorrCoeff2 (pos0(0.01-alphaf1Bar))
surfaceScalarField phiHbyA2 (IOobject:: groupName"phiHbyA", phase2.name(), fvc::flux(HbyA2)+phiCorrCoeff2 *fvc::interpolate(alpha2.oldTime()*rho2.oldTime()*rAU2)*(MRF.absolute(phi2.oldTime())-fvc::flux(U2.oldTime()))/runTime.deltaT()-phiF2()- phig2)
surfaceScalarField rAUKd1 (fvc:: interpolaterAU1 *Kd)
surfaceScalarField rAUKd2 (fvc:: interpolaterAU2 *Kd)
surfaceScalarField phiHbyA ("phiHbyA" , alphaf1 * phiHbyA1+rAUKd1 *MRF.absolute(phi2))+alphaf2 *(phiHbyA2+rAUKd2 *MRF.absolute(phi1))
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf ("rAUf")
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryFieldRef(), (phiHbyA.boundaryField()-(alphaf1.boundaryField()*phi1.boundaryField()+alphaf2.boundaryField()*phi2.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 (IOobject:: groupName"phid", phase2.name(), fvc::interpolate(psi2)* phi2)
pEqnComp1 ref ()
volScalarField p_rgh_0 (p_rgh)
solve (pEqnComp1()+pEqnComp2()+ pEqnIncomp, mesh. solverp_rgh.select(pimple.finalInnerIter()))
surfaceScalarField mSfGradp ("mSfGradp" , pEqnIncomp.flux()/ rAUf)
surfaceScalarField phi2s (phiHbyA2+alpharAUf2 * mSfGradp)
surfaceScalarField phir (((phi1s+rAUKd1 *phi2s)-(phi2s+rAUKd2 *phi1s))/(1-rAUKd1 *rAUKd2))
fluid dgdt ()
p_rgh relax ()
volVectorField Us2 (HbyA2+fvc:: reconstructalpharAUf2 *mSfGradp-phiF2()-phig2)
volScalarField D1 (rAU1 * Kd)
volScalarField D2 (rAU2 * Kd)
volVectorField Ur (((1-D2)*Us1-(1-D1)*Us2)/(1-D1 *D2))
U1 correctBoundaryConditions ()
fvOptions correct (U1)
fvOptions correct (U2)
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 413 of file pEqn.H.
References Foam::fac::ddt(), dpdt, and p.
Variable Documentation
phiF1 = Df1*snGradAlpha1 + fvc::flux(rAU1*F)
Definition at line 35 of file pEqn.H.
phiF2 = - Df2*snGradAlpha1 - fvc::flux(rAU2*F)
Definition at line 36 of file pEqn.H.
p_rgh = p - rho*gh
Definition at line 89 of file pEqn.H.
HbyA1
Initial value:
=
        rAU1
       *(
            U1Eqn.H()
          + max(phase1.residualAlpha() - alpha1, scalar(0))
           *rho1*U1.oldTime()/runTime.deltaT()
        )
Definition at line 100 of file pEqn.H.
HbyA2
Initial value:
=
        rAU2
       *(
            U2Eqn.H()
         +  max(phase2.residualAlpha() - alpha2, scalar(0))
           *rho2*U2.oldTime()/runTime.deltaT()
        )
Definition at line 113 of file pEqn.H.
surfaceScalarField::Boundary& phiCorrCoeff2Bf
Initial value:
=
            phiCorrCoeff2.boundaryFieldRef()
Definition at line 155 of file pEqn.H.
pEqnComp1
Initial value:
=
            (
                contErr1
              - fvc::Sp(fvc::ddt(alpha1) + fvc::div(alphaPhi1), rho1)
            )/rho1
          + correction
            (
                (alpha1/rho1)*
                (
                    psi1*fvm::ddt(p_rgh)
                  + fvm::div(phid1, p_rgh) - fvm::Sp(fvc::div(phid1), p_rgh)
                )
            )
Definition at line 235 of file pEqn.H.
pEqnComp2
Initial value:
=
            (
                contErr2
              - fvc::Sp(fvc::ddt(alpha2) + fvc::div(alphaPhi2), rho2)
            )/rho2
          + correction
            (
                (alpha2/rho2)*
                (
                    psi2*fvm::ddt(p_rgh)
                  + fvm::div(phid2, p_rgh) - fvm::Sp(fvc::div(phid2), p_rgh)
                )
            )
Definition at line 236 of file pEqn.H.
else
Initial value:
{
        pEqnComp1 =
            (
                contErr1
              - fvc::Sp(fvc::ddt(alpha1) + fvc::div(alphaPhi1), rho1)
            )/rho1
          + (alpha1*psi1/rho1)*correction(fvm::ddt(p_rgh))
Definition at line 283 of file pEqn.H.
phi1 = phi + alphaf2*phir
Definition at line 343 of file pEqn.H.
phi2 = phi - alphaf1*phir
Definition at line 344 of file pEqn.H.
mSfGradp = pEqnIncomp.flux()/rAUf
Definition at line 357 of file pEqn.H.
U = alpha1*(Us1 + D1*U2) + alpha2*(Us2 + D2*U1)
Definition at line 376 of file pEqn.H.
U1 = U + alpha2*Ur
Definition at line 379 of file pEqn.H.
U2 = U - alpha1*Ur
Definition at line 383 of file pEqn.H.
p = max(p_rgh + rho*gh, pMin)
Definition at line 393 of file pEqn.H.
rho1 = psi1*(p_rgh - p_rgh_0)
Definition at line 399 of file pEqn.H.
rho2 = psi2*(p_rgh - p_rgh_0)
Definition at line 400 of file pEqn.H.
rho = fluid.rho()
Definition at line 403 of file pEqn.H.
K1 = 0.5*magSqr(U1)
Definition at line 409 of file pEqn.H.
K2 = 0.5*magSqr(U2)
Definition at line 410 of file pEqn.H.