OpenFOAM: applications/solvers/multiphase/multiphaseEulerFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
PtrList< volVectorField > HbyAs (fluid.phases().size())
PtrList< surfaceScalarField > phiHbyAs (fluid.phases().size())
PtrList< volScalarField > rAUs (fluid.phases().size())
PtrList< surfaceScalarField > rAlphaAUfs (fluid.phases().size())
MRF makeAbsolute (phase.phi())
HbyAs set (phasei, new volVectorField(phase.U()))
phiHbyAs set (phasei, new surfaceScalarField(1.0 *phase.phi()))
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
volScalarField rho ("rho", fluid.rho())
surfaceScalarField ghSnGradRho (ghf *fvc::snGrad(rho)*mesh.magSf())
alphafs set (phasei, fvc::interpolate(alpha).ptr())
alphafs[phasei] rename ("hmm"+alpha.name())
volScalarField dragCoeffi (IOobject("dragCoeffi", runTime.timeName(), mesh), fluid.dragCoeff(phase, dragCoeffs())/phase.rho(), zeroGradientFvPatchScalarField::typeName)
dragCoeffi correctBoundaryConditions ()
rAUs set (phasei,(1.0/(UEqns[phasei].A()+dragCoeffi)).ptr())
rAlphaAUfs set (phasei,(alphafs[phasei]/fvc::interpolate(UEqns[phasei].A()+dragCoeffi)).ptr())
MRF makeRelative (phiHbyAs[phasei])
MRF makeRelative (phase.phi().oldTime())
MRF makeRelative (phase.phi())
for (;dmIter.good()&&dcIter.good();++dmIter,++dcIter)
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh), mesh,)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryFieldRef(),(phiHbyA.boundaryField()-MRF.relative(phib))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
pEqnIncomp setReference (pRefCell, pRefValue)
solve (pEqnIncomp, mesh.solver(p_rgh.select(pimple.finalInnerIter())))
p_rgh relax ()
phase U ()
Variables
phasei = 0
HbyAs [phasei] = rAUs[phasei]*UEqns[phasei].H()
phiHbyAs [phasei]
auto dmIter = fluid.dragModels().cbegin()
auto dcIter = dragCoeffs().cbegin()
phiHbyA = alphafs[phasei]*phiHbyAs[phasei]
phib = 0
phi = dimensionedScalar("phi", phi.dimensions(), Zero)
p = p_rgh + rho*gh
mSfGradp = pEqnIncomp.flux()/rAUf
U = dimensionedVector("U", dimVelocity, Zero)
Function Documentation
PtrList<volVectorField> HbyAs (fluid. phases).size()
PtrList<surfaceScalarField> phiHbyAs (fluid. phases).size()
PtrList<volScalarField> rAUs (fluid. phases).size()
PtrList<surfaceScalarField> rAlphaAUfs (fluid. phases).size()
MRF makeAbsolute (phase. phi())
Referenced by Foam::CorrectPhi(), and if().
HbyAs set (phasei , new volVectorFieldphase.U())
phiHbyAs set (phasei , new surfaceScalarField1.0 *phase.phi())
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
volScalarField rho ("rho" , fluid. rho())
surfaceScalarField ghSnGradRho (ghf *fvc:: snGradrho)*mesh.magSf()
alphafs set (phasei , fvc:: interpolatealpha).ptr()
alphafs [phasei] rename ("hmm"+alpha. name())
Referenced by Foam::mvBak().
volScalarField dragCoeffi (IOobject("dragCoeffi", runTime.timeName(), mesh) , fluid. dragCoeffphase, dragCoeffs())/phase.rho(, zeroGradientFvPatchScalarField::typeName)
Referenced by for().
dragCoeffi correctBoundaryConditions ()
rAUs set (phasei , (1.0/(UEqns[phasei].A()+dragCoeffi)).ptr())
rAlphaAUfs set (phasei , (alphafs[phasei]/fvc::interpolate(UEqns[phasei].A()+dragCoeffi)).ptr())
MRF makeRelative (phiHbyAs [phasei])
MRF makeRelative (phase. phi).oldTime()
MRF makeRelative (phase. phi())
for (;dmIter.good()&&dcIter.good();++ dmIter, ++ dcIter)
Definition at line 119 of file pEqn.H.
References A, dcIter, dmIter, dragCoeffi(), HbyAs, Foam::fac::interpolate(), phase2, phasei, phiHbyAs, rAUs, and UEqns().
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh) , mesh)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryFieldRef(), (phiHbyA.boundaryField()-MRF.relative(phib))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
pEqnIncomp setReference (pRefCell , pRefValue)
solve (pEqnIncomp , mesh. solverp_rgh.select(pimple.finalInnerIter()))
p_rgh relax ()
phase U ()
Variable Documentation
phasei = 0
Definition at line 33 of file pEqn.H.
HbyAs[phasei] = rAUs[phasei]*UEqns[phasei].H()
Definition at line 93 of file pEqn.H.
Referenced by for(), and if().
phiHbyAs[phasei]
Initial value:
=
        (
            fvc::flux(HbyAs[phasei])
          + MRF.zeroFilter
            (
                rAlphaAUfs[phasei]*fvc::ddtCorr(phase.U(), phase.phi())
            )
        )
Definition at line 95 of file pEqn.H.
Referenced by for(), and if().
auto dmIter = fluid.dragModels().cbegin()
Definition at line 115 of file pEqn.H.
Referenced by for().
auto dcIter = dragCoeffs().cbegin()
Definition at line 116 of file pEqn.H.
Referenced by for().
phiHbyA = alphafs[phasei]*phiHbyAs[phasei]
Definition at line 161 of file pEqn.H.
phib = 0
Definition at line 189 of file pEqn.H.
phi = dimensionedScalar("phi", phi.dimensions(), Zero)
Definition at line 234 of file pEqn.H.
p = p_rgh + rho*gh
Definition at line 259 of file pEqn.H.
mSfGradp = pEqnIncomp.flux()/rAUf
Definition at line 261 of file pEqn.H.
U = dimensionedVector("U", dimVelocity, Zero)
Definition at line 263 of file pEqn.H.