OpenFOAM: applications/solvers/multiphase/interFoam/overInterDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField faceMask (localMin< scalar >(mesh).interpolate(cellMask))
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField H ("H", UEqn.H())
volVectorField HbyA ("HbyA", U)
if (massFluxInterpolation)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
if (ddtCorr)
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA, U, p_rgh)
if (adjustFringe)
surfaceScalarField phig ((mixture.surfaceTensionForce()-ghf *fvc::snGrad(rho))*faceMask *rAUf *mesh.magSf())
constrainPressure (p_rgh, U, phiHbyA, rAUf, MRF)
p_rghEqn setReference (pRefCell, getRefCellValue(p_rgh, pRefCell))
p_rghEqn solve (mesh.solver(p_rgh.select(pimple.finalInnerIter())))
p_rgh relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
HbyA = constrainHbyA(rAU*H, U, p_rgh)
phiHbyA = phig
U
Function Documentation
surfaceScalarField faceMask (localMin< scalar > mesh).interpolate(cellMask)
surfaceScalarField rAUf ("rAUf" , fvc:: interpolaterAU)
volVectorField H ("H" , UEqn. H())
volVectorField HbyA ("HbyA" , U)
if (massFluxInterpolation)
Definition at line 15 of file pEqn.H.
surfaceScalarField phiHbyA ("phiHbyA" , fvc:: fluxHbyA)
if (ddtCorr)
Definition at line 22 of file pEqn.H.
References ddtCorr, Foam::fac::interpolate(), mesh, phiHbyA, rAU, rho, U, and Uf.
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA , U , p_rgh)
if (adjustFringe)
Definition at line 40 of file pEqn.H.
References makeAbsolute(), Foam::fvc::makeRelative(), Foam::oversetAdjustPhi(), phiHbyA, and U.
surfaceScalarField phig ((mixture.surfaceTensionForce()-ghf *fvc::snGrad(rho))*faceMask *rAUf *mesh.magSf())
constrainPressure (p_rgh , U , phiHbyA , rAUf , MRF)
p_rghEqn setReference (pRefCell , getRefCellValue(p_rgh, pRefCell))
p_rghEqn solve (mesh. solverp_rgh.select(pimple.finalInnerIter()))
p_rgh relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variable Documentation
HbyA = constrainHbyA(rAU*H, U, p_rgh)
Definition at line 13 of file pEqn.H.
phiHbyA = phig
Definition at line 55 of file pEqn.H.
U
Initial value:
=
                cellMask*
                (
                   HbyA + rAU*fvc::reconstruct((phig - p_rghEqn.flux())/rAUf)
                )
Definition at line 84 of file pEqn.H.