OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/pU/pEqn.H File Reference
pEqn.H File Reference
Functions
PtrList< surfaceScalarField > alphafs (phases.size())
forAll (phases, phasei)
PtrList< volScalarField > rAUs (phases.size())
rAUs set (phase.index(), new volScalarField(IOobject::groupName("rAU", phase.name()), 1.0/(UEqns[phase.index()].A()+byDt(max(phase.residualAlpha()-alpha, scalar(0))*phase.rho()))))
fluid fillFields ("rAU", dimTime/dimDensity, rAUs)
PtrList< surfaceScalarField > alpharAUfs (phases.size())
PtrList< surfaceScalarField > phiFs (fluid.phiFs(rAUs))
MRF correctBoundaryFlux (phase.U(), phase.phiRef())
PtrList< surfaceScalarField > phigFs (phases.size())
PtrList< volVectorField > HbyAs (phases.size())
PtrList< surfaceScalarField > phiHbyAs (phases.size())
HbyAs set (phase.index(), new volVectorField(IOobject::groupName("HbyA", phase.name()), phase.U()))
phiHbyAs set (phase.index(), new surfaceScalarField(IOobject::groupName("phiHbyA", phase.name()), fvc::flux(HbyAs[phase.index()])-phigFs[phase.index()]-ddtCorrByAs[phase.index()]))
fluid fillFields ("HbyA", dimVelocity, HbyAs)
fluid fillFields ("phiHbyA", dimForce/dimDensity/dimVelocity, phiHbyAs)
if (!partialElimination)
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
if (partialElimination)
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh), mesh,)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryFieldRef(),(phiHbyA.boundaryField()-phib)/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
PtrList< fvScalarMatrix > pEqnComps (phases.size())
PtrList< volScalarField > dmdts (fluid.dmdts())
volScalarField p_rgh_0 (p_rgh)
solve (pEqn, mesh.solver(p_rgh.select(pimple.finalInnerIter())))
surfaceScalarField mSfGradp ("mSfGradp", pEqnIncomp.flux()/rAUf)
phase phiRef ()
if (pEqnComps.set(phase.index()))
p_rgh relax ()
phase URef ()
fvOptions correct (phase.URef())
p_rgh correctBoundaryConditions ()
Variables
const volScalarField & alpha = phase
Fine-structure constant: default SI units: [].
p_rgh = p - rho*gh
HbyAs [phase.index()]
rAUf = mag(rAUf)
phib = 0
mSfGradp = pEqnIncomp.flux()/rAUf
p = max(p_rgh + rho*gh, pMin)
rho = fluid.rho()
Function Documentation
PtrList<surfaceScalarField> alphafs (phases. size())
Referenced by forAll(), and if().
forAll (phases , phasei)
Definition at line 3 of file pEqn.H.
References Foam::constant::atomic::alpha, alphafs(), Foam::fac::interpolate(), Foam::name(), phasei, and phases.
PtrList<volScalarField> rAUs (phases. size())
rAUs set (phase. index(), new volScalarFieldIOobject::groupName("rAU", phase.name()), 1.0/(UEqns[phase.index()].A()+byDt(max(phase.residualAlpha()-alpha, scalar(0))*phase.rho())))
fluid fillFields ("rAU" , dimTime/ dimDensity, rAUs)
PtrList<surfaceScalarField> alpharAUfs (phases. size())
PtrList<surfaceScalarField> phiFs (fluid. phiFsrAUs)
MRF correctBoundaryFlux (phase. U(), phase. phiRef())
PtrList<surfaceScalarField> phigFs (phases. size())
PtrList<volVectorField> HbyAs (phases. size())
PtrList<surfaceScalarField> phiHbyAs (phases. size())
HbyAs set (phase. index(), new volVectorFieldIOobject::groupName("HbyA", phase.name()), phase.U())
phiHbyAs set (phase. index(), new surfaceScalarFieldIOobject::groupName("phiHbyA", phase.name()), fvc::flux(HbyAs[phase.index()])-phigFs[phase.index()]-ddtCorrByAs[phase.index()])
fluid fillFields ("HbyA" , dimVelocity , HbyAs)
fluid fillFields ("phiHbyA" , dimForce/dimDensity/ dimVelocity, phiHbyAs)
if (! partialElimination)
Definition at line 153 of file pEqn.H.
References fluid, forAll, HbyAs, phasei, phases, phiHbyAs, phiKdPhis(), and rAUs.
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
if (partialElimination)
Definition at line 192 of file pEqn.H.
References alphafs(), fluid, forAll, phasei, phases, phiHbyA, phiKdPhis(), and rAUs.
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh) , mesh)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryFieldRef(), (phiHbyA.boundaryField()-phib)/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
PtrList<fvScalarMatrix> pEqnComps (phases. size())
Referenced by if().
PtrList<volScalarField> dmdts (fluid. dmdts())
Referenced by phaseSystem::solve().
volScalarField p_rgh_0 (p_rgh)
solve (pEqn , mesh. solverp_rgh.select(pimple.finalInnerIter()))
surfaceScalarField mSfGradp ("mSfGradp" , pEqnIncomp.flux()/ rAUf)
phase phiRef ()
if (pEqnComps. setphase.index())
Definition at line 396 of file pEqn.H.
References p_rgh, and pEqnComps().
p_rgh relax ()
phase URef ()
Initial value:
{
                phaseModel& phase = fluid.movingPhases()[movingPhasei]
fvOptions correct (phase. URef())
p_rgh correctBoundaryConditions ()
Variable Documentation
const volScalarField & alpha = phase
Fine-structure constant: default SI units: [].
Definition at line 17 of file pEqn.H.
p_rgh = p - rho*gh
Definition at line 60 of file pEqn.H.
HbyAs[phase.index()]
Initial value:
=
                rAUs[phase.index()]
               *(
                    UEqns[phase.index()].H()
                  + byDt
                    (
                        max(phase.residualAlpha() - alpha, scalar(0))
                       *phase.rho()
                    )
                   *phase.U()().oldTime()
                )
Definition at line 124 of file pEqn.H.
rAUf = mag(rAUf)
Definition at line 225 of file pEqn.H.
Referenced by if().
phib = 0
Definition at line 230 of file pEqn.H.
mSfGradp = pEqnIncomp.flux()/rAUf
Definition at line 405 of file pEqn.H.
p = max(p_rgh + rho*gh, pMin)
Definition at line 436 of file pEqn.H.
rho = fluid.rho()
Definition at line 449 of file pEqn.H.