OpenFOAM: Foam::vtk Namespace Reference
Foam::vtk Namespace Reference
Namespace for handling VTK input/output.
Namespaces
Tools
A collection of static methods to assist converting OpenFOAM data structures into VTK internal data structures.
legacy
Namespace for legacy VTK output constants and functions.
Classes
struct Caching
Bookkeeping for internal caching.
class vtuAdaptor
Bookkeeping for vtkUnstructuredGrid.
class internalWriter
Write an OpenFOAM volume (internal) geometry and internal fields as a vtu file or a legacy vtk file.
class patchWriter
Write OpenFOAM patches and patch fields in VTP or legacy vtk format.
class surfaceFieldWriter
Write surfaces fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported.
class surfaceMeshWriter
Write faces (eg face-zones or face-sets) with fields.
class fileWriter
Base class for VTK output writers that handle geometry and fields (eg, vtp, vtu data). These output formats are structured as DECLARED, FIELD_DATA, PIECE followed by any CELL_DATA or POINT_DATA.
class seriesWriter
Provides a means of accumulating and generating VTK file series.
class vtmWriter
Provides a means of accumulating file entries for generating a vtkMultiBlockDataSet (.vtm) file.
class appendBase64Formatter
Appended base-64 encoded binary output. Uses an output filter layer to write base-64 encoded content.
class appendRawFormatter
Appended raw binary output.
class asciiFormatter
Inline ASCII output. Adds spaces between entries and a newline every 6 items (for consistency with what VTK itself outputs).
class base64Formatter
Inline base-64 encoded binary output. Uses an output filter layer to write base-64 encoded content.
class foamVtkBase64Layer
Base-64 encoded output layer - normally only used indirectly by formatters.
class formatter
Abstract class for a VTK output stream formatter.
class legacyAsciiFormatter
Formatting as per Foam::vtk::asciiFormatter, but with naming for legacy output.
class legacyRawFormatter
Binary output for the VTK legacy format, always written as big-endian and with 32-bit integers.
class outputOptions
Encapsulated combinations of output format options. This is primarily useful when defining the output type based on some command-line arguments or dictionary contents. However, it can also be a useful alternative to using the underlying enumeration directly, since this class provides additional methods not possible with an enum.
class vtuCells
A deep-copy description of an OpenFOAM volume mesh in data structures suitable for VTK UnstructuredGrid, including the possibility of decomposing polyhedral cells into primitive cell types.
class vtuSizing
Sizing descriptions and routines for transcribing an OpenFOAM volume mesh into a VTK unstructured grid, with possible decomposition of polyhedral cells into primitive cell types.
class surfaceWriter
Write faces/points (optionally with fields) as a vtp file or a legacy vtk file.
class lagrangianWriter
Write lagrangian (cloud) positions and fields (as PointData) in VTP format. Legacy VTK format is intentionally not supported since the VTP format provides much better field selection in ParaView, and for consistency with the Foam::functionObjects::vtkCloud function object.
class indirectPatchWriter
Write indirectPrimitivePatch faces/points (optionally with fields) as a vtp file or a legacy vtk file.
Enumerations
enum OutputContext { INLINE, HEADER, APPEND }
The context when outputting a VTK file (XML or legacy).
enum formatType : uint8_t {
INLINE_ASCII = 0, INLINE_BASE64 = 0x01, APPEND_BASE64 = 0x11, APPEND_BINARY = 0x12,
LEGACY_ASCII = 0x20, LEGACY_BINARY = 0x22
}
The output format type for file contents.
enum cellType {
VTK_EMPTY_CELL = 0, VTK_VERTEX = 1, VTK_POLY_VERTEX = 2, VTK_LINE = 3,
VTK_POLY_LINE = 4, VTK_TRIANGLE = 5, VTK_TRIANGLE_STRIP = 6, VTK_POLYGON = 7,
VTK_PIXEL = 8, VTK_QUAD = 9, VTK_TETRA = 10, VTK_VOXEL = 11,
VTK_HEXAHEDRON = 12, VTK_WEDGE = 13, VTK_PYRAMID = 14, VTK_PENTAGONAL_PRISM = 15,
VTK_HEXAGONAL_PRISM = 16, VTK_POLYHEDRON = 42
}
Equivalent to enumeration in "vtkCellType.h".
enum fileTag {
VTK_FILE, DATA_ARRAY, BLOCK, PIECE,
DATA_SET, POINTS, CELLS, POLYS,
VERTS, LINES, CELL_DATA, POINT_DATA,
FIELD_DATA, POLY_DATA, UNSTRUCTURED_GRID, MULTI_BLOCK
}
Some common XML tags for vtk files.
enum fileAttr {
OFFSET, NUMBER_OF_COMPONENTS, NUMBER_OF_TUPLES, NUMBER_OF_POINTS,
NUMBER_OF_CELLS, NUMBER_OF_POLYS, NUMBER_OF_VERTS, NUMBER_OF_LINES
}
Some common XML attributes for vtk files.
enum dataArrayAttr {
POINTS, OFFSETS, CONNECTIVITY, TYPES,
FACES, FACEOFFSETS
}
Some common names for XML DataArray entries.
Functions
bool isAppend (enum formatType fmt)
Test for XML append format.
bool isLegacy (enum formatType fmt)
Test for vtk legacy format.
template<class Type , direction nComp = 1>
uint64_t sizeofData (label count)
Commonly used calculation for header and payload sizes.
autoPtr< vtk::formatter > newFormatter (std::ostream &os, unsigned prec=IOstream::defaultPrecision())
Return a default asciiFormatter.
autoPtr< vtk::formatter > newFormatter (std::ostream &os, const enum formatType fmtType, unsigned prec=IOstream::defaultPrecision())
Return a new formatter based on the specified format type.
void writeIdentity (vtk::formatter &fmt, const label len, label start=0)
Write an identity list of labels.
void writeList (vtk::formatter &fmt, const UList< uint8_t > &values)
Write a list of uint8_t values.
void writeListParallel (vtk::formatter &fmt, const UList< uint8_t > &values)
Write a list of uint8_t values.
template<class Type >
void write (vtk::formatter &fmt, const Type &val, const label n=1)
Component-wise write of a value (N times)
template<class Type >
void writeList (vtk::formatter &fmt, const UList< Type > &values)
Write a list of values.
template<class Type , unsigned N>
void writeList (vtk::formatter &fmt, const FixedList< Type, N > &values)
Write a list of values.
template<class Type >
void writeList (vtk::formatter &fmt, const UList< Type > &values, const labelUList &addressing)
Write a list of values via indirect addressing.
template<class Type >
void writeList (vtk::formatter &fmt, const UList< Type > &values, const bitSet &selected)
Write a list of values via indirect addressing.
template<class Type >
void writeLists (vtk::formatter &fmt, const UList< Type > &values1, const UList< Type > &values2, const labelUList &addressing)
Write a list of values and a list of values via indirect addressing.
template<class Type >
void writeListParallel (vtk::formatter &fmt, const UList< Type > &values)
Write a list of values.
void writeListParallel (vtk::formatter &fmt, const UList< label > &values, const globalIndex &procOffset)
Write a list of values, with constant per-processor offset.
template<class Type >
void writeListParallel (vtk::formatter &fmt, const UList< Type > &values, const labelUList &addressing)
Write a list of values via indirect addressing.
template<class Type >
void writeListParallel (vtk::formatter &fmt, const UList< Type > &values, const bitSet &selected)
Write a list of values via indirect addressing.
template<class Type >
void writeListsParallel (vtk::formatter &fmt, const UList< Type > &values1, const UList< Type > &values2)
Write a list of values and another list of values.
template<class Type >
void writeListsParallel (vtk::formatter &fmt, const UList< Type > &values1, const UList< Type > &values2, const labelUList &addressing)
Write a list of values and a list of values via indirect addressing.
template<>
void write< label > (vtk::formatter &fmt, const label &val, const label n)
Template specialization for label.
template<>
void write< float > (vtk::formatter &fmt, const float &val, const label n)
Template specialization for float.
template<>
void write< double > (vtk::formatter &fmt, const double &val, const label n)
Template specialization for double.
template<>
void write (vtk::formatter &fmt, const symmTensor &val, const label n)
Template specialization for symmTensor ordering.
bool writeTopoSet (const polyMesh &mesh, const topoSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Dispatch to vtk::writeCellSetFaces, vtk::writeFaceSet, vtk::writePointSet.
bool writeFaceSet (const polyMesh &mesh, const faceSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Write faceSet as VTK polydata file.
bool writeCellSetFaces (const polyMesh &mesh, const cellSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Write perimeter faces of cellset to vtk polydata file.
bool writePointSet (const polyMesh &mesh, const pointSet &set, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Write pointSet to VTK polydata file.
Variables
const Foam::Enum< fileTag > fileExtension
File extension (without ".") for some vtk XML file content types.
const Foam::Enum< fileTag > fileContentVersions
Version string for some vtk XML file content types.
const Foam::Enum< fileTag > fileTagNames
Strings corresponding to the vtk XML tags.
const Foam::Enum< fileAttr > fileAttrNames
Strings corresponding to the vtk XML attributes.
const Foam::Enum< dataArrayAttr > dataArrayAttrNames
Strings corresponding to the vtk XML DataArray attributes.
Detailed Description
Namespace for handling VTK input/output.
Namespace for handling VTK output. Contains classes and functions for writing VTK file content.
Source files
foamVtkCore.H
foamVtkCore.C
Enumeration Type Documentation
enum OutputContext
The context when outputting a VTK file (XML or legacy).
Enumerator
INLINE
HEADER
APPEND
Definition at line 53 of file foamVtkCore.H.
enum formatType : uint8_t strong
The output format type for file contents.
Upper bits for output type, lower bits for the format itself.
Enumerator
INLINE_ASCII
XML inline ASCII, asciiFormatter.
INLINE_BASE64
XML inline base64, base64Formatter.
APPEND_BASE64
XML append base64, appendBase64Formatter.
APPEND_BINARY
XML append raw binary, appendRawFormatter.
LEGACY_ASCII
Legacy ASCII, legacyAsciiFormatter.
LEGACY_BINARY
Legacy raw binary, legacyRawFormatter.
Definition at line 66 of file foamVtkCore.H.
enum cellType
Equivalent to enumeration in "vtkCellType.h".
Enumerator
VTK_EMPTY_CELL
VTK_VERTEX
VTK_POLY_VERTEX
VTK_LINE
VTK_POLY_LINE
VTK_TRIANGLE
VTK_TRIANGLE_STRIP
VTK_POLYGON
VTK_PIXEL
VTK_QUAD
VTK_TETRA
VTK_VOXEL
VTK_HEXAHEDRON
VTK_WEDGE
VTK_PYRAMID
VTK_PENTAGONAL_PRISM
VTK_HEXAGONAL_PRISM
VTK_POLYHEDRON
Definition at line 96 of file foamVtkCore.H.
enum fileTag strong
Some common XML tags for vtk files.
Enumerator
VTK_FILE
"VTKFile"
DATA_ARRAY
"DataArray"
BLOCK
"Block"
PIECE
"Piece"
DATA_SET
"DataSet"
POINTS
"Points"
CELLS
"Cells"
POLYS
"Polys"
VERTS
"Verts"
LINES
"Lines"
CELL_DATA
"CellData"
POINT_DATA
"PointData"
FIELD_DATA
"FieldData"
POLY_DATA
"PolyData"
UNSTRUCTURED_GRID
"UnstructuredGrid"
MULTI_BLOCK
"vtkMultiBlockDataSet"
Definition at line 122 of file foamVtkCore.H.
enum fileAttr strong
Some common XML attributes for vtk files.
Enumerator
OFFSET
"offset"
NUMBER_OF_COMPONENTS
"NumberOfComponents"
NUMBER_OF_TUPLES
"NumberOfTuples"
NUMBER_OF_POINTS
"NumberOfPoints"
NUMBER_OF_CELLS
"NumberOfCells"
NUMBER_OF_POLYS
"NumberOfPolys"
NUMBER_OF_VERTS
"NumberOfVerts"
NUMBER_OF_LINES
"NumberOfLines"
Definition at line 160 of file foamVtkCore.H.
enum dataArrayAttr strong
Some common names for XML DataArray entries.
Enumerator
POINTS
"Points"
OFFSETS
"offsets"
CONNECTIVITY
"connectivity"
TYPES
"types"
FACES
"faces"
FACEOFFSETS
"faceoffsets"
Definition at line 180 of file foamVtkCore.H.
Function Documentation
bool Foam::vtk::isAppend (enum formatType fmt) inline
Test for XML append format.
Definition at line 79 of file foamVtkCore.H.
bool Foam::vtk::isLegacy (enum formatType fmt) inline
Test for vtk legacy format.
Definition at line 87 of file foamVtkCore.H.
References VTK_EMPTY_CELL, VTK_LINE, VTK_POLY_LINE, VTK_POLY_VERTEX, and VTK_VERTEX.
uint64_t Foam::vtk::sizeofData (label count) inline
Commonly used calculation for header and payload sizes.
Definition at line 734 of file foamVtkFormatter.H.
Foam::autoPtr< Foam::vtk::formatter > newFormatter (std::ostream & os, unsigned prec = IOstream::defaultPrecision())
Return a default asciiFormatter.
Definition at line 41 of file foamVtkOutput.C.
Referenced by outputOptions::fmt().
Foam::autoPtr< Foam::vtk::formatter > newFormatter (std::ostream & os, const enum formatType fmtType, unsigned prec = IOstream::defaultPrecision())
Return a new formatter based on the specified format type.
Definition at line 49 of file foamVtkOutput.C.
void writeIdentity (vtk::formatter & fmt, const label len, label start = 0)
Write an identity list of labels.
The output does not include the payload size.
Definition at line 89 of file foamVtkOutput.C.
void writeList (vtk::formatter & fmt, const UList< uint8_t > & values)
Write a list of uint8_t values.
The output does not include the payload size.
Definition at line 105 of file foamVtkOutput.C.
Referenced by lagrangianWriter::write(), lumpedPointMovement::writeData(), and writePointSet().
void writeListParallel (vtk::formatter & fmt, const UList< uint8_t > & values)
Write a list of uint8_t values.
The output does not include the payload size.
Definition at line 119 of file foamVtkOutput.C.
References Foam::val.
Referenced by lagrangianWriter::write(), vtkCloud::writeFields(), and writePointSet().
void write (vtk::formatter & fmt, const Type & val, const label n = 1) inline
Component-wise write of a value (N times)
Definition at line 28 of file foamVtkOutputTemplates.C.
References Foam::component(), i, n, and formatter::write().
Referenced by meshRefinement::baffleAndSplitMesh(), meshRefinement::balanceAndRefine(), ensightGeoFile::beginCoordinates(), OSstream::flags(), foamVtkBase64Layer::flush(), legacyRawFormatter::flush(), appendRawFormatter::flush(), asciiFormatter::flush(), meshRefinement::mergePatchFacesUndo(), Foam::operator<<(), Foam::operator>>(), edgeMesh::readTypes(), foamVtkBase64Layer::write(), FLMAsurfaceFormat< Face >::write(), appendRawFormatter::write(), MeshedSurfaceProxy< Face >::write(), OBJstream::write(), regionModelFunctionObject::write(), x3dWriter::write(), IrreversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), NonEquilibriumReversibleReaction< ReactionType, ReactionThermo, ReactionRate >::write(), ensightFile::write(), graph::write(), internalWriter::write(), UnsortedMeshedSurface< Face >::write(), MeshedSurface< Face >::write(), surfMesh::write(), triSurface::write(), Time::writeAndEnd(), Foam::writeCellGraph(), IOPosition< ParticleType >::writeData(), ensightFile::writeKeyword(), ensightFile::writeList(), Foam::writePatchGraph(), ensightPartCells::writeSummary(), ensightPartFaces::writeSummary(), x3dWriter::writeTemplate(), and fileWriter::writeUniform().
void writeList (vtk::formatter & fmt, const UList< Type > & values)
Write a list of values.
The output does not include the payload size.
Definition at line 48 of file foamVtkOutputTemplates.C.
void writeList (vtk::formatter & fmt, const FixedList< Type, N > & values)
Write a list of values.
The output does not include the payload size.
Definition at line 62 of file foamVtkOutputTemplates.C.
void writeList (vtk::formatter & fmt, const UList< Type > & values, const labelUList & addressing)
Write a list of values via indirect addressing.
The output does not include the payload size.
Definition at line 76 of file foamVtkOutputTemplates.C.
void writeList (vtk::formatter & fmt, const UList< Type > & values, const bitSet & selected)
Write a list of values via indirect addressing.
The output does not include the payload size.
Definition at line 91 of file foamVtkOutputTemplates.C.
void writeLists (vtk::formatter & fmt, const UList< Type > & values1, const UList< Type > & values2, const labelUList & addressing)
Write a list of values and a list of values via indirect addressing.
The output does not include the payload size.
Definition at line 106 of file foamVtkOutputTemplates.C.
void writeListParallel (vtk::formatter & fmt, const UList< Type > & values)
Write a list of values.
The output does not include the payload size.
Definition at line 120 of file foamVtkOutputTemplates.C.
void Foam::vtk::writeListParallel (vtk::formatter & fmt, const UList< label > & values, const globalIndex & procOffset)
Write a list of values, with constant per-processor offset.
The output does not include the payload size.
void writeListParallel (vtk::formatter & fmt, const UList< Type > & values, const labelUList & addressing)
Write a list of values via indirect addressing.
The output does not include the payload size.
Definition at line 162 of file foamVtkOutputTemplates.C.
void writeListParallel (vtk::formatter & fmt, const UList< Type > & values, const bitSet & selected)
Write a list of values via indirect addressing.
The output does not include the payload size.
Definition at line 205 of file foamVtkOutputTemplates.C.
void writeListsParallel (vtk::formatter & fmt, const UList< Type > & values1, const UList< Type > & values2)
Write a list of values and another list of values.
The output does not include the payload size.
Definition at line 248 of file foamVtkOutputTemplates.C.
void writeListsParallel (vtk::formatter & fmt, const UList< Type > & values1, const UList< Type > & values2, const labelUList & addressing)
Write a list of values and a list of values via indirect addressing.
The output does not include the payload size.
Definition at line 293 of file foamVtkOutputTemplates.C.
void Foam::vtk::write< label > (vtk::formatter & fmt, const label & val, const label n) inline
Template specialization for label.
Definition at line 32 of file foamVtkOutputI.H.
References i, n, and Foam::val.
void Foam::vtk::write< float > (vtk::formatter & fmt, const float & val, const label n) inline
Template specialization for float.
Definition at line 45 of file foamVtkOutputI.H.
References i, n, and Foam::val.
void Foam::vtk::write< double > (vtk::formatter & fmt, const double & val, const label n) inline
Template specialization for double.
Definition at line 58 of file foamVtkOutputI.H.
References i, n, and Foam::val.
void Foam::vtk::write (vtk::formatter & fmt, const symmTensor & val, const label n) inline
Template specialization for symmTensor ordering.
VTK order is (XX, YY, ZZ, XY, YZ, XZ)
Definition at line 73 of file foamVtkOutputI.H.
References Foam::component(), formatter::write(), SymmTensor< scalar >::XX, SymmTensor< scalar >::XY, SymmTensor< scalar >::XZ, SymmTensor< scalar >::YY, SymmTensor< scalar >::YZ, and SymmTensor< scalar >::ZZ.
bool writeTopoSet (const polyMesh & mesh, const topoSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Dispatch to vtk::writeCellSetFaces, vtk::writeFaceSet, vtk::writePointSet.
The file name is with/without an extension.
Returns
True on successful dispatch
Definition at line 31 of file foamVtkWriteTopoSet.C.
References Foam::endl(), Foam::nl, WarningInFunction, writeCellSetFaces(), writeFaceSet(), and writePointSet().
bool writeFaceSet (const polyMesh & mesh, const faceSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Write faceSet as VTK polydata file.
Only one CELL_DATA, which is the original faceID The file name is with/without an extension.
————————————————————————
Definition at line 30 of file foamVtkWriteFaceSet.C.
References indirectPatchWriter::beginCellData(), indirectPatchWriter::beginFile(), fileWriter::close(), polyMesh::faces(), labelList(), IOobject::name(), primitiveMesh::nFaces(), fileWriter::open(), fileWriter::parallel(), polyMesh::points(), HashTable< T, Key, Hash >::sortedToc(), indirectPatchWriter::write(), and indirectPatchWriter::writeGeometry().
Referenced by writeTopoSet().
bool writeCellSetFaces (const polyMesh & mesh, const cellSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Write perimeter faces of cellset to vtk polydata file.
The data are the original cell ids The file name is with/without an extension.
————————————————————————
————————————————————————
————————————————————————
Definition at line 30 of file foamVtkWriteCellSetFaces.C.
References indirectPatchWriter::beginCellData(), indirectPatchWriter::beginFile(), primitiveMesh::cells(), fileWriter::close(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), polyMesh::faces(), forAll, topoSet::found(), primitiveMesh::isInternalFace(), labelList(), IOobject::name(), primitiveMesh::nCells(), fileWriter::open(), fileWriter::parallel(), polyMesh::points(), HashTable< T, Key, Hash >::size(), indirectPatchWriter::write(), and indirectPatchWriter::writeGeometry().
Referenced by writeTopoSet().
bool writePointSet (const polyMesh & mesh, const pointSet & set, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Write pointSet to VTK polydata file.
Only one CELL_DATA, which is the original pointID The file name is with/without an extension.
————————————————————————
————————————————————————
Definition at line 31 of file foamVtkWritePointSet.C.
References outputOptions::append(), Foam::vtk::legacy::beginPointData(), Foam::vtk::legacy::beginPoints(), ext(), fileExtension, format(), fileName::hasExt(), outputOptions::legacy(), fileName::lessExt(), Foam::mkDir(), IOobject::name(), outputOptions::newFormatter(), primitiveMesh::nPoints(), fileName::path(), pointLabels(), polyMesh::points(), Foam::reduce(), autoPtr< T >::ref(), HashTable< T, Key, Hash >::sortedToc(), writeList(), and writeListParallel().
Referenced by writeTopoSet().
Variable Documentation
const Foam::Enum< Foam::vtk::fileTag > fileExtension
File extension (without ".") for some vtk XML file content types.
Referenced by vtmWriter::append_vtp(), edgeMesh::readTypes(), and writePointSet().
const Foam::Enum< Foam::vtk::fileTag > fileContentVersions
Version string for some vtk XML file content types.
const Foam::Enum< Foam::vtk::fileTag > fileTagNames
Strings corresponding to the vtk XML tags.
Referenced by formatter::endCellData(), and formatter::tag().
const Foam::Enum< Foam::vtk::fileAttr > fileAttrNames
Strings corresponding to the vtk XML attributes.
const Foam::Enum< Foam::vtk::dataArrayAttr > dataArrayAttrNames
Strings corresponding to the vtk XML DataArray attributes.