OpenFOAM: Foam::vtk::legacy Namespace Reference
Foam::vtk::legacy Namespace Reference
Namespace for legacy VTK output constants and functions.
Functions
void fileHeader (std::ostream &os, const std::string &title, bool binary)
Emit header for legacy file.
void fileHeader (vtk::formatter &fmt, const std::string &title, const std::string &contentType)
Emit header for legacy file, with "ASCII" or "BINARY" depending on the formatter type.
void fileHeader (vtk::formatter &fmt, const std::string &title, vtk::fileTag contentType)
Emit header for legacy file, with "ASCII" or "BINARY" depending on the formatter type.
template<vtk::fileTag ContentType>
void fileHeader (vtk::formatter &fmt, const std::string &title)
Emit header for legacy file, with "ASCII" or "BINARY" depending on the formatter type.
void beginPoints (std::ostream &os, label nPoints)
Emit header for POINTS (with trailing newline).
void beginPolys (std::ostream &os, label nPolys, label nConnectivity)
Emit header for POLYGONS (with trailing newline).
void fieldData (vtk::formatter &fmt, label nFields)
Emit "FIELD FieldData <n>".
void beginFieldData (vtk::formatter &fmt, label nFields)
Emit legacy FIELD FieldData nFields.
void beginCellData (vtk::formatter &fmt, label nCells, label nFields)
Emit legacy CELL_DATA nCells, FIELD FieldData nFields.
void beginPointData (vtk::formatter &fmt, label nPoints, label nFields)
Emit legacy POINT_DATA nPoints, FIELD FieldData nFields.
void writeTimeValue (vtk::formatter &fmt, scalar timeValue)
Emit "TimeValue" for a FIELD entry (name as per Catalyst output)
template<direction nComp>
void floatField (vtk::formatter &fmt, const word &name, const label nEntries)
Start output of float field with the specified name.
template<direction nComp>
void doubleField (vtk::formatter &fmt, const word &name, const label nEntries)
Start output of double field with the specified name.
template<direction nComp>
void intField (vtk::formatter &fmt, const word &name, const label nEntries)
Start output of int field with the specified name.
Variables
const word fileExtension
Legacy file extension ("vtk")
const Foam::Enum< vtk::fileTag > contentNames
Legacy content names (POLYDATA, UNSTRUCTURED_GRID)
const Foam::Enum< vtk::fileTag > dataTypeNames
Legacy data type names (CELL_DATA, POINT_DATA)
Detailed Description
Namespace for legacy VTK output constants and functions.
Source files
foamVtkOutput.H
foamVtkOutput.C
foamVtkOutputTemplates.C
Function Documentation
void fileHeader (std::ostream & os, const std::string & title, bool binary)
Emit header for legacy file.
Writes "ASCII" or "BINARY" depending on specified type.
Definition at line 217 of file foamVtkOutput.C.
Referenced by fileHeader().
void fileHeader (vtk::formatter & fmt, const std::string & title, const std::string & contentType)
Emit header for legacy file, with "ASCII" or "BINARY" depending on the formatter type.
If the contentType is non-empty, it is used for "DATASET" line.
Definition at line 250 of file foamVtkOutput.C.
void fileHeader (vtk::formatter & fmt, const std::string & title, vtk::fileTag contentType) inline
Emit header for legacy file, with "ASCII" or "BINARY" depending on the formatter type.
Includes "DATASET" with the specified dataset type.
Definition at line 94 of file foamVtkOutputI.H.
References contentNames, and fileHeader().
void fileHeader (vtk::formatter & fmt, const std::string & title) inline
Emit header for legacy file, with "ASCII" or "BINARY" depending on the formatter type.
Includes "DATASET" of the templated dataset type.
Definition at line 106 of file foamVtkOutputI.H.
References contentNames, and fileHeader().
void beginPoints (std::ostream & os, label nPoints) inline
Emit header for POINTS (with trailing newline).
Definition at line 115 of file foamVtkOutputI.H.
Referenced by Foam::vtk::writePointSet().
void beginPolys (std::ostream & os, label nPolys, label nConnectivity) inline
Emit header for POLYGONS (with trailing newline).
The nConnectivity is the sum of all connectivity points used, but without additional space for the size prefixes. The additional prefix sizes are added internally.
Definition at line 123 of file foamVtkOutputI.H.
References Foam::nl.
void fieldData (vtk::formatter & fmt, label nFields) inline
Emit "FIELD FieldData <n>".
Definition at line 135 of file foamVtkOutputI.H.
References Foam::nl, and formatter::os().
Referenced by beginCellData(), beginFieldData(), and beginPointData().
void beginFieldData (vtk::formatter & fmt, label nFields) inline
Emit legacy FIELD FieldData nFields.
Definition at line 146 of file foamVtkOutputI.H.
References fieldData().
void beginCellData (vtk::formatter & fmt, label nCells, label nFields) inline
Emit legacy CELL_DATA nCells, FIELD FieldData nFields.
Definition at line 156 of file foamVtkOutputI.H.
References dataTypeNames, fieldData(), Foam::nl, and formatter::os().
void beginPointData (vtk::formatter & fmt, label nPoints, label nFields) inline
Emit legacy POINT_DATA nPoints, FIELD FieldData nFields.
Definition at line 171 of file foamVtkOutputI.H.
References dataTypeNames, fieldData(), Foam::nl, formatter::os(), and Foam::expressions::patchExpr::POINT_DATA.
Referenced by lagrangianWriter::endParcelData(), and Foam::vtk::writePointSet().
void writeTimeValue (vtk::formatter & fmt, scalar timeValue) inline
Emit "TimeValue" for a FIELD entry (name as per Catalyst output)
Definition at line 186 of file foamVtkOutputI.H.
void floatField (vtk::formatter & fmt, const word & name, const label nEntries) inline
Start output of float field with the specified name.
Definition at line 213 of file foamVtkOutputI.H.
References Foam::nl, and formatter::os().
void doubleField (vtk::formatter & fmt, const word & name, const label nEntries) inline
Start output of double field with the specified name.
Definition at line 199 of file foamVtkOutputI.H.
References Foam::nl, and formatter::os().
void intField (vtk::formatter & fmt, const word & name, const label nEntries) inline
Start output of int field with the specified name.
Definition at line 227 of file foamVtkOutputI.H.
References Foam::nl, and formatter::os().
Variable Documentation
const Foam::word fileExtension
Legacy file extension ("vtk")
const Foam::Enum< Foam::vtk::fileTag > contentNames
Legacy content names (POLYDATA, UNSTRUCTURED_GRID)
Referenced by fileHeader().
const Foam::Enum< Foam::vtk::fileTag > dataTypeNames
Legacy data type names (CELL_DATA, POINT_DATA)
Referenced by beginCellData(), and beginPointData().