OpenFOAM: Foam::BitOps Namespace Reference
Foam::BitOps Namespace Reference
Various bit-wise operations, etc.
Classes
struct bitInfo
An (unsigned) integral type adapter, for output of bit values.
Functions
unsigned int count (const UList< bool > &bools, const bool val=true)
Count number of 'true' entries.
bool all (const UList< bool > &bools)
True if all entries are 'true' or if the set is empty.
bool any (const UList< bool > &bools)
True if any entries are 'true'.
bool none (const UList< bool > &bools)
True if no entries are 'true'.
template<class UIntType >
unsigned int bit_count (UIntType x)
Count arbitrary number of bits (of an integral type)
template<>
unsigned int bit_count (uint32_t x)
Count bits in a 32-bit value (Hamming weight method)
template<>
unsigned int bit_count (uint64_t x)
Count bits in a 64-bit value (Hamming weight method)
template<class UIntType , unsigned BitWidth>
UIntType repeat_value (unsigned val)
Repeat a value of the given BitWidth into the destination output type.
template<class UIntType >
Ostream & print (Ostream &os, UIntType value, char off='0', char on='1')
Print 0/1 bits in the (unsigned) integral type.
Detailed Description
Various bit-wise operations, etc.
The population count uses the Hamming weight (http://en.wikipedia.org/wiki/Hamming_weight).
Function Documentation
unsigned int Foam::BitOps::count (const UList< bool > & bools, const bool val = true) inline
Count number of 'true' entries.
Parameters
val can be set to false to count the number of false values instead For compatibility with bitSet::count()
Definition at line 72 of file BitOps.H.
References UList< T >::begin(), UList< T >::end(), and Foam::val.
Referenced by MeshedSurface< Face >::checkZones(), hexRef8::consistentSlowRefinement(), decompositionMethod::decompose(), Histogram< List >::Histogram(), prefixOSstream::indent(), Foam::indicesImpl(), objectRegistry::names(), IOobjectList::names(), Foam::namesImpl(), blockMesh::numZonedBlocks(), refinementData::operator!=(), points_delaunay_naive_2d(), memorybuf::in::printBufInfo(), Foam::printHostsSubscription(), ensightReadFile::read(), clockValue::str(), wordRes::uniq(), cellVolumeWeight::update(), PtrListDetail< T >::write(), ensightFile::write(), Foam::writeAreaFields(), Foam::ensightOutput::writeCloudField(), Foam::writeDimFields(), Foam::writePointFields(), vtkWrite::writeVolFields(), ensightWrite::writeVolFields(), and Foam::writeVolFields().
bool Foam::BitOps::all (const UList< bool > & bools) inline
True if all entries are 'true' or if the set is empty.
For compatibility with bitSet::all()
Definition at line 82 of file BitOps.H.
References Foam::constant::physicoChemical::b, UList< T >::begin(), and UList< T >::end().
Referenced by decompositionMethod::decompose().
bool Foam::BitOps::any (const UList< bool > & bools) inline
True if any entries are 'true'.
For compatibility with bitSet::any()
Definition at line 92 of file BitOps.H.
References Foam::constant::physicoChemical::b, UList< T >::begin(), and UList< T >::end().
bool Foam::BitOps::none (const UList< bool > & bools) inline
True if no entries are 'true'.
For compatibility with bitSet::none()
Definition at line 102 of file BitOps.H.
References n, and x.
unsigned int Foam::BitOps::bit_count (UIntType x) inline
Count arbitrary number of bits (of an integral type)
Definition at line 112 of file BitOps.H.
unsigned int Foam::BitOps::bit_count (uint32_t x) inline
Count bits in a 32-bit value (Hamming weight method)
Definition at line 126 of file BitOps.H.
unsigned int Foam::BitOps::bit_count (uint64_t x) inline
Count bits in a 64-bit value (Hamming weight method)
Definition at line 139 of file BitOps.H.
UIntType Foam::BitOps::repeat_value (unsigned val) inline
Repeat a value of the given BitWidth into the destination output type.
Note
when BitWidth is 1, it is better to do directly.
*    (val ? ~0u : 0u)
*
Definition at line 159 of file BitOps.H.
Ostream& Foam::BitOps::print (Ostream & os, UIntType value, char off = '0', char on = '1') inline
Print 0/1 bits in the (unsigned) integral type.
Definition at line 190 of file BitOps.H.
Referenced by if(), dynamicIndexedOctree< Type >::print(), and indexedOctree< Type >::print().