OpenFOAM: Foam::stringOps Namespace Reference
Foam::stringOps Namespace Reference
Collection of static functions for various string-related operations.
Classes
struct natural_sort
Encapsulation of natural order sorting for algorithms.
Functions
std::string::size_type count (const std::string &str, const char c)
Count the number of occurrences of the specified character.
std::string::size_type count (const char *str, const char c)
Count the number of occurrences of the specified character.
bool match (const UList< wordRe > &patterns, const std::string &text)
Return true if text matches one of the regular expressions.
string expand (const std::string &str, const HashTable< string, word, string::hash > &mapping, const char sigil= '$')
Expand occurrences of variables according to the mapping and return the expanded string.
void inplaceExpand (std::string &s, const HashTable< string, word, string::hash > &mapping, const char sigil= '$')
Inplace expand occurrences of variables according to the mapping. Does not use environment values.
void inplaceExpand (std::string &s, const dictionary &dict, const bool allowEnv, const bool allowEmpty, const bool allowSubDict=false, const char sigil= '$')
Inplace expand occurrences of variables according to the dictionary and (optionally) environment variables.
string expand (const std::string &str, const dictionary &dict, const char sigil= '$')
Expand occurrences of dictionary or environment variables.
void inplaceExpand (std::string &s, const dictionary &dict, const char sigil= '$')
Inplace expand occurrences of dictionary or environment variables.
string expand (const std::string &str, const bool allowEmpty=false)
Expand initial tags, tildes, and all occurrences of environment variables.
void inplaceExpand (std::string &s, const bool allowEmpty=false)
Expand initial tags, tildes, and all occurrences of environment variables.
bool inplaceReplaceVar (std::string &s, const word &varName)
Replace environment variable contents with its name.
std::pair< size_t, size_t > findTrim (const std::string &s, size_t pos=0, size_t len=std::string::npos)
Find (first, last) non-space locations in string or sub-string.
string trimLeft (const std::string &s)
Return string trimmed of leading whitespace.
void inplaceTrimLeft (std::string &s)
Trim leading whitespace inplace.
string trimRight (const std::string &s)
Return string trimmed of trailing whitespace.
void inplaceTrimRight (std::string &s)
Trim trailing whitespace inplace.
string trim (const std::string &str)
Return string trimmed of leading and trailing whitespace.
void inplaceTrim (std::string &s)
Trim leading and trailing whitespace inplace.
string removeComments (const std::string &str)
Return string with C/C++ comments removed.
void inplaceRemoveComments (std::string &s)
Remove C/C++ comments inplace.
string lower (const std::string &str)
Return string transformed with std::tolower on each character.
void inplaceLower (std::string &s)
Inplace transform string with std::tolower on each character.
string upper (const std::string &str)
Return string transformed with std::toupper on each character.
void inplaceUpper (std::string &s)
Inplace transform string with std::toupper on each character.
template<class StringType >
Foam::SubStrings< StringType > split (const StringType &str, const char delim, const bool keepEmpty=false)
Split string into sub-strings at the delimiter character.
template<class StringType >
Foam::SubStrings< StringType > split (const StringType &str, const std::string &delim, const bool keepEmpty=false)
Split string into sub-strings using delimiter string.
template<class StringType >
Foam::SubStrings< StringType > splitAny (const StringType &str, const std::string &delim)
Split string into sub-strings using any characters in delimiter.
template<class StringType >
Foam::SubStrings< StringType > splitFixed (const StringType &str, const std::string::size_type width, const std::string::size_type start=0)
Split string into sub-strings using a fixed field width.
template<class StringType >
Foam::SubStrings< StringType > splitSpace (const StringType &str)
Split string into sub-strings at whitespace (TAB, NL, VT, FF, CR, SPC)
void writeWrapped (OSstream &os, const std::string &str, const std::string::size_type width, const std::string::size_type indent=0, const bool escape=false)
Output string with text wrapping.
string evaluate (const std::string &s, size_t pos=0, size_t len=std::string::npos)
A simple string evaluation that handles various basic expressions. For trivial input, use readScalar instead (faster).
int natstrcmp (const char *s1, const char *s2)
'Natural' compare for C-strings
Detailed Description
Collection of static functions for various string-related operations.
Source files
stringOps.H
stringOps.C
stringOpsTemplates.C
Function Documentation
std::string::size_type count (const std::string & str, const char c)
Count the number of occurrences of the specified character.
Definition at line 691 of file stringOps.C.
Referenced by string::replace().
std::string::size_type count (const char * str, const char c)
Count the number of occurrences of the specified character.
Correctly handles nullptr.
Definition at line 710 of file stringOps.C.
bool Foam::stringOps::match (const UList< wordRe > & patterns, const std::string & text) inline
Return true if text matches one of the regular expressions.
Definition at line 78 of file stringOps.H.
Referenced by degenerateMatcher::match(), regExpPosix::operator=(), keyType::operator=(), regExpCxx::operator=(), wordRe::operator=(), and scalarRange::operator==().
Foam::string expand (const std::string & str, const HashTable< string, word, string::hash > & mapping, const char sigil = '$')
Expand occurrences of variables according to the mapping and return the expanded string.
See Also
stringOps::inplaceExpand() for details
Definition at line 732 of file stringOps.C.
Referenced by exprString::exprString(), and exprString::valid().
void inplaceExpand (std::string & s, const HashTable< string, word, string::hash > & mapping, const char sigil = '$')
Inplace expand occurrences of variables according to the mapping. Does not use environment values.
Expansion includes:
Variables
$VAR
${VAR}
Default and alternative values as per the POSIX shell:
${parameter:-defValue} If parameter is unset or null, the defValue is substituted. Otherwise, the value of parameter is substituted.
${parameter:+altValue} If parameter is unset or null, nothing is substituted. Otherwise the altValue is substituted.
General behaviour:
Unknown entries are removed silently.
Malformed entries (eg, brace mismatch, sigil followed by unknown characters) are left as is.
Parameters
[in,out] s The string to modify inplace.
mapping The lookup table
sigil The leading sigil. Can be changed to avoid conflict with other string expansions. (default: '$')
Expansion behaviour
alternatives = True
environment = False
allow empty = True
subDict = Not applicable
Note
Currently only used by Foam::dynamicCode.
Definition at line 745 of file stringOps.C.
Referenced by dynamicCodeContext::addLineDirective(), CodedSource< Type >::read(), and string::removeRepeated().
void inplaceExpand (std::string & s, const dictionary & dict, const bool allowEnv, const bool allowEmpty, const bool allowSubDict = false, const char sigil = '$')
Inplace expand occurrences of variables according to the dictionary and (optionally) environment variables.
Expansion includes:
Dictionary variables and (optionally) environment variables
$VAR
${VAR}
${VAR:-defValue}
${VAR:+altValue}
Mathematical evaluation using stringOps::evaluate
${{EXPR}}
Current directory
leading "./" : the current directory - Foam::cwd()
Leading tag expansion for commonly used directories
<etc>/ : user/group/other OpenFOAM etc directory
<etc:[ugoa]+)>/ : user/group/other etc with specified location mode
<case>/ : The $FOAM_CASE directory
<constant>/ : The $FOAM_CASE/constant directory
<system>/ : The $FOAM_CASE/system directory
Tilde expansion
leading "~/" : home directory
leading "~user" : home directory for specified user
Default and alternative values as per the POSIX shell:
${parameter:-defValue} If parameter is unset or null, the defValue is substituted. Otherwise, the value of parameter is substituted.
${parameter:+altValue} If parameter is unset or null, nothing is substituted. Otherwise the altValue is substituted.
General behaviour:
Malformed entries (eg, brace mismatch, sigil followed by unknown characters) are left as is.
Supports recursive variable expansions. For example, "${var${num}}" and "${{100 + ${var}}}"
Parameters
[in,out] s The string to modify inplace
dict The dictionary context for the expansion
allowEnv Allow use of environment values as fallback
allowEmpty Allow empty expansions, or treat as Fatal
allowSubDict Allow expansion of subDict entries as well as primitive entries (default: false)
sigil The leading sigil. Can be changed to avoid conflict with other string expansions. (default: '$')
See Also
Foam::findEtcEntry(), Foam::findEtcEntries(), stringOps::evaluate()
Expansion behaviour
alternatives = True
environment = Given by parameter
allow empty = Given by parameter
subDict = Given by parameter (default: False)
Note
This function has too many parameters and should generally be avoided in user coding.
Definition at line 870 of file stringOps.C.
Foam::string expand (const std::string & str, const dictionary & dict, const char sigil = '$')
Expand occurrences of dictionary or environment variables.
Empty expansions are allowed. Serialization of subDict entries is permitted.
See Also
stringOps::inplaceExpand(std::string&, const dictionary&, char)
Definition at line 857 of file stringOps.C.
void inplaceExpand (std::string & s, const dictionary & dict, const char sigil = '$')
Inplace expand occurrences of dictionary or environment variables.
Empty expansions are allowed. Serialization of subDict entries is permitted.
See Also
stringOps::inplaceExpand (std::string&, const dictionary&, bool, bool, bool, char)
Expansion behaviour
alternatives = True
environment = True
allow empty = True
subDict = True
Definition at line 884 of file stringOps.C.
References Foam::expandString().
Foam::string expand (const std::string & str, const bool allowEmpty = false)
Expand initial tags, tildes, and all occurrences of environment variables.
See Also
stringOps::inplaceExpand(std::string&, bool);
Definition at line 897 of file stringOps.C.
void inplaceExpand (std::string & s, const bool allowEmpty = false)
Expand initial tags, tildes, and all occurrences of environment variables.
The expansion behaviour is identical to stringOps::inplaceExpand (std::string&, const dictionary&, bool, bool, bool, char) except that there is no dictionary and the environment variables are always enabled.
Expansion behaviour
alternatives = True
environment = True
allow empty = Given by parameter (default: False)
subDict = Not applicable
Definition at line 909 of file stringOps.C.
bool inplaceReplaceVar (std::string & s, const word & varName)
Replace environment variable contents with its name.
This is essentially the inverse operation for inplaceExpand for a single element. Return true if a replacement was successful.
Definition at line 920 of file stringOps.C.
References Foam::expandString().
std::pair<size_t, size_t> Foam::stringOps::findTrim (const std::string & s, size_t pos = 0, size_t len = std::string::npos)
Find (first, last) non-space locations in string or sub-string.
This may change to std::string_view in the future.
Referenced by evaluate().
Foam::string trimLeft (const std::string & s)
Return string trimmed of leading whitespace.
Definition at line 944 of file stringOps.C.
void inplaceTrimLeft (std::string & s)
Trim leading whitespace inplace.
Definition at line 966 of file stringOps.C.
Referenced by removeComments().
Foam::string trimRight (const std::string & s)
Return string trimmed of trailing whitespace.
Definition at line 986 of file stringOps.C.
void inplaceTrimRight (std::string & s)
Trim trailing whitespace inplace.
Definition at line 1006 of file stringOps.C.
Referenced by removeComments().
Foam::string trim (const std::string & str)
Return string trimmed of leading and trailing whitespace.
Definition at line 1060 of file stringOps.C.
void inplaceTrim (std::string & s)
Trim leading and trailing whitespace inplace.
Definition at line 1081 of file stringOps.C.
Referenced by dynamicCodeContext::addLineDirective(), and Foam::recursiveExpand().
Foam::string removeComments (const std::string & str)
Return string with C/C++ comments removed.
Definition at line 1088 of file stringOps.C.
References inplaceTrimLeft(), and inplaceTrimRight().
void inplaceRemoveComments (std::string & s)
Remove C/C++ comments inplace.
Definition at line 1096 of file stringOps.C.
References s.
Referenced by exprString::inplaceExpand().
Foam::string lower (const std::string & str)
Return string transformed with std::tolower on each character.
Definition at line 1192 of file stringOps.C.
Referenced by FixedList< T, N >::moveLast(), and UList< T >::moveLast().
void inplaceLower (std::string & s)
Inplace transform string with std::tolower on each character.
Definition at line 1200 of file stringOps.C.
References s.
Referenced by STARCDMeshReader::readBoundary().
Foam::string upper (const std::string & str)
Return string transformed with std::toupper on each character.
Definition at line 1212 of file stringOps.C.
Referenced by FixedList< T, N >::swapFirst(), and UList< T >::swapFirst().
void inplaceUpper (std::string & s)
Inplace transform string with std::toupper on each character.
Definition at line 1220 of file stringOps.C.
References s.
Foam::SubStrings< StringType > split (const StringType & str, const char delim, const bool keepEmpty = false)
Split string into sub-strings at the delimiter character.
Empty sub-strings are normally suppressed. Behaviour is ill-defined if delim is a NUL character.
Definition at line 25 of file stringOpsTemplates.C.
References SubStrings< String >::append(), and end().
Foam::SubStrings< StringType > split (const StringType & str, const std::string & delim, const bool keepEmpty = false)
Split string into sub-strings using delimiter string.
Empty sub-strings are normally suppressed.
Definition at line 61 of file stringOpsTemplates.C.
Foam::SubStrings< StringType > splitAny (const StringType & str, const std::string & delim)
Split string into sub-strings using any characters in delimiter.
Empty sub-strings are normally suppressed. Behaviour is ill-defined if delim is an empty string.
Definition at line 97 of file stringOpsTemplates.C.
Referenced by scalarRanges::parse().
Foam::SubStrings< StringType > splitFixed (const StringType & str, const std::string::size_type width, const std::string::size_type start = 0)
Split string into sub-strings using a fixed field width.
Behaviour is ill-defined if width is zero.
Parameters
str the string to be split
width the fixed field width for each sub-string
start the optional offset of where to start the splitting. Any text prior to start is ignored in the operation.
Definition at line 138 of file stringOpsTemplates.C.
Foam::SubStrings< StringType > splitSpace (const StringType & str)
Split string into sub-strings at whitespace (TAB, NL, VT, FF, CR, SPC)
Empty sub-strings are suppressed.
Definition at line 173 of file stringOpsTemplates.C.
void writeWrapped (OSstream & os, const std::string & str, const std::string::size_type width, const std::string::size_type indent = 0, const bool escape = false)
Output string with text wrapping.
Always includes a trailing newline, unless the string itself is empty.
Parameters
os the output stream
str the text to be output
width the max-width before wrapping
indent indentation for continued lines
escape escape any backslashes on output
Definition at line 1233 of file stringOps.C.
Foam::string evaluate (const std::string & s, size_t pos = 0, size_t len = std::string::npos)
A simple string evaluation that handles various basic expressions. For trivial input, use readScalar instead (faster).
The evaluation supports the following:
operations: - + * / %
functions: exp, log, log10, pow, sqrt, cbrt, sqr, mag, magSqr
trigonometric: sin, cos, tan, asin, acos, atan, atan2, hypot
hyperbolic: sinh, cosh, tanh
conversions: degToRad, radToDeg
type conversion: bool, mag
constants: pi(), true, false
limits: neg, pos, neg0, pos0, sign, floor, ceil, round
other: rand, rand(seed)
logic: ! ? : == != <= => < >
Note
Unlike C/C++, the ternary and logical operations are not short-circuiting. So additional guards may be required.
The rand() function returns a uniform scalar on [0-1] interval and uses a constant seed.
InfoErr<< "Evaluate " << str.substr(pos, len) << nl;
InfoErr<< "Evaluate " << str.substr(pos, len) << nl;
Definition at line 30 of file stringOpsEvaluate.C.
References findTrim(), exprResult::hasValue(), Foam::InfoErr, Foam::nl, parseDriver::parse(), exprDriver::result(), exprResult::size(), StringStreamAllocator< StreamType >::str(), and exprResult::writeValue().
Referenced by alphaContactAngleFvPatchScalarField::alphaContactAngleFvPatchScalarField(), basicSymmetryFaPatchField< Type >::basicSymmetryFaPatchField(), basicSymmetryFvPatchField< Type >::basicSymmetryFvPatchField(), constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField(), BlendedInterfacialModel< ModelType >::D(), directionMixedFvPatchField< Type >::directionMixedFvPatchField(), BlendedInterfacialModel< ModelType >::dmdt(), dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField(), codeStream::execute(), BlendedInterfacialModel< ModelType >::Ff(), fixedGradientFaPatchField< Type >::fixedGradientFaPatchField(), fixedGradientFvPatchField< Type >::fixedGradientFvPatchField(), CrankNicolsonDdtScheme< Type >::fvcDdt(), interfaceCompressionFvPatchScalarField::interfaceCompressionFvPatchScalarField(), mixedFaPatchField< Type >::mixedFaPatchField(), Foam::recursiveExpand(), temperatureDependentAlphaContactAngleFvPatchScalarField::temperatureDependentAlphaContactAngleFvPatchScalarField(), timeVaryingAlphaContactAngleFvPatchScalarField::timeVaryingAlphaContactAngleFvPatchScalarField(), wallHeatTransferFvPatchScalarField::wallHeatTransferFvPatchScalarField(), kqRWallFunctionFvPatchField< Type >::write(), and BlendedInterfacialModel< ModelType >::writeData().
int natstrcmp (const char * s1, const char * s2)
'Natural' compare for C-strings
Uses algorithm and code from Jan-Marten Spit jmspi.nosp@m.t@eu.nosp@m.ronet.nosp@m..nl
In the 'natural' comparison, strings are compared alphabetically and numerically. Thus 'file010.txt' sorts after 'file2.txt'
Parameters
s1 left string
s2 right string
Returns
-1 when s1 < s2, 0 when s1 == s2, 1 when s1 > s2
Definition at line 118 of file stringOpsSort.C.
Referenced by natural_sort::compare().