OpenFOAM: Foam::fac Namespace Reference
Foam::fac Namespace Reference
Functions
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > average (const GeometricField< Type, faePatchField, edgeMesh > &)
Area-weighted average a edgeField creating a areaField.
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &)
Area-weighted average a edgeField creating a areaField.
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > average (const GeometricField< Type, faPatchField, areaMesh > &)
Area-weighted average a edgeField creating a areaField.
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
Area-weighted average a edgeField creating a areaField.
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > d2dt2 (const dimensioned< Type > dt, const faMesh &mesh)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > d2dt2 (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > d2dt2 (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ddt (const dimensioned< Type > dt, const faMesh &mesh)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ddt (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ddt (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ddt (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> div (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> div (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> div (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> div (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > div (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > div (const GeometricField< Type, faPatchField, areaMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faPatchField, areaMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > div (const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > edgeIntegrate (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > edgeIntegrate (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &tssf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > edgeSum (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > edgeSum (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> grad (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> grad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> grad (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> grad (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faePatchField, edgeMesh > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > grad (const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const dimensionedScalar &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const areaScalarField &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > &tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const edgeScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const edgeScalarField &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > &tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const edgeScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const edgeScalarField &gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > &tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> ndiv (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvvf, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> ndiv (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh >> ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const edgeScalarField &flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< Type,
faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > &tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faPatchField, areaMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> ngrad (const GeometricField< Type, faePatchField, edgeMesh > &ssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> ngrad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &tssf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> ngrad (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> ngrad (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh >> ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faePatchField, edgeMesh > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faPatchField, areaMesh > &, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &, const word &name)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > ngrad (const GeometricField< Type, faPatchField, areaMesh > &)
template<class Type >
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, faPatchField, areaMesh > > ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
template<class Type >
static tmp
< edgeInterpolationScheme
< Type > > scheme (const edgeScalarField &faceFlux, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp
< edgeInterpolationScheme
< Type > > scheme (const edgeScalarField &faceFlux, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp
< edgeInterpolationScheme
< Type > > scheme (const faMesh &mesh, Istream &schemeData)
Return weighting factors for scheme given from Istream.
template<class Type >
static tmp
< edgeInterpolationScheme
< Type > > scheme (const faMesh &mesh, const word &name)
Return weighting factors for scheme given by name in dictionary.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const edgeScalarField &faceFlux, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const edgeScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in faSchemes.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const edgeScalarField &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in faSchemes.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const tmp< edgeScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in faSchemes.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const tmp< edgeScalarField > &faceFlux, const word &name)
Interpolate field onto faces using scheme given by name in faSchemes.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, Istream &schemeData)
Interpolate field onto faces using scheme given by Istream.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf, const word &name)
Interpolate field onto faces using scheme given by name in faSchemes.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf, const word &name)
Interpolate field onto faces using scheme given by name in faSchemes.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tvf)
Interpolate tmp field onto faces using central differencing.
template<class Type >
static tmp< GeometricField
< Type, faePatchField,
edgeMesh > > interpolate (const GeometricField< Type, faPatchField, areaMesh > &tvf)
Interpolate field onto faces using central differencing.
Function Documentation
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Area-weighted average a edgeField creating a areaField.
Definition at line 40 of file facAverage.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::dimensions(), edgeSum(), forAll, IOobject::instance(), faMesh::magLe(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, tmp< T >::ref(), and GeometricField< Type, PatchField, GeoMesh >::ref().
Referenced by Foam::bound(), if(), and PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints().
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faePatchField, edgeMesh >> & tssf)
Area-weighted average a edgeField creating a areaField.
Definition at line 84 of file facAverage.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const GeometricField< Type, faPatchField, areaMesh > & vtf)
Area-weighted average a edgeField creating a areaField.
Definition at line 100 of file facAverage.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > average (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvtf)
Area-weighted average a edgeField creating a areaField.
Definition at line 111 of file facAverage.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const dimensioned< Type > dt, const faMesh & mesh)
Definition at line 39 of file facD2dt2.C.
References mesh, and faD2dt2Scheme< Type >::New().
Referenced by optionList::d2dt2().
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 54 of file facD2dt2.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 68 of file facD2dt2.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > d2dt2 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 86 of file facD2dt2.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const dimensioned< Type > dt, const faMesh & mesh)
Definition at line 40 of file facDdt.C.
References faSchemes::ddtScheme(), mesh, dimensioned< Type >::name(), and faDdtScheme< Type >::New().
Referenced by for(), forAll(), and if().
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 56 of file facDdt.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 71 of file facDdt.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ddt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 90 of file facDdt.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 43 of file facDiv.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), edgeIntegrate(), Tensor< scalar >::I, GeometricField< Type, PatchField, GeoMesh >::internalField(), DimensionedField< Type, GeoMesh >::mesh(), n, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), Foam::sqr(), and Foam::transform().
Referenced by Foam::CorrectPhi(), div(), gaussLaplacianScheme< Type >::famLaplacian(), for(), and if().
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< GeometricField< Type, faePatchField, edgeMesh >> & tssf)
Definition at line 65 of file facDiv.C.
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::div (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 84 of file facDiv.C.
References Tensor< scalar >::I, DimensionedField< Type, GeoMesh >::mesh(), n, ref(), Foam::sqr(), and Foam::transform().
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::div (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvvf, const word & name)
Definition at line 131 of file facDiv.C.
References div().
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::div (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 154 of file facDiv.C.
References div(), and IOobject::name().
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::div (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvvf)
Definition at line 171 of file facDiv.C.
References div().
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 189 of file facDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 219 of file facDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 237 of file facDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 255 of file facDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 274 of file facDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 289 of file facDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 306 of file facDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > div (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 323 of file facDiv.C.
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::div (const GeometricField< Type, faPatchField, areaMesh > & , const word & name)
Definition at line 84 of file facDiv.C.
References Tensor< scalar >::I, DimensionedField< Type, GeoMesh >::mesh(), n, ref(), Foam::sqr(), and Foam::transform().
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::div (const tmp< GeometricField< Type, faPatchField, areaMesh >> & , const word & name)
Definition at line 131 of file facDiv.C.
References div().
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::div (const GeometricField< Type, faPatchField, areaMesh > &)
Definition at line 154 of file facDiv.C.
References div(), and IOobject::name().
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::div (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
Definition at line 171 of file facDiv.C.
References div().
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeIntegrate (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 40 of file facEdgeIntegrate.C.
References faMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), IOobject::db(), Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), mesh, DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), faMesh::neighbour(), faMesh::owner(), GeometricField< Type, PatchField, GeoMesh >::ref(), faMesh::S(), and Foam::Zero.
Referenced by div(), grad(), ndiv(), and ngrad().
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeIntegrate (const tmp< GeometricField< Type, faePatchField, edgeMesh >> & tssf)
Definition at line 96 of file facEdgeIntegrate.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeSum (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 112 of file facEdgeIntegrate.C.
Referenced by average().
tmp< GeometricField< Type, faPatchField, areaMesh > > edgeSum (const tmp< GeometricField< Type, faePatchField, edgeMesh >> & tssf)
Definition at line 165 of file facEdgeIntegrate.C.
tmp< GeometricField < typename outerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::grad (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 49 of file facGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), edgeIntegrate(), DimensionedField< Type, GeoMesh >::mesh(), n, and tmp< T >::ref().
Referenced by correctedLnGrad< Type >::correction(), fourthLnGrad< Type >::correction(), skewCorrectedSnGrad< Type >::fullGradCorrection(), correctedSnGrad< Type >::fullGradCorrection(), grad(), if(), ParticleTrap< CloudType >::postEvolve(), and skewCorrected< Type >::skewCorrection().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::grad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> & tssf)
Definition at line 76 of file facGrad.C.
References grad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::grad (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 99 of file facGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::mesh(), n, gradScheme< Type >::New(), ref(), and tmp< T >::ref().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 132 of file facGrad.C.
References grad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::grad (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 161 of file facGrad.C.
References grad(), and IOobject::name().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 178 of file facGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::grad (const GeometricField< Type, faePatchField, edgeMesh > &)
Definition at line 49 of file facGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), edgeIntegrate(), DimensionedField< Type, GeoMesh >::mesh(), n, and tmp< T >::ref().
Referenced by correctedLnGrad< Type >::correction(), fourthLnGrad< Type >::correction(), skewCorrectedSnGrad< Type >::fullGradCorrection(), correctedSnGrad< Type >::fullGradCorrection(), grad(), if(), ParticleTrap< CloudType >::postEvolve(), and skewCorrected< Type >::skewCorrection().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::grad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &)
Definition at line 76 of file facGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::grad (const GeometricField< Type, faPatchField, areaMesh > & , const word & name)
Definition at line 99 of file facGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::mesh(), n, gradScheme< Type >::New(), ref(), and tmp< T >::ref().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & , const word & name)
Definition at line 132 of file facGrad.C.
References grad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::grad (const GeometricField< Type, faPatchField, areaMesh > &)
Definition at line 161 of file facGrad.C.
References grad(), and IOobject::name().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::grad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
Definition at line 178 of file facGrad.C.
References grad().
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 40 of file facLaplacian.C.
References DimensionedField< Type, GeoMesh >::mesh(), Foam::name(), and laplacianScheme< Type >::New().
Referenced by Foam::CorrectPhi(), for(), forAll(), if(), and laplacian().
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 55 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 72 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 82 of file facLaplacian.C.
References laplacian(), and IOobject::name().
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 98 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 110 of file facLaplacian.C.
References laplacian().
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 128 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const dimensionedScalar & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 142 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 159 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 175 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 192 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 209 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 228 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 244 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const areaScalarField & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 260 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< areaScalarField > & tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 276 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const edgeScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 293 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 309 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const edgeScalarField & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 326 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > & tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 342 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const edgeScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 361 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 377 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const edgeScalarField & gamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 393 of file facLaplacian.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > laplacian (const tmp< edgeScalarField > & tgamma, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 408 of file facLaplacian.C.
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 40 of file facLnGrad.C.
References DimensionedField< Type, GeoMesh >::mesh(), Foam::name(), and lnGradScheme< Type >::New().
Referenced by fourthLnGrad< Type >::correction().
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 56 of file facLnGrad.C.
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 73 of file facLnGrad.C.
tmp< GeometricField< Type, faePatchField, edgeMesh > > lnGrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 84 of file facLnGrad.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 43 of file facNDiv.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), edgeIntegrate(), GeometricField< Type, PatchField, GeoMesh >::internalField(), DimensionedField< Type, GeoMesh >::mesh(), n, GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and tmp< T >::ref().
Referenced by ndiv().
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< GeometricField< Type, faePatchField, edgeMesh >> & tssf)
Definition at line 64 of file facNDiv.C.
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::ndiv (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 83 of file facNDiv.C.
References DimensionedField< Type, GeoMesh >::mesh(), n, ref(), and GeometricField< Type, PatchField, GeoMesh >::ref().
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvvf, const word & name)
Definition at line 115 of file facNDiv.C.
References ndiv().
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::ndiv (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 139 of file facNDiv.C.
References IOobject::name(), and ndiv().
tmp< GeometricField < typename innerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvvf)
Definition at line 156 of file facNDiv.C.
References ndiv().
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 174 of file facNDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 205 of file facNDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 224 of file facNDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 243 of file facNDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 263 of file facNDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 278 of file facNDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const edgeScalarField & flux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 295 of file facNDiv.C.
tmp< GeometricField< Type, faPatchField, areaMesh > > ndiv (const tmp< edgeScalarField > & tflux, const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 312 of file facNDiv.C.
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ndiv (const GeometricField< Type, faPatchField, areaMesh > & , const word & name)
Definition at line 83 of file facNDiv.C.
References DimensionedField< Type, GeoMesh >::mesh(), n, ref(), and GeometricField< Type, PatchField, GeoMesh >::ref().
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> & , const word & name)
Definition at line 115 of file facNDiv.C.
References ndiv().
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ndiv (const GeometricField< Type, faPatchField, areaMesh > &)
Definition at line 139 of file facNDiv.C.
References IOobject::name(), and ndiv().
tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ndiv (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
Definition at line 156 of file facNDiv.C.
References ndiv().
tmp< GeometricField < typename outerProduct<vector, Type>::type, faPatchField, areaMesh >> Foam::fac::ngrad (const GeometricField< Type, faePatchField, edgeMesh > & ssf)
Definition at line 50 of file facNGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), edgeIntegrate(), DimensionedField< Type, GeoMesh >::mesh(), n, and tmp< T >::ref().
Referenced by ngrad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::ngrad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> & tssf)
Definition at line 78 of file facNGrad.C.
References ngrad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::ngrad (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 102 of file facNGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::mesh(), n, gradScheme< Type >::New(), ref(), and tmp< T >::ref().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name)
Definition at line 135 of file facNGrad.C.
References ngrad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::ngrad (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 165 of file facNGrad.C.
References IOobject::name(), and ngrad().
tmp< GeometricField < typename outerProduct<vector,Type>::type, faPatchField, areaMesh >> Foam::fac::ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf)
Definition at line 182 of file facNGrad.C.
References ngrad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ngrad (const GeometricField< Type, faePatchField, edgeMesh > &)
Definition at line 50 of file facNGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), edgeIntegrate(), DimensionedField< Type, GeoMesh >::mesh(), n, and tmp< T >::ref().
Referenced by ngrad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ngrad (const tmp< GeometricField< Type, faePatchField, edgeMesh >> &)
Definition at line 78 of file facNGrad.C.
References ngrad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ngrad (const GeometricField< Type, faPatchField, areaMesh > & , const word & name)
Definition at line 102 of file facNGrad.C.
References GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DimensionedField< Type, GeoMesh >::mesh(), n, gradScheme< Type >::New(), ref(), and tmp< T >::ref().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> & , const word & name)
Definition at line 135 of file facNGrad.C.
References ngrad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ngrad (const GeometricField< Type, faPatchField, areaMesh > &)
Definition at line 165 of file facNGrad.C.
References IOobject::name(), and ngrad().
tmp< GeometricField <typename outerProduct<vector, Type>::type, faPatchField, areaMesh> > Foam::fac::ngrad (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
Definition at line 182 of file facNGrad.C.
References ngrad().
static tmp<edgeInterpolationScheme<Type> > Foam::fac::scheme (const edgeScalarField & faceFlux, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
static tmp<edgeInterpolationScheme<Type> > Foam::fac::scheme (const edgeScalarField & faceFlux, const word & name) static
Return weighting factors for scheme given by name in dictionary.
static tmp<edgeInterpolationScheme<Type> > Foam::fac::scheme (const faMesh & mesh, Istream & schemeData) static
Return weighting factors for scheme given from Istream.
static tmp<edgeInterpolationScheme<Type> > Foam::fac::scheme (const faMesh & mesh, const word & name) static
Return weighting factors for scheme given by name in dictionary.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const edgeScalarField & faceFlux, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
Referenced by pointLinear< Type >::correction(), deferredCorrection< Type >::correction(), for(), forAll(), faceCorrectedSnGrad< Type >::fullGradCorrection(), if(), interpolationCellPoint< Type >::interpolate(), and PhiScheme< Type, PhiLimiter >::limiter().
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const edgeScalarField & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in faSchemes.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const edgeScalarField & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in faSchemes.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const tmp< edgeScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in faSchemes.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const tmp< edgeScalarField > & faceFlux, const word & name) static
Interpolate field onto faces using scheme given by name in faSchemes.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, Istream & schemeData) static
Interpolate field onto faces using scheme given by Istream.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in faSchemes.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf, const word & name) static
Interpolate field onto faces using scheme given by name in faSchemes.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tvf) static
Interpolate tmp field onto faces using central differencing.
static tmp<GeometricField<Type, faePatchField, edgeMesh> > Foam::fac::interpolate (const GeometricField< Type, faPatchField, areaMesh > & tvf) static
Interpolate field onto faces using central differencing.