OpenFOAM: Foam::ListOps Namespace Reference
Foam::ListOps Namespace Reference
Various utility functions to work on Lists.
Classes
struct appendEqOp
List helper to append y elements onto the end of x.
struct uniqueEqOp
List helper to append y unique elements onto the end of x.
struct less
A list compare binary predicate for normal sort.
struct greater
A list compare binary predicate for reverse sort.
Functions
void identity (labelUList &map, label start=0)
Set identity map with (map[i] == i)
template<class ListType , class UnaryPredicate >
label find (const ListType &input, const UnaryPredicate &pred, const label start=0)
Find index of the first occurrence that satisfies the predicate.
template<class ListType , class UnaryPredicate >
bool found (const ListType &input, const UnaryPredicate &pred, const label start=0)
True if there is a value in the list that satisfies the predicate.
template<class T >
void setValue (UList< T > &list, const labelUList &locations, const T &val)
Set various locations of the list with a specified value.
template<class T >
void setValue (UList< T > &list, const labelHashSet &locations, const T &val)
Set various locations of the list with a specified value.
template<class T >
void setValue (UList< T > &list, const UList< bool > &locations, const T &val)
Set various locations of the list with a specified value.
template<class T >
void setValue (UList< T > &list, const bitSet &locations, const T &val)
Set various locations of the list with a specified value.
template<class T , class T2 , class UnaryOperation >
List< T > create (const UList< T2 > &input, const UnaryOperation &op)
Create a List from a List of a dissimilar type, using the entire list.
template<class T , class InputIterator , class UnaryOperation >
List< T > create (InputIterator first, InputIterator last, const UnaryOperation &op)
Create a List from an iterator range [first,last) of a dissimilar type.
template<class T >
List< T > createWithValue (const label len, const labelUList &locations, const T &val, const T &deflt=T())
Create a List filled with default values and various locations with another specified value.
template<class T >
List< T > createWithValue (const label len, const labelHashSet &locations, const T &val, const T &deflt=T())
Create a List filled with default values and various locations with another specified value.
template<class T >
List< T > createWithValue (const label len, const UList< bool > &locations, const T &val, const T &deflt=T())
Create a List filled with default values and various locations with another specified value.
template<class T >
List< T > createWithValue (const label len, const bitSet &locations, const T &val, const T &deflt=T())
Create a List filled with default values and various locations with another specified value.
template<class T >
List< T > createWithValue (const label len, const label index, const T &val, const T &deflt=T())
Create a List filled with default values and one specified value, which is copy assigned at the specified index.
template<class T >
List< T > createWithValue (const label len, const label index, T &&val, const T &deflt=T())
Create a List filled with default values and one specified value, which is move assigned at the specified index.
Detailed Description
Various utility functions to work on Lists.
Source files
ListOps.H
ListOps.C
ListOpsTemplates.C
Function Documentation
void identity (labelUList & map, label start = 0)
Set identity map with (map[i] == i)
Optionally with an alternative start index, so that (map[i] == i+start)
Definition at line 195 of file ListOps.C.
References Foam::reorder().
label Foam::ListOps::find (const ListType & input, const UnaryPredicate & pred, const label start = 0)
Find index of the first occurrence that satisfies the predicate.
When start is specified, any occurrences before start are ignored. Linear search.
Returns
position in list or -1 if not found.
Referenced by HashPtrTable< T, Key, Hash >::clear(), HashPtrTable< T, Key, Hash >::erase(), objectRegistry::erase(), string::hasExt(), scalars::match(), FixedList< T, N >::resize(), setValue(), UList< T >::shallowCopy(), and regExpPosix::swap().
bool found (const ListType & input, const UnaryPredicate & pred, const label start = 0)
True if there is a value in the list that satisfies the predicate.
When start is specified, any occurences before start are ignored. Linear search.
Returns
true if found.
Definition at line 1156 of file ListOpsTemplates.C.
void setValue (UList< T > & list, const labelUList & locations, const T & val)
Set various locations of the list with a specified value.
Parameters
list the list to modify
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
Definition at line 1168 of file ListOpsTemplates.C.
References find().
void setValue (UList< T > & list, const labelHashSet & locations, const T & val)
Set various locations of the list with a specified value.
Parameters
list the list to modify
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
Definition at line 1189 of file ListOpsTemplates.C.
void setValue (UList< T > & list, const UList< bool > & locations, const T & val)
Set various locations of the list with a specified value.
Parameters
list the list to modify
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
Definition at line 1210 of file ListOpsTemplates.C.
void setValue (UList< T > & list, const bitSet & locations, const T & val)
Set various locations of the list with a specified value.
Parameters
list the list to modify
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
Definition at line 1233 of file ListOpsTemplates.C.
List<T> Foam::ListOps::create (const UList< T2 > & input, const UnaryOperation & op)
Create a List from a List of a dissimilar type, using the entire list.
For example, convert a list of ints to floats, vectors etc.
Parameters
input the list input values.
op the unary conversion operator, which can be used to convert to other types.
* auto neg = ListOps::create<label>
* (
*     ints,
*     std::negate<label>()
*);
*
* auto labels = ListOps::create<label>
* (
*     ints,
*     labelOp<int>()
*);
*
* auto vectors = ListOps::create<vector>
* (
*     ints,
*     [](const int& val){ return vector(1.5*val, 0, 0); }
*);
*
*
List<T> Foam::ListOps::create (InputIterator first, InputIterator last, const UnaryOperation & op)
Create a List from an iterator range [first,last) of a dissimilar type.
Uses std::distance for the size.
Parameters
first the begin of the iterator range
last the end of the iterator range
op the unary conversion operator, which can be used to convert to other types.
List<T> Foam::ListOps::createWithValue (const label len, const labelUList & locations, const T & val, const T & deflt = T())
Create a List filled with default values and various locations with another specified value.
Parameters
len the length of the list
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
deflt the initialization default value
List<T> Foam::ListOps::createWithValue (const label len, const labelHashSet & locations, const T & val, const T & deflt = T())
Create a List filled with default values and various locations with another specified value.
Parameters
len the length of the list
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
deflt the initialization default value
List<T> Foam::ListOps::createWithValue (const label len, const UList< bool > & locations, const T & val, const T & deflt = T())
Create a List filled with default values and various locations with another specified value.
Parameters
len the length of the list
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
deflt the initialization default value
List<T> Foam::ListOps::createWithValue (const label len, const bitSet & locations, const T & val, const T & deflt = T())
Create a List filled with default values and various locations with another specified value.
Parameters
len the length of the list
locations where to apply the specified value An out-of-range index is silently ignored.
val the value to set at the specified locations
deflt the initialization default value
List<T> Foam::ListOps::createWithValue (const label len, const label index, const T & val, const T & deflt = T())
Create a List filled with default values and one specified value, which is copy assigned at the specified index.
Parameters
len the length of the list
index where to apply the specified value. An out-of-range index is silently ignored.
val the value to copy assign at the specified index
deflt the initialization default value
List<T> Foam::ListOps::createWithValue (const label len, const label index, T && val, const T & deflt = T())
Create a List filled with default values and one specified value, which is move assigned at the specified index.
Parameters
len the length of the list
index where to apply the specified value. An out-of-range index is silently ignored.
val the value to move assign at the specified index
deflt the initialization default value
For example,
* // Gather all unique points on master
*
* List<pointField> gatheredPoints(Pstream::nProcs());
* gatheredPoints[Pstream::myProcNo()] = pointField
* (
*     mesh.points(),
*     uniqueMeshPoints
*);
* ...
*
* // Or else
* auto gatheredPoints = ListOps::createWithValue<pointField>
* (
*     Pstream::nProcs(),
*     Pstream::myProcNo(),
*     pointField(mesh.points(), uniqueMeshPoints)
*);
* ...
*
*