OpenFOAM: src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidProperties.C File Reference
solidProperties.C File Reference
Namespaces
Foam
Namespace for OpenFOAM.
Functions
defineTypeNameAndDebug (solidProperties, 0)
defineRunTimeSelectionTable (solidProperties,)
defineRunTimeSelectionTable (solidProperties, dictionary)
Hf_ (dict.get< scalar >("Hf"))
emissivity_ (dict.get< scalar >("emissivity"))
Detailed Description
Original source file solidProperties.C
Definition in file solidProperties.C.
Function Documentation
Hf_ (dict.get< scalar > "Hf")
Referenced by eRefConstThermo< EquationOfState >::Ea(), solidProperties::Hs(), hConstThermo< EquationOfState >::S(), hRefConstThermo< EquationOfState >::S(), eConstThermo< EquationOfState >::S(), hPowerThermo< EquationOfState >::S(), and hPolynomialThermo< EquationOfState, PolySize >::S().
emissivity_ (dict.get< scalar > "emissivity")
Referenced by solidProperties::W().