OpenFOAM: applications/solvers/lagrangian/simpleCoalParcelFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< rhoReactionThermo > pThermo (rhoReactionThermo::New(mesh))
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.get< word >("inertSpecie"))
if (!composition.species().found(inertSpecie))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "\nReading field U\n"
<< endl;volVectorField U(IOobject("U",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());const
dimensionedScalar rhoMax("rhoMax",
dimDensity, GREAT, simple.dict());const
dimensionedScalar rhoMin("rhoMin",
dimDensity, Zero, simple.dict());Info
<< "Creating turbulence
model\n"<< endl;autoPtr
< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Info<< "Creating reaction
model\n"<< endl;autoPtr
< CombustionModel
< rhoReactionThermo > > reaction (CombustionModel< rhoReactionThermo >::New(thermo, turbulence()))
forAll (Y, i)
fields add (thermo.he())
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
Variables
rhoReactionThermo & thermo = pThermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & p = thermo.p()
Info<< "Creating multi-variate
interpolation scheme\n"<< endl;multivariateSurfaceInterpolationScheme
< scalar >::fieldTable fields
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<rhoReactionThermo> pThermo (rhoReactionThermo:: Newmesh)
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo.get< word > "inertSpecie")
if (!composition. species).found(inertSpecie)
Definition at line 15 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, inertSpecie(), and thermo.
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());const dimensionedScalar rhoMax("rhoMax", dimDensity, GREAT, simple.dict());const dimensionedScalar rhoMin("rhoMin", dimDensity, Zero, simple.dict());Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel:: Newrho, U, phi, thermo)
Info<< "Creating reaction model\n" << endl;autoPtr<CombustionModel<rhoReactionThermo> > reaction (CombustionModel< rhoReactionThermo >:: Newthermo, turbulence())
forAll (Y , i)
Definition at line 80 of file createFields.H.
References i.
fields add (thermo. he())
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
Variable Documentation
rhoReactionThermo& thermo = pThermo()
Definition at line 6 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 11 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 12 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 23 of file createFields.H.
Info<< "Creating multi-variate interpolation scheme\n" << endl;multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 78 of file createFields.H.