OpenFOAM: applications/solvers/lagrangian/reactingParcelFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< rhoReactionThermo > pThermo (rhoReactionThermo::New(mesh))
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.get< word >("inertSpecie"))
if (!composition.species().found(inertSpecie))
Info<< "Creating field rho\n"
<< endl;volScalarField rho(IOobject("rho",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE),
thermo.rho());volScalarField
&p=thermo.p();Info
<< "\nReading field U\n"
<< endl;volVectorField U(IOobject("U",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);Info
<< "Creating turbulence
model\n"<< endl;autoPtr
< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Info<< "Creating combustion
model\n"<< endl;autoPtr
< CombustionModel
< rhoReactionThermo > > combustion (CombustionModel< rhoReactionThermo >::New(thermo, turbulence()))
volScalarField p_rgh (IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh)
pressureControl pressureControl (p, rho, pimple.dict(), false)
mesh setFluxRequired (p_rgh.name())
forAll (Y, i)
fields add (thermo.he())
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), mesh,)
Variables
rhoReactionThermo & thermo = pThermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
p_rgh = p - rho*gh
Info<< "Creating multi-variate
interpolation scheme\n"<< endl;multivariateSurfaceInterpolationScheme
< scalar >::fieldTable fields
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<rhoReactionThermo> pThermo (rhoReactionThermo:: Newmesh)
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo.get< word > "inertSpecie")
if (!composition. species).found(inertSpecie)
Definition at line 14 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, inertSpecie(), and thermo.
Info<< "Creating field rho\n" << endl;volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField& p = thermo.p();Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel:: Newrho, U, phi, thermo)
Info<< "Creating combustion model\n" << endl;autoPtr<CombustionModel<rhoReactionThermo> > combustion (CombustionModel< rhoReactionThermo >:: Newthermo, turbulence())
volScalarField p_rgh (IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE) , mesh)
pressureControl pressureControl (p , rho , pimple. dict(), false)
mesh setFluxRequired (p_rgh. name())
forAll (Y , i)
Definition at line 100 of file createFields.H.
References i.
fields add (thermo. he())
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE) , mesh)
Variable Documentation
rhoReactionThermo& thermo = pThermo()
Definition at line 5 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 10 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 11 of file createFields.H.
p_rgh = p - rho*gh
Definition at line 91 of file createFields.H.
Info<< "Creating multi-variate interpolation scheme\n" << endl;multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 98 of file createFields.H.