OpenFOAM: applications/solvers/combustion/XiFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< psiuReactionThermo > pThermo (psiuReactionThermo::New(mesh))
thermo validate (args.executable(),"ha","ea")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
Info<< "min(b) = "<< min(b).value()
<< endl;Info<< "\nReading
field U\n"<< endl;volVectorField
U(IOobject("U",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info
<< "Creating turbulence
model\n"<< endl;autoPtr
< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Info<< "Creating field Xi\n"
<< endl;volScalarField Xi(IOobject("Xi",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);Info
<< "Creating the unstrained
laminar flame speed\n"<< endl;autoPtr
< laminarFlameSpeed > unstrainedLaminarFlameSpeed (laminarFlameSpeed::New(thermo))
fields add (b)
fields add (thermo.he())
Variables
psiuReactionThermo & thermo = pThermo()
basicSpecieMixture & composition = thermo.composition()
volScalarField & p = thermo.p()
volScalarField & b = composition.Y("b")
Wien displacement law constant: default SI units: [m.K].
Info<< "Reading strained
laminar flame speed field Su\n"
<< endl;volScalarField Su(IOobject("Su",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);dimensionedScalar
SuMin=0.01 *Su.average();dimensionedScalar
SuMax=4 *Su.average();Info
<< "Calculating turbulent
flame speed field St\n"<< endl;volScalarField
St(IOobject("St",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE), Xi *Su);multivariateSurfaceInterpolationScheme
< scalar >::fieldTable fields
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiuReactionThermo> pThermo (psiuReactionThermo:: Newmesh)
thermo validate (args. executable(), "ha" , "ea")
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Info<< "min(b) = " << min(b).value() << endl;Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);mesh.setFluxRequired(p.name());Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel:: Newrho, U, phi, thermo)
Info<< "Creating field Xi\n" << endl;volScalarField Xi(IOobject ("Xi", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating the unstrained laminar flame speed\n" << endl;autoPtr<laminarFlameSpeed> unstrainedLaminarFlameSpeed (laminarFlameSpeed:: Newthermo)
fields add (b)
fields add (thermo. he())
Variable Documentation
psiuReactionThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 10 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 25 of file createFields.H.
volScalarField& b = composition.Y("b")
Wien displacement law constant: default SI units: [m.K].
Definition at line 27 of file createFields.H.
Referenced by Foam::BitOps::all(), Foam::BitOps::any(), Foam::vectorTools::areAcute(), Foam::checkDims(), linearEqn::derivative(), quadraticEqn::derivative(), cubicEqn::derivative(), dmat_uniform(), pairPotentialList::dr(), quadraticEqn::error(), cubicEqn::error(), pairPotentialList::force(), Foam::getSTLpoint(), Foam::HasherDual(), Foam::HasherInt(), if(), exprResultStored::initialValueExpression(), Foam::interpolate(), discreteSurface::interpolate(), Foam::isTriCut(), Smagorinsky< BasicTurbulenceModel >::k(), reader::options::keepPorous(), reader::options::keepSolid(), reader::options::mergeInterfaces(), reader::options::mergeTol(), Foam::minimaxs(), Moment< Type >::Moment(), ensightCase::options::nodeValues(), Foam::operator!=(), Foam::operator&(), swakModuloOp::operator()(), seriesLess::operator()(), plusEqOp< Key, Hash >::operator()(), SortableListEFA< Type >::more::operator()(), SortableListDRGEP< Type >::less::operator()(), globalIndexAndTransform::less::operator()(), natural_sort::reverse::operator()(), boolAndOp< T >::operator()(), boolOrOp< T >::operator()(), less< T >::operator()(), minFirstOp< T1 >::operator()(), compareOp< T >::operator()(), Foam::operator*(), Foam::operator<(), Foam::operator<<(), Foam::operator==(), Foam::operator>(), Foam::operator>>(), Foam::pow(), pairPotentialList::rCut(), pairPotentialList::rCutSqr(), reader::options::removeBaffles(), reader::options::renameInterfaces(), Foam::reverse(), SortList< T >::reverseSort(), Foam::RGB_to_HSV(), linearEqn::roots(), ensightCase::options::separateCloud(), SortList< T >::sort(), Foam::sqrtSumSqr(), topoBoolSet::subset(), Foam::Swap(), swapec(), tetPoints::tetPoints(), Foam::transform(), triFace::triFace(), triPoints::triPoints(), regIOobject::upToDate(), reader::options::useNumberedNames(), and vbedg().
Info<< "Reading strained laminar flame speed field Su\n" << endl;volScalarField Su(IOobject ("Su", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);dimensionedScalar SuMin = 0.01*Su.average();dimensionedScalar SuMax = 4*Su.average();Info<< "Calculating turbulent flame speed field St\n" << endl;volScalarField St(IOobject ("St", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), Xi*Su);multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 116 of file createFields.H.