OpenFOAM: src/finiteVolume/fields/fvPatchFields/derived/turbulentDigitalFilterInlet/turbulentDigitalFilterInletFvPatchVectorField.C File Reference
turbulentDigitalFilterInletFvPatchVectorField.C File Reference
Namespaces
Foam
Namespace for OpenFOAM.
Functions
invDelta_ ()
indexPairs_ (patchIndexPairs())
R_ (interpolateOrRead< symmTensor >("R", dict, interpolateR_))
LundWuSquires_ (computeLundWuSquires())
UMean_ (interpolateOrRead< vector >("UMean", dict, interpolateUMean_))
Lbak_ (dict.getCheck< tensor >("L", [&](const tensor &l){return tiny_< cmptMin(l)?true:false;}))
L_ (convertScalesToGridUnits(Lbak_))
const1FSM_ ((variant_==variantType::FORWARD_STEPWISE)?dict.getOrDefault< scalar >("const1FSM",-0.25 *constant::mathematical::pi):Zero)
const2FSM_ ((variant_==variantType::FORWARD_STEPWISE)?dict.getOrDefault< scalar >("const2FSM",-0.5 *constant::mathematical::pi):Zero)
constList1FSM_ ((variant_==variantType::FORWARD_STEPWISE)?computeConstList1FSM():List< scalar >())
constList2FSM_ ((variant_==variantType::FORWARD_STEPWISE)?computeConstList2FSM():List< scalar >())
lenRandomBox_ (initLenRandomBox())
randomBoxFactors2D_ (initBoxFactors2D())
randomBoxFactors3D_ (initBoxFactors3D())
iNextToLastPlane_ (initBoxPlaneFactors())
randomBox_ ((isContinuous_ &&Pstream::master())?dict.getOrDefault< List< List< scalar >>>("randomBox", fillRandomBox()):)
filterCoeffs_ (computeFilterCoeffs())
filteredRandomBox_ (pTraits< vector >::nComponents, List< scalar >(planeDivisions_.first()*planeDivisions_.second(), Zero))
U0_ ((variant_==variantType::FORWARD_STEPWISE)?generateRandomSet< vectorField, vector >(patch().size()):vectorField())
computeVariant ((variant_==variantType::FORWARD_STEPWISE)?&turbulentDigitalFilterInletFvPatchVectorField::computeReducedDFM:&turbulentDigitalFilterInletFvPatchVectorField::computeDFM)
makePatchTypeField (fvPatchVectorField, turbulentDigitalFilterInletFvPatchVectorField)
Detailed Description
Original source file turbulentDigitalFilterInletFvPatchVectorField.C
Definition in file turbulentDigitalFilterInletFvPatchVectorField.C.
Function Documentation
invDelta_ ()
indexPairs_ (patchIndexPairs())
R_ (interpolateOrRead< symmTensor > "R", dict, interpolateR_)
Referenced by vectorTensorTransform::hasR(), ReynoldsStress< BasicTurbulenceModel >::k(), vectorTensorTransform::operator&=(), QRMatrix< MatrixType >::orderP(), and perfectFluid< Specie >::rho().
LundWuSquires_ (computeLundWuSquires())
UMean_ (interpolateOrRead< vector > "UMean", dict, interpolateUMean_)
Lbak_ (dict.getCheck< tensor > "L",[&](const tensor &l){return tiny_< cmptMin(l)?true:false;})
L_ (convertScalesToGridUnits(Lbak_))
Referenced by alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField::alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField().
const1FSM_ ((variant_==variantType::FORWARD_STEPWISE)?dict.getOrDefault< scalar >("const1FSM",-0.25 *constant::mathematical::pi):Zero)
const2FSM_ ((variant_==variantType::FORWARD_STEPWISE)?dict.getOrDefault< scalar >("const2FSM",-0.5 *constant::mathematical::pi):Zero)
constList1FSM_ ((variant_==variantType::FORWARD_STEPWISE)?computeConstList1FSM():List< scalar >())
constList2FSM_ ((variant_==variantType::FORWARD_STEPWISE)?computeConstList2FSM():List< scalar >())
lenRandomBox_ (initLenRandomBox())
randomBoxFactors2D_ (initBoxFactors2D())
randomBoxFactors3D_ (initBoxFactors3D())
iNextToLastPlane_ (initBoxPlaneFactors())
randomBox_ ((isContinuous_ &&Pstream::master())?dict.getOrDefault< List< List< scalar >>>("randomBox", fillRandomBox()):)
filterCoeffs_ (computeFilterCoeffs())
filteredRandomBox_ (pTraits< vector >::nComponents , List< scalar > planeDivisions_.first()*planeDivisions_.second(), Zero)
U0_ ((variant_==variantType::FORWARD_STEPWISE)?generateRandomSet< vectorField, vector >(patch().size()):vectorField())
computeVariant ((variant_==variantType::FORWARD_STEPWISE)?&turbulentDigitalFilterInletFvPatchVectorField::computeReducedDFM:&turbulentDigitalFilterInletFvPatchVectorField::computeDFM)
Definition at line 1041 of file turbulentDigitalFilterInletFvPatchVectorField.C.
References Foam::Info, Foam::nl, and WarningInFunction.