OpenFOAM: applications/utilities/postProcessing/lagrangian/particleTracks/createFields.H File Reference
createFields.H File Reference
Functions
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
const word cloudName (propsDict.get< word >("cloud"))
const label sampleFrequency (propsDict.get< label >("sampleFrequency"))
const label maxPositions (propsDict.get< label >("maxPositions"))
const word setFormat (propsDict.lookupOrDefault< word >("setFormat","vtk"))
Function Documentation
IOdictionary propsDict (IOobject("particleTrackProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED))
const word cloudName (propsDict.get< word > "cloud")
Referenced by if(), Foam::MapLagrangianFields(), and lagrangianReconstructor::reconstructField().
const label sampleFrequency (propsDict.get< label > "sampleFrequency")
const label maxPositions (propsDict.get< label > "maxPositions")
const word setFormat (propsDict.lookupOrDefault< word > "setFormat","vtk")