var searchData=
[
  ['kahipdecomp',['kahipDecomp',['../classFoam_1_1kahipDecomp.html',1,'Foam']]],
  ['kepsilon',['kEpsilon',['../classFoam_1_1RASModels_1_1kEpsilon.html',1,'Foam::RASModels']]],
  ['kepsilon',['kEpsilon',['../classFoam_1_1incompressible_1_1RASVariables_1_1kEpsilon.html',1,'Foam::incompressible::RASVariables']]],
  ['kepsilon_3c_20eddydiffusivity_3c_20compressible_3a_3aturbulencemodel_20_3e_20_3e',['kEpsilon&lt; EddyDiffusivity&lt; compressible::turbulenceModel &gt; &gt;',['../classFoam_1_1RASModels_1_1kEpsilon.html',1,'Foam::RASModels']]],
  ['kepsilonlopesdacosta',['kEpsilonLopesdaCosta',['../classFoam_1_1RASModels_1_1kEpsilonLopesdaCosta.html',1,'Foam::RASModels']]],
  ['kepsilonphitf',['kEpsilonPhitF',['../classFoam_1_1RASModels_1_1kEpsilonPhitF.html',1,'Foam::RASModels']]],
  ['kepsilonphitfbase',['kEpsilonPhitFBase',['../classFoam_1_1RASModels_1_1kEpsilonPhitFBase.html',1,'Foam::RASModels']]],
  ['keqn',['kEqn',['../classFoam_1_1LESModels_1_1kEqn.html',1,'Foam::LESModels']]],
  ['key_5fiterator_5fbase',['key_iterator_base',['../classFoam_1_1HashTable_1_1key__iterator__base.html',1,'Foam::HashTable']]],
  ['keyed',['Keyed',['../classFoam_1_1Keyed.html',1,'Foam']]],
  ['keytype',['keyType',['../classFoam_1_1keyType.html',1,'Foam']]],
  ['kinematiccloud',['kinematicCloud',['../classFoam_1_1kinematicCloud.html',1,'kinematicCloud'],['../classFoam_1_1KinematicCloud.html',1,'KinematicCloud&lt; CloudType &gt;']]],
  ['kinematiccloud_3c_20cloud_3c_20basickinematiccollidingparcel_20_3e_20_3e',['KinematicCloud&lt; Cloud&lt; basicKinematicCollidingParcel &gt; &gt;',['../classFoam_1_1KinematicCloud.html',1,'Foam']]],
  ['kinematiccloud_3c_20foam_3a_3adsmccloud_20_3e',['KinematicCloud&lt; Foam::DSMCCloud &gt;',['../classFoam_1_1KinematicCloud.html',1,'Foam']]],
  ['kinematiclookuptableinjection',['KinematicLookupTableInjection',['../classFoam_1_1KinematicLookupTableInjection.html',1,'Foam']]],
  ['kinematicparcel',['KinematicParcel',['../classFoam_1_1KinematicParcel.html',1,'Foam']]],
  ['kinematicparcelinjectiondata',['kinematicParcelInjectionData',['../classFoam_1_1kinematicParcelInjectionData.html',1,'Foam']]],
  ['kinematicparcelinjectiondataiolist',['kinematicParcelInjectionDataIOList',['../classFoam_1_1kinematicParcelInjectionDataIOList.html',1,'Foam']]],
  ['kinematicsinglelayer',['kinematicSingleLayer',['../classFoam_1_1regionModels_1_1surfaceFilmModels_1_1kinematicSingleLayer.html',1,'Foam::regionModels::surfaceFilmModels']]],
  ['kineticgasevaporation',['kineticGasEvaporation',['../classFoam_1_1meltingEvaporationModels_1_1kineticGasEvaporation.html',1,'Foam::meltingEvaporationModels']]],
  ['kinetictheorymodel',['kineticTheoryModel',['../classFoam_1_1kineticTheoryModel.html',1,'Foam']]],
  ['kinetictheorymodel',['kineticTheoryModel',['../classFoam_1_1RASModels_1_1kineticTheoryModel.html',1,'Foam::RASModels']]],
  ['kklomega',['kkLOmega',['../classFoam_1_1incompressible_1_1RASModels_1_1kkLOmega.html',1,'Foam::incompressible::RASModels']]],
  ['klowrewallfunctionfvpatchscalarfield',['kLowReWallFunctionFvPatchScalarField',['../classFoam_1_1kLowReWallFunctionFvPatchScalarField.html',1,'Foam']]],
  ['kmesh',['Kmesh',['../classFoam_1_1Kmesh.html',1,'Foam']]],
  ['kocamustafaogullariishii',['KocamustafaogullariIshii',['../classFoam_1_1wallBoilingModels_1_1departureDiameterModels_1_1KocamustafaogullariIshii.html',1,'Foam::wallBoilingModels::departureDiameterModels']]],
  ['komega',['kOmega',['../classFoam_1_1RASModels_1_1kOmega.html',1,'Foam::RASModels']]],
  ['komegasst',['kOmegaSST',['../classFoam_1_1RASModels_1_1kOmegaSST.html',1,'Foam::RASModels']]],
  ['komegasst',['kOmegaSST',['../classFoam_1_1incompressible_1_1RASVariables_1_1kOmegaSST.html',1,'Foam::incompressible::RASVariables']]],
  ['komegasstbase',['kOmegaSSTBase',['../classFoam_1_1kOmegaSSTBase.html',1,'Foam']]],
  ['komegasstbase_3c_20desmodel_3c_20basicturbulencemodel_20_3e_20_3e',['kOmegaSSTBase&lt; DESModel&lt; BasicTurbulenceModel &gt; &gt;',['../classFoam_1_1kOmegaSSTBase.html',1,'Foam']]],
  ['komegasstbase_3c_20eddyviscosity_3c_20rasmodel_3c_20basicturbulencemodel_20_3e_20_3e_20_3e',['kOmegaSSTBase&lt; eddyViscosity&lt; RASModel&lt; BasicTurbulenceModel &gt; &gt; &gt;',['../classFoam_1_1kOmegaSSTBase.html',1,'Foam']]],
  ['komegasstddes',['kOmegaSSTDDES',['../classFoam_1_1LESModels_1_1kOmegaSSTDDES.html',1,'Foam::LESModels']]],
  ['komegasstdes',['kOmegaSSTDES',['../classFoam_1_1LESModels_1_1kOmegaSSTDES.html',1,'Foam::LESModels']]],
  ['komegasstiddes',['kOmegaSSTIDDES',['../classFoam_1_1LESModels_1_1kOmegaSSTIDDES.html',1,'Foam::LESModels']]],
  ['komegasstlm',['kOmegaSSTLM',['../classFoam_1_1RASModels_1_1kOmegaSSTLM.html',1,'Foam::RASModels']]],
  ['komegasstsas',['kOmegaSSTSAS',['../classFoam_1_1RASModels_1_1kOmegaSSTSAS.html',1,'Foam::RASModels']]],
  ['komegasstsato',['kOmegaSSTSato',['../classFoam_1_1RASModels_1_1kOmegaSSTSato.html',1,'Foam::RASModels']]],
  ['kqrwallfunctionfvpatchfield',['kqRWallFunctionFvPatchField',['../classFoam_1_1kqRWallFunctionFvPatchField.html',1,'Foam']]],
  ['kts',['KTS',['../classFoam_1_1XiGModels_1_1KTS.html',1,'Foam::XiGModels']]],
  ['kunz',['Kunz',['../classFoam_1_1phaseChangeTwoPhaseMixtures_1_1Kunz.html',1,'Foam::phaseChangeTwoPhaseMixtures']]]
];
