OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/CourantNo.H File Reference
CourantNo.H File Reference
Calculates and outputs the mean and maximum Courant Numbers.
Functions
forAll (phases, phasei)
Variables
scalar CoNum = 0.0
scalar meanCoNum = 0.0
Detailed Description
Calculates and outputs the mean and maximum Courant Numbers.
Original source file CourantNo.H
Definition in file CourantNo.H.
Function Documentation
forAll (phases , phasei)
Initial value:
{
        const surfaceScalarField ghSnGradRho
        (
            "ghSnGradRho",
            ghf*fvc::snGrad(rho)*mesh.magSf()
        )
Definition at line 35 of file CourantNo.H.
References CoNum, forAll, Foam::gMax(), Foam::gSum(), Foam::mag(), Foam::max(), meanCoNum, mesh, phasei, phases, phi, runTime, sumPhi(), and Foam::fvc::surfaceSum().
Variable Documentation
CoNum = 0.0
Definition at line 25 of file CourantNo.H.
meanCoNum = 0.0
Definition at line 26 of file CourantNo.H.