OpenFOAM: src/lagrangian/molecularDynamics/molecule/mdTools/averageMDFields.H File Reference
averageMDFields.H File Reference
Functions
forAll (allSpeciesRhoN, rN)
totalRhoN primitiveFieldRef ()
scalarField totalRhoM_sum (mesh.nCells(), Zero)
forAll (allSpeciesRhoM, rM)
vectorField totalMomentum_sum (mesh.nCells(), Zero)
scalarField totalMass_sum (mesh.nCells(), Zero)
forAll (allSpeciesVelocity, v)
forAll (itotalVelocity, tV)
scalarField totalTemperatureVTerms_sum (mesh.nCells(), Zero)
scalarField totalN_sum (mesh.nCells(), Zero)
forAll (allSpeciesTemperature, t)
forAll (itotalTemperature, tT)
scalarField totalKE_sum (mesh.nCells(), Zero)
forAll (allSpeciesMeanKE, mKE)
forAll (itotalMeanKE, tMKE)
Variables
volVectorField::Internal & itotalVelocity = totalVelocity
volScalarField::Internal & itotalTemperature
volScalarField::Internal & itotalMeanKE = totalMeanKE
Function Documentation
forAll (allSpeciesRhoN , rN)
Definition at line 9 of file averageMDFields.H.
References allSpeciesN_RU(), allSpeciesRhoN(), and mesh.
totalRhoN primitiveFieldRef ()
scalarField totalRhoM_sum (mesh. nCells(), Zero)
Referenced by forAll().
forAll (allSpeciesRhoM , rM)
Definition at line 28 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesRhoM(), mesh, and totalRhoM_sum().
vectorField totalMomentum_sum (mesh. nCells(), Zero)
Referenced by forAll().
scalarField totalMass_sum (mesh. nCells(), Zero)
Referenced by forAll().
forAll (allSpeciesVelocity , v)
Definition at line 48 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesN_RU(), allSpeciesVelocity(), allSpeciesVelocitySum_RU, forAll, totalMass_sum(), totalMomentum_sum(), and Foam::Zero.
forAll (itotalVelocity , tV)
Definition at line 81 of file averageMDFields.H.
References totalMass_sum(), totalMomentum_sum(), and Foam::Zero.
scalarField totalTemperatureVTerms_sum (mesh. nCells(), Zero)
Referenced by forAll().
scalarField totalN_sum (mesh. nCells(), Zero)
Referenced by forAll().
forAll (allSpeciesTemperature , t)
Definition at line 101 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesN_RU(), allSpeciesTemperature(), allSpeciesVelocityMagSquaredSum_RU, allSpeciesVelocitySum_RU, forAll, kb, totalN_sum(), and totalTemperatureVTerms_sum().
forAll (itotalTemperature , tT)
Definition at line 155 of file averageMDFields.H.
References kb, totalN_sum(), and totalTemperatureVTerms_sum().
scalarField totalKE_sum (mesh. nCells(), Zero)
Referenced by forAll().
forAll (allSpeciesMeanKE , mKE)
Definition at line 175 of file averageMDFields.H.
References allSpeciesM_RU, allSpeciesMeanKE(), allSpeciesN_RU(), allSpeciesVelocityMagSquaredSum_RU, forAll, and totalKE_sum().
forAll (itotalMeanKE , tMKE)
Definition at line 213 of file averageMDFields.H.
References totalKE_sum(), and totalN_sum().
Variable Documentation
volVectorField::Internal& itotalVelocity = totalVelocity
Definition at line 79 of file averageMDFields.H.
volScalarField::Internal& itotalTemperature
Initial value:
=
        totalTemperature
Definition at line 152 of file averageMDFields.H.
volScalarField::Internal& itotalMeanKE = totalMeanKE
Definition at line 211 of file averageMDFields.H.