OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionTwoPhaseEulerFoam/fluid/createFluidFields.H File Reference
createFluidFields.H File Reference
Functions
PtrList< twoPhaseSystem > phaseSystemFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList
< uniformDimensionedScalarField > hRefFluid (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList
< multivariateSurfaceInterpolationScheme
< scalar >::fieldTable > fieldsFluid (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< bool > frozenFlowFluid (fluidRegions.size(), false)
List< label > pRefCellFluid (fluidRegions.size())
List< scalar > pRefValueFluid (fluidRegions.size())
PtrList< dimensionedScalar > pMinFluid (fluidRegions.size())
PtrList< pimpleControl > pimpleFluid (fluidRegions.size())
forAll (fluidRegions, i)
Variables
const
uniformDimensionedVectorField & g = meshObjects::gravity::New(runTime)
Function Documentation
PtrList<twoPhaseSystem> phaseSystemFluid (fluidRegions. size())
Referenced by forAll().
PtrList<volScalarField> ghFluid (fluidRegions. size())
PtrList<surfaceScalarField> ghfFluid (fluidRegions. size())
PtrList<uniformDimensionedScalarField> hRefFluid (fluidRegions. size())
PtrList<volScalarField> p_rghFluid (fluidRegions. size())
PtrList<multivariateSurfaceInterpolationScheme<scalar>::fieldTable> fieldsFluid (fluidRegions. size())
Referenced by forAll().
List<scalar> initialMassFluid (fluidRegions. size())
List<bool> frozenFlowFluid (fluidRegions. size(), false)
List<label> pRefCellFluid (fluidRegions. size())
List<scalar> pRefValueFluid (fluidRegions. size())
PtrList<dimensionedScalar> pMinFluid (fluidRegions. size())
Referenced by forAll().
PtrList<pimpleControl> pimpleFluid (fluidRegions. size())
Referenced by forAll().
forAll (fluidRegions , i)
Definition at line 196 of file createFluidFields.H.
References C, Foam::cmptMag(), Foam::dimLength, Foam::dimPressure, Foam::fvc::domainIntegrate(), Foam::endl(), fluidRegions(), frozenFlowFluid(), ghfFluid(), ghFluid(), hRefFluid(), i, Foam::Info, initialMassFluid(), Foam::mag(), Foam::name(), Foam::New(), Foam::nl, p, p_rghFluid(), phase1, phaseSystemFluid(), pimpleDict, pimpleFluid(), pMinFluid(), pRefCellFluid(), pRefValueFluid(), rho, runTime, Foam::setRefCell(), and Foam::Zero.
Variable Documentation
const uniformDimensionedVectorField& g = meshObjects::gravity::New(runTime)
Definition at line 20 of file createFluidFields.H.