OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionSimpleFoam/fluid/createFluidFields.H File Reference
createFluidFields.H File Reference
Functions
PtrList< rhoThermo > thermoFluid (fluidRegions.size())
PtrList< volScalarField > rhoFluid (fluidRegions.size())
PtrList< volVectorField > UFluid (fluidRegions.size())
PtrList< surfaceScalarField > phiFluid (fluidRegions.size())
PtrList
< uniformDimensionedScalarField > hRefFluid (fluidRegions.size())
PtrList< volScalarField > ghFluid (fluidRegions.size())
PtrList< surfaceScalarField > ghfFluid (fluidRegions.size())
PtrList
< compressible::turbulenceModel > turbulence (fluidRegions.size())
PtrList< volScalarField > p_rghFluid (fluidRegions.size())
PtrList
< radiation::radiationModel > radiation (fluidRegions.size())
List< scalar > initialMassFluid (fluidRegions.size())
List< label > pRefCellFluid (fluidRegions.size(),-1)
List< scalar > pRefValueFluid (fluidRegions.size(), Zero)
List< bool > frozenFlowFluid (fluidRegions.size(), false)
PtrList< dimensionedScalar > rhoMax (fluidRegions.size())
PtrList< dimensionedScalar > rhoMin (fluidRegions.size())
PtrList< IOMRFZoneList > MRFfluid (fluidRegions.size())
PtrList< fv::options > fluidFvOptions (fluidRegions.size())
forAll (fluidRegions, i)
Variables
const
uniformDimensionedVectorField & g = meshObjects::gravity::New(runTime)
Function Documentation
PtrList<rhoThermo> thermoFluid (fluidRegions. size())
Referenced by forAll().
PtrList<volScalarField> rhoFluid (fluidRegions. size())
Referenced by forAll().
PtrList<volVectorField> UFluid (fluidRegions. size())
Referenced by forAll().
PtrList<surfaceScalarField> phiFluid (fluidRegions. size())
Referenced by forAll().
PtrList<uniformDimensionedScalarField> hRefFluid (fluidRegions. size())
Referenced by forAll().
PtrList<volScalarField> ghFluid (fluidRegions. size())
Referenced by forAll().
PtrList<surfaceScalarField> ghfFluid (fluidRegions. size())
Referenced by forAll().
PtrList<compressible::turbulenceModel> turbulence (fluidRegions. size())
PtrList<volScalarField> p_rghFluid (fluidRegions. size())
Referenced by forAll().
PtrList<radiation::radiationModel> radiation (fluidRegions. size())
List<scalar> initialMassFluid (fluidRegions. size())
Referenced by forAll().
List<label> pRefCellFluid (fluidRegions. size(), - 1)
Referenced by forAll().
List<scalar> pRefValueFluid (fluidRegions. size(), Zero)
Referenced by forAll().
List<bool> frozenFlowFluid (fluidRegions. size(), false)
Referenced by forAll().
PtrList<dimensionedScalar> rhoMax (fluidRegions. size())
PtrList<dimensionedScalar> rhoMin (fluidRegions. size())
PtrList<IOMRFZoneList> MRFfluid (fluidRegions. size())
Referenced by forAll().
PtrList<fv::options> fluidFvOptions (fluidRegions. size())
Referenced by forAll().
forAll (fluidRegions , i)
Definition at line 27 of file createFluidFields.H.
References C, Foam::cmptMag(), Foam::dimDensity, Foam::dimLength, Foam::fvc::domainIntegrate(), Foam::endl(), fluidFvOptions(), fluidRegions(), frozenFlowFluid(), ghfFluid(), ghFluid(), hRefFluid(), i, Foam::Info, initialMassFluid(), Foam::linearInterpolate(), Foam::mag(), MRFfluid(), Foam::name(), Foam::New(), Foam::nl, p, p_rghFluid(), phiFluid(), pRefCellFluid(), pRefValueFluid(), radiation(), rho, rhoFluid(), rhoMax, rhoMin, runTime, Foam::setRefCell(), T, thermoFluid(), turbulence, UFluid(), and Foam::Zero.
Variable Documentation
const uniformDimensionedVectorField& g = meshObjects::gravity::New(runTime)
Definition at line 24 of file createFluidFields.H.
Referenced by cellMDLimitedGrad< Type >::calcGrad(), faceLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), KocamustafaogullariIshii::dDeparture(), adjointSpalartAllmaras::DnuTildaEff(), Foam::Elliptic::ellipticIntegralsKE(), Cole::fDeparture(), for(), surfaceFilmModel::New(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), Foam::RGB_to_HSV(), SVD::SVD(), and triangulation_plot_eps().