OpenFOAM: clockValue Class Reference
clockValue Class Reference
Access to high-resolution clock value with some basic operations.
Public Member Functions
clockValue ()
Construct zero initialized.
clockValue (const value_type &value)
Construct from duration with the same clock base.
clockValue (bool useNow)
Construct zero initialized or with current time.
const value_type & value () const
Return the value.
void clear ()
Reset to zero.
void update ()
Update to the current now() time from the system.
clockValue elapsed () const
The time elapsed from now() since the start time.
long seconds () const
The value in seconds (rounded)
std::string str () const
Format as day-hh:mm:ss string.
operator double () const
Conversion operator to seconds in floating point.
clockValue & operator-= (const clockValue &rhs)
Subtract time value.
clockValue & operator+= (const clockValue &rhs)
Add time value.
Static Public Member Functions
static clockValue now ()
Return the current time value from the system.
Detailed Description
Access to high-resolution clock value with some basic operations.
Source files
clockValue.H
clockValue.C
Definition at line 47 of file clockValue.H.
Constructor & Destructor Documentation
clockValue ()
Construct zero initialized.
Definition at line 29 of file clockValue.C.
clockValue (const value_type & value) explicit
Construct from duration with the same clock base.
Definition at line 35 of file clockValue.C.
clockValue (bool useNow) explicit
Construct zero initialized or with current time.
Definition at line 41 of file clockValue.C.
Member Function Documentation
static clockValue now () inline static
Return the current time value from the system.
Definition at line 84 of file clockValue.H.
Referenced by profiling::endTimer().
const value_type& value () const inline
Return the value.
Definition at line 95 of file clockValue.H.
Referenced by Foam::operator+().
void clear ()
Reset to zero.
Definition at line 54 of file clockValue.C.
void update ()
Update to the current now() time from the system.
Definition at line 60 of file clockValue.C.
Foam::clockValue elapsed () const
The time elapsed from now() since the start time.
Definition at line 66 of file clockValue.C.
Referenced by regionSplit::reduceRegions().
long seconds () const
The value in seconds (rounded)
Definition at line 72 of file clockValue.C.
std::string str () const
Format as day-hh:mm:ss string.
Definition at line 78 of file clockValue.C.
References Foam::BitOps::count().
operator double () const
Conversion operator to seconds in floating point.
Definition at line 126 of file clockValue.C.
Foam::clockValue & operator-= (const clockValue & rhs)
Subtract time value.
Definition at line 136 of file clockValue.C.
Foam::clockValue & operator+= (const clockValue & rhs)
Add time value.
Definition at line 143 of file clockValue.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/global/clockValue/clockValue.H
src/OpenFOAM/global/clockValue/clockValue.C