OpenFOAM: CStringList Class Reference
CStringList Class Reference
An adapter for copying a list of C++ strings into a list of C-style strings for passing to C code that expects argc/argv parameters.
Public Member Functions
CStringList ()
Construct empty, adding content later (via reset).
template<class StringType >
CStringList (const UList< StringType > &input)
Copy construct from a list of strings.
template<class StringType >
CStringList (const SubStrings< StringType > &input)
Copy construct from a list of sub-string references.
~CStringList ()
Destructor. Invokes clear() to free memory.
bool empty () const noexcept
True if the size is zero.
int size () const noexcept
Return the number of C-strings (ie, argc)
char ** strings () const
Return the list of C-strings (ie, argv)
char ** strings (int start) const
Return the sublist of C-strings (ie, argv) starting at the specified offset.
size_t length () const
Overall length of the flattened character (data) content.
const char * data () const
The flattened character content, with interspersed nul-chars.
void clear ()
Clear contents and free memory.
template<class StringType >
int reset (const UList< StringType > &input)
Copy the input list of strings.
template<class StringType >
int reset (const SubStrings< StringType > &input)
Copy the input list of strings.
const char * operator[] (int i) const
Return element at the given index. No bounds checking.
template<class StringType >
Foam::List< StringType > asList (int argc, const char *const argv[])
template<class StringType >
Foam::List< StringType > asList (const char *const argv[])
Static Public Member Functions
static int count (const char *const argv[])
Count the number of parameters until the first nullptr.
template<class StringType >
static List< StringType > asList (int argc, const char *const argv[])
Create a list from argc/argv parameters.
template<class StringType >
static List< StringType > asList (const char *const argv[])
Create a list from a nullptr-terminated list of argv parameters.
Detailed Description
An adapter for copying a list of C++ strings into a list of C-style strings for passing to C code that expects argc/argv parameters.
In addition to providing a C-compatible list of C-strings, the string lists are flattened into a single string of data that can be also be passed en mass.
Example use:
wordList myStrings;  ...
CStringList cstr(myStrings);
// pass as argc, argv:
someMain(cstr.size(), cstr.strings());
// access the raw characters:
os.write(cstr.data(), cstr.length());
Definition at line 63 of file CStringList.H.
Constructor & Destructor Documentation
CStringList () inline
Construct empty, adding content later (via reset).
Definition at line 54 of file CStringListI.H.
CStringList (const UList< StringType > & input) inline explicit
Copy construct from a list of strings.
Copies the input characters.
Definition at line 64 of file CStringListI.H.
CStringList (const SubStrings< StringType > & input) inline explicit
Copy construct from a list of sub-string references.
Copies the input characters.
Definition at line 73 of file CStringListI.H.
References reset().
~CStringList () inline
Destructor. Invokes clear() to free memory.
Definition at line 83 of file CStringListI.H.
References reset().
Member Function Documentation
int count (const char *const argv[]) inline static
Count the number of parameters until the first nullptr.
Return 0 if argv is nullptr.
Definition at line 38 of file CStringListI.H.
bool empty () const inline noexcept
True if the size is zero.
Definition at line 109 of file CStringListI.H.
int size () const inline noexcept
Return the number of C-strings (ie, argc)
Definition at line 115 of file CStringListI.H.
Referenced by Foam::operator<<().
char ** strings () const inline
Return the list of C-strings (ie, argv)
The position at argc is a nullptr
Definition at line 127 of file CStringListI.H.
char ** strings (int start) const inline
Return the sublist of C-strings (ie, argv) starting at the specified offset.
Parameters
start the offset, must be less than argc
Definition at line 133 of file CStringListI.H.
size_t length () const inline
Overall length of the flattened character (data) content.
Definition at line 121 of file CStringListI.H.
const char * data () const inline
The flattened character content, with interspersed nul-chars.
Definition at line 139 of file CStringListI.H.
References Foam::start.
void clear () inline
Clear contents and free memory.
Definition at line 91 of file CStringListI.H.
References clear().
int reset (const UList< StringType > & input) inline
Copy the input list of strings.
Returns
number of arguments (argc)
Definition at line 146 of file CStringListI.H.
int reset (const SubStrings< StringType > & input) inline
Copy the input list of strings.
Returns
number of arguments (argc)
Definition at line 153 of file CStringListI.H.
static List<StringType> asList (int argc, const char *const argv[]) static
Create a list from argc/argv parameters.
A null pointer for argv is permissible when argc is zero.
static List<StringType> asList (const char *const argv[]) inline static
Create a list from a nullptr-terminated list of argv parameters.
Using a nullptr for argv is permissible.
const char * operator[] (int i) const inline
Return element at the given index. No bounds checking.
Definition at line 161 of file CStringListI.H.
Foam::List<StringType> asList (int argc, const char *const argv[])
Definition at line 69 of file CStringListTemplates.C.
Foam::List<StringType> asList (const char *const argv[])
Definition at line 84 of file CStringListTemplates.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/lists/CStringList.H
src/OpenFOAM/primitives/strings/lists/CStringListI.H
src/OpenFOAM/primitives/strings/lists/CStringListTemplates.C