OpenFOAM: labelRange Class Reference
labelRange Class Reference
A range or interval of labels defined by a start and a size.
Classes
class const_iterator
Forward iterator with const access.
Public Types
typedef label value_type
Type of values the range contains.
typedef label size_type
The type that can represent the size of the range.
Public Member Functions
constexpr labelRange () noexcept
An empty range with zero for start/size.
labelRange (const label start, const label size) noexcept
Construct a range from start/size, enforcing non-negative size.
labelRange (const label start, const label size, const bool adjustStart) noexcept
Construct a range from start/size, enforcing non-negative size.
labelRange (const MinMax< label > &range) noexcept
Construct from a min/max range, enforcing non-negative size. Does not adjust the start.
labelRange (Istream &is)
Construct from Istream.
void setStart (const label i) noexcept
Change the start position.
void resize (const label n) noexcept
Change the size, enforcing non-negative size.
void setSize (const label n) noexcept
Change the size - alias for resize()
void clear () noexcept
Reset to zero start and zero size.
bool empty () const noexcept
Is the range empty?
bool valid () const noexcept
Is the range non-empty?
label start () const noexcept
The (inclusive) lower value of the range.
label size () const noexcept
The effective size of the range.
label before () const noexcept
The value before the start of the range.
label first () const noexcept
The (inclusive) lower value of the range - same as start()
label min () const noexcept
The (inclusive) lower value of the range - same as start(), first()
label last () const noexcept
The (inclusive) upper value of the range - same as max()
label max () const noexcept
The (inclusive) upper value of the range - same as last()
label after () const noexcept
The value after the last element in the range.
void adjust () noexcept
Adjust the start to avoid negative indices.
bool reset (const label start, const label size) noexcept
Reset start and size, enforcing non-negative size.
bool reset (const label start, const label size, const bool adjustStart) noexcept
Reset start and size, enforcing non-negative size.
bool found (const label value) const noexcept
Return true if the (global) value is located within the range.
List< label > labels () const
Return the range as a list of labels.
bool overlaps (const labelRange &range, bool touches=false) const
Return true if the ranges overlap.
labelRange join (const labelRange &range) const
Return a joined range, squashing any gaps in between.
labelRange subset (const labelRange &range) const
Calculate the intersection of the range with another.
labelRange subset (const label start, const label size) const
Calculate the intersection with the given start/size range.
labelRange subset0 (const label size) const
Calculate the intersection with the given 0/size range.
label operator[] (const label i) const noexcept
Return element in the range, without bounds checking.
bool operator() (const label value) const noexcept
Return true if the global value is located within the range.
label operator++ () noexcept
Increase the size by 1.
label operator++ (int) noexcept
label operator+= (const label n) noexcept
Increase the size by n.
label operator-- () noexcept
Decrease the size by 1, but never below 0.
label operator-- (int) noexcept
label operator-= (const label n) noexcept
Decrease the size by n, but never below 0.
const_iterator begin () const
A const_iterator set to the beginning of the range.
const_iterator cbegin () const
A const_iterator set to the beginning of the range.
const const_iterator cend () const
A const_iterator set to 1 beyond the end of the range.
const const_iterator end () const
A const_iterator set to 1 beyond the end of the range.
const_iterator at (const label i) const
Return const_iterator to a position within the range, with bounds checking.
Static Public Member Functions
static labelRange identity (const label len, const label start=0) noexcept
An identity range corresponding to (map[i] == i), or with an optional start index, so that (map[i] == i+start)
Static Public Attributes
static int debug
Debugging.
static const labelRange null
An empty range with start=0, size=0.
Detailed Description
A range or interval of labels defined by a start and a size.
Source files
labelRange.H
labelRange.C
labelRangeI.H
Definition at line 54 of file labelRange.H.
Member Typedef Documentation
typedef label value_type
Type of values the range contains.
Definition at line 76 of file labelRange.H.
typedef label size_type
The type that can represent the size of the range.
Definition at line 81 of file labelRange.H.
Constructor & Destructor Documentation
constexpr labelRange () inline noexcept
An empty range with zero for start/size.
Definition at line 24 of file labelRangeI.H.
Referenced by labelRange::setStart().
labelRange (const label start, const label size) inline noexcept
Construct a range from start/size, enforcing non-negative size.
Definition at line 32 of file labelRangeI.H.
labelRange (const label start, const label size, const bool adjustStart) inline noexcept
Construct a range from start/size, enforcing non-negative size.
Optionally adjust the start to avoid any negative indices.
Definition at line 45 of file labelRangeI.H.
labelRange (const MinMax< label > & range) explicit noexcept
Construct from a min/max range, enforcing non-negative size. Does not adjust the start.
Passing an invalid min/max range results in an empty labelRange
Definition at line 40 of file labelRange.C.
labelRange (Istream & is) explicit
Construct from Istream.
Definition at line 53 of file labelRange.C.
References range.
Member Function Documentation
Foam::labelRange identity (const label len, const label start = 0) inline static noexcept
An identity range corresponding to (map[i] == i), or with an optional start index, so that (map[i] == i+start)
The parameter order as per the Foam::identity() function.
Definition at line 172 of file labelRangeI.H.
Referenced by ensightCells::classify().
void setStart (const label i) inline noexcept
Change the start position.
Definition at line 181 of file labelRangeI.H.
References labelRange::labelRange(), and labelRange::start().
Referenced by foamPvCore::arrayRange::name().
void resize (const label n) inline noexcept
Change the size, enforcing non-negative size.
Definition at line 187 of file labelRangeI.H.
References i.
void setSize (const label n) inline noexcept
Change the size - alias for resize()
Definition at line 194 of file labelRangeI.H.
References n.
void clear () inline noexcept
Reset to zero start and zero size.
Definition at line 201 of file labelRangeI.H.
References n.
Referenced by foamPvCore::arrayRange::name().
bool empty () const inline noexcept
Is the range empty?
Definition at line 207 of file labelRangeI.H.
bool valid () const inline noexcept
Is the range non-empty?
Definition at line 213 of file labelRangeI.H.
Foam::label start () const inline noexcept
The (inclusive) lower value of the range.
Definition at line 225 of file labelRangeI.H.
Referenced by labelRange::setStart(), and UList< T >::validateRange().
Foam::label size () const inline noexcept
The effective size of the range.
Definition at line 219 of file labelRangeI.H.
Referenced by foamPvCore::arrayRange::intersects(), and UList< T >::validateRange().
Foam::label before () const inline noexcept
The value before the start of the range.
Definition at line 231 of file labelRangeI.H.
Foam::label first () const inline noexcept
The (inclusive) lower value of the range - same as start()
Definition at line 237 of file labelRangeI.H.
Foam::label min () const inline noexcept
The (inclusive) lower value of the range - same as start(), first()
Definition at line 243 of file labelRangeI.H.
Foam::label last () const inline noexcept
The (inclusive) upper value of the range - same as max()
Definition at line 249 of file labelRangeI.H.
Foam::label max () const inline noexcept
The (inclusive) upper value of the range - same as last()
Definition at line 255 of file labelRangeI.H.
Foam::label after () const inline noexcept
The value after the last element in the range.
This is identical to the value of cend()
Definition at line 261 of file labelRangeI.H.
void adjust () noexcept
Adjust the start to avoid negative indices.
The size is decreased accordingly, but will never become negative. Eg, adjusting (-10, 15) becomes (0,5). adjusting (-20, 15) becomes (0,0)
Definition at line 78 of file labelRange.C.
bool reset (const label start, const label size) inline noexcept
Reset start and size, enforcing non-negative size.
Returns
true if the updated range is valid (non-empty).
Definition at line 268 of file labelRangeI.H.
bool reset (const label start, const label size, const bool adjustStart) inline noexcept
Reset start and size, enforcing non-negative size.
Optionally adjust the start to avoid any negative indices.
Returns
true if the updated range is valid (non-empty).
Definition at line 283 of file labelRangeI.H.
bool found (const label value) const inline noexcept
Return true if the (global) value is located within the range.
Definition at line 305 of file labelRangeI.H.
Referenced by labelRange::operator++().
Foam::List< Foam::label > labels () const
Return the range as a list of labels.
Definition at line 64 of file labelRange.C.
bool overlaps (const labelRange & range, bool touches = false) const
Return true if the ranges overlap.
Optional test for ranges that also just touch each other
Definition at line 95 of file labelRange.C.
Foam::labelRange join (const labelRange & range) const
Return a joined range, squashing any gaps in between.
A prior overlaps() check can be used to avoid squashing gaps.
Definition at line 118 of file labelRange.C.
Foam::labelRange subset (const labelRange & range) const
Calculate the intersection of the range with another.
If there is no intersection, it returns an empty range with zero for start/size.
Definition at line 140 of file labelRange.C.
Foam::labelRange subset (const label start, const label size) const
Calculate the intersection with the given start/size range.
If there is no intersection, it returns an empty range with zero for start/size.
Definition at line 158 of file labelRange.C.
Foam::labelRange subset0 (const label size) const
Calculate the intersection with the given 0/size range.
If there is no intersection, it returns an empty range with zero for start/size.
Definition at line 178 of file labelRange.C.
Referenced by UList< T >::validateRange().
Foam::label operator[] (const label i) const inline noexcept
Return element in the range, without bounds checking.
Definition at line 313 of file labelRangeI.H.
References value().
bool operator() (const label value) const inline noexcept
Return true if the global value is located within the range.
Behaviour identical to found() - usable as a predicate
Definition at line 319 of file labelRangeI.H.
References i.
Foam::label operator++ () inline noexcept
Increase the size by 1.
Definition at line 325 of file labelRangeI.H.
References labelRange::found(), and value().
Foam::label operator++ (int) inline noexcept
Definition at line 331 of file labelRangeI.H.
Foam::label operator+= (const label n) inline noexcept
Increase the size by n.
Definition at line 354 of file labelRangeI.H.
Foam::label operator-- () inline noexcept
Decrease the size by 1, but never below 0.
Definition at line 337 of file labelRangeI.H.
Foam::label operator-- (int) inline noexcept
Definition at line 345 of file labelRangeI.H.
Foam::label operator-= (const label n) inline noexcept
Decrease the size by n, but never below 0.
Definition at line 361 of file labelRangeI.H.
References n.
Foam::labelRange::const_iterator begin () const inline
A const_iterator set to the beginning of the range.
The value returned is guaranteed to be the same as start()
Definition at line 138 of file labelRangeI.H.
References iter.
Foam::labelRange::const_iterator cbegin () const inline
A const_iterator set to the beginning of the range.
The value returned is guaranteed to be the same as start()
Definition at line 144 of file labelRangeI.H.
const Foam::labelRange::const_iterator cend () const inline
A const_iterator set to 1 beyond the end of the range.
The value returned is the same as after()
Definition at line 156 of file labelRangeI.H.
const Foam::labelRange::const_iterator end () const inline
A const_iterator set to 1 beyond the end of the range.
The value returned is the same as after()
Definition at line 150 of file labelRangeI.H.
Foam::labelRange::const_iterator at (const label i) const inline
Return const_iterator to a position within the range, with bounds checking.
Returns
iterator at the requested position, or end() for out of bounds
Definition at line 163 of file labelRangeI.H.
Member Data Documentation
int debug static
Debugging.
Definition at line 86 of file labelRange.H.
const Foam::labelRange null static
An empty range with start=0, size=0.
Definition at line 99 of file labelRange.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/ranges/labelRange/labelRange.H
src/OpenFOAM/primitives/ranges/labelRange/labelRange.C
src/OpenFOAM/primitives/ranges/labelRange/labelRangeI.H