OpenFOAM: solidProperties Class Reference
solidProperties Class Reference
The thermophysical properties of a solid.
Public Member Functions
TypeName ("solid")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, solidProperties, dictionary,(const dictionary &dict),(dict))
solidProperties (scalar rho, scalar Cp, scalar kappa, scalar Hf, scalar emissivity, scalar W)
Construct from components.
solidProperties (const dictionary &dict)
Construct from dictionary.
virtual autoPtr< solidProperties > clone () const
Construct and return clone.
virtual ~solidProperties ()=default
Destructor.
scalar rho () const
Density [kg/m3].
scalar Cp () const
Specific heat capacity [J/(kg.K)].
scalar kappa () const
Thermal conductivity [W/(m.K)].
scalar Hf () const
Heat of formation [J/kg].
scalar Hs (const scalar T) const
Sensible enthalpy - reference to Tstd [J/kg].
scalar emissivity () const
Emissivity [].
scalar W () const
Molar weight [Kg/Kmol].
void readIfPresent (const dictionary &dict)
Read and set the properties if present in the given dictionary.
virtual void writeData (Ostream &os) const
Write the solidProperties properties.
Static Public Member Functions
static autoPtr< solidProperties > New (const word &name)
Return a pointer to a new solidProperties created from name.
static autoPtr< solidProperties > New (const dictionary &dict)
Return a pointer to a new solidProperties created from dictionary.
Friends
Ostream & operator<< (Ostream &os, const solidProperties &s)
Ostream Operator.
Detailed Description
The thermophysical properties of a solid.
Source files
solidProperties.H
solidProperties.C
Definition at line 50 of file solidProperties.H.
Constructor & Destructor Documentation
solidProperties (scalar rho, scalar Cp, scalar kappa, scalar Hf, scalar emissivity, scalar W)
Construct from components.
Definition at line 37 of file solidProperties.C.
solidProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 55 of file solidProperties.C.
virtual ~solidProperties () virtual default
Destructor.
Member Function Documentation
TypeName ("solid")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , solidProperties , () , ())
declareRunTimeSelectionTable (autoPtr , solidProperties , dictionary , (const dictionary &dict) , (dict))
virtual autoPtr<solidProperties> clone () const inline virtual
Construct and return clone.
Reimplemented in ash, C, and CaCO3.
Definition at line 137 of file solidProperties.H.
Foam::autoPtr< Foam::solidProperties > New (const word & name) static
Return a pointer to a new solidProperties created from name.
Definition at line 28 of file solidPropertiesNew.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
Referenced by solidMixtureProperties::solidMixtureProperties().
Foam::autoPtr< Foam::solidProperties > New (const dictionary & dict) static
Return a pointer to a new solidProperties created from dictionary.
Definition at line 51 of file solidPropertiesNew.C.
Foam::scalar rho () const inline
Density [kg/m3].
Definition at line 26 of file solidPropertiesI.H.
Foam::scalar Cp () const inline
Specific heat capacity [J/(kg.K)].
Definition at line 32 of file solidPropertiesI.H.
Foam::scalar kappa () const inline
Thermal conductivity [W/(m.K)].
Definition at line 38 of file solidPropertiesI.H.
Foam::scalar Hf () const inline
Heat of formation [J/kg].
Definition at line 44 of file solidPropertiesI.H.
Foam::scalar Hs (const scalar T) const inline
Sensible enthalpy - reference to Tstd [J/kg].
Definition at line 50 of file solidPropertiesI.H.
References Hf_().
Foam::scalar emissivity () const inline
Emissivity [].
Definition at line 56 of file solidPropertiesI.H.
References Foam::constant::standard::Tstd.
Foam::scalar W () const inline
Molar weight [Kg/Kmol].
Definition at line 61 of file solidPropertiesI.H.
References emissivity_().
void readIfPresent (const dictionary & dict)
Read and set the properties if present in the given dictionary.
virtual void writeData (Ostream & os) const virtual
Write the solidProperties properties.
Reimplemented in ash, C, and CaCO3.
Referenced by Foam::operator<<().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const solidProperties & s) friend
Ostream Operator.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidProperties.H
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidProperties.C
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidPropertiesI.H
src/thermophysicalModels/thermophysicalProperties/solidProperties/solidProperties/solidPropertiesNew.C