OpenFOAM: dimensionSet Class Reference
dimensionSet Class Reference
Dimension set for the base types.
Public Types
enum dimensionType {
MASS, LENGTH, TIME, TEMPERATURE,
MOLES, CURRENT, LUMINOUS_INTENSITY
}
Enumeration for the dimension exponents.
typedef FixedList< scalar, 7 > list_type
The array of dimension exponents.
Public Member Functions
ClassName ("dimensionSet")
dimensionSet ()
Construct null (dimensionless).
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles, const scalar current=0, const scalar luminousIntensity=0)
Construct from exponents for the first five or all seven dimensions.
dimensionSet (const FixedList< scalar, 7 > &dimensions)
Construct from exponents for all seven dimensions.
dimensionSet (const dimensionSet &ds)
Copy construct.
dimensionSet (const dictionary &dict, const word &entryName)
Construct from dictionary entry - usually "dimensions".
autoPtr< dimensionSet > clone () const
Construct and return a clone.
dimensionSet (Istream &is)
Construct from Istream.
bool dimensionless () const
Return true if it is dimensionless.
const FixedList< scalar, 7 > & values () const
Return const access to the exponents as a list.
FixedList< scalar, 7 > & values ()
Return non-const access to the exponents as a list.
void clear ()
Reset exponents to be dimensionless.
void reset (const dimensionSet &ds)
Copy assign the exponents from the dimensionSet.
Istream & read (Istream &is, scalar &multiplier, const dictionary &)
Read using provided units. Used only in initial parsing.
Istream & read (Istream &is, scalar &multiplier, const HashTable< dimensionedScalar > &)
Read using provided units.
Istream & read (Istream &is, scalar &multiplier)
Read using system units.
Ostream & write (Ostream &os, scalar &multiplier, const dimensionSets &) const
Write using provided units.
Ostream & write (Ostream &os, scalar &multiplier) const
Write using system units.
scalar operator[] (const dimensionType) const
scalar & operator[] (const dimensionType)
scalar operator[] (const label) const
scalar & operator[] (const label)
bool operator== (const dimensionSet &) const
bool operator!= (const dimensionSet &) const
bool operator= (const dimensionSet &) const
bool operator+= (const dimensionSet &) const
bool operator-= (const dimensionSet &) const
bool operator*= (const dimensionSet &)
bool operator/= (const dimensionSet &)
Static Public Attributes
static constexpr int nDimensions = 7
There are 7 base dimensions.
static const scalar smallExponent = SMALL
Tolerance for 'small' exponents, for near-zero rounding.
Detailed Description
Dimension set for the base types.
This type may be used to implement rigorous dimension checking for algebraic manipulation.
Source files
dimensionSet.H
dimensionSet.C
dimensionSetIO.C
Definition at line 61 of file dimensionSet.H.
Member Typedef Documentation
typedef FixedList<scalar,7> list_type
The array of dimension exponents.
Definition at line 68 of file dimensionSet.H.
Member Enumeration Documentation
enum dimensionType
Enumeration for the dimension exponents.
Enumerator
MASS
kilogram kg
LENGTH
metre m
TIME
second s
TEMPERATURE
Kelvin K.
MOLES
mole mol
CURRENT
Ampere A.
LUMINOUS_INTENSITY
Candela Cd.
Definition at line 81 of file dimensionSet.H.
Constructor & Destructor Documentation
dimensionSet ()
Construct null (dimensionless).
Definition at line 64 of file dimensionSet.C.
dimensionSet (const scalar mass, const scalar length, const scalar time, const scalar temperature, const scalar moles, const scalar current = 0, const scalar luminousIntensity = 0)
Construct from exponents for the first five or all seven dimensions.
Definition at line 71 of file dimensionSet.C.
dimensionSet (const FixedList< scalar, 7 > & dimensions)
Construct from exponents for all seven dimensions.
Definition at line 93 of file dimensionSet.C.
dimensionSet (const dimensionSet & ds)
Copy construct.
Definition at line 99 of file dimensionSet.C.
dimensionSet (const dictionary & dict, const word & entryName)
Construct from dictionary entry - usually "dimensions".
Definition at line 29 of file dimensionSetIO.C.
References Foam::constant::electromagnetic::e, dictionary::lookupEntry(), keyType::REGEX, and entry::stream().
dimensionSet (Istream & is) explicit
Construct from Istream.
Definition at line 40 of file dimensionSetIO.C.
Member Function Documentation
ClassName ("dimensionSet")
autoPtr<dimensionSet> clone () const inline
Construct and return a clone.
Definition at line 221 of file dimensionSet.H.
bool dimensionless () const
Return true if it is dimensionless.
Definition at line 107 of file dimensionSet.C.
const Foam::FixedList< Foam::scalar, 7 > & values () const
Return const access to the exponents as a list.
Definition at line 122 of file dimensionSet.C.
Foam::FixedList< Foam::scalar, 7 > & values ()
Return non-const access to the exponents as a list.
Definition at line 128 of file dimensionSet.C.
void clear ()
Reset exponents to be dimensionless.
Definition at line 134 of file dimensionSet.C.
void reset (const dimensionSet & ds)
Copy assign the exponents from the dimensionSet.
Definition at line 140 of file dimensionSet.C.
References Foam::Zero.
Foam::Istream & read (Istream & is, scalar & multiplier, const dictionary & readSet)
Read using provided units. Used only in initial parsing.
Definition at line 493 of file dimensionSetIO.C.
References Foam::read(), and Foam::unitSet().
Foam::Istream & read (Istream & is, scalar & multiplier, const HashTable< dimensionedScalar > & readSet)
Read using provided units.
Definition at line 406 of file dimensionSetIO.C.
Foam::Istream & read (Istream & is, scalar & multiplier)
Read using system units.
Definition at line 483 of file dimensionSetIO.C.
Foam::Ostream & write (Ostream & os, scalar & multiplier, const dimensionSets & writeUnits) const
Write using provided units.
Definition at line 617 of file dimensionSetIO.C.
Foam::Ostream & write (Ostream & os, scalar & multiplier) const
Write using system units.
Definition at line 689 of file dimensionSetIO.C.
Foam::scalar operator[] (const dimensionType type) const
Definition at line 148 of file dimensionSet.C.
Foam::scalar & operator[] (const dimensionType type)
Definition at line 154 of file dimensionSet.C.
References Foam::type().
Foam::scalar operator[] (const label type) const
Definition at line 160 of file dimensionSet.C.
References Foam::type().
Foam::scalar & operator[] (const label type)
Definition at line 166 of file dimensionSet.C.
References Foam::type().
bool operator== (const dimensionSet & ds) const
Definition at line 172 of file dimensionSet.C.
References Foam::type().
bool operator!= (const dimensionSet & ds) const
Definition at line 190 of file dimensionSet.C.
bool operator= (const dimensionSet & ds) const
Definition at line 196 of file dimensionSet.C.
References Foam::operator==().
bool operator+= (const dimensionSet & ds) const
Definition at line 207 of file dimensionSet.C.
bool operator-= (const dimensionSet & ds) const
Definition at line 218 of file dimensionSet.C.
bool operator*= (const dimensionSet & ds)
Definition at line 229 of file dimensionSet.C.
bool operator/= (const dimensionSet & ds)
Definition at line 237 of file dimensionSet.C.
References reset().
Member Data Documentation
constexpr int nDimensions = 7 static
There are 7 base dimensions.
Definition at line 76 of file dimensionSet.H.
const Foam::scalar smallExponent = SMALL static
Tolerance for 'small' exponents, for near-zero rounding.
Definition at line 98 of file dimensionSet.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionSet/dimensionSet.H
src/OpenFOAM/dimensionSet/dimensionSet.C
src/OpenFOAM/dimensionSet/dimensionSetIO.C