OpenFOAM: localPointRegion Class Reference
localPointRegion Class Reference
Takes mesh with 'baffles' (= boundary faces sharing points). Determines for selected points on boundary faces the 'point region' it is connected to. Each region can be visited by a cell-face-cell walk. Used in duplicating points after splitting baffles.
Public Member Functions
ClassName ("localPointRegion")
Runtime type information.
localPointRegion (const polyMesh &mesh)
Construct from mesh. Assumes all non-coupled boundary points.
localPointRegion (const polyMesh &mesh, const labelList &candidatePoints)
Construct from mesh and candidate points for duplication.
localPointRegion (const polyMesh &mesh, const labelPairList &baffles, const labelList &candidatePoints)
Construct from mesh and candidate points for duplication.
const Map< label > & meshPointMap () const
Per point that is to be duplicated the local index.
const labelListList & pointRegions () const
Per local point the regions it is in.
const Map< label > & meshFaceMap () const
Per face that uses a duplicated point the local index.
const faceList & faceRegions () const
Per face (in local index) the region of its points.
void updateMesh (const mapPolyMesh &)
Force recalculation of locally stored data on topological change.
Static Public Member Functions
static labelList findDuplicateFaces (const primitiveMesh &, const labelList &)
Helper routine to find baffles (two boundary faces using the.
static labelPairList findDuplicateFacePairs (const polyMesh &)
Helper routine to find all baffles (two boundary faces.
Detailed Description
Takes mesh with 'baffles' (= boundary faces sharing points). Determines for selected points on boundary faces the 'point region' it is connected to. Each region can be visited by a cell-face-cell walk. Used in duplicating points after splitting baffles.
Regions are not consecutive per processor. They will be -1..nRegions_.
Note: coupled boundaries (cyclics, parallel) not fully tested.
Source files
localPointRegion.H
localPointRegion.C
Definition at line 65 of file localPointRegion.H.
Constructor & Destructor Documentation
localPointRegion (const polyMesh & mesh)
Construct from mesh. Assumes all non-coupled boundary points.
are candidates for duplication
Definition at line 455 of file localPointRegion.C.
localPointRegion (const polyMesh & mesh, const labelList & candidatePoints)
Construct from mesh and candidate points for duplication.
Definition at line 486 of file localPointRegion.C.
localPointRegion (const polyMesh & mesh, const labelPairList & baffles, const labelList & candidatePoints)
Construct from mesh and candidate points for duplication.
Definition at line 509 of file localPointRegion.C.
Member Function Documentation
ClassName ("localPointRegion")
Runtime type information.
Foam::labelList findDuplicateFaces (const primitiveMesh & mesh, const labelList & boundaryFaces) static
Helper routine to find baffles (two boundary faces using the.
same points but in reverse order) Gets list of (boundary!) faces to check. Returns labelList of same size as the input list with -1 or index of other face in the input list. Does not handle duplicate faces on both sides of processor patch
Definition at line 537 of file localPointRegion.C.
References Foam::abort(), f(), primitiveMesh::faces(), Foam::FatalError, FatalErrorInFunction, forAll, i, primitiveMesh::nInternalFaces(), Foam::nl, pFaces, and primitiveMesh::points().
Foam::List< Foam::labelPair > findDuplicateFacePairs (const polyMesh & mesh) static
Helper routine to find all baffles (two boundary faces.
using the same points but in reverse order)
Definition at line 618 of file localPointRegion.C.
Referenced by snappyLayerDriver::mergePatchFacesUndo().
const Map<label>& meshPointMap () const inline
Per point that is to be duplicated the local index.
Definition at line 204 of file localPointRegion.H.
const labelListList& pointRegions () const inline
Per local point the regions it is in.
Definition at line 212 of file localPointRegion.H.
const Map<label>& meshFaceMap () const inline
Per face that uses a duplicated point the local index.
Definition at line 220 of file localPointRegion.H.
const faceList& faceRegions () const inline
Per face (in local index) the region of its points.
Definition at line 228 of file localPointRegion.H.
void updateMesh (const mapPolyMesh & map)
Force recalculation of locally stored data on topological change.
Definition at line 677 of file localPointRegion.C.
The documentation for this class was generated from the following files:
src/meshTools/regionSplit/localPointRegion.H
src/meshTools/regionSplit/localPointRegion.C