OpenFOAM: OTstream Class Reference
OTstream Class Reference
A simple output token stream that can be used to build token lists.
Public Member Functions
OTstream (streamFormat format=ASCII, versionNumber version=currentVersion)
Construct and set stream status.
OTstream (const OTstream &os)
Copy construct.
OTstream (OTstream &&os)
Move construct.
~OTstream ()=default
Destructor.
const DynamicList< token > & tokens () const
The tokens.
DynamicList< token > & tokens ()
The tokens.
virtual bool write (const token &tok)
Write token to stream or otherwise handle it.
virtual Ostream & write (const char c)
Write single character. Whitespace is suppressed.
virtual Ostream & write (const char *str)
Write the word-characters of a character string.
virtual Ostream & write (const word &str)
Write word.
virtual Ostream & write (const string &str)
Write string.
virtual Ostream & writeQuoted (const std::string &str, const bool quoted=true)
Write std::string surrounded by quotes.
virtual Ostream & write (const int32_t val)
Write int32_t as a label.
virtual Ostream & write (const int64_t val)
Write int64_t as a label.
virtual Ostream & write (const floatScalar val)
Write floatScalar.
virtual Ostream & write (const doubleScalar val)
Write doubleScalar.
virtual Ostream & write (const char *data, std::streamsize count)
Write binary block with 8-byte alignment.
virtual Ostream & writeRaw (const char *data, std::streamsize count)
Low-level raw binary output.
virtual bool beginRawWrite (std::streamsize count)
Begin marker for low-level raw binary output.
virtual bool endRawWrite ()
End marker for low-level raw binary output.
virtual void indent ()
Add indentation characters.
virtual void flush ()
Flush stream.
virtual void endl ()
Add newline and flush stream.
virtual char fill () const
Get the current padding character.
virtual char fill (const char)
Set padding character for formatted field up to field width.
virtual int width () const
Get width of output field.
virtual int width (const int)
Set width of output field.
virtual int precision () const
Get precision of output field.
virtual int precision (const int)
Set precision of output field.
virtual ios_base::fmtflags flags () const
Return flags of output stream.
ios_base::fmtflags flags (const ios_base::fmtflags)
Set flags of stream.
void reset ()
Reset the output buffer and rewind the stream.
virtual void rewind ()
Rewind the output stream.
void print (Ostream &os) const
Print description of IOstream to Ostream.
Public Member Functions inherited from Ostream
Ostream (streamFormat format=ASCII, versionNumber version=currentVersion, compressionType compression=UNCOMPRESSED)
Construct and set stream status.
virtual ~Ostream ()=default
Destructor.
virtual Ostream & write (const keyType &kw)
Write keyType.
unsigned short indentSize () const
Return indent level.
unsigned short & indentSize ()
Access to indent size.
unsigned short indentLevel () const
Return indent level.
unsigned short & indentLevel ()
Access to indent level.
void incrIndent ()
Increment the indent level.
void decrIndent ()
Decrement the indent level.
virtual Ostream & writeKeyword (const keyType &kw)
Write the keyword followed by an appropriate indentation.
virtual Ostream & beginBlock (const keyType &kw)
Write begin block group with the given name.
virtual Ostream & beginBlock ()
Write begin block group without a name.
virtual Ostream & endBlock ()
Write end block group.
virtual Ostream & endEntry ()
Write end entry (';') followed by newline.
template<class T >
Ostream & writeEntry (const keyType &key, const T &value)
Write a keyword/value entry.
template<class T >
Ostream & writeEntryIfDifferent (const word &key, const T &value1, const T &value2)
Write a keyword/value entry only when the two values differ.
Ostream & operator() () const
Return a non-const reference to const Ostream.
Public Member Functions inherited from IOstream
IOstream (const IOstreamOption option)
Construct with specified stream option.
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct with format, version.
virtual ~IOstream ()=default
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
unsigned labelByteSize () const
The label byte-size associated with the stream.
unsigned scalarByteSize () const
The scalar byte-size associated with the stream.
void setLabelByteSize (unsigned nbytes)
Set the label byte-size associated with the stream.
void setScalarByteSize (unsigned nbytes)
Set the scalar byte-size associated with the stream.
template<class T = label>
std::enable_if
< std::is_integral< T >::value,
bool >::type checkLabelSize () const
Check if the label byte-size associated with the stream is the same as the given type.
template<class T = scalar>
std::enable_if
< std::is_floating_point< T >
::value, bool >::type checkScalarSize () const
Check if the scalar byte-size associated with the stream is the same as the given type.
label lineNumber () const
Const access to the current stream line number.
label & lineNumber ()
Non-const access to the current stream line number.
label lineNumber (const label num)
Set the stream line number.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
void print (Ostream &os, const int streamState) const
Print information about the stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from IOstreamOption
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Public Member Functions inherited from DynamicList< token >
constexpr DynamicList () noexcept
Construct null.
DynamicList (const label nElem)
Construct an empty list with given reserve size.
DynamicList (const label nElem, const token &val)
Construct with given size and value for all elements.
DynamicList (const label nElem, const zero)
Construct with given size initializing all elements to zero.
DynamicList (const DynamicList< token, SizeMin > &lst)
Copy construct.
DynamicList (const DynamicList< token, AnySizeMin > &lst)
Copy construct from DynamicList with different sizing parameters.
DynamicList (const UList< token > &lst)
Construct from UList. Size set to UList size.
DynamicList (const FixedList< token, N > &lst)
Construct from a FixedList.
DynamicList (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
DynamicList (std::initializer_list< token > lst)
Construct from an initializer list. Size set to list size.
DynamicList (const IndirectListBase< token, Addr > &lst)
Construct from IndirectList. Size set to addressing size.
DynamicList (DynamicList< token, SizeMin > &&lst)
Move construct.
DynamicList (DynamicList< token, AnySizeMin > &&lst)
Move construct with different sizing parameters.
DynamicList (List< token > &&lst)
Move construct from List.
DynamicList (SortableList< token > &&lst)
Move construct from SortableList.
DynamicList (Istream &is)
Construct from Istream. Size set to size of list read.
label capacity () const noexcept
Size of the underlying storage.
void setCapacity (const label nElem)
Alter the size of the underlying storage.
void setSize (const label nElem)
Alter addressable list size.
void setSize (const label nElem, const token &val)
Alter addressable list size and fill new space with constant.
void resize (const label nElem)
Alter addressable list size.
void resize (const label nElem, const token &val)
Alter addressable list size and fill new space with constant.
void reserve (const label nElem)
Reserve allocation space for at least this size.
void clear ()
Clear the addressed list, i.e. set the size to zero.
void clearStorage ()
Clear the list and delete storage.
label expandStorage ()
Expand the addressable size to fit the allocated capacity.
DynamicList< token, SizeMin > & shrink ()
Shrink the allocated space to the number of elements used.
void swap (DynamicList< token, AnySizeMin > &lst)
Swap content with any sized DynamicList.
void transfer (List< token > &lst)
Transfer contents of the argument List into this.
void transfer (DynamicList< token, AnySizeMin > &lst)
Transfer contents of any sized DynamicList into this.
void transfer (SortableList< token > &lst)
Transfer contents of the argument SortableList into this.
DynamicList< token, SizeMin > & append (const token &val)
Append an element to the end of this list.
DynamicList< token, SizeMin > & append (token &&val)
Move append an element.
DynamicList< token, SizeMin > & append (const UList< token > &lst)
Append another list to the end of this list.
DynamicList< token, SizeMin > & append (const FixedList< token, N > &lst)
Append a FixedList to the end of this list.
DynamicList< token, SizeMin > & append (std::initializer_list< token > lst)
Append an initializer list at the end of this list.
DynamicList< token, SizeMin > & append (const IndirectListBase< token, Addr > &lst)
Append a IndirectList at the end of this list.
DynamicList< token, SizeMin > & append (List< token > &&lst)
Move append list.
DynamicList< token, SizeMin > & append (DynamicList< token, SizeMin > &&lst)
Move append list.
DynamicList< token, SizeMin > & append (DynamicList< token, AnySizeMin > &&lst)
Move append list.
DynamicList< token, SizeMin > & append (SortableList< token > &&lst)
Move append list.
token remove ()
Remove and return the last element. Fatal on an empty list.
token remove (const label idx, const bool fast=false)
Remove and return the specified element. Fatal on an empty list.
label remove (const labelRange &range)
Remove a (start,size) subset from the list.
label remove (std::initializer_list< label > start_size)
Remove a (start,size) subset from the list.
label subset (const labelRange &range)
Retain a (start,size) subset from the list.
label subset (std::initializer_list< label > start_size)
Retain a (start,size) subset from List.
token & operator() (const label i)
Return non-const access to an element, resizing list if.
void operator= (const token &val)
Assignment of all addressed entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (const UList< token > &lst)
Assignment to UList.
void operator= (const FixedList< token, N > &lst)
Assignment to FixedList.
void operator= (const DynamicList< token, SizeMin > &lst)
Assignment to DynamicList.
void operator= (const DynamicList< token, AnySizeMin > &lst)
Assignment from DynamicList with different sizing parameters.
void operator= (std::initializer_list< token > lst)
Assignment from initializer list.
void operator= (const IndirectListBase< token, Addr > &lst)
Assignment from IndirectList.
void operator= (List< token > &&lst)
Move assignment.
void operator= (DynamicList< token, SizeMin > &&lst)
Move assignment.
void operator= (DynamicList< token, AnySizeMin > &&lst)
Move assignment.
void operator= (SortableList< token > &&lst)
Move assignment.
Public Member Functions inherited from List< T >
constexpr List () noexcept
Null constructor.
List (const label len)
Construct with given size.
List (const label len, const T &val)
Construct with given size and value for all elements.
List (const label len, const zero)
Construct with given size initializing all elements to zero.
List (const one, const T &val)
Construct with length=1, copying the value as the only content.
List (const one, T &&val)
Construct with length=1, moving the value as the only content.
List (const one, const zero)
Construct with length=1, initializing content to zero.
List (const List< T > &a)
Copy construct from list.
List (const UList< T > &a)
Copy construct contents from list.
List (List< T > &a, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &list, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
template<unsigned N>
List (const FixedList< T, N > &list)
Construct as copy of FixedList<T, N>
List (const PtrList< T > &list)
Construct as copy of PtrList<T>
List (const SLList< T > &list)
Construct as copy of SLList<T>
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
Construct as copy of IndirectList contents.
List (std::initializer_list< T > list)
Construct from an initializer list.
List (List< T > &&list)
Move construct from List.
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
Move construct from DynamicList.
List (SortableList< T > &&list)
Move construct from SortableList.
List (SLList< T > &&list)
Move construct from SLList.
List (Istream &is)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
void resize (const label newSize)
Adjust allocated size of list.
void resize (const label newSize, const T &val)
Adjust allocated size of list and set val for new elements.
void setSize (const label newSize)
Alias for resize(const label)
void setSize (const label newSize, const T &val)
Alias for resize(const label, const T&)
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &val)
Append an element at the end of the list.
void append (T &&val)
Move append an element at the end of the list.
void append (const UList< T > &list)
Append a List to the end of this list.
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
Append IndirectList contents at the end of this list.
void transfer (List< T > &list)
Transfer the contents of the argument List into this list and annul the argument list.
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (SortableList< T > &list)
Transfer the contents of the argument List into this list and annul the argument list.
T & newElmt (const label i)
Return subscript-checked element of UList and resizing the list if required.
void operator= (const UList< T > &a)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &list)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &list)
Assignment to SLList operator. Takes linear time.
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
Assignment from IndirectList. Takes linear time.
void operator= (std::initializer_list< T > list)
Assignment to an initializer list.
void operator= (const T &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (List< T > &&list)
Move assignment. Takes constant time.
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
Move assignment. Takes constant time.
void operator= (SortableList< T > &&list)
Move assignment. Takes constant time.
void operator= (SLList< T > &&list)
Move assignment. Takes constant time.
void shallowCopy (const UList< T > &)=delete
No shallowCopy permitted.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type set (const label i, bool val=true)
A bitSet::set() method for a list of bool.
template<>
void resize (const label newSize)
Public Member Functions inherited from UList< T >
constexpr UList () noexcept
Null constructor.
UList (T *__restrict__ v, label size) noexcept
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const T & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
T & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const T & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
T & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
std::streamsize byteSize () const
Return the binary size in number of characters of the UList if the element is a primitive type.
const T * cdata () const
Return a const pointer to the first data element.
T * data ()
Return a pointer to the first data element.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is within valid range [0,size].
void checkIndex (const label i) const
Check index is within valid range [0,size)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const T &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const T &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const T &val, const label start=0) const
True if the value if found in the list.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element. Fatal on an empty list.
void swapLast (const label i)
Swap element with the last element. Fatal on an empty list.
void shallowCopy (const UList< T > &list)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &list)
Copy elements of the given UList.
T & operator[] (const label i)
Return element of UList.
const T & operator[] (const label i) const
Return element of constant UList.
UList< T > operator[] (const labelRange &range)
Return (start,size) subset from UList with non-const access.
const UList< T > operator[] (const labelRange &range) const
Return (start,size) subset from UList with const access.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const noexcept
The number of elements in the UList.
bool empty () const noexcept
True if the UList is empty (ie, size() is zero)
void swap (UList< T > &list)
Swap content with another UList of the same type in constant time.
bool operator== (const UList< T > &a) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &a) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &list) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &a) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &a) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &a) const
Return true if !(a < b). Takes linear time.
void writeEntry (const word &keyword, Ostream &os) const
Write the List as a dictionary entry with keyword.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type test (const label i) const
A bitSet::test() method for a list of bool.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type get (const label i) const
A bitSet::get() method for a list of bool.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type unset (const label i)
A bitSet::unset() method for a list of bool.
template<>
const bool & operator[] (const label i) const
template<>
Foam::UPstream::commsStruct & operator[] (const label procID)
template<>
const Foam::UPstream::commsStruct & operator[] (const label procID) const
template<>
UPstream::commsStruct & operator[] (const label)
template<>
const UPstream::commsStruct & operator[] (const label) const
Additional Inherited Members
Public Types inherited from IOstream
enum streamAccess : char { CLOSED = 0, OPENED }
Enumeration for stream open/closed state.
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
The value type the list contains.
typedef T * pointer
The pointer type for non-const access to value_type items.
typedef const T * const_pointer
The pointer type for const access to value_type items.
typedef T & reference
The type used for storing into value_type objects.
typedef const T & const_reference
The type used for reading from constant value_type objects.
typedef T * iterator
Random access iterator for traversing a UList.
typedef const T * const_iterator
Random access iterator for traversing a UList.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Static Public Member Functions inherited from IOstream
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision.
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Static Public Member Functions inherited from DynamicList< token >
static constexpr label min_size () noexcept
Normal lower capacity limit - the SizeMin template parameter.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a UList reference to a nullObject.
static constexpr label max_size () noexcept
The size of the largest possible UList.
Static Public Attributes inherited from IOstream
static unsigned int precision_
Default precision.
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Protected Member Functions inherited from IOstream
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Member Functions inherited from DynamicList< token >
void assignDynList (const ListType &lst)
Copy assignment from another list.
Protected Member Functions inherited from UList< T >
void size (const label n) noexcept
Override size to be inconsistent with allocated storage.
void writeEntry (Ostream &os) const
Write the UList with its compound type.
labelRange validateRange (const labelRange &range) const
Return a validated (start,size) subset range, which means that it always addresses a valid section of the list.
UList< T > & operator= (const UList< T > &)=delete
No copy assignment (default: shallow copy)
Protected Attributes inherited from Ostream
unsigned short indentSize_ = 4
Number of spaces per indent level.
unsigned short indentLevel_ = 0
Current indent level.
Protected Attributes inherited from IOstream
streamAccess openClosed_
ios_base::iostate ioState_
unsigned short labelByteSize_
The label byte-size (could also be stored as byte)
unsigned short scalarByteSize_
The scalar byte-size (could also be stored as byte)
label lineNumber_
The file line.
Static Protected Attributes inherited from Ostream
static constexpr const
unsigned short entryIndentation_ = 16
Indentation of the entry from the start of the keyword.
Static Protected Attributes inherited from IOstream
static fileName staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
A simple output token stream that can be used to build token lists.
Note
Appending single characters to token list is fragile.
Source files
OTstream.H
OTstream.C
Definition at line 51 of file OTstream.H.
Constructor & Destructor Documentation
OTstream (streamFormat format = ASCII, versionNumber version = currentVersion) inline
Construct and set stream status.
Definition at line 64 of file OTstream.H.
References IOstream::setGood(), and IOstream::setOpened().
OTstream (const OTstream & os) inline
Copy construct.
Definition at line 79 of file OTstream.H.
References IOstream::setGood(), and IOstream::setOpened().
OTstream (OTstream && os) inline
Move construct.
Definition at line 91 of file OTstream.H.
References IOstream::setGood(), and IOstream::setOpened().
~OTstream () default
Destructor.
Member Function Documentation
const DynamicList<token>& tokens () const inline
The tokens.
Definition at line 112 of file OTstream.H.
DynamicList<token>& tokens () inline
The tokens.
Definition at line 120 of file OTstream.H.
bool write (const token & tok) virtual
Write token to stream or otherwise handle it.
Returns
false if the token type was not handled by this method
Implements Ostream.
Definition at line 27 of file OTstream.C.
References DynamicList< token >::append(), and token::good().
Foam::Ostream & write (const char c) virtual
Write single character. Whitespace is suppressed.
Implements Ostream.
Definition at line 39 of file OTstream.C.
Foam::Ostream & write (const char * str) virtual
Write the word-characters of a character string.
Sends as a single char, or as word.
Implements Ostream.
Definition at line 51 of file OTstream.C.
Foam::Ostream & write (const word & str) virtual
Write word.
Implements Ostream.
Definition at line 70 of file OTstream.C.
Foam::Ostream & write (const string & str) virtual
Write string.
Implements Ostream.
Definition at line 78 of file OTstream.C.
References append().
Foam::Ostream & writeQuoted (const std::string & str, const bool quoted = true) virtual
Write std::string surrounded by quotes.
Optional write without quotes.
Implements Ostream.
Definition at line 87 of file OTstream.C.
Foam::Ostream & write (const int32_t val) virtual
Write int32_t as a label.
Implements Ostream.
Definition at line 105 of file OTstream.C.
Foam::Ostream & write (const int64_t val) virtual
Write int64_t as a label.
Implements Ostream.
Definition at line 113 of file OTstream.C.
References append().
Foam::Ostream & write (const floatScalar val) virtual
Write floatScalar.
Implements Ostream.
Definition at line 121 of file OTstream.C.
References append().
Foam::Ostream & write (const doubleScalar val) virtual
Write doubleScalar.
Implements Ostream.
Definition at line 129 of file OTstream.C.
References append().
Foam::Ostream & write (const char * data, std::streamsize count) virtual
Write binary block with 8-byte alignment.
Implements Ostream.
Definition at line 137 of file OTstream.C.
References append().
Foam::Ostream & writeRaw (const char * data, std::streamsize count) virtual
Low-level raw binary output.
Implements Ostream.
Definition at line 153 of file OTstream.C.
bool beginRawWrite (std::streamsize count) virtual
Begin marker for low-level raw binary output.
The count indicates the number of bytes for subsequent writeRaw calls.
Implements Ostream.
Definition at line 167 of file OTstream.C.
virtual bool endRawWrite () inline virtual
End marker for low-level raw binary output.
Implements Ostream.
Definition at line 209 of file OTstream.H.
virtual void indent () inline virtual
Add indentation characters.
Implements Ostream.
Definition at line 217 of file OTstream.H.
virtual void flush () inline virtual
Flush stream.
Implements Ostream.
Definition at line 226 of file OTstream.H.
virtual void endl () inline virtual
Add newline and flush stream.
Implements Ostream.
Definition at line 232 of file OTstream.H.
virtual char fill () const inline virtual
Get the current padding character.
Returns
previous padding character
Implements Ostream.
Definition at line 240 of file OTstream.H.
virtual char fill (const char) inline virtual
Set padding character for formatted field up to field width.
Implements Ostream.
Definition at line 248 of file OTstream.H.
References OTstream::rewind().
virtual int width () const inline virtual
Get width of output field.
Implements Ostream.
Definition at line 256 of file OTstream.H.
References DynamicList< T, SizeMin >::clear().
virtual int width (const int) inline virtual
Set width of output field.
Returns
previous width
Implements Ostream.
Definition at line 266 of file OTstream.H.
virtual int precision () const inline virtual
Get precision of output field.
Implements Ostream.
Definition at line 274 of file OTstream.H.
virtual int precision (const int) inline virtual
Set precision of output field.
Returns
old precision
Implements Ostream.
Definition at line 284 of file OTstream.H.
virtual ios_base::fmtflags flags () const inline virtual
Return flags of output stream.
Implements IOstream.
Definition at line 296 of file OTstream.H.
ios_base::fmtflags flags (const ios_base::fmtflags) inline virtual
Set flags of stream.
Implements IOstream.
Definition at line 307 of file OTstream.H.
void reset () inline
Reset the output buffer and rewind the stream.
Definition at line 318 of file OTstream.H.
virtual void rewind () inline virtual
Rewind the output stream.
Definition at line 326 of file OTstream.H.
Referenced by OTstream::fill().
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented from IOstream.
Definition at line 182 of file OTstream.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Tstreams/OTstream.H
src/OpenFOAM/db/IOstreams/Tstreams/OTstream.C