OpenFOAM: ThermoPhaseModel< BasePhaseModel, ThermoType > Class Template Reference
ThermoPhaseModel< BasePhaseModel, ThermoType > Class Template Reference
Class which represents a phase with a thermodynamic model. Provides access to the thermodynamic variables. Note that the thermo model itself is not returned as this class could be substituted in the hierarchy for one which mirrors the functionality, but does not include a thermo model; an incompressible phase model, for example.
Public Member Functions
ThermoPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~ThermoPhaseModel ()
Destructor.
virtual bool compressible () const
Return whether the phase is compressible.
virtual const rhoThermo & thermo () const
Return the thermophysical model.
virtual rhoThermo & thermoRef ()
Access the thermophysical model.
virtual tmp< volScalarField > rho () const
Return the density field.
virtual tmp< volScalarField > mu () const
Return the laminar dynamic viscosity.
virtual tmp< scalarField > mu (const label patchi) const
Return the laminar dynamic viscosity on a patch.
virtual tmp< volScalarField > nu () const
Return the laminar kinematic viscosity.
virtual tmp< scalarField > nu (const label patchi) const
Return the laminar kinematic viscosity on a patch.
virtual tmp< volScalarField > alpha () const
Thermal diffusivity for enthalpy of mixture [kg/m/s].
virtual tmp< scalarField > alpha (const label patchi) const
Thermal diffusivity for enthalpy of mixture for patch [kg/m/s].
virtual tmp< volScalarField > kappa () const
Thermal diffusivity for temperature of mixture [J/m/s/K].
virtual tmp< scalarField > kappa (const label patchi) const
Thermal diffusivity for temperature of mixture.
virtual tmp< volScalarField > alphahe () const
Thermal diffusivity for energy of mixture [kg/m/s].
virtual tmp< scalarField > alphahe (const label patchi) const
Thermal diffusivity for energy of mixture for patch [kg/m/s].
virtual tmp< volScalarField > kappaEff (const volScalarField &alphat) const
Effective thermal turbulent diffusivity for temperature.
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
Effective thermal turbulent diffusivity for temperature.
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
Effective thermal turbulent diffusivity of mixture [kg/m/s].
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
Effective thermal turbulent diffusivity of mixture.
Protected Attributes
autoPtr< ThermoType > thermo_
Thermophysical model.
Detailed Description
template<class BasePhaseModel, class ThermoType>
class Foam::ThermoPhaseModel< BasePhaseModel, ThermoType >
Class which represents a phase with a thermodynamic model. Provides access to the thermodynamic variables. Note that the thermo model itself is not returned as this class could be substituted in the hierarchy for one which mirrors the functionality, but does not include a thermo model; an incompressible phase model, for example.
Source files
ThermoPhaseModel.H
ThermoPhaseModel.C
Definition at line 53 of file ThermoPhaseModel.H.
Constructor & Destructor Documentation
ThermoPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 36 of file ThermoPhaseModel.C.
References IOobject::groupName(), Foam::name(), ThermoPhaseModel< BasePhaseModel, ThermoType >::thermo_, and DimensionedField< Type, GeoMesh >::typeName().
~ThermoPhaseModel () virtual
Destructor.
Definition at line 57 of file ThermoPhaseModel.C.
Member Function Documentation
bool compressible () const virtual
Return whether the phase is compressible.
Definition at line 64 of file ThermoPhaseModel.C.
const Foam::rhoThermo & thermo () const virtual
Return the thermophysical model.
Definition at line 72 of file ThermoPhaseModel.C.
Foam::rhoThermo & thermoRef () virtual
Access the thermophysical model.
Definition at line 80 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > rho () const virtual
Return the density field.
Definition at line 88 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > mu () const virtual
Return the laminar dynamic viscosity.
Definition at line 96 of file ThermoPhaseModel.C.
Foam::tmp< Foam::scalarField > mu (const label patchi) const virtual
Return the laminar dynamic viscosity on a patch.
Definition at line 105 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > nu () const virtual
Return the laminar kinematic viscosity.
Definition at line 115 of file ThermoPhaseModel.C.
Foam::tmp< Foam::scalarField > nu (const label patchi) const virtual
Return the laminar kinematic viscosity on a patch.
Definition at line 124 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > alpha () const virtual
Thermal diffusivity for enthalpy of mixture [kg/m/s].
Definition at line 195 of file ThermoPhaseModel.C.
Foam::tmp< Foam::scalarField > alpha (const label patchi) const virtual
Thermal diffusivity for enthalpy of mixture for patch [kg/m/s].
Definition at line 204 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > kappa () const virtual
Thermal diffusivity for temperature of mixture [J/m/s/K].
Definition at line 134 of file ThermoPhaseModel.C.
Foam::tmp< Foam::scalarField > kappa (const label patchi) const virtual
Thermal diffusivity for temperature of mixture.
for patch [J/m/s/K]
Definition at line 143 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > alphahe () const virtual
Thermal diffusivity for energy of mixture [kg/m/s].
Definition at line 153 of file ThermoPhaseModel.C.
Foam::tmp< Foam::scalarField > alphahe (const label patchi) const virtual
Thermal diffusivity for energy of mixture for patch [kg/m/s].
Definition at line 162 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > kappaEff (const volScalarField & alphat) const virtual
Effective thermal turbulent diffusivity for temperature.
of mixture [J/m/s/K]
Definition at line 173 of file ThermoPhaseModel.C.
Foam::tmp< Foam::scalarField > kappaEff (const scalarField & alphat, const label patchi) const virtual
Effective thermal turbulent diffusivity for temperature.
of mixture for patch [J/m/s/K]
Definition at line 184 of file ThermoPhaseModel.C.
Foam::tmp< Foam::volScalarField > alphaEff (const volScalarField & alphat) const virtual
Effective thermal turbulent diffusivity of mixture [kg/m/s].
Definition at line 215 of file ThermoPhaseModel.C.
Foam::tmp< Foam::scalarField > alphaEff (const scalarField & alphat, const label patchi) const virtual
Effective thermal turbulent diffusivity of mixture.
for patch [kg/m/s]
Definition at line 226 of file ThermoPhaseModel.C.
Member Data Documentation
autoPtr<ThermoType> thermo_ protected
Thermophysical model.
Definition at line 64 of file ThermoPhaseModel.H.
Referenced by ThermoPhaseModel< BasePhaseModel, ThermoType >::ThermoPhaseModel().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/phaseModel/ThermoPhaseModel/ThermoPhaseModel.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/phaseModel/ThermoPhaseModel/ThermoPhaseModel.C