OpenFOAM: KinematicParcel< ParcelType > Class Template Reference
KinematicParcel< ParcelType > Class Template Reference
Parcels
Kinematic parcel class with rotational motion (as spherical particles only) and one/two-way coupling with the continuous phase.
Classes
class constantProperties
Class to hold kinematic particle constant properties.
class iNew
Factory class to read-construct particles used for.
class trackingData
Public Member Functions
TypeName ("KinematicParcel")
Runtime type information.
AddToPropertyList (ParcelType," active"+" typeId"+" nParticle"+" d"+" dTarget"+" (Ux Uy Uz)"+" rho"+" age"+" tTurb"+" (UTurbx UTurby UTurbz)")
String representation of properties.
KinematicParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from mesh, coordinates and topology.
KinematicParcel (const polyMesh &mesh, const vector &position, const label celli)
Construct from a position and a cell, searching for the rest of the.
KinematicParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const constantProperties &constProps)
Construct from components.
KinematicParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
KinematicParcel (const KinematicParcel &p)
Construct as a copy.
KinematicParcel (const KinematicParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
bool active () const
Return const access to active flag.
label typeId () const
Return const access to type id.
scalar nParticle () const
Return const access to number of particles.
scalar d () const
Return const access to diameter.
scalar dTarget () const
Return const access to target diameter.
const vector & U () const
Return const access to velocity.
scalar rho () const
Return const access to density.
scalar age () const
Return const access to the age.
scalar tTurb () const
Return const access to time spent in turbulent eddy.
const vector & UTurb () const
Return const access to turbulent velocity fluctuation.
void active (const bool state)
Set active flag to the specified state.
label & typeId ()
Return access to type id.
scalar & nParticle ()
Return access to number of particles.
scalar & d ()
Return access to diameter.
scalar & dTarget ()
Return access to target diameter.
vector & U ()
Return access to velocity.
scalar & rho ()
Return access to density.
scalar & age ()
Return access to the age.
scalar & tTurb ()
Return access to time spent in turbulent eddy.
vector & UTurb ()
Return access to turbulent velocity fluctuation.
scalar massCell (const trackingData &td) const
Cell owner mass.
scalar mass () const
Particle mass.
scalar momentOfInertia () const
Particle moment of inertia around diameter axis.
scalar volume () const
Particle volume.
scalar areaP () const
Particle projected area.
scalar areaS () const
Particle surface area.
scalar Re (const trackingData &td) const
Reynolds number.
scalar We (const trackingData &td, const scalar sigma) const
Weber number.
scalar Eo (const trackingData &td, const scalar sigma) const
Eotvos number.
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
Set cell values.
template<class TrackCloudType >
void calcDispersion (TrackCloudType &cloud, trackingData &td, const scalar dt)
Apply dispersion to the carrier phase velocity and update.
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
Correct cell values using latest transfer information.
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
Update parcel properties over the time interval.
template<class TrackCloudType >
bool move (TrackCloudType &cloud, trackingData &td, const scalar trackTime)
Move the parcel.
template<class TrackCloudType >
bool hitPatch (TrackCloudType &cloud, trackingData &td)
Overridable function to handle the particle hitting a patch.
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &cloud, trackingData &td)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &cloud, trackingData &td)
Overridable function to handle the particle hitting a wallPatch.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
Write individual parcel properties to stream.
template<class TrackCloudType >
const Foam::vector calcVelocity (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector &Su, vector &dUTrans, scalar &Spu) const
template<class CloudType >
void readFields (CloudType &c)
template<class CloudType >
void writeFields (const CloudType &c)
Static Public Member Functions
static scalar volume (const scalar d)
Particle volume for a given diameter.
static scalar areaP (const scalar d)
Projected area for given diameter.
static scalar areaS (const scalar d)
Surface area for given diameter.
static scalar Re (const scalar rhoc, const vector &U, const vector &Uc, const scalar d, const scalar muc)
Reynolds number for given conditions.
static scalar We (const scalar rhoc, const vector &U, const vector &Uc, const scalar d, const scalar sigma)
Weber number for given conditions.
static scalar Eo (const vector &g, const scalar rho, const scalar rhoc, const vector &U, const scalar d, const scalar sigma)
Eotvos number for given conditions.
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
Read.
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
Write.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields
Size in bytes of the fields.
Protected Member Functions
template<class TrackCloudType >
const vector calcVelocity (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector &Su, vector &dUTrans, scalar &Spu) const
Calculate new particle velocity.
Protected Attributes
label active_
Active flag - tracking inactive when active = false.
label typeId_
Parcel type id.
scalar nParticle_
Number of particles in Parcel.
scalar d_
Diameter [m].
scalar dTarget_
Target diameter [m].
vector U_
Velocity of Parcel [m/s].
scalar rho_
Density [kg/m3].
scalar age_
Age [s].
scalar tTurb_
Time spent in turbulent eddy [s].
vector UTurb_
Turbulent velocity fluctuation [m/s].
Friends
Ostream & operator (Ostream &, const KinematicParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::KinematicParcel< ParcelType >
Kinematic parcel class with rotational motion (as spherical particles only) and one/two-way coupling with the continuous phase.
Sub-models include:
drag
turbulent dispersion
wall interactions
Source files
KinematicParcel.H
KinematicParcelI.H
KinematicParcel.C
KinematicParcelIO.C
Definition at line 62 of file KinematicParcel.H.
Constructor & Destructor Documentation
KinematicParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Construct from mesh, coordinates and topology.
Other properties initialised as null
Definition at line 70 of file KinematicParcelI.H.
KinematicParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Construct from a position and a cell, searching for the rest of the.
required topology. Other properties are initialised as null.
Definition at line 94 of file KinematicParcelI.H.
KinematicParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const constantProperties & constProps) inline
Construct from components.
Definition at line 116 of file KinematicParcelI.H.
KinematicParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 46 of file KinematicParcelIO.C.
KinematicParcel (const KinematicParcel< ParcelType > & p)
Construct as a copy.
KinematicParcel (const KinematicParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
const vector calcVelocity (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector & Su, vector & dUTrans, scalar & Spu) const protected
Calculate new particle velocity.
TypeName ("KinematicParcel< ParcelType >")
Runtime type information.
AddToPropertyList (ParcelType , " active"+" typeId"+" nParticle"+" d"+" dTarget"+" (Ux Uy Uz)"+" rho"+" age"+" tTurb"+" (UTurbx UTurby UTurbz)")
String representation of properties.
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 510 of file KinematicParcel.H.
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 518 of file KinematicParcel.H.
bool active () const inline
Return const access to active flag.
Definition at line 189 of file KinematicParcelI.H.
Foam::label typeId () const inline
Return const access to type id.
Definition at line 196 of file KinematicParcelI.H.
Foam::scalar nParticle () const inline
Return const access to number of particles.
Definition at line 203 of file KinematicParcelI.H.
Foam::scalar d () const inline
Return const access to diameter.
Definition at line 210 of file KinematicParcelI.H.
Foam::scalar dTarget () const inline
Return const access to target diameter.
Definition at line 217 of file KinematicParcelI.H.
const Foam::vector & U () const inline
Return const access to velocity.
Definition at line 224 of file KinematicParcelI.H.
Referenced by MPPICParcel< ParcelType >::move().
Foam::scalar rho () const inline
Return const access to density.
Definition at line 231 of file KinematicParcelI.H.
Foam::scalar age () const inline
Return const access to the age.
Definition at line 238 of file KinematicParcelI.H.
Foam::scalar tTurb () const inline
Return const access to time spent in turbulent eddy.
Definition at line 245 of file KinematicParcelI.H.
const Foam::vector & UTurb () const inline
Return const access to turbulent velocity fluctuation.
Definition at line 252 of file KinematicParcelI.H.
void active (const bool state) inline
Set active flag to the specified state.
Definition at line 259 of file KinematicParcelI.H.
Foam::label & typeId () inline
Return access to type id.
Definition at line 266 of file KinematicParcelI.H.
Foam::scalar & nParticle () inline
Return access to number of particles.
Definition at line 273 of file KinematicParcelI.H.
Foam::scalar & d () inline
Return access to diameter.
Definition at line 280 of file KinematicParcelI.H.
Foam::scalar & dTarget () inline
Return access to target diameter.
Definition at line 287 of file KinematicParcelI.H.
Foam::vector & U () inline
Return access to velocity.
Definition at line 294 of file KinematicParcelI.H.
Foam::scalar & rho () inline
Return access to density.
Definition at line 301 of file KinematicParcelI.H.
Foam::scalar & age () inline
Return access to the age.
Definition at line 308 of file KinematicParcelI.H.
Foam::scalar & tTurb () inline
Return access to time spent in turbulent eddy.
Definition at line 315 of file KinematicParcelI.H.
Foam::vector & UTurb () inline
Return access to turbulent velocity fluctuation.
Definition at line 322 of file KinematicParcelI.H.
Foam::scalar massCell (const trackingData & td) const inline
Cell owner mass.
Definition at line 330 of file KinematicParcelI.H.
Foam::scalar mass () const inline
Particle mass.
Definition at line 339 of file KinematicParcelI.H.
References mesh.
Foam::scalar momentOfInertia () const inline
Particle moment of inertia around diameter axis.
Definition at line 346 of file KinematicParcelI.H.
References Foam::fieldTypes::volume.
Foam::scalar volume () const inline
Particle volume.
Definition at line 353 of file KinematicParcelI.H.
References Foam::sqr().
Foam::scalar volume (const scalar d) inline static
Particle volume for a given diameter.
Definition at line 360 of file KinematicParcelI.H.
References Foam::fieldTypes::volume.
Foam::scalar areaP () const inline
Particle projected area.
Definition at line 367 of file KinematicParcelI.H.
References Foam::constant::mathematical::pi(), and Foam::pow3().
Foam::scalar areaP (const scalar d) inline static
Projected area for given diameter.
Definition at line 374 of file KinematicParcelI.H.
Foam::scalar areaS () const inline
Particle surface area.
Definition at line 381 of file KinematicParcelI.H.
Foam::scalar areaS (const scalar d) inline static
Surface area for given diameter.
Definition at line 388 of file KinematicParcelI.H.
Foam::scalar Re (const trackingData & td) const inline
Reynolds number.
Definition at line 396 of file KinematicParcelI.H.
References d, and Foam::constant::mathematical::pi().
Foam::scalar Re (const scalar rhoc, const vector & U, const vector & Uc, const scalar d, const scalar muc) inline static
Reynolds number for given conditions.
Definition at line 406 of file KinematicParcelI.H.
References Foam::Re().
Foam::scalar We (const trackingData & td, const scalar sigma) const inline
Weber number.
Definition at line 420 of file KinematicParcelI.H.
References Foam::mag(), and Foam::max().
Foam::scalar We (const scalar rhoc, const vector & U, const vector & Uc, const scalar d, const scalar sigma) inline static
Weber number for given conditions.
Definition at line 431 of file KinematicParcelI.H.
References sigma().
Foam::scalar Eo (const trackingData & td, const scalar sigma) const inline
Eotvos number.
Definition at line 445 of file KinematicParcelI.H.
References Foam::magSqr(), and Foam::max().
Foam::scalar Eo (const vector & g, const scalar rho, const scalar rhoc, const vector & U, const scalar d, const scalar sigma) inline static
Eotvos number for given conditions.
Definition at line 456 of file KinematicParcelI.H.
References sigma().
void setCellValues (TrackCloudType & cloud, trackingData & td)
Set cell values.
Definition at line 38 of file KinematicParcel.C.
References coordinates(), Foam::expressions::patchExpr::debug, Foam::endl(), interpolation< class >::interpolate(), Foam::nl, KinematicParcel< ParcelType >::trackingData::rhoc(), KinematicParcel< ParcelType >::trackingData::rhoInterp(), KinematicParcel< ParcelType >::trackingData::Uc(), KinematicParcel< ParcelType >::trackingData::UInterp(), and WarningInFunction.
void calcDispersion (TrackCloudType & cloud, trackingData & td, const scalar dt)
Apply dispersion to the carrier phase velocity and update.
parcel turbulence parameters
Definition at line 68 of file KinematicParcel.C.
void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Correct cell values using latest transfer information.
Definition at line 89 of file KinematicParcel.C.
void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Update parcel properties over the time interval.
Definition at line 102 of file KinematicParcel.C.
bool move (TrackCloudType & cloud, trackingData & td, const scalar trackTime)
Move the parcel.
Definition at line 275 of file KinematicParcel.C.
References cloudSolution::cellValueSourceCorrection(), d, f(), Foam::mag(), Foam::max(), maxCo, cloudSolution::maxCo(), Foam::min(), p, s, and Foam::start.
bool hitPatch (TrackCloudType & cloud, trackingData & td)
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions
Definition at line 369 of file KinematicParcel.C.
void hitProcessorPatch (TrackCloudType & cloud, trackingData & td)
Overridable function to handle the particle hitting a.
processorPatch
Definition at line 412 of file KinematicParcel.C.
void hitWallPatch (TrackCloudType & cloud, trackingData & td)
Overridable function to handle the particle hitting a wallPatch.
Definition at line 424 of file KinematicParcel.C.
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Definition at line 434 of file KinematicParcel.C.
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Definition at line 444 of file KinematicParcel.C.
static void readFields (TrackCloudType & c) static
Read.
static void writeFields (const TrackCloudType & c) static
Write.
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Write individual parcel properties to stream.
Definition at line 264 of file KinematicParcelIO.C.
void readObjects (CloudType & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 295 of file KinematicParcelIO.C.
void writeObjects (const CloudType & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Definition at line 338 of file KinematicParcelIO.C.
const Foam::vector calcVelocity (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar mu, const scalar mass, const vector & Su, vector & dUTrans, scalar & Spu) const
Definition at line 154 of file KinematicParcel.C.
void readFields (CloudType & c)
Definition at line 111 of file KinematicParcelIO.C.
void writeFields (const CloudType & c)
Definition at line 209 of file KinematicParcelIO.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const KinematicParcel< ParcelType > &) friend
Member Data Documentation
const std::size_t sizeofFields static
Size in bytes of the fields.
Definition at line 94 of file KinematicParcel.H.
label active_ protected
Active flag - tracking inactive when active = false.
Store as label for data alignment, but only has bool states
Definition at line 344 of file KinematicParcel.H.
label typeId_ protected
Parcel type id.
Definition at line 349 of file KinematicParcel.H.
scalar nParticle_ protected
Number of particles in Parcel.
Definition at line 354 of file KinematicParcel.H.
scalar d_ protected
Diameter [m].
Definition at line 359 of file KinematicParcel.H.
scalar dTarget_ protected
Target diameter [m].
Definition at line 364 of file KinematicParcel.H.
vector U_ protected
Velocity of Parcel [m/s].
Definition at line 369 of file KinematicParcel.H.
scalar rho_ protected
Density [kg/m3].
Definition at line 374 of file KinematicParcel.H.
scalar age_ protected
Age [s].
Definition at line 379 of file KinematicParcel.H.
scalar tTurb_ protected
Time spent in turbulent eddy [s].
Definition at line 384 of file KinematicParcel.H.
vector UTurb_ protected
Turbulent velocity fluctuation [m/s].
Definition at line 389 of file KinematicParcel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcel.C
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelI.H
src/lagrangian/intermediate/parcels/Templates/KinematicParcel/KinematicParcelIO.C