OpenFOAM: multivariateScheme< Type, Scheme > Class Template Reference
multivariateScheme< Type, Scheme > Class Template Reference
Generic multi-variate discretisation scheme class which may be instantiated for any of the NVD, CNVD or NVDV schemes.
Classes
class fieldScheme
surfaceInterpolationScheme sub-class returned by operator(field)
Public Member Functions
TypeName ("multivariateScheme")
Runtime type information.
multivariateScheme (const fvMesh &mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct for field, faceFlux and Istream.
tmp
< surfaceInterpolationScheme
< Type > > operator() (const GeometricField< Type, fvPatchField, volMesh > &field) const
Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, multivariateSurfaceInterpolationScheme, Istream,(const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &is),(mesh, fields, faceFlux, is))
multivariateSurfaceInterpolationScheme (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct for interpolating given field.
virtual ~multivariateSurfaceInterpolationScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
const fieldTable & fields () const
Return fields to be interpolated.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from multivariateSurfaceInterpolationScheme< Type >
static tmp
< multivariateSurfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, const fieldTable &fields, const surfaceScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type, class Scheme>
class Foam::multivariateScheme< Type, Scheme >
Generic multi-variate discretisation scheme class which may be instantiated for any of the NVD, CNVD or NVDV schemes.
Source files
multivariateScheme.H
multivariateScheme.C
Definition at line 49 of file multivariateScheme.H.
Constructor & Destructor Documentation
multivariateScheme (const fvMesh & mesh, const typename multivariateSurfaceInterpolationScheme< Type >::fieldTable & fields, const surfaceScalarField & faceFlux, Istream & schemeData)
Construct for field, faceFlux and Istream.
Definition at line 30 of file multivariateScheme.C.
References HashTable< T, Key, Hash >::cbegin(), multivariateSurfaceInterpolationScheme< Type >::fields(), iter, Foam::limiter(), Foam::min(), and upwind< Type >::weights().
Member Function Documentation
TypeName ("multivariateScheme< Type, Scheme >")
Runtime type information.
tmp<surfaceInterpolationScheme<Type> > operator() (const GeometricField< Type, fvPatchField, volMesh > & field) const inline virtual
Implements multivariateSurfaceInterpolationScheme< Type >.
Definition at line 143 of file multivariateScheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateScheme/multivariateScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/multivariateSchemes/multivariateScheme/multivariateScheme.C