OpenFOAM: pairPatchAgglomeration Class Reference
pairPatchAgglomeration Class Reference
Primitive patch pair agglomerate method.
Public Member Functions
pairPatchAgglomeration (const faceList &faces, const pointField &points, const dictionary &controlDict)
Construct given faces, points and control dictionary.
pairPatchAgglomeration (const faceList &faces, const pointField &points, const label mergeLevels, const label maxLevels, const label nFacesInCoarsestLevel, const label nGlobalFacesInCoarsestLevel, const scalar featureAngle=0)
Construct from components.
~pairPatchAgglomeration ()
void agglomerate ()
Agglomerate patch.
label size () const
Return size.
const labelList & restrictTopBottomAddressing () const
Return restriction from top level to bottom level.
const bPatch & patchLevel (const label leveli) const
Return primitivePatch of given level.
const labelField & restrictAddressing (const label leveli) const
Return cell restrict addressing of given level.
template<class Type >
void restrictField (Field< Type > &cf, const Field< Type > &ff, const label fineLevelIndex) const
Restrict (integrate by summation) cell field.
template<class Type >
void prolongField (Field< Type > &ff, const Field< Type > &cf, const label coarseLevelIndex) const
Prolong (interpolate by injection) cell field.
Protected Types
typedef PrimitivePatch< face,
List, const pointField > bPatch
Protected Attributes
label mergeLevels_
Number of levels to merge, 1 = don't merge, 2 = merge pairs etc.
label maxLevels_
Max number of levels.
label nFacesInCoarsestLevel_
Number of faces in coarsest level.
label nGlobalFacesInCoarsestLevel_
Global number of faces in coarsest level.
scalar featureAngle_
Feature angle.
labelList nFaces_
The number of faces in each level.
PtrList< labelField > restrictAddressing_
Cell restriction addressing array.
labelList restrictTopBottomAddressing_
Maps from finest to coarsest.
PtrList< bPatch > patchLevels_
Hierarchy of patch addressing.
EdgeMap< scalar > facePairWeight_
Edge weights.
Detailed Description
Primitive patch pair agglomerate method.
Source files
pairPatchAgglomeration.H
pairPatchAgglomeration.C
Definition at line 50 of file pairPatchAgglomeration.H.
Member Typedef Documentation
typedef PrimitivePatch<face, List, const pointField> bPatch protected
Definition at line 54 of file pairPatchAgglomeration.H.
Constructor & Destructor Documentation
pairPatchAgglomeration (const faceList & faces, const pointField & points, const dictionary & controlDict)
Construct given faces, points and control dictionary.
Definition at line 194 of file pairPatchAgglomeration.C.
pairPatchAgglomeration (const faceList & faces, const pointField & points, const label mergeLevels, const label maxLevels, const label nFacesInCoarsestLevel, const label nGlobalFacesInCoarsestLevel, const scalar featureAngle = 0)
Construct from components.
Definition at line 235 of file pairPatchAgglomeration.C.
~pairPatchAgglomeration ()
Definition at line 269 of file pairPatchAgglomeration.C.
Member Function Documentation
void agglomerate ()
Agglomerate patch.
Definition at line 387 of file pairPatchAgglomeration.C.
label size () const inline
Return size.
Definition at line 225 of file pairPatchAgglomeration.H.
const labelList& restrictTopBottomAddressing () const inline
Return restriction from top level to bottom level.
Definition at line 233 of file pairPatchAgglomeration.H.
const Foam::pairPatchAgglomeration::bPatch & patchLevel (const label leveli) const
Return primitivePatch of given level.
Definition at line 277 of file pairPatchAgglomeration.C.
const labelField& restrictAddressing (const label leveli) const inline
Return cell restrict addressing of given level.
Definition at line 246 of file pairPatchAgglomeration.H.
void restrictField (Field< Type > & cf, const Field< Type > & ff, const label fineLevelIndex) const
Restrict (integrate by summation) cell field.
Definition at line 27 of file pairPatchAgglomerationTemplates.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, i, pairPatchAgglomeration::restrictAddressing_, UList< T >::size(), and UList< Type >::size().
void prolongField (Field< Type > & ff, const Field< Type > & cf, const label coarseLevelIndex) const
Prolong (interpolate by injection) cell field.
Definition at line 55 of file pairPatchAgglomerationTemplates.C.
Member Data Documentation
label mergeLevels_ protected
Number of levels to merge, 1 = don't merge, 2 = merge pairs etc.
Definition at line 61 of file pairPatchAgglomeration.H.
label maxLevels_ protected
Max number of levels.
Definition at line 66 of file pairPatchAgglomeration.H.
label nFacesInCoarsestLevel_ protected
Number of faces in coarsest level.
Definition at line 71 of file pairPatchAgglomeration.H.
label nGlobalFacesInCoarsestLevel_ protected
Global number of faces in coarsest level.
Definition at line 76 of file pairPatchAgglomeration.H.
scalar featureAngle_ protected
Feature angle.
Definition at line 81 of file pairPatchAgglomeration.H.
labelList nFaces_ protected
The number of faces in each level.
Definition at line 86 of file pairPatchAgglomeration.H.
PtrList<labelField> restrictAddressing_ protected
Cell restriction addressing array.
Maps from the finer to coarse level
Definition at line 93 of file pairPatchAgglomeration.H.
Referenced by pairPatchAgglomeration::restrictField().
labelList restrictTopBottomAddressing_ protected
Maps from finest to coarsest.
Definition at line 98 of file pairPatchAgglomeration.H.
PtrList<bPatch> patchLevels_ protected
Hierarchy of patch addressing.
Definition at line 103 of file pairPatchAgglomeration.H.
EdgeMap<scalar> facePairWeight_ protected
Edge weights.
Definition at line 108 of file pairPatchAgglomeration.H.
The documentation for this class was generated from the following files:
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomeration.H
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomeration.C
src/fvAgglomerationMethods/pairPatchAgglomeration/pairPatchAgglomerationTemplates.C