OpenFOAM: dimensioned< Type > Class Template Reference
dimensioned< Type > Class Template Reference
Generic dimensioned Type class.
Public Types
typedef Type value_type
The underlying data type.
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Member Functions
dimensioned ()
A dimensionless Zero, named "0".
dimensioned (const dimensionSet &dims)
A dimensioned Zero, named "0".
dimensioned (const dimensionSet &dims, const zero)
A dimensioned Zero, named "0".
dimensioned (const Type &val)
Implicit construct dimensionless from given value.
dimensioned (const word &name, const dimensioned< Type > &dt)
Copy construct dimensioned Type with a new name.
dimensioned (const word &name, const dimensionSet &dims, const Type &val)
Construct from components (name, dimensions, value).
dimensioned (const primitiveEntry &e)
Construct from primitive entry with given name.
dimensioned (const primitiveEntry &e, const dimensionSet &dims)
Construct from primitive entry with given name and dimensions.
dimensioned (const word &name, const dictionary &dict)
Construct from dictionary lookup with a given name.
dimensioned (const word &name, const dimensionSet &dims, const dictionary &dict)
Construct from dictionary lookup with a given name and dimensions.
dimensioned (const word &name, const dimensionSet &dims, const dictionary &dict, const word &entryName)
Construct from dictionary lookup with a given name and dimensions.
dimensioned (const word &name, const dimensionSet &dims, const Type &val, const dictionary &dict)
Construct from components (name, dimensions, value) with optional dictionary override.
const word & name () const
Return const reference to name.
word & name ()
Return non-const reference to name.
const dimensionSet & dimensions () const
Return const reference to dimensions.
dimensionSet & dimensions ()
Return non-const reference to dimensions.
const Type & value () const
Return const reference to value.
Type & value ()
Return non-const reference to value.
dimensioned< cmptType > component (const direction d) const
Return a component as a dimensioned<cmptType>
void replace (const direction d, const dimensioned< cmptType > &dc)
Return a component with a dimensioned<cmptType>
dimensioned< Type > T () const
Return transpose.
bool read (const dictionary &dict)
Update the value of dimensioned<Type>, lookup in dictionary with the name().
bool readIfPresent (const dictionary &dict)
Update the value of dimensioned<Type> if found in the dictionary, lookup in dictionary with the name().
bool read (const word &entryName, const dictionary &dict)
Update the value of dimensioned<Type>, using an alternative entry name.
bool readIfPresent (const word &entryName, const dictionary &dict)
Update the value of dimensioned<Type> if found in the dictionary, using an alternative entry name.
Istream & read (Istream &is, const bool readName=true)
Read (name, dimensions, value) from stream, using units from system table.
Istream & read (Istream &is, const dictionary &readSet)
Read (name, dimensions, value) from stream, using units from dictionary.
Istream & read (Istream &is, const HashTable< dimensionedScalar > &readSet)
Read (name, dimensions, value) from stream, using units from table.
void writeEntry (const word &keyword, Ostream &os) const
Write as a dictionary entry with keyword.
dimensioned< cmptType > operator[] (const direction d) const
Return a component as a dimensioned<cmptType>
void operator+= (const dimensioned< Type > &dt)
void operator-= (const dimensioned< Type > &dt)
void operator*= (const scalar s)
void operator/= (const scalar s)
dimensioned (Istream &is) FOAM_DEPRECATED(2018-11)
Deprecated(2018-11) Construct from Istream (expects name, dimensions, value)
FOAM_DEPRECATED (2018-11)
Deprecated(2018-11) Construct from Istream with given name (expects dimensions, value)
FOAM_DEPRECATED (2018-11)
Deprecated(2018-11) Construct from Istream with given name and expected dimensions.
Static Public Member Functions
static dimensioned< Type > getOrDefault (const word &name, const dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
Construct dimensioned from dictionary, with default value. FatalIOError if there are excess tokens.
static dimensioned< Type > getOrDefault (const word &name, const dictionary &dict, const Type &deflt=Type(Zero))
Construct dimensionless from dictionary, with default value.
static dimensioned< Type > getOrAddToDict (const word &name, dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
Construct dimensioned from dictionary, with default value.
static dimensioned< Type > getOrAddToDict (const word &name, dictionary &dict, const Type &deflt=Type(Zero))
Construct dimensionless from dictionary, with default value.
static dimensioned< Type > lookupOrDefault (const word &name, const dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
Construct dimensioned from dictionary, with default value. FatalIOError if there are excess tokens.
static dimensioned< Type > lookupOrDefault (const word &name, const dictionary &dict, const Type &deflt=Type(Zero))
Construct dimensionless from dictionary, with default value.
static dimensioned< Type > lookupOrAddToDict (const word &name, dictionary &dict, const dimensionSet &dims=dimless, const Type &deflt=Type(Zero))
Construct dimensioned from dictionary, with default value.
static dimensioned< Type > lookupOrAddToDict (const word &name, dictionary &dict, const Type &deflt=Type(Zero))
Construct dimensionless from dictionary, with default value.
Friends
Istream & operator>> (Istream &is, dimensioned< Type > &dt)
Read from stream. The name and dimensions are optional.
Detailed Description
template<class Type>
class Foam::dimensioned< Type >
Generic dimensioned Type class.
Source files
dimensionedType.H
dimensionedType.C
Definition at line 37 of file dimensionedScalarFwd.H.
Member Typedef Documentation
typedef Type value_type
The underlying data type.
Definition at line 127 of file dimensionedType.H.
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 132 of file dimensionedType.H.
Constructor & Destructor Documentation
dimensioned ()
A dimensionless Zero, named "0".
Definition at line 106 of file dimensionedType.C.
dimensioned (const dimensionSet & dims) explicit
A dimensioned Zero, named "0".
Definition at line 115 of file dimensionedType.C.
dimensioned (const dimensionSet & dims, const zero) explicit
A dimensioned Zero, named "0".
Definition at line 124 of file dimensionedType.C.
dimensioned (const Type & val) inline
Implicit construct dimensionless from given value.
Definition at line 155 of file dimensionedType.H.
dimensioned (const word & name, const dimensioned< Type > & dt)
Copy construct dimensioned Type with a new name.
Definition at line 134 of file dimensionedType.C.
dimensioned (const word & name, const dimensionSet & dims, const Type & val)
Construct from components (name, dimensions, value).
Definition at line 147 of file dimensionedType.C.
dimensioned (const primitiveEntry & e) explicit
Construct from primitive entry with given name.
The entry may contain optional name and dimensions.
* [name] [dims] value
*
If the optional name is found, it is used for renaming. If the optional dimensions are present, they are read and used without further verification. If no dimensions are found, the quantity is dimensionless. Fatal if not primitiveEntry or if number of tokens is incorrect.
Definition at line 161 of file dimensionedType.C.
dimensioned (const primitiveEntry & e, const dimensionSet & dims) explicit
Construct from primitive entry with given name and dimensions.
The entry may contain optional name and dimensions.
* [name] [dims] value
*
If the optional name is found, it is used for renaming. If the optional dimensions are present, they are read and verified against the expected dimensions. Fatal if not primitiveEntry or if number of tokens is incorrect.
Definition at line 180 of file dimensionedType.C.
dimensioned (const word & name, const dictionary & dict)
Construct from dictionary lookup with a given name.
The entry may contain optional name and dimensions.
* [name] [dims] value
*
If the optional name is found, it is used for renaming. If the optional dimensions are present, they are read and used without further verification. If no dimensions are found, the quantity is dimensionless.
Definition at line 200 of file dimensionedType.C.
dimensioned (const word & name, const dimensionSet & dims, const dictionary & dict)
Construct from dictionary lookup with a given name and dimensions.
The entry may contain optional name and dimensions.
* [name] [dims] value
*
If the optional name is found, it is used for renaming. If the optional dimensions are present, they are read and verified against the expected dimensions.
Definition at line 216 of file dimensionedType.C.
dimensioned (const word & name, const dimensionSet & dims, const dictionary & dict, const word & entryName)
Construct from dictionary lookup with a given name and dimensions.
The entry may contain optional name and dimensions.
* [name] [dims] value
*
If the optional name is found, it is used for renaming. If the optional dimensions are present, they are read and verified against the expected dimensions.
Parameters
entryName dictionary lookup name
Definition at line 233 of file dimensionedType.C.
dimensioned (const word & name, const dimensionSet & dims, const Type & val, const dictionary & dict)
Construct from components (name, dimensions, value) with optional dictionary override.
The entry may contain optional name and dimensions.
* [name] [dims] value
*
Definition at line 251 of file dimensionedType.C.
dimensioned (Istream & is) explicit
Deprecated(2018-11) Construct from Istream (expects name, dimensions, value)
Deprecated:
(2018-11) - should generally use construct from dictionary or primitiveEntry instead (additional checks on the input stream).
Definition at line 268 of file dimensionedType.C.
Member Function Documentation
Foam::dimensioned< Type > getOrDefault (const word & name, const dictionary & dict, const dimensionSet & dims = dimless, const Type & deflt = Type(Zero)) static
Construct dimensioned from dictionary, with default value. FatalIOError if there are excess tokens.
Definition at line 311 of file dimensionedType.C.
Foam::dimensioned< Type > getOrDefault (const word & name, const dictionary & dict, const Type & deflt = Type(Zero)) static
Construct dimensionless from dictionary, with default value.
FatalIOError if it is found and there are excess tokens.
Definition at line 325 of file dimensionedType.C.
Foam::dimensioned< Type > getOrAddToDict (const word & name, dictionary & dict, const dimensionSet & dims = dimless, const Type & deflt = Type(Zero)) static
Construct dimensioned from dictionary, with default value.
If the value is not found, it is added into the dictionary. FatalIOError if it is found and there are excess tokens.
Definition at line 337 of file dimensionedType.C.
References dict, Foam::dimless, and Foam::name().
Foam::dimensioned< Type > getOrAddToDict (const word & name, dictionary & dict, const Type & deflt = Type(Zero)) static
Construct dimensionless from dictionary, with default value.
If the value is not found, it is added into the dictionary. FatalIOError if it is found and there are excess tokens.
Definition at line 356 of file dimensionedType.C.
const Foam::word & name () const
Return const reference to name.
Definition at line 369 of file dimensionedType.C.
Referenced by Foam::atan2(), Foam::fac::ddt(), Foam::fvc::ddt(), steadyStateFaDdtScheme< Type >::facDdt(), EulerFaDdtScheme< Type >::facDdt(), backwardFaDdtScheme< Type >::facDdt(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), Foam::fvc::laplacian(), Foam::stabilise(), and dimensioned< Type >::T().
Foam::word & name ()
Return non-const reference to name.
Definition at line 376 of file dimensionedType.C.
const Foam::dimensionSet & dimensions () const
Return const reference to dimensions.
Definition at line 383 of file dimensionedType.C.
Referenced by steadyStateFaDdtScheme< Type >::facDdt(), EulerFaDdtScheme< Type >::facDdt(), backwardFaDdtScheme< Type >::facDdt(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), Foam::makeDimensionedMinMax(), dimensioned< Type >::read(), Foam::stabilise(), and dimensioned< Type >::T().
Foam::dimensionSet & dimensions ()
Return non-const reference to dimensions.
Definition at line 390 of file dimensionedType.C.
const Type & value () const
Return const reference to value.
Definition at line 397 of file dimensionedType.C.
Referenced by powerLawUniformBinary::addToBinaryBreakupRate(), vtmWriter::beginBlock(), surfaceWriter::beginTime(), Foam::bound(), logFiles::createFiles(), EulerFaDdtScheme< Type >::facDdt(), backwardFaDdtScheme< Type >::facDdt(), EulerD2dt2Scheme< Type >::fvcD2dt2(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), thermoSingleLayer::hs(), Foam::invTransform(), Foam::makeDimensionedMinMax(), Time::operator+=(), Foam::operator>(), magnet::orientation(), pressureControl::pressureControl(), Time::setDeltaT(), Time::setEndTime(), Time::setTime(), Foam::stabilise(), Foam::transform(), and Sine< Type >::value().
Type & value ()
Return non-const reference to value.
Definition at line 404 of file dimensionedType.C.
Foam::dimensioned< typename Foam::dimensioned< Type >::cmptType > component (const direction d) const
Return a component as a dimensioned<cmptType>
Definition at line 413 of file dimensionedType.C.
void replace (const direction d, const dimensioned< cmptType > & dc)
Return a component with a dimensioned<cmptType>
Definition at line 428 of file dimensionedType.C.
dimensionedTensor T () const
Return transpose.
Definition at line 31 of file dimensionedSphericalTensor.C.
References dimensioned< Type >::dimensions(), and dimensioned< Type >::name().
bool read (const dictionary & dict)
Update the value of dimensioned<Type>, lookup in dictionary with the name().
Definition at line 439 of file dimensionedType.C.
References dimensioned< Type >::dimensions().
Referenced by NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid().
bool readIfPresent (const dictionary & dict)
Update the value of dimensioned<Type> if found in the dictionary, lookup in dictionary with the name().
Definition at line 446 of file dimensionedType.C.
References Foam::read().
bool read (const word & entryName, const dictionary & dict)
Update the value of dimensioned<Type>, using an alternative entry name.
Definition at line 454 of file dimensionedType.C.
bool readIfPresent (const word & entryName, const dictionary & dict)
Update the value of dimensioned<Type> if found in the dictionary, using an alternative entry name.
Definition at line 466 of file dimensionedType.C.
Foam::Istream & read (Istream & is, const bool readName = true)
Read (name, dimensions, value) from stream, using units from system table.
Optionally skip reading the name
Definition at line 477 of file dimensionedType.C.
Foam::Istream & read (Istream & is, const dictionary & readSet)
Read (name, dimensions, value) from stream, using units from dictionary.
Definition at line 500 of file dimensionedType.C.
Foam::Istream & read (Istream & is, const HashTable< dimensionedScalar > & readSet)
Read (name, dimensions, value) from stream, using units from table.
Definition at line 520 of file dimensionedType.C.
void writeEntry (const word & keyword, Ostream & os) const
Write as a dictionary entry with keyword.
The name is not written when it is identical to keyword. The dimensions are always written.
Definition at line 543 of file dimensionedType.C.
Foam::dimensioned< typename Foam::dimensioned< Type >::cmptType > operator[] (const direction d) const
Return a component as a dimensioned<cmptType>
Definition at line 572 of file dimensionedType.C.
void operator+= (const dimensioned< Type > & dt)
Definition at line 582 of file dimensionedType.C.
References Foam::component().
void operator-= (const dimensioned< Type > & dt)
Definition at line 593 of file dimensionedType.C.
void operator*= (const scalar s)
Definition at line 604 of file dimensionedType.C.
void operator/= (const scalar s)
Definition at line 614 of file dimensionedType.C.
References s.
FOAM_DEPRECATED (2018- 11)
Deprecated(2018-11) Construct from Istream with given name (expects dimensions, value)
Deprecated:
(2018-11) - should generally use construct from dictionary or primitiveEntry instead (additional checks on the input stream).
FOAM_DEPRECATED (2018- 11)
Deprecated(2018-11) Construct from Istream with given name and expected dimensions.
Expects value, but supports optional name and dimensions. If the optional dimensions are present, they are read and verified against the expected dimensions.
Deprecated:
(2018-11) - should generally use construct from dictionary or primitiveEntry instead (additional checks on the input stream).
static dimensioned<Type> lookupOrDefault (const word & name, const dictionary & dict, const dimensionSet & dims = dimless, const Type & deflt = Type(Zero)) inline static
Construct dimensioned from dictionary, with default value. FatalIOError if there are excess tokens.
Definition at line 504 of file dimensionedType.H.
Referenced by lumpedPointMovement::forcesAndMoments().
static dimensioned<Type> lookupOrDefault (const word & name, const dictionary & dict, const Type & deflt = Type(Zero)) inline static
Construct dimensionless from dictionary, with default value.
FatalIOError if it is found and there are excess tokens.
Definition at line 520 of file dimensionedType.H.
static dimensioned<Type> lookupOrAddToDict (const word & name, dictionary & dict, const dimensionSet & dims = dimless, const Type & deflt = Type(Zero)) inline static
Construct dimensioned from dictionary, with default value.
If the value is not found, it is added into the dictionary. FatalIOError if it is found and there are excess tokens.
Definition at line 536 of file dimensionedType.H.
static dimensioned<Type> lookupOrAddToDict (const word & name, dictionary & dict, const Type & deflt = Type(Zero)) inline static
Construct dimensionless from dictionary, with default value.
If the value is not found, it is added into the dictionary. FatalIOError if it is found and there are excess tokens.
Definition at line 553 of file dimensionedType.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, dimensioned< Type > & dt) friend
Read from stream. The name and dimensions are optional.
If the optional dimensions are present, they are used without further verification.
The documentation for this class was generated from the following files:
src/OpenFOAM/dimensionedTypes/dimensionedScalar/dimensionedScalarFwd.H
src/OpenFOAM/dimensionedTypes/dimensionedType/dimensionedType.H
src/OpenFOAM/dimensionedTypes/dimensionedSphericalTensor/dimensionedSphericalTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedSymmTensor/dimensionedSymmTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedTensor/dimensionedTensor.C
src/OpenFOAM/dimensionedTypes/dimensionedType/dimensionedType.C