OpenFOAM: BlendedInterfacialModel< ModelType > Class Template Reference
BlendedInterfacialModel< ModelType > Class Template Reference
Public Member Functions
TypeName ("BlendedInterfacialModel")
Runtime type information.
BlendedInterfacialModel (const phaseModel &phase1, const phaseModel &phase2, const blendingMethod &blending, autoPtr< ModelType > model, autoPtr< ModelType > model1In2, autoPtr< ModelType > model2In1, const bool correctFixedFluxBCs=true)
Construct from two phases, blending method and three models.
BlendedInterfacialModel (const phasePair::dictTable &modelTable, const blendingMethod &blending, const phasePair &pair, const orderedPhasePair &pair1In2, const orderedPhasePair &pair2In1, const bool correctFixedFluxBCs=true)
Construct from the model table, dictionary and pairs.
~BlendedInterfacialModel ()
Destructor.
bool hasModel (const phaseModel &phase) const
Return true if a model is specified for the supplied phase.
const ModelType & model (const phaseModel &phase) const
Return the model for the supplied phase.
scalar sign (const phaseModel &phase) const
Return the sign of the explicit value for the supplied phase.
tmp< volScalarField > K () const
Return the blended force coefficient.
tmp< volScalarField > K (const scalar residualAlpha) const
Return the blended force coefficient with a specified residual alpha.
tmp< surfaceScalarField > Kf () const
Return the face blended force coefficient.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > F () const
Return the blended force.
tmp< surfaceScalarField > Ff () const
Return the face blended force.
tmp< volScalarField > D () const
Return the blended diffusivity.
tmp< volScalarField > dmdt () const
Return the blended mass transfer rate.
bool writeData (Ostream &os) const
Dummy write for regIOobject.
BlendedInterfacialModel (const phasePair::dictTable &modelTable, const blendingMethod &blending, const phasePair &pair, const orderedPhasePair &pair1In2, const orderedPhasePair &pair2In1, const bool correctFixedFluxBCs=true)
Construct from the model table, dictionary and pairs.
~BlendedInterfacialModel ()
Destructor.
bool hasModel (const phaseModel &phase) const
Return true if a model is specified for the supplied phase.
const modelType & phaseModel (const phaseModel &phase) const
Return the model for the supplied phase.
tmp< volScalarField > K () const
Return the blended force coefficient.
tmp< surfaceScalarField > Kf () const
Return the face blended force coefficient.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > F () const
Return the blended force.
tmp< surfaceScalarField > Ff () const
Return the face blended force.
tmp< volScalarField > D () const
Return the blended diffusivity.
template<class Type , template< class > class PatchField, class GeoMesh , class... Args>
Foam::tmp
< Foam::GeometricField< Type,
PatchField, GeoMesh > > evaluate (tmp< GeometricField< Type, PatchField, GeoMesh >>(ModelType::*method)(Args...) const, const word &name, const dimensionSet &dims, const bool subtract, Args...args) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > F () const
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class ModelType>
class Foam::BlendedInterfacialModel< ModelType >
Source files
BlendedInterfacialModel.H
BlendedInterfacialModel.C
Source files
BlendedInterfacialModel.H
BlendedInterfacialModel.C
Definition at line 67 of file BlendedInterfacialModel.H.
Constructor & Destructor Documentation
BlendedInterfacialModel (const phaseModel & phase1, const phaseModel & phase2, const blendingMethod & blending, autoPtr< ModelType > model, autoPtr< ModelType > model1In2, autoPtr< ModelType > model2In1, const bool correctFixedFluxBCs = true)
Construct from two phases, blending method and three models.
Definition at line 187 of file BlendedInterfacialModel.C.
BlendedInterfacialModel (const phasePair::dictTable & modelTable, const blendingMethod & blending, const phasePair & pair, const orderedPhasePair & pair1In2, const orderedPhasePair & pair2In1, const bool correctFixedFluxBCs = true)
Construct from the model table, dictionary and pairs.
Definition at line 218 of file BlendedInterfacialModel.C.
~BlendedInterfacialModel ()
Destructor.
Definition at line 282 of file BlendedInterfacialModel.C.
BlendedInterfacialModel (const phasePair::dictTable & modelTable, const blendingMethod & blending, const phasePair & pair, const orderedPhasePair & pair1In2, const orderedPhasePair & pair2In1, const bool correctFixedFluxBCs = true)
Construct from the model table, dictionary and pairs.
~BlendedInterfacialModel ()
Destructor.
Member Function Documentation
TypeName ("BlendedInterfacialModel< ModelType >")
Runtime type information.
bool hasModel (const phaseModel & phase) const
Return true if a model is specified for the supplied phase.
const ModelType & model (const phaseModel & phase) const
Return the model for the supplied phase.
Definition at line 303 of file BlendedInterfacialModel.C.
scalar sign (const phaseModel & phase) const
Return the sign of the explicit value for the supplied phase.
Foam::tmp< Foam::volScalarField > K () const
Return the blended force coefficient.
Definition at line 313 of file BlendedInterfacialModel.C.
Foam::tmp< Foam::volScalarField > K (const scalar residualAlpha) const
Return the blended force coefficient with a specified residual alpha.
Definition at line 323 of file BlendedInterfacialModel.C.
Foam::tmp< Foam::surfaceScalarField > Kf () const
Return the face blended force coefficient.
Definition at line 333 of file BlendedInterfacialModel.C.
tmp<GeometricField<Type, fvPatchField, volMesh> > F () const
Return the blended force.
Foam::tmp< Foam::surfaceScalarField > Ff () const
Return the face blended force.
Definition at line 350 of file BlendedInterfacialModel.C.
References Foam::stringOps::evaluate(), and F().
Foam::tmp< Foam::volScalarField > D () const
Return the blended diffusivity.
Definition at line 358 of file BlendedInterfacialModel.C.
References Foam::dimArea, Foam::stringOps::evaluate(), and Ff().
Foam::tmp< Foam::volScalarField > dmdt () const
Return the blended mass transfer rate.
Definition at line 366 of file BlendedInterfacialModel.C.
References D, and Foam::stringOps::evaluate().
bool writeData (Ostream & os) const virtual
Dummy write for regIOobject.
Implements regIOobject.
Definition at line 373 of file BlendedInterfacialModel.C.
References Foam::stringOps::evaluate().
bool hasModel (const phaseModel & phase) const
Return true if a model is specified for the supplied phase.
const modelType& phaseModel (const phaseModel & phase) const
Return the model for the supplied phase.
tmp<volScalarField> K () const
Return the blended force coefficient.
tmp<surfaceScalarField> Kf () const
Return the face blended force coefficient.
tmp<GeometricField<Type, fvPatchField, volMesh> > F () const
Return the blended force.
tmp<surfaceScalarField> Ff () const
Return the face blended force.
tmp<volScalarField> D () const
Return the blended diffusivity.
Foam::tmp<Foam::GeometricField<Type, PatchField, GeoMesh> > evaluate (tmp< GeometricField< Type, PatchField, GeoMesh >>(ModelType::*)(Args...) const method, const word & name, const dimensionSet & dims, const bool subtract, Args... args) const
Definition at line 88 of file BlendedInterfacialModel.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, x, and Foam::Zero.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > F () const
Definition at line 342 of file BlendedInterfacialModel.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/BlendedInterfacialModel/BlendedInterfacialModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/twoPhaseSystem/BlendedInterfacialModel/BlendedInterfacialModel.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/BlendedInterfacialModel/BlendedInterfacialModel.C