OpenFOAM: SVD Class Reference
SVD Class Reference
Singular value decomposition of a rectangular matrix.
Public Member Functions
SVD (const scalarRectangularMatrix &A, const scalar minCondition=0)
Construct from a rectangular Matrix.
const scalarRectangularMatrix & U () const
Return U.
const scalarRectangularMatrix & V () const
Return the square matrix V.
const scalarDiagonalMatrix & S () const
Return the singular values.
bool converged () const
Return the minimum non-zero singular value.
label nZeros () const
Return the number of zero singular values.
scalar minNonZeroS () const
Return the minimum non-zero singular value.
scalarRectangularMatrix VSinvUt () const
Return the matrix product V S^(-1) U^T (the pseudo inverse)
Detailed Description
Singular value decomposition of a rectangular matrix.
Source files
SVD.H
SVDI.H
SVD.C
Definition at line 49 of file SVD.H.
Constructor & Destructor Documentation
SVD (const scalarRectangularMatrix & A, const scalar minCondition = 0)
Construct from a rectangular Matrix.
Definition at line 28 of file SVD.C.
References c(), f(), Foam::findMax(), forAll, g, h, i, j, k, Matrix< Form, Type >::m(), Foam::mag(), Foam::max(), Foam::min(), Matrix< Form, Type >::n, s, Foam::sqrt(), Foam::sqrtSumSqr(), x, and y.
Member Function Documentation
const Foam::scalarRectangularMatrix & U () const inline
Return U.
Definition at line 33 of file SVDI.H.
const Foam::scalarRectangularMatrix & V () const inline
Return the square matrix V.
Definition at line 39 of file SVDI.H.
const Foam::scalarDiagonalMatrix & S () const inline
Return the singular values.
Definition at line 45 of file SVDI.H.
bool converged () const inline
Return the minimum non-zero singular value.
Definition at line 51 of file SVDI.H.
Foam::label nZeros () const inline
Return the number of zero singular values.
Definition at line 57 of file SVDI.H.
Foam::scalar minNonZeroS () const inline
Return the minimum non-zero singular value.
Definition at line 63 of file SVDI.H.
Foam::scalarRectangularMatrix VSinvUt () const
Return the matrix product V S^(-1) U^T (the pseudo inverse)
Definition at line 380 of file SVD.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.H
src/OpenFOAM/matrices/scalarMatrices/SVD/SVD.C
src/OpenFOAM/matrices/scalarMatrices/SVD/SVDI.H