OpenFOAM: tetIndices Class Reference
tetIndices Class Reference
Storage and named access for the indices of a tet which is part of the decomposition of a cell.
Public Member Functions
tetIndices ()
Construct null.
tetIndices (label celli, label facei, label tetPtI)
Construct from components.
~tetIndices ()
Destructor.
label cell () const
Return the cell.
label & cell ()
Return non-const access to the cell.
label face () const
Return the face.
label & face ()
Return non-const access to the face.
label tetPt () const
Return the characterising tetPtI.
label & tetPt ()
Return non-const access to the characterising tetPtI.
triFace faceTriIs (const polyMesh &mesh, const bool warn=true) const
Return the indices corresponding to the tri on the face for.
triFace triIs (const polyMesh &mesh, const bool warn=true) const
Return the local indices corresponding to the tri on the face.
tetPointRef tet (const polyMesh &mesh) const
Return the geometry corresponding to this tet.
triPointRef faceTri (const polyMesh &mesh) const
Return the geometry corresponding to the tri on the face for.
triPointRef oldFaceTri (const polyMesh &mesh) const
Return the geometry corresponding to the tri on the face for.
bool operator== (const tetIndices &) const
bool operator!= (const tetIndices &) const
Friends
Istream & operator>> (Istream &, tetIndices &)
Ostream & operator<< (Ostream &, const tetIndices &)
Detailed Description
Storage and named access for the indices of a tet which is part of the decomposition of a cell.
Tets are designated by
cell (of course)
face on cell
three points on face (faceBasePt, facePtA, facePtB) When constructing from a mesh and index in the face (tetPtI):
faceBasePt is the mesh.tetBasePtIs() base point
facePtA is tetPtI away from faceBasePt
facePtB is next one after/before facePtA e.g.:
+—+ |2 /| | / | |/ 1| <- tetPt (so 1 for first triangle, 2 for second) +—+ ^ faceBasePt
Source files
tetIndices.H
tetIndicesI.H
tetIndices.C
Definition at line 79 of file tetIndices.H.
Constructor & Destructor Documentation
tetIndices ()
Construct null.
Definition at line 32 of file tetIndices.C.
tetIndices (label celli, label facei, label tetPtI)
Construct from components.
Definition at line 41 of file tetIndices.C.
~tetIndices ()
Destructor.
Definition at line 55 of file tetIndices.C.
Member Function Documentation
Foam::label cell () const inline
Return the cell.
Definition at line 23 of file tetIndicesI.H.
Referenced by interpolationCell< scalar >::interpolate(), interpolationCellPatchConstrained< Type >::interpolate(), Basic< Type >::interpolate(), and Basic< Type >::primitiveField().
Foam::label & cell () inline
Return non-const access to the cell.
Definition at line 29 of file tetIndicesI.H.
Foam::label face () const inline
Return the face.
Definition at line 35 of file tetIndicesI.H.
Foam::label & face () inline
Return non-const access to the face.
Definition at line 41 of file tetIndicesI.H.
Foam::label tetPt () const inline
Return the characterising tetPtI.
Definition at line 47 of file tetIndicesI.H.
Foam::label & tetPt () inline
Return non-const access to the characterising tetPtI.
Definition at line 53 of file tetIndicesI.H.
Foam::triFace faceTriIs (const polyMesh & mesh, const bool warn = true) const inline
Return the indices corresponding to the tri on the face for.
this tet. The normal of the tri points out of the cell
Definition at line 60 of file tetIndicesI.H.
Referenced by Moment< Type >::Moment().
Foam::triFace triIs (const polyMesh & mesh, const bool warn = true) const inline
Return the local indices corresponding to the tri on the face.
for this tet. The normal of the tri points out of the cell
Definition at line 104 of file tetIndicesI.H.
Foam::tetPointRef tet (const polyMesh & mesh) const inline
Return the geometry corresponding to this tet.
Definition at line 147 of file tetIndicesI.H.
Referenced by Moment< Type >::Moment(), and interpolation< Foam::Vector >::psi().
Foam::triPointRef faceTri (const polyMesh & mesh) const inline
Return the geometry corresponding to the tri on the face for.
this tet. The normal of the tri points out of the cell
Definition at line 162 of file tetIndicesI.H.
Foam::triPointRef oldFaceTri (const polyMesh & mesh) const inline
Return the geometry corresponding to the tri on the face for.
this tet using the old positions
Definition at line 177 of file tetIndicesI.H.
bool operator== (const tetIndices & rhs) const inline
Definition at line 195 of file tetIndicesI.H.
bool operator!= (const tetIndices & rhs) const inline
Definition at line 204 of file tetIndicesI.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & , tetIndices &) friend
Ostream& operator<< (Ostream & , const tetIndices &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndices.H
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndices.C
src/OpenFOAM/meshes/polyMesh/polyMeshTetDecomposition/tetIndicesI.H