OpenFOAM: nutUSpaldingWallFunctionFvPatchScalarField Class Reference
nutUSpaldingWallFunctionFvPatchScalarField Class Reference
Wall functions
This boundary condition provides a wall constraint on the turbulent kinematic viscosity, i.e. nut, when using wall functions for rough walls, based on velocity, U, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
Public Member Functions
TypeName ("nutUSpaldingWallFunction")
Runtime type information.
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given nutUSpaldingWallFunctionFvPatchScalarField onto a new patch.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual ~nutUSpaldingWallFunctionFvPatchScalarField ()
Destructor.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given nutWallFunctionFvPatchScalarField onto a new patch.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar Cmu () const
Return Cmu.
scalar kappa () const
Return kappa.
scalar E () const
Return E.
scalar yPlusLam () const
Return the y+ at the edge of the viscous sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Uncomment in case of intrumentation.
virtual tmp< scalarField > calcUTau (const scalarField &magGradU) const
Calculate the friction velocity.
virtual tmp< scalarField > calcUTau (const scalarField &magGradU, const label maxIter, scalarField &err) const
Calculate the friction velocity and number of iterations for convergence.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
Helper to return the velocity field either from the turbulence model (default) or the mesh database.
virtual void checkType ()
Check the type of the patch.
Protected Attributes
const label maxIter_
Max iterations in calcNut.
const scalar tolerance_
Convergence tolerance.
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
Name of velocity field.
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Estimated y+ value at the edge of the viscous sublayer.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const
nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Return the nut patchField for the given wall patch.
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the y+ at the edge of the viscous sublayer.
Detailed Description
This boundary condition provides a wall constraint on the turbulent kinematic viscosity, i.e. nut, when using wall functions for rough walls, based on velocity, U, using Spalding's law to give a continuous nut profile to the wall (y+ = 0)
where
= non-dimensional position
= non-dimensional velocity
= Von Karman constant
Usage
Property Description Required Default value
Cmu Model coefficient no 0.09
kappa Von Karman constant no 0.41
E Model coefficient no 9.8
maxIter Number of Newton-Raphson iterations no 10
tolerance Convergence tolerance no 0.0001
Example of the boundary condition specification:
    <patchName>
    {
        // Mandatory entries
        type            nutUSpaldingWallFunction;
        // Optional entries
    }
See Also
Foam::nutWallFunctionFvPatchScalarField
Note
Suffers from non-exact restart since correctNut() (called through turbulence->validate) returns a slightly different value every time it is called. This is since the seed for the Newton-Raphson iteration uses the current value of *this (= nut).
This can be avoided by overriding the tolerance. This also switches on a pre-detection whether the current nut already satisfies the turbulence conditions and if so does not change it at all. This means that the nut only changes if it 'has really changed'. This probably should be used with a tight tolerance, e.g.
maxIter 100; tolerance 1e-7;
to make sure to kick every iteration.
Source files
nutUSpaldingWallFunctionFvPatchScalarField.H
nutUSpaldingWallFunctionFvPatchScalarField.C
Definition at line 148 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 202 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
nutUSpaldingWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 238 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given nutUSpaldingWallFunctionFvPatchScalarField onto a new patch.
Definition at line 219 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 256 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
nutUSpaldingWallFunctionFvPatchScalarField (const nutUSpaldingWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 272 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
~nutUSpaldingWallFunctionFvPatchScalarField () virtual
Destructor.
Definition at line 290 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
Member Function Documentation
Foam::tmp< Foam::scalarField > calcNut () const protected virtual
Uncomment in case of intrumentation.
mutable uint64_t invocations_; mutable uint64_t nontrivial_; mutable uint64_t nonconvergence_; mutable uint64_t iterations_;
Calculate the turbulence viscosity
Implements nutWallFunctionFvPatchScalarField.
Definition at line 32 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUSpaldingWallFunctionFvPatchScalarField::calcUTau(), forAll, Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), Foam::max(), turbulenceModel::nu(), nutWallFunctionFvPatchScalarField::nutw(), Foam::foamVersion::patch, turbulenceModel::propertiesName, tmp< T >::ref(), Foam::sqr(), nutUSpaldingWallFunctionFvPatchScalarField::tolerance_, and nutWallFunctionFvPatchScalarField::U().
Foam::tmp< Foam::scalarField > calcUTau (const scalarField & magGradU) const protected virtual
Calculate the friction velocity.
Definition at line 87 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
Referenced by nutUSpaldingWallFunctionFvPatchScalarField::calcNut().
Foam::tmp< Foam::scalarField > calcUTau (const scalarField & magGradU, const label maxIter, scalarField & err) const protected virtual
Calculate the friction velocity and number of iterations for convergence.
Definition at line 98 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
void writeLocalEntries (Ostream & os) const protected virtual
Write local wall function variables.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 187 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
TypeName ("nutUSpaldingWallFunction")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 258 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 279 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
Foam::tmp< Foam::scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 311 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 333 of file nutUSpaldingWallFunctionFvPatchScalarField.C.
Member Data Documentation
const label maxIter_ protected
Max iterations in calcNut.
Definition at line 159 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
const scalar tolerance_ protected
Convergence tolerance.
Definition at line 164 of file nutUSpaldingWallFunctionFvPatchScalarField.H.
Referenced by nutUSpaldingWallFunctionFvPatchScalarField::calcNut().
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUSpaldingWallFunction/nutUSpaldingWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUSpaldingWallFunction/nutUSpaldingWallFunctionFvPatchScalarField.C