OpenFOAM: lagrangianReconstructor Class Reference
lagrangianReconstructor Class Reference
Reconstructor for lagrangian positions and fields.
Public Member Functions
lagrangianReconstructor (const fvMesh &mesh, const PtrList< fvMesh > &procMeshes, const PtrList< labelIOList > &faceProcAddressing, const PtrList< labelIOList > &cellProcAddressing)
Construct from components.
label reconstructPositions (const word &cloudName) const
Reconstruct positions for given cloud.
template<class Type >
tmp< IOField< Type > > reconstructField (const word &cloudName, const word &fieldName)
Reconstruct a single field for given cloud.
template<class Type >
tmp< CompactIOField< Field
< Type >, Type > > reconstructFieldField (const word &cloudName, const word &fieldName)
Reconstruct a single field-field for given cloud.
template<class Type >
label reconstructFields (const word &cloudName, const IOobjectList &objects, const UList< word > &fieldNames)
Reconstruct multiple fields for given cloud.
template<class Type >
label reconstructFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields=wordRes())
Reconstruct multiple fields for given cloud.
template<class Type >
label reconstructFieldFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields=wordRes())
Reconstruct multiple field-field for given cloud.
template<class Type >
Foam::tmp< Foam::IOField< Type > > reconstructField (const word &cloudName, const word &fieldName)
template<class Type >
Foam::tmp
< Foam::CompactIOField
< Foam::Field< Type >, Type > > reconstructFieldField (const word &cloudName, const word &fieldName)
template<class Type >
Foam::label reconstructFields (const word &cloudName, const IOobjectList &objects, const UList< word > &fieldNames)
template<class Type >
Foam::label reconstructFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructFieldFields (const word &cloudName, const IOobjectList &objects, const wordRes &selectedFields)
Detailed Description
Reconstructor for lagrangian positions and fields.
Source files
lagrangianReconstructor.H
lagrangianReconstructor.C
lagrangianReconstructorFields.C
Definition at line 52 of file lagrangianReconstructor.H.
Constructor & Destructor Documentation
lagrangianReconstructor (const fvMesh & mesh, const PtrList< fvMesh > & procMeshes, const PtrList< labelIOList > & faceProcAddressing, const PtrList< labelIOList > & cellProcAddressing)
Construct from components.
Definition at line 29 of file lagrangianReconstructor.C.
Member Function Documentation
Foam::label reconstructPositions (const word & cloudName) const
Reconstruct positions for given cloud.
Definition at line 46 of file lagrangianReconstructor.C.
tmp<IOField<Type> > reconstructField (const word & cloudName, const word & fieldName)
Reconstruct a single field for given cloud.
tmp<CompactIOField<Field<Type>, Type> > reconstructFieldField (const word & cloudName, const word & fieldName)
Reconstruct a single field-field for given cloud.
label reconstructFields (const word & cloudName, const IOobjectList & objects, const UList< word > & fieldNames)
Reconstruct multiple fields for given cloud.
label reconstructFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Reconstruct multiple fields for given cloud.
label reconstructFieldFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Reconstruct multiple field-field for given cloud.
Foam::tmp<Foam::IOField<Type> > reconstructField (const word & cloudName, const word & fieldName)
Definition at line 31 of file lagrangianReconstructorFields.C.
References cloudName(), field(), forAll, j, IOobject::MUST_READ, Foam::New(), IOobject::NO_READ, IOobject::NO_WRITE, cloud::prefix, UList< Type >::size(), fvMesh::time(), and Time::timeName().
Foam::tmp<Foam::CompactIOField<Foam::Field<Type>, Type> > reconstructFieldField (const word & cloudName, const word & fieldName)
Definition at line 86 of file lagrangianReconstructorFields.C.
Foam::label reconstructFields (const word & cloudName, const IOobjectList & objects, const UList< word > & fieldNames)
Definition at line 147 of file lagrangianReconstructorFields.C.
Foam::label reconstructFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 179 of file lagrangianReconstructorFields.C.
Foam::label reconstructFieldFields (const word & cloudName, const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 200 of file lagrangianReconstructorFields.C.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/lagrangianReconstructor.H
src/parallel/reconstruct/reconstruct/lagrangianReconstructor.C
src/parallel/reconstruct/reconstruct/lagrangianReconstructorFields.C