OpenFOAM: ijkAddressing Class Reference
ijkAddressing Class Reference
A simple i-j-k (row-major order) to linear addressing.
Public Member Functions
ijkAddressing ()
Construct zero-size addressing.
ijkAddressing (const labelVector &ijk)
Construct with addressing.
ijkAddressing (const label ni, const label nj, const label nk)
Construct with addressing components.
bool empty () const
Addressing is considered empty if any component is zero.
const labelVector & sizes () const
The (i,j,k) addressing dimensions.
labelVector & sizes ()
Return the (i,j,k) dimensions for modification.
label size () const
Return the total i*j*k size.
const label & size (const vector::components cmpt) const
The addressing dimension in the given direction.
void clear ()
Reset to (0,0,0) sizing.
void reset (const label ni, const label nj, const label nk)
Change the sizing parameters.
void reset (const labelVector &newSizes)
Change the sizing parameters.
label index (const label i, const label j, const label k) const
Linear addressing index (offset) for an (i,j,k) position.
label index (const labelVector &ijk) const
Linear addressing index (offset) for an (i,j,k) position.
labelVector index (const label idx) const
The (i,j,k) indexing from linear addressing.
void checkIndex (const label i, const label j, const label k, const bool allowExtra=false) const
Check indices are within ni,nj,nk range.
void checkIndex (const labelVector &ijk, const bool allowExtra=false) const
Check indices are within ni,nj,nk range.
void checkSizes () const
Check that all components of sizes() are non-negative.
void checkSizes (const labelVector &other) const
Check that all components of sizes() match.
void checkSizes (const label nTotal) const
Check that the total size matches.
Detailed Description
A simple i-j-k (row-major order) to linear addressing.
Source files
ijkAddressing.H
ijkAddressingI.H
Definition at line 47 of file ijkAddressing.H.
Constructor & Destructor Documentation
ijkAddressing () inline
Construct zero-size addressing.
Definition at line 23 of file ijkAddressingI.H.
ijkAddressing (const labelVector & ijk) inline explicit
Construct with addressing.
Definition at line 29 of file ijkAddressingI.H.
ijkAddressing (const label ni, const label nj, const label nk) inline
Construct with addressing components.
Definition at line 40 of file ijkAddressingI.H.
Member Function Documentation
bool empty () const inline
Addressing is considered empty if any component is zero.
Definition at line 56 of file ijkAddressingI.H.
const Foam::labelVector & sizes () const inline
The (i,j,k) addressing dimensions.
Definition at line 62 of file ijkAddressingI.H.
Referenced by blockDescriptor::grading().
Foam::labelVector & sizes () inline
Return the (i,j,k) dimensions for modification.
Definition at line 68 of file ijkAddressingI.H.
Foam::label size () const inline
Return the total i*j*k size.
Definition at line 74 of file ijkAddressingI.H.
Referenced by ijkMesh::nFaces().
const Foam::label & size (const vector::components cmpt) const inline
The addressing dimension in the given direction.
Definition at line 82 of file ijkAddressingI.H.
void clear () inline
Reset to (0,0,0) sizing.
Definition at line 90 of file ijkAddressingI.H.
void reset (const label ni, const label nj, const label nk) inline
Change the sizing parameters.
Definition at line 97 of file ijkAddressingI.H.
References Foam::Zero.
void reset (const labelVector & newSizes) inline
Change the sizing parameters.
Definition at line 113 of file ijkAddressingI.H.
Foam::label index (const label i, const label j, const label k) const inline
Linear addressing index (offset) for an (i,j,k) position.
Definition at line 124 of file ijkAddressingI.H.
Referenced by ijkMesh::cellLabel(), and ijkMesh::pointLabel().
Foam::label index (const labelVector & ijk) const inline
Linear addressing index (offset) for an (i,j,k) position.
Definition at line 138 of file ijkAddressingI.H.
Foam::labelVector index (const label idx) const inline
The (i,j,k) indexing from linear addressing.
Definition at line 148 of file ijkAddressingI.H.
void checkIndex (const label i, const label j, const label k, const bool allowExtra = false) const inline
Check indices are within ni,nj,nk range.
Optionally allow an extra index for point addressing
Definition at line 162 of file ijkAddressingI.H.
void checkIndex (const labelVector & ijk, const bool allowExtra = false) const inline
Check indices are within ni,nj,nk range.
Optionally allow an extra index for point addressing
Definition at line 196 of file ijkAddressingI.H.
void checkSizes () const inline
Check that all components of sizes() are non-negative.
Definition at line 205 of file ijkAddressingI.H.
void checkSizes (const labelVector & other) const inline
Check that all components of sizes() match.
Definition at line 228 of file ijkAddressingI.H.
void checkSizes (const label nTotal) const inline
Check that the total size matches.
Definition at line 240 of file ijkAddressingI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/ijkMesh/ijkAddressing.H
src/OpenFOAM/meshes/ijkMesh/ijkAddressingI.H