OpenFOAM: faMatrix< Type > Class Template Reference
faMatrix< Type > Class Template Reference
A special matrix type and solver, designed for finite area solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Classes
class faSolver
Solver class returned by the solver function.
Public Types
typedef GeometricField< Type,
faePatchField, edgeMesh > * edgeTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Public Member Functions
ClassName ("faMatrix")
faMatrix (const GeometricField< Type, faPatchField, areaMesh > &, const dimensionSet &)
Construct given a field to solve for.
faMatrix (const faMatrix< Type > &)
Construct as copy.
faMatrix (const GeometricField< Type, faPatchField, areaMesh > &, Istream &)
Construct from Istream given field to solve for.
tmp< faMatrix< Type > > clone () const
Clone.
virtual ~faMatrix ()
Destructor.
const GeometricField< Type,
faPatchField, areaMesh > & psi () const
const dimensionSet & dimensions () const
Field< Type > & source ()
const Field< Type > & source () const
FieldField< Field, Type > & internalCoeffs ()
faBoundary scalar field containing pseudo-matrix coeffs
FieldField< Field, Type > & boundaryCoeffs ()
faBoundary scalar field containing pseudo-matrix coeffs
edgeTypeFieldPtr & faceFluxCorrectionPtr ()
Return pointer to face-flux non-orthogonal correction field.
void setValues (const labelUList &faces, const UList< Type > &values)
Set solution in given cells and eliminate corresponding.
void setReference (const label facei, const Type &value)
Set reference level for solution.
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
void relax ()
Relax matrix (for steady-state solution).
SolverPerformance< Type > solve (const dictionary &)
Solve returning the solution statistics.
SolverPerformance< Type > solve ()
Solve returning the solution statistics.
tmp< Field< Type > > residual () const
Return the matrix residual.
tmp< scalarField > D () const
Return the matrix diagonal.
tmp< areaScalarField > A () const
Return the central coefficient.
tmp< GeometricField< Type,
faPatchField, areaMesh > > H () const
Return the H operation source.
tmp< GeometricField< Type,
faePatchField, edgeMesh > > flux () const
Return the face-flux field from the matrix.
void operator= (const faMatrix< Type > &)
void operator= (const tmp< faMatrix< Type >> &)
void negate ()
void operator+= (const faMatrix< Type > &)
void operator+= (const tmp< faMatrix< Type >> &)
void operator-= (const faMatrix< Type > &)
void operator-= (const tmp< faMatrix< Type >> &)
void operator+= (const GeometricField< Type, faPatchField, areaMesh > &)
void operator+= (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
void operator-= (const GeometricField< Type, faPatchField, areaMesh > &)
void operator-= (const tmp< GeometricField< Type, faPatchField, areaMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator*= (const areaScalarField &)
void operator*= (const tmp< areaScalarField > &)
void operator*= (const dimensioned< scalar > &)
template<>
void setComponentReference (const label patchI, const label edgeI, const direction, const scalar value)
template<>
Foam::solverPerformance solve (const dictionary &solverControls)
template<>
Foam::tmp< Foam::scalarField > residual () const
template<>
Foam::tmp< Foam::areaScalarField > H () const
template<>
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
template<>
SolverPerformance< scalar > solve (const dictionary &)
template<>
tmp< scalarField > residual () const
template<>
tmp< areaScalarField > H () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from lduMatrix
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
Construct given an LDU addressed mesh.
lduMatrix (const lduMatrix &)
Construct as copy.
lduMatrix (lduMatrix &, bool reuse)
Construct as copy or re-use as specified.
lduMatrix (const lduMesh &, Istream &)
Construct given an LDU addressed mesh and an Istream from which the coefficients are read.
~lduMatrix ()
Destructor.
const lduMesh & mesh () const
Return the LDU mesh from which the addressing is obtained.
const lduAddressing & lduAddr () const
Return the LDU addressing.
const lduSchedule & patchSchedule () const
Return the patch evaluation schedule.
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const
bool hasUpper () const
bool hasLower () const
bool diagonal () const
bool symmetric () const
bool asymmetric () const
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix multiplication with updated interfaces.
void Tmul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
void sumA (solveScalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
Sum the coefficients on each row of the matrix.
void residual (solveScalarField &rA, const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< solveScalarField > residual (const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
Initialise the update of interfaced interfaces for matrix operations.
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
void setResidualField (const scalarField &residual, const word &fieldName, const bool initial) const
Set the residual field using an IOField on the object registry if it exists.
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type >> &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type >> &) const
InfoProxy< lduMatrix > info () const
Return info proxy.
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type >> &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type >> &tpsi) const
Friends
Ostream & operator (Ostream &, const faMatrix< Type > &)
Detailed Description
template<class Type>
class Foam::faMatrix< Type >
A special matrix type and solver, designed for finite area solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Finite-Area matrix.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
faMatrix.H
faMatrix.C
faMatrixSolve.C
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Definition at line 56 of file faMatrix.H.
Member Typedef Documentation
typedef GeometricField<Type, faePatchField, edgeMesh>* edgeTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Definition at line 296 of file faMatrix.H.
Constructor & Destructor Documentation
faMatrix (const GeometricField< Type, faPatchField, areaMesh > & psi, const dimensionSet & ds)
Construct given a field to solve for.
Definition at line 174 of file faMatrix.C.
faMatrix (const faMatrix< Type > & fam)
Construct as copy.
Definition at line 226 of file faMatrix.C.
faMatrix (const GeometricField< Type, faPatchField, areaMesh > & psi, Istream & is)
Construct from Istream given field to solve for.
Definition at line 254 of file faMatrix.C.
~faMatrix () virtual
Destructor.
Definition at line 312 of file faMatrix.C.
Member Function Documentation
ClassName ("faMatrix< Type >")
Foam::tmp< Foam::faMatrix< Type > > clone () const
Clone.
Definition at line 299 of file faMatrix.C.
const GeometricField<Type, faPatchField, areaMesh>& psi () const inline
Definition at line 251 of file faMatrix.H.
Referenced by gaussLaplacianScheme< Type >::famLaplacian(), and faMatrix< Type >::residual().
const dimensionSet& dimensions () const inline
Definition at line 256 of file faMatrix.H.
Field<Type>& source () inline
Definition at line 261 of file faMatrix.H.
Referenced by gaussLaplacianScheme< Type >::famLaplacian(), and Foam::fam::Su().
const Field<Type>& source () const inline
Definition at line 266 of file faMatrix.H.
FieldField<Field, Type>& internalCoeffs () inline
faBoundary scalar field containing pseudo-matrix coeffs
for internal cells
Definition at line 276 of file faMatrix.H.
Referenced by gaussLaplacianScheme< Type >::famLaplacian().
FieldField<Field, Type>& boundaryCoeffs () inline
faBoundary scalar field containing pseudo-matrix coeffs
for boundary cells
Definition at line 286 of file faMatrix.H.
Referenced by gaussLaplacianScheme< Type >::famLaplacian().
edgeTypeFieldPtr& faceFluxCorrectionPtr () inline
Return pointer to face-flux non-orthogonal correction field.
Definition at line 301 of file faMatrix.H.
Referenced by gaussLaplacianScheme< Type >::famLaplacian().
void setValues (const labelUList & faces, const UList< Type > & values)
Set solution in given cells and eliminate corresponding.
equations from the matrix
Definition at line 326 of file faMatrix.C.
void setReference (const label facei, const Type & value)
Set reference level for solution.
Definition at line 420 of file faMatrix.C.
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
on a given patch face
Definition at line 32 of file faMatrixSolve.C.
References Foam::diag().
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
alpha = 1 : diagonally equal alpha < 1 : ,, dominant alpha = 0 : do nothing
Definition at line 437 of file faMatrix.C.
void relax ()
Relax matrix (for steady-state solution).
alpha is read from controlDict
Definition at line 527 of file faMatrix.C.
Foam::SolverPerformance< Type > solve (const dictionary & solverControls)
Solve returning the solution statistics.
Solver controls read Istream
Definition at line 49 of file faMatrixSolve.C.
Foam::SolverPerformance< Type > solve ()
Solve returning the solution statistics.
Solver controls read from faSolution
Definition at line 164 of file faMatrixSolve.C.
References faMatrix< Type >::faSolver::solve().
Referenced by faMatrix< Type >::residual().
Foam::tmp< Foam::Field< Type > > residual () const
Return the matrix residual.
Definition at line 171 of file faMatrixSolve.C.
References lduMatrix::mesh(), Foam::name(), faMatrix< Type >::psi(), and faMatrix< Type >::solve().
Foam::tmp< Foam::scalarField > D () const
Return the matrix diagonal.
Definition at line 543 of file faMatrix.C.
Foam::tmp< Foam::areaScalarField > A () const
Return the central coefficient.
Definition at line 552 of file faMatrix.C.
Foam::tmp< Foam::GeometricField< Type, Foam::faPatchField, Foam::areaMesh > > H () const
Return the H operation source.
Definition at line 579 of file faMatrix.C.
Foam::tmp< Foam::GeometricField< Type, Foam::faePatchField, Foam::edgeMesh > > flux () const
Return the face-flux field from the matrix.
Definition at line 623 of file faMatrix.C.
void operator= (const faMatrix< Type > & famv)
Definition at line 705 of file faMatrix.C.
void operator= (const tmp< faMatrix< Type >> & tfamv)
Definition at line 738 of file faMatrix.C.
void negate ()
Definition at line 746 of file faMatrix.C.
void operator+= (const faMatrix< Type > & famv)
Definition at line 761 of file faMatrix.C.
void operator+= (const tmp< faMatrix< Type >> & tfamv)
Definition at line 787 of file faMatrix.C.
void operator-= (const faMatrix< Type > & famv)
Definition at line 795 of file faMatrix.C.
void operator-= (const tmp< faMatrix< Type >> & tfamv)
Definition at line 819 of file faMatrix.C.
void operator+= (const GeometricField< Type, faPatchField, areaMesh > & su)
Definition at line 828 of file faMatrix.C.
void operator+= (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tsu)
Definition at line 839 of file faMatrix.C.
void operator-= (const GeometricField< Type, faPatchField, areaMesh > & su)
Definition at line 850 of file faMatrix.C.
void operator-= (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tsu)
Definition at line 861 of file faMatrix.C.
void operator+= (const dimensioned< Type > & su)
Definition at line 872 of file faMatrix.C.
void operator-= (const dimensioned< Type > & su)
Definition at line 882 of file faMatrix.C.
void operator*= (const areaScalarField & vsf)
Definition at line 892 of file faMatrix.C.
void operator*= (const tmp< areaScalarField > & tvsf)
Definition at line 918 of file faMatrix.C.
void operator*= (const dimensioned< scalar > & ds)
Definition at line 929 of file faMatrix.C.
void setComponentReference (const label patchI, const label edgeI, const direction , const scalar value)
Definition at line 34 of file faScalarMatrix.C.
References Foam::diag().
Foam::solverPerformance solve (const dictionary & solverControls)
Definition at line 51 of file faScalarMatrix.C.
Foam::tmp< Foam::scalarField > residual () const
Definition at line 95 of file faScalarMatrix.C.
Foam::tmp< Foam::areaScalarField > H () const
Definition at line 124 of file faScalarMatrix.C.
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
SolverPerformance< scalar > solve (const dictionary &)
tmp< scalarField > residual () const
tmp< areaScalarField > H () const
Friends And Related Function Documentation
Ostream& operator (Ostream & , const faMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/finiteArea/faMatrices/faMatrix/faMatrix.H
src/finiteArea/faMatrices/faMatrix/faMatrix.C
src/finiteArea/faMatrices/faMatrix/faMatrixSolve.C