OpenFOAM: sigFpe Class Reference
sigFpe Class Reference
Set up trapping for floating point exceptions (signal FPE).
Classes
class ignore
Helper to locally ignore SIGFPE handling.
Public Member Functions
sigFpe ()
Constructor calls set() to activate the FPE signal handler if it was was not previously activate and requested() returns true.
~sigFpe ()
Destructor calls unset() to deactivate the FPE signal handler as required.
Static Public Member Functions
static bool requested ()
Check if SIGFPE signals handler is to be enabled.
static bool active ()
True if SIGFPE handling is currently active.
static bool nanActive ()
True if NaN memory initialisation is currently active.
static void set (bool verbose=false)
Activate SIGFPE signal handler when FOAM_SIGFPE is set.
static void unset (bool verbose=false)
Deactivate SIGFPE signal handler and NaN memory initialisation.
static void fillNan (UList< scalar > &list)
Fill data block with NaN values.
Detailed Description
Set up trapping for floating point exceptions (signal FPE).
Defined by controlDict InfoSwitch entries:
trapFpe
Enable floating point exception trapping.
setNaN
Initialization all malloced memory to NaN. Combined with trapFpe, this causes usage of uninitialized scalars to trigger an abort.
Environment variables:
FOAM_SIGFPE (true|false)
overrides trapFpe
FOAM_SETNAN (true|false)
overrides setNaN
Note that trapping can be set/removed through the static member functions or through the scope of the object (constructor sets trapping; destructor restores original). The class behaves as a singleton.
Source files
sigFpe.H
sigFpe.C
Definition at line 69 of file sigFpe.H.
Constructor & Destructor Documentation
sigFpe ()
Constructor calls set() to activate the FPE signal handler if it was was not previously activate and requested() returns true.
Definition at line 132 of file sigFpe.C.
~sigFpe ()
Destructor calls unset() to deactivate the FPE signal handler as required.
Definition at line 151 of file sigFpe.C.
Member Function Documentation
bool requested () static
Check if SIGFPE signals handler is to be enabled.
This is controlled by the trapFpe entry or the FOAM_SIGFPE environment variable
Definition at line 175 of file sigFpe.C.
References sigFpe::set().
static bool active () inline static
True if SIGFPE handling is currently active.
Definition at line 137 of file sigFpe.H.
static bool nanActive () inline static
True if NaN memory initialisation is currently active.
Definition at line 145 of file sigFpe.H.
void set (bool verbose = false) static
Activate SIGFPE signal handler when FOAM_SIGFPE is set.
Fill memory with NaN when FOAM_SETNAN is set
Definition at line 181 of file sigFpe.C.
References isTrue().
Referenced by sigFpe::requested().
void unset (bool verbose = false) static
Deactivate SIGFPE signal handler and NaN memory initialisation.
Definition at line 239 of file sigFpe.C.
Referenced by sigFpe::ignore::~ignore().
void fillNan (UList< scalar > & list) static
Fill data block with NaN values.
Definition at line 275 of file sigFpe.C.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/signals/sigFpe.H
src/OSspecific/POSIX/signals/sigFpe.C