OpenFOAM: alphaFixedPressureFvPatchScalarField Class Reference
alphaFixedPressureFvPatchScalarField Class Reference
A fixed-pressure alphaContactAngle boundary.
Public Member Functions
TypeName ("alphaFixedPressure")
Runtime type information.
alphaFixedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaFixedPressureFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given alphaFixedPressureFvPatchScalarField.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
const scalarField & p () const
Return the alphaFixed pressure.
scalarField & p ()
Return reference to the alphaFixed pressure to allow adjustment.
virtual void autoMap (const fvPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const fvPatchScalarField &, const labelList &)
Reverse map the given fvPatchField onto this fvPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
A fixed-pressure alphaContactAngle boundary.
Source files
alphaFixedPressureFvPatchScalarField.H
alphaFixedPressureFvPatchScalarField.C
Definition at line 46 of file alphaFixedPressureFvPatchScalarField.H.
Constructor & Destructor Documentation
alphaFixedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 33 of file alphaFixedPressureFvPatchScalarField.C.
Referenced by alphaFixedPressureFvPatchScalarField::clone().
alphaFixedPressureFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 59 of file alphaFixedPressureFvPatchScalarField.C.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given alphaFixedPressureFvPatchScalarField.
onto a new patch
Definition at line 45 of file alphaFixedPressureFvPatchScalarField.C.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & tppsf)
Construct as copy.
Definition at line 84 of file alphaFixedPressureFvPatchScalarField.C.
alphaFixedPressureFvPatchScalarField (const alphaFixedPressureFvPatchScalarField & tppsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 95 of file alphaFixedPressureFvPatchScalarField.C.
Member Function Documentation
TypeName ("alphaFixedPressure")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 111 of file alphaFixedPressureFvPatchScalarField.H.
References alphaFixedPressureFvPatchScalarField::alphaFixedPressureFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 132 of file alphaFixedPressureFvPatchScalarField.H.
const scalarField& p () const inline
Return the alphaFixed pressure.
Definition at line 150 of file alphaFixedPressureFvPatchScalarField.H.
scalarField& p () inline
Return reference to the alphaFixed pressure to allow adjustment.
Definition at line 158 of file alphaFixedPressureFvPatchScalarField.H.
void autoMap (const fvPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 108 of file alphaFixedPressureFvPatchScalarField.C.
void rmap (const fvPatchScalarField & ptf, const labelList & addr) virtual
Reverse map the given fvPatchField onto this fvPatchField.
Definition at line 118 of file alphaFixedPressureFvPatchScalarField.C.
References Field< scalar >::autoMap().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 132 of file alphaFixedPressureFvPatchScalarField.C.
void write (Ostream & os) const virtual
Write.
Definition at line 152 of file alphaFixedPressureFvPatchScalarField.C.
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaFixedPressure/alphaFixedPressureFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaFixedPressure/alphaFixedPressureFvPatchScalarField.C