OpenFOAM: extendedCellToCellStencil Class Reference
extendedCellToCellStencil Class Reference
Baseclass for cell-to-cell stencils.
Public Member Functions
extendedCellToCellStencil (const polyMesh &)
Construct from mesh.
Static Public Member Functions
template<class Type , class WeightType >
static tmp< GeometricField
< typename outerProduct
< WeightType, Type >::type,
fvPatchField, volMesh > > weightedSum (const mapDistribute &map, const labelListList &stencil, const GeometricField< Type, fvPatchField, volMesh > &fld, const List< List< WeightType >> &stencilWeights)
Sum surface field contributions to create cell values.
Protected Attributes
const polyMesh & mesh_
Detailed Description
Baseclass for cell-to-cell stencils.
Source files
extendedCellToCellStencil.H
extendedCellToCellStencil.C
extendedCellToCellStencilTemplates.C
Definition at line 50 of file extendedCellToCellStencil.H.
Constructor & Destructor Documentation
extendedCellToCellStencil (const polyMesh & mesh) explicit
Construct from mesh.
Definition at line 25 of file extendedCellToCellStencil.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, patchIdentifier::name(), coupledPolyPatch::parallel(), patches, and coupledPolyPatch::separated().
Member Function Documentation
static tmp< GeometricField < typename outerProduct<WeightType, Type>::type, fvPatchField, volMesh > > weightedSum (const mapDistribute & map, const labelListList & stencil, const GeometricField< Type, fvPatchField, volMesh > & fld, const List< List< WeightType >> & stencilWeights) static
Sum surface field contributions to create cell values.
Referenced by extendedCentredCellToCellStencil::collectData().
Member Data Documentation
const polyMesh& mesh_ protected
Definition at line 56 of file extendedCellToCellStencil.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCellToCellStencil.H
src/finiteVolume/fvMesh/extendedStencil/cellToCell/extendedCellToCellStencil.C