OpenFOAM: ParRunControl Class Reference
ParRunControl Class Reference
Helper class for initializing parallel jobs from the command arguments.
Public Member Functions
ParRunControl ()
Construct null.
~ParRunControl ()
Destructor, triggers Pstream::exit.
void runPar (int &argc, char **&argv, bool needsThread)
Initialize Pstream for a parallel run.
bool parRun () const
True if this is parallel run.
bool distributed () const
True if this is a parallel run and uses distributed roots.
void distributed (bool on)
Set use of distributed roots.
Detailed Description
Helper class for initializing parallel jobs from the command arguments.
This class also handles cleanup of parallel or serial jobs in a uniform manner.
Definition at line 46 of file parRun.H.
Constructor & Destructor Documentation
ParRunControl () inline
Construct null.
Definition at line 56 of file parRun.H.
~ParRunControl () inline
Destructor, triggers Pstream::exit.
Definition at line 65 of file parRun.H.
Member Function Documentation
void runPar (int & argc, char **& argv, bool needsThread) inline
Initialize Pstream for a parallel run.
Definition at line 80 of file parRun.H.
References Foam::endl(), UPstream::exit(), Foam::Info, and UPstream::init().
bool parRun () const inline
True if this is parallel run.
Definition at line 94 of file parRun.H.
bool distributed () const inline
True if this is a parallel run and uses distributed roots.
Definition at line 102 of file parRun.H.
void distributed (bool on) inline
Set use of distributed roots.
Definition at line 110 of file parRun.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/global/argList/parRun.H