OpenFOAM: vtmWriter Class Reference
vtmWriter Class Reference
Provides a means of accumulating file entries for generating a vtkMultiBlockDataSet (.vtm) file.
Public Member Functions
vtmWriter ()
Construct null, with autoName on.
vtmWriter (bool autoName)
Construct with specified behaviour for autoName.
~vtmWriter ()=default
Destructor.
bool empty () const
If there are no data sets.
label size () const
The number of data sets.
void clear ()
Clear all entries and reset output.
void setTime (scalar timeValue)
Define "TimeValue" for FieldData (name as per Catalyst output)
void setTime (const Time &t)
Define "TimeValue" for FieldData (name as per Catalyst output)
label beginBlock (const word &blockName=word::null)
Start a new block, optionally with a name.
label endBlock (const word &blockName=word::null)
End the previous block, optionally with name checking.
bool append (const fileName &file)
Add a file. The name is either empty or created with autoName.
bool append (const word &name, const fileName &file)
Add a file with name.
bool append (const fileName &file, vtk::fileTag contentType)
Add a file with given contentType extension The name is either empty or created with autoName.
bool append (const word &name, const fileName &file, vtk::fileTag contentType)
Add a file with name, with given contentType extension.
bool append_vtp (const fileName &file)
Add a (.vtp) file.
bool append_vtp (const word &name, const fileName &file)
Add a (.vtp) file with name.
bool append_vtu (const fileName &file)
Add a (.vtu) file.
bool append_vtu (const word &name, const fileName &file)
Add a (.vtu) file with name.
void repair (bool collapse=false)
Sanity fixes on the data.
void add (const word &blockName, const vtmWriter &other)
Add in content from another vtm and place under the given block name.
void add (const word &blockName, const fileName &prefix, const vtmWriter &other)
Add in content from another vtm and place under the given block name. Adjust the added 'file' entries to include the given prefix.
label write (const fileName &file)
Open file for writing (creates parent directory) and write the blocks and TimeValue.
void dump (Ostream &os) const
Print debug view of block and dataset contents.
Static Public Member Functions
static word ext ()
File extension (always "vtm")
Detailed Description
Provides a means of accumulating file entries for generating a vtkMultiBlockDataSet (.vtm) file.
For example, to generate the following content:
<?xml version='1.0'?>
<VTKFile type='vtkMultiBlockDataSet' ...>
  <vtkMultiBlockDataSet>
    <DataSet name='internal' file='internal.vtu' />
    <Block name='boundary'>
      <DataSet name='inlet' file='boundary/inlet.vtp' />
      <DataSet name='outlet' file='boundary/outlet.vtp' />
    </Block>
  </vtkMultiBlockDataSet>
  <FieldData>
    <DataArray type='Float32' Name='TimeValue' ...>
       12.345
    </DataArray>
  </FieldData>
</VTKFile>
The following code would be used:
vtm.clear();
vtm.setTime(12.345);
vtm.append("internal", "internal.vtu");
vtm.beginBlock("boundary");
vtm.append("boundary/inlet.vtp");
vtm.append("boundary/outlet.vtp");
vtm.write("outputName");
Source files
foamVtmWriter.H
foamVtmWriter.C
Definition at line 87 of file foamVtmWriter.H.
Constructor & Destructor Documentation
vtmWriter ()
Construct null, with autoName on.
Definition at line 310 of file foamVtmWriter.C.
vtmWriter (bool autoName) explicit
Construct with specified behaviour for autoName.
Definition at line 316 of file foamVtmWriter.C.
~vtmWriter () default
Destructor.
Member Function Documentation
Foam::word ext () inline static
File extension (always "vtm")
Definition at line 23 of file foamVtmWriterI.H.
bool empty () const
If there are no data sets.
Definition at line 338 of file foamVtmWriter.C.
Foam::label size () const
The number of data sets.
Definition at line 352 of file foamVtmWriter.C.
void clear ()
Clear all entries and reset output.
Definition at line 328 of file foamVtmWriter.C.
void setTime (scalar timeValue)
Define "TimeValue" for FieldData (name as per Catalyst output)
Definition at line 368 of file foamVtmWriter.C.
void setTime (const Time & t)
Define "TimeValue" for FieldData (name as per Catalyst output)
Definition at line 375 of file foamVtmWriter.C.
Foam::label beginBlock (const word & blockName = word::null)
Start a new block, optionally with a name.
Returns
block depth
Definition at line 382 of file foamVtmWriter.C.
References dimensioned< Type >::value().
Foam::label endBlock (const word & blockName = word::null)
End the previous block, optionally with name checking.
Returns
block depth
Definition at line 391 of file foamVtmWriter.C.
bool append (const fileName & file)
Add a file. The name is either empty or created with autoName.
Returns
True if file is non-empty
Definition at line 415 of file foamVtmWriter.C.
bool append (const word & name, const fileName & file)
Add a file with name.
Returns
True if file is non-empty
Definition at line 442 of file foamVtmWriter.C.
bool append (const fileName & file, vtk::fileTag contentType)
Add a file with given contentType extension The name is either empty or created with autoName.
Returns
True if file is non-empty
Definition at line 427 of file foamVtmWriter.C.
bool append (const word & name, const fileName & file, vtk::fileTag contentType)
Add a file with name, with given contentType extension.
Returns
True if file is non-empty
Definition at line 458 of file foamVtmWriter.C.
bool append_vtp (const fileName & file) inline
Add a (.vtp) file.
Returns
True if file is non-empty
Definition at line 29 of file foamVtmWriterI.H.
References Foam::vtk::fileExtension, and Foam::vtk::MULTI_BLOCK.
bool append_vtp (const word & name, const fileName & file) inline
Add a (.vtp) file with name.
Returns
True if file is non-empty
Definition at line 36 of file foamVtmWriterI.H.
References append(), and Foam::vtk::POLY_DATA.
bool append_vtu (const fileName & file) inline
Add a (.vtu) file.
Returns
True if file is non-empty
Definition at line 45 of file foamVtmWriterI.H.
References append(), and Foam::vtk::POLY_DATA.
bool append_vtu (const word & name, const fileName & file) inline
Add a (.vtu) file with name.
Returns
True if file is non-empty
Definition at line 52 of file foamVtmWriterI.H.
References append(), and Foam::vtk::UNSTRUCTURED_GRID.
void repair (bool collapse = false)
Sanity fixes on the data.
Definition at line 199 of file foamVtmWriter.C.
void add (const word & blockName, const vtmWriter & other)
Add in content from another vtm and place under the given block name.
Definition at line 565 of file foamVtmWriter.C.
void add (const word & blockName, const fileName & prefix, const vtmWriter & other)
Add in content from another vtm and place under the given block name. Adjust the added 'file' entries to include the given prefix.
Definition at line 490 of file foamVtmWriter.C.
Foam::label write (const fileName & file)
Open file for writing (creates parent directory) and write the blocks and TimeValue.
The file name is with/without an extension.
Returns
number of data sets
Definition at line 574 of file foamVtmWriter.C.
References Foam::add(), and fileName::null.
void dump (Ostream & os) const
Print debug view of block and dataset contents.
Definition at line 252 of file foamVtmWriter.C.
The documentation for this class was generated from the following files:
src/fileFormats/vtk/file/foamVtmWriter.H
src/fileFormats/vtk/file/foamVtmWriter.C
src/fileFormats/vtk/file/foamVtmWriterI.H