OpenFOAM: SHA1 Class Reference
SHA1 Class Reference
Functions to compute SHA1 message digest according to the NIST specification FIPS-180-1.
Public Member Functions
SHA1 ()
Construct null.
SHA1 (const char *str)
Construct null and append initial string.
SHA1 (const std::string &str)
Construct null and append initial std::string.
void clear ()
Reset the hashed data before appending more.
SHA1 & append (const char *str)
Append data for processing.
SHA1 & append (const char *data, size_t len)
Append data for processing.
SHA1 & append (const std::string &str)
Append string for processing.
SHA1 & append (const std::string &str, size_t pos, size_t len=std::string::npos)
Append substring for processing.
bool finalize ()
Finalized the calculations (normally not needed directly).
SHA1Digest digest () const
Calculate digest from current data.
std::string str (const bool prefixed=false) const
The digest (40-byte) text representation, optionally with '_' prefix.
Ostream & write (Ostream &os, const bool prefixed=false) const
Write digest (40-byte) representation, optionally with '_' prefix.
operator SHA1Digest () const
Cast conversion to a SHA1Digest,.
bool operator== (const SHA1 &rhs) const
Equality operator, compares digests.
bool operator== (const SHA1Digest &dig) const
Compare digest.
bool operator== (const std::string &hexdigits) const
Compare digest to (40-byte) text representation (eg, from sha1sum)
bool operator== (const char *hexdigits) const
Compare digest to (40-byte) text representation (eg, from sha1sum)
bool operator!= (const SHA1 &) const
Inequality operator, compares digests.
bool operator!= (const SHA1Digest &) const
Inequality operator, compare digest.
bool operator!= (const std::string &hexdigits) const
Inequality operator, compares digests.
bool operator!= (const char *hexdigits) const
Inequality operator, compare digest.
Detailed Description
Functions to compute SHA1 message digest according to the NIST specification FIPS-180-1.
Adapted from the gnulib implementation.
See Also
Foam::SHA1Digest
Source files
SHA1.H
SHA1I.H
SHA1.C
Definition at line 56 of file SHA1.H.
Constructor & Destructor Documentation
SHA1 () inline
Construct null.
Definition at line 27 of file SHA1I.H.
SHA1 (const char * str) inline explicit
Construct null and append initial string.
Definition at line 33 of file SHA1I.H.
References SHA1::clear().
SHA1 (const std::string & str) inline explicit
Construct null and append initial std::string.
Definition at line 40 of file SHA1I.H.
References append(), and clear().
Member Function Documentation
void clear ()
Reset the hashed data before appending more.
Definition at line 314 of file SHA1.C.
Referenced by SHA1::SHA1().
Foam::SHA1 & append (const char * str) inline
Append data for processing.
Definition at line 56 of file SHA1I.H.
Referenced by dynamicCodeContext::options().
Foam::SHA1 & append (const char * data, size_t len) inline
Append data for processing.
Definition at line 49 of file SHA1I.H.
Foam::SHA1 & append (const std::string & str) inline
Append string for processing.
Definition at line 66 of file SHA1I.H.
Foam::SHA1 & append (const std::string & str, size_t pos, size_t len = std::string::npos) inline
Append substring for processing.
Definition at line 74 of file SHA1I.H.
bool finalize ()
Finalized the calculations (normally not needed directly).
Returns false if no bytes were passed for processing
Definition at line 329 of file SHA1.C.
Foam::SHA1Digest digest () const inline
Calculate digest from current data.
Definition at line 94 of file SHA1I.H.
Referenced by SHA1::operator==(), and OSHA1streamAllocator::OSHA1streamAllocator().
std::string str (const bool prefixed = false) const inline
The digest (40-byte) text representation, optionally with '_' prefix.
Definition at line 116 of file SHA1I.H.
Foam::Ostream & write (Ostream & os, const bool prefixed = false) const inline
Write digest (40-byte) representation, optionally with '_' prefix.
Definition at line 122 of file SHA1I.H.
operator SHA1Digest () const inline
Cast conversion to a SHA1Digest,.
calculates the digest from the current data
bool operator== (const SHA1 & rhs) const inline
Equality operator, compares digests.
Definition at line 136 of file SHA1I.H.
bool operator== (const SHA1Digest & dig) const inline
Compare digest.
Definition at line 142 of file SHA1I.H.
References SHA1::digest().
bool operator== (const std::string & hexdigits) const inline
Compare digest to (40-byte) text representation (eg, from sha1sum)
An empty string is equivalent to "0000000000000000000000000000000000000000"
Definition at line 148 of file SHA1I.H.
bool operator== (const char * hexdigits) const inline
Compare digest to (40-byte) text representation (eg, from sha1sum)
A null or empty string is equivalent to "0000000000000000000000000000000000000000"
Definition at line 154 of file SHA1I.H.
bool operator!= (const SHA1 & rhs) const inline
Inequality operator, compares digests.
Definition at line 160 of file SHA1I.H.
bool operator!= (const SHA1Digest & rhs) const inline
Inequality operator, compare digest.
Definition at line 166 of file SHA1I.H.
References Foam::operator==().
bool operator!= (const std::string & hexdigits) const inline
Inequality operator, compares digests.
Definition at line 172 of file SHA1I.H.
References Foam::operator==().
bool operator!= (const char * hexdigits) const inline
Inequality operator, compare digest.
Definition at line 178 of file SHA1I.H.
References Foam::operator==().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/hashes/SHA1/SHA1.H
src/OpenFOAM/primitives/hashes/SHA1/SHA1.C
src/OpenFOAM/primitives/hashes/SHA1/SHA1I.H