OpenFOAM: fvMatrix< Type > Class Template Reference
fvMatrix< Type > Class Template Reference
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Classes
class fvSolver
Solver class returned by the solver function.
Public Types
typedef GeometricField< Type,
fvsPatchField, surfaceMesh > * surfaceTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Public Member Functions
ClassName ("fvMatrix")
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &, const dimensionSet &)
Construct given a field to solve for.
fvMatrix (const fvMatrix< Type > &)
Construct as copy.
fvMatrix (const tmp< fvMatrix< Type >> &)
Construct as copy of tmp<fvMatrix<Type>> deleting argument.
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > &, Istream &)
Construct from Istream given field to solve for.
tmp< fvMatrix< Type > > clone () const
Clone.
virtual ~fvMatrix ()
Destructor.
const GeometricField< Type,
fvPatchField, volMesh > & psi () const
const dimensionSet & dimensions () const
Field< Type > & source ()
const Field< Type > & source () const
const FieldField< Field, Type > & internalCoeffs () const
fvBoundary scalar field containing pseudo-matrix coeffs
FieldField< Field, Type > & internalCoeffs ()
fvBoundary scalar field containing pseudo-matrix coeffs
const FieldField< Field, Type > & boundaryCoeffs () const
fvBoundary scalar field containing pseudo-matrix coeffs
FieldField< Field, Type > & boundaryCoeffs ()
fvBoundary scalar field containing pseudo-matrix coeffs
surfaceTypeFieldPtr & faceFluxCorrectionPtr ()
Return pointer to face-flux non-orthogonal correction field.
void setValues (const labelUList &cells, const UList< Type > &values)
Set solution in given cells to the specified values.
void setValues (const labelUList &cells, const UIndirectList< Type > &values)
Set solution in given cells to the specified values.
void setReference (const label celli, const Type &value, const bool forceReference=false)
Set reference level for solution.
void setReferences (const labelUList &cells, const Type &value, const bool forceReference=false)
Set references level for solution.
void setReferences (const labelUList &cells, const UList< Type > &values, const bool forceReference=false)
Set references level for solution.
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
void relax ()
Relax matrix (for steady-state solution).
void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::Boundary &values)
Manipulate based on a boundary field.
autoPtr< fvSolver > solver (const dictionary &)
Construct and return the solver.
autoPtr< fvSolver > solver ()
Construct and return the solver.
SolverPerformance< Type > solveSegregatedOrCoupled (const dictionary &)
Solve segregated or coupled returning the solution statistics.
SolverPerformance< Type > solveSegregated (const dictionary &)
Solve segregated returning the solution statistics.
SolverPerformance< Type > solveCoupled (const dictionary &)
Solve coupled returning the solution statistics.
SolverPerformance< Type > solve (const dictionary &)
Solve returning the solution statistics.
SolverPerformance< Type > solve ()
Solve returning the solution statistics.
tmp< Field< Type > > residual () const
Return the matrix residual.
tmp< scalarField > D () const
Return the matrix scalar diagonal.
tmp< Field< Type > > DD () const
Return the matrix Type diagonal.
tmp< volScalarField > A () const
Return the central coefficient.
tmp< GeometricField< Type,
fvPatchField, volMesh > > H () const
Return the H operation source.
tmp< volScalarField > H1 () const
Return H(1)
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > flux () const
Return the face-flux field from the matrix.
const dictionary & solverDict () const
Return the solver dictionary taking into account finalIteration.
void operator= (const fvMatrix< Type > &)
void operator= (const tmp< fvMatrix< Type >> &)
void negate ()
void operator+= (const fvMatrix< Type > &)
void operator+= (const tmp< fvMatrix< Type >> &)
void operator-= (const fvMatrix< Type > &)
void operator-= (const tmp< fvMatrix< Type >> &)
void operator+= (const DimensionedField< Type, volMesh > &)
void operator+= (const tmp< DimensionedField< Type, volMesh >> &)
void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
void operator-= (const DimensionedField< Type, volMesh > &)
void operator-= (const tmp< DimensionedField< Type, volMesh >> &)
void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
void operator+= (const dimensioned< Type > &)
void operator-= (const dimensioned< Type > &)
void operator+= (const zero &)
void operator-= (const zero &)
void operator*= (const volScalarField::Internal &)
void operator*= (const tmp< volScalarField::Internal > &)
void operator*= (const tmp< volScalarField > &)
void operator*= (const dimensioned< scalar > &)
template<>
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
template<>
Foam::autoPtr< Foam::fvMatrix
< Foam::scalar >::fvSolver > solver (const dictionary &solverControls)
template<>
Foam::solverPerformance solveSegregated (const dictionary &solverControls)
template<>
Foam::tmp< Foam::scalarField > residual () const
template<>
Foam::tmp< Foam::volScalarField > H () const
template<>
Foam::tmp< Foam::volScalarField > H1 () const
template<>
void setComponentReference (const label patchi, const label facei, const direction, const scalar value)
template<>
autoPtr< fvMatrix< scalar >
::fvSolver > solver (const dictionary &)
template<>
solverPerformance solveSegregated (const dictionary &)
template<>
tmp< scalarField > residual () const
template<>
tmp< volScalarField > H () const
template<>
tmp< volScalarField > H1 () const
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from lduMatrix
ClassName ("lduMatrix")
lduMatrix (const lduMesh &)
Construct given an LDU addressed mesh.
lduMatrix (const lduMatrix &)
Construct as copy.
lduMatrix (lduMatrix &, bool reuse)
Construct as copy or re-use as specified.
lduMatrix (const lduMesh &, Istream &)
Construct given an LDU addressed mesh and an Istream from which the coefficients are read.
~lduMatrix ()
Destructor.
const lduMesh & mesh () const
Return the LDU mesh from which the addressing is obtained.
const lduAddressing & lduAddr () const
Return the LDU addressing.
const lduSchedule & patchSchedule () const
Return the patch evaluation schedule.
scalarField & lower ()
scalarField & diag ()
scalarField & upper ()
scalarField & lower (const label size)
scalarField & diag (const label nCoeffs)
scalarField & upper (const label nCoeffs)
const scalarField & lower () const
const scalarField & diag () const
const scalarField & upper () const
bool hasDiag () const
bool hasUpper () const
bool hasLower () const
bool diagonal () const
bool symmetric () const
bool asymmetric () const
void sumDiag ()
void negSumDiag ()
void sumMagOffDiag (scalarField &sumOff) const
void Amul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix multiplication with updated interfaces.
void Tmul (solveScalarField &, const tmp< solveScalarField > &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &, const direction cmpt) const
Matrix transpose multiplication with updated interfaces.
void sumA (solveScalarField &, const FieldField< Field, scalar > &, const lduInterfaceFieldPtrsList &) const
Sum the coefficients on each row of the matrix.
void residual (solveScalarField &rA, const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
tmp< solveScalarField > residual (const solveScalarField &psi, const scalarField &source, const FieldField< Field, scalar > &interfaceBouCoeffs, const lduInterfaceFieldPtrsList &interfaces, const direction cmpt) const
void initMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
Initialise the update of interfaced interfaces for matrix operations.
void updateMatrixInterfaces (const bool add, const FieldField< Field, scalar > &interfaceCoeffs, const lduInterfaceFieldPtrsList &interfaces, const solveScalarField &psiif, solveScalarField &result, const direction cmpt) const
Update interfaced interfaces for matrix operations.
void setResidualField (const scalarField &residual, const word &fieldName, const bool initial) const
Set the residual field using an IOField on the object registry if it exists.
template<class Type >
tmp< Field< Type > > H (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > H (const tmp< Field< Type >> &) const
tmp< scalarField > H1 () const
template<class Type >
tmp< Field< Type > > faceH (const Field< Type > &) const
template<class Type >
tmp< Field< Type > > faceH (const tmp< Field< Type >> &) const
InfoProxy< lduMatrix > info () const
Return info proxy.
void operator= (const lduMatrix &)
void negate ()
void operator+= (const lduMatrix &)
void operator-= (const lduMatrix &)
void operator*= (const scalarField &)
void operator*= (scalar)
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > H (const tmp< Field< Type >> &tpsi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const Field< Type > &psi) const
template<class Type >
Foam::tmp< Foam::Field< Type > > faceH (const tmp< Field< Type >> &tpsi) const
Protected Member Functions
template<class Type2 >
void addToInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
Add patch contribution to internal field.
template<class Type2 >
void addToInternalField (const labelUList &addr, const tmp< Field< Type2 >> &tpf, Field< Type2 > &intf) const
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const Field< Type2 > &pf, Field< Type2 > &intf) const
Subtract patch contribution from internal field.
template<class Type2 >
void subtractFromInternalField (const labelUList &addr, const tmp< Field< Type2 >> &tpf, Field< Type2 > &intf) const
void addBoundaryDiag (scalarField &diag, const direction cmpt) const
void addCmptAvBoundaryDiag (scalarField &diag) const
void addBoundarySource (Field< Type > &source, const bool couples=true) const
template<template< class > class ListType>
void setValuesFromList (const labelUList &cells, const ListType< Type > &values)
Set solution in given cells to the specified values.
Friends
class fvSolver
Declare friendship with the fvSolver class.
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const fvMatrix< Type > &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const fvMatrix< Type > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type >> &, const DimensionedField< Type, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > operator& (const tmp< fvMatrix< Type >> &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &)
Ostream & operator (Ostream &, const fvMatrix< Type > &)
Detailed Description
template<class Type>
class Foam::fvMatrix< Type >
A special matrix type and solver, designed for finite volume solutions of scalar equations. Face addressing is used to make all matrix assembly and solution loops vectorise.
Source files
fvMatrix.H
fvMatrix.C
fvMatrixSolve.C
fvScalarMatrix.C
Definition at line 72 of file fvPatchField.H.
Member Typedef Documentation
typedef GeometricField<Type, fvsPatchField, surfaceMesh>* surfaceTypeFieldPtr
Declare return type of the faceFluxCorrectionPtr() function.
Definition at line 390 of file fvMatrix.H.
Constructor & Destructor Documentation
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, const dimensionSet & ds)
Construct given a field to solve for.
Definition at line 264 of file fvMatrix.C.
fvMatrix (const fvMatrix< Type > & fvm)
Construct as copy.
Definition at line 318 of file fvMatrix.C.
fvMatrix (const tmp< fvMatrix< Type >> & tfvm)
Construct as copy of tmp<fvMatrix<Type>> deleting argument.
Definition at line 347 of file fvMatrix.C.
fvMatrix (const GeometricField< Type, fvPatchField, volMesh > & psi, Istream & is)
Construct from Istream given field to solve for.
Definition at line 402 of file fvMatrix.C.
~fvMatrix () virtual
Destructor.
Definition at line 461 of file fvMatrix.C.
Member Function Documentation
void addToInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Add patch contribution to internal field.
Definition at line 34 of file fvMatrix.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, forAll, UList< Type >::size(), and UList< T >::size().
void addToInternalField (const labelUList & addr, const tmp< Field< Type2 >> & tpf, Field< Type2 > & intf) const protected
Definition at line 57 of file fvMatrix.C.
void subtractFromInternalField (const labelUList & addr, const Field< Type2 > & pf, Field< Type2 > & intf) const protected
Subtract patch contribution from internal field.
Definition at line 71 of file fvMatrix.C.
void subtractFromInternalField (const labelUList & addr, const tmp< Field< Type2 >> & tpf, Field< Type2 > & intf) const protected
Definition at line 94 of file fvMatrix.C.
void addBoundaryDiag (scalarField & diag, const direction cmpt) const protected
Definition at line 107 of file fvMatrix.C.
void addCmptAvBoundaryDiag (scalarField & diag) const protected
Definition at line 125 of file fvMatrix.C.
void addBoundarySource (Field< Type > & source, const bool couples = true) const protected
Definition at line 141 of file fvMatrix.C.
void setValuesFromList (const labelUList & cells, const ListType< Type > & values) protected
Set solution in given cells to the specified values.
Definition at line 174 of file fvMatrix.C.
ClassName ("fvMatrix< Type >")
Foam::tmp< Foam::fvMatrix< Type > > clone () const
Clone.
Definition at line 449 of file fvMatrix.C.
const GeometricField<Type, fvPatchField, volMesh>& psi () const inline
Definition at line 325 of file fvMatrix.H.
Referenced by explicitPorositySource::read().
const dimensionSet& dimensions () const inline
Definition at line 330 of file fvMatrix.H.
Referenced by explicitPorositySource::read().
Field<Type>& source () inline
Definition at line 335 of file fvMatrix.H.
const Field<Type>& source () const inline
Definition at line 340 of file fvMatrix.H.
const FieldField<Field, Type>& internalCoeffs () const inline
fvBoundary scalar field containing pseudo-matrix coeffs
for internal cells
Definition at line 350 of file fvMatrix.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected().
FieldField<Field, Type>& internalCoeffs () inline
fvBoundary scalar field containing pseudo-matrix coeffs
for internal cells
Definition at line 360 of file fvMatrix.H.
const FieldField<Field, Type>& boundaryCoeffs () const inline
fvBoundary scalar field containing pseudo-matrix coeffs
for boundary cells
Definition at line 370 of file fvMatrix.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected().
FieldField<Field, Type>& boundaryCoeffs () inline
fvBoundary scalar field containing pseudo-matrix coeffs
for boundary cells
Definition at line 380 of file fvMatrix.H.
surfaceTypeFieldPtr& faceFluxCorrectionPtr () inline
Return pointer to face-flux non-orthogonal correction field.
Definition at line 395 of file fvMatrix.H.
void setValues (const labelUList & cells, const UList< Type > & values)
Set solution in given cells to the specified values.
and eliminate the corresponding equations from the matrix.
Definition at line 480 of file fvMatrix.C.
void setValues (const labelUList & cells, const UIndirectList< Type > & values)
Set solution in given cells to the specified values.
and eliminate the corresponding equations from the matrix.
Definition at line 491 of file fvMatrix.C.
void setReference (const label celli, const Type & value, const bool forceReference = false)
Set reference level for solution.
Definition at line 502 of file fvMatrix.C.
Referenced by Foam::CorrectPhi().
void setReferences (const labelUList & cells, const Type & value, const bool forceReference = false)
Set references level for solution.
Definition at line 518 of file fvMatrix.C.
void setReferences (const labelUList & cells, const UList< Type > & values, const bool forceReference = false)
Set references level for solution.
Definition at line 543 of file fvMatrix.C.
void setComponentReference (const label patchi, const label facei, const direction cmpt, const scalar value)
Set reference level for a component of the solution.
on a given patch face
Definition at line 31 of file fvMatrixSolve.C.
References Foam::diag(), and value().
void relax (const scalar alpha)
Relax matrix (for steady-state solution).
alpha = 1 : diagonally equal alpha < 1 : diagonally dominant alpha = 0 : do nothing Note: Requires positive diagonal.
Definition at line 567 of file fvMatrix.C.
void relax ()
Relax matrix (for steady-state solution).
alpha is read from controlDict
Definition at line 718 of file fvMatrix.C.
void boundaryManipulate (typename GeometricField< Type, fvPatchField, volMesh >::Boundary & values)
Manipulate based on a boundary field.
Definition at line 735 of file fvMatrix.C.
autoPtr<fvSolver> solver (const dictionary &)
Construct and return the solver.
Use the given solver controls
Foam::autoPtr< typename Foam::fvMatrix< Type >::fvSolver > solver ()
Construct and return the solver.
Solver controls read from fvSolution
Definition at line 301 of file fvMatrixSolve.C.
Foam::SolverPerformance< Type > solveSegregatedOrCoupled (const dictionary & solverControls)
Solve segregated or coupled returning the solution statistics.
Use the given solver controls
Definition at line 55 of file fvMatrixSolve.C.
Referenced by fvMesh::addFvPatches(), and fvMesh::solve().
Foam::SolverPerformance< Type > solveSegregated (const dictionary & solverControls)
Solve segregated returning the solution statistics.
Use the given solver controls
Definition at line 108 of file fvMatrixSolve.C.
Foam::SolverPerformance< Type > solveCoupled (const dictionary & solverControls)
Solve coupled returning the solution statistics.
Use the given solver controls
Definition at line 231 of file fvMatrixSolve.C.
Foam::SolverPerformance< Type > solve (const dictionary & solverControls)
Solve returning the solution statistics.
Use the given solver controls
Definition at line 291 of file fvMatrixSolve.C.
Referenced by Foam::CorrectPhi().
Foam::SolverPerformance< Type > solve ()
Solve returning the solution statistics.
Solver controls read from fvSolution
Definition at line 315 of file fvMatrixSolve.C.
References fvMatrix< Type >::fvSolver::solve().
Referenced by fvMatrix< Type >::residual().
Foam::tmp< Foam::Field< Type > > residual () const
Return the matrix residual.
Definition at line 322 of file fvMatrixSolve.C.
References fvMatrix< Type >::solve(), and fvMatrix< Type >::solverDict().
Foam::tmp< Foam::scalarField > D () const
Return the matrix scalar diagonal.
Definition at line 748 of file fvMatrix.C.
Foam::tmp< Foam::Field< Type > > DD () const
Return the matrix Type diagonal.
Definition at line 757 of file fvMatrix.C.
Foam::tmp< Foam::volScalarField > A () const
Return the central coefficient.
Definition at line 781 of file fvMatrix.C.
Foam::tmp< Foam::GeometricField< Type, Foam::fvPatchField, Foam::volMesh > > H () const
Return the H operation source.
Definition at line 810 of file fvMatrix.C.
Foam::tmp< Foam::volScalarField > H1 () const
Return H(1)
Definition at line 872 of file fvMatrix.C.
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > flux () const
Return the face-flux field from the matrix.
Definition at line 920 of file fvMatrix.C.
Referenced by Foam::CorrectPhi().
const Foam::dictionary & solverDict () const
Return the solver dictionary taking into account finalIteration.
Definition at line 1007 of file fvMatrix.C.
Referenced by fvMatrix< Type >::residual().
void operator= (const fvMatrix< Type > & fvmv)
Definition at line 1023 of file fvMatrix.C.
void operator= (const tmp< fvMatrix< Type >> & tfvmv)
Definition at line 1057 of file fvMatrix.C.
void negate ()
Definition at line 1065 of file fvMatrix.C.
void operator+= (const fvMatrix< Type > & fvmv)
Definition at line 1080 of file fvMatrix.C.
void operator+= (const tmp< fvMatrix< Type >> & tfvmv)
Definition at line 1106 of file fvMatrix.C.
void operator-= (const fvMatrix< Type > & fvmv)
Definition at line 1114 of file fvMatrix.C.
void operator-= (const tmp< fvMatrix< Type >> & tfvmv)
Definition at line 1138 of file fvMatrix.C.
void operator+= (const DimensionedField< Type, volMesh > & su)
Definition at line 1147 of file fvMatrix.C.
void operator+= (const tmp< DimensionedField< Type, volMesh >> & tsu)
Definition at line 1158 of file fvMatrix.C.
void operator+= (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tsu)
Definition at line 1169 of file fvMatrix.C.
void operator-= (const DimensionedField< Type, volMesh > & su)
Definition at line 1180 of file fvMatrix.C.
void operator-= (const tmp< DimensionedField< Type, volMesh >> & tsu)
Definition at line 1191 of file fvMatrix.C.
void operator-= (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tsu)
Definition at line 1202 of file fvMatrix.C.
void operator+= (const dimensioned< Type > & su)
Definition at line 1213 of file fvMatrix.C.
void operator-= (const dimensioned< Type > & su)
Definition at line 1223 of file fvMatrix.C.
References DimensionedField< Type, GeoMesh >::mesh(), and psi.
void operator+= (const zero &)
Definition at line 1233 of file fvMatrix.C.
References DimensionedField< Type, GeoMesh >::mesh(), and psi.
void operator-= (const zero &)
Definition at line 1241 of file fvMatrix.C.
void operator*= (const volScalarField::Internal & dsf)
Definition at line 1249 of file fvMatrix.C.
void operator*= (const tmp< volScalarField::Internal > & tdsf)
Definition at line 1279 of file fvMatrix.C.
void operator*= (const tmp< volScalarField > & tvsf)
Definition at line 1290 of file fvMatrix.C.
void operator*= (const dimensioned< scalar > & ds)
Definition at line 1301 of file fvMatrix.C.
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
Definition at line 31 of file fvScalarMatrix.C.
References Foam::diag(), and value().
Foam::autoPtr< Foam::fvMatrix< Foam::scalar >::fvSolver > solver (const dictionary & solverControls)
Definition at line 56 of file fvScalarMatrix.C.
Foam::solverPerformance solveSegregated (const dictionary & solverControls)
Definition at line 143 of file fvScalarMatrix.C.
Foam::tmp< Foam::scalarField > residual () const
Definition at line 192 of file fvScalarMatrix.C.
Foam::tmp< Foam::volScalarField > H () const
Definition at line 221 of file fvScalarMatrix.C.
Foam::tmp< Foam::volScalarField > H1 () const
Definition at line 253 of file fvScalarMatrix.C.
void setComponentReference (const label patchi, const label facei, const direction , const scalar value)
autoPtr< fvMatrix< scalar >::fvSolver > solver (const dictionary &)
solverPerformance solveSegregated (const dictionary &)
tmp< scalarField > residual () const
tmp< volScalarField > H () const
tmp< volScalarField > H1 () const
Friends And Related Function Documentation
friend class fvSolver friend
Declare friendship with the fvSolver class.
Definition at line 164 of file fvMatrix.H.
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const fvMatrix< Type > & , const DimensionedField< Type, volMesh > &) friend
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const fvMatrix< Type > & , const tmp< GeometricField< Type, fvPatchField, volMesh >> &) friend
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const tmp< fvMatrix< Type >> & , const DimensionedField< Type, volMesh > &) friend
tmp<GeometricField<Type, fvPatchField, volMesh> > operator& (const tmp< fvMatrix< Type >> & , const tmp< GeometricField< Type, fvPatchField, volMesh >> &) friend
Ostream& operator (Ostream & , const fvMatrix< Type > &) friend
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/fvPatchField/fvPatchField.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.H
src/finiteVolume/fvMatrices/fvMatrix/fvMatrix.C
src/finiteVolume/fvMatrices/fvMatrix/fvMatrixSolve.C