OpenFOAM: mappedVariableThicknessWallPolyPatch Class Reference
mappedVariableThicknessWallPolyPatch Class Reference
Foam::mappedVariableThicknessWallPolyPatch.
Public Member Functions
TypeName ("mappedWallVariableThickness")
Runtime type information.
mappedVariableThicknessWallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
mappedVariableThicknessWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vectorField &offset, const polyBoundaryMesh &bm)
Construct from components.
mappedVariableThicknessWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vector &offset, const polyBoundaryMesh &bm)
Construct from components. Uniform offset.
mappedVariableThicknessWallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~mappedVariableThicknessWallPolyPatch ()
Destructor.
scalarList & thickness ()
Return non const thickness.
const scalarList & thickness () const
Return const thickness.
void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from mappedWallPolyPatch
TypeName ("mappedWall")
Runtime type information.
mappedWallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
mappedWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vectorField &offset, const polyBoundaryMesh &bm)
Construct from components.
mappedWallPolyPatch (const word &name, const label size, const label start, const label index, const word &sampleRegion, const mappedPatchBase::sampleMode mode, const word &samplePatch, const vector &offset, const polyBoundaryMesh &bm)
Construct from components. Uniform offset.
mappedWallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
mappedWallPolyPatch (const mappedWallPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
mappedWallPolyPatch (const mappedWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
mappedWallPolyPatch (const mappedWallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~mappedWallPolyPatch ()
Destructor.
Public Member Functions inherited from wallPolyPatch
TypeName ("wall")
Runtime type information.
wallPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
wallPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
wallPolyPatch (const wallPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
wallPolyPatch (const wallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
wallPolyPatch (const wallPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label offset () const
The offset where this patch starts in the boundary face list.
label start () const
Return start label of this patch in the polyMesh face list.
labelRange range () const
Return start/size range of this patch.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch is geometrically coupled (i.e. faces and.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
tmp< scalarField > areaFraction () const
Return the area fraction as the ratio of the stored face area and the area given by the face points.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &p, const label index)
Copy construct, resetting the index.
virtual ~patchIdentifier ()=default
Destructor.
const word & name () const
Return the patch name.
word & name ()
Modifiable patch name.
const word & physicalType () const
The optional physical type of the patch.
word & physicalType ()
Modifiable optional physical type of the patch.
label index () const
The index of this patch in the boundaryMesh.
label & index ()
Modifiable the index of this patch in the boundaryMesh.
const wordList & inGroups () const
The optional groups that the patch belongs to.
wordList & inGroups ()
Modifiable optional groups that the patch belongs to.
bool inGroup (const word &name) const
Check if the patch is in named group.
void write (Ostream &os) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &&faces, const Field< PointType > &points)
Construct from components, transferring faces.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< PointType > & faceNormals () const
Return face unit normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Public Member Functions inherited from mappedPatchBase
TypeName ("mappedPatchBase")
Runtime type information.
mappedPatchBase (const polyPatch &)
Construct from patch.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
Construct with offsetMode=non-uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &offset)
Construct from offsetMode=uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar distance)
Construct from offsetMode=normal and distance.
mappedPatchBase (const polyPatch &, const dictionary &)
Construct from dictionary.
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
Construct from dictionary and (collocated) sample mode.
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
Construct as copy, resetting patch.
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
Construct as copy, resetting patch, map original data.
virtual ~mappedPatchBase ()
Destructor.
void clearOut ()
const sampleMode & mode () const
What to sample.
const word & sampleRegion () const
Region to sample.
const word & samplePatch () const
Patch (only if NEARESTPATCHFACE)
const word & coupleGroup () const
PatchGroup (only if NEARESTPATCHFACE)
label sampleSize () const
Return size of mapped mesh/patch/boundary.
const vector & offset () const
Offset vector (from patch faces to destination mesh objects)
const vectorField & offsets () const
Offset vector (from patch faces to destination mesh objects)
bool sameRegion () const
Cached sampleRegion != mesh.name()
const mapDistribute & map () const
Return reference to the parallel distribution map.
const
AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
Return reference to the AMI interpolator.
const autoPtr
< Foam::searchableSurface > & surfPtr () const
Return a pointer to the AMI projection surface.
const polyMesh & sampleMesh () const
Get the region mesh.
const polyPatch & samplePolyPatch () const
Get the patch on the region.
tmp< pointField > samplePoints () const
Get the sample points.
template<class Type >
void distribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
template<class Type >
void reverseDistribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
Additional Inherited Members
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Public Types inherited from mappedPatchBase
enum sampleMode {
NEARESTCELL, NEARESTPATCHFACE, NEARESTPATCHFACEAMI, NEARESTPATCHPOINT,
NEARESTFACE, NEARESTONLYCELL
}
Mesh items to sample.
enum offsetMode { UNIFORM, NONUNIFORM, NORMAL }
How to project face centres.
typedef Tuple2< pointIndexHit,
Tuple2< scalar, label > > nearInfo
Helper class for finding nearest.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Member Functions inherited from mappedPatchBase
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
Get a point on the face given a face decomposition method:
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Public Attributes inherited from mappedPatchBase
static const Enum< sampleMode > sampleModeNames_
static const Enum< offsetMode > offsetModeNames_
Protected Member Functions inherited from mappedWallPolyPatch
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Protected Member Functions inherited from mappedPatchBase
tmp< pointField > facePoints (const polyPatch &) const
Get the points from face-centre-decomposition face centres.
void collectSamples (const pointField &facePoints, pointField &, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
Collect single list of samples and originating processor+face.
void findSamples (const sampleMode mode, const pointField &, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
Find cells/faces containing samples.
tmp< pointField > samplePoints (const pointField &) const
Get the sample points given the face points.
void calcMapping () const
Calculate mapping.
void calcAMI () const
Calculate AMI interpolator.
Static Protected Member Functions inherited from mappedPatchBase
static tmp< pointField > readListOrField (const word &keyword, const dictionary &dict, const label size)
Helper to read field or non-uniform list from dictionary.
Protected Attributes inherited from mappedPatchBase
const polyPatch & patch_
Patch to sample.
word sampleRegion_
Region to sample.
const sampleMode mode_
What to sample.
word samplePatch_
Patch (if in sampleMode NEARESTPATCH*)
const coupleGroupIdentifier coupleGroup_
PatchGroup (if in sampleMode NEARESTPATCH*)
offsetMode offsetMode_
How to obtain samples.
vector offset_
Offset vector (uniform)
vectorField offsets_
Offset vector (nonuniform)
scalar distance_
Offset distance (normal)
bool sameRegion_
Same region.
autoPtr< mapDistribute > mapPtr_
Communication schedule:
autoPtr
< AMIPatchToPatchInterpolation > AMIPtr_
Pointer to AMI interpolator.
const bool AMIReverse_
Flag to indicate that slave patch should be reversed for AMI.
autoPtr< searchableSurface > surfPtr_
Pointer to projection surface employed by AMI interpolator.
dictionary surfDict_
Dictionary storing projection surface description.
Detailed Description
Foam::mappedVariableThicknessWallPolyPatch.
Source files
mappedVariableThicknessWallPolyPatch.H
mappedVariableThicknessWallPolyPatch.C
Definition at line 50 of file mappedVariableThicknessWallPolyPatch.H.
Constructor & Destructor Documentation
mappedVariableThicknessWallPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from components.
Definition at line 49 of file mappedVariableThicknessWallPolyPatch.C.
Referenced by mappedVariableThicknessWallPolyPatch::clone().
mappedVariableThicknessWallPolyPatch (const word & name, const label size, const label start, const label index, const word & sampleRegion, const mappedPatchBase::sampleMode mode, const word & samplePatch, const vectorField & offset, const polyBoundaryMesh & bm)
Construct from components.
Definition at line 64 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch (const word & name, const label size, const label start, const label index, const word & sampleRegion, const mappedPatchBase::sampleMode mode, const word & samplePatch, const vector & offset, const polyBoundaryMesh & bm)
Construct from components. Uniform offset.
Definition at line 82 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 100 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 115 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 126 of file mappedVariableThicknessWallPolyPatch.C.
mappedVariableThicknessWallPolyPatch (const mappedVariableThicknessWallPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 140 of file mappedVariableThicknessWallPolyPatch.C.
~mappedVariableThicknessWallPolyPatch () virtual
Destructor.
Definition at line 156 of file mappedVariableThicknessWallPolyPatch.C.
Member Function Documentation
TypeName ("mappedWallVariableThickness")
Runtime type information.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from mappedWallPolyPatch.
Definition at line 168 of file mappedVariableThicknessWallPolyPatch.H.
References mappedVariableThicknessWallPolyPatch::mappedVariableThicknessWallPolyPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from mappedWallPolyPatch.
Definition at line 182 of file mappedVariableThicknessWallPolyPatch.H.
References mappedVariableThicknessWallPolyPatch::mappedVariableThicknessWallPolyPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from mappedWallPolyPatch.
Definition at line 208 of file mappedVariableThicknessWallPolyPatch.H.
scalarList& thickness () inline
Return non const thickness.
Definition at line 240 of file mappedVariableThicknessWallPolyPatch.H.
const scalarList& thickness () const inline
Return const thickness.
Definition at line 249 of file mappedVariableThicknessWallPolyPatch.H.
void write (Foam::Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from mappedWallPolyPatch.
Definition at line 163 of file mappedVariableThicknessWallPolyPatch.C.
The documentation for this class was generated from the following files:
src/meshTools/mappedPatches/mappedPolyPatch/mappedVariableThicknessWallPolyPatch.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedVariableThicknessWallPolyPatch.C