OpenFOAM: interpolation< class > Class Template Reference
interpolation< class > Class Template Reference abstract
Abstract base class for interpolation.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolation, dictionary,(const GeometricField< Type, fvPatchField, volMesh > &psi),(psi))
interpolation (const GeometricField< Type, fvPatchField, volMesh > &psi)
Construct from components.
virtual ~interpolation ()=default
Destructor.
const GeometricField< Type,
fvPatchField, volMesh > & psi () const
Return the field to be interpolated.
virtual Type interpolate (const vector &position, const label celli, const label facei=-1) const =0
Interpolate field to the given point in the given cell.
virtual Type interpolate (const barycentric &coordinates, const tetIndices &tetIs, const label facei=-1) const
Interpolate field to the given coordinates in the tetrahedron.
Static Public Member Functions
static autoPtr< interpolation
< Type > > New (const word &interpolationType, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the specified interpolation scheme.
static autoPtr< interpolation
< Type > > New (const dictionary &interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > &psi)
Return a reference to the selected interpolation scheme.
Protected Attributes
const GeometricField< Type,
fvPatchField, volMesh > & psi_
const polyMesh & pMesh_
const vectorField & pMeshPoints_
const faceList & pMeshFaces_
const vectorField & pMeshFaceCentres_
const vectorField & pMeshFaceAreas_
Detailed Description
template<class>
class Foam::interpolation< class >
Abstract base class for interpolation.
Definition at line 91 of file mappedPatchFieldBase.H.
Constructor & Destructor Documentation
interpolation (const GeometricField< Type, fvPatchField, volMesh > & psi)
Construct from components.
Definition at line 30 of file interpolation.C.
virtual ~interpolation () virtual default
Destructor.
Member Function Documentation
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (autoPtr , interpolation< class > , dictionary , (const GeometricField< Type, fvPatchField, volMesh > &psi) , (psi))
Foam::autoPtr< Foam::interpolation< Type > > New (const word & interpolationType, const GeometricField< Type, fvPatchField, volMesh > & psi) static
Return a reference to the specified interpolation scheme.
Definition at line 29 of file interpolationNew.C.
References Foam::exit(), Foam::FatalError, and FatalErrorInLookup.
Referenced by discreteSurface::sampleType().
Foam::autoPtr< Foam::interpolation< Type > > New (const dictionary & interpolationSchemes, const GeometricField< Type, fvPatchField, volMesh > & psi) static
Return a reference to the selected interpolation scheme.
Definition at line 52 of file interpolationNew.C.
const GeometricField<Type, fvPatchField, volMesh>& psi () const inline
Return the field to be interpolated.
Definition at line 133 of file interpolation.H.
Referenced by sampledPatch::sampleOnFaces(), sampledTriSurfaceMesh::sampleOnFaces(), and sampledPatchInternalField::sampleOnFaces().
virtual Type interpolate (const vector & position, const label celli, const label facei = -1) const pure virtual
Interpolate field to the given point in the given cell.
Implemented in interpolationCellPointFace< Type >, interpolationPointMVC< Type >, interpolationCellPoint< Type >, interpolationCellPoint< scalar >, interpolationCellPoint< Foam::Vector >, interpolationCellPointWallModified< Type >, interpolationCellPatchConstrained< Type >, interpolationCell< Type >, and interpolationCell< scalar >.
Referenced by interpolation< Foam::Vector >::psi(), sampledSurface::sampleOnFaces(), sampledThresholdCellFaces::sampleOnFaces(), ReactingParcel< ParcelType >::setCellValues(), ThermoParcel< ParcelType >::setCellValues(), and KinematicParcel< ParcelType >::setCellValues().
virtual Type interpolate (const barycentric & coordinates, const tetIndices & tetIs, const label facei = -1) const inline virtual
Interpolate field to the given coordinates in the tetrahedron.
defined by the given indices. Calls interpolate function above here except where overridden by derived interpolation types.
Reimplemented in interpolationCellPoint< Type >, interpolationCellPoint< scalar >, interpolationCellPoint< Foam::Vector >, interpolationCellPointWallModified< Type >, interpolationCellPatchConstrained< Type >, interpolationCell< Type >, and interpolationCell< scalar >.
Definition at line 156 of file interpolation.H.
Member Data Documentation
const GeometricField<Type, fvPatchField, volMesh>& psi_ protected
Definition at line 59 of file interpolation.H.
const polyMesh& pMesh_ protected
Definition at line 61 of file interpolation.H.
Referenced by interpolation< Foam::Vector >::psi().
const vectorField& pMeshPoints_ protected
Definition at line 62 of file interpolation.H.
const faceList& pMeshFaces_ protected
Definition at line 63 of file interpolation.H.
const vectorField& pMeshFaceCentres_ protected
Definition at line 64 of file interpolation.H.
const vectorField& pMeshFaceAreas_ protected
Definition at line 65 of file interpolation.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fields/fvPatchFields/derived/mappedField/mappedPatchFieldBase.H
src/finiteVolume/interpolation/interpolation/interpolation/interpolation.H
src/finiteVolume/interpolation/interpolation/interpolation/interpolation.C
src/finiteVolume/interpolation/interpolation/interpolation/interpolationNew.C