OpenFOAM: ensightCase Class Reference
ensightCase Class Reference
Supports writing of ensight cases as well as providing common factory methods to open new files.
Classes
class options
Configuration options for the ensightCase.
Public Member Functions
ensightCase (const fileName &ensightDir, const word &caseName, const options &opts)
Construct from components.
ensightCase (const fileName &ensightDir, const word &caseName, const IOstream::streamFormat format=IOstream::BINARY)
Construct from components with all default options.
~ensightCase ()
Destructor.
const ensightCase::options & option () const
Reference to the case options.
IOstream::streamFormat format () const
The output file format (ascii/binary)
const fileName & path () const
The nominal path to the case file.
const word & mask () const
The output '*' mask.
word padded (const label i) const
Consistent zero-padded integer value.
bool nodeValues () const
Use values per nodes instead of per element.
bool separateCloud () const
Write clouds into their own directory instead in "data" directory.
void nextTime (const scalar t)
Set time for time-set 1, using next available index.
void nextTime (const instant &t)
Set time for time-set 1, using next available index.
void setTime (const scalar t, const label index)
Set current index and time for time-set 1.
void setTime (const instant &t, const label index)
Set current index and time for time-set 1.
autoPtr< ensightGeoFile > newGeometry (const bool moving=false) const
Open stream for new geometry file (on master).
autoPtr< ensightFile > newCloud (const word &cloudName) const
Open stream for new cloud positions (on master).
template<class Type >
autoPtr< ensightFile > newData (const word &varName) const
Open stream for new data file (on master), with current index.
template<class Type >
autoPtr< ensightFile > newCloudData (const word &cloudName, const word &varName) const
Open stream for new cloud data file (on master), with current index.
void rewind () const
Rewind the output stream (master only).
void write () const
Write the case file.
Ostream & operator() () const
Output stream (master only).
Ostream & printInfo (Ostream &os) const
Print some general information.
template<class Type >
Foam::autoPtr< Foam::ensightFile > newData (const word &name) const
template<class Type >
Foam::autoPtr< Foam::ensightFile > newCloudData (const word &cloudName, const word &name) const
Static Public Attributes
static const char * dataDirName = "data"
The name for "data" subdirectory.
static const char * geometryName = "geometry"
The name for geometry files.
Detailed Description
Supports writing of ensight cases as well as providing common factory methods to open new files.
Source files
ensightCase.H
ensightCase.C
Definition at line 59 of file ensightCase.H.
Constructor & Destructor Documentation
ensightCase (const fileName & ensightDir, const word & caseName, const options & opts)
Construct from components.
Definition at line 377 of file ensightCase.C.
ensightCase (const fileName & ensightDir, const word & caseName, const IOstream::streamFormat format = IOstream::BINARY)
Construct from components with all default options.
Definition at line 401 of file ensightCase.C.
~ensightCase ()
Destructor.
Definition at line 426 of file ensightCase.C.
Member Function Documentation
const Foam::ensightCase::options & option () const inline
Reference to the case options.
Definition at line 23 of file ensightCaseI.H.
Foam::IOstream::streamFormat format () const inline
The output file format (ascii/binary)
Definition at line 29 of file ensightCaseI.H.
const Foam::fileName & path () const inline
The nominal path to the case file.
Definition at line 35 of file ensightCaseI.H.
const Foam::word & mask () const inline
The output '*' mask.
Definition at line 41 of file ensightCaseI.H.
Foam::word padded (const label i) const inline
Consistent zero-padded integer value.
Definition at line 47 of file ensightCaseI.H.
Referenced by ensightCase::newData().
bool nodeValues () const inline
Use values per nodes instead of per element.
Definition at line 53 of file ensightCaseI.H.
bool separateCloud () const inline
Write clouds into their own directory instead in "data" directory.
Definition at line 59 of file ensightCaseI.H.
void nextTime (const scalar t)
Set time for time-set 1, using next available index.
Create corresponding sub-directory. Do not mix between nextTime and setTime in an application.
Definition at line 435 of file ensightCase.C.
void nextTime (const instant & t)
Set time for time-set 1, using next available index.
Create corresponding sub-directory. Do not mix between nextTime and setTime in an application.
Definition at line 442 of file ensightCase.C.
References setTime().
void setTime (const scalar t, const label index)
Set current index and time for time-set 1.
Create corresponding sub-directory
Note
do not mix between nextTime and setTime in an application.
Definition at line 448 of file ensightCase.C.
References Instant< T >::value().
void setTime (const instant & t, const label index)
Set current index and time for time-set 1.
Create corresponding sub-directory
Note
do not mix between nextTime and setTime in an application.
Definition at line 473 of file ensightCase.C.
Foam::autoPtr< Foam::ensightGeoFile > newGeometry (const bool moving = false) const
Open stream for new geometry file (on master).
Definition at line 673 of file ensightCase.C.
Foam::autoPtr< Foam::ensightFile > newCloud (const word & cloudName) const
Open stream for new cloud positions (on master).
Note the use of ensightFile, not ensightGeoFile.
Definition at line 707 of file ensightCase.C.
autoPtr<ensightFile> newData (const word & varName) const
Open stream for new data file (on master), with current index.
Referenced by Foam::writeVolField(), and ensightWrite::writeVolFields().
autoPtr<ensightFile> newCloudData (const word & cloudName, const word & varName) const
Open stream for new cloud data file (on master), with current index.
void rewind () const
Rewind the output stream (master only).
Definition at line 731 of file ensightCase.C.
void write () const
Write the case file.
Definition at line 479 of file ensightCase.C.
References setTime(), and Instant< T >::value().
Foam::Ostream & operator() () const inline
Output stream (master only).
Definition at line 67 of file ensightCaseI.H.
Foam::Ostream & printInfo (Ostream & os) const
Print some general information.
Definition at line 740 of file ensightCase.C.
Foam::autoPtr<Foam::ensightFile> newData (const word & name) const
Definition at line 29 of file ensightCaseTemplates.C.
References UPstream::master(), and ensightCase::padded().
Foam::autoPtr<Foam::ensightFile> newCloudData (const word & cloudName, const word & name) const
Definition at line 62 of file ensightCaseTemplates.C.
Member Data Documentation
const char * dataDirName = "data" static
The name for "data" subdirectory.
Definition at line 64 of file ensightCase.H.
const char * geometryName = "geometry" static
The name for geometry files.
Definition at line 76 of file ensightCase.H.
The documentation for this class was generated from the following files:
src/fileFormats/ensight/file/ensightCase.H
src/fileFormats/ensight/file/ensightCase.C
src/fileFormats/ensight/file/ensightCaseI.H
src/fileFormats/ensight/file/ensightCaseTemplates.C