OpenFOAM: refinementParameters Class Reference
refinementParameters Class Reference
Simple container to keep together refinement specific information.
Public Member Functions
refinementParameters (const dictionary &dict, const bool dryRun=false)
Construct from dictionary - new syntax.
label maxGlobalCells () const
Total number of cells.
label maxLocalCells () const
Per processor max number of cells.
label minRefineCells () const
When to stop refining.
scalar curvature () const
Curvature.
scalar planarAngle () const
Angle when two intersections are considered to be planar.
label nBufferLayers () const
Number of layers between different refinement levels.
const pointField & locationsInMesh () const
Areas to keep.
const wordList & zonesInMesh () const
Per area the zone name.
const pointField & locationsOutsideMesh () const
Optional points which are checked to be outside the mesh.
bool allowFreeStandingZoneFaces () const
Are zone faces allowed only inbetween different cell zones.
bool useTopologicalSnapDetection () const
Use old topology based problem-cell removal.
scalar maxLoadUnbalance () const
Allowed load unbalance.
bool handleSnapProblems () const
bool interfaceRefine () const
Refine cell with opposite faces with different refinement level.
label nErodeCellZone () const
Number of iterations of erosion to get a consistent cellZone.
label nFilterIter () const
Number of iterations of infill/erosion to get a smoother.
dictionary getZoneInfo (const word &fzName, surfaceZonesInfo::faceZoneType &faceType) const
Get patchInfo and faceType for faceZone.
labelList addCellZonesToMesh (polyMesh &) const
Add cellZones to mesh. Return indices of cellZones (or -1)
Static Public Member Functions
static labelList findCells (const bool checkInsideMesh, const polyMesh &, const pointField &locations)
Checks that cells are in mesh. Returns cells (or -1) they.
static labelList zonedLocations (const wordList &zonesInMesh)
Extract indices of named locations (so excludes 'keepPoints')
static labelList unzonedLocations (const wordList &zonesInMesh)
Extract indices of unnamed locations ('keepPoints')
Detailed Description
Simple container to keep together refinement specific information.
Source files
refinementParameters.H
refinementParameters.C
Definition at line 54 of file refinementParameters.H.
Constructor & Destructor Documentation
refinementParameters (const dictionary & dict, const bool dryRun = false)
Construct from dictionary - new syntax.
Definition at line 33 of file refinementParameters.C.
References List< T >::append(), Foam::cos(), Foam::degToRad(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, UList< T >::first(), forAll, dictionary::found(), get< scalar >(), i, IOWarningInFunction, dictionary::lookup(), word::null, nZones, dictionary::readIfPresent(), List< T >::setSize(), and UList< T >::size().
Member Function Documentation
label maxGlobalCells () const inline
Total number of cells.
Definition at line 172 of file refinementParameters.H.
label maxLocalCells () const inline
Per processor max number of cells.
Definition at line 180 of file refinementParameters.H.
label minRefineCells () const inline
When to stop refining.
Definition at line 188 of file refinementParameters.H.
scalar curvature () const inline
Curvature.
Definition at line 196 of file refinementParameters.H.
scalar planarAngle () const inline
Angle when two intersections are considered to be planar.
Definition at line 204 of file refinementParameters.H.
label nBufferLayers () const inline
Number of layers between different refinement levels.
Definition at line 212 of file refinementParameters.H.
const pointField& locationsInMesh () const inline
Areas to keep.
Definition at line 220 of file refinementParameters.H.
const wordList& zonesInMesh () const inline
Per area the zone name.
Definition at line 228 of file refinementParameters.H.
const pointField& locationsOutsideMesh () const inline
Optional points which are checked to be outside the mesh.
Definition at line 236 of file refinementParameters.H.
bool allowFreeStandingZoneFaces () const inline
Are zone faces allowed only inbetween different cell zones.
or also just free standing?
Definition at line 246 of file refinementParameters.H.
bool useTopologicalSnapDetection () const inline
Use old topology based problem-cell removal.
(cells with 8 points on surface)
Definition at line 256 of file refinementParameters.H.
scalar maxLoadUnbalance () const inline
Allowed load unbalance.
Definition at line 264 of file refinementParameters.H.
bool handleSnapProblems () const inline
Definition at line 269 of file refinementParameters.H.
bool interfaceRefine () const inline
Refine cell with opposite faces with different refinement level.
Definition at line 277 of file refinementParameters.H.
label nErodeCellZone () const inline
Number of iterations of erosion to get a consistent cellZone.
Definition at line 285 of file refinementParameters.H.
label nFilterIter () const inline
Number of iterations of infill/erosion to get a smoother.
blockage
Definition at line 295 of file refinementParameters.H.
Foam::dictionary getZoneInfo (const word & fzName, surfaceZonesInfo::faceZoneType & faceType) const
Get patchInfo and faceType for faceZone.
Definition at line 151 of file refinementParameters.C.
Foam::labelList addCellZonesToMesh (polyMesh & mesh) const
Add cellZones to mesh. Return indices of cellZones (or -1)
Definition at line 180 of file refinementParameters.C.
Foam::labelList findCells (const bool checkInsideMesh, const polyMesh & mesh, const pointField & locations) static
Checks that cells are in mesh. Returns cells (or -1) they.
are in.
Definition at line 202 of file refinementParameters.C.
Foam::labelList zonedLocations (const wordList & zonesInMesh) static
Extract indices of named locations (so excludes 'keepPoints')
Definition at line 262 of file refinementParameters.C.
Foam::labelList unzonedLocations (const wordList & zonesInMesh) static
Extract indices of unnamed locations ('keepPoints')
Definition at line 284 of file refinementParameters.C.
The documentation for this class was generated from the following files:
src/mesh/snappyHexMesh/snappyHexMeshDriver/refinementParameters/refinementParameters.H
src/mesh/snappyHexMesh/snappyHexMeshDriver/refinementParameters/refinementParameters.C