OpenFOAM: nutUTabulatedWallFunctionFvPatchScalarField Class Reference
nutUTabulatedWallFunctionFvPatchScalarField Class Reference
Wall functions
This boundary condition provides a wall constraint on the turbulent kinematic viscosity, i.e. nut, when using wall functions, based on velocity, i.e. U.
Public Member Functions
TypeName ("nutTabulatedWallFunction")
Runtime type information.
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given nutUTabulatedWallFunctionFvPatchScalarField onto a new patch.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > yPlus () const
Calculate and return the yPlus at the boundary.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from nutWallFunctionFvPatchScalarField
TypeName ("nutWallFunction")
Runtime type information.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
nutWallFunctionFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given nutWallFunctionFvPatchScalarField onto a new patch.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &)
Construct as copy.
nutWallFunctionFvPatchScalarField (const nutWallFunctionFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
scalar Cmu () const
Return Cmu.
scalar kappa () const
Return kappa.
scalar E () const
Return E.
scalar yPlusLam () const
Return the y+ at the edge of the viscous sublayer.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
Protected Member Functions
virtual tmp< scalarField > calcNut () const
Calculate the turbulence viscosity.
virtual tmp< scalarField > calcUPlus (const scalarField &Rey) const
Calculate wall u+ from table.
Protected Member Functions inherited from nutWallFunctionFvPatchScalarField
virtual const volVectorField & U (const turbulenceModel &turb) const
Helper to return the velocity field either from the turbulence model (default) or the mesh database.
virtual void checkType ()
Check the type of the patch.
virtual void writeLocalEntries (Ostream &) const
Write local wall function variables.
Protected Attributes
word uPlusTableName_
Name of u+ table.
uniformInterpolationTable< scalar > uPlusTable_
u+ table
Protected Attributes inherited from nutWallFunctionFvPatchScalarField
word UName_
Name of velocity field.
scalar Cmu_
Cmu coefficient.
scalar kappa_
Von Karman constant.
scalar E_
E coefficient.
scalar yPlusLam_
Estimated y+ value at the edge of the viscous sublayer.
Additional Inherited Members
Static Public Member Functions inherited from nutWallFunctionFvPatchScalarField
static const
nutWallFunctionFvPatchScalarField & nutw (const turbulenceModel &turbModel, const label patchi)
Return the nut patchField for the given wall patch.
static scalar yPlusLam (const scalar kappa, const scalar E)
Calculate the y+ at the edge of the viscous sublayer.
Detailed Description
This boundary condition provides a wall constraint on the turbulent kinematic viscosity, i.e. nut, when using wall functions, based on velocity, i.e. U.
As input, the user specifies a look-up table of U+ as a function of near-wall Reynolds number.
The table should be located in the $FOAM_CASE/constant directory.
Usage
Property Description Required Default value
uPlusTable U+ as a function of Re table name yes
Cmu Model coefficient no 0.09
kappa Von Karman constant no 0.41
E Model coefficient no 9.8
Example of the boundary condition specification:
    <patchName>
    {
        // Mandatory entries
        type            nutTabulatedWallFunction;
        uPlusTable      myUPlusTable;
        // Optional entries
    }
Note
The tables are not registered since the same table object may be used for more than one patch.
See Also
Foam::nutWallFunctionFvPatchScalarField
Source files
nutUTabulatedWallFunctionFvPatchScalarField.H
nutUTabulatedWallFunctionFvPatchScalarField.C
Definition at line 111 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
Constructor & Destructor Documentation
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 84 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 124 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given nutUTabulatedWallFunctionFvPatchScalarField onto a new patch.
Definition at line 109 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & wfpsf)
Construct as copy.
Definition at line 150 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
nutUTabulatedWallFunctionFvPatchScalarField (const nutUTabulatedWallFunctionFvPatchScalarField & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 162 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
Member Function Documentation
Foam::tmp< Foam::scalarField > calcNut () const protected virtual
Calculate the turbulence viscosity.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 32 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), nutUTabulatedWallFunctionFvPatchScalarField::calcUPlus(), Foam::constant::atomic::group, IOobject::groupName(), Foam::mag(), magUp, Foam::max(), turbulenceModel::nu(), Foam::foamVersion::patch, fvPatchField< Type >::patchInternalField(), turbulenceModel::propertiesName, fvPatchField< Type >::snGrad(), Foam::sqr(), nutWallFunctionFvPatchScalarField::U(), y, and turbulenceModel::y().
Foam::tmp< Foam::scalarField > calcUPlus (const scalarField & Rey) const protected virtual
Calculate wall u+ from table.
Definition at line 64 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
Referenced by nutUTabulatedWallFunctionFvPatchScalarField::calcNut().
TypeName ("nutTabulatedWallFunction")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 196 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 217 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
Foam::tmp< Foam::scalarField > yPlus () const virtual
Calculate and return the yPlus at the boundary.
Implements nutWallFunctionFvPatchScalarField.
Definition at line 176 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
void write (Ostream & os) const virtual
Write.
Reimplemented from nutWallFunctionFvPatchScalarField.
Definition at line 200 of file nutUTabulatedWallFunctionFvPatchScalarField.C.
Member Data Documentation
word uPlusTableName_ protected
Name of u+ table.
Definition at line 122 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
uniformInterpolationTable<scalar> uPlusTable_ protected
u+ table
Definition at line 127 of file nutUTabulatedWallFunctionFvPatchScalarField.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUTabulatedWallFunction/nutUTabulatedWallFunctionFvPatchScalarField.H
src/TurbulenceModels/turbulenceModels/derivedFvPatchFields/wallFunctions/nutWallFunctions/nutUTabulatedWallFunction/nutUTabulatedWallFunctionFvPatchScalarField.C