OpenFOAM: pointToPointPlanarInterpolation Class Reference
pointToPointPlanarInterpolation Class Reference
Interpolates between two sets of unstructured points using 2D Delaunay triangulation. Used in e.g. timeVaryingMapped bcs.
Public Member Functions
ClassName ("pointToPointPlanarInterpolation")
pointToPointPlanarInterpolation (const pointField &sourcePoints, const pointField &destPoints, const scalar perturb, const bool nearestOnly=false)
Construct from 3D locations. Determines local coordinate system.
pointToPointPlanarInterpolation (const coordinateSystem &referenceCS, const pointField &sourcePoints, const pointField &destPoints, const scalar perturb)
Construct from coordinate system and locations.
pointToPointPlanarInterpolation (const scalar perturb, const bool nearestOnly, const coordinateSystem &referenceCS, const label sourceSize, const List< FixedList< label, 3 >> &nearestVertex, const List< FixedList< scalar, 3 >> &nearestVertexWeight)
Construct from components.
autoPtr
< pointToPointPlanarInterpolation > clone () const
Construct and return a clone.
scalar perturb () const
Perturbation factor (for triangulation)
bool nearestOnly () const
Whether to use nearest point only (avoids triangulation, projection)
const coordSystem::cartesian & referenceCS () const
Return the Cartesian reference coordinate system.
label sourceSize () const
Number of source points.
const List< FixedList< label, 3 > > & nearestVertex () const
const List< FixedList< scalar, 3 > > & nearestVertexWeight () const
Current interpolation factors to face centres of underlying.
template<class Type >
tmp< Field< Type > > interpolate (const Field< Type > &sourceFld) const
Interpolate from field on source points to dest points.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const Field< Type > &sourceFld) const
Static Public Member Functions
static wordList timeNames (const instantList &)
Helper: extract words of times.
static bool findTime (const instantList &times, const label startSampleTime, const scalar timeVal, label &lo, label &hi)
Helper: find time. Return true if successful.
Detailed Description
Interpolates between two sets of unstructured points using 2D Delaunay triangulation. Used in e.g. timeVaryingMapped bcs.
Source files
pointToPointPlanarInterpolation.H
pointToPointPlanarInterpolation.C
Definition at line 49 of file pointToPointPlanarInterpolation.H.
Constructor & Destructor Documentation
pointToPointPlanarInterpolation (const pointField & sourcePoints, const pointField & destPoints, const scalar perturb, const bool nearestOnly = false)
Construct from 3D locations. Determines local coordinate system.
from sourcePoints and maps onto that. If nearestOnly skips any local coordinate system and triangulation and uses nearest vertex only
Definition at line 314 of file pointToPointPlanarInterpolation.C.
pointToPointPlanarInterpolation (const coordinateSystem & referenceCS, const pointField & sourcePoints, const pointField & destPoints, const scalar perturb)
Construct from coordinate system and locations.
Definition at line 335 of file pointToPointPlanarInterpolation.C.
pointToPointPlanarInterpolation (const scalar perturb, const bool nearestOnly, const coordinateSystem & referenceCS, const label sourceSize, const List< FixedList< label, 3 >> & nearestVertex, const List< FixedList< scalar, 3 >> & nearestVertexWeight)
Construct from components.
Definition at line 352 of file pointToPointPlanarInterpolation.C.
Member Function Documentation
ClassName ("pointToPointPlanarInterpolation")
Foam::autoPtr< Foam::pointToPointPlanarInterpolation > clone () const
Construct and return a clone.
Definition at line 371 of file pointToPointPlanarInterpolation.C.
scalar perturb () const inline
Perturbation factor (for triangulation)
Definition at line 163 of file pointToPointPlanarInterpolation.H.
bool nearestOnly () const inline
Whether to use nearest point only (avoids triangulation, projection)
Definition at line 171 of file pointToPointPlanarInterpolation.H.
const coordSystem::cartesian& referenceCS () const inline
Return the Cartesian reference coordinate system.
Definition at line 179 of file pointToPointPlanarInterpolation.H.
label sourceSize () const inline
Number of source points.
Definition at line 187 of file pointToPointPlanarInterpolation.H.
const List<FixedList<label, 3> >& nearestVertex () const inline
Definition at line 193 of file pointToPointPlanarInterpolation.H.
const List<FixedList<scalar, 3> >& nearestVertexWeight () const inline
Current interpolation factors to face centres of underlying.
patch
Definition at line 203 of file pointToPointPlanarInterpolation.H.
Foam::wordList timeNames (const instantList & times) static
Helper: extract words of times.
Definition at line 388 of file pointToPointPlanarInterpolation.C.
bool findTime (const instantList & times, const label startSampleTime, const scalar timeVal, label & lo, label & hi) static
Helper: find time. Return true if successful.
Definition at line 403 of file pointToPointPlanarInterpolation.C.
tmp<Field<Type> > interpolate (const Field< Type > & sourceFld) const
Interpolate from field on source points to dest points.
Foam::tmp<Foam::Field<Type> > interpolate (const Field< Type > & sourceFld) const
Definition at line 27 of file pointToPointPlanarInterpolationTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld, forAll, i, tmp< T >::ref(), and UList< Type >::size().
The documentation for this class was generated from the following files:
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolation.H
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolation.C
src/meshTools/triSurface/triSurfaceTools/pointToPointPlanarInterpolationTemplates.C