OpenFOAM: eRefConstThermo< EquationOfState > Class Template Reference
eRefConstThermo< EquationOfState > Class Template Reference
Constant properties thermodynamics package templated into the EquationOfState.
Public Member Functions
eRefConstThermo (const dictionary &dict)
Construct from dictionary.
eRefConstThermo (const word &, const eRefConstThermo &)
Construct as named copy.
autoPtr< eRefConstThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar Cv (const scalar p, const scalar T) const
Heat capacity at constant volume [J/(kg K)].
scalar Es (const scalar p, const scalar T) const
Sensible internal energy [J/kg].
scalar Ea (const scalar p, const scalar T) const
Absolute internal energy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar dGdT (const scalar p, const scalar T) const
Derivative of Gibbs free energy w.r.t. temperature.
scalar dCpdT (const scalar p, const scalar T) const
Temperature derivative of heat capacity at constant pressure.
void write (Ostream &os) const
Write to Ostream.
void operator+= (const eRefConstThermo &)
Static Public Member Functions
static autoPtr< eRefConstThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
eRefConstThermo operator+ (const eRefConstThermo &, const eRefConstThermo &)
eRefConstThermo operator* (const scalar, const eRefConstThermo &)
eRefConstThermo operator== (const eRefConstThermo &, const eRefConstThermo &)
Ostream & operator (Ostream &, const eRefConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::eRefConstThermo< EquationOfState >
Constant properties thermodynamics package templated into the EquationOfState.
Source files
eRefConstThermo.H
eRefConstThermoI.H
eRefConstThermo.C
Definition at line 44 of file eRefConstThermo.H.
Constructor & Destructor Documentation
eRefConstThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 27 of file eRefConstThermo.C.
eRefConstThermo (const word & name, const eRefConstThermo< EquationOfState > & ct) inline
Construct as named copy.
Definition at line 45 of file eRefConstThermoI.H.
Member Function Documentation
Foam::autoPtr< Foam::eRefConstThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 60 of file eRefConstThermoI.H.
Foam::autoPtr< Foam::eRefConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 71 of file eRefConstThermoI.H.
static word typeName () inline static
Return the instantiated type name.
Definition at line 137 of file eRefConstThermo.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 84 of file eRefConstThermoI.H.
Foam::scalar Cv (const scalar p, const scalar T) const inline
Heat capacity at constant volume [J/(kg K)].
Definition at line 94 of file eRefConstThermoI.H.
References T.
Foam::scalar Es (const scalar p, const scalar T) const inline
Sensible internal energy [J/kg].
Definition at line 105 of file eRefConstThermoI.H.
References Cv.
Foam::scalar Ea (const scalar p, const scalar T) const inline
Absolute internal energy [J/kg].
Definition at line 122 of file eRefConstThermoI.H.
References Hf_().
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 114 of file eRefConstThermoI.H.
References T.
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 132 of file eRefConstThermoI.H.
References Es().
Foam::scalar dGdT (const scalar p, const scalar T) const inline
Derivative of Gibbs free energy w.r.t. temperature.
Definition at line 142 of file eRefConstThermoI.H.
References Cp, Foam::log(), and Foam::constant::standard::Tstd.
Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Temperature derivative of heat capacity at constant pressure.
Definition at line 152 of file eRefConstThermoI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 40 of file eRefConstThermo.C.
void operator+= (const eRefConstThermo< EquationOfState > &) inline
Definition at line 164 of file eRefConstThermoI.H.
Friends And Related Function Documentation
eRefConstThermo operator+ (const eRefConstThermo< EquationOfState > & , const eRefConstThermo< EquationOfState > &) friend
eRefConstThermo operator* (const scalar , const eRefConstThermo< EquationOfState > &) friend
eRefConstThermo operator== (const eRefConstThermo< EquationOfState > & , const eRefConstThermo< EquationOfState > &) friend
Ostream& operator (Ostream & , const eRefConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/eRefConst/eRefConstThermo.H
src/thermophysicalModels/specie/thermo/eRefConst/eRefConstThermo.C
src/thermophysicalModels/specie/thermo/eRefConst/eRefConstThermoI.H