OpenFOAM: pointBitSet Class Reference
pointBitSet Class Reference
A special purpose topoSet with the point labels stored as a bitSet. It does not correspond to a pointSet either (no associated IOobject).
Public Member Functions
TypeName ("pointBitSet")
Runtime type information.
pointBitSet (const polyMesh &mesh)
Construct with nPoints elements, all elements unset.
pointBitSet (const polyMesh &mesh, const bool val)
Construct with nPoints elements, using initial val.
pointBitSet (const polyMesh &mesh, const bitSet &bits)
Copy construct from bitset, resizing to nPoints elements as required.
pointBitSet (const polyMesh &mesh, bitSet &&bits)
Move construct from bitset, resizing to nPoints elements as required.
virtual ~pointBitSet ()=default
Destructor.
virtual void sync (const polyMesh &mesh)
Sync pointBitSet across coupled patches.
virtual label maxSize (const polyMesh &mesh) const
Return max index+1.
virtual void updateMesh (const mapPolyMesh &morphMap)
Update any stored data for new labels.
virtual void distribute (const mapDistributePolyMesh &map)
Update any stored data for mesh redistribution.
virtual void writeDebug (Ostream &os, const primitiveMesh &mesh, const label maxLen) const
Write maxLen items with label and coordinates.
Public Member Functions inherited from topoBitSet
virtual ~topoBitSet ()=default
Destructor.
const bitSet & addressing () const
Return the bitSet.
bitSet & addressing ()
Access the bitSet.
void reset ()
Set values to false, leaving the size untouched.
virtual bool found (const label id) const
Has the given index?
virtual bool set (const label id)
Set an index.
virtual bool unset (const label id)
Unset an index.
virtual void set (const labelUList &labels)
Set multiple indices.
virtual void unset (const labelUList &labels)
Unset multiple indices.
virtual void invert (const label maxLen)
Invert contents.
virtual void subset (const topoSet &set)
Subset contents. Only elements present in both sets remain.
virtual void addSet (const topoSet &set)
Add elements present in set.
virtual void subtractSet (const topoSet &set)
Subtract elements present in set.
Public Member Functions inherited from topoSet
TypeName ("topoSet")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSet, word,(const polyMesh &mesh, const word &name, readOption r, writeOption w),(mesh, name, r, w))
declareRunTimeSelectionTable (autoPtr, topoSet, size,(const polyMesh &mesh, const word &name, const label size, writeOption w),(mesh, name, size, w))
declareRunTimeSelectionTable (autoPtr, topoSet, set,(const polyMesh &mesh, const word &name, const topoSet &set, writeOption w),(mesh, name, set, w))
topoSet (const IOobject &obj, const word &wantedType)
Construct from IOobject as explicitly passed type.
topoSet (const polyMesh &mesh, const word &wantedType, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Construct from polyMesh and name.
topoSet (const polyMesh &mesh, const word &name, const label size, writeOption w=NO_WRITE)
Construct empty from additional size of labelHashSet.
topoSet (const polyMesh &mesh, const word &name, const labelHashSet &labels, writeOption w=NO_WRITE)
Construct (no-read) with copy of labelHashSet.
topoSet (const polyMesh &mesh, const word &name, labelHashSet &&labels, writeOption w=NO_WRITE)
Construct (no-read) with moving labelHashSet.
topoSet (const polyMesh &mesh, const word &name, const labelUList &labels, writeOption w=NO_WRITE)
Construct (no-read) with copy of labels.
topoSet (const IOobject &io, const label size)
Construct empty from IOobject and HashSet size.
topoSet (const IOobject &io, const labelHashSet &labels)
Construct from IOobject and copy of labelHashSet.
topoSet (const IOobject &io, labelHashSet &&labels)
Construct from IOobject and move labelHashSet.
autoPtr< topoSet > clone () const
Clone.
virtual ~topoSet ()=default
Destructor.
virtual void writeDebug (Ostream &os, const label maxLen) const
Write labels columnwise to os. Truncate to maxLen.
virtual bool writeData (Ostream &) const
Write contents.
void operator= (const topoSet &)
Copy labelHashSet part only.
virtual void deleteSet (const topoSet &set)
Deprecated(2018-10) subtract elements present in set.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Public Member Functions inherited from HashSet< Key, Hash >
HashSet ()
Construct null with default (128) table capacity.
HashSet (const label size)
Construct given initial table capacity.
HashSet (Istream &is)
Construct from Istream with default table capacity.
template<unsigned N>
HashSet (const FixedList< Key, N > &list)
Construct from FixedList of Key.
HashSet (const UList< Key > &list)
Construct from UList of Key.
template<class Addr >
HashSet (const IndirectListBase< Key, Addr > &list)
Construct from an indirect list.
HashSet (std::initializer_list< Key > list)
Construct from an initializer list of Key.
HashSet (const this_type &hs)
Copy construct.
HashSet (this_type &&hs)
Move construct.
template<class AnyType , class AnyHash >
HashSet (const HashTable< AnyType, Key, AnyHash > &tbl)
Construct from the keys of another HashTable, the type of values held is arbitrary.
bool test (const Key &key) const
Same as found() - return true if key exists in the set.
bool insert (const Key &key)
Insert a new entry, not overwriting existing entries.
bool set (const Key &key)
Same as insert (no value to overwrite)
bool unset (const Key &key)
Unset the specified key - same as erase.
template<class InputIter >
label insert (InputIter first, InputIter last)
Insert keys from the input iterator range.
label insert (std::initializer_list< Key > list)
Insert keys from a initializer list of Key.
template<unsigned N>
label insert (const FixedList< Key, N > &list)
Insert keys from the list of Key.
label insert (const UList< Key > &list)
Insert keys from the list of Key.
template<class Addr >
label insert (const IndirectListBase< Key, Addr > &list)
Insert keys from the list of Key.
template<class InputIter >
label set (InputIter first, InputIter last)
Same as insert (no value to overwrite)
label set (std::initializer_list< Key > list)
Same as insert (no value to overwrite)
template<unsigned N>
label set (const FixedList< Key, N > &list)
Same as insert (no value to overwrite)
label set (const UList< Key > &list)
Same as insert (no value to overwrite)
template<class Addr >
label set (const IndirectListBase< Key, Addr > &list)
Same as insert (no value to overwrite)
template<class InputIter >
label setMany (InputIter first, InputIter last)
Same as insert (no value to overwrite)
template<class InputIter >
label unset (InputIter first, InputIter last)
Unset the keys listed in the input iterator range.
label unset (std::initializer_list< Key > list)
Unset the listed keys - same as erase.
template<unsigned N>
label unset (const FixedList< Key, N > &list)
Unset the listed keys - same as erase.
label unset (const UList< Key > &list)
Unset the listed keys - same as erase.
template<class Addr >
label unset (const IndirectListBase< Key, Addr > &list)
Unset the listed keys - same as erase.
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
const iterator & end ()
const const_iterator & end () const
const const_iterator & cend () const
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
bool operator() (const Key &key) const
Return true if the entry exists, same as found()
bool operator[] (const Key &key) const
Return true if the entry exists, same as found().
void operator= (const this_type &rhs)
Copy assignment.
void operator= (this_type &&rhs)
Move assignment.
bool operator== (const this_type &rhs) const
Sets are equal if all keys are equal, independent of order or underlying storage size.
bool operator!= (const this_type &rhs) const
The opposite of the equality operation.
void operator= (const UList< Key > &rhs)
Assignment from a UList of keys.
template<unsigned N>
void operator= (const FixedList< Key, N > &rhs)
Assignment from a FixedList of keys.
void operator= (std::initializer_list< Key > rhs)
Assignment from an initializer list of keys.
this_type & operator|= (const this_type &rhs)
Add entries to this HashSet.
this_type & operator&= (const this_type &rhs)
Only retain entries found in both HashSets.
this_type & operator^= (const this_type &rhs)
Only retain unique entries (xor)
this_type & operator+= (const this_type &rhs)
Add entries to this HashSet.
this_type & operator-= (const this_type &rhs)
Remove entries from this HashSet.
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class UnaryPredicate >
label countValues (const UnaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class InputIter >
Foam::label assignMany (const label nItems, InputIter first, InputIter last)
template<class InputIter>
Foam::label insert (InputIter first, InputIter last)
template<unsigned N>
Foam::label insert (const FixedList< Key, N > &list)
template<class Addr>
Foam::label insert (const IndirectListBase< Key, Addr > &list)
template<class InputIter>
Foam::label unset (InputIter first, InputIter last)
template<unsigned N>
Foam::label unset (const FixedList< Key, N > &list)
template<class Addr>
Foam::label unset (const IndirectListBase< Key, Addr > &list)
Public Member Functions inherited from HashTable< zero::null, Key, Hash >
HashTable ()
Construct null with default (128) table capacity.
HashTable (const label size)
Construct given initial table capacity.
HashTable (Istream &is, const label size=128)
Construct from Istream with default table capacity.
HashTable (const this_type &ht)
Copy construct.
HashTable (this_type &&rhs)
Move construct.
HashTable (std::initializer_list< std::pair< Key, zero::null >> list)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const noexcept
The size of the underlying table.
label size () const noexcept
The number of elements in table.
bool empty () const noexcept
True if the hash table is empty.
zero::null & at (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const zero::null & at (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
bool found (const Key &key) const
Return true if hashed entry is found in table.
iterator find (const Key &key)
Find and return an iterator set at the hashed entry.
const_iterator find (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const_iterator cfind (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const zero::null & lookup (const Key &key, const zero::null &deflt) const
Return hashed entry if it exists, or return the given default.
List< Key > toc () const
The table of contents (the keys) in unsorted order.
List< Key > sortedToc () const
The table of contents (the keys) in sorted order.
List< Key > sortedToc (const Compare &comp) const
The table of contents (the keys) sorted according to the specified comparator.
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the keys.
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the values.
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the binary predicate applied to the keys and values.
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Count the number of keys that satisfy the unary predicate.
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Count the number of values that satisfy the unary predicate.
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Count the number of entries that satisfy the binary predicate.
bool emplace (const Key &key, Args &&...args)
Emplace insert a new entry, not overwriting existing entries.
bool insert (const Key &key, const zero::null &obj)
Copy insert a new entry, not overwriting existing entries.
bool insert (const Key &key, zero::null &&obj)
Move insert a new entry, not overwriting existing entries.
bool set (const Key &key, const zero::null &obj)
Copy assign a new entry, overwriting existing entries.
bool set (const Key &key, zero::null &&obj)
Move assign a new entry, overwriting existing entries.
bool erase (const iterator &iter)
Erase an entry specified by given iterator.
bool erase (const Key &key)
Erase an entry specified by the given key.
label erase (const HashTable< AnyType, Key, AnyHash > &other)
Remove table entries given by keys of the other hash-table.
label erase (std::initializer_list< Key > keys)
Remove table entries given by the listed keys.
label erase (InputIter first, InputIter last)
Remove multiple entries using an iterator range of keys.
label erase (const FixedList< Key, N > &keys)
Remove table entries given by the listed keys.
label erase (const UList< Key > &keys)
Remove table entries given by the listed keys.
label retain (const HashTable< AnyType, Key, AnyHash > &other)
Retain table entries given by keys of the other hash-table.
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their keys.
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their values.
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their key/value.
void resize (const label sz)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void swap (HashTable< zero::null, Key, Hash > &rhs)
Swap contents into this table.
void transfer (HashTable< zero::null, Key, Hash > &rhs)
Transfer contents into this table.
zero::null & operator[] (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const zero::null & operator[] (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
zero::null & operator() (const Key &key)
Return existing entry or create a new entry.
zero::null & operator() (const Key &key, const zero::null &deflt)
Return existing entry or insert a new entry.
void operator= (const this_type &rhs)
Copy assign.
void operator= (std::initializer_list< std::pair< Key, zero::null >> rhs)
Copy assign from an initializer list.
void operator= (this_type &&rhs)
Move assign.
bool operator== (const this_type &rhs) const
Equality. Tables are equal if all keys and values are equal, independent of order or underlying storage size.
bool operator!= (const this_type &rhs) const
The opposite of the equality operation.
this_type & operator+= (const this_type &rhs)
Add entries into this HashTable.
const_iterator_pair
< const_key_iterator,
this_type > keys () const
A const iterator begin/end pair for iterating over keys.
iterator begin ()
iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const iterator & end ()
iterator to signal the end for any HashTable
const const_iterator & end () const
const_iterator to signal the end for any HashTable
const const_iterator & cend () const
const_iterator to signal the end for any HashTable
Ostream & printInfo (Ostream &os) const
Print information.
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
Public Member Functions inherited from HashTableCore
HashTableCore ()=default
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Public Types inherited from HashSet< Key, Hash >
typedef HashSet< Key, Hash > this_type
The template instance used for this HashSet.
typedef HashTable< zero::null,
Key, Hash > parent_type
The template instance used for the parent HashTable.
using iterator = typename parent_type::key_iterator
An iterator, returning reference to the key.
using const_iterator = typename parent_type::const_key_iterator
A const_iterator, returning reference to the key.
Public Types inherited from HashTable< zero::null, Key, Hash >
typedef HashTable< zero::null,
Key, Hash > this_type
The template instance used for this HashTable.
typedef Key key_type
The second template parameter, type of keys used.
typedef zero::null mapped_type
The first template parameter, type of objects contained.
typedef zero::null value_type
Same as mapped_type for OpenFOAM HashTables.
typedef Hash hasher
The third template parameter, the hash index method.
typedef zero::null & reference
Reference to the stored value_type.
typedef const zero::null & const_reference
Const reference to the stored value_type.
typedef label difference_type
The type to represent the difference between two iterators.
typedef label size_type
The type that can represent the size of a HashTable.
using key_iterator = key_iterator_base< iterator >
Forward iterator returning the key.
using const_key_iterator = key_iterator_base< const_iterator >
Forward const iterator returning the key.
Static Public Member Functions inherited from topoSet
static fileName localPath (const polyMesh &mesh, const word &name)
Name of file set will use.
static IOobject findIOobject (const polyMesh &mesh, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Find IOobject in the polyMesh/sets (used as constructor helper)
static IOobject findIOobject (const Time &runTime, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Find IOobject in the polyMesh/sets (used as constructor helper)
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, readOption r=MUST_READ, writeOption w=NO_WRITE)
Return a pointer to a toposet read from file.
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, const label size, writeOption w=NO_WRITE)
Return a pointer to a new toposet of given size.
static autoPtr< topoSet > New (const word &setType, const polyMesh &mesh, const word &name, const topoSet &set, writeOption w=NO_WRITE)
Return a pointer to a new toposet as copy of another toposet.
template<class Container >
static void updateMesh (const fileName &instance, const mapPolyMesh &, Container &)
Helper: call updateMesh on all sets in container (and.
template<class Container >
static void setInstance (const fileName &instance, Container &)
Helper: set instance on all sets in container.
static void removeFiles (const polyMesh &)
Helper: remove all sets files from mesh instance.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Return a canonical (power-of-two) of the requested size.
template<class IteratorType , class TableType >
static IteratorType iterator_begin (TableType &table)
Factory method to create a non-const iterator begin.
template<class IteratorType , class TableType >
static IteratorType iterator_cbegin (const TableType &table)
Factory method to create a const iterator begin.
template<class IteratorType >
static const IteratorType & iterator_end ()
Factory method to return an iterator end.
template<class IteratorType >
static const IteratorType & iterator_cend ()
Factory method to return an iterator cend.
Static Public Attributes inherited from topoSet
static int disallowGenericSets
Debug switch to disallow the use of generic sets.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable internal table size. Approximately labelMax/4.
Protected Member Functions inherited from topoBitSet
virtual void updateLabels (const labelUList &map)
Update map from map.
virtual void check (const label maxSize)
Check limits on addressable range.
topoBitSet (const polyMesh &mesh, const word &setName)
Construct with empty selection.
topoBitSet (const polyMesh &mesh, const word &setName, const label size, const bool val)
Construct with size elements.
topoBitSet (const polyMesh &mesh, const word &setName, const label size, const bitSet &bits)
Copy construct with bitset values, size elements.
topoBitSet (const polyMesh &mesh, const word &setName, const label size, bitSet &&bits)
Move construct with bitset values, size elements.
Protected Member Functions inherited from topoSet
void writeDebug (Ostream &os, const label maxElem, topoSet::const_iterator &iter, label &elemI) const
Write part of contents nicely formatted. Prints labels only.
void writeDebug (Ostream &os, const pointField &coords, const label maxElem, topoSet::const_iterator &iter, label &elemI) const
Write part of contents nicely formatted. Prints label.
void writeDebug (Ostream &os, const pointField &coords, const label maxLen) const
Write labels and coordinates columnwise to os. Truncate to maxLen.
topoSet (const topoSet &)=delete
No copy construct.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Protected Member Functions inherited from HashTable< zero::null, Key, Hash >
bool iterator_erase (node_type *&entry, label &index)
Low-level entry erasure using iterator internals.
Protected Attributes inherited from topoBitSet
bitSet selected_
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
A special purpose topoSet with the point labels stored as a bitSet. It does not correspond to a pointSet either (no associated IOobject).
Source files
pointBitSet.H
pointBitSet.C
Definition at line 47 of file pointBitSet.H.
Constructor & Destructor Documentation
pointBitSet (const polyMesh & mesh) explicit
Construct with nPoints elements, all elements unset.
Definition at line 37 of file pointBitSet.C.
References Foam::defineTypeNameAndDebug().
pointBitSet (const polyMesh & mesh, const bool val)
Construct with nPoints elements, using initial val.
Definition at line 43 of file pointBitSet.C.
pointBitSet (const polyMesh & mesh, const bitSet & bits)
Copy construct from bitset, resizing to nPoints elements as required.
Definition at line 50 of file pointBitSet.C.
pointBitSet (const polyMesh & mesh, bitSet && bits)
Move construct from bitset, resizing to nPoints elements as required.
Definition at line 60 of file pointBitSet.C.
virtual ~pointBitSet () virtual default
Destructor.
Member Function Documentation
TypeName ("pointBitSet")
Runtime type information.
void sync (const polyMesh & mesh) virtual
Sync pointBitSet across coupled patches.
Reimplemented from topoSet.
Definition at line 71 of file pointBitSet.C.
Foam::label maxSize (const polyMesh & mesh) const virtual
Return max index+1.
Implements topoSet.
Definition at line 78 of file pointBitSet.C.
References syncTools::syncPointList().
void updateMesh (const mapPolyMesh & morphMap) virtual
Update any stored data for new labels.
Reimplemented from topoSet.
Definition at line 84 of file pointBitSet.C.
References primitiveMesh::nPoints().
void distribute (const mapDistributePolyMesh & map) virtual
Update any stored data for mesh redistribution.
Implements topoSet.
Definition at line 90 of file pointBitSet.C.
References mapPolyMesh::reversePointMap().
void writeDebug (Ostream & os, const primitiveMesh & mesh, const label maxLen) const virtual
Write maxLen items with label and coordinates.
Implements topoSet.
Definition at line 104 of file pointBitSet.C.
The documentation for this class was generated from the following files:
src/meshTools/sets/topoSets/pointBitSet.H
src/meshTools/sets/topoSets/pointBitSet.C