OpenFOAM: surfaceLocation Class Reference
surfaceLocation Class Reference
Contains information about location on a triSurface.
Public Member Functions
surfaceLocation ()
Construct null.
surfaceLocation (const pointIndexHit &pih, const triPointRef::proxType elementType, const label triangle)
Construct from components.
surfaceLocation (Istream &is)
Construct from Istream.
triPointRef::proxType & elementType ()
triPointRef::proxType elementType () const
label & triangle ()
label triangle () const
vector normal (const triSurface &s) const
Normal. Approximate for points.
InfoProxy< surfaceLocation > info () const
Return info proxy.
void write (Ostream &os, const triSurface &s) const
Write info to os.
Public Member Functions inherited from PointIndexHit< Point >
PointIndexHit (const bool success, const Point &p, const label index)
Construct from components.
PointIndexHit (const Point &p)
Construct from point. Hit and distance set later.
PointIndexHit ()
Construct null.
PointIndexHit (Istream &is)
Construct from Istream.
bool hit () const
Is there a hit.
label index () const
Return index.
const Point & hitPoint () const
Return hit point.
const Point & missPoint () const
Return miss point.
const Point & rawPoint () const
Return point with no checking.
Point & rawPoint ()
void setHit ()
void setMiss ()
void setPoint (const Point &p)
void setIndex (const label index)
bool operator== (const PointIndexHit &rhs) const
bool operator!= (const PointIndexHit &rhs) const
void write (Ostream &os)
Friends
Istream & operator>> (Istream &is, surfaceLocation &sl)
Ostream & operator<< (Ostream &os, const surfaceLocation &sl)
Ostream & operator<< (Ostream &, const InfoProxy< surfaceLocation > &)
Detailed Description
Contains information about location on a triSurface.
Access to data:
pointIndexHit provides
location
bool: hit/miss
index (of triangle/point/edge)
elementType() provides
what index above relates to. In triangle::proxType
triangle() provides
last known triangle
Source files
surfaceLocation.H
surfaceLocation.C
Definition at line 71 of file surfaceLocation.H.
Constructor & Destructor Documentation
surfaceLocation () inline
Construct null.
Definition at line 89 of file surfaceLocation.H.
surfaceLocation (const pointIndexHit & pih, const triPointRef::proxType elementType, const label triangle) inline
Construct from components.
Definition at line 100 of file surfaceLocation.H.
surfaceLocation (Istream & is) inline
Construct from Istream.
Definition at line 114 of file surfaceLocation.H.
Member Function Documentation
triPointRef::proxType& elementType () inline
Definition at line 124 of file surfaceLocation.H.
Referenced by triSurfaceTools::classify().
triPointRef::proxType elementType () const inline
Definition at line 129 of file surfaceLocation.H.
label& triangle () inline
Definition at line 134 of file surfaceLocation.H.
label triangle () const inline
Definition at line 139 of file surfaceLocation.H.
Foam::vector normal (const triSurface & s) const
Normal. Approximate for points.
Definition at line 26 of file surfaceLocation.C.
References triangle< Point, PointRef >::EDGE, PrimitivePatch< Face, FaceList, PointField, PointType >::edgeFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::faceNormals(), forAll, i, PointIndexHit< Point >::index(), Foam::mag(), n, triangle< Point, PointRef >::NONE, UList< T >::size(), and Foam::Zero.
InfoProxy<surfaceLocation> info () const inline
Return info proxy.
Used to print token information to a stream
Definition at line 154 of file surfaceLocation.H.
void write (Ostream & os, const triSurface & s) const
Write info to os.
Definition at line 62 of file surfaceLocation.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, surfaceLocation & sl) friend
Ostream& operator<< (Ostream & os, const surfaceLocation & sl) friend
Ostream& operator<< (Ostream & , const InfoProxy< surfaceLocation > &) friend
The documentation for this class was generated from the following files:
src/meshTools/triSurface/surfaceLocation/surfaceLocation.H
src/meshTools/triSurface/surfaceLocation/surfaceLocation.C