OpenFOAM: GeometricField< Type, PatchField, GeoMesh >::Boundary Class Reference
GeometricField< Type, PatchField, GeoMesh >::Boundary Class Reference
Public Member Functions
Boundary (const BoundaryMesh &bmesh)
Construct from a BoundaryMesh.
Boundary (const BoundaryMesh &bmesh, const Internal &field, const word &patchFieldType)
Construct from a BoundaryMesh,.
Boundary (const BoundaryMesh &bmesh, const Internal &field, const wordList &wantedPatchTypes, const wordList &actualPatchTypes=wordList())
Construct from a BoundaryMesh,.
Boundary (const BoundaryMesh &bmesh, const Internal &field, const PtrList< PatchField< Type >> &)
Construct from a BoundaryMesh,.
Boundary (const Internal &field, const Boundary &btf)
Construct as copy setting the reference to the internal field.
Boundary (const Boundary &btf)
Construct as copy.
Boundary (const BoundaryMesh &bmesh, const Internal &field, const dictionary &dict)
Construct from dictionary.
void readField (const Internal &field, const dictionary &dict)
Read the boundary field.
void updateCoeffs ()
Update the boundary condition coefficients.
void evaluate ()
Evaluate boundary conditions.
wordList types () const
Return a list of the patch types.
Boundary boundaryInternalField () const
Return BoundaryField of the cell values neighbouring.
LduInterfaceFieldPtrsList< Type > interfaces () const
Return a list of pointers for each patch field with only those.
lduInterfaceFieldPtrsList scalarInterfaces () const
Return a list of pointers for each patch field with only those.
void writeEntry (const word &keyword, Ostream &os) const
Write boundary field as dictionary entry.
void writeEntries (Ostream &os) const
Write dictionary entries of the individual boundary fields.
void operator= (const Boundary &)
Assignment to BoundaryField<Type, PatchField, BoundaryMesh>
void operator= (const FieldField< PatchField, Type > &)
Assignment to FieldField<PatchField, Type>
void operator= (const Type &)
Assignment to Type.
void operator== (const Boundary &)
Forced assignment to.
void operator== (const FieldField< PatchField, Type > &)
Forced assignment to FieldField<PatchField, Type>
void operator== (const Type &)
Forced assignment to Type.
Public Member Functions inherited from FieldField< PatchField, Type >
constexpr FieldField () noexcept
Construct null.
FieldField (const label size)
Construct given size.
FieldField (const word &type, const FieldField< PatchField, Type > &ff)
Clone construct with new type.
FieldField (const FieldField< PatchField, Type > &ff)
Copy construct, cloning each element.
FieldField (FieldField< PatchField, Type > &&ff)
Move construct.
FieldField (FieldField< PatchField, Type > &ff, bool reuse)
Construct as copy or re-use as specified.
FieldField (const PtrList< PatchField< Type >> &list)
Copy construct from PtrList.
FieldField (PtrList< PatchField< Type >> &&list)
Move construct from PtrList.
FieldField (const tmp< FieldField< PatchField, Type >> &tf)
Move/copy construct from tmp<FieldField>
FieldField (Istream &is)
Construct from Istream.
tmp< FieldField< PatchField,
Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< PatchField,
cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< PatchField, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< PatchField,
Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< PatchField, Type > &)
Copy assignment.
void operator= (FieldField< PatchField, Type > &&)
Move assignment.
void operator= (const tmp< FieldField< PatchField, Type >> &)
Move or clone assignment.
void operator= (const Type &val)
Assign uniform value.
void operator+= (const FieldField< PatchField, Type > &)
void operator+= (const tmp< FieldField< PatchField, Type >> &)
void operator+= (const Type &)
void operator-= (const FieldField< PatchField, Type > &)
void operator-= (const tmp< FieldField< PatchField, Type >> &)
void operator-= (const Type &)
void operator*= (const FieldField< PatchField, scalar > &)
void operator*= (const tmp< FieldField< PatchField, scalar >> &)
void operator*= (const scalar &)
void operator/= (const FieldField< PatchField, scalar > &)
void operator/= (const tmp< FieldField< PatchField, scalar >> &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from PtrList< PatchField< Type > >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< PatchField< Type > > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< PatchField< Type > > &&list)
Move construct.
PtrList (UList< PatchField< Type > * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
PtrList (const PtrList< PatchField< Type > > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< PatchField< Type > > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< PatchField< Type > > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
PtrList< PatchField< Type > > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (PatchField< Type > *ptr)
Append an element to the end of the list.
void append (autoPtr< PatchField< Type > > &aptr)
Move append an element to the end of the list.
void append (autoPtr< PatchField< Type > > &&aptr)
Move append an element to the end of the list.
void append (const tmp< PatchField< Type > > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< PatchField< Type > > &list)
Transfer into this list and annul the argument list.
const PatchField< Type > * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< PatchField< Type > > set (const label i, PatchField< Type > *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< PatchField< Type > > set (const label i, autoPtr< PatchField< Type > > &aptr)
Set element to given autoPtr and return old element.
autoPtr< PatchField< Type > > set (const label i, autoPtr< PatchField< Type > > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< PatchField< Type > > set (const label i, const tmp< PatchField< Type > > &tptr)
Set element to given tmp and return old element.
autoPtr< PatchField< Type > > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< PatchField< Type > > &list)
Copy assignment.
void operator= (PtrList< PatchField< Type > > &&list)
Move assignment.
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from FieldField< PatchField, Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Static Public Member Functions inherited from FieldField< PatchField, Type >
static tmp< FieldField
< PatchField, Type > > NewCalculatedType (const FieldField< PatchField, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Protected Member Functions inherited from PtrList< PatchField< Type > >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Detailed Description
template<class Type, template< class > class PatchField, class GeoMesh>
class Foam::GeometricField< Type, PatchField, GeoMesh >::Boundary
Definition at line 124 of file GeometricField.H.
Constructor & Destructor Documentation
Boundary (const BoundaryMesh & bmesh)
Construct from a BoundaryMesh.
Definition at line 180 of file GeometricBoundaryField.C.
Boundary (const BoundaryMesh & bmesh, const Internal & field, const word & patchFieldType)
Construct from a BoundaryMesh,.
reference to the internal field and a patch type
Boundary (const BoundaryMesh & bmesh, const Internal & field, const wordList & wantedPatchTypes, const wordList & actualPatchTypes = wordList())
Construct from a BoundaryMesh,.
reference to the internal field and a wordList of patch types and optional the actual patch types (to override constraint patches)
Boundary (const BoundaryMesh & bmesh, const Internal & field, const PtrList< PatchField< Type >> &)
Construct from a BoundaryMesh,.
reference to the internal field and a PtrList<PatchField<Type>>
Boundary (const Internal & field, const Boundary & btf)
Construct as copy setting the reference to the internal field.
Boundary (const Boundary & btf)
Construct as copy.
Dangerous because Field may be set to a field which gets deleted Need new type of BoundaryField, one which is part of a geometric field for which snGrad etc. may be called and a free standing BoundaryField for which such operations are unavailable.
Boundary (const BoundaryMesh & bmesh, const Internal & field, const dictionary & dict)
Construct from dictionary.
Member Function Documentation
void readField (const Internal & field, const dictionary & dict)
Read the boundary field.
Definition at line 30 of file GeometricBoundaryField.C.
References PtrList< PatchField< Type > >::clear(), DebugInFunction, entry::dict(), Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, forAll, UList< Type >::found(), entry::isDict(), keyType::isLiteral(), iter, entry::keyword(), IOobject::name(), Foam::New(), Foam::nl, patchIds, PtrList< PatchField< Type > >::set(), PtrList< PatchField< Type > >::setSize(), UPtrList< T >::size(), and Foam::type().
void updateCoeffs ()
Update the boundary condition coefficients.
Definition at line 361 of file GeometricBoundaryField.C.
void evaluate ()
Evaluate boundary conditions.
Definition at line 374 of file GeometricBoundaryField.C.
Foam::wordList types () const
Return a list of the patch types.
Definition at line 438 of file GeometricBoundaryField.C.
Foam::GeometricField< Type, PatchField, GeoMesh >::Boundary boundaryInternalField () const
Return BoundaryField of the cell values neighbouring.
the boundary
Definition at line 456 of file GeometricBoundaryField.C.
Foam::LduInterfaceFieldPtrsList< Type > interfaces () const
Return a list of pointers for each patch field with only those.
pointing to interfaces being set
Definition at line 474 of file GeometricBoundaryField.C.
Foam::lduInterfaceFieldPtrsList scalarInterfaces () const
Return a list of pointers for each patch field with only those.
pointing to interfaces being set
Definition at line 500 of file GeometricBoundaryField.C.
void writeEntry (const word & keyword, Ostream & os) const
Write boundary field as dictionary entry.
Definition at line 525 of file GeometricBoundaryField.C.
void writeEntries (Ostream & os) const
Write dictionary entries of the individual boundary fields.
Definition at line 537 of file GeometricBoundaryField.C.
void operator= (const Boundary &)
Assignment to BoundaryField<Type, PatchField, BoundaryMesh>
void operator= (const FieldField< PatchField, Type > & ptff)
Assignment to FieldField<PatchField, Type>
Definition at line 565 of file GeometricBoundaryField.C.
void operator= (const Type & t)
Assignment to Type.
Definition at line 576 of file GeometricBoundaryField.C.
void operator== (const Boundary &)
Forced assignment to.
BoundaryField<Type, PatchField, BoundaryMesh>
void operator== (const FieldField< PatchField, Type > & ptff)
Forced assignment to FieldField<PatchField, Type>
Definition at line 602 of file GeometricBoundaryField.C.
void operator== (const Type & t)
Forced assignment to Type.
Definition at line 616 of file GeometricBoundaryField.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricField.H
src/OpenFOAM/fields/GeometricFields/GeometricField/GeometricBoundaryField.C