OpenFOAM: LduMatrix< Type, DType, LUType >::solver Class Reference
LduMatrix< Type, DType, LUType >::solver Class Reference abstract
Abstract base-class for LduMatrix solvers.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, solver, symMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
declareRunTimeSelectionTable (autoPtr, solver, asymMatrix,(const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict),(fieldName, matrix, solverDict))
solver (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
virtual ~solver ()=default
const word & fieldName () const
const LduMatrix< Type, DType,
LUType > & matrix () const
virtual void read (const dictionary &solverDict)
Read and reset the solver parameters from the given dictionary.
virtual SolverPerformance< Type > solve (Field< Type > &psi) const =0
Type normFactor (const Field< Type > &psi, const Field< Type > &Apsi, Field< Type > &tmpField) const
Return the matrix norm used to normalise the residual for the.
Static Public Member Functions
static autoPtr< solver > New (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict)
Return a new solver.
Protected Member Functions
template<class T >
void readControl (const dictionary &controlDict, T &control, const word &controlName)
Read a control parameter from controlDict.
virtual void readControls ()
Read the control parameters from the controlDict_.
Protected Attributes
word fieldName_
const LduMatrix< Type, DType,
LUType > & matrix_
dictionary controlDict_
Dictionary of controls.
label maxIter_
Maximum number of iterations in the solver.
label minIter_
Minimum number of iterations in the solver.
Type tolerance_
Final convergence tolerance.
Type relTol_
Convergence tolerance relative to the initial.
Static Protected Attributes
static const label defaultMaxIter_ = 1000
Default maximum number of iterations in the solver.
Detailed Description
template<class Type, class DType, class LUType>
class Foam::LduMatrix< Type, DType, LUType >::solver
Abstract base-class for LduMatrix solvers.
Definition at line 125 of file LduMatrix.H.
Constructor & Destructor Documentation
solver (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict)
Definition at line 114 of file LduMatrixSolver.C.
virtual ~solver () virtual default
Member Function Documentation
void readControl (const dictionary & controlDict, T & control, const word & controlName) inline protected
Read a control parameter from controlDict.
Definition at line 26 of file LduMatrixI.H.
References dictionary::readIfPresent().
void readControls () protected virtual
Read the control parameters from the controlDict_.
Reimplemented in SmoothSolver< Type, DType, LUType >.
Definition at line 137 of file LduMatrixSolver.C.
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (autoPtr , solver , symMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict) , (fieldName, matrix, solverDict))
declareRunTimeSelectionTable (autoPtr , solver , asymMatrix , (const word &fieldName, const LduMatrix< Type, DType, LUType > &matrix, const dictionary &solverDict) , (fieldName, matrix, solverDict))
Foam::autoPtr< typename Foam::LduMatrix< Type, DType, LUType >::solver > New (const word & fieldName, const LduMatrix< Type, DType, LUType > & matrix, const dictionary & solverDict) static
Return a new solver.
Definition at line 30 of file LduMatrixSolver.C.
References LduMatrix< Type, DType, LUType >::asymmetric(), LduMatrix< Type, DType, LUType >::diagonal(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, LduMatrix< Type, DType, LUType >::solver::fieldName(), dictionary::get(), LduMatrix< Type, DType, LUType >::solver::matrix(), and LduMatrix< Type, DType, LUType >::symmetric().
const word& fieldName () const inline
Definition at line 262 of file LduMatrix.H.
Referenced by LduMatrix< Type, DType, LUType >::solver::New().
const LduMatrix<Type, DType, LUType>& matrix () const inline
Definition at line 267 of file LduMatrix.H.
Referenced by DiagonalPreconditioner< Type, DType, LUType >::DiagonalPreconditioner(), LduMatrix< Type, DType, LUType >::solver::New(), LduMatrix< Type, DType, LUType >::preconditioner::New(), and TDILUPreconditioner< Type, DType, LUType >::TDILUPreconditioner().
void read (const dictionary & solverDict) virtual
Read and reset the solver parameters from the given dictionary.
Reimplemented in DiagonalSolver< Type, DType, LUType >.
Definition at line 148 of file LduMatrixSolver.C.
virtual SolverPerformance<Type> solve (Field< Type > & psi) const pure virtual
Implemented in PBiCCCG< Type, DType, LUType >, PBiCICG< Type, DType, LUType >, PCICG< Type, DType, LUType >, SmoothSolver< Type, DType, LUType >, and DiagonalSolver< Type, DType, LUType >.
Type normFactor (const Field< Type > & psi, const Field< Type > & Apsi, Field< Type > & tmpField) const
Return the matrix norm used to normalise the residual for the.
stopping criterion
Definition at line 159 of file LduMatrixSolver.C.
Member Data Documentation
word fieldName_ protected
Definition at line 131 of file LduMatrix.H.
const LduMatrix<Type, DType, LUType>& matrix_ protected
Definition at line 132 of file LduMatrix.H.
dictionary controlDict_ protected
Dictionary of controls.
Definition at line 137 of file LduMatrix.H.
const label defaultMaxIter_ = 1000 static protected
Default maximum number of iterations in the solver.
Definition at line 142 of file LduMatrix.H.
label maxIter_ protected
Maximum number of iterations in the solver.
Definition at line 147 of file LduMatrix.H.
label minIter_ protected
Minimum number of iterations in the solver.
Definition at line 152 of file LduMatrix.H.
Type tolerance_ protected
Final convergence tolerance.
Definition at line 157 of file LduMatrix.H.
Type relTol_ protected
Convergence tolerance relative to the initial.
Definition at line 162 of file LduMatrix.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrix.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixI.H
src/OpenFOAM/matrices/LduMatrix/LduMatrix/LduMatrixSolver.C