OpenFOAM: liquidFilmThermo Class Reference
liquidFilmThermo Class Reference
Liquid thermo model.
Public Member Functions
TypeName ("liquid")
Runtime type information.
liquidFilmThermo (surfaceFilmRegionModel &film, const dictionary &dict)
Construct from surface film model and dictionary.
virtual ~liquidFilmThermo ()
Destructor.
virtual const word & name () const
Return the specie name.
virtual scalar rho (const scalar p, const scalar T) const
Return density [kg/m3].
virtual scalar mu (const scalar p, const scalar T) const
Return dynamic viscosity [Pa.s].
virtual scalar sigma (const scalar p, const scalar T) const
Return surface tension [kg/s2].
virtual scalar Cp (const scalar p, const scalar T) const
Return specific heat capacity [J/kg/K].
virtual scalar kappa (const scalar p, const scalar T) const
Return thermal conductivity [W/m/K].
virtual scalar D (const scalar p, const scalar T) const
Return diffusivity [m2/s].
virtual scalar hl (const scalar p, const scalar T) const
Return latent heat [J/kg].
virtual scalar pv (const scalar p, const scalar T) const
Return vapour pressure [Pa].
virtual scalar W () const
Return molecular weight [kg/kmol].
virtual scalar Tb (const scalar p) const
Return boiling temperature [K].
virtual tmp< volScalarField > rho () const
Return density [kg/m3].
virtual tmp< volScalarField > mu () const
Return dynamic viscosity [Pa.s].
virtual tmp< volScalarField > sigma () const
Return surface tension [kg/s2].
virtual tmp< volScalarField > Cp () const
Return specific heat capacity [J/kg/K].
virtual tmp< volScalarField > kappa () const
Return thermal conductivity [W/m/K].
Public Member Functions inherited from filmThermoModel
TypeName ("filmThermoModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, filmThermoModel, dictionary,(surfaceFilmRegionModel &film, const dictionary &dict),(film, dict))
filmThermoModel (surfaceFilmRegionModel &film)
Construct null.
filmThermoModel (const word &modelType, surfaceFilmRegionModel &film, const dictionary &dict)
Construct from type name, dictionary and surface film model.
virtual ~filmThermoModel ()
Destructor.
Public Member Functions inherited from filmSubModelBase
filmSubModelBase (surfaceFilmRegionModel &film)
Construct null.
filmSubModelBase (surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from film film without name.
filmSubModelBase (const word &modelName, surfaceFilmRegionModel &film, const dictionary &dict, const word &baseName, const word &modelType)
Construct from film film with name.
virtual ~filmSubModelBase ()
Destructor.
virtual bool writeTime () const
Flag to indicate when to write a property.
const surfaceFilmRegionModel & film () const
Return const access to the film surface film model.
surfaceFilmRegionModel & film ()
Return the reference to the film surface film model.
template<class FilmType >
const FilmType & filmType () const
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
virtual fileName localPath () const
Output directory.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
bool getModelDict (const word &entryName, dictionary &dict) const
Retrieve dictionary, return true if set.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Member Functions
const thermoSingleLayer & thermoFilm () const
Return a reference to a thermo film.
void initLiquid (const dictionary &dict)
Initialise the liquid pointer.
liquidFilmThermo (const liquidFilmThermo &)=delete
No copy construct.
void operator= (const liquidFilmThermo &)=delete
No copy assignment.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
word name_
Liquid name.
const liquidProperties * liquidPtr_
Pointer to the liquid properties.
bool ownLiquid_
Flag to indicate that model owns the liquid object.
bool useReferenceValues_
Flag to indicate that reference values of p and T should be used.
scalar pRef_
Reference pressure [pa].
scalar TRef_
Reference temperature [K].
Protected Attributes inherited from filmSubModelBase
surfaceFilmRegionModel & filmModel_
Reference to the film surface film model.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Static Public Member Functions inherited from filmThermoModel
static autoPtr< filmThermoModel > New (surfaceFilmRegionModel &film, const dictionary &dict)
Return a reference to the selected phase change model.
Detailed Description
Liquid thermo model.
Source files
liquidFilmThermo.H
liquidFilmThermo.C
Definition at line 54 of file liquidFilmThermo.H.
Constructor & Destructor Documentation
liquidFilmThermo (const liquidFilmThermo &) protected delete
No copy construct.
liquidFilmThermo (surfaceFilmRegionModel & film, const dictionary & dict)
Construct from surface film model and dictionary.
Definition at line 104 of file liquidFilmThermo.C.
~liquidFilmThermo () virtual
Destructor.
Definition at line 129 of file liquidFilmThermo.C.
Member Function Documentation
const thermoSingleLayer & thermoFilm () const protected
Return a reference to a thermo film.
Definition at line 51 of file liquidFilmThermo.C.
void initLiquid (const dictionary & dict) protected
Initialise the liquid pointer.
Definition at line 67 of file liquidFilmThermo.C.
void operator= (const liquidFilmThermo &) protected delete
No copy assignment.
TypeName ("liquid")
Runtime type information.
const word & name () const virtual
Return the specie name.
Implements filmThermoModel.
Definition at line 140 of file liquidFilmThermo.C.
scalar rho (const scalar p, const scalar T) const virtual
Return density [kg/m3].
Implements filmThermoModel.
Definition at line 147 of file liquidFilmThermo.C.
References liquidFilmThermo::name_.
scalar mu (const scalar p, const scalar T) const virtual
Return dynamic viscosity [Pa.s].
Implements filmThermoModel.
Definition at line 157 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, thermophysicalProperties::rho(), and Foam::T().
scalar sigma (const scalar p, const scalar T) const virtual
Return surface tension [kg/s2].
Implements filmThermoModel.
Definition at line 167 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, liquidProperties::mu(), and Foam::T().
scalar Cp (const scalar p, const scalar T) const virtual
Return specific heat capacity [J/kg/K].
Implements filmThermoModel.
Definition at line 177 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, liquidProperties::sigma(), and Foam::T().
scalar kappa (const scalar p, const scalar T) const virtual
Return thermal conductivity [W/m/K].
Implements filmThermoModel.
Definition at line 187 of file liquidFilmThermo.C.
References thermophysicalProperties::Cp(), liquidFilmThermo::liquidPtr_, and Foam::T().
scalar D (const scalar p, const scalar T) const virtual
Return diffusivity [m2/s].
Implements filmThermoModel.
Definition at line 197 of file liquidFilmThermo.C.
References liquidProperties::kappa(), liquidFilmThermo::liquidPtr_, and Foam::T().
scalar hl (const scalar p, const scalar T) const virtual
Return latent heat [J/kg].
Implements filmThermoModel.
Definition at line 207 of file liquidFilmThermo.C.
References liquidProperties::D(), liquidFilmThermo::liquidPtr_, and Foam::T().
scalar pv (const scalar p, const scalar T) const virtual
Return vapour pressure [Pa].
Implements filmThermoModel.
Definition at line 217 of file liquidFilmThermo.C.
References liquidProperties::hl(), liquidFilmThermo::liquidPtr_, and Foam::T().
scalar W () const virtual
Return molecular weight [kg/kmol].
Implements filmThermoModel.
Definition at line 226 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, and liquidProperties::pv().
scalar Tb (const scalar p) const virtual
Return boiling temperature [K].
Implements filmThermoModel.
Definition at line 232 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, and thermophysicalProperties::W().
tmp< volScalarField > rho () const virtual
Return density [kg/m3].
Implements filmThermoModel.
Definition at line 238 of file liquidFilmThermo.C.
References liquidFilmThermo::liquidPtr_, and liquidProperties::pvInvert().
tmp< volScalarField > mu () const virtual
Return dynamic viscosity [Pa.s].
Implements filmThermoModel.
Definition at line 283 of file liquidFilmThermo.C.
tmp< volScalarField > sigma () const virtual
Return surface tension [kg/s2].
Implements filmThermoModel.
Definition at line 328 of file liquidFilmThermo.C.
tmp< volScalarField > Cp () const virtual
Return specific heat capacity [J/kg/K].
Implements filmThermoModel.
Definition at line 373 of file liquidFilmThermo.C.
tmp< volScalarField > kappa () const virtual
Return thermal conductivity [W/m/K].
Implements filmThermoModel.
Definition at line 418 of file liquidFilmThermo.C.
Member Data Documentation
word name_ protected
Liquid name.
Definition at line 65 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::rho().
const liquidProperties* liquidPtr_ protected
Pointer to the liquid properties.
Definition at line 70 of file liquidFilmThermo.H.
Referenced by liquidFilmThermo::Cp(), liquidFilmThermo::D(), liquidFilmThermo::hl(), liquidFilmThermo::kappa(), liquidFilmThermo::mu(), liquidFilmThermo::pv(), liquidFilmThermo::rho(), liquidFilmThermo::sigma(), liquidFilmThermo::Tb(), and liquidFilmThermo::W().
bool ownLiquid_ protected
Flag to indicate that model owns the liquid object.
Definition at line 75 of file liquidFilmThermo.H.
bool useReferenceValues_ protected
Flag to indicate that reference values of p and T should be used.
Definition at line 80 of file liquidFilmThermo.H.
scalar pRef_ protected
Reference pressure [pa].
Definition at line 85 of file liquidFilmThermo.H.
scalar TRef_ protected
Reference temperature [K].
Definition at line 90 of file liquidFilmThermo.H.
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/liquidFilmThermo/liquidFilmThermo.H
src/regionModels/surfaceFilmModels/submodels/kinematic/filmThermoModel/liquidFilmThermo/liquidFilmThermo.C