OpenFOAM: polyMeshModifier Class Reference
polyMeshModifier Class Reference abstract
Virtual base class for mesh modifiers.
Public Member Functions
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyMeshModifier, dictionary,(const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme),(name, dict, index, mme))
polyMeshModifier (const word &name, const label index, const polyTopoChanger &mme, const bool act)
Construct from components.
virtual ~polyMeshModifier ()
Destructor.
const word & name () const
Return name of this modifier.
label index () const
Return the index of this modifier.
const polyTopoChanger & topoChanger () const
Return reference to morph engine.
virtual bool changeTopology () const =0
Check for topology change.
virtual void setRefinement (polyTopoChange &) const =0
Insert the topological change instructions.
virtual void modifyMotionPoints (pointField &motionPoints) const =0
Modify motion points to comply with the topological change.
virtual void updateMesh (const mapPolyMesh &)=0
Force recalculation of locally stored data on topological change.
const Switch & active () const
void enable () const
Activate mesh modifier.
void disable () const
Activate mesh modifier.
virtual void write (Ostream &) const =0
Write.
virtual void writeDict (Ostream &) const =0
Write dictionary.
Static Public Member Functions
static autoPtr< polyMeshModifier > New (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme)
Select constructed from dictionary.
Friends
Ostream & operator<< (Ostream &, const polyMeshModifier &)
Detailed Description
Virtual base class for mesh modifiers.
Source files
polyMeshModifier.H
polyMeshModifier.C
Definition at line 67 of file polyMeshModifier.H.
Constructor & Destructor Documentation
polyMeshModifier (const word & name, const label index, const polyTopoChanger & mme, const bool act)
Construct from components.
Definition at line 43 of file polyMeshModifier.C.
~polyMeshModifier () virtual
Destructor.
Definition at line 59 of file polyMeshModifier.C.
Member Function Documentation
TypeName ("meshModifier")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , polyMeshModifier , dictionary , (const word &name, const dictionary &dict, const label index, const polyTopoChanger &mme) , (name, dict, index, mme))
Foam::autoPtr< Foam::polyMeshModifier > New (const word & name, const dictionary & dict, const label index, const polyTopoChanger & mme) static
Select constructed from dictionary.
Definition at line 28 of file polyMeshModifierNew.C.
References DebugInFunction, dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), polyMeshModifier::index(), and polyMeshModifier::name().
const word& name () const inline
Return name of this modifier.
Definition at line 171 of file polyMeshModifier.H.
Referenced by polyMeshModifier::New().
label index () const inline
Return the index of this modifier.
Definition at line 179 of file polyMeshModifier.H.
Referenced by polyMeshModifier::New().
const Foam::polyTopoChanger & topoChanger () const
Return reference to morph engine.
Definition at line 65 of file polyMeshModifier.C.
virtual bool changeTopology () const pure virtual
Check for topology change.
Implemented in slidingInterface, attachDetach, layerAdditionRemoval, perfectInterface, and setUpdater.
virtual void setRefinement (polyTopoChange &) const pure virtual
Insert the topological change instructions.
Implemented in slidingInterface, attachDetach, layerAdditionRemoval, perfectInterface, and setUpdater.
virtual void modifyMotionPoints (pointField & motionPoints) const pure virtual
Modify motion points to comply with the topological change.
Implemented in slidingInterface, attachDetach, layerAdditionRemoval, perfectInterface, and setUpdater.
virtual void updateMesh (const mapPolyMesh &) pure virtual
Force recalculation of locally stored data on topological change.
Implemented in slidingInterface, attachDetach, layerAdditionRemoval, perfectInterface, and setUpdater.
const Switch& active () const inline
Definition at line 212 of file polyMeshModifier.H.
void enable () const inline
Activate mesh modifier.
Definition at line 220 of file polyMeshModifier.H.
void disable () const inline
Activate mesh modifier.
Definition at line 228 of file polyMeshModifier.H.
virtual void write (Ostream &) const pure virtual
Write.
Implemented in slidingInterface, attachDetach, layerAdditionRemoval, perfectInterface, and setUpdater.
virtual void writeDict (Ostream &) const pure virtual
Write dictionary.
Implemented in slidingInterface, attachDetach, layerAdditionRemoval, perfectInterface, and setUpdater.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const polyMeshModifier &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyMeshModifier/polyMeshModifier.H
src/dynamicMesh/polyTopoChange/polyMeshModifier/polyMeshModifier.C
src/dynamicMesh/polyTopoChange/polyMeshModifier/polyMeshModifierNew.C