OpenFOAM: patchEdgeFaceInfo Class Reference
patchEdgeFaceInfo Class Reference
Public Member Functions
patchEdgeFaceInfo ()
Construct null.
patchEdgeFaceInfo (const point &, const scalar)
Construct from origin, distance.
patchEdgeFaceInfo (const patchEdgeFaceInfo &)
Construct as copy.
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
void transform (const polyMesh &mesh, const primitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
Apply rotation matrix.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const primitivePatch &patch, const label edgeI, const label facei, const patchEdgeFaceInfo &faceInfo, const scalar tol, TrackingData &td)
Influence of face on edge.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const primitivePatch &patch, const patchEdgeFaceInfo &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
New information for edge (from e.g. coupled edge)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const primitivePatch &patch, const label facei, const label edgeI, const patchEdgeFaceInfo &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on face.
template<class TrackingData >
bool equal (const patchEdgeFaceInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const patchEdgeFaceInfo &) const
bool operator!= (const patchEdgeFaceInfo &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceInfo &)
Istream & operator>> (Istream &, patchEdgeFaceInfo &)
Detailed Description
Source files
patchEdgeFaceInfo.H
patchEdgeFaceInfoI.H
patchEdgeFaceInfo.C
Definition at line 61 of file patchEdgeFaceInfo.H.
Constructor & Destructor Documentation
patchEdgeFaceInfo () inline
Construct null.
Definition at line 116 of file patchEdgeFaceInfoI.H.
patchEdgeFaceInfo (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 125 of file patchEdgeFaceInfoI.H.
patchEdgeFaceInfo (const patchEdgeFaceInfo & wpt) inline
Construct as copy.
Definition at line 136 of file patchEdgeFaceInfoI.H.
Member Function Documentation
const Foam::point & origin () const inline
Definition at line 145 of file patchEdgeFaceInfoI.H.
Foam::scalar distSqr () const inline
Definition at line 151 of file patchEdgeFaceInfoI.H.
References origin_().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 158 of file patchEdgeFaceInfoI.H.
void transform (const polyMesh & mesh, const primitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Apply rotation matrix.
Definition at line 166 of file patchEdgeFaceInfoI.H.
References VectorSpace< Vector< scalar >, scalar, 3 >::max, and origin_().
bool updateEdge (const polyMesh & mesh, const primitivePatch & patch, const label edgeI, const label facei, const patchEdgeFaceInfo & faceInfo, const scalar tol, TrackingData & td) inline
Influence of face on edge.
Definition at line 180 of file patchEdgeFaceInfoI.H.
References origin_(), and Foam::transform().
bool updateEdge (const polyMesh & mesh, const primitivePatch & patch, const patchEdgeFaceInfo & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
New information for edge (from e.g. coupled edge)
Definition at line 203 of file patchEdgeFaceInfoI.H.
bool updateFace (const polyMesh & mesh, const primitivePatch & patch, const label facei, const label edgeI, const patchEdgeFaceInfo & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on face.
Definition at line 218 of file patchEdgeFaceInfoI.H.
References update().
bool equal (const patchEdgeFaceInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 234 of file patchEdgeFaceInfoI.H.
References PrimitivePatch< Face, FaceList, PointField, PointType >::faceCentres(), and update().
bool operator== (const patchEdgeFaceInfo & rhs) const inline
Definition at line 246 of file patchEdgeFaceInfoI.H.
bool operator!= (const patchEdgeFaceInfo & rhs) const inline
Definition at line 255 of file patchEdgeFaceInfoI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const patchEdgeFaceInfo &) friend
Istream& operator>> (Istream & , patchEdgeFaceInfo &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceInfo.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceInfoI.H