OpenFOAM: FaceCellWave< Type, TrackingData > Class Template Reference
FaceCellWave< Type, TrackingData > Class Template Reference
Wave propagation of information through grid. Every iteration information goes through one layer of cells. Templated on information that is transferred.
Public Member Functions
FaceCellWave (const polyMesh &mesh, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, TrackingData &td=dummyTrackData_)
Construct from mesh. Use setFaceInfo and iterate() to do actual calculation.
FaceCellWave (const polyMesh &mesh, const labelUList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
FaceCellWave (const polyMesh &mesh, const labelPairList &explicitConnections, const bool handleCyclicAMI, const labelUList &initialChangedFaces, const List< Type > &changedFacesInfo, UList< Type > &allFaceInfo, UList< Type > &allCellInfo, const label maxIter, TrackingData &td=dummyTrackData_)
Construct from mesh and explicitly connected boundary faces.
virtual ~FaceCellWave ()=default
Destructor.
UList< Type > & allFaceInfo ()
Access allFaceInfo.
UList< Type > & allCellInfo ()
Access allCellInfo.
const TrackingData & data () const
Additional data to be passed into container.
const polyMesh & mesh () const
Access mesh.
label nUnvisitedCells () const
Get number of unvisited cells, i.e. cells that were not (yet) reached from walking across mesh.
label nUnvisitedFaces () const
Get number of unvisited faces.
void setFaceInfo (const label facei, const Type &faceInfo)
Set single initial changed face.
void setFaceInfo (const labelUList &changedFaces, const List< Type > &changedFacesInfo)
Set initial changed faces.
virtual label faceToCell ()
Propagate from face to cell.
virtual label cellToFace ()
Propagate from cell to face.
virtual label iterate (const label maxIter)
Iterate until no changes or maxIter reached.
Static Public Member Functions
static scalar propagationTol ()
Access to tolerance.
static void setPropagationTol (const scalar tol)
Change tolerance.
Protected Types
typedef std::pair< label, Type > taggedInfoType
Information tagged with a source or destination id.
Protected Member Functions
bool updateCell (const label celli, const label neighbourFacei, const Type &neighbourInfo, const scalar tol, Type &cellInfo)
Updates cellInfo with information from neighbour.
bool updateFace (const label facei, const label neighbourCelli, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
Updates faceInfo with information from neighbour.
bool updateFace (const label facei, const Type &neighbourInfo, const scalar tol, Type &faceInfo)
Updates faceInfo with information from same face.
void checkCyclic (const polyPatch &pPatch) const
Debugging: check info on both sides of cyclic.
template<class PatchType >
bool hasPatch () const
Has cyclic patch?
void mergeFaceInfo (const polyPatch &patch, const label nFaces, const labelUList &changedFaces, const List< Type > &changedFacesInfo)
Merge received patch data into global data.
label getChangedPatchFaces (const polyPatch &patch, const label startFacei, const label nFaces, labelList &changedPatchFaces, List< Type > &changedPatchFacesInfo) const
Extract info for single patch only.
void leaveDomain (const polyPatch &patch, const label nFaces, const labelUList &faceLabels, List< Type > &faceInfo) const
Handle leaving domain. Implementation referred to Type.
void enterDomain (const polyPatch &patch, const label nFaces, const labelUList &faceLabels, List< Type > &faceInfo) const
Handle leaving domain. Implementation referred to Type.
void transform (const tensorField &rotTensor, const label nFaces, List< Type > &faceInfo)
Apply transformation to Type.
void handleProcPatches ()
Merge data from across processor boundaries.
void handleCyclicPatches ()
Merge data from across cyclics.
void handleAMICyclicPatches ()
Merge data from across AMI cyclics.
void handleExplicitConnections ()
Merge data across explicitly provided local connections.
Static Protected Member Functions
static void offset (const polyPatch &patch, const label off, const label nFaces, labelList &faces)
Offset face labels by constant value.
Protected Attributes
const polyMesh & mesh_
Reference to mesh.
const labelPairList explicitConnections_
Optional boundary faces that information should travel through.
UList< Type > & allFaceInfo_
Information for all faces.
UList< Type > & allCellInfo_
Information for all cells.
TrackingData & td_
Additional data to be passed into container.
bitSet changedFace_
Has face changed.
bitSet changedCell_
Has cell changed.
DynamicList< label > changedFaces_
List of changed faces.
DynamicList< label > changedCells_
DynamicList< taggedInfoType > changedBaffles_
const bool hasCyclicPatches_
Contains cyclics.
const bool hasCyclicAMIPatches_
Contains cyclicAMI.
label nEvals_
Number of evaluations.
label nUnvisitedCells_
Number of unvisited cells/faces.
label nUnvisitedFaces_
Static Protected Attributes
static const scalar geomTol_ = 1e-6
static scalar propagationTol_ = 0.01
static int dummyTrackData_ = 12345
Used as default trackdata value to satisfy default template.
Detailed Description
template<class Type, class TrackingData = int>
class Foam::FaceCellWave< Type, TrackingData >
Wave propagation of information through grid. Every iteration information goes through one layer of cells. Templated on information that is transferred.
Handles parallel and cyclics and non-parallel cyclics.
Note: whether to propagate depends on the return value of Type::update which returns true (i.e. propagate) if the value changes by more than a certain tolerance. This tolerance can be very strict for normal face-cell and parallel cyclics (we use a value of 0.01 just to limit propagation of small changes) but for non-parallel cyclics this tolerance can be critical and if chosen too small can lead to non-convergence.
Source files
FaceCellWave.H
FaceCellWave.C
Definition at line 74 of file FaceCellWave.H.
Member Typedef Documentation
typedef std::pair<label,Type> taggedInfoType protected
Information tagged with a source or destination id.
With std::pair as lightweight, moveable container.
Definition at line 98 of file FaceCellWave.H.
Constructor & Destructor Documentation
FaceCellWave (const polyMesh & mesh, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, TrackingData & td = dummyTrackData_)
Construct from mesh. Use setFaceInfo and iterate() to do actual calculation.
Definition at line 877 of file FaceCellWave.C.
References Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, FaceCellWave< Type, TrackingData >::mesh_, primitiveMesh::nCells(), primitiveMesh::nFaces(), Foam::nl, and UList< T >::size().
FaceCellWave (const polyMesh & mesh, const labelUList & initialChangedFaces, const List< Type > & changedFacesInfo, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh and list of changed faces with the Type.
for these faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0 or negative). 0 initializes, -1 does not
Definition at line 922 of file FaceCellWave.C.
FaceCellWave (const polyMesh & mesh, const labelPairList & explicitConnections, const bool handleCyclicAMI, const labelUList & initialChangedFaces, const List< Type > & changedFacesInfo, UList< Type > & allFaceInfo, UList< Type > & allCellInfo, const label maxIter, TrackingData & td = dummyTrackData_)
Construct from mesh and explicitly connected boundary faces.
and list of changed faces with the Type for these faces. Iterates until nothing changes or maxIter reached. (maxIter can be 0 or negative). 0 initializes, -1 does not
Definition at line 986 of file FaceCellWave.C.
virtual ~FaceCellWave () virtual default
Destructor.
Member Function Documentation
bool updateCell (const label celli, const label neighbourFacei, const Type & neighbourInfo, const scalar tol, Type & cellInfo) protected
Updates cellInfo with information from neighbour.
Updates all statistics.
Definition at line 109 of file FaceCellWave.C.
bool updateFace (const label facei, const label neighbourCelli, const Type & neighbourInfo, const scalar tol, Type & faceInfo) protected
Updates faceInfo with information from neighbour.
Updates all statistics.
Definition at line 157 of file FaceCellWave.C.
bool updateFace (const label facei, const Type & neighbourInfo, const scalar tol, Type & faceInfo) protected
Updates faceInfo with information from same face.
Updates all statistics.
Definition at line 205 of file FaceCellWave.C.
void checkCyclic (const polyPatch & pPatch) const protected
Debugging: check info on both sides of cyclic.
Definition at line 251 of file FaceCellWave.C.
bool hasPatch () const protected
Has cyclic patch?
Definition at line 297 of file FaceCellWave.C.
void mergeFaceInfo (const polyPatch & patch, const label nFaces, const labelUList & changedFaces, const List< Type > & changedFacesInfo) protected
Merge received patch data into global data.
Definition at line 365 of file FaceCellWave.C.
Foam::label getChangedPatchFaces (const polyPatch & patch, const label startFacei, const label nFaces, labelList & changedPatchFaces, List< Type > & changedPatchFacesInfo) const protected
Extract info for single patch only.
Definition at line 399 of file FaceCellWave.C.
void leaveDomain (const polyPatch & patch, const label nFaces, const labelUList & faceLabels, List< Type > & faceInfo) const protected
Handle leaving domain. Implementation referred to Type.
Definition at line 431 of file FaceCellWave.C.
void enterDomain (const polyPatch & patch, const label nFaces, const labelUList & faceLabels, List< Type > & faceInfo) const protected
Handle leaving domain. Implementation referred to Type.
Definition at line 454 of file FaceCellWave.C.
void offset (const polyPatch & patch, const label off, const label nFaces, labelList & faces) static protected
Offset face labels by constant value.
Definition at line 506 of file FaceCellWave.C.
void transform (const tensorField & rotTensor, const label nFaces, List< Type > & faceInfo) protected
Apply transformation to Type.
Definition at line 477 of file FaceCellWave.C.
void handleProcPatches () protected
Merge data from across processor boundaries.
Transfer changed faces from neighbouring processors.
Definition at line 524 of file FaceCellWave.C.
void handleCyclicPatches () protected
Merge data from across cyclics.
Transfer changed faces across cyclic halves
Definition at line 640 of file FaceCellWave.C.
void handleAMICyclicPatches () protected
Merge data from across AMI cyclics.
Definition at line 724 of file FaceCellWave.C.
void handleExplicitConnections () protected
Merge data across explicitly provided local connections.
These are usually baffles
Definition at line 824 of file FaceCellWave.C.
static scalar propagationTol () inline static
Access to tolerance.
Definition at line 342 of file FaceCellWave.H.
static void setPropagationTol (const scalar tol) inline static
Change tolerance.
Definition at line 350 of file FaceCellWave.H.
References FaceCellWave< Type, TrackingData >::td_.
UList<Type>& allFaceInfo () inline
Access allFaceInfo.
Definition at line 421 of file FaceCellWave.H.
UList<Type>& allCellInfo () inline
Access allCellInfo.
Definition at line 429 of file FaceCellWave.H.
const TrackingData& data () const inline
Additional data to be passed into container.
Definition at line 437 of file FaceCellWave.H.
const polyMesh& mesh () const inline
Access mesh.
Definition at line 445 of file FaceCellWave.H.
Foam::label nUnvisitedCells () const
Get number of unvisited cells, i.e. cells that were not (yet) reached from walking across mesh.
This can happen from
not enough iterations done
a disconnected mesh
a mesh without walls in it
Definition at line 1054 of file FaceCellWave.C.
Foam::label nUnvisitedFaces () const
Get number of unvisited faces.
Definition at line 1061 of file FaceCellWave.C.
void setFaceInfo (const label facei, const Type & faceInfo)
Set single initial changed face.
This is a noop if the face had already been visited
Definition at line 312 of file FaceCellWave.C.
Referenced by hexRef8::consistentSlowRefinement().
void setFaceInfo (const labelUList & changedFaces, const List< Type > & changedFacesInfo)
Set initial changed faces.
Definition at line 336 of file FaceCellWave.C.
Foam::label faceToCell () virtual
Propagate from face to cell.
Returns
total number of cells (over all processors) changed.
Reimplemented in OppositeFaceCellWave< Type, TrackingData >.
Definition at line 1068 of file FaceCellWave.C.
Foam::label cellToFace () virtual
Propagate from cell to face.
Returns
total number of faces (over all processors) changed. Note that faces on processor patches are counted twice.
Reimplemented in OppositeFaceCellWave< Type, TrackingData >.
Definition at line 1145 of file FaceCellWave.C.
Foam::label iterate (const label maxIter) virtual
Iterate until no changes or maxIter reached.
Returns
the number of iterations taken.
Definition at line 1221 of file FaceCellWave.C.
Referenced by hexRef8::consistentSlowRefinement(), and OppositeFaceCellWave< Type, TrackingData >::OppositeFaceCellWave().
Member Data Documentation
const polyMesh& mesh_ protected
Reference to mesh.
Definition at line 106 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::FaceCellWave().
const labelPairList explicitConnections_ protected
Optional boundary faces that information should travel through.
Definition at line 111 of file FaceCellWave.H.
UList<Type>& allFaceInfo_ protected
Information for all faces.
Definition at line 116 of file FaceCellWave.H.
UList<Type>& allCellInfo_ protected
Information for all cells.
Definition at line 121 of file FaceCellWave.H.
TrackingData& td_ protected
Additional data to be passed into container.
Definition at line 126 of file FaceCellWave.H.
Referenced by FaceCellWave< Type, TrackingData >::setPropagationTol().
bitSet changedFace_ protected
Has face changed.
Definition at line 131 of file FaceCellWave.H.
bitSet changedCell_ protected
Has cell changed.
Definition at line 136 of file FaceCellWave.H.
DynamicList<label> changedFaces_ protected
List of changed faces.
Definition at line 141 of file FaceCellWave.H.
Referenced by OppositeFaceCellWave< Type, TrackingData >::OppositeFaceCellWave().
DynamicList<label> changedCells_ protected
Definition at line 144 of file FaceCellWave.H.
Referenced by OppositeFaceCellWave< Type, TrackingData >::OppositeFaceCellWave().
DynamicList<taggedInfoType> changedBaffles_ protected
Definition at line 148 of file FaceCellWave.H.
const bool hasCyclicPatches_ protected
Contains cyclics.
Definition at line 153 of file FaceCellWave.H.
const bool hasCyclicAMIPatches_ protected
Contains cyclicAMI.
Definition at line 158 of file FaceCellWave.H.
label nEvals_ protected
Number of evaluations.
Definition at line 163 of file FaceCellWave.H.
label nUnvisitedCells_ protected
Number of unvisited cells/faces.
Definition at line 168 of file FaceCellWave.H.
label nUnvisitedFaces_ protected
Definition at line 169 of file FaceCellWave.H.
const Foam::scalar geomTol_ = 1e-6 static protected
Definition at line 324 of file FaceCellWave.H.
Foam::scalar propagationTol_ = 0.01 static protected
Definition at line 325 of file FaceCellWave.H.
int dummyTrackData_ = 12345 static protected
Used as default trackdata value to satisfy default template.
argument.
Definition at line 332 of file FaceCellWave.H.
The documentation for this class was generated from the following files:
src/meshTools/algorithms/MeshWave/FaceCellWave.H
src/meshTools/algorithms/MeshWave/FaceCellWave.C