OpenFOAM: HashTable< T, Key, Hash > Class Template Reference
HashTable< T, Key, Hash > Class Template Reference
A HashTable similar to std::unordered_map.
Inherits HashTableCore.
Inherited by EdgeMap< Foam::List >, EdgeMap< label >, EdgeMap< scalar >, HashPtrTable< coordSystem::cylindrical, label, Hash< label > >, HashPtrTable< curve >, HashPtrTable< dragModel, interfacePair, interfacePair::symmHash >, HashPtrTable< exprResult >, HashPtrTable< Foam::colourTable >, HashPtrTable< Foam::Field >, HashPtrTable< Foam::Function1< Foam::Vector > >, HashPtrTable< Foam::GeometricField >, HashPtrTable< Foam::GeometricField, Foam::phasePairKey, Foam::phasePairKey::hash >, HashPtrTable< Foam::List >, HashPtrTable< Foam::OFstream >, HashPtrTable< Foam::surfaceWriter >, HashPtrTable< Foam::sutherlandTransport >, HashPtrTable< HashPtrTable< volScalarField >, phasePairKey, phasePairKey::hash >, HashPtrTable< IOobject >, HashPtrTable< surfaceScalarField, phasePairKey, phasePairKey::hash >, HashPtrTable< T, label, Hash< label > >, HashPtrTable< ThermoType >, HashPtrTable< volScalarField, phasePairKey, phasePairKey::hash >, HashSet< edge, Hash< edge > >, HashSet< Foam::fileName >, HashSet< Foam::string >, HashSet< label, Hash< label > >, HashSet< labelPairPair, labelPairPair::Hash<> >, HashSet< word >, Map< dictionary >, Map< Foam::edge >, Map< Foam::FixedList< int, 6 > >, Map< Foam::List >, Map< Foam::Pair< Foam::edge > >, Map< Foam::splitCell * >, Map< Foam::string >, Map< Foam::Vector >, Map< Foam::word >, Map< interfaceEntry >, Map< label >, and Map< scalar >.
Classes
class const_iterator
Forward iterator with const access.
class iterator
Forward iterator with non-const access.
class Iterator
Internally used base for iterator and const_iterator.
class key_iterator_base
An iterator wrapper for returning a reference to the key.
Public Types
typedef HashTable< T, Key, Hash > this_type
The template instance used for this HashTable.
typedef Key key_type
The second template parameter, type of keys used.
typedef T mapped_type
The first template parameter, type of objects contained.
typedef T value_type
Same as mapped_type for OpenFOAM HashTables.
typedef Hash hasher
The third template parameter, the hash index method.
typedef T & reference
Reference to the stored value_type.
typedef const T & const_reference
Const reference to the stored value_type.
typedef label difference_type
The type to represent the difference between two iterators.
typedef label size_type
The type that can represent the size of a HashTable.
using key_iterator = key_iterator_base< iterator >
Forward iterator returning the key.
using const_key_iterator = key_iterator_base< const_iterator >
Forward const iterator returning the key.
Public Member Functions
HashTable ()
Construct null with default (128) table capacity.
HashTable (const label size)
Construct given initial table capacity.
HashTable (Istream &is, const label size=128)
Construct from Istream with default table capacity.
HashTable (const this_type &ht)
Copy construct.
HashTable (this_type &&rhs)
Move construct.
HashTable (std::initializer_list< std::pair< Key, T >> list)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const noexcept
The size of the underlying table.
label size () const noexcept
The number of elements in table.
bool empty () const noexcept
True if the hash table is empty.
T & at (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const T & at (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
bool found (const Key &key) const
Return true if hashed entry is found in table.
iterator find (const Key &key)
Find and return an iterator set at the hashed entry.
const_iterator find (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const_iterator cfind (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const T & lookup (const Key &key, const T &deflt) const
Return hashed entry if it exists, or return the given default.
List< Key > toc () const
The table of contents (the keys) in unsorted order.
List< Key > sortedToc () const
The table of contents (the keys) in sorted order.
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
The table of contents (the keys) sorted according to the specified comparator.
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the keys.
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the values.
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the binary predicate applied to the keys and values.
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Count the number of keys that satisfy the unary predicate.
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Count the number of values that satisfy the unary predicate.
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Count the number of entries that satisfy the binary predicate.
template<class... Args>
bool emplace (const Key &key, Args &&...args)
Emplace insert a new entry, not overwriting existing entries.
bool insert (const Key &key, const T &obj)
Copy insert a new entry, not overwriting existing entries.
bool insert (const Key &key, T &&obj)
Move insert a new entry, not overwriting existing entries.
bool set (const Key &key, const T &obj)
Copy assign a new entry, overwriting existing entries.
bool set (const Key &key, T &&obj)
Move assign a new entry, overwriting existing entries.
bool erase (const iterator &iter)
Erase an entry specified by given iterator.
bool erase (const Key &key)
Erase an entry specified by the given key.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
Remove table entries given by keys of the other hash-table.
label erase (std::initializer_list< Key > keys)
Remove table entries given by the listed keys.
template<class InputIter >
label erase (InputIter first, InputIter last)
Remove multiple entries using an iterator range of keys.
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
Remove table entries given by the listed keys.
label erase (const UList< Key > &keys)
Remove table entries given by the listed keys.
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
Retain table entries given by keys of the other hash-table.
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their keys.
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their values.
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their key/value.
void resize (const label sz)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void swap (HashTable< T, Key, Hash > &rhs)
Swap contents into this table.
void transfer (HashTable< T, Key, Hash > &rhs)
Transfer contents into this table.
T & operator[] (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const T & operator[] (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
T & operator() (const Key &key)
Return existing entry or create a new entry.
T & operator() (const Key &key, const T &deflt)
Return existing entry or insert a new entry.
void operator= (const this_type &rhs)
Copy assign.
void operator= (std::initializer_list< std::pair< Key, T >> rhs)
Copy assign from an initializer list.
void operator= (this_type &&rhs)
Move assign.
bool operator== (const this_type &rhs) const
Equality. Tables are equal if all keys and values are equal, independent of order or underlying storage size.
bool operator!= (const this_type &rhs) const
The opposite of the equality operation.
this_type & operator+= (const this_type &rhs)
Add entries into this HashTable.
const_iterator_pair
< const_key_iterator,
this_type > keys () const
A const iterator begin/end pair for iterating over keys.
iterator begin ()
iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const iterator & end ()
iterator to signal the end for any HashTable
const const_iterator & end () const
const_iterator to signal the end for any HashTable
const const_iterator & cend () const
const_iterator to signal the end for any HashTable
Ostream & printInfo (Ostream &os) const
Print information.
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter>
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType, class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
HashTableCore ()=default
Construct null.
ClassName ("HashTable")
Define template name and debug.
Protected Member Functions
bool iterator_erase (node_type *&entry, label &index)
Low-level entry erasure using iterator internals.
Friends
class Iterator< true >
An iterator with const access to HashTable internals.
class Iterator< false >
An iterator with non-const access to HashTable internals.
Additional Inherited Members
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Return a canonical (power-of-two) of the requested size.
template<class IteratorType , class TableType >
static IteratorType iterator_begin (TableType &table)
Factory method to create a non-const iterator begin.
template<class IteratorType , class TableType >
static IteratorType iterator_cbegin (const TableType &table)
Factory method to create a const iterator begin.
template<class IteratorType >
static const IteratorType & iterator_end ()
Factory method to return an iterator end.
template<class IteratorType >
static const IteratorType & iterator_cend ()
Factory method to return an iterator cend.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable internal table size. Approximately labelMax/4.
Detailed Description
template<class T, class Key, class Hash>
class Foam::HashTable< T, Key, Hash >
A HashTable similar to std::unordered_map.
The entries are considered unordered since their placement depends on the method used to generate the hash key index, the table capacity, insertion order etc. When the key order is important, use the sortedToc() method to obtain a list of sorted keys and use that for further access.
Internally the table uses closed addressing into a flat storage space with collisions handled by linked-list chaining.
The end iterator of all hash-tables has a nullptr to the hash entry. Thus avoid separate allocation for each table and use a single one with a nullptr. The hash-table iterators always have an entry-pointer as the first member data, which allows reinterpret_cast from anything else with a nullptr as its first data member. The nullObject is such an item (with a nullptr data member).
Note
For historical reasons, dereferencing the table iterator (eg, *iter) returns a reference to the stored object value rather than the stored key/val pair like std::unordered_map does.
The HashTable iterator:
forAllConstIters(table, iter)
{
    Info<< "val:" << *iter << nl
        << "key:" << iter.key() << nl;
        << "val:" << iter.val() << nl;
}
whereas for the std::unordered_map iterator:
forAllConstIters(stdmap, iter)
{
    Info<< "key/val:" << *iter << nl
        << "key:" << iter->first << nl
        << "val:" << iter->second << nl;
}
This difference is most evident when using range-for syntax.
Source files
HashTable.H
HashTableI.H
HashTableIterI.H
HashTable.C
HashTableIO.C
HashTableIter.C
Definition at line 101 of file HashTable.H.
Member Typedef Documentation
typedef HashTable<T, Key, Hash> this_type
The template instance used for this HashTable.
Definition at line 167 of file HashTable.H.
typedef Key key_type
The second template parameter, type of keys used.
Definition at line 175 of file HashTable.H.
typedef T mapped_type
The first template parameter, type of objects contained.
Definition at line 180 of file HashTable.H.
typedef T value_type
Same as mapped_type for OpenFOAM HashTables.
Note that this is different than the std::map definition.
Definition at line 187 of file HashTable.H.
typedef Hash hasher
The third template parameter, the hash index method.
Definition at line 192 of file HashTable.H.
typedef T& reference
Reference to the stored value_type.
This type is usually 'value_type&'.
Definition at line 199 of file HashTable.H.
typedef const T& const_reference
Const reference to the stored value_type.
Definition at line 204 of file HashTable.H.
typedef label difference_type
The type to represent the difference between two iterators.
Definition at line 209 of file HashTable.H.
typedef label size_type
The type that can represent the size of a HashTable.
Definition at line 214 of file HashTable.H.
using key_iterator = key_iterator_base<iterator>
Forward iterator returning the key.
Definition at line 1102 of file HashTable.H.
using const_key_iterator = key_iterator_base<const_iterator>
Forward const iterator returning the key.
Definition at line 1107 of file HashTable.H.
Constructor & Destructor Documentation
HashTable ()
Construct null with default (128) table capacity.
Definition at line 32 of file HashTable.C.
HashTable (const label size) explicit
Construct given initial table capacity.
Definition at line 39 of file HashTable.C.
HashTable (Istream & is, const label size = 128)
Construct from Istream with default table capacity.
Definition at line 29 of file HashTableIO.C.
References i.
HashTable (const this_type & ht)
Copy construct.
HashTable (this_type && rhs)
Move construct.
HashTable (std::initializer_list< std::pair< Key, T >> list)
Construct from an initializer list.
Duplicate entries are handled by overwriting
Definition at line 85 of file HashTable.C.
~HashTable ()
Destructor.
Definition at line 101 of file HashTable.C.
Member Function Documentation
Foam::label capacity () const inline noexcept
The size of the underlying table.
Definition at line 38 of file HashTableI.H.
Foam::label size () const inline noexcept
The number of elements in table.
Definition at line 45 of file HashTableI.H.
Referenced by primitiveMesh::checkEdgeLength(), Foam::checkFireEdges(), IOobjectList::classesImpl(), objectRegistry::classesImpl(), coalCloudList::coalCloudList(), Foam::eraseImpl(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), meshRefinement::mergePatchFacesUndo(), plusEqOp< T, Key, Hash >::operator()(), Foam::polyMeshZipUpCells(), regionSplit::reduceRegions(), hexRef8::setUnrefinement(), cuttingSurfaceBase::walkCellCuts(), Foam::vtk::writeCellSetFaces(), Foam::ensightOutput::writeCloudPositions(), and meshRefinement::zonify().
bool empty () const inline noexcept
True if the hash table is empty.
Definition at line 52 of file HashTableI.H.
Referenced by triSurface::readTypes(), and regionSplit::reduceRegions().
T & at (const Key & key) inline
Find and return a hashed entry. FatalError if it does not exist.
Definition at line 59 of file HashTableI.H.
const T & at (const Key & key) const inline
Find and return a hashed entry. FatalError if it does not exist.
Definition at line 76 of file HashTableI.H.
bool found (const Key & key) const inline
Return true if hashed entry is found in table.
Definition at line 93 of file HashTableI.H.
Referenced by cellFeatures::faceMap(), lumpedPointMovement::forcesAndMoments(), meshToMesh0::meshToMesh0(), UnsortedMeshedSurface< Face >::New(), MeshedSurface< Face >::New(), STARCDMeshReader::readBoundary(), topoSet::set(), faMesh::updateMesh(), and cuttingSurfaceBase::walkCellCuts().
Foam::HashTable< T, Key, Hash >::iterator find (const Key & key) inline
Find and return an iterator set at the hashed entry.
If not found iterator = end()
Definition at line 107 of file HashTableI.H.
Referenced by meshToMesh0::meshToMesh0(), regionSplit::reduceRegions(), and meshRefinement::zonify().
Foam::HashTable< T, Key, Hash >::const_iterator find (const Key & key) const inline
Find and return an const_iterator set at the hashed entry.
If not found iterator = end()
Definition at line 123 of file HashTableI.H.
Foam::HashTable< T, Key, Hash >::const_iterator cfind (const Key & key) const inline
Find and return an const_iterator set at the hashed entry.
If not found iterator = end()
Definition at line 134 of file HashTableI.H.
Referenced by STLAsciiParse::beginSolid(), snappySnapDriver::getFacePoints(), PatchTools::matchPoints(), and PatchTools::pointNormals().
const T & lookup (const Key & key, const T & deflt) const inline
Return hashed entry if it exists, or return the given default.
Definition at line 205 of file HashTableI.H.
Referenced by enrichedPatch::calcEnrichedFaces(), and cuttingSurfaceBase::walkCellCuts().
Foam::List< Key > toc () const
The table of contents (the keys) in unsorted order.
Definition at line 114 of file HashTable.C.
Referenced by InflationInjection< CloudType >::InflationInjection(), objectRegistry::sortedNames(), and zoneMotion::zoneMotion().
Foam::List< Key > sortedToc () const
The table of contents (the keys) in sorted order.
Definition at line 129 of file HashTable.C.
Referenced by Foam::checkFireEdges(), DispersionRASModel< CloudType >::kModel(), Foam::listSwitches(), objectRegistry::names(), sampledPatch::needsUpdate(), Foam::polyMeshZipUpCells(), regionSplit::reduceRegions(), cuttingSurfaceBase::walkCellCuts(), Foam::vtk::writeFaceSet(), Foam::vtk::writePointSet(), Foam::ensightOutput::Detail::writeVolField(), and meshRefinement::zonify().
List<Key> sortedToc (const Compare & comp) const
The table of contents (the keys) sorted according to the specified comparator.
List<Key> tocKeys (const UnaryPredicate & pred, const bool invert = false) const
The table of contents (the keys) selected according to the unary predicate applied to the keys.
Parameters
invert changes the logic to select when the predicate is false
Returns
sorted list of selected keys
List<Key> tocValues (const UnaryPredicate & pred, const bool invert = false) const
The table of contents (the keys) selected according to the unary predicate applied to the values.
Parameters
invert changes the logic to select when the predicate is false
Returns
sorted list of selected keys
List<Key> tocEntries (const BinaryPredicate & pred, const bool invert = false) const
The table of contents (the keys) selected according to the binary predicate applied to the keys and values.
Parameters
invert changes the logic to select when the predicate is false
Returns
sorted list of selected keys
label countKeys (const UnaryPredicate & pred, const bool invert = false) const
Count the number of keys that satisfy the unary predicate.
Parameters
invert changes the logic to select when the predicate is false
label countValues (const UnaryPredicate & pred, const bool invert = false) const
Count the number of values that satisfy the unary predicate.
Parameters
invert changes the logic to select when the predicate is false
label countEntries (const BinaryPredicate & pred, const bool invert = false) const
Count the number of entries that satisfy the binary predicate.
Parameters
invert changes the logic to select when the predicate is false
bool emplace (const Key & key, Args &&... args) inline
Emplace insert a new entry, not overwriting existing entries.
Returns
True if the entry did not previously exist in the table.
Definition at line 150 of file HashTableI.H.
bool insert (const Key & key, const T & obj) inline
Copy insert a new entry, not overwriting existing entries.
Returns
True if the entry did not previously exist in the table.
Definition at line 161 of file HashTableI.H.
References args.
Referenced by STLAsciiParse::beginSolid(), surfaceInterpolate::interpolateFields(), meshToMesh0::meshToMesh0(), exprDriver::readTable(), regionSplit::reduceRegions(), combineFaces::setUnrefinement(), cuttingSurfaceBase::walkCellCuts(), meshReader::warnDuplicates(), and meshRefinement::zonify().
bool insert (const Key & key, T && obj) inline
Move insert a new entry, not overwriting existing entries.
Returns
True if the entry did not previously exist in the table.
Definition at line 172 of file HashTableI.H.
bool set (const Key & key, const T & obj) inline
Copy assign a new entry, overwriting existing entries.
Returns
True, since it always overwrites any entries.
Definition at line 183 of file HashTableI.H.
Referenced by interfaceDefinitions::interfaceDefinitions().
bool set (const Key & key, T && obj) inline
Move assign a new entry, overwriting existing entries.
Returns
True, since it always overwrites any entries.
Definition at line 194 of file HashTableI.H.
bool erase (const iterator & iter)
Erase an entry specified by given iterator.
This invalidates the iterator until the next ++ operation.
Includes a safeguard against the end-iterator such that the following is safe:
*     auto iter = table.find(unknownKey);
*     table.erase(iter);
*
which is what
table.erase(unknownKey)
does anyhow.
Returns
True if the corresponding entry existed and was removed
Definition at line 385 of file HashTable.C.
Referenced by cuttingSurfaceBase::walkCellCuts().
bool erase (const Key & key)
Erase an entry specified by the given key.
Returns
True if the entry existed and was removed
Definition at line 399 of file HashTable.C.
label erase (const HashTable< AnyType, Key, AnyHash > & other)
Remove table entries given by keys of the other hash-table.
The other hash-table must have the same type of key, but the type of values held and the hashing function are arbitrary.
Returns
The number of items removed
Foam::label erase (std::initializer_list< Key > keys) inline
Remove table entries given by the listed keys.
Returns
The number of items removed
Definition at line 435 of file HashTable.C.
label erase (InputIter first, InputIter last) inline
Remove multiple entries using an iterator range of keys.
label erase (const FixedList< Key, N > & keys) inline
Remove table entries given by the listed keys.
Returns
The number of items removed
Foam::label erase (const UList< Key > & keys) inline
Remove table entries given by the listed keys.
Returns
The number of items removed
Definition at line 456 of file HashTable.C.
References FixedList< T, N >::cbegin(), FixedList< T, N >::cend(), and erase().
label retain (const HashTable< AnyType, Key, AnyHash > & other)
Retain table entries given by keys of the other hash-table.
The other hash-table must have the same type of key, but the type of values held and the hashing function are arbitrary.
Returns
The number of items changed (removed)
label filterKeys (const UnaryPredicate & pred, const bool pruning = false)
Generalized means to filter table entries based on their keys.
Keep (or optionally prune) entries with keys that satisfy the unary predicate, which has the following signature:
* bool operator()(const Key& k);
*
For example,
* wordRes goodFields = ...;
* allFieldNames.filterKeys
* (
*     [&goodFields](const word& k){ return goodFields.match(k); }
*);
*
Returns
The number of items changed (removed)
label filterValues (const UnaryPredicate & pred, const bool pruning = false)
Generalized means to filter table entries based on their values.
Keep (or optionally prune) entries with values that satisfy the unary predicate, which has the following signature:
* bool operator()(const T& v);
*
Returns
The number of items changed (removed)
label filterEntries (const BinaryPredicate & pred, const bool pruning = false)
Generalized means to filter table entries based on their key/value.
Keep (or optionally prune) entries with keys/values that satisfy the binary predicate, which has the following signature:
* bool operator()(const Key& k, const T& v);
*
Returns
The number of items changed (removed)
void resize (const label sz)
Resize the hash table for efficiency.
Definition at line 546 of file HashTable.C.
Referenced by topoBitSet::topoBitSet(), topoBoolSet::topoBoolSet(), and Foam::HashSetOps::used().
void clear ()
Clear all entries from table.
Definition at line 623 of file HashTable.C.
Referenced by exprDriver::readTable(), regionSplit::reduceRegions(), and cuttingSurfaceBase::walkCellCuts().
void clearStorage ()
Clear the table entries and the table itself.
Equivalent to clear() followed by resize(0)
Definition at line 642 of file HashTable.C.
Referenced by objectRegistry::erase().
void swap (HashTable< T, Key, Hash > & rhs)
Swap contents into this table.
Definition at line 650 of file HashTable.C.
References clear(), and resize().
void transfer (HashTable< T, Key, Hash > & rhs)
Transfer contents into this table.
Definition at line 664 of file HashTable.C.
Referenced by primitiveMesh::checkEdgeLength().
T & operator[] (const Key & key) inline
Find and return a hashed entry. FatalError if it does not exist.
Definition at line 218 of file HashTableI.H.
const T & operator[] (const Key & key) const inline
Find and return a hashed entry. FatalError if it does not exist.
Definition at line 225 of file HashTableI.H.
T & operator() (const Key & key) inline
Return existing entry or create a new entry.
A newly created entry is created as a nameless T() and is thus value-initialized. For primitives, this will be zero.
Definition at line 232 of file HashTableI.H.
T & operator() (const Key & key, const T & deflt) inline
Return existing entry or insert a new entry.
Definition at line 248 of file HashTableI.H.
void operator= (const this_type & rhs)
Copy assign.
void operator= (std::initializer_list< std::pair< Key, T >> rhs)
Copy assign from an initializer list.
Duplicate entries are handled by overwriting
Definition at line 789 of file HashTable.C.
void operator= (this_type && rhs)
Move assign.
bool operator== (const this_type & rhs) const
Equality. Tables are equal if all keys and values are equal, independent of order or underlying storage size.
Definition at line 827 of file HashTable.C.
bool operator!= (const this_type & rhs) const
The opposite of the equality operation.
Definition at line 853 of file HashTable.C.
Foam::HashTable< T, Key, Hash > & operator+= (const this_type & rhs)
Add entries into this HashTable.
Definition at line 863 of file HashTable.C.
References Foam::operator==().
bool iterator_erase (node_type *& entry, label & index) protected
Low-level entry erasure using iterator internals.
This invalidates the iterator until the next ++ operation.
Returns
True if the corresponding entry existed and was removed
Definition at line 59 of file HashTableIter.C.
const_iterator_pair<const_key_iterator, this_type> keys () const inline
A const iterator begin/end pair for iterating over keys.
Definition at line 1112 of file HashTable.H.
Foam::HashTable< T, Key, Hash >::iterator begin () inline
iterator set to the beginning of the HashTable
Definition at line 245 of file HashTableIterI.H.
Referenced by Foam::kShellIntegration().
Foam::HashTable< T, Key, Hash >::const_iterator begin () const inline
const_iterator set to the beginning of the HashTable
Definition at line 253 of file HashTableIterI.H.
Foam::HashTable< T, Key, Hash >::const_iterator cbegin () const inline
const_iterator set to the beginning of the HashTable
Definition at line 261 of file HashTableIterI.H.
Referenced by multivariateScheme< Type, Scheme >::multivariateScheme(), and multivariateSelectionScheme< Type >::multivariateSelectionScheme().
const Foam::HashTable< T, Key, Hash >::iterator & end () inline
iterator to signal the end for any HashTable
Definition at line 269 of file HashTableIterI.H.
const Foam::HashTable< T, Key, Hash >::const_iterator & end () const inline
const_iterator to signal the end for any HashTable
Definition at line 277 of file HashTableIterI.H.
const Foam::HashTable< T, Key, Hash >::const_iterator & cend () const inline
const_iterator to signal the end for any HashTable
Definition at line 285 of file HashTableIterI.H.
Foam::Ostream & printInfo (Ostream & os) const
Print information.
Definition at line 53 of file HashTableIO.C.
Foam::Ostream & writeKeys (Ostream & os, const label shortLen = 0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
Using '0' suppresses line-breaks entirely.
Definition at line 90 of file HashTableIO.C.
Foam::List<Key> sortedToc (const Compare & comp) const
Definition at line 141 of file HashTable.C.
Foam::List<Key> tocKeys (const UnaryPredicate & pred, const bool invert) const
Definition at line 155 of file HashTable.C.
Foam::List<Key> tocValues (const UnaryPredicate & pred, const bool invert) const
Definition at line 181 of file HashTable.C.
Foam::List<Key> tocEntries (const BinaryPredicate & pred, const bool invert) const
Definition at line 207 of file HashTable.C.
Foam::label countKeys (const UnaryPredicate & pred, const bool invert) const
Definition at line 233 of file HashTable.C.
Foam::label countValues (const UnaryPredicate & pred, const bool invert) const
Definition at line 255 of file HashTable.C.
Foam::label countEntries (const BinaryPredicate & pred, const bool invert) const
Definition at line 277 of file HashTable.C.
Foam::label erase (InputIter first, InputIter last) inline
Definition at line 409 of file HashTable.C.
Foam::label erase (const FixedList< Key, N > & keys) inline
Definition at line 446 of file HashTable.C.
Foam::label erase (const HashTable< AnyType, Key, AnyHash > & other)
Definition at line 467 of file HashTable.C.
Foam::label retain (const HashTable< AnyType, Key, AnyHash > & other)
Definition at line 515 of file HashTable.C.
Foam::label filterKeys (const UnaryPredicate & pred, const bool pruning)
Definition at line 679 of file HashTable.C.
Foam::label filterValues (const UnaryPredicate & pred, const bool pruning)
Definition at line 706 of file HashTable.C.
Foam::label filterEntries (const BinaryPredicate & pred, const bool pruning)
Definition at line 733 of file HashTable.C.
Friends And Related Function Documentation
friend class Iterator< true > friend
An iterator with const access to HashTable internals.
Definition at line 232 of file HashTable.H.
friend class Iterator< false > friend
An iterator with non-const access to HashTable internals.
Definition at line 242 of file HashTable.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashTable/HashTable.H
src/OpenFOAM/containers/HashTables/HashTable/HashTable.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableI.H
src/OpenFOAM/containers/HashTables/HashTable/HashTableIO.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableIter.C
src/OpenFOAM/containers/HashTables/HashTable/HashTableIterI.H