OpenFOAM: d2dt2Scheme< Type > Class Template Reference
d2dt2Scheme< Type > Class Template Reference abstract
Abstract base class for finite volume d2dt2 schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, d2dt2Scheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
d2dt2Scheme (const fvMesh &mesh)
Construct from mesh.
d2dt2Scheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~d2dt2Scheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< d2dt2Scheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new d2dt2Scheme created on freestore.
Protected Member Functions
d2dt2Scheme (const d2dt2Scheme &)=delete
No copy construct.
void operator= (const d2dt2Scheme &)=delete
No copy assignment.
Protected Attributes
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::d2dt2Scheme< Type >
Abstract base class for finite volume d2dt2 schemes.
Source files
d2dt2Scheme.H
d2dt2Scheme.C
Definition at line 62 of file d2dt2Scheme.H.
Constructor & Destructor Documentation
d2dt2Scheme (const d2dt2Scheme< Type > &) protected delete
No copy construct.
d2dt2Scheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 112 of file d2dt2Scheme.H.
d2dt2Scheme (const fvMesh & mesh, Istream &) inline
Construct from mesh and Istream.
Definition at line 120 of file d2dt2Scheme.H.
virtual ~d2dt2Scheme () virtual default
Destructor.
Member Function Documentation
void operator= (const d2dt2Scheme< Type > &) protected delete
No copy assignment.
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , d2dt2Scheme< Type > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< d2dt2Scheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new d2dt2Scheme created on freestore.
Definition at line 39 of file d2dt2Scheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by Foam::fvc::d2dt2(), and Foam::fvm::d2dt2().
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 149 of file d2dt2Scheme.H.
Referenced by EulerD2dt2Scheme< Type >::EulerD2dt2Scheme(), and steadyStateD2dt2Scheme< Type >::steadyStateD2dt2Scheme().
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcD2dt2 (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
virtual tmp<fvMatrix<Type> > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
virtual tmp<fvMatrix<Type> > fvmD2dt2 (const dimensionedScalar & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
virtual tmp<fvMatrix<Type> > fvmD2dt2 (const volScalarField & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in EulerD2dt2Scheme< Type >, and steadyStateD2dt2Scheme< Type >.
Member Data Documentation
const fvMesh& mesh_ protected
Definition at line 71 of file d2dt2Scheme.H.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/d2dt2Schemes/d2dt2Scheme/d2dt2Scheme.H
src/finiteVolume/finiteVolume/d2dt2Schemes/d2dt2Scheme/d2dt2Scheme.C