OpenFOAM: IOstreamOption Class Reference
IOstreamOption Class Reference
The IOstreamOption is a simple container for options an IOstream can normally have. For example, ascii/binary, uncompressed/compressed, ...
Classes
class versionNumber
Representation of a major/minor version number.
Public Types
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Public Member Functions
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Static Public Member Functions
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Static Public Attributes
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Detailed Description
The IOstreamOption is a simple container for options an IOstream can normally have. For example, ascii/binary, uncompressed/compressed, ...
Source files
IOstreamOption.H
IOstreamOption.C
Definition at line 53 of file IOstreamOption.H.
Member Enumeration Documentation
enum streamFormat : char
Data format (ascii | binary)
Enumerator
ASCII
"ascii"
BINARY
"binary"
Definition at line 62 of file IOstreamOption.H.
enum compressionType : char
Compression treatment (UNCOMPRESSED | COMPRESSED)
Enumerator
UNCOMPRESSED
compression = false
COMPRESSED
compression = true
Definition at line 71 of file IOstreamOption.H.
Constructor & Destructor Documentation
IOstreamOption () inline noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
Definition at line 264 of file IOstreamOption.H.
IOstreamOption (streamFormat format) inline explicit noexcept
Construct with format. (default: uncompressed, currentVersion)
Definition at line 274 of file IOstreamOption.H.
IOstreamOption (streamFormat format, compressionType compression, versionNumber version = currentVersion) inline noexcept
Construct with format and compression, optionally with version.
Definition at line 285 of file IOstreamOption.H.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) inline noexcept
Construct with format, version, compression.
Definition at line 300 of file IOstreamOption.H.
Member Function Documentation
Foam::IOstreamOption::streamFormat formatEnum (const word & formatName) static
The stream format enum corresponding to the string.
Expected "ascii", "binary"
Definition at line 49 of file IOstreamOption.C.
Referenced by VTKsurfaceFormatCore::formatOptions(), and VTPsurfaceFormatCore::formatOptions().
Foam::IOstreamOption::compressionType compressionEnum (const word & compName) static
The compression enum corresponding to the string.
Expected "true", "false", "on", "off", etc.
Definition at line 66 of file IOstreamOption.C.
streamFormat format () const inline noexcept
Get the current stream format.
Definition at line 334 of file IOstreamOption.H.
Referenced by codeStream::evaluate(), IOobject::readHeader(), Foam::setformat(), Foam::ensightOutput::writeCloudPositions(), UList< T >::writeEntry(), and IndirectListBase< T, Addr >::writeList().
streamFormat format (const streamFormat format) inline noexcept
Set the stream format.
Returns
the previous value
Definition at line 344 of file IOstreamOption.H.
streamFormat format (const word & formatName) inline
Set the stream format, from string value.
Returns
the previous value
Definition at line 356 of file IOstreamOption.H.
compressionType compression () const inline noexcept
Get the stream compression.
Definition at line 366 of file IOstreamOption.H.
compressionType compression (const compressionType comp) inline noexcept
Set the stream compression.
Returns
the previous value
Definition at line 376 of file IOstreamOption.H.
compressionType compression (const word & compressionName) inline
Set the stream compression, from string value.
Returns
the previous value
Definition at line 388 of file IOstreamOption.H.
versionNumber version () const inline noexcept
Get the stream version.
Definition at line 398 of file IOstreamOption.H.
Referenced by IOobject::readHeader(), mappedPatchBase::readListOrField(), and Foam::setversion().
versionNumber version (const versionNumber verNum) inline noexcept
Set the stream version.
Returns
the previous value
Definition at line 408 of file IOstreamOption.H.
Member Data Documentation
const Foam::Enum< Foam::IOstreamOption::streamFormat > formatNames static
Stream format names (ascii, binary)
Definition at line 222 of file IOstreamOption.H.
Referenced by Foam::operator<<().
const Foam::IOstreamOption::versionNumber originalVersion static
The original version number.
Definition at line 227 of file IOstreamOption.H.
const Foam::IOstreamOption::versionNumber currentVersion static
The current version number.
Definition at line 232 of file IOstreamOption.H.
Referenced by lumpedPointMovement::writeData().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstreamOption.H
src/OpenFOAM/db/IOstreams/IOstreams/IOstreamOption.C