OpenFOAM: laplacianScheme< Type, GType > Class Template Reference
laplacianScheme< Type, GType > Class Template Reference abstract
Laplacian schemes
Abstract base class for laplacian schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, laplacianScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
laplacianScheme (const fvMesh &mesh)
Construct from mesh.
laplacianScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
laplacianScheme (const fvMesh &mesh, const tmp< surfaceInterpolationScheme< GType >> &igs, const tmp< snGradScheme< Type >> &sngs)
Construct from mesh, interpolation and snGradScheme schemes.
virtual ~laplacianScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)=0
virtual tmp< GeometricField
< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< laplacianScheme
< Type, GType > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new laplacianScheme created on freestore.
Protected Attributes
const fvMesh & mesh_
tmp
< surfaceInterpolationScheme
< GType > > tinterpGammaScheme_
tmp< snGradScheme< Type > > tsnGradScheme_
Detailed Description
template<class Type, class GType>
class Foam::fv::laplacianScheme< Type, GType >
Abstract base class for laplacian schemes.
Source files
laplacianScheme.H
laplacianScheme.C
Definition at line 66 of file laplacianScheme.H.
Constructor & Destructor Documentation
laplacianScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 120 of file laplacianScheme.H.
laplacianScheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 130 of file laplacianScheme.H.
References snGradScheme< Type >::New(), surfaceInterpolationScheme< Type >::New(), laplacianScheme< Type, GType >::tinterpGammaScheme_, and laplacianScheme< Type, GType >::tsnGradScheme_.
laplacianScheme (const fvMesh & mesh, const tmp< surfaceInterpolationScheme< GType >> & igs, const tmp< snGradScheme< Type >> & sngs) inline
Construct from mesh, interpolation and snGradScheme schemes.
Definition at line 151 of file laplacianScheme.H.
virtual ~laplacianScheme () virtual default
Destructor.
Member Function Documentation
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , laplacianScheme< Type, GType > , Istream , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< laplacianScheme< Type, GType > > New (const fvMesh & mesh, Istream & schemeData) static
Return a pointer to a new laplacianScheme created on freestore.
Definition at line 41 of file laplacianScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by Foam::fvc::laplacian(), and Foam::fvm::laplacian().
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 186 of file laplacianScheme.H.
virtual tmp<fvMatrix<Type> > fvmLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
tmp< fvMatrix< Type > > fvmLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 84 of file laplacianScheme.C.
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcLaplacian (const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
virtual tmp<GeometricField<Type, fvPatchField, volMesh> > fvcLaplacian (const GeometricField< GType, fvsPatchField, surfaceMesh > & , const GeometricField< Type, fvPatchField, volMesh > &) pure virtual
Implemented in gaussLaplacianScheme< Type, GType >.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcLaplacian (const GeometricField< GType, fvPatchField, volMesh > & gamma, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Definition at line 96 of file laplacianScheme.C.
Member Data Documentation
const fvMesh& mesh_ protected
Definition at line 75 of file laplacianScheme.H.
tmp<surfaceInterpolationScheme<GType> > tinterpGammaScheme_ protected
Definition at line 76 of file laplacianScheme.H.
Referenced by laplacianScheme< Type, GType >::laplacianScheme().
tmp<snGradScheme<Type> > tsnGradScheme_ protected
Definition at line 77 of file laplacianScheme.H.
Referenced by laplacianScheme< Type, GType >::laplacianScheme().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.H
src/finiteVolume/finiteVolume/laplacianSchemes/laplacianScheme/laplacianScheme.C