OpenFOAM: NURBS3DSurface Class Reference
NURBS3DSurface Class Reference
A NURBS 3D surface.
Public Member Functions
NURBS3DSurface (const List< vector > &CPs, const label nPointsU, const label nPointsV, const NURBSbasis &uBasis, const NURBSbasis &vBasis, const word name="NURBS3DSurface")
Construct from number of control points and basis functions.
NURBS3DSurface (const List< vector > &CPs, const List< scalar > &weights, const label nPointsU, const label nPointsV, const NURBSbasis &uBasis, const NURBSbasis &vBasis, const word name="NURBS3DSurface")
Construct from number of control points, weights and basis functions.
NURBS3DSurface (const List< vector > &CPs, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const word name="NURBS3DSurface")
Construct from control points, basis degree and number of points.
NURBS3DSurface (const List< vector > &CPs, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const scalarField &knotsU, const scalarField &knotsV, const word name="NURBS3DSurface")
Construct from control points, basis degree, knots and number of.
NURBS3DSurface (const List< vector > &CPs, const List< scalar > &weights, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const word name="NURBS3DSurface")
Construct from control points, weights, basis degree, and number of.
NURBS3DSurface (const List< vector > &CPs, const List< scalar > &weights, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const scalarField &knotsU, const scalarField &knotsV, const word name="NURBS3DSurface")
Construct from control points, weights, basis degree, knots and.
NURBS3DSurface (const NURBS3DSurface &)
Construct as copy.
~NURBS3DSurface ()=default
Destructor.
void setNrmOrientation (const vector &givenNrm, const scalar u, const scalar v)
void flipNrmOrientation ()
Flip the orientation of the nrm.
void setCPs (const List< vector > &CPs)
void setWeights (const scalarList &weights)
void setName (const word &name)
void buildSurface ()
void invertU ()
void invertV ()
void invertUV ()
void makeEquidistant (const label lenAcc=25, const label maxIter=10, const label spacingCorrInterval=-1, const scalar tolerance=1.e-5)
vector surfacePoint (const scalar &u, const scalar &v)
scalarList findClosestSurfacePoint (const vector &targetPoint, const label maxIter=100, const scalar tolerance=1.e-6)
tmp< vector2DField > findClosestSurfacePoint (const vectorField &targetPoints, const label maxIter=100, const scalar tolerance=1.e-6)
scalarList findClosestSurfacePoint (const vector &targetPoint, const scalar &uInitGuess, const scalar &vInitGuess, const label maxIter=100, const scalar tolerance=1.e-6)
const vector nrm (scalar u, scalar v)
List< scalarList > genEquidistant (const label nUPts=100, const label nVPts=100, const label lenAcc=25, const label maxIter=10, const label spacingCorrInterval=-1, const scalar tolerance=1.e-5)
Generate points on the surface which are evenly spaced in cartesian.
bool checkRangeU (const scalar u, const label CPI, const label uDegree) const
bool checkRangeU (const scalar u, const label CPI) const
bool checkRangeV (const scalar v, const label CPI, const label vDegree) const
bool checkRangeV (const scalar v, const label CPI) const
bool checkRangeUV (const scalar v, const scalar u, const label CPI, const label uDegree, const label vDegree) const
bool checkRangeUV (const scalar v, const scalar u, const label CPI) const
scalar lengthU (const label vIConst, const label uIStart, const label uIEnd) const
scalar lengthU (const scalar vConst, const scalar uStart, const scalar uEnd, const label nPts) const
scalar lengthU (const label vIConst) const
scalar lengthU (const scalar vConst) const
scalar lengthV (const label uIConst, const label vIStart, const label vIEnd) const
scalar lengthV (const scalar uConst, const scalar vStart, const scalar vEnd, const label nPts) const
scalar lengthV (const label uIConst) const
scalar lengthV (const scalar uConst) const
vector surfaceDerivativeU (const scalar u, const scalar v) const
Surface derivative wrt u at point u,v.
vector surfaceDerivativeV (const scalar u, const scalar v) const
Surface derivative wrt v at point u,v.
vector surfaceDerivativeUV (const scalar u, const scalar v) const
Surface second derivative wrt u and v at point u,v.
vector surfaceDerivativeUU (const scalar u, const scalar v) const
Surface second derivative wrt u at point u,v.
vector surfaceDerivativeVV (const scalar u, const scalar v) const
Surface second derivative wrt v at point u,v.
scalar surfaceDerivativeCP (const scalar u, const scalar v, const label CPI) const
Surface derivative wrt the weight of CPI at point u,v.
vector surfaceDerivativeW (const scalar u, const scalar v, const label CPI) const
Surface derivative wrt WI at point u,v.
scalar lengthDerivativeU (const scalar vConst, const scalar uStart, const scalar uEnd, const label nPts) const
Surface derivative wrt u length along v=const contour range.
scalar lengthDerivativeV (const scalar uConst, const scalar vStart, const scalar vEnd, const label nPts) const
Surface derivative wrt v length along u=const contour range.
const NURBSbasis & getBasisFunctionU () const
Get basis function.
const NURBSbasis & getBasisFunctionV () const
const List< vector > & getCPs () const
Get CPs.
const scalarList & getWeights () const
Get weights.
const scalarList & getParametricCoordinatesU () const
Get parametric coordinates.
const scalarList & getParametricCoordinatesV () const
const word & getName () const
Get name.
label getNPtsU () const
Get number of point in u direction.
label getNPtsV () const
Get number of point in u direction.
const labelList & getBoundaryCPIDs ()
Get IDs of boundary control points.
const labelList & getBoundaryCPIs ()
const label & whichBoundaryCPI (const label &globalCPI)
Get the boundary CP ID based on the global CP ID.
label nrmOrientation () const
Return the nrm sgn relation to the u=0 nrm.
const vector & givenInitNrm () const
Return the initial nrmal given to compare to the Curve's nrmals.
const labelList & getCPsUCPIs () const
Return ID in u direction for a given cp ID.
const labelList & getCPsVCPIs () const
Return ID in v direction for a given cp ID.
void write ()
Write curve to file.
void write (const word fileName)
void write (const fileName dirName, const fileName fileName)
void writeWParses ()
void writeWParses (const word fileName)
void writeWParses (const fileName dirName, const fileName fileName)
void writeVTK (const fileName vtkDirName, const fileName vtkFileName)
Public Member Functions inherited from Field< Type >
constexpr Field () noexcept
Construct null.
Field (const label len)
Construct given size.
Field (const label len, const Type &val)
Construct given size and initial value.
Field (const label len, const zero)
Construct given size and initial values of zero.
Field (const Field< Type > &fld)
Copy construct.
Field (const UList< Type > &list)
Copy construct from UList<Type>
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Copy construct from IndirectList.
Field (Field< Type > &&fld)
Move construct from Field.
Field (List< Type > &&list)
Move construct from List.
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Move construct from DynamicList.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Uses supplied uniform value for unmapped items.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Uses supplied values for unmapped items.
Field (Field< Type > &fld, bool reuse)
Copy construct or re-use as specified.
Field (const tmp< Field< Type >> &tfld)
Copy or move construct from tmp.
Field (Istream &is)
Construct from Istream.
Field (const word &keyword, const dictionary &dict, const label len)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field (negative).
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
Copy assignment.
void operator= (const tmp< Field< Type >> &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (Field< Type > &&rhs)
Move assignment.
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
Value assignment.
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Construct null, with refCount zero.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from List< Type >
constexpr List () noexcept
Null constructor.
List (const label len)
Construct with given size.
List (const label len, const Type &val)
Construct with given size and value for all elements.
List (const label len, const zero)
Construct with given size initializing all elements to zero.
List (const one, const Type &val)
Construct with length=1, copying the value as the only content.
List (const one, Type &&val)
Construct with length=1, moving the value as the only content.
List (const one, const zero)
Construct with length=1, initializing content to zero.
List (const List< Type > &a)
Copy construct from list.
List (const UList< Type > &a)
Copy construct contents from list.
List (List< Type > &a, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &list, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
List (const FixedList< Type, N > &list)
Construct as copy of FixedList<T, N>
List (const PtrList< Type > &list)
Construct as copy of PtrList<T>
List (const SLList< Type > &list)
Construct as copy of SLList<T>
List (const IndirectListBase< Type, Addr > &list)
Construct as copy of IndirectList contents.
List (std::initializer_list< Type > list)
Construct from an initializer list.
List (List< Type > &&list)
Move construct from List.
List (DynamicList< Type, SizeMin > &&list)
Move construct from DynamicList.
List (SortableList< Type > &&list)
Move construct from SortableList.
List (SLList< Type > &&list)
Move construct from SLList.
List (Istream &is)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label newSize)
Adjust allocated size of list.
void resize (const label newSize, const Type &val)
Adjust allocated size of list and set val for new elements.
void setSize (const label newSize)
Alias for resize(const label)
void setSize (const label newSize, const Type &val)
Alias for resize(const label, const T&)
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &val)
Append an element at the end of the list.
void append (Type &&val)
Move append an element at the end of the list.
void append (const UList< Type > &list)
Append a List to the end of this list.
void append (const IndirectListBase< Type, Addr > &list)
Append IndirectList contents at the end of this list.
void transfer (List< Type > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (DynamicList< Type, SizeMin > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (SortableList< Type > &list)
Transfer the contents of the argument List into this list and annul the argument list.
Type & newElmt (const label i)
Return subscript-checked element of UList and resizing the list if required.
void operator= (const UList< Type > &a)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &list)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &list)
Assignment to SLList operator. Takes linear time.
void operator= (const IndirectListBase< Type, Addr > &list)
Assignment from IndirectList. Takes linear time.
void operator= (std::initializer_list< Type > list)
Assignment to an initializer list.
void operator= (const Type &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (List< Type > &&list)
Move assignment. Takes constant time.
void operator= (DynamicList< Type, SizeMin > &&list)
Move assignment. Takes constant time.
void operator= (SortableList< Type > &&list)
Move assignment. Takes constant time.
void operator= (SLList< Type > &&list)
Move assignment. Takes constant time.
void shallowCopy (const UList< Type > &)=delete
No shallowCopy permitted.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type set (const label i, bool val=true)
A bitSet::set() method for a list of bool.
Public Member Functions inherited from UList< Type >
label size () const noexcept
The number of elements in the UList.
void writeEntry (const word &keyword, Ostream &os) const
Write the List as a dictionary entry with keyword.
void operator= (const Type &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
constexpr UList () noexcept
Null constructor.
UList (Type *__restrict__ v, label size) noexcept
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const Type & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
Type & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const Type & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
Type & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
std::streamsize byteSize () const
Return the binary size in number of characters of the UList if the element is a primitive type.
const Type * cdata () const
Return a const pointer to the first data element.
Type * data ()
Return a pointer to the first data element.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is within valid range [0,size].
void checkIndex (const label i) const
Check index is within valid range [0,size)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const Type &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const Type &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const Type &val, const label start=0) const
True if the value if found in the list.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element. Fatal on an empty list.
void swapLast (const label i)
Swap element with the last element. Fatal on an empty list.
void shallowCopy (const UList< Type > &list)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &list)
Copy elements of the given UList.
Type & operator[] (const label i)
Return element of UList.
const Type & operator[] (const label i) const
Return element of constant UList.
UList< Type > operator[] (const labelRange &range)
Return (start,size) subset from UList with non-const access.
const UList< Type > operator[] (const labelRange &range) const
Return (start,size) subset from UList with const access.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
bool empty () const noexcept
True if the UList is empty (ie, size() is zero)
void swap (UList< Type > &list)
Swap content with another UList of the same type in constant time.
bool operator== (const UList< Type > &a) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &a) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &list) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &a) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &a) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &a) const
Return true if !(a < b). Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type test (const label i) const
A bitSet::test() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type get (const label i) const
A bitSet::get() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type unset (const label i)
A bitSet::unset() method for a list of bool.
Additional Inherited Members
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
The value type the list contains.
typedef Type * pointer
The pointer type for non-const access to value_type items.
typedef const Type * const_pointer
The pointer type for const access to value_type items.
typedef Type & reference
The type used for storing into value_type objects.
typedef const Type & const_reference
The type used for reading from constant value_type objects.
typedef Type * iterator
Random access iterator for traversing a UList.
typedef const Type * const_iterator
Random access iterator for traversing a UList.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return nullObject reference field.
static autoPtr< Field< Type > > New (Istream &is)
Return a pointer to a new Field created on freestore.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on freestore without setting patchField values.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a UList reference to a nullObject.
static constexpr label max_size () noexcept
The size of the largest possible UList.
Static Public Attributes inherited from FieldBase
static const char *const typeName
Typename for Field.
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from UList< Type >
void size (const label n) noexcept
Override size to be inconsistent with allocated storage.
void writeEntry (Ostream &os) const
Write the UList with its compound type.
labelRange validateRange (const labelRange &range) const
Return a validated (start,size) subset range, which means that it always addresses a valid section of the list.
UList< Type > & operator= (const UList< Type > &)=delete
No copy assignment (default: shallow copy)
Detailed Description
A NURBS 3D surface.
Source files
NURBS3DSurface.H
NURBS3DSurface.C
Definition at line 50 of file NURBS3DSurface.H.
Constructor & Destructor Documentation
NURBS3DSurface (const List< vector > & CPs, const label nPointsU, const label nPointsV, const NURBSbasis & uBasis, const NURBSbasis & vBasis, const word name = "NURBS3DSurface")
Construct from number of control points and basis functions.
Definition at line 301 of file NURBS3DSurface.C.
NURBS3DSurface (const List< vector > & CPs, const List< scalar > & weights, const label nPointsU, const label nPointsV, const NURBSbasis & uBasis, const NURBSbasis & vBasis, const word name = "NURBS3DSurface")
Construct from number of control points, weights and basis functions.
Definition at line 338 of file NURBS3DSurface.C.
NURBS3DSurface (const List< vector > & CPs, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const word name = "NURBS3DSurface")
Construct from control points, basis degree and number of points.
Definition at line 376 of file NURBS3DSurface.C.
NURBS3DSurface (const List< vector > & CPs, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const scalarField & knotsU, const scalarField & knotsV, const word name = "NURBS3DSurface")
Construct from control points, basis degree, knots and number of.
points
Definition at line 424 of file NURBS3DSurface.C.
NURBS3DSurface (const List< vector > & CPs, const List< scalar > & weights, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const word name = "NURBS3DSurface")
Construct from control points, weights, basis degree, and number of.
points
Definition at line 474 of file NURBS3DSurface.C.
NURBS3DSurface (const List< vector > & CPs, const List< scalar > & weights, const label nPointsU, const label nPointsV, const label uDegree, const label vDegree, const label nCPsU, const label nCPsV, const scalarField & knotsU, const scalarField & knotsV, const word name = "NURBS3DSurface")
Construct from control points, weights, basis degree, knots and.
number of points
Definition at line 524 of file NURBS3DSurface.C.
NURBS3DSurface (const NURBS3DSurface &)
Construct as copy.
~NURBS3DSurface () default
Destructor.
Member Function Documentation
void setNrmOrientation (const vector & givenNrm, const scalar u, const scalar v)
Definition at line 578 of file NURBS3DSurface.C.
void flipNrmOrientation ()
Flip the orientation of the nrm.
Definition at line 606 of file NURBS3DSurface.C.
void setCPs (const List< vector > & CPs)
Definition at line 619 of file NURBS3DSurface.C.
void setWeights (const scalarList & weights)
Definition at line 625 of file NURBS3DSurface.C.
void setName (const word & name)
Definition at line 631 of file NURBS3DSurface.C.
void buildSurface ()
Definition at line 637 of file NURBS3DSurface.C.
References Foam::name().
void invertU ()
Definition at line 696 of file NURBS3DSurface.C.
void invertV ()
Definition at line 725 of file NURBS3DSurface.C.
void invertUV ()
Definition at line 754 of file NURBS3DSurface.C.
void makeEquidistant (const label lenAcc = 25, const label maxIter = 10, const label spacingCorrInterval = -1, const scalar tolerance = 1.e-5)
Definition at line 785 of file NURBS3DSurface.C.
vector surfacePoint (const scalar & u, const scalar & v)
Definition at line 871 of file NURBS3DSurface.C.
scalarList findClosestSurfacePoint (const vector & targetPoint, const label maxIter = 100, const scalar tolerance = 1.e-6)
Definition at line 918 of file NURBS3DSurface.C.
tmp< vector2DField > findClosestSurfacePoint (const vectorField & targetPoints, const label maxIter = 100, const scalar tolerance = 1.e-6)
Definition at line 1062 of file NURBS3DSurface.C.
scalarList findClosestSurfacePoint (const vector & targetPoint, const scalar & uInitGuess, const scalar & vInitGuess, const label maxIter = 100, const scalar tolerance = 1.e-6)
Definition at line 1202 of file NURBS3DSurface.C.
const vector nrm (scalar u, scalar v)
Definition at line 1258 of file NURBS3DSurface.C.
List< scalarList > genEquidistant (const label nUPts = 100, const label nVPts = 100, const label lenAcc = 25, const label maxIter = 10, const label spacingCorrInterval = -1, const scalar tolerance = 1.e-5)
Generate points on the surface which are evenly spaced in cartesian.
coordinate distances.
Definition at line 1278 of file NURBS3DSurface.C.
bool checkRangeU (const scalar u, const label CPI, const label uDegree) const
Definition at line 1374 of file NURBS3DSurface.C.
bool checkRangeU (const scalar u, const label CPI) const
Definition at line 1387 of file NURBS3DSurface.C.
bool checkRangeV (const scalar v, const label CPI, const label vDegree) const
Definition at line 1399 of file NURBS3DSurface.C.
bool checkRangeV (const scalar v, const label CPI) const
Definition at line 1412 of file NURBS3DSurface.C.
bool checkRangeUV (const scalar v, const scalar u, const label CPI, const label uDegree, const label vDegree) const
Definition at line 1424 of file NURBS3DSurface.C.
bool checkRangeUV (const scalar v, const scalar u, const label CPI) const
Definition at line 1442 of file NURBS3DSurface.C.
scalar lengthU (const label vIConst, const label uIStart, const label uIEnd) const
Definition at line 1456 of file NURBS3DSurface.C.
Referenced by NURBS3DSurface::lengthU(), and NURBS3DSurface::lengthV().
scalar lengthU (const scalar vConst, const scalar uStart, const scalar uEnd, const label nPts) const
Definition at line 1490 of file NURBS3DSurface.C.
scalar lengthU (const label vIConst) const
Definition at line 1520 of file NURBS3DSurface.C.
scalar lengthU (const scalar vConst) const
Definition at line 1526 of file NURBS3DSurface.C.
References NURBS3DSurface::lengthU().
scalar lengthV (const label uIConst, const label vIStart, const label vIEnd) const
Definition at line 1533 of file NURBS3DSurface.C.
References NURBS3DSurface::lengthU().
Referenced by NURBS3DSurface::lengthV().
scalar lengthV (const scalar uConst, const scalar vStart, const scalar vEnd, const label nPts) const
Definition at line 1567 of file NURBS3DSurface.C.
scalar lengthV (const label uIConst) const
Definition at line 1597 of file NURBS3DSurface.C.
scalar lengthV (const scalar uConst) const
Definition at line 1603 of file NURBS3DSurface.C.
References NURBS3DSurface::lengthV().
vector surfaceDerivativeU (const scalar u, const scalar v) const
Surface derivative wrt u at point u,v.
Definition at line 1612 of file NURBS3DSurface.C.
vector surfaceDerivativeV (const scalar u, const scalar v) const
Surface derivative wrt v at point u,v.
Definition at line 1654 of file NURBS3DSurface.C.
vector surfaceDerivativeUV (const scalar u, const scalar v) const
Surface second derivative wrt u and v at point u,v.
Definition at line 1696 of file NURBS3DSurface.C.
vector surfaceDerivativeUU (const scalar u, const scalar v) const
Surface second derivative wrt u at point u,v.
Definition at line 1758 of file NURBS3DSurface.C.
vector surfaceDerivativeVV (const scalar u, const scalar v) const
Surface second derivative wrt v at point u,v.
Definition at line 1814 of file NURBS3DSurface.C.
scalar surfaceDerivativeCP (const scalar u, const scalar v, const label CPI) const
Surface derivative wrt the weight of CPI at point u,v.
Definition at line 1870 of file NURBS3DSurface.C.
vector surfaceDerivativeW (const scalar u, const scalar v, const label CPI) const
Surface derivative wrt WI at point u,v.
Definition at line 1912 of file NURBS3DSurface.C.
scalar lengthDerivativeU (const scalar vConst, const scalar uStart, const scalar uEnd, const label nPts) const
Surface derivative wrt u length along v=const contour range.
Definition at line 1955 of file NURBS3DSurface.C.
scalar lengthDerivativeV (const scalar uConst, const scalar vStart, const scalar vEnd, const label nPts) const
Surface derivative wrt v length along u=const contour range.
Definition at line 1993 of file NURBS3DSurface.C.
const NURBSbasis& getBasisFunctionU () const inline
Get basis function.
Definition at line 501 of file NURBS3DSurface.H.
const NURBSbasis& getBasisFunctionV () const inline
Definition at line 506 of file NURBS3DSurface.H.
const List<vector>& getCPs () const inline
Get CPs.
Definition at line 514 of file NURBS3DSurface.H.
const scalarList& getWeights () const inline
Get weights.
Definition at line 522 of file NURBS3DSurface.H.
const scalarList& getParametricCoordinatesU () const inline
Get parametric coordinates.
Definition at line 530 of file NURBS3DSurface.H.
const scalarList& getParametricCoordinatesV () const inline
Definition at line 535 of file NURBS3DSurface.H.
const word& getName () const inline
Get name.
Definition at line 543 of file NURBS3DSurface.H.
label getNPtsU () const inline
Get number of point in u direction.
Definition at line 551 of file NURBS3DSurface.H.
label getNPtsV () const inline
Get number of point in u direction.
Definition at line 559 of file NURBS3DSurface.H.
const labelList & getBoundaryCPIDs ()
Get IDs of boundary control points.
Definition at line 2032 of file NURBS3DSurface.C.
Referenced by NURBS3DSurface::whichBoundaryCPI().
const labelList & getBoundaryCPIs ()
Definition at line 2070 of file NURBS3DSurface.C.
const label & whichBoundaryCPI (const label & globalCPI)
Get the boundary CP ID based on the global CP ID.
Definition at line 2076 of file NURBS3DSurface.C.
References NURBS3DSurface::getBoundaryCPIDs().
label nrmOrientation () const inline
Return the nrm sgn relation to the u=0 nrm.
Definition at line 579 of file NURBS3DSurface.H.
const vector& givenInitNrm () const inline
Return the initial nrmal given to compare to the Curve's nrmals.
Definition at line 587 of file NURBS3DSurface.H.
const labelList& getCPsUCPIs () const inline
Return ID in u direction for a given cp ID.
Definition at line 595 of file NURBS3DSurface.H.
const labelList& getCPsVCPIs () const inline
Return ID in v direction for a given cp ID.
Definition at line 603 of file NURBS3DSurface.H.
void write ()
Write curve to file.
Definition at line 2089 of file NURBS3DSurface.C.
Referenced by NURBS3DSurface::write().
void write (const word fileName)
Definition at line 2095 of file NURBS3DSurface.C.
References NURBS3DSurface::write().
void write (const fileName dirName, const fileName fileName)
Definition at line 2152 of file NURBS3DSurface.C.
void writeWParses ()
Definition at line 2209 of file NURBS3DSurface.C.
Referenced by NURBS3DSurface::writeWParses().
void writeWParses (const word fileName)
Definition at line 2215 of file NURBS3DSurface.C.
References NURBS3DSurface::writeWParses().
void writeWParses (const fileName dirName, const fileName fileName)
Definition at line 2275 of file NURBS3DSurface.C.
void writeVTK (const fileName vtkDirName, const fileName vtkFileName)
Definition at line 2338 of file NURBS3DSurface.C.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DSurface/NURBS3DSurface.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBS3DSurface/NURBS3DSurface.C