OpenFOAM: kOmegaSSTLM< BasicTurbulenceModel > Class Template Reference
kOmegaSSTLM< BasicTurbulenceModel > Class Template Reference
LES turbulence
Langtry-Menter 4-equation transitional SST model based on the k-omega-SST RAS model.
Public Types
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSST< BasicTurbulenceModel >
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Types inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
typedef eddyViscosity
< RASModel
< BasicTurbulenceModel >
>::alphaField alphaField
typedef eddyViscosity
< RASModel
< BasicTurbulenceModel >
>::rhoField rhoField
typedef eddyViscosity
< RASModel
< BasicTurbulenceModel >
>::transportModel transportModel
Public Types inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
typedef RASModel
< BasicTurbulenceModel >
::alphaField alphaField
typedef RASModel
< BasicTurbulenceModel >
::rhoField rhoField
typedef RASModel
< BasicTurbulenceModel >
::transportModel transportModel
Public Types inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
typedef RASModel
< BasicTurbulenceModel >
::alphaField alphaField
typedef RASModel
< BasicTurbulenceModel >
::rhoField rhoField
typedef RASModel
< BasicTurbulenceModel >
::transportModel transportModel
Public Types inherited from RASModel< BasicTurbulenceModel >
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("kOmegaSSTLM")
Runtime type information.
kOmegaSSTLM (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSSTLM ()=default
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
const volScalarField & ReThetat () const
Access function transition onset momentum-thickness Reynolds number.
const volScalarField & gammaInt () const
Access function to intermittency.
tmp< volScalarField > DReThetatEff () const
Return the effective diffusivity for transition onset.
tmp< volScalarField > DgammaIntEff () const
Return the effective diffusivity for intermittency.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Public Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
TypeName ("kOmegaSST")
Runtime type information.
kOmegaSST (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~kOmegaSST ()=default
Destructor.
Public Member Functions inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
kOmegaSSTBase (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~kOmegaSSTBase ()=default
Destructor.
tmp< volScalarField > DkEff (const volScalarField &F1) const
Return the effective diffusivity for k.
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
Return the effective diffusivity for omega.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate.
virtual tmp< volScalarField > omega () const
Return the turbulence kinetic energy dissipation rate.
Public Member Functions inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()=default
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< RASModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()=default
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from RASModel< BasicTurbulenceModel >
TypeName ("RAS")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, RASModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
RASModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~RASModel ()=default
Destructor.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
const dimensionedScalar & epsilonMin () const
Return the lower allowable limit for epsilon (default: SMALL)
const dimensionedScalar & omegaMin () const
Return the lower allowable limit for omega (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
dimensionedScalar & epsilonMin ()
Allow epsilonMin to be changed.
dimensionedScalar & omegaMin ()
Allow omegaMin to be changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
virtual tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
Modified form of the k-omega SST F1 function.
virtual tmp
< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
Modified form of the k-omega SST k production rate.
virtual tmp
< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
Modified form of the k-omega SST epsilon/k.
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal &Us, const volScalarField::Internal &Omega, const volScalarField::Internal &nu) const
Freestream blending-function.
tmp< volScalarField::Internal > ReThetac () const
Empirical correlation for critical Reynolds number where the.
tmp< volScalarField::Internal > Flength (const volScalarField::Internal &nu) const
Empirical correlation that controls the length of the.
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal &Rev, const volScalarField::Internal &ReThetac, const volScalarField::Internal &RT) const
Transition onset location control function.
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal &Us, const volScalarField::Internal &dUsds, const volScalarField::Internal &nu) const
Return the transition onset momentum-thickness Reynolds number.
void correctReThetatGammaInt ()
Solve the turbulence equations and correct the turbulence viscosity.
Protected Member Functions inherited from kOmegaSST< BasicTurbulenceModel >
virtual void correctNut (const volScalarField &S2)
virtual void correctNut ()
Protected Member Functions inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
void setDecayControl (const dictionary &dict)
virtual tmp< volScalarField > F2 () const
virtual tmp< volScalarField > F3 () const
virtual tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
virtual tmp
< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
Return G/nu.
virtual tmp< fvScalarMatrix > kSource () const
virtual tmp< fvScalarMatrix > omegaSource () const
virtual tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Member Functions inherited from RASModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
RASModel (const RASModel &)=delete
No copy construct.
void operator= (const RASModel &)=delete
No copy assignment.
Protected Attributes
dimensionedScalar ca1_
dimensionedScalar ca2_
dimensionedScalar ce1_
dimensionedScalar ce2_
dimensionedScalar cThetat_
dimensionedScalar sigmaThetat_
scalar lambdaErr_
Convergence criterion for the lambda/thetat loop.
label maxLambdaIter_
Maximum number of iterations to converge the lambda/thetat loop.
const dimensionedScalar deltaU_
Stabilization for division by the magnitude of the velocity.
volScalarField ReThetat_
Transition onset momentum-thickness Reynolds number.
volScalarField gammaInt_
Intermittency.
volScalarField::Internal gammaIntEff_
Effective intermittency.
Protected Attributes inherited from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
Flag to include the F3 term.
const volScalarField & y_
Wall distance.
volScalarField k_
volScalarField omega_
Switch decayControl_
Flag to include the decay control.
dimensionedScalar kInf_
dimensionedScalar omegaInf_
Protected Attributes inherited from eddyViscosity< RASModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from RASModel< BasicTurbulenceModel >
dictionary RASDict_
RAS coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
Additional Inherited Members
Static Public Member Functions inherited from RASModel< BasicTurbulenceModel >
static autoPtr< RASModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected RAS model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::kOmegaSSTLM< BasicTurbulenceModel >
Langtry-Menter 4-equation transitional SST model based on the k-omega-SST RAS model.
References:
    Langtry, R. B., & Menter, F. R. (2009).
    Correlation-based transition modeling for unstructured parallelized
    computational fluid dynamics codes.
    AIAA journal, 47(12), 2894-2906.
    Menter, F. R., Langtry, R., & Volker, S. (2006).
    Transition modelling for general purpose CFD codes.
    Flow, turbulence and combustion, 77(1-4), 277-303.
    Langtry, R. B. (2006).
    A correlation-based transition model using local variables for
    unstructured parallelized CFD codes.
    Phd. Thesis, Universitt Stuttgart.
The model coefficients are
    kOmegaSSTCoeffs
    {
        // Default SST coefficients
        alphaK1     0.85;
        alphaK2     1;
        alphaOmega1 0.5;
        alphaOmega2 0.856;
        beta1       0.075;
        beta2       0.0828;
        betaStar    0.09;
        gamma1      5/9;
        gamma2      0.44;
        a1          0.31;
        b1          1;
        c1          10;
        F3          no;
        // Default LM coefficients
        ca1         2;
        ca2         0.06;
        ce1         1;
        ce2         50;
        cThetat     0.03;
        sigmaThetat 2;
        lambdaErr   1e-6;
        maxLambdaIter 10;
    }
Source files
kOmegaSSTLM.H
kOmegaSSTLM.C
Definition at line 103 of file kOmegaSSTLM.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 250 of file kOmegaSSTLM.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 251 of file kOmegaSSTLM.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 252 of file kOmegaSSTLM.H.
Constructor & Destructor Documentation
kOmegaSSTLM (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 358 of file kOmegaSSTLM.C.
virtual ~kOmegaSSTLM () virtual default
Destructor.
Member Function Documentation
tmp< volScalarField > F1 (const volScalarField & CDkOmega) const protected virtual
Modified form of the k-omega SST F1 function.
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 35 of file kOmegaSSTLM.C.
References Foam::exp(), F3, nu, Foam::pow(), Foam::Ry(), and Foam::sqrt().
tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected virtual
Modified form of the k-omega SST k production rate.
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 48 of file kOmegaSSTLM.C.
tmp< volScalarField::Internal > epsilonByk (const volScalarField & F1, const volTensorField & gradU) const protected virtual
Modified form of the k-omega SST epsilon/k.
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 58 of file kOmegaSSTLM.C.
References kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >::Pk().
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal & Us, const volScalarField::Internal & Omega, const volScalarField::Internal & nu) const protected
Freestream blending-function.
Definition at line 71 of file kOmegaSSTLM.C.
tmp< volScalarField::Internal > ReThetac () const protected
Empirical correlation for critical Reynolds number where the.
intermittency first starts to increase in the boundary layer
Definition at line 110 of file kOmegaSSTLM.C.
tmp< volScalarField::Internal > Flength (const volScalarField::Internal & nu) const protected
Empirical correlation that controls the length of the.
transition region
Definition at line 151 of file kOmegaSSTLM.C.
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal & Rev, const volScalarField::Internal & ReThetac, const volScalarField::Internal & RT) const protected
Transition onset location control function.
Definition at line 328 of file kOmegaSSTLM.C.
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal & Us, const volScalarField::Internal & dUsds, const volScalarField::Internal & nu) const protected
Return the transition onset momentum-thickness Reynolds number.
(based on freestream conditions)
Definition at line 214 of file kOmegaSSTLM.C.
void correctReThetatGammaInt () protected
Solve the turbulence equations and correct the turbulence viscosity.
Definition at line 514 of file kOmegaSSTLM.C.
TypeName ("kOmegaSSTLM< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 493 of file kOmegaSSTLM.C.
const volScalarField& ReThetat () const inline
Access function transition onset momentum-thickness Reynolds number.
Definition at line 295 of file kOmegaSSTLM.H.
const volScalarField& gammaInt () const inline
Access function to intermittency.
Definition at line 303 of file kOmegaSSTLM.H.
tmp<volScalarField> DReThetatEff () const inline
Return the effective diffusivity for transition onset.
momentum-thickness Reynolds number
Definition at line 313 of file kOmegaSSTLM.H.
tmp<volScalarField> DgammaIntEff () const inline
Return the effective diffusivity for intermittency.
Definition at line 328 of file kOmegaSSTLM.H.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented from kOmegaSSTBase< eddyViscosity< RASModel< BasicTurbulenceModel > > >.
Definition at line 612 of file kOmegaSSTLM.C.
Member Data Documentation
dimensionedScalar ca1_ protected
Definition at line 126 of file kOmegaSSTLM.H.
dimensionedScalar ca2_ protected
Definition at line 127 of file kOmegaSSTLM.H.
dimensionedScalar ce1_ protected
Definition at line 129 of file kOmegaSSTLM.H.
dimensionedScalar ce2_ protected
Definition at line 130 of file kOmegaSSTLM.H.
dimensionedScalar cThetat_ protected
Definition at line 132 of file kOmegaSSTLM.H.
dimensionedScalar sigmaThetat_ protected
Definition at line 133 of file kOmegaSSTLM.H.
scalar lambdaErr_ protected
Convergence criterion for the lambda/thetat loop.
Definition at line 138 of file kOmegaSSTLM.H.
label maxLambdaIter_ protected
Maximum number of iterations to converge the lambda/thetat loop.
Definition at line 143 of file kOmegaSSTLM.H.
const dimensionedScalar deltaU_ protected
Stabilization for division by the magnitude of the velocity.
Definition at line 148 of file kOmegaSSTLM.H.
volScalarField ReThetat_ protected
Transition onset momentum-thickness Reynolds number.
Definition at line 156 of file kOmegaSSTLM.H.
volScalarField gammaInt_ protected
Intermittency.
Definition at line 161 of file kOmegaSSTLM.H.
volScalarField::Internal gammaIntEff_ protected
Effective intermittency.
Definition at line 166 of file kOmegaSSTLM.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTLM/kOmegaSSTLM.H
src/TurbulenceModels/turbulenceModels/RAS/kOmegaSSTLM/kOmegaSSTLM.C