OpenFOAM: optionList Class Reference
optionList Class Reference
List of finite volume options.
Public Member Functions
TypeName ("optionList")
Runtime type information.
optionList (const fvMesh &mesh)
Construct null.
optionList (const fvMesh &mesh, const dictionary &dict)
Construct from mesh and dictionary.
virtual ~optionList ()=default
Destructor.
void reset (const dictionary &dict)
Reset the source list.
bool appliesToField (const word &fieldName) const
Return whether there is something to apply to the field.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with specified name.
template<class Type >
tmp< fvMatrix< Type > > operator() (const volScalarField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > operator() (const geometricOneField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation.
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > &field)
Return source for equation with second time derivative.
template<class Type >
tmp< fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Return source for equation with second time derivative.
template<class Type >
void constrain (fvMatrix< Type > &eqn)
Apply constraints to equation.
template<class Type >
void correct (GeometricField< Type, fvPatchField, volMesh > &field)
Apply correction to field.
virtual bool read (const dictionary &dict)
Read dictionary.
virtual bool writeData (Ostream &os) const
Write data to Ostream.
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > source (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName, const dimensionSet &ds)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const geometricOneField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const volScalarField &alpha, const geometricOneField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > operator() (const geometricOneField &alpha, const volScalarField &rho, GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > &field)
template<class Type >
Foam::tmp< Foam::fvMatrix< Type > > d2dt2 (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName)
Public Member Functions inherited from PtrList< option >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< option > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< option > &&list)
Move construct.
PtrList (UList< option * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
PtrList (const PtrList< option > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< option > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< option > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
PtrList< option > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (option *ptr)
Append an element to the end of the list.
void append (autoPtr< option > &aptr)
Move append an element to the end of the list.
void append (autoPtr< option > &&aptr)
Move append an element to the end of the list.
void append (const tmp< option > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< option > &list)
Transfer into this list and annul the argument list.
const option * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< option > set (const label i, option *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< option > set (const label i, autoPtr< option > &aptr)
Set element to given autoPtr and return old element.
autoPtr< option > set (const label i, autoPtr< option > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< option > set (const label i, const tmp< option > &tptr)
Set element to given tmp and return old element.
autoPtr< option > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< option > &list)
Copy assignment.
void operator= (PtrList< option > &&list)
Move assignment.
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
const dictionary & optionsDict (const dictionary &dict) const
Return the "options" sub-dictionary if present otherwise return dict.
bool readOptions (const dictionary &dict)
Read options dictionary.
void checkApplied () const
Check that all sources have been applied.
template<class Type >
tmp< fvMatrix< Type > > source (GeometricField< Type, fvPatchField, volMesh > &field, const word &fieldName, const dimensionSet &ds)
Return source for equation with specified name and dimensions.
optionList (const optionList &)=delete
No copy construct.
void operator= (const optionList &)=delete
No copy assignment.
Protected Member Functions inherited from PtrList< option >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh database.
label checkTimeIndex_
Time index to check that all defined sources have been applied.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Friends
Ostream & operator<< (Ostream &os, const optionList &options)
Ostream operator.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Detailed Description
List of finite volume options.
SourceFile optionList.C
Definition at line 61 of file fvOptionList.H.
Constructor & Destructor Documentation
optionList (const optionList &) protected delete
No copy construct.
optionList (const fvMesh & mesh)
Construct null.
Definition at line 93 of file fvOptionList.C.
References reset().
optionList (const fvMesh & mesh, const dictionary & dict)
Construct from mesh and dictionary.
Definition at line 83 of file fvOptionList.C.
virtual ~optionList () virtual default
Destructor.
Member Function Documentation
const Foam::dictionary & optionsDict (const dictionary & dict) const protected
Return the "options" sub-dictionary if present otherwise return dict.
Definition at line 38 of file fvOptionList.C.
bool readOptions (const dictionary & dict) protected
Read options dictionary.
Definition at line 53 of file fvOptionList.C.
References dict.
void checkApplied () const protected
Check that all sources have been applied.
Definition at line 68 of file fvOptionList.C.
Referenced by optionList::source().
tmp<fvMatrix<Type> > source (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName, const dimensionSet & ds) protected
Return source for equation with specified name and dimensions.
Referenced by optionList::source().
void operator= (const optionList &) protected delete
No copy assignment.
TypeName ("optionList")
Runtime type information.
void reset (const dictionary & dict)
Reset the source list.
Definition at line 103 of file fvOptionList.C.
bool appliesToField (const word & fieldName) const
Return whether there is something to apply to the field.
Definition at line 135 of file fvOptionList.C.
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
tmp<fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Return source for equation with specified name.
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
tmp<fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Return source for equation with specified name.
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Return source for equation with specified name.
tmp<fvMatrix<Type> > operator() (const volScalarField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
tmp<fvMatrix<Type> > operator() (const geometricOneField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
tmp<fvMatrix<Type> > operator() (const geometricOneField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation.
tmp<fvMatrix<Type> > d2dt2 (GeometricField< Type, fvPatchField, volMesh > & field)
Return source for equation with second time derivative.
tmp<fvMatrix<Type> > d2dt2 (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Return source for equation with second time derivative.
void constrain (fvMatrix< Type > & eqn)
Apply constraints to equation.
Definition at line 281 of file fvOptionListTemplates.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, Foam::dimVolume, and Foam::sqr().
void correct (GeometricField< Type, fvPatchField, volMesh > & field)
Apply correction to field.
Definition at line 314 of file fvOptionListTemplates.C.
Referenced by kOmega< BasicTurbulenceModel >::correctNut(), DeardorffDiffStress< BasicTurbulenceModel >::correctNut(), SSG< BasicTurbulenceModel >::correctNut(), and LRR< BasicTurbulenceModel >::correctNut().
bool read (const dictionary & dict) virtual
Read dictionary.
Definition at line 153 of file fvOptionList.C.
bool writeData (Ostream & os) const virtual
Write data to Ostream.
Definition at line 159 of file fvOptionList.C.
Foam::tmp<Foam::fvMatrix<Type> > source (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName, const dimensionSet & ds)
Definition at line 28 of file fvOptionListTemplates.C.
References addProfiling, option::addSup(), option::applyToField(), optionList::checkApplied(), Foam::expressions::patchExpr::debug, Foam::endl(), forAll, i, Foam::Info, option::isActive(), option::name(), UPtrList< T >::operator[](), tmp< T >::ref(), option::setApplied(), and optionList::source().
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 70 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Definition at line 80 of file fvOptionListTemplates.C.
References field().
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 91 of file fvOptionListTemplates.C.
References Foam::dimTime, and Foam::dimVolume.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Definition at line 102 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 149 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Definition at line 161 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const geometricOneField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 210 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const volScalarField & alpha, const geometricOneField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 222 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > operator() (const geometricOneField & alpha, const volScalarField & rho, GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 249 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > d2dt2 (GeometricField< Type, fvPatchField, volMesh > & field)
Definition at line 261 of file fvOptionListTemplates.C.
Foam::tmp<Foam::fvMatrix<Type> > d2dt2 (GeometricField< Type, fvPatchField, volMesh > & field, const word & fieldName)
Definition at line 271 of file fvOptionListTemplates.C.
References Foam::fac::d2dt2(), and IOobject::name().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const optionList & options) friend
Ostream operator.
Member Data Documentation
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 72 of file fvOptionList.H.
label checkTimeIndex_ protected
Time index to check that all defined sources have been applied.
Definition at line 77 of file fvOptionList.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/fvOptions/fvOptionList.H
src/finiteVolume/cfdTools/general/fvOptions/fvOptionList.C
src/finiteVolume/cfdTools/general/fvOptions/fvOptionListTemplates.C