OpenFOAM: SpatialVector< Cmpt > Class Template Reference
SpatialVector< Cmpt > Class Template Reference
Templated 3D spatial vector derived from VectorSpace used to represent the anglular and linear components of position, velocity and acceleration of rigid bodies.
Classes
class dual
Class to represent the dual spatial vector.
Public Types
enum components {
WX, WY, WZ, LX,
LY, LZ
}
Component labeling enumeration.
Public Types inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
typedef VectorSpace
< SpatialVector< Cmpt >, Cmpt,
Ncmpts > vsType
VectorSpace type.
typedef Cmpt cmptType
Component type.
typedef Cmpt magType
Magnitude type.
typedef Cmpt * iterator
Random access iterator for traversing VectorSpace.
typedef const Cmpt * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
SpatialVector ()
Construct null.
SpatialVector (const Foam::zero)
Construct initialized to zero.
SpatialVector (const typename SpatialVector::vsType &)
Construct given VectorSpace of the same rank.
SpatialVector (const Vector< Cmpt > &w, const Vector< Cmpt > &l)
Construct from the angular and linear vector components.
SpatialVector (const Cmpt &wx, const Cmpt &wy, const Cmpt &wz, const Cmpt &lx, const Cmpt &ly, const Cmpt &lz)
Construct given 6 components.
SpatialVector (Istream &)
Construct from Istream.
const Cmpt & wx () const
const Cmpt & wy () const
const Cmpt & wz () const
const Cmpt & lx () const
const Cmpt & ly () const
const Cmpt & lz () const
Cmpt & wx ()
Cmpt & wy ()
Cmpt & wz ()
Cmpt & lx ()
Cmpt & ly ()
Cmpt & lz ()
Vector< Cmpt > w () const
Return the angular part of the spatial vector as a vector.
Vector< Cmpt > l () const
Return the linear part of the spatial vector as a vector.
dual operator* () const
Return the dual spatial vector.
Public Member Functions inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const Cmpt & component (const direction) const
Cmpt & component (const direction)
void component (Cmpt &, const direction) const
void replace (const direction, const Cmpt &)
const Cmpt * cdata () const noexcept
Return const pointer to the first data element.
Cmpt * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const Cmpt & operator[] (const direction) const
Cmpt & operator[] (const direction)
void operator= (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &)
void operator-= (const VectorSpace< SpatialVector< Cmpt >, Cmpt, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static SpatialVector< Cmpt > uniform (const Cmpt &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
Cmpt v_ [Ncmpts]
The components of this vector space.
Static Public Attributes inherited from VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const SpatialVector< Cmpt > zero
static const SpatialVector< Cmpt > one
static const SpatialVector< Cmpt > max
static const SpatialVector< Cmpt > min
static const SpatialVector< Cmpt > rootMax
static const SpatialVector< Cmpt > rootMin
Detailed Description
template<class Cmpt>
class Foam::SpatialVector< Cmpt >
Templated 3D spatial vector derived from VectorSpace used to represent the anglular and linear components of position, velocity and acceleration of rigid bodies.
Reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
Source files
SpatialVector.H
SpatialVectorI.H
See Also
Foam::VectorSpace Foam::Vector
Definition at line 61 of file SpatialVector.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
WX
WY
WZ
LX
LY
LZ
Definition at line 71 of file SpatialVector.H.
Constructor & Destructor Documentation
SpatialVector () inline
Construct null.
Definition at line 24 of file SpatialVectorI.H.
SpatialVector (const Foam::zero) inline
Construct initialized to zero.
Definition at line 29 of file SpatialVectorI.H.
SpatialVector (const typename SpatialVector< Cmpt >::vsType & vs) inline
Construct given VectorSpace of the same rank.
Definition at line 37 of file SpatialVectorI.H.
SpatialVector (const Vector< Cmpt > & w, const Vector< Cmpt > & l) inline
Construct from the angular and linear vector components.
Definition at line 47 of file SpatialVectorI.H.
SpatialVector (const Cmpt & wx, const Cmpt & wy, const Cmpt & wz, const Cmpt & lx, const Cmpt & ly, const Cmpt & lz) inline
Construct given 6 components.
Definition at line 63 of file SpatialVectorI.H.
SpatialVector (Istream & is) inline
Construct from Istream.
Definition at line 82 of file SpatialVectorI.H.
Member Function Documentation
const Cmpt & wx () const inline
Definition at line 98 of file SpatialVectorI.H.
Referenced by Foam::operator^().
const Cmpt & wy () const inline
Definition at line 105 of file SpatialVectorI.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WX.
Referenced by Foam::operator^().
const Cmpt & wz () const inline
Definition at line 112 of file SpatialVectorI.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WY.
Referenced by Foam::operator^().
const Cmpt & lx () const inline
Definition at line 119 of file SpatialVectorI.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WZ.
Referenced by Foam::operator^().
const Cmpt & ly () const inline
Definition at line 126 of file SpatialVectorI.H.
References SpatialVector< Cmpt >::LX, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Referenced by Foam::operator^().
const Cmpt & lz () const inline
Definition at line 133 of file SpatialVectorI.H.
References SpatialVector< Cmpt >::LY, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Referenced by Foam::operator^().
Cmpt & wx () inline
Definition at line 140 of file SpatialVectorI.H.
References SpatialVector< Cmpt >::LZ, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Cmpt & wy () inline
Definition at line 147 of file SpatialVectorI.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WX.
Cmpt & wz () inline
Definition at line 154 of file SpatialVectorI.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WY.
Cmpt & lx () inline
Definition at line 161 of file SpatialVectorI.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_, and SpatialVector< Cmpt >::WZ.
Cmpt & ly () inline
Definition at line 168 of file SpatialVectorI.H.
References SpatialVector< Cmpt >::LX, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Cmpt & lz () inline
Definition at line 175 of file SpatialVectorI.H.
References SpatialVector< Cmpt >::LY, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Foam::Vector< Cmpt > w () const inline
Return the angular part of the spatial vector as a vector.
Definition at line 182 of file SpatialVectorI.H.
References SpatialVector< Cmpt >::LZ, and VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Foam::Vector< Cmpt > l () const inline
Return the linear part of the spatial vector as a vector.
Definition at line 188 of file SpatialVectorI.H.
References VectorSpace< SpatialVector< Cmpt >, Cmpt, 6 >::v_.
Foam::SpatialVector< Cmpt >::dual operator* () const inline
Return the dual spatial vector.
Definition at line 205 of file SpatialVectorI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialVector/SpatialVector.H
src/OpenFOAM/primitives/spatialVectorAlgebra/SpatialVector/SpatialVectorI.H