OpenFOAM: PairModel< CloudType > Class Template Reference
PairModel< CloudType > Class Template Reference abstract
Templated pair interaction class.
Public Member Functions
TypeName ("pairModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PairModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PairModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~PairModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
virtual bool controlsTimestep () const =0
Whether the PairModel has a timestep limit that will.
virtual label nSubCycles () const =0
For PairModels that control the timestep, calculate the.
virtual void evaluatePair (typename CloudType::parcelType &pA, typename CloudType::parcelType &pB) const =0
Calculate the pair interaction between parcels.
Static Public Member Functions
static autoPtr< PairModel
< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions
scalar forceCoeff (typename CloudType::parcelType &pA, typename CloudType::parcelType &pB) const
Return the force coefficient based on the forceRampTime_.
Detailed Description
template<class CloudType>
class Foam::PairModel< CloudType >
Templated pair interaction class.
Source files
PairModel.H
PairModel.C
PairModelNew.C
Definition at line 49 of file PairCollision.H.
Constructor & Destructor Documentation
PairModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 28 of file PairModel.C.
~PairModel () virtual
Destructor.
Definition at line 47 of file PairModel.C.
Member Function Documentation
Foam::scalar forceCoeff (typename CloudType::parcelType & pA, typename CloudType::parcelType & pB) const protected
Return the force coefficient based on the forceRampTime_.
Definition at line 77 of file PairModel.C.
TypeName ("pairModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , PairModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::PairModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 29 of file PairModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
const CloudType & owner () const
Return the owner cloud object.
Definition at line 55 of file PairModel.C.
const Foam::dictionary & dict () const
Return the dictionary.
Definition at line 62 of file PairModel.C.
const Foam::dictionary & coeffDict () const
Return the coefficients dictionary.
Definition at line 69 of file PairModel.C.
virtual bool controlsTimestep () const pure virtual
Whether the PairModel has a timestep limit that will.
require subCycling
Implemented in PairSpringSliderDashpot< CloudType >.
virtual label nSubCycles () const pure virtual
For PairModels that control the timestep, calculate the.
number of subCycles needed to satisfy the minimum allowable timestep
Implemented in PairSpringSliderDashpot< CloudType >.
virtual void evaluatePair (typename CloudType::parcelType & pA, typename CloudType::parcelType & pB) const pure virtual
Calculate the pair interaction between parcels.
Implemented in PairSpringSliderDashpot< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairCollision.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairModel/PairModel/PairModel.H
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairModel/PairModel/PairModel.C
src/lagrangian/intermediate/submodels/Kinematic/CollisionModel/PairCollision/PairModel/PairModel/PairModelNew.C