OpenFOAM: fvMeshTools Class Reference
fvMeshTools Class Reference
A collection of tools for operating on an fvMesh.
Static Public Member Functions
static label addPatch (fvMesh &mesh, const polyPatch &patch, const dictionary &patchFieldDict, const word &defaultPatchFieldType, const bool validBoundary)
Add patch. Inserts patch before all processor patches.
static void setPatchFields (fvMesh &mesh, const label patchi, const dictionary &patchFieldDict)
Change patchField on registered fields according to dictionary.
static void zeroPatchFields (fvMesh &mesh, const label patchi)
Change patchField to zero on registered fields.
static void reorderPatches (fvMesh &, const labelList &oldToNew, const label nPatches, const bool validBoundary)
Reorder and remove trailing patches. If validBoundary call is parallel.
static labelList removeEmptyPatches (fvMesh &, const bool validBoundary)
Remove zero sized patches. All but processor patches are.
static autoPtr< fvMesh > newMesh (const IOobject &io, const bool masterOnlyReading)
Read mesh or create dummy mesh (0 cells, >0 patches). Works in two.
static void createDummyFvMeshFiles (const objectRegistry &parent, const word &regionName, const bool verbose=false)
Create additional fv* files.
Detailed Description
A collection of tools for operating on an fvMesh.
Source files
fvMeshTools.H
fvMeshTools.C
Definition at line 47 of file fvMeshTools.H.
Member Function Documentation
Foam::label addPatch (fvMesh & mesh, const polyPatch & patch, const dictionary & patchFieldDict, const word & defaultPatchFieldType, const bool validBoundary) static
Add patch. Inserts patch before all processor patches.
Supply per field the new patchField per field as a subdictionary or a default type. If validBoundary call is parallel synced and all add the same patch with same settings.
Definition at line 30 of file fvMeshTools.C.
References fvMesh::boundary(), polyMesh::boundaryMesh(), fvMesh::clearOut(), polyPatch::clone(), polyBoundaryMesh::findPatchID(), forAll, i, mesh, patchIdentifier::name(), fvPatch::New(), primitiveMesh::nFaces(), UPtrList< T >::reorder(), polyBoundaryMesh::reorder(), PtrList< T >::set(), PtrList< T >::setSize(), UPtrList< T >::size(), polyPatch::start(), and Foam::Zero.
static void setPatchFields (fvMesh & mesh, const label patchi, const dictionary & patchFieldDict) static
Change patchField on registered fields according to dictionary.
void zeroPatchFields (fvMesh & mesh, const label patchi) static
Change patchField to zero on registered fields.
Definition at line 236 of file fvMeshTools.C.
void reorderPatches (fvMesh & mesh, const labelList & oldToNew, const label nPatches, const bool validBoundary) static
Reorder and remove trailing patches. If validBoundary call is parallel.
synced
Definition at line 322 of file fvMeshTools.C.
Foam::labelList removeEmptyPatches (fvMesh & mesh, const bool validBoundary) static
Remove zero sized patches. All but processor patches are.
assumed to be present on all processors (so size will be reduced if validBoundary). Return map from new to old patches
Definition at line 354 of file fvMeshTools.C.
Foam::autoPtr< Foam::fvMesh > newMesh (const IOobject & io, const bool masterOnlyReading) static
Read mesh or create dummy mesh (0 cells, >0 patches). Works in two.
modes according to masterOnlyReading: true : all slaves create dummy mesh false: checks locally for mesh directories and only creates dummy mesh if not present
Definition at line 417 of file fvMeshTools.C.
void createDummyFvMeshFiles (const objectRegistry & parent, const word & regionName, const bool verbose = false) static
Create additional fv* files.
Definition at line 667 of file fvMeshTools.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshTools/fvMeshTools.H
src/dynamicMesh/fvMeshTools/fvMeshTools.C
src/dynamicMesh/fvMeshTools/fvMeshToolsTemplates.C