OpenFOAM: regIOobject Class Reference
regIOobject Class Reference abstract
regIOobject is an abstract class derived from IOobject to handle automatic object registration with the objectRegistry.
Inherits IOobject.
Inherited by AveragingMethod< Foam::Vector >, AveragingMethod< scalar >, BlendedInterfacialModel< Foam::dragModel >, BlendedInterfacialModel< Foam::heatTransferModel >, BlendedInterfacialModel< Foam::liftModel >, BlendedInterfacialModel< Foam::turbulentDispersionModel >, BlendedInterfacialModel< Foam::virtualMassModel >, BlendedInterfacialModel< Foam::wallLubricationModel >, CompactIOList< face, label >, DimensionedField< scalar, Foam::areaMesh >, DimensionedField< scalar, Foam::volMesh >, DimensionedField< scalar, triSurfacePointGeoMesh >, DimensionedField< Type, Foam::areaMesh >, DimensionedField< Type, Foam::edgeMesh >, DimensionedField< Type, Foam::pointMesh >, DimensionedField< Type, Foam::surfaceMesh >, DimensionedField< Type, Foam::volMesh >, adjointSolverManager, ATCModel, AveragingMethod< Type >, baseIOdictionary, BlendedInterfacialModel< ModelType >, CompactIOField< T, BaseType >, CompactIOList< T, BaseType >, coordinateSystems, decomposedBlockData, populationBalanceModel, DimensionedField< Type, GeoMesh >, dragModel, dragModel, exprDriverWriter, exprResultGlobals, extendedFeatureEdgeMesh, faBoundaryMesh, featureEdgeMesh, fieldDictionary, GlobalIOField< Type >, GlobalIOList< Type >, adjointTurbulenceModel, IOField< Type >, IOList< T >, IOMap< T >, IOmapDistribute, IOmapDistributePolyMesh, IOPosition< ParticleType >, IOPtrList< T >, lumpedPointIOMovement, meshObject, objectiveManager, objectRegistry, PDRDragModel, polyBoundaryMesh, polyBoundaryMeshEntries, polyTopoChanger, porosityModel, porousModel, refinementHistory, searchableSurface, SLGThermo, solutionControl, SubDimensionedField< Type, GeoMesh >, surfaceTensionModel, surfaceTensionModel, surfaceTensionModel, surfZoneIOList, topoSet, UniformDimensionedField< Type >, virtualMassModel, virtualMassModel, ZoneMesh< Zone, MeshType >, GlobalIOField< vector >, GlobalIOList< kinematicParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< reactingParcelInjectionData >, IOList< label >, IOList< labelList >, IOPtrList< Foam::entry >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, ZoneMesh< cellZone, polyMesh >, ZoneMesh< faceZone, polyMesh >, and ZoneMesh< pointZone, polyMesh >.
Public Member Functions
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeData (Ostream &) const =0
Pure virtual writeData function.
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Static Public Member Functions
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Attributes
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Protected Member Functions
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Static Protected Attributes
static bool masterOnlyReading = false
To flag master-only reading of objects.
Friends
class functionEntries::codeStream
Declare friendship with any classes that need access to.
class fileOperations::uncollatedFileOperation
class fileOperations::masterUncollatedFileOperation
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Detailed Description
regIOobject is an abstract class derived from IOobject to handle automatic object registration with the objectRegistry.
Source files
regIOobject.H
regIOobject.C
regIOobjectRead.C
regIOobjectWrite.C
Definition at line 63 of file regIOobject.H.
Constructor & Destructor Documentation
regIOobject (const IOobject & io, const bool isTime = false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
Definition at line 63 of file regIOobject.C.
References IOobject::registerObject().
regIOobject (const regIOobject & rio)
Copy construct.
Definition at line 79 of file regIOobject.C.
References regIOobject::checkIn().
regIOobject (const regIOobject & rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
Definition at line 92 of file regIOobject.C.
regIOobject (const word & newName, const regIOobject & rio, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
Definition at line 113 of file regIOobject.C.
regIOobject (const IOobject & io, const regIOobject & rio)
Copy construct with new IO parameters.
Definition at line 134 of file regIOobject.C.
References regIOobject::checkIn().
~regIOobject () virtual
Destructor.
Definition at line 155 of file regIOobject.C.
Member Function Documentation
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word & typeName) protected
Helper: check readOpt flags and read if necessary.
Definition at line 32 of file regIOobjectRead.C.
References Foam::fileHandler(), IOobject::fileModificationChecking, regIOobject::global(), regIOobject::headerOk(), IOobject::inotifyMaster, UPstream::master(), IOobject::MUST_READ, IOobject::MUST_READ_IF_MODIFIED, fileOperation::read(), IOobject::READ_IF_PRESENT, IOobject::readOpt(), Pstream::scatter(), and IOobject::timeStampMaster.
Referenced by IOdictionary::IOdictionary(), localIOdictionary::localIOdictionary(), and unwatchedIOdictionary::unwatchedIOdictionary().
Istream* objectStream () protected
Construct and return an IFstream for the object.
The results is NULL if the stream construction failed
TypeName ("regIOobject")
Runtime type information.
bool checkIn ()
Add object to registry, if not already registered.
Returns
true if object was newly registered
Definition at line 194 of file regIOobject.C.
Referenced by regIOobject::regIOobject().
bool checkOut ()
Remove all file watches and remove object from registry.
Returns
true if object was registered and was removed
Definition at line 230 of file regIOobject.C.
void addWatch () virtual
Add file watch on object (if registered and READ_IF_MODIFIED)
Reimplemented in unwatchedIOdictionary.
Definition at line 273 of file regIOobject.C.
Referenced by IOMap< T >::IOMap(), and IOPtrList< T >::IOPtrList().
bool ownedByRegistry () const inline
Is this object owned by the registry?
Definition at line 24 of file regIOobjectI.H.
void store () inline
Transfer ownership of this object to its registry.
Definition at line 30 of file regIOobjectI.H.
Referenced by fieldAverage::addMeanFieldType(), Foam::calc_rhoU(), cloud::createIOField(), MeshObject< Mesh, MeshObjectType, Type >::New(), coordinateSystems::New(), polySurface::polySurface(), turbulenceFields::processField(), and discreteSurface::sampleType().
Type & store (Type * p) inline static
Transfer ownership of the given object pointer to its registry.
Returns
reference to the object.
Definition at line 37 of file regIOobjectI.H.
Type & store (autoPtr< Type > & aptr) inline static
Transfer ownership of the given object pointer to its registry.
Returns
reference to the object.
Definition at line 53 of file regIOobjectI.H.
Type & store (autoPtr< Type > && aptr) inline static
Transfer ownership of the given object pointer to its registry.
Returns
reference to the object.
Definition at line 60 of file regIOobjectI.H.
References autoPtr< T >::ptr().
void release (const bool unregister = false) inline
Release ownership of this object from its registry.
Parameters
unregister optionally set as non-registered
Definition at line 66 of file regIOobjectI.H.
Foam::label eventNo () const inline
Event number at last update.
Definition at line 76 of file regIOobjectI.H.
Referenced by polyMesh::faces().
Foam::label & eventNo () inline
Event number at last update.
Definition at line 81 of file regIOobjectI.H.
bool upToDate (const regIOobject & a) const
Return true if up-to-date with respect to given object.
Definition at line 343 of file regIOobject.C.
Referenced by polyMesh::setUpToDatePoints().
bool upToDate (const regIOobject & a, const regIOobject & b) const
Return true if up-to-date with respect to given objects.
Definition at line 383 of file regIOobject.C.
bool upToDate (const regIOobject & a, const regIOobject & b, const regIOobject & c) const
Return true if up-to-date with respect to given objects.
Definition at line 393 of file regIOobject.C.
References Foam::constant::physicoChemical::b.
bool upToDate (const regIOobject & a, const regIOobject & b, const regIOobject & c, const regIOobject & d) const
Return true if up-to-date with respect to given objects.
Definition at line 404 of file regIOobject.C.
References c().
void setUpToDate ()
Set as up-to-date.
Definition at line 415 of file regIOobject.C.
void rename (const word & newName) virtual
Rename.
Reimplemented from IOobject.
Reimplemented in objectRegistry.
Definition at line 421 of file regIOobject.C.
Referenced by if().
Foam::fileName filePath () const virtual
Return complete path + object name if the file exists.
in the case directory otherwise null. Does not search up if parallel. Can be overridden to provide this functionality (e.g. IOdictionary)
Reimplemented in distributedTriSurfaceMesh, triSurfaceMesh, porosityModel, searchableSurface, extendedFeatureEdgeMesh, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, IOMap< T >, GlobalIOField< Type >, GlobalIOField< vector >, featureEdgeMesh, GlobalIOList< Type >, GlobalIOList< reactingParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< kinematicParcelInjectionData >, localIOdictionary, baseIOdictionary, IOdictionary, and unwatchedIOdictionary.
Definition at line 436 of file regIOobject.C.
bool headerOk ()
Read and check header info.
Definition at line 442 of file regIOobject.C.
References Foam::type().
Referenced by IOField< Type >::IOField(), IOList< T >::IOList(), IOMap< T >::IOMap(), IOPtrList< T >::IOPtrList(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), and regIOobject::readHeaderOk().
Foam::Istream & readStream (const word & expectName, const bool valid = true)
Return Istream and check object type against that given.
Definition at line 133 of file regIOobjectRead.C.
Referenced by fieldDictionary::fieldDictionary(), IOField< Type >::IOField(), IOList< T >::IOList(), IOMap< T >::IOMap(), IOmapDistribute::IOmapDistribute(), IOmapDistributePolyMesh::IOmapDistributePolyMesh(), IOPtrList< T >::IOPtrList(), polyBoundaryMeshEntries::polyBoundaryMeshEntries(), and exprDriverWriter::readData().
void close ()
Close Istream.
Definition at line 175 of file regIOobjectRead.C.
Referenced by fieldDictionary::fieldDictionary().
bool readData (Istream &) virtual
Virtual readData function.
Must be defined in derived types for which re-reading is required
Reimplemented in refinementHistory, exprResultGlobals, extendedFeatureEdgeMesh, lumpedPointIOMovement, GlobalIOField< Type >, GlobalIOField< vector >, GlobalIOList< Type >, GlobalIOList< reactingParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< kinematicParcelInjectionData >, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, baseIOdictionary, exprDriverWriter, IOmapDistributePolyMesh, IOmapDistribute, and featureEdgeMesh.
Definition at line 189 of file regIOobjectRead.C.
bool read () virtual
Read object.
Reimplemented in phaseSystem, phaseSystem, basicThermo, refinementHistory, phaseModel, Time, adjointRASModel, twoPhaseMixtureThermo, adjointSpalartAllmaras, twoPhaseMixtureEThermo, multiphaseSystem, laserDTRM, kinematicSingleLayer, fvDOM, multiphaseMixture, radiationModel, solarLoad, incompressibleThreePhaseMixture, phaseModel, diffusionMulticomponent< ReactionThermo, ThermoType >, thermoSingleLayer, twoPhaseSystem, crankConRod, viewFactor, incompressibleTwoPhaseInteractingMixture, kineticTheoryModel, kineticTheoryModel, adjointTurbulenceModel, rigidBodyMeshMotion, motionSolver, EDC< ReactionThermo >, solidThermo, faSchemes, reactingOneDim, rigidBodyMeshMotionSolver, combustionModel, multiphaseSystem, solution, FSD< ReactionThermo, ThermoType >, incompressibleTwoPhaseMixture, engineTime, sixDoFRigidBodyMotionSolver, RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > >, RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > >, temperaturePhaseChangeTwoPhaseMixture, phaseChangeTwoPhaseMixture, SRFModel, regionModel, fvSchemes, thermoIncompressibleTwoPhaseMixture, phasePressureModel, adjointLaminar, phasePressureModel, solutionControl, SchnerrSauer, SIMPLEControl, zoneCombustion< ReactionThermo >, phaseModel, CombustionModel< ReactionThermo >, decomposedBlockData, P1, laminar< ReactionThermo >, PaSR< ReactionThermo >, optimisationManager, turbulenceModel, eddyDissipationDiffusionModel< ReactionThermo, ThermoType >, eddyDissipationModelBase< ReactionThermo, ThermoType >, Kunz, thermalBaffle, singleStepCombustion< ReactionThermo, ThermoType >, Merkle, constant, diffusion< ReactionThermo, ThermoType >, regionModel1D, singlePhaseTransportModel, infinitelyFastChemistry< ReactionThermo, ThermoType >, pimpleControl, noCombustion< ReactionThermo >, options, IOMRFZoneList, thermalBaffleModel, opaqueSolid, noRadiation, EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > >, EddyDiffusivity< phaseCompressibleTurbulenceModel >, eddyViscosity< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, eddyViscosity< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, singleLayerRegion, rpm, IOoptionListAdjoint, tolerances, pyrolysisModel, IOporosityModelList, linearViscousStress< RASModel< EddyDiffusivity< ThermalDiffusivity< PhaseCompressibleTurbulenceModel< phaseModel > > > > >, linearViscousStress< RASModel< EddyDiffusivity< phaseCompressibleTurbulenceModel > > >, immiscibleIncompressibleTwoPhaseMixture, surfaceFilmRegionModel, thermo, noPyrolysis, noThermo, SIMPLEControlOpt, SIMPLEControlSingleRun, and simpleControl.
Definition at line 195 of file regIOobjectRead.C.
Referenced by turbulenceModel::validate().
Foam::label addWatch (const fileName & f) virtual
Add file watch for fileName on object if not yet watched. Return.
index of watch
Reimplemented in unwatchedIOdictionary.
Definition at line 249 of file regIOobject.C.
const Foam::labelList & watchIndices () const inline
Return file-monitoring handles.
Definition at line 87 of file regIOobjectI.H.
Foam::labelList & watchIndices () inline
Return file-monitoring handles.
Definition at line 93 of file regIOobjectI.H.
bool modified () const virtual
Return true if the object's file (or files for objectRegistry)
have been modified. (modified state is cached by Time)
Reimplemented in objectRegistry.
Definition at line 241 of file regIOobjectRead.C.
bool readIfModified () virtual
Read object if modified (as set by call to modified)
Reimplemented in objectRegistry.
Definition at line 255 of file regIOobjectRead.C.
virtual bool writeData (Ostream &) const pure virtual
Pure virtual writeData function.
Must be defined in derived types
Implemented in GeometricField< Type, PatchField, GeoMesh >, GeometricField< Type, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Type, Foam::faePatchField, Foam::edgeMesh >, GeometricField< Type, Foam::fvPatchField, Foam::volMesh >, GeometricField< symmTensor, fvPatchField, volMesh >, GeometricField< tensor, fvPatchField, volMesh >, GeometricField< vector, fvsPatchField, surfaceMesh >, GeometricField< scalar, fvPatchField, volMesh >, GeometricField< scalar, fvsPatchField, surfaceMesh >, GeometricField< scalar, pointPatchField, pointMesh >, GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh >, GeometricField< vector, fvPatchField, volMesh >, GeometricField< Type, Foam::faPatchField, Foam::areaMesh >, GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh >, GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh >, GeometricField< vector, pointPatchField, pointMesh >, objectRegistry, refinementHistory, populationBalanceModel, DimensionedField< Type, GeoMesh >, DimensionedField< scalar, Foam::volMesh >, DimensionedField< Type, Foam::edgeMesh >, DimensionedField< scalar, triSurfacePointGeoMesh >, DimensionedField< Type, Foam::surfaceMesh >, DimensionedField< Type, Foam::volMesh >, DimensionedField< scalar, Foam::areaMesh >, DimensionedField< Type, Foam::areaMesh >, DimensionedField< Type, Foam::pointMesh >, topoSet, triSurfaceMesh, searchableSurfaceWithGaps, searchableCone, searchableSurfaceCollection, polyBoundaryMesh, searchableRotatedBox, searchableBox, ZoneMesh< Zone, MeshType >, ZoneMesh< faceZone, polyMesh >, ZoneMesh< pointZone, polyMesh >, ZoneMesh< cellZone, polyMesh >, searchableCylinder, porosityModel, searchableSphere, searchableDisk, profiling, searchablePlate, searchableExtrudedCircle, searchablePlane, solidification, powerLawLopesdaCosta, BlendedInterfacialModel< ModelType >, BlendedInterfacialModel< Foam::wallLubricationModel >, BlendedInterfacialModel< Foam::dragModel >, BlendedInterfacialModel< Foam::heatTransferModel >, BlendedInterfacialModel< Foam::virtualMassModel >, BlendedInterfacialModel< Foam::liftModel >, BlendedInterfacialModel< Foam::turbulentDispersionModel >, solver, ATCModel, adjointTurbulenceModel, DarcyForchheimer, objectiveManager, faSchemes, exprResultGlobals, solutionControl, coordinateSystems, adjointSolverManager, adjointSimple, AveragingMethod< Type >, AveragingMethod< scalar >, AveragingMethod< Foam::Vector >, faBoundaryMesh, powerLaw, fixedCoeff, polyTopoChanger, SLGThermo, PDRDragModel, simple, dragModel, dragModel, surfaceTensionModel, virtualMassModel, virtualMassModel, extendedFeatureEdgeMesh, decomposedBlockData, temperatureDependent, RASTurbulenceModel, CompactIOField< T, BaseType >, CompactIOList< T, BaseType >, CompactIOList< face, label >, surfaceTensionModel, liquidProperties, MeshObject< fvMesh, MoveableMeshObject, FitDataType >, MeshObject< polyMesh, GeometricMeshObject, meshSearchMeshObject >, MeshObject< polyMesh, UpdateableMeshObject, decompositionModel >, MeshObject< fvMesh, MoveableMeshObject, CentredFitData< Polynomial > >, MeshObject< fvMesh, TopologicalMeshObject, centredCPCCellToFaceStencilObject >, MeshObject< polyMesh, UpdateableMeshObject, twoDPointCorrector >, MeshObject< fvMesh, UpdateableMeshObject, wallDist >, MeshObject< faMesh, Foam::MoveableMeshObject, leastSquaresFaVectors >, MeshObject< pointMesh, UpdateableMeshObject, pointConstraints >, MeshObject< fvMesh, TopologicalMeshObject, centredCPCCellToCellStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, centredCECCellToCellStencilObject >, MeshObject< polyMesh, GeometricMeshObject, meshSearchFACE_CENTRE_TRISMeshObject >, MeshObject< fvMesh, TopologicalMeshObject, centredCFCFaceToCellStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, upwindFECCellToFaceStencilObject >, MeshObject< fvMesh, MoveableMeshObject, LeastSquaresVectors< Stencil > >, MeshObject< fvMesh, TopologicalMeshObject, centredCFCCellToCellStencilObject >, MeshObject< fvMesh, Foam::GeometricMeshObject, boundaryRadiationProperties >, MeshObject< fvMesh, MoveableMeshObject, leastSquaresVectors >, MeshObject< fvMesh, TopologicalMeshObject, upwindCECCellToFaceStencilObject >, MeshObject< fvMesh, UpdateableMeshObject, volPointInterpolation >, MeshObject< fvMesh, TopologicalMeshObject, upwindCFCCellToFaceStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, upwindCPCCellToFaceStencilObject >, MeshObject< lduMesh, GeometricMeshObject, GAMGAgglomeration >, MeshObject< fvMesh, TopologicalMeshObject, pureUpwindCFCCellToFaceStencilObject >, MeshObject< fvMesh, UpdateableMeshObject, volBSplinesBase >, MeshObject< fvMesh, TopologicalMeshObject, centredCECCellToFaceStencilObject >, MeshObject< fvMesh, MoveableMeshObject, UpwindFitData< Polynomial > >, MeshObject< polyMesh, Foam::UpdateableMeshObject, faMesh >, MeshObject< polyMesh, TopologicalMeshObject, regionSplit >, MeshObject< fvMesh, MoveableMeshObject, skewCorrectionVectors >, MeshObject< polyMesh, UpdateableMeshObject, pointMesh >, MeshObject< fvMesh, TopologicalMeshObject, centredCFCCellToFaceStencilObject >, MeshObject< fvMesh, TopologicalMeshObject, centredFECCellToFaceStencilObject >, MeshObject< Time, TopologicalMeshObject, gravity >, MeshObject< fvMesh, MoveableMeshObject, CentredFitSnGradData< Polynomial > >, lumpedPointIOMovement, GlobalIOField< Type >, GlobalIOField< vector >, surfaceTensionModel, porousModel, GlobalIOList< Type >, GlobalIOList< reactingParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< kinematicParcelInjectionData >, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, constant, baseIOdictionary, exprDriverWriter, IOField< Type >, IOmapDistributePolyMesh, IOPtrList< T >, IOPtrList< Foam::entry >, IOPosition< ParticleType >, IOMap< T >, surfZoneIOList, IOList< T >, IOList< label >, IOList< labelList >, IOmapDistribute, featureEdgeMesh, polyBoundaryMeshEntries, and fieldDictionary.
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp, const bool valid) const virtual
Write using given format, version and compression.
uncomment this if you want to write global objects on master only
bool isGlobal = global();
Reimplemented in distributedTriSurfaceMesh, objectRegistry, fvMesh, polySurface, Time, surfMesh, dynamicOversetFvMesh, triSurfaceMesh, polyBoundaryMesh, dynamicRefineFvMesh, profiling, Cloud< ParticleType >, Cloud< Foam::passiveParticle >, Cloud< wallBoundedStreamLineParticle >, Cloud< indexedParticle >, Cloud< basicKinematicCollidingParcel >, Cloud< typename Foam::DSMCCloud::parcelType >, Cloud< ParcelType >, Cloud< Foam::molecule >, Cloud< solidParticle >, Cloud< parcelType >, Cloud< molecule >, Cloud< passiveParticle >, Cloud< injectedParticle >, Cloud< Foam::DTRMParticle >, Cloud< streamLineParticle >, Cloud< passivePositionParticle >, coordinateSystems, rigidBodyMeshMotion, motionSolver, rigidBodyMeshMotionSolver, faceZoneSet, sixDoFRigidBodyMotionSolver, pointZoneSet, cellZoneSet, decomposedBlockData, CompactIOField< T, BaseType >, CompactIOList< T, BaseType >, CompactIOList< face, label >, and unmappedPassivePositionParticleCloud.
Definition at line 33 of file regIOobjectWrite.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::fileHandler(), IOobject::fileModificationChecking, IOobject::good(), IOobject::inotifyMaster, IOobject::instance(), UList< T >::last(), UPstream::master(), IOobject::name(), IOobject::objectPath(), Foam::Pout, SeriousErrorInFunction, fileOperation::setUnmodified(), UList< T >::size(), Foam::system(), IOobject::time(), timeName, Time::timeName(), IOobject::timeStampMaster, and fileOperation::writeObject().
bool write (const bool valid = true) const virtual
Write using setting from DB.
Reimplemented in faMesh, fvMesh, solver, incompressibleAdjointSolver, AveragingMethod< Type >, AveragingMethod< scalar >, AveragingMethod< Foam::Vector >, incompressiblePrimalSolver, SIMPLEControl, objectiveManager, SIMPLEControlOpt, SIMPLEControlSingleRun, and IOPosition< ParticleType >.
Definition at line 167 of file regIOobjectWrite.C.
Referenced by limitedSnGrad< Type >::correction(), Foam::fvMesh::validComponents< Foam::sphericalTensor >(), Foam::MapLagrangianFields(), meshRefinement::mergePatchFacesUndo(), hexRef8::setUnrefinement(), and PatchCollisionDensity< CloudType >::write().
virtual bool global () const inline virtual
Is object global.
Reimplemented in distributedTriSurfaceMesh, triSurfaceMesh, porosityModel, searchableSurface, extendedFeatureEdgeMesh, UniformDimensionedField< Type >, UniformDimensionedField< scalar >, UniformDimensionedField< vector >, baseIOdictionary, GlobalIOField< Type >, IOMap< T >, GlobalIOField< vector >, featureEdgeMesh, GlobalIOList< Type >, GlobalIOList< reactingParcelInjectionData >, GlobalIOList< reactingMultiphaseParcelInjectionData >, GlobalIOList< kinematicParcelInjectionData >, localIOdictionary, IOdictionary, and unwatchedIOdictionary.
Definition at line 422 of file regIOobject.H.
Referenced by regIOobject::readHeaderOk().
void operator= (const IOobject & io)
Definition at line 463 of file regIOobject.C.
Friends And Related Function Documentation
friend class functionEntries::codeStream friend
Declare friendship with any classes that need access to.
masterOnlyReading
Definition at line 141 of file regIOobject.H.
friend class fileOperations::uncollatedFileOperation friend
Definition at line 142 of file regIOobject.H.
friend class fileOperations::masterUncollatedFileOperation friend
Definition at line 143 of file regIOobject.H.
Member Data Documentation
bool masterOnlyReading = false static protected
To flag master-only reading of objects.
Definition at line 88 of file regIOobject.H.
float fileModificationSkew static
Definition at line 153 of file regIOobject.H.
int maxFileModificationPolls static
Definition at line 155 of file regIOobject.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/regIOobject/regIOobject.H
src/OpenFOAM/db/regIOobject/regIOobject.C
src/OpenFOAM/db/regIOobject/regIOobjectI.H
src/OpenFOAM/db/regIOobject/regIOobjectRead.C
src/OpenFOAM/db/regIOobject/regIOobjectWrite.C