OpenFOAM: viscosityModel Class Reference
viscosityModel Class Reference abstract
Public Member Functions
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const dictionary &dict),(dict))
viscosityModel (const dictionary &dict)
Construct from components.
virtual ~viscosityModel ()
Destructor.
virtual tmp< volScalarField > nu (const volScalarField &alpha1, const volScalarField &Theta, const volScalarField &g0, const volScalarField &rho1, const volScalarField &da, const dimensionedScalar &e) const =0
virtual bool read ()
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, viscosityModel, dictionary,(const dictionary &dict),(dict))
viscosityModel (const dictionary &dict)
Construct from components.
virtual ~viscosityModel ()
Destructor.
virtual tmp< volScalarField > nu (const volScalarField &alpha1, const volScalarField &Theta, const volScalarField &g0, const volScalarField &rho1, const volScalarField &da, const dimensionedScalar &e) const =0
virtual bool read ()
Static Public Member Functions
static autoPtr< viscosityModel > New (const dictionary &dict)
static autoPtr< viscosityModel > New (const dictionary &dict)
Protected Attributes
const dictionary & dict_
Detailed Description
Source files
viscosityModel.H
viscosityModel.C
Definition at line 50 of file viscosityModel.H.
Constructor & Destructor Documentation
viscosityModel (const dictionary & dict)
Construct from components.
Definition at line 38 of file viscosityModel.C.
~viscosityModel () virtual
Destructor.
Definition at line 48 of file viscosityModel.C.
viscosityModel (const dictionary & dict)
Construct from components.
virtual ~viscosityModel () virtual
Destructor.
Member Function Documentation
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , viscosityModel , dictionary , (const dictionary &dict) , (dict))
Foam::autoPtr< Foam::kineticTheoryModels::viscosityModel > New (const dictionary & dict) static
Definition at line 28 of file newViscosityModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volScalarField> nu (const volScalarField & alpha1, const volScalarField & Theta, const volScalarField & g0, const volScalarField & rho1, const volScalarField & da, const dimensionedScalar & e) const pure virtual
Implemented in HrenyaSinclair, HrenyaSinclair, Syamlal, Syamlal, Gidaspow, Gidaspow, noneViscosity, and noneViscosity.
virtual bool read () inline virtual
Reimplemented in HrenyaSinclair, and HrenyaSinclair.
Definition at line 126 of file viscosityModel.H.
TypeName ("viscosityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , viscosityModel , dictionary , (const dictionary &dict) , (dict))
static autoPtr<viscosityModel> New (const dictionary & dict) static
virtual tmp<volScalarField> nu (const volScalarField & alpha1, const volScalarField & Theta, const volScalarField & g0, const volScalarField & rho1, const volScalarField & da, const dimensionedScalar & e) const pure virtual
Implemented in HrenyaSinclair, HrenyaSinclair, Syamlal, Syamlal, Gidaspow, Gidaspow, noneViscosity, and noneViscosity.
virtual bool read () inline virtual
Reimplemented in HrenyaSinclair, and HrenyaSinclair.
Definition at line 126 of file viscosityModel.H.
Member Data Documentation
const dictionary & dict_ protected
Definition at line 69 of file viscosityModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/viscosityModel/viscosityModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/phaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/viscosityModel/viscosityModel.H
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/viscosityModel/newViscosityModel.C
src/phaseSystemModels/reactingEulerFoam/reactingTwoPhaseEulerFoam/twoPhaseCompressibleTurbulenceModels/kineticTheoryModels/viscosityModel/viscosityModel/viscosityModel.C