OpenFOAM: polyPatch Class Reference
polyPatch Class Reference
A patch is a list of labels that address the faces in the global face list.
Public Member Functions
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~polyPatch ()
Destructor.
label offset () const
The offset where this patch starts in the boundary face list.
label start () const
Return start label of this patch in the polyMesh face list.
labelRange range () const
Return start/size range of this patch.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch is geometrically coupled (i.e. faces and.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
tmp< scalarField > areaFraction () const
Return the area fraction as the ratio of the stored face area and the area given by the face points.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &p, const label index)
Copy construct, resetting the index.
virtual ~patchIdentifier ()=default
Destructor.
const word & name () const
Return the patch name.
word & name ()
Modifiable patch name.
const word & physicalType () const
The optional physical type of the patch.
word & physicalType ()
Modifiable optional physical type of the patch.
label index () const
The index of this patch in the boundaryMesh.
label & index ()
Modifiable the index of this patch in the boundaryMesh.
const wordList & inGroups () const
The optional groups that the patch belongs to.
wordList & inGroups ()
Modifiable optional groups that the patch belongs to.
bool inGroup (const word &name) const
Check if the patch is in named group.
void write (Ostream &os) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &&faces, const Field< PointType > &points)
Construct from components, transferring faces.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< PointType > & faceNormals () const
Return face unit normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Static Public Member Functions
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &p)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
virtual void clearGeom ()
Clear geometry.
Friends
class polyBoundaryMesh
Ostream & operator<< (Ostream &, const polyPatch &)
Additional Inherited Members
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Detailed Description
A patch is a list of labels that address the faces in the global face list.
The patch can calculate its own edges based on the global faces. Patch also contains all addressing between the faces.
Source files
polyPatch.H
polyPatch.C
polyPatchNew.C
Definition at line 62 of file polyPatch.H.
Constructor & Destructor Documentation
polyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from components.
Definition at line 74 of file polyPatch.C.
polyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & physicalType, const wordList & inGroups)
Construct from components.
Definition at line 107 of file polyPatch.C.
References List< T >::append(), and patchIdentifier::inGroups().
polyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 131 of file polyPatch.C.
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 168 of file polyPatch.C.
References List< T >::append(), and patchIdentifier::inGroups().
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 192 of file polyPatch.C.
polyPatch (const polyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 219 of file polyPatch.C.
polyPatch (const polyPatch & p)
Construct as copy.
Definition at line 245 of file polyPatch.C.
~polyPatch () virtual
Destructor.
Definition at line 258 of file polyPatch.C.
Member Function Documentation
virtual void initGeometry (PstreamBuffers &) inline protected virtual
Initialise the calculation of the patch geometry.
Reimplemented in oldCyclicPolyPatch, cyclicAMIPolyPatch, cyclicPolyPatch, coupledPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, and mappedWallPolyPatch.
Definition at line 108 of file polyPatch.H.
Referenced by mappedPolyPatch::calcGeometry(), mappedWallPolyPatch::calcGeometry(), cyclicPolyPatch::initGeometry(), and oldCyclicPolyPatch::initGeometry().
virtual void calcGeometry (PstreamBuffers &) inline protected virtual
Calculate the patch geometry.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, coupledPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, wedgePolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, and symmetryPlanePolyPatch.
Definition at line 114 of file polyPatch.H.
Referenced by mappedPolyPatch::initMovePoints(), and mappedWallPolyPatch::initMovePoints().
virtual void initMovePoints (PstreamBuffers & , const pointField &) inline protected virtual
Initialise the patches for moving points.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, and mappedWallPolyPatch.
Definition at line 120 of file polyPatch.H.
Referenced by mappedPolyPatch::movePoints(), mappedWallPolyPatch::movePoints(), and cyclicPolyPatch::movePoints().
void movePoints (PstreamBuffers & , const pointField & p) protected virtual
Correct patches after moving points.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, and mappedWallPolyPatch.
Definition at line 53 of file polyPatch.C.
Referenced by mappedPolyPatch::initUpdateMesh(), mappedWallPolyPatch::initUpdateMesh(), cyclicAMIPolyPatch::initUpdateMesh(), cyclicPolyPatch::initUpdateMesh(), and processorPolyPatch::movePoints().
virtual void initUpdateMesh (PstreamBuffers &) inline protected virtual
Initialise the update of the patch topology.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, and mappedWallPolyPatch.
Definition at line 131 of file polyPatch.H.
Referenced by mappedPolyPatch::updateMesh(), mappedWallPolyPatch::updateMesh(), and cyclicPolyPatch::updateMesh().
void updateMesh (PstreamBuffers &) protected virtual
Update of the patch topology.
Reimplemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, and mappedWallPolyPatch.
Definition at line 58 of file polyPatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::movePoints().
Referenced by cyclicAMIPolyPatch::clearGeom(), cyclicPolyPatch::coupledPoints(), mappedPolyPatch::write(), and mappedWallPolyPatch::write().
void clearGeom () protected virtual
Clear geometry.
Reimplemented in cyclicAMIPolyPatch, and cyclicACMIPolyPatch.
Definition at line 65 of file polyPatch.C.
References PrimitivePatch< Face, FaceList, PointField, PointType >::clearGeom().
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , polyPatch , word , (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType) , (name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr , polyPatch , dictionary , (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType) , (name, dict, index, bm, patchType))
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented in cyclicPolyPatch, cyclicAMIPolyPatch, oldCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, cyclicPeriodicAMIPolyPatch, mappedVariableThicknessWallPolyPatch, wedgePolyPatch, cyclicSlipPolyPatch, nonuniformTransformCyclicPolyPatch, symmetryPlanePolyPatch, genericPolyPatch, oversetPolyPatch, symmetryPolyPatch, emptyPolyPatch, and wallPolyPatch.
Definition at line 272 of file polyPatch.H.
Referenced by fvMeshTools::addPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented in cyclicPolyPatch, cyclicAMIPolyPatch, oldCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, processorCyclicPolyPatch, mappedPolyPatch, mappedWallPolyPatch, cyclicPeriodicAMIPolyPatch, mappedVariableThicknessWallPolyPatch, wedgePolyPatch, nonuniformTransformCyclicPolyPatch, cyclicSlipPolyPatch, symmetryPlanePolyPatch, genericPolyPatch, oversetPolyPatch, symmetryPolyPatch, emptyPolyPatch, and wallPolyPatch.
Definition at line 283 of file polyPatch.H.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented in cyclicPolyPatch, cyclicAMIPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, mappedWallPolyPatch, mappedPolyPatch, cyclicPeriodicAMIPolyPatch, mappedVariableThicknessWallPolyPatch, wedgePolyPatch, nonuniformTransformCyclicPolyPatch, cyclicSlipPolyPatch, symmetryPlanePolyPatch, genericPolyPatch, oversetPolyPatch, symmetryPolyPatch, emptyPolyPatch, and wallPolyPatch.
Definition at line 299 of file polyPatch.H.
Foam::autoPtr< Foam::polyPatch > New (const word & patchType, const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from.
components
Definition at line 28 of file polyPatchNew.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, patchIdentifier::index(), patchIdentifier::name(), and polyPatch::start().
Foam::autoPtr< Foam::polyPatch > New (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from.
dictionary
Definition at line 67 of file polyPatchNew.C.
Foam::autoPtr< Foam::polyPatch > New (const word & patchType, const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from.
dictionary
Definition at line 84 of file polyPatchNew.C.
Foam::label offset () const
The offset where this patch starts in the boundary face list.
The value is the same as patch.start() - mesh.nInternalFaces()
Definition at line 292 of file polyPatch.C.
Referenced by cyclicPolyPatch::clone(), and Foam::ensightOutput::Detail::writeVolField().
label start () const inline
Return start label of this patch in the polyMesh face list.
Definition at line 374 of file polyPatch.H.
Referenced by fvMeshTools::addPatch(), cyclicPolyPatch::clone(), polyMeshTools::faceOrthogonality(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), polyPatch::New(), snappySnapDriver::repatchToSurface(), lumpedPointMovement::setMapping(), Foam::fvc::smooth(), and meshRefinement::zonify().
labelRange range () const inline
Return start/size range of this patch.
Definition at line 382 of file polyPatch.H.
Referenced by polyPatch::patchSlice().
const Foam::polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
Definition at line 298 of file polyPatch.C.
Referenced by cyclicPolyPatch::clone(), and mappedPatchBase::mappedPatchBase().
virtual bool coupled () const inline virtual
Return true if this patch is geometrically coupled (i.e. faces and.
points correspondence)
Reimplemented in cyclicAMIPolyPatch, processorPolyPatch, and coupledPolyPatch.
Definition at line 397 of file polyPatch.H.
Referenced by snappyLayerDriver::doLayers(), polyMeshTools::faceOrthogonality(), meshRefinement::mergePatchFaces(), meshRefinement::mergePatchFacesUndo(), facePointPatch::patch(), Foam::fvc::smooth(), and meshRefinement::zonify().
bool constraintType (const word & pt) static
Return true if the given type is a constraint type.
Definition at line 266 of file polyPatch.C.
Referenced by Foam::evaluateConstraintTypes(), and Foam::reusable().
Foam::wordList constraintTypes () static
Return a list of all the constraint patch types.
Definition at line 272 of file polyPatch.C.
const UIndirectList<T> patchInternalList (const UList< T > & internalValues) const inline
Extract face cell data.
Definition at line 417 of file polyPatch.H.
const List<T>::subList patchSlice (const UList< T > & l) const inline
Slice list to patch.
Definition at line 428 of file polyPatch.H.
const Field<T>::subField patchSlice (const Field< T > & l) const inline
Slice Field to patch.
Definition at line 437 of file polyPatch.H.
References polyPatch::range().
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, oldCyclicPolyPatch, mappedWallPolyPatch, mappedPolyPatch, cyclicPeriodicAMIPolyPatch, mappedVariableThicknessWallPolyPatch, and genericPolyPatch.
Definition at line 396 of file polyPatch.C.
const Foam::vectorField::subField faceCentres () const
Return face centres.
Definition at line 304 of file polyPatch.C.
const Foam::vectorField::subField faceAreas () const
Return face normals.
Definition at line 310 of file polyPatch.C.
References mesh.
Foam::tmp< Foam::vectorField > faceCellCentres () const
Return face cell centres.
Definition at line 316 of file polyPatch.C.
References mesh.
Foam::tmp< Foam::scalarField > areaFraction () const
Return the area fraction as the ratio of the stored face area and the area given by the face points.
Definition at line 335 of file polyPatch.C.
const Foam::labelUList & faceCells () const
Return face-cell addressing.
Definition at line 354 of file polyPatch.C.
Referenced by snappyLayerDriver::doLayers().
const Foam::labelList & meshEdges () const
Return global edge index for local edges.
Definition at line 368 of file polyPatch.C.
void clearAddressing () virtual
Clear addressing.
Definition at line 387 of file polyPatch.C.
label whichFace (const label l) const inline
Return label of face in patch from global face label.
Definition at line 496 of file polyPatch.H.
void initOrder (PstreamBuffers & , const primitivePatch &) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Reimplemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Definition at line 405 of file polyPatch.C.
bool order (PstreamBuffers & , const primitivePatch & , labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Reimplemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, coupledPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Definition at line 410 of file polyPatch.C.
void operator= (const polyPatch & p)
Assignment.
Definition at line 424 of file polyPatch.C.
Friends And Related Function Documentation
friend class polyBoundaryMesh friend
Definition at line 103 of file polyPatch.H.
Ostream& operator<< (Ostream & , const polyPatch &) friend
Member Data Documentation
int disallowGenericPolyPatch static
Debug switch to disallow the use of genericPolyPatch.
Definition at line 155 of file polyPatch.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatch.C
src/OpenFOAM/meshes/polyMesh/polyPatches/polyPatch/polyPatchNew.C