OpenFOAM: UPstream::commsStruct Class Reference
UPstream::commsStruct Class Reference
Structure for communicating between processors.
Public Member Functions
commsStruct ()
Construct null.
commsStruct (const label above, const labelList &below, const labelList &allBelow, const labelList &allNotBelow)
Construct from components.
commsStruct (const label nProcs, const label myProcID, const label above, const labelList &below, const labelList &allBelow)
Construct from components; construct allNotBelow_.
label above () const
const labelList & below () const
const labelList & allBelow () const
const labelList & allNotBelow () const
bool operator== (const commsStruct &) const
bool operator!= (const commsStruct &) const
Friends
Ostream & operator<< (Ostream &, const commsStruct &)
Detailed Description
Structure for communicating between processors.
Definition at line 82 of file UPstream.H.
Constructor & Destructor Documentation
commsStruct ()
Construct null.
Definition at line 26 of file UPstreamCommsStruct.C.
commsStruct (const label above, const labelList & below, const labelList & allBelow, const labelList & allNotBelow)
Construct from components.
Definition at line 36 of file UPstreamCommsStruct.C.
commsStruct (const label nProcs, const label myProcID, const label above, const labelList & below, const labelList & allBelow)
Construct from components; construct allNotBelow_.
Definition at line 51 of file UPstreamCommsStruct.C.
Member Function Documentation
label above () const inline
Definition at line 146 of file UPstream.H.
Referenced by Pstream::combineGather(), Pstream::gather(), and Pstream::gatherList().
const labelList& below () const inline
Definition at line 151 of file UPstream.H.
Referenced by Pstream::combineGather(), Pstream::gather(), and Pstream::gatherList().
const labelList& allBelow () const inline
Definition at line 156 of file UPstream.H.
Referenced by Pstream::gatherList().
const labelList& allNotBelow () const inline
Definition at line 161 of file UPstream.H.
bool operator== (const commsStruct & comm) const
Definition at line 88 of file UPstreamCommsStruct.C.
bool operator!= (const commsStruct & comm) const
Definition at line 100 of file UPstreamCommsStruct.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const commsStruct &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/Pstreams/UPstream.H
src/OpenFOAM/db/IOstreams/Pstreams/UPstreamCommsStruct.C