OpenFOAM: processorCyclicPolyPatch Class Reference
processorCyclicPolyPatch Class Reference
Neighbour processor patch.
Public Member Functions
TypeName ("processorCyclic")
Runtime type information.
processorCyclicPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const word &referPatchName, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components.
processorCyclicPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &, const word &patchType)
Construct from dictionary.
processorCyclicPolyPatch (const processorCyclicPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
processorCyclicPolyPatch (const processorCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
processorCyclicPolyPatch (const processorCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &referPatchName)
Construct as given the original patch and resetting the.
processorCyclicPolyPatch (const processorCyclicPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart, const word &referPatchName) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~processorCyclicPolyPatch ()
const word & referPatchName () const
Return name of originating cyclicPolyPatch patch.
label referPatchID () const
Referring patchID.
const coupledPolyPatch & referPatch () const
virtual int tag () const
Return message tag to use for communication.
virtual bool owner () const
Does this side own the patch ?
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual void transformPosition (pointField &l) const
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &l, const label facei) const
Transform a patch-based position from other side to this side.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from processorPolyPatch
TypeName ("processor")
Runtime type information.
processorPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components with automatically generated standard name.
processorPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &, const word &patchType)
Construct from dictionary.
processorPolyPatch (const processorPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
processorPolyPatch (const processorPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
processorPolyPatch (const processorPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~processorPolyPatch ()
Destructor.
virtual bool coupled () const
Return true only if this is a parallel run.
int myProcNo () const
Return processor number.
int neighbProcNo () const
Return neighbour processor number.
bool neighbour () const
Is the processor the patch neighbour ?
const vectorField & neighbFaceCentres () const
Return processor-neighbour patch face centres.
const vectorField & neighbFaceAreas () const
Return processor-neighbour patch face areas.
const vectorField & neighbFaceCellCentres () const
Return processor-neighbour patch neighbour cell centres.
const labelList & neighbPoints () const
Return neighbour point labels. WIP.
const labelList & neighbEdges () const
Return neighbour edge labels. WIP.
virtual label comm () const
Return communicator used for communication.
Public Member Functions inherited from coupledPolyPatch
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
scalar matchTolerance () const
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual ~polyPatch ()
Destructor.
label offset () const
The offset where this patch starts in the boundary face list.
label start () const
Return start label of this patch in the polyMesh face list.
labelRange range () const
Return start/size range of this patch.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
tmp< scalarField > areaFraction () const
Return the area fraction as the ratio of the stored face area and the area given by the face points.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &p, const label index)
Copy construct, resetting the index.
virtual ~patchIdentifier ()=default
Destructor.
const word & name () const
Return the patch name.
word & name ()
Modifiable patch name.
const word & physicalType () const
The optional physical type of the patch.
word & physicalType ()
Modifiable optional physical type of the patch.
label index () const
The index of this patch in the boundaryMesh.
label & index ()
Modifiable the index of this patch in the boundaryMesh.
const wordList & inGroups () const
The optional groups that the patch belongs to.
wordList & inGroups ()
Modifiable optional groups that the patch belongs to.
bool inGroup (const word &name) const
Check if the patch is in named group.
void write (Ostream &os) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &&faces, const Field< PointType > &points)
Construct from components, transferring faces.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< PointType > & faceNormals () const
Return face unit normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Static Public Member Functions
static word newName (const word &cyclicPolyPatchName, const label myProcNo, const label neighbProcNo)
Return the name of a processorCyclicPolyPatch.
static labelList patchIDs (const word &cyclicPolyPatchName, const polyBoundaryMesh &bm)
Return the indices of a processorCyclicPolyPatchs.
Static Public Member Functions inherited from processorPolyPatch
static word newName (const label myProcNo, const label neighbProcNo)
Return the name of a processorPolyPatch.
static label matchFace (const face &localFace, const pointField &localPts, const face &masterFace, const pointField &masterPts, const bool sameOrientation, const scalar absTolSqr, scalar &matchDistSqr)
Returns rotation.
Static Public Member Functions inherited from coupledPolyPatch
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Protected Member Functions
void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)
Calculate the patch geometry with externally.
void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
Protected Member Functions inherited from processorPolyPatch
processorPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const int myProcNo, const int neighbProcNo, const transformType transform=UNKNOWN, const word &patchType=typeName)
Construct from components with specified name.
Protected Member Functions inherited from coupledPolyPatch
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Additional Inherited Members
Public Types inherited from coupledPolyPatch
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Static Public Attributes inherited from coupledPolyPatch
static const Enum< transformType > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Static Protected Member Functions inherited from coupledPolyPatch
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
Neighbour processor patch.
Note: morph patch face ordering is geometric.
Source files
processorCyclicPolyPatch.H
processorCyclicPolyPatch.C
Definition at line 48 of file processorCyclicPolyPatch.H.
Constructor & Destructor Documentation
processorCyclicPolyPatch (const label size, const label start, const label index, const polyBoundaryMesh & bm, const int myProcNo, const int neighbProcNo, const word & referPatchName, const transformType transform = UNKNOWN, const word & patchType = typeName)
Construct from components.
Definition at line 39 of file processorCyclicPolyPatch.C.
Referenced by processorCyclicPolyPatch::clone().
processorCyclicPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 70 of file processorCyclicPolyPatch.C.
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 86 of file processorCyclicPolyPatch.C.
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct as given the original patch and resetting the.
face list and boundary mesh information
Definition at line 99 of file processorCyclicPolyPatch.C.
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & referPatchName)
Construct as given the original patch and resetting the.
face list, boundary mesh information and referPatch
Definition at line 115 of file processorCyclicPolyPatch.C.
processorCyclicPolyPatch (const processorCyclicPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 132 of file processorCyclicPolyPatch.C.
~processorCyclicPolyPatch () virtual
Definition at line 149 of file processorCyclicPolyPatch.C.
Member Function Documentation
void initGeometry (PstreamBuffers & pBufs) protected virtual
Initialise the calculation of the patch geometry.
Reimplemented from processorPolyPatch.
Definition at line 226 of file processorCyclicPolyPatch.C.
void calcGeometry (PstreamBuffers & pBufs) protected virtual
Calculate the patch geometry.
Reimplemented from processorPolyPatch.
Definition at line 233 of file processorCyclicPolyPatch.C.
References processorPolyPatch::initGeometry().
virtual void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) inline protected virtual
Calculate the patch geometry with externally.
provided geometry
Reimplemented from processorPolyPatch.
Definition at line 90 of file processorCyclicPolyPatch.H.
References NotImplemented.
void initMovePoints (PstreamBuffers & pBufs, const pointField & p) protected virtual
Initialise the patches for moving points.
Reimplemented from processorPolyPatch.
Definition at line 280 of file processorCyclicPolyPatch.C.
void movePoints (PstreamBuffers & pBufs, const pointField &) protected virtual
Correct patches after moving points.
Reimplemented from processorPolyPatch.
Definition at line 291 of file processorCyclicPolyPatch.C.
void initUpdateMesh (PstreamBuffers & pBufs) protected virtual
Initialise the update of the patch topology.
Reimplemented from processorPolyPatch.
Definition at line 300 of file processorCyclicPolyPatch.C.
void updateMesh (PstreamBuffers & pBufs) protected virtual
Update of the patch topology.
Reimplemented from processorPolyPatch.
Definition at line 306 of file processorCyclicPolyPatch.C.
References processorPolyPatch::initUpdateMesh().
TypeName ("processorCyclic")
Runtime type information.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm) const inline virtual
Construct and return a clone, resetting the boundary mesh.
Reimplemented from processorPolyPatch.
Definition at line 216 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::processorCyclicPolyPatch().
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from processorPolyPatch.
Definition at line 227 of file processorCyclicPolyPatch.H.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart, const word & referPatchName) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Definition at line 253 of file processorCyclicPolyPatch.H.
virtual autoPtr<polyPatch> clone (const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart) const inline virtual
Construct and return a clone, resetting the face list.
and boundary mesh
Reimplemented from processorPolyPatch.
Definition at line 281 of file processorCyclicPolyPatch.H.
const word& referPatchName () const inline
Return name of originating cyclicPolyPatch patch.
Definition at line 311 of file processorCyclicPolyPatch.H.
Foam::word newName (const word & cyclicPolyPatchName, const label myProcNo, const label neighbProcNo) static
Return the name of a processorCyclicPolyPatch.
constructed from cyclicPolyPatch name and the processor IDs
Definition at line 156 of file processorCyclicPolyPatch.C.
Foam::labelList patchIDs (const word & cyclicPolyPatchName, const polyBoundaryMesh & bm) static
Return the indices of a processorCyclicPolyPatchs.
constructed from the given cyclicPolyPatch
Definition at line 170 of file processorCyclicPolyPatch.C.
label referPatchID () const inline
Referring patchID.
Definition at line 342 of file processorCyclicPolyPatch.H.
const coupledPolyPatch& referPatch () const inline
Definition at line 362 of file processorCyclicPolyPatch.H.
References coupledPolyPatch::parallel().
Referenced by processorCyclicPolyPatch::owner().
int tag () const virtual
Return message tag to use for communication.
Reimplemented from processorPolyPatch.
Definition at line 186 of file processorCyclicPolyPatch.C.
Referenced by processorCyclicFvPatch::tag().
virtual bool owner () const inline virtual
Does this side own the patch ?
Reimplemented from processorPolyPatch.
Definition at line 376 of file processorCyclicPolyPatch.H.
References processorCyclicPolyPatch::referPatch(), and coupledPolyPatch::reverseT().
virtual transformType transform () const inline virtual
Type of transform.
Reimplemented from coupledPolyPatch.
Definition at line 384 of file processorCyclicPolyPatch.H.
virtual transformType& transform () inline virtual
Type of transform.
This is currently only for use when collapsing generated meshes that can have zero area faces.
Reimplemented from coupledPolyPatch.
Definition at line 395 of file processorCyclicPolyPatch.H.
virtual void transformPosition (pointField & l) const inline virtual
Transform a patch-based position from other side to this side.
Reimplemented from processorPolyPatch.
Definition at line 403 of file processorCyclicPolyPatch.H.
virtual void transformPosition (point & l, const label facei) const inline virtual
Transform a patch-based position from other side to this side.
Reimplemented from processorPolyPatch.
Definition at line 411 of file processorCyclicPolyPatch.H.
virtual bool separated () const inline virtual
Are the planes separated.
Reimplemented from coupledPolyPatch.
Definition at line 419 of file processorCyclicPolyPatch.H.
virtual const vectorField& separation () const inline virtual
If the planes are separated the separation vector.
Reimplemented from coupledPolyPatch.
Definition at line 427 of file processorCyclicPolyPatch.H.
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Reimplemented from coupledPolyPatch.
Definition at line 435 of file processorCyclicPolyPatch.H.
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Reimplemented from coupledPolyPatch.
Definition at line 443 of file processorCyclicPolyPatch.H.
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Reimplemented from coupledPolyPatch.
Definition at line 451 of file processorCyclicPolyPatch.H.
Referenced by processorCyclicFvPatch::forwardT().
virtual const boolList& collocated () const inline virtual
Are faces collocated. Either size 0,1 or length of patch.
Reimplemented from coupledPolyPatch.
Definition at line 459 of file processorCyclicPolyPatch.H.
void initOrder (PstreamBuffers & pBufs, const primitivePatch & pp) const virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Reimplemented from processorPolyPatch.
Definition at line 314 of file processorCyclicPolyPatch.C.
References processorPolyPatch::updateMesh().
bool order (PstreamBuffers & pBufs, const primitivePatch & pp, labelList & faceMap, labelList & rotation) const virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Reimplemented from processorPolyPatch.
Definition at line 325 of file processorCyclicPolyPatch.C.
References processorPolyPatch::initOrder().
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from processorPolyPatch.
Definition at line 337 of file processorCyclicPolyPatch.C.
References processorPolyPatch::order().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/processorCyclic/processorCyclicPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/constraint/processorCyclic/processorCyclicPolyPatch.C