OpenFOAM: ensightFaces Class Reference
ensightFaces Class Reference
Sorting/classification of faces (2D) into corresponding ensight types.
Public Types
enum elemType { TRIA3, QUAD4, NSIDED }
Addressable ensight element types.
Public Member Functions
ensightFaces ()
Construct null, with part index 0.
ensightFaces (const label partIndex)
Construct null, with specified part index.
ensightFaces (const ensightFaces &obj)
Copy constructor. Needed for lists etc.
~ensightFaces ()=default
Destructor.
label index () const
The index in a list.
label & index ()
The index in a list, non-const access.
label size () const
The processor local size of all elements.
label size (const enum elemType) const
The processor local size of the specified element type.
label total () const
The global number of all element types.
label total (const enum elemType) const
The global number of the specified element type.
const FixedList< label, 3 > & totals () const
The global numbers per element type.
FixedList< label, 3 > sizes () const
The processor local sizes per element type.
label offset (const enum elemType what) const
Processor local starting offset of element type.
const labelUList faceIds (const enum elemType) const
Return the (local) face ids of the specified element type.
const labelUList & faceIds () const
Return the processor local face ids of all elements.
const boolList & flipMap () const
Return the processor local flip-map of all elements.
void classify (const faceList &faces)
Classify the face types, set element list.
void classify (const faceList &faces, const labelUList &addressing, const boolList &flipMap=boolList(), const bitSet &exclude=bitSet())
Classify the face types, set element list.
void clear ()
Set addressable sizes to zero, free up addressing memory.
void reduce ()
Sum element counts across all processes.
void sort ()
Sort element lists numerically.
label operator[] (const label i) const
Return element from linear-list.
Static Public Member Functions
static const char * key (const enum elemType)
Return the ensight element name for the specified type.
Static Public Attributes
static constexpr int nTypes = 3
Number of element types (3)
static const char * elemNames [3]
The ensight element type names.
Detailed Description
Sorting/classification of faces (2D) into corresponding ensight types.
Definition at line 45 of file ensightFaces.H.
Member Enumeration Documentation
enum elemType
Addressable ensight element types.
Enumerator
TRIA3
"tria3"
QUAD4
"quad4"
NSIDED
"nsided"
Definition at line 54 of file ensightFaces.H.
Constructor & Destructor Documentation
ensightFaces ()
Construct null, with part index 0.
Definition at line 102 of file ensightFaces.C.
ensightFaces (const label partIndex) explicit
Construct null, with specified part index.
Definition at line 108 of file ensightFaces.C.
ensightFaces (const ensightFaces & obj)
Copy constructor. Needed for lists etc.
Definition at line 120 of file ensightFaces.C.
~ensightFaces () default
Destructor.
Member Function Documentation
const char * key (const enum elemType what) inline static
Return the ensight element name for the specified type.
Definition at line 25 of file ensightFacesI.H.
Foam::label index () const inline
The index in a list.
Definition at line 31 of file ensightFacesI.H.
References ensightFaces::elemNames.
Foam::label & index () inline
The index in a list, non-const access.
Definition at line 37 of file ensightFacesI.H.
Foam::label size () const inline
The processor local size of all elements.
Definition at line 43 of file ensightFacesI.H.
Referenced by Foam::ensightOutput::Detail::writeVolField().
Foam::label size (const enum elemType what) const inline
The processor local size of the specified element type.
Definition at line 61 of file ensightFacesI.H.
Foam::label total () const
The global number of all element types.
This value is only meaningful after a reduce operation.
Definition at line 155 of file ensightFaces.C.
Foam::label total (const enum elemType what) const inline
The global number of the specified element type.
This value is only meaningful after a reduce operation.
Definition at line 55 of file ensightFacesI.H.
const Foam::FixedList< Foam::label, 3 > & totals () const inline
The global numbers per element type.
This value is only meaningful after a reduce operation.
Definition at line 49 of file ensightFacesI.H.
Foam::FixedList< Foam::label, 3 > sizes () const
The processor local sizes per element type.
Definition at line 143 of file ensightFaces.C.
Foam::label offset (const enum elemType what) const inline
Processor local starting offset of element type.
Definition at line 67 of file ensightFacesI.H.
const Foam::labelUList faceIds (const enum elemType what) const inline
Return the (local) face ids of the specified element type.
Definition at line 74 of file ensightFacesI.H.
const Foam::labelUList & faceIds () const inline
Return the processor local face ids of all elements.
Definition at line 82 of file ensightFacesI.H.
const Foam::boolList & flipMap () const inline
Return the processor local flip-map of all elements.
Definition at line 88 of file ensightFacesI.H.
void classify (const faceList & faces)
Classify the face types, set element list.
Definition at line 222 of file ensightFaces.C.
void classify (const faceList & faces, const labelUList & addressing, const boolList & flipMap = boolList(), const bitSet & exclude = bitSet())
Classify the face types, set element list.
The indirect addressing can be used when classifying groups of face (eg, from a faceZone etc) with an optional flipMap. The optional exclude marker can be used to skip faces on particular boundary types or regions.
Definition at line 248 of file ensightFaces.C.
References Foam::add().
void clear ()
Set addressable sizes to zero, free up addressing memory.
Definition at line 166 of file ensightFaces.C.
void reduce ()
Sum element counts across all processes.
Definition at line 173 of file ensightFaces.C.
References Foam::Zero.
void sort ()
Sort element lists numerically.
Definition at line 184 of file ensightFaces.C.
References Foam::reduce().
Foam::label operator[] (const label i) const inline
Return element from linear-list.
Definition at line 94 of file ensightFacesI.H.
Member Data Documentation
constexpr int nTypes = 3 static
Number of element types (3)
Definition at line 64 of file ensightFaces.H.
const char * elemNames static
Initial value:
=
    { "tria3", "quad4", "nsided" }
The ensight element type names.
Definition at line 69 of file ensightFaces.H.
Referenced by ensightFaces::index().
The documentation for this class was generated from the following files:
src/fileFormats/ensight/part/ensightFaces.H
src/fileFormats/ensight/part/ensightFaces.C
src/fileFormats/ensight/part/ensightFacesI.H