OpenFOAM: regExpPosix Class Reference
regExpPosix Class Reference
Wrapper around POSIX extended regular expressions.
Public Types
typedef SubStrings< std::string > results_type
Type for matches - similar to std::smatch.
Public Member Functions
regExpPosix ()
Construct null.
regExpPosix (const regExpPosix &)=delete
Copy construct - disallowed.
regExpPosix (regExpPosix &&rgx)
Move construct.
regExpPosix (const char *pattern)
Construct from character array.
regExpPosix (const std::string &pattern)
Construct from string.
regExpPosix (const char *pattern, bool ignoreCase)
Construct from character array, optionally ignore case.
regExpPosix (const std::string &pattern, bool ignoreCase)
Construct from string, optionally ignore case.
~regExpPosix ()
Destructor.
bool empty () const noexcept
Return true if a precompiled expression does not exist.
bool exists () const noexcept
Return true if a precompiled expression exists.
unsigned ngroups () const
The number of capture groups for a non-empty expression.
bool clear ()
Clear expression.
void swap (regExpPosix &rgx)
Swap contents.
bool set (const char *pattern, bool ignoreCase=false)
Compile pattern into a regular expression, optionally ignore case.
bool set (const std::string &pattern, bool ignoreCase=false)
Compile pattern into a regular expression, optionally ignore case.
std::string::size_type find (const std::string &text) const
Find position within the text.
bool match (const std::string &text) const
True if the regex matches the entire text.
bool match (const std::string &text, results_type &matches) const
True if the regex matches the text, set the matches.
bool search (const std::string &text) const
Return true if the regex was found within the text.
bool operator() (const std::string &text) const
Perform match on text.
void operator= (const regExpPosix &)=delete
Copy assignment - disallowed.
void operator= (regExpPosix &&rgx)
Move assignment.
void operator= (const char *pattern)
Assign and compile pattern from a character array.
void operator= (const std::string &pattern)
Assign and compile pattern from string.
Static Public Member Functions
static bool meta (char c)
Test if character appears to be a regular expression meta-character.
Static Public Attributes
static int grammar
Grammar (unused) - for compatibility with Foam::regExpCxx.
Detailed Description
Wrapper around POSIX extended regular expressions.
The PCRE '(?i)' extension is provided to compile the regular expression as being case-insensitive.
See Also
The manpage regex(7) for more information about POSIX regular expressions. These differ somewhat from Perl and sed regular expressions.
Foam::regExp and Foam::regExpCxx
Warning
This class should not be used directly. Use the Foam::regExp typedef instead.
Deprecated:
This class will be superseded by Foam::regExpCxx as compiler support for regular expressions continues to improve.
Source files
regExpPosix.H
regExpPosixI.H
regExpPosix.C
Definition at line 71 of file regExpPosix.H.
Member Typedef Documentation
typedef SubStrings<std::string> results_type
Type for matches - similar to std::smatch.
Definition at line 87 of file regExpPosix.H.
Constructor & Destructor Documentation
regExpPosix () inline
Construct null.
Definition at line 39 of file regExpPosixI.H.
regExpPosix (const regExpPosix &) delete
Copy construct - disallowed.
regExpPosix (regExpPosix && rgx) inline
Move construct.
Definition at line 77 of file regExpPosixI.H.
References set().
regExpPosix (const char * pattern) inline explicit
Construct from character array.
Definition at line 45 of file regExpPosixI.H.
regExpPosix (const std::string & pattern) inline explicit
Construct from string.
Definition at line 53 of file regExpPosixI.H.
References set().
regExpPosix (const char * pattern, bool ignoreCase) inline
Construct from character array, optionally ignore case.
Definition at line 61 of file regExpPosixI.H.
References set().
regExpPosix (const std::string & pattern, bool ignoreCase) inline
Construct from string, optionally ignore case.
Definition at line 69 of file regExpPosixI.H.
References set().
~regExpPosix () inline
Destructor.
Definition at line 87 of file regExpPosixI.H.
Member Function Documentation
bool meta (char c) inline static
Test if character appears to be a regular expression meta-character.
Returns
true if character is one of the following:
any character: '.'
quantifiers: '*', '+', '?'
grouping: '(', '|', ')'
range: '[', ']'
Note
The presence of '{', '}' regex bounds is not considered
Definition at line 25 of file regExpPosixI.H.
Referenced by wordRe::valid().
bool empty () const inline noexcept
Return true if a precompiled expression does not exist.
Definition at line 95 of file regExpPosixI.H.
References clear().
bool exists () const inline noexcept
Return true if a precompiled expression exists.
Definition at line 101 of file regExpPosixI.H.
unsigned ngroups () const inline
The number of capture groups for a non-empty expression.
Definition at line 107 of file regExpPosixI.H.
bool clear ()
Clear expression.
Returns
True if expression had existed prior to the clear.
Definition at line 47 of file regExpPosix.C.
void swap (regExpPosix & rgx) inline
Swap contents.
Definition at line 119 of file regExpPosixI.H.
References Foam::ListOps::find().
bool set (const char * pattern, bool ignoreCase = false)
Compile pattern into a regular expression, optionally ignore case.
Returns
True if the pattern was compiled
Definition at line 62 of file regExpPosix.C.
bool set (const std::string & pattern, bool ignoreCase = false)
Compile pattern into a regular expression, optionally ignore case.
Returns
True if the pattern was compiled
Definition at line 113 of file regExpPosix.C.
std::string::size_type find (const std::string & text) const
Find position within the text.
Returns
The index where it begins or string::npos if not found
Definition at line 119 of file regExpPosix.C.
References set().
bool match (const std::string & text) const
True if the regex matches the entire text.
The begin-of-line (^) and end-of-line ($) anchors are implicit
Definition at line 136 of file regExpPosix.C.
Referenced by STARCDsurfaceFormatCore::readInpCellTable().
bool match (const std::string & text, results_type & matches) const
True if the regex matches the text, set the matches.
The first group starts at index 1 (0 is the entire match). The begin-of-line (^) and end-of-line ($) anchors are implicit
bool search (const std::string & text) const inline
Return true if the regex was found within the text.
Definition at line 113 of file regExpPosixI.H.
bool operator() (const std::string & text) const inline
Perform match on text.
Definition at line 131 of file regExpPosixI.H.
void operator= (const regExpPosix &) delete
Copy assignment - disallowed.
void operator= (regExpPosix && rgx) inline
Move assignment.
Definition at line 137 of file regExpPosixI.H.
References Foam::stringOps::match().
void operator= (const char * pattern) inline
Assign and compile pattern from a character array.
Matching is case sensitive.
Definition at line 144 of file regExpPosixI.H.
References clear().
void operator= (const std::string & pattern) inline
Assign and compile pattern from string.
Matching is case sensitive.
Definition at line 150 of file regExpPosixI.H.
References set().
Member Data Documentation
int grammar static
Grammar (unused) - for compatibility with Foam::regExpCxx.
Definition at line 95 of file regExpPosix.H.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/regExp/regExpPosix.H
src/OSspecific/POSIX/regExp/regExpPosix.C
src/OSspecific/POSIX/regExp/regExpPosixI.H