OpenFOAM: STARCDsurfaceFormatCore Class Reference
STARCDsurfaceFormatCore Class Reference
Internal class used by the STARCDsurfaceFormat.
Static Protected Member Functions
static Map< word > readInpCellTable (ISstream &is)
static void writeCase (Ostream &os, const UList< point > &pts, const label nFaces, const UList< surfZone > &zoneLst)
Static Protected Member Functions inherited from STARCDCore
static bool readHeader (IFstream &is, const enum fileHeader header)
Read header and check signature PROSTAR_(CELL|VERTEX|BOUNDARY)
static void writeHeader (Ostream &os, const enum fileHeader header)
Write header for fileType (CELL|VERTEX|BOUNDARY)
Additional Inherited Members
Public Types inherited from STARCDCore
enum fileHeader { HEADER_CEL, HEADER_VRT, HEADER_BND }
Enumeration defining the file headers.
enum fileExt { CEL_FILE, VRT_FILE, BND_FILE, INP_FILE }
Enumeration defining the file extensions.
enum matlType {
starcdFluidType = 1, starcdSolidType = 2, starcdBaffleType = 3, starcdShellType = 4,
starcdLineType = 5, starcdPointType = 6
}
Basic material type for STARCD/PROSTAR files.
enum shapeType {
starcdPoint = 1, starcdLine = 2, starcdShell = 3, starcdHex = 11,
starcdPrism = 12, starcdTet = 13, starcdPyr = 14, starcdPoly = 255
}
Shape-Type for STARCD/PROSTAR files.
Static Public Member Functions inherited from STARCDCore
static fileName starFileName (const fileName &baseName, const enum fileExt ext)
Resolve base file-name for the given file-type.
static void removeFiles (const fileName &baseName)
Remove existing PROSTAR files for the given base file-name.
static label readPoints (IFstream &is, List< point > &points, List< label > &ids)
Read points from a (.vrt) file, return the max prostar id used.
static void writePoints (Ostream &os, const UList< point > &points, const scalar scaleFactor=1.0)
Write header and points to (.vrt) file, optionally with scaling.
Static Public Attributes inherited from STARCDCore
static const char *const defaultBoundaryName
The name for default (unassigned) boundaries.
static const char *const defaultSolidBoundaryName
The name we have chosen for default (unassigned) solid boundaries.
Protected Member Functions inherited from STARCDCore
STARCDCore ()=default
Construct null.
Static Protected Attributes inherited from STARCDCore
static const Map< FixedList
< int, 6 > > starToFoamFaceAddr
Face addressing from PROSTAR faces to OpenFOAM faces.
static const Map< FixedList
< int, 6 > > foamToStarFaceAddr
Face addressing from OpenFOAM faces to PROSTAR faces.
Detailed Description
Internal class used by the STARCDsurfaceFormat.
Source files
STARCDsurfaceFormatCore.H
STARCDsurfaceFormatCore.C
Definition at line 51 of file STARCDsurfaceFormatCore.H.
Member Function Documentation
Foam::Map< Foam::word > readInpCellTable (ISstream & is) static protected
Definition at line 35 of file STARCDsurfaceFormatCore.C.
References ISstream::getLine(), IOstream::good(), HashTable< T, label, Hash< label > >::insert(), Foam::cellModeller::lookup(), regExpPosix::match(), Foam::readLabel(), SubStrings< String >::str(), and word::validate().
void writeCase (Ostream & os, const UList< point > & pts, const label nFaces, const UList< surfZone > & zoneLst) static protected
Definition at line 76 of file STARCDsurfaceFormatCore.C.
The documentation for this class was generated from the following files:
src/surfMesh/surfaceFormats/starcd/STARCDsurfaceFormatCore.H
src/surfMesh/surfaceFormats/starcd/STARCDsurfaceFormatCore.C