OpenFOAM: wallPoint Class Reference
wallPoint Class Reference
Holds information regarding nearest wall point. Used in wall distance calculation.
Public Member Functions
wallPoint ()
Construct null.
wallPoint (const point &origin, const scalar distSqr)
Construct from origin, distance.
wallPoint (const wallPoint &)
Construct as copy.
const point & origin () const
point & origin ()
scalar distSqr () const
scalar & distSqr ()
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallPoint &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const wallPoint &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const wallPoint &, TrackingData &td) const
Same (like operator==)
bool operator== (const wallPoint &) const
bool operator!= (const wallPoint &) const
Friends
Ostream & operator<< (Ostream &, const wallPoint &)
Istream & operator>> (Istream &, wallPoint &)
Detailed Description
Holds information regarding nearest wall point. Used in wall distance calculation.
Source files
wallPoint.H
wallPointI.H
wallPoint.C
Definition at line 61 of file wallPoint.H.
Constructor & Destructor Documentation
wallPoint () inline
Construct null.
Definition at line 80 of file wallPointI.H.
wallPoint (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 87 of file wallPointI.H.
wallPoint (const wallPoint & wpt) inline
Construct as copy.
Definition at line 94 of file wallPointI.H.
Member Function Documentation
const Foam::point & origin () const inline
Definition at line 103 of file wallPointI.H.
Referenced by wallPoint::operator!=(), and Foam::operator>>().
Foam::point & origin () inline
Definition at line 109 of file wallPointI.H.
References origin_().
Foam::scalar distSqr () const inline
Definition at line 115 of file wallPointI.H.
References origin_().
Referenced by Foam::operator>>().
Foam::scalar & distSqr () inline
Definition at line 121 of file wallPointI.H.
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 128 of file wallPointI.H.
bool sameGeometry (const polyMesh & , const wallPoint & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 137 of file wallPointI.H.
void leaveDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 166 of file wallPointI.H.
void enterDomain (const polyMesh & , const polyPatch & , const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 194 of file wallPointI.H.
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 180 of file wallPointI.H.
References origin_().
bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 210 of file wallPointI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 233 of file wallPointI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const wallPoint & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 255 of file wallPointI.H.
bool equal (const wallPoint & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 276 of file wallPointI.H.
bool operator== (const wallPoint & rhs) const inline
Definition at line 287 of file wallPointI.H.
References Foam::operator==().
bool operator!= (const wallPoint & rhs) const inline
Definition at line 293 of file wallPointI.H.
References wallPoint::origin().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const wallPoint &) friend
Istream& operator>> (Istream & , wallPoint &) friend
The documentation for this class was generated from the following files:
src/meshTools/cellDist/wallPoint/wallPoint.H
src/meshTools/cellDist/wallPoint/wallPointI.H