OpenFOAM: decompositionInformation Class Reference
decompositionInformation Class Reference
Abstract base class for decomposition.
Public Member Functions
decompositionInformation (const labelUList &adjncy, const labelUList &xadj, const labelUList &decomp, const label nDomains)
Construct.
decompositionInformation (const CompactListList< label > &cellCells, const labelUList &decomp, const label nDomains)
Construct.
~decompositionInformation ()
Destructor.
void clear ()
label nDomains () const
void printSummary (Ostream &os) const
void printDetails (Ostream &os) const
void printAll (Ostream &os) const
Detailed Description
Abstract base class for decomposition.
Source files
decompositionInformation.H
decompositionInformation.C
Definition at line 46 of file decompositionInformation.H.
Constructor & Destructor Documentation
decompositionInformation (const labelUList & adjncy, const labelUList & xadj, const labelUList & decomp, const label nDomains)
Construct.
Definition at line 113 of file decompositionInformation.C.
decompositionInformation (const CompactListList< label > & cellCells, const labelUList & decomp, const label nDomains)
Construct.
Definition at line 128 of file decompositionInformation.C.
~decompositionInformation () inline
Destructor.
Definition at line 132 of file decompositionInformation.H.
Member Function Documentation
void clear ()
Definition at line 143 of file decompositionInformation.C.
References CompactListList< T, Container >::m(), and CompactListList< T, Container >::offsets().
label nDomains () const inline
Definition at line 140 of file decompositionInformation.H.
void printSummary (Ostream & os) const
Definition at line 152 of file decompositionInformation.C.
void printDetails (Ostream & os) const
Definition at line 160 of file decompositionInformation.C.
References Foam::nl, and IOstream::print().
void printAll (Ostream & os) const
Definition at line 209 of file decompositionInformation.C.
The documentation for this class was generated from the following files:
src/parallel/decompose/decompose/decompositionInformation.H
src/parallel/decompose/decompose/decompositionInformation.C