OpenFOAM: plane Class Reference
plane Class Reference
Geometric class that creates a 3D plane and can return the intersection point between a line and the plane.
Classes
class ray
A reference point and direction.
Public Types
enum side { FRONT = 1, BACK = -1, NORMAL = 1, FLIP = -1 }
Side of the plane.
Public Member Functions
plane ()
Construct zero-initialised.
plane (const vector &normalVector)
Construct from normal vector through the origin.
plane (const point &originPoint, const vector &normalVector, const bool doNormalise=true)
Construct from normal vector and point in plane.
plane (const point &point1, const point &point2, const point &point3)
Construct from three points in plane.
plane (const scalarList &coeffs)
Construct from coefficients for the plane equation: ax + by + cz + d = 0.
plane (const FixedList< scalar, 4 > &coeffs)
Construct from coefficients for the plane equation: ax + by + cz + d = 0.
plane (const dictionary &dict)
Construct from dictionary.
plane (Istream &is)
Construct from Istream. Assumes (normal) (origin) input.
const vector & normal () const
The plane unit normal.
const point & origin () const
The plane base point.
point & origin ()
The plane base point, for modification.
const point & refPoint () const
The plane base point (same as origin)
void flip ()
Flip the plane by reversing the normal.
FixedList< scalar, 4 > planeCoeffs () const
Return coefficients for the plane equation: ax + by + cz + d = 0.
point nearestPoint (const point &p) const
Return nearest point in the plane for the given point.
scalar distance (const point &p) const
Return distance (magnitude) from the given point to the plane.
scalar signedDistance (const point &p) const
Return distance from the given point to the plane.
scalar normalIntersect (const point &pnt0, const vector &dir) const
Return cut coefficient for plane and line defined by origin and direction.
scalar normalIntersect (const ray &r) const
Return cut coefficient for plane and ray.
template<class Point , class PointRef >
scalar lineIntersect (const line< Point, PointRef > &l) const
Return the cutting point between the plane and.
ray planeIntersect (const plane &plane2) const
Return the cutting line between this plane and another.
point planePlaneIntersect (const plane &plane2, const plane &plane3) const
Return the cutting point between this plane and two other planes.
point somePointInPlane (const scalar dist=1e-3) const
Return a point somewhere on the plane, a distance from the base.
side sideOfPlane (const point &p) const
Return the side of the plane that the point is on.
int sign (const point &p, const scalar tol=SMALL) const
The sign for the side of the plane that the point is on.
point mirror (const point &p) const
Mirror the supplied point in the plane. Return the mirrored point.
void writeDict (Ostream &os) const
Write to dictionary.
Detailed Description
Geometric class that creates a 3D plane and can return the intersection point between a line and the plane.
Construction from a dictionary is driven by the planeType
For planeType as pointAndNormal :
pointAndNormalDict
{
    point   <point>;   // or basePoint
    normal  <vector>;  // or normalVector
}
For planeType as embeddedPoints :
embeddedPointsDict
{
    point1  <point>;
    point2  <point>;
    point3  <point>;
}
For planeType with planeEquation coefficients :
planeEquationDict
{
   a   <scalar>;
   b   <scalar>;
   c   <scalar>;
   d   <scalar>;
}
Source files
plane.H
plane.C
Definition at line 85 of file plane.H.
Member Enumeration Documentation
enum side
Side of the plane.
Enumerator
FRONT
The front (positive normal) side of the plane.
BACK
The back (negative normal) side of the plane.
NORMAL
Same as FRONT.
FLIP
Same as BACK.
Definition at line 92 of file plane.H.
Constructor & Destructor Documentation
plane () inline
Construct zero-initialised.
Definition at line 23 of file planeI.H.
plane (const vector & normalVector) explicit
Construct from normal vector through the origin.
The vector is normalised to a unit vector on input.
Definition at line 114 of file plane.C.
plane (const point & originPoint, const vector & normalVector, const bool doNormalise = true)
Construct from normal vector and point in plane.
By default, the vector is normalised to a unit vector on input.
Definition at line 124 of file plane.C.
References FUNCTION_NAME.
plane (const point & point1, const point & point2, const point & point3)
Construct from three points in plane.
Definition at line 163 of file plane.C.
plane (const scalarList & coeffs) explicit
Construct from coefficients for the plane equation: ax + by + cz + d = 0.
Definition at line 137 of file plane.C.
References FUNCTION_NAME.
plane (const FixedList< scalar, 4 > & coeffs) explicit
Construct from coefficients for the plane equation: ax + by + cz + d = 0.
Definition at line 150 of file plane.C.
plane (const dictionary & dict) explicit
Construct from dictionary.
Definition at line 169 of file plane.C.
References FUNCTION_NAME.
plane (Istream & is) explicit
Construct from Istream. Assumes (normal) (origin) input.
Definition at line 221 of file plane.C.
Member Function Documentation
const Foam::vector & normal () const inline
The plane unit normal.
Definition at line 32 of file planeI.H.
Referenced by Foam::operator!=().
const Foam::point & origin () const inline
The plane base point.
Definition at line 38 of file planeI.H.
Referenced by Foam::operator!=().
Foam::point & origin () inline
The plane base point, for modification.
Definition at line 44 of file planeI.H.
References origin_().
const Foam::point & refPoint () const inline
The plane base point (same as origin)
Definition at line 50 of file planeI.H.
References origin_().
void flip () inline
Flip the plane by reversing the normal.
Definition at line 56 of file planeI.H.
References origin_().
Foam::FixedList< Foam::scalar, 4 > planeCoeffs () const
Return coefficients for the plane equation: ax + by + cz + d = 0.
Definition at line 232 of file plane.C.
References FUNCTION_NAME.
Foam::point nearestPoint (const point & p) const inline
Return nearest point in the plane for the given point.
Definition at line 62 of file planeI.H.
Foam::scalar distance (const point & p) const inline
Return distance (magnitude) from the given point to the plane.
Definition at line 68 of file planeI.H.
References origin_().
Foam::scalar signedDistance (const point & p) const inline
Return distance from the given point to the plane.
Definition at line 74 of file planeI.H.
References Foam::mag().
Foam::scalar normalIntersect (const point & pnt0, const vector & dir) const
Return cut coefficient for plane and line defined by origin and direction.
Definition at line 283 of file plane.C.
scalar normalIntersect (const ray & r) const inline
Return cut coefficient for plane and ray.
Definition at line 300 of file plane.H.
scalar lineIntersect (const line< Point, PointRef > & l) const inline
Return the cutting point between the plane and.
a line passing through the supplied points
Definition at line 311 of file plane.H.
Foam::plane::ray planeIntersect (const plane & plane2) const
Return the cutting line between this plane and another.
Returned as direction vector and point line goes through.
Definition at line 294 of file plane.C.
References origin_(), and Foam::stabilise().
Foam::point planePlaneIntersect (const plane & plane2, const plane & plane3) const
Return the cutting point between this plane and two other planes.
Definition at line 363 of file plane.C.
Foam::point somePointInPlane (const scalar dist = 1e-3) const
Return a point somewhere on the plane, a distance from the base.
Definition at line 385 of file plane.C.
Foam::plane::side sideOfPlane (const point & p) const inline
Return the side of the plane that the point is on.
If the point is on the plane, then returns NORMAL.
Definition at line 80 of file planeI.H.
References origin_().
int sign (const point & p, const scalar tol = SMALL) const inline
The sign for the side of the plane that the point is on.
Uses the supplied tolerance for rounding around zero.
Returns
0: on plane
+1: front-side
-1: back-side
Definition at line 88 of file planeI.H.
Foam::point mirror (const point & p) const
Mirror the supplied point in the plane. Return the mirrored point.
Definition at line 413 of file plane.C.
void writeDict (Ostream & os) const
Write to dictionary.
Definition at line 428 of file plane.C.
References Foam::distance().
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/plane/plane.H
src/OpenFOAM/meshes/primitiveShapes/plane/plane.C
src/OpenFOAM/meshes/primitiveShapes/plane/planeI.H