OpenFOAM: faMeshMapper Class Reference
faMeshMapper Class Reference
Class holds all the necessary information for mapping fields associated with faMesh.
Public Member Functions
faMeshMapper (const faMesh &mesh, const mapPolyMesh &mpm)
Construct from components.
const faMesh & mesh () const
Return reference to mesh.
const objectRegistry & thisDb () const
Return reference to objectRegistry storing fields. Can be.
label nOldPoints () const
Return number of old points.
label nOldEdges () const
Return number of old edges.
label nOldInternalEdges () const
Return number of old internal edges.
label nOldFaces () const
Return number of old faces.
const labelList & oldPatchSizes () const
Return old patch sizes.
const labelList & oldPatchStarts () const
Return old patch starts.
const labelListList & oldPatchEdgeFaces () const
Return old patch edgeFaces.
const faAreaMapper & areaMap () const
Return surface mapper.
const faEdgeMapper & edgeMap () const
Return edge mapper.
const faBoundaryMeshMapper & boundaryMap () const
Return boundary mapper.
Detailed Description
Class holds all the necessary information for mapping fields associated with faMesh.
Note
In order to capture all necessary mesh sizes and mapping data, mapper is created with the OLD mesh, and provides new mesh data. In the process, field mapping information is assembled from the old faMesh and the mapping data
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
faMeshMapper.H
faMeshMapper.C
Definition at line 64 of file faMeshMapper.H.
Constructor & Destructor Documentation
faMeshMapper (const faMesh & mesh, const mapPolyMesh & mpm)
Construct from components.
Definition at line 26 of file faMeshMapper.C.
References faMesh::boundary(), forAll, patches, and UPtrList< T >::size().
Member Function Documentation
const faMesh& mesh () const inline
Return reference to mesh.
Definition at line 158 of file faMeshMapper.H.
const objectRegistry& thisDb () const inline
Return reference to objectRegistry storing fields. Can be.
removed once fields stored on pointMesh.
Definition at line 168 of file faMeshMapper.H.
label nOldPoints () const inline
Return number of old points.
Definition at line 179 of file faMeshMapper.H.
label nOldEdges () const inline
Return number of old edges.
Definition at line 187 of file faMeshMapper.H.
label nOldInternalEdges () const inline
Return number of old internal edges.
Definition at line 195 of file faMeshMapper.H.
label nOldFaces () const inline
Return number of old faces.
Definition at line 203 of file faMeshMapper.H.
const labelList& oldPatchSizes () const inline
Return old patch sizes.
Definition at line 211 of file faMeshMapper.H.
const labelList& oldPatchStarts () const inline
Return old patch starts.
Definition at line 219 of file faMeshMapper.H.
const labelListList& oldPatchEdgeFaces () const inline
Return old patch edgeFaces.
Definition at line 227 of file faMeshMapper.H.
Referenced by faMesh::updateMesh().
const faAreaMapper& areaMap () const inline
Return surface mapper.
Definition at line 238 of file faMeshMapper.H.
Referenced by faMesh::updateMesh().
const faEdgeMapper& edgeMap () const inline
Return edge mapper.
Definition at line 246 of file faMeshMapper.H.
const faBoundaryMeshMapper& boundaryMap () const inline
Return boundary mapper.
Definition at line 254 of file faMeshMapper.H.
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faMeshMapper/faMeshMapper.H
src/finiteArea/faMesh/faMeshMapper/faMeshMapper.C