OpenFOAM: indexedOctree< Type > Class Template Reference
indexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching.
Classes
class node
Tree node. Has up pointer and down pointers.
Public Member Functions
indexedOctree (const Type &shapes)
Construct null.
indexedOctree (const Type &shapes, const List< node > &nodes, const labelListList &contents)
Construct from components.
indexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
indexedOctree (const Type &shapes, Istream &is)
Construct from Istream.
autoPtr< indexedOctree< Type > > clone () const
Clone.
const Type & shapes () const
Reference to shape.
const List< node > & nodes () const
List of all nodes.
const labelListList & contents () const
List of all contents (referenced by those nodes that are.
const treeBoundBox & bb () const
Top bounding box.
PackedList< 2 > & nodeTypes () const
Per node, per octant whether is fully inside/outside/mixed.
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
template<class FindNearestOp >
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr, const FindNearestOp &fnOp) const
Calculate nearest point on nearest shape.
template<class FindNearestOp >
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint, const FindNearestOp &fnOp) const
Low level: calculate nearest starting from subnode.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to line.
template<class FindNearestOp >
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
template<class FindIntersectOp >
pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
Find nearest intersection of line between start and end.
template<class FindIntersectOp >
pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
Find any intersection of line between start and end.
labelList findBox (const treeBoundBox &bb) const
Find (in no particular order) indices of all shapes inside or.
labelList findSphere (const point &centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
labelBits findNode (const label nodeI, const point &) const
Find deepest node (as parent+octant) containing point. Starts.
label findInside (const point &) const
Find shape containing point. Only implemented for certain.
const labelList & findIndices (const point &) const
Find the shape indices that occupy the result of findNode.
volumeType getVolumeType (const point &) const
Determine type (inside/outside/mixed) for point. unknown if.
template<class CompareOp >
void findNear (const scalar nearDist, const indexedOctree< Type > &tree2, CompareOp &cop) const
Find near pairs and apply CompareOp to them.
void print (prefixOSstream &, const bool printContents, const label) const
Print tree. Either print all indices (printContent = true) or.
bool write (Ostream &os) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &treeStart, const point &treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp &fiOp, const bool verbose) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const bool findAny, const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const point &sample, const scalar startDistSqr, const FindNearestOp &fnOp) const
template<class FindNearestOp >
Foam::pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint, const FindNearestOp &fnOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLine (const point &start, const point &end, const FindIntersectOp &fiOp) const
template<class FindIntersectOp >
Foam::pointIndexHit findLineAny (const point &start, const point &end, const FindIntersectOp &fiOp) const
Static Public Member Functions
static scalar & perturbTol ()
Get the perturbation tolerance.
static bool isContent (const labelBits i)
static bool isEmpty (const labelBits i)
static bool isNode (const labelBits i)
static label getContent (const labelBits i)
static label getNode (const labelBits i)
static direction getOctant (const labelBits i)
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Helper function to return the side. Returns outside if.
static bool overlaps (const point &bbMin, const point &bbMax, const scalar nearestDistSqr, const point &sample)
Helper: does bb intersect a sphere around sample? Or is any.
Friends
Ostream & operator (Ostream &, const indexedOctree< Type > &)
Detailed Description
template<class Type>
class Foam::indexedOctree< Type >
Non-pointer based hierarchical recursive searching.
Source files
indexedOctree.H
indexedOctree.C
Definition at line 46 of file treeDataEdge.H.
Constructor & Destructor Documentation
indexedOctree (const Type & shapes)
Construct null.
Definition at line 2166 of file indexedOctree.C.
indexedOctree (const Type & shapes, const List< node > & nodes, const labelListList & contents)
Construct from components.
Definition at line 2177 of file indexedOctree.C.
indexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
Definition at line 2192 of file indexedOctree.C.
References DynamicList< T, SizeMin >::append(), indexedOctree< Type >::bb(), DynamicList< T, SizeMin >::clear(), indexedOctree< Type >::contents(), Foam::expressions::patchExpr::debug, Foam::endl(), forAll, i, Foam::identity(), Foam::max(), indexedOctree< Type >::nodes(), Foam::Pout, List< T >::setSize(), DynamicList< T, SizeMin >::shrink(), UList< T >::size(), and memInfo::size().
indexedOctree (const Type & shapes, Istream & is)
Construct from Istream.
Definition at line 2364 of file indexedOctree.C.
Member Function Documentation
Foam::scalar & perturbTol () static
Get the perturbation tolerance.
Definition at line 2379 of file indexedOctree.C.
autoPtr<indexedOctree<Type> > clone () const inline
Clone.
Definition at line 521 of file indexedOctree.H.
const Type& shapes () const inline
Reference to shape.
Definition at line 533 of file indexedOctree.H.
Referenced by meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestPoint(), and surfaceFeatures::nearestEdges().
const List<node>& nodes () const inline
List of all nodes.
Definition at line 541 of file indexedOctree.H.
Referenced by distributedTriSurfaceMesh::getVolumeType(), and indexedOctree< Type >::indexedOctree().
const labelListList& contents () const inline
List of all contents (referenced by those nodes that are.
contents)
Definition at line 551 of file indexedOctree.H.
Referenced by indexedOctree< Type >::indexedOctree().
const treeBoundBox& bb () const inline
Top bounding box.
Definition at line 559 of file indexedOctree.H.
Referenced by indexedOctree< Type >::findNear(), meshSearch::findNearestBoundaryFace(), indexedOctree< Type >::indexedOctree(), and surfaceFeatures::nearestSamples().
PackedList<2>& nodeTypes () const inline
Per node, per octant whether is fully inside/outside/mixed.
Definition at line 572 of file indexedOctree.H.
Referenced by distributedTriSurfaceMesh::getVolumeType().
static bool isContent (const labelBits i) inline static
Definition at line 580 of file indexedOctree.H.
static bool isEmpty (const labelBits i) inline static
Definition at line 585 of file indexedOctree.H.
static bool isNode (const labelBits i) inline static
Definition at line 590 of file indexedOctree.H.
static label getContent (const labelBits i) inline static
Definition at line 595 of file indexedOctree.H.
static label getNode (const labelBits i) inline static
Definition at line 605 of file indexedOctree.H.
static direction getOctant (const labelBits i) inline static
Definition at line 615 of file indexedOctree.H.
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Definition at line 2387 of file indexedOctree.C.
pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr, const FindNearestOp & fnOp) const
Calculate nearest point on nearest shape.
Returns
bool : any point found nearer than nearestDistSqr
label: index in shapes
point: actual nearest point found
void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint, const FindNearestOp & fnOp) const
Low level: calculate nearest starting from subnode.
Definition at line 485 of file indexedOctree.C.
References indexedOctree< Type >::node::bb_, i, boundBox::max(), boundBox::min(), treeBoundBox::searchOrder(), and indexedOctree< Type >::node::subNodes_.
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to line.
Returns
bool : any point found?
label: index in shapes
point: actual nearest point found sets:
linePoint : corresponding nearest point on line
Definition at line 2436 of file indexedOctree.C.
pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 2488 of file indexedOctree.C.
References findLine().
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 2505 of file indexedOctree.C.
References findLine().
pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
Find any intersection of line between start and end.
Foam::labelList findBox (const treeBoundBox & bb) const
Find (in no particular order) indices of all shapes inside or.
overlapping bounding box (i.e. all shapes not outside box)
Definition at line 2548 of file indexedOctree.C.
Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
overlapping a bounding sphere (i.e. all shapes not outside sphere)
Definition at line 2568 of file indexedOctree.C.
Foam::labelBits findNode (const label nodeI, const point & sample) const
Find deepest node (as parent+octant) containing point. Starts.
off from starting index in nodes_ (use 0 to start from top) Use getNode and getOctant to extract info, or call findIndices.
Definition at line 2589 of file indexedOctree.C.
References indexedOctree< Type >::node::bb_, indexedOctree< Type >::node::subNodes_, and treeBoundBox::subOctant().
Foam::label findInside (const point & sample) const
Find shape containing point. Only implemented for certain.
shapes.
Definition at line 2625 of file indexedOctree.C.
const Foam::labelList & findIndices (const point & sample) const
Find the shape indices that occupy the result of findNode.
Definition at line 2660 of file indexedOctree.C.
References List< label >::null(), and indexedOctree< Type >::node::subNodes_.
Foam::volumeType getVolumeType (const point & sample) const
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Definition at line 2687 of file indexedOctree.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, i, volumeType::INSIDE, volumeType::MIXED, volumeType::OUTSIDE, Foam::Pout, Foam::type(), and volumeType::UNKNOWN.
Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Helper function to return the side. Returns outside if.
outsideNormal&vec >= 0, inside otherwise
Definition at line 466 of file indexedOctree.C.
bool overlaps (const point & bbMin, const point & bbMax, const scalar nearestDistSqr, const point & sample) static
Helper: does bb intersect a sphere around sample? Or is any.
corner point of bb closer than nearestDistSqr to sample.
Definition at line 38 of file indexedOctree.C.
References boundBox::overlaps().
void findNear (const scalar nearDist, const indexedOctree< Type > & tree2, CompareOp & cop) const
Find near pairs and apply CompareOp to them.
tree2 can be *this or different tree.
Definition at line 2757 of file indexedOctree.C.
References indexedOctree< Type >::bb().
void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Print tree. Either print all indices (printContent = true) or.
just size of contents nodes.
Definition at line 2783 of file indexedOctree.C.
References indexedOctree< Type >::node::bb_, Foam::expressions::patchExpr::debug, Foam::endl(), forAll, j, Foam::nl, indexedOctree< Type >::node::parent_, prefixOSstream::prefix(), Foam::BitOps::print(), UList< T >::size(), treeBoundBox::subBbox(), indexedOctree< Type >::node::subNodes_, and Foam::meshTools::writeOBJ().
bool write (Ostream & os) const
Definition at line 2860 of file indexedOctree.C.
Foam::pointIndexHit findLine (const bool findAny, const point & treeStart, const point & treeEnd, const label startNodeI, const direction startOctant, const FindIntersectOp & fiOp, const bool verbose) const
Definition at line 1551 of file indexedOctree.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), treeBoundBox::faceBits(), Foam::FatalError, FatalErrorInFunction, findLine(), PointIndexHit< Point >::hit(), hitInfo(), i, Foam::Pout, PointIndexHit< Point >::rawPoint(), and WarningInFunction.
Foam::pointIndexHit findLine (const bool findAny, const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 1743 of file indexedOctree.C.
References findLine(), hitInfo(), treeBoundBox::intersects(), treeBoundBox::posBits(), and Foam::Zero.
Foam::pointIndexHit findNearest (const point & sample, const scalar startDistSqr, const FindNearestOp & fnOp) const
Definition at line 2404 of file indexedOctree.C.
References Foam::Zero.
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint, const FindNearestOp & fnOp) const
Definition at line 2455 of file indexedOctree.C.
References Foam::Zero.
Foam::pointIndexHit findLine (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2523 of file indexedOctree.C.
References findLine().
Foam::pointIndexHit findLineAny (const point & start, const point & end, const FindIntersectOp & fiOp) const
Definition at line 2536 of file indexedOctree.C.
References findLine().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const indexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataEdge.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.H
src/OpenFOAM/algorithms/indexedOctree/indexedOctree.C