OpenFOAM: localBlended< Type > Class Template Reference
localBlended< Type > Class Template Reference
Surface interpolation schemes
Two-scheme localBlended differencing scheme.
Public Member Functions
TypeName ("localBlended")
Runtime type information.
localBlended (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
localBlended (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &is)
Construct from mesh, faceFlux and Istream.
virtual ~localBlended ()=default
Destructor.
virtual tmp< surfaceScalarField > blendingFactor (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-based blending factor.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the interpolation weighting factors.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< typename innerProduct
< vector, Type >::type,
fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from blendedSchemeBase< Type >
blendedSchemeBase ()
Constructor.
virtual ~blendedSchemeBase ()=default
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField
< typename innerProduct
< typename SFType::value_type,
Type >::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::localBlended< Type >
Two-scheme localBlended differencing scheme.
Source files
localBlended.H
localBlended.C
Definition at line 52 of file localBlended.H.
Constructor & Destructor Documentation
localBlended (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 98 of file localBlended.H.
localBlended (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & is) inline
Construct from mesh, faceFlux and Istream.
Definition at line 118 of file localBlended.H.
virtual ~localBlended () virtual default
Destructor.
Member Function Documentation
TypeName ("localBlended< Type >")
Runtime type information.
virtual tmp<surfaceScalarField> blendingFactor (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-based blending factor.
Implements blendedSchemeBase< Type >.
Definition at line 148 of file localBlended.H.
References surfaceInterpolationScheme< Type >::mesh(), and IOobject::name().
Referenced by localBlended< Type >::weights().
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 164 of file localBlended.H.
References localBlended< Type >::blendingFactor(), surfaceInterpolationScheme< Type >::mesh(), and IOobject::name().
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the face-interpolate of the given cell field.
with explicit correction
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 186 of file localBlended.H.
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 206 of file localBlended.H.
References localBlended< Type >::correction().
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const inline virtual
Return the explicit correction to the face-interpolate.
for the given field
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 219 of file localBlended.H.
Referenced by localBlended< Type >::corrected().
The documentation for this class was generated from the following file:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/localBlended/localBlended.H