OpenFOAM: cellLimitedGrad< Type, Limiter > Class Template Reference
cellLimitedGrad< Type, Limiter > Class Template Reference
Gradient schemes
cellLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
Public Member Functions
TypeName ("cellLimited")
RunTime type information.
cellLimitedGrad (const fvMesh &mesh, Istream &schemeData)
Construct from mesh and schemeData.
void limitFaceCmpt (scalar &limiter, const scalar maxDelta, const scalar minDelta, const scalar extrapolate) const
void limitFace (Type &limiter, const Type &maxDelta, const Type &minDelta, const Type &extrapolate) const
virtual tmp< GeometricField
< typename outerProduct
< vector, Type >::type,
fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Return the gradient of the given field to the gradScheme::grad.
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type, class Limiter>
class Foam::fv::cellLimitedGrad< Type, Limiter >
cellLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
The scalar limiter based on limiting the extrapolated face values between the maximum and minumum cell and cell neighbour values and is applied to all components of the gradient.
Source files
cellLimitedGrad.H
cellLimitedGrad.C
Definition at line 59 of file cellLimitedGrad.H.
Constructor & Destructor Documentation
cellLimitedGrad (const fvMesh & mesh, Istream & schemeData) inline
Construct from mesh and schemeData.
Definition at line 112 of file cellLimitedGrad.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
Member Function Documentation
TypeName ("cellLimited")
RunTime type information.
void limitFaceCmpt (scalar & limiter, const scalar maxDelta, const scalar minDelta, const scalar extrapolate) const inline
Definition at line 168 of file cellLimitedGrad.H.
void limitFace (Type & limiter, const Type & maxDelta, const Type & minDelta, const Type & extrapolate) const inline
Definition at line 196 of file cellLimitedGrad.H.
References Foam::component(), and Foam::setComponent().
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Return the gradient of the given field to the gradScheme::grad.
for optional caching
Implements gradScheme< Type >.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/cellLimitedGrad/cellLimitedGrad.H
src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/cellLimitedGrad/cellLimitedGrad.C