OpenFOAM: liftModel Class Reference
liftModel Class Reference abstract
Public Member Functions
TypeName ("liftModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~liftModel ()
Destructor.
virtual tmp< volScalarField > Cl () const =0
Return lift coefficient.
virtual tmp< volVectorField > Fi () const
Return phase-intensive lift force.
virtual tmp< volVectorField > F () const
Return lift force.
virtual tmp< surfaceScalarField > Ff () const
Return face lift force.
TypeName ("liftModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, liftModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
liftModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~liftModel ()
Destructor.
virtual tmp< volScalarField > Cl () const =0
Return lift coefficient.
virtual tmp< volVectorField > Fi () const
Return phase-intensive lift force.
virtual tmp< volVectorField > F () const
Return lift force.
virtual tmp< surfaceScalarField > Ff () const
Return face lift force.
Static Public Member Functions
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< liftModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimF
Force dimensions.
Protected Attributes
const phasePair & pair_
Phase pair.
Detailed Description
Source files
liftModel.H
liftModel.C
newLiftModel.C
Source files
liftModel.H
liftModel.C
newLiftModel.C
Definition at line 50 of file liftModel.H.
Constructor & Destructor Documentation
liftModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
Definition at line 43 of file liftModel.C.
~liftModel () virtual
Destructor.
Definition at line 54 of file liftModel.C.
liftModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
virtual ~liftModel () virtual
Destructor.
Member Function Documentation
TypeName ("liftModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , liftModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::liftModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 28 of file newLiftModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volScalarField> Cl () const pure virtual
Return lift coefficient.
Implemented in LegendreMagnaudet, LegendreMagnaudet, Moraga, Moraga, wallDamped, TomiyamaLift, TomiyamaLift, constantLiftCoefficient, constantLiftCoefficient, noLift, and noLift.
Foam::tmp< Foam::volVectorField > Fi () const virtual
Return phase-intensive lift force.
Reimplemented in wallDamped.
Definition at line 60 of file liftModel.C.
Foam::tmp< Foam::volVectorField > F () const virtual
Return lift force.
Reimplemented in wallDamped, noLift, and noLift.
Definition at line 71 of file liftModel.C.
Foam::tmp< Foam::surfaceScalarField > Ff () const virtual
Return face lift force.
Reimplemented in wallDamped, noLift, and noLift.
Definition at line 77 of file liftModel.C.
TypeName ("liftModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , liftModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
static autoPtr<liftModel> New (const dictionary & dict, const phasePair & pair) static
virtual tmp<volScalarField> Cl () const pure virtual
Return lift coefficient.
Implemented in LegendreMagnaudet, LegendreMagnaudet, Moraga, Moraga, wallDamped, TomiyamaLift, TomiyamaLift, constantLiftCoefficient, constantLiftCoefficient, noLift, and noLift.
virtual tmp<volVectorField> Fi () const virtual
Return phase-intensive lift force.
Reimplemented in wallDamped.
virtual tmp<volVectorField> F () const virtual
Return lift force.
Reimplemented in wallDamped, noLift, and noLift.
virtual tmp<surfaceScalarField> Ff () const virtual
Return face lift force.
Reimplemented in wallDamped, noLift, and noLift.
Member Data Documentation
const phasePair & pair_ protected
Phase pair.
Definition at line 59 of file liftModel.H.
static const dimensionSet dimF static
Force dimensions.
Definition at line 90 of file liftModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialModels/liftModels/liftModel/liftModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/interfacialModels/liftModels/liftModel/liftModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialModels/liftModels/liftModel/liftModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialModels/liftModels/liftModel/newLiftModel.C