OpenFOAM: featureEdgeMesh Class Reference
featureEdgeMesh Class Reference
edgeMesh + IO.
Public Member Functions
TypeName ("featureEdgeMesh")
featureEdgeMesh (const IOobject &)
Construct (read) given an IOobject.
featureEdgeMesh (const IOobject &, const pointField &, const edgeList &)
Construct from featureEdgeMesh data.
featureEdgeMesh (const IOobject &, const featureEdgeMesh &)
Construct as copy.
virtual bool readData (Istream &)
ReadData function required for regIOobject read operation.
virtual bool writeData (Ostream &) const
WriteData function required for regIOobject write operation.
virtual bool global () const
Is object global.
virtual fileName filePath () const
Return complete path + object name if the file exists.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Public Member Functions inherited from edgeMesh
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C ()
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const edgeMesh &em)
Copy construct.
edgeMesh (edgeMesh &&em)
Move construct.
edgeMesh (const pointField &points, const edgeList &edges)
Copy construct from components.
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
Move construct from components.
edgeMesh (const fileName &name)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &name, const word &ext)
Construct from file name (uses extension to determine type)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &mesh)
Transfer the contents of the argument and annul the argument.
bool read (const fileName &name, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &name)
Read from file. Chooses reader based on detected extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void scalePoints (const scalar scaleFactor)
Scale points. A non-positive factor is ignored.
virtual void mergePoints (const scalar mergeDist)
Geometric merge points (points within mergeDist) prior to.
virtual void mergeEdges ()
Merge duplicate edges and eliminate unused points.
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &rhs)
Copy assignment.
void operator= (edgeMesh &&rhs)
Move assignment.
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
Construct null.
virtual ~edgeMeshFormatsCore ()=default
Destructor.
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
Construct from MESH.
bool hasDb () const
Return true if thisDb() is a valid DB - here = false.
const objectRegistry & thisDb () const
Return the object registry.
const faMesh & operator() () const
Return reference to polyMesh.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef faMesh::BoundaryMesh BoundaryMesh
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Member Functions inherited from edgeMesh
static label size (const Mesh &mesh)
static bool canRead (const fileName &name, bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &name, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &name)
Select constructed from filename (implicit extension)
static void write (const fileName &name, const edgeMesh &mesh)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Protected Member Functions inherited from edgeMesh
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Read non-comment line.
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Reference to Mesh.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
edgeMesh + IO.
See Also
Foam::extendedFeatureEdgeMesh
Source files
featureEdgeMesh.H
featureEdgeMesh.C
Definition at line 50 of file featureEdgeMesh.H.
Constructor & Destructor Documentation
featureEdgeMesh (const IOobject & io)
Construct (read) given an IOobject.
Definition at line 33 of file featureEdgeMesh.C.
References Foam::defineTypeNameAndDebug().
featureEdgeMesh (const IOobject & io, const pointField & points, const edgeList & edges)
Construct from featureEdgeMesh data.
Definition at line 61 of file featureEdgeMesh.C.
featureEdgeMesh (const IOobject & io, const featureEdgeMesh & em)
Construct as copy.
Definition at line 74 of file featureEdgeMesh.C.
Member Function Documentation
TypeName ("featureEdgeMesh")
bool readData (Istream & is) virtual
ReadData function required for regIOobject read operation.
Reimplemented from regIOobject.
Definition at line 86 of file featureEdgeMesh.C.
bool writeData (Ostream & os) const virtual
WriteData function required for regIOobject write operation.
Implements regIOobject.
Definition at line 93 of file featureEdgeMesh.C.
References IOstream::bad().
virtual bool global () const inline virtual
Is object global.
Reimplemented from regIOobject.
Definition at line 99 of file featureEdgeMesh.H.
References IOobject::globalFilePath(), and Foam::type().
virtual fileName filePath () const inline virtual
Return complete path + object name if the file exists.
either in the case/processor or case otherwise null
Reimplemented from regIOobject.
Definition at line 109 of file featureEdgeMesh.H.
The documentation for this class was generated from the following files:
src/meshTools/edgeMesh/featureEdgeMesh/featureEdgeMesh.H
src/meshTools/edgeMesh/featureEdgeMesh/featureEdgeMesh.C