OpenFOAM: noiseModel Class Reference
noiseModel Class Reference abstract
Base class for noise models.
Public Member Functions
TypeName ("noiseModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, noiseModel, dictionary,(const dictionary &dict),(dict))
Run time selection table.
noiseModel (const dictionary &dict, const bool readFields=true)
Constructor.
virtual ~noiseModel ()=default
Destructor.
virtual bool read (const dictionary &dict)
Read from dictionary.
virtual void calculate ()=0
Abstract call to calculate.
Static Public Member Functions
static autoPtr< noiseModel > New (const dictionary &dict)
Selector.
Protected Member Functions
void readWriteOption (const dictionary &dict, const word &lookup, bool &option) const
Helper function to read write options and provide info feedback.
scalar checkUniformTimeStep (const scalarList &times) const
Check and return uniform time step.
bool validateBounds (const scalarList &p) const
Return true if all pressure data is within min/max bounds.
label findStartTimeIndex (const instantList &allTimes, const scalar startTime) const
Find and return start time index.
fileName baseFileDir (const label dataseti) const
Return the base output directory.
noiseModel (const noiseModel &)=delete
No copy construct.
void operator= (const noiseModel &)=delete
No copy assignment.
Protected Attributes
const dictionary dict_
Copy of dictionary used for construction.
scalar rhoRef_
Reference density (to convert from kinematic to static pressure)
label nSamples_
Number of samples in sampling window, default = 2^16.
scalar fLower_
Lower frequency limit, default = 25Hz.
scalar fUpper_
Upper frequency limit, default = 10kHz.
bool customBounds_
Flag to indicate that custom frequency bounds are being used.
scalar startTime_
Start time, default = 0s.
autoPtr< windowModel > windowModelPtr_
Window model.
word graphFormat_
Graph format.
scalar minPressure_
Min pressure value.
scalar maxPressure_
Min pressure value.
fileName outputPrefix_
Output file prefix, default = ''.
bool writePrmsf_
Write Prmsf; default = yes.
bool writeSPL_
Write SPL; default = yes.
bool writePSD_
Write PSD; default = yes.
bool writePSDf_
Write PSDf; default = yes.
bool writeOctaves_
Write writeOctaves; default = yes.
Detailed Description
Base class for noise models.
Data is read from a dictionary, e.g.
rhoRef          0;
N               4096;
fl              25;
fu              25;
startTime       0;
outputPrefix    "test1";
// Optional write options dictionary
writeOptions
{
    writePrmsf  no;
    writeSPL    yes;
    writePSD    yes;
    writePSDf   no;
    writeOctaves yes;
}
where
Property Description Required Default value
rhoRef Reference density no 1
N Number of samples in sampling window no 65536 (2^16)
fl Lower frequency bounds no 25
fu Upper frequency bounds no 10000
startTime Start time no 0
outputPrefix Prefix applied to output files no ''
graphFormat Graph format no raw
writePrmsf Write Prmsf data no yes
writeSPL Write SPL data no yes
writePSD Write PSD data no yes
writePSDf Write PSDf data no yes
writeOctaves Write octaves data no yes
Source files
noiseModel.H
noiseModel.C
Definition at line 154 of file noiseModel.H.
Constructor & Destructor Documentation
noiseModel (const noiseModel &) protected delete
No copy construct.
noiseModel (const dictionary & dict, const bool readFields = true)
Constructor.
Definition at line 153 of file noiseModel.C.
virtual ~noiseModel () virtual default
Destructor.
Member Function Documentation
void readWriteOption (const dictionary & dict, const word & lookup, bool & option) const protected
Helper function to read write options and provide info feedback.
Definition at line 36 of file noiseModel.C.
Foam::scalar checkUniformTimeStep (const scalarList & times) const protected
Check and return uniform time step.
Definition at line 59 of file noiseModel.C.
References Foam::endl(), and Foam::Info.
bool validateBounds (const scalarList & p) const protected
Return true if all pressure data is within min/max bounds.
Definition at line 95 of file noiseModel.C.
Foam::label findStartTimeIndex (const instantList & allTimes, const scalar startTime) const protected
Find and return start time index.
Definition at line 118 of file noiseModel.C.
Foam::fileName baseFileDir (const label dataseti) const protected
Return the base output directory.
Definition at line 137 of file noiseModel.C.
void operator= (const noiseModel &) protected delete
No copy assignment.
TypeName ("noiseModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , noiseModel , dictionary , (const dictionary &dict) , (dict))
Run time selection table.
Foam::autoPtr< Foam::noiseModel > New (const dictionary & dict) static
Selector.
Definition at line 25 of file noiseModelNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, and dictionary::subDict().
bool read (const dictionary & dict) virtual
Read from dictionary.
Reimplemented in surfaceNoise, and pointNoise.
Definition at line 182 of file noiseModel.C.
virtual void calculate () pure virtual
Abstract call to calculate.
Implemented in surfaceNoise, and pointNoise.
Member Data Documentation
const dictionary dict_ protected
Copy of dictionary used for construction.
Definition at line 163 of file noiseModel.H.
scalar rhoRef_ protected
Reference density (to convert from kinematic to static pressure)
Definition at line 168 of file noiseModel.H.
label nSamples_ protected
Number of samples in sampling window, default = 2^16.
Definition at line 173 of file noiseModel.H.
scalar fLower_ protected
Lower frequency limit, default = 25Hz.
Definition at line 178 of file noiseModel.H.
scalar fUpper_ protected
Upper frequency limit, default = 10kHz.
Definition at line 183 of file noiseModel.H.
bool customBounds_ protected
Flag to indicate that custom frequency bounds are being used.
Definition at line 188 of file noiseModel.H.
scalar startTime_ protected
Start time, default = 0s.
Definition at line 193 of file noiseModel.H.
autoPtr<windowModel> windowModelPtr_ protected
Window model.
Definition at line 198 of file noiseModel.H.
word graphFormat_ protected
Graph format.
Definition at line 203 of file noiseModel.H.
scalar minPressure_ protected
Min pressure value.
Definition at line 211 of file noiseModel.H.
scalar maxPressure_ protected
Min pressure value.
Definition at line 216 of file noiseModel.H.
fileName outputPrefix_ protected
Output file prefix, default = ''.
Definition at line 224 of file noiseModel.H.
bool writePrmsf_ protected
Write Prmsf; default = yes.
Definition at line 229 of file noiseModel.H.
bool writeSPL_ protected
Write SPL; default = yes.
Definition at line 234 of file noiseModel.H.
bool writePSD_ protected
Write PSD; default = yes.
Definition at line 239 of file noiseModel.H.
bool writePSDf_ protected
Write PSDf; default = yes.
Definition at line 244 of file noiseModel.H.
bool writeOctaves_ protected
Write writeOctaves; default = yes.
Definition at line 249 of file noiseModel.H.
The documentation for this class was generated from the following files:
src/randomProcesses/noise/noiseModels/noiseModel/noiseModel.H
src/randomProcesses/noise/noiseModels/noiseModel/noiseModel.C
src/randomProcesses/noise/noiseModels/noiseModel/noiseModelNew.C