OpenFOAM: directionInfo Class Reference
directionInfo Class Reference
Holds direction in which to split cell (in fact a local coordinate axes). Information is a label and a direction.
Public Member Functions
directionInfo ()
Construct null.
directionInfo (const label, const vector &n)
Construct from components.
directionInfo (const directionInfo &)
Construct as copy.
label index () const
const vector & n () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const directionInfo &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const directionInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const directionInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const directionInfo &) const
bool operator!= (const directionInfo &) const
Static Public Member Functions
static label edgeToFaceIndex (const primitiveMesh &mesh, const label celli, const label facei, const label edgeI)
Given edge on hex cell find corresponding edge on face. Is either.
Friends
Ostream & operator<< (Ostream &, const directionInfo &)
Istream & operator>> (Istream &, directionInfo &)
Detailed Description
Holds direction in which to split cell (in fact a local coordinate axes). Information is a label and a direction.
The direction is the normal direction to cut in. The label's meaning depends on whether the info is on a cell or on a face:
in cell: edge that is being cut. (determines for hex how cut is)
in face: local face point that is being cut or -1.
(-1) : cut is tangential to plane
(>= 0): edge fp..fp+1 is cut
(has to be facepoint, not vertex since vertex not valid across processors whereas f[0] should correspond to f[0] on other side)
The rule is that if the label is set (-1 or higher) it is used (topological information only), otherwise the vector is used. This makes sure that we use topological information as much as possible and so a hex mesh is cut purely topologically. All other shapes are cut geometrically.
Source files
directionInfo.H
directionInfoI.H
directionInfo.C
Definition at line 81 of file directionInfo.H.
Constructor & Destructor Documentation
directionInfo () inline
Construct null.
Definition at line 28 of file directionInfoI.H.
directionInfo (const label index, const vector & n) inline
Construct from components.
Definition at line 37 of file directionInfoI.H.
directionInfo (const directionInfo & w2) inline
Construct as copy.
Definition at line 48 of file directionInfoI.H.
Member Function Documentation
Foam::label edgeToFaceIndex (const primitiveMesh & mesh, const label celli, const label facei, const label edgeI) static
Given edge on hex cell find corresponding edge on face. Is either.
index in face or -1 (cut tangential to face). Public since is needed to fill in seed faces in meshWave.
Definition at line 88 of file directionInfo.C.
label index () const inline
Definition at line 159 of file directionInfo.H.
Referenced by directionInfo::operator!=().
const vector& n () const inline
Definition at line 164 of file directionInfo.H.
Referenced by directionInfo::operator!=().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 58 of file directionInfoI.H.
bool sameGeometry (const polyMesh & , const directionInfo & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 67 of file directionInfoI.H.
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 82 of file directionInfoI.H.
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 98 of file directionInfoI.H.
References f(), and UList< T >::size().
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 118 of file directionInfoI.H.
bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 129 of file directionInfoI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 210 of file directionInfoI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const directionInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 259 of file directionInfoI.H.
bool equal (const directionInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 285 of file directionInfoI.H.
bool operator== (const directionInfo & rhs) const inline
Definition at line 296 of file directionInfoI.H.
References Foam::operator==().
bool operator!= (const directionInfo & rhs) const inline
Definition at line 303 of file directionInfoI.H.
References directionInfo::index(), n, and directionInfo::n().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const directionInfo &) friend
Istream& operator>> (Istream & , directionInfo &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/directions/directionInfo/directionInfo.H
src/dynamicMesh/meshCut/directions/directionInfo/directionInfo.C
src/dynamicMesh/meshCut/directions/directionInfo/directionInfoI.H