OpenFOAM: WallCollisionRecord< Type > Class Template Reference
WallCollisionRecord< Type > Class Template Reference
Record of a collision between the particle holding the record and a wall face at the position relative to the centre of the particle.
Public Member Functions
WallCollisionRecord ()
Construct null.
WallCollisionRecord (bool accessed, const vector &pRel, const Type &data=Type(Zero))
Construct from components.
WallCollisionRecord (Istream &)
Construct from Istream.
WallCollisionRecord (const WallCollisionRecord &)
Construct as copy.
~WallCollisionRecord ()
Destructor.
const vector & pRel () const
Return the pRel data.
const Type & collisionData () const
Return access to the collision data.
Type & collisionData ()
Return access to the collision data.
bool match (const vector &pRel, scalar radius)
bool accessed () const
Return the accessed status of the record.
void setAccessed ()
Set the accessed property of the record to accessed.
void setUnaccessed ()
Set the accessed property of the record to unaccessed.
void operator= (const WallCollisionRecord &)
Static Public Attributes
static const scalar errorCosAngle
Tolerance for detecting seriously erroneous wall matches.
Friends
bool operator== (const WallCollisionRecord< Type > &, const WallCollisionRecord< Type > &)
bool operator!= (const WallCollisionRecord< Type > &, const WallCollisionRecord< Type > &)
Istream & operator>> (Istream &, WallCollisionRecord< Type > &)
Ostream & operator (Ostream &, const WallCollisionRecord< Type > &)
Detailed Description
template<class Type>
class Foam::WallCollisionRecord< Type >
Record of a collision between the particle holding the record and a wall face at the position relative to the centre of the particle.
Source files
WallCollisionRecord.H
WallCollisionRecordI.H
WallCollisionRecord.C
WallCollisionRecordIO.C
Definition at line 47 of file WallCollisionRecord.H.
Constructor & Destructor Documentation
WallCollisionRecord ()
Construct null.
Definition at line 33 of file WallCollisionRecord.C.
WallCollisionRecord (bool accessed, const vector & pRel, const Type & data = Type(Zero))
Construct from components.
Definition at line 43 of file WallCollisionRecord.C.
WallCollisionRecord (Istream & is)
Construct from Istream.
Definition at line 27 of file WallCollisionRecordIO.C.
References IOstream::check(), and FUNCTION_NAME.
WallCollisionRecord (const WallCollisionRecord< Type > &)
Construct as copy.
~WallCollisionRecord ()
Destructor.
Definition at line 70 of file WallCollisionRecord.C.
Member Function Documentation
const Foam::vector & pRel () const inline
Return the pRel data.
Definition at line 68 of file WallCollisionRecordI.H.
const Type & collisionData () const inline
Return access to the collision data.
Definition at line 76 of file WallCollisionRecordI.H.
Type & collisionData () inline
Return access to the collision data.
Definition at line 83 of file WallCollisionRecordI.H.
bool match (const vector & pRel, scalar radius) inline
Definition at line 25 of file WallCollisionRecordI.H.
References Foam::abort(), Foam::endl(), Foam::FatalError, FatalErrorInFunction, Foam::Info, Foam::mag(), and Foam::nl.
bool accessed () const inline
Return the accessed status of the record.
Definition at line 90 of file WallCollisionRecordI.H.
void setAccessed () inline
Set the accessed property of the record to accessed.
Definition at line 97 of file WallCollisionRecordI.H.
void setUnaccessed () inline
Set the accessed property of the record to unaccessed.
Definition at line 104 of file WallCollisionRecordI.H.
void operator= (const WallCollisionRecord< Type > &)
Definition at line 78 of file WallCollisionRecord.C.
Friends And Related Function Documentation
bool operator== (const WallCollisionRecord< Type > & , const WallCollisionRecord< Type > &) friend
bool operator!= (const WallCollisionRecord< Type > & , const WallCollisionRecord< Type > &) friend
Istream& operator>> (Istream & , WallCollisionRecord< Type > &) friend
Ostream& operator (Ostream & , const WallCollisionRecord< Type > &) friend
Member Data Documentation
const Foam::scalar errorCosAngle static
Tolerance for detecting seriously erroneous wall matches.
Definition at line 102 of file WallCollisionRecord.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecord.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecord.C
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecordI.H
src/lagrangian/intermediate/parcels/Templates/CollidingParcel/CollisionRecordList/WallCollisionRecord/WallCollisionRecordIO.C