OpenFOAM: solutionControl Class Reference
solutionControl Class Reference abstract
Base class for solution control classes.
Classes
struct fieldData
Simple convenient storage of field residuals.
Public Member Functions
TypeName ("solutionControl")
Run-time type information.
solutionControl (fvMesh &mesh, const word &algorithmName)
Construct from mesh.
virtual ~solutionControl ()=default
Destructor.
virtual const dictionary dict () const
Return the solution dictionary.
label corr () const
Current corrector loop index.
label corrNonOrtho () const
Current non-orthogonal corrector index.
label nNonOrthCorr () const
Maximum number of non-orthogonal correctors.
bool finalNonOrthogonalIter () const
Helper function to identify final non-orthogonal iteration.
bool momentumPredictor () const
Flag to indicate to solve for momentum.
bool transonic () const
Flag to indicate to solve using transonic algorithm.
bool consistent () const
Flag to indicate to relax pressure using the.
bool frozenFlow () const
Flag to indicate that the flow system of equations should not.
virtual bool loop ()=0
Main control loop.
bool correctNonOrthogonal ()
Non-orthogonal corrector loop.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Static Public Member Functions
static Pair< scalar > maxResidual (const fvMesh &fvmesh, const entry &dataDictEntry)
Extract maximum residual for the solver performance entry, provided the corresponding volume field is available on the mesh.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Protected Member Functions
virtual bool read (const bool absTolOnly)
Read controls from fvSolution dictionary.
virtual bool read ()
Read controls from fvSolution dictionary.
virtual label applyToField (const word &fieldName, const bool useRegEx=true) const
Return index of field in residualControl_ if present.
virtual bool criteriaSatisfied ()=0
Return true if all convergence checks are satisfied.
virtual void storePrevIterFields () const
Store previous iteration fields.
template<class Type >
void storePrevIter () const
Store previous iteration field for vol<Type>Fields.
Pair< scalar > maxResidual (const entry &solverPerfDictEntry) const
Extract the maximum residual for the specified field.
virtual void setFirstIterFlag (const bool check=true, const bool force=false)
Set the firstIteration flag on the mesh data dictionary.
virtual bool writeData (Ostream &) const
Dummy write for regIOobject.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Static Protected Member Functions
template<class Type >
static bool maxTypeResidual (const fvMesh &fvmesh, const entry &solverPerfDictEntry, Pair< scalar > &residuals)
Initial and final residual of the specified field-name, provided that the corresponding volume field is available on the fvMesh.
Protected Attributes
fvMesh & mesh_
Reference to the mesh database.
List< fieldData > residualControl_
List of residual data per field.
const word algorithmName_
The dictionary name, e.g. SIMPLE, PIMPLE.
label nNonOrthCorr_
Maximum number of non-orthogonal correctors.
bool momentumPredictor_
Flag to indicate to solve for momentum.
bool transonic_
Flag to indicate to solve using transonic algorithm.
bool consistent_
Flag to indicate to relax pressure using the.
bool frozenFlow_
Flag to indicate that the flow system of equations should not.
label corr_
Current corrector loop index.
label corrNonOrtho_
Current non-orthogonal corrector loop index.
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
Base class for solution control classes.
Definition at line 43 of file solutionControl.H.
Constructor & Destructor Documentation
solutionControl (fvMesh & mesh, const word & algorithmName)
Construct from mesh.
Definition at line 264 of file solutionControl.C.
virtual ~solutionControl () virtual default
Destructor.
Member Function Documentation
Foam::Pair< Foam::scalar > maxResidual (const fvMesh & fvmesh, const entry & dataDictEntry) static
Extract maximum residual for the solver performance entry, provided the corresponding volume field is available on the mesh.
Returns
initial residual as first member, the final residual as the second (or last) member
Definition at line 235 of file solutionControl.C.
bool read (const bool absTolOnly) protected virtual
Read controls from fvSolution dictionary.
Definition at line 33 of file solutionControl.C.
References Foam::defineTypeNameAndDebug().
bool read () protected virtual
Read controls from fvSolution dictionary.
Reimplemented from regIOobject.
Reimplemented in SIMPLEControl, pimpleControl, SIMPLEControlOpt, SIMPLEControlSingleRun, and simpleControl.
Definition at line 128 of file solutionControl.C.
Referenced by simpleControl::criteriaSatisfied().
Foam::label applyToField (const word & fieldName, const bool useRegEx = true) const protected virtual
Return index of field in residualControl_ if present.
Definition at line 135 of file solutionControl.C.
References Foam::read().
virtual bool criteriaSatisfied () protected pure virtual
Return true if all convergence checks are satisfied.
Implemented in pimpleControl, SIMPLEControlOpt, and simpleControl.
void storePrevIterFields () const protected virtual
Store previous iteration fields.
Definition at line 152 of file solutionControl.C.
void storePrevIter () const protected
Store previous iteration field for vol<Type>Fields.
Definition at line 29 of file solutionControlTemplates.C.
References solutionControl::algorithmName_, DebugInfo, Foam::endl(), fld, forAllIters, iter, solutionControl::mesh_, and solution::relaxField().
bool maxTypeResidual (const fvMesh & fvmesh, const entry & solverPerfDictEntry, Pair< scalar > & residuals) static protected
Initial and final residual of the specified field-name, provided that the corresponding volume field is available on the fvMesh.
Populate residuals with initial residual as first member and the final residual as second (last) member.
Definition at line 210 of file solutionControl.C.
References Foam::cmptMax(), FixedList< T, N >::first(), objectRegistry::foundObject(), entry::keyword(), FixedList< T, N >::last(), and entry::stream().
Foam::Pair< Foam::scalar > maxResidual (const entry & solverPerfDictEntry) const protected
Extract the maximum residual for the specified field.
Returns
initial residual as first member, the final residual as second (last) member
Definition at line 164 of file solutionControl.C.
void setFirstIterFlag (const bool check = true, const bool force = false) protected virtual
Set the firstIteration flag on the mesh data dictionary.
Reimplemented in pimpleControl.
Definition at line 173 of file solutionControl.C.
bool writeData (Ostream &) const protected virtual
Dummy write for regIOobject.
Implements regIOobject.
Definition at line 198 of file solutionControl.C.
References DebugInfo, and Foam::endl().
TypeName ("solutionControl")
Run-time type information.
const Foam::dictionary dict () const virtual
Return the solution dictionary.
Reimplemented in SIMPLEControl.
Definition at line 292 of file solutionControl.C.
Foam::label corr () const inline
Current corrector loop index.
Definition at line 23 of file solutionControlI.H.
Foam::label corrNonOrtho () const inline
Current non-orthogonal corrector index.
Definition at line 29 of file solutionControlI.H.
References solutionControl::corr_.
Foam::label nNonOrthCorr () const inline
Maximum number of non-orthogonal correctors.
Definition at line 35 of file solutionControlI.H.
bool finalNonOrthogonalIter () const inline
Helper function to identify final non-orthogonal iteration.
Definition at line 41 of file solutionControlI.H.
Referenced by Foam::CorrectPhi().
bool momentumPredictor () const inline
Flag to indicate to solve for momentum.
Definition at line 47 of file solutionControlI.H.
bool transonic () const inline
Flag to indicate to solve using transonic algorithm.
Definition at line 53 of file solutionControlI.H.
bool consistent () const inline
Flag to indicate to relax pressure using the.
"consistent" approach of SIMPLEC
Definition at line 59 of file solutionControlI.H.
bool frozenFlow () const inline
Flag to indicate that the flow system of equations should not.
be evolved
Definition at line 65 of file solutionControlI.H.
virtual bool loop () pure virtual
Main control loop.
Implemented in pimpleControl, SIMPLEControl, SIMPLEControlOpt, SIMPLEControlSingleRun, and simpleControl.
bool correctNonOrthogonal () inline
Non-orthogonal corrector loop.
Definition at line 71 of file solutionControlI.H.
Referenced by Foam::CorrectPhi().
Member Data Documentation
fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 85 of file solutionControl.H.
Referenced by solutionControl::storePrevIter().
List<fieldData> residualControl_ protected
List of residual data per field.
Definition at line 90 of file solutionControl.H.
const word algorithmName_ protected
The dictionary name, e.g. SIMPLE, PIMPLE.
Definition at line 95 of file solutionControl.H.
Referenced by solutionControl::storePrevIter().
label nNonOrthCorr_ protected
Maximum number of non-orthogonal correctors.
Definition at line 103 of file solutionControl.H.
bool momentumPredictor_ protected
Flag to indicate to solve for momentum.
Definition at line 108 of file solutionControl.H.
bool transonic_ protected
Flag to indicate to solve using transonic algorithm.
Definition at line 113 of file solutionControl.H.
bool consistent_ protected
Flag to indicate to relax pressure using the.
"consistent" approach of SIMPLEC
Definition at line 120 of file solutionControl.H.
bool frozenFlow_ protected
Flag to indicate that the flow system of equations should not.
be evolved
Definition at line 127 of file solutionControl.H.
label corr_ protected
Current corrector loop index.
Definition at line 135 of file solutionControl.H.
Referenced by solutionControl::corrNonOrtho().
label corrNonOrtho_ protected
Current non-orthogonal corrector loop index.
Definition at line 140 of file solutionControl.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControl.H
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControl.C
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControlI.H
src/finiteVolume/cfdTools/general/solutionControl/solutionControl/solutionControlTemplates.C