OpenFOAM: cellVolumeWeight Class Reference
cellVolumeWeight Class Reference
Volume-weighted interpolation stencil.
Public Member Functions
TypeName ("cellVolumeWeight")
Runtime type information.
cellVolumeWeight (const fvMesh &, const dictionary &, const bool doUpdate)
Construct from fvMesh.
virtual ~cellVolumeWeight ()
Destructor.
scalar overlapTolerance () const
Access to volume overlap tolerance.
virtual bool update ()
Update stencils. Return false if nothing changed.
virtual const labelUList & cellTypes () const
Return the cell type list.
virtual const labelUList & interpolationCells () const
Indices of interpolated cells.
virtual const mapDistribute & cellInterpolationMap () const
Return a communication schedule.
virtual const labelListList & cellStencil () const
Per interpolated cell the neighbour cells (in terms of slots as.
virtual const List< scalarList > & cellInterpolationWeights () const
Weights for cellStencil.
virtual const scalarList & cellInterpolationWeight () const
Per interpolated cell the interpolation factor. (0 = use.
virtual void stencilWeights (const point &sample, const pointList &donorCcs, scalarList &weights) const
Calculate inverse distance weights for a single acceptor. Revert.
Public Member Functions inherited from cellCellStencil
TypeName ("cellCellStencil")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellCellStencil, mesh,(const fvMesh &mesh, const dictionary &dict, const bool update),(mesh, dict, update))
cellCellStencil (const fvMesh &)
Construct from fvMesh.
virtual ~cellCellStencil ()
Destructor.
virtual const wordHashSet & nonInterpolatedFields () const
Return the names of any (stencil or mesh specific) fields that.
virtual wordHashSet & nonInterpolatedFields ()
Return non-const non-interpolating fields.
bool localStencil (const labelUList &) const
Helper: is stencil fully local.
const labelIOList & zoneID () const
Helper: get reference to registered zoneID. Loads volScalarField.
template<class Type >
Foam::tmp< Foam::volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &psi)
Protected Member Functions
void walkFront (const scalar layerRelax, labelList &allCellTypes, scalarField &allWeight) const
void findHoles (const globalIndex &globalCells, const fvMesh &mesh, const labelList &zoneID, const labelListList &stencil, labelList &cellTypes) const
Find cells next to cells of type PATCH.
void markPatchCells (const fvMesh &mesh, const labelList &cellMap, labelList &patchCellTypes) const
according to additionalDocumentation/MEJ_oversetMesh.txt
void combineCellTypes (const label subZoneID, const fvMesh &subMesh, const labelList &subCellMap, const label donorZoneID, const labelListList &toOtherCells, const List< scalarList > &weights, const labelList &otherCells, const labelList &interpolatedOtherPatchTypes, labelListList &allStencil, scalarListList &allWeights, labelList &allCellTypes, labelList &allDonorID) const
void interpolatePatchTypes (const labelListList &addressing, const labelList &patchTypes, labelList &result) const
interpolate (= combine) patch types
void interpolatePatchTypes (const autoPtr< mapDistribute > &mapPtr, const labelListList &addressing, const labelList &patchTypes, labelList &result) const
interpolate (= combine) patch types
Protected Attributes
const dictionary dict_
Dictionary of motion control parameters.
scalar overlapTolerance_
Tolerance for volume overlap. Fraction of volume.
labelList cellTypes_
Per cell the cell type.
labelList interpolationCells_
Indices of interpolated cells.
autoPtr< mapDistribute > cellInterpolationMap_
Fetch interpolated cells.
labelListList cellStencil_
Interpolation stencil.
List< scalarList > cellInterpolationWeights_
Interpolation weights.
volScalarField cellInterpolationWeight_
Amount of interpolation.
Protected Attributes inherited from cellCellStencil
const fvMesh & mesh_
Reference to the mesh.
wordHashSet nonInterpolatedFields_
Set of fields that should not be interpolated.
Static Protected Attributes
static scalar defaultOverlapTolerance_ = 1e-6
Default overlap tolerance. Fraction of volume.
Static Protected Attributes inherited from cellCellStencil
static const Enum< cellType > cellTypeNames_
Mode type names.
Additional Inherited Members
Public Types inherited from cellCellStencil
enum patchCellType { OTHER = 0, PATCH = 1, OVERSET = 2 }
enum cellType { CALCULATED = 0, INTERPOLATED = 1, HOLE = 2 }
Static Public Member Functions inherited from cellCellStencil
static autoPtr< cellCellStencil > New (const fvMesh &, const dictionary &dict, const bool update=true)
New function which constructs and returns pointer to a.
static const labelIOList & zoneID (const fvMesh &)
Helper: get reference to registered zoneID. Loads volScalarField.
static void globalCellCells (const globalIndex &gi, const polyMesh &mesh, const boolList &isValidDonor, const labelList &selectedCells, labelListList &cellCells, pointListList &cellCellCentres)
Helper: create cell-cell addressing in global numbering.
Static Protected Member Functions inherited from cellCellStencil
static labelList count (const label size, const labelUList &lst)
Count ocurrences (in parallel)
template<class Type >
static tmp< volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &)
Helper: create volScalarField for postprocessing.
Detailed Description
Volume-weighted interpolation stencil.
Source files
cellVolumeWeightCellCellStencil.H
cellVolumeWeightCellCellStencil.C
cellVolumeWeightCellCellStencilTemplates.C
Definition at line 50 of file cellVolumeWeightCellCellStencil.H.
Constructor & Destructor Documentation
cellVolumeWeight (const fvMesh & mesh, const dictionary & dict, const bool doUpdate)
Construct from fvMesh.
Definition at line 660 of file cellVolumeWeightCellCellStencil.C.
References cellVolumeWeight::cellTypes_, d, Foam::expressions::patchExpr::debug, Foam::endl(), forAll, HashSet< Key, Hash >::insert(), cellCellStencil::mesh_, IOobject::NO_WRITE, cellCellStencil::nonInterpolatedFields_, Foam::Pout, IOobject::READ_IF_PRESENT, fvMesh::time(), Time::timeName(), cellVolumeWeight::update(), and cellCellStencil::zoneID().
~cellVolumeWeight () virtual
Destructor.
Definition at line 739 of file cellVolumeWeightCellCellStencil.C.
Member Function Documentation
void walkFront (const scalar layerRelax, labelList & allCellTypes, scalarField & allWeight) const protected
Definition at line 53 of file cellVolumeWeightCellCellStencil.C.
References fvMesh::boundary(), primitiveMesh::cells(), Foam::endl(), polyMesh::faceNeighbour(), polyMesh::faceOwner(), forAll, cellCellStencil::HOLE, i, Foam::Info, cellCellStencil::INTERPOLATED, primitiveMesh::isInternalFace(), cellCellStencil::mesh_, neiType, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::returnReduce(), List< T >::set(), Foam::start, syncTools::swapBoundaryCellList(), and syncTools::syncFaceList().
void findHoles (const globalIndex & globalCells, const fvMesh & mesh, const labelList & zoneID, const labelListList & stencil, labelList & cellTypes) const protected
Find cells next to cells of type PATCH.
Definition at line 197 of file cellVolumeWeightCellCellStencil.C.
void markPatchCells (const fvMesh & mesh, const labelList & cellMap, labelList & patchCellTypes) const protected
according to additionalDocumentation/MEJ_oversetMesh.txt
Definition at line 438 of file cellVolumeWeightCellCellStencil.C.
void combineCellTypes (const label subZoneID, const fvMesh & subMesh, const labelList & subCellMap, const label donorZoneID, const labelListList & toOtherCells, const List< scalarList > & weights, const labelList & otherCells, const labelList & interpolatedOtherPatchTypes, labelListList & allStencil, scalarListList & allWeights, labelList & allCellTypes, labelList & allDonorID) const protected
Option 1:
scalar currentVol = sum(allWeights[cellI]); if (overlapVol[subCellI] > currentVol)
Option 3:
Definition at line 546 of file cellVolumeWeightCellCellStencil.C.
void interpolatePatchTypes (const labelListList & addressing, const labelList & patchTypes, labelList & result) const protected
interpolate (= combine) patch types
Definition at line 478 of file cellVolumeWeightCellCellStencil.C.
void interpolatePatchTypes (const autoPtr< mapDistribute > & mapPtr, const labelListList & addressing, const labelList & patchTypes, labelList & result) const protected
interpolate (= combine) patch types
Definition at line 513 of file cellVolumeWeightCellCellStencil.C.
TypeName ("cellVolumeWeight")
Runtime type information.
scalar overlapTolerance () const inline
Access to volume overlap tolerance.
Definition at line 220 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::cellStencil_.
bool update () virtual
Update stencils. Return false if nothing changed.
Implements cellCellStencil.
Definition at line 745 of file cellVolumeWeightCellCellStencil.C.
References List< T >::clear(), dynamicOversetFvMesh::correctBoundaryConditions(), Foam::BitOps::count(), Foam::expressions::patchExpr::debug, Foam::decrIndent(), Foam::dimless, Foam::endl(), forAll, Foam::gMax(), i, meshToMesh::imCellVolumeWeight, Foam::incrIndent(), Foam::indent(), Foam::Info, Pstream::listCombineGather(), Pstream::listCombineScatter(), meshParts(), Foam::mkDir(), primitiveMesh::nCells(), nCellsPerZone(), Foam::nl, IOobject::NO_READ, IOobject::NO_WRITE, nZones, patchTypes(), meshToMesh::pmAABB, Foam::Pout, Foam::returnReduce(), s, PtrList< T >::set(), UPtrList< T >::size(), meshToMesh::srcMap(), meshToMesh::srcToTgtCellAddr(), meshToMesh::srcToTgtCellWght(), Foam::sum(), meshToMesh::tgtMap(), meshToMesh::tgtToSrcCellAddr(), meshToMesh::tgtToSrcCellWght(), globalIndex::toGlobal(), oversetFvPatchField< Type >::write(), Foam::Zero, and zoneID.
Referenced by cellVolumeWeight::cellVolumeWeight().
virtual const labelUList& cellTypes () const inline virtual
Return the cell type list.
Implements cellCellStencil.
Definition at line 233 of file cellVolumeWeightCellCellStencil.H.
References cellVolumeWeight::cellInterpolationWeight_.
virtual const labelUList& interpolationCells () const inline virtual
Indices of interpolated cells.
Implements cellCellStencil.
Definition at line 241 of file cellVolumeWeightCellCellStencil.H.
virtual const mapDistribute& cellInterpolationMap () const inline virtual
Return a communication schedule.
Implements cellCellStencil.
Definition at line 249 of file cellVolumeWeightCellCellStencil.H.
virtual const labelListList& cellStencil () const inline virtual
Per interpolated cell the neighbour cells (in terms of slots as.
constructed by above cellInterpolationMap) to interpolate
Implements cellCellStencil.
Definition at line 263 of file cellVolumeWeightCellCellStencil.H.
virtual const List<scalarList>& cellInterpolationWeights () const inline virtual
Weights for cellStencil.
Implements cellCellStencil.
Definition at line 271 of file cellVolumeWeightCellCellStencil.H.
virtual const scalarList& cellInterpolationWeight () const inline virtual
Per interpolated cell the interpolation factor. (0 = use.
calculated, 1 = use interpolated)
Implements cellCellStencil.
Definition at line 281 of file cellVolumeWeightCellCellStencil.H.
void stencilWeights (const point & sample, const pointList & donorCcs, scalarList & weights) const virtual
Calculate inverse distance weights for a single acceptor. Revert.
to inverse distance (so not consistent with volume overlap!)
Implements cellCellStencil.
Definition at line 1277 of file cellVolumeWeightCellCellStencil.C.
References d, forAll, i, Foam::mag(), List< T >::setSize(), UList< T >::size(), and Foam::sum().
Member Data Documentation
Foam::scalar defaultOverlapTolerance_ = 1e-6 static protected
Default overlap tolerance. Fraction of volume.
Definition at line 61 of file cellVolumeWeightCellCellStencil.H.
const dictionary dict_ protected
Dictionary of motion control parameters.
Definition at line 69 of file cellVolumeWeightCellCellStencil.H.
scalar overlapTolerance_ protected
Tolerance for volume overlap. Fraction of volume.
Definition at line 74 of file cellVolumeWeightCellCellStencil.H.
labelList cellTypes_ protected
Per cell the cell type.
Definition at line 79 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight().
labelList interpolationCells_ protected
Indices of interpolated cells.
Definition at line 84 of file cellVolumeWeightCellCellStencil.H.
autoPtr<mapDistribute> cellInterpolationMap_ protected
Fetch interpolated cells.
Definition at line 89 of file cellVolumeWeightCellCellStencil.H.
labelListList cellStencil_ protected
Interpolation stencil.
Definition at line 94 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::overlapTolerance().
List<scalarList> cellInterpolationWeights_ protected
Interpolation weights.
Definition at line 99 of file cellVolumeWeightCellCellStencil.H.
volScalarField cellInterpolationWeight_ protected
Amount of interpolation.
Definition at line 104 of file cellVolumeWeightCellCellStencil.H.
Referenced by cellVolumeWeight::cellTypes().
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/cellVolumeWeight/cellVolumeWeightCellCellStencil.H
src/overset/cellCellStencil/cellVolumeWeight/cellVolumeWeightCellCellStencil.C