OpenFOAM: CHFModel Class Reference
CHFModel Class Reference abstract
Base class for nucleation site density models.
Public Member Functions
TypeName ("CHFModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, CHFModel, dictionary,(const dictionary &dict),(dict))
Declare runtime construction.
CHFModel ()
Construct null.
virtual ~CHFModel ()
Destructor.
virtual tmp< scalarField > CHF (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
Calculate temperature.
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr< CHFModel > New (const dictionary &dict)
Select null constructed.
Detailed Description
Base class for nucleation site density models.
Source files
CHFModel.H
CHFModel.C
newCHFModel.C
Definition at line 53 of file CHFModel.H.
Constructor & Destructor Documentation
CHFModel ()
Construct null.
Definition at line 37 of file CHFModel.C.
~CHFModel () virtual
Destructor.
Definition at line 43 of file CHFModel.C.
Member Function Documentation
TypeName ("CHFModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , CHFModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime construction.
Foam::autoPtr< Foam::wallBoilingModels::CHFModel > New (const dictionary & dict) static
Select null constructed.
Definition at line 28 of file newCHFModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<scalarField> CHF (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Calculate temperature.
Implemented in Zuber.
void write (Ostream & os) const virtual
Reimplemented in Zuber.
Definition at line 49 of file CHFModel.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/CHFModels/CHFModel/CHFModel.H
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/CHFModels/CHFModel/CHFModel.C
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/CHFModels/CHFModel/newCHFModel.C