OpenFOAM: divScheme< Type > Class Template Reference
divScheme< Type > Class Template Reference abstract
Abstract base class for finite area calculus div schemes.
Public Member Functions
declareRunTimeSelectionTable (tmp, divScheme, Istream,(const faMesh &mesh, Istream &schemeData),(mesh, schemeData))
divScheme (const faMesh &mesh)
Construct from mesh.
divScheme (const faMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~divScheme ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< typename innerProduct
< vector, Type >::type,
faPatchField, areaMesh > > facDiv (const GeometricField< Type, faPatchField, areaMesh > &)=0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< divScheme< Type > > New (const faMesh &mesh, Istream &schemeData)
Return a pointer to a new divScheme created on freestore.
Protected Member Functions
divScheme (const divScheme &)=delete
No copy construct.
void operator= (const divScheme &)=delete
No copy assignment.
Protected Attributes
const faMesh & mesh_
tmp< edgeInterpolationScheme
< Type > > tinterpScheme_
Detailed Description
template<class Type>
class Foam::fa::divScheme< Type >
Abstract base class for finite area calculus div schemes.
Source files
faDivScheme.H
faDivScheme.C
faDivSchemes.C
Definition at line 63 of file faDivScheme.H.
Constructor & Destructor Documentation
divScheme (const divScheme< Type > &) protected delete
No copy construct.
divScheme (const faMesh & mesh) inline
Construct from mesh.
Definition at line 108 of file faDivScheme.H.
divScheme (const faMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 117 of file faDivScheme.H.
~divScheme () virtual
Destructor.
Definition at line 83 of file faDivScheme.C.
Member Function Documentation
void operator= (const divScheme< Type > &) protected delete
No copy assignment.
declareRunTimeSelectionTable (tmp , divScheme< Type > , Istream , (const faMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< divScheme< Type > > New (const faMesh & mesh, Istream & schemeData) static
Return a pointer to a new divScheme created on freestore.
Definition at line 40 of file faDivScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, mesh, and Foam::nl.
const faMesh& mesh () const inline
Return mesh reference.
Definition at line 147 of file faDivScheme.H.
virtual tmp< GeometricField <typename innerProduct<vector, Type>::type, faPatchField, areaMesh> > facDiv (const GeometricField< Type, faPatchField, areaMesh > &) pure virtual
Implemented in gaussDivScheme< Type >.
Member Data Documentation
const faMesh& mesh_ protected
Definition at line 72 of file faDivScheme.H.
tmp<edgeInterpolationScheme<Type> > tinterpScheme_ protected
Definition at line 73 of file faDivScheme.H.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/divSchemes/faDivScheme/faDivScheme.H
src/finiteArea/finiteArea/divSchemes/faDivScheme/faDivScheme.C