OpenFOAM: mappedPatchBase Class Reference
mappedPatchBase Class Reference
Determines a mapping between patch face centres and mesh cell or face centres and processors they're on.
Classes
class maxProcEqOp
class nearestEqOp
Public Types
enum sampleMode {
NEARESTCELL, NEARESTPATCHFACE, NEARESTPATCHFACEAMI, NEARESTPATCHPOINT,
NEARESTFACE, NEARESTONLYCELL
}
Mesh items to sample.
enum offsetMode { UNIFORM, NONUNIFORM, NORMAL }
How to project face centres.
typedef Tuple2< pointIndexHit,
Tuple2< scalar, label > > nearInfo
Helper class for finding nearest.
Public Member Functions
TypeName ("mappedPatchBase")
Runtime type information.
mappedPatchBase (const polyPatch &)
Construct from patch.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vectorField &offsets)
Construct with offsetMode=non-uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const vector &offset)
Construct from offsetMode=uniform.
mappedPatchBase (const polyPatch &pp, const word &sampleRegion, const sampleMode sampleMode, const word &samplePatch, const scalar distance)
Construct from offsetMode=normal and distance.
mappedPatchBase (const polyPatch &, const dictionary &)
Construct from dictionary.
mappedPatchBase (const polyPatch &, const sampleMode, const dictionary &)
Construct from dictionary and (collocated) sample mode.
mappedPatchBase (const polyPatch &, const mappedPatchBase &)
Construct as copy, resetting patch.
mappedPatchBase (const polyPatch &, const mappedPatchBase &, const labelUList &mapAddressing)
Construct as copy, resetting patch, map original data.
virtual ~mappedPatchBase ()
Destructor.
void clearOut ()
const sampleMode & mode () const
What to sample.
const word & sampleRegion () const
Region to sample.
const word & samplePatch () const
Patch (only if NEARESTPATCHFACE)
const word & coupleGroup () const
PatchGroup (only if NEARESTPATCHFACE)
label sampleSize () const
Return size of mapped mesh/patch/boundary.
const vector & offset () const
Offset vector (from patch faces to destination mesh objects)
const vectorField & offsets () const
Offset vector (from patch faces to destination mesh objects)
bool sameRegion () const
Cached sampleRegion != mesh.name()
const mapDistribute & map () const
Return reference to the parallel distribution map.
const
AMIPatchToPatchInterpolation & AMI (const bool forceUpdate=false) const
Return reference to the AMI interpolator.
const autoPtr
< Foam::searchableSurface > & surfPtr () const
Return a pointer to the AMI projection surface.
const polyMesh & sampleMesh () const
Get the region mesh.
const polyPatch & samplePolyPatch () const
Get the patch on the region.
tmp< pointField > samplePoints () const
Get the sample points.
template<class Type >
void distribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void distribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
template<class Type >
void reverseDistribute (List< Type > &lst) const
Wrapper around map/interpolate data distribution.
template<class Type , class CombineOp >
void reverseDistribute (List< Type > &lst, const CombineOp &cop) const
Wrapper around map/interpolate data distribution with operation.
virtual void write (Ostream &) const
Write as a dictionary.
Static Public Member Functions
static pointIndexHit facePoint (const polyMesh &, const label facei, const polyMesh::cellDecomposition)
Get a point on the face given a face decomposition method:
Static Public Attributes
static const Enum< sampleMode > sampleModeNames_
static const Enum< offsetMode > offsetModeNames_
Protected Member Functions
tmp< pointField > facePoints (const polyPatch &) const
Get the points from face-centre-decomposition face centres.
void collectSamples (const pointField &facePoints, pointField &, labelList &patchFaceProcs, labelList &patchFaces, pointField &patchFc) const
Collect single list of samples and originating processor+face.
void findSamples (const sampleMode mode, const pointField &, labelList &sampleProcs, labelList &sampleIndices, pointField &sampleLocations) const
Find cells/faces containing samples.
tmp< pointField > samplePoints (const pointField &) const
Get the sample points given the face points.
void calcMapping () const
Calculate mapping.
void calcAMI () const
Calculate AMI interpolator.
Static Protected Member Functions
static tmp< pointField > readListOrField (const word &keyword, const dictionary &dict, const label size)
Helper to read field or non-uniform list from dictionary.
Protected Attributes
const polyPatch & patch_
Patch to sample.
word sampleRegion_
Region to sample.
const sampleMode mode_
What to sample.
word samplePatch_
Patch (if in sampleMode NEARESTPATCH*)
const coupleGroupIdentifier coupleGroup_
PatchGroup (if in sampleMode NEARESTPATCH*)
offsetMode offsetMode_
How to obtain samples.
vector offset_
Offset vector (uniform)
vectorField offsets_
Offset vector (nonuniform)
scalar distance_
Offset distance (normal)
bool sameRegion_
Same region.
autoPtr< mapDistribute > mapPtr_
Communication schedule:
autoPtr
< AMIPatchToPatchInterpolation > AMIPtr_
Pointer to AMI interpolator.
const bool AMIReverse_
Flag to indicate that slave patch should be reversed for AMI.
autoPtr< searchableSurface > surfPtr_
Pointer to projection surface employed by AMI interpolator.
dictionary surfDict_
Dictionary storing projection surface description.
Detailed Description
Determines a mapping between patch face centres and mesh cell or face centres and processors they're on.
If constructed from dictionary:
    // Region to sample (default is region0)
    sampleRegion region0;
    // What to sample:
    // - nearestCell         : sample cell containing point
    // - nearestOnlyCell     : nearest sample cell (even if not containing
    //                         point)
    // - nearestPatchFace    : nearest face on selected patch
    // - nearestPatchFaceAMI : nearest face on selected patch
                               - patches need not conform
                               - uses AMI interpolation
    // - nearestFace         : nearest boundary face on any patch
    // - nearestPatchPoint   : nearest patch point (for coupled points
    //                         this might be any of the points so you have
    //                         to guarantee the point data is synchronised
    //                         beforehand)
    sampleMode nearestCell;
    // If sampleMode is nearestPatchFace : patch to find faces of
    samplePatch movingWall;
    // If sampleMode is nearestPatchFace : specify patchgroup to find
    // samplePatch and sampleRegion (if not provided)
    coupleGroup baffleGroup;
    // How to supply offset (w.r.t. my patch face centres):
    // - uniform : single offset vector
    // - nonuniform : per-face offset vector
    // - normal : using supplied distance and face normal
    offsetMode uniform;
    // According to offsetMode (see above) supply one of
    // offset, offsets or distance
    offset  (1 0 0);
Note: if offsetMode is normal it uses outwards pointing normals. So supply a negative distance if sampling inside the domain.
Note
Storage is not optimal. It temporary collects all (patch)face centres on all processors to keep the addressing calculation simple.
Source files
mappedPatchBase.H
mappedPatchBase.C
Definition at line 101 of file mappedPatchBase.H.
Member Typedef Documentation
typedef Tuple2<pointIndexHit, Tuple2<scalar, label> > nearInfo
Helper class for finding nearest.
Nearest:
point+local index
sqr(distance)
processor
Definition at line 144 of file mappedPatchBase.H.
Member Enumeration Documentation
enum sampleMode
Mesh items to sample.
Enumerator
NEARESTCELL
nearest cell containing sample
NEARESTPATCHFACE
nearest face on selected patch
NEARESTPATCHFACEAMI
nearest patch face + AMI interpolation
NEARESTPATCHPOINT
nearest point on selected patch
NEARESTFACE
nearest face
NEARESTONLYCELL
nearest cell (even if not containing cell)
Definition at line 111 of file mappedPatchBase.H.
enum offsetMode
How to project face centres.
Enumerator
UNIFORM
single offset vector
NONUNIFORM
per-face offset vector
NORMAL
use face normal + distance
Definition at line 124 of file mappedPatchBase.H.
Constructor & Destructor Documentation
mappedPatchBase (const polyPatch & pp)
Construct from patch.
Definition at line 912 of file mappedPatchBase.C.
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const vectorField & offsets)
Construct with offsetMode=non-uniform.
Definition at line 935 of file mappedPatchBase.C.
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const vector & offset)
Construct from offsetMode=uniform.
Definition at line 962 of file mappedPatchBase.C.
mappedPatchBase (const polyPatch & pp, const word & sampleRegion, const sampleMode sampleMode, const word & samplePatch, const scalar distance)
Construct from offsetMode=normal and distance.
Definition at line 989 of file mappedPatchBase.C.
mappedPatchBase (const polyPatch & pp, const dictionary & dict)
Construct from dictionary.
Definition at line 1016 of file mappedPatchBase.C.
References polyPatch::boundaryMesh(), mappedPatchBase::coupleGroup_, mappedPatchBase::distance_, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::found(), polyBoundaryMesh::mesh(), mappedPatchBase::mode_, IOobject::name(), mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, mappedPatchBase::NONUNIFORM, mappedPatchBase::NORMAL, mappedPatchBase::offset_, mappedPatchBase::offsetMode_, mappedPatchBase::offsetModeNames_, mappedPatchBase::offsets_, mappedPatchBase::patch_, dictionary::readEntry(), Enum< EnumType >::readIfPresent(), dictionary::readIfPresent(), mappedPatchBase::readListOrField(), mappedPatchBase::sameRegion_, mappedPatchBase::sampleRegion_, mappedPatchBase::UNIFORM, and coupleGroupIdentifier::valid().
mappedPatchBase (const polyPatch & pp, const sampleMode mode, const dictionary & dict)
Construct from dictionary and (collocated) sample mode.
(only for nearestPatchFace, nearestPatchFaceAMI, nearestPatchPoint) Assumes zero offset.
Definition at line 1092 of file mappedPatchBase.C.
References polyPatch::boundaryMesh(), mappedPatchBase::coupleGroup_, Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, polyBoundaryMesh::mesh(), IOobject::name(), mappedPatchBase::NEARESTPATCHFACE, mappedPatchBase::NEARESTPATCHFACEAMI, mappedPatchBase::patch_, mappedPatchBase::sameRegion_, mappedPatchBase::sampleModeNames_, mappedPatchBase::sampleRegion_, and coupleGroupIdentifier::valid().
mappedPatchBase (const polyPatch & pp, const mappedPatchBase & mpb)
Construct as copy, resetting patch.
Definition at line 1138 of file mappedPatchBase.C.
mappedPatchBase (const polyPatch & pp, const mappedPatchBase & mpb, const labelUList & mapAddressing)
Construct as copy, resetting patch, map original data.
Definition at line 1162 of file mappedPatchBase.C.
~mappedPatchBase () virtual
Destructor.
Definition at line 1193 of file mappedPatchBase.C.
Member Function Documentation
Foam::tmp< Foam::pointField > facePoints (const polyPatch & pp) const protected
Get the points from face-centre-decomposition face centres.
and project them onto the face-diagonal-decomposition triangles.
Definition at line 80 of file mappedPatchBase.C.
void collectSamples (const pointField & facePoints, pointField & samples, labelList & patchFaceProcs, labelList & patchFaces, pointField & patchFc) const protected
Collect single list of samples and originating processor+face.
Definition at line 108 of file mappedPatchBase.C.
void findSamples (const sampleMode mode, const pointField & samples, labelList & sampleProcs, labelList & sampleIndices, pointField & sampleLocations) const protected
Find cells/faces containing samples.
Note: face-diagonal decomposition
Note: face-diagonal decomposition
Note: face-diagonal decomposition
Definition at line 180 of file mappedPatchBase.C.
Foam::tmp< Foam::pointField > samplePoints (const pointField & fc) const protected
Get the sample points given the face points.
Definition at line 1242 of file mappedPatchBase.C.
References fld, Foam::mag(), n, and tmp< T >::ref().
void calcMapping () const protected
Calculate mapping.
Definition at line 515 of file mappedPatchBase.C.
References Foam::abort(), DynamicField< T, SizeMin >::append(), DynamicList< T, SizeMin >::append(), d, Foam::expressions::patchExpr::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::gAverage(), i, Foam::mag(), UPstream::master(), OSstream::name(), Foam::nl, Foam::Pout, Foam::reduce(), samples(), HashSet< Key, Hash >::set(), UList< T >::size(), HashSet< Key, Hash >::test(), Foam::type(), Foam::HashSetOps::used(), WarningInFunction, and Foam::meshTools::writeOBJ().
void calcAMI () const protected
Calculate AMI interpolator.
Definition at line 791 of file mappedPatchBase.C.
References Foam::expressions::patchExpr::debug, Foam::exit(), Foam::FatalError, FatalErrorInFunction, AMIInterpolation< SourcePatch, TargetPatch >::imFaceAreaWeight, PrimitivePatch< Face, FaceList, PointField, PointType >::localFaces(), PrimitivePatch< Face, FaceList, PointField, PointType >::localPoints(), faceAreaIntersect::tmMesh, and Foam::meshTools::writeOBJ().
Foam::tmp< Foam::pointField > readListOrField (const word & keyword, const dictionary & dict, const label size) static protected
Helper to read field or non-uniform list from dictionary.
Definition at line 852 of file mappedPatchBase.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, fld, IOWarningInFunction, token::isWord(), dictionary::lookup(), Istream::putBack(), tmp< T >::ref(), List< T >::setSize(), UList< T >::size(), IOstreamOption::version(), and token::wordToken().
Referenced by mappedPatchBase::mappedPatchBase().
TypeName ("mappedPatchBase")
Runtime type information.
void clearOut ()
Definition at line 1199 of file mappedPatchBase.C.
Referenced by mappedPolyPatch::initGeometry(), mappedWallPolyPatch::initGeometry(), mappedPolyPatch::initMovePoints(), mappedWallPolyPatch::initMovePoints(), mappedPolyPatch::initUpdateMesh(), mappedWallPolyPatch::initUpdateMesh(), mappedFieldFvPatchField< Type >::updateCoeffs(), mappedPolyPatch::write(), and mappedWallPolyPatch::write().
const Foam::mappedPatchBase::sampleMode & mode () const inline
What to sample.
Definition at line 22 of file mappedPatchBaseI.H.
const Foam::word & sampleRegion () const inline
Region to sample.
Definition at line 28 of file mappedPatchBaseI.H.
References mappedPatchBase::mode_.
const Foam::word & samplePatch () const inline
Patch (only if NEARESTPATCHFACE)
Definition at line 54 of file mappedPatchBaseI.H.
const Foam::word & coupleGroup () const inline
PatchGroup (only if NEARESTPATCHFACE)
Definition at line 80 of file mappedPatchBaseI.H.
Foam::label sampleSize () const inline
Return size of mapped mesh/patch/boundary.
Definition at line 86 of file mappedPatchBaseI.H.
const Foam::vector & offset () const inline
Offset vector (from patch faces to destination mesh objects)
Definition at line 121 of file mappedPatchBaseI.H.
const Foam::vectorField & offsets () const inline
Offset vector (from patch faces to destination mesh objects)
Definition at line 127 of file mappedPatchBaseI.H.
bool sameRegion () const inline
Cached sampleRegion != mesh.name()
Definition at line 133 of file mappedPatchBaseI.H.
const Foam::mapDistribute & map () const inline
Return reference to the parallel distribution map.
Definition at line 139 of file mappedPatchBaseI.H.
Referenced by mappedPatchBase::distribute().
const Foam::AMIPatchToPatchInterpolation & AMI (const bool forceUpdate = false) const inline
Return reference to the AMI interpolator.
Definition at line 151 of file mappedPatchBaseI.H.
Referenced by mappedPatchBase::distribute().
const Foam::autoPtr< Foam::searchableSurface > & surfPtr () const
Return a pointer to the AMI projection surface.
Definition at line 759 of file mappedPatchBase.C.
References polyMesh::boundaryMesh(), TimePaths::constant(), mesh, polyBoundaryMesh::mesh(), IOobject::MUST_READ, searchableSurface::New(), IOobject::NO_WRITE, and objectRegistry::time().
const Foam::polyMesh & sampleMesh () const
Get the region mesh.
Definition at line 1209 of file mappedPatchBase.C.
References polyMesh::boundaryMesh(), objectRegistry::lookupObject(), polyBoundaryMesh::mesh(), and objectRegistry::time().
const Foam::polyPatch & samplePolyPatch () const
Get the patch on the region.
Definition at line 1222 of file mappedPatchBase.C.
References polyMesh::boundaryMesh(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, polyBoundaryMesh::findPatchID(), and polyBoundaryMesh::names().
Foam::tmp< Foam::pointField > samplePoints () const
Get the sample points.
Definition at line 1276 of file mappedPatchBase.C.
Foam::pointIndexHit facePoint (const polyMesh & mesh, const label facei, const polyMesh::cellDecomposition decompMode) static
Get a point on the face given a face decomposition method:
face-centre-tet : face centre. Returns index of face. face-planes : face centre. Returns index of face. face-diagonal : intersection of ray from cellcentre to facecentre with any of the triangles. Returns index (0..size-2) of triangle.
Definition at line 1283 of file mappedPatchBase.C.
References Foam::abort(), polyMesh::CELL_TETS, primitiveMesh::cellCentres(), d, PointHit< Point >::distance(), f(), polyMesh::FACE_CENTRE_TRIS, polyMesh::FACE_DIAG_TRIS, polyMesh::FACE_PLANES, primitiveMesh::faceCentres(), polyMesh::faceOwner(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), intersection::HALF_RAY, PointHit< Point >::hit(), hitInfo(), PointHit< Point >::hitPoint(), i, triangle< Point, PointRef >::intersection(), p, polyMesh::points(), UList< T >::size(), and polyMesh::tetBasePtIs().
void distribute (List< Type > & lst) const
Wrapper around map/interpolate data distribution.
Definition at line 22 of file mappedPatchBaseTemplates.C.
References mappedPatchBase::AMI(), mapDistribute::distribute(), AMIInterpolation< SourcePatch, TargetPatch >::interpolateToSource(), mappedPatchBase::map(), mappedPatchBase::mode_, and mappedPatchBase::NEARESTPATCHFACEAMI.
void distribute (List< Type > & lst, const CombineOp & cop) const
Wrapper around map/interpolate data distribution with operation.
Definition at line 41 of file mappedPatchBaseTemplates.C.
void reverseDistribute (List< Type > & lst) const
Wrapper around map/interpolate data distribution.
Definition at line 75 of file mappedPatchBaseTemplates.C.
void reverseDistribute (List< Type > & lst, const CombineOp & cop) const
Wrapper around map/interpolate data distribution with operation.
Definition at line 95 of file mappedPatchBaseTemplates.C.
void write (Ostream & os) const virtual
Write as a dictionary.
Reimplemented in thermalBaffle1DFvPatchScalarField< solidType >, mappedWallPolyPatch, mappedFieldFvPatchField< Type >, mappedPolyPatch, mappedVariableThicknessWallPolyPatch, and semiPermeableBaffleMassFractionFvPatchScalarField.
Definition at line 1363 of file mappedPatchBase.C.
References Ostream::write(), Ostream::writeEntry(), and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
Member Data Documentation
const Foam::Enum< Foam::mappedPatchBase::sampleMode > sampleModeNames_ static
Definition at line 131 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
const Foam::Enum< Foam::mappedPatchBase::offsetMode > offsetModeNames_ static
Definition at line 133 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
const polyPatch& patch_ protected
Patch to sample.
Definition at line 196 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
word sampleRegion_ mutable protected
Region to sample.
Definition at line 201 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
const sampleMode mode_ protected
What to sample.
Definition at line 206 of file mappedPatchBase.H.
Referenced by mappedPatchBase::distribute(), mappedPatchBase::mappedPatchBase(), and mappedPatchBase::sampleRegion().
word samplePatch_ mutable protected
Patch (if in sampleMode NEARESTPATCH*)
Definition at line 211 of file mappedPatchBase.H.
const coupleGroupIdentifier coupleGroup_ protected
PatchGroup (if in sampleMode NEARESTPATCH*)
Definition at line 216 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
offsetMode offsetMode_ protected
How to obtain samples.
Definition at line 221 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
vector offset_ protected
Offset vector (uniform)
Definition at line 226 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
vectorField offsets_ protected
Offset vector (nonuniform)
Definition at line 231 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
scalar distance_ protected
Offset distance (normal)
Definition at line 236 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
bool sameRegion_ mutable protected
Same region.
Definition at line 241 of file mappedPatchBase.H.
Referenced by mappedPatchBase::mappedPatchBase().
autoPtr<mapDistribute> mapPtr_ mutable protected
Communication schedule:
Cells/faces to sample per processor
Patch faces to receive per processor
schedule
Definition at line 254 of file mappedPatchBase.H.
autoPtr<AMIPatchToPatchInterpolation> AMIPtr_ mutable protected
Pointer to AMI interpolator.
Definition at line 262 of file mappedPatchBase.H.
const bool AMIReverse_ protected
Flag to indicate that slave patch should be reversed for AMI.
Definition at line 267 of file mappedPatchBase.H.
autoPtr<searchableSurface> surfPtr_ mutable protected
Pointer to projection surface employed by AMI interpolator.
Definition at line 272 of file mappedPatchBase.H.
dictionary surfDict_ protected
Dictionary storing projection surface description.
Definition at line 277 of file mappedPatchBase.H.
The documentation for this class was generated from the following files:
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBase.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBase.C
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBaseI.H
src/meshTools/mappedPatches/mappedPolyPatch/mappedPatchBaseTemplates.C