OpenFOAM: fvPatch Class Reference
fvPatch Class Reference
A finiteVolume patch using a polyPatch and a fvBoundaryMesh.
Public Types
typedef fvBoundaryMesh BoundaryMesh
Public Member Functions
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
virtual bool coupled () const
Return true if this patch is coupled.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
virtual const labelUList & faceCells () const
Return faceCells.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
virtual tmp< vectorField > delta () const
Return cell-centre to face-centre vector except for coupled patches for which the cell-centre to coupled-cell-centre vector is returned.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coefficient except for coupled patches for which the cell-centre to coupled-cell-centre distance coefficient is returned.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::Patch & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const Type *=nullptr) const
Lookup and return the patchField of the named field from the local objectRegistry.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Static Public Member Functions
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Protected Member Functions
virtual void makeWeights (scalarField &) const
Make patch weighting factors.
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Friends
class fvBoundaryMesh
class surfaceInterpolation
Detailed Description
A finiteVolume patch using a polyPatch and a fvBoundaryMesh.
Source files
fvPatch.H
fvPatch.C
fvPatchNew.C
Definition at line 59 of file fvPatch.H.
Member Typedef Documentation
typedef fvBoundaryMesh BoundaryMesh
Definition at line 109 of file fvPatch.H.
Constructor & Destructor Documentation
fvPatch (const polyPatch & p, const fvBoundaryMesh & bm)
Construct from polyPatch and fvBoundaryMesh.
Definition at line 41 of file fvPatch.C.
~fvPatch () virtual
Destructor.
Definition at line 50 of file fvPatch.C.
Member Function Documentation
void makeWeights (scalarField & w) const protected virtual
Make patch weighting factors.
Reimplemented in cyclicACMIFvPatch, coupledFvPatch, cyclicFvPatch, cyclicAMIFvPatch, and processorFvPatch.
Definition at line 139 of file fvPatch.C.
References nf().
Referenced by cyclicAMIFvPatch::delta().
void initMovePoints () protected virtual
Initialise the patches for moving points.
Definition at line 145 of file fvPatch.C.
void movePoints () protected virtual
Correct patches after moving points.
Definition at line 149 of file fvPatch.C.
TypeName (polyPatch:: typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr , fvPatch , polyPatch , (const polyPatch &patch, const fvBoundaryMesh &bm) , (patch, bm))
Foam::autoPtr< Foam::fvPatch > New (const polyPatch & patch, const fvBoundaryMesh & bm) static
Return a pointer to a new patch created on freestore from polyPatch.
Definition at line 28 of file fvPatchNew.C.
References DebugInFunction, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, and fvPatch::patch().
Referenced by fvMeshTools::addPatch().
const polyPatch& patch () const inline
Return the polyPatch.
Definition at line 165 of file fvPatch.H.
Referenced by Foam::evaluateConstraintTypes(), fvPatch::New(), parseDriver::size(), and thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField().
virtual const word& name () const inline virtual
Return name.
Definition at line 173 of file fvPatch.H.
Referenced by genericFvPatchField< Type >::genericFvPatchField(), genericFvsPatchField< Type >::genericFvsPatchField(), and fvPatch::lookupPatchField().
virtual label start () const inline virtual
Return start label of this patch in the polyMesh face list.
Definition at line 181 of file fvPatch.H.
References patchIdentifier::index().
Referenced by pointLinear< Type >::correction(), and Foam::oversetAdjustPhi().
virtual label size () const inline virtual
Return size.
Reimplemented in emptyFvPatch.
Definition at line 189 of file fvPatch.H.
Referenced by boundaryAdjointContribution::adjointTMVariable2Source(), alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField(), cyclicAMIFvPatch::makeWeights(), fvPatch::patchInternalField(), semiPermeableBaffleVelocityFvPatchVectorField::semiPermeableBaffleVelocityFvPatchVectorField(), boundaryAdjointContributionIncompressible::sumContributions(), thermalBaffle1DFvPatchScalarField< solidType >::thermalBaffle1DFvPatchScalarField(), boundaryAdjointContribution::TMVariable1(), boundaryAdjointContribution::TMVariable1Diffusion(), boundaryAdjointContribution::TMVariable2(), and boundaryAdjointContribution::TMVariable2Diffusion().
virtual bool coupled () const inline virtual
Return true if this patch is coupled.
Reimplemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, and coupledFvPatch.
Definition at line 197 of file fvPatch.H.
bool constraintType (const word & pt) static
Return true if the given type is a constraint type.
Definition at line 56 of file fvPatch.C.
Referenced by inverseDistance::findHoles().
Foam::wordList constraintTypes () static
Return a list of all the constraint patch types.
Definition at line 62 of file fvPatch.C.
References UList< T >::found().
label index () const inline
Return the index of this patch in the fvBoundaryMesh.
Definition at line 215 of file fvPatch.H.
Referenced by boundaryAdjointContributionIncompressible::pab(), boundaryAdjointContributionIncompressible::pb(), boundaryAdjointContributionIncompressible::phiab(), boundaryAdjointContributionIncompressible::phib(), boundaryAdjointContributionIncompressible::primalSolverName(), boundaryAdjointContributionIncompressible::sumContributions(), and boundaryAdjointContributionIncompressible::turbulentDiffusivity().
const fvBoundaryMesh& boundaryMesh () const inline
Return boundaryMesh reference.
Definition at line 223 of file fvPatch.H.
Referenced by cyclicFvPatch::forwardT(), fvPatch::lookupPatchField(), cyclicFvPatch::owner(), cyclicAMIFvPatch::owner(), cyclicACMIFvPatch::owner(), and cyclicACMIFvPatch::parallel().
const List<T>::subList patchSlice (const List< T > & l) const inline
Slice list to patch.
Definition at line 232 of file fvPatch.H.
const Foam::labelUList & faceCells () const virtual
Return faceCells.
Reimplemented in coupledFvPatch, oversetFvPatch, and emptyFvPatch.
Definition at line 82 of file fvPatch.C.
Referenced by pointLinear< Type >::correction(), coupledFvPatch::coupled(), inverseDistance::findHoles(), Foam::oversetAdjustPhi(), and fvPatch::patchInternalField().
const Foam::vectorField & Cf () const
Return face centres.
Definition at line 88 of file fvPatch.C.
Foam::tmp< Foam::vectorField > Cn () const
Return neighbour cell centres.
Definition at line 94 of file fvPatch.C.
References boundaryMesh::mesh().
const Foam::vectorField & Sf () const
Return face area vectors.
Definition at line 119 of file fvPatch.C.
const Foam::scalarField & magSf () const
Return face area magnitudes.
Definition at line 125 of file fvPatch.C.
References boundaryMesh::mesh().
Referenced by parseDriver::field_faceCentre(), and parseDriver::pointSize().
Foam::tmp< Foam::vectorField > nf () const
Return face normals.
Definition at line 113 of file fvPatch.C.
Foam::tmp< Foam::vectorField > delta () const virtual
Return cell-centre to face-centre vector except for coupled patches for which the cell-centre to coupled-cell-centre vector is returned.
Reimplemented in cyclicACMIFvPatch, cyclicAMIFvPatch, processorFvPatch, cyclicFvPatch, and coupledFvPatch.
Definition at line 131 of file fvPatch.C.
References boundaryMesh::mesh().
const Foam::scalarField & weights () const
Return patch weighting factors.
Definition at line 159 of file fvPatch.C.
References boundaryMesh::mesh().
const Foam::scalarField & deltaCoeffs () const
Return the face - cell distance coefficient except for coupled patches for which the cell-centre to coupled-cell-centre distance coefficient is returned.
Definition at line 153 of file fvPatch.C.
tmp<Field<Type> > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
void patchInternalField (const UList< Type > & f, Field< Type > & pif) const
Return given internal field next to patch as patch field.
Definition at line 47 of file fvPatchTemplates.C.
const GeometricField::Patch & patchField (const GeometricField & gf) const
Return the corresponding patchField of the named field.
Definition at line 65 of file fvPatchTemplates.C.
const GeometricField::Patch & lookupPatchField (const word & name, const GeometricField * = nullptr, const Type * = nullptr) const
Lookup and return the patchField of the named field from the local objectRegistry.
N.B. The dummy pointer arguments are used if this function is instantiated within a templated function to avoid a bug in gcc. See inletOutletFvPatchField.C and outletInletFvPatchField.C
Definition at line 27 of file fvPatchFvMeshTemplates.C.
References fvPatch::boundaryMesh(), fvBoundaryMesh::mesh(), and fvPatch::name().
Foam::tmp<Foam::Field<Type> > patchInternalField (const UList< Type > & f) const
Definition at line 27 of file fvPatchTemplates.C.
References fvPatch::faceCells(), forAll, tmp< T >::ref(), and fvPatch::size().
Friends And Related Function Documentation
friend class fvBoundaryMesh friend
Definition at line 111 of file fvPatch.H.
friend class surfaceInterpolation friend
Definition at line 112 of file fvPatch.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatch.H
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatch.C
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatchFvMeshTemplates.C
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatchNew.C
src/finiteVolume/fvMesh/fvPatches/fvPatch/fvPatchTemplates.C