OpenFOAM: complex Class Reference
complex Class Reference
A complex number, similar to the C++ complex type.
Public Member Functions
constexpr complex () noexcept
Construct null as zero-initialized.
complex (const complex &)=default
Default copy constructor.
constexpr complex (const Foam::zero) noexcept
Construct zero-initialized from zero class.
constexpr complex (const scalar r) noexcept
Construct from real component.
constexpr complex (const scalar r, const scalar i) noexcept
Construct from real and imaginary parts.
complex (const std::complex< float > &c)
Construct from std::complex.
complex (const std::complex< double > &c)
Construct from std::complex.
complex (Istream &is)
Construct from Istream.
constexpr scalar real () const
Real part of complex number - STL naming.
constexpr scalar imag () const
Imaginary part of complex number - STL naming.
void real (scalar val)
Set real part of complex number - STL naming.
void imag (scalar val)
Set imaginary part of complex number - STL naming.
scalar Re () const
Real part of complex number.
scalar Im () const
Imaginary part of complex number.
scalar & Re ()
Real part of complex number.
scalar & Im ()
Imaginary part of complex number.
complex conjugate () const
Complex conjugate.
operator std::complex< scalar > () const
Conversion to std::complex.
void operator= (const complex &c)
Copy assignment.
void operator= (const Foam::zero)
Assign zero.
void operator= (const scalar s)
Assign scalar (imag = zero)
void operator+= (const complex &c)
void operator+= (const scalar s)
void operator-= (const complex &c)
void operator-= (const scalar s)
void operator*= (const complex &c)
void operator*= (const scalar s)
void operator/= (const complex &c)
void operator/= (const scalar s)
bool operator== (const complex &c) const
bool operator!= (const complex &c) const
Friends
scalar magSqr (const complex &c)
scalar mag (const complex &c)
complex sqr (const complex &c)
complex sign (const complex &c)
sgn() https://en.wikipedia.org/wiki/Sign_function#Complex_signum
scalar csign (const complex &c)
csgn() https://en.wikipedia.org/wiki/Sign_function#Complex_signum
const complex & min (const complex &c1, const complex &c2)
const complex & max (const complex &c1, const complex &c2)
complex limit (const complex &c1, const complex &c2)
const complex & sum (const complex &c)
complex operator- (const complex &c)
complex operator+ (const complex &c1, const complex &c2)
complex operator+ (const complex &c, const scalar s)
complex operator+ (const scalar s, const complex &c)
complex operator- (const complex &c1, const complex &c2)
complex operator- (const complex &c, const scalar s)
complex operator- (const scalar s, const complex &c)
complex operator* (const complex &c1, const complex &c2)
complex operator* (const complex &c, const scalar s)
complex operator* (const scalar s, const complex &c)
complex operator/ (const complex &c1, const complex &c2)
complex operator/ (const complex &c, const scalar s)
complex operator/ (const scalar s, const complex &c)
Detailed Description
A complex number, similar to the C++ complex type.
Source files
complex.H
complexI.H
complex.C
Definition at line 78 of file complex.H.
Constructor & Destructor Documentation
constexpr complex () inline noexcept
Construct null as zero-initialized.
Definition at line 24 of file complexI.H.
complex (const complex &) default
Default copy constructor.
constexpr complex (const Foam::zero) inline noexcept
Construct zero-initialized from zero class.
Definition at line 31 of file complexI.H.
constexpr complex (const scalar r) inline explicit noexcept
Construct from real component.
Definition at line 38 of file complexI.H.
constexpr complex (const scalar r, const scalar i) inline noexcept
Construct from real and imaginary parts.
Definition at line 45 of file complexI.H.
complex (const std::complex< float > & c) inline
Construct from std::complex.
Definition at line 52 of file complexI.H.
complex (const std::complex< double > & c) inline
Construct from std::complex.
Definition at line 59 of file complexI.H.
complex (Istream & is) explicit
Construct from Istream.
Definition at line 61 of file complex.C.
Member Function Documentation
constexpr scalar real () const inline
Real part of complex number - STL naming.
Definition at line 140 of file complex.H.
constexpr scalar imag () const inline
Imaginary part of complex number - STL naming.
Definition at line 148 of file complex.H.
void real (scalar val) inline
Set real part of complex number - STL naming.
Definition at line 68 of file complexI.H.
void imag (scalar val) inline
Set imaginary part of complex number - STL naming.
Definition at line 74 of file complexI.H.
References Foam::constant::atomic::re, and Foam::val.
Foam::scalar Re () const inline
Real part of complex number.
Definition at line 80 of file complexI.H.
References Foam::val.
Referenced by Foam::min().
Foam::scalar Im () const inline
Imaginary part of complex number.
Definition at line 86 of file complexI.H.
References Foam::constant::atomic::re.
Referenced by Foam::min().
Foam::scalar & Re () inline
Real part of complex number.
Definition at line 92 of file complexI.H.
Foam::scalar & Im () inline
Imaginary part of complex number.
Definition at line 98 of file complexI.H.
References Foam::constant::atomic::re.
Foam::complex conjugate () const inline
Complex conjugate.
Definition at line 104 of file complexI.H.
operator std::complex< scalar > () const inline
Conversion to std::complex.
Definition at line 203 of file complex.H.
void operator= (const complex & c) inline
Copy assignment.
Definition at line 112 of file complexI.H.
References Foam::roots::complex, and Foam::constant::atomic::re.
void operator= (const Foam::zero) inline
Assign zero.
Definition at line 119 of file complexI.H.
References Foam::constant::atomic::re.
void operator= (const scalar s) inline
Assign scalar (imag = zero)
Definition at line 126 of file complexI.H.
References Foam::constant::atomic::re.
void operator+= (const complex & c) inline
Definition at line 133 of file complexI.H.
References Foam::constant::atomic::re, and s.
void operator+= (const scalar s) inline
Definition at line 140 of file complexI.H.
References Foam::constant::atomic::re.
void operator-= (const complex & c) inline
Definition at line 146 of file complexI.H.
References Foam::constant::atomic::re, and s.
void operator-= (const scalar s) inline
Definition at line 153 of file complexI.H.
References Foam::constant::atomic::re.
void operator*= (const complex & c) inline
Definition at line 159 of file complexI.H.
References Foam::constant::atomic::re, and s.
void operator*= (const scalar s) inline
Definition at line 165 of file complexI.H.
References c().
void operator/= (const complex & c) inline
Definition at line 172 of file complexI.H.
References Foam::constant::atomic::re, and s.
void operator/= (const scalar s) inline
Definition at line 178 of file complexI.H.
References c().
bool operator== (const complex & c) const inline
Definition at line 185 of file complexI.H.
References Foam::constant::atomic::re, and s.
bool operator!= (const complex & c) const inline
Definition at line 191 of file complexI.H.
References Foam::equal(), and Foam::constant::atomic::re.
Friends And Related Function Documentation
scalar magSqr (const complex & c) friend
scalar mag (const complex & c) friend
complex sqr (const complex & c) friend
complex sign (const complex & c) friend
sgn() https://en.wikipedia.org/wiki/Sign_function#Complex_signum
Definition at line 228 of file complexI.H.
scalar csign (const complex & c) friend
csgn() https://en.wikipedia.org/wiki/Sign_function#Complex_signum
Definition at line 235 of file complexI.H.
const complex& min (const complex & c1, const complex & c2) friend
const complex& max (const complex & c1, const complex & c2) friend
complex limit (const complex & c1, const complex & c2) friend
const complex& sum (const complex & c) friend
complex operator- (const complex & c) friend
complex operator+ (const complex & c1, const complex & c2) friend
complex operator+ (const complex & c, const scalar s) friend
complex operator+ (const scalar s, const complex & c) friend
complex operator- (const complex & c1, const complex & c2) friend
complex operator- (const complex & c, const scalar s) friend
complex operator- (const scalar s, const complex & c) friend
complex operator* (const complex & c1, const complex & c2) friend
complex operator* (const complex & c, const scalar s) friend
complex operator* (const scalar s, const complex & c) friend
complex operator/ (const complex & c1, const complex & c2) friend
complex operator/ (const complex & c, const scalar s) friend
complex operator/ (const scalar s, const complex & c) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/complex/complex.H
src/OpenFOAM/primitives/complex/complex.C
src/OpenFOAM/primitives/complex/complexI.H