OpenFOAM: STLCore Class Reference
STLCore Class Reference
Core routines used when reading/writing STL files.
Public Types
enum STLFormat { ASCII, BINARY, UNKNOWN }
Enumeration for the format of data in the stream.
Protected Member Functions
STLCore ()=default
Construct null.
Static Protected Member Functions
static bool isBinaryName (const fileName &filename, const STLFormat format)
Detect 'stlb' extension as binary when format = UNKNOWN.
static int detectBinaryHeader (const fileName &filename)
Check contents to detect if the file is a binary STL.
static autoPtr< std::istream > readBinaryHeader (const fileName &filename, label &nTrisEstimated)
Read STL binary file header.
static void writeBinaryHeader (ostream &os, uint32_t nTris)
Write STL binary file and number of triangles to stream.
Detailed Description
Core routines used when reading/writing STL files.
Source files
STLCore.H
STLCore.C
Definition at line 50 of file STLCore.H.
Member Enumeration Documentation
enum STLFormat
Enumeration for the format of data in the stream.
Enumerator
ASCII
ASCII.
BINARY
BINARY.
UNKNOWN
Detect based on (input) content or (output) extension.
Definition at line 59 of file STLCore.H.
Constructor & Destructor Documentation
STLCore () protected default
Construct null.
Member Function Documentation
bool isBinaryName (const fileName & filename, const STLFormat format) static protected
Detect 'stlb' extension as binary when format = UNKNOWN.
Otherwise test if format == BINARY.
Definition at line 61 of file STLCore.C.
int detectBinaryHeader (const fileName & filename) static protected
Check contents to detect if the file is a binary STL.
Return the estimated number of triangles or 0 on error.
Definition at line 82 of file STLCore.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, Foam::fileSize(), Foam::isFile(), and autoPtr< T >::reset().
Foam::autoPtr< std::istream > readBinaryHeader (const fileName & filename, label & nTrisEstimated) static protected
Read STL binary file header.
Return the opened file stream and estimated number of triangles. The stream is invalid and number of triangles is 0 on error.
Definition at line 154 of file STLCore.C.
void writeBinaryHeader (ostream & os, uint32_t nTris) static protected
Write STL binary file and number of triangles to stream.
Definition at line 244 of file STLCore.C.
The documentation for this class was generated from the following files:
src/fileFormats/stl/STLCore.H
src/fileFormats/stl/STLCore.C