OpenFOAM: foamPvCore::arrayRange Class Reference
foamPvCore::arrayRange Class Reference
Bookkeeping for GUI checklists and multi-block organization.
Public Member Functions
arrayRange (const char *name, int blockNo=0)
Construct with given name for the specified block.
int block () const
Return the block holding these datasets.
int block (int blockNo)
Assign block number, return previous value.
const char * name () const
Return the name.
void reset (label startAt=0)
Reset the size to zero and optionally assign a new start.
void operator+= (label n)
Increment the size.
template<class T >
bool intersects (const Map< T > &map) const
True if the labelRange intersects any key in the Map.
template<class T >
List< label > intersection (const Map< T > &map) const
The intersection ids with keys in the Map.
Public Member Functions inherited from labelRange
constexpr labelRange () noexcept
An empty range with zero for start/size.
labelRange (const label start, const label size) noexcept
Construct a range from start/size, enforcing non-negative size.
labelRange (const label start, const label size, const bool adjustStart) noexcept
Construct a range from start/size, enforcing non-negative size.
labelRange (const MinMax< label > &range) noexcept
Construct from a min/max range, enforcing non-negative size. Does not adjust the start.
labelRange (Istream &is)
Construct from Istream.
void setStart (const label i) noexcept
Change the start position.
void resize (const label n) noexcept
Change the size, enforcing non-negative size.
void setSize (const label n) noexcept
Change the size - alias for resize()
void clear () noexcept
Reset to zero start and zero size.
bool empty () const noexcept
Is the range empty?
bool valid () const noexcept
Is the range non-empty?
label start () const noexcept
The (inclusive) lower value of the range.
label size () const noexcept
The effective size of the range.
label before () const noexcept
The value before the start of the range.
label first () const noexcept
The (inclusive) lower value of the range - same as start()
label min () const noexcept
The (inclusive) lower value of the range - same as start(), first()
label last () const noexcept
The (inclusive) upper value of the range - same as max()
label max () const noexcept
The (inclusive) upper value of the range - same as last()
label after () const noexcept
The value after the last element in the range.
void adjust () noexcept
Adjust the start to avoid negative indices.
bool reset (const label start, const label size) noexcept
Reset start and size, enforcing non-negative size.
bool reset (const label start, const label size, const bool adjustStart) noexcept
Reset start and size, enforcing non-negative size.
bool found (const label value) const noexcept
Return true if the (global) value is located within the range.
List< label > labels () const
Return the range as a list of labels.
bool overlaps (const labelRange &range, bool touches=false) const
Return true if the ranges overlap.
labelRange join (const labelRange &range) const
Return a joined range, squashing any gaps in between.
labelRange subset (const labelRange &range) const
Calculate the intersection of the range with another.
labelRange subset (const label start, const label size) const
Calculate the intersection with the given start/size range.
labelRange subset0 (const label size) const
Calculate the intersection with the given 0/size range.
label operator[] (const label i) const noexcept
Return element in the range, without bounds checking.
bool operator() (const label value) const noexcept
Return true if the global value is located within the range.
label operator++ () noexcept
Increase the size by 1.
label operator++ (int) noexcept
label operator+= (const label n) noexcept
Increase the size by n.
label operator-- () noexcept
Decrease the size by 1, but never below 0.
label operator-- (int) noexcept
label operator-= (const label n) noexcept
Decrease the size by n, but never below 0.
const_iterator begin () const
A const_iterator set to the beginning of the range.
const_iterator cbegin () const
A const_iterator set to the beginning of the range.
const const_iterator cend () const
A const_iterator set to 1 beyond the end of the range.
const const_iterator end () const
A const_iterator set to 1 beyond the end of the range.
const_iterator at (const label i) const
Return const_iterator to a position within the range, with bounds checking.
Additional Inherited Members
Public Types inherited from labelRange
typedef label value_type
Type of values the range contains.
typedef label size_type
The type that can represent the size of the range.
Static Public Member Functions inherited from labelRange
static labelRange identity (const label len, const label start=0) noexcept
An identity range corresponding to (map[i] == i), or with an optional start index, so that (map[i] == i+start)
Static Public Attributes inherited from labelRange
static int debug
Debugging.
static const labelRange null
An empty range with start=0, size=0.
Detailed Description
Bookkeeping for GUI checklists and multi-block organization.
Works like a SubList selection.
Definition at line 76 of file foamPvCore.H.
Constructor & Destructor Documentation
arrayRange (const char * name, int blockNo = 0) inline
Construct with given name for the specified block.
Definition at line 88 of file foamPvCore.H.
Member Function Documentation
int block () const inline
Return the block holding these datasets.
Definition at line 98 of file foamPvCore.H.
int block (int blockNo) inline
Assign block number, return previous value.
Definition at line 106 of file foamPvCore.H.
const char* name () const inline
Return the name.
Definition at line 116 of file foamPvCore.H.
References labelRange::clear(), and labelRange::setStart().
void reset (label startAt = 0) inline
Reset the size to zero and optionally assign a new start.
Definition at line 129 of file foamPvCore.H.
References HashTable< T, label, Hash< label > >::found().
void operator+= (label n) inline
Increment the size.
Definition at line 138 of file foamPvCore.H.
bool intersects (const Map< T > & map) const inline
True if the labelRange intersects any key in the Map.
Definition at line 147 of file foamPvCore.H.
References HashTable< T, label, Hash< label > >::found(), Foam::min(), List< T >::setSize(), UList< T >::size(), labelRange::size(), and HashTable< T, label, Hash< label > >::size().
List<label> intersection (const Map< T > & map) const inline
The intersection ids with keys in the Map.
Definition at line 164 of file foamPvCore.H.
The documentation for this class was generated from the following file:
applications/utilities/postProcessing/graphics/PVReaders/common/foamPvCore.H