OpenFOAM: euler Class Reference
euler Class Reference
A coordinateRotation defined in the z-x-z (intrinsic) Euler convention.
Public Types
using eulerOrder = quaternion::eulerOrder
Euler-angle rotation order.
Public Member Functions
TypeNameNoDebug ("euler")
Runtime type information.
euler ()
Construct null - an identity transform.
euler (const euler &crot)
Copy construct.
euler (const vector &angles, bool degrees)
Construct from Euler intrinsic rotation angles (z-x-z)
euler (scalar angle1, scalar angle2, scalar angle3, bool degrees)
Construct from Euler intrinsic rotation angles (z-x-z)
euler (const dictionary &dict)
Construct from dictionary.
autoPtr< coordinateRotation > clone () const
Return clone.
virtual ~euler ()=default
Destructor.
virtual void clear ()
Reset specification.
virtual tensor R () const
The rotation tensor calculated for the specified Euler angles.
virtual void write (Ostream &os) const
Write information.
virtual void writeEntry (const word &keyword, Ostream &os) const
Write dictionary entry.
Public Member Functions inherited from coordinateRotation
TypeNameNoDebug ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()=default
Destructor.
Static Public Member Functions
static tensor rotation (const vector &angles, bool degrees=false)
The rotation tensor calculated for the intrinsic Euler angles in z-x-z order.
static tensor rotation (const eulerOrder order, const vector &angles, bool degrees=false)
The rotation tensor calculated for given angles and order.
Static Public Member Functions inherited from coordinateRotation
static autoPtr
< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Additional Inherited Members
Static Protected Member Functions inherited from coordinateRotation
static vector findOrthogonal (const vector &axis)
Determine best-guess for an orthogonal axis.
Detailed Description
A coordinateRotation defined in the z-x-z (intrinsic) Euler convention.
The 3 rotations are defined in the Euler intrinsic convention (around Z, around X' and around Z''). The order of the parameter arguments matches this rotation order.
For reference and illustration, see https://en.wikipedia.org/wiki/Euler_angles
coordinateRotation
{
    type    euler;
    angles  (0 0 180);
}
Dictionary entries
Property Description Required Default
type Type name: euler (or EulerRotation) yes
angles The z-x-z rotation angles yes
degrees Angles are in degrees no true
Source files
EulerCoordinateRotation.H
EulerCoordinateRotation.C
Definition at line 93 of file EulerCoordinateRotation.H.
Member Typedef Documentation
using eulerOrder = quaternion::eulerOrder
Euler-angle rotation order.
Definition at line 104 of file EulerCoordinateRotation.H.
Constructor & Destructor Documentation
euler ()
Construct null - an identity transform.
Definition at line 243 of file EulerCoordinateRotation.C.
euler (const euler & crot)
Copy construct.
Definition at line 252 of file EulerCoordinateRotation.C.
euler (const vector & angles, bool degrees)
Construct from Euler intrinsic rotation angles (z-x-z)
Definition at line 262 of file EulerCoordinateRotation.C.
euler (scalar angle1, scalar angle2, scalar angle3, bool degrees)
Construct from Euler intrinsic rotation angles (z-x-z)
Definition at line 275 of file EulerCoordinateRotation.C.
euler (const dictionary & dict) explicit
Construct from dictionary.
Definition at line 289 of file EulerCoordinateRotation.C.
virtual ~euler () virtual default
Destructor.
Member Function Documentation
TypeNameNoDebug ("euler")
Runtime type information.
autoPtr<coordinateRotation> clone () const inline virtual
Return clone.
Implements coordinateRotation.
Definition at line 165 of file EulerCoordinateRotation.H.
Foam::tensor rotation (const vector & angles, bool degrees = false) static
The rotation tensor calculated for the intrinsic Euler angles in z-x-z order.
Definition at line 232 of file EulerCoordinateRotation.C.
Referenced by euler::write().
Foam::tensor rotation (const eulerOrder order, const vector & angles, bool degrees = false) static
The rotation tensor calculated for given angles and order.
Definition at line 58 of file EulerCoordinateRotation.C.
void clear () virtual
Reset specification.
Implements coordinateRotation.
Definition at line 308 of file EulerCoordinateRotation.C.
Foam::tensor R () const virtual
The rotation tensor calculated for the specified Euler angles.
Implements coordinateRotation.
Definition at line 315 of file EulerCoordinateRotation.C.
References Foam::Zero.
void write (Ostream & os) const virtual
Write information.
Implements coordinateRotation.
Definition at line 321 of file EulerCoordinateRotation.C.
References degrees_(), and euler::rotation().
void writeEntry (const word & keyword, Ostream & os) const virtual
Write dictionary entry.
Implements coordinateRotation.
Definition at line 328 of file EulerCoordinateRotation.C.
References degrees_().
The documentation for this class was generated from the following files:
src/meshTools/coordinate/rotation/EulerCoordinateRotation.H
src/meshTools/coordinate/rotation/EulerCoordinateRotation.C