OpenFOAM: interfaceProperties Class Reference
interfaceProperties Class Reference
Contains the interface properties.
Public Member Functions
interfaceProperties (const volScalarField &alpha1, const volVectorField &U, const IOdictionary &)
Construct from volume fraction field gamma and IOdictionary.
scalar cAlpha () const
const dimensionedScalar & deltaN () const
const surfaceScalarField & nHatf () const
tmp< volScalarField > sigmaK () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
Indicator of the proximity of the interface.
void correct ()
bool read ()
Read transportProperties dictionary.
Detailed Description
Contains the interface properties.
Properties to aid interFoam:
Correct the alpha boundary condition for dynamic contact angle.
Calculate interface curvature.
Source files
interfaceProperties.H
interfaceProperties.C
Definition at line 53 of file interfaceProperties.H.
Constructor & Destructor Documentation
interfaceProperties (const volScalarField & alpha1, const volVectorField & U, const IOdictionary & dict)
Construct from volume fraction field gamma and IOdictionary.
Definition at line 146 of file interfaceProperties.C.
Member Function Documentation
scalar cAlpha () const inline
Definition at line 130 of file interfaceProperties.H.
const dimensionedScalar& deltaN () const inline
Definition at line 135 of file interfaceProperties.H.
const surfaceScalarField& nHatf () const inline
Definition at line 140 of file interfaceProperties.H.
Foam::tmp< Foam::volScalarField > sigmaK () const
Definition at line 200 of file interfaceProperties.C.
Foam::tmp< Foam::surfaceScalarField > surfaceTensionForce () const
Definition at line 207 of file interfaceProperties.C.
Foam::tmp< Foam::volScalarField > nearInterface () const
Indicator of the proximity of the interface.
Field values are 1 near and 0 away for the interface.
Definition at line 214 of file interfaceProperties.C.
References Foam::fvc::interpolate(), and Foam::fvc::snGrad().
void correct ()
Definition at line 220 of file interfaceProperties.C.
References Foam::pos0().
Referenced by immiscibleIncompressibleTwoPhaseMixture::correct().
bool read ()
Read transportProperties dictionary.
Definition at line 226 of file interfaceProperties.C.
The documentation for this class was generated from the following files:
src/transportModels/interfaceProperties/interfaceProperties.H
src/transportModels/interfaceProperties/interfaceProperties.C