OpenFOAM: mapDistributeBase Class Reference
mapDistributeBase Class Reference
Class containing processor-to-processor mapping information.
Public Member Functions
ClassName ("mapDistributeBase")
mapDistributeBase ()
Construct null.
mapDistributeBase (const mapDistributeBase &map)
Copy construct.
mapDistributeBase (mapDistributeBase &&map)
Move construct.
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from components.
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs)
Construct from reverse addressing: per data item the send.
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Special variant that works with the info sorted into bins.
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from my elements to send. Assumes layout is my elements.
mapDistributeBase (Istream &is)
Construct from Istream.
label constructSize () const
Constructed data size.
label & constructSize ()
Constructed data size.
const labelListList & subMap () const
From subsetted data back to original data.
labelListList & subMap ()
From subsetted data back to original data.
const labelListList & constructMap () const
From subsetted data to new reconstructed data.
labelListList & constructMap ()
From subsetted data to new reconstructed data.
bool subHasFlip () const
Does subMap include a sign.
bool & subHasFlip ()
Does subMap include a sign.
bool constructHasFlip () const
Does constructMap include a sign.
bool & constructHasFlip ()
Does constructMap include a sign.
const List< labelPair > & schedule () const
Return a schedule. Demand driven. See above.
void transfer (mapDistributeBase &rhs)
Transfer the contents of the argument and annul the argument.
void compact (const boolList &elemIsUsed, const int tag=UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
void compact (const boolList &elemIsUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
Compact all maps and layout. Returns compaction maps for.
template<class T >
void distribute (List< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T , class negateOp >
void distribute (List< T > &fld, const negateOp &negOp, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void distribute (DynamicList< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, List< T > &, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void send (PstreamBuffers &, const List< T > &) const
Do all sends using PstreamBuffers.
template<class T >
void receive (PstreamBuffers &, List< T > &) const
Do all receives using PstreamBuffers.
void printLayout (Ostream &os) const
Debug: print layout. Can only be used on maps with sorted.
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistributeBase &rhs)
Copy assignment.
void operator= (mapDistributeBase &&rhs)
Move assignment.
Static Public Member Functions
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag)
Calculate a schedule. See above.
static label renumber (const globalIndex &, const List< Map< label >> &compactMap, const label globalElement)
Helper for construct from globalIndex. Renumbers element.
template<class T , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const negateOp &negOp, const int tag=UPstream::msgType())
Distribute data. Note:schedule only used for.
template<class T , class CombineOp , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const CombineOp &cop, const negateOp &negOp, const T &nullValue, const int tag=UPstream::msgType())
Distribute data. If multiple processors writing to same.
Protected Member Functions
void calcCompactAddressing (const globalIndex &globalNumbering, const labelUList &elements, List< Map< label >> &compactMap) const
Construct per processor compact addressing of the global elements.
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label >> &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label >> &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label >> &compactMap, labelList &compactStart)
Static Protected Member Functions
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
template<class T , class CombineOp , class negateOp >
static void flipAndCombine (const labelUList &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const negateOp &negOp, List< T > &lhs)
template<class T , class negateOp >
static T accessAndFlip (const UList< T > &fld, const label index, const bool hasFlip, const negateOp &negOp)
Protected Attributes
label constructSize_
Size of reconstructed data.
labelListList subMap_
Maps from subsetted data back to original data.
labelListList constructMap_
Maps from subsetted data to new reconstructed data.
bool subHasFlip_
Whether subMap includes flip or not.
bool constructHasFlip_
Whether constructMap includes flip or not.
autoPtr< List< labelPair > > schedulePtr_
Schedule.
Friends
Istream & operator>> (Istream &, mapDistributeBase &)
Read dictionary from Istream.
Ostream & operator<< (Ostream &, const mapDistributeBase &)
Write dictionary to Ostream.
Detailed Description
Class containing processor-to-processor mapping information.
We store mapping from the bits-to-send to the complete starting list (subXXXMap) and from the received bits to their location in the new list (constructXXXMap).
Note: Schedule is a list of processor pairs (one send, one receive. One of them will be myself) which forms a scheduled (i.e. non-buffered) exchange. See distribute on how to use it. Note2: number of items sent on one processor have to equal the number of items received on the other processor.
To aid constructing these maps there are the constructors from global numbering, either with or without transforms.
Constructors using compact numbering: layout is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor. So e.g 4 procs and on proc 1 the compact table will first have all globalIndex.localSize() elements from proc1 followed by used-only elements of proc0, proc2, proc3. The constructed mapDistributeBase sends the local elements from and receives the remote elements into their compact position. compactMap[proci] is the position of elements from proci in the compact map. compactMap[myProcNo()] is empty since trivial addressing.
It rewrites the input global indices into indices into the constructed data.
When constructing from components optionally a 'flip' on the maps can be specified. This will interpret the map values as index+flip, similar to e.g. faceProcAddressing. The flip will only be applied to fieldTypes (scalar, vector, .. triad)
Source files
mapDistributeBase.H
mapDistributeBase.C
mapDistributeBaseTemplates.C
Definition at line 99 of file mapDistributeBase.H.
Constructor & Destructor Documentation
mapDistributeBase ()
Construct null.
Definition at line 534 of file mapDistributeBase.C.
mapDistributeBase (const mapDistributeBase & map)
Copy construct.
Definition at line 544 of file mapDistributeBase.C.
mapDistributeBase (mapDistributeBase && map)
Move construct.
Definition at line 555 of file mapDistributeBase.C.
mapDistributeBase (const label constructSize, labelListList && subMap, labelListList && constructMap, const bool subHasFlip = false, const bool constructHasFlip = false)
Construct from components.
Definition at line 564 of file mapDistributeBase.C.
References transfer().
mapDistributeBase (const labelUList & sendProcs, const labelUList & recvProcs)
Construct from reverse addressing: per data item the send.
processor and the receive processor. (note: data is not stored sorted per processor so cannot use printLayout).
Definition at line 582 of file mapDistributeBase.C.
mapDistributeBase (const globalIndex & globalNumbering, labelList & elements, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
numbering (or -1). Determines compact numbering (see above) and distribute map to get data into this ordering and renumbers the elements to be in compact numbering.
Definition at line 656 of file mapDistributeBase.C.
mapDistributeBase (const globalIndex & globalNumbering, labelListList & cellCells, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Special variant that works with the info sorted into bins.
according to local indices. E.g. think cellCells where cellCells[localCellI] is a list of global cells
Definition at line 715 of file mapDistributeBase.C.
References Foam::Pout, and mapDistributeBase::printLayout().
mapDistributeBase (labelListList && subMap, const bool subHasFlip = false, const bool constructHasFlip = false) explicit
Construct from my elements to send. Assumes layout is my elements.
first followed by elements from all other processors in consecutive order
Definition at line 774 of file mapDistributeBase.C.
References Foam::Pout, and mapDistributeBase::printLayout().
mapDistributeBase (Istream & is)
Construct from Istream.
Definition at line 825 of file mapDistributeBase.C.
Member Function Documentation
void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize) static protected
Definition at line 187 of file mapDistributeBase.C.
void calcCompactAddressing (const globalIndex & globalNumbering, const labelUList & elements, List< Map< label >> & compactMap) const protected
Construct per processor compact addressing of the global elements.
needed. The ones from the local processor are not included since these are always all needed.
Definition at line 279 of file mapDistributeBase.C.
void calcCompactAddressing (const globalIndex & globalNumbering, const labelListList & elements, List< Map< label >> & compactMap) const protected
Definition at line 324 of file mapDistributeBase.C.
void exchangeAddressing (const int tag, const globalIndex & globalNumbering, labelList & elements, List< Map< label >> & compactMap, labelList & compactStart) protected
Definition at line 375 of file mapDistributeBase.C.
void exchangeAddressing (const int tag, const globalIndex & globalNumbering, labelListList & elements, List< Map< label >> & compactMap, labelList & compactStart) protected
Definition at line 453 of file mapDistributeBase.C.
References Foam::renumber().
void flipAndCombine (const labelUList & map, const bool hasFlip, const UList< T > & rhs, const CombineOp & cop, const negateOp & negOp, List< T > & lhs) static protected
Definition at line 31 of file mapDistributeBaseTemplates.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, forAll, i, and UList< T >::size().
T accessAndFlip (const UList< T > & fld, const label index, const bool hasFlip, const negateOp & negOp) static protected
Definition at line 76 of file mapDistributeBaseTemplates.C.
ClassName ("mapDistributeBase")
label constructSize () const inline
Constructed data size.
Definition at line 305 of file mapDistributeBase.H.
References mapDistributeBase::subHasFlip_.
Referenced by extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), PatchTools::edgeNormals(), PatchTools::pointNormals(), distributedUnallocatedDirectFieldMapper::size(), distributedUnallocatedDirectFvPatchFieldMapper::size(), distributedWeightedFvPatchFieldMapper::size(), and pointConstraints::syncUntransformedData().
label& constructSize () inline
Constructed data size.
Definition at line 313 of file mapDistributeBase.H.
References mapDistributeBase::subHasFlip_.
const labelListList& subMap () const inline
From subsetted data back to original data.
Definition at line 321 of file mapDistributeBase.H.
Referenced by distributedTriSurfaceMesh::findNearest(), and distributedTriSurfaceMesh::getVolumeType().
labelListList& subMap () inline
From subsetted data back to original data.
Definition at line 329 of file mapDistributeBase.H.
const labelListList& constructMap () const inline
From subsetted data to new reconstructed data.
Definition at line 337 of file mapDistributeBase.H.
Referenced by distributedTriSurfaceMesh::findNearest(), and distributedTriSurfaceMesh::getVolumeType().
labelListList& constructMap () inline
From subsetted data to new reconstructed data.
Definition at line 345 of file mapDistributeBase.H.
bool subHasFlip () const inline
Does subMap include a sign.
Definition at line 353 of file mapDistributeBase.H.
Referenced by distributedTriSurfaceMesh::findNearest(), and distributedTriSurfaceMesh::getVolumeType().
bool& subHasFlip () inline
Does subMap include a sign.
Definition at line 361 of file mapDistributeBase.H.
bool constructHasFlip () const inline
Does constructMap include a sign.
Definition at line 369 of file mapDistributeBase.H.
Referenced by distributedTriSurfaceMesh::findNearest(), and distributedTriSurfaceMesh::getVolumeType().
bool& constructHasFlip () inline
Does constructMap include a sign.
Definition at line 377 of file mapDistributeBase.H.
Foam::List< Foam::labelPair > schedule (const labelListList & subMap, const labelListList & constructMap, const int tag) static
Calculate a schedule. See above.
Definition at line 39 of file mapDistributeBase.C.
const Foam::List< Foam::labelPair > & schedule () const
Return a schedule. Demand driven. See above.
Definition at line 170 of file mapDistributeBase.C.
void transfer (mapDistributeBase & rhs)
Transfer the contents of the argument and annul the argument.
Definition at line 833 of file mapDistributeBase.C.
Foam::label renumber (const globalIndex & globalNumbering, const List< Map< label >> & compactMap, const label globalElement) static
Helper for construct from globalIndex. Renumbers element.
(in globalIndex numbering) into compact indices.
Definition at line 855 of file mapDistributeBase.C.
void compact (const boolList & elemIsUsed, const int tag = UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
and works out itself what this side and sender side can remove from maps. Only compacts non-local elements (i.e. the stuff that gets sent over), does not change the local layout
Definition at line 878 of file mapDistributeBase.C.
void compact (const boolList & elemIsUsed, const label localSize, labelList & oldToNewSub, labelList & oldToNewConstruct, const int tag = UPstream::msgType())
Compact all maps and layout. Returns compaction maps for.
subMap and constructMap
Definition at line 1039 of file mapDistributeBase.C.
void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const bool subHasFlip, const labelListList & constructMap, const bool constructHasFlip, List< T > & field, const negateOp & negOp, const int tag = UPstream::msgType()) static
Distribute data. Note:schedule only used for.
Pstream::commsTypes::scheduled for now, all others just use send-to-all, receive-from-all.
Definition at line 115 of file mapDistributeBaseTemplates.C.
Referenced by distributedTriSurfaceMesh::findNearest(), and distributedTriSurfaceMesh::getVolumeType().
void distribute (const Pstream::commsTypes commsType, const List< labelPair > & schedule, const label constructSize, const labelListList & subMap, const bool subHasFlip, const labelListList & constructMap, const bool constructHasFlip, List< T > & field, const CombineOp & cop, const negateOp & negOp, const T & nullValue, const int tag = UPstream::msgType()) static
Distribute data. If multiple processors writing to same.
position adds contributions using cop.
Definition at line 623 of file mapDistributeBaseTemplates.C.
void distribute (List< T > & fld, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 1260 of file mapDistributeBaseTemplates.C.
void distribute (List< T > & fld, const negateOp & negOp, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 1198 of file mapDistributeBaseTemplates.C.
References UPstream::blocking, UPstream::defaultCommsType, UPstream::nonBlocking, and UPstream::scheduled.
void distribute (DynamicList< T > & fld, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 1274 of file mapDistributeBaseTemplates.C.
References fld, DynamicList< T, SizeMin >::setCapacity(), DynamicList< T, SizeMin >::shrink(), and UList< T >::size().
void reverseDistribute (const label constructSize, List< T > & fld, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Definition at line 1294 of file mapDistributeBaseTemplates.C.
References UPstream::blocking, UPstream::defaultCommsType, UPstream::nonBlocking, and UPstream::scheduled.
Referenced by mapDistribute::reverseDistribute().
void reverseDistribute (const label constructSize, const T & nullValue, List< T > & fld, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Since constructSize might be larger than supplied size supply a nullValue
Definition at line 1359 of file mapDistributeBaseTemplates.C.
References UPstream::blocking, UPstream::defaultCommsType, UPstream::nonBlocking, and UPstream::scheduled.
void send (PstreamBuffers & pBufs, const List< T > & field) const
Do all sends using PstreamBuffers.
Definition at line 1121 of file mapDistributeBaseTemplates.C.
void receive (PstreamBuffers & pBufs, List< T > & field) const
Do all receives using PstreamBuffers.
Definition at line 1155 of file mapDistributeBaseTemplates.C.
void printLayout (Ostream & os) const
Debug: print layout. Can only be used on maps with sorted.
storage (local data first, then non-local data)
Definition at line 204 of file mapDistributeBase.C.
Referenced by mapDistributeBase::mapDistributeBase().
void updateMesh (const mapPolyMesh &) inline
Correct for topo change.
Definition at line 565 of file mapDistributeBase.H.
void operator= (const mapDistributeBase & rhs)
Copy assignment.
Definition at line 1262 of file mapDistributeBase.C.
void operator= (mapDistributeBase && rhs)
Move assignment.
Definition at line 1278 of file mapDistributeBase.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , mapDistributeBase &) friend
Read dictionary from Istream.
Ostream& operator<< (Ostream & , const mapDistributeBase &) friend
Write dictionary to Ostream.
Member Data Documentation
label constructSize_ protected
Size of reconstructed data.
Definition at line 108 of file mapDistributeBase.H.
labelListList subMap_ protected
Maps from subsetted data back to original data.
Definition at line 113 of file mapDistributeBase.H.
labelListList constructMap_ protected
Maps from subsetted data to new reconstructed data.
Definition at line 118 of file mapDistributeBase.H.
bool subHasFlip_ protected
Whether subMap includes flip or not.
Definition at line 123 of file mapDistributeBase.H.
Referenced by mapDistributeBase::constructSize().
bool constructHasFlip_ protected
Whether constructMap includes flip or not.
Definition at line 128 of file mapDistributeBase.H.
autoPtr<List<labelPair> > schedulePtr_ mutable protected
Schedule.
Definition at line 134 of file mapDistributeBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBase.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBase.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeBaseTemplates.C