OpenFOAM: interpolationWeights Class Reference
interpolationWeights Class Reference abstract
Abstract base class for interpolating in 1D.
Public Member Functions
TypeName ("interpolationWeights")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, interpolationWeights, word,(const scalarField &samples),(samples))
interpolationWeights (const scalarField &samples)
Construct from components.
virtual ~interpolationWeights ()=default
Destructor.
virtual bool valueWeights (const scalar t, labelList &indices, scalarField &weights) const =0
Calculate weights and indices to calculate t from samples.
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList &indices, scalarField &weights) const =0
Calculate weights and indices to calculate integrand of t1..t2.
template<class ListType1 , class ListType2 >
Foam::outerProduct< typename
ListType1::value_type,
typename ListType2::value_type >
::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Static Public Member Functions
static autoPtr
< interpolationWeights > New (const word &type, const scalarField &samples)
Return a reference to the selected interpolationWeights.
template<class ListType1 , class ListType2 >
static outerProduct< typename
ListType1::value_type,
typename ListType2::value_type >
::type weightedSum (const ListType1 &f1, const ListType2 &f2)
Helper: weighted sum.
Protected Member Functions
interpolationWeights (const interpolationWeights &)=delete
No copy construct.
void operator= (const interpolationWeights &)=delete
No copy assignment.
Protected Attributes
const scalarField & samples_
Detailed Description
Abstract base class for interpolating in 1D.
Source files
interpolationWeights.H
interpolationWeights.C
interpolationWeightsTemplates.C
Definition at line 54 of file interpolationWeights.H.
Constructor & Destructor Documentation
interpolationWeights (const interpolationWeights &) protected delete
No copy construct.
interpolationWeights (const scalarField & samples) explicit
Construct from components.
Definition at line 37 of file interpolationWeights.C.
virtual ~interpolationWeights () virtual default
Destructor.
Member Function Documentation
void operator= (const interpolationWeights &) protected delete
No copy assignment.
TypeName ("interpolationWeights")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , interpolationWeights , word , (const scalarField &samples) , (samples))
Foam::autoPtr< Foam::interpolationWeights > New (const word & type, const scalarField & samples) static
Return a reference to the selected interpolationWeights.
Definition at line 46 of file interpolationWeights.C.
Referenced by lumpedPointMovement::interpolator().
virtual bool valueWeights (const scalar t, labelList & indices, scalarField & weights) const pure virtual
Calculate weights and indices to calculate t from samples.
Returns true if indices changed.
Implemented in linearInterpolationWeights, and splineInterpolationWeights.
Referenced by lumpedPointMovement::displacePoints().
virtual bool integrationWeights (const scalar t1, const scalar t2, labelList & indices, scalarField & weights) const pure virtual
Calculate weights and indices to calculate integrand of t1..t2.
from samples. Returns true if indices changed.
Implemented in linearInterpolationWeights, and splineInterpolationWeights.
static outerProduct< typename ListType1::value_type, typename ListType2::value_type >::type weightedSum (const ListType1 & f1, const ListType2 & f2) static
Helper: weighted sum.
Foam::outerProduct< typename ListType1::value_type, typename ListType2::value_type>::type weightedSum (const ListType1 & f1, const ListType2 & f2)
Definition at line 34 of file interpolationWeightsTemplates.C.
References i, Foam::type(), and Foam::Zero.
Member Data Documentation
const scalarField& samples_ protected
Definition at line 60 of file interpolationWeights.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/interpolations/interpolationWeights/interpolationWeights/interpolationWeights.H
src/OpenFOAM/interpolations/interpolationWeights/interpolationWeights/interpolationWeights.C
src/OpenFOAM/interpolations/interpolationWeights/interpolationWeights/interpolationWeightsTemplates.C