OpenFOAM: bitSet::reference Class Reference
bitSet::reference Class Reference
A reference supporting read/write access to an entry.
Public Member Functions
void flip ()
Flip the bit at the position, no range-checking.
void operator= (const reference &other)
Value assignment.
void operator= (const unsigned int val)
Value assignment.
operator unsigned int () const
Conversion operator.
Public Member Functions inherited from PackedList< Width >::reference
void operator= (const reference &other)
Value assignment.
void operator= (const unsigned int val)
Value assignment.
operator unsigned int () const
Conversion operator.
Protected Member Functions
void operator& ()=delete
reference (bitSet *parent, const label index)
Construct by taking reference of block from within the list and the specified index.
Protected Member Functions inherited from PackedList< Width >::reference
void operator& ()=delete
reference (PackedList *parent, const label index)
Construct by taking reference of block from within the list and the specified index.
unsigned int get () const
Get value as unsigned, no range-checking.
bool set (unsigned int val)
Set value, returning true if changed, no range-checking.
Friends
class bitSet
Additional Inherited Members
Protected Attributes inherited from PackedList< Width >::reference
block_type & ref_
Reference to the block.
unsigned shift_
The bit shift to access the given sub-portion.
Detailed Description
A reference supporting read/write access to an entry.
Definition at line 591 of file bitSet.H.
Constructor & Destructor Documentation
reference (bitSet * parent, const label index) inline protected
Construct by taking reference of block from within the list and the specified index.
Definition at line 172 of file bitSetI.H.
Member Function Documentation
void operator& () protected delete
void flip () inline
Flip the bit at the position, no range-checking.
Definition at line 181 of file bitSetI.H.
Referenced by bitSet::bound().
void operator= (const reference & other) inline
Value assignment.
Definition at line 189 of file bitSetI.H.
References PackedList< 1 >::max_value.
void operator= (const unsigned int val) inline
Value assignment.
Definition at line 199 of file bitSetI.H.
References bitSet::set().
operator unsigned int () const inline
Conversion operator.
Definition at line 207 of file bitSetI.H.
References bitSet::set(), and Foam::val.
Friends And Related Function Documentation
friend class bitSet friend
Definition at line 596 of file bitSet.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Bits/bitSet/bitSet.H
src/OpenFOAM/containers/Bits/bitSet/bitSetI.H