OpenFOAM: MeshObject< Mesh, MeshObjectType, Type > Class Template Reference
MeshObject< Mesh, MeshObjectType, Type > Class Template Reference
Templated abstract base-class for optional mesh objects used to automate their allocation to the mesh database and the mesh-modifier event-loop.
Public Member Functions
MeshObject (const Mesh &mesh)
Construct on Mesh type.
virtual ~MeshObject ()=default
Destructor.
const Mesh & mesh () const
virtual bool writeData (Ostream &os) const
Static Public Member Functions
template<class... Args>
static const Type & New (const Mesh &mesh, Args &&...args)
Get existing or create a new MeshObject.
static bool Delete (const Mesh &mesh)
Static destructor.
Protected Attributes
const Mesh & mesh_
Detailed Description
template<class Mesh, template< class > class MeshObjectType, class Type>
class Foam::MeshObject< Mesh, MeshObjectType, Type >
Templated abstract base-class for optional mesh objects used to automate their allocation to the mesh database and the mesh-modifier event-loop.
MeshObject is templated on the type of mesh it is allocated to, the type of the mesh object (TopologicalMeshObject, GeometricMeshObject, MoveableMeshObject, UpdateableMeshObject) and the type of the actual object it is created for example:
class leastSquaresVectors
:
    public MeshObject<fvMesh, MoveableMeshObject, leastSquaresVectors>
{
.
.
.
    /*!
     * \brief Delete the least square vectors when the mesh moves
*/
        virtual bool movePoints();
    };
MeshObject types:
TopologicalMeshObject: mesh object to be deleted on topology change
GeometricMeshObject: mesh object to be deleted on geometry change
MoveableMeshObject: mesh object to be updated in movePoints
UpdateableMeshObject: mesh object to be updated in updateMesh or movePoints
Note movePoints must be provided for MeshObjects of type MoveableMeshObject and both movePoints and updateMesh functions must exist, provided for MeshObjects of type UpdateableMeshObject.
SourceFiles MeshObject.C
\*—————————————————————————
Definition at line 84 of file MeshObject.H.
Constructor & Destructor Documentation
MeshObject (const Mesh & mesh) explicit
Construct on Mesh type.
Definition at line 29 of file MeshObject.C.
virtual ~MeshObject () virtual default
Destructor.
Member Function Documentation
const Type & New (const Mesh & mesh, Args &&... args) static
Get existing or create a new MeshObject.
Definition at line 41 of file MeshObject.C.
References args, Foam::expressions::patchExpr::debug, Foam::endl(), OSstream::name(), Foam::Pout, and regIOobject::store().
Referenced by CentredFitSnGradScheme< Type, Polynomial, Stencil >::corrected(), CentredFitScheme< Type, Polynomial, Stencil >::corrected(), PureUpwindFitScheme< Type, Polynomial, Stencil >::corrected(), dynamicOversetFvMesh::interpolate(), and gravity::New().
bool Delete (const Mesh & mesh) static
Static destructor.
Definition at line 75 of file MeshObject.C.
const Mesh& mesh () const inline
Definition at line 126 of file MeshObject.H.
Referenced by patchExprFieldBase::getFvPatch().
virtual bool writeData (Ostream & os) const inline virtual
Definition at line 131 of file MeshObject.H.
Member Data Documentation
const Mesh& mesh_ protected
Definition at line 92 of file MeshObject.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/MeshObject/MeshObject.H
src/OpenFOAM/meshes/MeshObject/MeshObject.C