OpenFOAM: fieldVisualisationBase Class Reference
fieldVisualisationBase Class Reference
Base class for scene objects.
Classes
struct fieldSummary
General field characteristics.
Public Types
enum colourByType { cbColour, cbField }
Colouring type.
enum colourMapType {
cmCoolToWarm, cmBlueWhiteRed = cmCoolToWarm, cmColdAndHot, cmFire,
cmRainbow, cmGreyscale, cmXray
}
Colour map enumerations.
enum FieldAssociation { NO_DATA = 0, CELL_DATA = 0x1, POINT_DATA = 0x2, CELL_POINT_DATA = 0x3 }
Enumeration of the data field associations.
Public Member Functions
fieldVisualisationBase (const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~fieldVisualisationBase ()
Destructor.
const HashPtrTable< Function1
< vector > > & colours () const
Return the colours.
const word & fieldName () const
Return the field name.
Static Public Attributes
static const Enum< colourByType > colourByTypeNames
Enumeration names for colourByType.
static const Enum< colourMapType > colourMapTypeNames
Enumeration names for colourMapType.
Protected Member Functions
void setColourMap (vtkLookupTable *lut) const
Set the colour map.
void addScalarBar (const scalar position, vtkRenderer *renderer, vtkLookupTable *lut) const
Add scalar bar (if visible) to renderer.
void setField (const scalar position, const word &colourFieldName, const FieldAssociation fieldAssociation, vtkMapper *mapper, vtkRenderer *renderer) const
Set field/configure mapper, add scalar bar.
void addGlyphs (const scalar position, const word &scaleFieldName, const fieldSummary &scaleFieldInfo, const word &colourFieldName, const fieldSummary &colourFieldInfo, const scalar maxGlyphLength, vtkPolyData *data, vtkActor *actor, vtkRenderer *renderer) const
Add glyphs.
fieldVisualisationBase (const fieldVisualisationBase &)=delete
No copy construct.
void operator= (const fieldVisualisationBase &)=delete
No copy assignment.
Static Protected Member Functions
static fieldSummary queryFieldSummary (const word &fieldName, vtkDataSet *dataset)
Query DataSet for field name and its field association.
static fieldSummary queryFieldSummary (const word &fieldName, vtkCompositeDataSet *data)
Query composite DataSet for field name and its FieldAssociation.
static FieldAssociation queryFieldAssociation (const word &fieldName, vtkDataSet *dataset)
Query DataSet for field name and its field association.
static FieldAssociation queryFieldAssociation (const word &fieldName, vtkCompositeDataSet *data)
Query composite DataSet for field name and its FieldAssociation.
static void addMagField (const word &fieldName, vtkFieldData *fieldData)
Add "mag(..)" field for filters that only accept scalars.
static void addMagField (const word &fieldName, vtkDataSet *dataset)
Add "mag(..)" field for filters that only accept scalars.
static void addMagField (const word &fieldName, vtkCompositeDataSet *data)
Add "mag(..)" field for filters that only accept scalars.
Protected Attributes
const HashPtrTable< Function1
< vector > > & colours_
Colours.
word fieldName_
Field name.
bool smooth_
Requested smoother fields (eg, interpolate cell -> point values)
colourByType colourBy_
Colour by type.
colourMapType colourMap_
Colour map type.
Tuple2< scalar, scalar > range_
Range of values.
scalarBar scalarBar_
Scalar bar characteristics.
Detailed Description
Base class for scene objects.
Dictionary controls - colour by field
Property Description Required Default
colourBy Colouring type (color / field) yes
range Lower/upper range to display yes
smooth Request smoother output no false
colourMap Colour map for rendering no rainbow
scalarBar Scalar-bar sub-dictionary yes
Colour maps include "coolToWarm" ("blueWhiteRed"), "coldAndHot", "fire", "rainbow", "greyscale" ("grayscale"), "xray". For historical reasons, the default is still "rainbow".
Source files
fieldVisualisationBase.H
fieldVisualisationBase.C
Definition at line 121 of file fieldVisualisationBase.H.
Member Enumeration Documentation
enum colourByType
Colouring type.
Enumerator
cbColour
"colour" : Use specified colour
cbField
"field" : Use named field
Definition at line 130 of file fieldVisualisationBase.H.
enum colourMapType
Colour map enumerations.
Enumerator
cmCoolToWarm
ParaView "Cool To Warm" blue-white-read.
cmBlueWhiteRed
cmColdAndHot
ParaView "Cold and Hot".
cmFire
ParaView "Black-Body Radiation".
cmRainbow
"rainbow"
cmGreyscale
ParaView "Grayscale".
cmXray
ParaView "X Ray".
Definition at line 144 of file fieldVisualisationBase.H.
enum FieldAssociation
Enumeration of the data field associations.
These values are used internally and do NOT correspond to the vtkDataObject::FieldAssociations enumeration.
Enumerator
NO_DATA
No associated data.
CELL_DATA
Associated with cells (faces)
POINT_DATA
Associated with points.
CELL_POINT_DATA
Associated with cells and/or points.
Definition at line 167 of file fieldVisualisationBase.H.
Constructor & Destructor Documentation
fieldVisualisationBase (const fieldVisualisationBase &) protected delete
No copy construct.
fieldVisualisationBase (const dictionary & dict, const HashPtrTable< Function1< vector >> & colours)
Construct from dictionary.
Definition at line 733 of file fieldVisualisationBase.C.
~fieldVisualisationBase () virtual
Destructor.
Definition at line 780 of file fieldVisualisationBase.C.
Member Function Documentation
Foam::functionObjects::runTimePostPro::fieldVisualisationBase::fieldSummary queryFieldSummary (const word & fieldName, vtkDataSet * dataset) static protected
Query DataSet for field name and its field association.
Definition at line 83 of file fieldVisualisationBase.C.
References fieldVisualisationBase::fieldSummary::association_, fieldVisualisationBase::fieldSummary::nComponents_, Foam::expressions::patchExpr::POINT_DATA, fieldVisualisationBase::fieldSummary::range_, and Foam::vtk::Tools::rangeOf().
Foam::functionObjects::runTimePostPro::fieldVisualisationBase::fieldSummary queryFieldSummary (const word & fieldName, vtkCompositeDataSet * data) static protected
Query composite DataSet for field name and its FieldAssociation.
Definition at line 126 of file fieldVisualisationBase.C.
Foam::functionObjects::runTimePostPro::fieldVisualisationBase::FieldAssociation queryFieldAssociation (const word & fieldName, vtkDataSet * dataset) static protected
Query DataSet for field name and its field association.
Definition at line 172 of file fieldVisualisationBase.C.
Foam::functionObjects::runTimePostPro::fieldVisualisationBase::FieldAssociation queryFieldAssociation (const word & fieldName, vtkCompositeDataSet * data) static protected
Query composite DataSet for field name and its FieldAssociation.
Definition at line 198 of file fieldVisualisationBase.C.
void addMagField (const word & fieldName, vtkFieldData * fieldData) static protected
Add "mag(..)" field for filters that only accept scalars.
Definition at line 231 of file fieldVisualisationBase.C.
void addMagField (const word & fieldName, vtkDataSet * dataset) static protected
Add "mag(..)" field for filters that only accept scalars.
Definition at line 312 of file fieldVisualisationBase.C.
void addMagField (const word & fieldName, vtkCompositeDataSet * data) static protected
Add "mag(..)" field for filters that only accept scalars.
Definition at line 326 of file fieldVisualisationBase.C.
void setColourMap (vtkLookupTable * lut) const protected
Set the colour map.
Definition at line 388 of file fieldVisualisationBase.C.
void addScalarBar (const scalar position, vtkRenderer * renderer, vtkLookupTable * lut) const protected
Add scalar bar (if visible) to renderer.
Definition at line 473 of file fieldVisualisationBase.C.
void setField (const scalar position, const word & colourFieldName, const FieldAssociation fieldAssociation, vtkMapper * mapper, vtkRenderer * renderer) const protected
Set field/configure mapper, add scalar bar.
Definition at line 489 of file fieldVisualisationBase.C.
void addGlyphs (const scalar position, const word & scaleFieldName, const fieldSummary & scaleFieldInfo, const word & colourFieldName, const fieldSummary & colourFieldInfo, const scalar maxGlyphLength, vtkPolyData * data, vtkActor * actor, vtkRenderer * renderer) const protected
Add glyphs.
Definition at line 555 of file fieldVisualisationBase.C.
void operator= (const fieldVisualisationBase &) protected delete
No copy assignment.
const Foam::HashPtrTable< Foam::Function1< Foam::vector >, Foam::word > & colours () const
Return the colours.
Definition at line 787 of file fieldVisualisationBase.C.
const Foam::word & fieldName () const
Return the field name.
Definition at line 794 of file fieldVisualisationBase.C.
Referenced by geometryCloud::addField(), and geometryPatches::addPatchField().
Member Data Documentation
const Foam::Enum< Foam::functionObjects::runTimePostPro::fieldVisualisationBase::colourByType > colourByTypeNames static
Enumeration names for colourByType.
Definition at line 139 of file fieldVisualisationBase.H.
const Foam::Enum< Foam::functionObjects::runTimePostPro::fieldVisualisationBase::colourMapType > colourMapTypeNames static
Enumeration names for colourMapType.
Definition at line 158 of file fieldVisualisationBase.H.
const HashPtrTable<Function1<vector> >& colours_ protected
Colours.
Definition at line 249 of file fieldVisualisationBase.H.
word fieldName_ protected
Field name.
Definition at line 254 of file fieldVisualisationBase.H.
bool smooth_ protected
Requested smoother fields (eg, interpolate cell -> point values)
Definition at line 259 of file fieldVisualisationBase.H.
colourByType colourBy_ protected
Colour by type.
Definition at line 264 of file fieldVisualisationBase.H.
colourMapType colourMap_ protected
Colour map type.
Definition at line 269 of file fieldVisualisationBase.H.
Tuple2<scalar, scalar> range_ protected
Range of values.
Definition at line 274 of file fieldVisualisationBase.H.
scalarBar scalarBar_ protected
Scalar bar characteristics.
Definition at line 279 of file fieldVisualisationBase.H.
The documentation for this class was generated from the following files:
src/functionObjects/graphics/runTimePostProcessing/fieldVisualisationBase.H
src/functionObjects/graphics/runTimePostProcessing/fieldVisualisationBase.C