OpenFOAM: laminarModel< BasicTurbulenceModel > Class Template Reference
laminarModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for laminar transport models.
Public Types
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("laminar")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, laminarModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
laminarModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~laminarModel ()=default
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity, i.e. 0 for laminar flow.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity, i.e. the laminar viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual tmp< volScalarField > k () const
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
virtual tmp< volScalarField > epsilon () const
Return the turbulence kinetic energy dissipation rate,.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
virtual void correct ()
Correct the laminar transport.
Static Public Member Functions
static autoPtr< laminarModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected laminar model.
Protected Member Functions
virtual void printCoeffs (const word &type)
Print model coefficients.
laminarModel (const laminarModel &)=delete
No copy construct.
void operator= (const laminarModel &)=delete
No copy assignment.
Protected Attributes
dictionary laminarDict_
laminar coefficients dictionary
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::laminarModel< BasicTurbulenceModel >
Templated abstract base class for laminar transport models.
Source files
laminarModel.H
laminarModel.C
Definition at line 47 of file laminarModel.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 92 of file laminarModel.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 93 of file laminarModel.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 94 of file laminarModel.H.
Constructor & Destructor Documentation
laminarModel (const laminarModel< BasicTurbulenceModel > &) protected delete
No copy construct.
laminarModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 41 of file laminarModel.C.
virtual ~laminarModel () virtual default
Destructor.
Member Function Documentation
void printCoeffs (const word & type) protected virtual
Print model coefficients.
Definition at line 28 of file laminarModel.C.
References Foam::endl(), and Foam::Info.
void operator= (const laminarModel< BasicTurbulenceModel > &) protected delete
No copy assignment.
TypeName ("laminar")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , laminarModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
Foam::autoPtr< Foam::laminarModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected laminar model.
Definition at line 79 of file laminarModel.C.
References Foam::constant::atomic::alpha, TimePaths::constant(), IOobject::db(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::findDict(), dictionary::get(), IOobject::group(), IOobject::groupName(), Foam::Info, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, phi, rho, IOobject::time(), and U.
bool read () virtual
Read model coefficients if they have changed.
Reimplemented in Maxwell< BasicTurbulenceModel >, Stokes< BasicTurbulenceModel >, and linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 162 of file laminarModel.C.
virtual const dictionary& coeffDict () const inline virtual
Const access to the coefficients dictionary.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 177 of file laminarModel.H.
Foam::tmp< Foam::volScalarField > nut () const virtual
Return the turbulence viscosity, i.e. 0 for laminar flow.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 179 of file laminarModel.C.
Foam::tmp< Foam::scalarField > nut (const label patchi) const virtual
Return the turbulence viscosity on patch.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 201 of file laminarModel.C.
Foam::tmp< Foam::volScalarField > nuEff () const virtual
Return the effective viscosity, i.e. the laminar viscosity.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 214 of file laminarModel.C.
Foam::tmp< Foam::scalarField > nuEff (const label patchi) const virtual
Return the effective viscosity on patch.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 229 of file laminarModel.C.
Foam::tmp< Foam::volScalarField > k () const virtual
Return the turbulence kinetic energy, i.e. 0 for laminar flow.
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 239 of file laminarModel.C.
References nu.
Foam::tmp< Foam::volScalarField > epsilon () const virtual
Return the turbulence kinetic energy dissipation rate,.
i.e. 0 for laminar flow
Reimplemented in Stokes< BasicTurbulenceModel >.
Definition at line 260 of file laminarModel.C.
Foam::tmp< Foam::volSymmTensorField > R () const virtual
Return the Reynolds stress tensor, i.e. 0 for laminar flow.
Reimplemented in Stokes< BasicTurbulenceModel >, and Maxwell< BasicTurbulenceModel >.
Definition at line 281 of file laminarModel.C.
void correct () virtual
Correct the laminar transport.
Reimplemented in Maxwell< BasicTurbulenceModel >, Stokes< BasicTurbulenceModel >, and linearViscousStress< laminarModel< BasicTurbulenceModel > >.
Definition at line 301 of file laminarModel.C.
Member Data Documentation
dictionary laminarDict_ protected
laminar coefficients dictionary
Definition at line 59 of file laminarModel.H.
Switch printCoeffs_ protected
Flag to print the model coeffs at run-time.
Definition at line 64 of file laminarModel.H.
dictionary coeffDict_ protected
Model coefficients dictionary.
Definition at line 69 of file laminarModel.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/laminar/laminarModel/laminarModel.H
src/TurbulenceModels/turbulenceModels/laminar/laminarModel/laminarModel.C