OpenFOAM: CodedSource< Type > Class Template Reference
CodedSource< Type > Class Template Reference
Public Member Functions
TypeName ("coded")
Runtime type information.
CodedSource (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
option & redirectFvOption () const
Dynamically compiled fvOption.
virtual void correct (GeometricField< Type, fvPatchField, volMesh > &)
Correct field.
virtual void addSup (fvMatrix< Type > &eqn, const label fieldi)
Explicit/implicit matrix contributions.
virtual void addSup (const volScalarField &rho, fvMatrix< Type > &eqn, const label fieldi)
Explicit/implicit matrix contributions to compressible equation.
virtual void constrain (fvMatrix< Type > &eqn, const label fieldi)
Set value.
virtual bool read (const dictionary &dict)
Read source dictionary.
Public Member Functions inherited from cellSetOption
TypeName ("cellSetOption")
Runtime type information.
cellSetOption (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
virtual ~cellSetOption ()=default
Destructor.
scalar timeStart () const
Return const access to the time start.
scalar duration () const
Return const access to the duration.
bool inTimeLimits (const scalar time) const
Return true if within time limits.
const selectionModeType & selectionMode () const
Return const access to the cell selection mode.
const word & cellSetName () const
Return const access to the name of cell set for "cellSet".
scalar V () const
Return const access to the total cell volume.
const labelList & cells () const
Return const access to the cell set.
scalar & timeStart ()
Return access to the time start.
scalar & duration ()
Return access to the duration.
virtual bool isActive ()
Is the source active?
Public Member Functions inherited from option
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()=default
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
Protected Member Functions
virtual dlLibraryTable & libs () const
Get the loaded dynamic libraries.
virtual void prepare (dynamicCode &, const dynamicCodeContext &) const
Adapt the context for the current object.
virtual string description () const
Return a description (type + name) for the output.
virtual void clearRedirect () const
Clear any redirected objects.
virtual const dictionary & codeDict () const
Get the dictionary to initialize the codeContext.
Protected Member Functions inherited from cellSetOption
void setSelection (const dictionary &dict)
Set the cellSet or points selection.
void setCellSet ()
Set the cell set based on the user input selection mode.
void setVol ()
Recalculate the volume.
Protected Member Functions inherited from codedBase
void setCodeContext (const dictionary &dict)
Set code context from a dictionary.
void append (const std::string &str)
Add content to SHA1 hashing.
void updateLibrary (const word &name, const dynamicCodeContext &context) const
Update library as required, using the given context.
void updateLibrary (const word &name, const dictionary &dict) const
Update library as required, using the given code dictionary to use for the context.
void updateLibrary (const word &name) const
Update library as required, using the predefined context or use the codeDict() to generate one.
ClassName ("codedBase")
Runtime type information.
codedBase ()=default
Construct null.
virtual ~codedBase ()=default
Destructor.
Protected Attributes
word name_
string codeCorrect_
string codeAddSup_
string codeConstrain_
autoPtr< option > redirectFvOptionPtr_
Underlying functionObject.
Protected Attributes inherited from cellSetOption
scalar timeStart_
Time start.
scalar duration_
Duration.
selectionModeType selectionMode_
Cell selection mode.
word cellSetName_
Name of set/zone for "cellSet" and "cellZone" selectionMode.
List< point > points_
List of points for "points" selectionMode.
labelList cells_
Set of cells to apply source to.
scalar V_
Sum of cell volumes.
Protected Attributes inherited from option
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Additional Inherited Members
Public Types inherited from cellSetOption
enum selectionModeType { smPoints, smCellSet, smCellZone, smAll }
Enumeration for selection mode types.
Static Public Member Functions inherited from option
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Public Attributes inherited from option
bool log
Switch write log to Info.
Static Public Attributes inherited from cellSetOption
static const Enum
< selectionModeType > selectionModeTypeNames_
List of selection mode type names.
Static Protected Member Functions inherited from codedBase
static void writeCodeDict (Ostream &os, const dictionary &dict)
Write code-dictionary contents.
Detailed Description
template<class Type>
class Foam::fv::CodedSource< Type >
Definition at line 119 of file CodedSource.H.
Constructor & Destructor Documentation
CodedSource (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 112 of file CodedSource.C.
Member Function Documentation
Foam::dlLibraryTable & libs () const protected virtual
Get the loaded dynamic libraries.
Implements codedBase.
Definition at line 81 of file CodedSource.C.
void prepare (dynamicCode & dynCode, const dynamicCodeContext & context) const protected virtual
Adapt the context for the current object.
Implements codedBase.
Definition at line 32 of file CodedSource.C.
References dynamicCode::addCompileFile(), dynamicCode::addCopyFile(), dynamicCodeContext::options(), dynamicCode::setFilterVariable(), and dynamicCode::setMakeOptions().
Foam::string description () const protected virtual
Return a description (type + name) for the output.
Implements codedBase.
Definition at line 88 of file CodedSource.C.
void clearRedirect () const protected virtual
Clear any redirected objects.
Implements codedBase.
Definition at line 95 of file CodedSource.C.
const Foam::dictionary & codeDict () const protected virtual
Get the dictionary to initialize the codeContext.
Implements codedBase.
Definition at line 102 of file CodedSource.C.
TypeName ("coded")
Runtime type information.
Foam::fv::option & redirectFvOption () const
Dynamically compiled fvOption.
Definition at line 128 of file CodedSource.C.
void correct (GeometricField< Type, fvPatchField, volMesh > & field) virtual
Correct field.
Definition at line 149 of file CodedSource.C.
void addSup (fvMatrix< Type > & eqn, const label fieldi) virtual
Explicit/implicit matrix contributions.
Definition at line 164 of file CodedSource.C.
void addSup (const volScalarField & rho, fvMatrix< Type > & eqn, const label fieldi) virtual
Explicit/implicit matrix contributions to compressible equation.
Definition at line 180 of file CodedSource.C.
void constrain (fvMatrix< Type > & eqn, const label fieldi) virtual
Set value.
Definition at line 197 of file CodedSource.C.
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented from cellSetOption.
Definition at line 27 of file CodedSourceIO.C.
References append(), Foam::constant::electromagnetic::e, Foam::stringOps::inplaceExpand(), Foam::blockMeshTools::read(), dictionary::readCompat(), entry::readEntry(), and entry::startLineNumber().
Member Data Documentation
word name_ protected
Definition at line 129 of file CodedSource.H.
string codeCorrect_ protected
Definition at line 131 of file CodedSource.H.
string codeAddSup_ protected
Definition at line 132 of file CodedSource.H.
string codeConstrain_ protected
Definition at line 133 of file CodedSource.H.
autoPtr<option> redirectFvOptionPtr_ mutable protected
Underlying functionObject.
Definition at line 138 of file CodedSource.H.
The documentation for this class was generated from the following files:
src/fvOptions/sources/general/codedSource/CodedSource.H
src/fvOptions/sources/general/codedSource/CodedSource.C
src/fvOptions/sources/general/codedSource/CodedSourceIO.C