OpenFOAM: DimensionedField< Type, GeoMesh > Class Template Reference
DimensionedField< Type, GeoMesh > Class Template Reference
Field with dimensions and associated with geometry type GeoMesh which is used to size the field and a reference to it is maintained.
Public Types
typedef GeoMesh::Mesh Mesh
Type of mesh on which this DimensionedField is instantiated.
typedef Field< Type > FieldType
Type of the field from which this DimensionedField is derived.
typedef Field< Type >::cmptType cmptType
Component type of the elements of the field.
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Public Types inherited from Field< Type >
typedef pTraits< Type >::cmptType cmptType
Component type.
typedef SubField< Type > subField
Declare type of subField.
Public Types inherited from List< Type >
typedef SubList< Type > subList
Declare type of subList.
Public Types inherited from UList< Type >
typedef Type value_type
The value type the list contains.
typedef Type * pointer
The pointer type for non-const access to value_type items.
typedef const Type * const_pointer
The pointer type for const access to value_type items.
typedef Type & reference
The type used for storing into value_type objects.
typedef const Type & const_reference
The type used for reading from constant value_type objects.
typedef Type * iterator
Random access iterator for traversing a UList.
typedef const Type * const_iterator
Random access iterator for traversing a UList.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Public Member Functions
TypeName ("DimensionedField")
Runtime type information.
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const Field< Type > &field)
Construct from components.
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, Field< Type > &&field)
Construct from components, transferring initial field content.
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, List< Type > &&field)
Construct from components, transferring initial field content.
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const tmp< Field< Type >> &tfield)
Construct from components, copy or transfer tmp content.
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensionSet &dims, const bool checkIOFlags=true)
Construct from components, setting the initial size and assigning the dimensions, but not initialising any field values.
DimensionedField (const IOobject &io, const Mesh &mesh, const dimensioned< Type > &dt, const bool checkIOFlags=true)
Construct from components, setting the initial size and assigning both dimensions and values.
DimensionedField (const IOobject &io, const Mesh &mesh, const word &fieldDictEntry="value")
Construct from Istream.
DimensionedField (const IOobject &io, const Mesh &mesh, const dictionary &fieldDict, const word &fieldDictEntry="value")
Construct from dictionary.
DimensionedField (const DimensionedField< Type, GeoMesh > &df)
Copy construct.
DimensionedField (DimensionedField< Type, GeoMesh > &&df)
Move construct.
DimensionedField (DimensionedField< Type, GeoMesh > &df, bool reuse)
Copy construct or reuse (move) as specified.
DimensionedField (const tmp< DimensionedField< Type, GeoMesh >> &tdf)
Construct from tmp<DimensionedField> deleting argument.
DimensionedField (const IOobject &io, const DimensionedField< Type, GeoMesh > &df)
Copy construct, resetting IO parameters.
DimensionedField (const IOobject &io, DimensionedField< Type, GeoMesh > &&df)
Move construct, resetting IO parameters.
DimensionedField (const IOobject &io, DimensionedField< Type, GeoMesh > &df, bool reuse)
Copy or move construct, resetting IO parameters.
DimensionedField (const IOobject &io, const tmp< DimensionedField< Type, GeoMesh >> &tdf)
Construct from tmp<DimensionedField> deleting argument, resetting IO parameters.
DimensionedField (const word &newName, const DimensionedField< Type, GeoMesh > &df)
Copy construct with a new name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &&df)
Move construct with a new name.
DimensionedField (const word &newName, DimensionedField< Type, GeoMesh > &df, bool reuse)
Copy or move construct, resetting name.
DimensionedField (const word &newName, const tmp< DimensionedField< Type, GeoMesh >> &tdf)
Construct with a new name from tmp<DimensionedField>
tmp< DimensionedField< Type,
GeoMesh > > clone () const
Clone.
virtual ~DimensionedField ()=default
Destructor.
void readField (const dictionary &fieldDict, const word &fieldDictEntry="value")
const Mesh & mesh () const
Return mesh.
const dimensionSet & dimensions () const
Return dimensions.
dimensionSet & dimensions ()
Return non-const access to dimensions.
const orientedType & oriented () const
Return oriented type.
orientedType & oriented ()
Return non-const access to the oriented type.
void setOriented (const bool oriented=true)
Set the oriented flag.
const Field< Type > & field () const
Return field.
Field< Type > & field ()
Return field.
tmp< DimensionedField
< cmptType, GeoMesh > > component (const direction d) const
Return a component field of the field.
void replace (const direction d, const DimensionedField< cmptType, GeoMesh > &df)
Replace a component field of the field.
void replace (const direction d, const tmp< DimensionedField< cmptType, GeoMesh >> &tdf)
Replace a component field of the field.
tmp< DimensionedField< Type,
GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
dimensioned< Type > average () const
Calculate and return arithmetic average.
dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > &weightField) const
Calculate and return weighted average.
dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh >> &tweightField) const
Calculate and return weighted average.
bool writeData (Ostream &os, const word &fieldDictEntry) const
bool writeData (Ostream &os) const
Pure virtual writeData function.
void operator= (const DimensionedField< Type, GeoMesh > &df)
void operator= (const tmp< DimensionedField< Type, GeoMesh >> &tdf)
void operator= (const dimensioned< Type > &dt)
Assign dimensions and value.
void operator+= (const DimensionedField< Type, GeoMesh > &df)
void operator+= (const tmp< DimensionedField< Type, GeoMesh >> &tdf)
void operator-= (const DimensionedField< Type, GeoMesh > &df)
void operator-= (const tmp< DimensionedField< Type, GeoMesh >> &tdf)
void operator*= (const DimensionedField< scalar, GeoMesh > &df)
void operator*= (const tmp< DimensionedField< scalar, GeoMesh >> &tdf)
void operator/= (const DimensionedField< scalar, GeoMesh > &df)
void operator/= (const tmp< DimensionedField< scalar, GeoMesh >> &tdf)
void operator+= (const dimensioned< Type > &dt)
void operator-= (const dimensioned< Type > &dt)
void operator*= (const dimensioned< scalar > &dt)
void operator/= (const dimensioned< scalar > &dt)
template<>
const word typeName ("volScalarField::Internal")
template<>
const word typeName ("volVectorField::Internal")
template<>
const word typeName ("volSphericalTensorField::Internal")
template<>
const word typeName ("volSymmTensorField::Internal")
template<>
const word typeName ("volTensorField::Internal")
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Public Member Functions inherited from Field< Type >
constexpr Field () noexcept
Construct null.
Field (const label len)
Construct given size.
Field (const label len, const Type &val)
Construct given size and initial value.
Field (const label len, const zero)
Construct given size and initial values of zero.
Field (const Field< Type > &fld)
Copy construct.
Field (const UList< Type > &list)
Copy construct from UList<Type>
template<class Addr >
Field (const IndirectListBase< Type, Addr > &list)
Copy construct from IndirectList.
Field (Field< Type > &&fld)
Move construct from Field.
Field (List< Type > &&list)
Move construct from List.
template<int SizeMin>
Field (DynamicList< Type, SizeMin > &&list)
Move construct from DynamicList.
Field (const UList< Type > &mapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
Construct by 1 to 1 mapping from the given tmp field.
Field (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Construct by interpolative mapping from the given tmp field.
Field (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const UList< Type > &mapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Construct by mapping from the given tmp field.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const Type &defaultValue, const bool applyFlip=true)
Construct by mapping from the given tmp field. Uses supplied uniform value for unmapped items.
Field (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const UList< Type > &defaultValues, const bool applyFlip=true)
Construct by mapping from the given tmp field. Uses supplied values for unmapped items.
Field (Field< Type > &fld, bool reuse)
Copy construct or re-use as specified.
Field (const tmp< Field< Type >> &tfld)
Copy or move construct from tmp.
Field (Istream &is)
Construct from Istream.
Field (const word &keyword, const dictionary &dict, const label len)
Construct from a dictionary entry.
tmp< Field< Type > > clone () const
Clone.
void map (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 map from the given field
void map (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 map from the given tmp field
void map (const UList< Type > &mapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given field.
void map (const tmp< Field< Type >> &tmapF, const labelListList &mapAddressing, const scalarListList &weights)
Interpolative map from the given tmp field.
void map (const UList< Type > &mapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given field.
void map (const tmp< Field< Type >> &tmapF, const FieldMapper &map, const bool applyFlip=true)
Map from the given tmp field.
void autoMap (const FieldMapper &map, const bool applyFlip=true)
Map from self.
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given field
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing)
1 to 1 reverse-map from the given tmp field
void rmap (const UList< Type > &mapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given field.
void rmap (const tmp< Field< Type >> &tmapF, const labelUList &mapAddressing, const UList< scalar > &weights)
Interpolative reverse map from the given tmp field.
void negate ()
Negate this field (negative).
tmp< Field< cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const UList< cmptType > &)
Replace a component field of the field.
void replace (const direction, const tmp< Field< cmptType >> &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
template<class VSForm >
VSForm block (const label start) const
tmp< Field< Type > > T () const
Return the field transpose (only defined for second rank tensors)
void writeEntry (const word &keyword, Ostream &os) const
Write the field as a dictionary entry.
void operator= (const Field< Type > &)
Copy assignment.
void operator= (const tmp< Field< Type >> &)
void operator= (const UList< Type > &)
void operator= (const SubField< Type > &)
void operator= (Field< Type > &&rhs)
Move assignment.
void operator= (List< Type > &&rhs)
template<int SizeMin>
void operator= (DynamicList< Type, SizeMin > &&rhs)
void operator= (const Type &val)
Value assignment.
void operator= (const zero)
template<class Form , class Cmpt , direction nCmpt>
void operator= (const VectorSpace< Form, Cmpt, nCmpt > &)
void operator+= (const UList< Type > &)
void operator+= (const tmp< Field< Type >> &)
void operator-= (const UList< Type > &)
void operator-= (const tmp< Field< Type >> &)
void operator*= (const UList< scalar > &)
void operator*= (const tmp< Field< scalar >> &)
void operator/= (const UList< scalar > &)
void operator/= (const tmp< Field< scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
template<class Type>
void operator= (const tmp< Field > &rhs)
Public Member Functions inherited from FieldBase
constexpr FieldBase () noexcept
Construct null, with refCount zero.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from List< Type >
constexpr List () noexcept
Null constructor.
List (const label len)
Construct with given size.
List (const label len, const Type &val)
Construct with given size and value for all elements.
List (const label len, const zero)
Construct with given size initializing all elements to zero.
List (const one, const Type &val)
Construct with length=1, copying the value as the only content.
List (const one, Type &&val)
Construct with length=1, moving the value as the only content.
List (const one, const zero)
Construct with length=1, initializing content to zero.
List (const List< Type > &a)
Copy construct from list.
List (const UList< Type > &a)
Copy construct contents from list.
List (List< Type > &a, bool reuse)
Construct as copy or re-use as specified.
List (const UList< Type > &list, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
List (const FixedList< Type, N > &list)
Construct as copy of FixedList<T, N>
List (const PtrList< Type > &list)
Construct as copy of PtrList<T>
List (const SLList< Type > &list)
Construct as copy of SLList<T>
List (const IndirectListBase< Type, Addr > &list)
Construct as copy of IndirectList contents.
List (std::initializer_list< Type > list)
Construct from an initializer list.
List (List< Type > &&list)
Move construct from List.
List (DynamicList< Type, SizeMin > &&list)
Move construct from DynamicList.
List (SortableList< Type > &&list)
Move construct from SortableList.
List (SLList< Type > &&list)
Move construct from SLList.
List (Istream &is)
Construct from Istream.
autoPtr< List< Type > > clone () const
Clone.
~List ()
Destructor.
void resize (const label newSize)
Adjust allocated size of list.
void resize (const label newSize, const Type &val)
Adjust allocated size of list and set val for new elements.
void setSize (const label newSize)
Alias for resize(const label)
void setSize (const label newSize, const Type &val)
Alias for resize(const label, const T&)
void clear ()
Clear the list, i.e. set size to zero.
void append (const Type &val)
Append an element at the end of the list.
void append (Type &&val)
Move append an element at the end of the list.
void append (const UList< Type > &list)
Append a List to the end of this list.
void append (const IndirectListBase< Type, Addr > &list)
Append IndirectList contents at the end of this list.
void transfer (List< Type > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (DynamicList< Type, SizeMin > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (SortableList< Type > &list)
Transfer the contents of the argument List into this list and annul the argument list.
Type & newElmt (const label i)
Return subscript-checked element of UList and resizing the list if required.
void operator= (const UList< Type > &a)
Assignment to UList operator. Takes linear time.
void operator= (const List< Type > &list)
Assignment operator. Takes linear time.
void operator= (const SLList< Type > &list)
Assignment to SLList operator. Takes linear time.
void operator= (const IndirectListBase< Type, Addr > &list)
Assignment from IndirectList. Takes linear time.
void operator= (std::initializer_list< Type > list)
Assignment to an initializer list.
void operator= (const Type &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (List< Type > &&list)
Move assignment. Takes constant time.
void operator= (DynamicList< Type, SizeMin > &&list)
Move assignment. Takes constant time.
void operator= (SortableList< Type > &&list)
Move assignment. Takes constant time.
void operator= (SLList< Type > &&list)
Move assignment. Takes constant time.
void shallowCopy (const UList< Type > &)=delete
No shallowCopy permitted.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type set (const label i, bool val=true)
A bitSet::set() method for a list of bool.
Public Member Functions inherited from UList< Type >
label size () const noexcept
The number of elements in the UList.
void writeEntry (const word &keyword, Ostream &os) const
Write the List as a dictionary entry with keyword.
void operator= (const Type &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
constexpr UList () noexcept
Null constructor.
UList (Type *__restrict__ v, label size) noexcept
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const Type & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
Type & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const Type & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
Type & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
std::streamsize byteSize () const
Return the binary size in number of characters of the UList if the element is a primitive type.
const Type * cdata () const
Return a const pointer to the first data element.
Type * data ()
Return a pointer to the first data element.
Type & first ()
Return the first element of the list.
const Type & first () const
Return first element of the list.
Type & last ()
Return the last element of the list.
const Type & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is within valid range [0,size].
void checkIndex (const label i) const
Check index is within valid range [0,size)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const Type &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const Type &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const Type &val, const label start=0) const
True if the value if found in the list.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element. Fatal on an empty list.
void swapLast (const label i)
Swap element with the last element. Fatal on an empty list.
void shallowCopy (const UList< Type > &list)
Copy the pointer held by the given UList.
void deepCopy (const UList< Type > &list)
Copy elements of the given UList.
Type & operator[] (const label i)
Return element of UList.
const Type & operator[] (const label i) const
Return element of constant UList.
UList< Type > operator[] (const labelRange &range)
Return (start,size) subset from UList with non-const access.
const UList< Type > operator[] (const labelRange &range) const
Return (start,size) subset from UList with const access.
operator const Foam::List< Type > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
bool empty () const noexcept
True if the UList is empty (ie, size() is zero)
void swap (UList< Type > &list)
Swap content with another UList of the same type in constant time.
bool operator== (const UList< Type > &a) const
Equality operation on ULists of the same type.
bool operator!= (const UList< Type > &a) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< Type > &list) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< Type > &a) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< Type > &a) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< Type > &a) const
Return true if !(a < b). Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type test (const label i) const
A bitSet::test() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type get (const label i) const
A bitSet::get() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type unset (const label i)
A bitSet::unset() method for a list of bool.
Static Public Member Functions
static const DimensionedField
< Type, GeoMesh > & null ()
Return a NullObjectRef DimensionedField.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Member Functions inherited from Field< Type >
static const Field< Type > & null ()
Return nullObject reference field.
static autoPtr< Field< Type > > New (Istream &is)
Return a pointer to a new Field created on freestore.
template<class Type2 >
static tmp< Field< Type > > NewCalculatedType (const Field< Type2 > &f)
Return a pointer to a new calculatedFvPatchFieldField created on freestore without setting patchField values.
Static Public Member Functions inherited from List< Type >
static const List< Type > & null ()
Return a null List.
Static Public Member Functions inherited from UList< Type >
static const UList< Type > & null ()
Return a UList reference to a nullObject.
static constexpr label max_size () noexcept
The size of the largest possible UList.
Friends
Ostream & operator (Ostream &os, const DimensionedField< Type, GeoMesh > &df)
Ostream & operator (Ostream &os, const tmp< DimensionedField< Type, GeoMesh >> &tdf)
Additional Inherited Members
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Public Attributes inherited from FieldBase
static const char *const typeName
Typename for Field.
static bool allowConstructFromLargerSize = false
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Protected Member Functions inherited from UList< Type >
void size (const label n) noexcept
Override size to be inconsistent with allocated storage.
void writeEntry (Ostream &os) const
Write the UList with its compound type.
labelRange validateRange (const labelRange &range) const
Return a validated (start,size) subset range, which means that it always addresses a valid section of the list.
UList< Type > & operator= (const UList< Type > &)=delete
No copy assignment (default: shallow copy)
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
template<class Type, class GeoMesh>
class Foam::DimensionedField< Type, GeoMesh >
Field with dimensions and associated with geometry type GeoMesh which is used to size the field and a reference to it is maintained.
Source files
DimensionedField.H
DimensionedFieldI.H
DimensionedField.C
DimensionedFieldIO.C
Definition at line 50 of file DimensionedField.H.
Member Typedef Documentation
typedef GeoMesh::Mesh Mesh
Type of mesh on which this DimensionedField is instantiated.
Definition at line 84 of file DimensionedField.H.
typedef Field<Type> FieldType
Type of the field from which this DimensionedField is derived.
Definition at line 89 of file DimensionedField.H.
typedef Field<Type>::cmptType cmptType
Component type of the elements of the field.
Definition at line 94 of file DimensionedField.H.
Constructor & Destructor Documentation
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensionSet & dims, const Field< Type > & field)
Construct from components.
Definition at line 64 of file DimensionedField.C.
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensionSet & dims, Field< Type > && field)
Construct from components, transferring initial field content.
Definition at line 83 of file DimensionedField.C.
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensionSet & dims, List< Type > && field)
Construct from components, transferring initial field content.
Definition at line 102 of file DimensionedField.C.
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensionSet & dims, const tmp< Field< Type >> & tfield)
Construct from components, copy or transfer tmp content.
Definition at line 121 of file DimensionedField.C.
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensionSet & dims, const bool checkIOFlags = true)
Construct from components, setting the initial size and assigning the dimensions, but not initialising any field values.
Used for temporary fields which are initialised after construction
Definition at line 141 of file DimensionedField.C.
DimensionedField (const IOobject & io, const Mesh & mesh, const dimensioned< Type > & dt, const bool checkIOFlags = true)
Construct from components, setting the initial size and assigning both dimensions and values.
The internal name for the dimensioned<Type> has no influence.
Definition at line 163 of file DimensionedField.C.
DimensionedField (const IOobject & io, const Mesh & mesh, const word & fieldDictEntry = "value")
Construct from Istream.
Definition at line 71 of file DimensionedFieldIO.C.
DimensionedField (const IOobject & io, const Mesh & mesh, const dictionary & fieldDict, const word & fieldDictEntry = "value")
Construct from dictionary.
Definition at line 89 of file DimensionedFieldIO.C.
DimensionedField (const DimensionedField< Type, GeoMesh > & df)
Copy construct.
Definition at line 185 of file DimensionedField.C.
DimensionedField (DimensionedField< Type, GeoMesh > && df)
Move construct.
Definition at line 199 of file DimensionedField.C.
DimensionedField (DimensionedField< Type, GeoMesh > & df, bool reuse)
Copy construct or reuse (move) as specified.
Definition at line 209 of file DimensionedField.C.
DimensionedField (const tmp< DimensionedField< Type, GeoMesh >> & tdf)
Construct from tmp<DimensionedField> deleting argument.
Definition at line 224 of file DimensionedField.C.
DimensionedField (const IOobject & io, const DimensionedField< Type, GeoMesh > & df)
Copy construct, resetting IO parameters.
Definition at line 236 of file DimensionedField.C.
DimensionedField (const IOobject & io, DimensionedField< Type, GeoMesh > && df)
Move construct, resetting IO parameters.
Definition at line 251 of file DimensionedField.C.
DimensionedField (const IOobject & io, DimensionedField< Type, GeoMesh > & df, bool reuse)
Copy or move construct, resetting IO parameters.
Definition at line 262 of file DimensionedField.C.
DimensionedField (const IOobject & io, const tmp< DimensionedField< Type, GeoMesh >> & tdf)
Construct from tmp<DimensionedField> deleting argument, resetting IO parameters.
Definition at line 278 of file DimensionedField.C.
DimensionedField (const word & newName, const DimensionedField< Type, GeoMesh > & df)
Copy construct with a new name.
Definition at line 291 of file DimensionedField.C.
DimensionedField (const word & newName, DimensionedField< Type, GeoMesh > && df)
Move construct with a new name.
Definition at line 306 of file DimensionedField.C.
DimensionedField (const word & newName, DimensionedField< Type, GeoMesh > & df, bool reuse)
Copy or move construct, resetting name.
Definition at line 317 of file DimensionedField.C.
DimensionedField (const word & newName, const tmp< DimensionedField< Type, GeoMesh >> & tdf)
Construct with a new name from tmp<DimensionedField>
Definition at line 333 of file DimensionedField.C.
virtual ~DimensionedField () virtual default
Destructor.
Member Function Documentation
TypeName ("DimensionedField< Type, GeoMesh >")
Runtime type information.
const Foam::DimensionedField< Type, GeoMesh > & null () inline static
Return a NullObjectRef DimensionedField.
Definition at line 26 of file DimensionedFieldI.H.
Referenced by fvFieldDecomposer::decomposeField(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), pointFieldReconstructor::reconstructField(), and basicSolidChemistryModel::RR().
Foam::tmp< Foam::DimensionedField< Type, GeoMesh > > clone () const
Clone.
Definition at line 346 of file DimensionedField.C.
void readField (const dictionary & fieldDict, const word & fieldDictEntry = "value")
Definition at line 28 of file DimensionedFieldIO.C.
References f(), and transfer().
const GeoMesh::Mesh & mesh () const inline
Return mesh.
Definition at line 34 of file DimensionedFieldI.H.
Referenced by isoSurface::adaptPatchFields(), Foam::fvc::alphaCorr(), Foam::fac::average(), Foam::fvc::average(), Foam::byDt(), Foam::cmptAv(), extendedCellToFaceStencil::collectData(), Foam::constrainPressure(), Foam::MULES::correct(), limitedSnGrad< Type >::correction(), Foam::CorrectPhi(), Foam::correctUphiBCs(), Foam::fam::d2dt2(), Foam::fvc::d2dt2(), Foam::fvm::d2dt2(), KocamustafaogullariIshii::dDeparture(), Foam::fvc::DDt(), Foam::fvm::ddt(), Foam::fam::ddt(), Foam::fvm::div(), Foam::fam::div(), Foam::fac::div(), Foam::fvc::div(), Foam::fac::edgeIntegrate(), Foam::evaluateConstraintTypes(), Foam::MULES::explicitSolve(), Cole::fDeparture(), Foam::fvc::flux(), surfaceMeshWriter::getFaceField(), Foam::fac::grad(), Foam::fvc::grad(), edgeInterpolationScheme< Type >::interpolate(), pointMVCWeight::interpolate(), pointVolInterpolation::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), Foam::interpolatePointToCell(), interpolationCellPoint< Type >::interpolationCellPoint(), Foam::fvc::laplacian(), Foam::fac::laplacian(), Foam::fvm::laplacian(), Foam::fam::laplacian(), Foam::MULES::limit(), Foam::MULES::limitCorr(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), Foam::fac::lnGrad(), lnGradScheme< Type >::lnGrad(), Foam::fam::ndiv(), Foam::fac::ndiv(), radiationModel::New(), Foam::fac::ngrad(), NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid(), multivariateIndependentScheme< Type >::operator()(), fvMatrix< Type >::operator+=(), fvMatrix< Type >::operator-=(), Foam::oversetAdjustPhi(), Foam::pow(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), parseDriver::resultType(), Foam::setRefCell(), Foam::fvc::smooth(), Foam::fvc::snGrad(), snGradScheme< Type >::snGrad(), Foam::sqr(), Foam::stabilise(), Foam::fam::Su(), Foam::fvc::surfaceIntegrate(), Foam::fvc::volumeIntegrate(), extendedUpwindCellToFaceStencil::weightedSum(), linearEdgeInterpolation< Type >::weights(), linear< Type >::weights(), harmonic::weights(), localMax< Type >::weights(), localMin< Type >::weights(), Foam::writeCellGraph(), and Foam::writePatchGraph().
const Foam::dimensionSet & dimensions () const inline
Return dimensions.
Definition at line 42 of file DimensionedFieldI.H.
Referenced by Foam::fac::average(), Foam::fvc::average(), ReynoldsStress< BasicTurbulenceModel >::boundNormalStress(), dynamicKEqn< BasicTurbulenceModel >::Ck(), Foam::cmptAv(), optionList::constrain(), correctedLnGrad< Type >::correction(), fourthLnGrad< Type >::correction(), linearUpwind< Type >::correction(), limitedLnGrad< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwindNormal< Type >::correction(), limitedSnGrad< Type >::correction(), Foam::CorrectPhi(), fvFieldDecomposer::decomposeField(), adjointEikonalSolver::distanceSensitivities(), Foam::fac::edgeIntegrate(), gaussLaplacianScheme< Type >::famLaplacian(), skewCorrectedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), edgeInterpolationScheme< Type >::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), singleCellFvMesh::interpolate(), lnGradScheme< Type >::lnGrad(), meshToMesh::mapSrcToTgt(), meshToMesh::mapTgtToSrc(), adjointMeshMovementSolver::meshMovementSensitivities(), Foam::pow(), Foam::fvc::reconstructMag(), snGradScheme< Type >::snGrad(), Foam::sqr(), Foam::stabilise(), surfMesh::storeField(), Foam::fam::Su(), and extendedUpwindCellToFaceStencil::weightedSum().
Foam::dimensionSet & dimensions () inline
Return non-const access to dimensions.
Definition at line 49 of file DimensionedFieldI.H.
const Foam::orientedType & oriented () const inline
Return oriented type.
Definition at line 57 of file DimensionedFieldI.H.
Referenced by gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), and Foam::pow().
Foam::orientedType & oriented () inline
Return non-const access to the oriented type.
Definition at line 64 of file DimensionedFieldI.H.
void setOriented (const bool oriented = true) inline
Set the oriented flag.
Definition at line 72 of file DimensionedFieldI.H.
Referenced by snGradScheme< Type >::snGrad().
const Foam::Field< Type > & field () const inline
Return field.
Definition at line 82 of file DimensionedFieldI.H.
Referenced by Foam::cmptAv(), Foam::pow(), fvFieldReconstructor::reconstructFvVolumeInternalField(), Foam::stabilise(), and Foam::fvc::volumeIntegrate().
Foam::Field< Type > & field () inline
Return field.
Definition at line 90 of file DimensionedFieldI.H.
tmp<DimensionedField<cmptType, GeoMesh> > component (const direction d) const
Return a component field of the field.
void replace (const direction d, const DimensionedField< cmptType, GeoMesh > & df)
Replace a component field of the field.
void replace (const direction d, const tmp< DimensionedField< cmptType, GeoMesh >> & tdf)
Replace a component field of the field.
Foam::tmp< Foam::DimensionedField< Type, GeoMesh > > T () const
Return the field transpose (only defined for second rank tensors)
Definition at line 419 of file DimensionedField.C.
Foam::dimensioned< Type > average () const
Calculate and return arithmetic average.
Definition at line 440 of file DimensionedField.C.
Foam::dimensioned< Type > weightedAverage (const DimensionedField< scalar, GeoMesh > & weightField) const
Calculate and return weighted average.
Definition at line 454 of file DimensionedField.C.
Foam::dimensioned< Type > weightedAverage (const tmp< DimensionedField< scalar, GeoMesh >> & tweightField) const
Calculate and return weighted average.
Definition at line 470 of file DimensionedField.C.
bool writeData (Ostream & os, const word & fieldDictEntry) const
Definition at line 110 of file DimensionedFieldIO.C.
bool writeData (Ostream &) const virtual
Pure virtual writeData function.
Must be defined in derived types
Implements regIOobject.
Reimplemented in GeometricField< Type, PatchField, GeoMesh >, GeometricField< symmTensor, fvPatchField, volMesh >, GeometricField< tensor, fvPatchField, volMesh >, GeometricField< vector, fvsPatchField, surfaceMesh >, GeometricField< scalar, fvPatchField, volMesh >, GeometricField< scalar, fvsPatchField, surfaceMesh >, GeometricField< scalar, pointPatchField, pointMesh >, GeometricField< Foam::Vector, Foam::pointPatchField, Foam::pointMesh >, GeometricField< vector, fvPatchField, volMesh >, GeometricField< scalar, Foam::pointPatchField, Foam::pointMesh >, and GeometricField< vector, pointPatchField, pointMesh >.
Definition at line 128 of file DimensionedFieldIO.C.
void operator= (const DimensionedField< Type, GeoMesh > & df)
Definition at line 484 of file DimensionedField.C.
void operator= (const tmp< DimensionedField< Type, GeoMesh >> & tdf)
Definition at line 503 of file DimensionedField.C.
void operator= (const dimensioned< Type > & dt)
Assign dimensions and value.
Definition at line 525 of file DimensionedField.C.
void operator+= (const DimensionedField< Type, GeoMesh > & df)
Definition at line 569 of file DimensionedField.C.
void operator+= (const tmp< DimensionedField< Type, GeoMesh >> & tdf)
Definition at line 569 of file DimensionedField.C.
void operator-= (const DimensionedField< Type, GeoMesh > & df)
Definition at line 570 of file DimensionedField.C.
void operator-= (const tmp< DimensionedField< Type, GeoMesh >> & tdf)
Definition at line 570 of file DimensionedField.C.
void operator*= (const DimensionedField< scalar, GeoMesh > & df)
Definition at line 571 of file DimensionedField.C.
void operator*= (const tmp< DimensionedField< scalar, GeoMesh >> & tdf)
Definition at line 571 of file DimensionedField.C.
void operator/= (const DimensionedField< scalar, GeoMesh > & df)
Definition at line 572 of file DimensionedField.C.
void operator/= (const tmp< DimensionedField< scalar, GeoMesh >> & tdf)
Definition at line 572 of file DimensionedField.C.
void operator+= (const dimensioned< Type > & dt)
Definition at line 569 of file DimensionedField.C.
void operator-= (const dimensioned< Type > & dt)
Definition at line 570 of file DimensionedField.C.
void operator*= (const dimensioned< scalar > & dt)
Definition at line 571 of file DimensionedField.C.
void operator/= (const dimensioned< scalar > & dt)
Definition at line 572 of file DimensionedField.C.
const word typeName ("volScalarField::Internal")
Referenced by ThermoPhaseModel< BasePhaseModel, ThermoType >::ThermoPhaseModel().
const word typeName ("volVectorField::Internal")
const word typeName ("volSphericalTensorField::Internal")
const word typeName ("volSymmTensorField::Internal")
const word typeName ("volTensorField::Internal")
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const DimensionedField< Type, GeoMesh > & df) friend
Ostream& operator (Ostream & os, const tmp< DimensionedField< Type, GeoMesh >> & tdf) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedField.H
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedField.C
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedFieldI.H
src/OpenFOAM/fields/DimensionedFields/DimensionedField/DimensionedFieldIO.C