OpenFOAM: rigidBodyInertia Class Reference
rigidBodyInertia Class Reference
Public Member Functions
rigidBodyInertia ()
Null constructor, initializes to zero.
rigidBodyInertia (const scalar m, const vector &c, const symmTensor &Ic)
Construct from mass, centre of mass and moment of inertia tensor.
rigidBodyInertia (const dictionary &dict)
Construct from dictionary.
rigidBodyInertia (const spatialTensor &st)
Construct from the components of a spatial tensor.
rigidBodyInertia (Istream &is)
Construct from Istream.
scalar m () const
Return the mass of the rigid-body.
const vector & c () const
Return the centre of mass of the rigid-body.
const symmTensor & Ic () const
Return the inertia tensor of the rigid-body about the centre of mass.
symmTensor Ioc () const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Icc (const vector &c) const
Return the difference between the inertia tensor of the rigid-body.
symmTensor Io () const
Return the inertia tensor of the rigid-body about the origin.
scalar kineticEnergy (const spatialVector &v)
Return the kinetic energy of the body with the given velocity.
operator spatialTensor () const
Conversion to spatial tensor.
void operator+= (const rigidBodyInertia &)
Static Public Member Functions
static symmTensor Ioc (const scalar m, const vector &c)
Return the difference between the inertia tensor of the rigid-body.
Friends
Istream & operator>> (Istream &, rigidBodyInertia &)
Ostream & operator<< (Ostream &, const rigidBodyInertia &)
Detailed Description
Definition at line 73 of file rigidBodyInertia.H.
Constructor & Destructor Documentation
rigidBodyInertia () inline
Null constructor, initializes to zero.
Definition at line 39 of file rigidBodyInertiaI.H.
References Foam::I, Foam::magSqr(), and Foam::sqr().
rigidBodyInertia (const scalar m, const vector & c, const symmTensor & Ic) inline
Construct from mass, centre of mass and moment of inertia tensor.
about the centre of mass
Definition at line 48 of file rigidBodyInertiaI.H.
rigidBodyInertia (const dictionary & dict) inline
Construct from dictionary.
Definition at line 60 of file rigidBodyInertiaI.H.
rigidBodyInertia (const spatialTensor & st) inline explicit
Construct from the components of a spatial tensor.
Definition at line 68 of file rigidBodyInertiaI.H.
rigidBodyInertia (Istream & is) inline explicit
Construct from Istream.
Definition at line 76 of file rigidBodyInertiaI.H.
Member Function Documentation
Foam::symmTensor Ioc (const scalar m, const vector & c) inline static
Return the difference between the inertia tensor of the rigid-body.
about the origin - about the centre of mass for the given mass and centre of mass
Definition at line 28 of file rigidBodyInertiaI.H.
Foam::scalar m () const inline
Return the mass of the rigid-body.
Definition at line 86 of file rigidBodyInertiaI.H.
Referenced by Foam::RBD::operator+(), and Foam::RBD::transform().
const Foam::vector & c () const inline
Return the centre of mass of the rigid-body.
Definition at line 91 of file rigidBodyInertiaI.H.
Referenced by Foam::RBD::transform().
const Foam::symmTensor & Ic () const inline
Return the inertia tensor of the rigid-body about the centre of mass.
Definition at line 96 of file rigidBodyInertiaI.H.
Referenced by Foam::RBD::transform().
Foam::symmTensor Ioc () const inline
Return the difference between the inertia tensor of the rigid-body.
about the origin - about the centre of mass
Definition at line 101 of file rigidBodyInertiaI.H.
Foam::symmTensor Icc (const vector & c) const inline
Return the difference between the inertia tensor of the rigid-body.
about the a new centre of mass - about the current centre of mass
Definition at line 106 of file rigidBodyInertiaI.H.
Foam::symmTensor Io () const inline
Return the inertia tensor of the rigid-body about the origin.
Definition at line 111 of file rigidBodyInertiaI.H.
Foam::scalar kineticEnergy (const spatialVector & v) inline
Return the kinetic energy of the body with the given velocity.
Definition at line 234 of file rigidBodyInertiaI.H.
operator spatialTensor () const inline
Conversion to spatial tensor.
Definition at line 119 of file rigidBodyInertiaI.H.
void operator+= (const rigidBodyInertia & rbi) inline
Definition at line 245 of file rigidBodyInertiaI.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & , rigidBodyInertia &) friend
Ostream& operator<< (Ostream & , const rigidBodyInertia &) friend
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyInertia/rigidBodyInertia.H
src/rigidBodyDynamics/rigidBodyInertia/rigidBodyInertiaI.H