OpenFOAM: error Class Reference
error Class Reference
Class to handle errors and exceptions in a simple, consistent stream-based manner.
Public Member Functions
error (const string &title)
Construct from title string.
error (const dictionary &errDict)
Construct from dictionary.
error (const error &err)
Construct as copy.
virtual ~error () throw ()
Destructor.
string message () const
void clear () const
Clear any messages.
const string & functionName () const
const string & sourceFileName () const
label sourceFileLineNumber () const
bool throwing () const
Return the current exception throwing (on or off)
bool throwExceptions (bool doThrow)
Activate/deactivate exception throwing.
bool throwExceptions ()
Activate exception throwing.
bool dontThrowExceptions ()
Deactivate exception throwing.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
operator dictionary () const
Create and return a dictionary representation of the error.
void exit (const int errNo=1)
Exit : can be called for any error to exit program.
void abort ()
Abort : used to stop code for fatal errors.
void write (Ostream &os, const bool includeTitle=true) const
Print error message.
Public Member Functions inherited from messageStream
messageStream (const string &title, const errorSeverity severity, const int maxErrors=0)
Construct from components.
messageStream (const dictionary &dict)
Construct as Fatal from dictionary, extracting the 'title'.
const string & title () const
Return the title of this error type.
int maxErrors () const
Return the maximum number of errors before program termination.
int & maxErrors ()
Return non-const access to the maximum number of errors before.
OSstream & masterStream (const label communicator)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const string &functionName, const char *sourceFileName, const int sourceFileLineNumber=0)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const string &ioFileName, const label ioStartLineNumber=-1, const label ioEndLineNumber=-1)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const IOstream &)
Convert to OSstream.
OSstream & operator() (const char *functionName, const char *sourceFileName, const int sourceFileLineNumber, const dictionary &)
Convert to OSstream.
operator OSstream & ()
Convert to OSstream for << operations.
OSstream & operator() ()
Explicitly convert to OSstream for << operations.
Static Public Member Functions
static void warnAboutAge (const char *what, const int version)
Emit warning on stderr about something being old.
static void safePrintStack (std::ostream &os)
Helper function to print a stack, used when OpenFOAM IO not yet initialised.
static void printStack (Ostream &os)
Helper function to print a stack.
Protected Attributes
string functionName_
string sourceFileName_
label sourceFileLineNumber_
bool throwExceptions_
OStringStream * messageStreamPtr_
Protected Attributes inherited from messageStream
string title_
errorSeverity severity_
int maxErrors_
int errorCount_
Additional Inherited Members
Public Types inherited from messageStream
enum errorSeverity {
INFO = 1, WARNING, SERIOUS, FATAL,
INFO_STDERR = INFO | 0x10
}
Message type, or error severity flags.
Static Public Attributes inherited from messageStream
static int level
Controls the output verbosity of messageStream.
Detailed Description
Class to handle errors and exceptions in a simple, consistent stream-based manner.
The error class is globally instantiated with a title string. Errors, messages and other data are piped to the messageStream class in the standard manner. Manipulators are supplied for exit and abort that may terminate the program or throw an exception depending on whether the exception handling has been switched on (off by default).
Usage
error << "message1" << "message2" << FoamDataType << exit(errNo);
error << "message1" << "message2" << FoamDataType << abort();
Source files
error.H
error.C
Definition at line 60 of file error.H.
Constructor & Destructor Documentation
error (const string & title) explicit
Construct from title string.
Definition at line 68 of file error.C.
error (const dictionary & errDict) explicit
Construct from dictionary.
Definition at line 88 of file error.C.
error (const error & err)
Construct as copy.
Definition at line 109 of file error.C.
~error () throw () virtual
Destructor.
Definition at line 125 of file error.C.
Member Function Documentation
void warnAboutAge (const char * what, const int version) static
Emit warning on stderr about something being old.
Parameters
what description for the warning
version is the old version (YYMM) for determining the age in months compared to the current OpenFOAM version as conveyed by the foamVersion::api value.
Definition at line 33 of file error.C.
References Foam::foamVersion::api, and Foam::endl().
Foam::string message () const
Definition at line 197 of file error.C.
void clear () const
Clear any messages.
Definition at line 203 of file error.C.
const string& functionName () const inline
Definition at line 126 of file error.H.
const string& sourceFileName () const inline
Definition at line 131 of file error.H.
label sourceFileLineNumber () const inline
Definition at line 136 of file error.H.
bool throwing () const inline
Return the current exception throwing (on or off)
Definition at line 144 of file error.H.
bool throwExceptions (bool doThrow) inline
Activate/deactivate exception throwing.
Returns
the previous throwing state
Definition at line 154 of file error.H.
References error::throwExceptions().
Referenced by if().
bool throwExceptions () inline
Activate exception throwing.
Returns
the previous throwing state
Definition at line 166 of file error.H.
Referenced by error::throwExceptions().
bool dontThrowExceptions () inline
Deactivate exception throwing.
Returns
the previous throwing state
Definition at line 176 of file error.H.
Foam::OSstream & operator() (const char * functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 134 of file error.C.
Foam::OSstream & operator() (const string & functionName, const char * sourceFileName, const int sourceFileLineNumber = 0)
Convert to OSstream.
Prints basic message and returns OSstream for further info.
Definition at line 149 of file error.C.
operator OSstream & ()
Convert to OSstream.
Prints basic message and returns OSstream for further info.
OSstream& operator() () inline
Explicitly convert to OSstream for << operations.
Definition at line 215 of file error.H.
References IOerror::ioEndLineNumber(), IOerror::IOerror(), IOerror::ioFileName(), IOerror::ioStartLineNumber(), messageStream::title(), and IOerror::~IOerror().
operator dictionary () const
Create and return a dictionary representation of the error.
void safePrintStack (std::ostream & os) static
Helper function to print a stack, used when OpenFOAM IO not yet initialised.
Definition at line 25 of file dummyPrintStack.C.
void printStack (Ostream & os) static
Helper function to print a stack.
Definition at line 29 of file dummyPrintStack.C.
Referenced by Foam::reduce().
void exit (const int errNo = 1)
Exit : can be called for any error to exit program.
Prints stack before exiting, when FOAM_ABORT is on.
Definition at line 209 of file error.C.
Referenced by Foam::abort().
void abort ()
Abort : used to stop code for fatal errors.
Prints stack before exiting.
Definition at line 246 of file error.C.
Referenced by Foam::exit().
void write (Ostream & os, const bool includeTitle = true) const
Print error message.
Definition at line 293 of file error.C.
Member Data Documentation
string functionName_ protected
Definition at line 70 of file error.H.
string sourceFileName_ protected
Definition at line 71 of file error.H.
label sourceFileLineNumber_ protected
Definition at line 72 of file error.H.
bool throwExceptions_ protected
Definition at line 74 of file error.H.
OStringStream* messageStreamPtr_ protected
Definition at line 75 of file error.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/error/error.H
src/OpenFOAM/db/error/error.C
src/OSspecific/POSIX/printStack/dummyPrintStack.C
src/OSspecific/POSIX/printStack/printStack.C