OpenFOAM: wallLubricationModel Class Reference
wallLubricationModel Class Reference abstract
Public Member Functions
TypeName ("wallLubricationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, wallLubricationModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallLubricationModel (const dictionary &dict, const phasePair &pair)
Construct from components.
virtual ~wallLubricationModel ()
Destructor.
virtual tmp< volVectorField > Fi () const =0
Return phase-intensive wall lubrication force.
virtual tmp< volVectorField > F () const
Return wall lubrication force.
virtual tmp< surfaceScalarField > Ff () const
Return face wall lubrication force.
TypeName ("wallLubricationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, wallLubricationModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallLubricationModel (const dictionary &dict, const phasePair &pair)
Construct from components.
virtual ~wallLubricationModel ()
Destructor.
virtual tmp< volVectorField > Fi () const =0
Return phase-intensive wall lubrication force.
virtual tmp< volVectorField > F () const
Return wall lubrication force.
virtual tmp< surfaceScalarField > Ff () const
Return face wall lubrication force.
Public Member Functions inherited from wallDependentModel
wallDependentModel (const fvMesh &mesh)
Construct from a mesh.
virtual ~wallDependentModel ()
Destructor.
const volScalarField & yWall () const
const volVectorField & nWall () const
wallDependentModel (const fvMesh &mesh)
Construct from a mesh.
virtual ~wallDependentModel ()
Destructor.
const volScalarField & yWall () const
const volVectorField & nWall () const
Static Public Member Functions
static autoPtr
< wallLubricationModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr
< wallLubricationModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimF
Coefficient dimensions.
Protected Member Functions
tmp< volVectorField > zeroGradWalls (tmp< volVectorField >) const
Zero-gradient wall-lubrication force at walls.
Protected Attributes
const phasePair & pair_
Phase pair.
Detailed Description
Source files
wallLubricationModel.H
wallLubricationModel.C
newWallLubricationModel.C
Source files
wallLubricationModel.H
wallLubricationModel.C
newWallLubricationModel.C
Definition at line 51 of file wallLubricationModel.H.
Constructor & Destructor Documentation
wallLubricationModel (const dictionary & dict, const phasePair & pair)
Construct from components.
Definition at line 68 of file wallLubricationModel.C.
~wallLubricationModel () virtual
Destructor.
Definition at line 80 of file wallLubricationModel.C.
wallLubricationModel (const dictionary & dict, const phasePair & pair)
Construct from components.
virtual ~wallLubricationModel () virtual
Destructor.
Member Function Documentation
Foam::tmp< Foam::volVectorField > zeroGradWalls (tmp< volVectorField > tFi) const protected
Zero-gradient wall-lubrication force at walls.
Definition at line 43 of file wallLubricationModel.C.
TypeName ("wallLubricationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , wallLubricationModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::wallLubricationModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 28 of file newWallLubricationModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volVectorField> Fi () const pure virtual
Return phase-intensive wall lubrication force.
Implemented in Frank, Frank, TomiyamaWallLubrication, TomiyamaWallLubrication, Antal, Antal, noWallLubrication, and noWallLubrication.
Foam::tmp< Foam::volVectorField > F () const virtual
Return wall lubrication force.
Reimplemented in noWallLubrication, and noWallLubrication.
Definition at line 86 of file wallLubricationModel.C.
Foam::tmp< Foam::surfaceScalarField > Ff () const virtual
Return face wall lubrication force.
Definition at line 92 of file wallLubricationModel.C.
TypeName ("wallLubricationModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , wallLubricationModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
static autoPtr<wallLubricationModel> New (const dictionary & dict, const phasePair & pair) static
virtual tmp<volVectorField> Fi () const pure virtual
Return phase-intensive wall lubrication force.
Implemented in Frank, Frank, TomiyamaWallLubrication, TomiyamaWallLubrication, Antal, Antal, noWallLubrication, and noWallLubrication.
virtual tmp<volVectorField> F () const virtual
Return wall lubrication force.
Reimplemented in noWallLubrication, and noWallLubrication.
virtual tmp<surfaceScalarField> Ff () const virtual
Return face wall lubrication force.
Member Data Documentation
const phasePair & pair_ protected
Phase pair.
Definition at line 62 of file wallLubricationModel.H.
static const dimensionSet dimF static
Coefficient dimensions.
Definition at line 101 of file wallLubricationModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialModels/wallLubricationModels/wallLubricationModel/wallLubricationModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/interfacialModels/wallLubricationModels/wallLubricationModel/wallLubricationModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialModels/wallLubricationModels/wallLubricationModel/newWallLubricationModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialModels/wallLubricationModels/wallLubricationModel/wallLubricationModel.C