OpenFOAM: convectionScheme< Type > Class Template Reference
convectionScheme< Type > Class Template Reference abstract
Abstract base class for finite area calculus convection schemes.
Public Member Functions
declareRunTimeSelectionTable (tmp, convectionScheme, Istream,(const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
convectionScheme (const faMesh &mesh, const edgeScalarField &faceFlux)
Construct from mesh, flux and Istream.
virtual ~convectionScheme ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, faePatchField,
edgeMesh > > flux (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const =0
virtual tmp< faMatrix< Type > > famDiv (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const =0
virtual tmp< GeometricField
< Type, faPatchField, areaMesh > > facDiv (const edgeScalarField &, const GeometricField< Type, faPatchField, areaMesh > &) const =0
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< convectionScheme
< Type > > New (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData)
Return a pointer to a new convectionScheme created on freestore.
Detailed Description
template<class Type>
class Foam::fa::convectionScheme< Type >
Abstract base class for finite area calculus convection schemes.
Source files
faConvectionScheme.H
faConvectionScheme.C
Definition at line 61 of file faConvectionScheme.H.
Constructor & Destructor Documentation
convectionScheme (const faMesh & mesh, const edgeScalarField & faceFlux) inline
Construct from mesh, flux and Istream.
Definition at line 107 of file faConvectionScheme.H.
~convectionScheme () virtual
Destructor.
Definition at line 74 of file faConvectionScheme.C.
Member Function Documentation
declareRunTimeSelectionTable (tmp , convectionScheme< Type > , Istream , (const faMesh &mesh, const edgeScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
Foam::tmp< Foam::fa::convectionScheme< Type > > New (const faMesh & mesh, const edgeScalarField & faceFlux, Istream & schemeData) static
Return a pointer to a new convectionScheme created on freestore.
Definition at line 30 of file faConvectionScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and Foam::nl.
Referenced by Foam::fam::div(), and Foam::fam::ndiv().
const faMesh& mesh () const inline
Return mesh reference.
Definition at line 140 of file faConvectionScheme.H.
virtual tmp<GeometricField<Type, faePatchField, edgeMesh> > flux (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >.
virtual tmp<faMatrix<Type> > famDiv (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >.
virtual tmp<GeometricField<Type, faPatchField, areaMesh> > facDiv (const edgeScalarField & , const GeometricField< Type, faPatchField, areaMesh > &) const pure virtual
Implemented in gaussConvectionScheme< Type >.
The documentation for this class was generated from the following files:
src/finiteArea/finiteArea/convectionSchemes/faConvectionScheme/faConvectionScheme.H
src/finiteArea/finiteArea/convectionSchemes/faConvectionScheme/faConvectionScheme.C