OpenFOAM: IOobjectList Class Reference
IOobjectList Class Reference
List of IOobjects with searching and retrieving facilities.
Public Member Functions
IOobjectList ()
Construct null with default (128) table capacity.
IOobjectList (const label nObjects)
Construct given initial table capacity.
IOobjectList (const IOobjectList &list)
Copy construct.
IOobjectList (IOobjectList &&list)
Move construct.
IOobjectList (const objectRegistry &db, const fileName &instance, const fileName &local="", IOobject::readOption r=IOobject::MUST_READ, IOobject::writeOption w=IOobject::NO_WRITE, bool registerObject=true)
Construct from objectRegistry and instance path.
~IOobjectList ()=default
Destructor.
bool add (autoPtr< IOobject > &objectPtr)
Add IOobject to the list.
bool add (autoPtr< IOobject > &&objectPtr)
Add IOobject to the list.
label append (const IOobjectList &other)
Copy append objects from other to this list, but do not overwrite existing keys.
label append (IOobjectList &&other)
Move append objects from other to this list, but do not overwrite existing keys.
bool remove (const IOobject &io)
Remove IOobject from the list.
const IOobject * cfindObject (const word &objName) const
Return const pointer to the object found by name.
template<class Type >
const IOobject * cfindObject (const word &objName) const
Return const pointer to the object found by name that also has headerClassName == Type::typeName.
const IOobject * findObject (const word &objName) const
Return const pointer to the object found by name.
template<class Type >
const IOobject * findObject (const word &objName) const
Return const pointer to the object found by name that also has headerClassName == Type::typeName.
IOobject * findObject (const word &objName)
Return non-const pointer to the object found by name.
template<class Type >
IOobject * findObject (const word &objName)
Return non-const pointer to the object found by name that also has headerClassName == Type::typeName.
IOobject * getObject (const word &objName) const
Return non-const pointer to the object found by name, using a const-cast to have it behave like a mutable.
template<class Type >
IOobject * getObject (const word &objName) const
Return non-const pointer to the object found by name that also has headerClassName == Type::typeName, using a const-cast to have it behave like a mutable.
template<class MatchPredicate >
IOobjectList lookup (const MatchPredicate &matchName) const
The list of IOobjects that have a matching object name.
IOobjectList lookupClass (const char *clsName) const
The list of IOobjects with the given headerClassName.
template<class MatchPredicate >
IOobjectList lookupClass (const MatchPredicate &matchClass) const
The list of IOobjects with matching headerClassName.
template<class MatchPredicate1 , class MatchPredicate2 >
IOobjectList lookupClass (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
The list of IOobjects with matching headerClassName that also have a matching object name.
template<class Type >
IOobjectList lookupClass () const
The list of IOobjects with headerClassName == Type::typeName.
template<class Type , class MatchPredicate >
IOobjectList lookupClass (const MatchPredicate &matchName) const
The list of IOobjects with headerClassName == Type::typeName that also have a matching object name.
HashTable< wordHashSet > classes () const
A summary hash of classes used and their associated object names.
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
A summary hash of classes used and their associated object names, restricted to objects that have a matching object name.
label count (const char *clsName) const
The number of objects of the given headerClassName.
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
The number of objects of the given headerClassName.
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
The number of objects of the given headerClassName that also have a matching object name.
template<class Type >
label count () const
The number of objects with headerClassName == Type::typeName.
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
The number of objects with headerClassName == Type::typeName that also have a matching object name.
wordList names () const
The names of the IOobjects.
wordList names (const bool syncPar) const
The names of the IOobjects.
wordList names (const char *clsName) const
The names of IOobjects with the given headerClassName.
wordList names (const char *clsName, const bool syncPar) const
The names of the IOobjects with the given headerClassName.
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
The names of IOobjects with the given headerClassName.
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass, const bool syncPar) const
The names of the IOobjects with the given headerClassName.
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
The names of IOobjects with the given headerClassName that also have a matching object name.
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
The names of the IOobjects with the given headerClassName that also have a matching object name.
template<class Type >
wordList names () const
The names of objects with headerClassName == Type::typeName.
template<class Type >
wordList names (bool syncPar) const
The names of objects with headerClassName == Type::typeName.
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
The names of objects with headerClassName == Type::typeName that also have a matching object name.
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName, const bool syncPar) const
The names of objects with headerClassName == Type::typeName that also have a matching object name.
wordList sortedNames () const
The sorted names of the IOobjects.
wordList sortedNames (const bool syncPar) const
The sorted names of the IOobjects.
wordList sortedNames (const char *clsName) const
The sorted names of IOobjects with the given headerClassName.
wordList sortedNames (const char *clsName, const bool syncPar) const
The sorted names of the IOobjects with the given headerClassName.
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
The sorted names of IOobjects with the given headerClassName.
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass, const bool syncPar) const
The sorted names of the IOobjects with the given headerClassName.
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
The sorted names of IOobjects with the given headerClassName that also have a matching object name.
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
The sorted names of the IOobjects with the given headerClassName that also have a matching object name.
template<class Type >
wordList sortedNames () const
The sorted names of objects with headerClassName == Type::typeName.
template<class Type >
wordList sortedNames (bool syncPar) const
The sorted names of objects with headerClassName == Type::typeName.
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
The sorted names of objects with headerClassName == Type::typeName that also have a matching object name.
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName, const bool syncPar) const
The sorted names of objects with headerClassName == Type::typeName that also have a matching object name.
template<class UnaryPredicate >
label filterClasses (const UnaryPredicate &pred, const bool pruning=false)
Filter to retain or prune given classes.
template<class UnaryPredicate >
label filterObjects (const UnaryPredicate &pred, const bool pruning=false)
Filter to retain or prune given object names.
label prune_0 ()
Remove objects with names ending with "_0" (restart fields)
wordList allNames () const
The sorted names of all objects (synchronised across processors)
template<class Type >
wordList allNames () const
The sorted names of all objects (synchronised across processors) with headerClassName == Type::typeName.
bool checkNames (const bool syncPar=true) const
Verify that object names are synchronised across processors.
void operator= (const IOobjectList &)=delete
No copy assignment.
void operator= (IOobjectList &&list)
Move assignment.
IOobject * lookup (const char *objName) const
Deprecated(2018-11) Locate an object by name (c-string). Disambiguated from multiple-lookup version by calling parameter.
IOobject * lookup (const word &objName) const
Deprecated(2018-11) Locate an object by name (const word&). Disambiguated from multiple-lookup version by calling parameter.
template<class MatchPredicate >
Foam::HashTable
< Foam::wordHashSet > classesImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const IOobjectList &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const IOobjectList &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const IOobjectList &list, const MatchPredicate &matchName, const bool doSort)
template<class MatchPredicate >
Foam::IOobjectList lookupImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::IOobjectList lookupClassImpl (const IOobjectList &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::IOobjectList lookupClassTypeImpl (const IOobjectList &list, const MatchPredicate &matchName)
template<class MatchPredicate >
Foam::IOobjectList lookup (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::IOobjectList lookupClass (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::IOobjectList lookupClass (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::IOobjectList lookupClass () const
template<class Type , class MatchPredicate >
Foam::IOobjectList lookupClass (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::HashTable
< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type >
Foam::label count () const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass, const bool syncPar) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName, const bool syncPar) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass, const bool syncPar) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool syncPar) const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName, const bool syncPar) const
template<class UnaryPredicate >
Foam::label filterClasses (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterObjects (const UnaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashPtrTable< IOobject >
HashPtrTable ()
Construct null with default table capacity.
HashPtrTable (const label size)
Construct given initial table capacity.
HashPtrTable (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
HashPtrTable (Istream &is)
Construct from Istream using default Istream constructor class.
HashPtrTable (const dictionary &dict)
Construct from dictionary with default dictionary constructor class.
HashPtrTable (const this_type &ht)
Copy construct.
HashPtrTable (this_type &&ht)
Move construct.
~HashPtrTable ()
Destructor.
autoPtr< IOobject > remove (iterator &iter)
Remove entry specified by given iterator.
autoPtr< IOobject > remove (const Key &key)
Remove entry specified by given key.
bool erase (iterator &iter)
Erase entry specified by given iterator and delete the allocated pointer.
bool erase (const Key &key)
Erase entry specified by given key and delete the allocated pointer.
void clear ()
Clear all entries from table and delete any allocated pointers.
void write (Ostream &os) const
Write.
void operator= (const this_type &rhs)
Copy assignment.
void operator= (this_type &&rhs)
Move assignment.
bool insert (const Key &, IOobject *)=delete
No insert() with raw pointers (potential memory leaks). Use insert() with autoPtr or set()
bool insert (const Key &key, autoPtr< IOobject > &aptr)
Insert a new entry, not overwriting existing entries.
bool insert (const Key &key, autoPtr< IOobject > &&aptr)
Insert a new entry, not overwriting existing entries.
bool set (const Key &key, IOobject *ptr)
Assign a new entry, overwriting existing entries.
bool set (const Key &key, autoPtr< IOobject > &aptr)
Assign a new entry, overwriting existing entries.
bool set (const Key &key, autoPtr< IOobject > &&aptr)
Assign a new entry, overwriting existing entries.
Public Member Functions inherited from HashTable< T, Key, Hash >
HashTable ()
Construct null with default (128) table capacity.
HashTable (const label size)
Construct given initial table capacity.
HashTable (Istream &is, const label size=128)
Construct from Istream with default table capacity.
HashTable (const this_type &ht)
Copy construct.
HashTable (this_type &&rhs)
Move construct.
HashTable (std::initializer_list< std::pair< Key, T >> list)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const noexcept
The size of the underlying table.
label size () const noexcept
The number of elements in table.
bool empty () const noexcept
True if the hash table is empty.
T & at (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const T & at (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
bool found (const Key &key) const
Return true if hashed entry is found in table.
iterator find (const Key &key)
Find and return an iterator set at the hashed entry.
const_iterator find (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const_iterator cfind (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const T & lookup (const Key &key, const T &deflt) const
Return hashed entry if it exists, or return the given default.
List< Key > toc () const
The table of contents (the keys) in unsorted order.
List< Key > sortedToc () const
The table of contents (the keys) in sorted order.
template<class Compare >
List< Key > sortedToc (const Compare &comp) const
The table of contents (the keys) sorted according to the specified comparator.
template<class UnaryPredicate >
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the keys.
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the values.
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the binary predicate applied to the keys and values.
template<class UnaryPredicate >
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Count the number of keys that satisfy the unary predicate.
template<class UnaryPredicate >
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Count the number of values that satisfy the unary predicate.
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Count the number of entries that satisfy the binary predicate.
template<class... Args>
bool emplace (const Key &key, Args &&...args)
Emplace insert a new entry, not overwriting existing entries.
bool insert (const Key &key, const T &obj)
Copy insert a new entry, not overwriting existing entries.
bool insert (const Key &key, T &&obj)
Move insert a new entry, not overwriting existing entries.
bool set (const Key &key, const T &obj)
Copy assign a new entry, overwriting existing entries.
bool set (const Key &key, T &&obj)
Move assign a new entry, overwriting existing entries.
bool erase (const iterator &iter)
Erase an entry specified by given iterator.
bool erase (const Key &key)
Erase an entry specified by the given key.
template<class AnyType , class AnyHash >
label erase (const HashTable< AnyType, Key, AnyHash > &other)
Remove table entries given by keys of the other hash-table.
label erase (std::initializer_list< Key > keys)
Remove table entries given by the listed keys.
template<class InputIter >
label erase (InputIter first, InputIter last)
Remove multiple entries using an iterator range of keys.
template<unsigned N>
label erase (const FixedList< Key, N > &keys)
Remove table entries given by the listed keys.
label erase (const UList< Key > &keys)
Remove table entries given by the listed keys.
template<class AnyType , class AnyHash >
label retain (const HashTable< AnyType, Key, AnyHash > &other)
Retain table entries given by keys of the other hash-table.
template<class UnaryPredicate >
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their keys.
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their values.
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their key/value.
void resize (const label sz)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void swap (HashTable< T, Key, Hash > &rhs)
Swap contents into this table.
void transfer (HashTable< T, Key, Hash > &rhs)
Transfer contents into this table.
T & operator[] (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const T & operator[] (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
T & operator() (const Key &key)
Return existing entry or create a new entry.
T & operator() (const Key &key, const T &deflt)
Return existing entry or insert a new entry.
void operator= (const this_type &rhs)
Copy assign.
void operator= (std::initializer_list< std::pair< Key, T >> rhs)
Copy assign from an initializer list.
void operator= (this_type &&rhs)
Move assign.
bool operator== (const this_type &rhs) const
Equality. Tables are equal if all keys and values are equal, independent of order or underlying storage size.
bool operator!= (const this_type &rhs) const
The opposite of the equality operation.
this_type & operator+= (const this_type &rhs)
Add entries into this HashTable.
const_iterator_pair
< const_key_iterator,
this_type > keys () const
A const iterator begin/end pair for iterating over keys.
iterator begin ()
iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const iterator & end ()
iterator to signal the end for any HashTable
const const_iterator & end () const
const_iterator to signal the end for any HashTable
const const_iterator & cend () const
const_iterator to signal the end for any HashTable
Ostream & printInfo (Ostream &os) const
Print information.
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
template<class Compare >
Foam::List< Key > sortedToc (const Compare &comp) const
template<class UnaryPredicate >
Foam::List< Key > tocKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::List< Key > tocValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::List< Key > tocEntries (const BinaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countKeys (const UnaryPredicate &pred, const bool invert) const
template<class UnaryPredicate >
Foam::label countValues (const UnaryPredicate &pred, const bool invert) const
template<class BinaryPredicate >
Foam::label countEntries (const BinaryPredicate &pred, const bool invert) const
template<class InputIter>
Foam::label erase (InputIter first, InputIter last)
template<unsigned N>
Foam::label erase (const FixedList< Key, N > &keys)
template<class AnyType, class AnyHash >
Foam::label erase (const HashTable< AnyType, Key, AnyHash > &other)
template<class AnyType , class AnyHash >
Foam::label retain (const HashTable< AnyType, Key, AnyHash > &other)
template<class UnaryPredicate >
Foam::label filterKeys (const UnaryPredicate &pred, const bool pruning)
template<class UnaryPredicate >
Foam::label filterValues (const UnaryPredicate &pred, const bool pruning)
template<class BinaryPredicate >
Foam::label filterEntries (const BinaryPredicate &pred, const bool pruning)
Public Member Functions inherited from HashTableCore
HashTableCore ()=default
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Public Types inherited from HashPtrTable< IOobject >
typedef HashPtrTable< IOobject,
Key, Hash > this_type
The template instance used for this table.
typedef HashTable< IOobject
*, Key, Hash > parent_type
The template instance used for the parent HashTable.
using iterator = typename parent_type::iterator
using const_iterator = typename parent_type::const_iterator
Public Types inherited from HashTable< T, Key, Hash >
typedef HashTable< T, Key, Hash > this_type
The template instance used for this HashTable.
typedef Key key_type
The second template parameter, type of keys used.
typedef T mapped_type
The first template parameter, type of objects contained.
typedef T value_type
Same as mapped_type for OpenFOAM HashTables.
typedef Hash hasher
The third template parameter, the hash index method.
typedef T & reference
Reference to the stored value_type.
typedef const T & const_reference
Const reference to the stored value_type.
typedef label difference_type
The type to represent the difference between two iterators.
typedef label size_type
The type that can represent the size of a HashTable.
using key_iterator = key_iterator_base< iterator >
Forward iterator returning the key.
using const_key_iterator = key_iterator_base< const_iterator >
Forward const iterator returning the key.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Return a canonical (power-of-two) of the requested size.
template<class IteratorType , class TableType >
static IteratorType iterator_begin (TableType &table)
Factory method to create a non-const iterator begin.
template<class IteratorType , class TableType >
static IteratorType iterator_cbegin (const TableType &table)
Factory method to create a const iterator begin.
template<class IteratorType >
static const IteratorType & iterator_end ()
Factory method to return an iterator end.
template<class IteratorType >
static const IteratorType & iterator_cend ()
Factory method to return an iterator cend.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable internal table size. Approximately labelMax/4.
Protected Member Functions inherited from HashTable< T, Key, Hash >
bool iterator_erase (node_type *&entry, label &index)
Low-level entry erasure using iterator internals.
Detailed Description
List of IOobjects with searching and retrieving facilities.
Source files
IOobjectList.H
IOobjectList.C
IOobjectListTemplates.C
Definition at line 51 of file IOobjectList.H.
Constructor & Destructor Documentation
IOobjectList ()
Construct null with default (128) table capacity.
Definition at line 74 of file IOobjectList.C.
IOobjectList (const label nObjects) explicit
Construct given initial table capacity.
Definition at line 80 of file IOobjectList.C.
IOobjectList (const IOobjectList & list)
Copy construct.
Definition at line 86 of file IOobjectList.C.
IOobjectList (IOobjectList && list)
Move construct.
Definition at line 92 of file IOobjectList.C.
IOobjectList (const objectRegistry & db, const fileName & instance, const fileName & local = "", IOobject::readOption r = IOobject::MUST_READ, IOobject::writeOption w = IOobject::NO_WRITE, bool registerObject = true)
Construct from objectRegistry and instance path.
Definition at line 99 of file IOobjectList.C.
~IOobjectList () default
Destructor.
Member Function Documentation
bool add (autoPtr< IOobject > & objectPtr)
Add IOobject to the list.
Definition at line 157 of file IOobjectList.C.
bool add (autoPtr< IOobject > && objectPtr)
Add IOobject to the list.
Definition at line 168 of file IOobjectList.C.
Foam::label append (const IOobjectList & other)
Copy append objects from other to this list, but do not overwrite existing keys.
Returns
number of items added
Definition at line 179 of file IOobjectList.C.
Foam::label append (IOobjectList && other)
Move append objects from other to this list, but do not overwrite existing keys.
After calling this, the other parameter will contains any items that could not be moved.
Returns
number of items added
Definition at line 201 of file IOobjectList.C.
bool remove (const IOobject & io)
Remove IOobject from the list.
Returns
True if object was removed
Definition at line 229 of file IOobjectList.C.
const Foam::IOobject * cfindObject (const word & objName) const
Return const pointer to the object found by name.
Returns
IOobject ptr if found else nullptr
Definition at line 238 of file IOobjectList.C.
const IOobject* cfindObject (const word & objName) const
Return const pointer to the object found by name that also has headerClassName == Type::typeName.
Returns
IOobject ptr if found and the correct type, else nullptr
Note
If Type is void, no headerClassName check is used (always true).
const Foam::IOobject * findObject (const word & objName) const
Return const pointer to the object found by name.
Returns
IOobject ptr if found else nullptr
Definition at line 263 of file IOobjectList.C.
Referenced by Foam::writeDimFields(), and Foam::writeVolFields().
const IOobject* findObject (const word & objName) const
Return const pointer to the object found by name that also has headerClassName == Type::typeName.
Returns
IOobject ptr if found and the correct type, else nullptr
Note
If Type is void, no headerClassName check is used (always true).
Foam::IOobject * findObject (const word & objName)
Return non-const pointer to the object found by name.
Returns
IOobject ptr if found else nullptr
Definition at line 271 of file IOobjectList.C.
IOobject* findObject (const word & objName)
Return non-const pointer to the object found by name that also has headerClassName == Type::typeName.
Returns
IOobject ptr if found and the correct type, else nullptr
Note
If Type is void, no headerClassName check is used (always true).
Foam::IOobject * getObject (const word & objName) const
Return non-const pointer to the object found by name, using a const-cast to have it behave like a mutable.
Exercise caution when using.
Returns
IOobject ptr if found else nullptr
Definition at line 277 of file IOobjectList.C.
IOobject* getObject (const word & objName) const
Return non-const pointer to the object found by name that also has headerClassName == Type::typeName, using a const-cast to have it behave like a mutable.
Exercise caution when using.
Returns
IOobject ptr if found and the correct type, else nullptr
Note
If Type is void, no headerClassName check is used (always true).
IOobjectList lookup (const MatchPredicate & matchName) const
The list of IOobjects that have a matching object name.
Foam::IOobjectList lookupClass (const char * clsName) const
The list of IOobjects with the given headerClassName.
Definition at line 283 of file IOobjectList.C.
Referenced by Foam::MapConsistentVolFields(), Foam::MapLagrangianFields(), Foam::MapVolFields(), and Foam::UnMapped().
IOobjectList lookupClass (const MatchPredicate & matchClass) const
The list of IOobjects with matching headerClassName.
IOobjectList lookupClass (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
The list of IOobjects with matching headerClassName that also have a matching object name.
IOobjectList lookupClass () const
The list of IOobjects with headerClassName == Type::typeName.
Note
If Type is void, no headerClassName check is used (always true).
IOobjectList lookupClass (const MatchPredicate & matchName) const
The list of IOobjects with headerClassName == Type::typeName that also have a matching object name.
Foam::HashTable< Foam::wordHashSet > classes () const
A summary hash of classes used and their associated object names.
The HashTable representation allows us to leverage various HashTable methods. This hashed summary view can be useful when querying particular aspects. For example,
* IOobjectList objects(runTime, runTime.timeName());
* HashTable<wordHashSet> classes = objects.classes();
*
* // How many volScalarField?
* word checkType = volScalarField::typeName;
*
* Info<< checkType << "="
*     << (classes.found(checkType) ? classes[checkType].size() : 0)
*     << nl;
*
Using the two-parameter HashTable::lookup method lets us avoid the '?' ternary, but still looks fairly ugly:
* Info<< checkType << "="
*     << classes.lookup(checkType, wordHashSet()).size() << nl;
*
If we have non-const access to the hash table, and don't mind incidentally creating empty entries, we can use the HashTable::operator() directly:
* Info<< checkType << "=" << classes(checkType).size() << nl;
*
Of course, for a single query it would have been easier and simpler to have used a direct query of the names:
* Info<< checkType << "=" << objects.names(checkType).size() << nl;
*
The summary hash, however, becomes most useful when reducing the objects in consideration to a particular subset. For example,
* const wordHashSet interestingTypes
* {
*     volScalarField::typeName,
*     volVectorField::typeName
* };
*
* classes.retain(interestingTypes);
*
Or do just the opposite:
* classes.erase(unsupportedTypes);
*
This also works with a hashedWordList, since it provides the expected '()' operator. But in this case the more general HashTable::filterKeys is required:
* const hashedWordList interestingTypes
* {
*     volScalarField::typeName,
*     volVectorField::typeName
* };
*
* classes.filterKeys(interestingTypes);
*
Of course, there are many other ways to use and manipulate the summary information.
Returns
HashTable of class-names for keys and wordHashSet of of object-names for the values.
Definition at line 290 of file IOobjectList.C.
HashTable<wordHashSet> classes (const MatchPredicate & matchName) const
A summary hash of classes used and their associated object names, restricted to objects that have a matching object name.
Foam::label count (const char * clsName) const
The number of objects of the given headerClassName.
Note
uses the class type() method
Definition at line 296 of file IOobjectList.C.
label count (const MatchPredicate & matchClass) const
The number of objects of the given headerClassName.
label count (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
The number of objects of the given headerClassName that also have a matching object name.
label count () const
The number of objects with headerClassName == Type::typeName.
label count (const MatchPredicate & matchName) const
The number of objects with headerClassName == Type::typeName that also have a matching object name.
Note
If Type is void, no headerClassName check is used (always true).
Foam::wordList names () const
The names of the IOobjects.
Definition at line 303 of file IOobjectList.C.
References Foam::BitOps::count().
Referenced by fileFieldSelection::addFromFile().
Foam::wordList names (const bool syncPar) const
The names of the IOobjects.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
Definition at line 309 of file IOobjectList.C.
References HashTable< T *, Key, Hash >::toc().
Foam::wordList names (const char * clsName) const
The names of IOobjects with the given headerClassName.
Definition at line 318 of file IOobjectList.C.
Foam::wordList names (const char * clsName, const bool syncPar) const
The names of the IOobjects with the given headerClassName.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
Definition at line 326 of file IOobjectList.C.
wordList names (const MatchPredicate & matchClass) const
The names of IOobjects with the given headerClassName.
wordList names (const MatchPredicate & matchClass, const bool syncPar) const
The names of the IOobjects with the given headerClassName.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
The names of IOobjects with the given headerClassName that also have a matching object name.
wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
The names of the IOobjects with the given headerClassName that also have a matching object name.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList names () const
The names of objects with headerClassName == Type::typeName.
wordList names (bool syncPar) const
The names of objects with headerClassName == Type::typeName.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList names (const MatchPredicate & matchName) const
The names of objects with headerClassName == Type::typeName that also have a matching object name.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList names (const MatchPredicate & matchName, const bool syncPar) const
The names of objects with headerClassName == Type::typeName that also have a matching object name.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
Foam::wordList sortedNames () const
The sorted names of the IOobjects.
Definition at line 338 of file IOobjectList.C.
Referenced by Foam::writeAreaFields(), Foam::writeDimFields(), Foam::writePointFields(), and Foam::writeVolFields().
Foam::wordList sortedNames (const bool syncPar) const
The sorted names of the IOobjects.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
Definition at line 344 of file IOobjectList.C.
References HashTable< T *, Key, Hash >::sortedToc().
Foam::wordList sortedNames (const char * clsName) const
The sorted names of IOobjects with the given headerClassName.
Definition at line 353 of file IOobjectList.C.
Foam::wordList sortedNames (const char * clsName, const bool syncPar) const
The sorted names of the IOobjects with the given headerClassName.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
Definition at line 361 of file IOobjectList.C.
wordList sortedNames (const MatchPredicate & matchClass) const
The sorted names of IOobjects with the given headerClassName.
wordList sortedNames (const MatchPredicate & matchClass, const bool syncPar) const
The sorted names of the IOobjects with the given headerClassName.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
The sorted names of IOobjects with the given headerClassName that also have a matching object name.
wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
The sorted names of the IOobjects with the given headerClassName that also have a matching object name.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList sortedNames () const
The sorted names of objects with headerClassName == Type::typeName.
wordList sortedNames (bool syncPar) const
The sorted names of objects with headerClassName == Type::typeName.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList sortedNames (const MatchPredicate & matchName) const
The sorted names of objects with headerClassName == Type::typeName that also have a matching object name.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
wordList sortedNames (const MatchPredicate & matchName, const bool syncPar) const
The sorted names of objects with headerClassName == Type::typeName that also have a matching object name.
With syncPar = true, sorts the names and triggers FatalError if the names are not consistent on all processors.
label filterClasses (const UnaryPredicate & pred, const bool pruning = false)
Filter to retain or prune given classes.
Returns
The number of items changed (removed)
label filterObjects (const UnaryPredicate & pred, const bool pruning = false)
Filter to retain or prune given object names.
Returns
The number of items changed (removed)
Foam::label prune_0 ()
Remove objects with names ending with "_0" (restart fields)
Returns
The number of items changed (removed)
Definition at line 373 of file IOobjectList.C.
Foam::wordList allNames () const
The sorted names of all objects (synchronised across processors)
Definition at line 384 of file IOobjectList.C.
References string::ends_with().
wordList allNames () const
The sorted names of all objects (synchronised across processors) with headerClassName == Type::typeName.
bool checkNames (const bool syncPar = true) const
Verify that object names are synchronised across processors.
Triggers FatalError if the names are not consistent on all processors.
Definition at line 393 of file IOobjectList.C.
void operator= (const IOobjectList &) delete
No copy assignment.
void operator= (IOobjectList && list)
Move assignment.
Definition at line 408 of file IOobjectList.C.
IOobject* lookup (const char * objName) const inline
Deprecated(2018-11) Locate an object by name (c-string). Disambiguated from multiple-lookup version by calling parameter.
Deprecated:
(2018-11) use findObject() for non-ambiguous resolution
Definition at line 826 of file IOobjectList.H.
IOobject* lookup (const word & objName) const inline
Deprecated(2018-11) Locate an object by name (const word&). Disambiguated from multiple-lookup version by calling parameter.
Deprecated:
(2018-11) use findObject() for non-ambiguous resolution
Definition at line 837 of file IOobjectList.H.
Foam::HashTable<Foam::wordHashSet> classesImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 29 of file IOobjectListTemplates.C.
References forAllConstIters, IOobject::headerClassName(), HashPtrTable< IOobject >::insert(), iter, and HashTable< T, Key, Hash >::size().
Foam::label countImpl (const IOobjectList & list, const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName)
Definition at line 56 of file IOobjectListTemplates.C.
Foam::label countTypeImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 81 of file IOobjectListTemplates.C.
Foam::wordList namesImpl (const IOobjectList & list, const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool doSort)
Definition at line 105 of file IOobjectListTemplates.C.
Foam::wordList namesTypeImpl (const IOobjectList & list, const MatchPredicate & matchName, const bool doSort)
Definition at line 141 of file IOobjectListTemplates.C.
Foam::IOobjectList lookupImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 176 of file IOobjectListTemplates.C.
Foam::IOobjectList lookupClassImpl (const IOobjectList & list, const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName)
Definition at line 206 of file IOobjectListTemplates.C.
Foam::IOobjectList lookupClassTypeImpl (const IOobjectList & list, const MatchPredicate & matchName)
Definition at line 237 of file IOobjectListTemplates.C.
Foam::IOobjectList lookup (const MatchPredicate & matchName) const
Definition at line 328 of file IOobjectListTemplates.C.
Foam::IOobjectList lookupClass (const MatchPredicate & matchClass) const
Definition at line 338 of file IOobjectListTemplates.C.
Foam::IOobjectList lookupClass (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 348 of file IOobjectListTemplates.C.
Foam::IOobjectList lookupClass () const
Definition at line 358 of file IOobjectListTemplates.C.
Foam::IOobjectList lookupClass (const MatchPredicate & matchName) const
Definition at line 366 of file IOobjectListTemplates.C.
Foam::HashTable<Foam::wordHashSet> classes (const MatchPredicate & matchName) const
Definition at line 377 of file IOobjectListTemplates.C.
Foam::label count (const MatchPredicate & matchClass) const
Definition at line 387 of file IOobjectListTemplates.C.
Foam::label count (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 397 of file IOobjectListTemplates.C.
Foam::label count () const
Definition at line 407 of file IOobjectListTemplates.C.
Foam::label count (const MatchPredicate & matchName) const
Definition at line 415 of file IOobjectListTemplates.C.
Foam::wordList names (const MatchPredicate & matchClass) const
Definition at line 427 of file IOobjectListTemplates.C.
Foam::wordList names (const MatchPredicate & matchClass, const bool syncPar) const
Definition at line 437 of file IOobjectListTemplates.C.
References Foam::namesImpl().
Foam::wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 454 of file IOobjectListTemplates.C.
Foam::wordList names (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
Definition at line 465 of file IOobjectListTemplates.C.
References Foam::namesImpl().
Foam::wordList names (const MatchPredicate & matchName) const
Definition at line 497 of file IOobjectListTemplates.C.
Foam::wordList names (const MatchPredicate & matchName, const bool syncPar) const
Definition at line 507 of file IOobjectListTemplates.C.
Foam::wordList sortedNames (const MatchPredicate & matchClass) const
Definition at line 523 of file IOobjectListTemplates.C.
Foam::wordList sortedNames (const MatchPredicate & matchClass, const bool syncPar) const
Definition at line 533 of file IOobjectListTemplates.C.
References Foam::namesImpl().
Foam::wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName) const
Definition at line 550 of file IOobjectListTemplates.C.
Foam::wordList sortedNames (const MatchPredicate1 & matchClass, const MatchPredicate2 & matchName, const bool syncPar) const
Definition at line 560 of file IOobjectListTemplates.C.
References Foam::namesImpl().
Foam::wordList sortedNames (const MatchPredicate & matchName) const
Definition at line 592 of file IOobjectListTemplates.C.
Foam::wordList sortedNames (const MatchPredicate & matchName, const bool syncPar) const
Definition at line 602 of file IOobjectListTemplates.C.
Foam::label filterClasses (const UnaryPredicate & pred, const bool pruning)
Definition at line 615 of file IOobjectListTemplates.C.
Foam::label filterObjects (const UnaryPredicate & pred, const bool pruning)
Definition at line 652 of file IOobjectListTemplates.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOobjectList/IOobjectList.H
src/OpenFOAM/db/IOobjectList/IOobjectList.C
src/OpenFOAM/db/IOobjectList/IOobjectListTemplates.C