OpenFOAM: AABBTree< Type > Class Template Reference
AABBTree< Type > Class Template Reference
Templated tree of axis-aligned bounding boxes (AABB)
Public Member Functions
AABBTree ()
Null constructor.
AABBTree (const UList< Type > &objects, const pointField &points, const bool equalBinSize=true, const label maxLevel=3, const label minBinSize=100)
Construct from components.
const List< treeBoundBox > & boundBoxes () const
Return the bounding boxes making up the tree.
const List< labelList > & addressing () const
Return the contents addressing.
bool pointInside (const point &pt) const
Determine whether a point is inside the bounding boxes.
bool overlaps (const boundBox &bbIn) const
Determine whether a bounding box overlaps the tree bounding.
Protected Member Functions
void writeOBJ (const bool writeLinesOnly, const treeBoundBox &bb, label &vertI, Ostream &os) const
Write OBJ file of bounding box.
void writeOBJ (const bool leavesOnly, const bool writeLinesOnly, const treeBoundBox &bb, const label nodeI, const List< Pair< treeBoundBox >> &bbs, const List< Pair< label >> &nodes, label &vertI, Ostream &os) const
Write OBJ for all bounding boxes.
void createBoxes (const bool equalBinSize, const label level, const List< Type > &objects, const pointField &points, const DynamicList< label > &objectIDs, const treeBoundBox &bb, const label nodeI, DynamicList< Pair< treeBoundBox >> &bbs, DynamicList< labelPair > &nodes, DynamicList< labelList > &addressing) const
Create the bounding boxes by interrogating points.
Protected Attributes
label maxLevel_
Maximum tree level.
label minLeafSize_
Minimum points per leaf.
List< treeBoundBox > boundBoxes_
Bounding boxes making up the tree.
List< labelList > addressing_
Leaf adressing.
Static Protected Attributes
static scalar tolerance_ = 1e-4
Tolerance.
Friends
Istream & operator>> (Istream &, AABBTree &)
Ostream & operator (Ostream &, const AABBTree &)
Detailed Description
template<class Type>
class Foam::AABBTree< Type >
Templated tree of axis-aligned bounding boxes (AABB)
Designed to be templated on either faces or cells, the AABBTree will decompose the input into a tree of AABB's. The maximum number of tree levels and minimum number of objects per leaf are provided on construction, and the contents (addressing) is stored.
Source files
AABBTree.H
AABBTree.C
Definition at line 55 of file AABBTree.H.
Constructor & Destructor Documentation
AABBTree ()
Null constructor.
Definition at line 315 of file AABBTree.C.
AABBTree (const UList< Type > & objects, const pointField & points, const bool equalBinSize = true, const label maxLevel = 3, const label minBinSize = 100)
Construct from components.
equalBinSize: divide into equal number of elements or equal span
Definition at line 326 of file AABBTree.C.
Member Function Documentation
void writeOBJ (const bool writeLinesOnly, const treeBoundBox & bb, label & vertI, Ostream & os) const protected
Write OBJ file of bounding box.
Definition at line 34 of file AABBTree.C.
References Foam::constant::electromagnetic::e, treeBoundBox::edges, f(), treeBoundBox::faces, Foam::nl, treeBoundBox::points(), and Foam::meshTools::writeOBJ().
void writeOBJ (const bool leavesOnly, const bool writeLinesOnly, const treeBoundBox & bb, const label nodeI, const List< Pair< treeBoundBox >> & bbs, const List< Pair< label >> & nodes, label & vertI, Ostream & os) const protected
Write OBJ for all bounding boxes.
Definition at line 73 of file AABBTree.C.
void createBoxes (const bool equalBinSize, const label level, const List< Type > & objects, const pointField & points, const DynamicList< label > & objectIDs, const treeBoundBox & bb, const label nodeI, DynamicList< Pair< treeBoundBox >> & bbs, DynamicList< labelPair > & nodes, DynamicList< labelList > & addressing) const protected
Create the bounding boxes by interrogating points.
Definition at line 120 of file AABBTree.C.
const Foam::List< Foam::treeBoundBox > & boundBoxes () const
Return the bounding boxes making up the tree.
Definition at line 414 of file AABBTree.C.
const Foam::List< Foam::labelList > & addressing () const
Return the contents addressing.
Definition at line 421 of file AABBTree.C.
bool pointInside (const point & pt) const
Determine whether a point is inside the bounding boxes.
Definition at line 428 of file AABBTree.C.
bool overlaps (const boundBox & bbIn) const
Determine whether a bounding box overlaps the tree bounding.
boxes
Definition at line 443 of file AABBTree.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , AABBTree< Type > &) friend
Ostream& operator (Ostream & , const AABBTree< Type > &) friend
Member Data Documentation
Foam::scalar tolerance_ = 1e-4 static protected
Tolerance.
Definition at line 78 of file AABBTree.H.
label maxLevel_ protected
Maximum tree level.
Definition at line 83 of file AABBTree.H.
label minLeafSize_ protected
Minimum points per leaf.
Definition at line 88 of file AABBTree.H.
List<treeBoundBox> boundBoxes_ protected
Bounding boxes making up the tree.
Definition at line 93 of file AABBTree.H.
List<labelList> addressing_ protected
Leaf adressing.
Definition at line 98 of file AABBTree.H.
The documentation for this class was generated from the following files:
src/meshTools/AABBTree/AABBTree.H
src/meshTools/AABBTree/AABBTree.C