OpenFOAM: interpolated Class Reference
interpolated Class Reference abstract
Public Member Functions
TypeName ("interpolated")
Runtime type information.
interpolated (const dictionary &dict, const phasePair &pair)
Construct from components.
virtual ~interpolated ()
Destructor.
virtual tmp< volScalarField > damp (const tmp< volScalarField > &) const
Return damped coefficient.
virtual tmp< volVectorField > damp (const tmp< volVectorField > &) const
Return damped force.
virtual tmp< surfaceScalarField > damp (const tmp< surfaceScalarField > &) const
Return damped face force.
Public Member Functions inherited from wallDampingModel
TypeName ("wallDampingModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, wallDampingModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
wallDampingModel (const dictionary &dict, const phasePair &pair)
Construct from components.
virtual ~wallDampingModel ()
Destructor.
Public Member Functions inherited from wallDependentModel
wallDependentModel (const fvMesh &mesh)
Construct from a mesh.
virtual ~wallDependentModel ()
Destructor.
const volScalarField & yWall () const
const volVectorField & nWall () const
wallDependentModel (const fvMesh &mesh)
Construct from a mesh.
virtual ~wallDependentModel ()
Destructor.
const volScalarField & yWall () const
const volVectorField & nWall () const
Protected Member Functions
virtual tmp< volScalarField > limiter () const =0
Return the force limiter field.
Additional Inherited Members
Static Public Member Functions inherited from wallDampingModel
static autoPtr< wallDampingModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes inherited from wallDampingModel
static const dimensionSet dimF
Coefficient dimensions.
Protected Attributes inherited from wallDampingModel
const phasePair & pair_
Phase pair.
Detailed Description
Source files
interpolatedWallDamping.H
interpolatedWallDamping.C
Definition at line 50 of file interpolatedWallDamping.H.
Constructor & Destructor Documentation
interpolated (const dictionary & dict, const phasePair & pair)
Construct from components.
Definition at line 39 of file interpolatedWallDamping.C.
~interpolated () virtual
Destructor.
Definition at line 50 of file interpolatedWallDamping.C.
Member Function Documentation
virtual tmp<volScalarField> limiter () const protected pure virtual
Return the force limiter field.
Implemented in cosine, linear, and sine.
TypeName ("interpolated")
Runtime type information.
Foam::tmp< Foam::volScalarField > damp (const tmp< volScalarField > & F) const virtual
Return damped coefficient.
Implements wallDampingModel.
Definition at line 58 of file interpolatedWallDamping.C.
Foam::tmp< Foam::volVectorField > damp (const tmp< volVectorField > & F) const virtual
Return damped force.
Implements wallDampingModel.
Definition at line 68 of file interpolatedWallDamping.C.
References F(), and Foam::limiter().
Foam::tmp< Foam::surfaceScalarField > damp (const tmp< surfaceScalarField > & Ff) const virtual
Return damped face force.
Implements wallDampingModel.
Definition at line 78 of file interpolatedWallDamping.C.
References F(), and Foam::limiter().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialModels/wallDampingModels/interpolated/interpolatedWallDamping.H
src/phaseSystemModels/reactingEulerFoam/interfacialModels/wallDampingModels/interpolated/interpolatedWallDamping.C