OpenFOAM: pointVolInterpolation Class Reference
pointVolInterpolation Class Reference
Public Member Functions
ClassName ("pointVolInterpolation")
pointVolInterpolation (const pointMesh &, const fvMesh &)
Constructor given pointMesh and fvMesh.
~pointVolInterpolation ()
const FieldField< Field, scalar > & volWeights () const
Return reference to weights arrays.
void updateTopology ()
Update mesh topology using the morph engine.
bool movePoints ()
Correct weighting factors for moving mesh.
template<class Type >
void interpolate (const GeometricField< Type, pointPatchField, pointMesh > &, GeometricField< Type, fvPatchField, volMesh > &) const
Interpolate from pointField to volField.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &) const
Interpolate pointField returning volField.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh >> &) const
Interpolate tmp<pointField> returning volField.
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &pf) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh >> &tpf) const
Protected Member Functions
const pointMesh & pMesh () const
const fvMesh & vMesh () const
Detailed Description
Source files
pointVolInterpolation.H
pointVolInterpolation.C
pointVolInterpolate.C
Definition at line 58 of file pointVolInterpolation.H.
Constructor & Destructor Documentation
pointVolInterpolation (const pointMesh & pm, const fvMesh & vm)
Constructor given pointMesh and fvMesh.
Definition at line 164 of file pointVolInterpolation.C.
~pointVolInterpolation ()
Definition at line 178 of file pointVolInterpolation.C.
Member Function Documentation
const pointMesh& pMesh () const inline protected
Definition at line 101 of file pointVolInterpolation.H.
const fvMesh& vMesh () const inline protected
Definition at line 106 of file pointVolInterpolation.H.
Referenced by pointVolInterpolation::interpolate().
ClassName ("pointVolInterpolation")
const Foam::FieldField< Foam::Field, Foam::scalar > & volWeights () const
Return reference to weights arrays.
This also constructs the weighting factors if neccessary.
Definition at line 189 of file pointVolInterpolation.C.
Referenced by pointVolInterpolation::interpolate().
void updateTopology ()
Update mesh topology using the morph engine.
Definition at line 202 of file pointVolInterpolation.C.
bool movePoints ()
Correct weighting factors for moving mesh.
Definition at line 210 of file pointVolInterpolation.C.
void interpolate (const GeometricField< Type, pointPatchField, pointMesh > & pf, GeometricField< Type, fvPatchField, volMesh > & vf) const
Interpolate from pointField to volField.
using inverse distance weighting
Definition at line 33 of file pointVolInterpolate.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), DebugInFunction, Foam::endl(), forAll, DimensionedField< Type, GeoMesh >::mesh(), Foam::constant::mathematical::pi(), Foam::type(), pointVolInterpolation::vMesh(), and pointVolInterpolation::volWeights().
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolate (const GeometricField< Type, pointPatchField, pointMesh > &) const
Interpolate pointField returning volField.
using inverse distance weighting
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh >> &) const
Interpolate tmp<pointField> returning volField.
using inverse distance weighting
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolate (const GeometricField< Type, pointPatchField, pointMesh > & pf) const
Definition at line 89 of file pointVolInterpolate.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolate (const tmp< GeometricField< Type, pointPatchField, pointMesh >> & tpf) const
Definition at line 119 of file pointVolInterpolate.C.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/interpolation/pointVolInterpolation/pointVolInterpolation.H
src/optimisation/adjointOptimisation/adjoint/interpolation/pointVolInterpolation/pointVolInterpolate.C
src/optimisation/adjointOptimisation/adjoint/interpolation/pointVolInterpolation/pointVolInterpolation.C