OpenFOAM: fileName Class Reference
fileName Class Reference
A class for handling file names.
Public Types
enum Type { UNDEFINED = 0, FILE = 1, DIRECTORY = 2, LINK = 4 }
Enumerations to handle directory entry types.
Public Member Functions
fileName ()=default
Construct null.
fileName (const fileName &)=default
Copy construct.
fileName (fileName &&)=default
Move construct.
fileName (const word &s)
Copy construct from word.
fileName (word &&s)
Move construct from word.
fileName (const string &s, bool doStrip=true)
Copy construct from string.
fileName (string &&s, bool doStrip=true)
Move construct from string.
fileName (const std::string &s, bool doStrip=true)
Copy construct from std::string.
fileName (std::string &&s, bool doStrip=true)
Move construct from std::string.
fileName (const char *s, bool doStrip=true)
Copy construct from character array.
fileName (const UList< word > &list)
Construct by concatenating elements of wordList separated by '/'.
fileName (std::initializer_list< word > list)
Construct by concatenating words separated by '/'.
fileName (Istream &is)
Construct from Istream.
void stripInvalid ()
Strip invalid characters.
bool clean ()
Cleanup filename inplace.
fileName clean () const
Cleanup filename.
Type type (bool followLink=true, bool checkGzip=false) const
Return the directory entry type: UNDEFINED, FILE, DIRECTORY (or LINK).
bool isAbsolute () const
Return true if file name is absolute (starts with a '/')
fileName & toAbsolute ()
Convert from relative to absolute.
bool isBackup () const
Return true if file name ends with "~", ".bak", ".old", ".save".
word name () const
Return basename (part beyond last /), including its extension.
word nameLessExt () const
Return basename, without extension.
word name (const bool noExt) const
Deprecated(2017-03) return basename, optionally without extension.
fileName path () const
Return directory path name (part before last /)
bool hasPath () const
Return true if it contains a '/' character.
bool removePath ()
Remove leading path, returning true if string changed.
fileName relative (const fileName &parent, const bool caseTag=false) const
Return a relative name by stripping off the parent directory where possible.
fileName lessExt () const
Return file name without extension (part before last .)
word ext () const
Return file name extension (part after last .)
fileName & ext (const word &ending)
Append a '.' and the ending, and return the object.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
wordList components (const char delim= '/') const
Return path components as wordList.
word component (const size_type cmpt, const char delim= '/') const
Return a single component of the path.
fileName & operator= (const fileName &str)
Copy assignment, no character validation required.
fileName & operator= (fileName &&str)
Move assignment, no character validation required.
fileName & operator= (const word &str)
Copy assignment, no character validation required.
fileName & operator= (word &&str)
Move assignment, no character validation required.
fileName & operator= (const string &str)
Copy assignment, stripping invalid characters.
fileName & operator= (string &&str)
Move assignment, stripping invalid characters.
fileName & operator= (const std::string &str)
Copy assignment, stripping invalid characters.
fileName & operator= (std::string &&str)
Move assignment, stripping invalid characters.
fileName & operator= (const char *str)
Copy, stripping invalid characters.
fileName & operator/= (const string &other)
Append a path element with '/' separator.
Public Member Functions inherited from string
string ()=default
Construct null.
string (const std::string &str)
Copy construct from std::string.
string (std::string &&str)
Move construct from std::string.
string (const char *str)
Construct as copy of character array.
string (const char *str, const size_type len)
Construct as copy with a maximum number of characters.
string (const char c)
Construct from a single character.
string (const size_type len, const char c)
Construct fill copies of a single character.
string (Istream &is)
Construct from Istream.
bool match (const std::string &text) const
Test for equality.
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
Replace first occurrence of sub-string s1 with s2, beginning at pos.
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
Replace all occurrences of sub-string s1 with s2, beginning at pos in the string.
string & expand (const bool allowEmpty=false)
Inplace expand initial tags, tildes, and all occurrences of environment variables as per stringOps::expand.
bool removeRepeated (const char character)
Remove repeated characters.
bool removeStart (const std::string &text)
Remove the given text from the start of the string.
bool removeStart (const char c)
Remove leading character, unless string is a single character.
bool removeEnd (const std::string &text)
Remove the given text from the end of the string.
bool removeEnd (const char c)
Remove trailing character, unless string is a single character.
void swap (std::string &str)
Swap contents. Self-swapping is a no-op.
bool operator() (const std::string &text) const
Test for equality. Allows use as a predicate.
bool starts_with (const std::string &s) const
True if string starts with the given prefix (cf. C++20)
bool starts_with (const char c) const
True if string starts with the given character (cf. C++20)
bool ends_with (const std::string &s) const
True if string ends with the given suffix (cf. C++20)
bool ends_with (const char c) const
True if string ends with the given character (cf. C++20)
size_type count (const char c) const
Count the number of occurrences of the specified character in the string.
bool startsWith (const std::string &s) const
Deprecated(2019-11)
bool endsWith (const std::string &s) const
Deprecated(2019-11)
bool removeTrailing (const char c)
Deprecated(2019-11)
template<class String >
Foam::string quotemeta (const std::string &str, const char quote)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Static Public Member Functions
static bool valid (char c)
Is this character valid for a fileName?
static fileName validate (const std::string &s, const bool doClean=true)
Construct fileName with no invalid characters, possibly applying other transformations such as changing the path separator, removing duplicate or trailing slashes, etc.
static fileName concat (const std::string &s1, const std::string &s2, const char delim= '/')
Join two strings with a path separator ('/' by default).
static bool equals (const std::string &s1, const std::string &s2)
This is a specialized (possibly slower) version of compare() that ignores duplicate or trailing slashes.
static bool clean (std::string &str)
Cleanup filename.
static bool isAbsolute (const std::string &str)
Return true if string starts with a '/'.
static bool isBackup (const std::string &str)
Return true if string ends with "~", ".bak", ".old", ".save".
static std::string name (const std::string &str)
Return basename (part beyond last /), including its extension.
static std::string nameLessExt (const std::string &str)
Return basename, without extension.
static std::string path (const std::string &str)
Return directory path name (part before last /)
Static Public Member Functions inherited from string
template<class String >
static bool valid (const std::string &str)
Does the string contain valid characters only?
template<class String >
static bool meta (const std::string &str, const char quote='\\')
Does this string contain meta-characters?
template<class String >
static bool stripInvalid (std::string &str)
Strip invalid characters from the given string.
template<class String >
static String validate (const std::string &str)
Return a valid String from the given string.
template<class String >
static string quotemeta (const std::string &str, const char quote= '\\')
Return a String with quoted meta-characters from the given string.
Static Public Attributes
static const char *const typeName = "fileName"
The typeName.
static int debug
Debugging.
static int allowSpaceInFileName
Allow space character in fileName. To be used with caution.
static const fileName null
An empty fileName.
Static Public Attributes inherited from string
static const char *const typeName = "string"
The type name "string".
static int debug
The debug flag.
static const string null
An empty string.
Additional Inherited Members
Protected Member Functions inherited from string
std::string::size_type find_ext () const
Find position of a file extension dot, return npos on failure.
word ext () const
Return file name extension (part after last .)
bool ext (const word &ending)
Append a '.' and the ending.
bool hasPath () const
Return true if it contains a '/' character.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
bool removePath ()
Remove leading path, returning true if string changed.
Static Protected Member Functions inherited from string
static std::string::size_type find_ext (const std::string &str)
Find position of a file extension dot, return npos on failure.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
Detailed Description
A class for handling file names.
A fileName is a string of characters without whitespace or quotes. A fileName can be
constructed from a char*, a string or a word
concatenated by adding a '/' separator
decomposed into the path, name or component list
interrogated for type and access mode
The string::expand() method expands environment variables, etc,
Source files
fileName.H
fileName.C
fileNameIO.C
Definition at line 65 of file fileName.H.
Member Enumeration Documentation
enum Type
Enumerations to handle directory entry types.
Enumerator
UNDEFINED
Undefined type.
FILE
A file.
DIRECTORY
A directory.
LINK
A symlink.
Definition at line 74 of file fileName.H.
Constructor & Destructor Documentation
fileName () default
Construct null.
fileName (const fileName &) default
Copy construct.
fileName (fileName &&) default
Move construct.
fileName (const word & s) inline
Copy construct from word.
Definition at line 26 of file fileNameI.H.
fileName (word && s) inline
Move construct from word.
Definition at line 32 of file fileNameI.H.
fileName (const string & s, bool doStrip = true) inline
Copy construct from string.
Definition at line 38 of file fileNameI.H.
fileName (string && s, bool doStrip = true) inline
Move construct from string.
Definition at line 49 of file fileNameI.H.
References fileName::stripInvalid().
fileName (const std::string & s, bool doStrip = true) inline
Copy construct from std::string.
Definition at line 60 of file fileNameI.H.
References fileName::stripInvalid().
fileName (std::string && s, bool doStrip = true) inline
Move construct from std::string.
Definition at line 71 of file fileNameI.H.
References fileName::stripInvalid().
fileName (const char * s, bool doStrip = true) inline
Copy construct from character array.
Definition at line 82 of file fileNameI.H.
References fileName::stripInvalid().
fileName (const UList< word > & list) explicit
Construct by concatenating elements of wordList separated by '/'.
Definition at line 218 of file fileName.C.
fileName (std::initializer_list< word > list) explicit
Construct by concatenating words separated by '/'.
Definition at line 238 of file fileName.C.
fileName (Istream & is) explicit
Construct from Istream.
Definition at line 27 of file fileNameIO.C.
Member Function Documentation
bool valid (char c) inline static
Is this character valid for a fileName?
Definition at line 95 of file fileNameI.H.
Referenced by fileName::validate().
Foam::fileName validate (const std::string & s, const bool doClean = true) static
Construct fileName with no invalid characters, possibly applying other transformations such as changing the path separator, removing duplicate or trailing slashes, etc.
Definition at line 51 of file fileName.C.
References c(), iter, and fileName::valid().
Foam::fileName concat (const std::string & s1, const std::string & s2, const char delim = '/') static
Join two strings with a path separator ('/' by default).
No separator is added if either argument is an empty string or if the arguments already had the path separator at the junction. Invalid characters are not stripped (ie, retained).
Definition at line 119 of file fileName.C.
Referenced by dictionary::dictionary().
bool equals (const std::string & s1, const std::string & s2) static
This is a specialized (possibly slower) version of compare() that ignores duplicate or trailing slashes.
Definition at line 146 of file fileName.C.
void stripInvalid () inline
Strip invalid characters.
Definition at line 106 of file fileNameI.H.
Referenced by fileName::fileName().
bool clean (std::string & str) static
Cleanup filename.
Removes trailing /
*      /                 -->   /
*      /abc/             -->   /abc
*
Removes repeated slashes
*      /abc////def        -->   /abc/def
*
Removes /./ (current directory)
*      /abc/def/./ghi/.   -->   /abc/def/ghi
*      abc/def/./         -->   abc/def
*      ./abc/             -->   ./abc
*
Removes /../ (parent directory)
*      /abc/def/../ghi/jkl/nmo/..   -->   /abc/ghi/jkl
*      abc/../def/ghi/../jkl        -->   abc/../def/jkl
*
Returns
True if the content changed
Definition at line 291 of file fileName.C.
Referenced by meshRefinement::findRegions().
bool clean ()
Cleanup filename inplace.
Returns
True if any contents changed
Definition at line 381 of file fileName.C.
Referenced by fileName::clean(), and fileName::nameLessExt().
Foam::fileName clean () const
Cleanup filename.
Returns
cleaned copy of fileName
Definition at line 387 of file fileName.C.
References fileName::clean().
Foam::fileName::Type type (bool followLink = true, bool checkGzip = false) const
Return the directory entry type: UNDEFINED, FILE, DIRECTORY (or LINK).
Parameters
followLink when false it will return LINK for a symlink rather than following it.
checkGzip add an additional test for a gzip FILE
Definition at line 261 of file fileName.C.
Referenced by fvMeshDistribute::printFieldInfo().
bool isAbsolute (const std::string & str) inline static
Return true if string starts with a '/'.
Definition at line 129 of file fileNameI.H.
bool isAbsolute () const inline
Return true if file name is absolute (starts with a '/')
Definition at line 149 of file fileNameI.H.
Foam::fileName & toAbsolute ()
Convert from relative to absolute.
Definition at line 278 of file fileName.C.
bool isBackup (const std::string & str) static
Return true if string ends with "~", ".bak", ".old", ".save".
Definition at line 187 of file fileName.C.
bool isBackup () const inline
Return true if file name ends with "~", ".bak", ".old", ".save".
Definition at line 155 of file fileNameI.H.
std::string name (const std::string & str) inline static
Return basename (part beyond last /), including its extension.
The result normally corresponds to a Foam::word
Behaviour compared to /usr/bin/basename:
*   input           name()          basename
*   -----           ------          --------
*   ""              ""              ""
*   "abc"           "abc"           "abc"
*   "/"             ""              "/"
*   "/abc"          "abc"           "abc"
*   "abc/def"       "def"           "def"
*   "/abc/def"      "def"           "def"
*   "/abc/def/"     ""              "def"
*   "/abc/../def"   "def"           "def"
*
Definition at line 202 of file fileNameI.H.
References path().
Referenced by seriesWriter::append().
Foam::word name () const inline
Return basename (part beyond last /), including its extension.
Definition at line 215 of file fileNameI.H.
Referenced by fileName::ext().
std::string nameLessExt (const std::string & str) static
Return basename, without extension.
The result normally corresponds to a Foam::word
Definition at line 395 of file fileName.C.
References fileName::clean().
Foam::word nameLessExt () const inline
Return basename, without extension.
Definition at line 227 of file fileNameI.H.
References string::ext().
word name (const bool noExt) const inline
Deprecated(2017-03) return basename, optionally without extension.
Deprecated:
(2017-03) - use name() or nameLessExt() methods which describe their behaviour explicitly
Definition at line 346 of file fileName.H.
std::string path (const std::string & str) inline static
Return directory path name (part before last /)
The result normally coresponds to a Foam::fileName
Behaviour compared to /usr/bin/dirname:
*   input           path()          dirname
*   -----           ------          -------
*   ""              "."             "."
*   "abc"           "."             "."
*   "/"             "/"             "/"
*   "/abc"          "/"             "/"
*   "abc/def"       "abc"           "abc"
*   "/abc/def"      "/abc"          "/abc"
*   "/abc/def/"     "/abc/def"      "/abc"
*   "/abc/../def"   "/abc/.."       "/abc/.."
*
Definition at line 179 of file fileNameI.H.
References string::hasExt().
Referenced by Foam::mkDir(), x3dWriter::write(), distributedTriSurfaceMesh::writeObject(), Foam::vtk::writePointSet(), and x3dWriter::writeTemplate().
Foam::fileName path () const inline
Return directory path name (part before last /)
Definition at line 196 of file fileNameI.H.
bool hasPath () const inline
Return true if it contains a '/' character.
Definition at line 161 of file fileNameI.H.
bool removePath () inline
Remove leading path, returning true if string changed.
Definition at line 246 of file fileNameI.H.
Foam::fileName relative (const fileName & parent, const bool caseTag = false) const
Return a relative name by stripping off the parent directory where possible.
Parameters
parent the parent directory
caseTag replace the parent with <case> for later use with expand(), or prefix <case> if the file name was not an absolute location
Definition at line 424 of file fileName.C.
Referenced by TimePaths::constant(), and argList::distributed().
Foam::fileName lessExt () const inline
Return file name without extension (part before last .)
Definition at line 233 of file fileNameI.H.
Referenced by Foam::vtk::writePointSet().
Foam::word ext () const inline
Return file name extension (part after last .)
Definition at line 221 of file fileNameI.H.
References fileName::name().
Referenced by MeshedSurfaceProxy< Face >::write(), x3dWriter::write(), surfMesh::write(), triSurface::write(), and x3dWriter::writeTemplate().
Foam::fileName & ext (const word & ending) inline
Append a '.' and the ending, and return the object.
The '.' and ending will not be added when the ending is empty, or when the file name is empty or ended with a '/'.
Definition at line 258 of file fileNameI.H.
References string::removeExt().
bool hasExt () const inline
Return true if it has an extension or simply ends with a '.'.
Definition at line 167 of file fileNameI.H.
References string::hasPath().
Referenced by Foam::vtk::writePointSet().
bool hasExt (const word & ending) const inline
Return true if the extension is the same as the given ending.
Definition at line 173 of file fileNameI.H.
References string::hasExt().
bool hasExt (const wordRe & ending) const
Return true if the extension matches the given ending.
Definition at line 460 of file fileName.C.
bool removeExt () inline
Remove extension, returning true if string changed.
Definition at line 252 of file fileNameI.H.
References string::removePath().
Foam::wordList components (const char delim = '/') const
Return path components as wordList.
Behaviour:
*   input           components()
*   -----           ------------
*   ""              ()
*   "."             (".")
*   "abc"           ("abc")
*   "/abc"          ("abc")
*   "abc/def"       ("abc", "def")
*   "/abc/def"      ("abc", "def")
*   "/abc/def/"     ("abc", "def")
*
Definition at line 466 of file fileName.C.
References string::hasExt().
Foam::word component (const size_type cmpt, const char delim = '/') const
Return a single component of the path.
Definition at line 486 of file fileName.C.
Foam::fileName & operator= (const fileName & str) inline
Copy assignment, no character validation required.
Self-assignment is a no-op.
Definition at line 267 of file fileNameI.H.
Foam::fileName & operator= (fileName && str) inline
Move assignment, no character validation required.
Self-assignment is a no-op.
Definition at line 278 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator= (const word & str) inline
Copy assignment, no character validation required.
Definition at line 289 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator= (word && str) inline
Move assignment, no character validation required.
Definition at line 296 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator= (const string & str) inline
Copy assignment, stripping invalid characters.
Definition at line 303 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator= (string && str) inline
Move assignment, stripping invalid characters.
Definition at line 311 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator= (const std::string & str) inline
Copy assignment, stripping invalid characters.
Definition at line 319 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator= (std::string && str) inline
Move assignment, stripping invalid characters.
Definition at line 327 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator= (const char * str) inline
Copy, stripping invalid characters.
Definition at line 335 of file fileNameI.H.
References Foam::FieldOps::assign().
Foam::fileName & operator/= (const string & other)
Append a path element with '/' separator.
No '/' separator is added if this or the argument are empty.
Definition at line 504 of file fileName.C.
Member Data Documentation
const char *const typeName = "fileName" static
The typeName.
Definition at line 88 of file fileName.H.
int debug static
Debugging.
Definition at line 93 of file fileName.H.
int allowSpaceInFileName static
Allow space character in fileName. To be used with caution.
Definition at line 98 of file fileName.H.
const Foam::fileName null static
An empty fileName.
Definition at line 103 of file fileName.H.
Referenced by bladeModel::interpolateWeights(), profileModel::profileModel(), and vtmWriter::write().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/fileName/fileName.H
src/OpenFOAM/primitives/strings/fileName/fileName.C
src/OpenFOAM/primitives/strings/fileName/fileNameI.H
src/OpenFOAM/primitives/strings/fileName/fileNameIO.C