OpenFOAM: Lavieville Class Reference
Lavieville Class Reference
Lavieville wall heat flux partitioning model.
Public Member Functions
TypeName ("Lavieville")
Runtime type information.
Lavieville (const dictionary &dict)
Construct from a dictionary.
virtual ~Lavieville ()
Destructor.
virtual tmp< scalarField > fLiquid (const scalarField &alphaLiquid) const
Liquid blending function.
virtual void write (Ostream &os) const
Public Member Functions inherited from partitioningModel
TypeName ("partitioningModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, partitioningModel, dictionary,(const dictionary &dict),(dict))
Declare runtime construction.
partitioningModel ()
Construct null.
virtual ~partitioningModel ()
Destructor.
Additional Inherited Members
Static Public Member Functions inherited from partitioningModel
static autoPtr< partitioningModel > New (const dictionary &dict)
Select null constructed.
Detailed Description
Lavieville wall heat flux partitioning model.
Model parameters: alphaCrit: critical liquid fraction
Reference:
    Lavieville, J., Quemerais, E., Mimouni, S., Boucker, M., &
    Mechitoua, N. (2006).
    NEPTUNE CFD V1. 0 theory manual.
    NEPTUNE report Nept_2004_L1, 2(3).
Source files
Lavieville.H
Lavieville.C
Definition at line 61 of file Lavieville.H.
Constructor & Destructor Documentation
Lavieville (const dictionary & dict)
Construct from a dictionary.
Definition at line 47 of file Lavieville.C.
~Lavieville () virtual
Destructor.
Definition at line 57 of file Lavieville.C.
Member Function Documentation
TypeName ("Lavieville")
Runtime type information.
Foam::tmp< Foam::scalarField > fLiquid (const scalarField & alphaLiquid) const virtual
Liquid blending function.
Implements partitioningModel.
Definition at line 66 of file Lavieville.C.
References Foam::exp(), Foam::neg(), and Foam::pos0().
void write (Ostream & os) const virtual
Reimplemented from partitioningModel.
Definition at line 83 of file Lavieville.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/Lavieville/Lavieville.H
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/partitioningModels/Lavieville/Lavieville.C