OpenFOAM: functionObjectBase Class Reference
functionObjectBase Class Reference
Base class for function object visualisation.
Public Member Functions
functionObjectBase (const stateFunctionObject &state, const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~functionObjectBase ()=default
Destructor.
virtual bool clear ()
Clear files used to create the object(s)
Public Member Functions inherited from fieldVisualisationBase
fieldVisualisationBase (const dictionary &dict, const HashPtrTable< Function1< vector >> &colours)
Construct from dictionary.
virtual ~fieldVisualisationBase ()
Destructor.
const HashPtrTable< Function1
< vector > > & colours () const
Return the colours.
const word & fieldName () const
Return the field name.
Protected Member Functions
fileName getFileName (const word &keyword, const word &subDictName) const
Retrieve the filename used to create the scene object using information stored via the stateFunctionObject.
bool removeFile (const word &keyword, const word &subDictName)
Remove file used to create the scene object.
functionObjectBase (const functionObjectBase &)=delete
No copy construct.
void operator= (const functionObjectBase &)=delete
No copy assignment.
Protected Member Functions inherited from fieldVisualisationBase
void setColourMap (vtkLookupTable *lut) const
Set the colour map.
void addScalarBar (const scalar position, vtkRenderer *renderer, vtkLookupTable *lut) const
Add scalar bar (if visible) to renderer.
void setField (const scalar position, const word &colourFieldName, const FieldAssociation fieldAssociation, vtkMapper *mapper, vtkRenderer *renderer) const
Set field/configure mapper, add scalar bar.
void addGlyphs (const scalar position, const word &scaleFieldName, const fieldSummary &scaleFieldInfo, const word &colourFieldName, const fieldSummary &colourFieldInfo, const scalar maxGlyphLength, vtkPolyData *data, vtkActor *actor, vtkRenderer *renderer) const
Add glyphs.
fieldVisualisationBase (const fieldVisualisationBase &)=delete
No copy construct.
void operator= (const fieldVisualisationBase &)=delete
No copy assignment.
Protected Attributes
const stateFunctionObject & state_
Reference to the state.
word functionObjectName_
The function object name that provides the source data.
bool liveObject_
Flag to indicate "live" (simulation) data source should be used.
bool clearObjects_
Flag to indicate that source data should be cleared after use.
Protected Attributes inherited from fieldVisualisationBase
const HashPtrTable< Function1
< vector > > & colours_
Colours.
word fieldName_
Field name.
bool smooth_
Requested smoother fields (eg, interpolate cell -> point values)
colourByType colourBy_
Colour by type.
colourMapType colourMap_
Colour map type.
Tuple2< scalar, scalar > range_
Range of values.
scalarBar scalarBar_
Scalar bar characteristics.
Additional Inherited Members
Public Types inherited from fieldVisualisationBase
enum colourByType { cbColour, cbField }
Colouring type.
enum colourMapType {
cmCoolToWarm, cmBlueWhiteRed = cmCoolToWarm, cmColdAndHot, cmFire,
cmRainbow, cmGreyscale, cmXray
}
Colour map enumerations.
enum FieldAssociation { NO_DATA = 0, CELL_DATA = 0x1, POINT_DATA = 0x2, CELL_POINT_DATA = 0x3 }
Enumeration of the data field associations.
Static Public Attributes inherited from fieldVisualisationBase
static const Enum< colourByType > colourByTypeNames
Enumeration names for colourByType.
static const Enum< colourMapType > colourMapTypeNames
Enumeration names for colourMapType.
Static Protected Member Functions inherited from fieldVisualisationBase
static fieldSummary queryFieldSummary (const word &fieldName, vtkDataSet *dataset)
Query DataSet for field name and its field association.
static fieldSummary queryFieldSummary (const word &fieldName, vtkCompositeDataSet *data)
Query composite DataSet for field name and its FieldAssociation.
static FieldAssociation queryFieldAssociation (const word &fieldName, vtkDataSet *dataset)
Query DataSet for field name and its field association.
static FieldAssociation queryFieldAssociation (const word &fieldName, vtkCompositeDataSet *data)
Query composite DataSet for field name and its FieldAssociation.
static void addMagField (const word &fieldName, vtkFieldData *fieldData)
Add "mag(..)" field for filters that only accept scalars.
static void addMagField (const word &fieldName, vtkDataSet *dataset)
Add "mag(..)" field for filters that only accept scalars.
static void addMagField (const word &fieldName, vtkCompositeDataSet *data)
Add "mag(..)" field for filters that only accept scalars.
Detailed Description
Base class for function object visualisation.
Dictionary controls
Property Description Required Default
functionObject The data source yes
clearObjects Remove file after use no no
liveObject Prefer simulation data source no true
The "live" keyword indiates that from within the simulation (in memory) is preferred over data from disk (for example).
Source files
functionObjectBase.H
functionObjectBase.C
Definition at line 82 of file functionObjectBase.H.
Constructor & Destructor Documentation
functionObjectBase (const functionObjectBase &) protected delete
No copy construct.
functionObjectBase (const stateFunctionObject & state, const dictionary & dict, const HashPtrTable< Function1< vector >> & colours)
Construct from dictionary.
Definition at line 65 of file functionObjectBase.C.
virtual ~functionObjectBase () virtual default
Destructor.
Member Function Documentation
Foam::fileName getFileName (const word & keyword, const word & subDictName) const protected
Retrieve the filename used to create the scene object using information stored via the stateFunctionObject.
Parameters
keyword is normally "file"
subDictName is the sub-dictionary name, which is often the fieldName when one file is used per field.
Eg,
*     T
*     {
*         file    "<case>/relpath/T_object.vtk";
*     }
*     defaultCloud
*     {
*         file    "<case>/relpath/cloud_0001.vtp";
*         fields  (T U);
*     }
*
Definition at line 27 of file functionObjectBase.C.
References dict, string::expand(), f(), functionObjectBase::functionObjectName_, stateFunctionObject::getObjectDict(), dictionary::readIfPresent(), and functionObjectBase::state_.
bool removeFile (const word & keyword, const word & subDictName) protected
Remove file used to create the scene object.
Same naming semantics as getFileName.
Note
does not change the stateFunctionObject
Definition at line 46 of file functionObjectBase.C.
void operator= (const functionObjectBase &) protected delete
No copy assignment.
bool clear () virtual
Clear files used to create the object(s)
Reimplemented in functionObjectCloud, functionObjectSurface, and functionObjectLine.
Definition at line 81 of file functionObjectBase.C.
Member Data Documentation
const stateFunctionObject& state_ protected
Reference to the state.
Definition at line 93 of file functionObjectBase.H.
Referenced by functionObjectBase::getFileName().
word functionObjectName_ protected
The function object name that provides the source data.
Definition at line 98 of file functionObjectBase.H.
Referenced by functionObjectBase::getFileName().
bool liveObject_ protected
Flag to indicate "live" (simulation) data source should be used.
Definition at line 103 of file functionObjectBase.H.
bool clearObjects_ protected
Flag to indicate that source data should be cleared after use.
Definition at line 108 of file functionObjectBase.H.
The documentation for this class was generated from the following files:
src/functionObjects/graphics/runTimePostProcessing/functionObjectBase.H
src/functionObjects/graphics/runTimePostProcessing/functionObjectBase.C