OpenFOAM: LESModel< BasicTurbulenceModel > Class Template Reference
LESModel< BasicTurbulenceModel > Class Template Reference
Templated abstract base class for LES SGS models.
Public Types
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()=default
Destructor.
virtual bool read ()
Read model coefficients if they have changed.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
virtual void correct ()
Solve the turbulence equations and correct the turbulence viscosity.
Static Public Member Functions
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Protected Member Functions
virtual void printCoeffs (const word &type)
Print model coefficients.
LESModel (const LESModel &)=delete
No copy construct.
void operator= (const LESModel &)=delete
No copy assignment.
Protected Attributes
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModel< BasicTurbulenceModel >
Templated abstract base class for LES SGS models.
Source files
LESModel.H
LESModel.C
Definition at line 55 of file LESModel.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 125 of file LESModel.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 126 of file LESModel.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 127 of file LESModel.H.
Constructor & Destructor Documentation
LESModel (const LESModel< BasicTurbulenceModel > &) protected delete
No copy construct.
LESModel (const word & type, const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName)
Construct from components.
Definition at line 40 of file LESModel.C.
virtual ~LESModel () virtual default
Destructor.
Member Function Documentation
void printCoeffs (const word & type) protected virtual
Print model coefficients.
Definition at line 27 of file LESModel.C.
References Foam::endl(), and Foam::Info.
void operator= (const LESModel< BasicTurbulenceModel > &) protected delete
No copy assignment.
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , LESModel< BasicTurbulenceModel > , dictionary , (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName) , (alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
Foam::autoPtr< Foam::LESModel< BasicTurbulenceModel > > New (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName) static
Return a reference to the selected LES model.
Definition at line 122 of file LESModel.C.
References Foam::constant::atomic::alpha, TimePaths::constant(), IOobject::db(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), IOobject::group(), IOobject::groupName(), Foam::Info, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE, phi, rho, dictionary::subDict(), IOobject::time(), and U.
bool read () virtual
Read model coefficients if they have changed.
Reimplemented in SpalartAllmarasDES< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, SpalartAllmarasIDDES< BasicTurbulenceModel >, NicenoKEqn< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, SmagorinskyZhang< BasicTurbulenceModel >, DeardorffDiffStress< BasicTurbulenceModel >, continuousGasKEqn< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, SpalartAllmarasDDES< BasicTurbulenceModel >, dynamicLagrangian< BasicTurbulenceModel >, ReynoldsStress< LESModel< BasicTurbulenceModel > >, LESeddyViscosity< BasicTurbulenceModel >, eddyViscosity< LESModel< BasicTurbulenceModel > >, and linearViscousStress< LESModel< BasicTurbulenceModel > >.
Definition at line 174 of file LESModel.C.
virtual const dictionary& coeffDict () const inline virtual
Const access to the coefficients dictionary.
Definition at line 210 of file LESModel.H.
const dimensionedScalar& kMin () const inline
Return the lower allowable limit for k (default: SMALL)
Definition at line 218 of file LESModel.H.
References nu, and nut.
dimensionedScalar& kMin () inline
Allow kMin to be changed.
Definition at line 226 of file LESModel.H.
const volScalarField& delta () const inline
Access function to filter width.
Definition at line 234 of file LESModel.H.
virtual tmp<volScalarField> nuEff () const inline virtual
Return the effective viscosity.
Definition at line 243 of file LESModel.H.
virtual tmp<scalarField> nuEff (const label patchi) const inline virtual
Return the effective viscosity on patch.
Definition at line 258 of file LESModel.H.
void correct () virtual
Solve the turbulence equations and correct the turbulence viscosity.
Reimplemented in SpalartAllmarasDES< BasicTurbulenceModel >, dynamicKEqn< BasicTurbulenceModel >, Smagorinsky< BasicTurbulenceModel >, WALE< BasicTurbulenceModel >, ReynoldsStress< LESModel< BasicTurbulenceModel > >, dynamicLagrangian< BasicTurbulenceModel >, kEqn< BasicTurbulenceModel >, DeardorffDiffStress< BasicTurbulenceModel >, eddyViscosity< LESModel< BasicTurbulenceModel > >, and linearViscousStress< LESModel< BasicTurbulenceModel > >.
Definition at line 195 of file LESModel.C.
Member Data Documentation
dictionary LESDict_ protected
LES coefficients dictionary.
Definition at line 67 of file LESModel.H.
Switch turbulence_ protected
Turbulence on/off flag.
Definition at line 72 of file LESModel.H.
Switch printCoeffs_ protected
Flag to print the model coeffs at run-time.
Definition at line 77 of file LESModel.H.
dictionary coeffDict_ protected
Model coefficients dictionary.
Definition at line 82 of file LESModel.H.
dimensionedScalar kMin_ protected
Lower limit of k.
Definition at line 87 of file LESModel.H.
dimensionedScalar epsilonMin_ protected
Lower limit of epsilon.
Definition at line 92 of file LESModel.H.
dimensionedScalar omegaMin_ protected
Lower limit for omega.
Definition at line 97 of file LESModel.H.
autoPtr<Foam::LESdelta> delta_ protected
Run-time selectable delta model.
Definition at line 102 of file LESModel.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESModel/LESModel.H
src/TurbulenceModels/turbulenceModels/LES/LESModel/LESModel.C