OpenFOAM: cellModel Class Reference
cellModel Class Reference
Maps a geometry to a set of cell primitives.
Public Types
enum modelType {
UNKNOWN = 0, HEX = 3, WEDGE = 4, PRISM = 5,
PYR = 6, TET = 7, SPLITHEX = 8, TETWEDGE = 9
}
Enumeration of commonly used cellModel types.
Public Member Functions
cellModel (Istream &is)
Construct from Istream.
autoPtr< cellModel > clone () const
Return clone.
const word & name () const
Return model name.
label index () const
Return index of model in the model list.
label nPoints () const
Return number of points.
label nEdges () const
Return number of edges.
label nFaces () const
Return number of faces.
const edgeList & modelEdges () const
Return a raw list of model edges.
const faceList & modelFaces () const
Return a raw list of model faces.
edgeList edges (const labelUList &pointLabels) const
Return list of edges.
faceList faces (const labelUList &pointLabels) const
Return list of faces.
vector centre (const labelList &pointLabels, const UList< point > &points) const
Vector centroid.
scalar mag (const labelList &pointLabels, const UList< point > &points) const
Cell volume.
InfoProxy< cellModel > info () const
Return info proxy.
bool writeData (Ostream &os) const
WriteData member function required by regIOobject.
Static Public Member Functions
static const cellModel * ptr (const modelType model)
Look up pointer to cellModel by enumeration, or nullptr on failure.
static const cellModel * ptr (const word &modelName)
Look up pointer to cellModel by name, or nullptr on failure.
static const cellModel * ptr (const label modelIndex)
Look up pointer to cellModel by index, or nullptr on failure.
static const cellModel & ref (const modelType model)
Look up reference to cellModel by enumeration. Fatal on failure.
static const cellModel & ref (const word &modelName)
Look up reference to cellModel by name. Fatal on failure.
static const cellModel & ref (const label modelIndex)
Look up reference to cellModel by index. Fatal on failure.
static autoPtr< cellModel > New (Istream &is)
Return a new cellModel on free-store created from Istream.
Static Public Attributes
static const Enum< modelType > modelNames
Names of commonly used cellModels corresponding to modelType.
Friends
Ostream & operator<< (Ostream &os, const cellModel &cm)
Detailed Description
Maps a geometry to a set of cell primitives.
This enables geometric cell data to be calculated without access to the primitive geometric level. This means mapping a 3D geometry to a set of pyramids which are each described by a cell face and the cell centre point.
Also includes a static collection of cell models (normally loaded from etc/cellModels), and a means of looking them up.
Source files
cellModel.H
cellModelI.H
cellModel.C
cellModels.C
cellModelIO.C
Definition at line 68 of file cellModel.H.
Member Enumeration Documentation
enum modelType
Enumeration of commonly used cellModel types.
The indices must match those in "etc/cellModels"
Enumerator
UNKNOWN
unknown
HEX
hex
WEDGE
wedge
PRISM
prism
PYR
pyr
TET
tet
SPLITHEX
splitHex
TETWEDGE
tetWedge
Definition at line 77 of file cellModel.H.
Constructor & Destructor Documentation
cellModel (Istream & is)
Construct from Istream.
Definition at line 26 of file cellModelIO.C.
References dict, dictionaryEntry::dict(), entry::keyword(), dictionary::null, and dictionary::readEntry().
Member Function Documentation
const Foam::cellModel * ptr (const modelType model) static
Look up pointer to cellModel by enumeration, or nullptr on failure.
Definition at line 113 of file cellModels.C.
Referenced by Foam::cellModeller::lookup(), STARCDMeshReader::readCells(), and tetCell::tetCellShape().
const Foam::cellModel * ptr (const word & modelName) static
Look up pointer to cellModel by name, or nullptr on failure.
Definition at line 119 of file cellModels.C.
const Foam::cellModel * ptr (const label modelIndex) static
Look up pointer to cellModel by index, or nullptr on failure.
Definition at line 139 of file cellModels.C.
const Foam::cellModel & ref (const modelType model) static
Look up reference to cellModel by enumeration. Fatal on failure.
Definition at line 150 of file cellModels.C.
Referenced by STARCDMeshReader::readBoundary(), and STARCDMeshReader::readCells().
const Foam::cellModel & ref (const word & modelName) static
Look up reference to cellModel by name. Fatal on failure.
Definition at line 165 of file cellModels.C.
const Foam::cellModel & ref (const label modelIndex) static
Look up reference to cellModel by index. Fatal on failure.
Definition at line 180 of file cellModels.C.
static autoPtr<cellModel> New (Istream & is) inline static
Return a new cellModel on free-store created from Istream.
Definition at line 194 of file cellModel.H.
autoPtr<cellModel> clone () const inline
Return clone.
Definition at line 202 of file cellModel.H.
const Foam::word & name () const inline
Return model name.
Definition at line 23 of file cellModelI.H.
Foam::label index () const inline
Return index of model in the model list.
Definition at line 29 of file cellModelI.H.
Referenced by STARCDMeshReader::readBoundary().
Foam::label nPoints () const inline
Return number of points.
Definition at line 35 of file cellModelI.H.
Foam::label nEdges () const inline
Return number of edges.
Definition at line 41 of file cellModelI.H.
Foam::label nFaces () const inline
Return number of faces.
Definition at line 47 of file cellModelI.H.
const Foam::edgeList & modelEdges () const inline
Return a raw list of model edges.
Definition at line 53 of file cellModelI.H.
const Foam::faceList & modelFaces () const inline
Return a raw list of model faces.
Definition at line 59 of file cellModelI.H.
Foam::edgeList edges (const labelUList & pointLabels) const inline
Return list of edges.
Definition at line 68 of file cellModelI.H.
Foam::faceList faces (const labelUList & pointLabels) const inline
Return list of faces.
Definition at line 92 of file cellModelI.H.
Referenced by cellModel::centre().
Foam::vector centre (const labelList & pointLabels, const UList< point > & points) const
Vector centroid.
Definition at line 28 of file cellModel.C.
References Foam::endl(), cellModel::faces(), forAll, i, cellModel::mag(), UList< T >::size(), WarningInFunction, and Foam::Zero.
Foam::scalar mag (const labelList & pointLabels, const UList< point > & points) const
Cell volume.
Definition at line 85 of file cellModel.C.
Referenced by cellModel::centre().
InfoProxy<cellModel> info () const inline
Return info proxy.
Used to print information to a stream
Definition at line 279 of file cellModel.H.
bool writeData (Ostream & os) const inline
WriteData member function required by regIOobject.
Definition at line 287 of file cellModel.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const cellModel & cm) friend
Member Data Documentation
const Foam::Enum< Foam::cellModel::modelType > modelNames static
Names of commonly used cellModels corresponding to modelType.
The names must match those in "etc/cellModels"
Definition at line 94 of file cellModel.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/cellModel/cellModel.H
src/OpenFOAM/meshes/meshShapes/cellModel/cellModel.C
src/OpenFOAM/meshes/meshShapes/cellModel/cellModelI.H
src/OpenFOAM/meshes/meshShapes/cellModel/cellModelIO.C
src/OpenFOAM/meshes/meshShapes/cellModel/cellModels.C