OpenFOAM: cellInfo Class Reference
cellInfo Class Reference
Holds information regarding type of cell. Used in inside/outside determination in cellClassification.
Public Member Functions
cellInfo ()
Construct null.
cellInfo (const label)
Construct from cType.
cellInfo (const cellInfo &)
Construct as copy.
label type () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const cellInfo &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &patch, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &patch, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const cellInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const cellInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const cellInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const cellInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const cellInfo &) const
bool operator!= (const cellInfo &) const
Friends
Ostream & operator<< (Ostream &, const cellInfo &)
Istream & operator>> (Istream &, cellInfo &)
Detailed Description
Holds information regarding type of cell. Used in inside/outside determination in cellClassification.
Source files
cellInfo.H
cellInfoI.H
cellInfo.C
Definition at line 60 of file cellInfo.H.
Constructor & Destructor Documentation
cellInfo () inline
Construct null.
Definition at line 91 of file cellInfoI.H.
cellInfo (const label type) inline
Construct from cType.
Definition at line 98 of file cellInfoI.H.
cellInfo (const cellInfo & w2) inline
Construct as copy.
Definition at line 105 of file cellInfoI.H.
Member Function Documentation
label type () const inline
Definition at line 110 of file cellInfo.H.
Referenced by cellInfo::operator!=().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 114 of file cellInfoI.H.
bool sameGeometry (const polyMesh & , const cellInfo & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 123 of file cellInfoI.H.
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 138 of file cellInfoI.H.
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 162 of file cellInfoI.H.
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 151 of file cellInfoI.H.
bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const cellInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 175 of file cellInfoI.H.
bool updateFace (const polyMesh & , const label thisFacei, const label neighbourCelli, const cellInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 199 of file cellInfoI.H.
bool updateFace (const polyMesh & , const label thisFacei, const cellInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 222 of file cellInfoI.H.
bool equal (const cellInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 244 of file cellInfoI.H.
bool operator== (const cellInfo & rhs) const inline
Definition at line 255 of file cellInfoI.H.
References Foam::operator==().
bool operator!= (const cellInfo & rhs) const inline
Definition at line 261 of file cellInfoI.H.
References cellInfo::type(), and Foam::type().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const cellInfo &) friend
Istream& operator>> (Istream & , cellInfo &) friend
The documentation for this class was generated from the following files:
src/meshTools/cellClassification/cellInfo.H
src/meshTools/cellClassification/cellInfoI.H