OpenFOAM: barotropicCompressibilityModel Class Reference
barotropicCompressibilityModel Class Reference abstract
Abstract class for barotropic compressibility models.
Public Member Functions
TypeName ("barotropicCompressibilityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, barotropicCompressibilityModel, dictionary,(const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName),(compressibilityProperties, gamma, psiName))
barotropicCompressibilityModel (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Construct from components.
virtual ~barotropicCompressibilityModel ()=default
Destructor.
const dictionary & compressibilityProperties () const
Return the phase transport properties dictionary.
const volScalarField & psi () const
Return the compressibility.
virtual void correct ()=0
Correct the compressibility.
virtual bool read (const dictionary &compressibilityProperties)=0
Read compressibilityProperties dictionary.
Static Public Member Functions
static autoPtr
< barotropicCompressibilityModel > New (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName="psi")
Return a reference to the selected compressibility model.
Protected Member Functions
barotropicCompressibilityModel (const barotropicCompressibilityModel &)=delete
No copy construct.
void operator= (const barotropicCompressibilityModel &)=delete
No copy assignment.
Protected Attributes
dictionary compressibilityProperties_
volScalarField psi_
const volScalarField & gamma_
Detailed Description
Abstract class for barotropic compressibility models.
Source files
barotropicCompressibilityModel.H
barotropicCompressibilityModel.C
newbarotropicCompressibilityModel.C
Definition at line 61 of file barotropicCompressibilityModel.H.
Constructor & Destructor Documentation
barotropicCompressibilityModel (const barotropicCompressibilityModel &) protected delete
No copy construct.
barotropicCompressibilityModel (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi")
Construct from components.
Definition at line 37 of file barotropicCompressibilityModel.C.
virtual ~barotropicCompressibilityModel () virtual default
Destructor.
Member Function Documentation
void operator= (const barotropicCompressibilityModel &) protected delete
No copy assignment.
TypeName ("barotropicCompressibilityModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , barotropicCompressibilityModel , dictionary , (const dictionary &compressibilityProperties, const volScalarField &gamma, const word &psiName) , (compressibilityProperties, gamma, psiName))
Foam::autoPtr< Foam::barotropicCompressibilityModel > New (const dictionary & compressibilityProperties, const volScalarField & gamma, const word & psiName = "psi") static
Return a reference to the selected compressibility model.
Definition at line 28 of file barotropicCompressibilityModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, gamma, dictionary::get(), and Foam::Info.
const dictionary& compressibilityProperties () const inline
Return the phase transport properties dictionary.
Definition at line 151 of file barotropicCompressibilityModel.H.
const volScalarField& psi () const inline
Return the compressibility.
Definition at line 159 of file barotropicCompressibilityModel.H.
virtual void correct () pure virtual
Correct the compressibility.
Implemented in Wallis, Chung, and linear.
bool read (const dictionary & compressibilityProperties) pure virtual
Read compressibilityProperties dictionary.
Implemented in Wallis, Chung, and linear.
Definition at line 62 of file barotropicCompressibilityModel.C.
Member Data Documentation
dictionary compressibilityProperties_ protected
Definition at line 68 of file barotropicCompressibilityModel.H.
volScalarField psi_ protected
Definition at line 70 of file barotropicCompressibilityModel.H.
const volScalarField& gamma_ protected
Definition at line 71 of file barotropicCompressibilityModel.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModel.H
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModel.C
src/thermophysicalModels/barotropicCompressibilityModel/barotropicCompressibilityModel/barotropicCompressibilityModelNew.C