OpenFOAM: option Class Reference
option Class Reference
Finite volume options abstract base class. Provides a base set of controls, e.g.:
Classes
class iNew
Return pointer to new fvOption object created.
Public Member Functions
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, option, dictionary,(const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh),(name, modelType, dict, mesh))
option (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh)
Construct from components.
autoPtr< option > clone () const
Return clone.
virtual ~option ()=default
Destructor.
const word & name () const
Return const access to the source name.
const fvMesh & mesh () const
Return const access to the mesh database.
const dictionary & coeffs () const
Return dictionary.
bool active () const
Return const access to the source active flag.
void setApplied (const label fieldi)
Set the applied flag to true for field index fieldi.
Switch & active ()
Return access to the source active flag.
virtual bool isActive ()
Is the source active?
virtual label applyToField (const word &fieldName) const
Return index of field name if found in fieldNames list.
virtual void checkApplied () const
Check that the source has been applied.
virtual void addSup (fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< scalar > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< vector > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void addSup (const volScalarField &alpha, const volScalarField &rho, fvMatrix< tensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< scalar > &eqn, const label fieldi)
virtual void constrain (fvMatrix< vector > &eqn, const label fieldi)
virtual void constrain (fvMatrix< sphericalTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< symmTensor > &eqn, const label fieldi)
virtual void constrain (fvMatrix< tensor > &eqn, const label fieldi)
virtual void correct (volScalarField &field)
virtual void correct (volVectorField &field)
virtual void correct (volSphericalTensorField &field)
virtual void correct (volSymmTensorField &field)
virtual void correct (volTensorField &field)
virtual void writeHeader (Ostream &) const
Write the source header information.
virtual void writeFooter (Ostream &) const
Write the source footer information.
virtual void writeData (Ostream &) const
Write the source properties.
virtual bool read (const dictionary &dict)
Read source dictionary.
Static Public Member Functions
static autoPtr< option > New (const word &name, const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected fvOption model.
Public Attributes
bool log
Switch write log to Info.
Protected Attributes
const word name_
Source name.
const word modelType_
Model type.
const fvMesh & mesh_
Reference to the mesh database.
dictionary dict_
Top level source dictionary.
dictionary coeffs_
Dictionary containing source coefficients.
Switch active_
Source active flag.
wordList fieldNames_
Field names to apply source to - populated by derived models.
List< bool > applied_
Applied flag list - corresponds to each fieldNames_ entry.
Detailed Description
Finite volume options abstract base class. Provides a base set of controls, e.g.:
    type            scalarExplicitSource    // source type
    active          on;                     // on/off switch
Note
On evaluation, source/sink options are to be added to the equation R.H.S.
Source files
fvOption.H
fvOption.C
fvOptionIO.C
Definition at line 65 of file fvOption.H.
Constructor & Destructor Documentation
option (const word & name, const word & modelType, const dictionary & dict, const fvMesh & mesh)
Construct from components.
Definition at line 40 of file fvOption.C.
virtual ~option () virtual default
Destructor.
Member Function Documentation
TypeName ("option")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , option , dictionary , (const word &name, const word &modelType, const dictionary &dict, const fvMesh &mesh) , (name, modelType, dict, mesh))
autoPtr<option> clone () const inline
Return clone.
Definition at line 157 of file fvOption.H.
Foam::autoPtr< Foam::fv::option > New (const word & name, const dictionary & dict, const fvMesh & mesh) static
Return a reference to the selected fvOption model.
Definition at line 64 of file fvOption.C.
const Foam::word & name () const inline
Return const access to the source name.
Definition at line 23 of file fvOptionI.H.
Referenced by optionAdjointList::correct(), and optionList::source().
const Foam::fvMesh & mesh () const inline
Return const access to the mesh database.
Definition at line 29 of file fvOptionI.H.
References option::name_.
const Foam::dictionary & coeffs () const inline
Return dictionary.
Definition at line 35 of file fvOptionI.H.
bool active () const inline
Return const access to the source active flag.
Definition at line 41 of file fvOptionI.H.
void setApplied (const label fieldi) inline
Set the applied flag to true for field index fieldi.
Definition at line 47 of file fvOptionI.H.
Referenced by optionAdjointList::correct(), and optionList::source().
Foam::Switch & active () inline
Return access to the source active flag.
Definition at line 53 of file fvOptionI.H.
bool isActive () virtual
Is the source active?
Reimplemented in cellSetOption.
Definition at line 101 of file fvOption.C.
Referenced by optionAdjointList::correct(), and optionList::source().
Foam::label applyToField (const word & fieldName) const virtual
Return index of field name if found in fieldNames list.
Definition at line 107 of file fvOption.C.
Referenced by optionAdjointList::correct(), and optionList::source().
void checkApplied () const virtual
Check that the source has been applied.
Definition at line 113 of file fvOption.C.
void addSup (fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in effectivenessHeatExchangerSource, solidificationMeltingSource, VoFSolidificationMeltingSource, interRegionHeatTransferModel, multiphaseStabilizedTurbulence, and multiphaseMangrovesTurbulenceModel.
Definition at line 128 of file fvOption.C.
Referenced by optionList::source().
void addSup (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in rotorDiskSource, solidificationMeltingSource, directionalPressureGradientExplicitSource, actuationDiskSource, VoFSolidificationMeltingSource, radialActuationDiskSource, meanVelocityForce, interRegionExplicitPorositySource, acousticDampingSource, multiphaseMangrovesSource, explicitPorositySource, tabulatedAccelerationSource, and buoyancyForce.
Definition at line 136 of file fvOption.C.
void addSup (fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 152 of file fvOption.C.
void addSup (fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 144 of file fvOption.C.
void addSup (fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 160 of file fvOption.C.
void addSup (const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in effectivenessHeatExchangerSource, solidificationMeltingSource, jouleHeatingSource, VoFSolidificationMeltingSource, interRegionHeatTransferModel, multiphaseMangrovesTurbulenceModel, multiphaseStabilizedTurbulence, viscousDissipation, radiation, and buoyancyEnergy.
Definition at line 168 of file fvOption.C.
void addSup (const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in rotorDiskSource, solidificationMeltingSource, directionalPressureGradientExplicitSource, VoFSolidificationMeltingSource, actuationDiskSource, radialActuationDiskSource, interRegionExplicitPorositySource, meanVelocityForce, acousticDampingSource, multiphaseMangrovesSource, explicitPorositySource, tabulatedAccelerationSource, and buoyancyForce.
Definition at line 177 of file fvOption.C.
void addSup (const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 195 of file fvOption.C.
void addSup (const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 186 of file fvOption.C.
void addSup (const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 204 of file fvOption.C.
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< scalar > & eqn, const label fieldi) virtual
Definition at line 213 of file fvOption.C.
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in acousticDampingSource, and explicitPorositySource.
Definition at line 225 of file fvOption.C.
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 249 of file fvOption.C.
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 237 of file fvOption.C.
void addSup (const volScalarField & alpha, const volScalarField & rho, fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 261 of file fvOption.C.
void constrain (fvMatrix< scalar > & eqn, const label fieldi) virtual
Reimplemented in fixedTemperatureConstraint.
Definition at line 272 of file fvOption.C.
void constrain (fvMatrix< vector > & eqn, const label fieldi) virtual
Reimplemented in directionalPressureGradientExplicitSource, meanVelocityForce, and velocityDampingConstraint.
Definition at line 276 of file fvOption.C.
void constrain (fvMatrix< sphericalTensor > & eqn, const label fieldi) virtual
Definition at line 281 of file fvOption.C.
void constrain (fvMatrix< symmTensor > & eqn, const label fieldi) virtual
Definition at line 289 of file fvOption.C.
void constrain (fvMatrix< tensor > & eqn, const label fieldi) virtual
Definition at line 296 of file fvOption.C.
void correct (volScalarField & field) virtual
Reimplemented in multiphaseStabilizedTurbulence, and limitTemperature.
Definition at line 300 of file fvOption.C.
Referenced by optionAdjointList::correct().
void correct (volVectorField & field) virtual
Reimplemented in directionalPressureGradientExplicitSource, meanVelocityForce, and limitVelocity.
Definition at line 304 of file fvOption.C.
void correct (volSphericalTensorField & field) virtual
Definition at line 308 of file fvOption.C.
void correct (volSymmTensorField & field) virtual
Definition at line 312 of file fvOption.C.
void correct (volTensorField & field) virtual
Definition at line 316 of file fvOption.C.
void writeHeader (Ostream & os) const virtual
Write the source header information.
Definition at line 26 of file fvOptionIO.C.
void writeFooter (Ostream & os) const virtual
Write the source footer information.
Definition at line 32 of file fvOptionIO.C.
References Ostream::beginBlock(), and option::name_.
void writeData (Ostream & os) const virtual
Write the source properties.
Reimplemented in directionalPressureGradientExplicitSource, and velocityDampingConstraint.
Definition at line 38 of file fvOptionIO.C.
References Ostream::endBlock().
bool read (const dictionary & dict) virtual
Read source dictionary.
Reimplemented in effectivenessHeatExchangerSource, rotorDiskSource, solidificationMeltingSource, directionalPressureGradientExplicitSource, jouleHeatingSource, VoFSolidificationMeltingSource, actuationDiskSource, cellSetOption, interRegionHeatTransferModel, SemiImplicitSource< Type >, tabulatedNTUHeatTransfer, CodedSource< Type >, meanVelocityForce, multiphaseStabilizedTurbulence, multiphaseMangrovesTurbulenceModel, acousticDampingSource, interRegionExplicitPorositySource, radialActuationDiskSource, multiphaseMangrovesSource, explicitPorositySource, fixedTemperatureConstraint, tabulatedAccelerationSource, velocityDampingConstraint, PhaseLimitStabilization< Type >, viscousDissipation, limitTemperature, tabulatedHeatTransfer, variableHeatTransfer, limitVelocity, buoyancyForce, interRegionOption, radiation, buoyancyEnergy, FixedValueConstraint< Type >, and constantHeatTransfer.
Definition at line 48 of file fvOptionIO.C.
Referenced by radiation::addSup().
Member Data Documentation
const word name_ protected
Source name.
Definition at line 74 of file fvOption.H.
Referenced by option::mesh(), and option::writeFooter().
const word modelType_ protected
Model type.
Definition at line 79 of file fvOption.H.
const fvMesh& mesh_ protected
Reference to the mesh database.
Definition at line 84 of file fvOption.H.
dictionary dict_ protected
Top level source dictionary.
Definition at line 89 of file fvOption.H.
dictionary coeffs_ protected
Dictionary containing source coefficients.
Definition at line 94 of file fvOption.H.
Switch active_ protected
Source active flag.
Definition at line 99 of file fvOption.H.
wordList fieldNames_ protected
Field names to apply source to - populated by derived models.
Definition at line 104 of file fvOption.H.
Referenced by PhaseLimitStabilization< Type >::PhaseLimitStabilization().
List<bool> applied_ protected
Applied flag list - corresponds to each fieldNames_ entry.
Definition at line 109 of file fvOption.H.
Referenced by PhaseLimitStabilization< Type >::PhaseLimitStabilization().
bool log
Switch write log to Info.
Definition at line 122 of file fvOption.H.
The documentation for this class was generated from the following files:
src/finiteVolume/cfdTools/general/fvOptions/fvOption.H
src/finiteVolume/cfdTools/general/fvOptions/fvOption.C
src/finiteVolume/cfdTools/general/fvOptions/fvOptionI.H
src/finiteVolume/cfdTools/general/fvOptions/fvOptionIO.C