OpenFOAM: linear< Type > Class Template Reference
linear< Type > Class Template Reference
Surface interpolation schemes | Equation of state
Central-differencing interpolation scheme class.
Public Member Functions
TypeName ("linear")
Runtime type information.
linear (const fvMesh &mesh)
Construct from mesh.
linear (const fvMesh &mesh, Istream &)
Construct from Istream.
linear (const fvMesh &mesh, const surfaceScalarField &, Istream &)
Construct from faceFlux and Istream.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
linear (const Specie &sp, const scalar psi, const scalar rho0)
Construct from components.
linear (const dictionary &dict)
Construct from dictionary.
linear (const word &name, const linear &)
Construct as named copy.
autoPtr< linear > clone () const
Construct and return a clone.
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar H (const scalar p, const scalar T) const
Return enthalpy departure [J/kg].
scalar Cp (scalar p, scalar T) const
Return Cp departure [J/(kg K].
scalar E (const scalar p, const scalar T) const
Return internal energy departure [J/kg].
scalar Cv (scalar p, scalar T) const
Return Cv departure [J/(kg K].
scalar S (const scalar p, const scalar T) const
Return entropy [J/(kg K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar CpMCv (scalar p, scalar T) const
Return (Cp - Cv) [J/(kg K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const linear &)
void operator*= (const scalar)
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField
< typename innerProduct
< vector, Type >::type,
fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static autoPtr< linear > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField
< typename innerProduct
< typename SFType::value_type,
Type >::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Static Public Attributes
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
linear operator+ (const linear &, const linear &)
linear operator* (const scalar s, const linear &)
linear operator== (const linear &, const linear &)
Ostream & operator (Ostream &, const linear &)
Detailed Description
template<class Type>
class Foam::linear< Type >
Central-differencing interpolation scheme class.
Linear equation of state with constant compressibility.
Source files
linear.H
linear.C
    rho = rho0 + psi*p
Source files
linear.H
linearI.H
linear.C
Source files
linear.H
linear.C
Definition at line 51 of file linear.H.
Constructor & Destructor Documentation
linear (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 76 of file linear.H.
linear (const fvMesh & mesh, Istream &) inline
Construct from Istream.
Definition at line 84 of file linear.H.
linear (const fvMesh & mesh, const surfaceScalarField & , Istream &) inline
Construct from faceFlux and Istream.
Definition at line 93 of file linear.H.
linear (const Specie & sp, const scalar psi, const scalar rho0) inline
Construct from components.
Definition at line 27 of file linearI.H.
linear (const dictionary & dict)
Construct from dictionary.
Definition at line 27 of file linear.C.
linear (const word & name, const linear< Type > &) inline
Construct as named copy.
Member Function Documentation
TypeName ("linear< Type >")
Runtime type information.
tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors.
Implements surfaceInterpolationScheme< Type >.
Definition at line 109 of file linear.H.
References surfaceInterpolationScheme< Type >::interpolate(), and DimensionedField< Type, GeoMesh >::mesh().
Foam::autoPtr< Foam::linear< Specie > > clone () const inline
Construct and return a clone.
Definition at line 56 of file linearI.H.
Foam::autoPtr< Foam::linear< Specie > > New (const dictionary & dict) inline static
Definition at line 65 of file linearI.H.
static word typeName () inline static
Return the instantiated type name.
Definition at line 143 of file linear.H.
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 76 of file linearI.H.
Foam::scalar H (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kg].
Definition at line 83 of file linearI.H.
References p.
Foam::scalar Cp (scalar p, scalar T) const inline
Return Cp departure [J/(kg K].
Definition at line 90 of file linearI.H.
Foam::scalar E (const scalar p, const scalar T) const inline
Return internal energy departure [J/kg].
Definition at line 96 of file linearI.H.
Foam::scalar Cv (scalar p, scalar T) const inline
Return Cv departure [J/(kg K].
Definition at line 103 of file linearI.H.
Foam::scalar S (const scalar p, const scalar T) const inline
Return entropy [J/(kg K)].
Definition at line 110 of file linearI.H.
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 117 of file linearI.H.
References Foam::log(), and Foam::constant::standard::Pstd.
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 124 of file linearI.H.
Foam::scalar CpMCv (scalar p, scalar T) const inline
Return (Cp - Cv) [J/(kg K].
Definition at line 131 of file linearI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 38 of file linear.C.
void operator+= (const linear< Type > &) inline
Definition at line 141 of file linearI.H.
void operator*= (const scalar s) inline
Definition at line 160 of file linearI.H.
Friends And Related Function Documentation
linear operator+ (const linear< Type > & , const linear< Type > &) friend
linear operator* (const scalar s, const linear< Type > &) friend
linear operator== (const linear< Type > & , const linear< Type > &) friend
Ostream& operator (Ostream & , const linear< Type > &) friend
Member Data Documentation
const bool incompressible = false static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 154 of file linear.H.
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 159 of file linear.H.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/schemes/linear/linear.H
src/thermophysicalModels/specie/equationOfState/linear/linear.H
src/thermophysicalModels/specie/equationOfState/linear/linear.C
src/thermophysicalModels/specie/equationOfState/linear/linearI.H