OpenFOAM: septernion Class Reference
septernion Class Reference
Septernion class used to perform translations and rotations in 3D space.
Public Member Functions
septernion ()
Construct null.
septernion (const vector &t, const quaternion &r)
Construct given a translation vector and rotation quaternion.
septernion (const vector &t)
Construct a pure translation septernion given a translation vector.
septernion (const quaternion &r)
Construct a pure rotation septernion given a rotation quaternion.
septernion (const spatialTransform &st)
Construct a general septernion from the given spatialTransform.
septernion (Istream &)
Construct from Istream.
const vector & t () const
const quaternion & r () const
vector & t ()
quaternion & r ()
vector transformPoint (const vector &v) const
Transform the given coordinate point.
vector invTransformPoint (const vector &v) const
Inverse Transform the given coordinate point.
void operator= (const septernion &)
void operator*= (const septernion &)
void operator= (const vector &)
void operator+= (const vector &)
void operator-= (const vector &)
void operator= (const quaternion &)
void operator*= (const quaternion &)
void operator/= (const quaternion &)
void operator*= (const scalar)
void operator/= (const scalar)
Static Public Attributes
static const char *const typeName = "septernion"
static const septernion zero
static const septernion I
Friends
Istream & operator>> (Istream &is, septernion &)
Ostream & operator<< (Ostream &os, const septernion &C)
Detailed Description
Septernion class used to perform translations and rotations in 3D space.
It is composed of a translation vector and rotation quaternion and as such has seven components hence the name "septernion" from the Latin to be consistent with quaternion rather than "hepternion" derived from the Greek.
Source files
septernion.H
septernionI.H
septernion.C
Definition at line 62 of file septernion.H.
Constructor & Destructor Documentation
septernion () inline
Construct null.
Definition at line 23 of file septernionI.H.
septernion (const vector & t, const quaternion & r) inline
Construct given a translation vector and rotation quaternion.
Definition at line 26 of file septernionI.H.
septernion (const vector & t) inline explicit
Construct a pure translation septernion given a translation vector.
Definition at line 32 of file septernionI.H.
septernion (const quaternion & r) inline explicit
Construct a pure rotation septernion given a rotation quaternion.
Definition at line 38 of file septernionI.H.
septernion (const spatialTransform & st) inline explicit
Construct a general septernion from the given spatialTransform.
Definition at line 44 of file septernionI.H.
septernion (Istream & is)
Construct from Istream.
Definition at line 41 of file septernion.C.
Member Function Documentation
const Foam::vector & t () const inline
Definition at line 53 of file septernionI.H.
Referenced by Foam::operator!=(), Foam::operator*(), Foam::operator/(), and septernion::operator=().
const Foam::quaternion & r () const inline
Definition at line 59 of file septernionI.H.
Referenced by Foam::operator!=(), Foam::operator*(), Foam::operator/(), and septernion::operator=().
Foam::vector & t () inline
Definition at line 65 of file septernionI.H.
Foam::quaternion & r () inline
Definition at line 71 of file septernionI.H.
Foam::vector transformPoint (const vector & v) const inline
Transform the given coordinate point.
Definition at line 77 of file septernionI.H.
Foam::vector invTransformPoint (const vector & v) const inline
Inverse Transform the given coordinate point.
Definition at line 83 of file septernionI.H.
void operator= (const septernion & tr) inline
Definition at line 91 of file septernionI.H.
void operator*= (const septernion & tr) inline
Definition at line 97 of file septernionI.H.
void operator= (const vector & t) inline
Definition at line 104 of file septernionI.H.
References quaternion::invTransform(), septernion::r(), and septernion::t().
void operator+= (const vector & t) inline
Definition at line 110 of file septernionI.H.
References quaternion::I.
void operator-= (const vector & t) inline
Definition at line 115 of file septernionI.H.
void operator= (const quaternion & r) inline
Definition at line 121 of file septernionI.H.
void operator*= (const quaternion & r) inline
Definition at line 127 of file septernionI.H.
References Foam::Zero.
void operator/= (const quaternion & r) inline
Definition at line 133 of file septernionI.H.
References quaternion::invTransform().
void operator*= (const scalar s) inline
Definition at line 140 of file septernionI.H.
References quaternion::transform().
void operator/= (const scalar s) inline
Definition at line 146 of file septernionI.H.
References s.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, septernion &) friend
Ostream& operator<< (Ostream & os, const septernion & C) friend
Member Data Documentation
const char *const typeName = "septernion" static
Definition at line 81 of file septernion.H.
const Foam::septernion zero static
Definition at line 83 of file septernion.H.
const Foam::septernion I static
Definition at line 84 of file septernion.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/septernion/septernion.H
src/OpenFOAM/primitives/septernion/septernion.C
src/OpenFOAM/primitives/septernion/septernionI.H