OpenFOAM: findUniqueIntersectOp Class Reference
findUniqueIntersectOp Class Reference
Public Member Functions
findUniqueIntersectOp (const indexedOctree< treeDataFace > &tree, const List< pointIndexHit > &hits)
Construct from components.
bool operator() (const label index, const point &start, const point &end, point &intersectionPoint) const
Calculate intersection of triangle with ray. Sets result.
Public Member Functions inherited from treeDataFace::findIntersectOp
findIntersectOp (const indexedOctree< treeDataFace > &tree)
bool operator() (const label index, const point &start, const point &end, point &intersectionPoint) const
Calculate intersection of triangle with ray.
Public Attributes
const indexedOctree
< treeDataFace > & tree_
const List< pointIndexHit > & hits_
Detailed Description
Definition at line 40 of file meshSearch.C.
Constructor & Destructor Documentation
findUniqueIntersectOp (const indexedOctree< treeDataFace > & tree, const List< pointIndexHit > & hits) inline
Construct from components.
Definition at line 56 of file meshSearch.C.
Member Function Documentation
bool operator() (const label index, const point & start, const point & end, point & intersectionPoint) const inline
Calculate intersection of triangle with ray. Sets result.
accordingly
Definition at line 72 of file meshSearch.C.
References end(), primitiveMesh::faceAreas(), primitiveMesh::faces(), forAll, findUniqueIntersectOp::hits_, mesh, Foam::start, and findUniqueIntersectOp::tree_.
Member Data Documentation
const indexedOctree<treeDataFace>& tree_
Definition at line 46 of file meshSearch.C.
Referenced by findUniqueIntersectOp::operator()().
const List<pointIndexHit>& hits_
Definition at line 48 of file meshSearch.C.
Referenced by findUniqueIntersectOp::operator()().
The documentation for this class was generated from the following file:
src/meshTools/meshSearch/meshSearch.C