OpenFOAM: TableBase< Type > Class Template Reference
TableBase< Type > Class Template Reference
Base class for table with bounds handling, interpolation and integration.
Public Member Functions
TableBase (const word &name, const dictionary &dict)
Construct from dictionary - note table is not populated.
TableBase (const TableBase< Type > &tbl)
Copy constructor. Note: steals interpolator, tableSamples.
virtual ~TableBase ()
Destructor.
void check () const
Check the table for size and consistency.
bool checkMinBounds (const scalar x, scalar &xDash) const
Check minimum table bounds.
bool checkMaxBounds (const scalar x, scalar &xDash) const
Check maximum table bounds.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual Type value (const scalar x) const
Return Table value.
virtual Type integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< scalarField > x () const
Return the reference values.
virtual tmp< Field< Type > > y () const
Return the dependent values.
virtual void writeData (Ostream &os) const
Write all table data in dictionary format.
virtual void writeEntries (Ostream &os) const
Write keywords only in dictionary format.
Public Member Functions inherited from Function1< Type >
declareRunTimeSelectionTable (autoPtr, Function1, dictionary,(const word &entryName, const dictionary &dict),(entryName, dict))
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< Type > &f1)
Copy constructor.
virtual tmp< Function1< Type > > clone () const =0
Construct and return a clone.
virtual ~Function1 ()=default
Destructor.
const word & name () const
Return the name of the entry.
virtual tmp< Field< Type > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual tmp< Field< Type > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Protected Member Functions
const interpolationWeights & interpolator () const
Return (demand driven) interpolator.
void operator= (const TableBase< Type > &)=delete
No copy assignment.
Protected Attributes
const word name_
Table name.
const bounds::repeatableBounding bounding_
Handling for out-of-bound values.
const word interpolationScheme_
Interpolation type.
List< Tuple2< scalar, Type > > table_
Table data.
autoPtr< scalarField > tableSamplesPtr_
Extracted values.
autoPtr< interpolationWeights > interpolatorPtr_
Interpolator method.
labelList currentIndices_
Cached indices and weights.
scalarField currentWeights_
Protected Attributes inherited from Function1< Type >
const word name_
Name of entry.
Additional Inherited Members
Public Types inherited from Function1< Type >
typedef Type returnType
Static Public Member Functions inherited from Function1< Type >
static autoPtr< Function1< Type > > New (const word &entryName, const dictionary &dict, const word &redirectType=word::null)
Selector.
Detailed Description
template<class Type>
class Foam::Function1Types::TableBase< Type >
Base class for table with bounds handling, interpolation and integration.
Source files
TableBase.H
TableBase.C
Definition at line 54 of file TableBase.H.
Constructor & Destructor Documentation
TableBase (const word & name, const dictionary & dict)
Construct from dictionary - note table is not populated.
Definition at line 56 of file TableBase.C.
TableBase (const TableBase< Type > & tbl) explicit
Copy constructor. Note: steals interpolator, tableSamples.
Definition at line 82 of file TableBase.C.
~TableBase () virtual
Destructor.
Definition at line 97 of file TableBase.C.
Member Function Documentation
const Foam::interpolationWeights & interpolator () const protected
Return (demand driven) interpolator.
Definition at line 30 of file TableBase.C.
References UList< T >::first(), forAll, i, Foam::New(), and samples().
void operator= (const TableBase< Type > &) protected delete
No copy assignment.
void check () const
Check the table for size and consistency.
Definition at line 104 of file TableBase.C.
bool checkMinBounds (const scalar x, scalar & xDash) const
Check minimum table bounds.
Definition at line 136 of file TableBase.C.
bool checkMaxBounds (const scalar x, scalar & xDash) const
Check maximum table bounds.
Definition at line 194 of file TableBase.C.
void convertTimeBase (const Time & t) virtual
Convert time.
Reimplemented from Function1< Type >.
Definition at line 251 of file TableBase.C.
Type value (const scalar x) const virtual
Return Table value.
Reimplemented from Function1< Type >.
Definition at line 264 of file TableBase.C.
Type integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented from Function1< Type >.
Definition at line 293 of file TableBase.C.
Foam::tmp< Foam::scalarField > x () const virtual
Return the reference values.
Definition at line 312 of file TableBase.C.
Foam::tmp< Foam::Field< Type > > y () const virtual
Return the dependent values.
Definition at line 327 of file TableBase.C.
void writeData (Ostream & os) const virtual
Write all table data in dictionary format.
Reimplemented from Function1< Type >.
Reimplemented in CSV< Type >, and TableFile< Type >.
Definition at line 363 of file TableBase.C.
void writeEntries (Ostream & os) const virtual
Write keywords only in dictionary format.
Used for non-inline table types
Definition at line 342 of file TableBase.C.
Member Data Documentation
const word name_ protected
Table name.
Definition at line 65 of file TableBase.H.
const bounds::repeatableBounding bounding_ protected
Handling for out-of-bound values.
Definition at line 70 of file TableBase.H.
const word interpolationScheme_ protected
Interpolation type.
Definition at line 75 of file TableBase.H.
List<Tuple2<scalar, Type> > table_ protected
Table data.
Definition at line 80 of file TableBase.H.
autoPtr<scalarField> tableSamplesPtr_ mutable protected
Extracted values.
Definition at line 85 of file TableBase.H.
autoPtr<interpolationWeights> interpolatorPtr_ mutable protected
Interpolator method.
Definition at line 90 of file TableBase.H.
labelList currentIndices_ mutable protected
Cached indices and weights.
Definition at line 95 of file TableBase.H.
scalarField currentWeights_ mutable protected
Definition at line 97 of file TableBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/Table/TableBase.H
src/OpenFOAM/primitives/functions/Function1/Table/TableBase.C