OpenFOAM: pointPatch Class Reference
pointPatch Class Reference abstract
Basic pointPatch represents a set of points from the mesh.
Public Member Functions
TypeName ("basePatch")
Runtime type information.
pointPatch (const pointBoundaryMesh &bm)
Construct from boundary mesh.
virtual ~pointPatch ()=default
Destructor.
virtual const word & name () const =0
Return name.
virtual label size () const =0
Return size.
virtual label index () const =0
Return the index of this patch in the pointBoundaryMesh.
const pointBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
virtual bool coupled () const
Return true if this patch field is coupled.
virtual const labelList & meshPoints () const =0
Return mesh points.
virtual const vectorField & localPoints () const =0
Return mesh points.
virtual const vectorField & pointNormals () const =0
Return point normals.
virtual const word & constraintType () const
Return the constraint type this pointPatch implements.
virtual void applyConstraint (const label pointi, pointConstraint &) const
Accumulate the effect of constraint direction of this patch.
Protected Member Functions
virtual void initGeometry (PstreamBuffers &)
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)
Update of the patch topology.
pointPatch (const pointPatch &)=delete
No copy construct.
void operator= (const pointPatch &)=delete
No copy assignment.
Friends
class pointBoundaryMesh
Detailed Description
Basic pointPatch represents a set of points from the mesh.
Source files
pointPatch.H
pointPatch.C
Definition at line 54 of file pointPatch.H.
Constructor & Destructor Documentation
pointPatch (const pointPatch &) protected delete
No copy construct.
pointPatch (const pointBoundaryMesh & bm) inline explicit
Construct from boundary mesh.
Definition at line 131 of file pointPatch.H.
virtual ~pointPatch () virtual default
Destructor.
Member Function Documentation
virtual void initGeometry (PstreamBuffers &) inline protected virtual
Initialise the calculation of the patch geometry.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 73 of file pointPatch.H.
virtual void calcGeometry (PstreamBuffers &) inline protected virtual
Calculate the patch geometry.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, coupledFacePointPatch, and facePointPatch.
Definition at line 79 of file pointPatch.H.
virtual void initMovePoints (PstreamBuffers & , const pointField &) inline protected virtual
Initialise the patches for moving points.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 85 of file pointPatch.H.
virtual void movePoints (PstreamBuffers & , const pointField &) inline protected virtual
Correct patches after moving points.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 91 of file pointPatch.H.
virtual void initUpdateMesh (PstreamBuffers &) inline protected virtual
Initialise the update of the patch topology.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 97 of file pointPatch.H.
virtual void updateMesh (PstreamBuffers &) inline protected virtual
Update of the patch topology.
Reimplemented in cyclicACMIPointPatch, cyclicAMIPointPatch, and facePointPatch.
Definition at line 103 of file pointPatch.H.
void operator= (const pointPatch &) protected delete
No copy assignment.
TypeName ("basePatch")
Runtime type information.
virtual const word& name () const pure virtual
Return name.
Implemented in facePointPatch.
virtual label size () const pure virtual
Return size.
Implemented in facePointPatch.
virtual label index () const pure virtual
Return the index of this patch in the pointBoundaryMesh.
Implemented in facePointPatch.
const pointBoundaryMesh& boundaryMesh () const inline
Return boundaryMesh reference.
Definition at line 163 of file pointPatch.H.
Referenced by patchExprFieldBase::getFvPatch().
virtual bool coupled () const inline virtual
Return true if this patch field is coupled.
Reimplemented in facePointPatch, and cyclicACMIPointPatch.
Definition at line 171 of file pointPatch.H.
virtual const labelList& meshPoints () const pure virtual
Return mesh points.
Implemented in facePointPatch.
virtual const vectorField& localPoints () const pure virtual
Return mesh points.
Implemented in facePointPatch.
Referenced by sixDoFRigidBodyDisplacementPointPatchVectorField::sixDoFRigidBodyDisplacementPointPatchVectorField().
virtual const vectorField& pointNormals () const pure virtual
Return point normals.
Implemented in facePointPatch, cyclicSlipPointPatch, and nonuniformTransformCyclicPointPatch.
virtual const word& constraintType () const inline virtual
Return the constraint type this pointPatch implements.
Reimplemented in processorPointPatch, cyclicACMIPointPatch, cyclicAMIPointPatch, cyclicPointPatch, symmetryPlanePointPatch, wedgePointPatch, symmetryPointPatch, and emptyPointPatch.
Definition at line 194 of file pointPatch.H.
Referenced by pointPatchField< T >::New().
virtual void applyConstraint (const label pointi, pointConstraint &) const inline virtual
Accumulate the effect of constraint direction of this patch.
Reimplemented in symmetryPlanePointPatch, wedgePointPatch, cyclicSlipPointPatch, nonuniformTransformCyclicPointPatch, symmetryPointPatch, and emptyPointPatch.
Definition at line 203 of file pointPatch.H.
Friends And Related Function Documentation
friend class pointBoundaryMesh friend
Definition at line 68 of file pointPatch.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/pointMesh/pointPatches/pointPatch/pointPatch.H