OpenFOAM: polyAddFace Class Reference
polyAddFace Class Reference
A face addition data class. A face can be inflated either from a point or from another face and can either be in internal or a boundary face.
Public Member Functions
TypeName ("addFace")
Runtime type information.
polyAddFace ()
Construct null. Used for constructing lists.
polyAddFace (const face &f, const label owner, const label neighbour, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip)
Construct from components.
virtual autoPtr< topoAction > clone () const
Construct and return a clone.
const face & newFace () const
Return face.
label owner () const
Return owner cell.
label neighbour () const
Return neighbour cell.
bool isPointMaster () const
Is the face mastered by a point.
bool isEdgeMaster () const
Is the face mastered by an edge.
bool isFaceMaster () const
Is the face mastered by another face.
bool appended () const
Is the face appended with no master.
label masterPointID () const
Return master point ID.
label masterEdgeID () const
Return master edge ID.
label masterFaceID () const
Return master face ID.
bool flipFaceFlux () const
Does the face flux need to be flipped.
bool isInPatch () const
Does the face belong to a boundary patch?
label patchID () const
Boundary patch ID.
bool isInZone () const
Does the face belong to a zone?
bool onlyInZone () const
Is the face only a zone face (i.e. not belonging to a cell)
label zoneID () const
Face zone ID.
label zoneFlip () const
Face zone flip.
Public Member Functions inherited from topoAction
TypeName ("topoAction")
Runtime type information.
topoAction ()
Construct null.
virtual ~topoAction ()=default
Destructor.
Detailed Description
A face addition data class. A face can be inflated either from a point or from another face and can either be in internal or a boundary face.
Definition at line 47 of file polyAddFace.H.
Constructor & Destructor Documentation
polyAddFace () inline
Construct null. Used for constructing lists.
Definition at line 119 of file polyAddFace.H.
polyAddFace (const face & f, const label owner, const label neighbour, const label masterPointID, const label masterEdgeID, const label masterFaceID, const bool flipFaceFlux, const label patchID, const label zoneID, const bool zoneFlip) inline
Construct from components.
Definition at line 138 of file polyAddFace.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::min(), and UList< T >::size().
Member Function Documentation
TypeName ("addFace")
Runtime type information.
virtual autoPtr<topoAction> clone () const inline virtual
Construct and return a clone.
Implements topoAction.
Definition at line 251 of file polyAddFace.H.
const face& newFace () const inline
Return face.
Definition at line 264 of file polyAddFace.H.
label owner () const inline
Return owner cell.
Definition at line 272 of file polyAddFace.H.
label neighbour () const inline
Return neighbour cell.
Definition at line 280 of file polyAddFace.H.
bool isPointMaster () const inline
Is the face mastered by a point.
Definition at line 288 of file polyAddFace.H.
bool isEdgeMaster () const inline
Is the face mastered by an edge.
Definition at line 296 of file polyAddFace.H.
bool isFaceMaster () const inline
Is the face mastered by another face.
Definition at line 304 of file polyAddFace.H.
bool appended () const inline
Is the face appended with no master.
Definition at line 312 of file polyAddFace.H.
label masterPointID () const inline
Return master point ID.
Definition at line 320 of file polyAddFace.H.
label masterEdgeID () const inline
Return master edge ID.
Definition at line 328 of file polyAddFace.H.
label masterFaceID () const inline
Return master face ID.
Definition at line 336 of file polyAddFace.H.
bool flipFaceFlux () const inline
Does the face flux need to be flipped.
Definition at line 344 of file polyAddFace.H.
bool isInPatch () const inline
Does the face belong to a boundary patch?
Definition at line 352 of file polyAddFace.H.
label patchID () const inline
Boundary patch ID.
Definition at line 360 of file polyAddFace.H.
bool isInZone () const inline
Does the face belong to a zone?
Definition at line 368 of file polyAddFace.H.
bool onlyInZone () const inline
Is the face only a zone face (i.e. not belonging to a cell)
Definition at line 376 of file polyAddFace.H.
label zoneID () const inline
Face zone ID.
Definition at line 384 of file polyAddFace.H.
label zoneFlip () const inline
Face zone flip.
Definition at line 392 of file polyAddFace.H.
The documentation for this class was generated from the following file:
src/dynamicMesh/polyTopoChange/polyTopoChange/addObject/polyAddFace.H