OpenFOAM: line< Point, PointRef > Class Template Reference
line< Point, PointRef > Class Template Reference
A line primitive.
Public Member Functions
line (const Point &start, const Point &end)
Construct from two points.
line (const UList< Point > &points, const FixedList< label, 2 > &indices)
Construct from two points in the list of points.
line (Istream &is)
Construct from Istream.
PointRef first () const
Return first point.
PointRef second () const
Return second (last) point.
PointRef last () const
Return last (second) point.
PointRef start () const
Return first point.
PointRef end () const
Return second (last) point.
Point centre () const
Return centre (centroid)
scalar mag () const
Return scalar magnitude.
Point vec () const
Return start-to-end vector.
Point unitVec () const
Return the unit vector (start-to-end)
PointHit< Point > nearestDist (const Point &p) const
Return nearest distance to line from a given point.
scalar nearestDist (const line< Point, const Point & > &edge, Point &thisPoint, Point &edgePoint) const
Return nearest distance from line to line. Returns distance.
template<>
scalar nearestDist (const line< point2D, const point2D & > &e, point2D &thisPt, point2D &edgePt) const
template<>
scalar nearestDist (const line< point2D, const point2D & > &edge, point2D &thisPoint, point2D &edgePoint) const
Friends
Istream & operator>> (Istream &is, line &l)
Ostream & operator (Ostream &os, const line &l)
Detailed Description
template<class Point, class PointRef>
class Foam::line< Point, PointRef >
A line primitive.
Source files
line.H
lineI.H
Definition at line 55 of file line.H.
Constructor & Destructor Documentation
line (const Point & start, const Point & end) inline
Construct from two points.
Definition at line 28 of file lineI.H.
line (const UList< Point > & points, const FixedList< label, 2 > & indices) inline
Construct from two points in the list of points.
The indices could be from edge etc.
Definition at line 37 of file lineI.H.
line (Istream & is) inline explicit
Construct from Istream.
Definition at line 48 of file lineI.H.
Member Function Documentation
PointRef first () const inline
Return first point.
Definition at line 57 of file lineI.H.
PointRef second () const inline
Return second (last) point.
Definition at line 64 of file lineI.H.
PointRef last () const inline
Return last (second) point.
Definition at line 71 of file lineI.H.
References b_().
PointRef start () const inline
Return first point.
Definition at line 78 of file lineI.H.
References b_().
Referenced by line< Point, PointRef >::nearestDist().
PointRef end () const inline
Return second (last) point.
Definition at line 84 of file lineI.H.
Referenced by line< Point, PointRef >::nearestDist().
Point centre () const inline
Return centre (centroid)
Definition at line 91 of file lineI.H.
Referenced by surfaceFeatures::nearestSurfEdge().
Foam::scalar mag () const inline
Return scalar magnitude.
Definition at line 98 of file lineI.H.
References b_().
Point vec () const inline
Return start-to-end vector.
Definition at line 105 of file lineI.H.
References Foam::mag().
Point unitVec () const inline
Return the unit vector (start-to-end)
Definition at line 112 of file lineI.H.
References b_().
Foam::PointHit< Point > nearestDist (const Point & p) const
Return nearest distance to line from a given point.
If the nearest point is on the line, return a hit
Definition at line 123 of file lineI.H.
Referenced by line< Point, PointRef >::nearestDist(), and surfaceFeatures::nearestSamples().
Foam::scalar nearestDist (const line< Point, const Point & > & edge, Point & thisPoint, Point & edgePoint) const
Return nearest distance from line to line. Returns distance.
and sets both points (one on *this, one on the provided linePointRef.
Definition at line 155 of file lineI.H.
scalar nearestDist (const line< point2D, const point2D & > & e, point2D & thisPt, point2D & edgePt) const
Definition at line 32 of file line.C.
References d, Foam::constant::electromagnetic::e, end(), line< Point, PointRef >::end(), Foam::mag(), Foam::max(), Foam::min(), line< Point, PointRef >::nearestDist(), Vector2D< Cmpt >::perp(), s, line< Point, PointRef >::start(), and Foam::start.
scalar nearestDist (const line< point2D, const point2D & > & edge, point2D & thisPoint, point2D & edgePoint) const
Friends And Related Function Documentation
Istream& operator>> (Istream & is, line< Point, PointRef > & l) friend
Ostream& operator (Ostream & os, const line< Point, PointRef > & l) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/line/line.H
src/OpenFOAM/meshes/primitiveShapes/line/lineI.H