OpenFOAM: PointIndexHit< Point > Class Template Reference
PointIndexHit< Point > Class Template Reference
This class describes the interaction of (usually) a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
Public Member Functions
PointIndexHit (const bool success, const Point &p, const label index)
Construct from components.
PointIndexHit (const Point &p)
Construct from point. Hit and distance set later.
PointIndexHit ()
Construct null.
PointIndexHit (Istream &is)
Construct from Istream.
bool hit () const
Is there a hit.
label index () const
Return index.
const Point & hitPoint () const
Return hit point.
const Point & missPoint () const
Return miss point.
const Point & rawPoint () const
Return point with no checking.
Point & rawPoint ()
void setHit ()
void setMiss ()
void setPoint (const Point &p)
void setIndex (const label index)
bool operator== (const PointIndexHit &rhs) const
bool operator!= (const PointIndexHit &rhs) const
void write (Ostream &os)
Friends
Ostream & operator<< (Ostream &os, const PointIndexHit &pHit)
Istream & operator>> (Istream &is, PointIndexHit &pHit)
Detailed Description
template<class Point>
class Foam::PointIndexHit< Point >
This class describes the interaction of (usually) a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
like pointHit but carries face (or cell, edge etc.) index
Source files
PointIndexHit.H
Definition at line 51 of file PointIndexHit.H.
Constructor & Destructor Documentation
PointIndexHit (const bool success, const Point & p, const label index) inline
Construct from components.
Definition at line 78 of file PointIndexHit.H.
PointIndexHit (const Point & p) inline
Construct from point. Hit and distance set later.
Definition at line 88 of file PointIndexHit.H.
PointIndexHit () inline
Construct null.
Definition at line 98 of file PointIndexHit.H.
PointIndexHit (Istream & is) inline
Construct from Istream.
Definition at line 108 of file PointIndexHit.H.
Member Function Documentation
bool hit () const inline
Is there a hit.
Definition at line 119 of file PointIndexHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by Foam::calcProximityOfFeaturePoints(), indexedOctree< Type >::findLine(), distributedTriSurfaceMesh::findNearest(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestPoint(), boundaryMesh::getNearest(), meshSearch::intersection(), meshSearch::intersections(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), PointIndexHit< Point >::setHit(), and PointIndexHit< Point >::setIndex().
label index () const inline
Return index.
Definition at line 127 of file PointIndexHit.H.
Referenced by distributedTriSurfaceMesh::findNearest(), meshSearch::findNearestBoundaryFace(), refinementFeatures::findNearestPoint(), boundaryMesh::getNearest(), treeDataPrimitivePatch< PatchType >::getVolumeType(), meshSearch::intersection(), meshSearch::intersections(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), surfaceLocation::normal(), PointIndexHit< Point >::operator==(), PointIndexHit< Point >::rawPoint(), and PointIndexHit< Point >::setIndex().
const Point& hitPoint () const inline
Return hit point.
Definition at line 135 of file PointIndexHit.H.
References Foam::abort(), Foam::FatalError, and FatalErrorInFunction.
Referenced by Foam::calcProximityOfFeaturePoints(), distributedTriSurfaceMesh::findNearest(), refinementFeatures::findNearestPoint(), boundaryMesh::getNearest(), surfaceFeatures::nearestSurfEdge(), and PointIndexHit< Point >::setIndex().
const Point& missPoint () const inline
Return miss point.
Definition at line 150 of file PointIndexHit.H.
Referenced by PointIndexHit< Point >::operator==().
const Point& rawPoint () const inline
Return point with no checking.
Definition at line 165 of file PointIndexHit.H.
References p.
Referenced by indexedOctree< Type >::findLine(), and surfaceFeatures::nearestSurfEdge().
Point& rawPoint () inline
Definition at line 170 of file PointIndexHit.H.
References PointIndexHit< Point >::index().
void setHit () inline
Definition at line 175 of file PointIndexHit.H.
References PointIndexHit< Point >::hit().
Referenced by triSurfaceTools::classify().
void setMiss () inline
Definition at line 180 of file PointIndexHit.H.
Referenced by triSurfaceTools::classify().
void setPoint (const Point & p) inline
Definition at line 185 of file PointIndexHit.H.
References PointIndexHit< Point >::operator==().
Referenced by triSurfaceTools::classify().
void setIndex (const label index) inline
Definition at line 190 of file PointIndexHit.H.
References PointIndexHit< Point >::hit(), PointIndexHit< Point >::hitPoint(), and PointIndexHit< Point >::index().
Referenced by triSurfaceTools::classify(), meshSearch::intersection(), and meshSearch::intersections().
bool operator== (const PointIndexHit< Point > & rhs) const inline
Definition at line 195 of file PointIndexHit.H.
References PointIndexHit< Point >::index(), and PointIndexHit< Point >::missPoint().
Referenced by PointIndexHit< Point >::setPoint().
bool operator!= (const PointIndexHit< Point > & rhs) const inline
Definition at line 203 of file PointIndexHit.H.
References token::SPACE.
void write (Ostream & os) inline
Definition at line 208 of file PointIndexHit.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const PointIndexHit< Point > & pHit) friend
Definition at line 220 of file PointIndexHit.H.
Istream& operator>> (Istream & is, PointIndexHit< Point > & pHit) friend
Definition at line 241 of file PointIndexHit.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/PointIndexHit.H