OpenFOAM: edgeInterpolation Class Reference
edgeInterpolation Class Reference
Face to edge interpolation scheme. Included in faMesh.
Public Member Functions
ClassName ("edgeInterpolation")
edgeInterpolation (const faMesh &)
Construct given an faMesh.
~edgeInterpolation ()
Destructor.
const faMesh & mesh () const
Return mesh reference.
const edgeScalarField & lPN () const
Return reference to PN geodesic distance.
const edgeScalarField & weights () const
Return reference to weighting factors array.
const edgeScalarField & deltaCoeffs () const
Return reference to difference factors array.
bool orthogonal () const
Return whether mesh is orthogonal or not.
const edgeVectorField & correctionVectors () const
Return reference to non-orthogonality correction vectors array.
bool skew () const
Return whether mesh is skew or not.
const edgeVectorField & skewCorrectionVectors () const
Return reference to skew vectors array.
bool movePoints () const
Do what is necessary if the mesh has moved.
Protected Member Functions
void clearOut ()
Clear all geometry and addressing.
Detailed Description
Face to edge interpolation scheme. Included in faMesh.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
edgeInterpolation.H
edgeInterpolation.C
Definition at line 56 of file edgeInterpolation.H.
Constructor & Destructor Documentation
edgeInterpolation (const faMesh & fam) explicit
Construct given an faMesh.
Definition at line 50 of file edgeInterpolation.C.
~edgeInterpolation ()
Destructor.
Definition at line 67 of file edgeInterpolation.C.
Member Function Documentation
void clearOut () protected
Clear all geometry and addressing.
Definition at line 36 of file edgeInterpolation.C.
References Foam::defineTypeNameAndDebug().
ClassName ("edgeInterpolation")
const faMesh& mesh () const inline
Return mesh reference.
Definition at line 170 of file edgeInterpolation.H.
const Foam::edgeScalarField & lPN () const
Return reference to PN geodesic distance.
Definition at line 75 of file edgeInterpolation.C.
const Foam::edgeScalarField & weights () const
Return reference to weighting factors array.
Definition at line 86 of file edgeInterpolation.C.
const Foam::edgeScalarField & deltaCoeffs () const
Return reference to difference factors array.
Definition at line 97 of file edgeInterpolation.C.
Referenced by correctedLnGrad< Type >::correction().
bool orthogonal () const
Return whether mesh is orthogonal or not.
Definition at line 108 of file edgeInterpolation.C.
Referenced by correctedLnGrad< Type >::deltaCoeffs(), and limitedLnGrad< Type >::deltaCoeffs().
const Foam::edgeVectorField & correctionVectors () const
Return reference to non-orthogonality correction vectors array.
Definition at line 119 of file edgeInterpolation.C.
Referenced by correctedLnGrad< Type >::correction().
bool skew () const
Return whether mesh is skew or not.
Definition at line 132 of file edgeInterpolation.C.
const Foam::edgeVectorField & skewCorrectionVectors () const
Return reference to skew vectors array.
Definition at line 144 of file edgeInterpolation.C.
bool movePoints () const
Do what is necessary if the mesh has moved.
Definition at line 181 of file edgeInterpolation.C.
References Foam::deleteDemandDrivenData().
The documentation for this class was generated from the following files:
src/finiteArea/interpolation/edgeInterpolation/edgeInterpolation.H
src/finiteArea/interpolation/edgeInterpolation/edgeInterpolation.C