OpenFOAM: objectHit Class Reference
objectHit Class Reference
This class describes a combination of target object index and success flag.
Public Member Functions
objectHit ()
Construct null.
objectHit (const bool success, const label obj)
Construct from components.
objectHit (Istream &is)
Construct from Istream.
bool hit () const
Is there a hit.
label hitObject () const
Return hit object.
void setHit ()
void setMiss ()
Friends
Ostream & operator<< (Ostream &os, const objectHit &obj)
Detailed Description
This class describes a combination of target object index and success flag.
Definition at line 43 of file objectHit.H.
Constructor & Destructor Documentation
objectHit () inline
Construct null.
Definition at line 65 of file objectHit.H.
objectHit (const bool success, const label obj) inline
Construct from components.
Definition at line 74 of file objectHit.H.
objectHit (Istream & is) inline
Construct from Istream.
Definition at line 83 of file objectHit.H.
Member Function Documentation
bool hit () const inline
Is there a hit.
Definition at line 97 of file objectHit.H.
Referenced by objectHit::setMiss().
label hitObject () const inline
Return hit object.
Definition at line 105 of file objectHit.H.
Referenced by objectHit::setMiss().
void setHit () inline
Definition at line 113 of file objectHit.H.
void setMiss () inline
Definition at line 118 of file objectHit.H.
References objectHit::hit(), objectHit::hitObject(), and token::SPACE.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const objectHit & obj) friend
Definition at line 126 of file objectHit.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/objectHit.H