OpenFOAM: coupledPolyPatch Class Reference
coupledPolyPatch Class Reference abstract
The coupledPolyPatch is an abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
Public Types
enum transformType {
UNKNOWN, ROTATIONAL, TRANSLATIONAL, COINCIDENTFULLMATCH,
NOORDERING
}
Public Types inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
enum surfaceTopo { MANIFOLD, OPEN, ILLEGAL }
Enumeration defining the surface type. Used in check routines.
typedef Face FaceType
typedef FaceList< Face > FaceListType
typedef PointField PointFieldType
Public Member Functions
TypeName ("coupled")
Runtime type information.
coupledPolyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType, const transformType transform)
Construct from components.
coupledPolyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
coupledPolyPatch (const coupledPolyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
coupledPolyPatch (const coupledPolyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
virtual ~coupledPolyPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
virtual bool owner () const =0
Does this side own the patch ?
virtual bool neighbour () const
Does the coupled side own the patch ?
virtual transformType transform () const
Type of transform.
virtual transformType & transform ()
Type of transform.
virtual void transformPosition (pointField &) const =0
Transform a patch-based position from other side to this side.
virtual void transformPosition (point &, const label facei) const =0
Transform a patch-based position from other side to this side.
virtual bool separated () const
Are the planes separated.
virtual const vectorField & separation () const
If the planes are separated the separation vector.
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
virtual const boolList & collocated () const
Are faces collocated. Either size 0,1 or length of patch.
scalar matchTolerance () const
virtual void calcGeometry (const primitivePatch &referPatch, const pointField &thisCtrs, const vectorField &thisAreas, const pointField &thisCc, const pointField &nbrCtrs, const vectorField &nbrAreas, const pointField &nbrCc)=0
Calculate the patch geometry.
virtual void initOrder (PstreamBuffers &, const primitivePatch &) const =0
Initialize ordering for primitivePatch. Does not.
virtual bool order (PstreamBuffers &, const primitivePatch &, labelList &faceMap, labelList &rotation) const =0
Return new ordering for primitivePatch.
virtual void write (Ostream &) const
Write the polyPatch data as a dictionary.
Public Member Functions inherited from polyPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, polyPatch, word,(const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, size, start, index, bm, patchType))
declareRunTimeSelectionTable (autoPtr, polyPatch, dictionary,(const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType),(name, dict, index, bm, patchType))
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from components.
polyPatch (const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm, const word &physicalType, const wordList &inGroups)
Construct from components.
polyPatch (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm, const word &patchType)
Construct from dictionary.
polyPatch (const polyPatch &, const polyBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
polyPatch (const polyPatch &pp, const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart)
Construct given the original patch and a map.
polyPatch (const polyPatch &)
Construct as copy.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm) const
Construct and return a clone, resetting the boundary mesh.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const label newSize, const label newStart) const
Construct and return a clone, resetting the face list.
virtual autoPtr< polyPatch > clone (const polyBoundaryMesh &bm, const label index, const labelUList &mapAddressing, const label newStart) const
Construct and return a clone, resetting the face list.
virtual ~polyPatch ()
Destructor.
label offset () const
The offset where this patch starts in the boundary face list.
label start () const
Return start label of this patch in the polyMesh face list.
labelRange range () const
Return start/size range of this patch.
const polyBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const UIndirectList< T > patchInternalList (const UList< T > &internalValues) const
Extract face cell data.
template<class T >
const List< T >::subList patchSlice (const UList< T > &l) const
Slice list to patch.
template<class T >
const Field< T >::subField patchSlice (const Field< T > &l) const
Slice Field to patch.
const vectorField::subField faceCentres () const
Return face centres.
const vectorField::subField faceAreas () const
Return face normals.
tmp< vectorField > faceCellCentres () const
Return face cell centres.
tmp< scalarField > areaFraction () const
Return the area fraction as the ratio of the stored face area and the area given by the face points.
const labelUList & faceCells () const
Return face-cell addressing.
const labelList & meshEdges () const
Return global edge index for local edges.
virtual void clearAddressing ()
Clear addressing.
label whichFace (const label l) const
Return label of face in patch from global face label.
void operator= (const polyPatch &)
Assignment.
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &p, const label index)
Copy construct, resetting the index.
virtual ~patchIdentifier ()=default
Destructor.
const word & name () const
Return the patch name.
word & name ()
Modifiable patch name.
const word & physicalType () const
The optional physical type of the patch.
word & physicalType ()
Modifiable optional physical type of the patch.
label index () const
The index of this patch in the boundaryMesh.
label & index ()
Modifiable the index of this patch in the boundaryMesh.
const wordList & inGroups () const
The optional groups that the patch belongs to.
wordList & inGroups ()
Modifiable optional groups that the patch belongs to.
bool inGroup (const word &name) const
Check if the patch is in named group.
void write (Ostream &os) const
Write patchIdentifier as a dictionary.
Public Member Functions inherited from PrimitivePatch< Face, FaceList, PointField, PointType >
PrimitivePatch (const FaceList< Face > &faces, const Field< PointType > &points)
Construct from components.
PrimitivePatch (FaceList< Face > &&faces, const Field< PointType > &points)
Construct from components, transferring faces.
PrimitivePatch (FaceList< Face > &faces, Field< PointType > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< PointType > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< Face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< PointType > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< PointType > & faceCentres () const
Return face centres for patch.
const Field< PointType > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< PointType > & faceNormals () const
Return face unit normals for patch.
const Field< PointType > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
template<class ToPatch >
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
template<class ToPatch >
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< PointType > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< Face, FaceList, PointField, PointType > &)
Assignment.
template<class ToPatch >
Foam::List< Foam::objectHit > projectPoints (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
template<class ToPatch >
Foam::List< Foam::objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< PointType > &projectionDirection, const intersection::algorithm alg, const intersection::direction dir) const
Static Public Member Functions
static scalarField calcFaceTol (const UList< face > &faces, const pointField &points, const pointField &faceCentres)
Calculate typical tolerance per face. Is currently max distance.
Static Public Member Functions inherited from polyPatch
static autoPtr< polyPatch > New (const word &patchType, const word &name, const label size, const label start, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static autoPtr< polyPatch > New (const word &patchType, const word &name, const dictionary &dict, const label index, const polyBoundaryMesh &bm)
Return a pointer to a new patch created on freestore from.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Static Public Attributes
static const Enum< transformType > transformTypeNames
Static Public Attributes inherited from polyPatch
static int disallowGenericPolyPatch
Debug switch to disallow the use of genericPolyPatch.
Protected Member Functions
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr, const scalarField &smallDist, const scalar absTol, const transformType=UNKNOWN) const
Calculate the transformation tensors.
virtual void initGeometry (PstreamBuffers &)=0
Initialise the calculation of the patch geometry.
virtual void calcGeometry (PstreamBuffers &)=0
Calculate the patch geometry.
virtual void initMovePoints (PstreamBuffers &, const pointField &)=0
Initialise the patches for moving points.
virtual void movePoints (PstreamBuffers &, const pointField &)=0
Correct patches after moving points.
virtual void initUpdateMesh (PstreamBuffers &)=0
Initialise the update of the patch topology.
virtual void updateMesh (PstreamBuffers &)=0
Update of the patch topology.
Protected Member Functions inherited from polyPatch
virtual void clearGeom ()
Clear geometry.
Static Protected Member Functions
static void writeOBJ (Ostream &os, const point &pt)
Write point in OBJ format.
static void writeOBJ (Ostream &, const pointField &, const labelList &)
Write selected points in OBJ format.
static void writeOBJ (const fileName &, const UList< face > &, const pointField &)
Write patch.
static void writeOBJ (Ostream &os, const point &p0, const point &p1, label &vertI)
Write edge in OBJ format.
static pointField getAnchorPoints (const UList< face > &, const pointField &, const transformType)
Get a unique anchor point for all faces.
static label getRotation (const pointField &points, const face &f, const point &anchor, const scalar tol)
Get the number of vertices face f needs to be rotated such that.
Detailed Description
The coupledPolyPatch is an abstract base class for patches that couple regions of the computational domain e.g. cyclic and processor-processor links.
Source files
coupledPolyPatch.H
coupledPolyPatch.C
Definition at line 49 of file coupledPolyPatch.H.
Member Enumeration Documentation
enum transformType
Enumerator
UNKNOWN
ROTATIONAL
TRANSLATIONAL
COINCIDENTFULLMATCH
NOORDERING
Definition at line 55 of file coupledPolyPatch.H.
Constructor & Destructor Documentation
coupledPolyPatch (const word & name, const label size, const label start, const label index, const polyBoundaryMesh & bm, const word & patchType, const transformType transform)
Construct from components.
Definition at line 470 of file coupledPolyPatch.C.
coupledPolyPatch (const word & name, const dictionary & dict, const label index, const polyBoundaryMesh & bm, const word & patchType)
Construct from dictionary.
Definition at line 487 of file coupledPolyPatch.C.
coupledPolyPatch (const coupledPolyPatch & pp, const polyBoundaryMesh & bm)
Construct as copy, resetting the boundary mesh.
Definition at line 510 of file coupledPolyPatch.C.
coupledPolyPatch (const coupledPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const label newSize, const label newStart)
Construct given the original patch and resetting the.
face list and boundary mesh information
Definition at line 522 of file coupledPolyPatch.C.
coupledPolyPatch (const coupledPolyPatch & pp, const polyBoundaryMesh & bm, const label index, const labelUList & mapAddressing, const label newStart)
Construct given the original patch and a map.
Definition at line 537 of file coupledPolyPatch.C.
~coupledPolyPatch () virtual
Destructor.
Definition at line 553 of file coupledPolyPatch.C.
Member Function Documentation
void calcTransformTensors (const vectorField & Cf, const vectorField & Cr, const vectorField & nf, const vectorField & nr, const scalarField & smallDist, const scalar absTol, const transformType transform = UNKNOWN) const protected
Calculate the transformation tensors.
smallDist : matching distance per face absTol : absolute error in normal if transformType = unknown it first tries rotational, then translational transform
Definition at line 289 of file coupledPolyPatch.C.
virtual void initGeometry (PstreamBuffers &) protected pure virtual
Initialise the calculation of the patch geometry.
Reimplemented from polyPatch.
Implemented in oldCyclicPolyPatch, cyclicAMIPolyPatch, cyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
virtual void calcGeometry (PstreamBuffers &) protected pure virtual
Calculate the patch geometry.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
virtual void initMovePoints (PstreamBuffers & , const pointField &) protected pure virtual
Initialise the patches for moving points.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
virtual void movePoints (PstreamBuffers & , const pointField &) protected pure virtual
Correct patches after moving points.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
virtual void initUpdateMesh (PstreamBuffers &) protected pure virtual
Initialise the update of the patch topology.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
virtual void updateMesh (PstreamBuffers &) protected pure virtual
Update of the patch topology.
Reimplemented from polyPatch.
Implemented in cyclicPolyPatch, oldCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and processorCyclicPolyPatch.
void writeOBJ (Ostream & os, const point & pt) static protected
Write point in OBJ format.
Definition at line 52 of file coupledPolyPatch.C.
void writeOBJ (Ostream & os, const pointField & points, const labelList & pointLabels) static protected
Write selected points in OBJ format.
Definition at line 59 of file coupledPolyPatch.C.
References Foam::endl(), Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
void writeOBJ (const fileName & fName, const UList< face > & faces, const pointField & points) static protected
Write patch.
Definition at line 91 of file coupledPolyPatch.C.
void writeOBJ (Ostream & os, const point & p0, const point & p1, label & vertI) static protected
Write edge in OBJ format.
Definition at line 73 of file coupledPolyPatch.C.
References i, and Foam::meshTools::writeOBJ().
Foam::pointField getAnchorPoints (const UList< face > & faces, const pointField & points, const transformType transform) static protected
Get a unique anchor point for all faces.
Definition at line 127 of file coupledPolyPatch.C.
Foam::label getRotation (const pointField & points, const face & f, const point & anchor, const scalar tol) static protected
Get the number of vertices face f needs to be rotated such that.
its f[0] point aligns with given anchor (within tol).
Definition at line 235 of file coupledPolyPatch.C.
TypeName ("coupled")
Runtime type information.
virtual bool coupled () const inline virtual
Return true because this patch is coupled.
Reimplemented from polyPatch.
Reimplemented in cyclicAMIPolyPatch, and processorPolyPatch.
Definition at line 298 of file coupledPolyPatch.H.
virtual bool owner () const pure virtual
Does this side own the patch ?
Implemented in cyclicPolyPatch, processorCyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, and oldCyclicPolyPatch.
virtual bool neighbour () const inline virtual
Does the coupled side own the patch ?
Reimplemented in cyclicPolyPatch, and processorPolyPatch.
Definition at line 311 of file coupledPolyPatch.H.
virtual transformType transform () const inline virtual
Type of transform.
Reimplemented in processorCyclicPolyPatch.
Definition at line 319 of file coupledPolyPatch.H.
virtual transformType& transform () inline virtual
Type of transform.
This is currently only for use when collapsing generated meshes that can have zero area faces.
Reimplemented in processorCyclicPolyPatch.
Definition at line 330 of file coupledPolyPatch.H.
virtual void transformPosition (pointField &) const pure virtual
Transform a patch-based position from other side to this side.
Implemented in cyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and oldCyclicPolyPatch.
Referenced by mapDistribute::transformPosition::operator()().
virtual void transformPosition (point & , const label facei) const pure virtual
Transform a patch-based position from other side to this side.
Implemented in cyclicPolyPatch, cyclicAMIPolyPatch, processorPolyPatch, processorCyclicPolyPatch, and oldCyclicPolyPatch.
virtual bool separated () const inline virtual
Are the planes separated.
Reimplemented in processorCyclicPolyPatch.
Definition at line 348 of file coupledPolyPatch.H.
Referenced by extendedCellToCellStencil::extendedCellToCellStencil(), and extendedFaceToCellStencil::extendedFaceToCellStencil().
virtual const vectorField& separation () const inline virtual
If the planes are separated the separation vector.
Reimplemented in processorCyclicPolyPatch.
Definition at line 356 of file coupledPolyPatch.H.
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Reimplemented in processorCyclicPolyPatch.
Definition at line 364 of file coupledPolyPatch.H.
Referenced by cyclicAMIPointPatch::constraintType(), cyclicPointPatch::constraintType(), extendedCellToCellStencil::extendedCellToCellStencil(), extendedFaceToCellStencil::extendedFaceToCellStencil(), cyclicFvPatch::neighbPatch(), mapDistribute::transform::operator()(), and processorCyclicPolyPatch::referPatch().
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Reimplemented in processorCyclicPolyPatch.
Definition at line 372 of file coupledPolyPatch.H.
Referenced by cyclicACMIFvPatch::AMI(), cyclicAMIFvPatch::applyLowWeightCorrection(), cyclicACMIPointPatch::constraintType(), mapDistribute::transform::operator()(), and processorFvPatch::procPolyPatch().
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Reimplemented in processorCyclicPolyPatch.
Definition at line 380 of file coupledPolyPatch.H.
Referenced by cyclicACMIPointPatch::cyclicACMIPatch(), processorCyclicPolyPatch::owner(), processorFvPatch::parallel(), and cyclicAMIFvPatch::parallel().
virtual const boolList& collocated () const inline virtual
Are faces collocated. Either size 0,1 or length of patch.
Reimplemented in processorCyclicPolyPatch.
Definition at line 388 of file coupledPolyPatch.H.
scalar matchTolerance () const inline
Definition at line 393 of file coupledPolyPatch.H.
virtual void calcGeometry (const primitivePatch & referPatch, const pointField & thisCtrs, const vectorField & thisAreas, const pointField & thisCc, const pointField & nbrCtrs, const vectorField & nbrAreas, const pointField & nbrCc) pure virtual
Calculate the patch geometry.
Implemented in cyclicAMIPolyPatch, oldCyclicPolyPatch, cyclicPolyPatch, processorPolyPatch, and processorCyclicPolyPatch.
virtual void initOrder (PstreamBuffers & , const primitivePatch &) const pure virtual
Initialize ordering for primitivePatch. Does not.
refer to *this (except for name() and type() etc.)
Reimplemented from polyPatch.
Implemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
virtual bool order (PstreamBuffers & , const primitivePatch & , labelList & faceMap, labelList & rotation) const pure virtual
Return new ordering for primitivePatch.
Ordering is -faceMap: for every face index of the new face -rotation:for every new face the clockwise shift of the original face. Return false if nothing changes (faceMap is identity, rotation is 0), true otherwise.
Reimplemented from polyPatch.
Implemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, and oldCyclicPolyPatch.
Foam::scalarField calcFaceTol (const UList< face > & faces, const pointField & points, const pointField & faceCentres) static
Calculate typical tolerance per face. Is currently max distance.
from face centre to any of the face vertices.
Definition at line 195 of file coupledPolyPatch.C.
void write (Ostream & os) const virtual
Write the polyPatch data as a dictionary.
Reimplemented from polyPatch.
Reimplemented in cyclicAMIPolyPatch, cyclicPolyPatch, processorCyclicPolyPatch, processorPolyPatch, cyclicACMIPolyPatch, oldCyclicPolyPatch, and cyclicPeriodicAMIPolyPatch.
Definition at line 559 of file coupledPolyPatch.C.
Member Data Documentation
const Foam::Enum< Foam::coupledPolyPatch::transformType > transformTypeNames static
Definition at line 65 of file coupledPolyPatch.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/polyPatches/basic/coupled/coupledPolyPatch.H
src/OpenFOAM/meshes/polyMesh/polyPatches/basic/coupled/coupledPolyPatch.C