OpenFOAM: specieElement Class Reference
specieElement Class Reference
Public Member Functions
specieElement ()
Construct null.
specieElement (const word &name, const label nAtoms)
Construct from components.
specieElement (Istream &)
Construct from Istream.
const word & name () const
Return the name of the element.
word & name ()
Return non-const access to the name of the element.
label nAtoms () const
Return the number of atoms of this element in the specie.
label & nAtoms ()
Return non-const access to the number of atoms of this element.
bool operator== (const specieElement &) const
Equality comparison.
bool operator!= (const specieElement &) const
Inequality comparison.
Friends
Ostream & operator<< (Ostream &, const specieElement &)
Detailed Description
Source files
specieElement.H
specieElementI.H
Definition at line 50 of file specieElement.H.
Constructor & Destructor Documentation
specieElement () inline
Construct null.
Definition at line 25 of file specieElementI.H.
specieElement (const word & name, const label nAtoms) inline
Construct from components.
Definition at line 29 of file specieElementI.H.
specieElement (Istream & is) inline
Construct from Istream.
Definition at line 36 of file specieElementI.H.
Member Function Documentation
const Foam::word & name () const inline
Return the name of the element.
Definition at line 45 of file specieElementI.H.
Referenced by DAC< CompType, ThermoType >::DAC(), and EFA< CompType, ThermoType >::EFA().
Foam::word & name () inline
Return non-const access to the name of the element.
Definition at line 51 of file specieElementI.H.
Foam::label nAtoms () const inline
Return the number of atoms of this element in the specie.
Definition at line 57 of file specieElementI.H.
Referenced by DAC< CompType, ThermoType >::DAC(), and EFA< CompType, ThermoType >::EFA().
Foam::label & nAtoms () inline
Return non-const access to the number of atoms of this element.
in the specie
Definition at line 63 of file specieElementI.H.
bool operator== (const specieElement & se) const inline
Equality comparison.
Definition at line 71 of file specieElementI.H.
bool operator!= (const specieElement & se) const inline
Inequality comparison.
Definition at line 81 of file specieElementI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const specieElement &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/specieElement/specieElement.H
src/thermophysicalModels/specie/specieElement/specieElementI.H