OpenFOAM: MultiComponentPhaseModel< BasePhaseModel > Class Template Reference
MultiComponentPhaseModel< BasePhaseModel > Class Template Reference
Class which represents a phase with multiple species. Returns the species' mass fractions, and their governing equations.
Public Member Functions
MultiComponentPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~MultiComponentPhaseModel ()
Destructor.
virtual void correctThermo ()
Correct the thermodynamics.
virtual bool pure () const
Return whether the phase is pure (i.e., not multi-component)
virtual tmp< fvScalarMatrix > YiEqn (volScalarField &Yi)
Return the species fraction equation.
virtual const PtrList
< volScalarField > & Y () const
Return the species mass fractions.
virtual const volScalarField & Y (const word &name) const
Return a species mass fraction by name.
virtual PtrList< volScalarField > & YRef ()
Access the species mass fractions.
virtual const UPtrList
< volScalarField > & YActive () const
Return the active species mass fractions.
virtual UPtrList
< volScalarField > & YActiveRef ()
Access the active species mass fractions.
MultiComponentPhaseModel (const phaseSystem &fluid, const word &phaseName)
virtual ~MultiComponentPhaseModel ()=default
Destructor.
const hashedWordList & species () const
Species table.
virtual const phaseThermo & thermo () const
Access to thermo.
virtual phaseThermo & thermo ()
Access non-const thermo.
virtual void correct ()
Correct phase thermo.
virtual void solveYi (PtrList< volScalarField::Internal > &, PtrList< volScalarField::Internal > &)
Solve species fraction equation.
virtual const PtrList
< volScalarField > & Y () const
Constant access the species mass fractions.
virtual PtrList< volScalarField > & Y ()
Access the species mass fractions.
label inertIndex () const
Return inert species index.
Protected Member Functions
void calculateMassFractions ()
Transfor volume fraction into mass fractions.
void calculateVolumeFractions ()
Transfor mass fraction into volume fractions.
Protected Attributes
dimensionedScalar Sct_
Turbulent Schmidt number.
dimensionedScalar residualAlpha_
Residual phase fraction.
label inertIndex_
Inert species index.
UPtrList< volScalarField > YActive_
Pointer list to active species.
hashedWordList species_
Species table.
autoPtr< phaseThermo > thermoPtr_
Thermophysical model.
PtrList< volScalarField > X_
Ptr list of volumetric fractions for species.
Detailed Description
template<class BasePhaseModel>
class Foam::MultiComponentPhaseModel< BasePhaseModel >
Class which represents a phase with multiple species. Returns the species' mass fractions, and their governing equations.
Source files
MultiComponentPhaseModel.H
MultiComponentPhaseModel.C
Source files
MultiComponentPhaseModel.H
MultiComponentPhaseModel.C
Definition at line 48 of file MultiComponentPhaseModel.H.
Constructor & Destructor Documentation
MultiComponentPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 37 of file MultiComponentPhaseModel.C.
References forAll, i, MultiComponentPhaseModel< BasePhaseModel >::inertIndex_, inertSpecie(), j, word::null, MultiComponentPhaseModel< BasePhaseModel >::Y(), and MultiComponentPhaseModel< BasePhaseModel >::YActive_.
~MultiComponentPhaseModel () virtual
Destructor.
Definition at line 85 of file MultiComponentPhaseModel.C.
MultiComponentPhaseModel (const phaseSystem & fluid, const word & phaseName)
virtual ~MultiComponentPhaseModel () virtual default
Destructor.
Member Function Documentation
void correctThermo () virtual
Correct the thermodynamics.
Definition at line 92 of file MultiComponentPhaseModel.C.
bool pure () const virtual
Return whether the phase is pure (i.e., not multi-component)
Definition at line 135 of file MultiComponentPhaseModel.C.
Foam::tmp< Foam::fvScalarMatrix > YiEqn (volScalarField & Yi) virtual
Return the species fraction equation.
Definition at line 143 of file MultiComponentPhaseModel.C.
const Foam::PtrList< Foam::volScalarField > & Y () const virtual
Return the species mass fractions.
Definition at line 171 of file MultiComponentPhaseModel.C.
Referenced by MultiComponentPhaseModel< BasePhaseModel >::MultiComponentPhaseModel().
const Foam::volScalarField & Y (const word & name) const virtual
Return a species mass fraction by name.
Definition at line 179 of file MultiComponentPhaseModel.C.
Foam::PtrList< Foam::volScalarField > & YRef () virtual
Access the species mass fractions.
Definition at line 187 of file MultiComponentPhaseModel.C.
const Foam::UPtrList< Foam::volScalarField > & YActive () const virtual
Return the active species mass fractions.
Definition at line 195 of file MultiComponentPhaseModel.C.
Foam::UPtrList< Foam::volScalarField > & YActiveRef () virtual
Access the active species mass fractions.
Definition at line 203 of file MultiComponentPhaseModel.C.
void calculateMassFractions () protected
Transfor volume fraction into mass fractions.
void calculateVolumeFractions () protected
Transfor mass fraction into volume fractions.
const hashedWordList& species () const inline
Species table.
Definition at line 117 of file MultiComponentPhaseModel.H.
virtual const phaseThermo& thermo () const virtual
Access to thermo.
virtual phaseThermo& thermo () virtual
Access non-const thermo.
virtual void correct () virtual
Correct phase thermo.
virtual void solveYi (PtrList< volScalarField::Internal > & , PtrList< volScalarField::Internal > &) virtual
Solve species fraction equation.
virtual const PtrList<volScalarField>& Y () const virtual
Constant access the species mass fractions.
virtual PtrList<volScalarField>& Y () virtual
Access the species mass fractions.
label inertIndex () const
Return inert species index.
Member Data Documentation
dimensionedScalar Sct_ protected
Turbulent Schmidt number.
Definition at line 59 of file MultiComponentPhaseModel.H.
dimensionedScalar residualAlpha_ protected
Residual phase fraction.
Definition at line 64 of file MultiComponentPhaseModel.H.
label inertIndex_ protected
Inert species index.
Definition at line 69 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel >::MultiComponentPhaseModel().
UPtrList<volScalarField> YActive_ protected
Pointer list to active species.
Definition at line 74 of file MultiComponentPhaseModel.H.
Referenced by MultiComponentPhaseModel< BasePhaseModel >::MultiComponentPhaseModel().
hashedWordList species_ protected
Species table.
Definition at line 62 of file MultiComponentPhaseModel.H.
autoPtr<phaseThermo> thermoPtr_ protected
Thermophysical model.
Definition at line 72 of file MultiComponentPhaseModel.H.
PtrList<volScalarField> X_ protected
Ptr list of volumetric fractions for species.
Definition at line 77 of file MultiComponentPhaseModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/phaseModel/MultiComponentPhaseModel/MultiComponentPhaseModel.H
applications/solvers/multiphase/icoReactingMultiphaseInterFoam/phasesSystem/phaseModel/MultiComponentPhaseModel/MultiComponentPhaseModel.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/phaseModel/MultiComponentPhaseModel/MultiComponentPhaseModel.C