OpenFOAM: zeroField Class Reference
zeroField Class Reference
A class representing the concept of a field of 0 used to avoid unnecessary manipulations for objects which are known to be zero at compile-time.
Public Member Functions
zeroField ()=default
Construct null.
zeroField field () const
scalar operator[] (const label) const
zeroField operator() () const
zeroField operator- () const
Public Member Functions inherited from zero
constexpr zero () noexcept
Null constructible.
constexpr zero (Istream &) noexcept
Construct from Istream consumes no content.
constexpr operator bool () const noexcept
Return false (0) for bool.
constexpr operator label () const noexcept
Return 0 for label.
constexpr operator float () const noexcept
Return 0 for float.
constexpr operator double () const noexcept
Return 0 for double.
Additional Inherited Members
Public Types inherited from zero
typedef zero value_type
Detailed Description
A class representing the concept of a field of 0 used to avoid unnecessary manipulations for objects which are known to be zero at compile-time.
Used for example as the argument to a function in which certain terms are optional, see source terms in the MULES solvers.
Definition at line 47 of file zeroField.H.
Constructor & Destructor Documentation
zeroField () default
Construct null.
Referenced by zeroField::field(), and zeroField::operator-().
Member Function Documentation
zeroField field () const inline
Definition at line 63 of file zeroField.H.
References zeroField::zeroField().
scalar operator[] (const label) const inline
Definition at line 71 of file zeroField.H.
zeroField operator() () const inline
Definition at line 76 of file zeroField.H.
zeroField operator- () const inline
Definition at line 81 of file zeroField.H.
References zeroField::zeroField().
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/zeroField/zeroField.H