OpenFOAM: HashSet< Key, Hash > Class Template Reference
HashSet< Key, Hash > Class Template Reference
A HashTable with keys but without contents that is similar to std::unordered_set.
Public Types
typedef HashSet< Key, Hash > this_type
The template instance used for this HashSet.
typedef HashTable< zero::null,
Key, Hash > parent_type
The template instance used for the parent HashTable.
using iterator = typename parent_type::key_iterator
An iterator, returning reference to the key.
using const_iterator = typename parent_type::const_key_iterator
A const_iterator, returning reference to the key.
Public Types inherited from HashTable< zero::null, Key, Hash >
typedef HashTable< zero::null,
Key, Hash > this_type
The template instance used for this HashTable.
typedef Key key_type
The second template parameter, type of keys used.
typedef zero::null mapped_type
The first template parameter, type of objects contained.
typedef zero::null value_type
Same as mapped_type for OpenFOAM HashTables.
typedef Hash hasher
The third template parameter, the hash index method.
typedef zero::null & reference
Reference to the stored value_type.
typedef const zero::null & const_reference
Const reference to the stored value_type.
typedef label difference_type
The type to represent the difference between two iterators.
typedef label size_type
The type that can represent the size of a HashTable.
using key_iterator = key_iterator_base< iterator >
Forward iterator returning the key.
using const_key_iterator = key_iterator_base< const_iterator >
Forward const iterator returning the key.
Public Member Functions
HashSet ()
Construct null with default (128) table capacity.
HashSet (const label size)
Construct given initial table capacity.
HashSet (Istream &is)
Construct from Istream with default table capacity.
template<unsigned N>
HashSet (const FixedList< Key, N > &list)
Construct from FixedList of Key.
HashSet (const UList< Key > &list)
Construct from UList of Key.
template<class Addr >
HashSet (const IndirectListBase< Key, Addr > &list)
Construct from an indirect list.
HashSet (std::initializer_list< Key > list)
Construct from an initializer list of Key.
HashSet (const this_type &hs)
Copy construct.
HashSet (this_type &&hs)
Move construct.
template<class AnyType , class AnyHash >
HashSet (const HashTable< AnyType, Key, AnyHash > &tbl)
Construct from the keys of another HashTable, the type of values held is arbitrary.
bool test (const Key &key) const
Same as found() - return true if key exists in the set.
bool insert (const Key &key)
Insert a new entry, not overwriting existing entries.
bool set (const Key &key)
Same as insert (no value to overwrite)
bool unset (const Key &key)
Unset the specified key - same as erase.
template<class InputIter >
label insert (InputIter first, InputIter last)
Insert keys from the input iterator range.
label insert (std::initializer_list< Key > list)
Insert keys from a initializer list of Key.
template<unsigned N>
label insert (const FixedList< Key, N > &list)
Insert keys from the list of Key.
label insert (const UList< Key > &list)
Insert keys from the list of Key.
template<class Addr >
label insert (const IndirectListBase< Key, Addr > &list)
Insert keys from the list of Key.
template<class InputIter >
label set (InputIter first, InputIter last)
Same as insert (no value to overwrite)
label set (std::initializer_list< Key > list)
Same as insert (no value to overwrite)
template<unsigned N>
label set (const FixedList< Key, N > &list)
Same as insert (no value to overwrite)
label set (const UList< Key > &list)
Same as insert (no value to overwrite)
template<class Addr >
label set (const IndirectListBase< Key, Addr > &list)
Same as insert (no value to overwrite)
template<class InputIter >
label setMany (InputIter first, InputIter last)
Same as insert (no value to overwrite)
template<class InputIter >
label unset (InputIter first, InputIter last)
Unset the keys listed in the input iterator range.
label unset (std::initializer_list< Key > list)
Unset the listed keys - same as erase.
template<unsigned N>
label unset (const FixedList< Key, N > &list)
Unset the listed keys - same as erase.
label unset (const UList< Key > &list)
Unset the listed keys - same as erase.
template<class Addr >
label unset (const IndirectListBase< Key, Addr > &list)
Unset the listed keys - same as erase.
iterator begin ()
const_iterator begin () const
const_iterator cbegin () const
const iterator & end ()
const const_iterator & end () const
const const_iterator & cend () const
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
bool operator() (const Key &key) const
Return true if the entry exists, same as found()
bool operator[] (const Key &key) const
Return true if the entry exists, same as found().
void operator= (const this_type &rhs)
Copy assignment.
void operator= (this_type &&rhs)
Move assignment.
bool operator== (const this_type &rhs) const
Sets are equal if all keys are equal, independent of order or underlying storage size.
bool operator!= (const this_type &rhs) const
The opposite of the equality operation.
void operator= (const UList< Key > &rhs)
Assignment from a UList of keys.
template<unsigned N>
void operator= (const FixedList< Key, N > &rhs)
Assignment from a FixedList of keys.
void operator= (std::initializer_list< Key > rhs)
Assignment from an initializer list of keys.
this_type & operator|= (const this_type &rhs)
Add entries to this HashSet.
this_type & operator&= (const this_type &rhs)
Only retain entries found in both HashSets.
this_type & operator^= (const this_type &rhs)
Only retain unique entries (xor)
this_type & operator+= (const this_type &rhs)
Add entries to this HashSet.
this_type & operator-= (const this_type &rhs)
Remove entries from this HashSet.
template<class UnaryPredicate >
List< Key > tocValues (const UnaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class BinaryPredicate >
List< Key > tocEntries (const BinaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class UnaryPredicate >
label countValues (const UnaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class BinaryPredicate >
label countEntries (const BinaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class UnaryPredicate >
label filterValues (const UnaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class BinaryPredicate >
label filterEntries (const BinaryPredicate &, const bool)=delete
Not applicable for HashSet.
template<class InputIter >
Foam::label assignMany (const label nItems, InputIter first, InputIter last)
template<class InputIter>
Foam::label insert (InputIter first, InputIter last)
template<unsigned N>
Foam::label insert (const FixedList< Key, N > &list)
template<class Addr>
Foam::label insert (const IndirectListBase< Key, Addr > &list)
template<class InputIter>
Foam::label unset (InputIter first, InputIter last)
template<unsigned N>
Foam::label unset (const FixedList< Key, N > &list)
template<class Addr>
Foam::label unset (const IndirectListBase< Key, Addr > &list)
Public Member Functions inherited from HashTable< zero::null, Key, Hash >
HashTable ()
Construct null with default (128) table capacity.
HashTable (const label size)
Construct given initial table capacity.
HashTable (Istream &is, const label size=128)
Construct from Istream with default table capacity.
HashTable (const this_type &ht)
Copy construct.
HashTable (this_type &&rhs)
Move construct.
HashTable (std::initializer_list< std::pair< Key, zero::null >> list)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const noexcept
The size of the underlying table.
label size () const noexcept
The number of elements in table.
bool empty () const noexcept
True if the hash table is empty.
zero::null & at (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const zero::null & at (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
bool found (const Key &key) const
Return true if hashed entry is found in table.
iterator find (const Key &key)
Find and return an iterator set at the hashed entry.
const_iterator find (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const_iterator cfind (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const zero::null & lookup (const Key &key, const zero::null &deflt) const
Return hashed entry if it exists, or return the given default.
List< Key > toc () const
The table of contents (the keys) in unsorted order.
List< Key > sortedToc () const
The table of contents (the keys) in sorted order.
List< Key > sortedToc (const Compare &comp) const
The table of contents (the keys) sorted according to the specified comparator.
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the keys.
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the values.
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the binary predicate applied to the keys and values.
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Count the number of keys that satisfy the unary predicate.
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Count the number of values that satisfy the unary predicate.
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Count the number of entries that satisfy the binary predicate.
bool emplace (const Key &key, Args &&...args)
Emplace insert a new entry, not overwriting existing entries.
bool insert (const Key &key, const zero::null &obj)
Copy insert a new entry, not overwriting existing entries.
bool insert (const Key &key, zero::null &&obj)
Move insert a new entry, not overwriting existing entries.
bool set (const Key &key, const zero::null &obj)
Copy assign a new entry, overwriting existing entries.
bool set (const Key &key, zero::null &&obj)
Move assign a new entry, overwriting existing entries.
bool erase (const iterator &iter)
Erase an entry specified by given iterator.
bool erase (const Key &key)
Erase an entry specified by the given key.
label erase (const HashTable< AnyType, Key, AnyHash > &other)
Remove table entries given by keys of the other hash-table.
label erase (std::initializer_list< Key > keys)
Remove table entries given by the listed keys.
label erase (InputIter first, InputIter last)
Remove multiple entries using an iterator range of keys.
label erase (const FixedList< Key, N > &keys)
Remove table entries given by the listed keys.
label erase (const UList< Key > &keys)
Remove table entries given by the listed keys.
label retain (const HashTable< AnyType, Key, AnyHash > &other)
Retain table entries given by keys of the other hash-table.
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their keys.
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their values.
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their key/value.
void resize (const label sz)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void swap (HashTable< zero::null, Key, Hash > &rhs)
Swap contents into this table.
void transfer (HashTable< zero::null, Key, Hash > &rhs)
Transfer contents into this table.
zero::null & operator[] (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const zero::null & operator[] (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
zero::null & operator() (const Key &key)
Return existing entry or create a new entry.
zero::null & operator() (const Key &key, const zero::null &deflt)
Return existing entry or insert a new entry.
void operator= (const this_type &rhs)
Copy assign.
void operator= (std::initializer_list< std::pair< Key, zero::null >> rhs)
Copy assign from an initializer list.
void operator= (this_type &&rhs)
Move assign.
bool operator== (const this_type &rhs) const
Equality. Tables are equal if all keys and values are equal, independent of order or underlying storage size.
bool operator!= (const this_type &rhs) const
The opposite of the equality operation.
this_type & operator+= (const this_type &rhs)
Add entries into this HashTable.
const_iterator_pair
< const_key_iterator,
this_type > keys () const
A const iterator begin/end pair for iterating over keys.
iterator begin ()
iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const iterator & end ()
iterator to signal the end for any HashTable
const const_iterator & end () const
const_iterator to signal the end for any HashTable
const const_iterator & cend () const
const_iterator to signal the end for any HashTable
Ostream & printInfo (Ostream &os) const
Print information.
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
Public Member Functions inherited from HashTableCore
HashTableCore ()=default
Construct null.
ClassName ("HashTable")
Define template name and debug.
Additional Inherited Members
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Return a canonical (power-of-two) of the requested size.
template<class IteratorType , class TableType >
static IteratorType iterator_begin (TableType &table)
Factory method to create a non-const iterator begin.
template<class IteratorType , class TableType >
static IteratorType iterator_cbegin (const TableType &table)
Factory method to create a const iterator begin.
template<class IteratorType >
static const IteratorType & iterator_end ()
Factory method to return an iterator end.
template<class IteratorType >
static const IteratorType & iterator_cend ()
Factory method to return an iterator cend.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable internal table size. Approximately labelMax/4.
Protected Member Functions inherited from HashTable< zero::null, Key, Hash >
bool iterator_erase (node_type *&entry, label &index)
Low-level entry erasure using iterator internals.
Detailed Description
template<class Key = word, class Hash = string::hash>
class Foam::HashSet< Key, Hash >
A HashTable with keys but without contents that is similar to std::unordered_set.
The entries are considered unordered since their placement depends on the method used to generate the hash key index, the table capacity, insertion order etc. When the key order is important, use the sortedToc() method to obtain a list of sorted keys and use that for further access.
Note
The HashSet iterator dereferences to the key, so the following range-for works as expected:
labelHashSet someLabels{10, 20, 30, 40, ...};
for (const label i : someLabels)
{
    Info<< "val:" << i << nl;
}
Definition at line 80 of file HashSet.H.
Member Typedef Documentation
typedef HashSet<Key, Hash> this_type
The template instance used for this HashSet.
Definition at line 103 of file HashSet.H.
typedef HashTable<zero::null, Key, Hash> parent_type
The template instance used for the parent HashTable.
Definition at line 108 of file HashSet.H.
using iterator = typename parent_type::key_iterator
An iterator, returning reference to the key.
Definition at line 113 of file HashSet.H.
using const_iterator = typename parent_type::const_key_iterator
A const_iterator, returning reference to the key.
Definition at line 118 of file HashSet.H.
Constructor & Destructor Documentation
HashSet () inline
Construct null with default (128) table capacity.
Definition at line 126 of file HashSet.H.
HashSet (const label size) inline explicit
Construct given initial table capacity.
Definition at line 134 of file HashSet.H.
HashSet (Istream & is) inline
Construct from Istream with default table capacity.
Definition at line 142 of file HashSet.H.
HashSet (const FixedList< Key, N > & list) explicit
Construct from FixedList of Key.
Definition at line 57 of file HashSet.C.
HashSet (const UList< Key > & list) explicit
Construct from UList of Key.
Definition at line 69 of file HashSet.C.
References HashSet< Key, Hash >::insert(), and k.
HashSet (const IndirectListBase< Key, Addr > & list) explicit
Construct from an indirect list.
Definition at line 82 of file HashSet.C.
HashSet (std::initializer_list< Key > list)
Construct from an initializer list of Key.
Definition at line 94 of file HashSet.C.
References HashSet< Key, Hash >::insert(), and k.
HashSet (const this_type & hs) inline
Copy construct.
Definition at line 172 of file HashSet.H.
HashSet (this_type && hs) inline
Move construct.
Definition at line 180 of file HashSet.H.
HashSet (const HashTable< AnyType, Key, AnyHash > & tbl) explicit
Construct from the keys of another HashTable, the type of values held is arbitrary.
Definition at line 108 of file HashSet.C.
Member Function Documentation
bool test (const Key & key) const inline
Same as found() - return true if key exists in the set.
Method name compatibility with bitSet and boolList.
Definition at line 200 of file HashSet.H.
Referenced by mappedPatchBase::calcMapping().
bool insert (const Key & key) inline
Insert a new entry, not overwriting existing entries.
Returns
True if the entry inserted, which means that it did not previously exist in the set.
Definition at line 214 of file HashSet.H.
Referenced by cellVolumeWeight::cellVolumeWeight(), primitiveMesh::checkEdgeLength(), primitiveMeshGeometry::checkFaceAngles(), polyMeshGeometry::checkFaceAngles(), primitiveMeshGeometry::checkFaceTwist(), PatchTools::checkOrientation(), PrimitivePatch< Face, FaceList, PointField, PointType >::checkPointManifold(), primitiveMesh::checkPointNearness(), PrimitivePatch< Face, FaceList, PointField, PointType >::checkTopology(), fieldSelection::filters(), surfaceSets::getSurfaceSets(), HashSet< Key, Hash >::HashSet(), Foam::polyMeshZipUpCells(), Foam::HashSetOps::used(), and cuttingSurfaceBase::walkCellCuts().
bool set (const Key & key) inline
Same as insert (no value to overwrite)
Definition at line 222 of file HashSet.H.
Referenced by mappedPatchBase::calcMapping(), Foam::checkFireEdges(), and topoSet::unset().
bool unset (const Key & key) inline
Unset the specified key - same as erase.
Returns
True if the entry existed and was removed
Definition at line 232 of file HashSet.H.
Referenced by topoSet::invert(), Foam::listSwitches(), and topoSet::set().
label insert (InputIter first, InputIter last) inline
Insert keys from the input iterator range.
Returns
The number of new elements inserted
Foam::label insert (std::initializer_list< Key > list) inline
Insert keys from a initializer list of Key.
Returns
The number of new elements inserted
Definition at line 145 of file HashSet.C.
label insert (const FixedList< Key, N > & list) inline
Insert keys from the list of Key.
Returns
The number of new elements inserted
Foam::label insert (const UList< Key > & list) inline
Insert keys from the list of Key.
Returns
The number of new elements inserted
Definition at line 166 of file HashSet.C.
References FixedList< T, N >::begin(), FixedList< T, N >::end(), and insert().
label insert (const IndirectListBase< Key, Addr > & list) inline
Insert keys from the list of Key.
Returns
The number of new elements inserted
label set (InputIter first, InputIter last) inline
Same as insert (no value to overwrite)
Definition at line 282 of file HashSet.H.
label set (std::initializer_list< Key > list) inline
Same as insert (no value to overwrite)
Definition at line 290 of file HashSet.H.
label set (const FixedList< Key, N > & list) inline
Same as insert (no value to overwrite)
Definition at line 299 of file HashSet.H.
label set (const UList< Key > & list) inline
Same as insert (no value to overwrite)
Definition at line 307 of file HashSet.H.
label set (const IndirectListBase< Key, Addr > & list) inline
Same as insert (no value to overwrite)
Definition at line 316 of file HashSet.H.
label setMany (InputIter first, InputIter last) inline
Same as insert (no value to overwrite)
Note
Method name compatibility with bitSet
Definition at line 327 of file HashSet.H.
label unset (InputIter first, InputIter last) inline
Unset the keys listed in the input iterator range.
Returns
The number of items removed
Foam::label unset (std::initializer_list< Key > list) inline
Unset the listed keys - same as erase.
Returns
The number of items removed
Definition at line 199 of file HashSet.C.
References erase().
label unset (const FixedList< Key, N > & list) inline
Unset the listed keys - same as erase.
Returns
The number of items removed
Foam::label unset (const UList< Key > & list) inline
Unset the listed keys - same as erase.
Returns
The number of items removed
Definition at line 220 of file HashSet.C.
References FixedList< T, N >::begin(), and FixedList< T, N >::end().
label unset (const IndirectListBase< Key, Addr > & list) inline
Unset the listed keys - same as erase.
Returns
The number of items removed
Foam::HashSet< Key, Hash >::iterator begin () inline
Definition at line 413 of file HashSet.C.
Foam::HashSet< Key, Hash >::const_iterator begin () const inline
Definition at line 424 of file HashSet.C.
Foam::HashSet< Key, Hash >::const_iterator cbegin () const inline
Definition at line 435 of file HashSet.C.
const Foam::HashSet< Key, Hash >::iterator & end () inline
Definition at line 446 of file HashSet.C.
const Foam::HashSet< Key, Hash >::const_iterator & end () const inline
Definition at line 454 of file HashSet.C.
const Foam::HashSet< Key, Hash >::const_iterator & cend () const inline
Definition at line 462 of file HashSet.C.
Ostream& writeList (Ostream & os, const label shortLen = 0) const inline
Write unordered keys (list), with line-breaks when length exceeds shortLen.
Using '0' suppresses line-breaks entirely.
Definition at line 390 of file HashSet.H.
bool operator() (const Key & key) const inline
Return true if the entry exists, same as found()
Definition at line 242 of file HashSet.C.
bool operator[] (const Key & key) const inline
Return true if the entry exists, same as found().
Definition at line 249 of file HashSet.C.
References found.
void operator= (const this_type & rhs) inline
Copy assignment.
Definition at line 413 of file HashSet.H.
void operator= (this_type && rhs) inline
Move assignment.
Definition at line 421 of file HashSet.H.
bool operator== (const this_type & rhs) const
Sets are equal if all keys are equal, independent of order or underlying storage size.
Definition at line 278 of file HashSet.C.
bool operator!= (const this_type & rhs) const
The opposite of the equality operation.
Definition at line 299 of file HashSet.C.
void operator= (const UList< Key > & rhs)
Assignment from a UList of keys.
Definition at line 264 of file HashSet.C.
References FixedList< T, N >::begin(), FixedList< T, N >::end(), and FixedList< T, N >::size().
void operator= (const FixedList< Key, N > & rhs)
Assignment from a FixedList of keys.
Definition at line 257 of file HashSet.C.
References found.
void operator= (std::initializer_list< Key > rhs)
Assignment from an initializer list of keys.
Definition at line 271 of file HashSet.C.
References UList< T >::begin(), UList< T >::end(), and UList< T >::size().
Foam::HashSet< Key, Hash > & operator|= (const this_type & rhs)
Add entries to this HashSet.
Definition at line 307 of file HashSet.C.
References Foam::operator==().
Foam::HashSet< Key, Hash > & operator&= (const this_type & rhs) inline
Only retain entries found in both HashSets.
Definition at line 321 of file HashSet.C.
Foam::HashSet< Key, Hash > & operator^= (const this_type & rhs)
Only retain unique entries (xor)
Definition at line 330 of file HashSet.C.
this_type& operator+= (const this_type & rhs) inline
Add entries to this HashSet.
Definition at line 480 of file HashSet.H.
Foam::HashSet< Key, Hash > & operator-= (const this_type & rhs) inline
Remove entries from this HashSet.
Definition at line 351 of file HashSet.C.
List<Key> tocValues (const UnaryPredicate & , const bool) delete
Not applicable for HashSet.
List<Key> tocEntries (const BinaryPredicate & , const bool) delete
Not applicable for HashSet.
label countValues (const UnaryPredicate & , const bool) delete
Not applicable for HashSet.
label countEntries (const BinaryPredicate & , const bool) delete
Not applicable for HashSet.
label filterValues (const UnaryPredicate & , const bool) delete
Not applicable for HashSet.
label filterEntries (const BinaryPredicate & , const bool) delete
Not applicable for HashSet.
Foam::label assignMany (const label nItems, InputIter first, InputIter last) inline
Definition at line 33 of file HashSet.C.
References clear(), insert(), and resize().
Foam::label insert (InputIter first, InputIter last) inline
Definition at line 126 of file HashSet.C.
References insert().
Foam::label insert (const FixedList< Key, N > & list) inline
Definition at line 156 of file HashSet.C.
Foam::label insert (const IndirectListBase< Key, Addr > & list) inline
Definition at line 177 of file HashSet.C.
Foam::label unset (InputIter first, InputIter last) inline
Definition at line 188 of file HashSet.C.
Foam::label unset (const FixedList< Key, N > & list) inline
Definition at line 210 of file HashSet.C.
Foam::label unset (const IndirectListBase< Key, Addr > & list) inline
Definition at line 231 of file HashSet.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashSet/HashSet.H
src/OpenFOAM/containers/HashTables/HashSet/HashSet.C