OpenFOAM: diameterModel Class Reference
diameterModel Class Reference abstract
A2stract base-class for dispersed-phase particle diameter models.
Public Member Functions
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &diameterProperties, const phaseModel &phase),(diameterProperties, phase))
diameterModel (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
const dictionary & diameterProperties () const
Return the phase diameter properties dictionary.
const phaseModel & phase () const
Return the phase.
virtual tmp< volScalarField > d () const =0
Return the phase mean diameter field.
virtual void correct ()
Correct the diameter field.
virtual bool read (const dictionary &phaseProperties)=0
Read phaseProperties dictionary.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &dict, const phaseModel &phase),(dict, phase))
diameterModel (const dictionary &dict, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
virtual tmp< volScalarField > d () const =0
Return the phase mean diameter field.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, diameterModel, dictionary,(const dictionary &diameterProperties, const phaseModel &phase),(diameterProperties, phase))
diameterModel (const dictionary &diameterProperties, const phaseModel &phase)
virtual ~diameterModel ()
Destructor.
const dictionary & diameterProperties () const
Return the phase diameter properties dictionary.
const phaseModel & phase () const
Return the phase.
virtual tmp< volScalarField > d () const =0
Return the phase mean diameter field.
virtual void correct ()
Correct the diameter field.
virtual bool read (const dictionary &phaseProperties)=0
Read phaseProperties dictionary.
Static Public Member Functions
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &dict, const phaseModel &phase)
static autoPtr< diameterModel > New (const dictionary &diameterProperties, const phaseModel &phase)
Protected Attributes
dictionary diameterProperties_
const phaseModel & phase_
const dictionary & dict_
Detailed Description
A2stract base-class for dispersed-phase particle diameter models.
Abstract base-class for dispersed-phase particle diameter models.
Source files
diameterModel.H
diameterModel.C
newDiameterModel.C
Source files
diameterModel.H
diameterModel.C
newDiameterModel.C
Source files
diameterModel.H
diameterModel.C
newDiameterModel.C
Definition at line 49 of file diameterModel.H.
Constructor & Destructor Documentation
diameterModel (const dictionary & diameterProperties, const phaseModel & phase)
Definition at line 35 of file diameterModel.C.
~diameterModel () virtual
Destructor.
Definition at line 47 of file diameterModel.C.
diameterModel (const dictionary & dict, const phaseModel & phase)
virtual ~diameterModel () virtual
Destructor.
diameterModel (const dictionary & diameterProperties, const phaseModel & phase)
virtual ~diameterModel () virtual
Destructor.
Member Function Documentation
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &diameterProperties, const phaseModel &phase) , (diameterProperties, phase))
Foam::autoPtr< Foam::diameterModel > New (const dictionary & diameterProperties, const phaseModel & phase) static
Definition at line 27 of file newDiameterModel.C.
References Foam::abort(), Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, phaseModel::name(), dictionary::optionalSubDict(), and diameterModel::phase().
Referenced by phaseModel::clone().
const dictionary& diameterProperties () const inline
Return the phase diameter properties dictionary.
Definition at line 112 of file diameterModel.H.
References diameterModel::diameterProperties_.
const phaseModel& phase () const inline
Return the phase.
Definition at line 120 of file diameterModel.H.
Referenced by diameterModel::New(), and IATEsource::phase().
virtual tmp<volScalarField> d () const pure virtual
Return the phase mean diameter field.
Implemented in velocityGroup, IATE, IATE, linearTsub, isothermal, isothermal, isothermal, constant, constant, and constant.
void correct () virtual
Correct the diameter field.
Reimplemented in IATE, IATE, linearTsub, and isothermal.
Definition at line 53 of file diameterModel.C.
bool read (const dictionary & phaseProperties) pure virtual
Read phaseProperties dictionary.
Implemented in velocityGroup, IATE, IATE, linearTsub, isothermal, isothermal, constant, and constant.
Definition at line 57 of file diameterModel.C.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &dict, const phaseModel &phase) , (dict, phase))
static autoPtr<diameterModel> New (const dictionary & dict, const phaseModel & phase) static
virtual tmp<volScalarField> d () const pure virtual
Return the phase mean diameter field.
Implemented in velocityGroup, IATE, IATE, linearTsub, isothermal, isothermal, isothermal, constant, constant, and constant.
TypeName ("diameterModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , diameterModel , dictionary , (const dictionary &diameterProperties, const phaseModel &phase) , (diameterProperties, phase))
static autoPtr<diameterModel> New (const dictionary & diameterProperties, const phaseModel & phase) static
const dictionary& diameterProperties () const inline
Return the phase diameter properties dictionary.
Definition at line 112 of file diameterModel.H.
References diameterModel::diameterProperties_.
const phaseModel& phase () const inline
Return the phase.
Definition at line 120 of file diameterModel.H.
virtual tmp<volScalarField> d () const pure virtual
Return the phase mean diameter field.
Implemented in velocityGroup, IATE, IATE, linearTsub, isothermal, isothermal, isothermal, constant, constant, and constant.
virtual void correct () virtual
Correct the diameter field.
Reimplemented in IATE, IATE, linearTsub, and isothermal.
virtual bool read (const dictionary & phaseProperties) pure virtual
Read phaseProperties dictionary.
Implemented in velocityGroup, IATE, IATE, linearTsub, isothermal, isothermal, constant, and constant.
Member Data Documentation
dictionary diameterProperties_ protected
Definition at line 56 of file diameterModel.H.
Referenced by diameterModel::diameterProperties().
const phaseModel & phase_ protected
Definition at line 57 of file diameterModel.H.
const dictionary& dict_ protected
Definition at line 55 of file diameterModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/diameterModels/diameterModel/diameterModel.H
applications/solvers/multiphase/multiphaseEulerFoam/multiphaseSystem/diameterModels/diameterModel/diameterModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/twoPhaseSystem/diameterModels/diameterModel/diameterModel.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/diameterModels/diameterModel/diameterModel.C
src/phaseSystemModels/reactingEulerFoam/phaseSystems/diameterModels/diameterModel/newDiameterModel.C