OpenFOAM: cylindrical Class Reference
cylindrical Class Reference
A cylindrical coordinate system (r-theta-z). The coordinate system angle theta is always in radians.
Public Member Functions
TypeNameNoDebug ("cylindrical")
Runtime type information.
cylindrical ()
Construct null (identity coordinateSystem)
cylindrical (const cylindrical &csys)=default
Copy construct.
cylindrical (cylindrical &&csys)=default
Move construct.
cylindrical (const coordinateSystem &csys)
Copy construct from another coordinateSystem type.
cylindrical (coordinateSystem &&csys)
Move construct from another coordinateSystem type.
cylindrical (autoPtr< coordinateSystem > &&csys)
Move construct from autoPtr of another coordinateSystem type.
cylindrical (const point &origin, const coordinateRotation &crot)
Construct from origin and rotation.
cylindrical (const point &origin, const vector &axis)
Construct from origin and single axis.
cylindrical (const word &name, const point &origin, const vector &axis)
Construct from origin and single axis.
cylindrical (const point &origin, const vector &axis, const vector &dirn)
Construct from origin and two axes.
cylindrical (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and two axes.
cylindrical (const word &name, const dictionary &dict)
Construct from dictionary with a given name.
cylindrical (const dictionary &dict)
Construct from dictionary without a name.
cylindrical (const dictionary &dict, const word &dictName)
Construct from dictionary with optional subDict lookup.
virtual autoPtr< coordinateSystem > clone () const
Return clone.
virtual ~cylindrical ()=default
Destructor.
virtual bool uniform () const
Treat the rotation tensor as non-uniform.
virtual tensor R (const point &global) const
Position-dependent rotation tensor at a single point.
cylindrical & operator= (const cylindrical &)=default
Copy assignment.
cylindrical & operator= (cylindrical &&)=default
Move assignment.
Public Member Functions inherited from coordinateSystem
TypeName ("coordinateSystem")
Runtime type information.
coordinateSystem ()
Construct null. This is an identity coordinateSystem.
coordinateSystem (const coordinateRotation &crot)
Copy construct from rotation with origin=0.
coordinateSystem (coordinateRotation &&crot)
Move construct from rotation with origin=0.
coordinateSystem (const coordinateSystem &csys)
Copy construct.
coordinateSystem (coordinateSystem &&csys)
Move construct.
coordinateSystem (autoPtr< coordinateSystem > &&csys)
Move construct from autoPtr.
coordinateSystem (const word &name, const coordinateSystem &csys)
Copy construct with a different name.
coordinateSystem (const point &origin, const coordinateRotation &crot)
Construct from origin and rotation.
coordinateSystem (const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const point &origin, const coordinateRotation &crot)
Construct from origin and rotation.
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const dictionary &dict)
Construct from dictionary with a given name.
coordinateSystem (const dictionary &dict)
Construct from dictionary without a name.
coordinateSystem (const dictionary &dict, const word &dictName)
Construct from dictionary with optional subDict lookup.
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, coordinateSystem, registry,(const objectRegistry &obr, const dictionary &dict),(obr, dict))
virtual ~coordinateSystem ()=default
Destructor.
virtual bool valid () const
Considered valid if it has a specification.
virtual const coordinateRotation & rotation () const
The rotation specification.
virtual const word & name () const
Return the name.
virtual const string & note () const
Return the optional note.
virtual const point & origin () const
Return origin.
virtual const tensor & R () const
Return const reference to the rotation tensor.
virtual const vector e1 () const
The local Cartesian x-axis in global coordinates.
virtual const vector e2 () const
The local Cartesian y-axis in global coordinates.
virtual const vector e3 () const
The local Cartesian z-axis in global coordinates.
virtual void rename (const word &newName)
Rename.
virtual string & note ()
Provide non-constant access to the optional note.
virtual point & origin ()
Edit access to origin.
virtual void clear ()
Reset origin and rotation to an identity coordinateSystem.
virtual void rotation (autoPtr< coordinateRotation > &&crot)
Change the rotation.
virtual void write (Ostream &os) const
Write.
virtual void writeEntry (const word &keyword, Ostream &os) const
Write dictionary entry.
void operator= (const coordinateSystem &csys)
Copy assignment.
void operator= (coordinateSystem &&csys)
Move assignment.
void operator= (const autoPtr< coordinateSystem > &csys)
Copy assignment from autoPtr.
void operator= (autoPtr< coordinateSystem > &&csys)
Move assignment from autoPtr.
virtual tmp< tensorField > R (const UList< point > &global) const
Position-dependent rotation tensors (when uniform = false)
virtual tmp< tensorField > R (const pointUIndList &global) const
Position-dependent rotation tensors (when uniform = false)
point transformPoint (const point &localCart) const
Transform point and add origin offset.
tmp< pointField > transformPoint (const UList< point > &localCart) const
Transform points and add origin offset.
tmp< pointField > transformPoint (const pointUIndList &localCart) const
Transform points and add origin offset.
point invTransformPoint (const point &global) const
Remove origin offset and inverse transform point.
tmp< pointField > invTransformPoint (const UList< point > &global) const
Remove origin offset and inverse transform points.
tmp< pointField > invTransformPoint (const pointUIndList &global) const
Remove origin offset and inverse transform points.
point globalPosition (const point &local) const
From local coordinate position to global (cartesian) position.
tmp< pointField > globalPosition (const pointField &local) const
From local coordinate position to global (cartesian) position.
point localPosition (const point &global) const
From global (cartesian) position to local coordinate position.
tmp< pointField > localPosition (const pointField &global) const
From global (cartesian) position to local coordinate position.
vector globalVector (const vector &local) const
From local to global (cartesian) vector components.
tmp< vectorField > globalVector (const vectorField &local) const
From local to global (cartesian) vector components.
vector localVector (const vector &global) const
From global (cartesian) to local vector components.
tmp< vectorField > localVector (const vectorField &global) const
From global (cartesian) to local vector components.
virtual symmTensor transformPrincipal (const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< vector > &input) const
virtual symmTensor transformPrincipal (const point &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const UList< vector > &input) const
virtual scalar transform (const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< scalar > &input) const
virtual scalar transform (const point &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< point > &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< point > &global, const UList< scalar > &input) const
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const UList< scalar > &input) const
virtual vector transform (const vector &input) const
virtual tmp< Field< vector > > transform (const UList< vector > &input) const
virtual vector transform (const point &global, const vector &input) const
virtual tmp< Field< vector > > transform (const UList< point > &global, const vector &input) const
virtual tmp< Field< vector > > transform (const pointUIndList &global, const vector &input) const
virtual tmp< Field< vector > > transform (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< vector > > transform (const pointUIndList &global, const UList< vector > &input) const
virtual sphericalTensor transform (const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< sphericalTensor > &input) const
virtual sphericalTensor transform (const point &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< point > &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const pointUIndList &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< point > &global, const UList< sphericalTensor > &input) const
virtual tmp< Field
< sphericalTensor > > transform (const pointUIndList &global, const UList< sphericalTensor > &input) const
virtual symmTensor transform (const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< symmTensor > &input) const
virtual symmTensor transform (const point &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const UList< symmTensor > &input) const
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const UList< symmTensor > &input) const
virtual tensor transform (const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< tensor > &input) const
virtual tensor transform (const point &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< point > &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< point > &global, const UList< tensor > &input) const
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const UList< tensor > &input) const
virtual scalar invTransform (const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< scalar > &input) const
virtual scalar invTransform (const point &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const UList< scalar > &input) const
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const UList< scalar > &input) const
virtual vector invTransform (const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< vector > &input) const
virtual vector invTransform (const point &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const UList< vector > &input) const
virtual sphericalTensor invTransform (const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< sphericalTensor > &input) const
virtual sphericalTensor invTransform (const point &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< point > &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const pointUIndList &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< point > &global, const UList< sphericalTensor > &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const pointUIndList &global, const UList< sphericalTensor > &input) const
virtual symmTensor invTransform (const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< symmTensor > &input) const
virtual symmTensor invTransform (const point &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const UList< symmTensor > &input) const
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const UList< symmTensor > &input) const
virtual tensor invTransform (const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< tensor > &input) const
virtual tensor invTransform (const point &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const UList< tensor > &input) const
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const UList< tensor > &input) const
template<class PointField >
Foam::tmp< Foam::tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
Foam::tmp< Foam::pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
Foam::tmp< Foam::pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Static Public Attributes
static const cylindrical null
Global (identity) cylindrical coordinate system.
Protected Member Functions
virtual vector localToGlobal (const vector &local, bool translate) const
From local coordinate system to the global Cartesian system with optional translation for the origin.
virtual tmp< vectorField > localToGlobal (const vectorField &local, bool translate) const
From local coordinate system to the global Cartesian system with optional translation for the origin.
virtual vector globalToLocal (const vector &global, bool translate) const
From global Cartesian system to the local coordinate system with optional translation for the origin.
virtual tmp< vectorField > globalToLocal (const vectorField &global, bool translate) const
Convert from global Cartesian system to the local coordinate system with optional translation for the origin.
Protected Member Functions inherited from coordinateSystem
template<class PointField >
tmp< tensorField > rotationsImpl (const PointField &global) const
Implementation for R() methods.
template<class PointField >
tmp< pointField > transformPointImpl (const PointField &localCart) const
Implementation for transformPoint() methods.
template<class PointField >
tmp< pointField > invTransformPointImpl (const PointField &global) const
Implementation for transformPosition() methods.
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
Use position-dependent transform tensors for multiple inputs.
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Use position-dependent transform tensors for single input.
void assign (const dictionary &dict)
Assign from dictionary content.
coordinateSystem (std::nullptr_t)
Construct null, without allocating a coordinateRotation specification.
Additional Inherited Members
Static Public Member Functions inherited from coordinateSystem
static autoPtr< coordinateSystem > New (word modelType, const objectRegistry &obr, const dictionary &dict)
Select construct the specified coordinate system type with reference to objectRegistry for indirect entries.
static autoPtr< coordinateSystem > New (word modelType, const dictionary &dict)
Select construct the specified coordinate system type.
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict, const word &dictName="")
Select construct from dictionary with reference to objectRegistry for indirect entries.
static autoPtr< coordinateSystem > New (const dictionary &dict, const word &dictName="")
Select constructed from dictionary.
static autoPtr< coordinateSystem > New (Istream &is)
Select constructed from Istream.
Static Protected Member Functions inherited from coordinateSystem
template<class RetType , class Type , class BinaryOp >
static tmp< Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
Apply single transform tensor for multiple inputs.
Protected Attributes inherited from coordinateSystem
autoPtr< coordinateRotation > spec_
User specification of the coordinate rotation.
point origin_
The coordinate system origin.
tensor rot_
The rotation tensor.
word name_
The name of the coordinate system (optional)
string note_
An optional note describing the coordinate system.
Static Protected Attributes inherited from coordinateSystem
static coordinateSystem dummy_
Dummy coordinate system for suppressed manipulation.
Detailed Description
A cylindrical coordinate system (r-theta-z). The coordinate system angle theta is always in radians.
Dictionary entries
Property Description Required Default
type type name: cylindrical yes
Source files
cylindricalCS.H
cylindricalCS.C
cylindricalCSTransform.C
Definition at line 67 of file cylindricalCS.H.
Constructor & Destructor Documentation
cylindrical ()
Construct null (identity coordinateSystem)
Definition at line 84 of file cylindricalCS.C.
cylindrical (const cylindrical & csys) default
Copy construct.
cylindrical (cylindrical && csys) default
Move construct.
cylindrical (const coordinateSystem & csys) explicit
Copy construct from another coordinateSystem type.
Definition at line 90 of file cylindricalCS.C.
cylindrical (coordinateSystem && csys) explicit
Move construct from another coordinateSystem type.
Definition at line 96 of file cylindricalCS.C.
cylindrical (autoPtr< coordinateSystem > && csys) explicit
Move construct from autoPtr of another coordinateSystem type.
Definition at line 102 of file cylindricalCS.C.
cylindrical (const point & origin, const coordinateRotation & crot)
Construct from origin and rotation.
Definition at line 109 of file cylindricalCS.C.
cylindrical (const point & origin, const vector & axis)
Construct from origin and single axis.
Definition at line 119 of file cylindricalCS.C.
cylindrical (const word & name, const point & origin, const vector & axis)
Construct from origin and single axis.
Definition at line 129 of file cylindricalCS.C.
cylindrical (const point & origin, const vector & axis, const vector & dirn)
Construct from origin and two axes.
Definition at line 145 of file cylindricalCS.C.
cylindrical (const word & name, const point & origin, const vector & axis, const vector & dirn)
Construct from origin and two axes.
Definition at line 156 of file cylindricalCS.C.
cylindrical (const word & name, const dictionary & dict)
Construct from dictionary with a given name.
Definition at line 168 of file cylindricalCS.C.
References dictionary::lookupOrDefault(), and Foam::warnCompatDegrees().
cylindrical (const dictionary & dict) explicit
Construct from dictionary without a name.
Definition at line 182 of file cylindricalCS.C.
cylindrical (const dictionary & dict, const word & dictName)
Construct from dictionary with optional subDict lookup.
Parameters
dictName If non-empty, the sub-dictionary to use.
Definition at line 194 of file cylindricalCS.C.
References dictionary::lookupOrDefault(), dictionary::subDict(), and Foam::warnCompatDegrees().
virtual ~cylindrical () virtual default
Destructor.
Member Function Documentation
Foam::vector localToGlobal (const vector & local, bool translate) const protected virtual
From local coordinate system to the global Cartesian system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 252 of file cylindricalCS.C.
References coordinateSystem::localToGlobal(), and Foam::toCartesian().
Foam::tmp< Foam::vectorField > localToGlobal (const vectorField & local, bool translate) const protected virtual
From local coordinate system to the global Cartesian system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 266 of file cylindricalCS.C.
References i, coordinateSystem::localToGlobal(), tmp< T >::New(), UList< T >::size(), and Foam::toCartesian().
Foam::vector globalToLocal (const vector & global, bool translate) const protected virtual
From global Cartesian system to the local coordinate system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 291 of file cylindricalCS.C.
References Foam::fromCartesian(), and coordinateSystem::globalToLocal().
Foam::tmp< Foam::vectorField > globalToLocal (const vectorField & global, bool translate) const protected virtual
Convert from global Cartesian system to the local coordinate system with optional translation for the origin.
Reimplemented from coordinateSystem.
Definition at line 304 of file cylindricalCS.C.
References Foam::fromCartesian(), coordinateSystem::globalToLocal(), i, tmp< T >::ref(), and UList< T >::size().
TypeNameNoDebug ("cylindrical")
Runtime type information.
virtual autoPtr<coordinateSystem> clone () const inline virtual
Return clone.
Reimplemented from coordinateSystem.
Definition at line 221 of file cylindricalCS.H.
virtual bool uniform () const inline virtual
Treat the rotation tensor as non-uniform.
Reimplemented from coordinateSystem.
Definition at line 238 of file cylindricalCS.H.
Foam::tensor R (const point & global) const virtual
Position-dependent rotation tensor at a single point.
Returns
tensor
Reimplemented from coordinateSystem.
Definition at line 217 of file cylindricalCS.C.
References Tensor< Cmpt >::col(), Foam::mag(), and origin_().
cylindrical& operator= (const cylindrical &) default
Copy assignment.
cylindrical& operator= (cylindrical &&) default
Move assignment.
Member Data Documentation
const Foam::coordSystem::cylindrical null static
Global (identity) cylindrical coordinate system.
Definition at line 129 of file cylindricalCS.H.
The documentation for this class was generated from the following files:
src/meshTools/coordinate/systems/cylindricalCS.H
src/meshTools/coordinate/systems/cylindricalCS.C