OpenFOAM: basicMultiComponentMixture Class Reference
basicMultiComponentMixture Class Reference
Mixtures
Multi-component mixture.
Public Types
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Public Types inherited from basicMixture
typedef basicMixture basicMixtureType
The base class of the mixture.
Public Member Functions
TypeName ("basicMultiComponentMixture")
Run time type information.
basicMultiComponentMixture (const dictionary &thermoDict, const wordList &specieNames, const fvMesh &mesh, const word &phaseName)
Construct from dictionary, species names, mesh and phase name.
virtual ~basicMultiComponentMixture ()=default
Destructor.
const speciesTable & species () const
Return the table of species.
bool contains (const word &specieName) const
Does the mixture include this specie?
bool active (label speciei) const
Return true for active species.
const List< bool > & active () const
Return the bool list of active species.
void setActive (label speciei)
Set speciei active.
void setInactive (label speciei)
Set speciei inactive.
PtrList< volScalarField > & Y ()
Return the mass-fraction fields.
const PtrList< volScalarField > & Y () const
Return the const mass-fraction fields.
volScalarField & Y (const label i)
Return the mass-fraction field for a specie given by index.
const volScalarField & Y (const label i) const
Return the const mass-fraction field for a specie given by index.
volScalarField & Y (const word &specieName)
Return the mass-fraction field for a specie given by name.
const volScalarField & Y (const word &specieName) const
Return the const mass-fraction field for a specie given by name.
Public Member Functions inherited from basicMixture
basicMixture (const dictionary &, const fvMesh &, const word &)
Construct from dictionary, mesh and phase name.
Protected Attributes
speciesTable species_
Table of specie names.
List< bool > active_
List of specie active flags.
PtrList< volScalarField > Y_
Species mass fractions.
Detailed Description
Multi-component mixture.
Provides a list of mass fraction fields and helper functions to query mixture composition.
Source files
basicMultiComponentMixture.H
basicMultiComponentMixture.C
Definition at line 56 of file basicMultiComponentMixture.H.
Member Typedef Documentation
typedef basicMultiComponentMixture basicMixtureType
The base class of the mixture.
Definition at line 92 of file basicMultiComponentMixture.H.
Constructor & Destructor Documentation
basicMultiComponentMixture (const dictionary & thermoDict, const wordList & specieNames, const fvMesh & mesh, const word & phaseName)
Construct from dictionary, species names, mesh and phase name.
Definition at line 33 of file basicMultiComponentMixture.C.
References Foam::defineTypeNameAndDebug().
virtual ~basicMultiComponentMixture () virtual default
Destructor.
Member Function Documentation
TypeName ("basicMultiComponentMixture")
Run time type information.
const Foam::speciesTable & species () const inline
Return the table of species.
Definition at line 22 of file basicMultiComponentMixtureI.H.
Referenced by InterfaceCompositionModel< Thermo, OtherThermo >::getLocalThermo(), and TDACChemistryModel< CompType, ThermoType >::TDACChemistryModel().
bool contains (const word & specieName) const inline
Does the mixture include this specie?
Definition at line 29 of file basicMultiComponentMixtureI.H.
References basicMultiComponentMixture::species_.
bool active (label speciei) const inline
Return true for active species.
Definition at line 37 of file basicMultiComponentMixtureI.H.
const Foam::List< bool > & active () const inline
Return the bool list of active species.
Definition at line 43 of file basicMultiComponentMixtureI.H.
void setActive (label speciei) inline
Set speciei active.
Definition at line 49 of file basicMultiComponentMixtureI.H.
void setInactive (label speciei) inline
Set speciei inactive.
Definition at line 55 of file basicMultiComponentMixtureI.H.
Referenced by TDACChemistryModel< CompType, ThermoType >::TDACChemistryModel().
Foam::PtrList< Foam::volScalarField > & Y () inline
Return the mass-fraction fields.
Definition at line 62 of file basicMultiComponentMixtureI.H.
const Foam::PtrList< Foam::volScalarField > & Y () const inline
Return the const mass-fraction fields.
Definition at line 69 of file basicMultiComponentMixtureI.H.
Foam::volScalarField & Y (const label i) inline
Return the mass-fraction field for a specie given by index.
Definition at line 75 of file basicMultiComponentMixtureI.H.
const Foam::volScalarField & Y (const label i) const inline
Return the const mass-fraction field for a specie given by index.
Definition at line 82 of file basicMultiComponentMixtureI.H.
References i.
Foam::volScalarField & Y (const word & specieName) inline
Return the mass-fraction field for a specie given by name.
Definition at line 91 of file basicMultiComponentMixtureI.H.
References i.
const Foam::volScalarField & Y (const word & specieName) const inline
Return the const mass-fraction field for a specie given by name.
Definition at line 100 of file basicMultiComponentMixtureI.H.
Member Data Documentation
speciesTable species_ protected
Table of specie names.
Definition at line 68 of file basicMultiComponentMixture.H.
Referenced by basicMultiComponentMixture::contains().
List<bool> active_ protected
List of specie active flags.
Definition at line 73 of file basicMultiComponentMixture.H.
PtrList<volScalarField> Y_ protected
Species mass fractions.
Definition at line 78 of file basicMultiComponentMixture.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.H
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixture.C
src/thermophysicalModels/reactionThermo/mixtures/basicMultiComponentMixture/basicMultiComponentMixtureI.H