OpenFOAM: SHA1Digest Class Reference
SHA1Digest Class Reference
The SHA1 message digest.
Public Member Functions
SHA1Digest ()
Construct a zero digest.
SHA1Digest (Istream &is)
Read construct a digest.
void clear ()
Reset the digest to zero.
bool empty () const
Return true if the digest is empty (ie, all zero).
std::string str (const bool prefixed=false) const
Return (40-byte) text representation, optionally with '_' prefix.
Istream & read (Istream &is)
Read (40-byte) text representation.
Ostream & write (Ostream &os, const bool prefixed=false) const
Write (40-byte) text representation, optionally with '_' prefix.
bool operator== (const SHA1Digest &) const
Equality operator.
bool operator== (const std::string &hexdigits) const
Compare to (40-byte) text representation (eg, from sha1sum)
bool operator== (const char *hexdigits) const
Compare to (40-byte) text representation (eg, from sha1sum)
bool operator!= (const SHA1Digest &) const
Inequality operator.
bool operator!= (const std::string &hexdigits) const
Inequality operator.
bool operator!= (const char *hexdigits) const
Inequality operator.
Static Public Attributes
static const SHA1Digest null
A null digest (ie, all zero)
Friends
class SHA1
Detailed Description
The SHA1 message digest.
See Also
Foam::SHA1
Source files
SHA1Digest.H
SHA1Digest.C
Definition at line 56 of file SHA1Digest.H.
Constructor & Destructor Documentation
SHA1Digest ()
Construct a zero digest.
Definition at line 74 of file SHA1Digest.C.
SHA1Digest (Istream & is) explicit
Read construct a digest.
Definition at line 80 of file SHA1Digest.C.
References SHA1Digest::clear().
Member Function Documentation
void clear ()
Reset the digest to zero.
Definition at line 89 of file SHA1Digest.C.
Referenced by SHA1Digest::SHA1Digest().
bool empty () const
Return true if the digest is empty (ie, all zero).
Definition at line 95 of file SHA1Digest.C.
std::string str (const bool prefixed = false) const
Return (40-byte) text representation, optionally with '_' prefix.
Definition at line 109 of file SHA1Digest.C.
Foam::Istream & read (Istream & is)
Read (40-byte) text representation.
Since leading and intermediate underscores are skipped, a '_' can be prefixed to the text representation to use an unquoted SHA1Digest without parsing ambiguities as a number.
Definition at line 134 of file SHA1Digest.C.
Referenced by Foam::operator<<().
Foam::Ostream & write (Ostream & os, const bool prefixed = false) const
Write (40-byte) text representation, optionally with '_' prefix.
Definition at line 149 of file SHA1Digest.C.
bool operator== (const SHA1Digest & rhs) const
Equality operator.
Definition at line 169 of file SHA1Digest.C.
bool operator== (const std::string & hexdigits) const
Compare to (40-byte) text representation (eg, from sha1sum)
An empty string is equivalent to "0000000000000000000000000000000000000000" The hexdigits may optionally start with a '_' prefix
Definition at line 175 of file SHA1Digest.C.
bool operator== (const char * hexdigits) const
Compare to (40-byte) text representation (eg, from sha1sum)
A null or empty string is equivalent to "0000000000000000000000000000000000000000" The hexdigits may optionally start with a '_' prefix
Definition at line 209 of file SHA1Digest.C.
bool operator!= (const SHA1Digest & rhs) const
Inequality operator.
Definition at line 243 of file SHA1Digest.C.
bool operator!= (const std::string & hexdigits) const
Inequality operator.
Definition at line 249 of file SHA1Digest.C.
References Foam::operator==().
bool operator!= (const char * hexdigits) const
Inequality operator.
Definition at line 255 of file SHA1Digest.C.
References Foam::operator==().
Friends And Related Function Documentation
friend class SHA1 friend
Definition at line 77 of file SHA1Digest.H.
Member Data Documentation
const Foam::SHA1Digest null static
A null digest (ie, all zero)
Definition at line 88 of file SHA1Digest.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/hashes/SHA1/SHA1Digest.H
src/OpenFOAM/primitives/hashes/SHA1/SHA1Digest.C