OpenFOAM: hexRef8Data Class Reference
hexRef8Data Class Reference
Various for reading/decomposing/reconstructing/distributing refinement data.
Public Member Functions
hexRef8Data (const IOobject &io)
Construct read. Has special provision for only some processors.
hexRef8Data (const IOobject &io, const hexRef8Data &, const labelList &cellMap, const labelList &pointMap)
Construct as subset.
hexRef8Data (const IOobject &io, const UPtrList< const labelList > &cellMaps, const UPtrList< const labelList > &pointMaps, const UPtrList< const hexRef8Data > &)
Construct from multiple hexRef8Data.
~hexRef8Data ()
Destructor.
void sync (const IOobject &io)
Parallel synchronise. This enforces valid objects on all processors.
void updateMesh (const mapPolyMesh &)
Update local numbering for changed mesh.
void distribute (const mapDistributePolyMesh &)
In-place distribute.
bool write () const
Write.
Detailed Description
Various for reading/decomposing/reconstructing/distributing refinement data.
Source files
hexRef8Data.H
hexRef8Data.C
Definition at line 56 of file hexRef8Data.H.
Constructor & Destructor Documentation
hexRef8Data (const IOobject & io)
Construct read. Has special provision for only some processors.
having the files so can be used in redistribution.
Definition at line 35 of file hexRef8Data.C.
References Foam::endl(), Foam::Info, IOobject::name(), IOobject::rename(), Foam::returnReduce(), and IOobject::typeHeaderOk().
hexRef8Data (const IOobject & io, const hexRef8Data & data, const labelList & cellMap, const labelList & pointMap)
Construct as subset.
Definition at line 97 of file hexRef8Data.C.
hexRef8Data (const IOobject & io, const UPtrList< const labelList > & cellMaps, const UPtrList< const labelList > & pointMaps, const UPtrList< const hexRef8Data > & procDatas)
Construct from multiple hexRef8Data.
Definition at line 153 of file hexRef8Data.C.
~hexRef8Data ()
Destructor.
Definition at line 244 of file hexRef8Data.C.
Member Function Documentation
void sync (const IOobject & io)
Parallel synchronise. This enforces valid objects on all processors.
(even if they don't have a mesh). Used by redistributePar.
Definition at line 250 of file hexRef8Data.C.
void updateMesh (const mapPolyMesh & map)
Update local numbering for changed mesh.
Definition at line 311 of file hexRef8Data.C.
void distribute (const mapDistributePolyMesh & map)
In-place distribute.
Definition at line 382 of file hexRef8Data.C.
bool write () const
Write.
Definition at line 402 of file hexRef8Data.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8Data.H
src/dynamicMesh/polyTopoChange/polyTopoChange/hexRef8/hexRef8Data.C