OpenFOAM: surfaceInterpolationScheme< Type > Class Template Reference
surfaceInterpolationScheme< Type > Class Template Reference abstract
Abstract base class for surface interpolation schemes.
Public Member Functions
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const =0
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
virtual tmp< GeometricField
< typename innerProduct
< vector, Type >::type,
fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField
< typename innerProduct
< typename SFType::value_type,
Type >::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Detailed Description
template<class Type>
class Foam::surfaceInterpolationScheme< Type >
Abstract base class for surface interpolation schemes.
Source files
surfaceInterpolationScheme.H
surfaceInterpolationScheme.C
Definition at line 53 of file surfaceInterpolationScheme.H.
Constructor & Destructor Documentation
surfaceInterpolationScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 119 of file surfaceInterpolationScheme.H.
virtual ~surfaceInterpolationScheme () virtual default
Destructor.
Member Function Documentation
TypeName ("surfaceInterpolationScheme< Type >")
Runtime type information.
declareRunTimeSelectionTable (tmp , surfaceInterpolationScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
declareRunTimeSelectionTable (tmp , surfaceInterpolationScheme< Type > , MeshFlux , (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData) , (mesh, faceFlux, schemeData))
Foam::tmp< Foam::surfaceInterpolationScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 33 of file surfaceInterpolationScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalError, Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, and InfoInFunction.
Referenced by laplacianScheme< Type, GType >::laplacianScheme(), and multivariateIndependentScheme< Type >::operator()().
Foam::tmp< Foam::surfaceInterpolationScheme< Type > > New (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 74 of file surfaceInterpolationScheme.C.
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 158 of file surfaceInterpolationScheme.H.
Referenced by localBlended< Type >::blendingFactor(), cubic< Type >::corrected(), CentredFitScheme< Type, Polynomial, Stencil >::corrected(), PureUpwindFitScheme< Type, Polynomial, Stencil >::corrected(), skewCorrected< Type >::corrected(), localMax< Type >::weights(), localMin< Type >::weights(), skewCorrected< Type >::weights(), and localBlended< Type >::weights().
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas, const tmp< surfaceScalarField > & tys) static
Return the face-interpolate of the given cell field.
with the given owner and neighbour weighting factors
Definition at line 120 of file surfaceInterpolationScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), tmp< T >::clear(), IOobject::db(), Foam::expressions::patchExpr::debug, DimensionedField< Type, GeoMesh >::dimensions(), Foam::endl(), forAll, InfoInFunction, IOobject::instance(), lambda(), DimensionedField< Type, GeoMesh >::mesh(), N(), IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), Foam::constant::mathematical::pi(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), tmp< T >::ref(), UList< T >::size(), and y.
Referenced by skewCorrected< Type >::skewCorrection(), and linear< Type >::weights().
static tmp< GeometricField < typename innerProduct<typename SFType::value_type, Type>::type, fvsPatchField, surfaceMesh > > dotInterpolate (const SFType & Sf, const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas) static
Return the face-interpolate of the given cell field.
with the given weighting factors dotted with given field Sf
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tlambdas) static
Return the face-interpolate of the given cell field.
with the given weighting factors
Definition at line 301 of file surfaceInterpolationScheme.C.
virtual tmp<surfaceScalarField> weights (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Return the interpolation weighting factors for the given field.
Implemented in DEShybrid< Type >, cellCoBlended< Type >, CoBlended< Type >, multivariateSurfaceInterpolationScheme< Type >::fieldScheme, blended< Type >, limitedSurfaceInterpolationScheme< Type >, weightedFlux< Type >, fixedBlended< Type >, localBlended< Type >, limiterBlended< Type >, upwind< Type >, outletStabilised< Type >, limitWith< Type >, multivariateUpwind< Type >::fieldScheme, clippedLinear< Type >, multivariateSelectionScheme< Type >::fieldScheme, downwind< Type >, multivariateScheme< Type, Scheme >::fieldScheme, weighted< Type >, skewCorrected< Type >, harmonic, localMax< Type >, localMin< Type >, LUST< Type >, reverseLinear< Type >, linear< Type >, and midPoint< Type >.
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented in DEShybrid< Type >, cellCoBlended< Type >, CoBlended< Type >, fixedBlended< Type >, localBlended< Type >, limiterBlended< Type >, outletStabilised< Type >, limitWith< Type >, linearUpwindNormal< Type >, linearUpwindV< Type >, deferredCorrection< Type >, skewCorrected< Type >, linearUpwind< Type >, UpwindFitScheme< Type, Polynomial, Stencil >, PureUpwindFitScheme< Type, Polynomial, Stencil >, LUST< Type >, CentredFitScheme< Type, Polynomial, Stencil >, pointLinear< Type >, and cubic< Type >.
Definition at line 222 of file surfaceInterpolationScheme.H.
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the explicit correction to the face-interpolate.
for the given field
Reimplemented in DEShybrid< Type >, cellCoBlended< Type >, CoBlended< Type >, fixedBlended< Type >, localBlended< Type >, limiterBlended< Type >, outletStabilised< Type >, skewCorrected< Type >, limitWith< Type >, linearUpwindNormal< Type >, linearUpwindV< Type >, deferredCorrection< Type >, linearUpwind< Type >, UpwindFitScheme< Type, Polynomial, Stencil >, PureUpwindFitScheme< Type, Polynomial, Stencil >, LUST< Type >, CentredFitScheme< Type, Polynomial, Stencil >, pointLinear< Type >, and cubic< Type >.
Definition at line 233 of file surfaceInterpolationScheme.H.
virtual tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the face-interpolate of the given cell field.
with explicit correction dotted with given field Sf
tmp< GeometricField < typename innerProduct<vector, Type>::type, fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField & Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
with explicit correction dotted with given field Sf
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the face-interpolate of the given cell field.
with explicit correction
Reimplemented in DEShybrid< Type >, cellCoBlended< Type >, CoBlended< Type >, weightedFlux< Type >, fixedBlended< Type >, localBlended< Type >, limiterBlended< Type >, harmonic, localMax< Type >, and localMin< Type >.
Definition at line 391 of file surfaceInterpolationScheme.C.
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) const
Return the face-interpolate of the given tmp cell field.
with explicit correction
Definition at line 420 of file surfaceInterpolationScheme.C.
The documentation for this class was generated from the following files:
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolationScheme/surfaceInterpolationScheme.H
src/finiteVolume/interpolation/surfaceInterpolation/surfaceInterpolationScheme/surfaceInterpolationScheme.C