OpenFOAM: SpalartAllmarasDES< BasicTurbulenceModel > Class Template Reference
SpalartAllmarasDES< BasicTurbulenceModel > Class Template Reference
DES turbulence
SpalartAllmarasDES DES turbulence model for incompressible and compressible flows.
Public Types
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Types inherited from DESModel< BasicTurbulenceModel >
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Types inherited from LESeddyViscosity< BasicTurbulenceModel >
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Types inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
typedef LESModel
< BasicTurbulenceModel >
::alphaField alphaField
typedef LESModel
< BasicTurbulenceModel >
::rhoField rhoField
typedef LESModel
< BasicTurbulenceModel >
::transportModel transportModel
Public Types inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
typedef LESModel
< BasicTurbulenceModel >
::alphaField alphaField
typedef LESModel
< BasicTurbulenceModel >
::rhoField rhoField
typedef LESModel
< BasicTurbulenceModel >
::transportModel transportModel
Public Types inherited from LESModel< BasicTurbulenceModel >
typedef
BasicTurbulenceModel::alphaField alphaField
typedef
BasicTurbulenceModel::rhoField rhoField
typedef
BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SpalartAllmarasDES")
Runtime type information.
SpalartAllmarasDES (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
Construct from components.
virtual ~SpalartAllmarasDES ()=default
Destructor.
virtual bool read ()
Re-read model coefficients if they have changed.
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
virtual tmp< volScalarField > k () const
Return SGS kinetic energy.
tmp< volScalarField > nuTilda () const
virtual tmp< volScalarField > LESRegion () const
Return the LES field indicator.
virtual void correct ()
Correct nuTilda and related properties.
Public Member Functions inherited from DESModel< BasicTurbulenceModel >
DESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~DESModel ()
Destructor.
Public Member Functions inherited from DESModelBase
DESModelBase ()
Constructor.
virtual ~DESModelBase ()=default
Destructor.
ClassName ("DESModelBase")
Public Member Functions inherited from LESeddyViscosity< BasicTurbulenceModel >
LESeddyViscosity (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Construct from components.
virtual ~LESeddyViscosity ()=default
Destructor.
virtual tmp< volScalarField > epsilon () const
Return sub-grid dissipation rate.
Public Member Functions inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
eddyViscosity (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~eddyViscosity ()=default
Destructor.
virtual tmp< volScalarField > nut () const
Return the turbulence viscosity.
virtual tmp< scalarField > nut (const label patchi) const
Return the turbulence viscosity on patch.
virtual tmp< volSymmTensorField > R () const
Return the Reynolds stress tensor.
virtual void validate ()
Validate the turbulence fields after construction.
Public Member Functions inherited from linearViscousStress< LESModel< BasicTurbulenceModel > >
linearViscousStress (const word &modelName, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~linearViscousStress ()=default
Destructor.
virtual tmp< volSymmTensorField > devRhoReff () const
Return the effective stress tensor.
virtual tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U) const
Return the source term for the momentum equation.
virtual tmp< fvVectorMatrix > divDevRhoReff (const volScalarField &rho, volVectorField &U) const
Return the source term for the momentum equation.
Public Member Functions inherited from LESModel< BasicTurbulenceModel >
TypeName ("LES")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESModel, dictionary,(const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName),(alpha, rho, U, alphaRhoPhi, phi, transport, propertiesName))
LESModel (const word &type, const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName)
Construct from components.
virtual ~LESModel ()=default
Destructor.
virtual const dictionary & coeffDict () const
Const access to the coefficients dictionary.
const dimensionedScalar & kMin () const
Return the lower allowable limit for k (default: SMALL)
dimensionedScalar & kMin ()
Allow kMin to be changed.
const volScalarField & delta () const
Access function to filter width.
virtual tmp< volScalarField > nuEff () const
Return the effective viscosity.
virtual tmp< scalarField > nuEff (const label patchi) const
Return the effective viscosity on patch.
Protected Member Functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > ft2 (const volScalarField &chi) const
tmp< volScalarField > Omega (const volTensorField &gradU) const
tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1, const volScalarField &Omega, const volScalarField &dTilda) const
tmp< volScalarField > r (const volScalarField &nur, const volScalarField &Omega, const volScalarField &dTilda) const
tmp< volScalarField > fw (const volScalarField &Omega, const volScalarField &dTilda) const
tmp< volScalarField > psi (const volScalarField &chi, const volScalarField &fv1) const
virtual tmp< volScalarField > dTilda (const volScalarField &chi, const volScalarField &fv1, const volTensorField &gradU) const
Length scale.
void correctNut (const volScalarField &fv1)
virtual void correctNut ()
Protected Member Functions inherited from LESModel< BasicTurbulenceModel >
virtual void printCoeffs (const word &type)
Print model coefficients.
LESModel (const LESModel &)=delete
No copy construct.
void operator= (const LESModel &)=delete
No copy assignment.
Protected Attributes
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cs_
dimensionedScalar CDES_
dimensionedScalar ck_
Switch lowReCorrection_
dimensionedScalar Ct3_
dimensionedScalar Ct4_
dimensionedScalar fwStar_
volScalarField nuTilda_
const volScalarField & y_
Wall distance.
Protected Attributes inherited from LESeddyViscosity< BasicTurbulenceModel >
dimensionedScalar Ce_
Protected Attributes inherited from eddyViscosity< LESModel< BasicTurbulenceModel > >
volScalarField nut_
Protected Attributes inherited from LESModel< BasicTurbulenceModel >
dictionary LESDict_
LES coefficients dictionary.
Switch turbulence_
Turbulence on/off flag.
Switch printCoeffs_
Flag to print the model coeffs at run-time.
dictionary coeffDict_
Model coefficients dictionary.
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
autoPtr< Foam::LESdelta > delta_
Run-time selectable delta model.
Additional Inherited Members
Static Public Member Functions inherited from LESModel< BasicTurbulenceModel >
static autoPtr< LESModel > New (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName)
Return a reference to the selected LES model.
Detailed Description
template<class BasicTurbulenceModel>
class Foam::LESModels::SpalartAllmarasDES< BasicTurbulenceModel >
SpalartAllmarasDES DES turbulence model for incompressible and compressible flows.
Reference:
    Spalart, P. R., Jou, W. H., Strelets, M., & Allmaras, S. R. (1997).
    Comments on the feasibility of LES for wings, and on a hybrid
    RANS/LES approach.
    Advances in DNS/LES, 1, 4-8.
Including the low Reynolds number correction documented in
    Spalart, P. R., Deck, S., Shur, M.L., Squires, K.D., Strelets, M.Kh,
    Travin, A. (2006).
    A new version of detached-eddy simulation, resistant to ambiguous grid
    densities.
    Theor. Comput. Fluid Dyn., 20, 181-195.
Note
The default value of the DES constant implemented was calibrated for OpenFOAM using decaying isotropic turbulence and agrees with the value suggested in the reference publication.
Source files
SpalartAllmarasDES.H
SpalartAllmarasDES.C
Definition at line 76 of file SpalartAllmarasDES.H.
Member Typedef Documentation
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 193 of file SpalartAllmarasDES.H.
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 194 of file SpalartAllmarasDES.H.
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 195 of file SpalartAllmarasDES.H.
Constructor & Destructor Documentation
SpalartAllmarasDES (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Construct from components.
Definition at line 234 of file SpalartAllmarasDES.C.
virtual ~SpalartAllmarasDES () virtual default
Destructor.
Member Function Documentation
tmp< volScalarField > chi () const protected
Definition at line 35 of file SpalartAllmarasDES.C.
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 43 of file SpalartAllmarasDES.C.
References nu.
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 54 of file SpalartAllmarasDES.C.
tmp< volScalarField > ft2 (const volScalarField & chi) const protected
Definition at line 65 of file SpalartAllmarasDES.C.
tmp< volScalarField > Omega (const volTensorField & gradU) const protected
Definition at line 75 of file SpalartAllmarasDES.C.
References Foam::exp(), and Foam::sqr().
tmp< volScalarField > Stilda (const volScalarField & chi, const volScalarField & fv1, const volScalarField & Omega, const volScalarField & dTilda) const protected
Definition at line 85 of file SpalartAllmarasDES.C.
References Foam::mag(), Foam::skew(), and Foam::sqrt().
tmp< volScalarField > r (const volScalarField & nur, const volScalarField & Omega, const volScalarField & dTilda) const protected
Definition at line 106 of file SpalartAllmarasDES.C.
tmp< volScalarField > fw (const volScalarField & Omega, const volScalarField & dTilda) const protected
Definition at line 136 of file SpalartAllmarasDES.C.
tmp< volScalarField > psi (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 150 of file SpalartAllmarasDES.C.
tmp< volScalarField > dTilda (const volScalarField & chi, const volScalarField & fv1, const volTensorField & gradU) const protected virtual
Length scale.
Reimplemented in SpalartAllmarasIDDES< BasicTurbulenceModel >, and SpalartAllmarasDDES< BasicTurbulenceModel >.
Definition at line 197 of file SpalartAllmarasDES.C.
void correctNut (const volScalarField & fv1) protected
Definition at line 211 of file SpalartAllmarasDES.C.
void correctNut () protected virtual
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 224 of file SpalartAllmarasDES.C.
TypeName ("SpalartAllmarasDES< BasicTurbulenceModel >")
Runtime type information.
bool read () virtual
Re-read model coefficients if they have changed.
Reimplemented from LESeddyViscosity< BasicTurbulenceModel >.
Reimplemented in SpalartAllmarasIDDES< BasicTurbulenceModel >, and SpalartAllmarasDDES< BasicTurbulenceModel >.
Definition at line 410 of file SpalartAllmarasDES.C.
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
Definition at line 442 of file SpalartAllmarasDES.C.
tmp< volScalarField > k () const virtual
Return SGS kinetic energy.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 452 of file SpalartAllmarasDES.C.
tmp<volScalarField> nuTilda () const inline
Definition at line 245 of file SpalartAllmarasDES.H.
tmp< volScalarField > LESRegion () const virtual
Return the LES field indicator.
Implements DESModel< BasicTurbulenceModel >.
Definition at line 483 of file SpalartAllmarasDES.C.
void correct () virtual
Correct nuTilda and related properties.
Implements eddyViscosity< LESModel< BasicTurbulenceModel > >.
Definition at line 509 of file SpalartAllmarasDES.C.
Member Data Documentation
dimensionedScalar sigmaNut_ protected
Definition at line 99 of file SpalartAllmarasDES.H.
dimensionedScalar kappa_ protected
Definition at line 100 of file SpalartAllmarasDES.H.
dimensionedScalar Cb1_ protected
Definition at line 102 of file SpalartAllmarasDES.H.
dimensionedScalar Cb2_ protected
Definition at line 103 of file SpalartAllmarasDES.H.
dimensionedScalar Cw1_ protected
Definition at line 104 of file SpalartAllmarasDES.H.
dimensionedScalar Cw2_ protected
Definition at line 105 of file SpalartAllmarasDES.H.
dimensionedScalar Cw3_ protected
Definition at line 106 of file SpalartAllmarasDES.H.
dimensionedScalar Cv1_ protected
Definition at line 107 of file SpalartAllmarasDES.H.
dimensionedScalar Cs_ protected
Definition at line 108 of file SpalartAllmarasDES.H.
dimensionedScalar CDES_ protected
Definition at line 109 of file SpalartAllmarasDES.H.
dimensionedScalar ck_ protected
Definition at line 110 of file SpalartAllmarasDES.H.
Switch lowReCorrection_ protected
Definition at line 115 of file SpalartAllmarasDES.H.
dimensionedScalar Ct3_ protected
Definition at line 116 of file SpalartAllmarasDES.H.
dimensionedScalar Ct4_ protected
Definition at line 117 of file SpalartAllmarasDES.H.
dimensionedScalar fwStar_ protected
Definition at line 118 of file SpalartAllmarasDES.H.
volScalarField nuTilda_ protected
Definition at line 123 of file SpalartAllmarasDES.H.
const volScalarField& y_ protected
Wall distance.
Note: different to wall distance in parent RASModel which is for near-wall cells only
Definition at line 131 of file SpalartAllmarasDES.H.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/DES/SpalartAllmarasDES/SpalartAllmarasDES.H
src/TurbulenceModels/turbulenceModels/DES/SpalartAllmarasDES/SpalartAllmarasDES.C