OpenFOAM: wallNormalInfo Class Reference
wallNormalInfo Class Reference
Holds information regarding nearest wall point. Used in wall refinement.
Public Member Functions
wallNormalInfo ()
Construct null.
wallNormalInfo (const vector &normal)
Construct from normal.
wallNormalInfo (const wallNormalInfo &)
Construct as copy.
const vector & normal () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const wallNormalInfo &, const scalar, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &td)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &td)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const wallNormalInfo &neighbourInfo, const scalar tol, TrackingData &td)
Influence of different value on same face.
template<class TrackingData >
bool equal (const wallNormalInfo &, TrackingData &td) const
Same (like operator==)
bool operator== (const wallNormalInfo &) const
bool operator!= (const wallNormalInfo &) const
Friends
Ostream & operator<< (Ostream &, const wallNormalInfo &)
Istream & operator>> (Istream &, wallNormalInfo &)
Detailed Description
Holds information regarding nearest wall point. Used in wall refinement.
Source files
wallNormalInfo.H
wallNormalInfoI.H
wallNormalInfo.C
Definition at line 61 of file wallNormalInfo.H.
Constructor & Destructor Documentation
wallNormalInfo () inline
Construct null.
Definition at line 57 of file wallNormalInfoI.H.
wallNormalInfo (const vector & normal) inline
Construct from normal.
Definition at line 64 of file wallNormalInfoI.H.
wallNormalInfo (const wallNormalInfo & wpt) inline
Construct as copy.
Definition at line 71 of file wallNormalInfoI.H.
Member Function Documentation
const Foam::vector & normal () const inline
Definition at line 79 of file wallNormalInfoI.H.
Referenced by wallNormalInfo::operator!=().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 86 of file wallNormalInfoI.H.
bool sameGeometry (const polyMesh & , const wallNormalInfo & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 95 of file wallNormalInfoI.H.
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 109 of file wallNormalInfoI.H.
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 133 of file wallNormalInfoI.H.
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 122 of file wallNormalInfoI.H.
bool updateCell (const polyMesh & , const label thisCelli, const label neighbourFacei, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 146 of file wallNormalInfoI.H.
bool updateFace (const polyMesh & , const label thisFacei, const label neighbourCelli, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 162 of file wallNormalInfoI.H.
bool updateFace (const polyMesh & , const label thisFacei, const wallNormalInfo & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 178 of file wallNormalInfoI.H.
bool equal (const wallNormalInfo & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 192 of file wallNormalInfoI.H.
References update().
bool operator== (const wallNormalInfo & rhs) const inline
Definition at line 203 of file wallNormalInfoI.H.
References Foam::operator==().
bool operator!= (const wallNormalInfo & rhs) const inline
Definition at line 210 of file wallNormalInfoI.H.
References wallNormalInfo::normal().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const wallNormalInfo &) friend
Istream& operator>> (Istream & , wallNormalInfo &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/wallLayerCells/wallNormalInfo/wallNormalInfo.H
src/dynamicMesh/meshCut/wallLayerCells/wallNormalInfo/wallNormalInfoI.H