OpenFOAM: faceMDLimitedGrad< Type > Class Template Reference
faceMDLimitedGrad< Type > Class Template Reference
Gradient schemes
faceMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
Public Member Functions
TypeName ("faceMDLimited")
RunTime type information.
faceMDLimitedGrad (const fvMesh &mesh, Istream &schemeData)
Construct from mesh and schemeData.
virtual tmp< GeometricField
< typename outerProduct
< vector, Type >::type,
fvPatchField, volMesh > > calcGrad (const GeometricField< Type, fvPatchField, volMesh > &vsf, const word &name) const
Return the gradient of the given field to the gradScheme::grad.
template<>
tmp< volVectorField > calcGrad (const volScalarField &vsf, const word &name) const
template<>
tmp< volTensorField > calcGrad (const volVectorField &vsf, const word &name) const
template<>
Foam::tmp< Foam::volVectorField > calcGrad (const volScalarField &vsf, const word &name) const
template<>
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField &vvf, const word &name) const
Public Member Functions inherited from gradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, gradScheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
gradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~gradScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &, const word &name) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const GeometricField< Type, fvPatchField, volMesh > &) const
Calculate and return the grad of the given field.
tmp< GeometricField< typename
outerProduct< vector, Type >
::type, fvPatchField, volMesh > > grad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Calculate and return the grad of the given field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from gradScheme< Type >
static tmp< gradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new gradScheme created on freestore.
Detailed Description
template<class Type>
class Foam::fv::faceMDLimitedGrad< Type >
faceMDLimitedGrad gradient scheme applied to a runTime selected base gradient scheme.
The scalar limiter based on limiting the extrapolated face values between the face-neighbour cell values and is applied to the gradient in each face direction separately.
Source files
faceMDLimitedGrad.H
faceMDLimitedGrad.C
Definition at line 60 of file faceMDLimitedGrad.H.
Constructor & Destructor Documentation
faceMDLimitedGrad (const fvMesh & mesh, Istream & schemeData) inline
Construct from mesh and schemeData.
Definition at line 109 of file faceMDLimitedGrad.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
Member Function Documentation
TypeName ("faceMDLimited")
RunTime type information.
virtual tmp< GeometricField <typename outerProduct<vector, Type>::type, fvPatchField, volMesh> > calcGrad (const GeometricField< Type, fvPatchField, volMesh > & vsf, const word & name) const virtual
Return the gradient of the given field to the gradScheme::grad.
for optional caching
Implements gradScheme< Type >.
tmp< volVectorField > calcGrad (const volScalarField & vsf, const word & name) const
tmp< volTensorField > calcGrad (const volVectorField & vsf, const word & name) const
Foam::tmp< Foam::volVectorField > calcGrad (const volScalarField & vsf, const word & name) const
Definition at line 39 of file faceMDLimitedGrads.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), correctBoundaryConditions(), GeometricField< Type, PatchField, GeoMesh >::correctBoundaryConditions(), fvPatchField< Type >::coupled(), fvPatchField< Type >::fixesValue(), forAll, g, Foam::max(), mesh, Foam::min(), fvMesh::neighbour(), fvMesh::owner(), fvPatchField< Type >::patchNeighbourField(), and tmp< T >::ref().
Foam::tmp< Foam::volTensorField > calcGrad (const volVectorField & vvf, const word & name) const
Definition at line 179 of file faceMDLimitedGrads.C.
The documentation for this class was generated from the following file:
src/finiteVolume/finiteVolume/gradSchemes/limitedGradSchemes/faceMDLimitedGrad/faceMDLimitedGrad.H