OpenFOAM: ORourkeCollision< CloudType > Class Template Reference
ORourkeCollision< CloudType > Class Template Reference
Collision model by P.J. O'Rourke.
Public Member Functions
TypeName ("ORourke")
Runtime type information.
ORourkeCollision (const dictionary &dict, CloudType &cloud, const word &modelName=typeName)
Construct from dictionary.
ORourkeCollision (const ORourkeCollision< CloudType > &cm)
Construct copy.
virtual autoPtr
< StochasticCollisionModel
< CloudType > > clone () const
Construct and return a clone.
virtual ~ORourkeCollision ()
Destructor.
Public Member Functions inherited from StochasticCollisionModel< CloudType >
TypeName ("collisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, StochasticCollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
StochasticCollisionModel (CloudType &owner)
Construct null from owner.
StochasticCollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
StochasticCollisionModel (const StochasticCollisionModel< CloudType > &cm)
Construct copy.
virtual ~StochasticCollisionModel ()
Destructor.
void update (typename CloudType::parcelType::trackingData &td, const scalar dt)
Update the model.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
virtual fileName localPath () const
Output directory.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
bool getModelDict (const word &entryName, dictionary &dict) const
Retrieve dictionary, return true if set.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Protected Types
typedef CloudType::parcelType parcelType
Convenience typedef to the cloud's parcel type.
Protected Member Functions
virtual void collide (typename CloudType::parcelType::trackingData &td, const scalar dt)
Main collision routine.
virtual bool collideParcels (const scalar dt, parcelType &p1, parcelType &p2, scalar &m1, scalar &m2)
Collide parcels and return true if mass has changed.
virtual bool collideSorted (const scalar dt, parcelType &p1, parcelType &p2, scalar &m1, scalar &m2)
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const liquidMixtureProperties & liquids_
bool coalescence_
Coalescence activated?
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from StochasticCollisionModel< CloudType >
static autoPtr
< StochasticCollisionModel
< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::ORourkeCollision< CloudType >
Collision model by P.J. O'Rourke.
Definition at line 43 of file ORourkeCollision.H.
Member Typedef Documentation
typedef CloudType::parcelType parcelType protected
Convenience typedef to the cloud's parcel type.
Definition at line 54 of file ORourkeCollision.H.
Constructor & Destructor Documentation
ORourkeCollision (const dictionary & dict, CloudType & cloud, const word & modelName = typeName)
Construct from dictionary.
Definition at line 286 of file ORourkeCollision.C.
ORourkeCollision (const ORourkeCollision< CloudType > & cm)
Construct copy.
Definition at line 306 of file ORourkeCollision.C.
~ORourkeCollision () virtual
Destructor.
Definition at line 319 of file ORourkeCollision.C.
Member Function Documentation
void collide (typename CloudType::parcelType::trackingData & td, const scalar dt) protected virtual
Main collision routine.
Implements StochasticCollisionModel< CloudType >.
Reimplemented in TrajectoryCollision< CloudType >.
Definition at line 33 of file ORourkeCollision.C.
References Foam::cbrt(), forAll, i, j, mesh, p, Foam::constant::mathematical::pi(), UList< T >::size(), and Foam::Zero.
bool collideParcels (const scalar dt, parcelType & p1, parcelType & p2, scalar & m1, scalar & m2) protected virtual
Collide parcels and return true if mass has changed.
Reimplemented in TrajectoryCollision< CloudType >.
Definition at line 119 of file ORourkeCollision.C.
bool collideSorted (const scalar dt, parcelType & p1, parcelType & p2, scalar & m1, scalar & m2) protected virtual
Definition at line 164 of file ORourkeCollision.C.
TypeName ("ORourke")
Runtime type information.
virtual autoPtr<StochasticCollisionModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements StochasticCollisionModel< CloudType >.
Reimplemented in TrajectoryCollision< CloudType >.
Definition at line 126 of file ORourkeCollision.H.
Member Data Documentation
const liquidMixtureProperties& liquids_ protected
Definition at line 56 of file ORourkeCollision.H.
bool coalescence_ protected
Coalescence activated?
Definition at line 61 of file ORourkeCollision.H.
The documentation for this class was generated from the following files:
src/lagrangian/spray/submodels/StochasticCollision/ORourkeCollision/ORourkeCollision.H
src/lagrangian/spray/submodels/StochasticCollision/ORourkeCollision/ORourkeCollision.C