OpenFOAM: meshToMesh0 Class Reference
meshToMesh0 Class Reference
mesh to mesh interpolation class.
Classes
class patchFieldInterpolator
Patch-field interpolation class.
Public Types
enum order { MAP, INTERPOLATE, CELL_POINT_INTERPOLATE, CELL_VOLUME_WEIGHT }
Enumeration specifying required accuracy.
Public Member Functions
ClassName ("meshToMesh0")
meshToMesh0 (const fvMesh &fromMesh, const fvMesh &toMesh, const HashTable< word > &patchMap, const wordList &cuttingPatchNames)
Construct from the two meshes, the patch name map for the patches.
meshToMesh0 (const fvMesh &fromMesh, const fvMesh &toMesh)
Construct from the two meshes assuming there is an exact mapping.
~meshToMesh0 ()
Destructor.
const fvMesh & fromMesh () const
const fvMesh & toMesh () const
const labelList & cellAddressing () const
From toMesh cells to fromMesh cells.
scalar V () const
Overlap volume.
template<class Type , class CombineOp >
void mapField (Field< Type > &, const Field< Type > &, const labelList &adr, const CombineOp &cop) const
Map field.
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, const labelList &adr, const scalarListList &weights, const CombineOp &cop) const
Interpolate field using inverse-distance weights.
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, const labelListList &adr, const scalarListList &weights, const CombineOp &cop) const
Interpolate field using inverse-volume weights.
template<class Type , class CombineOp >
void interpolateField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, const labelList &adr, const vectorField &centres, const CombineOp &cop) const
Interpolate field using cell-point interpolation.
template<class Type , class CombineOp >
void interpolateInternalField (Field< Type > &, const GeometricField< Type, fvPatchField, volMesh > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
Interpolate internal volume field.
template<class Type , class CombineOp >
void interpolateInternalField (Field< Type > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
void interpolate (GeometricField< Type, fvPatchField, volMesh > &, const GeometricField< Type, fvPatchField, volMesh > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
Interpolate volume field.
template<class Type , class CombineOp >
void interpolate (GeometricField< Type, fvPatchField, volMesh > &, const tmp< GeometricField< Type, fvPatchField, volMesh >> &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
tmp< GeometricField< Type,
fvPatchField, volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
Interpolate volume field.
template<class Type , class CombineOp >
tmp< GeometricField< Type,
fvPatchField, volMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &, order=INTERPOLATE, const CombineOp &cop=eqOp< Type >()) const
template<class Type , class CombineOp >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &fromVf, meshToMesh0::order ord, const CombineOp &cop) const
template<class Type , class CombineOp >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &tfromVf, meshToMesh0::order ord, const CombineOp &cop) const
Detailed Description
mesh to mesh interpolation class.
Note
This class is due to be deprecated in favour of meshToMesh0New
Source files
meshToMesh0.H
meshToMesh0.C
calculateMeshToMesh0Addressing.C
calculateMeshToMesh0Weights.C
meshToMesh0Templates.C
Definition at line 62 of file meshToMesh0.H.
Member Enumeration Documentation
enum order
Enumeration specifying required accuracy.
Enumerator
MAP
INTERPOLATE
CELL_POINT_INTERPOLATE
CELL_VOLUME_WEIGHT
Definition at line 165 of file meshToMesh0.H.
Constructor & Destructor Documentation
meshToMesh0 (const fvMesh & fromMesh, const fvMesh & toMesh, const HashTable< word > & patchMap, const wordList & cuttingPatchNames)
Construct from the two meshes, the patch name map for the patches.
to be interpolated and the names of the toMesh-patches which cut the fromMesh
Definition at line 38 of file meshToMesh0.C.
References polyMesh::boundaryMesh(), Foam::endl(), HashTable< T, Key, Hash >::find(), forAll, HashTable< T, Key, Hash >::found(), i, HashTable< T, Key, Hash >::insert(), IOobject::name(), and WarningInFunction.
meshToMesh0 (const fvMesh & fromMesh, const fvMesh & toMesh)
Construct from the two meshes assuming there is an exact mapping.
between the patches
Definition at line 109 of file meshToMesh0.C.
~meshToMesh0 ()
Destructor.
Definition at line 189 of file meshToMesh0.C.
Member Function Documentation
ClassName ("meshToMesh0")
const fvMesh& fromMesh () const inline
Definition at line 265 of file meshToMesh0.H.
Referenced by Foam::MapConsistentVolFields(), and Foam::MapVolFields().
const fvMesh& toMesh () const inline
Definition at line 270 of file meshToMesh0.H.
Referenced by Foam::MapConsistentVolFields(), Foam::MapLagrangianFields(), and Foam::MapVolFields().
const labelList& cellAddressing () const inline
From toMesh cells to fromMesh cells.
Definition at line 278 of file meshToMesh0.H.
scalar V () const inline
Overlap volume.
Definition at line 286 of file meshToMesh0.H.
void mapField (Field< Type > & toF, const Field< Type > & fromVf, const labelList & adr, const CombineOp & cop) const
Map field.
Definition at line 31 of file meshToMesh0Templates.C.
References forAll.
void interpolateField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, const labelList & adr, const scalarListList & weights, const CombineOp & cop) const
Interpolate field using inverse-distance weights.
Definition at line 81 of file meshToMesh0Templates.C.
void interpolateField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, const labelListList & adr, const scalarListList & weights, const CombineOp & cop) const
Interpolate field using inverse-volume weights.
Definition at line 54 of file meshToMesh0Templates.C.
void interpolateField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, const labelList & adr, const vectorField & centres, const CombineOp & cop) const
Interpolate field using cell-point interpolation.
Definition at line 116 of file meshToMesh0Templates.C.
void interpolateInternalField (Field< Type > & toF, const GeometricField< Type, fvPatchField, volMesh > & fromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Interpolate internal volume field.
Definition at line 147 of file meshToMesh0Templates.C.
void interpolateInternalField (Field< Type > & toF, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 228 of file meshToMesh0Templates.C.
void interpolate (GeometricField< Type, fvPatchField, volMesh > & toVf, const GeometricField< Type, fvPatchField, volMesh > & fromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Interpolate volume field.
Definition at line 242 of file meshToMesh0Templates.C.
Referenced by Foam::MapConsistentVolFields(), and Foam::MapVolFields().
void interpolate (GeometricField< Type, fvPatchField, volMesh > & toVf, const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfromVf, meshToMesh0::order ord = INTERPOLATE, const CombineOp & cop = eqOp<Type>()) const
Definition at line 341 of file meshToMesh0Templates.C.
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & , order = INTERPOLATE, const CombineOp & cop = eqOp< Type >()) const
Interpolate volume field.
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & , order = INTERPOLATE, const CombineOp & cop = eqOp< Type >()) const
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolate (const GeometricField< Type, fvPatchField, volMesh > & fromVf, meshToMesh0::order ord, const CombineOp & cop) const
Definition at line 356 of file meshToMesh0Templates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tfromVf, meshToMesh0::order ord, const CombineOp & cop) const
Definition at line 428 of file meshToMesh0Templates.C.
The documentation for this class was generated from the following files:
src/sampling/meshToMesh0/meshToMesh0.H
src/sampling/meshToMesh0/calculateMeshToMesh0Addressing.C
src/sampling/meshToMesh0/calculateMeshToMesh0Weights.C
src/sampling/meshToMesh0/meshToMesh0.C
src/sampling/meshToMesh0/meshToMesh0Templates.C