OpenFOAM: mapDistribute::transform Class Reference
mapDistribute::transform Class Reference
Default transformation behaviour.
Public Member Functions
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< Type > &fld) const
template<class Type >
void operator() (const vectorTensorTransform &vt, const bool forward, List< List< Type >> &flds) const
template<class Type >
void operator() (const coupledPolyPatch &cpp, UList< Type > &fld) const
Transform patch-based field.
template<class Type , template< class > class Container>
void operator() (const coupledPolyPatch &cpp, Container< Type > &map) const
Transform sparse field.
template<>
void operator() (const vectorTensorTransform &, const bool, List< label > &) const
template<>
void operator() (const coupledPolyPatch &, UList< label > &) const
template<>
void operator() (const coupledPolyPatch &, Map< label > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< label > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, UList< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, Map< scalar > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< scalar > &) const
template<>
void operator() (const vectorTensorTransform &, const bool, List< bool > &) const
template<>
void operator() (const coupledPolyPatch &, UList< bool > &) const
template<>
void operator() (const coupledPolyPatch &, Map< bool > &) const
template<>
void operator() (const coupledPolyPatch &, EdgeMap< bool > &) const
Detailed Description
Default transformation behaviour.
Definition at line 216 of file mapDistribute.H.
Member Function Documentation
void operator() (const vectorTensorTransform & vt, const bool forward, List< Type > & fld) const inline
Definition at line 222 of file mapDistribute.H.
Referenced by mapDistribute::transform::operator()().
void operator() (const vectorTensorTransform & vt, const bool forward, List< List< Type >> & flds) const inline
Definition at line 234 of file mapDistribute.H.
References fld, and mapDistribute::transform::operator()().
void operator() (const coupledPolyPatch & cpp, UList< Type > & fld) const inline
Transform patch-based field.
Definition at line 250 of file mapDistribute.H.
References coupledPolyPatch::forwardT(), coupledPolyPatch::parallel(), and Foam::transformList().
void operator() (const coupledPolyPatch & cpp, Container< Type > & map) const inline
Transform sparse field.
Definition at line 262 of file mapDistribute.H.
References fld.
void operator() (const vectorTensorTransform & , const bool , List< label > &) const
Definition at line 38 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , UList< label > &) const
Definition at line 46 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , Map< label > &) const
Definition at line 53 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , EdgeMap< label > &) const
Definition at line 60 of file mapDistribute.C.
void operator() (const vectorTensorTransform & , const bool , List< scalar > &) const
Definition at line 68 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , UList< scalar > &) const
Definition at line 76 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , Map< scalar > &) const
Definition at line 83 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , EdgeMap< scalar > &) const
Definition at line 90 of file mapDistribute.C.
void operator() (const vectorTensorTransform & , const bool , List< bool > &) const
Definition at line 98 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , UList< bool > &) const
Definition at line 106 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , Map< bool > &) const
Definition at line 113 of file mapDistribute.C.
void operator() (const coupledPolyPatch & , EdgeMap< bool > &) const
Definition at line 120 of file mapDistribute.C.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.C