OpenFOAM: BinaryCollisionModel< CloudType > Class Template Reference
BinaryCollisionModel< CloudType > Class Template Reference abstract
Templated DSMC particle collision class.
Public Member Functions
TypeName ("BinaryCollisionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, BinaryCollisionModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
BinaryCollisionModel (CloudType &owner)
Construct null from owner.
BinaryCollisionModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from components.
virtual ~BinaryCollisionModel ()
Destructor.
const CloudType & owner () const
Return the owner cloud object.
CloudType & owner ()
Return non-const access to the owner cloud object.
const dictionary & dict () const
Return the dictionary.
const dictionary & coeffDict () const
Return the coefficients dictionary.
virtual bool active () const =0
Flag to indicate whether model activates collision model.
virtual scalar sigmaTcR (const typename CloudType::parcelType &pP, const typename CloudType::parcelType &pQ) const =0
Return the collision cross section * relative velocity product.
virtual void collide (typename CloudType::parcelType &pP, typename CloudType::parcelType &pQ)=0
Apply collision.
Static Public Member Functions
static autoPtr
< BinaryCollisionModel
< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Detailed Description
template<class CloudType>
class Foam::BinaryCollisionModel< CloudType >
Templated DSMC particle collision class.
Source files
BinaryCollisionModel.H
BinaryCollisionModel.C
BinaryCollisionModelNew.C
Definition at line 54 of file DSMCCloud.H.
Constructor & Destructor Documentation
BinaryCollisionModel (CloudType & owner)
Construct null from owner.
Definition at line 26 of file BinaryCollisionModel.C.
BinaryCollisionModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from components.
Definition at line 36 of file BinaryCollisionModel.C.
~BinaryCollisionModel () virtual
Destructor.
Definition at line 51 of file BinaryCollisionModel.C.
Member Function Documentation
TypeName ("BinaryCollisionModel< CloudType >")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , BinaryCollisionModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::BinaryCollisionModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 29 of file BinaryCollisionModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
const CloudType & owner () const
Return the owner cloud object.
Definition at line 59 of file BinaryCollisionModel.C.
CloudType & owner ()
Return non-const access to the owner cloud object.
Definition at line 67 of file BinaryCollisionModel.C.
const Foam::dictionary & dict () const
Return the dictionary.
Definition at line 75 of file BinaryCollisionModel.C.
const Foam::dictionary & coeffDict () const
Return the coefficients dictionary.
Definition at line 83 of file BinaryCollisionModel.C.
virtual bool active () const pure virtual
Flag to indicate whether model activates collision model.
Implemented in LarsenBorgnakkeVariableHardSphere< CloudType >, VariableHardSphere< CloudType >, and NoBinaryCollision< CloudType >.
virtual scalar sigmaTcR (const typename CloudType::parcelType & pP, const typename CloudType::parcelType & pQ) const pure virtual
Return the collision cross section * relative velocity product.
Implemented in LarsenBorgnakkeVariableHardSphere< CloudType >, VariableHardSphere< CloudType >, and NoBinaryCollision< CloudType >.
virtual void collide (typename CloudType::parcelType & pP, typename CloudType::parcelType & pQ) pure virtual
Apply collision.
Implemented in LarsenBorgnakkeVariableHardSphere< CloudType >, VariableHardSphere< CloudType >, and NoBinaryCollision< CloudType >.
The documentation for this class was generated from the following files:
src/lagrangian/DSMC/clouds/Templates/DSMCCloud/DSMCCloud.H
src/lagrangian/DSMC/submodels/BinaryCollisionModel/BinaryCollisionModel/BinaryCollisionModel.H
src/lagrangian/DSMC/submodels/BinaryCollisionModel/BinaryCollisionModel/BinaryCollisionModel.C
src/lagrangian/DSMC/submodels/BinaryCollisionModel/BinaryCollisionModel/BinaryCollisionModelNew.C