OpenFOAM: parseDriver Class Reference
parseDriver Class Reference
Driver for generic primitive field expressions.
Public Member Functions
ClassName ("fieldExpr::driver")
parseDriver ()
Construct null - uses size = 1.
parseDriver (const label len)
Construct with specified size.
parseDriver (const label len, const dictionary &dict)
Construct for specified size with given dictionary.
parseDriver (const label len, const parseDriver &driver_)
Construct for specified size with copy of driver context.
virtual ~parseDriver ()=default
Destructor.
virtual label size () const
The underlying field size for the expression.
virtual label pointSize () const
The underlying point field size for the expression.
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)
Execute the parser.
template<class Type >
void setResult (Field< Type > *ptr, bool pointVal=false)
Set result.
template<class Type >
tmp< Field< Type > > getField (const word &fieldName) const
Return named field (variable) if available.
tmp< scalarField > field_rand (label seed=0, bool gaussian=false) const
A uniform random field.
tmp< scalarField > field_randGaussian (label seed=0) const
A Gaussian random field.
Public Member Functions inherited from genericRagelLemonDriver
genericRagelLemonDriver ()
Construct null.
genericRagelLemonDriver (const genericRagelLemonDriver &rhs)=default
Copy construct.
genericRagelLemonDriver (genericRagelLemonDriver &&rhs)=default
Move construct.
virtual ~genericRagelLemonDriver ()=default
Destructor.
void clear ()
Reset references.
const std::string & content () const
Get reference to the input buffer content.
void content (const std::string &s, size_t pos=0, size_t len=std::string::npos)
Set reference to the input buffer content, which acts like a std::string_view.
std::string::const_iterator cbegin () const
Iterator to begin of content (sub)string.
std::string::const_iterator cend () const
Iterator to end of content (sub)string.
size_t parsePosition () const
The relative parse position with the content (sub)string.
size_t & parsePosition ()
The relative parse position with the content (sub)string.
Ostream & printBuffer (Ostream &os) const
Output the input buffer string content.
void reportFatal (const std::string &msg) const
Report FatalError.
void reportFatal (const std::string &msg, size_t pos) const
Report FatalError at parser position.
Public Member Functions inherited from exprDriver
TypeName ("exprDriver")
Runtime type information.
exprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
exprDriver (const exprDriver &)
Copy construct.
exprDriver (const dictionary &dict)
Construct from a dictionary.
virtual ~exprDriver ()=default
Destructor.
const dictionary & dict () const
The dictionary with all input data/specification.
virtual const exprResult & result () const
Const access to expression result.
virtual exprResult & result ()
Non-const access to expression result.
void clearResult ()
Clear the result.
template<class Type >
tmp< Field< Type > > getResult (bool isPointVal=false)
Return the expression result as a tmp field.
virtual word getResultType () const
The result type as word - same as result().valueType()
int stashedTokenId () const
Get "look-behind" parsing context (internal bookkeeping)
int resetStashedTokenId (int tokenId=0) const
Reset "look-behind" parsing context (mutable operation)
void setDebugging (bool scannerDebug, bool parserDebug)
Set the scanner/parser debug.
void setDebugging (const exprDriver &rhs)
Set the scanner/parser debug to match the input.
void setSearchBehaviour (bool cacheReadFields, bool searchInMemory, bool searchFiles)
Set search behaviour.
void setSearchBehaviour (const exprDriver &rhs)
Set search behaviour to be identical to rhs.
bool debugScanner () const
Read access to scanner debug.
bool debugParser () const
Read access to parser debug.
bool cacheReadFields () const
bool searchInMemory () const
bool searchFiles () const
bool prevIterIsOldTime () const
virtual void clearVariables ()
Clear temporary variables and resets from expression strings.
virtual bool hasVariable (const word &name) const
True if named variable exists.
virtual const exprResult & variable (const word &name) const
Return const-access to the named variable.
void addVariables (const expressions::exprString &expr, bool clear=true)
Add/set string expressions for variables.
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
Add/set string expressions for variables.
template<class T >
void addUniformVariable (const word &name, const T &val)
Add a uniform variable from an outside caller.
template<class T >
bool isLocalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a local variable.
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return the field.
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return a single value.
void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
Evaluate an expression on a remote and save as the specified named variable.
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
Return a new field with the size()
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
Return a new field with the pointSize()
expressions::exprString readExpression (const word &name)
Read an expression string (with the current dictionary) and do substitutions.
virtual bool readDict (const dictionary &dict)
Read variables, tables etc.
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Read "variables" and assigns to the list of expression strings.
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
Write "variables".
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Protected Member Functions
parseDriver (const parseDriver &)=delete
void operator= (const parseDriver &)=delete
Protected Member Functions inherited from exprDriver
virtual exprResult & variable (const word &name)
Non-const access to the named variable (sub-classes only)
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Fill a random field.
virtual bool update ()
Update things.
virtual void updateSpecialVariables (bool force=false)
Examine current variable values and update stored variables.
virtual exprResult getRemoteResult (const exprDriver &other) const
Get the result from another driver.
void operator= (const exprDriver &)=delete
No copy assignment.
Protected Attributes
label size_
The field size.
Protected Attributes inherited from genericRagelLemonDriver
std::reference_wrapper< const
std::string > content_
Reference to the input string.
size_t start_
Start position within input string.
size_t length_
Length of input (sub)string.
size_t position_
The last known parser position.
Protected Attributes inherited from exprDriver
const dictionary & dict_
The dictionary with all input data/specification.
exprResult result_
The result.
List< expressions::exprString > variableStrings_
Variable definitions, as read from a dictionary.
HashTable< exprResult > variables_
The variables table.
int stashedTokenId_
Internal bookkeeping as "look-behind" parsing context.
bool debugScanner_
Request debugging for scanner.
bool debugParser_
Request debugging for parser.
bool allowShadowing_
Allow variable names to mask field names.
bool prevIterIsOldTime_
Use value of previous iteration when oldTime is requested.
bool cacheReadFields_
Keep fields read from disc in memory.
bool searchInMemory_
Search in registry before looking on disk.
bool searchFiles_
Search on disk (eg, for a standalone application)
Additional Inherited Members
Public Types inherited from genericRagelLemonDriver
typedef size_t location_type
Type for linear addressing within parse content.
Static Public Member Functions inherited from exprDriver
static expressions::exprString readExpression (const word &name, const dictionary &dict)
Read an expression string and do substitutions.
static List
< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Read the list of variable strings.
Static Protected Member Functions inherited from exprDriver
template<typename TableType >
static bool readTable (const word &name, const dictionary &dict, HashTable< TableType > &tbl, bool clear=true)
Read an interpolation table.
template<class TableType >
static void writeTable (Ostream &os, const word &name, const HashTable< TableType > &tbl)
Write an interpolation table.
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
The (global) weighted average of a field, with stabilisation.
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
The (global) weighted sum (integral) of a field.
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
Return the location of the min value.
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Return the location of the max value.
Detailed Description
Driver for generic primitive field expressions.
In addition to the standard mathematical functions, operations and logical and relational operations, the volume expression support the following driver-specific functions:
Functions
Function Description Number of arguments
rand Random field 0/1
Note
Use namespace debug switch fieldExpr for scanner (2), parser (4)
Source files
fieldExprDriver.H
fieldExprDriver.C
fieldExprDriverFields.C
fieldExprDriverTemplates.C
Definition at line 78 of file fieldExprDriver.H.
Constructor & Destructor Documentation
parseDriver (const parseDriver &) protected delete
parseDriver ()
Construct null - uses size = 1.
Definition at line 45 of file fieldExprDriver.C.
parseDriver (const label len) explicit
Construct with specified size.
Definition at line 52 of file fieldExprDriver.C.
parseDriver (const label len, const dictionary & dict)
Construct for specified size with given dictionary.
Definition at line 63 of file fieldExprDriver.C.
parseDriver (const label len, const parseDriver & driver_)
Construct for specified size with copy of driver context.
Definition at line 75 of file fieldExprDriver.C.
virtual ~parseDriver () virtual default
Destructor.
Member Function Documentation
void operator= (const parseDriver &) protected delete
ClassName ("fieldExpr::driver")
virtual label size () const inline virtual
The underlying field size for the expression.
Reimplemented from exprDriver.
Definition at line 140 of file fieldExprDriver.H.
Referenced by parseDriver::field_rand(), and parseDriver::getField().
virtual label pointSize () const inline virtual
The underlying point field size for the expression.
Reimplemented from exprDriver.
Definition at line 148 of file fieldExprDriver.H.
References exprDriver::result(), and exprResult::setResult().
Referenced by parseDriver::getField().
unsigned parse (const std::string & expr, size_t pos = 0, size_t len = std::string::npos) virtual
Execute the parser.
The return value currently has no meaning.
Implements exprDriver.
Definition at line 89 of file fieldExprDriver.C.
Referenced by Foam::stringOps::evaluate().
void setResult (Field< Type > * ptr, bool pointVal = false) inline
Set result.
Definition at line 180 of file fieldExprDriver.H.
tmp<Field<Type> > getField (const word & fieldName) const
Return named field (variable) if available.
Foam::tmp< Foam::scalarField > field_rand (label seed = 0, bool gaussian = false) const
A uniform random field.
Definition at line 27 of file fieldExprDriverFields.C.
References exprDriver::fill_random(), tmp< T >::New(), and parseDriver::size().
tmp<scalarField> field_randGaussian (label seed = 0) const inline
A Gaussian random field.
Definition at line 206 of file fieldExprDriver.H.
Member Data Documentation
label size_ protected
The field size.
Definition at line 90 of file fieldExprDriver.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/expressions/fields/fieldExprDriver.H
src/OpenFOAM/expressions/fields/fieldExprDriver.C
src/OpenFOAM/expressions/fields/fieldExprDriverFields.C