OpenFOAM: wordRe Class Reference
wordRe Class Reference
A wordRe is a Foam::word, but can contain a regular expression for matching words or strings.
Public Types
enum compOption {
LITERAL = 0, REGEX = 1, ICASE = 2, NOCASE = 2,
DETECT = 4, UNKNOWN = 4, REGEX_ICASE = (REGEX|ICASE), DETECT_ICASE = (DETECT|ICASE)
}
Enumeration with compile options.
Public Member Functions
wordRe ()
Construct null.
wordRe (const wordRe &str)
Copy construct.
wordRe (wordRe &&str)
Move construct.
wordRe (const keyType &str)
Construct from keyType, using its compile information.
wordRe (const char *str)
Copy from character array, treat as a literal.
wordRe (const std::string &str)
Copy from std::string, treat as a literal.
wordRe (const string &str)
Copy from string, treat as a literal.
wordRe (const word &str)
Copy from word, treat as a literal.
wordRe (const keyType &str, const compOption opt)
Copy from keyType, use specified compile option.
wordRe (const char *str, const compOption opt)
Copy from character array, use specified compile option.
wordRe (const std::string &str, const compOption opt)
Copy from std::string, use specified compile option.
wordRe (const string &str, const compOption opt)
Copy from string, use specified compile option.
wordRe (const word &str, const compOption opt)
Copy from word, use specified compile option.
wordRe (Istream &is)
Construct from Istream.
bool isLiteral () const
The wordRe is treated as literal string, not as pattern.
bool isPattern () const
The wordRe is treated as a pattern, not as literal string.
bool compile ()
Compile the regular expression.
bool compile (const compOption opt)
Possibly compile the regular expression, with greater control.
void uncompile (bool adjust=false)
Make wordRe a literal again, instead of a regular expression.
void set (const std::string &str, const compOption opt=DETECT)
Copy string, auto-test for regular expression or other options.
void set (const char *str, const compOption opt=DETECT)
Copy string, auto-test for regular expression or other options.
void clear ()
Clear string and regular expression.
void swap (wordRe &str)
Swap contents. Self-swapping is a no-op.
bool match (const std::string &text, bool literal=false) const
Smart match as regular expression or as a string.
string quotemeta () const
Return a string with quoted meta-characters.
Ostream & info (Ostream &os) const
Output some basic info.
bool operator() (const std::string &text) const
Perform smart match on text, as per match()
void operator= (const wordRe &str)
Copy assignment, retaining type (literal or regex)
void operator= (const word &str)
Copy word, never a regular expression.
void operator= (const keyType &str)
Copy keyType and its type (literal or regex)
void operator= (const string &str)
Copy string, auto-test for regular expression.
void operator= (const std::string &str)
Copy string, auto-test for regular expression.
void operator= (const char *str)
Copy string, auto-test for regular expression.
void operator= (wordRe &&str)
Move assignment.
Public Member Functions inherited from word
word ()=default
Construct null.
word (const word &)=default
Copy construct.
word (word &&w)=default
Move construct.
word (const string &s, bool doStrip=true)
Copy construct from Foam::string.
word (string &&s, bool doStrip=true)
Move construct from Foam::string.
word (const std::string &s, bool doStrip=true)
Copy construct from std::string.
word (std::string &&s, bool doStrip=true)
Move construct from std::string.
word (const char *s, bool doStrip=true)
Copy from character array.
word (const char *s, size_type len, bool doStrip)
Copy from buffer for a maximum number of characters.
word (Istream &is)
Construct from Istream.
void stripInvalid ()
Strip invalid characters from this word.
word lessExt () const
Return word without extension (part before last .)
word ext () const
Return file name extension (part after last .)
word & ext (const word &ending)
Append a '.' and the ending, and return the object.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
word & operator= (const word &s)
Copy assignment, no character validation required.
word & operator= (word &&s)
Move assignment, no character validation required.
word & operator= (const string &s)
Copy assignment from Foam::string, stripping invalid characters.
word & operator= (string &&s)
Move assignment from Foam::string, stripping invalid characters.
word & operator= (const std::string &s)
Copy assignment from std::string, stripping invalid characters.
word & operator= (std::string &&s)
Move assignment from std::string, stripping invalid characters.
word & operator= (const char *s)
Copy, stripping invalid characters.
template<class PrimitiveType >
Foam::word printf (const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
Foam::word printf (const std::string &fmt, const PrimitiveType &val)
Public Member Functions inherited from string
string ()=default
Construct null.
string (const std::string &str)
Copy construct from std::string.
string (std::string &&str)
Move construct from std::string.
string (const char *str)
Construct as copy of character array.
string (const char *str, const size_type len)
Construct as copy with a maximum number of characters.
string (const char c)
Construct from a single character.
string (const size_type len, const char c)
Construct fill copies of a single character.
string (Istream &is)
Construct from Istream.
bool match (const std::string &text) const
Test for equality.
string & replace (const std::string &s1, const std::string &s2, size_type pos=0)
Replace first occurrence of sub-string s1 with s2, beginning at pos.
string & replaceAll (const std::string &s1, const std::string &s2, size_type pos=0)
Replace all occurrences of sub-string s1 with s2, beginning at pos in the string.
string & expand (const bool allowEmpty=false)
Inplace expand initial tags, tildes, and all occurrences of environment variables as per stringOps::expand.
bool removeRepeated (const char character)
Remove repeated characters.
bool removeStart (const std::string &text)
Remove the given text from the start of the string.
bool removeStart (const char c)
Remove leading character, unless string is a single character.
bool removeEnd (const std::string &text)
Remove the given text from the end of the string.
bool removeEnd (const char c)
Remove trailing character, unless string is a single character.
void swap (std::string &str)
Swap contents. Self-swapping is a no-op.
bool operator() (const std::string &text) const
Test for equality. Allows use as a predicate.
bool starts_with (const std::string &s) const
True if string starts with the given prefix (cf. C++20)
bool starts_with (const char c) const
True if string starts with the given character (cf. C++20)
bool ends_with (const std::string &s) const
True if string ends with the given suffix (cf. C++20)
bool ends_with (const char c) const
True if string ends with the given character (cf. C++20)
size_type count (const char c) const
Count the number of occurrences of the specified character in the string.
bool startsWith (const std::string &s) const
Deprecated(2019-11)
bool endsWith (const std::string &s) const
Deprecated(2019-11)
bool removeTrailing (const char c)
Deprecated(2019-11)
template<class String >
Foam::string quotemeta (const std::string &str, const char quote)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
template<class PrimitiveType >
std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
Static Public Member Functions
static bool meta (char c)
Is this a meta character?
static bool valid (char c)
Is this character valid for a wordRe?
static bool isPattern (const std::string &str)
Test string for regular expression meta characters.
Static Public Member Functions inherited from word
template<class PrimitiveType >
static word printf (const char *fmt, const PrimitiveType &val)
Use a printf-style formatter for a primitive.
template<class PrimitiveType >
static word printf (const std::string &fmt, const PrimitiveType &val)
Use a printf-style formatter for a primitive.
static bool valid (char c)
Is this character valid for a word?
static word validate (const std::string &s, const bool prefix=false)
Construct validated word (no invalid characters).
static word validate (const char *first, const char *last, const bool prefix=false)
Construct validated word (no invalid characters) from a sequence of characters in the range [first,last),.
Static Public Member Functions inherited from string
template<class String >
static bool valid (const std::string &str)
Does the string contain valid characters only?
template<class String >
static bool meta (const std::string &str, const char quote='\\')
Does this string contain meta-characters?
template<class String >
static bool stripInvalid (std::string &str)
Strip invalid characters from the given string.
template<class String >
static String validate (const std::string &str)
Return a valid String from the given string.
template<class String >
static string quotemeta (const std::string &str, const char quote= '\\')
Return a String with quoted meta-characters from the given string.
Static Public Attributes
static const wordRe null
An empty wordRe.
Static Public Attributes inherited from word
static const char *const typeName = "word"
The typeName.
static int debug
Debugging.
static const word null
An empty word.
Static Public Attributes inherited from string
static const char *const typeName = "string"
The type name "string".
static int debug
The debug flag.
static const string null
An empty string.
Additional Inherited Members
Protected Member Functions inherited from string
std::string::size_type find_ext () const
Find position of a file extension dot, return npos on failure.
word ext () const
Return file name extension (part after last .)
bool ext (const word &ending)
Append a '.' and the ending.
bool hasPath () const
Return true if it contains a '/' character.
bool hasExt () const
Return true if it has an extension or simply ends with a '.'.
bool hasExt (const word &ending) const
Return true if the extension is the same as the given ending.
bool hasExt (const wordRe &ending) const
Return true if the extension matches the given ending.
bool removeExt ()
Remove extension, returning true if string changed.
bool removePath ()
Remove leading path, returning true if string changed.
Static Protected Member Functions inherited from string
static std::string::size_type find_ext (const std::string &str)
Find position of a file extension dot, return npos on failure.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const char *fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
template<class PrimitiveType >
static std::string::size_type string_printf (std::string &output, const std::string &fmt, const PrimitiveType &val)
A printf-style formatter for a primitive.
Detailed Description
A wordRe is a Foam::word, but can contain a regular expression for matching words or strings.
By default the constructors will generally preserve the argument as a string literal and the assignment operators will use the wordRe::DETECT compOption to scan the string for regular expression meta characters and/or invalid word characters and react accordingly.
The exceptions are when constructing/assigning from another Foam::wordRe (preserve the same type) or from a Foam::word (always literal).
Note
If the string contents are changed - eg, by the operator+=() or by string::replace(), etc - it will be necessary to use compile() to synchronize the regular expression.
Source files
wordRe.H
wordRe.C
Definition at line 68 of file wordRe.H.
Member Enumeration Documentation
enum compOption
Enumeration with compile options.
Note that 'REGEX' is implicit if 'ICASE' is specified alone.
Enumerator
LITERAL
String literal.
REGEX
Regular expression.
ICASE
Ignore case in regular expression.
NOCASE
Deprecated:
(2018-04) Alias for ICASE
DETECT
Detect if the string contains meta-characters.
UNKNOWN
Unknown content.
REGEX_ICASE
Combined REGEX and ICASE.
DETECT_ICASE
Combined DETECT and ICASE.
Definition at line 97 of file wordRe.H.
Constructor & Destructor Documentation
wordRe () inline
Construct null.
Definition at line 44 of file wordReI.H.
wordRe (const wordRe & str) inline
Copy construct.
Definition at line 51 of file wordReI.H.
wordRe (wordRe && str) inline
Move construct.
Definition at line 63 of file wordReI.H.
References wordRe::compile().
wordRe (const keyType & str) inline explicit
Construct from keyType, using its compile information.
Definition at line 70 of file wordReI.H.
wordRe (const char * str) inline explicit
Copy from character array, treat as a literal.
Definition at line 82 of file wordReI.H.
References wordRe::compile().
wordRe (const std::string & str) inline explicit
Copy from std::string, treat as a literal.
Definition at line 89 of file wordReI.H.
wordRe (const string & str) inline explicit
Copy from string, treat as a literal.
Definition at line 96 of file wordReI.H.
wordRe (const word & str) inline explicit
Copy from word, treat as a literal.
Definition at line 103 of file wordReI.H.
wordRe (const keyType & str, const compOption opt) inline
Copy from keyType, use specified compile option.
Definition at line 110 of file wordReI.H.
wordRe (const char * str, const compOption opt) inline
Copy from character array, use specified compile option.
Definition at line 122 of file wordReI.H.
References wordRe::compile().
wordRe (const std::string & str, const compOption opt) inline
Copy from std::string, use specified compile option.
Definition at line 130 of file wordReI.H.
wordRe (const string & str, const compOption opt) inline
Copy from string, use specified compile option.
Definition at line 138 of file wordReI.H.
wordRe (const word & str, const compOption opt) inline
Copy from word, use specified compile option.
Definition at line 146 of file wordReI.H.
wordRe (Istream & is) explicit
Construct from Istream.
Words are treated as literals, strings with an auto-test
Definition at line 33 of file wordRe.C.
Member Function Documentation
bool meta (char c) inline static
Is this a meta character?
Definition at line 24 of file wordReI.H.
bool valid (char c) inline static
Is this character valid for a wordRe?
This is largely identical with what word accepts, but also permit brace-brackets, which are valid for some regexs.
Definition at line 30 of file wordReI.H.
References regExpPosix::meta().
bool isPattern (const std::string & str) inline static
Test string for regular expression meta characters.
Definition at line 36 of file wordReI.H.
References keyType::valid().
bool isLiteral () const inline
The wordRe is treated as literal string, not as pattern.
Definition at line 156 of file wordReI.H.
bool isPattern () const inline
The wordRe is treated as a pattern, not as literal string.
Definition at line 162 of file wordReI.H.
bool compile () inline
Compile the regular expression.
Definition at line 199 of file wordReI.H.
Referenced by wordRe::wordRe().
bool compile (const compOption opt) inline
Possibly compile the regular expression, with greater control.
Definition at line 168 of file wordReI.H.
void uncompile (bool adjust = false) inline
Make wordRe a literal again, instead of a regular expression.
Optionally strip invalid word characters.
Definition at line 205 of file wordReI.H.
void set (const std::string & str, const compOption opt = DETECT) inline
Copy string, auto-test for regular expression or other options.
Definition at line 239 of file wordReI.H.
void set (const char * str, const compOption opt = DETECT) inline
Copy string, auto-test for regular expression or other options.
Definition at line 246 of file wordReI.H.
References Foam::FieldOps::assign().
void clear () inline
Clear string and regular expression.
Definition at line 215 of file wordReI.H.
void swap (wordRe & str) inline
Swap contents. Self-swapping is a no-op.
Definition at line 253 of file wordReI.H.
References Foam::FieldOps::assign().
bool match (const std::string & text, bool literal = false) const inline
Smart match as regular expression or as a string.
Optionally force a literal match only
Definition at line 222 of file wordReI.H.
References clear().
Foam::string quotemeta () const inline
Return a string with quoted meta-characters.
Definition at line 233 of file wordReI.H.
Foam::Ostream & info (Ostream & os) const
Output some basic info.
Definition at line 44 of file wordRe.C.
bool operator() (const std::string & text) const inline
Perform smart match on text, as per match()
Allows use as a predicate.
Definition at line 267 of file wordReI.H.
void operator= (const wordRe & str) inline
Copy assignment, retaining type (literal or regex)
Self-assignment is a no-op.
Definition at line 273 of file wordReI.H.
References Foam::stringOps::match().
void operator= (const word & str) inline
Copy word, never a regular expression.
Definition at line 292 of file wordReI.H.
void operator= (const keyType & str) inline
Copy keyType and its type (literal or regex)
Always case sensitive
Definition at line 299 of file wordReI.H.
References Foam::FieldOps::assign().
void operator= (const string & str) inline
Copy string, auto-test for regular expression.
Always case sensitive
Definition at line 313 of file wordReI.H.
void operator= (const std::string & str) inline
Copy string, auto-test for regular expression.
Always case sensitive
Definition at line 320 of file wordReI.H.
References Foam::FieldOps::assign().
void operator= (const char * str) inline
Copy string, auto-test for regular expression.
Always case sensitive
Definition at line 327 of file wordReI.H.
References Foam::FieldOps::assign().
void operator= (wordRe && str) inline
Move assignment.
Self-assignment is a no-op.
Definition at line 334 of file wordReI.H.
References Foam::FieldOps::assign().
Member Data Documentation
const Foam::wordRe null static
An empty wordRe.
Definition at line 87 of file wordRe.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/strings/wordRe/wordRe.H
src/OpenFOAM/primitives/strings/wordRe/wordRe.C
src/OpenFOAM/primitives/strings/wordRe/wordReI.H