OpenFOAM: IListStreamAllocator Class Reference
IListStreamAllocator Class Reference
An stream/stream-buffer input allocator with List storage.
Public Member Functions
void clearStorage ()
Clear storage.
void swap (List< char > &list)
Transfer contents to other List.
Public Member Functions inherited from UIListStreamAllocator
const UList< char > list () const
Const UList access to the input characters (shallow copy).
UList< char > list ()
Non-const UList access to the input characters (shallow copy).
label size () const
The list size.
std::streampos tellg () const
Position of the get buffer.
void rewind ()
Move to buffer start, clear errors.
Protected Member Functions
IListStreamAllocator ()
Construct empty.
IListStreamAllocator (List< char > &&buffer)
Move construct from List.
template<int SizeMin>
IListStreamAllocator (DynamicList< char, SizeMin > &&buffer)
Move construct from DynamicList.
void reset_gbuffer ()
Convenience method to address the underlying List storage.
Protected Member Functions inherited from UIListStreamAllocator
UIListStreamAllocator (char *buffer, size_t nbytes)
Construct for character array and number of bytes.
void reset (char *buffer, size_t nbytes)
Reset buffer pointers.
void printBufInfo (Ostream &os) const
Additional Inherited Members
Protected Types inherited from UIListStreamAllocator
typedef std::istream stream_type
Protected Attributes inherited from UIListStreamAllocator
memorybuf::in buf_
The stream buffer.
stream_type stream_
The stream.
Detailed Description
An stream/stream-buffer input allocator with List storage.
Definition at line 55 of file IListStream.H.
Constructor & Destructor Documentation
IListStreamAllocator () inline protected
Construct empty.
Definition at line 67 of file IListStream.H.
IListStreamAllocator (List< char > && buffer) inline protected
Move construct from List.
Definition at line 76 of file IListStream.H.
IListStreamAllocator (DynamicList< char, SizeMin > && buffer) inline protected
Move construct from DynamicList.
Definition at line 86 of file IListStream.H.
Member Function Documentation
void reset_gbuffer () inline protected
Convenience method to address the underlying List storage.
Definition at line 98 of file IListStream.H.
Referenced by IListStreamAllocator::clearStorage().
void clearStorage () inline
Clear storage.
Definition at line 119 of file IListStream.H.
References IListStreamAllocator::reset_gbuffer(), and UList< T >::swap().
void swap (List< char > & list) inline
Transfer contents to other List.
Definition at line 128 of file IListStream.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/IListStream.H