OpenFOAM: hRefConstThermo< EquationOfState > Class Template Reference
hRefConstThermo< EquationOfState > Class Template Reference
Thermodynamics
Constant properties thermodynamics package templated into the EquationOfState.
Public Member Functions
hRefConstThermo (const dictionary &dict)
Construct from dictionary.
hRefConstThermo (const word &, const hRefConstThermo &)
Construct as named copy.
autoPtr< hRefConstThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar Cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar Ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kg].
scalar Hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar dGdT (const scalar p, const scalar T) const
Derivative of Gibbs free energy w.r.t. temperature.
scalar dCpdT (const scalar p, const scalar T) const
Temperature derivative of heat capacity at constant pressure.
void write (Ostream &os) const
Write to Ostream.
void operator+= (const hRefConstThermo &)
Static Public Member Functions
static autoPtr< hRefConstThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hRefConstThermo operator+ (const hRefConstThermo &, const hRefConstThermo &)
hRefConstThermo operator* (const scalar, const hRefConstThermo &)
hRefConstThermo operator== (const hRefConstThermo &, const hRefConstThermo &)
Ostream & operator (Ostream &, const hRefConstThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hRefConstThermo< EquationOfState >
Constant properties thermodynamics package templated into the EquationOfState.
Source files
hRefConstThermo.H
hRefConstThermoI.H
hRefConstThermo.C
Definition at line 47 of file hRefConstThermo.H.
Constructor & Destructor Documentation
hRefConstThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 27 of file hRefConstThermo.C.
hRefConstThermo (const word & name, const hRefConstThermo< EquationOfState > & ct) inline
Construct as named copy.
Definition at line 45 of file hRefConstThermoI.H.
Member Function Documentation
Foam::autoPtr< Foam::hRefConstThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 60 of file hRefConstThermoI.H.
Foam::autoPtr< Foam::hRefConstThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 68 of file hRefConstThermoI.H.
References Foam::New().
static word typeName () inline static
Return the instantiated type name.
Definition at line 140 of file hRefConstThermo.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 78 of file hRefConstThermoI.H.
Foam::scalar Cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 88 of file hRefConstThermoI.H.
References T.
Foam::scalar Ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kg].
Definition at line 99 of file hRefConstThermoI.H.
References Cp.
Foam::scalar Hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 109 of file hRefConstThermoI.H.
References Hs().
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 118 of file hRefConstThermoI.H.
References H(), and T.
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 126 of file hRefConstThermoI.H.
References Hf_().
Foam::scalar dGdT (const scalar p, const scalar T) const inline
Derivative of Gibbs free energy w.r.t. temperature.
Definition at line 136 of file hRefConstThermoI.H.
References Foam::log(), and Foam::constant::standard::Tstd.
Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Temperature derivative of heat capacity at constant pressure.
Definition at line 146 of file hRefConstThermoI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 40 of file hRefConstThermo.C.
void operator+= (const hRefConstThermo< EquationOfState > &) inline
Definition at line 158 of file hRefConstThermoI.H.
Friends And Related Function Documentation
hRefConstThermo operator+ (const hRefConstThermo< EquationOfState > & , const hRefConstThermo< EquationOfState > &) friend
hRefConstThermo operator* (const scalar , const hRefConstThermo< EquationOfState > &) friend
hRefConstThermo operator== (const hRefConstThermo< EquationOfState > & , const hRefConstThermo< EquationOfState > &) friend
Ostream& operator (Ostream & , const hRefConstThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hRefConst/hRefConstThermo.H
src/thermophysicalModels/specie/thermo/hRefConst/hRefConstThermo.C
src/thermophysicalModels/specie/thermo/hRefConst/hRefConstThermoI.H