OpenFOAM: axisAngle Class Reference
axisAngle Class Reference
A coordinateRotation specified by a rotation axis and a rotation angle about that axis.
Public Member Functions
TypeNameNoDebug ("axisAngle")
Runtime type information.
axisAngle ()
Construct null.
axisAngle (const axisAngle &crot)
Copy construct.
axisAngle (axisAngle &&crot)
Move construct.
axisAngle (const vector &axis, scalar angle, bool degrees)
Construct from axis and angle.
axisAngle (const vector::components axis, scalar angle, bool degrees)
Construct from x/y/z axis enumeration and angle.
axisAngle (const dictionary &dict)
Construct from dictionary.
autoPtr< coordinateRotation > clone () const
Return clone.
virtual ~axisAngle ()=default
Destructor.
virtual void clear ()
Reset specification.
virtual tensor R () const
Calculate and return the rotation tensor calculated from axis and angle.
virtual void write (Ostream &os) const
Write information.
virtual void writeEntry (const word &keyword, Ostream &os) const
Write dictionary entry.
Public Member Functions inherited from coordinateRotation
TypeNameNoDebug ("coordinateRotation")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, coordinateRotation, dictionary,(const dictionary &dict),(dict))
virtual ~coordinateRotation ()=default
Destructor.
Static Public Member Functions
static tensor rotation (const vector &axis, const scalar angle, bool degrees=false)
The rotation tensor for given axis/angle.
Static Public Member Functions inherited from coordinateRotation
static autoPtr
< coordinateRotation > New (const dictionary &dict)
Select constructed from dictionary.
Additional Inherited Members
Static Protected Member Functions inherited from coordinateRotation
static vector findOrthogonal (const vector &axis)
Determine best-guess for an orthogonal axis.
Detailed Description
A coordinateRotation specified by a rotation axis and a rotation angle about that axis.
coordinateRotation
{
    type        axisAngle;
    axis        (1 0 0);
    angle       90;
}
Dictionary entries
Property Description Required Default
type Type name: axisAngle yes
axis Axis of rotation (vector) yes
angle Rotation angle yes
degrees The angle is in degrees no true
Note
The rotation axis will be normalized internally.
Source files
axisAngleRotation.H
axisAngleRotation.C
Definition at line 95 of file axisAngleRotation.H.
Constructor & Destructor Documentation
axisAngle ()
Construct null.
Definition at line 75 of file axisAngleRotation.C.
axisAngle (const axisAngle & crot)
Copy construct.
Definition at line 84 of file axisAngleRotation.C.
axisAngle (axisAngle && crot)
Move construct.
Definition at line 95 of file axisAngleRotation.C.
axisAngle (const vector & axis, scalar angle, bool degrees)
Construct from axis and angle.
Definition at line 107 of file axisAngleRotation.C.
axisAngle (const vector::components axis, scalar angle, bool degrees)
Construct from x/y/z axis enumeration and angle.
Definition at line 123 of file axisAngleRotation.C.
axisAngle (const dictionary & dict) explicit
Construct from dictionary.
Definition at line 138 of file axisAngleRotation.C.
References axis_().
virtual ~axisAngle () virtual default
Destructor.
Member Function Documentation
TypeNameNoDebug ("axisAngle")
Runtime type information.
autoPtr<coordinateRotation> clone () const inline virtual
Return clone.
Implements coordinateRotation.
Definition at line 167 of file axisAngleRotation.H.
Foam::tensor rotation (const vector & axis, const scalar angle, bool degrees = false) static
The rotation tensor for given axis/angle.
Definition at line 58 of file axisAngleRotation.C.
void clear () virtual
Reset specification.
Implements coordinateRotation.
Definition at line 151 of file axisAngleRotation.C.
Foam::tensor R () const virtual
Calculate and return the rotation tensor calculated from axis and angle.
Implements coordinateRotation.
Definition at line 158 of file axisAngleRotation.C.
References Foam::extrudeModels::angle_(), axis_(), and Foam::Zero.
void write (Ostream & os) const virtual
Write information.
Implements coordinateRotation.
Definition at line 164 of file axisAngleRotation.C.
References Foam::extrudeModels::angle_(), axis_(), and degrees_().
void writeEntry (const word & keyword, Ostream & os) const virtual
Write dictionary entry.
Implements coordinateRotation.
Definition at line 172 of file axisAngleRotation.C.
References Foam::extrudeModels::angle_(), axis_(), and degrees_().
The documentation for this class was generated from the following files:
src/meshTools/coordinate/rotation/axisAngleRotation.H
src/meshTools/coordinate/rotation/axisAngleRotation.C