OpenFOAM: FIFOStack< T > Class Template Reference
FIFOStack< T > Class Template Reference
A FIFO stack based on a singly-linked list.
Public Member Functions
T top () const
Return a copy of the top element.
T bottom () const
Return a copy of the bottom element.
void push (const T &element)
Push an element onto the back of the stack.
void push (T &&element)
Move an element onto the back of the stack.
T pop ()
Pop the bottom element off the stack.
Public Member Functions inherited from LList< LListBase, T >
LList ()=default
Null construct.
LList (const T &item)
Construct and copy insert the initial T item.
LList (T &&item)
Construct and move insert the initial T item.
LList (Istream &is)
Construct from Istream.
LList (const LList< LListBase, T > &lst)
Copy construct.
LList (LList< LListBase, T > &&lst)
Move construct.
LList (std::initializer_list< T > lst)
Copy construct from an initializer list.
~LList ()
Destructor.
reference first ()
The first entry in the list.
const_reference first () const
The first entry in the list (const access)
reference last ()
The last entry in the list.
const_reference last () const
The last entry in the list (const access)
void insert (const T &item)
Add copy at head of list.
void insert (T &&item)
Move construct at head of list.
void append (const T &item)
Add copy at tail of list.
void append (T &&item)
Move construct at tail of list.
T removeHead ()
Remove and return head.
T remove (link *item)
Remove and return element.
T remove (iterator &iter)
Remove and return element specified by iterator.
void clear ()
Delete contents of list.
void transfer (LList< LListBase, T > &lst)
Transfer the contents of the argument into this List.
void operator= (const LList< LListBase, T > &lst)
Copy assignment.
void operator= (LList< LListBase, T > &&lst)
Move assignment.
void operator= (std::initializer_list< T > lst)
Copy assignment from an initializer list.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write LList with line-breaks when length exceeds shortLen.
iterator begin ()
Iterator to first item in list with non-const access.
const_iterator cbegin () const
Iterator to first item in list with const access.
reverse_iterator rbegin ()
Iterator to last item in list with non-const access.
const_reverse_iterator crbegin () const
Iterator to last item in list with const access.
const_iterator begin () const
Iterator to first item in list with const access.
const_reverse_iterator rbegin () const
Iterator to last item in list with const access.
const iterator & end ()
End of list for forward iterators.
const const_iterator & cend () const
End of list for forward iterators.
const reverse_iterator & rend ()
End of list for reverse iterators.
const const_reverse_iterator & crend () const
End of list for reverse iterators.
const const_iterator & end () const
End of list for forward iterators.
const const_reverse_iterator & rend () const
End of list for reverse iterators.
Additional Inherited Members
Public Types inherited from LList< LListBase, T >
typedef T value_type
Type of values stored.
typedef T * pointer
Pointer for value_type.
typedef const T * const_pointer
Const pointer for value_type.
typedef T & reference
Reference for value_type.
typedef const T & const_reference
Const reference for value_type.
typedef label size_type
The type that can represent the container size.
typedef label difference_type
The difference between iterator objects.
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Detailed Description
template<class T>
class Foam::FIFOStack< T >
A FIFO stack based on a singly-linked list.
Stack operations are push(), pop(), top(), bottom().
Definition at line 45 of file FIFOStack.H.
Member Function Documentation
T top () const inline
Return a copy of the top element.
Definition at line 64 of file FIFOStack.H.
T bottom () const inline
Return a copy of the bottom element.
Definition at line 72 of file FIFOStack.H.
void push (const T & element) inline
Push an element onto the back of the stack.
Definition at line 80 of file FIFOStack.H.
Referenced by averageCondition::calc(), DAC< CompType, ThermoType >::reduceMechanism(), and DRGEP< CompType, ThermoType >::reduceMechanism().
void push (T && element) inline
Move an element onto the back of the stack.
Definition at line 88 of file FIFOStack.H.
T pop () inline
Pop the bottom element off the stack.
Definition at line 96 of file FIFOStack.H.
Referenced by averageCondition::calc(), DAC< CompType, ThermoType >::reduceMechanism(), and DRGEP< CompType, ThermoType >::reduceMechanism().
The documentation for this class was generated from the following file:
src/OpenFOAM/containers/LinkedLists/user/FIFOStack.H