OpenFOAM: NURBSbasis Class Reference
NURBSbasis Class Reference
NURBSbasis fuction. Used to construct NURBS curves, surfaces and volumes.
Public Member Functions
TypeName ("NURBbasis")
Runtime type information.
NURBSbasis (const label nCPs, const label degree, const scalarField &knots)
Construct from number of control points, knot vector and basis order.
NURBSbasis (const label nCPs, const label degree)
Construct from number of control points and basis order.
NURBSbasis (const dictionary &dict)
Construct from dictionary.
NURBSbasis (const NURBSbasis &)
Construct as copy.
virtual ~NURBSbasis ()=default
Destructor.
scalar basisValue (const label iCP, const label degree, const scalar u) const
Basis value.
scalar basisDerivativeU (const label iCP, const label degree, const scalar u) const
Basis derivative w.r.t u.
scalar basisDerivativeUU (const label iCP, const label degree, const scalar u) const
Basis second derivative w.r.t u.
bool checkRange (const scalar u, const label CPI, const label degree) const
Checks to see if given u is affected by given CP.
label insertKnot (const scalar uBar)
Adds the new knot's u value, increments the nCPs and returns 'k', the index of the newly inserted uValue.
const scalarField & knots () const
const label & degree () const
const label & nCPs () const
Detailed Description
NURBSbasis fuction. Used to construct NURBS curves, surfaces and volumes.
Source files
NURBSbasis.H
NURBSbasis.C
NURBSbasisTemplates.C
NURBSbasisI.H
Definition at line 51 of file NURBSbasis.H.
Constructor & Destructor Documentation
NURBSbasis (const label nCPs, const label degree, const scalarField & knots)
Construct from number of control points, knot vector and basis order.
Definition at line 77 of file NURBSbasis.C.
NURBSbasis (const label nCPs, const label degree)
Construct from number of control points and basis order.
Assumes uniform knot vector
Definition at line 90 of file NURBSbasis.C.
NURBSbasis (const dictionary & dict)
Construct from dictionary.
Assumes uniform knot vector
Definition at line 104 of file NURBSbasis.C.
NURBSbasis (const NURBSbasis & basis)
Construct as copy.
Definition at line 117 of file NURBSbasis.C.
virtual ~NURBSbasis () virtual default
Destructor.
Member Function Documentation
TypeName ("NURBbasis")
Runtime type information.
scalar basisValue (const label iCP, const label degree, const scalar u) const
Basis value.
Definition at line 133 of file NURBSbasis.C.
scalar basisDerivativeU (const label iCP, const label degree, const scalar u) const
Basis derivative w.r.t u.
Definition at line 183 of file NURBSbasis.C.
scalar basisDerivativeUU (const label iCP, const label degree, const scalar u) const
Basis second derivative w.r.t u.
Definition at line 224 of file NURBSbasis.C.
bool checkRange (const scalar u, const label CPI, const label degree) const
Checks to see if given u is affected by given CP.
Definition at line 266 of file NURBSbasis.C.
Referenced by NURBS3DCurve::checkRange(), and NURBS3DCurve::length().
label insertKnot (const scalar uBar)
Adds the new knot's u value, increments the nCPs and returns 'k', the index of the newly inserted uValue.
uBar should be pre-bounded between 0,1.
Definition at line 291 of file NURBSbasis.C.
const Foam::scalarField & knots () const inline
Definition at line 27 of file NURBSbasisI.H.
const Foam::label & degree () const inline
Definition at line 33 of file NURBSbasisI.H.
Referenced by NURBS3DCurve::length().
const Foam::label & nCPs () const inline
Definition at line 39 of file NURBSbasisI.H.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBSbasis/NURBSbasis.H
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBSbasis/NURBSbasis.C
src/optimisation/adjointOptimisation/adjoint/parameterization/NURBS/NURBSbasis/NURBSbasisI.H