OpenFOAM: linearUpwindNormal< Type > Class Template Reference
linearUpwindNormal< Type > Class Template Reference
linearUpwindNormal interpolation scheme class derived from upwind and returns upwind weighting factors and also applies a gradient-based explicit correction. The magnitude of the correcting gradient is equal to 1
Public Member Functions
TypeName ("linearUpwindNormal")
Runtime type information.
linearUpwindNormal (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from faceFlux.
linearUpwindNormal (const fvMesh &mesh, Istream &schemeData)
Construct from Istream.
linearUpwindNormal (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Construct from faceFlux and Istream.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the face-interpolate.
Public Member Functions inherited from upwind< Type >
TypeName ("upwind")
Runtime type information.
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from faceFlux.
upwind (const fvMesh &mesh, Istream &is)
Construct from Istream.
upwind (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &)
Construct from faceFlux and Istream.
virtual tmp< surfaceScalarField > limiter (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation limiter.
tmp< surfaceScalarField > weights () const
Return the interpolation weighting factors.
virtual tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
TypeName ("limitedSurfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, limitedSurfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
limitedSurfaceInterpolationScheme (const fvMesh &mesh, const surfaceScalarField &faceFlux)
Construct from mesh and faceFlux.
limitedSurfaceInterpolationScheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
virtual ~limitedSurfaceInterpolationScheme ()
Destructor.
tmp< surfaceScalarField > weights (const GeometricField< Type, fvPatchField, volMesh > &, const surfaceScalarField &CDweights, tmp< surfaceScalarField > tLimiter) const
Return the interpolation weighting factors for the given field,.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > flux (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors.
Public Member Functions inherited from surfaceInterpolationScheme< Type >
TypeName ("surfaceInterpolationScheme")
Runtime type information.
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
declareRunTimeSelectionTable (tmp, surfaceInterpolationScheme, MeshFlux,(const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData),(mesh, faceFlux, schemeData))
surfaceInterpolationScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~surfaceInterpolationScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< typename innerProduct
< vector, Type >::type,
fvsPatchField, surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< typename
innerProduct< vector, Type >
::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const surfaceVectorField &Sf, const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the face-interpolate of the given cell field.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the face-interpolate of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from limitedSurfaceInterpolationScheme< Type >
static tmp
< limitedSurfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp
< limitedSurfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
Static Public Member Functions inherited from surfaceInterpolationScheme< Type >
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp
< surfaceInterpolationScheme
< Type > > New (const fvMesh &mesh, const surfaceScalarField &faceFlux, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
template<class SFType >
static tmp< GeometricField
< typename innerProduct
< typename SFType::value_type,
Type >::type, fvsPatchField,
surfaceMesh > > dotInterpolate (const SFType &Sf, const GeometricField< Type, fvPatchField, volMesh > &vf, const tmp< surfaceScalarField > &tlambdas)
Return the face-interpolate of the given cell field.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &)
Return the face-interpolate of the given cell field.
Protected Attributes inherited from limitedSurfaceInterpolationScheme< Type >
const surfaceScalarField & faceFlux_
Detailed Description
template<class Type>
class Foam::linearUpwindNormal< Type >
linearUpwindNormal interpolation scheme class derived from upwind and returns upwind weighting factors and also applies a gradient-based explicit correction. The magnitude of the correcting gradient is equal to 1
Source files
linearUpwindNormal.H
linearUpwindNormal.C
Definition at line 53 of file linearUpwindNormal.H.
Constructor & Destructor Documentation
linearUpwindNormal (const fvMesh & mesh, const surfaceScalarField & faceFlux) inline
Construct from faceFlux.
Definition at line 90 of file linearUpwindNormal.H.
linearUpwindNormal (const fvMesh & mesh, Istream & schemeData) inline
Construct from Istream.
The name of the flux field is read from the Istream and looked-up from the mesh objectRegistry
Definition at line 110 of file linearUpwindNormal.H.
linearUpwindNormal (const fvMesh & mesh, const surfaceScalarField & faceFlux, Istream & schemeData) inline
Construct from faceFlux and Istream.
Definition at line 131 of file linearUpwindNormal.H.
Member Function Documentation
TypeName ("linearUpwindNormal< Type >")
Runtime type information.
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 155 of file linearUpwindNormal.H.
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the face-interpolate.
Reimplemented from surfaceInterpolationScheme< Type >.
Definition at line 31 of file linearUpwindNormal.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), fvMesh::C(), fvMesh::Cf(), fvsPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, Foam::mag(), mesh, IOobject::name(), fvMesh::neighbour(), fvMesh::owner(), fvMesh::time(), Time::timeName(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/optimisation/adjointOptimisation/adjoint/finiteVolume/interpolation/surfaceInterpolation/schemes/limitedSchemes/linearUpwindNormal/linearUpwindNormal.H
src/optimisation/adjointOptimisation/adjoint/finiteVolume/interpolation/surfaceInterpolation/schemes/limitedSchemes/linearUpwindNormal/linearUpwindNormal.C