OpenFOAM: dynamicAlphaContactAngleFvPatchScalarField Class Reference
dynamicAlphaContactAngleFvPatchScalarField Class Reference
A dynamic alphaContactAngle scalar boundary condition (alphaContactAngleTwoPhaseFvPatchScalarField)
Public Member Functions
TypeName ("dynamicAlphaContactAngle")
Runtime type information.
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
Evaluate and return dynamic contact-angle.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphaContactAngleTwoPhaseFvPatchScalarField
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &)
Construct as copy.
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Evaluate the patch field.
Additional Inherited Members
Public Types inherited from alphaContactAngleTwoPhaseFvPatchScalarField
enum limitControls { lcNone, lcGradient, lcZeroGradient, lcAlpha }
Alpha limit options.
Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
static const Enum< limitControls > limitControlNames_
Detailed Description
A dynamic alphaContactAngle scalar boundary condition (alphaContactAngleTwoPhaseFvPatchScalarField)
Source files
dynamicAlphaContactAngleFvPatchScalarField.H
dynamicAlphaContactAngleFvPatchScalarField.C
Definition at line 48 of file dynamicAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 31 of file dynamicAlphaContactAngleFvPatchScalarField.C.
Referenced by dynamicAlphaContactAngleFvPatchScalarField::clone().
dynamicAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 63 of file dynamicAlphaContactAngleFvPatchScalarField.C.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
dynamicAlphaContactAngleFvPatchScalarField onto a new patch
Definition at line 46 of file dynamicAlphaContactAngleFvPatchScalarField.C.
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf)
Construct as copy.
Definition at line 81 of file dynamicAlphaContactAngleFvPatchScalarField.C.
References Foam::stringOps::evaluate().
dynamicAlphaContactAngleFvPatchScalarField (const dynamicAlphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 95 of file dynamicAlphaContactAngleFvPatchScalarField.C.
Member Function Documentation
TypeName ("dynamicAlphaContactAngle")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 129 of file dynamicAlphaContactAngleFvPatchScalarField.H.
References dynamicAlphaContactAngleFvPatchScalarField::dynamicAlphaContactAngleFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 150 of file dynamicAlphaContactAngleFvPatchScalarField.H.
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Evaluate and return dynamic contact-angle.
Implements alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 112 of file dynamicAlphaContactAngleFvPatchScalarField.C.
void write (Ostream & os) const virtual
Write.
Reimplemented from alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 142 of file dynamicAlphaContactAngleFvPatchScalarField.C.
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/dynamicAlphaContactAngle/dynamicAlphaContactAngleFvPatchScalarField.C