OpenFOAM: ReactingParcel< ParcelType >::trackingData Class Reference
ReactingParcel< ParcelType >::trackingData Class Reference
Public Types
typedef
ParcelType::trackingData::trackPart trackPart
Public Member Functions
template<class TrackCloudType >
trackingData (const TrackCloudType &cloud, trackPart part=ParcelType::trackingData::tpLinearTrack)
Construct from components.
const interpolation< scalar > & pInterp () const
Return const access to the interpolator for continuous phase.
scalar pc () const
Return the continuous phase pressure.
scalar & pc ()
Access the continuous phase pressure.
Detailed Description
template<class ParcelType>
class Foam::ReactingParcel< ParcelType >::trackingData
Definition at line 133 of file ReactingParcel.H.
Member Typedef Documentation
typedef ParcelType::trackingData::trackPart trackPart
Definition at line 159 of file ReactingParcel.H.
Constructor & Destructor Documentation
trackingData (const TrackCloudType & cloud, trackPart part = ParcelType::trackingData::tpLinearTrack) inline
Construct from components.
Definition at line 24 of file ReactingParcelTrackingDataI.H.
Member Function Documentation
const Foam::interpolation< Foam::scalar > & pInterp () const inline
Return const access to the interpolator for continuous phase.
pressure field
Definition at line 44 of file ReactingParcelTrackingDataI.H.
Referenced by ReactingParcel< ParcelType >::setCellValues().
Foam::scalar pc () const inline
Return the continuous phase pressure.
Definition at line 51 of file ReactingParcelTrackingDataI.H.
Referenced by ReactingParcel< ParcelType >::calcPhaseChange(), and ReactingParcel< ParcelType >::setCellValues().
Foam::scalar & pc () inline
Access the continuous phase pressure.
Definition at line 58 of file ReactingParcelTrackingDataI.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcel.H
src/lagrangian/intermediate/parcels/Templates/ReactingParcel/ReactingParcelTrackingDataI.H