OpenFOAM: appendRawFormatter Class Reference
appendRawFormatter Class Reference
Appended raw binary output.
Public Member Functions
appendRawFormatter (std::ostream &os)
Construct and attach to an output stream.
virtual ~appendRawFormatter ()=default
Destructor.
virtual const outputOptions & opts () const
The output is APPEND_BINARY.
virtual const char * name () const
Output name for XML type ("append")
virtual const char * encoding () const
Output name for append encoding type ("raw")
virtual uint64_t offset (const uint64_t numbytes)
Increase the append data offset by numbytes and sizeof(uint64_t).
virtual bool writeSize (const uint64_t numbytes)
Write leading size for binary output.
virtual void write (const uint8_t val)
virtual void write (const label val)
virtual void write (const float val)
virtual void write (const double val)
virtual void flush ()
A no-op for this format.
Public Member Functions inherited from formatter
virtual ~formatter ()=default
Destructor.
std::ostream & os ()
Access to the underlying output stream.
void quoting (const quoteChar quote)
Change quoting char for XML attributes (default: SINGLE_QUOTE)
virtual std::size_t encodedLength (std::size_t n) const
The encoded length for binary output is pass-through.
void indent ()
Add indenting according to the current XML tag depth.
void indent (label n)
Add indenting of n spaces.
formatter & xmlHeader ()
Write XML header.
template<class... Args>
formatter & xmlComment (const std::string &text, Args &&...args)
Write XML comment (at the current indentation level)
template<class... Args>
formatter & openTag (const word &tagName, Args &&...args)
Start an XML tag, optionally with attributes.
template<class... Args>
formatter & openTag (vtk::fileTag t, Args &&...args)
Start an XML tag, optionally with attributes.
formatter & closeTag (const bool isEmpty=false)
Finish an XML tag, optional as an empty container.
formatter & endTag (const word &tagName=word::null)
An end XML tag, optional with sanity check.
virtual formatter & endTag (vtk::fileTag t)
An end XML tag with sanity check.
template<class... Args>
formatter & tag (const word &t, Args &&...args)
Write XML tag without any attributes. Combines openTag/closeTag.
template<class... Args>
formatter & tag (vtk::fileTag t, Args &&...args)
Write XML tag without any attributes. Combines openTag/closeTag.
formatter & beginVTKFile (const word &contentType, const word &contentVersion, const bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
formatter & beginVTKFile (vtk::fileTag contentType, const word &contentVersion, const bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
formatter & beginVTKFile (vtk::fileTag contentType, const bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
template<vtk::fileTag ContentType>
formatter & beginVTKFile (bool leaveOpen=false)
Add a "VTKFile" XML tag for contentType, followed by a tag for the contentType itself.
formatter & beginAppendedData ()
Add a "AppendedData" XML tag with the current encoding and output the requisite '_' prefix.
formatter & beginBlock (label index, std::string name="")
Begin "Block" XML section.
formatter & endBlock ()
End "Block" XML section.
formatter & beginPiece (label index, std::string name="")
Begin "Piece" XML section.
virtual formatter & endPiece ()
End "Piece" XML section.
formatter & DataSet (label index, std::string file="", bool autoName=true)
Insert a single "DataSet" XML entry tag.
formatter & DataSet (label index, std::string file, std::string name)
Insert a single "DataSet" XML entry tag.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & beginDataArray (const word &dataName, uint64_t payLoad=npos, bool leaveOpen=false)
Begin "DataArray" XML section.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & beginDataArray (const vtk::dataArrayAttr &dataName, uint64_t payLoad=npos, bool leaveOpen=false)
Begin "DataArray" XML section.
virtual formatter & endDataArray ()
End "DataArray" XML section.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & PDataArray (const word &dataName)
Insert a single "PDataArray" XML entry tag.
formatter & beginFieldData ()
Begin "FieldData" XML section.
formatter & beginCellData ()
Begin "CellData" XML section.
formatter & beginPointData ()
Begin "PointData" XML section.
virtual formatter & endFieldData ()
End "FieldData" XML section.
virtual formatter & endCellData ()
End "CellData" XML section.
virtual formatter & endPointData ()
End "PointData" XML section.
formatter & endAppendedData ()
End "AppendedData" XML section.
virtual formatter & endVTKFile ()
End "VTKFile" XML section.
formatter & writeTimeValue (scalar timeValue)
Emit "TimeValue" for FieldData (name as per Catalyst output)
template<class... Args>
formatter & xmlAttr (const word &k, const std::string &v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const int32_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const int64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const uint64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const word &k, const scalar v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const std::string &v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const int32_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const int64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const uint64_t v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class... Args>
formatter & xmlAttr (const vtk::fileAttr &k, const scalar v, Args &&...args)
Pair-wise write of XML key/value attributes.
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & openDataArray (const word &dataName)
Open "DataArray" XML tag and leave open (requires a closeTag).
template<class Type , direction nComp = 1, int nTuple = 0>
formatter & openDataArray (const vtk::dataArrayAttr &dataName)
Open "DataArray" XML tag and leave open (requires a closeTag).
template<class... Args>
Foam::vtk::formatter & xmlComment (const std::string &text, Args &&...args)
template<class... Args>
Foam::vtk::formatter & openTag (const word &tagName, Args &&...args)
template<class... Args>
Foam::vtk::formatter & openTag (vtk::fileTag t, Args &&...args)
template<class... Args>
Foam::vtk::formatter & tag (const word &t, Args &&...args)
template<class... Args>
Foam::vtk::formatter & tag (vtk::fileTag t, Args &&...args)
template<Foam::vtk::fileTag ContentType>
Foam::vtk::formatter & beginVTKFile (bool leaveOpen)
template<class Type , Foam::direction nComp, int nTuple>
Foam::vtk::formatter & beginDataArray (const vtk::dataArrayAttr &dataName, uint64_t payLoad, bool leaveOpen)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const std::string &v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const int32_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const int64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const uint64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const word &k, const scalar v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const std::string &v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const int32_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const int64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const uint64_t v, Args &&...args)
template<class... Args>
Foam::vtk::formatter & xmlAttr (const vtk::fileAttr &k, const scalar v, Args &&...args)
template<class Type , Foam::direction nComp, int nTuple>
Foam::vtk::formatter & beginDataArray (const word &dataName, uint64_t payLoad, bool leaveOpen)
template<class Type , Foam::direction nComp, int nTuple>
Foam::vtk::formatter & PDataArray (const word &dataName)
Protected Member Functions
void write (const char *s, std::streamsize n)
Write.
Protected Member Functions inherited from formatter
bool canWriteAttr (const word &k) const
Can write XML key/value attribute pair when inside a tag. Emit warning and return false if this condition is not met.
bool canWriteToplevel (const char *what) const
Can write tag-like top-level content (eg, comment, ...) when not already inside a tag. Emit warning and return false if this condition is not met.
template<class Type >
void writeAttr (const word &k, const Type &v)
Write XML key/value attribute pair (implementation).
formatter & xmlAttr ()
No-op write XML attribute (for templating code).
void xmlCommentLoop ()
No-op XML comment loop (for templating code).
template<class... Args>
void xmlCommentLoop (const std::string &text, Args &&...args)
Loop/output XML comments.
bool openTagImpl (const word &tagName)
Open XML tag (implementation), checking if not already inside another tag. Emit warning and return false if this condition is not met.
formatter (std::ostream &os)
Construct and attach to an output stream.
Additional Inherited Members
Public Types inherited from formatter
enum quoteChar : char { DOUBLE_QUOTE = '\"', SINGLE_QUOTE = '\'' }
Quoting for XML attributes.
typedef uint64_t headerType
The header data is vtk UInt64.
Static Public Attributes inherited from formatter
static constexpr uint64_t npos = uint64_t(-1)
Out of range position or size.
Protected Attributes inherited from formatter
std::ostream & os_
The output stream for the formatter.
DynamicList< word > xmlTags_
LIFO stack of current XML tags.
bool inTag_
Tag open/closed/ended state.
char quote_
Quoting character for XML attributes.
Detailed Description
Appended raw binary output.
Source files
foamVtkAppendRawFormatter.H
foamVtkAppendRawFormatter.C
Definition at line 48 of file foamVtkAppendRawFormatter.H.
Constructor & Destructor Documentation
appendRawFormatter (std::ostream & os)
Construct and attach to an output stream.
Definition at line 48 of file foamVtkAppendRawFormatter.C.
References formatter::os().
virtual ~appendRawFormatter () virtual default
Destructor.
Member Function Documentation
void write (const char * s, std::streamsize n) protected
Write.
Definition at line 37 of file foamVtkAppendRawFormatter.C.
const Foam::vtk::outputOptions & opts () const virtual
The output is APPEND_BINARY.
Implements formatter.
Definition at line 58 of file foamVtkAppendRawFormatter.C.
const char * name () const virtual
Output name for XML type ("append")
Implements formatter.
Definition at line 64 of file foamVtkAppendRawFormatter.C.
const char * encoding () const virtual
Output name for append encoding type ("raw")
Implements formatter.
Definition at line 70 of file foamVtkAppendRawFormatter.C.
uint64_t offset (const uint64_t numbytes) virtual
Increase the append data offset by numbytes and sizeof(uint64_t).
The additional (uint64_t) size information is consistent with writeSize()
Returns
The previous data offset
Reimplemented from formatter.
Definition at line 76 of file foamVtkAppendRawFormatter.C.
bool writeSize (const uint64_t numbytes) virtual
Write leading size for binary output.
Returns
True - format uses this information
Implements formatter.
Definition at line 88 of file foamVtkAppendRawFormatter.C.
void write (const uint8_t val) virtual
Implements formatter.
Definition at line 95 of file foamVtkAppendRawFormatter.C.
References Foam::vtk::write().
void write (const label val) virtual
Implements formatter.
Definition at line 101 of file foamVtkAppendRawFormatter.C.
References Foam::vtk::write().
void write (const float val) virtual
Implements formatter.
Definition at line 108 of file foamVtkAppendRawFormatter.C.
References Foam::vtk::write().
void write (const double val) virtual
Implements formatter.
Definition at line 115 of file foamVtkAppendRawFormatter.C.
References Foam::vtk::write().
void flush () virtual
A no-op for this format.
Implements formatter.
Definition at line 136 of file foamVtkAppendRawFormatter.C.
References Foam::vtk::write().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/format/foamVtkAppendRawFormatter.H
src/fileFormats/vtk/format/foamVtkAppendRawFormatter.C