OpenFOAM: writeFile Class Reference
writeFile Class Reference
functionObject base class for writing single files
Public Member Functions
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name="undefined", const bool writeToFile=true)
Construct from objectRegistry, prefix, fileName.
writeFile (const objectRegistry &obr, const fileName &prefix, const word &name, const dictionary &dict, const bool writeToFile=true)
Construct from objectRegistry, prefix, fileName and read options from dictionary.
writeFile (const writeFile &wf)
Construct copy.
virtual ~writeFile ()=default
Destructor.
virtual bool read (const dictionary &dict)
Read.
virtual OFstream & file ()
Return access to the file (if only 1)
virtual bool writeToFile () const
Flag to allow writing to file.
virtual label charWidth () const
Return width of character stream output.
virtual void writeCommented (Ostream &os, const string &str) const
Write a commented string to stream.
virtual void writeTabbed (Ostream &os, const string &str) const
Write a tabbed string to stream.
virtual void writeHeader (Ostream &os, const string &str) const
Write a commented header to stream.
virtual void writeCurrentTime (Ostream &os) const
Write the current time to stream.
virtual void writeBreak (Ostream &os) const
Write a break marker to the stream.
template<class Type >
void writeHeaderValue (Ostream &os, const string &property, const Type &value) const
Write a (commented) header property and value pair.
Static Public Attributes
static label addChars = 8
Additional characters for writing.
Protected Member Functions
void initStream (Ostream &os) const
Initialise the output stream for writing.
fileName baseFileDir () const
Return the base directory for output.
fileName baseTimeDir () const
Return the base directory for the current time value.
virtual autoPtr< OFstream > createFile (const word &name, scalar timeValue) const
Return autoPtr to a new file for a given time.
virtual autoPtr< OFstream > createFile (const word &name) const
Return autoPtr to a new file using the simulation start time.
virtual void resetFile (const word &name)
Reset internal file pointer to new file with new name.
Omanip< int > valueWidth (const label offset=0) const
Return the value width when writing to stream with optional offset.
void operator= (const writeFile &)=delete
No copy assignment.
Protected Attributes
const objectRegistry & fileObr_
Reference to the region objectRegistry.
const fileName prefix_
Prefix.
word fileName_
Name of file.
autoPtr< OFstream > filePtr_
File pointer.
label writePrecision_
Write precision.
bool writeToFile_
Flag to enable/disable writing to file.
bool writtenHeader_
Flag to identify whether the header has been written.
bool useUserTime_
Flag to use the specified user time, e.g. CA deg instead of seconds. Default = true.
scalar startTime_
Start time value.
Detailed Description
functionObject base class for writing single files
See Also
Foam::functionObject Foam::functionObjects::logFiles
Source files
writeFile.H
writeFile.C
Definition at line 55 of file writeFile.H.
Constructor & Destructor Documentation
writeFile (const objectRegistry & obr, const fileName & prefix, const word & name = "undefined", const bool writeToFile = true)
Construct from objectRegistry, prefix, fileName.
Definition at line 164 of file writeFile.C.
writeFile (const objectRegistry & obr, const fileName & prefix, const word & name, const dictionary & dict, const bool writeToFile = true)
Construct from objectRegistry, prefix, fileName and read options from dictionary.
Definition at line 184 of file writeFile.C.
writeFile (const writeFile & wf)
Construct copy.
Definition at line 149 of file writeFile.C.
References Foam::setw().
virtual ~writeFile () virtual default
Destructor.
Member Function Documentation
void initStream (Ostream & os) const protected
Initialise the output stream for writing.
Definition at line 35 of file writeFile.C.
Foam::fileName baseFileDir () const protected
Return the base directory for output.
Definition at line 43 of file writeFile.C.
References writeFile::charWidth(), Ostream::precision(), Foam::scientific(), IOstream::setf(), Ostream::width(), and writeFile::writePrecision_.
Foam::fileName baseTimeDir () const protected
Return the base directory for the current time value.
Definition at line 70 of file writeFile.C.
Foam::autoPtr< Foam::OFstream > createFile (const word & name, scalar timeValue) const protected virtual
Return autoPtr to a new file for a given time.
Definition at line 77 of file writeFile.C.
Referenced by logFiles::createFiles().
Foam::autoPtr< Foam::OFstream > createFile (const word & name) const protected virtual
Return autoPtr to a new file using the simulation start time.
Definition at line 122 of file writeFile.C.
void resetFile (const word & name) protected virtual
Reset internal file pointer to new file with new name.
Definition at line 131 of file writeFile.C.
Foam::Omanip< int > valueWidth (const label offset = 0) const protected
Return the value width when writing to stream with optional offset.
Definition at line 139 of file writeFile.C.
void operator= (const writeFile &) protected delete
No copy assignment.
bool read (const dictionary & dict) virtual
Read.
Reimplemented in surfaceFieldValue, stabilityBlendingFactor, forces, regionSizeDistribution, volFieldValue, forceCoeffs, extractEulerianParticles, fluxSummary, sizeDistribution, momentum, fieldMinMax, fieldExtents, fieldValueDelta, blendingFactor, valueAverage, solverInfo, particleDistribution, histogram, wallShearStress, reactionsSensitivityAnalysis< chemistryType >, fieldValue, energySpectrum, wallHeatFlux, continuityError, AMIWeights, timeInfo, cloudInfo, sixDoFRigidBodyState, DESModelRegions, yPlus, and specieReactionRates< ChemistryModelType >.
Definition at line 205 of file writeFile.C.
Referenced by logFiles::names().
Foam::OFstream & file () virtual
Return access to the file (if only 1)
Definition at line 221 of file writeFile.C.
Referenced by valueAverage::calc(), fieldMinMax::output(), and specieReactionRates< ChemistryModelType >::specieReactionRates().
bool writeToFile () const virtual
Flag to allow writing to file.
Definition at line 238 of file writeFile.C.
Foam::label charWidth () const virtual
Return width of character stream output.
Definition at line 244 of file writeFile.C.
Referenced by writeFile::baseFileDir(), and writeFile::writeHeaderValue().
void writeCommented (Ostream & os, const string & str) const virtual
Write a commented string to stream.
Definition at line 251 of file writeFile.C.
void writeTabbed (Ostream & os, const string & str) const virtual
Write a tabbed string to stream.
Definition at line 267 of file writeFile.C.
Referenced by fieldMinMax::output(), and solverInfo::writeFileHeader().
void writeHeader (Ostream & os, const string & str) const virtual
Write a commented header to stream.
Definition at line 277 of file writeFile.C.
References Foam::setw(), and Foam::tab.
void writeCurrentTime (Ostream & os) const virtual
Write the current time to stream.
Definition at line 287 of file writeFile.C.
References Foam::nl.
Referenced by fieldMinMax::output().
void writeBreak (Ostream & os) const virtual
Write a break marker to the stream.
Definition at line 300 of file writeFile.C.
void writeHeaderValue (Ostream & os, const string & property, const Type & value) const
Write a (commented) header property and value pair.
Definition at line 25 of file writeFileTemplates.C.
References writeFile::charWidth(), Foam::nl, Foam::setf(), and Foam::setw().
Member Data Documentation
const objectRegistry& fileObr_ protected
Reference to the region objectRegistry.
Definition at line 65 of file writeFile.H.
Referenced by logFiles::createFiles().
const fileName prefix_ protected
Prefix.
Definition at line 70 of file writeFile.H.
word fileName_ protected
Name of file.
Definition at line 75 of file writeFile.H.
autoPtr<OFstream> filePtr_ protected
File pointer.
Definition at line 80 of file writeFile.H.
label writePrecision_ protected
Write precision.
Definition at line 85 of file writeFile.H.
Referenced by writeFile::baseFileDir().
bool writeToFile_ protected
Flag to enable/disable writing to file.
Definition at line 90 of file writeFile.H.
bool writtenHeader_ protected
Flag to identify whether the header has been written.
Definition at line 95 of file writeFile.H.
bool useUserTime_ protected
Flag to use the specified user time, e.g. CA deg instead of seconds. Default = true.
Definition at line 101 of file writeFile.H.
scalar startTime_ protected
Start time value.
Definition at line 106 of file writeFile.H.
Foam::label addChars = 8 static
Additional characters for writing.
Definition at line 165 of file writeFile.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/writeFile/writeFile.H
src/OpenFOAM/db/functionObjects/writeFile/writeFile.C
src/OpenFOAM/db/functionObjects/writeFile/writeFileTemplates.C