OpenFOAM: rigidBodySolver Class Reference
rigidBodySolver Class Reference abstract
Public Member Functions
TypeName ("rigidBodySolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, rigidBodySolver, dictionary,(rigidBodyMotion &body, const dictionary &dict),(body, dict))
rigidBodySolver (rigidBodyMotion &body)
virtual ~rigidBodySolver ()
Destructor.
virtual void solve (const scalarField &tau, const Field< spatialVector > &fx)=0
Integrate the rigid-body motion for one time-step.
Static Public Member Functions
static autoPtr< rigidBodySolver > New (rigidBodyMotion &body, const dictionary &dict)
Protected Member Functions
rigidBodyModelState & state ()
Return the motion state.
scalarField & q ()
Return the current joint position and orientation.
scalarField & qDot ()
Return the current joint quaternion.
scalarField & qDdot ()
Return the current joint acceleration.
scalar deltaT () const
Return the current time-step.
const rigidBodyModelState & state0 () const
Return the previous motion state.
const scalarField & q0 () const
Return the current joint position and orientation.
const scalarField & qDot0 () const
Return the current joint quaternion.
const scalarField & qDdot0 () const
Return the current joint acceleration.
scalar deltaT0 () const
Return the previous time-step.
void correctQuaternionJoints ()
Correct the quaternion joints based on the current change in q.
Protected Attributes
rigidBodyMotion & model_
The rigid-body model.
Detailed Description
Source files
rigidBodySolver.H
rigidBodySolver.C
newSixDoFSolver.C
Definition at line 49 of file rigidBodySolver.H.
Constructor & Destructor Documentation
rigidBodySolver (rigidBodyMotion & body)
Definition at line 38 of file rigidBodySolver.C.
~rigidBodySolver () virtual
Destructor.
Definition at line 46 of file rigidBodySolver.C.
Member Function Documentation
Foam::RBD::rigidBodyModelState & state () inline protected
Return the motion state.
Definition at line 23 of file rigidBodySolverI.H.
Foam::scalarField & q () inline protected
Return the current joint position and orientation.
Definition at line 29 of file rigidBodySolverI.H.
References rigidBodySolver::model_.
Foam::scalarField & qDot () inline protected
Return the current joint quaternion.
Return the current joint velocity
Definition at line 35 of file rigidBodySolverI.H.
Foam::scalarField & qDdot () inline protected
Return the current joint acceleration.
Definition at line 41 of file rigidBodySolverI.H.
Foam::scalar deltaT () const inline protected
Return the current time-step.
Definition at line 47 of file rigidBodySolverI.H.
const Foam::RBD::rigidBodyModelState & state0 () const inline protected
Return the previous motion state.
Definition at line 54 of file rigidBodySolverI.H.
const Foam::scalarField & q0 () const inline protected
Return the current joint position and orientation.
Definition at line 59 of file rigidBodySolverI.H.
const Foam::scalarField & qDot0 () const inline protected
Return the current joint quaternion.
Return the current joint velocity
Definition at line 65 of file rigidBodySolverI.H.
const Foam::scalarField & qDdot0 () const inline protected
Return the current joint acceleration.
Definition at line 71 of file rigidBodySolverI.H.
Foam::scalar deltaT0 () const inline protected
Return the previous time-step.
Definition at line 77 of file rigidBodySolverI.H.
void correctQuaternionJoints () protected
Correct the quaternion joints based on the current change in q.
Definition at line 52 of file rigidBodySolver.C.
TypeName ("rigidBodySolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , rigidBodySolver , dictionary , (rigidBodyMotion &body, const dictionary &dict) , (body, dict))
Foam::autoPtr< Foam::RBD::rigidBodySolver > New (rigidBodyMotion & body, const dictionary & dict) static
Definition at line 27 of file newRigidBodySolver.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual void solve (const scalarField & tau, const Field< spatialVector > & fx) pure virtual
Integrate the rigid-body motion for one time-step.
Implemented in CrankNicolson, Newmark, and symplectic.
Member Data Documentation
rigidBodyMotion& model_ protected
The rigid-body model.
Definition at line 58 of file rigidBodySolver.H.
Referenced by rigidBodySolver::q().
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/rigidBodySolver.H
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/newRigidBodySolver.C
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/rigidBodySolver.C
src/rigidBodyDynamics/rigidBodySolvers/rigidBodySolver/rigidBodySolverI.H