OpenFOAM: perfectFluid< Specie > Class Template Reference
perfectFluid< Specie > Class Template Reference
Equation of state
Perfect gas equation of state.
Public Member Functions
perfectFluid (const Specie &sp, const scalar R, const scalar rho0)
Construct from components.
perfectFluid (const dictionary &dict)
Construct from dictionary.
perfectFluid (const word &name, const perfectFluid &)
Construct as named copy.
autoPtr< perfectFluid > clone () const
Construct and return a clone.
scalar R () const
Return fluid constant [J/(kg K)].
scalar rho (scalar p, scalar T) const
Return density [kg/m^3].
scalar H (const scalar p, const scalar T) const
Return enthalpy departure [J/kg].
scalar Cp (scalar p, scalar T) const
Return Cp departure [J/(kg K].
scalar E (const scalar p, const scalar T) const
Return internal energy departure [J/kg].
scalar Cv (scalar p, scalar T) const
Return Cv departure [J/(kg K].
scalar S (const scalar p, const scalar T) const
Return entropy [J/(kg K)].
scalar psi (scalar p, scalar T) const
Return compressibility rho/p [s^2/m^2].
scalar Z (scalar p, scalar T) const
Return compression factor [].
scalar CpMCv (scalar p, scalar T) const
Return (Cp - Cv) [J/(kg K].
void write (Ostream &os) const
Write to Ostream.
void operator+= (const perfectFluid &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< perfectFluid > New (const dictionary &dict)
static word typeName ()
Return the instantiated type name.
Static Public Attributes
static const bool incompressible = false
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
perfectFluid operator+ (const perfectFluid &, const perfectFluid &)
perfectFluid operator* (const scalar s, const perfectFluid &)
perfectFluid operator== (const perfectFluid &, const perfectFluid &)
Ostream & operator (Ostream &, const perfectFluid &)
Detailed Description
template<class Specie>
class Foam::perfectFluid< Specie >
Perfect gas equation of state.
Source files
perfectFluid.H
perfectFluidI.H
perfectFluid.C
Definition at line 48 of file perfectFluid.H.
Constructor & Destructor Documentation
perfectFluid (const Specie & sp, const scalar R, const scalar rho0) inline
Construct from components.
Definition at line 28 of file perfectFluidI.H.
perfectFluid (const dictionary & dict)
Construct from dictionary.
Definition at line 27 of file perfectFluid.C.
perfectFluid (const word & name, const perfectFluid< Specie > &) inline
Construct as named copy.
Member Function Documentation
Foam::autoPtr< Foam::perfectFluid< Specie > > clone () const inline
Construct and return a clone.
Definition at line 57 of file perfectFluidI.H.
Foam::autoPtr< Foam::perfectFluid< Specie > > New (const dictionary & dict) inline static
Definition at line 66 of file perfectFluidI.H.
static word typeName () inline static
Return the instantiated type name.
Definition at line 139 of file perfectFluid.H.
Foam::scalar R () const inline
Return fluid constant [J/(kg K)].
Definition at line 77 of file perfectFluidI.H.
Foam::scalar rho (scalar p, scalar T) const inline
Return density [kg/m^3].
Definition at line 84 of file perfectFluidI.H.
References R_().
Foam::scalar H (const scalar p, const scalar T) const inline
Return enthalpy departure [J/kg].
Definition at line 91 of file perfectFluidI.H.
References R, and Foam::T().
Foam::scalar Cp (scalar p, scalar T) const inline
Return Cp departure [J/(kg K].
Definition at line 98 of file perfectFluidI.H.
Foam::scalar E (const scalar p, const scalar T) const inline
Return internal energy departure [J/kg].
Definition at line 105 of file perfectFluidI.H.
Foam::scalar Cv (scalar p, scalar T) const inline
Return Cv departure [J/(kg K].
Definition at line 112 of file perfectFluidI.H.
Foam::scalar S (const scalar p, const scalar T) const inline
Return entropy [J/(kg K)].
Definition at line 119 of file perfectFluidI.H.
Foam::scalar psi (scalar p, scalar T) const inline
Return compressibility rho/p [s^2/m^2].
Definition at line 126 of file perfectFluidI.H.
References Foam::log(), Foam::constant::standard::Pstd, and R.
Foam::scalar Z (scalar p, scalar T) const inline
Return compression factor [].
Definition at line 133 of file perfectFluidI.H.
References R, and Foam::T().
Foam::scalar CpMCv (scalar p, scalar T) const inline
Return (Cp - Cv) [J/(kg K].
Definition at line 140 of file perfectFluidI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 38 of file perfectFluid.C.
void operator+= (const perfectFluid< Specie > &) inline
Definition at line 153 of file perfectFluidI.H.
void operator*= (const scalar s) inline
Definition at line 172 of file perfectFluidI.H.
Friends And Related Function Documentation
perfectFluid operator+ (const perfectFluid< Specie > & , const perfectFluid< Specie > &) friend
perfectFluid operator* (const scalar s, const perfectFluid< Specie > &) friend
perfectFluid operator== (const perfectFluid< Specie > & , const perfectFluid< Specie > &) friend
Ostream& operator (Ostream & , const perfectFluid< Specie > &) friend
Member Data Documentation
const bool incompressible = false static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 150 of file perfectFluid.H.
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 155 of file perfectFluid.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluid.H
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluid.C
src/thermophysicalModels/specie/equationOfState/perfectFluid/perfectFluidI.H