OpenFOAM: cuttingPlane Class Reference
cuttingPlane Class Reference
Constructs cutting plane through a mesh.
Public Member Functions
cuttingPlane (const plane &pln, const primitiveMesh &mesh, const bool triangulate, const bitSet &cellIdLabels=bitSet())
Construct from plane and mesh reference, possibly restricted to a list of cells.
cuttingPlane (const plane &pln, const primitiveMesh &mesh, const bool triangulate, bitSet &&cellIdLabels)
Construct from plane and mesh reference, possibly restricted to a list of cells.
cuttingPlane (const plane &pln, const primitiveMesh &mesh, const bool triangulate, const labelUList &cellIdLabels)
Construct from plane and mesh reference, possibly restricted to a list of cells.
const plane & planeDesc () const
The plane used.
plane & planeDesc ()
The plane used. Non-const access.
void operator= (const cuttingPlane &rhs)
Copy assignment.
Public Member Functions inherited from plane
plane ()
Construct zero-initialised.
plane (const vector &normalVector)
Construct from normal vector through the origin.
plane (const point &originPoint, const vector &normalVector, const bool doNormalise=true)
Construct from normal vector and point in plane.
plane (const point &point1, const point &point2, const point &point3)
Construct from three points in plane.
plane (const scalarList &coeffs)
Construct from coefficients for the plane equation: ax + by + cz + d = 0.
plane (const FixedList< scalar, 4 > &coeffs)
Construct from coefficients for the plane equation: ax + by + cz + d = 0.
plane (const dictionary &dict)
Construct from dictionary.
plane (Istream &is)
Construct from Istream. Assumes (normal) (origin) input.
const vector & normal () const
The plane unit normal.
const point & origin () const
The plane base point.
point & origin ()
The plane base point, for modification.
const point & refPoint () const
The plane base point (same as origin)
void flip ()
Flip the plane by reversing the normal.
FixedList< scalar, 4 > planeCoeffs () const
Return coefficients for the plane equation: ax + by + cz + d = 0.
point nearestPoint (const point &p) const
Return nearest point in the plane for the given point.
scalar distance (const point &p) const
Return distance (magnitude) from the given point to the plane.
scalar signedDistance (const point &p) const
Return distance from the given point to the plane.
scalar normalIntersect (const point &pnt0, const vector &dir) const
Return cut coefficient for plane and line defined by origin and direction.
scalar normalIntersect (const ray &r) const
Return cut coefficient for plane and ray.
template<class Point , class PointRef >
scalar lineIntersect (const line< Point, PointRef > &l) const
Return the cutting point between the plane and.
ray planeIntersect (const plane &plane2) const
Return the cutting line between this plane and another.
point planePlaneIntersect (const plane &plane2, const plane &plane3) const
Return the cutting point between this plane and two other planes.
point somePointInPlane (const scalar dist=1e-3) const
Return a point somewhere on the plane, a distance from the base.
side sideOfPlane (const point &p) const
Return the side of the plane that the point is on.
int sign (const point &p, const scalar tol=SMALL) const
The sign for the side of the plane that the point is on.
point mirror (const point &p) const
Mirror the supplied point in the plane. Return the mirrored point.
void writeDict (Ostream &os) const
Write to dictionary.
Public Member Functions inherited from cuttingSurfaceBase
cuttingSurfaceBase ()
Construct null.
virtual ~cuttingSurfaceBase ()=default
Destructors.
const labelList & meshCells () const
The mesh cells cut.
labelList & meshCells ()
The mesh cells cut.
bool cut () const
Have any cells been cut?
void operator= (const cuttingSurfaceBase &rhs)
Copy assignment.
Public Member Functions inherited from MeshedSurface< face >
MeshedSurface ()
Construct null, an empty surface.
MeshedSurface (const MeshedSurface &surf)
Copy construct.
MeshedSurface (const UnsortedMeshedSurface< face > &surf)
Copy construct from an UnsortedMeshedSurface.
MeshedSurface (MeshedSurface &&surf)
Move construct.
MeshedSurface (UnsortedMeshedSurface< face > &&surf)
Move construct from an UnsortedMeshedSurface.
MeshedSurface (const pointField &pointLst, const UList< face > &faceLst, const UList< surfZone > &zoneLst)
Copy construct from components (points, faces, zones).
MeshedSurface (pointField &&pointLst, List< face > &&faceLst, const UList< surfZone > &zoneLst)
Move construct from components (points, faces).
MeshedSurface (const pointField &pointLst, const UList< face > &faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Copy construct from components (points, faces).
MeshedSurface (pointField &&pointLst, List< face > &&faceLst, const labelUList &zoneSizes=labelUList(), const UList< word > &zoneNames=UList< word >())
Move construct from components (points, faces).
MeshedSurface (const polyBoundaryMesh &bMesh, const bool globalPoints=false)
Construct from a boundary mesh with local points/faces.
MeshedSurface (const surfMesh &mesh)
Construct from a surfMesh.
MeshedSurface (const fileName &name)
Construct from file name (uses extension to determine type)
MeshedSurface (const fileName &name, const word &ext)
Construct from file name (uses extension to determine type)
MeshedSurface (Istream &is)
Construct from Istream.
MeshedSurface (const Time &runTime, const word &surfName=word::null)
Construct from database.
bool read (const fileName &name, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &name)
Read from file. Chooses reader based on detected extension.
virtual void write (const fileName &name, const dictionary &options=dictionary::null) const
Generic write routine. Chooses writer based on extension.
void write (const Time &t, const word &surfName=word::null) const
Write to database.
ClassName ("MeshedSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, MeshedSurface, fileExtension,(const fileName &name),(name))
virtual ~MeshedSurface ()
Destructor.
declareMemberFunctionSelectionTable (void, UnsortedMeshedSurface, write, fileExtension,(const fileName &name, const MeshedSurface< face > &surf, const dictionary &options),(name, surf, options))
label size () const
The surface size is the number of faces.
const List< face > & surfFaces () const
Return const access to the faces.
const surfZoneList & surfZones () const
Const access to the surface zones.
const vectorField & Sf () const
Face area vectors (normals)
const scalarField & magSf () const
Face area magnitudes.
const vectorField & Cf () const
Face centres.
virtual void clear ()
Clear all storage.
virtual void addZones (const UList< surfZone > &, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const UList< word > &names, const bool cullEmpty=false)
Add surface zones.
virtual void addZones (const labelUList &sizes, const bool cullEmpty=false)
Add surface zones.
bool addZonesToFaces ()
Propagate zone information on face regions.
virtual void removeZones ()
Remove surface zones.
virtual void movePoints (const pointField &newPoints)
Move points.
virtual void scalePoints (const scalar scaleFactor)
Scale points. A non-positive factor is ignored.
virtual void cleanup (const bool verbose)
Remove invalid faces.
virtual bool stitchFaces (const scalar tol=SMALL, const bool verbose=false)
virtual bool checkFaces (const bool verbose=false)
virtual label nTriangles () const
Count number of triangles.
virtual label nTriangles (List< label > &faceMap) const
Count number of triangles, returning a face map of original ids.
virtual label triangulate ()
Triangulate in-place, returning the number of triangles added.
virtual label triangulate (List< label > &faceMap)
Triangulate in-place, returning the number of triangles added.
MeshedSurface subsetMesh (const BoolListType &include, labelList &pointMap, labelList &faceMap) const
Return new surface.
MeshedSurface subsetMesh (const bitSet &include) const
Return new surface.
MeshedSurface subsetMesh (const labelHashSet &include) const
Return new surface.
void swap (MeshedSurface< face > &surf)
Swap contents.
void transfer (pointField &pointLst, List< face > &faceLst)
Transfer the components.
void transfer (MeshedSurface< face > &surf)
Transfer the contents of the argument and annul the argument.
void transfer (UnsortedMeshedSurface< face > &surf)
Transfer the contents of the argument and annul the argument.
autoPtr< MeshedSurface< face > > releaseGeom ()
Release (clear) geometry and return for reuse.
void swapFaces (List< face > &faces)
Swap the stored faces.
void swapPoints (pointField &points)
Swap the stored points.
void swapZones (surfZoneList &zones)
Swap the stored zones.
void writeStats (Ostream &os) const
void operator= (const MeshedSurface< face > &surf)
Copy assignment.
void operator= (MeshedSurface< face > &&surf)
Move assignment.
operator MeshedSurfaceProxy< face > () const
Conversion operator to MeshedSurfaceProxy.
Public Member Functions inherited from PrimitivePatch< face,::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< face > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (::Foam::List< face > &&faces, const Field< point > &points)
Construct from components, transferring faces.
PrimitivePatch (::Foam::List< face > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< face,::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< point > & faceNormals () const
Return face unit normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< face,::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< face >
constexpr List () noexcept
Null constructor.
List (const label len)
Construct with given size.
List (const label len, const face &val)
Construct with given size and value for all elements.
List (const label len, const zero)
Construct with given size initializing all elements to zero.
List (const one, const face &val)
Construct with length=1, copying the value as the only content.
List (const one, face &&val)
Construct with length=1, moving the value as the only content.
List (const one, const zero)
Construct with length=1, initializing content to zero.
List (const List< face > &a)
Copy construct from list.
List (const UList< face > &a)
Copy construct contents from list.
List (List< face > &a, bool reuse)
Construct as copy or re-use as specified.
List (const UList< face > &list, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
List (const FixedList< face, N > &list)
Construct as copy of FixedList<T, N>
List (const PtrList< face > &list)
Construct as copy of PtrList<T>
List (const SLList< face > &list)
Construct as copy of SLList<T>
List (const IndirectListBase< face, Addr > &list)
Construct as copy of IndirectList contents.
List (std::initializer_list< face > list)
Construct from an initializer list.
List (List< face > &&list)
Move construct from List.
List (DynamicList< face, SizeMin > &&list)
Move construct from DynamicList.
List (SortableList< face > &&list)
Move construct from SortableList.
List (SLList< face > &&list)
Move construct from SLList.
List (Istream &is)
Construct from Istream.
autoPtr< List< face > > clone () const
Clone.
~List ()
Destructor.
void resize (const label newSize)
Adjust allocated size of list.
void resize (const label newSize, const face &val)
Adjust allocated size of list and set val for new elements.
void setSize (const label newSize)
Alias for resize(const label)
void setSize (const label newSize, const face &val)
Alias for resize(const label, const T&)
void clear ()
Clear the list, i.e. set size to zero.
void append (const face &val)
Append an element at the end of the list.
void append (face &&val)
Move append an element at the end of the list.
void append (const UList< face > &list)
Append a List to the end of this list.
void append (const IndirectListBase< face, Addr > &list)
Append IndirectList contents at the end of this list.
void transfer (List< face > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (DynamicList< face, SizeMin > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (SortableList< face > &list)
Transfer the contents of the argument List into this list and annul the argument list.
face & newElmt (const label i)
Return subscript-checked element of UList and resizing the list if required.
void operator= (const UList< face > &a)
Assignment to UList operator. Takes linear time.
void operator= (const List< face > &list)
Assignment operator. Takes linear time.
void operator= (const SLList< face > &list)
Assignment to SLList operator. Takes linear time.
void operator= (const IndirectListBase< face, Addr > &list)
Assignment from IndirectList. Takes linear time.
void operator= (std::initializer_list< face > list)
Assignment to an initializer list.
void operator= (const face &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (List< face > &&list)
Move assignment. Takes constant time.
void operator= (DynamicList< face, SizeMin > &&list)
Move assignment. Takes constant time.
void operator= (SortableList< face > &&list)
Move assignment. Takes constant time.
void operator= (SLList< face > &&list)
Move assignment. Takes constant time.
void shallowCopy (const UList< face > &)=delete
No shallowCopy permitted.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type set (const label i, bool val=true)
A bitSet::set() method for a list of bool.
Public Member Functions inherited from UList< face >
label size () const noexcept
The number of elements in the UList.
void writeEntry (const word &keyword, Ostream &os) const
Write the List as a dictionary entry with keyword.
void operator= (const face &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
constexpr UList () noexcept
Null constructor.
UList (face *__restrict__ v, label size) noexcept
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const face & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
face & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const face & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
face & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
std::streamsize byteSize () const
Return the binary size in number of characters of the UList if the element is a primitive type.
const face * cdata () const
Return a const pointer to the first data element.
face * data ()
Return a pointer to the first data element.
face & first ()
Return the first element of the list.
const face & first () const
Return first element of the list.
face & last ()
Return the last element of the list.
const face & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is within valid range [0,size].
void checkIndex (const label i) const
Check index is within valid range [0,size)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const face &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const face &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const face &val, const label start=0) const
True if the value if found in the list.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element. Fatal on an empty list.
void swapLast (const label i)
Swap element with the last element. Fatal on an empty list.
void shallowCopy (const UList< face > &list)
Copy the pointer held by the given UList.
void deepCopy (const UList< face > &list)
Copy elements of the given UList.
face & operator[] (const label i)
Return element of UList.
const face & operator[] (const label i) const
Return element of constant UList.
UList< face > operator[] (const labelRange &range)
Return (start,size) subset from UList with non-const access.
const UList< face > operator[] (const labelRange &range) const
Return (start,size) subset from UList with const access.
operator const Foam::List< face > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
bool empty () const noexcept
True if the UList is empty (ie, size() is zero)
void swap (UList< face > &list)
Swap content with another UList of the same type in constant time.
bool operator== (const UList< face > &a) const
Equality operation on ULists of the same type.
bool operator!= (const UList< face > &a) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< face > &list) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< face > &a) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< face > &a) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< face > &a) const
Return true if !(a < b). Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type test (const label i) const
A bitSet::test() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type get (const label i) const
A bitSet::get() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type unset (const label i)
A bitSet::unset() method for a list of bool.
Public Member Functions inherited from surfaceFormatsCore
surfaceFormatsCore ()=default
Construct null.
virtual ~surfaceFormatsCore ()=default
Destructor.
Protected Member Functions
cuttingPlane (const plane &pln)
Construct from a plane description without any cutting.
virtual void performCut (const primitiveMesh &mesh, const bool triangulate, bitSet &&cellIdLabels)
Cut mesh, restricted to a list of cells.
void checkOverlap (const word callerName, const boundBox &meshBounds, const boundBox &userBounds) const
Check and warn if bounding boxes do not intersect, and if the plane does not intersect the bounding boxes.
bitSet cellSelection (const polyMesh &mesh, const boundBox &userBounds, const wordRes &zoneNames, const word callerName, const bool warn) const
Define cell selection from bounding-box and zones.
Protected Member Functions inherited from cuttingSurfaceBase
template<class EdgeOrientIntersect , class EdgeAlphaIntersect >
void walkCellCuts (const primitiveMesh &mesh, const bitSet &cellCuts, const EdgeOrientIntersect &edgeOrientIntersect, const EdgeAlphaIntersect &edgeAlphaIntersect, const bool triangulate, label nFaceCuts=0)
Walk cell cuts to create faces.
virtual void performCut (const primitiveMesh &mesh, const bool triangulate, const labelUList &cellIdLabels)
Cut mesh, restricted to a list of cells.
virtual void performCut (const primitiveMesh &mesh, const bool triangulate, const bitSet &cellSelectionMask=bitSet())
Cut mesh, restricted to a list of cells.
virtual void remapFaces (const labelUList &faceMap)
Remap action on triangulation or cleanup.
Protected Member Functions inherited from MeshedSurface< face >
void transcribe (MeshedSurface< face > &surf)
Transfer points/zones from 'face' to other other shapes.
void checkZones ()
Basic sanity check on zones.
pointField & storedPoints ()
Non-const access to global points.
List< face > & storedFaces ()
Non-const access to the faces.
surfZoneList & storedZones ()
Non-const access to the zones.
void sortFacesAndStore (DynamicList< face > &unsortedFaces, DynamicList< label > &zoneIds, const bool sorted)
Sort faces by zones and store sorted faces.
Protected Member Functions inherited from UList< face >
void size (const label n) noexcept
Override size to be inconsistent with allocated storage.
void writeEntry (Ostream &os) const
Write the UList with its compound type.
labelRange validateRange (const labelRange &range) const
Return a validated (start,size) subset range, which means that it always addresses a valid section of the list.
UList< face > & operator= (const UList< face > &)=delete
No copy assignment (default: shallow copy)
Additional Inherited Members
Public Types inherited from plane
enum side { FRONT = 1, BACK = -1, NORMAL = 1, FLIP = -1 }
Side of the plane.
Public Types inherited from MeshedSurface< face >
typedef face FaceType
Face type used.
Public Types inherited from PrimitivePatch< face,::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef face FaceType
typedef ::Foam::List< face > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< face >
typedef SubList< face > subList
Declare type of subList.
Public Types inherited from UList< face >
typedef face value_type
The value type the list contains.
typedef face * pointer
The pointer type for non-const access to value_type items.
typedef const face * const_pointer
The pointer type for const access to value_type items.
typedef face & reference
The type used for storing into value_type objects.
typedef const face & const_reference
The type used for reading from constant value_type objects.
typedef face * iterator
Random access iterator for traversing a UList.
typedef const face * const_iterator
Random access iterator for traversing a UList.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Static Public Member Functions inherited from MeshedSurface< face >
static void write (const fileName &name, const MeshedSurface< face > &surf, const dictionary &options=dictionary::null)
Write to file, selecting writer based on its extension.
static void write (const fileName &name, const word &ext, const MeshedSurface< face > &surf, const dictionary &options=dictionary::null)
Write to file, selecting writer based on the given extension.
static bool canRead (const fileName &name, bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, bool verbose=false)
Can we write this file format?
static wordHashSet readTypes ()
Known readable file-types.
static wordHashSet writeTypes ()
Known writable file-types.
static autoPtr< MeshedSurface > New (const fileName &name, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< MeshedSurface > New (const fileName &name)
Select constructed from filename (implicit extension)
Static Public Member Functions inherited from List< face >
static const List< face > & null ()
Return a null List.
Static Public Member Functions inherited from UList< face >
static const UList< face > & null ()
Return a UList reference to a nullObject.
static constexpr label max_size () noexcept
The size of the largest possible UList.
Static Public Member Functions inherited from surfaceFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Helper function when checking if a file extension is supported.
static fileName localMeshFileName (const word &surfName=word::null)
Return the local file name (within time directory)
static fileName findMeshInstance (const Time &, const word &surfName=word::null)
Find instance with surfName.
static fileName findMeshFile (const Time &, const word &surfName=word::null)
Find mesh file with surfName.
Static Public Attributes inherited from cuttingSurfaceBase
static int debug
Debug information.
Static Public Attributes inherited from surfaceFormatsCore
static word nativeExt
The file extension corresponding to 'native' surface format.
Protected Types inherited from cuttingSurfaceBase
typedef MeshedSurface< face > MeshStorage
Typedef for convenience.
Static Protected Member Functions inherited from cuttingSurfaceBase
static void checkOverlap (const word callerName, const boundBox &meshBounds, const boundBox &userBounds)
Check and warn if bounding boxes do not intersect.
static bitSet cellSelection (const polyMesh &mesh, const boundBox &userBounds, const wordRes &zoneNames, boundBox &meshBounds)
Define cell selection from bounding-box and zones.
static bitSet cellSelection (const polyMesh &mesh, const boundBox &userBounds, const wordRes &zoneNames, const word callerName, const bool warn)
Define cell selection from bounding-box and zones.
Static Protected Member Functions inherited from surfaceFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Read non-empty and non-comment line.
template<class Container >
static List< surfZone > oneZone (const Container &container, const word &name="zone0")
Return a surfZone list with a single entry, the size of which corresponds to that of the container.
Protected Attributes inherited from cuttingSurfaceBase
labelList meshCells_
List of the cells cut.
Detailed Description
Constructs cutting plane through a mesh.
No attempt at resolving degenerate cases. Since the cut faces can be quite ugly, they will often be triangulated.
Source files
cuttingPlane.H
cuttingPlane.C
Definition at line 54 of file cuttingPlane.H.
Constructor & Destructor Documentation
cuttingPlane (const plane & pln) protected
Construct from a plane description without any cutting.
Definition at line 25 of file cuttingPlane.C.
cuttingPlane (const plane & pln, const primitiveMesh & mesh, const bool triangulate, const bitSet & cellIdLabels = bitSet())
Construct from plane and mesh reference, possibly restricted to a list of cells.
Definition at line 32 of file cuttingPlane.C.
cuttingPlane (const plane & pln, const primitiveMesh & mesh, const bool triangulate, bitSet && cellIdLabels)
Construct from plane and mesh reference, possibly restricted to a list of cells.
Definition at line 46 of file cuttingPlane.C.
cuttingPlane (const plane & pln, const primitiveMesh & mesh, const bool triangulate, const labelUList & cellIdLabels)
Construct from plane and mesh reference, possibly restricted to a list of cells.
Definition at line 60 of file cuttingPlane.C.
Member Function Documentation
void performCut (const primitiveMesh & mesh, const bool triangulate, bitSet && cellIdLabels) protected virtual
Cut mesh, restricted to a list of cells.
Reclaim memory for cellIdLabels
Implements cuttingSurfaceBase.
Definition at line 76 of file cuttingPlane.C.
void checkOverlap (const word callerName, const boundBox & meshBounds, const boundBox & userBounds) const protected
Check and warn if bounding boxes do not intersect, and if the plane does not intersect the bounding boxes.
Definition at line 27 of file cuttingPlaneSelection.C.
References cuttingSurfaceBase::checkOverlap(), Foam::endl(), boundBox::intersects(), Foam::nl, boundBox::valid(), and WarningInFunction.
Foam::bitSet cellSelection (const polyMesh & mesh, const boundBox & userBounds, const wordRes & zoneNames, const word callerName, const bool warn) const protected
Define cell selection from bounding-box and zones.
Parameters
userBounds Optionally user-specified bounding box
zoneNames Optionally user-specified zone names
warn Check and warn if the plane does not intersect with the bounds of the mesh (or submesh) or if the bounding box does not overlap with the mesh (or submesh)
Returns
A set of nCells size with the selected cells or an empty set if no bounding-box or zones were specified.
Definition at line 60 of file cuttingPlaneSelection.C.
const plane& planeDesc () const inline
The plane used.
Definition at line 191 of file cuttingPlane.H.
plane& planeDesc () inline
The plane used. Non-const access.
Definition at line 199 of file cuttingPlane.H.
void operator= (const cuttingPlane & rhs)
Copy assignment.
Definition at line 142 of file cuttingPlane.C.
The documentation for this class was generated from the following files:
src/sampling/surface/cutting/cuttingPlane.H
src/sampling/surface/cutting/cuttingPlane.C
src/sampling/surface/cutting/cuttingPlaneCuts.C
src/sampling/surface/cutting/cuttingPlaneSelection.C