OpenFOAM: fieldInfo Class Reference
fieldInfo Class Reference
Helper class to store a wordRe and label used by Foam::functionObjects::fieldSelection.
Public Member Functions
fieldInfo ()
Null constructor.
fieldInfo (const wordRe &name, const label component=-1)
Construct from components.
fieldInfo (Istream &is)
Construct from stream.
~fieldInfo ()=default
Destructor.
const wordRe & name () const
label component () const
Switch & found () const
Friends
bool operator== (const fieldInfo &a, const fieldInfo &b)
bool operator!= (const fieldInfo &a, const fieldInfo &b)
Istream & operator>> (Istream &is, fieldInfo &fi)
Ostream & operator<< (Ostream &os, const fieldInfo &fi)
Detailed Description
Helper class to store a wordRe and label used by Foam::functionObjects::fieldSelection.
Definition at line 50 of file fieldInfo.H.
Constructor & Destructor Documentation
fieldInfo () inline
Null constructor.
Definition at line 77 of file fieldInfo.H.
fieldInfo (const wordRe & name, const label component = -1) inline
Construct from components.
Definition at line 88 of file fieldInfo.H.
fieldInfo (Istream & is) inline
Construct from stream.
Definition at line 98 of file fieldInfo.H.
~fieldInfo () default
Destructor.
Member Function Documentation
const wordRe& name () const inline
Definition at line 114 of file fieldInfo.H.
Referenced by fileFieldSelection::addFromFile(), fieldSelection::addRegistered(), and fieldSelection::filters().
label component () const inline
Definition at line 119 of file fieldInfo.H.
Referenced by fieldSelection::addRegistered().
Switch& found () const inline
Definition at line 124 of file fieldInfo.H.
Referenced by fileFieldSelection::addFromFile(), and fieldSelection::addRegistered().
Friends And Related Function Documentation
bool operator== (const fieldInfo & a, const fieldInfo & b) friend
Definition at line 129 of file fieldInfo.H.
bool operator!= (const fieldInfo & a, const fieldInfo & b) friend
Definition at line 137 of file fieldInfo.H.
Istream& operator>> (Istream & is, fieldInfo & fi) friend
Definition at line 145 of file fieldInfo.H.
Ostream& operator<< (Ostream & os, const fieldInfo & fi) friend
Definition at line 150 of file fieldInfo.H.
The documentation for this class was generated from the following file:
src/finiteVolume/functionObjects/fieldSelections/fieldSelection/fieldInfo.H