OpenFOAM: edge Class Reference
edge Class Reference
An edge is a list of two point labels. The functionality it provides supports the discretisation on a 2-D flat mesh.
Classes
struct Hash
Hashing function class for edge (commutative)
Public Member Functions
edge ()
Construct null with invalid point labels (-1)
edge (const label from, const label to)
Construct from two point labels.
edge (const labelPair &pair)
Construct from pair of labels.
edge (const FixedList< label, 2 > &list)
Construct from list.
edge (const label from, const label to, const bool doSort)
Construct from two point labels, sorted with first less-than second.
edge (const FixedList< label, 2 > &list, const bool doSort)
Construct from list, sorted with first less-than second.
edge (Istream &is)
Construct from Istream.
label start () const
Return start (first) vertex label.
label & start ()
Return start (first) vertex label.
label end () const
Return end (last/second) vertex label.
label & end ()
Return end (last/second) vertex label.
edge reverseEdge () const
Return reverse edge as copy.
label minVertex () const
Return the smallest point label used by the edge.
label maxVertex () const
Return the largest point label used by the edge.
bool valid () const
Return true if the vertices are unique and non-negative.
bool found (const label pointLabel) const
Return true if point label is found in edge.
label which (const label pointLabel) const
Return local index (0,1) of point label in edge -1 on failure.
bool connects (const edge &other) const
Do the edges share a common vertex index?
label commonVertex (const edge &other) const
Return vertex common with other edge or -1 on failure.
label otherVertex (const label pointLabel) const
Given the point label for one vertex, return the other one.
label collapse ()
'Collapse' edge by marking duplicate point labels as '-1', the lower vertex is retained.
label count () const
Return the number of unique, valid (non -1) point labels.
bool empty () const
Return true if edge has no valid point labels.
void clear ()
'Clears' edge by setting both ends to invalid point labels.
bool insert (const label index)
Fill any open slot with the index if it did not previously exist.
template<class InputIterator >
label insert (InputIterator begIter, InputIterator endIter)
Insert values, using begin/end iterators.
label insert (std::initializer_list< label > list)
Fill open slots with the indices if they did not previously exist.
template<unsigned N>
label insert (const FixedList< label, N > &list)
Fill open slots with the indices if they did not previously exist.
label insert (const labelUList &list)
Fill open slots with the indices if they did not previously exist.
label erase (const label index)
Remove an existing index from the edge and set its location to '-1'.
template<class InputIterator >
label erase (InputIterator begIter, InputIterator endIter)
Remove values, using begin/end iterators.
label erase (std::initializer_list< label > list)
Remove existing indices from the edge and set locations to '-1'.
template<unsigned N>
label erase (const FixedList< label, N > &list)
Remove existing indices from the edge and set locations to '-1'.
label erase (const labelUList &list)
Remove existing indices from the edge and set locations to '-1'.
point centre (const UList< point > &pts) const
Return centre point (centroid) of the edge.
vector vec (const UList< point > &pts) const
Return the vector (end - start)
vector unitVec (const UList< point > &pts) const
Return the unit vector (end - start)
scalar mag (const UList< point > &pts) const
Return scalar magnitude of the edge.
linePointRef line (const UList< point > &pts) const
Return edge line.
label & operator[] (const label i)
Return edge element. Index should be limited to 0/1.
const label & operator[] (const label i) const
Return constant edge element. Index should be limited to 0/1.
unsigned hashval (unsigned seed=0) const
The (commutative) hash-value for edge.
template<class InputIterator>
Foam::label insert (InputIterator begIter, InputIterator endIter)
template<unsigned N>
Foam::label insert (const FixedList< label, N > &list)
template<class InputIterator>
Foam::label erase (InputIterator begIter, InputIterator endIter)
template<unsigned N>
Foam::label erase (const FixedList< label, N > &list)
Public Member Functions inherited from Pair< T >
Pair ()=default
Construct null.
Pair (const T &f, const T &s)
Copy construct from components.
Pair (T &&f, T &&s)
Move construct from components.
Pair (const std::pair< T, T > &vals)
Copy construct from std::pair.
Pair (std::pair< T, T > &&vals)
Move construct from std::pair.
Pair (const FixedList< T, 2 > &list)
Copy construct FixedList of two items.
Pair (const T &f, const T &s, const bool doSort)
Copy construct, optionally sorted with first less-than second.
Pair (const FixedList< T, 2 > &list, const bool doSort)
Copy construct, optionally sorted with first less-than second.
Pair (Istream &is)
Construct from Istream.
const T & second () const noexcept
Return second element, which is also the last element.
T & second () noexcept
Return second element, which is also the last element.
const T & other (const T &a) const
Return other element.
bool sorted () const
True if first() is less-than second()
void flip ()
Flip the Pair in-place.
void sort ()
Sort so that first() is less-than second()
Public Member Functions inherited from FixedList< T, 2 >
void writeEntry (const word &keyword, Ostream &os) const
Write the list as a dictionary entry with keyword.
FixedList ()=default
Null constructor.
FixedList (const T &val)
Construct and initialize all entries to given value.
FixedList (const zero)
Construct and initialize all entries to zero.
FixedList (const T list[N])
Copy construct from C-array.
FixedList (const FixedList< T, N > &list)
Copy constructor.
FixedList (FixedList< T, N > &&list)
Move construct by using move assignment for the individual list elements.
FixedList (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
FixedList (std::initializer_list< T > list)
Construct from an initializer list.
FixedList (const UList< T > &list)
Construct from UList.
FixedList (const SLList< T > &list)
Construct from SLList.
FixedList (Istream &is)
Construct from Istream.
autoPtr< FixedList< T, N > > clone () const
Clone.
const T * cdata () const noexcept
Return a const pointer to the first data element.
T * data () noexcept
Return a pointer to the first data element.
T & first () noexcept
The first element of the list, position [0].
const T & first () const noexcept
The first element of the list, position [0].
T & last () noexcept
The last element of the list, position [N-1].
const T & last () const noexcept
The last element of the list, position [N-1].
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const T & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
T & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const T & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
T & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is identical to template parameter N.
void checkIndex (const label i) const
Check index is within valid range [0,N)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const T &val, const label start=0) const
Find index of the first occurence of the value.
bool found (const T &val, const label start=0) const
True if the value if found in the list. Linear search.
void resize (const label n)
Dummy resize function, to make FixedList consistent with List.
void setSize (const label n)
Dummy setSize function, to make FixedList consistent with List.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element.
void swapLast (const label i)
Swap element with the last element.
void transfer (FixedList< T, N > &list)
Transfer by swapping using a move assignment for the content of the individual list elements.
T & operator[] (const label i)
Return element of FixedList.
const T & operator[] (const label i) const
Return element of constant FixedList.
void operator= (const T list[N])
Assignment to array operator. Takes linear time.
void operator= (const UList< T > &list)
Assignment to UList operator. Takes linear time.
void operator= (const SLList< T > &list)
Assignment to SLList operator. Takes linear time.
void operator= (std::initializer_list< T > list)
Assignment to an initializer list. Takes linear time.
void operator= (const T &val)
Assignment of all entries to the given value.
void operator= (const FixedList< T, N > &list)
Copy assignment.
void operator= (FixedList< T, N > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the FixedList.
const_iterator begin () const
Return const_iterator to begin traversing the constant FixedList.
iterator end ()
Return an iterator to end traversing the FixedList.
const_iterator end () const
Return const_iterator to end traversing the constant FixedList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant FixedList.
const_iterator cend () const
Return const_iterator to end traversing the constant FixedList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the FixedList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the FixedList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing FixedList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing FixedList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing FixedList.
void swap (FixedList< T, N > &list)
Swap lists by swapping the content of the individual list elements.
bool operator== (const FixedList< T, N > &list) const
Equality operation on FixedLists of the same type.
bool operator!= (const FixedList< T, N > &list) const
The opposite of the equality operation. Takes linear time.
bool operator< (const FixedList< T, N > &list) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator> (const FixedList< T, N > &list) const
Compare two FixedLists lexicographically. Takes linear time.
bool operator<= (const FixedList< T, N > &list) const
Return true if !(a > b). Takes linear time.
bool operator>= (const FixedList< T, N > &list) const
Return true if !(a < b). Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
Static Public Member Functions
static int compare (const edge &a, const edge &b)
Compare edges.
Static Public Member Functions inherited from Pair< T >
static int compare (const Pair< T > &a, const Pair< T > &b)
Compare Pairs.
Static Public Member Functions inherited from FixedList< T, 2 >
static const FixedList< T, N > & null ()
Return a null FixedList.
static constexpr bool empty () noexcept
Always false since zero-sized FixedList is compile-time disabled.
static constexpr label size () noexcept
Return the number of elements in the FixedList.
static constexpr unsigned max_size () noexcept
The dimensioned size (template parameter N) of the FixedList.
Static Public Attributes
static const char *const typeName = "edge"
Additional Inherited Members
Public Types inherited from FixedList< T, 2 >
typedef T value_type
The value type the FixedList contains.
typedef T * pointer
The pointer type for non-const access to value_type items.
typedef const T * const_pointer
The pointer type for const access to value_type items.
typedef T & reference
The type used for storing into value_type objects.
typedef const T & const_reference
The type used for reading from constant value_type objects.
typedef T * iterator
Random access iterator for traversing FixedList.
typedef const T * const_iterator
Random access iterator for traversing FixedList.
typedef label size_type
The type to represent the size of a FixedList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Protected Member Functions inherited from FixedList< T, 2 >
void writeEntry (Ostream &os) const
Write the FixedList with its compound type.
Detailed Description
An edge is a list of two point labels. The functionality it provides supports the discretisation on a 2-D flat mesh.
The edge is implemented as a Pair/FixedList of labels. As well as geometrically relevant methods, it also provides methods similar to HashSet for additional convenience. Valid point labels are always non-negative (since they correspond to addressing within the mesh). The value '-1' is used to tag invalid point labels that correspond conceptually to open 'slots', which can be filled with a HashSet-like functionality.
Source files
edge.H
edge.C
edgeI.H
Definition at line 59 of file edge.H.
Constructor & Destructor Documentation
edge () inline
Construct null with invalid point labels (-1)
Definition at line 34 of file edgeI.H.
References Pair< T >::compare().
edge (const label from, const label to) inline
Construct from two point labels.
Definition at line 40 of file edgeI.H.
edge (const labelPair & pair) inline
Construct from pair of labels.
Definition at line 46 of file edgeI.H.
edge (const FixedList< label, 2 > & list) inline
Construct from list.
Definition at line 52 of file edgeI.H.
edge (const label from, const label to, const bool doSort) inline
Construct from two point labels, sorted with first less-than second.
Definition at line 58 of file edgeI.H.
edge (const FixedList< label, 2 > & list, const bool doSort) inline
Construct from list, sorted with first less-than second.
Definition at line 64 of file edgeI.H.
edge (Istream & is) inline
Construct from Istream.
Definition at line 70 of file edgeI.H.
Member Function Documentation
Foam::label start () const inline
Return start (first) vertex label.
Definition at line 78 of file edgeI.H.
Referenced by PatchTools::checkOrientation(), PrimitivePatch< Face, FaceList, PointField, PointType >::checkTopology(), triSurfaceTools::getVertexTriangles(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), surfaceFeatures::nearestSurfEdge(), Foam::polyMeshZipUpCells(), PatchTools::sortedEdgeFaces(), PatchTools::sortedPointEdges(), extendedEdgeMesh::sortPointsAndEdges(), and PrimitivePatch< Face, FaceList, PointField, PointType >::whichEdge().
Foam::label & start () inline
Return start (first) vertex label.
Definition at line 83 of file edgeI.H.
Foam::label end () const inline
Return end (last/second) vertex label.
Definition at line 89 of file edgeI.H.
Referenced by PatchTools::checkOrientation(), PrimitivePatch< Face, FaceList, PointField, PointType >::checkTopology(), triSurfaceTools::getVertexTriangles(), surfaceFeatures::nearestSurfEdge(), Foam::polyMeshZipUpCells(), PatchTools::sortedPointEdges(), and extendedEdgeMesh::sortPointsAndEdges().
Foam::label & end () inline
Return end (last/second) vertex label.
Definition at line 95 of file edgeI.H.
Foam::edge reverseEdge () const inline
Return reverse edge as copy.
No special handling of negative point labels.
Definition at line 208 of file edgeI.H.
Foam::label minVertex () const inline
Return the smallest point label used by the edge.
No special handling of negative point labels.
Definition at line 101 of file edgeI.H.
Foam::label maxVertex () const inline
Return the largest point label used by the edge.
No special handling of negative point labels.
Definition at line 107 of file edgeI.H.
bool valid () const inline
Return true if the vertices are unique and non-negative.
Definition at line 113 of file edgeI.H.
bool found (const label pointLabel) const inline
Return true if point label is found in edge.
Always false for a negative label.
Definition at line 119 of file edgeI.H.
Referenced by edge::commonVertex().
Foam::label which (const label pointLabel) const inline
Return local index (0,1) of point label in edge -1 on failure.
Always return -1 for a negative label.
Definition at line 130 of file edgeI.H.
bool connects (const edge & other) const inline
Do the edges share a common vertex index?
Negative point labels never connect.
Definition at line 149 of file edgeI.H.
Foam::label commonVertex (const edge & other) const inline
Return vertex common with other edge or -1 on failure.
Negative point labels are never considered common between edges.
Definition at line 155 of file edgeI.H.
References edge::found().
Foam::label otherVertex (const label pointLabel) const inline
Given the point label for one vertex, return the other one.
No special treatment for negative point labels.
Definition at line 171 of file edgeI.H.
Foam::label collapse () inline
'Collapse' edge by marking duplicate point labels as '-1', the lower vertex is retained.
Return the effective size after collapsing.
Definition at line 187 of file edgeI.H.
Foam::label count () const inline
Return the number of unique, valid (non -1) point labels.
Similar to a HashTable::size().
Definition at line 221 of file edgeI.H.
bool empty () const inline
Return true if edge has no valid point labels.
Definition at line 237 of file edgeI.H.
void clear () inline
'Clears' edge by setting both ends to invalid point labels.
Definition at line 214 of file edgeI.H.
bool insert (const label index) inline
Fill any open slot with the index if it did not previously exist.
Returns true on success. A negative label never inserts. Similar to a HashTable::insert().
Definition at line 243 of file edgeI.H.
Referenced by PatchTools::matchEdges().
label insert (InputIterator begIter, InputIterator endIter) inline
Insert values, using begin/end iterators.
Foam::label insert (std::initializer_list< label > list) inline
Fill open slots with the indices if they did not previously exist.
Returns true on success. Negative labels never insert. Return the number of slots filled. Similar to a HashTable::insert().
Definition at line 298 of file edgeI.H.
label insert (const FixedList< label, N > & list) inline
Fill open slots with the indices if they did not previously exist.
Returns true on success. Negative labels never insert. Return the number of slots filled. Similar to a HashTable::insert().
Foam::label insert (const labelUList & list) inline
Fill open slots with the indices if they did not previously exist.
Returns true on success. Negative labels never insert. Return the number of slots filled. Similar to a HashTable::insert().
Definition at line 311 of file edgeI.H.
References FixedList< T, N >::begin(), FixedList< T, N >::end(), and insert().
Foam::label erase (const label index) inline
Remove an existing index from the edge and set its location to '-1'.
Returns the number of changes. A negative label never removes. Similar to a HashTable::erase().
Definition at line 317 of file edgeI.H.
References UList< T >::begin(), UList< T >::end(), and insert().
label erase (InputIterator begIter, InputIterator endIter) inline
Remove values, using begin/end iterators.
Foam::label erase (std::initializer_list< label > list) inline
Remove existing indices from the edge and set locations to '-1'.
Returns the number of changes.
Definition at line 364 of file edgeI.H.
label erase (const FixedList< label, N > & list) inline
Remove existing indices from the edge and set locations to '-1'.
Returns the number of changes.
Foam::label erase (const labelUList & list) inline
Remove existing indices from the edge and set locations to '-1'.
Returns the number of changes.
Definition at line 377 of file edgeI.H.
References FixedList< T, N >::begin(), FixedList< T, N >::end(), and erase().
Foam::point centre (const UList< point > & pts) const inline
Return centre point (centroid) of the edge.
No special handling of negative point labels.
Definition at line 385 of file edgeI.H.
References UList< T >::begin(), UList< T >::end(), and erase().
Referenced by surfaceFeatures::nearestEdges(), and surfaceFeatures::nearestFeatEdge().
Foam::vector vec (const UList< point > & pts) const inline
Return the vector (end - start)
No special handling of negative point labels.
Definition at line 400 of file edgeI.H.
Referenced by surfaceFeatures::nearestEdges(), surfaceFeatures::nearestFeatEdge(), surfaceFeatures::nearestSamples(), extendedEdgeMesh::sortPointsAndEdges(), and cuttingSurfaceBase::walkCellCuts().
Foam::vector unitVec (const UList< point > & pts) const inline
Return the unit vector (end - start)
No special handling of negative point labels.
Definition at line 415 of file edgeI.H.
Referenced by PatchTools::sortedEdgeFaces().
Foam::scalar mag (const UList< point > & pts) const inline
Return scalar magnitude of the edge.
No special handling of negative point labels.
Definition at line 433 of file edgeI.H.
Referenced by triSurfaceTools::minEdge(), and surfaceFeatures::trimFeatures().
Foam::linePointRef line (const UList< point > & pts) const inline
Return edge line.
No special handling of negative point labels.
Definition at line 439 of file edgeI.H.
References Foam::mag().
Referenced by surfaceFeatures::nearestSamples(), and surfaceFeatures::nearestSurfEdge().
int compare (const edge & a, const edge & b) inline static
Compare edges.
Returns
0: different
+1: identical values and order used
-1: identical values, but in different order
Definition at line 26 of file edgeI.H.
Referenced by Foam::operator!=().
Foam::label & operator[] (const label i) inline
Return edge element. Index should be limited to 0/1.
Definition at line 456 of file edgeI.H.
const Foam::label & operator[] (const label i) const inline
Return constant edge element. Index should be limited to 0/1.
Definition at line 469 of file edgeI.H.
unsigned hashval (unsigned seed = 0) const inline
The (commutative) hash-value for edge.
Definition at line 393 of file edge.H.
Foam::label insert (InputIterator begIter, InputIterator endIter) inline
Definition at line 276 of file edgeI.H.
Foam::label insert (const FixedList< label, N > & list) inline
Definition at line 305 of file edgeI.H.
References insert().
Foam::label erase (InputIterator begIter, InputIterator endIter) inline
Definition at line 345 of file edgeI.H.
Foam::label erase (const FixedList< label, N > & list) inline
Definition at line 371 of file edgeI.H.
References erase().
Member Data Documentation
const char *const typeName = "edge" static
Definition at line 67 of file edge.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/meshShapes/edge/edge.H
src/OpenFOAM/meshes/meshShapes/edge/edge.C
src/OpenFOAM/meshes/meshShapes/edge/edgeI.H