OpenFOAM: externalPointEdgePoint Class Reference
externalPointEdgePoint Class Reference
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Classes
class trackingData
Class used to pass data into container.
Public Member Functions
externalPointEdgePoint ()
Construct null.
externalPointEdgePoint (const point &, const scalar)
Construct from origin, distance.
externalPointEdgePoint (const externalPointEdgePoint &)
Construct as copy.
const point & origin () const
scalar distSqr () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const externalPointEdgePoint &, const scalar tol, TrackingData &td) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert origin to relative vector to leaving point.
template<class TrackingData >
void enterDomain (const polyPatch &patch, const label patchPointi, const point &pos, TrackingData &td)
Convert relative origin to absolute by adding entering point.
template<class TrackingData >
void transform (const tensor &rotTensor, TrackingData &td)
Apply rotation matrix to origin.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const label edgeI, const externalPointEdgePoint &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on point.
template<class TrackingData >
bool updatePoint (const polyMesh &mesh, const label pointi, const externalPointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updatePoint (const externalPointEdgePoint &newPointInfo, const scalar tol, TrackingData &td)
Influence of different value on same point.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const label edgeI, const label pointi, const externalPointEdgePoint &pointInfo, const scalar tol, TrackingData &td)
Influence of point on edge.
template<class TrackingData >
bool equal (const externalPointEdgePoint &, TrackingData &td) const
Equivalent to operator== with TrackingData.
bool operator== (const externalPointEdgePoint &) const
bool operator!= (const externalPointEdgePoint &) const
Friends
Ostream & operator<< (Ostream &, const externalPointEdgePoint &)
Istream & operator>> (Istream &, externalPointEdgePoint &)
Detailed Description
Holds information regarding nearest wall point. Used in PointEdgeWave. (so not standard FaceCellWave) To be used in wall distance calculation.
Source files
externalPointEdgePoint.H
externalPointEdgePointI.H
externalPointEdgePoint.C
Definition at line 59 of file externalPointEdgePoint.H.
Constructor & Destructor Documentation
externalPointEdgePoint () inline
Construct null.
Definition at line 113 of file externalPointEdgePointI.H.
externalPointEdgePoint (const point & origin, const scalar distSqr) inline
Construct from origin, distance.
Definition at line 121 of file externalPointEdgePointI.H.
externalPointEdgePoint (const externalPointEdgePoint & wpt) inline
Construct as copy.
Definition at line 132 of file externalPointEdgePointI.H.
Member Function Documentation
const Foam::point & origin () const inline
Definition at line 143 of file externalPointEdgePointI.H.
Foam::scalar distSqr () const inline
Definition at line 149 of file externalPointEdgePointI.H.
References origin_().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 156 of file externalPointEdgePointI.H.
bool sameGeometry (const externalPointEdgePoint & w2, const scalar tol, TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 165 of file externalPointEdgePointI.H.
void leaveDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Convert origin to relative vector to leaving point.
(= point coordinate)
Definition at line 193 of file externalPointEdgePointI.H.
void enterDomain (const polyPatch & patch, const label patchPointi, const point & pos, TrackingData & td) inline
Convert relative origin to absolute by adding entering point.
Definition at line 217 of file externalPointEdgePointI.H.
References origin_(), and Foam::transform().
void transform (const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to origin.
Definition at line 206 of file externalPointEdgePointI.H.
References origin_().
bool updatePoint (const polyMesh & mesh, const label pointi, const label edgeI, const externalPointEdgePoint & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on point.
Definition at line 231 of file externalPointEdgePointI.H.
bool updatePoint (const polyMesh & mesh, const label pointi, const externalPointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
Merge new and old info.
Definition at line 246 of file externalPointEdgePointI.H.
References update().
bool updatePoint (const externalPointEdgePoint & newPointInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same point.
No information about current position whatsoever.
Definition at line 260 of file externalPointEdgePointI.H.
References update().
bool updateEdge (const polyMesh & mesh, const label edgeI, const label pointi, const externalPointEdgePoint & pointInfo, const scalar tol, TrackingData & td) inline
Influence of point on edge.
Definition at line 272 of file externalPointEdgePointI.H.
References update().
bool equal (const externalPointEdgePoint & rhs, TrackingData & td) const inline
Equivalent to operator== with TrackingData.
Definition at line 288 of file externalPointEdgePointI.H.
bool operator== (const externalPointEdgePoint & rhs) const inline
Definition at line 300 of file externalPointEdgePointI.H.
bool operator!= (const externalPointEdgePoint & rhs) const inline
Definition at line 310 of file externalPointEdgePointI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const externalPointEdgePoint &) friend
Istream& operator>> (Istream & , externalPointEdgePoint &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/pointPatchDist/externalPointEdgePoint.H
src/dynamicMesh/pointPatchDist/externalPointEdgePointI.H