OpenFOAM: memorybuf Class Reference
memorybuf Class Reference
A streambuf for memory.
Classes
class in
An input streambuf for memory access.
class out
An output streambuf for memory access.
Protected Member Functions
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
Set position pointer to relative position.
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
Set position pointer to absolute position.
std::streamsize tellg () const
std::streamsize tellp () const
Detailed Description
A streambuf for memory.
A std::streambuf used for memory buffer streams such as UIListStream, UOListStream, etc.
Definition at line 50 of file memoryStreamBuffer.H.
Member Function Documentation
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which = std::ios_base::in|std::ios_base::out) inline protected virtual
Set position pointer to relative position.
Definition at line 60 of file memoryStreamBuffer.H.
References end().
Referenced by memorybuf::seekpos().
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which = std::ios_base::in|std::ios_base::out) inline protected virtual
Set position pointer to absolute position.
Definition at line 124 of file memoryStreamBuffer.H.
References memorybuf::seekoff().
std::streamsize tellg () const inline protected
Returns
the current buffer get position
Definition at line 136 of file memoryStreamBuffer.H.
std::streamsize tellp () const inline protected
Returns
the current buffer put position
Definition at line 144 of file memoryStreamBuffer.H.
Referenced by UOListStreamAllocator::capacity().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/memoryStreamBuffer.H