OpenFOAM: coupledFaPatch Class Reference
coupledFaPatch Class Reference abstract
coupledFaPatch is an abstract base class for patches that couple regions of the computational domain e.g. cyclic, arbitrary interfaces, sliding interfaces and processor-processor links.
Public Member Functions
TypeName ("coupled")
Runtime type information.
coupledFaPatch (const word &name, const labelList &edgeLabels, const label index, const faBoundaryMesh &bm, const label ngbPolyPatchIndex)
Construct from components.
coupledFaPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
Construct from dictionary.
virtual ~coupledFaPatch ()
Destructor.
virtual bool coupled () const
Return true because this patch is coupled.
bool separated () const
Are the coupled planes separated.
const vectorField & separation () const
Return the offset (distance) vector from one side of the couple.
const tensorField & forwardT () const
Return face transformation tensor.
const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
bool parallel () const
Are the cyclic planes parallel.
virtual void initGeometry ()=0
Initialise the calculation of the patch geometry.
virtual void calcGeometry ()=0
Calculate the patch geometry.
virtual void initMovePoints (const pointField &)=0
Initialise the patches for moving points.
virtual void movePoints (const pointField &)=0
Correct patches after moving points.
virtual tmp< vectorField > delta () const =0
Return delta (P to N) vectors across coupled patch.
virtual const labelUList & faceCells () const
Return faceCell addressing: lduInterface virtual function.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const =0
Return the values of the given internal data adjacent to.
virtual void initTransfer (const Pstream::commsTypes commsType, const labelUList &interfaceData) const
Initialise interface data transfer.
virtual tmp< labelField > transfer (const Pstream::commsTypes commsType, const labelUList &interfaceData) const =0
Transfer and return neighbour field.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const
Initialise neighbour field transfer.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &iF) const =0
Return neighbour field.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()=default
Construct null.
virtual ~lduInterface ()=default
Destructor.
Public Member Functions inherited from faPatch
TypeName ("patch")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, faPatch, dictionary,(const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm),(name, dict, index, bm))
faPatch (const word &name, const labelList &edgeLabels, const label index, const faBoundaryMesh &bm, const label ngbPolyPatchIndex)
Construct from components.
faPatch (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
Construct from dictionary.
faPatch (const faPatch &, const faBoundaryMesh &)
Construct as copy, resetting the boundary mesh.
virtual autoPtr< faPatch > clone (const faBoundaryMesh &bm, const labelList &edgeLabels, const label index, const label ngbPolyPatchIndex) const
Construct and return a clone, resetting the edge list.
virtual ~faPatch ()
Destructor.
label nPoints () const
Return number of patch points.
label ngbPolyPatchIndex () const
Return neighbour polyPatch index.
const faBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
label start () const
Patch start in edge list.
virtual label size () const
Patch size.
label whichEdge (const label l) const
Return label of edge in patch from global edge label.
template<class T >
List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
virtual void write (Ostream &) const
Write.
const labelList & pointLabels () const
Return patch point labels.
const labelListList & pointEdges () const
Return patch point-edge addressing.
labelList ngbPolyPatchFaces () const
Return edge neighbour polyPatch faces.
tmp< vectorField > ngbPolyPatchFaceNormals () const
Return normals of neighbour polyPatch faces.
tmp< vectorField > ngbPolyPatchPointNormals () const
Return normals of neighbour polyPatch joined points.
const labelUList & edgeFaces () const
Return edge-face addressing.
const vectorField & edgeCentres () const
Return edge centres.
const vectorField & edgeLengths () const
Return edge length vectors.
const scalarField & magEdgeLengths () const
Return edge length magnitudes.
tmp< vectorField > edgeNormals () const
Return edge normals.
tmp< vectorField > edgeFaceCentres () const
Return neighbour face centres.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return patch edge - neighbour face distances.
void resetEdges (const labelList &)
Reset edge list.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::Patch & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const Type *=nullptr) const
Lookup and return the patchField of the named field from the.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Public Member Functions inherited from List< T >
constexpr List () noexcept
Null constructor.
List (const label len)
Construct with given size.
List (const label len, const T &val)
Construct with given size and value for all elements.
List (const label len, const zero)
Construct with given size initializing all elements to zero.
List (const one, const T &val)
Construct with length=1, copying the value as the only content.
List (const one, T &&val)
Construct with length=1, moving the value as the only content.
List (const one, const zero)
Construct with length=1, initializing content to zero.
List (const List< T > &a)
Copy construct from list.
List (const UList< T > &a)
Copy construct contents from list.
List (List< T > &a, bool reuse)
Construct as copy or re-use as specified.
List (const UList< T > &list, const labelUList &mapAddressing)
Construct as subset.
template<class InputIterator >
List (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
template<unsigned N>
List (const FixedList< T, N > &list)
Construct as copy of FixedList<T, N>
List (const PtrList< T > &list)
Construct as copy of PtrList<T>
List (const SLList< T > &list)
Construct as copy of SLList<T>
template<class Addr >
List (const IndirectListBase< T, Addr > &list)
Construct as copy of IndirectList contents.
List (std::initializer_list< T > list)
Construct from an initializer list.
List (List< T > &&list)
Move construct from List.
template<int SizeMin>
List (DynamicList< T, SizeMin > &&list)
Move construct from DynamicList.
List (SortableList< T > &&list)
Move construct from SortableList.
List (SLList< T > &&list)
Move construct from SLList.
List (Istream &is)
Construct from Istream.
autoPtr< List< T > > clone () const
Clone.
~List ()
Destructor.
void resize (const label newSize)
Adjust allocated size of list.
void resize (const label newSize, const T &val)
Adjust allocated size of list and set val for new elements.
void setSize (const label newSize)
Alias for resize(const label)
void setSize (const label newSize, const T &val)
Alias for resize(const label, const T&)
void clear ()
Clear the list, i.e. set size to zero.
void append (const T &val)
Append an element at the end of the list.
void append (T &&val)
Move append an element at the end of the list.
void append (const UList< T > &list)
Append a List to the end of this list.
template<class Addr >
void append (const IndirectListBase< T, Addr > &list)
Append IndirectList contents at the end of this list.
void transfer (List< T > &list)
Transfer the contents of the argument List into this list and annul the argument list.
template<int SizeMin>
void transfer (DynamicList< T, SizeMin > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (SortableList< T > &list)
Transfer the contents of the argument List into this list and annul the argument list.
T & newElmt (const label i)
Return subscript-checked element of UList and resizing the list if required.
void operator= (const UList< T > &a)
Assignment to UList operator. Takes linear time.
void operator= (const List< T > &list)
Assignment operator. Takes linear time.
void operator= (const SLList< T > &list)
Assignment to SLList operator. Takes linear time.
template<class Addr >
void operator= (const IndirectListBase< T, Addr > &list)
Assignment from IndirectList. Takes linear time.
void operator= (std::initializer_list< T > list)
Assignment to an initializer list.
void operator= (const T &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (List< T > &&list)
Move assignment. Takes constant time.
template<int SizeMin>
void operator= (DynamicList< T, SizeMin > &&list)
Move assignment. Takes constant time.
void operator= (SortableList< T > &&list)
Move assignment. Takes constant time.
void operator= (SLList< T > &&list)
Move assignment. Takes constant time.
void shallowCopy (const UList< T > &)=delete
No shallowCopy permitted.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type set (const label i, bool val=true)
A bitSet::set() method for a list of bool.
template<>
void resize (const label newSize)
Public Member Functions inherited from UList< T >
constexpr UList () noexcept
Null constructor.
UList (T *__restrict__ v, label size) noexcept
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const T & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
T & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const T & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
T & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
std::streamsize byteSize () const
Return the binary size in number of characters of the UList if the element is a primitive type.
const T * cdata () const
Return a const pointer to the first data element.
T * data ()
Return a pointer to the first data element.
T & first ()
Return the first element of the list.
const T & first () const
Return first element of the list.
T & last ()
Return the last element of the list.
const T & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is within valid range [0,size].
void checkIndex (const label i) const
Check index is within valid range [0,size)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const T &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const T &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const T &val, const label start=0) const
True if the value if found in the list.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element. Fatal on an empty list.
void swapLast (const label i)
Swap element with the last element. Fatal on an empty list.
void shallowCopy (const UList< T > &list)
Copy the pointer held by the given UList.
void deepCopy (const UList< T > &list)
Copy elements of the given UList.
T & operator[] (const label i)
Return element of UList.
const T & operator[] (const label i) const
Return element of constant UList.
UList< T > operator[] (const labelRange &range)
Return (start,size) subset from UList with non-const access.
const UList< T > operator[] (const labelRange &range) const
Return (start,size) subset from UList with const access.
operator const Foam::List< T > & () const
Allow cast to a const List<T>&.
void operator= (const T &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
iterator begin ()
Return an iterator to begin traversing the UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
label size () const noexcept
The number of elements in the UList.
bool empty () const noexcept
True if the UList is empty (ie, size() is zero)
void swap (UList< T > &list)
Swap content with another UList of the same type in constant time.
bool operator== (const UList< T > &a) const
Equality operation on ULists of the same type.
bool operator!= (const UList< T > &a) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< T > &list) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< T > &a) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< T > &a) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< T > &a) const
Return true if !(a < b). Takes linear time.
void writeEntry (const word &keyword, Ostream &os) const
Write the List as a dictionary entry with keyword.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type test (const label i) const
A bitSet::test() method for a list of bool.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type get (const label i) const
A bitSet::get() method for a list of bool.
template<class TypeT = T>
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type unset (const label i)
A bitSet::unset() method for a list of bool.
template<>
const bool & operator[] (const label i) const
template<>
Foam::UPstream::commsStruct & operator[] (const label procID)
template<>
const Foam::UPstream::commsStruct & operator[] (const label procID) const
template<>
UPstream::commsStruct & operator[] (const label)
template<>
const UPstream::commsStruct & operator[] (const label) const
Public Member Functions inherited from patchIdentifier
patchIdentifier (const word &name, const label index, const word &physicalType=word::null, const wordList &inGroups=wordList())
Construct from components.
patchIdentifier (const word &name, const dictionary &dict, const label index)
Construct from dictionary.
patchIdentifier (const patchIdentifier &p, const label index)
Copy construct, resetting the index.
virtual ~patchIdentifier ()=default
Destructor.
const word & name () const
Return the patch name.
word & name ()
Modifiable patch name.
const word & physicalType () const
The optional physical type of the patch.
word & physicalType ()
Modifiable optional physical type of the patch.
label index () const
The index of this patch in the boundaryMesh.
label & index ()
Modifiable the index of this patch in the boundaryMesh.
const wordList & inGroups () const
The optional groups that the patch belongs to.
wordList & inGroups ()
Modifiable optional groups that the patch belongs to.
bool inGroup (const word &name) const
Check if the patch is in named group.
void write (Ostream &os) const
Write patchIdentifier as a dictionary.
Protected Member Functions
virtual void makeWeights (scalarField &) const =0
Make patch weighting factors.
virtual void makeDeltaCoeffs (scalarField &) const =0
Make patch face - neighbour cell distances.
void calcTransformTensors (const vector &Cf, const vector &Cr, const vector &nf, const vector &nr) const
Calculate the uniform transformation tensors.
void calcTransformTensors (const vectorField &Cf, const vectorField &Cr, const vectorField &nf, const vectorField &nr) const
Calculate the transformation tensors.
Protected Member Functions inherited from faPatch
void calcPointLabels () const
Calculate patch point labels.
void calcPointEdges () const
Calculate patch point-edge addressing.
virtual void initUpdateMesh ()
Initialise the update of the patch topology.
virtual void updateMesh ()
Update of the patch topology.
Protected Member Functions inherited from UList< T >
void size (const label n) noexcept
Override size to be inconsistent with allocated storage.
void writeEntry (Ostream &os) const
Write the UList with its compound type.
labelRange validateRange (const labelRange &range) const
Return a validated (start,size) subset range, which means that it always addresses a valid section of the list.
UList< T > & operator= (const UList< T > &)=delete
No copy assignment (default: shallow copy)
Additional Inherited Members
Public Types inherited from faPatch
typedef faBoundaryMesh BoundaryMesh
Public Types inherited from List< T >
typedef SubList< T > subList
Declare type of subList.
Public Types inherited from UList< T >
typedef T value_type
The value type the list contains.
typedef T * pointer
The pointer type for non-const access to value_type items.
typedef const T * const_pointer
The pointer type for const access to value_type items.
typedef T & reference
The type used for storing into value_type objects.
typedef const T & const_reference
The type used for reading from constant value_type objects.
typedef T * iterator
Random access iterator for traversing a UList.
typedef const T * const_iterator
Random access iterator for traversing a UList.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Static Public Member Functions inherited from faPatch
static autoPtr< faPatch > New (const word &name, const dictionary &dict, const label index, const faBoundaryMesh &bm)
Return a pointer to a new patch created.
Static Public Member Functions inherited from List< T >
static const List< T > & null ()
Return a null List.
Static Public Member Functions inherited from UList< T >
static const UList< T > & null ()
Return a UList reference to a nullObject.
static constexpr label max_size () noexcept
The size of the largest possible UList.
Detailed Description
coupledFaPatch is an abstract base class for patches that couple regions of the computational domain e.g. cyclic, arbitrary interfaces, sliding interfaces and processor-processor links.
Author Zeljko Tukovic and Hrvoje Jasak
Source files
coupledFaPatch.H
coupledFaPatch.C
Definition at line 52 of file coupledFaPatch.H.
Constructor & Destructor Documentation
coupledFaPatch (const word & name, const labelList & edgeLabels, const label index, const faBoundaryMesh & bm, const label ngbPolyPatchIndex) inline
Construct from components.
Definition at line 126 of file coupledFaPatch.H.
coupledFaPatch (const word & name, const dictionary & dict, const label index, const faBoundaryMesh & bm) inline
Construct from dictionary.
Definition at line 141 of file coupledFaPatch.H.
~coupledFaPatch () virtual
Destructor.
Definition at line 115 of file coupledFaPatch.C.
Member Function Documentation
virtual void makeWeights (scalarField &) const protected pure virtual
Make patch weighting factors.
Reimplemented from faPatch.
Implemented in processorFaPatch, and cyclicFaPatch.
virtual void makeDeltaCoeffs (scalarField &) const protected pure virtual
Make patch face - neighbour cell distances.
Reimplemented from faPatch.
Implemented in processorFaPatch, and cyclicFaPatch.
void calcTransformTensors (const vector & Cf, const vector & Cr, const vector & nf, const vector & nr) const protected
Calculate the uniform transformation tensors.
Definition at line 34 of file coupledFaPatch.C.
References Foam::defineTypeNameAndDebug().
void calcTransformTensors (const vectorField & Cf, const vectorField & Cr, const vectorField & nf, const vectorField & nr) const protected
Calculate the transformation tensors.
Definition at line 68 of file coupledFaPatch.C.
TypeName ("coupled")
Runtime type information.
virtual bool coupled () const inline virtual
Return true because this patch is coupled.
Reimplemented from faPatch.
Reimplemented in processorFaPatch.
Definition at line 165 of file coupledFaPatch.H.
bool separated () const inline
Are the coupled planes separated.
Definition at line 174 of file coupledFaPatch.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
const vectorField& separation () const inline
Return the offset (distance) vector from one side of the couple.
to the other
Definition at line 184 of file coupledFaPatch.H.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, and UList< T >::size().
const tensorField& forwardT () const inline
Return face transformation tensor.
Definition at line 199 of file coupledFaPatch.H.
References UList< T >::size().
Referenced by processorFaPatch::myProcNo(), and cyclicFaPatch::owner().
const tensorField& reverseT () const inline
Return neighbour-cell transformation tensor.
Definition at line 214 of file coupledFaPatch.H.
Referenced by cyclicFaPatch::neighbPatch().
bool parallel () const inline
Are the cyclic planes parallel.
Definition at line 229 of file coupledFaPatch.H.
Referenced by cyclicFaPatchField< Type >::transformCoupleField().
virtual void initGeometry () pure virtual
Initialise the calculation of the patch geometry.
Reimplemented from faPatch.
Implemented in cyclicFaPatch, and processorFaPatch.
virtual void calcGeometry () pure virtual
Calculate the patch geometry.
Reimplemented from faPatch.
Implemented in cyclicFaPatch, and processorFaPatch.
virtual void initMovePoints (const pointField &) pure virtual
Initialise the patches for moving points.
Reimplemented from faPatch.
Implemented in cyclicFaPatch, and processorFaPatch.
virtual void movePoints (const pointField &) pure virtual
Correct patches after moving points.
Reimplemented from faPatch.
Implemented in cyclicFaPatch, and processorFaPatch.
virtual tmp<vectorField> delta () const pure virtual
Return delta (P to N) vectors across coupled patch.
Reimplemented from faPatch.
Implemented in processorFaPatch, and cyclicFaPatch.
virtual const labelUList& faceCells () const inline virtual
Return faceCell addressing: lduInterface virtual function.
Implements lduInterface.
Definition at line 269 of file coupledFaPatch.H.
virtual tmp<labelField> interfaceInternalField (const labelUList & internalData) const pure virtual
Return the values of the given internal data adjacent to.
the interface as a field
Implements lduInterface.
Implemented in processorFaPatch, and cyclicFaPatch.
virtual void initTransfer (const Pstream::commsTypes commsType, const labelUList & interfaceData) const inline virtual
Initialise interface data transfer.
Reimplemented in processorFaPatch.
Definition at line 288 of file coupledFaPatch.H.
virtual tmp<labelField> transfer (const Pstream::commsTypes commsType, const labelUList & interfaceData) const pure virtual
Transfer and return neighbour field.
Implemented in processorFaPatch, and cyclicFaPatch.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const inline virtual
Initialise neighbour field transfer.
Reimplemented from lduInterface.
Reimplemented in processorFaPatch.
Definition at line 307 of file coupledFaPatch.H.
virtual tmp<labelField> internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList & iF) const pure virtual
Return neighbour field.
Implements lduInterface.
Implemented in processorFaPatch, and cyclicFaPatch.
The documentation for this class was generated from the following files:
src/finiteArea/faMesh/faPatches/basic/coupled/coupledFaPatch.H
src/finiteArea/faMesh/faPatches/basic/coupled/coupledFaPatch.C