OpenFOAM: rigidBodyModel Class Reference
rigidBodyModel Class Reference
Basic rigid-body model representing a system of rigid-bodies connected by 1-6 DoF joints.
Public Member Functions
TypeName ("rigidBodyModel")
Runtime type information.
rigidBodyModel (const Time &time)
Null-constructor which adds the single root-body at the origin.
rigidBodyModel (const Time &time, const dictionary &dict)
Construct from dictionary.
virtual ~rigidBodyModel ()
Destructor.
const Time & time () const
Return the time.
label nBodies () const
Return the number of bodies in the model (bodies().size())
PtrList< rigidBody > bodies () const
Return the list of the bodies in the model.
const DynamicList< label > & lambda () const
List of indices of the parent of each body.
const PtrList< joint > & joints () const
Return the list of joints in the model.
label nDoF () const
Return the number of degrees of freedom of the model.
bool unitQuaternions () const
Return true if any of the joints using quaternions.
const vector & g () const
Return the acceleration due to gravity.
vector & g ()
Allow the acceleration due to gravity to be set.
const word & name (const label bodyID) const
Return the name of body with the given ID.
const rigidBodyInertia & I (const label i) const
Return the inertia of body i.
const spatialVector & v (const label i) const
Return the spatial velocity of the bodies.
const spatialVector & a (const label i) const
Return the spatial acceleration of the bodies.
virtual label join (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
label join (const label parentID, const spatialTransform &XT, autoPtr< joints::composite > cJoint, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
label merge (const label parentID, const spatialTransform &X, autoPtr< rigidBody > bodyPtr)
Merge the given body with transform X into the parent with ID.
bool merged (label bodyID) const
Return true if the body with given ID has been merged with a parent.
label master (label bodyID) const
Return the ID of the master body for a sub-body otherwise.
label mergedBodyIndex (const label mergedBodyID) const
Return the index of the merged body in the mergedBody list.
label mergedBodyID (const label mergedBodyIndex) const
Return the merged body ID for the given merged body index.
const subBody & mergedBody (label mergedBodyID) const
Return the merged body for the given body ID.
label bodyID (const word &name) const
Return the ID of the body with the given name.
spatialTransform X0 (const label bodyId) const
Return the current transform to the global frame for the given body.
vector masterPoint (const label bodyID, const vector &p) const
spatialVector v (const label bodyID, const vector &p) const
Return the velocity of the given point on the given body.
void applyRestraints (scalarField &tau, Field< spatialVector > &fx, const rigidBodyModelState &state) const
Apply the restraints and accumulate the internal joint forces.
void forwardDynamics (rigidBodyModelState &state, const scalarField &tau, const Field< spatialVector > &fx) const
Calculate the joint acceleration qDdot from the joint state q,.
void forwardDynamicsCorrection (const rigidBodyModelState &state) const
Correct the velocity and acceleration of the bodies in the model.
virtual void write (Ostream &) const
Write.
bool read (const dictionary &dict)
Read coefficients dictionary and update system parameters,.
Protected Member Functions
virtual label join_ (const label parentID, const spatialTransform &XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
Protected Attributes
const Time & time_
Reference to time database.
PtrList< rigidBody > bodies_
List of the bodies.
PtrList< subBody > mergedBodies_
Bodies may be merged into existing bodies, the inertia of which is.
HashTable< label > bodyIDs_
Lookup-table of the IDs of the bodies.
DynamicList< label > lambda_
List of indices of the parent of each body.
PtrList< joint > joints_
Each body it attached with a joint which are held on this list.
DynamicList< spatialTransform > XT_
Transform from the parent body frame to the joint frame.
label nDoF_
The number of degrees of freedom of the model.
bool unitQuaternions_
True if any of the joints using quaternions.
PtrList< restraint > restraints_
Motion restraints.
vector g_
Acceleration due to gravity.
DynamicList< spatialTransform > Xlambda_
Transform from the parent body to the current body.
DynamicList< spatialTransform > X0_
Transform for external forces to the bodies reference frame.
DynamicList< spatialVector > v_
The spatial velocity of the bodies.
DynamicList< spatialVector > a_
The spatial acceleration of the bodies.
DynamicList< spatialVector > c_
The velocity dependent spatial acceleration of the joints.
DynamicList< spatialTensor > IA_
Velocity-product acceleration.
DynamicList< spatialVector > pA_
Articulated body bias force.
DynamicList< compactSpatialTensor > S_
Motion subspace for joints with 3 degrees of freedom.
DynamicList< spatialVector > S1_
Motion subspace for joints with 1 degrees of freedom.
DynamicList< compactSpatialTensor > U_
Sub-expression IA.S in the forward-dynamics algorithm.
DynamicList< spatialVector > U1_
Sub-expression IA.S1 in the forward-dynamics algorithm.
DynamicList< tensor > Dinv_
Sub-expression (S^T.U)^-1 in the forward-dynamics algorithm.
DynamicList< vector > u_
Sub-expression tau - S^T.pA in the forward-dynamics algorithm.
Friends
Ostream & operator<< (Ostream &, const rigidBodyModel &)
Detailed Description
Basic rigid-body model representing a system of rigid-bodies connected by 1-6 DoF joints.
This class holds various body and joint state fields needed by the kinematics and forward-dynamics algorithms presented in
reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
    Chapter 4.
Source files
rigidBodyModel.H
rigidBodyModel.C
kinematics.C
forwardDynamics.C
Definition at line 79 of file rigidBodyModel.H.
Constructor & Destructor Documentation
rigidBodyModel (const Time & time)
Null-constructor which adds the single root-body at the origin.
Definition at line 161 of file rigidBodyModel.C.
rigidBodyModel (const Time & time, const dictionary & dict)
Construct from dictionary.
Definition at line 171 of file rigidBodyModel.C.
~rigidBodyModel () virtual
Destructor.
Definition at line 216 of file rigidBodyModel.C.
Member Function Documentation
Foam::label join_ (const label parentID, const spatialTransform & XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr) protected virtual
Join the given body to the parent with ID parentID via the given.
joint with transform from the parent frame to the joint frame XT.
Definition at line 115 of file rigidBodyModel.C.
TypeName ("rigidBodyModel")
Runtime type information.
const Foam::Time & time () const inline
Return the time.
Definition at line 24 of file rigidBodyModelI.H.
Foam::label nBodies () const inline
Return the number of bodies in the model (bodies().size())
Definition at line 30 of file rigidBodyModelI.H.
References rigidBodyModel::time_.
Foam::PtrList< Foam::RBD::rigidBody > bodies () const inline
Return the list of the bodies in the model.
Definition at line 37 of file rigidBodyModelI.H.
const Foam::DynamicList< Foam::label > & lambda () const inline
List of indices of the parent of each body.
Definition at line 44 of file rigidBodyModelI.H.
const Foam::PtrList< Foam::RBD::joint > & joints () const inline
Return the list of joints in the model.
Definition at line 51 of file rigidBodyModelI.H.
Foam::label nDoF () const inline
Return the number of degrees of freedom of the model.
used to set the size of the of joint state fields q, qDot and qDdot.
Definition at line 57 of file rigidBodyModelI.H.
bool unitQuaternions () const inline
Return true if any of the joints using quaternions.
Definition at line 63 of file rigidBodyModelI.H.
const Foam::vector & g () const inline
Return the acceleration due to gravity.
Definition at line 69 of file rigidBodyModelI.H.
Foam::vector & g () inline
Allow the acceleration due to gravity to be set.
after model construction
Definition at line 75 of file rigidBodyModelI.H.
const Foam::word & name (const label bodyID) const inline
Return the name of body with the given ID.
Definition at line 82 of file rigidBodyModelI.H.
const Foam::RBD::rigidBodyInertia & I (const label i) const inline
Return the inertia of body i.
Definition at line 98 of file rigidBodyModelI.H.
const Foam::spatialVector & v (const label i) const inline
Return the spatial velocity of the bodies.
Definition at line 105 of file rigidBodyModelI.H.
References i.
const Foam::spatialVector & a (const label i) const inline
Return the spatial acceleration of the bodies.
Definition at line 111 of file rigidBodyModelI.H.
References i.
Foam::label join (const label parentID, const spatialTransform & XT, autoPtr< joint > jointPtr, autoPtr< rigidBody > bodyPtr) virtual
Join the given body to the parent with ID parentID via the given.
joint with transform from the parent frame to the joint frame XT.
Definition at line 223 of file rigidBodyModel.C.
Foam::label join (const label parentID, const spatialTransform & XT, autoPtr< joints::composite > cJoint, autoPtr< rigidBody > bodyPtr)
Join the given body to the parent with ID parentID via the given.
composite joint (specified as a list of co-located joints) with transform from the parent frame to the joint frame XT. Composite joins are useful to represent complex joints with degrees of freedom other than 1 or 3 which are directly supported.
Definition at line 257 of file rigidBodyModel.C.
Foam::label merge (const label parentID, const spatialTransform & X, autoPtr< rigidBody > bodyPtr)
Merge the given body with transform X into the parent with ID.
parentID. The parent body assumes the properties of the combined body (inertia etc.) and the merged body is held on a separate list for reference.
Definition at line 315 of file rigidBodyModel.C.
bool merged (label bodyID) const inline
Return true if the body with given ID has been merged with a parent.
Definition at line 116 of file rigidBodyModelI.H.
References i.
Foam::label master (label bodyID) const inline
Return the ID of the master body for a sub-body otherwise.
return the given body ID
Definition at line 122 of file rigidBodyModelI.H.
Foam::label mergedBodyIndex (const label mergedBodyID) const inline
Return the index of the merged body in the mergedBody list.
from the given body ID
Definition at line 143 of file rigidBodyModelI.H.
Foam::label mergedBodyID (const label mergedBodyIndex) const inline
Return the merged body ID for the given merged body index.
in the mergedBody list
Definition at line 136 of file rigidBodyModelI.H.
const Foam::RBD::subBody & mergedBody (label mergedBodyID) const inline
Return the merged body for the given body ID.
Definition at line 150 of file rigidBodyModelI.H.
Foam::label bodyID (const word & name) const inline
Return the ID of the body with the given name.
Definition at line 163 of file rigidBodyModelI.H.
Foam::spatialTransform X0 (const label bodyId) const
Return the current transform to the global frame for the given body.
Definition at line 373 of file rigidBodyModel.C.
Referenced by restraint::bodyPointVelocity().
Foam::vector masterPoint (const label bodyID, const vector & p) const inline
Definition at line 170 of file rigidBodyModelI.H.
References Foam::name().
Foam::spatialVector v (const label bodyID, const vector & p) const inline
Return the velocity of the given point on the given body.
Definition at line 191 of file rigidBodyModelI.H.
References p.
void applyRestraints (scalarField & tau, Field< spatialVector > & fx, const rigidBodyModelState & state) const
Apply the restraints and accumulate the internal joint forces.
into the tau field and external forces into the fx field
Definition at line 28 of file forwardDynamics.C.
References DebugInfo, forAll, and rigidBodyModel::restraints_.
void forwardDynamics (rigidBodyModelState & state, const scalarField & tau, const Field< spatialVector > & fx) const
Calculate the joint acceleration qDdot from the joint state q,.
velocity qDot, internal force tau (in the joint frame) and external force fx (in the global frame) using the articulated body algorithm (Section 7.3 and Table 7.1)
Definition at line 50 of file forwardDynamics.C.
void forwardDynamicsCorrection (const rigidBodyModelState & state) const
Correct the velocity and acceleration of the bodies in the model.
from the given joint state fields following an integration step of the forwardDynamics
Definition at line 203 of file forwardDynamics.C.
void write (Ostream & os) const virtual
Write.
Reimplemented in rigidBodyMotion.
Definition at line 387 of file rigidBodyModel.C.
bool read (const dictionary & dict)
Read coefficients dictionary and update system parameters,.
restraints but not the current state
Definition at line 448 of file rigidBodyModel.C.
Referenced by rigidBodyMotion::read().
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const rigidBodyModel &) friend
Member Data Documentation
const Time& time_ protected
Reference to time database.
Definition at line 110 of file rigidBodyModel.H.
Referenced by rigidBodyModel::nBodies().
PtrList<rigidBody> bodies_ protected
List of the bodies.
The 0'th body represents the fixed origin and is constructed automatically. The subsequent (moving) bodies are appended by the join member function.
Definition at line 121 of file rigidBodyModel.H.
PtrList<subBody> mergedBodies_ protected
Bodies may be merged into existing bodies, the inertia of which is.
updated to represent the combined body which is more efficient than attaching them with fixed joints. These 'merged' bodies are held on this list.
Definition at line 130 of file rigidBodyModel.H.
HashTable<label> bodyIDs_ protected
Lookup-table of the IDs of the bodies.
Definition at line 135 of file rigidBodyModel.H.
DynamicList<label> lambda_ protected
List of indices of the parent of each body.
Definition at line 140 of file rigidBodyModel.H.
PtrList<joint> joints_ protected
Each body it attached with a joint which are held on this list.
Definition at line 145 of file rigidBodyModel.H.
DynamicList<spatialTransform> XT_ protected
Transform from the parent body frame to the joint frame.
Definition at line 150 of file rigidBodyModel.H.
label nDoF_ protected
The number of degrees of freedom of the model.
used to set the size of the of joint state fields q, qDot and qDdot.
Definition at line 157 of file rigidBodyModel.H.
bool unitQuaternions_ protected
True if any of the joints using quaternions.
Definition at line 162 of file rigidBodyModel.H.
PtrList<restraint> restraints_ protected
Motion restraints.
Definition at line 167 of file rigidBodyModel.H.
Referenced by rigidBodyModel::applyRestraints().
vector g_ protected
Acceleration due to gravity.
Definition at line 175 of file rigidBodyModel.H.
DynamicList<spatialTransform> Xlambda_ mutable protected
Transform from the parent body to the current body.
Definition at line 183 of file rigidBodyModel.H.
DynamicList<spatialTransform> X0_ mutable protected
Transform for external forces to the bodies reference frame.
Definition at line 188 of file rigidBodyModel.H.
DynamicList<spatialVector> v_ mutable protected
The spatial velocity of the bodies.
Definition at line 196 of file rigidBodyModel.H.
DynamicList<spatialVector> a_ mutable protected
The spatial acceleration of the bodies.
Definition at line 201 of file rigidBodyModel.H.
DynamicList<spatialVector> c_ mutable protected
The velocity dependent spatial acceleration of the joints.
Definition at line 206 of file rigidBodyModel.H.
DynamicList<spatialTensor> IA_ mutable protected
Velocity-product acceleration.
Articulated body inertia
Definition at line 218 of file rigidBodyModel.H.
DynamicList<spatialVector> pA_ mutable protected
Articulated body bias force.
Definition at line 223 of file rigidBodyModel.H.
DynamicList<compactSpatialTensor> S_ mutable protected
Motion subspace for joints with 3 degrees of freedom.
Definition at line 231 of file rigidBodyModel.H.
DynamicList<spatialVector> S1_ mutable protected
Motion subspace for joints with 1 degrees of freedom.
Definition at line 236 of file rigidBodyModel.H.
DynamicList<compactSpatialTensor> U_ mutable protected
Sub-expression IA.S in the forward-dynamics algorithm.
Definition at line 241 of file rigidBodyModel.H.
DynamicList<spatialVector> U1_ mutable protected
Sub-expression IA.S1 in the forward-dynamics algorithm.
Definition at line 246 of file rigidBodyModel.H.
DynamicList<tensor> Dinv_ mutable protected
Sub-expression (S^T.U)^-1 in the forward-dynamics algorithm.
Definition at line 251 of file rigidBodyModel.H.
DynamicList<vector> u_ mutable protected
Sub-expression tau - S^T.pA in the forward-dynamics algorithm.
Definition at line 256 of file rigidBodyModel.H.
The documentation for this class was generated from the following files:
src/rigidBodyDynamics/rigidBodyModel/rigidBodyModel.H
src/rigidBodyDynamics/rigidBodyModel/forwardDynamics.C
src/rigidBodyDynamics/rigidBodyModel/rigidBodyModel.C
src/rigidBodyDynamics/rigidBodyModel/rigidBodyModelI.H