OpenFOAM: refinementDistanceData Class Reference
refinementDistanceData Class Reference
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Public Member Functions
refinementDistanceData ()
Construct null.
refinementDistanceData (const scalar level0Size, const point &origin, const label level)
Construct from count.
scalar level0Size () const
scalar & level0Size ()
const point & origin () const
point & origin ()
label originLevel () const
label & originLevel ()
label wantedLevel (const point &pt) const
Calculates the wanted level at a given point. Walks out from.
template<class TrackingData >
bool valid (TrackingData &) const
Check whether origin has been changed at all or.
template<class TrackingData >
bool sameGeometry (const polyMesh &, const refinementDistanceData &, const scalar, TrackingData &) const
Check for identical geometrical data. Used for cyclics checking.
template<class TrackingData >
void leaveDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &)
Convert any absolute coordinates into relative to (patch)face.
template<class TrackingData >
void enterDomain (const polyMesh &, const polyPatch &, const label patchFacei, const point &faceCentre, TrackingData &)
Reverse of leaveDomain.
template<class TrackingData >
void transform (const polyMesh &, const tensor &, TrackingData &)
Apply rotation matrix to any coordinates.
template<class TrackingData >
bool updateCell (const polyMesh &, const label thisCelli, const label neighbourFacei, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
Influence of neighbouring face.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const label neighbourCelli, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
Influence of neighbouring cell.
template<class TrackingData >
bool updateFace (const polyMesh &, const label thisFacei, const refinementDistanceData &neighbourInfo, const scalar tol, TrackingData &)
Influence of different value on same face.
template<class TrackingData >
bool equal (const refinementDistanceData &, TrackingData &) const
Same (like operator==)
bool operator== (const refinementDistanceData &) const
bool operator!= (const refinementDistanceData &) const
Friends
Ostream & operator<< (Ostream &, const refinementDistanceData &)
Istream & operator>> (Istream &, refinementDistanceData &)
Detailed Description
Transfers refinement levels such that slow transition between levels is maintained. Used in FaceCellWave.
Source files
refinementDistanceData.H
refinementDistanceDataI.H
refinementDistanceData.C
Definition at line 59 of file refinementDistanceData.H.
Constructor & Destructor Documentation
refinementDistanceData () inline
Construct null.
Definition at line 119 of file refinementDistanceDataI.H.
refinementDistanceData (const scalar level0Size, const point & origin, const label level) inline
Construct from count.
Definition at line 127 of file refinementDistanceDataI.H.
Member Function Documentation
scalar level0Size () const inline
Definition at line 113 of file refinementDistanceData.H.
scalar& level0Size () inline
Definition at line 118 of file refinementDistanceData.H.
const point& origin () const inline
Definition at line 123 of file refinementDistanceData.H.
point& origin () inline
Definition at line 128 of file refinementDistanceData.H.
label originLevel () const inline
Definition at line 133 of file refinementDistanceData.H.
label& originLevel () inline
Definition at line 138 of file refinementDistanceData.H.
Foam::label wantedLevel (const point & pt) const inline
Calculates the wanted level at a given point. Walks out from.
the origin.
Definition at line 28 of file refinementDistanceDataI.H.
References Foam::magSqr(), and Foam::sqr().
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 142 of file refinementDistanceDataI.H.
bool sameGeometry (const polyMesh & , const refinementDistanceData & , const scalar , TrackingData & td) const inline
Check for identical geometrical data. Used for cyclics checking.
Definition at line 151 of file refinementDistanceDataI.H.
void leaveDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Convert any absolute coordinates into relative to (patch)face.
centre
Definition at line 164 of file refinementDistanceDataI.H.
void enterDomain (const polyMesh & , const polyPatch & patch, const label patchFacei, const point & faceCentre, TrackingData & td) inline
Reverse of leaveDomain.
Definition at line 191 of file refinementDistanceDataI.H.
void transform (const polyMesh & , const tensor & rotTensor, TrackingData & td) inline
Apply rotation matrix to any coordinates.
Definition at line 178 of file refinementDistanceDataI.H.
References origin_().
bool updateCell (const polyMesh & mesh, const label thisCelli, const label neighbourFacei, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring face.
Definition at line 207 of file refinementDistanceDataI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const label neighbourCelli, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of neighbouring cell.
Definition at line 225 of file refinementDistanceDataI.H.
bool updateFace (const polyMesh & mesh, const label thisFacei, const refinementDistanceData & neighbourInfo, const scalar tol, TrackingData & td) inline
Influence of different value on same face.
Definition at line 243 of file refinementDistanceDataI.H.
bool equal (const refinementDistanceData & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 259 of file refinementDistanceDataI.H.
bool operator== (const refinementDistanceData & rhs) const inline
Definition at line 278 of file refinementDistanceDataI.H.
bool operator!= (const refinementDistanceData & rhs) const inline
Definition at line 290 of file refinementDistanceDataI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const refinementDistanceData &) friend
Istream& operator>> (Istream & , refinementDistanceData &) friend
The documentation for this class was generated from the following files:
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDistanceData.H
src/dynamicMesh/polyTopoChange/polyTopoChange/refinementDistanceDataI.H