OpenFOAM: heatTransferModel Class Reference
heatTransferModel Class Reference abstract
Public Member Functions
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
heatTransferModel (const dictionary &dict, const phasePair &pair)
Construct froma dictionary and a phase pair.
virtual ~heatTransferModel ()
Destructor.
tmp< volScalarField > K () const
The heat transfer function K used in the enthalpy equation.
virtual tmp< volScalarField > K (const scalar residualAlpha) const =0
The heat transfer function K used in the enthalpy equation.
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &interfaceDict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2),(interfaceDict, alpha1, phase1, phase2))
heatTransferModel (const dictionary &interfaceDict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2)
virtual ~heatTransferModel ()
Destructor.
virtual tmp< volScalarField > K (const volScalarField &Ur) const =0
The heat-transfer function K used in the enthalpy eq.
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, heatTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
heatTransferModel (const dictionary &dict, const phasePair &pair)
Construct froma dictionary and a phase pair.
virtual ~heatTransferModel ()
Destructor.
virtual tmp< volScalarField > K () const =0
The heat transfer function K used in the enthalpy equation.
Static Public Member Functions
static autoPtr< heatTransferModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr< heatTransferModel > New (const dictionary &interfaceDict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2)
static autoPtr< heatTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimK
Coefficient dimensions.
Protected Attributes
const phasePair & pair_
Phase pair.
const dimensionedScalar residualAlpha_
Residual phase fraction.
const dictionary & interfaceDict_
const volScalarField & alpha1_
const phaseModel & phase1_
const phaseModel & phase2_
Detailed Description
Source files
heatTransferModel.H
heatTransferModel.C
Source files
heatTransferModel.H
heatTransferModel.C
newHeatTransferModel.C
Source files
heatTransferModel.H
heatTransferModel.C
Definition at line 49 of file heatTransferModel.H.
Constructor & Destructor Documentation
heatTransferModel (const dictionary & dict, const phasePair & pair)
Construct froma dictionary and a phase pair.
Definition at line 40 of file heatTransferModel.C.
~heatTransferModel () virtual
Destructor.
Definition at line 63 of file heatTransferModel.C.
heatTransferModel (const dictionary & interfaceDict, const volScalarField & alpha1, const phaseModel & phase1, const phaseModel & phase2)
virtual ~heatTransferModel () virtual
Destructor.
heatTransferModel (const dictionary & dict, const phasePair & pair)
Construct froma dictionary and a phase pair.
virtual ~heatTransferModel () virtual
Destructor.
Member Function Documentation
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , heatTransferModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::heatTransferModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 28 of file newHeatTransferModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
Foam::tmp< Foam::volScalarField > K () const
The heat transfer function K used in the enthalpy equation.
ddt(alpha1*rho1*ha) + ... = ... K*(Ta - Tb) ddt(alpha2*rho2*hb) + ... = ... K*(Tb - Ta)
Definition at line 70 of file heatTransferModel.C.
virtual tmp<volScalarField> K (const scalar residualAlpha) const pure virtual
The heat transfer function K used in the enthalpy equation.
ddt(alpha1*rho1*ha) + ... = ... K*(Ta - Tb) ddt(alpha2*rho2*hb) + ... = ... K*(Tb - Ta) with a specified residual volume fraction
Implemented in constantNuHeatTransfer, RanzMarshall, and sphericalHeatTransfer.
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , heatTransferModel , dictionary , (const dictionary &interfaceDict, const volScalarField &alpha1, const phaseModel &phase1, const phaseModel &phase2) , (interfaceDict, alpha1, phase1, phase2))
static autoPtr<heatTransferModel> New (const dictionary & interfaceDict, const volScalarField & alpha1, const phaseModel & phase1, const phaseModel & phase2) static
virtual tmp<volScalarField> K (const volScalarField & Ur) const pure virtual
The heat-transfer function K used in the enthalpy eq.
ddt(alpha1*rho1*ha) + ... = ... alpha1*alpha2*K*(Ta - Tb) ddt(alpha2*rho2*hb) + ... = ... alpha1*alpha2*K*(Tb - Ta) ********************************** NB! ***************************** for numerical reasons alpha1 and alpha2 has been extracted from the heat-transfer function K, so you MUST divide K by alpha1*alpha2 when implementing the heat-transfer function ********************************** NB! *****************************
Implemented in RanzMarshall.
TypeName ("heatTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , heatTransferModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
static autoPtr<heatTransferModel> New (const dictionary & dict, const phasePair & pair) static
virtual tmp<volScalarField> K () const pure virtual
The heat transfer function K used in the enthalpy equation.
ddt(alpha1*rho1*ha) + ... = ... K*(Ta - Tb) ddt(alpha2*rho2*hb) + ... = ... K*(Tb - Ta)
Implemented in RanzMarshall, and sphericalHeatTransfer.
Member Data Documentation
const phasePair & pair_ protected
Phase pair.
Definition at line 58 of file heatTransferModel.H.
const dimensionedScalar residualAlpha_ protected
Residual phase fraction.
Definition at line 63 of file heatTransferModel.H.
static const dimensionSet dimK static
Coefficient dimensions.
Definition at line 94 of file heatTransferModel.H.
Referenced by TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem().
const dictionary& interfaceDict_ protected
Definition at line 54 of file heatTransferModel.H.
const volScalarField& alpha1_ protected
Definition at line 55 of file heatTransferModel.H.
const phaseModel& phase1_ protected
Definition at line 56 of file heatTransferModel.H.
const phaseModel& phase2_ protected
Definition at line 57 of file heatTransferModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialModels/heatTransferModels/heatTransferModel/heatTransferModel.H
applications/solvers/multiphase/multiphaseEulerFoam/interfacialModels/heatTransferModels/heatTransferModel/heatTransferModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/interfacialModels/heatTransferModels/heatTransferModel/heatTransferModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialModels/heatTransferModels/heatTransferModel/heatTransferModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialModels/heatTransferModels/heatTransferModel/newHeatTransferModel.C