OpenFOAM: lumpedPointMovement Class Reference
lumpedPointMovement Class Reference
The movement driver that describes initial point locations, the segmentation for pressure integration, the current state of the points/rotations, and forwarding to the externalFileCoupler communication coordinator.
Public Types
enum outputFormatType { PLAIN, DICTIONARY }
Output format types.
enum scalingType { LENGTH = 0, FORCE, MOMENT }
Output format types.
Public Member Functions
lumpedPointMovement ()
Construct null.
lumpedPointMovement (const dictionary &dict, label ownerId=-1)
Construct from dictionary, optionally with some owner information.
virtual ~lumpedPointMovement ()
Destructor.
void readDict (const dictionary &dict)
Update settings from dictionary.
bool empty () const
If no number of lumped points (locations) were specified.
label size () const
The number of lumped points (number of locations)
const vector & axis () const
The normalized reference axis.
const scalarField & locations () const
Read access to the locations.
scalar division () const
The division (0-1) when calculating pressure forces.
label ownerId () const
An owner Id, if needed for bookkeeping purposes.
void ownerId (label id)
Change the owner id, if needed for bookkeeping purposes.
const scalarField & thresholds () const
Threshold locations for pressure forces.
label threshold (const point &position) const
Classify the position to be located in one of the threshold zones.
const externalFileCoupler & coupler () const
Communication control.
externalFileCoupler & coupler ()
Communication control.
const lumpedPointState & state0 () const
The initial state (positions/rotations)
const lumpedPointState & state () const
The current state (positions/rotations)
scalar relax () const
The relaxation factor when changing states.
scalar & relax ()
The relaxation factor when changing states.
const word & inputName () const
The input (state) file name.
const word & outputName () const
The output (forces) file name.
const word & logName () const
The log file name.
lumpedPointState::inputFormatType inputFormat () const
The input (state) file format.
lumpedPointMovement::outputFormatType outputFormat () const
The output (forces) file format.
void setBoundBox (const polyMesh &mesh, const labelUList &patchIds, const pointField &points0)
Define the bounding-box required to enclose the specified patches.
void setMapping (const polyMesh &mesh, const labelUList &patchIds, const pointField &points0)
Define the pressure-zones mapping for faces in the specified.
bool hasMapping () const
True if the pressure-zones mapping has already been performed.
const List< labelList > & zones () const
Return the pressure-zones mapping with the associated.
bool forcesAndMoments (const polyMesh &pmesh, List< vector > &forces, List< vector > &moments) const
The forces and moments acting on each pressure-zone.
tmp< pointField > displacePoints (const pointField &points0, const labelList &pointLabels) const
Displace points according to the current state.
tmp< pointField > displacePoints (const lumpedPointState &state, const pointField &points0, const labelList &pointLabels) const
Displace points according to specified state.
const interpolationWeights & interpolator () const
Interpolation weights.
void writeDict (Ostream &os) const
Write axis, locations, division as a dictionary.
bool writeData (Ostream &os, const UList< vector > &forces, const UList< vector > &moments, const outputFormatType fmt=outputFormatType::PLAIN, const Time *timeinfo=nullptr) const
Write points, forces, moments. Only call from the master process.
bool writeData (const UList< vector > &forces, const UList< vector > &moments=List< vector >(), const Time *timeinfo=nullptr) const
Write points, forces, moments.
bool readState ()
Read state from file, applying relaxation as requested.
void writeStateVTP (const fileName &file) const
Write state as VTK PolyData format.
void writeForcesAndMomentsVTP (const fileName &file, const UList< vector > &forces, const UList< vector > &moments) const
Write forces on points as VTK PolyData format.
void writeZonesVTP (const fileName &file, const polyMesh &mesh, const pointField &points0) const
Write pressure-zones geometry, write as VTK PolyData format.
void writeVTP (const fileName &file, const polyMesh &mesh, const labelUList &patchIds, const pointField &points0) const
Write displaced geometry according to the current state,.
void writeVTP (const fileName &file, const lumpedPointState &state, const polyMesh &mesh, const labelUList &patchLst, const pointField &points0) const
Write displaced geometry according to the specified state,.
Static Public Member Functions
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Deprecated(2018-08) compatibility method.
Static Public Attributes
static const Enum
< outputFormatType > formatNames
Names for the output format types.
static const Enum< scalingType > scalingNames
Names for the scaling types.
static const word canonicalName
The canonical name ("lumpedPointMovement") for the dictionary.
Detailed Description
The movement driver that describes initial point locations, the segmentation for pressure integration, the current state of the points/rotations, and forwarding to the externalFileCoupler communication coordinator.
The lumpedPointIOMovement class is simply a registered version of the same.
See externalFileCoupler for more information about some of the communication parameters and setup.
Dictionary parameters
Property Description Required Default
axis Reference axis for the locations yes
locations List of lumped point locations yes
centre Offset of patch points to locations no automatic
division Division (0-1) for pressure forces no 0
relax Relaxation/scaling for updating positions no
interpolationScheme The interpolation scheme yes
forces Optional forces dictionary no
communication Required communication dictionary yes
Parameters for communication dictionary
Property Description Required Default
inputName Name of positions input file yes
outputName Name of forces output file yes
logName Name of log file no movement.log
inputFormat Input format: dictionary/plain yes
outputFormat Output format: dictionary/plain yes
scaleInput Input scaling parameter dictionary no
scaleOutput Output scaling parameter dictionary no
Parameters for optional communication/scaleInput dictionary
Property Description Required Default
length Scaling for input positions no 1
Parameters for optional communication/scaleOutput dictionary
Property Description Required Default
length Scaling for output positions no 1
force Scaling for force no 1
moment Scaling for moment no 1
Parameters for optional forces dictionary
Property Description Required Default
p Name of the pressure field no p
pRef Reference pressure in Pa no 0
rhoRef Reference density for incompressible no 1
Source files
lumpedPointMovement.H
lumpedPointMovement.C
Definition at line 256 of file lumpedPointMovement.H.
Member Enumeration Documentation
enum outputFormatType strong
Output format types.
Enumerator
PLAIN
"plain" is a simple ASCII format
DICTIONARY
"dictionary" is the OpenFOAM dictionary format
Definition at line 263 of file lumpedPointMovement.H.
enum scalingType
Output format types.
Enumerator
LENGTH
The "length" scaling.
FORCE
The "force" scaling.
MOMENT
The "moment" scaling.
Definition at line 272 of file lumpedPointMovement.H.
Constructor & Destructor Documentation
lumpedPointMovement ()
Construct null.
Definition at line 166 of file lumpedPointMovement.C.
lumpedPointMovement (const dictionary & dict, label ownerId = -1)
Construct from dictionary, optionally with some owner information.
Definition at line 194 of file lumpedPointMovement.C.
~lumpedPointMovement () virtual
Destructor.
Definition at line 233 of file lumpedPointMovement.C.
References Foam::deleteDemandDrivenData().
Member Function Documentation
void readDict (const dictionary & dict)
Update settings from dictionary.
Definition at line 241 of file lumpedPointMovement.C.
References axis_(), Foam::deleteDemandDrivenData(), dictionary::findDict(), lumpedPointState::formatNames, lumpedPointMovement::formatNames, Enum< EnumType >::get(), i, Foam::Info, Foam::nl, dictionary::readEntry(), dictionary::readIfPresent(), dictionary::subDict(), and dictionary::subOrEmptyDict().
bool empty () const inline
If no number of lumped points (locations) were specified.
Definition at line 21 of file lumpedPointMovementI.H.
Foam::label size () const inline
The number of lumped points (number of locations)
Definition at line 27 of file lumpedPointMovementI.H.
References UList< T >::empty().
const Foam::vector & axis () const inline
The normalized reference axis.
Definition at line 33 of file lumpedPointMovementI.H.
Referenced by lumpedPointMovement::writeForcesAndMomentsVTP().
const Foam::scalarField & locations () const inline
Read access to the locations.
Definition at line 39 of file lumpedPointMovementI.H.
References axis_().
Foam::scalar division () const inline
The division (0-1) when calculating pressure forces.
Definition at line 45 of file lumpedPointMovementI.H.
Foam::label ownerId () const inline
An owner Id, if needed for bookkeeping purposes.
Definition at line 51 of file lumpedPointMovementI.H.
void ownerId (label id) inline
Change the owner id, if needed for bookkeeping purposes.
Definition at line 57 of file lumpedPointMovementI.H.
const Foam::scalarField & thresholds () const inline
Threshold locations for pressure forces.
Definition at line 63 of file lumpedPointMovementI.H.
Foam::label threshold (const point & position) const inline
Classify the position to be located in one of the threshold zones.
Definition at line 75 of file lumpedPointMovementI.H.
const Foam::externalFileCoupler & coupler () const inline
Communication control.
Definition at line 82 of file lumpedPointMovementI.H.
References axis_().
Foam::externalFileCoupler & coupler () inline
Communication control.
Definition at line 88 of file lumpedPointMovementI.H.
const Foam::lumpedPointState & state0 () const inline
The initial state (positions/rotations)
Definition at line 97 of file lumpedPointMovementI.H.
const Foam::lumpedPointState & state () const inline
The current state (positions/rotations)
Definition at line 103 of file lumpedPointMovementI.H.
Referenced by lumpedPointMovement::writeForcesAndMomentsVTP().
Foam::scalar relax () const inline
The relaxation factor when changing states.
Definition at line 109 of file lumpedPointMovementI.H.
Foam::scalar & relax () inline
The relaxation factor when changing states.
Definition at line 115 of file lumpedPointMovementI.H.
const Foam::word & inputName () const inline
The input (state) file name.
Definition at line 121 of file lumpedPointMovementI.H.
const Foam::word & outputName () const inline
The output (forces) file name.
Definition at line 127 of file lumpedPointMovementI.H.
const Foam::word & logName () const inline
The log file name.
Definition at line 133 of file lumpedPointMovementI.H.
Foam::lumpedPointState::inputFormatType inputFormat () const inline
The input (state) file format.
Definition at line 140 of file lumpedPointMovementI.H.
Foam::lumpedPointMovement::outputFormatType outputFormat () const inline
The output (forces) file format.
Definition at line 147 of file lumpedPointMovementI.H.
void setBoundBox (const polyMesh & mesh, const labelUList & patchIds, const pointField & points0)
Define the bounding-box required to enclose the specified patches.
Calculates the centre as required.
Parameters
mesh The volume mesh reference
patchIds The patch ids to be included in the bounding box.
points0 The initial mesh points, prior to movement
Definition at line 338 of file lumpedPointMovement.C.
References axis_(), polyMesh::boundaryMesh(), Foam::expressions::patchExpr::debug, Foam::endl(), boundBox::invertedBox, patches, patchId(), and Foam::Pout.
void setMapping (const polyMesh & mesh, const labelUList & patchIds, const pointField & points0)
Define the pressure-zones mapping for faces in the specified.
patches. The face centres are compared to the threshold positions, which are determined by locations along the defined axis.
Parameters
mesh The volume mesh reference
patchIds The patch ids to be included in the mapping
points0 The initial mesh points, prior to movement
Definition at line 377 of file lumpedPointMovement.C.
References polyMesh::boundaryMesh(), face::centre(), Foam::expressions::patchExpr::debug, Foam::endl(), f(), polyMesh::faces(), forAll, i, n, primitiveMesh::nFaces(), primitiveMesh::nInternalFaces(), Foam::nl, patches, patchId(), Foam::Pout, Foam::returnReduce(), List< T >::setSize(), polyPatch::start(), and Foam::Zero.
bool hasMapping () const inline
True if the pressure-zones mapping has already been performed.
Definition at line 153 of file lumpedPointMovementI.H.
const Foam::List< Foam::labelList > & zones () const inline
Return the pressure-zones mapping with the associated.
patch face ids.
Definition at line 160 of file lumpedPointMovementI.H.
bool forcesAndMoments (const polyMesh & pmesh, List< vector > & forces, List< vector > & moments) const
The forces and moments acting on each pressure-zone.
The zones must be previously defined via setMapping.
Definition at line 457 of file lumpedPointMovement.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), polyMesh::boundaryMesh(), fvMesh::Cf(), Foam::dimPressure, Foam::endl(), objectRegistry::findObject(), forAll, HashTable< T, Key, Hash >::found(), Foam::Info, Pstream::listCombineGather(), Pstream::listCombineScatter(), dimensioned< Type >::lookupOrDefault(), Foam::nl, p, patches, rhoRef(), HashPtrTable< T, label, Hash< label > >::set(), List< T >::setSize(), fvMesh::Sf(), polyBoundaryMesh::start(), WarningInFunction, polyBoundaryMesh::whichPatch(), and Foam::Zero.
Foam::tmp< Foam::pointField > displacePoints (const pointField & points0, const labelList & pointLabels) const
Displace points according to the current state.
Definition at line 610 of file lumpedPointMovement.C.
Foam::tmp< Foam::pointField > displacePoints (const lumpedPointState & state, const pointField & points0, const labelList & pointLabels) const
Displace points according to specified state.
Definition at line 621 of file lumpedPointMovement.C.
References axis_(), forAll, local, p0, lumpedPointState::points(), tmp< T >::ref(), lumpedPointState::rotations(), UList< T >::size(), and interpolationWeights::valueWeights().
const Foam::interpolationWeights & interpolator () const
Interpolation weights.
Definition at line 885 of file lumpedPointMovement.C.
References interpolationWeights::New().
void writeDict (Ostream & os) const
Write axis, locations, division as a dictionary.
Definition at line 678 of file lumpedPointMovement.C.
References axis_(), and Ostream::writeEntry().
bool writeData (Ostream & os, const UList< vector > & forces, const UList< vector > & moments, const outputFormatType fmt = outputFormatType::PLAIN, const Time * timeinfo = nullptr) const
Write points, forces, moments. Only call from the master process.
Definition at line 706 of file lumpedPointMovement.C.
References axis_(), forAll, i, Foam::nl, UList< T >::size(), Foam::val, Foam::vtk::writeList(), and VectorSpace< Vector< scalar >, scalar, 3 >::zero.
bool writeData (const UList< vector > & forces, const UList< vector > & moments = List<vector>(), const Time * timeinfo = nullptr) const
Write points, forces, moments.
Definition at line 845 of file lumpedPointMovement.C.
References IOstreamOption::ASCII, IOstreamOption::currentVersion, UPstream::master(), IOstreamOption::UNCOMPRESSED, and Foam::writeData().
bool readState ()
Read state from file, applying relaxation as requested.
Definition at line 687 of file lumpedPointMovement.C.
References lumpedPointState::readData().
void writeStateVTP (const fileName & file) const
Write state as VTK PolyData format.
Definition at line 30 of file lumpedPointMovementWriter.C.
void writeForcesAndMomentsVTP (const fileName & file, const UList< vector > & forces, const UList< vector > & moments) const
Write forces on points as VTK PolyData format.
Definition at line 37 of file lumpedPointMovementWriter.C.
References lumpedPointMovement::axis(), lumpedPointMovement::state(), and lumpedPointState::writeVTP().
void writeZonesVTP (const fileName & file, const polyMesh & mesh, const pointField & points0) const
Write pressure-zones geometry, write as VTK PolyData format.
Definition at line 166 of file lumpedPointMovementWriter.C.
void writeVTP (const fileName & file, const polyMesh & mesh, const labelUList & patchIds, const pointField & points0) const
Write displaced geometry according to the current state,.
write as VTK PolyData format.
Definition at line 296 of file lumpedPointMovementWriter.C.
void writeVTP (const fileName & file, const lumpedPointState & state, const polyMesh & mesh, const labelUList & patchLst, const pointField & points0) const
Write displaced geometry according to the specified state,.
write as VTK PolyData format.
Definition at line 308 of file lumpedPointMovementWriter.C.
static IOobject selectIO (const IOobject & io, const fileName & altFile, const word & ioName = "") inline static
Deprecated(2018-08) compatibility method.
Deprecated:
(2018-08) - use IOobject::selectIO directly
Definition at line 746 of file lumpedPointMovement.H.
Member Data Documentation
const Foam::Enum< Foam::lumpedPointMovement::outputFormatType > formatNames static
Names for the output format types.
Definition at line 284 of file lumpedPointMovement.H.
Referenced by lumpedPointMovement::readDict().
const Foam::Enum< Foam::lumpedPointMovement::scalingType > scalingNames static
Names for the scaling types.
Definition at line 289 of file lumpedPointMovement.H.
const Foam::word canonicalName static
The canonical name ("lumpedPointMovement") for the dictionary.
Definition at line 430 of file lumpedPointMovement.H.
The documentation for this class was generated from the following files:
src/lumpedPointMotion/movement/lumpedPointMovement.H
src/lumpedPointMotion/movement/lumpedPointMovement.C
src/lumpedPointMotion/movement/lumpedPointMovementI.H
src/lumpedPointMotion/movement/lumpedPointMovementWriter.C