OpenFOAM: surfaceFilmModel Class Reference
surfaceFilmModel Class Reference abstract
Base class for surface film models.
Public Member Functions
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, surfaceFilmModel, mesh,(const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType),(modelType, mesh, g, regionType))
surfaceFilmModel ()
Constructor.
virtual ~surfaceFilmModel ()
Destructor.
virtual scalar CourantNumber () const =0
Courant number evaluation.
virtual tmp
< volScalarField::Internal > Srho () const =0
Return total mass source - Eulerian phase only.
virtual tmp
< volScalarField::Internal > Srho (const label i) const =0
Return mass source for specie i - Eulerian phase only.
virtual tmp
< volScalarField::Internal > Sh () const =0
Return enthalpy source - Eulerian phase only.
virtual void evolve ()=0
Main driver routing to evolve the region - calls other evolves.
Static Public Member Functions
static autoPtr< surfaceFilmModel > New (const fvMesh &mesh, const dimensionedVector &g, const word &regionType="surfaceFilm")
Return a reference to the selected surface film model.
Static Public Attributes
static const dimensionedScalar Tref
Reference temperature for enthalpy.
Detailed Description
Base class for surface film models.
Source files
surfaceFilmModel.H
surfaceFilmModelI.H
surfaceFilmModel.C
surfaceFilmModelNew.C
Definition at line 51 of file surfaceFilmModel.H.
Constructor & Destructor Documentation
surfaceFilmModel ()
Constructor.
Definition at line 45 of file surfaceFilmModel.C.
~surfaceFilmModel () virtual
Destructor.
Definition at line 51 of file surfaceFilmModel.C.
Member Function Documentation
TypeName ("surfaceFilmModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , surfaceFilmModel , mesh , (const word &modelType, const fvMesh &mesh, const dimensionedVector &g, const word &regionType) , (modelType, mesh, g, regionType))
autoPtr< surfaceFilmModel > New (const fvMesh & mesh, const dimensionedVector & g, const word & regionType = "surfaceFilm") static
Return a reference to the selected surface film model.
Definition at line 35 of file surfaceFilmModelNew.C.
References TimePaths::constant(), dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, g, Foam::Info, mesh, IOobject::MUST_READ, IOobject::NO_WRITE, dictionary::readEntry(), and fvMesh::time().
virtual scalar CourantNumber () const pure virtual
Courant number evaluation.
Implemented in kinematicSingleLayer, and noFilm.
virtual tmp<volScalarField::Internal> Srho () const pure virtual
Return total mass source - Eulerian phase only.
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
virtual tmp<volScalarField::Internal> Srho (const label i) const pure virtual
Return mass source for specie i - Eulerian phase only.
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
virtual tmp<volScalarField::Internal> Sh () const pure virtual
Return enthalpy source - Eulerian phase only.
Implemented in kinematicSingleLayer, thermoSingleLayer, and noFilm.
virtual void evolve () pure virtual
Main driver routing to evolve the region - calls other evolves.
Implemented in surfaceFilmRegionModel, and noFilm.
Member Data Documentation
const dimensionedScalar Tref static
Reference temperature for enthalpy.
Definition at line 76 of file surfaceFilmModel.H.
Referenced by thermoSingleLayer::hs().
The documentation for this class was generated from the following files:
src/regionModels/surfaceFilmModels/surfaceFilmModel/surfaceFilmModel.H
src/regionModels/surfaceFilmModels/surfaceFilmModel/surfaceFilmModel.C
src/regionModels/surfaceFilmModels/surfaceFilmModel/surfaceFilmModelNew.C