OpenFOAM: correctedSnGrad< Type > Class Template Reference
correctedSnGrad< Type > Class Template Reference
Surface normal gradient schemes
Simple central-difference snGrad scheme with non-orthogonal correction.
Public Member Functions
TypeName ("corrected")
Runtime type information.
correctedSnGrad (const fvMesh &mesh)
Construct from mesh.
correctedSnGrad (const fvMesh &mesh, Istream &)
Construct from mesh and data stream.
virtual ~correctedSnGrad ()
Destructor.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > fullGradCorrection (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the correctedSnGrad.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the correctedSnGrad.
template<>
tmp< surfaceScalarField > correction (const volScalarField &vsf) const
template<>
tmp< surfaceVectorField > correction (const volVectorField &vvf) const
template<>
Foam::tmp
< Foam::surfaceScalarField > correction (const volScalarField &vsf) const
template<>
Foam::tmp
< Foam::surfaceVectorField > correction (const volVectorField &vvf) const
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Detailed Description
template<class Type>
class Foam::fv::correctedSnGrad< Type >
Simple central-difference snGrad scheme with non-orthogonal correction.
Source files
correctedSnGrad.H
correctedSnGrad.C
Definition at line 55 of file correctedSnGrad.H.
Constructor & Destructor Documentation
correctedSnGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 80 of file correctedSnGrad.H.
correctedSnGrad (const fvMesh & mesh, Istream &) inline
Construct from mesh and data stream.
Definition at line 89 of file correctedSnGrad.H.
~correctedSnGrad () virtual
Destructor.
Definition at line 31 of file correctedSnGrad.C.
Member Function Documentation
TypeName ("corrected")
Runtime type information.
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements snGradScheme< Type >.
Definition at line 107 of file correctedSnGrad.H.
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from snGradScheme< Type >.
Definition at line 117 of file correctedSnGrad.H.
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > fullGradCorrection (const GeometricField< Type, fvPatchField, volMesh > & vf) const
Return the explicit correction to the correctedSnGrad.
for the given field using the gradient of the field
Definition at line 40 of file correctedSnGrad.C.
References Foam::fvc::dotInterpolate(), Foam::fac::grad(), fvSchemes::gradScheme(), mesh, IOobject::name(), Foam::New(), surfaceInterpolation::nonOrthCorrectionVectors(), and tmp< T >::ref().
Foam::tmp< Foam::GeometricField< Type, Foam::fvsPatchField, Foam::surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the correctedSnGrad.
for the given field using the gradients of the field components
Reimplemented from snGradScheme< Type >.
Definition at line 66 of file correctedSnGrad.C.
tmp< surfaceScalarField > correction (const volScalarField & vsf) const
tmp< surfaceVectorField > correction (const volVectorField & vvf) const
Foam::tmp< Foam::surfaceScalarField > correction (const volScalarField & vsf) const
Definition at line 31 of file correctedSnGrads.C.
Foam::tmp< Foam::surfaceVectorField > correction (const volVectorField & vvf) const
Definition at line 42 of file correctedSnGrads.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/correctedSnGrad/correctedSnGrad.H
src/finiteVolume/finiteVolume/snGradSchemes/correctedSnGrad/correctedSnGrad.C