OpenFOAM: autoPtr< T > Class Template Reference
autoPtr< T > Class Template Reference
Pointer management similar to std::unique_ptr, with some additional methods and type checking.
Inherited by LList< Foam::autoPtr< Foam::regExpPosix > >.
Public Types
typedef T element_type
Type of object being managed.
typedef T * pointer
Pointer to type of object being managed.
Public Member Functions
constexpr autoPtr () noexcept
Construct with no managed object.
constexpr autoPtr (std::nullptr_t) noexcept
Construct with no managed object (literal nullptr).
autoPtr (T *p) noexcept
Construct, taking ownership of the pointer.
autoPtr (autoPtr< T > &&ap) noexcept
Move construct, transferring ownership.
template<class U >
autoPtr (autoPtr< U > &&ap)
Move construct, transferring ownership from derived type.
autoPtr (const autoPtr< T > &ap) noexcept
A move construct disguised as a copy construct (transfers ownership)
~autoPtr () noexcept
Deletes the managed object if such is present.
bool empty () const noexcept
True if the managed pointer is null.
bool valid () const noexcept
True if the managed pointer is non-null.
T * get () noexcept
Return pointer to managed object without nullptr checking.
const T * get () const noexcept
Return const pointer to managed object without nullptr checking.
T & ref ()
Return reference to the managed object without nullptr checking.
T * release () noexcept
Return pointer to the managed object and release ownership.
T * ptr () noexcept
Return pointer to the managed object and release ownership. Identical behaviour to release().
void clear () noexcept
Delete managed object and set pointer to nullptr.
void reset (T *p=nullptr) noexcept
Delete managed object and set to new given pointer.
void reset (autoPtr< T > &&ap) noexcept
Delete managed object and set to new given pointer.
void swap (autoPtr< T > &other) noexcept
Swaps the managed object with other autoPtr.
template<class... Args>
autoPtr< T > clone (Args &&...args) const
Construct copy by invoking clone on underlying managed object.
T & operator* ()
Return reference to the managed object.
const T & operator* () const
Return const reference to the object.
T * operator-> ()
Dereferences (non-const) pointer to the managed object.
const T * operator-> () const
Dereferences (const) pointer to the managed object.
T & operator() ()
Return reference to the object data.
const T & operator() () const
Return const reference to the object data.
operator const T & () const
Deprecated(2019-01) Automatic cast conversion to underlying type.
operator const T * () const noexcept
Cast to pointer type.
operator T * () noexcept
Cast to pointer type.
operator bool () const noexcept
True if the managed pointer is non-null - same as valid()
void operator= (autoPtr< T > &&ap) noexcept
Transfer object ownership from parameter.
template<class U >
void operator= (autoPtr< U > &&ap) noexcept
Transfer object ownership from parameter.
void operator= (const autoPtr< T > &ap) noexcept
A move assignment disguised as a copy assignment.
void operator= (std::nullptr_t) noexcept
Clear via assignment from literal nullptr.
void set (T *p) noexcept
Deprecated(2018-02) Identical to reset().
void operator= (T *p)=delete
Deprecated(2018-02) No copy assignment from plain pointer.
template<class... Args>
Foam::autoPtr< T > New (Args &&...args)
template<class U , class... Args>
Foam::autoPtr< T > NewFrom (Args &&...args)
template<class... Args>
Foam::autoPtr< T > clone (Args &&...args) const
Static Public Member Functions
template<class... Args>
static autoPtr< T > New (Args &&...args)
Construct autoPtr of T with forwarding arguments.
template<class U , class... Args>
static autoPtr< T > NewFrom (Args &&...args)
Construct autoPtr from derived type with forwarding arguments.
Detailed Description
template<class T>
class Foam::autoPtr< T >
Pointer management similar to std::unique_ptr, with some additional methods and type checking.
Note
Parts of the interface now mirror std::unique_ptr, but since it pre-dates both C++11 and std::unique_ptr, it has some additional idiosyncrasies. The const-reference constructors and assignment operators actually use move semantics to allow their participation in default constructible, default assignable classes.
Source files
autoPtr.H
autoPtrI.H
Definition at line 49 of file HashPtrTable.H.
Member Typedef Documentation
typedef T element_type
Type of object being managed.
Definition at line 76 of file autoPtr.H.
typedef T* pointer
Pointer to type of object being managed.
Definition at line 81 of file autoPtr.H.
Constructor & Destructor Documentation
constexpr autoPtr () inline noexcept
Construct with no managed object.
Definition at line 46 of file autoPtrI.H.
constexpr autoPtr (std::nullptr_t) inline noexcept
Construct with no managed object (literal nullptr).
Definition at line 53 of file autoPtrI.H.
autoPtr (T * p) inline explicit noexcept
Construct, taking ownership of the pointer.
Definition at line 60 of file autoPtrI.H.
autoPtr (autoPtr< T > && ap) inline noexcept
Move construct, transferring ownership.
Definition at line 67 of file autoPtrI.H.
autoPtr (autoPtr< U > && ap) inline explicit
Move construct, transferring ownership from derived type.
U must be derivable from T
Note
Future check for std::is_base_of ?
Definition at line 75 of file autoPtrI.H.
autoPtr (const autoPtr< T > & ap) inline noexcept
A move construct disguised as a copy construct (transfers ownership)
Remarks
This should ideally be deleted - pending cleanup of code currently relying on this behaviour.
Definition at line 149 of file autoPtr.H.
~autoPtr () inline noexcept
Deletes the managed object if such is present.
Definition at line 84 of file autoPtrI.H.
Member Function Documentation
static autoPtr<T> New (Args &&... args) inline static
Construct autoPtr of T with forwarding arguments.
Parameters
args list of arguments with which an instance of T will be constructed.
Note
Similar to std::make_unique, but the overload for array types is not disabled.
Referenced by polyMeshAdder::add(), subBody::body(), Foam::loadPointField(), reader::mesh(), motionInterpolation::New(), rigidBody::New(), RASModelVariables::New(), ignitionSite::iNew::operator()(), UnsortedMeshedSurface< Face >::read(), dictionary::read(), regionSplit::reduceRegions(), solidMixtureProperties::rho(), liquidMixtureProperties::Tc(), colourTable::value(), mapDistribute::whichTransform(), boundaryPatch::~boundaryPatch(), and dictionary::~dictionary().
static autoPtr<T> NewFrom (Args &&... args) inline static
Construct autoPtr from derived type with forwarding arguments.
Parameters
args list of arguments with which an instance of U will be constructed.
Note
Similar to New but for derived types. Future check for std::is_base_of ?
bool empty () const inline noexcept
True if the managed pointer is null.
Definition at line 93 of file autoPtrI.H.
bool valid () const inline noexcept
True if the managed pointer is non-null.
Definition at line 100 of file autoPtrI.H.
Referenced by snappySnapDriver::detectNearSurfaces(), Foam::writeDimField(), Foam::writePointField(), Foam::writeVolField(), vtkWrite::writeVolFields(), and medialAxisMeshMover::~medialAxisMeshMover().
T * get () inline noexcept
Return pointer to managed object without nullptr checking.
Pointer remains under autoPtr management.
Definition at line 107 of file autoPtrI.H.
const T * get () const inline noexcept
Return const pointer to managed object without nullptr checking.
Pointer remains under autoPtr management.
Definition at line 114 of file autoPtrI.H.
T & ref () inline
Return reference to the managed object without nullptr checking.
When get() == nullptr, additional guards may be required to avoid inadvertent access to a nullptr.
Definition at line 121 of file autoPtrI.H.
Referenced by vtkCloud::writeFields(), Foam::vtk::writePointSet(), Foam::writeVolField(), and ensightWrite::writeVolFields().
T * release () inline noexcept
Return pointer to the managed object and release ownership.
Definition at line 128 of file autoPtrI.H.
Referenced by PtrList< T >::append(), PtrList< T >::set(), and HashPtrTable< T, Key, Hash >::set().
T * ptr () inline noexcept
Return pointer to the managed object and release ownership. Identical behaviour to release().
Note
Provided for method naming consistent with Foam::tmp
Definition at line 137 of file autoPtrI.H.
Referenced by exprResult::setObjectResult(), exprResult::setObjectResultImpl(), and regIOobject::store().
void clear () inline noexcept
Delete managed object and set pointer to nullptr.
Definition at line 144 of file autoPtrI.H.
void reset (T * p = nullptr) inline noexcept
Delete managed object and set to new given pointer.
Definition at line 151 of file autoPtrI.H.
References reset().
Referenced by polyMeshAdder::add(), variablesSet::allocateRenamedField(), STLCore::detectBinaryHeader(), snappySnapDriver::detectNearSurfaces(), distributedTriSurfaceMesh::distribute(), if(), and medialAxisMeshMover::~medialAxisMeshMover().
void reset (autoPtr< T > && ap) inline noexcept
Delete managed object and set to new given pointer.
Remarks
Same as move assign, but better for code documentation
Definition at line 159 of file autoPtrI.H.
References p.
void swap (autoPtr< T > & other) inline noexcept
Swaps the managed object with other autoPtr.
Definition at line 166 of file autoPtrI.H.
References reset().
autoPtr<T> clone (Args &&... args) const inline
Construct copy by invoking clone on underlying managed object.
A no-op if no pointer is managed
Parameters
args list of arguments for clone
T & operator* () inline
Return reference to the managed object.
FatalError if no pointer is managed
Definition at line 191 of file autoPtrI.H.
Referenced by autoPtr< Foam::distributionModel >::autoPtr().
const T & operator* () const inline
Return const reference to the object.
FatalError if no pointer is managed
Definition at line 204 of file autoPtrI.H.
T * operator-> () inline
Dereferences (non-const) pointer to the managed object.
FatalError if no pointer is managed
Definition at line 211 of file autoPtrI.H.
const T * operator-> () const inline
Dereferences (const) pointer to the managed object.
FatalError if no pointer is managed
Definition at line 224 of file autoPtrI.H.
T & operator() () inline
Return reference to the object data.
FatalError if no pointer is managed
Definition at line 231 of file autoPtrI.H.
const T & operator() () const inline
Return const reference to the object data.
FatalError if no pointer is managed
Definition at line 238 of file autoPtrI.H.
References Foam::operator*().
operator const T & () const inline
Deprecated(2019-01) Automatic cast conversion to underlying type.
FatalError if no pointer is managed
Deprecated:
(2019-01) Can result in inadvertent conversions where the user should really know or check if the pointer is valid prior to using.
Definition at line 307 of file autoPtr.H.
operator const T * () const inline noexcept
Cast to pointer type.
Definition at line 315 of file autoPtr.H.
operator T * () inline noexcept
Cast to pointer type.
Definition at line 320 of file autoPtr.H.
operator bool () const inline explicit noexcept
True if the managed pointer is non-null - same as valid()
Definition at line 245 of file autoPtrI.H.
References Foam::operator*().
void operator= (autoPtr< T > && ap) inline noexcept
Transfer object ownership from parameter.
Definition at line 252 of file autoPtrI.H.
void operator= (autoPtr< U > && ap) inline noexcept
Transfer object ownership from parameter.
Definition at line 264 of file autoPtrI.H.
void operator= (const autoPtr< T > & ap) inline noexcept
A move assignment disguised as a copy assignment.
Remarks
Non-standard definition - should just be movable
Definition at line 344 of file autoPtr.H.
void operator= (std::nullptr_t) inline noexcept
Clear via assignment from literal nullptr.
Definition at line 275 of file autoPtrI.H.
void set (T * p) inline noexcept
Deprecated(2018-02) Identical to reset().
Note
Provided for backward compatibility - the older version enforced a run-time check (Fatal if pointer was already set) but this was rarely used.
Deprecated:
(2018-02) Identical to reset().
Definition at line 368 of file autoPtr.H.
Referenced by distributedTriSurfaceMesh::findNearest(), and distributedTriSurfaceMesh::getVolumeType().
void operator= (T * p) delete
Deprecated(2018-02) No copy assignment from plain pointer.
Deprecated:
(2018-02) Convenient, but uncontrolled access
Foam::autoPtr<T> New (Args &&... args) inline
Definition at line 29 of file autoPtrI.H.
Foam::autoPtr<T> NewFrom (Args &&... args) inline
Definition at line 37 of file autoPtrI.H.
References args, and T.
Foam::autoPtr<T> clone (Args &&... args) const inline
Definition at line 177 of file autoPtrI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/HashTables/HashPtrTable/HashPtrTable.H
src/OpenFOAM/memory/autoPtr/autoPtr.H
src/OpenFOAM/memory/autoPtr/autoPtrI.H