OpenFOAM: seriesWriter Class Reference
seriesWriter Class Reference
Provides a means of accumulating and generating VTK file series.
Public Member Functions
seriesWriter ()=default
Construct an empty series.
seriesWriter (const seriesWriter &)=default
Copy construct.
seriesWriter (seriesWriter &&)=default
Move construct.
seriesWriter & operator= (const seriesWriter &)=default
Copy assignment.
seriesWriter & operator= (seriesWriter &&)=default
Move assignment.
~seriesWriter ()=default
Destructor.
bool empty () const noexcept
True if there are no data sets.
label size () const noexcept
The number of data sets.
void clear ()
Clear entries.
bool append (const fileNameInstant &inst)
Append the specified file instant.
bool append (fileNameInstant &&inst)
Append the specified file instant.
bool append (scalar timeValue, const fileName &file)
Append the specified file instant.
bool append (scalar timeValue, fileName &&file)
Append the specified file instant.
label load (const fileName &seriesName, const bool checkFiles=false, const scalar restartTime=ROOTVGREAT)
Clear contents and reload by parsing the specified file.
label scan (const fileName &seriesName, const scalar restartTime=ROOTVGREAT)
Clear contents and scan directory for files.
bool removeNewer (const scalar timeValue)
Remove entries that are greater_equal the time value.
void sort ()
Sort by time value and by file name.
void print (Ostream &os) const
Print file series as (JSON format)
void write (const fileName &seriesName) const
Write file series as (JSON format) to disk.
Static Public Member Functions
static fileName base (const fileName &outputName, char sep= '_')
Extract the base name for a file series.
static word suffix (const fileName &file, char sep= '_')
Extract the time-varying ending of files.
static Ostream & print (Ostream &os, const fileName &seriesName, const UList< instant > &series, const char sep= '_')
Print file series (JSON format) for specified time instances.
static void write (const fileName &base, const UList< instant > &series, const char sep= '_')
Write file series (JSON format) to disk, for specified instances.
static Ostream & print (Ostream &os, const UList< fileNameInstant > &series)
Print file series (JSON format) for specified time instances.
static void write (const fileName &seriesName, const UList< fileNameInstant > &series)
Write file series (JSON format) to disk, for specified instances.
Detailed Description
Provides a means of accumulating and generating VTK file series.
The VTK file series format is a simple JSON format with the following type of content:
{
  "file-series-version" : "1.0",
  "files": [
    { "name" : "file1.vtk", "time" : 10 },
    { "name" : "file2.vtk", "time" : 20 },
    { "name" : "file3.vtk", "time" : 30 },
  ]
}
The append() operations include various sanity checks. Entries with an empty name are ignored. If an entry with an identical name already exists, its place will be overwritten with the new time value.
Source files
foamVtkSeriesWriter.H
foamVtkSeriesWriter.C
Definition at line 71 of file foamVtkSeriesWriter.H.
Constructor & Destructor Documentation
seriesWriter () default
Construct an empty series.
seriesWriter (const seriesWriter &) default
Copy construct.
seriesWriter (seriesWriter &&) default
Move construct.
~seriesWriter () default
Destructor.
Member Function Documentation
seriesWriter& operator= (const seriesWriter &) default
Copy assignment.
seriesWriter& operator= (seriesWriter &&) default
Move assignment.
Foam::fileName base (const fileName & outputName, char sep = '_') static
Extract the base name for a file series.
Parameters
outputName The name of the data output file Eg, "somefile_0001.vtk" would extract to "somefile.vtk"
sep The separator used between file stem and suffix.
Definition at line 87 of file foamVtkSeriesWriter.C.
Foam::word suffix (const fileName & file, char sep = '_') static
Extract the time-varying ending of files.
Parameters
file The name of the file Eg, "somefile_0001.vtk" would extract to "0001"
sep The separator used between file stem and suffix.
Definition at line 117 of file foamVtkSeriesWriter.C.
Foam::Ostream & print (Ostream & os, const fileName & seriesName, const UList< instant > & series, const char sep = '_') static
Print file series (JSON format) for specified time instances.
Parameters
os The output stream
base The name for the series (eg, "path/file.vtk")
series The list of suffix/value entries
sep The separator used between file stem and suffix.
Definition at line 147 of file foamVtkSeriesWriter.C.
Referenced by seriesWriter::write().
void write (const fileName & base, const UList< instant > & series, const char sep = '_') static
Write file series (JSON format) to disk, for specified instances.
Parameters
base The name for the series (eg, "path/file.vtk")
series The list of suffix/value entries
sep The separator used between file stem and suffix.
Definition at line 229 of file foamVtkSeriesWriter.C.
Foam::Ostream & print (Ostream & os, const UList< fileNameInstant > & series) static
Print file series (JSON format) for specified time instances.
Since the VTK file series does not currently (OCT-2018) support sub-directories, these will be stripped on output.
Parameters
os The output stream
series The list of filename/value entries
Definition at line 194 of file foamVtkSeriesWriter.C.
void write (const fileName & seriesName, const UList< fileNameInstant > & series) static
Write file series (JSON format) to disk, for specified instances.
Parameters
seriesName The name for the series (eg, "path/file.vtk")
series The list of filename/value entries
Definition at line 250 of file foamVtkSeriesWriter.C.
bool empty () const inline noexcept
True if there are no data sets.
Definition at line 23 of file foamVtkSeriesWriterI.H.
Foam::label size () const inline noexcept
The number of data sets.
Definition at line 29 of file foamVtkSeriesWriterI.H.
void clear () inline
Clear entries.
Definition at line 35 of file foamVtkSeriesWriterI.H.
bool append (const fileNameInstant & inst) inline
Append the specified file instant.
Definition at line 42 of file foamVtkSeriesWriterI.H.
bool append (fileNameInstant && inst) inline
Append the specified file instant.
Definition at line 49 of file foamVtkSeriesWriterI.H.
References Instant< T >::name(), and Instant< T >::value().
bool append (scalar timeValue, const fileName & file) inline
Append the specified file instant.
Definition at line 59 of file foamVtkSeriesWriterI.H.
bool append (scalar timeValue, fileName && file) inline
Append the specified file instant.
Definition at line 70 of file foamVtkSeriesWriterI.H.
References fileName::name().
Foam::label load (const fileName & seriesName, const bool checkFiles = false, const scalar restartTime = ROOTVGREAT)
Clear contents and reload by parsing the specified file.
Parameters
seriesName the base name of the series to scan, without the ".series" ending.
checkFiles verify that the files also exist
restartTime ignore entries with a time greater/equal to the specified restart time.
Returns
the number of entries
Definition at line 362 of file foamVtkSeriesWriter.C.
Foam::label scan (const fileName & seriesName, const scalar restartTime = ROOTVGREAT)
Clear contents and scan directory for files.
The expected xml header content is a comment with the following:
*    <!-- ... time='3.14159' ... -->
*
Parameters
seriesName the base name of the series to scan, without the ".series" ending.
restartTime ignore entries with a time greater/equal to the specified restart time.
Returns
the number of entries
Definition at line 581 of file foamVtkSeriesWriter.C.
bool removeNewer (const scalar timeValue)
Remove entries that are greater_equal the time value.
Returns
True if the contents changed
Definition at line 712 of file foamVtkSeriesWriter.C.
void sort ()
Sort by time value and by file name.
Definition at line 742 of file foamVtkSeriesWriter.C.
void print (Ostream & os) const inline
Print file series as (JSON format)
Definition at line 82 of file foamVtkSeriesWriterI.H.
void write (const fileName & seriesName) const inline
Write file series as (JSON format) to disk.
Definition at line 88 of file foamVtkSeriesWriterI.H.
References seriesWriter::print().
The documentation for this class was generated from the following files:
src/fileFormats/vtk/file/foamVtkSeriesWriter.H
src/fileFormats/vtk/file/foamVtkSeriesWriter.C
src/fileFormats/vtk/file/foamVtkSeriesWriterI.H