OpenFOAM: functionObject Class Reference
functionObject Class Reference abstract
Abstract base-class for Time/database function objects.
Classes
class unavailableFunctionObject
Abstract functionObject to report when a real version is unavailable.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (autoPtr, functionObject, dictionary,(const word &name, const Time &runTime, const dictionary &dict),(name, runTime, dict))
functionObject (const word &name)
Construct from components.
autoPtr< functionObject > clone () const
Return clone.
virtual ~functionObject ()=default
Destructor.
const word & name () const
Return the name of this functionObject.
virtual bool read (const dictionary &dict)
Read and set the function object if its data have changed.
virtual bool execute ()=0
Called at each ++ or += of the time-loop.
virtual bool execute (const label subIndex)
Execute using the specified subIndex.
virtual bool write ()=0
Called at each ++ or += of the time-loop.
virtual bool end ()
Called when Time::run() determines that the time-loop exits.
virtual bool adjustTimeStep ()
Called at the end of Time::adjustDeltaT() if adjustTime is true.
virtual bool filesModified () const
Did any file get changed during execution?
virtual void updateMesh (const mapPolyMesh &mpm)
Update for changes of mesh.
virtual void movePoints (const polyMesh &mesh)
Update for changes of mesh.
Static Public Member Functions
static autoPtr< functionObject > New (const word &name, const Time &runTime, const dictionary &dict)
Select from dictionary, based on its "type" entry.
Public Attributes
bool log
Switch write log to Info.
Static Public Attributes
static int debug
static bool postProcess
Global post-processing mode switch.
static word outputPrefix
Directory prefix.
Protected Member Functions
word scopedName (const word &name) const
Return a scoped name, e.g. used to construct local field names.
Detailed Description
Abstract base-class for Time/database function objects.
See Also
Foam::functionObjectList Foam::functionObjects::timeControl
Source files
functionObject.H
functionObject.C
Definition at line 226 of file functionObject.H.
Constructor & Destructor Documentation
functionObject (const word & name)
Construct from components.
Definition at line 50 of file functionObject.C.
References functionObject::name().
virtual ~functionObject () virtual default
Destructor.
Member Function Documentation
Foam::word scopedName (const word & name) const protected
Return a scoped name, e.g. used to construct local field names.
Definition at line 42 of file functionObject.C.
Referenced by turbulenceFields::processField().
virtual const word& type () const pure virtual
Runtime type information.
Referenced by fieldExpression::foundObject().
declareRunTimeSelectionTable (autoPtr , functionObject , dictionary , (const word &name, const Time &runTime, const dictionary &dict) , (name, runTime, dict))
autoPtr<functionObject> clone () const inline
Return clone.
Definition at line 296 of file functionObject.H.
Foam::autoPtr< Foam::functionObject > New (const word & name, const Time & runTime, const dictionary & dict) static
Select from dictionary, based on its "type" entry.
Definition at line 60 of file functionObject.C.
const Foam::word & name () const
Return the name of this functionObject.
Definition at line 124 of file functionObject.C.
Referenced by forces::createFiles(), fieldExpression::foundObject(), functionObject::functionObject(), and fieldValue::New().
bool read (const dictionary & dict) virtual
Read and set the function object if its data have changed.
Reimplemented in surfaceFieldValue, stabilityBlendingFactor, forces, sampledSurfaces, vtkWrite, regionSizeDistribution, pressure, volFieldValue, energyTransport, forceCoeffs, fieldAverage, ensightWrite, externalCoupled, extractEulerianParticles, fluxSummary, scalarTransport, sizeDistribution, momentum, sampledSets, probes, vtkCloud, turbulenceFields, timeControl, streamLineBase, runTimePostProcessing, dataCloud, areaWrite, wallBoundedStreamLine, nearWallFields, codedFunctionObject, regionFunctionObject, fieldMinMax, streamLine, thermoCoupleProbes, fieldExtents, reference, hydrostaticPressure, setFlow, fieldValueDelta, ddt2, limitFields, Curle, writeObjects, blendingFactor, valueAverage, solverInfo, fieldCoordinateSystemTransform, mapFields, particleDistribution, patchProbes, systemCall, histogram, wallShearStress, zeroGradient, reactionsSensitivityAnalysis< chemistryType >, icoUncoupledKinematicCloud, fieldValue, proudmanAcousticPower, derivedFields, heatTransferCoeff, energySpectrum, wallHeatFlux, surfaceInterpolate, timeActivatedFileUpdate, surfaceDistance, continuityError, abort, columnAverage, AMIWeights, setTimeStepFunctionObject, readFields, timeInfo, cloudInfo, phaseForces, CourantNo, runTimeControl, sixDoFRigidBodyState, DESModelRegions, PecletNo, yPlus, fieldsExpression, processorField, removeRegisteredObject, dsmcFields, pointHistory, writeDictionary, moleFractions< ThermoType >, writeCellCentres, XiReactionRate, writeCellVolumes, fieldExpression, writeFreeSurface, specieReactionRates< ChemistryModelType >, and randomise.
Definition at line 130 of file functionObject.C.
virtual bool execute () pure virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual executeControl behaviour and forces execution (used in post-processing mode)
Implemented in forces, sampledSurfaces, vtkWrite, regionSizeDistribution, energyTransport, forceCoeffs, fieldAverage, functionObject::unavailableFunctionObject, ensightWrite, extractEulerianParticles, fluxSummary, externalCoupled, scalarTransport, sizeDistribution, momentum, sampledSets, probes, vtkCloud, turbulenceFields, streamLineBase, runTimePostProcessing, dataCloud, areaWrite, timeControl, nearWallFields, fieldMinMax, fieldExtents, codedFunctionObject, hydrostaticPressure, thermoCoupleProbes, fieldValueDelta, setFlow, ddt2, limitFields, writeObjects, valueAverage, solverInfo, fieldCoordinateSystemTransform, mapFields, particleDistribution, systemCall, histogram, wallShearStress, zeroGradient, reactionsSensitivityAnalysis< chemistryType >, icoUncoupledKinematicCloud, fieldValue, proudmanAcousticPower, derivedFields, energySpectrum, wallHeatFlux, surfaceInterpolate, timeActivatedFileUpdate, surfaceDistance, continuityError, abort, columnAverage, AMIWeights, setTimeStepFunctionObject, readFields, timeInfo, cloudInfo, phaseForces, runTimeControl, sixDoFRigidBodyState, DESModelRegions, yPlus, fieldsExpression, processorField, removeRegisteredObject, dsmcFields, writeDictionary, moleFractions< ThermoType >, pointHistory, writeCellCentres, XiReactionRate, writeCellVolumes, fieldExpression, specieReactionRates< ChemistryModelType >, parProfiling, and writeFreeSurface.
bool execute (const label subIndex) virtual
Execute using the specified subIndex.
The base implementation is a no-op.
Parameters
subIndex an execution sub-index corresponding to a sub-cycle or something similar.
Reimplemented in externalCoupled, and timeControl.
Definition at line 141 of file functionObject.C.
virtual bool write () pure virtual
Called at each ++ or += of the time-loop.
postProcess overrides the usual writeControl behaviour and forces writing always (used in post-processing mode)
Implemented in surfaceFieldValue, stabilityBlendingFactor, forces, sampledSurfaces, vtkWrite, regionSizeDistribution, energyTransport, volFieldValue, forceCoeffs, fieldAverage, functionObject::unavailableFunctionObject, ensightWrite, extractEulerianParticles, externalCoupled, fluxSummary, scalarTransport, sizeDistribution, momentum, sampledSets, probes, vtkCloud, turbulenceFields, streamLineBase, runTimePostProcessing, dataCloud, timeControl, areaWrite, nearWallFields, fieldMinMax, codedFunctionObject, fieldExtents, hydrostaticPressure, fieldValueDelta, setFlow, ddt2, limitFields, thermoCoupleProbes, writeObjects, valueAverage, solverInfo, fieldCoordinateSystemTransform, mapFields, particleDistribution, histogram, blendingFactor, systemCall, wallShearStress, zeroGradient, reactionsSensitivityAnalysis< chemistryType >, icoUncoupledKinematicCloud, fieldValue, proudmanAcousticPower, patchProbes, derivedFields, energySpectrum, wallHeatFlux, surfaceInterpolate, timeActivatedFileUpdate, surfaceDistance, continuityError, abort, columnAverage, AMIWeights, setTimeStepFunctionObject, readFields, timeInfo, cloudInfo, phaseForces, runTimeControl, sixDoFRigidBodyState, DESModelRegions, yPlus, fieldsExpression, processorField, removeRegisteredObject, dsmcFields, pointHistory, writeDictionary, moleFractions< ThermoType >, writeCellCentres, XiReactionRate, writeCellVolumes, fieldExpression, specieReactionRates< ChemistryModelType >, writeFreeSurface, parProfiling, and components.
bool end () virtual
Called when Time::run() determines that the time-loop exits.
The base implementation is a no-op.
Reimplemented in vtkWrite, ensightWrite, externalCoupled, timeControl, codedFunctionObject, systemCall, abort, and parProfiling.
Definition at line 147 of file functionObject.C.
bool adjustTimeStep () virtual
Called at the end of Time::adjustDeltaT() if adjustTime is true.
Reimplemented in timeControl, and setTimeStepFunctionObject.
Definition at line 153 of file functionObject.C.
bool filesModified () const virtual
Did any file get changed during execution?
Reimplemented in timeControl, and timeActivatedFileUpdate.
Definition at line 159 of file functionObject.C.
void updateMesh (const mapPolyMesh & mpm) virtual
Update for changes of mesh.
The base implementation is a no-op.
Reimplemented in surfaceFieldValue, sampledSurfaces, vtkWrite, ensightWrite, momentum, sampledSets, probes, streamLineBase, timeControl, areaWrite, and derivedFields.
Definition at line 165 of file functionObject.C.
void movePoints (const polyMesh & mesh) virtual
Update for changes of mesh.
The base implementation is a no-op.
Reimplemented in surfaceFieldValue, sampledSurfaces, vtkWrite, ensightWrite, momentum, sampledSets, probes, streamLineBase, timeControl, areaWrite, and derivedFields.
Definition at line 169 of file functionObject.C.
Member Data Documentation
int debug static
Definition at line 256 of file functionObject.H.
Referenced by fieldExpression::foundObject().
bool postProcess static
Global post-processing mode switch.
Definition at line 261 of file functionObject.H.
Foam::word outputPrefix static
Directory prefix.
Definition at line 266 of file functionObject.H.
Referenced by meshRefinement::findRegions(), and if().
bool log
Switch write log to Info.
Definition at line 271 of file functionObject.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/functionObjects/functionObject/functionObject.H
src/OpenFOAM/db/functionObjects/functionObject/functionObject.C