OpenFOAM: Enum< EnumType > Class Template Reference
Enum< EnumType > Class Template Reference
Enum is a wrapper around a list of names/values that represent particular enumeration (or int) values. All dictionary searches use a literal (not regex).
Public Types
typedef EnumType value_type
The type of enumeration represented by the Enum.
Public Member Functions
Enum ()=default
Construct null (empty list)
Enum (std::initializer_list< std::pair< EnumType, const char * >> list)
Construct from a values/names list.
bool empty () const noexcept
True if the enumeration list is empty.
label size () const noexcept
The number of name/value pairs for the enumeration.
const List< word > & names () const
The list of enum names, in construction order. Same as toc()
const List< word > & toc () const
The list of enum names, in construction order. Same as names()
List< word > sortedToc () const
The sorted list of enum names.
const List< int > & values () const
The list of enum values, in construction order.
void clear ()
Clear all entries.
void append (std::initializer_list< std::pair< EnumType, const char * >> list)
Append value/key pairs to the lists of known enumerations.
label find (const word &enumName) const
Find the index of the given name.
label find (const EnumType e) const
Find the first index of given enumeration.
bool found (const word &enumName) const
Test if there is an enumeration corresponding to the given name.
bool found (const EnumType e) const
Test if there is a name corresponding to the given enumeration.
EnumType get (const word &enumName) const
The enumeration corresponding to the given name.
EnumType get (const word &enumName, const EnumType deflt) const
The enumeration corresponding to the given name.
const word & get (const EnumType e) const
The name corresponding to the given enumeration.
EnumType get (const word &key, const dictionary &dict) const
Get the key in the dictionary and return the corresponding enumeration element based on its name.
EnumType getOrDefault (const word &key, const dictionary &dict, const EnumType deflt, const bool failsafe=false) const
Find the key in the dictionary and return the corresponding enumeration element based on its name.
bool readEntry (const word &key, const dictionary &dict, EnumType &val, const bool mandatory=true) const
Find entry and assign to T val.
bool readIfPresent (const word &key, const dictionary &dict, EnumType &val) const
Find an entry if present, and assign to T val.
EnumType read (Istream &is) const
Read a word from Istream and return the corresponding enumeration.
bool read (Istream &is, EnumType &val, const bool mandatory=true) const
Read a word from Istream, lookup named enumeration.
void write (const EnumType e, Ostream &os) const
Write the name representation of the enumeration to an Ostream.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write the names as a list to an Ostream.
EnumType operator[] (const word &enumName) const
Return the enumeration corresponding to the given name.
const word & operator[] (const EnumType e) const
Return the first name corresponding to the given enumeration, or an empty word on failure.
const word & operator() (const EnumType e) const
Return the first name corresponding to the given enumeration, or an empty word on failure.
EnumType operator() (const word &enumName, const EnumType deflt) const
Return the enumeration corresponding to the given name, or deflt if the name is not found.
EnumType lookupOrDefault (const word &key, const dictionary &dict, const EnumType deflt, const bool failsafe=false) const
Find the key in the dictionary and return the corresponding enumeration element based on its name.
EnumType FOAM_DEPRECATED_FOR (2018-10,"get() method") lookup(const word &key
Deprecated(2018-10) same as two-parameter get()
Public Attributes
EnumType const dictionary &dict const
Detailed Description
template<class EnumType>
class Foam::Enum< EnumType >
Enum is a wrapper around a list of names/values that represent particular enumeration (or int) values. All dictionary searches use a literal (not regex).
Source files
Enum.H
Enum.C
EnumI.H
Definition at line 47 of file IOstreamOption.H.
Member Typedef Documentation
typedef EnumType value_type
The type of enumeration represented by the Enum.
Definition at line 77 of file Enum.H.
Constructor & Destructor Documentation
Enum () default
Construct null (empty list)
Enum (std::initializer_list< std::pair< EnumType, const char * >> list) explicit
Construct from a values/names list.
Duplicate values are permitted (eg, for aliases). Duplicate names are permitted, but won't make much sense.
Definition at line 28 of file Enum.C.
References i.
Member Function Documentation
bool empty () const inline noexcept
True if the enumeration list is empty.
Definition at line 24 of file EnumI.H.
Foam::label size () const inline noexcept
The number of name/value pairs for the enumeration.
Definition at line 31 of file EnumI.H.
const Foam::wordList & names () const inline
The list of enum names, in construction order. Same as toc()
Definition at line 38 of file EnumI.H.
const Foam::wordList & toc () const inline
The list of enum names, in construction order. Same as names()
Definition at line 45 of file EnumI.H.
Foam::List< Foam::word > sortedToc () const
The sorted list of enum names.
Definition at line 48 of file Enum.C.
const Foam::List< int > & values () const inline
The list of enum values, in construction order.
Definition at line 52 of file EnumI.H.
void clear () inline
Clear all entries.
Definition at line 59 of file EnumI.H.
void append (std::initializer_list< std::pair< EnumType, const char * >> list)
Append value/key pairs to the lists of known enumerations.
Does not check for duplicate entries
Definition at line 60 of file Enum.C.
Foam::label find (const word & enumName) const inline
Find the index of the given name.
Returns
position in list or -1 if not found.
Definition at line 67 of file EnumI.H.
Foam::label find (const EnumType e) const inline
Find the first index of given enumeration.
Returns
position in list or -1 if not found.
Definition at line 74 of file EnumI.H.
bool found (const word & enumName) const inline
Test if there is an enumeration corresponding to the given name.
Definition at line 81 of file EnumI.H.
bool found (const EnumType e) const inline
Test if there is a name corresponding to the given enumeration.
Definition at line 88 of file EnumI.H.
EnumType get (const word & enumName) const
The enumeration corresponding to the given name.
FatalError if not found.
Definition at line 79 of file Enum.C.
Referenced by lumpedPointMovement::readDict().
EnumType get (const word & enumName, const EnumType deflt) const
The enumeration corresponding to the given name.
Returns
The enumeration or default if not found.
Definition at line 96 of file Enum.C.
const Foam::word & get (const EnumType e) const inline
The name corresponding to the given enumeration.
Return an empty word if not found.
Definition at line 95 of file EnumI.H.
EnumType get (const word & key, const dictionary & dict) const
Get the key in the dictionary and return the corresponding enumeration element based on its name.
FatalIOError if anything is incorrect.
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
Definition at line 161 of file Enum.C.
EnumType getOrDefault (const word & key, const dictionary & dict, const EnumType deflt, const bool failsafe = false) const
Find the key in the dictionary and return the corresponding enumeration element based on its name.
Returns
The value found or default if not found in dictionary. FatalIOError if the enumeration is incorrect. Specifying failsafe downgrades the FatalIOError to an IOWarning.
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
deflt fallback if not found
failsafe Warn only on bad enumeration
Definition at line 183 of file Enum.C.
bool readEntry (const word & key, const dictionary & dict, EnumType & val, const bool mandatory = true) const
Find entry and assign to T val.
FatalIOError if the enumeration is incorrect, or when it is mandatory but was not found.
Returns
true if the entry was found.
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
val the value to read into
mandatory the keyword is mandatory
Definition at line 226 of file Enum.C.
bool readIfPresent (const word & key, const dictionary & dict, EnumType & val) const
Find an entry if present, and assign to T val.
FatalIOError if the enumeration is incorrect. Default search: non-recursive with patterns.
Returns
true if the entry was found.
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
val the value to read into
Definition at line 264 of file Enum.C.
Referenced by distributedTriSurfaceMesh::distributedTriSurfaceMesh(), and mappedPatchBase::mappedPatchBase().
EnumType read (Istream & is) const
Read a word from Istream and return the corresponding enumeration.
Definition at line 113 of file Enum.C.
Referenced by addcommsTypeToOpt::writeData().
bool read (Istream & is, EnumType & val, const bool mandatory = true) const
Read a word from Istream, lookup named enumeration.
Returns
true on success. Fatal if mandatory and not found.
Definition at line 132 of file Enum.C.
void write (const EnumType e, Ostream & os) const inline
Write the name representation of the enumeration to an Ostream.
A noop if the enumeration wasn't found.
Definition at line 120 of file EnumI.H.
Foam::Ostream & writeList (Ostream & os, const label shortLen = 0) const inline
Write the names as a list to an Ostream.
Default is without line-breaks.
Definition at line 110 of file EnumI.H.
EnumType operator[] (const word & enumName) const inline
Return the enumeration corresponding to the given name.
FatalError if the name is not found. Identical to single parameter get()
Definition at line 135 of file EnumI.H.
const Foam::word & operator[] (const EnumType e) const inline
Return the first name corresponding to the given enumeration, or an empty word on failure.
Identical to single parameter get()
Definition at line 145 of file EnumI.H.
const Foam::word & operator() (const EnumType e) const inline
Return the first name corresponding to the given enumeration, or an empty word on failure.
Identical to single parameter get()
Definition at line 155 of file EnumI.H.
References Foam::constant::electromagnetic::e.
EnumType operator() (const word & enumName, const EnumType deflt) const inline
Return the enumeration corresponding to the given name, or deflt if the name is not found.
Definition at line 165 of file EnumI.H.
References Foam::constant::electromagnetic::e.
EnumType lookupOrDefault (const word & key, const dictionary & dict, const EnumType deflt, const bool failsafe = false) const inline
Find the key in the dictionary and return the corresponding enumeration element based on its name.
Returns
The value found or default if not found in dictionary. FatalError (or Warning) if the enumeration was incorrect.
Parameters
key Lookup key. Uses LITERAL (not REGEX)
dict dictionary
deflt fallback if not found
failsafe Warn only on bad enumeration
Definition at line 352 of file Enum.H.
EnumType FOAM_DEPRECATED_FOR (2018- 10, "get() method") const
Deprecated(2018-10) same as two-parameter get()
Deprecated:
(2018-10) - use two-parameter get() method
Member Data Documentation
EnumType const dictionary& dict const
Initial value:
{
            return get(key, dict)
Definition at line 369 of file Enum.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstreamOption.H
src/OpenFOAM/primitives/enums/Enum.H
src/OpenFOAM/primitives/enums/Enum.C
src/OpenFOAM/primitives/enums/EnumI.H