OpenFOAM: PtrDynList< T, SizeMin > Class Template Reference
PtrDynList< T, SizeMin > Class Template Reference
A dynamically resizable PtrList with allocation management.
Public Member Functions
constexpr PtrDynList () noexcept
Construct null.
PtrDynList (const label len)
Construct with given capacity.
PtrDynList (const PtrDynList< T, SizeMin > &list)
Copy construct using 'clone()' method on each element.
PtrDynList (PtrDynList< T, SizeMin > &&list)
Move construct.
PtrDynList (UList< T * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
~PtrDynList ()=default
Destructor.
label capacity () const noexcept
Size of the underlying storage.
void setCapacity (const label nElem)
Alter the size of the underlying storage.
void resize (const label newLen)
Alter the addressed list size.
void setSize (const label newLen)
Same as resize()
void reserve (const label nElem)
Reserve allocation space for at least this size.
void clear ()
Clear the addressed list, i.e. set the size to zero.
void clearStorage ()
Clear the list and delete storage.
label expandStorage ()
Expand the addressable size to fit the allocated capacity.
void shrink ()
Shrink the allocated space to the number of elements used.
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers and adjust the addressable size accordingly.
void append (T *ptr)
Append an element to the end of the list.
void append (const autoPtr< T > &aptr)
Move append an element to the end of the list.
void append (const tmp< T > &tptr)
Move or clone append a tmp to the end of the list.
void append (PtrList< T > &&other)
Move append another list to the end of this list.
template<int AnySizeMin>
void append (PtrDynList< T, AnySizeMin > &&other)
Move append another list to the end of this list.
autoPtr< T > remove ()
Remove and return the top element.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< T > set (const label i, T *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< T > set (const label i, const autoPtr< T > &aptr)
Set element to given autoPtr and return old element.
autoPtr< T > set (const label i, const tmp< T > &tptr)
Set element to given tmp and return old element.
void reorder (const labelUList &oldToNew)
Reorder elements. Reordering must be unique (ie, shuffle).
void operator= (const PtrList< T > &list)
Copy (clone) assignment.
void operator= (const PtrDynList< T, SizeMin > &list)
Copy (clone) assignment.
template<int AnySizeMin>
void operator= (const PtrDynList< T, AnySizeMin > &list)
Copy (clone) assignment with different sizing parameters.
void operator= (PtrList< T > &&list)
Move assignment.
void operator= (PtrDynList< T, SizeMin > &&list)
Move assignment.
template<int AnySizeMin>
void operator= (PtrDynList< T, AnySizeMin > &&list)
Move assignment with different sizing parameters.
Public Member Functions inherited from PtrList< T >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< T > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< T > &&list)
Move construct.
PtrList (UList< T * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< T > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
template<class INew >
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
template<class... Args>
PtrList< T > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (T *ptr)
Append an element to the end of the list.
void append (autoPtr< T > &aptr)
Move append an element to the end of the list.
void append (autoPtr< T > &&aptr)
Move append an element to the end of the list.
void append (const tmp< T > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< T > &list)
Transfer into this list and annul the argument list.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< T > set (const label i, T *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< T > set (const label i, autoPtr< T > &aptr)
Set element to given autoPtr and return old element.
autoPtr< T > set (const label i, autoPtr< T > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< T > set (const label i, const tmp< T > &tptr)
Set element to given tmp and return old element.
autoPtr< T > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< T > &list)
Copy assignment.
void operator= (PtrList< T > &&list)
Move assignment.
template<class... Args>
Foam::PtrList< T > clone (Args &&...args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Protected Member Functions inherited from PtrList< T >
template<class INew >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Detailed Description
template<class T, int SizeMin>
class Foam::PtrDynList< T, SizeMin >
A dynamically resizable PtrList with allocation management.
See Also
Foam::UPtrList Foam::PtrList
Source files
PtrDynList.H
PtrDynListI.H
Definition at line 49 of file PtrDynList.H.
Constructor & Destructor Documentation
constexpr PtrDynList () inline noexcept
Construct null.
Definition at line 36 of file PtrDynListI.H.
PtrDynList (const label len) inline explicit
Construct with given capacity.
Definition at line 44 of file PtrDynListI.H.
PtrDynList (const PtrDynList< T, SizeMin > & list) inline
Copy construct using 'clone()' method on each element.
Definition at line 55 of file PtrDynListI.H.
PtrDynList (PtrDynList< T, SizeMin > && list) inline
Move construct.
Definition at line 66 of file PtrDynListI.H.
PtrDynList (UList< T * > & list) inline explicit
Take ownerskip of pointers in the list, set old pointers to null.
Definition at line 78 of file PtrDynListI.H.
~PtrDynList () default
Destructor.
Member Function Documentation
Foam::label capacity () const inline noexcept
Size of the underlying storage.
Definition at line 88 of file PtrDynListI.H.
void setCapacity (const label nElem) inline
Alter the size of the underlying storage.
Definition at line 95 of file PtrDynListI.H.
void resize (const label newLen) inline
Alter the addressed list size.
Definition at line 129 of file PtrDynListI.H.
void setSize (const label newLen) inline
Same as resize()
Definition at line 163 of file PtrDynListI.H.
void reserve (const label nElem) inline
Reserve allocation space for at least this size.
Never shrinks the allocated size, use setCapacity() for that.
Definition at line 112 of file PtrDynListI.H.
void clear () inline
Clear the addressed list, i.e. set the size to zero.
Allocated size does not change
Definition at line 170 of file PtrDynListI.H.
References resize().
void clearStorage () inline
Clear the list and delete storage.
Definition at line 178 of file PtrDynListI.H.
Foam::label expandStorage () inline
Expand the addressable size to fit the allocated capacity.
Returns the previous addressable size.
Definition at line 186 of file PtrDynListI.H.
References clear().
void shrink () inline
Shrink the allocated space to the number of elements used.
Definition at line 198 of file PtrDynListI.H.
Foam::label squeezeNull () inline
Squeeze out intermediate nullptr entries in the list of pointers and adjust the addressable size accordingly.
Returns
the number of non-null entries
Definition at line 215 of file PtrDynListI.H.
void append (T * ptr) inline
Append an element to the end of the list.
Definition at line 224 of file PtrDynListI.H.
void append (const autoPtr< T > & aptr) inline
Move append an element to the end of the list.
Definition at line 233 of file PtrDynListI.H.
void append (const tmp< T > & tptr) inline
Move or clone append a tmp to the end of the list.
Definition at line 240 of file PtrDynListI.H.
References append().
void append (PtrList< T > && other) inline
Move append another list to the end of this list.
Definition at line 247 of file PtrDynListI.H.
References append(), and tmp< T >::ptr().
void append (PtrDynList< T, AnySizeMin > && other) inline
Move append another list to the end of this list.
Definition at line 266 of file PtrDynListI.H.
Foam::autoPtr< T > remove () inline
Remove and return the top element.
Definition at line 285 of file PtrDynListI.H.
const T * set (const label i) const inline
Return const pointer to element (if set) or nullptr.
The return value can be tested as a bool.
Definition at line 304 of file PtrDynListI.H.
Foam::autoPtr< T > set (const label i, T * ptr) inline
Set element to given pointer and return old element (can be null)
Definition at line 312 of file PtrDynListI.H.
References set().
Foam::autoPtr< T > set (const label i, const autoPtr< T > & aptr) inline
Set element to given autoPtr and return old element.
Definition at line 328 of file PtrDynListI.H.
Foam::autoPtr< T > set (const label i, const tmp< T > & tptr) inline
Set element to given tmp and return old element.
Definition at line 339 of file PtrDynListI.H.
References set().
void reorder (const labelUList & oldToNew) inline
Reorder elements. Reordering must be unique (ie, shuffle).
Definition at line 349 of file PtrDynListI.H.
References set().
void operator= (const PtrList< T > & list) inline
Copy (clone) assignment.
Definition at line 361 of file PtrDynListI.H.
void operator= (const PtrDynList< T, SizeMin > & list) inline
Copy (clone) assignment.
Definition at line 377 of file PtrDynListI.H.
void operator= (const PtrDynList< T, AnySizeMin > & list) inline
Copy (clone) assignment with different sizing parameters.
Definition at line 394 of file PtrDynListI.H.
void operator= (PtrList< T > && list) inline
Move assignment.
Definition at line 410 of file PtrDynListI.H.
void operator= (PtrDynList< T, SizeMin > && list) inline
Move assignment.
Definition at line 427 of file PtrDynListI.H.
void operator= (PtrDynList< T, AnySizeMin > && list) inline
Move assignment with different sizing parameters.
Definition at line 445 of file PtrDynListI.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/PtrLists/PtrDynList/PtrDynList.H
src/OpenFOAM/containers/PtrLists/PtrDynList/PtrDynListI.H