OpenFOAM: reader Class Reference
reader Class Reference
Reads CCM files as written by PROSTAR/STARCCM.
Classes
class options
Public Member Functions
reader (const fileName &file, const reader::options &opts)
Open a file for reading.
~reader ()
Destructor (closes file)
const reader::options & option () const
Reference to the reader options.
autoPtr< polyMesh > mesh (const objectRegistry &registry, const fileName &remappingDictName=fileName::null)
Construct the polyMesh from the read geometry.
bool hasGeometry ()
Return true if file has geometry associated with it.
bool hasSolution ()
Return true if file has solutions associated with it.
bool remapMeshInfo (const objectRegistry &registry, const fileName &remappingDictName=fileName::null)
Remap cellTable and boundaryRegion according to dictionary.
void writeMesh (const polyMesh &mesh, IOstream::streamFormat fmt=IOstream::BINARY) const
Write the polyMesh.
void writeAux (const objectRegistry &registry) const
Write cellTable, boundaryRegion and interface information.
bool readGeometry (const scalar scaleFactor=1.0)
Detect and read geometry if possible.
void printInfo () const
Print general information about the mesh.
void clearGeom ()
Clear out some information after obtaining a polyMesh.
const labelList & origCellId () const
Map to original cell Id.
const labelList & origFaceId () const
Map to original face Id.
const interfaceDefinitions & interfaceDefinitionsInfo () const
Return interface definitions map.
const boundaryRegion & boundaryTableInfo () const
Return boundaryRegion table.
const cellTable & cellTableInfo () const
Return cell table.
Map< word > fluids () const
Return a list of names corresponding to fluids.
Map< word > solids () const
Return a list of names corresponding to solids.
const solutionTable & solutions ()
Return table of available solutions.
const fieldTable & fields ()
Return table of available fields.
const fieldTable & lagrangian ()
Return table of available lagrangian fields.
tmp< scalarField > readField (const word &solutionName, const word &fieldName, const bool wallData=false)
Read solution and field combination.
Public Member Functions inherited from base
base ()
Construct null.
~base ()
Destructor: close file.
bool close ()
Explicitly close the file and terminate ccmio access.
Static Public Member Functions
static void warnDuplicates (const word &context, const wordList &lst)
Warn about repeated name.
Additional Inherited Members
Protected Types inherited from STARCDCore
enum fileHeader { HEADER_CEL, HEADER_VRT, HEADER_BND }
Enumeration defining the file headers.
enum fileExt { CEL_FILE, VRT_FILE, BND_FILE, INP_FILE }
Enumeration defining the file extensions.
enum matlType {
starcdFluidType = 1, starcdSolidType = 2, starcdBaffleType = 3, starcdShellType = 4,
starcdLineType = 5, starcdPointType = 6
}
Basic material type for STARCD/PROSTAR files.
enum shapeType {
starcdPoint = 1, starcdLine = 2, starcdShell = 3, starcdHex = 11,
starcdPrism = 12, starcdTet = 13, starcdPyr = 14, starcdPoly = 255
}
Shape-Type for STARCD/PROSTAR files.
Protected Member Functions inherited from base
bool assertNoError (const char *msg) const
check global state for errors and die as required
bool assertNoError (const std::string &msg) const
check global state for errors and die as required
Protected Member Functions inherited from STARCDCore
STARCDCore ()=default
Construct null.
Static Protected Member Functions inherited from base
static bool assertNoError (int err, const char *msg)
Die with msg if there is an error.
static bool assertNoError (int err, const std::string &msg)
Die with msg if there is an error.
Static Protected Member Functions inherited from STARCDCore
static bool readHeader (IFstream &is, const enum fileHeader header)
Read header and check signature PROSTAR_(CELL|VERTEX|BOUNDARY)
static void writeHeader (Ostream &os, const enum fileHeader header)
Write header for fileType (CELL|VERTEX|BOUNDARY)
static fileName starFileName (const fileName &baseName, const enum fileExt ext)
Resolve base file-name for the given file-type.
static void removeFiles (const fileName &baseName)
Remove existing PROSTAR files for the given base file-name.
static label readPoints (IFstream &is, List< point > &points, List< label > &ids)
Read points from a (.vrt) file, return the max prostar id used.
static void writePoints (Ostream &os, const UList< point > &points, const scalar scaleFactor=1.0)
Write header and points to (.vrt) file, optionally with scaling.
Protected Attributes inherited from base
ccmGlobalState * globalState_
Maintain overall global states (error, root-node)
Static Protected Attributes inherited from STARCDCore
static const Map< FixedList
< int, 6 > > starToFoamFaceAddr
Face addressing from PROSTAR faces to OpenFOAM faces.
static const Map< FixedList
< int, 6 > > foamToStarFaceAddr
Face addressing from OpenFOAM faces to PROSTAR faces.
static const char *const defaultBoundaryName
The name for default (unassigned) boundaries.
static const char *const defaultSolidBoundaryName
The name we have chosen for default (unassigned) solid boundaries.
Detailed Description
Reads CCM files as written by PROSTAR/STARCCM.
arbitrary polyhedral meshs
writes interfaces (baffles) to constant/polymesh/interfaces
experimental handling of monitoring (internal) boundaries
does not handle cyclics. Use createPatch to recreate these
does patch names only if they are in the problem description
reads cell and face solution data
reads Lagrangian data
The Default_Boundary_Region (region 0) is a special region that serves two purposes:
it contains all wall and baffle boundaries that have not otherwise been assigned.
it holds the outer bounds of flow domains (fluid/porous/solid)
The CCM node Meshes/FaceBasedTopology/Cells/Interfaces holds the mapping of the corresponding mesh faces, which can be used to merge these internal boundaries.
If solid cells exist, there are three possible courses of action:
Remove all solid cells for subsequent flow calculations. This is the default.
Treat solid cells like fluid cells, but convert the corresponding Default_Boundary_Region to Default_Boundary_Solid for easier identification. This treatment is useful for visualization purposes.
Move solid cells to a separate mesh region. This would be useful for conjugate heat transfer, but is not implemented.
Files
The constant/remapping file is an IOdictionary that is READ_IF_PRESENT and can be used to remap certain information. eg,
    // rename/combine cellTable entries
    //   newName ( listOldNames );
    cellTable
    {
        fluid ( inletRegion outletRegion );
        cat1  ( CAT1 "cat1_(Back|Front|Gamma)" );
    }
    // rename boundary regions
    //   newName oldName;
    boundaryRegion
    {
        inlet_4  inlet_1;
        inlet_5  inlet_2;
        inlet_6  inlet_3;
    }
The constant/boundaryRegion file is an IOMap<dictionary> that is written. It contains the boundary type and names. eg,
    (
        0
        {
            BoundaryType    wall;
            Label           Default_Boundary_Region;
        }
        1
        {
            BoundaryType    inlet;
            Label           inlet_1;
        }
        ...
        4
        {
            BoundaryType    pressure;
            Label           outlet;
        }
    )
The constant/cellTable file is an IOMap<dictionary> that is written. It contains the cellTable information. eg,
    (
        1
        {
            Label           inletRegion;
            MaterialType    fluid;
            MaterialId      1;
        }
        2
        {
            Label           cat1;
            MaterialType    fluid;
            MaterialId      1;
            PorosityId      1;
        }
        3
        {
            Label           outletRegion;
            MaterialType    fluid;
            MaterialId      1;
        }
    )
Note
this class is still under development
any/all of the class names and members may change
Source files
ccmReader.H
ccmReader.C
ccmReaderAux.C
ccmReaderMesh.C
ccmReaderSolution.C
Definition at line 180 of file ccmReader.H.
Constructor & Destructor Documentation
reader (const fileName & file, const reader::options & opts)
Open a file for reading.
Definition at line 650 of file ccmReader.C.
~reader ()
Destructor (closes file)
Definition at line 709 of file ccmReader.C.
Member Function Documentation
void warnDuplicates (const word & context, const wordList & lst) static
Warn about repeated name.
Definition at line 64 of file ccmReaderAux.C.
const Foam::ccm::reader::options & option () const
Reference to the reader options.
Definition at line 718 of file ccmReader.C.
Foam::autoPtr< Foam::polyMesh > mesh (const objectRegistry & registry, const fileName & remappingDictName = fileName::null)
Construct the polyMesh from the read geometry.
provide optional remapping dictionary
Definition at line 2587 of file ccmReaderMesh.C.
References IOobject::AUTO_WRITE, polyMesh::boundaryMesh(), polyMesh::cellZones(), polyMesh::defaultRegion, meshPtr, polyBoundaryMesh::names(), ZoneMesh< Zone, MeshType >::names(), autoPtr< T >::New(), and IOobject::NO_READ.
bool hasGeometry ()
Return true if file has geometry associated with it.
Definition at line 558 of file ccmReader.C.
bool hasSolution ()
Return true if file has solutions associated with it.
Definition at line 565 of file ccmReader.C.
bool remapMeshInfo (const objectRegistry & registry, const fileName & remappingDictName = fileName::null)
Remap cellTable and boundaryRegion according to dictionary.
Definition at line 593 of file ccmReader.C.
void writeMesh (const polyMesh & mesh, IOstream::streamFormat fmt = IOstream::BINARY) const
Write the polyMesh.
Definition at line 573 of file ccmReader.C.
void writeAux (const objectRegistry & registry) const
Write cellTable, boundaryRegion and interface information.
Definition at line 182 of file ccmReaderAux.C.
bool readGeometry (const scalar scaleFactor = 1.0)
Detect and read geometry if possible.
Definition at line 530 of file ccmReader.C.
void printInfo () const
Print general information about the mesh.
Definition at line 516 of file ccmReader.C.
void clearGeom ()
Clear out some information after obtaining a polyMesh.
Definition at line 2566 of file ccmReaderMesh.C.
const labelList& origCellId () const inline
Map to original cell Id.
Definition at line 660 of file ccmReader.H.
const labelList& origFaceId () const inline
Map to original face Id.
Definition at line 668 of file ccmReader.H.
const interfaceDefinitions& interfaceDefinitionsInfo () const inline
Return interface definitions map.
Definition at line 676 of file ccmReader.H.
const boundaryRegion& boundaryTableInfo () const inline
Return boundaryRegion table.
Definition at line 684 of file ccmReader.H.
const cellTable& cellTableInfo () const inline
Return cell table.
Definition at line 692 of file ccmReader.H.
Map<word> fluids () const inline
Return a list of names corresponding to fluids.
Definition at line 700 of file ccmReader.H.
Map<word> solids () const inline
Return a list of names corresponding to solids.
Definition at line 708 of file ccmReader.H.
const solutionTable& solutions () inline
Return table of available solutions.
Definition at line 716 of file ccmReader.H.
const fieldTable& fields () inline
Return table of available fields.
Definition at line 725 of file ccmReader.H.
const fieldTable& lagrangian () inline
Return table of available lagrangian fields.
Definition at line 734 of file ccmReader.H.
Foam::tmp< Foam::scalarField > readField (const word & solutionName, const word & fieldName, const bool wallData = false)
Read solution and field combination.
Definition at line 350 of file ccmReaderSolution.C.
References UList< T >::begin(), cellId, forAll, i, fieldEntry::maxCellId(), fieldEntry::maxFaceId(), n, tmp< T >::New(), tmp< T >::ref(), and List< T >::setSize().
The documentation for this class was generated from the following files:
src/conversion/ccm/reader/ccmReader.H
src/conversion/ccm/reader/ccmReader.C
src/conversion/ccm/reader/ccmReaderAux.C
src/conversion/ccm/reader/ccmReaderMesh.C
src/conversion/ccm/reader/ccmReaderSolution.C