OpenFOAM: halfCosineRamp Class Reference
halfCosineRamp Class Reference
Half-cosine ramp function starting from 0 and increasing to 1 from start over the duration and remaining at 1 thereafter.
Public Member Functions
TypeName ("halfCosineRamp")
halfCosineRamp (const word &entryName, const dictionary &dict)
Construct from entry name and dictionary.
virtual ~halfCosineRamp ()
Destructor.
virtual scalar value (const scalar t) const
Return value for time t.
Public Member Functions inherited from ramp
ramp (const word &entryName, const dictionary &dict)
Construct from entry name and dictionary.
virtual ~ramp ()
Destructor.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from Function1< scalar >
declareRunTimeSelectionTable (autoPtr, Function1, dictionary,(const word &entryName, const dictionary &dict),(entryName, dict))
Runtime type information.
Function1 (const word &entryName)
Construct from entry name.
Function1 (const Function1< scalar > &f1)
Copy constructor.
virtual tmp< Function1< scalar > > clone () const =0
Construct and return a clone.
virtual ~Function1 ()=default
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual tmp< Field< scalar > > value (const scalarField &x) const
Return value as a function of (scalar) independent variable.
virtual scalar integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< Field< scalar > > integrate (const scalarField &x1, const scalarField &x2) const
Integrate between two (scalar) values.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Public Types inherited from Function1< scalar >
typedef scalar returnType
Static Public Member Functions inherited from Function1< scalar >
static autoPtr< Function1
< scalar > > New (const word &entryName, const dictionary &dict, const word &redirectType=word::null)
Selector.
Protected Member Functions inherited from ramp
scalar linearRamp (const scalar t) const
Simple linear ramp function.
Protected Attributes inherited from ramp
scalar start_
Start-time of the ramp function.
scalar duration_
Duration of the ramp function.
Protected Attributes inherited from Function1< scalar >
const word name_
Name of entry.
Detailed Description
Half-cosine ramp function starting from 0 and increasing to 1 from start over the duration and remaining at 1 thereafter.
See Also
Foam::Function1Types::ramp
Source files
halfCosineRamp.H
halfCosineRamp.C
Definition at line 52 of file halfCosineRamp.H.
Constructor & Destructor Documentation
halfCosineRamp (const word & entryName, const dictionary & dict)
Construct from entry name and dictionary.
Definition at line 37 of file halfCosineRamp.C.
~halfCosineRamp () virtual
Destructor.
Definition at line 48 of file halfCosineRamp.C.
Member Function Documentation
TypeName ("halfCosineRamp")
Foam::scalar value (const scalar t) const inline virtual
Return value for time t.
Implements ramp.
Definition at line 27 of file halfCosineRampI.H.
References Foam::cos(), ramp::linearRamp(), and Foam::constant::mathematical::pi().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/functions/Function1/halfCosineRamp/halfCosineRamp.H
src/OpenFOAM/primitives/functions/Function1/halfCosineRamp/halfCosineRamp.C
src/OpenFOAM/primitives/functions/Function1/halfCosineRamp/halfCosineRampI.H