OpenFOAM: PtrList< T > Class Template Reference
PtrList< T > Class Template Reference
A list of pointers to objects of type <T>, with allocation/deallocation management of the pointers. The operator[] returns a reference to the object, not the pointer.
Inherits UPtrList< T >.
Inherited by DictionaryBase< PtrList< T >, T >, blockMesh, faBoundaryMesh, fvBoundaryMesh, IOPtrList< T >, pointBoundaryMesh, polyBoundaryMesh, and PtrDynList< T, SizeMin >.
Public Member Functions
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< T > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< T > &&list)
Move construct.
PtrList (UList< T * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
template<class CloneArg >
PtrList (const PtrList< T > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< T > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< T > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
template<class INew >
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
template<class... Args>
PtrList< T > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (T *ptr)
Append an element to the end of the list.
void append (autoPtr< T > &aptr)
Move append an element to the end of the list.
void append (autoPtr< T > &&aptr)
Move append an element to the end of the list.
void append (const tmp< T > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< T > &list)
Transfer into this list and annul the argument list.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< T > set (const label i, T *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< T > set (const label i, autoPtr< T > &aptr)
Set element to given autoPtr and return old element.
autoPtr< T > set (const label i, autoPtr< T > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< T > set (const label i, const tmp< T > &tptr)
Set element to given tmp and return old element.
autoPtr< T > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< T > &list)
Copy assignment.
void operator= (PtrList< T > &&list)
Move assignment.
template<class... Args>
Foam::PtrList< T > clone (Args &&...args) const
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Protected Member Functions
template<class INew >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Friends
Istream & operator>> (Istream &is, PtrList< T > &list)
Read from Istream, discarding contents of existing list.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Detailed Description
template<class T>
class Foam::PtrList< T >
A list of pointers to objects of type <T>, with allocation/deallocation management of the pointers. The operator[] returns a reference to the object, not the pointer.
See Also
Foam::UPtrList Foam::PtrDynList
Source files
PtrList.H
PtrListI.H
PtrList.C
PtrListIO.C
Definition at line 61 of file List.H.
Constructor & Destructor Documentation
constexpr PtrList () inline noexcept
Construct null.
Definition at line 37 of file PtrListI.H.
PtrList (const label len) inline explicit
Construct with specified size, each element initialized to nullptr.
Definition at line 44 of file PtrListI.H.
PtrList (const PtrList< T > & list) inline
Copy construct using 'clone()' method on each element.
Definition at line 51 of file PtrListI.H.
PtrList (PtrList< T > && list) inline
Move construct.
Definition at line 58 of file PtrListI.H.
PtrList (UList< T * > & list) inline explicit
Take ownerskip of pointers in the list, set old pointers to null.
Definition at line 65 of file PtrListI.H.
PtrList (const PtrList< T > & list, const CloneArg & cloneArgs) inline
Copy construct using 'clone()' method on each element.
Definition at line 81 of file PtrListI.H.
PtrList (PtrList< T > & list, bool reuse)
Construct as copy or re-use as specified.
Definition at line 29 of file PtrList.C.
References i, and UPtrList< T >::size().
PtrList (const SLPtrList< T > & list) explicit
Copy construct using 'clone()' on each element of SLPtrList<T>
Definition at line 47 of file PtrList.C.
PtrList (Istream & is, const INew & inew)
Construct from Istream using given Istream constructor class.
Definition at line 158 of file PtrListIO.C.
PtrList (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 165 of file PtrListIO.C.
~PtrList ()
Destructor.
Definition at line 65 of file PtrList.C.
Member Function Documentation
void readIstream (Istream & is, const INew & inew) protected
Read from Istream using Istream constructor class.
Definition at line 31 of file PtrListIO.C.
References LList< LListBase, T >::append(), clear(), IOstream::eof(), Foam::exit(), IOstream::fatalCheck(), Foam::FatalIOError, FatalIOErrorInFunction, FUNCTION_NAME, i, token::info(), token::isLabel(), token::isPunctuation(), token::labelToken(), p, token::pToken(), Istream::putBack(), Istream::readBeginList(), Istream::readEndList(), resize(), set(), and T.
void free () inline protected
Delete the allocated entries, but retain the list size.
Definition at line 28 of file PtrListI.H.
PtrList<T> clone (Args &&... args) const
Make a copy by cloning each of the list elements.
void clear () inline
Clear the PtrList. Delete allocated entries and set size to zero.
Definition at line 93 of file PtrListI.H.
Referenced by polyMesh::removeBoundary(), and decompositionMethod::setConstraints().
void resize (const label newLen)
Adjust size of PtrList.
New entries are initialized to nullptr, removed entries are deleted
Definition at line 96 of file PtrList.C.
Referenced by PDRblock::PDRblock().
void setSize (const label newLen) inline
Same as resize()
Definition at line 101 of file PtrListI.H.
References UPtrList< T >::clear().
Referenced by fvMeshTools::addPatch(), Foam::preservePatchTypes(), polyMesh::removeBoundary(), and searchableSurfaces::searchableSurfaces().
void append (T * ptr) inline
Append an element to the end of the list.
Definition at line 108 of file PtrListI.H.
References resize().
void append (autoPtr< T > & aptr) inline
Move append an element to the end of the list.
Definition at line 115 of file PtrListI.H.
References UPtrList< T >::append().
void append (autoPtr< T > && aptr) inline
Move append an element to the end of the list.
Definition at line 122 of file PtrListI.H.
References UPtrList< T >::append(), and autoPtr< T >::release().
void append (const tmp< T > & tptr) inline
Move or clone append a tmp to the end of the list.
Definition at line 129 of file PtrListI.H.
References UPtrList< T >::append().
void transfer (PtrList< T > & list) inline
Transfer into this list and annul the argument list.
Definition at line 183 of file PtrListI.H.
const T * set (const label i) const inline
Return const pointer to element (if set) or nullptr.
The return value can be tested as a bool.
Definition at line 136 of file PtrListI.H.
References UPtrList< T >::append(), and tmp< T >::ptr().
Referenced by isoSurface::adaptPatchFields(), fvMeshTools::addPatch(), forAll(), singleCellFvMesh::interpolate(), PDRblock::PDRblock(), pointBoundaryMesh::pointBoundaryMesh(), Foam::preservePatchTypes(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), snappySnapDriver::repatchToSurface(), and cellVolumeWeight::update().
Foam::autoPtr< T > set (const label i, T * ptr) inline
Set element to given pointer and return old element (can be null)
No-op if the new pointer value is identical to the current content.
Definition at line 143 of file PtrListI.H.
References UPtrList< T >::set().
Foam::autoPtr< T > set (const label i, autoPtr< T > & aptr) inline
Set element to given autoPtr and return old element.
Definition at line 150 of file PtrListI.H.
References UPtrList< T >::set().
Foam::autoPtr< T > set (const label i, autoPtr< T > && aptr) inline
Set element to given autoPtr and return old element.
Definition at line 157 of file PtrListI.H.
References autoPtr< T >::release(), and set().
Foam::autoPtr< T > set (const label i, const tmp< T > & tptr) inline
Set element to given tmp and return old element.
Definition at line 164 of file PtrListI.H.
References set().
Foam::autoPtr< T > release (const label i) inline
Release ownership of the pointer at the given position.
Out of bounds addressing is a no-op and returns nullptr.
Definition at line 171 of file PtrListI.H.
References tmp< T >::ptr(), and set().
void operator= (const PtrList< T > & list)
Copy assignment.
For existing list entries, values are copied from the list. For new list entries, pointers are cloned from the list.
Definition at line 126 of file PtrList.C.
Referenced by IOPtrList< T >::IOPtrList().
void operator= (PtrList< T > && list) inline
Move assignment.
Definition at line 193 of file PtrListI.H.
Foam::PtrList<T> clone (Args &&... args) const
Definition at line 75 of file PtrList.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, PtrList< T > & list) friend
Read from Istream, discarding contents of existing list.
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/Lists/List/List.H
src/OpenFOAM/containers/PtrLists/PtrList/PtrList.H
src/OpenFOAM/containers/PtrLists/PtrList/PtrList.C
src/OpenFOAM/containers/PtrLists/PtrList/PtrListI.H
src/OpenFOAM/containers/PtrLists/PtrList/PtrListIO.C