OpenFOAM: pointFieldReconstructor Class Reference
pointFieldReconstructor Class Reference
Point field reconstructor.
Classes
class pointPatchFieldReconstructor
Public Member Functions
pointFieldReconstructor (const pointMesh &mesh, const PtrList< pointMesh > &procMeshes, const PtrList< labelIOList > &pointProcAddressing, const PtrList< labelIOList > &boundaryProcAddressing)
Construct from components.
label nReconstructed () const
Return number of fields reconstructed.
template<class Type >
tmp< GeometricField< Type,
pointPatchField, pointMesh > > reconstructField (const IOobject &fieldIoObject)
Reconstruct field.
template<class Type >
label reconstructFields (const IOobjectList &objects, const UList< word > &fieldNames)
Reconstruct and write specified fields.
template<class Type >
label reconstructFields (const IOobjectList &objects, const wordRes &selectedFields=wordRes())
Reconstruct and write all or selected fields.
template<class Type >
label reconstructFields (const IOobjectList &objects, const wordHashSet &selectedFields)
Reconstruct and write all or selected fields.
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::pointPatchField,
Foam::pointMesh > > reconstructField (const IOobject &fieldIoObject)
template<class Type >
Foam::label reconstructFields (const IOobjectList &objects, const UList< word > &fieldNames)
template<class Type >
Foam::label reconstructFields (const IOobjectList &objects, const wordRes &selectedFields)
template<class Type >
Foam::label reconstructFields (const IOobjectList &objects, const wordHashSet &selectedFields)
Detailed Description
Point field reconstructor.
Source files
pointFieldReconstructor.H
pointFieldReconstructor.C
pointFieldReconstructorFields.C
Definition at line 51 of file pointFieldReconstructor.H.
Constructor & Destructor Documentation
pointFieldReconstructor (const pointMesh & mesh, const PtrList< pointMesh > & procMeshes, const PtrList< labelIOList > & pointProcAddressing, const PtrList< labelIOList > & boundaryProcAddressing)
Construct from components.
Definition at line 26 of file pointFieldReconstructor.C.
References Foam::abort(), pointMesh::boundary(), Foam::FatalError, FatalErrorInFunction, forAll, Foam::min(), List< T >::setSize(), pointMesh::size(), UList< T >::size(), and UPtrList< T >::size().
Member Function Documentation
label nReconstructed () const inline
Return number of fields reconstructed.
Definition at line 163 of file pointFieldReconstructor.H.
tmp<GeometricField<Type, pointPatchField, pointMesh> > reconstructField (const IOobject & fieldIoObject)
Reconstruct field.
label reconstructFields (const IOobjectList & objects, const UList< word > & fieldNames)
Reconstruct and write specified fields.
label reconstructFields (const IOobjectList & objects, const wordRes & selectedFields = wordRes())
Reconstruct and write all or selected fields.
An empty wordRes corresponds to select ALL.
label reconstructFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Reconstruct and write all or selected fields.
An empty wordHashSet corresponds to select ALL.
Note
this may be removed in the future (2018-11)
Foam::tmp<Foam::GeometricField<Type, Foam::pointPatchField, Foam::pointMesh> > reconstructField (const IOobject & fieldIoObject)
Definition at line 28 of file pointFieldReconstructorFields.C.
References pointMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), forAll, IOobject::MUST_READ, IOobject::name(), Foam::New(), IOobject::NO_READ, IOobject::NO_WRITE, DimensionedField< Type, GeoMesh >::null(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), pointMesh::size(), UPtrList< T >::size(), IOobject::time(), and Time::timeName().
Foam::label reconstructFields (const IOobjectList & objects, const UList< word > & fieldNames)
Definition at line 136 of file pointFieldReconstructorFields.C.
Foam::label reconstructFields (const IOobjectList & objects, const wordRes & selectedFields)
Definition at line 168 of file pointFieldReconstructorFields.C.
Foam::label reconstructFields (const IOobjectList & objects, const wordHashSet & selectedFields)
Definition at line 188 of file pointFieldReconstructorFields.C.
The documentation for this class was generated from the following files:
src/parallel/reconstruct/reconstruct/pointFieldReconstructor.H
src/parallel/reconstruct/reconstruct/pointFieldReconstructor.C
src/parallel/reconstruct/reconstruct/pointFieldReconstructorFields.C