OpenFOAM: patchExprFieldBase Class Reference
patchExprFieldBase Class Reference
Base class for managing patches with expressions. The expected input supports values, gradients and mixed conditions.
Public Member Functions
patchExprFieldBase ()
Null constructor.
patchExprFieldBase (bool allowGradient)
Construct with specified gradient handling.
patchExprFieldBase (const dictionary &dict, bool allowGradient=false, bool isPointVal=false)
Construct from dictionary.
patchExprFieldBase (const patchExprFieldBase &rhs)
Copy constructor.
void write (Ostream &os) const
Write.
Static Public Member Functions
static const fvPatch & getFvPatch (const facePointPatch &fp)
Find (guess) fvPatch from a pointPatch.
Protected Attributes
bool debug_
bool allowGradient_
bool evalOnConstruct_
Slightly dodgy concept here.
expressions::exprString valueExpr_
expressions::exprString gradExpr_
expressions::exprString fracExpr_
Detailed Description
Base class for managing patches with expressions. The expected input supports values, gradients and mixed conditions.
Usage
Property Description Required Default
valueExpr expression for fixed value no 0
gradientExpr expression for patch normal gradient no 0
fractionExpr expression for value fraction weight no 1
Source files
patchExprFieldBase.H
patchExprFieldBase.C
Definition at line 84 of file patchExprFieldBase.H.
Constructor & Destructor Documentation
patchExprFieldBase ()
Null constructor.
Definition at line 51 of file patchExprFieldBase.C.
patchExprFieldBase (bool allowGradient) explicit
Construct with specified gradient handling.
Definition at line 58 of file patchExprFieldBase.C.
patchExprFieldBase (const dictionary & dict, bool allowGradient = false, bool isPointVal = false) explicit
Construct from dictionary.
Definition at line 72 of file patchExprFieldBase.C.
patchExprFieldBase (const patchExprFieldBase & rhs)
Copy constructor.
Definition at line 143 of file patchExprFieldBase.C.
Member Function Documentation
const Foam::fvPatch & getFvPatch (const facePointPatch & fp) static
Find (guess) fvPatch from a pointPatch.
Definition at line 31 of file patchExprFieldBase.C.
References pointPatch::boundaryMesh(), Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, pointBoundaryMesh::mesh(), MeshObject< Mesh, MeshObjectType, Type >::mesh(), and Foam::nl.
void write (Ostream & os) const
Write.
Definition at line 158 of file patchExprFieldBase.C.
Member Data Documentation
bool debug_ protected
Definition at line 90 of file patchExprFieldBase.H.
bool allowGradient_ protected
Definition at line 91 of file patchExprFieldBase.H.
bool evalOnConstruct_ protected
Slightly dodgy concept here.
Definition at line 96 of file patchExprFieldBase.H.
expressions::exprString valueExpr_ protected
Definition at line 99 of file patchExprFieldBase.H.
expressions::exprString gradExpr_ protected
Definition at line 100 of file patchExprFieldBase.H.
expressions::exprString fracExpr_ protected
Definition at line 101 of file patchExprFieldBase.H.
The documentation for this class was generated from the following files:
src/finiteVolume/expressions/fields/base/patchExprFieldBase.H
src/finiteVolume/expressions/fields/base/patchExprFieldBase.C