OpenFOAM: fvMeshSubsetProxy Class Reference
fvMeshSubsetProxy Class Reference
Simple proxy for holding a mesh, or mesh-subset. The subMeshes are currently limited to cellSet or cellZone definitions.
Public Types
enum subsetType { NONE, SET, ZONE, ZONES }
Internal bookkeeping for subset type.
Public Member Functions
fvMeshSubsetProxy (fvMesh &baseMesh)
Construct a pass-through proxy. No correct() invoked or required.
fvMeshSubsetProxy (fvMesh &baseMesh, const subsetType type, const word &selectionName, label exposedPatchId=-1)
Construct from components.
fvMeshSubsetProxy (fvMesh &baseMesh, const wordRes &zoneNames, label exposedPatchId=-1)
Construct from components. The subsetType is ZONES.
fvMeshSubsetProxy (fvMesh &baseMesh, wordRes &&zoneNames, label exposedPatchId=-1)
Construct from components. The subsetType is ZONES.
const fvMesh & baseMesh () const
The entire base mesh.
const fvMeshSubset & subsetter () const
The mesh subsetter.
bool useSubMesh () const
Check if a sub-mesh is being used.
const fvMesh & mesh () const
Access either base-mesh or sub-mesh.
const word & name () const
The associated (set or zone) name if any.
const bitSet & selectedCells () const
The current cell selection, when subsetting is active.
bool correct (bool verbose=false)
Update of mesh subset.
polyMesh::readUpdateState readUpdate ()
Read mesh. Correct on topo-change.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > interpolateInternal (const DimensionedField< Type, volMesh > &df) const
Convert an internal field to a volume field (with zeroGradient)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > interpolateInternal (const tmp< DimensionedField< Type, volMesh >> &tdf) const
Convert an internal field to a volume field (with zeroGradient)
template<class GeoField >
tmp< GeoField > interpolate (const GeoField &fld) const
Wrapper for field or the subsetted field.
template<class GeoField >
tmp< GeoField > interpolate (const tmp< GeoField > &fld) const
Wrapper for field or the subsetted field.
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const DimensionedField< Type, volMesh > &df)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const tmp< DimensionedField< Type, volMesh >> &tdf)
template<class GeoField >
Foam::tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const GeoField &fld)
template<class GeoField >
Foam::tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const tmp< GeoField > &tfield)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolateInternal (const DimensionedField< Type, volMesh > &df) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > interpolateInternal (const tmp< DimensionedField< Type, volMesh >> &tdf) const
template<class GeoField >
Foam::tmp< GeoField > interpolate (const GeoField &fld) const
template<class GeoField >
Foam::tmp< GeoField > interpolate (const tmp< GeoField > &tfield) const
Static Public Member Functions
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > zeroGradientField (const DimensionedField< Type, volMesh > &df)
Construct volField (with zeroGradient) from an internal field.
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const DimensionedField< Type, volMesh > &df)
Convert an internal field to a volume field (with zeroGradient)
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > interpolateInternal (const fvMeshSubset &subsetter, const tmp< DimensionedField< Type, volMesh >> &tdf)
Convert an internal field to a volume field (with zeroGradient)
template<class GeoField >
static tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const GeoField &fld)
Wrapper for field or the subsetted field.
template<class GeoField >
static tmp< GeoField > interpolate (const fvMeshSubset &subsetter, const tmp< GeoField > &fld)
Wrapper for field or the subsetted field.
Detailed Description
Simple proxy for holding a mesh, or mesh-subset. The subMeshes are currently limited to cellSet or cellZone definitions.
Source files
fvMeshSubsetProxy.H
fvMeshSubsetProxy.C
fvMeshSubsetProxyTemplates.C
Definition at line 54 of file fvMeshSubsetProxy.H.
Member Enumeration Documentation
enum subsetType
Internal bookkeeping for subset type.
Enumerator
NONE
SET
ZONE
ZONES
Definition at line 61 of file fvMeshSubsetProxy.H.
Constructor & Destructor Documentation
fvMeshSubsetProxy (fvMesh & baseMesh) explicit
Construct a pass-through proxy. No correct() invoked or required.
Definition at line 28 of file fvMeshSubsetProxy.C.
References fvMeshSubsetProxy::useSubMesh().
fvMeshSubsetProxy (fvMesh & baseMesh, const subsetType type, const word & selectionName, label exposedPatchId = -1)
Construct from components.
Definition at line 46 of file fvMeshSubsetProxy.C.
References fvMeshSubsetProxy::correct().
fvMeshSubsetProxy (fvMesh & baseMesh, const wordRes & zoneNames, label exposedPatchId = -1)
Construct from components. The subsetType is ZONES.
Definition at line 80 of file fvMeshSubsetProxy.C.
References fvMeshSubsetProxy::correct().
fvMeshSubsetProxy (fvMesh & baseMesh, wordRes && zoneNames, label exposedPatchId = -1)
Construct from components. The subsetType is ZONES.
Definition at line 102 of file fvMeshSubsetProxy.C.
References fvMeshSubsetProxy::correct().
Member Function Documentation
const fvMesh& baseMesh () const inline
The entire base mesh.
Definition at line 171 of file fvMeshSubsetProxy.H.
Referenced by Foam::getField(), and Foam::getZeroGradField().
const fvMeshSubset& subsetter () const inline
The mesh subsetter.
Definition at line 179 of file fvMeshSubsetProxy.H.
bool useSubMesh () const inline
Check if a sub-mesh is being used.
Definition at line 187 of file fvMeshSubsetProxy.H.
Referenced by fvMeshSubsetProxy::fvMeshSubsetProxy(), and Foam::writePointField().
const fvMesh& mesh () const inline
Access either base-mesh or sub-mesh.
Definition at line 195 of file fvMeshSubsetProxy.H.
const word& name () const inline
The associated (set or zone) name if any.
Definition at line 208 of file fvMeshSubsetProxy.H.
const bitSet& selectedCells () const inline
The current cell selection, when subsetting is active.
Definition at line 216 of file fvMeshSubsetProxy.H.
bool correct (bool verbose = false)
Update of mesh subset.
Return true if the subset changed from previous call.
Definition at line 125 of file fvMeshSubsetProxy.C.
Referenced by fvMeshSubsetProxy::fvMeshSubsetProxy().
Foam::polyMesh::readUpdateState readUpdate ()
Read mesh. Correct on topo-change.
Definition at line 189 of file fvMeshSubsetProxy.C.
static tmp<GeometricField<Type, fvPatchField, volMesh> > zeroGradientField (const DimensionedField< Type, volMesh > & df) static
Construct volField (with zeroGradient) from an internal field.
Referenced by Foam::getZeroGradField().
static tmp<GeometricField<Type, fvPatchField, volMesh> > interpolateInternal (const fvMeshSubset & subsetter, const DimensionedField< Type, volMesh > & df) static
Convert an internal field to a volume field (with zeroGradient)
Referenced by Foam::getZeroGradField().
static tmp<GeometricField<Type, fvPatchField, volMesh> > interpolateInternal (const fvMeshSubset & subsetter, const tmp< DimensionedField< Type, volMesh >> & tdf) static
Convert an internal field to a volume field (with zeroGradient)
Currently no proper memory reuse
static tmp<GeoField> interpolate (const fvMeshSubset & subsetter, const GeoField & fld) static
Wrapper for field or the subsetted field.
Pass through or forward to fvMeshSubset::interpolate()
Referenced by Foam::getField(), Foam::writePointField(), vtkWrite::writeVolFields(), and ensightWrite::writeVolFields().
static tmp<GeoField> interpolate (const fvMeshSubset & subsetter, const tmp< GeoField > & fld) static
Wrapper for field or the subsetted field.
Pass through or forward to fvMeshSubset::interpolate()
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolateInternal (const DimensionedField< Type, volMesh > & df) const
Convert an internal field to a volume field (with zeroGradient)
tmp<GeometricField<Type, fvPatchField, volMesh> > interpolateInternal (const tmp< DimensionedField< Type, volMesh >> & tdf) const
Convert an internal field to a volume field (with zeroGradient)
Currently no proper memory reuse
tmp<GeoField> interpolate (const GeoField & fld) const
Wrapper for field or the subsetted field.
Pass through or forward to fvMeshSubset::interpolate()
tmp<GeoField> interpolate (const tmp< GeoField > & fld) const
Wrapper for field or the subsetted field.
Pass through or forward to fvMeshSubset::interpolate()
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolateInternal (const fvMeshSubset & subsetter, const DimensionedField< Type, volMesh > & df)
Definition at line 60 of file fvMeshSubsetProxyTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolateInternal (const fvMeshSubset & subsetter, const tmp< DimensionedField< Type, volMesh >> & tdf)
Definition at line 79 of file fvMeshSubsetProxyTemplates.C.
Foam::tmp<GeoField> interpolate (const fvMeshSubset & subsetter, const GeoField & fld)
Definition at line 114 of file fvMeshSubsetProxyTemplates.C.
Foam::tmp<GeoField> interpolate (const fvMeshSubset & subsetter, const tmp< GeoField > & tfield)
Definition at line 135 of file fvMeshSubsetProxyTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolateInternal (const DimensionedField< Type, volMesh > & df) const
Definition at line 158 of file fvMeshSubsetProxyTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > interpolateInternal (const tmp< DimensionedField< Type, volMesh >> & tdf) const
Definition at line 169 of file fvMeshSubsetProxyTemplates.C.
Foam::tmp<GeoField> interpolate (const GeoField & fld) const
Definition at line 179 of file fvMeshSubsetProxyTemplates.C.
Foam::tmp<GeoField> interpolate (const tmp< GeoField > & tfield) const
Definition at line 187 of file fvMeshSubsetProxyTemplates.C.
References Foam::interpolate().
The documentation for this class was generated from the following files:
src/dynamicMesh/fvMeshSubsetProxy/fvMeshSubsetProxy.H
src/dynamicMesh/fvMeshSubsetProxy/fvMeshSubsetProxy.C
src/dynamicMesh/fvMeshSubsetProxy/fvMeshSubsetProxyTemplates.C