OpenFOAM: quadraticEqn Class Reference
quadraticEqn Class Reference
Quadratic equation of the form a*x^2 + b*x + c = 0.
Public Types
enum components { A, B, C }
Component labeling enumeration.
Public Types inherited from VectorSpace< quadraticEqn, scalar, 3 >
typedef VectorSpace
< quadraticEqn, scalar, Ncmpts > vsType
VectorSpace type.
typedef scalar cmptType
Component type.
typedef scalar magType
Magnitude type.
typedef scalar * iterator
Random access iterator for traversing VectorSpace.
typedef const scalar * const_iterator
Random access iterator for traversing VectorSpace.
Public Member Functions
quadraticEqn ()
Construct null.
quadraticEqn (const Foam::zero)
Construct initialized to zero.
quadraticEqn (const scalar a, const scalar b, const scalar c)
Construct from components.
scalar a () const
scalar b () const
scalar c () const
scalar & a ()
scalar & b ()
scalar & c ()
scalar value (const scalar x) const
Evaluate at x.
scalar derivative (const scalar x) const
Evaluate the derivative at x.
scalar error (const scalar x) const
Estimate the error of evaluation at x.
Roots< 2 > roots () const
Get the roots.
Public Member Functions inherited from VectorSpace< quadraticEqn, scalar, 3 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< quadraticEqn, scalar, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const scalar & component (const direction) const
scalar & component (const direction)
void component (scalar &, const direction) const
void replace (const direction, const scalar &)
const scalar * cdata () const noexcept
Return const pointer to the first data element.
scalar * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const scalar & operator[] (const direction) const
scalar & operator[] (const direction)
void operator= (const VectorSpace< quadraticEqn, scalar, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< quadraticEqn, scalar, Ncmpts > &)
void operator-= (const VectorSpace< quadraticEqn, scalar, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Additional Inherited Members
Static Public Member Functions inherited from VectorSpace< quadraticEqn, scalar, 3 >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static quadraticEqn uniform (const scalar &s)
Return a VectorSpace with all elements = s.
Public Attributes inherited from VectorSpace< quadraticEqn, scalar, 3 >
scalar v_ [Ncmpts]
The components of this vector space.
Static Public Attributes inherited from VectorSpace< quadraticEqn, scalar, 3 >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const quadraticEqn zero
static const quadraticEqn one
static const quadraticEqn max
static const quadraticEqn min
static const quadraticEqn rootMax
static const quadraticEqn rootMin
Detailed Description
Quadratic equation of the form a*x^2 + b*x + c = 0.
Source files
quadraticEqn.H
quadraticEqnI.H
quadraticEqn.C
Definition at line 47 of file quadraticEqn.H.
Member Enumeration Documentation
enum components
Component labeling enumeration.
Enumerator
A
B
C
Definition at line 56 of file quadraticEqn.H.
Constructor & Destructor Documentation
quadraticEqn () inline
Construct null.
Definition at line 23 of file quadraticEqnI.H.
quadraticEqn (const Foam::zero) inline
Construct initialized to zero.
Definition at line 27 of file quadraticEqnI.H.
quadraticEqn (const scalar a, const scalar b, const scalar c) inline
Construct from components.
Definition at line 34 of file quadraticEqnI.H.
Member Function Documentation
Foam::scalar a () const inline
Definition at line 48 of file quadraticEqnI.H.
Referenced by quadraticEqn::roots().
Foam::scalar b () const inline
Definition at line 54 of file quadraticEqnI.H.
References A.
Referenced by quadraticEqn::roots().
Foam::scalar c () const inline
Definition at line 60 of file quadraticEqnI.H.
References B.
Referenced by quadraticEqn::roots().
Foam::scalar & a () inline
Definition at line 66 of file quadraticEqnI.H.
References C.
Foam::scalar & b () inline
Definition at line 72 of file quadraticEqnI.H.
References A.
Foam::scalar & c () inline
Definition at line 78 of file quadraticEqnI.H.
References B.
Foam::scalar value (const scalar x) const inline
Evaluate at x.
Definition at line 84 of file quadraticEqnI.H.
References C.
Foam::scalar derivative (const scalar x) const inline
Evaluate the derivative at x.
Definition at line 90 of file quadraticEqnI.H.
References Foam::constant::physicoChemical::b, and c().
Foam::scalar error (const scalar x) const inline
Estimate the error of evaluation at x.
Definition at line 96 of file quadraticEqnI.H.
References Foam::constant::physicoChemical::b.
Foam::Roots< 2 > roots () const
Get the roots.
Definition at line 26 of file quadraticEqn.C.
References quadraticEqn::a(), quadraticEqn::b(), quadraticEqn::c(), Foam::roots::complex, Foam::roots::nan, linearEqn::roots(), Foam::sign(), Foam::sqrt(), and x.
Referenced by cubicEqn::roots().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/polynomialEqns/quadraticEqn/quadraticEqn.H
src/OpenFOAM/primitives/polynomialEqns/quadraticEqn/quadraticEqn.C
src/OpenFOAM/primitives/polynomialEqns/quadraticEqn/quadraticEqnI.H