OpenFOAM: memorybuf::in Class Reference
memorybuf::in Class Reference
An input streambuf for memory access.
Public Member Functions
in (char *s, std::streamsize n)
Construct for character array (can be nullptr) and number of bytes.
void resetg (char *s, std::streamsize n)
Reset for character array (can be nullptr) and number of bytes.
std::streamsize capacity () const
The buffer capacity.
const UList< char > list () const
Const UList access to the input characters (shallow copy).
UList< char > list ()
Non-const UList access to the input characters (shallow copy).
void printBufInfo (Ostream &os) const
Some information about the input buffer position/capacity.
Protected Member Functions
in ()=default
Default construct null.
virtual std::streamsize xsgetn (char *s, std::streamsize n)
Get sequence of characters.
Protected Member Functions inherited from memorybuf
virtual std::streampos seekoff (std::streamoff off, std::ios_base::seekdir way, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
Set position pointer to relative position.
virtual std::streampos seekpos (std::streampos pos, std::ios_base::openmode which=std::ios_base::in|std::ios_base::out)
Set position pointer to absolute position.
std::streamsize tellg () const
std::streamsize tellp () const
Detailed Description
An input streambuf for memory access.
Definition at line 165 of file memoryStreamBuffer.H.
Constructor & Destructor Documentation
in () protected default
Default construct null.
in (char * s, std::streamsize n) inline
Construct for character array (can be nullptr) and number of bytes.
Definition at line 198 of file memoryStreamBuffer.H.
Member Function Documentation
virtual std::streamsize xsgetn (char * s, std::streamsize n) inline protected virtual
Get sequence of characters.
Definition at line 179 of file memoryStreamBuffer.H.
void resetg (char * s, std::streamsize n) inline
Reset for character array (can be nullptr) and number of bytes.
Sets get pointer to the begin.
Definition at line 208 of file memoryStreamBuffer.H.
Referenced by uiliststream::reset(), and UIListStreamAllocator::UIListStreamAllocator().
std::streamsize capacity () const inline
The buffer capacity.
Definition at line 228 of file memoryStreamBuffer.H.
const UList<char> list () const inline
Const UList access to the input characters (shallow copy).
Definition at line 236 of file memoryStreamBuffer.H.
UList<char> list () inline
Non-const UList access to the input characters (shallow copy).
Definition at line 244 of file memoryStreamBuffer.H.
References n, memorybuf::out::out(), s, and memorybuf::out::xsputn().
void printBufInfo (Ostream & os) const inline
Some information about the input buffer position/capacity.
Definition at line 252 of file memoryStreamBuffer.H.
References Foam::BitOps::count().
The documentation for this class was generated from the following file:
src/OpenFOAM/db/IOstreams/memory/memoryStreamBuffer.H