OpenFOAM: searchableSurfaces Class Reference
searchableSurfaces Class Reference
Container for searchableSurfaces. The collection is specified as a dictionary. For example,.
Public Member Functions
ClassName ("searchableSurfaces")
searchableSurfaces (const label)
Construct with length specified. Fill later.
searchableSurfaces (const IOobject &, const dictionary &, const bool singleRegionName)
Construct from dictionary.
const wordList & names () const
Surface names, not region names.
wordList & names ()
Surface names, not region names.
const List< wordList > & regionNames () const
Region names per surface.
List< wordList > & regionNames ()
Region names per surface.
label findSurfaceID (const word &name) const
Find index of surface. Return -1 if not found.
label findSurfaceRegionID (const word &surfaceName, const word &regionName) const
void findAnyIntersection (const pointField &start, const pointField &end, labelList &surfaces, List< pointIndexHit > &) const
Find any intersection. Return hit point information and.
void findAllIntersections (const pointField &start, const pointField &end, labelListList &surfaces, List< List< pointIndexHit >> &) const
Find all intersections in order from start to end. Returns for.
void findNearestIntersection (const pointField &start, const pointField &end, labelList &surface1, List< pointIndexHit > &hit1, labelList &surface2, List< pointIndexHit > &hit2) const
void findNearest (const pointField &, const scalarField &nearestDistSqr, labelList &surfaces, List< pointIndexHit > &) const
Find nearest. Return -1 (and a miss()) or surface and nearest.
void findNearest (const labelListList &regionIndices, const pointField &samples, const scalarField &nearestDistSqr, labelList &nearestSurfaces, List< pointIndexHit > &nearestInfo) const
boundBox bounds () const
Calculate bounding box.
bool checkClosed (const bool report) const
Are all surfaces closed and manifold.
bool checkNormalOrientation (const bool report) const
Are all (triangulated) surfaces consistent normal orientation.
bool checkSizes (const scalar maxRatio, const bool report) const
Are all bounding boxes of similar size.
bool checkIntersection (const scalar tol, const autoPtr< writer< scalar >> &, const bool report) const
Do surfaces self-intersect or intersect others.
bool checkQuality (const scalar minQuality, const bool report) const
Check triangle quality.
label checkTopology (const bool report) const
All topological checks. Return number of failed checks.
label checkGeometry (const scalar maxRatio, const scalar tolerance, const autoPtr< writer< scalar >> &setWriter, const scalar minQuality, const bool report) const
All geometric checks. Return number of failed checks.
void writeStats (const List< wordList > &, Ostream &) const
Write some stats.
const searchableSurface & operator[] (const word &) const
Return const reference to searchableSurface by name.
searchableSurface & operator[] (const word &)
Return reference to searchableSurface by name.
Public Member Functions inherited from PtrList< searchableSurface >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< searchableSurface > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< searchableSurface > &&list)
Move construct.
PtrList (UList< searchableSurface * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
PtrList (const PtrList< searchableSurface > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< searchableSurface > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< searchableSurface > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
PtrList< searchableSurface > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (searchableSurface *ptr)
Append an element to the end of the list.
void append (autoPtr< searchableSurface > &aptr)
Move append an element to the end of the list.
void append (autoPtr< searchableSurface > &&aptr)
Move append an element to the end of the list.
void append (const tmp< searchableSurface > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< searchableSurface > &list)
Transfer into this list and annul the argument list.
const searchableSurface * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< searchableSurface > set (const label i, searchableSurface *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< searchableSurface > set (const label i, autoPtr< searchableSurface > &aptr)
Set element to given autoPtr and return old element.
autoPtr< searchableSurface > set (const label i, autoPtr< searchableSurface > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< searchableSurface > set (const label i, const tmp< searchableSurface > &tptr)
Set element to given tmp and return old element.
autoPtr< searchableSurface > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< searchableSurface > &list)
Copy assignment.
void operator= (PtrList< searchableSurface > &&list)
Move assignment.
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Additional Inherited Members
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Protected Member Functions inherited from PtrList< searchableSurface >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Detailed Description
Container for searchableSurfaces. The collection is specified as a dictionary. For example,.
geometry
{
    surface1
    {
        type  ...;
    }
    surface2
    {
        type  ...;
    }
}
The Sub-dictionary parameters
Property Description Required Default
name alternative name for surface no dict name
regions Region names sub-dictionary no
Source files
searchableSurfaces.H
searchableSurfaces.C
Definition at line 88 of file searchableSurfaces.H.
Constructor & Destructor Documentation
searchableSurfaces (const label size) explicit
Construct with length specified. Fill later.
Definition at line 91 of file searchableSurfaces.C.
searchableSurfaces (const IOobject & io, const dictionary & topDict, const bool singleRegionName)
Construct from dictionary.
Parameters
singleRegionName controls if names are constructed as surfaceName "_" regionName (singleRegionName false) or for single region surfaces as surfaceName only (singleRegionName true)
Definition at line 190 of file searchableSurfaces.C.
References IOobject::clone(), dict, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, UList< T >::find(), forAll, dictionary::found(), dictionary::get(), dictionary::lookupOrDefault(), IOobject::name(), searchableSurface::New(), Foam::nl, searchableSurfaces::operator[](), searchableSurface::regions(), PtrList< searchableSurface >::set(), PtrList< T >::setSize(), List< T >::setSize(), UList< T >::size(), and dictionary::subDict().
Member Function Documentation
ClassName ("searchableSurfaces")
const wordList& names () const inline
Surface names, not region names.
Definition at line 171 of file searchableSurfaces.H.
wordList& names () inline
Surface names, not region names.
Definition at line 179 of file searchableSurfaces.H.
const List<wordList>& regionNames () const inline
Region names per surface.
Definition at line 187 of file searchableSurfaces.H.
List<wordList>& regionNames () inline
Region names per surface.
Definition at line 195 of file searchableSurfaces.H.
Foam::label findSurfaceID (const word & name) const
Find index of surface. Return -1 if not found.
Definition at line 302 of file searchableSurfaces.C.
Foam::label findSurfaceRegionID (const word & surfaceName, const word & regionName) const
Definition at line 311 of file searchableSurfaces.C.
void findAnyIntersection (const pointField & start, const pointField & end, labelList & surfaces, List< pointIndexHit > & hitInfo) const
Find any intersection. Return hit point information and.
surface number. If multiple surfaces hit the first surface is returned, not necessarily the nearest (to start).
Definition at line 324 of file searchableSurfaces.C.
void findAllIntersections (const pointField & start, const pointField & end, labelListList & surfaces, List< List< pointIndexHit >> & hitInfo) const
Find all intersections in order from start to end. Returns for.
every hit the surface and the hit info.
Definition at line 344 of file searchableSurfaces.C.
void findNearestIntersection (const pointField & start, const pointField & end, labelList & surface1, List< pointIndexHit > & hit1, labelList & surface2, List< pointIndexHit > & hit2) const
Definition at line 365 of file searchableSurfaces.C.
void findNearest (const pointField & samples, const scalarField & nearestDistSqr, labelList & surfaces, List< pointIndexHit > & nearestInfo) const
Find nearest. Return -1 (and a miss()) or surface and nearest.
point.
Definition at line 389 of file searchableSurfaces.C.
void findNearest (const labelListList & regionIndices, const pointField & samples, const scalarField & nearestDistSqr, labelList & nearestSurfaces, List< pointIndexHit > & nearestInfo) const
Definition at line 409 of file searchableSurfaces.C.
Foam::boundBox bounds () const
Calculate bounding box.
Definition at line 432 of file searchableSurfaces.C.
bool checkClosed (const bool report) const
Are all surfaces closed and manifold.
Definition at line 442 of file searchableSurfaces.C.
bool checkNormalOrientation (const bool report) const
Are all (triangulated) surfaces consistent normal orientation.
Definition at line 509 of file searchableSurfaces.C.
bool checkSizes (const scalar maxRatio, const bool report) const
Are all bounding boxes of similar size.
Definition at line 556 of file searchableSurfaces.C.
bool checkIntersection (const scalar tol, const autoPtr< writer< scalar >> & setWriter, const bool report) const
Do surfaces self-intersect or intersect others.
Definition at line 604 of file searchableSurfaces.C.
bool checkQuality (const scalar minQuality, const bool report) const
Check triangle quality.
Definition at line 748 of file searchableSurfaces.C.
Foam::label checkTopology (const bool report) const
All topological checks. Return number of failed checks.
Definition at line 813 of file searchableSurfaces.C.
Foam::label checkGeometry (const scalar maxRatio, const scalar tolerance, const autoPtr< writer< scalar >> & setWriter, const scalar minQuality, const bool report) const
All geometric checks. Return number of failed checks.
Definition at line 833 of file searchableSurfaces.C.
void writeStats (const List< wordList > & patchTypes, Ostream & os) const
Write some stats.
Definition at line 863 of file searchableSurfaces.C.
const Foam::searchableSurface & operator[] (const word & surfName) const
Return const reference to searchableSurface by name.
Definition at line 908 of file searchableSurfaces.C.
Referenced by searchableSurfaces::searchableSurfaces().
Foam::searchableSurface & operator[] (const word & surfName)
Return reference to searchableSurface by name.
Definition at line 927 of file searchableSurfaces.C.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchableSurfaces/searchableSurfaces.H
src/meshTools/searchableSurfaces/searchableSurfaces/searchableSurfaces.C