OpenFOAM: regionModelFunctionObject Class Reference
regionModelFunctionObject Class Reference
Region model function object base class.
Public Member Functions
TypeName ("regionModelFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, regionModelFunctionObject, dictionary,(const dictionary &dict, regionModel &region),(dict, region))
Declare runtime constructor selection table.
regionModelFunctionObject (regionModel &region)
Construct null from region.
regionModelFunctionObject (const dictionary &dict, regionModel &region, const word &modelType)
Construct from dictionary.
regionModelFunctionObject (const regionModelFunctionObject &ppm)
Construct copy.
virtual autoPtr
< regionModelFunctionObject > clone () const
Construct and return a clone.
virtual ~regionModelFunctionObject ()
Destructor.
virtual void preEvolveRegion ()
Pre-evolve region hook.
virtual void postEvolveRegion ()
Post-evolve region hook.
virtual void write () const
write
Static Public Member Functions
static autoPtr
< regionModelFunctionObject > New (const dictionary &dict, regionModel &region, const word &modelType)
Selector.
Protected Attributes
dictionary dict_
Dictionary.
regionModel & regionModel_
Reference to the region model.
word modelType_
Model type name.
Detailed Description
Region model function object base class.
Source files
regionModelFunctionObject.H
regionModelFunctionObject.C
regionModelFunctionObjectNew.C
Definition at line 54 of file regionModelFunctionObject.H.
Constructor & Destructor Documentation
regionModelFunctionObject (regionModel & region)
Construct null from region.
Definition at line 38 of file regionModelFunctionObject.C.
regionModelFunctionObject (const dictionary & dict, regionModel & region, const word & modelType)
Construct from dictionary.
Definition at line 49 of file regionModelFunctionObject.C.
regionModelFunctionObject (const regionModelFunctionObject & ppm)
Construct copy.
Definition at line 62 of file regionModelFunctionObject.C.
~regionModelFunctionObject () virtual
Destructor.
Definition at line 74 of file regionModelFunctionObject.C.
Member Function Documentation
TypeName ("regionModelFunctionObject")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , regionModelFunctionObject , dictionary , (const dictionary &dict, regionModel &region) , (dict, region))
Declare runtime constructor selection table.
virtual autoPtr<regionModelFunctionObject> clone () const inline virtual
Construct and return a clone.
Definition at line 124 of file regionModelFunctionObject.H.
Foam::autoPtr< Foam::regionModels::regionModelFunctionObject > New (const dictionary & dict, regionModel & region, const word & modelType) static
Selector.
Definition at line 28 of file regionModelFunctionObjectNew.C.
References Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), Foam::Info, and dictionary::subDict().
void preEvolveRegion () virtual
Pre-evolve region hook.
Definition at line 80 of file regionModelFunctionObject.C.
void postEvolveRegion () virtual
Post-evolve region hook.
Definition at line 84 of file regionModelFunctionObject.C.
void write () const virtual
write
Definition at line 93 of file regionModelFunctionObject.C.
References Foam::vtk::write().
Member Data Documentation
dictionary dict_ protected
Dictionary.
Definition at line 63 of file regionModelFunctionObject.H.
regionModel& regionModel_ protected
Reference to the region model.
Definition at line 68 of file regionModelFunctionObject.H.
word modelType_ protected
Model type name.
Definition at line 73 of file regionModelFunctionObject.H.
The documentation for this class was generated from the following files:
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObject.H
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObject.C
src/regionModels/regionModel/regionModelFunctionObject/regionModelFunctionObject/regionModelFunctionObjectNew.C