OpenFOAM: FieldField< Field, Type > Class Template Reference
FieldField< Field, Type > Class Template Reference
A field of fields is a PtrList of fields with reference counting.
Public Types
typedef pTraits< Type >::cmptType cmptType
Component type.
Public Types inherited from UPtrList< T >
typedef T value_type
Type of values the list contains.
typedef T & reference
A non-const reference to the value_type.
typedef const T & const_reference
A const reference to the value_type.
Public Member Functions
constexpr FieldField () noexcept
Construct null.
FieldField (const label size)
Construct given size.
FieldField (const word &type, const FieldField< Field, Type > &ff)
Clone construct with new type.
FieldField (const FieldField< Field, Type > &ff)
Copy construct, cloning each element.
FieldField (FieldField< Field, Type > &&ff)
Move construct.
FieldField (FieldField< Field, Type > &ff, bool reuse)
Construct as copy or re-use as specified.
FieldField (const PtrList< Field< Type >> &list)
Copy construct from PtrList.
FieldField (PtrList< Field< Type >> &&list)
Move construct from PtrList.
FieldField (const tmp< FieldField< Field, Type >> &tf)
Move/copy construct from tmp<FieldField>
FieldField (Istream &is)
Construct from Istream.
tmp< FieldField< Field, Type > > clone () const
Clone.
void negate ()
Negate this field.
tmp< FieldField< Field,
cmptType > > component (const direction) const
Return a component field of the field.
void replace (const direction, const FieldField< Field, cmptType > &)
Replace a component field of the field.
void replace (const direction, const cmptType &)
Replace a component field of the field.
tmp< FieldField< Field, Type > > T () const
Return the field transpose (only defined for second rank tensors)
void operator= (const FieldField< Field, Type > &)
Copy assignment.
void operator= (FieldField< Field, Type > &&)
Move assignment.
void operator= (const tmp< FieldField< Field, Type >> &)
Move or clone assignment.
void operator= (const Type &val)
Assign uniform value.
void operator+= (const FieldField< Field, Type > &)
void operator+= (const tmp< FieldField< Field, Type >> &)
void operator-= (const FieldField< Field, Type > &)
void operator-= (const tmp< FieldField< Field, Type >> &)
void operator*= (const FieldField< Field, scalar > &)
void operator*= (const tmp< FieldField< Field, scalar >> &)
void operator/= (const FieldField< Field, scalar > &)
void operator/= (const tmp< FieldField< Field, scalar >> &)
void operator+= (const Type &)
void operator-= (const Type &)
void operator*= (const scalar &)
void operator/= (const scalar &)
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Public Member Functions inherited from PtrList< Field< Type > >
constexpr PtrList () noexcept
Construct null.
PtrList (const label len)
Construct with specified size, each element initialized to nullptr.
PtrList (const PtrList< Field< Type > > &list)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< Field< Type > > &&list)
Move construct.
PtrList (UList< Field< Type > * > &list)
Take ownerskip of pointers in the list, set old pointers to null.
PtrList (const PtrList< Field< Type > > &list, const CloneArg &cloneArgs)
Copy construct using 'clone()' method on each element.
PtrList (PtrList< Field< Type > > &list, bool reuse)
Construct as copy or re-use as specified.
PtrList (const SLPtrList< Field< Type > > &list)
Copy construct using 'clone()' on each element of SLPtrList<T>
PtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
PtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~PtrList ()
Destructor.
PtrList< Field< Type > > clone (Args &&...args) const
Make a copy by cloning each of the list elements.
void clear ()
Clear the PtrList. Delete allocated entries and set size to zero.
void resize (const label newLen)
Adjust size of PtrList.
void setSize (const label newLen)
Same as resize()
void append (Field< Type > *ptr)
Append an element to the end of the list.
void append (autoPtr< Field< Type > > &aptr)
Move append an element to the end of the list.
void append (autoPtr< Field< Type > > &&aptr)
Move append an element to the end of the list.
void append (const tmp< Field< Type > > &tptr)
Move or clone append a tmp to the end of the list.
void transfer (PtrList< Field< Type > > &list)
Transfer into this list and annul the argument list.
const Field< Type > * set (const label i) const
Return const pointer to element (if set) or nullptr.
autoPtr< Field< Type > > set (const label i, Field< Type > *ptr)
Set element to given pointer and return old element (can be null)
autoPtr< Field< Type > > set (const label i, autoPtr< Field< Type > > &aptr)
Set element to given autoPtr and return old element.
autoPtr< Field< Type > > set (const label i, autoPtr< Field< Type > > &&aptr)
Set element to given autoPtr and return old element.
autoPtr< Field< Type > > set (const label i, const tmp< Field< Type > > &tptr)
Set element to given tmp and return old element.
autoPtr< Field< Type > > release (const label i)
Release ownership of the pointer at the given position.
void operator= (const PtrList< Field< Type > > &list)
Copy assignment.
void operator= (PtrList< Field< Type > > &&list)
Move assignment.
Public Member Functions inherited from UPtrList< T >
constexpr UPtrList () noexcept
Construct null.
UPtrList (const label len)
Construct with specified size, each element initialized to nullptr.
UPtrList (const UPtrList< T > &list)
Copy construct (shallow copies addresses)
UPtrList (UPtrList< T > &&list)
Move construct.
UPtrList (UPtrList< T > &list, bool reuse)
Construct as shallow copy or re-use as specified.
UPtrList (PtrList< T > &list)
Shallow copy from PtrList.
UPtrList (UList< T > &list)
Construct from UList, taking the address of each list element.
label size () const noexcept
The number of elements in the list.
bool empty () const noexcept
True if the list is empty (ie, size() is zero)
T & first ()
Return reference to the first element of the list.
const T & first () const
Return reference to first element of the list.
T & last ()
Return reference to the last element of the list.
const T & last () const
Return reference to the last element of the list.
void clear ()
Set list size to zero.
void resize (const label newLen)
Reset size of list.
void setSize (const label newLen)
Same as resize()
label squeezeNull ()
Squeeze out intermediate nullptr entries in the list of pointers.
void append (T *ptr)
Append an element to the end of the list.
void swap (UPtrList< T > &list)
Swap content.
void transfer (UPtrList< T > &list)
Transfer contents into this list and annul the argument.
const T * set (const label i) const
Return const pointer to element (if set) or nullptr.
T * set (const label i, T *ptr)
Set element to specified pointer and return the old list element, which can be a nullptr.
void reorder (const labelUList &oldToNew, const bool testNull=true)
Reorder elements. Reordering must be unique (ie, shuffle).
void sortOrder (const labelUList &order, const bool testNull=true)
Reorder elements according to new order mapping (newToOld). Reordering must be unique (ie, shuffle).
const T & operator[] (const label i) const
Return const reference to the element.
T & operator[] (const label i)
Return reference to the element.
const T * operator() (const label i) const
Return const pointer to the element.
void operator= (const UPtrList< T > &list)
Copy assignment (shallow copies addresses)
void operator= (UPtrList< T > &&list)
Move assignment.
iterator begin ()
Return an iterator to begin traversing the UPtrList.
iterator end ()
Return an iterator to end traversing the UPtrList.
const_iterator cbegin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator cend () const
Return an const_iterator to end traversing the UPtrList.
const_iterator begin () const
Return an const_iterator to begin traversing the UPtrList.
const_iterator end () const
Return an const_iterator to end traversing the UPtrList.
Static Public Member Functions
template<class Type2 >
static tmp< FieldField< Field,
Type > > NewCalculatedType (const FieldField< Field, Type2 > &ff)
Return a pointer to a new calculatedFvPatchFieldField created on.
Friends
Ostream & operator (Ostream &, const FieldField< Field, Type > &)
Ostream & operator (Ostream &, const tmp< FieldField< Field, Type >> &)
Additional Inherited Members
Protected Member Functions inherited from PtrList< Field< Type > >
void readIstream (Istream &is, const INew &inew)
Read from Istream using Istream constructor class.
void free ()
Delete the allocated entries, but retain the list size.
Protected Member Functions inherited from UPtrList< T >
UPtrList (Detail::PtrListDetail< T > &&ptrs)
Low-level move construct.
Protected Attributes inherited from UPtrList< T >
Detail::PtrListDetail< T > ptrs_
The list of pointers.
Detailed Description
template<template< class > class Field, class Type>
class Foam::FieldField< Field, Type >
A field of fields is a PtrList of fields with reference counting.
Source files
FieldField.H
FieldField.C
Definition at line 49 of file FieldField.H.
Member Typedef Documentation
typedef pTraits<Type>::cmptType cmptType
Component type.
Definition at line 82 of file FieldField.H.
Constructor & Destructor Documentation
constexpr FieldField () noexcept
Construct null.
Used for temporary fields which are initialised after construction
Definition at line 101 of file FieldField.C.
FieldField (const label size) explicit
Construct given size.
Used for temporary fields which are initialised after construction
Definition at line 108 of file FieldField.C.
FieldField (const word & type, const FieldField< Field, Type > & ff)
Clone construct with new type.
Definition at line 116 of file FieldField.C.
FieldField (const FieldField< Field, Type > & ff)
Copy construct, cloning each element.
Definition at line 131 of file FieldField.C.
References i, and PtrList< Field< Type > >::set().
FieldField (FieldField< Field, Type > && ff)
Move construct.
Definition at line 138 of file FieldField.C.
FieldField (FieldField< Field, Type > & ff, bool reuse)
Construct as copy or re-use as specified.
Definition at line 145 of file FieldField.C.
FieldField (const PtrList< Field< Type >> & list)
Copy construct from PtrList.
Definition at line 152 of file FieldField.C.
FieldField (PtrList< Field< Type >> && list)
Move construct from PtrList.
Definition at line 159 of file FieldField.C.
FieldField (const tmp< FieldField< Field, Type >> & tf)
Move/copy construct from tmp<FieldField>
Definition at line 166 of file FieldField.C.
FieldField (Istream & is)
Construct from Istream.
Definition at line 175 of file FieldField.C.
References List< T >::clear().
Member Function Documentation
tmp< FieldField< Field, Type > > clone () const
Clone.
Definition at line 182 of file FieldField.C.
tmp< FieldField< Field, Type > > NewCalculatedType (const FieldField< Field, Type2 > & ff) static
Return a pointer to a new calculatedFvPatchFieldField created on.
freestore without setting patchField values
Definition at line 191 of file FieldField.C.
Referenced by reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, Type2 >::New(), reuseTmpTmpFieldField< Field, TypeR, Type1, Type12, TypeR >::New(), reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, Type2 >::New(), and reuseTmpTmpFieldField< Field, TypeR, TypeR, TypeR, TypeR >::New().
void negate ()
Negate this field.
Definition at line 212 of file FieldField.C.
tmp< FieldField< Field, typename FieldField< Field, Type >::cmptType > > component (const direction d) const
Return a component field of the field.
Definition at line 224 of file FieldField.C.
void replace (const direction d, const FieldField< Field, cmptType > & sf)
Replace a component field of the field.
Definition at line 242 of file FieldField.C.
void replace (const direction d, const cmptType & s)
Replace a component field of the field.
Definition at line 256 of file FieldField.C.
tmp< FieldField< Field, Type > > T () const
Return the field transpose (only defined for second rank tensors)
Definition at line 269 of file FieldField.C.
References i.
Referenced by Moment< Type >::Moment().
void operator= (const FieldField< Field, Type > & ff)
Copy assignment.
Definition at line 284 of file FieldField.C.
void operator= (FieldField< Field, Type > && ff)
Move assignment.
Definition at line 301 of file FieldField.C.
References i.
void operator= (const tmp< FieldField< Field, Type >> &)
Move or clone assignment.
void operator= (const Type & val)
Assign uniform value.
Definition at line 333 of file FieldField.C.
void operator+= (const FieldField< Field, Type > & f)
Definition at line 372 of file FieldField.C.
void operator+= (const tmp< FieldField< Field, Type >> & tf)
Definition at line 372 of file FieldField.C.
void operator-= (const FieldField< Field, Type > & f)
Definition at line 373 of file FieldField.C.
void operator-= (const tmp< FieldField< Field, Type >> & tf)
Definition at line 373 of file FieldField.C.
void operator*= (const FieldField< Field, scalar > & f)
Definition at line 374 of file FieldField.C.
void operator*= (const tmp< FieldField< Field, scalar >> & tf)
Definition at line 374 of file FieldField.C.
void operator/= (const FieldField< Field, scalar > & f)
Definition at line 375 of file FieldField.C.
void operator/= (const tmp< FieldField< Field, scalar >> & tf)
Definition at line 375 of file FieldField.C.
void operator+= (const Type & t)
Definition at line 372 of file FieldField.C.
void operator-= (const Type & t)
Definition at line 373 of file FieldField.C.
void operator*= (const scalar & t)
Definition at line 374 of file FieldField.C.
void operator/= (const scalar & t)
Definition at line 375 of file FieldField.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const FieldField< Field, Type > &) friend
Ostream& operator (Ostream & , const tmp< FieldField< Field, Type >> &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/fields/FieldFields/FieldField/FieldField.H
src/OpenFOAM/fields/FieldFields/FieldField/FieldField.C