OpenFOAM: cpuTimeCxx Class Reference
cpuTimeCxx Class Reference
Starts timing CPU usage and return elapsed time from start.
Public Member Functions
cpuTimeCxx ()
Construct with the current clock time.
void resetCpuTime ()
Reset to use the current time for the start time.
double elapsedCpuTime () const
Return CPU time (in seconds) from the start.
double cpuTimeIncrement () const
Return CPU time (in seconds) since last call to cpuTimeIncrement()
Detailed Description
Starts timing CPU usage and return elapsed time from start.
See Also
clockTime
Source files
cpuTimeCxx.H
cpuTimeCxx.C
Definition at line 49 of file cpuTimeCxx.H.
Constructor & Destructor Documentation
cpuTimeCxx ()
Construct with the current clock time.
Definition at line 39 of file cpuTimeCxx.C.
References update().
Member Function Documentation
void resetCpuTime ()
Reset to use the current time for the start time.
Definition at line 54 of file cpuTimeCxx.C.
References value().
double elapsedCpuTime () const
Return CPU time (in seconds) from the start.
Definition at line 61 of file cpuTimeCxx.C.
double cpuTimeIncrement () const
Return CPU time (in seconds) since last call to cpuTimeIncrement()
Definition at line 68 of file cpuTimeCxx.C.
References Foam::diff().
The documentation for this class was generated from the following files:
src/OpenFOAM/global/cpuTime/cpuTimeCxx.H
src/OpenFOAM/global/cpuTime/cpuTimeCxx.C