OpenFOAM: fileMonitor Class Reference
fileMonitor Class Reference
Checking for changes to files.
Public Types
enum fileState { UNMODIFIED = 0, MODIFIED = 1, DELETED = 2 }
Enumeration defining the file state.
Public Member Functions
ClassName ("fileMonitor")
fileMonitor (const bool useInotify)
Construct null.
~fileMonitor ()
Destructor.
label addWatch (const fileName &)
Add file to watch. Return watch descriptor.
bool removeWatch (const label watchFd)
Remove file to watch. Return true if successful.
const fileName & getFile (const label watchFd) const
Get name of file being watched.
fileState getState (const label watchFd) const
Check state using handle.
void updateStates (const bool masterOnly, const bool syncPar) const
Check state of all files. Updates state_.
void setUnmodified (const label watchFd)
Reset state (e.g. after having read it) using handle.
Static Public Attributes
static const Enum< fileState > fileStateNames_
Detailed Description
Checking for changes to files.
Note
The default is to use stat to get the timestamp.
Compile with FOAM_USE_INOTIFY to use the inotify (Linux specific, since 2.6.13) framework. The problem is that inotify does not work on nfs3 mounted directories!!
Source files
fileMonitor.H
fileMonitor.C
Definition at line 61 of file fileMonitor.H.
Member Enumeration Documentation
enum fileState
Enumeration defining the file state.
Enumerator
UNMODIFIED
MODIFIED
DELETED
Definition at line 70 of file fileMonitor.H.
Constructor & Destructor Documentation
fileMonitor (const bool useInotify) explicit
Construct null.
Definition at line 438 of file fileMonitor.C.
~fileMonitor ()
Destructor.
Definition at line 451 of file fileMonitor.C.
References Foam::endl(), and Foam::Pout.
Member Function Documentation
ClassName ("fileMonitor")
Foam::label addWatch (const fileName & fName)
Add file to watch. Return watch descriptor.
Definition at line 459 of file fileMonitor.C.
bool removeWatch (const label watchFd)
Remove file to watch. Return true if successful.
Definition at line 500 of file fileMonitor.C.
const Foam::fileName & getFile (const label watchFd) const
Get name of file being watched.
Definition at line 516 of file fileMonitor.C.
Foam::fileMonitor::fileState getState (const label watchFd) const
Check state using handle.
Definition at line 522 of file fileMonitor.C.
References UPstream::master().
void updateStates (const bool masterOnly, const bool syncPar) const
Check state of all files. Updates state_.
Definition at line 530 of file fileMonitor.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), forAll, Pstream::listCombineGather(), Pstream::listCombineScatter(), UPstream::master(), Foam::Pout, Foam::reduce(), Pstream::scatter(), and WarningInFunction.
void setUnmodified (const label watchFd)
Reset state (e.g. after having read it) using handle.
Definition at line 626 of file fileMonitor.C.
Member Data Documentation
const Foam::Enum< Foam::fileMonitor::fileState > fileStateNames_ static
Definition at line 77 of file fileMonitor.H.
The documentation for this class was generated from the following files:
src/OSspecific/POSIX/fileMonitor/fileMonitor.H
src/OSspecific/POSIX/fileMonitor/fileMonitor.C