OpenFOAM: sixDoFSolver Class Reference
sixDoFSolver Class Reference abstract
Solvers
Public Member Functions
TypeName ("sixDoFSolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sixDoFSolver, dictionary,(const dictionary &dict, sixDoFRigidBodyMotion &body),(dict, body))
sixDoFSolver (const dictionary &dict, sixDoFRigidBodyMotion &body)
virtual autoPtr< sixDoFSolver > clone () const =0
Construct and return a clone.
virtual ~sixDoFSolver ()
Destructor.
virtual void solve (bool firstIter, const vector &fGlobal, const vector &tauGlobal, scalar deltaT, scalar deltaT0)=0
Drag coefficient.
void write (Ostream &) const
Write.
Static Public Member Functions
static autoPtr< sixDoFSolver > New (const dictionary &dict, sixDoFRigidBodyMotion &body)
Protected Member Functions
point & centreOfRotation ()
Return the current centre of rotation.
tensor & Q ()
Return the orientation.
vector & v ()
Return non-const access to vector.
vector & a ()
Return non-const access to acceleration.
vector & pi ()
Return non-const access to angular momentum.
vector & tau ()
Return non-const access to torque.
const point & centreOfRotation0 () const
Return the centre of rotation at previous time-step.
const tensor & Q0 () const
Return the orientation at previous time-step.
const vector & v0 () const
Return the velocity at previous time-step.
const vector & a0 () const
Return the acceleration at previous time-step.
const vector & pi0 () const
Return the angular momentum at previous time-step.
const vector & tau0 () const
Return the torque at previous time-step.
scalar aDamp () const
Acceleration damping coefficient (for steady-state simulations)
tensor tConstraints () const
Translational constraint tensor.
tensor rConstraints () const
Rotational constraint tensor.
Tuple2< tensor, vector > rotate (const tensor &Q0, const vector &pi, const scalar deltaT) const
Apply rotation tensors to Q0 for the given torque (pi) and deltaT.
void updateAcceleration (const vector &fGlobal, const vector &tauGlobal)
Update and relax accelerations from the force and torque.
Protected Attributes
sixDoFRigidBodyMotion & body_
The rigid body.
dictionary dict_
Model dictionary.
Detailed Description
Source files
sixDoFSolver.H
sixDoFSolver.C
newSixDoFSolver.C
Definition at line 50 of file sixDoFSolver.H.
Constructor & Destructor Documentation
sixDoFSolver (const dictionary & dict, sixDoFRigidBodyMotion & body)
Definition at line 36 of file sixDoFSolver.C.
~sixDoFSolver () virtual
Destructor.
Definition at line 53 of file sixDoFSolver.C.
Member Function Documentation
Foam::point & centreOfRotation () inline protected
Return the current centre of rotation.
Definition at line 23 of file sixDoFSolverI.H.
Foam::tensor & Q () inline protected
Return the orientation.
Definition at line 28 of file sixDoFSolverI.H.
References sixDoFSolver::body_, and sixDoFRigidBodyMotionState::centreOfRotation().
Foam::vector & v () inline protected
Return non-const access to vector.
Definition at line 33 of file sixDoFSolverI.H.
Foam::vector & a () inline protected
Return non-const access to acceleration.
Definition at line 38 of file sixDoFSolverI.H.
Foam::vector & pi () inline protected
Return non-const access to angular momentum.
Definition at line 43 of file sixDoFSolverI.H.
Foam::vector & tau () inline protected
Return non-const access to torque.
Definition at line 48 of file sixDoFSolverI.H.
const Foam::point & centreOfRotation0 () const inline protected
Return the centre of rotation at previous time-step.
Definition at line 54 of file sixDoFSolverI.H.
const Foam::tensor & Q0 () const inline protected
Return the orientation at previous time-step.
Definition at line 59 of file sixDoFSolverI.H.
const Foam::vector & v0 () const inline protected
Return the velocity at previous time-step.
Definition at line 65 of file sixDoFSolverI.H.
const Foam::vector & a0 () const inline protected
Return the acceleration at previous time-step.
Definition at line 71 of file sixDoFSolverI.H.
const Foam::vector & pi0 () const inline protected
Return the angular momentum at previous time-step.
Definition at line 77 of file sixDoFSolverI.H.
const Foam::vector & tau0 () const inline protected
Return the torque at previous time-step.
Definition at line 83 of file sixDoFSolverI.H.
Foam::scalar aDamp () const inline protected
Acceleration damping coefficient (for steady-state simulations)
Definition at line 88 of file sixDoFSolverI.H.
Foam::tensor tConstraints () const inline protected
Translational constraint tensor.
Definition at line 93 of file sixDoFSolverI.H.
Foam::tensor rConstraints () const inline protected
Rotational constraint tensor.
Definition at line 98 of file sixDoFSolverI.H.
Foam::Tuple2< Foam::tensor, Foam::vector > rotate (const tensor & Q0, const vector & pi, const scalar deltaT) const inline protected
Apply rotation tensors to Q0 for the given torque (pi) and deltaT.
and return the rotated Q and pi as a tuple
Definition at line 109 of file sixDoFSolverI.H.
void updateAcceleration (const vector & fGlobal, const vector & tauGlobal) inline protected
Update and relax accelerations from the force and torque.
Definition at line 122 of file sixDoFSolverI.H.
TypeName ("sixDoFSolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , sixDoFSolver , dictionary , (const dictionary &dict, sixDoFRigidBodyMotion &body) , (dict, body))
virtual autoPtr<sixDoFSolver> clone () const pure virtual
Construct and return a clone.
Implemented in CrankNicolson, Newmark, and symplectic.
Foam::autoPtr< Foam::sixDoFSolver > New (const dictionary & dict, sixDoFRigidBodyMotion & body) static
Definition at line 27 of file newSixDoFSolver.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual void solve (bool firstIter, const vector & fGlobal, const vector & tauGlobal, scalar deltaT, scalar deltaT0) pure virtual
Drag coefficient.
Implemented in CrankNicolson, Newmark, and symplectic.
void write (Ostream & os) const
Write.
Definition at line 46 of file sixDoFSolver.C.
Member Data Documentation
sixDoFRigidBodyMotion& body_ protected
The rigid body.
Definition at line 59 of file sixDoFSolver.H.
Referenced by symplectic::clone(), and sixDoFSolver::Q().
dictionary dict_ protected
Model dictionary.
Definition at line 64 of file sixDoFSolver.H.
Referenced by symplectic::clone().
The documentation for this class was generated from the following files:
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/sixDoFSolver.H
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/newSixDoFSolver.C
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/sixDoFSolver.C
src/sixDoFRigidBodyMotion/sixDoFSolvers/sixDoFSolver/sixDoFSolverI.H