OpenFOAM: IOstream Class Reference
IOstream Class Reference abstract
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
Public Types
enum streamAccess : char { CLOSED = 0, OPENED }
Enumeration for stream open/closed state.
Public Types inherited from IOstreamOption
enum streamFormat : char { ASCII, BINARY }
Data format (ascii | binary)
enum compressionType : char { UNCOMPRESSED = 0, COMPRESSED }
Compression treatment (UNCOMPRESSED | COMPRESSED)
Public Member Functions
IOstream (const IOstreamOption option)
Construct with specified stream option.
IOstream (streamFormat format, versionNumber version, compressionType compression=UNCOMPRESSED)
Construct with format, version.
virtual ~IOstream ()=default
Destructor.
virtual const fileName & name () const
Return the name of the stream.
virtual fileName & name ()
Return non-const access to the name of the stream.
virtual bool check (const char *operation) const
Check IOstream status for given operation.
void fatalCheck (const char *operation) const
Check IOstream status for given operation.
bool opened () const
Return true if stream has been opened.
bool closed () const
Return true if stream is closed.
bool good () const
Return true if next operation might succeed.
bool eof () const
Return true if end of input seen.
bool fail () const
Return true if next operation will fail.
bool bad () const
Return true if stream is corrupted.
operator bool () const
Return true if the stream has not failed.
bool operator! () const
Return true if the stream has failed.
unsigned labelByteSize () const
The label byte-size associated with the stream.
unsigned scalarByteSize () const
The scalar byte-size associated with the stream.
void setLabelByteSize (unsigned nbytes)
Set the label byte-size associated with the stream.
void setScalarByteSize (unsigned nbytes)
Set the scalar byte-size associated with the stream.
template<class T = label>
std::enable_if
< std::is_integral< T >::value,
bool >::type checkLabelSize () const
Check if the label byte-size associated with the stream is the same as the given type.
template<class T = scalar>
std::enable_if
< std::is_floating_point< T >
::value, bool >::type checkScalarSize () const
Check if the scalar byte-size associated with the stream is the same as the given type.
label lineNumber () const
Const access to the current stream line number.
label & lineNumber ()
Non-const access to the current stream line number.
label lineNumber (const label num)
Set the stream line number.
virtual ios_base::fmtflags flags () const =0
Return flags of stream.
void setEof ()
Set stream to have reached eof.
void setFail ()
Set stream to have failed.
void setBad ()
Set stream to be bad.
virtual ios_base::fmtflags flags (const ios_base::fmtflags f)=0
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f)
Set flags of stream.
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask)
Set flags of given field of stream.
void unsetf (const ios_base::fmtflags f)
Unset flags of stream.
virtual void print (Ostream &os) const
Print description of IOstream to Ostream.
void print (Ostream &os, const int streamState) const
Print information about the stream state bits.
InfoProxy< IOstream > info () const
Return info proxy.
Public Member Functions inherited from IOstreamOption
IOstreamOption () noexcept
Construct null. (default: ASCII, uncompressed, currentVersion)
IOstreamOption (streamFormat format) noexcept
Construct with format. (default: uncompressed, currentVersion)
IOstreamOption (streamFormat format, compressionType compression, versionNumber version=currentVersion) noexcept
Construct with format and compression, optionally with version.
IOstreamOption (streamFormat format, versionNumber version, compressionType compression) noexcept
Construct with format, version, compression.
streamFormat format () const noexcept
Get the current stream format.
streamFormat format (const streamFormat format) noexcept
Set the stream format.
streamFormat format (const word &formatName)
Set the stream format, from string value.
compressionType compression () const noexcept
Get the stream compression.
compressionType compression (const compressionType comp) noexcept
Set the stream compression.
compressionType compression (const word &compressionName)
Set the stream compression, from string value.
versionNumber version () const noexcept
Get the stream version.
versionNumber version (const versionNumber verNum) noexcept
Set the stream version.
Static Public Member Functions
static unsigned int defaultPrecision ()
Return the default precision.
static unsigned int defaultPrecision (unsigned int prec)
Reset the default precision.
Static Public Member Functions inherited from IOstreamOption
static streamFormat formatEnum (const word &formatName)
The stream format enum corresponding to the string.
static compressionType compressionEnum (const word &compName)
The compression enum corresponding to the string.
Static Public Attributes
static unsigned int precision_
Default precision.
Static Public Attributes inherited from IOstreamOption
static const Enum< streamFormat > formatNames
Stream format names (ascii, binary)
static const versionNumber originalVersion
The original version number.
static const versionNumber currentVersion
The current version number.
Protected Member Functions
void setOpened ()
Set stream opened.
void setClosed ()
Set stream closed.
void setState (ios_base::iostate state)
Set stream state.
void setGood ()
Set stream to be good.
Protected Attributes
streamAccess openClosed_
ios_base::iostate ioState_
unsigned short labelByteSize_
The label byte-size (could also be stored as byte)
unsigned short scalarByteSize_
The scalar byte-size (could also be stored as byte)
label lineNumber_
The file line.
Static Protected Attributes
static fileName staticName_
Name for any generic stream - normally treat as readonly.
Detailed Description
An IOstream is an abstract base class for all input/output systems; be they streams, files, token lists etc.
The basic operations are construct, close, read token, read primitive and read binary block. In addition version control and line number counting is incorporated. Usually one would use the read primitive member functions, but if one were reading a stream on unknown data sequence one can read token by token, and then analyse.
Source files
IOstream.H
IOstream.C
Definition at line 71 of file IOstream.H.
Member Enumeration Documentation
enum streamAccess : char
Enumeration for stream open/closed state.
Enumerator
CLOSED
stream not open
OPENED
stream is open
Definition at line 82 of file IOstream.H.
Constructor & Destructor Documentation
IOstream (const IOstreamOption option) inline explicit
Construct with specified stream option.
Definition at line 170 of file IOstream.H.
IOstream (streamFormat format, versionNumber version, compressionType compression = UNCOMPRESSED) inline
Construct with format, version.
Definition at line 186 of file IOstream.H.
virtual ~IOstream () virtual default
Destructor.
Member Function Documentation
void setOpened () inline protected
Set stream opened.
Definition at line 133 of file IOstream.H.
Referenced by ISstream::ISstream(), ITstream::ITstream(), OSstream::OSstream(), and OTstream::OTstream().
void setClosed () inline protected
Set stream closed.
Definition at line 141 of file IOstream.H.
References IOstream::ioState_.
void setState (ios_base::iostate state) inline protected
Set stream state.
Definition at line 149 of file IOstream.H.
Referenced by OSstream::OSstream().
void setGood () inline protected
Set stream to be good.
Definition at line 157 of file IOstream.H.
References IOstream::setBad().
Referenced by ISstream::ISstream(), ITstream::ITstream(), OSstream::OSstream(), OTstream::OTstream(), and UOListStream::UOListStream().
const Foam::fileName & name () const virtual
Return the name of the stream.
Useful for Fstream to return the filename
Reimplemented in ITstream, primitiveEntry, ISstream, and OSstream.
Definition at line 32 of file IOstream.C.
Referenced by IOobject::readHeader().
Foam::fileName & name () virtual
Return non-const access to the name of the stream.
Useful to alter the stream name
Reimplemented in ITstream, primitiveEntry, ISstream, and OSstream.
Definition at line 38 of file IOstream.C.
References IOstream::staticName_.
bool check (const char * operation) const virtual
Check IOstream status for given operation.
Print IOstream state if error has occurred
Definition at line 44 of file IOstream.C.
Referenced by CollisionRecordList< PairType, WallType >::CollisionRecordList(), kinematicParcelInjectionData::kinematicParcelInjectionData(), maxFirstOp< T1 >::operator()(), Foam::operator<<(), eddy::operator=(), Foam::operator>>(), orientedType::oriented(), PairCollisionRecord< Type >::PairCollisionRecord(), reactingMultiphaseParcelInjectionData::reactingMultiphaseParcelInjectionData(), reactingParcelInjectionData::reactingParcelInjectionData(), thermoParcelInjectionData::thermoParcelInjectionData(), VectorSpace< Form, Cmpt, Ncmpts >::VectorSpace(), WallCollisionRecord< Type >::WallCollisionRecord(), PtrListDetail< T >::write(), UILList< LListBase, T >::writeList(), and IndirectListBase< T, Addr >::writeList().
void fatalCheck (const char * operation) const
Check IOstream status for given operation.
Print IOstream state if error has occurred and exit
Definition at line 57 of file IOstream.C.
Referenced by dictionaryEntry::dictionaryEntry(), PtrList< T >::readIstream(), and dictionaryEntry::write().
bool opened () const inline
Return true if stream has been opened.
Definition at line 240 of file IOstream.H.
References IOstream::fail().
Referenced by meshRefinement::findRegions().
bool closed () const inline
Return true if stream is closed.
Definition at line 248 of file IOstream.H.
References IOstream::fail().
bool good () const inline
Return true if next operation might succeed.
Definition at line 256 of file IOstream.H.
References IOstream::labelByteSize_.
Referenced by populationBalanceModel::gamma(), STARCDMeshReader::readBoundary(), STARCDMeshReader::readCells(), STARCDCore::readHeader(), IOobject::readHeader(), STARCDsurfaceFormatCore::readInpCellTable(), STARCDMeshReader::readPoints(), refinementHistory::removeFiles(), TableFile< Type >::TableFile(), FLMAsurfaceFormat< Face >::write(), X3DsurfaceFormat< Face >::write(), SMESHsurfaceFormat< Face >::write(), AveragingMethod< Type >::write(), correlationFunction< Type >::writeAveraged(), fieldDictionary::writeData(), GlobalIOList< Type >::writeData(), GlobalIOField< Type >::writeData(), and pairPotential::writeEnergyAndForceTables().
bool eof () const inline
Return true if end of input seen.
Definition at line 264 of file IOstream.H.
Referenced by laplacianScheme< Type >::laplacianScheme(), lnGradScheme< Type >::New(), gradScheme< Type >::New(), edgeInterpolationScheme< Type >::New(), convectionScheme< Type >::New(), snGradScheme< Type >::New(), divScheme< Type >::New(), surfaceInterpolationScheme< Type >::New(), faD2dt2Scheme< Type >::New(), d2dt2Scheme< Type >::New(), faDdtScheme< Type >::New(), limitedSurfaceInterpolationScheme< Type >::New(), laplacianScheme< Type >::New(), ddtScheme< Type >::New(), laplacianScheme< Type, GType >::New(), and PtrList< T >::readIstream().
bool fail () const inline
Return true if next operation will fail.
Definition at line 272 of file IOstream.H.
References IOstream::scalarByteSize_.
Referenced by IOstream::closed(), and IOstream::opened().
bool bad () const inline
Return true if stream is corrupted.
Definition at line 280 of file IOstream.H.
References IOstream::labelByteSize_, and Foam::T().
Referenced by Foam::getToken(), baseIOdictionary::readData(), featureEdgeMesh::writeData(), extendedFeatureEdgeMesh::writeData(), and refinementHistory::writeData().
operator bool () const inline explicit
Return true if the stream has not failed.
Definition at line 288 of file IOstream.H.
References IOstream::scalarByteSize_, and Foam::T().
bool operator! () const inline
Return true if the stream has failed.
Definition at line 296 of file IOstream.H.
unsigned labelByteSize () const inline
The label byte-size associated with the stream.
Definition at line 307 of file IOstream.H.
References IOstream::lineNumber_.
unsigned scalarByteSize () const inline
The scalar byte-size associated with the stream.
Definition at line 315 of file IOstream.H.
References IOstream::lineNumber_.
void setLabelByteSize (unsigned nbytes) inline
Set the label byte-size associated with the stream.
Definition at line 323 of file IOstream.H.
References IOstream::precision_.
Referenced by IOobject::readHeader().
void setScalarByteSize (unsigned nbytes) inline
Set the scalar byte-size associated with the stream.
Definition at line 331 of file IOstream.H.
References IOstream::precision_.
Referenced by IOobject::readHeader().
std::enable_if<std::is_integral<T>::value, bool>::type checkLabelSize () const inline
Check if the label byte-size associated with the stream is the same as the given type.
Definition at line 343 of file IOstream.H.
std::enable_if<std::is_floating_point<T>::value, bool>::type checkScalarSize () const inline
Check if the scalar byte-size associated with the stream is the same as the given type.
Definition at line 354 of file IOstream.H.
References IOstream::ioState_.
label lineNumber () const inline
Const access to the current stream line number.
Definition at line 365 of file IOstream.H.
Referenced by codeStream::evaluate(), and IOobject::readHeader().
label& lineNumber () inline
Non-const access to the current stream line number.
Definition at line 373 of file IOstream.H.
References IOstream::flags().
label lineNumber (const label num) inline
Set the stream line number.
Returns
the previous value
Definition at line 383 of file IOstream.H.
virtual ios_base::fmtflags flags () const pure virtual
Return flags of stream.
Implemented in OTstream, ITstream, dummyISstream, dummyIstream, UOPstream, UIPstream, ISstream, and OSstream.
Referenced by IOstream::lineNumber().
defaultPrecision () inline static
Return the default precision.
Definition at line 398 of file IOstream.H.
Referenced by VTKsurfaceFormatCore::formatOptions(), VTPsurfaceFormatCore::formatOptions(), patchProbes::sampleAndWrite(), and thermoCoupleProbes::sampleAndWrite().
static unsigned int defaultPrecision (unsigned int prec) inline static
Reset the default precision.
Returns
the previous value
Definition at line 408 of file IOstream.H.
void setEof () inline
Set stream to have reached eof.
Definition at line 418 of file IOstream.H.
References f().
void setFail () inline
Set stream to have failed.
Definition at line 426 of file IOstream.H.
void setBad () inline
Set stream to be bad.
Definition at line 434 of file IOstream.H.
Referenced by Foam::operator>>(), and IOstream::setGood().
virtual ios_base::fmtflags flags (const ios_base::fmtflags f) pure virtual
Set flags of stream.
Implemented in ITstream, UOPstream, OTstream, ISstream, UIPstream, OSstream, dummyISstream, and dummyIstream.
ios_base::fmtflags setf (const ios_base::fmtflags f) inline
Set flags of stream.
Definition at line 447 of file IOstream.H.
References Foam::scientific(), and IOstream::setf().
Referenced by writeFile::baseFileDir(), Foam::setf(), and IOstream::setf().
ios_base::fmtflags setf (const ios_base::fmtflags f, const ios_base::fmtflags mask) inline
Set flags of given field of stream.
Definition at line 456 of file IOstream.H.
void unsetf (const ios_base::fmtflags f) inline
Unset flags of stream.
Definition at line 467 of file IOstream.H.
void print (Ostream & os) const virtual
Print description of IOstream to Ostream.
Reimplemented in OListStream, ITstream, UOPstream, OTstream, UIListStream, OSstream, UOListStream, OCountStream, OStringStream, ISstream, UIPstream, IListStream, IStringStream, prefixOSstream, IFstream, and OFstream.
Definition at line 68 of file IOstream.C.
Referenced by decompositionInformation::printDetails().
void print (Ostream & os, const int streamState) const
Print information about the stream state bits.
Definition at line 107 of file IOstream.C.
InfoProxy<IOstream> info () const inline
Return info proxy.
Used to print IOstream information to a stream
Definition at line 493 of file IOstream.H.
Member Data Documentation
unsigned int precision_ static
Default precision.
Definition at line 94 of file IOstream.H.
Referenced by OSstream::OSstream(), IOstream::setLabelByteSize(), and IOstream::setScalarByteSize().
Foam::fileName staticName_ static protected
Name for any generic stream - normally treat as readonly.
Definition at line 104 of file IOstream.H.
Referenced by IOstream::name().
streamAccess openClosed_ protected
Definition at line 106 of file IOstream.H.
ios_base::iostate ioState_ protected
Definition at line 108 of file IOstream.H.
Referenced by IOstream::checkScalarSize(), and IOstream::setClosed().
unsigned short labelByteSize_ protected
The label byte-size (could also be stored as byte)
Definition at line 113 of file IOstream.H.
Referenced by IOstream::bad(), and IOstream::good().
unsigned short scalarByteSize_ protected
The scalar byte-size (could also be stored as byte)
Definition at line 118 of file IOstream.H.
Referenced by IOstream::fail(), and IOstream::operator bool().
label lineNumber_ protected
The file line.
Definition at line 123 of file IOstream.H.
Referenced by IOstream::labelByteSize(), and IOstream::scalarByteSize().
The documentation for this class was generated from the following files:
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.H
src/OpenFOAM/db/IOstreams/IOstreams/IOstream.C
src/OpenFOAM/db/IOstreams/IOstreams.C
src/surfMesh/writers/vtk/vtkSurfaceWriter.C