OpenFOAM: PhaseChangeModel< CloudType > Class Template Reference
PhaseChangeModel< CloudType > Class Template Reference abstract
Phase change
Templated phase change model class.
Public Types
enum enthalpyTransferType { etLatentHeat, etEnthalpyDifference }
Enthalpy transfer type.
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Public Member Functions
TypeName ("phaseChangeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, PhaseChangeModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
PhaseChangeModel (CloudType &owner)
Construct null from owner.
PhaseChangeModel (const dictionary &dict, CloudType &owner, const word &type)
Construct from dictionary.
PhaseChangeModel (const PhaseChangeModel< CloudType > &pcm)
Construct copy.
virtual autoPtr
< PhaseChangeModel< CloudType > > clone () const =0
Construct and return a clone.
virtual ~PhaseChangeModel ()=default
Destructor.
const enthalpyTransferType & enthalpyTransfer () const
Return the enthalpy transfer type enumeration.
virtual void calculate (const scalar dt, const label celli, const scalar Re, const scalar Pr, const scalar d, const scalar nu, const scalar T, const scalar Ts, const scalar pc, const scalar Tc, const scalarField &X, scalarField &dMassPC) const =0
Update model.
virtual scalar dh (const label idc, const label idl, const scalar p, const scalar T) const
Return the enthalpy per unit mass.
virtual scalar Tvap (const scalarField &X) const
Return vapourisation temperature.
virtual scalar TMax (const scalar p, const scalarField &X) const
Return maximum/limiting temperature.
void addToPhaseChangeMass (const scalar dMass)
Add to phase change mass.
virtual void info (Ostream &os)
Write injection info to stream.
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
virtual fileName localPath () const
Output directory.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
bool getModelDict (const word &entryName, dictionary &dict) const
Retrieve dictionary, return true if set.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Static Public Member Functions
static autoPtr
< PhaseChangeModel< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Static Public Attributes
static const wordList enthalpyTransferTypeNames
Name representations of enthalpy transfer types.
Protected Member Functions
enthalpyTransferType wordToEnthalpyTransfer (const word &etName) const
Convert word to enthalpy transfer type.
scalar Sh () const
Sherwood number.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
enthalpyTransferType enthalpyTransfer_
Enthalpy transfer type enumeration.
scalar dMass_
Mass of lagrangian phase converted.
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::PhaseChangeModel< CloudType >
Templated phase change model class.
Source files
PhaseChangeModel.H
PhaseChangeModel.C
PhaseChangeModelNew.C
Definition at line 57 of file ReactingCloud.H.
Member Enumeration Documentation
enum enthalpyTransferType
Enthalpy transfer type.
Enumerator
etLatentHeat
etEnthalpyDifference
Definition at line 65 of file PhaseChangeModel.H.
Constructor & Destructor Documentation
PhaseChangeModel (CloudType & owner)
Construct null from owner.
Definition at line 60 of file PhaseChangeModel.C.
PhaseChangeModel (const dictionary & dict, CloudType & owner, const word & type)
Construct from dictionary.
Definition at line 84 of file PhaseChangeModel.C.
PhaseChangeModel (const PhaseChangeModel< CloudType > & pcm)
Construct copy.
Definition at line 72 of file PhaseChangeModel.C.
virtual ~PhaseChangeModel () virtual default
Destructor.
Member Function Documentation
Foam::PhaseChangeModel< CloudType >::enthalpyTransferType wordToEnthalpyTransfer (const word & etName) const protected
Convert word to enthalpy transfer type.
Definition at line 37 of file PhaseChangeModel.C.
scalar Sh () const protected
Sherwood number.
TypeName ("phaseChangeModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , PhaseChangeModel< CloudType > , dictionary , (const dictionary &dict, CloudType &owner) , (dict, owner))
Declare runtime constructor selection table.
virtual autoPtr<PhaseChangeModel<CloudType> > clone () const pure virtual
Construct and return a clone.
Implemented in LiquidEvaporationBoil< CloudType >, LiquidEvaporation< CloudType >, and NoPhaseChange< CloudType >.
Foam::autoPtr< Foam::PhaseChangeModel< CloudType > > New (const dictionary & dict, CloudType & owner) static
Selector.
Definition at line 29 of file PhaseChangeModelNew.C.
References dict, Foam::endl(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
const Foam::PhaseChangeModel< CloudType >::enthalpyTransferType & enthalpyTransfer () const
Return the enthalpy transfer type enumeration.
Definition at line 103 of file PhaseChangeModel.C.
virtual void calculate (const scalar dt, const label celli, const scalar Re, const scalar Pr, const scalar d, const scalar nu, const scalar T, const scalar Ts, const scalar pc, const scalar Tc, const scalarField & X, scalarField & dMassPC) const pure virtual
Update model.
Implemented in LiquidEvaporationBoil< CloudType >, LiquidEvaporation< CloudType >, and NoPhaseChange< CloudType >.
Foam::scalar dh (const label idc, const label idl, const scalar p, const scalar T) const virtual
Return the enthalpy per unit mass.
Reimplemented in LiquidEvaporationBoil< CloudType >, and LiquidEvaporation< CloudType >.
Definition at line 111 of file PhaseChangeModel.C.
Foam::scalar Tvap (const scalarField & X) const virtual
Return vapourisation temperature.
Reimplemented in LiquidEvaporationBoil< CloudType >, and LiquidEvaporation< CloudType >.
Definition at line 134 of file PhaseChangeModel.C.
Foam::scalar TMax (const scalar p, const scalarField & X) const virtual
Return maximum/limiting temperature.
Reimplemented in LiquidEvaporationBoil< CloudType >, and LiquidEvaporation< CloudType >.
Definition at line 124 of file PhaseChangeModel.C.
void addToPhaseChangeMass (const scalar dMass)
Add to phase change mass.
Definition at line 141 of file PhaseChangeModel.C.
void info (Ostream & os) virtual
Write injection info to stream.
Definition at line 148 of file PhaseChangeModel.C.
Member Data Documentation
const Foam::wordList enthalpyTransferTypeNames static
Initial value:
{
    "latentHeat", "enthalpyDifference"
}
Name representations of enthalpy transfer types.
Definition at line 74 of file PhaseChangeModel.H.
enthalpyTransferType enthalpyTransfer_ protected
Enthalpy transfer type enumeration.
Definition at line 84 of file PhaseChangeModel.H.
scalar dMass_ protected
Mass of lagrangian phase converted.
Definition at line 92 of file PhaseChangeModel.H.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/ReactingCloud/ReactingCloud.H
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/PhaseChangeModel/PhaseChangeModel.H
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/PhaseChangeModel/PhaseChangeModel.C
src/lagrangian/intermediate/submodels/Reacting/PhaseChangeModel/PhaseChangeModel/PhaseChangeModelNew.C