OpenFOAM: triad Class Reference
triad Class Reference
Representation of a 3D Cartesian coordinate system as a Vector of row vectors.
Public Member Functions
triad ()
Construct null.
triad (const Vector< vector > &vv)
Construct from components.
triad (const vector &x, const vector &y, const vector &z)
Construct from coordinate axes (row vectors)
triad (const tensor &t)
Construct from a tensor.
triad (const vector &pa)
Construct from a primary axis with the other two unset.
triad (const quaternion &q)
Construct from a quaternion.
triad (Istream &)
Construct from Istream.
bool set (const direction d) const
Is the vector in the direction d set.
bool set () const
Are all the vector set.
void orthogonalize ()
Orthogonalize this triad so that it is ortho-normal.
void normalize ()
Normalize each set axis vector to have a unit magnitude.
void align (const vector &v)
Align this triad with the given vector v.
triad sortxyz () const
Sort the axes such that they are closest to the x, y and z axes.
operator quaternion () const
Convert to a quaternion.
triad T () const
Return transpose.
vector cx () const
Extract vector for column 0.
vector cy () const
Extract vector for column 1.
vector cz () const
Extract vector for column 2.
void operator= (const Vector< vector > &vv)
void operator= (const tensor &t)
void operator+= (const triad &t2)
Add the triad t2 to this triad.
Public Member Functions inherited from Vector< vector >
Vector ()
Construct null.
Vector (const Foam::zero)
Construct initialized to zero.
Vector (const VectorSpace< Vector< Cmpt2 >, Cmpt2, 3 > &vs)
Copy construct from VectorSpace of the same rank.
Vector (const vector &vx, const vector &vy, const vector &vz)
Construct from three components.
Vector (Istream &is)
Construct from Istream.
const vector & x () const
Access to the vector x component.
vector & x ()
Access to the vector x component.
const vector & y () const
Access to the vector y component.
vector & y ()
Access to the vector y component.
const vector & z () const
Access to the vector z component.
vector & z ()
Access to the vector z component.
Vector< vector > & normalise ()
Normalise the vector by its magnitude.
const Vector< vector > & centre (const Foam::List< Vector< vector >> &) const
Return *this (used for point which is a typedef to Vector<scalar>.
Public Member Functions inherited from VectorSpace< Vector< vector >, vector, 3 >
VectorSpace ()
Construct null.
VectorSpace (const Foam::zero)
Construct initialized to zero.
VectorSpace (Istream &is)
Construct from Istream.
VectorSpace (const VectorSpace< Vector< vector >, vector, Ncmpts > &vs)
Copy construct.
VectorSpace (const VectorSpace< Form2, Cmpt2, Ncmpts > &)
Copy construct of a VectorSpace with the same size.
const vector & component (const direction) const
vector & component (const direction)
void component (vector &, const direction) const
void replace (const direction, const vector &)
const vector * cdata () const noexcept
Return const pointer to the first data element.
vector * data () noexcept
Return pointer to the first data element.
const ConstBlock< SubVector,
BStart > block () const
const vector & operator[] (const direction) const
vector & operator[] (const direction)
void operator= (const VectorSpace< Vector< vector >, vector, Ncmpts > &)
void operator= (const Foam::zero)
void operator+= (const VectorSpace< Vector< vector >, vector, Ncmpts > &)
void operator-= (const VectorSpace< Vector< vector >, vector, Ncmpts > &)
void operator*= (const scalar)
void operator/= (const scalar)
iterator begin ()
Return an iterator to begin of VectorSpace.
const_iterator begin () const
Return const_iterator to begin of VectorSpace.
iterator end ()
Return an iterator to end of VectorSpace.
const_iterator end () const
Return const_iterator to end of VectorSpace.
const_iterator cbegin () const
Return const_iterator to begin of VectorSpace.
const_iterator cend () const
Return const_iterator to end of VectorSpace.
Static Public Member Functions
static direction primaryDirection (const vector &v)
Return the primary direction of the vector v.
static vector orthogonal (const vector &v1, const vector &v2)
Return the vector orthogonal to the two provided.
Static Public Member Functions inherited from VectorSpace< Vector< vector >, vector, 3 >
static constexpr direction size ()
Return the number of elements in the VectorSpace = Ncmpts.
static Vector< vector > uniform (const vector &s)
Return a VectorSpace with all elements = s.
Static Public Attributes
static const triad I
static const triad unset
Static Public Attributes inherited from Vector< vector >
static constexpr direction rank
Rank of Vector is 1.
Static Public Attributes inherited from VectorSpace< Vector< vector >, vector, 3 >
static constexpr direction dim
Dimensionality of space.
static constexpr direction nComponents
Number of components in this vector space.
static constexpr direction mRows
static constexpr direction nCols
static const char *const typeName
static const char *const componentNames []
static const Vector< vector > zero
static const Vector< vector > one
static const Vector< vector > max
static const Vector< vector > min
static const Vector< vector > rootMax
static const Vector< vector > rootMin
Friends
Istream & operator>> (Istream &, triad &)
Ostream & operator<< (Ostream &, const triad &)
Additional Inherited Members
Public Types inherited from Vector< vector >
enum components
Component labeling enumeration.
typedef Vector< label > labelType
Equivalent type of labels used for valid component indexing.
Public Types inherited from VectorSpace< Vector< vector >, vector, 3 >
typedef VectorSpace< Vector
< vector >, vector, Ncmpts > vsType
VectorSpace type.
typedef vector cmptType
Component type.
typedef vector magType
Magnitude type.
typedef vector * iterator
Random access iterator for traversing VectorSpace.
typedef const vector * const_iterator
Random access iterator for traversing VectorSpace.
Public Attributes inherited from VectorSpace< Vector< vector >, vector, 3 >
vector v_ [Ncmpts]
The components of this vector space.
Detailed Description
Representation of a 3D Cartesian coordinate system as a Vector of row vectors.
See Also
Foam::quaternion
Source files
triad.H
triadI.H
triad.C
Definition at line 62 of file triad.H.
Constructor & Destructor Documentation
triad () inline
Construct null.
Definition at line 24 of file triadI.H.
triad (const Vector< vector > & vv) inline
Construct from components.
Definition at line 30 of file triadI.H.
triad (const vector & x, const vector & y, const vector & z) inline
Construct from coordinate axes (row vectors)
Definition at line 36 of file triadI.H.
triad (const tensor & t) inline
Construct from a tensor.
Definition at line 42 of file triadI.H.
triad (const vector & pa) inline
Construct from a primary axis with the other two unset.
Definition at line 48 of file triadI.H.
triad (const quaternion & q)
Construct from a quaternion.
Definition at line 84 of file triad.C.
References quaternion::R(), Tensor< Cmpt >::T(), Vector< vector >::x(), and Vector< Cmpt >::x().
triad (Istream & is) inline
Construct from Istream.
Definition at line 55 of file triadI.H.
References triad::unset.
Member Function Documentation
bool set (const direction d) const inline
Is the vector in the direction d set.
Definition at line 63 of file triadI.H.
bool set () const inline
Are all the vector set.
Definition at line 69 of file triadI.H.
Foam::direction primaryDirection (const vector & v) inline static
Return the primary direction of the vector v.
Definition at line 75 of file triadI.H.
References set().
Foam::vector orthogonal (const vector & v1, const vector & v2) inline static
Return the vector orthogonal to the two provided.
Definition at line 93 of file triadI.H.
References Vector< vector >::Z.
void orthogonalize ()
Orthogonalize this triad so that it is ortho-normal.
Definition at line 95 of file triad.C.
void normalize () inline
Normalize each set axis vector to have a unit magnitude.
Definition at line 113 of file triadI.H.
References triad::unset.
void align (const vector & v)
Align this triad with the given vector v.
by rotating the most aligned axis to be coincident with v
Definition at line 233 of file triad.C.
Foam::triad sortxyz () const
Sort the axes such that they are closest to the x, y and z axes.
Definition at line 278 of file triad.C.
operator quaternion () const
Convert to a quaternion.
Foam::triad T () const inline
Return transpose.
Definition at line 139 of file triadI.H.
References x, and y.
Foam::vector cx () const inline
Extract vector for column 0.
Definition at line 121 of file triadI.H.
References Foam::mag(), and set().
Foam::vector cy () const inline
Extract vector for column 1.
Definition at line 127 of file triadI.H.
References x, and y.
Foam::vector cz () const inline
Extract vector for column 2.
Definition at line 133 of file triadI.H.
References x, and y.
void operator= (const Vector< vector > & vv) inline
Definition at line 147 of file triadI.H.
void operator= (const tensor & t) inline
Definition at line 153 of file triadI.H.
References VectorSpace< Vector< Cmpt >, Cmpt, 3 >::operator=().
void operator+= (const triad & t2)
Add the triad t2 to this triad.
without normalizing or orthogonalizing
Definition at line 170 of file triad.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , triad &) friend
Ostream& operator<< (Ostream & , const triad &) friend
Member Data Documentation
const Foam::triad I static
Definition at line 109 of file triad.H.
const Foam::triad unset static
Definition at line 110 of file triad.H.
Referenced by triad::normalize(), and triad::triad().
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/triad/triad.H
src/OpenFOAM/primitives/triad/triad.C
src/OpenFOAM/primitives/triad/triadI.H