OpenFOAM: hPolynomialThermo< EquationOfState, PolySize > Class Template Reference
hPolynomialThermo< EquationOfState, PolySize > Class Template Reference
Thermodynamics
Thermodynamics package templated on the equation of state, using polynomial functions for cp, h and s.
Public Member Functions
hPolynomialThermo (const dictionary &dict)
Construct from dictionary.
hPolynomialThermo (const word &, const hPolynomialThermo &)
Construct as a named copy.
scalar limit (const scalar) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar Cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar Ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kg].
scalar Hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar dGdT (const scalar p, const scalar T) const
Derivative of Gibbs free energy w.r.t. temperature.
scalar dCpdT (const scalar p, const scalar T) const
Temperature derivative of heat capacity at constant pressure.
void write (Ostream &os) const
Write to Ostream.
void operator= (const hPolynomialThermo &)
void operator+= (const hPolynomialThermo &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
Return the instantiated type name.
Friends
hPolynomialThermo operator+ (const hPolynomialThermo &, const hPolynomialThermo &)
hPolynomialThermo operator* (const scalar, const hPolynomialThermo &)
hPolynomialThermo operator== (const hPolynomialThermo &, const hPolynomialThermo &)
Ostream & operator (Ostream &, const hPolynomialThermo &)
Detailed Description
template<class EquationOfState, int PolySize>
class Foam::hPolynomialThermo< EquationOfState, PolySize >
Thermodynamics package templated on the equation of state, using polynomial functions for cp, h and s.
Polynomials for h and s derived from cp.
Usage
Property Description
Hf Heat of formation
Sf Standard entropy
CpCoeffs<8> Specific heat at constant pressure polynomial coeffs
Example of the specification of the thermodynamic properties:
    thermodynamics
    {
        Hf              0;
        Sf              0;
        CpCoeffs<8>     ( 1000 -0.05 0.003 0 0 0 0 0 );
    }
The polynomial expression is evaluated as so:
Note
Heat of formation is inputted in [J/kg], but internally uses [J/kmol]
Standard entropy is inputted in [J/kg/K], but internally uses [J/kmol/K]
Specific heat at constant pressure polynomial coefficients evaluate to an expression in [J/(kg.K)].
Source files
hPolynomialThermo.H
hPolynomialThermoI.H
hPolynomialThermo.C
See Also
Foam::Polynomial
Definition at line 99 of file hPolynomialThermo.H.
Constructor & Destructor Documentation
hPolynomialThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 28 of file hPolynomialThermo.C.
References Foam::constant::standard::Tstd.
hPolynomialThermo (const word & name, const hPolynomialThermo< EquationOfState, PolySize > & pt) inline
Construct as a named copy.
Definition at line 49 of file hPolynomialThermoI.H.
Member Function Documentation
static word typeName () inline static
Return the instantiated type name.
Definition at line 213 of file hPolynomialThermo.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 67 of file hPolynomialThermoI.H.
Foam::scalar Cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 77 of file hPolynomialThermoI.H.
References T.
Foam::scalar Ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kg].
Definition at line 87 of file hPolynomialThermoI.H.
References Cp.
Foam::scalar Hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 97 of file hPolynomialThermoI.H.
References H().
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 106 of file hPolynomialThermoI.H.
References Ha(), and T.
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 115 of file hPolynomialThermoI.H.
References Hf_().
Foam::scalar dGdT (const scalar p, const scalar T) const inline
Derivative of Gibbs free energy w.r.t. temperature.
Definition at line 126 of file hPolynomialThermoI.H.
Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Temperature derivative of heat capacity at constant pressure.
Definition at line 142 of file hPolynomialThermoI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 54 of file hPolynomialThermo.C.
void operator= (const hPolynomialThermo< EquationOfState, PolySize > &) inline
Definition at line 157 of file hPolynomialThermoI.H.
void operator+= (const hPolynomialThermo< EquationOfState, PolySize > &) inline
Definition at line 173 of file hPolynomialThermoI.H.
void operator*= (const scalar s) inline
Definition at line 197 of file hPolynomialThermoI.H.
Friends And Related Function Documentation
hPolynomialThermo operator+ (const hPolynomialThermo< EquationOfState, PolySize > & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
hPolynomialThermo operator* (const scalar , const hPolynomialThermo< EquationOfState, PolySize > &) friend
hPolynomialThermo operator== (const hPolynomialThermo< EquationOfState, PolySize > & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
Ostream& operator (Ostream & , const hPolynomialThermo< EquationOfState, PolySize > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermo.H
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermo.C
src/thermophysicalModels/specie/thermo/hPolynomial/hPolynomialThermoI.H