OpenFOAM: constantAlphaContactAngleFvPatchScalarField Class Reference
constantAlphaContactAngleFvPatchScalarField Class Reference
A constant alphaContactAngle scalar boundary condition.
Public Member Functions
TypeName ("constantAlphaContactAngle")
Runtime type information.
constantAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
constantAlphaContactAngleFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping given.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField &)
Construct as copy.
virtual tmp< fvPatchScalarField > clone () const
Construct and return a clone.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual tmp< scalarField > theta (const fvPatchVectorField &Up, const fvsPatchVectorField &nHat) const
Return the equilibrium contact-angle.
virtual void write (Ostream &) const
Write.
Public Member Functions inherited from alphaContactAngleTwoPhaseFvPatchScalarField
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
Construct from patch and internal field.
alphaContactAngleTwoPhaseFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
Construct by mapping onto a new patch.
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &)
Construct as copy.
alphaContactAngleTwoPhaseFvPatchScalarField (const alphaContactAngleTwoPhaseFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
Construct as copy setting internal field reference.
virtual void evaluate (const Pstream::commsTypes commsType=Pstream::commsTypes::blocking)
Evaluate the patch field.
Additional Inherited Members
Public Types inherited from alphaContactAngleTwoPhaseFvPatchScalarField
enum limitControls { lcNone, lcGradient, lcZeroGradient, lcAlpha }
Alpha limit options.
Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
limitControls limit_
Static Public Attributes inherited from alphaContactAngleTwoPhaseFvPatchScalarField
static const Enum< limitControls > limitControlNames_
Detailed Description
A constant alphaContactAngle scalar boundary condition.
See Also
Foam::alphaContactAngleTwoPhaseFvPatchScalarField Foam::temperatureDependentAlphaContactAngleFvPatchScalarField
Source files
constantAlphaContactAngleFvPatchScalarField.H
constantAlphaContactAngleFvPatchScalarField.C
Definition at line 51 of file constantAlphaContactAngleFvPatchScalarField.H.
Constructor & Destructor Documentation
constantAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Construct from patch and internal field.
Definition at line 31 of file constantAlphaContactAngleFvPatchScalarField.C.
Referenced by constantAlphaContactAngleFvPatchScalarField::clone().
constantAlphaContactAngleFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 43 of file constantAlphaContactAngleFvPatchScalarField.C.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField & gcpsf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Construct by mapping given.
constantAlphaContactAngleFvPatchScalarField onto a new patch
Definition at line 58 of file constantAlphaContactAngleFvPatchScalarField.C.
References Foam::stringOps::evaluate().
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField & gcpsf)
Construct as copy.
Definition at line 72 of file constantAlphaContactAngleFvPatchScalarField.C.
constantAlphaContactAngleFvPatchScalarField (const constantAlphaContactAngleFvPatchScalarField & gcpsf, const DimensionedField< scalar, volMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 83 of file constantAlphaContactAngleFvPatchScalarField.C.
Member Function Documentation
TypeName ("constantAlphaContactAngle")
Runtime type information.
virtual tmp<fvPatchScalarField> clone () const inline virtual
Construct and return a clone.
Definition at line 117 of file constantAlphaContactAngleFvPatchScalarField.H.
References constantAlphaContactAngleFvPatchScalarField::constantAlphaContactAngleFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 138 of file constantAlphaContactAngleFvPatchScalarField.H.
Foam::tmp< Foam::scalarField > theta (const fvPatchVectorField & Up, const fvsPatchVectorField & nHat) const virtual
Return the equilibrium contact-angle.
Implements alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 97 of file constantAlphaContactAngleFvPatchScalarField.C.
void write (Ostream & os) const virtual
Write.
Reimplemented from alphaContactAngleTwoPhaseFvPatchScalarField.
Definition at line 107 of file constantAlphaContactAngleFvPatchScalarField.C.
References tmp< T >::New().
The documentation for this class was generated from the following files:
src/transportModels/twoPhaseProperties/alphaContactAngle/constantAlphaContactAngle/constantAlphaContactAngleFvPatchScalarField.H
src/transportModels/twoPhaseProperties/alphaContactAngle/constantAlphaContactAngle/constantAlphaContactAngleFvPatchScalarField.C