OpenFOAM: triangle< Point, PointRef > Class Template Reference
triangle< Point, PointRef > Class Template Reference
A triangle primitive used to calculate face normals and swept volumes.
Classes
class dummyOp
Dummy.
class storeOp
Store resulting tris.
class sumAreaOp
Sum resulting areas.
Public Types
enum proxType { NONE, POINT, EDGE }
Return types for classify.
typedef FixedList< triPoints, 27 > triIntersectionList
Storage type for triangles originating from intersecting triangle.
Public Member Functions
triangle (const Point &a, const Point &b, const Point &c)
Construct from three points.
triangle (const FixedList< Point, 3 > &tri)
Construct from three points.
triangle (const UList< Point > &points, const FixedList< label, 3 > &indices)
Construct from three points in the list of points.
triangle (Istream &is)
Construct from Istream.
const Point & a () const
Return first vertex.
const Point & b () const
Return second vertex.
const Point & c () const
Return third vertex.
Point centre () const
Return centre (centroid)
vector areaNormal () const
The area normal - with magnitude equal to area of triangle.
vector unitNormal () const
Return unit normal.
vector FOAM_DEPRECATED_FOR (2018-12,"areaNormal() or unitNormal()") normal() const
Legacy name for areaNormal().
scalar mag () const
Return scalar magnitude.
Point circumCentre () const
Return circum-centre.
scalar circumRadius () const
Return circum-radius.
scalar quality () const
Return quality: Ratio of triangle and circum-circle.
scalar sweptVol (const triangle &t) const
Return swept-volume.
tensor inertia (PointRef refPt=Zero, scalar density=1.0) const
Return the inertia tensor, with optional reference.
Point randomPoint (Random &rndGen) const
Return a random point on the triangle from a uniform.
Point barycentricToPoint (const barycentric2D &bary) const
Calculate the point from the given barycentric coordinates.
barycentric2D pointToBarycentric (const point &pt) const
Calculate the barycentric coordinates from the given point.
scalar pointToBarycentric (const point &pt, barycentric2D &bary) const
Calculate the barycentric coordinates from the given point.
pointHit ray (const point &p, const vector &q, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction dir=intersection::VECTOR) const
Return point intersection with a ray.
pointHit intersection (const point &p, const vector &q, const intersection::algorithm alg, const scalar tol=0.0) const
Fast intersection with a ray.
pointHit nearestPointClassify (const point &p, label &nearType, label &nearLabel) const
Find the nearest point to p on the triangle and classify it:
pointHit nearestPoint (const point &p) const
Return nearest point to p on triangle.
bool classify (const point &p, label &nearType, label &nearLabel) const
Classify nearest point to p in triangle plane.
pointHit nearestPoint (const linePointRef &edge, pointHit &edgePoint) const
Return nearest point to line on triangle. Returns hit if.
int sign (const point &p, const scalar tol=SMALL) const
The sign for which side of the face plane the point is on.
template<class AboveOp , class BelowOp >
void sliceWithPlane (const plane &pln, AboveOp &aboveOp, BelowOp &belowOp) const
Decompose triangle into triangles above and below plane.
template<class InsideOp , class OutsideOp >
void triangleOverlap (const vector &n, const triangle< Point, PointRef > &tri, InsideOp &insideOp, OutsideOp &outsideOp) const
Decompose triangle into triangles inside and outside.
Friends
Istream & operator>> (Istream &, triangle &)
Ostream & operator (Ostream &, const triangle &)
Detailed Description
template<class Point, class PointRef>
class Foam::triangle< Point, PointRef >
A triangle primitive used to calculate face normals and swept volumes.
Source files
triangle.H
triangleI.H
Definition at line 58 of file triangle.H.
Member Typedef Documentation
typedef FixedList<triPoints, 27> triIntersectionList
Storage type for triangles originating from intersecting triangle.
with another triangle
Definition at line 93 of file triangle.H.
Member Enumeration Documentation
enum proxType
Return types for classify.
Enumerator
NONE
POINT
EDGE
Definition at line 98 of file triangle.H.
Constructor & Destructor Documentation
triangle (const Point & a, const Point & b, const Point & c) inline
Construct from three points.
Definition at line 31 of file triangleI.H.
triangle (const FixedList< Point, 3 > & tri) inline
Construct from three points.
Definition at line 45 of file triangleI.H.
triangle (const UList< Point > & points, const FixedList< label, 3 > & indices) inline
Construct from three points in the list of points.
The indices could be from triFace etc.
Definition at line 57 of file triangleI.H.
triangle (Istream & is) inline
Construct from Istream.
Definition at line 70 of file triangleI.H.
Member Function Documentation
const Point & a () const inline
Return first vertex.
Definition at line 79 of file triangleI.H.
const Point & b () const inline
Return second vertex.
Definition at line 85 of file triangleI.H.
const Point & c () const inline
Return third vertex.
Definition at line 91 of file triangleI.H.
References b_().
Point centre () const inline
Return centre (centroid)
Definition at line 98 of file triangleI.H.
Foam::vector areaNormal () const inline
The area normal - with magnitude equal to area of triangle.
Definition at line 105 of file triangleI.H.
References b_().
Foam::vector unitNormal () const inline
Return unit normal.
Definition at line 112 of file triangleI.H.
References b_().
vector FOAM_DEPRECATED_FOR (2018- 12, "areaNormal() or unitNormal()") const inline
Legacy name for areaNormal().
Deprecated:
(2018-06) Deprecated for new use
Definition at line 254 of file triangle.H.
Foam::scalar mag () const inline
Return scalar magnitude.
Definition at line 121 of file triangleI.H.
Point circumCentre () const inline
Return circum-centre.
Definition at line 128 of file triangleI.H.
References Foam::mag().
Foam::scalar circumRadius () const inline
Return circum-radius.
Definition at line 155 of file triangleI.H.
Foam::scalar quality () const inline
Return quality: Ratio of triangle and circum-circle.
area, scaled so that an equilateral triangle has a quality of 1
Definition at line 176 of file triangleI.H.
Foam::scalar sweptVol (const triangle< Point, PointRef > & t) const inline
Return swept-volume.
Definition at line 192 of file triangleI.H.
Foam::tensor inertia (PointRef refPt = Zero, scalar density = 1.0) const inline
Return the inertia tensor, with optional reference.
point and density specification
Definition at line 211 of file triangleI.H.
Point randomPoint (Random & rndGen) const inline
Return a random point on the triangle from a uniform.
distribution
Definition at line 247 of file triangleI.H.
Point barycentricToPoint (const barycentric2D & bary) const inline
Calculate the point from the given barycentric coordinates.
Definition at line 255 of file triangleI.H.
References barycentric2D01().
Foam::barycentric2D pointToBarycentric (const point & pt) const inline
Calculate the barycentric coordinates from the given point.
Definition at line 265 of file triangleI.H.
References b_().
Foam::scalar pointToBarycentric (const point & pt, barycentric2D & bary) const inline
Calculate the barycentric coordinates from the given point.
Returns the determinant.
Definition at line 277 of file triangleI.H.
Foam::pointHit ray (const point & p, const vector & q, const intersection::algorithm alg = intersection::FULL_RAY, const intersection::direction dir = intersection::VECTOR) const inline
Return point intersection with a ray.
For a hit, the distance is signed. Positive number represents the point in front of triangle. In case of miss pointHit is set to nearest point on triangle and its distance to the distance between the original point and the plane intersection point
Definition at line 316 of file triangleI.H.
Foam::pointHit intersection (const point & p, const vector & q, const intersection::algorithm alg, const scalar tol = 0.0) const inline
Fast intersection with a ray.
For a hit, the pointHit.distance() is the line parameter t : intersection=p+t*q. Only defined for VISIBLE, FULL_RAY or HALF_RAY. tol increases the virtual size of the triangle by a relative factor.
Definition at line 432 of file triangleI.H.
Referenced by mappedPatchBase::facePoint().
Foam::pointHit nearestPointClassify (const point & p, label & nearType, label & nearLabel) const
Find the nearest point to p on the triangle and classify it:
+ near point (nearType=POINT, nearLabel=0, 1, 2) + near edge (nearType=EDGE, nearLabel=0, 1, 2) Note: edges are counted from starting vertex so e.g. edge 2 is from f[2] to f[0]
Definition at line 515 of file triangleI.H.
Foam::pointHit nearestPoint (const point & p) const inline
Return nearest point to p on triangle.
Definition at line 664 of file triangleI.H.
bool classify (const point & p, label & nearType, label & nearLabel) const inline
Classify nearest point to p in triangle plane.
w.r.t. triangle edges and points. Returns inside (true)/outside (false).
Definition at line 678 of file triangleI.H.
Foam::pointHit nearestPoint (const linePointRef & edge, pointHit & edgePoint) const inline
Return nearest point to line on triangle. Returns hit if.
point is inside triangle. Sets edgePoint to point on edge (hit if nearest is inside line)
Definition at line 690 of file triangleI.H.
int sign (const point & p, const scalar tol = SMALL) const inline
The sign for which side of the face plane the point is on.
Uses the supplied tolerance for rounding around zero.
Returns
0: on plane
+1: front-side
-1: back-side
Definition at line 816 of file triangleI.H.
void sliceWithPlane (const plane & pln, AboveOp & aboveOp, BelowOp & belowOp) const inline
Decompose triangle into triangles above and below plane.
Definition at line 108 of file triangle.C.
void triangleOverlap (const vector & n, const triangle< Point, PointRef > & tri, InsideOp & insideOp, OutsideOp & outsideOp) const inline
Decompose triangle into triangles inside and outside.
(with respect to user provided normal) other triangle.
Definition at line 121 of file triangle.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , triangle< Point, PointRef > &) friend
Ostream& operator (Ostream & , const triangle< Point, PointRef > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/primitiveShapes/triangle/triangle.H
src/OpenFOAM/meshes/primitiveShapes/triangle/triangle.C
src/OpenFOAM/meshes/primitiveShapes/triangle/triangleI.H