OpenFOAM: dictionary Class Reference
dictionary Class Reference
A list of keyword definitions, which are a keyword followed by a number of values (eg, words and numbers) or by a sub-dictionary. Since the dictionary format is used extensively throughout OpenFOAM for input/output files, there are many examples of its use.
Classes
class Searcher
Generic const/non-const dictionary entry searcher.
Public Types
typedef Searcher< true > const_searcher
Searcher with const access.
typedef Searcher< false > searcher
Searcher with non-const access.
Public Types inherited from UILList< LListBase, T >
typedef T value_type
Type of values stored.
typedef T * pointer
Pointer for value_type.
typedef const T * const_pointer
Const pointer for value_type.
typedef T & reference
Reference for value_type.
typedef const T & const_reference
Const reference for value_type.
typedef label size_type
The type that can represent the container size.
typedef label difference_type
The difference between iterator objects.
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Member Functions
ClassName ("dictionary")
dictionary ()
Construct top-level dictionary null.
dictionary (const fileName &name)
Construct top-level empty dictionary with given name.
dictionary (const fileName &name, const dictionary &parentDict, Istream &is, bool keepHeader=false)
Construct given the entry name, parent dictionary and Istream, reading entries until EOF, optionally keeping the header.
dictionary (Istream &is)
Construct top-level dictionary from Istream, reading entries until EOF. Discards the header.
dictionary (Istream &is, bool keepHeader)
Construct top-level dictionary from Istream, reading entries until EOF, optionally keeping the header.
dictionary (const dictionary &parentDict, const dictionary &dict)
Copy construct given the parent dictionary.
dictionary (const dictionary &dict)
Copy construct top-level dictionary.
dictionary (const dictionary *dict)
Construct top-level dictionary as copy from pointer to dictionary.
dictionary (const dictionary &parentDict, dictionary &&dict)
Move construct for given parent dictionary.
dictionary (dictionary &&dict)
Move construct top-level dictionary.
autoPtr< dictionary > clone () const
Construct and return clone.
virtual ~dictionary ()
Destructor.
const fileName & name () const
The dictionary name.
fileName & name ()
The dictionary name for modification (use with caution).
word dictName () const
The local dictionary name (final part of scoped name)
const dictionary & parent () const
Return the parent dictionary.
const dictionary & topDict () const
Return the top of the tree.
label startLineNumber () const
Return line number of first token in dictionary.
label endLineNumber () const
Return line number of last token in dictionary.
SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
tokenList tokens () const
Return the dictionary as a list of tokens.
bool found (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Search for an entry (const access) with the given keyword.
entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find for an entry (non-const access) with the given keyword.
const entry * findEntry (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry (const access) with the given keyword.
const entry * findScoped (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Search for a scoped entry (const access) with the given keyword.
dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary pointer if present.
const dictionary * findDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary pointer if present.
const entry & lookupEntry (const word &keyword, enum keyType::option matchOpt) const
Search for an entry (const access) with the given keyword.
ITstream & lookup (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return an entry data stream. FatalIOError if not found, or if the number of tokens is incorrect.
template<class T >
T get (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T. FatalIOError if not found, or if the number of tokens is incorrect.
template<class T >
T getOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T getOrAdd (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
bool readEntry (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
template<class T >
bool readIfPresent (const word &keyword, T &val, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
T getCheck (const word &keyword, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T with additional checking FatalIOError if not found, or if the number of tokens is incorrect.
template<class T , class Predicate >
T getCheckOrDefault (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
T getCheckOrAdd (const word &keyword, const T &deflt, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T , class Predicate >
bool readCheck (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
template<class T , class Predicate >
bool readCheckIfPresent (const word &keyword, T &val, const Predicate &pred, enum keyType::option matchOpt=keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
bool isDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Check if entry is found and is a sub-dictionary.
const dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary.
dictionary & subDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary for manipulation.
dictionary & subDictOrAdd (const word &keyword, enum keyType::option matchOpt=keyType::REGEX)
Find and return a sub-dictionary for manipulation.
dictionary subOrEmptyDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX, const bool mandatory=false) const
Find and return a sub-dictionary as a copy, otherwise return an empty dictionary.
const dictionary & optionalSubDict (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a sub-dictionary, otherwise return this dictionary.
wordList toc () const
Return the table of contents.
wordList sortedToc () const
Return the sorted table of contents.
template<class Compare >
wordList sortedToc (const Compare &comp) const
Return table of contents sorted using the specified comparator.
List< keyType > keys (bool patterns=false) const
Return the list of available keys or patterns.
bool substituteKeyword (const word &keyword, bool mergeEntry=false)
Substitute the given keyword (which is prefixed by '$')
bool substituteScopedKeyword (const word &keyword, bool mergeEntry=false)
Substitute the given scoped keyword (which is prefixed by '$')
entry * add (entry *entryPtr, bool mergeEntry=false)
Add a new entry.
entry * add (const entry &e, bool mergeEntry=false)
Add an entry.
entry * add (const keyType &k, const word &v, bool overwrite=false)
Add a word entry.
entry * add (const keyType &k, const string &v, bool overwrite=false)
Add a string entry.
entry * add (const keyType &k, const label v, bool overwrite=false)
Add a label entry.
entry * add (const keyType &k, const scalar v, bool overwrite=false)
Add a scalar entry.
entry * add (const keyType &k, const dictionary &d, bool mergeEntry=false)
Add a dictionary entry.
template<class T >
entry * add (const keyType &k, const T &v, bool overwrite=false)
Add a T entry.
entry * set (entry *entryPtr)
Assign a new entry, overwriting any existing entry.
entry * set (const entry &e)
Assign a new entry, overwriting any existing entry.
entry * set (const keyType &k, const dictionary &v)
Assign a dictionary entry, overwriting any existing entry.
template<class T >
entry * set (const keyType &k, const T &v)
Assign a T entry, overwriting any existing entry.
bool remove (const word &keyword)
Remove an entry specified by keyword.
bool changeKeyword (const keyType &oldKeyword, const keyType &newKeyword, bool overwrite=false)
Change the keyword for an entry,.
bool merge (const dictionary &dict)
Merge entries from the given dictionary.
void clear ()
Clear the dictionary.
void transfer (dictionary &dict)
Transfer the contents of the argument and annul the argument.
void checkITstream (const ITstream &is, const word &keyword) const
Check after reading if the input token stream has unconsumed tokens remaining or if there were no tokens in the first place.
bool read (Istream &is)
Read dictionary from Istream.
bool read (Istream &is, bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
void writeEntry (const keyType &keyword, Ostream &os) const
Write sub-dictionary with the keyword as its header.
void writeEntries (Ostream &os, const bool extraNewLine=false) const
Write dictionary entries.
void write (Ostream &os, const bool subDict=true) const
Write dictionary, normally with sub-dictionary formatting.
const_searcher csearch (const word &keyword, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword.
const_searcher search (const word &keyword, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword.
searcher search (const word &keyword, enum keyType::option=keyType::REGEX)
Search dictionary for given keyword.
const_searcher csearchScoped (const word &keyword, enum keyType::option) const
Search using scoping.
const_searcher searchScoped (const word &keyword, enum keyType::option) const
Search using dot or slash scoping.
searcher searchScoped (const word &keyword, enum keyType::option)
Search using dot or slash scoping.
const dictionary * cfindScopedDict (const fileName &dictPath) const
Locate a sub-dictionary using slash-scoping.
const dictionary * findScopedDict (const fileName &dictPath) const
Locate a sub-dictionary using slash-scoping.
dictionary * findScopedDict (const fileName &dictPath)
Locate a sub-dictionary using slash-scoping.
dictionary * makeScopedDict (const fileName &dictPath)
Locate existing or create sub-dictionary using slash-scoping.
const_searcher csearchCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
bool foundCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
const entry * findCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option) const
Find and return an entry pointer if present, or return a nullptr, using any compatibility names if needed.
const entry & lookupEntryCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option) const
Find and return an entry if present, otherwise FatalIOError, using any compatibility names if needed.
ITstream & lookupCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Find and return an entry data stream, using any compatibility names if needed.
template<class T >
T getCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option=keyType::REGEX) const
Find and return a T using any compatibility names if needed. FatalIOError if not found, or if there are excess tokens.
template<class T >
T getOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, const T &deflt, enum keyType::option=keyType::REGEX) const
Find and return a T, or return the given default value using any compatibility names if needed.
template<class T >
bool readCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, T &val, enum keyType::option=keyType::REGEX, bool mandatory=true) const
Find entry and assign to T val using any compatibility names if needed. FatalIOError if there are excess tokens.
template<class T >
bool readIfPresentCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, T &val, enum keyType::option=keyType::REGEX) const
Find an entry if present, and assign to T val using any compatibility names if needed. FatalIOError if it is found and there are excess tokens.
void operator= (const dictionary &rhs)
Copy assignment.
void operator+= (const dictionary &rhs)
Include entries from the given dictionary.
void operator|= (const dictionary &rhs)
Conditionally include entries from the given dictionary.
void operator<<= (const dictionary &rhs)
Unconditionally include entries from the given dictionary.
template<class T >
T lookupOrDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T lookupOrAddDefault (const word &keyword, const T &deflt, enum keyType::option matchOpt=keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
template<class T >
T lookupOrDefaultCompat (const word &keyword, std::initializer_list< std::pair< const char *, int >> compat, const T &deflt, enum keyType::option matchOpt=keyType::REGEX) const
Find and return a T, or return the given default value using any compatibility names if needed.
ITstream & FOAM_DEPRECATED_FOR (2018-07,"lookup() method") operator[](const word &keyword) const
Deprecated(2018-07) find and return an entry data stream.
template<class T >
T FOAM_DEPRECATED_FOR (2018-10,"get() method") lookupType(const word &keyword
Deprecated(2018-10) find and return a T.
label getLabel (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< label >(const word&, keyType::option)
scalar getScalar (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< scalar >(const word&, keyType::option)
string getString (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< string >(const word&, keyType::option)
word getWord (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< word >(const word&, keyType::option)
fileName getFileName (const word &keyword, enum keyType::option matchOpt=keyType::REGEX) const
Same as get< fileName >(const word&, keyType::option)
template<class Compare >
Foam::wordList sortedToc (const Compare &comp) const
template<class T >
Foam::entry * add (const keyType &k, const T &v, bool overwrite)
template<class T >
Foam::entry * set (const keyType &k, const T &v)
Public Member Functions inherited from ILList< LListBase, T >
ILList ()=default
Null construct.
ILList (T *item)
Construct and insert the initial T item pointer.
ILList (Istream &is)
Construct from Istream.
ILList (const ILList< LListBase, T > &lst)
Copy construct using the 'clone()' method for each element.
ILList (ILList< LListBase, T > &&lst)
Move construct.
template<class CloneArg >
ILList (const ILList< LListBase, T > &lst, const CloneArg &cloneArg)
Copy constructor with additional argument for clone 'clone()'.
template<class INew >
ILList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
~ILList ()
Destructor.
bool eraseHead ()
Remove the head element specified from the list and delete it.
bool erase (T *item)
Remove the specified element from the list and delete it.
void clear ()
Clear the contents of the list.
void transfer (ILList< LListBase, T > &lst)
Transfer the contents of the argument into this List and annul the argument list.
void operator= (const ILList< LListBase, T > &lst)
Copy assignment using the 'clone()' method for each element.
void operator= (ILList< LListBase, T > &&lst)
Move assignment.
Public Member Functions inherited from UILList< LListBase, T >
UILList ()=default
Null construct.
UILList (T *item)
Construct and insert the initial T item.
UILList (const UILList< LListBase, T > &lst)
Construct as copy.
T * first ()
The first entry in the list.
const T * first () const
The first entry in the list (const access)
T * last ()
The last entry in the list.
const T * last () const
The last entry in the list (const access)
T * removeHead ()
Remove and return head.
T * remove (T *item)
Remove and return element.
T * remove (iterator &iter)
Remove and return item specified by iterator.
void operator= (const UILList< LListBase, T > &lst)
Copy assignment.
bool operator== (const UILList< LListBase, T > &lst) const
Equality. True both lists are element-wise equal.
bool operator!= (const UILList< LListBase, T > &lst) const
The opposite of the equality operation. Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write UILList with line-breaks when length exceeds shortLen.
iterator begin ()
Iterator to first item in list with non-const access.
const_iterator cbegin () const
Iterator to first item in list with const access.
reverse_iterator rbegin ()
Iterator to last item in list with non-const access.
const_reverse_iterator crbegin () const
Iterator to last item in list with const access.
const_iterator begin () const
Iterator to first item in list with const access.
const_reverse_iterator rbegin () const
Iterator to last item in list with const access.
const iterator & end ()
End of list for forward iterators.
const const_iterator & cend () const
End of list for forward iterators.
const reverse_iterator & rend ()
End of list for reverse iterators.
const const_reverse_iterator & crend () const
End of list for reverse iterators.
const const_iterator & end () const
End of list for forward iterators.
const const_reverse_iterator & rend () const
End of list for reverse iterators.
Static Public Member Functions
static autoPtr< dictionary > New (Istream &is)
Construct top-level dictionary on freestore from Istream.
Public Attributes
friend const_searcher
Declare friendship with the searcher classes.
friend searcher
T bool recursive = false
T bool bool patternMatch
Static Public Attributes
static int writeOptionalEntries
Report optional keywords and values if not present in dictionary.
static const dictionary null
An empty dictionary, which is also the parent for all dictionaries.
Friends
class entry
Declare friendship with the entry class for IO.
Istream & operator>> (Istream &is, dictionary &dict)
Read dictionary from Istream.
Ostream & operator<< (Ostream &os, const dictionary &dict)
Write dictionary to Ostream.
Detailed Description
A list of keyword definitions, which are a keyword followed by a number of values (eg, words and numbers) or by a sub-dictionary. Since the dictionary format is used extensively throughout OpenFOAM for input/output files, there are many examples of its use.
Dictionary keywords are a plain word or a pattern (regular expression). The general order for searching is as follows:
exact match
pattern match (in reverse order)
optional recursion into the enclosing (parent) dictionaries
The dictionary class is the base class for IOdictionary and also serves as a bootstrap dictionary for the objectRegistry data dictionaries.
Note
Within dictionaries, entries can be referenced by using the '$' syntax familiar from shell programming. A '.' separator is used when referencing sub-dictionary entries. Leading '.' prefixes can be used to specify an entry from a parent dictionary. An initial '^' anchor (or ':' for backward compatibility) specifies starting from the top-level entry. For example,
key1        val1;
key2        $key1;   // use key1 value from current scope
key3        $.key1;  // use key1 value from current scope
subdict1
{
    key1        val1b;
    key2        $..key1; // use key1 value from parent
    subdict2
    {
        key2    val2;
        key3    $...key1; // use key1 value from grandparent
    }
}
key4        $^subdict1.subdict2.key3;  // lookup with absolute scoping
It is also possible to use the '${}' syntax for clarity.
Source files
dictionary.H
dictionary.C
dictionaryIO.C
dictionarySearch.C
See Also
Foam::entry
Foam::dictionaryEntry
Foam::primitiveEntry
Definition at line 117 of file dictionary.H.
Member Typedef Documentation
typedef Searcher<true> const_searcher
Searcher with const access.
Definition at line 313 of file dictionary.H.
typedef Searcher<false> searcher
Searcher with non-const access.
Definition at line 318 of file dictionary.H.
Constructor & Destructor Documentation
dictionary ()
Construct top-level dictionary null.
Definition at line 74 of file dictionary.C.
dictionary (const fileName & name) explicit
Construct top-level empty dictionary with given name.
Definition at line 81 of file dictionary.C.
dictionary (const fileName & name, const dictionary & parentDict, Istream & is, bool keepHeader = false)
Construct given the entry name, parent dictionary and Istream, reading entries until EOF, optionally keeping the header.
Definition at line 28 of file dictionaryIO.C.
dictionary (Istream & is)
Construct top-level dictionary from Istream, reading entries until EOF. Discards the header.
Definition at line 42 of file dictionaryIO.C.
References Foam::blockMeshTools::read().
dictionary (Istream & is, bool keepHeader)
Construct top-level dictionary from Istream, reading entries until EOF, optionally keeping the header.
Definition at line 48 of file dictionaryIO.C.
dictionary (const dictionary & parentDict, const dictionary & dict)
Copy construct given the parent dictionary.
Definition at line 89 of file dictionary.C.
dictionary (const dictionary & dict)
Copy construct top-level dictionary.
Definition at line 112 of file dictionary.C.
dictionary (const dictionary * dict)
Construct top-level dictionary as copy from pointer to dictionary.
A null pointer is treated like an empty dictionary.
Definition at line 133 of file dictionary.C.
dictionary (const dictionary & parentDict, dictionary && dict)
Move construct for given parent dictionary.
Definition at line 146 of file dictionary.C.
References dictionary::operator=().
dictionary (dictionary && dict)
Move construct top-level dictionary.
Definition at line 160 of file dictionary.C.
References fileName::concat(), Foam::name(), and transfer().
~dictionary () virtual
Destructor.
Definition at line 179 of file dictionary.C.
References autoPtr< T >::New().
Member Function Documentation
ClassName ("dictionary")
Foam::autoPtr< Foam::dictionary > clone () const
Construct and return clone.
Definition at line 171 of file dictionary.C.
References transfer().
Referenced by Foam::preservePatchTypes().
Foam::autoPtr< Foam::dictionary > New (Istream & is) static
Construct top-level dictionary on freestore from Istream.
Definition at line 62 of file dictionaryIO.C.
const fileName& name () const inline
The dictionary name.
Definition at line 559 of file dictionary.H.
Referenced by dictionaryEntry::clone(), codeStream::evaluate(), meshRefinement::subDict(), and Foam::warnCompatDegrees().
fileName& name () inline
The dictionary name for modification (use with caution).
Definition at line 567 of file dictionary.H.
word dictName () const inline
The local dictionary name (final part of scoped name)
Definition at line 575 of file dictionary.H.
Referenced by basicSolidChemistryModel::New(), ParticleForce< CloudType >::ParticleForce(), and pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel().
const dictionary& parent () const inline
Return the parent dictionary.
Definition at line 591 of file dictionary.H.
const Foam::dictionary & topDict () const
Return the top of the tree.
Definition at line 185 of file dictionary.C.
Foam::label startLineNumber () const
Return line number of first token in dictionary.
Definition at line 198 of file dictionary.C.
Foam::label endLineNumber () const
Return line number of last token in dictionary.
Definition at line 209 of file dictionary.C.
Foam::SHA1Digest digest () const
Return the SHA1 digest of the dictionary contents.
Definition at line 220 of file dictionary.C.
Foam::tokenList tokens () const
Return the dictionary as a list of tokens.
Definition at line 234 of file dictionary.C.
bool found (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Search for an entry (const access) with the given keyword.
Parameters
matchOpt the default search is non-recursive with patterns
Returns
True if entry was found
Definition at line 352 of file dictionary.C.
Referenced by DAC< CompType, ThermoType >::DAC(), DRG< CompType, ThermoType >::DRG(), DRGEP< CompType, ThermoType >::DRGEP(), subModelBase::getBaseProperty(), turbulentDigitalFilterInletFvPatchVectorField::interpolateOrRead(), turbulentDFSEMInletFvPatchVectorField::interpolateOrRead(), MappedFile< Type >::MappedFile(), mappedPatchBase::mappedPatchBase(), waveModel::New(), PFA< CompType, ThermoType >::PFA(), Foam::preservePatchTypes(), pressureControl::pressureControl(), exprDriver::readTable(), refinementParameters::refinementParameters(), searchableSurfaces::searchableSurfaces(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::setPorosityCoefficient(), and Foam::setRefCell().
Foam::entry * findEntry (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Find for an entry (non-const access) with the given keyword.
Parameters
matchOpt the search mode
Returns
the entry pointer found or a nullptr.
Definition at line 362 of file dictionary.C.
Referenced by Foam::getOrAdd(), Function1< Type >::New(), and PatchFunction1< Type >::New().
const Foam::entry * findEntry (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Find an entry (const access) with the given keyword.
Parameters
matchOpt the default search is non-recursive with patterns
Returns
the entry pointer found or a nullptr.
Definition at line 372 of file dictionary.C.
References Foam::search().
const Foam::entry * findScoped (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Search for a scoped entry (const access) with the given keyword.
Allows scoping using '.'. Special handling for an absolute anchor (^) at start of the keyword and for '..' to ascend into the parent dictionaries.
Parameters
matchOpt the default search is non-recursive with patterns
Returns
the entry pointer found or a nullptr.
Definition at line 382 of file dictionary.C.
Referenced by Foam::getVariable(), Foam::getVariableOrDie(), and Foam::blockMeshTools::read().
Foam::dictionary * findDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Find and return a sub-dictionary pointer if present.
(and a sub-dictionary) otherwise return nullptr.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 496 of file dictionary.C.
Referenced by laminarModel< BasicTurbulenceModel >::New(), and lumpedPointMovement::readDict().
const Foam::dictionary * findDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a sub-dictionary pointer if present.
(and a sub-dictionary) otherwise return nullptr.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 506 of file dictionary.C.
References Foam::search().
const Foam::entry & lookupEntry (const word & keyword, enum keyType::option matchOpt) const
Search for an entry (const access) with the given keyword.
Parameters
matchOpt the default search is non-recursive with patterns
Returns
return an entry if present, otherwise FatalIOError.
Definition at line 392 of file dictionary.C.
Referenced by dimensionSet::dimensionSet().
Foam::ITstream & lookup (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Find and return an entry data stream. FatalIOError if not found, or if the number of tokens is incorrect.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 412 of file dictionary.C.
Referenced by Pa::clone(), Ra::clone(), coalCloudList::coalCloudList(), fieldSelection::containsPattern(), multiDirRefinement::multiDirRefinement(), multivariateSelectionScheme< Type >::multivariateSelectionScheme(), reactionRateFlameArea::New(), multivariateIndependentScheme< Type >::operator()(), Polynomial< Type >::Polynomial(), mappedPatchBase::readListOrField(), exprDriver::readTable(), refinementParameters::refinementParameters(), equationInitialResidualCondition::setResidual(), and Table< Type >::Table().
T get (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a T. FatalIOError if not found, or if the number of tokens is incorrect.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 74 of file dictionaryTemplates.C.
References set().
Referenced by SIMPLEControl::checkMeanSolution(), DAC< CompType, ThermoType >::DAC(), FreeStream< CloudType >::FreeStream(), Foam::MULES::limiterCorr(), multiDirRefinement::multiDirRefinement(), decompositionMethod::nDomains(), blendingMethod::New(), scatterModel::New(), wallTransmissivityModel::New(), wallAbsorptionEmissionModel::New(), conductivityModel::New(), granularPressureModel::New(), radialModel::New(), diameterModel::New(), windowModel::New(), partitioningModel::New(), saturationModel::New(), viscosityModel::New(), tetherPotential::New(), frictionalStressModel::New(), departureDiameterModel::New(), filmBoilingModel::New(), LeidenfrostModel::New(), departureFrequencyModel::New(), nucleationSiteModel::New(), MHFModel::New(), TDNBModel::New(), aspectRatioModel::New(), swarmCorrection::New(), CHFModel::New(), CHFSubCoolModel::New(), absorptionEmissionModel::New(), energyScalingFunction::New(), trimModel::New(), massTransferModel::New(), phaseTransferModel::New(), DispersionModel< CloudType >::New(), liftModel::New(), engineMesh::New(), interfaceCompositionModel::New(), surfaceTensionModel::New(), wallDampingModel::New(), filmThermoModel::New(), filmRadiationModel::New(), WallModel< CloudType >::New(), heatTransferModel::New(), virtualMassModel::New(), BinaryCollisionModel< CloudType >::New(), turbulentDispersionModel::New(), WallInteractionModel< CloudType >::New(), AtomizationModel< CloudType >::New(), filmTurbulenceModel::New(), InflowBoundaryModel< CloudType >::New(), barotropicCompressibilityModel::New(), basicSolidChemistryModel::New(), pairPotential::New(), sixDoFRigidBodyMotionRestraint::New(), wallLubricationModel::New(), filmViscosityModel::New(), laminarFlameSpeed::New(), heatTransferCoeffModel::New(), solidBodyMotionFunction::New(), HeatTransferModel< CloudType >::New(), CollisionModel< CloudType >::New(), DevolatilisationModel< CloudType >::New(), dragModel::New(), integrationScheme::New(), IsotropyModel< CloudType >::New(), StochasticCollisionModel< CloudType >::New(), SurfaceReactionModel< CloudType >::New(), DampingModel< CloudType >::New(), phaseModel::New(), phaseChangeModel::New(), chemistryReductionMethod< CompType, ThermoType >::New(), BreakupModel< CloudType >::New(), twoPhaseSystem::New(), sixDoFRigidBodyMotionConstraint::New(), PairModel< CloudType >::New(), extrudeModel::New(), CompositionModel< CloudType >::New(), PackingModel< CloudType >::New(), regionModelFunctionObject::New(), HeterogeneousReactingModel< CloudType >::New(), distributionModel::New(), laminarModel< BasicTurbulenceModel >::New(), AveragingMethod< Type >::New(), polyMeshModifier::New(), SRFModel::New(), restraint::New(), runTimeCondition::New(), optMeshMovement::New(), fieldValue::New(), rigidBodySolver::New(), RASModel< BasicTurbulenceModel >::New(), PhaseChangeModel< CloudType >::New(), PatchInteractionModel< CloudType >::New(), dynamicFvMesh::New(), multiphaseSystem::New(), LESModel< BasicTurbulenceModel >::New(), ODESolver::New(), pyrolysisModel::New(), cellZone::New(), sixDoFSolver::New(), pointZone::New(), SurfaceFilmModel< CloudType >::New(), updateMethod::New(), LduMatrix< Type, DType, LUType >::solver::New(), porosityModel::New(), faPatch::New(), waveModel::New(), Reaction< ReactionThermo >::New(), faceZone::New(), InjectionModel< CloudType >::New(), noiseModel::New(), LduMatrix< Type, DType, LUType >::smoother::New(), LduMatrix< Type, DType, LUType >::preconditioner::New(), pressureControl::pressureControl(), exprDriver::readExpression(), IOobject::readHeader(), exprDriver::readTable(), searchableSurfaces::searchableSurfaces(), kEpsilonLopesdaCosta< BasicTurbulenceModel >::setPorosityCoefficient(), and Foam::setRefCell().
T getOrDefault (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 115 of file dictionaryTemplates.C.
Referenced by engineTime::New(), and thermalBaffleModel::New().
T getOrAdd (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 155 of file dictionaryTemplates.C.
bool readEntry (const word & keyword, T & val, enum keyType::option matchOpt = keyType::REGEX, bool mandatory = true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
Parameters
val the value to read into
matchOpt the default search is non-recursive with patterns
mandatory the keyword is mandatory (default: true)
Returns
true if the entry was found.
Definition at line 307 of file dictionaryTemplates.C.
Referenced by coordinateSystem::assign(), cellModel::cellModel(), ETAB< CloudType >::ETAB(), geometrySurface::geometrySurface(), InflationInjection< CloudType >::InflationInjection(), mappedPatchBase::mappedPatchBase(), surfaceFilmModel::New(), Function1< Type >::New(), radiationModel::New(), Foam::operator<<(), pressureControl::pressureControl(), thermo::read(), thermalBaffle::read(), sixDoFRigidBodyMotion::read(), lumpedPointMovement::readDict(), ReitzDiwakar< CloudType >::ReitzDiwakar(), ReitzKHRT< CloudType >::ReitzKHRT(), Foam::setRefCell(), thermalBaffle::solveEnergy(), and TableFile< Type >::TableFile().
bool readIfPresent (const word & keyword, T & val, enum keyType::option matchOpt = keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
Default search: non-recursive with patterns.
Parameters
val the value to read into
matchOpt the default search is non-recursive with patterns
Returns
true if the entry was found.
Definition at line 410 of file dictionaryTemplates.C.
Referenced by coordinateSystem::assign(), averageCondition::calc(), cloudSolution::cloudSolution(), demandDrivenEntry< Type >::demandDrivenEntry(), distributedTriSurfaceMesh::distributedTriSurfaceMesh(), DRGEP< CompType, ThermoType >::DRGEP(), subModelBase::getBaseProperty(), functionObjectBase::getFileName(), mappedPatchBase::mappedPatchBase(), sootModel::New(), dlLibraryTable::open(), patchIdentifier::patchIdentifier(), plenumPressureFvPatchScalarField::plenumPressureFvPatchScalarField(), fvExprDriver::prepareData(), Foam::preservePatchTypes(), pressureControl::pressureControl(), STARCDMeshReader::readBoundary(), LduMatrix< Type, DType, LUType >::solver::readControl(), lumpedPointMovement::readDict(), IOobject::readHeader(), refinementParameters::refinementParameters(), data::setSolverPerformance(), surfaceWriter::surfaceWriter(), surfZoneIdentifier::surfZoneIdentifier(), updateMethod::updateMethod(), thermophysicalProperties::writeData(), x3dWriter::x3dWriter(), fvMotionSolverEngineMesh::~fvMotionSolverEngineMesh(), and layeredEngineMesh::~layeredEngineMesh().
T getCheck (const word & keyword, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a T with additional checking FatalIOError if not found, or if the number of tokens is incorrect.
Parameters
pred the value check predicate
matchOpt the default search is non-recursive with patterns
Definition at line 87 of file dictionaryTemplates.C.
T getCheckOrDefault (const word & keyword, const T & deflt, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
Parameters
pred the value check predicate
matchOpt the default search is non-recursive with patterns
Definition at line 196 of file dictionaryTemplates.C.
T getCheckOrAdd (const word & keyword, const T & deflt, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX)
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
Parameters
pred the value check predicate
matchOpt the default search is non-recursive with patterns
Definition at line 251 of file dictionaryTemplates.C.
bool readCheck (const word & keyword, T & val, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX, bool mandatory = true) const
Find entry and assign to T val. FatalIOError if it is found and the number of tokens is incorrect, or it is mandatory and not found.
Parameters
val the value to read into
pred the value check predicate
matchOpt the default search is non-recursive with patterns
mandatory the keyword is mandatory
Returns
true if the entry was found.
Definition at line 339 of file dictionaryTemplates.C.
bool readCheckIfPresent (const word & keyword, T & val, const Predicate & pred, enum keyType::option matchOpt = keyType::REGEX) const
Find an entry if present, and assign to T val. FatalIOError if it is found and the number of tokens is incorrect.
Default search: non-recursive with patterns.
Parameters
val the value to read into
pred the value check predicate
matchOpt the default search is non-recursive with patterns
Returns
true if the entry was found.
Definition at line 423 of file dictionaryTemplates.C.
bool isDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Check if entry is found and is a sub-dictionary.
Parameters
matchOpt the default search is non-recursive with patterns
Returns
true if the entry was found.
Definition at line 486 of file dictionary.C.
Referenced by liquidMixtureProperties::liquidMixtureProperties(), basicChemistryModel::New(), surfaceTensionModel::New(), and solidMixtureProperties::solidMixtureProperties().
const Foam::dictionary & subDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a sub-dictionary.
Fatal if the entry does not exist or is not a sub-dictionary.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 516 of file dictionary.C.
Referenced by averageCondition::calc(), phaseModel::clone(), cylindrical::cylindrical(), DAC< CompType, ThermoType >::DAC(), DRG< CompType, ThermoType >::DRG(), DRGEP< CompType, ThermoType >::DRGEP(), subModelBase::getBaseProperty(), cloudSolution::integrationSchemes(), cloudSolution::interpolationSchemes(), ISAT< CompType, ThermoType >::ISAT(), liquidMixtureProperties::liquidMixtureProperties(), Foam::listSwitches(), basicChemistryModel::New(), windowModel::New(), chemistryTabulationMethod< CompType, ThermoType >::New(), basicSolidChemistryModel::New(), phaseModel::New(), chemistryReductionMethod< CompType, ThermoType >::New(), regionModelFunctionObject::New(), RASModel< BasicTurbulenceModel >::New(), LESModel< BasicTurbulenceModel >::New(), waveModel::New(), noiseModel::New(), NonRandomTwoLiquid< Thermo, OtherThermo >::NonRandomTwoLiquid(), PFA< CompType, ThermoType >::PFA(), Foam::preservePatchTypes(), solverControl::printMaxMags(), profileModelList::profileModelList(), pyrolysisModelCollection::pyrolysisModelCollection(), Raoult< Thermo, OtherThermo >::Raoult(), thermo::read(), PDRblock::read(), lumpedPointMovement::readDict(), searchableSurfaces::searchableSurfaces(), surfaceTensionModel::sigmaDict(), solidMixtureProperties::solidMixtureProperties(), and cloudSolution::transient().
Foam::dictionary & subDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Find and return a sub-dictionary for manipulation.
Fatal if the entry does not exist or is not a sub-dictionary.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 536 of file dictionary.C.
Foam::dictionary & subDictOrAdd (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Find and return a sub-dictionary for manipulation.
Fatal if the entry exist and is not a sub-dictionary.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 556 of file dictionary.C.
Foam::dictionary subOrEmptyDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX, const bool mandatory = false) const
Find and return a sub-dictionary as a copy, otherwise return an empty dictionary.
Warn if the entry exists but is not a sub-dictionary.
Parameters
matchOpt the default search is non-recursive with patterns
mandatory the keyword is mandatory (default: false)
Definition at line 596 of file dictionary.C.
Referenced by adjointMeshMovementSolver::accumulateIntegrand(), adjointEikonalSolver::accumulateIntegrand(), cloudSolution::cloudSolution(), distributionModel::New(), sensitivityBezierFI::read(), and lumpedPointMovement::readDict().
const Foam::dictionary & optionalSubDict (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a sub-dictionary, otherwise return this dictionary.
Warn if the entry exists but is not a sub-dictionary.
Search type: non-recursive with patterns.
Definition at line 633 of file dictionary.C.
Referenced by lineSearch::lineSearch(), diameterModel::New(), Function1< Type >::New(), PatchFunction1< Type >::New(), stepUpdate::stepUpdate(), and solidBodyMotionFunction::writeData().
Foam::wordList toc () const
Return the table of contents.
Definition at line 658 of file dictionary.C.
Referenced by DAC< CompType, ThermoType >::DAC(), FreeStream< CloudType >::FreeStream(), liquidMixtureProperties::liquidMixtureProperties(), Foam::listSwitches(), profileModelList::profileModelList(), pyrolysisModelCollection::pyrolysisModelCollection(), and solidMixtureProperties::solidMixtureProperties().
Foam::wordList sortedToc () const
Return the sorted table of contents.
Definition at line 672 of file dictionary.C.
wordList sortedToc (const Compare & comp) const
Return table of contents sorted using the specified comparator.
Foam::List< Foam::keyType > keys (bool patterns = false) const
Return the list of available keys or patterns.
Definition at line 678 of file dictionary.C.
bool substituteKeyword (const word & keyword, bool mergeEntry = false)
Substitute the given keyword (which is prefixed by '$')
with the corresponding sub-dictionary entries
Definition at line 422 of file dictionary.C.
bool substituteScopedKeyword (const word & keyword, bool mergeEntry = false)
Substitute the given scoped keyword (which is prefixed by '$')
with the corresponding sub-dictionary entries
Definition at line 454 of file dictionary.C.
Foam::entry * add (entry * entryPtr, bool mergeEntry = false)
Add a new entry.
Parameters
mergeEntry dictionaries are interwoven and primitive entries are overwritten
Returns
pointer to inserted entry, or place of merging or nullptr on failure
Definition at line 696 of file dictionary.C.
Referenced by Foam::getOrAdd(), Foam::preservePatchTypes(), rigidBodyModelState::write(), sixDoFRigidBodyMotionState::write(), and surfaceFeatures::writeDict().
Foam::entry * add (const entry & e, bool mergeEntry = false)
Add an entry.
Parameters
mergeEntry dictionaries are interwoven and primitive entries are overwritten
Returns
pointer to inserted entry, or place of merging or nullptr on failure
Definition at line 774 of file dictionary.C.
Foam::entry * add (const keyType & k, const word & v, bool overwrite = false)
Add a word entry.
Parameters
overwrite force overwrite of an existing entry.
Returns
pointer to inserted entry or nullptr on failure
Definition at line 781 of file dictionary.C.
References Foam::add(), and entry::clone().
Foam::entry * add (const keyType & k, const string & v, bool overwrite = false)
Add a string entry.
Parameters
overwrite force overwrite of an existing entry.
Returns
pointer to inserted entry or nullptr on failure
Definition at line 792 of file dictionary.C.
References Foam::add().
Foam::entry * add (const keyType & k, const label v, bool overwrite = false)
Add a label entry.
Parameters
overwrite force overwrite of an existing entry.
Returns
pointer to inserted entry or nullptr on failure
Definition at line 803 of file dictionary.C.
References Foam::add().
Foam::entry * add (const keyType & k, const scalar v, bool overwrite = false)
Add a scalar entry.
Parameters
overwrite force overwrite of an existing entry.
Returns
pointer to inserted entry or nullptr on failure
Definition at line 814 of file dictionary.C.
References Foam::add().
Foam::entry * add (const keyType & k, const dictionary & d, bool mergeEntry = false)
Add a dictionary entry.
Parameters
mergeEntry merge into an existing sub-dictionary
Returns
pointer to inserted entry, or place of merging or nullptr on failure
Definition at line 825 of file dictionary.C.
References Foam::add().
entry* add (const keyType & k, const T & v, bool overwrite = false)
Add a T entry.
Parameters
overwrite force overwrite of existing entry
Returns
pointer to inserted entry or nullptr on failure
Foam::entry * set (entry * entryPtr)
Assign a new entry, overwriting any existing entry.
Returns
pointer to inserted entry or nullptr on failure
Definition at line 835 of file dictionary.C.
References Foam::add().
Referenced by averageCondition::calc().
Foam::entry * set (const entry & e)
Assign a new entry, overwriting any existing entry.
Returns
pointer to inserted entry or nullptr on failure
Definition at line 855 of file dictionary.C.
Foam::entry * set (const keyType & k, const dictionary & v)
Assign a dictionary entry, overwriting any existing entry.
Returns
pointer to inserted entry or nullptr on failure
Definition at line 861 of file dictionary.C.
References entry::clone(), and set().
entry* set (const keyType & k, const T & v)
Assign a T entry, overwriting any existing entry.
Returns
pointer to inserted entry or nullptr on failure
bool remove (const word & keyword)
Remove an entry specified by keyword.
Definition at line 575 of file dictionarySearch.C.
bool changeKeyword (const keyType & oldKeyword, const keyType & newKeyword, bool overwrite = false)
Change the keyword for an entry,.
Parameters
overwrite force overwrite of an existing entry.
Definition at line 604 of file dictionarySearch.C.
bool merge (const dictionary & dict)
Merge entries from the given dictionary.
Also merge sub-dictionaries as required.
Definition at line 867 of file dictionary.C.
References set().
Referenced by Foam::listSwitches().
void clear ()
Clear the dictionary.
Definition at line 912 of file dictionary.C.
Referenced by data::setSolverPerformance().
void transfer (dictionary & dict)
Transfer the contents of the argument and annul the argument.
Definition at line 921 of file dictionary.C.
void checkITstream (const ITstream & is, const word & keyword) const
Check after reading if the input token stream has unconsumed tokens remaining or if there were no tokens in the first place.
Emits FatalIOError
Definition at line 251 of file dictionary.C.
bool read (Istream & is)
Read dictionary from Istream.
Definition at line 134 of file dictionaryIO.C.
Referenced by codeStream::execute().
bool read (Istream & is, bool keepHeader)
Read dictionary from Istream, optionally keeping the header.
Definition at line 70 of file dictionaryIO.C.
References autoPtr< T >::New().
void writeEntry (const keyType & keyword, Ostream & os) const
Write sub-dictionary with the keyword as its header.
Definition at line 157 of file dictionaryIO.C.
Referenced by Foam::operator<<().
void writeEntries (Ostream & os, const bool extraNewLine = false) const
Write dictionary entries.
Parameters
extraNewLine adds additional newline
between entries for "top-level" dictionaries
Definition at line 165 of file dictionaryIO.C.
References Ostream::beginBlock(), and Ostream::endBlock().
void write (Ostream & os, const bool subDict = true) const
Write dictionary, normally with sub-dictionary formatting.
Definition at line 191 of file dictionaryIO.C.
Referenced by fieldDictionary::writeData(), and surfaceFeatures::writeDict().
Foam::dictionary::const_searcher csearch (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Search dictionary for given keyword.
Default search: non-recursive with patterns.
Parameters
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 258 of file dictionarySearch.C.
Referenced by meshRefinement::subDict().
Foam::dictionary::const_searcher search (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const
Search dictionary for given keyword.
Default search: non-recursive with patterns.
Parameters
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 296 of file dictionarySearch.C.
Foam::dictionary::searcher search (const word & keyword, enum keyType::option matchOpt = keyType::REGEX)
Search dictionary for given keyword.
Default search: non-recursive with patterns.
Parameters
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 306 of file dictionarySearch.C.
Foam::dictionary::const_searcher csearchScoped (const word & keyword, enum keyType::option matchOpt) const
Search using scoping.
There are two types of scoping available:
dot-scoping, where a '.' is used to delineate the scope
slash-scoping, where a '/' is used to delineate the scope
For dot-scoping, a leading '^' traverses to the top-level dictionary, leading dots mean use the parent dictionary and an intermediate dot separates a sub-dictionary or sub-entry. However, since the use of dots is ambiguous ("a.b.c" could be an entry itself or represent a "bc" entry from dictionary "a" etc), the heuristic backtracks and attempts successively longer top-level entries until a suitable match is found.
For slash-scoping, semantics similar to directory structures are used. A leading '/' traverses to the top-level dictionary, a single leading or intermediate '.' references the current dictionary level. A '..' pair references the parent dictionary. Any doubled slashes are silently ignored. Since a slash is not a valid keyword character, there is no ambiguity between separator and content.
Parameters
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 318 of file dictionarySearch.C.
Foam::dictionary::const_searcher searchScoped (const word & keyword, enum keyType::option matchOpt) const
Search using dot or slash scoping.
Parameters
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 348 of file dictionarySearch.C.
Foam::dictionary::searcher searchScoped (const word & keyword, enum keyType::option matchOpt)
Search using dot or slash scoping.
Parameters
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 358 of file dictionarySearch.C.
const Foam::dictionary * cfindScopedDict (const fileName & dictPath) const
Locate a sub-dictionary using slash-scoping.
Returns
nullptr if the dictionary path does not exist
Definition at line 370 of file dictionarySearch.C.
const Foam::dictionary * findScopedDict (const fileName & dictPath) const
Locate a sub-dictionary using slash-scoping.
Returns
nullptr if the dictionary path does not exist
Definition at line 455 of file dictionarySearch.C.
Foam::dictionary * findScopedDict (const fileName & dictPath)
Locate a sub-dictionary using slash-scoping.
Returns
nullptr if the dictionary path does not exist
Definition at line 464 of file dictionarySearch.C.
Foam::dictionary * makeScopedDict (const fileName & dictPath)
Locate existing or create sub-dictionary using slash-scoping.
Returns
nullptr if the dictionary path could not be created
Definition at line 473 of file dictionarySearch.C.
Foam::dictionary::const_searcher csearchCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option matchOpt = keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used. Old version 1600=OpenFOAM-v3.0, 240=OpenFOAM-2.4.x, 170=OpenFOAM-1.7.x,...
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 44 of file dictionaryCompat.C.
Referenced by coordinateSystem::assign().
bool foundCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option matchOpt = keyType::REGEX) const
Search dictionary for given keyword and any compatibility names.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 92 of file dictionaryCompat.C.
const Foam::entry * findCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option matchOpt) const
Find and return an entry pointer if present, or return a nullptr, using any compatibility names if needed.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 103 of file dictionaryCompat.C.
const Foam::entry & lookupEntryCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option matchOpt) const
Find and return an entry if present, otherwise FatalIOError, using any compatibility names if needed.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 114 of file dictionaryCompat.C.
Foam::ITstream & lookupCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option matchOpt = keyType::REGEX) const
Find and return an entry data stream, using any compatibility names if needed.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 135 of file dictionaryCompat.C.
T getCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a T using any compatibility names if needed. FatalIOError if not found, or if there are excess tokens.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 101 of file dictionaryTemplates.C.
Referenced by basicChemistryModel::New().
T getOrDefaultCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) const
Find and return a T, or return the given default value using any compatibility names if needed.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 437 of file dictionaryTemplates.C.
bool readCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, T & val, enum keyType::option matchOpt = keyType::REGEX, bool mandatory = true) const
Find entry and assign to T val using any compatibility names if needed. FatalIOError if there are excess tokens.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
val the value to read
recursive search parent dictionaries
patternMatch use regular expressions
Returns
true if the entry was found.
Definition at line 377 of file dictionaryTemplates.C.
Referenced by CodedSource< Type >::read().
bool readIfPresentCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, T & val, enum keyType::option matchOpt = keyType::REGEX) const
Find an entry if present, and assign to T val using any compatibility names if needed. FatalIOError if it is found and there are excess tokens.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
val the value to read
recursive search parent dictionaries
patternMatch use regular expressions
Returns
true if the entry was found.
Definition at line 478 of file dictionaryTemplates.C.
void operator= (const dictionary & rhs)
Copy assignment.
Definition at line 936 of file dictionary.C.
Referenced by dictionary::dictionary().
void operator+= (const dictionary & rhs)
Include entries from the given dictionary.
Warn, but do not overwrite existing entries.
Definition at line 956 of file dictionary.C.
References Foam::add(), and entry::clone().
void operator|= (const dictionary & rhs)
Conditionally include entries from the given dictionary.
Do not overwrite existing entries.
Definition at line 973 of file dictionary.C.
References Foam::add(), and entry::clone().
void operator<<= (const dictionary & rhs)
Unconditionally include entries from the given dictionary.
Overwrite existing entries.
Definition at line 993 of file dictionary.C.
References Foam::add(), and entry::clone().
T lookupOrDefault (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) const inline
Find and return a T, or return the given default value. FatalIOError if it is found and the number of tokens is incorrect.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 1593 of file dictionary.H.
Referenced by adjointEikonalSolver::computeYPhi(), SIMPLEControlOpt::criteriaSatisfied(), cylindrical::cylindrical(), fixedMeanFvPatchField< Type >::fixedMeanFvPatchField(), VTKsurfaceFormatCore::formatOptions(), VTPsurfaceFormatCore::formatOptions(), Foam::MULES::limiter(), Foam::MULES::limiterCorr(), tableReader< Type >::New(), chemistryReader< ThermoType >::New(), noSlipFvPatchVectorField::noSlipFvPatchVectorField(), sensitivityBezierFI::read(), rigidBodyMotion::read(), PDRblock::read(), sixDoFRigidBodyMotion::read(), searchableSurfaces::searchableSurfaces(), smoothSolver::solve(), and zoneMotion::zoneMotion().
T lookupOrAddDefault (const word & keyword, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) inline
Find and return a T, or return the given default value and add it to dictionary. FatalIOError if it is found and the number of tokens is incorrect.
Parameters
matchOpt the default search is non-recursive with patterns
Definition at line 1613 of file dictionary.H.
T lookupOrDefaultCompat (const word & keyword, std::initializer_list< std::pair< const char *, int >> compat, const T & deflt, enum keyType::option matchOpt = keyType::REGEX) const inline
Find and return a T, or return the given default value using any compatibility names if needed.
Default search: non-recursive with patterns.
Parameters
compat list of old compatibility keywords and the last OpenFOAM version for which they were used.
recursive search parent dictionaries
patternMatch use regular expressions
Definition at line 1635 of file dictionary.H.
ITstream& FOAM_DEPRECATED_FOR (2018- 07, "lookup() method") const inline
Deprecated(2018-07) find and return an entry data stream.
Deprecated:
(2018-07) - use lookup() method
Definition at line 1651 of file dictionary.H.
T FOAM_DEPRECATED_FOR (2018- 10, "get() method") const
Deprecated(2018-10) find and return a T.
Deprecated:
(2018-10) - use get() method
label getLabel (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< label >(const word&, keyType::option)
Definition at line 1884 of file dictionary.H.
scalar getScalar (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< scalar >(const word&, keyType::option)
Definition at line 1885 of file dictionary.H.
string getString (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< string >(const word&, keyType::option)
Definition at line 1886 of file dictionary.H.
word getWord (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< word >(const word&, keyType::option)
Definition at line 1887 of file dictionary.H.
Referenced by PatchFunction1< Type >::New().
fileName getFileName (const word & keyword, enum keyType::option matchOpt = keyType::REGEX) const inline
Same as get< fileName >(const word&, keyType::option)
Definition at line 1888 of file dictionary.H.
Foam::wordList sortedToc (const Compare & comp) const
Definition at line 52 of file dictionaryTemplates.C.
Foam::entry* add (const keyType & k, const T & v, bool overwrite)
Definition at line 59 of file dictionaryTemplates.C.
Foam::entry* set (const keyType & k, const T & v)
Definition at line 66 of file dictionaryTemplates.C.
References Foam::add().
Friends And Related Function Documentation
friend class entry friend
Declare friendship with the entry class for IO.
Definition at line 326 of file dictionary.H.
Istream& operator>> (Istream & is, dictionary & dict) friend
Read dictionary from Istream.
Ostream& operator<< (Ostream & os, const dictionary & dict) friend
Write dictionary to Ostream.
Member Data Documentation
friend const_searcher
Declare friendship with the searcher classes.
Definition at line 331 of file dictionary.H.
friend searcher
Definition at line 332 of file dictionary.H.
int writeOptionalEntries static
Report optional keywords and values if not present in dictionary.
For value greater than 1: fatal. Set/unset via an InfoSwitch
Definition at line 464 of file dictionary.H.
const Foam::dictionary null static
An empty dictionary, which is also the parent for all dictionaries.
Definition at line 469 of file dictionary.H.
Referenced by cellModel::cellModel(), primitiveEntry::primitiveEntry(), Stokes< BasicTurbulenceModel >::read(), dynamicCodeContext::setCodeContext(), and meshRefinement::subDict().
T bool recursive = false
Definition at line 1667 of file dictionary.H.
T bool bool patternMatch
Definition at line 1668 of file dictionary.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/db/dictionary/dictionary.H
src/OpenFOAM/db/dictionary/dictionary.C
src/OpenFOAM/db/dictionary/dictionaryCompat.C
src/OpenFOAM/db/dictionary/dictionaryIO.C
src/OpenFOAM/db/dictionary/dictionarySearch.C
src/OpenFOAM/db/dictionary/dictionaryTemplates.C