OpenFOAM: cellCuts Class Reference
cellCuts Class Reference
Description of cuts across cells.
Public Member Functions
ClassName ("cellCuts")
Runtime type information.
cellCuts (const polyMesh &mesh, const labelList &cutCells, const labelList &meshVerts, const labelList &meshEdges, const scalarField &meshEdgeWeights, const bool verbose=true)
Construct from cells to cut and pattern of cuts.
cellCuts (const polyMesh &mesh, const labelList &meshVerts, const labelList &meshEdges, const scalarField &meshEdgeWeights, const bool verbose=true)
Construct from pattern of cuts. Detect cells to cut.
cellCuts (const polyMesh &mesh, const labelList &cellLabels, const labelListList &cellLoops, const List< scalarField > &cellEdgeWeights, const bool verbose=true)
Construct from complete cellLoops through specified cells.
cellCuts (const polyMesh &mesh, const cellLooper &cellCutter, const List< refineCell > &refCells, const bool verbose=true)
Construct from list of cells to cut and direction to cut in.
cellCuts (const polyMesh &mesh, const cellLooper &cellCutter, const labelList &cellLabels, const List< plane > &cutPlanes, const bool verbose=true)
Construct from list of cells to cut and plane to cut with and.
cellCuts (const polyMesh &mesh, const boolList &pointIsCut, const boolList &edgeIsCut, const scalarField &edgeWeight, const Map< edge > &faceSplitCut, const labelListList &cellLoops, const label nLoops, const labelListList &cellAnchorPoints, const bool verbose=true)
Construct from components.
~cellCuts ()
Destructor.
void clearOut ()
Clear out demand driven storage.
const boolList & pointIsCut () const
Is mesh point cut.
const boolList & edgeIsCut () const
Is edge cut.
const scalarField & edgeWeight () const
If edge is cut gives weight (ratio between start() and end())
const labelListList & faceCuts () const
Cuts per existing face (includes those along edge of face)
const Map< edge > & faceSplitCut () const
Gives for split face the two cuts that split the face into two.
const labelListList & cellLoops () const
For each cut cell the cut along the circumference.
label nLoops () const
Number of valid cell loops.
const labelListList & cellAnchorPoints () const
For each cut cell the points on the 'anchor' side of the cell.
pointField loopPoints (const label celli) const
Returns coordinates of points on loop for given cell.
labelList nonAnchorPoints (const labelList &cellPoints, const labelList &anchorPoints, const labelList &loop) const
Invert anchor point selection.
void flip (const label celli)
Flip loop for celli. Updates anchor points as well.
void flipLoopOnly (const label celli)
Flip loop for celli. Does not update anchors. Use with care.
void writeOBJ (Ostream &os, const pointField &loopPoints, label &vertI) const
debugging:Write list of cuts to stream in OBJ format
void writeOBJ (Ostream &os) const
debugging:Write all of cuts to stream in OBJ format
void writeCellOBJ (const fileName &dir, const label celli) const
debugging:Write edges of cell and loop
Public Member Functions inherited from edgeVertex
edgeVertex (const polyMesh &mesh)
Construct from mesh.
const polyMesh & mesh () const
bool isEdge (const label eVert) const
label getEdge (const label eVert) const
label getVertex (const label eVert) const
label vertToEVert (const label vertI) const
label edgeToEVert (const label edgeI) const
point coord (const label cut, const scalar weight) const
label cutPairToEdge (const label cut0, const label cut1) const
Ostream & writeCut (Ostream &os, const label cut, const scalar) const
Write cut description to Ostream.
Ostream & writeCuts (Ostream &os, const labelList &, const scalarField &) const
Write cut descriptions to Ostream.
Additional Inherited Members
Static Public Member Functions inherited from edgeVertex
static void updateLabels (const labelList &map, List< refineCell > &)
Update refine list from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, Map< label > &)
Update map from map. Used to update cell/face labels.
static void updateLabels (const labelList &map, labelHashSet &)
Update map from map. Used to update cell/face labels.
static bool isEdge (const primitiveMesh &mesh, const label eVert)
Is eVert an edge?
static label getEdge (const primitiveMesh &mesh, const label eVert)
Convert eVert to edge label.
static label getVertex (const primitiveMesh &mesh, const label eVert)
Convert eVert to vertex label.
static label vertToEVert (const primitiveMesh &mesh, const label vertI)
Convert pointi to eVert.
static label edgeToEVert (const primitiveMesh &mesh, const label edgeI)
Convert edgeI to eVert.
static point coord (const primitiveMesh &, const label cut, const scalar weight)
Return coordinate of cut (uses weight if edgeCut)
static label cutPairToEdge (const primitiveMesh &, const label cut0, const label cut1)
Find mesh edge (or -1) between two cuts.
Detailed Description
Description of cuts across cells.
Description of cut is given as list of vertices and list of edges to be cut (and position on edge).
Does some checking of correctness/non-overlapping of cuts. 2x2x2 refinement has to be done in three passes since cuts can not overlap (would make addressing too complicated)
Introduces concept of 'cut' which is either an existing vertex or a edge.
Input can either be
list of cut vertices and list of cut edges. Constructs cell circumference walks ('cellLoops').
list of cell circumference walks. Will filter them so they don't overlap.
cellWalker and list of cells to refine (refineCell). Constructs cellLoops and does B. cellWalker is class which can cut a single cell using a plane through the cell centre and in a certain normal direction
CellCuts constructed from cellLoops (B, C) can have multiple cut-edges and/or cut-point as long as there is per face only one (or none) cut across a face, i.e. a face can only be split into two faces.
The information available after construction:
pointIsCut, edgeIsCut.
faceSplitCut : the cross-cut of a face.
cellLoops : the loop which cuts across a cell
cellAnchorPoints : per cell the vertices on one side which are considered the anchor points.
AnchorPoints: connected loops have to be oriented in the same way to be able to grow new internal faces out of the same bottom faces. (limitation of the mapping procedure). The loop is cellLoop is oriented such that the normal of it points towards the anchorPoints. This is the only routine which uses geometric information.
Limitations:
cut description is very precise. Hard to get right.
do anchor points need to be unique per cell? Very inefficient.
is orientation guaranteed to be correct? Uses geometric info so can go wrong on highly distorted meshes.
is memory inefficient. Probably need to use Maps instead of labelLists.
Source files
cellCuts.H
cellCuts.C
Definition at line 106 of file cellCuts.H.
Constructor & Destructor Documentation
cellCuts (const polyMesh & mesh, const labelList & cutCells, const labelList & meshVerts, const labelList & meshEdges, const scalarField & meshEdgeWeights, const bool verbose = true)
Construct from cells to cut and pattern of cuts.
Definition at line 2870 of file cellCuts.C.
References cellCuts::clearOut(), Foam::expressions::patchExpr::debug, Foam::endl(), and Foam::Pout.
cellCuts (const polyMesh & mesh, const labelList & meshVerts, const labelList & meshEdges, const scalarField & meshEdgeWeights, const bool verbose = true)
Construct from pattern of cuts. Detect cells to cut.
Definition at line 2915 of file cellCuts.C.
References cellCuts::clearOut(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::identity(), primitiveMesh::nCells(), and Foam::Pout.
cellCuts (const polyMesh & mesh, const labelList & cellLabels, const labelListList & cellLoops, const List< scalarField > & cellEdgeWeights, const bool verbose = true)
Construct from complete cellLoops through specified cells.
Checks for consistency. Constructs cut-cut addressing and cellAnchorPoints.
Definition at line 2964 of file cellCuts.C.
References cellCuts::clearOut(), Foam::expressions::patchExpr::debug, Foam::endl(), and Foam::Pout.
cellCuts (const polyMesh & mesh, const cellLooper & cellCutter, const List< refineCell > & refCells, const bool verbose = true)
Construct from list of cells to cut and direction to cut in.
(always through cell centre) and celllooper.
Definition at line 3012 of file cellCuts.C.
References cellCuts::clearOut(), Foam::expressions::patchExpr::debug, Foam::endl(), and Foam::Pout.
cellCuts (const polyMesh & mesh, const cellLooper & cellCutter, const labelList & cellLabels, const List< plane > & cutPlanes, const bool verbose = true)
Construct from list of cells to cut and plane to cut with and.
celllooper. (constructor above always cuts through cell centre)
Definition at line 3059 of file cellCuts.C.
References cellCuts::clearOut(), Foam::expressions::patchExpr::debug, Foam::endl(), and Foam::Pout.
cellCuts (const polyMesh & mesh, const boolList & pointIsCut, const boolList & edgeIsCut, const scalarField & edgeWeight, const Map< edge > & faceSplitCut, const labelListList & cellLoops, const label nLoops, const labelListList & cellAnchorPoints, const bool verbose = true)
Construct from components.
Definition at line 3109 of file cellCuts.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), and Foam::Pout.
~cellCuts ()
Destructor.
Definition at line 3141 of file cellCuts.C.
Member Function Documentation
ClassName ("cellCuts")
Runtime type information.
void clearOut ()
Clear out demand driven storage.
Definition at line 3147 of file cellCuts.C.
Referenced by cellCuts::cellCuts().
const boolList& pointIsCut () const inline
Is mesh point cut.
Definition at line 687 of file cellCuts.H.
const boolList& edgeIsCut () const inline
Is edge cut.
Definition at line 695 of file cellCuts.H.
const scalarField& edgeWeight () const inline
If edge is cut gives weight (ratio between start() and end())
Definition at line 703 of file cellCuts.H.
const labelListList& faceCuts () const inline
Cuts per existing face (includes those along edge of face)
Cuts in no particular order
Definition at line 713 of file cellCuts.H.
const Map<edge>& faceSplitCut () const inline
Gives for split face the two cuts that split the face into two.
Definition at line 725 of file cellCuts.H.
const labelListList& cellLoops () const inline
For each cut cell the cut along the circumference.
Definition at line 733 of file cellCuts.H.
label nLoops () const inline
Number of valid cell loops.
Definition at line 741 of file cellCuts.H.
const labelListList& cellAnchorPoints () const inline
For each cut cell the points on the 'anchor' side of the cell.
Definition at line 749 of file cellCuts.H.
Foam::pointField loopPoints (const label celli) const
Returns coordinates of points on loop for given cell.
Uses cellLoops_ and edgeWeight_
Definition at line 3155 of file cellCuts.C.
References forAll, and UList< T >::size().
Foam::labelList nonAnchorPoints (const labelList & cellPoints, const labelList & anchorPoints, const labelList & loop) const
Invert anchor point selection.
Definition at line 1328 of file cellCuts.C.
References forAll, UList< T >::found(), i, List< T >::setSize(), and UList< T >::size().
void flip (const label celli)
Flip loop for celli. Updates anchor points as well.
Definition at line 3180 of file cellCuts.C.
References mesh, and Foam::reverse().
void flipLoopOnly (const label celli)
Flip loop for celli. Does not update anchors. Use with care.
(only if you're sure loop orientation is wrong)
Definition at line 3197 of file cellCuts.C.
References Foam::reverse().
void writeOBJ (Ostream & os, const pointField & loopPoints, label & vertI) const
debugging:Write list of cuts to stream in OBJ format
Definition at line 3206 of file cellCuts.C.
References Foam::endl(), forAll, Vector< Cmpt >::x(), Vector< Cmpt >::y(), and Vector< Cmpt >::z().
void writeOBJ (Ostream & os) const
debugging:Write all of cuts to stream in OBJ format
Definition at line 3232 of file cellCuts.C.
References forAll, and Foam::meshTools::writeOBJ().
void writeCellOBJ (const fileName & dir, const label celli) const
debugging:Write edges of cell and loop
Definition at line 3246 of file cellCuts.C.
References Foam::meshTools::writeOBJ().
The documentation for this class was generated from the following files:
src/dynamicMesh/meshCut/cellCuts/cellCuts.H
src/dynamicMesh/meshCut/cellCuts/cellCuts.C