OpenFOAM: magnet Class Reference
magnet Class Reference
Class to hold the defining data for a permanent magnet, in particular the name, relative permeability and remanence.
Public Member Functions
magnet ()
Null constructor for lists.
magnet (const word &name, const scalar mur, const scalar Mr, const vector &orientation)
Construct from components.
magnet (Istream &is)
Construct from Istream.
const word & name () const
Return name.
scalar mur () const
Return relative permeability.
const dimensionedScalar & Mr () const
Return remenance.
const vector & orientation () const
Return orientation.
Friends
Istream & operator>> (Istream &is, magnet &m)
Ostream & operator<< (Ostream &os, const magnet &m)
Detailed Description
Class to hold the defining data for a permanent magnet, in particular the name, relative permeability and remanence.
Source files
magnet.H
Definition at line 55 of file magnet.H.
Constructor & Destructor Documentation
magnet () inline
Null constructor for lists.
Definition at line 71 of file magnet.H.
magnet (const word & name, const scalar mur, const scalar Mr, const vector & orientation) inline
Construct from components.
Definition at line 81 of file magnet.H.
magnet (Istream & is) inline
Construct from Istream.
Definition at line 97 of file magnet.H.
Member Function Documentation
const word& name () const inline
Return name.
Definition at line 111 of file magnet.H.
scalar mur () const inline
Return relative permeability.
Definition at line 119 of file magnet.H.
const dimensionedScalar& Mr () const inline
Return remenance.
Definition at line 127 of file magnet.H.
const vector& orientation () const inline
Return orientation.
Definition at line 135 of file magnet.H.
References Istream::readBegin(), Istream::readEnd(), and dimensioned< Type >::value().
Friends And Related Function Documentation
Istream& operator>> (Istream & is, magnet & m) friend
Definition at line 143 of file magnet.H.
Ostream& operator<< (Ostream & os, const magnet & m) friend
Definition at line 156 of file magnet.H.
The documentation for this class was generated from the following file:
applications/solvers/electromagnetics/magneticFoam/magnet.H