OpenFOAM: ConstPrecisionAdaptor< Type, InputType, Container > Class Template Reference
ConstPrecisionAdaptor< Type, InputType, Container > Class Template Reference
A const Field wrapper with possible data conversion.
Public Types
typedef Container< Type > FieldType
The adapted field type.
Public Types inherited from tmpNrc< Container< Type > >
typedef Container< Type > element_type
Type of object being managed.
typedef Container< Type > * pointer
Pointer to type of object being managed.
typedef Foam::refCount::zero refCount
Null reference counter class.
Public Member Functions
ConstPrecisionAdaptor (const Container< InputType > &input)
Construct from Container<InputType>, copying on input as required.
ConstPrecisionAdaptor (tmp< Container< InputType >> &&input)
Construct from tmp Container, copy/move as required.
ConstPrecisionAdaptor (const tmp< Container< InputType >> &input)
Construct from tmp Container, copy/move as required.
Public Member Functions inherited from tmpNrc< Container< Type > >
constexpr tmpNrc () noexcept
Construct with no managed pointer.
constexpr tmpNrc (std::nullptr_t) noexcept
Construct with no managed pointer.
tmpNrc (Container< Type > *p) noexcept
Construct, taking ownership of the pointer.
tmpNrc (const Container< Type > &obj) noexcept
Construct for a const reference to an object.
tmpNrc (tmpNrc< Container< Type > > &&t) noexcept
Move construct, transferring ownership.
tmpNrc (const tmpNrc< Container< Type > > &t)
Copy construct.
tmpNrc (const tmpNrc< Container< Type > > &t, bool reuse)
Copy construct. Optionally reusing pointer.
~tmpNrc ()
Destructor: deletes managed pointer.
bool isTmp () const noexcept
True if this is a managed pointer (not a const reference)
bool empty () const noexcept
True if this is a non-null managed pointer.
bool valid () const noexcept
True if this is a non-null managed pointer, or is a const object reference.
bool movable () const noexcept
True if this is a non-null managed pointer with a unique ref-count.
word typeName () const
Return type-name of the tmp, constructed from type-name of T.
Container< Type > * get () noexcept
Return pointer without nullptr checking.
const Container< Type > * get () const noexcept
Return const pointer without nullptr checking.
const Container< Type > & cref () const
Return the const object reference or a const reference to the contents of a non-null managed pointer.
void cref (const Container< Type > &obj) noexcept
Delete managed temporary object and set to const reference.
Container< Type > & ref () const
Return non-const reference to the contents of a non-null managed pointer.
Container< Type > & constCast () const
Non-const dereference, even if the object is const.
Container< Type > * ptr () const
Return managed pointer for reuse, or clone() the const object reference.
void clear () const noexcept
If object pointer points to valid object: delete object and set pointer to nullptr.
void reset () noexcept
Release ownership of managed temporary object.
void reset (Container< Type > *p) noexcept
Delete managed temporary object and set to new given pointer.
void reset (tmpNrc< Container< Type > > &&other) noexcept
Clear existing and transfer ownership.
void swap (tmpNrc< Container< Type > > &other) noexcept
Swaps the managed object with other.
const Container< Type > & operator() () const
Return const reference to the object.
operator const Container< Type > & () const
Cast to underlying data type, using the cref() method.
const Container< Type > * operator-> () const
Dereferences (const) pointer to the managed object.
Container< Type > * operator-> ()
Dereferences (non-const) pointer to the managed object.
operator bool () const noexcept
Is non-null managed pointer or const object reference : valid()
void operator= (Container< Type > *p)
Take ownership of the pointer.
void operator= (const tmpNrc< Container< Type > > &t)
Transfer ownership of the managed pointer.
void operator= (tmpNrc< Container< Type > > &&other) noexcept
Clear existing and transfer ownership.
void operator= (std::nullptr_t)=delete
No assignment from literal nullptr.
operator tmp< Container< Type > > ()
Conversion to tmp.
Static Public Member Functions
static const Container< Type > & get (const Container< InputType > &input, Container< Type > &dst)
Return the field.
Static Public Member Functions inherited from tmpNrc< Container< Type > >
static tmpNrc< Container< Type > > New (Args &&...args)
Construct tmpNrc of T with forwarding arguments.
static tmpNrc< Container< Type > > NewFrom (Args &&...args)
Construct tmpNrc from derived type with forwarding arguments.
Detailed Description
template<class Type, class InputType, template< class > class Container = Field>
class Foam::ConstPrecisionAdaptor< Type, InputType, Container >
A const Field wrapper with possible data conversion.
Definition at line 46 of file PrecisionAdaptor.H.
Member Typedef Documentation
typedef Container<Type> FieldType
The adapted field type.
Definition at line 96 of file PrecisionAdaptor.H.
Constructor & Destructor Documentation
ConstPrecisionAdaptor (const Container< InputType > & input) inline
Construct from Container<InputType>, copying on input as required.
Definition at line 104 of file PrecisionAdaptor.H.
References tmpNrc< Container< Type > >::cref(), and value().
ConstPrecisionAdaptor (tmp< Container< InputType >> && input) inline
Construct from tmp Container, copy/move as required.
Definition at line 122 of file PrecisionAdaptor.H.
ConstPrecisionAdaptor (const tmp< Container< InputType >> & input) inline
Construct from tmp Container, copy/move as required.
Definition at line 133 of file PrecisionAdaptor.H.
References value().
Member Function Documentation
static const Container<Type>& get (const Container< InputType > & input, Container< Type > & dst) inline static
Return the field.
Definition at line 147 of file PrecisionAdaptor.H.
The documentation for this class was generated from the following file:
src/OpenFOAM/fields/Fields/Field/PrecisionAdaptor/PrecisionAdaptor.H