OpenFOAM: sampledDistanceSurface Class Reference
sampledDistanceSurface Class Reference
A sampledSurface defined by a distance to a surface - using either an isoSurfaceCell or an isoSurface.
Public Member Functions
TypeName ("sampledDistanceSurface")
Runtime type information.
sampledDistanceSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
virtual ~sampledDistanceSurface ()=default
Destructor.
virtual bool needsUpdate () const
Does the surface need an update?
virtual bool expire ()
Mark the surface as needing an update.
virtual bool update ()
Update the surface as required.
virtual const pointField & points () const
Points of surface.
virtual const faceList & faces () const
Faces of surface.
virtual const labelList & zoneIds () const
Per-face zone/region information.
virtual const vectorField & Sf () const
Face area vectors.
virtual const scalarField & magSf () const
Face area magnitudes.
virtual const vectorField & Cf () const
Face centres.
virtual tmp< scalarField > sample (const interpolation< scalar > &sampler) const
Sample volume field onto surface faces.
virtual tmp< vectorField > sample (const interpolation< vector > &sampler) const
Sample volume field onto surface faces.
virtual tmp< sphericalTensorField > sample (const interpolation< sphericalTensor > &sampler) const
Sample volume field onto surface faces.
virtual tmp< symmTensorField > sample (const interpolation< symmTensor > &sampler) const
Sample volume field onto surface faces.
virtual tmp< tensorField > sample (const interpolation< tensor > &sampler) const
Sample volume field onto surface faces.
virtual tmp< scalarField > interpolate (const interpolation< scalar > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< vectorField > interpolate (const interpolation< vector > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< sphericalTensorField > interpolate (const interpolation< sphericalTensor > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< symmTensorField > interpolate (const interpolation< symmTensor > &interpolator) const
Interpolate volume field onto surface points.
virtual tmp< tensorField > interpolate (const interpolation< tensor > &interpolator) const
Interpolate volume field onto surface points.
virtual void print (Ostream &os) const
Print information.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler) const
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnPoints (const interpolation< Type > &interpolator) const
Public Member Functions inherited from sampledSurface
TypeName ("sampledSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, sampledSurface, word,(const word &name, const polyMesh &mesh, const dictionary &dict),(name, mesh, dict))
Declare run-time constructor selection table.
sampledSurface (const word &name, const polyMesh &mesh, const bool interpolate=false)
Construct from name, mesh.
sampledSurface (const word &name, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
autoPtr< sampledSurface > clone () const
Clone.
virtual ~sampledSurface ()
Destructor - calls clearGeom()
const polyMesh & mesh () const
Access to the underlying mesh.
const word & name () const
Name of surface.
bool enabled () const
Surface is enabled.
bool invariant () const
Surface is invariant with geometry change (caution)
bool interpolate () const
Interpolation to nodes requested for surface.
scalar area () const
The total surface area.
virtual bool hasFaceIds () const
If element ids/order of the original surface are available.
virtual const labelList & originalIds () const
List of element ids/order of the original surface, when hasFaceIds is true.
polySurface * getRegistrySurface (const objectRegistry &obr, word lookupName="") const
Get surface from registry if available.
polySurface * storeRegistrySurface (objectRegistry &obr, word lookupName="") const
Copy surface into registry.
bool removeRegistrySurface (objectRegistry &obr, word lookupName="") const
Remove surface from registry.
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
Copy/store sampled field onto registered surface (if it exists)
template<class Type , class GeoMeshType >
bool storeRegistryField (const objectRegistry &obr, const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
Move/store sampled field onto registered surface (if it exists)
surfMesh * getSurfMesh (word lookupName="") const
Get surface from registry if available.
surfMesh * storeSurfMesh (word lookupName="") const
Copy surface into registry.
bool removeSurfMesh (word lookupName="") const
Remove surface from registry.
template<class Type , class GeoMeshType >
bool storeSurfMeshField (const word &fieldName, const dimensionSet &dims, const Field< Type > &values, word lookupName="") const
Copy/store sampled Face field onto surfMesh (if it exists)
template<class Type , class GeoMeshType >
bool storeSurfMeshField (const word &fieldName, const dimensionSet &dims, Field< Type > &&values, word lookupName="") const
Move/store sampled Face field onto surfMesh (if it exists)
virtual bool withSurfaceFields () const
Can it sample surface-fields?
virtual tmp< scalarField > sample (const surfaceScalarField &sField) const
Sample surface field onto surface.
virtual tmp< vectorField > sample (const surfaceVectorField &sField) const
Sample surface field onto surface.
virtual tmp< sphericalTensorField > sample (const surfaceSphericalTensorField &sField) const
Sample surface field onto surface.
virtual tmp< symmTensorField > sample (const surfaceSymmTensorField &sField) const
Sample surface field onto surface.
virtual tmp< tensorField > sample (const surfaceTensorField &sField) const
Sample surface field onto surface.
virtual void rename (const word &newName)
Rename.
template<class Type >
Foam::tmp< Foam::Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts)
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld)
Public Member Functions inherited from meshedSurf
meshedSurf ()=default
Construct null.
virtual ~meshedSurf ()=default
Destructor.
Public Member Functions inherited from distanceSurface
TypeName ("distanceSurface")
Runtime type information.
distanceSurface (const word &defaultSurfaceName, const polyMesh &mesh, const dictionary &dict)
Construct from dictionary.
distanceSurface (const polyMesh &mesh, const bool interpolate, const word &surfaceType, const word &surfaceName, const scalar distance, const bool signedDistance, const isoSurfaceBase::algorithmType algo, const isoSurfaceBase::filterType filter, const boundBox &bounds=boundBox::invertedBox)
Construct from components.
virtual ~distanceSurface ()=default
Destructor.
void createGeometry ()
Create/recreate the distance surface.
const word & surfaceName () const
The name of the underlying searchableSurface.
scalar distance () const
The distance to the underlying searchableSurface.
const meshedSurface & surface () const
The underlying surface.
meshedSurface & surface ()
The underlying surface.
const labelList & meshCells () const
For each face, the original cell in mesh.
labelList & meshCells ()
For each face, the original cell in mesh.
template<class Type >
tmp< Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &cellValues, const Field< Type > &pointValues) const
Interpolate volume field onto surface points.
void print (Ostream &os) const
Print information.
template<class Type >
Foam::tmp< Foam::Field< Type > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &cellValues, const Field< Type > &pointValues) const
Additional Inherited Members
Static Public Member Functions inherited from sampledSurface
static autoPtr< sampledSurface > New (const word &name, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected surface.
Static Public Attributes inherited from sampledSurface
static const wordList surfaceFieldTypes
Class names for surface field types.
Protected Member Functions inherited from sampledSurface
virtual void clearGeom () const
Additional cleanup when clearing the geometry.
sampledSurface (const word &name, std::nullptr_t)
Construct null.
Static Protected Member Functions inherited from sampledSurface
template<class Type >
static tmp< Field< Type > > sampleOnFaces (const interpolation< Type > &sampler, const labelUList &elements, const faceList &fcs, const pointField &pts)
General loop for sampling elements to faces.
template<class Type >
static tmp< GeometricField
< Type, fvPatchField, volMesh > > pointAverage (const GeometricField< Type, pointPatchField, pointMesh > &pfld)
Create cell values by averaging the point values.
Detailed Description
A sampledSurface defined by a distance to a surface - using either an isoSurfaceCell or an isoSurface.
This is often embedded as part of a sampled surfaces function object.
Usage
Example of function object partial specification:
surfaces
(
    surface1
    {
        type        distanceSurface;
    }
);
Where the sub-entries comprise:
Property Description Required Default
type distanceSurface yes
distance Distance from surface yes
signed Use sign when distance is positive partly
isoAlgorithm (cell/topo/point) no cell
regularise Point snapping for iso-surface no true
average Cell values from averaged point values no false
bounds Limit with bounding box no
surfaceType Type of surface yes
surfaceName Name of surface in triSurface/ no dict name
Note
For compatibility, the keyword 'cell' (as a bool) is accepted
Source files
sampledDistanceSurface.H
sampledDistanceSurface.C
Definition at line 129 of file sampledDistanceSurface.H.
Constructor & Destructor Documentation
sampledDistanceSurface (const word & name, const polyMesh & mesh, const dictionary & dict)
Construct from dictionary.
Definition at line 47 of file sampledDistanceSurface.C.
virtual ~sampledDistanceSurface () virtual default
Destructor.
Member Function Documentation
TypeName ("sampledDistanceSurface")
Runtime type information.
bool needsUpdate () const virtual
Does the surface need an update?
Implements sampledSurface.
Definition at line 62 of file sampledDistanceSurface.C.
bool expire () virtual
Mark the surface as needing an update.
May also free up unneeded data. Return false if surface was already marked as expired.
Implements sampledSurface.
Definition at line 68 of file sampledDistanceSurface.C.
bool update () virtual
Update the surface as required.
Do nothing (and return false) if no update was needed
Implements sampledSurface.
Definition at line 90 of file sampledDistanceSurface.C.
virtual const pointField& points () const inline virtual
Points of surface.
Implements sampledSurface.
Definition at line 220 of file sampledDistanceSurface.H.
Referenced by sampledDistanceSurface::sampleOnFaces().
virtual const faceList& faces () const inline virtual
Faces of surface.
Implements sampledSurface.
Definition at line 228 of file sampledDistanceSurface.H.
Referenced by sampledDistanceSurface::sampleOnFaces().
virtual const labelList& zoneIds () const inline virtual
Per-face zone/region information.
Reimplemented from meshedSurf.
Definition at line 236 of file sampledDistanceSurface.H.
virtual const vectorField& Sf () const inline virtual
Face area vectors.
Implements sampledSurface.
Definition at line 244 of file sampledDistanceSurface.H.
virtual const scalarField& magSf () const inline virtual
Face area magnitudes.
Implements sampledSurface.
Definition at line 252 of file sampledDistanceSurface.H.
virtual const vectorField& Cf () const inline virtual
Face centres.
Implements sampledSurface.
Definition at line 260 of file sampledDistanceSurface.H.
Foam::tmp< Foam::scalarField > sample (const interpolation< scalar > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 111 of file sampledDistanceSurface.C.
Foam::tmp< Foam::vectorField > sample (const interpolation< vector > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 120 of file sampledDistanceSurface.C.
Foam::tmp< Foam::sphericalTensorField > sample (const interpolation< sphericalTensor > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 129 of file sampledDistanceSurface.C.
Foam::tmp< Foam::symmTensorField > sample (const interpolation< symmTensor > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 138 of file sampledDistanceSurface.C.
Foam::tmp< Foam::tensorField > sample (const interpolation< tensor > & sampler) const virtual
Sample volume field onto surface faces.
Implements sampledSurface.
Definition at line 147 of file sampledDistanceSurface.C.
Foam::tmp< Foam::scalarField > interpolate (const interpolation< scalar > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 156 of file sampledDistanceSurface.C.
Foam::tmp< Foam::vectorField > interpolate (const interpolation< vector > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 165 of file sampledDistanceSurface.C.
Foam::tmp< Foam::sphericalTensorField > interpolate (const interpolation< sphericalTensor > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 173 of file sampledDistanceSurface.C.
Foam::tmp< Foam::symmTensorField > interpolate (const interpolation< symmTensor > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 182 of file sampledDistanceSurface.C.
Foam::tmp< Foam::tensorField > interpolate (const interpolation< tensor > & interpolator) const virtual
Interpolate volume field onto surface points.
Implements sampledSurface.
Definition at line 191 of file sampledDistanceSurface.C.
void print (Ostream & os) const virtual
Print information.
Reimplemented from sampledSurface.
Definition at line 199 of file sampledDistanceSurface.C.
Foam::tmp<Foam::Field<Type> > sampleOnFaces (const interpolation< Type > & sampler) const
Definition at line 32 of file sampledDistanceSurfaceTemplates.C.
References sampledDistanceSurface::faces(), distanceSurface::meshCells(), sampledDistanceSurface::points(), and sampledSurface::sampleOnFaces().
Foam::tmp<Foam::Field<Type> > sampleOnPoints (const interpolation< Type > & interpolator) const
Definition at line 49 of file sampledDistanceSurfaceTemplates.C.
The documentation for this class was generated from the following files:
src/sampling/sampledSurface/distanceSurface/sampledDistanceSurface.H
src/sampling/sampledSurface/distanceSurface/sampledDistanceSurface.C
src/sampling/sampledSurface/distanceSurface/sampledDistanceSurfaceTemplates.C