OpenFOAM: laplaceFilter Class Reference
laplaceFilter Class Reference
Laplace filter for LES.
Public Member Functions
TypeName ("laplace")
Runtime type information.
laplaceFilter (const fvMesh &mesh, scalar widthCoeff)
Construct from components.
laplaceFilter (const fvMesh &mesh, const dictionary &)
Construct from IOdictionary.
virtual ~laplaceFilter ()=default
Destructor.
virtual void read (const dictionary &)
Read the LESfilter dictionary.
virtual tmp< volScalarField > operator() (const tmp< volScalarField > &) const
virtual tmp< volVectorField > operator() (const tmp< volVectorField > &) const
virtual tmp< volSymmTensorField > operator() (const tmp< volSymmTensorField > &) const
virtual tmp< volTensorField > operator() (const tmp< volTensorField > &) const
Public Member Functions inherited from LESfilter
TypeName ("LESfilter")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, LESfilter, dictionary,(const fvMesh &mesh, const dictionary &LESfilterDict),(mesh, LESfilterDict))
LESfilter (const fvMesh &mesh)
Construct from components.
virtual ~LESfilter ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
Additional Inherited Members
Static Public Member Functions inherited from LESfilter
static autoPtr< LESfilter > New (const fvMesh &, const dictionary &, const word &filterDictName="filter")
Return a reference to the selected LES filter.
Protected Member Functions inherited from LESfilter
template<class GeoFieldType >
void correctBoundaryConditions (const tmp< GeoFieldType > &tgf) const
Temporary function to ensure the coupled boundary conditions of the.
Detailed Description
Laplace filter for LES.
Kernel                 as filter          as Test filter with ratio 2
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Box filter:            g = delta2/24  ->  g = delta2/6
Spherical box filter:  g = delta2/64  ->  g = delta2/16
Gaussian filter:       g = delta2/24  ->  g = delta2/6
Source files
laplaceFilter.H
laplaceFilter.C
Definition at line 54 of file laplaceFilter.H.
Constructor & Destructor Documentation
laplaceFilter (const fvMesh & mesh, scalar widthCoeff)
Construct from components.
Definition at line 38 of file laplaceFilter.C.
laplaceFilter (const fvMesh & mesh, const dictionary & bd)
Construct from IOdictionary.
Definition at line 59 of file laplaceFilter.C.
References Foam::pow(), GeometricField< Type, PatchField, GeoMesh >::ref(), and fvMesh::V().
virtual ~laplaceFilter () virtual default
Destructor.
Member Function Documentation
TypeName ("laplace")
Runtime type information.
void read (const dictionary & bd) virtual
Read the LESfilter dictionary.
Implements LESfilter.
Definition at line 85 of file laplaceFilter.C.
References Foam::pow(), and fvMesh::V().
Foam::tmp< Foam::volScalarField > operator() (const tmp< volScalarField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 94 of file laplaceFilter.C.
Foam::tmp< Foam::volVectorField > operator() (const tmp< volVectorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 110 of file laplaceFilter.C.
Foam::tmp< Foam::volSymmTensorField > operator() (const tmp< volSymmTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 126 of file laplaceFilter.C.
Foam::tmp< Foam::volTensorField > operator() (const tmp< volTensorField > & unFilteredField) const virtual
Implements LESfilter.
Definition at line 142 of file laplaceFilter.C.
The documentation for this class was generated from the following files:
src/TurbulenceModels/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.H
src/TurbulenceModels/turbulenceModels/LES/LESfilters/laplaceFilter/laplaceFilter.C