OpenFOAM: forceSuSp Class Reference
forceSuSp Class Reference
Helper container for force Su and Sp terms.
Public Member Functions
forceSuSp ()
Construct null.
forceSuSp (const zero)
Construct zero-initialized content.
forceSuSp (const Tuple2< vector, scalar > &susp)
Construct given Tuple2.
forceSuSp (const vector &Su, const scalar Sp)
Construct given two components.
forceSuSp (Istream &is)
Construct from Istream.
const vector & Su () const
Return const access to the explicit contribution [kg.m/s2].
scalar Sp () const
Return const access to the implicit coefficient [kg/s].
vector & Su ()
Return reference to the explicit contribution.
scalar & Sp ()
Return reference to the implicit coefficient.
void operator= (const forceSuSp &susp)
Assignment.
void operator+= (const forceSuSp &susp)
Addition.
void operator-= (const forceSuSp &susp)
Subtraction.
Public Member Functions inherited from Tuple2< vector, scalar >
Tuple2 ()=default
Construct null.
Tuple2 (const vector &f, const scalar &s)
Copy construct from components.
Tuple2 (vector &&f, scalar &&s)
Move construct from components.
Tuple2 (const std::pair< vector, scalar > &vals)
Copy construct from std::pair.
Tuple2 (std::pair< vector, scalar > &&vals)
Move construct from std::pair.
Tuple2 (Istream &is)
Construct from Istream.
const vector & first () const noexcept
Return first.
vector & first () noexcept
Return first.
const scalar & second () const noexcept
Return second.
scalar & second () noexcept
Return second.
Friends
forceSuSp operator* (const forceSuSp &susp1, const forceSuSp &susp2)
Addition.
forceSuSp operator* (const scalar s, const forceSuSp &susp)
Multiplication.
Additional Inherited Members
Public Types inherited from Tuple2< vector, scalar >
typedef vector first_type
Type of member first, the first template parameter (T1)
typedef scalar second_type
Type of member second, the second template parameter (T2)
Detailed Description
Helper container for force Su and Sp terms.
F = Sp(U - Up) + Su
Explicit contribution, Su specified as a force Implicit coefficient, Sp specified as force/velocity
Source files
forceSuSp.H
forceSuSpI.H
Definition at line 59 of file forceSuSp.H.
Constructor & Destructor Documentation
forceSuSp () inline
Construct null.
Definition at line 23 of file forceSuSpI.H.
forceSuSp (const zero) inline
Construct zero-initialized content.
Definition at line 27 of file forceSuSpI.H.
forceSuSp (const Tuple2< vector, scalar > & susp) inline
Construct given Tuple2.
Definition at line 34 of file forceSuSpI.H.
forceSuSp (const vector & Su, const scalar Sp) inline
Construct given two components.
Definition at line 42 of file forceSuSpI.H.
forceSuSp (Istream & is) inline
Construct from Istream.
Definition at line 49 of file forceSuSpI.H.
References Sp, and Su.
Member Function Documentation
const Foam::vector & Su () const inline
Return const access to the explicit contribution [kg.m/s2].
Definition at line 57 of file forceSuSpI.H.
Foam::scalar Sp () const inline
Return const access to the implicit coefficient [kg/s].
Definition at line 63 of file forceSuSpI.H.
Foam::vector & Su () inline
Return reference to the explicit contribution.
Definition at line 69 of file forceSuSpI.H.
Foam::scalar & Sp () inline
Return reference to the implicit coefficient.
Definition at line 75 of file forceSuSpI.H.
void operator= (const forceSuSp & susp) inline
Assignment.
Definition at line 83 of file forceSuSpI.H.
void operator+= (const forceSuSp & susp) inline
Addition.
Definition at line 90 of file forceSuSpI.H.
References Tuple2< T1, T2 >::first(), and Tuple2< T1, T2 >::second().
void operator-= (const forceSuSp & susp) inline
Subtraction.
Definition at line 97 of file forceSuSpI.H.
References Tuple2< T1, T2 >::first(), and Tuple2< T1, T2 >::second().
Friends And Related Function Documentation
forceSuSp operator* (const forceSuSp & susp1, const forceSuSp & susp2) friend
Addition.
forceSuSp operator* (const scalar s, const forceSuSp & susp) friend
Multiplication.
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/forceSuSp/forceSuSp.H
src/lagrangian/intermediate/submodels/Kinematic/ParticleForces/forceSuSp/forceSuSpI.H