OpenFOAM: turbulentDispersionModel Class Reference
turbulentDispersionModel Class Reference abstract
Public Member Functions
TypeName ("turbulentDispersionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, turbulentDispersionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
turbulentDispersionModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~turbulentDispersionModel ()
Destructor.
const
phaseCompressibleTurbulenceModel & continuousTurbulence () const
Return a reference to the turbulence model for the continuous phase.
virtual tmp< volScalarField > D () const =0
Turbulent diffusivity.
virtual tmp< volVectorField > F () const
Turbulent dispersion force.
virtual tmp< surfaceScalarField > Ff () const
Turbulent dispersion force on faces.
TypeName ("turbulentDispersionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, turbulentDispersionModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
turbulentDispersionModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~turbulentDispersionModel ()
Destructor.
virtual tmp< volScalarField > D () const =0
Turbulent diffusivity.
virtual tmp< volVectorField > F () const
Turbulent dispersion force.
Static Public Member Functions
static autoPtr
< turbulentDispersionModel > New (const dictionary &dict, const phasePair &pair)
static autoPtr
< turbulentDispersionModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimD
Diffusivity dimensions.
static const dimensionSet dimF
Force dimensions.
Protected Attributes
const phasePair & pair_
Phase pair.
Detailed Description
Source files
turbulentDispersionModel.H
turbulentDispersionModel.C
newTurbulentDispersionModel.C
Source files
turbulentDispersionModel.H
turbulentDispersionModel.C
newTurbulentDispersionModel.C
Definition at line 51 of file turbulentDispersionModel.H.
Constructor & Destructor Documentation
turbulentDispersionModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
Definition at line 45 of file turbulentDispersionModel.C.
~turbulentDispersionModel () virtual
Destructor.
Definition at line 56 of file turbulentDispersionModel.C.
turbulentDispersionModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
virtual ~turbulentDispersionModel () virtual
Destructor.
Member Function Documentation
TypeName ("turbulentDispersionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , turbulentDispersionModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::turbulentDispersionModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 29 of file newTurbulentDispersionModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
const Foam::phaseCompressibleTurbulenceModel & continuousTurbulence () const
Return a reference to the turbulence model for the continuous phase.
Definition at line 63 of file turbulentDispersionModel.C.
virtual tmp<volScalarField> D () const pure virtual
Turbulent diffusivity.
multiplying the gradient of the phase-fraction
Implemented in Burns, Burns, LopezDeBertodano, LopezDeBertodano, Gosman, Gosman, constantTurbulentDispersionCoefficient, constantTurbulentDispersionCoefficient, noTurbulentDispersion, and noTurbulentDispersion.
Foam::tmp< Foam::volVectorField > F () const virtual
Turbulent dispersion force.
Reimplemented in noTurbulentDispersion, and noTurbulentDispersion.
Definition at line 78 of file turbulentDispersionModel.C.
Foam::tmp< Foam::surfaceScalarField > Ff () const virtual
Turbulent dispersion force on faces.
Definition at line 85 of file turbulentDispersionModel.C.
References D, and Foam::fvc::grad().
TypeName ("turbulentDispersionModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , turbulentDispersionModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
static autoPtr<turbulentDispersionModel> New (const dictionary & dict, const phasePair & pair) static
virtual tmp<volScalarField> D () const pure virtual
Turbulent diffusivity.
multiplying the gradient of the phase-fraction
Implemented in Burns, Burns, LopezDeBertodano, LopezDeBertodano, Gosman, Gosman, constantTurbulentDispersionCoefficient, constantTurbulentDispersionCoefficient, noTurbulentDispersion, and noTurbulentDispersion.
virtual tmp<volVectorField> F () const virtual
Turbulent dispersion force.
Reimplemented in noTurbulentDispersion, and noTurbulentDispersion.
Member Data Documentation
const phasePair & pair_ protected
Phase pair.
Definition at line 60 of file turbulentDispersionModel.H.
static const dimensionSet dimD static
Diffusivity dimensions.
Definition at line 90 of file turbulentDispersionModel.H.
static const dimensionSet dimF static
Force dimensions.
Definition at line 95 of file turbulentDispersionModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/turbulentDispersionModel.H
applications/solvers/multiphase/twoPhaseEulerFoam/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/turbulentDispersionModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/newTurbulentDispersionModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialModels/turbulentDispersionModels/turbulentDispersionModel/turbulentDispersionModel.C