OpenFOAM: PatchFunction1< Type > Class Template Reference
PatchFunction1< Type > Class Template Reference abstract
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or time varying, and provide functions to return the (interpolated) value, and integral between limits.
Public Types
typedef Field< Type > returnType
Public Member Functions
declareRunTimeSelectionTable (autoPtr, PatchFunction1, dictionary,(const polyPatch &pp, const word &type, const word &entryName, const dictionary &dict, const bool faceValues),(pp, type, entryName, dict, faceValues))
Runtime type information.
PatchFunction1 (const polyPatch &pp, const word &entryName, const bool faceValues=true)
Construct from polyPatch and entry name.
PatchFunction1 (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
Construct from polyPatch, dictionary and entry name.
PatchFunction1 (const PatchFunction1< Type > &pf1)
Copy constructor.
PatchFunction1 (const PatchFunction1< Type > &pf1, const polyPatch &pp)
Copy constructor setting patch.
virtual tmp< PatchFunction1
< Type > > clone () const =0
Construct and return a clone.
virtual tmp< PatchFunction1
< Type > > clone (const polyPatch &pp) const =0
Construct and return a clone setting patch.
virtual ~PatchFunction1 ()=default
Destructor.
const word & name () const
Return the name of the entry.
virtual void convertTimeBase (const Time &t)
Convert time.
virtual tmp< Field< Type > > value (const scalar x) const
Return value as a function of (scalar) independent variable.
virtual bool constant () const =0
Is value constant (i.e. independent of x)
virtual bool uniform () const =0
Is value uniform (i.e. independent of coordinate)
virtual tmp< Field< Type > > integrate (const scalar x1, const scalar x2) const
Integrate between two (scalar) values.
virtual tmp< pointField > localPosition (const pointField &globalPos) const
Helper: optionally convert coordinates to local coordinates.
virtual tmp< Field< Type > > transform (const Field< Type > &fld) const
Apply optional transformation.
virtual tmp< Field< Type > > transform (const tmp< Field< Type >> &tfld) const
Apply optional transformation.
virtual void autoMap (const FieldMapper &mapper)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const PatchFunction1< Type > &pf1, const labelList &addr)
Reverse map the given PatchFunction1 onto this PatchFunction1.
virtual void writeData (Ostream &os) const
Write in dictionary format.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static autoPtr< PatchFunction1
< Type > > New (const polyPatch &pp, const word &entryName, const dictionary &dict, const bool faceValues=true)
Selector.
Protected Attributes
const word name_
Name of entry.
const polyPatch & patch_
Reference to the patch.
const bool faceValues_
Whether to generate face or point values on patch.
coordinateScaling< Type > coordSys_
Optional local co-ordinate system and scaling.
Friends
Ostream & operator (Ostream &os, const PatchFunction1< Type > &func)
Ostream Operator.
Detailed Description
template<class Type>
class Foam::PatchFunction1< Type >
Top level data entry class for use in dictionaries. Provides a mechanism to specify a variable as a certain type, e.g. constant or time varying, and provide functions to return the (interpolated) value, and integral between limits.
Extends the Function1 class by adding autoMap and rMap functions
Source files
PatchFunction1.H
PatchFunction1.C
PatchFunction1New.C
See Also
Foam::Function1
Definition at line 59 of file PatchFunction1.H.
Member Typedef Documentation
typedef Field<Type> returnType
Definition at line 112 of file PatchFunction1.H.
Constructor & Destructor Documentation
PatchFunction1 (const polyPatch & pp, const word & entryName, const bool faceValues = true)
Construct from polyPatch and entry name.
Definition at line 29 of file PatchFunction1.C.
PatchFunction1 (const polyPatch & pp, const word & entryName, const dictionary & dict, const bool faceValues = true)
Construct from polyPatch, dictionary and entry name.
Definition at line 45 of file PatchFunction1.C.
PatchFunction1 (const PatchFunction1< Type > & pf1) explicit
Copy constructor.
Definition at line 61 of file PatchFunction1.C.
PatchFunction1 (const PatchFunction1< Type > & pf1, const polyPatch & pp) explicit
Copy constructor setting patch.
Definition at line 73 of file PatchFunction1.C.
virtual ~PatchFunction1 () virtual default
Destructor.
Member Function Documentation
declareRunTimeSelectionTable (autoPtr , PatchFunction1< Type > , dictionary , (const polyPatch &pp, const word &type, const word &entryName, const dictionary &dict, const bool faceValues) , (pp, type, entryName, dict, faceValues))
Runtime type information.
Declare runtime constructor selection table
virtual tmp<PatchFunction1<Type> > clone () const pure virtual
Construct and return a clone.
Implemented in Sampled< Type >, MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
virtual tmp<PatchFunction1<Type> > clone (const polyPatch & pp) const pure virtual
Construct and return a clone setting patch.
Implemented in Sampled< Type >, MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
Foam::autoPtr< Foam::PatchFunction1< Type > > New (const polyPatch & pp, const word & entryName, const dictionary & dict, const bool faceValues = true) static
Selector.
Definition at line 27 of file PatchFunction1New.C.
References dict, entry::dict(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findEntry(), dictionary::getWord(), entry::isDict(), token::isWord(), Foam::nl, PrimitivePatch< Face, FaceList, PointField, PointType >::nPoints(), dictionary::optionalSubDict(), Istream::putBack(), entry::stream(), value(), and token::wordToken().
const Foam::word & name () const
Return the name of the entry.
Definition at line 89 of file PatchFunction1.C.
void convertTimeBase (const Time & t) virtual
Convert time.
Definition at line 96 of file PatchFunction1.C.
Foam::tmp< Foam::Field< Type > > value (const scalar x) const virtual
Return value as a function of (scalar) independent variable.
Reimplemented in Sampled< Type >, MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
Definition at line 102 of file PatchFunction1.C.
virtual bool constant () const pure virtual
Is value constant (i.e. independent of x)
Implemented in Sampled< Type >, MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
bool uniform () const pure virtual
Is value uniform (i.e. independent of coordinate)
Implemented in Sampled< Type >, MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
Definition at line 112 of file PatchFunction1.C.
References NotImplemented.
Referenced by MappedFile< Type >::clone().
Foam::tmp< Foam::Field< Type > > integrate (const scalar x1, const scalar x2) const virtual
Integrate between two (scalar) values.
Reimplemented in Sampled< Type >, MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
Definition at line 120 of file PatchFunction1.C.
Foam::tmp< Foam::pointField > localPosition (const pointField & globalPos) const virtual
Helper: optionally convert coordinates to local coordinates.
Definition at line 133 of file PatchFunction1.C.
Foam::tmp< Foam::Field< Type > > transform (const Field< Type > & fld) const virtual
Apply optional transformation.
Definition at line 169 of file PatchFunction1.C.
Foam::tmp< Foam::Field< Type > > transform (const tmp< Field< Type >> & tfld) const virtual
Apply optional transformation.
Definition at line 146 of file PatchFunction1.C.
void autoMap (const FieldMapper & mapper) virtual
Map (and resize as needed) from self given a mapping object.
Reimplemented in MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
Definition at line 190 of file PatchFunction1.C.
References fld.
void rmap (const PatchFunction1< Type > & pf1, const labelList & addr) virtual
Reverse map the given PatchFunction1 onto this PatchFunction1.
Reimplemented in MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
Definition at line 196 of file PatchFunction1.C.
void writeData (Ostream & os) const virtual
Write in dictionary format.
Reimplemented in Sampled< Type >, MappedFile< Type >, ConstantField< Type >, and UniformValueField< Type >.
Definition at line 204 of file PatchFunction1.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const PatchFunction1< Type > & func) friend
Ostream Operator.
Member Data Documentation
const word name_ protected
Name of entry.
Definition at line 92 of file PatchFunction1.H.
const polyPatch& patch_ protected
Reference to the patch.
Definition at line 97 of file PatchFunction1.H.
const bool faceValues_ protected
Whether to generate face or point values on patch.
Definition at line 102 of file PatchFunction1.H.
coordinateScaling<Type> coordSys_ protected
Optional local co-ordinate system and scaling.
Definition at line 107 of file PatchFunction1.H.
The documentation for this class was generated from the following files:
src/meshTools/PatchFunction1/PatchFunction1.H
src/meshTools/PatchFunction1/PatchFunction1.C
src/meshTools/PatchFunction1/PatchFunction1New.C