OpenFOAM: dynamicIndexedOctree< Type > Class Template Reference
dynamicIndexedOctree< Type > Class Template Reference
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
Classes
class node
Tree node. Has up pointer and down pointers.
Public Member Functions
dynamicIndexedOctree (const Type &shapes, const treeBoundBox &bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
autoPtr< dynamicIndexedOctree
< Type > > clone () const
Clone.
const Type & shapes () const
Reference to shape.
const List< node > & nodes () const
List of all nodes.
const contentListList & contents () const
List of all contents (referenced by those nodes that are.
const treeBoundBox & bb () const
Top bounding box.
pointIndexHit findNearest (const point &sample, const scalar nearestDistSqr) const
Calculate nearest point on nearest shape.
void findNearest (const label nodeI, const point &, scalar &nearestDistSqr, label &nearestShapeI, point &nearestPoint) const
Low level: calculate nearest starting from subnode.
pointIndexHit findNearest (const linePointRef &ln, treeBoundBox &tightest, point &linePoint) const
Find nearest to line.
pointIndexHit findLine (const point &start, const point &end) const
Find nearest intersection of line between start and end.
pointIndexHit findLineAny (const point &start, const point &end) const
Find any intersection of line between start and end.
labelList findBox (const treeBoundBox &bb) const
Find (in no particular order) indices of all shapes inside or.
labelList findSphere (const point &centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
labelBits findNode (const label nodeI, const point &) const
Find deepest node (as parent+octant) containing point. Starts.
label findInside (const point &) const
Find shape containing point. Only implemented for certain.
const labelList & findIndices (const point &) const
Find the shape indices that occupy the result of findNode.
volumeType getVolumeType (const point &) const
Determine type (inside/outside/mixed) for point. unknown if.
template<class CompareOp >
void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > &tree2, CompareOp &cop) const
Find near pairs and apply CompareOp to them.
bool insert (label startIndex, label endIndex)
Insert a new object into the tree.
bool insertIndex (const label nodIndex, const label index, label &nLevels)
bool remove (const label index)
Remove an object from the tree.
label removeIndex (const label nodIndex, const label index)
void print (prefixOSstream &, const bool printContents, const label) const
Print tree. Either print all indices (printContent = true) or.
bool write (Ostream &os) const
void writeTreeInfo () const
Static Public Member Functions
static scalar & perturbTol ()
Get the perturbation tolerance.
static bool isContent (const labelBits i)
static bool isEmpty (const labelBits i)
static bool isNode (const labelBits i)
static label getContent (const labelBits i)
static label getNode (const labelBits i)
static direction getOctant (const labelBits i)
static volumeType getSide (const vector &outsideNormal, const vector &vec)
Helper function to return the side. Returns outside if.
static bool overlaps (const point &bbMin, const point &bbMax, const scalar nearestDistSqr, const point &sample)
Helper: does bb intersect a sphere around sample? Or is any.
Friends
Ostream & operator (Ostream &, const dynamicIndexedOctree< Type > &)
Detailed Description
template<class Type>
class Foam::dynamicIndexedOctree< Type >
Non-pointer based hierarchical recursive searching. Storage is dynamic, so elements can be deleted.
Source files
dynamicIndexedOctree.H
dynamicIndexedOctree.C
Definition at line 53 of file dynamicIndexedOctree.H.
Constructor & Destructor Documentation
dynamicIndexedOctree (const Type & shapes, const treeBoundBox & bb, const label maxLevels, const scalar maxLeafRatio, const scalar maxDuplicity)
Construct from shapes.
Definition at line 2133 of file dynamicIndexedOctree.C.
References Foam::expressions::patchExpr::debug, dynamicIndexedOctree< Type >::insert(), and dynamicIndexedOctree< Type >::writeTreeInfo().
Member Function Documentation
Foam::scalar & perturbTol () static
Get the perturbation tolerance.
Definition at line 2169 of file dynamicIndexedOctree.C.
autoPtr<dynamicIndexedOctree<Type> > clone () const inline
Clone.
Definition at line 499 of file dynamicIndexedOctree.H.
const Type& shapes () const inline
Reference to shape.
Definition at line 512 of file dynamicIndexedOctree.H.
const List<node>& nodes () const inline
List of all nodes.
Definition at line 520 of file dynamicIndexedOctree.H.
const contentListList& contents () const inline
List of all contents (referenced by those nodes that are.
contents)
Definition at line 530 of file dynamicIndexedOctree.H.
const treeBoundBox& bb () const inline
Top bounding box.
Definition at line 538 of file dynamicIndexedOctree.H.
Referenced by dynamicIndexedOctree< Type >::findNear().
static bool isContent (const labelBits i) inline static
Definition at line 551 of file dynamicIndexedOctree.H.
static bool isEmpty (const labelBits i) inline static
Definition at line 556 of file dynamicIndexedOctree.H.
static bool isNode (const labelBits i) inline static
Definition at line 561 of file dynamicIndexedOctree.H.
static label getContent (const labelBits i) inline static
Definition at line 566 of file dynamicIndexedOctree.H.
static label getNode (const labelBits i) inline static
Definition at line 576 of file dynamicIndexedOctree.H.
static direction getOctant (const labelBits i) inline static
Definition at line 586 of file dynamicIndexedOctree.H.
Foam::pointIndexHit findNearest (const point & sample, const scalar nearestDistSqr) const
Calculate nearest point on nearest shape.
Returns
bool : any point found nearer than nearestDistSqr
label: index in shapes
point: actual nearest point found
Definition at line 2177 of file dynamicIndexedOctree.C.
References Foam::Zero.
void findNearest (const label nodeI, const point & sample, scalar & nearestDistSqr, label & nearestShapeI, point & nearestPoint) const
Low level: calculate nearest starting from subnode.
Definition at line 466 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::node::bb_, i, boundBox::max(), boundBox::min(), treeBoundBox::searchOrder(), and dynamicIndexedOctree< Type >::node::subNodes_.
Foam::pointIndexHit findNearest (const linePointRef & ln, treeBoundBox & tightest, point & linePoint) const
Find nearest to line.
Returns
bool : any point found?
label: index in shapes
point: actual nearest point found sets:
linePoint : corresponding nearest point on line
Definition at line 2205 of file dynamicIndexedOctree.C.
References Foam::Zero.
Foam::pointIndexHit findLine (const point & start, const point & end) const
Find nearest intersection of line between start and end.
Definition at line 2238 of file dynamicIndexedOctree.C.
References findLine().
Foam::pointIndexHit findLineAny (const point & start, const point & end) const
Find any intersection of line between start and end.
Definition at line 2249 of file dynamicIndexedOctree.C.
References findLine().
Foam::labelList findBox (const treeBoundBox & bb) const
Find (in no particular order) indices of all shapes inside or.
overlapping bounding box (i.e. all shapes not outside box)
Definition at line 2260 of file dynamicIndexedOctree.C.
Foam::labelList findSphere (const point & centre, const scalar radiusSqr) const
Find (in no particular order) indices of all shapes inside or.
overlapping a bounding sphere (i.e. all shapes not outside sphere)
Definition at line 2280 of file dynamicIndexedOctree.C.
Foam::labelBits findNode (const label nodeI, const point & sample) const
Find deepest node (as parent+octant) containing point. Starts.
off from starting index in nodes_ (use 0 to start from top) Use getNode and getOctant to extract info, or call findIndices.
Definition at line 2301 of file dynamicIndexedOctree.C.
References Foam::abort(), dynamicIndexedOctree< Type >::node::bb_, treeBoundBox::contains(), Foam::expressions::patchExpr::debug, Foam::FatalError, FatalErrorInFunction, dynamicIndexedOctree< Type >::node::subNodes_, and treeBoundBox::subOctant().
Foam::label findInside (const point & sample) const
Find shape containing point. Only implemented for certain.
shapes.
Definition at line 2348 of file dynamicIndexedOctree.C.
References forAll, and dynamicIndexedOctree< Type >::node::subNodes_.
const Foam::labelList & findIndices (const point & sample) const
Find the shape indices that occupy the result of findNode.
Definition at line 2380 of file dynamicIndexedOctree.C.
References List< label >::null(), and dynamicIndexedOctree< Type >::node::subNodes_.
Foam::volumeType getVolumeType (const point & sample) const
Determine type (inside/outside/mixed) for point. unknown if.
cannot be determined (e.g. non-manifold surface)
Definition at line 2402 of file dynamicIndexedOctree.C.
References Foam::abort(), Foam::expressions::patchExpr::debug, Foam::endl(), Foam::FatalError, FatalErrorInFunction, forAll, volumeType::INSIDE, volumeType::MIXED, volumeType::OUTSIDE, Foam::Pout, Foam::type(), and volumeType::UNKNOWN.
Foam::volumeType getSide (const vector & outsideNormal, const vector & vec) static
Helper function to return the side. Returns outside if.
outsideNormal&vec >= 0, inside otherwise
Definition at line 448 of file dynamicIndexedOctree.C.
bool overlaps (const point & bbMin, const point & bbMax, const scalar nearestDistSqr, const point & sample) static
Helper: does bb intersect a sphere around sample? Or is any.
corner point of bb closer than nearestDistSqr to sample.
Definition at line 36 of file dynamicIndexedOctree.C.
References Foam::mag().
void findNear (const scalar nearDist, const dynamicIndexedOctree< Type > & tree2, CompareOp & cop) const
Find near pairs and apply CompareOp to them.
tree2 can be *this or different tree.
Definition at line 2472 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::bb().
bool insert (label startIndex, label endIndex)
Insert a new object into the tree.
Definition at line 2494 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Type >::dynamicIndexedOctree().
bool insertIndex (const label nodIndex, const label index, label & nLevels)
Definition at line 2541 of file dynamicIndexedOctree.C.
References treeBoundBox::subBbox().
bool remove (const label index)
Remove an object from the tree.
Definition at line 2617 of file dynamicIndexedOctree.C.
Foam::label removeIndex (const label nodIndex, const label index)
Definition at line 2632 of file dynamicIndexedOctree.C.
References DynamicList< T, SizeMin >::append(), forAll, UList< T >::size(), treeBoundBox::subBbox(), and DynamicList< T, SizeMin >::transfer().
void print (prefixOSstream & os, const bool printContents, const label nodeI) const
Print tree. Either print all indices (printContent = true) or.
just size of contents nodes.
Definition at line 2715 of file dynamicIndexedOctree.C.
References dynamicIndexedOctree< Type >::node::bb_, Foam::endl(), forAll, j, Foam::nl, dynamicIndexedOctree< Type >::node::parent_, prefixOSstream::prefix(), Foam::BitOps::print(), UList< T >::size(), treeBoundBox::subBbox(), dynamicIndexedOctree< Type >::node::subNodes_, and Foam::meshTools::writeOBJ().
bool write (Ostream & os) const
Definition at line 2813 of file dynamicIndexedOctree.C.
void writeTreeInfo () const
Definition at line 2787 of file dynamicIndexedOctree.C.
Referenced by dynamicIndexedOctree< Type >::dynamicIndexedOctree().
Friends And Related Function Documentation
Ostream& operator (Ostream & , const dynamicIndexedOctree< Type > &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.H
src/OpenFOAM/algorithms/dynamicIndexedOctree/dynamicIndexedOctree.C