OpenFOAM: cloudSolution Class Reference
cloudSolution Class Reference
Stores all relevant solution info for cloud.
Public Member Functions
cloudSolution (const fvMesh &mesh)
Construct null from mesh reference.
cloudSolution (const fvMesh &mesh, const dictionary &dict)
Construct from mesh and dictionary.
cloudSolution (const cloudSolution &cs)
Construct copy.
virtual ~cloudSolution ()
Destructor.
void read ()
Read properties from dictionary.
scalar relaxCoeff (const word &fieldName) const
Return relaxation coefficient for field.
bool semiImplicit (const word &fieldName) const
Return semi-implicit flag coefficient for field.
const fvMesh & mesh () const
Return reference to the mesh.
const dictionary & dict () const
Return const access to the dictionary.
const Switch active () const
Return the active flag.
const Switch transient () const
Return const access to the transient flag.
const Switch steadyState () const
Return const access to the steady flag.
label calcFrequency () const
Return const access to the calculation frequency.
scalar maxCo () const
Return const access to the max particle Courant number.
label iter () const
Return const access to the current cloud iteration.
label nextIter ()
Increment and return iter counter.
scalar trackTime () const
Return the particle track time.
scalar deltaTMax () const
Return the maximum integration time step.
const Switch coupled () const
Return const access to the coupled flag.
Switch & coupled ()
Return non-const access to the coupled flag.
const Switch cellValueSourceCorrection () const
Return const access to the cell value correction flag.
scalar maxTrackTime () const
Return const access to the particle track time.
const Switch resetSourcesOnStartup () const
Return const access to the reset sources flag.
const dictionary & sourceTermDict () const
Source terms dictionary.
const dictionary & interpolationSchemes () const
Interpolation schemes dictionary.
const dictionary & integrationSchemes () const
Integration schemes dictionary.
bool solveThisStep () const
Returns true if performing a cloud iteration this calc step.
bool canEvolve ()
Returns true if possible to evolve the cloud and sets timestep.
bool output () const
Returns true if writing this step.
scalar deltaTMax (const scalar trackTime) const
Return the maximum integration time.
scalar deltaLMax (const scalar lRef) const
Return the maximum integration length.
Detailed Description
Stores all relevant solution info for cloud.
Source files
cloudSolution.H
cloudSolutionI.H
cloudSolution.C
Definition at line 49 of file cloudSolution.H.
Constructor & Destructor Documentation
cloudSolution (const fvMesh & mesh)
Construct null from mesh reference.
Definition at line 89 of file cloudSolution.C.
cloudSolution (const fvMesh & mesh, const dictionary & dict)
Construct from mesh and dictionary.
Definition at line 27 of file cloudSolution.C.
References Foam::endl(), Foam::Info, cloudSolution::read(), dictionary::readIfPresent(), and dictionary::subOrEmptyDict().
cloudSolution (const cloudSolution & cs)
Construct copy.
Definition at line 70 of file cloudSolution.C.
~cloudSolution () virtual
Destructor.
Definition at line 110 of file cloudSolution.C.
Member Function Documentation
void read ()
Read properties from dictionary.
Definition at line 116 of file cloudSolution.C.
Referenced by cloudSolution::cloudSolution().
Foam::scalar relaxCoeff (const word & fieldName) const
Return relaxation coefficient for field.
Definition at line 197 of file cloudSolution.C.
bool semiImplicit (const word & fieldName) const
Return semi-implicit flag coefficient for field.
Definition at line 215 of file cloudSolution.C.
const Foam::fvMesh & mesh () const inline
Return reference to the mesh.
Definition at line 21 of file cloudSolutionI.H.
const Foam::dictionary & dict () const inline
Return const access to the dictionary.
Definition at line 27 of file cloudSolutionI.H.
const Foam::Switch active () const inline
Return the active flag.
Definition at line 33 of file cloudSolutionI.H.
const Foam::Switch transient () const inline
Return const access to the transient flag.
Definition at line 57 of file cloudSolutionI.H.
References dictionary::subDict().
const Foam::Switch steadyState () const inline
Return const access to the steady flag.
Definition at line 63 of file cloudSolutionI.H.
Foam::label calcFrequency () const inline
Return const access to the calculation frequency.
Definition at line 69 of file cloudSolutionI.H.
Foam::scalar maxCo () const inline
Return const access to the max particle Courant number.
Definition at line 75 of file cloudSolutionI.H.
Referenced by KinematicParcel< ParcelType >::move().
Foam::label iter () const inline
Return const access to the current cloud iteration.
Definition at line 81 of file cloudSolutionI.H.
Foam::label nextIter () inline
Increment and return iter counter.
Definition at line 87 of file cloudSolutionI.H.
Foam::scalar trackTime () const inline
Return the particle track time.
Definition at line 93 of file cloudSolutionI.H.
Foam::scalar deltaTMax () const inline
Return the maximum integration time step.
Definition at line 99 of file cloudSolutionI.H.
const Foam::Switch coupled () const inline
Return const access to the coupled flag.
Definition at line 111 of file cloudSolutionI.H.
Foam::Switch & coupled () inline
Return non-const access to the coupled flag.
Definition at line 105 of file cloudSolutionI.H.
const Foam::Switch cellValueSourceCorrection () const inline
Return const access to the cell value correction flag.
Definition at line 117 of file cloudSolutionI.H.
Referenced by KinematicParcel< ParcelType >::move().
Foam::scalar maxTrackTime () const inline
Return const access to the particle track time.
Definition at line 123 of file cloudSolutionI.H.
const Foam::Switch resetSourcesOnStartup () const inline
Return const access to the reset sources flag.
Definition at line 129 of file cloudSolutionI.H.
const Foam::dictionary & sourceTermDict () const inline
Source terms dictionary.
Definition at line 39 of file cloudSolutionI.H.
const Foam::dictionary & interpolationSchemes () const inline
Interpolation schemes dictionary.
Definition at line 45 of file cloudSolutionI.H.
References dictionary::subDict().
const Foam::dictionary & integrationSchemes () const inline
Integration schemes dictionary.
Definition at line 51 of file cloudSolutionI.H.
References dictionary::subDict().
bool solveThisStep () const
Returns true if performing a cloud iteration this calc step.
Definition at line 233 of file cloudSolution.C.
bool canEvolve ()
Returns true if possible to evolve the cloud and sets timestep.
parameters
Definition at line 244 of file cloudSolution.C.
bool output () const
Returns true if writing this step.
Definition at line 259 of file cloudSolution.C.
Foam::scalar deltaTMax (const scalar trackTime) const
Return the maximum integration time.
Definition at line 265 of file cloudSolution.C.
Foam::scalar deltaLMax (const scalar lRef) const
Return the maximum integration length.
Definition at line 278 of file cloudSolution.C.
References Foam::min().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolution.H
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolution.C
src/lagrangian/intermediate/clouds/Templates/KinematicCloud/cloudSolution/cloudSolutionI.H