OpenFOAM: PointHit< Point > Class Template Reference
PointHit< Point > Class Template Reference
This class describes the interaction of a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
Public Member Functions
PointHit ()
Construct null.
PointHit (const bool hit, const Point &p, const scalar dist, const bool eligibleMiss)
Construct from components.
PointHit (const Point &p)
Construct from point. Hit and distance set later.
bool hit () const
Is there a hit.
const Point & hitPoint () const
Return hit point.
scalar distance () const
Return distance to hit.
const Point & missPoint () const
Return miss point.
const Point & rawPoint () const
Return point with no checking.
bool eligibleMiss () const
Is this an eligible miss.
void setHit ()
void setMiss (const bool eligible)
void setPoint (const Point &p)
void setDistance (const scalar d)
Friends
Ostream & operator (Ostream &os, const PointHit< Point > &b)
Detailed Description
template<class Point>
class Foam::PointHit< Point >
This class describes the interaction of a face and a point. It carries the info of a successful hit and (if successful), returns the interaction point.
Definition at line 47 of file PointHit.H.
Constructor & Destructor Documentation
PointHit () inline
Construct null.
Definition at line 90 of file PointHit.H.
PointHit (const bool hit, const Point & p, const scalar dist, const bool eligibleMiss) inline
Construct from components.
Definition at line 102 of file PointHit.H.
PointHit (const Point & p) inline
Construct from point. Hit and distance set later.
Definition at line 118 of file PointHit.H.
Member Function Documentation
bool hit () const inline
Is there a hit.
Definition at line 134 of file PointHit.H.
Referenced by mappedPatchBase::facePoint(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectFaceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints(), and face::ray().
const Point& hitPoint () const inline
Return hit point.
Definition at line 142 of file PointHit.H.
Referenced by mappedPatchBase::facePoint(), and face::ray().
scalar distance () const inline
Return distance to hit.
Definition at line 157 of file PointHit.H.
Referenced by mappedPatchBase::facePoint(), meshSearch::findNearestBoundaryFace(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectFaceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints(), and face::ray().
const Point& missPoint () const inline
Return miss point.
Definition at line 165 of file PointHit.H.
Referenced by PrimitivePatch< Face, FaceList, PointField, PointType >::projectFaceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints(), and face::ray().
const Point& rawPoint () const inline
Return point with no checking.
Definition at line 180 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere().
bool eligibleMiss () const inline
Is this an eligible miss.
Definition at line 188 of file PointHit.H.
Referenced by PrimitivePatch< Face, FaceList, PointField, PointType >::projectFaceCentres(), PrimitivePatch< Face, FaceList, PointField, PointType >::projectPoints(), and face::ray().
void setHit () inline
Definition at line 195 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), and face::ray().
void setMiss (const bool eligible) inline
Definition at line 201 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), and face::ray().
void setPoint (const Point & p) inline
Definition at line 207 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), and face::ray().
void setDistance (const scalar d) inline
Definition at line 212 of file PointHit.H.
Referenced by tetrahedron< Point, PointRef >::containmentSphere(), and face::ray().
Friends And Related Function Documentation
Ostream& operator (Ostream & os, const PointHit< Point > & b) friend
The documentation for this class was generated from the following file:
src/OpenFOAM/meshes/primitiveShapes/objectHit/PointHit.H