OpenFOAM: coordinateSystem Class Reference
coordinateSystem Class Reference
Base class for coordinate system specification, the default coordinate system type is cartesian .
Classes
struct iNew
Helper for construction of coordinateSystem PtrList.
Public Member Functions
TypeName ("coordinateSystem")
Runtime type information.
coordinateSystem ()
Construct null. This is an identity coordinateSystem.
coordinateSystem (const coordinateRotation &crot)
Copy construct from rotation with origin=0.
coordinateSystem (coordinateRotation &&crot)
Move construct from rotation with origin=0.
coordinateSystem (const coordinateSystem &csys)
Copy construct.
coordinateSystem (coordinateSystem &&csys)
Move construct.
coordinateSystem (autoPtr< coordinateSystem > &&csys)
Move construct from autoPtr.
coordinateSystem (const word &name, const coordinateSystem &csys)
Copy construct with a different name.
coordinateSystem (const point &origin, const coordinateRotation &crot)
Construct from origin and rotation.
coordinateSystem (const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const point &origin, const coordinateRotation &crot)
Construct from origin and rotation.
coordinateSystem (const word &name, const point &origin, const vector &axis, const vector &dirn)
Construct from origin and 2 axes.
coordinateSystem (const word &name, const dictionary &dict)
Construct from dictionary with a given name.
coordinateSystem (const dictionary &dict)
Construct from dictionary without a name.
coordinateSystem (const dictionary &dict, const word &dictName)
Construct from dictionary with optional subDict lookup.
virtual autoPtr< coordinateSystem > clone () const
Return clone.
declareRunTimeSelectionTable (autoPtr, coordinateSystem, dictionary,(const dictionary &dict),(dict))
declareRunTimeSelectionTable (autoPtr, coordinateSystem, registry,(const objectRegistry &obr, const dictionary &dict),(obr, dict))
virtual ~coordinateSystem ()=default
Destructor.
virtual bool valid () const
Considered valid if it has a specification.
virtual bool uniform () const
True if the rotation tensor is uniform for all locations.
virtual const coordinateRotation & rotation () const
The rotation specification.
virtual const word & name () const
Return the name.
virtual const string & note () const
Return the optional note.
virtual const point & origin () const
Return origin.
virtual const tensor & R () const
Return const reference to the rotation tensor.
virtual const vector e1 () const
The local Cartesian x-axis in global coordinates.
virtual const vector e2 () const
The local Cartesian y-axis in global coordinates.
virtual const vector e3 () const
The local Cartesian z-axis in global coordinates.
virtual void rename (const word &newName)
Rename.
virtual string & note ()
Provide non-constant access to the optional note.
virtual point & origin ()
Edit access to origin.
virtual void clear ()
Reset origin and rotation to an identity coordinateSystem.
virtual void rotation (autoPtr< coordinateRotation > &&crot)
Change the rotation.
virtual void write (Ostream &os) const
Write.
virtual void writeEntry (const word &keyword, Ostream &os) const
Write dictionary entry.
void operator= (const coordinateSystem &csys)
Copy assignment.
void operator= (coordinateSystem &&csys)
Move assignment.
void operator= (const autoPtr< coordinateSystem > &csys)
Copy assignment from autoPtr.
void operator= (autoPtr< coordinateSystem > &&csys)
Move assignment from autoPtr.
virtual tensor R (const point &global) const
Position-dependent rotation tensor (when uniform = false)
virtual tmp< tensorField > R (const UList< point > &global) const
Position-dependent rotation tensors (when uniform = false)
virtual tmp< tensorField > R (const pointUIndList &global) const
Position-dependent rotation tensors (when uniform = false)
point transformPoint (const point &localCart) const
Transform point and add origin offset.
tmp< pointField > transformPoint (const UList< point > &localCart) const
Transform points and add origin offset.
tmp< pointField > transformPoint (const pointUIndList &localCart) const
Transform points and add origin offset.
point invTransformPoint (const point &global) const
Remove origin offset and inverse transform point.
tmp< pointField > invTransformPoint (const UList< point > &global) const
Remove origin offset and inverse transform points.
tmp< pointField > invTransformPoint (const pointUIndList &global) const
Remove origin offset and inverse transform points.
point globalPosition (const point &local) const
From local coordinate position to global (cartesian) position.
tmp< pointField > globalPosition (const pointField &local) const
From local coordinate position to global (cartesian) position.
point localPosition (const point &global) const
From global (cartesian) position to local coordinate position.
tmp< pointField > localPosition (const pointField &global) const
From global (cartesian) position to local coordinate position.
vector globalVector (const vector &local) const
From local to global (cartesian) vector components.
tmp< vectorField > globalVector (const vectorField &local) const
From local to global (cartesian) vector components.
vector localVector (const vector &global) const
From global (cartesian) to local vector components.
tmp< vectorField > localVector (const vectorField &global) const
From global (cartesian) to local vector components.
virtual symmTensor transformPrincipal (const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< vector > &input) const
virtual symmTensor transformPrincipal (const point &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const vector &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< symmTensor > > transformPrincipal (const pointUIndList &global, const UList< vector > &input) const
virtual scalar transform (const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< scalar > &input) const
virtual scalar transform (const point &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< point > &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const scalar &input) const
virtual tmp< Field< scalar > > transform (const UList< point > &global, const UList< scalar > &input) const
virtual tmp< Field< scalar > > transform (const pointUIndList &global, const UList< scalar > &input) const
virtual vector transform (const vector &input) const
virtual tmp< Field< vector > > transform (const UList< vector > &input) const
virtual vector transform (const point &global, const vector &input) const
virtual tmp< Field< vector > > transform (const UList< point > &global, const vector &input) const
virtual tmp< Field< vector > > transform (const pointUIndList &global, const vector &input) const
virtual tmp< Field< vector > > transform (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< vector > > transform (const pointUIndList &global, const UList< vector > &input) const
virtual sphericalTensor transform (const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< sphericalTensor > &input) const
virtual sphericalTensor transform (const point &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< point > &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const pointUIndList &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > transform (const UList< point > &global, const UList< sphericalTensor > &input) const
virtual tmp< Field
< sphericalTensor > > transform (const pointUIndList &global, const UList< sphericalTensor > &input) const
virtual symmTensor transform (const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< symmTensor > &input) const
virtual symmTensor transform (const point &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > transform (const UList< point > &global, const UList< symmTensor > &input) const
virtual tmp< Field< symmTensor > > transform (const pointUIndList &global, const UList< symmTensor > &input) const
virtual tensor transform (const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< tensor > &input) const
virtual tensor transform (const point &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< point > &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const tensor &input) const
virtual tmp< Field< tensor > > transform (const UList< point > &global, const UList< tensor > &input) const
virtual tmp< Field< tensor > > transform (const pointUIndList &global, const UList< tensor > &input) const
virtual scalar invTransform (const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< scalar > &input) const
virtual scalar invTransform (const point &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const scalar &input) const
virtual tmp< Field< scalar > > invTransform (const UList< point > &global, const UList< scalar > &input) const
virtual tmp< Field< scalar > > invTransform (const pointUIndList &global, const UList< scalar > &input) const
virtual vector invTransform (const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< vector > &input) const
virtual vector invTransform (const point &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const vector &input) const
virtual tmp< Field< vector > > invTransform (const UList< point > &global, const UList< vector > &input) const
virtual tmp< Field< vector > > invTransform (const pointUIndList &global, const UList< vector > &input) const
virtual sphericalTensor invTransform (const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< sphericalTensor > &input) const
virtual sphericalTensor invTransform (const point &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< point > &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const pointUIndList &global, const sphericalTensor &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const UList< point > &global, const UList< sphericalTensor > &input) const
virtual tmp< Field
< sphericalTensor > > invTransform (const pointUIndList &global, const UList< sphericalTensor > &input) const
virtual symmTensor invTransform (const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< symmTensor > &input) const
virtual symmTensor invTransform (const point &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const symmTensor &input) const
virtual tmp< Field< symmTensor > > invTransform (const UList< point > &global, const UList< symmTensor > &input) const
virtual tmp< Field< symmTensor > > invTransform (const pointUIndList &global, const UList< symmTensor > &input) const
virtual tensor invTransform (const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< tensor > &input) const
virtual tensor invTransform (const point &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const tensor &input) const
virtual tmp< Field< tensor > > invTransform (const UList< point > &global, const UList< tensor > &input) const
virtual tmp< Field< tensor > > invTransform (const pointUIndList &global, const UList< tensor > &input) const
template<class PointField >
Foam::tmp< Foam::tensorField > rotationsImpl (const PointField &global) const
template<class PointField >
Foam::tmp< Foam::pointField > transformPointImpl (const PointField &localCart) const
template<class PointField >
Foam::tmp< Foam::pointField > invTransformPointImpl (const PointField &global) const
template<class RetType , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
template<class RetType , class PointField , class Type , class BinaryOp >
Foam::tmp< Foam::Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Static Public Member Functions
static autoPtr< coordinateSystem > New (word modelType, const objectRegistry &obr, const dictionary &dict)
Select construct the specified coordinate system type with reference to objectRegistry for indirect entries.
static autoPtr< coordinateSystem > New (word modelType, const dictionary &dict)
Select construct the specified coordinate system type.
static autoPtr< coordinateSystem > New (const objectRegistry &obr, const dictionary &dict, const word &dictName="")
Select construct from dictionary with reference to objectRegistry for indirect entries.
static autoPtr< coordinateSystem > New (const dictionary &dict, const word &dictName="")
Select constructed from dictionary.
static autoPtr< coordinateSystem > New (Istream &is)
Select constructed from Istream.
Protected Member Functions
template<class PointField >
tmp< tensorField > rotationsImpl (const PointField &global) const
Implementation for R() methods.
template<class PointField >
tmp< pointField > transformPointImpl (const PointField &localCart) const
Implementation for transformPoint() methods.
template<class PointField >
tmp< pointField > invTransformPointImpl (const PointField &global) const
Implementation for transformPosition() methods.
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToOneImpl (const PointField &global, const UList< Type > &input, const BinaryOp &bop) const
Use position-dependent transform tensors for multiple inputs.
template<class RetType , class PointField , class Type , class BinaryOp >
tmp< Field< RetType > > oneToManyImpl (const PointField &global, const Type &input, const BinaryOp &bop) const
Use position-dependent transform tensors for single input.
virtual vector localToGlobal (const vector &local, bool translate) const
From local coordinate system to the global Cartesian system with optional translation for the origin.
virtual tmp< vectorField > localToGlobal (const vectorField &local, bool translate) const
From local coordinate system to the global Cartesian system with optional translation for the origin.
virtual vector globalToLocal (const vector &global, bool translate) const
From global Cartesian system to the local coordinate system with optional translation for the origin.
virtual tmp< vectorField > globalToLocal (const vectorField &global, bool translate) const
From global Cartesian system to the local coordinate system with optional translation for the origin.
void assign (const dictionary &dict)
Assign from dictionary content.
coordinateSystem (std::nullptr_t)
Construct null, without allocating a coordinateRotation specification.
Static Protected Member Functions
template<class RetType , class Type , class BinaryOp >
static tmp< Field< RetType > > manyTimesImpl (const tensor &tt, const UList< Type > &input, const BinaryOp &bop)
Apply single transform tensor for multiple inputs.
Protected Attributes
autoPtr< coordinateRotation > spec_
User specification of the coordinate rotation.
point origin_
The coordinate system origin.
tensor rot_
The rotation tensor.
word name_
The name of the coordinate system (optional)
string note_
An optional note describing the coordinate system.
Static Protected Attributes
static coordinateSystem dummy_
Dummy coordinate system for suppressed manipulation.
Detailed Description
Base class for coordinate system specification, the default coordinate system type is cartesian .
All systems are defined by an origin point and a coordinate rotation By default, the axes specification can be used directly as part of the coordinate system specification. For example,
coordinateSystem
{
    origin  (0 0 0);
    e1      (0 1 0);
    e3      (1 0 0);
}
The same, but in more verbose format:
coordinateSystem
{
    type    cartesian;
    origin  (0 0 0);
    rotation
    {
        type    axes;
        e1      (0 1 0);
        e3      (1 0 0);
    }
}
Types of coordinateRotation:
none
axes
axisAngle
euler
starcd
Type of coordinateSystem:
cartesian
cylindrical
indirect (references an entry in coordinateSystems).
Source files
coordinateSystem.H
coordinateSystem.C
coordinateSystemNew.C
coordinateSystemTransform.C
Definition at line 119 of file coordinateSystem.H.
Constructor & Destructor Documentation
coordinateSystem (std::nullptr_t) protected
Construct null, without allocating a coordinateRotation specification.
Definition at line 99 of file coordinateSystem.C.
coordinateSystem ()
Construct null. This is an identity coordinateSystem.
Definition at line 109 of file coordinateSystem.C.
coordinateSystem (const coordinateRotation & crot) explicit
Copy construct from rotation with origin=0.
Definition at line 119 of file coordinateSystem.C.
coordinateSystem (coordinateRotation && crot) explicit
Move construct from rotation with origin=0.
Definition at line 125 of file coordinateSystem.C.
coordinateSystem (const coordinateSystem & csys)
Copy construct.
Definition at line 131 of file coordinateSystem.C.
coordinateSystem (coordinateSystem && csys)
Move construct.
Definition at line 141 of file coordinateSystem.C.
coordinateSystem (autoPtr< coordinateSystem > && csys) explicit
Move construct from autoPtr.
Definition at line 151 of file coordinateSystem.C.
coordinateSystem (const word & name, const coordinateSystem & csys)
Copy construct with a different name.
Definition at line 170 of file coordinateSystem.C.
coordinateSystem (const point & origin, const coordinateRotation & crot)
Construct from origin and rotation.
Definition at line 184 of file coordinateSystem.C.
coordinateSystem (const point & origin, const vector & axis, const vector & dirn)
Construct from origin and 2 axes.
Definition at line 209 of file coordinateSystem.C.
coordinateSystem (const word & name, const point & origin, const coordinateRotation & crot)
Construct from origin and rotation.
Definition at line 194 of file coordinateSystem.C.
coordinateSystem (const word & name, const point & origin, const vector & axis, const vector & dirn)
Construct from origin and 2 axes.
Definition at line 220 of file coordinateSystem.C.
coordinateSystem (const word & name, const dictionary & dict)
Construct from dictionary with a given name.
Definition at line 236 of file coordinateSystem.C.
coordinateSystem (const dictionary & dict) explicit
Construct from dictionary without a name.
Definition at line 251 of file coordinateSystem.C.
coordinateSystem (const dictionary & dict, const word & dictName)
Construct from dictionary with optional subDict lookup.
Parameters
dictName If non-empty, the sub-dictionary to use.
Definition at line 258 of file coordinateSystem.C.
virtual ~coordinateSystem () virtual default
Destructor.
Member Function Documentation
tmp<tensorField> rotationsImpl (const PointField & global) const protected
Implementation for R() methods.
tmp<pointField> transformPointImpl (const PointField & localCart) const protected
Implementation for transformPoint() methods.
tmp<pointField> invTransformPointImpl (const PointField & global) const protected
Implementation for transformPosition() methods.
static tmp<Field<RetType> > manyTimesImpl (const tensor & tt, const UList< Type > & input, const BinaryOp & bop) static protected
Apply single transform tensor for multiple inputs.
tmp<Field<RetType> > oneToOneImpl (const PointField & global, const UList< Type > & input, const BinaryOp & bop) const protected
Use position-dependent transform tensors for multiple inputs.
tmp<Field<RetType> > oneToManyImpl (const PointField & global, const Type & input, const BinaryOp & bop) const protected
Use position-dependent transform tensors for single input.
Foam::vector localToGlobal (const vector & local, bool translate) const protected virtual
From local coordinate system to the global Cartesian system with optional translation for the origin.
Reimplemented in indirect, and cylindrical.
Definition at line 330 of file coordinateSystem.C.
Referenced by coordinateSystem::e2(), cylindrical::localToGlobal(), and coordinateSystem::note().
Foam::tmp< Foam::vectorField > localToGlobal (const vectorField & local, bool translate) const protected virtual
From local coordinate system to the global Cartesian system with optional translation for the origin.
Reimplemented in indirect, and cylindrical.
Definition at line 345 of file coordinateSystem.C.
Foam::vector globalToLocal (const vector & global, bool translate) const protected virtual
From global Cartesian system to the local coordinate system with optional translation for the origin.
Reimplemented in indirect, and cylindrical.
Definition at line 360 of file coordinateSystem.C.
Referenced by cylindrical::globalToLocal(), indirect::localToGlobal(), and coordinateSystem::rename().
Foam::tmp< Foam::vectorField > globalToLocal (const vectorField & global, bool translate) const protected virtual
From global Cartesian system to the local coordinate system with optional translation for the origin.
Reimplemented in indirect, and cylindrical.
Definition at line 375 of file coordinateSystem.C.
void assign (const dictionary & dict) protected
Assign from dictionary content.
Definition at line 66 of file coordinateSystem.C.
References dictionary::csearchCompat(), keyType::LITERAL, coordinateRotation::New(), coordinateSystem::note_, coordinateSystem::origin_, dictionary::readEntry(), dictionary::readIfPresent(), coordinateSystem::rot_, and coordinateSystem::spec_.
TypeName ("coordinateSystem")
Runtime type information.
virtual autoPtr<coordinateSystem> clone () const inline virtual
Return clone.
Reimplemented in cylindrical, indirect, and cartesian.
Definition at line 406 of file coordinateSystem.H.
declareRunTimeSelectionTable (autoPtr , coordinateSystem , dictionary , (const dictionary &dict) , (dict))
declareRunTimeSelectionTable (autoPtr , coordinateSystem , registry , (const objectRegistry &obr, const dictionary &dict) , (obr, dict))
Foam::autoPtr< Foam::coordinateSystem > New (word modelType, const objectRegistry & obr, const dictionary & dict) static
Select construct the specified coordinate system type with reference to objectRegistry for indirect entries.
An empty modelType will be treated as "cartesian"
Definition at line 78 of file coordinateSystemNew.C.
References dict, Foam::exit(), Foam::FatalIOError, and FatalIOErrorInLookup.
Foam::autoPtr< Foam::coordinateSystem > New (word modelType, const dictionary & dict) static
Select construct the specified coordinate system type.
An empty modelType will be treated as "cartesian"
Definition at line 116 of file coordinateSystemNew.C.
Foam::autoPtr< Foam::coordinateSystem > New (const objectRegistry & obr, const dictionary & dict, const word & dictName = "") static
Select construct from dictionary with reference to objectRegistry for indirect entries.
Parameters
dictName If non-empty, the sub-dictionary name to use for the coordinate system description.
Note
When the dictName is empty, it includes an implicit search for a "coordinateSystem" sub-dictionary for convenience and compatibility with previous versions (1806 and earlier).
Definition at line 144 of file coordinateSystemNew.C.
Foam::autoPtr< Foam::coordinateSystem > New (const dictionary & dict, const word & dictName = "") static
Select constructed from dictionary.
Parameters
dictName If non-empty, the sub-dictionary name to use for the coordinate system description.
Note
When the dictName is empty, it includes an implicit search for a "coordinateSystem" sub-dictionary for convenience and compatibility with previous versions (1806 and earlier).
Definition at line 173 of file coordinateSystemNew.C.
Foam::autoPtr< Foam::coordinateSystem > New (Istream & is) static
Select constructed from Istream.
Expects a name/dictionary as input
Definition at line 200 of file coordinateSystemNew.C.
virtual bool valid () const inline virtual
Considered valid if it has a specification.
Reimplemented in indirect.
Definition at line 522 of file coordinateSystem.H.
virtual bool uniform () const inline virtual
True if the rotation tensor is uniform for all locations.
Reimplemented in cylindrical, and indirect.
Definition at line 530 of file coordinateSystem.H.
virtual const coordinateRotation& rotation () const inline virtual
The rotation specification.
Reimplemented in indirect.
Definition at line 538 of file coordinateSystem.H.
Referenced by indirect::clone().
virtual const word& name () const inline virtual
Return the name.
Reimplemented in indirect.
Definition at line 546 of file coordinateSystem.H.
virtual const string& note () const inline virtual
Return the optional note.
Reimplemented in indirect.
Definition at line 554 of file coordinateSystem.H.
Referenced by indirect::name().
virtual const point& origin () const inline virtual
Return origin.
Reimplemented in indirect.
Definition at line 562 of file coordinateSystem.H.
Referenced by indirect::note(), and Foam::operator!=().
virtual const tensor& R () const inline virtual
Return const reference to the rotation tensor.
Reimplemented in indirect.
Definition at line 570 of file coordinateSystem.H.
Referenced by Foam::operator!=(), indirect::rename(), and coordinateSystem::rotationsImpl().
virtual const vector e1 () const inline virtual
The local Cartesian x-axis in global coordinates.
Reimplemented in indirect.
Definition at line 578 of file coordinateSystem.H.
Referenced by indirect::valid().
virtual const vector e2 () const inline virtual
The local Cartesian y-axis in global coordinates.
Reimplemented in indirect.
Definition at line 586 of file coordinateSystem.H.
References coordinateSystem::localToGlobal().
Referenced by indirect::uniform().
virtual const vector e3 () const inline virtual
The local Cartesian z-axis in global coordinates.
Reimplemented in indirect.
Definition at line 594 of file coordinateSystem.H.
virtual void rename (const word & newName) inline virtual
Rename.
Reimplemented in indirect.
Definition at line 605 of file coordinateSystem.H.
References coordinateSystem::globalToLocal().
virtual string& note () inline virtual
Provide non-constant access to the optional note.
Reimplemented in indirect.
Definition at line 613 of file coordinateSystem.H.
References coordinateSystem::localToGlobal().
virtual point& origin () inline virtual
Edit access to origin.
Reimplemented in indirect.
Definition at line 621 of file coordinateSystem.H.
void clear () virtual
Reset origin and rotation to an identity coordinateSystem.
Also resets the note
Reimplemented in indirect.
Definition at line 278 of file coordinateSystem.C.
References SphericalTensor< scalar >::I, origin_(), and Foam::Zero.
void rotation (autoPtr< coordinateRotation > && crot) virtual
Change the rotation.
Reimplemented in indirect.
Definition at line 389 of file coordinateSystem.C.
void write (Ostream & os) const virtual
Write.
Reimplemented in indirect.
Definition at line 403 of file coordinateSystem.C.
void writeEntry (const word & keyword, Ostream & os) const virtual
Write dictionary entry.
Reimplemented in indirect.
Definition at line 421 of file coordinateSystem.C.
void operator= (const coordinateSystem & csys)
Copy assignment.
Definition at line 460 of file coordinateSystem.C.
References SphericalTensor< scalar >::I, coordinateSystem::name_, coordinateSystem::note_, coordinateSystem::origin_, and coordinateSystem::spec_.
void operator= (coordinateSystem && csys)
Move assignment.
Definition at line 479 of file coordinateSystem.C.
void operator= (const autoPtr< coordinateSystem > & csys)
Copy assignment from autoPtr.
Definition at line 489 of file coordinateSystem.C.
void operator= (autoPtr< coordinateSystem > && csys)
Move assignment from autoPtr.
Definition at line 495 of file coordinateSystem.C.
Foam::tensor R (const point & global) const virtual
Position-dependent rotation tensor (when uniform = false)
Returns
tensor
Reimplemented in indirect, and cylindrical.
Definition at line 287 of file coordinateSystem.C.
Foam::tmp< Foam::tensorField > R (const UList< point > & global) const virtual
Position-dependent rotation tensors (when uniform = false)
Returns
tensorField
Reimplemented in indirect.
Definition at line 294 of file coordinateSystem.C.
Foam::tmp< Foam::tensorField > R (const pointUIndList & global) const virtual
Position-dependent rotation tensors (when uniform = false)
Returns
tensorField
Reimplemented in indirect.
Definition at line 303 of file coordinateSystem.C.
Foam::point transformPoint (const point & localCart) const
Transform point and add origin offset.
Corresponds to a local-to-global transformation using Cartesian coordinates for both local and global.
Definition at line 312 of file coordinateSystem.C.
Foam::tmp< Foam::pointField > transformPoint (const UList< point > & localCart) const
Transform points and add origin offset.
Definition at line 96 of file coordinateSystemTransform.C.
Foam::tmp< Foam::pointField > transformPoint (const pointUIndList & localCart) const
Transform points and add origin offset.
Definition at line 105 of file coordinateSystemTransform.C.
Foam::point invTransformPoint (const point & global) const
Remove origin offset and inverse transform point.
Corresponds to a global-to-local transformation using Cartesian coordinates for both local and global.
Definition at line 321 of file coordinateSystem.C.
Foam::tmp< Foam::pointField > invTransformPoint (const UList< point > & global) const
Remove origin offset and inverse transform points.
Definition at line 114 of file coordinateSystemTransform.C.
Foam::tmp< Foam::pointField > invTransformPoint (const pointUIndList & global) const
Remove origin offset and inverse transform points.
Definition at line 123 of file coordinateSystemTransform.C.
point globalPosition (const point & local) const inline
From local coordinate position to global (cartesian) position.
Definition at line 741 of file coordinateSystem.H.
tmp<pointField> globalPosition (const pointField & local) const inline
From local coordinate position to global (cartesian) position.
Definition at line 749 of file coordinateSystem.H.
point localPosition (const point & global) const inline
From global (cartesian) position to local coordinate position.
Definition at line 757 of file coordinateSystem.H.
tmp<pointField> localPosition (const pointField & global) const inline
From global (cartesian) position to local coordinate position.
Definition at line 765 of file coordinateSystem.H.
vector globalVector (const vector & local) const inline
From local to global (cartesian) vector components.
Definition at line 775 of file coordinateSystem.H.
tmp<vectorField> globalVector (const vectorField & local) const inline
From local to global (cartesian) vector components.
Definition at line 783 of file coordinateSystem.H.
vector localVector (const vector & global) const inline
From global (cartesian) to local vector components.
Definition at line 791 of file coordinateSystem.H.
tmp<vectorField> localVector (const vectorField & global) const inline
From global (cartesian) to local vector components.
Definition at line 799 of file coordinateSystem.H.
Foam::symmTensor transformPrincipal (const vector & input) const virtual
! With constant rotation tensor
Definition at line 197 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const UList< vector > & input) const virtual
! With constant rotation tensor
Definition at line 197 of file coordinateSystemTransform.C.
Foam::symmTensor transformPrincipal (const point & global, const vector & input) const virtual
! With rotation tensor at given global position
Definition at line 197 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const UList< point > & global, const vector & input) const virtual
! With rotation tensors at given global positions
Definition at line 197 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const pointUIndList & global, const vector & input) const virtual
! With rotation tensors at given global positions
Definition at line 197 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const UList< point > & global, const UList< vector > & input) const virtual
! With rotation tensors at given global positions
Definition at line 197 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transformPrincipal (const pointUIndList & global, const UList< vector > & input) const virtual
! With rotation tensors at given global positions
Definition at line 197 of file coordinateSystemTransform.C.
Foam::scalar transform (const scalar & input) const virtual
! With constant rotation tensor
Definition at line 199 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > transform (const UList< scalar > & input) const virtual
! With constant rotation tensor
Definition at line 199 of file coordinateSystemTransform.C.
Foam::scalar transform (const point & global, const scalar & input) const virtual
! With rotation tensor at given global position
Definition at line 199 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > transform (const UList< point > & global, const scalar & input) const virtual
! With rotation tensors at given global positions
Definition at line 199 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > transform (const pointUIndList & global, const scalar & input) const virtual
! With rotation tensors at given global positions
Definition at line 199 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > transform (const UList< point > & global, const UList< scalar > & input) const virtual
! With rotation tensors at given global positions
Definition at line 199 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > transform (const pointUIndList & global, const UList< scalar > & input) const virtual
! With rotation tensors at given global positions
Definition at line 199 of file coordinateSystemTransform.C.
Foam::vector transform (const vector & input) const virtual
! With constant rotation tensor
Definition at line 200 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > transform (const UList< vector > & input) const virtual
! With constant rotation tensor
Definition at line 200 of file coordinateSystemTransform.C.
Foam::vector transform (const point & global, const vector & input) const virtual
! With rotation tensor at given global position
Definition at line 200 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > transform (const UList< point > & global, const vector & input) const virtual
! With rotation tensors at given global positions
Definition at line 200 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > transform (const pointUIndList & global, const vector & input) const virtual
! With rotation tensors at given global positions
Definition at line 200 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > transform (const UList< point > & global, const UList< vector > & input) const virtual
! With rotation tensors at given global positions
Definition at line 200 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > transform (const pointUIndList & global, const UList< vector > & input) const virtual
! With rotation tensors at given global positions
Definition at line 200 of file coordinateSystemTransform.C.
Foam::sphericalTensor transform (const sphericalTensor & input) const virtual
! With constant rotation tensor
Definition at line 201 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const UList< sphericalTensor > & input) const virtual
! With constant rotation tensor
Definition at line 201 of file coordinateSystemTransform.C.
Foam::sphericalTensor transform (const point & global, const sphericalTensor & input) const virtual
! With rotation tensor at given global position
Definition at line 201 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const UList< point > & global, const sphericalTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 201 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const pointUIndList & global, const sphericalTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 201 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const UList< point > & global, const UList< sphericalTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 201 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > transform (const pointUIndList & global, const UList< sphericalTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 201 of file coordinateSystemTransform.C.
Foam::symmTensor transform (const symmTensor & input) const virtual
! With constant rotation tensor
Definition at line 202 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const UList< symmTensor > & input) const virtual
! With constant rotation tensor
Definition at line 202 of file coordinateSystemTransform.C.
Foam::symmTensor transform (const point & global, const symmTensor & input) const virtual
! With rotation tensor at given global position
Definition at line 202 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const UList< point > & global, const symmTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 202 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const pointUIndList & global, const symmTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 202 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const UList< point > & global, const UList< symmTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 202 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > transform (const pointUIndList & global, const UList< symmTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 202 of file coordinateSystemTransform.C.
Foam::tensor transform (const tensor & input) const virtual
! With constant rotation tensor
Definition at line 203 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > transform (const UList< tensor > & input) const virtual
! With constant rotation tensor
Definition at line 203 of file coordinateSystemTransform.C.
Foam::tensor transform (const point & global, const tensor & input) const virtual
! With rotation tensor at given global position
Definition at line 203 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > transform (const UList< point > & global, const tensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 203 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > transform (const pointUIndList & global, const tensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 203 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > transform (const UList< point > & global, const UList< tensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 203 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > transform (const pointUIndList & global, const UList< tensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 203 of file coordinateSystemTransform.C.
Foam::scalar invTransform (const scalar & input) const virtual
! With constant rotation tensor
Definition at line 205 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const UList< scalar > & input) const virtual
! With constant rotation tensor
Definition at line 205 of file coordinateSystemTransform.C.
Foam::scalar invTransform (const point & global, const scalar & input) const virtual
! With rotation tensor at given global position
Definition at line 205 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const UList< point > & global, const scalar & input) const virtual
! With rotation tensors at given global positions
Definition at line 205 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const pointUIndList & global, const scalar & input) const virtual
! With rotation tensors at given global positions
Definition at line 205 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const UList< point > & global, const UList< scalar > & input) const virtual
! With rotation tensors at given global positions
Definition at line 205 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::scalar > > invTransform (const pointUIndList & global, const UList< scalar > & input) const virtual
! With rotation tensors at given global positions
Definition at line 205 of file coordinateSystemTransform.C.
Foam::vector invTransform (const vector & input) const virtual
! With constant rotation tensor
Definition at line 206 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const UList< vector > & input) const virtual
! With constant rotation tensor
Definition at line 206 of file coordinateSystemTransform.C.
Foam::vector invTransform (const point & global, const vector & input) const virtual
! With rotation tensor at given global position
Definition at line 206 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const UList< point > & global, const vector & input) const virtual
! With rotation tensors at given global positions
Definition at line 206 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const pointUIndList & global, const vector & input) const virtual
! With rotation tensors at given global positions
Definition at line 206 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const UList< point > & global, const UList< vector > & input) const virtual
! With rotation tensors at given global positions
Definition at line 206 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::vector > > invTransform (const pointUIndList & global, const UList< vector > & input) const virtual
! With rotation tensors at given global positions
Definition at line 206 of file coordinateSystemTransform.C.
Foam::sphericalTensor invTransform (const sphericalTensor & input) const virtual
! With constant rotation tensor
Definition at line 207 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const UList< sphericalTensor > & input) const virtual
! With constant rotation tensor
Definition at line 207 of file coordinateSystemTransform.C.
Foam::sphericalTensor invTransform (const point & global, const sphericalTensor & input) const virtual
! With rotation tensor at given global position
Definition at line 207 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const UList< point > & global, const sphericalTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 207 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const pointUIndList & global, const sphericalTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 207 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const UList< point > & global, const UList< sphericalTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 207 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::sphericalTensor > > invTransform (const pointUIndList & global, const UList< sphericalTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 207 of file coordinateSystemTransform.C.
Foam::symmTensor invTransform (const symmTensor & input) const virtual
! With constant rotation tensor
Definition at line 208 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const UList< symmTensor > & input) const virtual
! With constant rotation tensor
Definition at line 208 of file coordinateSystemTransform.C.
Foam::symmTensor invTransform (const point & global, const symmTensor & input) const virtual
! With rotation tensor at given global position
Definition at line 208 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const UList< point > & global, const symmTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 208 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const pointUIndList & global, const symmTensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 208 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const UList< point > & global, const UList< symmTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 208 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::symmTensor > > invTransform (const pointUIndList & global, const UList< symmTensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 208 of file coordinateSystemTransform.C.
Foam::tensor invTransform (const tensor & input) const virtual
! With constant rotation tensor
Definition at line 209 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const UList< tensor > & input) const virtual
! With constant rotation tensor
Definition at line 209 of file coordinateSystemTransform.C.
Foam::tensor invTransform (const point & global, const tensor & input) const virtual
! With rotation tensor at given global position
Definition at line 209 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const UList< point > & global, const tensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 209 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const pointUIndList & global, const tensor & input) const virtual
! With rotation tensors at given global positions
Definition at line 209 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const UList< point > & global, const UList< tensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 209 of file coordinateSystemTransform.C.
Foam::tmp< Foam::Field< Foam::tensor > > invTransform (const pointUIndList & global, const UList< tensor > & input) const virtual
! With rotation tensors at given global positions
Definition at line 209 of file coordinateSystemTransform.C.
Foam::tmp<Foam::tensorField> rotationsImpl (const PointField & global) const
Definition at line 28 of file coordinateSystemTemplates.C.
References i, tmp< T >::New(), and coordinateSystem::R().
Foam::tmp<Foam::pointField> transformPointImpl (const PointField & localCart) const
Definition at line 46 of file coordinateSystemTemplates.C.
Foam::tmp<Foam::pointField> invTransformPointImpl (const PointField & global) const
Definition at line 64 of file coordinateSystemTemplates.C.
Foam::tmp<Foam::Field<RetType> > manyTimesImpl (const tensor & tt, const UList< Type > & input, const BinaryOp & bop)
Definition at line 83 of file coordinateSystemTemplates.C.
Foam::tmp<Foam::Field<RetType> > oneToOneImpl (const PointField & global, const UList< Type > & input, const BinaryOp & bop) const
Definition at line 106 of file coordinateSystemTemplates.C.
Foam::tmp<Foam::Field<RetType> > oneToManyImpl (const PointField & global, const Type & input, const BinaryOp & bop) const
Definition at line 136 of file coordinateSystemTemplates.C.
Member Data Documentation
autoPtr<coordinateRotation> spec_ protected
User specification of the coordinate rotation.
May be invalid after a move assignment or transfer
Definition at line 144 of file coordinateSystem.H.
Referenced by coordinateSystem::assign(), and coordinateSystem::operator=().
point origin_ protected
The coordinate system origin.
Definition at line 149 of file coordinateSystem.H.
Referenced by coordinateSystem::assign(), and coordinateSystem::operator=().
tensor rot_ protected
The rotation tensor.
Definition at line 154 of file coordinateSystem.H.
Referenced by coordinateSystem::assign().
word name_ protected
The name of the coordinate system (optional)
Definition at line 159 of file coordinateSystem.H.
Referenced by coordinateSystem::operator=().
string note_ protected
An optional note describing the coordinate system.
Definition at line 164 of file coordinateSystem.H.
Referenced by coordinateSystem::assign(), and coordinateSystem::operator=().
Foam::coordinateSystem dummy_ static protected
Dummy coordinate system for suppressed manipulation.
Definition at line 169 of file coordinateSystem.H.
Referenced by indirect::name(), and indirect::note().
The documentation for this class was generated from the following files:
src/meshTools/coordinate/systems/coordinateSystem.H
src/meshTools/coordinate/systems/coordinateSystem.C
src/meshTools/coordinate/systems/coordinateSystemNew.C
src/meshTools/coordinate/systems/coordinateSystemTemplates.C
src/meshTools/coordinate/systems/coordinateSystemTransform.C