OpenFOAM: powerLawUniformBinary Class Reference
powerLawUniformBinary Class Reference
Powerlaw kernel with a uniform daughter size distribution. Used for verification and validation of the binary breakup formulation implemented in the populationBalanceModel class.
Public Member Functions
TypeName ("powerLawUniformBinary")
Runtime type information.
powerLawUniformBinary (const populationBalanceModel &popBal, const dictionary &dict)
virtual ~powerLawUniformBinary ()=default
Destructor.
virtual void addToBinaryBreakupRate (volScalarField &binaryBreakupRate, const label i, const label j)
Add to binary breakupRate.
Public Member Functions inherited from binaryBreakupModel
TypeName ("binaryBreakupModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, binaryBreakupModel, dictionary,(const populationBalanceModel &popBal, const dictionary &dict),(popBal, dict))
binaryBreakupModel (const populationBalanceModel &popBal, const dictionary &dict)
autoPtr< binaryBreakupModel > clone () const
virtual ~binaryBreakupModel ()=default
Destructor.
virtual void correct ()
Correct diameter independent expressions.
Additional Inherited Members
Static Public Member Functions inherited from binaryBreakupModel
static autoPtr
< binaryBreakupModel > New (const word &type, const populationBalanceModel &popBal, const dictionary &dict)
Protected Attributes inherited from binaryBreakupModel
const populationBalanceModel & popBal_
Reference to the populationBalanceModel.
Detailed Description
Powerlaw kernel with a uniform daughter size distribution. Used for verification and validation of the binary breakup formulation implemented in the populationBalanceModel class.
Source files
powerLawUniformBinary.H
powerLawUniformBinary.C
Definition at line 52 of file powerLawUniformBinary.H.
Constructor & Destructor Documentation
powerLawUniformBinary (const populationBalanceModel & popBal, const dictionary & dict)
Definition at line 48 of file powerLawUniformBinary.C.
virtual ~powerLawUniformBinary () virtual default
Destructor.
Member Function Documentation
TypeName ("powerLawUniformBinary")
Runtime type information.
void addToBinaryBreakupRate (volScalarField & binaryBreakupRate, const label i, const label j) virtual
Add to binary breakupRate.
Implements binaryBreakupModel.
Definition at line 63 of file powerLawUniformBinary.C.
References j, Foam::pow(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), dimensioned< Type >::value(), and sizeGroup::x().
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/populationBalanceModel/binaryBreakupModels/powerLawUniformBinary/powerLawUniformBinary.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/populationBalanceModel/binaryBreakupModels/powerLawUniformBinary/powerLawUniformBinary.C