OpenFOAM: columnFvMeshInfo Class Reference
columnFvMeshInfo Class Reference
Public Member Functions
ClassName ("columnFvMeshInfo")
Runtime type information.
columnFvMeshInfo (const Time &runTime, const word &regionName)
Protected Member Functions
void addLocalPatches (fvMesh &mesh) const
Add the patches to the mesh.
void initialiseZones (fvMesh &mesh)
Initialise zones if constructed from mesh.
Protected Attributes
const word regionName_
Region of existing mesh.
const fileName regionPrefix_
Additional prefix for region. Empty if default region.
const word localInstance_
Location of existing mesh (if present)
bool createFromMesh_
Created from existing mesh (false = from field)
pointField points1D_
Points.
faceList faces1D_
Faces.
labelList owner1D_
Owner addressing.
labelList neighbour1D_
Neighbour addressing.
dictionary patchEntries_
Dictionary of patch information.
label nPatchWithFace_
Number of patches with at least 1 local face.
Detailed Description
Definition at line 49 of file columnFvMesh.H.
Constructor & Destructor Documentation
columnFvMeshInfo (const Time & runTime, const word & regionName)
Definition at line 399 of file columnFvMesh.C.
Member Function Documentation
void addLocalPatches (fvMesh & mesh) const protected
Add the patches to the mesh.
Definition at line 318 of file columnFvMesh.C.
Referenced by SimplifiedDynamicFvMesh< DynamicMeshType >::SimplifiedDynamicFvMesh().
void initialiseZones (fvMesh & mesh) protected
Initialise zones if constructed from mesh.
Definition at line 379 of file columnFvMesh.C.
References polyMesh::boundaryMesh(), Foam::endl(), Foam::nl, and Foam::Pout.
Referenced by SimplifiedDynamicFvMesh< DynamicMeshType >::SimplifiedDynamicFvMesh().
ClassName ("columnFvMeshInfo")
Runtime type information.
Member Data Documentation
const word regionName_ protected
Region of existing mesh.
Definition at line 82 of file columnFvMesh.H.
const fileName regionPrefix_ protected
Additional prefix for region. Empty if default region.
Definition at line 87 of file columnFvMesh.H.
const word localInstance_ protected
Location of existing mesh (if present)
Definition at line 92 of file columnFvMesh.H.
bool createFromMesh_ protected
Created from existing mesh (false = from field)
Definition at line 97 of file columnFvMesh.H.
pointField points1D_ protected
Points.
Definition at line 105 of file columnFvMesh.H.
faceList faces1D_ protected
Faces.
Definition at line 110 of file columnFvMesh.H.
labelList owner1D_ protected
Owner addressing.
Definition at line 115 of file columnFvMesh.H.
labelList neighbour1D_ protected
Neighbour addressing.
Definition at line 120 of file columnFvMesh.H.
dictionary patchEntries_ protected
Dictionary of patch information.
Definition at line 128 of file columnFvMesh.H.
label nPatchWithFace_ protected
Number of patches with at least 1 local face.
Definition at line 133 of file columnFvMesh.H.
The documentation for this class was generated from the following files:
src/finiteVolume/fvMesh/simplifiedFvMesh/columnFvMesh/columnFvMesh.H
src/finiteVolume/fvMesh/simplifiedFvMesh/columnFvMesh/columnFvMesh.C
src/finiteVolume/fvMesh/simplifiedFvMesh/columnFvMesh/columnFvMeshTemplates.C