OpenFOAM: LPtrList< LListBase, T > Class Template Reference
LPtrList< LListBase, T > Class Template Reference
Template class for non-intrusive linked PtrLists.
Classes
class const_iterator
An STL-conforming const_iterator.
class const_reverse_iterator
A const_reverse_iterator, for base classes that support reverse iteration.
class iterator
An STL-conforming iterator.
class reverse_iterator
A reverse_iterator, for base classes that support reverse iteration.
Public Types
typedef T * pointer
Pointer for LPtrList::value_type objects.
typedef const T * const_pointer
Const pointer for LPtrList::value_type objects.
typedef T & reference
Reference for LPtrList::value_type objects.
typedef const T & const_reference
Const reference for LPtrList::value_type objects.
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
typedef LList< LListBase, T * > parent_type
The parent list storage.
Public Types inherited from LList< LListBase, T * >
typedef T * value_type
Type of values stored.
typedef T ** pointer
Pointer for value_type.
typedef const T ** const_pointer
Const pointer for value_type.
typedef T *& reference
Reference for value_type.
typedef const T *& const_reference
Const reference for value_type.
typedef label size_type
The type that can represent the container size.
typedef label difference_type
The difference between iterator objects.
using base_iterator = typename LListBase::iterator
using const_base_iterator = typename LListBase::const_iterator
Public Member Functions
LPtrList ()=default
Null construct.
LPtrList (T *item)
Construct and insert the initial T item.
LPtrList (const LPtrList &lst)
Copy construct by using 'clone()' for each element.
LPtrList (LPtrList &&lst)
Move construct.
template<class INew >
LPtrList (Istream &is, const INew &inew)
Construct from Istream using given Istream constructor class.
LPtrList (Istream &is)
Construct from Istream using default Istream constructor class.
~LPtrList ()
Destructor.
T & first ()
The first entry in the list.
const T & first () const
The first entry in the list (const access)
T & last ()
The last entry in the list.
const T & last () const
The last entry in the list (const access)
bool eraseHead ()
Remove the head element from the list and delete the pointer.
void clear ()
Clear the contents of the list.
void transfer (LPtrList< LListBase, T > &lst)
Transfer the contents of the argument into this List and annul the argument list.
void operator= (const LPtrList< LListBase, T > &lst)
Copy assign by using 'clone()' for each element.
void operator= (LPtrList< LListBase, T > &&lst)
Move assign.
iterator begin ()
Iterator to first item in list with non-const access.
const_iterator cbegin () const
Iterator to first item in list with const access.
reverse_iterator rbegin ()
Iterator to last item in list with non-const access.
const_reverse_iterator crbegin () const
Iterator to last item in list with const access.
const_iterator begin () const
Iterator to first item in list with const access.
const_reverse_iterator rbegin () const
Iterator to last item in list with const access.
const iterator & end ()
End of list for forward iterators.
const const_iterator & cend () const
End of list for forward iterators.
const reverse_iterator & rend ()
End of list for reverse iterators.
const const_reverse_iterator & crend () const
End of list for reverse iterators.
const const_iterator & end () const
End of list for forward iterators.
const const_reverse_iterator & rend () const
End of list for reverse iterators.
Public Member Functions inherited from LList< LListBase, T * >
LList ()=default
Null construct.
LList (const T *&item)
Construct and copy insert the initial T item.
LList (T *&&item)
Construct and move insert the initial T item.
LList (Istream &is)
Construct from Istream.
LList (const LList< LListBase, T * > &lst)
Copy construct.
LList (LList< LListBase, T * > &&lst)
Move construct.
LList (std::initializer_list< T * > lst)
Copy construct from an initializer list.
~LList ()
Destructor.
reference first ()
The first entry in the list.
const_reference first () const
The first entry in the list (const access)
reference last ()
The last entry in the list.
const_reference last () const
The last entry in the list (const access)
void insert (const T *&item)
Add copy at head of list.
void insert (T *&&item)
Move construct at head of list.
void append (const T *&item)
Add copy at tail of list.
void append (T *&&item)
Move construct at tail of list.
T * removeHead ()
Remove and return head.
T * remove (link *item)
Remove and return element.
T * remove (iterator &iter)
Remove and return element specified by iterator.
void clear ()
Delete contents of list.
void transfer (LList< LListBase, T * > &lst)
Transfer the contents of the argument into this List.
void operator= (const LList< LListBase, T * > &lst)
Copy assignment.
void operator= (LList< LListBase, T * > &&lst)
Move assignment.
void operator= (std::initializer_list< T * > lst)
Copy assignment from an initializer list.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write LList with line-breaks when length exceeds shortLen.
iterator begin ()
Iterator to first item in list with non-const access.
const_iterator begin () const
Iterator to first item in list with const access.
const_iterator cbegin () const
Iterator to first item in list with const access.
reverse_iterator rbegin ()
Iterator to last item in list with non-const access.
const_reverse_iterator rbegin () const
Iterator to last item in list with const access.
const_reverse_iterator crbegin () const
Iterator to last item in list with const access.
const iterator & end ()
End of list for forward iterators.
const const_iterator & end () const
End of list for forward iterators.
const const_iterator & cend () const
End of list for forward iterators.
const reverse_iterator & rend ()
End of list for reverse iterators.
const const_reverse_iterator & rend () const
End of list for reverse iterators.
const const_reverse_iterator & crend () const
End of list for reverse iterators.
Friends
Istream & operator>> (Istream &is, LPtrList< LListBase, T > &list)
Ostream & operator (Ostream &os, const LPtrList< LListBase, T > &list)
Detailed Description
template<class LListBase, class T>
class Foam::LPtrList< LListBase, T >
Template class for non-intrusive linked PtrLists.
Source files
LPtrList.H
LPtrList.C
LPtrListIO.C
Definition at line 46 of file LPtrList.H.
Member Typedef Documentation
typedef T* pointer
Pointer for LPtrList::value_type objects.
Definition at line 90 of file LPtrList.H.
typedef const T* const_pointer
Const pointer for LPtrList::value_type objects.
Definition at line 95 of file LPtrList.H.
typedef T& reference
Reference for LPtrList::value_type objects.
Definition at line 100 of file LPtrList.H.
typedef const T& const_reference
Const reference for LPtrList::value_type objects.
Definition at line 105 of file LPtrList.H.
using base_iterator = typename LListBase::iterator
Definition at line 113 of file LPtrList.H.
using const_base_iterator = typename LListBase::const_iterator
Definition at line 114 of file LPtrList.H.
typedef LList<LListBase, T*> parent_type
The parent list storage.
Definition at line 119 of file LPtrList.H.
Constructor & Destructor Documentation
LPtrList () default
Null construct.
LPtrList (T * item) inline explicit
Construct and insert the initial T item.
Definition at line 132 of file LPtrList.H.
LPtrList (const LPtrList< LListBase, T > & lst)
Copy construct by using 'clone()' for each element.
LPtrList (LPtrList< LListBase, T > && lst)
Move construct.
LPtrList (Istream & is, const INew & inew)
Construct from Istream using given Istream constructor class.
Definition at line 130 of file LPtrListIO.C.
LPtrList (Istream & is)
Construct from Istream using default Istream constructor class.
Definition at line 137 of file LPtrListIO.C.
~LPtrList ()
Destructor.
Definition at line 49 of file LPtrList.C.
Member Function Documentation
T& first () inline
The first entry in the list.
Definition at line 170 of file LPtrList.H.
const T& first () const inline
The first entry in the list (const access)
Definition at line 178 of file LPtrList.H.
T& last () inline
The last entry in the list.
Definition at line 186 of file LPtrList.H.
const T& last () const inline
The last entry in the list (const access)
Definition at line 194 of file LPtrList.H.
References iter, LPtrList< LListBase, T >::iterator::iterator(), LPtrList< LListBase, T >::iterator::operator()(), LPtrList< LListBase, T >::iterator::operator*(), Foam::operator*(), and LPtrList< LListBase, T >::iterator::operator->().
bool eraseHead ()
Remove the head element from the list and delete the pointer.
Definition at line 58 of file LPtrList.C.
void clear ()
Clear the contents of the list.
Definition at line 73 of file LPtrList.C.
void transfer (LPtrList< LListBase, T > & lst)
Transfer the contents of the argument into this List and annul the argument list.
Definition at line 86 of file LPtrList.C.
void operator= (const LPtrList< LListBase, T > & lst)
Copy assign by using 'clone()' for each element.
Definition at line 96 of file LPtrList.C.
void operator= (LPtrList< LListBase, T > && lst)
Move assign.
Definition at line 108 of file LPtrList.C.
References append().
iterator begin () inline
Iterator to first item in list with non-const access.
Definition at line 404 of file LPtrList.H.
const_iterator cbegin () const inline
Iterator to first item in list with const access.
Definition at line 412 of file LPtrList.H.
References LPtrList< LListBase, T >::crend().
reverse_iterator rbegin () inline
Iterator to last item in list with non-const access.
Definition at line 420 of file LPtrList.H.
const_reverse_iterator crbegin () const inline
Iterator to last item in list with const access.
Definition at line 428 of file LPtrList.H.
const_iterator begin () const inline
Iterator to first item in list with const access.
Definition at line 436 of file LPtrList.H.
const_reverse_iterator rbegin () const inline
Iterator to last item in list with const access.
Definition at line 444 of file LPtrList.H.
const iterator& end () inline
End of list for forward iterators.
Definition at line 453 of file LPtrList.H.
const const_iterator& cend () const inline
End of list for forward iterators.
Definition at line 461 of file LPtrList.H.
const reverse_iterator& rend () inline
End of list for reverse iterators.
Definition at line 469 of file LPtrList.H.
const const_reverse_iterator& crend () const inline
End of list for reverse iterators.
Definition at line 477 of file LPtrList.H.
Referenced by LPtrList< LListBase, T >::cbegin().
const const_iterator& end () const inline
End of list for forward iterators.
Definition at line 485 of file LPtrList.H.
const const_reverse_iterator& rend () const inline
End of list for reverse iterators.
Definition at line 493 of file LPtrList.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & is, LPtrList< LListBase, T > & list) friend
Ostream& operator (Ostream & os, const LPtrList< LListBase, T > & list) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrList.H
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrList.C
src/OpenFOAM/containers/LinkedLists/accessTypes/LPtrList/LPtrListIO.C