OpenFOAM: internalWriter Class Reference
internalWriter Class Reference
Write an OpenFOAM volume (internal) geometry and internal fields as a vtu file or a legacy vtk file.
Public Member Functions
internalWriter (const fvMesh &mesh, const vtk::vtuCells &cells, const vtk::outputOptions opts=vtk::formatType::INLINE_BASE64)
File extension for given output type.
internalWriter (const fvMesh &mesh, const vtk::vtuCells &cells, const fileName &file, bool parallel=Pstream::parRun())
Construct from components (default format INLINE_BASE64),.
internalWriter (const fvMesh &mesh, const vtk::vtuCells &cells, const vtk::outputOptions opts, const fileName &file, bool parallel=Pstream::parRun())
Construct from components (default format INLINE_BASE64),.
virtual ~internalWriter ()=default
Destructor.
virtual bool beginFile (std::string title="")
Write file header (non-collective)
virtual bool writeGeometry ()
Write mesh topology.
virtual bool beginCellData (label nFields=0)
Begin CellData output section for specified number of fields.
virtual bool beginPointData (label nFields=0)
Begin PointData for specified number of fields.
void writeCellIDs ()
Write cell ids as CellData.
bool writeProcIDs ()
Write processor ids as CellData. This is no-op in serial.
void writePointIDs ()
Write point ids as PointData.
template<class Type >
void writeUniform (const word &fieldName, const Type &val)
Write a uniform field of Cell or Point values.
template<class Type , template< class > class PatchField>
void write (const GeometricField< Type, PatchField, pointMesh > &field)
Write point field.
template<class Type >
void write (const DimensionedField< Type, volMesh > &field)
Write the internal field.
template<class Type , template< class > class PatchField>
void write (const GeometricField< Type, PatchField, volMesh > &field)
Write the volume field (internal part)
template<class Type >
void write (const DimensionedField< Type, volMesh > &vfield, const volPointInterpolation &pInterp)
Write internal field with point interpolation.
template<class Type >
void write (const GeometricField< Type, fvPatchField, volMesh > &vfield, const volPointInterpolation &pInterp)
Write volume field with point interpolation.
Public Member Functions inherited from fileWriter
fileWriter (const vtk::fileTag contentType, const vtk::outputOptions opts)
Construct from components.
virtual ~fileWriter ()
Destructor.
vtk::fileTag contentType () const
The content type.
vtk::outputOptions opts () const
The output options in use.
word ext () const
File extension for current format type.
bool legacy () const
Commonly used query.
bool parallel () const
Parallel output requested?
const word & state () const
The output state in printable format.
const fileName & output () const
The current output file name.
bool open (const fileName &file, bool parallel=Pstream::parRun())
Open file for writing (creates parent directory).
void close ()
End the file contents and close the file after writing.
bool beginFieldData (label nFields=0)
Begin FieldData output section for specified number of fields.
label nCellData () const
Return the number of CellData written for the Piece thus far.
label nPointData () const
Return the number of PointData written for the Piece thus far.
bool endFieldData ()
Explicitly end FieldData output and switch to DECLARED state.
bool endCellData ()
Explicitly end CellData output and switch to PIECE state.
bool endPointData ()
Explicitly end PointData output and switch to PIECE state.
void writeTimeValue (scalar timeValue)
Write "TimeValue" FieldData (name as per Catalyst output)
Static Public Member Functions
static word ext (vtk::outputOptions opts)
File extension for given output type.
Static Public Attributes
static int debug = 0
Debug information.
Additional Inherited Members
Protected Types inherited from fileWriter
enum outputState {
CLOSED = 0, OPENED, DECLARED, FIELD_DATA,
PIECE, CELL_DATA, POINT_DATA
}
Internal tracking of the output state.
Protected Member Functions inherited from fileWriter
std::ofstream & os ()
The backend ostream in use.
vtk::formatter & format ()
The VTK formatter in use.
bool isState (outputState test) const
True if the output state corresponds to the test state.
bool notState (outputState test) const
True if the output state does not correspond to the test state.
template<class Type >
void writeUniform (const word &fieldName, const Type &val, const label nValues)
Write uniform field content.
bool enter_Piece ()
Trigger change state to Piece. Resets nCellData_, nPointData_.
bool endPiece ()
Explicitly end Piece output and switch to DECLARED state.
bool enter_CellData (label nEntries, label nFields)
Trigger change state to CellData.
bool enter_PointData (label nEntries, label nFields)
Trigger change state to PointData.
bool exit_File ()
Emit file footer (end data, end piece, end file)
fileWriter (const fileWriter &)=delete
No copy construct.
void operator= (const fileWriter &)=delete
No copy assignment.
Protected Attributes inherited from fileWriter
vtk::fileTag contentType_
The content type.
outputOptions opts_
The requested output options.
bool parallel_
Writing in parallel (via master)
outputState state_
The output state.
label nCellData_
The number of CellData written for the Piece thus far.
label nPointData_
The number of PointData written for the Piece thus far.
fileName outputFile_
The output file name.
autoPtr< vtk::formatter > format_
The VTK formatter in use (master process)
std::ofstream os_
The backend ostream in use (master process)
Static Protected Attributes inherited from fileWriter
static const Enum< outputState > stateNames
Names for the output state (for messages, not for file output).
Detailed Description
Write an OpenFOAM volume (internal) geometry and internal fields as a vtu file or a legacy vtk file.
The file output states are managed by the Foam::vtk::fileWriter class. FieldData (eg, TimeValue) must appear before any geometry pieces.
Note
Parallel output is combined into a single Piece without point merging, which is similar to using multi-piece data sets, but allows more convenient creation as a streaming process. In the future, the duplicate points at processor connections may be addressed using ghost points.
Source files
foamVtkInternalWriter.H
foamVtkInternalWriter.C
foamVtkInternalWriterTemplates.C
Definition at line 67 of file foamVtkInternalWriter.H.
Constructor & Destructor Documentation
internalWriter (const fvMesh & mesh, const vtk::vtuCells & cells, const vtk::outputOptions opts = vtk::formatType::INLINE_BASE64)
File extension for given output type.
constexpr static vtk::fileTag content = vtk::fileTag::UNSTRUCTURED_GRID;
Construct from components (default format INLINE_BASE64),
Definition at line 473 of file foamVtkInternalWriter.C.
internalWriter (const fvMesh & mesh, const vtk::vtuCells & cells, const fileName & file, bool parallel = Pstream::parRun())
Construct from components (default format INLINE_BASE64),.
The file name is with/without an extension.
Definition at line 491 of file foamVtkInternalWriter.C.
internalWriter (const fvMesh & mesh, const vtk::vtuCells & cells, const vtk::outputOptions opts, const fileName & file, bool parallel = Pstream::parRun())
Construct from components (default format INLINE_BASE64),.
The file name is with/without an extension.
Definition at line 505 of file foamVtkInternalWriter.C.
virtual ~internalWriter () virtual default
Destructor.
Member Function Documentation
static word ext (vtk::outputOptions opts) inline static
File extension for given output type.
Definition at line 209 of file foamVtkInternalWriter.H.
bool beginFile (std::string title = "") virtual
Write file header (non-collective)
Note
Expected calling states: (OPENED)
Reimplemented from fileWriter.
Definition at line 521 of file foamVtkInternalWriter.C.
bool writeGeometry () virtual
Write mesh topology.
Also writes the file header if not previously written.
Note
Must be called prior to writing CellData or PointData
Implements fileWriter.
Definition at line 559 of file foamVtkInternalWriter.C.
bool beginCellData (label nFields = 0) virtual
Begin CellData output section for specified number of fields.
Must be called prior to writing any cell data fields.
Parameters
nFields is for legacy format only. When nFields=0, this a no-op for legacy format.
Note
Expected calling states: (PIECE | POINT_DATA).
Returns
True if the state changed
Implements fileWriter.
Definition at line 596 of file foamVtkInternalWriter.C.
bool beginPointData (label nFields = 0) virtual
Begin PointData for specified number of fields.
Must be called prior to writing any point data fields.
Parameters
nFields is for legacy format only. When nFields=0, this a no-op for legacy format.
Note
Expected calling states: (PIECE | CELL_DATA).
Returns
True if the state changed
Implements fileWriter.
Definition at line 602 of file foamVtkInternalWriter.C.
void writeCellIDs ()
Write cell ids as CellData.
Must be called within the CELL_DATA state.
Definition at line 608 of file foamVtkInternalWriter.C.
bool writeProcIDs ()
Write processor ids as CellData. This is no-op in serial.
Must be called within the CELL_DATA state.
Definition at line 661 of file foamVtkInternalWriter.C.
References format().
void writePointIDs ()
Write point ids as PointData.
Must be called within the POINT_DATA state.
Definition at line 723 of file foamVtkInternalWriter.C.
void writeUniform (const word & fieldName, const Type & val)
Write a uniform field of Cell or Point values.
Definition at line 30 of file foamVtkInternalWriterTemplates.C.
References Foam::vtk::CELL_DATA, Foam::endl(), fileWriter::isState(), fileWriter::nCellData_, Foam::nl, fileWriter::nPointData_, Foam::vtk::POINT_DATA, fileWriter::state_, fileWriter::stateNames, Foam::val, and WarningInFunction.
void write (const GeometricField< Type, PatchField, pointMesh > & field)
Write point field.
Interpolate to originating cell centre for decomposed cells.
Definition at line 57 of file foamVtkInternalWriterTemplates.C.
Referenced by Foam::writeDimField(), Foam::writePointField(), and Foam::writeVolField().
void write (const DimensionedField< Type, volMesh > & field)
Write the internal field.
Definition at line 127 of file foamVtkInternalWriterTemplates.C.
void write (const GeometricField< Type, PatchField, volMesh > & field)
Write the volume field (internal part)
Definition at line 183 of file foamVtkInternalWriterTemplates.C.
void write (const DimensionedField< Type, volMesh > & vfield, const volPointInterpolation & pInterp)
Write internal field with point interpolation.
Definition at line 193 of file foamVtkInternalWriterTemplates.C.
References GeometricField< Type, PatchField, GeoMesh >::internalField(), and Foam::vtk::write().
void write (const GeometricField< Type, fvPatchField, volMesh > & vfield, const volPointInterpolation & pInterp)
Write volume field with point interpolation.
Definition at line 262 of file foamVtkInternalWriterTemplates.C.
Member Data Documentation
int debug = 0 static
Debug information.
Definition at line 144 of file foamVtkInternalWriter.H.
The documentation for this class was generated from the following files:
src/conversion/vtk/output/foamVtkInternalWriter.H
src/conversion/vtk/output/foamVtkInternalWriter.C
src/conversion/vtk/output/foamVtkInternalWriterTemplates.C