OpenFOAM: DRGEP< CompType, ThermoType > Class Template Reference
DRGEP< CompType, ThermoType > Class Template Reference
The DRGEP algorithm [1] is based on.
Public Member Functions
TypeName ("DRGEP")
Runtime type information.
DRGEP (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~DRGEP ()
Destructor.
virtual void reduceMechanism (const scalarField &c, const scalar T, const scalar p)
Reduce the mechanism.
Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
TypeName ("chemistryReductionMethod")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, chemistryReductionMethod, dictionary,(const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry),(dict, chemistry))
chemistryReductionMethod (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Construct from components.
virtual ~chemistryReductionMethod ()
Destructor.
bool active () const
Is mechanism reduction active?
bool log () const
Is performance data logging enabled?
const List< bool > & activeSpecies () const
Return the active species.
label NsSimp ()
Return the number of active species.
label nSpecie ()
Return the initial number of species.
scalar tolerance () const
Return the tolerance.
Additional Inherited Members
Static Public Member Functions inherited from chemistryReductionMethod< CompType, ThermoType >
static autoPtr
< chemistryReductionMethod
< CompType, ThermoType > > New (const IOdictionary &dict, TDACChemistryModel< CompType, ThermoType > &chemistry)
Protected Attributes inherited from chemistryReductionMethod< CompType, ThermoType >
const IOdictionary & dict_
const dictionary coeffsDict_
Dictionary that store the algorithm data.
Switch active_
Is mechanism reduction active?
Switch log_
Switch to select performance logging.
TDACChemistryModel< CompType,
ThermoType > & chemistry_
List< bool > activeSpecies_
List of active species (active = true)
label NsSimp_
Number of active species.
const label nSpecie_
Number of species.
scalar tolerance_
Tolerance for the mechanism reduction algorithm.
Detailed Description
template<class CompType, class ThermoType>
class Foam::chemistryReductionMethods::DRGEP< CompType, ThermoType >
The DRGEP algorithm [1] is based on.
|sum_i=1->Nr vAi wi dBi| rAB = ————————— , max(PA, CA)
PA = sum_i=1->Nr (max (0, vAi wi)) -> production of species A
CA = sum_i=1->Nr (max (0, -vAi wi)) -> consumption of species A
where i is the reaction index, Nr the number of reactions, vAi is the net stoechiometric coefficient of species A in the ith reaction (vAi = v''-v') , wi is the progress variable of reaction i and dBi equals 1 if reaction i involves B and O otherwise. rAB show the error introduced to the production rates of A when B and all the reactions including it are removed. It is computed as in [2] so that the algorithm is O(Nr).
DAC uses a initial set of species that represents the major parts of the combustion mechanism, i.e. H2/O2, fuel decomposition and CO2 production. Usualy, it includes the fuel, HO2 and CO. Then it computes the dependance of these set to the other species. This is done by introducing R-value defined by
R_V0 (V) = max_SP(product(rij)) ,
where SP is the set of all possible paths leading from V0 to V and product(rij) is the chain product of the weights of the edges along the given path. The R-value for the initial set species is 1.
When the R-value of a species is larger than a user-defined tolerance then the species is included in the simplified mechanism. Otherwise, the species is removed along with all the reactions including it.
During this process, instead of looking over all species like described in [1], the algorithm implemented here creates dynamic list to retain the initialized edges only (see [2]).
To avoid using the target species when they are not contributing yet or anymore to the system, a coefficient based on the exchange of element is introduced:
NTa |PT - CT| alphaTa = —————- Pa
Pa = sum_speciesS NSa max(0, PS-CS)
where 'a' refers to different elements present in the system (namely C, H, O and N for conventionail hydrocarbon combustion), NTa is the number of element a in species T. When this coefficient alpha is below the specified threshold, the species is removed from the search initiating set. In the original paper from Pepiot-Desjardins et al.[2], this coefficient is further transformed to compute a global normalized scaling coefficient but here as it is dynamicly computed, alpha is not introduced in the calculation of R.
References:
    [1] Pepiot-Desjardins, P., & Pitsch, H. (2008).
    An efficient error-propagation-based reduction method for large
    chemical kinetic mechanisms.
    Combustion and Flame, 154(1), 67-81.
    [2] Lu, T., & Law, C. K. (2006).
    Linear time reduction of large kinetic mechanisms with directed
    relation graph: n-Heptane and iso-octane.
    Combustion and Flame, 144(1), 24-36.
Source files
DRGEP.H
DRGEP.C
Definition at line 117 of file DRGEP.H.
Constructor & Destructor Documentation
DRGEP (const IOdictionary & dict, TDACChemistryModel< CompType, ThermoType > & chemistry)
Construct from components.
Definition at line 28 of file DRGEP.C.
References chemistryReductionMethod< CompType, ThermoType >::chemistry_, chemistryReductionMethod< CompType, ThermoType >::coeffsDict_, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInFunction, dictionary::found(), i, Foam::Info, j, StandardChemistryModel< ReactionThermo, ThermoType >::nSpecie(), chemistryReductionMethod< CompType, ThermoType >::nSpecie_, dictionary::readIfPresent(), UList< T >::size(), dictionary::subDict(), and TDACChemistryModel< CompType, ThermoType >::Y().
~DRGEP () virtual
Destructor.
Definition at line 99 of file DRGEP.C.
Member Function Documentation
TypeName ("DRGEP< CompType, ThermoType >")
Runtime type information.
void reduceMechanism (const scalarField & c, const scalar T, const scalar p) virtual
Reduce the mechanism.
Implements chemistryReductionMethod< CompType, ThermoType >.
Definition at line 108 of file DRGEP.C.
References Foam::constant::physicoChemical::c1, forAll, found, i, SortableListDRGEP< Type >::indices(), j, Reaction< ReactionThermo >::lhs(), Foam::mag(), Foam::max(), p, SortableListDRGEP< Type >::partialSort(), FIFOStack< T >::pop(), FIFOStack< T >::push(), R, Reaction< ReactionThermo >::rhs(), s, DynamicList< T, SizeMin >::setSize(), List< T >::setSize(), UList< T >::size(), Foam::T(), and Foam::Zero.
The documentation for this class was generated from the following files:
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/DRGEP/DRGEP.H
src/thermophysicalModels/chemistryModel/chemistryModel/TDACChemistryModel/reduction/DRGEP/DRGEP.C