OpenFOAM: spatialTransform Class Reference
spatialTransform Class Reference
Compact representation of the Plücker spatial transformation tensor in terms of the rotation tensor E and translation vector r .
Classes
class dual
Wrapper-class to provide dual functions and operators.
class transpose
Wrapper-class to provide transpose functions and operators.
Public Member Functions
spatialTransform ()
Construct null.
spatialTransform (const tensor &E, const vector &r)
Construct from components.
spatialTransform (Istream &)
Construct from Istream.
const tensor & E () const
Return the rotation tensor.
tensor & E ()
Return non-const access to the rotation tensor.
const vector & r () const
Return the translation vector.
vector & r ()
Return non-const access to the translation vector.
transpose T () const
Return the transpose transformation tensor ^A{X^*}_B.
spatialTransform inv () const
Return the inverse transformation tensor: X^-1.
dual operator* () const
Return the dual transformation tensor ^B{X^*}_A.
operator spatialTensor () const
Return transformation tensor ^BX_A.
void operator&= (const spatialTransform &X)
Inner-product multiply with a transformation tensor.
spatialTransform operator& (const spatialTransform &X) const
Return the inner-product of two transformation tensors.
spatialVector operator& (const spatialVector &v) const
Transform v: ^BX_A . v.
vector transformPoint (const vector &p) const
Transform position p.
spatialVector operator&& (const spatialVector &v) const
Transform position p.
Friends
Istream & operator>> (Istream &, spatialTransform &)
Ostream & operator<< (Ostream &, const spatialTransform &)
Detailed Description
Compact representation of the Plücker spatial transformation tensor in terms of the rotation tensor E and translation vector r .
See Chapter 2 and Appendix A in reference:
    Featherstone, R. (2008).
    Rigid body dynamics algorithms.
    Springer.
Source files
spatialTransform.H
spatialTransformI.H
Definition at line 66 of file spatialTransform.H.
Constructor & Destructor Documentation
spatialTransform () inline
Construct null.
Definition at line 33 of file spatialTransformI.H.
Referenced by spatialTransform::operator&(), spatialTransform::operator*(), Foam::Xr(), Foam::Xrx(), and Foam::Xrz().
spatialTransform (const tensor & E, const vector & r) inline
Construct from components.
Definition at line 41 of file spatialTransformI.H.
spatialTransform (Istream & is) inline
Construct from Istream.
Definition at line 51 of file spatialTransformI.H.
Member Function Documentation
const Foam::tensor & E () const inline
Return the rotation tensor.
Definition at line 72 of file spatialTransformI.H.
Referenced by Foam::RBD::transform().
Foam::tensor & E () inline
Return non-const access to the rotation tensor.
Definition at line 77 of file spatialTransformI.H.
const Foam::vector & r () const inline
Return the translation vector.
Definition at line 82 of file spatialTransformI.H.
Referenced by Foam::RBD::transform().
Foam::vector & r () inline
Return non-const access to the translation vector.
Definition at line 87 of file spatialTransformI.H.
Foam::spatialTransform::transpose T () const inline
Return the transpose transformation tensor ^A{X^*}_B.
X^T
Definition at line 93 of file spatialTransformI.H.
Foam::spatialTransform inv () const inline
Return the inverse transformation tensor: X^-1.
X^-1 = (E^T, −E.r)
Definition at line 99 of file spatialTransformI.H.
Referenced by restraint::bodyPointVelocity().
Foam::spatialTransform::dual operator* () const inline
Return the dual transformation tensor ^B{X^*}_A.
Definition at line 107 of file spatialTransformI.H.
References spatialTransform::spatialTransform(), and Tensor< Cmpt >::T().
operator spatialTensor () const inline
Return transformation tensor ^BX_A.
X
Definition at line 113 of file spatialTransformI.H.
void operator&= (const spatialTransform & X) inline
Inner-product multiply with a transformation tensor.
Definition at line 123 of file spatialTransformI.H.
Foam::spatialTransform operator& (const spatialTransform & X) const inline
Return the inner-product of two transformation tensors.
Definition at line 131 of file spatialTransformI.H.
Foam::spatialVector operator& (const spatialVector & v) const inline
Transform v: ^BX_A . v.
X.v = (E . vw, E . (vl - r^vw))
Definition at line 140 of file spatialTransformI.H.
References spatialTransform::spatialTransform().
Foam::vector transformPoint (const vector & p) const inline
Transform position p.
X:p = E . (pl - r)
Definition at line 166 of file spatialTransformI.H.
Foam::spatialVector operator&& (const spatialVector & v) const inline
Transform position p.
X:p = (E . pw, E . (vl - r))
Definition at line 153 of file spatialTransformI.H.
Friends And Related Function Documentation
Istream& operator>> (Istream & , spatialTransform &) friend
Ostream& operator<< (Ostream & , const spatialTransform &) friend
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransform.H
src/OpenFOAM/primitives/spatialVectorAlgebra/spatialTransform/spatialTransformI.H