OpenFOAM: nucleationSiteModel Class Reference
nucleationSiteModel Class Reference abstract
Base class for nucleation site density models.
Public Member Functions
TypeName ("nucleationSiteModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, nucleationSiteModel, dictionary,(const dictionary &dict),(dict))
Declare runtime construction.
nucleationSiteModel ()
Construct null.
virtual ~nucleationSiteModel ()
Destructor.
virtual tmp< scalarField > N (const phaseModel &liquid, const phaseModel &vapor, const label patchi, const scalarField &Tl, const scalarField &Tsatw, const scalarField &L) const =0
Calculate and return the nucleation-site density.
virtual void write (Ostream &os) const
Static Public Member Functions
static autoPtr
< nucleationSiteModel > New (const dictionary &dict)
Select null constructed.
Detailed Description
Base class for nucleation site density models.
Source files
nucleationSiteModel.H
nucleationSiteModel.C
newnucleationSiteModel.C
Definition at line 53 of file nucleationSiteModel.H.
Constructor & Destructor Documentation
nucleationSiteModel ()
Construct null.
Definition at line 37 of file nucleationSiteModel.C.
~nucleationSiteModel () virtual
Destructor.
Definition at line 43 of file nucleationSiteModel.C.
Member Function Documentation
TypeName ("nucleationSiteModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , nucleationSiteModel , dictionary , (const dictionary &dict) , (dict))
Declare runtime construction.
Foam::autoPtr< Foam::wallBoilingModels::nucleationSiteModel > New (const dictionary & dict) static
Select null constructed.
Definition at line 28 of file newNucleationSiteModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<scalarField> N (const phaseModel & liquid, const phaseModel & vapor, const label patchi, const scalarField & Tl, const scalarField & Tsatw, const scalarField & L) const pure virtual
Calculate and return the nucleation-site density.
Implemented in LemmertChawla.
void write (Ostream & os) const virtual
Definition at line 49 of file nucleationSiteModel.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/nucleationSiteModels/nucleationSiteModel/nucleationSiteModel.H
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/nucleationSiteModels/nucleationSiteModel/newNucleationSiteModel.C
src/phaseSystemModels/reactingEulerFoam/derivedFvPatchFields/wallBoilingSubModels/nucleationSiteModels/nucleationSiteModel/nucleationSiteModel.C