OpenFOAM: specie Class Reference
specie Class Reference
Base class of the thermophysical property types.
Public Member Functions
ClassName ("specie")
Runtime type information.
specie (const scalar Y, const scalar molWeight)
Construct from components without name.
specie (const word &name, const scalar Y, const scalar molWeight)
Construct from components with name.
specie (const word &name, const specie &)
Construct as named copy.
specie (const dictionary &dict)
Construct from dictionary.
const word & name () const
Name.
scalar W () const
Molecular weight [kg/kmol].
scalar Y () const
No of moles of this species in mixture.
scalar R () const
Gas constant [J/(kg K)].
void write (Ostream &os) const
Write to Ostream.
void operator= (const specie &)
void operator+= (const specie &)
void operator*= (const scalar)
Friends
specie operator+ (const specie &, const specie &)
specie operator* (const scalar, const specie &)
specie operator== (const specie &, const specie &)
Ostream & operator<< (Ostream &, const specie &)
Detailed Description
Base class of the thermophysical property types.
Source files
specie.H
specieI.H
specie.C
Definition at line 63 of file specie.H.
Constructor & Destructor Documentation
specie (const scalar Y, const scalar molWeight) inline
Construct from components without name.
Definition at line 44 of file specieI.H.
Referenced by specie::specie().
specie (const word & name, const scalar Y, const scalar molWeight) inline
Construct from components with name.
Definition at line 31 of file specieI.H.
References Foam::name(), specie::specie(), and Y.
specie (const word & name, const specie & st) inline
Construct as named copy.
Definition at line 56 of file specieI.H.
specie (const dictionary & dict)
Construct from dictionary.
Definition at line 34 of file specie.C.
References Foam::defineTypeNameAndDebug().
Member Function Documentation
ClassName ("specie")
Runtime type information.
const word & name () const inline
Name.
Definition at line 66 of file specieI.H.
scalar W () const inline
Molecular weight [kg/kmol].
Definition at line 72 of file specieI.H.
scalar Y () const inline
No of moles of this species in mixture.
Definition at line 78 of file specieI.H.
scalar R () const inline
Gas constant [J/(kg K)].
Definition at line 84 of file specieI.H.
void write (Ostream & os) const
Write to Ostream.
Definition at line 44 of file specie.C.
void operator= (const specie & st) inline
Definition at line 92 of file specieI.H.
References Foam::constant::thermodynamic::RR.
void operator+= (const specie & st) inline
Definition at line 100 of file specieI.H.
void operator*= (const scalar s) inline
Definition at line 112 of file specieI.H.
Friends And Related Function Documentation
specie operator+ (const specie & st1, const specie & st2) friend
specie operator* (const scalar s, const specie & st) friend
specie operator== (const specie & st1, const specie & st2) friend
Ostream& operator<< (Ostream & , const specie &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/specie/specie.H
src/thermophysicalModels/specie/specie/specie.C
src/thermophysicalModels/specie/specie/specieI.H