OpenFOAM: meshToMeshMethod Class Reference
meshToMeshMethod Class Reference abstract
Base class for mesh-to-mesh calculation methods.
Public Member Functions
TypeName ("meshToMeshMethod")
Run-time type information.
declareRunTimeSelectionTable (autoPtr, meshToMeshMethod, components,(const polyMesh &src, const polyMesh &tgt),(src, tgt))
Declare runtime constructor selection table.
meshToMeshMethod (const polyMesh &src, const polyMesh &tgt)
Construct from source and target meshes.
virtual ~meshToMeshMethod ()
Destructor.
virtual void calculate (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, pointListList &srcToTgtVec, labelListList &tgtToSrcAddr, scalarListList &tgtToSrcWght, pointListList &tgtToSrcVec)=0
Calculate addressing and weights and optionally offset vectors.
const polyMesh & src () const
Return const access to the source mesh.
const polyMesh & tgt () const
Return const access to the target mesh.
scalar V () const
Return const access to the overlap volume.
void writeConnectivity (const polyMesh &mesh1, const polyMesh &mesh2, const labelListList &mesh1ToMesh2Addr) const
Write the connectivity (debugging)
Static Public Member Functions
static autoPtr< meshToMeshMethod > New (const word &methodName, const polyMesh &src, const polyMesh &tgt)
Selector.
Protected Member Functions
labelList maskCells () const
Return src cell IDs for the overlap region.
virtual bool intersect (const label srcCelli, const label tgtCelli) const
Return the true if cells intersect.
virtual scalar interVol (const label srcCelli, const label tgtCelli) const
Return the intersection volume between two cells.
virtual Tuple2< scalar, point > interVolAndCentroid (const label srcCellI, const label tgtCellI)
Return the intersection volume and centroid between two cells.
virtual void appendNbrCells (const label tgtCelli, const polyMesh &mesh, const DynamicList< label > &visitedTgtCells, DynamicList< label > &nbrTgtCellIDs) const
Append target cell neighbour cells to cellIDs list.
virtual bool initialise (labelListList &srcToTgtAddr, scalarListList &srcToTgtWght, labelListList &tgtToTgtAddr, scalarListList &tgtToTgtWght) const
Protected Attributes
const polyMesh & src_
Reference to the source mesh.
const polyMesh & tgt_
Reference to the target mesh.
scalar V_
Cell total volume in overlap region [m3].
Static Protected Attributes
static scalar tolerance_ = 1e-6
Tolerance used in volume overlap calculations.
Detailed Description
Base class for mesh-to-mesh calculation methods.
Source files
meshToMeshMethod.H
meshToMeshMethod.C
Definition at line 47 of file meshToMeshMethod.H.
Constructor & Destructor Documentation
meshToMeshMethod (const polyMesh & src, const polyMesh & tgt)
Construct from source and target meshes.
Definition at line 237 of file meshToMeshMethod.C.
~meshToMeshMethod () virtual
Destructor.
Definition at line 260 of file meshToMeshMethod.C.
Member Function Documentation
Foam::labelList maskCells () const protected
Return src cell IDs for the overlap region.
Definition at line 40 of file meshToMeshMethod.C.
bool intersect (const label srcCelli, const label tgtCelli) const protected virtual
Return the true if cells intersect.
Reimplemented in directMethod.
Definition at line 74 of file meshToMeshMethod.C.
Foam::scalar interVol (const label srcCelli, const label tgtCelli) const protected virtual
Return the intersection volume between two cells.
Definition at line 105 of file meshToMeshMethod.C.
Foam::Tuple2< Foam::scalar, Foam::point > interVolAndCentroid (const label srcCellI, const label tgtCellI) protected virtual
Return the intersection volume and centroid between two cells.
Definition at line 136 of file meshToMeshMethod.C.
void appendNbrCells (const label tgtCelli, const polyMesh & mesh, const DynamicList< label > & visitedTgtCells, DynamicList< label > & nbrTgtCellIDs) const protected virtual
Append target cell neighbour cells to cellIDs list.
Definition at line 178 of file meshToMeshMethod.C.
bool initialise (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, labelListList & tgtToTgtAddr, scalarListList & tgtToTgtWght) const protected virtual
Definition at line 203 of file meshToMeshMethod.C.
TypeName ("meshToMeshMethod")
Run-time type information.
declareRunTimeSelectionTable (autoPtr , meshToMeshMethod , components , (const polyMesh &src, const polyMesh &tgt) , (src, tgt))
Declare runtime constructor selection table.
Foam::autoPtr< Foam::meshToMeshMethod > New (const word & methodName, const polyMesh & src, const polyMesh & tgt) static
Selector.
Definition at line 27 of file meshToMeshMethodNew.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), Foam::exit(), Foam::FatalError, FatalErrorInLookup, Foam::Info, meshToMeshMethod::src(), and meshToMeshMethod::tgt().
virtual void calculate (labelListList & srcToTgtAddr, scalarListList & srcToTgtWght, pointListList & srcToTgtVec, labelListList & tgtToSrcAddr, scalarListList & tgtToSrcWght, pointListList & tgtToSrcVec) pure virtual
Calculate addressing and weights and optionally offset vectors.
Implemented in mapNearestMethod, directMethod, cellVolumeWeightMethod, correctedCellVolumeWeightMethod, and waveMethod.
const Foam::polyMesh & src () const inline
Return const access to the source mesh.
Definition at line 21 of file meshToMeshMethodI.H.
Referenced by meshToMeshMethod::New().
const Foam::polyMesh & tgt () const inline
Return const access to the target mesh.
Definition at line 27 of file meshToMeshMethodI.H.
References meshToMeshMethod::src_.
Referenced by meshToMeshMethod::New().
Foam::scalar V () const inline
Return const access to the overlap volume.
Definition at line 33 of file meshToMeshMethodI.H.
void writeConnectivity (const polyMesh & mesh1, const polyMesh & mesh2, const labelListList & mesh1ToMesh2Addr) const
Write the connectivity (debugging)
Definition at line 267 of file meshToMeshMethod.C.
Member Data Documentation
const polyMesh& src_ protected
Reference to the source mesh.
Definition at line 57 of file meshToMeshMethod.H.
Referenced by meshToMeshMethod::tgt().
const polyMesh& tgt_ protected
Reference to the target mesh.
Definition at line 62 of file meshToMeshMethod.H.
scalar V_ protected
Cell total volume in overlap region [m3].
Definition at line 67 of file meshToMeshMethod.H.
Foam::scalar tolerance_ = 1e-6 static protected
Tolerance used in volume overlap calculations.
Definition at line 72 of file meshToMeshMethod.H.
The documentation for this class was generated from the following files:
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethod.H
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethod.C
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethodI.H
src/sampling/meshToMesh/calcMethod/meshToMeshMethod/meshToMeshMethodNew.C