OpenFOAM: addwriteNowSignalToOpt Class Reference
addwriteNowSignalToOpt Class Reference
Public Member Functions
addwriteNowSignalToOpt (const addwriteNowSignalToOpt &)=delete
void operator= (const addwriteNowSignalToOpt &)=delete
addwriteNowSignalToOpt (const char *name)
virtual ~addwriteNowSignalToOpt ()=default
virtual void readData (Foam::Istream &is)
Read.
virtual void writeData (Foam::Ostream &os) const
Write.
Public Member Functions inherited from simpleRegIOobject
simpleRegIOobject (void(*fn)(const char *name, simpleRegIOobject *), const char *name)
Construct from objectregistry inserter and name.
virtual ~simpleRegIOobject ()=default
Destructor.
Detailed Description
Definition at line 50 of file sigWriteNow.C.
Constructor & Destructor Documentation
addwriteNowSignalToOpt (const addwriteNowSignalToOpt &) delete
Referenced by addwriteNowSignalToOpt::addwriteNowSignalToOpt().
addwriteNowSignalToOpt (const char * name) inline explicit
Definition at line 60 of file sigWriteNow.C.
References addwriteNowSignalToOpt::addwriteNowSignalToOpt(), and addwriteNowSignalToOpt::operator=().
virtual ~addwriteNowSignalToOpt () virtual default
Member Function Documentation
void operator= (const addwriteNowSignalToOpt &) delete
Referenced by addwriteNowSignalToOpt::addwriteNowSignalToOpt().
virtual void readData (Foam::Istream & is) inline virtual
Read.
Implements simpleRegIOobject.
Definition at line 67 of file sigWriteNow.C.
virtual void writeData (Foam::Ostream & os) const inline virtual
Write.
Implements simpleRegIOobject.
Definition at line 73 of file sigWriteNow.C.
References sigWriteNow::set().
The documentation for this class was generated from the following file:
src/OSspecific/POSIX/signals/sigWriteNow.C