OpenFOAM: snGradScheme< Type > Class Template Reference
snGradScheme< Type > Class Template Reference abstract
Surface normal gradient schemes
Abstract base class for snGrad schemes.
Public Member Functions
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const =0
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the snGrad.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Static Public Member Functions
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Detailed Description
template<class Type>
class Foam::fv::snGradScheme< Type >
Abstract base class for snGrad schemes.
Source files
snGradScheme.H
snGradScheme.C
Definition at line 61 of file snGradScheme.H.
Constructor & Destructor Documentation
snGradScheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 111 of file snGradScheme.H.
virtual ~snGradScheme () virtual default
Destructor.
Member Function Documentation
virtual const word& type () const pure virtual
Runtime type information.
declareRunTimeSelectionTable (tmp , snGradScheme< Type > , Mesh , (const fvMesh &mesh, Istream &schemeData) , (mesh, schemeData))
tmp< snGradScheme< Type > > New (const fvMesh & mesh, Istream & schemeData) static
Return new tmp interpolation scheme.
Definition at line 42 of file snGradScheme.C.
References Foam::expressions::patchExpr::debug, Foam::endl(), IOstream::eof(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, FatalIOErrorInLookup, InfoInFunction, and mesh.
Referenced by laplacianScheme< Type, GType >::laplacianScheme(), and Foam::fvc::snGrad().
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 140 of file snGradScheme.H.
Referenced by CentredFitSnGradScheme< Type, Polynomial, Stencil >::CentredFitSnGradScheme(), and CentredFitSnGradScheme< Type, Polynomial, Stencil >::corrected().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const tmp< surfaceScalarField > & tdeltaCoeffs, const word & snGradName = "snGrad") static
Return the snGrad of the given cell field with the given deltaCoeffs.
Definition at line 86 of file snGradScheme.C.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), fvPatchField< Type >::coupled(), DimensionedField< Type, GeoMesh >::dimensions(), forAll, IOobject::instance(), DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), fvMesh::neighbour(), IOobject::NO_READ, IOobject::NO_WRITE, fvMesh::owner(), tmp< T >::ref(), DimensionedField< Type, GeoMesh >::setOriented(), and fvPatchField< Type >::snGrad().
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > & vf, const word & snGradName = "sndGrad") static
Return the sndGrad of the given cell field.
Definition at line 151 of file snGradScheme.C.
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const pure virtual
Return the interpolation weighting factors for the given field.
Implemented in limitedSnGrad< Type >, CentredFitSnGradScheme< Type, Polynomial, Stencil >, orthogonalSnGrad< Type >, uncorrectedSnGrad< Type >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, and skewCorrectedSnGrad< Type >.
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented in limitedSnGrad< Type >, CentredFitSnGradScheme< Type, Polynomial, Stencil >, orthogonalSnGrad< Type >, uncorrectedSnGrad< Type >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, and skewCorrectedSnGrad< Type >.
Definition at line 178 of file snGradScheme.H.
virtual tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > correction (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the explicit correction to the snGrad.
for the given field
Reimplemented in limitedSnGrad< Type >, correctedSnGrad< Type >, faceCorrectedSnGrad< Type >, skewCorrectedSnGrad< Type >, CentredFitSnGradScheme< Type, Polynomial, Stencil >, orthogonalSnGrad< Type >, and uncorrectedSnGrad< Type >.
Definition at line 189 of file snGradScheme.H.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the snGrad of the given cell field.
with explicit correction
Definition at line 163 of file snGradScheme.C.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> & tvf) const
Return the snGrad of the given tmp cell field.
with explicit correction
Definition at line 184 of file snGradScheme.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/snGradScheme/snGradScheme.H
src/finiteVolume/finiteVolume/snGradSchemes/snGradScheme/snGradScheme.C