OpenFOAM: faceAreaIntersect Class Reference
faceAreaIntersect Class Reference
Face intersection class.
Public Types
enum triangulationMode { tmFan, tmMesh }
Public Member Functions
faceAreaIntersect (const pointField &pointsA, const pointField &pointsB, const DynamicList< face > &trisA, const DynamicList< face > &trisB, const bool reverseB=false, const bool cacheTriangulation=false)
Construct from components.
bool cacheTriangulation () const
Const access to the cacheTriangulation flag.
const DynamicList< triPoints > triangles () const
Const access to the triangulation.
DynamicList< triPoints > & triangles ()
Non-const access to the triangulation.
scalar calc (const face &faceA, const face &faceB, const vector &n) const
Return area of intersection of faceA with faceB.
bool overlaps (const face &faceA, const face &faceB, const vector &n, const scalar threshold) const
Return area of intersection of faceA with faceB.
Static Public Member Functions
static scalar & tolerance ()
Fraction of local length scale to use as intersection tolerance.
static void triangulate (const face &f, const pointField &points, const triangulationMode &triMode, faceList &faceTris)
Triangulate a face using the given triangulation mode.
static void triangleFan (const face &f, DynamicList< face > &faces)
Decompose face into triangle fan.
Static Public Attributes
static const Enum
< triangulationMode > triangulationModeNames_
Detailed Description
Face intersection class.
calculates intersection area by sub-dividing face into triangles and cutting
Source files
faceAreaIntersect.H
faceAreaIntersect.C
Definition at line 54 of file faceAreaIntersect.H.
Member Enumeration Documentation
enum triangulationMode
Enumerator
tmFan
tmMesh
Definition at line 58 of file faceAreaIntersect.H.
Constructor & Destructor Documentation
faceAreaIntersect (const pointField & pointsA, const pointField & pointsB, const DynamicList< face > & trisA, const DynamicList< face > & trisB, const bool reverseB = false, const bool cacheTriangulation = false)
Construct from components.
Definition at line 375 of file faceAreaIntersect.C.
Member Function Documentation
Foam::scalar & tolerance () inline static
Fraction of local length scale to use as intersection tolerance.
Definition at line 111 of file faceAreaIntersectI.H.
References Foam::mag().
void triangulate (const face & f, const pointField & points, const triangulationMode & triMode, faceList & faceTris) static
Triangulate a face using the given triangulation mode.
Definition at line 397 of file faceAreaIntersect.C.
bool cacheTriangulation () const inline
Const access to the cacheTriangulation flag.
Definition at line 117 of file faceAreaIntersectI.H.
const Foam::DynamicList< Foam::triPoints > triangles () const inline
Const access to the triangulation.
Definition at line 124 of file faceAreaIntersectI.H.
Foam::DynamicList< Foam::triPoints > & triangles () inline
Non-const access to the triangulation.
Definition at line 130 of file faceAreaIntersectI.H.
void triangleFan (const face & f, DynamicList< face > & faces) inline static
Decompose face into triangle fan.
Definition at line 25 of file faceAreaIntersectI.H.
References DynamicList< T, SizeMin >::append(), i, and UList< T >::size().
Foam::scalar calc (const face & faceA, const face & faceB, const vector & n) const
Return area of intersection of faceA with faceB.
Definition at line 441 of file faceAreaIntersect.C.
bool overlaps (const face & faceA, const face & faceB, const vector & n, const scalar threshold) const
Return area of intersection of faceA with faceB.
Definition at line 492 of file faceAreaIntersect.C.
Member Data Documentation
const Foam::Enum< Foam::faceAreaIntersect::triangulationMode > triangulationModeNames_ static
Definition at line 64 of file faceAreaIntersect.H.
The documentation for this class was generated from the following files:
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersect.H
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersect.C
src/meshTools/AMIInterpolation/faceAreaIntersect/faceAreaIntersectI.H