OpenFOAM: subModelBase Class Reference
subModelBase Class Reference
Base class for generic sub-models requiring to be read from dictionary. Provides a mechanism to read and write properties from a dictionary to enable clean re-starts. Used by, e.g. clou dsub-models.
Public Member Functions
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
virtual bool writeTime () const
Flag to indicate when to write a property.
virtual fileName localPath () const
Output directory.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
bool getModelDict (const word &entryName, dictionary &dict) const
Retrieve dictionary, return true if set.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
virtual void write (Ostream &os) const
Write.
Protected Member Functions
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
Base class for generic sub-models requiring to be read from dictionary. Provides a mechanism to read and write properties from a dictionary to enable clean re-starts. Used by, e.g. clou dsub-models.
Source files
subModelBase.H
subModelBase.C
Definition at line 50 of file subModelBase.H.
Constructor & Destructor Documentation
subModelBase (dictionary & properties)
Construct null.
Definition at line 34 of file subModelBase.C.
subModelBase (dictionary & properties, const dictionary & dict, const word & baseName, const word & modelType, const word & dictExt = "Coeffs")
Construct from components without name.
Definition at line 46 of file subModelBase.C.
subModelBase (const word & modelName, dictionary & properties, const dictionary & dict, const word & baseName, const word & modelType)
Construct from components with name.
Definition at line 64 of file subModelBase.C.
subModelBase (const subModelBase & smb)
Construct as copy.
Definition at line 81 of file subModelBase.C.
~subModelBase () virtual
Destructor.
Definition at line 94 of file subModelBase.C.
Member Function Documentation
bool inLine () const protected
Flag to indicate whether data is/was read in-line.
const Foam::word & modelName () const
Return const access to the name of the sub-model.
Definition at line 100 of file subModelBase.C.
const Foam::dictionary & dict () const
Return const access to the cloud dictionary.
Definition at line 106 of file subModelBase.C.
Referenced by InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), filmThermoModel::New(), heatTransferModel::New(), filmRadiationModel::New(), force::New(), filmTurbulenceModel::New(), filmViscosityModel::New(), phaseChangeModel::New(), transferModel::New(), and injectionModel::New().
const Foam::word & baseName () const
Return const access to the base name of the sub-model.
Definition at line 112 of file subModelBase.C.
const Foam::word & modelType () const
Return const access to the sub-model type.
Definition at line 118 of file subModelBase.C.
Referenced by filmSubModelBase::filmType(), filmThermoModel::New(), filmRadiationModel::New(), heatTransferModel::New(), filmTurbulenceModel::New(), filmViscosityModel::New(), and phaseChangeModel::New().
const Foam::dictionary & coeffDict () const
Return const access to the coefficients dictionary.
Definition at line 124 of file subModelBase.C.
Referenced by COxidationHurtMitchell< CloudType >::COxidationHurtMitchell(), ETAB< CloudType >::ETAB(), InflationInjection< CloudType >::InflationInjection(), MUCSheterogeneousRate< CloudType >::MUCSheterogeneousRate(), ReitzDiwakar< CloudType >::ReitzDiwakar(), and ReitzKHRT< CloudType >::ReitzKHRT().
const Foam::dictionary & properties () const
Return const access to the properties dictionary.
Definition at line 130 of file subModelBase.C.
bool defaultCoeffs (const bool printMsg) const virtual
Returns true if defaultCoeffs is true and outputs on printMsg.
Definition at line 136 of file subModelBase.C.
Referenced by ETAB< CloudType >::ETAB(), PilchErdman< CloudType >::PilchErdman(), ReitzDiwakar< CloudType >::ReitzDiwakar(), and ReitzKHRT< CloudType >::ReitzKHRT().
bool active () const virtual
Return the model 'active' status - default active = true.
Reimplemented in MultiInteraction< CloudType >, NoSurfaceFilm< CloudType >, NoDamping< CloudType >, NoPacking< CloudType >, NoCollision< CloudType >, NoStochasticCollision< CloudType >, NoIsotropy< CloudType >, NoInjection< CloudType >, noPhaseChange, NoheterogeneousReacting< CloudType >, NoDispersion< CloudType >, NoInteraction< CloudType >, NoDevolatilisation< CloudType >, NoSurfaceReaction< CloudType >, NoHeatTransfer< CloudType >, NoPhaseChange< CloudType >, NoAtomization< CloudType >, and NoBreakup< CloudType >.
Definition at line 150 of file subModelBase.C.
void cacheFields (const bool store) virtual
Cache dependant sub-model fields.
Reimplemented in Implicit< CloudType >, Explicit< CloudType >, DispersionRASModel< CloudType >, Relaxation< CloudType >, and GradientDispersionRAS< CloudType >.
Definition at line 156 of file subModelBase.C.
bool writeTime () const virtual
Flag to indicate when to write a property.
Reimplemented in CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< CloudType > >, CloudSubModelBase< Foam::SprayCloud< CloudType > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< CloudType > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< CloudType > >, CloudSubModelBase< Foam::KinematicCloud< CloudType > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< CloudType > >, CloudSubModelBase< Foam::MPPICCloud< CloudType > >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< CloudType > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >, and filmSubModelBase.
Definition at line 160 of file subModelBase.C.
Foam::fileName localPath () const virtual
Output directory.
Reimplemented in CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< CloudType > >, CloudSubModelBase< Foam::SprayCloud< CloudType > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< CloudType > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< CloudType > >, CloudSubModelBase< Foam::KinematicCloud< CloudType > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< CloudType > >, CloudSubModelBase< Foam::MPPICCloud< CloudType > >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< CloudType > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, and CloudSubModelBase< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >.
Definition at line 166 of file subModelBase.C.
Type getBaseProperty (const word & entryName, const Type & defaultValue = Type(Zero)) const
Retrieve generic property from the base model.
Definition at line 25 of file subModelBaseTemplates.C.
References subModelBase::baseName_, dictionary::found(), subModelBase::properties_, dictionary::readIfPresent(), and dictionary::subDict().
void getBaseProperty (const word & entryName, Type & value) const
Retrieve generic property from the base model.
Definition at line 44 of file subModelBaseTemplates.C.
void setBaseProperty (const word & entryName, const Type & value)
Add generic property to the base model.
Definition at line 59 of file subModelBaseTemplates.C.
bool getModelDict (const word & entryName, dictionary & dict) const
Retrieve dictionary, return true if set.
Definition at line 178 of file subModelBase.C.
Referenced by InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection().
void getModelProperty (const word & entryName, Type & value) const
Retrieve generic property from the sub-model.
Definition at line 79 of file subModelBaseTemplates.C.
Type getModelProperty (const word & entryName, const Type & defaultValue = Type(Zero)) const
Retrieve generic property from the sub-model.
Definition at line 102 of file subModelBaseTemplates.C.
void setModelProperty (const word & entryName, const Type & value)
Add generic property to the sub-model.
Definition at line 115 of file subModelBaseTemplates.C.
void write (Ostream & os) const virtual
Write.
Reimplemented in DispersionRASModel< CloudType >, CloudSubModelBase< CloudType >, CloudSubModelBase< Foam::DSMCCloud >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< CloudType > >, CloudSubModelBase< Foam::SprayCloud< CloudType > >, CloudSubModelBase< Foam::ReactingMultiphaseCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< KinematicCloud< Cloud< basicKinematicCollidingParcel > > > >, CloudSubModelBase< Foam::MPPICCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ReactingCloud< CloudType > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::KinematicCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::CollidingCloud< CloudType > >, CloudSubModelBase< Foam::KinematicCloud< CloudType > >, CloudSubModelBase< Foam::ReactingHeterogeneousCloud< CloudType > >, CloudSubModelBase< Foam::MPPICCloud< CloudType > >, CloudSubModelBase< Foam::CollidingCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::SprayCloud< Foam::DSMCCloud > >, CloudSubModelBase< Foam::ThermoCloud< CloudType > >, CloudSubModelBase< Foam::ReactingCloud< Foam::DSMCCloud > >, and CloudSubModelBase< Foam::KinematicCloud< Cloud< basicKinematicCollidingParcel > > >.
Definition at line 205 of file subModelBase.C.
Member Data Documentation
const word modelName_ protected
Name of the sub-model.
Definition at line 67 of file subModelBase.H.
dictionary& properties_ protected
Reference to properties dictionary e.g. for restart.
Definition at line 72 of file subModelBase.H.
Referenced by subModelBase::getBaseProperty().
const dictionary dict_ protected
Copy of dictionary used during construction.
Definition at line 77 of file subModelBase.H.
const word baseName_ protected
Name of the sub-model base class.
Definition at line 82 of file subModelBase.H.
Referenced by subModelBase::getBaseProperty().
const word modelType_ protected
Type of the sub-model.
Definition at line 87 of file subModelBase.H.
const dictionary coeffDict_ protected
Coefficients dictionary.
Definition at line 92 of file subModelBase.H.
The documentation for this class was generated from the following files:
src/OpenFOAM/primitives/subModelBase/subModelBase.H
src/OpenFOAM/primitives/subModelBase/subModelBase.C
src/OpenFOAM/primitives/subModelBase/subModelBaseTemplates.C