OpenFOAM: ensightMesh Class Reference
ensightMesh Class Reference
Encapsulation of volume meshes for writing in ensight format.
Classes
class options
Configuration options for the ensightMesh.
Public Member Functions
ensightMesh (const fvMesh &mesh, const options &opts)
Construct from components.
ensightMesh (const fvMesh &mesh)
Construct from fvMesh with all default options, binary output.
ensightMesh (const fvMesh &mesh, const IOstream::streamFormat format)
Construct from fvMesh with all default options and specified format.
~ensightMesh ()
Destructor.
const fvMesh & mesh () const
Reference to the underlying fvMesh.
const ensightMesh::options & option () const
Reference to the writer/mesh options.
IOstream::streamFormat format () const
Ascii/Binary file output.
bool useInternalMesh () const
Using internal?
bool useBoundaryMesh () const
Using boundary?
const ensightCells & meshCells () const
The volume cells (internalMesh)
const Map< word > & patches () const
The list of patches to be output.
const HashTable< ensightFaces > & boundaryPatchFaces () const
Face elements per selected patch.
const HashTable< ensightFaces > & faceZoneFaces () const
Face elements per selected faceZone.
const globalIndex & globalPoints () const
Global numbering for merged points.
const labelList & pointToGlobal () const
From mesh point to global merged point.
const labelList & uniquePointMap () const
Local points that are unique.
bool needsUpdate () const
Does the content need an update?
bool expire ()
Mark as needing an update.
void correct ()
Update for new mesh.
void write (autoPtr< ensightGeoFile > &os) const
Write to file.
void write (ensightGeoFile &os) const
Write to file.
Detailed Description
Encapsulation of volume meshes for writing in ensight format.
Source files
ensightMesh.H
ensightMesh.C
ensightMeshIO.C
ensightMeshOptions.C
Definition at line 64 of file ensightMesh.H.
Constructor & Destructor Documentation
ensightMesh (const fvMesh & mesh, const options & opts)
Construct from components.
Definition at line 50 of file ensightMesh.C.
ensightMesh (const fvMesh & mesh) explicit
Construct from fvMesh with all default options, binary output.
Definition at line 66 of file ensightMesh.C.
References ensightMesh::correct().
ensightMesh (const fvMesh & mesh, const IOstream::streamFormat format)
Construct from fvMesh with all default options and specified format.
Definition at line 73 of file ensightMesh.C.
~ensightMesh ()
Destructor.
Definition at line 91 of file ensightMesh.C.
Member Function Documentation
const Foam::fvMesh & mesh () const inline
Reference to the underlying fvMesh.
Definition at line 23 of file ensightMeshI.H.
Referenced by Foam::ensightOutput::Detail::writeVolField().
const Foam::ensightMesh::options & option () const inline
Reference to the writer/mesh options.
Definition at line 29 of file ensightMeshI.H.
Foam::IOstream::streamFormat format () const inline
Ascii/Binary file output.
Definition at line 35 of file ensightMeshI.H.
bool useInternalMesh () const inline
Using internal?
Definition at line 41 of file ensightMeshI.H.
Referenced by Foam::ensightOutput::Detail::writeVolField().
bool useBoundaryMesh () const inline
Using boundary?
Definition at line 47 of file ensightMeshI.H.
const Foam::ensightCells & meshCells () const inline
The volume cells (internalMesh)
Definition at line 53 of file ensightMeshI.H.
Referenced by Foam::ensightOutput::Detail::writeVolField().
const Foam::Map< Foam::word > & patches () const inline
The list of patches to be output.
Definition at line 59 of file ensightMeshI.H.
Referenced by Foam::ensightOutput::Detail::writeVolField().
const Foam::HashTable< Foam::ensightFaces > & boundaryPatchFaces () const inline
Face elements per selected patch.
Definition at line 66 of file ensightMeshI.H.
Referenced by Foam::ensightOutput::Detail::writeVolField().
const Foam::HashTable< Foam::ensightFaces > & faceZoneFaces () const inline
Face elements per selected faceZone.
To be output in sorted order.
Definition at line 73 of file ensightMeshI.H.
Referenced by Foam::ensightOutput::Detail::writeVolField().
const globalIndex& globalPoints () const inline
Global numbering for merged points.
Definition at line 439 of file ensightMesh.H.
const labelList& pointToGlobal () const inline
From mesh point to global merged point.
Definition at line 447 of file ensightMesh.H.
const labelList& uniquePointMap () const inline
Local points that are unique.
Definition at line 455 of file ensightMesh.H.
bool needsUpdate () const
Does the content need an update?
Definition at line 99 of file ensightMesh.C.
References Foam::deleteDemandDrivenData().
bool expire ()
Mark as needing an update.
May also free up unneeded data. Return false if already marked as expired.
Definition at line 105 of file ensightMesh.C.
void correct ()
Update for new mesh.
Definition at line 120 of file ensightMesh.C.
Referenced by ensightMesh::ensightMesh().
void write (autoPtr< ensightGeoFile > & os) const inline
Write to file.
Definition at line 79 of file ensightMeshI.H.
void write (ensightGeoFile & os) const
Write to file.
Definition at line 268 of file ensightMesh.C.
The documentation for this class was generated from the following files:
src/conversion/ensight/mesh/ensightMesh.H
src/conversion/ensight/mesh/ensightMesh.C
src/conversion/ensight/mesh/ensightMeshI.H
src/conversion/ensight/mesh/ensightMeshIO.C