OpenFOAM: treeDataFace Class Reference
treeDataFace Class Reference
Encapsulation of data needed to search for faces.
Classes
class findIntersectOp
class findNearestOp
Public Member Functions
ClassName ("treeDataFace")
treeDataFace (const bool cacheBb, const primitiveMesh &mesh, const labelUList &faceLabels)
Construct from mesh, copying subset of faces.
treeDataFace (const bool cacheBb, const primitiveMesh &mesh, labelList &&faceLabels)
Construct from mesh, moving subset of faces.
treeDataFace (const bool cacheBb, const primitiveMesh &mesh)
Construct from mesh. Uses all faces in mesh.
treeDataFace (const bool cacheBb, const polyPatch &patch)
Construct from mesh. Uses all faces in patch.
const labelList & faceLabels () const
const primitiveMesh & mesh () const
label size () const
pointField shapePoints () const
Representative point cloud for all shapes inside (one point per shape)
volumeType getVolumeType (const indexedOctree< treeDataFace > &, const point &) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
bool overlaps (const label index, const treeBoundBox &sampleBb) const
Does (bb of) shape at index overlap bb.
Detailed Description
Encapsulation of data needed to search for faces.
Source files
treeDataFace.H
treeDataFace.C
Definition at line 55 of file treeDataFace.H.
Constructor & Destructor Documentation
treeDataFace (const bool cacheBb, const primitiveMesh & mesh, const labelUList & faceLabels)
Construct from mesh, copying subset of faces.
Definition at line 63 of file treeDataFace.C.
treeDataFace (const bool cacheBb, const primitiveMesh & mesh, labelList && faceLabels)
Construct from mesh, moving subset of faces.
Definition at line 79 of file treeDataFace.C.
References update().
treeDataFace (const bool cacheBb, const primitiveMesh & mesh)
Construct from mesh. Uses all faces in mesh.
Definition at line 95 of file treeDataFace.C.
References update().
treeDataFace (const bool cacheBb, const polyPatch & patch)
Construct from mesh. Uses all faces in patch.
Definition at line 110 of file treeDataFace.C.
References update().
Member Function Documentation
ClassName ("treeDataFace")
const labelList& faceLabels () const inline
Definition at line 200 of file treeDataFace.H.
Referenced by meshSearch::findNearestBoundaryFace().
const primitiveMesh& mesh () const inline
Definition at line 205 of file treeDataFace.H.
label size () const inline
Definition at line 210 of file treeDataFace.H.
Foam::pointField shapePoints () const
Representative point cloud for all shapes inside (one point per shape)
Definition at line 147 of file treeDataFace.C.
Foam::volumeType getVolumeType (const indexedOctree< treeDataFace > & oc, const point & sample) const
Get type (inside,outside,mixed,unknown) of point w.r.t. surface.
Only makes sense for closed surfaces.
Definition at line 161 of file treeDataFace.C.
bool overlaps (const label index, const treeBoundBox & sampleBb) const
Does (bb of) shape at index overlap bb.
Definition at line 407 of file treeDataFace.C.
The documentation for this class was generated from the following files:
src/meshTools/indexedOctree/treeDataFace.H
src/meshTools/indexedOctree/treeDataFace.C