OpenFOAM: StationaryPhaseModel< BasePhaseModel > Class Template Reference
StationaryPhaseModel< BasePhaseModel > Class Template Reference
Class which represents a stationary (and therefore probably solid) phase. Generates, but does not store, zero velocity and flux field and turbulent qauantities. Throws an error when non-const access is requested to the motion fields or when the momentum equation is requested. Usage must must protect against such calls.
Public Member Functions
StationaryPhaseModel (const phaseSystem &fluid, const word &phaseName, const label index)
virtual ~StationaryPhaseModel ()
Destructor.
virtual bool stationary () const
Return whether the phase is stationary.
virtual tmp< fvVectorMatrix > UEqn ()
Return the momentum equation.
virtual tmp< fvVectorMatrix > UfEqn ()
Return the momentum equation for the face-based algorithm.
virtual tmp< volVectorField > U () const
Return the velocity.
virtual volVectorField & URef ()
Access the velocity.
virtual tmp< surfaceScalarField > phi () const
Return the volumetric flux.
virtual surfaceScalarField & phiRef ()
Access the volumetric flux.
virtual tmp< surfaceScalarField > alphaPhi () const
Return the volumetric flux of the phase.
virtual surfaceScalarField & alphaPhiRef ()
Access the volumetric flux of the phase.
virtual tmp< surfaceScalarField > alphaRhoPhi () const
Return the mass flux of the phase.
virtual surfaceScalarField & alphaRhoPhiRef ()
Access the mass flux of the phase.
virtual tmp< volVectorField > DUDt () const
Return the substantive acceleration.
virtual tmp< surfaceScalarField > DUDtf () const
Return the substantive acceleration on the faces.
virtual tmp< volScalarField > continuityError () const
Return the continuity error.
virtual tmp< volScalarField > continuityErrorFlow () const
Return the continuity error due to the flow field.
virtual tmp< volScalarField > continuityErrorSources () const
Return the continuity error due to any sources.
virtual tmp< volScalarField > K () const
Return the phase kinetic energy.
virtual tmp< volScalarField > divU () const
Return the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
virtual void divU (tmp< volScalarField > divU)
Set the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
virtual tmp< volScalarField > mut () const
Return the turbulent dynamic viscosity.
virtual tmp< volScalarField > muEff () const
Return the effective dynamic viscosity.
virtual tmp< volScalarField > nut () const
Return the turbulent kinematic viscosity.
virtual tmp< volScalarField > nuEff () const
Return the effective kinematic viscosity.
virtual tmp< volScalarField > kappaEff () const
Return the effective thermal conductivity.
virtual tmp< scalarField > kappaEff (const label patchi) const
Return the effective thermal conductivity on a patch.
virtual tmp< volScalarField > alphaEff () const
Return the effective thermal diffusivity.
virtual tmp< scalarField > alphaEff (const label patchi) const
Return the effective thermal conductivity on a patch.
virtual tmp< volScalarField > k () const
Return the turbulent kinetic energy.
virtual tmp< volScalarField > pPrime () const
Return the phase-pressure'.
template<class Type , template< class > class PatchField, class GeoMesh >
Foam::tmp
< Foam::GeometricField< Type,
PatchField, GeoMesh > > zeroField (const word &name, const dimensionSet &dims, const bool cache) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > zeroVolField (const word &name, const dimensionSet &dims, const bool cache) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > zeroSurfaceField (const word &name, const dimensionSet &dims, const bool cache) const
Detailed Description
template<class BasePhaseModel>
class Foam::StationaryPhaseModel< BasePhaseModel >
Class which represents a stationary (and therefore probably solid) phase. Generates, but does not store, zero velocity and flux field and turbulent qauantities. Throws an error when non-const access is requested to the motion fields or when the momentum equation is requested. Usage must must protect against such calls.
See Also
MovingPhaseModel
Source files
StationaryPhaseModel.H
StationaryPhaseModel.C
Definition at line 54 of file StationaryPhaseModel.H.
Constructor & Destructor Documentation
StationaryPhaseModel (const phaseSystem & fluid, const word & phaseName, const label index)
Definition at line 84 of file StationaryPhaseModel.C.
~StationaryPhaseModel () virtual
Destructor.
Definition at line 97 of file StationaryPhaseModel.C.
Member Function Documentation
bool stationary () const virtual
Return whether the phase is stationary.
Definition at line 104 of file StationaryPhaseModel.C.
Foam::tmp< Foam::fvVectorMatrix > UEqn () virtual
Return the momentum equation.
Definition at line 112 of file StationaryPhaseModel.C.
Foam::tmp< Foam::fvVectorMatrix > UfEqn () virtual
Return the momentum equation for the face-based algorithm.
Definition at line 124 of file StationaryPhaseModel.C.
Foam::tmp< Foam::volVectorField > U () const virtual
Return the velocity.
Definition at line 136 of file StationaryPhaseModel.C.
Foam::volVectorField & URef () virtual
Access the velocity.
Definition at line 144 of file StationaryPhaseModel.C.
References Foam::dimVelocity.
Foam::tmp< Foam::surfaceScalarField > phi () const virtual
Return the volumetric flux.
Definition at line 156 of file StationaryPhaseModel.C.
Foam::surfaceScalarField & phiRef () virtual
Access the volumetric flux.
Definition at line 164 of file StationaryPhaseModel.C.
References Foam::dimTime, and Foam::dimVolume.
Foam::tmp< Foam::surfaceScalarField > alphaPhi () const virtual
Return the volumetric flux of the phase.
Definition at line 176 of file StationaryPhaseModel.C.
Foam::surfaceScalarField & alphaPhiRef () virtual
Access the volumetric flux of the phase.
Definition at line 184 of file StationaryPhaseModel.C.
References Foam::dimTime, and Foam::dimVolume.
Foam::tmp< Foam::surfaceScalarField > alphaRhoPhi () const virtual
Return the mass flux of the phase.
Definition at line 196 of file StationaryPhaseModel.C.
Foam::surfaceScalarField & alphaRhoPhiRef () virtual
Access the mass flux of the phase.
Definition at line 204 of file StationaryPhaseModel.C.
References Foam::dimMass, and Foam::dimTime.
Foam::tmp< Foam::volVectorField > DUDt () const virtual
Return the substantive acceleration.
Definition at line 216 of file StationaryPhaseModel.C.
Foam::tmp< Foam::surfaceScalarField > DUDtf () const virtual
Return the substantive acceleration on the faces.
Definition at line 224 of file StationaryPhaseModel.C.
References Foam::dimTime, and Foam::dimVelocity.
Foam::tmp< Foam::volScalarField > continuityError () const virtual
Return the continuity error.
Definition at line 232 of file StationaryPhaseModel.C.
References Foam::dimArea, Foam::dimTime, and Foam::dimVelocity.
Foam::tmp< Foam::volScalarField > continuityErrorFlow () const virtual
Return the continuity error due to the flow field.
Definition at line 240 of file StationaryPhaseModel.C.
References Foam::dimDensity, and Foam::dimTime.
Foam::tmp< Foam::volScalarField > continuityErrorSources () const virtual
Return the continuity error due to any sources.
Definition at line 248 of file StationaryPhaseModel.C.
References Foam::dimDensity, and Foam::dimTime.
Foam::tmp< Foam::volScalarField > K () const virtual
Return the phase kinetic energy.
Definition at line 256 of file StationaryPhaseModel.C.
References Foam::dimDensity, and Foam::dimTime.
Foam::tmp< Foam::volScalarField > divU () const virtual
Return the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
Definition at line 264 of file StationaryPhaseModel.C.
References Foam::dimVelocity, and Foam::sqr().
void divU (tmp< volScalarField > divU) virtual
Set the phase dilatation rate (d(alpha)/dt + div(alpha*phi))
Definition at line 272 of file StationaryPhaseModel.C.
Foam::tmp< Foam::volScalarField > mut () const virtual
Return the turbulent dynamic viscosity.
Definition at line 284 of file StationaryPhaseModel.C.
Foam::tmp< Foam::volScalarField > muEff () const virtual
Return the effective dynamic viscosity.
Definition at line 292 of file StationaryPhaseModel.C.
References Foam::dimDynamicViscosity.
Foam::tmp< Foam::volScalarField > nut () const virtual
Return the turbulent kinematic viscosity.
Definition at line 300 of file StationaryPhaseModel.C.
References thermo.
Foam::tmp< Foam::volScalarField > nuEff () const virtual
Return the effective kinematic viscosity.
Definition at line 308 of file StationaryPhaseModel.C.
References Foam::dimViscosity.
Foam::tmp< Foam::volScalarField > kappaEff () const virtual
Return the effective thermal conductivity.
Definition at line 316 of file StationaryPhaseModel.C.
References thermo.
Foam::tmp< Foam::scalarField > kappaEff (const label patchi) const virtual
Return the effective thermal conductivity on a patch.
Definition at line 324 of file StationaryPhaseModel.C.
References thermo.
Foam::tmp< Foam::volScalarField > alphaEff () const virtual
Return the effective thermal diffusivity.
Definition at line 332 of file StationaryPhaseModel.C.
References thermo.
Foam::tmp< Foam::scalarField > alphaEff (const label patchi) const virtual
Return the effective thermal conductivity on a patch.
Definition at line 340 of file StationaryPhaseModel.C.
References thermo.
Foam::tmp< Foam::volScalarField > k () const virtual
Return the turbulent kinetic energy.
Definition at line 348 of file StationaryPhaseModel.C.
References thermo.
Foam::tmp< Foam::volScalarField > pPrime () const virtual
Return the phase-pressure'.
(derivative of phase-pressure w.r.t. phase-fraction)
Definition at line 356 of file StationaryPhaseModel.C.
References Foam::dimVelocity, and Foam::sqr().
Foam::tmp<Foam::GeometricField<Type, PatchField, GeoMesh> > zeroField (const word & name, const dimensionSet & dims, const bool cache) const
Definition at line 29 of file StationaryPhaseModel.C.
References mesh, Foam::name(), and timeName.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > zeroVolField (const word & name, const dimensionSet & dims, const bool cache) const
Definition at line 56 of file StationaryPhaseModel.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > zeroSurfaceField (const word & name, const dimensionSet & dims, const bool cache) const
Definition at line 70 of file StationaryPhaseModel.C.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/phaseSystems/phaseModel/StationaryPhaseModel/StationaryPhaseModel.H
src/phaseSystemModels/reactingEulerFoam/phaseSystems/phaseModel/StationaryPhaseModel/StationaryPhaseModel.C