OpenFOAM: ThermoParcel< ParcelType > Class Template Reference
ThermoParcel< ParcelType > Class Template Reference
Parcels
Thermodynamic parcel class with one/two-way coupling with the continuous phase. Includes Kinematic parcel sub-models, plus:
Classes
class constantProperties
Class to hold thermo particle constant properties.
class iNew
Factory class to read-construct particles used for.
class trackingData
Public Member Functions
TypeName ("ThermoParcel")
Runtime type information.
AddToPropertyList (ParcelType," T"+" Cp")
String representation of properties.
ThermoParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from mesh, coordinates and topology.
ThermoParcel (const polyMesh &mesh, const vector &position, const label celli)
Construct from a position and a cell, searching for the rest of the.
ThermoParcel (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector &U0, const vector &f0, const vector &angularMomentum0, const vector &torque0, const constantProperties &constProps)
Construct from components.
ThermoParcel (const polyMesh &mesh, Istream &is, bool readFields=true, bool newFormat=true)
Construct from Istream.
ThermoParcel (const ThermoParcel &p)
Construct as a copy.
ThermoParcel (const ThermoParcel &p, const polyMesh &mesh)
Construct as a copy.
virtual autoPtr< particle > clone () const
Construct and return a (basic particle) clone.
virtual autoPtr< particle > clone (const polyMesh &mesh) const
Construct and return a (basic particle) clone.
scalar T () const
Return const access to temperature.
scalar Cp () const
Return const access to specific heat capacity.
scalar hs () const
Return the parcel sensible enthalpy.
scalar & T ()
Return access to temperature.
scalar & Cp ()
Return access to specific heat capacity.
template<class TrackCloudType >
void setCellValues (TrackCloudType &cloud, trackingData &td)
Set cell values.
template<class TrackCloudType >
void cellValueSourceCorrection (TrackCloudType &cloud, trackingData &td, const scalar dt)
Correct cell values using latest transfer information.
template<class TrackCloudType >
void calcSurfaceValues (TrackCloudType &cloud, trackingData &td, const scalar T, scalar &Ts, scalar &rhos, scalar &mus, scalar &Pr, scalar &kappas) const
Calculate surface thermo properties.
template<class TrackCloudType >
void calc (TrackCloudType &cloud, trackingData &td, const scalar dt)
Update parcel properties over the time interval.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly=false) const
Write individual parcel properties to stream.
template<class TrackCloudType >
Foam::scalar calcHeatTransfer (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar &dhsTrans, scalar &Sph)
Static Public Member Functions
template<class CloudType >
static void readFields (CloudType &c)
Read.
template<class CloudType >
static void writeFields (const CloudType &c)
Write.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static const std::size_t sizeofFields
Size in bytes of the fields.
Protected Member Functions
template<class TrackCloudType >
scalar calcHeatTransfer (TrackCloudType &cloud, trackingData &td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar &dhsTrans, scalar &Sph)
Calculate new particle temperature.
Protected Attributes
scalar T_
Temperature [K].
scalar Cp_
Specific heat capacity [J/(kg.K)].
Friends
Ostream & operator (Ostream &, const ThermoParcel< ParcelType > &)
Detailed Description
template<class ParcelType>
class Foam::ThermoParcel< ParcelType >
Thermodynamic parcel class with one/two-way coupling with the continuous phase. Includes Kinematic parcel sub-models, plus:
heat transfer
Source files
ThermoParcel.H
ThermoParcelI.H
ThermoParcel.C
ThermoParcelIO.C
Definition at line 53 of file ThermoParcel.H.
Constructor & Destructor Documentation
ThermoParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti) inline
Construct from mesh, coordinates and topology.
Other properties initialised as null
Definition at line 70 of file ThermoParcelI.H.
ThermoParcel (const polyMesh & mesh, const vector & position, const label celli) inline
Construct from a position and a cell, searching for the rest of the.
required topology. Other properties are initialised as null.
Definition at line 86 of file ThermoParcelI.H.
ThermoParcel (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti, const label typeId, const scalar nParticle0, const scalar d0, const scalar dTarget0, const vector & U0, const vector & f0, const vector & angularMomentum0, const vector & torque0, const constantProperties & constProps) inline
Construct from components.
Definition at line 100 of file ThermoParcelI.H.
ThermoParcel (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 44 of file ThermoParcelIO.C.
ThermoParcel (const ThermoParcel< ParcelType > & p)
Construct as a copy.
ThermoParcel (const ThermoParcel< ParcelType > & p, const polyMesh & mesh)
Construct as a copy.
Member Function Documentation
scalar calcHeatTransfer (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar & dhsTrans, scalar & Sph) protected
Calculate new particle temperature.
TypeName ("ThermoParcel< ParcelType >")
Runtime type information.
AddToPropertyList (ParcelType , " T"+" Cp")
String representation of properties.
virtual autoPtr<particle> clone () const inline virtual
Construct and return a (basic particle) clone.
Definition at line 456 of file ThermoParcel.H.
virtual autoPtr<particle> clone (const polyMesh & mesh) const inline virtual
Construct and return a (basic particle) clone.
Definition at line 464 of file ThermoParcel.H.
Foam::scalar T () const inline
Return const access to temperature.
Definition at line 200 of file ThermoParcelI.H.
Foam::scalar Cp () const inline
Return const access to specific heat capacity.
Definition at line 207 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::T_.
Foam::scalar hs () const inline
Return the parcel sensible enthalpy.
Definition at line 214 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::Cp_.
Foam::scalar & T () inline
Return access to temperature.
Definition at line 221 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::Cp_, and ThermoParcel< ParcelType >::T_.
Foam::scalar & Cp () inline
Return access to specific heat capacity.
Definition at line 228 of file ThermoParcelI.H.
References ThermoParcel< ParcelType >::T_.
void setCellValues (TrackCloudType & cloud, trackingData & td)
Set cell values.
Definition at line 31 of file ThermoParcel.C.
References coordinates(), ThermoParcel< ParcelType >::trackingData::Cpc(), ThermoParcel< ParcelType >::trackingData::CpInterp(), Foam::expressions::patchExpr::debug, Foam::endl(), interpolation< class >::interpolate(), Foam::nl, ThermoParcel< ParcelType >::trackingData::Tc(), ThermoParcel< ParcelType >::trackingData::TInterp(), and WarningInFunction.
void cellValueSourceCorrection (TrackCloudType & cloud, trackingData & td, const scalar dt)
Correct cell values using latest transfer information.
Definition at line 61 of file ThermoParcel.C.
void calcSurfaceValues (TrackCloudType & cloud, trackingData & td, const scalar T, scalar & Ts, scalar & rhos, scalar & mus, scalar & Pr, scalar & kappas) const
Calculate surface thermo properties.
Definition at line 95 of file ThermoParcel.C.
void calc (TrackCloudType & cloud, trackingData & td, const scalar dt)
Update parcel properties over the time interval.
Definition at line 138 of file ThermoParcel.C.
void readFields (CloudType & c) static
Read.
Definition at line 84 of file ThermoParcelIO.C.
void writeFields (const CloudType & c) static
Write.
Definition at line 110 of file ThermoParcelIO.C.
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly = false) const
Write individual parcel properties to stream.
Definition at line 136 of file ThermoParcelIO.C.
void readObjects (CloudType & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 159 of file ThermoParcelIO.C.
void writeObjects (const CloudType & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Definition at line 185 of file ThermoParcelIO.C.
Foam::scalar calcHeatTransfer (TrackCloudType & cloud, trackingData & td, const scalar dt, const scalar Re, const scalar Pr, const scalar kappa, const scalar NCpW, const scalar Sh, scalar & dhsTrans, scalar & Sph)
Definition at line 247 of file ThermoParcel.C.
Friends And Related Function Documentation
Ostream& operator (Ostream & , const ThermoParcel< ParcelType > &) friend
Member Data Documentation
const std::size_t sizeofFields static
Size in bytes of the fields.
Definition at line 76 of file ThermoParcel.H.
scalar T_ protected
Temperature [K].
Definition at line 334 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::Cp(), and ThermoParcel< ParcelType >::T().
scalar Cp_ protected
Specific heat capacity [J/(kg.K)].
Definition at line 339 of file ThermoParcel.H.
Referenced by ThermoParcel< ParcelType >::hs(), ThermoParcel< ParcelType >::trackingData::kappa(), and ThermoParcel< ParcelType >::T().
The documentation for this class was generated from the following files:
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcel.C
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelI.H
src/lagrangian/intermediate/parcels/Templates/ThermoParcel/ThermoParcelIO.C