OpenFOAM: steadyStateD2dt2Scheme< Type > Class Template Reference
steadyStateD2dt2Scheme< Type > Class Template Reference
SteadyState d2dt2 which returns 0.
Public Member Functions
TypeName ("steadyState")
Runtime type information.
steadyStateD2dt2Scheme (const fvMesh &mesh)
Construct from mesh.
steadyStateD2dt2Scheme (const fvMesh &mesh, Istream &is)
Construct from mesh and Istream.
const fvMesh & mesh () const
Return mesh reference.
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< GeometricField< Type,
fvPatchField, volMesh > > fvcD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar &, const GeometricField< Type, fvPatchField, volMesh > &)
tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField &, const GeometricField< Type, fvPatchField, volMesh > &)
Public Member Functions inherited from d2dt2Scheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, d2dt2Scheme, Istream,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
d2dt2Scheme (const fvMesh &mesh)
Construct from mesh.
d2dt2Scheme (const fvMesh &mesh, Istream &)
Construct from mesh and Istream.
virtual ~d2dt2Scheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from d2dt2Scheme< Type >
static tmp< d2dt2Scheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return a pointer to a new d2dt2Scheme created on freestore.
Protected Member Functions inherited from d2dt2Scheme< Type >
d2dt2Scheme (const d2dt2Scheme &)=delete
No copy construct.
void operator= (const d2dt2Scheme &)=delete
No copy assignment.
Protected Attributes inherited from d2dt2Scheme< Type >
const fvMesh & mesh_
Detailed Description
template<class Type>
class Foam::fv::steadyStateD2dt2Scheme< Type >
SteadyState d2dt2 which returns 0.
Source files
steadyStateD2dt2Scheme.H
steadyStateD2dt2Scheme.C
Definition at line 52 of file steadyStateD2dt2Scheme.H.
Constructor & Destructor Documentation
steadyStateD2dt2Scheme (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 82 of file steadyStateD2dt2Scheme.H.
steadyStateD2dt2Scheme (const fvMesh & mesh, Istream & is) inline
Construct from mesh and Istream.
Definition at line 90 of file steadyStateD2dt2Scheme.H.
References d2dt2Scheme< Type >::mesh().
Member Function Documentation
TypeName ("steadyState")
Runtime type information.
const fvMesh& mesh () const inline
Return mesh reference.
Definition at line 101 of file steadyStateD2dt2Scheme.H.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 40 of file steadyStateD2dt2Scheme.C.
References DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimTime, mesh, IOobject::name(), IOobject::NO_READ, IOobject::NO_WRITE, and Foam::Zero.
tmp< GeometricField< Type, fvPatchField, volMesh > > fvcD2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 66 of file steadyStateD2dt2Scheme.C.
tmp< fvMatrix< Type > > fvmD2dt2 (const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 94 of file steadyStateD2dt2Scheme.C.
tmp< fvMatrix< Type > > fvmD2dt2 (const dimensionedScalar & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 114 of file steadyStateD2dt2Scheme.C.
tmp< fvMatrix< Type > > fvmD2dt2 (const volScalarField & rho, const GeometricField< Type, fvPatchField, volMesh > & vf) virtual
Implements d2dt2Scheme< Type >.
Definition at line 135 of file steadyStateD2dt2Scheme.C.
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/d2dt2Schemes/steadyStateD2dt2Scheme/steadyStateD2dt2Scheme.H
src/finiteVolume/finiteVolume/d2dt2Schemes/steadyStateD2dt2Scheme/steadyStateD2dt2Scheme.C