OpenFOAM: massTransferModel Class Reference
massTransferModel Class Reference abstract
Public Member Functions
TypeName ("massTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, massTransferModel, dictionary,(const dictionary &dict, const phasePair &pair),(dict, pair))
massTransferModel (const dictionary &dict, const phasePair &pair)
Construct from a dictionary and a phase pair.
virtual ~massTransferModel ()
Destructor.
virtual tmp< volScalarField > K () const =0
The implicit mass transfer coefficient.
Static Public Member Functions
static autoPtr< massTransferModel > New (const dictionary &dict, const phasePair &pair)
Static Public Attributes
static const dimensionSet dimK
Coefficient dimensions.
Protected Attributes
const phasePair & pair_
Phase pair.
Detailed Description
Source files
massTransferModel.H
massTransferModel.C
Definition at line 49 of file massTransferModel.H.
Constructor & Destructor Documentation
massTransferModel (const dictionary & dict, const phasePair & pair)
Construct from a dictionary and a phase pair.
Definition at line 40 of file massTransferModel.C.
~massTransferModel () virtual
Destructor.
Definition at line 51 of file massTransferModel.C.
Member Function Documentation
TypeName ("massTransferModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , massTransferModel , dictionary , (const dictionary &dict, const phasePair &pair) , (dict, pair))
Foam::autoPtr< Foam::massTransferModel > New (const dictionary & dict, const phasePair & pair) static
Definition at line 28 of file newMassTransferModel.C.
References Foam::abort(), dict, Foam::endl(), Foam::FatalIOError, FatalIOErrorInLookup, dictionary::get(), and Foam::Info.
virtual tmp<volScalarField> K () const pure virtual
The implicit mass transfer coefficient.
Note: this has had the species mass diffusivity factored out
Implemented in Frossling, and sphericalMassTransfer.
Member Data Documentation
const phasePair& pair_ protected
Phase pair.
Definition at line 58 of file massTransferModel.H.
const Foam::dimensionSet dimK static
Coefficient dimensions.
Definition at line 89 of file massTransferModel.H.
The documentation for this class was generated from the following files:
src/phaseSystemModels/reactingEulerFoam/interfacialCompositionModels/massTransferModels/massTransferModel/massTransferModel.H
src/phaseSystemModels/reactingEulerFoam/interfacialCompositionModels/massTransferModels/massTransferModel/massTransferModel.C
src/phaseSystemModels/reactingEulerFoam/interfacialCompositionModels/massTransferModels/massTransferModel/newMassTransferModel.C