OpenFOAM: polyMeshGeometry Class Reference
polyMeshGeometry Class Reference
Updateable mesh geometry and checking routines.
Public Member Functions
ClassName ("polyMeshGeometry")
polyMeshGeometry (const polyMesh &)
Construct from mesh.
const polyMesh & mesh () const
const vectorField & faceAreas () const
const vectorField & faceCentres () const
const vectorField & cellCentres () const
const scalarField & cellVolumes () const
void correct ()
Take over properties from mesh.
void correct (const pointField &p, const labelList &changedFaces)
Recalculate on selected faces. Recalculates cell properties.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceTets (const bool report, const scalar minTetQuality, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkVolRatio (const bool report, const scalar warnRatio, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr) const
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkTriangleTwist (const bool report, const scalar minTwist, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceFlatness (const bool report, const scalar minFlatness, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkFaceArea (const bool report, const scalar minArea, const labelList &checkFaces, labelHashSet *setPtr) const
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr) const
Static Public Member Functions
static labelList affectedCells (const polyMesh &, const labelList &changedFaces)
Helper function: get affected cells from faces.
static bool checkFaceDotProduct (const bool report, const scalar orthWarn, const polyMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
See primitiveMesh.
static bool checkFacePyramids (const bool report, const scalar minPyrVol, const polyMesh &, const vectorField &cellCentres, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *)
See primitiveMesh.
static bool checkFaceTets (const bool report, const scalar minPyrVol, const polyMesh &, const vectorField &cellCentres, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *)
See primitiveMesh.
static bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const polyMesh &mesh, const pointField &points, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
See primitiveMesh.
static bool checkFaceWeights (const bool report, const scalar warnWeight, const polyMesh &mesh, const vectorField &cellCentres, const vectorField &faceCentres, const vectorField &faceAreas, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
Interpolation weights (0.5 for regular mesh)
static bool checkVolRatio (const bool report, const scalar warnRatio, const polyMesh &mesh, const scalarField &cellVolumes, const labelList &checkFaces, const List< labelPair > &baffles, labelHashSet *setPtr)
Cell volume ratio of neighbouring cells (1 for regular mesh)
static bool checkFaceAngles (const bool report, const scalar maxDeg, const polyMesh &mesh, const vectorField &faceAreas, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
See primitiveMesh.
static bool checkFaceTwist (const bool report, const scalar minTwist, const polyMesh &, const vectorField &cellCentres, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
Triangle (from face-centre decomposition) normal v.s.
static bool checkTriangleTwist (const bool report, const scalar minTwist, const polyMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
Consecutive triangle (from face-centre decomposition) normals.
static bool checkFaceFlatness (const bool report, const scalar minFlatness, const polyMesh &, const vectorField &faceAreas, const vectorField &faceCentres, const pointField &p, const labelList &checkFaces, labelHashSet *setPtr)
Area of faces v.s. sum of triangle areas.
static bool checkFaceArea (const bool report, const scalar minArea, const polyMesh &, const vectorField &faceAreas, const labelList &checkFaces, labelHashSet *setPtr)
Small faces.
static bool checkCellDeterminant (const bool report, const scalar minDet, const polyMesh &, const vectorField &faceAreas, const labelList &checkFaces, const labelList &affectedCells, labelHashSet *setPtr)
Area of internal faces v.s. boundary faces.
Detailed Description
Updateable mesh geometry and checking routines.
non-ortho done across coupled faces.
faceWeight (delta factors) done across coupled faces.
Source files
polyMeshGeometry.H
polyMeshGeometry.C
Definition at line 50 of file polyMeshGeometry.H.
Constructor & Destructor Documentation
polyMeshGeometry (const polyMesh & mesh)
Construct from mesh.
Definition at line 321 of file polyMeshGeometry.C.
Member Function Documentation
ClassName ("polyMeshGeometry")
const polyMesh& mesh () const inline
Definition at line 159 of file polyMeshGeometry.H.
const vectorField& faceAreas () const inline
Definition at line 164 of file polyMeshGeometry.H.
const vectorField& faceCentres () const inline
Definition at line 168 of file polyMeshGeometry.H.
const vectorField& cellCentres () const inline
Definition at line 172 of file polyMeshGeometry.H.
const scalarField& cellVolumes () const inline
Definition at line 176 of file polyMeshGeometry.H.
void correct ()
Take over properties from mesh.
Definition at line 331 of file polyMeshGeometry.C.
References correct.
void correct (const pointField & p, const labelList & changedFaces)
Recalculate on selected faces. Recalculates cell properties.
on owner and neighbour of these cells.
Definition at line 341 of file polyMeshGeometry.C.
Foam::labelList affectedCells (const polyMesh & mesh, const labelList & changedFaces) static
Helper function: get affected cells from faces.
Definition at line 176 of file polyMeshGeometry.C.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 354 of file polyMeshGeometry.C.
bool checkFacePyramids (const bool report, const scalar minPyrVol, const polyMesh & mesh, const vectorField & cellCentres, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 532 of file polyMeshGeometry.C.
bool checkFaceTets (const bool report, const scalar minPyrVol, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 703 of file polyMeshGeometry.C.
bool checkFaceSkewness (const bool report, const scalar internalSkew, const scalar boundarySkew, const polyMesh & mesh, const pointField & points, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 924 of file polyMeshGeometry.C.
bool checkFaceWeights (const bool report, const scalar warnWeight, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceCentres, const vectorField & faceAreas, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Interpolation weights (0.5 for regular mesh)
Definition at line 1129 of file polyMeshGeometry.C.
bool checkVolRatio (const bool report, const scalar warnRatio, const polyMesh & mesh, const scalarField & cellVolumes, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) static
Cell volume ratio of neighbouring cells (1 for regular mesh)
Definition at line 1277 of file polyMeshGeometry.C.
bool checkFaceAngles (const bool report, const scalar maxDeg, const polyMesh & mesh, const vectorField & faceAreas, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
See primitiveMesh.
Definition at line 1413 of file polyMeshGeometry.C.
References Foam::abort(), Foam::asin(), Foam::degToRad(), Foam::endl(), polyMesh::faces(), Foam::FatalError, FatalErrorInFunction, UList< T >::fcIndex(), UList< T >::first(), forAll, Foam::Info, HashSet< Key, Hash >::insert(), UList< T >::last(), Foam::mag(), Foam::max(), Foam::min(), Foam::normalised(), Foam::radToDeg(), Foam::reduce(), Foam::sin(), and WarningInFunction.
bool checkFaceTwist (const bool report, const scalar minTwist, const polyMesh & mesh, const vectorField & cellCentres, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Triangle (from face-centre decomposition) normal v.s.
average face normal
Definition at line 1541 of file polyMeshGeometry.C.
bool checkTriangleTwist (const bool report, const scalar minTwist, const polyMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Consecutive triangle (from face-centre decomposition) normals.
Definition at line 1687 of file polyMeshGeometry.C.
bool checkFaceFlatness (const bool report, const scalar minFlatness, const polyMesh & mesh, const vectorField & faceAreas, const vectorField & faceCentres, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) static
Area of faces v.s. sum of triangle areas.
Definition at line 1833 of file polyMeshGeometry.C.
bool checkFaceArea (const bool report, const scalar minArea, const polyMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, labelHashSet * setPtr) static
Small faces.
Definition at line 1926 of file polyMeshGeometry.C.
bool checkCellDeterminant (const bool report, const scalar minDet, const polyMesh & mesh, const vectorField & faceAreas, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) static
Area of internal faces v.s. boundary faces.
Definition at line 1983 of file polyMeshGeometry.C.
bool checkFaceDotProduct (const bool report, const scalar orthWarn, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2075 of file polyMeshGeometry.C.
bool checkFacePyramids (const bool report, const scalar minPyrVol, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2098 of file polyMeshGeometry.C.
bool checkFaceTets (const bool report, const scalar minTetQuality, const pointField & p, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2122 of file polyMeshGeometry.C.
bool checkFaceWeights (const bool report, const scalar warnWeight, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2173 of file polyMeshGeometry.C.
bool checkVolRatio (const bool report, const scalar warnRatio, const labelList & checkFaces, const List< labelPair > & baffles, labelHashSet * setPtr) const
Definition at line 2197 of file polyMeshGeometry.C.
bool checkFaceAngles (const bool report, const scalar maxDeg, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2219 of file polyMeshGeometry.C.
bool checkFaceTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2241 of file polyMeshGeometry.C.
bool checkTriangleTwist (const bool report, const scalar minTwist, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2265 of file polyMeshGeometry.C.
bool checkFaceFlatness (const bool report, const scalar minFlatness, const pointField & p, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2288 of file polyMeshGeometry.C.
bool checkFaceArea (const bool report, const scalar minArea, const labelList & checkFaces, labelHashSet * setPtr) const
Definition at line 2311 of file polyMeshGeometry.C.
bool checkCellDeterminant (const bool report, const scalar warnDet, const labelList & checkFaces, const labelList & affectedCells, labelHashSet * setPtr) const
Definition at line 2331 of file polyMeshGeometry.C.
The documentation for this class was generated from the following files:
src/dynamicMesh/motionSmoother/polyMeshGeometry/polyMeshGeometry.H
src/dynamicMesh/motionSmoother/polyMeshGeometry/polyMeshGeometry.C