OpenFOAM: particle< Type > Class Template Reference
particle< Type > Class Template Reference
Base particle class.
Classes
class iNew
Factory class to read-construct particles (for parallel transfer)
struct positionsCompat1706
Old particle positions content for OpenFOAM-1706 and earlier.
class trackingData
Public Member Functions
TypeName ("particle")
Runtime type information.
particle (const polyMesh &mesh, const barycentric &coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from components.
particle (const polyMesh &mesh, const vector &position, const label celli=-1)
Construct from a position and a cell.
particle (const polyMesh &mesh, const vector &position, const label celli, const label tetFacei, const label tetPti, const bool doLocate=true)
Construct from position components.
particle (const polyMesh &mesh, Istream &, bool readFields=true, bool newFormat=true)
Construct from Istream.
particle (const particle &p)
Construct as a copy.
particle (const particle &p, const polyMesh &mesh)
Construct as a copy with reference to a new mesh.
virtual autoPtr< particle > clone () const
Construct a clone.
virtual ~particle ()=default
Destructor.
label getNewParticleID () const
Get unique particle creation id.
const polyMesh & mesh () const
Return the mesh database.
const barycentric & coordinates () const
Return current particle coordinates.
label cell () const
Return current cell particle is in.
label & cell ()
Return current cell particle is in for manipulation.
label tetFace () const
Return current tet face particle is in.
label & tetFace ()
Return current tet face particle is in for manipulation.
label tetPt () const
Return current tet face particle is in.
label & tetPt ()
Return current tet face particle is in for manipulation.
label face () const
Return current face particle is on otherwise -1.
label & face ()
Return current face particle is on for manipulation.
scalar stepFraction () const
Return the fraction of time-step completed.
scalar & stepFraction ()
Return the fraction of time-step completed.
label origProc () const
Return the originating processor ID.
label & origProc ()
Return the originating processor ID.
label origId () const
Return the particle ID on the originating processor.
label & origId ()
Return the particle ID on the originating processor.
Pair< scalar > stepFractionSpan () const
Return the step fraction change within the overall time-step.
scalar currentTimeFraction () const
Return the current fraction within the timestep. This differs.
tetIndices currentTetIndices () const
Return the indices of the current tet that the.
barycentricTensor currentTetTransform () const
Return the current tet transformation tensor.
vector normal () const
The (unit) normal of the tri on tetFacei_ for the current tet.
bool onFace () const
Is the particle on a face?
bool onInternalFace () const
Is the particle on an internal face?
bool onBoundaryFace () const
Is the particle on a boundary face?
label patch () const
Return the index of patch that the particle is on.
vector position () const
Return current particle position.
scalar track (const vector &displacement, const scalar fraction)
Track along the displacement for a given fraction of the overall.
scalar trackToFace (const vector &displacement, const scalar fraction)
As particle::track, but also stops on internal faces.
scalar trackToTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToFace, but also stops on tet triangles. On.
scalar trackToStationaryTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for stationary meshes.
scalar trackToMovingTri (const vector &displacement, const scalar fraction, label &tetTriI)
As particle::trackToTri, but for moving meshes.
template<class TrackCloudType >
void hitFace (const vector &direction, TrackCloudType &cloud, trackingData &td)
Hit the current face. If the current face is internal than this.
template<class TrackCloudType >
void trackToAndHitFace (const vector &direction, const scalar fraction, TrackCloudType &cloud, trackingData &td)
Convenience function. Combines trackToFace and hitFace.
vector deviationFromMeshCentre () const
Get the displacement from the mesh centre. Used to correct the.
void patchData (vector &n, vector &U) const
Get the normal and velocity of the current patch location.
virtual void transformProperties (const tensor &T)
Transform the physical properties of the particle.
virtual void transformProperties (const vector &separation)
Transform the physical properties of the particle.
void prepareForParallelTransfer ()
Convert global addressing to the processor patch local equivalents.
void correctAfterParallelTransfer (const label patchi, trackingData &td)
Convert processor patch addressing to the global equivalents.
void prepareForInteractionListReferral (const vectorTensorTransform &transform)
Break the topology and store the particle position so that the.
void correctAfterInteractionListReferral (const label celli)
Correct the topology after referral. The particle may still be.
label procTetPt (const polyMesh &procMesh, const label procCell, const label procTetFace) const
Return the tet point appropriate for decomposition or reconstruction.
void autoMap (const vector &position, const mapPolyMesh &mapper)
Map after a topology change.
void relocate (const point &position, const label celli=-1)
Set the addressing based on the provided position.
void writeProperties (Ostream &os, const wordRes &filters, const word &delim, const bool namesOnly) const
Write individual particle properties to stream.
void writeCoordinates (Ostream &os) const
Write the particle barycentric coordinates and cell info.
virtual void writePosition (Ostream &os) const
Write the particle position and cell id.
Static Public Member Functions
static string propertyList ()
template<class Type >
static void writePropertyName (Ostream &os, const word &name, const word &delim)
Write the name representation to stream.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Type &value, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property to stream, optionally filtered based on its name.
template<class Type >
static void writeProperty (Ostream &os, const word &name, const Field< Type > &values, const bool nameOnly, const word &delim, const wordRes &filters=wordRes::null())
Write a named particle property list to stream, optionally filtered based on its name.
template<class TrackCloudType >
static void readFields (TrackCloudType &c)
Read the fields associated with the owner cloud.
template<class TrackCloudType >
static void writeFields (const TrackCloudType &c)
Write the fields associated with the owner cloud.
template<class CloudType >
static void readObjects (CloudType &c, const objectRegistry &obr)
Read particle fields as objects from the obr registry.
template<class CloudType >
static void writeObjects (const CloudType &c, objectRegistry &obr)
Write particle fields as objects into the obr registry.
Static Public Attributes
static string propertyList_ = Foam::particle::propertyList()
String representation of properties.
static label particleCount_ = 0
Cumulative particle counter - used to provide unique ID.
static bool writeLagrangianCoordinates = true
Write particle coordinates file (v1712 and later) Default is true.
static bool writeLagrangianPositions
Write particle positions file (v1706 format and earlier) Default is true (disable in etc/controlDict)
Protected Member Functions
template<class TrackCloudType >
bool hitPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a patch.
template<class TrackCloudType >
void hitWedgePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wedgePatch.
template<class TrackCloudType >
void hitSymmetryPlanePatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitSymmetryPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a symmetryPatch.
template<class TrackCloudType >
void hitCyclicPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a cyclicPatch.
template<class TrackCloudType >
void hitCyclicAMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a cyclicAMIPatch.
template<class TrackCloudType >
void hitCyclicACMIPatch (TrackCloudType &, trackingData &, const vector &)
Overridable function to handle the particle hitting a.
template<class TrackCloudType >
void hitProcessorPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a processorPatch.
template<class TrackCloudType >
void hitWallPatch (TrackCloudType &, trackingData &)
Overridable function to handle the particle hitting a wallPatch.
Friends
Ostream & operator<< (Ostream &, const particle &)
bool operator== (const particle &pA, const particle &pB)
bool operator!= (const particle &pA, const particle &pB)
Detailed Description
template<class Type>
class Foam::particle< Type >
Base particle class.
Definition at line 70 of file particle.H.
Constructor & Destructor Documentation
particle (const polyMesh & mesh, const barycentric & coordinates, const label celli, const label tetFacei, const label tetPti)
Construct from components.
Definition at line 497 of file particle.C.
particle (const polyMesh & mesh, const vector & position, const label celli = -1)
Construct from a position and a cell.
Searches for the rest of the required topology.
Definition at line 518 of file particle.C.
particle (const polyMesh & mesh, const vector & position, const label celli, const label tetFacei, const label tetPti, const bool doLocate = true)
Construct from position components.
Definition at line 546 of file particle.C.
particle (const polyMesh & mesh, Istream & is, bool readFields = true, bool newFormat = true)
Construct from Istream.
Definition at line 43 of file particleIO.C.
particle (const particle< Type > & p)
Construct as a copy.
Definition at line 579 of file particle.C.
particle (const particle< Type > & p, const polyMesh & mesh)
Construct as a copy with reference to a new mesh.
Definition at line 593 of file particle.C.
virtual ~particle () virtual default
Destructor.
Member Function Documentation
bool hitPatch (TrackCloudType & , trackingData &) protected
Overridable function to handle the particle hitting a patch.
Executed before other patch-hitting functions.
Definition at line 372 of file particleTemplates.C.
void hitWedgePatch (TrackCloudType & cloud, trackingData & td) protected
Overridable function to handle the particle hitting a wedgePatch.
Definition at line 379 of file particleTemplates.C.
void hitSymmetryPlanePatch (TrackCloudType & cloud, trackingData & td) protected
Overridable function to handle the particle hitting a.
symmetryPlanePatch
Definition at line 391 of file particleTemplates.C.
void hitSymmetryPatch (TrackCloudType & , trackingData &) protected
Overridable function to handle the particle hitting a symmetryPatch.
Definition at line 401 of file particleTemplates.C.
void hitCyclicPatch (TrackCloudType & , trackingData &) protected
Overridable function to handle the particle hitting a cyclicPatch.
Definition at line 410 of file particleTemplates.C.
void hitCyclicAMIPatch (TrackCloudType & , trackingData & td, const vector & direction) protected
Overridable function to handle the particle hitting a cyclicAMIPatch.
Definition at line 452 of file particleTemplates.C.
void hitCyclicACMIPatch (TrackCloudType & cloud, trackingData & td, const vector & direction) protected
Overridable function to handle the particle hitting a.
cyclicACMIPatch
Definition at line 524 of file particleTemplates.C.
void hitProcessorPatch (TrackCloudType & , trackingData &) protected
Overridable function to handle the particle hitting a processorPatch.
Definition at line 566 of file particleTemplates.C.
void hitWallPatch (TrackCloudType & , trackingData &) protected
Overridable function to handle the particle hitting a wallPatch.
Definition at line 571 of file particleTemplates.C.
TypeName ("particle< Type >")
Runtime type information.
static string propertyList () inline static
Definition at line 429 of file particle.H.
virtual autoPtr<particle> clone () const inline virtual
Construct a clone.
Reimplemented in molecule, wallBoundedParticle, wallBoundedStreamLineParticle, streamLineParticle, trackedParticle, solidParticle, injectedParticle, findCellParticle, indexedParticle, passiveParticle, and passivePositionParticle.
Definition at line 513 of file particle.H.
Foam::label getNewParticleID () const inline
Get unique particle creation id.
Definition at line 111 of file particleI.H.
const Foam::polyMesh & mesh () const inline
Return the mesh database.
Definition at line 125 of file particleI.H.
Referenced by passivePositionParticle::clone(), wallBoundedParticle::currentEdge(), wallBoundedStreamLineParticle::move(), and wallBoundedParticle::patchInteraction().
const Foam::barycentric & coordinates () const inline
Return current particle coordinates.
Definition at line 131 of file particleI.H.
Foam::label cell () const inline
Return current cell particle is in.
Definition at line 137 of file particleI.H.
Foam::label & cell () inline
Return current cell particle is in for manipulation.
Definition at line 143 of file particleI.H.
Foam::label tetFace () const inline
Return current tet face particle is in.
Definition at line 149 of file particleI.H.
Referenced by wallBoundedParticle::currentEdge().
Foam::label & tetFace () inline
Return current tet face particle is in for manipulation.
Definition at line 155 of file particleI.H.
Foam::label tetPt () const inline
Return current tet face particle is in.
Definition at line 161 of file particleI.H.
Foam::label & tetPt () inline
Return current tet face particle is in for manipulation.
Definition at line 167 of file particleI.H.
Foam::label face () const inline
Return current face particle is on otherwise -1.
Definition at line 173 of file particleI.H.
Referenced by wallBoundedParticle::patchInteraction().
Foam::label & face () inline
Return current face particle is on for manipulation.
Definition at line 179 of file particleI.H.
Foam::scalar stepFraction () const inline
Return the fraction of time-step completed.
Definition at line 185 of file particleI.H.
Referenced by wallBoundedStreamLineParticle::move().
Foam::scalar & stepFraction () inline
Return the fraction of time-step completed.
Definition at line 191 of file particleI.H.
Foam::label origProc () const inline
Return the originating processor ID.
Definition at line 197 of file particleI.H.
Referenced by Foam::operator!=().
Foam::label & origProc () inline
Return the originating processor ID.
Definition at line 203 of file particleI.H.
Foam::label origId () const inline
Return the particle ID on the originating processor.
Definition at line 209 of file particleI.H.
Referenced by Foam::operator!=().
Foam::label & origId () inline
Return the particle ID on the originating processor.
Definition at line 215 of file particleI.H.
Foam::Pair< Foam::scalar > stepFractionSpan () const inline
Return the step fraction change within the overall time-step.
Returns the start value and the change as a scalar pair. Always return Pair<scalar>(0, 1), unless sub-cycling is in effect, in which case the values will reflect the span of the sub-cycle within the time-step.
Definition at line 221 of file particleI.H.
Foam::scalar currentTimeFraction () const inline
Return the current fraction within the timestep. This differs.
from the stored step fraction due to sub-cycling.
Definition at line 245 of file particleI.H.
Foam::tetIndices currentTetIndices () const inline
Return the indices of the current tet that the.
particle occupies.
Definition at line 253 of file particleI.H.
References s.
Foam::barycentricTensor currentTetTransform () const inline
Return the current tet transformation tensor.
Definition at line 259 of file particleI.H.
Foam::vector normal () const inline
The (unit) normal of the tri on tetFacei_ for the current tet.
Definition at line 272 of file particleI.H.
bool onFace () const inline
Is the particle on a face?
Definition at line 278 of file particleI.H.
bool onInternalFace () const inline
Is the particle on an internal face?
Definition at line 284 of file particleI.H.
bool onBoundaryFace () const inline
Is the particle on a boundary face?
Definition at line 290 of file particleI.H.
Foam::label patch () const inline
Return the index of patch that the particle is on.
Definition at line 296 of file particleI.H.
Referenced by wallBoundedParticle::patchInteraction().
Foam::vector position () const inline
Return current particle position.
Definition at line 302 of file particleI.H.
Referenced by wallBoundedStreamLineParticle::interpolateFields().
Foam::scalar track (const vector & displacement, const scalar fraction)
Track along the displacement for a given fraction of the overall.
step. End when the track is complete, or when a boundary is hit. On exit, stepFraction_ will have been incremented to the current position, and facei_ will be set to the index of the boundary face that was hit, or -1 if the track completed within a cell. The proportion of the displacement still to be completed is returned.
Definition at line 610 of file particle.C.
Foam::scalar trackToFace (const vector & displacement, const scalar fraction)
As particle::track, but also stops on internal faces.
Definition at line 629 of file particle.C.
Foam::scalar trackToTri (const vector & displacement, const scalar fraction, label & tetTriI)
As particle::trackToFace, but also stops on tet triangles. On.
exit, tetTriI is set to the index of the tet triangle that was hit, or -1 if the end position was reached.
Definition at line 904 of file particle.C.
Foam::scalar trackToStationaryTri (const vector & displacement, const scalar fraction, label & tetTriI)
As particle::trackToTri, but for stationary meshes.
Definition at line 665 of file particle.C.
Foam::scalar trackToMovingTri (const vector & displacement, const scalar fraction, label & tetTriI)
As particle::trackToTri, but for moving meshes.
Definition at line 776 of file particle.C.
void hitFace (const vector & direction, TrackCloudType & cloud, trackingData & td)
Hit the current face. If the current face is internal than this.
crosses into the next cell. If it is a boundary face then this will interact the particle with the relevant patch.
Definition at line 288 of file particleTemplates.C.
void trackToAndHitFace (const vector & direction, const scalar fraction, TrackCloudType & cloud, trackingData & td)
Convenience function. Combines trackToFace and hitFace.
Definition at line 358 of file particleTemplates.C.
Foam::vector deviationFromMeshCentre () const
Get the displacement from the mesh centre. Used to correct the.
particle position in cases with reduced dimensionality. Returns a zero vector for three-dimensional cases.
Definition at line 921 of file particle.C.
void patchData (vector & n, vector & U) const inline
Get the normal and velocity of the current patch location.
Definition at line 308 of file particleI.H.
void transformProperties (const tensor & T) virtual
Transform the physical properties of the particle.
according to the given transformation tensor
Reimplemented in molecule, and solidParticle.
Definition at line 936 of file particle.C.
References VectorSpace< Vector< scalar >, scalar, 3 >::zero.
Referenced by solidParticle::transformProperties().
void transformProperties (const vector & separation) virtual
Transform the physical properties of the particle.
according to the given separation vector
Reimplemented in molecule, and solidParticle.
Definition at line 940 of file particle.C.
void prepareForParallelTransfer ()
Convert global addressing to the processor patch local equivalents.
Definition at line 944 of file particle.C.
void correctAfterParallelTransfer (const label patchi, trackingData & td)
Convert processor patch addressing to the global equivalents.
and set the celli to the face-neighbour
Definition at line 952 of file particle.C.
References Foam::foamVersion::patch.
void prepareForInteractionListReferral (const vectorTensorTransform & transform)
Break the topology and store the particle position so that the.
particle can be referred.
Definition at line 1001 of file particle.C.
void correctAfterInteractionListReferral (const label celli)
Correct the topology after referral. The particle may still be.
outside the stored tet and therefore not track-able.
Definition at line 1026 of file particle.C.
References vectorTensorTransform::R(), and Tensor< Cmpt >::T().
Foam::label procTetPt (const polyMesh & procMesh, const label procCell, const label procTetFace) const
Return the tet point appropriate for decomposition or reconstruction.
to or from the given mesh.
Definition at line 1064 of file particle.C.
void autoMap (const vector & position, const mapPolyMesh & mapper)
Map after a topology change.
Definition at line 1090 of file particle.C.
void relocate (const point & position, const label celli = -1)
Set the addressing based on the provided position.
Definition at line 1106 of file particle.C.
void writePropertyName (Ostream & os, const word & name, const word & delim) static
Write the name representation to stream.
Definition at line 38 of file particleTemplates.C.
References i, and Foam::name().
void writeProperty (Ostream & os, const word & name, const Type & value, const bool nameOnly, const word & delim, const wordRes & filters = wordRes::null()) static
Write a named particle property to stream, optionally filtered based on its name.
Definition at line 64 of file particleTemplates.C.
void writeProperty (Ostream & os, const word & name, const Field< Type > & values, const bool nameOnly, const word & delim, const wordRes & filters = wordRes::null()) static
Write a named particle property list to stream, optionally filtered based on its name.
Definition at line 92 of file particleTemplates.C.
void readFields (TrackCloudType & c) static
Read the fields associated with the owner cloud.
Definition at line 133 of file particleTemplates.C.
References Foam::HashTableOps::values().
Referenced by passiveParticleCloud::passiveParticleCloud().
void writeFields (const TrackCloudType & c) static
Write the fields associated with the owner cloud.
Definition at line 163 of file particleTemplates.C.
void writeProperties (Ostream & os, const wordRes & filters, const word & delim, const bool namesOnly) const
Write individual particle properties to stream.
Definition at line 190 of file particleIO.C.
void readObjects (CloudType & c, const objectRegistry & obr) static
Read particle fields as objects from the obr registry.
Definition at line 217 of file particleTemplates.C.
void writeObjects (const CloudType & c, objectRegistry & obr) static
Write particle fields as objects into the obr registry.
Always writes "position", not "coordinate"
Definition at line 266 of file particleTemplates.C.
void writeCoordinates (Ostream & os) const
Write the particle barycentric coordinates and cell info.
Definition at line 215 of file particleIO.C.
void writePosition (Ostream & os) const virtual
Write the particle position and cell id.
Reimplemented in injectedParticle.
Definition at line 234 of file particleIO.C.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const particle< Type > &) friend
bool operator== (const particle< Type > & pA, const particle< Type > & pB) friend
bool operator!= (const particle< Type > & pA, const particle< Type > & pB) friend
Member Data Documentation
Foam::string propertyList_ = Foam::particle::propertyList() static
String representation of properties.
Definition at line 429 of file particle.H.
Foam::label particleCount_ = 0 static
Cumulative particle counter - used to provide unique ID.
Definition at line 429 of file particle.H.
bool writeLagrangianCoordinates = true static
Write particle coordinates file (v1712 and later) Default is true.
Definition at line 440 of file particle.H.
bool writeLagrangianPositions static
Write particle positions file (v1706 format and earlier) Default is true (disable in etc/controlDict)
Definition at line 446 of file particle.H.
The documentation for this class was generated from the following files:
src/lagrangian/basic/particle/particle.H
src/lagrangian/basic/particle/particle.C
src/lagrangian/basic/particle/particleI.H
src/lagrangian/basic/particle/particleIO.C
src/lagrangian/basic/particle/particleTemplates.C