OpenFOAM: edgeNormalFixedValueFaPatchVectorField Class Reference
edgeNormalFixedValueFaPatchVectorField Class Reference
Edge normal fixed value vector field finite area boundary condition.
Public Member Functions
TypeName ("edgeNormalFixedValue")
Runtime type information.
edgeNormalFixedValueFaPatchVectorField (const faPatch &, const DimensionedField< vector, areaMesh > &)
Construct from patch and internal field.
edgeNormalFixedValueFaPatchVectorField (const faPatch &, const DimensionedField< vector, areaMesh > &, const dictionary &)
Construct from patch, internal field and dictionary.
edgeNormalFixedValueFaPatchVectorField (const edgeNormalFixedValueFaPatchVectorField &, const faPatch &, const DimensionedField< vector, areaMesh > &, const faPatchFieldMapper &)
Construct by mapping given.
edgeNormalFixedValueFaPatchVectorField (const edgeNormalFixedValueFaPatchVectorField &)
Construct as copy.
virtual tmp< faPatchVectorField > clone () const
Construct and return a clone.
edgeNormalFixedValueFaPatchVectorField (const edgeNormalFixedValueFaPatchVectorField &, const DimensionedField< vector, areaMesh > &)
Construct as copy setting internal field reference.
virtual tmp< faPatchVectorField > clone (const DimensionedField< vector, areaMesh > &iF) const
Construct and return a clone setting internal field reference.
virtual void autoMap (const faPatchFieldMapper &)
Map (and resize as needed) from self given a mapping object.
virtual void rmap (const faPatchVectorField &, const labelList &)
Reverse map the given faPatchField onto this faPatchField.
virtual void updateCoeffs ()
Update the coefficients associated with the patch field.
virtual void write (Ostream &) const
Write.
Detailed Description
Edge normal fixed value vector field finite area boundary condition.
Describes a surface normal vector boundary condition by its magnitude. Note: The value is positive for outward-pointing vectors
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Source files
edgeNormalFixedValueFaPatchVectorField.H
edgeNormalFixedValueFaPatchVectorField.C
Definition at line 54 of file edgeNormalFixedValueFaPatchVectorField.H.
Constructor & Destructor Documentation
edgeNormalFixedValueFaPatchVectorField (const faPatch & p, const DimensionedField< vector, areaMesh > & iF)
Construct from patch and internal field.
Definition at line 30 of file edgeNormalFixedValueFaPatchVectorField.C.
Referenced by edgeNormalFixedValueFaPatchVectorField::clone().
edgeNormalFixedValueFaPatchVectorField (const faPatch & p, const DimensionedField< vector, areaMesh > & iF, const dictionary & dict)
Construct from patch, internal field and dictionary.
Definition at line 56 of file edgeNormalFixedValueFaPatchVectorField.C.
edgeNormalFixedValueFaPatchVectorField (const edgeNormalFixedValueFaPatchVectorField & ptf, const faPatch & p, const DimensionedField< vector, areaMesh > & iF, const faPatchFieldMapper & mapper)
Construct by mapping given.
edgeNormalFixedValueFaPatchVectorField onto a new patch
Definition at line 42 of file edgeNormalFixedValueFaPatchVectorField.C.
edgeNormalFixedValueFaPatchVectorField (const edgeNormalFixedValueFaPatchVectorField & pivpvf)
Construct as copy.
Definition at line 69 of file edgeNormalFixedValueFaPatchVectorField.C.
edgeNormalFixedValueFaPatchVectorField (const edgeNormalFixedValueFaPatchVectorField & pivpvf, const DimensionedField< vector, areaMesh > & iF)
Construct as copy setting internal field reference.
Definition at line 80 of file edgeNormalFixedValueFaPatchVectorField.C.
Member Function Documentation
TypeName ("edgeNormalFixedValue")
Runtime type information.
virtual tmp<faPatchVectorField> clone () const inline virtual
Construct and return a clone.
Definition at line 120 of file edgeNormalFixedValueFaPatchVectorField.H.
References edgeNormalFixedValueFaPatchVectorField::edgeNormalFixedValueFaPatchVectorField().
virtual tmp<faPatchVectorField> clone (const DimensionedField< vector, areaMesh > & iF) const inline virtual
Construct and return a clone setting internal field reference.
Definition at line 141 of file edgeNormalFixedValueFaPatchVectorField.H.
void autoMap (const faPatchFieldMapper & m) virtual
Map (and resize as needed) from self given a mapping object.
Definition at line 93 of file edgeNormalFixedValueFaPatchVectorField.C.
void rmap (const faPatchVectorField & ptf, const labelList & addr) virtual
Reverse map the given faPatchField onto this faPatchField.
Definition at line 103 of file edgeNormalFixedValueFaPatchVectorField.C.
References Field< Type >::autoMap().
void updateCoeffs () virtual
Update the coefficients associated with the patch field.
Definition at line 117 of file edgeNormalFixedValueFaPatchVectorField.C.
void write (Ostream & os) const virtual
Write.
Definition at line 128 of file edgeNormalFixedValueFaPatchVectorField.C.
The documentation for this class was generated from the following files:
src/finiteArea/fields/faPatchFields/derived/edgeNormalFixedValue/edgeNormalFixedValueFaPatchVectorField.H
src/finiteArea/fields/faPatchFields/derived/edgeNormalFixedValue/edgeNormalFixedValueFaPatchVectorField.C