OpenFOAM: hPowerThermo< EquationOfState > Class Template Reference
hPowerThermo< EquationOfState > Class Template Reference
Thermodynamics
Power-function based thermodynamics package templated on EquationOfState.
Public Member Functions
hPowerThermo (const dictionary &)
Construct from dictionary.
hPowerThermo (const word &, const hPowerThermo &)
Construct as a named copy.
autoPtr< hPowerThermo > clone () const
Construct and return a clone.
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar Cp (const scalar p, const scalar T) const
Heat capacity at constant pressure [J/(kg K)].
scalar Ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kg].
scalar Hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
Entropy [J/(kg K)].
scalar dGdT (const scalar p, const scalar T) const
Derivative of Gibbs free energy w.r.t. temperature.
scalar dCpdT (const scalar p, const scalar T) const
Temperature derivative of heat capacity at constant pressure.
void operator+= (const hPowerThermo &)
Static Public Member Functions
static autoPtr< hPowerThermo > New (const dictionary &dict)
Selector from dictionary.
static word typeName ()
Return the instantiated type name.
Friends
hPowerThermo operator+ (const hPowerThermo &, const hPowerThermo &)
hPowerThermo operator* (const scalar, const hPowerThermo &)
hPowerThermo operator== (const hPowerThermo &, const hPowerThermo &)
Ostream & operator (Ostream &, const hPowerThermo &)
Detailed Description
template<class EquationOfState>
class Foam::hPowerThermo< EquationOfState >
Power-function based thermodynamics package templated on EquationOfState.
In this thermodynamics package the heat capacity is a simple power of temperature:
Cp(T) = c0*(T/Tref)^n0;
which is particularly suitable for solids.
Source files
hPowerThermo.H
hPowerThermoI.H
hPowerThermo.C
Definition at line 55 of file hPowerThermo.H.
Constructor & Destructor Documentation
hPowerThermo (const dictionary & dict)
Construct from dictionary.
Definition at line 28 of file hPowerThermo.C.
hPowerThermo (const word & name, const hPowerThermo< EquationOfState > & jt) inline
Construct as a named copy.
Definition at line 44 of file hPowerThermoI.H.
Member Function Documentation
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > clone () const inline
Construct and return a clone.
Definition at line 79 of file hPowerThermoI.H.
Foam::autoPtr< Foam::hPowerThermo< EquationOfState > > New (const dictionary & dict) inline static
Selector from dictionary.
Definition at line 87 of file hPowerThermoI.H.
References Foam::New().
static word typeName () inline static
Return the instantiated type name.
Definition at line 159 of file hPowerThermo.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 97 of file hPowerThermoI.H.
Foam::scalar Cp (const scalar p, const scalar T) const inline
Heat capacity at constant pressure [J/(kg K)].
Definition at line 107 of file hPowerThermoI.H.
References Foam::T().
Foam::scalar Ha (const scalar p, const scalar T) const inline
Absolute Enthalpy [J/kg].
Definition at line 117 of file hPowerThermoI.H.
References Cp, and Foam::pow().
Foam::scalar Hs (const scalar p, const scalar T) const inline
Sensible enthalpy [J/kg].
Definition at line 127 of file hPowerThermoI.H.
References Hs().
Foam::scalar Hc () const inline
Chemical enthalpy [J/kg].
Definition at line 138 of file hPowerThermoI.H.
Foam::scalar S (const scalar p, const scalar T) const inline
Entropy [J/(kg K)].
Definition at line 146 of file hPowerThermoI.H.
References Hf_().
Foam::scalar dGdT (const scalar p, const scalar T) const inline
Derivative of Gibbs free energy w.r.t. temperature.
Definition at line 158 of file hPowerThermoI.H.
Foam::scalar dCpdT (const scalar p, const scalar T) const inline
Temperature derivative of heat capacity at constant pressure.
Definition at line 170 of file hPowerThermoI.H.
void operator+= (const hPowerThermo< EquationOfState > &) inline
Definition at line 184 of file hPowerThermoI.H.
Friends And Related Function Documentation
hPowerThermo operator+ (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
hPowerThermo operator* (const scalar , const hPowerThermo< EquationOfState > &) friend
hPowerThermo operator== (const hPowerThermo< EquationOfState > & , const hPowerThermo< EquationOfState > &) friend
Ostream& operator (Ostream & , const hPowerThermo< EquationOfState > &) friend
The documentation for this class was generated from the following files:
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.H
src/thermophysicalModels/specie/thermo/hPower/hPowerThermo.C
src/thermophysicalModels/specie/thermo/hPower/hPowerThermoI.H