OpenFOAM: mapDistribute Class Reference
mapDistribute Class Reference
Class containing processor-to-processor mapping information.
Classes
class transform
Default transformation behaviour.
class transformPosition
Default transformation behaviour for position.
Public Member Functions
ClassName ("mapDistribute")
mapDistribute ()
Construct null.
mapDistribute (const mapDistribute &map)
Copy construct.
mapDistribute (mapDistribute &&map)
Move construct.
mapDistribute (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Move construct from components.
mapDistribute (const label constructSize, labelListList &&subMap, labelListList &&constructMap, labelListList &&transformElements, labelList &&transformStart, const bool subHasFlip=false, const bool constructHasFlip=false)
Move construct from components.
mapDistribute (const labelUList &sendProcs, const labelUList &recvProcs)
Construct from reverse addressing: per data item the send processor and the receive processor.
mapDistribute (const globalIndex &, labelList &elements, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex numbering (or -1).
mapDistribute (const globalIndex &, labelListList &cellCells, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Special variant that works with the info sorted into bins according to local indices.
mapDistribute (const globalIndex &, labelList &untransformedElements, const globalIndexAndTransform &, const labelPairList &transformedElements, labelList &transformedIndices, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly remote) untransformed elements in globalIndex numbering (or -1) and (possibly remote) transformed elements in globalIndexAndTransform numbering.
mapDistribute (const globalIndex &, labelListList &cellCells, const globalIndexAndTransform &, const List< labelPairList > &transformedElements, labelListList &transformedIndices, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
As above but with ListLists.
mapDistribute (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from my elements to send. Assumes layout is my elements.
mapDistribute (Istream &is)
Construct from Istream.
autoPtr< mapDistribute > clone () const
Clone.
virtual ~mapDistribute ()=default
Destructor.
const labelListList & transformElements () const
For every globalIndexAndTransform::transformPermutations.
const labelList & transformStart () const
Destination in constructMap for transformed elements.
label whichTransform (const label index) const
Find transform from transformElements.
void transfer (mapDistribute &map)
Transfer the contents of the argument and annul the argument.
template<class T >
void distribute (List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T , class negateOp >
void distribute (List< T > &fld, const negateOp &negOp, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void distribute (DynamicList< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, List< T > &, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const bool dummyTransform=true, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T , class TransformOp >
void distribute (const globalIndexAndTransform &, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Distribute with transforms.
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Reverse distribute with transforms.
template<class T , class TransformOp >
void reverseDistribute (const globalIndexAndTransform &, const label constructSize, const T &nullValue, List< T > &fld, const TransformOp &top, const int tag=UPstream::msgType()) const
Reverse distribute with transforms.
void printLayout (Ostream &os) const
Debug: print layout. Can only be used on maps with sorted.
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistribute &rhs)
Copy assignment.
void operator= (mapDistribute &&rhs)
Move assignment.
Public Member Functions inherited from mapDistributeBase
ClassName ("mapDistributeBase")
mapDistributeBase ()
Construct null.
mapDistributeBase (const mapDistributeBase &map)
Copy construct.
mapDistributeBase (mapDistributeBase &&map)
Move construct.
mapDistributeBase (const label constructSize, labelListList &&subMap, labelListList &&constructMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from components.
mapDistributeBase (const labelUList &sendProcs, const labelUList &recvProcs)
Construct from reverse addressing: per data item the send.
mapDistributeBase (const globalIndex &, labelList &elements, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex.
mapDistributeBase (const globalIndex &, labelListList &cellCells, List< Map< label >> &compactMap, const int tag=Pstream::msgType())
Special variant that works with the info sorted into bins.
mapDistributeBase (labelListList &&subMap, const bool subHasFlip=false, const bool constructHasFlip=false)
Construct from my elements to send. Assumes layout is my elements.
mapDistributeBase (Istream &is)
Construct from Istream.
label constructSize () const
Constructed data size.
label & constructSize ()
Constructed data size.
const labelListList & subMap () const
From subsetted data back to original data.
labelListList & subMap ()
From subsetted data back to original data.
const labelListList & constructMap () const
From subsetted data to new reconstructed data.
labelListList & constructMap ()
From subsetted data to new reconstructed data.
bool subHasFlip () const
Does subMap include a sign.
bool & subHasFlip ()
Does subMap include a sign.
bool constructHasFlip () const
Does constructMap include a sign.
bool & constructHasFlip ()
Does constructMap include a sign.
const List< labelPair > & schedule () const
Return a schedule. Demand driven. See above.
void transfer (mapDistributeBase &rhs)
Transfer the contents of the argument and annul the argument.
void compact (const boolList &elemIsUsed, const int tag=UPstream::msgType())
Compact maps. Gets per field a bool whether it is used (locally)
void compact (const boolList &elemIsUsed, const label localSize, labelList &oldToNewSub, labelList &oldToNewConstruct, const int tag=UPstream::msgType())
Compact all maps and layout. Returns compaction maps for.
template<class T >
void distribute (List< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T , class negateOp >
void distribute (List< T > &fld, const negateOp &negOp, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void distribute (DynamicList< T > &fld, const int tag=UPstream::msgType()) const
Distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, List< T > &, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void reverseDistribute (const label constructSize, const T &nullValue, List< T > &fld, const int tag=UPstream::msgType()) const
Reverse distribute data using default commsType.
template<class T >
void send (PstreamBuffers &, const List< T > &) const
Do all sends using PstreamBuffers.
template<class T >
void receive (PstreamBuffers &, List< T > &) const
Do all receives using PstreamBuffers.
void printLayout (Ostream &os) const
Debug: print layout. Can only be used on maps with sorted.
void updateMesh (const mapPolyMesh &)
Correct for topo change.
void operator= (const mapDistributeBase &rhs)
Copy assignment.
void operator= (mapDistributeBase &&rhs)
Move assignment.
Friends
Istream & operator>> (Istream &, mapDistribute &)
Read dictionary from Istream.
Ostream & operator<< (Ostream &, const mapDistribute &)
Write dictionary to Ostream.
Additional Inherited Members
Static Public Member Functions inherited from mapDistributeBase
static List< labelPair > schedule (const labelListList &subMap, const labelListList &constructMap, const int tag)
Calculate a schedule. See above.
static label renumber (const globalIndex &, const List< Map< label >> &compactMap, const label globalElement)
Helper for construct from globalIndex. Renumbers element.
template<class T , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const negateOp &negOp, const int tag=UPstream::msgType())
Distribute data. Note:schedule only used for.
template<class T , class CombineOp , class negateOp >
static void distribute (const Pstream::commsTypes commsType, const List< labelPair > &schedule, const label constructSize, const labelListList &subMap, const bool subHasFlip, const labelListList &constructMap, const bool constructHasFlip, List< T > &, const CombineOp &cop, const negateOp &negOp, const T &nullValue, const int tag=UPstream::msgType())
Distribute data. If multiple processors writing to same.
Protected Member Functions inherited from mapDistributeBase
void calcCompactAddressing (const globalIndex &globalNumbering, const labelUList &elements, List< Map< label >> &compactMap) const
Construct per processor compact addressing of the global elements.
void calcCompactAddressing (const globalIndex &globalNumbering, const labelListList &elements, List< Map< label >> &compactMap) const
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelList &elements, List< Map< label >> &compactMap, labelList &compactStart)
void exchangeAddressing (const int tag, const globalIndex &globalNumbering, labelListList &elements, List< Map< label >> &compactMap, labelList &compactStart)
Static Protected Member Functions inherited from mapDistributeBase
static void checkReceivedSize (const label proci, const label expectedSize, const label receivedSize)
template<class T , class CombineOp , class negateOp >
static void flipAndCombine (const labelUList &map, const bool hasFlip, const UList< T > &rhs, const CombineOp &cop, const negateOp &negOp, List< T > &lhs)
template<class T , class negateOp >
static T accessAndFlip (const UList< T > &fld, const label index, const bool hasFlip, const negateOp &negOp)
Protected Attributes inherited from mapDistributeBase
label constructSize_
Size of reconstructed data.
labelListList subMap_
Maps from subsetted data back to original data.
labelListList constructMap_
Maps from subsetted data to new reconstructed data.
bool subHasFlip_
Whether subMap includes flip or not.
bool constructHasFlip_
Whether constructMap includes flip or not.
autoPtr< List< labelPair > > schedulePtr_
Schedule.
Detailed Description
Class containing processor-to-processor mapping information.
We store mapping from the bits-to-send to the complete starting list (subXXXMap) and from the received bits to their location in the new list (constructXXXMap).
Note: Schedule is a list of processor pairs (one send, one receive. One of them will be myself) which forms a scheduled (i.e. non-buffered) exchange. See distribute on how to use it. Note2: number of items sent on one processor have to equal the number of items received on the other processor.
To aid constructing these maps there are the constructors from global numbering, either with or without transforms.
without transforms: Constructors using compact numbering: layout is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor. So e.g 4 procs and on proc 1 the compact table will first have all globalIndex.localSize() elements from proc1 followed by used-only elements of proc0, proc2, proc3. The constructed mapDistribute sends the local elements from and receives the remote elements into their compact position. compactMap[proci] is the position of elements from proci in the compact map. compactMap[myProcNo()] is empty since trivial addressing.
It rewrites the input global indices into indices into the constructed data.
with transforms: This requires the precalculated set of possible transforms (globalIndexAndTransform). These are given as permutations (+, -, or none) of up to 3 independent transforms. The layout of the data is
all my own elements first (whether used or not)
followed by used-only remote elements sorted by remote processor.
followed by - for each transformation index - the set of local or remote elements with that transformation. The inputs for the constructor are
the set of untransformed local or remote indices in globalIndex numbering. These get rewritten to be indices into the layout of the data.
the set of transformed local or remote indices in globalIndexAndTransform encoding. These are labelPairs.
Any distribute with transforms is now done as: 1. exchange data with other processors and receive these into the slots for that processor 2. for all transformations transform a subset of the data according to transformElements_[transformI] and store this starting from transformStart_[transformI]
In the same way a reverse distribute will 1. apply the inverse transform to the data starting at transformStart_[transformI] and copy the result back into the transformElements_[transformI]. These might be local or remote slots. 2. the data in the remote slots will now be sent back to the correct location in the originating processor.
E.g. a map to handle
mesh points on a mesh with
1 cyclic so 3 permutations (+,-,none) will have layout
on e.g. processor 1 out of 2:
+——+ <- transformStart[2] | | | | <- transform2 applied to data in local or remote slots | | +——+ <- transformStart[1] | | | | <- transform1 applied to data in local or remote slots | | +——+ <- transformStart[1] | | | | <- transform0 applied to data in local or remote slots | | +——+ <- transformStart[0] | | | | <- data from proc2 | | +——+ | | | | <- data from proc0 | | +——+ <- mesh.nPoints() | | | | | | +——+ 0
When constructing from components optionally a 'flip' on the maps can be specified. This will interpret the map values as index+flip, similar to e.g. faceProcAddressing. The flip will only be applied to fieldTypes (scalar, vector, .. triad)
Source files
mapDistribute.H
mapDistribute.C
mapDistributeTemplates.C
Definition at line 159 of file mapDistribute.H.
Constructor & Destructor Documentation
mapDistribute ()
Construct null.
Definition at line 144 of file mapDistribute.C.
mapDistribute (const mapDistribute & map) explicit
Copy construct.
Definition at line 150 of file mapDistribute.C.
mapDistribute (mapDistribute && map) explicit
Move construct.
Definition at line 158 of file mapDistribute.C.
mapDistribute (const label constructSize, labelListList && subMap, labelListList && constructMap, const bool subHasFlip = false, const bool constructHasFlip = false)
Move construct from components.
Definition at line 167 of file mapDistribute.C.
References transfer().
mapDistribute (const label constructSize, labelListList && subMap, labelListList && constructMap, labelListList && transformElements, labelList && transformStart, const bool subHasFlip = false, const bool constructHasFlip = false)
Move construct from components.
Definition at line 187 of file mapDistribute.C.
mapDistribute (const labelUList & sendProcs, const labelUList & recvProcs)
Construct from reverse addressing: per data item the send processor and the receive processor.
Note
data are not stored per processor so cannot use printLayout.
Definition at line 211 of file mapDistribute.C.
mapDistribute (const globalIndex & globalNumbering, labelList & elements, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Construct from list of (possibly) remote elements in globalIndex numbering (or -1).
Determines compact numbering (see above) and distribute map to get data into this ordering and renumbers the elements to be in compact numbering.
Definition at line 221 of file mapDistribute.C.
mapDistribute (const globalIndex & globalNumbering, labelListList & cellCells, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Special variant that works with the info sorted into bins according to local indices.
For example, cellCells where cellCells[localCelli] is a list of global cells.
Definition at line 239 of file mapDistribute.C.
mapDistribute (const globalIndex & globalNumbering, labelList & untransformedElements, const globalIndexAndTransform & globalTransforms, const labelPairList & transformedElements, labelList & transformedIndices, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
Construct from list of (possibly remote) untransformed elements in globalIndex numbering (or -1) and (possibly remote) transformed elements in globalIndexAndTransform numbering.
Determines compact numbering (see above) and distribute map to get data into this ordering and renumbers the elements to be in compact numbering.
Definition at line 257 of file mapDistribute.C.
mapDistribute (const globalIndex & globalNumbering, labelListList & cellCells, const globalIndexAndTransform & globalTransforms, const List< labelPairList > & transformedElements, labelListList & transformedIndices, List< Map< label >> & compactMap, const int tag = Pstream::msgType())
As above but with ListLists.
Definition at line 362 of file mapDistribute.C.
References Foam::Pout, and mapDistribute::printLayout().
mapDistribute (labelListList && subMap, const bool subHasFlip = false, const bool constructHasFlip = false) explicit
Construct from my elements to send. Assumes layout is my elements.
first followed by elements from all other processors in consecutive order
Definition at line 480 of file mapDistribute.C.
References Foam::Pout, and mapDistribute::printLayout().
mapDistribute (Istream & is) explicit
Construct from Istream.
Definition at line 490 of file mapDistribute.C.
virtual ~mapDistribute () virtual default
Destructor.
Member Function Documentation
ClassName ("mapDistribute")
Foam::autoPtr< Foam::mapDistribute > clone () const
Clone.
Definition at line 496 of file mapDistribute.C.
const labelListList& transformElements () const inline
For every globalIndexAndTransform::transformPermutations.
gives the elements that need to be transformed
Definition at line 502 of file mapDistribute.H.
const labelList& transformStart () const inline
Destination in constructMap for transformed elements.
Definition at line 510 of file mapDistribute.H.
Foam::label whichTransform (const label index) const
Find transform from transformElements.
Definition at line 504 of file mapDistribute.C.
References autoPtr< T >::New().
void transfer (mapDistribute & map)
Transfer the contents of the argument and annul the argument.
Definition at line 510 of file mapDistribute.C.
References Foam::findLower().
void distribute (List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 149 of file mapDistributeTemplates.C.
Referenced by extendedCellToFaceStencil::collectData(), extendedFaceToCellStencil::collectData(), mappedPatchBase::distribute(), mapDistributePolyMesh::faceMap(), inverseDistance::findHoles(), distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getVolumeType(), distributedTriSurfaceMesh::localQueries(), mapDistributePolyMesh::pointMap(), PatchTools::pointNormals(), globalMeshData::syncData(), and pointConstraints::syncUntransformedData().
void distribute (List< T > & fld, const negateOp & negOp, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Fill in transformed slots with copies
Definition at line 125 of file mapDistributeTemplates.C.
void distribute (DynamicList< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Distribute data using default commsType.
Definition at line 161 of file mapDistributeTemplates.C.
References fld, DynamicList< T, SizeMin >::setCapacity(), DynamicList< T, SizeMin >::shrink(), and UList< T >::size().
void reverseDistribute (const label constructSize, List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Definition at line 179 of file mapDistributeTemplates.C.
References mapDistributeBase::reverseDistribute().
Referenced by distributedTriSurfaceMesh::findNearest(), distributedTriSurfaceMesh::getField(), distributedTriSurfaceMesh::getNormal(), distributedTriSurfaceMesh::getRegion(), PatchTools::pointNormals(), globalMeshData::syncData(), and pointConstraints::syncUntransformedData().
void reverseDistribute (const label constructSize, const T & nullValue, List< T > & fld, const bool dummyTransform = true, const int tag = UPstream::msgType()) const
Reverse distribute data using default commsType.
Since constructSize might be larger than supplied size supply a nullValue
Definition at line 197 of file mapDistributeTemplates.C.
References mapDistributeBase::reverseDistribute().
void distribute (const globalIndexAndTransform & git, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Distribute with transforms.
Definition at line 216 of file mapDistributeTemplates.C.
void reverseDistribute (const globalIndexAndTransform & git, const label constructSize, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Reverse distribute with transforms.
Definition at line 232 of file mapDistributeTemplates.C.
void reverseDistribute (const globalIndexAndTransform & git, const label constructSize, const T & nullValue, List< T > & fld, const TransformOp & top, const int tag = UPstream::msgType()) const
Reverse distribute with transforms.
Definition at line 252 of file mapDistributeTemplates.C.
void printLayout (Ostream & os) const
Debug: print layout. Can only be used on maps with sorted.
storage (local data first, then non-local data)
Definition at line 126 of file mapDistribute.C.
Referenced by mapDistribute::mapDistribute().
void updateMesh (const mapPolyMesh &) inline
Correct for topo change.
Definition at line 639 of file mapDistribute.H.
void operator= (const mapDistribute & rhs)
Copy assignment.
Definition at line 525 of file mapDistribute.C.
Referenced by IOmapDistribute::IOmapDistribute().
void operator= (mapDistribute && rhs)
Move assignment.
Definition at line 538 of file mapDistribute.C.
Friends And Related Function Documentation
Istream& operator>> (Istream & , mapDistribute &) friend
Read dictionary from Istream.
Ostream& operator<< (Ostream & , const mapDistribute &) friend
Write dictionary to Ostream.
The documentation for this class was generated from the following files:
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.H
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistribute.C
src/OpenFOAM/meshes/polyMesh/mapPolyMesh/mapDistribute/mapDistributeTemplates.C