OpenFOAM: processorCyclicFvPatch Class Reference
processorCyclicFvPatch Class Reference
Processor patch.
Public Member Functions
TypeName (processorCyclicPolyPatch::typeName_())
Runtime type information.
processorCyclicFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from components.
virtual int tag () const
Return message tag used for sending.
const processorCyclicPolyPatch & procPolyPatch () const
virtual bool parallel () const
Are the cyclic planes parallel.
virtual const tensorField & forwardT () const
Return face transformation tensor.
virtual const tensorField & reverseT () const
Return neighbour-cell transformation tensor.
Public Member Functions inherited from processorFvPatch
TypeName (processorPolyPatch::typeName_())
Runtime type information.
processorFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from components.
virtual label comm () const
Return communicator used for comms.
virtual int myProcNo () const
Return processor number.
virtual int neighbProcNo () const
Return neighbour processor number.
virtual bool coupled () const
Return true if running parallel.
const processorPolyPatch & procPolyPatch () const
virtual tmp< vectorField > delta () const
Return delta (P to N) vectors across coupled patch.
virtual tmp< labelField > interfaceInternalField (const labelUList &internalData) const
Return the values of the given internal data adjacent to.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Initialise neighbour field transfer.
virtual tmp< labelField > internalFieldTransfer (const Pstream::commsTypes commsType, const labelUList &internalData) const
Return neighbour field.
Public Member Functions inherited from coupledFvPatch
TypeName (coupledPolyPatch::typeName_())
Runtime type information.
coupledFvPatch (const polyPatch &patch, const fvBoundaryMesh &bm)
Construct from polyPatch.
virtual ~coupledFvPatch ()
Destructor.
virtual const labelUList & faceCells () const
Return faceCell addressing.
virtual void initInternalFieldTransfer (const Pstream::commsTypes commsType, labelUList &iF) const
Initialise neighbour field transfer.
Public Member Functions inherited from lduInterface
TypeName ("lduInterface")
Runtime type information.
lduInterface ()=default
Construct null.
virtual ~lduInterface ()=default
Destructor.
Public Member Functions inherited from fvPatch
TypeName (polyPatch::typeName_())
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvPatch, polyPatch,(const polyPatch &patch, const fvBoundaryMesh &bm),(patch, bm))
fvPatch (const polyPatch &, const fvBoundaryMesh &)
Construct from polyPatch and fvBoundaryMesh.
virtual ~fvPatch ()
Destructor.
const polyPatch & patch () const
Return the polyPatch.
virtual const word & name () const
Return name.
virtual label start () const
Return start label of this patch in the polyMesh face list.
virtual label size () const
Return size.
label index () const
Return the index of this patch in the fvBoundaryMesh.
const fvBoundaryMesh & boundaryMesh () const
Return boundaryMesh reference.
template<class T >
const List< T >::subList patchSlice (const List< T > &l) const
Slice list to patch.
const vectorField & Cf () const
Return face centres.
tmp< vectorField > Cn () const
Return neighbour cell centres.
const vectorField & Sf () const
Return face area vectors.
const scalarField & magSf () const
Return face area magnitudes.
tmp< vectorField > nf () const
Return face normals.
const scalarField & weights () const
Return patch weighting factors.
const scalarField & deltaCoeffs () const
Return the face - cell distance coefficient except for coupled patches for which the cell-centre to coupled-cell-centre distance coefficient is returned.
template<class Type >
tmp< Field< Type > > patchInternalField (const UList< Type > &) const
Return given internal field next to patch as patch field.
template<class Type >
void patchInternalField (const UList< Type > &, Field< Type > &) const
Return given internal field next to patch as patch field.
template<class GeometricField , class Type >
const GeometricField::Patch & patchField (const GeometricField &) const
Return the corresponding patchField of the named field.
template<class GeometricField , class Type >
const GeometricField::Patch & lookupPatchField (const word &name, const GeometricField *=nullptr, const Type *=nullptr) const
Lookup and return the patchField of the named field from the local objectRegistry.
template<class Type >
Foam::tmp< Foam::Field< Type > > patchInternalField (const UList< Type > &f) const
Public Member Functions inherited from processorLduInterface
TypeName ("processorLduInterface")
Runtime type information.
processorLduInterface ()=default
Construct null.
virtual ~processorLduInterface ()=default
Destructor.
template<class Type >
void send (const Pstream::commsTypes commsType, const UList< Type > &f) const
Raw send function.
template<class Type >
void receive (const Pstream::commsTypes commsType, UList< Type > &f) const
Raw receive function.
template<class Type >
tmp< Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
Raw receive function returning field.
template<class Type >
void compressedSend (const Pstream::commsTypes commsType, const UList< Type > &f) const
Raw send function with data compression.
template<class Type >
void compressedReceive (const Pstream::commsTypes commsType, UList< Type > &f) const
Raw receive function with data compression.
template<class Type >
tmp< Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Raw receive function with data compression returning field.
template<class Type >
Foam::tmp< Foam::Field< Type > > receive (const Pstream::commsTypes commsType, const label size) const
template<class Type >
Foam::tmp< Foam::Field< Type > > compressedReceive (const Pstream::commsTypes commsType, const label size) const
Additional Inherited Members
Public Types inherited from fvPatch
typedef fvBoundaryMesh BoundaryMesh
Static Public Member Functions inherited from fvPatch
static autoPtr< fvPatch > New (const polyPatch &, const fvBoundaryMesh &)
Return a pointer to a new patch created on freestore from polyPatch.
static bool constraintType (const word &pt)
Return true if the given type is a constraint type.
static wordList constraintTypes ()
Return a list of all the constraint patch types.
Protected Member Functions inherited from processorFvPatch
void makeWeights (scalarField &) const
Make patch weighting factors.
Protected Member Functions inherited from fvPatch
virtual void initMovePoints ()
Initialise the patches for moving points.
virtual void movePoints ()
Correct patches after moving points.
Detailed Description
Processor patch.
Source files
processorCyclicFvPatch.H
processorCyclicFvPatch.C
Definition at line 47 of file processorCyclicFvPatch.H.
Constructor & Destructor Documentation
processorCyclicFvPatch (const polyPatch & patch, const fvBoundaryMesh & bm) inline
Construct from components.
Definition at line 68 of file processorCyclicFvPatch.H.
Member Function Documentation
TypeName (processorCyclicPolyPatch:: typeName_())
Runtime type information.
virtual int tag () const inline virtual
Return message tag used for sending.
Reimplemented from processorFvPatch.
Definition at line 80 of file processorCyclicFvPatch.H.
References processorCyclicPolyPatch::tag().
const processorCyclicPolyPatch& procPolyPatch () const inline
Definition at line 86 of file processorCyclicFvPatch.H.
virtual bool parallel () const inline virtual
Are the cyclic planes parallel.
Reimplemented from processorFvPatch.
Definition at line 94 of file processorCyclicFvPatch.H.
Referenced by processorCyclicFvPatchField< Type >::clone().
virtual const tensorField& forwardT () const inline virtual
Return face transformation tensor.
Reimplemented from processorFvPatch.
Definition at line 102 of file processorCyclicFvPatch.H.
References processorCyclicPolyPatch::reverseT().
virtual const tensorField& reverseT () const inline virtual
Return neighbour-cell transformation tensor.
Reimplemented from processorFvPatch.
Definition at line 110 of file processorCyclicFvPatch.H.
The documentation for this class was generated from the following file:
src/finiteVolume/fvMesh/fvPatches/constraint/processorCyclic/processorCyclicFvPatch.H