OpenFOAM: cellCellStencil Class Reference
cellCellStencil Class Reference abstract
Calculation of interpolation stencils.
Public Types
enum patchCellType { OTHER = 0, PATCH = 1, OVERSET = 2 }
enum cellType { CALCULATED = 0, INTERPOLATED = 1, HOLE = 2 }
Public Member Functions
TypeName ("cellCellStencil")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, cellCellStencil, mesh,(const fvMesh &mesh, const dictionary &dict, const bool update),(mesh, dict, update))
cellCellStencil (const fvMesh &)
Construct from fvMesh.
virtual ~cellCellStencil ()
Destructor.
virtual bool update ()=0
Update stencils. Return false if nothing changed.
virtual const labelUList & cellTypes () const =0
Return the cell type list.
virtual const labelUList & interpolationCells () const =0
Indices of interpolated cells.
virtual const mapDistribute & cellInterpolationMap () const =0
Return a communication schedule.
virtual const labelListList & cellStencil () const =0
Per interpolated cell the neighbour cells (in terms of slots as.
virtual const List< scalarList > & cellInterpolationWeights () const =0
Weights for cellStencil.
virtual const scalarList & cellInterpolationWeight () const =0
Per interpolated cell the interpolation factor. (0 = use.
virtual void stencilWeights (const point &sample, const pointList &donorCcs, scalarList &weights) const =0
Calculate weights for a single acceptor.
virtual const wordHashSet & nonInterpolatedFields () const
Return the names of any (stencil or mesh specific) fields that.
virtual wordHashSet & nonInterpolatedFields ()
Return non-const non-interpolating fields.
bool localStencil (const labelUList &) const
Helper: is stencil fully local.
const labelIOList & zoneID () const
Helper: get reference to registered zoneID. Loads volScalarField.
template<class Type >
Foam::tmp< Foam::volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &psi)
Static Public Member Functions
static autoPtr< cellCellStencil > New (const fvMesh &, const dictionary &dict, const bool update=true)
New function which constructs and returns pointer to a.
static const labelIOList & zoneID (const fvMesh &)
Helper: get reference to registered zoneID. Loads volScalarField.
static void globalCellCells (const globalIndex &gi, const polyMesh &mesh, const boolList &isValidDonor, const labelList &selectedCells, labelListList &cellCells, pointListList &cellCellCentres)
Helper: create cell-cell addressing in global numbering.
Static Protected Member Functions
static labelList count (const label size, const labelUList &lst)
Count ocurrences (in parallel)
template<class Type >
static tmp< volScalarField > createField (const fvMesh &mesh, const word &name, const UList< Type > &)
Helper: create volScalarField for postprocessing.
Protected Attributes
const fvMesh & mesh_
Reference to the mesh.
wordHashSet nonInterpolatedFields_
Set of fields that should not be interpolated.
Static Protected Attributes
static const Enum< cellType > cellTypeNames_
Mode type names.
Detailed Description
Calculation of interpolation stencils.
Looks up zoneID labelIOList to give the zoning. Wrapped in MeshObject as cellCellStencilObject. Kept separate so meshes can implement more clever methods (e.g. solid body motion does not require full recalculation)
Source files
cellCellStencil.H
cellCellStencil.C
cellCellStencilObject.C
Definition at line 57 of file cellCellStencil.H.
Member Enumeration Documentation
enum patchCellType
Enumerator
OTHER
PATCH
OVERSET
Definition at line 61 of file cellCellStencil.H.
enum cellType
Enumerator
CALCULATED
INTERPOLATED
HOLE
Definition at line 68 of file cellCellStencil.H.
Constructor & Destructor Documentation
cellCellStencil (const fvMesh & mesh)
Construct from fvMesh.
Definition at line 49 of file cellCellStencil.C.
virtual ~cellCellStencil () virtual
Destructor.
Member Function Documentation
static labelList count (const label size, const labelUList & lst) static protected
Count ocurrences (in parallel)
static tmp<volScalarField> createField (const fvMesh & mesh, const word & name, const UList< Type > &) static protected
Helper: create volScalarField for postprocessing.
TypeName ("cellCellStencil")
Runtime type information.
declareRunTimeSelectionTable (autoPtr , cellCellStencil , mesh , (const fvMesh &mesh, const dictionary &dict, const bool update) , (mesh, dict, update))
static autoPtr<cellCellStencil> New (const fvMesh & , const dictionary & dict, const bool update = true) static
New function which constructs and returns pointer to a.
cellCellStencil
virtual bool update () pure virtual
Update stencils. Return false if nothing changed.
Implemented in inverseDistance, cellVolumeWeight, trackingInverseDistance, and cellCellStencilObject.
virtual const labelUList& cellTypes () const pure virtual
Return the cell type list.
Implemented in inverseDistance, cellVolumeWeight, and cellCellStencilObject.
virtual const labelUList& interpolationCells () const pure virtual
Indices of interpolated cells.
Implemented in inverseDistance, cellVolumeWeight, and cellCellStencilObject.
Referenced by dynamicOversetFvMesh::interpolate().
virtual const mapDistribute& cellInterpolationMap () const pure virtual
Return a communication schedule.
Implemented in inverseDistance, cellVolumeWeight, and cellCellStencilObject.
Referenced by dynamicOversetFvMesh::interpolate().
virtual const labelListList& cellStencil () const pure virtual
Per interpolated cell the neighbour cells (in terms of slots as.
constructed by above cellInterpolationMap) to interpolate
Implemented in inverseDistance, cellVolumeWeight, and cellCellStencilObject.
Referenced by dynamicOversetFvMesh::interpolate().
virtual const List<scalarList>& cellInterpolationWeights () const pure virtual
Weights for cellStencil.
Implemented in inverseDistance, cellVolumeWeight, and cellCellStencilObject.
Referenced by dynamicOversetFvMesh::interpolate().
virtual const scalarList& cellInterpolationWeight () const pure virtual
Per interpolated cell the interpolation factor. (0 = use.
calculated, 1 = use interpolated)
Implemented in inverseDistance, cellVolumeWeight, and cellCellStencilObject.
Referenced by dynamicOversetFvMesh::interpolate().
virtual void stencilWeights (const point & sample, const pointList & donorCcs, scalarList & weights) const pure virtual
Calculate weights for a single acceptor.
Implemented in inverseDistance, cellVolumeWeight, cellCellStencilObject, and leastSquares.
virtual const wordHashSet& nonInterpolatedFields () const virtual
Return the names of any (stencil or mesh specific) fields that.
should not be interpolated
Reimplemented in cellCellStencilObject.
virtual wordHashSet& nonInterpolatedFields () virtual
Return non-const non-interpolating fields.
bool localStencil (const labelUList &) const
Helper: is stencil fully local.
static const labelIOList& zoneID (const fvMesh &) static
Helper: get reference to registered zoneID. Loads volScalarField.
if not registered.
Referenced by Foam::oversetAdjustPhi().
const labelIOList& zoneID () const inline
Helper: get reference to registered zoneID. Loads volScalarField.
if not registered.
Definition at line 260 of file cellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight().
static void globalCellCells (const globalIndex & gi, const polyMesh & mesh, const boolList & isValidDonor, const labelList & selectedCells, labelListList & cellCells, pointListList & cellCellCentres) static
Helper: create cell-cell addressing in global numbering.
Foam::tmp<Foam::volScalarField> createField (const fvMesh & mesh, const word & name, const UList< Type > & psi)
Definition at line 28 of file cellCellStencilTemplates.C.
References Foam::dimless, fld, forAll, mesh, IOobject::NO_READ, IOobject::NO_WRITE, tmp< T >::ref(), fvMesh::time(), Time::timeName(), and Foam::Zero.
Member Data Documentation
const Foam::Enum< Foam::cellCellStencil::cellType > cellTypeNames_ static protected
Mode type names.
Definition at line 83 of file cellCellStencil.H.
const fvMesh& mesh_ protected
Reference to the mesh.
Definition at line 88 of file cellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight(), and cellVolumeWeight::walkFront().
wordHashSet nonInterpolatedFields_ protected
Set of fields that should not be interpolated.
Definition at line 93 of file cellCellStencil.H.
Referenced by cellVolumeWeight::cellVolumeWeight().
The documentation for this class was generated from the following files:
src/overset/cellCellStencil/cellCellStencil/cellCellStencil.H
src/overset/cellCellStencil/cellCellStencil/cellCellStencil.C
src/overset/cellCellStencil/cellCellStencil/cellCellStencilTemplates.C