OpenFOAM: topoSetSource Class Reference
topoSetSource Class Reference abstract
Base class of a source for a topoSet.
Classes
class addToUsageTable
Class with constructor to add usage string to table.
class iNew
Class used for the read-construction of.
Public Types
enum sourceType {
UNKNOWN_SOURCE = 0, SET_SOURCE = 0x10, ZONE_SOURCE = 0x20, CELL_TYPE = 0x1,
FACE_TYPE = 0x2, POINT_TYPE = 0x4, CELLSET_SOURCE = (CELL_TYPE | SET_SOURCE), FACESET_SOURCE = (FACE_TYPE | SET_SOURCE),
POINTSET_SOURCE = (POINT_TYPE | SET_SOURCE), CELLZONE_SOURCE = (CELL_TYPE | ZONE_SOURCE), FACEZONE_SOURCE = (FACE_TYPE | ZONE_SOURCE), POINTZONE_SOURCE = (POINT_TYPE | ZONE_SOURCE),
CELLSETSOURCE = CELLSET_SOURCE, FACESETSOURCE = FACESET_SOURCE, POINTSETSOURCE = POINTSET_SOURCE, CELLZONESOURCE = CELLZONE_SOURCE,
FACEZONESOURCE = FACEZONE_SOURCE, POINTZONESOURCE = POINTZONE_SOURCE
}
Enumeration defining the types of sources.
enum setAction {
ADD, SUBTRACT, SUBSET, INVERT,
CLEAR, NEW, REMOVE, LIST,
DELETE = SUBTRACT
}
Enumeration defining the valid actions.
Public Member Functions
TypeName ("topoSetSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, topoSetSource, word,(const polyMesh &mesh, const dictionary &dict),(mesh, dict))
declareRunTimeSelectionTable (autoPtr, topoSetSource, istream,(const polyMesh &mesh, Istream &is),(mesh, is))
topoSetSource (const polyMesh &mesh)
Construct from components.
autoPtr< topoSetSource > clone () const
Clone (disallowed)
virtual ~topoSetSource ()=default
Destructor.
const polyMesh & mesh () const
Reference to the mesh.
bool verbose () const
Return the current verbosity.
void verbose (bool on)
Set the current verbosity.
virtual sourceType setType () const =0
The source category (set/zone, cell/face/point)
virtual void applyToSet (const topoSetSource::setAction action, topoSet &set) const =0
Apply specified action to the topoSet.
Static Public Member Functions
static Istream & checkIs (Istream &is)
Check state of stream.
static bool isSetSource (const sourceType t)
True if a "set" source.
static bool isZoneSource (const sourceType t)
True if a "zone" source.
static bool isCell (const sourceType t)
True if "cell" geometric type.
static bool isFace (const sourceType t)
True if "face" geometric type.
static bool isPoint (const sourceType t)
True if "point" geometric type.
static const string & usage (const word &name)
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, const dictionary &dict)
Return a reference to the selected topoSetSource.
static autoPtr< topoSetSource > New (const word &topoSetSourceType, const polyMesh &mesh, Istream &is)
Return a reference to the selected topoSetSource.
static setAction toAction (const word &actionName)
Deprecated(2018-07) convert string to action.
Static Public Attributes
static const Enum< setAction > actionNames
The setActions text representations.
Protected Member Functions
void addOrDelete (topoSet &set, const label id, const bool add) const
Add or delete id from set. Add when 'add' is true.
void addOrDelete (topoSet &set, const labelUList &labels, const bool add) const
Add or delete labels from set. Add when 'add' is true.
void addOrDelete (topoSet &set, const bitSet &labels, const bool add) const
Add or delete labels from set. Add when 'add' is true.
topoSetSource (const topoSetSource &)=delete
No copy construct.
void operator= (const topoSetSource &)=delete
No copy assignment.
Static Protected Member Functions
static bool check (labelList &list, const label maxLabel)
Detect and remove any values less than 0 or ge maxLabel.
Protected Attributes
const polyMesh & mesh_
Reference to the mesh.
bool verbose_
Verbosity (default: true)
Static Protected Attributes
static const string illegalSource_
static HashTable< string > * usageTablePtr_ = nullptr
A table of usage strings.
Detailed Description
Base class of a source for a topoSet.
Implementer must modify the given set (see applyToSet) according to its function and the setAction (one of add/delete/new)
Source files
topoSetSource.H
topoSetSource.C
Definition at line 62 of file topoSetSource.H.
Member Enumeration Documentation
enum sourceType
Enumeration defining the types of sources.
Enumerator
UNKNOWN_SOURCE
Placeholder.
SET_SOURCE
Source based on topoSet.
ZONE_SOURCE
Source based on mesh zone.
CELL_TYPE
Geometric type is "cell".
FACE_TYPE
Geometric type is "face".
POINT_TYPE
Geometric type is "point".
CELLSET_SOURCE
Cells as set.
FACESET_SOURCE
Faces as set.
POINTSET_SOURCE
Points as set.
CELLZONE_SOURCE
Cells as zone.
FACEZONE_SOURCE
Faces as zone.
POINTZONE_SOURCE
Points as zone.
CELLSETSOURCE
FACESETSOURCE
POINTSETSOURCE
CELLZONESOURCE
FACEZONESOURCE
POINTZONESOURCE
Definition at line 71 of file topoSetSource.H.
enum setAction
Enumeration defining the valid actions.
Enumerator
ADD
Add elements to the set.
SUBTRACT
Subtract elements from the set.
SUBSET
Subset with elements in the set.
INVERT
Invert the elements in the set.
CLEAR
Clear the set, possibly creating it.
NEW
Create a new set and ADD elements to it.
REMOVE
Remove the set (from the file system)
LIST
Print contents of the set.
DELETE
Deprecated:
(2018-10) Alias for SUBTRACT
Definition at line 99 of file topoSetSource.H.
Constructor & Destructor Documentation
topoSetSource (const topoSetSource &) protected delete
No copy construct.
topoSetSource (const polyMesh & mesh) explicit
Construct from components.
Definition at line 224 of file topoSetSource.C.
virtual ~topoSetSource () virtual default
Destructor.
Member Function Documentation
bool check (labelList & list, const label maxLabel) static protected
Detect and remove any values less than 0 or ge maxLabel.
Returns
false if invalid elements were detected (and removed)
Definition at line 66 of file topoSetSource.C.
References i, List< T >::resize(), UList< T >::size(), and Foam::val.
void addOrDelete (topoSet & set, const label id, const bool add) const protected
Add or delete id from set. Add when 'add' is true.
Definition at line 163 of file topoSetSource.C.
void addOrDelete (topoSet & set, const labelUList & labels, const bool add) const protected
Add or delete labels from set. Add when 'add' is true.
Definition at line 181 of file topoSetSource.C.
References topoSet::unset().
void addOrDelete (topoSet & set, const bitSet & labels, const bool add) const protected
Add or delete labels from set. Add when 'add' is true.
Definition at line 199 of file topoSetSource.C.
void operator= (const topoSetSource &) protected delete
No copy assignment.
TypeName ("topoSetSource")
Runtime type information.
Foam::Istream & checkIs (Istream & is) static
Check state of stream.
Definition at line 148 of file topoSetSource.C.
static bool isSetSource (const sourceType t) inline static
True if a "set" source.
Definition at line 231 of file topoSetSource.H.
static bool isZoneSource (const sourceType t) inline static
True if a "zone" source.
Definition at line 239 of file topoSetSource.H.
static bool isCell (const sourceType t) inline static
True if "cell" geometric type.
Definition at line 247 of file topoSetSource.H.
static bool isFace (const sourceType t) inline static
True if "face" geometric type.
Definition at line 255 of file topoSetSource.H.
static bool isPoint (const sourceType t) inline static
True if "point" geometric type.
Definition at line 263 of file topoSetSource.H.
References dict, topoSetSource::iNew::iNew(), topoSetSource::New(), and topoSetSource::iNew::operator()().
declareRunTimeSelectionTable (autoPtr , topoSetSource , word , (const polyMesh &mesh, const dictionary &dict) , (mesh, dict))
declareRunTimeSelectionTable (autoPtr , topoSetSource , istream , (const polyMesh &mesh, Istream &is) , (mesh, is))
static const string& usage (const word & name) inline static
Definition at line 323 of file topoSetSource.H.
autoPtr<topoSetSource> clone () const inline
Clone (disallowed)
Definition at line 344 of file topoSetSource.H.
References topoSetSource::verbose_.
Foam::autoPtr< Foam::topoSetSource > New (const word & topoSetSourceType, const polyMesh & mesh, const dictionary & dict) static
Return a reference to the selected topoSetSource.
Definition at line 102 of file topoSetSource.C.
Referenced by topoSetSource::isPoint().
Foam::autoPtr< Foam::topoSetSource > New (const word & topoSetSourceType, const polyMesh & mesh, Istream & is) static
Return a reference to the selected topoSetSource.
Definition at line 126 of file topoSetSource.C.
const polyMesh& mesh () const inline
Reference to the mesh.
Definition at line 385 of file topoSetSource.H.
bool verbose () const inline
Return the current verbosity.
Definition at line 393 of file topoSetSource.H.
void verbose (bool on) inline
Set the current verbosity.
Definition at line 401 of file topoSetSource.H.
virtual sourceType setType () const pure virtual
The source category (set/zone, cell/face/point)
Implemented in searchableSurfaceToFaceZone, setsToFaceZone, topoSetCellSource, topoSetFaceSource, topoSetPointSource, setAndNormalToFaceZone, setToFaceZone, faceZoneToFaceZone, setToPointZone, and setToCellZone.
virtual void applyToSet (const topoSetSource::setAction action, topoSet & set) const pure virtual
Apply specified action to the topoSet.
Implemented in surfaceToCell, regionToCell, surfaceToPoint, regionsToCell, faceZoneToCell, cellToFace, faceToCell, targetVolumeToCell, pointToFace, cylinderAnnulusToCell, cylinderAnnulusToFace, searchableSurfaceToFaceZone, cylinderToCell, pointToCell, rotatedBoxToCell, cylinderToFace, cylinderToPoint, cellToPoint, faceToPoint, fieldToCell, sphereToCell, sphereToFace, sphereToPoint, searchableSurfaceToCell, searchableSurfaceToFace, searchableSurfaceToPoint, setsToFaceZone, regionToFace, boxToPoint, boxToCell, boxToFace, shapeToCell, normalToFace, setAndNormalToFaceZone, zoneToCell, patchToFace, zoneToFace, zoneToPoint, setToFaceZone, patchToCell, labelToFace, nearestToCell, faceZoneToFaceZone, nearestToPoint, setToPointZone, cellToCell, haloToCell, faceToFace, pointToPoint, nbrToCell, setToCellZone, labelToCell, labelToPoint, badQualityToFace, boundaryToFace, badQualityToCell, and boundaryToCell.
static setAction toAction (const word & actionName) inline static
Deprecated(2018-07) convert string to action.
Deprecated:
(2018-07) - use actionNames[] directly
Definition at line 431 of file topoSetSource.H.
Member Data Documentation
const Foam::Enum< Foam::topoSetSource::setAction > actionNames static
The setActions text representations.
Definition at line 115 of file topoSetSource.H.
const Foam::string illegalSource_ static protected
Definition at line 120 of file topoSetSource.H.
Foam::HashTable< Foam::string > * usageTablePtr_ = nullptr static protected
A table of usage strings.
Definition at line 125 of file topoSetSource.H.
const polyMesh& mesh_ protected
Reference to the mesh.
Definition at line 159 of file topoSetSource.H.
bool verbose_ protected
Verbosity (default: true)
Definition at line 164 of file topoSetSource.H.
Referenced by topoSetSource::clone().
The documentation for this class was generated from the following files:
src/meshTools/sets/topoSetSource/topoSetSource.H
src/meshTools/sets/topoSetSource/topoSetSource.C