OpenFOAM: searchableSurfaceWithGaps Class Reference
searchableSurfaceWithGaps Class Reference
searchableSurface using multiple slightly shifted underlying surfaces to make sure pierces don't go through gaps:
Public Member Functions
TypeName ("searchableSurfaceWithGaps")
Runtime type information.
searchableSurfaceWithGaps (const IOobject &io, const dictionary &dict)
Construct from dictionary (used by searchableSurface)
virtual ~searchableSurfaceWithGaps ()=default
Destructor.
const searchableSurface & surface () const
The underlying searchableSurface.
virtual const wordList & regions () const
Name of regions.
virtual bool hasVolumeType () const
Whether supports volume type (below)
virtual volumeType outsideVolumeType () const
What is type of points outside bounds.
virtual label size () const
Range of local indices that can be returned.
virtual tmp< pointField > coordinates () const
Get representative set of element coordinates.
virtual void boundingSpheres (pointField &centres, scalarField &radiusSqr) const
Get bounding spheres (centre and radius squared), one per element.
virtual tmp< pointField > points () const
Get the points that define the surface.
virtual bool overlaps (const boundBox &bb) const
Does any part of the surface overlap the supplied bound box?
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &info) const
Find nearest on original surface. Note:does not use perturbation.
virtual void findLine (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Find first intersection on segment from start to end.
virtual void findLineAny (const pointField &start, const pointField &end, List< pointIndexHit > &) const
Return any intersection on segment from start to end.
virtual void findLineAll (const pointField &start, const pointField &end, List< List< pointIndexHit >> &) const
Get all intersections in order from start to end.
virtual void getRegion (const List< pointIndexHit > &info, labelList &region) const
From a set of points and indices get the region.
virtual void getNormal (const List< pointIndexHit > &info, vectorField &normal) const
From a set of points and indices get the normal.
virtual void getVolumeType (const pointField &samples, List< volumeType > &info) const
Determine type (inside/outside/mixed) for points.
virtual void setField (const labelList &values)
Set bounds of surface. Bounds currently set as list of.
virtual void getField (const List< pointIndexHit > &info, labelList &values) const
WIP. From a set of hits (points and.
bool writeData (Ostream &os) const
Pure virtual writeData function.
Public Member Functions inherited from searchableSurface
TypeName ("searchableSurface")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, searchableSurface, dict,(const IOobject &io, const dictionary &dict),(io, dict))
searchableSurface (const IOobject &io)
virtual autoPtr
< searchableSurface > clone () const
Clone.
virtual ~searchableSurface ()=default
Destructor.
virtual bool global () const
Is object global.
virtual fileName filePath () const
Return complete path + object name if the file exists.
virtual const boundBox & bounds () const
Return const reference to boundBox.
virtual boundBox & bounds ()
Return non-const access to the boundBox to allow it to be set.
virtual label globalSize () const
Range of global indices that can be returned.
virtual void findNearest (const pointField &samples, const scalarField &nearestDistSqr, const labelList &regionIndices, List< pointIndexHit > &info) const
Find the nearest locations for the supplied points to a.
virtual void findNearest (const pointField &sample, const scalarField &nearestDistSqr, List< pointIndexHit > &, vectorField &normal, labelList &region) const
Find nearest, normal and region. Can be overridden with.
virtual void distribute (const List< treeBoundBox > &, const bool keepNonLocal, autoPtr< mapDistribute > &faceMap, autoPtr< mapDistribute > &pointMap)
Set bounds of surface. Bounds currently set as list of.
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual void rename (const word &newName)
Rename.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool modified () const
Return true if the object's file (or files for objectRegistry)
virtual bool readIfModified ()
Read object if modified (as set by call to modified)
virtual bool writeObject (IOstream::streamFormat, IOstream::versionNumber, IOstream::compressionType, const bool valid) const
Write using given format, version and compression.
virtual bool write (const bool valid=true) const
Write using setting from DB.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Additional Inherited Members
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Static Public Member Functions inherited from searchableSurface
static autoPtr< searchableSurface > New (const word &surfaceType, const IOobject &io, const dictionary &dict)
Return a reference to the selected searchableSurface.
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
searchableSurface using multiple slightly shifted underlying surfaces to make sure pierces don't go through gaps:
shift test vector with two small vectors (of size gap_) perpendicular to the original. Test with + and - this vector. Only if both register a hit is it seen as one.
extend the test vector slightly (with SMALL) to account for numerical inaccuracies.
sphere.stl
{
    type triSurfaceMesh;
}
sphere
{
    type    searchableSurfaceWithGaps;
    surface sphere.stl;      // Underlying surface
    gap     1e-3;            // Perturb distance
}
Dictionary parameters
Property Description Required Default
type searchableSurfaceWithGaps selector
surface Name of the underlying surface yes
gap Gap tolerance in meters yes
Source files
searchableSurfaceWithGaps.H
searchableSurfaceWithGaps.C
Definition at line 97 of file searchableSurfaceWithGaps.H.
Constructor & Destructor Documentation
searchableSurfaceWithGaps (const IOobject & io, const dictionary & dict)
Construct from dictionary (used by searchableSurface)
Definition at line 173 of file searchableSurfaceWithGaps.C.
virtual ~searchableSurfaceWithGaps () virtual default
Destructor.
Member Function Documentation
TypeName ("searchableSurfaceWithGaps")
Runtime type information.
const searchableSurface& surface () const inline
The underlying searchableSurface.
Definition at line 183 of file searchableSurfaceWithGaps.H.
References searchableSurface::coordinates().
Referenced by searchableSurfaceWithGaps::getRegion(), searchableSurfaceWithGaps::hasVolumeType(), searchableSurfaceWithGaps::outsideVolumeType(), searchableSurfaceWithGaps::overlaps(), and searchableSurfaceWithGaps::regions().
virtual const wordList& regions () const inline virtual
Name of regions.
Implements searchableSurface.
Definition at line 191 of file searchableSurfaceWithGaps.H.
References searchableSurface::boundingSpheres(), and searchableSurfaceWithGaps::surface().
virtual bool hasVolumeType () const inline virtual
Whether supports volume type (below)
Reimplemented from searchableSurface.
Definition at line 199 of file searchableSurfaceWithGaps.H.
References searchableSurface::points(), and searchableSurfaceWithGaps::surface().
virtual volumeType outsideVolumeType () const inline virtual
What is type of points outside bounds.
Implements searchableSurface.
Definition at line 207 of file searchableSurfaceWithGaps.H.
References searchableSurface::overlaps(), and searchableSurfaceWithGaps::surface().
virtual label size () const inline virtual
Range of local indices that can be returned.
Implements searchableSurface.
Definition at line 215 of file searchableSurfaceWithGaps.H.
virtual tmp<pointField> coordinates () const inline virtual
Get representative set of element coordinates.
Usually the element centres (should be of length size()).
Implements searchableSurface.
Definition at line 225 of file searchableSurfaceWithGaps.H.
virtual void boundingSpheres (pointField & centres, scalarField & radiusSqr) const inline virtual
Get bounding spheres (centre and radius squared), one per element.
Any point on element is guaranteed to be inside.
Implements searchableSurface.
Definition at line 236 of file searchableSurfaceWithGaps.H.
virtual tmp<pointField> points () const inline virtual
Get the points that define the surface.
Implements searchableSurface.
Definition at line 247 of file searchableSurfaceWithGaps.H.
virtual bool overlaps (const boundBox & bb) const inline virtual
Does any part of the surface overlap the supplied bound box?
Note: use perturbed surface? Since uses boundbox of points and not actual intersection chosen to use unperturbed surface.
Implements searchableSurface.
Definition at line 258 of file searchableSurfaceWithGaps.H.
References searchableSurface::getRegion(), and searchableSurfaceWithGaps::surface().
virtual void findNearest (const pointField & sample, const scalarField & nearestDistSqr, List< pointIndexHit > & info) const inline virtual
Find nearest on original surface. Note:does not use perturbation.
and hence might be inconsistent with intersections.
Implements searchableSurface.
Definition at line 272 of file searchableSurfaceWithGaps.H.
void findLine (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Find first intersection on segment from start to end.
Note: searchableSurfacesQueries expects no intersection to be found if start==end. Is problem?
Implements searchableSurface.
Definition at line 197 of file searchableSurfaceWithGaps.C.
void findLineAny (const pointField & start, const pointField & end, List< pointIndexHit > &) const virtual
Return any intersection on segment from start to end.
Implements searchableSurface.
Definition at line 322 of file searchableSurfaceWithGaps.C.
void findLineAll (const pointField & start, const pointField & end, List< List< pointIndexHit >> & info) const virtual
Get all intersections in order from start to end.
Implements searchableSurface.
Definition at line 334 of file searchableSurfaceWithGaps.C.
References findLine().
virtual void getRegion (const List< pointIndexHit > & info, labelList & region) const inline virtual
From a set of points and indices get the region.
Implements searchableSurface.
Definition at line 314 of file searchableSurfaceWithGaps.H.
References searchableSurface::getField(), and searchableSurfaceWithGaps::surface().
virtual void getNormal (const List< pointIndexHit > & info, vectorField & normal) const inline virtual
From a set of points and indices get the normal.
Implements searchableSurface.
Definition at line 326 of file searchableSurfaceWithGaps.H.
virtual void getVolumeType (const pointField & samples, List< volumeType > & info) const inline virtual
Determine type (inside/outside/mixed) for points.
Unknown if cannot be determined (e.g. non-manifold surface)
Implements searchableSurface.
Definition at line 340 of file searchableSurfaceWithGaps.H.
virtual void setField (const labelList & values) inline virtual
Set bounds of surface. Bounds currently set as list of.
bounding boxes. The bounds are hints to the surface as for the range of queries it can expect. faceMap/pointMap can be set if the surface has done any redistribution. virtual void distribute (const List<treeBoundBox>& bbs, const bool keepNonLocal, autoPtr<mapDistribute>& faceMap, autoPtr<mapDistribute>& pointMap) { subGeom_[0].distribute(bbs, keepNonLocal, faceMap, pointMap); }
WIP. Store element-wise field.
Reimplemented from searchableSurface.
Definition at line 372 of file searchableSurfaceWithGaps.H.
virtual void getField (const List< pointIndexHit > & info, labelList & values) const inline virtual
WIP. From a set of hits (points and.
indices) get the specified field. Misses do not get set. Return empty field if not supported.
Reimplemented from searchableSurface.
Definition at line 384 of file searchableSurfaceWithGaps.H.
bool writeData (Ostream &) const inline virtual
Pure virtual writeData function.
Must be defined in derived types
Implements regIOobject.
Definition at line 394 of file searchableSurfaceWithGaps.H.
The documentation for this class was generated from the following files:
src/meshTools/searchableSurfaces/searchableSurfaceWithGaps/searchableSurfaceWithGaps.H
src/meshTools/searchableSurfaces/searchableSurfaceWithGaps/searchableSurfaceWithGaps.C