OpenFOAM: ReitzDiwakar< CloudType > Class Template Reference
ReitzDiwakar< CloudType > Class Template Reference
Breakup
secondary breakup model
Public Member Functions
TypeName ("ReitzDiwakar")
Runtime type information.
ReitzDiwakar (const dictionary &, CloudType &)
Construct from dictionary.
ReitzDiwakar (const ReitzDiwakar< CloudType > &bum)
Construct copy.
virtual autoPtr< BreakupModel
< CloudType > > clone () const
Construct and return a clone.
virtual ~ReitzDiwakar ()
Destructor.
virtual bool update (const scalar dt, const vector &g, scalar &d, scalar &tc, scalar &ms, scalar &nParticle, scalar &KHindex, scalar &y, scalar &yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector &U, const scalar rhoc, const scalar muc, const vector &Urel, const scalar Urmag, const scalar tMom, scalar &dChild, scalar &massChild)
Update the parcel properties.
Public Member Functions inherited from BreakupModel< CloudType >
TypeName ("breakupModel")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, BreakupModel, dictionary,(const dictionary &dict, CloudType &owner),(dict, owner))
Declare runtime constructor selection table.
BreakupModel (CloudType &owner)
Construct null from owner.
BreakupModel (const dictionary &dict, CloudType &owner, const word &type, bool solveOscillationEq=false)
Construct from dictionary.
BreakupModel (const BreakupModel< CloudType > &bum)
Construct copy.
virtual ~BreakupModel ()
Destructor.
const Switch & solveOscillationEq () const
const scalar & y0 () const
const scalar & yDot0 () const
const scalar & TABComega () const
const scalar & TABCmu () const
const scalar & TABtwoWeCrit () const
Public Member Functions inherited from CloudSubModelBase< CloudType >
CloudSubModelBase (CloudType &owner)
Construct null from owner cloud.
CloudSubModelBase (CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from owner cloud without name.
CloudSubModelBase (const word &modelName, CloudType &owner, const dictionary &dict, const word &baseName, const word &modelType)
Construct from owner cloud with name.
CloudSubModelBase (const CloudSubModelBase< CloudType > &smb)
Construct as copy.
virtual ~CloudSubModelBase ()
Destructor.
const CloudType & owner () const
Return const access to the owner cloud.
virtual bool writeTime () const
Flag to indicate when to write a property.
virtual fileName localPath () const
Output directory.
CloudType & owner ()
Return non-const access to the owner cloud for manipulation.
virtual void write (Ostream &os) const
Write.
Public Member Functions inherited from subModelBase
subModelBase (dictionary &properties)
Construct null.
subModelBase (dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType, const word &dictExt="Coeffs")
Construct from components without name.
subModelBase (const word &modelName, dictionary &properties, const dictionary &dict, const word &baseName, const word &modelType)
Construct from components with name.
subModelBase (const subModelBase &smb)
Construct as copy.
virtual ~subModelBase ()
Destructor.
const word & modelName () const
Return const access to the name of the sub-model.
const dictionary & dict () const
Return const access to the cloud dictionary.
const word & baseName () const
Return const access to the base name of the sub-model.
const word & modelType () const
Return const access to the sub-model type.
const dictionary & coeffDict () const
Return const access to the coefficients dictionary.
const dictionary & properties () const
Return const access to the properties dictionary.
virtual bool defaultCoeffs (const bool printMsg) const
Returns true if defaultCoeffs is true and outputs on printMsg.
virtual bool active () const
Return the model 'active' status - default active = true.
virtual void cacheFields (const bool store)
Cache dependant sub-model fields.
template<class Type >
Type getBaseProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the base model.
template<class Type >
void getBaseProperty (const word &entryName, Type &value) const
Retrieve generic property from the base model.
template<class Type >
void setBaseProperty (const word &entryName, const Type &value)
Add generic property to the base model.
bool getModelDict (const word &entryName, dictionary &dict) const
Retrieve dictionary, return true if set.
template<class Type >
void getModelProperty (const word &entryName, Type &value) const
Retrieve generic property from the sub-model.
template<class Type >
Type getModelProperty (const word &entryName, const Type &defaultValue=Type(Zero)) const
Retrieve generic property from the sub-model.
template<class Type >
void setModelProperty (const word &entryName, const Type &value)
Add generic property to the sub-model.
Additional Inherited Members
Public Types inherited from CloudSubModelBase< CloudType >
typedef CloudType cloudType
Type of cloud this model was instantiated for.
Static Public Member Functions inherited from BreakupModel< CloudType >
static autoPtr< BreakupModel
< CloudType > > New (const dictionary &dict, CloudType &owner)
Selector.
Protected Member Functions inherited from subModelBase
bool inLine () const
Flag to indicate whether data is/was read in-line.
Protected Attributes inherited from BreakupModel< CloudType >
Switch solveOscillationEq_
scalar y0_
scalar yDot0_
scalar TABComega_
scalar TABCmu_
scalar TABtwoWeCrit_
Protected Attributes inherited from CloudSubModelBase< CloudType >
CloudType & owner_
Reference to the cloud.
Protected Attributes inherited from subModelBase
const word modelName_
Name of the sub-model.
dictionary & properties_
Reference to properties dictionary e.g. for restart.
const dictionary dict_
Copy of dictionary used during construction.
const word baseName_
Name of the sub-model base class.
const word modelType_
Type of the sub-model.
const dictionary coeffDict_
Coefficients dictionary.
Detailed Description
template<class CloudType>
class Foam::ReitzDiwakar< CloudType >
secondary breakup model
Reitz, R.D.
"Modelling atomization processes in highpressure vaporizing sprays"
Atomization and Spray Technology 3 (1987), 309-337
Reitz, R.D. and Diwakar, R.
"Effect of drop breakup on fuel sprays"
SAE Tech. paper series, 860469 (1986)
Reitz, R.D. and Diwakar, R.
"Structure of high-pressure fuel sprays"
SAE Tech. paper series, 870598 (1987)
Definition at line 62 of file ReitzDiwakar.H.
Constructor & Destructor Documentation
ReitzDiwakar (const dictionary & dict, CloudType & owner)
Construct from dictionary.
Definition at line 27 of file ReitzDiwakar.C.
References subModelBase::coeffDict(), subModelBase::defaultCoeffs(), and dictionary::readEntry().
ReitzDiwakar (const ReitzDiwakar< CloudType > & bum)
Construct copy.
Definition at line 49 of file ReitzDiwakar.C.
~ReitzDiwakar () virtual
Destructor.
Definition at line 62 of file ReitzDiwakar.C.
Member Function Documentation
TypeName ("ReitzDiwakar< CloudType >")
Runtime type information.
virtual autoPtr<BreakupModel<CloudType> > clone () const inline virtual
Construct and return a clone.
Implements BreakupModel< CloudType >.
Definition at line 99 of file ReitzDiwakar.H.
bool update (const scalar dt, const vector & g, scalar & d, scalar & tc, scalar & ms, scalar & nParticle, scalar & KHindex, scalar & y, scalar & yDot, const scalar d0, const scalar rho, const scalar mu, const scalar sigma, const vector & U, const scalar rhoc, const scalar muc, const vector & Urel, const scalar Urmag, const scalar tMom, scalar & dChild, scalar & massChild) virtual
Update the parcel properties.
Implements BreakupModel< CloudType >.
Definition at line 70 of file ReitzDiwakar.C.
The documentation for this class was generated from the following files:
src/lagrangian/spray/submodels/BreakupModel/ReitzDiwakar/ReitzDiwakar.H
src/lagrangian/spray/submodels/BreakupModel/ReitzDiwakar/ReitzDiwakar.C