OpenFOAM: limitedSnGrad< Type > Class Template Reference
limitedSnGrad< Type > Class Template Reference
Surface normal gradient schemes
Run-time selected snGrad scheme with limited non-orthogonal correction.
Public Member Functions
TypeName ("limited")
Runtime type information.
limitedSnGrad (const fvMesh &mesh)
Construct from mesh.
limitedSnGrad (const fvMesh &mesh, Istream &schemeData)
Construct from mesh and data stream.
virtual ~limitedSnGrad ()
Destructor.
virtual tmp< surfaceScalarField > deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the interpolation weighting factors for the given field.
virtual bool corrected () const
Return true if this scheme uses an explicit correction.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the explicit correction to the limitedSnGrad.
Public Member Functions inherited from snGradScheme< Type >
virtual const word & type () const =0
Runtime type information.
declareRunTimeSelectionTable (tmp, snGradScheme, Mesh,(const fvMesh &mesh, Istream &schemeData),(mesh, schemeData))
snGradScheme (const fvMesh &mesh)
Construct from mesh.
virtual ~snGradScheme ()=default
Destructor.
const fvMesh & mesh () const
Return mesh reference.
virtual tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &) const
Return the snGrad of the given cell field.
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > snGrad (const tmp< GeometricField< Type, fvPatchField, volMesh >> &) const
Return the snGrad of the given tmp cell field.
Public Member Functions inherited from refCount
constexpr refCount () noexcept
Construct null initializing count to 0.
int count () const noexcept
Return the current reference count.
bool unique () const noexcept
Return true if the reference count is zero.
void operator++ () noexcept
Increment the reference count.
void operator++ (int) noexcept
Increment the reference count.
void operator-- () noexcept
Decrement the reference count.
void operator-- (int) noexcept
Decrement the reference count.
Additional Inherited Members
Static Public Member Functions inherited from snGradScheme< Type >
static tmp< snGradScheme< Type > > New (const fvMesh &mesh, Istream &schemeData)
Return new tmp interpolation scheme.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > snGrad (const GeometricField< Type, fvPatchField, volMesh > &, const tmp< surfaceScalarField > &, const word &snGradName="snGrad")
Return the snGrad of the given cell field with the given deltaCoeffs.
static tmp< GeometricField
< Type, fvsPatchField,
surfaceMesh > > sndGrad (const GeometricField< Type, fvPatchField, volMesh > &, const word &snGradName="sndGrad")
Return the sndGrad of the given cell field.
Detailed Description
template<class Type>
class Foam::fv::limitedSnGrad< Type >
Run-time selected snGrad scheme with limited non-orthogonal correction.
The limiter is controlled by a coefficient with a value between 0 and 1 which when 0 switches the correction off and the scheme behaves as uncorrectedSnGrad, when set to 1 the full correction of the selected scheme is used and when set to 0.5 the limiter is calculated such that the non-orthogonal contribution does not exceed the orthogonal part.
Format: limited <corrected scheme> <coefficient>;
or
limited <coefficient>; // Backward compatibility
Source files
limitedSnGrad.H
limitedSnGrad.C
Definition at line 68 of file limitedSnGrad.H.
Constructor & Destructor Documentation
limitedSnGrad (const fvMesh & mesh) inline
Construct from mesh.
Definition at line 131 of file limitedSnGrad.H.
limitedSnGrad (const fvMesh & mesh, Istream & schemeData) inline
Construct from mesh and data stream.
Definition at line 142 of file limitedSnGrad.H.
References Foam::exit(), Foam::FatalIOError, and FatalIOErrorInFunction.
~limitedSnGrad () virtual
Destructor.
Definition at line 41 of file limitedSnGrad.C.
Member Function Documentation
TypeName ("limited")
Runtime type information.
virtual tmp<surfaceScalarField> deltaCoeffs (const GeometricField< Type, fvPatchField, volMesh > &) const inline virtual
Return the interpolation weighting factors for the given field.
Implements snGradScheme< Type >.
Definition at line 169 of file limitedSnGrad.H.
virtual bool corrected () const inline virtual
Return true if this scheme uses an explicit correction.
Reimplemented from snGradScheme< Type >.
Definition at line 179 of file limitedSnGrad.H.
tmp< GeometricField< Type, fvsPatchField, surfaceMesh > > correction (const GeometricField< Type, fvPatchField, volMesh > & vf) const virtual
Return the explicit correction to the limitedSnGrad.
for the given field
Reimplemented from snGradScheme< Type >.
Definition at line 50 of file limitedSnGrad.C.
References Foam::average(), Foam::fvc::cellReduce(), Foam::correction(), Foam::expressions::patchExpr::debug, DimensionedField< Type, GeoMesh >::dimensions(), Foam::dimless, Foam::endl(), Foam::Info, InfoInFunction, Foam::limiter(), Foam::mag(), Foam::max(), DimensionedField< Type, GeoMesh >::mesh(), Foam::min(), Foam::name(), IOobject::NO_READ, IOobject::NO_WRITE, IOobject::objectPath(), oldTime, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and regIOobject::write().
The documentation for this class was generated from the following files:
src/finiteVolume/finiteVolume/snGradSchemes/limitedSnGrad/limitedSnGrad.H
src/finiteVolume/finiteVolume/snGradSchemes/limitedSnGrad/limitedSnGrad.C