OpenFOAM: liquidProperties Class Reference
liquidProperties Class Reference abstract
The thermophysical properties of a liquid.
Public Member Functions
TypeName ("liquid")
declareRunTimeSelectionTable (autoPtr, liquidProperties,,(),())
declareRunTimeSelectionTable (autoPtr, liquidProperties, dictionary,(const dictionary &dict),(dict))
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
Construct from components.
liquidProperties (const dictionary &dict)
Construct from dictionary.
virtual autoPtr< liquidProperties > clone () const =0
Construct and return clone.
virtual ~liquidProperties ()=default
Destructor.
scalar Y () const
No of moles of this species in mixture.
scalar Tc () const
Critical temperature [K].
scalar Pc () const
Critical pressure [Pa].
scalar Vc () const
Critical volume [m^3/kmol].
scalar Zc () const
Critical compressibility factor.
scalar Tt () const
Triple point temperature [K].
scalar Pt () const
Triple point pressure [Pa].
scalar Tb () const
Normal boiling temperature [K].
scalar dipm () const
Dipole moment [].
scalar omega () const
Pitzer's acentric factor [].
scalar delta () const
Solubility parameter [(J/m^3)^(1/2)].
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
scalar psi (scalar p, scalar T) const
Liquid compressibility rho/p [s^2/m^2].
scalar CpMCv (scalar p, scalar T) const
Return (Cp - Cv) [J/(kg K].
scalar Ha (const scalar p, const scalar T) const
Absolute Enthalpy [J/kg].
scalar Hs (const scalar p, const scalar T) const
Sensible enthalpy [J/kg].
scalar Hc () const
Chemical enthalpy [J/kg].
scalar S (const scalar p, const scalar T) const
virtual scalar pv (scalar p, scalar T) const =0
Vapour pressure [Pa].
virtual scalar hl (scalar p, scalar T) const =0
Heat of vapourisation [J/kg].
virtual scalar h (scalar p, scalar T) const =0
Liquid enthalpy [J/kg] - reference to 298.15 K.
virtual scalar Cpg (scalar p, scalar T) const =0
Vapour heat capacity [J/(kg K)].
virtual scalar mu (scalar p, scalar T) const =0
Liquid viscosity [Pa s].
virtual scalar mug (scalar p, scalar T) const =0
Vapour viscosity [Pa s].
virtual scalar kappa (scalar p, scalar T) const =0
Liquid thermal conductivity [W/(m K)].
scalar alphah (const scalar p, const scalar T) const
Liquid thermal diffusivity of enthalpy [kg/ms].
virtual scalar kappag (scalar p, scalar T) const =0
Vapour thermal conductivity [W/(m K)].
virtual scalar sigma (scalar p, scalar T) const =0
Surface tension [N/m].
virtual scalar D (scalar p, scalar T) const =0
Vapour diffusivity [m2/s].
virtual scalar D (scalar p, scalar T, scalar Wb) const =0
Vapour diffusivity [m2/s] with specified binary pair.
virtual scalar pvInvert (scalar p) const
Invert the vapour pressure relationship to retrieve the.
void readIfPresent (const dictionary &dict)
Read and set the properties present it the given dictionary.
template<class Func >
void readIfPresent (Func &f, const word &name, const dictionary &dict)
Read and set the function coefficients.
template<class Liquid >
void readIfPresent (Liquid &l, const dictionary &dict)
Read and set the function coefficients.
virtual void writeData (Ostream &os) const =0
Write the function coefficients.
template<class Liquid >
void writeData (const Liquid &l, Ostream &os) const
Write the data for each of the property functions.
Public Member Functions inherited from thermophysicalProperties
TypeName ("thermophysicalProperties")
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties,,(),())
declareRunTimeSelectionTable (autoPtr, thermophysicalProperties, dictionary,(const dictionary &dict),(dict))
thermophysicalProperties (scalar W)
Construct from molecular weight.
thermophysicalProperties (const dictionary &dict)
Construct from dictionary.
virtual ~thermophysicalProperties ()=default
Destructor.
scalar W () const
Molecular weight [kg/kmol].
scalar limit (const scalar T) const
Limit the temperature to be in the range Tlow_ to Thigh_.
virtual scalar rho (scalar p, scalar T) const =0
Liquid density [kg/m^3].
virtual scalar Cp (const scalar p, const scalar T) const =0
Heat capacity at constant pressure [J/(kg K)].
void readIfPresent (const dictionary &dict)
Read and set the properties present it the given dictionary.
Static Public Member Functions
static autoPtr< liquidProperties > New (const word &name)
Return a pointer to a new liquidProperties created from name.
static autoPtr< liquidProperties > New (const dictionary &dict)
Return a pointer to a new liquidProperties created from dictionary.
Static Public Member Functions inherited from thermophysicalProperties
static autoPtr
< thermophysicalProperties > New (const word &name)
Return a pointer to a new thermophysicalProperties created from name.
static autoPtr
< thermophysicalProperties > New (const dictionary &dict)
Return a pointer to a new thermophysicalProperties.
Static Public Attributes
static const bool incompressible = true
Is the equation of state is incompressible i.e. rho != f(p)
static const bool isochoric = false
Is the equation of state is isochoric i.e. rho = const.
Friends
Ostream & operator<< (Ostream &os, const liquidProperties &l)
Ostream Operator.
Detailed Description
The thermophysical properties of a liquid.
Source files
liquidProperties.H
liquidProperties.C
Definition at line 47 of file liquidProperties.H.
Constructor & Destructor Documentation
liquidProperties (scalar W, scalar Tc, scalar Pc, scalar Vc, scalar Zc, scalar Tt, scalar Pt, scalar Tb, scalar dipm, scalar omega, scalar delta)
Construct from components.
Definition at line 37 of file liquidProperties.C.
liquidProperties (const dictionary & dict)
Construct from dictionary.
Definition at line 65 of file liquidProperties.C.
virtual ~liquidProperties () virtual default
Destructor.
Member Function Documentation
TypeName ("liquid")
declareRunTimeSelectionTable (autoPtr , liquidProperties , () , ())
declareRunTimeSelectionTable (autoPtr , liquidProperties , dictionary , (const dictionary &dict) , (dict))
virtual autoPtr<liquidProperties> clone () const pure virtual
Construct and return clone.
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Foam::autoPtr< Foam::liquidProperties > New (const word & name) static
Return a pointer to a new liquidProperties created from name.
Definition at line 84 of file liquidProperties.C.
Referenced by liquidMixtureProperties::liquidMixtureProperties().
Foam::autoPtr< Foam::liquidProperties > New (const dictionary & dict) static
Return a pointer to a new liquidProperties created from dictionary.
Definition at line 110 of file liquidProperties.C.
Foam::scalar Y () const inline
No of moles of this species in mixture.
Note Mixing of liquidProperties is not currently supported so Y = 1
Definition at line 27 of file liquidPropertiesI.H.
References Foam::T().
Foam::scalar Tc () const inline
Critical temperature [K].
Definition at line 33 of file liquidPropertiesI.H.
Foam::scalar Pc () const inline
Critical pressure [Pa].
Definition at line 39 of file liquidPropertiesI.H.
Foam::scalar Vc () const inline
Critical volume [m^3/kmol].
Definition at line 45 of file liquidPropertiesI.H.
Foam::scalar Zc () const inline
Critical compressibility factor.
Definition at line 51 of file liquidPropertiesI.H.
Foam::scalar Tt () const inline
Triple point temperature [K].
Definition at line 57 of file liquidPropertiesI.H.
Foam::scalar Pt () const inline
Triple point pressure [Pa].
Definition at line 63 of file liquidPropertiesI.H.
Foam::scalar Tb () const inline
Normal boiling temperature [K].
Definition at line 69 of file liquidPropertiesI.H.
Foam::scalar dipm () const inline
Dipole moment [].
Definition at line 75 of file liquidPropertiesI.H.
Foam::scalar omega () const inline
Pitzer's acentric factor [].
Definition at line 81 of file liquidPropertiesI.H.
Foam::scalar delta () const inline
Solubility parameter [(J/m^3)^(1/2)].
Definition at line 87 of file liquidPropertiesI.H.
Foam::scalar limit (const scalar T) const inline
Limit the temperature to be in the range Tlow_ to Thigh_.
Definition at line 21 of file liquidPropertiesI.H.
Foam::scalar psi (scalar p, scalar T) const inline virtual
Liquid compressibility rho/p [s^2/m^2].
Note: currently it is assumed the liquid is incompressible
Implements thermophysicalProperties.
Definition at line 93 of file liquidPropertiesI.H.
Foam::scalar CpMCv (scalar p, scalar T) const inline virtual
Return (Cp - Cv) [J/(kg K].
Note: currently it is assumed the liquid is incompressible so CpMCv = 0
Implements thermophysicalProperties.
Definition at line 99 of file liquidPropertiesI.H.
Foam::scalar Ha (const scalar p, const scalar T) const inline virtual
Absolute Enthalpy [J/kg].
Implements thermophysicalProperties.
Definition at line 105 of file liquidPropertiesI.H.
Foam::scalar Hs (const scalar p, const scalar T) const inline virtual
Sensible enthalpy [J/kg].
Implements thermophysicalProperties.
Definition at line 111 of file liquidPropertiesI.H.
References h.
Foam::scalar Hc () const inline virtual
Chemical enthalpy [J/kg].
Implements thermophysicalProperties.
Definition at line 117 of file liquidPropertiesI.H.
References h.
Foam::scalar S (const scalar p, const scalar T) const virtual
Implements thermophysicalProperties.
Definition at line 171 of file liquidProperties.C.
virtual scalar pv (scalar p, scalar T) const pure virtual
Vapour pressure [Pa].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::W().
virtual scalar hl (scalar p, scalar T) const pure virtual
Heat of vapourisation [J/kg].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::pv().
virtual scalar h (scalar p, scalar T) const pure virtual
Liquid enthalpy [J/kg] - reference to 298.15 K.
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
virtual scalar Cpg (scalar p, scalar T) const pure virtual
Vapour heat capacity [J/(kg K)].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
virtual scalar mu (scalar p, scalar T) const pure virtual
Liquid viscosity [Pa s].
Implements thermophysicalProperties.
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::sigma().
virtual scalar mug (scalar p, scalar T) const pure virtual
Vapour viscosity [Pa s].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
virtual scalar kappa (scalar p, scalar T) const pure virtual
Liquid thermal conductivity [W/(m K)].
Implements thermophysicalProperties.
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::D().
Foam::scalar alphah (const scalar p, const scalar T) const inline virtual
Liquid thermal diffusivity of enthalpy [kg/ms].
Implements thermophysicalProperties.
Definition at line 123 of file liquidPropertiesI.H.
virtual scalar kappag (scalar p, scalar T) const pure virtual
Vapour thermal conductivity [W/(m K)].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
virtual scalar sigma (scalar p, scalar T) const pure virtual
Surface tension [N/m].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::Cp().
virtual scalar D (scalar p, scalar T) const pure virtual
Vapour diffusivity [m2/s].
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, IC8H18, MB, N2, H2O, iC3H8O, nC3H8O, and C8H10.
Referenced by liquidFilmThermo::hl().
virtual scalar D (scalar p, scalar T, scalar Wb) const pure virtual
Vapour diffusivity [m2/s] with specified binary pair.
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, iC3H8O, IC8H18, MB, N2, nC3H8O, H2O, and C8H10.
Foam::scalar pvInvert (scalar p) const virtual
Invert the vapour pressure relationship to retrieve the.
boiling temperature as a function of pressure
Definition at line 178 of file liquidProperties.C.
References NotImplemented.
Referenced by liquidFilmThermo::rho().
void readIfPresent (const dictionary & dict)
Read and set the properties present it the given dictionary.
Definition at line 221 of file liquidProperties.C.
void readIfPresent (Func & f, const word & name, const dictionary & dict) inline
Read and set the function coefficients.
if present it the given dictionary
Definition at line 131 of file liquidPropertiesI.H.
References Cp, and Foam::constant::electromagnetic::kappa.
void readIfPresent (Liquid & l, const dictionary & dict) inline
Read and set the function coefficients.
if present it the given dictionary
Definition at line 146 of file liquidPropertiesI.H.
void writeData (Ostream & os) const pure virtual
Write the function coefficients.
Implements thermophysicalProperties.
Implemented in IDEA, aC10H7CH3, Ar, bC10H7CH3, C10H22, C12H26, C13H28, C14H30, C16H34, C2H5OH, C2H6, C2H6O, C3H6O, C3H8, C4H10O, C6H14, C6H6, C7H16, C7H8, C8H18, C9H20, CH3OH, CH4N2O, iC3H8O, IC8H18, MB, N2, nC3H8O, H2O, and C8H10.
Definition at line 237 of file liquidProperties.C.
Referenced by Foam::operator<<().
void writeData (const Liquid & l, Ostream & os) const inline
Write the data for each of the property functions.
Definition at line 170 of file liquidPropertiesI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const liquidProperties & l) friend
Ostream Operator.
Member Data Documentation
const bool incompressible = true static
Is the equation of state is incompressible i.e. rho != f(p)
Definition at line 185 of file liquidProperties.H.
const bool isochoric = false static
Is the equation of state is isochoric i.e. rho = const.
Definition at line 190 of file liquidProperties.H.
The documentation for this class was generated from the following files:
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidProperties/liquidProperties.H
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidProperties/liquidProperties.C
src/thermophysicalModels/thermophysicalProperties/liquidProperties/liquidProperties/liquidPropertiesI.H