OpenFOAM: patchEdgeFaceRegion Class Reference
patchEdgeFaceRegion Class Reference
Transport of region for use in PatchEdgeFaceWave.
Public Member Functions
patchEdgeFaceRegion ()
Construct null.
patchEdgeFaceRegion (const label)
Construct from origin, distance.
label region () const
template<class TrackingData >
bool valid (TrackingData &td) const
Check whether origin has been changed at all or.
template<class TrackingData >
void transform (const polyMesh &mesh, const indirectPrimitivePatch &patch, const tensor &rotTensor, const scalar tol, TrackingData &td)
Apply rotation matrix.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label edgeI, const label facei, const patchEdgeFaceRegion &faceInfo, const scalar tol, TrackingData &td)
Influence of face on edge.
template<class TrackingData >
bool updateEdge (const polyMesh &mesh, const indirectPrimitivePatch &patch, const patchEdgeFaceRegion &edgeInfo, const bool sameOrientation, const scalar tol, TrackingData &td)
New information for edge (from e.g. coupled edge)
template<class TrackingData >
bool updateFace (const polyMesh &mesh, const indirectPrimitivePatch &patch, const label facei, const label edgeI, const patchEdgeFaceRegion &edgeInfo, const scalar tol, TrackingData &td)
Influence of edge on face.
template<class TrackingData >
bool equal (const patchEdgeFaceRegion &, TrackingData &) const
Same (like operator==)
bool operator== (const patchEdgeFaceRegion &) const
bool operator!= (const patchEdgeFaceRegion &) const
Friends
Ostream & operator<< (Ostream &, const patchEdgeFaceRegion &)
Istream & operator>> (Istream &, patchEdgeFaceRegion &)
Detailed Description
Transport of region for use in PatchEdgeFaceWave.
Set element to -2 to denote blocked.
Source files
patchEdgeFaceRegion.H
patchEdgeFaceRegionI.H
patchEdgeFaceRegion.C
Definition at line 63 of file patchEdgeFaceRegion.H.
Constructor & Destructor Documentation
patchEdgeFaceRegion () inline
Construct null.
Definition at line 71 of file patchEdgeFaceRegionI.H.
patchEdgeFaceRegion (const label region) inline
Construct from origin, distance.
Definition at line 79 of file patchEdgeFaceRegionI.H.
Member Function Documentation
Foam::label region () const inline
Definition at line 89 of file patchEdgeFaceRegionI.H.
bool valid (TrackingData & td) const inline
Check whether origin has been changed at all or.
still contains original (invalid) value.
Definition at line 96 of file patchEdgeFaceRegionI.H.
void transform (const polyMesh & mesh, const indirectPrimitivePatch & patch, const tensor & rotTensor, const scalar tol, TrackingData & td) inline
Apply rotation matrix.
Definition at line 104 of file patchEdgeFaceRegionI.H.
bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label edgeI, const label facei, const patchEdgeFaceRegion & faceInfo, const scalar tol, TrackingData & td) inline
Influence of face on edge.
Definition at line 116 of file patchEdgeFaceRegionI.H.
bool updateEdge (const polyMesh & mesh, const indirectPrimitivePatch & patch, const patchEdgeFaceRegion & edgeInfo, const bool sameOrientation, const scalar tol, TrackingData & td) inline
New information for edge (from e.g. coupled edge)
Definition at line 132 of file patchEdgeFaceRegionI.H.
References update().
bool updateFace (const polyMesh & mesh, const indirectPrimitivePatch & patch, const label facei, const label edgeI, const patchEdgeFaceRegion & edgeInfo, const scalar tol, TrackingData & td) inline
Influence of edge on face.
Definition at line 147 of file patchEdgeFaceRegionI.H.
References update().
bool equal (const patchEdgeFaceRegion & rhs, TrackingData & td) const inline
Same (like operator==)
Definition at line 163 of file patchEdgeFaceRegionI.H.
References update().
bool operator== (const patchEdgeFaceRegion & rhs) const inline
Definition at line 175 of file patchEdgeFaceRegionI.H.
bool operator!= (const patchEdgeFaceRegion & rhs) const inline
Definition at line 184 of file patchEdgeFaceRegionI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & , const patchEdgeFaceRegion &) friend
Istream& operator>> (Istream & , patchEdgeFaceRegion &) friend
The documentation for this class was generated from the following files:
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegion.H
src/meshTools/algorithms/PatchEdgeFaceWave/patchEdgeFaceRegionI.H