OpenFOAM: edgeMesh Class Reference
edgeMesh Class Reference
Mesh data needed to do the Finite Area discretisation.
Public Member Functions
edgeMesh (const faMesh &mesh)
label size () const
const edgeVectorField & C ()
TypeName ("edgeMesh")
Runtime type information.
edgeMesh ()
Construct null.
edgeMesh (const edgeMesh &em)
Copy construct.
edgeMesh (edgeMesh &&em)
Move construct.
edgeMesh (const pointField &points, const edgeList &edges)
Copy construct from components.
edgeMesh (pointField &&pointLst, edgeList &&edgeLst)
Move construct from components.
edgeMesh (const fileName &name)
Construct from file name (uses extension to determine type)
edgeMesh (const fileName &name, const word &ext)
Construct from file name (uses extension to determine type)
declareRunTimeSelectionTable (autoPtr, edgeMesh, fileExtension,(const fileName &name),(name))
virtual ~edgeMesh ()=default
Destructor.
declareMemberFunctionSelectionTable (void, edgeMesh, write, fileExtension,(const fileName &name, const edgeMesh &mesh),(name, mesh))
void transfer (edgeMesh &mesh)
Transfer the contents of the argument and annul the argument.
bool read (const fileName &name, const word &ext)
Read from file. Chooses reader based on explicit extension.
virtual bool read (const fileName &name)
Read from file. Chooses reader based on detected extension.
const pointField & points () const
Return points.
const edgeList & edges () const
Return edges.
const labelListList & pointEdges () const
Return edges.
label regions (labelList &edgeRegion) const
Find connected regions. Set region number per edge.
virtual void clear ()
Clear all storage.
virtual void scalePoints (const scalar scaleFactor)
Scale points. A non-positive factor is ignored.
virtual void mergePoints (const scalar mergeDist)
Geometric merge points (points within mergeDist) prior to.
virtual void mergeEdges ()
Merge duplicate edges and eliminate unused points.
virtual void writeStats (Ostream &) const
virtual void write (const fileName &name) const
Generic write routine. Chooses writer based on extension.
void operator= (const edgeMesh &rhs)
Copy assignment.
void operator= (edgeMesh &&rhs)
Move assignment.
Public Member Functions inherited from edgeMeshFormatsCore
edgeMeshFormatsCore ()=default
Construct null.
virtual ~edgeMeshFormatsCore ()=default
Destructor.
Public Member Functions inherited from GeoMesh< faMesh >
GeoMesh (const faMesh &mesh)
Construct from MESH.
bool hasDb () const
Return true if thisDb() is a valid DB - here = false.
const objectRegistry & thisDb () const
Return the object registry.
const faMesh & operator() () const
Return reference to polyMesh.
Static Public Member Functions
static label size (const Mesh &mesh)
static bool canRead (const fileName &name, bool verbose=false)
Can we read this file format?
static bool canReadType (const word &ext, bool verbose=false)
Can we read this file format?
static bool canWriteType (const word &ext, bool verbose=false)
Can we write this file format type?
static wordHashSet readTypes ()
static wordHashSet writeTypes ()
static autoPtr< edgeMesh > New (const fileName &name, const word &ext)
Select constructed from filename (explicit extension)
static autoPtr< edgeMesh > New (const fileName &name)
Select constructed from filename (implicit extension)
static void write (const fileName &name, const edgeMesh &mesh)
Write to file.
Static Public Member Functions inherited from edgeMeshFormatsCore
static bool checkSupport (const wordHashSet &available, const word &ext, const bool verbose, const word &functionName)
Protected Member Functions
pointField & storedPoints ()
Non-const access to global points.
edgeList & storedEdges ()
Non-const access to the edges.
Friends
Ostream & operator<< (Ostream &os, const edgeMesh &em)
Istream & operator>> (Istream &is, edgeMesh &em)
Additional Inherited Members
Public Types inherited from GeoMesh< faMesh >
typedef faMesh Mesh
typedef faMesh::BoundaryMesh BoundaryMesh
Static Public Attributes inherited from edgeMeshFormatsCore
static word nativeExt
The file extension corresponding to 'native' edge format.
Static Protected Member Functions inherited from edgeMeshFormatsCore
static string getLineNoComment (ISstream &is, const char comment='#')
Read non-comment line.
Protected Attributes inherited from GeoMesh< faMesh >
const faMesh & mesh_
Reference to Mesh.
Detailed Description
Mesh data needed to do the Finite Area discretisation.
Points connected by edges.
Author Zeljko Tukovic, FMENA Hrvoje Jasak, Wikki Ltd.
Can be read from fileName based on extension. Uses New factory method to select the reader and transfer the result.
Source files
edgeMesh.H
edgeMeshI.H
edgeMesh.C
edgeMeshIO.C
edgeMeshNew.C
Definition at line 46 of file edgeFaMesh.H.
Constructor & Destructor Documentation
edgeMesh (const faMesh & mesh) inline explicit
Definition at line 53 of file edgeFaMesh.H.
edgeMesh () inline
Construct null.
Definition at line 38 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
edgeMesh (const edgeMesh & em) inline
Copy construct.
Definition at line 47 of file edgeMeshI.H.
edgeMesh (edgeMesh && em) inline
Move construct.
Definition at line 56 of file edgeMeshI.H.
edgeMesh (const pointField & points, const edgeList & edges) inline
Copy construct from components.
Definition at line 65 of file edgeMeshI.H.
References transfer().
edgeMesh (pointField && pointLst, edgeList && edgeLst) inline
Move construct from components.
Definition at line 78 of file edgeMeshI.H.
edgeMesh (const fileName & name)
Construct from file name (uses extension to determine type)
Definition at line 42 of file edgeMeshIO.C.
References Foam::blockMeshTools::read().
edgeMesh (const fileName & name, const word & ext)
Construct from file name (uses extension to determine type)
Definition at line 29 of file edgeMeshIO.C.
virtual ~edgeMesh () virtual default
Destructor.
Member Function Documentation
label size () const inline
Definition at line 58 of file edgeFaMesh.H.
static label size (const Mesh & mesh) inline static
Definition at line 63 of file edgeFaMesh.H.
const edgeVectorField& C () inline
Definition at line 68 of file edgeFaMesh.H.
Foam::pointField & storedPoints () inline protected
Non-const access to global points.
Definition at line 24 of file edgeMeshI.H.
Foam::edgeList & storedEdges () inline protected
Non-const access to the edges.
Definition at line 30 of file edgeMeshI.H.
TypeName ("edgeMesh")
Runtime type information.
bool canRead (const fileName & name, bool verbose = false) static
Can we read this file format?
Definition at line 78 of file edgeMesh.C.
bool canReadType (const word & ext, bool verbose = false) static
Can we read this file format?
Definition at line 54 of file edgeMesh.C.
bool canWriteType (const word & ext, bool verbose = false) static
Can we write this file format type?
Definition at line 66 of file edgeMesh.C.
Foam::wordHashSet readTypes () static
Definition at line 40 of file edgeMesh.C.
References Foam::defineMemberFunctionSelectionTable(), Foam::defineRunTimeSelectionTable(), Foam::defineTypeNameAndDebug(), Foam::vtk::fileExtension, and Foam::vtk::write().
Foam::wordHashSet writeTypes () static
Definition at line 46 of file edgeMesh.C.
declareRunTimeSelectionTable (autoPtr , edgeMesh , fileExtension , (const fileName &name) , (name))
Foam::autoPtr< Foam::edgeMesh > New (const fileName & name, const word & ext) static
Select constructed from filename (explicit extension)
Definition at line 26 of file edgeMeshNew.C.
References FatalErrorInFunction, and Foam::nl.
Foam::autoPtr< Foam::edgeMesh > New (const fileName & name) static
Select constructed from filename (implicit extension)
Definition at line 47 of file edgeMeshNew.C.
declareMemberFunctionSelectionTable (void , edgeMesh , write , fileExtension , (const fileName &name, const edgeMesh &mesh) , (name, mesh))
void write (const fileName & name, const edgeMesh & mesh) static
Write to file.
Definition at line 81 of file edgeMeshIO.C.
void transfer (edgeMesh & mesh)
Transfer the contents of the argument and annul the argument.
Definition at line 116 of file edgeMesh.C.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
bool read (const fileName & name, const word & ext)
Read from file. Chooses reader based on explicit extension.
Definition at line 69 of file edgeMeshIO.C.
bool read (const fileName & name) virtual
Read from file. Chooses reader based on detected extension.
Reimplemented in extendedEdgeMesh, edgeMeshFormat, STARCDedgeFormat, VTKedgeFormat, NASedgeFormat, OBJedgeFormat, extendedFeatureEdgeMeshFormat, and extendedEdgeMeshFormat.
Definition at line 54 of file edgeMeshIO.C.
References Foam::blockMeshTools::read().
const Foam::pointField & points () const inline
Return points.
Definition at line 92 of file edgeMeshI.H.
Referenced by refinementFeatures::checkSizes(), extendedEdgeMesh::sortPointsAndEdges(), and Foam::edgeMeshTools::writeStats().
const Foam::edgeList & edges () const inline
Return edges.
Definition at line 98 of file edgeMeshI.H.
Referenced by Foam::edgeMeshTools::writeStats().
const Foam::labelListList & pointEdges () const inline
Return edges.
Definition at line 104 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
Foam::label regions (labelList & edgeRegion) const
Find connected regions. Set region number per edge.
Returns number of regions.
Definition at line 124 of file edgeMesh.C.
void clear () virtual
Clear all storage.
Reimplemented in extendedEdgeMesh.
Definition at line 108 of file edgeMesh.C.
void scalePoints (const scalar scaleFactor) virtual
Scale points. A non-positive factor is ignored.
Definition at line 189 of file edgeMesh.C.
void mergePoints (const scalar mergeDist) virtual
Geometric merge points (points within mergeDist) prior to.
automatically calling mergeEdges().
Definition at line 199 of file edgeMesh.C.
void mergeEdges () virtual
Merge duplicate edges and eliminate unused points.
Definition at line 233 of file edgeMesh.C.
void writeStats (Ostream & os) const virtual
Reimplemented in extendedEdgeMesh.
Definition at line 106 of file edgeMeshIO.C.
virtual void write (const fileName & name) const inline virtual
Generic write routine. Chooses writer based on extension.
Reimplemented in edgeMeshFormat, STARCDedgeFormat, VTKedgeFormat, and OBJedgeFormat.
Definition at line 316 of file edgeMesh.H.
void operator= (const edgeMesh & rhs) inline
Copy assignment.
Definition at line 116 of file edgeMeshI.H.
Referenced by extendedEdgeMesh::sortPointsAndEdges().
void operator= (edgeMesh && rhs) inline
Move assignment.
Definition at line 124 of file edgeMeshI.H.
Friends And Related Function Documentation
Ostream& operator<< (Ostream & os, const edgeMesh & em) friend
Istream& operator>> (Istream & is, edgeMesh & em) friend
The documentation for this class was generated from the following files:
src/finiteArea/edgeMesh/edgeFaMesh.H
src/meshTools/edgeMesh/edgeMesh.H
src/meshTools/edgeMesh/edgeMesh.C
src/meshTools/edgeMesh/edgeMeshI.H
src/meshTools/edgeMesh/edgeMeshIO.C
src/meshTools/edgeMesh/edgeMeshNew.C