OpenFOAM: parseDriver Class Reference
parseDriver Class Reference
Driver for volume, surface, point field expressions.
Public Member Functions
ClassName ("volumeExpr::driver")
parseDriver (const fvMesh &mesh, bool cacheReadFields=false)
Construct for specified mesh.
parseDriver (const fvMesh &mesh, const dictionary &dict)
Construct for specified mesh with given dictionary.
parseDriver (const fvMesh &mesh, const parseDriver &driver)
Construct for specified mesh with copy of driver context.
parseDriver (const word &meshName, const fvMesh &mesh)
Construct with meshName for the given mesh.
parseDriver (const dictionary &dict, const fvMesh &mesh)
Construct with patchName and region specified in dictionary.
virtual autoPtr
< expressions::fvExprDriver > clone () const
Clone.
virtual ~parseDriver ()=default
Destructor.
virtual const fvMesh & mesh () const
The mesh we are attached to.
virtual label size () const
The underlying field size for the expression.
virtual label pointSize () const
The underlying point field size for the expression.
label size (const FieldAssociation geoType) const
Field size associated with different geometric field types.
virtual bool readDict (const dictionary &dict)
Read variables, tables etc.
virtual unsigned parse (const std::string &expr, size_t pos=0, size_t len=std::string::npos)
Execute the parser.
const word & resultType () const
The result type-name.
FieldAssociation fieldAssociation () const
The geometric field association.
bool isLogical () const
A logical (bool-like) field. Actually stored as a scalar.
bool isVolumeData () const
A volume field.
bool isSurfaceData () const
A surface field.
bool isPointData () const
A point field.
template<class GeoField >
const GeoField * isResultType () const
Test if stored result pointer is the specified type.
template<class GeoField >
const GeoField * isResultType (bool logical, bool dieOnNull=false) const
Test if stored result pointer is the specified type and matches the specified logical type.
template<class Type >
void setResult (GeometricField< Type, fvPatchField, volMesh > *ptr, bool logical=false)
Set result (vol field)
template<class Type >
void setResult (GeometricField< Type, fvsPatchField, surfaceMesh > *ptr, bool logical=false)
Set result (surface field)
template<class Type >
void setResult (GeometricField< Type, pointPatchField, pointMesh > *ptr, bool logical=false)
Set result (point field)
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > newVolField (const Type &val=pTraits< Type >::zero) const
Return a new volume field with the mesh size.
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > newSurfaceField (const Type &val=pTraits< Type >::zero) const
Return a new surface field with the mesh nInternalFaces size.
template<class Type >
tmp< GeometricField< Type,
pointPatchField, pointMesh > > newPointField (const Type &val=pTraits< Type >::zero) const
Return a new point field with the mesh nPoints size.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > getVolField (const word &fldName, bool getOldTime=false)
Retrieve field (vol field)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > getSurfaceField (const word &fldName, bool getOldTime=false)
Retrieve field (surface field)
template<class Type >
tmp< GeometricField< Type,
pointPatchField, pointMesh > > getPointField (const word &fldName, bool getOldTime=false)
Retrieve field (surface field)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > cellToFace (const GeometricField< Type, fvPatchField, volMesh > &field) const
Interpolate cell to face values.
template<class Type >
tmp< GeometricField< Type,
pointPatchField, pointMesh > > cellToPoint (const GeometricField< Type, fvPatchField, volMesh > &field) const
Interpolate cell to point values.
template<class Type >
tmp< GeometricField< Type,
fvPatchField, volMesh > > pointToCell (const GeometricField< Type, pointPatchField, pointMesh > &field) const
Interpolate point to cell values.
template<class Type >
Type volAverage (GeometricField< Type, fvPatchField, volMesh > &fld) const
The volume-weighted average of a field.
template<class Type >
Type volSum (GeometricField< Type, fvPatchField, volMesh > &fld) const
The volume-weighted sum of a field.
template<class Type >
Type areaAverage (GeometricField< Type, fvsPatchField, surfaceMesh > &fld) const
The area-weighted average of a field.
template<class Type >
Type areaSum (GeometricField< Type, fvsPatchField, surfaceMesh > &fld) const
The area-weighted sum of a field.
tmp< volScalarField > field_cellVolume () const
The cell volumes - (swak = vol)
tmp< volVectorField > field_cellCentre () const
The cell centres - (swak = pos)
tmp< surfaceScalarField > field_faceArea () const
The face area magnitudes [magSf] - (swak = area)
tmp< surfaceVectorField > field_faceCentre () const
The face centres - (swak = fpos)
tmp< surfaceVectorField > field_areaNormal () const
The face areas with their vector direction [Sf] - (swak = face)
tmp< pointVectorField > field_pointField () const
The mesh point locations - (swak = pts)
tmp< volScalarField > field_cellSet (const word &name) const
Cell selection (set)
tmp< volScalarField > field_cellZone (const word &name) const
Cell selection (zone)
tmp< surfaceScalarField > field_faceSet (const word &name) const
Face selection (set)
tmp< surfaceScalarField > field_faceZone (const word &name) const
Face selection (zone)
tmp< pointScalarField > field_pointSet (const word &name) const
Point selection (set)
tmp< pointScalarField > field_pointZone (const word &name) const
Point selection (zone)
tmp< volScalarField > field_rand (label seed=0, bool gaussian=false) const
A uniform random field.
tmp< volScalarField > field_randGaussian (label seed=0) const
A Gaussian random field.
template<class GeomField >
const GeomField * isResultType () const
template<class GeomField >
const GeomField * isResultType (bool logical, bool dieOnNull) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > newVolField (const Type &val) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > newSurfaceField (const Type &val) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::pointPatchField,
Foam::pointMesh > > newPointField (const Type &val) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvsPatchField,
Foam::surfaceMesh > > cellToFace (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::pointPatchField,
Foam::pointMesh > > cellToPoint (const GeometricField< Type, fvPatchField, volMesh > &field) const
template<class Type >
Foam::tmp
< Foam::GeometricField< Type,
Foam::fvPatchField,
Foam::volMesh > > pointToCell (const GeometricField< Type, pointPatchField, pointMesh > &field) const
Public Member Functions inherited from genericRagelLemonDriver
genericRagelLemonDriver ()
Construct null.
genericRagelLemonDriver (const genericRagelLemonDriver &rhs)=default
Copy construct.
genericRagelLemonDriver (genericRagelLemonDriver &&rhs)=default
Move construct.
virtual ~genericRagelLemonDriver ()=default
Destructor.
void clear ()
Reset references.
const std::string & content () const
Get reference to the input buffer content.
void content (const std::string &s, size_t pos=0, size_t len=std::string::npos)
Set reference to the input buffer content, which acts like a std::string_view.
std::string::const_iterator cbegin () const
Iterator to begin of content (sub)string.
std::string::const_iterator cend () const
Iterator to end of content (sub)string.
size_t parsePosition () const
The relative parse position with the content (sub)string.
size_t & parsePosition ()
The relative parse position with the content (sub)string.
Ostream & printBuffer (Ostream &os) const
Output the input buffer string content.
void reportFatal (const std::string &msg) const
Report FatalError.
void reportFatal (const std::string &msg, size_t pos) const
Report FatalError at parser position.
Public Member Functions inherited from fvExprDriver
TypeName ("fvExprDriver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, fvExprDriver, dictionary,(const dictionary &dict, const fvMesh &mesh),(dict, mesh))
declareRunTimeSelectionTable (autoPtr, fvExprDriver, idName,(const word &ident, const fvMesh &mesh),(ident, mesh))
fvExprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
fvExprDriver (const fvExprDriver &)
Copy construct.
fvExprDriver (const dictionary &dict)
Construct from a dictionary.
virtual ~fvExprDriver ()
Destructor.
const Time & runTime () const
The Time associated with the mesh.
virtual word timeName () const
The current time name.
virtual scalar timeValue () const
The current time value.
bool cacheSets () const
Status of cache-sets (static variable)
virtual void clearVariables ()
Clear temporary variables and resets from expression strings.
virtual bool hasVariable (const word &name) const
True if named variable exists.
virtual const exprResult & variable (const word &name) const
Return const-access to the named variable.
template<class Type >
bool isVariableOrField (const word &name, bool isPointVal=false, label expectSize=-1) const
Test for existence of a local/global variable or a field.
template<class Type >
tmp< Field< Type > > getVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
word getFieldClassName (const word &name) const
Lookup the field class name (memory or read from disk)
topoSetSource::sourceType topoSetType (const word &name) const
Return cell/face/point set type or unknown.
topoSetSource::sourceType topoZoneType (const word &name) const
Return cell/face/point zone type or unknown.
topoSetSource::sourceType topoSourceType (const word &name) const
Return cell/face/point zone/set type or unknown.
labelList getTopoSetLabels (const word &name, enum topoSetSource::sourceType setType) const
Read and return labels associated with the topo set.
bool isCellZone (const word &name) const
Test if name is a known cellZone.
bool isFaceZone (const word &name) const
Test if name is a known faceZone.
bool isPointZone (const word &name) const
Test if name is a known pointZone.
bool isCellSet (const word &name) const
Test if name is a known cellSet.
bool isFaceSet (const word &name) const
Test if name is a known faceSet.
bool isPointSet (const word &name) const
Test if name is a known pointSet.
virtual void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
virtual void evaluateVariableRemote (string remote, const word &varName, const expressions::exprString &expr)
Evaluate an expression on a remote and save as the specified named variable.
template<class Type >
bool isVariable (const word &name, bool isPointVal=false, label expectSize=-1) const
Test existence of a local/global variable.
template<class Type >
bool foundField (const word &name) const
Test if specified field can be found in memory or disk.
word getTypeOfField (const word &fieldName) const
Read the IOobject for fieldName and return its headerClassName.
Ostream & writeCommon (Ostream &os, bool debug=false) const
Write "variables", "storedVariables", "delayedVariables", "globalScopes" if they are present.
void createWriterAndRead (const word &name)
Create a writer for this object.
void tryWrite () const
Write data if apropriate Should enable exact restarts.
template<class GeomField >
Foam::tmp< GeomField > getOrReadField (const word &name, bool mandatory, bool getOldTime)
template<class GeomField >
Foam::tmp< GeomField > getOrReadPointField (const word &name, bool mandatory, bool getOldTime)
template<class GeomField , class Mesh >
Foam::tmp< GeomField > readAndRegister (const word &name, const Mesh &meshRef)
template<class Type >
Foam::tmp< Foam::Field< Type > > getVariable (const word &name, label expectedSize, const bool mandatory) const
template<class GeomField , class Mesh >
Foam::tmp< GeomField > getOrReadFieldImpl (const word &name, const Mesh &meshRef, bool mandatory, bool getOldTime)
template<class T >
Foam::autoPtr< T > getTopoSet (const fvMesh &mesh, const word &name, SetOrigin &origin) const
Public Member Functions inherited from exprDriver
TypeName ("exprDriver")
Runtime type information.
exprDriver (bool cacheReadFields=false, bool searchInMemory=true, bool searchFiles=false, const dictionary &dict=dictionary::null)
Null constructor, and null construct with search preferences.
exprDriver (const exprDriver &)
Copy construct.
exprDriver (const dictionary &dict)
Construct from a dictionary.
virtual ~exprDriver ()=default
Destructor.
const dictionary & dict () const
The dictionary with all input data/specification.
virtual const exprResult & result () const
Const access to expression result.
virtual exprResult & result ()
Non-const access to expression result.
void clearResult ()
Clear the result.
template<class Type >
tmp< Field< Type > > getResult (bool isPointVal=false)
Return the expression result as a tmp field.
virtual word getResultType () const
The result type as word - same as result().valueType()
int stashedTokenId () const
Get "look-behind" parsing context (internal bookkeeping)
int resetStashedTokenId (int tokenId=0) const
Reset "look-behind" parsing context (mutable operation)
void setDebugging (bool scannerDebug, bool parserDebug)
Set the scanner/parser debug.
void setDebugging (const exprDriver &rhs)
Set the scanner/parser debug to match the input.
void setSearchBehaviour (bool cacheReadFields, bool searchInMemory, bool searchFiles)
Set search behaviour.
void setSearchBehaviour (const exprDriver &rhs)
Set search behaviour to be identical to rhs.
bool debugScanner () const
Read access to scanner debug.
bool debugParser () const
Read access to parser debug.
bool cacheReadFields () const
bool searchInMemory () const
bool searchFiles () const
bool prevIterIsOldTime () const
void addVariables (const expressions::exprString &expr, bool clear=true)
Add/set string expressions for variables.
void addVariables (const UList< expressions::exprString > &list, bool clear=true)
Add/set string expressions for variables.
template<class T >
void addUniformVariable (const word &name, const T &val)
Add a uniform variable from an outside caller.
template<class T >
bool isLocalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a local variable.
template<class Type >
tmp< Field< Type > > getLocalVariable (const word &name, label expectSize, const bool mandatory=true) const
Retrieve local/global variable as a tmp field.
template<class Type >
tmp< Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return the field.
template<class Type >
Type evaluateUniform (const expressions::exprString &expr, bool isPointVal=false)
Evaluate the expression and return a single value.
void evaluateVariable (const word &varName, const expressions::exprString &expr)
Evaluate the expression and save as the specified named variable.
template<class Type >
tmp< Field< Type > > newField (const Type &val=pTraits< Type >::zero) const
Return a new field with the size()
template<class Type >
tmp< Field< Type > > newPointField (const Type &val=pTraits< Type >::zero) const
Return a new field with the pointSize()
expressions::exprString readExpression (const word &name)
Read an expression string (with the current dictionary) and do substitutions.
label setVariableStrings (const dictionary &dict, bool mandatory=false)
Read "variables" and assigns to the list of expression strings.
Ostream & writeVariableStrings (Ostream &os, const word &keyword="") const
Write "variables".
template<class Type >
void addUniformVariable (const word &name, const Type &val)
template<class Type >
Foam::tmp< Foam::Field< Type > > evaluate (const expressions::exprString &expr, bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > getResult (bool isPointVal)
template<class Type >
Foam::tmp< Foam::Field< Type > > newField (const Type &val) const
template<class Type >
Foam::tmp< Foam::Field< Type > > newPointField (const Type &val) const
Protected Member Functions
template<class Type >
void setInternalFieldResult (const Field< Type > &fld)
Deep-copy the internalField as a result.
tmp< volScalarField > field_cellSelection (const word &name, enum topoSetSource::sourceType setType) const
Cell selections (as logical)
tmp< surfaceScalarField > field_faceSelection (const word &name, enum topoSetSource::sourceType setType) const
Face selections (as logical)
tmp< pointScalarField > field_pointSelection (const word &name, enum topoSetSource::sourceType setType) const
Point selections (as logical)
parseDriver (const parseDriver &)=delete
void operator= (const parseDriver &)=delete
Protected Member Functions inherited from fvExprDriver
void setGlobalScopes (const wordUList &scopes)
Define scopes for global variables.
virtual exprResult & variable (const word &name)
Non-const access to the named variable (sub-classes only)
template<class T >
bool isGlobalVariable (const word &name, bool isPointVal, label expectedSize=-1) const
Test existence of a global variable.
const exprResult & lookupGlobal (const word &name) const
Return the global variable if available or a null result.
template<class Type >
bool isField (const word &name, bool isPointVal=false, label expectSize=-1) const
Test for the existence of a mesh field.
template<class GeomField >
tmp< GeomField > getOrReadField (const word &name, bool mandatory=true, bool getOldTime=false)
Retrieve field from memory or disk.
template<class GeomField >
tmp< GeomField > getOrReadPointField (const word &name, bool mandatory=true, bool getOldTime=false)
Retrieve point field from memory or disk.
template<class GeomField , class MeshRef >
tmp< GeomField > getOrReadFieldImpl (const word &name, const MeshRef &meshRef, bool mandatory=true, bool getOldTime=false)
Retrieve field from memory or disk (implementation)
template<class GeomField , class MeshRef >
tmp< GeomField > readAndRegister (const word &name, const MeshRef &meshRef)
Helper function for getOrReadField.
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Create a random field.
template<class T >
autoPtr< T > getTopoSet (const fvMesh &mesh, const word &setName, SetOrigin &origin) const
Get topoSet.
template<class T >
bool updateSet (autoPtr< T > &setPtr, const word &setName, SetOrigin origin) const
Update topoSet.
virtual void updateSpecialVariables (bool force=false)
Examine current variable values and update stored variables.
virtual bool hasDataToWrite () const
Do we need a data file to be written.
virtual void prepareData (dictionary &dict) const
Prepare/update special variables and add to dictionary, normally via the reader/writer.
virtual void getData (const dictionary &dict)
Read data from dictionary, normally via the reader/writer.
Protected Member Functions inherited from exprDriver
void fill_random (scalarField &field, label seed=0, const bool gaussian=false) const
Fill a random field.
virtual bool update ()
Update things.
virtual exprResult getRemoteResult (const exprDriver &other) const
Get the result from another driver.
void operator= (const exprDriver &)=delete
No copy assignment.
Protected Attributes
const fvMesh & mesh_
The referenced mesh.
autoPtr< regIOobject > resultField_
The results (volume, surface, point)
word resultType_
The result type-name.
bool isLogical_
A logical (bool-like) field (but actually a scalar)
enum FieldAssociation fieldGeoType_
A volume/surface/point field.
dimensionSet resultDimension_
The result dimensions.
Protected Attributes inherited from genericRagelLemonDriver
std::reference_wrapper< const
std::string > content_
Reference to the input string.
size_t start_
Start position within input string.
size_t length_
Length of input (sub)string.
size_t position_
The last known parser position.
Protected Attributes inherited from exprDriver
const dictionary & dict_
The dictionary with all input data/specification.
exprResult result_
The result.
List< expressions::exprString > variableStrings_
Variable definitions, as read from a dictionary.
HashTable< exprResult > variables_
The variables table.
int stashedTokenId_
Internal bookkeeping as "look-behind" parsing context.
bool debugScanner_
Request debugging for scanner.
bool debugParser_
Request debugging for parser.
bool allowShadowing_
Allow variable names to mask field names.
bool prevIterIsOldTime_
Use value of previous iteration when oldTime is requested.
bool cacheReadFields_
Keep fields read from disc in memory.
bool searchInMemory_
Search in registry before looking on disk.
bool searchFiles_
Search on disk (eg, for a standalone application)
Additional Inherited Members
Public Types inherited from genericRagelLemonDriver
typedef size_t location_type
Type for linear addressing within parse content.
Static Public Member Functions inherited from fvExprDriver
static const fvMesh & defaultMesh ()
Get the default mesh, if one is defined.
static const fvMesh * resetDefaultMesh (const fvMesh &mesh, const bool force=false)
Set the default mesh (if not already set)
static autoPtr< fvExprDriver > New (const dictionary &dict, const fvMesh &mesh)
Return a reference to the selected value driver.
static autoPtr< fvExprDriver > New (const dictionary &dict)
Return a reference to the selected value driver.
static autoPtr< fvExprDriver > New (const word &type, const word &id, const fvMesh &mesh)
Return a reference to the selected value driver.
Static Public Member Functions inherited from exprDriver
static expressions::exprString readExpression (const word &name, const dictionary &dict)
Read an expression string and do substitutions.
static List
< expressions::exprString > readVariableStrings (const dictionary &dict, const word &name="variables", bool mandatory=false)
Read the list of variable strings.
Protected Types inherited from fvExprDriver
enum SetOrigin {
INVALID = 0, NEW, FILE, MEMORY,
CACHE
}
The origin of the topoSet.
Static Protected Member Functions inherited from fvExprDriver
static const fvMesh & regionMesh (const dictionary &dict, const fvMesh &mesh, bool readIfNecessary)
Determine mesh or region mesh as specified in the dictionary with the keyword "region".
template<class T >
static word defaultBoundaryType (const T &)
Default boundary type is calculated.
template<class Type >
static word defaultBoundaryType (const GeometricField< Type, fvPatchField, volMesh > &)
Default boundary type for volume fields is zeroGradient.
template<class T >
static void correctField (T &)
Apply correctBoundaryConditions (volume fields only)
template<class Type >
static void correctField (GeometricField< Type, fvPatchField, volMesh > &fld)
Static Protected Member Functions inherited from exprDriver
template<typename TableType >
static bool readTable (const word &name, const dictionary &dict, HashTable< TableType > &tbl, bool clear=true)
Read an interpolation table.
template<class TableType >
static void writeTable (Ostream &os, const word &name, const HashTable< TableType > &tbl)
Write an interpolation table.
template<class Type >
static Type weightedAverage (const scalarField &weights, const Field< Type > &fld)
The (global) weighted average of a field, with stabilisation.
template<class Type >
static Type weightedSum (const scalarField &weights, const Field< Type > &fld)
The (global) weighted sum (integral) of a field.
static point getPositionOfMinimum (const scalarField &vals, const pointField &locs)
Return the location of the min value.
static point getPositionOfMaximum (const scalarField &vals, const pointField &locs)
Return the location of the max value.
Detailed Description
Driver for volume, surface, point field expressions.
Additional Properties
Property Description Required Default
dimensions Dimensions for the expression result no
In addition to the standard mathematical functions, operations and logical and relational operations, the volume expressions support the following driver-specific functions:
Functions
Function Description Number of arguments
vol The cell volumes 0
pos The cell centres 0
pts The cell points 0
area The face area magnitudes 0
fpos The face centres 0
weightAverage Volume or area weighted average 1
weightSum Volume or area weighted sum 1
face The face areaNormal vectors 0
face A surface-field face value 1
point A point-field point value 1
cellToFace Interpolate cell values onto faces 1
cellToPoint Interpolate cell values onto points 1
pointToCell Interpolate point values onto cells 1
reconstruct Reconstruct cell vector from surface scalar 1
rand Random field 0/1
Selections
Function Description Number of arguments
cset Logical vol field corresponding to cellSet 1
fset Logical surf field corresponding to faceSet 1
pset Logical point field corresponding to pointSet 1
czone Logical vol field corresponding to cellZone 1
fzone Logical surf field corresponding to faceZone 1
pzone Logical point field corresponding to pointZone 1
Note
Use namespace debug switch volumeExpr for scanner (2), parser (4) or dictionary controls as per Foam::expressions::exprDriver.
Source files
volumeExprDriver.H
volumeExprDriver.C
Definition at line 225 of file volumeExprDriver.H.
Constructor & Destructor Documentation
parseDriver (const parseDriver &) protected delete
parseDriver (const fvMesh & mesh, bool cacheReadFields = false) explicit
Construct for specified mesh.
Definition at line 80 of file volumeExprDriver.C.
parseDriver (const fvMesh & mesh, const dictionary & dict)
Construct for specified mesh with given dictionary.
Definition at line 96 of file volumeExprDriver.C.
parseDriver (const fvMesh & mesh, const parseDriver & driver)
Construct for specified mesh with copy of driver context.
Definition at line 112 of file volumeExprDriver.C.
parseDriver (const word & meshName, const fvMesh & mesh)
Construct with meshName for the given mesh.
Definition at line 128 of file volumeExprDriver.C.
parseDriver (const dictionary & dict, const fvMesh & mesh)
Construct with patchName and region specified in dictionary.
Definition at line 140 of file volumeExprDriver.C.
virtual ~parseDriver () virtual default
Destructor.
Member Function Documentation
void setInternalFieldResult (const Field< Type > & fld) protected
Deep-copy the internalField as a result.
Uses the isLogical() and isPointData() values to handle additional bookkeeping. For isLogical(), renames the resultType_ from '*Scalar*' to '*Logical*' (eg, volLogicalField)
Definition at line 31 of file volumeExprDriverTemplates.C.
References Foam::FieldOps::assign(), Foam::HashSetOps::bools(), parseDriver::isLogical_, parseDriver::isPointData(), string::replace(), exprDriver::result(), parseDriver::resultType_, exprResult::setResult(), and UList< Type >::size().
Foam::tmp< Foam::volScalarField > field_cellSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Cell selections (as logical)
Definition at line 29 of file volumeExprDriverFields.C.
References Foam::exit(), Foam::FatalError, FatalErrorInFunction, fld, fvExprDriver::getTopoSetLabels(), parseDriver::mesh(), GeometricField< scalar, fvPatchField, volMesh >::New(), Foam::nl, and Foam::Zero.
Foam::tmp< Foam::surfaceScalarField > field_faceSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Face selections (as logical)
Definition at line 69 of file volumeExprDriverFields.C.
Foam::tmp< Foam::pointScalarField > field_pointSelection (const word & name, enum topoSetSource::sourceType setType) const protected
Point selections (as logical)
Definition at line 144 of file volumeExprDriverFields.C.
void operator= (const parseDriver &) protected delete
ClassName ("volumeExpr::driver")
virtual autoPtr<expressions::fvExprDriver> clone () const inline virtual
Clone.
Implements fvExprDriver.
Definition at line 354 of file volumeExprDriver.H.
virtual const fvMesh& mesh () const inline virtual
The mesh we are attached to.
Implements fvExprDriver.
Definition at line 374 of file volumeExprDriver.H.
Referenced by parseDriver::field_cellSelection().
virtual label size () const inline virtual
The underlying field size for the expression.
Implements fvExprDriver.
Definition at line 382 of file volumeExprDriver.H.
virtual label pointSize () const inline virtual
The underlying point field size for the expression.
Implements fvExprDriver.
Definition at line 390 of file volumeExprDriver.H.
Foam::label size (const FieldAssociation geoType) const inline
Field size associated with different geometric field types.
Definition at line 24 of file volumeExprDriverI.H.
References parseDriver::mesh_, primitiveMesh::nCells(), primitiveMesh::nInternalFaces(), primitiveMesh::nPoints(), Foam::expressions::patchExpr::POINT_DATA, Foam::expressions::patchExpr::SURFACE_DATA, and Foam::expressions::volumeExpr::VOLUME_DATA.
bool readDict (const dictionary & dict) virtual
Read variables, tables etc.
Adds support for "dimensions"
Reimplemented from fvExprDriver.
Definition at line 158 of file volumeExprDriver.C.
unsigned parse (const std::string & expr, size_t pos = 0, size_t len = std::string::npos) virtual
Execute the parser.
The return value currently has no meaning.
Implements exprDriver.
Definition at line 172 of file volumeExprDriver.C.
const word& resultType () const inline
The result type-name.
Normally volScalarField, surfaceVectorField etc, but Scalar is modified for logical as volScalarField etc
Definition at line 439 of file volumeExprDriver.H.
References DimensionedField< Type, GeoMesh >::mesh(), GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and exprDriver::weightedSum().
FieldAssociation fieldAssociation () const inline
The geometric field association.
Definition at line 447 of file volumeExprDriver.H.
bool isLogical () const inline
A logical (bool-like) field. Actually stored as a scalar.
Definition at line 455 of file volumeExprDriver.H.
bool isVolumeData () const inline
A volume field.
Definition at line 463 of file volumeExprDriver.H.
bool isSurfaceData () const inline
A surface field.
Definition at line 471 of file volumeExprDriver.H.
bool isPointData () const inline
A point field.
Definition at line 479 of file volumeExprDriver.H.
Referenced by parseDriver::setInternalFieldResult().
const GeoField* isResultType () const
Test if stored result pointer is the specified type.
const GeoField* isResultType (bool logical, bool dieOnNull = false) const
Test if stored result pointer is the specified type and matches the specified logical type.
void setResult (GeometricField< Type, fvPatchField, volMesh > * ptr, bool logical = false)
Set result (vol field)
Definition at line 57 of file volumeExprDriverTemplates.C.
void setResult (GeometricField< Type, fvsPatchField, surfaceMesh > * ptr, bool logical = false)
Set result (surface field)
Definition at line 86 of file volumeExprDriverTemplates.C.
void setResult (GeometricField< Type, pointPatchField, pointMesh > * ptr, bool logical = false)
Set result (point field)
Definition at line 115 of file volumeExprDriverTemplates.C.
tmp<GeometricField<Type, fvPatchField, volMesh> > newVolField (const Type & val = pTraits< Type >::zero) const
Return a new volume field with the mesh size.
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > newSurfaceField (const Type & val = pTraits< Type >::zero) const
Return a new surface field with the mesh nInternalFaces size.
tmp<GeometricField<Type, pointPatchField, pointMesh> > newPointField (const Type & val = pTraits< Type >::zero) const
Return a new point field with the mesh nPoints size.
tmp<GeometricField<Type, fvPatchField, volMesh> > getVolField (const word & fldName, bool getOldTime = false)
Retrieve field (vol field)
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > getSurfaceField (const word & fldName, bool getOldTime = false)
Retrieve field (surface field)
tmp<GeometricField<Type, pointPatchField, pointMesh> > getPointField (const word & fldName, bool getOldTime = false)
Retrieve field (surface field)
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > cellToFace (const GeometricField< Type, fvPatchField, volMesh > & field) const
Interpolate cell to face values.
tmp<GeometricField<Type, pointPatchField, pointMesh> > cellToPoint (const GeometricField< Type, fvPatchField, volMesh > & field) const
Interpolate cell to point values.
tmp<GeometricField<Type, fvPatchField, volMesh> > pointToCell (const GeometricField< Type, pointPatchField, pointMesh > & field) const
Interpolate point to cell values.
Type volAverage (GeometricField< Type, fvPatchField, volMesh > & fld) const inline
The volume-weighted average of a field.
Definition at line 617 of file volumeExprDriver.H.
Type volSum (GeometricField< Type, fvPatchField, volMesh > & fld) const inline
The volume-weighted sum of a field.
Definition at line 629 of file volumeExprDriver.H.
Type areaAverage (GeometricField< Type, fvsPatchField, surfaceMesh > & fld) const inline
The area-weighted average of a field.
Definition at line 641 of file volumeExprDriver.H.
Type areaSum (GeometricField< Type, fvsPatchField, surfaceMesh > & fld) const inline
The area-weighted sum of a field.
Definition at line 657 of file volumeExprDriver.H.
Foam::tmp< Foam::volScalarField > field_cellVolume () const
The cell volumes - (swak = vol)
Definition at line 184 of file volumeExprDriverFields.C.
Foam::tmp< Foam::volVectorField > field_cellCentre () const
The cell centres - (swak = pos)
Definition at line 197 of file volumeExprDriverFields.C.
Foam::tmp< Foam::surfaceScalarField > field_faceArea () const
The face area magnitudes [magSf] - (swak = area)
Definition at line 204 of file volumeExprDriverFields.C.
References C, mesh, and tmp< T >::New().
Foam::tmp< Foam::surfaceVectorField > field_faceCentre () const
The face centres - (swak = fpos)
Definition at line 217 of file volumeExprDriverFields.C.
Foam::tmp< Foam::surfaceVectorField > field_areaNormal () const
The face areas with their vector direction [Sf] - (swak = face)
Definition at line 230 of file volumeExprDriverFields.C.
Foam::tmp< Foam::pointVectorField > field_pointField () const
The mesh point locations - (swak = pts)
Definition at line 243 of file volumeExprDriverFields.C.
tmp<volScalarField> field_cellSet (const word & name) const inline
Cell selection (set)
Foam::tmp< Foam::volScalarField > field_cellZone (const word & name) const inline
Cell selection (zone)
Definition at line 62 of file volumeExprDriverI.H.
Foam::tmp< Foam::surfaceScalarField > field_faceSet (const word & name) const inline
Face selection (set)
Definition at line 76 of file volumeExprDriverI.H.
Foam::tmp< Foam::surfaceScalarField > field_faceZone (const word & name) const inline
Face selection (zone)
Definition at line 90 of file volumeExprDriverI.H.
Foam::tmp< Foam::pointScalarField > field_pointSet (const word & name) const inline
Point selection (set)
Definition at line 104 of file volumeExprDriverI.H.
Foam::tmp< Foam::pointScalarField > field_pointZone (const word & name) const inline
Point selection (zone)
Definition at line 118 of file volumeExprDriverI.H.
Foam::tmp< Foam::volScalarField > field_rand (label seed = 0, bool gaussian = false) const
A uniform random field.
Definition at line 257 of file volumeExprDriverFields.C.
tmp<volScalarField> field_randGaussian (label seed = 0) const inline
A Gaussian random field.
Definition at line 738 of file volumeExprDriver.H.
const GeomField* isResultType () const
Definition at line 144 of file volumeExprDriverTemplates.C.
const GeomField* isResultType (bool logical, bool dieOnNull) const
Definition at line 153 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvPatchField, Foam::volMesh> > newVolField (const Type & val) const
Definition at line 237 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > newSurfaceField (const Type & val) const
Definition at line 253 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::pointPatchField, Foam::pointMesh> > newPointField (const Type & val) const
Definition at line 269 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::fvsPatchField, Foam::surfaceMesh> > cellToFace (const GeometricField< Type, fvPatchField, volMesh > & field) const
Definition at line 285 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type, Foam::pointPatchField, Foam::pointMesh> > cellToPoint (const GeometricField< Type, fvPatchField, volMesh > & field) const
Definition at line 296 of file volumeExprDriverTemplates.C.
Foam::tmp<Foam::GeometricField<Type,Foam::fvPatchField,Foam::volMesh> > pointToCell (const GeometricField< Type, pointPatchField, pointMesh > & field) const
Definition at line 308 of file volumeExprDriverTemplates.C.
Member Data Documentation
const fvMesh& mesh_ protected
The referenced mesh.
Definition at line 237 of file volumeExprDriver.H.
Referenced by parseDriver::size().
autoPtr<regIOobject> resultField_ protected
The results (volume, surface, point)
Definition at line 242 of file volumeExprDriver.H.
word resultType_ protected
The result type-name.
Normally volScalarField, surfaceVectorField etc, but Scalar is modified for logical as volScalarField etc
Definition at line 250 of file volumeExprDriver.H.
Referenced by parseDriver::setInternalFieldResult().
bool isLogical_ protected
A logical (bool-like) field (but actually a scalar)
Definition at line 255 of file volumeExprDriver.H.
Referenced by parseDriver::setInternalFieldResult().
enum FieldAssociation fieldGeoType_ protected
A volume/surface/point field.
Definition at line 260 of file volumeExprDriver.H.
dimensionSet resultDimension_ protected
The result dimensions.
Definition at line 265 of file volumeExprDriver.H.
The documentation for this class was generated from the following files:
src/finiteVolume/expressions/volume/volumeExprDriver.H
src/finiteVolume/expressions/volume/volumeExprDriver.C
src/finiteVolume/expressions/volume/volumeExprDriverFields.C
src/finiteVolume/expressions/volume/volumeExprDriverI.H
src/finiteVolume/expressions/volume/volumeExprDriverTemplates.C