OpenFOAM: polySurface Class Reference
polySurface Class Reference
A surface mesh consisting of general polygon faces and capable of holding fields.
Public Types
enum FieldAssociation { NO_DATA = 0, FACE_DATA = 0x1, POINT_DATA = 0x2, FACE_POINT_DATA = 0x3 }
Enumeration for the field association.
typedef polySurface Mesh
Typedef required for GeoMesh.
typedef bool BoundaryMesh
Placeholder only, for GeoMesh.
Public Types inherited from IOobject
enum objectState : char { GOOD, BAD }
Enumeration defining the valid states of an IOobject.
enum readOption : char { MUST_READ, MUST_READ_IF_MODIFIED, READ_IF_PRESENT, NO_READ }
Enumeration defining the read options.
enum writeOption : char { AUTO_WRITE = 0, NO_WRITE = 1 }
Enumeration defining the write options.
enum fileCheckTypes : char { timeStamp, timeStampMaster, inotify, inotifyMaster }
Enumeration defining the file checking options.
Public Types inherited from HashTable< regIOobject * >
typedef HashTable< regIOobject
*, Key, Hash > this_type
The template instance used for this HashTable.
typedef Key key_type
The second template parameter, type of keys used.
typedef regIOobject * mapped_type
The first template parameter, type of objects contained.
typedef regIOobject * value_type
Same as mapped_type for OpenFOAM HashTables.
typedef Hash hasher
The third template parameter, the hash index method.
typedef regIOobject *& reference
Reference to the stored value_type.
typedef const regIOobject *& const_reference
Const reference to the stored value_type.
typedef label difference_type
The type to represent the difference between two iterators.
typedef label size_type
The type that can represent the size of a HashTable.
using key_iterator = key_iterator_base< iterator >
Forward iterator returning the key.
using const_key_iterator = key_iterator_base< const_iterator >
Forward const iterator returning the key.
Public Types inherited from PrimitivePatch< face,::Foam::List, pointField, point >
enum surfaceTopo
Enumeration defining the surface type. Used in check routines.
typedef face FaceType
typedef ::Foam::List< face > FaceListType
typedef pointField PointFieldType
Public Types inherited from List< face >
typedef SubList< face > subList
Declare type of subList.
Public Types inherited from UList< face >
typedef face value_type
The value type the list contains.
typedef face * pointer
The pointer type for non-const access to value_type items.
typedef const face * const_pointer
The pointer type for const access to value_type items.
typedef face & reference
The type used for storing into value_type objects.
typedef const face & const_reference
The type used for reading from constant value_type objects.
typedef face * iterator
Random access iterator for traversing a UList.
typedef const face * const_iterator
Random access iterator for traversing a UList.
typedef label size_type
The type to represent the size of a UList.
typedef label difference_type
The difference between iterator objects.
typedef std::reverse_iterator
< iterator > reverse_iterator
Reverse iterator (non-const access)
typedef std::reverse_iterator
< const_iterator > const_reverse_iterator
Reverse iterator (const access)
Public Member Functions
TypeName ("polySurface")
Runtime type information.
polySurface (const IOobject &io, bool doCheckIn=false)
Construct null with NO_READ, NO_WRITE optionally with a checkIn on the parent registry.
polySurface (const word &surfName, const objectRegistry &obr, bool doCheckIn=false)
Construct null with specified name on the given registry, optionally with a checkIn on the parent registry.
polySurface (const IOobject &io, const MeshedSurface< face > &surf, bool doCheckIn=false)
Copy construct from MeshedSurface<face> contents with NO_READ, NO_WRITE optionally with a checkIn on the parent registry.
polySurface (const IOobject &io, MeshedSurface< face > &&surf, bool doCheckIn=false)
Move construct from MeshedSurface<face> contents with NO_READ, NO_WRITE optionally with a checkIn on the parent registry.
virtual ~polySurface ()
Destructor.
virtual label nPoints () const
Return the number of points.
virtual label nFaces () const
Return the number of faces.
virtual label size () const
Return number of faces.
virtual const pointField & points () const
Return points.
virtual const faceList & faces () const
Return faces.
virtual const labelList & zoneIds () const
Const access to per-face zone/region information (demand-driven)
const vectorField & Sf () const
Return face area vectors (normals)
const scalarField & magSf () const
Return face area magnitudes.
const vectorField & Cf () const
Face centres.
void copySurface (const pointField &points, const faceList &faces, bool unused=false)
Update with new contents.
void copySurface (const meshedSurf &surf, bool unused=false)
Update with new contents.
void copySurface (const MeshedSurface< face > &surf, bool unused=false)
Update with new contents.
void transfer (pointField &&points, faceList &&faces, labelList &&zoneIds=labelList())
Transfer the contents of the argument and annul the argument.
void transfer (MeshedSurface< face > &surf, bool validate=false)
Transfer the contents of the argument and annul the argument.
label nFaceData () const
Number of main entries, without PointData sub-registry.
label nPointData () const
Number of entries on PointData sub-registry (if it exists)
FieldAssociation queryFieldAssociation (const word &fieldName) const
Query the field association (FACE or POINT)
const regIOobject * findFieldObject (const word &fieldName, const FieldAssociation association) const
Find the field object with the given name and required FieldAssociation (FACE or POINT).
template<class GeoMeshType = void>
const regIOobject * findFieldObject (const word &fieldName) const
General finding of the field object (FACE or POINT)
template<class GeoMeshType = void>
const objectRegistry * whichRegistry (const word &fieldName) const
General finding of the registry with the field object (FACE or POINT).
template<class DataType >
const objectRegistry & fieldData () const
Regular data are stored directly on the registry.
const objectRegistry & faceData () const
Face data are stored directly on the registry.
const objectRegistry & pointData () const
Point data are stored in a sub-registry.
template<class Type , class GeoMeshType = polySurfaceGeoMesh>
void storeField (const word &fieldName, const dimensionSet &dims, const Field< Type > &values)
Copy/store named field as face or point data (template parameter).
template<class Type , class GeoMeshType = polySurfaceGeoMesh>
void storeField (const word &fieldName, const dimensionSet &dims, Field< Type > &&values)
Move/store named field as face or point data (template parameter).
virtual bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp, const bool valid) const
Write all components using given format, version and compression.
void clearGeom ()
Clear geometry.
void clearAddressing ()
Clear addressing.
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
void clearPrimitives ()
Clear primitive data (points, faces and cells)
void clearFields ()
Clear stored fields.
template<>
const regIOobject * findFieldObject (const word &fieldName) const
template<>
const regIOobject * findFieldObject (const word &fieldName) const
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
template<>
const regIOobject * findFieldObject (const word &fieldName) const
Find face field object (on main registry).
template<>
const regIOobject * findFieldObject (const word &fieldName) const
Find point field object (on sub-registry)
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
Return field object (on main registry). Face data field found on main registry?
template<>
const objectRegistry * whichRegistry (const word &fieldName) const
Point data field found on sub-registry?
template<>
const objectRegistry & fieldData () const
Point data are stored in a sub-registry.
template<class GeoMeshType >
const Foam::regIOobject * findFieldObject (const word &fieldName) const
template<class GeoMeshType >
const Foam::objectRegistry * whichRegistry (const word &fieldName) const
Public Member Functions inherited from objectRegistry
TypeName ("objectRegistry")
Declare type name for this IOobject.
objectRegistry (const Time &db, const label nObjects=128)
Construct the time objectRegistry, with estimated table capacity (default: 128)
objectRegistry (const IOobject &io, const label nObjects=128)
Construct sub-registry given an IObject to describe the registry, with estimated table capacity (default: 128)
virtual ~objectRegistry ()
Destructor, with checkOut() for all objects that are ownedByRegistry.
const objectRegistry & thisDb () const
Return the object registry.
const Time & time () const
Return time.
const objectRegistry & parent () const
Return the parent objectRegistry.
virtual const fileName & dbDir () const
Local directory path of this objectRegistry relative to the time.
HashTable< wordHashSet > classes () const
A summary hash of classes used and their associated object names.
template<class MatchPredicate >
HashTable< wordHashSet > classes (const MatchPredicate &matchName) const
A summary hash of classes used and their associated object names, restricted to objects that have a matching object name.
label count (const char *clsName) const
The number of objects of the given class name.
template<class MatchPredicate >
label count (const MatchPredicate &matchClass) const
The number of objects of the given class name.
template<class MatchPredicate1 , class MatchPredicate2 >
label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
The number of objects of the given class name.
template<class Type >
label count (const bool strict=false) const
The names of objects with a class satisfying isA<Type>
template<class Type , class MatchPredicate >
label count (const MatchPredicate &matchName) const
The names of objects with a class satisfying isA<Type> that also have a matching object name.
wordList names () const
The names of all objects.
wordList names (const char *clsName) const
The names of objects with the given class name.
template<class MatchPredicate >
wordList names (const MatchPredicate &matchClass) const
The names of objects with a matching class name.
template<class MatchPredicate1 , class MatchPredicate2 >
wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
The names of objects with a matching class name that also have a matching object name.
template<class Type >
wordList names () const
The names of objects with a class satisfying isA<Type>.
template<class Type , class MatchPredicate >
wordList names (const MatchPredicate &matchName) const
The names of objects with a class satisfying isA<Type> that also have a matching object name.
wordList sortedNames () const
The sorted names of all objects.
wordList sortedNames (const char *clsName) const
The sorted names of objects with the given class name.
template<class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchClass) const
The sorted names objects with a matching class name.
template<class MatchPredicate1 , class MatchPredicate2 >
wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
The sorted names of objects with a matching class name that also have a matching object name.
template<class Type >
wordList sortedNames () const
The sorted names of objects with a class satisfying isA<Type>
template<class Type , class MatchPredicate >
wordList sortedNames (const MatchPredicate &matchName) const
The sorted names of objects with a class satisfying isA<Type> that also have a matching object name.
const objectRegistry & subRegistry (const word &name, const bool forceCreate=false, const bool recursive=false) const
Lookup and return a const sub-objectRegistry.
template<class Type >
HashTable< const Type * > lookupClass (const bool strict=false) const
Return all objects with a class satisfying isA<Type>
template<class Type >
HashTable< Type * > lookupClass (const bool strict=false)
Return all objects with a class satisfying isA<Type>
bool found (const word &name, const bool recursive=false) const
Can the regIOobject object be found (by name).
template<class Type >
bool foundObject (const word &name, const bool recursive=false) const
Is the named Type found?
template<class Type >
const Type * cfindObject (const word &name, const bool recursive=false) const
Return const pointer to the object of the given Type.
template<class Type >
const Type * findObject (const word &name, const bool recursive=false) const
Return const pointer to the object of the given Type.
template<class Type >
Type * findObject (const word &name, const bool recursive=false)
Return non-const pointer to the object of the given Type.
template<class Type >
Type * getObjectPtr (const word &name, const bool recursive=false) const
Return non-const pointer to the object of the given Type, using a const-cast to have it behave like a mutable.
template<class Type >
const Type & lookupObject (const word &name, const bool recursive=false) const
Lookup and return const reference to the object of the given Type. Fatal if not found or the wrong type.
template<class Type >
Type & lookupObjectRef (const word &name, const bool recursive=false) const
Lookup and return non-const reference to the object of the given Type. Fatal if not found or the wrong type.
label getEvent () const
Return new event number.
bool checkIn (regIOobject *io) const
Add a regIOobject to registry. A nullptr is ignored.
bool checkIn (regIOobject &io) const
Add a regIOobject to registry.
bool checkOut (regIOobject *io) const
Remove a regIOobject from registry and free memory if the object is ownedByRegistry. A nullptr is ignored.
bool checkOut (regIOobject &io) const
Remove a regIOobject from registry and free memory if the object is ownedByRegistry.
bool checkOut (const word &key) const
Remove a regIOobject by name from registry and free memory if the object is ownedByRegistry.
void clear ()
Clear all entries from the registry.
void clearStorage ()
Clear all entries from the registry and the table itself.
bool erase (const iterator &iter)
Erase an entry specified by the given iterator.
bool erase (const word &key)
Erase an entry specified by the given key.
label erase (std::initializer_list< word > keys)
Remove entries given by the listed keys.
label erase (const UList< word > &keys)
Remove entries given by the listed keys.
virtual void rename (const word &newName)
Rename.
virtual bool modified () const
Return true if any of the object's files have been modified.
void readModifiedObjects ()
Read the objects that have been modified.
virtual bool readIfModified ()
Read object if modified.
virtual bool writeData (Ostream &) const
writeData function required by regIOobject but not used.
template<class Type >
const Type * lookupObjectPtr (const word &name, bool recursive=false) const
Deprecated(2018-10) find object.
template<class Type >
Type * lookupObjectRefPtr (const word &name, bool recursive=false) const
Deprecated(2018-10) get object pointer, ignoring constness.
template<class MatchPredicate >
Foam::HashTable
< Foam::wordHashSet > classesImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label countImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName)
template<class Type , class MatchPredicate >
Foam::label countTypeImpl (const objectRegistry &list, const MatchPredicate &matchName)
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList namesImpl (const objectRegistry &list, const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName, const bool doSort)
template<class Type , class MatchPredicate >
Foam::wordList namesTypeImpl (const objectRegistry &list, const MatchPredicate &matchName, const bool doSort)
template<class MatchPredicate >
Foam::HashTable
< Foam::wordHashSet > classes (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::label count (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::label count (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::label count (const MatchPredicate &matchName) const
template<class Type >
Foam::label count (const bool strict) const
template<class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList names (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::wordList names (const MatchPredicate &matchName) const
template<class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchClass) const
template<class MatchPredicate1 , class MatchPredicate2 >
Foam::wordList sortedNames (const MatchPredicate1 &matchClass, const MatchPredicate2 &matchName) const
template<class Type , class MatchPredicate >
Foam::wordList sortedNames (const MatchPredicate &matchName) const
template<class Type >
Foam::HashTable< const Type * > lookupClass (const bool strict) const
template<class Type >
Foam::HashTable< Type * > lookupClass (const bool strict)
Public Member Functions inherited from regIOobject
TypeName ("regIOobject")
Runtime type information.
regIOobject (const IOobject &io, const bool isTime=false)
Construct from IOobject. The optional flag adds special handling if the object is the top-level regIOobject (eg, Time).
regIOobject (const regIOobject &rio)
Copy construct.
regIOobject (const regIOobject &rio, bool registerCopy)
Copy construct, transferring registry registration to the copy if registerCopy is true.
regIOobject (const word &newName, const regIOobject &, bool registerCopy)
Copy construct with new name, transferring registry registration to the copy f registerCopy is true.
regIOobject (const IOobject &io, const regIOobject &rio)
Copy construct with new IO parameters.
virtual ~regIOobject ()
Destructor.
bool checkIn ()
Add object to registry, if not already registered.
bool checkOut ()
Remove all file watches and remove object from registry.
virtual void addWatch ()
Add file watch on object (if registered and READ_IF_MODIFIED)
bool ownedByRegistry () const
Is this object owned by the registry?
void store ()
Transfer ownership of this object to its registry.
void release (const bool unregister=false)
Release ownership of this object from its registry.
label eventNo () const
Event number at last update.
label & eventNo ()
Event number at last update.
bool upToDate (const regIOobject &) const
Return true if up-to-date with respect to given object.
bool upToDate (const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
bool upToDate (const regIOobject &, const regIOobject &, const regIOobject &, const regIOobject &) const
Return true if up-to-date with respect to given objects.
void setUpToDate ()
Set as up-to-date.
virtual fileName filePath () const
Return complete path + object name if the file exists.
bool headerOk ()
Read and check header info.
Istream & readStream (const word &, const bool valid=true)
Return Istream and check object type against that given.
void close ()
Close Istream.
virtual bool readData (Istream &)
Virtual readData function.
virtual bool read ()
Read object.
virtual label addWatch (const fileName &)
Add file watch for fileName on object if not yet watched. Return.
const labelList & watchIndices () const
Return file-monitoring handles.
labelList & watchIndices ()
Return file-monitoring handles.
virtual bool write (const bool valid=true) const
Write using setting from DB.
virtual bool global () const
Is object global.
void operator= (const IOobject &)
Public Member Functions inherited from IOobject
TypeName ("IOobject")
Runtime type information.
IOobject (const word &name, const fileName &instance, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true)
Construct from name, instance, registry, io options.
IOobject (const word &name, const fileName &instance, const fileName &local, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from name, instance, local, registry, io options.
IOobject (const fileName &path, const objectRegistry &registry, readOption r=NO_READ, writeOption w=NO_WRITE, bool registerObject=true, bool globalObject=false)
Construct from path, registry, io options.
IOobject (const IOobject &io, const objectRegistry &registry)
Construct as copy resetting registry.
IOobject (const IOobject &io, const word &name)
Construct as copy resetting name.
autoPtr< IOobject > clone () const
Clone.
autoPtr< IOobject > clone (const objectRegistry &registry) const
Clone resetting registry.
virtual ~IOobject ()=default
Destructor.
const objectRegistry & db () const
Return the local objectRegistry.
const Time & time () const
Return time.
const word & name () const
Return name.
const word & headerClassName () const
Return name of the class name read from header.
word & headerClassName ()
Return non-constant access to the class name read from header.
const string & note () const
Return the optional note.
string & note ()
Return non-constant access to the optional note.
bool registerObject () const
Should object created with this IOobject be registered?
bool & registerObject ()
Should object created with this IOobject be registered?
bool globalObject () const
Is object same for all processors?
bool & globalObject ()
Is object same for all processors?
unsigned labelByteSize () const
The label byte-size, possibly read from the header.
unsigned scalarByteSize () const
The scalar byte-size, possibly read from the header.
bool isHeaderClassName (const word &clsName) const
Test if headerClassName() equals the given class name.
template<class Type >
bool isHeaderClassName () const
Test if headerClassName() equals Type::typeName.
readOption readOpt () const
The read option.
readOption & readOpt ()
Non-constant access to the read option.
writeOption writeOpt () const
The write option.
writeOption & writeOpt ()
Non-constant access to the write option.
word group () const
Return group (extension part of name)
word member () const
Return member (name without the extension)
const fileName & rootPath () const
const fileName & caseName () const
const fileName & instance () const
fileName & instance ()
const fileName & local () const
fileName path () const
The complete path.
fileName path (const word &instance, const fileName &local=fileName::null) const
The complete path with alternative instance and local.
fileName objectPath () const
The complete path + object name.
fileName localFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches locally.
fileName globalFilePath (const word &typeName, const bool search=true) const
Helper for filePath that searches up if in parallel.
bool readHeader (Istream &is)
Read header.
template<class Type >
bool typeHeaderOk (const bool checkType=true, const bool search=true, const bool verbose=true)
Read header (uses typeFilePath to find file) and check its info.
template<class Type >
void warnNoRereading () const
Helper: warn that type does not support re-reading.
bool writeHeader (Ostream &os) const
Write header.
bool writeHeader (Ostream &os, const word &objectType) const
Write header. Allow override of type.
bool good () const
bool bad () const
InfoProxy< IOobject > info () const
Return info proxy.
void operator= (const IOobject &io)
template<>
bool isHeaderClassName () const
Specialization for void always returns true (no headerClassName check).
template<class StringType >
Foam::word groupName (StringType name, const word &group)
Public Member Functions inherited from HashTable< regIOobject * >
HashTable ()
Construct null with default (128) table capacity.
HashTable (const label size)
Construct given initial table capacity.
HashTable (Istream &is, const label size=128)
Construct from Istream with default table capacity.
HashTable (const this_type &ht)
Copy construct.
HashTable (this_type &&rhs)
Move construct.
HashTable (std::initializer_list< std::pair< Key, regIOobject * >> list)
Construct from an initializer list.
~HashTable ()
Destructor.
label capacity () const noexcept
The size of the underlying table.
label size () const noexcept
The number of elements in table.
bool empty () const noexcept
True if the hash table is empty.
regIOobject *& at (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const regIOobject *& at (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
bool found (const Key &key) const
Return true if hashed entry is found in table.
iterator find (const Key &key)
Find and return an iterator set at the hashed entry.
const_iterator find (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const_iterator cfind (const Key &key) const
Find and return an const_iterator set at the hashed entry.
const regIOobject *& lookup (const Key &key, const regIOobject *&deflt) const
Return hashed entry if it exists, or return the given default.
List< Key > toc () const
The table of contents (the keys) in unsorted order.
List< Key > sortedToc () const
The table of contents (the keys) in sorted order.
List< Key > sortedToc (const Compare &comp) const
The table of contents (the keys) sorted according to the specified comparator.
List< Key > tocKeys (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the keys.
List< Key > tocValues (const UnaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the unary predicate applied to the values.
List< Key > tocEntries (const BinaryPredicate &pred, const bool invert=false) const
The table of contents (the keys) selected according to the binary predicate applied to the keys and values.
label countKeys (const UnaryPredicate &pred, const bool invert=false) const
Count the number of keys that satisfy the unary predicate.
label countValues (const UnaryPredicate &pred, const bool invert=false) const
Count the number of values that satisfy the unary predicate.
label countEntries (const BinaryPredicate &pred, const bool invert=false) const
Count the number of entries that satisfy the binary predicate.
bool emplace (const Key &key, Args &&...args)
Emplace insert a new entry, not overwriting existing entries.
bool insert (const Key &key, const regIOobject *&obj)
Copy insert a new entry, not overwriting existing entries.
bool insert (const Key &key, regIOobject *&&obj)
Move insert a new entry, not overwriting existing entries.
bool set (const Key &key, const regIOobject *&obj)
Copy assign a new entry, overwriting existing entries.
bool set (const Key &key, regIOobject *&&obj)
Move assign a new entry, overwriting existing entries.
bool erase (const iterator &iter)
Erase an entry specified by given iterator.
bool erase (const Key &key)
Erase an entry specified by the given key.
label erase (const HashTable< AnyType, Key, AnyHash > &other)
Remove table entries given by keys of the other hash-table.
label erase (std::initializer_list< Key > keys)
Remove table entries given by the listed keys.
label erase (InputIter first, InputIter last)
Remove multiple entries using an iterator range of keys.
label erase (const FixedList< Key, N > &keys)
Remove table entries given by the listed keys.
label erase (const UList< Key > &keys)
Remove table entries given by the listed keys.
label retain (const HashTable< AnyType, Key, AnyHash > &other)
Retain table entries given by keys of the other hash-table.
label filterKeys (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their keys.
label filterValues (const UnaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their values.
label filterEntries (const BinaryPredicate &pred, const bool pruning=false)
Generalized means to filter table entries based on their key/value.
void resize (const label sz)
Resize the hash table for efficiency.
void clear ()
Clear all entries from table.
void clearStorage ()
Clear the table entries and the table itself.
void swap (HashTable< regIOobject *, Key, Hash > &rhs)
Swap contents into this table.
void transfer (HashTable< regIOobject *, Key, Hash > &rhs)
Transfer contents into this table.
regIOobject *& operator[] (const Key &key)
Find and return a hashed entry. FatalError if it does not exist.
const regIOobject *& operator[] (const Key &key) const
Find and return a hashed entry. FatalError if it does not exist.
regIOobject *& operator() (const Key &key)
Return existing entry or create a new entry.
regIOobject *& operator() (const Key &key, const regIOobject *&deflt)
Return existing entry or insert a new entry.
void operator= (const this_type &rhs)
Copy assign.
void operator= (std::initializer_list< std::pair< Key, regIOobject * >> rhs)
Copy assign from an initializer list.
void operator= (this_type &&rhs)
Move assign.
bool operator== (const this_type &rhs) const
Equality. Tables are equal if all keys and values are equal, independent of order or underlying storage size.
bool operator!= (const this_type &rhs) const
The opposite of the equality operation.
this_type & operator+= (const this_type &rhs)
Add entries into this HashTable.
const_iterator_pair
< const_key_iterator,
this_type > keys () const
A const iterator begin/end pair for iterating over keys.
iterator begin ()
iterator set to the beginning of the HashTable
const_iterator begin () const
const_iterator set to the beginning of the HashTable
const_iterator cbegin () const
const_iterator set to the beginning of the HashTable
const iterator & end ()
iterator to signal the end for any HashTable
const const_iterator & end () const
const_iterator to signal the end for any HashTable
const const_iterator & cend () const
const_iterator to signal the end for any HashTable
Ostream & printInfo (Ostream &os) const
Print information.
Ostream & writeKeys (Ostream &os, const label shortLen=0) const
Write unordered keys (list), with line-breaks when length exceeds shortLen.
Public Member Functions inherited from HashTableCore
HashTableCore ()=default
Construct null.
ClassName ("HashTable")
Define template name and debug.
Public Member Functions inherited from PrimitivePatch< face,::Foam::List, pointField, point >
PrimitivePatch (const ::Foam::List< face > &faces, const Field< point > &points)
Construct from components.
PrimitivePatch (::Foam::List< face > &&faces, const Field< point > &points)
Construct from components, transferring faces.
PrimitivePatch (::Foam::List< face > &faces, Field< point > &points, const bool reuse)
Construct from components, reuse storage.
PrimitivePatch (const PrimitivePatch< face,::Foam::List, pointField, point > &)
Construct as copy.
virtual ~PrimitivePatch ()
Destructor.
void clearOut ()
void clearGeom ()
void clearTopology ()
void clearPatchMeshAddr ()
void swap (PrimitivePatch &)=delete
Suppress direct swapping, since storage containers may be const.
const Field< point > & points () const
Return reference to global points.
label nPoints () const
Return number of points supporting patch faces.
label nEdges () const
Return number of edges in patch.
const edgeList & edges () const
Return list of edges, address into LOCAL point list.
label nInternalEdges () const
Number of internal edges.
bool isInternalEdge (const label edgei) const
Is internal edge?
const labelList & boundaryPoints () const
Return list of boundary points, address into LOCAL point list.
const labelListList & faceFaces () const
Return face-face addressing.
const labelListList & edgeFaces () const
Return edge-face addressing.
const labelListList & faceEdges () const
Return face-edge addressing.
const labelListList & pointEdges () const
Return point-edge addressing.
const labelListList & pointFaces () const
Return point-face addressing.
const List< face > & localFaces () const
Return patch faces addressing into local point list.
const labelList & meshPoints () const
Return labelList of mesh points in patch.
const Map< label > & meshPointMap () const
Mesh point map.
const Field< point > & localPoints () const
Return pointField of points in patch.
const labelList & localPointOrder () const
Return orders the local points for most efficient search.
label whichPoint (const label gp) const
Given a global point index, return the local point index.
label whichEdge (const edge &) const
Given an edge in local point labels, return its index in the edge list. If the edge is not found, return -1.
labelList meshEdges (const edgeList &allEdges, const labelListList &cellEdges, const labelList &faceCells) const
Return labels of patch edges in the global edge list using cell addressing.
labelList meshEdges (const edgeList &allEdges, const labelListList &pointEdges) const
Return labels of patch edges in the global edge list using basic edge addressing.
const Field< point > & faceCentres () const
Return face centres for patch.
const Field< point > & faceAreas () const
Return face area vectors for patch.
const Field< scalar > & magFaceAreas () const
Return face area magnitudes for patch.
const Field< point > & faceNormals () const
Return face unit normals for patch.
const Field< point > & pointNormals () const
Return point normals for patch.
bool hasFaceAreas () const
bool hasFaceCentres () const
bool hasFaceNormals () const
bool hasPointNormals () const
List< objectHit > projectPoints (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
List< objectHit > projectFaceCentres (const ToPatch &targetPatch, const Field< point > &projectionDirection, const intersection::algorithm=intersection::FULL_RAY, const intersection::direction=intersection::VECTOR) const
Project vertices of patch onto another patch.
const labelListList & edgeLoops () const
Return list of closed loops of boundary vertices.
surfaceTopo surfaceType () const
Calculate surface type formed by patch.
bool checkTopology (const bool report=false, labelHashSet *setPtr=nullptr) const
Check surface formed by patch for manifoldness (see above).
bool checkPointManifold (const bool report=false, labelHashSet *setPtr=nullptr) const
Checks primitivePatch for faces sharing point but not edge.
virtual void movePoints (const Field< point > &)
Correct patch after moving points.
void operator= (const PrimitivePatch< face,::Foam::List, pointField, point > &)
Assignment.
Public Member Functions inherited from List< face >
constexpr List () noexcept
Null constructor.
List (const label len)
Construct with given size.
List (const label len, const face &val)
Construct with given size and value for all elements.
List (const label len, const zero)
Construct with given size initializing all elements to zero.
List (const one, const face &val)
Construct with length=1, copying the value as the only content.
List (const one, face &&val)
Construct with length=1, moving the value as the only content.
List (const one, const zero)
Construct with length=1, initializing content to zero.
List (const List< face > &a)
Copy construct from list.
List (const UList< face > &a)
Copy construct contents from list.
List (List< face > &a, bool reuse)
Construct as copy or re-use as specified.
List (const UList< face > &list, const labelUList &mapAddressing)
Construct as subset.
List (InputIterator begIter, InputIterator endIter)
Construct given begin/end iterators.
List (const FixedList< face, N > &list)
Construct as copy of FixedList<T, N>
List (const PtrList< face > &list)
Construct as copy of PtrList<T>
List (const SLList< face > &list)
Construct as copy of SLList<T>
List (const IndirectListBase< face, Addr > &list)
Construct as copy of IndirectList contents.
List (std::initializer_list< face > list)
Construct from an initializer list.
List (List< face > &&list)
Move construct from List.
List (DynamicList< face, SizeMin > &&list)
Move construct from DynamicList.
List (SortableList< face > &&list)
Move construct from SortableList.
List (SLList< face > &&list)
Move construct from SLList.
List (Istream &is)
Construct from Istream.
autoPtr< List< face > > clone () const
Clone.
~List ()
Destructor.
void resize (const label newSize)
Adjust allocated size of list.
void resize (const label newSize, const face &val)
Adjust allocated size of list and set val for new elements.
void setSize (const label newSize)
Alias for resize(const label)
void setSize (const label newSize, const face &val)
Alias for resize(const label, const T&)
void clear ()
Clear the list, i.e. set size to zero.
void append (const face &val)
Append an element at the end of the list.
void append (face &&val)
Move append an element at the end of the list.
void append (const UList< face > &list)
Append a List to the end of this list.
void append (const IndirectListBase< face, Addr > &list)
Append IndirectList contents at the end of this list.
void transfer (List< face > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (DynamicList< face, SizeMin > &list)
Transfer the contents of the argument List into this list and annul the argument list.
void transfer (SortableList< face > &list)
Transfer the contents of the argument List into this list and annul the argument list.
face & newElmt (const label i)
Return subscript-checked element of UList and resizing the list if required.
void operator= (const UList< face > &a)
Assignment to UList operator. Takes linear time.
void operator= (const List< face > &list)
Assignment operator. Takes linear time.
void operator= (const SLList< face > &list)
Assignment to SLList operator. Takes linear time.
void operator= (const IndirectListBase< face, Addr > &list)
Assignment from IndirectList. Takes linear time.
void operator= (std::initializer_list< face > list)
Assignment to an initializer list.
void operator= (const face &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
void operator= (List< face > &&list)
Move assignment. Takes constant time.
void operator= (DynamicList< face, SizeMin > &&list)
Move assignment. Takes constant time.
void operator= (SortableList< face > &&list)
Move assignment. Takes constant time.
void operator= (SLList< face > &&list)
Move assignment. Takes constant time.
void shallowCopy (const UList< face > &)=delete
No shallowCopy permitted.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type set (const label i, bool val=true)
A bitSet::set() method for a list of bool.
Public Member Functions inherited from UList< face >
label size () const noexcept
The number of elements in the UList.
void writeEntry (const word &keyword, Ostream &os) const
Write the List as a dictionary entry with keyword.
void operator= (const face &val)
Assignment of all entries to the given value.
void operator= (const zero)
Assignment of all entries to zero.
constexpr UList () noexcept
Null constructor.
UList (face *__restrict__ v, label size) noexcept
Construct from components.
label fcIndex (const label i) const
Return the forward circular index, i.e. next index which returns to the first at the end of the list.
const face & fcValue (const label i) const
Return forward circular value (ie, next value in the list)
face & fcValue (const label i)
Return forward circular value (ie, next value in the list)
label rcIndex (const label i) const
Return the reverse circular index, i.e. previous index which returns to the last at the beginning of the list.
const face & rcValue (const label i) const
Return reverse circular value (ie, previous value in the list)
face & rcValue (const label i)
Return reverse circular value (ie, previous value in the list)
std::streamsize byteSize () const
Return the binary size in number of characters of the UList if the element is a primitive type.
const face * cdata () const
Return a const pointer to the first data element.
face * data ()
Return a pointer to the first data element.
face & first ()
Return the first element of the list.
const face & first () const
Return first element of the list.
face & last ()
Return the last element of the list.
const face & last () const
Return the last element of the list.
void checkStart (const label start) const
Check start is within valid range [0,size)
void checkSize (const label size) const
Check size is within valid range [0,size].
void checkIndex (const label i) const
Check index is within valid range [0,size)
bool uniform () const
True if all entries have identical values, and list is non-empty.
label find (const face &val, const label start=0) const
Find index of the first occurrence of the value.
label rfind (const face &val, const label pos=-1) const
Find index of the last occurrence of the value.
bool found (const face &val, const label start=0) const
True if the value if found in the list.
void moveFirst (const label i)
Move element to the first position.
void moveLast (const label i)
Move element to the last position.
void swapFirst (const label i)
Swap element with the first element. Fatal on an empty list.
void swapLast (const label i)
Swap element with the last element. Fatal on an empty list.
void shallowCopy (const UList< face > &list)
Copy the pointer held by the given UList.
void deepCopy (const UList< face > &list)
Copy elements of the given UList.
face & operator[] (const label i)
Return element of UList.
const face & operator[] (const label i) const
Return element of constant UList.
UList< face > operator[] (const labelRange &range)
Return (start,size) subset from UList with non-const access.
const UList< face > operator[] (const labelRange &range) const
Return (start,size) subset from UList with const access.
operator const Foam::List< face > & () const
Allow cast to a const List<T>&.
iterator begin ()
Return an iterator to begin traversing the UList.
const_iterator begin () const
Return const_iterator to begin traversing the constant UList.
iterator end ()
Return an iterator to end traversing the UList.
const_iterator end () const
Return const_iterator to end traversing the constant UList.
const_iterator cbegin () const
Return const_iterator to begin traversing the constant UList.
const_iterator cend () const
Return const_iterator to end traversing the constant UList.
reverse_iterator rbegin ()
Return reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator rbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
reverse_iterator rend ()
Return reverse_iterator to end reverse traversing the UList.
const_reverse_iterator rend () const
Return const_reverse_iterator to end reverse traversing the UList.
const_reverse_iterator crbegin () const
Return const_reverse_iterator to begin reverse traversing the UList.
const_reverse_iterator crend () const
Return const_reverse_iterator to end reverse traversing the UList.
bool empty () const noexcept
True if the UList is empty (ie, size() is zero)
void swap (UList< face > &list)
Swap content with another UList of the same type in constant time.
bool operator== (const UList< face > &a) const
Equality operation on ULists of the same type.
bool operator!= (const UList< face > &a) const
The opposite of the equality operation. Takes linear time.
bool operator< (const UList< face > &list) const
Compare two ULists lexicographically. Takes linear time.
bool operator> (const UList< face > &a) const
Compare two ULists lexicographically. Takes linear time.
bool operator<= (const UList< face > &a) const
Return true if !(a > b). Takes linear time.
bool operator>= (const UList< face > &a) const
Return true if !(a < b). Takes linear time.
Ostream & writeList (Ostream &os, const label shortLen=0) const
Write List, with line-breaks in ASCII when length exceeds shortLen.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type test (const label i) const
A bitSet::test() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type get (const label i) const
A bitSet::get() method for a list of bool.
std::enable_if< std::is_same
< bool, TypeT >::value, bool >
::type unset (const label i)
A bitSet::unset() method for a list of bool.
Public Member Functions inherited from meshedSurf
meshedSurf ()=default
Construct null.
virtual ~meshedSurf ()=default
Destructor.
Static Public Attributes
static const word pointDataName
Name for point fields sub-registry.
Static Public Attributes inherited from regIOobject
static float fileModificationSkew
static int maxFileModificationPolls
Static Public Attributes inherited from IOobject
static const Enum< fileCheckTypes > fileCheckTypesNames
Names for the fileCheckTypes.
static fileCheckTypes fileModificationChecking
Type of file modification checking.
Static Public Attributes inherited from HashTableCore
static const label maxTableSize
Maximum allowable internal table size. Approximately labelMax/4.
Protected Member Functions
pointField & storedPoints ()
Non-const access to points.
faceList & storedFaces ()
Non-const access to the faces.
const faceList & storedFaces () const
Const access to the faces.
Protected Member Functions inherited from regIOobject
bool readHeaderOk (const IOstream::streamFormat PstreamFormat, const word &typeName)
Helper: check readOpt flags and read if necessary.
Istream * objectStream ()
Construct and return an IFstream for the object.
Protected Member Functions inherited from IOobject
void setBad (const string &s)
Set the object state to bad.
Protected Member Functions inherited from HashTable< regIOobject * >
bool iterator_erase (node_type *&entry, label &index)
Low-level entry erasure using iterator internals.
Protected Member Functions inherited from UList< face >
void size (const label n) noexcept
Override size to be inconsistent with allocated storage.
void writeEntry (Ostream &os) const
Write the UList with its compound type.
labelRange validateRange (const labelRange &range) const
Return a validated (start,size) subset range, which means that it always addresses a valid section of the list.
UList< face > & operator= (const UList< face > &)=delete
No copy assignment (default: shallow copy)
Additional Inherited Members
Static Public Member Functions inherited from regIOobject
template<class Type >
static Type & store (Type *p)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &aptr)
Transfer ownership of the given object pointer to its registry.
template<class Type >
static Type & store (autoPtr< Type > &&aptr)
Transfer ownership of the given object pointer to its registry.
Static Public Member Functions inherited from IOobject
static bool fileNameComponents (const fileName &path, fileName &instance, fileName &local, word &name)
Split path into instance, local, name components.
template<class StringType >
static word groupName (StringType name, const word &group)
Create dot-delimited name.group.
static word group (const word &name)
Return group (extension part of name)
static word member (const word &name)
Return member (name without the extension)
static IOobject selectIO (const IOobject &io, const fileName &altFile, const word &ioName="")
Return the IOobject, but also consider an alternative file name.
static Ostream & writeBanner (Ostream &os, bool noHint=false)
Write the standard OpenFOAM file/dictionary banner.
static Ostream & writeDivider (Ostream &os)
Write the standard file section divider.
static Ostream & writeEndDivider (Ostream &os)
Write the standard end file divider.
Static Public Member Functions inherited from HashTableCore
static label canonicalSize (const label requested_size)
Return a canonical (power-of-two) of the requested size.
template<class IteratorType , class TableType >
static IteratorType iterator_begin (TableType &table)
Factory method to create a non-const iterator begin.
template<class IteratorType , class TableType >
static IteratorType iterator_cbegin (const TableType &table)
Factory method to create a const iterator begin.
template<class IteratorType >
static const IteratorType & iterator_end ()
Factory method to return an iterator end.
template<class IteratorType >
static const IteratorType & iterator_cend ()
Factory method to return an iterator cend.
Static Public Member Functions inherited from List< face >
static const List< face > & null ()
Return a null List.
Static Public Member Functions inherited from UList< face >
static const UList< face > & null ()
Return a UList reference to a nullObject.
static constexpr label max_size () noexcept
The size of the largest possible UList.
Static Protected Attributes inherited from regIOobject
static bool masterOnlyReading = false
To flag master-only reading of objects.
Detailed Description
A surface mesh consisting of general polygon faces and capable of holding fields.
Source files
polySurface.H
polySurface.C
polySurfaceClear.C
polySurfaceIO.C
polySurfaceTemplates.C
Definition at line 63 of file polySurface.H.
Member Typedef Documentation
typedef polySurface Mesh
Typedef required for GeoMesh.
Definition at line 163 of file polySurface.H.
typedef bool BoundaryMesh
Placeholder only, for GeoMesh.
Definition at line 168 of file polySurface.H.
Member Enumeration Documentation
enum FieldAssociation
Enumeration for the field association.
Enumerator
NO_DATA
No associated data.
FACE_DATA
Data associated with faces.
POINT_DATA
Data associated with points.
FACE_POINT_DATA
Data associated with faces and points.
Definition at line 74 of file polySurface.H.
Constructor & Destructor Documentation
polySurface (const IOobject & io, bool doCheckIn = false) explicit
Construct null with NO_READ, NO_WRITE optionally with a checkIn on the parent registry.
Created without a PointData sub-registry
Definition at line 78 of file polySurface.C.
polySurface (const word & surfName, const objectRegistry & obr, bool doCheckIn = false)
Construct null with specified name on the given registry, optionally with a checkIn on the parent registry.
Created without a PointData sub-registry
Definition at line 105 of file polySurface.C.
References regIOobject::store().
polySurface (const IOobject & io, const MeshedSurface< face > & surf, bool doCheckIn = false)
Copy construct from MeshedSurface<face> contents with NO_READ, NO_WRITE optionally with a checkIn on the parent registry.
Created without a PointData sub-registry
Definition at line 128 of file polySurface.C.
polySurface (const IOobject & io, MeshedSurface< face > && surf, bool doCheckIn = false)
Move construct from MeshedSurface<face> contents with NO_READ, NO_WRITE optionally with a checkIn on the parent registry.
Created without a PointData sub-registry
Definition at line 141 of file polySurface.C.
~polySurface () virtual
Destructor.
clearOut(); // Clear addressing
Definition at line 155 of file polySurface.C.
References transfer().
Member Function Documentation
pointField& storedPoints () inline protected
Non-const access to points.
Definition at line 130 of file polySurface.H.
faceList& storedFaces () inline protected
Non-const access to the faces.
Definition at line 138 of file polySurface.H.
const faceList& storedFaces () const inline protected
Const access to the faces.
Definition at line 146 of file polySurface.H.
TypeName ("polySurface")
Runtime type information.
virtual label nPoints () const inline virtual
Return the number of points.
Definition at line 255 of file polySurface.H.
References PrimitivePatch< face,::Foam::List, pointField, point >::faceAreas().
virtual label nFaces () const inline virtual
Return the number of faces.
Definition at line 263 of file polySurface.H.
References PrimitivePatch< face,::Foam::List, pointField, point >::magFaceAreas().
virtual label size () const inline virtual
Return number of faces.
Definition at line 271 of file polySurface.H.
virtual const pointField& points () const inline virtual
Return points.
Implements meshedSurf.
Definition at line 280 of file polySurface.H.
Referenced by surface::gatherSurfacePieces(), and polySurfacePointGeoMesh::size().
virtual const faceList& faces () const inline virtual
Return faces.
Implements meshedSurf.
Definition at line 288 of file polySurface.H.
Referenced by surface::gatherSurfacePieces(), and polySurfaceGeoMesh::size().
virtual const labelList& zoneIds () const inline virtual
Const access to per-face zone/region information (demand-driven)
Reimplemented from meshedSurf.
Definition at line 296 of file polySurface.H.
const vectorField& Sf () const inline
Return face area vectors (normals)
Definition at line 304 of file polySurface.H.
const scalarField& magSf () const inline
Return face area magnitudes.
Definition at line 312 of file polySurface.H.
const vectorField& Cf () const inline
Face centres.
Definition at line 320 of file polySurface.H.
void copySurface (const pointField & points, const faceList & faces, bool unused = false)
Update with new contents.
Definition at line 273 of file polySurface.C.
void copySurface (const meshedSurf & surf, bool unused = false)
Update with new contents.
Definition at line 304 of file polySurface.C.
void copySurface (const MeshedSurface< face > & surf, bool unused = false)
Update with new contents.
Definition at line 334 of file polySurface.C.
void transfer (pointField && points, faceList && faces, labelList && zoneIds = labelList())
Transfer the contents of the argument and annul the argument.
Optionally validate the zone coverage.
Definition at line 364 of file polySurface.C.
void transfer (MeshedSurface< face > & surf, bool validate = false)
Transfer the contents of the argument and annul the argument.
Optionally validate the zone coverage.
Definition at line 380 of file polySurface.C.
Foam::label nFaceData () const
Number of main entries, without PointData sub-registry.
Definition at line 163 of file polySurface.C.
Foam::label nPointData () const
Number of entries on PointData sub-registry (if it exists)
Definition at line 177 of file polySurface.C.
Foam::polySurface::FieldAssociation queryFieldAssociation (const word & fieldName) const
Query the field association (FACE or POINT)
Definition at line 205 of file polySurface.C.
References objectRegistry::subRegistry().
const Foam::regIOobject * findFieldObject (const word & fieldName, const FieldAssociation association) const
Find the field object with the given name and required FieldAssociation (FACE or POINT).
For FACE_POINT_DATA, face data are checked first.
Returns
nullptr is the field was not found
Definition at line 235 of file polySurface.C.
const regIOobject* findFieldObject (const word & fieldName) const
General finding of the field object (FACE or POINT)
Later specializations are used to restrict the scope.
Returns
nullptr is the field was not found
const objectRegistry* whichRegistry (const word & fieldName) const
General finding of the registry with the field object (FACE or POINT).
Later specializations are used to restrict the scope.
Returns
nullptr is the field was not found
const objectRegistry& fieldData () const inline
Regular data are stored directly on the registry.
Definition at line 433 of file polySurface.H.
const Foam::objectRegistry & faceData () const
Face data are stored directly on the registry.
Definition at line 191 of file polySurface.C.
const Foam::objectRegistry & pointData () const
Point data are stored in a sub-registry.
Note that this method with automatically create the corresponding sub-registry if it did not previously exist. Use the nPointData() methods instead if you wish to test for content without this side-effect.
Definition at line 197 of file polySurface.C.
void storeField (const word & fieldName, const dimensionSet & dims, const Field< Type > & values)
Copy/store named field as face or point data (template parameter).
Default is face-data (polySurfaceGeoMesh as template). For point data use (polySurfacePointGeoMesh as template).
Definition at line 89 of file polySurfaceTemplates.C.
void storeField (const word & fieldName, const dimensionSet & dims, Field< Type > && values)
Move/store named field as face or point data (template parameter).
Default is face-data (polySurfaceGeoMesh as template). For point data use (polySurfacePointGeoMesh as template).
Definition at line 130 of file polySurfaceTemplates.C.
bool writeObject (IOstream::streamFormat fmt, IOstream::versionNumber ver, IOstream::compressionType cmp, const bool valid) const virtual
Write all components using given format, version and compression.
Reimplemented from objectRegistry.
Definition at line 26 of file polySurfaceIO.C.
void clearGeom ()
Clear geometry.
Definition at line 27 of file polySurfaceClear.C.
void clearAddressing ()
Clear addressing.
Definition at line 35 of file polySurfaceClear.C.
References PrimitivePatch< face,::Foam::List, pointField, point >::clearGeom(), DebugInFunction, and Foam::endl().
void clearOut ()
Clear all geometry and addressing unnecessary for CFD.
Definition at line 43 of file polySurfaceClear.C.
References DebugInFunction, and Foam::endl().
void clearPrimitives ()
Clear primitive data (points, faces and cells)
void clearFields ()
Clear stored fields.
Definition at line 52 of file polySurfaceClear.C.
const regIOobject* findFieldObject (const word & fieldName) const
Definition at line 445 of file polySurface.C.
const regIOobject* findFieldObject (const word & fieldName) const
Definition at line 456 of file polySurface.C.
const objectRegistry* whichRegistry (const word & fieldName) const
Definition at line 477 of file polySurface.C.
const objectRegistry* whichRegistry (const word & fieldName) const
Definition at line 495 of file polySurface.C.
const regIOobject* findFieldObject (const word & fieldName) const
Find face field object (on main registry).
const regIOobject* findFieldObject (const word & fieldName) const
Find point field object (on sub-registry)
const objectRegistry* whichRegistry (const word & fieldName) const
Return field object (on main registry). Face data field found on main registry?
const objectRegistry* whichRegistry (const word & fieldName) const
Point data field found on sub-registry?
const objectRegistry& fieldData () const inline
Point data are stored in a sub-registry.
Definition at line 574 of file polySurface.H.
const Foam::regIOobject* findFieldObject (const word & fieldName) const
Definition at line 29 of file polySurfaceTemplates.C.
References objectRegistry::cfindObject(), forAllConstIters, and iter.
const Foam::objectRegistry* whichRegistry (const word & fieldName) const
Definition at line 60 of file polySurfaceTemplates.C.
Member Data Documentation
const Foam::word pointDataName static
Name for point fields sub-registry.
Definition at line 173 of file polySurface.H.
The documentation for this class was generated from the following files:
src/surfMesh/polySurface/polySurface.H
src/surfMesh/polySurface/polySurface.C
src/surfMesh/polySurface/polySurfaceClear.C
src/surfMesh/polySurface/polySurfaceIO.C
src/surfMesh/polySurface/polySurfaceTemplates.C