OpenFOAM: src/dynamicFvMesh/include/createDynamicFvMesh.H File Reference
createDynamicFvMesh.H File Reference
Functions
Info<< "Create mesh for time = "
<< runTime.timeName()<< nl
<< endl;autoPtr< dynamicFvMesh > meshPtr (dynamicFvMesh::New(args, runTime))
Variables
dynamicFvMesh & mesh = meshPtr()
Function Documentation
Info<< "Create mesh for time = " << runTime.timeName() << nl << endl;autoPtr<dynamicFvMesh> meshPtr (dynamicFvMesh:: Newargs, runTime)
Variable Documentation
dynamicFvMesh& mesh = meshPtr()
Definition at line 6 of file createDynamicFvMesh.H.
Referenced by isoSurface::adaptPatchFields(), fileFieldSelection::addInternalFieldTypes(), fvMeshTools::addPatch(), Foam::fvc::alphaCorr(), Foam::fac::average(), Foam::fvc::average(), faMesh::boundary(), Foam::calc_rhoU(), faceLimitedGrad< Type >::calcGrad(), cellMDLimitedGrad< Type >::calcGrad(), faceMDLimitedGrad< Type >::calcGrad(), faceZone::checkParallelSync(), ORourkeCollision< CloudType >::collide(), Foam::constrainPressure(), Foam::MULES::correct(), correctedLnGrad< Type >::correction(), fourthLnGrad< Type >::correction(), pointLinear< Type >::correction(), linearUpwind< Type >::correction(), limitedLnGrad< Type >::correction(), linearUpwindV< Type >::correction(), linearUpwindNormal< Type >::correction(), Foam::CorrectPhi(), Foam::correctUphiBCs(), cellCellStencil::createField(), Foam::createZeroFieldPtr(), Foam::fac::d2dt2(), Foam::fac::ddt(), Foam::fvc::ddt(), codedPoints0MotionSolver::description(), Foam::fac::edgeIntegrate(), sampledThresholdCellFaces::expire(), sampledIsoSurface::expire(), Foam::MULES::explicitSolve(), steadyStateFaDdtScheme< Type >::facDdt(), EulerFaDdtScheme< Type >::facDdt(), backwardFaDdtScheme< Type >::facDdt(), polyPatch::faceAreas(), polyPatch::faceCellCentres(), faMesh::facesInstance(), faMeshLduAddressing::faMeshLduAddressing(), gaussLaplacianScheme< Type >::famLaplacian(), parseDriver::field_faceArea(), pointBoundaryMesh::findPatchID(), fvBoundaryMesh::findPatchID(), cellCuts::flip(), for(), forAll(), FSD< ReactionThermo, ThermoType >::FSD(), skewCorrectedSnGrad< Type >::fullGradCorrection(), correctedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), steadyStateD2dt2Scheme< Type >::fvcD2dt2(), EulerD2dt2Scheme< Type >::fvcD2dt2(), steadyStateDdtScheme< Type >::fvcDdt(), EulerDdtScheme< Type >::fvcDdt(), backwardDdtScheme< Type >::fvcDdt(), CrankNicolsonDdtScheme< Type >::fvcDdt(), gaussLaplacianScheme< Type, GType >::fvcLaplacian(), fvMeshLduAddressing::fvMeshLduAddressing(), gaussLaplacianScheme< Type, GType >::fvmLaplacianUncorrected(), fvExprDriver::getFieldClassName(), boundaryMesh::getNearest(), sampledSet::getNeighbourCell(), fvExprDriver::hasDataToWrite(), if(), InflationInjection< CloudType >::InflationInjection(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), InterfaceCompositionPhaseChangePhaseSystem< BasePhaseSystem >::InterfaceCompositionPhaseChangePhaseSystem(), multivariateGaussConvectionScheme< Type >::interpolate(), Foam::interpolatePointToCell(), fvExprDriver::isFaceZone(), fvExprDriver::isPointZone(), Foam::levelSetFraction(), Foam::MULES::limit(), Foam::MULES::limitCorr(), Foam::MULES::limiter(), PhiScheme< Type, PhiLimiter >::limiter(), LimitedScheme< Type, Limiter, LimitFunc >::limiter(), Foam::MULES::limiterCorr(), Foam::loadPointField(), fvExprDriver::lookupGlobal(), KinematicParcel< ParcelType >::mass(), DSMCParcel< ParcelType >::move(), sampledIsoSurfaceCell::needsUpdate(), scatterModel::New(), surfaceFilmModel::New(), lnGradScheme< Type >::New(), gradScheme< Type >::New(), snGradScheme< Type >::New(), solidReactionThermo::New(), heatTransferCoeffModel::New(), psiuReactionThermo::New(), divScheme< Type >::New(), psiReactionThermo::New(), rhoReactionThermo::New(), faD2dt2Scheme< Type >::New(), faDdtScheme< Type >::New(), d2dt2Scheme< Type >::New(), fluidThermo::New(), surfaceTensionModel::New(), reactionRateFlameArea::New(), solidThermo::New(), ParticleForce< CloudType >::New(), psiThermo::New(), multivariateSurfaceInterpolationScheme< Type >::New(), laplacianScheme< Type >::New(), ddtScheme< Type >::New(), optMeshMovement::New(), rhoThermo::New(), laplacianScheme< Type, GType >::New(), thermalBaffleModel::New(), pyrolysisModel::New(), updateMethod::New(), porosityModel::New(), waveModel::New(), findUniqueIntersectOp::operator()(), oldCyclicPolyPatch::order(), Foam::oversetAdjustPhi(), faMesh::patch(), sampledSet::pointInCell(), faMesh::pointsInstance(), PopulationBalancePhaseSystem< BasePhaseSystem >::PopulationBalancePhaseSystem(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::pyrolysisChemistryModel(), pyrolysisModelCollection::pyrolysisModelCollection(), Foam::fvc::reconstruct(), Foam::fvc::reconstructMag(), regionSplit::reduceRegions(), regionSplit2D::regionSplit2D(), hexRef8::removeFiles(), ThermoCloud< CloudType >::setModels(), singleStepCombustion< ReactionThermo, ThermoType >::singleStepCombustion(), Foam::fvc::smooth(), solidChemistryModel< CompType, SolidThermo >::solidChemistryModel(), displacementMeshMoverMotionSolver::solve(), elasticityMotionSolver::solve(), GAMGSolver::solve(), Foam::fam::Su(), Foam::fvc::surfaceIntegrate(), mappedPatchBase::surfPtr(), ThermalPhaseChangePhaseSystem< BasePhaseSystem >::ThermalPhaseChangePhaseSystem(), faMesh::time(), PatchInjection< CloudType >::timeEnd(), PatchFlowRateInjection< CloudType >::timeEnd(), fvExprDriver::timeName(), TwoResistanceHeatTransferPhaseSystem< BasePhaseSystem >::TwoResistanceHeatTransferPhaseSystem(), sampledTriSurfaceMesh::update(), discreteSurface::update(), extendedUpwindCellToFaceStencil::weightedSum(), PatchCollisionDensity< CloudType >::write(), Foam::writeDimFields(), Foam::writeVolField(), Foam::ensightOutput::Detail::writeVolField(), Foam::writeVolFields(), StationaryPhaseModel< BasePhaseModel >::zeroField(), basicThermo::~basicThermo(), fluidThermo::~fluidThermo(), medialAxisMeshMover::~medialAxisMeshMover(), psiReactionThermo::~psiReactionThermo(), psiThermo::~psiThermo(), psiuReactionThermo::~psiuReactionThermo(), rhoReactionThermo::~rhoReactionThermo(), rhoThermo::~rhoThermo(), solidReactionThermo::~solidReactionThermo(), and solidThermo::~solidThermo().