OpenFOAM: src/finiteVolume/cfdTools/compressible/createRhoUfIfPresent.H File Reference
createRhoUfIfPresent.H File Reference
Creates and initialises the velocity field rhoUf if required.
Functions
rhoUf reset (new surfaceVectorField(IOobject("rhoUf", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), fvc::interpolate(rho *U)))
Variables
autoPtr< surfaceVectorField > rhoUf
Detailed Description
Creates and initialises the velocity field rhoUf if required.
Original source file createRhoUfIfPresent.H
Definition in file createRhoUfIfPresent.H.
Function Documentation
rhoUf reset (new surfaceVectorFieldIOobject("rhoUf", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), fvc::interpolate(rho *U))
Referenced by vtuCells::clear(), PackedList< Width >::clearStorage(), CStringList::CStringList(), globalIndex::globalIndex(), globalIndex::offset(), dimensionSet::operator/=(), token::operator=(), token::operator==(), optionAdjointList::optionAdjointList(), optionList::optionList(), autoPtr< T >::reset(), token::reset(), autoPtr< T >::swap(), vtuCells::vtuCells(), and CStringList::~CStringList().
Variable Documentation
autoPtr<surfaceVectorField> rhoUf
Definition at line 27 of file createRhoUfIfPresent.H.
Referenced by if().