OpenFOAM: src/thermophysicalModels/radiation/include/createIncompressibleRadiationModel.H File Reference
createIncompressibleRadiationModel.H File Reference
Functions
autoPtr
< radiation::radiationModel > radiation (radiation::radiationModel::New(T))
dimensionedScalar rhoCpRef ("rhoCpRef", dimDensity *dimEnergy/dimMass/dimTemperature, 1.0)
dimensionedScalar rhoRef ("rhoRef", dimDensity, transportProperties)
dimensionedScalar CpRef ("CpRef", dimSpecificHeatCapacity, transportProperties)
Variables
rhoCpRef = rhoRef*CpRef
Function Documentation
autoPtr<radiation::radiationModel> radiation (radiation::radiationModel:: NewT)
Referenced by fvDOM::blackBody(), forAll(), and viewFactor::nBands().
dimensionedScalar rhoCpRef ("rhoCpRef" , dimDensity *dimEnergy/dimMass/ dimTemperature, 1. 0)
dimensionedScalar rhoRef ("rhoRef" , dimDensity , transportProperties)
Referenced by Foam::calc_rhoU(), and lumpedPointMovement::forcesAndMoments().
dimensionedScalar CpRef ("CpRef" , dimSpecificHeatCapacity , transportProperties)
Variable Documentation
rhoCpRef = rhoRef*CpRef
Definition at line 42 of file createIncompressibleRadiationModel.H.