OpenFOAM: src/finiteVolume/fields/fvPatchFields/derived/cylindricalInletVelocity/cylindricalInletVelocityFvPatchVectorField.C File Reference
cylindricalInletVelocityFvPatchVectorField.C File Reference
Functions
axis_ (dict.lookup("axis"))
axialVelocity_ (Function1< scalar >::New("axialVelocity", dict))
radialVelocity_ (Function1< scalar >::New("radialVelocity", dict))
origin_ (ptf.origin_)
axis_ (ptf.axis_)
axialVelocity_ (ptf.axialVelocity_.clone())
radialVelocity_ (ptf.radialVelocity_.clone())
Detailed Description
Original source file cylindricalInletVelocityFvPatchVectorField.C
Definition in file cylindricalInletVelocityFvPatchVectorField.C.
Function Documentation
axis_ (dict. lookup"axis")
Referenced by MRFZone::addCoriolis(), angularOscillatingDisplacementPointPatchVectorField::angularOscillatingDisplacementPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), axisAngle::axisAngle(), lumpedPointMovement::coupler(), lumpedPointMovement::displacePoints(), lumpedPointMovement::locations(), SRFModel::omega(), axisAngle::R(), axis::read(), lumpedPointMovement::readDict(), coordSet::scalarCoord(), lumpedPointMovement::setBoundBox(), axisAngle::write(), lumpedPointMovement::writeData(), lumpedPointMovement::writeDict(), and axisAngle::writeEntry().
axialVelocity_ (Function1< scalar >:: New"axialVelocity", dict)
radialVelocity_ (Function1< scalar >:: New"radialVelocity", dict)
origin_ (ptf. origin_)
Referenced by angularOscillatingDisplacementPointPatchVectorField::angularOscillatingDisplacementPointPatchVectorField(), angularOscillatingVelocityPointPatchVectorField::angularOscillatingVelocityPointPatchVectorField(), SRFModel::axis(), searchablePlate::boundingSpheres(), coordinateSystem::clear(), plane::distance(), wallPoint::distSqr(), patchEdgeFaceInfo::distSqr(), pointEdgePoint::distSqr(), externalPointEdgePoint::distSqr(), sweepData::enterDomain(), externalPointEdgePoint::enterDomain(), plane::flip(), wallPoint::origin(), plane::origin(), plane::planeIntersect(), cylindrical::R(), plane::refPoint(), plane::sideOfPlane(), patchEdgeFaceInfo::transform(), sweepData::transform(), wallPoint::transform(), pointEdgePoint::transform(), externalPointEdgePoint::transform(), refinementDistanceData::transform(), and patchEdgeFaceInfo::updateEdge().
axis_ (ptf. axis_)
axialVelocity_ (ptf.axialVelocity_. clone())
radialVelocity_ (ptf.radialVelocity_. clone())