OpenFOAM: src/thermophysicalModels/reactionThermo/mixtures/egrMixture/egrMixture.C File Reference
egrMixture.C File Reference
Functions
stoicRatio_ ("stoichiometricAirFuelMassRatio", dimless, thermoDict)
fuel_ (thermoDict.subDict("fuel"))
oxidant_ (thermoDict.subDict("oxidant"))
products_ (thermoDict.subDict("burntProducts"))
mixture_ ("mixture", fuel_)
ft_ (Y("ft"))
b_ (Y("b"))
Variables
mesh
phaseName
Detailed Description
Original source file egrMixture.C
Definition in file egrMixture.C.
Function Documentation
stoicRatio_ ("stoichiometricAirFuelMassRatio" , dimless , thermoDict)
Referenced by singleStepReactingMixture< ThermoType >::s().
fuel_ (thermoDict. subDict"fuel")
oxidant_ (thermoDict. subDict"oxidant")
products_ (thermoDict. subDict"burntProducts")
mixture_ ("mixture" , fuel_)
ft_ (Y("ft"))
Referenced by FSD< ReactionThermo, ThermoType >::FSD().
b_ (Y("b"))
Referenced by triangle< Point, PointRef >::areaNormal(), STLtriangle::c(), tetrahedron< Point, PointRef >::c(), triangle< Point, PointRef >::c(), NonSphereDragForce< CloudType >::CdRe(), tetrahedron< Point, PointRef >::centre(), tetrahedron< Point, PointRef >::circumCentre(), tetrahedron< Point, PointRef >::containmentSphere(), line< Point, PointRef >::last(), line< Point, PointRef >::mag(), tetrahedron< Point, PointRef >::mag(), tetrahedron< Point, PointRef >::pointToBarycentric(), triangle< Point, PointRef >::pointToBarycentric(), tetrahedron< Point, PointRef >::Sb(), tetrahedron< Point, PointRef >::Sd(), line< Point, PointRef >::start(), triangle< Point, PointRef >::unitNormal(), line< Point, PointRef >::unitVec(), and SRIFallOffFunction::write().
Variable Documentation
mesh
Definition at line 37 of file egrMixture.C.
phaseName
Definition at line 37 of file egrMixture.C.
Referenced by solidReactionThermo::New(), psiuReactionThermo::New(), psiReactionThermo::New(), rhoReactionThermo::New(), phaseModel::New(), fluidThermo::New(), solidThermo::New(), psiThermo::New(), rhoThermo::New(), basicThermo::~basicThermo(), fluidThermo::~fluidThermo(), psiReactionThermo::~psiReactionThermo(), psiThermo::~psiThermo(), psiuReactionThermo::~psiuReactionThermo(), rhoReactionThermo::~rhoReactionThermo(), rhoThermo::~rhoThermo(), solidReactionThermo::~solidReactionThermo(), and solidThermo::~solidThermo().