OpenFOAM: src/thermophysicalModels/specie/thermo/thermo/EtoHthermo.H File Reference
EtoHthermo.H File Reference
Functions
scalar Cp (const scalar p, const scalar T) const
scalar Hs (const scalar p, const scalar T) const
scalar Ha (const scalar p, const scalar T) const
Function Documentation
scalar Cp (const scalar p, const scalar T) const inline
Definition at line 2 of file EtoHthermo.H.
References Cv.
scalar Hs (const scalar p, const scalar T) const inline
Definition at line 17 of file EtoHthermo.H.
References Es(), and rho.
Referenced by Es(), thermo< Thermo, Type >::hc(), hConstThermo< EquationOfState >::Hs(), hRefConstThermo< EquationOfState >::Hs(), and hPowerThermo< EquationOfState >::Hs().
scalar Ha (const scalar p, const scalar T) const inline
Definition at line 32 of file EtoHthermo.H.
References Ea(), and rho.
Referenced by thermo< Thermo, Type >::A(), Ea(), janafThermo< EquationOfState >::Hc(), hPolynomialThermo< EquationOfState, PolySize >::Hc(), and thermo< Thermo, Type >::hs().