OpenFOAM: applications/utilities/postProcessing/dataConversion/foamToGMV/gmvOutputSpray.H File Reference
gmvOutputSpray.H File Reference
Functions
forAll (s, n)
Variables
gmvFile<< "tracers "
<< particles.size()<< nl;for(const
passiveParticle &p:particles){gmvFile
<< p.position().x()
<< " ";}gmvFile<< nl;for(const
passiveParticle &p:particles){gmvFile
<< p.position().y()
<< " ";}gmvFile<< nl;for(const
passiveParticle &p:particles){gmvFile
<< p.position().z()
<< " ";}gmvFile<< nl;forAll(lagrangianScalarNames,
i){word name=lagrangianScalarNames[i];IOField
< scalar > s (IOobject(name, runTime.timeName(), cloud::prefix, mesh, IOobject::MUST_READ, IOobject::NO_WRITE))
Function Documentation
forAll (s , n)
Definition at line 41 of file gmvOutputSpray.H.
References n, and s.
Variable Documentation
gmvFile<< "tracers " << particles.size() << nl;for (const passiveParticle& p : particles){ gmvFile << p.position().x() << " ";}gmvFile << nl;for (const passiveParticle& p : particles){ gmvFile << p.position().y() << " ";}gmvFile << nl;for (const passiveParticle& p : particles){ gmvFile << p.position().z() << " ";}gmvFile << nl;forAll(lagrangianScalarNames, i){ word name = lagrangianScalarNames[i]; IOField<scalar> s(IOobject(name,runTime.timeName(),cloud::prefix,mesh,IOobject::MUST_READ,IOobject::NO_WRITE))
Definition at line 25 of file gmvOutputSpray.H.
Referenced by barycentric01(), barycentric2D01(), Foam::csign(), particle< Type >::currentTetIndices(), diaedg(), VectorSpaceOps< N, I >::eqOpS(), forAll(), Foam::stringOps::inplaceLower(), Foam::stringOps::inplaceRemoveComments(), Foam::stringOps::inplaceUpper(), isoSurfaceTopo::interpolate(), dynamicOversetFvMesh::interpolate(), Foam::colourTools::interpolateDiverging(), triangleFuncs::intersectAxesBundle(), Foam::invTransform(), keyType::keyType(), memorybuf::in::list(), triFace::mag(), face::mag(), Foam::minMod(), KinematicParcel< ParcelType >::move(), line< Point, PointRef >::nearestDist(), surfaceFeatures::nearestEdges(), surfaceFeatures::nearestSamples(), Foam::neg0(), pyrolysisChemistryModel< CompType, SolidThermo, GasThermo >::omega(), minMaxMagEqOp< T >::operator()(), complex::operator*=(), Matrix< Form, Type >::operator*=(), Foam::operator+(), complex::operator+=(), complex::operator-=(), Matrix< Form, Type >::operator-=(), septernion::operator/=(), SubField< Type >::operator/=(), complex::operator/=(), VectorSpace< Form, Cmpt, Ncmpts >::operator/=(), quaternion::operator/=(), faePatchField< Type >::operator/=(), fvsPatchField< Type >::operator/=(), dimensioned< Type >::operator/=(), faPatchField< Type >::operator/=(), Matrix< Form, Type >::operator/=(), fvPatchField< Type >::operator/=(), quaternion::operator=(), token::operator=(), complex::operator==(), faePatchField< Type >::operator==(), fvsPatchField< Type >::operator==(), faPatchField< Type >::operator==(), fvPatchField< Type >::operator==(), Foam::operator>>(), Pair< T >::Pair(), scalarRanges::parse(), Foam::posPart(), Foam::pow(), Foam::pow025(), Foam::pow5(), Foam::pow6(), Foam::blockMeshTools::read(), DAC< CompType, ThermoType >::reduceMechanism(), DRGEP< CompType, ThermoType >::reduceMechanism(), Foam::rotationTensor(), Foam::Rx(), Foam::Ry(), s_len_trim(), Foam::ScalarRead(), Foam::stabilise(), SVD::SVD(), swapec(), timestring(), Foam::transform(), cyclicPolyPatch::transformPosition(), triangulation_print(), and cellVolumeWeight::update().