OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/fluid/pEqn.H File Reference
pEqn.H File Reference
Functions
const volScalarField psip0 (psi *p)
volScalarField rAU ("rAU", 1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA",(fvc::flux(rho *HbyA)+MRF.zeroFilter(rhorAUf *fvc::ddtCorr(rho, U, phi)))+phig)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
for (int nonOrth=0;nonOrth<=nNonOrthCorr;nonOrth++)
pressureControl limit (p)
if (closedVolume)
Variables
bool closedVolume = p_rgh.needReference()
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
rho = thermo.rho()
p = p_rgh + rho*gh
else
Function Documentation
const volScalarField psip0 (psi * p)
volScalarField rAU ("rAU" , 1.0/UEqn. A())
surfaceScalarField rhorAUf ("rhorAUf" , fvc:: interpolaterho *rAU)
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc:: snGradrho)*mesh.magSf()
surfaceScalarField phiHbyA ("phiHbyA" , (fvc::flux(rho *HbyA)+MRF.zeroFilter(rhorAUf *fvc::ddtCorr(rho, U, phi)))+ phig)
MRF makeRelative (fvc:: interpolaterho, phiHbyA)
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
for (int nonOrth = 0; nonOrth<=nNonOrthCorr; nonOrth++)
Definition at line 39 of file pEqn.H.
References fvOptions, Foam::getRefCellValue(), HbyA, Foam::fac::laplacian(), Foam::magSqr(), mesh, nCorr, nNonOrthCorr, nOuterCorr, p_rgh, p_rghDDtEqn(), p_rghEqn, phi, phig(), phiHbyA, pRefCell, pRefValue, rAU, Foam::fvc::reconstruct(), rhorAUf(), and U.
pressureControl limit (p)
if (closedVolume)
Definition at line 90 of file pEqn.H.
References Foam::fvc::domainIntegrate(), Foam::getRefCellValue(), gh, initialMass, p, p_rgh, pRefCell, pRefValue, psi, psip0(), rho, rhoMax, rhoMin, and thermo.
Variable Documentation
bool closedVolume = p_rgh.needReference()
Definition at line 1 of file pEqn.H.
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 2 of file pEqn.H.
bool compressible = (compressibility.value() > SMALL)
Definition at line 3 of file pEqn.H.
rho = thermo.rho()
Definition at line 5 of file pEqn.H.
p = p_rgh + rho*gh
Definition at line 82 of file pEqn.H.
else
Initial value:
{
    thermo.correctRho(psi*p - psip0,  rhoMin, rhoMax)
Definition at line 112 of file pEqn.H.