OpenFOAM: applications/solvers/heatTransfer/chtMultiRegionFoam/chtMultiRegionSimpleFoam/fluid/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
tUEqn clear ()
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(rho *HbyA))
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
for (int nonOrth=0;nonOrth<=nNonOrthCorr;nonOrth++)
if (closedVolume)
rho relax ()
Variables
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
phiHbyA = phig
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
p = p_rgh + rho*gh
rho = thermo.rho()
Function Documentation
surfaceScalarField rhorAUf ("rhorAUf" , fvc:: interpolaterho *rAU)
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
tUEqn clear ()
surfaceScalarField phig (-rhorAUf *ghf *fvc:: snGradrho)*mesh.magSf()
surfaceScalarField phiHbyA ("phiHbyA" , fvc:: fluxrho *HbyA)
MRF makeRelative (fvc:: interpolaterho, phiHbyA)
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
for (int nonOrth = 0; nonOrth<=nNonOrthCorr; nonOrth++)
Definition at line 28 of file pEqn.H.
References Foam::fac::div(), fvOptions, Foam::getRefCellValue(), HbyA, Foam::fac::laplacian(), nNonOrthCorr, p_rgh, p_rghEqn, phi, phig(), phiHbyA, pRefCell, rAU, Foam::fvc::reconstruct(), rhorAUf(), and U.
if (closedVolume)
Definition at line 61 of file pEqn.H.
References Foam::fvc::domainIntegrate(), Foam::getRefCellValue(), gh, initialMass, p, p_rgh, pRefCell, pRefValue, psi, and rho.
rho relax ()
Variable Documentation
bool closedVolume = adjustPhi(phiHbyA, U, p_rgh)
Definition at line 17 of file pEqn.H.
phiHbyA = phig
Definition at line 19 of file pEqn.H.
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 24 of file pEqn.H.
bool compressible = (compressibility.value() > SMALL)
Definition at line 25 of file pEqn.H.
p = p_rgh + rho*gh
Definition at line 55 of file pEqn.H.
rho = thermo.rho()
Definition at line 80 of file pEqn.H.