OpenFOAM: applications/solvers/heatTransfer/buoyantPimpleFoam/overBuoyantPimpleDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
const volScalarField psip0 (psi *p)
volScalarField rAU (1.0/UEqn.A())
mesh interpolate (rAU)
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(rho *HbyA)+phig)
if (ddtCorr)
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
constrainPressure (p_rgh, rho, U, phiHbyA, rhorAUf, MRF)
fvScalarMatrix p_rghDDtEqn (fvc::ddt(rho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA)==)
p_rghEqn solve (mesh.solver(p_rgh.select(pimple.finalInnerIter())))
p_rgh relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceScalarField faceMask (localMin< scalar >(mesh).interpolate(cellMask))
Variables
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
bool compressible = (compressibility.value() > SMALL)
rho = thermo.rho()
U
K = 0.5*magSqr(U)
p = p_rgh + rho*gh
Function Documentation
const volScalarField psip0 (psi * p)
volScalarField rAU (1.0/UEqn. A())
mesh interpolate (rAU)
surfaceScalarField rhorAUf ("rhorAUf" , fvc:: interpolaterho *rAU)
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p_rgh))
surfaceScalarField phig (-rhorAUf *ghf *fvc:: snGradrho)*mesh.magSf()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(rho *HbyA)+ phig)
if (ddtCorr)
Definition at line 25 of file pEqn.H.
References ddtCorr, Foam::fac::interpolate(), mesh, MRF, phi, phiHbyA, rho, rhorAUf(), and U.
MRF makeRelative (fvc:: interpolaterho, phiHbyA)
constrainPressure (p_rgh , rho , U , phiHbyA , rhorAUf , MRF)
fvScalarMatrix p_rghDDtEqn (fvc:: ddtrho)+psi *correction(fvm::ddt(p_rgh))+fvc::div(phiHbyA = =)
p_rghEqn solve (mesh. solverp_rgh.select(pimple.finalInnerIter()))
p_rgh relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceScalarField faceMask (localMin< scalar > mesh).interpolate(cellMask)
Variable Documentation
dimensionedScalar compressibility = fvc::domainIntegrate(psi)
Definition at line 2 of file pEqn.H.
bool compressible = (compressibility.value() > SMALL)
Definition at line 3 of file pEqn.H.
Referenced by alphatWallFunctionFvPatchScalarField::alphatWallFunctionFvPatchScalarField(), Foam::compressible::New(), and thermalBaffleFvPatchScalarField::thermalBaffleFvPatchScalarField().
rho = thermo.rho()
Definition at line 5 of file pEqn.H.
U
Initial value:
=
            cellMask*
            (
                HbyA + rAU*fvc::reconstruct((phig + p_rghEqn.flux())/rhorAUf)
            )
Definition at line 69 of file pEqn.H.
K = 0.5*magSqr(U)
Definition at line 76 of file pEqn.H.
p = p_rgh + rho*gh
Definition at line 80 of file pEqn.H.