OpenFOAM: applications/solvers/incompressible/pimpleFoam/overPimpleDyMFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU ("rAU", 1.0/UEqn.A())
mesh interpolate (rAU)
surfaceScalarField rAUf ("rAUf", fvc::interpolate(rAU))
volVectorField H ("H", UEqn.H())
volVectorField HbyA ("HbyA", U)
if (massFluxInterpolation)
rAU write ()
if (ddtCorr)
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA, U, p)
if (adjustFringe)
pEqn setReference (pRefCell, pRefValue)
pEqn solve (mesh.solver(p.select(pimple.finalInnerIter())))
p relax ()
volVectorField gradP (fvc::grad(p))
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceVectorField n (mesh.Sf()/mesh.magSf())
surfaceScalarField faceMask (localMin< scalar >(mesh).interpolate(cellMask))
Variables
HbyA = constrainHbyA(rAU*H, U, p)
phiHbyA = fvc::flux(HbyA)
U = cellMask*(HbyA - rAU*gradP)
Uf = n*(phi/mesh.magSf() - (n & Uf))
Function Documentation
volScalarField rAU ("rAU" , 1.0/UEqn. A())
mesh interpolate (rAU)
surfaceScalarField rAUf ("rAUf" , fvc:: interpolaterAU)
volVectorField H ("H" , UEqn. H())
volVectorField HbyA ("HbyA" , U)
if (massFluxInterpolation)
Definition at line 22 of file pEqn.H.
rAU write ()
if (ddtCorr)
Definition at line 41 of file pEqn.H.
References ddtCorr, Foam::fac::interpolate(), mesh, phiHbyA, rAUf, U, and Uf.
MRF makeRelative (phiHbyA)
adjustPhi (phiHbyA , U , p)
if (adjustFringe)
Definition at line 61 of file pEqn.H.
References makeAbsolute(), Foam::fvc::makeRelative(), Foam::oversetAdjustPhi(), phiHbyA, and U.
pEqn setReference (pRefCell , pRefValue)
pEqn solve (mesh. solverp.select(pimple.finalInnerIter()))
p relax ()
volVectorField gradP (fvc:: gradp)
U correctBoundaryConditions ()
fvOptions correct (U)
surfaceVectorField n (mesh. Sf)/mesh.magSf()
surfaceScalarField faceMask (localMin< scalar > mesh).interpolate(cellMask)
Variable Documentation
HbyA = constrainHbyA(rAU*H, U, p)
Definition at line 20 of file pEqn.H.
phiHbyA = fvc::flux(HbyA)
Definition at line 39 of file pEqn.H.
U = cellMask*(HbyA - rAU*gradP)
Definition at line 99 of file pEqn.H.
Uf = n*(phi/mesh.magSf() - (n & Uf))
Definition at line 107 of file pEqn.H.