OpenFOAM: applications/solvers/multiphase/interFoam/interMixingFoam/alphaEqn.H File Reference
alphaEqn.H File Reference
Functions
word alpharScheme ("div(phirb,alpha)")
surfaceScalarField phir (IOobject("phir", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mixture.cAlpha()*mag(phi/mesh.magSf())*mixture.nHatf())
for (int gCorr=0;gCorr< nAlphaCorr;gCorr++)
Function Documentation
word alpharScheme ("div(phirb,alpha)")
surfaceScalarField phir (IOobject("phir", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mixture. cAlpha)*mag(phi/mesh.magSf())*mixture.nHatf()
for ()
Definition at line 18 of file alphaEqn.H.
References alpha1, alpha2, alphaPhi1, alphaPhi2, alpharScheme(), Foam::fac::ddt(), Foam::dimless, Foam::fac::div(), Foam::fvc::flux(), Foam::fac::interpolate(), lambda(), Foam::fac::laplacian(), Foam::limiter(), LTS, Foam::max(), mesh, phi, phir(), Foam::pos0(), rho1, rho2, rhoPhi, runTime, Foam::fvc::snGrad(), solve(), and Foam::vtk::Tools::zeroField().