OpenFOAM: applications/solvers/incompressible/pimpleFoam/overPimpleDyMFoam/interpolatedFaces.H File Reference
interpolatedFaces.H File Reference
Functions
interpolationCellPoint< vector > UInterpolator (HbyA)
bitSet isOwnerInterpolatedFace (mesh.nInternalFaces())
bitSet isNeiInterpolatedFace (mesh.nInternalFaces())
labelListList donorCell (mesh.nInternalFaces())
scalarListList weightCellCells (mesh.nInternalFaces())
vectorField UIntFaces (mesh.nInternalFaces(), Zero)
labelList receptorNeigCell (mesh.nInternalFaces(),-1)
PtrList< fvMeshSubset > meshParts (nZones)
labelList nCellsPerZone (nZones, Zero)
forAll (meshParts, zonei)
if (ownType==cellCellStencil::INTERPOLATED &&neiType==cellCellStencil::CALCULATED)
vectorField U1Contrav (mesh.nInternalFaces(), Zero)
surfaceVectorField faceNormals (mesh.Sf()/mesh.magSf())
forAll (isNeiInterpolatedFace, faceI)
Variables
const labelList & cellTypes = overlap.cellTypes()
const labelIOList & zoneID = overlap.zoneID()
label nZones = gMax(zoneID)+1
label neiType = cellTypes[mesh.faceNeighbour()[faceI]]
Function Documentation
interpolationCellPoint<vector> UInterpolator (HbyA)
Referenced by if().
bitSet isOwnerInterpolatedFace (mesh. nInternalFaces())
Referenced by forAll(), and if().
bitSet isNeiInterpolatedFace (mesh. nInternalFaces())
Referenced by forAll().
labelListList donorCell (mesh. nInternalFaces())
Referenced by if().
scalarListList weightCellCells (mesh. nInternalFaces())
Referenced by if().
vectorField UIntFaces (mesh. nInternalFaces(), Zero)
Referenced by forAll(), and if().
labelList receptorNeigCell (mesh. nInternalFaces(), - 1)
Referenced by forAll(), and if().
PtrList<fvMeshSubset> meshParts (nZones)
Referenced by forAll(), if(), and cellVolumeWeight::update().
labelList nCellsPerZone (nZones , Zero)
Referenced by cellVolumeWeight::update().
forAll (meshParts , zonei)
Definition at line 29 of file interpolatedFaces.H.
References mesh, and meshParts().
else if (ownType = = cellCellStencil::INTERPOLATED && neiType == cellCellStencil::CALCULATED)
Definition at line 44 of file interpolatedFaces.H.
References d, donorCell(), forAll, i, isOwnerInterpolatedFace(), labelList(), Foam::mag(), mesh, meshParts(), nZones, receptorNeigCell(), Foam::sum(), UInterpolator(), UIntFaces(), and weightCellCells().
vectorField U1Contrav (mesh. nInternalFaces(), Zero)
Referenced by forAll().
surfaceVectorField faceNormals (mesh. Sf)/mesh.magSf()
Referenced by PatchTools::edgeNormals(), forAll(), PatchTools::pointNormals(), and extendedEdgeMesh::sortPointsAndEdges().
forAll (isNeiInterpolatedFace , faceI)
Definition at line 180 of file interpolatedFaces.H.
References cellId, faceNormals(), HbyA, Foam::inv(), isNeiInterpolatedFace(), isOwnerInterpolatedFace(), Foam::mag(), mesh, n, Vector< Cmpt >::normalise(), Foam::normalised(), receptorNeigCell(), Foam::transform(), U1Contrav(), UIntFaces(), Y, and Foam::Zero.
Variable Documentation
const labelList& cellTypes = overlap.cellTypes()
Definition at line 21 of file interpolatedFaces.H.
const labelIOList& zoneID = overlap.zoneID()
Definition at line 22 of file interpolatedFaces.H.
Referenced by fvExprDriver::getTopoSetLabels(), Foam::oversetAdjustPhi(), polyTopoChange::removeCell(), combineFaces::setUnrefinement(), meshRefinement::subsetBaffles(), cellVolumeWeight::update(), and zoneMotion::zoneMotion().
label nZones = gMax(zoneID)+1
Definition at line 24 of file interpolatedFaces.H.
Referenced by if(), Foam::oversetAdjustPhi(), refinementParameters::refinementParameters(), cellVolumeWeight::update(), and meshRefinement::zonify().
label neiType = cellTypes[mesh.faceNeighbour()[faceI]]
Definition at line 42 of file interpolatedFaces.H.
Referenced by inverseDistance::findHoles(), Foam::oversetAdjustPhi(), and cellVolumeWeight::walkFront().