OpenFOAM: applications/solvers/multiphase/cavitatingFoam/pEqn.H File Reference
pEqn.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiGradp (rhorAUf *mesh.magSf()*fvc::snGrad(p))
pEqn solve (mesh.solver(p.select(pimple.finalInnerIter())))
p correctBoundaryConditions ()
Variables
phi
Info<< "Predicted p max-min : "
<< max(p).value()<< " "<< min(p).value()
<< endl;rho==max(psi *p+alphal
*rhol0+((alphav *psiv+alphal
*psil)-psi)*pSat, rhoMin);#1"/home/pengfei/OpenFOAM/OpenFOAM-v1912/applications/solvers/multiphase/cavitatingFoam/alphavPsi.H"1{alphav=max(min((rho-rholSat)/(rhovSat-rholSat),),);alphal=1.0-alphav;Info
<< "max-min alphav: "<< max(alphav).value()
<< " "<< min(alphav).value()
<< endl;psiModel-> correct ()
p
Function Documentation
volScalarField rAU (1.0/UEqn. A())
surfaceScalarField rhorAUf ("rhorAUf" , fvc:: interpolaterho *rAU)
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiGradp (rhorAUf *mesh. magSf)*fvc::snGrad(p)
pEqn solve (mesh. solverp.select(pimple.finalInnerIter()))
p correctBoundaryConditions ()
Variable Documentation
phi
Initial value:
= fvc::flux(HbyA)
         + rhorAUf*fvc::ddtCorr(U, phi)
Definition at line 18 of file pEqn.H.
radiation correct ()
Initial value:
{
            phi += (phiGradp + pEqn.flux())/rhof
Definition at line 72 of file pEqn.H.
Referenced by Foam::MULES::correct(), Chung::correct(), Wallis::correct(), inversePointDistanceDiffusivity::correct(), inverseDistanceDiffusivity::correct(), patchPatchDist::correct(), exact::correct(), Poisson::correct(), polyMeshGeometry::correct(), advectionDiffusion::correct(), for(), if(), sampledSets::movePoints(), sampledSets::readUpdate(), directionalDiffusivity::~directionalDiffusivity(), inverseFaceDistanceDiffusivity::~inverseFaceDistanceDiffusivity(), inverseVolumeDiffusivity::~inverseVolumeDiffusivity(), and pointPatchDist::~pointPatchDist().
p
Initial value:
=
    (
        rho
      - alphal*rhol0
      - ((alphav*psiv + alphal*psil) - psi)*pSat
    )/psi
Definition at line 57 of file pEqn.H.