OpenFOAM: applications/solvers/multiphase/interCondensatingEvaporatingFoam/TEqn.H File Reference
TEqn.H File Reference
Functions
const surfaceScalarField rhoCpPhi (fvc::interpolate(cp)*rhoPhi)
const volScalarField vDotvmcAlphal (vDotvAlphal-vDotcAlphal)
fvScalarMatrix TEqn (fvm::ddt(rhoCp, T)+fvm::div(rhoCpPhi, T)-fvm::Sp(fvc::ddt(rhoCp)+fvc::div(rhoCpPhi), T)-fvm::laplacian(kappaEff, T)+thermo->hc()*vDotvmcAlphal)
TEqn relax ()
TEqn solve ()
Variables
const volScalarField & cp = tcp()
rhoCp = rho*cp
kappaEff = thermo->kappa() + rho*cp*turbulence->nut()/Prt
Pair< tmp< volScalarField > > vDotAlphal = mixture->mDot()
const volScalarField & vDotcAlphal = vDotAlphal[0]()
const volScalarField & vDotvAlphal = vDotAlphal[1]()
Function Documentation
const surfaceScalarField rhoCpPhi (fvc::interpolate(cp)* rhoPhi)
const volScalarField vDotvmcAlphal (vDotvAlphal- vDotcAlphal)
Referenced by for(), and if().
fvScalarMatrix TEqn (fvm::ddt(rhoCp, T)+fvm::div(rhoCpPhi, T)-fvm::Sp(fvc::ddt(rhoCp)+fvc::div(rhoCpPhi), T)-fvm::laplacian(kappaEff, T)+thermo->hc()* vDotvmcAlphal)
TEqn relax ()
TEqn solve ()
Variable Documentation
const volScalarField& cp = tcp()
Definition at line 3 of file TEqn.H.
rhoCp = rho*cp
Definition at line 5 of file TEqn.H.
kappaEff = thermo->kappa() + rho*cp*turbulence->nut()/Prt
Definition at line 7 of file TEqn.H.
Pair<tmp<volScalarField> > vDotAlphal = mixture->mDot()
Definition at line 11 of file TEqn.H.
const volScalarField& vDotcAlphal = vDotAlphal[0]()
Definition at line 13 of file TEqn.H.
Referenced by for().
const volScalarField& vDotvAlphal = vDotAlphal[1]()
Definition at line 14 of file TEqn.H.