OpenFOAM: applications/solvers/multiphase/twoPhaseEulerFoam/pUf/pEqn.H File Reference
pEqn.H File Reference
Functions
surfaceScalarField alphaf1 ("alphaf1", fvc::interpolate(alpha1))
surfaceScalarField alphaf2 ("alphaf2", scalar(1)-alphaf1)
surfaceScalarField alphaRhof10 ("alphaRhof10", fvc::interpolate(max(alpha1.oldTime(), phase1.residualAlpha())*rho1.oldTime()))
surfaceScalarField alphaRhof20 ("alphaRhof20", fvc::interpolate(max(alpha2.oldTime(), phase2.residualAlpha())*rho2.oldTime()))
surfaceScalarField Kdf ("Kdf", fluid.Kdf())
surfaceScalarField Vmf ("Vmf", fluid.Vmf())
surfaceScalarField rAUf1 (IOobject::groupName("rAUf", phase1.name()), 1.0/((alphaRhof10+Vmf)/runTime.deltaT()+fvc::interpolate(U1Eqn.A())+Kdf))
surfaceScalarField rAUf2 (IOobject::groupName("rAUf", phase2.name()), 1.0/((alphaRhof20+Vmf)/runTime.deltaT()+fvc::interpolate(U2Eqn.A())+Kdf))
surfaceScalarField Df1 (fvc::interpolate(D+phase1.turbulence().pPrime()))
surfaceScalarField Df2 (fvc::interpolate(D+phase2.turbulence().pPrime()))
if (implicitPhasePressure)
surfaceScalarField Ff (fluid.Ff())
surfaceScalarField snGradAlpha1 (fvc::snGrad(alpha1)*mesh.magSf())
surfaceScalarField rhof1 (fvc::interpolate(rho1))
surfaceScalarField rhof2 (fvc::interpolate(rho2))
MRF correctBoundaryFlux (U1, phi1)
MRF correctBoundaryFlux (U2, phi2)
surfaceScalarField alpharAUf1 (IOobject::groupName("alpharAUf", phase1.name()), max(alphaf1, phase1.residualAlpha())*rAUf1)
surfaceScalarField alpharAUf2 (IOobject::groupName("alpharAUf", phase2.name()), max(alphaf2, phase2.residualAlpha())*rAUf2)
surfaceScalarField ghSnGradRho ("ghSnGradRho", ghf *fvc::snGrad(rho)*mesh.magSf())
surfaceScalarField phig1 (IOobject::groupName("phig", phase1.name()), alpharAUf1 *(ghSnGradRho-alphaf2 *(rhof1-rhof2)*(g &mesh.Sf())))
surfaceScalarField phig2 (IOobject::groupName("phig", phase2.name()), alpharAUf2 *(ghSnGradRho-alphaf1 *(rhof2-rhof1)*(g &mesh.Sf())))
surfaceScalarField phiHbyA1 (IOobject::groupName("phiHbyA", phase1.name()), phi1)
surfaceScalarField phiHbyA2 (IOobject::groupName("phiHbyA", phase2.name()), phi2)
surfaceScalarField phiHbyA ("phiHbyA", alphaf1 *(phiHbyA1-phig1)+alphaf2 *(phiHbyA2-phig2))
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf ("rAUf",)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryFieldRef(),(phiHbyA.boundaryField()-(alphaf1.boundaryField()*phi1.boundaryField()+alphaf2.boundaryField()*phi2.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 (IOobject::groupName("phid", phase2.name()), fvc::interpolate(psi2)*phi2)
pEqnComp1 ref ().relax()
volScalarField p_rgh_0 ("p_rgh_0", p_rgh)
solve (pEqnComp1()+pEqnComp2()+pEqnIncomp, mesh.solver(p_rgh.select(pimple.finalInnerIter())))
surfaceScalarField phi1s (phiHbyA1+alpharAUf1 *mSfGradp-rAUf1 *Kdf *MRF.absolute(phi2))
surfaceScalarField phi2s (phiHbyA2+alpharAUf2 *mSfGradp-rAUf2 *Kdf *MRF.absolute(phi1))
surfaceScalarField phir (((phi2s+rAUf2 *Kdf *phi1s)-(phi1s+rAUf1 *Kdf *phi2s))/(1.0-rAUf1 *rAUf2 *sqr(Kdf)))
U1 correctBoundaryConditions ()
fvOptions correct (U1)
fvOptions correct (U2)
fluid dgdt ()
if (thermo1.dpdt()||thermo2.dpdt())
Variables
tmp< surfaceScalarField > Ff1 = Df1*snGradAlpha1 + Ff
tmp< surfaceScalarField > Ff2 = -Df2*snGradAlpha1 - Ff
p_rgh = p - rho*gh
phiHbyA1
phiHbyA2
tmp< fvScalarMatrix > pEqnComp1
tmp< fvScalarMatrix > pEqnComp2
else
phi = phiHbyA + pEqnIncomp.flux()
phi1 = phi - alphaf2*phir
phi2 = phi + alphaf1*phir
U1 = fvc::reconstruct(MRF.absolute(phi1))
U2 = fvc::reconstruct(MRF.absolute(phi2))
U = fluid.U()
p = max(p_rgh + rho*gh, pMin)
rho1 = psi1*(p_rgh - p_rgh_0)
rho2 = psi2*(p_rgh - p_rgh_0)
rho = fluid.rho()
K1 = 0.5*magSqr(U1)
K2 = 0.5*magSqr(U2)
Function Documentation
surfaceScalarField alphaf1 ("alphaf1" , fvc:: interpolatealpha1)
surfaceScalarField alphaf2 ("alphaf2" , scalar(1)- alphaf1)
surfaceScalarField alphaRhof10 ("alphaRhof10" , fvc:: interpolatemax(alpha1.oldTime(), phase1.residualAlpha())*rho1.oldTime())
surfaceScalarField alphaRhof20 ("alphaRhof20" , fvc:: interpolatemax(alpha2.oldTime(), phase2.residualAlpha())*rho2.oldTime())
surfaceScalarField Kdf ("Kdf" , fluid. Kdf())
surfaceScalarField Vmf ("Vmf" , fluid. Vmf())
surfaceScalarField rAUf1 (IOobject:: groupName"rAUf", phase1.name(), 1.0/ (alphaRhof10+Vmf)/runTime.deltaT()+fvc::interpolate(U1Eqn.A())+Kdf)
surfaceScalarField rAUf2 (IOobject:: groupName"rAUf", phase2.name(), 1.0/ (alphaRhof20+Vmf)/runTime.deltaT()+fvc::interpolate(U2Eqn.A())+Kdf)
surfaceScalarField Df1 (fvc:: interpolateD+phase1.turbulence().pPrime())
surfaceScalarField Df2 (fvc:: interpolateD+phase2.turbulence().pPrime())
if (implicitPhasePressure)
Definition at line 74 of file pEqn.H.
References Df2(), fluid, rAUf1, and rAUf2.
surfaceScalarField Ff (fluid. Ff())
Referenced by BlendedInterfacialModel< ModelType >::D().
surfaceScalarField snGradAlpha1 (fvc:: snGradalpha1)*mesh.magSf()
surfaceScalarField rhof1 (fvc:: interpolaterho1)
surfaceScalarField rhof2 (fvc:: interpolaterho2)
MRF correctBoundaryFlux (U1 , phi1)
MRF correctBoundaryFlux (U2 , phi2)
surfaceScalarField alpharAUf1 (IOobject:: groupName"alpharAUf", phase1.name(), max(alphaf1, phase1.residualAlpha())* rAUf1)
surfaceScalarField alpharAUf2 (IOobject:: groupName"alpharAUf", phase2.name(), max(alphaf2, phase2.residualAlpha())* rAUf2)
surfaceScalarField ghSnGradRho ("ghSnGradRho" , ghf *fvc:: snGradrho)*mesh.magSf()
surfaceScalarField phig1 (IOobject:: groupName"phig", phase1.name(), alpharAUf1 * ghSnGradRho-alphaf2 *(rhof1-rhof2)*(g &mesh.Sf()))
surfaceScalarField phig2 (IOobject:: groupName"phig", phase2.name(), alpharAUf2 * ghSnGradRho-alphaf1 *(rhof2-rhof1)*(g &mesh.Sf()))
surfaceScalarField phiHbyA1 (IOobject:: groupName"phiHbyA", phase1.name(), phi1)
surfaceScalarField phiHbyA2 (IOobject:: groupName"phiHbyA", phase2.name(), phi2)
surfaceScalarField phiHbyA ("phiHbyA" , alphaf1 * phiHbyA1-phig1)+alphaf2 *(phiHbyA2-phig2)
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf ("rAUf")
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryFieldRef(), (phiHbyA.boundaryField()-(alphaf1.boundaryField()*phi1.boundaryField()+alphaf2.boundaryField()*phi2.boundaryField()))/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
surfaceScalarField phid2 (IOobject:: groupName"phid", phase2.name(), fvc::interpolate(psi2)* phi2)
pEqnComp1 ref ()
volScalarField p_rgh_0 ("p_rgh_0" , p_rgh)
solve (pEqnComp1()+pEqnComp2()+ pEqnIncomp, mesh. solverp_rgh.select(pimple.finalInnerIter()))
surfaceScalarField phi1s (phiHbyA1+alpharAUf1 *mSfGradp-rAUf1 *Kdf *MRF. absolutephi2)
surfaceScalarField phi2s (phiHbyA2+alpharAUf2 *mSfGradp-rAUf2 *Kdf *MRF. absolutephi1)
surfaceScalarField phir (((phi2s+rAUf2 *Kdf *phi1s)-(phi1s+rAUf1 *Kdf *phi2s))/(1.0-rAUf1 *rAUf2 *sqr(Kdf)))
U1 correctBoundaryConditions ()
fvOptions correct (U1)
fvOptions correct (U2)
fluid dgdt ()
if (thermo1. dpdt)||thermo2.dpdt()
Definition at line 365 of file pEqn.H.
References Foam::fac::ddt(), dpdt, and p.
Variable Documentation
Ff1 = Df1*snGradAlpha1 + Ff
Definition at line 54 of file pEqn.H.
Ff2 = -Df2*snGradAlpha1 - Ff
Definition at line 55 of file pEqn.H.
p_rgh = p - rho*gh
Definition at line 101 of file pEqn.H.
phiHbyA1
Initial value:
=
        rAUf1
       *(
            (alphaRhof10 + Vmf)
           *MRF.absolute(phi1.oldTime())/runTime.deltaT()
          + fvc::flux(U1Eqn.H())
          + Vmf*ddtPhi2
          + Kdf*MRF.absolute(phi2)
          - Ff1()
        )
Definition at line 158 of file pEqn.H.
phiHbyA2
Initial value:
=
        rAUf2
       *(
            (alphaRhof20 + Vmf)
           *MRF.absolute(phi2.oldTime())/runTime.deltaT()
          + fvc::flux(U2Eqn.H())
          + Vmf*ddtPhi1
          + Kdf*MRF.absolute(phi1)
          - Ff2()
       )
Definition at line 176 of file pEqn.H.
pEqnComp1
Initial value:
=
            (
                contErr1
              - fvc::Sp(fvc::ddt(alpha1) + fvc::div(alphaPhi1), rho1)
            )/rho1
          + correction
            (
                (alpha1/rho1)*
                (
                    psi1*fvm::ddt(p_rgh)
                  + fvm::div(phid1, p_rgh) - fvm::Sp(fvc::div(phid1), p_rgh)
                )
            )
Definition at line 217 of file pEqn.H.
pEqnComp2
Initial value:
=
            (
                contErr2
              - fvc::Sp(fvc::ddt(alpha2) + fvc::div(alphaPhi2), rho2)
            )/rho2
          + correction
            (
                (alpha2/rho2)*
                (
                    psi2*fvm::ddt(p_rgh)
                  + fvm::div(phid2, p_rgh) - fvm::Sp(fvc::div(phid2), p_rgh)
                )
            )
Definition at line 218 of file pEqn.H.
else
Initial value:
{
        pEqnComp1 =
            (
                contErr1
              - fvc::Sp(fvc::ddt(alpha1) + fvc::div(alphaPhi1), rho1)
            )/rho1
          + (alpha1*psi1/rho1)*correction(fvm::ddt(p_rgh))
Definition at line 264 of file pEqn.H.
phi = phiHbyA + pEqnIncomp.flux()
Definition at line 301 of file pEqn.H.
phi1 = phi - alphaf2*phir
Definition at line 323 of file pEqn.H.
phi2 = phi + alphaf1*phir
Definition at line 324 of file pEqn.H.
U1 = fvc::reconstruct(MRF.absolute(phi1))
Definition at line 326 of file pEqn.H.
U2 = fvc::reconstruct(MRF.absolute(phi2))
Definition at line 330 of file pEqn.H.
U = fluid.U()
Definition at line 334 of file pEqn.H.
p = max(p_rgh + rho*gh, pMin)
Definition at line 345 of file pEqn.H.
rho1 = psi1*(p_rgh - p_rgh_0)
Definition at line 351 of file pEqn.H.
rho2 = psi2*(p_rgh - p_rgh_0)
Definition at line 352 of file pEqn.H.
rho = fluid.rho()
Definition at line 355 of file pEqn.H.
K1 = 0.5*magSqr(U1)
Definition at line 361 of file pEqn.H.
K2 = 0.5*magSqr(U2)
Definition at line 362 of file pEqn.H.