OpenFOAM: applications/solvers/multiphase/reactingEulerFoam/reactingMultiphaseEulerFoam/pUf/pEqn.H File Reference
pEqn.H File Reference
Functions
PtrList< surfaceScalarField > alphafs (phases.size())
PtrList< surfaceScalarField > alphaRho0fs (phases.size())
forAll (phases, phasei)
PtrList< surfaceScalarField > rAUfs (phases.size())
rAUfs set (phase.index(), new surfaceScalarField(IOobject::groupName("rAUf", phase.name()), 1.0/(+fvc::interpolate(UEqns[phase.index()].A())+AFfs[phase.index()])))
fluid fillFields ("rAUf", dimTime/dimDensity, rAUfs)
PtrList< surfaceScalarField > alpharAUfs (phases.size())
PtrList< surfaceScalarField > phiFfs (fluid.phiFfs(rAUfs))
MRF correctBoundaryFlux (phase.U(), phase.phiRef())
PtrList< surfaceScalarField > phigFs (phases.size())
PtrList< surfaceScalarField > phiHbyAs (phases.size())
phiHbyAs set (phase.index(), new surfaceScalarField(IOobject::groupName("phiHbyA", phase.name()), rAUfs[phase.index()]*(fvc::flux(UEqns[phase.index()].H())+alphaRho0fs[phase.index()]*byDt(MRF.absolute(phase.phi()().oldTime())))-phigFs[phase.index()]))
fluid fillFields ("phiHbyA", dimForce/dimDensity/dimVelocity, phiHbyAs)
if (!partialElimination)
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
if (partialElimination)
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh), mesh,)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh.boundaryFieldRef(),(phiHbyA.boundaryField()-phib)/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
PtrList< fvScalarMatrix > pEqnComps (phases.size())
PtrList< volScalarField > dmdts (fluid.dmdts())
volScalarField p_rgh_0 (p_rgh)
solve (pEqn, mesh.solver(p_rgh.select(pimple.finalInnerIter())))
surfaceScalarField mSfGradp ("mSfGradp", pEqnIncomp.flux()/rAUf)
phase phiRef ()
if (pEqnComps.set(phase.index()))
p_rgh relax ()
phase URef ()
fvOptions correct (phase.URef())
p_rgh correctBoundaryConditions ()
Variables
p_rgh = p - rho*gh
rAUf = mag(rAUf)
phib = 0
mSfGradp = pEqnIncomp.flux()/rAUf
p = max(p_rgh + rho*gh, pMin)
rho = fluid.rho()
Function Documentation
PtrList<surfaceScalarField> alphafs (phases. size())
PtrList<surfaceScalarField> alphaRho0fs (phases. size())
Referenced by forAll().
forAll (phases , phasei)
Definition at line 4 of file pEqn.H.
References Foam::constant::atomic::alpha, alphafs(), alphaRho0fs(), Foam::fac::interpolate(), Foam::max(), Foam::name(), oldTime, phasei, and phases.
PtrList<surfaceScalarField> rAUfs (phases. size())
rAUfs set (phase. index(), new surfaceScalarFieldIOobject::groupName("rAUf", phase.name()), 1.0/(+fvc::interpolate(UEqns[phase.index()].A())+AFfs[phase.index()]))
fluid fillFields ("rAUf" , dimTime/ dimDensity, rAUfs)
PtrList<surfaceScalarField> alpharAUfs (phases. size())
PtrList<surfaceScalarField> phiFfs (fluid. phiFfsrAUfs)
MRF correctBoundaryFlux (phase. U(), phase. phiRef())
PtrList<surfaceScalarField> phigFs (phases. size())
PtrList<surfaceScalarField> phiHbyAs (phases. size())
phiHbyAs set (phase. index(), new surfaceScalarFieldIOobject::groupName("phiHbyA", phase.name()), rAUfs[phase.index()]*(fvc::flux(UEqns[phase.index()].H())+alphaRho0fs[phase.index()]*byDt(MRF.absolute(phase.phi()().oldTime())))-phigFs[phase.index()])
fluid fillFields ("phiHbyA" , dimForce/dimDensity/ dimVelocity, phiHbyAs)
if (! partialElimination)
Definition at line 143 of file pEqn.H.
References fluid, forAll, phasei, phases, phiHbyAs, phiKdPhifs(), and rAUfs.
surfaceScalarField phiHbyA (IOobject("phiHbyA", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
if (partialElimination)
Definition at line 177 of file pEqn.H.
References alphafs(), fluid, forAll, phasei, phases, phiHbyA, phiKdPhifs(), and rAUfs.
MRF makeRelative (phiHbyA)
surfaceScalarField rAUf (IOobject("rAUf", runTime.timeName(), mesh) , mesh)
setSnGrad< fixedFluxPressureFvPatchScalarField > (p_rgh. boundaryFieldRef(), (phiHbyA.boundaryField()-phib)/(mesh.magSf().boundaryField()*rAUf.boundaryField()))
PtrList<fvScalarMatrix> pEqnComps (phases. size())
PtrList<volScalarField> dmdts (fluid. dmdts())
volScalarField p_rgh_0 (p_rgh)
solve (pEqn , mesh. solverp_rgh.select(pimple.finalInnerIter()))
surfaceScalarField mSfGradp ("mSfGradp" , pEqnIncomp.flux()/ rAUf)
phase phiRef ()
if (pEqnComps. setphase.index())
Definition at line 384 of file pEqn.H.
References p_rgh, and pEqnComps().
p_rgh relax ()
phase URef ()
fvOptions correct (phase. URef())
p_rgh correctBoundaryConditions ()
Variable Documentation
p_rgh = p - rho*gh
Definition at line 76 of file pEqn.H.
rAUf = mag(rAUf)
Definition at line 210 of file pEqn.H.
phib = 0
Definition at line 215 of file pEqn.H.
mSfGradp = pEqnIncomp.flux()/rAUf
Definition at line 398 of file pEqn.H.
p = max(p_rgh + rho*gh, pMin)
Definition at line 412 of file pEqn.H.
rho = fluid.rho()
Definition at line 425 of file pEqn.H.