OpenFOAM: Foam::compressible Namespace Reference
Foam::compressible Namespace Reference
Namespaces
RASModels
Classes
class alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField
A simple alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField with a fixed volumetric phase-change mass flux.
class alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model for the Eulerian multiphase solvers.
class alphatPhaseChangeWallFunctionFvPatchScalarField
Abstract base-class for all alphatWallFunctions supporting phase-change.
class alphatWallBoilingWallFunctionFvPatchScalarField
A thermal wall function for simulation of boiling wall.
class thermalBaffleFvPatchScalarField
This boundary condition provides a coupled temperature condition between multiple mesh regions.
class convectiveHeatTransferFvPatchScalarField
This boundary condition provides a convective heat transfer coefficient condition.
class thermalBaffle1DFvPatchScalarField
This BC solves a steady 1D thermal baffle.
class turbulentTemperatureCoupledBaffleMixedFvPatchScalarField
Mixed boundary condition for temperature, to be used for heat-transfer on back-to-back baffles. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
class turbulentTemperatureRadCoupledMixedFvPatchScalarField
Mixed boundary condition for temperature and radiation heat transfer to be used for in multiregion cases. Optional thin thermal layer resistances can be specified through thicknessLayers and kappaLayers entries.
class alphatJayatillekeWallFunctionFvPatchScalarField
This boundary condition provides a thermal wall function for turbulent thermal diffusivity (usuallyalphat) based on the Jayatilleke model.
class alphatWallFunctionFvPatchScalarField
This boundary condition provides a turbulent thermal diffusivity conditon when using wall functions.
class turbulentTemperatureTwoPhaseRadCoupledMixedFvPatchScalarField
Mixed boundary condition for temperature and radiation heat transfer to be used for in multiregion cases with two phase Euler system.
class humidityTemperatureCoupledMixedFvPatchScalarField
Mixed boundary condition for temperature to be used at the coupling interface between fluid solid regions.
Typedefs
typedef
thermalBaffle1DFvPatchScalarField
< hConstSolidThermoPhysics > constSolid_thermalBaffle1DFvPatchScalarField
typedef
thermalBaffle1DFvPatchScalarField
< hPowerSolidThermoPhysics > expoSolid_thermalBaffle1DFvPatchScalarField
typedef ThermalDiffusivity
< CompressibleTurbulenceModel
< fluidThermo > > turbulenceModel
typedef laminarModel
< turbulenceModel > laminarModel
typedef RASModel
< EddyDiffusivity
< turbulenceModel > > RASModel
typedef LESModel
< EddyDiffusivity
< turbulenceModel > > LESModel
Typedefs for turbulence, RAS and LES models for compressible flow based on the standard laminar transport package.
Functions
makePatchTypeField (fvPatchScalarField, alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField)
defineTypeNameAndDebug (alphatPhaseChangeWallFunctionFvPatchScalarField, 0)
makePatchTypeField (fvPatchScalarField, alphatWallBoilingWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, thermalBaffleFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, convectiveHeatTransferFvPatchScalarField)
refGrad ()
valueFraction ()
addToPatchFieldRunTimeSelection (fvPatchScalarField, constSolid_thermalBaffle1DFvPatchScalarField)
addToPatchFieldRunTimeSelection (fvPatchScalarField, expoSolid_thermalBaffle1DFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, turbulentTemperatureRadCoupledMixedFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatJayatillekeWallFunctionFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, alphatWallFunctionFvPatchScalarField)
template<class BasicCompressibleTurbulenceModel >
autoPtr
< BasicCompressibleTurbulenceModel > New (const volScalarField &rho, const volVectorField &U, const surfaceScalarField &phi, const typename BasicCompressibleTurbulenceModel::transportModel &transport, const word &propertiesName)
Variables
else
Typedef Documentation
typedef thermalBaffle1DFvPatchScalarField< hConstSolidThermoPhysics > constSolid_thermalBaffle1DFvPatchScalarField
Definition at line 39 of file thermalBaffle1DFvPatchScalarFields.H.
typedef thermalBaffle1DFvPatchScalarField< hPowerSolidThermoPhysics > expoSolid_thermalBaffle1DFvPatchScalarField
Definition at line 44 of file thermalBaffle1DFvPatchScalarFields.H.
turbulenceModel
Foam::compressible::RASModel
Definition at line 59 of file turbulentFluidThermoModel.H.
typedef laminarModel<turbulenceModel> laminarModel
Definition at line 61 of file turbulentFluidThermoModel.H.
typedef RASModel<EddyDiffusivity<turbulenceModel> > RASModel
Definition at line 62 of file turbulentFluidThermoModel.H.
LESModel
Typedefs for turbulence, RAS and LES models for compressible flow based on the standard laminar transport package.
Source files
turbulentFluidThermoModel.H
turbulentFluidThermoModel.C
turbulentFluidThermoModels.C
Definition at line 63 of file turbulentFluidThermoModel.H.
Function Documentation
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatFixedDmdtWallBoilingWallFunctionFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatPhaseChangeJayatillekeWallFunctionFvPatchScalarField)
Foam::compressible::defineTypeNameAndDebug (alphatPhaseChangeWallFunctionFvPatchScalarField , 0)
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatWallBoilingWallFunctionFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , thermalBaffleFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , convectiveHeatTransferFvPatchScalarField)
refGrad ()
Referenced by heThermo< BasicThermo, MixtureType >::heBoundaryCorrection().
valueFraction ()
Referenced by mixedEnergyFvPatchScalarField::mixedEnergyFvPatchScalarField(), and mixedUnburntEnthalpyFvPatchScalarField::mixedUnburntEnthalpyFvPatchScalarField().
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , constSolid_thermalBaffle1DFvPatchScalarField)
Foam::compressible::addToPatchFieldRunTimeSelection (fvPatchScalarField , expoSolid_thermalBaffle1DFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureCoupledBaffleMixedFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , turbulentTemperatureRadCoupledMixedFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatJayatillekeWallFunctionFvPatchScalarField)
Foam::compressible::makePatchTypeField (fvPatchScalarField , alphatWallFunctionFvPatchScalarField)
autoPtr< BasicCompressibleTurbulenceModel > New (const volScalarField & rho, const volVectorField & U, const surfaceScalarField & phi, const typename BasicCompressibleTurbulenceModel::transportModel & transport, const word & propertiesName)
Definition at line 31 of file turbulentFluidThermoModel.C.
References compressible, Foam::New(), phi, rho, and U.
Variable Documentation
else
Initial value:
{
        refValue() = *this
Definition at line 130 of file thermalBaffle1DFvPatchScalarField.C.