OpenFOAM: Foam::debug Namespace Reference
Foam::debug Namespace Reference
Namespace for handling debugging switches.
Functions
dictionary & controlDict ()
The central control dictionary, the contents of which are either taken directly from the FOAM_CONTROLDICT environment variable, or generated by merging the contents of user/group/other files.
dictionary & debugSwitches ()
The DebugSwitches sub-dictionary in the central controlDict(s).
dictionary & infoSwitches ()
The InfoSwitches sub-dictionary in the central controlDict(s).
dictionary & optimisationSwitches ()
The OptimisationSwitches sub-dictionary in the central controlDict(s).
int debugSwitch (const char *name, const int deflt=0)
Lookup debug switch or add default value.
int infoSwitch (const char *name, const int deflt=0)
Lookup info switch or add default value.
int optimisationSwitch (const char *name, const int deflt=0)
Lookup optimisation switch or add default value.
float floatOptimisationSwitch (const char *name, const float deflt=0)
Lookup optimisation switch or add default value.
dictionary & switchSet (const char *subDictName, dictionary *&subDictPtr)
Internal function to lookup a sub-dictionary from controlDict.
void addDebugObject (const char *name, simpleRegIOobject *obj)
Register debug switch read/write object.
void addInfoObject (const char *name, simpleRegIOobject *obj)
Register info switch read/write object.
void addOptimisationObject (const char *name, simpleRegIOobject *obj)
Register optimisation switch read/write object.
void addDimensionSetObject (const char *name, simpleRegIOobject *obj)
Register DimensionSets read/write object.
void addDimensionedConstantObject (const char *name, simpleRegIOobject *)
Register DimensionedConstant read/write object.
simpleObjectRegistry & debugObjects ()
Access to registered DebugSwitch objects.
simpleObjectRegistry & infoObjects ()
Access to registered InfoSwitch objects.
simpleObjectRegistry & optimisationObjects ()
Access to registered OptimisationSwitch objects.
simpleObjectRegistry & dimensionSetObjects ()
Access to registered DimensionSets objects.
simpleObjectRegistry & dimensionedConstantObjects ()
Access to registered DimensionedConstants objects.
void listSwitches (const bool unset=false)
List debug/info/optimisation switches.
void listDebugSwitches (const bool unset=false)
List debug switches.
void listInfoSwitches (const bool unset=false)
List info switches.
void listOptimisationSwitches (const bool unset=false)
List optimisation switches.
void listRegisteredSwitches (const bool unset=false)
List registered debug/info/optimisation switches.
void listRegisteredDebugSwitches (const bool unset=false)
List debug switches.
void listRegisteredInfoSwitches (const bool unset=false)
List info switches.
void listRegisteredOptimisationSwitches (const bool unset=false)
List optimisation switches.
Detailed Description
Namespace for handling debugging switches.
Source files
debug.H
debug.C
Function Documentation
Foam::dictionary & controlDict ()
The central control dictionary, the contents of which are either taken directly from the FOAM_CONTROLDICT environment variable, or generated by merging the contents of user/group/other files.
~/.OpenFOAM/{PROJECT_API}/controlDict
~/.OpenFOAM/controlDict
$WM_PROJECT_SITE/{PROJECT_API}/etc/controlDict
$WM_PROJECT_SITE/etc/controlDict
$WM_PROJECT_DIR/etc/controlDict
Where {PROJECT_API} corresponds to the foamVersion::api value.
See Also
Foam::findEtcFile()
Definition at line 139 of file debug.C.
References Foam::findEtcFiles(), forAllReverse, Foam::getEnv(), i, and SafeFatalIOErrorInFunction.
Referenced by Foam::listSwitches().
Foam::dictionary & debugSwitches ()
The DebugSwitches sub-dictionary in the central controlDict(s).
Definition at line 203 of file debug.C.
Referenced by listSwitches(), and Foam::listSwitches().
Foam::dictionary & infoSwitches ()
The InfoSwitches sub-dictionary in the central controlDict(s).
Definition at line 209 of file debug.C.
Referenced by listSwitches(), and Foam::listSwitches().
Foam::dictionary & optimisationSwitches ()
The OptimisationSwitches sub-dictionary in the central controlDict(s).
Definition at line 215 of file debug.C.
Referenced by listSwitches().
int debugSwitch (const char * name, const int deflt = 0)
Lookup debug switch or add default value.
Definition at line 221 of file debug.C.
int infoSwitch (const char * name, const int deflt = 0)
Lookup info switch or add default value.
Definition at line 227 of file debug.C.
int optimisationSwitch (const char * name, const int deflt = 0)
Lookup optimisation switch or add default value.
Definition at line 233 of file debug.C.
float floatOptimisationSwitch (const char * name, const float deflt = 0)
Lookup optimisation switch or add default value.
Definition at line 239 of file debug.C.
Foam::dictionary & switchSet (const char * subDictName, dictionary *& subDictPtr)
Internal function to lookup a sub-dictionary from controlDict.
Definition at line 176 of file debug.C.
void addDebugObject (const char * name, simpleRegIOobject * obj)
Register debug switch read/write object.
Definition at line 245 of file debug.C.
void addInfoObject (const char * name, simpleRegIOobject * obj)
Register info switch read/write object.
Definition at line 251 of file debug.C.
void addOptimisationObject (const char * name, simpleRegIOobject * obj)
Register optimisation switch read/write object.
Definition at line 258 of file debug.C.
void addDimensionSetObject (const char * name, simpleRegIOobject * obj)
Register DimensionSets read/write object.
Definition at line 268 of file debug.C.
void addDimensionedConstantObject (const char * name, simpleRegIOobject * obj)
Register DimensionedConstant read/write object.
Definition at line 278 of file debug.C.
Foam::simpleObjectRegistry & debugObjects ()
Access to registered DebugSwitch objects.
Definition at line 287 of file debug.C.
Foam::simpleObjectRegistry & infoObjects ()
Access to registered InfoSwitch objects.
Definition at line 298 of file debug.C.
Foam::simpleObjectRegistry & optimisationObjects ()
Access to registered OptimisationSwitch objects.
Definition at line 309 of file debug.C.
Foam::simpleObjectRegistry & dimensionSetObjects ()
Access to registered DimensionSets objects.
Definition at line 320 of file debug.C.
Foam::simpleObjectRegistry & dimensionedConstantObjects ()
Access to registered DimensionedConstants objects.
Definition at line 331 of file debug.C.
void listSwitches (const bool unset = false)
List debug/info/optimisation switches.
Definition at line 435 of file debug.C.
References debugSwitches(), infoSwitches(), Foam::listSwitches(), and optimisationSwitches().
void listDebugSwitches (const bool unset = false)
List debug switches.
Definition at line 447 of file debug.C.
void listInfoSwitches (const bool unset = false)
List info switches.
Definition at line 459 of file debug.C.
void listOptimisationSwitches (const bool unset = false)
List optimisation switches.
Definition at line 471 of file debug.C.
void listRegisteredSwitches (const bool unset = false)
List registered debug/info/optimisation switches.
Definition at line 483 of file debug.C.
void listRegisteredDebugSwitches (const bool unset = false)
List debug switches.
Definition at line 495 of file debug.C.
void listRegisteredInfoSwitches (const bool unset = false)
List info switches.
Definition at line 507 of file debug.C.
void listRegisteredOptimisationSwitches (const bool unset = false)
List optimisation switches.
Definition at line 519 of file debug.C.