OpenFOAM: Foam::constant::mathematical Namespace Reference
Foam::constant::mathematical Namespace Reference
Mathematical constants.
Functions
constexpr scalar e (M_E)
constexpr scalar pi (M_PI)
constexpr scalar twoPi (2 *M_PI)
constexpr scalar piByTwo (0.5 *M_PI)
constexpr scalar Eu (0.57721566490153286060651209)
Euler's constant.
Variables
constexpr const char *const group = "mathematical"
Group name for atomic constants.
Detailed Description
Mathematical constants.
Function Documentation
constexpr scalar Foam::constant::mathematical::e (M_E)
Referenced by alphatWallBoilingWallFunctionFvPatchScalarField::alphatWallBoilingWallFunctionFvPatchScalarField(), and Foam::calcQE11().
constexpr scalar Foam::constant::mathematical::pi (M_PI)
Referenced by LehrMilliesMewesCoalescence::addToCoalescenceRate(), Foam::adjustHue(), Foam::angleDiff(), KinematicParcel< ParcelType >::areaP(), ReactingHeterogeneousParcel< ParcelType >::calc(), rotorDiskSource::calculate(), ORourkeCollision< CloudType >::collide(), pointLinear< Type >::correction(), Foam::Elliptic::ellipticIntegralsKE(), primitiveMeshTools::faceSkewness(), FieldActivatedInjection< CloudType >::FieldActivatedInjection(), cosine::fLiquid(), faceCorrectedSnGrad< Type >::fullGradCorrection(), InjectedParticleInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::initialise(), DSMCParcel< ParcelType >::constantProperties::internalDegreesOfFreedom(), edgeInterpolationScheme< Type >::interpolate(), pointVolInterpolation::interpolate(), surfaceInterpolationScheme< Type >::interpolate(), Foam::colourTools::interpolateDiverging(), Foam::kShellIntegration(), eddy::move(), IATEsource::otherPhase(), KinematicParcel< ParcelType >::Re(), sixDoFRigidBodyMotion::time(), halfCosineRamp::value(), quarterCosineRamp::value(), quarterSineRamp::value(), and Foam::vertices().
constexpr scalar Foam::constant::mathematical::twoPi (2 * M_PI)
Referenced by Foam::angleDiff(), rotorDiskSource::calculate(), and Sine< Type >::value().
constexpr scalar Foam::constant::mathematical::piByTwo (0.5 * M_PI)
Referenced by Foam::transformMask(), and Foam::transformMask< sphericalTensor >().
constexpr scalar Foam::constant::mathematical::Eu (0. 57721566490153286060651209)
Euler's constant.
Variable Documentation
constexpr const char* const group = "mathematical"
Group name for atomic constants.
Group name for universal constants.
Group name for physico-chemical constants.
Group name for electromagnetic constants.
Definition at line 45 of file mathematicalConstants.H.
Referenced by nutkWallFunctionFvPatchScalarField::calcNut(), nutUWallFunctionFvPatchScalarField::calcNut(), nutkAtmRoughWallFunctionFvPatchScalarField::calcNut(), nutUTabulatedWallFunctionFvPatchScalarField::calcNut(), nutUBlendedWallFunctionFvPatchScalarField::calcNut(), nutUSpaldingWallFunctionFvPatchScalarField::calcNut(), nutkFilmWallFunctionFvPatchScalarField::calcUTau(), DispersionRASModel< CloudType >::kModel(), and obstacleGrouping::nObstacle().