OpenFOAM: Foam::vtk::Tools Namespace Reference
Foam::vtk::Tools Namespace Reference
A collection of static methods to assist converting OpenFOAM data structures into VTK internal data structures.
Classes
struct Patch
Convert OpenFOAM patch to vtkPolyData.
struct FieldAccess
Default field access is vtkCellData.
struct FieldAccess<::Foam::polySurfacePointGeoMesh >
PointAccess for point fields (on polySurfacePointGeoMesh)
Functions
UList< uint8_t > asUList (vtkUnsignedCharArray *array, const label size)
Wrap vtkUnsignedCharArray as a UList.
UList< vtkIdType > asUList (vtkIdTypeArray *array, const label size)
Wrap vtkIdTypeArray as a UList.
UList< vtkIdType > asUList (vtkCellArray *cells, const label nCells, const label size)
Wrap vtkCellArray as a UList.
vtkSmartPointer< vtkPoints > Points (const UList< point > &pts)
Return a list of points as vtkPoints.
vtkSmartPointer< vtkPoints > Points (const UList< point > &pts, const labelUList &addr)
Return an indirect list of points as vtkPoints.
template<class Face >
vtkSmartPointer< vtkCellArray > Faces (const UList< Face > &faces)
Convert a list of faces (or triFaces) to vtk polygon cells.
vtkSmartPointer< vtkPolyData > Vertices (const UList< point > &pts)
Return vtkPolyData of vertices for each point.
vtkSmartPointer< vtkPolyData > Vertices (const UList< point > &pts, const labelUList &addr)
Return vtkPolyData of vertices for each point.
scalarMinMax rangeOf (vtkDataArray *data)
Min/Max of scalar, or mag() of non-scalars. Includes nullptr check.
template<class Type >
void remapTuple (float data[])
Remapping for some OpenFOAM data types (eg, symmTensor)
template<>
void remapTuple< symmTensor > (float data[])
Template specialization for symmTensor ordering.
template<class Type >
void remapTuple (double data[])
Remapping for some OpenFOAM data types (eg, symmTensor)
template<>
void remapTuple< symmTensor > (double data[])
Template specialization for symmTensor ordering.
template<class Type >
void foamToVtkTuple (float output[], const Type &val)
Copy/transcribe OpenFOAM data types to VTK format.
template<class Type >
void foamToVtkTuple (double output[], const Type &val)
Copy/transcribe OpenFOAM data types to VTK format.
template<class Type >
label transcribeFloatData (vtkFloatArray *array, const UList< Type > &input, vtkIdType start=0)
Copy list to pre-allocated vtk array.
template<class Type >
vtkSmartPointer< vtkFloatArray > zeroField (const word &name, const label size)
Create named field initialized to zero.
template<class Type >
vtkSmartPointer< vtkFloatArray > convertFieldToVTK (const word &name, const UList< Type > &fld)
Convert field data to a vtkFloatArray.
vtkSmartPointer< vtkCellArray > identityVertices (const label size)
An identity list of VTK_VERTEX.
vtkCellData * GetCellData (vtkDataSet *dataset)
Functional call with null-pointer check.
vtkPointData * GetPointData (vtkDataSet *dataset)
Functional call with null-pointer check.
Detailed Description
A collection of static methods to assist converting OpenFOAM data structures into VTK internal data structures.
Remapping of the symmTensor order is required in input or output directions. OpenFOAM uses (XX, XY, XZ, YY, YZ, ZZ) order, VTK uses (XX, YY, ZZ, XY, YZ, XZ) order.
Note
The class is implemented as headers-only.
Source files
foamVtkTools.H
foamVtkToolsI.H
foamVtkToolsTemplates.C
Function Documentation
Foam::UList< uint8_t > asUList (vtkUnsignedCharArray * array, const label size) inline
Wrap vtkUnsignedCharArray as a UList.
Definition at line 24 of file foamVtkToolsI.H.
Referenced by Faces().
Foam::UList< vtkIdType > asUList (vtkIdTypeArray * array, const label size) inline
Wrap vtkIdTypeArray as a UList.
Definition at line 37 of file foamVtkToolsI.H.
Foam::UList< vtkIdType > asUList (vtkCellArray * cells, const label nCells, const label size) inline
Wrap vtkCellArray as a UList.
Definition at line 50 of file foamVtkToolsI.H.
vtkSmartPointer< vtkPoints > Points (const UList< point > & pts) inline
Return a list of points as vtkPoints.
Definition at line 63 of file foamVtkToolsI.H.
Referenced by Foam::polyMeshZipUpCells().
vtkSmartPointer< vtkPoints > Points (const UList< point > & pts, const labelUList & addr) inline
Return an indirect list of points as vtkPoints.
Definition at line 80 of file foamVtkToolsI.H.
vtkSmartPointer< vtkCellArray > Faces (const UList< Face > & faces)
Convert a list of faces (or triFaces) to vtk polygon cells.
Definition at line 37 of file foamVtkToolsTemplates.C.
References asUList(), UList< T >::begin(), f(), iter, Foam::New(), and UList< T >::size().
Referenced by Patch::mesh().
vtkSmartPointer< vtkPolyData > Vertices (const UList< point > & pts) inline
Return vtkPolyData of vertices for each point.
Definition at line 97 of file foamVtkToolsI.H.
Referenced by geometryCloud::gatherCloud().
vtkSmartPointer< vtkPolyData > Vertices (const UList< point > & pts, const labelUList & addr) inline
Return vtkPolyData of vertices for each point.
Definition at line 109 of file foamVtkToolsI.H.
Foam::scalarMinMax rangeOf (vtkDataArray * data) inline
Min/Max of scalar, or mag() of non-scalars. Includes nullptr check.
Definition at line 120 of file foamVtkToolsI.H.
Referenced by fieldVisualisationBase::queryFieldSummary().
void Foam::vtk::Tools::remapTuple (float data[]) inline
Remapping for some OpenFOAM data types (eg, symmTensor)
Parameters
data[in,out] The data to be remapped in-place
Definition at line 317 of file foamVtkTools.H.
void Foam::vtk::Tools::remapTuple< symmTensor > (float data[]) inline
Template specialization for symmTensor ordering.
void Foam::vtk::Tools::remapTuple (double data[]) inline
Remapping for some OpenFOAM data types (eg, symmTensor)
Parameters
data[in,out] The data to be remapped in-place
Definition at line 331 of file foamVtkTools.H.
void Foam::vtk::Tools::remapTuple< symmTensor > (double data[]) inline
Template specialization for symmTensor ordering.
void foamToVtkTuple (float output[], const Type & val) inline
Copy/transcribe OpenFOAM data types to VTK format.
This allows a change of data type (float vs double) as well as addressing any swapping issues (eg, symmTensor)
Parameters
output[out] The output scratch space. Must be long enough to hold the result.
val[in] The input data to copy/transcribe
Definition at line 166 of file foamVtkToolsI.H.
Referenced by vtuAdaptor::convertField().
void foamToVtkTuple (double output[], const Type & val) inline
Copy/transcribe OpenFOAM data types to VTK format.
This allows a change of data type (float vs double) as well as addressing any swapping issues (eg, symmTensor)
Parameters
output[out] The output scratch space. Must be long enough to hold the result.
val[in] The input data to copy/transcribe
Definition at line 181 of file foamVtkToolsI.H.
label Foam::vtk::Tools::transcribeFloatData (vtkFloatArray * array, const UList< Type > & input, vtkIdType start = 0)
Copy list to pre-allocated vtk array.
Returns
number of input items copied
Parameters
start The write offset into output array
vtkSmartPointer< vtkFloatArray > zeroField (const word & name, const label size)
Create named field initialized to zero.
Definition at line 251 of file foamVtkToolsTemplates.C.
Referenced by Foam::MULES::correct(), Foam::MULES::explicitSolve(), for(), if(), Foam::operator*(), Foam::operator+(), Foam::operator-(), Foam::operator/(), and zeroFieldField::operator[]().
vtkSmartPointer< vtkFloatArray > convertFieldToVTK (const word & name, const UList< Type > & fld)
Convert field data to a vtkFloatArray.
Definition at line 279 of file foamVtkToolsTemplates.C.
vtkSmartPointer< vtkCellArray > identityVertices (const label size) inline
An identity list of VTK_VERTEX.
Definition at line 142 of file foamVtkToolsI.H.
vtkCellData * GetCellData (vtkDataSet * dataset)
Functional call with null-pointer check.
Definition at line 73 of file surface.C.
vtkPointData * GetPointData (vtkDataSet * dataset)
Functional call with null-pointer check.
Definition at line 79 of file surface.C.