OpenFOAM: Foam::extrudeModels Namespace Reference
Foam::extrudeModels Namespace Reference
Classes
class cyclicSector
Extrudes a sector.
class linearDirection
Extrudes by transforming points in a specified direction by the given distance.
class linearNormal
Extrudes by transforming points normal to the surface by a given distance.
class linearRadial
Extrudes by transforming radially from the surface.
class offsetSurface
Extrudes by interpolating points from one surface to the other. Surfaces have to be topologically identical i.e. one has to be an offsetted version of the other.
class plane
Extrudes by transforming points normal to the surface by 1 layer over a given distance.
class radial
Extrudes radially according to the Function1 description.
class sector
Extrudes by rotating a surface around an axis.
class sigmaRadial
Extrudes into sphere with grading according to pressure (atmospherics)
class wedge
Extrudes by rotating a surface symmetrically around axis by 1 layer.
Functions
defineTypeNameAndDebug (cyclicSector, 0)
addToRunTimeSelectionTable (extrudeModel, cyclicSector, dictionary)
defineTypeNameAndDebug (linearDirection, 0)
addToRunTimeSelectionTable (extrudeModel, linearDirection, dictionary)
defineTypeNameAndDebug (linearNormal, 0)
addToRunTimeSelectionTable (extrudeModel, linearNormal, dictionary)
defineTypeNameAndDebug (linearRadial, 0)
addToRunTimeSelectionTable (extrudeModel, linearRadial, dictionary)
defineTypeNameAndDebug (offsetSurface, 0)
addToRunTimeSelectionTable (extrudeModel, offsetSurface, dictionary)
defineTypeNameAndDebug (plane, 0)
addToRunTimeSelectionTable (extrudeModel, plane, dictionary)
defineTypeNameAndDebug (radial, 0)
addToRunTimeSelectionTable (extrudeModel, radial, dictionary)
defineTypeNameAndDebug (sector, 0)
addToRunTimeSelectionTable (extrudeModel, sector, dictionary)
axis_ (coeffDict_.get< vector >("axis").normalise())
angle_ (degToRad(coeffDict_.get< scalar >("angle")))
defineTypeNameAndDebug (sigmaRadial, 0)
addToRunTimeSelectionTable (extrudeModel, sigmaRadial, dictionary)
defineTypeNameAndDebug (wedge, 0)
addToRunTimeSelectionTable (extrudeModel, wedge, dictionary)
Function Documentation
Foam::extrudeModels::defineTypeNameAndDebug (cyclicSector , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , cyclicSector , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (linearDirection , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , linearDirection , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (linearNormal , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , linearNormal , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (linearRadial , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , linearRadial , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (offsetSurface , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , offsetSurface , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (plane , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , plane , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (radial , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , radial , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (sector , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , sector , dictionary)
Foam::extrudeModels::axis_ (coeffDict_.get< vector > "axis").normalise()
Foam::extrudeModels::angle_ (degToRad(coeffDict_.get< scalar >("angle")))
Definition at line 47 of file sector.C.
Referenced by axisAngle::R(), axisAngle::write(), and axisAngle::writeEntry().
Foam::extrudeModels::defineTypeNameAndDebug (sigmaRadial , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , sigmaRadial , dictionary)
Foam::extrudeModels::defineTypeNameAndDebug (wedge , 0)
Foam::extrudeModels::addToRunTimeSelectionTable (extrudeModel , wedge , dictionary)