OpenFOAM: Foam::ensightOutput::Detail Namespace Reference
Foam::ensightOutput::Detail Namespace Reference
Implementation details and output backends that would not normally be called directly by a user.
Functions
template<class Type >
bool writeVolField (const GeometricField< Type, fvPatchField, volMesh > &vf, const ensightMesh &ensMesh, ensightFile &os)
Write volume field component-wise.
template<class Type >
bool writePointField (const GeometricField< Type, pointPatchField, pointMesh > &pf, const ensightMesh &ensMesh, ensightFile &os)
Write point field component-wise.
template<template< typename > class FieldContainer, class Type >
bool writeFieldComponents (const char *key, const FieldContainer< Type > &fld, ensightFile &os, bool parallel)
Write field content (component-wise) for the given ensight element type.
template<class Type >
bool writeFaceField (const Field< Type > &fld, const ensightFaces &part, ensightFile &os, bool parallel)
Write a field of faces values as an indirect list, using the face ids from ensightFaces.
template<class Type >
bool writeFaceSubField (const Field< Type > &fld, const ensightFaces &part, ensightFile &os, bool parallel)
Write a sub-field of faces values as an indirect list, using the sublist sizing information from ensightFaces.
template<class Type >
bool writeCellField (const Field< Type > &fld, const ensightCells &part, ensightFile &os, bool parallel)
Write a field of cell values as an indirect list, using the cell ids from ensightCells.
Detailed Description
Implementation details and output backends that would not normally be called directly by a user.
Function Documentation
bool writeVolField (const GeometricField< Type, fvPatchField, volMesh > & vf, const ensightMesh & ensMesh, ensightFile & os)
Write volume field component-wise.
Definition at line 37 of file ensightOutputVolFieldTemplates.C.
References fvMesh::boundary(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), ensightMesh::boundaryPatchFaces(), UList< T >::empty(), faceId(), ensightMesh::faceZoneFaces(), forAll, i, primitiveMesh::isInternalFace(), Foam::linearInterpolate(), mesh, ensightMesh::mesh(), ensightMesh::meshCells(), primitiveMesh::nBoundaryFaces(), primitiveMesh::nInternalFaces(), polyPatch::offset(), ensightMesh::patches(), patchId(), patchIds, ensightFaces::size(), HashTable< T, label, Hash< label > >::sortedToc(), HashTable< T, Key, Hash >::sortedToc(), ensightMesh::useInternalMesh(), Foam::HashTableOps::values(), writeCellField(), writeFaceField(), writeFaceSubField(), and Foam::Zero.
bool writePointField (const GeometricField< Type, pointPatchField, pointMesh > & pf, const ensightMesh & ensMesh, ensightFile & os)
Write point field component-wise.
Definition at line 160 of file ensightOutputVolFieldTemplates.C.
bool writeFieldComponents (const char * key, const FieldContainer< Type > & fld, ensightFile & os, bool parallel)
Write field content (component-wise) for the given ensight element type.
Parameters
parallel Collective write?
Definition at line 28 of file ensightOutputTemplates.C.
References d, Foam::reduce(), ensightFile::writeKeyword(), and ensightFile::writeList().
bool writeFaceField (const Field< Type > & fld, const ensightFaces & part, ensightFile & os, bool parallel)
Write a field of faces values as an indirect list, using the face ids from ensightFaces.
Parameters
parallel Collective write?
Definition at line 112 of file ensightOutputTemplates.C.
Referenced by writeVolField().
bool writeFaceSubField (const Field< Type > & fld, const ensightFaces & part, ensightFile & os, bool parallel)
Write a sub-field of faces values as an indirect list, using the sublist sizing information from ensightFaces.
Parameters
parallel Collective write?
Definition at line 164 of file ensightOutputTemplates.C.
Referenced by writeVolField().
bool writeCellField (const Field< Type > & fld, const ensightCells & part, ensightFile & os, bool parallel)
Write a field of cell values as an indirect list, using the cell ids from ensightCells.
Parameters
parallel Collective write?
Definition at line 268 of file ensightOutputTemplates.C.
Referenced by writeVolField().