OpenFOAM: stdFoam Namespace Reference
stdFoam Namespace Reference
Global macros and templates used by OpenFOAM and some standard C++ headers.
Functions
template<class C >
constexpr auto begin (C &c) -> decltype(c.begin())
Return iterator to the beginning of the container c.
template<class C >
constexpr auto begin (const C &c) -> decltype(c.begin())
Return const_iterator to the beginning of the container c.
template<class C >
constexpr auto cbegin (const C &c) -> decltype(c.begin())
Return const_iterator to the beginning of the container c.
template<class C >
constexpr auto end (C &c) -> decltype(c.end())
Return iterator to the end of the container c.
template<class C >
constexpr auto end (const C &c) -> decltype(c.end())
Return const_iterator to the end of the container c.
template<class C >
constexpr auto cend (const C &c) -> decltype(c.end())
Return const_iterator to the end of the container c.
template<class C >
constexpr auto rbegin (C &c) -> decltype(c.rbegin())
Return reverse_iterator to the reverse-begin of container c.
template<class C >
constexpr auto rbegin (const C &c) -> decltype(c.rbegin())
Return const_reverse_iterator to the reverse-begin of container c.
template<class C >
constexpr auto crbegin (const C &c) -> decltype(c.rbegin())
Return const_reverse_iterator to the reverse-begin of container c.
template<class C >
constexpr auto rend (C &c) -> decltype(c.rend())
Return reverse_iterator to reverse-end of container c.
template<class C >
constexpr auto rend (const C &c) -> decltype(c.rend())
Return const_reverse_iterator to reverse-end of container c.
template<class C >
constexpr auto crend (const C &c) -> decltype(c.rend())
Return const_reverse_iterator to reverse-end of container c.
template<class T >
constexpr const T & min (const T &a, const T &b)
Return the lesser of the parameters.
template<class T >
constexpr const T & max (const T &a, const T &b)
Return the greater of the parameters.
Detailed Description
Global macros and templates used by OpenFOAM and some standard C++ headers.
Some of the templates defined here correspond to useful std templates that are part of future C++ standards, or that are in a state of change. Defining them here provides some additional control over which definitions are used within the OpenFOAM code-base.
See Also
http://en.cppreference.com/w/cpp/iterator/begin
http://en.cppreference.com/w/cpp/iterator/end
http://en.cppreference.com/w/cpp/iterator/rbegin
http://en.cppreference.com/w/cpp/iterator/rend
Function Documentation
constexpr auto stdFoam::begin (C & c) -> decltype(c.begin())
Return iterator to the beginning of the container c.
Definition as per std::begin C++17
Definition at line 94 of file stdFoam.H.
Referenced by DictionaryBase< IDLListType, T >::addEntries(), FixedList< T, N >::crend(), UList< T >::crend(), Matrix< Form, Type >::operator+=(), Matrix< Form, Type >::operator=(), FixedList< T, N >::rend(), UList< T >::rend(), and UList< T >::size().
constexpr auto stdFoam::begin (const C & c) -> decltype(c.begin())
Return const_iterator to the beginning of the container c.
Definition as per std::begin C++17
Definition at line 105 of file stdFoam.H.
References c().
constexpr auto stdFoam::cbegin (const C & c) -> decltype(c.begin())
Return const_iterator to the beginning of the container c.
Definition as per std::cbegin C++17
Definition at line 116 of file stdFoam.H.
References c().
Referenced by LPtrList< LListBase, T >::const_reverse_iterator::const_reverse_iterator(), UILList< LListBase, T >::const_reverse_iterator::const_reverse_iterator(), and LList< LListBase, T >::reverse_iterator::reverse_iterator().
constexpr auto stdFoam::end (C & c) -> decltype(c.end())
Return iterator to the end of the container c.
Definition as per std::end C++17
Definition at line 127 of file stdFoam.H.
References c().
constexpr auto stdFoam::end (const C & c) -> decltype(c.end())
Return const_iterator to the end of the container c.
Definition as per std::end C++17
Definition at line 138 of file stdFoam.H.
References c().
constexpr auto stdFoam::cend (const C & c) -> decltype(c.end())
Return const_iterator to the end of the container c.
Definition as per std::cend C++17
Definition at line 149 of file stdFoam.H.
References c().
constexpr auto stdFoam::rbegin (C & c) -> decltype(c.rbegin())
Return reverse_iterator to the reverse-begin of container c.
Definition as per std::rbegin C++17
Definition at line 163 of file stdFoam.H.
References c().
constexpr auto stdFoam::rbegin (const C & c) -> decltype(c.rbegin())
Return const_reverse_iterator to the reverse-begin of container c.
Definition as per std::rbegin C++17
Definition at line 174 of file stdFoam.H.
References c().
constexpr auto stdFoam::crbegin (const C & c) -> decltype(c.rbegin())
Return const_reverse_iterator to the reverse-begin of container c.
Definition as per std::crbegin C++17
Definition at line 185 of file stdFoam.H.
constexpr auto stdFoam::rend (C & c) -> decltype(c.rend())
Return reverse_iterator to reverse-end of container c.
Definition as per std::rend C++17
Definition at line 196 of file stdFoam.H.
constexpr auto stdFoam::rend (const C & c) -> decltype(c.rend())
Return const_reverse_iterator to reverse-end of container c.
Definition as per std::rend C++17
Definition at line 207 of file stdFoam.H.
constexpr auto stdFoam::crend (const C & c) -> decltype(c.rend())
Return const_reverse_iterator to reverse-end of container c.
Definition as per std::crend C++17
Definition at line 218 of file stdFoam.H.
constexpr const T& stdFoam::min (const T & a, const T & b) inline
Return the lesser of the parameters.
Definition as per std::min C++14
Definition at line 229 of file stdFoam.H.
constexpr const T& stdFoam::max (const T & a, const T & b) inline
Return the greater of the parameters.
Definition as per std::max C++14
Definition at line 240 of file stdFoam.H.