OpenFOAM: Foam::colourTools Namespace Reference
Foam::colourTools Namespace Reference
Utility methods for colours and colour spaces.
Functions
void rgbToHsv (const vector &rgb, vector &hsv)
Convert RGB to HSV.
vector rgbToHsv (const vector &rgb)
Convert RGB to HSV.
void hsvToRgb (const vector &hsv, vector &rgb)
Convert HSV to RGB.
vector hsvToRgb (const vector &hsv)
Convert HSV to RGB.
void rgbToXyz (const vector &rgb, vector &xyz)
Convert RGB to XYZ.
vector rgbToXyz (const vector &rgb)
Convert RGB to XYZ.
void xyzToRgb (const vector &xyz, vector &rgb)
Convert XYZ to RGB.
vector xyzToRgb (const vector &xyz)
Convert XYZ to RGB.
void labToXyz (const vector &lab, vector &xyz)
Convert LAB to XYZ.
vector labToXyz (const vector &lab)
Convert LAB to XYZ.
void xyzToLab (const vector &xyz, vector &lab)
Convert XYZ to LAB.
vector xyzToLab (const vector &xyz)
Convert XYZ to LAB.
void rgbToLab (const vector &rgb, vector &lab)
Convert RGB to LAB.
vector rgbToLab (const vector &rgb)
Convert RGB to LAB.
void labToRgb (const vector &lab, vector &rgb)
Convert LAB to RGB.
vector labToRgb (const vector &lab)
Convert LAB to RGB.
void interpolateDiverging (scalar s, const vector &rgb1, const vector &rgb2, vector &result)
Interpolate RGB values with diverging color map.
vector interpolateDiverging (scalar s, const vector &rgb1, const vector &rgb2)
Interpolate RGB values with diverging color map.
void interpolateHSV (scalar s, const vector &rgb1, const vector &rgb2, vector &result)
Interpolate RGB values in HSV colourspace.
vector interpolateHSV (scalar s, const vector &rgb1, const vector &rgb2)
Interpolate RGB values in HSV colourspace.
vector interpolateRGB (scalar s, const vector &rgb1, const vector &rgb2)
Interpolate RGB values in RGB colourspace.
Detailed Description
Utility methods for colours and colour spaces.
Source files
colourTools.H
colourTools.C
Function Documentation
void rgbToHsv (const vector & rgb, vector & hsv)
Convert RGB to HSV.
Definition at line 350 of file colourTools.C.
References Foam::RGB_to_HSV().
Referenced by interpolateHSV(), and rgbToHsv().
vector Foam::colourTools::rgbToHsv (const vector & rgb) inline
Convert RGB to HSV.
Definition at line 57 of file colourTools.H.
References rgbToHsv().
void hsvToRgb (const vector & hsv, vector & rgb)
Convert HSV to RGB.
Definition at line 355 of file colourTools.C.
Referenced by interpolateHSV().
vector Foam::colourTools::hsvToRgb (const vector & hsv) inline
Convert HSV to RGB.
Definition at line 73 of file colourTools.H.
void rgbToXyz (const vector & rgb, vector & xyz)
Convert RGB to XYZ.
Definition at line 361 of file colourTools.C.
References Foam::RGB_to_XYZ().
vector Foam::colourTools::rgbToXyz (const vector & rgb) inline
Convert RGB to XYZ.
Definition at line 89 of file colourTools.H.
void xyzToRgb (const vector & xyz, vector & rgb)
Convert XYZ to RGB.
Definition at line 366 of file colourTools.C.
Referenced by labToRgb().
vector Foam::colourTools::xyzToRgb (const vector & xyz) inline
Convert XYZ to RGB.
Definition at line 104 of file colourTools.H.
References labToXyz().
void labToXyz (const vector & lab, vector & xyz)
Convert LAB to XYZ.
Definition at line 372 of file colourTools.C.
References Foam::LAB_to_XYZ().
Referenced by labToRgb(), and xyzToRgb().
vector Foam::colourTools::labToXyz (const vector & lab) inline
Convert LAB to XYZ.
Definition at line 120 of file colourTools.H.
void xyzToLab (const vector & xyz, vector & lab)
Convert XYZ to LAB.
Definition at line 378 of file colourTools.C.
References Foam::XYZ_to_LAB().
vector Foam::colourTools::xyzToLab (const vector & xyz) inline
Convert XYZ to LAB.
Definition at line 136 of file colourTools.H.
void rgbToLab (const vector & rgb, vector & lab)
Convert RGB to LAB.
Definition at line 384 of file colourTools.C.
References Foam::RGB_to_XYZ(), and Foam::XYZ_to_LAB().
Referenced by interpolateDiverging().
vector Foam::colourTools::rgbToLab (const vector & rgb) inline
Convert RGB to LAB.
Definition at line 152 of file colourTools.H.
void labToRgb (const vector & lab, vector & rgb)
Convert LAB to RGB.
Definition at line 392 of file colourTools.C.
References labToXyz(), and xyzToRgb().
Referenced by interpolateDiverging().
vector Foam::colourTools::labToRgb (const vector & lab) inline
Convert LAB to RGB.
Definition at line 168 of file colourTools.H.
void interpolateDiverging (scalar s, const vector & rgb1, const vector & rgb2, vector & result)
Interpolate RGB values with diverging color map.
Definition at line 401 of file colourTools.C.
References Foam::adjustHue(), Foam::angleDiff(), Foam::labToMsh(), labToRgb(), Foam::max(), Foam::mshToLab(), Foam::constant::mathematical::pi(), rgbToLab(), and s.
vector Foam::colourTools::interpolateDiverging (scalar s, const vector & rgb1, const vector & rgb2) inline
Interpolate RGB values with diverging color map.
Definition at line 191 of file colourTools.H.
void interpolateHSV (scalar s, const vector & rgb1, const vector & rgb2, vector & result)
Interpolate RGB values in HSV colourspace.
Definition at line 465 of file colourTools.C.
References hsvToRgb(), and rgbToHsv().
vector Foam::colourTools::interpolateHSV (scalar s, const vector & rgb1, const vector & rgb2) inline
Interpolate RGB values in HSV colourspace.
Definition at line 218 of file colourTools.H.
vector Foam::colourTools::interpolateRGB (scalar s, const vector & rgb1, const vector & rgb2) inline
Interpolate RGB values in RGB colourspace.
Definition at line 234 of file colourTools.H.