OpenFOAM: Foam::blockMeshTools Namespace Reference
Foam::blockMeshTools Namespace Reference
Tools for parsing label(List) with dictionary lookup.
Functions
void read (Istream &, label &, const dictionary &)
In-place read with dictionary lookup.
template<class T >
void read (Istream &, List< T > &, const dictionary &)
In-place read with dictionary lookup.
label read (Istream &, const dictionary &)
Return-read with dictionary lookup.
void write (Ostream &, const label, const dictionary &)
Write with dictionary lookup.
const keyType & findEntry (const dictionary &, const label)
Linear search for label entry.
Detailed Description
Tools for parsing label(List) with dictionary lookup.
Source files
blockMeshTools.H
blockMeshTools.C
blockMeshToolsTemplates.C
Function Documentation
void read (Istream & is, label & val, const dictionary & dict)
In-place read with dictionary lookup.
Definition at line 26 of file blockMeshTools.C.
References Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, dictionary::findScoped(), token::info(), token::isLabel(), token::isWord(), token::labelToken(), Foam::readLabel(), entry::stream(), and token::wordToken().
Referenced by AC3DsurfaceFormat< Face >::AC3DsurfaceFormat(), setTimeStepFunctionObject::adjustTimeStep(), linearViscousStress< BasicTurbulenceModel >::devRhoReff(), dictionary::dictionary(), edgeMesh::edgeMesh(), dsmcFields::execute(), fieldValue::fieldValue(), GTSsurfaceFormat< Face >::GTSsurfaceFormat(), MultiInteraction< CloudType >::MultiInteraction(), OBJsurfaceFormat< Face >::OBJsurfaceFormat(), OFFsurfaceFormat< Face >::OFFsurfaceFormat(), eddyViscosity< BasicTurbulenceModel >::R(), ReynoldsStress< BasicTurbulenceModel >::R(), read(), tolerances::read(), trimModel::read(), removeRegisteredObject::read(), derivedFields::read(), writeObjects::read(), CodedSource< Type >::read(), edgeMesh::read(), Scale< Type >::Scale(), Sine< Type >::Sine(), Square< Type >::Square(), UnsortedMeshedSurface< Face >::UnsortedMeshedSurface(), ZoneMesh< Zone, MeshType >::ZoneMesh(), axis::~axis(), externalForce::~externalForce(), fieldValue::~fieldValue(), line::~line(), linearAxialAngularSpring::~linearAxialAngularSpring(), linearDamper::~linearDamper(), linearMotion::~linearMotion(), linearSpring::~linearSpring(), multiMotion::~multiMotion(), orientation::~orientation(), particleDistribution::~particleDistribution(), plane::~plane(), point::~point(), prescribedRotation::~prescribedRotation(), softWall::~softWall(), sphericalAngularDamper::~sphericalAngularDamper(), surfaceInterpolate::~surfaceInterpolate(), tabulated6DoFMotion::~tabulated6DoFMotion(), writeCellCentres::~writeCellCentres(), writeCellVolumes::~writeCellVolumes(), and XiReactionRate::~XiReactionRate().
void read (Istream & is, List< T > & L, const dictionary & dict)
In-place read with dictionary lookup.
Definition at line 25 of file blockMeshToolsTemplates.C.
References LList< LListBase, T >::append(), Foam::exit(), Foam::FatalIOError, FatalIOErrorInFunction, i, token::info(), token::isLabel(), token::isPunctuation(), token::labelToken(), token::pToken(), Istream::putBack(), read(), Istream::readBeginList(), Istream::readEndList(), s, List< T >::setSize(), and T.
Foam::List< T > read (Istream & is, const dictionary & dict)
Return-read with dictionary lookup.
Definition at line 69 of file blockMeshTools.C.
void write (Ostream & os, const label val, const dictionary & dict)
Write with dictionary lookup.
Definition at line 81 of file blockMeshTools.C.
const Foam::keyType & findEntry (const dictionary & dict, const label val)
Linear search for label entry.
Definition at line 104 of file blockMeshTools.C.