OpenFOAM: Foam::HashSetOps Namespace Reference
Foam::HashSetOps Namespace Reference
Various operations for HashSet.
Classes
struct plusEqOp
Combine HashSet operation. Equivalent to 'a |= b'.
Functions
labelHashSet used (const bitSet &select)
Convert a bitset to a labelHashSet of the indices used.
labelHashSet used (const UList< bool > &select)
Convert a list of bools to a labelHashSet of the indices used.
bitSet bitset (const labelHashSet &locations)
Transform the on locations to a bitSet.
List< bool > bools (const labelHashSet &locations)
Transform the on locations to a boolList, with true for each non-negative location and false for all others.
Detailed Description
Various operations for HashSet.
Function Documentation
Foam::labelHashSet used (const bitSet & select)
Convert a bitset to a labelHashSet of the indices used.
Parameters
select the bitset for which an on entry corresponds to an index in the output labelHashSet
Returns
a labelHashSet of the selected indices
This is equivalent of the following code, but more efficiently implemented.
*     bitSet select = ...;
*     return labelHashSet(select.toc());
*
Definition at line 28 of file HashOps.C.
References bitSet::any(), bitSet::count(), bitSet::find_first(), bitSet::find_next(), i, HashSet< Key, Hash >::insert(), and HashTable< T, Key, Hash >::resize().
Referenced by mappedPatchBase::calcMapping(), and Foam::polyMeshZipUpCells().
Foam::labelHashSet used (const UList< bool > & select)
Convert a list of bools to a labelHashSet of the indices used.
Parameters
select the boolList for which a true entry corresponds to an index in the output labelHashSet
Returns
a labelHashSet of the selected indices
Definition at line 46 of file HashOps.C.
Foam::bitSet bitset (const labelHashSet & locations)
Transform the on locations to a bitSet.
Ignored any negative values (invalid positions in a bitset).
Parameters
locations the list of positions corresponding to an on bit.
Returns
a bitset
See Also
BitSetOps::create for other possiblities
Definition at line 65 of file HashOps.C.
Referenced by bitSet::operator&=().
Foam::List< bool > bools (const labelHashSet & locations)
Transform the on locations to a boolList, with true for each non-negative location and false for all others.
Parameters
locations the list of positions corresponding to an on bit.
Returns
a boolList
Note
The operation necessarily discards any negative values since these are invalid positions in a boolList.
Definition at line 74 of file HashOps.C.
Referenced by parseDriver::setInternalFieldResult(), and topoBoolSet::topoBoolSet().