OpenFOAM: Foam::fam Namespace Reference
Foam::fam Namespace Reference
Functions
template<class Type >
tmp< faMatrix< Type > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > d2dt2 (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > d2dt2 (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ddt (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ddt (const dimensionedScalar &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ddt (const areaScalarField &rho, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > div (const edgeScalarField &flux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > div (const tmp< edgeScalarField > &tflux, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const dimensionedScalar &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const areaScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const tmp< areaScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const edgeScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const tmp< edgeScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > laplacian (const edgeScalarField &gamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > laplacian (const tmp< edgeScalarField > &tgamma, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ndiv (const edgeScalarField &flux, GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > &tflux, GeometricField< Type, faPatchField, areaMesh > &vf, const word &name)
template<class Type >
tmp< faMatrix< Type > > ndiv (const edgeScalarField &flux, GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > &tflux, GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > Su (const GeometricField< Type, faPatchField, areaMesh > &su, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > Su (const tmp< GeometricField< Type, faPatchField, areaMesh >> &tsu, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > Sp (const areaScalarField &sp, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > Sp (const tmp< areaScalarField > &tsp, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > Sp (const dimensionedScalar &sp, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > SuSp (const areaScalarField &sp, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<class Type >
tmp< faMatrix< Type > > SuSp (const tmp< areaScalarField > &tsp, const GeometricField< Type, faPatchField, areaMesh > &vf)
template<>
tmp< faMatrix< scalar > > div (const edgeScalarField &flux, const GeometricField< scalar, faPatchField, areaMesh > &vf, const word &name)
Function Documentation
tmp< faMatrix< Type > > d2dt2 (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 40 of file famD2dt2.C.
References DimensionedField< Type, GeoMesh >::mesh(), and faD2dt2Scheme< Type >::New().
tmp< faMatrix< Type > > d2dt2 (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 54 of file famD2dt2.C.
tmp< faMatrix< Type > > d2dt2 (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 72 of file famD2dt2.C.
tmp< faMatrix< Type > > ddt (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 41 of file famDdt.C.
References DimensionedField< Type, GeoMesh >::mesh(), IOobject::name(), and faDdtScheme< Type >::New().
tmp< faMatrix< Type > > ddt (const dimensionedScalar & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 56 of file famDdt.C.
tmp< faMatrix< Type > > ddt (const areaScalarField & rho, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 75 of file famDdt.C.
tmp< faMatrix< Type > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 41 of file famDiv.C.
References Foam::fvc::flux(), M, DimensionedField< Type, GeoMesh >::mesh(), n, Foam::name(), and ref().
Referenced by div().
tmp< faMatrix< Type > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 80 of file famDiv.C.
tmp< faMatrix< Type > > div (const edgeScalarField & flux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 96 of file famDiv.C.
tmp< faMatrix< Type > > div (const tmp< edgeScalarField > & tflux, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 107 of file famDiv.C.
References div(), and IOobject::name().
tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 42 of file famLaplacian.C.
References IOobject::db(), Foam::dimless, DimensionedField< Type, GeoMesh >::mesh(), IOobject::NO_READ, and IOobject::time().
tmp< faMatrix< Type > > laplacian (const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 66 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 91 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const dimensionedScalar & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 116 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 142 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const areaScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 159 of file famLaplacian.C.
tmp<faMatrix<Type> > Foam::fam::laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 176 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const tmp< areaScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 190 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const edgeScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 205 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const tmp< edgeScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 222 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const edgeScalarField & gamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 237 of file famLaplacian.C.
tmp< faMatrix< Type > > laplacian (const tmp< edgeScalarField > & tgamma, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 253 of file famLaplacian.C.
tmp< faMatrix< Type > > ndiv (const edgeScalarField & flux, GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 41 of file famNDiv.C.
References Foam::fvc::flux(), DimensionedField< Type, GeoMesh >::mesh(), Foam::name(), and convectionScheme< Type >::New().
tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > & tflux, GeometricField< Type, faPatchField, areaMesh > & vf, const word & name)
Definition at line 59 of file famNDiv.C.
tmp< faMatrix< Type > > ndiv (const edgeScalarField & flux, GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 75 of file famNDiv.C.
tmp< faMatrix< Type > > ndiv (const tmp< edgeScalarField > & tflux, GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 87 of file famNDiv.C.
tmp< faMatrix< Type > > Su (const GeometricField< Type, faPatchField, areaMesh > & su, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 40 of file famSup.C.
References Foam::dimArea, DimensionedField< Type, GeoMesh >::dimensions(), GeometricField< Type, PatchField, GeoMesh >::internalField(), mesh, DimensionedField< Type, GeoMesh >::mesh(), tmp< T >::ref(), faMesh::S(), and faMatrix< Type >::source().
tmp< faMatrix< Type > > Su (const tmp< GeometricField< Type, faPatchField, areaMesh >> & tsu, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 65 of file famSup.C.
tmp< faMatrix< Type > > Sp (const areaScalarField & sp, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 79 of file famSup.C.
tmp< faMatrix< Type > > Sp (const tmp< areaScalarField > & tsp, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 104 of file famSup.C.
tmp< faMatrix< Type > > Sp (const dimensionedScalar & sp, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 118 of file famSup.C.
tmp< faMatrix< Type > > SuSp (const areaScalarField & sp, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 144 of file famSup.C.
tmp< faMatrix< Type > > SuSp (const tmp< areaScalarField > & tsp, const GeometricField< Type, faPatchField, areaMesh > & vf)
Definition at line 172 of file famSup.C.
tmp< faMatrix< scalar > > div (const edgeScalarField & flux, const GeometricField< scalar, faPatchField, areaMesh > & vf, const word & name)
Definition at line 41 of file vectorFamDiv.C.
References div(), Foam::fvc::flux(), DimensionedField< Type, GeoMesh >::mesh(), Foam::name(), convectionScheme< Type >::New(), and ref().