OpenFOAM: Foam::ensightOutput Namespace Reference
Foam::ensightOutput Namespace Reference
A collection of functions for writing ensight file content.
Namespaces
Detail
Implementation details and output backends that would not normally be called directly by a user.
Serial
Output routines that are either designed for serial-only, or for which parallelization is pending.
Functions
template<class Type >
bool writeVolField (const GeometricField< Type, fvPatchField, volMesh > &, const ensightMesh &ensMesh, ensightFile &os, const bool nodeValues=false)
Write volume field component-wise.
bool writeCloudPositions (const fvMesh &mesh, const word &cloudName, bool exists, autoPtr< ensightFile > &output, Pstream::commsTypes comm=Pstream::commsTypes::blocking)
Write cloud positions.
template<class Type >
bool writeCloudField (const IOField< Type > &field, ensightFile &os, Pstream::commsTypes comm=Pstream::commsTypes::blocking)
Write cloud field, returning true if the field is non-empty.
template<class Type >
bool writeCloudField (const IOobject &io, bool exists, autoPtr< ensightFile > &output, Pstream::commsTypes comm=Pstream::commsTypes::blocking)
Read cloud field from IOobject (if exists == true) and write, always returning true.
Detailed Description
A collection of functions for writing ensight file content.
Source files
ensightOutput.H
ensightOutputTemplates.C
Function Documentation
bool writeVolField (const GeometricField< Type, fvPatchField, volMesh > & vf, const ensightMesh & ensMesh, ensightFile & os, const bool nodeValues = false)
Write volume field component-wise.
Definition at line 283 of file ensightOutputVolFieldTemplates.C.
bool writeCloudPositions (const fvMesh & mesh, const word & cloudName, bool exists, autoPtr< ensightFile > & output, Pstream::commsTypes comm = Pstream::commsTypes::blocking)
Write cloud positions.
Definition at line 76 of file ensightOutputCloud.C.
References UList< T >::begin(), ensightFile::beginParticleCoordinates(), Foam::exists(), IOstreamOption::format(), p, List< T >::resize(), Foam::returnReduce(), UList< T >::size(), HashTable< T, Key, Hash >::size(), ensightFile::write(), and Foam::writeMeasured().
Referenced by if().
bool writeCloudField (const IOField< Type > & field, ensightFile & os, Pstream::commsTypes comm = Pstream::commsTypes::blocking)
Write cloud field, returning true if the field is non-empty.
Definition at line 28 of file ensightOutputCloudTemplates.C.
References Foam::component(), Foam::BitOps::count(), d, Foam::constant::electromagnetic::e, UList< Type >::empty(), field(), Foam::mag(), ensightFile::newline(), Foam::returnReduce(), Foam::val, ensightFile::write(), and Foam::Zero.
bool writeCloudField (const IOobject & io, bool exists, autoPtr< ensightFile > & output, Pstream::commsTypes comm = Pstream::commsTypes::blocking)
Read cloud field from IOobject (if exists == true) and write, always returning true.
Definition at line 112 of file ensightOutputCloudTemplates.C.