OpenFOAM: Foam::Elliptic Namespace Reference
Foam::Elliptic Namespace Reference
Functions
void ellipticIntegralsKE (const scalar m, scalar &K, scalar &E)
Foam::scalar JacobiAmp (const scalar u, const scalar mIn)
void JacobiSnCnDn (const scalar u, const scalar m, scalar &Sn, scalar &Cn, scalar &Dn)
Detailed Description
Function Documentation
void Foam::Elliptic::ellipticIntegralsKE (const scalar m, scalar & K, scalar & E)
Definition at line 41 of file Elliptic.H.
References g, Foam::mag(), Foam::constant::mathematical::pi(), Foam::sqrt(), and Foam::sum().
Foam::scalar Foam::Elliptic::JacobiAmp (const scalar u, const scalar mIn)
Definition at line 78 of file Elliptic.H.
void Foam::Elliptic::JacobiSnCnDn (const scalar u, const scalar m, scalar & Sn, scalar & Cn, scalar & Dn)
Definition at line 128 of file Elliptic.H.