OpenFOAM: Foam::RBD Namespace Reference
Foam::RBD Namespace Reference
Namespaces
joints
Namespace for rigid-body joints.
restraints
Namespace for rigid-body dynamics restraints.
rigidBodySolvers
Classes
class compositeBody
class cuboid
class jointBody
class masslessBody
class rigidBody
class sphere
class subBody
class joint
Abstract base-class for all rigid-body joints.
class restraint
Base class for defining restraints for rigid-body dynamics.
class rigidBodyInertia
class rigidBodyModel
Basic rigid-body model representing a system of rigid-bodies connected by 1-6 DoF joints.
class rigidBodyModelState
Holds the motion state of rigid-body model.
class rigidBodyMotion
Six degree of freedom motion for a rigid body.
class rigidBodySolver
Functions
defineTypeNameAndDebug (cuboid, 0)
addToRunTimeSelectionTable (rigidBody, cuboid, dictionary)
defineTypeNameAndDebug (jointBody, 0)
addToRunTimeSelectionTable (rigidBody, jointBody, dictionary)
defineTypeNameAndDebug (masslessBody, 0)
addToRunTimeSelectionTable (rigidBody, masslessBody, dictionary)
defineTypeNameAndDebug (rigidBody, 0)
defineRunTimeSelectionTable (rigidBody, dictionary)
addToRunTimeSelectionTable (rigidBody, rigidBody, dictionary)
Ostream & operator<< (Ostream &, const rigidBody &)
defineTypeNameAndDebug (sphere, 0)
addToRunTimeSelectionTable (rigidBody, sphere, dictionary)
defineTypeNameAndDebug (joint, 0)
defineRunTimeSelectionTable (joint, dictionary)
Ostream & operator<< (Ostream &, const joint &)
defineTypeNameAndDebug (restraint, 0)
defineRunTimeSelectionTable (restraint, dictionary)
Istream & operator>> (Istream &, rigidBodyInertia &)
Ostream & operator<< (Ostream &, const rigidBodyInertia &)
rigidBodyInertia operator+ (const rigidBodyInertia &rbi1, const rigidBodyInertia &rbi2)
Return the rigid-body inertia of the combined body.
spatialVector operator& (const rigidBodyInertia &rbi, const spatialVector &sv)
Inner-product with a spatialVector (e.g. velocity returning the momentum)
rigidBodyInertia transform (const spatialTransform &X, const rigidBodyInertia &I)
Return (^BX_A)^* I ^AX_B.
defineTypeNameAndDebug (rigidBodyModel, 0)
Ostream & operator<< (Ostream &, const rigidBodyModel &)
Istream & operator>> (Istream &, rigidBodyModelState &)
Ostream & operator<< (Ostream &, const rigidBodyModelState &)
defineTypeNameAndDebug (rigidBodySolver, 0)
defineRunTimeSelectionTable (rigidBodySolver, dictionary)
Function Documentation
Foam::RBD::defineTypeNameAndDebug (cuboid , 0)
Foam::RBD::addToRunTimeSelectionTable (rigidBody , cuboid , dictionary)
Foam::RBD::defineTypeNameAndDebug (jointBody , 0)
Foam::RBD::addToRunTimeSelectionTable (rigidBody , jointBody , dictionary)
Foam::RBD::defineTypeNameAndDebug (masslessBody , 0)
Foam::RBD::addToRunTimeSelectionTable (rigidBody , masslessBody , dictionary)
Foam::RBD::defineTypeNameAndDebug (rigidBody , 0)
Foam::RBD::defineRunTimeSelectionTable (rigidBody , dictionary)
Foam::RBD::addToRunTimeSelectionTable (rigidBody , rigidBody , dictionary)
Foam::Ostream & operator<< (Ostream & os, const rigidBody & rb) inline
Definition at line 68 of file rigidBodyI.H.
Foam::RBD::defineTypeNameAndDebug (sphere , 0)
Foam::RBD::addToRunTimeSelectionTable (rigidBody , sphere , dictionary)
Foam::RBD::defineTypeNameAndDebug (joint , 0)
Foam::RBD::defineRunTimeSelectionTable (joint , dictionary)
Foam::Ostream & operator<< (Ostream & os, const joint & j) inline
Definition at line 108 of file jointI.H.
Foam::RBD::defineTypeNameAndDebug (restraint , 0)
Foam::RBD::defineRunTimeSelectionTable (restraint , dictionary)
Foam::Istream & operator>> (Istream & is, rigidBodyInertia & rbi) inline
Definition at line 134 of file rigidBodyInertiaI.H.
Foam::Ostream & operator<< (Ostream & os, const rigidBodyInertia & rbi) inline
Definition at line 145 of file rigidBodyInertiaI.H.
rigidBodyInertia Foam::RBD::operator+ (const rigidBodyInertia & rbi1, const rigidBodyInertia & rbi2) inline
Return the rigid-body inertia of the combined body.
Definition at line 168 of file rigidBodyInertiaI.H.
References rigidBodyInertia::m().
spatialVector Foam::RBD::operator& (const rigidBodyInertia & rbi, const spatialVector & sv) inline
Inner-product with a spatialVector (e.g. velocity returning the momentum)
Definition at line 189 of file rigidBodyInertiaI.H.
rigidBodyInertia Foam::RBD::transform (const spatialTransform & X, const rigidBodyInertia & I) inline
Return (^BX_A)^* I ^AX_B.
Definition at line 209 of file rigidBodyInertiaI.H.
References rigidBodyInertia::c(), spatialTransform::E(), rigidBodyInertia::Ic(), rigidBodyInertia::m(), spatialTransform::r(), and Tensor< Cmpt >::T().
Foam::RBD::defineTypeNameAndDebug (rigidBodyModel , 0)
Foam::Ostream & operator<< (Ostream & os, const rigidBodyModel & rbm)
Definition at line 459 of file rigidBodyModel.C.
Foam::Istream & operator>> (Istream & is, rigidBodyModelState & state)
Definition at line 49 of file rigidBodyModelStateIO.C.
Foam::Ostream & operator<< (Ostream & os, const rigidBodyModelState & state)
Definition at line 66 of file rigidBodyModelStateIO.C.
Foam::RBD::defineTypeNameAndDebug (rigidBodySolver , 0)
Foam::RBD::defineRunTimeSelectionTable (rigidBodySolver , dictionary)