OpenFOAM: Foam::FieldOps Namespace Reference
Foam::FieldOps Namespace Reference
Various utility functions to work on Fields.
Functions
template<class Tout , class T1 , class UnaryOp >
void assign (Field< Tout > &result, const Field< T1 > &a, const UnaryOp &op)
Populate a field as the result of a unary operation on an input.
template<class Tout , class T1 , class T2 , class BinaryOp >
void assign (Field< Tout > &result, const Field< T1 > &a, const Field< T2 > &b, const BinaryOp &bop)
Populate a field as the result of a binary operation on two inputs.
template<class T , class BinaryOp >
void ternary (Field< T > &result, const Field< T > &a, const Field< T > &b, const BinaryOp &bop)
Emulate a ternary operation, selecting values from a or b depending on the binary predicate.
template<class T , class BoolListType , class FlipOp >
void ternarySelect (Field< T > &result, const BoolListType &cond, const Field< T > &a, const Field< T > &b, const FlipOp &flip)
Emulate a ternary operation, selecting values from a or b depending on the conditional.
template<class T , class FlipOp >
void ternarySelect (Field< T > &result, const bitSet &cond, const Field< T > &a, const Field< T > &b, const FlipOp &flip)
Emulate a ternary operation, selecting values from a or b depending on the conditional.
template<class T , class BoolListType >
void ternarySelect (Field< T > &result, const BoolListType &cond, const Field< T > &a, const Field< T > &b)
Emulated ternary operation, without condition flipping.
template<class T >
void ternarySelect (Field< T > &result, const bitSet &cond, const Field< T > &a, const Field< T > &b)
Emulated ternary operation, without condition flipping.
template<class T1 , class T2 >
Tuple2< T1, T2 > findMinData (const Field< T1 > &vals, const Field< T2 > &data)
Locate the min value in a field and return it and associated data.
template<class T1 , class T2 >
Tuple2< T1, T2 > findMaxData (const Field< T1 > &vals, const Field< T2 > &data)
Locate the max value in a field and return it and associated data.
template<class Tout , class T1 , class UnaryOp , template< class > class PatchField, class GeoMesh >
void assign (GeometricField< Tout, PatchField, GeoMesh > &result, const GeometricField< T1, PatchField, GeoMesh > &a, const UnaryOp &op)
Populate a geometric field as the result of a unary operation on an input.
template<class Tout , class T1 , class T2 , class BinaryOp , template< class > class PatchField, class GeoMesh >
void assign (GeometricField< Tout, PatchField, GeoMesh > &result, const GeometricField< T1, PatchField, GeoMesh > &a, const GeometricField< T2, PatchField, GeoMesh > &b, const BinaryOp &bop)
Populate a geometric field from the binary operation on two inputs.
template<class T , class BinaryOp , template< class > class PatchField, class GeoMesh >
void ternary (GeometricField< T, PatchField, GeoMesh > &result, const GeometricField< T, PatchField, GeoMesh > &a, const GeometricField< T, PatchField, GeoMesh > &b, const BinaryOp &bop)
Emulate a ternary operation, selecting values from a or b depending on the binary predicate.
template<class T , class BoolType , class FlipOp , template< class > class PatchField, class GeoMesh >
void ternarySelect (GeometricField< T, PatchField, GeoMesh > &result, const GeometricField< BoolType, PatchField, GeoMesh > &cond, const GeometricField< T, PatchField, GeoMesh > &a, const GeometricField< T, PatchField, GeoMesh > &b, const FlipOp &flip)
Emulate a ternary operation, selecting field values from a or b depending on the conditional.
template<class Tout , class T1 , class UnaryOp >
void assign (pointPatchField< Tout > &result, const pointPatchField< T1 > &a, const UnaryOp &op)
template<class Tout , class T1 , class T2 , class BinaryOp >
void assign (pointPatchField< Tout > &result, const pointPatchField< T1 > &a, const pointPatchField< T2 > &b, const BinaryOp &bop)
template<class T , class BinaryOp >
void ternary (pointPatchField< T > &result, const pointPatchField< T > &a, const pointPatchField< T > &b, const BinaryOp &bop)
template<class T , class BoolType , class FlipOp >
void ternarySelect (pointPatchField< T > &result, const pointPatchField< BoolType > &cond, const pointPatchField< T > &a, const pointPatchField< T > &b, const FlipOp &flip)
Detailed Description
Various utility functions to work on Fields.
Source files
FieldOps.H
FieldOps.C
Function Documentation
void assign (Field< Tout > & result, const Field< T1 > & a, const UnaryOp & op)
Populate a field as the result of a unary operation on an input.
It is permissible for inputs/outputs to refer to the same field(s), but partially overlapping regions are ill-defined.
Examples,
*   boolField result(sfield1.size());
*
*   FieldOps::assign(result, sfield1, lessOp1<scalar>(0.5));
*   FieldOps::assign(result, lfield1, std::logical_not<bool>());
*
Example of using the Random::uniformGeneratorOp unary operator to populate a random field,
*   FieldOps::assign
*   (
*       sfield,
*       sfield,
*       Random::uniformGeneratorOp<scalar>(-15, 25)
*);
*
Note
wraps std::transform
Definition at line 28 of file FieldOps.C.
References Foam::abort(), Foam::FatalError, FatalErrorInFunction, Foam::nl, and UList< Type >::size().
Referenced by assign(), bitSet::bitSet(), exprDriver::fill_random(), labelledTri::labelledTri(), word::operator=(), keyType::operator=(), wordRe::operator=(), fileName::operator=(), PackedList< Width >::operator=(), wordRe::set(), parseDriver::setInternalFieldResult(), and wordRe::swap().
void assign (Field< Tout > & result, const Field< T1 > & a, const Field< T2 > & b, const BinaryOp & bop)
Populate a field as the result of a binary operation on two inputs.
It is permissible for inputs/outputs to refer to the same field(s), but partially overlapping regions are ill-defined.
Examples,
*   FieldOps::assign(result, sfield1, sfield2, std::less<scalar>());
*   FieldOps::assign(result, lfield1, lfield2, std::logical_or<bool>());
*
Note
wraps std::transform
Definition at line 50 of file FieldOps.C.
void ternary (Field< T > & result, const Field< T > & a, const Field< T > & b, const BinaryOp & bop)
Emulate a ternary operation, selecting values from a or b depending on the binary predicate.
Examples,
*   FieldOps::ternary(result, sfield1, sfield2, std::less<scalar>());
*
Definition at line 73 of file FieldOps.C.
Referenced by ternary().
void ternarySelect (Field< T > & result, const BoolListType & cond, const Field< T > & a, const Field< T > & b, const FlipOp & flip)
Emulate a ternary operation, selecting values from a or b depending on the conditional.
The meaning of the conditional is adjusted by the flip operation, which is typically Foam::noOp() or Foam::flipBoolOp()
Similar parameter requirements as Foam::subset()
Examples,
*   FieldOps::ternarySelect(result, selector, sfield1, sfield2);
*
Definition at line 99 of file FieldOps.C.
Referenced by ternarySelect().
void ternarySelect (Field< T > & result, const bitSet & cond, const Field< T > & a, const Field< T > & b, const FlipOp & flip)
Emulate a ternary operation, selecting values from a or b depending on the conditional.
The meaning of the conditional is adjusted by the flip operation, which is typically Foam::noOp() or Foam::flipBoolOp()
Definition at line 126 of file FieldOps.C.
void Foam::FieldOps::ternarySelect (Field< T > & result, const BoolListType & cond, const Field< T > & a, const Field< T > & b)
Emulated ternary operation, without condition flipping.
Definition at line 181 of file FieldOps.H.
References ternarySelect().
void Foam::FieldOps::ternarySelect (Field< T > & result, const bitSet & cond, const Field< T > & a, const Field< T > & b)
Emulated ternary operation, without condition flipping.
Definition at line 197 of file FieldOps.H.
Tuple2<T1,T2> Foam::FieldOps::findMinData (const Field< T1 > & vals, const Field< T2 > & data)
Locate the min value in a field and return it and associated data.
This can be used, for example, to return a value/position combination.
Referenced by exprDriver::getPositionOfMaximum().
Tuple2<T1,T2> Foam::FieldOps::findMaxData (const Field< T1 > & vals, const Field< T2 > & data)
Locate the max value in a field and return it and associated data.
This can be used, for example, to return a value/position combination.
void Foam::FieldOps::assign (GeometricField< Tout, PatchField, GeoMesh > & result, const GeometricField< T1, PatchField, GeoMesh > & a, const UnaryOp & op)
Populate a geometric field as the result of a unary operation on an input.
It is permissible for inputs/outputs to refer to the same field(s), but partially overlapping regions are ill-defined.
Definition at line 62 of file GeometricFieldOps.H.
References assign(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), i, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
void Foam::FieldOps::assign (GeometricField< Tout, PatchField, GeoMesh > & result, const GeometricField< T1, PatchField, GeoMesh > & a, const GeometricField< T2, PatchField, GeoMesh > & b, const BinaryOp & bop)
Populate a geometric field from the binary operation on two inputs.
It is permissible for inputs/outputs to refer to the same field(s), but partially overlapping regions are ill-defined.
Definition at line 103 of file GeometricFieldOps.H.
References assign(), GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), i, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), and GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef().
void Foam::FieldOps::ternary (GeometricField< T, PatchField, GeoMesh > & result, const GeometricField< T, PatchField, GeoMesh > & a, const GeometricField< T, PatchField, GeoMesh > & b, const BinaryOp & bop)
Emulate a ternary operation, selecting values from a or b depending on the binary predicate.
Definition at line 145 of file GeometricFieldOps.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), i, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and ternary().
void Foam::FieldOps::ternarySelect (GeometricField< T, PatchField, GeoMesh > & result, const GeometricField< BoolType, PatchField, GeoMesh > & cond, const GeometricField< T, PatchField, GeoMesh > & a, const GeometricField< T, PatchField, GeoMesh > & b, const FlipOp & flip)
Emulate a ternary operation, selecting field values from a or b depending on the conditional.
Since boolean fields are not normally used, a flip operation is a general requirement.
Definition at line 191 of file GeometricFieldOps.H.
References GeometricField< Type, PatchField, GeoMesh >::boundaryField(), GeometricField< Type, PatchField, GeoMesh >::boundaryFieldRef(), i, GeometricField< Type, PatchField, GeoMesh >::primitiveField(), GeometricField< Type, PatchField, GeoMesh >::primitiveFieldRef(), and ternarySelect().
void Foam::FieldOps::assign (pointPatchField< Tout > & result, const pointPatchField< T1 > & a, const UnaryOp & op) inline
Definition at line 367 of file pointPatchFieldFunctions.H.
References assign().
void Foam::FieldOps::assign (pointPatchField< Tout > & result, const pointPatchField< T1 > & a, const pointPatchField< T2 > & b, const BinaryOp & bop) inline
Definition at line 377 of file pointPatchFieldFunctions.H.
void Foam::FieldOps::ternary (pointPatchField< T > & result, const pointPatchField< T > & a, const pointPatchField< T > & b, const BinaryOp & bop) inline
Definition at line 387 of file pointPatchFieldFunctions.H.
void Foam::FieldOps::ternarySelect (pointPatchField< T > & result, const pointPatchField< BoolType > & cond, const pointPatchField< T > & a, const pointPatchField< T > & b, const FlipOp & flip) inline
Definition at line 397 of file pointPatchFieldFunctions.H.