OpenFOAM: applications/solvers/combustion/PDRFoam/bEqn.H File Reference
bEqn.H File Reference
Functions
tmp< fv::convectionScheme
< scalar > > mvConvection (fv::convectionScheme< scalar >::New(mesh, fields, phi, mesh.divScheme("div(phi,ft_b_ha_hau)")))
volScalarField Db ("Db", turbulence->muEff())
volScalarField c ("c", 1.0-b)
volScalarField rhou (thermo.rhou())
volVectorField n (fvc::reconstruct(fvc::snGrad(b)*mesh.magSf()))
volScalarField mgb ("mgb", mag(n))
dimensionedScalar dMgb ("dMgb", mgb.dimensions(), SMALL)
surfaceVectorField Sfhat (mesh.Sf()/mesh.magSf())
surfaceVectorField nfVec (fvc::interpolate(n))
surfaceScalarField nf ("nf", mesh.Sf()&nfVec)
surfaceScalarField phiSt ("phiSt", fvc::interpolate(rhou *StCorr *St)*nf)
Info<< "St courant Number
mean: "<< meanStCoNum<< " max: "
<< StCoNum<< endl;}#63"/home/pengfei/OpenFOAM/OpenFOAM-v1912/applications/solvers/combustion/PDRFoam/bEqn.H"2
Db=flameWrinkling-> Db ()
fvScalarMatrix bEqn (betav *fvm::ddt(rho, b)+mvConvection->fvmDiv(phi, b)+fvm::div(phiSt, b)-fvm::Sp(fvc::div(phiSt), b)-fvm::laplacian(Db, b)==betav *fvOptions(rho, b))
bEqn relax ()
fvOptions constrain (bEqn)
bEqn solve ()
fvOptions correct (b)
Info<< "min(b) = "<< min(b).value()
<< endl;{volScalarField &ft=composition.Y("ft");Info
<< "Combustion progress = "
<< 100 *(1.0-b)().weightedAverage(mesh.V()*ft).value()
<< "%"<< endl;}else{Info
<< "Combustion progress = "
<< 100 *(1.0-b)().weightedAverage(mesh.V()).value()
<< "%"<< endl;}flameWrinkling-> correct (mvConvection)
Variables
const volScalarField & Xi = flameWrinkling->Xi()
dMgb
mgb = dMgb
nfVec = Sfhat*(fvc::snGrad(b) - (Sfhat & nfVec))
n = mgb
StCoNum = 0.5*gMax(sumPhi/mesh.V().field())*runTime.deltaTValue()
meanStCoNum
St = Xi*Su
Function Documentation
tmp<fv::convectionScheme<scalar> > mvConvection (fv::convectionScheme< scalar >:: Newmesh, fields, phi, mesh.divScheme("div(phi,ft_b_ha_hau)"))
volScalarField Db ("Db" , turbulence-> muEff())
volScalarField c ("c" , 1.0- b)
Referenced by stdFoam::begin(), stdFoam::cbegin(), stdFoam::cend(), quadraticEqn::derivative(), cubicEqn::derivative(), stdFoam::end(), cubicEqn::error(), Foam::getSTLpoint(), Foam::HasherDual(), Foam::HasherInt(), Foam::interpolate(), Foam::isTriCut(), Smagorinsky< BasicTurbulenceModel >::k(), Foam::mapClouds(), Moment< Type >::Moment(), FallOffReactionRate< ReactionRate, FallOffFunction >::operator()(), ChemicallyActivatedReactionRate< ReactionRate, ChemicallyActivationFunction >::operator()(), Circulator< ContainerType >::operator*(), ConstCirculator< ContainerType >::operator*(), complex::operator*=(), Foam::operator-(), complex::operator/=(), Foam::operator>>(), countstreambuf::overflow(), stdFoam::rbegin(), Foam::ReadHex(), Foam::readHexDigit(), Foam::Rx(), Foam::Ry(), Foam::sign(), SVD::SVD(), swapec(), tetPoints::tetPoints(), Foam::transform(), triFace::triFace(), triPoints::triPoints(), regIOobject::upToDate(), fileName::validate(), thirdBodyArrheniusReactionRate::write(), and zoneMotion::zoneMotion().
volScalarField rhou (thermo. rhou())
volVectorField n (fvc:: reconstructfvc::snGrad(b)*mesh.magSf())
volScalarField mgb ("mgb" , mag(n))
dimensionedScalar dMgb ("dMgb" , mgb. dimensions(), SMALL)
surfaceVectorField Sfhat (mesh. Sf)/mesh.magSf()
surfaceVectorField nfVec (fvc:: interpolaten)
surfaceScalarField nf ("nf" , mesh.Sf()& nfVec)
Referenced by primitiveMeshGeometry::checkFaceTwist(), forAll(), skewCorrectedSnGrad< Type >::fullGradCorrection(), faceCorrectedSnGrad< Type >::fullGradCorrection(), and fvPatch::makeWeights().
surfaceScalarField phiSt ("phiSt" , fvc::interpolate(rhou *StCorr *St)* nf)
Info<< "St courant Number mean: " << meanStCoNum << " max: " << StCoNum << endl;}# 63 "/home/pengfei/OpenFOAM/OpenFOAM-v1912/applications/solvers/combustion/PDRFoam/bEqn.H" 2 Db = flameWrinkling-> Db ()
fvScalarMatrix bEqn (betav *fvm:: ddtrho, b)+mvConvection->fvmDiv(phi, b)+fvm::div(phiSt, b)-fvm::Sp(fvc::div(phiSt), b)-fvm::laplacian(Db, b = =betav *fvOptions(rho, b))
bEqn relax ()
fvOptions constrain (bEqn)
bEqn solve ()
fvOptions correct (b)
Info<< "min(b) = " << min(b).value() << endl; { volScalarField& ft = composition.Y("ft"); Info<< "Combustion progress = " << 100*(1.0 - b)().weightedAverage(mesh.V()*ft).value() << "%" << endl; } else { Info<< "Combustion progress = " << 100*(1.0 - b)().weightedAverage(mesh.V()).value() << "%" << endl; } flameWrinkling-> correct (mvConvection)
Variable Documentation
const volScalarField& Xi = flameWrinkling->Xi()
Definition at line 20 of file bEqn.H.
dMgb
Initial value:
= 1.0e-3*
            (bc*mgb)().weightedAverage(mesh.V())
           /(bc.weightedAverage(mesh.V()) + SMALL)
Definition at line 43 of file bEqn.H.
mgb = dMgb
Definition at line 48 of file bEqn.H.
nfVec = Sfhat*(fvc::snGrad(b) - (Sfhat & nfVec))
Definition at line 52 of file bEqn.H.
n = mgb
Definition at line 55 of file bEqn.H.
StCoNum = 0.5*gMax(sumPhi/mesh.V().field())*runTime.deltaTValue()
Definition at line 37 of file bEqn.H.
Referenced by if().
meanStCoNum
Initial value:
=
            0.5*(gSum(sumPhi)/gSum(mesh.V().field()))*runTime.deltaTValue()
Definition at line 39 of file bEqn.H.
St = Xi*Su
Definition at line 100 of file bEqn.H.