OpenFOAM: applications/solvers/combustion/chemFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading initial conditions.\n"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=initialConditions.get< scalar > ("p")
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< psiReactionThermo > pThermo (psiReactionThermo::New(mesh))
thermo validate (args.executable(),"h")
autoPtr< BasicChemistryModel
< psiReactionThermo > > pChemistry (BasicChemistryModel< psiReactionThermo >::New(thermo))
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), mesh,)
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh,)
OFstream post (args.path()/"chemFoam.out")
Variables
scalar T0 = initialConditions.get<scalar>("T")
psiReactionThermo & thermo = pThermo()
Function Documentation
Info<< "Reading initial conditions.\n"<< endl;IOdictionary initialConditions(IOobject("initialConditions", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));scalar p0=initialConditions.get< scalar > ("p")
Info<< "Reading thermophysical properties\n" << endl; autoPtr<psiReactionThermo> pThermo (psiReactionThermo:: Newmesh)
thermo validate (args. executable(), "h")
autoPtr<BasicChemistryModel<psiReactionThermo> > pChemistry (BasicChemistryModel< psiReactionThermo >:: Newthermo)
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
volScalarField Rspecific (IOobject("Rspecific", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , mesh)
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh)
OFstream post (args.path()/"chemFoam.out")
Variable Documentation
scalar T0 = initialConditions.get<scalar>("T")
Definition at line 22 of file createFields.H.
Referenced by ReactingHeterogeneousParcel< ParcelType >::calc(), if(), and sensibleInternalEnergy< Thermo >::THE().
psiReactionThermo& thermo = pThermo()
Definition at line 28 of file createFields.H.
Referenced by TDACChemistryModel< CompType, ThermoType >::active(), StationaryPhaseModel< BasePhaseModel >::alphaEff(), LiquidEvaporation< CloudType >::calcXc(), LiquidEvaporationBoil< CloudType >::calcXc(), phaseSystem::correctThermo(), diffusion< ReactionThermo, ThermoType >::diffusion(), eddyDissipationModelBase< ReactionThermo, ThermoType >::eddyDissipationModelBase(), forAll(), FSD< ReactionThermo, ThermoType >::FSD(), if(), infinitelyFastChemistry< ReactionThermo, ThermoType >::infinitelyFastChemistry(), StationaryPhaseModel< BasePhaseModel >::k(), StationaryPhaseModel< BasePhaseModel >::kappaEff(), combustionModel::New(), CombustionModel< ReactionThermo >::New(), basicSolidChemistryModel::New(), StationaryPhaseModel< BasePhaseModel >::nut(), TDACChemistryModel< CompType, ThermoType >::setNsDAC(), and singleStepCombustion< ReactionThermo, ThermoType >::singleStepCombustion().