OpenFOAM: applications/solvers/combustion/fireFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< psiReactionThermo > pThermo (psiReactionThermo::New(mesh))
thermo validate (args.executable(),"h","e")
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.get< word >("inertSpecie"))
if (!composition.species().found(inertSpecie))
Info<< "Creating field rho\n"
<< endl;volScalarField rho(IOobject("rho",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE),
thermo.rho());volScalarField
&p=thermo.p();Info
<< "\nReading field U\n"
<< endl;volVectorField U(IOobject("U",
runTime.timeName(), mesh,
IOobject::MUST_READ,
IOobject::AUTO_WRITE), mesh);Info
<< "Creating turbulence
model\n"<< endl;autoPtr
< compressible::turbulenceModel > turbulence (compressible::turbulenceModel::New(rho, U, phi, thermo))
Info<< "Creating combustion
model\n"<< endl;autoPtr
< CombustionModel
< psiReactionThermo > > combustion (CombustionModel< psiReactionThermo >::New(thermo, turbulence()))
volScalarField p_rgh (IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh)
mesh setFluxRequired (p_rgh.name())
forAll (Y, i)
fields add (thermo.he())
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), mesh,)
Variables
psiReactionThermo & thermo = pThermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
multivariateSurfaceInterpolationScheme
< scalar >::fieldTable fields
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiReactionThermo> pThermo (psiReactionThermo:: Newmesh)
thermo validate (args. executable(), "h" , "e")
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo.get< word > "inertSpecie")
Referenced by if(), and MultiComponentPhaseModel< BasePhaseModel >::MultiComponentPhaseModel().
if (!composition. species).found(inertSpecie)
Definition at line 12 of file createFields.H.
References args, argList::executable(), Foam::exit(), Foam::FatalIOError, FatalIOErrorIn, inertSpecie(), and thermo.
Info<< "Creating field rho\n" << endl;volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volScalarField& p = thermo.p();Info<< "\nReading field U\n" << endl;volVectorField U(IOobject ("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh);Info<< "Creating turbulence model\n" << endl;autoPtr<compressible::turbulenceModel> turbulence (compressible::turbulenceModel:: Newrho, U, phi, thermo)
Info<< "Creating combustion model\n" << endl;autoPtr<CombustionModel<psiReactionThermo> > combustion (CombustionModel< psiReactionThermo >:: Newthermo, turbulence())
Referenced by forAll().
volScalarField p_rgh (IOobject("p_rgh", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE) , mesh)
mesh setFluxRequired (p_rgh. name())
forAll (Y , i)
Definition at line 99 of file createFields.H.
References i.
fields add (thermo. he())
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE) , mesh)
Variable Documentation
psiReactionThermo& thermo = pThermo()
Definition at line 3 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 8 of file createFields.H.
PtrList<volScalarField>& Y = composition.Y()
Definition at line 9 of file createFields.H.
multivariateSurfaceInterpolationScheme<scalar>::fieldTable fields
Definition at line 97 of file createFields.H.
Referenced by fieldSelection::containsPattern(), Foam::MapConsistentVolFields(), Foam::MapDimensionedFields(), Foam::MapGeometricFields(), Foam::MapLagrangianFields(), Foam::MapVolFields(), and Foam::UnMapped().