OpenFOAM: src/engine/include/StCorr.H File Reference
StCorr.H File Reference
Functions
dimensionedScalar StCorr ("StCorr", dimless, 1.0)
dimensionedScalar Ak ("Ak", dimArea, Zero)
StCorr value ()
Variables
dimensionedScalar AkEst = gSum(mgb*mesh.V().field())
Function Documentation
dimensionedScalar StCorr ("StCorr" , dimless , 1. 0)
dimensionedScalar Ak ("Ak" , dimArea , Zero)
StCorr value ()
Referenced by fieldAverage::addMeanFieldType(), Foam::allReduce(), averageCondition::calc(), veryInhomogeneousMixture< ThermoType >::cellProducts(), Pstream::combineGather(), ConstPrecisionAdaptor< Type, InputType, Container >::ConstPrecisionAdaptor(), kinematicSingleLayer::constrainFilmField(), diaedg(), scalars::falseOp(), Cole::fDeparture(), Foam::functionObjects::runTimeControls::minMaxCondition::setValue< Foam::scalar >(), forAll(), Pstream::gather(), Foam::getVariable(), ReactingHeterogeneousParcel< ParcelType >::constantProperties::hRetentionCoeff(), i_modp(), i_wrap(), if(), Ostream::indentLevel(), lrline(), always::match(), DSMCCloud< ParcelType >::maxwellianRMSSpeed(), PatchFunction1< Type >::New(), ifEqEqOp< value >::operator()(), always::operator()(), never::operator()(), labelRange::operator++(), sweepData::operator==(), smoothData::operator==(), labelRange::operator[](), veryInhomogeneousMixture< ThermoType >::patchFaceReactants(), FIRECore::putFireLabels(), zoltanRenumber::renumber(), lineSearch::reset(), cpuTimeCxx::resetCpuTime(), Random::sample01(), fvMatrix< Type >::setComponentReference(), updateMethod::setConstraintValues(), quadratic::setOldMeritValue(), lineSearch::setOldMeritValue(), Time::stopAt(), Foam::Swap(), scalars::trueOp(), freePiston::unit(), crankConRod::unit(), PatchCollisionDensity< CloudType >::write(), lagrangianWriter::write(), vtkCloud::writeFields(), fileWriter::writeUniform(), and nastranWriter::writeValue().
Variable Documentation
dimensionedScalar AkEst = gSum(mgb*mesh.V().field())
Definition at line 81 of file StCorr.H.