OpenFOAM: Patch Struct Reference
Patch Struct Reference
Convert OpenFOAM patch to vtkPolyData.
Static Public Member Functions
template<class PatchType >
static vtkSmartPointer< vtkPoints > points (const PatchType &p)
Return local patch points as vtkPoints.
template<class PatchType >
static vtkSmartPointer
< vtkCellArray > faces (const PatchType &p)
Convert patch faces to vtk polygon cells.
template<class PatchType >
static vtkSmartPointer
< vtkPolyData > mesh (const PatchType &p)
Convert patch points/faces to vtkPolyData.
template<class PatchType >
static vtkSmartPointer
< vtkFloatArray > faceNormals (const PatchType &p)
Convert patch face normals to vtkFloatArray.
template<class PatchType >
static vtkSmartPointer< vtkPoints > faceCentres (const PatchType &p)
Return patch face centres as vtkPoints.
template<class Face >
static vtkSmartPointer
< vtkPolyData > mesh (const UList< point > &pts, const UList< Face > &fcs)
Convert points/faces component to vtkPolyData.
Detailed Description
Convert OpenFOAM patch to vtkPolyData.
Definition at line 267 of file foamVtkTools.H.
Member Function Documentation
vtkSmartPointer< vtkPoints > points (const PatchType & p) static
Return local patch points as vtkPoints.
Definition at line 68 of file foamVtkToolsTemplates.C.
vtkSmartPointer< vtkCellArray > faces (const PatchType & p) static
Convert patch faces to vtk polygon cells.
Definition at line 77 of file foamVtkToolsTemplates.C.
vtkSmartPointer< vtkPolyData > mesh (const PatchType & p) static
Convert patch points/faces to vtkPolyData.
Definition at line 85 of file foamVtkToolsTemplates.C.
References Foam::vtk::Tools::Faces().
Referenced by geometryPatches::gatherPatchPieces(), and surface::gatherSurfacePieces().
vtkSmartPointer< vtkFloatArray > faceNormals (const PatchType & p) static
Convert patch face normals to vtkFloatArray.
Definition at line 115 of file foamVtkToolsTemplates.C.
vtkSmartPointer< vtkPoints > faceCentres (const PatchType & p) static
Return patch face centres as vtkPoints.
Definition at line 149 of file foamVtkToolsTemplates.C.
vtkSmartPointer< vtkPolyData > mesh (const UList< point > & pts, const UList< Face > & fcs) static
Convert points/faces component to vtkPolyData.
Definition at line 99 of file foamVtkToolsTemplates.C.
The documentation for this struct was generated from the following files:
src/conversion/vtk/adaptor/foamVtkTools.H
src/conversion/vtk/adaptor/foamVtkToolsTemplates.C