OpenFOAM: LList< LListBase, T >::link Struct Reference
LList< LListBase, T >::link Struct Reference
The storage of T with linked nodes.
Public Member Functions
link (const T &obj)
Copy construct from given object.
link (T &&obj)
Move construct from given object.
Static Public Member Functions
static constexpr T * ptr (typename LListBase::link *node)
Dereference LListBase::link to obtain address of stored object.
static constexpr const T * ptr (const typename LListBase::link *node)
Dereference LListBase::link to obtain address of stored object.
static constexpr T & ref (typename LListBase::link *node)
Dereference LListBase::link to obtain the stored object.
static constexpr const T & ref (const typename LListBase::link *node)
Dereference LListBase::link to obtain the stored object.
Public Attributes
T obj_
Stored object.
Detailed Description
template<class LListBase, class T>
struct Foam::LList< LListBase, T >::link
The storage of T with linked nodes.
Definition at line 128 of file LList.H.
Constructor & Destructor Documentation
link (const T & obj) inline
Copy construct from given object.
Definition at line 140 of file LList.H.
link (T && obj) inline
Move construct from given object.
Definition at line 148 of file LList.H.
References LList< LListBase, T >::link::obj_.
Member Function Documentation
static constexpr T* ptr (typename LListBase::link * node) inline static
Dereference LListBase::link to obtain address of stored object.
Definition at line 157 of file LList.H.
References LList< LListBase, T >::link::obj_.
Referenced by LList< LListBase, T >::const_iterator::operator*(), and LList< LListBase, T >::iterator::operator++().
static constexpr const T* ptr (const typename LListBase::link * node) inline static
Dereference LListBase::link to obtain address of stored object.
Definition at line 165 of file LList.H.
References LList< LListBase, T >::insert().
static constexpr T& ref (typename LListBase::link * node) inline static
Dereference LListBase::link to obtain the stored object.
Definition at line 173 of file LList.H.
References LList< LListBase, T >::insert().
Referenced by LList< LListBase, T >::const_iterator::const_iterator(), LList< Foam::chemPointISAT< CompType, ThermoType > * >::first(), LList< Foam::chemPointISAT< CompType, ThermoType > * >::last(), LList< Foam::chemPointISAT< CompType, ThermoType > * >::LList(), and LList< LListBase, T >::iterator::operator()().
static constexpr const T& ref (const typename LListBase::link * node) inline static
Dereference LListBase::link to obtain the stored object.
Definition at line 181 of file LList.H.
Member Data Documentation
T obj_
Stored object.
Definition at line 135 of file LList.H.
Referenced by LList< LListBase, T >::link::link(), and LList< LListBase, T >::link::ptr().
The documentation for this struct was generated from the following file:
src/OpenFOAM/containers/LinkedLists/accessTypes/LList/LList.H