OpenFOAM: always Struct Reference
always Struct Reference
Unary and binary predicates that always return true, useful for templating.
Public Member Functions
template<class T >
constexpr bool operator() (const T &) const noexcept
Unary predicate.
template<class T1 , class T2 >
constexpr bool operator() (const T1 &, const T2 &) const noexcept
Binary predicate.
constexpr bool match (const std::string &, bool literal=false) const noexcept
String match.
Detailed Description
Unary and binary predicates that always return true, useful for templating.
Definition at line 54 of file predicates.H.
Member Function Documentation
constexpr bool operator() (const T &) const inline noexcept
Unary predicate.
Returns
true
Definition at line 62 of file predicates.H.
References value().
constexpr bool operator() (const T1 & , const T2 &) const inline noexcept
Binary predicate.
Returns
true
Definition at line 73 of file predicates.H.
References value().
constexpr bool match (const std::string & , bool literal = false) const inline noexcept
String match.
Returns
true
Definition at line 83 of file predicates.H.
References never::operator()(), Foam::T(), and value().
The documentation for this struct was generated from the following file:
src/OpenFOAM/primitives/predicates/predicates.H