OpenFOAM: applications/utilities/postProcessing/miscellaneous/pdfPlot/createFields.H File Reference
createFields.H File Reference
Functions
IOdictionary pdfDictionary (IOobject("pdfDict", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
const label nIntervals (pdfDictionary.get< label >("nIntervals"))
const label nSamples (pdfDictionary.get< label >("nSamples"))
const bool writeData (pdfDictionary.get< bool >("writeData"))
mkDir (pdfPath)
autoPtr< distributionModel > p (distributionModel::New(pdfDictionary, rndGen))
if (writeData)
scalarField samples (nIntervals, Zero)
Variables
const fileName pdfPath = runTime.path()/"pdf"
Random rndGen
const scalar xMin = p->minValue()
const scalar xMax = p->maxValue()
autoPtr< OFstream > filePtr
Function Documentation
IOdictionary pdfDictionary (IOobject("pdfDict", runTime.constant(), runTime, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE))
const label nIntervals (pdfDictionary.get< label > "nIntervals")
const label nSamples (pdfDictionary.get< label > "nSamples")
Referenced by windowModel::validate().
const bool writeData (pdfDictionary.get< bool > "writeData")
mkDir (pdfPath)
autoPtr<distributionModel> p (distributionModel:: NewpdfDictionary, rndGen)
if (writeData)
Definition at line 38 of file createFields.H.
References Foam::endl(), Foam::Info, Foam::nl, and p.
scalarField samples (nIntervals , Zero)
Referenced by mappedPatchBase::calcMapping(), and TableBase< Type >::interpolator().
Variable Documentation
const fileName pdfPath = runTime.path()/"pdf"
Definition at line 20 of file createFields.H.
Random rndGen
Definition at line 23 of file createFields.H.
Referenced by meshSearch::boundaryTree(), meshSearch::cellTree(), InjectedParticleDistributionInjection< CloudType >::initialise(), InjectedParticleDistributionInjection< CloudType >::InjectedParticleDistributionInjection(), distributionModel::New(), and while().
const scalar xMin = p->minValue()
Definition at line 34 of file createFields.H.
const scalar xMax = p->maxValue()
Definition at line 35 of file createFields.H.
autoPtr<OFstream> filePtr
Definition at line 37 of file createFields.H.