OpenFOAM: src/renumber/zoltanRenumber/zoltanRenumber.C File Reference
zoltanRenumber.C File Reference
Namespaces
Foam
Namespace for OpenFOAM.
Functions
defineTypeNameAndDebug (zoltanRenumber, 0)
addToRunTimeSelectionTable (renumberMethod, zoltanRenumber, dictionary)
static int get_number_of_vertices (void *data, int *ierr)
static void get_vertex_list (void *data, int sizeGID, int sizeLID, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int wgt_dim, float *obj_wgts, int *ierr)
static void get_num_edges_list (void *data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int *numEdges, int *ierr)
static void get_edge_list (void *data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int *num_edges, ZOLTAN_ID_PTR nborGID, int *nborProc, int wgt_dim, float *ewgts, int *ierr)
static int get_mesh_dim (void *data, int *ierr)
static void get_geom_list (void *data, int num_gid_entries, int num_lid_entries, int num_obj, ZOLTAN_ID_PTR global_ids, ZOLTAN_ID_PTR local_ids, int num_dim, double *geom_vec, int *ierr)
Detailed Description
Original source file zoltanRenumber.C
Definition in file zoltanRenumber.C.
Function Documentation
static int get_number_of_vertices (void * data, int * ierr) static
Definition at line 76 of file zoltanRenumber.C.
Referenced by zoltanRenumber::renumber().
static void get_vertex_list (void * data, int sizeGID, int sizeLID, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int wgt_dim, float * obj_wgts, int * ierr) static
Definition at line 84 of file zoltanRenumber.C.
Referenced by zoltanRenumber::renumber().
static void get_num_edges_list (void * data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int * numEdges, int * ierr) static
Definition at line 107 of file zoltanRenumber.C.
Referenced by zoltanRenumber::renumber().
static void get_edge_list (void * data, int sizeGID, int sizeLID, int num_obj, ZOLTAN_ID_PTR globalID, ZOLTAN_ID_PTR localID, int * num_edges, ZOLTAN_ID_PTR nborGID, int * nborProc, int wgt_dim, float * ewgts, int * ierr) static
Definition at line 139 of file zoltanRenumber.C.
Referenced by zoltanRenumber::renumber().
static int get_mesh_dim (void * data, int * ierr) static
Definition at line 199 of file zoltanRenumber.C.
Referenced by zoltanRenumber::renumber().
static void get_geom_list (void * data, int num_gid_entries, int num_lid_entries, int num_obj, ZOLTAN_ID_PTR global_ids, ZOLTAN_ID_PTR local_ids, int num_dim, double * geom_vec, int * ierr) static
Definition at line 208 of file zoltanRenumber.C.
Referenced by zoltanRenumber::renumber().